### ISSUE TITLE
⚠️⚠️ Do NOT open PRs for new features ⚠️⚠️

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#10003]
Please do **not** open pull requests for *new features* now, as we are planning to rewrite large chunks of the code. Only bugfix PRs will be accepted. More details will be announced soon!

**Comment by papb** [comment]
Can you make an exception for the already existing PR #9937 which finally implements a highly-desired feature (#5854) requested for over two years, and hopefully merge it before the large code rewrite, so that the contributor avoids rebase conflicts?

**Comment by Stypox** [comment]
Yes, that's exactly the point. Existing PRs that add big features will be merged into 0.26.0, while new PRs won't be accepted for some time. We'll release a blogpost explaining our plan soon.

**Comment by hollownights** [comment]
Yes, it would be great to finally have #9182 merged into NewPipe.

**Comment by LavHinsu** [comment]
Is there any open project page like a scrum board for planned features?

**Comment by Stypox** [comment]
https://github.com/orgs/TeamNewPipe/projects/14/views/1

**Comment by Stypox** [comment]
Here is the announcement, as promised :-)
https://github.com/TeamNewPipe/NewPipe/discussions/10118
