### ISSUE TITLE
(0.11.4) Incorrect Video List Loading

### ISSUE THREAD

**Issue by tonkou-roi** [TeamNewPipe/NewPipe#1000]
Newpipe will load perpetually load the second series of videos on a channel page instead of the videos that follow it.

For a channel of Videos A-P, where each load displays 4 more videos, Newpipe will display:

A B C D, E F G H, E F G H, E F G H(...)

instead of:

A B C D, E F G H, I J K L, M N O P

**Comment by coffeemakr** [comment]
Hi this seems to be the same issue as #990. I assume that it's fixed in the next release.
