### ISSUE TITLE
Playlists for downloaded files

### ISSUE THREAD

**Issue by logcatdog** [TeamNewPipe/NewPipe#10023]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like to be able to create playlists from the 'downloads' section. I download everything in 160k opus file format, and would love if i could just use newpipe as an offline player too. You can play the file from the downloads section, but i dont see a way to make a playlist from anything inside the downloads section.

### Why do you want this feature?

I download everything in 160k opus file format, and would love if i could just use newpipe as an offline player too. I've tried long pressing the .opus file in the downloads menu, but there is no add to playlist.

### Additional information

I might be missing something. If this is already possible disregard.

**Comment by Stypox** [comment]
Depends on #478, and can be considered a duplicate

**Comment by logcatdog** [comment]
No, the point was to not use an external player. You can make playlists of links to youtube or whatever, what i was hoping for was a way to make playlists, inside newpipe, with items in the downloaded folder
