### ISSUE TITLE
pressing and holding the background and popup button on a channel or playlist are automatically added to the active playlist

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#1002]
add the possibility that by holding down the background button and the pop-up button in a playlist or channel (I mean the play button all), they are automatically added to the playlist you're listening to or watching

<img src="https://framapic.org/cAhRkoBS685l/mprnSHj4KDjv.png" width="300">

**Comment by theScrabi** [comment]
I don't get your question. Try it than you will see whether it works or not.

**Comment by speednroll** [comment]
I just edited the request. Sorry, I use the Google translator and it does not work very well since I do not know English

**Comment by speednroll** [comment]
I just want these two buttons that are marked:
![](https://framapic.org/6uGy67Ye5fqo/jcIr4ZWefjg1.jpeg)

by keeping them pressed have this menu:
![](https://framapic.org/flnZWTL6zCPk/grHl9PnSzOIZ.png)

**Comment by felixgonsug** [comment]
I más about to post the same FR, when you press play in background in a playlist it sutitute the background list with the playlist. It would be nice to add a playlist to de background list without deleting the actual background list. Summing up, the ability to queue a playlist in the background or popup

**Comment by speednroll** [comment]
It would be nice to add this basic option

**Comment by filalex77** [comment]
I would really like this, and I don't think it's that hard to implement. I may give it a shot

**Comment by Stypox** [comment]
This has been implemented
