### ISSUE TITLE
change package name

### ISSUE THREAD

**Issue by msuanwar** [TeamNewPipe/NewPipe#10036]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hello, every time I try to change the package name, I get a lot of errors.
It changes in places and places, but it changes with it, so is there a way

**Comment by Stypox** [comment]
Provide more info
