### ISSUE TITLE
custom font

### ISSUE THREAD

**Issue by idontveapc** [TeamNewPipe/NewPipe#10041]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

feature option(s) for changing the font of the app. 

### Why do you want this feature?

what want the app to look good, as i want or fix some issues like some unicodes/characters not being available on my device or system fonts or similar else.

### Additional information

>!sorry for the previous template, if you're reading this again!!<

**Comment by Timothy099qw** [comment]
Hi, interested in adding this feature. Could I be assigned?

**Comment by u7648330** [comment]
Hi, interested in adding this feature. Could I be assigned?

**Comment by u7648330** [comment]
Thank you for your message, I will work on this issue.

**Comment by Stypox** [comment]
I am closing this issue as off-topic, it is not up to NewPipe to fix buggy system fonts, since then every app would need to implements such a thing. Try to see if you can use one of the options here: https://www.xda-developers.com/how-to-change-font-android/.
