### ISSUE TITLE
Video resolution information is delayed when downloading

### ISSUE THREAD

**Issue by yemenihandsome** [TeamNewPipe/NewPipe#10060]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1- Login to the application
2- Choose a video to download
3-Delay when displaying required quality information after some time
 

### Expected behavior

Shows quality and size res fast

### Actual behavior

But the quality information is not shown fast and appears after some passage

### Affected Android/Custom ROM version

android 13

### Affected device model

LG V60 5G

**Comment by Stypox** [comment]
This is not solvable, since in order to obtain size a HEAD request needs to be performed for each stream, which might take some (small) time
