### ISSUE TITLE
Feature request save / export / import subscriptions 

### ISSUE THREAD

**Issue by Ozyc** [TeamNewPipe/NewPipe#1006]
When you have +50 subscription it's boring to add them, and if you change you rom you have to make it again :(
It will be a great feature 👍

**Comment by speednroll** [comment]
I think this was already requested

**Comment by theScrabi** [comment]
Yea it was. But just a haker tip: If you have root on ur rom backup the dir ‘/data/data/org.schabi.newpipe/databases‘

**Comment by theScrabi** [comment]
We should definetly write an export for this.

**Comment by speednroll** [comment]
the same to make a backup of the preferences that you changed in settings
