### ISSUE TITLE
the letters overlap if you change the default size setting in android

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1008]
the letters are on top of each other in the video list when you change the default size of letters in the android settings:

<img src="https://framapic.org/idJXhLD78xTW/VFpqCK63pB4K" width=350px/>

**Comment by theScrabi** [comment]
Hm... This is a small screen. Seems the items do not addapt.

**Comment by speednroll** [comment]
![](https://framapic.org/pVtVzXOS7XWy/GwjyOG4fU4Kk.png)

in previous articles I had said that I have a motorola moto g5 plus.I just warned that there is an error since I have a family member who uses the application. he uses the big letters because he is difficult to read and the screen of his phone is not very small either

**Comment by speednroll** [comment]
Anyway, it's not a very relevant problem. more than anything is not aesthetic, just that

**Comment by opusforlife2** [comment]
Close. The link is expired/invalid, and OP account is gone.

**Comment by wb9688** [comment]
@opusforlife2: Nope, this is still actually a valid bug

**Comment by opusforlife2** [comment]
Oh. If it's reproducible, then it's fine.

**Comment by opusforlife2** [comment]
@MeHimWho Could you post screenshots of the before/after for how this would be fixed, potentially?

**Comment by MeHimWho** [comment]
I wasn't able to reproduce the bug. I did some digging and think that this issue might have been fixed as this issue [#5096](https://github.com/TeamNewPipe/NewPipe/issues/5096)

**Comment by opusforlife2** [comment]
@MeHimWho No problem. Would you like to work on another issue?
