### ISSUE TITLE
Subscription of subfolders

### ISSUE THREAD

**Issue by poweRalph** [TeamNewPipe/NewPipe#10092]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hello Christian,

is it possible with NewPipe to load videos from subfolders of YouTube?

Example from me:

I subscribed to the channel "Pia Aumeier". But the videos are always uploaded from the channel in the subfolder "Live". Thus, they do not appear in the subscriptions in NewPipe.

Therefore the question, whether one can synchronize with channels also the contents of the subfolders with.

Best regards
poweRalph

**Comment by ctntt** [comment]
The question wasn't addressed at me but I try answering it anyway.

Currently with version 0.25.1 this isn't possible. This is also a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2414.

**Comment by ctntt** [comment]
Here a workaround is mentioned https://github.com/TeamNewPipe/NewPipe/issues/9680#issuecomment-1382714916.
You use the 'Uploads from ...' playlist https://www.youtube.com/playlist?list=UUFNwIbxfLRGtzHwk0GY05JA.

**Comment by poweRalph** [comment]
Thanks for sharing this workaround. I'll try it out.
