### ISSUE TITLE
ability to automatically switch to background

### ISSUE THREAD

**Issue by Skrell** [TeamNewPipe/NewPipe#1010]
- [x] I checked if the issue/feature exists in the latest version.
Please add an option to automatically switch to background mode upon newpipe losing focus.  That would be fantastic!!!  Love the app btw and use it daily!
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

**Comment by theScrabi** [comment]
? You may not just write your question in the title an then leave it there. We need more intel about what you want.

**Comment by Skrell** [comment]
My sincere apologies!  I had written a message and upon posting it somehow got replaced with checkbox agreements?? 

Anyway, the original message I had posted was requesting an option to automatically switch the video to "background" mode upon the app losing focus.   Typically the way I use your excellent app is by opening a video from my youtube subscription via the "share function" to your app and then listening to it in the car.  The ability to more easily switch between "background mode" and "foreground" mode would be appreciated as I switch between other apps.

**Comment by avently** [comment]
@Skrell it's implemented here #834. Just wait until it will be merged.
When you are watching a video and than hide the app only audio track will be loaded. Its not a background player but it works identical.

**Comment by Skrell** [comment]
Awesome! Can't wait until the next release! 😄

**Comment by Stypox** [comment]
This has been implemented
