### ISSUE TITLE
Looping on Firefox not working

### ISSUE THREAD

**Issue by wh152** [TeamNewPipe/NewPipe#10114]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Go to any video on any instance
2. Press on the loop checkbox
3. Scroll to just before the end of the video

### Expected behavior

The video to loop.

### Actual behavior

The video does not loop and when scrolling back the video does not load.

### Logs

I get the following warning was displayed when the video loaded: 
Changing tracks while abr manager is enabled will likely result in the selected track being overriden. Consider disabling abr before calling selectVariantTrack()
The following 3 warnings were displayed after the video failed to loop:
Media resource blob:https://piped.video/1ae87e09-6cb6-4741-8da4-f5df95e1e8ce could not be decoded.
This error message will be blank when privacy.resistFingerprinting = true.  If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_WAITING_FOR_DATA (0x806e0009)
Media resource blob:https://piped.video/1ae87e09-6cb6-4741-8da4-f5df95e1e8ce could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_WAITING_FOR_DATA (0x806e0009)

### Additional information

I am using an up-to-date Firefox, and changing privacy to standard, disabling all extensions and giving all permissions including autoplay and cookies in a new window after restarting does not work. Javascript is enabled. Looping works in Chromium-based browsers like Brave for me, so I think this is a Firefox-specific issue. 

Scrolling back through didn't play the video so I assume the data stream failed when the looping was attempted and not re-tried.
privacy.resistFingerprinting is true, and setting it to false and restarting the browser does not fix the issue.
I'm assuming the last 3 error messages are as a result of the issue and not the cause since the last 2 are due to data (presuamably the video) not being loaded, and the 3rd last is likely due to what I think the cause is, which is that the current video has been overridden by the best stream (in terms of bitrate and resolution) since Adaptive Bitrate Streaming has not been disabled when selectVariantTrack() is called. The code at https://github.com/TeamPiped/Piped/blob/master/src/components/VideoPlayer.vue at line 573 calls selectVariantTrack() and there is a check on line 525 to disable ABR if a high quality stream is selected, but this must be blocked on Firefox for some reason which is causing the video stream to fail.

**Comment by AudricV** [comment]
Wrong repository, Piped is not NewPipe. Open an issue at the right one instead, https://github.com/TeamPiped/Piped.
