### ISSUE TITLE
Changing the language settings doesn't change the trending content

### ISSUE THREAD

**Issue by vatsalasonal** [TeamNewPipe/NewPipe#1013]
I downloaded the latest code (v0.11.4) and built and found that below issues exists:
Steps to reproduce:
1. Settings->Content->default content language
2. Change to Portugues(Brasil)
3. Go back
3. Check the trending page, content is still set to previous content.
4. Go to kiosk and then click on trending.
5. Now the trending page content has changed.

Issue:
In point 3 the trending page should have changed as the language has been change along with the country.

**Comment by FaizKhan5** [comment]
Close this.

**Comment by gkeegan** [comment]
As far as I can tell, this is actually not fixed yet. Although I may be misinterpreting the issue.

**Comment by Stypox** [comment]
This happens because the trending activity is only updated upon reload (either by closing&reopening the app or by clicking on "trending" from "kiosk"). The ability to refresh would probably fix this issue.

**Comment by B0pol** [comment]
The trending content is changed by the content language, not the content language.

Youtube features trending by countries, that's why. Please close this @Stypox
