### ISSUE TITLE
Why is this English video star playing with spanish or who knows what language? 

### ISSUE THREAD

**Issue by idk-floppy** [TeamNewPipe/NewPipe#10146]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Open app
2. Look up chloe ting
3. Start this video: /watch?v=ljNgkSctkXg
4. It starts with spanish or idk wha language. If you open another, like this: /watch?v=0rL2496zybs
5. This one works as intended.

What is happening and why? I tested it on 2 different phones, with fresh install too. 

### Expected behavior

Just play it in English like default. 

### Actual behavior

Plays in spanish or italian or idk

### Affected Android/Custom ROM version

Android 12

### Affected device model

Xiaomi mi 10t pro, and xiaomi mi 11

**Comment by idk-floppy** [comment]
Forgot to mention: I opened both videos on desktop for example, and both plays in English.

**Comment by idk-floppy** [comment]
I don't really understand that. The video is in English but there's some italian voiceover that I never turned off, and only on that particular video, in this app.

Am I missing something? I could send a screenrecord of it I guess?

**Comment by NottLexa** [comment]
You see, Youtube has brought a new "multiple audiotrack" feature, which allows selected authors put several audiotrack for one video on different languages. In official Youtube app or website you can choose one track to enable while watching the video. NewPipe doesn't support this feature yet so it picks random audiotrack avaible.

**Comment by idk-floppy** [comment]
Ooh I see! Thank you for your explanation and patience, have a great day! :)
