### ISSUE TITLE
Add thumbnail / album cover to downloaded files

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [TeamNewPipe/NewPipe#1014]
Id like m4a files contain an album cover.

**Comment by AndroidDeveloperLB** [comment]
As for the conversion to mp3, there are apps that do this, if needed.

**Comment by theScrabi** [comment]
The [Contribution Guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md) say it all.

**Comment by AndroidDeveloperLB** [comment]
@theScrabi Duplicate of where? I don't see playlist download mentioned. Same goes for cover art

**Comment by theScrabi** [comment]
For example: https://github.com/TeamNewPipe/NewPipe/issues?utf8=%E2%9C%93&q=mp3

**Comment by AndroidDeveloperLB** [comment]
Main thing is the playlist& cover, as Android can play m4a just fine.
Not sure if this format has cover support, though.

**Comment by AndroidDeveloperLB** [comment]
Can I at least change the post to be about playlist&cover art only?

**Comment by theScrabi** [comment]
m4a is a mpeg4 only containing audio files. So yes I think coverart would be supported. [This library](https://github.com/jcodec/jcodec/blob/master/src/main/java/org/jcodec/movtool/MetadataEditor.java) could do the job.

**Comment by AndroidDeveloperLB** [comment]
If it contains only audio, it won't support cover art, no?
Anyway, I'm not expert on audio files. I just know that there are PC solutions to convert to mp3 with album art, but never saw one for m4a.

**Comment by AndroidDeveloperLB** [comment]
Can I create a thread for downloading a whole playlist, too?

**Comment by theScrabi** [comment]
I guess this issue exists already.

**Comment by AndroidDeveloperLB** [comment]
It is? where?

**Comment by darkon5** [comment]
I would love if it would parse the track name and artist from the video title/channel name. A dialog message would be best to check if the parsed info is correctly typed.

**Comment by wb9688** [comment]
@theScrabi: That JCodec thing is pretty cool, I think we should implement that (instead of going with the FFmpeg in a separate app way I suggested before).

**Comment by theScrabi** [comment]
Yea we can give it a shot, especially when its just about putting an album cover somwhere.

**Comment by AndroidDeveloperLB** [comment]
Is it now available?

**Comment by Rubb46** [comment]
My friends says that (Ymusic app) done this job.

**Comment by Stypox** [comment]
That's a totally different proprietary app. How does that count?

**Comment by Rubb46** [comment]
> That's a totally different proprietary app. How does that count?

🤣🤣

**Comment by Rubb46** [comment]
New pipe will give this feature? #1014

**Comment by Stypox** [comment]
Closing in favour of #4341

**Comment by gl-dev** [comment]
This might be a workaround for the requested cover feature, but it requires MP4 files as source.
https://github.com/TeamNewPipe/NewPipe/issues/4341#issuecomment-706684420
