### ISSUE TITLE
Mrbeast video dubbed in non english language despite settings

### ISSUE THREAD

**Issue by DankEngineer** [TeamNewPipe/NewPipe#10155]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Go to mrbeasts video
2. Play it

### Expected behavior

Plays in english

### Actual behavior

Dubbed in some language (not sure which one)

### Screenshots/Screen recordings

Here is a video of what happened
Unfortunately YouTube made it a short because it is vertically recorded

https://m.youtube.com/shorts/Mw4hNBn0iKc

### Affected Android/Custom ROM version

Android 10

### Affected device model

Samsung galaxy s9+

**Comment by moriel5** [comment]
Which language were you getting?
Since for me it is in Arabic for some odd reason, but if I go back far enough, the older videos are in English.
