### ISSUE TITLE
SoundCloud Download "Unknown Quality" audio cannot be played

### ISSUE THREAD

**Issue by esn89** [TeamNewPipe/NewPipe#10153]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Go to NewPipe
2. Go to the SoundCloud option
3. Find a song that allows you to download in bitrate higher than 125kbps.  Normally it says "Unknown Quality" with a filesize significantly bigger than the default mp3 128kbps.
4. Download it
5. Try to play it with AIMP
6. Go to terminal of your phone and do `file $DOWNLOADED_FILE` it says file type is just "data".

### Expected behavior

I should be able to play this file.

### Actual behavior

Music players cannot play the downloaded file.
Linux does not detect the extension.

### Screenshots/Screen recordings

![screenshot](https://i.imgur.com/hbLbfqh.jpeg)

### Logs

No crash logs.

### Affected Android/Custom ROM version

Android 13, OxygenOS

### Affected device model

OnePlus 8 Pro

**Comment by esn89** [comment]
Ooops, here is the image:

https://imgur.com/a/FzmS61B

**Comment by esn89** [comment]
@opusforlife2 since this is a whole DJ set about ~1 hour, it is quite possible if it is a flac :)

**Comment by TobiGr** [comment]
@esn89 Please test the APK in #10165 . I was able to test the it with the song you provided in the screen shot. That download is an AIFF file. SoundCloud artists can upload streams with other formats, too. I was not able to find one which uses another format. If you do, please tell us if it works.

**Comment by esn89** [comment]
@TobiGr , let me test this out.  Give me some time :)

**Comment by esn89** [comment]
It downloads, but, it saves as a 49.4mb mp3 instead.

**Comment by TobiGr** [comment]
@esn89 That's a regression which was recently introduced. I'll have to fix it first (see #10180)

**Comment by TobiGr** [comment]
Please test the latest APK, everything should work now.
