### ISSUE TITLE
Black screen while playing

### ISSUE THREAD

**Issue by freMea** [TeamNewPipe/NewPipe#1015]
**Version** : 0.11.5
**Android** : 6.0.1 x86

_Test with default setting, data and cache cleaned up_ 

## Steps

- Play a video (default resolution is 360p) in full screen.
- Select any resolution above 360p.
- Video must be in landscape.

## Results
After the overlay controls disappears the screen turns black and video keeps playing but just showing black screen until you tap the screen that show the video and the controls again. Conclusion: the video is correctly displayed only when controls are displayed too or if its resolution is below 480p.

## Settings tests

- Changing theme, default video resolution, video format or using external player (MXPlayer) doesn't solve the issue.
- If external player is set and I download the video in a resolution higher than 360p and launch it through the Newpipe download screen in MXPlayer, the issue happens in this player too on the same condition (when in full screen, landscape, controls off). But if I run MXPlayer and launch the playback from its library NO issue.
- No issue when "use former player" is set.

I hope it helps to find out the bug.

**Comment by wb9688** [comment]
Does the same happen in the official YouTube app? Does it work when you set
another prefered video codec in NewPipe's setting? What phone do you have?
If not running the default ROM, what custom ROM are you using (link)?

**Comment by freMea** [comment]
In official app, no.
Like I said, changing from mpeg4 to webm or 3gp doesn't solve.
Phone is zenfone 2, stock ROM. Can't reproduce issue in any other youtube or video apps.

**Comment by freMea** [comment]
0.11.5 solve this issue. Good!

**Comment by freMea** [comment]
It works as expected if another app named Twilight is enabled. It's a screen color filter used dim brightness and blue. I would expect compatibility issue if bug occured when Twilight is ON but it's the opposite Twilight seems to fix the bug.

**Comment by theScrabi** [comment]
Al right than we just have to merge twilight than its fixed 😂.

**Comment by theScrabi** [comment]
Well I'd guess this is one of the errors that occurs because of the huge android segmentation. Every device has its own little issue, and this sounds pretty od.

**Comment by freMea** [comment]
It sounds like an overlay issue. Maybe the video renderer.

**Comment by tobiasBora** [comment]
It may be very stupid but I had a similar issue because I negligely swiped my finger on the left side and it changed the luminosity. Switch it again from bottom to top and you have a nice luminosity back!

**Comment by Murderisrelevant** [comment]
I keep getting this dark acreen. I can see the video and settings on the overlay, if I am in a darker lit place. My phone brightness is at max. Still does it.

**Comment by Stypox** [comment]
Is this still an issue after many exoplayer updates?
