### ISSUE TITLE
Background play gets interrupted (ERROR_CODE_IO_NETWORK_CONNECTION_FAILED)

### ISSUE THREAD

**Issue by mehmetgunacti** [TeamNewPipe/NewPipe#10161]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

open a long video on Youtube.

minimize NewPipe, so that controls appear as a notification.

turn off screen, listen to the youtube video

### Expected behavior

The (long) Youtube video should play uninterruptedly until the end.

### Actual behavior

It stops after a while giving an error.

### Logs

{"user_action":"play stream","request":"Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED] occurred while playing https://www.youtube.com/watch?v=0NbBjNiw4tk","content_language":"en-US","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.25.1","os":"Linux samsung/b0qxtur/b0q:13/TP1A.220624.014/S908EXXU4CWCE:user/release-keys 13 - 33","time":"2023-06-12 21:25","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.UnknownHostException: Unable to resolve host \"rr3---sn-8vq54voxu-pnue.googlevideo.com\": No address associated with hostname\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)\n\tat com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)\n\tat java.lang.Thread.run(Thread.java:1012)\nCaused by: java.net.UnknownHostException: Unable to resolve host \"rr3---sn-8vq54voxu-pnue.googlevideo.com\": No address associated with hostname\n\tat java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)\n\tat java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)\n\tat java.net.InetAddress.getAllByName(InetAddress.java:1152)\n\tat com.android.okhttp.Dns$1.lookup(Dns.java:41)\n\tat com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)\n\tat com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)\n\tat com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)\n\tat com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)\n\tat com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)\n\tat com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)\n\tat com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)\n\tat com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)\n\tat com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)\n\tat com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)\n\t... 10 more\nCaused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)\n\tat libcore.io.Linux.android_getaddrinfo(Native Method)\n\tat libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)\n\tat libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)\n\tat libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)\n\tat java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)\n\t... 28 more\n"],"user_comment":"long youtube video playing in bg, screen closed"}

### Affected Android/Custom ROM version

Android 13 OneUI 5.1

### Affected device model

Samsung Galaxy S22 Ultra

### Additional information

I'm using Brave browser for background play. The same interruption occurs there as well.

Then I switch to Firefox Nightly, background play and screen off; the same error occurs there as well.

Except; Brave and Firefox Nightly recover after 3-5 minutes of silence (sometimes longer) and playback continues on its own. 

So I'm not sure if this is intentionally done by Google/Youtube !?

Also, opening the screen and opening Brave or Firefox (when video is hung) the "loading" animation is seen, but most of the time playback resumes instantly (after opening the browser video window).

Finally, I switch to NewPipe, open the same video, background play and screen off. Except after a few minutes of being able to listening to the video NewPipe throws an exception.

**Comment by mehmetgunacti** [comment]
This happened a few times in the past, so I finally opened this issue.

I'm not sure if this has something to do with AdAware (non root) on my phone, but I couldn't reproduce this again. I'm closing this for now but will re-open it if it happens again.

**Comment by obfripper** [comment]
I was getting the same error with background playback, with the playback working fine while I was browsing or other general use, but once the phone goes to lockscreen, within 2-3 mins the playback would stop and trigger an error, and would not restart until the screen was unlocked.

I think it is related to vpn use, I have Duckduckgo tracking protection running, which is implemented as a vpn service.

I've whitelisted Newpipe in Duckduckgo and as far as I can see am getting no more errors.
