### ISSUE TITLE
Shorts tab not loading anything in channel tabs PR

### ISSUE THREAD

**Issue by Drangonfly30** [TeamNewPipe/NewPipe#10186]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Channel tab PR

### Steps to reproduce the bug

Go to channel tabs of a channel
Go to shorts section

### Expected behavior

It should load all the shorts

### Actual behavior

It does not load anything and keeps the page blank

### Screenshots/Screen recordings

![Screenshot_2023-06-25-23-58-33-397](https://github.com/TeamNewPipe/NewPipe/assets/113085944/c516acc3-851d-4351-857d-2366f1604d6e)

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

Lenovo k6 power

**Comment by AudricV** [comment]
> in channel tabs PR

Then report the issue in the PR and not in a separated issue. Issues are only for code merged of this repository and not its forks.
