### ISSUE TITLE
Website main page removed from Google search results due to a DMCA complaint

### ISSUE THREAD

**Issue by SebCbien59** [TeamNewPipe/NewPipe#10197]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Google has blocked the adress in his search engine after a DMCA complaint, adress still on top of sezrch with bing duck duck go or Qwant. Maybe changing.net in .org or in .com etc will solve for some times the issue.

### Why do you want this feature?

Risk with google and end of Newpipe project

**Comment by theScrabi** [comment]
According to Google it was this DMCA Request that led to the Unlisting: https://lumendatabase.org/notices/34186209#

**Comment by ARBoyGo** [comment]
I don't think it's a big problem so far, So lets wait.... 
No need to change domain.

**Comment by ARBoyGo** [comment]
The language of author of this issue 😭

**Comment by TheoCGaming** [comment]
> Is this DMCA compliant really from Ed Sheeran team ?

It seems so, also it mentions a song actually being used? I find that hard to believe...

It also appears that some other sites have been affected, but I don't see APKPure being delisted yet.
![image](https://github.com/TeamNewPipe/NewPipe/assets/65421262/774a6fc8-1817-41e4-97b8-3276cce141f4)

**Comment by Fish25op** [comment]
The website has been restored😇

**Comment by TobiGr** [comment]
The DMCA was rescinded and therefore the landing page is back in the search results
