### ISSUE TITLE
[feature request] Is it possible to add the possibilty to answer surveys?

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1019]
- [✔ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [✔ ] I checked if the issue/feature exists in the latest version.

I was wondering if it was possible to answer to surveys made by youtubers without any account, and if it is, could you add this feature ? :)

**Comment by theScrabi** [comment]
No. I don't know how youtube organizes this survey, but we want to keep the interaction with google as low as possible.

If you where still interested in this you could take a look at [webtube](https://f-droid.org/en/packages/cz.martykan.webtube/).

**Comment by justanidea** [comment]
No, dont worry, its not this tiny feature which will make me quit this awesome app :)
