### ISSUE TITLE
No video can be played on TCL TV

### ISSUE THREAD

**Issue by sbkkztb** [TeamNewPipe/NewPipe#10204]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

My Android TV is TCL Q10G.
On this device，Newpipe can't play any youtube video, the playback page keeps spinning in circles, and  can't load any video. But at the same time, my phone can play normally. Excuse me, does the app not support TCL Q10G, and will it be supported in subsequent updates?

### Expected behavior

Can play videos normally

### Actual behavior

After waiting for more than 10 minutes, it kept spinning in circles and no video appeared

### Screenshots/Screen recordings

![IMG_20230704_112247](https://github.com/TeamNewPipe/NewPipe/assets/138541196/0a22da8b-261d-4707-8f02-8a993d96c238)

### Affected Android/Custom ROM version

Android 9

### Affected device model

TCL Q10G

**Comment by TobiGr** [comment]
that looks strange, is any data loaded or stays everything empty as shown in the picture? If just the video is missing / black, download the APK from #10122 and disable media tunneling as explained [here](https://github.com/TeamNewPipe/NewPipe/pull/10122#issuecomment-1588139580).

**Comment by sbkkztb** [comment]
> that looks strange, is any data loaded or stays everything empty as shown in the picture? If just the video is missing / black, download the APK from #10122 and disable media tunneling as explained [here](https://github.com/TeamNewPipe/NewPipe/pull/10122#issuecomment-1588139580).

Thank you for your reply and help.

After uninstalling the original APP, reinstall the beta version you provided, and "Disable media tunneling" is enabled.

The failure is still as shown in the previous picture: the app does not crash, but nothing is displayed, it keeps spinning, no video loads, some video comments can be displayed, some cannot, no regularity,

**Comment by TobiGr** [comment]
I am sorry to hear this. Well, we cannot do anything with just the screenshots. You'll need to record and send us the application logs. In case you haven't enabled debugging on your device yet, see https://stackoverflow.com/a/39839668 for more info.
