### ISSUE TITLE
[YouTube] Incessant Buffering/Slow Stream Download on Age Restricted Videos

### ISSUE THREAD

**Issue by Connor-Killman** [TeamNewPipe/NewPipe#10202]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Find a restricted video, either from within NewPipe or via direct link. (I used the following playlist for testing: https://www.youtube.com/playlist?list=PLvF4o8XXUlUP-UytxYNMEVndMem__ySoJ)
2. Play the video.
3. Be greeted by a buffer preceding playback.

### Expected behavior

The video will buffer briefly before beginning playback. (Or possibly not play at all. I found this issue, https://github.com/TeamNewPipe/NewPipe/issues/9654, which claims restricted videos should not play, but they do on my device, albeit badly.) Playback continues smoothly for the rest of the video.

### Actual behavior

The video has a distinctly longer buffering period before beginning playback. Once playback begins, a few seconds will pass before buffering is again required. The video will continue for another few seconds before needing to buffer again. This will continue for the entirety of playback. The video will consistently play for around 2-3 seconds before buffering for around 10 seconds.

### Logs

No Logs

### Affected Android/Custom ROM version

Android Version 12

### Affected device model

Samsung Galaxy S10e

**Comment by Noobydoobie** [comment]
Same issue but with Note 10 plus

**Comment by katsumag** [comment]
I have the same issue on an S20

**Comment by AudricV** [comment]
Fixed by TeamNewPipe/NewPipeExtractor#1076.
