### ISSUE TITLE
[feature request] A volume upgrade?

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1020]
- [✔ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [✔ ] I checked if the issue/feature exists in the latest version.

Could you make possible to enable volume increasing by swiping up on the right side of the screen even if the screen is turned off ? It would be awesome when you put your video in audio-background

**Comment by switchtegrax1** [comment]
That's not possible as this would require hardware and/or software modifications to the phone to allow gestures with the screen off

**Comment by justanidea** [comment]
Kk
