### ISSUE TITLE
Cannot drag popup video from top-left corner.

### ISSUE THREAD

**Issue by TheJeffGoldblum** [TeamNewPipe/NewPipe#1021]
Popup mode used to work fine, but the last few times I've tried using it, I haven't been able to move the video from its original position.
Instead, when I try dragging the video somewhere, I somehow only move the overlay controls (play, fullscreen, progress bar, etc.), while the actual video stays in place. 
I am also able to re-size the video by pressing and holding down on it. It does expand, but I still cannot move it afterwards. 
This happens on each version of NewPipe I try, including the latest. 

I have a US LG G6, stock OS.

**Comment by RodolfoCandido** [comment]
I have the same problem, but its only happens when I use the expanded desktop option from LineageOS. If I disable this option, everything works fine again. I am using LineageOS 13 with the latest version of NewPipe.

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1159
