### ISSUE TITLE
[Feature Request] run the links of time of the description in the background player and video popup

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1025]
• [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
• [x] I checked if the issue/feature exists in the latest version.

Could you add the time links that are in the description to change the seconds in the video popup and background player?
<img src="https://framapic.org/SsCAtjQmdiKL/wyTGx4z25P2H.png" width=350px/>

**Comment by speednroll** [comment]
answer :grimacing:

**Comment by speednroll** [comment]
Can someone say something about this?

**Comment by theScrabi** [comment]
We had this already, somehow we had to remove it since it crashed the application.

**Comment by speednroll** [comment]
great!

**Comment by Stypox** [comment]
This already works with comments, so I don't think it would be too difficult to implement for the description

**Comment by jimbo1qaz** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/commit/389a87fc897aa44ac6347de41deb02b0fe9a5e1d breaks Youtube video description timestamp links.

In master: https://github.com/TeamNewPipe/NewPipeExtractor/blob/5f65788a2f89eedbf384aa5c5f3f98dcfd73400e/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L159

`return parseHtmlAndGetFullLinks(doc.select("p[id=\"eow-description\"]").first().html());`

I don't know the intention and don't know how Youtube links look like now.

-------------

I used https://www.youtube.com/watch?v=HtYEt0H1Wuk as a test video with timestamp links in the description.

In `doc.select("p[id=\"eow-description\"]").first().html()`, timestamp links look like `<a href="#" onclick="yt.www.watch.player.seekTo(0*3600+00*60+00);return false;">0:00:00</a>`.

`parseHtmlAndGetFullLinks()` turns them into `<a href="https://www.youtube.com/watch?v=HtYEt0H1Wuk#" onclick="yt.www.watch.player.seekTo(0*3600+00*60+00);return false;">https://www.youtube.com/watch?v=HtYEt0H1Wuk#</a>`, which is bad.

-----------

https://github.com/TeamNewPipe/NewPipe/issues/2200 points to https://github.com/TeamNewPipe/NewPipe/pull/2168/files#diff-a2aee87b46e03249422bc44ee9976c20R38, which fixes links found in the comments (but not the description).

**Comment by B0pol** [comment]
Can you reopen this issue as it's not fixed ? We still can't open links from the description.
