### ISSUE TITLE
After resuming video in "Play all" in playlist and going full-screen, video stops seconds later, and tapping "Play all" plays the 2nd video at the timestamp where the 1st video stopped

### ISSUE THREAD

**Issue by gasull** [TeamNewPipe/NewPipe#10251]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

NewPipe SponsorBlock 0.25.1

### Steps to reproduce the bug

1. Play a playlist with "Play all" to play the list starting with the 1st video.
2. Pause the video after a while.
3. Wait a long time, maybe an hour.  (I wonder if it's related with the video stream from YouTube)
4. Open NewPipe again and resume the video.
5. Rotate the phone to go full-screen.
6. The video is interrupted (most of the time) and the information screen of the video is shown.
7. Tap play.
8. 2nd video is played instead of the 1st video, at the timestamp where the 1st video was interrupted.

### Expected behavior

The 1st video should continue playing without stopping.  And if it stops, it shouldn't be skipped when I tap "Play all".  And if it skipped, then the 2nd video shouldn't start at the timestamp where I left the  1st video.

### Actual behavior

1st video stops after a few seconds.  It doesn't always happen.  It seems to happen when I haven't resumed the video in an hour or so.

Then when I tap "Play all" the 2nd video (next one in the playlist) is played instead, but at the timestamp where the 1st video was interrupted.

### Affected Android/Custom ROM version

GrapheneOS (Android version 13)

### Affected device model

Pixel 5

**Comment by gasull** [comment]
I edited the description to correct the flow for the bug, as it happened to me again just now.

A possible workaround is to exit the video, go back to the playlist, and play it again.  Then it won't skip the first video.

**Comment by ygaz69** [comment]
I can confirm this occurs in the Official app 0.25.1  There is no consistency to when it happens, but I'm unable to listen to this full playlist without at least 2 viseos freezing at 1:19 https://youtube.com/playlist?list=PL9MmRpJGJW1lwEHzgL85Om5Ij8UNNEDkC
