### ISSUE TITLE
[Feature request] - Able to create playlist and export it to file

### ISSUE THREAD

**Issue by janos-szenfner** [TeamNewPipe/NewPipe#1026]
It would be great if as a user I would be able to create playlists and be able to save it to file.

**Comment by speednroll** [comment]
this already exists and there is very little left for them to launch a version of newpipe with these characteristics (except for keeping it in a file, I'm not sure)

**Comment by Stypox** [comment]
Playlists have been implemented, while for the save option refer to #2258
