### ISSUE TITLE
remove youtube redirects to links in the description and instead access the clean full link

### ISSUE THREAD

**Issue by RustoMCSpit** [TeamNewPipe/NewPipe#10287]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

youtube makes redirect tracker links to any links in the description of a youyube video but hides them under the plain text that appears to shpw a differeng link

### Why do you want this feature?

privacy

**Comment by AudricV** [comment]
This should be already implemented. If you still see tracking redirect links, could you give us steps to reproduce with valid data (like a valid video ID on which you can reproduce the issue), as this would be a bug?

**Comment by RustoMCSpit** [comment]
> This should be already implemented. If you still see tracking redirect links, could you give us steps to reproduce with valid data (like a valid video ID on which you can reproduce the issue), as this would be a bug?

dont worry about it, i thoyght this wasnt impleneneted

**Comment by RustoMCSpit** [comment]
it works fine just tested, pleaze cloze this
