### ISSUE TITLE
[bug] when opening a youtube url directly to video popup it does not appear in the history

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#1028]
• [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
• [x] I checked if the issue/feature exists in the latest version.

I found another bug, this is about when you open a video from a link directly from the popup this does not appear in the history

**Comment by karyogamy** [comment]
Fixed in #1004.
