### ISSUE TITLE
I’m going to uninstall the Newpipe x Sponsorblock app

### ISSUE THREAD

**Issue by MuerteRoja** [TeamNewPipe/NewPipe#10282]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

When I find myself using the application a poster appears in which tells me that an error has been detected and automatically the video that was playing stops me, this error has already occurred more than once, Newpipe x Sponsorblock is an application that I use frequently for my sports training, I put on a music video, I turn off the screen of the mobile phone and while I am running the application stops me, this, metaphorically speaking represents a great pain in my balls, before this problem what I did was to download the application of Youtube Vanced next to the application of Vanced Micro G, I must say that the problems and inconveniences that the application of Newpipe x Sponsorblock presents me, I do not have them with Youtube Vanced

### Expected behavior

When I find myself using the application a poster appears in which tells me that an error has been detected and automatically the video that was playing stops me, this error has already occurred more than once, Newpipe x Sponsorblock is an application that I use frequently for my sports training, I put on a music video, I turn off the screen of the mobile phone and while I am running the application stops me, this, metaphorically speaking represents a great pain in my balls, before this problem what I did was to download the application of Youtube Vanced next to the application of Vanced Micro G, I must say that the problems and inconveniences that the application of Newpipe x Sponsorblock presents me, I do not have them with Youtube Vanced

### Actual behavior

When I find myself using the application a poster appears in which tells me that an error has been detected and automatically the video that was playing stops me, this error has already occurred more than once, Newpipe x Sponsorblock is an application that I use frequently for my sports training, I put on a music video, I turn off the screen of the mobile phone and while I am running the application stops me, this, metaphorically speaking represents a great pain in my balls, before this problem what I did was to download the application of Youtube Vanced next to the application of Vanced Micro G, I must say that the problems and inconveniences that the application of Newpipe x Sponsorblock presents me, I do not have them with Youtube Vanced

### Affected Android/Custom ROM version

Android 12 MIUI 13

### Affected device model

Xiaomi Redmi 9

**Comment by TobiGr** [comment]
Hi, where should I begin?
1. This is not the repository for NewPipe x Sponsorblock. It is the repository for NewPipe. If the issue is caused by Sponsorblock, please report the crash at https://github.com/polymorphicshade/NewPipe/issues
2. You need to fill in the template properly. The categories above exist for a reason
3. You won't get any help without posting the crash logs or a precise description of what happened how and when.
4. Search for duplicates

Sorry, if this comes of rude, but we get a lot of bug reports and if newly submitted tickets do not meet a certain quality, they just waste time which could be used to fix bugs.
