### ISSUE TITLE
Add "copy to clipboard" ability for YouTube video.

### ISSUE THREAD

**Issue by sky-cake** [TeamNewPipe/NewPipe#10299]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

1. Add `Copy to Clipboard` option after `long hold on video component` -> tapping `Share`
2. Add `Copy to Clipboard` in video player where the globe and share icons are, or as part of the menu that appears after tapping the share icon, or to the video data menu.

Essentially, just add the Copy to Clipboard ability for YouTube videos anywhere.

### Why do you want this feature?

Right now, in order to copy a YouTube video link to my clipboard, I must either
1. Tap the globe icon in the video player, get taken to my Android browser, highlight the URL address and copy it.
or
2. Tap the share icon in the video player, select a method to send the URL (e.g. send myself the link through Signal), go to that app, and copy the address.
or
4. Similar to 2. but tap and holding on a video component then selecting Share. Sent the URL to a messaging app, go to that app and copy the address.

It would be much faster to just tap a copy icon from the video player, or other menu.

### Additional information

I am using the latest version of NewPipe, v0.25.2.
I am running Android 9, One UI version 1.0

**Comment by Aleovas** [comment]
This already exists. Hold tap on the share button

**Comment by ChaosNicro** [comment]
Well I'm not sure if this differs in Android versions, but A10-12 has a copy button at the very top of the native share menu. Is this really not convenient enough?

**Comment by sky-cake** [comment]
> This already exists. Hold tap on the share button

Thanks, while I've tried tapping the share button, I didn't know about hold-tapping it. Thank you!

**Comment by lsahnicne** [comment]
I still would like to advocate for OP's original request. Hold-tapping the share icon is just so unintuitive - I never would have discovered it on my own have I not found this thread. Access to such basic functionality should not rely on esoteric knowledge.

**Comment by syphyr** [comment]
When I select `share` then `copy to clipboard`, I get an endless message popping up that Google Drive is unable to start. Using Android 7.1 and latest newpipe source on master branch.

**Comment by syphyr** [comment]
If I remove Google Drive, then the option to `copy to clipboard` is removed also...
