### ISSUE TITLE
[bug] too long links under a video can be bad

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1029]
- [. ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [. ] I checked if the issue/feature exists in the latest version.

When a link is too long, we can a "..." at his end.  But when we open the link, this link is copied/past whith the ".." and we dont find any internet page.

**Comment by justanidea** [comment]
I couldnt send my screenshots, you'll need to believe me
Anyway this is the url of the video where i discovered the bug, so you can try it yourself (the two last links under the video):

https://www.youtube.com/watch?v=m3GCXp82X5Q

**Comment by yasu4** [comment]
It's not always include ... to the link, but it's always missing the end part. From above video last link ends with /ind... (original is /index.php/something) and the second from the end is /acouphene with original /acouphene-troubles-audition-orl-comment-ecouter-musique-sans-danger-casque-audio-ecouteurs-2028135.html

**Comment by theScrabi** [comment]
Ah links in the description can't be opened right? This should be fixed then.

**Comment by Stypox** [comment]
This was fixed a while ago
