### ISSUE TITLE
[Feature Request] Show playlists on someone's channel

### ISSUE THREAD

**Issue by JuniorJPDJ** [TeamNewPipe/NewPipe#1030]
I would like to see not only videos, but also playlists in channel's view.

**Comment by theScrabi** [comment]
Yea that would be userfull.

**Comment by speednroll** [comment]
it could be something like that :grin:
![](https://framapic.org/j2KKHJ6WUX6Y/t8j9Oo9iAW15.jpg)

**Comment by kevinbakbak** [comment]
yes,i wish support show playlists on someone's channel

**Comment by spandan888** [comment]
same here. the support to show playlists on every channel should be implemented. since they are available on the m.youtube.com site, it shouldn't be much of a hassle.
many thanks for the app.

**Comment by theScrabi** [comment]
maybe with the new filter system im working on we can filter by playlists when accessing channels ... so it could be included here :)

**Comment by bisam** [comment]
This feature would be awesome! Is there any progress? :grin:

**Comment by burneracc69** [comment]
Yeah any progress? Still waiting.. I need confirmation :p

**Comment by Stypox** [comment]
Closing in favour of #2414
