### ISSUE TITLE
[Feature Request] Audio-Only Streaming

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#1031]
I would like to request a new feature that would enable (by option) to only stream the audio, so that it saves bandwidth (for those who have limited (speed) access to internet or limited internet plans).

Thank you in advance for your understanding (sorry if my English is bad).

**Comment by wb9688** [comment]
We already have that, just press the background button.

**Comment by justanidea** [comment]
I think he means for a real stream, which isnt supported for the moment

**Comment by theScrabi** [comment]
That's exactly what happens when you press play in background 😂. It's the same data as when you download audio only.
