### ISSUE TITLE
Premium ad free

### ISSUE THREAD

**Issue by phpcip** [TeamNewPipe/NewPipe#10314]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Need an ad free version

### Why do you want this feature?

Because I hate ads.

**Comment by rozari0** [comment]
Newpipe is adfree. 🙄

**Do not** install newpipe from playstore.

**Comment by ChiefMikeK** [comment]
> Newpipe is is completely ad-free NOT available on play store. Please download from here: https://github.com/TeamNewPipe/NewPipe/releases

But fake apps that look like NewPipe can be found elsewhere.    
 **CAUTION**   
ONLY DOWNLOAD FROM **Github** or **F-droid**
