### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by sanzGod717** [TeamNewPipe/NewPipe#10323]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

Network error

### Screenshots/Screen recordings

<img alt="Screenshot_20230809-191151" src="https://github.com/TeamNewPipe/NewPipe/assets/136474723/89c059c4-cc88-4e6e-862c-fa28e4b19045" width=270 />

### Affected Android/Custom ROM version

Android 10

### Affected device model

Moto e7 power

### Additional information

again this is error , please concert

**Comment by sanzGod717** [comment]
i no want uninstall the app

**Comment by hajekad** [comment]
![Screenshot_20230810-051108.jpg](https://github.com/TeamNewPipe/NewPipe/assets/107691642/14c29922-9ddd-487b-a075-8090112f4260)

same problem here, video plays for a few seconds, then this error comes up

**Comment by shadyqwer** [comment]
I see you are both using v0.25.1. There is [v0.25.2](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.25.2) update which should solve this problems (worked for me).

**Comment by AudricV** [comment]
> - [x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).

You are not using the latest version. Please update to the latest version before opening a new issue. Thank you.

**Comment by sanzGod717** [comment]
thank you i solved my problem, the app be now on last version
