### ISSUE TITLE
[Big Bug] Missing notification player actions

### ISSUE THREAD

**Issue by maringuk14** [TeamNewPipe/NewPipe#10335]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

All

### Steps to reproduce the bug

-

### Expected behavior

-

### Actual behavior

The notification player isn't working properly in android 13+, the repeat and exit button are missing.

### Screenshots/Screen recordings

-

### Logs

-

### Affected Android/Custom ROM version

-

### Affected device model

-

**Comment by tsiflimagas** [comment]
You just commented on the existing issue but still you opened a duplicate.

**Comment by maringuk14** [comment]
> 

Oh sorry, I'm new.
