### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Raj2032** [TeamNewPipe/NewPipe#1035]
I wanted to suggest a few suggestions on how to improve HookTube

- Have keyboard shortcuts for player. I wish we can press space to play and pause, pressing the up and down arrows to control the volume, pressing 'm' to mute audio etc (essentially use all the shortcuts that YouTube has).
- Allow users to sign in with a Google account to be able to like and dislike videos, and to reply and add comments without having Google to track what you watch. Also plenty of times in YouTube, whenever I post a comment, it gets marked as spam, it would be great of HookTube could have a method of placing your comments WITHOUT YouTube having to mark your comments as spam.
- Allow users to receive notifications for people who have commented or replied to a comment from other videos and allow the user to directly reply back to the user without having to leave the video.
- Have personlised videos suggested (like YouTube does).
- Have a nicer user interface and also have a dark theme.

**Comment by Raj2032** [comment]
May I ask why did you close this issue?

**Comment by mauriciocolli** [comment]
@Raj2032 take a look at the name of the repository (above the issues tab).

**Comment by Raj2032** [comment]
People have been suggesting new features in this repo, so how come I can't?
Also what does it mean by new pipe?

https://github.com/TeamNewPipe/NewPipe/issues/1034

Look at this person's issue, does it have to do with new pipe?

Also where can I go and post suggestions then?

**Comment by Raj2032** [comment]
Is this part of HookTube by any chance?

**Comment by mauriciocolli** [comment]
@Raj2032 it's not, I suggest you to try the contacts informed in their site.
