### ISSUE TITLE
Is Newpipe going to add twitch ?

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1036]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

After youtube, souncloud (soon), will you try to adapt twitch on newpipe?:D

**Comment by theScrabi** [comment]
This ia a duplicate, but yes.
