### ISSUE TITLE
Improving Video downloading experience from youtube

### ISSUE THREAD

**Issue by rishab247** [TeamNewPipe/NewPipe#10378]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Video download popup box should be shown as soon as download flow is initiated from youtube app. we should not wait for backend response for metadata and show a loader inside of the pop box.

### Why do you want this feature?

Whenever a user tries to download a video from the youtube app through sharing a video to the newPipe app we show a toast "Processing may take some time" then after a few seconds a video download popup is shown. But on slow internet, this gap between toast and popup can increase to 10+ seconds which gives users to impression of an unresponsive device as we are showing an invisible activity that may lead them to exit the download flow.

### Additional information

Rough Design mockup
https://github.com/TeamNewPipe/NewPipe/assets/47221639/28f0d4f2-8d0a-4120-bde1-4a83bb57adab

i would love to raise a pr for this. if approved.

**Comment by rishab247** [comment]
Currently, users can't interact with YouTube while waiting for the popup to be shown, as we are displaying an invisible activity on top of YouTube while initiating downloads.

https://github.com/TeamNewPipe/NewPipe/assets/47221639/2870474f-a735-47c1-93d8-5c71d71f098b

There are two ways that a user can exit the download flow:
1. When a user is trying to scroll, but they see no response from YouTube, they will panic and click on the home button.
2. When a user is trying to scroll, but they see no response, they keep on trying, which will instantly dismiss the popup before the user can read it (as shown in the above video).

**Comment by rishab247** [comment]
https://github.com/TeamNewPipe/NewPipe/assets/47221639/bf181ac6-6cb1-4a0a-a1b6-7be175a69eee

This video should make things clearer. I am using the YouTube mobile app and sharing a video with NewPipe to initiate the download process. Then I see a toast message saying 'Processing may take some time,' which indicates that the download flow has been initiated. However, I haven't seen the popup yet due to the slow internet, which gives the impression that the application is not responsive, even though it is.

Do you want to defer PR for some specific time ?

**Comment by rishab247** [comment]
Okay cool

**Comment by Stypox** [comment]
How would you plan to fix this problem? Just showing a loading indicator would be fine imo

**Comment by rishab247** [comment]
yes, i am planing to fix by showing loading indicator on download initiated. i have attached a rough mockup also
https://github.com/TeamNewPipe/NewPipe/assets/47221639/28f0d4f2-8d0a-4120-bde1-4a83bb57adab

**Comment by Stypox** [comment]
Yeah that's a good idea and can be merged before the rewrite, you can proceed, thanks!

**Comment by rishab247** [comment]
@Stypox @rishab247 please review this PR
https://github.com/TeamNewPipe/NewPipe/pull/10407
