### ISSUE TITLE
'Failed to play stream' during playback

### ISSUE THREAD

**Issue by craigphiz** [TeamNewPipe/NewPipe#1040]
• Device OS and version: android 6.0.1
• Device model/manufacturer: SG5
• Newpipe version: 0.11.5, 0.11.0 tested

What did you do?
Played https://youtu.be/EjqXXengN1s in background player. Okay until 37:49 then 'Failed to play stream'. Tried replaying. Same result. Tried playing in foreground player, did not play file at all

What did you to see?
Error 'Failed to play stream'

**Comment by theScrabi** [comment]
This is od. It plays for me.

**Comment by justanidea** [comment]
Mee too

**Comment by megaxlr** [comment]
I've had this happen to me with several videos. It seems to happen at random videos. Sometimes restarting the app resolves the issue.

I've had a suspicion that it might be because YouTube switches a streaming server or plays an ad, but I am not sure.

**Comment by aFoxWhoIsNice** [comment]
This happens to me at times as well.

**Comment by theScrabi** [comment]
I think it could also be related to buffering.

**Comment by Stypox** [comment]
@craigphiz is this still an issue?
