### ISSUE TITLE
Player skips seconds in age restricted videos (and some times in non age restricted videos)

### ISSUE THREAD

**Issue by BlastboomStrice** [TeamNewPipe/NewPipe#10405]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Find an age restricted video (like this: https://www.youtube.com/watch?v=7t0SqerlBA0 )
2. Play the video

Alternative to step 1: https://www.youtube.com/watch?v=KOv0-TyKY5A (a non age restricted video with similar issue though)

### Expected behavior

The video should play smoothly.

### Actual behavior

The video plays for 1seconds, skips about 15 seconds, plays again for 1second and so on until it finishes.

This also happens some times on non age-restricted videos, but the effect is milder, it skips about 2seconds each time instead of 15seconds.

In the recordings below the 1st clip is from the age restricted video (which is labeled as technology and science in youtube) and the second from a non age restricted video (which i s labeled as music in youtube).
As you can see in both cases, the recording timer is left far behind the video timeline (for example the timer may show that 10seconds have passed, but youtube shows that I'm watching the 20th second.)

### Screenshots/Screen recordings

Age restricted video recording - https://www.youtube.com/watch?v=7t0SqerlBA0

https://github.com/TeamNewPipe/NewPipe/assets/65232133/11aa9404-312d-4fec-8a4e-03eaf131c5b3

Non age restricted video recording - https://www.youtube.com/watch?v=KOv0-TyKY5A

https://github.com/TeamNewPipe/NewPipe/assets/65232133/dbfd7a4e-67b4-4c01-906d-9fb2ba47841e

### Affected Android/Custom ROM version

Android 11 / Miui.eu costum rom 12.6 beta version

### Affected device model

Xiaomi Mi 10

### Additional information

This has been happening the last ~3-4weeks.

**Comment by BlastboomStrice** [comment]
Update:
Exporting and then importing the database *without* restoring the settings fixed it. 🙂

Thanks for this amazing app btw!

**Comment by AudricV** [comment]
This behavior happened because you probably enabled the skip silence feature, which you can control in the playback speed dialog.
