### ISSUE TITLE
Some movies from playlists are not visible in NewPipe

### ISSUE THREAD

**Issue by pawlosck** [TeamNewPipe/NewPipe#10420]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

Compare movies from tab Video and from playlists.
I don't know if this is bug, or feature request, because movies at Youtube are not visible too.

### Expected behavior

All movies from channel should be visible in app.

### Actual behavior

Movie https://www.youtube.com/watch?v=-zP7Qg4KHqU  (Jak latać szybciej od światła? - AstroStory #1) is visible in playlist https://www.youtube.com/watch?v=-zP7Qg4KHqU&list=PL6-nym1-0TdV2u9JFl3iRq9scjguvrMLI (AstroStory) and in tab video
but movies from playlist  https://www.youtube.com/watch?v=As7M5yblk6I&list=PL6-nym1-0TdV8iLMSZCTy1BCmXsUal2f6 (AstroKawa) are not visible at Youtube  website (tab Video) and NewPipe.

### Affected Android/Custom ROM version

Android 9

### Affected device model

Samsung Galaxy S8

**Comment by pawlosck** [comment]
When I added new issue, I found it
[YouTube] No streams are returned in some playlists: YouTube returns an unsupported UI by the extractor when there are only shorts in a playlists: see https://github.com/TeamNewPipe/NewPipeExtractor/issues/1077 more details.

Probably is the same problem, but I m not sure.

**Comment by AudricV** [comment]
> movies at Youtube are not visible too.

In general, when you don't see a content on YouTube's website when logged-out, you won't see it on NewPipe.

In this case, it's an issue from the creator or YouTube, that's a pending livestream broadcast which never started.

Trying to open it would result in an error saying that `This live event will begin in a few moments.`

> Probably is the same problem, but I m not sure.

No, the contents you linked are planned live streams, not shorts.

Closing as it is not an issue of NewPipe or its extractor.

**Comment by pawlosck** [comment]
I don't know if we understand well.
If I understand well, NewPipe displays movies from Video tab, but youtube contains other tabs like Live, shorts etc, so I can't watch movies from other tabs in NewPipe and I have to watch these movies in Web Browser via Youtube.
Could you check this and tell me if you plan to display movies from other tabs.

If I know title of movie, then NewPipe find this movie and can play, but I have to use search option to find this movie.
At Youtube, movies from other tabs (live, shorts etc) are not displayed in Video tab.

**Comment by githubw0** [comment]
i NEVER login to YT.

the vid reported played w/o login, but w/ all of the usual/unsual YT tracking, in 4 diff security hardened browsers, on 2 OS-es.

i really like np. i'm not "casting stones" at it. when the error occurred & recurred, np SOLICITED ME to submit a bug report.

don't lightly shoot or disparage well-meaning "messengers." no decent dev needs to be defensive. your good reputation is still intact.
