### ISSUE TITLE
Polish is not displayed correctly and Portuguese is used instead

### ISSUE THREAD

**Issue by Hub3rt0** [TeamNewPipe/NewPipe#10438]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.25.2

### Steps to reproduce the bug

1. Go to Settings
2. Go to Content
3. Go to App language
4. Pick up "Polski"
5. Restart App
6. You will get not Polish translation but a Portuguese

### Expected behavior

I expected a Polish translation

### Actual behavior

but I get a Portuguese instead

### Screenshots/Screen recordings

<img alt="Screenshot_20230921_182756_org schabi newpipe" src="https://github.com/TeamNewPipe/NewPipe/assets/78320397/170381a8-16b5-46e2-9d76-b61c224efeae" width=276 />

### Affected Android/Custom ROM version

Android 10

### Affected device model

Honor 20 PRO

**Comment by TobiGr** [comment]
This is fixed by #10406. As a workaround, select one language above or below Polish for now. The fix will be included in the next version.
