### ISSUE TITLE
Video keeps stopping constantly

### ISSUE THREAD

**Issue by artur-py** [TeamNewPipe/NewPipe#10449]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Select any of the services (Youtube, SoundCloud...)
2. Play any video and/or audio.

### Expected behavior

Have the audio or video play out without any interruptions (except when there are Wi-fi problems)

### Actual behavior

Video/audio stops after 3\~4 seconds, and needs to be resumed by tapping the screen... but then stops again after 3\~4 seconds.

### Screenshots/Screen recordings

https://github.com/TeamNewPipe/NewPipe/assets/59511715/6e9d7c1d-5dce-41d6-80cc-8e90739009ff

### Affected Android/Custom ROM version

Android 11

### Affected device model

TCL 10 SE

### Additional information

I've tried playing different media other than the one shown  in the video, but this happened with every one of them. Don't know what might be causing this. I will try to keep testing to see if there are edge cases where this doesn't happen.

**Comment by Gabr-F** [comment]
You're sure the phone is not out of space, and you tried reinstalling NewPipe? (backup it first)
You tried with more than one good wi-fi connection?

**Comment by artur-py** [comment]
@Gabr-F yeah it turns out it was just lack of space... I'm sorry I wasted your time. I feel kinda stupid for not having realised this before. Closing this right now.
