### ISSUE TITLE
[Improvement suggestion] Make "tap to seek" more seamless

### ISSUE THREAD

**Issue by ReekyMarko** [TeamNewPipe/NewPipe#1045]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

This is kind of hard to describe, so excuse me for the horrible title. Basically what I would like to see is an improvement to the "tap to seek" feature, where you can go forward or rewind by tapping the left or right side of the screen.

Currently, NewPipe starts loading the video immediately after going forwards/backwards and if I want to seek again, I have to wait for the video to load. Basically if I want to skip 30 seconds quicky, I have to wait a couple of seconds between each skip, so that would equal to f.ex 3x3 seconds = 9 seconds.

If my explanation is not sufficient, just compare the functionality to the official YouTube app. It's much more fluent there

I might start working for a resolution to this myself if I find the time to learn (I have 0 experience in Android developement) but for now I'm just gonna leave this here if anyone wants to try and fix this.

**Comment by theScrabi** [comment]
I see. Well we will keep that in mind.

**Comment by Duppadaadadii** [comment]
Good suggestion.

**Comment by ReekyMarko** [comment]
Just found the "fast inexact seek" option and it's exactly what I'm looking for
