### ISSUE TITLE
Crash after turning on video

### ISSUE THREAD

**Issue by person10301** [TeamNewPipe/NewPipe#10459]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1.Play video in window
2.Just wait

### Logs

[crash-de-justus-newpipe-30-09_14-15-39.zip](https://github.com/TeamNewPipe/NewPipe/files/12774514/crash-de-justus-newpipe-30-09_14-15-39.zip)

### Affected Android/Custom ROM version

Android13/RealmeUI4.0

### Affected device model

Realme 9 pro 5G

### Additional information

•Animations are disabled on the device
•Mobile Internet is used

**Comment by person10301** [comment]
Wrong

**Comment by AudricV** [comment]
> de.justus.newpipe

Where did you get this potential copycat of the app? Anyway, your issue is a duplicate of several existing ones.
