### ISSUE TITLE
Randomly Skipping Video Frames

### ISSUE THREAD

**Issue by ssaagamemer** [TeamNewPipe/NewPipe#10452]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.21.15-0.22.2

### Steps to reproduce the bug

Just Start A App
And Play Any Video
And It Ramdomly Skipping Frames

### Expected behavior

Its Will Run Normally

### Actual behavior

Video Will Ramdomly Skipping Frames Video And It Happen not All Time

### Screenshots/Screen recordings

![IMG_20230926_143642](https://github.com/TeamNewPipe/NewPipe/assets/49770384/48516f9a-5f86-4ee3-941d-c1d3418d0272)
And Ramdomly Its Skipping 1 sec
![IMG_20230926_143702](https://github.com/TeamNewPipe/NewPipe/assets/49770384/1f1a366b-800b-4e37-9adb-7526f8555c98)

### Affected Android/Custom ROM version

Android 12 / MIUI Global 14.0.3

### Affected device model

Redmi Note 10

### Additional information

It Happen Any Video And Any Random Video That Happen

**Comment by ssaagamemer** [comment]
my bad its setting lol

**Comment by BigmenPixel0** [comment]
> my bad its setting lol

What setting?
