### ISSUE TITLE
[Feature Request] Add support for Hooktube links.

### ISSUE THREAD

**Issue by ikocevski** [TeamNewPipe/NewPipe#1046]
It would be great to add support for opening Hooktube links, either parsing them "natively" or just by changing the link from hooktube.com to youtube.com on the fly.

The first solution should be preferable but I guess it wouldn't be necessary because NewPipe also by default doesn't load the G spying scripts (if I'm right) so this shouldn't be that hard to implement.

Thanks.

**Comment by speednroll** [comment]
I think there is someone else who has requested it before
