### ISSUE TITLE
Repeating videos

### ISSUE THREAD

**Issue by w0ken** [TeamNewPipe/NewPipe#1047]
When looking through a channel's video list only a certain number of videos get loaded, after which the app repeats some of those already loaded videos when I keep scrolling down.

**Comment by speednroll** [comment]
but what version are you using?

**Comment by w0ken** [comment]
The latest available 0.11.5.

**Comment by speednroll** [comment]
I just did some searches and I realized that it also happens to me, but it's just some videos mixed with the new ones. It seems that the fix was partially addressed

**Comment by Stypox** [comment]
This does not seem to be happening anymore. @w0ken can you confirm?

**Comment by w0ken** [comment]
Confirmed, the issue is gone.

**Comment by Stypox** [comment]
Ok thanks
