### ISSUE TITLE
[FR] Subtitles

### ISSUE THREAD

**Issue by ZaneHannanAU** [TeamNewPipe/NewPipe#1048]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Feature request: playback and download of subtitles.

Subtitles can be retrieved by the general form

    https://video.google.com/timedtext?lang=$(LANG)&fmt=$(FMT)&v=(VIDEO_ID)

Example [`en`, `vtt`, `TkPIZtHb_fE`](https://video.google.com/timedtext?lang=en&fmt=vtt&v=TkPIZtHb_fE)

Known formats are `vtt` and some XML document type, `srt` doesn't seem to be an option. Auto subs make extremely heavy use of timed cues in all formats.

If possible, please have the options of the desktop YouTube along with the option to use fonts from local flash, such as `~/Fonts`.

Thank you for your time.

---

In addition, are there any FLOSS android applications that can combine multiple media streams into a single file? VLC half-works but the performance is nowhere near singular pipes. Thank you for your time.

**Comment by theScrabi** [comment]
Sub titles got requested already.
