### ISSUE TITLE
Videos already seen

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1050]
I have looked for this issue but its quite boring to search on a phone, so if it already exists, sorry.

  The idea is to improve the feed page by changing the background color behind the miniature of the video when it is already seen. For example, the backround is dark grey if you havent seen the video, and it become black after seeing.

**Comment by justanidea** [comment]
I habe tried to make an example:
http://i67.tinypic.com/2rrkrqd.png

**Comment by speednroll** [comment]
you only have to relate the video history with the videos of the results: if a video appears in the results that already exists in the video history, its background changes to a gray color

**Comment by justanidea** [comment]
How do you do that ?

**Comment by wb9688** [comment]
I wouldn't change the background, but I'd make the text lighter. Btw this
shouldn't be hard to add and it'd be pretty useful.

**Comment by justanidea** [comment]
:)

**Comment by justanidea** [comment]
Let's motive someone to do that! :)

**Comment by theScrabi** [comment]
> Let's motive someone to do that! :)

Haha ... well you know we have bountysource ;D

**Comment by Stypox** [comment]
Duplicate of #993
Fixed in #2288
