### ISSUE TITLE
[FR][Multiservice] play local files

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#1052]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

NP grown mature and cool ))
I think it's time to play local (video) files.
Probably Multi Service initiative should fit just fine as an implementation base for it.

**Comment by speednroll** [comment]
I'm not sure but I think that was also requested earlier

**Comment by ildar** [comment]
I seeked and couldn't find. Sorry if dup

**Comment by ildar** [comment]
Up.
Sorry for that but it's important

**Comment by ildar** [comment]
Should this FR stay here or move to
https://github.com/TeamNewPipe/NewPipeExtractor ?

**Comment by Stypox** [comment]
@ildar it has nothing to do with the extractor

**Comment by Stypox** [comment]
Also see #478

**Comment by mhmdanas** [comment]
Duplicate of #478.
