### ISSUE TITLE
[bug] when you pass a foreground video to popup and background (or vice versa) it does not save the pause or play

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1053]
• [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
• [x] I checked if the issue/feature exists in the latest version.

if I decide to change a video that is in the foreground keeping it paused this when going to popup or background is played automatically

**Comment by Stypox** [comment]
This was fixed lately
