### ISSUE TITLE
Bandcamp artist pages missing most content

### ISSUE THREAD

**Issue by ProgrammerWhoPrograms** [TeamNewPipe/NewPipe#10539]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

Go to page for Bandcamp artist/channel

### Expected behavior

It should show everything uploaded by the artist.

### Actual behavior

It only shows a few uploads. Sometimes none at all.

### Screenshots/Screen recordings

<img alt="Some content but not all" src="https://github.com/TeamNewPipe/NewPipe/assets/38004699/308b5185-b034-41c9-8e46-6a9dc943f0e9" width=270 />
<img alt="No content" src="https://github.com/TeamNewPipe/NewPipe/assets/38004699/14c4627a-de54-462a-be70-35d50e551915" width=270 />

### Affected Android/Custom ROM version

GrapheneOS UP1A.231005.007.2023103100

### Affected device model

Google Pixel 6a

### Additional information

This also occurs on the same version of NewPipe x SponsorBlock, where I first encountered the issue.

**Comment by ProgrammerWhoPrograms** [comment]
Possibly related to https://github.com/TeamNewPipe/NewPipe/issues/10538 and https://github.com/TeamNewPipe/NewPipe/issues/8920?

**Comment by pdefrancisci** [comment]
Weird. I'm observing this issue on NP 0.25.2 on a Google Pixel 6. In Android Studio's simulator of a Pixel 3a, I'm not seeing it. Same artists, also 0.25.2. I'd like to take a shot at this one, is there a way to dump logs on the device to see if we're getting failures from the extractor or something?

**Comment by ProgrammerWhoPrograms** [comment]
Dump logs from GOS or NP?
I don't know how to do either of those things, sorry.
