### ISSUE TITLE
[bug] the image of the videos do not look complete when they are vertical

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#1054]
• [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
• [x] I checked if the issue/feature exists in the latest version.

I don't know if this is duplicated.
when you select a video of the results, the picture is cut out on the sides when you see it vertically (this does not happen when you look at it horizontally)
<img src="https://framapic.org/mc0Xyi4LQFaM/eZOyGIRvJyaE.png" width=350px />

**Comment by speednroll** [comment]
![](https://framapic.org/dgDbjJ9OwGd9/r3VKXTgX2NYo.png)

**Comment by speednroll** [comment]
something to say?

**Comment by theScrabi** [comment]
Can't you pull down the scroll veiw, so the whole image gets vissible?
If not please post a link to this video so we can confirm this :)

**Comment by speednroll** [comment]
This problem usually happens to me in any video. is the picture that is on the screen before giving play to watch the video

**Comment by speednroll** [comment]
[](https://www.youtube.com/watch?v=mEfG4DMiJzM)

![](https://framapic.org/por5kVILXgDk/xCS0Kqw8b9os.png)

**Comment by theScrabi** [comment]
yes confirmed

**Comment by mauriciocolli** [comment]
With the fix everything that don't have 16/9 proportion will have black bars, that why it was implemented like this in the first place. 

This happens when in landscape and most videos have the "correct" thumbnails, so I'd not worry about it.
