### ISSUE TITLE
Notifications (get notified) for uploads from EXACTLY 3 month ago | Bug?

### ISSUE THREAD

**Issue by citizenserious** [TeamNewPipe/NewPipe#10553]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. subscribe to a channel
2. activate Notifications
3. activate "get notified"

### Expected behavior

Get Notifications **only** for new videos.

### Actual behavior

Receive notifications for **exactly 3 month old** videos, alongside the correct upload notifications

### Logs

no logs to provide, because there is no crash.

### Affected Android/Custom ROM version

Android 13 (iodéOS 4.6)

### Affected device model

star2lte

### Additional information

https://github.com/TeamNewPipe/NewPipe/issues/10237 addresses a different notification issue.

A few out of many examples: 

- got notified on 08.Nov for an upload from 08.Aug
- got notified on 06.Nov for an upload from 06.Aug
and so on

There where never a current notification for the channel I got notified for the 3 month old video, but it could be that there where notifications for current videos from other channels parallel.

My language and local setting in Android are:
Englisch (Germany)
so the time format is: dd.mm.yyyy

**Comment by citizenserious** [comment]
I don't know why, but I can not click and therefore not download the "app" folder. Tried it with different bowsers so far, would be happy to test it.

**Comment by TobiGr** [comment]
This will be fixed by #10494
