### ISSUE TITLE
Add a "Desktop mode" (so that NewPipe can play/download "Free with ads" movies)

### ISSUE THREAD

**Issue by shuttittuppitt** [TeamNewPipe/NewPipe#10588]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Youtube has recently started letting (some) movies be shown on youtube, complete & "Free with ads". However, there is a _minor_ problem with _playing_ such videos.

I only have an android tablet (Android 11, not rooted) & I use 3 browsers on it (Chrome, 1dm+, & X-Browser).
If you go to one of these youtube movies on an _android_ phone/tablet in a BROWSER using the MOBILE version of that youtube movie's URL (example = https://m.youtube.com/watch?v=ZhHRh_1ufnI) you'll see this message.
**This content can't be played on your mobile browser. Get the YouTube app to start watching.**
If you paste that URL into NewPipe's search bar & go to it, you'll see this message.
**Sorry, something went wrong.** (with a giant sad emoticon face)
If you go to that URL in a browser & choose "Desktop mode" in your browser & then refresh the page, it will change the URL into this (https://www.youtube.com/watch?app=desktop&v=ZhHRh_1ufnI) & you'll be able to play the video.

The problem (for NewPipe) is that either there is not a way to do that, or if there is, I haven't found it. Therefore, I request that NewPipe should be given a way to play such videos. It seems like a solution could be as simple as adding a "Desktop mode" option to it.

### Why do you want this feature?

I'll add that for most of the youtube movies I can find most of them somewhere else. However, _those_ sites are always getting taken down, whereas youtube is not in danger of that happening. Therefore, watching/downloading those specific movies would be made more doable if NewPipe gets this requested feature.

**Comment by AudricV** [comment]
There is nothing like a desktop mode, as the app can use any user agent it wants.

The available streams of these movies and TV shows are DRM protected, so we can't support them in the app.

Closing as won't fix.

**Comment by shuttittuppitt** [comment]
I can understand that, but I can't find out how to change _NewPipe's_ user agent. How _do_ you do that?
