### ISSUE TITLE
[feature request] Download entire playlist?

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1058]
Could there be a feature where you download an entire playlist?
Thanks!

**Comment by theScrabi** [comment]
Well was requested multiple times now. I guess we have to take this into consideration :)

**Comment by Gagggg** [comment]
That's awesome!
Love the app!

**Comment by phly95** [comment]
It would be beneficial if the playlist would be downloaded into its own folder for organizational purposes

**Comment by Gagggg** [comment]
Yup, that's a good idea

**Comment by theScrabi** [comment]
Tho it would be great if we could get a little halp on this :)

**Comment by Gagggg** [comment]
I would love to help, but I don't have any coding experience or anything,
tell me if I can do something to help!

**Comment by Bombastisch** [comment]
This one PR looks like it was stalled. I really wait for this feature, because downloading them individually takes really long.

**Comment by Gagggg** [comment]
I think you got the wrong email...

**Comment by Bombastisch** [comment]
@Gagggg which Email? No. I was talking about a PR which goal was to actually implement this feature but the creator seems to have stopped working on it.

**Comment by Gagggg** [comment]
Ah sorry :P

**Comment by phly95** [comment]
Another thing would be allowing for adding numbers before each item, which will be useful when downloading albums to keep things in the right order.

**Comment by Mkilbride** [comment]
We really need this.

**Comment by MrSoke** [comment]
It would be great to have the option to download each playlist to its own subfolder, that way it does not get mixed up with other stuff in the Newpipe folder.

**Comment by dwlsalmeida** [comment]
any updates on this?

I have some android experience, might be willing to help

**Comment by dwlsalmeida** [comment]
@Bombastisch what PR is this? Is the dude still around?

**Comment by noodlebreak** [comment]
Guys is this gonna become a reality or do I need to learn Android to help out make it one? 😄

**Comment by theScrabi** [comment]
There is a pr open, but i told him to push it back a little as there are still some older features pending.

**Comment by majkinetor** [comment]
It would also be cool to see your youtube "Library" (collection of remote playlists). Currently I must open a playlist in youtube app and then share it with New pipe.

**Comment by Butterbird** [comment]
Hello! Found this thread while trying to solve the problem with exporting more than just subscriptions from youtube to newpipe. This is not my field of expertise so, lot of headache.  I used the takeout function in google, unmarked everything but youtube (and in youtube submenu only marked favorites). Download the archive generated, open it and you will find some folders, amongs them the "favorites.json" (I then used powershell to convert to txt file) Maybe all this can be done with the youtube data API ?

**Comment by TobiGr** [comment]
See #2018

**Comment by VishalNehra** [comment]
I've rebased the dev on PR, also leaving debug apk here so interested people can try and report 
https://drive.google.com/open?id=11veL6lAop0h3GC-VyLjqpYsl1sENv6kx

**Comment by bassu** [comment]
App crashes with memory leaks during queuing of playlists to download.

Here's the stack trace:


```
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe.debug",
   "version": "0.17.1",
   "os": "Linux samsung\/dreamltexx\/dreamlte:9\/PPR1.180610.011\/G950FXXU5DSHC:user\/release-keys 9 - 28",
   "time": "2019-10-19 11:14",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] org.schabi.newpipe.download.DownloadSetting.getUrls()' on a null object reference\n\tat us.shandian.giga.service.DownloadManagerService.startMission(DownloadManagerService.java:380)\n\tat org.schabi.newpipe.util.NavigationHelper.startDownloadFromDownloadSetting(NavigationHelper.java:208)\n\tat org.schabi.newpipe.util.NavigationHelper.lambda$null$0(NavigationHelper.java:178)\n\tat org.schabi.newpipe.util.-$$Lambda$NavigationHelper$S9xQ4_P3SLn0TQp6JNT_ZkqQRRU.accept(Unknown Source:6)\n\tat io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)\n\tat io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:136)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\n"
   ],
   "user_comment": "App crashes while downloading playlist"
}
```

**Comment by bassu** [comment]
In case if download is resumed, it cannot get past first 48 downloads.

**Comment by VishalNehra** [comment]
I've already fixed most of the things. Please try new build in same link.

**Comment by Stypox** [comment]
@bassu anyway you should use the incredible bugreport to markdown converter to paste bug reports.

**Comment by lovec741** [comment]
For me:
`{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=19gXZpjXmh4",
   "content_language": "GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe.debug",
   "version": "0.17.1",
   "os": "Linux Android 9 - 28",
   "time": "2020-02-11 19:57",
   "exceptions": [
      "org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function \n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:793)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:672)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \";([A-Za-z0-9_\\$]{2})\\...\\( inside of var lea=function(a){a=a.split(\"\");var b=[function(c,d){d=(d%c.length+c.length)%c.length;c.splice(d,1)};\"\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:73)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:780)\n\t... 30 more\n"
   ],
   "user_comment": ""
}`

**Comment by DrRayThe2nd** [comment]
I can't wait for this to become a reality!

**Comment by TheOnlyRealCoder** [comment]
Just saying, an export all urls of playlist to .txt file feature seems much easier to implement and then we'll at least have the option of downloading an entire playlist with youtube-dl while we're waiting on this feature.

**Comment by SebiderSushi** [comment]
> Just saying, an export all urls of playlist to .txt file feature seems much easier to implement and then we'll at least have the option of downloading an entire playlist with youtube-dl while we're waiting on this feature.

Yeah, but if you can run `youtube-dl` you can also just use the share menu in NewPipe and copy the playlist URL. In the case of YouTube, `youtube-dl` can do the rest from there.

**Comment by TheOnlyRealCoder** [comment]
> 
> 
> > Just saying, an export all urls of playlist to .txt file feature seems much easier to implement and then we'll at least have the option of downloading an entire playlist with youtube-dl while we're waiting on this feature.
> 
> Yeah, but if you can run `youtube-dl` you can also just use the share menu in NewPipe and copy the playlist URL. In the case of YouTube, `youtube-dl` can do the rest from there.
> 
> For example, you could use the share feature from Termux to pass input on to `youtube-dl` when shared with Termux.
Hmm. I've got a work-around using one of those block-program apps which simulates touches and copies all the urls of the videos to a .txt file. Seems like using that solution together with your Termux-youtube-dl tunnel could make it fully automatic. It takes a while to simulate the touches though and it would require installing 2 apps and writing your own block program (as I can't seem to share mine).

**Comment by SebiderSushi** [comment]
You can write a script calling `youtube-dl` inside the [`termux-url-opener`](https://wiki.termux.com/wiki/Intents_and_Hooks). Then you can open the playlist in NewPipe, tap the share button at the top of the screen, select Termux and wait for `youtube-dl` to download your playlist. No additional wizardry involved.

**Comment by mhmdanas** [comment]
Subsumed by #2380.

**Comment by delinter** [comment]
Thank you very much I look forward to it. The app is fantastic keep up the good work.

**Comment by delinter** [comment]
> Well was requested multiple times now. I guess we have to take this into consideration :)

Thank you very much I love the app keep up the good work!

**Comment by arteteco** [comment]
> > Just saying, an export all urls of playlist to .txt file feature seems much easier to implement and then we'll at least have the option of downloading an entire playlist with youtube-dl while we're waiting on this feature.
> 
> Yeah, but if you can run `youtube-dl` you can also just use the share menu in NewPipe and copy the playlist URL. In the case of YouTube, `youtube-dl` can do the rest from there.
> 
> For example, you could use the share feature from Termux to pass input on to `youtube-dl` when shared with Termux.

As you say this approach doesn't work with local playlist. Being able to download a simple txt file would make it trivial to pipe it into termux to download, as a temporary solution until this feature will be finally implemented

**Comment by e-xception** [comment]
Is there any progress on the exporting to txt file or any workaround? I tried exporting newpipe data and opening the database hoping it would be stored as legible data to get a list of URLs but it wasn't.

**Comment by Thyrum** [comment]
Although I could probably write it myself, it would be easier if I can copy-paste your script. Care to share?

**Comment by e-xception** [comment]
`import sqlite3
import csv
conn = sqlite3.connect('newpipe.db')
c = conn.cursor()
c.execute("SELECT * FROM streams")
StreamData = c.fetchall()
c.execute("SELECT * FROM playlist_stream_join")
PlayListToData = c.fetchall()
#replace XX with the id of the playlist you want, found in playlist_stream_join in the newpipe database
Playlist = []
for i in range(len(PlayListToData)):
    if PlayListToData[i][0] == XX:
        Playlist.append(PlayListToData[i][1])             
YoutubeLinks = []
for i in range(len(StreamData)):
    if StreamData[i][0] in Playlist:
        YoutubeLinks.append(StreamData[i][2])
w = csv.writer(open('links.csv', 'w'), delimiter='\n')
for i in YoutubeLinks:
    w.writerow([i])`

I used this to make a csv with the youtube video links, then stripped the blank lines with notepad++ (didn't know how to do that in python lol I'm new to this stuff, if anyone reads this and knows better I'd appreciate the advice) then used [this script](https://github.com/aman-roy/mp3_downloader) which is very easily modified to download whatever you want. Use it with yt-dlp rather than youtube-dl, and just switch out youtube-dl for yt-dlp in the script. Also you need ffmpeg.exe.

**Comment by Thyrum** [comment]
And now I took the liberty of improving upon your script :). Note for every local playlist (playlist created within NewPipe), this script creates a file `playlists/{playlist-name}.csv` with all the URL's of that playlist in order, seperated by newlines. Note this script should not produce empty lines (since every video has a URL). If it somehow does, adding a check `if song[0] != '':` before `w.writerow(song)` should suffice.

```python3
#!/usr/bin/env python3

from pathlib import Path
import sqlite3
import csv

# Remove all old files to ensure all playlists are up-to-date
playlistdir = Path('playlists')
playlistdir.mkdir(exist_ok=True)

for file in playlistdir.glob('*.csv'):
    if file.is_file():
        file.unlink()

conn = sqlite3.connect('newpipe.db')
c = conn.cursor()

c.execute("SELECT * FROM playlists")
playlists = c.fetchall()

for playlist in playlists:
    # Combine streams and playlist_stream_join table to get a stream listing for a single playlist
    c.execute("SELECT url FROM streams,playlist_stream_join WHERE stream_id==uid AND playlist_id=? ORDER BY join_index ASC", (str(playlist[0])))
    with (playlistdir / f'{playlist[1]}.csv').open('w') as csvfile:
        w = csv.writer(csvfile, delimiter='\t')
        for song in c:
            w.writerow(song)
```

**Comment by m3wiscool** [comment]
5 years and still nothing?
