### ISSUE TITLE
Disable thumbnails

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#1060]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It would be nice to have the option to disable thumbnails to make the app more light on data. This will be quite helpful for those who are left in slow data after using up thier plan.

**Comment by speednroll** [comment]
Listen, this can be useful... although it should be added to almost everything, including the history and playlists. I think it's going to take a while to implement this if take it into account

**Comment by phly95** [comment]
I wonder if it could be done in a manner that blocks the app from requesting jpg files, therefore taking care of all the different screens in one go?

**Comment by justanidea** [comment]
More over it is great to save data for tiny mobile package

**Comment by TobiGr** [comment]
This has been implemented.
