### ISSUE TITLE
Show likes and dislikes on search results

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#1061]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It would be cool if we could see the rating of a video before clicking on it. I think YouTube used to have this officially before Google removed it for some reason.

**Comment by wb9688** [comment]
Do they show up on the desktop website on the search results page? If not,
that isn't possible unfortunately. Btw to check the checkboxes you've to
change `[ ]` to `[x]`

**Comment by mauriciocolli** [comment]
As @wb9688, YouTube doesn't show this information so the only way to implement would be fetching each one to get it, and that is just not possible.
