### ISSUE TITLE
Add Some Features to Download 

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#1062]
Add A Feature to share the downloaded video URL

Change the Notification on The Notification Bar To the Downloading File Name And % Completed

Add Thumpnail Seeing Feature Of Downloaded  Video

**Comment by theScrabi** [comment]
Well this would require that we wrote the download manager from the ground up. You bring up some cool ideas but this was a loot of work for us right now.

**Comment by Stypox** [comment]
The notification has been brought about in #962

**Comment by opusforlife2** [comment]
Partially done + partially duplicate of #3332.
