### ISSUE TITLE
(Feature request) Timed view in the Feed Page

### ISSUE THREAD

**Issue by MTomic2003** [TeamNewPipe/NewPipe#1065]
Maybe you can add the option for different views of different pages. I mainly requested the "Timed view" of the Feed Page because it's then easier to view the new videos from the subscriber list.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
Yea feed needs to be reworked anyway.

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/1044
