### ISSUE TITLE
Post processing error in WebM download

### ISSUE THREAD

**Issue by SShwinA** [TeamNewPipe/NewPipe#10696]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.0

### Steps to reproduce the bug

1. Download a video with Default video format as WebM

### Expected behavior

The video gets downloaded and post-processing happens with no error.  

### Actual behavior

The file gets downloaded. It displays an error while post-processing. And the downloaded WebM can't be played.  

### Screenshots/Screen recordings

<img alt="Screenshot_20231225-121600_1" src="https://github.com/TeamNewPipe/NewPipe/assets/154785786/66470a75-8863-4c68-ab2f-c746e02ce31a" width=277 />

## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=UXqq0ZvbOnk [ {type=video format=WebM quality=720p videoOnly=true}  {type=audio format=m4a bitrate=32} ]
* __Content Country:__ 
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.26.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.io.IOException: Invalid encoded length
	at org.schabi.newpipe.streams.WebMReader.readEncodedNumber(WebMReader.java:167)
	at org.schabi.newpipe.streams.WebMReader.readElement(WebMReader.java:173)
	at org.schabi.newpipe.streams.WebMReader.readElement(WebMReader.java:181)
	at org.schabi.newpipe.streams.WebMReader.parse(WebMReader.java:64)
	at org.schabi.newpipe.streams.WebMWriter.parseSources(WebMWriter.java:79)
	at us.shandian.giga.postprocessing.WebMMuxer.process(WebMMuxer.java:22)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:174)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:700)
	at us.shandian.giga.get.DownloadMission.$r8$lambda$TfhfQRw7BXa67GG5rH8lpt1NlmQ(DownloadMission.java:0)
	at us.shandian.giga.get.DownloadMission$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Tecno Spark 8c

**Comment by SShwinA** [comment]
> Do you get this error with 0.25.2?

No.   
WebM downloads were/are ok in that version.   

Just tried 0.26.0 on an older Redmi phone with Android 9 and was able to download WebM's without any issue.   

I checked the file permissions and video download folder(changed it to have a shorter path) on the phone with Android 11. It still has the error when downloading WebM's. No issues with Mp4's.

**Comment by muqeem066** [comment]
### Redmi Note 9 Pro Max (Android 12, MIUI 14)
**Error on 0.26.x version, previous version okay.**


`{"user_action":"download post-processing","request":"https://www.youtube.com/watch?v=z1h5gWuxX_Q [ {type=video format=WebM quality=360p videoOnly=true} {type=audio format=m4a bitrate=32} ]","content_language":"en-IN","content_country":"IN","app_language":"en_IN","service":"YouTube","package":"org.schabi.newpipe","version":"0.26.1","os":"Linux Android 12 - 31","time":"2023-12-27 23:21","exceptions":["java.io.IOException: Invalid encoded length\n\tat org.schabi.newpipe.streams.WebMReader.readEncodedNumber(WebMReader.java:167)\n\tat org.schabi.newpipe.streams.WebMReader.readElement(WebMReader.java:173)\n\tat org.schabi.newpipe.streams.WebMReader.readElement(WebMReader.java:181)\n\tat org.schabi.newpipe.streams.WebMReader.parse(WebMReader.java:64)\n\tat org.schabi.newpipe.streams.WebMWriter.parseSources(WebMWriter.java:79)\n\tat us.shandian.giga.postprocessing.WebMMuxer.process(WebMMuxer.java:22)\n\tat us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:174)\n\tat us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:700)\n\tat us.shandian.giga.get.DownloadMission.$r8$lambda$TfhfQRw7BXa67GG5rH8lpt1NlmQ(DownloadMission.java:0)\n\tat us.shandian.giga.get.DownloadMission$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)\n\tat java.lang.Thread.run(Thread.java:1012)\n"],"user_comment":""}`

**Comment by Stypox** [comment]
Can you check if this PR fixes it? I couldn't reproduce but I think I found out what the error was and fixed it. https://github.com/TeamNewPipe/NewPipe/pull/10912

**Comment by SShwinA** [comment]
Downloaded the apk and tried to download the same videos.   
Same result for me. It seems to be fixed.  
Thank you.
