### ISSUE TITLE
Add Ability To Download More Formats

### ISSUE THREAD

**Issue by Jithendra-V-Kumar** [TeamNewPipe/NewPipe#1069]
In Case Of Audio The Available Formats Are m4a And  webm Which Are Not Able To Play On All Music Player Android Apps. 

If You  Add a mp3 Format Downloading Option Which May be Very Helpful And Is Appreciated

**Comment by wb9688** [comment]
YouTube only offers M4A, WebM and OGG, so we can't download MP3. We can
however convert it to MP3 afterwards, we are going to implement that in the
future through an optional separate app, but there are more important
things to do at the moment. Besides that, this has been asked before, so
could you please search first? The issue template isn't there for nothing,
but you removed it.
