### ISSUE TITLE
Videos pause every 5s

### ISSUE THREAD

**Issue by BHydden** [TeamNewPipe/NewPipe#10707]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Play any video
2. See that video pauses every 5 seconds
3. Closing and restarting app unable to fix issue

### Expected behavior

Videos should not pause unless requested. 

### Actual behavior

Videos (any)  pause every 5 seconds. 

### Affected Android/Custom ROM version

Android 14 GrapheneOS UQ1A.231205.015.2023121200

### Affected device model

Google Pixel 6

**Comment by BHydden** [comment]
Bug seems to have gone away after a full device restart,  will leave issue open in case anyone else has the issue.

**Comment by BHydden** [comment]
Still happens sometimes.  Unsure what causes it. Haven't found a guaranteed trigger but once it starts it doesn't stop without force close app or device restart.

**Comment by RalfHerzog** [comment]
I have the same issue after starting a live-stream in browser app (but can be any other app as well). Even after stop playing the stream, it buffers data every 5 seconds and thus using my audio (for whatever reason) so that any newpipe video is paused.
After a phone-restart the browser and stream is closed and not causing any further interruptions. For me, it is reproducible and maybe the same reason for you

**Comment by MDP43140** [comment]
> I have the same issue after starting a live-stream in browser app (but can be any other app as well)

Maybe the issue is more specific to GrapheneOS itself, if you experienced the same thing on another app, try to ask on GrapheneOS forum

**Comment by BHydden** [comment]
> I have the same issue after starting a live-stream in browser app (but can be any other app as well). Even after stop playing the stream, it buffers data every 5 seconds and thus using my audio (for whatever reason) so that any newpipe video is paused. After a phone-restart the browser and stream is closed and not causing any further interruptions. For me, it is reproducible and maybe the same reason for you

After further testing I think this is right. Newpipe seems to only and reliably pause every 5s or so if there is a paused stream in the background of another app,  for me that is usually an audio stream in the browser. If I close the stream Newpipe works normally again,  but it should probably be able to fully take control of the foreground regardless of what's in the background.

**Comment by BHydden** [comment]
> Reopening because someone might figure out a workaround.
> 
> But just to state this outright, the straightforward solution of insistently keeping, or trying to regain, audio focus will likely backfire when the interruptions are from a more important source, like incoming calls, or user-initiated playback on another app.

I didn't consider the browser claiming authority. I guess it makes sense but I feel there should be a way to keep paused streams from interrupting foreground services 🤔 but if it can't I understand.
