### ISSUE TITLE
download cancelled silently and don't retry

### ISSUE THREAD

**Issue by mouarfff** [TeamNewPipe/NewPipe#10715]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

26.1

### Steps to reproduce the bug

Try to download a youtube video when 4g internet bitrate is low and not regular

### Expected behavior

Should download and retry if else
.should not stopped 

### Actual behavior

10 to 30% of videos don't retry to download videos

Videos with error message disapear from the download list

I need to keep legacy version because i Can force to retry Download but the non legacy version Can delete some random vidéo from the list

(Some vidéos can't be retry and some vidéo Can... After a lot of retry or another day, but if the video disapear from the list, it's not possible)

**Comment by MD77MD** [comment]
i had this problem too... perhaps its solved in this version,  I'll have to check
