### ISSUE TITLE
[Suggestion] While seeking, show the video screen more clearly

### ISSUE THREAD

**Issue by microtaka** [TeamNewPipe/NewPipe#1073]
While fast forwarding or rewinding through a video, the screen is dimmed and prev/pause/next icons are shown in the middle of the screen.

Since we want to look at the video being played while doing this, I think it would be better to not dim the screen, and maybe move the prev/pause/next icons and/or make them smaller.

Or maybe make these configurable?

Thanks for making NewPipe!

**Comment by Z3ROGRAV1TYx** [comment]
Bump

**Comment by gkeegan** [comment]
I think making the dimming effect less dark would be a simple enough solution to this.

**Comment by Z3ROGRAV1TYx** [comment]
> I think making the dimming effect less dark would be a simple enough solution to this.
Personally I feel like the buttons are a bit unnecessarily large and the screen is a bit too dimmed.
Ideally, it would be cool to have a seek preview (So when you drag on the seekbar, it shows a preview of what you will be viewing. Basically how YouTube does it). I really miss that one feature to be quite honest.
