### ISSUE TITLE
Buttons play pause headphone feature please

### ISSUE THREAD

**Issue by sunchip123** [TeamNewPipe/NewPipe#10774]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Buttons play pause headphone feature please

### Why do you want this feature?

Cause its missing

### Additional information

Play 
![image](https://github.com/TeamNewPipe/NewPipe/assets/77446268/ef78a64f-cc9b-449a-ba3b-b20b7b44accf)
pause

**Comment by invinciblevenom** [comment]
Can you describe your issue?

**Comment by MDP43140** [comment]
This is already a feature in NewPipe, what do you mean?
