### ISSUE TITLE
Download crashes

### ISSUE THREAD

**Issue by aesycos** [TeamNewPipe/NewPipe#1078]
I think the issuss is newpipe wont create music or movie download folder (of it was deleted or moved), and crashes if you try saving to non-existent location.

**Comment by theScrabi** [comment]
Please describe more detailed how to reproduce this error.

**Comment by wb9688** [comment]
@theScrabi: He means that if you set the download folder to something and then remove the folder, the downloader crashes. However when I try that, NewPipe recreates the download folder, so I think this issue could be closed.
