### ISSUE TITLE
Videos not loading on WiFi connection

### ISSUE THREAD

**Issue by Fledron** [TeamNewPipe/NewPipe#1080]
- [ X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ X ] I checked if the issue/feature exists in the latest version.

On the newest version (0.11.5) and on the 0.11.6 Beta, Videos don't load when I am connected to WiFi. I allowed everything, and my internet works, but NewPipe won't load anything. I tried different WiFi networks and rebooting my phone and reinstalling NewPipe. My phone is a Huawei p9 lite.

**Comment by theScrabi** [comment]
Odd. This should not happen.

**Comment by Fledron** [comment]
I will do logcat soon. I don't use a VPN or proxy, and the router firewall is set up to not blocking anything. What I found out after leaving the phone alone loading, is that after some minutes (~5) it actually loads. Not much, but titles and some thumbnails.

**Comment by theScrabi** [comment]
that is even more strange.

**Comment by Fledron** [comment]
here is the logcat. I don't know what exactly you need, so I just give you the complete one during my test: 
[newpipe not loading.txt](https://github.com/TeamNewPipe/NewPipe/files/1711259/newpipe.not.loading.txt)

**Comment by faissaloo** [comment]
This happens only when I'm using the London Underground WiFi, my home WiFi works fine with NewPipe

**Comment by Fledron** [comment]
Well, I am using my home WiFi. Everything else loads without problems (like Googles YouTube App, 2K Videos are no problem).

**Comment by Fledron** [comment]
bump

**Comment by theScrabi** [comment]
This is really weird. I have no clue either. @Fledron your log is big, and I could not find anything that would tell me something. The only thing I could suggest is to check:
- your firewall if you have one
- if you have root run `tcpdump -w` to see whats up
- try spoffing the NewPipe user agent, with a browser, and see if something strange happens

**Comment by Fledron** [comment]
I just tried opening a youtube Link with NewPipe again, without changing anything and it worked. Now the app works flawless. I can't tell what the problem was. It also works with firewall disabled, I don't have root access so I can't run tcpdump and nothing strange happens when I change the user agent. My IP address changed, could have to do something with that, but everything else is normal.
