### ISSUE TITLE
Playlist history duplicates issue

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1081]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.

So say you want to re-listen/re-watch a video repeatedly, everytime you listen to it, its re-added to the history watched list, this clogs it up and creates a lot of duplicates.

Can you allow that the video that was re-listened/re-watched moves up in the list as the last listened/watched video instead of creating an extra history item?

**Comment by theScrabi** [comment]
confirmed

**Comment by karyogamy** [comment]
This should be fixed as part of #1004

**Comment by wb9688** [comment]
@theScrabi: Huh? I'm not working on the db

**Comment by theScrabi** [comment]
I ment @karyogamy sorry. :D
