### ISSUE TITLE
Low audio quality when using mobile data

### ISSUE THREAD

**Issue by crawler34** [TeamNewPipe/NewPipe#10815]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Turn off WiFi, enable mobile data
2. Go to any video
3. Click download
4. The audio tab will default to either 32 or 48kbps
This also applies to the played audio, any resolution, even background playback

Closing the video and enabling Wifi, then playing the same video will make it default to 128kbps download and playback.

### Expected behavior

128kbps m4a (or at least high quality) playback and download

### Actual behavior

lowest possible quality audio playback and download

### Screenshots/Screen recordings

<img alt="Screenshot_20240204-162617" src="https://github.com/TeamNewPipe/NewPipe/assets/34932587/4af391d3-99e5-4242-97e3-1e7b50d84801" width=276 />
<img alt="Screenshot_20240204-164018" src="https://github.com/TeamNewPipe/NewPipe/assets/34932587/2daa37c6-04cd-4723-b2dc-af86dd24e7b1" width=276 />

### Affected Android/Custom ROM version

Android 14/GrapheneOS; Android 9/MIUI 11.0.8

### Affected device model

Google Pixel 6 Pro; Xiaomi Redmi 6a

### Additional information

I tested this on 2 phones and my WiFi is slower than LTE on both. This is not a new issue, I think I first noticed it a month ago, don't have a specific date. I checked and tested the settings thoroughly but didn't find anything to change this behavior.

**Comment by crawler34** [comment]
Yes, I think that's what I am talking about. I only noticed it with the latest Version despite having used NewPipe for a year on my old phone.
What did it for me was setting "limit resolution when using mobile data" to no limit, as described in the issue you linked.

**Comment by DmitrysMusic** [comment]
Happens to me as well on 3 phones with mobile data enabled, (POCO F3 on stock MIUI 14 with Android 13, Samsung Galaxy A9 2018 on One UI 2 with Android 10 and Infinix Note 12 2023 with XOS 10.6 on Android 12)  as well as when connected to "metered Wi-Fi" (when marked like this in Wi-Fi settings).
I think it's more of a application issue, rather than a "device-specifi"c one
