### ISSUE TITLE
NewPipe doesn't connect to WiFi (0.26.1)

### ISSUE THREAD

**Issue by snakeVenom4** [TeamNewPipe/NewPipe#10821]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

With phone connected to the wifi, video doesn't load: not only the stream of youtube videos, also video description and comments: nothing gets loaded.

When I switch off WiFi and use phone data, all works flawlessly.

Important to notice that is not related to my ISP / WiFi connection because the same video reached by the official Youtube application works perfectly.

I have tried disabling call over WiFi, uninstalling and reinstalling the app, clearing cache, and restarting the phone to no avail.

### Screenshots/Screen recordings

<img alt="Screenshot_20240207-140459_NewPipe" src="https://github.com/TeamNewPipe/NewPipe/assets/159330257/b541e794-cde3-4de7-b2b7-3fa01586b910" width=264 />
<img alt="Screenshot_20240207-140436_NewPipe" src="https://github.com/TeamNewPipe/NewPipe/assets/159330257/a670b987-f4be-466f-bf16-54c5756891a7" width=264 />

### Affected Android/Custom ROM version

Android 13/ Build number WW_33.0820.0810.217

### Affected device model

ASUS ROG phone 7

**Comment by AudricV** [comment]
Does it happen on other services than YouTube? We already got several issues describing similar problems. I suspect the issue is in OkHttp, the network stack we use.

**Comment by snakeVenom4** [comment]
Hi. Yes, it seems to affect all services in the app from YouTube to
bandcamp.

**Comment by Feuerswut** [comment]
Do you use a VPN/software firewall (e.g. Netguard) on your device?

Check if the app is allowed through (you have to allow it each time you reinstall another version manually)
