### ISSUE TITLE
[YouTube] Avatars, banners and subscriber count unavailable sometimes on channels

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#10826]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Open https://www.youtube.com/channel/UCxcrzzhQDj5zKJbXfIscCtg in newpipe 
2. See subscriber count unavailable (refer to screenshot)

### Expected behavior

Should fetch subsciber count 

### Actual behavior

It isn't able to fetch the aforesaid information.

### Screenshots/Screen recordings

<img alt="Screenshot_20240214_195932_NewPipe SponsorBlock" src="https://github.com/TeamNewPipe/NewPipe/assets/28833686/56ad83ef-ef3b-409b-a012-3a43e01e1aeb" width=276 />

### Affected Android/Custom ROM version

One ui 6.0 android 14

### Affected device model

Samsung s21 fe

### Additional information

Most likely requires extractor changes.

**Comment by AudricV** [comment]
YouTube is A/B testing a new channel header for user channels, we partially support it currently (only for system channels such as the sports one where it was only returned before).

I already added support for it, and this change will be soon pushed and added in a future pull request of the extractor which will be linked to this issue.

**Comment by King8976** [comment]
Newpipe not working

**Comment by oifj34f34f** [comment]
Related: https://github.com/yt-dlp/yt-dlp/issues/9893

**Comment by vmp9** [comment]
![Screenshot_2024-07-05-08-20-14-63_ee8807d2de22f1831269d80920e33a3b](https://github.com/TeamNewPipe/NewPipe/assets/168427165/26d7666d-4b9a-45d6-9440-dffb4a6e64c9)
This issue is present
