### ISSUE TITLE
feature request: add access to play media from my device not from online service, because your video player and audio player has a lot of features, like repeat and playing in the background and playback speed, thats it goodbye.

### ISSUE THREAD

**Issue by unknowndelicateboy** [TeamNewPipe/NewPipe#1085]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by JuniorJPDJ** [comment]
You should move big part of title to description :p

**Comment by unknowndelicateboy** [comment]
@JuniorJPDJ hello, i renamed the title how about that? :p
