### ISSUE TITLE
Hide videos "X days from now"

### ISSUE THREAD

**Issue by cosimini** [TeamNewPipe/NewPipe#10857]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I'm not sure this was not asked before, but I run out of search terms. The issue I'm facing is that sometimes, some of the channels I follow, upload a video that will be available in N days or M hours.

I think NewPipe do not handle this elegantly, as all the time i refresh the feed, those videos will be listed on the top. A feature I'd like to have is the possibility to hide those videos until they are out, and make them appear when they are available.

### Why do you want this feature?

Due to the way I use the app, having videos that will be available only in the future always on top of the feed list makes my feed kind of confusing.

### Additional information

In the screenshot, I'd like to hide the first video marked as "One week from now"

<img alt="Screenshot_20240229-200856_NewPipe" src="https://github.com/TeamNewPipe/NewPipe/assets/62906444/3fb55e52-128f-4be0-83cf-6b8129407a28" width=270 />

**Comment by Phantom1472** [comment]
I think what you are asking for already exists in NewPipe:
![image](https://github.com/TeamNewPipe/NewPipe/assets/6776227/cc0686f8-a349-4710-9300-bd6757d20ec7)

Just uncheck the checkbox for "Upcoming" streams.

**Comment by cosimini** [comment]
Oh crap sorry, seemed to me too stupid not to be already implemented.
