### ISSUE TITLE
Notification for new video

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1086]
Did someone already asked for notifications when a new video is uploaded in your subscription ? Its a very basic & usefull idea but nobody told about that! For the moment, i still have to receive my youtube account notification by mail to know when i can watch a new video! Quite stupid when you want to escape from youtube, isnt it? Could you try to help me to avoid this stupid solution and add a notification system ? It would be awesome ! More over, i think the fact that there isnt any notification system is THE reason why some people dont download Newpipe, so by adding it we could more and more ! 
Thanks everyone for your job :)

**Comment by speednroll** [comment]
It is a good idea! 😅

**Comment by justanidea** [comment]
Could @theScrabi tell his opinion there ?

**Comment by theScrabi** [comment]
Well first we'd need a proper feed implementation, after that works nice this feature is not fare away.

**Comment by justanidea** [comment]
Then Newpipe is coming to perfection :)

**Comment by justanidea** [comment]
Then Newpipe is coming to perfection :)

**Comment by FaizKhan5** [comment]
I want that feature because every time checking one by one in What's new is difficult.

**Comment by Stypox** [comment]
Will be fixed in #2335

**Comment by gdnzz** [comment]
Has this feature been implemented? I can't find it in the app.
