### ISSUE TITLE
Infinite loading on some videos 

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#10872]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Open https://www.youtube.com/watch?v=xTN1IcqZvOo in newpipe 
2. Play video 
3. After sone time the video will start buffering endlessly (check screenshot)

### Expected behavior

Video should play

### Actual behavior

Buffers endlessly

### Screenshots/Screen recordings

<img alt="Screenshot_20240309_115548_NewPipe SponsorBlock" src="https://github.com/TeamNewPipe/NewPipe/assets/28833686/73caa6da-8215-434a-bfac-a47884eb0d61" width=276 />

### Affected Android/Custom ROM version

One ui 6.0 android 14

### Affected device model

Samsung s21 fe

### Additional information

1. The video plays normally in other browsers 
2. It can be reproduced on any video from this channel and few other channels..
3. My internet connection is working fine

**Comment by remixedcat** [comment]
Same here latest main version (non fdroid)

**Comment by Glich440** [comment]
I'm seememgly having the same issue and even force closing the app doesn't fix it

**Comment by ABCHON** [comment]
same issue
