### ISSUE TITLE
Unable to stream certain random videos

### ISSUE THREAD

**Issue by shadowbone94** [TeamNewPipe/NewPipe#1087]
This issue occurs randomly, but certain streams show 'failed to play' error.

For example : https://m.youtube.com/watch?v=QGn35RBKeSk

**Comment by speednroll** [comment]
probably related to [this](https://github.com/TeamNewPipe/NewPipeExtractor/issues/65)

**Comment by shadowbone94** [comment]
@speednroll
Turns out it is the same issue you had. I'm able to stream it in both 360p as well as 480p, but 240p gives me this error.

So I'm closing this issue so as to avoid duplicate bug report. Thanks for cross referencing.
