### ISSUE TITLE
Implement theming

### ISSUE THREAD

**Issue by KOLANICH** [TeamNewPipe/NewPipe#109]
Allow the users to setup elements color. It should be possible to make app screen almost completely black.

**Comment by theScrabi** [comment]
My aim is to let every service usable with NewPipe have its own theme.

**Comment by KOLANICH** [comment]
I'd be acceptable only if the user is able to setup themes. IMHO different themes for different resources accessible through one specialized app is not very good idea.

**Comment by medavox** [comment]
How about a dark theme and a light theme for each?

**Comment by wb9688** [comment]
+1 for the dark and light theme
Op 5 dec. 2015 14:48 schreef "Adam Howard" <notifications@github.com>:

**Comment by theScrabi** [comment]
Hmpf as long as i don't need to implement that I guess dark and light theme would be ok.

**Comment by chschtsch** [comment]
We can use a service-specific color for some selected elements.
This app doesn't have a thin loading bar on top like on Vine or YouTube, but it would've fit best for custom color. Navigation bar is still an option, though.

**Comment by theScrabi** [comment]
Ok well I want the navigation bar to change color, everything that is red at the moment can have another color for another service. For text, and white backgrounds I guess we could make a dark theme.

**Comment by KOLANICH** [comment]
I'm against of changing of the color of navbar. IMHO it'd be better to write either service logo or name. So I think that that changing color should be optional. Also some people are colorblind, identifiing the service by color can trouble them.

**Comment by theScrabi** [comment]
Right that would become an extra feature nod the way of identifying a service.

**Comment by chschtsch** [comment]
@KOLANICH, not sure what you mean by 'display burn', but look at theme coloring in OctoDriod.

http://m.imgur.com/61WYWr4
http://m.imgur.com/5NNb4Mr

Dark theme has dark green color, so it looks fine.

And different colors for services are not problematic for colorblind people as long as it's just a design feature. I assume, there will be a navigation drawer with service labels/logos.

**Comment by KOLANICH** [comment]
>not sure what you mean by 'display burn'
Degradation of oled. Oled is organic led, organic molecules are not as stable as inorganic crystalls. Blue oleds degrade epecially fast.

>but look at theme coloring in OctoDriod.
The green bar on top burns the screen.

**Comment by chschtsch** [comment]
@KOLANICH, anyways, I don't think we should draw our attention to that.
I think a dark theme is rather readability/eye health consideration, when you use your phone in the dark.

**Comment by theScrabi** [comment]
Right dark/white themes like in OctoDroid would be a nice thing. I like this.

**Comment by KOLANICH** [comment]
It'd be nice to chance the color of material design bar on top too.
