### ISSUE TITLE
Maximum resolution/framerate setting

### ISSUE THREAD

**Issue by PacoBell** [TeamNewPipe/NewPipe#1090]
I know most people probably won't run into buffer under-runs in normal usage, but I personally like to play most videos @ 2X speed and, on my previous phone, that would cause the video to completely lock up at any resolution over 720p, let alone 720p60. My current phone (Pixel 2 XL) can handle WebM video/audio @ 2X1080p, but not 2X1080p60. Suffice it to say, unless we can implement a more robust/adaptive frame decimation mechanism, I would like to be able to set a maximum quality level that I know works for me based on empirical testing. Thanks!

**Comment by Stypox** [comment]
Doesn't the "Default resolution" option suit your needs?

**Comment by litetex** [comment]
No feedback since >2 years. 
I think we can close that issue...
