### ISSUE TITLE
NewPipe Talk 2017 is online

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1091]
As you may know I did a little talk about NewPipe at the last year CCC congress in Leipzig. I wanted to give a little impression about what happened last year, and what is planed for the future.

Huge thanks to @TheAssassin who shot cut and hosted the video :D

[Here](https://media.assassinate-you.net/video/newpipe-on-34c3) it is :)

**Comment by TobiGr** [comment]
Can we upload the slides [here](https://newpipe.schabi.org/press/various/), just like we did last year?

**Comment by TheAssassin** [comment]
@theScrabi should upload his latest version. I have a couple of versions of the slides, too, so I could upload them, too, however.

**Comment by theScrabi** [comment]
We should also update and write a new block post for this.

**Comment by TheAssassin** [comment]
Feel free to write an article.

**Comment by theScrabi** [comment]
Ok I'll do :)
Also is it possible to host the pdf's at your site, I don't want to bload the repository any further.

**Comment by TheAssassin** [comment]
Just add it to the repository, that single file won't bloat it.

**Comment by theScrabi** [comment]
It has 8 megabyte, both slides add up to 10 mb now, so I would like to remove both. However if you don't want to host them we'll find another way.

Maybe a second repo where we post assets.

**Comment by TheAssassin** [comment]
@theScrabi I thought this was in the website repository. Let's just move them there.

**Comment by theScrabi** [comment]
Move them into the website repository?
All right.

**Comment by theScrabi** [comment]
@TobiGr how can I add images to block posts?

**Comment by FaizKhan5** [comment]
Close this.
