### ISSUE TITLE
Videos play at faster speed than 1.0x even without changing settings

### ISSUE THREAD

**Issue by peaners95** [TeamNewPipe/NewPipe#10934]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1 - open video
2 - video plays at abnormal speed and skips

### Expected behavior

Video to play normally

### Actual behavior

Video plays at a strange speed and skips

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung S23

**Comment by AudricV** [comment]
Did you enable skipping silences in the playback speed settings (accessible when pressing the speed label, you may need to scroll at the bottom of the dialog)?

**Comment by peaners95** [comment]
Yes, unchecked now

**Comment by AudricV** [comment]
So is the issue gone? If so, please close the issue, thanks.
