### ISSUE TITLE
Silently fails most downloads

### ISSUE THREAD

**Issue by mouarfff** [TeamNewPipe/NewPipe#10932]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

all versions since more than 1 year

### Steps to reproduce the bug

1 : find a video to download

2 : go to download the video

3 : wait conditions : juste keep the app open and there will random fail download

Or change screen orientation 

Or just go app to the background

### Expected behavior

Should finish download and the download list will be updated and put the download in finished download section

The file is complet downloaded

### Actual behavior

The file disapear from download list, no error message, and the file is incomplete....

### Affected Android/Custom ROM version

android 13 and others

### Affected device model

xiami redmi9 - dogee s110 - homt Tom ht70

**Comment by NewNewPipe** [comment]
A topic as old as the world. It has been on the forum for a long time.
