### ISSUE TITLE
open Unsupported URL in browser

### ISSUE THREAD

**Issue by anoadragon453** [TeamNewPipe/NewPipe#1093]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I love NewPipe, so I've set it as the default handler of YouTube links practically everywhere. Now, when I get a link from someone that leads to a live stream or another unsupported URL, and it opens up in NewPipe, I get the friendly message that the URL isn't support yet. Fair enough, I'll just hit the option to open this link up in the browser and watch from there. Not as convenient, but at least it'll work.

The problem is that the 'Open the Browser' button doesn't seem to function when the URL is unsupported, leaving the user pretty much stuck.

If would be nice if that buttonf functioned, even if the URL is unsupported :)

**Comment by theScrabi** [comment]
Can you please post an example url.

**Comment by anoadragon453** [comment]
https://www.youtube.com/watch?v=bTsBZAC8ymQ&feature=youtu.be

**Comment by wb9688** [comment]
That URL works for me, but I agree this feature should be implemented.

**Comment by theScrabi** [comment]
I agree :D

**Comment by anoadragon453** [comment]
The URL changed from a Livestream to a normal video once the stream ended :P

Here's another URL of a 24/7 livestream for testing purposes: https://youtube.com/watch?v=ueupsBPNkSc

**Comment by theScrabi** [comment]
Yea. So this feature and livestream support.

**Comment by anoadragon453** [comment]
Mhm

**Comment by anoadragon453** [comment]
Awesome, thank you! I don't have an Android dev environment here to build the PR, but I'm eager to test it once it's merged :)

**Comment by theScrabi** [comment]
I intent to release the next beta soon anyway. :D

**Comment by anoadragon453** [comment]
Great, I just started using the beta!

**Comment by anoadragon453** [comment]
Pretty sure this is fixed now. Thanks!
