### ISSUE TITLE
[Feature Request] add HookTube link

### ISSUE THREAD

**Issue by daufinsyd** [TeamNewPipe/NewPipe#1094]
It would be awesome if NewPipe could open hooktube.com link besides youtube.com

Related to #917

**Comment by theScrabi** [comment]
Yea could be done.

**Comment by wb9688** [comment]
Yeah, it's like 5 minutes work. I could do this.

**Comment by theScrabi** [comment]
Will be fixed with this:
https://github.com/TeamNewPipe/NewPipe/pull/1097

**Comment by daufinsyd** [comment]
Thanks :-)
