### ISSUE TITLE
Audio-Only-Download settings

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1096]
1. Please add/change the audio-only-data containerformat. 
The Problem is, that most audioapplications think that .webm would be a videofile and doesn't list them.
The .webm container uses the VP8/VP9 videocodec and the vorbis/opus audiocodec [1].
Therefore the simplest way would be only to change the containerformat from .webm to **.ogg** for audio-only downloads. The best option would be to add libopus and change to the opus codec/container for the best decoder at this time [2].

2. Please add an option to change the bitrate. In my mind 128kb/s is not enough. ≥192kb/s, for example 256kb/s would be nice. -> #1059 

Thank you for your great work!! :)

[1] https://en.wikipedia.org/wiki/WebM
[2] https://en.wikipedia.org/wiki/Opus_(audio_format)

**Comment by gappleto97** [comment]
I would also be interested in this

**Comment by ale5000-git** [comment]
I think it would be better to also add an option to only change container and direct stream copy audio because every conversion lost quality.

**Comment by theScrabi** [comment]
We are currently not able to convert anything, we can only take what we get form youtube. And this is basicly m4a or webm.
However we through about converting. In several other threads.

**Comment by Stypox** [comment]
Closing in favour of #1059 and #507
