### ISSUE TITLE
Downloads of longer videos often fail with HTTP 401 error but can be finished by repeatedly "starting" the download again.

### ISSUE THREAD

**Issue by AdamJacobson** [TeamNewPipe/NewPipe#10977]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Select any video longer than 60 minutes
2. Choose download.
3. Select any settings. Happens for both video and audio only download.
4. Select OK
5. Download should start but quite often fails with a notification
6. Go to downloads page and note percentage completed

<img src="https://github.com/TeamNewPipe/NewPipe/assets/7927980/45db7ad8-ff70-4889-bed0-0a237dee33b7" width="400"/>

7. Click 3 dots icon and select "Start"
8. Download will resume and make progress. It's possible that the download will complete but, depending on file size, it may fail again
9. Select 3 dots icon and select "Show error"
10. Error will be shown as "HTTP 401"

<img src="https://github.com/TeamNewPipe/NewPipe/assets/7927980/31d182aa-f593-4890-aff9-d9161cdc7113" width="400"/>

### Expected behavior

Downloads should start and complete successfully without further interaction from the user.

### Actual behavior

Downloads often fail and require the user to manually start them again in order to complete.

### Screenshots/Screen recordings

<img alt="Screenshot_20240415_054519_NewPipe" src="https://github.com/TeamNewPipe/NewPipe/assets/7927980/1fc60a37-da16-48b3-9315-6d96c13afd8e" width=599 />

<img alt="Screenshot_20240415_054526_NewPipe" src="https://github.com/TeamNewPipe/NewPipe/assets/7927980/fd05d099-df72-4a96-9413-75c0fba69234" width=592 />

<img alt="Screenshot_20240415_055720_NewPipe" src="https://github.com/TeamNewPipe/NewPipe/assets/7927980/ae0c6222-4764-46c5-9767-30767ec4ddce" width=276 />

### Affected Android/Custom ROM version

Android 14 / Kernel 6.1.25

### Affected device model

Samsung Galaxy S24+

**Comment by thebackiller** [comment]
The solution is use a vpn i do with a one in my onw country and works perfectly without stops or rare things, can u test it and tell me how its work
(Sorry for my bad inglins im spanis  un saludo)

**Comment by Liace** [comment]
It happened to me also in France on a OnePlus 12. Exactly the same problem as described by OP. And also worked using a VPN. 
Why would it be, any ideas?

**Comment by Liace** [comment]
Unfortunately no, I got a static public IP

**Comment by AdamJacobson** [comment]
After dealing with this for ages, I remembered that I had configured a private DNS on my phone of `dns.adguard.com`. I disabled it and now downloads work as expected with no errors.
