### ISSUE TITLE
[Suggestion] automatically pop-up and / or audio in background

### ISSUE THREAD

**Issue by Ozyc** [TeamNewPipe/NewPipe#1098]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

I don't know anything about applications development but I have 2 features in my mind
The first is automatically pop up video when NewPipe is in background, and the second one is same but with only audio

I'm thinking it like an option to enable / disable in parameters, one for audio, the second for popup

Twitch did something like that for example

Greetings, Ozyc

**Comment by theScrabi** [comment]
Yea that sounds good, and rather easy to implement.

**Comment by speednroll** [comment]
change to popup when switching applications or play in the background if you block the screen 😃

**Comment by theScrabi** [comment]
also god

**Comment by sonho666** [comment]
Just came here to suggest the same thing. But you might want to check out how VLC (open source) implement this feature. In my opinion it's the best "PIP" out there. They also have an auto transition from in play to pop up.

**Comment by theScrabi** [comment]
@kariugamy is currently working on this.

**Comment by Stypox** [comment]
If I correctly understood the issue, this has been implemented with the option "Minimize on app switch". When the NewPipe app loses focus the chosen player is activated
