### ISSUE TITLE
Yes this will be off topic but do it.

### ISSUE THREAD

**Issue by Kahsa228** [TeamNewPipe/NewPipe#10995]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hello,newpipe👋!Can you help me, if in the version (of regular YouTube) 15.33.34 there is an error 400, I know why it is,Are you definitely interested in the API YouTube, could you give me a working APK of this version, I know that you won’t do this, but there are chances so I’ll wait for a working APK!😄
![Screenshot_20240329-104808](https://github.com/TeamNewPipe/NewPipe/assets/158554821/05d37089-a70d-4d02-9c5b-c64f73dbabfc)
[](url)

### Why do you want this feature?

I have nothing to write here.

**Comment by wb9688** [comment]
No.

**Comment by Kahsa228** [comment]
> No.

?
