### ISSUE TITLE
Make easier to play video on download

### ISSUE THREAD

**Issue by spaetz** [TeamNewPipe/NewPipe#1100]
Videos on the download page can only be interacted with via the "three dots" menu. It would be convenient if eg a click on a video starts playing it. A long press could pop up the context menu, this way the fat-fingered , could easier reach the menu.

**Comment by wb9688** [comment]
The current GigaGet-based download manager is really bad. Once we've
finished more important stuff, we'll replace it with a better one we'll
write ourselves.

**Comment by theScrabi** [comment]
closing if favour of https://github.com/TeamNewPipe/NewPipe/issues/962
