### ISSUE TITLE
[bug] when you close Newpipe playing in the background and later you open the playlist if you try to go back, you leave the application again…

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1101]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

when you hear a playlist in the background and close the newpipe application. When you select the player's notification to open the playlist, if you go back, you exit the application and do not return to the video information that was before selecting the playlist.

**Comment by speednroll** [comment]
@theScrabi could you say what do you think of this?

**Comment by theScrabi** [comment]
Yea this is something about the NavigationHelper. There are more places where this does not work properly.

**Comment by opusforlife2** [comment]
@wb9688 Isn't this expected behaviour? The notification opens the background player activity (it really should be renamed) so naturally, tapping Back would just leave the app, since there was no other activity in the backstack.

But this seems like a useful thing to have, no?

**Comment by Stypox** [comment]
Yes, this is the expected behaviour for Android apps. The back arrow on the top-left of the screen can be used instead to go back inside the app, as requested by the OP.

**Comment by wb9688** [comment]
>The back arrow on the top-left of the screen

That thing is called "up", not "back".

**Comment by opusforlife2** [comment]
I wonder why it isn't an up arrow, then.
