### ISSUE TITLE
How do I stop NewPipe 0.27.0 from playing videos in FULL screen?

### ISSUE THREAD

**Issue by shuttittuppitt** [TeamNewPipe/NewPipe#11025]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1) Make sure that you're using version 0.27.0, because this behavior is _not_ in previous versions.
2) Go to any video's page. (The video's resolution does _not_ affect this, because I've tested this with videos that had 360p (max) & videos that had 1080p & higher).
3) Going to any video's page will AUTO play that video, & haven't found any setting that changes that. Also, it will _auto_ play that video in FULL screen mode. I haven't found any settings that will change either of those 2 behaviors. (Both of those behaviors are _fully_ related, so this still counts as reporting only _one_ bug.)
4) The _only_ way to "exit" full screen mode is to use the back button, but doing that stops/pauses the _playback_ of that video.

### Expected behavior

(RELEVANT: In previous versions, the _expected_ behavior was either the _default_ behavior, or else it was easy to set it to such in the settings.)
When I go to a specific video's page & click the "Play" button, NewPipe should play that video in "Windowed" mode. (The "Window" is the area of the screen that the video occupies _before_ you click the "Play" button.) If you want to expand the video playback to FULL screen mode, then you would click on the small "[_]" button (bottom right corner of the video) to do so. You could switch between windowed playback & full screen playback _without_ stopping/pausing the video (if you didn't _want_ to stop/pause it).

(There's also the "Popup" player option, but that's _not_ what I mean by "Windowed" playback.)

### Actual behavior

(RELEVANT: This behavior was optional & easily avoidable in previous versions.)
When I go to a specific video's page & click the "Play" button, NewPipe 0.27.0 uses FULL screen playback. (Clicking "Fit/fill/zoom" changes the video's appearance, but does _not_ exit full screen playback.) The only available behaviors are full screen playback & don't play the video at all. (There's also the "Popup" player option, but that's _not_ what I mean by "Windowed" playback.)

### Screenshots/Screen recordings

A video's resolution does _not,_ affect this, because I've tested this with videos that had 360p (max) & videos that had 1080p & higher. Also, in "Video & audio > Default resolution", I use 720p, but my screen's resolution is at least 1200 x 2000.

This new behavior _removes_ a level of control over videos that previous versions allowed us. Please bring back the ability to switch between "Windowed" playback & full screen playback.

IF the ability to do that is in 0.27.0, tell me exactly which setting I need to change & what I need to change it to. Also, IF the ability to do that is in 0.27.0, change it's location/name so that we won't have to come here & ask you developers where that setting is.

### Affected Android/Custom ROM version

Android 11 & android 14 (both are not rooted)

### Affected device model

Samsung galaxy tab A7 & Samsung galaxy tab S9

**Comment by peat80** [comment]
![Screenshot_20240501-214733](https://github.com/TeamNewPipe/NewPipe/assets/32403292/b27de617-5097-40f7-ad15-28918aef365c)

**Comment by peat80** [comment]
Under settings > video and audio as always.

-Start main player in fullscreen
-Autoplay

**Comment by shuttittuppitt** [comment]
Sorry for the late response (busy day).
Both "Start main player in full screen" & "Auto play" were already turned off. Turning them back on & then off again does not fix this behavior. It may be specific to tablets (but not phones) or even specific to only Samsung tablets (happens on both my "Samsung galaxy tab A7" & my "Samsung galaxy tab S9"). Tomorrow, I'll record a video of it & the relevant settings, post it on Youtube, & then post a link to it here.

Also, on a guess, I tried rotating my device (to portrait mode), but while that _does_ work, it _only_ fixes this behavior in PORTRAIT mode, which I do _not_ want to use. (Plus, I haven't found any "portrait" (youtube) videos to test that on.) Rotating my device back to landscape mode brings the behavior back.

Does NewPipe have any way to produce a "Logcat" file or some other kind of debug file? If so, I could email _that_ to you. I've heard that there's an (android) program that can do that for other (android) programs, so I'll investigate that too.

**Comment by shuttittuppitt** [comment]
Here is the link to the promised video. I muted the sound while recording it (for file size reasons), so you won't hear anything. Also, while the "Full screen" behavior _is_ demonstrated in this video, it turns out that the "Auto-play" behavior was because I had _that_ (relevant) setting set to "Only on wi-fi". Changing it to "Never" does fix _that_ behavior.
https://m.youtube.com/watch?v=kATk6b0tDps

**Comment by peat80** [comment]
Settings > Appearance > Tablet Mode > On

should give you your desired "windowed view". 😉

**Comment by shuttittuppitt** [comment]
That _does_ fix it (finally), but it also causes a different problem. It took me a while to find the link, but the problem that this solution causes is reported here (ironically, the solution to _that_ problem was to set "Tablet mode" to OFF, thereby causing the full screen behavior).
https://github.com/TeamNewPipe/NewPipe/issues/11020
Despite what I reported (in _that_ bug report), _both_ of my tablets (Samsung galaxy tab A7 (android 11, not rooted) & Samsung galaxy tab S9 (android 14, not rooted)) are affected if "Tablet mode = On".
Essentially, if "Tablet mode = On", then I have extreme difficulty making NewPipe 0.27.0 scroll down (for a video's description), although after several seconds of repeated swiping, it _eventually_ does scroll down. So I'm left with either a solution to the full screen behavior or a solution to the "resistance to scrolling down on a video's description", but either solution _also causes_ the other bug!

**Comment by shuttittuppitt** [comment]
I can't find any setting that is named "Developer options", so where is it located? Also, I _expected_ to have to wait for a _future_ version for a fix since I didn't know that it is possible for a _retroactive_ bug fix. All bug reports that I make (for _anybody's_ programs) are intended to let somebody know that a bug _exists,_ allowing them to fix it in a future update.

**Comment by shuttittuppitt** [comment]
Oh, you mean ANDROID'S developer options. I thought you meant that NewPipe had a setting with that name. It's late now, so I'll try that tomorrow.
