### ISSUE TITLE
Scroll to top feature in comments view

### ISSUE THREAD

**Issue by marcel263** [TeamNewPipe/NewPipe#11036]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Currently there is no (obvious) way to scroll back to top. User has to manually make many scroll gestures if they are deep into comments.

A workaround is to switch to another tab (related videos) and tap comments again, this puts the video in view.

Ideally, a scroll back to top floating button.

A quick fix: double tapping the comments button (also goes for other tabs)

### Why do you want this feature?

Physically tiring to scroll many times, not user-friendly

### Additional information

Release 0.27.0

**Comment by NewNewPipe** [comment]
What I miss most is the RECORD of COMMENTS to the FILE.

**Comment by katalllen** [comment]
Hi, I'm interested in working on this issue, could I please have it assigned to me?

**Comment by katalllen** [comment]
Hi @opusforlife2, I've been working on the issue and I'm struggling to find where the logic for the comments button is instantiated, do you know where I should look for it? I've looked in the VideoDetailFragment as that is the only place the xml that has the comments icon is used, but I ca't find where the logic for the button is, as in I can't find an onClickListener or anything like that.

**Comment by Stypox** [comment]
The refactor branch contains a scrollbar which is equivalent to having a "scroll to top" button, you can download a testing APK from here: https://github.com/TeamNewPipe/NewPipe-refactor-nightly. Closing as fixed, although expect the refactor branch to be merged on the dev branch in some time.
