### ISSUE TITLE
Notification Size Problem

### ISSUE THREAD

**Issue by sstraightea** [TeamNewPipe/NewPipe#1104]
- [ X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ X ] I checked if the issue/feature exists in the latest version.

When scrolling down the notification list while background play is enabled and the music is playing, the notofication always goes to big size when updating the prograss bar. On Android 7 there's the small/big notification size thing, which NewPipe makes use of. The problem is, that scrolling does not work because it makes notifications small when scrolling, but NewPipe starts with the big notification size when the prograss bar updates. So when I want to scroll through my notifications I now have to pause the music. 

Phone: Huawei p9 lite
Android Version: 7.0
EMUI Version: 5.0.1
Model: Huawei VNS-L31

**Comment by wb9688** [comment]
>Huawei p9 lite

I've owned a Huawei P8 lite and it did some weird things (compared to stock
Android) with displaying notifications, so I guess the P9 lite does too.
Could you make a screen video of the issue?

**Comment by Fledron** [comment]
Here's a Link to the video showing the problem
https://drive.google.com/open?id=1uW2p9GP6_TODdrZz_I384-XT_mi_xS1F
 
PS: The music is bad.

**Comment by wb9688** [comment]
That indeed shouldn't happen, but is Huawei's fault. I think we could fix it by using the [standard media player notification](https://developer.android.com/reference/android/app/Notification.MediaStyle.html).

**Comment by Fledron** [comment]
Maybe make a setting under the appearance section to choose between standard and the fancy notification style.
