### ISSUE TITLE
Toggle orientation for current video only 

### ISSUE THREAD

**Issue by MildPanda** [TeamNewPipe/NewPipe#1105]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

In one of the recent updates toggle orientation toggles for all current and future watched videos. Could a setting be made to make it only toggle orientation for current video.

**Comment by wb9688** [comment]
Well, searching isn't possible on GitHub's mobile site (you could switch to
desktop though) and tagging could only be done by members of Team NewPipe.

**Comment by Opzon** [comment]
Didn't know tagging is only a team member thing, thanks. Will try a search
on desktop version. Just going to be super clunky.

**Comment by opusforlife2** [comment]
Changed already by #2907.
