### ISSUE TITLE
Pause volume recover

### ISSUE THREAD

**Issue by AlexinnoSB** [TeamNewPipe/NewPipe#11055]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

Play any video/audio from another player while the app is in background (the volume always recovers when I go back to the app) and while the volume is set at 100% for example it will always stay lower than that. It may be a bug with the resume playing setting. Please fix as it's really annoying.

**Comment by hellcat707hp** [comment]
Could this be related to #9710? If so, adding your experiences there would be helpful.
