### ISSUE TITLE
Couldn't parse the website

### ISSUE THREAD

**Issue by Yashironeko** [TeamNewPipe/NewPipe#11087]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Steps to reproduce the bug

1. When you press the download, the website will not appear, and it says "A new error encountered, check notifications" or sumthin like that... I try to press the same thing many times but it still the same... 
2. Anyway, sorry if my english is bad... I'm from Malaysia... So I'm kind of bad at it... 

### Expected behavior

I expect it to be just a normal bug... And it was my phone problem... But turns out it was some issues... I hope you can fix it as soon as possible... I appreciate your work

**Comment by LordStandridge** [comment]
Same problem here. 
![Screenshot_20240521_180711_PlayTube](https://github.com/TeamNewPipe/NewPipe/assets/170475393/de37c19d-f792-4181-9bc3-3c7b42ff8d82)

**Comment by AudricV** [comment]
@Yashironeko @LordStandridge Please install the real NewPipe from the official sources listed [here](https://github.com/TeamNewPipe/NewPipe#installation-and-updates).

Also, if the copycats you are using, which I think are coming from the Google Play Store, are not listed in #539, please add a comment there with the link where you downloaded them (from the Play Store app, you need to share the app in its details page and keep the link starting with `https://play.google.com/store/apps/details`). Thank you in advance.

@Yashironeko The `Affected version` section of the issue form is to fill the app version with the issue you are reporting (`33.0` in your case) and not to paste an error report which should come in the `Logs` section.

**Comment by Yashironeko** [comment]
Sorry if I did it wrong way, cause I don't really understand English.

And can you please fix it? I want to download a song, your app are the only
one that I think is the best, cause of the download and the feature, the
quality is also good, I couldn't imagine how I'm gonna download a song
without your app... Please fix it...

**Comment by Profpatsch** [comment]
@Yashironeko try this: https://newpipe.net/#download  (It’s the official application! Not a copy! It’s better!)

**Comment by Yashironeko** [comment]
Thanks, it worked.

Thank you so much for your hard work! Just know that I appreciate your
work!
