### ISSUE TITLE
ytp-dlp updater built-in inside the new pipe

### ISSUE THREAD

**Issue by User1l0** [TeamNewPipe/NewPipe#11099]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

ytp-dlp updater built-in inside the new pipe

### Why do you want this feature?

to prevent constant and continuous YouTube downloader to not function and error

### Additional information

There's an android software called  (Seal) it's FOSS and has ytp-dlp inside. You can easy copy the code from seal repository

**Comment by NewNewPipe** [comment]
Good idea.
I am in favor of the implementation of yt-dlp.
Yes, yes, yes !!!
