### ISSUE TITLE
Beta - app name & icon

### ISSUE THREAD

**Issue by licaon-kter** [TeamNewPipe/NewPipe#1110]
0.11.6-beta

in [KISS](https://github.com/Neamar/KISS/)
![kiss](https://lut.im/hrwi1jFsjR/Avh8UCzHdfTBnZQx.jpg)

in [NetGuard](https://github.com/M66B/NetGuard/)
![netg](https://lut.im/7gxVYNQrA3/Gw9uYO3Mmg3jj01x.jpg)

in [F-Droid](https://gitlab.com/fdroid/fdroidclient)
![fdr](https://lut.im/N8LNQLulaz/FRQUej6hHVK8wEoH.jpg)

Where should I report this?

**Comment by theScrabi** [comment]
here

**Comment by theScrabi** [comment]
why does it look so bad?

**Comment by speednroll** [comment]
When I tried it I received an android message saying that the application had an error, close or wait. although that was not as relevant as seeing two Newpipe on F-Droid, I thought it would be the same as the F-Droid releases, which publish the stable versions and the possibility of upgrading to unstable versions:
<img src="https://framapic.org/jyNMEOv3u7ex/HxjhLi6DVw2V.png" width="300">

**Comment by licaon-kter** [comment]
@speednroll This is a separate app, read here: https://gitlab.com/fdroid/fdroiddata/merge_requests/2878

**Comment by theScrabi** [comment]
right, and on top of that you should have the ability to use both if you want to.

**Comment by licaon-kter** [comment]
Maybe it needs more content in https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/beta/AndroidManifest.xml

**Comment by licaon-kter** [comment]
Or move `tools:replace`, adding it in the <manifest> directly instead of under <application> ([here](https://stackoverflow.com/a/40306041))

Or check out `tools:ignore` from other parts of the app ([here](https://stackoverflow.com/a/36626818))

**Comment by ale5000-git** [comment]
@theScrabi: [Here](https://gitlab.com/fdroid/fdroiddata/merge_requests/2878) it say "This MR has merge conflicts" and "The changes were not merged into master".

**Comment by licaon-kter** [comment]
In the Huawei share dialogue...
![pic](https://lut.im/MdunmxEcKM/vVhDHjHKmSQ75C5n.jpg)

**Comment by theScrabi** [comment]
Beta will reduce to one Item in the future. However it's sad that all these launcher don't understand that there is a different icon :/

**Comment by wb9688** [comment]
>Beta will reduce to one Item in the future

Why?

>However it's sad that all these launcher don't understand that there is a different icon :/

I agree, however it works completely fine with stock Android. I sometimes really hate that Android is so fragmented

**Comment by theScrabi** [comment]
> Why?

Because mauriciocolli wrote a menu that will pop up once you select newpipe. With that menu you can select the action you want to take.

**Comment by wb9688** [comment]
@theScrabi: I know that, but then there are still 2 options: NewPipe and NewPipe's menu to directly play it.

**Comment by mauriciocolli** [comment]
That's because someone have to create the adaptive icon for the beta yet.

**Comment by licaon-kter** [comment]
No more beta
