### ISSUE TITLE
Play Facebook video, when shared into NewPipe

### ISSUE THREAD

**Issue by iAdesanyaDaniel** [TeamNewPipe/NewPipe#11116]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

If we share a video link from Facebook, and share it to NewPipe, NewPipe should play the video stream and allow the normal minimize option and other available functions

### Why do you want this feature?

Facebook videos would also be useable on NewPipe

### Additional information

-

**Comment by AudricV** [comment]
> - [x] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).

You didn't follow this instruction of the template, as you are making a service request with this issue. Closing.
