### ISSUE TITLE
Crash when going fullscreen

### ISSUE THREAD

**Issue by CommonLoon102** [TeamNewPipe/NewPipe#11128]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Press OK on the remote when the Fullscreen button is selected

### Expected behavior

Video goes fullscreen.

### Actual behavior

Message appears: "An error occurred, see the notification".
Video stops playing and it goes back to the video details page (video cover image, details, comments, recommended videos, etc.).

### Logs

No crash, no stack trace. I cannot see the mentioned notification anywhere.

### Affected Android/Custom ROM version

Android TV OS 11 build RTM7.230903.173

### Affected device model

Sharp AQUOS-TVE21F

### Additional information

It is a TV.

I don't have a cat.

My current workaround to play videos in fullscreen is this:
Video and Audio:
  Start main player in fullscreen: On
Appearance:
  Tabled mode: On
Content:
  Show 'Next' and 'Similar' videos: Off

**Comment by CommonLoon102** [comment]
> Have you played around with the Exoplayer settings menu? There are a few toggles you can try out.

No. I cannot find any "Exoplayer" settings. Where should I look for it?
I have downloaded NewPipe via F-Droid, if that makes a difference.

**Comment by CommonLoon102** [comment]
Thanks, I found it.
Both `Disable media tunneling` and `Always use ExoPlayer's video output surface setting workaround` solved the issue. I decided to enable only the latter, I restarted the TV and it works fine! Thanks!

**Comment by balintbarna** [comment]
It works but would be nice to find this info without having to come to GitHub issues :)
