### ISSUE TITLE
 Network Error: Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] less then 1 minute into the video

### ISSUE THREAD

**Issue by Growebis** [TeamNewPipe/NewPipe#11136]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27

### Steps to reproduce the bug

1. Go to this video https://www.youtube.com/watch?v=iNPHF0hg7a0
2. watch it for a minute or less (it always stops before one minute passes).
3. Get an error message.

### Expected behavior

The videos plays fine till the end. No interruptions whatsoever.

### Actual behavior

Usually before the video hits the one minute mark, it stops and gives a network error

### Screenshots/Screen recordings

Video demonstration:
[newpipebug.webm](https://github.com/TeamNewPipe/NewPipe/assets/113867283/ad4bc303-3f2e-4823-baca-2a9a88fdba73)

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=iNPHF0hg7a0
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:203)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7

### Affected device model

Sony Xperia L1

### Additional information

I've had this happen on a couple videos before but i didn't report it since i though it was a fluke. Guess it wasn't (maybe youtube changed something again?).

**Comment by Coehill** [comment]
I experienced the same bug on Galaxy S23, Android 14, NewPipe v0.27.0

**Comment by TechnologyClassroom** [comment]
All videos stop with an error for me at 1:09 mark the last few days. Android 14 (GrapheneOS) NewPipe v0.27.0

**Comment by Growebis** [comment]
> "Response code: 403" bugs are usually temporary. If it doesn't fix itself in a few days, leave a comment.

i tried to watch the video again and it seems like its gone. I'll close this issue for now until it pops up again..

**Comment by Growebis** [comment]
Well this error poped up again with another video https://youtu.be/wV2mXcmnxmQ

I don't think this a temporary bug. I think (imo) that YouTube is changing something that's causing this.

I will reopen the bug report

**Comment by stevenaloha** [comment]
Hello! I am experiencing the same issue. It has been going on for me for the past 4 days or so. I think, just as  @Growebis says, that YouTube has something to do with this; probably changing the backend to make it harder to watch videos from third party apps...

**Comment by TechnologyClassroom** [comment]
Likely related: https://9to5google.com/2024/06/12/youtube-ad-injection/

**Comment by Growebis** [comment]
so far i haven't come across the issue so i will close this issue unless i get another video with the same error.

**Comment by 1xFF** [comment]
I think this issue should stay open instead of flip flopping, YouTube has definitely made some change causing this and it effects the usability of NewPipe.

I've had this happen completely randomly for the last few days. Exactly as described, random video gets 403'd at 0:59, 20+ minutes later I'm allowed to watch it.

**Comment by TechnologyClassroom** [comment]
Here is a screen recording of the behavior happening on the site: https://old.reddit.com/r/Piracy/comments/1dh0yem/youtubes_serverside_ads_in_action/

It is a massive, ongoing A/B test so it is hard to reproduce effectively.

**Comment by Growebis** [comment]
This issue came back and i already got 3 videos with the same error today. If i notice it happening  more/doesn't go away i may reopen it again.

**Comment by acarasimon96** [comment]
> Exactly as described, random video gets 403'd at 0:59, 20+ minutes later I'm allowed to watch it.

I've been getting the same thing too, but I found a workaround. I force stopped NewPipe and cleared its cache from the system settings, relaunched it, and I was able to play the same video that errored out past the 1 minute mark.

**Comment by 1xFF** [comment]
> I force stopped NewPipe and cleared its cache from the system settings, relaunched it, and I was able to play the same video that errored out past the 1 minute mark.

Thanks, I'll try doing that.

The issue author refuses to reopen this issue, so #11191 is the current active issue for this problem.

**Comment by Growebis** [comment]
> > I force stopped NewPipe and cleared its cache from the system settings, relaunched it, and I was able to play the same video that errored out past the 1 minute mark.
> 
> Thanks, I'll try doing that.
> 
> The issue author refuses to reopen this issue, so #11191 may be the current active issue for this problem. Though, it doesn't mention a 403 at 0:59. Just a 403 when loading.

Well the other issue suddenly got more popular and i was lazy to log into github and reopen.

> Though, it doesn't mention a 403 at 0:59. Just a 403 when loading.

For me now its happening before 0:59.

**Comment by JoeleJB** [comment]
I am in Australia (not sure if related, maybe A/B testing google depends on region?) and can no longer use Newpipe on my tablet or phone... All videos immediately give - ERROR_CODE_IO_BAD_HTTP_STATUS.

This started 5 days ago and has been constant (no flip flopping)
