### ISSUE TITLE
[Feature Request] Auto expand description

### ISSUE THREAD

**Issue by cavemandaveman** [TeamNewPipe/NewPipe#1113]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Instead of clicking to expand, can there be an option to always have the description of a video expanded?

**Comment by justanidea** [comment]
Its a good idea. I think Newpipe should be as customizable as possible :)

**Comment by B0pol** [comment]
I close this for the same reason: #2998
