### ISSUE TITLE
Add Odnoklassniki support 

### ISSUE THREAD

**Issue by X64X2** [TeamNewPipe/NewPipe#11146]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like to request the addition of Odnoklassniki as a supported platform in NewPipe. Odnoklassniki is a popular social media platform in Russia and eastern european countries, with a large user base. Adding support for Odnoklassniki would expand NewPipe's reach and provide access to a diverse range of content.

### Why do you want this feature?

NewPipe currently supports a variety of platforms, including YouTube, Peertube, and SoundCloud. Adding Odnoklassniki to this list would be a valuable addition and open up a new avenue of content for users.

### Use cases 

Users who are interested in content from Russia and the former Soviet Union countries would benefit from direct access to Odnoklassniki through NewPipe.
People who value privacy and open-source software would appreciate having an alternative way to access Odnoklassniki without sacrificing their privacy.

**Comment by AudricV** [comment]
Like written in the template, please open services requests in NewPipe Extractor repository.
