### ISSUE TITLE
[bug] the results or videos in the history do not change to the corresponding color when you select them

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#1114]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

when selecting a search in the history that was from YouTube or soundcloud it doesn't change to its corresponding color

**Comment by theScrabi** [comment]
Sorry wasn't that other bug about selected suggestions?
I may have misunderstand this, I was slipping through the previous discussion when I was in the subway.

**Comment by speednroll** [comment]
😂 hahaha, you said I do two different things about each problem. although I think it was not necessary

**Comment by theScrabi** [comment]
I thought you ment the suggested search phrases which you used already are not bound to a service. Because they are nod, and this was indeed an issue.

**Comment by speednroll** [comment]
I'm sorry, I find it quite complicated to understand what you said, assuming that I'm answering from a translator and I have very little knowledge of English, but I think we understood each other. that's good 😂🔫

**Comment by theScrabi** [comment]
You need to know your self weather it is a good idea to use platforms like Github with a translator. However I'd suggest not do it, since english is an important requirement for development, and decrypting a translator can sometimes be hard or even impossible.

**Comment by speednroll** [comment]
For that reason, it is the first time I participate proposing ideas in a project. Because of my English limitations, although I may still propose some ideas (because I can not stay still), at least until I practice my English better and it is no longer a problem
