### ISSUE TITLE
Github tags

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1115]
Is it possible to create different tags to separate youtube issues and soundcloud issues ? It would give more visibilty for the devs :)

**Comment by theScrabi** [comment]
yea maybe. Are there example issues that could be labled like this?

**Comment by justanidea** [comment]
Yes, #1071 for example :)

**Comment by TobiGr** [comment]
We should also flag everything related to `download` and maybe have a label `needs-extractor-change` or something like this.

**Comment by theScrabi** [comment]
sounds ok.
