### ISSUE TITLE
How would I import account information in the new beta?

### ISSUE THREAD

**Issue by anoraktrend** [TeamNewPipe/NewPipe#1118]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
I want to import the data I got from the takeout functionality of google, how would i do that? Or even just importing the subscription json. How would I do these things?

**Comment by theScrabi** [comment]
Sorry you may ned to wait until import export is available in stable.

**Comment by theScrabi** [comment]
I consider to do that soon :)

**Comment by mauriciocolli** [comment]
Is not from the takeout, but you can import/export subscriptions from other source.

Check out #1145.
