### ISSUE TITLE
No audio while using VLC external player with 720p videos

### ISSUE THREAD

**Issue by nipsn** [TeamNewPipe/NewPipe#11214]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Enable "Use external video player"
2. Tap on video
3. Select 720p
4. Get redirected to VLC
5. No audio

### Expected behavior

I expected the audio to play along with the video, but it's not working.

### Actual behavior

No audio playback. This seems to be a known issue with some video resolutions (i.e. 1080p or 720p 60fps), but a couple of weeks ago it stopped working as expected with 720p.

### Affected Android/Custom ROM version

Graphene OS latest

### Affected device model

Google Pixel 6a

### Additional information

As mentioned above. This seems to be a known issue for some resolutions, but I never had any issues with "regular" 720p. I noticed this behavior around a week or so ago, and I can't recall updating NewPipe at the time (I update as soon as new versions are available), so it may be on YouTube's side. 360p still works as expected, but to me it's the only one that still works as of now.

**Comment by Lavrick** [comment]
Can confirm this bug with MX player and nightly build of newpipe.

**Comment by Adobrinin** [comment]
Confirming the issue with latest NewPipe and VLC player

**Comment by nipsn** [comment]
I've just tested and 360p seems to be working fine with VLC for me at the moment. Also quickly tested on mpv-android and I see the same behaviour.

Just guessing here, but maybe 360p not working for you is a region problem? I'm currently in the EU. Spain to be more precise. Maybe 360p is not supposed to work at the moment, but this change has still not been rolled to my region... As I said, just guessing as I lack the general context of how things work on YT.

Also, I can't remember seeing the speaker icon in the past, but that's a topic for another issue I guess.

**Comment by Growebis** [comment]
I think this issue may be related to what invidious is currently facing in https://github.com/iv-org/invidious/issues/4759.

**Comment by Munkhu1** [comment]
So it won't be possible to play 1080p videos on external players anymore?
