### ISSUE TITLE
hide likes, view count, dates and other viewer metrics

### ISSUE THREAD

**Issue by mykolaso** [TeamNewPipe/NewPipe#11222]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like to remove likes, view count, currently watching, dates and all other viewer metrics, similar to the existing "hide comments" switch in settings. 

### Why do you want this feature?

helps the content to be viewed with less prejudice

### Additional information

Switch button would be preferable, but if just hiding the numbers would be easier, could you provide the code files locations for the relevant changes. Many thanks.

**Comment by mykolaso** [comment]
@opusforlife2 Didn't find seperate issue for likes. By currently watching I mean watching. Are all these things that hard to change? Isn't it just finding a few lines and setting the field to hidden? Maybe you could send the code file locations so I can clone this and change it myself? Thank you.

**Comment by mykolaso** [comment]
![Screenshot_20240715_220027_NewPipe](https://github.com/user-attachments/assets/8d1c3ac7-eddb-4284-bc66-a063a7d14b9e)

![Screenshot_20240715_220039_NewPipe](https://github.com/user-attachments/assets/4213733d-527f-4e13-8707-8b29afb252ea)

**Comment by Adam-Sahilu** [comment]
I don't know if this got implemented. But I would also love a feature where I can hide view counts, subscribers count and like counts.
