### ISSUE TITLE
Image to personnalize your background

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1123]
I know its not the most important thing that you have to do on Newpipe, but it could be pretty stylish to make your own picture as a background in the whats new section for example (instead of the dark grey part - in the dark theme-, like the picture you can make in bg in whatsapp)

**Comment by theScrabi** [comment]
Well I would not implement it, but if somone wrote a patch so this works I would not hold it back :)

**Comment by Stypox** [comment]
I'd close this, since it is not a feature that would add much to the app, there are very few people asking for it and maintainers said it is not going to be implemented
