### ISSUE TITLE
Switch to Background mode automatically when the application loses focus

### ISSUE THREAD

**Issue by leafcutterant** [TeamNewPipe/NewPipe#1124]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

For now (0.11.5), if I watch a video in NewPipe and press the home button or switch to another application, NewPipe will stop the playback and when I return, it shows the default page of the video, not the video playing. And the bigger problem is that if you press play again, it starts the video from the beginning. You lose the previous position.

Now this is a major annoyance. Astute users will discover that there is a Background mode that you can switch to, but it is tedious to do. And having to remember to do this every time you want to do something else on your phone but want to keep listening to the audio in even more tedious. I lost my position in hours-long videos many times this way.

Therefore I suggest that whenever you switch the focus away from the application while it's playing a video, NewPipe should **automatically** switch to Background mode so that the audio can keep playing and the position won't be lost. This behavior can also be optional, something that can be activated in the Settings.

But please, do something about this, because it makes the usage of the app a very rough experience. And NewPipe is like the only useful open source YouTube client for Android.

**Comment by speednroll** [comment]
this is similar to what was proposed in #1098

**Comment by leafcutterant** [comment]
I read that before posting, but it was so loosely defined I didn't realize (and still not sure) it's the same. I don't want a pop-up panel (not even with audio) and it is paramount that this happens automatically when NewPipe goes into the background.

**Comment by theScrabi** [comment]
I get your point, but I still mark it as a duplicate, since both requests are pretty similar.
