### ISSUE TITLE
Let the app auto open youtube.com links in the app, instead of the browser

### ISSUE THREAD

**Issue by cyber-sec0** [TeamNewPipe/NewPipe#11265]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

This could also help solve https://github.com/TeamNewPipe/NewPipe/issues/11264 since if the app opened YT links I could just save+copy the link anywhere, and then manually open the link in a single click.

### Why do you want this feature?

This could also help solve https://github.com/TeamNewPipe/NewPipe/issues/11264 since if the app opened YT links I could just save+copy the link anywhere, and then manually open the link in a single click.

**Comment by xad0x** [comment]
You can do this in the app info settings, there is something like open supported links or so, there you have to tap on the plus and select all. Here is a nextcloud link to a video tutorial: https://share.inmy.it/index.php/s/GtLwsHqDQq3QR9j

**Comment by cyber-sec0** [comment]
Thanks!
