### ISSUE TITLE
[Feature Request] Toggle show description during playback

### ISSUE THREAD

**Issue by cavemandaveman** [TeamNewPipe/NewPipe#1126]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It would be really useful if we could pull up the description of the video while it's playing. Not sure how the implementation would look, but for example, Skytube has it where you can swipe up to bring up the description during playback.

**Comment by opusforlife2** [comment]
Can do this after #2907.
