### ISSUE TITLE
a tipp for fdroid

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1127]
NewPipe exists for about two and half years now, and It would work without fdroid. The guys over there do a great job, and they supported NewPipe from the beginning on. They run fdroid for free, and run their setup with donated money. Therefore I thought we could give them something back :)

The current account value of the NewPipe project over at Bountysource is at bout 900 USD. I'd like to suggest to donate some of that money to fdroid. However I'd like ask you guys what you think about that, and how much we should donate, or even how:
Monthy selery, or one time payment.

I'd suggest 200$ one time or 15-20$ every month. (This month we made [80$](https://www.bountysource.com/teams/newpipe/issues)).

**Comment by ale5000-git** [comment]
I think it is a good idea and you are a good person.

My opinion about donations is that is better less money but regularly, I suggest 10$ every month.

**Comment by theScrabi** [comment]
Well but small prices always come with a higher ratio of transaction fee. Also I still didn't figure out who to get the money form bountysource to librepay other then by hand.
Normally I'd say the same and pay someone an monthy fee, but I don't know about this now.

@wb9688 @TheAssassin @coffeemakr @mauriciocolli @TobiGr since this is basically project money what do you think about the whole idea?

**Comment by TheAssassin** [comment]
I like the idea itself, but I'd rather go for @ale5000-git's suggestion donating something regularly instead of sending them a one-time donation. Being infrastructure provider, I can confirm it's better to have get regular donations to be able to pay the monthly invoices. Also, if we keep some money, we can mitigate fluctuations.
I would suggest 15 USD per month, that's a good start.

For the rest of the money, well, I plan to attend a couple of conferences this year, and was already a bit disappointed we didn't have any merch for 34C3. I'd like to order some labels, posters, etc.
(Perhaps we can even use some of this money to invite some less wealthy developers to a hack weekend or something.)

**Comment by theScrabi** [comment]
A little merge for 35c3 or other conventions (maybe even street lamps ;D) is in general a cool idea. However lets disuse this in another thread.

**Comment by TheAssassin** [comment]
Of course. I'm just saying, we should save some of the money, and invest it in something useful for advertising.

**Comment by theScrabi** [comment]
So I took a look into Bountysource, I could not find anything where we could pay someone monthly.

**Comment by theScrabi** [comment]
I'm afraid we could only claim it once.

**Comment by theScrabi** [comment]
We could create an account at [librepay](https://liberapay.com/), then I'll take about 200 from bountysource and put it into librepay. Maybe we should also consider to create a lib replay account for us. After all bountysource didn't really pay out the way wed liked to.

**Comment by TobiGr** [comment]
> We could create an account at librepay

Good idea, I think F-Droid recently added support for it. 

I'd prefer monthly donations too. But if we loose money / pay higher transaction fees, I'd also suggest to donate once.

**Comment by TheAssassin** [comment]
You could also just pay out some amount of money _once_ and then donate it using some other method. It's not _that_ complicated.

**Comment by theScrabi** [comment]
All right I think we mean the same thing :D

**Comment by theScrabi** [comment]
So next thing todo is set up a libre pay account and put some money from bountycode there.

**Comment by theScrabi** [comment]
All right so I set every thing up.

I took 200$ ~ 150€ from Bountysource as a claim:

[auszahlung.pdf](https://github.com/TeamNewPipe/NewPipe/files/1839363/auszahlung.pdf)

Now i put 144€ into libre pay:
![librepay](https://user-images.githubusercontent.com/1891273/37800461-2467ceba-2e23-11e8-8601-f0fdc38c3073.png)


And setup a monthly payment of about 13 € > 15 $ up:
![bildschirmfoto vom 2018-03-22 22-50-13](https://user-images.githubusercontent.com/1891273/37800550-717a1c08-2e23-11e8-9475-21e67e3d8cbe.png)

I'll inform you as soon as the money arrives in lib repay.

@TheAssassin @TobiGr we might need a blog post about this.

**Comment by TheAssassin** [comment]
@theScrabi feel free to write some, we'll review it.

**Comment by TobiGr** [comment]
I think it's undecent to tell everyone that we donated money. It can easily sound like "Hey we are the good ones and look how generous we are!!!!". Just take a look at Budweiser's last Super bowl commercial. It is horrible.
IMHO we should donate, but in a decent way. If you guys really want to announce it, the post shouldn't be advertising. A good occasion to inform people about it could be a post revealing our donation income after using Bountysource for almost six months. Furthermore we should thank our donators and show how effective Bountysource is (e.g. Local playlist feature completed by @karyogamy). In this post we should announce our new Liberapay account (and the recurrent donation system) too and include what we did with the donated money so far. And as a side note we can mention our F-Droid donation.

**Comment by TheAssassin** [comment]
@TobiGr I think he meant we should advertise that we accept donations via Liberapay in a blog post.

**Comment by theScrabi** [comment]
No I ment the first one, but @TobiGr is right.
Should we create a blogpost for librepay then?

**Comment by TheAssassin** [comment]
Seems like a good idea, @theScrabi.

**Comment by theScrabi** [comment]
Here we go. So its official 15€ per month to librepay.

[fdroid_librepay.pdf](https://github.com/TeamNewPipe/NewPipe/files/1864614/fdroid_librepay.pdf)

**Comment by TobiGr** [comment]
Sounds good. @theScrabi Are you going to write a post then?

**Comment by theScrabi** [comment]
Na we said we wont want to do that. I think its ok the way it is :)
