### ISSUE TITLE
Connect with orbot 

### ISSUE THREAD

**Issue by herotux** [TeamNewPipe/NewPipe#1129]
Please add an option to use proxy or using orbot like fdroid and orfox .
Many users live in countries like iran and govermentes block services and freedom.
Add this for freedom.thanks

**Comment by theScrabi** [comment]
We had that before, but we had to remove it since many data slipt through and where not send via tor. @eightheive back then you said something about making a orbot lib that could redirect all the traffic.
Whats the status about this? Can we use it?

**Comment by wb9688** [comment]
@theScrabi: We'll have to manually add code for supporting SOCKS proxies to the `Downloader` (OkHttp supports them), but AFAIK Universal Image Loader and ExoPlayer don't support SOCKS proxies. We could fork them to add support for SOCKS proxies, but I don't want to do that.

**Comment by theScrabi** [comment]
@wb9688 That's the problem. However I remembered that @eighthave said something about a lib that could somehow intercept the traffic and redirect it so we would not have to take care about that which would make things much easier.. ... Maybe I'm wrong.

**Comment by wb9688** [comment]
@theScrabi: I think he said Orbot has an option to let everything use it transparantly, but that's only possible when you've rooted your device. I'm not 100% sure though.

**Comment by theScrabi** [comment]
Well you can always use vpn even without root, this is already supported by NewPipe.

**Comment by eighthave** [comment]
The NetCipher libs provides easy methods for settng up the proxy, and getting the Orbot status.  You will still need to find all the places where you are using network libs, and apply NetCipher calls.  Universal Image Library works fine with NetCipher, we use both together in F-Droid.  With UIL, just do the NetCipher setup in the downloader class given to UIL.  I know nothing about ExoPlayer.

Perhaps it makes sense to offer a Tor mode, where things that can't be forced over Tor are disabled or hidden.  Downloading and searching always worked, as far as I remember.

**Comment by wb9688** [comment]
When #1136 is merged, it's only one line of code to use a (SOCKS or HTTP) proxy with OkHttp (and some other lines to make it a setting, but you get the point). However the actual playback won't use it then. @mauriciocolli or @karyogamy: do you know if you could set a SOCKS proxy for ExoPlayer?

**Comment by karyogamy** [comment]
I don't have much experience with proxies, but my guess is that you would want to implement and pass in a custom data source to the [Cache Factory](https://github.com/TeamNewPipe/NewPipe/blob/72a9940863c4573f8c2ed74676e2d52fd9a7e8c4/app/src/main/java/org/schabi/newpipe/player/helper/CacheFactory.java#L46), which is currently using [the default data source implementation](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java).

**Comment by eighthave** [comment]
NetCipher has simple helper methods for handling the OkHTTP3 config:

https://github.com/guardianproject/NetCipher/tree/master/sample-okhttp3/src/sample/netcipher/okhttp3

**Comment by eighthave** [comment]
oops, sorry, you were talking about Exoplayer.  It uses
HttpURLConnection.  Maybe you could make a subclass and override
makeConnection() and getConnection(), then use the NetCipher
HttpURLConnection factory stuff.

**Comment by JJohnGreenSr** [comment]
Any update? Watching my favorite PeerTube vids over Tor would be amazing!

**Comment by xmha97** [comment]
Duplicate: #992
