### ISSUE TITLE
Upload Newpipe package to F-droid

### ISSUE THREAD

**Issue by thecommitteduser** [TeamNewPipe/NewPipe#11290]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest

### Steps to reproduce the bug

Not on F-Droids release queue. Please submit

**Comment by AudricV** [comment]
We already submitted the update to F-Droid, see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15367.

We have no control on F-Droid official repository build system, please be patient.

It is not on the release queue as it has been already built, see https://monitor.f-droid.org/builds/log/org.schabi.newpipe/998#site-footer.
