### ISSUE TITLE
Cannot play any YouTube videos - Content unavailable

### ISSUE THREAD

**Issue by TheRealOne78** [TeamNewPipe/NewPipe#11304]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.27.1

### Steps to reproduce the bug

Simply try to play any YouTube video and you will get a Content unavailable error.

### Expected behavior

Play YouTube videos.

### Actual behavior

Every single YouTube video gets a "Content unavailable" error

### Screenshots/Screen recordings

![image](https://github.com/user-attachments/assets/9af84584-f712-4173-a946-d869343d5327)

### Logs

{"user_action":"requested stream","request":"https://www.youtube.com/watch?v=STSzSxJ2Gtk","content_language":"en-US","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.27.1","os":"Linux samsung/a42xqeea/a42xq:12/SP1A.210812.016/A426BXXU5DWE1:user/release-keys 12 - 31","time":"2024-07-16 23:02","exceptions":["org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Watch on the latest version of YouTube.\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:941)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:844)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)\n\tat org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)\n\tat org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16144)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)\n\tat java.lang.Thread.run(Thread.java:1012)\n"],"user_comment":""}

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy A42 5G

### Additional information

This happens with Tubular (fork) too, and a python local server called https://github.com/user234683/youtube-local that instead shows "Error: Error getting missing player or bypassing age-restriction: This video is unavailable".
![image](https://github.com/user-attachments/assets/928553eb-a29f-42ed-8a4e-05c18908214b)

When trying to play videos from other sites (like the DuckDuckGo video player), you get a "The following content is not available on this app. Watch on the latest version of YouTube." message:
![image](https://github.com/user-attachments/assets/8736feb6-9481-4467-aaca-713a6f58a3d6)

The only way to play YouTube videos is directly from the official youtube.com site (or possibly app, I haven't tried, and won't try).

It only started happening today. It's weird that I didn't see any issues yet, so maybe it's just me, or just a few users YouTube started treating as lab mices, or this happens only in my country (Romania). I hope this detail is useful.

**Comment by kreativum** [comment]
This also happens in germany. NewPipe is not the only app. The ytdl project seems to be affected as well. I think YouTube might have changed something in their API? I am not familiar with the way of accessing YouTube. But this already happened to NewPipe at least two times since i am using it.

**Comment by TheRealOne78** [comment]
After connecting to a CloudFare Warp VPN located in the same country, this error disappeared.

To check whether that's the case, I tried playing multiple videos and they worked just fine. After that, I disconnected from the VPN and the videos nolonger played.

I have a static IP address, but I can't see why YouTube would suddenly stop me from playing videos externally.

So I still cannot guarantee that this is a me-issue (YouTube silently soft-banned my IP), or I'm their new lab mice, just like the server-side ads injection adware they started using a few weeks ago on a few people.

Im case you're wondering, I also cannot use yt-dlp:
```
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] XAeKtyL2m-Q: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] XAeKtyL2m-Q: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] XAeKtyL2m-Q: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] XAeKtyL2m-Q: The following content is not available on this app.. Watch on the latest version of YouTube.
```

**Comment by lmsalustri** [comment]
Duplicate of #11139

**Comment by TheRealOne78** [comment]
Oh ok

**Comment by Chiquirod** [comment]
Gracias
