### ISSUE TITLE
Do not use IP to select app's language

### ISSUE THREAD

**Issue by aladar42** [TeamNewPipe/NewPipe#1130]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Currently it seems NewPipe uses the IP to determine the language of the app. This is pretty sub-optimal for any user that uses an out-of-country VPN, or for users who wish to use another language (I set all my applications to English, for example). It's also harder to debug translations thi way. Could it be made so that it either has a language selector, or selects the language depending on the system locale?

**Comment by theScrabi** [comment]
Thats actually a problem. You can select the content country but not the language. Tho its not that hard to implement. We need to do this.

**Comment by rattan77** [comment]
My app language changed to Malay as I am in Malaysia. It is super annoying. Wonder if I was in Germany , the language will change to German ? lol

**Comment by theScrabi** [comment]
<img src="https://user-images.githubusercontent.com/1891273/36473741-c355e79a-16f5-11e8-85c8-b5cbd46ed14f.jpeg" width=200px/>

**Comment by nv95** [comment]
I already work on it

**Comment by Stypox** [comment]
Related: #578
