### ISSUE TITLE
Use the content country of the language set in the Android settings by default

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1132]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

By default, NewPipe sets the content country to United Kingdom, but it'd be better if it looks at Android's language setting (in my case "Nederlands (Nederland)") to set it to the same content country (in my case "Nederland") by default.

**Comment by theScrabi** [comment]
Yes sounds good :)

**Comment by Stypox** [comment]
Related: #1130

**Comment by treble2019** [comment]
Not sure where to comment but I am in Germany and want the content to be en_US. Even if I setup both country and content language to US - I am getting my search results hits of videos in German - mainly if the video is available in both German and English.
Can I some how make sure everything is en_US? Any tips.

Yes, I am running the latest and also reset (clear all data) before testing this! Thanks
