### ISSUE TITLE
[bug] some channels does not show the results of their videos

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#1135]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

In beta 0.12 some channels do not show their videos, for example:

I went to watch this video
<img src="https://framapic.org/WEoEFGcjOuUW/4VoL6Hhut7wO.png" width="300">

and when I went to their channel, I received these results
<img src="https://framapic.org/QmlAJnPg3kX7/EeuhEO48QxcA.png" width="300">

**Comment by theScrabi** [comment]
Can you please paste the link to the channel.

**Comment by speednroll** [comment]
I forgot, this is the video that I put of [example](https://www.youtube.com/watch?v=K0siYUjV9UM)

the most curious thing is that this sends me to a different channel on the mobile [(link)](https://m.youtube.com/channel/UCvPh0iaCmHZPPiGAUOnP28Q) to the computer [(link)](https://m.youtube.com/user/OzzyOsbourneVEVO)

**Comment by speednroll** [comment]
this problem is not exclusive to the last beta because I tested with version 0.11.5 and even with the web browser and I received the same problem

**Comment by wb9688** [comment]
@speednroll: It's the same channel, but every channel has a channel URL, but some also have a user URL, which YouTube prefers in some cases.

**Comment by mauriciocolli** [comment]
That's not it, it seems that this channel has a special case of redirecting (one channel linked to another?):

- **Original user**:  ozzyosbourneTV
**Id**: UCe3JCin4Gnv9azlWnAs5keg
**Uploads playlist**: [/playlist?list=UUe3JCin4Gnv9azlWnAs5keg](https://www.youtube.com/playlist?list=UUe3JCin4Gnv9azlWnAs5keg)
**RSS feed**: [/feeds/videos.xml?channel_id=UCe3JCin4Gnv9azlWnAs5keg](https://www.youtube.com/feeds/videos.xml?channel_id=UCe3JCin4Gnv9azlWnAs5keg)
**Date of creation**: 2007-03-14T18:49:32.000Z

- **Redirected user**: ozzyosbourneTVSME
**Id**: UCvPh0iaCmHZPPiGAUOnP28Q
**Uploads playlist**: [/playlist?list=UUvPh0iaCmHZPPiGAUOnP28Q](https://www.youtube.com/playlist?list=UUvPh0iaCmHZPPiGAUOnP28Q)
**RSS feed**: [/feeds/videos.xml?channel_id=UCe3JCin4Gnv9azlWnAs5keg](https://www.youtube.com/feeds/videos.xml?channel_id=UCe3JCin4Gnv9azlWnAs5keg)
**Date of creation**: 2009-09-02T23:16:00.000Z

Interesting indeed, but not NewPipe's fault.

**Comment by speednroll** [comment]
but do you have any solution? it only happens on phones

**Comment by mauriciocolli** [comment]
It happens everywhere, see: (note the http status code and the location header, typical of a redirect)

```bash
$ curl --head 'https://www.youtube.com/channel/UCe3JCin4Gnv9azlWnAs5keg'

HTTP/2 303 
[...]
location: https://www.youtube.com/channel/UCvPh0iaCmHZPPiGAUOnP28Q
[...]
```

The one that you get the vevo channel is another video: [K0siYUjV9UM (the one that gets redirected)](https://www.youtube.com/watch?v=K0siYUjV9UM) and [dvNXF7aGP2s (from the vevo channel)](https://www.youtube.com/watch?v=dvNXF7aGP2s). I'm just guessing that you got to the other one by mistake since they are so alike.
