### ISSUE TITLE
Crash when playing videos on Android TV

### ISSUE THREAD

**Issue by senol3476** [TeamNewPipe/NewPipe#11359]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

Play Stream 
Player Error type ERROR_CODE_FAİLED_RUNTİME_CHEK occourd while platin YouTube 
![IMG20240728170048](https://github.com/user-attachments/assets/d1ed5e15-428d-4ac8-9b72-141d7e62fb46)

### Expected behavior

Android Tv ve Android Tv Boxlarda sorunsuz bir şekilde çalışmasını Ayrıca telegramdan sorunlar tartışılırsa güzel olur.

### Actual behavior

![IMG20240728170048](https://github.com/user-attachments/assets/4c5cd48a-dea9-4ecf-8154-854824cc789f)

### Affected Android/Custom ROM version

Android Tv Box Android Tv OS 11

### Affected device model

Next

### Additional information

Tüm ayarları kontrol ettim ona rağmen çöküyor

**Comment by AudricV** [comment]
Thanks for your bug report.

Your device seems to be the one indicated at this page: https://www.next.com.tr/start-4k-tv-box. Is it the right one?

> Tüm ayarları kontrol ettim ona rağmen çöküyor

According to a machine translation, this means "I checked all the settings but it still crashes". Please use English at all places for all of your future issues.

Did you try to toggle the ExoPlayer settings related to surface output workaround and decoder fallback (both at the same time enabled, one at a time)? If not, please try to do so and see if playback works.

If the issue still happen or if you already tried this, could you install [Just Video Player from F-Droid](https://f-droid.org/fr/packages/com.brouken.player/) and see if you can play a video on your device (for instance one which you would download with NewPipe) with this app?

**Comment by senol3476** [comment]
Thank you. After changing the ExoPlayer settings to surface output, the
problem disappeared.

28 Tem 2024 Paz 18:49 tarihinde Audric V. ***@***.***> şunu
yazdı:
