### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by orpkeeg** [TeamNewPipe/NewPipe#11368]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

27.2

### Steps to reproduce the bug

Network error 

### Expected behavior

Network error 

### Actual behavior

Network error 

### Screenshots/Screen recordings

[546aeb5d-e8d4-464c-af85-236b86755291.zip](https://github.com/user-attachments/files/16408361/546aeb5d-e8d4-464c-af85-236b86755291.zip)

### Logs

{"user_action":"requested stream","request":"https://www.youtube.com/watch?v=TL5zPys0ufk","content_language":"en-US","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.27.2","os":"Linux Android 11 - 30","time":"2024-07-29 00:36","exceptions":["[javax.net](http://javax.net/).ssl.SSLHandshakeException: [java.security](http://java.security/).cert.CertPathValidatorException: Trust anchor for certification path not found.\n\tat [com.android.org](http://com.android.org/).conscrypt.SSLUtils.toSSLHandshakeException([SSLUtils.java:362](http://sslutils.java:362/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngine.convertException([ConscryptEngine.java:1134](http://conscryptengine.java:1134/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngine.readPlaintextData([ConscryptEngine.java:1089](http://conscryptengine.java:1089/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngine.unwrap([ConscryptEngine.java:876](http://conscryptengine.java:876/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngine.unwrap([ConscryptEngine.java:747](http://conscryptengine.java:747/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngine.unwrap([ConscryptEngine.java:712](http://conscryptengine.java:712/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket([ConscryptEngineSocket.java:849](http://conscryptenginesocket.java:849/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$SSLInputStream.access$100([ConscryptEngineSocket.java:722](http://conscryptenginesocket.java:722/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket.doHandshake([ConscryptEngineSocket.java:238](http://conscryptenginesocket.java:238/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket.startHandshake([ConscryptEngineSocket.java:217](http://conscryptenginesocket.java:217/))\n\tat okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)\n\tat okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)\n\tat okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)\n\tat okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)\n\tat okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)\n\tat okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)\n\tat okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)\n\tat okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)\n\tat org.schabi.newpipe.DownloaderImpl.execute([DownloaderImpl.java:163](http://downloaderimpl.java:163/))\n\tat [org.schabi.newpipe.extractor.downloader.Downloader.post](http://org.schabi.newpipe.extractor.downloader.downloader.post/)([Downloader.java:143](http://downloader.java:143/))\n\tat org.schabi.newpipe.extractor.downloader.Downloader.postWithContentType([Downloader.java:175](http://downloader.java:175/))\n\tat org.schabi.newpipe.extractor.downloader.Downloader.postWithContentTypeJson([Downloader.java:217](http://downloader.java:217/))\n\tat [org.schabi.newpipe.extractor.services.youtube](http://org.schabi.newpipe.extractor.services.youtube/).YoutubeParsingHelper.getMobilePostResponse([YoutubeParsingHelper.java:1149](http://youtubeparsinghelper.java:1149/))\n\tat [org.schabi.newpipe.extractor.services.youtube](http://org.schabi.newpipe.extractor.services.youtube/).YoutubeParsingHelper.getJsonIosPostResponse([YoutubeParsingHelper.java:1132](http://youtubeparsinghelper.java:1132/))\n\tat [org.schabi.newpipe.extractor.services.youtube](http://org.schabi.newpipe.extractor.services.youtube/).extractors.YoutubeStreamExtractor.fetchIosMobileJsonPlayer([YoutubeStreamExtractor.java:962](http://youtubestreamextractor.java:962/))\n\tat [org.schabi.newpipe.extractor.services.youtube](http://org.schabi.newpipe.extractor.services.youtube/).extractors.YoutubeStreamExtractor.onFetchPage([YoutubeStreamExtractor.java:823](http://youtubestreamextractor.java:823/))\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage([Extractor.java:60](http://extractor.java:60/))\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo([StreamInfo.java:77](http://streaminfo.java:77/))\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo([StreamInfo.java:72](http://streaminfo.java:72/))\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3([ExtractorHelper.java:118](http://extractorhelper.java:118/))\n\tat org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY([ExtractorHelper.java:0](http://extractorhelper.java:0/))\n\tat org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual([SingleFromCallable.java:43](http://singlefromcallable.java:43/))\n\tat io.reactivex.rxjava3.core.Single.subscribe([Single.java:4855](http://single.java:4855/))\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual([SingleDoOnSuccess.java:35](http://singledoonsuccess.java:35/))\n\tat io.reactivex.rxjava3.core.Single.subscribe([Single.java:4855](http://single.java:4855/))\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual([MaybeFromSingle.java:41](http://maybefromsingle.java:41/))\n\tat io.reactivex.rxjava3.core.Maybe.subscribe([Maybe.java:5377](http://maybe.java:5377/))\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain([MaybeConcatArray.java:153](http://maybeconcatarray.java:153/))\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request([MaybeConcatArray.java:78](http://maybeconcatarray.java:78/))\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe([FlowableElementAtMaybe.java:66](http://flowableelementatmaybe.java:66/))\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual([MaybeConcatArray.java:42](http://maybeconcatarray.java:42/))\n\tat io.reactivex.rxjava3.core.Flowable.subscribe([Flowable.java:16144](http://flowable.java:16144/))\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual([FlowableElementAtMaybe.java:36](http://flowableelementatmaybe.java:36/))\n\tat io.reactivex.rxjava3.core.Maybe.subscribe([Maybe.java:5377](http://maybe.java:5377/))\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual([MaybeToSingle.java:46](http://maybetosingle.java:46/))\n\tat io.reactivex.rxjava3.core.Single.subscribe([Single.java:4855](http://single.java:4855/))\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$[SubscribeOnObserver.run](http://subscribeonobserver.run/)([SingleSubscribeOn.java:89](http://singlesubscribeon.java:89/))\n\tat io.reactivex.rxjava3.core.Scheduler$[DisposeTask.run](http://disposetask.run/)([Scheduler.java:644](http://scheduler.java:644/))\n\tat [io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run](http://io.reactivex.rxjava3.internal.schedulers.scheduledrunnable.run/)([ScheduledRunnable.java:65](http://scheduledrunnable.java:65/))\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call([ScheduledRunnable.java:56](http://scheduledrunnable.java:56/))\n\tat [java.util.concurrent.FutureTask.run](http://java.util.concurrent.futuretask.run/)([FutureTask.java:266](http://futuretask.java:266/))\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$[ScheduledFutureTask.run](http://scheduledfuturetask.run/)([ScheduledThreadPoolExecutor.java:301](http://scheduledthreadpoolexecutor.java:301/))\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker([ThreadPoolExecutor.java:1167](http://threadpoolexecutor.java:1167/))\n\tat java.util.concurrent.ThreadPoolExecutor$[Worker.run](http://worker.run/)([ThreadPoolExecutor.java:641](http://threadpoolexecutor.java:641/))\n\tat [java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:923](http://thread.java:923/))\nCaused by: [java.security](http://java.security/).cert.CertificateException: [java.security](http://java.security/).cert.CertPathValidatorException: Trust anchor for certification path not found.\n\tat [com.android.org](http://com.android.org/).conscrypt.TrustManagerImpl.verifyChain([TrustManagerImpl.java:677](http://trustmanagerimpl.java:677/))\n\tat [com.android.org](http://com.android.org/).conscrypt.TrustManagerImpl.checkTrustedRecursive([TrustManagerImpl.java:554](http://trustmanagerimpl.java:554/))\n\tat [com.android.org](http://com.android.org/).conscrypt.TrustManagerImpl.checkTrusted([TrustManagerImpl.java:510](http://trustmanagerimpl.java:510/))\n\tat [com.android.org](http://com.android.org/).conscrypt.TrustManagerImpl.checkTrusted([TrustManagerImpl.java:428](http://trustmanagerimpl.java:428/))\n\tat [com.android.org](http://com.android.org/).conscrypt.TrustManagerImpl.getTrustedChainForServer([TrustManagerImpl.java:356](http://trustmanagerimpl.java:356/))\n\tat [android.security.net](http://android.security.net/).config.NetworkSecurityTrustManager.checkServerTrusted([NetworkSecurityTrustManager.java:94](http://networksecuritytrustmanager.java:94/))\n\tat [android.security.net](http://android.security.net/).config.RootTrustManager.checkServerTrusted([RootTrustManager.java:90](http://roottrustmanager.java:90/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$2.checkServerTrusted([ConscryptEngineSocket.java:161](http://conscryptenginesocket.java:161/))\n\tat [com.android.org](http://com.android.org/).conscrypt.Platform.checkServerTrusted([Platform.java:250](http://platform.java:250/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngine.verifyCertificateChain([ConscryptEngine.java:1644](http://conscryptengine.java:1644/))\n\tat [com.android.org](http://com.android.org/).conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)\n\tat [com.android.org](http://com.android.org/).conscrypt.NativeSsl.readDirectByteBuffer([NativeSsl.java:568](http://nativessl.java:568/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngine.readPlaintextDataDirect([ConscryptEngine.java:1095](http://conscryptengine.java:1095/))\n\tat [com.android.org](http://com.android.org/).conscrypt.ConscryptEngine.readPlaintextData([ConscryptEngine.java:1079](http://conscryptengine.java:1079/))\n\t... 62 more\nCaused by: [java.security](http://java.security/).cert.CertPathValidatorException: Trust anchor for certification path not found.\n\t... 76 more\n"],"user_comment":""}

### Affected Android/Custom ROM version

LineageOS (Android 11)

### Affected device model

OnePlus

### Additional information

none

**Comment by lmsalustri** [comment]
This is a nightmare without formatting.
```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.\n\tat com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)\n\tat com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)\n\tat com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)\n\tat com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)\n\tat com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)\n\tat com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)\n\tat com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)\n\tat com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)\n\tat okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)\n\tat okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)\n\tat okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)\n\tat okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)\n\tat okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)\n\tat okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)\n\tat okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)\n\tat okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)\n\tat org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:163)\n\tat org.schabi.newpipe.extractor.downloader.Downloader.post(Downloader.java:143)\n\tat org.schabi.newpipe.extractor.downloader.Downloader.postWithContentType(Downloader.java:175)\n\tat org.schabi.newpipe.extractor.downloader.Downloader.postWithContentTypeJson(Downloader.java:217)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getMobilePostResponse(YoutubeParsingHelper.java:1149)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonIosPostResponse(YoutubeParsingHelper.java:1132)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchIosMobileJsonPlayer(YoutubeStreamExtractor.java:962)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:823)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)\n\tat org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)\n\tat org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16144)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:923)\nCaused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.\n\tat com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:677)\n\tat com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)\n\tat com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)\n\tat com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)\n\tat com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)\n\tat android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)\n\tat android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)\n\tat com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)\n\tat com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)\n\tat com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)\n\tat com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)\n\tat com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)\n\tat com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)\n\t... 62 more\nCaused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.\n\t... 76 more
```

**Comment by MikkyDoubleB** [comment]
I'm getting this also. It happens whem trying to view any video. Newest release from github.

**Comment by maacruz** [comment]
I can confirm this bug on 0.27.2
It happens trying to open any YT video.
My phone is a Huawey P-Smart (2018)

Crash report:
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=RJw3Y-3EBFo
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ YouTube
* __Version:__ 0.27.2
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:355)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:163)
	at org.schabi.newpipe.extractor.downloader.Downloader.post(Downloader.java:143)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentType(Downloader.java:175)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentTypeJson(Downloader.java:217)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getMobilePostResponse(YoutubeParsingHelper.java:1149)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonIosPostResponse(YoutubeParsingHelper.java:1132)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchIosMobileJsonPlayer(YoutubeStreamExtractor.java:962)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:823)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16144)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:659)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:537)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:493)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:416)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:337)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:203)
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:592)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351)
	... 55 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 66 more

```
</details>
<hr>
