### ISSUE TITLE
Notifications not arriving until app opened

### ISSUE THREAD

**Issue by exefile2** [TeamNewPipe/NewPipe#11361]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

Subscribe a channel and allow notification. The app will not give you the notification until you open the app and refresh the feed.

### Expected behavior

The app should push notifications in background just like YouTube does.

### Actual behavior

The app will not give you the notification until you open the app and refresh the feed.

### Screenshots/Screen recordings

Na

### Logs

Na

### Affected Android/Custom ROM version

Android 10 MIUI

### Affected device model

Dandelion

**Comment by exefile2** [comment]
> Did you turn on new stream notifications?

All are turned on!
![Screenshot_2024-07-29-21-26-18-244_org schabi newpipe](https://github.com/user-attachments/assets/31bcaa8d-7152-4e0a-8a1d-6c556ae89211)

**Comment by lmsalustri** [comment]
> > Did you turn on new stream notifications?
> 
> All are turned on!
> ![Screenshot_2024-07-29-21-26-18-244_org schabi newpipe](https://github.com/user-attachments/assets/31bcaa8d-7152-4e0a-8a1d-6c556ae89211)
> 
@exefile2 They meant the "New stream notifications" setting in Settings > Notifications

**Comment by exefile2** [comment]
> > > Did you turn on new stream notifications?
> > 
> > 
> > All are turned on!
> 
> @exefile2 They meant the "New stream notifications" setting in Settings > Notifications
As I said earlier, all are turned on from settings to all notifications.

**Comment by exefile2** [comment]
> And you've added the required channels? By default zero are selected.

See the screenshot

**Comment by exefile2** [comment]
> Oh, my bad. I had to unblock images.
> 
> > Android 10 MIUI
> 
> MIUI is notorious for messing with notification settings. Could you check all OS settings related to notifications to see if they're correctly set?

As I mentioned earlier, all the settings are turned on and other apps are working well.

**Comment by exefile2** [comment]
> Have you configured all the nonsense settings mentioned in https://dontkillmyapp.com/xiaomi ? Sounds like the OS is killing the app.

Yeah. I also tried the app in my one ui, same thing is happening.

**Comment by aryaritesh08** [comment]
> What about notification channels? The OS setting, not Youtube channels. Newpipe has different ones for update notifs, player notifs, etc.

As I said earlier, all are turned on

**Comment by exefile2** [comment]
Nah, tried all, not worked. It doesn't send any notifications until the app is opened. Happening in every devices...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aryaritesh08** [comment]
Bruh. Android obviously

________________________________

**Comment by exefile2** [comment]
Bruh. Obviously Android

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aryaritesh08** [comment]
Redmi note 7s  miui 12.5
Galaxy a14 one ui 6.1 ndroid 14
Redmi 9i miui 12 Android 10
Galaxy s23 one ui 6.1 Android 14

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
