### ISSUE TITLE
Suggest adding support for bilibili.com

### ISSUE THREAD

**Issue by yisa3** [TeamNewPipe/NewPipe#11376]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add bilibili.com to the list of supported sites

### Why do you want this feature?

Currently there are more than a billion people in the world using Chinese, a lot of high-quality Chinese content exists only on bilibili.com, other sites do not have a backup. newpipe gives me a lot of convenience to watch videos, I very much hope that newpipe to provide support for bilibili!

**Comment by asandikci** [comment]
try PipePipe
