### ISSUE TITLE
Can't fetch channel (maybe pronouns confuse extractor?)

### ISSUE THREAD

**Issue by StevenAlexander44** [TeamNewPipe/NewPipe#11374]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

27.2

### Steps to reproduce the bug

Subscribe to https://youtube.com/@hbmmaster and reload your subscriptions.

### Expected behavior

Reload successfully.

### Actual behavior

An error message.

### Affected Android/Custom ROM version

Lineage 21

### Affected device model

Multiple and seems N/A

**Comment by lmsalustri** [comment]
No logs to confirm, but seems like a duplicate of my issue #11353

**Comment by StevenAlexander44** [comment]
> No logs to confirm, but seems like a duplicate of my issue #11353
Yes, sorry.

> If you know it's right there, why wouldn't you add it to the description when it is clearly asked for?
I forgot to copy it the first time, waited so I could reload the channel list, and missed the popup that gives an error (it doesn't come as a notification), and didn't want to wait another 5 minutes.
