### ISSUE TITLE
Some video names crash the downloader

### ISSUE THREAD

**Issue by paulcmal** [TeamNewPipe/NewPipe#1140]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I noticed video names containing quotation marks `"` crash the UI when attempting to download a video. I get prompted with the download menu. Clicking OK crashes Newpipe. Removing the quotation marks in the filename to be saved makes it possible to download without crashing.

I did not report the issue through Sentry because I don't have a mail client on my phone (and do not wish to have one at the moment) and because I found how to reproduce the crash. [Here](https://www.youtube.com/watch?v=ROhyYT39aM0) is a video you can try it on. I could reproduce the issue with both 0.11.5 and beta 0.11.6.

Thank you for maintaining NewPipe, it's a wonder! Lots of datalove to you <3

**Comment by paulcmal** [comment]
Hi, sorry to bump this topic but this issue is still present in the latest releases. If you have any idea what part of the system for me to poke around, i'll be more than happy to try, although i have exactly 0 experience with android dev.

I've stumbled upon [default_file_charset_value](https://github.com/TeamNewPipe/NewPipe/blob/51ff371083b85b0a3ddc9d5c5dd9596e5573075c/app/src/main/java/org/schabi/newpipe/util/FilenameUtils.java#L22) which from what i gathered defines the list of forbidden characters in filename (although the variable name suggests otherwise), but i couldn't find where its default value resides. Am i looking in the right direction?

**Comment by theScrabi** [comment]
@paulcmal sorry that I didn't answer. Yes, indeed that looks like a good starting point.
What this line does it it takes the value you can set in the settings `Settings > Downloads > et charset`
The value for the key `R.string.default_file_charset_value is defined here:
https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values/settings_keys.xml#L186

which again points to this line here: 
https://github.com/TeamNewPipe/NewPipe/blob/6b66f40bcbbe7518fdb460a9410cc9f02936924f/app/src/main/res/values/strings.xml#L302

**Comment by paulcmal** [comment]
OK. I'm sorry but i don't think i can do it. I just spent 3 hours trying to setup gradle and android sdk to compile NewPipe. However, i was every time unsuccessful:
```
> Could not find method google() for arguments [] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
I read the [debian docs](https://wiki.debian.org/AndroidTools) about Android Tools and some stackoverflow topics but that did not help me. If you've got any pointers, i'm willing to try again :)

**Comment by theScrabi** [comment]
Thats noremally an issue of the gradle version:

> I read the debian docs

I hightly recomend you to use the official version of android studio form here:
https://developer.android.com/studio/

Versions distributed by package repositories are mostly outdated.

**Comment by paulcmal** [comment]
Hi, due to some problems with my phone (eMMC near-death making internal storage super unreliable) i will not be able to try and work with this issue. As far as i know this issue was still present in the latest releases and should really not take long for anyone with proper knowledge of the codebase to fix :)

Wish you all the best!

**Comment by Stypox** [comment]
@karyogamy was this fixed by your recent pr?

**Comment by kapodamy** [comment]
@Stypox 
same as #2229 is fixed
