### ISSUE TITLE
Strange "jump cuts" appearing in videos that don't appear in the web browser

### ISSUE THREAD

**Issue by bluemods** [TeamNewPipe/NewPipe#11402]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

- Open any video (I am using https://www.youtube.com/watch?v=uGfVn-cyz3o and I am playing it at 720p / 60fps)
- Watch and listen carefully and compare it to watching the same video from a browser
- You will notice jump cuts in NewPipe that cut out any "dead air" (short pauses between speaking). Just compare the first 15 seconds and you'll see it.

It is subtle but if you compare the same video directly you should notice it. Seems to happen on every single video since this morning. You can see that the video freezes for a moment when the "cut" happens.

### Expected behavior

I expect the video to play un-modified with no modifications to the video feed.

### Actual behavior

Videos are playing in a strange jump cut style, where pauses between sentences in talking are cut out and the video freezes. This is very strange behavior. Maybe an A/B test from Google?
Check screen recording and compare to video playback from browser.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/f1d7d5b9-85c3-44ac-b430-fde49a64f787

### Affected Android/Custom ROM version

Android 14

**Comment by adamf30** [comment]
Is "Fast-forward during silence" on?

**Comment by bluemods** [comment]
> Is "Fast-forward during silence" on?

I can't find such a setting in the app. Where can I find that?

**Comment by bluemods** [comment]
Thank you very much, I don't know how I enabled that. Problem is solved.
