### ISSUE TITLE
Support Coursera

### ISSUE THREAD

**Issue by KOLANICH** [TeamNewPipe/NewPipe#1141]
A relevant project with the compatible license (LGPL-3.0) is https://github.com/coursera-dl/coursera-dl

**Comment by wb9688** [comment]
Does Coursera require a login?

**Comment by theScrabi** [comment]
Thats not the only service with login. We might consider to implement an interface for login.

People requested spotify premium support ... same issue.

**Comment by KOLANICH** [comment]
>Does Coursera require a login?

It does for most videos. Sometimes videos are available without login (see `--preview` flag).

**Comment by theScrabi** [comment]
Hm ... yea well. If we do something lets do it full way or no way. Otherwise it would be frustrating.

**Comment by theScrabi** [comment]
But honestly I don't know when we can offer support for services with login. Lets first focus on getting other services work properly at all. Multyservice is really early bird and still needs a loot of fixes before its good usable :)

**Comment by speednroll** [comment]
I know this goes on another topic, but can you also consider the inclusion of bandcamp? this is something similar to what happens with coursera-dl & youtube-dl [with bandcamp-dl](https://github.com/iheanyi/bandcamp-dl) :v

**Comment by justanidea** [comment]
What kind of account would it be ? A personnal account (so they collect data)? A anonym account (like the Newpipe account, used for everybody or idk)?

**Comment by speednroll** [comment]
it would be great if we can do something similar to yalp store, be able to use a particular account of the app if you want to remain anonymous or your own account

**Comment by KOLANICH** [comment]
Using a shared account would likely cause dmca takedown: they would say that it allows downloading videos in violation of ToS. In fact they care not about copyright on videos (since most of them are free), but about their "honor code" which forbids an individual to have more than one account, to share solutions (some solutions to quizes have been taken down from github) and to pass quizes done not by the person account belongs to (a shared token would mean that anyone using this token will be able to do it). IMHO it's better to implement socks proxy for that, so the ones seeking for privacy could use Tor and implejent a feature "enroll into all courses possible and simulate watching random videos automatically" to resist profiling.

**Comment by KOLANICH** [comment]
Still not implemented.

**Comment by KOLANICH** [comment]
Moved the issue to https://github.com/TeamNewPipe/NewPipeExtractor/issues/402
