### ISSUE TITLE
[feature request] add "add to playlist" to the list of related videos

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#1142]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

can add to the menu of the related videos the option of "add to playlist" too?
It's strange, this option is in the results but not in the information of a video, in the list of related videos

**Comment by speednroll** [comment]
it is also needed in the list of videos of the channels

**Comment by theScrabi** [comment]
Hm well discussable. 
As always, if someone implements this I'm going to merge it :)

**Comment by karyogamy** [comment]
@theScrabi Issues like this are quite easy to fix and it's probably a good place for new contributors to join in. Do you think it would be a good idea to introduce a new tag, like `up-for-grabs`, to encourage first-timer PRs?

**Comment by wb9688** [comment]
I agree with that.

**Comment by justanidea** [comment]
Talking about that, i would like to say i want to partcipate a bit even if i havent so many experience. Im still trying to put an emulator on my pc (failed, my pc cant do virtual device ) But if I find a way to fix it, I would like to try to do it :)

**Comment by justanidea** [comment]
Is there any place where you could talk about that, and help new contributors without crowding github with useless messages? (= messages not talking about issues, which are alerting everybody for nothing)

**Comment by TobiGr** [comment]
You can join our [IRC channel](http://webchat.freenode.net/?channels=%23newpipe).

**Comment by justanidea** [comment]
Thanks

**Comment by theScrabi** [comment]
> up-for-grabs

Yes why not

**Comment by wb9688** [comment]
I don't think "up-for-grabs" would be the best name for it, I'd rather name
it something like "beginner-friendly'.

**Comment by speednroll** [comment]
what he proposes @wb9688 seems to me a better idea. By the way, this other request #1002 could also tag it in the same way

**Comment by larsgw** [comment]
`good first issue` seems to be the standard label for this: https://help.github.com/articles/about-labels/#using-default-labels

**Comment by jMuzsik** [comment]
Hi, I'd be up for doing it, though this would also be introductory for me in terms of Java and Android Development so I may take a bit of time to finish but definitely less then a week, if that's cool with ya'll.

**Comment by Shan11812** [comment]
@jMuzsik are you still working on this? I'd like to give a try if you are not.

**Comment by jMuzsik** [comment]
Please do it, I apologize, never intentionally got to it...

**Comment by Somethingweirdhere** [comment]
@Shan11812 Hey there, how it's going? I would really like to try next if you don't want to anymore.
