### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by EspWifi8266** [TeamNewPipe/NewPipe#11432]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1 open Newpipe
2 try to open any video
3 the video loads but does not scroll, you can try to go forward and backward it loads the preview but it does not play

### Expected behavior

The video plays correctly and the seconds tick by

### Actual behavior

The seconds remain still and the video does not scroll (I tried to clear the app data but nothing changed)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Motorola Edge 20 lite

**Comment by EspWifi8266** [comment]
I tried on android emulator on windows and there the videos play correctly...

**Comment by amsitlab** [comment]
I have same problem, just 3 minutes ago

**Comment by EspWifi8266** [comment]
I tried it now and it didn't give me the problem anymore, but a screenshot wouldn't be much use, it's as if the video was paused when in reality it's playing, and even closing it and trying to delete the app data, the problem persisted (even with tubular form there was the problem at that time)

**Comment by EspWifi8266** [comment]
Sorry, I misread... However, unfortunately I didn't make a screen record... However, if it can be useful, it didn't show me any errors, it was as if the video was paused even though it was playing, only a static image was displayed.

**Comment by EspWifi8266** [comment]
Sorry I closed it by mistake...

**Comment by EspWifi8266** [comment]
Ok thank you very much, I will close the issues. If the problem returns I will take a screen record and open an issues width the video.
