### ISSUE TITLE
Importing an OPML

### ISSUE THREAD

**Issue by The-Demon-Prosecutor** [TeamNewPipe/NewPipe#1143]
Hey,
I'm a bit confused regarding importing an OPML file.
If I try to import it as an .opml I get the error message - No valid ZIP file. If I zip the file up, I don't get my subscriptions in the menu.
I tried to export and see how the database is stored. Apparently it's a .db and .db-journal file, but I'm not sure how would I convert the .opml into those files (I have tried to simply rename the file to newpipe.db and newpipe.db-journal).

**Comment by mauriciocolli** [comment]
That option is only to backup/restore the database (subscriptions, history, searches, etc.).

Regarding OPML support, I already completed the implementation and will open a pull request later today, so expect it to be available in the next version of NewPipe.

See #698

**Comment by The-Demon-Prosecutor** [comment]
Ah I see.
Thank you for replying

**Comment by pokyah** [comment]
Hi ! 

I've exported an OPML file of my YouTube channels RSS feeds from feedly but I can't make NewPipe app to import the file.

Here is an example of the structure of the OPML  file produced by feedly: 

`<?xml version="1.0" encoding="UTF-8"?>

<opml version="1.0">
    <head>
        <title>Subscriptions in feedly Cloud</title>
    </head>
    <body>
        <outline text="YouTube Subscriptions" title="YouTube Subscriptions">
            <outline type="rss" text="Numberphile" title="Numberphile" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCoxcjq-8xIDTYp3uz647V5A" htmlUrl="https://www.youtube.com/channel/UCoxcjq-8xIDTYp3uz647V5A"/>
            <outline type="rss" text="Mickaël Launay" title="Mickaël Launay" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC4PasDd25MXqlXBogBw9CAg" htmlUrl="https://www.youtube.com/channel/UC4PasDd25MXqlXBogBw9CAg"/>
            <outline type="rss" text="Kurzgesagt – In a Nutshell" title="Kurzgesagt – In a Nutshell" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q" htmlUrl="https://www.youtube.com/channel/UCsXVk37bltHxD1rDPwtNM8Q"/>
        </outline>
    </body>
</opml>`

What should I edit to make sure that Newspipe will read and import it properly?

Thanks for your help
