### ISSUE TITLE
Support timestamps in video URLs

### ISSUE THREAD

**Issue by anoadragon453** [TeamNewPipe/NewPipe#1144]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Opening a YouTube URL such as https://www.youtube.com/watch?v=Qd2JYMNycBo&t=2325s or https://youtu.be/tBiPumGnVT4?t=2m17s should skip to those times when the video is played.

It's confusing when someone posts a 50m video and links a specific moment, and NewPipe starts it at the beginning :)

**Comment by wb9688** [comment]
We had this a long time ago, but we've accidentally removed it and this has
already been reported in another issue, so this can be closed.

**Comment by anoadragon453** [comment]
@wb9688 Ah OK, can you link the other issue number? I couldn't find it when I was searching.

**Comment by wb9688** [comment]
#861

**Comment by anoadragon453** [comment]
Ah there it is, thank you!
