### ISSUE TITLE
Subscription order

### ISSUE THREAD

**Issue by thanksgivingmeal** [TeamNewPipe/NewPipe#1146]
I have subscribed to numerous channels on YouTube and the way the new videos feed works is as follows:
For each channel I see their newest video, in the order of the first channel I was subscribed to, to the last. (A.k.a. the first channel I see in my feed is the last video uploaded by the channel I first subscribed to on Newpipe). Wouldn't it be better if the new videos feed just showed the most recently uploaded videos?

**Comment by justanidea** [comment]
Dont worry, we already talked about it and its coming soon

**Comment by thanksgivingmeal** [comment]
Wew you guys are quick.
Btw I love Newpipe its amazing! <3

**Comment by theScrabi** [comment]
@justanidea where have we talked about it?

**Comment by justanidea** [comment]
Is it the same subject as  #822, right?

**Comment by justanidea** [comment]
I talk too fast when i said "we", i wanted to say the "dev", not me. Sorry.

**Comment by wb9688** [comment]
Yes, and it's being implemented in #1044.
