### ISSUE TITLE
[data protection] IP address request to third party service leaks information about users

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/NewPipe#1148]
At the moment, the service https://ipv4.icanhazip.com is used by the crash report activity to (whyever) fetch the public IPv4 of a user, which is then "anonymized" by removing the last two bytes.

Not only this information doesn't really add anything to the crash reports (at least nothing I could think of), it also shares the following details with this service (which, so far, nobody checked, regarding data protection and privacy):
  - complete IP address (and therefore an approximation of their location)
  - user's operating system
  - user is using NewPipe (user agent thing)
  - time of the crash (allows for generating stats like frequency, ...)

In my opinion, this "feature" should be removed entirely from NewPipe, following the data protection principle of "Datensparsamkeit" (a.k.a. "data economy", i.e., reduce the amount of data collected to the absolute minimum).

If there are good reasons to continue to collect this information, however, the implementation needs to be improved to ensure users' privacy (otherwise, one of our USPs, "privacy", doesn't apply):
  - validate service's ToS and ensure they won't collect and/or share the information
  - implement multiple providers (I'd say at least 5) and choose a random one every time (round-robin like)
  - ask user whether they want to share this information, maybe with a checkbox they can uncheck, and request service only when the user confirms they want to send a mail (i.e., don't auto fetch it when the activity is shown)

By the way, according to https://major.io/icanhazip-com-faq/, the software is open source, but the requests are all logged and there is no word about deletion of logs. Also, we don't know anything about where it's hosted and how many "service providers" the provider makes use of have access to the data or network streams.

CC @theScrabi

**Comment by theScrabi** [comment]
I agree. The base idea of the ip address was to check weather certain IP ranges might trigger errors due to regional locks of videos. However this seem to not have helped.

I agree on removing this ASAP.

**Comment by TheAssassin** [comment]
If you don't mind, I'll try to remove those data from Sentry as well. I won't alter the backups, though, but within a couple of weeks those data will be gone as well.

**Comment by ale5000-git** [comment]
What about keep only the first half of IPs?

So for 151.151.151.151 keep only as 151.151.0.0 (doing the change directly inside NewPipe), in this way there is a minimal info for regional locks but the user isn't traced.

**Comment by TheAssassin** [comment]
That is the current state. The IP address information is anonymized on the client before the mail is composed.

However, as we don't have _any_ value in collecting those data, we will get rid of them entirely.

**Comment by theScrabi** [comment]
No it has no value. We need to remove this.
