### ISSUE TITLE
[Feature request] No overlay after double-tap

### ISSUE THREAD

**Issue by Areiser** [TeamNewPipe/NewPipe#1150]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When showing newpipe to my brother, he really liked the app. However, he showed me you can skip small sections of videos by quickly double tapping on the right side of the screen while watching a video on the official app.

In the NewPipe app this works as well, but after doing it the "Menu overlay" is still visible. It would be cool if the overlay disappeared after a double tap, like it does on the official youtube app. That would mean you can skip a small part of the video and continue watching without the overlay getting active.

Is the current behaviour intentional/necessary or is this something that could be changed?

**Comment by mauriciocolli** [comment]
Closing in favor of #1151, as it's more general and the exact (indirect) problem.
