### ISSUE TITLE
Videos are unable to play.

### ISSUE THREAD

**Issue by iiman1c** [TeamNewPipe/NewPipe#11516]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

Every single video i download in 720p(which is what i ALWAYS choose), turn out to be unable to play ,lagging or black screen with only audio played, I can't play any video well untill i redownload the whole video with another quality, which is super annoying to me

-the app is updated to the latest version
-i already tried switching the download files, both internal storage and sd card.
-i read the FAQ and searched about this, but haven't found any solution.
- i already tried using to many video players, but all of them didn't help.

### Expected behavior

Videos being played normally

### Actual behavior

Getting the message "video is unable to play", video is lagging or black screen with only audio playing

### Affected Android/Custom ROM version

Android 9 / XOS v5.5.2

### Affected device model

Infinix X653C

**Comment by spacedrone404** [comment]
+1. I am using tubular, but it is based on the newpipe code. Oppo X6 Pro Android 13.
essential functionality is lost. It is imposible to use atrocious web interface of youtube via browser. Please save us!!

**Comment by kabramahesh19** [comment]
I am able to download but video is not playing please help

https://github.com/user-attachments/assets/d23d9a90-a0f2-4a34-8b34-6e147e6b42ab

**Comment by kabramahesh19** [comment]
No same problem facing for other resolution too
I tried all variation here

**Comment by iiman1c** [comment]
> Isn't YouTube removing 720p? Or did I get it wrong last time somebody mentioned something like that.
> 
> Do other resolutions work fine?

No YouTube is removing HD from 720p, not removing 720p itself , and yea other resolutions work but the resolutions lower than 720p are bad, and the ones higher than 720p take so long to download so 720p is perfect for me

**Comment by kabramahesh19** [comment]
Bro my new pipe app not working video are not playing 😑
