### ISSUE TITLE
Don't show overlay after resuming from buffering

### ISSUE THREAD

**Issue by Knowbody42** [TeamNewPipe/NewPipe#1151]
If I'm watching a video and it needs to buffer, the overlay (play/pause, seek bar) keeps appearing over the top of the video after it resumes.
It's annoying having to press the screen to make it disappear.

**Comment by mauriciocolli** [comment]
This a long time annoyance for me, I just didn't have the time to improve it.

I'll try to in the next few days.

**Comment by karyogamy** [comment]
@mauriciocolli If you wouldn't mind, I'll take care of this issue as part of #1147 since they are closely related.

**Comment by mauriciocolli** [comment]
Ok, it's all yours.
