### ISSUE TITLE
[YouTube] Shorts do not load in their channel tab

### ISSUE THREAD

**Issue by aryaritesh08** [TeamNewPipe/NewPipe#11525]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

Go to the shorts tab in the uploader's channel, the shorts are loading forever.

### Expected behavior

The shorts should load.

### Actual behavior

Shorts not loading

### Affected Android/Custom ROM version

Android 10 Miui 12

### Affected device model

Redmi 9i

### Additional information

Just recently Youtube shorts is not showing in the shorts tab on the uploaders channel. Shorts can still be viewed from the playlist, just not on the uploaders channel.

**Comment by DanielProg39** [comment]
I have this problem for almost a week now

**Comment by aryaritesh08** [comment]
> I have this problem for almost a week now

Happening in other clients too.

**Comment by aryaritesh08** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Santana2217** [comment]
I ensured I have latest update but this is still not working on my Pixel 7a. Tried two channels (screenshot below).
![Screenshot_20241030-222749](https://github.com/user-attachments/assets/eb200e10-3ae2-4d31-969a-3d2b0e76ab57)
![Screenshot_20241030-222737](https://github.com/user-attachments/assets/371d5d43-b46f-462c-8fe5-ea0266a9f869)

**Comment by aryaritesh08** [comment]
Same here

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
