### ISSUE TITLE
[feature request] parse comments from web

### ISSUE THREAD

**Issue by Tapmemer** [TeamNewPipe/NewPipe#1152]
i know comments request has been rejected so much because of no youtube/google api thing but what about parsing the comments from the web version of youtube (so no posting of comments, only viewing)?

if this is possible it would allow people to view comments and newpipe wouldnt use google libs or youtube api.

• [ x] I carefully read the contribution guidelines and agree to them.
• [ x] I checked if the issue/feature exists in the latest version.

**Comment by speednroll** [comment]
those who develop Newpipe have talked about adding this option before

**Comment by theScrabi** [comment]
Yes this is a duplicate.
@Tapmemer scraping it was not a Problem. I'm just not interestrd in doing it. Howevet if someone else was willing to write this feature he is highly wellcome :D

**Comment by KeizerDev** [comment]
If it is a duplicate, please close it. It will keep the issue list more clean
