### ISSUE TITLE
Liberapay for newpipe?

### ISSUE THREAD

**Issue by Bubu** [TeamNewPipe/NewPipe#1153]
I very much like newpipe and I'd like to donate something to you.

As I'm not using bitcoin I wanted to ask if you have considered creating a liberapay team for newpipe?

Fdroid will have full support for it in the next client and website release as well.

**Comment by TobiGr** [comment]
Hey @Bubu,
thanks for your interest in donating to NewPipe! As discussed in #1127 we are going to set up librepay soon and then publish all information you need to the readme, our [website](https://newpipe.schabi.org/donate) and to F-Droid. If you want, you can also donate via [Bountysource](https://www.bountysource.com/teams/newpipe).

**Comment by Bubu** [comment]
Thanks for your reply, looking forward to it!

**Comment by theScrabi** [comment]
Spread the word, we now have librepay:
https://liberapay.com/TeamNewPipe/

**Comment by TobiGr** [comment]
I'll add it to the [donation page](https://newpipe.schabi.org/donate/) soon.

**Comment by theScrabi** [comment]
@TobiGr @wb9688 @coffeemakr @mauriciocolli @karyogamy @TheAssassin please feel free to sign your self up to the team :)

**Comment by theScrabi** [comment]
@Bubu please think twice if you wan't to donate to NewPipe. I've just seen you are part of the fdroid team, and we use a small part of the NewPipe donations to support fdroid. So if you donate back you might push money in a circle.

**Comment by Bubu** [comment]
@theScrabi that would be indeed rather awkward, yes 😅

Well in that case I have just added it to the f-droid metadata:
https://gitlab.com/fdroid/fdroiddata/commit/6264f1c2c235f6fbc4c06014c1753291139be68d

And thanks for your work, this is now one of the most used apps on my Phone ;-)

**Comment by TheAssassin** [comment]
@Bubu may we quote you on that on our homepage, please?

**Comment by Bubu** [comment]
> @Bubu may we quote you on that on our homepage, please?

Sure, why not.

**Comment by B0pol** [comment]
As schabi mentionned, the liberapay is here: https://liberapay.com/TeamNewPipe/
And the donate button in app, in about, is redirecting the website, which show liberapay https://newpipe.schabi.org/donate/

**Comment by hxEmre** [comment]
Merhabalar ben Newpipe yükledim güncelleme gösteriyor ama güncelleme yok güncelleme olmadığı için kullanamıyorum ugulamayı yardımcı olur musunuz?

**Comment by B0pol** [comment]
English?
