### ISSUE TITLE
Unable to play videos

### ISSUE THREAD

**Issue by electric-pants243** [TeamNewPipe/NewPipe#11548]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

Attempt to play a video.
Press on any video shown to me

### Expected behavior

The video to play

### Actual behavior

Screen goes to a grey background with "Content Unavailable"

### Logs

![Screenshot_20240918-210103_NewPipe](https://github.com/user-attachments/assets/73e62f8b-c52d-43a8-87c8-1d4be4d1b79f)

### Affected Android/Custom ROM version

Android 10 Q

### Affected device model

Samsung Galaxy 9

**Comment by electric-pants243** [comment]
Apologies, I would like to close this thread. I was unaware at the time that I was using a VPN

**Comment by vehosah** [comment]
I'm not using a VPN, but I have the problem
