### ISSUE TITLE
Large playlists don't fully load and queue properly when pressing play all

### ISSUE THREAD

**Issue by TheNeto06** [TeamNewPipe/NewPipe#11542]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Make a large youtube playlist. (Large is quite an arbitrary term, but I don't know the lower bound).
2. Open it in the app
3. Press Play All or Background Play

### Expected behavior

All videos in a playlist should load and queue

### Actual behavior

Only a few videos actually appear in queue

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/5505ed81-8fba-4ccb-94cf-e7bb63ead694

it is worth mentioning that swiping down loads the videos, but it is only a workaround and is very annoying to do every time...

### Affected Android/Custom ROM version

Android 10

### Affected device model

LG V40

**Comment by 86ul** [comment]
> #Actual behavior
> Only a few videos actually appear in queue

It happens on my FP3 too, but only the first video is appears, with nothing queued.

**Comment by 86ul** [comment]
> @opusforlife2 
> Would you mind counting the ones that do end up queued? If it's 100, then the same reason as #875 applies.

Hum, I had my notifications set wrongly on my phone and/or github app, this sorry for my late reply. I am not the creator of this issue itself though.

It happened a few this already on my LOS21 with NewPipe 0.27.2. It happened with both self created, and bookmarked playlists. Although NewPipe mentions that the preferred playlist is "hold to queue", sometimes it just fails to add any to all videos to the queue...

**Comment by TheNeto06** [comment]
> Would you mind counting the ones that do end up queued? If it's 100, then the same reason as #875 applies.

sorry for the late reply. i don't usually do this kinda thing and sort of forgot... 😅
yes, it seems to be 100 videos. about [the topic in the other issue](https://github.com/TeamNewPipe/NewPipe/issues/875), i think it would be a nice feature to be able to load a full playlist, even if at the expense of performance.

thanks for the reply! :)

**Comment by P0tluck** [comment]
I am experiencing this issue as well. No bug notification is created and most methods I have been using to navigate at least one playlist doesn't solve the issue. Nor does a application or device restart.

This is my first comment on Github so do let me know if there's any specifics I could provide to further assist with diagnosing or addressing this bug
