### ISSUE TITLE
Background update of youtube subscriptions

### ISSUE THREAD

**Issue by matbrik** [TeamNewPipe/NewPipe#11561]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

let the app update the youtube subscriptions feed in background in order to have an updated list once I open the app

### Why do you want this feature?

Manually updating the feed with a large number of channels (150) takes 10 seconds once you opened the app and tapped on the refresh button

**Comment by Stypox** [comment]
This is already implemented, you can go to Settings->Notifications and enable New Streams Notifications for all channels, and choose a frequency. The channels will be reloaded when the notification appears, but if you don't want notifications you can disable them from Android app settinga.
