### ISSUE TITLE
Decrease battery usage when playing audio

### ISSUE THREAD

**Issue by trudnorx** [TeamNewPipe/NewPipe#11571]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

On Android, I have tested the battery usage when playing an audio source (no video) in three scenarios:

(a) playing with NewPipe, from a network stream: high battery usage
(b) playing with Firefox, from a network stream: medium battery usage
(c) playing with mpv, from a local file: low battery usage

The audio file was the same or extremely similar in each case. These results were highly reproducible and the differences between each case were large.

On this basis, I hypothesize that NewPipe's results would be closer to (b) if it eliminated some inefficiencies, based on the high similarity of the scenarios NewPipe and Firefox were faced with.

I believe, but did not thoroughly check, that both NewPipe and Firefox were downloading small chunks at a time, continuously buffering more chunks throughout the duration of playing.

I also speculate that NewPipe could get closer to (c), perhaps if it buffered in huge chunks (like buffer an hour of content in the first few seconds of playing). This could be a user setting.

### Why do you want this feature?

Self explanatory. The differences in battery usage between the cases are massive. NewPipe makes the battery last many hours less.

**Comment by 86ul** [comment]
Just to think along with: Did you double checked the quality of the streams? As in, a *.mp3 can have a lower quality, thus there is less energy needed to process, than playing a stream with a higher quality. 

In other words, in case all three streams have similar to same quality° and conversion* method, and NewPipe is still using more energy, then your request seem to be valid.

I know your request is about an improvement about the audio, allow me to phrase it with video terms:
° Regarding _quality_ on video, conversions, and alike: although both 1080i and 1080p may seem HD, 1080i is just 720p with more space between the lines (kinda, to phrase it less technical). 
* Regarding _conversions_ on video, there are a lot of ways to compress full HD (1080p) to lower nitrates that streaming services use to lower the data usages, without losing quality, but may impact the need for energy.
