### ISSUE TITLE
Feature Request - HDR video

### ISSUE THREAD

**Issue by Pointeh** [TeamNewPipe/NewPipe#1158]
Hey folks.

Any chance to have 720 HDR and 1080 HDR playback/download choices on supported videos?

I've been using the iYTBP modded YouTube and it works great, don't know why Google haven't updated YouTube proper yet.

**Comment by Pointeh** [comment]
Sorry, found https://github.com/TeamNewPipe/NewPipeExtractor/issues/39 after posting

**Comment by justanidea** [comment]
You can close the issue if you want
