### ISSUE TITLE
Publishing NewPipe to Flathub

### ISSUE THREAD

**Issue by julianwi** [TeamNewPipe/NewPipe#11597]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hi, I'm involved in the android translation layer project (https://gitlab.com/android_translation_layer). We are reimplementing the Android application API on top of GNU/Linux and Freedesktop technology. NewPipe is currently one of the best supported apps (nearly feature complete). We would like to know if you would be fine with publishing NewPipe to Flathub.

### Why do you want this feature?

Our translation layer is very lightweight and can therefore be bundled into a Flatpak. I have created a Flatpak manifest for NewPipe here: https://gitlab.com/julianwi/newpipe_flatpak. It works really great and I think it would make sense to put it on Flathub, so that other people can use it as well.

### Additional information

The size of the Flatpak is about 59MB. The largest parts are libart, libicu, libskia, framework-res.apk and NewPipe.apk, each of them about 10MB plus some smaller libraries. The common libraries can be split out into a Flatpak baseapp to be reused once we support more applications.
The first launch will take a few seconds to do the ahead-of-time compilation. Subsequent launches are nearly instant.
With the help of android translation layer, NewPipe integrates nicely into the Linux Desktop environment. Notifications are published to the XDG-desktop-portal, the playback can be controlled using MPRIS, the Light/Dark theme is automatically selected on startup, and the widget tree can be inspected using GTK-Inspector.

**Comment by theScrabi** [comment]
Can you provide a [Single File Bundle](https://docs.flatpak.org/en/latest/single-file-bundles.html), so we can test it?

IMO You can do this, but you will have to be responsible for maintaining the flatpack package and the desktop experience. I think we are currently exhausted with the things we already have to do.

When you put NP on Flathub please mark it as experimental so if certain things don't yet work people will not come here and complain about things not working on Desktop.

**Comment by julianwi** [comment]
Marking it as experimental is a good idea, as it has not been tested widely.

I created a single file bundle (arch=x86_64) of it here: https://gitlab.com/-/project/58175993/uploads/e45086f66a720cd4d354ed88ab3044ff/NewPipe.flatpak

**Comment by theScrabi** [comment]
OMG this is awesome. Just in case someone is interested how it looks like:

https://github.com/user-attachments/assets/11430372-69e4-485d-a422-1517e9ea3d43

**Comment by julianwi** [comment]
Flathub submission was accepted. I will close this issue

**Comment by Poolitzer** [comment]
Appended in #380, though I will try and add it to the next blog post

**Comment by theScrabi** [comment]
@julianwi how is the Android translation layer holding up with compose. Will NewPipe still be compatible once we do the transition?

**Comment by julianwi** [comment]
@theScrabi, since composeui uses a lot of custom drawing, we need to implement some additional methods in android.graphics.Canvas, so it won't work out of the box, but there is no hard blocker.

**Comment by jhorner6511** [comment]
Honestly, making NewPipe available for Linux Desktop would be a game-changer. I haven't installed it from Flathub yet until it's verified and the kinks have all been worked out. But I'll be keeping an eye on it.

**Comment by theScrabi** [comment]
@jhorner6511 keep in mind [FreeTube](https://freetubeapp.io/) is also an awesome alternative for desktop :)

**Comment by Fuseteam** [comment]
hey @julianwi i would like to test building a different app like you did with newpipe, where would the right avenue be for asking for details on how this works?

**Comment by julianwi** [comment]
Hi @Fuseteam, the Translation Layer is not very feature complete in its current state. Basically we just implemented the APIs used by NewPipe and some other apps we care about. Therefore, any other random app will likely not work out of the box. To bring up a new app, you would need to build https://gitlab.com/android_translation_layer/android_translation_layer from source and implement the missing APIs yourself. Depending on the exact app that could be quite some work.

**Comment by Fuseteam** [comment]
hi @julianwi i understand that, the app i have in mind might be very similar to newpipe. but i don't want to derail this issue further by going into specifics. Is there a group/room where i can asks questions when i get stuck? or would a issue on [gitlab](https://gitlab.com/android_translation_layer/android_translation_layer) suffice?

**Comment by julianwi** [comment]
Hi @Fuseteam, yes, we recently matrix chat room: #android-translation-layer:matrix.org . Opening issues on Gitlab is also fine

**Comment by vitaly-zdanevich** [comment]
@julianwi great, please consider adding to Flatpak this great FOSS podcast app https://antennapod.org
