### ISSUE TITLE
PopUp don't move around with Expanded Desktop from LineageOS enabled

### ISSUE THREAD

**Issue by RodolfoCandido** [TeamNewPipe/NewPipe#1159]
PopUp mode doesn't move arround when Expanded Desktop from LineageOS 13 option its enabled. 
When I try dragging the video, only the overlay controls moves, keeping the video in original place in top-left corner.
If I disable the Expanded Desktop option, everything works normal, but I only use the option enabled (more because my AMOLED screen has now burned Android nav buttons on down corner), so a solution in a future update will be great.

I have a Motorola Moto X 2013 and use the oficial LineageOS 13, and NewPipe 0.11.6 (latest from F-Droid).

**Comment by switchtegrax1** [comment]
Can confirm also happening on lineage 14.1

**Comment by theScrabi** [comment]
This gets more and more a problem. Its not the first time this happens.

@mauriciocolly maybe we have to consider using the new overlay funktion for oreo devices.

**Comment by theScrabi** [comment]
Did it work on older versions of newpipe?

**Comment by RodolfoCandido** [comment]
No. At the least using the 0.9.10 its behave the same way, just overlay buttons moving.

**Comment by theScrabi** [comment]
I see. Well might might need to think about using [this](https://android.gadgethacks.com/how-to/use-new-picture-picture-mode-android-o-0178324/).

**Comment by RodolfoCandido** [comment]
But this would only resolve the problem to Android Oreo. LineageOS 13 is based on Android 6, and the LineageOS 14 on Android 7.

**Comment by theScrabi** [comment]
Thats true as well. Well, if some of the developers of NewPipe has a device that is inflicted to this error, he might take a look at it.

**Comment by mauriciocolli** [comment]
I don't have an Android device atm to test it, but in Android X86 (based on Lineage) it is confirmed:

<img src="https://user-images.githubusercontent.com/13389907/37063218-71a8d4ac-2177-11e8-8ea5-3454247fdb70.png" width="550" />

**Comment by RodolfoCandido** [comment]
I've tested all APK releases from GitHub (from 0.9.4 to 0.12.0-beta, I can't compile the source code from olders) and they all have this problem. I've also recorded how its behaves with Expanded Desktop enabled and disabled.

[https://youtu.be/cYLFJdgkj_g](url)

**Comment by wb9688** [comment]
@mauriciocolli: Nice that we can finally reproduce this issue ourself (before there were only certain users with certain phones with this issue).

**Comment by theScrabi** [comment]
Yes. By the way I have lineage os 12.1, and it turns out when I enable expanded desktop I have the same problem.

**Comment by Stypox** [comment]
Also see #712

**Comment by B0pol** [comment]
It has been dropped in LineageOS 17.1 https://www.lineageos.org/Changelog-24/

**Comment by opusforlife2** [comment]
Close, then.
