### ISSUE TITLE
Legality of Newpipe

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1160]
Imagine a future where Newpipe becomes very important, and a lot of peope use it in the world, enough to make the real youtube App quite lonely. Dont you think google could sue the owners of Newpipe, because they loose money, because of an app which use their own services ? I pretty dont wish that happens, but I was wondering if @theScrabi and all the dev were safe with this app today :)

**Comment by Lionirdeadman** [comment]
It doesn't use any API and so, it's legally the same as using a browser. And modifying a web page is not illegal by any means AFAIK.

**Comment by theScrabi** [comment]
Yes. First of all we are providing a piece of software no service. Therefore everyone that uses NewPipe is responsible for that to him self.

And @Lionirdeadman is basically right with what he says. First of all what is a browser? NewPipe could be.

On the other hand Goole has billions of lawyers, but if we are really big enough so google wants to sue us ... We might have some as well :P
