### ISSUE TITLE
[Feature Request] Download a playlist without having to play it

### ISSUE THREAD

**Issue by john3voltas** [TeamNewPipe/NewPipe#1161]
I've searched but couldn't find an answer. Even asked in the irc channel and @TheAssassin told me this feature doesn't exist.
So I was wondering if it would be viable to implement a download button for playlists.
- One that would be there even before playing the playlist.
- One that would allow us to download the video or just the audio and pick the format (m4a, aac, etc).
Thanks in advance.
Cheers

**Comment by wb9688** [comment]
I agree this would be a nice feature, but it'd be hard to implement,
because some streams in the playlist may have some formats available, while
others may not.

**Comment by TheAssassin** [comment]
@wb9688 one could always just download the best available audio/video format. @john3voltas is more interested in downloading either video or audio streams, the format picking is more of an alternative way how to achieve it, but being able to choose "I want the audio streams" would probably suffice. One could combine it with a "preferred format" dropdown.

**Comment by theScrabi** [comment]
Maybe transcoding was an interesting thing here.

**Comment by MCMic** [comment]
I want this too !

**Comment by john3voltas** [comment]
@theScrabi 
> Maybe transcoding was an interesting thing here.

Hey there. Thank you all for getting in this issue, especially you @theScrabi .
Honestly, most phones/tablets out there don't have the necessary specs to transcode audio, not to mention video.
If you would implement that as a feature I would ask you if you could leave the transcoding as an option and not as a obligation.
I feel more inclined to @TheAssassin 's option:
> ...being able to choose "I want the audio streams" would probably suffice. One could combine it with a "preferred format" dropdown.

This looks more like what I had in mind in the first place.

I have more ideas but they are based on grabbing music albums from YT.
YT has a lot of music albums that can be searched by using your band/musician name and the string 'full album'. This is usually a 1 hour long "video" which usually only has a background still image (CD cover) and the music which ranges from spotify's free quality to very high quality.

There's a desktop PC media player named foobar2000 that has a closed source addon named foo_youtube where you can search YT's database for your music album and pick the one that you're interested in.
It then uses discogs to find that album and it either downloads or generates a cue file.
Here's an app that can do just that [https://sourceforge.net/projects/dcue/](url)
With that cue file, and using media players that support it, you can then display some sort of playlist with the names and tack lengths available on discogs and where in order to skip to a given song you just move the playing position to the minute/second that the cue file says the song selected by the user starts.

I am looking for an app that does this on android (search discogs, download cue and cover cd images and possibly lyrics) to complement NewPipe's ability to download the full audio streams in m4a/aac.
This would be an option when I'm on the car or on a plane with no access to wifi/spotify. I don't have a spotify premium account that would allow me to download in advance.

Anyone here knows an android app that can do this?
@theScrabi would you be interested in this feature for NewPipe? I know it is far from NewPipe's scope, right?
Cheers

**Comment by speednroll** [comment]
I like this idea. but until they develop these features you should find some application to convert these files to mp3 or other format and then use vanilla music with the tag editor plugin to modify the tags of the music you download from newpipe and then use the vanilla cover addon to find the album cover (?

**Comment by theScrabi** [comment]
> @theScrabi would you be interested in this feature for NewPipe? I know it is far from NewPipe's scope, right?

A bit, first of all NewPipe wants to be a replacement for certain video service apps. But the features are the things that make NewPipe cools, so if someone would add and maintain this feature I would totally take it in :)

**Comment by john3voltas** [comment]
> 
> 
> I like this idea. but until they develop these features you should find some application to convert these files to mp3 or other format and then use vanilla music with the tag editor plugin to modify the tags of the music you download from newpipe and then use the vanilla cover addon to find the album cover (?

@speednroll I don't see how I could do that. Do you mean downloading every single audio file from any given youtube playlist? No way. I'm never doing that, it would fry my brain. Music albums usually have between 8 and 12 songs but there are albums with as much as 25 songs. Imagine going over 25 youtube items, asking to download every single file and the go through all the trouble of editing by hand the ID3 tags on every single file using god knows which app with a very small virtual keyboard and then creating an m3u playlist file with all the names and with all the songs in order of appearance.
All that can be scripted into an app using musicbrainz/discogs databases to grab the tags and creating the playlist file. I just happen to be a dumb human being with no programming skills otherwise I'd give it a go myself...

**Comment by Stypox** [comment]
Duplicate of #1058
