### ISSUE TITLE
Put the soundcloud logo as a default bannier in soundcloud's channels

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1165]
I think everything is said in the title :)

**Comment by theScrabi** [comment]
I was more thinking about removing the banner as a default.

**Comment by justanidea** [comment]
Its an other possibility that i like too :)

**Comment by Stypox** [comment]
![Screenshot_20190719-150411](https://user-images.githubusercontent.com/36421898/61537071-83efd680-aa36-11e9-83cc-c7ea2489acc1.png)
Isn't this the expected behaviour? @justanidea

**Comment by justanidea** [comment]
It is. When i posted this it still wasnt the case :)
