### ISSUE TITLE
Flatpak: "Unverified"

### ISSUE THREAD

**Issue by erebion** [TeamNewPipe/NewPipe#11659]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The Flatpak package is currently marked as unverified.

It'd be cool to have it verified.

### Why do you want this feature?

Users will have more trust the package is genuinely NewPipe if it is marked as "Verified".

### Additional information

Verification seems pretty straight forward: https://docs.flathub.org/docs/for-app-authors/verification

**Comment by theScrabi** [comment]
The problem is that the Flatpak version of NewPipe is not officially maintained by us. By verifying it we would take the responsibility for it which we can not since we are not responsible for it.

@AudricV @Stypox am I right?
