### ISSUE TITLE
soundcloud kore not found

### ISSUE THREAD

**Issue by myf** [TeamNewPipe/NewPipe#1166]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

If I try to stream soundcloud on kore the error (kore not found) will popup. When I stream/share youtube link with kore it works perfectly.

**Comment by theScrabi** [comment]
Kore does not support Soundcloud. We need to hide the option there.

**Comment by Stypox** [comment]
Kore now seems to support SoundCloud: https://github.com/xbmc/Kore/blob/master/app/src/main/AndroidManifest.xml
Anyway, it surely does not support neither PeerTube nor MediaCCC

**Comment by Stypox** [comment]
It also does not seem to have problems with `https` anymore
