### ISSUE TITLE
"Network Error" on each and every request

### ISSUE THREAD

**Issue by Arcegis** [TeamNewPipe/NewPipe#1167]
Hello !
I'm using the 0.11.6 version (that I had to manually download, since 0.11.0 seems to be the most recent on F-Droid...and it's not available anymore), with CyanogenOS 12.1 (Android kernel v5.1.1), on a Gigabit Fiber, with a Wifi-N bridge.
Since yesterday night, each and every request that I type gives me a "Network Error". Even the "Trending" page doesn't display anymore and gives me a "Network Error". There is no network problem on my end. Any idea ?

**Comment by theScrabi** [comment]
0.11.0 is not the latest on fdroid. Please try to update the repository manually.

Also please try to use the beta version. And tell us if its existing there as well. However this is odd. Did you modify your phone? Or your network? From where are you connecting?

**Comment by Arcegis** [comment]
Hello !

Apparently, the problem fixed by itself about half an hour after I posted the question. The app is still working now.
(I am connecting from France, and I've set my region to France. I haven't modified my phone, and I just rebooted my network bridge before retrying.)
