### ISSUE TITLE
Feature Request: mark watched videos in playlist/search results/channel

### ISSUE THREAD

**Issue by yasu4** [TeamNewPipe/NewPipe#1168]
- [.] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [.] I checked if the issue/feature exists in the latest version.
e.g. by changing color of title/background

**Comment by theScrabi** [comment]
Well if someone was impelmenting this definetly not a no.

**Comment by speednroll** [comment]
this is a duplicate request

**Comment by theScrabi** [comment]
where is the duplicate?

**Comment by speednroll** [comment]
this is the request #1050

**Comment by theScrabi** [comment]
thank you :)
