### ISSUE TITLE
Option to replace the cowards running this app

### ISSUE THREAD

**Issue by burgrr** [TeamNewPipe/NewPipe#11702]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add an option to disable the backstack and restore sensible back button functionality. 

### Why do you want this feature?

I dont need you babying me by deciding my settings for me. Restore the ability to disable it. 

### Additional information

You people are cowards and disgraces.

**Comment by burgrr** [comment]
'Template ignored'? That's adorable. This is why people use newpipe.

**Comment by theScrabi** [comment]
In my ten years of doing open source work, I never received an issue or comment,  as blunt and disgusting as this.
This is shameful. Dear contributors of this project, you are great and awesome. What you do is a gift to us all, no matter how perfect it is in the end. 🤗
