### ISSUE TITLE
Feature Request: Chronological Order and marking of the videos in the News Section of subscribed channels

### ISSUE THREAD

**Issue by max421** [TeamNewPipe/NewPipe#1172]
Hi,

i have two wishes. 

First can you make the list with the videos in the News Section sorted towards uploading time? At the moment the videos from the channels which I subscribed are totally in a random order. So it's heavy to keep a overview.

Second is it possible to add a option that videos in the News Section can be marked as not new anymore or something like that? Or that videos disappearing after they were displayed a specified duration? 

I think this two improvements would make the user experience more smooth. If the features already in the app I'm sorry but i don't any options regarding to this in the App.

**Comment by justanidea** [comment]
Those two topics already exist :) These features are coming, its not for tomorow of course, but some devs work on it. You can follow their progress on #1044 and #1050

**Comment by mauriciocolli** [comment]
As @justanidea said.

**Comment by max421** [comment]
Thx for the informations:)
