### ISSUE TITLE
Closing app animation glitch

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1173]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Whenever i exit newpipe sometimes the last screen of the app pops in for a split second during the exit animation

**Comment by theScrabi** [comment]
Which android version are you using? Is it stock android or something else?

**Comment by switchtegrax1** [comment]
Lineage os 14.1,newpipe seens to be the only app causing this issue (ive tried changing my system animations but it didn't fix it)

**Comment by switchtegrax1** [comment]
This started happening on version 11.6 while previous versions worked fine.

**Comment by mauriciocolli** [comment]
Can you provide a screen record demonstrating this issue?

**Comment by switchtegrax1** [comment]
[20180309_110656.zip](https://github.com/TeamNewPipe/NewPipe/files/1797125/20180309_110656.zip)
The last seconds of the video you can see the glitch 2 times

**Comment by bboa** [comment]
Hi all, I have the same problem too. How I can help to find problem?
My fw are stock (4.4.2), but have changes (hmm, many changes).

logcat output https://gist.github.com/bboa/7395119c72d9a866ae73563f8bb0e17b
[out.mp4.zip](https://github.com/TeamNewPipe/NewPipe/files/2242908/out.mp4.zip)
[build.prop.zip](https://github.com/TeamNewPipe/NewPipe/files/2242913/build.prop.zip)
[egl.cfg.zip](https://github.com/TeamNewPipe/NewPipe/files/2242927/egl.cfg.zip)

**Comment by theScrabi** [comment]
Thx :) So since this issue I've been patient, so I've seen it on my phone as well. However I'm still trying to figure out what could be the issue.

**Comment by bboa** [comment]
@theScrabi, what you think about this - https://stackoverflow.com/questions/31987029/android-animation-blink-when-repeat/32592871#32592871

**Comment by theScrabi** [comment]
No, but sounds good. :) could someone pls find out how to reproduce this correctly.
