### ISSUE TITLE
[FR] Pause/Play from lock screen?

### ISSUE THREAD

**Issue by jvaehki** [TeamNewPipe/NewPipe#1174]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Hi,

Would it be possible to have NewPipe display on the lock screen like [this](http://cdn.webcazine.com/wp-content/uploads/2015/03/android5_music_controls_on_lock_screen_1_20150408.jpg?x42751). Typically media players do that for example VLC player or Timber. That way you can play/pause without having to unlock the phone. Thanks.

Cheers!

**Comment by theScrabi** [comment]
? Isn't this what NewPipe is doing?
You may want to use the background future.

**Comment by jvaehki** [comment]
I have tried this in two different android devices and none of them had this behavior. Could it be a bug? What more info can I provide to help track this down?

**Comment by justanidea** [comment]
It may be because you have enabled "hide notifications" in your phone setting

**Comment by jvaehki** [comment]
The notification displays normally, just not on the lock screen.

In any case, checked the app notification settings: newpipe is allowed to display notifications and the app notifications are given top priority.

**Comment by jvaehki** [comment]
Fixed! If anyone has the same problem, try this: 

In 'lock screen and security' setting, make sure notifications are 'ON' ('Set display options for notification on the lock screen and always on display')

Thanks a lot to both of you!
