### ISSUE TITLE
Ensure Forced Update(if available)  when NewPipe is not able to function normally for around 15s

### ISSUE THREAD

**Issue by sriramnpkt** [TeamNewPipe/NewPipe#11777]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When New updates are available, the notification tray contains a Notification asking to update. Instead, go for forced update greying out the background and asking users to update before proceeding

1) When the app is outdated for more than few months
2) When the app is not able to stream normally for around 20s

Enforce the update, before allowing access to other features of the app

### Why do you want this feature?

Senior citizens and not-so tech savvy people are not understanding the update available notification

### Additional information

![image](https://github.com/user-attachments/assets/b8c64742-7b57-44e4-8497-6d1e50d13051)
Use similar greying out mechanism and block operations without update

**Comment by hatalmasalma** [comment]
Tons of things can cause a stream to fail!
Even a temporary network issue.
Not only that, but you want to block the whole interface?!?!
Only to force tech-illiterate to push a button?!?!?!

This suggestion is nonsense.
To the degree, I wonder if you are from some marketing department sriramnpkt?

**Comment by AudricV** [comment]
This is not something planned and a very bad idea.

If we release a very bugged update, do you think forcing users to use it when they can rollback to the previous version is a good idea? I do not think so and I think the rest of the team agrees with me.

> Senior citizens and not-so tech savvy people are not understanding the update available notification

However, you're making a point with this, especially for Android TV users: we should have something in the app directly to highlight this and not only rely on a notification.
