### ISSUE TITLE
Custom images or themes (with transparent) over/replacing titlebar colour

### ISSUE THREAD

**Issue by v-cycl3** [TeamNewPipe/NewPipe#1177]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hello I enjoy a lot this app!
My idea is like Google Chrome themes, changing only top bar colour with a custom image.... 
(like transparent fractal of white circles over red)

that may keep Newpipe simple but beautiful for the mood of the user

Thanks.(sorry for my bad english)

**Comment by speednroll** [comment]
I have asked for something similar before. see #1034
