### ISSUE TITLE
do not download the video track while watching

### ISSUE THREAD

**Issue by gipperpank** [TeamNewPipe/NewPipe#11771]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

in the video quality selection field after 144, add OFF so that the video track does not load, how can you add the disable video button in the player itself

### Why do you want this feature?

in places with poor connection quality video from 144p is constantly interrupted video shutdown will be a measure to reduce traffic

**Comment by Stypox** [comment]
Just turn off your screen or move away from the NewPipe app or switch to background mode, and only the audio will play
