### ISSUE TITLE
(idea) A complete offline option in the settings

### ISSUE THREAD

**Issue by jnewz** [TeamNewPipe/NewPipe#1179]
A complete offline option in the settings
In some countries, the price of mobile memory cards is cheaper than for mobile data. Therefore, it would be very good to have an option to save all of the data retrieved on the phone. It saves time, mobile data and money.
It should download the search history the descriptions and thumbnails as well as the video and audio track. That if one searches these again can be called locally. Of course you should be able to turn the feature on and off.

**Comment by gcandrade10** [comment]
First sorry if my grammar is not the best. I use newpipe mostly to listen to music.
I was thinking of implement a repository that stores the files and if you want to watch/listen again don't waste the data but use the local file instead. But I like your approach too!

**Comment by test2a** [comment]
Isnt the download option on all videos in video or audio format already present? Why do you want something new that is already present?

**Comment by gcandrade10** [comment]
You can download the videos or audio, but you need an external app to play those files.
The idea Is to keep the UI as Is and implement a repository which will find the content un the device before reaching internet.
Maybe a Burton to turn the autosave and another to use online offline content. What do you think?
I even would like to implement it myself.

**Comment by Stypox** [comment]
Related: #478

**Comment by alayoubiyoun** [comment]
#478 it wil be a great idea if i can listen to audio with newpipe offline(i love that playback+ignore silence feauture)

**Comment by opusforlife2** [comment]
Slide for Reddit keeps an offline cache of 250 MB for images and 50 MB for GIFs. Maybe Newpipe could do something similar and keep separate cache limits for videos, audios and other stuff like thumbnails, video details, etc.

**Comment by litetex** [comment]
Same reason as in #478 is also in applicable here.
