### ISSUE TITLE
allow subtitles also in Popup mode

### ISSUE THREAD

**Issue by awefartib** [TeamNewPipe/NewPipe#1187]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I just tried the new subtitle feature in the NewPipe beta. From what I can tell, it's only available in the fullscreen player. I was wondering if it's possible to allow subtitles in the floating player as well. This would make the feature a whole lot more useful.

**Comment by karyogamy** [comment]
It does work in popup, but you need to expand the popup window large enough, so the subtitle button has space to show up.

**Comment by theScrabi** [comment]
I think @karyogamy is right, the popup UI already is overcrowded.
