### ISSUE TITLE
don't delete videos from queue if they don't play

### ISSUE THREAD

**Issue by awefartib** [TeamNewPipe/NewPipe#1188]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

NewPipe seems to sometimes produce errors when playing videos, while using a VPN service. This can easily be tested by using it for a couple of days through Orbot. I don't know if the error in itself can be fixed, but I think that NewPipe should NOT automatically delete the videos that produced an error from the playlist. The error is temporary and videos that didn't work sometimes just start to work again. Perhaps mark them in the playlist as having produced an error or simply ignore it and go to the next video?

**Comment by attila-lendvai** [comment]
FTR, i came here just now to report this issue.

**Comment by opusforlife2** [comment]
Fixed.
