### ISSUE TITLE
Image loading cause no more memory issue

### ISSUE THREAD

**Issue by narutosanjiv** [TeamNewPipe/NewPipe#119]
When i goes on scrolling the page, then i get no memory issue. It happening due to bitmap using too much memory.

**Comment by theScrabi** [comment]
I had that once on an early version of 6.0, but nowhere else. Are you working with android 6.0?

**Comment by narutosanjiv** [comment]
No,  i have experienced this issue in kitkat(4.4.4). Why are not we using Android Universal image loader?

**Comment by theScrabi** [comment]
I didn't know it exists. If it helps I think we could consider to use it.

**Comment by 912d** [comment]
I found workaround for this.
I'm using CM11 kitkat and in my case selecting option **allow purgin assets** under *Settings*->*Performance*->*Memory management* helps manage memory.
And in my case NewPipe now isn't crashing.

On earlier version of cyanogenmod, 4.3, I didn't have these kind of problems.
