### ISSUE TITLE
Unable to play downloaded audio files

### ISSUE THREAD

**Issue by codesalad** [TeamNewPipe/NewPipe#1191]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by codesalad** [comment]
I am using the beta version 0.12 and I can only playback the downloaded video files, but it seems like the audio files are corrupt. 

The media players I tries were Google play music, default android one and vlc. I unfortunately don't get useful error messages when trying to play, just that it is similar as when you try to play a faulty file. 

Anything I could check on my phone to fix this? And thanks for all the work, apart from that, it is really neat.

**Comment by justanidea** [comment]
Have you tried Vanilla music?(on fdroid) Because sometimes some apps just cant read m4a

**Comment by codesalad** [comment]
I just did and still nothing. Webm also doesn't work. I will look at the files on my computers when I have time and try to see what's wrong.

**Comment by justanidea** [comment]
What is your phone device? Wait for a real dev for more answers 😉

**Comment by codesalad** [comment]
It's an LG e980, 4.1 – 4.3.1 Android. So it's quite dated, but I haven't met any issues like this before. Thanks.

**Comment by codesalad** [comment]
The files are downloaded correctly. I was able to play the files when opening VLC on my phone and choosing the file from the directories. It does however report "Playback error" when I try to play the audio file with VLC from within NewPipe.

**Comment by wb9688** [comment]
>from within NewPipe

@codesalad: In the download section I assume? If so, the download section is really buggy, and I'm going to replace it soon.

**Comment by codesalad** [comment]
@wb9688 Yes, in the downloads section. Thanks.
