### ISSUE TITLE
NewPipe uploaded with ads to app store 

### ISSUE THREAD

**Issue by beta-phenylethylamine** [TeamNewPipe/NewPipe#1192]
I just found this app and I figured y'all might like to know about it:

https://play.google.com/store/apps/details?id=com.helixapps.steemittube

It calls itself a d.tube player but it's actually just an old version of NewPipe with some colors, text, and images changed, plus ads. 

Technically I guess that wouldn't be a problem on its own, but it doesn't seem to be following the GPL either. I searched far and wide and couldn't find the source, despite it still mentioning that it's under the GPL in the "About" page and i'm sure it's breaking it in about 12 other ways as well

**Comment by theScrabi** [comment]
Hei thank you.
However I will close this, since we have an own thread for copycats:
https://github.com/TeamNewPipe/NewPipe/issues/539
