### ISSUE TITLE
Add Features

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#1194]
Can you please add a Repeat video feature?

**Comment by justanidea** [comment]
There already is :)

**Comment by mauriciocolli** [comment]
Already exist.

**Comment by TobiGr** [comment]
You can already repeat videos, but this feature is hard to find. We'll need to improve the UI/UX for that.
When watching a video, tap on the playlist icon (the three bars prepended each by a dot). Then toggle the repeat mode on the top left.
