### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#1196]
Can you also add a subtitle option and to play the video on the page and not in fullscreen?

**Comment by wb9688** [comment]
Subtitles are already implemented and the second thing is being implemented
by @avently.

**Comment by theScrabi** [comment]
@GKid94 please dont call your isseus just "feature" or "request". Provide a propper title.

**Comment by GKid94** [comment]
@wb9688 How do I enable the subtitles I don't see any option?

**Comment by wb9688** [comment]
It'll be included in the next release.

**Comment by justanidea** [comment]
But you can already have it in the beta version (available on fdroid )
