### ISSUE TITLE
New drawables and icons

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1199]
As @karyogamy pointed out [here](https://github.com/TeamNewPipe/NewPipe/pull/1189#issuecomment-375434974) our current icons/drawables use up lots of memor and are not very scalable since they are bitmaps. On top of that I think they don't look not look very awesome. So as he suggested we should replace them with vector desirables.

**Comment by FaizKhan5** [comment]
Close this.

**Comment by TobiGr** [comment]
I just came across [this article](https://android.jlelse.eu/android-vector-drawables-on-pre-lollipop-crash-solution-45c0c34f0160) on a friend's blog. It could solve our problem.
