### ISSUE TITLE
Share or yt account data to NewPipe storage

### ISSUE THREAD

**Issue by daedrot** [TeamNewPipe/NewPipe#1202]
Hello, thx for your amazing project. I've found it not long ago, and have been using youtube pretty heavily lately. I'd like to ask if there are possible ways to add my youtube channel statistics(subscriptions/playlists/favourites/etc) any other ways than manually? If not is such a feature possible and might be implicated in the future? Thank you for your reply.

**Comment by justanidea** [comment]
Watch #1145, and wait for it :)

**Comment by theScrabi** [comment]
I am so on fire to release the new beta O.o hopefully soon.

**Comment by justanidea** [comment]
0.13.0 released. Now you can import your youtube data !

**Comment by theScrabi** [comment]
yup
