### ISSUE TITLE
Video freeze when switching apps 0.13

### ISSUE THREAD

**Issue by switchtegrax1** [TeamNewPipe/NewPipe#1206]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

 If i switch to another app while watching a video on the latest beta and go back to the video,the video stays frozen and only the audio plays until i exit and start the video again

**Comment by theScrabi** [comment]
can this be confirmed?

**Comment by justanidea** [comment]
I have tried and I havent had any problem. My device is samsung galaxy grand prime.

**Comment by theScrabi** [comment]
@switchtegrax1 could you give us some more information. What phone/os are you using. Can you take a video about what happens?

**Comment by switchtegrax1** [comment]
Lg L70 Lineage 14.1 android 7.1.2,as i described i start watching a video,switch to another app then switch back to the video it stays frozen and only the audio plays
[ScreenRecord-2018-03-24-12-00-35.zip](https://github.com/TeamNewPipe/NewPipe/files/1844498/ScreenRecord-2018-03-24-12-00-35.zip)

**Comment by theScrabi** [comment]
Hm this is strange. I'm not able to reproduce this.

**Comment by switchtegrax1** [comment]
I just found out if i minimize newpipe and change rotation (landscape to portrait) and go back to newpipe the video continues as normal (if i go from landscape to portrait and back to landscape it also works)

**Comment by mauriciocolli** [comment]
> How can I debug this?

You can provide a `logcat` with this debug apk: [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/1887664/app-debug.apk.zip)

**Comment by mission712** [comment]
Here's the log (from main activity start to main activity force stop): [newpipe.txt](https://github.com/TeamNewPipe/NewPipe/files/1894291/newpipe.txt)
I also recorded what happens: https://my.mixtape.moe/vrjhig.mp4

**Comment by karyogamy** [comment]
I suspect the reason for this problem comes from the new way of handling android lifecycle events: instead of destroying the player when the app is paused (switched out), the player is merely paused and only destroyed when the system deems necessary. I've updated #1226 to rollback this change while keeping the existing functionalities, so please take a look and see if this fixes the problem, since I can't reproduce the issue on my own devices: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/1901224/app-debug.zip).

**Comment by switchtegrax1** [comment]
It says package is corrupt

**Comment by switchtegrax1** [comment]
All working now

**Comment by mission712** [comment]
Package was also broken there, @switchtegrax1's package works, and the fix works here as well. I'm suspecting this has something to do with old video decoders on these devices (my device is from 2012!).

**Comment by switchtegrax1** [comment]
Well my device is from 2014 2 years newer than the s3,so it can't be a codec bug so i suspect it could actually be a bug in lineage os because as i reported if i minimize the video,rotate the screen and go back to the video it resumed normally,it really seens like lineage does not like keeping the player alive which is why i assume it gets destroyed and recreated when i rotate

**Comment by switchtegrax1** [comment]
Mine is from 2014,i think it could also be an issue with lineage os as i've reported here another bug which nonone seemed to be able to replicate,an exit animation glitch. #1173

**Comment by switchtegrax1** [comment]
Its fully fixed on the latest release,ill be closing this issue
