### ISSUE TITLE
Notification bar priority fight with Google Maps

### ISSUE THREAD

**Issue by 5nefarious** [TeamNewPipe/NewPipe#1207]
When New pipe is playing in the background and navigation is running at the same time, the two apps fight for priority in the notification bar. This results in both applications endlessly swapping back and forth in the UI, making it hard to tap on either of them.

I do not know if this is only an issue with Google Maps, but this is the only app I have observed this behavior with.

**Comment by theScrabi** [comment]
Can you send a video of this happening?

**Comment by DidiBear** [comment]
I faced the same issue. Google Maps is also the only app that do this.

Here is a video of the problem : https://www.youtube.com/watch?v=9gIg82rkJuQ

**Comment by theScrabi** [comment]
Yea nasty. I have to check this.

However It brings a little movement into the screen :dancer:

**Comment by marco-locatelli** [comment]
I have the exact problem with my s9+, Android 9 with November patch. 
Newpipe version 0.17.4
Google Maps 10.31.0

Small video/gif demonstrating the error: https://gfycat.com/uglyspiritedichneumonfly

**Comment by qandrav** [comment]
I have the exact problem with my s9+, Android 9 with November patch.
Newpipe version 0.17.4
Google Maps 10.31.0

Small video/gif demonstrating the error: https://gfycat.com/uglyspiritedichneumonfly
