### ISSUE TITLE
Wrong version shown in crash log

### ISSUE THREAD

**Issue by budsterblue** [TeamNewPipe/NewPipe#1208]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

In the 0.13.0 beta, the version shown in the crash log says 0.12.0 instead of 0.13.0

Also, I have a crash, but the "Report Error Via E-Mail" button seems to be grayed out (app in crash loop when setting "Content of main page" to "Subscription Page")

**Comment by theScrabi** [comment]
HOLLY F*** I forgot to increse the version number.

God thing its not yet on fdroid.
