### ISSUE TITLE
v0.13 crash when Subscription Page is the main page

### ISSUE THREAD

**Issue by TemporaryAccount0x1** [TeamNewPipe/NewPipe#1211]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

This crash happens as soon as I start newpipe beta v0.13:
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe.beta",
   "version": "0.13.0",
   "os": "Linux Android 7.1.2 - 25",
   "time": "2018-03-25 13:37",
   "exceptions": [
      "java.lang.IllegalStateException: Fragment SubscriptionFragment{bcef37b id=0x7f090162 android:switcher:2131296610:0} not attached to a context.\n\tat android.support.v4.app.Fragment.requireContext(Fragment.java:611)\n\tat android.support.v4.app.Fragment.getResources(Fragment.java:675)\n\tat android.support.v4.app.Fragment.getString(Fragment.java:697)\n\tat org.schabi.newpipe.fragments.subscription.SubscriptionFragment.setUserVisibleHint(SubscriptionFragment.java:108)\n\tat android.support.v4.app.FragmentPagerAdapter.setPrimaryItem(FragmentPagerAdapter.java:136)\n\tat android.support.v4.view.ViewPager.populate(ViewPager.java:1228)\n\tat android.support.v4.view.ViewPager.populate(ViewPager.java:1086)\n\tat android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)\n\tat android.view.View.measure(View.java:19861)\n\tat android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)\n\tat android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)\n\tat android.view.View.measure(View.java:19861)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:185)\n\tat android.view.View.measure(View.java:19861)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:185)\n\tat android.view.View.measure(View.java:19861)\n\tat android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1059)\n\tat android.view.View.measure(View.java:19861)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:185)\n\tat android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)\n\tat android.view.View.measure(View.java:19861)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)\n\tat android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)\n\tat android.widget.LinearLayout.measureVertical(LinearLayout.java:758)\n\tat android.widget.LinearLayout.onMeasure(LinearLayout.java:640)\n\tat android.view.View.measure(View.java:19861)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:185)\n\tat android.view.View.measure(View.java:19861)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)\n\tat android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)\n\tat android.widget.LinearLayout.measureVertical(LinearLayout.java:758)\n\tat android.widget.LinearLayout.onMeasure(LinearLayout.java:640)\n\tat android.view.View.measure(View.java:19861)\n\tat android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)\n\tat android.widget.FrameLayout.onMeasure(FrameLayout.java:185)\n\tat com.android.internal.policy.DecorView.onMeasure(DecorView.java:693)\n\tat android.view.View.measure(View.java:19861)\n\tat android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)\n\tat android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:699)\n\tat android.view.Choreographer.doFrame(Choreographer.java:634)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)\n\tat android.os.Handler.handleCallback(Handler.java:751)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:153)\n\tat android.app.ActivityThread.main(ActivityThread.java:6244)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)\n"
   ],
   "user_comment": ""
}

this didn't happen in beta v0.12

**Comment by TemporaryAccount0x1** [comment]
additional logcat info:

---- 25 Mar 2018 15:58:51 ----

03-25 15:58:21.467  1096  1229 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.schabi.newpipe.beta/org.schabi.newpipe.MainActivity (has extras)} from uid 10035 on display 0

03-25 15:58:21.511  1096  2256 I ActivityManager: Start proc 11025:org.schabi.newpipe.beta/u0a133 for activity org.schabi.newpipe.beta/org.schabi.newpipe.MainActivity

03-25 15:58:21.565 11025 11025 W System  : ClassLoader referenced unknown path: /data/app/org.schabi.newpipe.beta-1/lib/arm

03-25 15:58:21.623 11025 11025 I ACRA    : ACRA is enabled for org.schabi.newpipe.beta, initializing...

03-25 15:58:21.937 11025 11025 E ACRA    : ACRA caught a IllegalStateException for org.schabi.newpipe.beta

03-25 15:58:22.129  1096  3261 I ActivityManager: Start proc 11060:org.schabi.newpipe.beta:acra/u0a133 for service org.schabi.newpipe.beta/org.acra.sender.SenderService

03-25 15:58:22.149 11060 11060 W System  : ClassLoader referenced unknown path: /data/app/org.schabi.newpipe.beta-1/lib/arm

03-25 15:58:22.153  1096  2036 W InputDispatcher: channel 'cdf0bb7 org.schabi.newpipe.beta/org.schabi.newpipe.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

03-25 15:58:22.153  1096  2036 E InputDispatcher: channel 'cdf0bb7 org.schabi.newpipe.beta/org.schabi.newpipe.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

03-25 15:58:22.153  1096  3765 I WindowManager: WIN DEATH: Window{cdf0bb7 u0 org.schabi.newpipe.beta/org.schabi.newpipe.MainActivity}

03-25 15:58:22.154  1096  3765 W InputDispatcher: Attempted to unregister already unregistered input channel 'cdf0bb7 org.schabi.newpipe.beta/org.schabi.newpipe.MainActivity (server)'

03-25 15:58:22.154  1096  8007 I ActivityManager: Process org.schabi.newpipe.beta (pid 11025) has died

03-25 15:58:22.347 11060 11081 I ACRA    : Sending report /data/user/0/org.schabi.newpipe.beta/app_ACRA-approved/2018-03-25T15:58:21.986+02:00-IS_SILENT.stacktrace

03-25 15:58:22.358  1096  3764 I ActivityManager: START u0 {flg=0x10000000 cmp=org.schabi.newpipe.beta/org.schabi.newpipe.report.ErrorActivity (has extras)} from uid 10133 on display 0

03-25 15:58:22.418  1096  1230 I ActivityManager: Start proc 11082:org.schabi.newpipe.beta/u0a133 for activity org.schabi.newpipe.beta/org.schabi.newpipe.report.ErrorActivity

03-25 15:58:22.457 11082 11082 W System  : ClassLoader referenced unknown path: /data/app/org.schabi.newpipe.beta-1/lib/arm

03-25 15:58:22.496 11082 11082 I ACRA    : ACRA is enabled for org.schabi.newpipe.beta, initializing...

03-25 15:58:22.904  1096  1423 I ActivityManager: Displayed org.schabi.newpipe.beta/org.schabi.newpipe.report.ErrorActivity: +535ms (total +1s417ms)

---- 25 Mar 2018 15:58:51 ----

**Comment by TemporaryAccount0x1** [comment]
I fixed it, I forgot to uninstall the old version before installing the new version.

**Comment by TemporaryAccount0x1** [comment]
I spoke too soon. 

This still happens. The cause seems to be having the subscription page as main page since that was my main page in beta v0.12 it happened at start up. Uninstalling and reinstalling will reset the main page to the trending page.

To reproduce:

go to content -> Content of main page and change it to Subscription Page -> crash

**Comment by karyogamy** [comment]
Confirmed. Locked myself out of the app. Fixed in #1212.
