### ISSUE TITLE
★★ Bug Purging Time ★★

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1213]
[![giphy-downsized](https://user-images.githubusercontent.com/1891273/37878741-d06b9bd2-306d-11e8-9ccd-833f67008a80.gif)](https://github.com/TeamNewPipe/NewPipe/projects/3)

Now where v0.13.0 beta is out we could try to squees a few bugs again.

## [Here is a list](https://github.com/TeamNewPipe/NewPipe/projects/3)

It was good if we ceept it low with features for version, so v0.13.1 can be a release again, and a release is overtime.

**Comment by theScrabi** [comment]
No

**Comment by theScrabi** [comment]
Have you used NewPipe lately?

**Comment by FaizKhan5** [comment]
Yeah

**Comment by theScrabi** [comment]
Moreover this should be bumped more.
