### ISSUE TITLE
0.13.0 beta - Polish and English are both displayed at the same time

### ISSUE THREAD

**Issue by slyscorpion** [TeamNewPipe/NewPipe#1215]
Hi, 

I checked the issue tracker but I couldn't find if my issue exists or my github-fu skills are lacking.

In the 0.13.0 beta for NewPipe there are some Polish words mixed in with English when I open up NewPipe.

https://i.imgur.com/DuhQwM1.jpg

If you look at the attached screenshot, you will see the words "2 dni temu" (2 days ago) mixed in with everything else.

My phone's language is set to English (United States) and my input languages are set English (United States) and Polish. My region in my Android settings is set to Poland. The content country in my install of NewPipe is set to United Kingdom. Figured I should mention that in case any of what I just mentioned has a bearing on this issue.

Let me know if you need any further info.

**Comment by theScrabi** [comment]
2 dni temu is generated localy on your phone, while the rest  of the item is downloaded. If the content country and your language are different this will mix.

**Comment by slyscorpion** [comment]
I just changed my content country to USA in NewPipe to match my language which is English (United States) and I still get the "2 dni temu" text.

**Comment by theScrabi** [comment]
Ah ... well al right are you in Poland right now?

I might have told you wrong, the date is not yet parsed and locally generated as I said.
In fact the date is generated by Youtube, and it depends on your content language. However NewPipe does respect your content countery, which means its which video your content language, which means in which language Youtube presents meta information. 

We discuses this before. Actually NewPipe should respect both.

Bug confirmed.

**Comment by slyscorpion** [comment]
Hi @theScrabi yes I am located in Poland.

**Comment by Stypox** [comment]
Related: #578 #1130 #1132
