### ISSUE TITLE
Toast background

### ISSUE THREAD

**Issue by pr0gr8mm3r** [TeamNewPipe/NewPipe#1218]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

# Steps to reproduce:
1. Set Theme to light
2. Go to Settings > Content
3. Click on "Import database" or "export database"
4. Deny access to storage
5. Toast saying "Permission to access filesystem denied" appears with white background

**Comment by pr0gr8mm3r** [comment]
Version 0.12.0
I forgot to check checkboxes

**Comment by theScrabi** [comment]
Normally we can not alter the style of a toasy. Can you send a screenshot?

**Comment by pr0gr8mm3r** [comment]
![screenshot_2018-03-27-12-06-05 1](https://user-images.githubusercontent.com/37022952/37961166-d9b848ac-31b7-11e8-94b3-6ac3f739bccf.png)

**Comment by theScrabi** [comment]
How does it look when its black layout?

**Comment by pr0gr8mm3r** [comment]
Just like it should:
![screenshot_2018-03-27-19-37-26 1](https://user-images.githubusercontent.com/37022952/37984422-85048fb6-31f6-11e8-9ea2-80d208f811d1.png)

**Comment by pr0gr8mm3r** [comment]
The error doesn't occur in 0.13.0 (tested on all themes). Close it?

**Comment by theScrabi** [comment]
Still this looks strange tho.
