### ISSUE TITLE
Popup window is detached from the "control frame" and stays in the top left corner

### ISSUE THREAD

**Issue by pExeen** [TeamNewPipe/NewPipe#1219]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hello, first of all I want to thank all the contributors for developping the app.
So as I described it in the title the video and the controls are detached and I the video stays in the top left corner.
[Here is a screenshot of it.](https://i.imgur.com/rPtDxaj.jpg)
I am running Lineage 14 (Android 7.1.2) with the latest NewPipe version.
I get the same issue with the latest beta release on github.
Thanks.

**Comment by theScrabi** [comment]
We are aware of that bug :D but thank you.

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1159
