### ISSUE TITLE
"New" button list sorted by date

### ISSUE THREAD

**Issue by ABOATDev** [TeamNewPipe/NewPipe#1220]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Hello to the developer! 
http://prntscr.com/ix7jup
You want to file the videos on the release date? 

Version : 0.11.6
Langage : French
Thank you

**Comment by theScrabi** [comment]
Yes the feedpage needs to be reworked hardly. The one we have right now is just sort of some prototype.

**Comment by freddii** [comment]
I would like to see that too.

**Comment by Lonami** [comment]
Duplicate of #739, I think this one can be closed.
