### ISSUE TITLE
[bug] the covers of the videos aren't seen in the background player

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1221]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I publish this here since I have not found the original problem where it was requested before (because I'm sure it was previously requested).
I don't see the covers of the videos in the background player in Android Oreo, I guess it will not be very complex to solve this:
<img src="https://framapic.org/rSHAObanBs2q/aTejIsnD4lQL.png" width="300">

p.s: forget to mention that I am currently using the beta version of newpipe found in F-Droid (0.12.0)

**Comment by Duppadaadadii** [comment]
Why are people sending bug reports for older versions?

I can see the cover on 0.13.0 beta.
So at least i don't have this problem.

**Comment by wb9688** [comment]
I don't have this problem in the latest release nor in the current
development branch, but I'm using Android 7.0. Is there any version where
it was working on?

**Comment by theScrabi** [comment]
I've added a not to the contribution page that one hase to check if an issue exists in the latest version before posting a report.

@speednroll please check if the bug exists in v0.13.0-beta

**Comment by speednroll** [comment]
before I used Android Stock Nougat and these problems didn't happen, but remember that Android Oreo is different in several things (I don't know how the next Android P will be). I just tried the 0.13.0 and the problem persists (remember that the problem only happens in Oreo)

**Comment by speednroll** [comment]
@Duppadaadadii you speak for speaking :laughing:

**Comment by theScrabi** [comment]
Anyway, I'll need to check this.

**Comment by speednroll** [comment]
This problem still exists. It was not reviewed.

**Comment by opusforlife2** [comment]
Close. Account is gone.

**Comment by wb9688** [comment]
@opusforlife2: Account being gone isn't a valid close reason. However I'll close this anyway, as it should just work, especially with the new MediaStyle notifications.

**Comment by opusforlife2** [comment]
I'm saying this for those where we need more info from the issue creator, but that isn't possible anymore. If there are multiple people reporting that issue in that thread, then of course there is no reason to close.

**Comment by wb9688** [comment]
@opusforlife2: Why did you ask to close on e.g. #1453 then? That feature request is clear.

**Comment by opusforlife2** [comment]
Only issue poster was asking for something. It wasn't clear what. Stypox asked for clarification. No reply is possible now.
