### ISSUE TITLE
Left menu select SoundCloud item, Trending or youtube content, SoundCloud content not displayed

### ISSUE THREAD

**Issue by LIYANJU2015** [TeamNewPipe/NewPipe#1222]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

Left menu select SoundCloud item, Trending or youtube content, SoundCloud content not displayed

**Comment by JuniorJPDJ** [comment]
You forgot to tick boxes xD
But +1, should be fixed

**Comment by wb9688** [comment]
This was more or less intentionally done. We know that UI isn't really
intuitive, so we're going to improve it soon.

**Comment by Stypox** [comment]
This issue is (I think) the same as #1013
Reopen if it is not :-)
