### ISSUE TITLE
"implement me" bug

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1228]
If you enable a soundcloud kiosk as frontpage, and go back to the frontpage you will get an error:

![screenshot_20180330-201843](https://user-images.githubusercontent.com/1891273/38152405-f73020d2-3467-11e8-9342-152fd232985d.png)

The snagbar for this error always shows up, however its particular nasty because you cant access the settings in the drawer enymore in order to turn off the kiosk.

However if you want to read the error the message is "implement me"

... this however is my fault, I've deaktivated kisok for soundcloud once.

**Comment by karyogamy** [comment]
I can't seem to reproduce the error, but for the snackbar, maybe it's a good idea to add a dismiss button to it.

**Comment by theScrabi** [comment]
> maybe it's a good idea to add a dismiss button to it.

that would not help since the error is instantly risen again. I/we just had to fix the error I produced by writing that "implement me" thing.

> can't seem to reproduce the error

On the current version you can still access the settings via dropdown menu, however I'm working on a branch where I remove beta builds, and therefore also the redundant items in the dropdown menu. Then this issue will be a problem for us.

**Comment by karyogamy** [comment]
Oh, I was on the `removebeta` branch and can't reproduce any error on returning to main fragment after changing the page to soundcloud kiosk.

> that would not help since the error is instantly risen again.

Something might be wrong internally, then, since something has to constantly spewing out errors to make the snackbar reappear instantly.

**Comment by theScrabi** [comment]
> Something might be wrong internally, then, since something has to constantly spewing out errors to make the snackbar reappear instantly.

I see ...

**Comment by Stypox** [comment]
SoundCloud Kiosk pages now can't be added from the "Content of main page" option, so this is not an issue anymore.
