### ISSUE TITLE
[Feature request] Improve Player Design & consistency

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1234]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I find it anoying when i playing a video and when i want to change the quality i press on the resolution (360p,480 etc..) and them it shows the codec right at the side of the resolution,honestly this should only be kept to the quality selector before you watch the video and not the one inside exoplayer as it looks ugly and senseless as the user already knows the format its playing from the quality selector and doesnt need to be reminded inside the exoplayer
![screenshot_20180331-215957](https://user-images.githubusercontent.com/32078304/38168837-0b9c35a2-352f-11e8-869b-97f26b536e30.png)

**Comment by theScrabi** [comment]
> as the user already knows the format its playing from the quality selector

arguable. I use this function quite often.

**Comment by switchtegrax1** [comment]
Before you play the video you already see what format the video is in the top so there's very little to keep that inside the player as it looks asthetically unplessing and unintuitive as the user will select a quality (480p) and then BAM a large menu opens up showing both format and quality so i propose this either remove the mpeg and webm text from the exoplayer or show that text all the time to keep ui consistency

**Comment by switchtegrax1** [comment]
Before you play the video you already see what format the video is on the top so there's very little to keep that inside the player as it looks asthetically unplessing and unintuitive as the user will select a quality (480p) and then BAM a large menu opens up showing both format and quality so i propose this either remove the mpeg and webm text from the exoplayer or show that text all the time to keep ui consistency

**Comment by Stypox** [comment]
I often use that option, so it should not be removed, but I agree the "MPEG-4" piece should not be shown since most people don't even know what it is.

**Comment by litetex** [comment]
This is fixed now when nothing is chosen:
![grafik](https://user-images.githubusercontent.com/40789489/132917008-845f9d17-3bc1-40ca-9d94-fd97c32d7412.png)
![grafik](https://user-images.githubusercontent.com/40789489/132917038-8cc96e8e-1d7f-420e-a0fb-ca834f430fdb.png)

The shown quality label (while choosing) is quite useful for various reasons, e.g. when debugging.

Closing this issue for now due to inactivity.
