### ISSUE TITLE
Video doesn't resume.

### ISSUE THREAD

**Issue by mathwhiz1212** [TeamNewPipe/NewPipe#124]
If I open a video and go to another app it starts the video over without resuming.

**Comment by theScrabi** [comment]
Yes we left that out because with the current player we use, we have buffer problems.

**Comment by mathwhiz1212** [comment]
Ok. I don't know if this info will help or not but, this is also a problem if I use VLC as an external player.

**Comment by theScrabi** [comment]
That issue than belongs to VLC xD. Try some other StreamPlayer like MXPlayer, and se what they do.

**Comment by mathwhiz1212** [comment]
Newpipe's video player and VLC don't resume. The default video player that comes with my LG power resumes after a delay. (3-4 seconds.)

**Comment by theScrabi** [comment]
Hm we are aiming to use [ExoPlayer](https://github.com/google/ExoPlayer) in the future. So maybe this will solve our problems.

**Comment by mathwhiz1212** [comment]
Ok. Please keep me up to date on it. Thanks!

**Comment by locutis-of-borg-1999** [comment]
If you stay subscribed to this thread, you'll be kept in the loop.  

I stopped using VLC, due to some issue, which I didn't document/note.  The internal player does the job.  

I just hope this ExoPlayer will be more FOSS than Google pretends to be, and will be available on repo's like F-Droid.

Of course a dev's got to eat, and buy gear.  So hopefully those "donate" links do the job.

**Comment by theScrabi** [comment]
Well exoplayer is apache software, therefore it is FLOSS. You can find it here [exoplayer](https://github.com/google/ExoPlayer). Also exoplayer is not an external player. It's more a framework based on android's build in MediaPlayer, just with much more customization abilities. So for example you can set the buffersize, the way of encoding, and you can set a network proxy.

**Comment by locutis-of-borg-1999** [comment]
Oh!  Thanks for explaining!  B-)  8-)

**Comment by m1cha1** [comment]
I have the same problem with version 0.77. But when you switch on exoplyaer in settings and you switch to another app music is playing in the background. When you back to Newpie you will have black screen. For me it's a feature because backroung player doesn't work (hangs).
Moto G 2014 Android 6.0

**Comment by leafcutterant** [comment]
Why was this closed? This is still an issue and happens to me every time.

Or am I supposed to install Exoplayer and then NewPipe will resume to the same timestamp when it regains focus?
