### ISSUE TITLE
[FR] set name of artists in downloaded songs

### ISSUE THREAD

**Issue by ahmedzs** [TeamNewPipe/NewPipe#1241]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

naming artist field of downloaded songs to the name of channel, set album to 'name of channel - playlist name'

**Comment by Stypox** [comment]
Duplicate of #183
