### ISSUE TITLE
Unsubscribing a deleted channel

### ISSUE THREAD

**Issue by JakobWerner** [TeamNewPipe/NewPipe#1245]
As far as I know the only possibility to unsubscribe a channel is to navigate to the channel and uncheck the subscribe button. However I subscribed to a YouTube channel which is now deleted. Hence I cannot load the channel. It only gives a rather obscure error message and therefore I cannot delete the channel from my subscription list.

**Comment by TobiGr** [comment]
hey @JakobWerner,
someone had this problem before and opened #940.
