### ISSUE TITLE
Can't download to SD card

### ISSUE THREAD

**Issue by placidcasual98** [TeamNewPipe/NewPipe#1246]
I have been trying to download to my SD card but the app does not allow me to.

**Comment by placidcasual98** [comment]
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.13.1",
   "os": "Linux Android 7.1.2 - 25",
   "time": "2018-04-02 21:12",
   "exceptions": [
      "java.lang.RuntimeException: java.io.IOException: Permission denied\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:350)\nCaused by: java.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\njava.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
Sd card download does not yet function, but we are aware of that.
