### ISSUE TITLE
[feature request] able to download to SD card

### ISSUE THREAD

**Issue by placidcasual98** [TeamNewPipe/NewPipe#1248]
[feature request]I have been trying to download to my SD card but the app does not allow me to.
This is a major flaw .
Before closing this request please link to the already open one if you think this is duplicate.

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/315

**Comment by placidcasual98** [comment]
Lol that is not a feature request thread is is a fault
