### ISSUE TITLE
[feature/enhancement] add playlists to subscription feed

### ISSUE THREAD

**Issue by alexandroidii** [TeamNewPipe/NewPipe#1253]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.

Hey guys and girls and thank you for this awesome app!  I just discovered it to only load subscribed channels so my son can watch videos from those channels without being flooded with horrible recommended videos.  

I'm requesting there be the option to add playlists to the channel page so we can add a playlist that we can add videos to that will appear in my son's newpipe app.

Thank you!

Alex

**Comment by Stypox** [comment]
Closing in favour of #2414
