### ISSUE TITLE
Video popup on lock screen

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1254]
Is it technically possible to make appear a video popup on the lock screen, as a notification for instance? So you can watch it without doing your code, and if you switch off the screen it continues in background.

**Comment by switchtegrax1** [comment]
Why would someone do that,the screen would still turn off,so its kinda pointless

**Comment by switchtegrax1** [comment]
No,you can't overlay the lockscreen (with a popup atleast) neither can you run a video as notification,plus the lockscreen would still forcibly turn the screen off

**Comment by theScrabi** [comment]
Yes, you can make activity's appear on top of the lock screen. Isn't even complicated. What would be the use case for it?

**Comment by justanidea** [comment]
You'll laught... I just would be very stylish and satisfacting too see that (you now, when you hear a music, and you want to see the clip, but not sure... x'D)
Maybe its not very important, but it's like woaw, this app is really better than youtube! 
:)

**Comment by theScrabi** [comment]
I see :D, yea its stylish.

However I'm most of the time a little preservative when it comes in terms of exotic features. However we can take a look at it if more people want it.

**Comment by speednroll** [comment]
In my opinion, I will not find functionality, especially because I unlock my phone with fingerprint

**Comment by Stypox** [comment]
I agree this would not be that useful

**Comment by justanidea** [comment]
I guess that you are right. Focusing on the main issues and functionalities is a much better deal IMO
Should i close this?

**Comment by Stypox** [comment]
If you are ok with closing, go for it :-)
