### ISSUE TITLE
[Feature request]Setting to limit mobile data usage

### ISSUE THREAD

**Issue by Zenopheus** [TeamNewPipe/NewPipe#1259]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When I use NewPipe outside of my home I always switch to 144p to avoid eating up my data plan. This is annoying and I often forget. Could you add an option to limit bandwidth usage when off of wifi?
Instead of adding four additional non-wifi “Default XXXX” options you could add just one:

Settings option:
**Limit mobile data usage**

Choices:

| Label | Action |
| --- | --- |
| No change | Stick with user chosen defaults |
| Play video and audio at a reduced quality | Reduce resolution and format for the lowest bandwidth consumption |
| Play only audio at a reduced quality | Show video thumbnail and reduce audio rate |

What it might look like:
![newpipe-mobilelimit](https://user-images.githubusercontent.com/4527783/38314145-986d8456-37f3-11e8-9906-25fdd21f32bc.jpg)

**Comment by theScrabi** [comment]
Sounds cool. Now someone had to implement this :D

**Comment by Zenopheus** [comment]
I'll see if I can get the time to add it.

**Comment by Zenopheus** [comment]
Ooops, I closed this by accident. Sorry... Looking into it shorty once I set up my dev environment.
