### ISSUE TITLE
WebM videos fallback to 3GPP instead of MPEG-4

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#1261]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Many obscure videos don't have WebM versions, so when watching these obscure videos in low qualities such as 144p and 240p, the quality is significantly reduced (3GPP is much worse than MPEG-4, and MPEG-4 is worse than WebM). It would help if the fallback became MPEG-4, even at lower resolutions.

**Comment by chpio** [comment]
This is somewhat related, not sure if it is exactly the same problem described in OP. My settings are set to use the webm (vp9) format. But a lot of videos (with less then a few ten thousand views) don't have a vp9 variant. So they fail to play. But there's only an option for "MPEG-4 360p" (even if there's is are higher-res avc1 variants of the video on the YT website) in the resolution/format selector. It would be nice to have either more options to select a higher resolution or better to automagically fallback to "MPEG-4" with a higher-res.

**Comment by opusforlife2** [comment]
Close as invalid.

@chpio Your problem is probably #2415.
