### ISSUE TITLE
[Feature Request] Show Download Progress on The Notification

### ISSUE THREAD

**Issue by switchtegrax1** [TeamNewPipe/NewPipe#1264]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Also If there's more than one video downloading show an estimate percentage of both together

**Comment by theScrabi** [comment]
closing in favour of https://github.com/TeamNewPipe/NewPipe/issues/962
