### ISSUE TITLE
Surveys for contributors

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1267]
Is there a way to make surveys here, or something which permit the community to vote and choose what feature request is the most important, or the most liked, so it make easier for devs to now what to do first (?)

**Comment by wb9688** [comment]
On GitHub, you could add reactions (like thumbs up) to issues.

**Comment by justanidea** [comment]
Yes, but it is quite limited :)

**Comment by TobiGr** [comment]
You can sort issues by reactions. So I guess there is no need for a different solution.

**Comment by TobiGr** [comment]
Maybe we can open an issue to tell the people to vote via 👍
