### ISSUE TITLE
Remember last settings on download popup 

### ISSUE THREAD

**Issue by gdevenyi** [TeamNewPipe/NewPipe#1272]
Right now the download widget resets to  defaults with each use. I think from a usability standpoint it makes sense to remember the last used settings.

**Comment by rakeshdas1** [comment]
+1, would be very useful to download things in sequence

**Comment by gdevenyi** [comment]
Still a +1 for this, it goes really nicely with the default open Download dialog that was added.

**Comment by TobiGr** [comment]
implemented in #1759
