### ISSUE TITLE
Typo in German localisation

### ISSUE THREAD

**Issue by ksaerdna** [TeamNewPipe/NewPipe#1274]
The text
`Neue Playlist Erstellen`
should be
`Neue Wiedergabeliste erstellen`
or, if you prefer Denglish,
`Neue Playlist erstellen`
, but in any case „erstellen” must not be written in upper case here, although it's common fashion to do so nowadays.

**Comment by mauriciocolli** [comment]
You can fix this in [weblate](https://hosted.weblate.org/projects/newpipe/strings/de/), our translation service.

**Comment by ksaerdna** [comment]
Thanks, I tried, but I cannot repair the typos, I can just suggest the correct translations. BTW: There are indeed more examples of wrong upper case infinitives in the localisation, as expected.

**Comment by TobiGr** [comment]
You can login into Weblate with your GitHun account and then modify the translations directly.

**Comment by ksaerdna** [comment]
Oh, too late... just started...  :-)
