### ISSUE TITLE
[Feature Request] Daily Backups

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#1279]
A great feature would be to have it so NewPipe could backup all of your playlists, history, subscriptions, etc daily to file called NewPipeData.zip or something, And daily it can overwrite the NewPipeData.zip file. 

The reason for this is to make the NewPipe devs jobs easier by not having to add all of these cloud storage services to the app. I use an app called [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite) which allows me to backup files from my phone to many cloud storage providers hourly, daily, weekly, etc.

So if users want to backup their NewPipe data to a cloud just add a feature for NewPipe to export its data daily to a special folder called DailyBackups or something and then users can download FolderSync and configure the backup of the DailyBackups folder to their desire cloud storage service.

But another thing about the backup is that is should be encrypted to keep the backup data safe when its being stored on the cloud. To do this you just need to create a password for your backup and to import it you need to enter that password so it can decrypt it. I am not an app dev but if there maybe a library to backup the file as a 7Zip and encrypt the 7z file with a password.

**Comment by theScrabi** [comment]
Encryption yes.
FolderSync no.
We want to support oprn standarts, se if we do daily backup than we could go with something like WebDav.
