### ISSUE TITLE
how does one sync their devices?

### ISSUE THREAD

**Issue by simonelthis** [TeamNewPipe/NewPipe#1281]
I know this is not a forum but how does one sync suscriptions and bookmarks between playlists?

**Comment by theScrabi** [comment]
There is non yet, you could use the export/import function of the database.

**Comment by simonelthis** [comment]
Is it in the works? It says it on your website?
[Untitled.png](https://postimg.org/image/pb1y31g4l/)

**Comment by TobiGr** [comment]
Oh. I should add a _manually_. ATM you need to go to the settings, export the stuff, get the zip file to the other device and then import it.

**Comment by theScrabi** [comment]
There is no automated sync yet. I think this is was people understand when they hear the word sync.

@TobiGr I think we may not want to call it sync on the website. Call it import/export.

**Comment by wb9688** [comment]
Can't we use Bluetooth? Everything is better with Bluetooth ;)

**Comment by theScrabi** [comment]
I think we should consider a proper cloud solution, so syncing does not involve a user action.

**Comment by TomJansen** [comment]
@theScrabi maybe with webDAV? Then you can support many cloud solutions in one go

**Comment by theScrabi** [comment]
Yes thats the plan :D

**Comment by theScrabi** [comment]
no

**Comment by trymeouteh** [comment]
I am personally not a fan of European cloud storage providers (Except for Switzerland). Is there a list of all the cloud storage providers that support webdav?

**Comment by theScrabi** [comment]
certainly. You can even host a webdav storrage at home if you want ;)

**Comment by speednroll** [comment]
this is directly related to the feature request that I did previously #1163

**Comment by cocoonkid** [comment]
please make webdav happen!

**Comment by rshadow** [comment]
I have a home media server. WebDaw would be the perfect solution for syncing devices at home.

**Comment by opusforlife2** [comment]
Have a look at #3157.

**Comment by Rik44444** [comment]
hello all! Thumbs up for webdav sync! Also a solution like this like Antennapod does might be possible https://gpodder.net

**Comment by EmanuelLoos** [comment]
You could also implement something like [Syncthing](https://en.wikipedia.org/wiki/Syncthing) or do it the way [Briar](https://briarproject.org/) or [OnionShare](https://onionshare.org/) transfer information over Tor.

That way it would be serverless and the user would b in full control of his/her data.

**Comment by natema** [comment]
I was about to open an issue in order to ask for the possibility to sync bookmarks and subscriptions across devices via Nextcloud, then I found this issue. I'm just commenting so that the thread shows up if someone search for `Nextcloud` in the issues.
Thumbs up for supporting WebDAV!

**Comment by mhmdanas** [comment]
Closing in favor of #5325.
