### ISSUE TITLE
List item display overlaps

### ISSUE THREAD

**Issue by DanteAndroid** [TeamNewPipe/NewPipe#1292]
Model: Samsung N9500
Screen display: Medium scale, medium font

Actually, I think the list_stream_item height is a little low, so I just change it to 110dp, just look fine.
My suggestion is:
1. **Change the layout to a better one** (which I'm not sure, maybe constraintlayout?)
2. **Add an option of having a large item view** which could bypass this issue (Youtube client has a way bigger item)

FYI:
### Before/after
<img width=300px src="https://user-images.githubusercontent.com/10005563/38475798-f74d680a-3bdc-11e8-93ef-4bf163999013.jpg"/> <img src="https://user-images.githubusercontent.com/10005563/38475923-8c159e6c-3bdd-11e8-95aa-278f7b5f7b17.jpg" width=300px/>

```
Before: 
    <!-- Elements Size -->
    <!-- 16 / 9 ratio-->
    <dimen name="video_item_search_thumbnail_image_width">124dp</dimen>
    <dimen name="video_item_search_thumbnail_image_height">70dp</dimen>
    <!-- Calculated: 2*video_item_search_padding + video_item_search_thumbnail_image_height -->
    <dimen name="video_item_search_height">94dp</dimen>
```
```
After: 
    <!-- Elements Size -->
    <!-- 16 / 9 ratio-->
    <dimen name="video_item_search_thumbnail_image_width">150dp</dimen>
    <dimen name="video_item_search_thumbnail_image_height">86dp</dimen>
    <!-- Calculated: 2*video_item_search_padding + video_item_search_thumbnail_image_height -->
    <dimen name="video_item_search_height">110dp</dimen>
```

**Comment by theScrabi** [comment]
Yea ... you are not the first who requested a change here.
Seems you already figured out a loot. Would you like to send us a pull request with the fix :)

**Comment by mauriciocolli** [comment]
It seems like your font is causing this, can you please try with the default android font?

**Comment by theScrabi** [comment]
> It seems like your font is causing this, can you please try with the default android font?

This is actually something I witness multiple people to have problems with. So one college at my work for example has a xiomi phone with a larger than default font, he has similar problems.

**Comment by speednroll** [comment]
this is related to #1008
