### ISSUE TITLE
request suport for 192 kbps audio

### ISSUE THREAD

**Issue by faydin** [TeamNewPipe/NewPipe#1293]
https://www.h3xed.com/web-and-internet/youtube-audio-quality-bitrate-240p-360p-480p-720p-1080p

According to this site, youtube has audio quality up to 192 kbps but in the app I can only download 128kbps.
What is the reason for that?

**Comment by theScrabi** [comment]
The itags need to be updated:
https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/ItagItem.java#L13

**Comment by opusforlife2** [comment]
AFAIK highest bitrate available is 160 kbps Opus. I have never seen a higher bitrate in youtube-dl.

Close as invalid, probably.

**Comment by wb9688** [comment]
I've never seen 192 kHz on YouTube either. We just show whatever the services serves us (or a subset of it).
