### ISSUE TITLE
[Feature Request] Simplify multi-service support

### ISSUE THREAD

**Issue by andrewferguson** [TeamNewPipe/NewPipe#1295]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

[Disclaimer - these are just my thoughts. I welcome feedback as to why this is not a good idea!]

In the latest version of NewPipe multiple services are now supported (both YouTube and SoundCloud). However I don't see that is particularly intuative that you go to the main menu to change which service is being used, because only two features are affected by which service is being used:
* Searching (where the results that appear are limited to only the current service)
* Related videos (where the related videos* that appear underneath a selected video are limited to only the current service)

My thoughts are that it would be simpler and less confusing if you chose a service when you searched. Then all the results that appeared would be for the service you chose when making the search. Similarly, when you are on a video, all of the related videos would be from the same service as the selected video.

The reason I think this is more intuiative is because many of the features that are offered by NewPipe (history, playlists, etc..) are completely service-independent, and therefore having the whole of the app (including the colour scheme!) change with the service - when in reality you can still access videos from service A when in the "mode" for service B - is a little confusing.

What do other's think?

*in SoundCloud's case this would be songs, as SoundCloud hosts songs, and not videos, but you get what I mean!

**Comment by theScrabi** [comment]
Yea well  it affects more then search and related videos, for example also kiosk.

If you select a video you only see videos offered by the same service, not videos offered by a different video. So unless your browse up to the root of the videos you selected you will not change the service. Therefore I think the design we have right now is god enough for what NewPipe is able to now.

**Comment by karyogamy** [comment]
Now that we have autoplay and gapless playback, guess which service we should add next ( ͡° ͜ʖ ͡°)

**Comment by theScrabi** [comment]
@karyogamy w8 for a bit, I'm currently reworking some bits.  For example I want to get rid of SearchEngine, and make it a propper ListExtractor.
You can see it at the search branch over at NewPipeExtractor. First PR comming today.

**Comment by trymeouteh** [comment]
I think it should appear as "audio" not "videos" or "songs" since Soundcloud is an audio platform. They have podcasts and such and podcasts are not songs. I do see it saying videos when I am on soundcloud in the NewPipe app even though they are audio clips. I understand it is a UI bug and a very minor one.

**Comment by theScrabi** [comment]
Search filter is still in refactor, after that every service is able to set its own filter.

**Comment by Stypox** [comment]
Closing in favour of #650, I moved your comment there
