### ISSUE TITLE
NewPipe Application : Can not download video

### ISSUE THREAD

**Issue by fadligenta** [TeamNewPipe/NewPipe#1296]
#### Expected behavior<br>
<br>
Hope I can download video from this app. And can enjoy all the downloaded videos from this app.<br>
<br>
#### Actual behavior<br>
In fact, when I downloaded something went wrong. I can not download video <br>
<br>
#### How to reproduce<br>
<br>
* Download the Application in f droid<br>
* Launch App<br>
* Please select the video you wish to download <br>
* Then click the download button at the bottom of the video <br>
* Customize the selection of videos you want to download <br>
* then Click OK<br>

>- Device used: Samsung Grand prime SM-G530<br>
<br>
>* Operating System: Android version 4.4.4<br>
<br>
>* Application version: 0.13.1<br>
<br>
#### Recording Of The Bug<br>
https://youtu.be/plRbBwxcDCE<br>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fadligenta/newpipe-application-can-not-download-video">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by justanidea** [comment]
Have you changed the path of the download ? Like to the sd card ? I have a Grand Prime too but i dont have any problem :) (sm g531 F)

**Comment by theScrabi** [comment]
Well in the video you wiggled around with a bug report. How about you put that bug report here ;)

**Comment by fadligenta** [comment]
Yes ...
How should I explain to you?

**Comment by fadligenta** [comment]
I can not download when saving the file to Sdcard.that is all

**Comment by theScrabi** [comment]
Yes thats a bug we are aware of. We need to take action here.
