### ISSUE TITLE
Subscribed Channels/Recommended Feed & Notifications

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#1299]
The YouTube app can give you notifications on new videos that have been added by your subscriptions and when you launch the YouTube app it shows all the recent and recommended videos based on your search criteria.

For notifications to work the app could scan your subscriptions every hour or do it daily and then give you a notification on new videos uploaded by your subscribed channels. 

For the feed every time you launch the app it can scan your subscriptions for new videos and display them on your feed.

For recommended  videos in your feed it could see what your subscribed channels new videos are and see what there next videos are to get an idea what is recommended for you. This may not be a good recommendation and this may just not be possible or a too painful to make it happen.

This way users can see what new videos are uploaded by their subscribed channels without having to check each channel and without having to use a gmail account.

I know this will take time to develop but its just a suggestion I had and I am sure many people will enjoy. Even if there are no recommended videos I am sure people would be happy to have a feed of their subscribed channels.

**Comment by theScrabi** [comment]
This is already under discussion, and the required parts for the backend are in work.
