### ISSUE TITLE
Save position

### ISSUE THREAD

**Issue by dbolser** [TeamNewPipe/NewPipe#1301]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

What I really miss is being able to close the app, reopen, and resume playing at the previous position.

**Comment by theScrabi** [comment]
Yes this was requested multiple times now. We think about this :)

**Comment by dbolser** [comment]
Ta.
