### ISSUE TITLE
New & Hot as well as Top 50 broken in Soundcloud

### ISSUE THREAD

**Issue by Jestemkioskiem** [TeamNewPipe/NewPipe#1304]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

You can see the full report of the bug over on Utopian.io - [here](https://utopian.io/utopian-io/@gentasteem/new-and-hot-and-top-50-features-can-not-work-newpipe-application). Utopian is a site that supports open source contributors with monetary incentive (steem cryptocurrency). I am a part of the team reviewing these contributions and was able to reproduce the bug.

If you wish to ban your repository from our website, let me know! As long as you don't I'll keep you updated about the issues to your project.

**Comment by theScrabi** [comment]
@wb9688 what could be the reason?

**Comment by wb9688** [comment]
Hmm… it works locally, except that it shows the same for new & hot as in
top 50

**Comment by theScrabi** [comment]
Hm well I have the same problem as @Jestemkioskiem here in Spain.

**Comment by wb9688** [comment]
@theScrabi: We try to get the localized version of the SoundCloud charts when it's available (e.g. when you've set your content country to "AU", "CA", "FR", "DE", "IE", "NL", "NZ", "GB" or "US"). Can you try it with a country in the list and a country not in the list? Both work for me. If it doesn't work for you with only one of them, can you tell me what country you've tried? If it doesn't work for you with both of them, I'll need more debug information (probably a `logcat` from a custom debug build).

Btw I don't like that Utopian.io *#@$, that link doesn't even work for me.

**Comment by theScrabi** [comment]
So by contribution you can earn STEEM coins there like on d.tube :P.

**Comment by B0pol** [comment]
This should be marked as Localization / Translation @Stypox

The reason why it doesn't change with language is simple
[As mentionned here](https://github.com/TeamNewPipe/NewPipe/issues/3089#issuecomment-585832060), the method giving supported countries is not overriden, and the code in chartsextractor is not built around that.

I'll fix it.
