### ISSUE TITLE
I click ok in the download window and the application crashes.

### ISSUE THREAD

**Issue by oktay454** [TeamNewPipe/NewPipe#1305]
{
"user_action": "ui error",
"request": "App crash, UI failure",
"content_language": "TR",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.13.1",
"os": "Linux Android 7.1.2 - 25",
"time": "2018-04-12 05:58",
"exceptions": [
"java.lang.RuntimeException: java.io.IOException: Permission denied\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:350)\nCaused by: java.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\njava.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\n"
],
"user_comment": "I click ok in the download window and the application crashes."
}

**Comment by SohamBiswas1** [comment]
Were you trying download the song in SD card ?

**Comment by SohamBiswas1** [comment]
Is your OS marshmallow? Because I am also having the same issue

**Comment by nametable** [comment]
I can confirm that I have the same issue. I made a folder on my SD card to download the videos to. When I set that folder to my download location in NewPipe and tried to download some video, the app crashed.
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "US",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.13.2",
   "os": "Linux Android 7.0 - 24",
   "time": "2018-04-14 18:48",
   "exceptions": [
      "java.lang.RuntimeException: java.io.IOException: Permission denied\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:350)\nCaused by: java.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\njava.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\n"
   ]

**Comment by justanidea** [comment]
See #962

**Comment by theScrabi** [comment]
AAAAA we need to show a notification when the app creashes to tell users that SD card is currently not supported.
