### ISSUE TITLE
Option To Close NewPipe In The Popup Window

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#1306]
Can you please add an option to close NewPipe in the popup window?

**Comment by karyogamy** [comment]
Probably not, since we prefer not adding redundant UI elements and the popup window already can be closed via the notification. Also, although not an obvious feature, the popup window can be closed by hard-swiping the window left or right.

**Comment by GKid94** [comment]
I don't have any notifications and I'm swiping the popup window but it doesn't go away

**Comment by theScrabi** [comment]
Can you show us that via screenshot?

**Comment by GKid94** [comment]
![screenshot_20180421-152515](https://user-images.githubusercontent.com/18757054/39084573-750eb2fe-4578-11e8-9154-4b3aeb1ceb5a.png)

**Comment by GKid94** [comment]
I just found out that I blocked all notifications from New Pipe that's why I don't see the notification, can you improve the swipe popup closing?

**Comment by karyogamy** [comment]
We will probably introduce a parameter in the settings to let users increase the sensitivity of the swipe and implement PIP for Oreo.
