### ISSUE TITLE
Remove The Auto Video Pause When Pressing On The Popup Window

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#1307]
Can you please remove the auto video pause when pressing on the popup window instead make it just to show the player controls when pressing on the popup window?

**Comment by Somethingweirdhere** [comment]
I have tried this but failed. It was easy to prevent the pausing, but I haven't managed to get the controls there.

**Comment by Stypox** [comment]
Fixed in #1342
