### ISSUE TITLE
How to download your playlists?

### ISSUE THREAD

**Issue by Stallonious** [TeamNewPipe/NewPipe#1309]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I see in the description that you can watch videos in your youtube playlists but I don't see how to download your playlists anywhere, just to download your subscriptions. How can I download my playlists?

Also, it would be great if the videos we download would retain their thumbnail.

Thanks!

**Comment by JuniorJPDJ** [comment]
You mean import from account?

**Comment by Stallonious** [comment]
yes, import from my youtube account. is that possible? there's a lot of videos i save in playlists to watch later and being able to download them in NewPipe would be awesome.

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1058
