### ISSUE TITLE
What's new Sorting

### ISSUE THREAD

**Issue by Severus157** [TeamNewPipe/NewPipe#1315]
It would be great if the Whats new Area for Youtube Videos would actually be sorted by the newest Videos from the Subscriptions.

Right now, it's sorted so damn stupid what is not making any sense.
Example:
1. Video I get is 2 days old
2. Video is 10 hours ago
3. Video is 3 years old

Would be great if the sorting could go like this:
1. Video 2 hours ago
2. Video 5 hours ago
3. Video 7 hours ago

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by justanidea** [comment]
See #1044
