### ISSUE TITLE
[Feature Request] Set Default Aspect Ratio

### ISSUE THREAD

**Issue by switchtegrax1** [TeamNewPipe/NewPipe#1318]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
This would be useful for people that multiwindow as the fill aspect ratio gives a fullscreen view while in landscape splitscreen and having to set it manually for every video can be such a drag

**Comment by hipunk** [comment]
I already submitted this request and as the dev is obviously super awesome, he implemeted such a feature already!

If you're watching a video, tap the upper right corner of the screen:
![newpipe aspect ratio1](https://user-images.githubusercontent.com/11931747/38782249-f9df3238-40f0-11e8-8380-515689ca8cd0.png)
Then look in the upper left corner of the screen to find the aspect ratio settings:
![newpipe aspect ratio2](https://user-images.githubusercontent.com/11931747/38782254-07bd236a-40f1-11e8-80c9-5cf2334c1e1b.png)


Hope this helps, it sure helps me!

Greetz,

hipunk

**Comment by hipunk** [comment]
Oh, I see. Don't know about that.

**Comment by dnesbitt03qub** [comment]
Yes, it would be nice if users with 18:9 screens could set the default to zoom. It shouldn't be a global default as not all users, or users with 18:9 screens will want this.

**Comment by 24RJ6** [comment]
Yes, please persist the zoom setting between videos and app restarts. It's super annoying for every video to click the down arrow, tap two times until it's in zoom mode and tap once more to hide the OSD again. MX Player does, VLC does it.

Please, it's 4-5 clicks for every single video.

Thanks a lot!
