### ISSUE TITLE
[Feature Request] Auto Detect Compatible Resolutions

### ISSUE THREAD

**Issue by switchtegrax1** [TeamNewPipe/NewPipe#1319]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It would be great if newpipe could automatically detect compatible resolutions (and hide incompatible ones) just like the default youtube app,it could also get rid of the show higher resoultions toggle

**Comment by justanidea** [comment]
Be careful with that : thanks of youtube I only could watch 480p
Here I can watch 1080p60 without any problem :)
