### ISSUE TITLE
Minimal version of NewPipe

### ISSUE THREAD

**Issue by TomJansen** [TeamNewPipe/NewPipe#1321]
It would be nice IMO to have a minimal version of NewPipe, just a minimal as possible. While I do think that extra features are great for some people, I would like to see a version that is completely focussed on supporting Youtube. The Soundcloud (and in the feature Dtube) integration add a lot of extra code to the APK

**Comment by justanidea** [comment]
Yeah maybe download the services we want

**Comment by TomJansen** [comment]
@justanidea addon-support maybe?

**Comment by justanidea** [comment]
Yeah if its not too hard for devs

**Comment by theScrabi** [comment]
Hm, the module thing is not posible with the architecture we have right now, and also I think modularizing NewPipe is not a good aproach.

We already plan a light version of NewPipe that comes with less functionalliy, however the aim there is getting play store compatibility, so we will just remove the necessary. If you want a real light weigt lightweight versoin of NewPipe you can use the [NewPipeExtractor](https://github.com/teamnewpipe/neawpipeextractor) and try to write a lightweight client with it. I think a seperated maintained application might be the best aproche here :)

**Comment by Somethingweirdhere** [comment]
@theScrabi Sounds good! Which component violates the Google TOS? I guess the downloading? What else needs to be done?

**Comment by droidberg** [comment]
i too agree that adding features is equal to adding bloat! honestly, this would be a great time to introduce a pro version that has all the soundcloud and other site stuff. the lite version could just be a youtube app. i would gladly pay for a lite version.

**Comment by Somethingweirdhere** [comment]
@droidberg Currently everything is free and open source, and I don't think there is a working way to force others to pay for an Open Source app. But I do understand if Scrabi wants to make some money off of it. You can donate too: https://newpipe.schabi.org/donate/

**Comment by theScrabi** [comment]
If it's just about the services, we already plan to introduce a lite version of NewPipe, which we will try to put on PlayStore as well.

**Comment by ktt9117** [comment]
I'm developing my application using youtube player library.
But they are not support many features. So I would like using newpipe video player (I need only player related feature - watching video, background playing, popup mode), , to my application. If it is possible, how can I do that? Is there any document or something?

**Comment by theScrabi** [comment]
The NewPipeExtractor, the core of newpipe, is an independent project. You can find it [here](https://github.com/teamnewpipe/newpipeextractor).

There is also a documentation of it:
https://teamnewpipe.github.io/documentation/
However it's early alpha and by far not complete. It also only covers the implementation of own extractors, but not how to use the NewPipeExtractor.

However there are several example apps such as [MusicPiped](https://github.com/deep-gaurav/MusicPiped) and [SkyTube](https://github.com/ram-on/SkyTube/) who also use the extractor.

**Comment by ktt9117** [comment]
@theScrabi Thanks bro. That is all I need. You are such a kindness man.

**Comment by theScrabi** [comment]
@ktt9117 however please be aware to opensource your app if you use the extractor :)

**Comment by ktt9117** [comment]
@theScrabi I know 😄 Thanks!
