### ISSUE TITLE
Sign In/Log In Option

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#1322]
Add an option to sign in or log in with your YouTube account

**Comment by theScrabi** [comment]
We want to be google independent, and send as less data to them as possible. So login is not in our scope unless its not avoidable in order to use a service.

**Comment by ThomasCr** [comment]
I also would like to log in to YT. So you can access (play/save) your playlists, access comments and mush more. Why not leave the choice to the end user?!

I know it gives some extra work, but maybe somebody else will provide some extra lines of code?!

**Comment by gkeegan** [comment]
Readme file says the app is trying to be as independent from Google as possible. Google services would probably then be necessary. Also it would probably increase apk size and decrease performance.

**Comment by xxxserxxx** [comment]
I'm aware I'm responding to an old comment, and that it's unlikely to be accepted.

I'd like to suggest a feature that allows configuring a login that is *only* used when a user upvotes a video -- since upvoting is not possible anonymously. It'd help content creators, and is an entirely optional and user-driven metric.

**Comment by lrq3000** [comment]
Seems like this issue needs to be revisited now that YouTube is regularly blocking users until they login, the only other alternative currently is to wait it out for 24h or open YouTube in a browser which defeats the purpose of NewPipe. 

For ref : https://www.reddit.com/r/NewPipe/comments/1p1hmdo/content_unavailable_or_your_ip_is_blocked_by/

And I am using the latest release v0.28.2
