### ISSUE TITLE
Notification not visible on Xiamomi Redmi Note 4 witg MIUI 9 8.4.12 (weekly)

### ISSUE THREAD

**Issue by adam-tychoniewicz** [TeamNewPipe/NewPipe#1323]
- [ x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x ] I checked if the issue/feature exists in the latest version.

Controls from Notification are not visible. There is only icon in notification bar, but when expanded there is nothing (no play/pause, exit button)

**Comment by mnazrth** [comment]
Same problem here.
Adding .setContentTitle("a string") and .setContentText("a string") to the notification builder in BackgroundPlayer.java fixes this.
I've opened a bug report on the MIUI forums, hopefully future updates will fix it.

**Comment by theScrabi** [comment]
@mnazrth is this fixed on our site as well?

**Comment by mnazrth** [comment]
No, but the new MIUI update (version 8.4.19 Global Beta) has solved the issue for me

**Comment by theScrabi** [comment]
ok.
