### ISSUE TITLE
Certain videos continually buffer, never load

### ISSUE THREAD

**Issue by tgp1994** [TeamNewPipe/NewPipe#1328]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I'm really happy to see the latest updates hit F-Droid!

It looks like since the 0.13.x releases, certain videos will continually buffer and never actually load. I'm able to see the video page with its information, but actually trying to load the video seems to fail. I'll try to update this as I find more videos that don't work. My settings include MP4 as the video format, and I think it's the same for audio.

- https://www.youtube.com/watch?v=legTJktVULY

**Comment by karyogamy** [comment]
Are you watching in 1080p/480p/360p/240p/144p (maybe as default)? Looks like this video is in 1080p60 and was just uploaded today, so youtube probably hasn't finished encoding it for certain qualities. See [this](https://github.com/TeamNewPipe/NewPipeExtractor/issues/65).

**Comment by tgp1994** [comment]
@karyogamy Hah, you're right! I even commented in that bug report. For some reason I thought I had also tried 720p60 (I was watching in 1080p like you said) and it still wouldn't load. Maybe it was only in 1080p60 at the time.

Sorry for the spam!
