### ISSUE TITLE
[Feature Request] Set subtitles/CCs on by default

### ISSUE THREAD

**Issue by plusuncold** [TeamNewPipe/NewPipe#1329]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

A quite nice (and likely easy) feature would be to be able to set a default subtitle/CC language and if the video has them available to show them by default.

**Comment by Sirove** [comment]
+1

**Comment by juanfra684** [comment]
If possible, please add also the option to enable the subtitles for different languages including the auto-generated subtitles. For example, the user could sets the languages and the priority: English, Spanish, Auto-generated(EN).

**Comment by juanfra684** [comment]
Bump.

**Comment by B0pol** [comment]
Closed by #2820
