### ISSUE TITLE
[Feature Request} minimize on exit

### ISSUE THREAD

**Issue by droidberg** [TeamNewPipe/NewPipe#1334]
currently when you click on a video it expands to a window that then allows you to play the video. when you press on the back button it closes the video and reverts back to the window. any chance you can make it so that the video minimizes to a floating window when you press back? this is one of the things i like about youtube and would love to see it in newpipe.

**Comment by Phoenix616** [comment]
If such a feature is implemented it should definitely be an option. I personally extremely dislike this behaviour about the official app, I expect the back button to go back and actually stop everything that's currently going on.

**Comment by theScrabi** [comment]
I agree with @Phoenix616. Also we already have a button to switch between popup and fullscreen mode.

**Comment by TimboJones** [comment]
Having it as an option would be awesome imo. It's just quality of life really, but more often than not I was just going back to the Homescreen and expected the video to go into pop-up mode automatically. I was thinking of implementing something like that before, maybe I'll get around to it

**Comment by theScrabi** [comment]
@TimboJones I'll merge it :)

**Comment by droidberg** [comment]
obviously, this would be an optional thing but it comes in handy when viewing a video and switching to another task. i also very often look for other videos to watch before the current one ends.

**Comment by trymeouteh** [comment]
I think this should be an option in the settings. You can set the back button to either exit the video (By Default), popup window, or background.
