### ISSUE TITLE
Autonext issue

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1336]
Please make disapear the autonext video when we enqueue a video after the first one

**Comment by TobiGr** [comment]
Yes that sounds good

**Comment by shivanju** [comment]
Hi. I want to work on this issue. I've already started looking into the code. As this is my first contribution to this project any guidance will be appreciated.

**Comment by shivanju** [comment]
Hi. I want to work on this issue. I've already started looking into the code. As this is my first contribution to this project any guidance will be appreciated.

**Comment by theScrabi** [comment]
You may want to take a look at thr playqueue at the player: https://github.com/TeamNewPipe/NewPipe

**Comment by shivanju** [comment]
Raised a PR https://github.com/TeamNewPipe/NewPipe/pull/1878
