### ISSUE TITLE
FEATURE-REQUEST stateful playback audio/videos

### ISSUE THREAD

**Issue by leinadlime** [TeamNewPipe/NewPipe#1340]
i like the youtube feature "watch-state" of a video,
which is representated in a red progress bar, under neath the video thumbnail,
showing where you stopped streaming, the last time you have played this media back.

now the killer feature would be to have all them displayed at once.
and if not only on youtube, but souncloud, etc,... we could build a feature
to show and let the user decide, in which playback one want to go back.

i would try to call this "stateful watchlist" or "playback overview", for now,
and there could be helpful for these use cases:
- a simple "watch later" list,
- video playlist of "series/lectures/episodes"
- audio playlist of "podcasts/audiobooks" (which would be convenient to have synced on the go.)

what do you think? is it understandable? :)

**Comment by karyogamy** [comment]
The watch state is already being saved in the database in the current release, though we still need to think of a good UI and someone need to implement it.

**Comment by Stypox** [comment]
Implemented by #2288
