### ISSUE TITLE
10 seconds forwards/backwards always appears in the middle

### ISSUE THREAD

**Issue by gregordr** [TeamNewPipe/NewPipe#1341]
- [x] I checked if the issue/feature exists in the latest version.
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

It's not really a big issue, but on YouTube the animation is on the side that you pressed on (right for forwards, left for backwards). I'm mostly wondering if anyone really feels like this needs to change, I have taken a look at it and it seems like a relatively easy change.

**Comment by B0pol** [comment]
It has been fixed
