### ISSUE TITLE
Download subtitles

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#1347]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

[From our blog]

[Francesco asked](https://newpipe.schabi.org/blog/pinned/NewPipe-needs-feedback/#isso-104) us to enable subtitles download as an option in the download dialog.

I guess this shouldn't be that difficult. Maybe someone can implement this along with #962.

**Comment by theScrabi** [comment]
Yup definetly a good idea.

**Comment by TobiGr** [comment]
Implemented in #1759
