### ISSUE TITLE
[Feature Request] Webtorrent / Torrent support

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1349]
- [ x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x ] I checked if the issue/feature exists in the latest version.

Webtorrent and Torrent support should be considered as an increasing amount of services use them. (Bitchute, Peertube and potentially more).

**Comment by theScrabi** [comment]
Yes we neeed to think about adding this into our extractor bakend.

**Comment by trymeouteh** [comment]
I would like to see this so we are able to add Bitchute to NewPipe.

**Comment by kgbm3** [comment]
No, please... No torrents, lol. Looking at the issues, there seem to be *tons* of things to do already.

**Comment by theScrabi** [comment]
We need to see once service is there. If someone is able is able to add a webtorrent service that does not bump our apk size to an unrealistig high, and if it runs smooth without draining battery and connection bill, ... id be happy. After all webtorrent is like the idealistic way. However I'm sceptical. Maybe we could add bitchue etc if there is some sort of gateway like there are for d.tube.

**Comment by Symbian9** [comment]
Latest `youtube-dl` added some improvements in it's PeerTube extractor with example for `https://video.blender.org/*`

- https://github.com/rg3/youtube-dl/releases/tag/2018.06.19
  - https://github.com/rg3/youtube-dl/issues/16733
    - https://github.com/rg3/youtube-dl/commit/8b4b400aef83b233502ece7321ee84f6ab9e213e

**Comment by KonoromiHimaries** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/664

**Comment by AudricV** [comment]
Unfortunately, Torrent and WebTorrent are hard to support on Android, as ExoPlayer/Media3 (the player library we use) has no native support for them and there is probably not a lot (if not at all) Android/JVM libraries for them that exist.

PeerTube also removed WebTorrent support in their 6.0 version, and no service implemented in the extractor supports that (except the PeerTube implementation).

Seeing the lack of interest in these technologies, I am closing this issue as won't fix. We can always reconsider this feature in the future if there is more interest (and if it's not hard to do and maintain, as the team has a limited bandwidth).
