### ISSUE TITLE
programmatic language list generation

### ISSUE THREAD

**Issue by eighthave** [TeamNewPipe/NewPipe#135]
I saw this comment in `settings_keys.xml`:

```
    <!-- TODO: scrape these programmatically, then store in a local cache -->
    <!-- alternatively, load these from some local android data store -->
```

I've made a similar library-like thing that could also be used for that case.  It is meant for changing an app's interface language separately from the system language.  This is useful since Android only provides one language choice, not a list.  So if an app does not support your language, it defaults to English.  For much of the world, there are much better fall back languages.  For example, people from former Soviet countries mostly would speak Russian over English and Tibetans mostly would speak Chinese over English.

Here's the code, its a single java file:
https://github.com/zom/Zom-Android/blob/d15de442058f991c102788f032d9dc839add18f3/awesomeAppCore/src/main/java/info/guardianproject/util/Languages.java

and here is how its used:
https://github.com/zom/zom-android/commit/d15de442058f991c102788f032d9dc839add18f3/

**Comment by litetex** [comment]
Will close this issue:
* affected code is now longer present
* Links are dead
* No progress since >5 years
