### ISSUE TITLE
Consistent error on download request. All required permissions granted.

### ISSUE THREAD

**Issue by TinKode** [TeamNewPipe/NewPipe#1353]
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "US",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.13.2",
   "os": "Linux samsung\/heroltexx\/herolte:7.0\/NRD90M\/G930FXXU2DRB6:user\/release-keys 7.0 - 24",
   "time": "2018-04-26 11:54",
   "exceptions": [
      "java.lang.RuntimeException: java.io.IOException: Permission denied\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:350)\nCaused by: java.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\njava.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\n"
   ],
   "user_comment": ""
}

{
   "user_action": "requested kiosk",
   "request": "https:\/\/www.youtube.com\/feed\/trending",
   "content_language": "US",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.13.2",
   "os": "Linux samsung\/heroltexx\/herolte:7.0\/NRD90M\/G930FXXU2DRB6:user\/release-keys 7.0 - 24",
   "time": "2018-04-26 11:56",
   "exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse yt-lockup-meta although available: https:\/\/www.youtube.com\/watch?v=q8v9MvManKE\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeStreamInfoItemExtractor.getViewCount(YoutubeStreamInfoItemExtractor.java:140)\n\tat org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:69)\n\tat org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:89)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeTrendingExtractor.getInitialPage(YoutubeTrendingExtractor.java:97)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)\n\tat org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:79)\n\tat org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:61)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$8$ExtractorHelper(ExtractorHelper.java:149)\n\tat org.schabi.newpipe.util.ExtractorHelper$$Lambda$8.call(Unknown Source)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3096)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3096)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:3940)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:13610)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:3940)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3096)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)\n\tat java.lang.Thread.run(Thread.java:762)\nCaused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1\n\tat java.util.ArrayList.get(ArrayList.java:411)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeStreamInfoItemExtractor.getViewCount(YoutubeStreamInfoItemExtractor.java:138)\n\t... 32 more\n"
   ],
   "user_comment": ""
}

**Comment by TobiGr** [comment]
1) Did you try to download to an external SDcard? Then this is covered by #962.

2) That's #1352
