### ISSUE TITLE
USA content bug in 0.13.2

### ISSUE THREAD

**Issue by maxborowsky** [TeamNewPipe/NewPipe#1357]
If I selected the default content different from United Kingdom (for example USA, Russian Federation etc), at the app start, an error message pops up.
<img src="https://user-images.githubusercontent.com/20723033/39405662-62e71b90-4bb1-11e8-894c-25fbd03678da.jpg" width="280">

**Comment by theScrabi** [comment]
can you please send us the content of the error message.

**Comment by maxborowsky** [comment]
>**theScrabi**
How can i do this? To which e-mail can I send the log?

**Comment by maxborowsky** [comment]
**My log**:

{
   "user_action": "requested kiosk",
   "request": "https:\/\/www.youtube.com\/feed\/trending",
   "content_language": "US",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.13.2",
   "os": "Linux Android 8.0.0 - 26",
   "time": "2018-04-29 14:23",
   "exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse yt-lockup-meta although available: https:\/\/www.youtube.com\/watch?v=q8v9MvManKE\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeStreamInfoItemExtractor.getViewCount(YoutubeStreamInfoItemExtractor.java:140)\n\tat org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:69)\n\tat org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:89)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeTrendingExtractor.getInitialPage(YoutubeTrendingExtractor.java:97)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)\n\tat org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:79)\n\tat org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:61)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$8$ExtractorHelper(ExtractorHelper.java:149)\n\tat org.schabi.newpipe.util.ExtractorHelper$$Lambda$8.call(Unknown Source:6)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3096)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3096)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:3940)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:13610)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:3940)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3096)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1\n\tat java.util.ArrayList.get(ArrayList.java:437)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeStreamInfoItemExtractor.getViewCount(YoutubeStreamInfoItemExtractor.java:138)\n\t... 32 more\n"
   ],
   "user_comment": ""
}

**Comment by Stypox** [comment]
Is this still an issue? I can't reproduce it... Probably because locales do not work at all now, it seems like :-/

**Comment by maxborowsky** [comment]
> Is this still an issue? I can't reproduce it...

Version 0.16.2 - change content locales and countries work correct. I think the bug has already been fixed in one of the previous versions...

**Comment by Stypox** [comment]
Ok, thanks :-)
