### ISSUE TITLE
AudioFX bug

### ISSUE THREAD

**Issue by chiru-michiru** [TeamNewPipe/NewPipe#1359]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
Hello.  Sometimes (like once on three or two videos) I receive a bug. I receive a massage that AudioFX stops working, however I don't receive any other error messages. I'm sorry for the quality, I wasn't able to take a screenshot.
https://imgur.com/a/ZXAlyjw
I'm using Android 5.1 and a custom ROM based on CyanogenMod.

**Comment by theScrabi** [comment]
Seems like an android problem. Can you plese provide a log.

**Comment by chiru-michiru** [comment]
There's no log. Only that massage. 

Also it works fine with the audio player but the same massage just appeared when I turned on Radiodroid. And now I think that the problem is on my side. Sorry for the false alarm,
