### ISSUE TITLE
[Feature Request] search ability inside a channel

### ISSUE THREAD

**Issue by jsimeo** [TeamNewPipe/NewPipe#1361]
Hello, and thank you for this great app!

It would be very usefull to me, and I guess for others too, to be able to search/filter within a channel. When a fav channel has hundreds or thousands of files, scrolling can't help you find the particular files-songs-etc.

Thank you again!

**Comment by hujan86** [comment]
I installed NewPipe last week and would love to see feature implemented. Easier to search for specific videos within channels both subscribed and non-subscribed.

**Comment by jsimeo** [comment]
> I installed NewPipe last week and would love to see feature implemented. Easier to search for specific videos within channels both subscribed and non-subscribed.

Just removed my old version and re installed the latest (0.15.1) but I still can't see this option for searching withing channel.

On what version you saw this implement?

**Comment by Stypox** [comment]
Closing in favour of #2414
