### ISSUE TITLE
[Issue] 'Time counter' is defined relative to your position 

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1362]
Im french, and Newpipe is in french for me.
But today im in Italia, and instead of having "il y a deux jours"(two days ago) I have it in italian !(2 giorni fa) XD But all the rest of words in the app is still in french...So its quite confusing...

**Comment by theScrabi** [comment]
Yes thays a known issue.

**Comment by justanidea** [comment]
Sorry
