### ISSUE TITLE
search shell command

### ISSUE THREAD

**Issue by illustribe** [TeamNewPipe/NewPipe#1364]
Hello,
How can I start new pipe with a search query via a shell command?

Thank you and congratulations on your great work :)

**Comment by theScrabi** [comment]
With pm the package name org.schbai.newpipe, and the input comamnd however you will be better off looking up how to use pm and input.

**Comment by illustribe** [comment]
Ok thanks a lot!

**Comment by illustribe** [comment]
Yes, I will check on pm command, thank you.
I was asking the specific command to search a query because I want to run the search through a search engine app (searchBar ex https://play.google.com/store/apps/details?id=com.devhomc.search) where I can select the app to use for the search (in this case new pipe) but I have to provide the command to use...

Thanks!
