### ISSUE TITLE
Can't import OPML history and subscriptions

### ISSUE THREAD

**Issue by nunbit** [TeamNewPipe/NewPipe#1365]
I exported my subscriptions and history from that stupid youtube into a file as opml and downloaded zip. When i try to import into NewPipe nothing happens. What could be wrong? Tried on Android KK and MM with latest NewPipe.

**Comment by Stypox** [comment]
Is this still an issue? After TeamNewPipe/NewPipeExtractor#160 it should be fixed, if not reopen
