### ISSUE TITLE
If video is playing in popup/background tapping play continues in main player

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#1366]
When I am listening to a video in the background or have it in the popup and I press play on the video page to view it in fullscreen mode it would be nice to not have the video start over but to continue in fullscreen mode.

If many people like how it is now were if your listening to a video in the background or have it in the popup and I press play on the video page to view it in fullscreen it will start over an option in the settings to choose what you prefer would make everyone happy.

**Comment by Stypox** [comment]
Fixed by #2907

**Comment by opusforlife2** [comment]
Close, then.
