### ISSUE TITLE
[FR] boost sharing

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#1367]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Usecase: a user wants to share a video he've seen with a friend. He goes to history, find the video and.. slowdowns start.
1. He could longtap on it but share option is absent.
2. He opens the video again but cannot share until the metadata loaded.

Possible to boost?

**Comment by theScrabi** [comment]
You should be able to share without needing to load the whole metadata.

**Comment by ildar** [comment]
Can't. Clearly on slow connections. Just see the "loading" indicator and
"Share" button doesn't react.

**Comment by MayeulC** [comment]
An option to share any result list could solve this, and would be welcome for when I browse videos to play on Kodi (It could also be an icon on the result list -- and ideally, only when connected to the Kodi player, though that would be harder to achieve).

**Comment by ildar** [comment]
I believe this one is fixed #1367

**Comment by ildar** [comment]
thanks BTW
