### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [TeamNewPipe/NewPipe#1368]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by theScrabi** [comment]
I don't understand. What do you mean by copywriting? Why do you want to communicate via mail?

**Comment by Hamzeto938** [comment]
it means like i want to create a writeup for about us and FAQs for ur app and if u like it. u can merge it

**Comment by TobiGr** [comment]
I am currently working on a FAQ. Take a look at TeamNewPipe/website#69 and TeamNewPipe/NewPipe#1316. I hope to finish the technical things in the next two  weeks. We would then need good tutorials. I'd love to have someone helping me with  that, because my time is limited at the moment.

**Comment by TobiGr** [comment]
@Hamzeto938 Please reopen in case you are still interested in helping us. You can also contact us via IRC on freenode: [#newpipe](http://webchat.freenode.net/?channels=%23newpipe)
