### ISSUE TITLE
Use https instead of http

### ISSUE THREAD

**Issue by Avizini** [TeamNewPipe/NewPipe#1370]
Idk if you already use https version but when I was streaming videos, my ISP was able to mitm my connection

![https://framapic.org/02mZJOq85pfc/63Ycd8oHXRSG](https://framapic.org/02mZJOq85pfc/63Ycd8oHXRSG)

When connected to vpn, newpipe connects to a ip from Google, otherwise it connects to something.mtnl.net.in

Mtnl is my ISP.

Also if using https by default then warn users about SSL errors. Net monitor says that connection with mtnl.net.in is also encrypted!

**Comment by Avizini** [comment]
Screenshot above is with a vpn and below is without a vpn

**Comment by theScrabi** [comment]
NewPipe uses https. However we do not do cert pinning yet.

**Comment by kioth** [comment]
Your ISP is just peering not MITMing

**Comment by kioth** [comment]
Some ISPs host google's content on their servers to save bandwidth and provide faster service for their customers.

**Comment by Avizini** [comment]
Oh! I get it, they act like a CDN. Closing this issue, thanks.
