### ISSUE TITLE
Crash on start (0.13.3)

### ISSUE THREAD

**Issue by repsorp** [TeamNewPipe/NewPipe#1374]
{
"user_action": "something",
"request": "Subscriptions",
"content_language": "GB",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.13.3",
"os": "Linux Android 7.1.2 - 25",
"time": "2018-06-05 08:02",
"exceptions": [
"android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database\n\tat android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)\n\tat android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)\n\tat android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)\n\tat android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)\n\tat android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)\n\tat android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)\n\tat android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)\n\tat android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)\n\tat android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)\n\tat android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)\n\tat android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)\n\tat android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)\n\tat android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)\n\tat android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)\n\tat android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)\n\tat android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)\n\tat org.schabi.newpipe.database.subscription.SubscriptionDAO_Impl$6.call(SubscriptionDAO_Impl.java:300)\n\tat org.schabi.newpipe.database.subscription.SubscriptionDAO_Impl$6.call(SubscriptionDAO_Impl.java:298)\n\tat android.arch.persistence.room.RxRoom$4.apply(RxRoom.java:111)\n\tat android.arch.persistence.room.RxRoom$4.apply(RxRoom.java:108)\n\tat io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.tryOnNext(FlowableMap.java:124)\n\tat io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:637)\n\tat io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)\n\tat java.lang.Thread.run(Thread.java:761)\n"
],
"user_comment": ""
}

**Comment by theScrabi** [comment]
Uch thats a nasty s***. Your option here is to remove NewPipe and reinstall it. However all your saved data will be lost unless you have a backup.
