### ISSUE TITLE
Popup window size adjustment and lock screen media controls

### ISSUE THREAD

**Issue by chris47368** [TeamNewPipe/NewPipe#1379]
Could you add a way to change the popup window size? In the beta version the window size was a little too big but was OK,but with the newer newpipe versions of the non beta app the popup window is way too small with no way to adjust the size :(

Adding a way to adjust the size would be great like for example dragging a corner of the popup to adjust the size would be great.

One other feature i request is a way to control the background player from lock screen controls in the same way you would with a music player app since in order to skip,pause or replay a video i have to unlock my screen and go into the notifications or app to access the controls.
Adding a way to get to a specific part of the video from the home screen would be good too,by for example having your typical pause/play,go back and forward buttons on the lockscreen then if you hold the control widget down you can then access/modify video stream position.

 I would greatly appreciate those implementations, thank you Newpipe team :)

**Comment by chris47368** [comment]
Thanks i will try :)

**Comment by Somethingweirdhere** [comment]
#834 Should add controls if I'm not wrong.
