### ISSUE TITLE
Auto rotation not working on Android Oreo 8.0

### ISSUE THREAD

**Issue by gitSaptarshi** [TeamNewPipe/NewPipe#1380]
Auto rotation not working in the app on Android Oreo 8.0. The handset is Lenovo k8 note with newly updated to Android 8.0 Oreo. The handset is running stock ROM and is not modified or rooted.

**Comment by theScrabi** [comment]
which rotation is not working, the automatic, or the one when you tap on the rotate button?

**Comment by baimafeima** [comment]
@theScrabi I'm running the latest `LineageOS 15.1` based on `Android 8.1`. I always have all auto-rotate functionality deactivated in my phone through the drop-down menu. Is it possible to have `NewPipe` use the widescreen by default and override the deactivated auto-rotate functionality? I believe something similar is at place with the app [Zapp](https://f-droid.org/en/packages/de.christinecoenen.code.zapp/) and it works amazingly well. It would be great if you could implement that.

**Comment by baimafeima** [comment]
Maybe @cemrich can help with this issue?

**Comment by theScrabi** [comment]
You can use the newpipe rotate button, it will remember the last rotation.

**Comment by baimafeima** [comment]
I looked for it but cannot find the button. Where in the settings is it located?

**Comment by cemrich** [comment]
Here it is - it is hidden behind a foldout menu:
![screenshot_20181018-141725](https://user-images.githubusercontent.com/403202/47153831-f7668b00-d2e0-11e8-8900-d6c5b1af4bc5.jpg)

**Comment by baimafeima** [comment]
Thanks a lot! I guess this issue can be closed unless you want to make it default to widescreen.
