### ISSUE TITLE
[UX] Improve notification for background audio player

### ISSUE THREAD

**Issue by Tonat** [TeamNewPipe/NewPipe#139]
Hey there,
thanks for adding the background audio player. In v0.7.1 it seems to do what it's supposed to do. 
  However I noticed that in the displayed notification the play-pause-button (which is working, the audio can be stopped and continued) does not change its image. 
  So it would be nice (and user-friendly) to have a || -like image when the audio is playing and the current triangular image when the audio's been paused.  Cheers!

**Comment by theScrabi** [comment]
All right, is not that complicated.
