### ISSUE TITLE
Two histories

### ISSUE THREAD

**Issue by Somethingweirdhere** [TeamNewPipe/NewPipe#1391]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It seems like there currently is a search history, a list of the last played videos and a list of watched videos. I feel like this should be split up in a search history + watched history.

**Comment by theScrabi** [comment]
You can access the search history when you click on the lense icon. Unless you type something you will se the full history. You can even modify it.

**Comment by Somethingweirdhere** [comment]
@theScrabi Exactly! But when you go to the three dots button there is another history/Verlauf but with less features. 

I feel like the one in the three points is redundant and could just redirect to the one found in the bookmarks. It's quite annoying when I need to go to the right type of history only to find out I need to go to the other one if I want to play all videos in background.

**Comment by theScrabi** [comment]
?

Isn't this basicly the change I did with the latest 0.13.3 release? Are you using an old version? xD

**Comment by Somethingweirdhere** [comment]
@theScrabi Yeah you are right lol. I shouldn't be opening issues after midnight. Sorry ^^
