### ISSUE TITLE
[Feature Request] tap or drag to skip/seek in audio in Background Player

### ISSUE THREAD

**Issue by adueck** [TeamNewPipe/NewPipe#1393]
It would be really great to also have an option to skip back and forth in the Audio in the Background Player. This could be done with a button or an area that the user could tap, or also by dragging left or right on the screen to seek back and forward?

In the pulldown widget the << and >> buttons are great, but it would also be nice to have something like those buttons in the Background Player and a little more control / flexibility in seeking back and forth in the audio.

**Comment by Stypox** [comment]
Closing in favour of #1967
