### ISSUE TITLE
[Improvement] Create something that lets users vote for new features

### ISSUE THREAD

**Issue by StarTrekRocks73** [TeamNewPipe/NewPipe#1394]
Hi everyone.

I think that making a voting feature that allows users to voice their opinions about new features and/or feature improvements would increase user interaction and help with the development of NewPipe. Some other FOSS projects impliment a voting feature inside of the app. 

I want this feature to be something other than making a github issue.

**Comment by theScrabi** [comment]
The problem for us as developer is that for such things we ad extra channels. The more channel we open, the more we have to moderate, and the less time is left for actual development. We already have sentry github and our blog, so even though it might not look perfect, sticking to github, and just bumping issues would be the best for the next time :)
