### ISSUE TITLE
[Improvement] Create something that allows users to submit bug reports easily

### ISSUE THREAD

**Issue by StarTrekRocks73** [TeamNewPipe/NewPipe#1395]
Hi everyone,

I think that there should be a way for people to notify the development team about bugs voluntarily. By this I mean that people should be able to contribute bugs at times other when the program crashes. 

I want this feature to be something other than making a github issue.

**Comment by Somethingweirdhere** [comment]
@StarTrekRocks73 You can post bugs here.

I do feel like you should be able to label your own issues as bug reports, but I think this is alimitation from github.

**Comment by StarTrekRocks73** [comment]
@Somethingweirdhere Thanks for the fast response. I agree that we should be able to tag our issues.

**Comment by theScrabi** [comment]
As @Somethingweirdhere said, github issues is thought for this. :)
