### ISSUE TITLE
[Feature Request] I would like to be able to filter search results by video quality

### ISSUE THREAD

**Issue by MatthewR37** [TeamNewPipe/NewPipe#1396]
Hi everyone.

Something that has been bothering me about NewPipe for a while is that I cannot filter the searg results by video quality. It can get annoying because I might be looking for a 1080p clip, but most of the clips that show up are 360p.

I noticed that the other foss YouTube apps don't have this, so adding this feature would help NewPipe to stand out.

**Comment by theScrabi** [comment]
The question is would such a sort be supported by newpipe?

**Comment by Hashik-Donthineni** [comment]
He is asking for a feature I believe, a "filter" feature in which if 1080P is selected, only videos having 1080P resolution(and above) will show up.

**Comment by theScrabi** [comment]
> The question is would such a sort be supported by newpipe?

I ment youtube.

The question is would such a sort be supported by youtube?

I talk and mention NewPipe so often that i sometimes mix up NewPipe with youtube.

**Comment by theScrabi** [comment]
Ok than it can be done. I actually work on a feature for backend right now that would allow more detailed filtering/sorting.

**Comment by Hashik-Donthineni** [comment]
Can you turn newpipe extractor into RESTful API? If you do that it can be used for both Android, Desktop if people are willing to build, also maybe for Flutter app who knows...

**Comment by theScrabi** [comment]
I want to, but please discuse this at another tread.

**Comment by Hashik-Donthineni** [comment]
Ow, sorry about that.

**Comment by StarTrekRocks73** [comment]
@theScrabi Do you think that you can add this feature to the next release? I really want NewPipe to have this feature.

**Comment by theScrabi** [comment]
@StarTrekRocks73 I am currently working on supporting further sorting, but it will definitely take some time until we can sea the first advantages of it.

**Comment by Hashik-Donthineni** [comment]
Idk about HD but sorting according to time and sort by upload date/time is a damn useful feature. It is a must have and many people use it.

**Comment by Stypox** [comment]
Closing in favour of #2251 #110 and TeamNewPipe/NewPipeExtractor#124
