### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by probonopd** [TeamNewPipe/NewPipe#1398]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

In the latest version as of today, cannot download anymore. The download does not start. Phone: Motorola Moto G4.

Please let me know what to report here in order to facilitate debugging.

**Comment by theScrabi** [comment]
Can you give us further descriptuon. Which android version, where do you want to download, and does everything else work?
