### ISSUE TITLE
[FR] Favourites aka bookmarks

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#14]
As long as the app doesn't support online accounts, I'd want to have local Favourites aka bookmarks.
Thanks for the great app!

**Comment by fred702** [comment]
Good idea, @ildar. I think RSS may be a good way of handling this. For those with a Google account, subscriptions can be [exported](https://support.google.com/youtube/answer/6224202?hl=en) to an OPML file. Perhaps NewPipe could have an import/export feature for that.

For those not using Google the template for a channel's RSS feed is:

`https://www.youtube.com/feeds/videos.xml?channel_id=XXXX`

**Comment by theScrabi** [comment]
Well I'm planing to implement the hole channel thing. Means searching, subscription, and status update. So far I'm also using an rss feed reader to subscribe to some. @fred702 As far as i know not all channels allow rss is that true?

**Comment by fred702** [comment]
@theScrabi You might have to go digging into the website source, but i've always been able to find a channel id. I'm not sure if there's a way to automate it using an API.

**Comment by Rob--W** [comment]
Why go fancy? Just being able to bookmark a video or seeing the history of played videos would be nice.

**Comment by theScrabi** [comment]
Well subscription is another topic of coerce,  but it would still be a great feature. Bookmarks on the other hand is rather simple, in fact its more or less what i hope to implement next.

**Comment by timofonic** [comment]
I want to not need the cloud, but just be able to import my already bookmarked videos in OPML.

And if I can automatically mirror them in a big SD, even better.

**Comment by theScrabi** [comment]
Yes I don't want the could either. Mirroring onto the SD card wouldn't be such a great problem, so we could do that :)

**Comment by aphirst** [comment]
I'd definitely like to see support for "pseudo-subscriptions" using the RSS feeds offered by each YouTube channel's page, just like I do in my desktop Web Browser.

**Comment by 2SI3NX** [comment]
would definitely love this feature and agree with @aphirst about the channel subscriptions but must be local (without online account login)

**Comment by theScrabi** [comment]
It will be local.
It'll be the next thing I'll work on:
Designing a proper database for such things.

**Comment by ildar** [comment]
Are we there yet? 😉

**Comment by theScrabi** [comment]
Almost, but I got interrupted, I have my exams right now.

**Comment by theScrabi** [comment]
I have my exams at the moment, afterwards I have some time to take care about this.

**Comment by ildar** [comment]
👍 good luck and don't worry!

**Comment by theScrabi** [comment]
thanks :)

**Comment by axelsimon** [comment]
Don't mean to be the "are we there yet" kid, but is there any progress on this? I really enjoy using NewPipe… except for when I start watching a video, go do something else, forget about it, click a Youtube link in another app that opens NewPipe and then remember that I was watching something interesting.
And there is now no way to finding what it was.

Also, a simple history (log) of what was watched would help answer a question that comes up often (to me, at least): what was that interesting video I watched (or started watching) the other day?

In any case, thanks for making NewPipe 😃

**Comment by mauriciocolli** [comment]
@axelsimon the latest version of NewPipe includes a search and watch history. 

But favorites will come as soon as playlist support is implemented (essentially _it is_ a playlist).

**Comment by 2SI3NX** [comment]
Although when you implement this, there should be a Favorites button which should be easily accessible in Kiosk :)

**Comment by ildar** [comment]
Playlists are here and working.
I guess we're in one leap to Favorites?
I suggest all usual YT lists be implemented for user's sake: +1 👍 (aka
Favorites), Watch later, ... what else?

**Comment by theScrabi** [comment]
Yea but can't you add a playlist like favourite, or watch later yourself, or do you think its necessary for us to label those?

**Comment by ildar** [comment]
I can. My child - hardly )))
A star as the "Add to Favorites" action is much demanded by my sun. Please?

**Comment by theScrabi** [comment]
By your son hä 😀. Na if it's like that we need to discuss that ;D

However the thing is that i always want to keep the UI as flat as possible, in order not to add double functionality, or doube paths. Otherwise this would bload it. We already are at a point where we barely can put something at the detail screen, but still have to.

**Comment by ildar** [comment]
:)
This is very rational approach.
But actually this isn't about "customization" but actually the question of
UI/UX. Favorites/Star/Bookmarks is a very recognizable and demanded
interface capability. Children is just one example of users who needs Star
because playlists aren't as usable for them.
I don't insist but writing this just to move my sun from WebTube to NP. For
me NP is the everyday app and I don't see any better.
Thanks for developing it! My respect to devs.

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ildar** [comment]
I step back. My 7 years old sun seem to easily use playlists as they are
currently.
So you can close this FR, I don't mind.
(How fast they grow!)))

**Comment by theScrabi** [comment]
:D all right.
