### ISSUE TITLE
Double tap options

### ISSUE THREAD

**Issue by umunais** [TeamNewPipe/NewPipe#1401]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
please provide an option to adjust the double tap seek timing from at least five seconds onwards.

**Comment by Somethingweirdhere** [comment]
Looks like an easy change. Two questions:

 - Should there be a picker between 5, 10 and 30 seconds or just a field where you can input the desired amount?
 - Double tapping and pressing the fast forward button in the background player notification currently use the same function in Baseplayer, so if you change the double tap seek time it also changes the seek time of the background player. I assume that's alright, or do we need seperate options for both players?

**Comment by umunais** [comment]
Thanks for your response.
Well, personally I think a picker to choose time period less than 5 seconds
in seek option is unnecessary since adding quite a number of multiples of 5
will be more than sufficient, just like in original YouTube API.
also i don't think no modification related to controls is needed so far as
background and main players are concerned.

**Comment by umunais** [comment]
The issue has not been resolved

**Comment by Keychain-SSB** [comment]
Being able to skip just 5 seconds instead of 10 would be ideal. Fingers crossed on this being a thing soon!
