### ISSUE TITLE
Yes

### ISSUE THREAD

**Issue by nissa-sabyan** [TeamNewPipe/NewPipe#1403]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by gkeegan** [comment]
May I ask why this is important?

**Comment by TobiGr** [comment]
@gkeegan Yes
@nissa-sabyan You notified 209 watchers successfully ;) Is there anything you want to tell us? If this is the case, feel free to reopen this.

**Comment by theScrabi** [comment]
> feel free to reopen this.

Yesn't
