### ISSUE TITLE
In android 4.4.4. The download list can not be displayed

### ISSUE THREAD

**Issue by nissa-sabyan** [TeamNewPipe/NewPipe#1404]
In android 4.4.4. The download list can not be displayed

**Comment by johnnyw3** [comment]
Works for me, on 4.4.4

**Comment by theScrabi** [comment]
> In android 4.4.4. The download list can not be displayed

@nissa-sabyan just saying that things don't work doesn't help. You need to help us help you. Provide some detailed info about why it does not work. How can we reprocude it. What phone/np version do u use. etc.

until provided -> close
