### ISSUE TITLE
Why now i cant download 240p with audio?

### ISSUE THREAD

**Issue by JScars** [TeamNewPipe/NewPipe#1408]
I loved to download 240p, since it mades download and share short videos faster... But now i can't, any video hasn't audio at 240p resolution! And it's just stupid because i can play it at that resolution with audio, it's just for the downloads.

**Comment by theScrabi** [comment]
We should try to offer the streams that include audio for download.

**Comment by scarfaces** [comment]
Solved. Just changing the default video format at settings to 3GP.

**Comment by TobiGr** [comment]
fixed in #1759
