### ISSUE TITLE
[Feature Request] Add a way to access background player within the app

### ISSUE THREAD

**Issue by uzbezt** [TeamNewPipe/NewPipe#1409]
It would be nice to have a way to access the background player within the app, besides tapping on the notification. Maybe a button on the three dot menu or something.
It would also improve compatibility with android tv.

Thank you

**Comment by theScrabi** [comment]
I want to make NewPipe more responsive for devices like notebooks (android x86), tablets, and TV. Maybe something can be done during the next sprint.

**Comment by newpipeplayer** [comment]
Yes pleeeeeease. It's surprising it's not already a feature!

There should not only be a convenient way to access the player from within the app, but also a whole, background player-foucused side of the app whereby users such as myself can navigate YouTube/SoundCloud and queue songs all getting within the background player!!

Please please please! This is the one major feature holding Newpipe back!

**Comment by berdzena** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1841

**Comment by berdzena** [comment]
I think it is same request ☝️

**Comment by Stypox** [comment]
Closing in favour of #2477
