### ISSUE TITLE
EU GDPR for Sentry and website

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1411]
I know we are not a company, but should we take care about DSGVO for the sentry reports and the webblog?

@TheAssassin Was that what you wrote me about in the mails?

**Comment by TobiGr** [comment]
That is TeamNewPipe/website#72. 
We should also add this to the about page inside NewPipe. Does it suffice to add a link to the online version or do we need to include it as "offline" version under [`src/main/assets`](https://github.com/TeamNewPipe/NewPipe/tree/dev/app/src/main/assets)?

**Comment by TheAssassin** [comment]
For sentry, a link to the privacy policy will suffice. We can assume that every data that is sent to us is sent with so-called "informed consent", as the user is presented the data in their e-mail software, and they send it manually.
However, we should inform about what is being done with the data, and show why the data is anonymized. As said before, I am working on this. I should be done by Monday.

**Comment by theScrabi** [comment]
I know this does not belong here, but I also need somrthing for schabi.org, since there i posted the fingerprint to the key with which i sign NP.

**Comment by TheAssassin** [comment]
@theScrabi what do you think you need there? And why?

**Comment by theScrabi** [comment]
a EU GDPR. Don't you think?

**Comment by TheAssassin** [comment]
@theScrabi EU GDPR stands for European Union General Data Protection Regulation. It's the English translation of the German abbreviation DSGVO (Datenschutzgrundverordnung).

Why would you need a privacy policy because you publish a key's fingerprint? You need to publish a privacy policy when you work with personal data.

**Comment by theScrabi** [comment]
At the c't podcast they said that when you have something business related on your website you might need a  EU GPDR things. My keys are also used for business purpose since I sell apps signed with them. So ... maybe I understand something wrong here, though I want to be on the save side.

**Comment by TheAssassin** [comment]
@theScrabi you're misinterpreting the text totally, I'd say. And the "things" is called _privacy policy_.
