### ISSUE TITLE
NewPipe should remember brightness level

### ISSUE THREAD

**Issue by erenseymen** [TeamNewPipe/NewPipe#1416]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I always keep my phone's brightness at a dimmed level for reading. When I open a video in NewPipe, I increase the brightness level. Is it possible NewPipe to remember this brightness level for the next videos?

**Comment by acrosca** [comment]
UX questions:
You expect NewPipe to remember the brightness for the next video in the current session or keep the setting until you change it again?

Eg. In the evening you watch video A. You set  0% brightness. After A, you play B. And C.  B and C keep the 0% brightness.  You turn screen off/close the app, do something that makes it clear you are not watching. The next day, you expect 0% again?

**Comment by erenseymen** [comment]
I open yuotube videos from another app. Let's say it's Chrome.

1) I click on videoA on Chrome.
>> videoA is opened on NewPipe.
2) I change brightness level.
3) I click back button.
>> I'm back on Chrome. (I guess NewPipe is closed?)
4) Click on videoB
>> videoB opened on NewPipe (I think this is another session now)
EXPECTED: NewPipe remembers brightness level.

There is no problem for me if NewPipe remembers it in the next day. On the other hand, some may not like this so there may be a toggle to enable this behaviour in the options.

**Comment by acrosca** [comment]
Part of release 0.13.5
