### ISSUE TITLE
Download in newpipe fails and  the ui failure in version 0.13.3

### ISSUE THREAD

**Issue by Praveen0899** [TeamNewPipe/NewPipe#1419]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by Praveen0899** [comment]
Unable to open downloads

**Comment by theScrabi** [comment]
fixed by https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.13.4

**Comment by Praveen0899** [comment]
What's duplicate label
