### ISSUE TITLE
Privacy policy link is broken in 0.13.4

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1421]
In the about section, when you press "read privacy policy" you have a 404 error.

**Comment by TobiGr** [comment]
@TheAssassin I linked https://newpipe.schabi.org/legal/privacy/. Did you put it somewhere else?

**Comment by justanidea** [comment]
This link still doesnt work for me. Maybe its because of my device or my country ?

**Comment by TobiGr** [comment]
@justanidea  I made the changes in the app and we discussed the location of the policy in the web. And I linked the page above inside the app. Maybe @TheAssassin put the document to another location.

**Comment by justanidea** [comment]
Okay

**Comment by TheAssassin** [comment]
Guys, relax. This is being worked on. The link is correct. I will put it online as soon as I can.

**Comment by justanidea** [comment]
Okay, thanks for your work !
