### ISSUE TITLE
(Feature Request) Sort 'What's New' page by date instead of the last video each subscription posted

### ISSUE THREAD

**Issue by Darkassassin07** [TeamNewPipe/NewPipe#1424]
When using the normal youtube app, the subscriptions page shows the most recent video any of your subscriptions posted then the second most recent and so on. Personally this is pretty much the only page I use and would really like the option to replicate this functionality in NewPipe.

**Comment by Darkassassin07** [comment]
Would have been nice if you could link the thread I have duplicated....

**Comment by lionirdeadman** [comment]
This : https://github.com/TeamNewPipe/NewPipe/issues/739
