### ISSUE TITLE
Add playing yt playlist from specific clip

### ISSUE THREAD

**Issue by Antinatalist** [TeamNewPipe/NewPipe#1425]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

Thanks in advance

**Comment by theScrabi** [comment]
Please describe your request further.

**Comment by Antinatalist** [comment]
It's possible to import playlist from YT. Then it's possible to play it in the background from song no. 1, then it plays automatically song no. 2, 3, 4 and so on.

I'd glad to have possibility where I import such playlist and start from song no. 43. Now I can choose song 43, but... I can't find way to play song no. 44 automatically. This is my suggestion to add/correct in NewPipe.

**Comment by theScrabi** [comment]
If you select to play the whole playlist in background, and click on the play notification you can select each video/song from that playlist, and after it got played it will switch to the next song. Just like you described.
