### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by GoThrones** [TeamNewPipe/NewPipe#1426]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

(1) Everytime I click on a video on Newpipe, the thumbnail of the video appears and on top of it, a triangle appears. Clicking on the triangle plays the video.

It would have been much better if right after I click on the video (not the triangle on the video), it should start playing. I do not understand, why it waits for the user to click on the triangle for it to start playing. It seems unnecessary.

I request you to remove the dependency of clicking on the triangle for the video to be played. Atleast give user the option to play the video without having to click on the triangle to start playing the video.

(2) When playing the video in landscape mode, if I switch back to portrait mode, the video comes at the center of the screen. It would be a good idea to bring it back to the portrait position where list of other videos is also available below the main video. Also, while the video is playing in the landscape mode, when I press the button next to the headphone sign button, it pops up the video, which doesn't make much sense, as it is not the pop-up button. This is not useful.
A lot of user intuitiveness from the stock youtube app needs to be brought into this app, if it is ever going to be adopted enmasse by the people.

(3) When the video is playing, if I touch the screen once, the pause button appears, and on the right and left of the pause button, there appears a next and previous button. However, the previous button only makes the currently playing video play from the start, it doesn't play the previous video. And more weirdly, the button on the right side of the pause button apparently does nothing, no matter how many it is clicked.

(4) In portrait mode, the list of videos is visible, but in landscape mode, the list does not appear. In the stock youtube app, even in landscape mode, a scrollable list appears at the bottom of the page. It would be better if you could bring this functionality in this player too.

**Comment by theScrabi** [comment]
Please split your request into separate ones, ad check if you have duplicates.

**Comment by GoThrones** [comment]
I've already marked them separately by numbering them. I don't think its very difficult to read ?
Before you post another generic message, please do read what I've written.

**Comment by theScrabi** [comment]
I quickly flow ever them. Some are good, some are duplicates.
The reason for multiple threads is because every feature will have its own discussion, and its own process of development. Also if you have separate issues they are easier to find if someone wants to look if an issue already exists.
I don't want to block you :D
