### ISSUE TITLE
[Improvement] Add  Confirmation dialog box when delete downloaded video 

### ISSUE THREAD

**Issue by southern-dust** [TeamNewPipe/NewPipe#1430]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

I found that my video straightly deleted when I touch on the "delete" button accidentally.
It is so closed for "play" and "delete" button that it may be easily wrong touch.
If so, your video downloaded just now would gone !
For avoid this, please consider adding a 
Confirmation dialog box when user touch "delete" buton, or mv this button another place hard to touch by accident.
Thanks!

**Comment by TobiGr** [comment]
Fixed in #1472 which will be included in the next release.
