### ISSUE TITLE
IDEA support decentral video platforms

### ISSUE THREAD

**Issue by leinadlime** [TeamNewPipe/NewPipe#1435]
I see some mutual long-term benefit opportunity by providing some support or 
easy integration possibilities to these platform (since those users could need a nice client too): 
- PeerTube: https://joinpeertube.org/en/
- MediaGoblin: https://wiki.mediagoblin.org/
- DTube: https://d.tube/

these all are different, so for sure, there must be some thoughts,
which platform architecture can be supported, etc...

**Comment by theScrabi** [comment]
> @theScrabi We once discussed guidelines for new services and how to handle service requests. Maybe we should open one ticket for all requests and with the inclusion criteria and a link to the documentation in the description. Otherwise we'll just get a bunch of duplicates.

Yes you are right. We can put a link to the [inclusion criteria](https://teamnewpipe.github.io/documentation/00_Prepare_everything/#inclusion-criteria-for-services) in the [contribution note](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md). Maybe also in the FAQ what do you thing?

However as you said these guidelines are not final.

**Comment by TobiGr** [comment]
> We can put a link to the inclusion criteria in the contribution note.

That sounds like a good idea.

I once made a [draft](https://github.com/TeamNewPipe/website/issues/50#issuecomment-372109087) for our website which included some information about multi service support. 
For now, I think it is enough to leave a short note in the FAQ, but once we have proper support for at least three services, I am going to put some (better designed) information on the main page.

**Comment by KonoromiHimaries** [comment]
as cdn https://github.com/TeamNewPipe/NewPipe/issues/664#issuecomment-590871075

**Comment by mhmdanas** [comment]
PeerTube is supported now. For DTube, see https://github.com/TeamNewPipe/NewPipeExtractor/issues/420. For MediaGoblin, I found no issue, but if somebody wants it to be added please open an issue in https://github.com/TeamNewPipe/NewPipeExtractor, not in this repo.
