### ISSUE TITLE
[Feature Request] Enhanced subscriptions

### ISSUE THREAD

**Issue by Remelibo** [TeamNewPipe/NewPipe#1437]
[Feature Request] Enhanced subscriptions

Hello. To understand what I would like to see in New Pipe, look at extension for the browser "Youtube Subscription(Collection) Manager". https://chrome.google.com/webstore/detail/youtube-subscriptioncolle/kdmnjgijlmjgmimahnillepgcgeemffb?utm_source=chrome-app-launcher-info-dialog

From the description:
"Using this simple extension, you can create collections that seamlessly fits into the YouTube webpage.

This extension enables you to:
  ★  Create/modify/delete collections list. 
  ★  Group channels to collections. One channel = few collections.
  ★  Add custom icon for collection.
  ★  Show last videos from collections and channel."

I need this so much on my Android device! Please do not ignore it. I think many will say thank you very much for such a functional! Thank you and thanks for NewPipe!

**Comment by selurvedu** [comment]
Bump to prevent closing.

**Comment by Stypox** [comment]
It wouldn't be closed anyway (the stale bot isn't there anymore), and this will be included in #2309
