### ISSUE TITLE
[Feature Request] Share from search results

### ISSUE THREAD

**Issue by tbjorheim** [TeamNewPipe/NewPipe#1438]
Great app! I use it a lot to search for videos to send to my Kodi box (using Yatse via the share options).

But what i miss, is a function to share directly from the search results. Like the original Youtube app, where you can click on the dots after each results, and then select "Share" to bring up the Android share menu.

Would it be possible to add this to NewPipe?

**Comment by theScrabi** [comment]
Yes, we could bury this features in the long tap menu.

**Comment by tbjorheim** [comment]
Thank you for your feedback. Adding this to the long tap menu would be great, and will for me work just as fine as an option with a button, like described above.

**Comment by Somethingweirdhere** [comment]
@tbjorheim Added it, also added a share button to the queues of the background and popup players.

**Comment by tbjorheim** [comment]
Sorry for late feedback, but I would like to say thank you for adding this feature, which works very well. Use it almost every day. Thank you very much!

**Comment by Somethingweirdhere** [comment]
Glad to hear that :)
