### ISSUE TITLE
"What's new" section isn't in chronological order

### ISSUE THREAD

**Issue by Mati20187** [TeamNewPipe/NewPipe#1439]
Hi, is there any way to make videos on "what's new" tab appear in chronological order? It's my biggest and the only problem with this app and it really annoys me when the first video on this tab was posted 2 months ago, next one 16hours ago, third one 1 week ago and so on.

**Comment by theScrabi** [comment]
Thats a problem this is true, and got reported multiple times. Also code got already contributed concerning this toppic. I am going to write an issue about this soon where I summarize my plans.
