### ISSUE TITLE
Feature-Request: Comments comments comments! & Tablet Landscape Fix

### ISSUE THREAD

**Issue by henrykratom** [TeamNewPipe/NewPipe#144]
Hi there, it would be great to be able to read the Video-Comments on the Video-page, it might sound unnecessary but sometimes the Comments themselves are more hilarious/informative than the video-content itself.

Read-only would be more than enough really, no need to implement a possibility to  comment yourself (yet) imo.

And another thing i noticed is that  the landscape view on Tablets such as Nexus 7/9 is totally messed up or at least not optimized for.

Greetings, Henry Kratom

**Comment by chschtsch** [comment]
Please tell me what version you use on the tablet. There was such problem (#120), which is now fixed prior to 7.1.
Please be more specific next time. (Better to create separate issue fo each topic)

**Comment by henrykratom** [comment]
Hello there again, is this https://github.com/theScrabi/NewPipe/issues/120 how it is supposed to look?
If so then i guess it isn't a bug, it just seemed like such a waste of space.

I like the Landscape-View on my Phone better as it seems to be more nicely (not that much empty space)

**Comment by chschtsch** [comment]
Not quiet sure what you mean.

Is this the space you're talking about?
![5a405dd2-a936-11e5-8781-5ca5b43ecc67](https://cloud.githubusercontent.com/assets/6196182/12169087/71ddec1c-b547-11e5-9e67-f3c1327f0dbb.png)

In contrary, it is supposed to use space more reasonably and practically. This fragment shows detail information when you open a video.

**Comment by chschtsch** [comment]
But tell if you think the other way. Or suggest other improvements, as an every day user.
I don't have a tablet, so I'm miss many things.

**Comment by rrooij** [comment]
If comments are deemed necessary, I would like it as an option, as most of the YouTube comments are not worth reading in my opinion.

**Comment by theScrabi** [comment]
1. I guess comments have low priority. At least to me.
2. We have to be careful with what features we add, since we need to stay compatible with other services (one day the are implemented).

**Comment by Stypox** [comment]
Comments were added in #1650
