### ISSUE TITLE
Broken Video Info Layout

### ISSUE THREAD

**Issue by switchtegrax1** [TeamNewPipe/NewPipe#1440]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
If i keep changing videos in newpipe eventually the video description layout will break and go on top of the thumbnail 
 ![](https://i.imgur.com/srCw9I3.png)

**Comment by gkeegan** [comment]
I've seen this too. To add on to the description of it: you can scroll the text and icons up and down and they will show up above the thumbnail.
