### ISSUE TITLE
[Feature request] add hooktube link support

### ISSUE THREAD

**Issue by daufinsyd** [TeamNewPipe/NewPipe#1444]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
Hi, could you add support to open hooktube link just like youtube ones ?
Thank you ;)

**Comment by theScrabi** [comment]
Its there diesnt it work?

**Comment by daufinsyd** [comment]
No, at least Kore isn't in the "open with" app list.

**Comment by daufinsyd** [comment]
Arf, sorry I totally messed up my github tabs, NewPipe works fine :( my bad

**Comment by theScrabi** [comment]
:D happens
