### ISSUE TITLE
Download always crashing on MIUI 8.2 / Android 5.0.2

### ISSUE THREAD

**Issue by Zoldiru** [TeamNewPipe/NewPipe#1446]
Hello there, every time I'm trying to download a video on just even going to the download tab, the app is crashing and there is the report : 

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.13.4",
   "os": "Linux Android 5.0.2 - 21",
   "time": "2018-06-03 09:22",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference\n\tat us.shandian.giga.get.DownloadMission.addListener(DownloadMission.java:235)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:119)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:44)\n\tat android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)\n\tat android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)\n\tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)\n\tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)\n\tat android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)\n\tat android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)\n\tat android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)\n\tat android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)\n\tat android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)\n\tat android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)\n\tat android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)\n\tat android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java)\n\tat android.view.View.layout(View.java)\n\tat android.view.ViewGroup.layout(ViewGroup.java)\n\tat android.view.ViewRootImpl.performLayout(ViewRootImpl.java)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java)\n\tat android.view.Choreographer.doFrame(Choreographer.java)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)\n\tat android.os.Handler.handleCallback(Handler.java)\n\tat android.os.Handler.dispatchMessage(Handler.java)\n\tat android.os.Looper.loop(Looper.java)\n\tat android.app.ActivityThread.main(ActivityThread.java)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:372)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java)\n"
   ],
   "user_comment": ""
}

Any idea ?

**Comment by theScrabi** [comment]
yes. The next version should close this.
