### ISSUE TITLE
Newpipe 0.13.5 does not install

### ISSUE THREAD

**Issue by rmsEfx** [TeamNewPipe/NewPipe#1449]
Newpipe 0.13.5 does not install until 0.13.4 is removed.. All previous versions did installation without old one removing... Android 6.0 LenovoPad TB3-850M

**Comment by rmsEfx** [comment]
I don't remember that moment... If possible, answer on both situations... Possibly, I updated 0.13.3 with Fdroid... And 0.13.3 was installed from github...

**Comment by theScrabi** [comment]
That should not be possible as well, since fdroid and github have a different signature. Try updating via fdorid instead or export your data base, reinstall and import the database.
