### ISSUE TITLE
Is it possible: channels and videos in multiple rows (in subscriptions and videofeeds)? 

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1453]
1

**Comment by theScrabi** [comment]
It should be, we only need to change the adapter.

**Comment by theScrabi** [comment]
This is something we should face.

**Comment by rmsEfx** [comment]
Place channels and videos like downloads in the pics below 
![shot_9](https://user-images.githubusercontent.com/19751507/41113188-2e52d3ec-6aab-11e8-900d-18a82949b6f0.png)

**Comment by Stypox** [comment]
Does grid mode (Settings -> Appearance -> List view mode) solve this issue?

**Comment by opusforlife2** [comment]
Close, account is gone.
