### ISSUE TITLE
Redesign?

### ISSUE THREAD

**Issue by Somethingweirdhere** [TeamNewPipe/NewPipe#1455]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

![image](https://user-images.githubusercontent.com/36226087/40995511-861a7b46-68ff-11e8-9c96-741e307b4613.png)

Right now, we have an options menu and a navigation drawer, which have some features twice. I feel like we can remove the options menu and add all features the the navigation drawer.

Maybe something like this (only a prototype for now)?

![image](https://user-images.githubusercontent.com/36226087/40997053-ba2fd7a6-6903-11e8-95d5-487bdb3ae749.png)

Additionally, I feel like not all people are using the trending section and would prefer to see other things like downloads on the "Home Screen". I have thought about this, and as most the features are fragments, we could easily make the "Home Screen" customizable. For example you could chose to see the history, bookmarks and subscription.

What are you thoughts on this?

**Comment by theScrabi** [comment]
All right sounds like a good idea :D

**Comment by rmsEfx** [comment]
"Trending now" option is the weapon of manipulation... Why can it even exist in non-engage software?

**Comment by justanidea** [comment]
Maybe let us hide the trending icon as we want so we can forget it exist if we want :)

**Comment by rmsEfx** [comment]
If choose "Subscriptions" as main page content, "Trending" dissappears by itself

**Comment by Somethingweirdhere** [comment]
Exactly, it would only be in the side menu, but not on the main page.

What I have been wondering about is the subscriptions: Right now, it shows the channels and you have to press to another button to see the videos. 

Should I leave it this way? Personally I feel like the video feed is the important part, so pressing on subscriptions should lead you there. And above the feed there should be a button to see the channels. Of course we could also make two buttons, "Subscriptions" and "New Videos", but that seems confusing.

So yeah, what do you think? And any other suggestions?

**Comment by justanidea** [comment]
Maybe "channels" for Subcriptions, and "New videos" for new videos

**Comment by Somethingweirdhere** [comment]
Sounds good, but I'm not sure if we need both, or one of those should just be accessible from the other one. Just like history and most watched maybe?

**Comment by Somethingweirdhere** [comment]
#1461 

Alright, the drawer is here. I have kept the options menu for testing reasons, but will remove it later. I feel like accessing all the different sections of NewPipe is more intuitive this way, what do you think? I have also considered that we will add more services, and the UI is ready for that :)

I will now get to work on the tabs.

Two things to think about:

- We might want to get new icons for the New&Hot section and Top 50 section of soundcloud, I'm currently using the Trands icon.
- The navigation doesn't feel right. I guess it's according to android design guidelines, but now the Up button goes back to the main screen. Maybe we should make it work like the back button, or replace it with an X? After all, it closes everything that's open right now.

**Comment by Somethingweirdhere** [comment]
Alright, it technically works. The Main Page is now veeeeeery customizable. There is one issue though: Every time a tab is supposed to be replaced, the fragments need to be replaced. And that's the issue, I can't make it work. Right now you have to restart the app manually if you want the new tabs to load, which isn't optimal.

Also, I'm not sure how to handle Kiosk. The way I think it should work:

You select the kiosks tab, and depending on the service that's selected it will either show the Youtube-Top section, or if Soundcloud is selected it will show a tab with Top 50 and another one with Hot&New.

The other option would be that when chosing the tab you chose the kiosk, and then the service you have selected doesn't matter, it will always be the same kiosk.

**Comment by TobiGr** [comment]
Thanks again!
