### ISSUE TITLE
Bad upload date localization

### ISSUE THREAD

**Issue by kapodamy** [TeamNewPipe/NewPipe#1457]
The upload date field is showing a wrong language (maybe similar to #1215):
How? setting **Default content country** to any non-english language (in my case spanish).

Screenshot of **Trending** showing the _upload date_ in english:
![2018_06_06_20 46 51](https://user-images.githubusercontent.com/16857233/41071016-43cd9052-69cc-11e8-947d-717b853f1920.png)

Search results also too, but in arab:
![2018_06_06_20 48 02](https://user-images.githubusercontent.com/16857233/41071080-96c911b4-69cc-11e8-8b62-54c92c517a64.png)

**Comment by johnnyw3** [comment]
Yes, this also happens with Canada (the dates show in French) even though most of Canada is English.

**Comment by theScrabi** [comment]
Yes the problem is known.

**Comment by kapodamy** [comment]
as i see this belongs to NewPipeExtractor

**Comment by theScrabi** [comment]
I've seen your submission. This week I am a bit busy. I  will take a look at it next weekend.

**Comment by 4ut0-M-4t** [comment]
From my observations I deduced that it may have something to do with your WAN IP address and does not depend on the chosen UI localisation 'cause that data seems to be retrieved "raw" from Google's servers and not generated locally by the app.

**Comment by kapodamy** [comment]
i think this is fixed
