### ISSUE TITLE
Subtitle download support

### ISSUE THREAD

**Issue by gabriellluz** [TeamNewPipe/NewPipe#1460]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Currently, when we download a video, we can't have the subtitles embedded in the video.
So we think we should have an option download subtitles in the same folder as the video or a ZIP file with all the subtitles including the auto-generated subtitles. I know muxing into a MKV might get tricky since NewPipe is for small to big mobile devices and most are really slow so I think downloading subtitles separately in the same folder or all of them in a ZIP would be easier.

**Comment by theScrabi** [comment]
sounds like a cool idea :)

**Comment by MissBastet** [comment]
yesssss I moved on to newpipe when tubemate stopped letting you download copyright videos but I am hard of hearing and I do miss the option of downloading videos with cc. currently you can watch the videos with them but not downlaod them with them :(

**Comment by theScrabi** [comment]
There is a contribution for subtitle downloading open right now. I will take care of it soon.

**Comment by TobiGr** [comment]
Implemented by @kapodamy in #1759
