### ISSUE TITLE
"Sorry, some errors occurred" in videos where the description has a link without 'https:'

### ISSUE THREAD

**Issue by RodolfoCandido** [TeamNewPipe/NewPipe#1464]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

In videos where the description has a link without 'https:' (or 'http:'), the NewPipe shows a message that occurred an error and allow to report this error, which one the log shows that the error was with the extraction (or to locate) of the specific link.

The image below shows a video description with a link that have 'https:'
The video link is https://www.youtube.com/watch?v=rfb3gsDSDCM

<img src="https://user-images.githubusercontent.com/29472542/41185087-2bd8b87e-6b5b-11e8-9e2e-73e542aa2b8a.png"
style="max-width:100%;" width="300">

This one below shows a video description with a link that doesn't have 'https:'
The video link is https://www.youtube.com/watch?v=_xfNmoZ2Lrk

<img src="https://user-images.githubusercontent.com/29472542/41185127-97dd7294-6b5b-11e8-88f0-45e73a7b0ef0.png"
style="max-width:100%;" width="300">

The log shown on report:
[Log.txt](https://github.com/TeamNewPipe/NewPipe/files/2086478/Log.txt)

**Comment by Somethingweirdhere** [comment]
#1399 fixes this
