### ISSUE TITLE
random screen stuttering on android oreo 8.0 on nexus 5X

### ISSUE THREAD

**Issue by Tapmemer** [TeamNewPipe/NewPipe#1469]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

There are random stutters happing over the screen when it updates after closing a fullscreen video, i’m unable to give steps to reproduce this due to the random nature of this glitch nor can i screenshot them correctly. It seems like items that are rendered get displaced for a brief moment to another position.

also when you close a video that was titled when phone is positioned in portrait it will shortly rotate the screen to landscape and then back to portrait. This also sometimes seems to be the cause for the stutters.

p.s the android oreo is enrolled in google’s beta program if this makes any difference.

**Comment by theScrabi** [comment]
> p.s the android oreo is enrolled in google’s beta program if this makes any difference.

Maybe it does. I heard of random drawings on android 8 before, and I've seen video footage of it, but the only thing we could really do is research about it on the internet.
Also you say it only occurs with the video screen? Might be an issue of exoplayer then. Could you check if these glitches happen with older versions of NewPipe eg. v0.12.x
