### ISSUE TITLE
History not kept when using external video player

### ISSUE THREAD

**Issue by kkuhle** [TeamNewPipe/NewPipe#1475]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

This may just not be possible, but it would be nice if there were a way to keep history when using an external video player.

**Comment by theScrabi** [comment]
It should be kept. I thought NewPipe would actually do that already.

**Comment by kkuhle** [comment]
I want to say my history used to be kept with an external video player as I've always used one.  Maybe this has changed with newer versions by mistake or my settings are breaking it?

I'll have to install some older versions to see if history is kept with an external video player.

**Comment by theScrabi** [comment]
> I'll have to install some older versions to see if history is kept with an external video player.

This would help us yes. ... Your settings shouldn't brake this, I guess its might be a regression then.

**Comment by kkuhle** [comment]
I tested and the last version history was kept when using an external video player is 11.6.  Its not keeping it 12.0 beta and above.

**Comment by theScrabi** [comment]
I see thank you for finding that out 👍

**Comment by kkuhle** [comment]
No worries happy to help!
