### ISSUE TITLE
Notifications for subscriptions

### ISSUE THREAD

**Issue by TomJansen** [TeamNewPipe/NewPipe#1476]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It would be nice if NewPipe had some way of notificating the user (push notification?) that a subscribed channel uploaded a new video. This is not that hard to implement (I think) because YouTube already supports RSS for channels. Thank you.

All the best,

Tom

**Comment by theScrabi** [comment]
lats make this part of [this](https://github.com/TeamNewPipe/NewPipe/issues/1448) discussion :)

**Comment by seclution** [comment]
Anyone interested in the feature anymore?
