### ISSUE TITLE
[Feature Request] Audio Only

### ISSUE THREAD

**Issue by ZiTAL** [TeamNewPipe/NewPipe#1478]
There will be awesome an option to request audio only by default, for example in:
Settings -> Video & Audio -> Default video format ->
"no video" or "audio only" option.

Thanks for your awesome job.

**Comment by gkeegan** [comment]
I don't see a reason to add this as there are no extra taps to get audio vs video/audio. Go to the page where the video is and either tap the play button to watch the video, or tap the "Background" button. I don't see a reason to change the default when no time is lost with extra taps the way it is now. This would just add a useless setting in my opinion.

**Comment by theScrabi** [comment]
I aggree to @gkeegan.
