### ISSUE TITLE
Player interface addition

### ISSUE THREAD

**Issue by umunais** [TeamNewPipe/NewPipe#1479]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

Please consider integrating 'fast forward/backward' buttons in background player mode when an entire playlist is loaded in background play option. Only 'next/previous' button is available right now. And 'fast forward/backward' buttons are available only when a single item is loaded in background play.

**Comment by karyogamy** [comment]
Sure, this should be simple to implement for anyone as well:
 - Setup the button UI and listeners for ffw/rewind.
 - Slightly shrink the size of all buttons so they fit on the screen.
 - Follow a similar layout as VLC's control panel.

**Comment by Stypox** [comment]
Closing in favour of #1967
