### ISSUE TITLE
Latest release... 

### ISSUE THREAD

**Issue by rmsEfx** [TeamNewPipe/NewPipe#1480]
Still no luck with rss from github and other sites and applications .. 
So, if any new Newpipe release occurs, please drop the line (hope github subscriptions work well)

**Comment by gkeegan** [comment]
This seems like more of an issue with GitHub for you rather than an issue with Newpipe from my understanding. 

May I ask if you are using the website version or an app to view GitHub?

**Comment by rmsEfx** [comment]
No, you may not

**Comment by gkeegan** [comment]
Alright then so nobody can help you. I was trying to be nice and help find a solution so you don't have to rely on others to tell you when the releases come out.

**Comment by TheAssassin** [comment]
Closing and locking as this is merely an attempt to troll.
