### ISSUE TITLE
"Is it possible" series :). Multiple background player windows, multiple background player windows for an "audio only" and a direct link to an video on Android workspace.

### ISSUE THREAD

**Issue by rmsEfx** [TeamNewPipe/NewPipe#1482]
Is it any possibility of a feature for creating multiple background player windows (BPWs) for different videos respectively at the same time?

Possibility to place "Audio only" in BPW, and create multiple "Audio only" BPWs?

Direct bookmark link to a video and "audio only" on Android workspace, like it possible to do on Windows, Linux and ios workspace?

(picture below is an raw prototype: 5 BPWs [same picture doesn't mean 5 copies of the same video] with video and 2 "audio only" BPWs)

![img_20180614_132754_650](https://user-images.githubusercontent.com/19751507/41396612-b0ce8d22-6fdb-11e8-9187-fe58d4a84340.jpg)

**Comment by rmsEfx** [comment]
Multiple "Audio only" background player windows are good addition enhancement for music.youtube.com support 😊😉👂🏀

**Comment by theScrabi** [comment]
No.
