### ISSUE TITLE
Eliminate duplicates in playlist

### ISSUE THREAD

**Issue by sorab2142** [TeamNewPipe/NewPipe#1483]
Currently it will append all items to existing list. 

If you have a playlist with 5 items
-> Add to Playlist 
-> Select Existing Playlist (which already has the same 5 videos)

**Current Behaviour:**
-> Playlist now has 10 items (i.e. duplicates entries will be appended to it). 
**Expected:**
-> Playlist should only have the current 5 items

It should just overwrite the old list entirely because this button is on the Background Playlist view and not on a single video's detail page.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
So what you are asking is basically to eliminate duplicates am I right?

**Comment by sorab2142** [comment]
That would be a quick fix, yes.

**Comment by shivanju** [comment]
Hi. I'd like to work on this issue. I looked into the code and found the while upserting the streams into playlist we are blindly putting streams to the table... I was thinking of adding a duplicate check there but it will be kinda slow to check entire playlist for every entry that is being added. Instead I was thinking that whether there is something that we can do at DB level e.g. making stream uid as primary key.
Thanks,
Shivanju

**Comment by Stypox** [comment]
The possibility to have duplicate items could be useful. YouTube allows duplicate videos but provides a way to delete all duplicates. So closing in favour of #1473
