### ISSUE TITLE
Add download option when sharing video to newpipe?

### ISSUE THREAD

**Issue by Somethingweirdhere** [TeamNewPipe/NewPipe#1485]
I feel like we could make a new share intent receiver activity for audio and video download, so after setting default downlaod values you could download videos from the youtube app quite easily. Just pressing sharea and selecting Newpipe Audio Downloader. 

And if that's too much, maybe just adding downlaod to the current share intent receiver acitvity would be ok?

**Comment by theScrabi** [comment]
This got requested multiple times now, and I think its a good idea to add a download option to the share receiver activity :)

**Comment by Somethingweirdhere** [comment]
Alright, I will work on it as soon as soon as my other PRs are done!
