### ISSUE TITLE
High memory usage of background service when NewPipe is idle

### ISSUE THREAD

**Issue by chris47368** [TeamNewPipe/NewPipe#1488]
Hey NewPipe team,
This is my last post for this version for now I promise ;)

The other night i was clearing up a couple of startup apps from my phone and unchecked Newpipe from startup to make my ram usage lower(RAM usage at 80-90%).I restarted my phone,Ram usage was really nice and low(65-70%),tried to play newpipe in the background...App Crash every time i started newpipe and tried to play background videos....I found this unusual for NewPipe to be this unstable and I remembered I Disabled newpipe from startup.I re-enabled NewPipe, restarted my phone and NewPipe was stable again but however RAM usage was back to 80-85%.

This made me conclude that the NewPipe Startup Item is some type of background service essential for allowing NewPipe to function, but this service runs in the background using up alot of resources(for me atleast) even if Newpipe is not actually being used.Is it possible you could somehow reduce the amount of resources this service usages while NewPipe is not being used/closed?
 
My phone is A galaxy S4-I9505 2GB RAM if that helps.

Thanks Again!!!

**Comment by opusforlife2** [comment]
@wb9688 Memory leak?

**Comment by Stypox** [comment]
This could be anything, but yeah, probably a memory leak of some sort. Though the kind of report provided by the OP is not so useful, so I think this should be closed until further information is provided @opusforlife2

**Comment by opusforlife2** [comment]
Alright. Closing until @chris47368 replies.
