### ISSUE TITLE
Set color of Navigation bar in the bottom

### ISSUE THREAD

**Issue by RocketJannis** [TeamNewPipe/NewPipe#1494]
My Samsung A8 has got a white bottom navigation bar (this one with back, home and multitab) and its not very nice next to the dark theme of NewPipe

Just set it to black or something like that

Thank you for this software

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
I see. Well help is always welcome :)

**Comment by SpajicM** [comment]
Looked into this for a minute, and seems it can only be correctly handled in Android 8.1+.

While background of navigation bar can be changed (since Lollipop), the color of buttons can only be changed since 8.1 Oreo. If navigation bar is set to black in older versions, you'll get black buttons on black background.

**Comment by marcovr** [comment]
I agree, having a white navigation bar doesn't look very nice, especially with the black theme.

 > Looked into this for a minute, and seems it can only be correctly handled in Android 8.1+.

Then how about applying the color change only for 8.1+ ? For example by having a file `styles.xml` in the `res/values-v27` folder with the following content:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <style name="BlackTheme" parent="DarkTheme">
        <item name="android:windowBackground">@color/black_background_color</item>
        <item name="windowBackground">@color/black_background_color</item>
        <item name="android:navigationBarColor">@android:color/black</item>
        <item name="android:windowLightNavigationBar">false</item>

        <item name="separator_color">@color/black_separator_color</item>
        <item name="contrast_background_color">@color/black_contrast_background_color</item>
    </style>
</resources>
```

I successfully tested this on Emulators running Android 7 and 9 as well as on a Samsung phone running Android 9. Here two screenshots from the phone (before and after the change):

<img src="https://user-images.githubusercontent.com/16596935/63225086-0225d100-c1cd-11e9-9b6e-d4376875e5f6.jpg" width="300"/> <img src="https://user-images.githubusercontent.com/16596935/63225126-6b0d4900-c1cd-11e9-8573-1aafac2fa7f9.jpg" width="300"/>


Now of course this only changes the color for the black theme, but the same could also be done for the dark theme.

**Comment by Stypox** [comment]
@marcovr open a pull request :-D
