### ISSUE TITLE
[Minor Bug] - The number of videos in a playlist is not updated

### ISSUE THREAD

**Issue by andretiagogr** [TeamNewPipe/NewPipe#1495]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Steps to reproduce:**
- Subscribe to a public playlist.
- The creator of the playlist adds a new video to that playlist

**Expected behavior:**
Update the counter when a new video is added

**What happens:**
The counter of videos is not updated. It still shows the number of videos it had when you subscribed to that playlist.

Only the counter doesn't update, If you open the playlist all videos are there.
This bug only happens with public playlists. If the playlist was created by me, it works as expected.

**Comment by theScrabi** [comment]
@karyogamy could you please take a look at this?

**Comment by karyogamy** [comment]
Confirmed. This was actually fixed in #1392 but I guess it got dragged on by the PR. I'll create another PR just for this fix and #1475 in a bit.
