### ISSUE TITLE
Download: Poor handling of the slash character in the video title

### ISSUE THREAD

**Issue by chithanh** [TeamNewPipe/NewPipe#150]
When a video is downloaded which contains a slash character in its title, then a subdirectory will be created with the substring before the slash, and the part after that becomes the filename.
An example of such a video is XzHYt8aK_30

This is not optimal, instead it should be
- escaped like %2F, or
- replaced with an underscore (_) or the replacement character (�, U+FFFD), or
- changed to a different user-specified filename.

There are characters which are homoglyphs to the slash in most fonts (e.g. U+2215), but using them as replacement might not be a good idea.

I haven't checked whether directory traversal is possible with specially crafted video names.

**Comment by theScrabi** [comment]
Yap noticed that.

**Comment by codermess** [comment]
Fixed by b0479d0bd96e894b52176c37428761779075aae4.
