### ISSUE TITLE
Feature requests for Bookmarks

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#1500]
- prevent adding the same video multiple times to one playlist
- editable names for playlists and videos
- searching by words in playlist and video names
- when open video then show playlist names/references that include this video
- folder tree groups for playlists with copy/move function to transfer playlists
- create tags for each video with search function to find videos in playlists by tags

**Comment by theScrabi** [comment]
some of these things you write are duplicates, for the rest please open an additional issue.
