### ISSUE TITLE
show the license and filter by license

### ISSUE THREAD

**Issue by arteteco** [TeamNewPipe/NewPipe#1502]
Hello everyone,

what would you think about showing the license of the videos, maybe under the description, and even be able to only search by license? I know that most people would not care about a video being CC or youtube standard license, but it makes sense to me to highlight the truly free content.

Thanks!

**Comment by theScrabi** [comment]
That is a good idea :)

**Comment by B0pol** [comment]
See https://github.com/TeamNewPipe/NewPipeExtractor/pull/306
