### ISSUE TITLE
Some country names on 'Default content country' were not written correctly

### ISSUE THREAD

**Issue by AndhikaWB** [TeamNewPipe/NewPipe#1504]
The title describes it.
![img_20180622_131413](https://user-images.githubusercontent.com/17119394/41773276-0bbbe024-760b-11e8-8b93-67963a88c74d.png)

**Comment by theScrabi** [comment]
Country names can be found [here](https://github.com/TeamNewPipe/NewPipe/blob/1470fdc0571c17c5dde6f3da08ed21dd581a6534/app/src/main/res/values/settings_keys.xml#L359) help is welcome.

**Comment by AndhikaWB** [comment]
I'm done fixing it, but I'm newbie at pulling request. Which one should I compare?

**Comment by AndhikaWB** [comment]
[Here](https://pastebin.com/REDfEpvX) it is

**Comment by TobiGr** [comment]
@AndhikaWB Do you want to send a pull request or should we fix this?

**Comment by AndhikaWB** [comment]
@TobiGr Unfortunately, I don't know how to pull a request. So.. would you do it?

**Comment by TobiGr** [comment]
@AndhikaWB Sure. But if you'd like to learn how to do a pull request, I'd be happy to show it to you, too.

**Comment by AndhikaWB** [comment]
Sure, actually I'm stuck at "Compare changes" title, I don't know which one to compare. And even if I select a random branch, how do I pull an update request to a specific file? (in this case, I think it should be "settings_keys.xml" file)
![screenshot_1](https://user-images.githubusercontent.com/17119394/47423801-2af95780-d7b0-11e8-948a-0b1250498c2d.png)

**Comment by TobiGr** [comment]
Well, first of all, you need to fork this repository. To do so, click on the Fork button in the upper right corner.

![grafik](https://user-images.githubusercontent.com/17365767/47425273-28840700-d78a-11e8-8829-63d1cb167882.png)

You'll see a dialog, confirm the questions and wait until the fork process has been completed. You should now see your own repository (AndhikaWB/NewPipe). If you do not see it, go to it via your profile > Your repositories > NewPipe (forked from TeamNewPipe/NewPipe). Now, go to the setting_key.xml file: https://github.com/AndhikaWB/NewPipe/blob/dev/app/src/main/res/values/settings_keys.xml
I replaced TeamNewPipe with AndhikaWB. https://github.com/AndhikaWB/NewPipe/ should bring you to your repository as well. If the link to the xml file does not work, please go there by clicking through the folders in the code tab of your fork.
 
Click on the pen to edit the document and do the required changes.

![grafik](https://user-images.githubusercontent.com/17365767/47425645-443bdd00-d78b-11e8-8a7b-f371f532685f.png)

When finished, go to the bottom of the page and commit your changes. Please make sure to create a new branch and write a good commit summary. Commit your changes. It should look similar to this:

![grafik](https://user-images.githubusercontent.com/17365767/47426021-54a08780-d78c-11e8-9776-ef02e5e69ae0.png)

No go back to to the pull request page of **this repository**. You'll notice a yellow banner:

![grafik](https://user-images.githubusercontent.com/17365767/47426447-81a16a00-d78d-11e8-94ad-96f29fa7ab82.png)

Click on **compare & pull request**. Now, you can add more information about your changes if needed. Please also make sure to read our contribution guidelines and agree to them. Once you hit **Create pull request**, you just need to wait for our review 👍 

In case you get stuck somewhere, feel free to ask. Also, please tell me if everything worked the way I told you. If this is the case, I'll add this post to our wiki.

----

**NOTE: you can do this when you have small changes in one file. As soon as you change more code and files, you'll need to clone your repository to your computer using Git, do your changes, commit them, push them to your upstream repository and then create a pull request.**

If you are interested, we can show you how to do this too.

**Comment by TobiGr** [comment]
@AndhikaWB Thanks!
Did everything work or did you have any problems with this description?

**Comment by AndhikaWB** [comment]
@TobiGr Sorry for the very late reply (I only open GitHub to check issues on some apps). Yes, everything look perfect for me. No, you don't have to reply me again.
