### ISSUE TITLE
[enhancement] Background queue : remove with swipe right

### ISSUE THREAD

**Issue by orangemango** [TeamNewPipe/NewPipe#1505]
Hello!

It would be great to be able to remove an item from the background player queue list by swiping to the right.

Thanks <3

**Comment by agarwalakash06** [comment]
Hi @theScrabi ,
I am looking to contribute for this issue and any leads on how to go about it will be helpful.

Thanks,
Akash

**Comment by agarwalakash06** [comment]
Hi
I tried to connect with you in IRC but getting the following error.
[10:59] == Cannot send to nick/channel: #newpipe


Thanks,
Akash

**Comment by TobiGr** [comment]
Fixed in #1915. @agarwalakash06 Thanks again!
