### ISSUE TITLE
Lockscreen player stuck and affected other music players.

### ISSUE THREAD

**Issue by krrbn** [TeamNewPipe/NewPipe#1508]
Don't know why and how but seems that NewPipe doesn't like my Xiaomi Redmi 5. Even uninstalled, it stuck on one specific song from my YT playlist. I tried wiping apps data but nothing. And I don't really want factory reset my phone. 

https://i.imgur.com/rhJBAlo.png

**Comment by theScrabi** [comment]
I hate how xiaomi is basically braking every rule and compatibility with android. You always have to take care about their UI specialties :/

... is your phone android 5+

**Comment by krrbn** [comment]
Yes it is on 7.1.2

**Comment by theScrabi** [comment]
Well I don't want to say no to that fix, but unless we have one of your phones we can't help. And even if we had one someone had to have the time to take care of this.

Help is always welcome :)

**Comment by wb9688** [comment]
@theScrabi: Not only Xiaomi, but Huawei also really likes doing that. I wonder how they come through Google's compatibility test, which is required for GMS (Google Play store and all that stuff).

Have you tried adding it to the whitelist of phone manager (or whatever they're calling it)?

**Comment by theScrabi** [comment]
I heard about that vlc issue. We might somehow want to tell the user to disable optimisation for NewPipe.

**Comment by opusforlife2** [comment]
@krrbn Is this still an issue with 0.20.0?
