### ISSUE TITLE
Implement action buttons (pause/resume & cancel) on download notification

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#151]
![unnamedrttuyduo](https://cloud.githubusercontent.com/assets/6850125/12218460/048b8d42-b720-11e5-9f68-35f107abfb15.png)

**Comment by theScrabi** [comment]
Will come. In february I whant to refactor downloading anway.

**Comment by M2ck** [comment]
Great! It will close #13 too by the way.
I've updated title and added screenshot above.

**Comment by opusforlife2** [comment]
Duplicate of #3332.
