### ISSUE TITLE
Shuffle only shuffles the loaded videos, not the entire playlist

### ISSUE THREAD

**Issue by crkellen** [TeamNewPipe/NewPipe#1511]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I have a large playlist of just under 300 videos I use to listen to music.
In order to get a better shuffle, I must go into the playlist, then scroll down, load the videos, scroll down some more, and continue this process until I reach the first video.

If I don't do that, it wont actually shuffle all the videos, making the actual randomization very low.

**Comment by agarwalakash06** [comment]
This bug is a duplicate of #875
