### ISSUE TITLE
[Feature request] download entire playlists

### ISSUE THREAD

**Issue by gcandrade10** [TeamNewPipe/NewPipe#1512]
- [ √] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ √] I checked if the issue/feature exists in the latest version.
I'm fan of newpipe, I used it to listen music in background, it would be great if a playlist could be downloaded a played offline.
English is not my main language, sorry for typos.

**Comment by MaskedPierrot** [comment]
Was just about to come make this suggestion. It really would be great

**Comment by TobiGr** [comment]
Duplicate of #1058
