### ISSUE TITLE
NewPipe ignores content country settings and auto-translates video titles into my native language

### ISSUE THREAD

**Issue by augbo** [TeamNewPipe/NewPipe#1513]
Greetings!

I couldn't find an answer to this question anywhere, even in here, so I decided to post the issue myself. I downloaded the apk from F-Droid site and installed it, NewPipe was working perfectly for me for a long time, but about 2-3 days ago, I've decided to download the app from the F-Droid app directly, so that it could auto-update through F-Droid app.
After all this, even if I've set the content country to UK or US (I've tried switching between those two), the search showed me the results in my native language and from my country of origin, which is Russia.
So now, even if the content country is set to UK or US, it still shows me the video results from Russia.
Not only that, the app has started to randomly translate video titles into Russian, which is annoying.
**How is it possible?**
NewPipe is not allowed to access my location. Yet it knows, that I'm from Russia.
NewPipe has no way of accessing my YouTube account, so that it would know from Google Location Services my approximate location. Yet it still knows that I'm Russian.

I don't want to browse the russian videos on youtube, nor do I want to see any russian letters in the app itself, since I've set everything to English.

Has anyone stumbled upon this issue? Maybe it's all due to the way I've decided to download the app from F-Droid app, but F-Droid doesn't have any permission to my location either. If anyone knows how can I fix this issue, please, let me know! I love this app and I want to continue using it, but this issue in particular sets me back. 

Thank in advance for your help!

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/pull/91
