### ISSUE TITLE
Preferred action when opening video not working

### ISSUE THREAD

**Issue by RikoDEV** [TeamNewPipe/NewPipe#1514]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I have a problem with the preferred action when opening a video. When you select background playback as the preferred action, the videos open in a standard view.

Android: 6.0
NewPipe: 0.13.5

**Comment by theScrabi** [comment]
weird. Could you backup the database and send me a copy of your settings. ... You  should remove your history in the backup database however.

**Comment by RikoDEV** [comment]
Settings file: 
[newpipe-settings.zip](https://github.com/TeamNewPipe/NewPipe/files/2241878/newpipe-settings.zip)

**Comment by opusforlife2** [comment]
@RikoDEV Is this still an issue in 0.20.0?
