### ISSUE TITLE
Videos that haven’t premiered yet don’t show info

### ISSUE THREAD

**Issue by IvanFon** [TeamNewPipe/NewPipe#1517]
Youtube’s “premiering” videos are broken.

This is what they look like in Youtube:

![Youtube](https://u.teknik.io/yEjSn.png)

In NewPipe, they appear in the subscription feed, but the time until they air is missing:

![NewPipe](https://u.teknik.io/JxGcw.png)

And they give an error when you try to view them:

![NewPipe](https://u.teknik.io/8fJ4b.png)

I think they work fine once the video is actually up, but right now you can’t view info about when it’s premiering or how many people are “waiting”.

**Comment by zaheernathani** [comment]
This issue still exists. Cant mark it as Stale issue.

**Comment by opusforlife2** [comment]
Notice, the label was removed more than a year ago.

**Comment by AudricV** [comment]
> the time until they air is missing

This issue should have been fixed for a long time, as I always seen the time in which YouTube premieres will be released.

For your latest point, I am closing your issue in favor of #5192.
