### ISSUE TITLE
Old video playing when playing new video through intent

### ISSUE THREAD

**Issue by anoadragon453** [TeamNewPipe/NewPipe#1518]
If an old video was playing and you haven't finished it, trying to play a new video in newpipe will simply open up in the old video again, and any intent to play your old video is lost, so you end up having you stop the old video, go back, and reopen the new video again.

Ideally an intent to play a video in the app would cancel any current video and play the new one.

**Comment by Stypox** [comment]
Is this still an issue? I have never encountered it...

**Comment by anoadragon453** [comment]
Oops, I indeed have not experienced this recently at all. You're right to close it :)
