### ISSUE TITLE
Screen in the app to show and download APKs from github releases.

### ISSUE THREAD

**Issue by krtkush** [TeamNewPipe/NewPipe#1520]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Feature request/ idea**

Currently, F-Droid takes too long to update its repo with the latest version of the app. Also, there must be users who don't have/ want F-Droid installed but still want to track the latest version of NewPipe. 

For these users and to counter the slowness of F-Droid APK updates, I suggest that we have an inbuilt system in the app which shows and notifies the availability of the latest APKs. We can use the [Releases API](https://developer.github.com/v3/repos/releases/) to get the latest info from github itself. 

I'm willing to take up this task if the general idea is approved.

**Comment by theScrabi** [comment]
Yum I'm at your side here :)

**Comment by krtkush** [comment]
Great! I'll start working on it, then.

**Comment by TobiGr** [comment]
I am not sure which information you want to get, but you can use the api we created for the website to get the current version: [TeamNewPipe/web-api](https://github.com/TeamNewPipe/web-api)
You can fetch the data from https://newpipe.schabi.org/api/data.json

**Comment by krtkush** [comment]
@TobiGr  The API you mentioned does not provide link to download the APK. 

My idea is to provide a functionality to notify the user about a new APK availability and then let the user download it from within the NewPipe app. I, personally, would like this way of updating the app because I find that F-Froid is not quick enough to make the latest APK available for download. 

`https://api.github.com/repos/TeamNewPipe/NewPipe/releases` gives the `assets_url` which further provides `browser_download_url`. This url can be used to download the APK of that release.

**Comment by TobiGr** [comment]
It's no problem to include it into the web-api. We'd only need to make a difference between F-Droid and GitHub releases. @TheAssassin What do you think about this?

**Comment by krtkush** [comment]
> It's no problem to include it into the web-api.

That sounds good.

**Comment by TheAssassin** [comment]
@TobiGr this should be doable, although I'm a bit worried about the GitHub rate limit. I think we should use some cheap web scraping to get the information we need.

**Comment by TobiGr** [comment]
The rate limit is at 60 requests per hour for non authorized applications. As long as we keep the cache this won't be a problem.

**Comment by TheAssassin** [comment]
This is not the only application I run that uses the GitHub API, @TobiGr...

**Comment by theScrabi** [comment]
> This is not the only application I run that uses the GitHub API, @TobiGr... 

... NewPipe is a scraper ... so maybe, just maybe we could scrape that avalue as well 🙈

**Comment by TobiGr** [comment]
@theScrabi. Jup. I just opened a PR which does the scrapping.

**Comment by TheAssassin** [comment]
It's "scraping", not "scrapping"...

**Comment by TobiGr** [comment]
@krtkush I've updated the API and the changes should be online soon. Tell me when you need additional information which could be provided by the API.

**Comment by TheAssassin** [comment]
Deployment just finished in this

**Comment by TheAssassin** [comment]
@krtkush closing for now, feel free to reopen if you need more assistance.

**Comment by pranavg189** [comment]
@krtkush Are you working on this ?

**Comment by krtkush** [comment]
Yes. Should have a working prototype by end of next weekend.

**Comment by pranavg189** [comment]
Cool. Great to know that.

**Comment by krtkush** [comment]
@TheAssassin In the data api will it possible to get the version_code under the github too? Like we already get under F-droid? 

Comparing version code makes more sense than comparing version names.

**Comment by krtkush** [comment]
@TheAssassin The API seems to be down. 

Getting `<html><title>500: OK</title><body>500: OK</body></html>` as output.

**Comment by TheAssassin** [comment]
Works fine on my end. https://newpipe.schabi.org/api/data.json?json

**Comment by krtkush** [comment]
Yep! It's up now.

**Comment by TobiGr** [comment]
> In the data api will it possible to get the version_code under the github too? Like we already get under F-droid?

Yep. That's possible. I can take a look on this next Friday (just in case you don't want to do it, @theAssassin)

**Comment by TobiGr** [comment]
@krtkush I just merged my changes to display the version code. We just need to wait until the new version will be deployed.

**Comment by krtkush** [comment]
@TobiGr Thank you! How soon will that be?

**Comment by dege1000** [comment]
F-droid works with repositories much like linux, can't you make a one that you can update with more frequency

**Comment by krtkush** [comment]
@TobiGr All the values are coming as -1 under the github object.

**Comment by TobiGr** [comment]
GitHub just renamed some CSS classes :roll_eyes:

**Comment by TobiGr** [comment]
@TheAssassin Thanks

**Comment by krtkush** [comment]
Thanks, guys.
