### ISSUE TITLE
Options when choosing external audio player

### ISSUE THREAD

**Issue by bogdanteleaga** [TeamNewPipe/NewPipe#1526]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Using an external audio player with NewPipe only supports a subset of the audio players installed on the phone. Specifically, I can select GPM and Solid Explorer's Audio player, but I cannot select GMMP, Onkyo Hi-Fi audio player or USB Audio Player Pro. (They do now show up in the list)

**Comment by theScrabi** [comment]
I fear we can't do much since the players have to support streaming.
The only thing you can do is download the music and play it then.
