### ISSUE TITLE
internet interface change, notification area background player appears

### ISSUE THREAD

**Issue by BigGiantHeadsHighCommander** [TeamNewPipe/NewPipe#1527]
Cycle between internet available and not.  This highest position notification player appears.  This also happens when rebuilding tun interface from openvpn connections.  newpipe like many other internets apps on my phone are traffic limited to vpn via iptables.

It does not impair function of the player.  Is this constrained to android kitkat?  This persists over updates easily since april if not longer.

fdroid build

**Comment by theScrabi** [comment]
We need to check, however I noticed that the notification appears much to often, even with other events involved.

**Comment by bleedingcrow** [comment]
#metoo

**Comment by Stypox** [comment]
@bleedingcrow @BigGiantHeadsHighCommander could you check if this is fixed by the APK from #3178 ?
