### ISSUE TITLE
Shuffle feature

### ISSUE THREAD

**Issue by jedokim** [TeamNewPipe/NewPipe#1529]
Hello, I'm not sure if other people have already addressed this but I'd love to see a "shuffle" feature for the playlists that I have made.
Thank you in advance!

**Comment by jedokim** [comment]
forgot to add the tag [feature request]

**Comment by theScrabi** [comment]
The player has a feature for this.

**Comment by Grammost** [comment]
Here's a step-by-step guide on how to do this:
1. Open the Playlist and press "Play all"
2. When you're on the media player interface, press the second symbol from the right in the top
3. The list of videos will appear with two options on the top left corner, one for loop and another for shuffle

I think this issue can be closed.

**Comment by francoism90** [comment]
@Grammost Thanks! I didn't thought shuffle was included.
