### ISSUE TITLE
Add adjustable playback speeds

### ISSUE THREAD

**Issue by tlvince** [TeamNewPipe/NewPipe#153]
Could you add adjustable playback speeds to the bundled media player? For example, -1.5x, 1x, 1.5x, etc.

**Comment by theScrabi** [comment]
We could try once we have exoplayer.

**Comment by mauriciocolli** [comment]
In the issue 26 of ExoPlayer, it's announced that they already implemented it (well, it already works for API 23+, but now it's for all of them) in the `dev` branch.

> Playback rate and pitch adjustments are seamless again as of f7fff0d. The feature is now at the level of our previous (API 23+ only) support, only now across all API levels. Expect a release in the next week or two as mentioned above.

So, I guess, it's an upcoming feature :D (or at least, my little tests with the API 23+ were good, but of course I can't guarantee that will be possible, but I'll try)

**Comment by falematte** [comment]
This feature would be really useful. Also for the audio-only playback.
