### ISSUE TITLE
Auto upgrade Newpipe

### ISSUE THREAD

**Issue by pranavg189** [TeamNewPipe/NewPipe#1531]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [ x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

It would be great if an Newpipe can auto update itself when a new version is released.

**Comment by pranavg189** [comment]
I can volunteer writing code for this functionality If someone is able to given me pointers on how to get started on this.

**Comment by alfasi** [comment]
This truly seems like a feature F-droid should contain instead of each individual app.
At the most NewPipe should notify when a new version is available, but not take the responsibility of upgrading itself IMO.

**Comment by Grammost** [comment]
F-Droid is already able to auto-update your apps, when you flash the OTA package.

**Comment by pranavg189** [comment]
I think atleast it should notify when a new version is available, because all users like me do not use F-Droid. F-Droid seems very slow to me. I can go ahead and implement this notify feature.

**Comment by theScrabi** [comment]
@pranavg189 +1

**Comment by crkellen** [comment]
To remedy this issue, I have a tab open on my phone's browser to the releases page, which I check semi-regularly.

It would be amazing if I could just get updates through the app. I also don't like F-droid due to it taking weeks or more sometimes to update an app.

**Comment by krtkush** [comment]
I'm working on this as mentioned in #1520. Should have a working version by the end of next weekend.

**Comment by stonerl** [comment]
Some of you apparently don't know how F-Droid works. All versions of Newpipe where available within 24 hours after release. If a maintainer doesn't properly tag releases, F-Droid can't properly provide the latest versions of an app.

Back on topic. The release notifications should be opt-in and/or only available in the version available from the GitHub-Downloadpage and not the one from F-Droid IMHO.

**Comment by stonerl** [comment]
Btw. GitHub provides a newsfeef for releases. For Newpipe you just have to add this URL to the RSS-Reader of you liking:

https://github.com/TeamNewPipe/NewPipe/releases.atom

**Comment by krtkush** [comment]
> The release notifications should be opt-in..

Agreed.

As decided in #1520, we'll integrate the https://newpipe.schabi.org/api/data.json API. This will provide the option to download the github or F-droid apk. The RSS option is good but having an option to download from within the app will be convenient.

**Comment by krtkush** [comment]
If the apks on F-Droid and Github are identical I don't think there is way to identify the source of download. Or are they different?

**Comment by theScrabi** [comment]
The signature differs. I don't know if that can be checked. If that does not help a flavour or a buildtype might.

**Comment by stonerl** [comment]
F-Droid builds the apk from the source. Also the signing-key is different afaik. So F-Droid users should never be bothered with this, since they can't upgrade their F-Droid version with the one from GitHub. Furthermore does F-Droid handle the notification and upgrade process.

The entire notification and download of the apk should solely be available for users who decide to manually download the apk.

**Comment by theScrabi** [comment]
> Furthermore does F-Droid handle the notification and upgrade process.

Kind of true, honestly I'd be bothered if two applications are actually notifying me. ... especially because I have privileged extension, and therefore don't even notice when my apps get updated.

**Comment by krtkush** [comment]
Notification only for github apk sounds good. I concur about the logic behind it. 

Things we have decided on, yet -

1. Version update notification inside settings
2. Check the source of the apk (github or F-droid) - Will have to see this can be achieved. 
3. Check for newer version of NewPipe
4. Show notification to download the new apk

Some more suggestions -  

1. We can show a notification on a F-Droid version too if F-Droid is not installed on the device. We can check that by getting the installed app package list. 
2. A one time pop-up on the main activity to take the user to update notification opt-in under settings.
3. A check for update screen accessible from settings. We can place the notification opt-in toggle here and maybe show a changelog too. [Pretty much like LineageOS updates activity](https://imgur.com/a/sy3brdh). For this we'll have to make some changes to https://newpipe.schabi.org/api/data.json

What do you guys think?

**Comment by krtkush** [comment]
I don't think we need any permission. Refer [here](https://stackoverflow.com/questions/2695746/how-to-get-a-list-of-installed-android-applications-and-pick-one-to-run).

However, it can be privacy issue for some; but then the code is open sourced. 

It's a minor thing. We can drop it, though.

**Comment by theScrabi** [comment]
> . A one time pop-up on the main activity to take the user to update notification opt-in under settings.

**Comment by krtkush** [comment]
> I would make this opt in for github users anyway. No pupup needed.

You mean make the user opted-in by default, right?

**Comment by wb9688** [comment]
I'd make a different build flavor that contains the notification for a new
version. Then use that flavor for the GitHub builds and use the normal one
on F-Droid.

Op vr 27 jul. 2018 17:52 schreef Kartikey Kushwaha <notifications@github.com

**Comment by pranavg189** [comment]
@wb9688  Sounds Good.

**Comment by krtkush** [comment]
Update on the feature - 

1. The API has been integrated.
2. Notification has been implemented too.

What is left is a minor change in API as requested in #1520. Once that is done and I include those changes in the app we'll be ready for deployment.

**Comment by TobiGr** [comment]
@theScrabi  from my comment on https://github.com/TeamNewPipe/NewPipe/pull/1608#pullrequestreview-147030435

> My biggest concern about these changes are the additional build flavors. When someone installs NewPipe from F-Droid, he/she will always be forced to use this source to update the application.
Additionally, with this new config every user needs to uninstall the current version of the app. 
Not only for this reason, but also as update notifications can be disturbing from time to time, I suggest to add a setting which handles the update options:
>- Enable / Disable search for new updates
>- Preferred download mirror (applies when F-Droid and GitHub versions are the same, see below).
>
>To identify whether the app is from F-Droid or GitHub we need to check the app's signature. A guide how this can be achieved can be found [here](https://www.airpair.com/android/posts/adding-tampering-detection-to-your-android-app).
>
>IMHO we should come back to one release apk using [F-Droid's reproducible builds feature](https://f-droid.org/en/docs/Reproducible_Builds/).

**Comment by lionirdeadman** [comment]
I personally think we should stick F-droid's apks in the release tab and use this if the user doesn't have F-droid installed : https://gitlab.com/fdroid/update-channels/tree/master/appupdater#f-droid-update-detector
