### ISSUE TITLE
Ability to change default number of threads

### ISSUE THREAD

**Issue by litlmike** [TeamNewPipe/NewPipe#1532]
When you go to download a video, it automatically sets the number of threads to 3.  I would like an option in settings to change the default number of threads.  For me, I always want maximum number of threads, but I understand that maybe not everyone wants that.  It would be great if we could all choose our own number of threads!  Thanks for an amazing app!!!!

**Comment by theScrabi** [comment]
Actually we want to remove the feature to set the number of threads anyway. We consider this a legacy feature of multyget.

**Comment by litlmike** [comment]
Does this mean that'll be the maximum number of threads moving forward?

**Comment by theScrabi** [comment]
Probably not. Gigaget had a buffer size of about 256 byte per thread, we encreased this to I thing around 40Kbyte, therefore reducing overhead. Also I noticed that most phones do best with about 2 maximum 3 threads. This will become a fixed value.

**Comment by gkeegan** [comment]
Yeah I feel like setting a custom number of threads is a good feature to keep. Maybe just putting it in the settings instead of popping up when clicking download?

**Comment by theScrabi** [comment]
Ok, we need to see that. I don't think we are going to change something on that feature so soon, but once we do I will take that into account.

I like the idea to set the amount of the treads globally. However please keep in mind that our Download manager is deprecated, and we where already brainstorming about a new one. So far there is no Multithread feature discuses there. If you want to can a suggestion to that thread: https://github.com/TeamNewPipe/NewPipe/issues/962

**Comment by litlmike** [comment]
I think that is a great idea
