### ISSUE TITLE
[Feature Request] Subscription Searchbars

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#1534]
Two cool features would be to add a searchbar in the Subscriptions tab to be able to find a channel easily and to have a searchbar when viewing a channel to find videos quicker from that channel. I find it annoying to scroll down my subscriptions especially when the channel I want to check out is near the end of my subscription list. Same goes for videos on channels, I know YouTube.com has the ability to search within a channel and this way when you are trying to find a video from a channel you can easily find it instead of using the main searchbar and get tons of results that you are not after.

**Comment by theScrabi** [comment]
I agree. Would be cool yea. First the extractor had to be made compatible with that.

**Comment by pranavg189** [comment]
Would like to work on this. Any pointers to get started ?

**Comment by pranavg189** [comment]
I think we can add a separate searchbar within the subscriptions tab and within the channel view tab. Maybe an option like "Search within subscriptions" or "Search within playlist" can be added in the three dot menu.

**Comment by theScrabi** [comment]
@pranavg189 before working on this we might want to speak about a proper architecture for this in the extractor. Please get used on how the extractor works.
Here is an early documentation of the extractor: https://teamnewpipe.github.io/documentation/01_Concept_of_the_extractor/

**Comment by pranavg189** [comment]
Thanks @theScrabi. Will look into it and discuss about it with you.

**Comment by pranavg189** [comment]
For channel search, TeamNewPipe/NewPipe#49

**Comment by Stypox** [comment]
Closing in favour of #2414
