### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by johntylor** [TeamNewPipe/NewPipe#1537]
![1](https://user-images.githubusercontent.com/35785199/43040486-b07d6124-8d4d-11e8-9223-0cc2f0347eb1.png)
How can I fix this problem?

**Comment by theScrabi** [comment]
Well it did not compile because you have some errors in the code.

**Comment by TobiGr** [comment]
@johntylor Is your problem solved?
