### ISSUE TITLE
Opening via Facebook App; becomes Facebook App until closed.

### ISSUE THREAD

**Issue by a-raccoon** [TeamNewPipe/NewPipe#154]
If clicking a YouTube video link in Facebook app, and selecting NewPipe, the app will hog ones ability to continue browsing Facebook posts while the video buffers.  NewPipe is identified as /being/ Facebook for as long as NewPipe is open, blocking access from app switching via Recents or Home > Facebook.

Something something "intent"?  Not an Android expert here.

**Comment by wb9688** [comment]
That's Android's default behavior, AFAIK that can't be changed... Does it
also happen with the offical YouTuba app?
Op 11 jan. 2016 06:19 schreef "a-raccoon" <notifications@github.com>:

**Comment by a-raccoon** [comment]
I just reinstalled YouTube to test this.

And no.  I can click a YouTube link and open it in YouTube or Chrome or Firefox, and the apps will all open independently of Facebook app, allowing for Recent App Switching between each of the above and continued browsing of Facebook.

Only NewPipe "takes over" Facebook App, preventing continued browsing of Facebook posts until NewPipe is terminated.

**Comment by theScrabi** [comment]
Hm...
