### ISSUE TITLE
Media (player) controls doesn't work for windowed video

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#1542]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
Both in 0.13.5 and 0.13.6.
When the screen is locked media buttons allow control audio-only playback.
But when playing in windowed mode this fictionally misbehaves. Media controls appear but they control inexistent audio playback, not the current windowed playback

**Comment by theScrabi** [comment]
This is a duplicate I think.
We are aware of that issue.

**Comment by ildar** [comment]
Emm, Didn't you ask me to open it?
https://github.com/TeamNewPipe/NewPipe/issues/880#issuecomment-406340783

**Comment by theScrabi** [comment]
Yes I did, you are right. This is not a duplicate.

**Comment by ildar** [comment]
Thanks, fixed
