### ISSUE TITLE
Default audio format explanations are incorrect

### ISSUE THREAD

**Issue by kaoneko** [TeamNewPipe/NewPipe#1543]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

### Issue
_Settings > Video & Audio > Default audio format_ offers two choices, accompanied by an explanation:

> * M4A - better quality
> * WebM - libre format

Since both are container formats that in theory can hold various codecs, how is one per definition better quality than the other?

Now with YouTube (don't know about SoundCloud) the highest quality M4A audio streams for various videos I checked are encoded in 128 kbps AAC. The highest quality WebM audio streams for the same videos are encoded in 160 kbps Opus. The Opus codec already outperforms AAC when both use the same bitrate ([1](https://www.opus-codec.org/comparison/), [2](https://wiki.hydrogenaud.io/index.php?title=Opus#Bitrate_performance), [3](https://en.wikipedia.org/wiki/Opus_%28audio_format%29)), let alone at a higher bitrate.

That's why these explanations in the audio format selection screen have always annoyed my inner audiophile a bit ;)

### Suggested solution
Remove explanations.

**Comment by theScrabi** [comment]
Ok

**Comment by wb9688** [comment]
Yeah, btw there are also WebM's containing Vorbis, but I'm not sure if that's implemented at NewPipeExtractor. I'd just remove that option and automatically decide what's the best, however not all phones support Opus. SoundCloud always uses 128 kb/s MP3.
