### ISSUE TITLE
[Feature] Support For Existing Playlists

### ISSUE THREAD

**Issue by RuthlessRuler** [TeamNewPipe/NewPipe#1546]
When I Open a playlist link in a browser and then select NewPipe to perform the action, only the video is retained, the playlist is gone.
So it would be nice if this feature is added to the app!

**Comment by theScrabi** [comment]
Can you send a link pls.

**Comment by RuthlessRuler** [comment]
Like This:  https://www.youtube.com/watch?v=aJOTlE1K90k&index=2&list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG, would only play the the current video and everything in that pllist in not loaded in next video!

**Comment by theScrabi** [comment]
I see. A PR for this is already on the way: https://github.com/TeamNewPipe/NewPipeExtractor/pull/97
