### ISSUE TITLE
Does not open such kind of links

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#1548]
https://www.youtube.com/embed/videoseries?list=PLxKWAamP3x0FfJmDtzOoUvz56bLx3_4us

**Comment by theScrabi** [comment]
All right, so the parts in the code where this is handled is here:
https://github.com/TeamNewPipe/NewPipe/blob/84cb3a10603e0191d80674a5f5e686539fcd04e2/app/src/main/AndroidManifest.xml#L144

and here:
https://github.com/TeamNewPipe/NewPipeExtractor/blob/dcca11fbebb6c4c83b2f320613b152a29252b109/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java#L40

Help is welcome.
