### ISSUE TITLE
Preload queue for offline viewing

### ISSUE THREAD

**Issue by a-raccoon** [TeamNewPipe/NewPipe#155]
Having a queue where videos are buffered completely and then played anytime (even offline) would help people who have an oscillating internet connection, letting them load as much content as they can when the internet is up and just viewing what has already been buffered if the internet is down

**Comment by a-raccoon** [comment]
If possible, detect if TCP sessions time out frequently and adjust for more aggressive timeout and reconnect values. Ie, on really poor and congested wifi/mesh networks.  Instead of the defacto 120 second timeout, switch to a 4 second timeout to reconnect?

**Comment by theScrabi** [comment]
When I'm about to re implement I want to display the downloaded videos in NewPipe. That may help. For now your only option is to just download the videos as they are.

**Comment by Stypox** [comment]
So closing this as a too-niche feature in favour of #478

**Comment by Stypox** [comment]
The queue for offline viewing part is original though, sorry ;-)

**Comment by litetex** [comment]
Is this still relevant?
#478 got closed - see https://github.com/TeamNewPipe/NewPipe/issues/478#issuecomment-960959193
