### ISSUE TITLE
Opus 160kbs download broken?

### ISSUE THREAD

**Issue by Krawei** [TeamNewPipe/NewPipe#1553]
When I'm trying to download a video's sound track in a opus 160kbs-file, the sound output doesn't work.

Lower bitrates with 70 or 50 kbs work.

See this viseo for example: https://www.youtube.com/watch?v=AJm8PeWkiEU

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/pull/96
