### ISSUE TITLE
Nocookie domain of Youtube

### ISSUE THREAD

**Issue by ale5000-git** [TeamNewPipe/NewPipe#1555]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi,
I wonder if anyone has thought of using the official nocookie domain instead of the base one.

Example: https://www.youtube-nocookie.com/embed/9ij9qf-oAwA

**Comment by theScrabi** [comment]
What would be the advantage of it?

We could add support for such links though.

**Comment by ale5000-git** [comment]
It has no cookie and the page is smaller; so more privacy and faster parsing.

**Comment by theScrabi** [comment]
> It has no cookie and the page is smaller; so more privacy and faster parsing.

That's no issue for us :D we don't use cookies anyway, and we only try to get the data we really need.

**Comment by ale5000-git** [comment]
Any update about support for these links?

**Comment by theScrabi** [comment]
No support for adding no cookiedomain is still open.

**Comment by B0pol** [comment]
It's supported now
Try those links
https://www.youtube-nocookie.com/embed/9ij9qf-oAwA
https://www.youtube-nocookie.com/embed/-cdveCh1kQk
etc

The issue should be closed

**Comment by danwdart** [comment]
This seems not to use them as sharing urls, or is that a different ticket?
