### ISSUE TITLE
no download button

### ISSUE THREAD

**Issue by mouarfff** [TeamNewPipe/NewPipe#1557]
Hello,

I posted somes months ago about download button disapear but you closed my repport, now i 'm using 0.9.4 version because i have the same problem since this time ...

I was on oukitel K 6000 pro and now homtom ht70

**Comment by mouarfff** [comment]
I'm using f-droid since 2011 and i'm pro "GNU/GPL"

It's not the first time i ask for this problem and nobody seem believe me ...

I re-re-re-explain :/

After update, i've almost the same interface but there no download button, only ways to change resolution, sharing button and three dot icon for options, nothing elese.

My phone is the homtom ht70 with android 7.0 (kernel 3.18.35), but i had this problem with oukitel k6000pro

Without this probleme, the app seem to bee the same. but no because I HAVEN'T GOT THE DOWNLOAD BUTTON :)
so i had to downgrade to very old version to have it, and i hope youtube will not change more for the time you to debug this...

If you want more information tell me, 'im ok to help us...

**Comment by wb9688** [comment]
Can you show a screenshot? It definitely is there on my phone:

![Screenshot](https://user-images.githubusercontent.com/9780201/43357911-81200170-9289-11e8-9d07-732dcf2847df.png)

**Comment by mouarfff** [comment]
Okay okay ...

But i don't understand why it seem usefull to change this to another place ... It's more ergonomic to have a big button above in the ui but having it into the page ....

Now i need to wait loading and if i'm in landscape mode i need to scroll the screen ...

The sharing button and video mode didn't change his place, why download button change ?

I wanted (as soft power mode) to discouraging downloading ?

.....

**Comment by theScrabi** [comment]
I think that the download button fits better at the place where it is now.
