### ISSUE TITLE
[Bug] the videos are locked at a certain moment

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#1559]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I am using Android Oreo (Dirty Unicorn ROM) in a Moto G5 Plus for several weeks now I can see that the videos are locked in a certain time even when they are in the background or in pop-up mode. sometimes I suspect that it is related to the use of a Magisk module that serves to define a specific DNS. but I only have problems in Newpipe. I found that the only way to fix it temporarily is by changing the video mode (for example, from background to pop-up mode and then back to the background) until the problem repeats itself... now it's getting a little more annoying 🤪

**Comment by theScrabi** [comment]
It soulds like an optimisation issue. Could you disable battery optimisation for NewPipe?

**Comment by speednroll** [comment]
I haven't tried it, I will try it and I'll tell you how it went 😅

**Comment by speednroll** [comment]
This problem was solved. I forgot to close it.
