### ISSUE TITLE
Improve quality

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1566]
NewPipe got quite bugy recently. Which is also my fault, since I released to early. The problem I'm seeing here is that we/I did take to much care about features but to less about bugs and maintaining. We have to take more care about QA. I think it was a good Idea if we wrote some sort of QA plan, which some of us anticipate. 

For now, and the near future I would also focuse more on bugfixing and readability than on adding more features. Remember features need to be maintained, the more we add the more work we have !!!

So here are some bugs which are importand and which we should take care of:
- [x] Cyclic search result https://github.com/TeamNewPipe/NewPipe/issues/1562
- [x] Seek bar not statically lay outed: 
![asdf](https://user-images.githubusercontent.com/1891273/43455001-de1c05e0-94be-11e8-9e27-a4a293e74837.gif)
- [x] YT Premium video are not blocked correctly
![screenshot_20180804-131600](https://user-images.githubusercontent.com/1891273/43684840-d6ac9256-98a7-11e8-8829-0de5d6c397d8.png)
- [x] Videos sometimes not loading (need to be checked)
- [x] Fix links in video description
- [ ] Make player UI appear instantly when clicking the background player.
- [x] Show warning when someone tries to download to external sdcard
- [x] nothing found exception should not trigger error report
- [x] thumbnail not shown in background player for android 8.1 [see here](https://github.com/TeamNewPipe/NewPipe/issues/943)

**Comment by wb9688** [comment]
I think we should create a list on the wiki with things to check before releasing it.

**Comment by theScrabi** [comment]
Btw guys help is wellcome.
