### ISSUE TITLE
[Feature Request] Show video thumbnail on lock screen

### ISSUE THREAD

**Issue by heyseth** [TeamNewPipe/NewPipe#1570]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

It would be really cool if - when background music is playing - NewPipe would show the thumbnail of the video on the lockscreen. Many music players do this with album artwork. Here's what I mean:

<img src="https://preview.ibb.co/df7LRK/screenshot.png" alt="drawing" width="300px"/>

**Comment by theScrabi** [comment]
![screenshot_20180803-145639](https://user-images.githubusercontent.com/1891273/43644081-ba9b4466-972d-11e8-9626-aa2889bfdbf6.png)

**Comment by heyseth** [comment]
I think you misunderstood what I meant, my bad for not explaining better. 😅

What I would like to see is the entire wallpaper background change to match the video thumbnail. (notice in my screenshot how the wallpaper is the same as the icon displayed?)

**Comment by theScrabi** [comment]
Aaah si :D yea that be cool. :)
