### ISSUE TITLE
[Feature Request] adding more gesture

### ISSUE THREAD

**Issue by dharmendra1111** [TeamNewPipe/NewPipe#1577]
It would be very useful to have "seek video poison" by gesture, like we already have for volume and brightness control, because seeking few frames forward or backward from bar is difficult, also on some devices the seek bar is covered by onscreen navigation buttons.

**Comment by theScrabi** [comment]
You can double tab in oder to seek ten seconds forward and backwards, like on the yt app.

**Comment by xzyone** [comment]
> You can double tab in the direction u want in oder to seek ten seconds forward and backwards, like on the yt app.

Could the app allow people to customize the time forward and backwards, like 5, 10, 20 secounds.
