### ISSUE TITLE
Can't find background player anywhere

### ISSUE THREAD

**Issue by TurtleInTheSky** [TeamNewPipe/NewPipe#1584]
I'm stuck and can't make newpipe work. The problem is, I can't find the background player. Its not in running apps, no visible sign of it, nothing in the notifications list, but it's playing a download. Have to restart to stop it. I can start and stop NewPipe app without any access, sign of background player.  Using stock Samsung S5. Android 6.0.1.    I removed 13.5, installed 13.7, and found ... I think it's the background player on... my notifications list. I thought it was fixed. But cancelling it, went back to being unfindable. Like, exactly where would I find the background player from the newpipe app?

**Comment by theScrabi** [comment]
The button is the one with the headphones below the video thumbnail.
![](https://github.com/TeamNewPipe/NewPipe/blob/dev/fastlane/metadata/android/en-US/images/phoneScreenshots/shot_6.png)

**Comment by theScrabi** [comment]
If nithing happens if you click there it could be that the app is battery optimized. You need to disable this for newpipe.

**Comment by TurtleInTheSky** [comment]
I'm mainly wanting to play downloads, offline. It seems the YT vids downloaded audio only are using some other player that's... idk, invisible. When I start the background player with the headphones from video thumbnail list, it plays, it's in the notifications, as expected. But if I next play an YT audio download, it doesn't show up on the background player but it plays. There's no running app that I can see. Even if I "End all" of them, it continues until I reboot. 

In settings, I have video:Use external player: OFF. 
audio: Use external player: OFF. 
In fact, all the video&audio options under settings are off.

I downloaded a YT as video, and it's playing using VLC, not the background player. So that's the problem. It's not using the background player, and for audio, the audio player used has no visible interface or controls except reboot to stop.

**Comment by TurtleInTheSky** [comment]
I cleared the default app settings for VLC and now if I try to play a downloaded video, it asks "OPen with VLC, Video Player, QuickPic"? Similar for downloaded audio. No background player in there.

**Comment by theScrabi** [comment]
I think the problem is that newpipe cant play downloaded videos/audio
