### ISSUE TITLE
NewPipe, I get audio, but no video?

### ISSUE THREAD

**Issue by Sarah-Jaina** [TeamNewPipe/NewPipe#1585]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by oktober29** [comment]
me too have this issue (1.15.1).
Any news?
