### ISSUE TITLE
[bug] Links in description of video don't work.

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#1586]
Links if they are long (or even not long) in description of a video don't work.

**Comment by teod0r** [comment]
By the way, when you will add posibility to paste links for opening a video and adding urls to copy\paste buffer?

**Comment by TobiGr** [comment]
Duplicate of #1390

Pasting links into the search field is possible. Btw you can share a video with NewPipe and it will directly open it.
