### ISSUE TITLE
"More options" popup is not translatable

### ISSUE THREAD

**Issue by bboa** [TeamNewPipe/NewPipe#1587]
Dear friends, can I ask you to add required string to resource files.

It's a popup message that displayed when longpress 3-points button in ActionBar.

**Comment by theScrabi** [comment]
:D of course you can :D. Help is welcome.

**Comment by bboa** [comment]
.. looking for a Java teacher )

**Comment by pExeen** [comment]
You don't have to learn Java, the translations are done [here](https://hosted.weblate.org/engage/NewPipe/).

**Comment by bboa** [comment]
probably this string located somewhere here - 

https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/layout/activity_main_player.xml#L235

but will be fine to obtain it here) https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values/strings.xml

**Comment by bboa** [comment]
Looks like now this string is localized, thanks for changes.
