### ISSUE TITLE
Plurals problem in Russian

### ISSUE THREAD

**Issue by bboa** [TeamNewPipe/NewPipe#1588]
Dear friends, last build have some plurals problems: https://imgur.com/a/m0VryaY

Explanation for screenshot:

str. 2 "6 тыс. подписчика" - expected "many", current "few",
str. 4 "56 тыс. подписчик" - expected "many", current "one".

As I see, the plurals section in strings.xml are correct. How we can help to fix this?

**Comment by theScrabi** [comment]
You could take a look at our weblate.org translation page. Maybe the plurals are wrong there. Also app/src/res/values/strings-ru.xml could help you.

**Comment by bboa** [comment]
hmm, I just check Weblate template and he is also correct, so probably it's a more wide problem, maybe other languages affected too.

I can bypass this by shortening words in translation, but not sure that it's a good idea.

**Comment by bboa** [comment]
Hey! Now I understand.

We have two different view counters.
The one is placed on video details screen, under big thumbnail. It always contains an exact views value, e. g. "194,541 views" and works correctly.

The other is placed on videos list, on right side from little video thumbnails. This counter works dinamically, and here is a problem. If views count is less than 1000, this counter displays exact views count, e.g. "741 views", and all work perfectly too.

But, if views count is more than 999, this counter displays approximate value, e.g. 1K, 2M, 127K etc. And, here is a problem: if we have 194,541 views, in Russian, because last digit is 1, here will be used word form, equal to English "view", not "wiews". But this second counter will be displayed as "194K view", is a English translated eqivalent. Same problem will be reproduced, if exact views count will have last digits as 1, 2, 3, 4, e. g. in 40% cases, for Russian UI.

Looks like for second counter we need to add additional checking to fix non-English UI behaviour, if views count is more than 999 and contains approximated value, then plurals word form (like "views") will be always used, I hope that it's right for all languages.
