### ISSUE TITLE
No audio in most download options since a long time

### ISSUE THREAD

**Issue by TheRealMarnes** [TeamNewPipe/NewPipe#1589]
![43776630-b967b46e-9a50-11e8-90a6-ee55b455b032](https://user-images.githubusercontent.com/1891273/44946341-e5955b00-adfa-11e8-9268-f122b0eb827e.png) ![43776633-bafd4852-9a50-11e8-8baa-ca9bf47378d3](https://user-images.githubusercontent.com/1891273/44946342-e5955b00-adfa-11e8-923e-d9d50317423d.png)

How come there are so few working options? Does it depend on the video itself? LastWeekTonight is a big channel so I can't imagine google skimping on the formats. Is it a problem in newpipe? If it is, how come it's been here so long and I don't see much fuss about it?

Newpipe isn't still beta software with "baseline usable" status, is it? I thought it had become quite big and widely popular already, so it seems strange that such a fundamental problem exists in it for a while.

**Comment by TheRealMarnes** [comment]
FYI "use external player" is disabled. Of course, I'm downloading to a file in this usecase, which I think has the same effect. From another thread I gather that this is caused by a lacking ability to mux video and audio streams? So I take it that newpipe itself can perfectly play all these combinations, and there's only a problem with audio when downloading to a file/using an external player?

**Comment by theScrabi** [comment]
Correct. We spoke about muxing and transcoding using jcodec, but so far this is more or less a discussion.

However it might be that YT lately switches more and more to the video or audio only solution. We may need to se if we can bypass this because we hide streams in certain cases.

**Comment by Riotous** [comment]
@theScrabi There shouldn't be any need to transcode. Muxing to mp4 is all you need to do because pretty much any player can play the resulting file.

**Comment by FaizKhan5** [comment]
when this problem solves ?

**Comment by beskhu3epnm** [comment]
- How long until a video-audio muxing feature will be incorporated into NewPipe? The inability to download 1080p 60fps video or higher with audio synchronized is the only thing preventing me from using it as my primary YT downloader.

**Comment by TobiGr** [comment]
This is going to be fixed in #1759. No need to use video transcoder.
