### ISSUE TITLE
Please support downloading direct URLs

### ISSUE THREAD

**Issue by aelmahmoudy** [TeamNewPipe/NewPipe#1590]
Please support downloading direct URLs, sometimes I have a direct link (https://site.com/path/to/file.mp4) to a file, and I need to use a reliable download software to get it (Android download utility isn't so reliable).
NewPipe has a download manager (seems to be based on GigaGet which is notmaintained, and doesn't work with recent Android versions) which is reliable, the problem is that I can't manually add a direct link to it.
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment]
We want to abandon gigaget. Also simple download is not quite our duty. Pls find a different download manager :)
