### ISSUE TITLE
Weblate commits went full retart

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1592]
If you look into our commit history you will see that it got a mess, because it seems that every single change of line results in a commit there.

More that 50% of all our commits are basically weblate commits. I locked down the dev branch a few days ago which resulted in weblate not being able to push anything anymore. So now I get a daily mail that rebase failed. Rebasing by hand results in 120 new commits. You can not properly squash them because they do rebase, and our commits are somewhere in between.

Maybe I'm doing something wrong here. I need help because I don't want to merge this mess. 

You can find the git repo under https://hosted.weblate.org/git/newpipe/strings/

**Comment by TobiGr** [comment]
I suggest to do this the way it is done for F-Droid: before each release all weblate changes are squashed and merged. This keeps the commit history clean and also helps to find bugs in translation files easier.
In case we do not want to squash them, we should definitely rebase them on top of our master/dev branch to keep the history clean.

I didn't dig into it yet, but for me it looks like weblate only syncs their sources when a merge was done. I hope there is another way to trigger a refresh of the resources.

>  You can find the git repo under https://hosted.weblate.org/git/newpipe/strings/

I guess the access to the git repo is restricted. At least I get redirected to https://hosted.weblate.org/projects/newpipe/strings/. Btw. which git command did you use for this?

**Comment by bboa** [comment]
Dear friends, I only want ask you to merge recent Weblate updates before new release.

**Comment by theScrabi** [comment]
>  Btw. which git command did you use for this?

I guess I did a rebase.
