### ISSUE TITLE
Proxy socks5 

### ISSUE THREAD

**Issue by unknowtech** [TeamNewPipe/NewPipe#1593]
Hi need feature use proxy for conection 

thank you

**Comment by theScrabi** [comment]
I recomend using a socks proxy app that woks on android lika a VPN: https://github.com/shadowsocks/shadowsocks-android/releases

**Comment by peylight** [comment]
I think it would be nice if you add socks5 proxy.
Actually shadowsocks and many VPN's work with two options:

1.The whole android applications will be through VPN.
2.Proxy mode that you can add to that application settings.

So many applications have proxy settings like Telegram...
