### ISSUE TITLE
Janky video quality selector

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1599]
Whenever i tap to change quality inside a video the dialog displaying the avaliable resolutions stutters horribly to open,ill attach a gfxinfo log here if it helps fixing it and to give an idea how badly it stutters 

Edit:the stutter is less noticieable when the video is paused but still noticeable,so i assume some of the problem is just my device being slow

Applications Graphics Acceleration Info:
Uptime: 2942080 Realtime: 2942080

** Graphics info for pid 6205 [org.schabi.newpipe] **

Stats since: 776367239395ns
Total frames rendered: 25063
Janky frames: 3081 (12.29%)
50th percentile: 9ms
90th percentile: 19ms
95th percentile: 23ms
99th percentile: 36ms
Number Missed Vsync: 131
Number High input latency: 50
Number Slow UI thread: 881
Number Slow bitmap uploads: 223
Number Slow issue draw commands: 2438
HISTOGRAM: 5ms=935 6ms=491 7ms=1483 8ms=6062 9ms=8021 10ms=2609 11ms=923 12ms=577 13ms=383 14ms=189 15ms=189 16ms=172 17ms=229 18ms=276 19ms=322 20ms=305 21ms=262 22ms=212 23ms=220 24ms=160 25ms=144 26ms=120 27ms=103 28ms=85 29ms=79 30ms=72 31ms=50 32ms=70 34ms=59 36ms=52 38ms=47 40ms=23 42ms=21 44ms=14 46ms=12 48ms=14 53ms=10 57ms=9 61ms=9 65ms=4 69ms=10 73ms=2 77ms=4 81ms=3 85ms=4 89ms=2 93ms=4 97ms=0 101ms=2 105ms=1 109ms=1 113ms=0 117ms=0 121ms=0 125ms=0 129ms=3 133ms=0 150ms=8 200ms=0 250ms=1 300ms=1 350ms=0 400ms=0 450ms=0 500ms=0 550ms=0 600ms=0 650ms=0 700ms=0 750ms=0 800ms=0 850ms=0 900ms=0 950ms=0 1000ms=0 1050ms=0 1100ms=0 1150ms=0 1200ms=0 1250ms=0 1300ms=0 1350ms=0 1400ms=0 1450ms=0 1500ms=0 1550ms=0 1600ms=0 1650ms=0 1700ms=0 1750ms=0 1800ms=0 1850ms=0 1900ms=0 1950ms=0 2000ms=0 2050ms=0 2100ms=0 2150ms=0 2200ms=0 2250ms=0 2300ms=0 2350ms=0 2400ms=0 2450ms=0 2500ms=0 2550ms=0 2600ms=0 2650ms=0 2700ms=0 2750ms=0 2800ms=0 2850ms=0 2900ms=0 2950ms=0 3000ms=0 3050ms=0 3100ms=0 3150ms=0 3200ms=0 3250ms=0 3300ms=0 3350ms=0 3400ms=0 3450ms=0 3500ms=0 3550ms=0 3600ms=0 3650ms=0 3700ms=0 3750ms=0 3800ms=0 3850ms=0 3900ms=0 3950ms=0 4000ms=0 4050ms=0 4100ms=0 4150ms=0 4200ms=0 4250ms=0 4300ms=0 4350ms=0 4400ms=0 4450ms=0 4500ms=0 4550ms=0 4600ms=0 4650ms=0 4700ms=0 4750ms=0 4800ms=0 4850ms=0 4900ms=0 4950ms=0
Caches:
Current memory usage / total memory usage (bytes):
  TextureCache            34584 /  9216000
  Layers total          0 (numLayers = 0)
  RenderBufferCache           0 /   768000
  GradientCache               0 /  1048576
  PathCache                   0 /  1536000
  TessellationCache           0 /  1048576
  TextDropShadowCache         0 /   768000
  PatchCache                  0 /   131072
  FontRenderer A8         93767 /   409600
    A8   texture 0        93767 /   409600
  FontRenderer RGBA       26236 /  1638400
    RGBA texture 0        26236 /  1638400
  FontRenderer total     120003 /  2048000
Other:
  FboCache                    0 /        0
Total memory usage:
  2082584 bytes, 1.99 MB

Pipeline=FrameBuilder
Profile data in ms:

        org.schabi.newpipe/org.schabi.newpipe.MainActivity/android.view.ViewRootImpl@698ed1e (visibility=8)
        org.schabi.newpipe/org.schabi.newpipe.player.MainVideoPlayer/android.view.ViewRootImpl@a9049ff (visibility=8)
View hierarchy:

  org.schabi.newpipe/org.schabi.newpipe.MainActivity/android.view.ViewRootImpl@698ed1e
  145 views, 114,41 kB of display lists

  org.schabi.newpipe/org.schabi.newpipe.player.MainVideoPlayer/android.view.ViewRootImpl@a9049ff
  52 views, 41,03 kB of display lists

Total ViewRootImpl: 2
Total Views:        197
Total DisplayList:  155,45 kB

**Comment by theScrabi** [comment]
Could you give us some device infirmation, and possible avideo of this happening

**Comment by opusforlife2** [comment]
@DanGLES3 Still an issue in 0.20.0?
