### ISSUE TITLE
Error when play video

### ISSUE THREAD

**Issue by Brimont** [TeamNewPipe/NewPipe#1600]
Hi on my phone the 1080p and other format does not work well when play video or live.

Video format error
MPEG-4 (1080p) player error, no video no audio
MPEG-4 (1440p,2160p) no video only audio
WebM(1080p,720p,480p,240p,144p,1440p,2160p)  no video only audio
3GP (1080p,480p)  no video only audio

my phone specific
-Android 4.2.1
-Ram 1GB
-CPU Mediatek MT6589 1,21GHz
-Core 4
-Architecture 4xARM Cortex-A7 @1,21GHz
-GPU renderer PowerVR SGX 544MP

Test: i have use external player and 1080p and other format. All video Work from Video format error but no audio
screen mxplayer https://image.prntscr.com/image/h9ymRMMhSUGY5qpP4SKIqQ.jpg
screen NewPipe https://image.prntscr.com/image/NHCBTPhXSIaIW0tHPzBcVA.png

thanks at all for help

**Comment by opusforlife2** [comment]
@Brimont Still a problem in 0.20.0?
