### ISSUE TITLE
EMUI 5.1: issue with notification bar on tablets

### ISSUE THREAD

**Issue by impreza233** [TeamNewPipe/NewPipe#1602]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
Since the latest update of NewPipe (0.13.7) i reproduce this issue (steps below):

1-Play any video in background
2-Pull down the notification bar one time
3-You obtain this:
![screenshot_20180814-184925](https://user-images.githubusercontent.com/25793051/44105885-584cc07c-9ff3-11e8-96f4-9aeaef962216.png)

I'm on a tablet Huawei MediaPad T3 10", on EMUI 5.1.2 and Android 7.0.

**Comment by theScrabi** [comment]
Does the audio continue playing?

**Comment by impreza233** [comment]
Yes, the audio continues playing as usual.

**Comment by impreza233** [comment]
Well, I'm aware that it will be a new version of EMUI firmware on my
MediaPad (B271). When it arrives I will retest it and I will provide
feedback.

Rubén Abad

**Comment by impreza233** [comment]
This issue is solved with firmware version B271. I can close this problem.
