### ISSUE TITLE
[settings/options] Override rotation lock when playing video

### ISSUE THREAD

**Issue by h3298** [TeamNewPipe/NewPipe#1610]
Create a toggle switch in **Settings** menu that presents video in **landscape** mode even if rotation lock is on **portrait** mode.

**Comment by theScrabi** [comment]
I think this demand is a little bit to specific.

**Comment by h3298** [comment]
Other video player apps have implemented this feature =(

**Comment by gkeegan** [comment]
I think an setting for default playback orientation would be best here. Like setting  "Landscape", "Portrait", and "Follow System" for every video.
