### ISSUE TITLE
Can't import .zip backup on 0.13.7

### ISSUE THREAD

**Issue by tlg98** [TeamNewPipe/NewPipe#1612]
I receive an "invalid content/source" error trying to restore from the .zip

**Comment by theScrabi** [comment]
Could you tell us which files are int that zip?

**Comment by tlg98** [comment]
There's a newpipe.db database file and a newpipe.settings file

**Comment by theScrabi** [comment]
Ok, what error is NewPipe showing?

**Comment by tlg98** [comment]
"Could not import subscriptions""Invalid File/Source"


Sent from my Sprint Samsung Galaxy S8.
-------- Original message --------From: Christian Schabesberger <notifications@github.com> Date: 8/23/18  11:54 AM  (GMT-06:00) To: TeamNewPipe/NewPipe <NewPipe@noreply.github.com> Cc: tlg98 <pesparza91098@gmail.com>, Author <author@noreply.github.com> Subject: Re: [TeamNewPipe/NewPipe] Can't import .zip backup on 0.13.7 (#1612) 
Ok, what error is NewPipe showing?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TeamNewPipe/NewPipe","title":"TeamNewPipe/NewPipe","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/TeamNewPipe/NewPipe"}},"updates":{"snippets":[{"icon":"PERSON","message":"@theScrabi in #1612: Ok, what error is NewPipe showing?"}],"action":{"name":"View Issue","url":"https://github.com/TeamNewPipe/NewPipe/issues/1612#issuecomment-415490194"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TeamNewPipe/NewPipe/issues/1612#issuecomment-415490194",
"url": "https://github.com/TeamNewPipe/NewPipe/issues/1612#issuecomment-415490194",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [TeamNewPipe/NewPipe] Can't import .zip backup on 0.13.7 (#1612)",
"sections": [
{
"text": "",
"activityTitle": "**Christian Schabesberger**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@theScrabi",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"TeamNewPipe/NewPipe\",\n\"issueId\": 1612,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"TeamNewPipe/NewPipe\",\n\"issueId\": 1612\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/TeamNewPipe/NewPipe/issues/1612#issuecomment-415490194"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 369924501\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by theScrabi** [comment]
Please use the report to markdown converter.

**Comment by Stypox** [comment]
Is this still an issue?
