### ISSUE TITLE
[Feature Request] Download: Progress bar in notification

### ISSUE THREAD

**Issue by DrDragonKiller** [TeamNewPipe/NewPipe#1613]
When downloading a video the notification says you should click it to see download details. Why don't you show a progress bar like other downloads do? (Feature request)

**Comment by TobiGr** [comment]
This only makes sense for larger downloads since updating the notification to often will cause lagging. Maybe it's a good idea to update it every 2 or 3 seconds.

**Comment by voidc** [comment]
NewPipe uses the GigaGet download manager. I wonder if we could use the android system download manager [[1]](https://developer.android.com/reference/android/app/DownloadManager) instead. It would provide this feature out-of-the-box.

**Comment by TobiGr** [comment]
@voidc See #962 for that

**Comment by beskhu3epnm** [comment]
I agree that more information in the notification drawer for downloads is much appreciated.

https://my.mixtape.moe/qcfdih.png
`NewPipe download notification drawer compared to Videoder.`

Aspects to consider:
- Video title
- Amount downloaded / Total amount
- Speed
