### ISSUE TITLE
support invidious link opening

### ISSUE THREAD

**Issue by killoid** [TeamNewPipe/NewPipe#1614]
[invidious](https://invidio.us/) is another hooktube like client to watch youtube videos. it would be great to include support for opening its links in newpipe. thanks.

**Comment by kershan** [comment]
Hi @theScrabi I would to try implementing this.

Please can you provide more info on how, thanks.

**Comment by theel0ja** [comment]
Don't close

**Comment by Perflyst** [comment]
NewPipe now only supports invidio.us links, but there are other instances out there: https://github.com/omarroth/invidious/wiki/Invidious-Instances

Is there a way (if possible without hardcoding) to support all of them?
