### ISSUE TITLE
Add share links on the internet background player

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#1615]
When you play an audio from youtube or sound cloud you have a view with other recommended songs. Well that's awesome except the fact that let's say you select one of the recommended..

Why there is no share button.... like it's pretty obvious there should be one.

You can add it only to a playlist. Only that button.... Can you please add a share button for the currently playing song or at least a share button on the right corner where is the change position of song hamburger button. 

Can't send an image from my phone. :) Best wishes for this amazing app ♥

**Comment by theScrabi** [comment]
If you select a video you have a share button in the top right corner, and you can get to this view from the background player by long pressing a video, and select "show details".
