### ISSUE TITLE
[Request] Peertube integration

### ISSUE THREAD

**Issue by ben345** [TeamNewPipe/NewPipe#1618]
Hi, I just would like to know if you think to implement Peertube on top of Youtube and SoundCloud ?

I saw your comments on the issue : #1435 But it's not clear if this intended or not at all. 

Thanks

**Comment by TobiGr** [comment]
Yes, we'd like to add Peertube, people have already added a 300€ bounty on this. See https://github.com/TeamNewPipe/NewPipeExtractor/issues/79 for more info.
