### ISSUE TITLE
Count in playlist not updated

### ISSUE THREAD

**Issue by compext** [TeamNewPipe/NewPipe#1622]
1) Add a playlist to my favorite
2) If the author add or delete some videos from the playlist
3) Go to my favourite, the count is not changed, so the user may think this playlist has no updates

**Comment by theScrabi** [comment]
So we should check the count then?

**Comment by compext** [comment]
for a better user experience, it's necessary to update meta info of the playlist, including name, count, etc.

**Comment by hipeo** [comment]
I have this problem too, except my playlist is permanently glitched so you can't edit the playlist at all.

**Comment by Stypox** [comment]
Closing in favour of #2088
