### ISSUE TITLE
[feature request] progress in background notification

### ISSUE THREAD

**Issue by xiorcal** [TeamNewPipe/NewPipe#163]
It would be great to add progress indication in the notification.

either a percentage or a "eleapsed / total-time"

**great app**, keep going!

**Comment by theScrabi** [comment]
Yap I'll work on that :)

**Comment by Lokesh-Krishna** [comment]
Really hoping to see this come into the app someday.
Love how simple and pleasant to use it is. Thank you so much for it :)
