### ISSUE TITLE
[Feature Request] Automatic change track skip on long tracks to 30 sec forward

### ISSUE THREAD

**Issue by coreequip** [TeamNewPipe/NewPipe#1630]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

For remote control behaviour of the NP app (eg. listening to music with the background player over bluetooth), the following would be great:

A optional setting on track longer then - lets say - 10 minutes (mostly mixes) turns the "track skip" function in 30 sec forward/backward instead of skipping the track.

```java
function skipTrack() {
    if (options.skipReplaceActive && songLenghtInSeconds >= 600) {
        seek(currentPosition + 30); 
        return;
    } else {
        // do really skip this track
    }
}
```
This feature would make NewPipe even more awesome. :sunglasses:

**Comment by satinworship** [comment]
Also, would it be possible to add in more S Pen action support for the new bluetooth SPen on the Note 9? Right now you can set click and double click actions as Play/Pause or Skip. However, skip doesn't seem to work and I would like the option to have a click be skip forward/reverse.

**Comment by Stypox** [comment]
Closing in favour of #3027, as this solution wouldn't suit everyone
