### ISSUE TITLE
Add autoplay video at the end of the current video

### ISSUE THREAD

**Issue by ReekyMarko** [TeamNewPipe/NewPipe#1631]
Right now, the autoplay feature adds the next video as soon as the current one starts playing. This is less than ideal when you want to f.ex add songs to be played in the background one by one using the queuing feature. When I add the first song, the autoplay feature immediately adds the next one. If I want to add another song to be played next, I have to queue that and go to the player and remove the song added by autoplay.

So here is my suggestion: add the autoplay video only when there is no videos coming up next, and preferably towards the end of the video (I'm thinking 5 seconds before the current one ends)

**Comment by theScrabi** [comment]
Sounds like a good idea :)

**Comment by ReekyMarko** [comment]
Forgot this was open. Recent versions have introduced a feature similar to this.
