### ISSUE TITLE
Icon reminds me of "Arbeitsamt"

### ISSUE THREAD

**Issue by probonopd** [TeamNewPipe/NewPipe#1633]
Icon reminds me of the German [Arbeitsamt](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fde.wikipedia.org%2Fwiki%2FArbeitsamt&edit-text=&act=url) (employment office) which has this logo:

![Arbeitsamt](https://user-images.githubusercontent.com/2480569/44687240-39412680-aa40-11e8-94d3-950b353d238d.png)

I would not be surprised if lawyers would see "[Verwechslungsgefahr](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fde.wikipedia.org%2Fwiki%2FVerwechslungsgefahr&edit-text=&act=url)" (likelihood of confusion) here.

**Comment by theScrabi** [comment]
Yes we had a discussion about that, and a contact to a lawyer, its ok.

**Comment by probonopd** [comment]
Well, the law is one thing and certainly important, but then there's also the emotional association...

**Comment by ecxod** [comment]
the problem is not the legal one, but the analogy to the people using it . It suggests that the people who use it are clients of the Arbeitsamt, like if only jobless people use free software.

**Comment by gkeegan** [comment]
Wat. The only problem is the legal one (not that I think this is really copying of logo, they are different enough). Idk how anybody could possible think of the analogy.
