### ISSUE TITLE
Playback speed is merely a sample rate increase?

### ISSUE THREAD

**Issue by galoko** [TeamNewPipe/NewPipe#1636]
Maybe it's a bug, I don't really know, but when I adjust playback speed voices become distorted and high-pitched. Can you use WSOLA or PICOLA in your player, please? First one can be copied from [ffmpeg filters](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/af_atempo.c) and the second one can be found in [sonic](https://github.com/waywardgeek/sonic) library.

**Comment by wb9688** [comment]
In the playback speed dialog, press unlink and only adjust the top one.

**Comment by galoko** [comment]
everything just stutter

**Comment by wb9688** [comment]
@theScrabi: Don't close this yet.

@galoko: What do you mean? Does the same happen in background player?

**Comment by galoko** [comment]
@wb9688 If I adjust any of track bars separately the end result will be stuttering of audio. I use audio-only playback, I forgot to tell that. I just checked and the same thing happen if I watch a whole video. Maybe it's because I use fairly low-end android phone. Is this speed up computation heavy?

**Comment by ritiek** [comment]
> In the playback speed dialog, press unlink and only adjust the top one.

This works for me in audio-only playback as expected like @galoko wants it to work.

> Maybe it's because I use fairly low-end android phone. Is this speed up computation heavy?

This maybe possible. You may be able to confirm it by enabling CPU usage overlay in your Android's debug settings and comparing CPU usage at different playback tempos.

**Comment by galoko** [comment]
@ritiek I just checked CPU usage via "adb shell top -d 1 | FINDSTR newpipe" and yeah, when I increase playback speed CPU usage is just raising up to steady 27% at 4 core CPU, so my guess is: it's reaching bottleneck there. Well... that's kinda sad really, should I just buy better phone to solve this? I mean MX Player seems to work fine, it uses 7-8% at normal playback speed and roughly 19% at x2 speed, so that's a close call I guess.

**Comment by wb9688** [comment]
Do you have the same problem in the official YouTube app (they use the same
player framework) when you increase playback speed?

**Comment by galoko** [comment]
@wb9688 yes, the same thing just happened. not a good sign I suppose
