### ISSUE TITLE
Video should pause if the headphone is unplugged 

### ISSUE THREAD

**Issue by Dostoi** [TeamNewPipe/NewPipe#164]
When playing a video in the background or in normal view, if you unplugged your headphone, the music keep playing.
It would be nice to pause the video if the device detects that the headphone is unplugged, or at least having it as an option.

**Comment by theScrabi** [comment]
Ok I'll see.

**Comment by Dostoi** [comment]
Thanks ! :)

**Comment by rrooij** [comment]
Doesn't Android have standard behavior for this? Like muting the audio when the headphone unplugs? Why would you want to pause the video?

**Comment by theScrabi** [comment]
Well as I know android, you most likely have to implement it yourself.

**Comment by Ravenstine** [comment]
I would like this as well, as my headphones occasionally unplug themselves and I really don't want whatever it is I'm listening to be blasting out loud in my workplace or public.
