### ISSUE TITLE
[Question] ¿What is the purpose of the stored url in GET's database?

### ISSUE THREAD

**Issue by kapodamy** [TeamNewPipe/NewPipe#1643]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

I notice when a download finish, the url stored is never used.
in table `download_missions` column `url`

**Comment by theScrabi** [comment]
If you speek about the gigaget part, no plan. We want to get rid of it anyway.
