### ISSUE TITLE
NewPipe 0.14.0 Description link not extract well

### ISSUE THREAD

**Issue by Brimont** [TeamNewPipe/NewPipe#1657]
links written in the description do not work if they are long. try to open long links in this video 
https://m.youtube.com/watch?v=4cyiL8n-5P8

Click to this link on newpipe 
➽CANALE YT ALEBRAMBI45:
https://www.youtube.com/channel/UCy2B...

➽CANALE YT BALKAN GLITCH:
https://www.youtube.com/channel/UCpzg...

**Comment by theScrabi** [comment]
Yes I noticed this as well.

**Comment by theScrabi** [comment]
fixed

**Comment by theScrabi** [comment]
Try downloading v0.14.1 again.

**Comment by YOmarKhan** [comment]
How do I download 0.14.1 I have 0.14.0 I use f droid btw

**Comment by switchtegrax1** [comment]
https://github.com/TeamNewPipe/NewPipe/releases download here and you will have to unistall the fdroid version as this one is signed differently

**Comment by Brimont** [comment]
Lino on description no work
https://m.youtube.com/watch?v=AYDWsf2EL4c

https://m.youtube.com/watch?v=gTBRfjo7dc4

https://m.youtube.com/watch?v=cYFxnpSLlxY

https://m.youtube.com/watch?v=QojZq2iQqsM
