### ISSUE TITLE
Videos can't be played anymore

### ISSUE THREAD

**Issue by BaptisteGelez** [TeamNewPipe/NewPipe#1665]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It looks like Youtube released a change that broke NewPipe. It also affected Youtube-DL, and a fix has been merged there, if it helps: https://github.com/rg3/youtube-dl/issues/17457

**Comment by switchtegrax1** [comment]
all fixed in release 0.14.1

**Comment by lol768** [comment]
Is said release on F-Droid?

**Comment by switchtegrax1** [comment]
no,fdroid is still stuck with the old 0.13.5 version
