### ISSUE TITLE
Can't play any video in the app

### ISSUE THREAD

**Issue by jamesbond55** [TeamNewPipe/NewPipe#1667]
Hi,

i was on the version 0.13 and couldn't play any videos. I got always the error "The video url couldn't be encrypted". The problem appeared from one day to another.
So i upgrade to version 0.14 RC3 because i thought mayby the issue is fixed in this version but the described error remain. Any help would be nice:)

**Comment by switchtegrax1** [comment]
https://github.com/TeamNewPipe/NewPipe/releases update to the latest 0.14.1 stable release

**Comment by jamesbond55** [comment]
yes with the 0.14.1 version it works without problems. Thx for your link. 

So you can close the issue when you want:)
