### ISSUE TITLE
Youtube Comment Section & mp3 format

### ISSUE THREAD

**Issue by tajjz** [TeamNewPipe/NewPipe#1668]
Please Add Youtube comment section & mp3 format download option plzzz. Then i can use this app instead of Youtube official app. Love this app.

**Comment by switchtegrax1** [comment]
comments will be implemented soon but newpipe can't download mp3 because youtube audio is only in m4a or opus format and changing would rrquire a conveter and that would increase the app size very signficantly

**Comment by tajjz** [comment]
Ok waiting for comment section😊thanks a lot ♥

**Comment by ridwan47** [comment]
Use TubeMate to download videos and audios with mp3

**Comment by theScrabi** [comment]
@ridwan47 why?
