### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by AlfRomer0** [TeamNewPipe/NewPipe#1670]
Hello, 
The app has stopped working as per yesterday. 
Thanks for your help.

**Comment by gkeegan** [comment]
Get version 14.1

**Comment by gkeegan** [comment]
+ this is a duplicate

**Comment by AlfRomer0** [comment]
Hi Keegan!
Where can I get it? In the F-Droid store they only have 13.7.
Thank you so much for your quick answer!
Alf  Venerdì, 07 Settembre 2018, 09:36PM -04:00 da Keegan Given  notifications@github.com :

**Comment by switchtegrax1** [comment]
https://github.com/TeamNewPipe/NewPipe/releases you will have to uninstall the fdroid version

**Comment by AlfRomer0** [comment]
Great! Thank you so much! 
--
Inviato da Libero Mail per Android Venerdì, 07 Settembre 2018, 09:45PM -04:00 da switchtegrax1  notifications@github.com :

**Comment by 1u** [comment]
thx for the quick fix and the contributions here!
could someone tell me or point me to the answer about the question, if this new version will be available on fdroid soon? (for all my friends wanting to use it but not used to install apps mannually from github and apks)

**Comment by TobiGr** [comment]
We can't say anything about F-Droid release cycle. Two weeks ago, they released index updates daily. I guess they have issues with the build process because version 0.14.0 has not been released on F-Droid yet.
