### ISSUE TITLE
Play on background isn't available for certain streams

### ISSUE THREAD

**Issue by kowith337** [TeamNewPipe/NewPipe#1671]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I've previously hinted about this while testing 0.14.0rc3 before we occur recent NPE bug, cause Google ruined us!

Certain stream no longer have "Background" playback support and button, as I expected, background play seems like it's available for all streams (as it's not private or premium videos/sounds).

Even you can queue from search result, channel's list, share to, etc. it cannot be played and then throw the `Failed to play this stream` error message popup.

Also worst case happen while play multiple queue or from saved playlists, if next stream cannot preload, the current stream will be skip early and jump to next stream that still can play on background.

**Comment by kowith337** [comment]
### User settings
Video Format: WebM
Audio Format: M4A
Main resolution: 720p60
Popup Resolution: 360p
Limit mobile data resolution:240p
Disable gesture control
Disable remember popup size
Disable hold to append tip
Disable watched history
Disable search history

### Example case
I've custom playlist that have 6 videos in the list, but it's only play first 3 videos, rest of them was skipped and removed due to cannot retrieve background audio.

Note these videos below is Thai videos, you may need connect to Thai proxy/VPN before reproduce.

1. https://www.youtube.com/watch?v=FwfcKAJyeqE
2. https://www.youtube.com/watch?v=y69CWHk1meA
3. https://www.youtube.com/watch?v=g2FQdbRfCXw
4. https://www.youtube.com/watch?v=CK9zN7b8j8M
5. https://www.youtube.com/watch?v=SFj00khJeig
6. https://www.youtube.com/watch?v=tk_CVAz04-8

![playlist](https://i.imgur.com/g7rlZeI.jpeg)
![actualplay](https://i.imgur.com/TEXHcIW.png)
![video1](https://i.imgur.com/JhP5aBV.png)
![video2](https://i.imgur.com/A1J6wzc.jpg)
![video3](https://i.imgur.com/CoSNda1.jpg)
![video4](https://i.imgur.com/qWTxJb1.png)
![video5](https://i.imgur.com/CKPnLPu.png)
![video6](https://i.imgur.com/0PRdwnO.png)

**Comment by theScrabi** [comment]
Some streams dont have playable audio only, however i fixed something where i broke the ability to play those streams in background. You are right we/I should fix this.

**Comment by no-boot-device** [comment]
Having this issue with this video if you need more example cases: https://www.youtube.com/watch?v=UK3GNYuAcf0

**Comment by nbmrjuhneibkr** [comment]
Can confirm this issue too on v14.1.

Also, it's rather unfortunate that F-Droid is currently stuck at v14.0, which is pretty much unusable.
I hope that it's possible to skip v14.1 there and go straight to the next release (fully functional again, hopefully).

**Comment by vynmera** [comment]
Seeing this too, it seems this happens often on music-related videos with few movement (think VGM), as I suppose YouTube bundles the video together as it won't cost too much extra. Using popup for now, but would be nice to see this fixed!

Furthermore, this issue also shows at the download popup - no audio download is present anymore.

**Comment by theScrabi** [comment]
@kowith337v0.14.1 shows the play in background feature for all the streams that you listed for me.

**Comment by kowith337** [comment]
@theScrabi  Sorry, but I've tried both videos from @no-boot-device and @Zedreeks, I still cannot play on background, is it possible because of ads insertion that preventing background playback to be happen for me or specific country?

**Comment by theScrabi** [comment]
The country might most certainly be the issue I guess.

**Comment by kaikun97** [comment]
@theScrabi I tried the links that said worked for you and they also do not show background playback for me. If I put any video without that option into a background playlist, the video gets skipped with a toast message saying "Unable to play this stream". Long pressing the video and tapping "Play background from here" gives a toast message that says "Recovering from player error". I also have some music related videos that before this version had the option available, and after this update now do not have option anymore. I think maybe this is not related to the country.

**Comment by wyjek** [comment]
I'm facing this issue too.

**Comment by ritiek** [comment]
It's probably because YouTube does not generate separate audio streams for videos with low view count (AFAIK separate audio streams get generated once the view count reaches ~4,000 views), so there is no play in background option available for such videos.

**Comment by kaikun97** [comment]
@ritiek this is a new issue that is affecting videos not previously affected. The view count appears to be irrelevant (Some affected video I have looked at have view counts over 15,000).

**Comment by ritiek** [comment]
You guys are right. No background option for me with https://www.youtube.com/watch?v=CEsV2z1ymh8 on v0.14.1 either (2.6M views) where as youtube-dl downloads audio fine.

**Comment by justanidea** [comment]
This song works for me in bg

**Comment by theScrabi** [comment]
Truth is, i removed the ability to use videostreams in background player with 0.14.0. This is due to a quick fix since some videos without audio only seemed to crash. @kariugamy You told me that background player could do that, but which video streams would work for it?

**Comment by kowith337** [comment]
@justanidea for first 3 songs, yes, but the rest isn't...
Also you can try this playlist, entire list cannot play in background on my end.
https://www.youtube.com/playlist?list=PL_h4IoimLDtR1XayXb2y6s0OMsoggBt6d

**Comment by theScrabi** [comment]
> This means we need to either modify the extractor to return a DASH file in StreamInfo, so the AudioPlaybackResolver can recognize the stream and use it. We may also need to modify the background player itself, so it can select on which audio stream is played back. In this case, I assume we are going to choose the one with the best quality.

I see. So i think a way to do is maybe not to provide a url to the dash file, but the file itself, and then prepare it a little.

**Comment by theScrabi** [comment]
> This means we need to either modify the extractor to return a DASH file in StreamInfo, so the AudioPlaybackResolver can recognize the stream and use it.

As i said we had trouble with segmantet video streams. As you said we need to have a way to tell that there are streams that are segmented. And than inszead of having a url haveva selector that points to the tag in the dash file. What do you think?

**Comment by karyogamy** [comment]
We can return the dash file url in the extractor, just like how livestream is done. This way, the audio resolver would just play the stream in audio. But this means we need to implement a quality selector, so these dash videos can change quality. Otherwise, the current video resolver will treat it as a livestream and not provide a selector. This is a good idea in general, since this means we can also change livestream quality. 

However, if we want to let the user download audio streams, we will need to parse the segmented audio url still. This should be fine though, since the resolver will take the dash file before it looks for an url to play. 

So, I think we should still parse the segmented url to allow download. But also return the dash url, so the player resolver can play them instead of the invalid urls.

**Comment by theScrabi** [comment]
> But this means we need to implement a quality selector, so these dash videos can change quality. Otherwise, the current video resolver will treat it as a livestream and not provide a selector.

Yes that should be done. With this selector we can later also filter out the streams that created the crashes in the first place :)

> However, if we want to let the user download audio streams, we will need to parse the segmented audio url still.

But wouldn't that mean we would need to mux them as well?

**Comment by phly95** [comment]
https://www.youtube.com/playlist?list=PLQNHYNv9IpSw_bS2Jke60RJ85Nx_CsgjP this playlist seems to have issues. If you hit the background button, it repeatedly said "failed to play steam" for every song in this album.

**Comment by kaikun97** [comment]
Any ETA for when this will be fixed?

**Comment by Nathan-Jonson** [comment]
I'm also having the same issue. Playlist https://www.youtube.com/playlist?list=PL493TQZToFwGtwMh1_9Y_nuralywpdQ45 has multiple that do not play. 
Also, some will stop playing part way through. This appears to happen once the buffer loads up to the video that cannot be played. 

I under stand that playing the non-supported videos requires some effort, but in the meantime, would it be possible to at least finish the previous one?
Thanks!
