### ISSUE TITLE
Subscription counter in search displays wrong amount

### ISSUE THREAD

**Issue by ZerataX** [TeamNewPipe/NewPipe#1672]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Using the latest version 0.14.0 when using the search function the subscription count seems to be based on the amount of videos the channel uploaded times a million or something, instead of the actual subscriber count.

Example:
![68747470733a2f2f7667792e6d652f577a5948496a2e706e67](https://user-images.githubusercontent.com/1891273/45357360-4c1e3400-b5c6-11e8-96c9-c0819ee70d4b.png)

**Comment by theScrabi** [comment]
Yes its true that is a bug :/

**Comment by theScrabi** [comment]
fixed.
