### ISSUE TITLE
Player is displaying the vertical only orientation on the tablet Asus Transformer TF300 (Android 4.2)

### ISSUE THREAD

**Issue by konkor** [TeamNewPipe/NewPipe#1673]
Thanks for the great application first!
Today I updated FDroid version 13.7 to GitHub 14.1 to fix recent youtube player on my tablet. I'm using it mostly with dock station in horizontal orientation but the new version just ignoring horizontal orientation and changing only vertical orientations.
I selected internal embedded framework player to temporary fix it.
So I have tested it on the phone with Android 5.1 and it's working just fine.

**Comment by theScrabi** [comment]
What do you mean exactly?

**Comment by konkor** [comment]
When I press the play button on the tablet, it's rotating all Android layout including system notification area and buttons.

**Comment by theScrabi** [comment]
Did you try tabbing on the rotation button, or enable autorotation?

**Comment by konkor** [comment]
Nice. The rotation button fixed the problem. I didn't know about this button. You can close it.
Thanks.
