### ISSUE TITLE
Email address does not show up in bugreport

### ISSUE THREAD

**Issue by moshpirit** [TeamNewPipe/NewPipe#1676]
Bug report: when reporting bug the email direction doesn't show up

**Comment by TobiGr** [comment]
Which mail client do you use?

**Comment by moshpirit** [comment]
K9-mail, which is weird, because I remember reporting by mail in former versions and everything working fine

**Comment by TobiGr** [comment]
Well, I can't reproduce this and IIRC we did not change any code which is important for this.
Which Android version/Custom ROM is installed on your device? Which NewPipe version do you use?
Can you also test this with another mail client please?

**Comment by moshpirit** [comment]
OK, that's weird, now it does appear so I think I'm closing the issue. Sorry for the inconvenience.

I'm using NewPipe 0.13.7 (I'm going to update to 0.14.0) from F-droid on Android 7.1.2 (Official)
