### ISSUE TITLE
Next song (autoplay) not working anymore (build 14.1)

### ISSUE THREAD

**Issue by henkya** [TeamNewPipe/NewPipe#1678]
Hi All:
First off many thanks for the quick fix on the YouTube stream URL error. 
I was using 13.7 before and just upgraded to 14.1 couple hours ago.

The new build did fix the url issue but it seems that the autoplay functionality is not working anymore - both while playing music on Main or in Background (or has it been removed? I never used the build 14.0 before so I don't know if this was an intended new thing?
The autoplay worked fine in build 13.7 for me before (i.e. When I play a song in background it automatically queue up a new suggested song in the queue for me).

In build 14.1, when I played a song in background - nothing else got queued up

**Comment by goxr3plus** [comment]
Exacrly the same problem :)

**Comment by goxr3plus** [comment]
![](https://i.imgur.com/evl1lAT.png)

**Comment by theScrabi** [comment]
Have you ched if autoplay is still enabled?

**Comment by henkya** [comment]
Okay got it fixed now!! . Yeah I forgot to turn the autoplay on :)
FYI the setting is in this page:
Settings > content
