### ISSUE TITLE
background and text color are the same, it can't see time info

### ISSUE THREAD

**Issue by michel90** [TeamNewPipe/NewPipe#1679]
The background is dark and the letters also, and they do not allow to see Duration and Current time, 

In the following the rights is adjusting tones to brighten to see time tags
![Image](http://i64.tinypic.com/nq9t3s.png)

**Comment by skil3z** [comment]
What version of the app is this? Also,
Settings > Video & Audio > Player: "Use old built-in Mediaframework player" What is this set to? Try changing

**Comment by michel90** [comment]
Latest release 0.14.1
I set both options "ON" and "OFF" and both show it bad

**Comment by skil3z** [comment]
@michel90 How about (Also under "Player") Use external video player
Do you have it enabled? It should be off to use the NewPipe player, which looks completely different from your screenshots

**Comment by theScrabi** [comment]
This is the old player. Which android version do you use? If its newer than 4.1 please disable it, we only support that player for backwards compatibility.

**Comment by michel90** [comment]
Android 4.0.4
I'm not using an external video player, is NewPipe player and his appearance does not change anything when I enable or disable "Use old player"

**Comment by switchtegrax1** [comment]
the new player is only avaliable on android jellybean 4.1 and android 4.0 can only use the old player

**Comment by michel90** [comment]
ok, so old player option has that issue with colors in time tags

**Comment by Stypox** [comment]
This issue should probably be transferred to https://github.com/TeamNewPipe/NewPipe-legacy but I don't have the rights

**Comment by opusforlife2** [comment]
@TobiGr ^
