### ISSUE TITLE
[bug] Hangs when seeking forward or backwards

### ISSUE THREAD

**Issue by Gitoffthelawn** [TeamNewPipe/NewPipe#168]
On Android KitKat with NewPipe 0.7.3, seeking forwards or backwards in a video causes NewPipe to hang.

Watching a video works perfectly.  But if you tap anywhere on the seek bar, NewPipe hangs.  No error message is issued.

**Comment by theScrabi** [comment]
I know that problem, but thats a problem of android media player. Stand by we are about to switch to exoplayer, which may fix that issue.

**Comment by Gitoffthelawn** [comment]
Looking forward to it!  Hopefully it will work.

**Comment by Gitoffthelawn** [comment]
BTW, not sure you want to close this since it's an active bug.

**Comment by theScrabi** [comment]
I thought it was a duplicate.
