### ISSUE TITLE
[Request] Add an option to view a playlist while in Popup Mode

### ISSUE THREAD

**Issue by oilrig11** [TeamNewPipe/NewPipe#1683]
I would like to be able to view a playlist and jump around videos within that playlist while in pop up mode. As it is now to do this I have to expand the video first then switch back to popup mode after choosing where I want to continue from.

**Comment by Stypox** [comment]
You can long-press on items to open them directly in the popup player. Or you can enqueue the whole playlist on popup and then switch videos from the popup queue.
