### ISSUE TITLE
playlist use new player even when old is selected

### ISSUE THREAD

**Issue by ezx-code** [TeamNewPipe/NewPipe#1686]
Hi all.
I use the old player option because the new do not resize to fullscreen on my x96mini tv box tuning Android 7.1.2, at any résolution, btw.
When entering the playlist, i can play individual vidéos, but it is when i choose 'play all' that the 'wrong' player launch. 
It works playing every videos on the list, just not with the selected player..
This is true for a year and à half updating the app on fdroid and also on the 0.14.1 today.
Regards, and thousand thanks for this marvellous app. All the family enjoy not being bugged by YouTube awfull autoplay!

**Comment by theScrabi** [comment]
The old player is actually legecy and should be removed soon.

**Comment by theScrabi** [comment]
How comes the new player does not play fullscreen?

**Comment by ezx-code** [comment]
Hi, 
I still dont know... As from the beggining, using the alternative player or the old one worked for me... 
According to Google :-) my board is am805w with mali450 graphics https://androidtvbox.eu/x96-mini-android-tv-box-powered-amlogic-s905w-chipset-now-24-99-promo/ 
So i Never investigate on this. Maybe i am wrong, i didn't found a resize feature? The video appears like a small windows (i am not in windows mode...) without border on the center right side of a black screen.
Maybe you can guide me to send you debug logs, etc...? I would be more than Happy. But since the old player feature is going to disappear, maybe juste allowing playlist to be all played with the alternative player would be a simple solution for those like me...? I can't tell about how much people encounter that 'bug'....
Regards, Fred

**Comment by ezx-code** [comment]
Sorry. It seems my board is amlogic s905w. Not am805w , i mixed up things..

**Comment by theScrabi** [comment]
Can you send a screenshot Please. Maybe you are exidently using the popup mode.

**Comment by ezx-code** [comment]
Hello, 
I am sorry i had problems with my mails...
So here is a pic of the TV playing a random video, with defaults options/player. 
https://imgur.com/a/cajQUGO
I dont think it's popup mode, i tested this mode, but this is the same i can't resize in popup or windows mode. 
You may have noticed the image's height is top big the ratio is bas, but the image is not filling all the screen in height... The lengh seems to be only on the right side of the screen.

I can test on another monitor if it helps...
But again my first concern is about the 'play all' button on playlist  not using the selected alternative (or external) player.

Thanks you ans best regards.

**Comment by ezx-code** [comment]
Sorry, using my phone...
Height is too big and ratio is bad...

**Comment by ezx-code** [comment]
Hello again,
Did you saw my pictures?  can you confirm I am not confusing and I really use normal fullscreen mode?
I would really love if it was possible to play a list using alternative player...
Sounds simple?😃
Again I propose to help with testing why my setup build the image on a quarter of the screen with that heightened ratio...
Regards.
