### ISSUE TITLE
Bump F-Droid repo to 0.14.1

### ISSUE THREAD

**Issue by basilgello** [TeamNewPipe/NewPipe#1689]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Currently F-Droid lists NewPipe version as 0.14.0 from September 6th having issues with Youtube playback (#1069). Please push the update to F-Droid so users can continue using the software without the need to reinstall an app.

**Comment by theScrabi** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/1352
