### ISSUE TITLE
resolution resets to default after coming back from background player

### ISSUE THREAD

**Issue by switchtegrax1** [TeamNewPipe/NewPipe#1693]
if i put a video in 360p then minimize to listen in the background,once i go back to the video it resets to the default resolution set in settings instead of staying at the previously set resolution

**Comment by theScrabi** [comment]
Thats because it does reload the page and therefore loose the settning as it is not permanent.

**Comment by theScrabi** [comment]
I wpuld not want to save it though.

**Comment by TobiGr** [comment]
@theScrabi Are you sure? That's bad UX. On the other hand, how many people switch from video to background and then back?
