### ISSUE TITLE
ability to choose another homepage or blank homepage instead of trending

### ISSUE THREAD

**Issue by blablablerg** [TeamNewPipe/NewPipe#1698]
Hello, I love your app, it's great!

I have a feature request: ability to change the default homepage (trending) to something else, or blank, with an option to search YT. This is because trending tends to be filled with clickbait and other low quality stuff. Its very distracting!

Tnx for the great app :)

Cheers,

Krishan

**Comment by switchtegrax1** [comment]
you can do that in the latest version 0.14.1 https://github.com/TeamNewPipe/NewPipe/releases

**Comment by TobiGr** [comment]
That's already possible. In the settings, go to Appearance and click on "Content of main page". If you need more explanations, feel free to ask :)

**Comment by ChristinaDev** [comment]
Hi, please how can I make the home page Blank by Default? (By Default I mean a Blank page is what I should see just after installation even before changing it from settings). Thanks in advance

**Comment by kowith337** [comment]
Instead, I want to change "by default"

Currently default is set to 'Trending' I sugest to revert to 'Blank' like an older version instead...

Or have a welcome page (intro, first launch, something else to call) and let user decide what first page should be set.
