### ISSUE TITLE
Is it just me or everyone getting crash & error "could not decrypt video URL video" ??

### ISSUE THREAD

**Issue by lunio9** [TeamNewPipe/NewPipe#1700]
Not sure when this started but today since this morning i can't play video or audio from even on the Trending menu.
This happens both on Newpipe and Newpipe BETA.
I even cleared data of Newpipe and went back into Trending, chose a video and as soon as it tries opening, it crashes with Guru Meditation "could not decrypt video URL video"
Did something change on Youtube?

**Comment by IamJithendra** [comment]
Issue Fixed On Latest Release

**Comment by lunio9** [comment]
thanks and sorry for the duplicate issues.
related to https://github.com/TeamNewPipe/NewPipe/issues/1692
