### ISSUE TITLE
Newpipe crashes when opening

### ISSUE THREAD

**Issue by rkaug27** [TeamNewPipe/NewPipe#1701]
![screenshot_2018-09-10-20-31-10](https://user-images.githubusercontent.com/40330928/45314245-e3897580-b539-11e8-8953-b1ec39b8859e.png)
![screenshot_2018-09-10-20-29-45](https://user-images.githubusercontent.com/40330928/45314247-e3897580-b539-11e8-809c-32748e11f7b5.png)

- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by TobiGr** [comment]
These screenshots do not help us in any way. Please past the error report after converting it with our [Crashreport converter](https://teamnewpipe.github.io/CrashReportToMarkdown/). 
And btw we have released NewPipe 0.14.1 (which has not made it to F-Droid yet).

**Comment by rkaug27** [comment]
thank you for your reply... 
now I get that... I posted reply after using the latest version....

**Comment by rkaug27** [comment]
Thanks again current 0.14.1 is worked well...
