### ISSUE TITLE
Live and video not work on player

### ISSUE THREAD

**Issue by Brimont** [TeamNewPipe/NewPipe#1703]
All live and video not work.
1080p and 1080p 60 fps Video not work.

Video of my phone https://streamable.com/s75zg

how to see from the video of my phone the live do not start and the 1080p and 1080p 60fps videos do not start. can you solve this problem?

Link youtube on video
https://www.youtube.com/watch?v=9oiK7M9Oolc

https://www.youtube.com/watch?v=KQ7t0auyRgc

https://www.youtube.com/watch?v=9U9Sicrrep4

https://www.youtube.com/watch?v=6v2L2UGZJAM

https://www.youtube.com/watch?v=OKM--8fzDpo

**Comment by Brimont** [comment]
You can fix this https://github.com/TeamNewPipe/NewPipe/issues/1600?

**Comment by Stypox** [comment]
Is this still an issue?

**Comment by Stypox** [comment]
Closing in favour of #1600
