### ISSUE TITLE
Ui crash loading videos from any of the views

### ISSUE THREAD

**Issue by Neodymium5312** [TeamNewPipe/NewPipe#1706]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.14.1
* __OS:__ Linux motorola/payton/payton:8.1.0/OPW28.46-21/e3c72:user/release-keys 8.1.0 - 27

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:620)
	at java.lang.Integer.parseInt(Integer.java:643)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:396)
	at org.schabi.newpipe.util.ListHelper.computeDefaultResolution(ListHelper.java:113)
	at org.schabi.newpipe.util.ListHelper.getDefaultResolutionIndex(ListHelper.java:40)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.setupActionBar(VideoDetailFragment.java:738)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1204)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$startLoading$6$VideoDetailFragment(VideoDetailFragment.java:866)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$Lambda$5.accept(Unknown Source:4)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6545)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)

-------------------

```

**Comment by Akcqsel** [comment]
Hi,

Seems not to be the exactly same issue but unable to read videos also.

Here's report, sent by mail.

Thank you, great app. Keep going on !


Exception in NewPipe 0.14.0

{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=HQw_GIiqIDM",
   "content_language": "FR",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.14.0",
   "os": "Linux Android 6.0.1 - 23",
   "time": "2018-09-11 06:51",
   "exceptions": [
      "org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function \n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:722)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:597)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:48)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:55)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3$ExtractorHelper(ExtractorHelper.java:113)\n\tat org.schabi.newpipe.util.ExtractorHelper$$Lambda$3.call(Unknown Source)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4073)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14349)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4073)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)\n\tat java.lang.Thread.run(Thread.java:818)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \"([\"\\'])signature\\1\\s*,\\s*([a-zA-Z0-9$]+)\\(\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:702)\n\t... 31 more\n"
   ],
   "user_comment": "Unable to read the URL signature of the video"
}

**Comment by theScrabi** [comment]
You say this happens the every video, or is it just specific ones?

**Comment by Akcqsel** [comment]
Every video, from any view.
Thanks.

**Comment by Akcqsel** [comment]
From France.

**Comment by Salamandar** [comment]
Same here, using 1.4.1 from France. Looks like youtube "broke" the Web page :(

**Comment by Neodymium5312** [comment]
I'm located in the myself but yes it's any video from any of the different tabs

**Comment by Neodymium5312** [comment]
It's suddenly working again. No clue why since I haven't changed anything ..

**Comment by Akcqsel** [comment]
Great ! 
Still not working for me.

**Comment by theScrabi** [comment]
Cpuld you trie to switch to another language/country in the settings?

**Comment by richfelker** [comment]
I'm hitting the same issue. Country is US.

**Comment by Neodymium5312** [comment]
My new pipe works on USA as well as United kingdom.

**Comment by nicolasdb** [comment]
Same problem from Belgium

**Comment by tomyasli** [comment]
I'm having the same problem and didn't change my device configuration.

**Comment by richfelker** [comment]
Yes. With 0.14.1 installed it works again for me.

**Comment by Akcqsel** [comment]
It works for me too with the new version. Thanks !

**Comment by nicolasdb** [comment]
I have uninstalled and reinstalled from F-droid, it's working again. 
thanks.

**Comment by onyxogen** [comment]
When I set a "resolution limit when using mobile data" (e.g. 720p) this error occurs on every video. If I set it to unlimited, it does not.
I hope you can reproduce this. I already sent an email with the bug.

**Comment by benryanau** [comment]
Repro here, 0.14.1 on Android 6.0. Locale en-au.

Definitely the "Mobile data resolution restriction" setting that triggers it for me.. thanks for the clue onyx!
