### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by Bindslev** [TeamNewPipe/NewPipe#1709]
I get a 'download failed', 'the requested file was not found. https://f-droid.org/repo/org.schabi.newpipe.beta_47.apk'. I uninstalled the application today in hope that it would fix the issue with requesting videos, but now I am unable to download and install it again.

**Comment by TobiGr** [comment]
The beta has been removed because F-Droid needed to much time to build and publish new releases. Please use the "normal" NewPipe app. Unfortunately, F-Droid have not published the latest bugfix release yet. In case the F-Droid version crashes, please wait until they updated their index.
