### ISSUE TITLE
[Request] Usage on a Android-TV

### ISSUE THREAD

**Issue by rubbernglue** [TeamNewPipe/NewPipe#1711]
I use this app on my Android TV (philips) and I have some small issues which is hopefully easy to fix..

1. I have to use a separate launcher since newpipe installation does not create a "separate desktop icon". The default philips tv launcher does not give the availibility to see all installed apps in a menu like regular android launchers do. Only installed apps which provide a "desktop icon" is available through the (philips) app-menu.

2. The app is clearly made to be used through touch-interface, but I use a remote control. Some features are not available if I dont connect a mouse to my TV, like: subscripe/unsubscripe for instance.

3. The most anoying part for me is not being able to pause a video; I have to see it all or back out.

Thanks fo a great app!

**Comment by theScrabi** [comment]
Newpipe is not optimized for television, however we have that in mind, and with adding support for dpad we are working twords  tv.
