### ISSUE TITLE
Queue management UI automation & UX improvements suggestions

### ISSUE THREAD

**Issue by doronbehar** [TeamNewPipe/NewPipe#1717]
Hello my dear NewPipe heroes,

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I've read over all the currently open issues which are related to several improvements suggestions I'd like to discuss:

- #1487
- #1409
- #1386
- #1366
- #1334
- #1101
- #1098
- #1053
- #1010
- #1002
- #577

I think all of these issues can be closed in favor of a new issue that will strive to track the general improvements needed for the playlist management UI / UX. I know from the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) you prefer to have smaller issues and not multiple of them in one issue but I think these issues should be compressed to a single one because most of the app's behaviours related to the queue management should be automated so the app will act more like a music app or an improved version of the original YouTube app rather then something else.

Here is a description of the current problems described in the issues mentioned above in my own words:

Let's say I'm performing a search and I click a video from the search results, I might want to watch the video in full screen / popup / background.

* In case I have initially played the main play button and afterwards I've decided I'd like to put my attention on other things, whether it'll be other videos from the app or perhaps totally other apps. In any chance, I'd probably want to automatically switch to popup / background. **This should be done automatically whether I press the home button or the back button** (#1098, #1010 and #1334). Pressing the back button shouldn't stop the video totally (#1334) but continue on popup / background. A sort of workaround exists thanks to the 'Minimize on application switch' setting which through more button presses (and more concentration from the user) enables switching to popup / background and return to the app and the video info and suggestions through the OS's recent apps after reaching the home screen... IMO, this setting shouldn't even exist and it should become the built-in behaviour along with the desired change to the back button's behaviour.
* If I've switched to background playing, some kind of indicator is needed (besides the notification) for indicating something is playing in the background (#1409). This button should naturally lead to the queue just like the notification.
* In case I know I'd like to initially watch the video on popup or listen to it on the background, we come back to the same problems noted in my 2nd point.

Let's say we have reached the background queue activity (currently possible only through the background player notification (as far as I know)), the UI there acts rather non intuitively as well IMO:

* Pressing the currently playing video just restarts it. Why would I want to restart it? IMO, the most intuitive action for this press on the **currently playing** video is going to the details of video and see the video's suggestions (similar to the 2nd suggestion from #1386). A similar improvements to this behaviour was suggested in #1366 (title should have been clearer..) which can be good enough in the meantime only if the back button behaviour on full screen videos will be fixed (again - #1334).
* One more smaller issue I feel needs to be mentioned as well regards the behaviour of the 'queue to background' button in the video info activity when the setting 'Auto-queue next stream' is on - when it is, queueing to the background queues the video **after** the video that was queued automatically by this setting! I understand this is the reasonable behaviour from a software behaviour point of view but IMO, intuitively, the 'Auto-queue next stream' setting should act more like a fallback action for when the queue is over, rather then an automated action.

To summarize, I'd put down everything to this list:

* Make the back button switch to popup / background when a video is on full screen (#1334, #1098, #1010).
* Add background player indicator inside the app (#1409).
* Make pressing the currently playing video in the queue lead to the details of it and not restart it (#1366 & 2nd suggestion from #1386).
* Make the 'Auto-queue next stream' setting act more like a 'play "up next" video as a fallback when queue is over' so the next video will be played only when no video was queued **by the user**.
* Enable adding to the current queue all of a playlist's videos (suggested in https://github.com/TeamNewPipe/NewPipe/issues/1002#issuecomment-358980047)
* Enable enqueueing videos when opening links (#1487)

Issues I think can be closed:

- #577: I don't experience this problem and it seems pretty old.
- #1010 / #1098 / #1334: Essentially the same - again only the back button behaviour acts to weird although there is the 'Minimize on application switch' setting.

I'm no Android developer although I have only minimal background but I hope my feedback will be useful. You have no idea how much I admire your work, for being so effective in helping users get YouTube content for free - the way it was in the past. Thanks again for creating and working on this wonderful app!

**Comment by switchtegrax1** [comment]
#1053 issue is that when you pause a video then press home it will resume in the background instead of staying paused,its annoying because now the video needs to be closed otherwise whenever they pause and minimize it the video will unpause and keep playong in the background

**Comment by doronbehar** [comment]
Damn you are right @switchtegrax1, I didn't notice this problem up until now. I've edited my 1st comment accordingly.

**Comment by filalex77** [comment]
Good job collecting these! Adding a playlist to queue is probably my most desired feature right now, I might even give it a shot :)

**Comment by opusforlife2** [comment]
@Stypox Most of the linked bugs are closed. Should we close this as well?

**Comment by doronbehar** [comment]
Yes I think so. Thanks for all the work on https://github.com/TeamNewPipe/NewPipe/pull/2907 and 0.20.0 - it's a historical update. Finally I can recommend nontechnical people this app and tell them that it's UI is _good_. Thanks again :heart: .
