### ISSUE TITLE
Whats's new results have no specific order

### ISSUE THREAD

**Issue by MeCias** [TeamNewPipe/NewPipe#1719]
Hi,

quite not sure whether I do not see the setting or it is just not there. I miss anyhow a way to select if the what's new results are sorted ascending or descending. At the moment they are all over the place.

**Comment by kaikun97** [comment]
There is no setting for it, it's how the results are retrieved from Youtube and they do not have any order associated with them. An issue was made about it at https://github.com/TeamNewPipe/NewPipe/issues/1448

**Comment by TobiGr** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/739
