### ISSUE TITLE
What's the point of the like and dislike buttons if we are not logged in on the NewPipe app?

### ISSUE THREAD

**Issue by sNrVJx** [TeamNewPipe/NewPipe#1721]
What's the point of the like and dislike buttons if we are not logged in on the NewPipe app?

**Comment by gkeegan** [comment]
I like having them because it allows me to see if a video is a scam, since viewing comments are not yet implemented in NewPipe.

**Comment by wb9688** [comment]
It's not a button; it just shows how much a Stream (as we call videos
internally, since on SoundCloud there are no videos) is liked and/or
disliked.

>
