### ISSUE TITLE
Channel subscriber count wrong in search results (using # of videos instead)

### ISSUE THREAD

**Issue by OverkillGuy** [TeamNewPipe/NewPipe#1726]
Channel search result gives incorrect number of subscriber (actually using number of videos)
number of subscriber is fine in detailed channel view.
Using latest at the time: 0.14.1 via fdroid

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports. (irrelevant, not a crash)

**Comment by OverkillGuy** [comment]
Search result of a small (<1M channel I love)
![img_20180916_195127](https://user-images.githubusercontent.com/2757699/45599799-fe506400-b9e9-11e8-87f5-fb1ddbae845e.jpg)
Note the 214M subscribers = 214 videos

Compare with the detailed channel view
![img_20180916_195110](https://user-images.githubusercontent.com/2757699/45599816-47a0b380-b9ea-11e8-8aba-76a9b7a434b9.jpg)

**Comment by OverkillGuy** [comment]
Reproduced on other channels.

I would go out on a limb and assume this issue is not a problem of displaying the wrong field, but of inappropriate parsing of the subscriber count in search results. I'll have a look inside the library code (specifically the different codepath between channel details and search results).

**Comment by theScrabi** [comment]
This is fixed. Next version will have the fix.
