### ISSUE TITLE
Videos Lack Option to Play in Background

### ISSUE THREAD

**Issue by Astronox** [TeamNewPipe/NewPipe#1728]
As the title says, I'm on 0.14.1. First image shows lack of any option to play in background, second image shows what most videos look like. I'm not sure what other information there is to add to this (first time posting an issue), but I'll keep an eye on this to answer what I can.

![image](https://user-images.githubusercontent.com/38494293/45605105-6d3cb580-ba08-11e8-8ea3-a8f42f6d9ca9.png)

![image](https://user-images.githubusercontent.com/38494293/45605110-762d8700-ba08-11e8-8634-fe565cfcbca6.png)

**Comment by nbmrjuhneibkr** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1671

**Comment by wyjek** [comment]
I'm facing this issue too.

**Comment by kowith337** [comment]
Yep, might be duplicate.
I don't think about it's depend on view count, subscriber count, whatever...
Can anyone try fork 0.13.5 and update NPE to this version and test it out is it still can play on background or not, if yes it maybe a bug that start to happening on 0.14.0 onward...
