### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by canbonbon** [TeamNewPipe/NewPipe#1729]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
Hello, I just installed this app. But it shows "network Error" and does not do anything else. I am on Oreo OS. Any help or suggestions on how to fix that?.

**Comment by gkeegan** [comment]
Any info would be useful. App version. Device manufacturer. Stock rom or custom. Etc

**Comment by canbonbon** [comment]
Sorry for the false alarm. Looks like my router was blocking it. Its all set now.
