### ISSUE TITLE
Download location settings change requires app restart

### ISSUE THREAD

**Issue by kasbah** [TeamNewPipe/NewPipe#1730]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

A slight annoyance that I noticed:

1. Set download location to SD-Card
2. Try and download a video
3. Get notification that download to SD-card is not supported yet, *confirm reset of download location*
4. Try and download again, get the same notification
5. Check settings, it's *already changed to internal storage*
5. Restart app through the task manager and it works

Currently running 14.1 from F-Droid on Lineage OS

**Comment by kapodamy** [comment]
@kasbah  fixed in #2149
