### ISSUE TITLE
Exception on all videos

### ISSUE THREAD

**Issue by NitroNils** [TeamNewPipe/NewPipe#1731]
-    Version: 0.14.1
-    OS: Linux Android 6.0 - 23 
-    Device: Huawei ALE21
-    UI: EMUI 4.0.3

   _"exceptions": [
      "java.lang.NumberFormatException: Invalid int: \"\"\n\tat java.lang.Integer.invalidInt(Integer.java:138)\n\tat java.lang.Integer.parseInt(Integer.java:358)\n\tat […etc]"_ 

Any reason why my device refuses to stay alive when I load a video?

I've been using this version for a week or something, but this never happened before.

NewPipe in general crashes upon downloading certain videos (why? Could it not just tell me "It's not possible to DL this video?).

I send the built in bug-reports, but there's never any reply so I have no idea whether this is usefull or just terrorizing the busy devs.

I'm pretty sure this is an issue with Huaweis horrible vendor twists on the OS/UI-thing, but maybe you might know how to solve this, or who to ask?

### One of my fav apps!

**Comment by NitroNils** [comment]
It works again, error was due to Google changing something.
_https://mastodon.technology/@fdroidorg/100713565500510428_

**Comment by theScrabi** [comment]
No thats a different issue.

**Comment by theScrabi** [comment]
You may need to tell us the language/country you ar using.

**Comment by wb9688** [comment]
Could you please put it in
https://teamnewpipe.github.io/CrashReportToMarkdown/ and paste it here?

Btw crash reports will be automatically processed into a system we're
using, where we can view how much that error has happened, on what Android
versions it occurs, etc. Within that system we can't reply, so that's why
you never get a reply.

**Comment by NitroNils** [comment]
@theScrabi In NP's settings I use Norwegian as default content country, default system language is English (NP is also English - I'd be happy to translate to NO). The crash reports I send out contains all info, they come from anti.moral and 9liam.

As edited above, the issue is solved upon reinstalling from F-Droid's repositories. Same version nr.

@wb9688 thx for explaining!
The report was sent from 'that system' so you should find it there. I can dig it out of my _sent-directory_ if you truly need it. But issue is 'solved'.

**Comment by theScrabi** [comment]
Thats propably an issue related to the different timeformat. Norwegian use <minute>.<second> not like the rest <minute>:<second> for telling the length of a video. If its that issue it will be fixed with the next version.

**Comment by jhabdas** [comment]
In #1716 I had exceptions on all videos as well as suggested by OP. In my case my Fdroid client DB wasn't pulling the latest version of NewPipe. Uninstalled and Reinstalled Fdroid allowed me to upgrade to the latest APK more easily than attempting to download from source.
