### ISSUE TITLE
Error when trying to stream a video

### ISSUE THREAD

**Issue by heyarne** [TeamNewPipe/NewPipe#1735]
I know that this shouldn't be used for crash reports; unfortunately my mail got bounced back. I can't watch any video anymore, there's an exception thrown every time (see attached file). I'm using the MicroG fork of LineageOS 15.1., if you need any additional information I'm happy to help.

Even though I can't use it right now, I'd like to say thanks for making this app! It's fantastic.

[20180918_180626.txt](https://github.com/TeamNewPipe/NewPipe/files/2400238/20180918_180626.txt)

**Comment by wb9688** [comment]
Update NewPipe to v0.14.1.
