### ISSUE TITLE
Download button in long-tap menu?

### ISSUE THREAD

**Issue by Somethingweirdhere** [TeamNewPipe/NewPipe#1736]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

What do you think about adding an option to directly open the download box in the long-tap menu? Currently you first need to open the video, and then wait until the page has stopped loading, which is quite annoying when I have a bad connection.

**Comment by theScrabi** [comment]
No, i think this wouldn't of big use. I want to prevent putting to much stuff inthat menu.
