### ISSUE TITLE
[Issue] Please don't delete playlist entries on error

### ISSUE THREAD

**Issue by Repligon** [TeamNewPipe/NewPipe#1737]
Since the last update my whole playlist gets cleared on every connection hiccup and I have to recreate it and search for a place where it stopped. Sometimes it happens on the road and I have to do this on the go.

I would much prefer it to rerty connection until success or manual input.

**Comment by theScrabi** [comment]
Hm just jump to the next one without delete. I see.

**Comment by Repligon** [comment]
Noo. Sometimes I listen to stream recordings. I don't like the idea of loosing the timestamp in hours long video.

**Comment by 4ut0-M-4t** [comment]
This issue is a duplicate of #1188
