### ISSUE TITLE
VLC sometimes not found and app wants to install it

### ISSUE THREAD

**Issue by leoauri** [TeamNewPipe/NewPipe#174]
Hi scrabi, thanks for your work,
Sometimes when I hit the headphones to use music listening mode, the app doesn't find vlc and wants to install it. Sometimes it works. I haven't identified a pattern as to when. 
This is on android 4.2.2, FairphoneOS 1.8.7
Cheers

**Comment by theScrabi** [comment]
Hm we had this error once. But I still didn't have time to search for it, or was able to reproduce it.

**Comment by leoauri** [comment]
Haven't seen it happen for ages now so I guess that update fixed it as you suspected,
Cheers
