### ISSUE TITLE
[Feature Request] Update our UI to match the current YT app

### ISSUE THREAD

**Issue by jerryn70** [TeamNewPipe/NewPipe#1740]
Currently we are on the old UI style of yt app. The UI of YT app has changed a lot . We need to change our "Trending page" style and whats new "Whats New" page style to match the current YT app. 
In Newpipe app  videos in the trending page and What's New page is displayed in small size (small preview) we need to change it big size like this the screenshot. 
![](https://i.imgur.com/nSJjKEH.jpg)

**Comment by trymeouteh** [comment]
I think the light theme could be better by making the black text ontop the red elements be white instead but it is a minor issue. And I do prefer NP UI over YouTube since it is simple.

**Comment by FaizKhan5** [comment]
I like original YT UI because some people play videos by only see thumbnails.

**Comment by Serkan-devel** [comment]
But I think YouTube uses twice as much band with as newpipe with all the autoplaying thumbnails which gets really annoying

**Comment by Z3ROGRAV1TYx** [comment]
> But I think YouTube uses twice as much band with as newpipe with all the autoplaying thumbnails which gets really annoying

I personally +1 for video previews, but I think it should be a toggle on or off feature for people who don't want it.
