### ISSUE TITLE
Position is not kept on switching from full screen to window

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#1743]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

During the full screen watch I tap Home to get to Launcher. NP is set to switch to widowed mode. At the moment position is lost and video starts from 00:00.
This happens in 80%
If i use "+" to switch then the position persists

**Comment by ildar** [comment]
up

**Comment by Stypox** [comment]
This was fixed some versions ago, and is not an issue anymore
