### ISSUE TITLE
No new videos in the What's New section!

### ISSUE THREAD

**Issue by sNrVJx** [TeamNewPipe/NewPipe#1747]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Even that my subscribed channels have uploaded videos everyday, I don't see any new videos in the What's New section. How do I fix it?

**Comment by Zypherspace** [comment]
Bump

**Comment by Guduche** [comment]
I have the same problem

**Comment by TobiGr** [comment]
Please take a look at #739 and #822
