### ISSUE TITLE
[Feature Request] mark watched videos as "watched"

### ISSUE THREAD

**Issue by MaX-Lo** [TeamNewPipe/NewPipe#1750]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

One thing I noticed, is that after discovering a cool channel I often see me watching many of its videos. On NewPipe watched videos appear in the history but aren't highlighted as "watched" when scrolling through a channel or search results. For me that results in accidentally rewatching videos from time to time. You get it after like 10sec, but it's kind of annoying.

So, since NewPipe stores a history of watched videos anyway it could maybe get used for marking watched videos as such. (similar to the official Youtube site)

**Comment by jhabdas** [comment]
What if there were a cursor showing how far you scrolled within a feed like Telegram?

**Comment by MaX-Lo** [comment]
I'm not sure if I understand you correctly, so I added a little mockup. I think a little overlay on the thumbnail isn't that intruding and would already do the trick.

![np_watched_mockup](https://user-images.githubusercontent.com/16520883/45926699-d2236e80-bf26-11e8-9c7d-3d70469b2a20.jpg)

**Comment by MaX-Lo** [comment]
Nice to hear that. I did it on my fork too, but I'm not satisfied with my solution yet. Really interested in how your solution will look like.

**Comment by Jluedtke19** [comment]
How far did you get, I'm having trouble trying to get the streamhistorytable in the History Record Manager from the StreamMiniInfoItemHolder

**Comment by justanidea** [comment]
Guys have a look of #1448

**Comment by MaX-Lo** [comment]
Exactly my Point. I added the watched Label in the VideoDetailFragment.
I got so far that before you start a video the watched label gets displayed, in case you watched it already, and on related videos it gets shown as well.

**Comment by MaX-Lo** [comment]
@justanidea isn't that something different? #1448 is about marking new videos whereas this is about marking already watched videos to prevent double watching?

**Comment by woj-tek** [comment]
Instead of creating new issue I would like to suggest small addition to this one: "Mark video as watched" in Subscriptions page/view - I would like to subscribe to a number of channels but I rarely watch all videos. I could simply swipe-off items I don't want to watch.

**Comment by MaX-Lo** [comment]
Still think it would be a nice feature. Just hat no time to implement it yet...

**Comment by infinitytec** [comment]
I'd like it as well.

**Comment by Stypox** [comment]
Closing in favour of #2567 since it has more information
