### ISSUE TITLE
[Question] Interest in multiple Subscription feeds?

### ISSUE THREAD

**Issue by lquenti** [TeamNewPipe/NewPipe#1752]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [no bugs] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hey, I'd love to have multiple Subscription feeds that I can switch between music related channels and real videos. Is that in check with your interests? Any wishes/ideas how to implement it well UI-wise?

If you would be okay with it I'd do it myself and PR it.

PS: I labeled it as a question since I could implement and maintain it myself. If thats wrong, feel free to change it.

**Comment by Stypox** [comment]
Duplicate of #1437
