### ISSUE TITLE
HD videos with audio?

### ISSUE THREAD

**Issue by jhabdas** [TeamNewPipe/NewPipe#1755]
In earlier versions I was able to find more HD videos with audio. In 0.14.1 I'm only seeing 360p which is basically leading me to build a queue for later download once I can get the 720/1080+ with audio streams embedded (MP4/M4V only desired). It's there something that changed which could be causing this? I'm on a high bandwidth connection at the moment.

**Comment by theScrabi** [comment]
You mean for downloading, This is because youtube changed over the time, however @kapodamy is working on [it](https://github.com/TeamNewPipe/NewPipe/pull/1759).
