### ISSUE TITLE
Subscription count displays as a multiplication of videos amount

### ISSUE THREAD

**Issue by p00rt** [TeamNewPipe/NewPipe#1756]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When using the search option all channels report ridiculously high subscription count that seems to correlate with the amount of videos on those channels (10^4 or 10^7 x videos amount), but sub count is displayed correctly on the channel page.

![screenshot_20180923-125003](https://user-images.githubusercontent.com/10347432/45927218-ef106f80-bf2f-11e8-8719-b8edbd75dc62.png)
![screenshot_20180923-125007](https://user-images.githubusercontent.com/10347432/45927219-ef106f80-bf2f-11e8-862d-2070d44ea849.png)

**Comment by Aqueminivan** [comment]
I think this issue can be closed, the newest release of Newpipe states that subscription count has been fixed and I've verified that it is indeed fixed.
https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.14.2
