### ISSUE TITLE
Auto-play next stream only for background players

### ISSUE THREAD

**Issue by anoadragon453** [TeamNewPipe/NewPipe#1761]
I enjoy listening to music with Newpipe and having it auto-queue another tune, but enjoy less watching a video only for it to immediately change into another video, especially when no (playing next video) UI comes up. It seems as if the next video is just a new scene in the current one!

An option to only use autoplaying for the background player would be great :)

**Comment by anoadragon453** [comment]
I still want this feature! :)

**Comment by gillhash** [comment]
+1 for 
[An option to only use autoplaying for the background player]
