### ISSUE TITLE
Delete & while pause not working

### ISSUE THREAD

**Issue by Windev99** [TeamNewPipe/NewPipe#1762]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [ x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi, thanks for the hard work put in this. To reproduce this issue you should have more than 1 downloaded video.  Deleting downloads doesn't work, even if we wait for the Undo pop up to disappear. 

Also, if we PAUSE then delete the video it reappears. 
Please kindly fix this because it's so important for a smooth user experience

**Comment by TobiGr** [comment]
Should be fixed in the next version (see #1759)
