### ISSUE TITLE
60fps is removed in update v.0.14.1

### ISSUE THREAD

**Issue by H4rry523** [TeamNewPipe/NewPipe#1764]
I just updated the app, and when i downloaded a video, 
i see that there is no 60fps option. Please bring back 60fps.

**Comment by theScrabi** [comment]
Could be an issue of the removed dash streams. We try to get that running again.

**Comment by gkeegan** [comment]
I actually see the 60fps option. What is a video this happens on?

**Comment by Kahri52** [comment]
Screenshots showing the problem.
[https://imgur.com/a/Zy5mwxN](url)

**Comment by gkeegan** [comment]
Interesting... My device shows that I can download it. 

![](https://i.imgur.com/sEKukXa.jpg) 
![](https://i.imgur.com/p1UBQce.jpg)

What device are you on?

**Comment by Kahri52** [comment]
I'm using a tablet.
The brand is BLUEWAVE 8 HD

**Comment by Kahri52** [comment]
It's not working, i've adjusted the settings and reinstalled it.

**Comment by Riotous** [comment]
@theScrabi You might also want to update to Exoplayer 2.9.0 which improves high FPS performance while you're at it. 

https://github.com/google/ExoPlayer/releases/tag/r2.9.0

**Comment by theScrabi** [comment]
@karyogamy you should take a look at thr update

**Comment by Stypox** [comment]
Is this still an issue? I can't reproduce it
