### ISSUE TITLE
Big Kang Warning

### ISSUE THREAD

**Issue by 4PERTURE** [TeamNewPipe/NewPipe#1767]
I found this on XDA:
https://labs.xda-developers.com/store/app/com.gomezgutierrezd.alejandra.mini

This app violates the GPL license and there is no mention of NewPipe or the license anywhere in the app.

**Comment by comradekingu** [comment]
@4PERTURE Such issues are discussed in #539 :)

**Comment by comradekingu** [comment]
@theScrabi Here https://www.xda-developers.com/contact/#legal

**Comment by B0pol** [comment]
Duplicate of #539
