### ISSUE TITLE
Import subscriptions does not work when subscriptions file contains certain unicode characters

### ISSUE THREAD

**Issue by setzer22** [TeamNewPipe/NewPipe#1768]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I was unable to import my subscriptions file, just got a small toast with the message "Could not import subscriptions". After thinking this may have something to do with the channels I was subscribed to, I realized that I was subscribed to a channel whose name contained japanese characters: "バカスマシ" (https://www.youtube.com/user/2m42hy/videos). After unsubscribing from that channel I was able to import all my other subscriptions successfully.

I guess there is some encoding issue when trying to parse those characters, but I was unable to obtain any log, since the app doesn't crash when this happens, only the aforementioned error message is shown.

**Comment by Stypox** [comment]
Fixed in TeamNewPipe/NewPipeExtractor#160
