### ISSUE TITLE
media play button raises NP with empty PL

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#1787]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

while https://github.com/TeamNewPipe/NewPipe/issues/1542 fixed in 0.14.1 it's still not perfect: using BT headset I push "Play" and end up with NP appearing among Notifications but playlist is empty. Not good.

**Comment by theScrabi** [comment]
please post the npe.

**Comment by Stypox** [comment]
Duplicate of #1619
