### ISSUE TITLE
Share playlist or export it to text or clipboard

### ISSUE THREAD

**Issue by Moomoozer** [TeamNewPipe/NewPipe#1788]
Please add ability to Export playlists in readable text just in case Newpipe becomes blocked by YouTube and the internal playlists are inaccessible.

**Comment by theScrabi** [comment]
This is not an issue, if this really happens we can still create a program that can read the database.

**Comment by Moomoozer** [comment]
It would still be prudent to add the simple ability for the user to copy all links in a specific playlist as to avoid a repeat of any future issues that traps the users playlists inside a non functional application. Please reconsider this request thanks.

**Comment by 4ut0-M-4t** [comment]
Actually, it could be a useful feature. E.g. if one decided to watch a particular playlist on another device, sharing it via TrebleShot or some such might be required. 
Though export of a locally created playlist to M3U, XSPF or CSV file would still require time investment, so it shouldn't be a number one priority for the developers ATM.

**Comment by PaperMountainStudio** [comment]
I think it would be a great improvement, also import playlists would be interesting.

**Comment by LarusContract** [comment]
I don't know if that's exactly what is requested here, but even if not this should be something easy to implement with huge benefit: the ability to share playlists per URL. This is possible like this: 
`https://www.youtube.com/watch_videos?video_ids=**ID1**,**ID2**,etc`
ID means: youtube.com/watch?v=ID, so for `https://www.youtube.com/watch?v=av6NhDzuphU` the ID is `av6NhDzuphU`
Example: https://www.youtube.com/watch_videos?video_ids=av6NhDzuphU,kwv_pQUBiLU 
This has a cap of 50 IDs. A link like that gets very fast very long, but when this URL gets resolved, it gets shortened (example: playlist of 50 videos: https://www.youtube.com/watch?v=kwv_pQUBiLU&list=TLGGgN4wnw6MybkxODA0MjAxOQ). I wasn't able to figure out, whether there is a pattern (and if there is none how to parse this short playlist URL). Also I tried figuring out whether there is some URL-magic to combine playlists in order to bypass the 50 video limit, maybe someone smarter will find something.

**Comment by rachmadaniHaryono** [comment]
sql command to extract playlist from newpipe.db

```sql
select 
	url,
	title,
	stream_type,
	duration,
	uploader,
	streams.thumbnail_Url,
	playlists.name as playlist_name,
	playlists.thumbnail_url as playlist_thumbnail_url
from streams 
inner join playlist_stream_join on playlist_stream_join.stream_id = streams.uid
inner join playlists on playlists.uid == playlist_stream_join.playlist_id
```

i use `db browser for sqlite`.

- go to `execute sql`
- paste above code
- click play button
- export csv

**Comment by justanidea** [comment]
Ow thank you so much 🔥🔥🔥

**Comment by justanidea** [comment]
Maybe it could be something to put in Faq for people looking for this idk

**Comment by rachmadaniHaryono** [comment]
i can create a new wiki page, but maybe need better sql command as above script only tested with single playlist.

cmiiw above code only print single playlist on each `stream` record

for better playlist related data, it should be taken from `playlist_stream_join` table instead from `streams` table

something like this

```sql
select 
	streams.url,
	streams.title,
	streams.stream_type,
	streams.duration,
	streams.uploader,
	streams.thumbnail_Url,
	playlists.name as playlist_name,
	playlists.thumbnail_url as playlist_thumbnail_url
from playlist_stream_join 
inner join streams on playlist_stream_join.stream_id = streams.uid
inner join playlists on playlists.uid == playlist_stream_join.playlist_id
```

**Comment by rachmadaniHaryono** [comment]
```python
#!/usr/bin/env python3
from io import StringIO
from sqlite3 import Error
import csv
import sqlite3
import sys


def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except Error as e:
        print(e)
 
    return None


def get_rows(db_file):
    conn = create_connection(db_file)

    cmds = """
    select 
            url,
            title,
            stream_type,
            duration,
            uploader,
            streams.thumbnail_Url,
            playlists.name as playlist_name,
            playlists.thumbnail_url as playlist_thumbnail_url
    from streams 
    inner join playlist_stream_join on playlist_stream_join.stream_id = streams.uid
    inner join playlists on playlists.uid == playlist_stream_join.playlist_id
    """
    cur = conn.cursor()
    cur.execute(cmds)
    rows = cur.fetchall()
    return rows


def main(db_file):
    rows = get_rows(db_file)
    f = StringIO()
    wr = csv.writer(f)
    wr.writerow([
        'url', 'title', 'stream_type', 'duration', 'uploader',
        'stream_thumbnail_url', 'playlist_name', 'playlist_thumbnail_url'])
    for row in rows:
        wr.writerow(row)
    print(f.getvalue())


if __name__ == '__main__':
    main(sys.argv[1])
```
simple script to print csv of youtube video on playlist

usage:

```console
script.py newpipe.db
```

**Comment by redstreet** [comment]
+1 for the ability to share playlists with other users. It's quite painful now to copy and paste 25 links and have the other user click on each and add to their list.

**Comment by TheOnlyRealCoder** [comment]
This feature would be awesome for the following reasons:
1 Using it with youtube-dl or an internet download manager
2 Easier to share multiple videos with someone
3 Having a local back-up of playlists
Especially number 1 is essential to me and is keeping me from replacing the Youtube app with Newpipe.

**Comment by Stypox** [comment]
#3719 by @andrei-belkin:
#### Describe the feature you want
I believe it would be great if a NewPipe user could share a playlist they made with another NewPipe user.

Some options I'm seeing are:
1 - Assigning a random public URL (maybe temporary) to the playlist.
2 - Exporting the playlist (just that playlist, not the whole NewPipe database on the device) as a JSON file and importing it on another device.
3 - Sharing the playlist in some form (maybe the same JSON file) on the local network, without actually going into the internet.

#### Is your feature request related to a problem? Please describe it

Say, I made a playlist and want to watch it on another device. That's impossible to do at this point in time (as of June 2nd, 2020) without having to export and import the whole NewPipe database that's stored on the device, which is a privacy threat to me.

#### Additional context

N/A

#### How will you/everyone benefit from this feature?

There are multiple use cases for such a feature. Here are some of them:
- Sharing a playlist with a friend.
- Watching the playlist on another device (like an Android TV or a tablet).
- Sending the playlist to someone for a more serious matter (for example, it could be an aggregation of public videos regarding a particular topic: political speeches, TV shows, an artist album, videos serving as proof of some fact, etc).

In my case, all I want at this moment is to watch a large playlist I made (over a hundred videos) on another device (the playlist is stored on my phone and I often want to watch it on my Android TV).

**Comment by B0pol** [comment]
Someone (palmstreet on reddit / f1nbar on GitHub) made a Java program to export your playlists: 

> I made a simple tool to make it a little more convenient to export your NewPipe playlists to either a YouTube or [invidio.us](https://invidio.us) link if anyone is interested, created it mainly for myself but I figured there may be a handful of people who'd also find it interesting. (There have been intermittent issues on [invidio.us](https://invidio.us) end with linking playlists at the moment)
> 
> [https://github.com/f1nbar/PlaylistsForNewPipe](https://github.com/f1nbar/PlaylistsForNewPipe)

_[Message from palmstreets on r/NewPipe](https://reddit.com/comments/gte6pf)_

It uses Java and has a graphical interface, it might be easier to use than the SQL or python scripts above.

**Comment by mgolden356** [comment]
I would like to add that I would like the feature should it be added to be similar to the export subscriptions function: without manipulating multiple .CSV files with custom functions, the .CSV file for playlists can be exported as immediately user-friendly data.

**Comment by j0n4t** [comment]
Maybe a function that return a simple list of links for export and import might work too. Then the user can just copy/paste/share the link list to whatever app they want.

**Comment by mgolden356** [comment]
@LarusContract 
It now has a limit of 20 videos on my end :/

**Comment by LostWanita21** [comment]
Since it's an open issue, I don't know if this went anywhere since it hasn't been touched in several months but I'll chime in, I'd think thus could be a very valuable and useful function, especially for those on other instances, similar programs like Freetube, or migrating off of regular YouTube.

I'm thinking it could go either in the main content page under settings, or a sub option could be on the bookmarked playlists page, like how subscriptions are handled where the export/import is on its page.

Import Playlist:
Overwrite your current saved Playlists

Export Playlist:
Export Saved Playlists to a file

I don't know how Newpipe saves playlists, but one suggestion i found mentioned saving those as a .CSV file, which could be good as a format but alternative formats are also welcome.

I feel this could be useful for two reasons, the first being backing up playlists to another Newpipe instance without interfering with existing settings with the seperate instance, eg: sending a playlist to a friend who also uses Newpipe.

The second reason could be helpful for similar, non mobile services like Freetube, where being able to import a Newpipe playlist into a Freetube or Yotter instance, though this depends on how they save playlists compared to how Newpipe saves it

**Comment by JeffRockatansky** [comment]
@LostWanita21 [This feature](https://github.com/TeamNewPipe/NewPipe/issues/1788#issuecomment-484678883) is also important and I guess might be easily implemented.

**Comment by JeffRockatansky** [comment]
@LarusContract Do you have any news?

**Comment by jeremiah-miller** [comment]
Seems like maybe the import/export functionality from the subscriptions tab could be copied over and used for playlists too?

**Comment by Donkey-Doug** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/7680

**Comment by Feuerswut** [comment]
really just a .json autocreate and share button. Instead of sharing a link to playlist X on YouTube.com the program just makes a json/txt/whatever fits file and shares this. something like <name>.json.npl (newpipe playlist)

**Comment by Feuerswut** [comment]
> I don't know if that's exactly what is requested here, but even if not this should be something easy to implement with huge benefit: the ability to share playlists per URL. This is possible like this: `https://www.youtube.com/watch_videos?video_ids=**ID1**,**ID2**,etc` ID means: youtube.com/watch?v=ID, so for `https://www.youtube.com/watch?v=av6NhDzuphU` the ID is `av6NhDzuphU` Example: https://www.youtube.com/watch_videos?video_ids=av6NhDzuphU,kwv_pQUBiLU This has a cap of 50 IDs. A link like that gets very fast very long, but when this URL gets resolved, it gets shortened (example: playlist of 50 videos: https://www.youtube.com/watch?v=kwv_pQUBiLU&list=TLGGgN4wnw6MybkxODA0MjAxOQ). I wasn't able to figure out, whether there is a pattern (and if there is none how to parse this short playlist URL). Also I didn't figure out whether there is some URL-magic to combine playlists in order to bypass the 50 video limit, maybe someone smarter will find something. Update: Working on a PR

The Google Chrome browser supports a maximum URL length of 2 MB (2048 characters).

That would be a technical limit of 2000/12 ≈ 160 Videos; even if YouTube allowed more. Thats a start, but definetly not perfect.

If you want to do Something like share 1 playlist X to your friend who also uses Newpipe, you would send text and unnecessary or slow reparsing.
a file is easier.

And BTW.: you dont want to share a full database file BECAUSE IT CONTAINS YOUR WATCH HISTORY (PRIVATE!!).

**Comment by redstreet** [comment]
> really just a .json autocreate and share button. Instead of sharing a link to playlist X on YouTube.com the program just makes a json/txt/whatever fits file and shares this. something like .json.npl (newpipe playlist)

Yes, this please. It's simple, easy to program, just works (no external dependencies), has no privacy issues. Its content is easily verifiable because it's human readable. The file can be shared via a user's favorite messaging app.

**Comment by Donkey-Doug** [comment]
I would like a list of urls to download the videos offline.

**Comment by JeffRockatansky** [comment]
`video_ids` URL option is useful in case you want to share a local playlist w/ someone for them to watch too. Or you want to continue watching it yourself from desktop w/o Google Account.

There is no 2MB URL length limit anymore. This limitation is long gone. Unless you are still using browsers based on old Chromium. Or IE prior to v10)

**Comment by gwymor** [comment]
I wrote a Python script to export NewPipe playlists to M3U playlist files with title/uploader metadata, which may be helpful to people here: https://tilde.club/~gwymor/newpipelist/

Export your NewPipe data and use the script with the `newpipe.db` file.

``` sh
pip install newpipelist

# List playlists
newpipelist --list newpipe.db

# Export a playlist by its ID
newpipelist --playlist 123 newpipe.db >my-playlist.m3u

# Export all playlists to a directory
newpipelist --directory playlists newpipe.db
```

**Comment by Moomoozer** [comment]
> I wrote a Python script to export NewPipe playlists to M3U playlist files with title/uploader metadata, which may be helpful to people here: https://tilde.club/~gwymor/newpipelist/
> 
> Export your NewPipe data and use the script with the `newpipe.db` file.
> 
> ```shell
> pip install newpipelist
> 
> # List playlists
> newpipelist --list newpipe.db
> 
> # Export a playlist by its ID
> newpipelist --playlist 123 newpipe.db >my-playlist.m3u
> 
> # Export all playlists to a directory
> newpipelist --directory playlists newpipe.db
> ```

Thanks gwymor, after 4 years we now have a useful solution. Your script worked well. I installed Pydroid for Android to run python scripts and installed your script through the pip, then went to the terminal and ran the last command in your example on an exported newpipe data base which generated a playlist directory on my phone where I copied and pasted the plain text results into the Android app Clipto, which automatically displays each link with a description and thumbnail. I just wish the NP devs could save users the hassle of using scripts and incorporate a similar means to export links in plain text within the app itself.

**Comment by redstreet** [comment]
Thank you, @gwymor!

@Moomoozer, would you mind sharing how you exported your newpipe database on your phone?

**Comment by Moomoozer** [comment]
> Thank you, @gwymor!
> 
> @Moomoozer, would you mind sharing how you exported your newpipe database on your phone?

Convert playlists to plaintext on Android:
https://youtu.be/Ej36W3ey2AY

**Comment by redstreet** [comment]
Hmm, the video didn't show how the `newpipe.db` file came to be.

**Comment by Moomoozer** [comment]
> Hmm, the video didn't show how the `newpipe.db` file came to be.

Instructions were written in video at time index O:17

Goto newpipe > settings > contents > export database
zip file contains the "newpipe.db" 

The above should be obvious, the video is more for those who want to convert their exported database with the script gwymor wrote.

**Comment by redstreet** [comment]
Got it, thanks @Moomoozer. I'd incorrectly assumed this was the internal sqlite database, and didn't realize it was the exported database.

For others, an alternative to pydroid is installing [Termux](https://github.com/termux/), and then:
```
pkg install python
pip install newpipelist

# Then run newpipelist as usual:
newpipelist --list newpipe.db
```

Works great. Thanks again @gwymor

**Comment by dm17** [comment]
Would be very useful on android. Don't want to download an obscure app to try to do functions like this.

**Comment by AudricV** [comment]
Then you will be happy to use 0.24.0 version once it is released (the next time you want to comment, please read properly issues, including comments and their state before).
