### ISSUE TITLE
Privacy Policy Statement.

### ISSUE THREAD

**Issue by HarryHeights** [TeamNewPipe/NewPipe#1789]
Newpipe is an amazing software. I've utilized it for quite some time now and it's been really good. I felt the need to contribute to the project and I saw an opportunity to contribute in terms of documentation(creating documents) for the software. I really don't know the architecture of the software in terms of end user data collection and use. If Newpipe does collect information when the software is utilized, it'll be cool if a statement is released to create transparency between you(the developer) and end users.
I can create this document if I'm supplied the necessary informations.

Thanks!

**Comment by gkeegan** [comment]
There already is one linked in the app. It goes to this [link](https://newpipe.schabi.org/legal/privacy/)

**Comment by TobiGr** [comment]
hey @HarryHeights,

thanks for your interest in improving NewPipe. The app does not collect any data without the user's conduct. 
However, NewPipe stores following data:
- error reports which users emailed us
- information which you tell us when commenting at our blog
- anonymised server logs when visiting the NewPipe website

You can find a more detailed text [here](https://newpipe.schabi.org/legal/privacy/). As you can see, @TheAssassin already created a document containing all important information.

**Comment by gkeegan** [comment]
We should add the link to the privacy statement to the readme

**Comment by TheAssassin** [comment]
Feel free to send a PR @gkeegan. There can't be "too many" links to the privacy statement.
