### ISSUE TITLE
Negative download progress

### ISSUE THREAD

**Issue by Salamandar** [TeamNewPipe/NewPipe#1791]
Sometimes we can get a negative progress percentage. I don't know if it's due to connectivity issues or the storage being full.

Here's the problem on a friend's phone, I didn't have the problem for some time.
![image](https://user-images.githubusercontent.com/6552989/46465524-20f3c280-c7c9-11e8-89e0-338db316ad63.png)

**Comment by Stypox** [comment]
Is this still an issue after #2149 ?
