### ISSUE TITLE
[FEATURE REQUEST] Equalizer

### ISSUE THREAD

**Issue by Dougo007** [TeamNewPipe/NewPipe#1794]
First time using github.

Could this be implemented into the background music player?

http://www.kevinboone.net/android_simple_eq.html

I am using the app above but when the audio loses and regains focus, the settings are ignored.

**Comment by SDB69100** [comment]
Hi I don't work on NewPipe but there's a solution : an app called Floating Equalizer (background app, 10 bands, customizable presets, relatively lightweight for ram), it's not on Play Store anymore but you can find it on apk websites. The pro version 1.7 is working fine, you can install this version directly, no need to install the free version first and no licence procedure. I use it for the YouTube app and I've realized it works with NewPipe too and some others. Bye

**Comment by SDB69100** [comment]
... Hum but I don't know yet if the focus problem occurs with floating eq ^^

**Comment by Dougo007** [comment]
I found the issue.
Some sound eq(s) use notifications to hold the settings, otherwise they break.
I ended up finding a better app that doesn't leak data post-disabling play services (I'm mostly closed source Google free at this point).
