### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by vertigo220** [TeamNewPipe/NewPipe#1799]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

In F-Droid, the recent update showed/shows three new permissions: "This app can appear on top of other apps" and "modify or delete" and "read the contents of your SD card." However, F-Droid didn't give any warning when updating that there were new permissions. So are these new, or are they just being shown as new for some reason?

**Comment by TobiGr** [comment]
NewPipe asks for these permissions to provide you the pop-up/pip player and downloads. So these permissions are not new, unless you've updated from a really old version. Therefore I guess this is a F-Droid bug. Please do the F-Droid devs a favour and open a ticket with some more information [here](https://gitlab.com/fdroid/fdroidclient/issues/new).

**Comment by vertigo220** [comment]
Thanks. I already have a ticket open there, but it was regarding the lack of warning for new permissions. So it seems it may need to be changed. Unfortunately, I'm not sure what version I updated from. I doubt it was really old, but I really have no idea. But it's still showing them as new after updating, so I'm guessing it's a bug with that.

**Comment by TobiGr** [comment]
Yes, it seems to be a F-Droid bug. Therefore I'd say, we can close this ticket. If you have anything to add or further questions, feel free to ask.
