### ISSUE TITLE
URL not supported on all videos when using share

### ISSUE THREAD

**Issue by dasmikko** [TeamNewPipe/NewPipe#1802]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I have set the NewPipe app to open the download window when i share a youtube link with the app.

The app now fails to open download window when clicking share in the YouTube app. 

[Video](https://my.mixtape.moe/lkmoha.mp4)

**Comment by theScrabi** [comment]
Does this happen for every video?

**Comment by dasmikko** [comment]
Yup.
