### ISSUE TITLE
Could not decrypt video URL signature

### ISSUE THREAD

**Issue by duergrim** [TeamNewPipe/NewPipe#1803]
Happened on Oneplus 6, android 9.

**Comment by TobiGr** [comment]
Which NewPipe version is installed on your device?

**Comment by duergrim** [comment]
The latest version

**Comment by TobiGr** [comment]
In this case, we need some more information. Does this happen on every video? And also please convert your error report and post it below.

**Comment by duergrim** [comment]
Yes, it happens on every video. This is what it says:
{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=bkRhoGPo2is",
   "content_language": "DK",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.14.1",
   "os": "Linux Android 9 - 28",
   "time": "2018-10-10 15:13",
   "exceptions": [
      "org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function \n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:725)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:598)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:48)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:55)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3$ExtractorHelper(ExtractorHelper.java:113)\n\tat org.schabi.newpipe.util.ExtractorHelper$$Lambda$3.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4073)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14349)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4073)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \";([A-Za-z0-9_\\$]{2})\\...\\( inside of var K=function(a){if(a.data.getUint8(a.dataOffset)){var b=a.data;a=a.dataOffset+4;return 4294967296*b.getUint32(a)+b.getUint32(a+4)};\"\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:65)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:713)\n\t... 30 more\n"
   ],
   "user_comment": ""
}

**Comment by xim** [comment]
Same stack trace, same error conditions, as of recently. Using content language GB.

**Comment by zsoltherpai** [comment]
It's the second time in the past month a youtube change - I assume - breaks this..

Have you considered making parsing not hardcoded in the application? Then it could be fixed without an app release.

**Comment by theScrabi** [comment]
Maybe something special in denmark?

**Comment by infinitytec** [comment]
Same here.
US.

**Comment by duergrim** [comment]
Nope, it's not something special in Denmark. As you can see, a lot of people from different countries have this issue

**Comment by duergrim** [comment]
When do you think the bug will be fixed?

**Comment by fhchl** [comment]
Same problem here. DK but language set to GB.

**Comment by bobdenardd** [comment]
same here, french settings. got the same error with axet/vget, looks like youtube changed the html5 js code, so you'll have to change the guessing of the name of the signature function....

**Comment by TomasEkeli** [comment]
Same here, Norwegian. Seems to be all videos for a few days now, I've had to go back to the (horrible) default player.

**Comment by duergrim** [comment]
Thanks for the fix, I'll close the issue now

**Comment by stonerl** [comment]
@duergrim Why did you close this one? Nothing has been fixed, yet.

**Comment by duergrim** [comment]
Are you sure? It works for me now, but I'll reopen it

**Comment by stonerl** [comment]
The problem is that these errors can't be pinpointed to a specific video or location. Some videos crash the app and hours later can be played without any problems. Maybe I have a different error...

```
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "US",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.14.1",
   "os": "Linux Android 8.1.0 - 27",
   "time": "2018-10-19 11:27",
   "exceptions": [
      "java.lang.NumberFormatException: For input string: \"\"\n\tat java.lang.Integer.parseInt(Integer.java:620)\n\tat java.lang.Integer.parseInt(Integer.java:643)\n\tat org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:396)\n\tat org.schabi.newpipe.util.ListHelper.computeDefaultResolution(ListHelper.java:113)\n\tat org.schabi.newpipe.util.ListHelper.getDefaultResolutionIndex(ListHelper.java:40)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.setupActionBar(VideoDetailFragment.java:738)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1204)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$startLoading$6$VideoDetailFragment(VideoDetailFragment.java:866)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment$$Lambda$5.accept(Unknown Source:4)\n\tat io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)\n\tat io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)\n\tat io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)\n\tat android.os.Handler.handleCallback(Handler.java:790)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6494)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
Yra thats not the decrypt error

**Comment by stonerl** [comment]
The I'm sincerely sorry.

**Comment by TomasEkeli** [comment]
This intermittency is probably because youtube are doing A/B -testing. This may be very hard to reproduce. The error has gone away for me as well.

**Comment by infinitytec** [comment]
Gone away for me also.
