### ISSUE TITLE
Some songs skipping part way through.

### ISSUE THREAD

**Issue by ZDelta47** [TeamNewPipe/NewPipe#1804]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I have some playslists set up in my bookmarks. I usually choose one and put it in background play. There are some aongs where the it will go up to 50-70% of the song and just skip to the next. It happens a lot on the same song.

One observation I made is that it happens more often when there is a song after it which doesn't have a background play option or if YouTube removed the file.

I would prefer it finishes the song instead of skipping after playing only part of it.

**Comment by kowith337** [comment]
May duplicate to #1671 due to some videos cannot retrieve the audio only streams
> you can determine in video details and see some videos lost the function to play on background (no headphone icon)
