### ISSUE TITLE
Videos not playing anymore

### ISSUE THREAD

**Issue by mieze11111** [TeamNewPipe/NewPipe#1806]
When I try to open a video on YouTube, I only get the error message "Nicht behebbarer Wiedergabefehler aufgetreten" (I'm a german user). This problem appears in every available resolution. When I try to download the it, I get a muted video, even in supported resolutions like 720p and 360p. I think, the YouTube API changed again, because I have problems in other inofficial YouTube clients, too.

**Comment by The-Demon-Prosecutor** [comment]
Can you provide an example video in which the error occurs?
