### ISSUE TITLE
Could not load a particular video and eventually crashes

### ISSUE THREAD

**Issue by rosareven** [TeamNewPipe/NewPipe#181]
Video that failed to load: https://www.youtube.com/watch?v=zoLWLsO-ApQ

Happened to version 0.74.

Asus ZenFone 2 ZE551ML

No other videos have the same issue so far.

**Comment by ackzsel** [comment]
I also have this issue with multiple videos on 0.7.4. I reverted to 0.7.3 which solved the issue.

**Comment by Smultie** [comment]
Same here, also see https://github.com/theScrabi/NewPipe/issues/180

**Comment by prashantchawla** [comment]
+1

**Comment by theScrabi** [comment]
I could not confirm. Can you please provide a log.
