### ISSUE TITLE
Too long error message - hard to report

### ISSUE THREAD

**Issue by okan35** [TeamNewPipe/NewPipe#1811]
When there are errors, the errors are too long and you have to scroll quite a lot to be able send like literally you need to scroll down 10 seconds at least.

My suggestion is either user doesn't need to see what error app gave and just let the user report it or keep the scrollView shorter that it will fit to screen with the report button below it. If my suggestions are ok for you I could also work on this issue myself to fix.

**Comment by TobiGr** [comment]
I know that issue. I work on the error report converter to make the logs collapsible. Just wait a few days, because there are some other things I'd like to add to it.

**Comment by okan35** [comment]
oh got it. Will be waiting for it, thanks.
