### ISSUE TITLE
Compact and highest quality audio tracks are same

### ISSUE THREAD

**Issue by ritiek** [TeamNewPipe/NewPipe#1812]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I tried checking if limiting data usage returns a lower audio quality index as here:
https://github.com/TeamNewPipe/NewPipe/blob/2d17cfaf2ba0795771546bf33533745399c38935/app/src/main/java/org/schabi/newpipe/util/ListHelper.java#L68-L79
I added some debug statements and compared the output from `getMostCompactAudioIndex` and `getHighestQualityAudioIndex`, just before the return statements:
```java
boolean match = getMostCompactAudioIndex(defaultFormat, audioStreams) == getHighestQualityAudioIndex(defaultFormat, audioStreams);
System.out.println(match);
```
but this returned `true` consistently. I tested this with multiple videos but no difference. These both functions seem to behave the same, while they probably shouldn't.

This is with latest commit on dev branch (2d17cfaf2ba0795771546bf33533745399c38935).

**Comment by theScrabi** [comment]
:/ that selector is a little premature. I am a little short on time right now, so I would appreciate help :)

**Comment by ritiek** [comment]
This seems to be happening because NewPipe treats `WEBMA` and `OPUS` differently, while in reality there is only a single format `webm` with two different codec; vorbis and opus (which are `WEBMA` and `OPUS` respectively in NewPipe).

Also, most videos I've noticed, for example: https://www.youtube.com/watch?v=Uk1hv6h7O1Y usually have 5 audio streams; 1 `M4A`, 1 `WEBMA` and 3 `OPUS` (I got this by calling `.getFormat()` on each audio stream but this can also be checked using `youtube-dl -F <video-link>`).

Since, there is only one stream each for M4A and WEBMA, it doesn't matter whether we choose the best or the lowest quality. We'll always end up with the same audio stream for a specific audio format. Also, it seems we are ignoring all `OPUS` audio format streams and only accepting either `M4A` or `WEBMA` audio formats in NewPipe.

I am not sure what's the best solution here. What do you guys think?

**Comment by opusforlife2** [comment]
@kapodamy Was this not fixed by your PR?

**Comment by kapodamy** [comment]
Is already fixed,i do not remember on what PR. maybe in the OGG muxer implementation

**Comment by opusforlife2** [comment]
Thanks!
