### ISSUE TITLE
trending videos on there previous search

### ISSUE THREAD

**Issue by Praveen0899** [TeamNewPipe/NewPipe#1813]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Praveen0899** [comment]
only the top trending videos are available .I suggest to  develope the trending videos based on the countries, states and languages

**Comment by TobiGr** [comment]
The trending videos are based on your content country which you can set in the settings > content > content country.

**Comment by TobiGr** [comment]
I hope this is what you wanted to know. If you mean something different, please change the title and give a more detailed description. 

Btw. the content country setting also applies to the search, recommend and next videos.
