### ISSUE TITLE
Documentation. 

### ISSUE THREAD

**Issue by princekelly1** [TeamNewPipe/NewPipe#1817]
Hello, I'm Kelly
I think having a privacy policy statement will be a good thing for your project seeing it kind of have functionalities that may lead to data collection on your end or not. It's a good end users are made aware of the safety of their privacy. I could draft a privacy policy statement if you wish. It's my way of contributing to open source projects.
The wiki section can also benefit from having a FAQ page. 
If I may

**Comment by TobiGr** [comment]
I've added a link to the privacy policy in #1800.

I am working on a FAQ. You can find an early state [here](https://newpipe.schabi.org/FAQ/). Once it is finished, placing a link to it in wiki will suffice.

I really need help writing the FAQ because there is still a bunch of interesting things left. If you are interested, please tell me.

**Comment by TobiGr** [comment]
Nice!
As a developer, I am quite familiar with NewPipe's features and partly hidden improvements.
We have an [ongoing discussion](https://github.com/TeamNewPipe/website/issues/69) over at our website repository where we gathered a bunch of FAQ and tutorial topics. I'll update the list and mark implemented things. However until this is done, you can do use a favour and tell us the features which are not user-friendly or hard to discover.
Additionally, @saderror256 submitted some FAQ drafts, too. You can find them here: https://github.com/TeamNewPipe/website/issues/100 They need a review such as all the other FAQ posts which you can find online.

And thank you again for your interest in improving these tiny, but important parts of NewPipe!

**Comment by princekelly1** [comment]
Below, I have made a draft suitable for use on the project's github profile. Which can easily be adapted to the app's website.
If you like this draft. I will keep working on the template i created.
I await your reply.


# New Pipe FAQs
## What is New pipe
Newpipe is a lightweight Youtube frontend, created for users to enjoy the original Youtube experience on their mobile device, without annoying ads and questionable permissions. With Newpipe users can download their favorite videos without expiration limits. And can share their downloaded videos to friends.

## Getting started on NewPipe
How you navigate through **NewPipe** depends on your selected video sharing app. New pipe offer users the option, to use Youtube and Soundcloud.
On your Newpipe app, look at the top left of your screen, to see your selected video sharing app. You can click on it, to choose between Youtube and Soundcloud.

## Newpipe Homepage
The Newpipe apps consist of the following main features
* Trending.
* Subscription.
* Bookmarks.
* Download.
* History.
* Settings.
* About.

<center><h2> Trending</h2><center>

The trending section of Newpipe displays, the most popular videos from Youtube at the moment. It displays a random selection of popular videos, depending on your preferred content country. The default content country on your Newpipe is the **United Kingdom**. To change your default content country, please refer to the content section under the settings guide in this FAQ document.
<center><h2> Subscription</h2><center>
This tab shows you, the list of your subscribed channels. Tap on a channel to view the list of videos on the channel.

### Import/Export
You can use this option to import and export channels from Youtube and Soundcloud.
**1.  To Import Subscription**: Tap on the import/export button, Select either Youtube or SoundCloud.
* For Youtube:
i. Go to this URL: https://www.youtube.com/subscription_manager?action_takeout=1
ii.  Log in if asked.
iii.  A download will start (that’s the export file from your Youtube profile).
iv.  Go back to your Newpipe app, and tap on the **import file** at the bottom of the page. Now, select your downloaded Youtube export file.
* For SoundCloud:
i.  Go to this URL: https://soundcloud.com/you, on a web browser (Make sure to enable desktop mode).
ii.  Log in when asked.
iii.  Copy the profile URL, you were directed to.
iv.  Go back to your Newpipe app and paste the URL in the space provided. Tap **import** at the bottom of the page.

**2.  Import from previous export**: Tap on **previous export**, to select from your previous exported files.

**3.  Export to**: This allows users to create a Json file, of their Youtube/SoundCloud subscriptions and save on their device.

**Comment by theScrabi** [comment]
Nice

**Comment by princekelly1** [comment]
Thanks, theScrabi. 
Still, have a lot of work to do. To complete it and also proofread before submitting.

**Comment by TobiGr** [comment]
I think we can close this ticket because we started a discussion on your drafts in https://github.com/TeamNewPipe/website/issues/69
