### ISSUE TITLE
[Feature request] Floating pop up video player

### ISSUE THREAD

**Issue by alpha-k** [TeamNewPipe/NewPipe#182]
Is it possible to do a floating pop up video mode, and also set it as default when opening youtube links from other applications? Would love to see a simple floating video player implementation, panel that floats anywhere.

My understanding of getting this done is to use a [Popup Window](http://developer.android.com/reference/android/widget/PopupWindow.html) control, and embedding a [VideoView ](http://developer.android.com/reference/android/widget/VideoView.html) as the main element in that window.

This will also require the app to add another permission, to draw over other apps, but would be worth it I believe! I'd actually love to contribute code but am not skilled enough to do so, maybe one day :)

**Comment by alfonsojon** [comment]
I'd love a feature like this. This would make me drop the current YouTube app in a heartbeat

**Comment by alpha-k** [comment]
Absolutely!! There used to be an app on the play store called Viral, but it was removed by el goog, because it had background (screen off) playback, which the dev was forced to remove in a newer version, but he had in the description "don't update, this newer version breaks background playback" and ultimately got delisted from the store.. I still have the titanium backup of viral so keep using it, even on marshmallow (have to manually give it permission to draw over other apps) but would love a newer, more up to date app.

There's another app using xposed called Awesome Popup Video, but it's very sluggish, feels unintuitive and requires xposed + root to do something that can realistically be done using a simple app.

**Comment by theScrabi** [comment]
@alpha-k can you ask the developer of viral, if he would like to open source his code, so the app could be made available on fdroid? Or ask him if he could at least make this code part open, so we can use it.

**Comment by theScrabi** [comment]
@alpha-k I've seen your commend on reddit. You can uncross your fingers :P I'll cross them for you now. So I've asked the developer of OGYouTube to help us: https://github.com/OsamaGhareeb/OGYouTube/issues/4

Maybe he is interested :)

**Comment by mauriciocolli** [comment]
Hey, I've been implementing this feature, and the basic part is almost done.

@theScrabi if you can create a feature branch, I can open a pull request (it'd be a cleaner way of working)

**Comment by theScrabi** [comment]
Right

**Comment by theScrabi** [comment]
@mauriciocolli [Here](https://github.com/TeamNewPipe/NewPipe/tree/floating_player) you go.

**Comment by Poussinou** [comment]
Tested and approved, works like a charm on my Android 5.1 Phone ;)

**Comment by theScrabi** [comment]
Done :) 

Again nice work
