### ISSUE TITLE
Content not available 

### ISSUE THREAD

**Issue by nidnme** [TeamNewPipe/NewPipe#1820]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by gkeegan** [comment]
YouTube was down as a whole. Newpipe is not at fault here.
