### ISSUE TITLE
Set "Limit resolution when using mobile data" video CRASH

### ISSUE THREAD

**Issue by vlatstoj** [TeamNewPipe/NewPipe#1829]
When i set "**Default resolution**" to "**Best resolution**" and "**Limit resolution when using mobile data**" to **480p**(or other XXXp), **turn on mobile data** and try playing video my newpipe always crash can't open video, when i turn OFF mobile data and turn ON WI-FI all is good. 
Can someone else confirm this? 
If needed logs or anything else tell me how to do it.

**Comment by stnby** [comment]
Same issue
Android 5.1
