### ISSUE TITLE
Could not import subscriptions

### ISSUE THREAD

**Issue by andpalmier** [TeamNewPipe/NewPipe#1839]
I tried to import Youtube subscription following the procedure in the Subscriptions section. I am able to download `subscription_manager.bin`, but, when I try to import it, an error is displayed saying "Invalid file/content source.".

**Comment by TobiGr** [comment]
IIRC this should be a XML or JSON file, not binary. Can you post a screenshot of the subscription manager page you see only?

**Comment by andpalmier** [comment]
Basically I went to this section:

![newpipe2](https://user-images.githubusercontent.com/13154679/47431417-0dba8e00-d79c-11e8-8e22-cf8f1a6ef78d.jpg)

Clicking on Youtube, it opens this page:

![newpipe1](https://user-images.githubusercontent.com/13154679/47431415-0a270700-d79c-11e8-96ff-972d4ad5863f.jpg)

And it forward me to this link: https://accounts.google.com/signin/v2/identifier?passive=true&hl=en&service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26next%3D%252Fsubscription_manager%253Faction_takeout%253D1%26app%3Ddesktop%26feature%3Dredirect_login%26hl%3Den&uilel=3&flowName=GlifWebSignIn&flowEntry=ServiceLogin

At this point, if I proceed with the login with my Youtube account, the download of the bin file starts.

**Comment by TobiGr** [comment]
That is strange. When I follow the instructions with different browsers, I get different results.
Using Chrome and Firefox, I get the `subscription_manager`, using Firefox Klar/Focus i get the `subscriptions_manager.bin` file. 

Which browser do you use?

The bad news is, I can't reproduce this bug with my subscriptions. Would you mind to upload an incorrect/invalid `subscription_manager.bin` file as `.zip` here?
Make sure to remove personal information / channels if you feel they reveal personal information about you which you do not want to see on the internet.

**Comment by andpalmier** [comment]
I am using FOSS browser with Bromite Webview and thanks to your comment I was able to download the correct file using Firefox. The bin file seems to be just the html of the login page.

Here it is:
[subscription_manager.bin.zip](https://github.com/TeamNewPipe/NewPipe/files/2522959/subscription_manager.bin.zip)

**Comment by bgoodr** [comment]
![Screenshot_20200203-191628_NewPipe](https://user-images.githubusercontent.com/141319/73711231-0d0ce900-46bb-11ea-9c36-5528a8630498.jpg)


Find the screenshot above. The error message shown was too vague. It needs to provide more text in the error message to clarify what went wrong. I found that by using Firefox on android to download the subscriptions from YouTube, the output file could not have a .bin file extension. When I used the file browser to rename it such that it did have that .bin file extension, I was able to successfully import the subscriptions. So it seems to me that there is a bug either in Firefox or in Newpipe that is not able to import the files unless it has a .bin file extension.

**Comment by T4iga** [comment]
I can still confirm the issue as of 2020. 
Tested on Fennec (not working) but
Working on Brave Browser.

**Comment by Stypox** [comment]
This is an issue with YouTube

**Comment by rokoburilo** [comment]
FreeTube imports it correctly, I don't think it's a Youtube problem.

**Comment by shoukry1** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1753#issuecomment-917820131
