### ISSUE TITLE
Now playing tab

### ISSUE THREAD

**Issue by berdzena** [TeamNewPipe/NewPipe#1841]
Please add ,,now playing,, tab

**Comment by theScrabi** [comment]
Please get further description.

**Comment by berdzena** [comment]
Ruso:
In regards to the request for adding the ‘Now playing’ function, the basic issue is that whilst choosing the option of playing in background, it is impossible to find  what is playing and where it is playing in the application. The widget on home screen gives you the option to pause/play (I am using the Niagara Launcher and it shows every single player on home screen), rewind but while clicking on the app widget it does not redirect you to the song playing. 
I search for other tracks while I play the music in background, but in case I want to go back to the song that is playing, and scroll through the suggestions I have to go to the history and find the track there. 
As much as the application itself is amazing and gives you tons of functions, which other apps do not allow, I think that this function could be very helpful. Maybe adding a page ‘Now Playing’ or a minimization option would make a user experience better. 
Thank you for your time and interest.

**Comment by theScrabi** [comment]
You can click on the notification. Here you can find the now playing screen.

**Comment by berdzena** [comment]
Thank you for the note. 
It is nice that you can go to the ‘Background Player’ at least from the notifications, but in my humble opinion it would be much practical to navigate inside the application. If I can have history, my own playlists, trending videos as pages, why should not there be a background player page, to just tap and know what’s playing inside the app. Also, the controls could be in the bottom of the application, all the time in order to pause/play/rewind while in the app for background player, not from the notification bar.

**Comment by Stypox** [comment]
Closing in favour of #2477
