### ISSUE TITLE
Can't install any version higher than 0.11.0 on Andoird 6.0.1

### ISSUE THREAD

**Issue by Plugdemholes-Imeanpatchdembugs** [TeamNewPipe/NewPipe#1846]
Have recently tried to update since this version can't resolve the changes YT made but I don't seem to be able to install any later version.
Is that intended? I think the target API level was switched after this version, any chance this has anything to do with it?

**Comment by switchtegrax1** [comment]
Did you try uninstalling your current version then installing it?

**Comment by TobiGr** [comment]
Where did you install your current version from? F-Droid or GitHub?
Which build do you want to install now?

**Comment by Plugdemholes-Imeanpatchdembugs** [comment]
Huh, look at that.
Looks like I've downloaded the versions from apkmirror.
Now downloaded the latest version from github and it works flawlessly as ever! :)
To celebrate this I'm going to watch "when you are overqualified for the job" with irony levels cranked to 11! xD
