### ISSUE TITLE
[Feature request] Add extra options under ''video & audio''

### ISSUE THREAD

**Issue by ElbowJoint** [TeamNewPipe/NewPipe#1848]
Just recently installed NewPipe and there's a few options I would like to see added for more usability, I searched for the issues so I wouldn't create a duplicate thread and found that the first one has been brought up but since it was 1,5 years ago I'll include it for the sake of it.

1. Add option to start video in windowed mode (with the same features as fullscreen has) as default rather than forcing it to fullscreen and stopping the video when you attempt to go to window
2. Add option for having Previous/Next arrows at locked screen while using background mode
3. Add option not to restart video when you launch in fullscreen, leave fullscreen and then go back into fullscreen

First issue/request I leave on Github, please have mercy sire!

**Comment by switchtegrax1** [comment]
By leaving fullscreen you mean switching to popup/background player or pressing the home button in the main player then going back to the video?

**Comment by ElbowJoint** [comment]
Pressing the home button produces the same result yeah, it causes the video to go into background mode (which is fine) but if you wanna go back into fullscreen mode it restarts it.

I was thinking more of the backspace key which returns you to the video menu after fullscreen (the menu you're in after you search for a video and click on it), it continues playing the video (without letting you interact with it) and if you click on it to go back into fullscreen it just resets the video.

I really like a lot of the features this app has but I feel like the switching between the modes is a little iffier than others (and as said a Window mode where you can interact with the video doesn't exist), I'd try to contribute some code for it but my portfolio consists of me making two shitty websites in Dreamweaver ten years ago so I doubt I could be of much use :D

**Comment by switchtegrax1** [comment]
To go back to fullscreen just tap the notification,then tap the 3 dots them switch to main,i already suggested tapping the notification to go straight back to the video instead of the playlist view but so far i got no response

**Comment by ElbowJoint** [comment]
I see, that's one way to do it! Kind of clunky though so I still think it would be easier for the user for the video to continue where its at (how it switches to background mode when you press homescreen/backspace, and when you click on the video in the app again it restarts the video), not to say it would have to be mutually exclusive and your way could be added as well.

Kinda off-topic but how difficult would it be to go through the code and implement such an option without breaking the app? As said my experience in coding is some practice in Dreamweaver and messing around a little with game files to add different character sprites and backgrounds to a game, would it be very difficult to learn to contribute at a practical level?

**Comment by switchtegrax1** [comment]
I don really know much about programming Honestly it doens't seen very difficult if you know java (you need to know java newpipe is written in java),newpipe already stores and passes playback information to other players once you switch to them,its just a matter of whenever you open the video while the background player is still on the player pass its playback state to the main player

**Comment by Stypox** [comment]
1. Duplicate, as you said
2. They now exist
3. This has been fixed

If any of the problems are still there please open a new issue, as packing problems toghether makes it difficult to find them and track progress
