### ISSUE TITLE
Part of the app pops up again for a split second after closing it/pressing on home screen

### ISSUE THREAD

**Issue by ElbowJoint** [TeamNewPipe/NewPipe#1849]
Using Android version 7.1.1

Title pretty much explains it but when you attempt to close the app/return to home screen, roughly 0.2-0.3 seconds after you return (and things are looking as they should) part of the app pops up again, stays up for another 0.2-0.3 seconds and then closes properly.

After a dozen or so tries I managed to time my screenshot to capture it. I'll try updating my version and see if the problem remains but regardless I wanted to let you know that it exists for older Android versions.
![thumbnail_screenshot_20181028-222225](https://user-images.githubusercontent.com/44555881/47622535-4f359b00-db06-11e8-843a-330d5a1b0c19.png)

**Comment by switchtegrax1** [comment]
I posted this issue months ago and even sent a video and so far i got no response

**Comment by ElbowJoint** [comment]
Is that so? I searched for the android version and none of the threads using it was about the same issue so I figured it wouldn't be a duplicate, but I guess this problem exists for multiple versions then. I initially thought that 520 open issues were quite much, I hope the original dev/s hasn't gone AWOL and moved onto other projects.

**Comment by ElbowJoint** [comment]
Since others have already made threads about it I'll just close mine then, thanks for the responses :)
