### ISSUE TITLE
F-droid version outdated

### ISSUE THREAD

**Issue by ralphioli** [TeamNewPipe/NewPipe#1853]
The current latest version on f-droid is 0.14.0. This version crashes as soon as you play a video. This issue luckily has been resolved in future versions of this app. However, those newer versions aren't on f-droid. Is there any reason for this?

**Comment by theScrabi** [comment]
You may want to refresh your data on fdroid.

**Comment by theScrabi** [comment]
Also it seems like fdroid has issues again displaying the latest version as the main one.

**Comment by theScrabi** [comment]
But 0.14.2 is online.

**Comment by WebBuddha** [comment]
The Version is not Up2date again. F-Droid is stil lshowing 16.0 instead of 16.1
