### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by stemy2** [TeamNewPipe/NewPipe#1854]
Hello,

I tried to watch a video but it crashed with this message:

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.14.2",
   "os": "Linux Android 6.0.1 - 23",
   "time": "2018-10-29 16:32",
   "exceptions": [
      "java.lang.RuntimeException: Unable to stop activity {org.schabi.newpipe\/org.schabi.newpipe.player.MainVideoPlayer}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3795)\n\tat android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)\n\tat android.app.ActivityThread.access$1500(ActivityThread.java:150)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:148)\n\tat android.app.ActivityThread.main(ActivityThread.java:5417)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)\n\tat de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)\n\tat org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)\n\tat org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)\n\tat android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1279)\n\tat android.app.Activity.performStop(Activity.java:6429)\n\tat android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3790)\n\t... 10 more\njava.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)\n\tat org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)\n\tat org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)\n\tat android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1279)\n\tat android.app.Activity.performStop(Activity.java:6429)\n\tat android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3790)\n\tat android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)\n\tat android.app.ActivityThread.access$1500(ActivityThread.java:150)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:148)\n\tat android.app.ActivityThread.main(ActivityThread.java:5417)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)\n\tat de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
Please use the crash reporter for this.
