### ISSUE TITLE
Settings layout broken

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#1866]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- I did not use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

In 0.14.2 and later the layout of the sub-setting pages is wrong. It looks like there is an additional column for icons.

<img src="https://user-images.githubusercontent.com/17365767/47961583-1b7ad980-e00e-11e8-8eff-2986bab3f437.png" width="300">

**Comment by theScrabi** [comment]
I gues this is because of the new sdk 28 we use. :/

**Comment by theScrabi** [comment]
So add icons or try to remoce the padding?

**Comment by theScrabi** [comment]
Yes you are right.

**Comment by TobiGr** [comment]
It should be possible to remove the empty space via XML
``` 
app:iconSpaceReserved="true"
```
or Java
https://developer.android.com/reference/android/preference/Preference#setIconSpaceReserved(boolean)
