### ISSUE TITLE
The application is Too slow

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#1868]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

To load my video it takes 22 seconds 
And the same video via YouTube app takes 10 seconds !
[https://www.youtube.com/embed/ZcBxSnx2rx0?ecver=1](url)

**Comment by theScrabi** [comment]
I can not confirm. Also we can not make loading faster.

**Comment by lionirdeadman** [comment]
@theScrabi This could be because NewPipe doesn't use any kind of adaptive resolution based on network connection (although this issue doesn't establish this so it's worth making a new one possibly)

**Comment by theScrabi** [comment]
yes well
