### ISSUE TITLE
[O.7.4] failed to find pattern

### ISSUE THREAD

**Issue by mdPlusPlus** [TeamNewPipe/NewPipe#187]
coming from link: https://mobile.twitter.com/darmstadt_news/status/699011786859790340

browser: fennec

screeenshot: 
![tmp_12911-screenshot_2016-02-16-07-52-32-1775866601](https://cloud.githubusercontent.com/assets/9272131/13069240/06fc6dfa-d483-11e5-847d-3567fb9f62d5.png)

**Comment by theScrabi** [comment]
This is a playlist link. These are currently not supported.

**Comment by theScrabi** [comment]
Also for me it seems wo be working now.
