### ISSUE TITLE
Open video info from a playing video

### ISSUE THREAD

**Issue by michaelPotter** [TeamNewPipe/NewPipe#1873]
When I click a YouTube link on an external site, the video starts playing in the video player. Sometimes I want to download or share this video, or see more videos from the same channel.

As far as I can tell, there is no way to open the video info page for a playing video; I always have to reopen the app and search for it. Please add a way to do this. 

I would suggest either clicking the name of the video brings you there, or adding a little circle i "info" button to the video controls at the top of the player

Thanks!

**Comment by trymeouteh** [comment]
I would like a button on the full screen player, popup player and the background player that can take you to the video page itself.

**Comment by mdnghtman** [comment]
Yeah, I've been looking for that feature as well.

**Comment by Stypox** [comment]
Implemented by #2430

**Comment by opusforlife2** [comment]
Invalid after #2907.
