### ISSUE TITLE
Automatically Play in Background As Soon As You Tap

### ISSUE THREAD

**Issue by mlgrahul98** [TeamNewPipe/NewPipe#1875]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I absolutely love NewPipe and have been using it for months about now. I've been using it primarily for listening to music, as it is very similar to YouTube Music.  The ONLY feature I wish to be added is tapping on the video and automatically playing the music in the background, instead of bringing up different options to play video, background play, popup play etc. 

There is an option for this in the "Preferred 'open' Action" in the Behavior section of Video & Audio settings, and I've set this to background player, but I am not sure why it doesn't work. 

Again, I appreciate this app and devs so much. Thank you for putting out such an amazing app!

**Comment by MaX-Lo** [comment]
The description is probably a little bit confusing. "Preferred 'open' Action" is used when opening a youtube link from outside the app. For example browsing through another app, and clicking there on a link to youtube will play the video automatically in the background with said settings.

**Comment by xXJOKRXx** [comment]
Currently you can long press any video to get a menu with some options including an option to directly play in background.

**Comment by Bluesir9** [comment]
I too would like an option to customize the "Default action" taken when a user taps on a video inside NewPipe. I use NewPipe exclusively as an audio player so it would save that extra click I guess. But it feels like a very specific use case for a very specific set of users. 

That said if people are fine with such a settings option, I would be happy to implement it. Will be simple enough.

**Comment by namboori** [comment]
> I too would like an option to customize the "Default action" taken when a user taps on a video inside NewPipe. I use NewPipe exclusively as an audio player so it would save that extra click I guess. But it feels like a very specific use case for a very specific set of users.
> 
> That said if people are fine with such a settings option, I would be happy to implement it. Will be simple enough.

If you can implement the setting option, that would make the experience better, in my opinion! You are correct, there is a small set of audience that uses NewPipe exclusively as an audio player, but it would be a huge help to those people. I love NewPipe too much to use it despite YMusic being a good option to listen to YouTube music.

**Comment by Stypox** [comment]
Closing as "won't fix", see #1910
