### ISSUE TITLE
how to change package name without error

### ISSUE THREAD

**Issue by muzahid2018** [TeamNewPipe/NewPipe#1877]
i am new in java and Android Studio, i want to modify newpipe app ,but when i try to change package name i get error about Extractor component . i fixed it buy downloading and adding extractor folder on the folder, but i get another error related to subtitles.java its not in extractor folder,
i hope you understand the issue .

please tell me which file i need to modify or edit to rename the package.

**Comment by GalAbutbul** [comment]
try use apk editor from google play store

**Comment by B0pol** [comment]
https://stackoverflow.com/questions/16804093/rename-package-in-android-studio
