### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by MuzahidGithub** [TeamNewPipe/NewPipe#1880]
I downloaded a fresh copy of newpipe and imported to android studio. but when i try to build a apk from the source it gives me some error, i haven`t touched the source code. 
i get this errors :
 1: error cannot find symbol class Subtitles 
 2: error cannot find symbol class SubtitlesFormat

I am attaching some screenshot so you can understand easily. [ images uploaded on imgur ]
https://imgur.com/8BOWYb4
https://imgur.com/H2O4H0i
https://imgur.com/hAFDcgM
https://imgur.com/7pb74fA
https://imgur.com/pVaATlq
https://imgur.com/QrkU34p
https://imgur.com/kkqCFfZ
https://imgur.com/UJXqHKH
https://imgur.com/G4bqCP6
https://imgur.com/fkHY1Ci

---------------------------------------------------------------
please give me a solution

**Comment by beNitinhere** [comment]
I think you should try to sync with gradle or restart studio after
invalidating cache.

**Comment by xonexx** [comment]
I synced and invalidated cache and restarted android studio but the error is same. 😞

**Comment by beNitinhere** [comment]
Replace your Newpipe Extractor dependency with '''implementation
'com.github.TeamNewPipe:NewPipeExtractor:32d316330c26'
''' and rebuild your project

**Comment by theScrabi** [comment]
The latest commit on the extractor is not compatible with the frontend at the moment.

**Comment by theScrabi** [comment]
If you use the commit of thr latest release it should work.

**Comment by xonexx** [comment]
Hello theScrabi 
I Didn't understand your last comment. Should I use latest release

**Comment by theScrabi** [comment]
Try to follow these instructions:
https://teamnewpipe.github.io/documentation/04_Run_changes_in_App/

But instead of using the latest commit of NewPipeExtractor use this:
```
implementation 'com.github.TeamNewPipe:NewPipeExtractor:32d316330c26'
```

It's the latest version compatible version of the NewPipeExtractor.
