### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by unknowtech** [TeamNewPipe/NewPipe#1882]
When you leave a video during playback to go to another app for example an error is displayed 

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "FR",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.14.2",
   "os": "Linux Android 7.0 - 24",
   "time": "2018-11-13 13:33",
   "exceptions": [
      "java.lang.RuntimeException: Unable to stop activity {org.schabi.newpipe\/org.schabi.newpipe.player.MainVideoPlayer}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4127)\n\tat android.app.ActivityThread.handleStopActivity(ActivityThread.java:4177)\n\tat android.app.ActivityThread.-wrap27(ActivityThread.java)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1607)\n\tat android.os.Handler.dispatchMessage(Handler.java:105)\n\tat android.os.Looper.loop(Looper.java:156)\n\tat android.app.ActivityThread.main(ActivityThread.java:6605)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)\n\tat org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)\n\tat org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)\n\tat android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1301)\n\tat android.app.Activity.performStop(Activity.java:7162)\n\tat android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4124)\n\t... 9 more\njava.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)\n\tat org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)\n\tat org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)\n\tat android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1301)\n\tat android.app.Activity.performStop(Activity.java:7162)\n\tat android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4124)\n\tat android.app.ActivityThread.handleStopActivity(ActivityThread.java:4177)\n\tat android.app.ActivityThread.-wrap27(ActivityThread.java)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1607)\n\tat android.os.Handler.dispatchMessage(Handler.java:105)\n\tat android.os.Looper.loop(Looper.java:156)\n\tat android.app.ActivityThread.main(ActivityThread.java:6605)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)\n"
   ],
   "user_comment": ""
}

**Comment by francoism90** [comment]
@theScrabi Could you please create a new release? It seems this bug has been fixed. :)
