### ISSUE TITLE
Please add support for MP3

### ISSUE THREAD

**Issue by BaumGuard** [TeamNewPipe/NewPipe#1883]
Some media players have probems with m4a. So it would be nice, if you could download audio tracks as a MP3-file.

**Comment by switchtegrax1** [comment]
The thing is YouTube doesn't give it's audio files in mp3 format and adding a converter would increase the app size significantly something the developers don't want,also most players support m4a just fine

**Comment by xlotlu** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/507
