### ISSUE TITLE
Could not find aapt2-proto.jar

### ISSUE THREAD

**Issue by tomjuggler** [TeamNewPipe/NewPipe#1889]
Gradle project sync fails. Found a solution here on Stackoverflow: 
https://stackoverflow.com/questions/52944598/could-not-find-aapt2-proto-jar
Simply put, the build.gradle repositories needs google() to be above the other repositories in order for NewPipe to compile on my Android Studio. I may be missing something here, how does everyone else get this to compile? Just moving google() to above jcenter() in both places it appears did it for me. 

- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment]
looks like google() repo was down for some while again. Wait a bit, it might work later.

**Comment by TobiGr** [comment]
This is fixed for me
