### ISSUE TITLE
Not response in 8.1 J7Prime

### ISSUE THREAD

**Issue by caogia** [TeamNewPipe/NewPipe#1890]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
Please fix it

**Comment by TobiGr** [comment]
Please give further information or we will close this ticket.

**Comment by SC1040-TS2** [comment]
Small speculation, but it could be referring to constant UX crashes when attempting to load some videos. I have encountered them occasionally.

Like @TobiGr said, this Issue needs more contextual information for it to be kept open.

**Comment by caogia** [comment]
It work perfectly after 15s times reopen app. At the first time I install newpipe, after play any video (background played) it not respone. Can not to roll or tap, even close, only close in app setting.
Now it work fine, but the Distance between title, author, like counter is unclear to see. 
Anyway it juat fine for me, hope it help for next update

**Comment by caogia** [comment]
And it oftenly crashed. For example if you open video then change to another mode popup or background it goes crashed. I'm on Oreo J7 Prime.

**Comment by caogia** [comment]
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "US",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.14.2",
   "os": "Linux Android 8.1.0 - 27",
   "time": "2018-11-25 09:01",
   "exceptions": [
      "java.lang.RuntimeException: Unable to stop activity {org.schabi.newpipe\/org.schabi.newpipe.player.MainVideoPlayer}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)\n\tat android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4652)\n\tat android.app.ActivityThread.-wrap5(Unknown Source:0)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:7000)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)\n\tat org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)\n\tat org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)\n\tat android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1383)\n\tat android.app.Activity.performStop(Activity.java:7534)\n\tat android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4591)\n\t... 9 more\njava.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference\n\tat org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)\n\tat org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)\n\tat org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)\n\tat android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1383)\n\tat android.app.Activity.performStop(Activity.java:7534)\n\tat android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4591)\n\tat android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4652)\n\tat android.app.ActivityThread.-wrap5(Unknown Source:0)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:7000)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
1. Please read the contribution guidelines.
2. use https://teamnewpipe.github.io/CrashReportToMarkdown/
