### ISSUE TITLE
glitches on downloading list with only with360dp but with canot show 1080p on list glitch htc u ultra

### ISSUE THREAD

**Issue by hawkarqadr** [TeamNewPipe/NewPipe#1895]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by hawkarqadr** [comment]
https://drive.google.com/file/d/1b5NJ6rOjnE3zEe7a1prm1-uxtyw49iOA/view?usp=drivesdk     screenshot

**Comment by TobiGr** [comment]
Where's the difference between your three tickets?
Please remove all unimportant information from the title and put it in the description.
