### ISSUE TITLE
https://drive.google.com/file/d/1b5NJ6rOjnE3zEe7a1prm1-uxtyw49iOA/view?usp=drivesdk

### ISSUE THREAD

**Issue by hawkarqadr** [TeamNewPipe/NewPipe#1896]
cannot scrool and tap 1080 yes selwct but showing list in glitch

**Comment by gkeegan** [comment]
I could not duplicate. What version of Newpipe are you on? Also what device and version of Android.

**Comment by theScrabi** [comment]
Please change the name of the issue.

**Comment by FaizKhan5** [comment]
Close this.
