### ISSUE TITLE
Broken sub counters in search results

### ISSUE THREAD

**Issue by alxthecomrade** [TeamNewPipe/NewPipe#1899]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by TobiGr** [comment]
Please give more information / post a screenshot and tell us which content country and language you have set in the options. Ideally, tell us the expected sub count  :)

**Comment by gkeegan** [comment]
Duplicate of #1672. Update Newpipe to version 14.2. If you are currently on 14.2, then please elaborate on the issue as @TobiGr said.

**Comment by alxthecomrade** [comment]
Some channels have way over 100m subs! Country of browsing: Russia
Language: English

**Comment by alxthecomrade** [comment]
Sorry for not replying so long.

I just reinstalled it a couple of days ago, and now the counters seem to be
okay. Thank you!
