### ISSUE TITLE
Search Problem

### ISSUE THREAD

**Issue by geldons** [TeamNewPipe/NewPipe#19]
Doing a search for the word "lunopolis" gives 'network error'. The actual first item on youtube that Fennec web browser shows looks to be behind a paywall. ??

**Comment by theScrabi** [comment]
That might cause the problem. Although i never head to deal with paywalls in youtube yet. Might be that this is just not yet available in my country. Please provide a log about that.

**Comment by snelltheta** [comment]
I can confirm the bug.

**Comment by theScrabi** [comment]
I can't either. But if its true that there are videos with paywall, it could possibly be that NP can't parse those properly and therefore break.

**Comment by theScrabi** [comment]
I may also need a vpn connection into USA. I see what i can do.
