### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by glebkn** [TeamNewPipe/NewPipe#1904]
Hi, my subscription feed, in NewPipe app, only shows channels, but can i see the latest videos added by this channels? I have succesfully imported the channels, but can't see the feed like original youtube does.
Need help, please!

**Comment by gkeegan** [comment]
Tap "What's new" on the top of the screen.

**Comment by glebkn** [comment]
Oh, yeah, i saw this, but it is so mixed up, can it be sorted by the correct timeline? Because i see videos from 5 years first and only some videos from today, at the bottom.

**Comment by gkeegan** [comment]
It cannot be sorted at the moment, but I have seen people bring up chronological order for the feed before. I thought someone was working on it but maybe the idea fizzled out.

**Comment by JulienPalard** [comment]
I'm +1 on the idea of sorting this "what's new" feed, I always have to visually scan the whole list to find if there's some new things to watch.

(landed on this issue while searching if it was already reported or not).

**Comment by affron** [comment]
I am also +1 on this idea and this is the only reason I am unable to switch from the youtube app/website

**Comment by TobiGr** [comment]
This bug has been reported multiple times. I'll close this in favour of  #822. We'd also like to see it fixed, but there are many other things to do, too. Every kind of help is welcome.
