### ISSUE TITLE
Rename playlist from long-press menu

### ISSUE THREAD

**Issue by sarevok-anchev** [TeamNewPipe/NewPipe#1907]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

At present it does not seem possible to rename a locally saved playlist.

If this is no oversight on my part, would it be possible to add this simple feature?

**Comment by 4ut0-M-4t** [comment]
You should open your playlist first and then tap on its name. That's all.

**Comment by prg318** [comment]
Might be a nice addition to add a rename option when you long press a playlist.  Currently long pressing a playlist only asks to delete, which led me to believe renaming playlists wasn't possible until I saw this GitHub issue

**Comment by Symbian9** [comment]
Any news on "Rename Playlist" feature?

**Comment by gkeegan** [comment]
Renaming already exists, but the only thing that could really be added would be a rename feature from the long press.


I feel like this issue should be renamed to reflect that.

@Symbian9

**Comment by Symbian9** [comment]
> Renaming already exists

How?
