### ISSUE TITLE
Short in time

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1912]
Hei Fellows,

as you might have noticed, I'm short in time again. This is due to lots of stuff that is going on
at my university. I will be fully available again after this semester ends.

@TobiGr I saw that you have been active on several Pullrequests. If you find them worthy to merge please go on.

See you guys at CCC :)

**Comment by TobiGr** [comment]
Moin,

I am also quite busy right now, but I will try my best to get those two PRs done in the next week :)
@theScrabi Did you read the message I send you on IRC last week? Unfortunately, my connection is unstable and I was not able to receive a reply because I had multiple connection timeouts.

**Comment by goxr3plus** [comment]
@theScrabi A University Student made all this,  all the time impressed by the amazing things we University students make ❤

**Comment by FaizKhan5** [comment]
I think now it's time to close this issue ticket.

**Comment by theScrabi** [comment]
Tomorrow if you want to be precise :D
