### ISSUE TITLE
Import subscriptions from YouTube not update immediately

### ISSUE THREAD

**Issue by Wang-GY** [TeamNewPipe/NewPipe#1919]
# Describe the bug  
After import Subscriptions from YouTube by a subscription_manager file, the Subscriptions page don't update immediately.

# Context  
- Device:  Nexus 5X  
- OS version: Android 8.0.0  
- App version: newest dev (1/12/2018)  

# How to reporduce?  

1. Go to  Subscriptions
![](http://ww1.sinaimg.cn/large/006lTfYGly1fxrfu4v65nj30u01hcwfn.jpg)  
2.  Select import from Youtube  
![](http://ww1.sinaimg.cn/large/006lTfYGgy1fxrfv97v9dj30u01hcabs.jpg)  
3. Go to the URL and download a file  
4. Select file and choice the file download  
![](http://ww1.sinaimg.cn/large/006lTfYGgy1fxrfwvxbo2j30u01hcdh3.jpg)  
4. The app show a toast "imported"  
![](http://ww1.sinaimg.cn/large/006lTfYGgy1fxrfymh5m2j30u01hcwgp.jpg)  

# Expected behavior  
The app should update this page immediately. In this case, it should be
![](http://ww1.sinaimg.cn/large/006lTfYGgy1fxrg03whidj30u01hcmz4.jpg)  
Only If I go to the home page and reopen the subscriptions menu, it will be updated.

**Comment by Stypox** [comment]
Related: #1013
