### ISSUE TITLE
Remove that `stale` bot

### ISSUE THREAD

**Issue by KOLANICH** [TeamNewPipe/NewPipe#1921]
Why have you introduced that bot? It just closes issues without human intervention, no matter if the issue has been fixed or not.

**Comment by jnewz** [comment]
I think there are many suggestions, and if there is a double, it saves time.

**Comment by gkeegan** [comment]
I second the removal of the bot. All it does is fill my feed of issues through the app I use to view GitHub with "this post has been marked stale". It makes it harder to see issues that have had actual people posting things.

**Comment by KOLANICH** [comment]
>I think there are many suggestions, and if there is a double, it saves time.

It doesn't. It causes time waste, confusion (marking issues which have not been implemented as closed) and garbaging the list of issues with duplicates of closed issues. Usage of issue-closing bots is the misuse of a bug-tracker.

**Comment by Somethingweirdhere** [comment]
Agreed, it closes things that are still relevant.

**Comment by gkeegan** [comment]
It is good in some regards though. It bumps old issues to the top, and if they are still an issue they can be commented on. It all depends on how long it takes from being marked stale to be officially closed.

**Comment by gkeegan** [comment]
This can be closed now since @theScrabi disabled the bot.
