### ISSUE TITLE
A few more ideas from me

### ISSUE THREAD

**Issue by jnewz** [TeamNewPipe/NewPipe#1922]
- Opening a Youtube link with New Pipe (WhatsApp and other Messager or Apps).
- My offline function has already been recorded, it would be nice if you can collect the download and then it will be downloaded with active wlan connection everything in one go
- Offline search where already downloaded local is played
- Push notification on a channel or playlist change
- A button to reload the comments later
- An option that with active wlan connection the subscribed channels are automatically downloaded in the background
- Download complete channels and playlists
- a thumbnail when downloading an audio

_a bit confused but I would be glad if there is something that makes the app even better, thanks to the developers and community for this great app_

**Comment by snappyapple632** [comment]
1) This can already be done by going into the YouTube app, clicking share and selecting NewPipe, although linking directly to NewPipe would be nice.

2) I don't think this would be possible in realtime without probing into Google's assets (not a dev so I may be wrong). A scheduled refresh would be possible but would be inefficient at best.

2.1) NewPipe doesn't load the comments section. I'm assuming you mean the description? Unless the uploaded is updating it constantly, I don't see much of a reason for this. Perhaps the slide up gesture could be used here?

2.2-3) These will have to be put aside until NewPipe gets its own download manager to replace the partially broken one it has now.

3) Ditto.

**Comment by Stypox** [comment]
Closing since all of the ideas are now either duplicate or solved
