### ISSUE TITLE
Not correct icons views 

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#1923]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
![screenshot_20181201-223422](https://user-images.githubusercontent.com/11852634/49333196-c7d2c000-f5ba-11e8-9b89-3c17b8aead50.jpg)

**Comment by TobiGr** [comment]
Please give us some more information: on what phone and Android version does this happen? What tabs have you pined to the main page?

**Comment by heberjeur** [comment]
I use zenfone 3 , Android 8.0
![screenshot_20181204-215305](https://user-images.githubusercontent.com/11852634/49472358-8b4bd200-f80f-11e8-92c5-b986a8a2f570.jpg)
![screenshot_20181204-215257](https://user-images.githubusercontent.com/11852634/49472377-969efd80-f80f-11e8-8438-c98509268a61.jpg)

**Comment by heberjeur** [comment]
When I added others tabs it appears like that
![screenshot_20181204-220141](https://user-images.githubusercontent.com/11852634/49472640-3ceb0300-f810-11e8-9328-d258523c547b.jpg)
![screenshot_20181204-220129](https://user-images.githubusercontent.com/11852634/49472659-45dbd480-f810-11e8-925c-d706e444cf7a.jpg)

**Comment by Stypox** [comment]
Closing in favour of #2438
