### ISSUE TITLE
How to import private playlists from youtube?

### ISSUE THREAD

**Issue by brentr** [TeamNewPipe/NewPipe#1926]
My daughter has hundreds of music vids in her youtube playlist.
I'm trying to switch her to using NewPipe (primarily for its background play mode)
What's the best approach to importing a large private playlist from one's Youtube account to NewPipe?
Would it appear in NewPipe as a collection of bookmarks?

**Comment by JOduMonT** [comment]
Hi, I understand the par where I'm sharing the playlist in YouTube but how I retrieve them on the NewPipe side if those are unlisted and/or not really popular ;)

**Comment by Atemu** [comment]
NewPipe should offer itself as a "share" target for any YouTube link. All you should have to do is share the playlist's URL with NewPipe. You can do that from the official YT app, your browser or any text field.

**Comment by JOduMonT** [comment]
> NewPipe should offer itself as a "share" target for any YouTube link. All you should have to do is share the playlist's URL with NewPipe. You can do that from the official YT app, your browser or any text field.

Ok I'll ease my life by installing YouTube app on my phone ;)
Thank for your quick reply
