### ISSUE TITLE
[Feature Request] Add "automatically queue next stream" On/Off Icon to playback screen

### ISSUE THREAD

**Issue by rorar** [TeamNewPipe/NewPipe#1929]
Hi there, 

As many of you I enjoy listening to stuff on YouTube to fall asleep in the evening. For example audio books or some relaxing stuff.

To not get distracted by another noisier video, I go to the settings and turn of the automatically queue... option.
In the morning I'll have to turn it on again to listen to music. 
That takes some time and the time sums up. 

That's why I strongly believe that the users definitely need a shortcut button next to "play in background" on their playback screen. 

This button has three options:
Automatically queue on
Automatically que playlist only
Automatically que off

I would really appreciate it if it will be in the next release. 

Thanks mates, will spend you a beer some time :)

**Comment by Stypox** [comment]
Fixes in #1650
