### ISSUE TITLE
NewPipe fails to see that Kore (Kodi remote) is installed

### ISSUE THREAD

**Issue by ledanisman** [TeamNewPipe/NewPipe#1930]
While it has previously worked on this installation (same version, 0.14.2 from F-Droid), NewPipe now fails to register that Kore is installed, so it's not possible to queue videos Kodi.
I've tried reinstalling both NewPipe and Kore but even with Kore open in the background, it's not recognised as being there. It used to occasionally work but has now stopped, even if I restart my phone (Mi4C, running the latest MIUI). 

- [ yes] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [yes] I checked if the issue/feature exists in the latest version.
-

**Comment by Stypox** [comment]
Is this still an issue? I assume it is caused by #1166, and if it is not then I think this is a device specific problem that can't be solved.
