### ISSUE TITLE
YouTube Music 

### ISSUE THREAD

**Issue by tdaron** [TeamNewPipe/NewPipe#1931]
Hello !
Could you include support for YouTube Music? And, if it is possible (I ask a lot) Have, in the YouTube Music part part 'Music offline' in which we would have our music downloaded, sortable by album and artists with a built-in player. Or just something like Spotify. (But with YouTube Music) If you do that, you will really be the best. But I think I'm asking too much of it 🤔😉

**Comment by lionirdeadman** [comment]
Youtube music requires a Google account with a subscription therefore it's not possible.

**Comment by Kaporos** [comment]
@lionirdeadman
We can access YouTube without Google Account, why can't we access YouTube Music?

I'did try to listen music (music.youtube.com) without account and.... I was able to listen music.

**Comment by gkeegan** [comment]
You can access YouTube music through the website without an account.  So I don't see why they wouldn't be okay with an app that can do the same.

**Comment by snappyapple632** [comment]
Hm... I haven't used YouTube Music so I guess I shouldn't have answered this.

**Comment by lionirdeadman** [comment]
Ah, I didn't know either. I guess it is possible. I had assumed there was no website because of the application requiring an account / subscription. I wonder how that works 🤔

**Comment by Kaporos** [comment]
So, is it possible? 😂

**Comment by gkeegan** [comment]
Isn't YouTube music just regular YouTube but curated so it's just music? Are the videos on youtube music available on regular YouTube?

**Comment by gkeegan** [comment]
Hm. Are the videos tagged a certain way? As in, is there a way to tell in regular youtube that the video is in YouTube music?

**Comment by lionirdeadman** [comment]
Actually. This is a #1484 duplicate.
