### ISSUE TITLE
Background crashing when i turn the screen off

### ISSUE THREAD

**Issue by lomexicano** [TeamNewPipe/NewPipe#1934]
I've got a problem with the last version of NewPipe. Since It was updated, i can't turn off the screen to listen music (background playlists).
I do It, wait 10s, the music stops for a moment (quickly), then It returns, but waiting 10, 15s the app crashes. 
After the "Quick stop", in the beggining, NewPipe is already crashed, because the music timer stops, although the sound stay running for a few more seconds.
NewPipe just restarts after crashing, when i unlock the phone, but It doesn't bring any error screen, just goes back to the main page.
Motorola Moto G5 - Android 8.1.0

**Comment by francoism90** [comment]
Think this is releated to #1920 and should have been fixed in dev.
