### ISSUE TITLE
Some videos give webm option instead of mp4 for 720p

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/NewPipe#1937]
I've recently noticed that some videos don't give the mp4 option for 720p videos anymore. https://i.imgur.com/5Vvbqwa.jpg

This is only a few videos. There doesn't appear to be a pattern to it. This could possibly break our downloading functionality at some point, as if all videos are webm, we will have no way to get sound.

**Comment by gkeegan** [comment]
It appears this only occurs in music videos.  #1759 appears like it will fix this problem with it's addition of webm muxing.

**Comment by gkeegan** [comment]
Was not fixed by that PR. (Don't want to ping it again)

**Comment by theScrabi** [comment]
We can not change it if youtube pulls back mp4 files

**Comment by gkeegan** [comment]
Yeah I figured so. Also, I just checked to see if webm is working with sound, and it is as of the dev version I have on my device, so I will close this issue.
