### ISSUE TITLE
It is not respecting the orientation

### ISSUE THREAD

**Issue by gerroon** [TeamNewPipe/NewPipe#194]
Hi

Since last upgrade (F-droid), NP is not respecting the orientation properly. Sometimes it is portrait on landscape sometimes behaves properly. I am on Lollipop.

**Comment by theScrabi** [comment]
NP saves the last orientation when you close the player activity. Do you mean that saved orientation is not working anymore? Please be more detailed.

**Comment by gerroon** [comment]
H

Yes the orientation is not respecting the devices orientation. For instance when my device is landscape, NP open in portrait then when I play a video it opens in landscape proper.

**Comment by theScrabi** [comment]
It's designed that way. You can change the orientation by clicking the orientation button.

**Comment by gerroon** [comment]
I am not talking about the video view. I am talking about the interface. 

I search for a video in landscape mode then I click on one of the results, NP goes in to portrait mode. When I click on play it goes into landscape again.

**Comment by theScrabi** [comment]
Yes this is an issue of the new UI. But since the UI isn't made by me I can't help you at the moment.  @algoprog can you please maintain that issue.

**Comment by Magissia** [comment]
The issue is blocking on laptops where there are no sensors to change orientation, because it locks the whole system to portrait when it happens.

**Comment by theScrabi** [comment]
Ok I allow rotation again. Although it's till not that perfect.
@algoprog please continue to maintain your code. You did great work, and I appreciate that. But we still have to improve some things, and I can't do it my self alone.
