### ISSUE TITLE
Background play causes UI lag

### ISSUE THREAD

**Issue by abhijitparida** [TeamNewPipe/NewPipe#1941]
Using background play causes UI lag. The lag goes away if I pause background play, but comes back when I resume playback. (Only the app UI lags; everything outside the app functions normally).

Playing videos in fullscreen or popup mode doesn't cause this issue.

NewPipe version: 0.14.2
Android version: 8.1.0
Device: Moto G5 S Plus

- [x] I checked if the issue/feature exists in the latest version.
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Octobread** [comment]
Can confirm this for android version 8.1.0 an NewPipe version 0.15.1.
