### ISSUE TITLE
Video playing in  Pop-up mode is not paused when display go to sleep

### ISSUE THREAD

**Issue by Wang-GY** [TeamNewPipe/NewPipe#1942]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
# Context  
- Device: Nexus 5X  
- OS version: Android 8.0.0  
- App version: newest dev branch (13/12/2018)

# Describe the bug  
If the video is playing in full- screen mode, when I lock the phone (shut up the display), the video will be paused. But if the video is playing in pop-up mode, lock the phone won't pause the video.  

# How to reproduce  
Play a video in pop-up mode and lock the screen.  

# Expected behavior  
The video should be paused, like full-screen mode.

**Comment by snappyapple632** [comment]
Can confirm, having the same problem on an LG VS988 on 8.0.0 with the latest NewPipe version.

**Comment by lionirdeadman** [comment]
I believe this is intended behavior. There might be the need for a setting to be made to make this optional though.

**Comment by Stypox** [comment]
Does `Settings -> Video & audio -> Minimize on app switch` suit your needs?

**Comment by mhmdanas** [comment]
I believe @Stypox's suggestion should fix this issue. If not, please make a comment and I'll re-open the issue.
