### ISSUE TITLE
Watch history can be exported after being cleaned

### ISSUE THREAD

**Issue by xwoooo** [TeamNewPipe/NewPipe#1945]
# Bug report for NewPipe

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to th em.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## Context

Device: Mi Redmi Note 5
OS version: Android 8.1.0
App version: 0.14.2

## Describe the bug

After the watch history was cleaned, I exported database and then import database and found that the history appeared again.

## How to reproduce

click Settings -> click History & cache -> click Clear watch history -> watch history is gone -> click settings -> click Content -> click Export database -> export to a file -> click Import database -> import the file -> watch history revives

## Expected behavior

Watch history disappears after it is cleared.

**Comment by theScrabi** [comment]
Its not an issue if you export the database after you cleared the history. :P

**Comment by TobiGr** [comment]
@theScrabi But that's exactly what @xwoooo did, isn't it?
