### ISSUE TITLE
Autoplay: refresh first clicked video with last played

### ISSUE THREAD

**Issue by francoism90** [TeamNewPipe/NewPipe#1948]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

It would be great to have the last played item, replacing the first clicked screen.
Let's say I'm watching 'Video 1', autoplay will play up to 'Video 5'; 'Video 1' is still the main screen when canceling/returning to player interface.

**Comment by opusforlife2** [comment]
Fixed by #2907.
