### ISSUE TITLE
Increase video limit in new/kiosk feed

### ISSUE THREAD

**Issue by francoism90** [TeamNewPipe/NewPipe#1949]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Is it possible to increase the feed limit? When scrolling to new/kiosk feed, it will eventually limit the number of videos shown, the official YT app always way more items.

Thanks!

**Comment by TobiGr** [comment]
The feed is broken atm. Please take a look at #1448 and other tickets related to the feed.
