### ISSUE TITLE
Youtube live not supported

### ISSUE THREAD

**Issue by gerroon** [TeamNewPipe/NewPipe#195]
Hi

It seems like I cant play the live vidoes. Is this a support issue?

**Comment by theScrabi** [comment]
I've never tested live streaming. Therefore its not supported right now.

**Comment by theScrabi** [comment]
Ok live streaming is now officially not supported by now.

**Comment by ZatsuneNoMokou** [comment]
It could be possible to support lives?

**Comment by theScrabi** [comment]
Yes.

**Comment by ZatsuneNoMokou** [comment]
There's still long time before it come?

**Comment by theScrabi** [comment]
Maybe. If i have to do it my self alone it might take a while.
There are other things that are more urged to take care of first.

**Comment by ZatsuneNoMokou** [comment]
I would like to help but I don't know much in android ^^

**Comment by theScrabi** [comment]
Well that might be a problem. ;P

**Comment by Zero3K** [comment]
Any news regarding the implementing of this suggestion?

**Comment by theScrabi** [comment]
Well the technology should be there now. Maybe once the refactored [extractor](https://github.com/teamnewpipe/newpipeextractor) got merged into frontend, we can face this.

**Comment by aFoxWhoIsNice** [comment]
It's been quite some time, what's the status? When can we expect this coming?

**Comment by theScrabi** [comment]
It's around the corner. Maybe within a half year.

**Comment by theScrabi** [comment]
Live stream support got added :)

https://github.com/TeamNewPipe/NewPipe/pull/1147

However it still needs to be improved and tested :)
