### ISSUE TITLE
On long press on video, add Download option.

### ISSUE THREAD

**Issue by PaperMountainStudio** [TeamNewPipe/NewPipe#1952]
I woul like you to add download option to long press menu on item. What do you think about it?

**Comment by goxr3plus** [comment]
Great Idea 💡

**Comment by Somethingweirdhere** [comment]
#1736

**Comment by Namired** [comment]
This would be great. I have been thinking of making an "issue" myself. But #1736 explains that won't happen. Also if a video wasn't available for download from simply being deleted. It would probably require more code than necessary. I don't know.
