### ISSUE TITLE
[Request] Librem 5 NewPipe

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1955]
- [yes] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

If you wonderful people havent seen the new Linux phone shipping out in a few months. Called Librem 5. Then you should totally do that before you continue reading.

My "issue" is more of a request or wish. I was wondering if you talented people could make this app into a Linux app. The Librem team told me I could give you this link so you could port this app to them

https://developer.puri.sm/Librem5

Thanks a lot. Sorry if I posted in the wrong section or whatever. Just wanted this out there!

**Comment by Namired** [comment]
Wow, please make this a thing!

**Comment by theScrabi** [comment]
We focuse on android. If another dev is interested he is wellcome to write a port for native Linux.
