### ISSUE TITLE
Support invidio.us as link opener

### ISSUE THREAD

**Issue by theel0ja** [TeamNewPipe/NewPipe#1962]
it's a site similar to hooktube, but it doesnt use embeds

https://github.com/TeamNewPipe/NewPipe/blob/67f091c73179d02433a8f8607de97e1191396510/app/src/main/AndroidManifest.xml

**Comment by fliegentoeter** [comment]
That would be great. With Invidio.us you get a real subscription page like on youtube. Something that newpipe misses. So if you could use invidio.us for subscription in a browser and open links in newpipe it would be a perfect solution...
They use the same url scheme as youtube, so all that needs to be done is change invidio.us to youtube.com if I am correct.

**Comment by delightfulagony** [comment]
Are invidio.us links supposed to work already on NewPipe?

Right now invidio.us links are not added as links supported by the app in settings.
If support for those links already exists maybe invidio.us links should be added as supported in the settings of the app.

**Comment by DrDonkey** [comment]
When you go to invidio.us and click on a video, then the popup lists a NewPipe but clicking that option results in Unsupported URL toast notification.

**Comment by github-userx** [comment]
Any Updates on this? Highly needed this Feature.

**Comment by TobiGr** [comment]
Will come with version 0.16.2. You can find a release candidate here: https://github.com/TeamNewPipe/NewPipe/pull/2312

**Comment by github-userx** [comment]
@TobiGr absolutely fantastic!
