### ISSUE TITLE
[mediaCCC] Cannot go back with hardware back button from VideoDetail

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#1965]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hey @theScrabi! Merry Christmas. 
It's great to see that you started to add support for mediaCCC ❤️ 
I tested the branch quickly and found a smaller bug which keeps me from returning to the search results. Please tell me when you need some help to get the new service implemented and released before 35c3. 

**How to reproduce:**
1. Select mediaCCC to be your current service
2. Search for something (e.g. "Daniel Kriesel")
3. Click on a search result
4. You should be able to see a video detail page
5. Use your hardware back button to go back to the search results. This does not work. Instead, the video detail page is loaded again.

**Comment by theScrabi** [comment]
Hi, I am aware of that, however any kind of development stopped when my notebook got stolen on 35c3. Now i have my semester finals, so the earlyest date I can work on NewPipe again is February.

**Comment by TobiGr** [comment]
Sure, no problem I thought that we could manage to get mediaCCC support working before or while congress. I already started to write a blog post for that release :) But I guess we can finish mediaCCC until next December.

> however any kind of development stopped when my notebook got stolen on 35c3

Yes, I read that on your Mastodon page. It's sad that they stole multiple devices. I still don't get who goes to C3 and then steals other people belongings.

**Comment by TobiGr** [comment]
#2083
