### ISSUE TITLE
Feature Request: background player forward/backward wind

### ISSUE THREAD

**Issue by nofabe** [TeamNewPipe/NewPipe#1967]
I'm not sure if this already is a feature, at least I haven't found anything yet, if it does, feel free to tell me how, but if not, I'd like to request a feature where you can precisely wind forward/backward in the background player, similar to the double tap in videos, as I have a few one-or-more-hour-long tracks where it's really hard to move to a specific part with just the bar - maybe an additional row underneath the speed and pitch option where you can select how much it'll wind and then a button for forward and one for backwards

**Comment by Namired** [comment]
Hello nofabe. 

This already works but in a different way than you would expect. You can actually do what you described. If you pull down the notification bar and click on the picture of the music you're watching. You can then slide through the video keeping it in the background. 

Sadly it requires the opening of the app.

**Comment by nofabe** [comment]
I think you misunderstood me - I already know about the progress bar, and I'm not even talking about outside of the app, but with very long videos (1hr music mixes etc) it gets really hard to navigate to a specific part, so I'd like a feature similar to the double tap in videos, where you can skip forward/backwards 10 seconds (or maybe even an adjustable amount)

**Comment by goxr3plus** [comment]
@nofabe @ghost Exactly , like VLC Player has .

**Comment by opusforlife2** [comment]
Close as implemented.
