### ISSUE TITLE
Simplify navigation to the background player activity

### ISSUE THREAD

**Issue by voidc** [TeamNewPipe/NewPipe#1976]
In my opinion it should be easier to open the background player activity during background playback.
I suggest to replace the toast, which is shown when starting background playback, with a snackbar allowing to directly open the background player activity.
Additionally a menu item might be added to the top toolbar during playback in the background which opens the  background player activity when clicked.
This would also serve as an better indicator that the background player is active besides the notification.

**Comment by voidc** [comment]
The same could be done for downloading videos. i.e. showing a snackbar allowing to open the downloads activity when starting a new download and showing an icon in the toolbar while downloads are running

**Comment by MuellerSeb** [comment]
I miss this feature, too. I always tap on the tray widget of the background player to access its playlist, which feels a bit inconvenient.

**Comment by MuellerSeb** [comment]
Ping.

**Comment by Stypox** [comment]
Closing in favour of #2477
