### ISSUE TITLE
You guys are building the best youtube frontend out there!

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#1978]
Never had such a streamlined smooth youtube experience. It's tenfolds better than the original.
Just perfect. This is the VLC to Media Player. 
No wonder there are so many copycats.
Just wanted to thank you and keep supporting this project.
Some nice comment features in pulls too!

**Comment by trymeouteh** [comment]
Yeah this is my favorite app and the app I use the most. NewPipe is more private than the official YouTube app and the ability to subscribe to channels with a Google account is great.

**Comment by marlid91** [comment]
True, a bit too many crashes and no comment support though.

**Comment by gkeegan** [comment]
Comment support is coming soon. (Just reading comments, you can't post [since there is no Google login])

**Comment by FaizKhan5** [comment]
Close this issue.
