### ISSUE TITLE
while changing from full screen to popup mode app is getting crashed

### ISSUE THREAD

**Issue by aniteshreddy** [TeamNewPipe/NewPipe#1979]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by TobiGr** [comment]
Fixed in version 0.15.0  (not yet released)
