### ISSUE TITLE
[FR] Playlist tags

### ISSUE THREAD

**Issue by 4ut0-M-4t** [TeamNewPipe/NewPipe#1982]
- [✔] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [✔] I checked if the issue/feature exists in the latest version.

It would be more reasonable to group native and local playlists by tag, than to implement something like [playlist nesting](https://github.com/TeamNewPipe/NewPipe/issues/1790) or [folder tree](https://github.com/TeamNewPipe/NewPipe/issues/1500).
E.g. _music_, _comedy_, _games_, etc. I actually meant *custom* tags.

**Comment by theScrabi** [comment]
Folder are a good idea.

**Comment by anpic** [comment]
and add field for searching by tags

**Comment by Stypox** [comment]
I think playlist folders would be better (#1313), since it makes sense to group things toghether, and for many user it would probably be a hassle to mantain tags (it takes more thinking). Closing but leaving reference in #1313 just in case.
