### ISSUE TITLE
No sound in 4 resolution while download  video In mpeg-4 Format 

### ISSUE THREAD

**Issue by tajjz** [TeamNewPipe/NewPipe#1984]
Hello newpipe Teams
We are facing a problem while downloading Videos in newpipe. There is no sound in mpeg-4 format. This 1080p,   480p ,  240, 144p Resolution Videos not downloading with sound. When i changed the default video format in setting to 3gp

Then Other Quality Videos Can be download with sound Except 480p & 1080p resolution.

Please fix this problem   ;(

**Comment by tajjz** [comment]
No sound 720p 480p and other resolution

**Comment by theScrabi** [comment]
Will be fixed soon.
