### ISSUE TITLE
1080p Downloads Don't Have Audio

### ISSUE THREAD

**Issue by mon0theist** [TeamNewPipe/NewPipe#1985]
Not sure if this is by design or if it's some sort of bug or settings/config error on my part, but only some video resolutions have audio and others don't. Notably, 1080p doesn't have audio but 720p does.

Example screenshot:
https://imgur.com/a/x50aCeq

**Comment by gkeegan** [comment]
This is known. Getting a 1080p file with audio would require muxing a video stream and an audio stream together, which hasn't been made available yet in this app, but will be soon.

**Comment by gkeegan** [comment]
See #1759, which, once implemented in a release, will allow downloads of 1080p video with audio.

**Comment by mon0theist** [comment]
Thanks
