### ISSUE TITLE
Disable automatic localization method? 

### ISSUE THREAD

**Issue by Kfatah22** [TeamNewPipe/NewPipe#1988]
Whenever I lunch the app the word "trending" changes to my local language.. Along with the 'date of posting' of each videos.. I want the app to be English with no automatic localization.. How to do so please?!

**Comment by solanav** [comment]
If your phone is in your local language, apps will automatically change to that language. But it shouldn't affect anything else.

**Comment by Kfatah22** [comment]
My phone is in English but I live in Egypt.. Trending and timing are in Arabic!!

**Comment by solanav** [comment]
This shouldn't be a NewPipe problem, but you can check the app's permissions just in case and disable GPS if its enabled.

**Comment by gkeegan** [comment]
Have you tried going to "settings>content>default content language" and setting that to English? If that fails to change it, try setting "default content country" to either US or UK.

**Comment by Kfatah22** [comment]
Thank you.

**Comment by Kfatah22** [comment]
Yes I have but it is already on English

**Comment by Kfatah22** [comment]
I was wondering if the app was created in away to change the interface
language based on my location. And if there was away to disable it.

**Comment by comradekingu** [comment]
- Download xposed from xposed.info
- Install the "app settings" module
- In the module, search for NewPipe
- Change its locale to your liking


As per, https://android.stackexchange.com/questions/29124/change-language-for-one-application-google-now-voice-recognition-root-availabl

**Comment by theScrabi** [comment]
Well then you may ned to change the devicelang, or use virtual xposed
