### ISSUE TITLE
Chash when switching from main to background player

### ISSUE THREAD

**Issue by sreejithpm92** [TeamNewPipe/NewPipe#1989]
~I have encountered two issues~

1. ~When I pause the playback in background player for a long time, and then resume the playback, the streaming is stopped after a while. I think the player fails to buffer anymore. It plays the content which is buffered before pause, and then stops.~

2. The player crashes when switched from main player to background player.

Please solve these issues in the next release.

Thanks

**Comment by Astuceman** [comment]
Have the same problem (1)

**Comment by Stypox** [comment]
1. duplicate
2. could you please send a video, or describe the steps leading to the problem? Device information, videos in queue and crash report would be appreciated, too.

**Comment by opusforlife2** [comment]
Closing until @sreejithpm92 replies.
