### ISSUE TITLE
If you use newpipe, are you at risk of deleting your app or account due to developer policy violations?

### ISSUE THREAD

**Issue by ddunddu** [TeamNewPipe/NewPipe#1990]
If you use newpipe, are you at risk of deleting your app or account due to developer policy violations?

I think Google bots are aware of the problem with how newpipe fetches data. 
Is there no problem if YouTube does not allow crawling? Do you not violate the developer's policy?
If the developer account can be terminated!
I'm sorry, I'm not good at English.

**Comment by kowith337** [comment]
I think as long as you didn't login, actually NewPipe didn't give any ability to login with Google accounts in the app itself...

So I didn't see any risks about that.

**Comment by ddunddu** [comment]
> I think as long as you didn't login, actually NewPipe didn't give any ability to login with Google accounts in the app itself...
> 
> So I didn't see any risks about that.

thank you 
Can you rest assured about web scraping?
Is this against the Youtube site and google developer policy?
You may not be able to protest even if you deleted an app or terminated an account

I think the newpipe is very good, but it is also unstable.
I need a guarantee that it's safe to use it.
As you know, once your developer account is terminated, you can not recover it.

**Comment by gkeegan** [comment]
Since Newpipe has no Google dependencies and no Google play services, it is impossible for the app to tell Google what account you are using, unless they find your IP. But they probably would not ban your account based on IP anyways, due to the possibility of it being a VPN, thus blocking hundreds of people.

**Comment by ddunddu** [comment]
> 
> 
> Since Newpipe has no Google dependencies and no Google play services, it is impossible for the app to tell Google what account you are using, unless they find your IP. But they probably would not ban your account based on IP anyways, due to the possibility of it being a VPN, thus blocking hundreds of people.

In my case, I was launching an app with newpipe library dependency to the Playstore. I am not good at English, so I think it is wrong to communicate.
I was wondering if it would be a problem by the tool of the play store team or the bot that monitors the store.
In my case, there was a problem with the Youtube rss feed parsing app using jsoup. I'm sure Bot does source code scan.
Thank you for your answer. You've been a great help.

**Comment by comradekingu** [comment]
This is both unlikely, and has yet to happen.

**Comment by theScrabi** [comment]
You may not copy and put NewPipe into playstore, if its about that. As soon as you put it there you have a contract with google, and that might get you into trouble.

**Comment by kowith337** [comment]
In another question, did NewPipe rely to YouTube API?

**Comment by theScrabi** [comment]
no.

**Comment by theScrabi** [comment]
@TobiGr maybe we should add the question about the api into the FAQ.

**Comment by TobiGr** [comment]
Yes, I can do that. I wrote that in the [main page](https://newpipe.schabi.org/#privacy) as well, but I think, it is likely to hidden for most users :)
