### ISSUE TITLE
Feature: Keep audio streamed in background

### ISSUE THREAD

**Issue by Shawn-Beltz** [TeamNewPipe/NewPipe#1991]
- [x] I carefully read the [contribution guidelines] and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Add a toggle to the background player to keep a copy of each song streamed to completion.

This would be a convenient way to download playlists without wasting or abusing bandwidth.

**Comment by gkeegan** [comment]
So basically caching (not sure if that would be the term) the audio file for a while, then if you select to download it or play it again later, the app will just play from the file?

**Comment by Stypox** [comment]
Duplicate of #478 #1179
