### ISSUE TITLE
permanently store unlink pitch and tempo flag

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#1994]
I'd like to always scale only tempo and never touch pitch.
But I need to set unlink checkmark every time.

For example VLC has separate setting for this.

**Comment by JoeTvx** [comment]
+1
Having the unlink checked as default would be the use case for 99.9% of users, I would imagine, and would also solve this issue.

**Comment by Stypox** [comment]
Duplicate of #735
