### ISSUE TITLE
option to remember playback speed

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#1995]
Please add an option to remember playback speed.

**Comment by Tikotik** [comment]
Duplicate of #1924

**Comment by 532910** [comment]
It's not exactly "duplicate".

**Comment by Stypox** [comment]
Duplicate of #735

**Comment by 532910** [comment]
It's no a duplicate of #735, but another setting.

**Comment by Stypox** [comment]
As theScrabi said there, there will be no new setting, at least not in the settings screen. Also the discussion is in #735, and even though the request is different the base problem is the same, so only one way to do this will be chosen.
