### ISSUE TITLE
Youtube Live Streams not working correctly

### ISSUE THREAD

**Issue by tecgyver** [TeamNewPipe/NewPipe#1996]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Starting today I run into troubles when watching youtube live streams on NewPipe. Live streams start at the current position (end of stream) correctly, but playback fails to continue past the first 5 seconds after the start position. When jumping to a different position in the stream the next video automatically starts (as if the stream ended). I tried it with and without inexact search and using the old player, but none of these settings fix the error.

**Comment by SC1040-TS2** [comment]
What device are you using to watch these streams, and what is your Internet connection speed?

**Comment by tico-tico** [comment]
@tecgyver same here, even in the browser (i mean just internet browser like Fx or Opera) we have some weird behaviour with live streams,  jumping slider and periodical hangs.
i guess youtube guys doing experiments on us people.

**Comment by Donpedro1** [comment]
Same issue here, can't listen to my live radio channel.. It stop just after 3 sec, background or not. Worked perfectly before. (for information I change my phone, from a xperia XZ1 compact to XZ2 compact.)
Thanks for your help :)

**Comment by tecgyver** [comment]
@SC1040-TS2 I am using a HTC U11 and have 33 Mbit/sec according to Google's speedtest.

**Comment by hypnotica420x** [comment]
i have the same problem. live streams were working until a couple of days ago. they play for about 2 seconds then stop. i can play everything else fine. i have a note 3 and a 2016 samsung Tab A. I'm using version 0.14.1 on both i believe.

**Comment by Donpedro1** [comment]
Yes latest too!

**Comment by WuvorWenda** [comment]
Yt has their live HLS streaming changed.
Project YTDL has already adapted the change.

**Comment by theScrabi** [comment]
A fix is wellcome. However time is rare for me atm. Is one other maintainer available?

**Comment by r2308145** [comment]
Can confirm livestreams are broken for me too (Android 7 Nougat).

**Comment by r2308145** [comment]
Can confirm live streams not working here aswell (Android 7 Nougat)

**Comment by angelkoh** [comment]
trying to play this live video. 
https://www.youtube.com/watch?v=hHW1oY26kxQ 

it runs for maybe 2seconds and stopped.
running on Android 8.1.0

**Comment by SC1040-TS2** [comment]
So I see, @tecgyver. In that case, it is either an issue on Google/Youtube's end, or something to that effect.

**Comment by theScrabi** [comment]
I lost kind of the overview of all issues, but I remember to have red, that just like the signature issue that happened yesterday, youtube changed the way livestreams are deliverd. Now youtube-dl seam to have fixed that already, however we still lack a fix in our extractor.

Please help if you know how to do so :)

**Comment by tecgyver** [comment]
@SC1040-TS2 It seems like it, since youtube-dl also had to adapt to fix the problem.

@theScrabi I really need to start getting into NewPipe development, but it has been a long time since I wrote something in Java and sadly time is short for me as well :-\

**Comment by WuvorWenda** [comment]
Tested with 15.0, youtube live streams still stopped after a few seconds.
The elapsed time on the left gives the total time streaming.

**Comment by yausername** [comment]
A fix is available here https://github.com/TeamNewPipe/NewPipeExtractor/pull/135

**Comment by yausername** [comment]
[here](https://anonfile.com/T7Qbfbr9b8/app-debug_apk) is the debug apk with the fix. please test.

**Comment by GaryMericano** [comment]
Yausername - the site hosting the debug apk seems to be down, mind uploading it again?

**Comment by Kirk1984** [comment]
@GaryMericano it's up here in germany.

The debug apk works perfectly! Livestreams are fine now.
