### ISSUE TITLE
Background Player Widget  won't show up on Lock screen after MIUI update.

### ISSUE THREAD

**Issue by SolaireJS** [TeamNewPipe/NewPipe#1998]
Today, right after I updated MIUI   to : **MIUI Global 10.2 | Stable**,  version: **10.2.1.0(OEIMIXM)** and attempted to play a track in NewPipe on **background player**, it didn't show up **Lock Screen** as a notification/widget to control playback without unlocking the device. (I loved this feature!)
**What I have tried:**

- _Reinstalling latest version of NewPipe from Github_.
- _Going into MIUI settings and giving permissions to NewPipe to showup on Lock Screen_.

**Device Info:**

- Redmi Note 5 Pro
- Android Version: 8.1.0 OPM1.171019.011

Thanks for this any help and this amazing app ofc !

**Comment by patelpreet422** [comment]
Are you complaining about playback control not visible on lock screen?

If yes then may be your update has revoked the permission from NewPipe to show notification on lock screen try to enable it and it should work.

**Comment by shaitaankhoopdi** [comment]
I literally wrote that I have already tried that in OP.

**Comment by opusforlife2** [comment]
@SolaireJS Is this still a problem with 0.20.0?

**Comment by SolaireJS** [comment]
The problem is fixed for my device now.

**Comment by opusforlife2** [comment]
Thanks for confirming!
