### ISSUE TITLE
support searching and browsing accounts and channels

### ISSUE THREAD

**Issue by travisfw** [TeamNewPipe/NewPipe#2]
I searched for an account I subscribe to, and I got videos from it, but out of order, and not including the latest upload. Users should be able to find and browse accounts and channels they know the name for.

**Comment by theScrabi** [comment]
Yes you are right. This feature is totally on my roadmap. But before I can implement that, I need to implement a next and related video function, witch is already in work. But it will take a while since I also have to develop some other things first. :)

**Comment by travisfw** [comment]
:) sweet

**Comment by epitron** [comment]
Just my two cents, but I personally dislike the related videos feature on YouTube. It is a huge waste of time -- I finish watching some video, then instead of returning to what I was doing, the related videos take me down some YouTube rabbit hole that burns 20 minutes of my life! :(

Playlists, on the other hand, are nice. I would definitely prefer that related videos could be turned off, or not even included. (The design would also look cleaner without them.)

**Comment by JasperWeiss** [comment]
Indeed related video's are just a way to keep people watching even if that wasn't what they initially came for.
For instance, I'm watching a video about chemistry for homework. I end up watching something competely unrelated and wasting all my time :)
As with other feature request like search history; make it optional in settings

**Comment by theScrabi** [comment]
Hm may be write, but somehow sometimes I want that. Sometimes youtube offers videos witch can only be seen if another one was seen before. Therefore related videos would be nice.

So i will implement that, but make it suppressible through preferences.

**Comment by JasperWeiss** [comment]
@theScrabi can I just point out it's "right" :) "write" means to write a letter, or to write something down

**Comment by theScrabi** [comment]
Sry I couldn't get the sleep I'd deserve. :P

**Comment by JasperWeiss** [comment]
@theScrabi Alright, don't miss out on some good sleep. Humans aren't made to code all day :)

**Comment by theScrabi** [comment]
All rifht the next version will finally feature browsing channels and users :)
But still you can't search for users.
