### ISSUE TITLE
Continuous notifications from background player

### ISSUE THREAD

**Issue by Mrhappy5** [TeamNewPipe/NewPipe#2002]
The background player, once opened from the notification drawer or when another app is being used in the foreground (e.g. Facebook, Messenger, Whatsapp etc.) on my phone, continuously pushes notifications to my Garmin watch via bluetooth.

The issue might exist for other smart watches or devices to which notifications can be sent over bluetooth, however I don't have the means to test.

The notifications only cease when the background player is left running and the device screen is switched off.  However, the notifications will restart and persist when the device screen is on and other foreground apps are in use again.

NewPipe version 0.14.2
HTC One M9 on stock ROM, Android 7.0 v4.28.401.3
Garmin VivoActive HR with Garmin Connect version 4.13.5

**Comment by theScrabi** [comment]
Yes sadly this is a known issue. Help is wellcome to fix this.

**Comment by Stypox** [comment]
This has been fixed in recent versions, as far as I know. Reopen it if that's not true
