### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by lbrunkho** [TeamNewPipe/NewPipe#2004]
how do I, or can I, build this app from source code? It has been a while since your last release and your main branch is many commits, about 61, ahead of your latest release. There are some major bug fixes that would make this app usable again for me. Mainly the bug that crashes the app when "back" is pressed from the player, and properly sorting the recent video tab.

**Comment by FaizKhan5** [comment]
Install Android Studio then use git to download source code in Android studio then create debug apk.

**Comment by FaizKhan5** [comment]
Close this issue now
