### ISSUE TITLE
Suggestion: Split song name and authors

### ISSUE THREAD

**Issue by ViniP8** [TeamNewPipe/NewPipe#2005]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

The only feature i'm missing is that the app could be able split the name of the youtube songs in two parts (with delimiter "-"), where the first part is the authors of the song, and the second part is the name of the song. (For better organization and better look at the music folder)

eg. Alan Walker - Fade [NCS Release] -> Song name: Fade [NCS RELEASE], Author: Alan Walker

Thanks for the awesome app!!

**Comment by patelpreet422** [comment]
Could you please elaborate what you actually mean?

**Comment by ViniP8** [comment]
The ideia is, when downloading a music, it would split the title of the video into two parts (name of Music and name of author) (today the music name is the full title, and the author name isn't saved)

For example:
The video: Alan Walker - Fade [NCS Release] 
Would be saved as:
Song name: Fade [NCS RELEASE]
Author: Alan Walker

Usually the part before "-" is the name of the author, and the part after is the song's name

**Comment by Stypox** [comment]
I have an implementation of this concept [here](https://gitlab.com/Stypox/song-downloader/blob/master/song-downloader/song-downloader.py#L59). It extracts song metadata (such as artist, title, remixer) as explained in the [README](https://gitlab.com/Stypox/song-downloader/blob/master/README.md).

**Comment by Stypox** [comment]
From the readme:
> Imagine a playlist (id ``1234567890abcdefghijklmnopqrstuvwx``) whose second video (id ``0a1b2c3d4e5``) is titled<br/>``ArtistName feat. Ft1 | SongName [Rel release](Remixer ft. Ft2 remix)``. [...] the song's ID3 metadata would be:

    artist: "Remixer (original by ArtistName)"
    title: "SongName (remix)"
    tracknumber: "1"
    album: "1234567890abcdefghijklmnopqrstuvwx"

> "tracknumber" is **1** because the video is the **second** one of the playlist

**Comment by Stypox** [comment]
Closing in favour of #183
