### ISSUE TITLE
Doesn't respect metered wifis

### ISSUE THREAD

**Issue by 101lols** [TeamNewPipe/NewPipe#2006]
The app doesn't treat metered wifis as mobile data.

https://developer.android.com/reference/android/support/v4/net/ConnectivityManagerCompat#isActiveNetworkMetered(android.net.ConnectivityManager)

**Comment by ThomasCr** [comment]
I have never seen, that you can define a WiFi as metered. But on my last stay in Kenya this could be nice.

**Comment by comradekingu** [comment]
Do you by any chance have
"Unlimited data use
Allow unlimited data access when data saving is turned on?" turned on?

Settings> Data use>Wi-Fi data use>NewPipe

**Comment by 101lols** [comment]
@comradekingu Yes, I'm sure that the wifi is metered and that data saving is off.

May I ask what do you mean by **for me**?
>**For me** neither NewPipe or NewPipe Beta have the ACCESS_NETWORK_STATE permission.

**Comment by def14nt** [comment]
(for him)

**Comment by theScrabi** [comment]
@comradekingu you are still using NewPipe beta O.o beta releases are dead for about 2/3 years now :D.

**Comment by comradekingu** [comment]
@theScrabi I'll stop then :)
Could upload one final "use the regular version" build maybe? I saw Stringlate doing it recently.

**Comment by theScrabi** [comment]
I would if beta was still available on fdroid, but it got removed from there.
