### ISSUE TITLE
Not compatible with Android 4.0.3

### ISSUE THREAD

**Issue by xiaomee** [TeamNewPipe/NewPipe#2027]
I cannot install the latest version 0.15.0 only the previous version can installed.

Error: There is a problem parsing the package.

Using Android 4.0.3

**Comment by kowith337** [comment]
As I remember, this app dropped support older android version than 4.4, sorry about that.

**Comment by FaizKhan5** [comment]
Kitkat or later versions

**Comment by Brimont** [comment]
@xiaomee install this https://anonfile.com/r2G4bcr0b8/NewPipe-v0.15.0-android-v4.0_apk
I have modief apk to work on old phone, i have android 4.2.1

**Comment by xiaomee** [comment]
Can install but UI crash when played video.

It seems I have to install a new rom.
Does katkiss 6.0.1 compatible with this software?

**Comment by FaizKhan5** [comment]
@xiaomee Try official version 0.15.0

**Comment by xiaomee** [comment]
@FaizKhan5  apparent this software has drop support for 4.3 and below.

**Comment by theScrabi** [comment]
There is already a fork that tries to take care of older phones.

**Comment by H1PnOT1C** [comment]
@Brimont
Thank you! :)
