### ISSUE TITLE
High latency of ui during playback of videos after update to android oreo(?) motorola moto g5s

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2028]
While other apps don't lag, the new pipe application struggles to playback videos(in the background and in the foreground).
User interface(including notification) during video playback is sluggish it often takes over 2-10secs to pause a video, close one ,loop the video or fast forward sometimes it doesn't react at all and the app shutsdown.
It also seems like the application doesn't pause during other media playback anymore on oreo.
Battery optimization turned off.
Soundcloud playback works just fine though.

**Comment by Stypox** [comment]
Is this still an issue?

**Comment by opusforlife2** [comment]
Close. Account gone.
