### ISSUE TITLE
Still can't add subscriptions via xml file (0.15 and previous versions)

### ISSUE THREAD

**Issue by wisor12** [TeamNewPipe/NewPipe#2029]
I still can't add my subscriptions no matter what I try and believe me I tried everything and more. (downloading the subscription_manager.xml via my desktop, some mild editing etc.)

My guess is NewPipe still has issues with special characters/symbols within the sub names. (I follow japanese/russian channels with Kanji/Cyrillic in it)

That or it can't handle a high subscription number (subscribed to 551 channels)

**Comment by Legion495** [comment]
Same boat.

**Comment by voss** [comment]
Just came across this issue. It used to work for me, but now it won't. Will try to check my subscription file for special characters etc, and see if that helps.

**Comment by Kesefon** [comment]
For me the issue was a banned channel. 
```
<outline text="" title="" type="rss" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC__OCxukGKoA7rxav7aOk4Q" />
```

**Comment by Legion495** [comment]
> For me the issue was a banned channel.
> 
> ```
> <outline text="" title="" type="rss" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC__OCxukGKoA7rxav7aOk4Q" />
> ```

Indeed blocked channel. Nice.

**Comment by mauriciocolli** [comment]
Closing in favor of #2226.
