### ISSUE TITLE
JellyBean maintenance fork & questions

### ISSUE THREAD

**Issue by friendlyanon** [TeamNewPipe/NewPipe#2033]
I'd like to keep maintaining a [JB compatibility fork of this project](https://github.com/friendlyanon/newpipe-jb) and I'd like to know if the GDPR laws apply to me as an individual in regards to the crash report.  
Furthermore, if you have any comments on what I else should be taken care of in this regard, then please do let me know.

**Comment by theScrabi** [comment]
No gdpr for you. You are not storing informetion on a website or so.

**Comment by theScrabi** [comment]
Also not much, however keep in mind that you will want to bring the legecy player back which i removed in 0.15.0.

**Comment by Brimont** [comment]
@theScrabi the version 0.15.0 is 100% compatible with android 4.2 . next versione you re add android 4.2?

**Comment by friendlyanon** [comment]
@theScrabi well the idea was to rewrite the existing email address where the crash reports are sent to an email I set up, so technically I do plan on storing and processing info via a 3rd party?  
Also, not sure what the `old player` was for yet, but I just compiled and built 0.15.0 for my 4.3 phone and everything works dandy on default settings.

@Brimont even though you are right, please keep these kind of comments out of this issue.

**Comment by Brimont** [comment]
@friendlyanon watch my comment https://github.com/TeamNewPipe/NewPipe/issues/2027
Download apk and install my apk. I ha ve tester on android 4.2.1

**Comment by theScrabi** [comment]
@Brimont I will not bring devices older than 4.4 back because we had to test them as well. This is more or less the reason. If someone else is willing to maintain and test old devices he is welcome to do so.

**Comment by TobiGr** [comment]
Unfortunately, I didn't participate on the debate about dropping support for Jelly Bean last year, because I was busy with other things. However, I think we should support older Android versions. I'd suggest to add a new branch for this, which is maintained by other devs like @friendlyanon. This would allow us to release a legacy version of NewPipe to F-Droid using the same signing key and package name, so people using older phone can simply use it without needing to uninstall the current version. If I got this right, [F-Droid is capable of adding version with different min-SDKs](https://forum.f-droid.org/t/does-f-droid-support-separate-packages-for-different-flavors/1520/2). But we should clarify if this is still the case and how it can be achieved.

**Comment by theScrabi** [comment]
@TobiGr well I would support everyone who is trying to bring back support for older versions, however I would rather see this as a separate project with a separate maintainer. So that people of the mainline NewPipe are not responsible of handling this. I would even say this should be done in a seperate repository, but not just in a branch. This repository can be added under the hood of TeamNewPipe.

My goal however is to LEAN things a little, so we can act more swiftly.

**Comment by friendlyanon** [comment]
> I would rather see this as a separate project with a separate maintainer.

Yes, that is my intended goal, to have a backwards compatible version maintained separately. I can understand having to support legacy environments sometimes being ugly coming from the world of web. That is why I'd like to know how I should go about the crashreport feature, since GDPR is not something I had to deal with so far and I thought I would ask you guys before doing any changes.

@Brimont thank you, but I already have Android Studio set up and the 0.15.0 apk running on my phone.

**Comment by theScrabi** [comment]
let your crashes be continued to send to our servers. Except if you want to deactivate it compleatly. If you are willing to maintain, you will also get access to sentry.schabi.org

If you want to get started I will also give you a repository here.

**Comment by Brimont** [comment]
@friendlyanon @theScrabi I'm not a programmer, I just Computer enthusiast stuff but I can test the legacy app.

**Comment by friendlyanon** [comment]
@theScrabi sounds awesome! Please do contact me via the email I posted earlier to continue this discussion in a quicker fashion.

**Comment by RuthlessRuler** [comment]
Any APK  for JB atm to install and test this Version?

**Comment by TheAssassin** [comment]
> I'd like to keep maintaining a JB compatibility fork of this project and I'd like to know if the GDPR laws apply to me as an individual in regards to the crash report.

Please don't send us all your crash reports. Either set up your own (in which case you must of course set up a privacy policy etc. to conform with data protection laws such as the GDPR, we did that, too), or disable it completely. The volume of crash reports is huge, and although we filter out most non-project related reports, the amount of inbound mails doesn't have to grow more.

> No gdpr for you. You are not storing informetion on a website or so.

That's not even close to the truth. Please don't post such inept remarks, they just create issues.

Please note this is not legal advice, our project can't provide any such advice. See it as a friendly reminder, or a recommendation.

**Comment by TheAssassin** [comment]
The situation changes of course if this is becomes an "official" project. I just wanted to highlight we don't want nor support "third-party" projects based on NewPipe with sentry hosting, and I don't want to add exceptions to this rule for obvious reasons.

**Comment by theScrabi** [comment]
if @friendlyanon is willing to maintain this, and keep on it (@friendlyanon  be aware that this might sometimes become a burden) I'll be willing to work with him. I just don't want to have to take care about 4.x about my self any more. However I think if he wants to bring this on he should be one of our team :)

**Comment by SC1040-TS2** [comment]
Greetings. I notice you all have been busy figuring out what to do with this new forked NewPipe repo.

The original intent behind my asking about the deprecation of Android 4.1-4.3 Jelly Bean and eventually seeing it realized was to eventually nudge development into no longer supporting the Dalvik VM in favor of building exclusively for Android Runtime(ART), which was introduced as the default app runtime environment beginning with 5.0 Lollipop.

As a thought towards that end, this forked repo could, become a legacy fork known more clearly as NewPipe Dalvik, while the original repo focuses exclusively on ART usage onward. It could be something to consider for the 16.0 or 17.0 version release, at least.

Anyway, those are my two cents on the matter. Good day for now.

**Comment by friendlyanon** [comment]
> be aware that this might sometimes become a burden
My daily driver is a 4.3 device and I don't plan on changing that anytime soon. Not having NewPipe would be a bigger issue for me than the "burden" of maintaining a backwards compatible fork.

**Comment by SC1040-TS2** [comment]
Question for @friendlyanon: Why do you not plan on changing such a daily driver? Simply because it still works and all of that, or some other additional reason?

**Comment by friendlyanon** [comment]
Rooted stock SGS4, the L&F of the whole thing is just right for me and all I use it for is browsing the web and watching youtube. I messed around a lot with my previous Android phone (and my SE phone before that) that after I had to buy a new one I just got tired of that kinda thing, so I'd rather contribute to OSS than scrap things and set everything up again the way I'd like.

**Comment by SC1040-TS2** [comment]
Wait a minute. According to the ever unreliable Wikipedia, the S4 could be updated to 5.0 Lollipop through stock updates or have 8.1 Oreo installed with LineageOS. I presume you did not wish to do either, or simply could not?

**Comment by f1vefour** [comment]
> Wait a minute. According to the ever unreliable Wikipedia, the S4 could be updated to 5.0 Lollipop through stock updates or have 8.1 Oreo installed with LineageOS. I presume you did not wish to do either, or simply could not?

I don't see how this is relevant to this issue. It's been by experience developers don't like getting unnecessary notifications.

I have a Galaxy Tab 10.1 stuck on 4.4.2 so a Jelly Bean fork or branch is nice for a lot of people.

**Comment by Spielmops** [comment]
@ friendlyanon
It would be great, if you create a version for Jelly Bean. I have two devices with this version of Android, because they do their work - old or not old very reliable. And If I can not use them for Youtube, they would be nearly useless.

Regards,

Spielmops

**Comment by SC1040-TS2** [comment]
@f1vefour, that is exactly why it was a separate comment. That comment was handled as an aside rather than being linked to the original, relevant topic.

I had not thought of those rare but known cases where devices did not receive updates, so that bit is understandable.

**Comment by johnb-xp** [comment]
I'm using a BlackBerry Classic still because it works well for me and I love the keyboard and form factor. It's running BlackBerry 10 with a Android 4.3 runtime, and unfortunately the runtime cannot be updated.

Anyways, NewPipe is lightweight and has a great UI that works with the trackpad so I love using it on my BlackBerry. Using NewPipe is a much better experience than browsing the website. I hope this fork takes off! 🤞

**Comment by friendlyanon** [comment]
I have one more email awaiting response, after which I'll most likely be able to start working on the public legacy version of NewPipe, so stay tuned and keep an eye on [the legacy repo](https://github.com/TeamNewPipe/NewPipe-legacy).

**Comment by theScrabi** [comment]
Mail sent

**Comment by Raitsa** [comment]
Sorry to be a retard but is there an .apk file anywhere I could test out?
( I got an Android 4.2.2 system in an EV that cant be upgraded so the current NewPipe does not work on it anymore).

**Comment by johnb-xp** [comment]
> Sorry to be a retard but is there an .apk file anywhere I could test out?
> ( I got an Android 4.2.2 system in an EV that cant be upgraded so the current NewPipe v0.15.1 does not work on it anymore).

https://sites.google.com/a/vhhscougars.org/johnsearch/searchindex/newpipe-apk-for-android-jelly-bean-4-1/NewPipe-v0.15.0-android-v4.0.apk?attredirects=0&d=1
Try out this apk from "Brimont", I'm running a mirror of it because the site he uploaded it to kept giving me popups.
It's already a version behind, but it works.

**Comment by pmaziere** [comment]
I'm not doubting that @johnb-xp means well, but  please do not install packages from random sources !
I'm also waiting for this legacy version, but it is no reason to put your devices, your networks as well as others at risk.
I would advise to be patient and wait for the sources to be published on the relevant newpipe-legacy repository.

**Comment by TheAssassin** [comment]
Please be patient, we will very likely set up an F-Droid repository once this project is really starting. Right now, it's not ready for a public audience yet.

**Comment by Raitsa** [comment]
Thanks for all the help guys. 
Lets hope this version gets a good start cos the demand for it exists.

**Comment by johnb-xp** [comment]
https://sites.google.com/a/vhhscougars.org/johnsearch/searchindex/newpipe-apk-for-android-jelly-bean-4-1
I compiled 0.15.1 targeting Android 4.1, works fine on my BlackBerry Classic.

If you (understandably) don't trust me / my APK:
- Download Android Studio
- Download the source code from https://github.com/TeamNewPipe/NewPipe/releases
- Open the source in Android Studio
      - Right click the App directory
      - Choose the "module setting" option
      - Change the minAPI to 16
      - Click Apply
      - Build --> APK

I'm more of a Visual Studio guy and don't develop android apps, so I don't really know what I'm doing. Looking forward to the legacy repo!

**Comment by friendlyanon** [comment]
Kinks are in the process of being worked out, like update API endpoints and error report handling. A legacy version is pretty much official at this point.

Closing this issue since it has outlived its usefulness.
