### ISSUE TITLE
The new v0.15.0 won't install

### ISSUE THREAD

**Issue by TGWGitHub** [TeamNewPipe/NewPipe#2034]
I tried several times to no avail, screenshot: https://i.postimg.cc/fTzr0H8H/Screenshot-2019-01-19-18-10-20-1.png

My phone is Samsung A5 2015 (A500H) running Android 6.0.1

**Comment by wisor12** [comment]
Make sure to remove the previous version and have plenty of internal storage space left. Depending on the Android skin you have to have at least 1GB of storage space left. I know Huawei EMUI is pretty picky about installing when there isn't enough of ""redudant"" storage available for caching etc. (no matter if play store install or some apk, even if the install is only a few MB in size)

**Comment by TGWGitHub** [comment]
Update:

Solved the issue by first uninstalling v0.14.2 and then install the new v0.15.0

In-place updating doesn't work on my device running Android 6.0.1, though it updated fine on my other device running Android 8.1

**Comment by TGWGitHub** [comment]
@wisor12

You beat me to it haha, you're correct I had to uninstall the older then install the newer version, usually it updates fine...

Thanks buddy.

**Comment by theScrabi** [comment]
If you try to install the current version over the one on fdroid than this happens.

If you got the previous version from github as well, then i mixed up the signing keys :/

**Comment by TGWGitHub** [comment]
@theScrabi

That's exactly it! I installed the older version from F-Droid and updated to the newer of GitHub, wonder why I didn't think of that...

While on the other device the older version and newer one were both obtained from GitHub which now explains why it updated successfully.

Thanks for the clarification.

**Comment by TGWGitHub** [comment]
What backup keys? lol

**Comment by theScrabi** [comment]
My notebook got stollen on Christmas. On its disks where all the signin keys saved. I have a backup of my keys in a keepass database, but one of my keepass apps f*** up the database, and scattered the key files all over all entries. So I had to drive to my parrents place because one last backup of the signing key was saved on my moms computer. However I was not sure if that was the right one.

**Comment by MR4Y** [comment]
The whole thing of uninstalling first has nothing to do with FDroid. Android doesn't let you install older versions of apps over newer ones.

**Comment by FaizKhan5** [comment]
I think it's time to close this issue.
