### ISSUE TITLE
version on f droid not working

### ISSUE THREAD

**Issue by yannusone** [TeamNewPipe/NewPipe#2036]
Hello and thanks a lot for this great app. 
v 14.2 is absolutely not working and the only available version on f droid. Wouldn't it be better to have v 15 on f droid. I personnaly don't know how to install it in another way.

Thanks again.

**Comment by theScrabi** [comment]
@gkeegan correct.

**Comment by yannusone** [comment]
Thanks for your answer. Why not having the app directly downloadable on the webpage like before ?
