### ISSUE TITLE
Pleas add new version to F-Droid

### ISSUE THREAD

**Issue by ema-pe** [TeamNewPipe/NewPipe#2038]
Hi!

I'm a user of you application, but in the last weeks the app version 0.14.2 doesn't work anymore. It crashes when I open a video. So I download from GitHub the new version (0.15.0), and it works correctly. Please add this version to [F-Droid][0], because the last version on the website is 0.14.2.

Thanks in advance and have a good day!

[0]: https://f-droid.org/en/packages/org.schabi.newpipe/

**Comment by beskhu3epnm** [comment]
I came here just now to report the same issue. I'm angry this wasn't resolved sooner. I know several others who are also confused as to why NewPipe suddenly stopped working days ago. The developer doesn't seem to care.

**Comment by ema-pe** [comment]
@beskhu3epnm maybe you are talking about the problem with older Android versions. But I'm using LineageOS 14.1 (Android 7.1.2), NewPipe 0.14.2 doesn't work instead 0.15.0 works perfectly.

Regards the F-Droid problema, this is a issue with the packager that upload NewPipe to F-Droid. Maintainer and packager don't need to be the same person.

I found this issue on F-Droid: https://gitlab.com/fdroid/fdroiddata/issues/1509

**Comment by TobiGr** [comment]
> I came here just now to report the same issue. I'm angry this wasn't resolved sooner. I know several others who are also confused as to why NewPipe suddenly stopped working days ago. The developer doesn't seem to care.

1. @beskhu3epnm here's no need to be angry. Most NewPipe devs are students which spend their spare time on this app. We explained it in other threads multiple times: it's the end of the semester and we need to pass our exams. theScrabi for example wrote them this week. We do care about fixing bugs and bringing new versions to you. Dealing with complaints like yours does not bring us forward in any way, but rather wastes our time which we could have spent differently.
2. F-Droid updates the apps automatically. We have no influence on the current build mechanism. However, feel free to [help us by speeding it up for further releases](#1981).
