### ISSUE TITLE
Download manager enhancement suggestions

### ISSUE THREAD

**Issue by beskhu3epnm** [TeamNewPipe/NewPipe#2043]
I have some suggestions to enhance the current download manager for NewPipe.

- Hold to select multiple videos. If you want to perform the same action on multiple videos.
- Provide the option to add the video(s) to a playlist.
- Show the thumbnail of the video.

- Delete video button at the top bar. Perhaps appears once a video is selected.
- Option to shrink/enlarge the UI in both grid or list form.
- Side-swipe to clear video from the download manager.

https://my.mixtape.moe/uetfcl.png
`How the current download manager looks.`

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/962
