### ISSUE TITLE
Subscription alert feature suggestion

### ISSUE THREAD

**Issue by beskhu3epnm** [TeamNewPipe/NewPipe#2044]
How about allowing you to set selected Subscriptions to alert you of a new video upon opening NewPipe? You could tap a bell icon to be notified from your home page, or your Subscription page is changed to indicate a new video from one Channel row.

Alternatively, you receive a notification the moment they upload a new video from the notification drawer due to regular background checking. I don't know if that is possible or considered too radical to implement at this time.

**Comment by Imarok** [comment]
Would be helpful to know which issue this issue duplicates...
