### ISSUE TITLE
New Pipe cannot play any YouTube video

### ISSUE THREAD

**Issue by sreejithpm92** [TeamNewPipe/NewPipe#2051]
"Couldnot decrypt URL signature"

New Pipe is showing this message for every video. It cannot play any video now.

Please resolve the issue.

**Comment by TobiGr** [comment]
Please post error los using the crash report converter. do you use NewPipe 0.15.0?

**Comment by Hellbeholder** [comment]
I'm having the same problem, videos are not playable anymore for several days. I used F-Droid to download the app, but it hasn't been updated to 0.15 on that, so my app can't update either.

**Comment by sreejithpm92** [comment]
No I'm still using v0.14.2...i cannot find v0.15 in f-droid

**Comment by TobiGr** [comment]
The bug has been fixed. Please wait until F-Droid updated their indices.

**Comment by Ickerday** [comment]
F-Droid still doesn't have v0.15.

**Comment by Ickerday** [comment]
Update: I removed F-Droid cache and data and got the update. :)
