### ISSUE TITLE
Crush on videos with "&" in the title

### ISSUE THREAD

**Issue by deniss-s** [TeamNewPipe/NewPipe#2054]
Crush when opening videos with ampersand ("&") in the title. Will try to upload the stack trace soon.

**Comment by TobiGr** [comment]
Hello @deniss-s,
this crash is not related to the `&` in the title but a crash due to changed code on YouTube's site. We have fixed it in version 0.15.0 which you can either download from the GitHub release page. It should be build be F-Droid soon.
