### ISSUE TITLE
newpipe 0.15.0 build fail in f-droid

### ISSUE THREAD

**Issue by Anthony-Sensors** [TeamNewPipe/NewPipe#2055]
'Build.py failed on server for org.schabi.newpipe:0.15.0' 

== Installed Android Tools ==

INFO: Creating log directory
INFO: Creating temporary directory
INFO: Creating output directory
CRITICAL: Git fetch failed
==== detail begin ====
fatal: unable to access 'https://u:p@github.com/TeamNewPipe/NewPipe/': The requested URL returned error: 503
==== detail end ====

https://f-droid.org/wiki/page/org.schabi.newpipe/lastbuild_70

**Comment by theScrabi** [comment]
Lol

**Comment by Hoppaz** [comment]
Any idea who is able to fix the url @ f-droid ?

**Comment by TobiGr** [comment]
> fdroid way to update repos sucks ass

We are happy that F-Droid provides NewPipe for tons of people. They even wrote a long post about how _we_ can improve the way, NewPipe gets to you. No reason to be mad.

> Any idea who is able to fix the url @ f-droid ?

That error 503 can be translated as `service unavailable`. In other words, GitHub was down at the moment F-Droid buildserver tried to access the URL. I just checked it and I got a 200 status code when using curl. So everything is fine and the next build should succeed. 
@theScrabi Close this or wait until the app was built successfully?

**Comment by simo1994** [comment]
Build failed again, for another reason. cc @theScrabi

**Comment by TobiGr** [comment]
```
File /home/vagrant/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 28.0.3 in /home/vagrant/android-sdk/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
```

**Comment by 60Eight** [comment]
> ```
> File /home/vagrant/.android/repositories.cfg could not be loaded.
> Checking the license for package Android SDK Build-Tools 28.0.3 in /home/vagrant/android-sdk/licenses
> Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > Failed to install the following Android SDK packages as some licences have not been accepted.
>      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
> ```

[This](https://github.com/dan-v/rattlesnakeos-stack/commit/aad083b9889d795c95622c914bccdd5d73753ca0) may help.

**Comment by theScrabi** [comment]
its the buildtools version that has not been updated.

**Comment by theScrabi** [comment]
f*** that means that we need to downgrade them

**Comment by Anthony-Sensors** [comment]
build session started at 2019-01-26 01:05:56Z
    this build started at 2019-01-26 06:06:15Z
    this build completed at 2019-01-26 06:13:03Z
    fdroiddata: 0c44364d4f39ca040cafe6a814fbdbee747ecbf1
    fdroidserverid: aa47e93f36208364c25a1a2ed7622d6c20dc773d

    buildserverid: aa47e93f36208364c25a1a2ed7622d6c20dc773d

Build succeeded 

https://f-droid.org/wiki/page/org.schabi.newpipe/lastbuild_70
