### ISSUE TITLE
[Suggestion]Tell me if I've already downloaded a video when I go to download it so I don't download it twice.

### ISSUE THREAD

**Issue by Staravonjim** [TeamNewPipe/NewPipe#2063]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by TylerCarberry** [comment]
Does it not do this already? I just got a dialog when I try to download a video twice. Version 0.15.0
