### ISSUE TITLE
Music Album Matching

### ISSUE THREAD

**Issue by woorst** [TeamNewPipe/NewPipe#2071]
Search by album title then have newpipe create a playlist automatically populated with tracks in the album à la [mps-youtube](https://github.com/mps-youtube/mps-youtube/blob/0d21ac37fe9f676b4cfb21a2f12e982baa770b3c/README.rst#music-album-matching).

**Comment by opusforlife2** [comment]
Fixed? Youtube Music search has an Album option.

**Comment by Stypox** [comment]
@opusforlife2 also, this would be out of scope for newpipe

**Comment by opusforlife2** [comment]
Oh. Then I probably misunderstood what the issue is about.
