### ISSUE TITLE
Android Studio build error

### ISSUE THREAD

**Issue by 1emirozdemir** [TeamNewPipe/NewPipe#2074]
![error1](https://user-images.githubusercontent.com/35995145/51940690-c6d7d680-2423-11e9-862d-d16e0ace735a.png)
![error2](https://user-images.githubusercontent.com/35995145/51940691-c6d7d680-2423-11e9-8795-20f23ad9c6bd.png)

**Comment by theScrabi** [comment]
Weird try to pull the latest vesion, and sync gradle again.

**Comment by 1emirozdemir** [comment]
I try but dont work please help me!

**Comment by 1emirozdemir** [comment]
do you get this error!

**Comment by Stypox** [comment]
When you are asked to update gradle on the first time you open the project, answer "No"
