### ISSUE TITLE
Playback Speed UI cleanup

### ISSUE THREAD

**Issue by dardoor** [TeamNewPipe/NewPipe#2076]
The playback speed controls UI is a mess, IMO. There are too many elements, which probably nobody uses, taking up valuable space.

1. The pitch slider -- Does anyone ever use that?
2. The step selector -- This probably belongs in the settings, not in the main UI (although if you remove the rest there is space for it). Also, if you just make it, say, 10% I doubt anyone would mind.
3. The 'Unlink' checkbox -- Does anyone want to listen to pitch altered sound? Just keep the default pitch, like Youtube and every other video player does.
4. Fast forward during silence -- Sounds nice on paper, but I doubt it gets much use, since most videos don't have unnecessary silence.

The worst part of having all these elements is that when I hold the phone in landscape mode I have to scroll down to reach the "unlink" checkbox. And I have to do this with every video, because the setting is not remembered.
Some of these features, which I'm guessing 95% of people never use (points 1, 3 and 4) could perhaps be enabled in the settings, for those who want them.

BTW, this is how the old speed selector looked like:
![latest-newpipe-update-lets-you-control-the-playback-speed-of-youtube-videos-390x390_c](https://user-images.githubusercontent.com/21084776/51968350-062d1400-2472-11e9-8a74-a349bad0cb95.png)
What if (in addition to the current speed menu) this was available with "tap and hold", so that you could select one of the preset speeds very quickly?

**Comment by theScrabi** [comment]
> I just want to say I love this feature and would be greatly disappointed to see it removed.

I see it similar, I would leave it as an additional checkbox.

**Comment by connectety** [comment]
>     4. Fast forward during silence -- Sounds nice on paper, but I doubt it gets much use, since most videos don't have unnecessary silence.

I use NewPipe to listen to podcasts and this always has been a handy feature, but using the forward button to forward is always just a button push away

**Comment by Tikotik** [comment]
Related : #1536 #1823 #1924

**Comment by AntonLee** [comment]
What about instead of "tap and hold" adding extended settings menu button in old menu?
Kinda like this:
- 0.5x
- 0.75x
- 1x
- 1.25x
- 1.5x
- 1.75x
- 2x
- More settings

**Comment by TobiGr** [comment]
That's the current state. I think we can close this 
![Screenshot_20190604-120654](https://user-images.githubusercontent.com/17365767/58871449-4ae7e680-86c2-11e9-81ec-df562da6a6c4.png)

**Comment by AntonLee** [comment]
> BTW, this is how the old speed selector looked like:
> ![latest-newpipe-update-lets-you-control-the-playback-speed-of-youtube-videos-390x390_c](https://user-images.githubusercontent.com/21084776/51968350-062d1400-2472-11e9-8a74-a349bad0cb95.png)

I mean adding option to this menu to open current menu.

**Comment by Kreijstal** [comment]
don't you dare to remove fast forward on silence, lol
