### ISSUE TITLE
New version code scheme

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/NewPipe#2078]
To be able to create a proper version history in our own F-Droid repo, I need to be able to "insert" versions between the official F-Droid builds to allow for including our GitHub release APKs with a "lower version code" than it would normally have (i.e., download the APK, open it, change version code to `<previous version> + 1`, and repack the whole thing). When including the official binaries, users will then be prompted to upgrade, and we'll be compatible to F-Droid.

Please increase the version code by e.g., 10, in the future, instead of just 1.

**Comment by theScrabi** [comment]
Why? The versions released on github are the same as the once released on fdroid. There is no difference in code, they are just build by different machines (and will soon have the same signature).

**Comment by TheAssassin** [comment]
They are different:

```
2a325a24d82962e201932b3ea47d682b34ed7e40cb343f431a403d57eff1da22  NewPipe-v0.15.0.apk
5fe63e56b048fc173baa490f6666cedc6005aa20e8647b4721ea88efc830aa2c  NewPipe-v0.15.1.apk
28a546f08f141e12d5522cd990b468ec8597987961c1cad0b06a32dc6ef991d9  org.schabi.newpipe_70.apk
```

`70` == `0.15.0` in this example. The F-Droid binaries are right now just the "better" ones, as they are verified to be 100% reproducible and they also provide proper tarballs.

Generally, I'd like to be able to have some "room for maneuver", i.e., imagine I screw up something while maintaining the repo, I'd have a few chances to fix everything (e.g., wrong version shipped accidentally, I could fix the original binary and insert a "new" version pointing to the exact same release.

Most projects just don't use a 1-by-1 scheme I was told, for the reasons I named above. And technically, it doesn't make a difference for the project whether to use a distance of 1 or 10 or 1337 for every release.

**Comment by theScrabi** [comment]
The question is just this, if you are building the apps, with which key are they signed.

**Comment by TheAssassin** [comment]
That's a question for another day (we would have to sign the edited APKs with the "official" NewPipe key). This issue is about the version codes.

**Comment by TheAssassin** [comment]
> android version id (the internal version number)

... which is called version code, which is what this issue is about. I don't want to change what Android calls "version name".

**Comment by opusforlife2** [comment]
@wb9688 This was changed again right? Close as not relevant?

**Comment by TobiGr** [comment]
we went back to increasing the version code by 1

**Comment by TheAssassin** [comment]
Yeah, that surprised me a bit recently. An interval of 1 is okay now again.

**Comment by wb9688** [comment]
Recently the version codes have been pretty weird indeed.
