### ISSUE TITLE
Orbot support doesn't work

### ISSUE THREAD

**Issue by A-Shahbazi** [TeamNewPipe/NewPipe#2081]
The description page states "Orbot/Tor support (not yet directly)" as a feature. I have installed latest orbot and it's working properly(tested with other apps), however I couldn't figure out how to set newpipe to use orbot. There's neither socks nor http proxy setting in the app. If it's set up to work out of the box with orbot without changing anything(which is kind of weird) it's not working for me.

**Comment by hyphenc** [comment]
To use NewPipe with Orbot you can use Orbot's "VPN Mode" and add NewPipe as a "Tor-Enabled App", that way NewPipes traffic will go through Tor. Hope that helps.

**Comment by theScrabi** [comment]
NewPipe has not a direct orbot support anymore as data tended to slip throught that connection. However NewPipe is able to detect when you have to enter a captcha so you can use it through tor.
