### ISSUE TITLE
[0.15.1] Downloading/Muxing files cause App crash

### ISSUE THREAD

**Issue by x2k13** [TeamNewPipe/NewPipe#2087]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Downloads of need-to-be-muxed (1080p) videos crash the app right at the end of muxing, leaving the file broken:

Filename.mp4

Code 1007
Post-processing failed

java.lang.Runtime.Exception: stopped unexpectedly

Affected version is 0.15.1, 0.15.0 doesn't have this.
I know the guidelines say we shouldn't create issues here referring to crashes, but here's the catch:

Unfortunately, no .json is generated to be emailed for further investigation, so I just can describe what to do to reproduce the bug:

1. Search/open/go to any video you'd like to download that's available in at least 1080p (requires muxing, 720p versions can be downloaded "as is" which isn't usable for this scenario).

2. Tap on download, choose 1080p, hit OK.

3. Wait for the file to be downloaded, then muxed.

4. Experience a sudden FC right when muxing reaches 99,9%

5. Check the file and see that it's broken beyond repair. (Doesn't play in any player, tried VLC, MX ...)

**Comment by theScrabi** [comment]
Is there a stacktrace you could post?

**Comment by kapodamy** [comment]
In the version 0.15.1, the native android muxer is used.
according to this looks a android bug
`02-02 13:22:10.399 E/MPEG4Extractor(431): No width or height, assuming worst case 1080p`
¿or your device doesnt support the widevine drm?

**Comment by x2k13** [comment]
Well, it used to work in all versions before 0.15.1. The reason why it doesn't work anymore now is not very important to me, to me it's just important that it works again.

The latest veraion just is a constant bug fest.

**Comment by theScrabi** [comment]
x2k13 well but it is important to us, and you want to make newpipe become better you might help us. So in some sort it is important, even to you.

**Comment by x2k13** [comment]
@theScrabi well then just revert what you changed. That will make newpipe better.

**Comment by kapodamy** [comment]
please provide a full logcat aka since the video is downloading

**Comment by x2k13** [comment]
@kapodamy here you go:

https://vim.cx/?bc821b48a0dedfce#UVU4mO5fywYp9xOswnK1Bl2Q+gwGKZCoql9xpJVzabE=

**Comment by x2k13** [comment]
@theScrabi

Tested the latest 0.16.0 RC if this problem is fixed, but it still crashes at 99.9% of muxing DASH streams. Maybe the logcat I provided above helps you finding the error.

**Comment by theScrabi** [comment]
@x2k13 can you also post it in the release thread.

**Comment by x2k13** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/2114

**Comment by x2k13** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/2190

**Comment by kapodamy** [comment]
yup is a bug in android 7, requires (again) another muxer. working on it

**Comment by x2k13** [comment]
@kapodamy
Just an update, a friend of mine told me he's got the very same bug in Android 6. Apparently this is not Android 7 exclusive.

**Comment by solarelf** [comment]
Same bug with my Android Oreo 8.1. I carefully documented the bug and conducted lots of test. Please see my recent post.

**Comment by FoxInFlame** [comment]
The video doesn't have to be 1080p. I tried downloading [this video](https://www.youtube.com/watch?v=f8W5Zy-gagU) which has 480p as the highest, and it still resulted in a 1007 Error upon post-processing.

**Comment by x2k13** [comment]
Well, then it's something to do with the muxing process as such being buggy. Videos that don't need muxing download w/o problems.
