### ISSUE TITLE
I'm using the latest version of NewPipe 0.15.0, which can not play Live video on YouTube, like https://www.youtube.com/watch?v=3zzjwjhsXck   Anyone can help? Thanks

### ISSUE THREAD

**Issue by ed828a** [TeamNewPipe/NewPipe#2089]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment]
Closed in v0.15.1
