### ISSUE TITLE
Allow "subscribing" to channels, obviously without that actually occuring

### ISSUE THREAD

**Issue by energ1zer** [TeamNewPipe/NewPipe#209]
It'd be nice if there were a feature that allowed users to effectively just "follow" specific channels, or just show all their most recent videos. Amending my suggestion earlier, the new videos of whatever channnel one is subscribed to could be what is displayed on the homescreen.

**Comment by theScrabi** [comment]
Yes that's one of my goals to it will just take a while.

**Comment by aphirst** [comment]
I mentioned in another thread that YouTube already provides RSS feeds for each channel, perhaps these can be leveraged into a "pseudo"-subscriptions feature for those with no Google accounts?

**Comment by theScrabi** [comment]
Yea this "pseudo"-subscriptions is my play. The only problem is that we'd have to implement channel support first.

**Comment by mtbu** [comment]
Currently the RSS can be retrieved from the channel's page and added to SpaRSS/some RSS app

**Comment by codermess** [comment]
This has been implemented.

**Comment by FaizKhan5** [comment]
Close this issue.

**Comment by iillyyaa2033** [comment]
@theScrabi, looks like this issue has been implemented.
