### ISSUE TITLE
Feature Request: Grid options to make layout larger.

### ISSUE THREAD

**Issue by ariusa** [TeamNewPipe/NewPipe#2095]
On TV or android boxes the layout is small.  Make the columuns for the grid customizable.  So 3 columns for example (instead of current 6) would provide a larger thumb of videos including text.  Helps us blind people out more by allowing scaling of some kind.  Thanks for your efforts.  Ps. I'm wearing glasses already..

**Comment by opusforlife2** [comment]
Duplicate of #3139.
