### ISSUE TITLE
No next video for this file

### ISSUE THREAD

**Issue by Massedil** [TeamNewPipe/NewPipe#2098]
Just to inform you that there is no next video for this file :
https://www.youtube.com/watch?v=ktiONWfSL48

So "autoplay next video" isn't working.

Is it normal ?

NewPipe 0.15.1 - fdroid

---

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by justanidea** [comment]
On youtube neither there is no next video, so i guess its quite normal

**Comment by Massedil** [comment]
For me, connected on YouTube, I have next videos :

![](https://user-images.githubusercontent.com/20357783/52262590-2571e880-292d-11e9-83a0-e741436a8ec9.jpg)

Without connection, I cannot play the video.

With this link, I can play the video without connection : 
https://www.youtube.com/embed/ktiONWfSL48

And there is a new autoplay video at the end.

**Comment by Stypox** [comment]
This is a problem with youtube, and cannot therefore be solved, so I'm closing
