### ISSUE TITLE
How to show the youtube search result as default main page while opening the app?

### ISSUE THREAD

**Issue by cashcrate921** [TeamNewPipe/NewPipe#2099]

**Comment by MaximumP** [comment]
Go to 
Settings>Appearance>Content of main page
Tap the "+" button and add "History" to the list and move it to the top by dragging it

**Comment by kurniaweb1** [comment]
how to add setting on android studio?

**Comment by opusforlife2** [comment]
Answered?

**Comment by Stypox** [comment]
Question issues should be kept open in my opinion, as they are easy to filter out and are useful for FAQ. What do you think @TobiGr @wb9688 @B0pol ?

**Comment by opusforlife2** [comment]
If we need questions for FAQ, then why not just make a FAQ? In fact, having a FAQ will help easily answer repeated, similar questions. The developer of FairEmail uses his FAQ to _great_ effect. It has over a hundred entries, each linked with an anchor tag for direct linking.

**Comment by wb9688** [comment]
@Stypox: Imho questions should be closed when they're answered. I do agree we should put more stuff in our FAQ.

**Comment by Stypox** [comment]
@wb9688 ok. Then not only all `more info needed` issues should be closed, but also all `question` ones @opusforlife2 ;-) (this can be done via bulk actions I think, though check if recent issues shouldn't be closed)

**Comment by wb9688** [comment]
@Stypox: I wouldn't just close all more info needed issues.

**Comment by opusforlife2** [comment]
I think the FAQ should come first. Then the issues labelled question can be directed to it. It would be unfair to the non-ghost users otherwise.

**Comment by B0pol** [comment]
> What do you think TobiGr wb9688 B0pol ?

Same as wb: close them if they are answered
