### ISSUE TITLE
[]Download videos and music with different pitch and speed

### ISSUE THREAD

**Issue by pakodx** [TeamNewPipe/NewPipe#2101]
Hello, I would like to request a feature.
I'd like to be able to download videos, well mostly music, in the speed and pitch I listen to them in.
Is that possible?

Thanks in advance

**Comment by Stypox** [comment]
I don't think it would be a good idea, since it is too specific, it would need ffmpeg (thus increasing apk size) and you could use other tools.

**Comment by noauthoritybuturself** [comment]
i also would love this feature. i don't think it's too specific, if speed & pitch is offered online, i don't see why it's not important offline too.

**Comment by opusforlife2** [comment]
Use your media player to do it? VLC can save playback speed for individual media.
