### ISSUE TITLE
Cannot fetch a video of YouTube

### ISSUE THREAD

**Issue by linux-player9** [TeamNewPipe/NewPipe#2103]
NewPipe is no more able to fetch YouTube videos so I can just use it for SoundCloud. Now I need to use a script to use a recent youtube-dl version in Termux to be able to download Youtube videos. Please update the NewPipe version of the F-Droid repositories so that everyone will be able to use the app to view YouTube videos and read YouTube musics in background.

**Comment by gkeegan** [comment]
Which version are you on right now? Mine is 0.15.1 and it works fine.

**Comment by linux-player9** [comment]
Now my NewPipe is up to date and it works

**Comment by linux-player9** [comment]
Now my NewPipe is up to date and it works 👌
