### ISSUE TITLE
Cannot play any video - complete failure to parse

### ISSUE THREAD

**Issue by JYNxYoshii** [TeamNewPipe/NewPipe#2106]
I used to run the F-Droid version of .14.2, since that actually worked, but .15.1 goes back to the same error with .14.2 downloaded from the repo here: complete failure to parse the website. No custom hosts files, no VPN, no special routing for my phone, updated directly from F-Droid. Playing from a playlist just gives me the Could Not Play This Stream error, and individual video selection immediately crashes with a Could Not Decrypt URL Signature error. Rolling back to .14.2.

**Comment by Stypox** [comment]
Closing since this is not a problem anymore
