### ISSUE TITLE
[0.15.1]playback speed controls

### ISSUE THREAD

**Issue by fullon9** [TeamNewPipe/NewPipe#2108]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
..............................................................................................................................
I hope I can set DEFAULT settings for playback speed controls.
My favorite setttings are
  tempo : 2x ([v]unlink(may cause distortion))
Thanks in advance

**Comment by Tikotik** [comment]
Duplicate of #1924

**Comment by Stypox** [comment]
Duplicate of #735
