### ISSUE TITLE
Search engine not working

### ISSUE THREAD

**Issue by nacotokomu** [TeamNewPipe/NewPipe#2110]
Hi,
I have a problem with D.Tube, can't find ANY video. When trying got information ''There is result for X'' and there is no videos. 
Please, answer if you know what can be wrong.
Thank you.

**Comment by gkeegan** [comment]
This is not a support area for D Tube. I am sorry for the inconvenience.

**Comment by gkeegan** [comment]
Did someone at D Tube link you here?
