### ISSUE TITLE
Downloading large capacity videos will fail

### ISSUE THREAD

**Issue by pongfcnkl** [TeamNewPipe/NewPipe#2111]
![screenshot_2019-02-10-16-47-12-892_org schabi newpipe](https://user-images.githubusercontent.com/24273319/52531806-3fa92d80-2d56-11e9-9356-280cfc4ec1e4.png)

**Comment by TobiGr** [comment]
Can you please tell us,

1. which video you tried to download (url, resolution, encoding)

2. how much free storage did you have at the time you downloaded the video

3. your device model and Android version

**Comment by pongfcnkl** [comment]
> 
> 
> Can you please tell us,
> 
>     1. which video you tried to download (url, resolution, encoding)
> 
>     2. how much free storage did you have at the time you downloaded the video
> 
>     3. your device model and Android version

1.https://www.youtube.com/watch?v=2kAQCR7qV0U  

2.8G, stored on an external SD card

3.radmi 4pro    Android6.0.1

**Comment by TobiGr** [comment]
> 1.https://www.youtube.com/watch?v=2kAQCR7qV0U 1080P mpeg4

The video and audio streams have a size of 2,94 GB

> 2.11G, stored on an external SD card

This means we did not have enough free space. We need to check this before downloading.

Btw. downloading to external SD cards is not possible. What was your download directory?

**Comment by pongfcnkl** [comment]
> 
> 
> > 1.https://www.youtube.com/watch?v=2kAQCR7qV0U 1080P mpeg4
> 
> The video and audio streams have a size of 2,94 GB
> 
> > 2.11G, stored on an external SD card
> 
> This means we did not have enough free space. We need to check this before downloading.
> 
> Btw. downloading to external SD cards is not possible. What was your download directory?

Not 2.11G is 11G
2. Is the sequence
Download the catalog at Android/date/org.schabi.NewPipe

**Comment by Stypox** [comment]
Is this fixed in the latest version (after #2149)? @kapodamy

**Comment by kapodamy** [comment]
First, ¿what filesystem you have in the external sd card?
In FAT32 the maximum file size is 4Gb.
@Stypox yes

**Comment by kapodamy** [comment]
fixed in commit https://github.com/TeamNewPipe/NewPipe/pull/2679/commits/dd2885c2cdef77f29f8c4179b8b8c3350a80ef9c

**Comment by gkeegan** [comment]
@kapodamy I got a postprocessing error today. Downloading to sdcard with filesystem sdcardfs (basically fat32 AFAIK). The file was 2.07Gb, but as it failed it said the file was 4Gb. Upon merging audio+video, do the files duplicate in size then shrink down again? This would cause anything over 2Gb to fail in postprocessing.

**Comment by kapodamy** [comment]
this was fixed in https://github.com/TeamNewPipe/NewPipe/pull/2679/commits/84c476120889918036b1fd0c1ef8f464ee804f10 commit
