### ISSUE TITLE
Audio format error

### ISSUE THREAD

**Issue by MACtr** [TeamNewPipe/NewPipe#2113]
•M4A format does not work properly on many devices. MP3 format should also be download.

**Comment by FaizKhan5** [comment]
On which devices?

**Comment by MACtr** [comment]
In-car Bluetooth Lighter (Transmitter), low-price music players ...M4A format is not supported on such devices.That's why I can't use the music I downloaded with Newpipe.

"Google Translate"

**Comment by TobiGr** [comment]
For mp3 support see #503
