### ISSUE TITLE
Add duplicate deletion inside the playlist

### ISSUE THREAD

**Issue by jakerockz97** [TeamNewPipe/NewPipe#2115]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by eternaltyro** [comment]
This would be really nice to have. Basically, what I would like to have is this:

1. If a video is not in a playlist, and I attempt to add it to a playlist (say `music`), add it.
   - Increment Playlist length numeral
2. If a video is not in a playlist, and I attempt to add it to a playlist, silently ignore and
   - Don't increment playlist length numeral
3. In the information view, if video is added to any playlist, change "Add To" icon to signify, video is already listed. ( + to ✓ or something similar )
4. Even if a video is in some playlist, allow user to add to other play lists. (probably have some indication in the list selection view for whether the video is already in a list)

**Comment by Stypox** [comment]
@eternaltyro this would be another feature request

@jakerockz97 closing in favour of #2583
