### ISSUE TITLE
On my Android TV Box, get only audio and no video

### ISSUE THREAD

**Issue by oktober29** [TeamNewPipe/NewPipe#2119]
Hi all,
i've got a Himedia Q5 PRO (Android TV Box).
Installed NewPipe, but any video doesn't appear, i hear only audio.
Any suggestion?

Many Thanks

**Comment by oktober29** [comment]
None have this issue?

**Comment by Stypox** [comment]
Could you send a complete list of the steps to reproduce, or a video?

**Comment by Z3ROGRAV1TYx** [comment]
I don't have anything to contribute to this, but I did have a question.
I wasn't even aware Newpipe  had AndroidTV support, I assume it's just the Android APK sideloaded?
Is the UI the same as android? Doesn't seem like it'd be very intuitive on the TV with controller?
