### ISSUE TITLE
translate Fastlane app store texts directly on Weblate

### ISSUE THREAD

**Issue by eighthave** [TeamNewPipe/NewPipe#2124]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Weblate just launched a beta feature for directly translating the Fastlane name/summary/description/whatsnew texts.  Since NewPipe is already on Fastlane and Weblate, it can easily use this. See this in action for F-Droid's Android client:
https://hosted.weblate.org/projects/f-droid/f-droid-metadata/

Follow the beta here: https://github.com/WeblateOrg/weblate/issues/1525

@comradekingu 
#675 
#833

**Comment by TobiGr** [comment]
@theScrabi @TheAssassin  I don't have acces to set this up on WebLate. I guess this is a nice change and will also be required sooner or later. Nevertheless, there will be changes to algo which shows the "latest" app in F-Droid. Apps need to meet certain criteria after a new F-Droid version containing the changes of [this PR](https://gitlab.com/fdroid/fdroidclient/merge_requests/805) is merged.
If I understand the new requiresment correctly, we already fullfill them by providing some German translations. Nevertheless, some translated app descriptions might be nice for F-Droid users.

**Comment by TheAssassin** [comment]
@TobiGr neither do I, @theScrabi will have to do it.

What is Fastlane by the way?

**Comment by TobiGr** [comment]
[Fastlane](https://fastlane.tools/) is an app automation tool. You can do quite interesting things with it. 
IIRC F-Droid tools use it to handle the screenshots, changelogs and descriptions which we store in this repository.

**Comment by eighthave** [comment]
Fastlane is a tool that automates publishing texts and screenshots to
Google Play.  F-Droid also supports the file layout.  So for NewPipe,
you don't need the fastlane tool at all, just use the file layout.

**Comment by eighthave** [comment]
actually, I forgot, fastlane would be useful for you if you want to
generate localized screenshots since it automates that process.

**Comment by TobiGr** [comment]
@theScrabi I know that your busy atm. I'll take care of it when someone grants me the Weblate permissions.

**Comment by B0pol** [comment]
Done
