### ISSUE TITLE
Minimize on app switch unpauses video

### ISSUE THREAD

**Issue by kingelilol** [TeamNewPipe/NewPipe#2125]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

#### Context
Device: Samsung S4
OS version: Linage 14.1
Android version: 7.1.2
App version: 0.15.1

#### Issue
A paused video starts playing after I'm locking my screen or switshing / closing the app.

#### Steps to Reproduce
Set the setting "Video&audio / behavior / minimize on app switch" to "Minimize to background player" or "Minimize to popup".
Start watching a video and pause it.
Switch / Close the app or lock the screen. 

#### Expected behavior
The video shold stay paused.

**Comment by fightthepower** [comment]
Same here I am also facing the same problem

**Comment by TBog** [comment]
This is also bothering me. I will fork this repository when I finish my current job tasks.

**Comment by ildar** [comment]
dup https://github.com/TeamNewPipe/NewPipe/issues/2395 ?

**Comment by Stypox** [comment]
Closing in favour of #2395
