### ISSUE TITLE
Downloads don't automatically start

### ISSUE THREAD

**Issue by johnb-xp** [TeamNewPipe/NewPipe#2126]
I have to manually go to the download page and start every download I thought was automatically started. Is this a new intentional thing, or an issue? I'm pretty sure downloads would start automatically before.

**Comment by gkeegan** [comment]
The first video is supposed to start. Then once it finishes, the next video starts downloading. Is this what happens for you?

**Comment by johnb-xp** [comment]
Just tried it again and it seems to be working properly now. Hmm 😂

**Comment by gkeegan** [comment]
The behavior you said before has been reported I believe. Could you close the issue, as this is a duplicate?
