### ISSUE TITLE
Support for VP9 Webm video.

### ISSUE THREAD

**Issue by mathwhiz1212** [TeamNewPipe/NewPipe#213]
Youtube automatically serves Webm VP9  video wherever available on desktop.
Could you implement Webm VP9?
It's less to download for higher quailty making it good for data caps.

**Comment by theScrabi** [comment]
Yes will come.

**Comment by mathwhiz1212** [comment]
Good :)

**Comment by mauriciocolli** [comment]
It's possible with internal player now (ExoPlayer).
