### ISSUE TITLE
Disable infinite scroll

### ISSUE THREAD

**Issue by dimqua** [TeamNewPipe/NewPipe#2134]
Could you add an option to disable infinite scroll in the search result?

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by AhmedNSidd** [comment]
How would this work? Would it only show a limited number of videos (the first set of results) and that's it? Or do you set the number of search results that it's going to display? And why is this a problem for you in the first place?

**Comment by cup** [comment]
@AhmedNSidd what do you mean how would this work?

it would just like thousands of sites worked before infinite scroll existed

in fact youtube itself even paginates

https://youtube.com/results?search_query=hello

**Comment by AhmedNSidd** [comment]
I clicked on the link and it was infinite scrolling in the search results on youtube . Also I misunderstood what OP meant. I get what he's saying now.

**Comment by Stypox** [comment]
I don't understand why this would be needed... Is it a problem to download 2 pages instead of one?

**Comment by JM480** [comment]
I think this option should affect channels and comments as well.

**Comment by Stypox** [comment]
The author still hasn't answered this, I'm adding the tag:

> I don't understand why this would be needed... Is it a problem to download 2 pages instead of one?
