### ISSUE TITLE
[Feature request] Add an entire playlist to the background player queue

### ISSUE THREAD

**Issue by Obigre** [TeamNewPipe/NewPipe#2138]
Heyo ! 👋

When you already have some music playing in the background, it's impossible to add a playlist to the queue. For now the only option available is to "Play in the background", which cleans up the current queue and puts the playlist on play.
But what if i want to just add these titles to the queue, and not replace the old one with the playlist ? You could always go on and add each title to the playlist by hand but it can get very tedious at times.

➡ My request would be that you would do so by holding down the "Background" button that already exists, which would present you with the option to add the whole playlist to the queue. OR you could hold down on the playlist icon and name in the search results, which would present you with the same option.

As an additional remark, writing this feature request i realized playlists had less interactions possible than music or video titles alone. They could benefit for batch adding to playlist, batch adding to queue, quick options from the search menu by holding down on their icon etc... but these will belong in another feature request i think.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by huckvrni** [comment]
I would like it as well, my current solution is to start play the first playlist then add it to a temporary playlist and then start the second playlist and add it to the temporary playlist and then play it.
Quite cumbersome but better then doing one by one on very large playlists.

**Comment by Stypox** [comment]
If you long press on the 'background' button you can enqueue the whole playlist.
