### ISSUE TITLE
Release documentatoin

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#2139]
Releases have always been something nasty, as we often changed the way how to release.
Here a wrote down our current attempt of releasing versions (some things I wrote down are not done yet, but should be done by now).

I am also looking for someone who can assist me or could replace me in case of me getting rolled over by a bus. So if one of you wants to get into maintaining NewPipe you might want to read it as well :)

https://teamnewpipe.github.io/documentation/05_releasing/

**Comment by snappyapple632** [comment]
I'd be happy to help fix up the documentation if you would like me to do so! Looks like there are a couple of typos and some irregular structuring that should be easy fixes on my end.

**Comment by theScrabi** [comment]
Yes pleas, language is not one of my best parts :D

**Comment by snappyapple632** [comment]
So how do you want me to do this? Just copy everything over onto a Google Doc and revise it from there, or do you have a copy on your own account that I can revise?

**Comment by theScrabi** [comment]
Read the docs, its written down how documentation works.
https://teamnewpipe.github.io/documentation/06_documentation/
