### ISSUE TITLE
Feature Request: Start Video "Play", in Buffering/Paused Mode, as a Setting.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [TeamNewPipe/NewPipe#214]
We've all encountered network log-jambs, when the kiddies get out of school, or on weekend nights.  Some are, most often, on slow networks.  

You must maintain a vigil, waiting for enough buffering to occur, to hit the "Pause" button, or you are likely to get an error that the vid' won't play.  

I'd like to have a setting that allows the choice to default the buffering of streams, paused, "globally" for all videos, within NewPipe.

Thanks.

**Comment by theScrabi** [comment]
That would be something that could be implemented using exoPlayer. I think.

**Comment by locutis-of-borg-1999** [comment]
Hmmm...  So it seem impossible with tha native/internal platwr?  Pity.   I hadn't noticed if it's, possible with VLC, but ditched it, fo some reason, probably reliability related.  

Well, hopefully exoPlayer is fully FOSS, an in FOSS repo's, like F-Droid.

**Comment by theScrabi** [comment]
Well actually I don't really know. But I know that MediaPlayer does only have rudimentary streaming support.

**Comment by Stypox** [comment]
@opusforlife2 yes, I am updating #155's description to be only about offline queue
