### ISSUE TITLE
720p MP4 downloads are not possible for many videos

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/NewPipe#2140]
On this video (https://www.youtube.com/watch?v=pzsGoHxjZuk), and many others, 404 errors occur when attempting to download the video in 720p. I believe that this is due to YouTube hiding (or removing) itag 22 in 720p videos.

Much more in depth info and discussion about this is occurred in the youtube-dl repo. See https://github.com/rg3/youtube-dl/issues/17842.

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I am on the latest commit of dev branch.

**Comment by FaizKhan5** [comment]
On my side it's working fine in f-droid release

**Comment by gkeegan** [comment]
Odd. I will try the F-Droid version in a few hours and report back.

**Comment by gkeegan** [comment]
Sorry for the delay. I have tested it on the F-Droid and GitHub versions of the 0.15.1 release, as well as latest dev commits, and the linked video no longer has the error when downloading. This can't be a fault of NewPipe, it has to be a problem with YouTube changing something yet again.

**Comment by gkeegan** [comment]
I have found something related to this, but the video cannot be played or downloaded AT ALL on NewPipe, while it works fine in browser. 

https://www.youtube.com/watch?v=igXCqYOT_Bo

When I attempt to play in NewPipe, it gets stuck at the loading screen endlessly.

When I attempt to download, it gave code 1002 (java.io.IOException: unexpected end of stream on com.android.okhttp.Address@589f5ac6)

When I attempted to restart the download, I received a different error, error 1005 (Can not find the server).

YouTube is being sneaky again.

**Comment by gkeegan** [comment]
It would be very much appreciated if someone would test this video quickly on a different device, in order to see if the video does end up working again, as it is my belief that YouTube is making this happen with certain videos, but only for a certain length of time.

**Comment by puppykickr** [comment]
Ok, so I tried plaing it, and downloading it as well.

It worked just fine on my device, a ZTE 558VL, running 7.1.1

**Comment by gkeegan** [comment]
It works for me as well now. Same device and internet connection. This has been the case for many videos. They don't work for a day, then all of a sudden everything is fine.

**Comment by sangohan** [comment]
Also seeing the same issue on this music video: 
* https://www.youtube.com/watch?v=-gMNd861RNY
* https://www.youtube.com/watch?v=YtU_sb4jYE8

If you use youtube center (dev version https://github.com/YePpHa/YouTubeCenter/raw/master/dist/YouTubeCenter.user.js) to force turn off DASH playback, then only the 360p option is available in the browser. Turning back DASH on will let you watch the 1080p and 720p. 

It may just be that the non-DASH format is no longer available? =(

**Comment by gkeegan** [comment]
Fixed as of 0.16.2.

**Comment by CWftw** [comment]
What was the solution for this? I'm using an updated version of the extractor and I am receiving 720p mp4s that are not playable. Is there any way to differentiate them or play them?

**Comment by gkeegan** [comment]
There is an issue with those videos again, but it is separate from this. There is an open issue for it afaik.
