### ISSUE TITLE
[Feature request] Bring back support for Android 4.0.4

### ISSUE THREAD

**Issue by tbjorheim** [TeamNewPipe/NewPipe#2141]
I have used NewPipe for some time on my Samsung Galaxy Tab 8.9, and it worked very well. But since version 15, I cannot upgrade since it's not compatible with Android 4.0.4. (And 14.2 does not work anymore). Yes, I know my tablet is old, but it still works great for my use. And there is no option to upgrade it, as Android 4.0.4 is the latest version available for this device.

When searching Play Store for an alternative, I came across an app called [Play Tube & Video Tube](https://play.google.com/store/apps/details?id=tube.video.tubevideo.playtube)  This seems to be based on Newpipe, but several functions seems to have been removed. I don't know which version of Newpipe it's based on, but it works. I can live without downloading and background play. But I will prefer to use the official NewPipe app, and not a fake one like this seems to be.

Lately Google/Youtube has made the official Youtube app unavailable for Android 4.0.4 by putting a message to upgrade in the app. But when trying to upgrade, it's not possible. In other forums, many other peoples are very unhappy with this and are looking for an alternative.

Would it be possible to bring back support for Android 4.0.4? At least a fix for 14.2 which could make it work again.

**Comment by theScrabi** [comment]
This is why the new legecy repo exists.
