### ISSUE TITLE
Remote support during playback for AndroidTV devices

### ISSUE THREAD

**Issue by anpaza** [TeamNewPipe/NewPipe#2142]
The applications has good support for remote control almost everywhere.
However, during full-screen playback, it doesn't react when any remote button is pressed, neither arrows or OK (which is DPAD_CENTER or ENTER depending on device).
Is it possible to support arrows and other keys in full-screen player, at least the most obvious functions? E.g. SPACE for pause, OK (and, perhaps, MENU) for popping up the navigation bar & controls, arrows for fast forward/rewind.

**Comment by theScrabi** [comment]
Indeed this should be improved

**Comment by allendema** [comment]
@anpaza 
This should be working now.
