### ISSUE TITLE
UI / UX suggestions for comments

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#2146]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

for better UX, we should increase the padding of the "Up next" tab. I tapped on "download" multiple times today. Maybe this was because of my clumsy fingers...
![upnext_phone](https://user-images.githubusercontent.com/17365767/53289987-52802100-379e-11e9-9146-af14bdf842be.png)
For design aspects, I'd suggest to increase the padding in the tablet column as well,
![upnext_tablet](https://user-images.githubusercontent.com/17365767/53289986-51e78a80-379e-11e9-9fa9-2abfdee93024.png)

CC @yausername @theScrabi 

I'll try to do some more testing with the current dev next week. I love the recent changes ❤️

**Comment by FaizKhan5** [comment]
@TobiGr What you think about comments font size ?

**Comment by theScrabi** [comment]
Full ack :)
