### ISSUE TITLE
M4A audio download and Dash header issues

### ISSUE THREAD

**Issue by andiandi13** [TeamNewPipe/NewPipe#2152]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When I download audio from YouTube it's an AAC with a "dash" header.

Contrary to other apps like TubeMate, when there isn't any issue playing the songs, files downloaded with NewPipe shows some issues :

- When I skip time on a track on my music player,   it seems like there isn't some sort of "keyframe". e.g, if I want to go to 00:53, it will warp to 00:50.

- When the audio track is ending, the player freezes for some seconds before reacting againg.

Anyway, that header is strange, and it'd be better to use a simpler M4A header/codec.

**Comment by kapodamy** [comment]
implemented in https://github.com/TeamNewPipe/NewPipe/pull/2149

**Comment by andiandi13** [comment]
Thanks ! Closing the issue

**Comment by andiandi13** [comment]
@kapodamy : Why it's not included in the new version ?

**Comment by gkeegan** [comment]
I would assume because the downloader fixes were not implemented in time, or that it was wanted to not change many things between version to keep bug fixing easier.

**Comment by andiandi13** [comment]
> I would assume because the downloader fixes were not implemented in time

I thought apps where built directly from the updated GitHub code, with all the commits am I wrong ?

It might be the second reason

**Comment by gkeegan** [comment]
The apps are built from the code, but kapodamys code is in what is called pull request, which means the code is not being implemented yet, and is just being worked on at the moment. It has not been committed yet.

**Comment by andiandi13** [comment]
@gkeegan Oh true, I thought it was a commit up here. Thanks for the clarification.
