### ISSUE TITLE
[fr] Add support for Yatse to "play on Kodi"

### ISSUE THREAD

**Issue by zilexa** [TeamNewPipe/NewPipe#2157]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

NewPipe uses the cast button in the app to send the video to Kodi, which is totally awesome! 

Currently this only works if you install the Kore app, a Kodi remote that was given new life recently by the Kodi team.

Yatse has been the most popular remote app, filling the gap when Kore was being ignored. 

But Yatse can no longer be compared to Kore, because it is a fully featured Kodi _client_, allowing you to view your entire Kodi library (even offline) and play everything in the Yatse app, without ever turning on your TV.

It just happens to have a remote as well (and full support to use as receiver or TV remote).

Please add support for Yatse to "play on Kodi". If I was a developer I would offer my help. I can only offer a donation unfortunately.

I noticed this request has been denied simply in the premise Yatse not being open source and Kore is. What you are ignoring is that Kore is not a Yatse replacement. And Kore simply copied the remote features of Yatse, since they were all developed for Yatse first. 
And although there is no open source alternative to Yatse, Yatse for Windows (Yatse2) is open source, here on GitHub. Also note Yatse could not even exist without lots of open source libraries. 

There is no trial in Yatse, it is a fully featured Kodi client. The unlocker, which is rediculously cheap, adds support for receivers like Yamaha. I'm sure there is a license that needs to be paid to support that. 

Hence, saying Kore is opensource and Yatse really you are comparing apples to potatoes. 

Also, note that the developer of Yatse is actually an active code contributor to Kodi, worthy mention for example JSON-API and bug fixing.

I do not think it is fair to say that Yatse sucks or compare it to Kore.

All the information above can be found on the Yatse website btw. It is public knowledge.

**Comment by theScrabi** [comment]
Yatse was requested before, but its not free software, and thus not available through fdroid. So we don't support it.

**Comment by zilexa** [comment]
It's not available through F-Droid but it is free software. As explained above.

**Comment by tbjorheim** [comment]
Hi. I use Yatse with NewPipe. You can use the share function to send a video to Yatse. You can then select between queue or play. Tip: To send directly from search results, hold down and select share from the menu.

Hope this was helpful. Not sure if it works exactly the same as the other function to send to Kodi, but I have used this method a lot, and I think it works very well.

**Comment by UserX404** [comment]
I just noticed the play on kodi button but it want to install kore (?). I dont know this app and i'm using yatse since 2013. I think at this time there was no official XBMC/KODi app. I'd love to see support for this/my one and only remote app.
To bring clearance: Yatse is free. But you are able to buy a premium unlocker to get more features.

**Comment by UserX404** [comment]
@tbjorheim 
Messed a lot of time with the damn YT-Kodi app and hasn't get it running.
Are you able to forward a stream without Kodi-YT?

**Comment by tbjorheim** [comment]
To make it work, the Youtube addon needs to be working on Kodi.
