### ISSUE TITLE
I can't play video's on 3GP format

### ISSUE THREAD

**Issue by AdamWest99** [TeamNewPipe/NewPipe#2166]
Since my internet is not the greatest I usually play the videos on 3GP format , but for some reason doesn't show up anymore :^(

https://i.imgur.com/rFoIx7K.png

**Comment by gkeegan** [comment]
I would assume that this video is a music video? They are served differently through YouTube (probably for the usage of YouTube Music).

There isn't really much that can be done about this, at least from my understanding.

**Comment by AdamWest99** [comment]
It's not working for any video's.. even video's I already watched on 3GP

**Comment by Symbian9** [comment]
**Seems like there no 3GP links anymore!**

I detected it for all channels few days ago too!

*YouTube* stopped providing 3GP links? 

Or  *YouTube* changed API and *NewPipe* can't pars 3GP links?

**Comment by AdamWest99** [comment]
Well that sucks :^(

anywho, thanks for the info
