### ISSUE TITLE
cannot import subscription if have a chinese or japanese character

### ISSUE THREAD

**Issue by willowen** [TeamNewPipe/NewPipe#2169]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by willowen** [comment]
Cannot import subscription if have a chinese or japanese character. Please fix it

**Comment by DragonWolf5589** [comment]
That must be my issue. It won't import at all but I have a subscription to a channel that's learning japense so it has Japanese characters

**Comment by mauriciocolli** [comment]
This case is [already being tested](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/resources/youtube_export_test.xml).

Closing in favor of #2226
