### ISSUE TITLE
Scroll Down Bugged After Update To 0.16.0

### ISSUE THREAD

**Issue by TakuyaSama** [TeamNewPipe/NewPipe#2174]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
- I enter at the NewPipe since 0.16.0, with both comments and sugested new videos disabled, open the description, scroll down and it comes everything black, with no content.
I attach an screenshot of the issue.
If a screencast help, i will provide it too, i do not mind.
The OS is LineageOS 16 (based on Android 9.0 Pie), but the same issue was on LineageOS 15.1 (based on Android 8.1 Oreo), so i suppose the issue is not OS version related.

![53688159-bfb42900-3d3f-11e9-8d89-d205752cab26](https://user-images.githubusercontent.com/1891273/53700608-65c16b00-3df4-11e9-8afa-5557bd6d0f40.png)

**Comment by gkeegan** [comment]
I have noticed this issue. 

The way I noticed it, it happened by having comments and next videos disabled, then opening a video, and scrolling down before the video page finishes loading. It is not related to expanding the video description.

**Comment by epitron** [comment]
There's another aspect to the bug: if the description is just a bit longer than the display, you can't scroll it at all.

Also, with a longer description, if you scroll off into the abyss, you can never scroll back.

**Comment by TakuyaSama** [comment]
> There's another aspect to the bug: if the description is just a bit longer than the display, you can't scroll it at all.
> 
> Also, with a longer description, if you scroll off into the abyss, you can never scroll back.

That is it what i was saying yes, the fact that you can not scroll back or restore the video status or something, just press back or go back, and reload the video, i hope this gets fixed soon.

**Comment by TakuyaSama** [comment]
> I have noticed this issue.
> 
> The way I noticed it, it happened by having comments and next videos disabled, then opening a video, and scrolling down before the video page finishes loading. It is not related to expanding the video description.

Yes, you are completely right, i just tried it to check it out, you only have to scroll down from the blank zone, and it appears the bug as the way i told, so yes, it is not related with expanded description. Thank you for the clarification mate.
