### ISSUE TITLE
Can i use it for my own website

### ISSUE THREAD

**Issue by chinli12** [TeamNewPipe/NewPipe#2175]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
I have my video site I want to know if I can use to create my website application my website have api

**Comment by chinli12** [comment]
Can I use it to build my own website application I have my own api

**Comment by hueldoeu** [comment]
0.16.0 is extreamly awesome

**Comment by chinli12** [comment]
Please can you provide the document to interrogate my website api to it,or should I hire you to do it for me

**Comment by gkeegan** [comment]
Are you asking if you can add support for your video site into your own version of NewPipe?

**Comment by theScrabi** [comment]
Yes its possible. Pleas see the documentation of the newpipe extractor.

**Comment by chinli12** [comment]
Where can I find the documentation of the newpipe extractor

**Comment by chinli12** [comment]
@gkeegan  yes I want to add  support for my video site into myown version of NewPipe?

**Comment by gkeegan** [comment]
Here is the documentation: https://teamnewpipe.github.io/documentation/

**Comment by chinli12** [comment]
Please can any one help me build it I don't understand the document

**Comment by TobiGr** [comment]
In case you have problems with the documentation, please open tickets in the [doc repository](https://github.com/TeamNewPipe/documentation) and tell us, which steps fail or are hard to understand.
