### ISSUE TITLE
Extra option in addition of `Enqueue when Backgrounded`

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#2187]
# The problem

One think that will avoid many time for me.

Let's say that a song is already playing in background.

Now i am searching and decided to play another song on Background directly

What i do is Enqueue in background and i go to background player and press next to play the one that i selected to be Enqueued.

# One Solution
Can we have an option like....

If another song is playing in background... replace it and directly play the one i want. As an addition to Enqueue in background.

# Let's have an extra menu option called '' Play directly in Background ''

I swear it saves me a lot of time :)

Thank you team. 

![Image](https://i.imgur.com/ZNg7dQn.png)

**Comment by goxr3plus** [comment]
@theScrabi @karyogamy @TobiGr

**Comment by Redirion** [comment]
I think this is already changed in the current git state. You can play a video in background simply by clicking on the background button. If you do the same on another video while the earlier one is still playing, the new video will be played in background instead. A long click on the background button enqueues it to the background player queue.

**Comment by goxr3plus** [comment]
Let me check it actually :)

**Comment by goxr3plus** [comment]
@Redirion Well thr problem is different, let's say i am on the details of one video. And it has other videos recommended below. I don't want to press on thr to go to their details and then press play. I want directly when i press on them context menu appears and press 'Play Now'

**Comment by goxr3plus** [comment]
![](https://i.imgur.com/QpoMwex.png)

**Comment by goxr3plus** [comment]
There is the background button but every time i have to go to details like above

**Comment by goxr3plus** [comment]
What if i want to directly play on the background one of the recommended ones below.... well navigate to their details and etc... too much procedure, we need one click

**Comment by Redirion** [comment]
> What i do is Enqueue in background and i go to background player and press next to play the one that i selected to be Enqueued.

But why don't you just click on the video (this is in terms of required time to load the details similar to the long click on the item in the list in my opinion) and just hit that background play button?

I don't see a huge time saving here. In essence you just found out how to do it quicker in comparison to the original approach from the problem description.

**Comment by goxr3plus** [comment]
You are absolutely right , but here is the difference .

I want to play one of the recommended but still , not go to details because i want to play some other of the current recommended without the need to go on the  details and then come back again to the current recommended videos.

Do you catch me :) ? It makes a huge difference for me .

**Comment by Redirion** [comment]
yes I got it. That extra step back to your previous detail view is adding the "time overhead".

Shouldn't be that hard to implement this. I might take a look at it tomorrow.

**Comment by Redirion** [comment]
Done! :)
![Screenshot_20190308-225606](https://user-images.githubusercontent.com/10477907/54058232-896e2200-41f5-11e9-9421-9981eefaf469.png)

**Comment by goxr3plus** [comment]
@Redirion I am waiting to see in the next release and send you all ma love 💓

**Comment by goxr3plus** [comment]
Update 16.1 and it is still not there :(

**Comment by goxr3plus** [comment]
@Redirion ![](https://i.imgur.com/xGsaS1S.png)

**Comment by Redirion** [comment]
16.1. was just a hotfix release. The next regular release will contain your feature.

**Comment by TobiGr** [comment]
Please take a look at the release notes. You'll see, that this is a hotfix release which does not included any other changes
