### ISSUE TITLE
Tapping on update notification not working.

### ISSUE THREAD

**Issue by krtkush** [TeamNewPipe/NewPipe#2188]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

So I got the update notification for `v0.16.0` on opening NewPipe but tapping on it did not do anything but dismiss it.

Here is what I have figured - 

`https://newpipe.schabi.org/api/data.json` is not providing the correct apk url. Instead, the `apk` object is providing -1 as value under `github` `stable`.

**Comment by krtkush** [comment]
Based on #1520, I think @TheAssassin would be the person to correct this.

**Comment by TobiGr** [comment]
Fixed in https://github.com/TeamNewPipe/web-api/commit/f243997c65b491af757184f8bbdd9c7213691edc
We just need to wait for @TheAssassin to deploy it.

**Comment by TheAssassin** [comment]
Deployment there was delayed as we had to wait for NPL to be deployed on F-Droid. Deployed your changes now.
