### ISSUE TITLE
Withdraw video/audio from exoplayer cache instead of downloading again

### ISSUE THREAD

**Issue by oguz-ismail** [TeamNewPipe/NewPipe#2189]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

If cached and requested formats are the same, downloader should withdraw the content from cache and write to disk instead of downloading it again. Thus mobile data usage would be reduced.

**Comment by Redirion** [comment]
I don't think this will work. I would be very surprised, if ExoPlayer actually cashes the whole video. Instead it most likely a circular buffer which only holds a very small fraction of the video around the current playback position.
