### ISSUE TITLE
Releasing site source

### ISSUE THREAD

**Issue by rrooij** [TeamNewPipe/NewPipe#219]
What about releasing the site's source code on GitHub so it can be improved by the community? I'm talking about: https://newpipe.schabi.org/

**Comment by theScrabi** [comment]
Yes nice idea, but to be honest, the site isn't made by me, so I don't even know what licence it is xD.

**Comment by rrooij** [comment]
Haha. Do you have contact information of the original developer?

**Comment by theScrabi** [comment]
Well, he may have send me a mail some time ago. But at the moment the only thing I have so far is his profile: https://github.com/darkon5

**Comment by theScrabi** [comment]
Well but to be honest, the current version of the side, which is linked in f-droid and here on github is also just a copy of the original one.

**Comment by mauriciocolli** [comment]
It is now - https://github.com/TeamNewPipe/website
