### ISSUE TITLE
Doesn't work with the below video

### ISSUE THREAD

**Issue by badabing2005** [TeamNewPipe/NewPipe#2191]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [x ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports. No NPE, just HTTP 404

Using 0.16.0
It doesn't work with this video, 
https://www.youtube.com/watch?v=qOTYgcdNrXE

It does not play nor it downloads, the error is:
Code: 404

Thanks

**Comment by gkeegan** [comment]
Update NewPipe to the latest version (0.16.2).
