### ISSUE TITLE
youtube video cannot play

### ISSUE THREAD

**Issue by Cha0sX** [TeamNewPipe/NewPipe#2192]
### this video cannot play in NewPipe
https://www.youtube.com/watch?v=7pydCH06WVU

**Comment by gkeegan** [comment]
Works fine for me. Are you on the latest version of NewPipe?

**Comment by Cha0sX** [comment]
@gkeegan sometimes happen.
https://www.youtube.com/watch?v=EG1AmUK4reM
and now this video play failed neither

**Comment by Bubu** [comment]
Happens to me a lot lately. I currently can neither download nor play this video: Gold - Interference (Once) - https://www.youtube.com/watch?v=9oH-B0LMnzU

Downloading says error http 403.

**Comment by justanidea** [comment]
I know that usually when this problem happens to me i clear the cache in the App settings and things go better then

**Comment by Bubu** [comment]
Clearing cache didn't help here.

**Comment by mihawk90** [comment]
Been happening for me for a while as well. Few days I try again, doesn't work either. I delete it from the download list, re-add the video, and suddenly it works... but not with all videos either :/

**Comment by Stypox** [comment]
This issue was solved in some of the hotfix releases. Since YT will change something again, just open a new issue in that case!
