### ISSUE TITLE
Cannot import subscriptions from YouTube

### ISSUE THREAD

**Issue by puppykickr** [TeamNewPipe/NewPipe#2194]
I have tried multiple times, but cannot get NewPipe to accept the subscription info after it has been downloaded.

Any help with this is greatly appreciated.

**Comment by burneracc69** [comment]
Hello, I had similar problems. But I just eventually manually added them later, took at screenshot of the subs. I can give a bit more in detail to the issue. If this should get fixed.

I clicked on import subscriptions. Click the link and login and get a file. I then import it and it doesnt work, simple. I dont remember what it said, maybe @puppykickr could tell that. But it just failed to import them.

**Comment by puppykickr** [comment]
It only failed to import on my 7.1.1 devices.
It imported just fine on my 8.1.0.

**Comment by puppykickr** [comment]
OK, scratch that.
Due to a faulty SD card (that NewPipe was mistakenly installed on) I had to redownload the app.

Now I can't import subscriptions onto my 8.1.0 either.

Why does it require a zip file, but a zip file is not the format that the file is downloaded as?

I have tried multiple times, changing the file into a zip file and it seems a waste of time.

I could have already entered hundreds of subscriptions by hand one at a time and been done.

But instead, I am frustrated and still staring at a blank subscription page after wasting an hour.

**Comment by Stypox** [comment]
This should be fixed in TeamNewPipe/NewPipeExtractor#160 . It will come in release 0.16.2. For now try analyzing the subscription file and removing any subscription with empty ("") title tag ("title"). Look at the Pull Request for more informations.

**Comment by puppykickr** [comment]
I just deleted the subscription page.
It just won't work, and I am beyond frustrated.

I already spent hours entering everything by hand once before, just to have to wind up doing it all over again.

That's not going to happen.

Features that don't work are not features at all, and should not be included in the app.

It's one thing to need to enter everything by hand, but quite another to be teased with a so called simple method 'feature' that does not function at all.

This app is wonderful, and I recommend it to all my friends.

But the addition of 'features' that don't function will make an idiot of me for having my friends try it.

It would be better if the whole subscription thing did not exist at all, especially since we must keep the actual YouTube app so that we can add comments of our own to the content.

Sorry for the rant, but I have already wasted yet another hour attempting to import my subscriptions, and almost (not quite) feel like it would be better to put up with the ads on YouTube.

At least that's a bit less frustrating.

I could be watching an ad on YouTube, and say to myself, "Well, at least you're not trying to import your subscriptions onto NewPipe."

**Comment by Stypox** [comment]
Your eager is completely understandable (it happened to me too with other services), but I think you are overexaggerating by saying subscriptions have not been tested enough...

I (and many others) never had any problem importing subscriptions, since problems are very specific (such as deleted channel) and appear rarely. Consequently problems like this are really difficult to test thoroughly, mostly because it is not possible to build a test-case for every situation (since many situations are unknown).

Again, wait for the 0.16.2 version to be released. If the problem still persists, I am willing to fix it, but I'd need your  subscriptions file.

Remember that if you don't want to provide the subscriptions file, either for privacy or time reasons, there is nothing wrong :-)

**Comment by Stypox** [comment]
If you update the app to 0.16.2 this problem should be fixed

**Comment by puppykickr** [comment]
I did finally get the sibscriptions to import to the 8.1.0 after updating to 16.2 but not onto the 7.1.1 even after the update.
