### ISSUE TITLE
How can I play the video in the first window without popup?

### ISSUE THREAD

**Issue by mahmoud32xn** [TeamNewPipe/NewPipe#2195]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by mahmoud32xn** [comment]
Thank you for the application. Next time I hope to play the video in the same window as the beginning of the video without magnifying it

**Comment by mahmoud32xn** [comment]
Thank you for the application. Next time I hope to play the video in the same window as the beginning of the video without magnifying it

**Comment by yausername** [comment]
Something like this?

![popup_1](https://user-images.githubusercontent.com/5203007/53983161-9e3aaf00-413c-11e9-9bdd-81a7c3978b06.gif)

**Comment by theScrabi** [comment]
@mahmoud32xn please change the title of your post so somrthing meaningfull.

**Comment by mahmoud32xn** [comment]
> @mahmoud32xn please change the title of your post so somrthing meaningfull.

OK

**Comment by mahmoud32xn** [comment]
> Something like this?
> 
> ![popup_1](https://user-images.githubusercontent.com/5203007/53983161-9e3aaf00-413c-11e9-9bdd-81a7c3978b06.gif)

How can I play the video in the first window without popup?

**Comment by mahmoud32xn** [comment]
> Something like this?
> 
> ![popup_1](https://user-images.githubusercontent.com/5203007/53983161-9e3aaf00-413c-11e9-9bdd-81a7c3978b06.gif)

Yes like this but without a pop-up window

**Comment by TobiGr** [comment]
I guess you mean something like https://github.com/TeamNewPipe/NewPipe/issues/1200

**Comment by mahmoud32xn** [comment]
Yes, this is exactly what I need #1200

**Comment by mahmoud32xn** [comment]
Yes, this is exactly what I need #1200

**Comment by TobiGr** [comment]
In this case, I close your ticket to keep discussions on the embedded player in one place :)

**Comment by fightthepower** [comment]
@yausername If I didn't checked the issue page I would not have found this method to play videos. I would recommend **adding options in the settings** in such a way that a user can select whether the video be played as a pop up or as a maximized window when clicked  play button [Feature request].
