### ISSUE TITLE
How to display the playlists of the subscribed channel?

### ISSUE THREAD

**Issue by ooyellow58** [TeamNewPipe/NewPipe#2199]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
Closing in favour of #2414
