### ISSUE TITLE
Remove code assoiciated with GEMA

### ISSUE THREAD

**Issue by nekobit1** [TeamNewPipe/NewPipe#2208]
https://github.com/TeamNewPipe/NewPipe/blob/dev/assets/gruese_die_gema.svg

Looks line it was made in MS paint at the top, I don't know the language its in either

**Comment by gkeegan** [comment]
It's German, but I don't know what C3s or GEMA is.

**Comment by theScrabi** [comment]
You propably herd about artikle 13 right? Here in germany we had similar issues with music already, where copyrighted videos didnt get claimed but blocked instead. The one who send the dcma takedowns was a private organisation who claims to take care artists get their money. They are called GEMA. An alternative to them was C3s an organisation close to CCC. So every time NewPipe hit a gema takedown video back then it would show this error.

However I did't see it for years so I guess this and the code behind can be safely removed.

**Comment by Phoenix616** [comment]
The reason why you haven't seen it in years is probably because YouTube started paying off the GEMA ;)

**Comment by theScrabi** [comment]
I see.

**Comment by TobiGr** [comment]
I think someone can clean up the code related to this topic. This should be quite easy and make the app smaller.

**Comment by sherlockbeard** [comment]
@TobiGr i set a pr in respect to this issue.
