### ISSUE TITLE
could not decrypt video url signature

### ISSUE THREAD

**Issue by regmishailendra** [TeamNewPipe/NewPipe#2210]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by StevenNLWu** [comment]
this also happening on 0.16.0 version.

**Comment by nv95** [comment]
Duplicate of #2209
