### ISSUE TITLE
"Could not decrypt video URL signature" is back for 0.16.0

### ISSUE THREAD

**Issue by OSPerspective** [TeamNewPipe/NewPipe#2214]
Sorry if this was already reported but it's affecting the latest version downloaded from the F-Droid site (0.16.0) and breaks all video playback in the UK
[Error report.txt](https://github.com/TeamNewPipe/NewPipe/files/2966754/Error.report.txt)
.

**Comment by theScrabi** [comment]
Fix is on the way

**Comment by OSPerspective** [comment]
I don't usually download direct from Github so I didn't see the update. Apologies.
Thanks for continuing to work on this amazing app.
