### ISSUE TITLE
F-Droid still shows 16.0 instead of 16.1

### ISSUE THREAD

**Issue by WebBuddha** [TeamNewPipe/NewPipe#2218]
It seems that the F-Droid Repository isn't up2date yet. It still shows me the version 16.0 insted of 16.1 which is already available here.
It manual update was not able for me. Device: Oneplus 6

**Comment by Cjumelin** [comment]
+1

**Comment by Exagone313** [comment]
This is normal, it takes time for F-droid to compile releases. It's not related to NewPipe in particular.

**Comment by SpaceAgeHero** [comment]
Actually if issues like URL decryption failures keep reoccurring then F-Droid is inappropriate for the distribution of this app ...

**Comment by Exagone313** [comment]
Have you read the README?

**Comment by Cjumelin** [comment]
How can i update it manualy to keep my stored playlist ?
