### ISSUE TITLE
Why 0.16.1?

### ISSUE THREAD

**Issue by nift4** [TeamNewPipe/NewPipe#2219]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

YouTube works also without 0.16.1!
Using F-Droid version 0.16.0.
Screenshot viewing Popup Player, About NewPipe and Calendar: https://ibb.co/r2VBPFF

**Comment by theScrabi** [comment]
It used to be broken for a moment.

**Comment by nift4** [comment]
Thanks for the answer. :)
