### ISSUE TITLE
Add setting for replacing emoji in file names (but keep other special charscters)

### ISSUE THREAD

**Issue by Symbian9** [TeamNewPipe/NewPipe#2220]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Add settings for replacing emoji characters in file names.

**Comment by Stypox** [comment]
See the "Allowed characters in filenames" under Download settings
