### ISSUE TITLE
I want to add a new tab in the defualt setting What can I?

### ISSUE THREAD

**Issue by 1emirozdemir** [TeamNewPipe/NewPipe#2221]
I want to increase the number of tabs at the top. How can I do it 
Thank you

**Comment by 1emirozdemir** [comment]
I want to add a new tab in the defualt setting What can I?

**Comment by yausername** [comment]
Go to Settings->Appearance->Content of main page
Click + to add
Swipe to remove

**Comment by 1emirozdemir** [comment]
ı don't mean it! How make in Android studio

**Comment by hemanta212** [comment]
what's "kiosk page" can i add elements to it?

**Comment by hemanta212** [comment]
what's "kiosk page" can i add elements to it?

**Comment by mhmdanas** [comment]
If somebody is still interested in this, I believe you would have to change this declaration: https://github.com/TeamNewPipe/NewPipe/blob/e4ab25072908e2b752f8a8640886438dc4f94801/app/src/main/java/org/schabi/newpipe/settings/tabs/TabsJsonHelper.java#L23
