### ISSUE TITLE
Possible to have recommendations like official client?

### ISSUE THREAD

**Issue by DanteAndroid** [TeamNewPipe/NewPipe#2227]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi, thanks for hard work. I wonder is it possible to have home page which contains recommended videos like official client?

**Comment by kowith337** [comment]
"Grending" are added by default, but recommended videos is seems to be based on videos you've watched, however, NewPipe doesn't need and support to login with Google accounts, I think only trending is enough for, IMO.

**Comment by dimqua** [comment]
> recommended videos is seems to be based on videos you've watched and all channels that you've subscribe

Yes, but in theory I believe, nothing prevents to implement the same mechanism in NewPipe.

It already keeps the watch history, what's why it should be possible to retrieve "related videos" list for every watched video. And should be possible to get "related channels" for each currently subscribed channels and every channel you have watched videos from. 

This way we can have both videos and channels recommendations without exposing users data to third-parties (Google). Sounds complicated, I know. :-)

**Comment by cloudrac3r** [comment]
Sounds like a lot of requests to be made from the client to gather data.

I don't think that videos related to a user's watch history on the front page is actually a great idea, especially in the way it works with YouTube, where you watch one video about e.g. Fortnite and then suddenly your recommendations everywhere are swamped with Fortnite and you can't get it out no matter how many times you click "not interested".

Front page trending and related in video details is enough for me.

**Comment by TobiGr** [comment]
As @cloudrac3r already said, to get recommendations, we'd need to  make a bunch of requests. Nevertheless, we could only use videos which are recommended by YouTube in the right column next to the video or videos from a channel recently visited/watched channel.

To make any more interesting and "better" recommendation, we would need to access the metadata of a video as well as data about what videos are "trending" which match the same idea or content. Most of this is only stored on the YouTube servers and not visible to any of us. Some of the interesting info would be in the video description. 

All in all, recommendations by NewPipe would be a) slow and data consuming and b) not precisely. Apart from that, this is a topic which has enough content to fill a master thesis. In other words, this way to much work for to be done in our free time. There are so many things features which are still missing and tons of bugs which need to be fixed. So this would be at the lowest priority.

I'll therefore close this. @theScrabi Please reopen in case I missed something which enables us provide good recommendations.

**Comment by rien333** [comment]
First of all, thanks for all the great work. It's seems this project is coming along really nicely :smiley: 

I often like to kill idle time by watching a youtube video, so I kinda of miss the official client's recommendations (even if they are fairly bad, they keep me occupied). 

>  you watch one video about e.g. Fortnite and then suddenly your recommendations everywhere are swamped with Fortnite and you can't get it out no matter how many times you click "not interested".

Given that you all seem to agree that youtube's own recommendations are not even that good, is quality really the issue? 

> to get recommendations, we'd need to make a bunch of requests

Is the real problem thus the amount of request? I'm okay with it taking a couple of seconds to load, actually (In fact, I think most will be content with this, given that browsing recommendations is almost inherently a "time killer").

Provided that recommendations are generally used a time killers (and not actually expected to contain the computationally most likely video to peak an user's interest), I think there would be a few heuristics available. 

Viewing history would be a bad heuristic --- just watching one video skews the result too much. However, given that newpipe already has a feed with  content the user has explicitly selected to be interested in (their  "what's new" feed, which is based on their subscriptions), can't Newpipe just:

1. Pick a few random, new video's from this feed
2. Get a few (again, possibly random) of the related videos (so youtube's own algorithms will already have done some quality control)
3. Shuffle the results, and show them in a tab on user request? You could keep the amount of suggestions very small, but just repeat the process when the user taps again

**Comment by Santhanam1** [comment]
Or create tags system like Twitter or club house to recommend videos Or atleast show old video of subscribed channel
