### ISSUE TITLE
Re-add ability to autoplay video when directly opened

### ISSUE THREAD

**Issue by Phoenix616** [TeamNewPipe/NewPipe#2232]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

There used to be a setting with which videos would automatically start playing if you opened the info page from another app. This functionality seems to have been removed in a recent update and I would like to request it to be added back in. (It was optional to begin with so wouldn't hurt anyone)

I realise that a similar behaviour is possible by selecting "Video Player" as the "Preferred 'open'  option" but that has one major drawback: You are not able to quickly go to view the video info activity by pressing the back button e.g. to go to the channel page or view related videos.

There doesn't even seem to be any way to get to the video info from the player as far as I can tell so an extra info button might be useful there too. (But I would prefer the old way because although a new button might work it would still break my "[workflow](https://xkcd.com/1172/)" ;P)

**Comment by burneracc69** [comment]
I can relate to this alot! I just used to click that Info button at the top and then click the video to play it. But I guess now that you bring this up, it wouldnt have been such a bad idea to get the info after press the back button if you choose video player directly. But I dont think they will change this, because most people would just click video player and then press the backbutton and resume to whatever they did before that, for a better workflow.

**Comment by burneracc69** [comment]
Im back again, I saw a fellow talk about something that you might be intrested in. I sure was but it was totally ignored. So here is it. #1975

**Comment by Phoenix616** [comment]
Yeah that issue kinda relates to my last thought of there not being a way to view the info from the player.

But please note that I'm not requesting that the back button leads to the info page when selecting "Video Player" on the "Open"-dialog, I'm requesting for the old, removed feature being re-added that let us auto-play the video when it was opened from another app and "Show Info" was selected in the "Open" dialog. (Could even be a new "Show Info & Autoplay" option that is later used in an eventual in-info player as requested in #1831)

**Comment by Phoenix616** [comment]
I just noticed that this functionality still works on another device of mine and noticed that the stored preference `autoplay_through_intent` was set which seems to still work even though it doesn't have a config option anymore. Can't really check why — git blame is a bit hard to use on mobile — but will hopefully track the commit that removed it from the menu down soon.

**Comment by Phoenix616** [comment]
Actually I managed to find the commit that removed the settings entry: cbfe91f36f626fad343d4475f7aefd67e8f28901

Was there a reasoning behind removang that @theScrabi and would there be an issue with just re-adding the setting? Because the commit message doesn't seem to really include that... (personally I'm not a fan of multi feature change commits with very short changenotes for this reason)

**Comment by jimbo1qaz** [comment]
This behavior was not removed, but the preference entry to turn it on/off was removed from the GUI, while keeping the choice made in an earlier version of the app!

As a result, this invisible config entry causes some older app installations to either autoplay video or not, without any visible configuration differences.

**Comment by Stypox** [comment]
I think it would be better to completely drop the autoplay feature and instead implement #1873

**Comment by Phoenix616** [comment]
The linked issue and PR would be basically useless without the autoplay?

**Comment by Stypox** [comment]
Why? The back button on the screen would bring the user to the video info, while the hardware back button would close the activity.

**Comment by Phoenix616** [comment]
Without auto play being a thing both of these would be exactly the same as the info view will always be the previous activity.

What's your reasoning behind suggesting to remove autoplay anyways? You just linked a slightly related issue/commit without actually going into that.

**Comment by Stypox** [comment]
No, the info view will never be the previous activity. The only change in the pull request is a button that opens a **new** info activity on top of the video. This way you can access both the previous screen (with the phone's back button) and the info page (with the app's specific button).

**Comment by Phoenix616** [comment]
Oh, I forgot about "Video Player" being one of the preferred options then yeah, if an info view button would be added that would be enough to provide an alternative way to get to the video page I guess. (Would still break my workflow but ¯\\\_(ツ)_/¯ )

**Comment by Stypox** [comment]
The way you used "autoplay" was more of a workaround than a solution, this is why I think the solution in #2430 is better... sorry for this ;-)

**Comment by Stypox** [comment]
Fixed in #2907, since the autoplay toggle now exists. Refer to #4071 for autoplay not working upon share
