### ISSUE TITLE
Download notification with progress

### ISSUE THREAD

**Issue by ravig252525** [TeamNewPipe/NewPipe#2233]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by ravig252525** [comment]
Each download  notification show progress made

**Comment by ravig252525** [comment]
For video  post  processing try this library com.googlecode.mp4parser:isoparser:1.1.22

**Comment by gkeegan** [comment]
For your first part, are you requesting a progress bar within the notification?

For the second, please make a separate issue that explains how this would be better than the current solution.

**Comment by ravig252525** [comment]
Downloading start before  show progress in notification like UC browser

**Comment by ravig252525** [comment]
https://www.youtube.com/browse_ajax?action_continuation=1&direct_render=1&target_id=section-list-557023&continuation=4qmFsgKWARIPRkV3aGF0X3RvX3dhdGNoGoABQ0FoNlhFTnBkMEZCUjFaMVFVRkdTbFJuUVVKVFZUUkJRVkZDUjFKWVpHOVpXRkptWkVjNVptUXlSakJaTW1kQlFWRkJRVUZSUlVKQlFVRkNRVUZGUVVGQ1FVRkhUSHBtYkhGNmIyeFBSVU5OWjI5Sk56bGxSV3htVkVwZlRsSTVCAA%253D%253D


This link not download html why check this YouTube  home next ajaxpage

**Comment by ravig252525** [comment]
How to implement notification progress download

**Comment by kapodamy** [comment]
@ravig252525 i tried in the past but the library holds all audio/video data in the RAM.  Example: for a mp4 video of 2Gb you need a device with more that 2Gb of RAM.

**Comment by ravig252525** [comment]
How  to notification implement in gigaget download library for each
download  new notification with progress bar show

**Comment by Stypox** [comment]
Closing in favour of #332
