### ISSUE TITLE
Video automatically starts playing, upon screen lock, in the background even if it was paused

### ISSUE THREAD

**Issue by Juni4567** [TeamNewPipe/NewPipe#2239]
Steps to reproduce the issue:
1. Set minimize behavior to "Minimize to background player" in the settings
2. Now play a video 
3. Pause the video and lock your phone screen by pressing the power button
4. The video which was paused started running in the background mode 

Solution:
It should only keep running in the background if the video was not paused

- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by fightthepower** [comment]
I was going to report this issue. When I pop up the video then pause it and lock the screen. The video automatically starts to play after a while.

**Comment by ciborge** [comment]
Same behaviour here with note 9

**Comment by pietervw** [comment]
Same issue on a Galaxy S8 on Android Pie while connected to Bluetooth (haven't tested without BT yet but probably unrelated)

**Comment by ildar** [comment]
dup https://github.com/TeamNewPipe/NewPipe/issues/2395 ?

**Comment by Juni4567** [comment]
Yes @ildar that's a duplicate

**Comment by Stypox** [comment]
Closing in favour of #2395
