### ISSUE TITLE
Icons for Icon and List

### ISSUE THREAD

**Issue by glor** [TeamNewPipe/NewPipe#2246]
The icons for switching between list and icon are switched. As you can see, I am already in list mode but the icon is a list.  
![photo_2019-03-23_19-28-43](https://user-images.githubusercontent.com/1354608/54870082-3a51f080-4da2-11e9-9872-d2178693d0e5.jpg)

**Comment by gkeegan** [comment]
Yeah I noticed this too. I thought it might just be a design choice but idk.

**Comment by TobiGr** [comment]
@kapodamy provided a fix for this in #2149, but closed his PR due to no free time. I guess, there will be a new PR sooner or later.

**Comment by kapodamy** [comment]
my bad, fixed
