### ISSUE TITLE
.opus file in Downloads doesn't find VLC 

### ISSUE THREAD

**Issue by Apfelkuchen1234** [TeamNewPipe/NewPipe#2248]
Hi, great app and I really like it. I can finally listen to YouTube videos without screen on or downloading GB of videos I will only listen to.

My minor problem is, if I go to Download (in NewPipe)  and open an .opus file, I get the error: "No app to open file installed." (Translated from germany) But I can open the file from Simple File Browser in VLC and I can open mp4 and m4a from the app NewPipe/Downloads in VLC.

I don't know if the issue is with NewPipe or VLC or my settings (of my tablet and phone)

I also asked VLC https://forum.videolan.org/viewtopic.php?f=35&t=148768

Thanks for reading, and it is only a minor inconvenience  for me.

**Comment by gkeegan** [comment]
I'm pretty sure opus files aren't technically supported by android, but ogg (vorbis), which is basically the same thing, is supported.

**Comment by theScrabi** [comment]
Na vobis and opus are something diferent. Both should work with a modern phone.

**Comment by gkeegan** [comment]
Ah I was mistaken. I did some more research and learned that they can both be contained with in ogg, but have different features, quality, etc. I guess it must have been just EMUI, as I just tested on a different device, and opus works fine.

**Comment by Apfelkuchen1234** [comment]
Well I can start .opus files in VLC and from other apps via VLC... and with simple music player

Someone in the link thinks it could be a mine type error

Not sure about that.

Anyhow thanks

**Comment by Popkornium18** [comment]
Android only supports Opus codec with the .ogg extension. Try renaming the file. Some apps and custom Roms might support the .opus extension though (like VLC and LineageOS).

**Comment by dakotagrvtt** [comment]
I've had this problem for awhile. I have to go into my file manager and click on the file for it to automatically play in VLC. It must be something on Newpipe's end because .opus does work fine in VLC.

**Comment by Stypox** [comment]
Closing in favour of #2542
