### ISSUE TITLE
Background player stops playing a few seconds after locking the screen

### ISSUE THREAD

**Issue by Brn9hrd7** [TeamNewPipe/NewPipe#2250]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I've noticed that the background player stops playing around 12 seconds after locking the screen of my phone(the player continues immediately after unlocking the screen). The first time this issue occurred was two days ago, and I was able to solve it by going to Settings->Apps->NewPipe and stopping the app there. Today this issue occurred again, but now the solution that worked two days ago doesn't work anymore. I´m using version 0.16.1 since it has been released, not sure why this started happening just two days ago.

Phone: Huawei P10, Android Version 8.0.0

**Comment by Stypox** [comment]
Probably this is a battery-saving measure imposed by your system... have you checked NewPipe is allowed to run in background and send background network requests?

**Comment by Brn9hrd7** [comment]
Yes, that was the problem. It was set to 'automatic', after setting it to 'manual' and allowing running it background it works without problems. Thanks for the quick response.
