### ISSUE TITLE
YouTube changing file size so that 480p uses less space than 360p

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/NewPipe#2252]
So basically the image is self-explanatory. The file sizes do not match what they should be, at all.

![Image](https://i.imgur.com/ZF8A98R_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

Yes, I watch Minecraft videos.    

Edit: for some reason the formatting of this post is weird for me. Apologies if it looks weird for anyone else.

**Comment by goxr3plus** [comment]
Hm that's strange indeed

**Comment by Serkan-devel** [comment]
Maybe the compression rates are different for each format

**Comment by gkeegan** [comment]
I believe that must be the case. 60fps videos have significantly less quality than their regular counterparts.

Since this is no fault of NewPipe, I will close this issue.

**Comment by Serkan-devel** [comment]
Are you shure? That was just a guess, I don't know if 60fps comes with a lover quality actually
