### ISSUE TITLE
Do not show "History" in context menu if "History & Cache" disabled in "Settings"

### ISSUE THREAD

**Issue by Symbian9** [TeamNewPipe/NewPipe#2254]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

![pic.1](https://i.imgur.com/3nPj4jO.png)

![pic.2](https://i.imgur.com/lDBK798.png)

**Comment by TobiGr** [comment]
I think the whole menu can be remove as its content is available through the navigation drawer. @theScrabi Is there a reason why it has not been remove yet?

**Comment by karkaminski** [comment]
Hey, I would like to make this one (as my first-ever OS issue). Is it still available?

**Comment by Stypox** [comment]
Yeah, this is still available @karkaminski 
What needs to be done is removing the duplicate three-dot menu and disable the History button in the navigation drawer when the user asked not to store history.
Feel free to ask any question, and thank you :-D

**Comment by karkaminski** [comment]
(I think) I completed the task but need support with git-stuff ;)
This is what I've done so far:
1. Forked and cloned NewPipe repo
2. Created new branch (name: issue-#2254)
3. Completed the task: removed dot-menu where it is no longer needed and implemented disabling History button according to settings
4. commited (2 commits) and pushed to github
What should I do next...? :)

**Comment by Stypox** [comment]
Go [to your branch on GitHub](https://github.com/karkaminski/NewPipe/tree/issue-%232254) and click on the "Pull request" button just above the file browser

**Comment by mauriciocolli** [comment]
If this is to be kept, maybe we should think about making the navigation drawer available application-wide as well?

Very annoying that you have to quit everything for changing a single setting.
