### ISSUE TITLE
Feature Request: If ready to, deprecate 4.4 KitKat in the non-legacy release.

### ISSUE THREAD

**Issue by SC1040-TS2** [TeamNewPipe/NewPipe#2259]
- [Yes.] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [Yes.] I checked if the issue/feature exists in the latest version.
- [N/A.] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Greetings. Since it has been a few release versions since the minSDKVersion was moved up to 19 and Android 4.1-4.3 Jelly Bean was deprecated in the main version, I now return to ask about the end goal of that prior request: Leaving building for the Dalvik VM behind in favor of pure ART development.

Such a thing may be a problem in regard to backporting code to the legacy release where possible, but that is an assumption based on my limited understanding of how the application would be built differently for each runtime environment.

If those working on both the mainline and legacy releases feel they could handle such a shift, I would be pleased to see it come about by the 17.0 or 18.0 version release. If not, then it is no problem.

Anyway, good day, and regards for now.

**Comment by SC1040-TS2** [comment]
That is the idea, @Symbian9 . This would only be implemented as part of a major version release, such as 17.0 or 18.0. However, given the track record of prior releases that version may not be far off.

**Comment by fortunewalla** [comment]
I have a Blackberry z30. I used to use SuperTube, a native BB YouTube application but it stopped working. I now use NewPipe by installing the APK. It works very well with all the features including background play. The OS Version gives: `qnx Android 4.3-18`. 

I don't know for how long it would be possible but I hope you continue to offer support to the Blackberry Android system. It is probably the only youtube app that works on the Blackberry. Thanks for such a wonderful app.

**Comment by SC1040-TS2** [comment]
From what I understand, @fortunewalla, support for the BlackBerryOS version you have(A variant of Android 4.3 Jelly Bean) has already been removed from the main app version for some time now.

However, there does exist a NewPipe Legacy app for those on Jelly Bean devices, currently maintained by @friendlyanon and I believe @Brimont alongside Schabi.

Its F-Droid repository link is here: https://f-droid.org/en/packages/org.schabi.newpipelegacy/ .

**Comment by fortunewalla** [comment]
@SC1040-TS2 I was using NewPipe `0v0.14.2`. Yesterday the decrypt error started and I came across your issue while searching for a solution. I never knew NewPipe stopped supported `4.1-4.3`

I'm so glad that @friendlyanon is maintaining a legacy version. Thanks for the link. It works on the Blackberry. Hope the legacy project will continue for a long time.

**Comment by opusforlife2** [comment]
Was this the point of the legacy release?

**Comment by Stypox** [comment]
@SC1040-TS2 what would be the advantages of moving to pure ART? I don't think this should be done, unless there are important performance/reliability enhancements

**Comment by wb9688** [comment]
@Stypox: There is no difference in the bytecode, ART is fully backwards compatible with Dalvik.
