### ISSUE TITLE
Release of v0.16.2

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#2260]
Please i am waiting for the play in background directly feature, it is implemented but when the next release will happen :)?

Do a small relase soon  my lords. I am waiting long time for it.

**Comment by ouzowtf** [comment]
You could maaaaaaaybe be a little less demanding

**Comment by goxr3plus** [comment]
@ouzowtf  :)

**Comment by TobiGr** [comment]
This should happen soon.

**Comment by goxr3plus** [comment]
Waiting my lord waiting
