### ISSUE TITLE
org.schabi.newpipe.debug E/class org.schabi.newpipe.report.ErrorActivity: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException:

### ISSUE THREAD

**Issue by cion49235** [TeamNewPipe/NewPipe#2261]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment]
Please read the contribution guidelines.
