### ISSUE TITLE
Newpipe Stuck at post-processing donwloaded videos

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [TeamNewPipe/NewPipe#2264]
- [] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Hi,
So I downloaded the following video through new pipe;
https://www.youtube.com/watch?v=WShlkAOI7XQ
and after downloading the video the newpipe is stuck at post processing at 0%.
It's been an hour.
The video does not have any audio so I was thinking is there anyplace else where new pipe saves the audio before merging it with the video.

**Comment by TGWGitHub** [comment]
Same here..

**Comment by kapodamy** [comment]
in what format and resolution?

**Comment by Ashutosh-Kukreti** [comment]
I think it’s with all the format and resolutions
I tried 480p and 360p

**Comment by kapodamy** [comment]
confirmed

**Comment by TGWGitHub** [comment]
@kapodamy

For me it's 480, 1080 and 2160

**Comment by azzamsa** [comment]
I think it's an important issue. I have to force kill NewPipe multipe times and wait for  a luck.

Could we bump into 0.16.2 to include this important fix ?

**Comment by Abdulssamiu** [comment]
what algorithm used in Newpipe

**Comment by gkeegan** [comment]
@Abdulssamiu Can you please explain what you mean?

**Comment by Abdulssamiu** [comment]
I was asking the algorithm used to create NewPipe. As we now when you
create an application thier is a certain algorithm you use.
