### ISSUE TITLE
How to show the youtube search on android studio?

### ISSUE THREAD

**Issue by kurniaweb1** [TeamNewPipe/NewPipe#2265]
How to show the youtube search result as default main page while opening the app on android studio?

**Comment by TobiGr** [comment]
I am not quite sure what you want to do. But you can add blank page as main page. There is no 
And what do you want to do with Android Studio?

**Comment by gkeegan** [comment]
I believe kurnia wants to find a way to change the default in the code to the search page. But I don't think this is possible anyways right now.

**Comment by kurniaweb1** [comment]
I want the settings that I made will appear when the new application installs on the cellphone.
how do I make the settings that appear when new applications are installed on the cellphone?
How do you apply it to the Android Studio source code?

**Comment by kurniaweb1** [comment]
example:
I want the default settings when the new application is installed, the settings that I expect will appear, such as settings for keyword searches. How do you apply it to the Android Studio source?
