### ISSUE TITLE
[feature request] Remove the trashcan icon in the download section or change its fonction

### ISSUE THREAD

**Issue by kyungjin** [TeamNewPipe/NewPipe#2267]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hello
Taping the trashcan icon in the download section deletes the downloads list, but doesn't delete the files. I find this useless since I like to view from the app what downloaded files are still on my device, without using my file manager. And I didn't find any way to get back the list.

Would it be possible to remove this (according to me) useless icon ?
Or change its usage. For example, if we could have the possibility to check items in the downloads list and delete them (and the files) at once, instead of having to delete files one by one by the dot menu.

**Comment by ouzowtf** [comment]
And I like how it currently works and wouldn't want the icon to be removed.

**Comment by gkeegan** [comment]
I agree with ouzowtf. Having the icon delete all files would be problematic, as it could cause people to have to re-download all their videos. Having it simply clear the download list is much better.

**Comment by dankxylese** [comment]
maybe a confirm window to warn people? would be a good compromise

**Comment by gkeegan** [comment]
It isn't really necessary for a confirm window. The files are all still there.

**Comment by kyungjin** [comment]
The files are still here but we don't know it. 
The function of this trashcan icon isn't explicit enough I think. The first time I used it, I thought it was a bug that the files weren't deleted.

**Comment by B0pol** [comment]
Fixed by #2717 (we can now delete files)
