### ISSUE TITLE
> I cannot reproduce this. Can someone please post the full error report. 

### ISSUE THREAD

**Issue by cion49235** [TeamNewPipe/NewPipe#2269]
> I cannot reproduce this. Can someone please post the full error report. @cion49235 Next time please use the [crash report converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) which is linked in every new issue. The info you posted there only helps us particularly. And in this case, I cannot reproduce your problem because the important info is missing.

This error does not occur for a specific period of time 
It is not a precise reason, but error or pause occurs for a certain time when decrypting from NewPipe when the URL changes or updates on YouTube side

If this error occurs, the error will disappear after 24 hours or a day or two
I've already had 2 experiences
Despite not using version 0.16.1
It has been activated again
Have you updated the NewPipeExtractor Core File?
I am wondering if core files will be modified in real time
Ex)
implementation 'com.github.TeamNewPipe:NewPipeExtractor:f7c7b9df1a'

_Originally posted by @cion49235 in https://github.com/TeamNewPipe/NewPipe/issues/2262#issuecomment-479711137_

**Comment by cion49235** [comment]
I always appreciate the NewPipe team.

**Comment by TobiGr** [comment]
I guess this was opened by accident. Please see [my reply](https://github.com/TeamNewPipe/NewPipe/issues/2262#issuecomment-479824905) in the original thread
