### ISSUE TITLE
Illegal copy on Google Play

### ISSUE THREAD

**Issue by niansa** [TeamNewPipe/NewPipe#2270]
https://play.google.com/store/apps/details?id=com.sct.yourtv <-- Does anyone manage to get this removed from Play Store? This is modified NewPipe (added adverts and changed name) without license note.

**Comment by gkeegan** [comment]
Please post this in #539 after checking if it isn't already there.

**Comment by TobiGr** [comment]
Thanks! I'll close this, because the info is now in #539
