### ISSUE TITLE
Trending tab changes translation several times

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#2272]
Just after start:
![image](https://user-images.githubusercontent.com/14617699/55677218-95c8c600-58ec-11e9-81f7-d0a340de1027.png)

Some time later:
![image](https://user-images.githubusercontent.com/14617699/55677220-9bbea700-58ec-11e9-8a60-3b4953159352.png)

Some time later:
![image](https://user-images.githubusercontent.com/14617699/55677218-95c8c600-58ec-11e9-81f7-d0a340de1027.png)

**Comment by 532910** [comment]
My phone language is English (United States) and my geographical location is Russia.

**Comment by B0pol** [comment]
It has been fixed with #2921. Go to Settings -> content -> app language, and set your language. It won't change

**Comment by 532910** [comment]
I don't' want to change it, I want it to be taken from the device settings.
