### ISSUE TITLE
Incorrect Belarusian translate

### ISSUE THREAD

**Issue by minsk21** [TeamNewPipe/NewPipe#2273]
![en](https://i.ibb.co/zJkYcyx/Partial-Screenshot-20190407-064201.png)

![by](https://i.ibb.co/WFXHM5p/Partial-Screenshot-20190407-064237.png)

**Comment by minsk21** [comment]
Correct translation

Enqueue on new popup = У чаргу "У акне"

**Comment by theScrabi** [comment]
U can use our weblate to update translations. Please se our contribution guidelines for that.

**Comment by minsk21** [comment]
I'm not programmer. What is this about

**Comment by TobiGr** [comment]
[Weblate](https://hosted.weblate.org/engage/NewPipe/) is a translation platform. You can register with your GitHub account and translate the Strings. This allows us developers to concentrate on programming while translators can submit and change translations at their own.

**Comment by minsk21** [comment]
Fixed in Weblate.

**Comment by TobiGr** [comment]
Thanks!
