### ISSUE TITLE
Video plays in popup mode when a call comes in

### ISSUE THREAD

**Issue by test2a** [TeamNewPipe/NewPipe#2274]
I recently discovered the popup player on the app after a long time. Anyways, since the last update I think whenever I am watching a video and a call comes in, the video goes to popup mode and continues to play on a low voice. That should not happen. It should just pause. 

I have minimize on app switch set to popup mode but getting a call should not be considered as app switching.

**Comment by opusforlife2** [comment]
@test2a Is this still an issue in 0.20.0? Just tried this, and it works normally.
