### ISSUE TITLE
NewPipe not playing videos with less views

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [TeamNewPipe/NewPipe#2275]
Dear Newpipe team,

I tried playing the following video and then tried playing some other videos with no or less views and new pipe is not playing them.
I'm using the lastest version of newpipe v0.16.1 on samasung j2
https://www.youtube.com/watch?v=Y6ECVaJeuoM

**Comment by justanidea** [comment]
Im able to read this video 👍

**Comment by Ashutosh-Kukreti** [comment]
But I’m not able to watch it,newpipe did not loads the video,I’m having a lot of problem with this version can I migrate back to an older cersion?will it work?

**Comment by gkeegan** [comment]
Going back to an older version will not work, as version 0.16.1 has the fixes for when YouTube changed how they give videos again.

**Comment by Pentaphon** [comment]
I noticed videos posted within an hour are very difficult to get to play. Took me like 5 tries to play a video that just came out.

**Comment by jimbo1qaz** [comment]
I haven't experienced this issue, but I'm guessing newpipe doesn't support some of the codecs (video+audio, video, audio) delivered by Youtube (new videos don't have all codecs right away).
