### ISSUE TITLE
Display comment replies

### ISSUE THREAD

**Issue by BaumGuard** [TeamNewPipe/NewPipe#2277]
It's great that NewPipe has the feature to view comments since the version 0.16.0! But I miss a function to view the answers of the comments.

**Comment by hp8wvvvgnj6asjm7** [comment]
Anyone working on this?

**Comment by lu4p** [comment]
Would appreciate this feature as I often open YouTube in Firefox to read the comments.

**Comment by Gymcap** [comment]
Maybe have the comment answers collapsed by default to keep from taking up too much space. You could tap a down arrow to reveal the comment answers. This could result in showing 5-10 answers with a "show more" at the bottom of the comment thread.

**Comment by Mhowser** [comment]
Any progress on this?

**Comment by chekmanh** [comment]
I think this is a really nice feature, would really appreciate it

**Comment by alittlebitofit** [comment]
By "answers of comments", does it mean replies to comments as in a comment thread?

If yes, then yes I want this feature too.

Is there any update on this feature?

**Comment by opusforlife2** [comment]
Yup. That's what it means. Which means one less issue for you to open. :P

**Comment by alittlebitofit** [comment]
Haha yea :P

So any update?

**Comment by opusforlife2** [comment]
Nyope.

**Comment by alittlebitofit** [comment]
Ah well, atleast 33.33333% of my issues are solved.

**Comment by Invisible3ck** [comment]
I’d like this feature, too. Hopefully it gets added one day.

**Comment by Oizaro** [comment]
> I’d like this feature, too. Hopefully it gets added one day.

If the creators of newpipe are waiting for someone to implement it, I believe we will not see this feature until 2050.

**Comment by NewNewPipe** [comment]
Hello.
With the help of mhmdanas I would like to add what I miss the most in NewPipe nowadays.

The functionality / ability to save all the comments under the movie together with the answers (tree structure) to TXT, HTML, PDF file would be very useful.

**Comment by Kohoshi12** [comment]
Freetube implemented this feature.

**Comment by cyberkollider** [comment]
I am also interested in this feature, including timestamps.

**Comment by Gottarocket** [comment]
+1 for this

**Comment by ShareASmile** [comment]
This feature is being worked upon in this PR on the extractor side:
https://github.com/TeamNewPipe/NewPipeExtractor/pull/576

@TiA4f8R this issue should be linked to the Comments-Reply PR to auto close.

**Comment by TiA4f8R** [comment]
Not really to auto-close, because this PR only implements replies for the YouTube service.

**Comment by opusforlife2** [comment]
Moreover, even if the Extractor PR is merged, we'd still need a Newpipe PR to be merged before we can consider the feature implemented.

**Comment by ShareASmile** [comment]
Ok, thanks for correction, well then we can say Extractor PR is the first step in the implementation of youtube  comments reply feature. Other services can be dealt later.

**Comment by opusforlife2** [comment]
@BaumGuard Did you specifically have Youtube comments in mind? Or did you mean comment replies for all services? Please feel free to revert the title change if it's the latter.

**Comment by opusforlife2** [comment]
There. Now a PR for Newpipe will be able to link to this issue, and close it when merged.

**Comment by FriendlyNeighborhoodShane** [comment]
For anybody following the issue: the PR linked above has been closed and succeeded by this one:
https://github.com/TeamNewPipe/NewPipeExtractor/pull/703

**Comment by TobiGr** [comment]
Extractor changes have been merged. Someone needs to do the app part of this enhancement

**Comment by kyoyacchi** [comment]
Any updates?

**Comment by opusforlife2** [comment]
@kyoyacchi There is a linked PR that is under development. You can help test the PR by installing the APK from there.

**Comment by nicoursi** [comment]
#7244 has been closed. Could it be possible to put this issue in #6448 so that someone could take over? This feature is already partially implemented and it is a pity to letting it being abandoned.

**Comment by opusforlife2** [comment]
Done. 👍

**Comment by AudricV** [comment]
I changed back the title to generalize again this issue because the UI needs to support multiple comment levels.

It would be probably not worth it to implement a first temporary UI to support YouTube replies and then a second and general UI for YouTube and PeerTube, which can have multi-level threads, unless someone is able to do so.

Extractor changes should probably need to be done first to be able to support multi-thread comments properly.

In order to not have waterfall issues (I mean at a certain thread count a very small space for the comment itself), I think using the following structure is the best option we have (that's what YouTube partially use in their mobile app too):

<img src="https://user-images.githubusercontent.com/74829229/177427867-e2307694-d99c-4d11-8866-c96f09c006dc.jpg" width="300px" alt="comment_replies_ui_idea">

Where:
- in green: a back button;
- in blue: a title such as `Replies` or `Comment replies`;
- in yellow (maybe): the comment which has its replies shown below;
- in red: comment replies (which can have replies too, which may be the case on PeerTube).


Note that I don't know if this programmatically doable, I have no real knowledge in Android development.

Help is wanted for this feature.

**Comment by krlvm** [comment]
@AudricV @Stypox What's your opinion on using bottom sheet to display replies?

**Comment by Stypox** [comment]
Do you mean, something that slides in from the bottom, and that the user is able to close by swiping down from the top bar?

**Comment by krlvm** [comment]
> Do you mean, something that slides in from the bottom, and that the user is able to close by swiping down from the top bar?

Yes. Some other UI elements can also be replaced with this as part of UI refresh.

**Comment by xz-dev** [comment]
> 

Such a design like PeerTube would look ugly on newpipe at this stage, because the player position is not fixed on top.
So I'm going to implement it the way youtube shows it and RP it.
What do you think?

**Comment by xz-dev** [comment]
> @AudricV I really like that design and was also what I was thinking about. Once the extractor has a stable API for comment replies access, including replies, I can work on the UI or we could have a call.

Such a design like PeerTube would look ugly on newpipe at this stage, because the player position is not fixed on top.
So I'm going to implement it the way youtube shows it and RP it.
What do you think?

**Comment by ygz213** [comment]
This is the most important missing feature in my opinion. It is weird to see this issue still undone for 3 years

**Comment by opusforlife2** [comment]
@ygz213 You're most welcome to open a PR.

**Comment by ygz213** [comment]
@opusforlife2 I am not interested in Android programming.

**Comment by xz-dev** [comment]
> @ygz213 You're most welcome to open a PR.

If you think it can do right now, I will progam it next days and PR it, I just not sure it's there anyone coding for it.

**Comment by opusforlife2** [comment]
@xz-dev No one else is coding this. A PR is most welcome. But you're waiting on @AudricV's answer, aren't you?

**Comment by xz-dev** [comment]
> @xz-dev No one else is coding this. A PR is most welcome. But you're waiting on @AudricV's answer, aren't you?

Because I see that he has something special in mind, but I may not be available after a few days, so I'll start now.

**Comment by Mhowser** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/7244

**Comment by AudricV** [comment]
@xz-dev Hmm, I don't understand the problems you raised.

> Such a design like PeerTube would look ugly on newpipe at this stage

What is really the difference of PeerTube's comment's UI with the one of YouTube? For me they are using the same UI principles, except the fact there is not only one replies level on PeerTube.

> the player position is not fixed on top

I don't see a link with the player and comment replies. What does the player have to do with comments and/or their replies?

> it need a lot of code and test

Yes, even if it seems to be a small feature for users, it requires a lot of changes in the codebase for it. Don't be discouraged by this!

**Comment by xz-dev** [comment]
> @xz-dev Hmm, I don't understand the problems you raised.
> 
> > Such a design like PeerTube would look ugly on newpipe at this stage
> 
> What is really the difference of PeerTube's comment's UI with the one of YouTube? For me they are using the same UI principles, except the fact there is not only one replies level on PeerTube.
> 
> > the player position is not fixed on top
> 
> I don't see a link with the player and comment replies. What does the player have to do with comments and/or their replies?
> 
> > it need a lot of code and test
> 
> Yes, even if it seems to be a small feature for users, it requires a lot of changes in the codebase for it. Don't be discouraged by this!

The main idea I'm trying to convey is that I often view comments while watching a video, and by default the video is slid off the screen, so I usually enable the video popup.
So, with AudricV showing, full screen display comment like that would completely cover the video, or the comment section would be covered by the hovered video popup window.

**Comment by AudricV** [comment]
> The main idea I'm trying to convey is that I often view comments while watching a video, and by default the video is slid off the screen, so I usually enable the video popup.

You don't have to care with the feature of showing player while showing one of the content tabs (description + metadata, comments, related items). This is a separate feature request, and from a code perspective, comments and video are separated.

If the player is made sticky at some point, it should not change the comments UI except the height used for comments, that's it.

> So, like AudricV showing, full screen display comment like that would completely cover the video, or the comment section would be covered by the hovered video popup window.

My UI concept talks about the comments UI but it doesn't talk about the `VideoDetailFragment` itself.

> So, I'll follow https://github.com/TeamNewPipe/NewPipe/pull/7244 and patch on it.

Free feel to do so but this model has some issues in the future, requiring at least that you fix them. However, in my opinion, the UI I presented seems to be more readable for users.

**Comment by xz-dev** [comment]
> Free feel to do so but this model has some issues in the future, requiring at least that you fix them. However, in my opinion, the UI I presented seems to be more readable for users.

fine, I'll try to let it like that, in order to not have waterfall issues.
![Screenshot_20220924-221725_YouTube](https://user-images.githubusercontent.com/32761048/192103039-b949d2a6-a8b4-401e-a2b4-5ccfbb53cbbe.png)

**Comment by AudricV** [comment]
That's from where my idea comes from! Thank you :)

**Comment by xz-dev** [comment]
I'm done, I cann't wait seeing merged.

**Comment by litetex** [comment]
Just my 5 cents on this topic regarding comments.

The [Infinity for Reddit](https://github.com/Docile-Alligator/Infinity-For-Reddit) app already has nested comments implemented:
![grafik](https://user-images.githubusercontent.com/40789489/222828772-af2b6417-2f4a-48b8-8081-fbe8252f3e04.png)

Maybe some code from them could be reused (however be careful with the license) or inspiration taken from.

**Comment by JacksonChen666** [comment]
> The [Infinity for Reddit](https://github.com/Docile-Alligator/Infinity-For-Reddit) app already has nested comments implemented:
>
> [image](https://user-images.githubusercontent.com/40789489/222828772-af2b6417-2f4a-48b8-8081-fbe8252f3e04.png)
>
> Maybe some code from them could be reused (however be careful with the license) or inspiration taken from.

seems to be [already planned (kind of)](https://github.com/TeamNewPipe/NewPipe/issues/2277#issuecomment-1175571858)

**Comment by Gottarocket** [comment]
@litetex Libretube has comment replies. They use newpipe extractor so some code can be similar and be used
