### ISSUE TITLE
[Feature request] "Expose" media data

### ISSUE THREAD

**Issue by utack** [TeamNewPipe/NewPipe#228]
Android seems to support exposing metadata of the stuff an app is playing, for generic Music widgets and other stuff (lockscreen background?)
Would be cool if you could add support that with the data from the "play in background" notification. Title as Music Track Title, Channel as Artist and the static video previews image as album cover.

**Comment by theScrabi** [comment]
Yes, I already thought about that. I just don't know when I will stumble across it.

**Comment by Mmedic23** [comment]
Not sure if commenting on a 2 year old post is frowned upon but.. Still waiting on this? Video thumbnail as lockscreen background seems like a pretty good feature for background playback mode.

**Comment by theScrabi** [comment]
Yes this is a feature I would also celebrate deeply.

**Comment by RuthlessRuler** [comment]
Any updates on this Issue?

**Comment by Stypox** [comment]
@RuthlessRuler you can see more discussion in #2453, though there are no recent updates

**Comment by wb9688** [comment]
For Android's lockscreen thingie, we need to use https://developer.android.com/reference/android/app/Notification.MediaStyle. I don't think that'd be hard to implement.
