### ISSUE TITLE
Buffering fails after long pause

### ISSUE THREAD

**Issue by youssefchrome** [TeamNewPipe/NewPipe#2281]
After a longe pause (background audio player) the buffering process does not restart. The audio will stop when it reaches the end of the buffer, and no new data is buffered again. The audio needs to be restarted in order to continue listening. This problem occurs in long audio's like lectures etc. (Around 10 minutes or larger)

**Comment by ritiek** [comment]
I'm guessing this is because the YouTube content URL expires after some time. One way to fix would be to keep a check on whether the content URL has been expired and fetch the new content URL if so.

**Comment by barbrastreisand** [comment]
I get this also with videos that are typically longer than 30 minutes (DJ mixes etc). Bit annoying since I leave it on while I drive, and then it just pauses and I'm sat there in silence. Still, the fact that there even is a background player is fantastic.

**Comment by CptSpaceToaster** [comment]
Seeking around does not repair the buffer/stream. The video needs to be restarted to refresh the content URL, losing progress in videos that are longer than 30 minutes (lectures, mixes, podcasts, etc)

**Comment by Stypox** [comment]
Caused by #938
