### ISSUE TITLE
Feature Request: Save Caption in Download Dialog

### ISSUE THREAD

**Issue by magi44ken** [TeamNewPipe/NewPipe#2284]
In the download dialog, add an option to download and save caption, including the auto-generated caption. It is also nice to be able to select and download multiple language captions.

**Comment by kapodamy** [comment]
What do you mean?
![Screenshot_1540512108](https://user-images.githubusercontent.com/16857233/56250094-add6dd00-6084-11e9-94dd-8f2048e9e631.png)
