### ISSUE TITLE
Divide by Zero error while post-processing webm files and doubling filesize

### ISSUE THREAD

**Issue by solarelf** [TeamNewPipe/NewPipe#2291]
Hi! Thank you for your app! I would like to contribute by documenting a severe bug. I hope this will be corrected soon.
You may contact me for details.

THE ISSUE

**Type**: BUG
Applies to: New Pipe
Version 0.16.2 (non -legacy)
Permissions: all requested permissions are granted

**Device and OS data**: 
Name: Samsung Galaxy Tab S4 
Model: T835N
Firmware: T835NKOU2ARI1
Core: 4.4.78-14803871
gcc version: 4.9.x 20150123 GCC)
Android Oreo 8.1 Build: M1AJQ.T835NKOU2ARK4
Latest security patches applied (versions on request)

**Device app running environment**:

- Processor: SnapDragon 845 MSM8998
- Processor load: typically around 30%
- GPU: Adreno 540
- Available memory: ~3Gb of 6Gb total
- Available storage: 200 Gb inner SSD, no SD card, no added encryption layer
- Network: Wi-Fi connected to my iPhone XS Max hotspot on 4G LTE rated at 50Mbits/sec max, 30 Mbits/sec.sustained speed
- Network encryption layer: ProtonVPN, IKE v.2 128 AES
- Network link quality: good/excellent, latency below 150ms, no frame dropouts, no streaming buffering at max resolution and FPS

**Bug manifests itself**:
- on downloading *.webm videos to inner storage

**Bug type**: failed post-processing, corrupted output

**Bug error string as displayed, occasion A** (25% of cases)
   "Code: 1007
   Post-processing failed
   java.io.EOFException: parser go beyond limits of the Element. 
   type=0xf43b675 offset=146934910 size=3843765 
   position=150845079"

**Bug error string as displayed, occasion B** (75% of cases)
   "Code: 1007
   Post-processing failed"

**Bug significant features**: 
- no post-processed file is created, only downloaded file from stream remains on disk
- the downloaded file may contain very rare occasional MPEG blocking defect
- the downloaded file can be played with some advanced players like MX Player Pro and VLC Player but not simple built-in Video Player by Samsung which produces error on open
- the downloaded file can not be searched (obviously no index was created)
-  for the downloaded file, occasionally some moderate frame dropping occurs with no slowdown in playback. These are not connected with high CPU/GPU load.
- _On one occasion_ (2160p 30 fps) video was played back extremely slow while audio was played back at normal speed)

**Bug peculiar feature:** just before the exception occurs, the size of the file displayed on the download page on a stripe with file and progress details, multiplies by 2

**Experimental data**:

Files tested: 
3 files, ranging from dozens to thousands megabytes in size
Resolutions tested: 
1440p, 2160p
FPS tested: 30p/60p
Total tests: 12
Bug manifested at rate: 100%

**Reference file to test** (selected as the best one to demonstrate):

https://www.youtube.com/watch?v=1La4QzGeaaQ

**Screenshots**:
![Screenshot_20190416-200737_NewPipe](https://user-images.githubusercontent.com/42090132/56232522-a6660280-6089-11e9-8c29-3ee038074827.jpg)

![Screenshot_20190416-205401_NewPipe](https://user-images.githubusercontent.com/42090132/56232588-cdbccf80-6089-11e9-86a6-5e5f784ae9e5.jpg)

This is all info I could extract and carefully prepare for the Developers. If anybody has something to add or, request additional experiments, please let me know.

And again, many thanks to you all guys!

**Comment by kapodamy** [comment]
fixed in #2149, but the muxer does not support high resolutions. I'll take a look tomorrow

**Comment by solarelf** [comment]
Any news guys?

**Comment by solarelf** [comment]
Nothing has changed. The issue has not been resolved.

![Screenshot_20190620-142617_NewPipe](https://user-images.githubusercontent.com/42090132/59846030-85f74480-9367-11e9-8a68-565d0ffd81db.jpg)

**Comment by Stypox** [comment]
@solarelf It will change in the next version. The issue has been closed since the bug has been fixed, but the new version containing the bugfix has not been released yet.

**Comment by solarelf** [comment]
2321# seems to come back now ((( is there a chance for ax working fix that will be a more permanent solution to this?
