### ISSUE TITLE
Allow editing remote playtlists (editable bookmarks)

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#2293]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

please add ability to edit names for playlists and videos in playlists and search by names

**Comment by hp8wvvvgnj6asjm7** [comment]
This already is possible, but only for playlists you created. If you added a playlist from another source, you can't. That is why I added a feature request for merging bookmarked playlists.

**Comment by anpic** [comment]
> This already is possible, but only for playlists you created.

no :(
video names aren't editable

**Comment by mhmdanas** [comment]
Closing in favor of https://github.com/TeamNewPipe/NewPipe/issues/3695.
