### ISSUE TITLE
Feature Request: avoid recurs

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#2294]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

please add option to prevent adding the same video multiple times to one playlist

**Comment by Redirion** [comment]
as new options are not welcomed by the maintainers: what about an alertdialog like "This video is already on this playlist."
Buttons: "Add again at the end" "Move existing to end of queue" "Abort"

**Comment by Stypox** [comment]
Closing in favour of #1473
