### ISSUE TITLE
Feature Request: Open youtube link in youtube page, not video

### ISSUE THREAD

**Issue by ThaChillera** [TeamNewPipe/NewPipe#2296]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I set my phone to automatically open Youtube links in newpipe, as described [here](https://github.com/TeamNewPipe/NewPipe/issues/2160#issuecomment-474178682). However, this link automatically opens the video, not the page itself. If the video has addittional info in the description, or I want to read comments etc, I need to manually search for the video in newpipe. 

Can links (optionally) open the video page instead of the video itself? Or can I enable that pressing back will first bring me to the video page before sending me back to the place I clicked the link?

**Comment by gkeegan** [comment]
Yes. Go to Settings>Video & Audio>Preferred open action

If you want to sometimes go straight to the video, and sometimes straight to video page, choose Always Ask. If you always want description, choose Show Info.

**Comment by TobiGr** [comment]
If there are any questions left, feel free to ask.
Thanks @gkeegan for the fast response!

**Comment by 894-572** [comment]
Here's a screenshot of the video page if anyone is confused: 

![Screenshot_20200412-140502_NewPipe](https://user-images.githubusercontent.com/44001490/79067548-9d653c80-7caf-11ea-948a-485bdad4b6f4.png)
