### ISSUE TITLE
[Bug] Playback issue when trying to play certain videos in WebM format

### ISSUE THREAD

**Issue by VitinhoCarneiro** [TeamNewPipe/NewPipe#2297]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [-] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports. (does not apply, no crashes happen)

When trying to play certain videos in WebM format, the player just buffers endlessly, never starting the playback. I've seen reports that changing the playback quality eventually makes it work, but that wasn't the case for me - only setting the default video format to MP4 makes it work. The bug is reproducible in the latest release (0.16.1).

By trial and error, I've narrowed down the issue to the fact that _there are certain Youtube videos which have available WebM VP9 video streams, but no available WebM Opus/Vorbis audio streams_ - only MP4/M4A AAC streams are available.

My belief is that New Pipe is _trying to stream these non-existent WebM audio streams_, which doesn't work and causes the video playback thread to hang since the audio stream never comes through. The suggested fix would be to add a fallback and make it stream AAC audio (M4A, format id 140/139) whenever WebM audio streams are unavailable. (and yes, I have tested setting the default audio format to AAC, it doesn't have any effect on video playback)

To reproduce the bug, you need to find a video which has the WebM audio streams and one that doesn't (but still has WebM video streams available). I have listed two examples of such videos below. This can be verified using youtube-dl with the -F (list available formats) option. 

For instance, the video https://www.youtube.com/watch?v=IiVtyhdONkA does have WebM audio streams (format codes 249, 250, 171, 251 below) as well as the WebM video streams, and _plays back correctly in New Pipe_:
>```
>$ youtube-dl -F "https://www.youtube.com/watch?v=IiVtyhdONkA"
>[youtube] IiVtyhdONkA: Downloading webpage
>[youtube] IiVtyhdONkA: Downloading video info webpage
>[info] Available formats for IiVtyhdONkA:
>format code  extension  resolution note
>249          webm       audio only DASH audio   59k , opus @ 50k, 826.10KiB
>250          webm       audio only DASH audio   77k , opus @ 70k, 1.06MiB
>140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k, 1.88MiB
>171          webm       audio only DASH audio  138k , vorbis@128k, 1.89MiB
>251          webm       audio only DASH audio  149k , opus @160k, 2.06MiB
>278          webm       256x144    144p   96k , webm container, vp9, 30fps, video only, 1.30MiB
>(...)
>248          webm       1920x1080  1080p 2386k , vp9, 30fps, video only, 33.13MiB
>302          webm       1280x720   720p60 2907k , vp9, 60fps, video only, 39.06MiB
>298          mp4        1280x720   720p60 3749k , avc1.4d4020, 60fps, video only, 51.19MiB
>303          webm       1920x1080  1080p60 4019k , vp9, 60fps, video only, 55.97MiB
>(...)```

On the other hand, the video https://www.youtube.com/watch?v=kjDmFJ5UvMM does not have any of those WebM audio streams despite having WebM video streams, and _does not play at all unless the default video format is set to MP4_:
>```
>$ youtube-dl -F "https://www.youtube.com/watch?v=kjDmFJ5UvMM"
>[youtube] kjDmFJ5UvMM: Downloading webpage
>[youtube] kjDmFJ5UvMM: Downloading video info webpage
>[youtube] kjDmFJ5UvMM: Downloading MPD manifest
>[info] Available formats for kjDmFJ5UvMM:
>format code  extension  resolution note
>139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
>140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz)
>278          webm       216x144    DASH video   95k , webm_dash container, vp9, 29fps, video only
>160          mp4        216x144    DASH video  108k , mp4_dash container, avc1.4d400b, 29fps, video only
>242          webm       360x240    DASH video  220k , webm_dash container, vp9, 29fps, video only
>(...)
>247          webm       1080x720   DASH video 1505k , webm_dash container, vp9, 29fps, video only
>136          mp4        1080x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 29fps, video only
>302          webm       1080x720   DASH video 2646k , webm_dash container, vp9, 59fps, video only
>(...)```

**Comment by soshial** [comment]
I have the same problem with this video: https://www.youtube.com/watch?v=UPq1LDxL5_w
MPEG-4 works nicely, all WEB-M choices do not work.
NewPipe v18.4 on Google Pixel 2
