### ISSUE TITLE
Question: How to bookmark a playlist (when playlist URL shared with NewPipe)?

### ISSUE THREAD

**Issue by anishmittal2020** [TeamNewPipe/NewPipe#2299]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

In my Android 6.1, I shared (from 3rd Party App) a YouTube playlist URL (https://www.youtube.com/playlist?list=PLOAFgXcJkZ2wLr-7Kzm0Q3wZ8fq5Xsn-x) to be opened with NewPipe as follows

![image](https://user-images.githubusercontent.com/42092626/56396839-21bde480-6241-11e9-9388-be202df96f75.png)

On opening in NewPipe (see following figure), how can I bookmark it?

![image](https://user-images.githubusercontent.com/42092626/56396864-3e5a1c80-6241-11e9-9f1d-f26633187c81.png)

**Comment by gkeegan** [comment]
I don't think it's possible right now. In the meantime, you can search it on NewPipe and then bookmark it there.
