### ISSUE TITLE
Not working with VPN ?

### ISSUE THREAD

**Issue by Nico207** [TeamNewPipe/NewPipe#230]
Hi,
I have something strange with my config : it seems NewPipe doesn't work on VPN. 
I didn't find this problem with another similar apps (like Webtube or Skytube) 

The app start correctly but when I try to search something, the wait cursor appears and nothing else,  even if I wait some time. 

If I disconnect the VPN, all work fine.

**Comment by theScrabi** [comment]
I can't test it right now. But I'll try it later with my vpn. However please provide a log, and tell me which version you use. That would be a great help.

**Comment by theScrabi** [comment]
I confirm that behavior can also be raplicated by using orbot.

**Comment by Nico207** [comment]
I use the version 0.7.6 on Cyanogenmod 11 (Android 4.4.4)

Another thing I just found : it's only happens when I am connected with WiFi (it's work with the mobile data connection)

**Comment by theScrabi** [comment]
Ok strange thing. I'll try to figure out what the problem is.

**Comment by rrooij** [comment]
I'm having no problems with using a VPN. Using OpenVPN for Android 0.6.49 from FDroid.

**Comment by Nico207** [comment]
Another thing : this problem does'nt appear on all WiFi networks... maybe a network problem (firewall / dns / ...) ?

**Comment by licaon-kter** [comment]
Works ok through [NetGuard](https://github.com/M66B/NetGuard), yes it's a local VPN but it behaves just the same as an external VPN.

**Comment by mauriciocolli** [comment]
Must be some problem with the VPN, because NewPipe don't even know that it is under a vpn (and shouldn't).
