### ISSUE TITLE
[Feature Request} option to skip premium videos of a channel

### ISSUE THREAD

**Issue by ElTopo** [TeamNewPipe/NewPipe#2301]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Some channels have premium videos that require "YouTube Premium" subscription, for example, Vsauce:
https://www.youtube.com/user/Vsauce/videos

NewPipe (0.16.1) has problems to list out all videos from these channels. If I search "Vsauce" and click on the "Vsauce" channel icon, I only get 2 episodes (they are both "Premium free episode"), even though the Vsauce channel has many free episodes.

Since I did not log in, I am only interested in watching free episodes.

Can we have an option to skip "Premium" videos so NewPipe can list out free episodes only?

**Comment by gkeegan** [comment]
I believe this could be done simply, so long as premium videos have some sort of identifying tag or something of similar nature.

**Comment by B0pol** [comment]
I tried to reproduce this bug and it seems fixed
### Steps to reproduce
1. Go on [YouTube Originals channel](https://www.youtube.com/channel/UCqVDpXKLmKeBU_yyt_QkItQ)
2. Search for « The deported »
- [on pc, you will see the premium tag](https://user-images.githubusercontent.com/58657617/71783249-ebe1ab80-2fdb-11ea-8e3d-499660b98586.png)
- [on NewPipe, it doesn't show as the OP wanted](https://user-images.githubusercontent.com/58657617/71783239-c3f24800-2fdb-11ea-9c6a-2b9b1fb9f2b1.png)

Then this issue should be closed.
