### ISSUE TITLE
Feature Request: Block Channels

### ISSUE THREAD

**Issue by LordCorvin** [TeamNewPipe/NewPipe#2302]
This is feature request which I beleive would improve the app. Channel blocking, there a bunch of clickbaiting channels which would be nice to block.

**Comment by Symbian9** [comment]
You mean in search results? Think "Skip Channel in Search" or "Ignore Channel in Search" is better name for this option

**Comment by justanidea** [comment]
Probably in suggestions too

**Comment by nostromov** [comment]
Channel Blacklist doesn't exclude them? It should, it does, right? :o

**Comment by TobiGr** [comment]
Duplicate of #1815
