### ISSUE TITLE
[Feature Request] Feature/Fix + Endless loading and No loading while searching | 2 Bugs!

### ISSUE THREAD

**Issue by youngbasta** [TeamNewPipe/NewPipe#2304]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Version:** 0.16.1
**OS:** LineageOS 15.1
**Model:** Samsung Galaxy Tab S2 9.7 Wi-Fi (2016)
**Model:** gts210vewifi
**Model:** SM-T813
**Android Version:** 8.1.0
More Info: https://wiki.lineageos.org/devices/gts210vewifi/

# Feature:

![Screenshot_20190421_NewPipe](https://user-images.githubusercontent.com/49840534/56472695-51dbd200-6451-11e9-8407-74c63579af74.png)

**Remove the drag by thumbnail**
* It's so annoying to click on a video when using _Grid_. You have to snipe the text underneath to click it.
The thumbnail here is x3 as big as the text making it hard to click.
* Laying in bed scrolling around through my playlist with my left hand on a tablet is hard using the _List_ view. My thumb can't reach beyond the thumbnails of the videos, making me move them instead of the list.

**Replace/Reposition the "Handle"?**
* The two rows beside the displayed video title is covering up the end of the title a little bit. 
* It is also removing more click space, meaning I will have an even easier time moving it around rather than clicking on the video. 
So having both thumbnail + handle moving them around is annoying. And the solution should be to remove the "drag by thumbnail" feature.

# Bugs:

![Screenshot_20190421_NewPipe](https://user-images.githubusercontent.com/49840534/56473239-b9951b80-6457-11e9-82c8-4df77c01c7c8.png)

**Endless loading!**
* This is seriously annoying, and should be considered _high priority_. I have noticed that with each version coming out, this bug won't get fixed. 
So, when using _Grid_ or _Auto_. Which is the same thing when using a tablet. The loading does not stop on "What's New". It only loads the first two rows.
And completely closing and reopening the app does not solved anything. 
_No further information can be said!.. yet_

![Screenshot_20190421_NewPipe](https://user-images.githubusercontent.com/49840534/56473337-99fef280-6459-11e9-8b75-916010934b6c.png)

**No loading...**
* This is also seriously annoying and should also be considered _high priority_ and it is tied to the first bug "Endless loading!".
Here I cannot load search results more than what can be loaded from first initiating the search. And it stops with one "page".
No loading circle can be seen, I am also trying to scroll down but it's stopping me.

**Comment by Stypox** [comment]
I think you should split this into two different issues: it is difficult to keep track of problems if they are hidden inside a thread, whose title is not descriptive at all.

**Comment by nostromov** [comment]
Hang on, there's expected to be support for a device-specific ROM? Not sure the devs can even go there?..:)

**Comment by gkeegan** [comment]
@nostromov Adding ROM + device helps with understanding the issue a bit more.

I.e. for people with Huawei/Honor devices on EMUI, they have to do specific things to get background play working properly.

**Comment by youngbasta** [comment]
@Stypox Yes, I knew that. But I really didn't think it would matter. The title says two bugs, and they are pretty similar. I could put the feature in a separate issue. But actually just decided to put it here :/ 
Wrong of me, sorry!

**Comment by youngbasta** [comment]
Lol, thought I could edit my post and put them in a separate issue. :(

**Comment by nostromov** [comment]
Cool, but 4 example: I can't reproduce the second one, on Mi A2 stock Android One (jasmine ROM, global). So, how does that work for OP... Is it a tablet-only reoccurrence, or does it have to do with Lineage; for example, how the manager draws on screen (no clue as to what's up, really)?
