### ISSUE TITLE
[Feature request] swipe while searching to add to queue.

### ISSUE THREAD

**Issue by Lirlisa** [TeamNewPipe/NewPipe#2306]
I use this app mainly to listen to music in background, so it will be useful to just look for music and swipe them to the side to add to queue.

**Comment by TobiGr** [comment]
Nice idea 👍

**Comment by Stypox** [comment]
I'd like to implement this, but there is a problem: in most views the swipe gesture has already been used. For example in the video info fragment the swipe gesture is used to switch between comments and related videos.
The only solution I can think of is adding a little "headset" button on top of the video thumbnail that lets you add that video to the background queue. But this would make the video view more crowded and maybe sometimes cause unwanted behaviour (e.g. pressing on the button by mistake).

**Comment by Lirlisa** [comment]
In the searching view, the side swipe gesture has not been implemented, so maybe, you can add it just for that context.

**Comment by Stypox** [comment]
Yes, I could do that.

Oh and btw the headset icon would look something along these lines:
![Screenshot_20190426-234302](https://user-images.githubusercontent.com/36421898/56838297-c5307a00-687d-11e9-8f78-ed07f5116612.png)
which is not that good.

**Comment by Stypox** [comment]
After thinking about it I don't think it would be much useful to add the swipe option only in the "search" tab: it would make the gui inconsistent and it wouldn't solve the problem (at least for me it would be great to have such an option everywhere). What do you think @Lirlisa @TobiGr ?

**Comment by Lirlisa** [comment]
Well, it'd be great to add it everywhere, but as you said, there is already a swipe option implemented in other views, but if you come with something as fast as the swipe or better, i think would be great.
Maybe something like select multiple videos at the same time and then add them to queue.

**Comment by Stypox** [comment]
I thought a little bit about this and I came up with a solution: what about adding a resize-gesture (the same you do with two fingers to resize images) on videos? But detecting such a gesture could be difficult, so for now (as a demonstration) I added a two-fingers tap gesture.

It uses the [onTouchListener](https://developer.android.com/training/gestures/scale#java) and detects two-finger presses that are like this one (the two presses are interlaced, they are not contained one inside the other):
Finger 1:  ____
Finger 2:       _____
------------------------------> time (t)

I would like to improve this by making it such that the two presses can be one contained into the other, to allow things like this:
Finger 1:  ____
Finger 2:    __
------------------------------> time (t)

**Comment by Stypox** [comment]
What do you think?

**Comment by Lirlisa** [comment]
I'm not sure if i get your idea.
If i use 2 fingers it allows me to select the video?

**Comment by Lirlisa** [comment]
I click the wrong buttom :(

**Comment by Stypox** [comment]
Instead of clicking with one finger, you click with two. But I don't think I will follow that path.

I found a way to add a zoom/scale gesture, so I will try to add that. I will provide a testing apk, so that you can try it yourself and give me some feedback.

**Comment by Stypox** [comment]
I managed to add the zoom/scale gesture, but it was very sloppy. So I ended up fixing the problems with the double-finger tap and here is a debug apk. The gesture should work everywhere.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/3142262/app-debug.zip)

**Comment by justanidea** [comment]
I like this gesture 👍

**Comment by Lirlisa** [comment]
It's indeed faster and much better than long pressing each video, but i feel like it misses the one hand comfort

**Comment by Stypox** [comment]
I closed pull request #2322, and I explained why there.

**Comment by Stypox** [comment]
Closing, see https://github.com/TeamNewPipe/NewPipe/issues/6187#issuecomment-904445140 and https://github.com/TeamNewPipe/NewPipe/pull/2322#issuecomment-494469940
