### ISSUE TITLE
Error in NewPipe GitHub intro blurb

### ISSUE THREAD

**Issue by comradekingu** [TeamNewPipe/NewPipe#2307]
https://github.com/TeamNewPipe/NewPipe says: 
"A lightweight Youtube frontend for Android." It is supposed to be "YouTube"

That is however outdated, seeing as below it, it says 
"A libre lightweight streaming frontend for Android." which is a lot more precise.

My spellchecker says it should be "front-end" though…

**Comment by TheAssassin** [comment]
Fixed the repo description, and also put in the website URL there. Used the `front-end` spelling.
