### ISSUE TITLE
Divide Download Screen Into two sections and create Presets. 

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#2308]
Hello :)

It is very tiring for me every time i want to download audio to have to go through two different screens:

Just Download => Select Audio   because video is always selected for some reason => Download.

Can't we have just presets that we defined and just click one button => Download MP3 => Boom.

1 vs 3 clicks is a huge difference homies  :)

I love you too 💓.

**Comment by opusforlife2** [comment]
Will be partially fixed by #4038?

**Comment by TobiGr** [comment]
@opusforlife2 Note: I gave you triage rights, so you can manage issues. Thank you for your ongoing contribution and participation!
PS: feel free to join our Matrix channel for more direct communication.

**Comment by goxr3plus** [comment]
Great greaaat, wairing for it :)

**Comment by vmazoyer** [comment]
#4038 will only save you one click. The implementation of presets for the media type was rejected in the discussion of #3901. 

The idea I had mind back then was:
- Short press on the download button initiates a download according to preferred settings.
- Long press calls the usual download screen.
- If the user short-presses and the preset is not available for download, then the usual download screen appears along with a toast notification "preferred download not available" or something similar.
