### ISSUE TITLE
[Feature request] Yatse instead of Kore?

### ISSUE THREAD

**Issue by Smultie** [TeamNewPipe/NewPipe#231]
I think more people use the brilliant remote control app Yatse than Kore.
Could you implement the 'Play with Kodi' feature for Yatse as well?

**Comment by theScrabi** [comment]
I gues you can reach Yatse via "Open in browser" menue right? Is yatse open source software? Because I want to relay on software that is available over f-droid.

**Comment by Smultie** [comment]
Yeah, opening in Yatse via the 'share' functionality works.
I'm not sure if it's oss. It's not on F-droid for sure.

**Comment by theScrabi** [comment]
@Smultie would you like to figure out? Would be an app more we have :)

**Comment by wb9688** [comment]
I think it isn't FOSS, because it has a paid version...
Op 11 mrt. 2016 14:50 schreef "Christian Schabesberger" <
notifications@github.com>:

**Comment by theScrabi** [comment]
Hm.
