### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by arvchz** [TeamNewPipe/NewPipe#2318]
Hi,

I'm new to android development so this is a noob question. I'm unable to run the project. how do i fix this ??

![Screenshot from 2019-05-03 22-31-32](https://user-images.githubusercontent.com/4346153/57155769-efdc7e80-6df9-11e9-96a8-0f7a5330468c.png)

**Comment by Stypox** [comment]
What did you do when the IDE asked you to upgrade grandle?

**Comment by arvchz** [comment]
@Stypox : I upgraded it. Is that a mistake. ?? Going to retry now without that.

**Comment by arvchz** [comment]
That was the issue., fixed now. Thanks @Stypox
