### ISSUE TITLE
Removing view of 'trending' completely

### ISSUE THREAD

**Issue by sulyniv** [TeamNewPipe/NewPipe#2319]
Although the trending tab can be removed from the homepage of newpipe, the trending page still appears in the side menu. I assume newpipe was developed partly to remove distractions such as comments, recommended videos etc. 

Is it possible to give an option which completely removes the trending page from sight so there is no temptation? If you would be willing to implement this idea I will donate $30 as soon as you reply.

**Comment by gkeegan** [comment]
I think this issue could be expanded to more than just removing trending. Allowing to customize all aspects of the sidebar would be a nice addition.

**Comment by lbrunkho** [comment]
I agree, adding the option to customize the tabs would be nice. Right now I just want the "whats new" to actually display properly :/

**Comment by gkeegan** [comment]
What is wrong with what's new?

**Comment by lbrunkho** [comment]
it does not display videos in chronological order like the YT sub-box. It instead shows you the most recent video from each channel in your subscribed list in alphabetical order. The result is that videos released within, lets say, one day. Get buried if you are subscribed to a bunch of less active channels.

**Comment by gkeegan** [comment]
That is going to be added soon in a future update.

**Comment by hp8wvvvgnj6asjm7** [comment]
Trending only gives me shit, I suppose my country only watches crap.

**Comment by Serkan-devel** [comment]
I assume the subbox loads all channels from an rss-feed. With many subs it would be harder to sort in realtime

**Comment by abusarimhindi** [comment]
Please guide me, how can I remove trending now tab?

**Comment by Stypox** [comment]
@abusarimhindi sorry if I am late, here is what you could do. Keep in mind that we would prefer not to add yet another rather-unused entry in settings, so what I'd suggest another approach: you could make the trending button in the drawer long-pressable, and after a long press you should ask the user if he wants to hide trending views (use a Dialog). The hidden trending menu buttons should still be visible, but should be grayed out and with no action connected to a click. Only with another long press they could be re-enabled (use a Dialog here, too).
[These lines](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/MainActivity.java#L151-L156) are where the trending menu buttons in the drawer are set up

**Comment by Stypox** [comment]
Closing in favour of #3343
