### ISSUE TITLE
App does not detect when the device is offline

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#2326]
Instead I get an error on startup.
There is something called service workers I think.

Same goes for any action, the app should tell me that my device has no internet connection.

Why is the app not aware of this?

**Comment by Redirion** [comment]
can you please test the current [0.16.2 RC2](https://github.com/TeamNewPipe/NewPipe/issues/2314) to see if your issues are (partly) resolved? At least the error on startup should be gone.
