### ISSUE TITLE
Some videos get skipped in background mode

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#2327]
In background mode, some videos won't even play, they get skipped and removed from the playlist. This has happened pretty often now.

**Comment by hp8wvvvgnj6asjm7** [comment]
Such videos, also fail to download.

**Comment by Stypox** [comment]
Could you provide an example playlist

**Comment by CorneliusHuber** [comment]
In my experience there is no specific list of videos. Sometimes it happens and after you kill the app and delete the cache it usually works again. After a few videos it starts happening again though.

**Comment by Rikests** [comment]
Some of the skips happened while listening to this playlist in background. https://m.youtube.com/playlist?list=PLx1QwUpzcAQlCkJ0GLVdGkazkiTsHVt-T

**Comment by Stypox** [comment]
Ok, thank you. I get problems there too, so I can investigate.

**Comment by Stypox** [comment]
Apparently this video is the problem, since it was blocked for copyright reasons: https://www.youtube.com/watch?v=8NsJ84YV1oA
When that video is encountered, NewPipe shows the toast `Could not play this stream` and skips it.

**Comment by hp8wvvvgnj6asjm7** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/2336

**Comment by Stypox** [comment]
I don't think this has anything to do with #2336 , since in #2336 the background player would load indefinitely, while here it would just skip a video for copyright reasons.

**Comment by hp8wvvvgnj6asjm7** [comment]
No, I got videos skipped and removed from my background list, which were clearly not copyrighted. Either way, both issues are affecting me.

**Comment by Stypox** [comment]
See if the after the merge of TeamNewPipe/NewPipeExtractor#163 it still happens

**Comment by TobiGr** [comment]
The fix will be included in version 0.16.2. @Stypox Thanks again!
