### ISSUE TITLE
Ability to group subscriptions into categories

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#2329]
Imagine having too many subscriptions, you want to browse trough them as categories. Just like playlists, you can open such and see all new videos of that given category.

**Comment by justanidea** [comment]
This already exists, and come in the next release probably :)

**Comment by justanidea** [comment]
See #2309

**Comment by hp8wvvvgnj6asjm7** [comment]
This is great. Thanks
