### ISSUE TITLE
NewPipe ignores content country settings and auto-translates video time into a ip related language

### ISSUE THREAD

**Issue by selay01** [TeamNewPipe/NewPipe#2330]
![01](https://user-images.githubusercontent.com/1252491/57220173-e4bd6480-702c-11e9-8c76-6ab08c1bc850.png)
![02](https://user-images.githubusercontent.com/1252491/57220174-e4bd6480-702c-11e9-97a0-5c8a520627a6.png)
![03](https://user-images.githubusercontent.com/1252491/57220176-e4bd6480-702c-11e9-9149-86d0f3c1319b.png)

Not only videos under trending, all time are auto-translated into a ip related language.
Search results seem to be unaffected.

**Comment by startas** [comment]
Yes, this is really annoying. Setting languages in app does nothing...

**Comment by hp8wvvvgnj6asjm7** [comment]
Same here

**Comment by Stypox** [comment]
Duplicate of #578
