### ISSUE TITLE
[Feature Request] Add a way to go to the description page from the video playing screen

### ISSUE THREAD

**Issue by pieqq** [TeamNewPipe/NewPipe#2332]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

# Summary

It would be great to have a way to go from a video running in full screen to its description page.

# Rationale

Sometimes, a friend sends me a link to a Youtube video. I open it using NewPipe and can start watching it, but there is no way to go to the description page for this video from the playing screen:

![Screenshot_20190506-120634_NewPipe](https://user-images.githubusercontent.com/512471/57270629-b6886500-70be-11e9-9373-1ee27834774a.jpg)

This is a problem if I want to access the description of the video (often, content creators put extra information in this field), the statistics, the comments, the download link, etc.

It's also a problem if I want to stream it to my Kodi mediaplayer: the `Play with Kodi` button is only available in the description screen (here next to the share button):

![Screenshot_20190507-115826_NewPipe](https://user-images.githubusercontent.com/512471/57270813-770e4880-70bf-11e9-86ac-977e3d40cab7.jpg)

P.S.: Thanks a lot for this great piece of software! It's really useful in my daily life :)

**Comment by youngbasta** [comment]
If you had looked around in the Issues page. Searched for this, there are already many people wanting this exact feature. This hasn't been worked on as far as I know, been months upon months. This will probably never happen :/
I wish this was a feature too.

**Comment by Stypox** [comment]
This is a duplicate, and will be fixed in #2430
