### ISSUE TITLE
[Just another feature], Implement Live Chat!

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2334]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Just want to add the live chat to the live streams. Thanks

**Comment by Serkan-devel** [comment]
Is there a branch for it already?

**Comment by SameenAhnaf** [comment]
@mhmdanas Isn't this a duplicate of #5171?

**Comment by mhmdanas** [comment]
It's the other way around, but that issue has more discussion anyway. Closing this.
