### ISSUE TITLE
Background player not working for specific songs

### ISSUE THREAD

**Issue by shmil111** [TeamNewPipe/NewPipe#2336]
hey, i already talked about it with a comment on the post announcing the last update.

im gonna repost it here just because im not sure if this is a better place to report on things like this or not. sorry, not meaning to spam.

-----------------------------------------------

I'm experiencing a problem in playing specific videos on the background player.
It just doesn't load.
The problem is span across many versions of the app.

An example of a video like this:
https://www.youtube.com/watch?v=EWSNOSv9TAs

It happens quite often.

I tried forcing shutdown of the app and trying to load it again, I tried even uninstalling the app and downloading it again, and the same song still won't load (but only on background mode).

I know with a problem so unspecific like this I'm not helping you much.
I assume the problem is specific to me since it happens so often if it was happening for everyone it for sure would've been reported and fixed already.

Thanks!

**Comment by Redirion** [comment]
works for me. What device do you have?

**Comment by ime90** [comment]
I have the same problem. 

Some songs won't play in background or download.

Phone:
Huawei mate 20 pro.

Model LYA-L20

Android version:
9.

**Comment by Redirion** [comment]
@ime90 did you try to switch the preferred Audio format? 

Do you guys know "adb logcat" and can send the relevant portion of the log that might indicate the problem?

**Comment by shmil111** [comment]
now things fine for me.
it's wierd. 

i'll continue updating if anything changes again.

thank you.

**Comment by shmil111** [comment]
Oh, it happened again. Twice.
This time I tried to change the audio format - didn't help.

I noticed that if I connect to a VPN, even if it's to my home country, it works.
Also if I was on WiFi and I switch to mobile data, or the opposite, it usually also works (but only if i restart the app).

You asked what type of phone I have, it's Meizu m6 note.

**Comment by shmil111** [comment]
About logcat, it needs root for it to be able to work.

**Comment by elFuret** [comment]
Hi, 
I had the same issue, closing the app, clearing cache and datas, unistall, and install again worked for me.

**Comment by justanidea** [comment]
![](https://i.imgur.com/ccAU1C6.png)
I guess its that.

**Comment by justanidea** [comment]
I also got:
ActivityManager
destPackageName = null
(That i guess to be from Newpipe)
And :
  ![](https://i.imgur.com/5MjRKi2.png)
