### ISSUE TITLE
Cannot seek in an opus file downloaded using Newpipe

### ISSUE THREAD

**Issue by opusforlife** [TeamNewPipe/NewPipe#2340]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Vanilla and Odyssey (the two music players I've found on F-Droid that don't use a custom audio engine, yet support opus playback) can play opus files downloaded using Newpipe, but cannot seek in them. Neither can the media player built into FX File Explorer (I'm using LineageOS which recognizes the opus extension as an audio file). The cursor(?) just jumps to its previous position and the audio continues uninterrupted.

I've messed around some and found these things:

- VLC, mpv-android and Poweramp can seek in them, *probably* because they don't use Android's code for this.
- The 'file' command gives the mime type for WebM/opus and m4a downloads as "video/webm" and "video/mp4" respectively. Strangely, **m4a files play and seek just fine**. The WebM extension is read by Android as a video file so it's ignored by these players entirely. Renaming it to ogg (since it contains a vorbis stream) doesn't help. The file is seen by the players, but it doesn't play. (Edit: my bad. Just renaming the file won't change the container from webm to ogg.)
- The equivalent for youtube-dl is to download DASH audio streams by their format code (-f 251 and the like). It gives the same video mime types.
- If instead I use the -x flag to extract audio in youtube-dl, it gives the mime type audio/ogg for opus downloads, and they play and seek just fine in Vanilla and Odyssey.

I don't know if it's just the incorrect mime type or something else causing this.

Edit: Reading #2149, it appears that this is caused by the DASH audio not being handled properly. This issue seems to be the opus/webm version of #2152.

**Comment by Stypox** [comment]
A friend of mine also said he can't edit the metadata tags of the audio files he downloaded with NewPipe. This could be related.

**Comment by opusforlife2** [comment]
Oh. This was fixed by #2679. @Stypox please close this.
