### ISSUE TITLE
Overlay stays after resume with headphone button

### ISSUE THREAD

**Issue by bodtx** [TeamNewPipe/NewPipe#2342]
* connect a headphone with a button (like a mic headphone with mute button)
* play a video
* push the headphone button => the video stops 👍
* push the headphoe button => the video resume 👍 
* 🛑the overlay stay in place 👎 I need to touch the screen to remove it🛑

I'm on LOS 14.1

**Comment by xinobrax** [comment]
Same here with bluetooth headphones.

**Comment by opusforlife2** [comment]
@bodtx @xinobrax Is this still a problem in 0.20.0?

**Comment by bodtx** [comment]
@opusforlife2 tested right now and same problem in 0.20

**Comment by opusforlife2** [comment]
Thanks!

**Comment by opusforlife2** [comment]
Closing in favour of #3403. That one is already linked to a PR that will fix the issue.
