### ISSUE TITLE
Downloads don't start automaticaly

### ISSUE THREAD

**Issue by mouarfff** [TeamNewPipe/NewPipe#2343]
Hello,

Since the last version 16.1, sometimes download don't satrt automaticaly without any reason i can see.

Sometimes it's ok, the first download start, and after finish, the second start etc etc....
but in most cases, no download start at all

i'm in HOMTOM HT70 with android 7

**Comment by Stypox** [comment]
Like #2072 and #2290, it should be fixed in #2149
Please close this.
