### ISSUE TITLE
Optimize The App

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#2346]
Optimize the app for this device

DEVICE
Model: Smartphone 3.1 Lite (Smartphone)
Manufacturer: Smartphone
Baseband Version: MOLY.WR8.W1449.MD.WG.MP.V57.P2, 2016/04/28 16:27
RIL Version: mtk gemini ril 1.0
Build Number: Z13_GQ3029DH_Smartphone3.1_Lite_20170927
Build Fingerprint: alps/full_long6580_we_m/long6580_we_m:6.0/MRA58K/1506562004:user/dev-keys
Bootloader: unknown
Java VM: ART 2.1.0
OS Version: Marshmallow (6.0)
SDK: 23

DISPLAY
Resolution: HD, 720x1280 pixels
Software Density: 320 dpi (xhdpi)
Refresh Rate: 58.1 Hz

PROCESSOR
CPU Architecture: ARMv7 Processor rev 3 (v7l)
Board: MT6580
Chipset: MT6580
Cores: 4
Clock Speed: 604 MHz - 1300 MHz
Instruction Sets: armeabi-v7a, armeabi
CPU Features: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU Governor: interactive
Kernel Version: 3.18.19
Kernel Architecture: armv7l

GRAPHICS
Renderer: Mali-400 MP
Vendor: ARM
OpenGL Version: OpenGL ES 2.0

RAM
Total: 959 MB
Java Heap: 128 MB

STORAGE
Internal: 5.1 GB
EXTERNAL: Not Detected

PRIMARY CAMERA
Resolution: 8.3 MP
Flash: Yes
Video Resolution: 4K UHD, 3840x2160
Supported Resolutions: 
    Image:
    320x180
    320x240
    640x360
    640x480
    1024x768
    1280x720
    1280x960
    1600x912
    1600x1200
    1920x1088
    2048x1536
    2304x1296
    2560x1440
    2560x1920
    3072x1728
    3264x2448
    3840x2160

    Video:
    176x144
    480x320
    640x480 (VGA)
    720x480
    864x480
    1280x720 (HD)
    1920x1080 (Full HD)
    1920x1088
    3840x2160 (4K UHD)

SECONDARY CAMERA
Resolution: 2.1 MP
Video Resolution: 1280x736
Supported Resolutions: 
    Image:
    320x180
    320x240
    640x360
    640x480
    1024x768
    1280x720
    1280x960
    1600x912
    1600x1200
    1920x1088

    Video:
    176x144
    320x240
    352x288
    480x320
    640x480 (VGA)
    864x480
    1280x720 (HD)
    720x480
    1280x736

FEATURES
Bluetooth: Yes
Bluetooth LE: Yes
GPS: Yes
NFC: No
USB Accessory: Yes
WiFi: Yes
WiFi Direct: Yes

BATTERY
Technology: Li-ion
Health: Good

SENSORS
ACCELEROMETER
PROXIMITY
LIGHT

**Comment by Stypox** [comment]
What do you mean by "optimize"? What slowdowns did you come across?

**Comment by gkeegan** [comment]
@Stypox He keeps complaining about NewPipe needing optimizations but never gives any good info about what the issue is. This is also the second or third issue like this he has opened (he deleted the other ones as far as I can tell).

**Comment by GKid94** [comment]
I don't have any slowdowns I just want he developers to make the app so that it runs better on that device

**Comment by TobiGr** [comment]
How should we make the app run better on your phone when you cannot tell us what to improve exactly?
``` Java
public void run() {
    runImprovedVersion(); // does not help
}
```

**Comment by GKid94** [comment]
Improve the whole app so that it's compatible and that it runs well on the device

**Comment by Stypox** [comment]
When does it not run well??

The app is fully compatible with Android 6.0, so that's not a problem.

Please provide an explanation of the slowdowns you are experiencing. Just repeating the same thing again and again, without answering the questions you are asked, is not going to lead to the resolution of the issue.

@GKid94

**Comment by GKid94** [comment]
It does run well but I don't know if it's compatible with my device so I sent the device info so the developers can see if it is or if it's not compatible

**Comment by GKid94** [comment]
But now I know it is compatible

**Comment by Stypox** [comment]
Then you should have give the issue the title "Is the app compatible with my device", not "optimize the app". Anyway I'm glad I could help you.
