### ISSUE TITLE
[Feature Request] Change Font Size Option for TV-Screens

### ISSUE THREAD

**Issue by Predator76** [TeamNewPipe/NewPipe#2347]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hello,
it would be great, if you could implement an option to change the size of the fonts in the overview. I am using NewPipe on my Android TV Box and having issues with the readability of the small video descriptions on my TV Screen. Thanks in advance and keep up the good work! Cheers, Al

**Comment by heberjeur** [comment]
Me too

**Comment by Stypox** [comment]
Closing in favour of #3221
