### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by joek85** [TeamNewPipe/NewPipe#2349]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hello, thanks for this amazing project, i have a question regarding the licensing, i understand that i can use this project, modify and reuse it while submitting back the modifications. 
I am working on a hardware project that will be sold as a commercial product and i want to include this project as a modified preinstalled app.
What should i do to not violate the term of uses of the license and ofcource i am willing to submitt my modifications back to this repo. 
Thank you, and keep up yoir good work. 
Best regards.

**Comment by gkeegan** [comment]
I'm not a lawyer, nor a member of TeamNewpipe, and this is not legal advice, but as long as you distribute your source code/have it linked in your app, and stick with the GNU license in your program as well, you should be okay.

It isn't necessary to give any modifications back to this repo, but they would be appreciated.

**Comment by theScrabi** [comment]
> What should i do to not violate the term of uses of the license and ofcource i am willing to submitt my modifications back to this repo.

You may want license your modifications under the same license (GPL v.3), (read them please). Also you may not change the copyright owner.

**Comment by theScrabi** [comment]
I said in the video that I was documenting some Maintainer stuff. Here are the links:
- [Releasing a New NewPipe version](https://teamnewpipe.github.io/documentation/05_releasing/)
- [My View on some Maintianing questions](https://teamnewpipe.github.io/documentation/07_maintainers_view/)

**Comment by joek85** [comment]
you may not change the copyright owner.
> 
surely not
Anyway thank you for your clarifications.
