### ISSUE TITLE
The option to chose quality gets pushed outside of the window in popup mode

### ISSUE THREAD

**Issue by dankxylese** [TeamNewPipe/NewPipe#2353]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

The option to chose quality gets pushed outside of the window in popup mode when there are too many quality options and they don't fit on the screen. Heres a video of it: https://upload.cat/b51101a765df26ae

Running on Android 9 if that matters.

**Comment by opusforlife2** [comment]
I can confirm this starts to happen when you place the popup _just_ low enough on the screen that the resolution selection popup won't have space to show fully. In that case, it opens upwards (naturally) but for some reason, it gets cut off at the boundary of the popup window.

**Comment by dankxylese** [comment]
I no longer experience this in the latest version. I have also since then moved to Android 10 so it might be that. OnePlus 5T running mostly AOSP.

**Comment by opusforlife2** [comment]
Does it open fine upwards?

**Comment by dankxylese** [comment]
Yes, I tried getting it as low as possible before the quality select goes up and it works as intended.

**Comment by opusforlife2** [comment]
Then it probably happens for Android 9, and maybe other versions. Thanks for checking.

**Comment by Feuerswut** [comment]
Is this still an issue?

**Comment by dankxylese** [comment]
> Is this still an issue?

Nope. It's been fixed for at least a year now. Forgot this ticket was even still around. I'll close it with this comment. 

A big thanks to the NewPipe team and countless contributors who continuously work on this great app!
