### ISSUE TITLE
Making the long-press menu consistant across the application

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#2354]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

The order of the items in the long-press menu is different in every view (playlist, search, info...). I am willing to fix this inconsistency, but I thought I'd open an issue anyway, just to get some feedback before proceeding. So what do you think? Should I make long-press menus the same across the whole app?

**Comment by justanidea** [comment]
Seems a logical idea👍

**Comment by TobiGr** [comment]
Sounds good. Our long-term idea is to replace them with something like this:
![image](https://user-images.githubusercontent.com/17365767/58190716-606e1100-7cbd-11e9-9361-ffd468be24cb.png)

**Comment by Stypox** [comment]
Oh, that's great!

**Comment by Gymcap** [comment]
May I suggest an idea I've been tossing around? I believe it would help make the ui slightly less cluttered with options, while keeping it intuitive. I think a simple [drag&drop/tap&hold](https://i.imgur.com/nsr45Kq.jpg) style selector would be perfect for this.

To explain my sketch:

Long tap on a video   
A ui shows up giving the option to play, background, popup, playlist, download, and share   
Long pressing one of these icons will queue the action   
An alternative way to interact with this interface could be to long tap video>release on selection/hold to queue selection

**Comment by Stypox** [comment]
At first I thought @Gymcap solution was better than the other one, even if it lacked the select-multiple feature. But after reordering chats in Telegram, I found out they do the same thing with the menu on top of the screen. So at the end that is ok, I think.

**Comment by Stypox** [comment]
At first I thought @Gymcap solution was better than the other one, even if it lacked the select-multiple feature. But after reordering chats in Telegram, I found out they do the same thing with the menu on top of the screen. So at the end @TobiGr solution is better, I think.

**Comment by Stypox** [comment]
Looking through the app I found 4 different types of menus (entries are in order), by long pressing on streams from ... :
- TRENDING or VIDEO INFO or WHAT'S NEW: background, background-enqueue, popup-enqueue, add-to-playlist, share
- LAST PLAYED: background-enqueue, popup-enqueue, play-here, background, popup, delete-from-history, share
- CHANNEL: background-enqueue, popup-enqueue, play-here, background, popup, add-to-playlist, share
- PLAYLIST: background-enqueue, popup-enqueue, play-here, background, popup, share

Even though it is not a stream, the subscription long-press menu still has a different order from the others: share, delete

I'd improve them in this way (note that I removed the play-here, because I think it is useless since it takes roughly the same time to long-press the stream and click play-here, and to open the stream info and click the big play button):

```
background-enqueue
popup-enqueue
background
popup
-------------------- [separator]
add-to-playlist
share
-------------------- [separator (when needed)]
[specific actions, such as delete-from-history]
```

**Comment by Stypox** [comment]
After looking through the code, I found out that the long-press menu is generated by a built-in AlertDialog, so no separator can be added. I'll just implement the same as above, but without the separators (It would take too much work to create a custom dialog that will then be removed).
