### ISSUE TITLE
player is slow and don't work sometimes.

### ISSUE THREAD

**Issue by soilentgreen** [TeamNewPipe/NewPipe#2356]
Hello,
I use version 0.16.1 and I have 2 problem when I try to watch youtube videos:
1 It take 10-50 seconds until the video start to play.
2 sometimes the video don't play at all. It stuck on the circle animation.

This is not related to internet speed. I have fast connection. It happning on 4G and WIFI.

Thanks.

**Comment by Stypox** [comment]
This should be fixed with 0.16.2, or at least the video-not-playing part. Please install the apk of 0.16.2 provided in #2314 and see if it solves your issue.

**Comment by soilentgreen** [comment]
[https://www.virustotal.com/#/file/69b7eff40ede2f30243cdb62b0f0f50f9837c34314f15cf795c343cde6e21c4e/detection](url)
Why this virsion not clean as 0.16.1?

**Comment by TobiGr** [comment]
Because I didn't sign it with the official key, but my debug key. I said this in the comments.

**Comment by fightthepower** [comment]
Just want to report the same issue. It takes time to play a video or not play at all.

**Comment by soilentgreen** [comment]
0.16.2 didn't fix issue.
