### ISSUE TITLE
Is this source code free of malware?

### ISSUE THREAD

**Issue by hyperpanthera** [TeamNewPipe/NewPipe#2357]
I don't want my password stolen.

Anyone analyzed the source code yet?

**Comment by gkeegan** [comment]
Each commit (addition or removal) of code requires at least two people to have viewed it and read through it (the person who submitted it and the person who checked it, and possibly a third if the person who checked isn't someone who can authorize the commit). So yes people have analyzed it. 

Also, you don't need to input any passwords to use the app, as signing in to any of the sites (mediaCCC, YouTube, Soundcloud) is not and will not be supported.

**Comment by hyperpanthera** [comment]
> Each commit (addition or removal) of code requires at least two people to have viewed it and read through it (the person who submitted it and the person who checked it, and possibly a third if the person who checked isn't someone who can authorize the commit). So yes people have analyzed it.
> 
> Also, you don't need to input any passwords to use the app, as signing in to any of the sites (mediaCCC, YouTube, Soundcloud) is not and will not be supported.

Thanks man!

Some heroes don't wear capes.

**Comment by gkeegan** [comment]
No problem. Could you please close this issue?

**Comment by hyperpanthera** [comment]
@gkeegan Closed.
