### ISSUE TITLE
Select audio quality when downloading video. (Feature request)

### ISSUE THREAD

**Issue by 4goodapp** [TeamNewPipe/NewPipe#2364]

**Comment by litetex** [comment]
This is already possible:
![grafik](https://user-images.githubusercontent.com/40789489/132919036-f23196b8-06ba-4f83-ad91-4d14972cc29f.png)

**Comment by foxjaw** [comment]
I personally just prefer yt-dlp on termux. No GUI's honestly superior than cli.
