### ISSUE TITLE
Subtitle embed in video features

### ISSUE THREAD

**Issue by ravig252525** [TeamNewPipe/NewPipe#2365]
Subtitle embed in video features

**Comment by gkeegan** [comment]
Could you please elaborate on what the issue is?

**Comment by ravig252525** [comment]
I want to video download if video subtitle available mixing subtitle then download

**Comment by gkeegan** [comment]
So hardcoding the subtitle into the video?

**Comment by opusforlife2** [comment]
@kapodamy Possible?

**Comment by kapodamy** [comment]
@opusforlife2 no, ambitious feature.

**Comment by opusforlife2** [comment]
Alright. Thanks!

**Comment by opusforlife2** [comment]
For clarity: closing because subtitles can be downloaded separately, which is the next best thing.
