### ISSUE TITLE
default tabs

### ISSUE THREAD

**Issue by 1emirozdemir** [TeamNewPipe/NewPipe#2375]
hello normally there are 3 tabs in the app's default, these feed, subscribers and playlist, how we can add new tabs

**Comment by gkeegan** [comment]
Do you wish to add new tabs to the default in the code or manually add some to your installation?

---

To add to your installation, go to Settings>Appearance>Contents of Main Page and tap the plus.

---

To add to the default, you will need to edit [this file](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/MainActivity.java) at some point after line 121. You may also have to edit the strings.xml file depending on what you are doing. 

---

I hope I have answered your question sufficiently well.

**Comment by 1emirozdemir** [comment]
yes I want to change the default in the code but I don't understand what to do in mainactivity

**Comment by TobiGr** [comment]
So you basically want to make changes to the code, don't you?

**Comment by 1emirozdemir** [comment]
yes

**Comment by 1emirozdemir** [comment]
please help me

**Comment by Stypox** [comment]
Duplicate of #2221
