### ISSUE TITLE
Video playback causes lockscreen on

### ISSUE THREAD

**Issue by test2a** [TeamNewPipe/NewPipe#2378]
I just updated to 0.16.2 from github and every 6-7th video, I press play button and I am locked out of screen. Then I have to unlock the phone.

Same with leaving "minimize on app switch" to minimize to background player. The app locks out of video and plays in the background every time.

**Comment by test2a** [comment]
And yes, leaving that minimize on app switch, I have had my wallpaper reset. Twice.

**Comment by gkeegan** [comment]
When you are going to the new videos, is it just a playlist or do you actively press around the screen and stuff to navigate to the new video? I suspect this may be related to screen timeout. Could you change the sleep time to never and see if the issue still occurs when following the same steps?

Also, some info about your device would be appreciated, such as model, android version, if you are a custom ROM, etc.

**Comment by test2a** [comment]
@gkeegan normally. be it from whats new or from search. 
android 7. no custom rom. lenovo z2 plus.
never have had this problem before, right untill i updated the app the few days ago. I didnt change anything in the setting or in the app.

**Comment by test2a** [comment]
@gkeegan this problem just arrived in the latest version so i have to consider the update has something to do with this

**Comment by gkeegan** [comment]
Yes it is most likely from the update. 

I have a few questions:
1. So when you press play it *immediately* locks your phone? 

2. Does it turn off the screen?

3. When you press play does the issue occur immediately, or does it take a little bit?

4. Does the app crash?

5. Is there some sort of "double tap to lock" feature on your phone?

This issue is really odd to me because I don't think apps are supposed to be able to lock the screen on Android.

**Comment by test2a** [comment]
i took a screenrecording. not the best one but i have narrowed it down. this behaviour happens "always" on time playing a video after i have quit the app. second time it works fine. only first time. same with leaving the "minimize on app switch" option. otherwise the video just quits...

![1559562606-videorecord-2019-6-3-17-20-6](https://user-images.githubusercontent.com/39449563/58800355-44eff800-8625-11e9-808b-e244e2b82198.gif)


![1559562524-videorecord-2019-6-3-17-18-44](https://user-images.githubusercontent.com/39449563/58800203-e165ca80-8624-11e9-88b4-f287e3a41020.gif)

**Comment by test2a** [comment]
Another bug. Changing video resolution also locks user of out to lockscreen. Always

**Comment by opusforlife2** [comment]
@test2a Can you confirm if this happens on the latest version?

**Comment by test2a** [comment]
@opusforlife2 nope. not at the moment. this problem was solved in a later update. i would close this issue as solved

**Comment by gkeegan** [comment]
@test2a I would suggest editing out your  videos (and removing the history) if that is your current phone PIN in it :)
