### ISSUE TITLE
Video does not play in Newpipe

### ISSUE THREAD

**Issue by Esokrates** [TeamNewPipe/NewPipe#2379]
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

The following video does not play: https://www.youtube.com/watch?v=fO-ZbyDLUeA

**Comment by Stypox** [comment]
Which NewPipe version are you using

**Comment by Esokrates** [comment]
@Stypox 0.16.1 since F-Droid does not have 0.16.2 yet. I'll test the newer version as soon as it becomes available.

**Comment by Stypox** [comment]
Yes, it should be fixed in 0.16.2

**Comment by soilentgreen** [comment]
No its not fixed.

**Comment by Esokrates** [comment]
I just upgraded to 0.16.2 from F-Droid and the video works.
Thanks very much!
