### ISSUE TITLE
Cant get new version

### ISSUE THREAD

**Issue by cup** [TeamNewPipe/NewPipe#2381]
I am looking on Fdroid but I only see version 0.16.1

**Comment by cup** [comment]
Looks like you can get it from GitHub

**Comment by Stypox** [comment]
Fdroid takes some time to push updates. See #1981

**Comment by licaon-kter** [comment]
@cup Already build ( https://f-droid.org/wiki/page/org.schabi.newpipe/lastbuild_740 ) waiting for sign&publish
