### ISSUE TITLE
Improve layout of popup-dialog

### ISSUE THREAD

**Issue by ronidee** [TeamNewPipe/NewPipe#2383]
- [Y] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [Y] I checked if the issue/feature exists in the latest version.

The popup-dialog that opens when long-pressing a video thumbnail only contains text/phrases. Thus it may take some time to find the wanted action.

I would like to suggest using a more structured layout based on icons+text. I have attached an image showing my personal proposition, made with GIMP not with XML yet. It should serve as a first attempt to be criticized and improved upon (on?).

Now I would like to know what you think:
**1) Do you think, this is (fundamentally) a good idea?**
**2) If so, how would you further improve it?**

It may look cluttered at first glance, but I think when you're getting used to it, it really improves usability
![newpipe_popup](https://user-images.githubusercontent.com/22625272/58973428-40ac1200-87c0-11e9-8d40-5241a88d6664.jpg)

**Comment by Stypox** [comment]
I think this is already being discussed in [#2198](https://github.com/TeamNewPipe/NewPipe/pull/2198#issuecomment-471980795) and in #2354

**Comment by ronidee** [comment]
You're right. Thanks for the comment.
