### ISSUE TITLE
[Feature request] Stats for nerds?

### ISSUE THREAD

**Issue by opusforlife** [TeamNewPipe/NewPipe#2385]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Would it be possible to implement this function from the official app, in whole or in part?

**Comment by TobiGr** [comment]
It is possible, but I am not sure who might need this. Tbh, there are much more important features and bugs which need more attention. 
I guess, this won't be implemented. Nevertheless, in case someone really wants to implement this, I am happy to review  the PR. But please, comment here first, so we can speak about a good  UI integration.

**Comment by opusforlife** [comment]
You're right. It's a superficial feature. It was just an afterthought to my investigation in #2340. I thought having that info upfront would be useful for debugging and issue reporting purposes.

**Comment by probotico** [comment]
Hi, I would also like to have access to this data.
Getting playback statistics and dropped frames is important for testing, troubleshooting, video aceleration.
I'm actually getting dropped frames in certain resolutions and framerates but I cannot quantify it.

Thank you!

**Comment by opusforlife2** [comment]
A workaround here is to use the version of mpv-android that bundles youtube-dl, and enable the stats there. It will naturally not help with debugging/analysing Exoplayer playback, but it will provide information about the stream itself.

**Comment by opusforlife2** [comment]
Closing as it is a high effort, low return feature.
