### ISSUE TITLE
Which Google Play terms and conditions does NewPipe violate?

### ISSUE THREAD

**Issue by IgorBelyayev** [TeamNewPipe/NewPipe#2386]
In the project readme it states:
```
PUTTING NEWPIPE OR ANY FORK OF IT INTO GOOGLE PLAYSTORE VIOLATES THEIR TERMS OF CONDITIONS.
```

I'm curious: which specific terms and conditions does NewPipe violate?

**Comment by gkeegan** [comment]
Google doesn't like YouTube downloaders being in their store.

**Comment by snappyapple632** [comment]
NewPipe, in essence, offers features that Google would otherwise charge monthly for, such as downloading videos, listening to videos in the background, and an ad-free experience.
