### ISSUE TITLE
cant play one specific video

### ISSUE THREAD

**Issue by pcislocked** [TeamNewPipe/NewPipe#2389]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them. not too carefully but im not a jerk 
- [x] I checked if the issue/feature exists in the latest version. my version is 0.16.2
- [ ] I did not use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports because i dont have a bug report

i can see thumbnail, comments and video meta but i cannot play at foreground/background/popup or download [this specific video](https://www.youtube.com/watch?v=cB0YO1HVHTI)

but other videos are doing fine. im not sure about whats wrong but, yeah shortly this is what happened

**Comment by gkeegan** [comment]
This video plays fine for me. Try a VPN to another country.

**Comment by ilBEastli** [comment]
It works only at 360p on my phone.

**Comment by gkeegan** [comment]
Oh I see. Confirmed a bug. It seems like YouTube is providing music videos slightly differently again.

**Comment by pcislocked** [comment]
today I retried same song and it worked just fine. im not sure about should i close the ticket after gkeegan's comment

**Comment by sergioperez** [comment]
It is also happening to me with a lot of music videos.

It is happening to me with these videos:
https://www.youtube.com/watch?v=10v0h1CXSEM
https://www.youtube.com/watch?v=1SnHi7vp57E
https://www.youtube.com/watch?v=FXqp9WiFWzc
https://www.youtube.com/watch?v=IqxbWbEpms4

It does not happen with these ones:
https://www.youtube.com/watch?v=ujeENWevTlU
https://www.youtube.com/watch?v=L5QMZ9HPuPc
https://www.youtube.com/watch?v=8CdcCD5V-d8
https://www.youtube.com/watch?v=tbNlMtqrYS0

Yesterday it was happening to me with this one, but it seems to be working today:
https://www.youtube.com/watch?v=MtJju8htq0A

**Comment by poldown** [comment]
Isn't it possible to make the interface with YouTube fully customizable and take out it's settings to a remotely updated file..?

**Comment by sergioperez** [comment]
Not happening anymore :)
