### ISSUE TITLE
[Bug] 'Close' button restarts video with 'Minimize on app switch' enabled

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2391]
Steps to reproduce

 • Set 'Minimize on app switch' to popup or background in settings   
 • Reach the end of a video in Full Screen   
 • Tap 'Close' and the video will restart according to your previous preference

**Comment by TobiGr** [comment]
Yep, we dived into it some tie ago, but didn't have time to fix it. From https://github.com/TeamNewPipe/NewPipe/pull/2312#issuecomment-491604829:

>Thanks for reporting. I tried to track this down, but unfortunately, this wrong behaviour is not limited to the close button, but to all player exit actions when minimize to background/popup is enabled. I first tried to find any related code which has been touched during the work on this release. After debugging and searching for too long, it turned out that this bug existed in previous versions, too.
>
>Whenever a video is left by either closing it or switching to a different player, the player to minimize to is opened. For example, set minimize to background, open a video and than switch to popup. Both players will be started.

**Comment by Gymcap** [comment]
Just a possible idea:

Any action that is meant to close the video 100% of the time (i.e. 'close' button), should cancel the video in the same way the back button does.

 If I'm understanding something wrong please correct me, but pressing the back button seems to close the video in a way that bypasses this setting.

**Comment by TobiGr** [comment]
You are totally right.

**Comment by fightthepower** [comment]
This bug was there in the 0.16.1 and also in 0.16.2 . The problem with this bug is its point less to pause the video because it gonna restarts anyway after some time. Is this gonna be solved in next version?

**Comment by Gymcap** [comment]
That's a slightly different bug. I'll start an issue for it.

**Comment by opusforlife2** [comment]
Interesting. In 0.19.8, the player _does_ restart upon tapping close, but stays paused at the beginning.

Anyway this has become moot after the unified player PR, because all players are combined now. The cross button closes the notification as well as the main player/popup.
