### ISSUE TITLE
[Bug] Choosing caption in floating player shows as no captions

### ISSUE THREAD

**Issue by killoid** [TeamNewPipe/NewPipe#2393]
![IMG_20190608_005231](https://user-images.githubusercontent.com/6173607/59296253-51202900-8ca7-11e9-99e4-944c39e5d575.jpg)

as shown in the ss, choosing a caption to show will still show it as no captions. using the latest version from f-droid (0.16.2). it doen't happen in previous versions.

**Comment by gkeegan** [comment]
Confirmed. It seems like when captions were fixed in 0.16.2 that something was broken with this.

**Comment by R0ci0-V3rd3al** [comment]
_Hi. excuse me. where is version 0.16.2? I can not find it. the only error that I found the application in its previous version is that the previous version 0.16.1 does not play the audio or download the audio_

**Comment by Stypox** [comment]
@R0ci0-V3rd3al you can find the 0.16.2 version on [F-Droid](https://f-droid.org/app/org.schabi.newpipe) and on [GitHub releases](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.16.2).

**Comment by Redirion** [comment]
can you please tell me the name of the video you have tried? I assume that this is just an ui issue, where the subtitle name can not be matched to the extracted subtitles. I have already tried to build in a workaround for that by making case insensitive comparisons.

**Comment by killoid** [comment]
@Redirion https://youtube.com/watch?v=g6RcydERJLI
btw i am sure pretty much all the videos in youtube have the same issue. you can try any other videos to be confirmed.

**Comment by Redirion** [comment]
found the issue :(

**Comment by Redirion** [comment]
https://github.com/Redirion/NewPipe/releases/tag/v0.16.3

I have uploaded my debug apk with the fix. Please give it a try @killoid

**Comment by killoid** [comment]
@Redirion just tested your debug apk and everything is fine now! thanks!

**Comment by TobiGr** [comment]
@Redirion Thanks for fixing 👍
