### ISSUE TITLE
[Bug] Paused video resumes on screen off (Minimize on app switch) | [Request] Video/Player State Management (Continue Watching?)

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2395]
Steps to reproduce:   
• Enable minimize on app switch   
• Pause a video   
• Turn off screen

Video will start playing again.

I believe this bug could be fixed in conjunction with a 'continue watching' feature. If NewPipe could keep track of where you are in a video, then it could act accordingly in situations like this (video paused>screen off>don't resume) while allowing users to resume videos they had previously left (up to a certain amount). Think of this like YouTube's default 'continue watching' feature.

**Comment by Redirion** [comment]
this might have been fixed by a recent PR from me. If you are interested, please test it: https://github.com/Redirion/NewPipe/releases/tag/v0.16.3-2

**Comment by Gymcap** [comment]
Unfortunately I lack a platform to build on currently, otherwise I would.

**Comment by gkeegan** [comment]
There is an already compiled apk there, if you could use that instead of compiling yourself.

**Comment by Gymcap** [comment]
Tested. This keeps the video position (ended) but still follows 'Minimize on switch' settings when the close button is pressed. This results in the finished video appearing in popup (with endcard) or background.

**Comment by Redirion** [comment]
okay. but "Video will start playing again." is not happening anymore?

**Comment by Gymcap** [comment]
I apologize, I've mixed up the two issues I'm in.

In regards to your debug apk, It seems that now I have an inability skip forward with gui controls (reverse works) as well as not being able to pause a video at all.

**Comment by Redirion** [comment]
damn, you are right. I need to inspect this.

**Comment by nahuhh** [comment]
Fwiw, this also happens (on 16.2) when the video is over, not only when paused. 
Specifically, 
1. Player switches (main to popup/background) are happening with the screen off 
2. The play/pause/finished states are being ignored 

If possible, a finished video should not switch to background/popup at all
--
Play a video
Put your phone down
Video ends and screen turns off
With the screen still off, a new popup opens and the video starts playing from the beginning

**Comment by clockingin** [comment]
Just here to say that it happens to me too. On 16.2, my phone is a Samsung Galaxy S5 with LineageOS with microG.

**Comment by Stypox** [comment]
Closing in favour of #2391; "continue playing" has recently been implemented :-D
