### ISSUE TITLE
Update f-droid to latest version

### ISSUE THREAD

**Issue by alfredonodo** [TeamNewPipe/NewPipe#2398]
Hi,
I cannot install the latest apk version 0.16.2 on android 9 arm and arm64 downloaded from the Web site. Please upgrade it into [f-droid](https://f-droid.org/en/packages/org.schabi.newpipe/).
Best Regards.

**Comment by lionirdeadman** [comment]
We don't control when F-droid updates it. Please be patient.

**Comment by alfredonodo** [comment]
> We don't control when F-droid updates it. Please be patient.

Of course, but the current release stopped to work since one week.

**Comment by TobiGr** [comment]
The new version is available through F-Droid. You can download it either using the F-Droid app or directly: https://f-droid.org/repo/org.schabi.newpipe_740.apk
