### ISSUE TITLE
Add support for queing vidoes / songs

### ISSUE THREAD

**Issue by nickmdowson** [TeamNewPipe/NewPipe#240]
Hi,

I was wondering if you might consider adding support for queuing.

I guess I have in mind particularly queuing things to play in background, but I guess queuing whilst playing directly might be useful for some other users (this might be more complicated I suppose). queuing things for background playing would be great for listening to music :-)

Thanks for the app, I really like it, keep up the good work!

**Comment by theScrabi** [comment]
Queing is a nice idea. But I have t thousand of other things to to so I can't tell you when I could be able to implement something like this.

**Comment by nickmdowson** [comment]
That's fine I totally understand that!

On 13 March 2016 21:29:26 GMT+00:00, Christian Schabesberger <notifications@github.com> wrote:
>Queing is a nice idea. But I have t thousand of other things to to so I
>can't tell you when I could be able to implement something like this.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/theScrabi/NewPipe/issues/240#issuecomment-196056318

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by theScrabi** [comment]
Sorry :/ I didn't even manage to hit the goals I set for my self.

**Comment by nickmdowson** [comment]
Well I am learning to code so If I ever get good enough I will see if there's anything I can do myself!

On 14 March 2016 13:56:58 GMT+00:00, Christian Schabesberger <notifications@github.com> wrote:
>Sorry :/ I didn't even manage to hit the goals I set for my self.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/theScrabi/NewPipe/issues/240#issuecomment-196320167

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by theScrabi** [comment]
Sounds great :)

**Comment by shekhar575** [comment]
@nickmdowson 

Did you tried this feature for queing videos?
If yes, can you please let me know how you did it ?

Thanks

**Comment by nickmdowson** [comment]
Hi Shekhar,
I don't think this feature has been implemented yet but I believe it's on the wishlist

On 1 April 2016 15:30:30 BST, shekhar575 <notifications@github.com> wrote:
>@nickmdowson 
>
>Did you tried this feature for queing videos?
>If yes, can you please let me know how you did it ?
>
>Thanks
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/theScrabi/NewPipe/issues/240#issuecomment-204417496

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by devnoname120** [comment]
This would be a killer feature, especially at parties: people could add musics without interrupting the current one.

**Comment by theScrabi** [comment]
I'll add it as a future feature.

**Comment by karagenit** [comment]
Queuing could be really great - especially useful for implementing some sort of autoplay (see Issue #165), as (assuming the user has autoplay enabled) each video could automatically add the "Next Video" to the play queue. 

Plus (and this is thinking way in the future) it could enable us to have a Radio-Station like feature (such as that found in the Youtube Music app) ... and maybe even allow users to save these queues as playlists.

**Comment by PanderMusubi** [comment]
Would queueing also result in next to

Open with Newpipe popup mode

there also be

Open with Newpipe popup queue

?

**Comment by theScrabi** [comment]
So far there is no plan to do that.

**Comment by theScrabi** [comment]
Is coming with next release.

**Comment by FSMaxB** [comment]
Is this feature already out? And if yes: How can it be used (haven't found anything in the UI).

**Comment by karyogamy** [comment]
@FSMaxB 
To access the play queue, click on the notification for background/popup player. For main player, there is a new icon right beside the change mode button on the top right.
To add items to an existing queue, go into a video details page, then click and hold the background and popup button. 

@theScrabi 
Perhaps we should consider providing an update log in the app?

**Comment by FSMaxB** [comment]
Thanks!

**Comment by theScrabi** [comment]
> Perhaps we should consider providing an update log in the app?

Would be a good idea.

**Comment by TobiGr** [comment]
> Perhaps we should consider providing an update log in the app?
Yes definitely. I'am working on a concept for a kind of beginner tour for NewPipe right now, but I can do a changelog first.
