### ISSUE TITLE
Subtitle issues

### ISSUE THREAD

**Issue by newuser70** [TeamNewPipe/NewPipe#2400]
Hi,
I use version 0.16.2. on android 7.1.1 .
This problem occurs from the first subtitle download feature is existing.
1. Overlapping timecodes (subtitles apper on screen longer than it should be and cleared later) (seems to be  fixed on 0.16.2 if you made a fix on this you can ignore this)

2. There is a 1 blank line on every lines so the subtitle is displayed 1 line lower on video player. Eg.  :
0
00:00:01,000 --> 00:00:05,000

... Hello. There is an empty line above me ...

3. Italic text code 
<i> ....</i>
is not added on subtitle

4. Subtitle is not starting to download immediately. Manually must be started under download section (video download has same issue but it is already opened)

Ps : If i download subtitle via web-based site (eg. downsub. c o m) these errors do not exist.

**Comment by Stypox** [comment]
Point 4 should be fixed with #2149

**Comment by kapodamy** [comment]
please share the video link, so i can test. From now, most of "auto-generated" subtitles are broken and is a youtube fault.

**Comment by opusforlife2** [comment]
@newuser70 Please check if this is happening in the latest version and reopen if that is the case.
