### ISSUE TITLE
[Feature request] Dowload a playlist

### ISSUE THREAD

**Issue by djibux** [TeamNewPipe/NewPipe#2405]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hello,

I would love a feature to be able to download all videos/sounds in a playlist.
Currently, the only solution I found is to manually open each playlist item and click download.

**Comment by Stypox** [comment]
Duplicate of #1058
This feature will be added as soon as #2018 is merged

**Comment by djibux** [comment]
My bad, I’m sorry for the duplicate.  I did search for existing issues… but maybe I mis-typed "dowload" as I did in this issue.

**Comment by Stypox** [comment]
No problem :-)
