### ISSUE TITLE
Don't add autoplay item if last item is removed

### ISSUE THREAD

**Issue by FunctionalHacker** [TeamNewPipe/NewPipe#2408]
With autoplay turned on, NewPipe keeps adding the next video if I remove it.

My usecase where this is apparent: I like to play some music when going to sleep but if autoplay is on, NewPipe keeps adding videos to the playlist until the end of time and it will still be playing when I wake up. This means I will have to go to the settings and disable autoplay to get the effect I want.

Alternatively, we could implement a switch to the playlist editor which temporarily disables autoplay for the current session only.

**Comment by ReekyMarko** [comment]
Found a related comment to this: https://github.com/TeamNewPipe/NewPipe/pull/1878#issuecomment-445360261

**Comment by shivanju** [comment]
I think having a `switch` for enabling/disabling auto queue would be good. @TobiGr  what do you think?

**Comment by hunkjazz** [comment]
This feature is implemented in both:

- VLC;
- Twirte.

I think it's called "sleep".

**Comment by FunctionalHacker** [comment]
There seems to be a switch implemented in the latest version, so this issue is respolved
