### ISSUE TITLE
[Request] 'Tabbed' Channel View (Owner Created Playlists/Etc)

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2409]
Many channels have playlists so viewers can watch a long series at once.    
It would be nice if we could have a second page on channels that allows us to [view playlists](https://youtube.com/user/GameGrumps/playlists)(open in browser) created by that channel.

This could go further into adding an 'About' or 'Affiliated Channels' page if wanted.

**Comment by gkeegan** [comment]
Yeah this is a pretty good thing that could be added.

**Comment by Stypox** [comment]
Closing in favour of #2414
