### ISSUE TITLE
problem importing subscriptions from youtube

### ISSUE THREAD

**Issue by cuilean** [TeamNewPipe/NewPipe#2410]
When I try to import subscriptions, all that is downloaded is a file called "subscription manager" instead. I see no export file. I am fully updated as well. I saw a proposal of downloading through the PC and placing it on your mobile, but the download is still the same. Am I doing anything wrong?

**Comment by cuilean** [comment]
i fixed it, sorry

**Comment by gkeegan** [comment]
No worries. I'm glad it worked out for you so you can enjoy NewPipe. :)
