### ISSUE TITLE
I'd like to help moderating and classifying issues

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#2411]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Hello :-)
Every now and then I look for something I can help with in NewPipe (e.g. a bugfix, an issue discussion...), but it's difficult to find an issue to focus on, since almost none of them have labels. I think labelling every issue (with bug, enhancement and so on) would benefit the project, making them simpler to navigate through and more welcoming for newcomers.
When I was a newcomer myself (some months ago), it took me ages to find [something simple](https://github.com/TeamNewPipe/NewPipe/pull/2271) I could work on in order to familiarise with the codebase: there are not many issues available in the "[for beginners](https://github.com/TeamNewPipe/NewPipe/labels/for%20beginner)" section.

For the reasons stated above I would like to get the permission to classify the issues. I would go through all of the open issues and add a label. The permission to close duplicates / already fixed ones would be appreciated, too, but I think that's asking too much since I've not been into the project for many months :-)

**Comment by gkeegan** [comment]
I think that's a good idea since you've been doing an excellent job at managing issues and helping solve them.

**Comment by Gymcap** [comment]
As someone who has nothing to do with programming NewPipe, and who's opinion holds absolutely no weight on this subject, I agree with this.

Good luck!

**Comment by theScrabi** [comment]
@TobiGr ill give access for @Stypox to moderate issues.

**Comment by theScrabi** [comment]
@Stypox I've send you a Triage invitation. This should give you the permission to moderate the issues and pull requests. :)

**Comment by Stypox** [comment]
Thanks :-)
I'll do the work in the following days
