### ISSUE TITLE
Issue #48 disappeared

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/NewPipe#2420]
Seems like GitHub deleted https://github.com/TeamNewPipe/NewPipe/issues/48 without any notice, or did anyone get a mail from them?

Someone should reach out to them and ask why they deleted it and whether we could get it back.

**Comment by TobiGr** [comment]
@TheAssassin I didn't get a mail, too. I've sent the GitHub support a mail.

**Comment by TobiGr** [comment]
The GitHub support was fast on this xD
> It looks like the user who created the Issue has been marked as spam, which causes all of their content--including issues--to be hidden from public view.

@TheAssassin Issue content: [TeamNewPipe-NewPipe-48.md.zip](https://github.com/TeamNewPipe/NewPipe/files/3477159/TeamNewPipe-NewPipe-48.md.zip)

**Comment by TheAssassin** [comment]
@TobiGr it would've been nice if they'd informed the maintainers of the project or organization so they could've restored it if it was no spam. Thanks for taking care of this.
