### ISSUE TITLE
[Feature Request] What's new page, parse video from RSS feed

### ISSUE THREAD

**Issue by masozzi** [TeamNewPipe/NewPipe#2424]
Currenty the _what's new_ page fetches the new videos from the each channels page (taking only the first video).

Would be possible to get the new videos from the RSS feed instead?
Also, i think that #2404 would benefit from that.

I could open a PR for those changes, but i'd prefer some feedback before start the development.
I understand that part of this would need to be done in the extractor, rather that the app itself.

**Comment by phatloot123** [comment]
take a look at https://github.com/TeamNewPipe/NewPipe/pull/2309 before you start development

**Comment by masozzi** [comment]
Thanks @phatloot123 !
That PR would add the requested feature.
