### ISSUE TITLE
Channel links unsupported

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/NewPipe#2425]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

- [X] I checked if the issue/feature exists in the latest version.

- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Channel links in this format cannot be opened in NewPipe, and give a "Unsupported URL" toast notification. Any variants of this (https/http/www/m) do not effect if it works. Tested on a debug build of very recent commits.

youtube.com/c/channelname

**Comment by Redirion** [comment]
I tested a few channels, this does rarely work as the actual channelname that needs to be inserted may be different from the channel name that is shown to the user.

For example the channel Coreteks, it does work: 
https://www.youtube.com/channel/UCX_t3BvnQtS5IHzto_y7tbw 
https://www.youtube.com/c/Coreteks

For the channel Hardware Unboxed, it doesn't work:
https://www.youtube.com/channel/UCI8iQa1hv7oV_Z8D35vVuSg
https://www.youtube.com/c/Hardware%20Unboxed

is this a widely used format?

**Comment by gkeegan** [comment]
I don't believe it is widely used. It's mostly for posting YouTubers that were present in the video into the description in order to share credit, or for easy posting of a channel online.

I suppose it could be done by checking if the link redirects to the youtube.com/oops domain when visited, which is what happens for me when a channel link doesn't work.
