### ISSUE TITLE
Video loads sometimes, and halts at 00:00 other times.

### ISSUE THREAD

**Issue by DenizBasgoren** [TeamNewPipe/NewPipe#2426]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Most of the time when I go run the app, then search the video, find it, and try to run it,
- if in background mode, image gets loaded, time is always 00:00 and video doesnt play.
- if in popup mode, popup is in black and has a loader spinner.
- if i hit play button , same thing happens as in popup mode.

However this doesnt happen all the time, and if youre lucky, video loads and runs seamlessly. Same thing could happen to the next video though.

I realized that this behavior is independent of the video. It could happen to just about any video. And most importantly, that it tends to misbehave only if run the video impatiently. That is, if I wait for like 10 minutes before running, it is less likely to misbehave.

I use lenovo p2a42 phone with android 6.0.1. ram 4 gb

**Comment by Stypox** [comment]
Which NewPipe version are you using?

**Comment by goxr3plus** [comment]
I am facing the exactly same issue two

**Comment by hp8wvvvgnj6asjm7** [comment]
This happens all the time!

**Comment by Stypox** [comment]
Could you provide a link to a video that does not work? Just so that we can determine whether it is reproducible at any time or if it is just something that creates problems sometimes

**Comment by gkeegan** [comment]
@Stypox I believe this is related to the issues with music videos in particular. Other videos are fine. I have noticed the issue as well.

**Comment by DenizBasgoren** [comment]
Here are some videos I tried to run:

works
https://www.youtube.com/watch?v=S8n3usXreL0

doesnt
https://www.youtube.com/watch?v=WEQnzs8wl6E

works, again
https://www.youtube.com/watch?v=S8n3usXreL0

doesnt
https://www.youtube.com/watch?v=Ckom3gf57Yw

works
https://www.youtube.com/watch?v=_M_Yhlh2PTo

works
https://www.youtube.com/watch?v=IJhgZBn-LHg

works
https://www.youtube.com/watch?v=gLDYtH1RH-U

doesnt
https://www.youtube.com/watch?v=QJJYpsA5tv8

doesnt
https://youtu.be/p2FZvPLWf_M

works
https://www.youtube.com/watch?v=X7rhovBK_eA

works
https://www.youtube.com/watch?v=yWQo_AAHDUA

doesnt
https://youtu.be/vq3hP9Sd1sM

doesnt
https://www.youtube.com/watch?v=v4xZUr0BEfE


My version is 0.16.1
Default video format: MPEG4
Default audio format: M4A

**Comment by gkeegan** [comment]
Please use the latest versions when submitted bug reports. Update to 0.16.2 and test these videos again please. @DenizBasgoren

**Comment by DenizBasgoren** [comment]
Seems to work on the new version. Didnt encounter this issue yet.
