### ISSUE TITLE
[Request] can you make a music player that support option ignore silence+playback,or make Newpipe music player work offline

### ISSUE THREAD

**Issue by alayoubiyoun** [TeamNewPipe/NewPipe#2427]
i love that player of Newpipe and i want it as player audio plzz

**Comment by alayoubiyoun** [comment]
just i love that player of Newpipe and i want it as player audio plzz

**Comment by gkeegan** [comment]
I would say that this is related to #478 in some capacity. Also, please make separate requests in separate issues (after searching to check if they don't exist as issues already)

**Comment by alayoubiyoun** [comment]
> I would say that this is related to #478 in some capacity. Also, please make separate requests in separate issues (after searching to check if they don't exist as issues already)

Ok just i want to play offline music with Newpipe playback(ignore silence feauture +pitch+Tempo) can you help me

**Comment by gkeegan** [comment]
Please go to that issue (478) and request this feature.

**Comment by alayoubiyoun** [comment]
Ok plz reopen this i want this feauture of ignore silence and playback  offline so badly i will pay for it if you want

**Comment by Stypox** [comment]
This is a duplicate of #1052 . Sorry if I didn't point that out, but at first I thought this was a duplicate of #478 :-)
If you want to encourage someone to implement this feature you can open a bounty on [BountySource](https://www.bountysource.com/teams/newpipe)
