### ISSUE TITLE
[Request] i want Newpipe to play music offline she has beautifull sound with that player(ignore silence+Tempo+pitch)

### ISSUE THREAD

**Issue by alayoubiyoun** [TeamNewPipe/NewPipe#2428]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by gkeegan** [comment]
Please do not create two issues asking for the same thing. 

Go to the issue I suggested to you to try to get more attention to this feature you want.
