### ISSUE TITLE
High Battery And Data Usage

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#2436]
Reduce the battery and data usage of the app

![Screenshot_20190629-201523](https://user-images.githubusercontent.com/18757054/60387995-74bae000-9aab-11e9-8242-f2f7c9eb6ee7.png)

![Screenshot_20190629-201824](https://user-images.githubusercontent.com/18757054/60387997-7b495780-9aab-11e9-9c22-04139b571bd8.png)

**Comment by Stypox** [comment]
As you have been said multiple times, if we don't know more information about when too much battery is used, we can't do anything.
Also, data usage can't be reduced: a video provided by youtube at (e.g.) 8kb/s can't be sent to the phone with less than 8kb/s...
