### ISSUE TITLE
Scrolling jumps when "Animator duration scale" is set 

### ISSUE THREAD

**Issue by jimbo1qaz** [TeamNewPipe/NewPipe#2437]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] ~~I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.~~

On my phone, I set "Animator duration scale" to Off (0 duration). Then I open the "Youtube video info screen" (with a large tappable video image).

- When I scroll up and release my finger *with the video icon partially on the screen*, the entire page snaps up to the top of the page.
- If I scroll down and release my finger *with the video icon partially on the screen*, the entire page snaps down so the video is entirely off-screen, and then normal momentum scrolling begins.

The bug goes away if I change "Animator duration scale" to 1x duration.

Moto G5 Plus, Android 7.0, Newpipe 0.16.2 (F-Droid?).

**Comment by gkeegan** [comment]
Confirmed on Android 9, NewPipe 0.16.2 (my own build with latest commits).

**Comment by Redirion** [comment]
this might be fixed with PR #2372 in particular with this commit https://github.com/TeamNewPipe/NewPipe/pull/2372/commits/28310de86f6a3560ef8c3580b83cec7082509e19

once I figured out how to fix the merge issues I will provide a debug apk for you to test

**Comment by Stypox** [comment]
Can confirm, this is present in 0.17.3
