### ISSUE TITLE
I've tried to download a video and now the app doesn't open

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2443]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I can't report the bug anywhere else, because the app doesn't open anymore.

At first I've tried to download this video: https://youtu.be/_N94HCqhTeE
It stopped in the middle of the download. Then I tried to pause it and download again. Doesn't work. I've tried to download again with another name. Didn't work and then the app working.

**Comment by Stypox** [comment]
What version are you using? Have you tried reinstalling the app?
And what do you mean by " the app does not open anymore"? Does it show the red&white startup icon and then stops, or not?

**Comment by kapodamy** [comment]
Inside of a file explorer, go to followig path:
**/sdcard/Android/data/org.schabi.newpipe/files/pending_downloads**
or
**/storage/emulated/0/Android/data/org.schabi.newpipe/files/pending_downloads**

attach here the files inside of that folder or just delete them and try open the app again.

**Comment by opusforlife2** [comment]
Account gone. No info possible.
