### ISSUE TITLE
[Feature request] Download after clicking a youtube link and opening in NewPipe

### ISSUE THREAD

**Issue by AdKiller** [TeamNewPipe/NewPipe#2446]
When I click a youtube link from another program and open the video in NewPipe there is no way to download that video. 
Would it be possible to add this option?

Thank you.

Example screenshot:
![image](https://user-images.githubusercontent.com/13304436/60736487-7119d400-9f57-11e9-8173-9e8006e09bbb.png)

**Comment by Stypox** [comment]
Duplicate of #1064 and #1873
