### ISSUE TITLE
[solved] 0.7.6 - Share with NewPipe, similar videos bug

### ISSUE THREAD

**Issue by ministro** [TeamNewPipe/NewPipe#245]
When video is opened using Share with NewPipe (1.1),
attempting to open similar video throws the following popup error:
failed to find pattern _(regex)_ inside of _(document url)_

**Comment by theScrabi** [comment]
You may need to uograde to 0.7.7 if its not yet available for you wait for the next version.

**Comment by ministro** [comment]
Thank you! Will report status when upgraded.

**Comment by theScrabi** [comment]
"Any intentions to support playlists?" - Yes ... one day

**Comment by ministro** [comment]
I wish I could help, but I suck at Java
On Mar 20, 2016 7:41 PM, Christian Schabesberger <notifications@github.com> wrote:"Any intentions to support playlists?" - Yes ... one day
