### ISSUE TITLE
Newpipe doesn't reload the expired links

### ISSUE THREAD

**Issue by jojosilva** [TeamNewPipe/NewPipe#2451]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

If we pause a download for a few hours, we can't resume it because the link is expired. The error message is "403 not found". Can you please make it so newpipe can reload the page automatically when the link expired and resume the download.

**Comment by mehedihasanziku** [comment]
Yes, This is new issue now, not updating the expired links
