### ISSUE TITLE
How i can play music offline with Newpipe ,can you add READ permission

### ISSUE THREAD

**Issue by alayoubiyoun** [TeamNewPipe/NewPipe#2454]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
Take a look at #155 #478
