### ISSUE TITLE
Samsung A20e Overheating

### ISSUE THREAD

**Issue by IonutDaniel99** [TeamNewPipe/NewPipe#2457]
So i bought a new phone , Samsung A20e . I downloaded NewPipe from github(latest Version 0.16.2 or something like this) and after configuration and importing old setting i started to listen on of my playlists from playlist tab. After 10 minutes i got an error from phone ,,Your device Overheated,we close all applications ... ,, i think it was a bug from phone,then again(in the same app,i didnt figured this problem yet)..so again i think it was an error and i restarted the phone. Today i got the same problem with overheating and after this i downloaded a CPU monitor. In some moment when im listening at max volume,my CPU goes from 30C to 70-90C for 20 second,then decrease again to 30....and it became a loop ... waiting 10 second -> 70 C -> 30C ->10 second...and so one.. 

i dont know what should i do(maybe i will install an old version)

i know i have a lot of english grammar mistakes and speaking error but i`m trying to improve it so sorry if i angry you with my mistakes.Also if u can change wrong words in good one it will help me a lot to understand where i  was wrong..

**Comment by gkeegan** [comment]
Old versions won't work that well since YouTube has changed things and videos won't load on those older versions. 

This is really odd behavior though. I've never seen any issues about overheating with NewPipe. Does this issue only happen when the volume is at maximum? And is it using headphones or the speaker?

**Comment by kiwipear** [comment]
I'm having the exact same problem, and I'm using the exact same phone model. There is definitely something weird going on since NewPipe is the only app giving me this message/error.

**Comment by gkeegan** [comment]
Does the problem change when you are setting the volume through the volume buttons vs sliding via gesture in NewPipe?

**Comment by rafael1998ma** [comment]
> So i bought a new phone , Samsung A20e . I downloaded NewPipe from github(latest Version 0.16.2 or something like this) and after configuration and importing old setting i started to listen on of my playlists from playlist tab. After 10 minutes i got an error from phone ,,Your device Overheated,we close all applications ... ,, i think it was a bug from phone,then again(in the same app,i didnt figured this problem yet)..so again i think it was an error and i restarted the phone. Today i got the same problem with overheating and after this i downloaded a CPU monitor. In some moment when im listening at max volume,my CPU goes from 30C to 70-90C for 20 second,then decrease again to 30....and it became a loop ... waiting 10 second -> 70 C -> 30C ->10 second...and so one..
> 
> i dont know what should i do(maybe i will install an old version)
> 
> i know i have a lot of english grammar mistakes and speaking error but i`m trying to improve it so sorry if i angry you with my mistakes.Also if u can change wrong words in good one it will help me a lot to understand where i was wrong..

I have the same issue and i'm lookin forward next week to deliver it into service

**Comment by opusforlife2** [comment]
Was the problem fixed? If not, could you test if this still happens on 0.20.0?
