### ISSUE TITLE
搜索栏默认的“急上昇”三个字不妥

### ISSUE THREAD

**Issue by rrn21833** [TeamNewPipe/NewPipe#2460]
搜索栏默认的“急上昇”三个字看着怪怪的，越看越不适。
![20190714-114631](https://user-images.githubusercontent.com/37966911/61179079-b613c980-a62d-11e9-8ecc-63b9a2518f3e.png)

**Comment by Stypox** [comment]
Please read the contribution guidelines: issues must be submitted in English language.
