### ISSUE TITLE
sound not working for videos

### ISSUE THREAD

**Issue by cuilean** [TeamNewPipe/NewPipe#2463]
when i download a video as an audio, it works. but when i download a video that has audio with it (say, a pewdiepie video) it only downloads the visuals and no sound. i have tried downloading in different settings but nothing works so far.

interestingly, i had imported the video on my PC, and the sound worked. on mobile, it doesn't.

**Comment by dirtygardner** [comment]
SM-G530A_Android-5.1.1_NewPipe-0.16.2

If download youtube video in 1080p, then sound doesn't work.

**Comment by Stypox** [comment]
@karyogamy has this anything to do with #2542, or will it be fixed?

**Comment by opusforlife2** [comment]
@cuilean @dirtygardner Can you see if this is still an issue in 0.19.8? I'm pretty sure this was fixed by kapodamy months ago.

**Comment by dirtygardner** [comment]
> @cuilean @dirtygardner Can you see if this is still an issue in 0.19.8? I'm pretty sure this was fixed by kapodamy months ago.

Works for 2 out of 2 videos tested (SM-G930R4_Android-8.0.0_NewPipe-0.19.8).
