### ISSUE TITLE
Downloads via cell network even though WiFi is available 

### ISSUE THREAD

**Issue by guidot** [TeamNewPipe/NewPipe#247]
- NewPipe 0.7.6
- Android 6.0.1_r22
- WiFi > advanced settings > avoid poor connections: OFF
- WiFi connection established
- Data usage > restrict app background data: ON

I started a video-download and half a minute later NewPipe had used up my high speed cell data volume :(

I'm not sure it is actually NewPipe's fault. How could that happen given the settings mentioned above?

If that is indeed possible I suggest a setting that allows the user to limit network usage to WiFi only. 

Thanks in advance!

**Comment by theScrabi** [comment]
As far as I know Newpipe still redirects downloads to the Android Download manager. So if there is really an error, it would most likely be located there.
