### ISSUE TITLE
After some newpipe/android updated webm audio and video slows down gui+notification/progress probing, sometimes causes crashes.

### ISSUE THREAD

**Issue by kubast2** [TeamNewPipe/NewPipe#2471]
And agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
I will paste in crash report later if and when it happens, in general sometimes the app runs so slow it crashes

**Comment by kubast2** [comment]
Iirc the bug is since newpipe 11.2/12.0 or/and android 8.0

**Comment by Stypox** [comment]
Insert an "x" inside the [ ] to tick the boxes

**Comment by Stypox** [comment]
This is probably a duplicate of #2170, can you confirm @kubast2 ?

**Comment by kubast2** [comment]
I do believe so, I am not sure rn if it is cause by certain videos or by chainging default audio format to webm.
