### ISSUE TITLE
newpipeextractor repo gives 500

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#2472]
I just wanted to push something,
but now [newpipe extractor](https://github.com/teamnewpipe/newpipeextractor) gives a 500. Can someone confirm?

![lol mp4](https://user-images.githubusercontent.com/1891273/61646282-56f72a00-aca9-11e9-8f0d-7f2655c7f921.gif)

**Comment by TobiGr** [comment]
Uh. I can reproduce it. We should contact the dev support.

**Comment by Stypox** [comment]
For me now it works

**Comment by theScrabi** [comment]
It seems to work again :)
