### ISSUE TITLE
[FR] Button to lock app input via touch while video play

### ISSUE THREAD

**Issue by Catfriend1** [TeamNewPipe/NewPipe#2473]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi,

Please add a button "lock/unlock" which allows the ui to ignore touch while video playing. I have one of those notch+large screen are phones and would hold it comfortly in my hands while playing back and watching a video. If the app reacts to every touch on the outer display areas while holding I accidentially click things I didn't mean to do.
E.g. mx player also has this option.

Keep up the good work :-).

Kind regards
Catfriend1

**Comment by isgarlo** [comment]
VLC for Android has also that feature. It's called **lock button** which locks the screen so that you can watch the video in peace. Accidentally tapping on the screen will do nothing.

**Comment by Stypox** [comment]
Duplicate of #1734

**Comment by ghost** [comment]
please delete issue
