### ISSUE TITLE
save sdcard not work And saved 86BF-74E4/android/media/org.schabi.newpipe, does not support very large file size

### ISSUE THREAD

**Issue by Herman0701** [TeamNewPipe/NewPipe#2475]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I am trying to download videos in micro SD memory in 4k and 2k but I do not get any download, it only allows me to download 720p and 480 and lower resolutions

**Comment by Stypox** [comment]
The next version contains the fix for your problems. See #2149
