### ISSUE TITLE
[Feature Request] Add an option to stop automatic download of video thumbnails

### ISSUE THREAD

**Issue by Bunnicula2** [TeamNewPipe/NewPipe#2479]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Whenever I open a personal playlist or my video history, NewPipe appears to fetch thumbnails that haven't been cached. When I scroll down the video history when offline, only the first few thumbnails are shown; when I do it online, thumbnails get loaded immediately. The same behavior applies to opening the background player interface (including the notification entry).

This is a possible privacy leak, and I believe this is how Youtube keeps identifying me and serving me the same garbage recommended videos over and over no matter how many IPs I change.

Hence I'd like an option, not necessarily a very visible one where this auto downloading is disabled for locally stored playlists and video history. There's probably no benefit to disabling this on searches and Youtube's public playlists since you've already transmitted the search term/playlist name to Youtube, although if you block the thumbnails here too, I won't care.

Alternatively, an option to increase thumbnail cache to arbitrary levels would work too and preserve the appearance, although for frequent NewPipe users this cache could grow very large.

**Comment by gkeegan** [comment]
You can disable loading of thumbnails in the settings>content>load thumbnails.

Your other suggestions are pretty good though.

**Comment by Bunnicula2** [comment]
Thanks, dunno how I missed that option.

**Comment by gkeegan** [comment]
No problem! It's easy to miss things sometimes when skimming for specific phrases.

**Comment by AnotherLife** [comment]
Well, close the issue then...
