### ISSUE TITLE
when will the version 17 of the legacy app will be uploaded?

### ISSUE THREAD

**Issue by tedadd** [TeamNewPipe/NewPipe#2490]
I just want to know when will the latest version of the legacy app will be released. My phone is below android 4.4. There are many errors in the current latest legacy version and its a pain. Please release it as quickly as possible. Thanks

**Comment by Pentaphon** [comment]
@tedadd When will you buy a new phone or install a custom rom?

**Comment by Stypox** [comment]
@Pentaphon that's not the right way to think. That's consumism.

**Comment by theScrabi** [comment]
First that second please no personal attaks here.

**Comment by Pentaphon** [comment]
@Pentaphon I told him to install a custom rom as an option. He can't expect his phone to be supported by devs forever. Even at some point, he will have to buy a new phone no matter what.

**Comment by theScrabi** [comment]
@tedadd however you may ask this question over at the legecy repository of newpipe, as that one has a different maintainer.

**Comment by Stypox** [comment]
See TeamNewPipe/NewPipe-legacy#14
