### ISSUE TITLE
Can't import subscriptions on Android Q Beta 5

### ISSUE THREAD

**Issue by 101118496** [TeamNewPipe/NewPipe#2491]
Location defaults to storage/emulated/0 but all the directories are completely empty.
Best of luck, love your work :)

**Comment by 101118496** [comment]
Thank you sorry about that!

**Comment by Stypox** [comment]
Is this a duplicate of #2470 ?

**Comment by Stypox** [comment]
This is old and was probably fixed in the meantime. Btw, could you try if #3777 works?
