### ISSUE TITLE
Sorry an error occurred 

### ISSUE THREAD

**Issue by wolfnuts69** [TeamNewPipe/NewPipe#2494]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
Opening any source for an album to down load audio it comes up and says sorry some errors occurred I've tried all sorts

**Comment by theScrabi** [comment]
Please read the contribution guidelinrs about bugreporting.
