### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by GiovanniSM20** [TeamNewPipe/NewPipe#2497]
one thing i feel like in newpipe other than youtube is a button for screen sharing. would like an assessment of the feature (if possible). depending on the outcome, I intend to implement the same.

tks!

**Comment by Stypox** [comment]
What do you mean by "screen sharing"? Syncronizing your video with someone, like https://www.watch2gether.com/ ?

**Comment by gkeegan** [comment]
I think this means like Chromecast. @Stypox

**Comment by Stypox** [comment]
Then it is a duplicate of #668 and #105
