### ISSUE TITLE
How to remove "download button"? & How to make "Light theme" default?

### ISSUE THREAD

**Issue by zakariamohey** [TeamNewPipe/NewPipe#2500]
Only want to know the files!
Thanks

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment]
1. Please reed the cobtribution guidelines.
2. U cant remove the download button.
3. You can set the theme in the settings.
