### ISSUE TITLE
Trending loading problems after update 0.17.0

### ISSUE THREAD

**Issue by ronidee** [TeamNewPipe/NewPipe#2503]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

- Install update
- open NewPipe
- trending kiosk appeared
- but no entries, only infinite loading circle
- no touch input gets registered
- after a while (15 seconds..) dialog appears "app is not responding"
- I press wait, one second later app closes

The app also constantly freeze and crashes
Clearing cache, force stop didn't resolve the issue.

Sometimes, when I open the app, then pause (back, recents) and come back after a minute, everything works.

![Screenshot_20190812-150356_NewPipe](https://user-images.githubusercontent.com/22625272/62867153-e759e500-bd12-11e9-8eca-5738a8dcc3eb.png)

**Comment by TobiGr** [comment]
Can you please go to the settings > History & Cache and clear the cache? Maybe this is a caching problem, otherwise we need to dig a bit deeper. What Android version are you using?

**Comment by ronidee** [comment]
I'm using AEX, API 28, no GApps.
I cleared the cache (not the history tho), now after pressing "wait" on the dialog it finally loads the trending page. Takes about 30 seconds. Both with 4G and Wi-Fi (250 mbit/s) so it's most certainly not a network problem.
When I'm home I will provide a log file.

**Comment by TobiGr** [comment]
Uh. I am sorry.  For the next time: you can export and import your NewPipe data in the content settings

**Comment by ronidee** [comment]
I did, but doesn't it only include the subscriptions?

**Comment by ronidee** [comment]
And just so you know, I've kept my watch history since many months (easily half a year) and use NewPipe on a daily basis - it's also my default music player, so it had probably 5k - 10k entries. 
On the other hand, deleting the watch-history + cache + searches didn't resolve the issue. 
Hope this info helps.

**Comment by TobiGr** [comment]
For more info and a temporary fix, please take a look at https://github.com/TeamNewPipe/NewPipe/issues/2507#issuecomment-520584085
