### ISSUE TITLE
Can't enable "Documents" for 0.17.0 on Android 5.x

### ISSUE THREAD

**Issue by Symbian9** [TeamNewPipe/NewPipe#2504]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

After upgrading from `0.16.2` to `0.17.0` NewPipe start asking for:

> Turn on Documents in Settings > Installed apps first

![pic.1](https://i.imgur.com/yMkrleA.png)

![pic.2](https://i.imgur.com/yxleSSe.png)

But when I open permissions of NewPipe in "Installed apps" I see that there NO "Documents".

![pic.3](https://i.imgur.com/N94otIw.png)

How should I allow downloading for `0.17.0`?

Android: `5.1.1` (Redmi 3)

**Comment by TobiGr** [comment]
@kapodamy Do we need to ask for a different storage permission on Android 5?

**Comment by kapodamy** [comment]
@TobiGr @Symbian9 
not sure, but appears a MIUI restriction. You need enable an app called `Documents`, because is disabled/desactivated/freezed by default.

**Comment by Symbian9** [comment]
> MIUI restriction. You need enable an app called Documents, because is disabled/desactivated/freezed by default.

Is it possible fix it in `0.17.x`? With `0.16.x` I had not such "MIUI dependency".

**Comment by kapodamy** [comment]
> 
> 
> > MIUI restriction. You need enable an app called Documents, because is disabled/desactivated/freezed by default.
> 
> Is it possible fix it in `0.17.x`? With `0.16.x` I had not such "MIUI dependency".

NO
is not related to newpipe is an android issue and cannot be fixed

**Comment by theScrabi** [comment]
So we need to add legecy support @kapodamy how vomplicated will it be?

**Comment by kapodamy** [comment]
@theScrabi is not complicated

@Symbian9 please try this:
* check the option "**Ask where to download**"
* try download something
* choose save the file in somewhere

if you not see this screen "**save as**" dialog, please tell me:
![Screenshot_1565801438](https://user-images.githubusercontent.com/16857233/63039778-6e859500-be9a-11e9-93dc-9f5e0c874b1d.png)![Screenshot_1565801442](https://user-images.githubusercontent.com/16857233/63039785-70e7ef00-be9a-11e9-8fb7-8ec95ceb4e02.png)

**Comment by Symbian9** [comment]
> please try this

What build should I use? As `0.17.0` release files removed.

**Comment by kapodamy** [comment]
yes with the 0.17 version, post back @theScrabi the files

**Comment by Symbian9** [comment]
> please try this:

> - check the option "Ask where to download"
> - try download something
> - choose save the file in somewhere
>
> if you not see this screen "save as" dialog, please tell me:

NOT work! Just tried `0.17.0RC4` build but has same behavior as described in first message in this thread — NewPipe start show me warning *"Turn on Documents in Settings > Installed apps first"* and I can't reach file chooser window.

**Comment by TobiGr** [comment]
@Symbian9 Can you please test the apk, I linked in https://github.com/TeamNewPipe/NewPipe/pull/2521#issuecomment-521547093?

**Comment by Symbian9** [comment]
Can you please test the apk, I linked in https://github.com/TeamNewPipe/NewPipe/pull/2521#issuecomment-521547093 ?

Just tried - still has same behaviour as described above.

NOT work :-(

**Comment by theScrabi** [comment]
I tried it on android 5, for me it worked.

**Comment by TobiGr** [comment]
It looks like I uploaded the wrong apk... :man_facepalming: Sorry.
Next try: [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3507014/app-debug.apk.zip)

**Comment by theScrabi** [comment]
It should look like this:
![untitled webm](https://user-images.githubusercontent.com/1891273/63124285-3621ac00-bfab-11e9-8500-32d2dcb50dc4.gif)

**Comment by Symbian9** [comment]
> It should look like this:

On my Androud 5.1.1 with MIUI I reached floated warning *"Turn on Documents in Settings > Installed apps first"* and can't reach file manager window :-(

**Comment by theScrabi** [comment]
try this once more:
[app-release.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3509283/app-release.apk.zip)

**Comment by theScrabi** [comment]
However the more I think about this the more I get the feeling this is more of a problem by MIUI. Chinese phone producers, and especially Xiaumi tend to brake Android compatibility. Especially Xiaumi, as we had trouble with their phones before in other parts.

I took a look around, for your phone is a never version for MIUI available:
http://c.mi.com/oc/miuidownload/detail?device=1700298

LOS 14.1 (android 7) seemed to be the last supported Lineage os version, however they stopped support so you can't even download it anymore.

Here seems an AOSP rom for playin android 6, however I'd be carefull with custom builds:
https://forum.xda-developers.com/redmi-3/development/rom-pixelexperience-ido-t3742977

**Comment by Symbian9** [comment]
> try this once more:

NO luck :-(

**Comment by theScrabi** [comment]
Well it seems to me that this asf filepicker acticity is not available on MIUI, which otherwise is on other android 5.x+ phones. @kapodamy was it complicated to activate that internal filepicker activity again, or did you do this already, and on @Symbian9  it still does show this error? If so we would need to add a manual setting for which  IO to use.

**Comment by kapodamy** [comment]
@Symbian9 ok

**Comment by Symbian9** [comment]
> ok

@kapodamy, should I test some nightly build?

**Comment by TobiGr** [comment]
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3512261/app-debug.apk.zip)

**Comment by Symbian9** [comment]
@TobiGr It's working! 🎉

**Comment by theScrabi** [comment]
instand merge huraaay

**Comment by Symbian9** [comment]
@TobiGr @theScrabi, It seems like there is regression in *NewPipe* `v0.21.15` — it asks "enable Documents" again (there was no such issue with `v0.21.14`)

- https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.21.15

Could be it fixed now once more?
