### ISSUE TITLE
Reduced performance caused by playback position in list views

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#2507]
Just completely freezes..
![Uploading Screenshot_2019-08-12-22-09-49.png…]()

**Comment by hp8wvvvgnj6asjm7** [comment]
I hoped for fixes with this update...

**Comment by hp8wvvvgnj6asjm7** [comment]
Going to revert to previous version, until fixed. Background player crashes too. App freezes for no apparent reason.

**Comment by hp8wvvvgnj6asjm7** [comment]
Is a YouTube employee sabotaging this project?

**Comment by TobiGr** [comment]
> Is a YouTube employee sabotaging this project?

No

> Just completely freezes..

Which Android version are you using?

**Comment by hp8wvvvgnj6asjm7** [comment]
Android 5.0.2
It looks as if the last played list is pretty long, which causes the freezing? Possibly because it has to check the last played time?

**Comment by TobiGr** [comment]
Can you please clear the cache? Settings > history & cache

**Comment by hp8wvvvgnj6asjm7** [comment]
Cleared... still freezing on last played view

**Comment by TobiGr** [comment]
@theScrabi. If there are serious problems with Android 5, we might want to take down the new version from F-Droid.

**Comment by hp8wvvvgnj6asjm7** [comment]
Thanks for caring guys..

**Comment by hp8wvvvgnj6asjm7** [comment]
So clearing all data would resolve it? Really bad. Any fix without deleting everything?

**Comment by TobiGr** [comment]
Can you please disable in history & cache > watch history > position in lists and tell me if the problem still exists?

**Comment by hp8wvvvgnj6asjm7** [comment]
That fixed it for me..

Cleared cached metadata and unchecked position in lists..

So it was because of the resume point feature?

**Comment by TobiGr** [comment]
Yes. We experienced some smaller lags with it on quite new hardware. As you are using Android 5, I assumed that your hardware isn't the newest which could enlarge the problem and cause more/longer lags.

**Comment by ronidee** [comment]
The issue #2503 that I opened was apparently caused by the same bug.
After "position in lists" was disabled  the app is as fluent as before.

**Comment by theScrabi** [comment]
I guess it has to do with database conversion. Maybe we should take a look there.

**Comment by jebdjwnekebd** [comment]
Same for me. Completely freezes and NewPipe isn't responding. I am using android version 9. I disabled as you said, "Positions in lists" and now it works. Just to inform you a bit further. I was using 0.17.0 RC3 completely fine with the "Positions in lists" turned ON.

**Comment by TobiGr** [comment]
> I was using 0.17.0 RC3 completely fine with the "Positions in lists" turned ON.

In this case, we need to take a closer look at https://github.com/TeamNewPipe/NewPipe/commit/a64f5206446edc396b99e23e2c213900b285480a, I guess.

**Comment by Stypox** [comment]
@TobiGr @yausername At [StateObjectsListAdapter::loadStates](https://github.com/TeamNewPipe/NewPipe/blame/a64f5206446edc396b99e23e2c213900b285480a/app/src/main/java/org/schabi/newpipe/info_list/StateObjectsListAdapter.java#L80) a `blockingGet()` is performed on a `Single` that was created using `subscribeOn(Schedulers.io())` (see [HistoryRecordManager::loadStreamStateBatch](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java#L264)).

[Javadocs](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/schedulers/Schedulers.html#io--) for `Schedulers.io()` say that "this scheduler may create an unbounded number of worker threads that can result in system slowdowns". So this might be the problem.

Also see:
- [StateObjectsListAdapter::loadState](https://github.com/TeamNewPipe/NewPipe/blame/a64f5206446edc396b99e23e2c213900b285480a/app/src/main/java/org/schabi/newpipe/info_list/StateObjectsListAdapter.java#L95) + [HistoryRecordManager::loadStreamState](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java#L244)
- [StateObjectsListAdapter::loadStatesForLocal](https://github.com/TeamNewPipe/NewPipe/blame/a64f5206446edc396b99e23e2c213900b285480a/app/src/main/java/org/schabi/newpipe/info_list/StateObjectsListAdapter.java#L110) + [HistoryRecordManager::loadStreamState](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java#L290)

**Comment by Stypox** [comment]
Maybe we should replace `Schedulers.io()` with `Schedulers.computation()`? https://stackoverflow.com/questions/31276164

**Comment by Stypox** [comment]
I am able to reproduce the freeze on my Huawei p9 lite, so I will try the alternatives tomorrow.

**Comment by Stypox** [comment]
The problem was there even before a64f5206446edc396b99e23e2c213900b285480a. That commit just made the app freeze, but in the end it takes the exact same time to load states into lists.
I don't think it is a good idea to load the state of every video at once... Just as (we do)/(Android does) with thumbnails, what about loading them when needed? What I mean is: loading the playback state of a stream only when the mini stream view is visible. I will try to implement this, but I'm not sure I am able to ;-/

**Comment by Stypox** [comment]
@hp8wvvvgnj6asjm7 @ronidee could you please check if this apk works for you? On my end the freeze seems to be disappeared, but I am not sure if it has completely disappeared: it could just have become shorter. Anyway I am now able to load history istantaneously: it took 5-10 seconds before.

Testing apk: 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/3500648/app-debug.zip)

**Comment by theScrabi** [comment]
I did not have the historry issue on thr app you build :)

**Comment by TobiGr** [comment]
I can test this later today

**Comment by ronidee** [comment]
@Stypox I tested your apk and the issue was no longer present.

**Comment by Gymcap** [comment]
@Stypox Maybe I'm referring to a different issue than others here, because I'm still experiencing it in the debug apk.
