### ISSUE TITLE
Allow install on external memory card

### ISSUE THREAD

**Issue by Gitoffthelawn** [TeamNewPipe/NewPipe#251]
Can you set the flag to allow it to be installed on an external memory card?

**Comment by theScrabi** [comment]
Nop, we had that problem so far. Until we re write the whole downloading thing, it will not be possible to use external storage. The build in download manager of android prevents that.

**Comment by Gitoffthelawn** [comment]
Interesting.  So NewPipe is currently using the built-in Android download manager, and anything that uses it cannot be stored on external storage?

**Comment by theScrabi** [comment]
As far as I know yes. It depends on the android version. Newer one locked down the external memory. We already have our own build in download manager, but I deactivated it, because its garbage right now.

**Comment by Gitoffthelawn** [comment]
Thanks for the details.  Perhaps you will be able to allow it to be moved to external storage in the future.  Fortunately, it's still a relatively small app at ~8MB.

**Comment by mauriciocolli** [comment]
@theScrabi he's talking about this flag [`android:installLocation`](https://developer.android.com/guide/topics/manifest/manifest-element.html), to move the app itself to the sdcard.

And we should allow the users to do that.

**Comment by Gitoffthelawn** [comment]
Can what @mauriciocolli proposed by implemented?
