### ISSUE TITLE
database diagram needs to be updated

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#2511]
Now where  we have changed the database we should also change our diagram accordingly:
https://github.com/TeamNewPipe/NewPipe/blob/dev/assets/db.dia

It was good to not change the existing file but creating a new one, something called `post_0.17.0_db.dia` so that we know what the database looked before, and what it looked like after.

**Comment by Michelle616** [comment]
> y

**Comment by mauriciocolli** [comment]
It will be updated as part of #2309.

**Comment by opusforlife2** [comment]
Done, then.
