### ISSUE TITLE
v0.17.0 is really slow to go back from a channel page

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2513]
I grabbed the v0.17.0 apk while it was up. When you are viewing a channel and press back to view your subscriptions, the app seemingly hangs for a second. This bug is not present on v0.16.2.

Steps to reproduce: 

Goto subscriptions, select a channel, then press back. The app will hang a bit both ways, but most notably when going back to subscriptions.

**Comment by Stypox** [comment]
Duplicate of #2507

**Comment by Gymcap** [comment]
This bug is still present as of [#2531](https://github.com/TeamNewPipe/NewPipe/issues/2531). 

To clarify, I am referencing the fact that it takes about a second for the subscriptions activity to show when pressing back from a channel activity. This was near/instant in v0.16.2 and previous.

**Comment by Stypox** [comment]
You are right. I'll take a look at this

**Comment by Stypox** [comment]
I am not able to find the cause of this slowdown. I can't find any relationship between the latest changes in ChannelFragment and the slowdown... the problem probably has to do with other files used by ChannelFragment.
Anyway I noticed that the slowdown happens anytime "back" is pressed in a channel, independently from the previous fragment.

**Comment by Isayso** [comment]
I tested the dev branch yesterday and started a bigger download (and cannot scroll resolution in portrait mode). After I opened the download page and pressed "back", download still running, the app froze. Could leave app with home button. After some minutes I got a Shutdown or wait message from Android. 
No such behavior with 16.x
Hope this helps.

**Comment by TobiGr** [comment]
Could you please try to disable 'Position in lists' in the history and cache settings and tell us whether the problems still exist.

**Comment by Isayso** [comment]
I switched "Position in lists off", no change, App stops when I try to go back from download fragment.

**Comment by opusforlife2** [comment]
@Stypox Is this bug present in 0.17.1? I haven't faced it so far.

**Comment by Stypox** [comment]
@opusforlife2 we should probably ask @Gymcap as I could only reproduce "roughly" (i.e. my phone is probably fast enough to prevent slowdowns)

**Comment by opusforlife2** [comment]
@Stypox Close?

**Comment by Stypox** [comment]
This still happens on really slow devices, I think @opusforlife2

**Comment by opusforlife2** [comment]
@Gymcap @Isayso Is this still an issue in 0.20.0?
