### ISSUE TITLE
Trending videos

### ISSUE THREAD

**Issue by Gitoffthelawn** [TeamNewPipe/NewPipe#252]
I have mixed emotions about it, but is it possible to add a Trending videos tab or button?

**Comment by theScrabi** [comment]
Yup, will come anyway, since we need a front-page one day.

**Comment by Gitoffthelawn** [comment]
Sounds good.  Thanks.

**Comment by digiwizkid** [comment]
+1

**Comment by phly95** [comment]
Well, at least leave the option to turn it off though because I find that stuff distracting and would rather not have trending videos to make me stay on YouTube.

**Comment by Gitoffthelawn** [comment]
@phly95 I think that's an excellent idea.  I wish I could turn them off on Wikipedia's app.

**Comment by theScrabi** [comment]
All right I will do that to ;)

**Comment by theScrabi** [comment]
Will come with the next version.
