### ISSUE TITLE
Duplicate Playlist

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#2520]
When we add a video to Playlist more than once it is appearing on the Playlist as how many times added it. Instead of it show messages that this video has been Already added to Playlist 
![Screenshot_20190814-223533](https://user-images.githubusercontent.com/33452200/63041019-7b2edb00-bee4-11e9-80eb-e234ec0b1681.png)

**Comment by Stypox** [comment]
This is the correct behavior... YouTube allows duplicate videos in playlists, too.
