### ISSUE TITLE
[Meta] Using Milestones

### ISSUE THREAD

**Issue by snappyapple632** [TeamNewPipe/NewPipe#2523]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [N/A] I checked if the issue/feature exists in the latest version.
- [N/A] I did use the [incredible bug report to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I have noted that the team is posting issues to try and raise attention to users to test release candidates of NewPipe. I am not sure if this is the most efficient way of doing so. GitHub has a feature called "Milestones" that would help to not only keep version releases in a dedicated spot on the issue/PR list for all to see (to the right of the search bar) but would also help with organization.

The way it works is that issues (and I believe PRs) can be assigned to a milestone, where progress can be tracked in a streamlined manner. As issues are closed and PRs are merged, the progress bar goes up, until it is completed. This system would help point contributors to the direction that the leader wants to go towards for sequential releases, rather than just raffling away what issues they want to solve.

Many of the larger GitHub projects use milestones in the way I descibed above. It looks like it has been used before in an old version of NewPipe, but I think utilizing this feature would help create a sort of progress indicator and would help remove some additional work on the contributors' end.

**Comment by B0pol** [comment]
See https://github.com/TeamNewPipe/NewPipe/milestones and https://github.com/TeamNewPipe/NewPipeextractor/milestones
