### ISSUE TITLE
Exoplayer : the top bar doesn't disappear

### ISSUE THREAD

**Issue by Paviluf** [TeamNewPipe/NewPipe#253]
Exoplayer work great but something that can be improved is the top bar that doesn't disappear whereas it should.

**Comment by theScrabi** [comment]
Its experimental so far, we need a new UI anyway.

**Comment by Paviluf** [comment]
OK thanks !

**Comment by Smultie** [comment]
Just here to tell I would like to get this fixed as well. Really like the exoplayer's speed, but true full screen is a must.

**Comment by theScrabi** [comment]
Ok nice thanks. Could you try to stick a bit to the original youtube player design. :)

**Comment by Smultie** [comment]
Would love to help out, man. I'm afraid I can't code for sh*t though :(

**Comment by theScrabi** [comment]
Hm thats to bad. But hey you can always learn how to code, and coding for android is always worth it. (Although a small warning! Coding for android sometimes is no fun :/ )

**Comment by Paviluf** [comment]
> we need a new UI anyway.

By the way it's "just" a fullscreen mode that is missing ;)

**Comment by theScrabi** [comment]
Yea for a hacky UI it was just fullscren. But for a proper UI it was much more.

**Comment by theScrabi** [comment]
How ever of course a simple UI would do it for the moment.

**Comment by Paviluf** [comment]
> How ever of course a simple UI would do it for the moment.

That would be great ! When you watch your videos the UI is not important, you don't see it in fullscreen. So a simple way to switch to real fullscreen will be enough for now ;)

**Comment by Paviluf** [comment]
It seems that is fairly easy to make Exoplayer full screen

https://github.com/google/ExoPlayer/issues/520

**Comment by Paviluf** [comment]
@theScrabi do you think you can implement this ?
```
Do that in OnCreate:
this.requestWindowFeature(Window.FEATURE_NO_TITLE); //Remove title bar
this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN); //Remove notification bar
```

**Comment by theScrabi** [comment]
Hm well I could try, but I still dont fully understand how this fullscreen thing works on android. To br hones the current player has only poor fullscreen support :/ I want a propper solution for the new player.

**Comment by Paviluf** [comment]
Did you tried ?

**Comment by Paviluf** [comment]
I guess no :D

**Comment by theScrabi** [comment]
No and I still have the hope that someone else could help me.

**Comment by Wiredframe** [comment]
Although Gracecr added his fix the issue still persists unfortunately.

**Comment by theScrabi** [comment]
Well exoplayer is by far not finished... Its still experimental.

Would love to see someone implement a probber UI.

**Comment by adelumban-sp** [comment]
```
ActionBar actionBar = getSupportActionBar();
if(null != actionBar){
      actionBar.hide();
}
```

**Comment by Paviluf** [comment]
It seem that can be closed now ?

**Comment by mauriciocolli** [comment]
Yes, the ExoPlayer is now the default player, with a new UI.

If you have another problem, you should create another issue.

**Comment by Paviluf** [comment]
Thanks !
