### ISSUE TITLE
Watch time shouldn't be recorded under certain circumstances

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2532]
If the player is closed near enough to the start or end of a video, then watch time should not be recorded.

For example.
If a you have 15 seconds left in a 20 minute video, then watch time should not be recorded.

If you're 15 seconds into a video when you close it, the watch time should also not be recorded.

These are obviously just examples to get the general idea across. You may want to change the length of time or use percentages for shorter videos.

**Comment by Stypox** [comment]
This is already being done: see [the code that checks time](https://github.com/TeamNewPipe/NewPipe/blob/61472a995f76468b1cffe168d5e75de8c2b06224/app/src/main/java/org/schabi/newpipe/database/stream/model/StreamStateEntity.java#L62-L64) and [threshold values](https://github.com/TeamNewPipe/NewPipe/blob/61472a995f76468b1cffe168d5e75de8c2b06224/app/src/main/java/org/schabi/newpipe/database/stream/model/StreamStateEntity.java#L29-L32)
