### ISSUE TITLE
Can't play age restricted videos

### ISSUE THREAD

**Issue by SuperMeepBoy** [TeamNewPipe/NewPipe#2538]
It's been a while now. I thought I saw something around here about this issue but I can't find it anymore and the bug isn't solved yet. I have a lot of videos that won't play and it seems that it is related to age restrictions.

Here is an example of URL that doesn't work (kinda NSFW, no explicit images but the topic of the video is "NSFW") : https://www.youtube.com/watch?v=cDFmn1T6p7k

Thanks for your help sorry if there is already a post about this but couldn't find it. :/

**Comment by aidalgol** [comment]
I noticed this, too, a few weeks ago, but I didn't make the connection with age restrictions.  (I have submitted a crash report separately.)

**Comment by Stypox** [comment]
@SuperMeepBoy which version of the app are you using? On 0.17.x it works

**Comment by SuperMeepBoy** [comment]
@Stypox Interesting. I'm in 0.16.2. I got the app from F-Droid. And even after updating repos I have no notifications of an update in 0.17.x. Is there any reason to that ? :thinking:

**Comment by gkeegan** [comment]
Yes it is normal.

**Comment by SuperMeepBoy** [comment]
@gkeegan Can you confirm me that the only way to get the 0.17.x running on my phone is by building a debug APK myself ? It seems 0.17.x isn't in the releases yet : https://github.com/TeamNewPipe/NewPipe/releases ?

Does someone know when it will be released ? :)

**Comment by gkeegan** [comment]
#2531 has an apk you can download. You will need to uninstall any versions of NewPipe from F-Droid to install it. Make sure you back up the data in the app.

**Comment by SuperMeepBoy** [comment]
Thanks a lot ! Issue closed then. :)

**Comment by Stypox** [comment]
(by the way 0.17.x means 0.17.[any version], that is, every version that starts with 0.17)
