### ISSUE TITLE
Autoplay is not working

### ISSUE THREAD

**Issue by rbernat** [TeamNewPipe/NewPipe#2539]
Since last week autoplay is not working. Next button does not load new video. "Show Next and Similar videos" is checked. I've tried releases 0.16.2 and 0.17.1.

**Comment by TobiGr** [comment]
What's you content country and where are you located?

**Comment by rbernat** [comment]
Croatia

**Comment by opusforlife2** [comment]
@rbernat Please reopen if you still have this issue.
