### ISSUE TITLE
Rename Playlist, Up (or back) Navigation, Background Player controls

### ISSUE THREAD

**Issue by alittlebitofit** [TeamNewPipe/NewPipe#2540]
1) It would be nice to rename any given playlist of your own or the ones you bookmarked.

2) Plus, when I open a video from the playlist and then press up button (not system's back button) to navigate back to the playlist, it takes me to the bookmarks. Although pressing the system's back button takes me back to the playlist. Was this intentional? Because I am used to up button for back navigation.

3) When I play a video in background mode, it used to give me controls such as pausing or playing it back in the notification panel. But now, its only on the lock screen. And once I pause a given song, controls disappear even from the lock screen.

4) There's a word missing in the fourth point on the site where it says: "Your donation cover a majority `of` our costs."

![Screenshot_2019-08-16 NewPipe - a free YouTube client](https://user-images.githubusercontent.com/42311431/63172366-2eb9db80-c05b-11e9-9c64-d41c1814e802.png)

I couldn't find a support mail so I posted the issue here.

**Comment by alittlebitofit** [comment]
Thanks.
But haven't I opened the issue on the correct link?

**Comment by Stypox** [comment]
3. Closing in favour of #1660
4. This has been fixed, the website just needs to be updated
