### ISSUE TITLE
Repack OPUS to OGG container

### ISSUE THREAD

**Issue by DocSniper** [TeamNewPipe/NewPipe#2542]
I noticed that the files from the OPUS downloads are encapsulated in a WEBM container (WEBM is a video+audio container). That's maybe OK for VLC, but it's bad for other (audio only) players.
As audio only, OPUS should be encapsulated in an OGG container (just like VORBIS), but unlike OGG-Vorbis that uses the OGG extension, OGG-OPUS should use the extension OPUS, see below.

I also noticed that the OPUS formats 249, 250 and 251 have a WEBM container as default.
So we need to repack the OPUS stream (without transcoding it) from the WEBM to an OGG container after the download is done. 
```
# youtube-dl output with -F or --list-formats

format code  extension  resolution note
249          webm       audio only DASH audio   50k , opus @ 50k, ?.??MiB
250          webm       audio only DASH audio   63k , opus @ 70k, ?.??MiB
251          webm       audio only DASH audio  123k , opus @160k, ?.??MiB
```
From: https://tools.ietf.org/html/rfc7845#section-9
```
9.  Content Type

   An "Ogg Opus file" consists of one or more sequentially multiplexed
   segments, each containing exactly one Ogg Opus stream.  The
   RECOMMENDED mime-type for Ogg Opus files is "audio/ogg".

   If more specificity is desired, one MAY indicate the presence of Opus
   streams using the codecs parameter defined in [RFC6381] and
   [RFC5334], e.g.,

                            audio/ogg; codecs=opus

   for an Ogg Opus file.

   The RECOMMENDED filename extension for Ogg Opus files is '.opus'.
```

**Comment by Stypox** [comment]
(see #1372 for previous discussion)

**Comment by opusforlife2** [comment]
@Stypox @kapodamy This might be the source of the problem I described in #2340 as well. If implementing this _still_ doesn't fix that, then it might need a fix similar to the one required by #2152 implemented in #2149 as well.

**Comment by kapodamy** [comment]
@opusforlife2 I tried implement this in the past but I have not found any documentation/specification about the OGG format, how the audio data is stored, etc.
The only documentation I found only shows how the header is formed. I also can't find utilities likeI wanted to implement this in the past but I have not found the documentation of the ogg format, as the audio data is stored. The only documentation I found only shows how the header is formed. I also can't find utilities like BMFF Viewer or MKV Toolnix that allow you to debug the file or MKV Toolnix that allow debug/inspect the file

**Comment by opusforlife2** [comment]
@kapodamy Are the sources at https://xiph.org/ogg/doc/ incomplete or irrelevant?

**Comment by kapodamy** [comment]
1_ for me is imcoplete
2_ thanks, thats was looking for

**Comment by opusforlife2** [comment]
@kapodamy Do you specifically need more documentation on the Ogg container or on the Opus codec as well?

**Comment by kapodamy** [comment]
nope i basically used an hex editor and the oggz-dump for this

**Comment by Pentaphon** [comment]
We should not use .ogg. We should remux Opus audio downloads to the .opus container for audio player compatibility and to not confuse people by making them think it is a Vorbis file when it is actually an Opus.

**Comment by DocSniper** [comment]
@Pentaphon the title of this thread is absolutely correct.

You seem to mess up container format and audio codes a bit ?

Brief overview of the relationship between the container format OGG and the audio codecs/formats Vorbis and Opus and how they relate to each other:
- https://en.wikipedia.org/wiki/Ogg#Ogg_codecs
- https://en.wikipedia.org/wiki/Opus_(audio_format)#Containers

> Opus packets are not self-delimiting, but are designed to be used inside a container of some sort which supplies the decoder with each packet's length. Opus was originally specified for encapsulation in Ogg containers, specified as _audio/ogg; codecs=opus_, and for Ogg Opus files the _.opus_ filename extension is recommended.

**Comment by Pentaphon** [comment]
The .opus filename extension, I mean.
