### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by yohellonewpipe** [TeamNewPipe/NewPipe#2543]
So I used 0.17.0 and just suddenly I get Network error and the app is actling weird. I cannot access my bookmarks, the inside of them. But sometimes I can but then Newpipe just crashes after looking around. I can search and use the Internet in every other app except Newpipe. Tried 0.17.1 too, nothing. I tried a VPN, nothing. I tried my phone, nothing. Is this an issue for more than just me? I also restarted my WiFi and rebooted my phone. Nothing

**Comment by gkeegan** [comment]
Could you please post the crashlog after putting it through the markdown converter? 

Also, by trying your phone, do you mean this happens on multiple devices?

**Comment by Stypox** [comment]
Update to 0.18.2 and if the problem still persists create an new issue
