### ISSUE TITLE
[FR] option to clear playback positions history only.

### ISSUE THREAD

**Issue by unknowndelicateboy** [TeamNewPipe/NewPipe#2544]
note: in version 0.17.1 you have to clear watch history to clear playback positions history. 
there's a bug in 0.17.0 caused by playback positions when i watch a video without saving it to history, playback positions history is still on so I can't delete the playback positions i have to delete watch history to delete playback positions history.

**Comment by snappyapple632** [comment]
I'm in full agreement, especially since they seem to be causing a few problems at the moment.

**Comment by TobiGr** [comment]
I can add a new entry to the the history settings tonight. 
In case someone else wants to do it, here is is the method to clear the stream states:
https://github.com/TeamNewPipe/NewPipe/blob/670a95a01dd65217f9096a1f1fd13fb07d937ea1/app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java#L113
