### ISSUE TITLE
Downloading stalling forever with message "Nachbearbeitung"

### ISSUE THREAD

**Issue by ksaerdna** [TeamNewPipe/NewPipe#2546]
For example try to download "https://www.youtube.com/watch?v=UW7lB7p0Eow". Choose "Video". Select "480p". Downloading will work fine until "Nachbearbeitung" (in English: "post processing"). This message will stay forever, in fact I had to use the developer settings to stop the NewPipe's "DownloadManagerService". For whatever reason the 360p version works fine, i.e. can be downloaded.

**Comment by Stypox** [comment]
Which version of NewPipe are you on? 0.17 contains #2149 that fixes many of these downloading problems

**Comment by ksaerdna** [comment]
Using the latest version from F-Droid which is 0.16.2. Also looked up and down, but could not find a newer apk.

**Comment by Stypox** [comment]
You can fin one here, it has yet to be published on F-Droid (see the project README): #2531

**Comment by ksaerdna** [comment]
I could not find a suitable link in README.md, but, however, your link worked. I could install the apk (after deinstalling the existing one, most probably due to signature mismatch), and the malfunction seems to be repaired now. Thanks! Hopefully a repaired version will find its way to the F-Droid store soon, as maybe other users might suffer from the same problems.

**Comment by Stypox** [comment]
See this https://github.com/TeamNewPipe/NewPipe#updates
:-)
