### ISSUE TITLE
download can not auto start

### ISSUE THREAD

**Issue by joshatt** [TeamNewPipe/NewPipe#2553]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Sorry, what is JSON bug report?

I remember this is not an issue years ago, but recent versions seem to be: after I add some download mission(audio), it will not start automatically, I have to find it and start it manually, and have to do it for each one of them.
Anybody else experiencing this?

**Comment by kapodamy** [comment]
there is a option in download settings try disable it, is called "Pause on metered networks"

**Comment by joshatt** [comment]
> there is a option in download settings try disable it, is called "Pause on metered networks"

Updated from v16.1 to v17.1 then I got this option, works like charm. Thanks a lot!

**Comment by Stypox** [comment]
Close the issue if it is solved 😅
