### ISSUE TITLE
Import from earlier version not working :(

### ISSUE THREAD

**Issue by gabriellluz** [TeamNewPipe/NewPipe#2555]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I'm trying to import a backup I've made from version 0.16.2 but it's not working. :(
I really need those subscriptions. I always make a backup before updating, but this time it won't restore my backups.

Can you guys help me?

**Comment by Stypox** [comment]
Does it give you some error?

**Comment by gabriellluz** [comment]
Nothing happens. No message.

**Comment by Stypox** [comment]
You may need to provide the file so that we can investigate. This is probably related to https://github.com/TeamNewPipe/NewPipe/issues/2483#issuecomment-517544740 @theScrabi
