### ISSUE TITLE
Backgroud player unable to load content of a channel you subscribed to

### ISSUE THREAD

**Issue by jojoxl01** [TeamNewPipe/NewPipe#2559]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

0.17.1 background audio playback, unable to load all the content of a channel that you subscribe to. (0.1.62 can) The video in the background auto play queue is not the content of the subscription channel, but it is randomly added randomly, very bad! Hope to improve! Thank you!

**Comment by Stypox** [comment]
<img src="https://user-images.githubusercontent.com/36421898/63747079-9287a400-c8a6-11e9-87c9-74466fa6177b.gif" width="200">

**Comment by jojoxl01** [comment]
Thank you for your explanation! From the video, you found that you clicked "Background Play" from below a certain channel, so that the background video is played from the first video, so I found that all the videos of a channel can be added in the background play column. However, if you click on the background play from any video in a channel, there is no video of the channel in the background playlist. Only the selected one, and after the video is finished in the background, any video will be added randomly and irregularly. . This is not the case in the 0.6.82 version. Please check this question! Thank you for your contribution!

**Comment by jojoxl01** [comment]
The 0.1.62 version will not have this problem. My version number is wrong.😂

**Comment by Stypox** [comment]
Closing in favour of #2510
