### ISSUE TITLE
keep playback position when switching between foreground and background

### ISSUE THREAD

**Issue by Sohalt** [TeamNewPipe/NewPipe#256]
When switching between foreground and background (audio only)  playback the position is lost. I'd like to be able to switch between both modes mostly seamlessly.

**Comment by theScrabi** [comment]
Yes I also like that idea. When we move to exoplayer smooth switching between background, and video playback would be possible, with even having to restart the stream.

So far exoplayer is not yet completely functional within NewPipe.

**Comment by mauriciocolli** [comment]
Fixed recently.

**Comment by ildar** [comment]
Does it really work now?
