### ISSUE TITLE
App crashing on downloading 1080 videos simultaneously. 

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#2560]
Hello :)

I am downloading 2 documentaries of 1080 quality each one simultaneously.

The app is crashing like no tommorow

![Example Image](https://i.imgur.com/rBXzzjh.jpg)

This screen has been freezed since two minutes now.

Let me ask you something:

Are you using the same Thread for downloading content. Like is the application multithreaded in the first place.

Please let me know if you need help on designing it multithreaded if the issue has to do with that.

**Comment by Stypox** [comment]
The application is multithreaded... Android itself throws exceptions when doing networking on the main thread and the whole app would be unusable if not multithreaded.

What you are experiencing is a bug. Can you please provide more information about app version, videos creating problems and their format?

**Comment by Serkan-devel** [comment]
Doesn't it give you an option to submit an error report after a while?

**Comment by Isayso** [comment]
I think this is the same or connected to #2513?  UI just freeze and after a while Android 9 shows an App not responding message.

**Comment by goxr3plus** [comment]
@Serkan-devel  nope :(

**Comment by goxr3plus** [comment]
It happened only using wifi network in the airport , in 4g i have not seen the same issue.

**Comment by kapodamy** [comment]
android version?

**Comment by kapodamy** [comment]
Also in android 9 (Pie) DocumentFile.[exists](https://developer.android.com/reference/android/support/v4/provider/DocumentFile.html#isFile())() and DocumentFile.[isFile](https://developer.android.com/reference/android/support/v4/provider/DocumentFile.html#exists())() methods are really slow
