### ISSUE TITLE
Bookmarks backup support

### ISSUE THREAD

**Issue by gabriellluz** [TeamNewPipe/NewPipe#2563]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

So I was trying to update NewPipe 0.16.2 to 0.17. I had to uninstall NewPipe because updating wasn't working. Ok. So I've installed 0.17 and my bookmarks were gone. We need an option to backup bookmarks/playlists. I had more than 50. That would be great. :)

**Comment by Stypox** [comment]
The option to backup the whole database already esists, and as far as I know works with bookmarks and playlist. `Settings -> Content -> Import/Export database`
