### ISSUE TITLE
[Feature Request] Add ' clear search history ' option

### ISSUE THREAD

**Issue by Nandan9** [TeamNewPipe/NewPipe#2564]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Nandan9** [comment]
...

**Comment by Stypox** [comment]
You can delete single entries by long-pressing on them. As a workaround for deleting all entries you can probably enable and disable the search history (but I did not test this).
I agree an option would be useful.

**Comment by sherlockbeard** [comment]
there is a clear search history in history and cache. It is already present

**Comment by sherlockbeard** [comment]
@Stypox

**Comment by Stypox** [comment]
Oh you are right ;-)
I had even checked...
