### ISSUE TITLE
[Request] Resume Playlist

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2566]
When you click on a playlist, there is a play all option. This starts the playlist from the beginning, playing through it chronologically. If you leave in the middle of a playlist, you'll have to start the playlist over from the beginning and skip to the video you left at in order to continue the playlist naturally.

There should be a way for the app to remember which video you left off in the playlist, then return you to that point, continuing the playlist.

**Comment by opusforlife2** [comment]
Now that we have resume playback and position indicators, is this still an issue?
