### ISSUE TITLE
[Request] Add a visible watched flag to videos found in the history view

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2567]
Add a 'watched' flag or banner to videos found in the history view that have reached the 'ending threshold'.

'Ending threshold' is referring to [this code](https://github.com/TeamNewPipe/NewPipe/blob/61472a995f76468b1cffe168d5e75de8c2b06224/app/src/main/java/org/schabi/newpipe/database/stream/model/StreamStateEntity.java#L29-L32) used to stop recording watch time at the end of a video.

**Comment by gabriellluz** [comment]
I second that :) I was trying to watch all the videos from a channel but then I realized it's impossible to track watched video even with the official YouTube app.

**Comment by gabriellluz** [comment]
> Add a 'watched' flag or banner to videos found in the history view that have reached the 'ending threshold'.
> 
> 'Ending threshold' is referring to [this code](https://github.com/TeamNewPipe/NewPipe/blob/61472a995f76468b1cffe168d5e75de8c2b06224/app/src/main/java/org/schabi/newpipe/database/stream/model/StreamStateEntity.java#L29-L32) used to stop recording watch time at the end of a video.

I guess not only on the history view, but especially in the channel page because we don't usually go to the history view to see videos with the watched flag. Videos in the history view are already "watched". I love your idea. We need that. It would allow me to watch entire channels without having to take a note on a paper (yes, many ppl do that lol) or something like that.

**Comment by Gymcap** [comment]
> I guess not only on the history view, but especially in the channel page

Of course, this wording was only used to insure that the watched tags are 1:1 with the history view. I.e. If you removed a video from the history, it loses its watched tag. The video links would of course remained tagged in all other views of the app.

**Comment by nikhilCad** [comment]
This feature will be helful in watching long playlists too. I am watching dragon ball z abriged from playlist, and I have currently a hard time finding the last videoI watched(so that I could watch the next video).

A little tickmark at the corner(like VLC for mobile does it) will be great.

**Comment by opusforlife2** [comment]
Now that you have position indicators in lists, you can easily see which videos are pending and which are finished.

**Comment by RickyM7** [comment]
@opusforlife2 How can I see this?  Is that the red bar disappears when the video is watched in full and thus it is difficult to see where I am in the playlist, ideally the red bar should continue after the video is completely seen, or maybe a small "watched" message appears, or maybe  a small icon of an eye on the cover of the video to show that the video has been completely watched.

**Comment by opusforlife2** [comment]
@RickyM7 Follow #4480.
