### ISSUE TITLE
[Feature Request] Play videos in NewPipe that youtube-dl can fetch

### ISSUE THREAD

**Issue by fnadde42** [TeamNewPipe/NewPipe#2568]
NewPipe is really an awesome app and I could go on and on how much I love it. However, there are a lot more video services than YouTube that I would like to use through NewPipe. Developing ways to fetch the video from these services would be a pain but luckily there already is a way to do that called [youtube-dl](http://youtube-dl.org) (which I'm sure many have heard of).

What I envision is that a "service" is added in the list where "YouTube, SoundCloud..." is called either "youtube-dl" or "Generic". A popup informs user that using the generic video fetcher will only give the user the video and features related to video (like play, pause, forward, backwards, subtitles and downloading audio or video) and that the "service" is based on external software with no guarantees that it will work (and the usual disclaimers about who to turn to when things go south). 

Instead of having a search bar there is a place to paste a URL. If a user copies text that is a URL, the context menu could maybe show a "view in newpipe". Or if a user is on a web page with a video, the user could share the URL to NewPipe.

Youtube-dl is GNU GPL compatible and supported by a solid community that is hell bent on being able to play and download any video on the web and combined with the smooth interface of NewPipe... nothing would be able to stop such a force.

**Comment by Stypox** [comment]
The problem with youtube-dl is that it is made in Python, and is thus not embeddable in an android app. Even though Python interpreters for Android exist, they are not lightweight and would make the app heavier and slower.

**Comment by fnadde42** [comment]
I figured you had already discussed this but was curious as to why it hadn't happened. Thanks for the explanation!

**Comment by mihawk90** [comment]
I've also always been wondering why you did your own downloader, kinda makes sense now...

Anyway, the [Python Wiki](https://wiki.python.org/moin/Android) states that it would be possible to trans-compile Python into java using [VOC](https://github.com/beeware/voc). I'm not into Android development, so probably a long shot, but might this be an option?

**Comment by nyanpasu64** [comment]
You can use Nuitka to compile youtube-dl into a binary or shared object (35MB on win64) that depends on the Python shared object (3.6MB on win64) but not a filesystem package tree. It reduces load time slightly, but launching the .exe from a clean cache (no previous runs) takes 3 seconds on a SSD. But it's still quite bloated, and I don't know if Nuitka supports targeting ARM/Android shared libraries. I think this is a very unusual architecture and may not necessarily work (or well).

**Comment by Stypox** [comment]
Closing this since this is not going to be done, the way forward is with NewPipeExtractor and probably extensions

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/2415#issuecomment-683421792
