### ISSUE TITLE
Questions about the background player.

### ISSUE THREAD

**Issue by jojoxl01** [TeamNewPipe/NewPipe#2575]
<img src="https://user-images.githubusercontent.com/36421898/63747079-9287a400-c8a6-11e9-87c9-74466fa6177b.gif" width="150">
Doesn't this suit your needs?

_Originally posted by @Stypox in https://github.com/TeamNewPipe/NewPipe/issues/2559#issuecomment-525162909_
         Thank you for your explanation! From the video, you found that you clicked "Background Play" from below a certain channel, so that the background video is played from the first video, so I found that all the videos of a channel can be added in the background play column. However, if you click on the background play from any video in a channel, there is no video of the channel in the background playlist. Only the selected one, and after the video is finished in the background, any video will be added randomly and irregularly. . This is not the case in the 0.1.62 version. Please check this question! Thank you for your contribution!

**Comment by opusforlife2** [comment]
I'm pretty sure this is the case in 0.16.2 and below as well. Any time you load a video from anywhere, the video details page shows you the current video and shows a list of videos to watch next. If your queue is currently empty, the first item in this list is the one that auto plays next. If you play this second video, the _third_ video that would auto play is the first item from the _second video's_ list of videos to watch next.

I'm guessing that the videos that auto played for you from the same channel just happened to be the next recommended videos to watch. This can happen on topic specific channels like 3Blue1Brown, which I have just tested.

**Comment by jojoxl01** [comment]
In version 0.1.62, no matter which video in the subscription channel clicks to play in the background, all videos can be loaded in the background playlist! All videos! All channels are like this! I hope that the new version will not give up this feature! Thank you! I am using 0.1.62 now.

**Comment by jojoxl01** [comment]
> 我很确定这是0.16.2及以下的情况。无论何时从任何地方加载视频，视频详细信息页面都会显示当前视频，并显示下一个要观看的视频列表。如果您的队列当前为空，则此列表中的第一个项目是下一个自动播放的项目。如果您播放第二个视频，则自动播放的_第三个_视频是_第二个视频的_下一个_视频_列表中的第一个视频。
> 
> 我猜测从同一频道为你播放的视频恰好是下一个推荐观看的视频。这可能发生在我刚刚测试过的3Blue1Brown等特定主题频道上。
In version 0.1.62, no matter which video in the subscription channel clicks to play in the background, all videos can be loaded in the background playlist! All videos! All channels are like this! I hope that the new version will not give up this feature! Thank you! I am using 0.1.62 now.

**Comment by BartFarley** [comment]
jojoxl01 my friend,
Your issue will most likely not be considered. I commented, politely at first, that the long-press menu is now a mere shadow of it's former self. I was told that the menu can't be reverted because there's big plans for a way more complicated menu. It's got three screens, and more icons! Takes more clicks too! It was perfect in 0.16.2. Other folks thought so too.
See: #2510, #2559, #2575 
If I keep writing at this moment, I might revert back to my sardonic style. But I will not. Seems some contributors found my prose a bit "rude". Made them cry. For this I apologize.
Still rockin' 0.16.2

**Comment by jojoxl01** [comment]
I looked at the feedback from #2510, the "Play from here" menu, maybe there is more than one for this demand, and it may be because it is too crowded. But I also expect future menus to do better. Maybe we use different languages, but this does not affect our communication! Anyway, thank you for your contribution!!!

**Comment by jojoxl01** [comment]
I looked at the feedback from #2510, the "Play from here" menu, maybe there is more than one for this demand, and it may be because it is too crowded. But I also expect future menus to do better. Maybe we use different languages, but this does not affect our communication! Anyway, thank you for your contribution!

**Comment by opusforlife2** [comment]
@jojoxl01 I tried 0.16.2 and I see what you mean. A slightly inconvenient workaround is to use one of the three buttons under the channel name and then navigate to the video/audio of interest in the queue. Then you'll be in the same position as if you had pressed "Start playing from here". I don't think you should let this stop you from using the latest version.

**Comment by jojoxl01** [comment]
> @ jojoxl01我试过0.16.2，我明白你的意思了。稍微不方便的解决方法是使用频道名称下的三个按钮之一，然后向下滚动到队列中感兴趣的视频/音频。然后你将处于相同的位置，好像你按下了“从这里开始玩”。我认为你不应该让这阻止你使用最新版本。


Thank you for your understanding!

**Comment by Stypox** [comment]
Closing in favour of #2510
