### ISSUE TITLE
NewPipe random lags on 4G Mobile Network

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#2577]
This strange issue happens even on the latest version 0.17.1

I have Huawei p20 lite and using 4G Mobile data . I open New Pipe , play a song in the background ... i close the phone screen for 1 minute the audio continues playing in the background.

Reopening the phone screen and opening New Pipe , trying to navigate and search for something new on the search bar or play another audio from the history.

It simply hangs loading for ever like i don't have internet . 

How i am solving : Everytime i close and reopen 4G mobile data ( toggle) and the NewPipe loads again. But why that strange behaviour happens ?

**Comment by opusforlife2** [comment]
@goxr3plus Still happening?

**Comment by goxr3plus** [comment]
Now i have changed to Samswng phone so we can close this issue.  :)
