### ISSUE TITLE
Newpipe start lagging when using YouTube background playback

### ISSUE THREAD

**Issue by thegodofplay** [TeamNewPipe/NewPipe#2579]
Newpipe lags when using background playback for YouTube streams. 
SoundCloud and mediaCCC works fine.
Lagging only limited to newpipe app.
This issue was also exists in previous versions of newpipe.
Issue #2577 confirm this.

Is someone else observed it?

**Comment by goxr3plus** [comment]
It exists on the latest 17.1 version too. I am using Hawaii p20 lite :). I have to close and reopen 4g data to unlag.

**Comment by Stypox** [comment]
Closing in favour of #2577
