### ISSUE TITLE
Duplicated videos in search

### ISSUE THREAD

**Issue by PhoenixDiscord** [TeamNewPipe/NewPipe#2580]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
So I was just searching for things on YouTube and sometimes videos appear two times in the search results.

How to reproduce: Search something, keep scrolling down

Screenshot:
![Screenshot_20190830_215901_org schabi newpipe](https://user-images.githubusercontent.com/37777903/64048466-1628e580-cb72-11e9-9190-a0512e2658c0.jpg)

**Comment by Stypox** [comment]
I can't reproduce
