### ISSUE TITLE
Cannon open video in 1080p

### ISSUE THREAD

**Issue by rissilver** [TeamNewPipe/NewPipe#2584]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I cannon open video in 1080p, sometime video open after 1-2 minute waiting. I have 40mbps internet speed that shouldn't create a problem. In 720p video start instantly. 
Phone: Xiaomi redmi note 4X
Android: 8.1.0 lineageos without gapps
Version : 0.17.1

**Comment by Stypox** [comment]
Related: #2525

**Comment by Stypox** [comment]
Duplicate of #2415
