### ISSUE TITLE
In the import and export, you can't import the list of favorites in youtube, for example, the default playlist: watch later, and the list created by the user himself. I hope to consider this feature thank you!

### ISSUE THREAD

**Issue by jojoxl01** [TeamNewPipe/NewPipe#2585]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
This cannot be implemented since we do not allow Google login. So unless YouTube provides a way to export playlist, this cannot be implemented.

**Comment by dg7op** [comment]
YouTube does provide a way to export favorites and watch later playlists as files! Please implement an import feature!
