### ISSUE TITLE
Wrong colors in channel name in background player

### ISSUE THREAD

**Issue by xxkfqz** [TeamNewPipe/NewPipe#2586]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
---

![Screenshot_2019-08-31-22-36-38-518_org schabi newpipe_1](https://user-images.githubusercontent.com/52203435/64067376-00cebc80-cc41-11e9-9dc3-fc7eb870a656.png)

![Screenshot_2019-08-31-22-46-03-919_org schabi newpipe_1](https://user-images.githubusercontent.com/52203435/64067401-6cb12500-cc41-11e9-85f0-b708526e0c23.png)

![Screenshot_2019-08-31-22-45-42-566_org schabi newpipe_1](https://user-images.githubusercontent.com/52203435/64067422-ac780c80-cc41-11e9-9821-d0ea30fc94c3.png)

**Comment by Nico-late** [comment]
I can't seem to reproduce your isssue. In dark and black appearance, the channel name is in white on my device.
![Screenshot_1574765035](https://user-images.githubusercontent.com/56306738/69622885-1dad3d00-1042-11ea-90b7-792b2b6c3212.png)

 Can you please describe how you got these screenshots ?

**Comment by xxkfqz** [comment]
> Can you please describe how you got these screenshots ?

Just now noticed that this bug reproducible on MIUI 9.3 but not on AOSP. I think it's only MIUI bug
