### ISSUE TITLE
The number of subscribers of a youtube channel is not shown below the video

### ISSUE THREAD

**Issue by pizzaHar** [TeamNewPipe/NewPipe#2587]
1
When a video clicks in the search. Then the main page comes and sees the name of the youtube channel below the video.

But unfortunately does not show how many subscribers the youtube channel has. only if you type on the youtube channel.

Here an example:
https://github.com/TeamNewPipe/NewPipe/blob/dev/fastlane/metadata/android/en-US/images/phoneScreenshots/shot_06.png

**Comment by Wilker-a** [comment]
title could be **"YouTube viewer to show subscriber count in video pages"**, if what you want is a follower count near the usernames like we usually see in the official page.

someone pointed out in the Matrix channel that the grammar caused some confusion. the screenshot helped though.

**Comment by Wilker-a** [comment]
title could be **"YouTube viewer to show subscriber count in video pages"**, if what you want is a follower count near the usernames like we usually see in the official page.

someone pointed out in the Matrix channel that the grammar caused some confusion. the screenshot helped though.
