### ISSUE TITLE
Does not correctly come back after forcibly stop 

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#2593]
I've  started using a task manager app, which stops background applications after a period of time.
NewPipe does not correctly reacts on hw BACK button after it had been stoped while watching video. Instead of hiding the window of NewPipe with BACK button it just blinks for the first time of pressing the button.

**Comment by teod0r** [comment]
1. in a third app click on link with yt video -> NewPipe opens
2. start play the video (external player)
3. watch for some time to make the task manager to stop background NewPipe
4. stop the video by pressing BACK
5. try to close the NewPipe window by pressing BACK.
will work only with second pressing

**Comment by Stypox** [comment]
Could you send a video?

**Comment by teod0r** [comment]
making a video and uploading it would be problematic for me.
also this effect does not always happen

**Comment by teod0r** [comment]
this thing happens without a task manager stopping NewPipe!!!
I open link, start the video, close video player, go to current channel, press BACK, then press BACK to exit -- it blinks instead of exit!
can't send you link for the video because your program does not support copying of links and program from which I open the link does not support that too

**Comment by teod0r** [comment]
https://www.youtube.com/watch?v=mevbN3Bz08U
go to the channel and then twise press BACK

**Comment by teod0r** [comment]
Stopping the task manager did not actually work. I removed NewPipe from the task manager auto-end list and the problem gone.

**Comment by gkeegan** [comment]
>I open link, start the video, close video player, go to current channel, press BACK, then press BACK to exit -- it blinks instead of exit!

I can confirm this behavior without any task managing apps installed.

**Comment by opusforlife2** [comment]
@gkeegan Can you check if this happens in the unified player? The STR aren't exactly clear to me.

**Comment by gkeegan** [comment]
@opusforlife2 I can't reproduce on 0.19.8 anymore (without unified player).

**Comment by opusforlife2** [comment]
Thanks!
