### ISSUE TITLE
[feature request] adding Bitchute

### ISSUE THREAD

**Issue by ramsin31** [TeamNewPipe/NewPipe#2595]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Can you please add Bitchute as an option? Their platform is terrible and newpipe is amazing. :)

**Comment by Stypox** [comment]
Duplicate of #664

**Comment by balibebas** [comment]
Given mods are locking issues and no longer open to discussion on this matter it's time for a BraveNewPipe. Until then we always have Telegram which doesn't attempt to become an ethics police.
