### ISSUE TITLE
feature requestt

### ISSUE THREAD

**Issue by drji3m** [TeamNewPipe/NewPipe#2596]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

not sure how to do this but i would like to make a feature request.
One real problem i have with ytube is the inability to blacklist (personal) specific videos so they dont keep appearing in a search. Especially annoying are pantomime diy videos which are generally useless and have obnoxious music. Also block search hit for videos ive put on a playlist.

Seems doable without a lot of code. Kinda like a negative playlist.

this wuld go a long way to cleaning up youtube from pure vanity videos.

**Comment by TobiGr** [comment]
This is related to and could be implemented along with https://github.com/TeamNewPipe/NewPipe/issues/1815. The idea of having a blacklist for videos is a good, especially when you listen to music. I'll close this ticket to keep the discussion bundled in the issue mentioned above.
