### ISSUE TITLE
Disabling brightness and volume gestures

### ISSUE THREAD

**Issue by dmoa** [TeamNewPipe/NewPipe#2597]
Really sorry if this is the incorrect place to ask this but:
Is there a way to disable brightness and volume gestures? 
With my android phone and it's gestures, if I check notifications while full screen in a landscape video, it may cause my to mute my video by accident. The only solution I've thought of is to simply disable those gestures, but I couldn't find an option in settings.

Any help would be appreciated!

**Comment by gkeegan** [comment]
They can be disabled!

Settings>video and audio>volume/brightness gesture control toggles.

**Comment by dmoa** [comment]
thank you!
