### ISSUE TITLE
When loading a URL with the timestamp specified, the video loads as paused

### ISSUE THREAD

**Issue by tgp1994** [TeamNewPipe/NewPipe#260]
When I open a link from reddit such as this one: https://www.youtube.com/watch?v=Khyt3p5Cut0&t=28, NP will load the video to a black screen with it paused. Normally, when the timestamp isn't specified, the video begins playing automatically as I would expect. I'm not sure if this is expected behavior, although I would really like it if it was consistent.

**Comment by tgp1994** [comment]
Just updating this ticket as the issue still stands in NP version v.0.8.0.

**Comment by satiricon** [comment]
@tgp1994 It's weird because it explicitly programed like that in line 145 of PlayVideoActivity. @theScrabi Did you made it like that for a reason?

**Comment by tgp1994** [comment]
@satiricon Not to speak for @theScrabi , but I wonder if he meant to do a check for the "Autoplay when called from another app" option, since I have it checked even though the issue persists.

**Comment by theScrabi** [comment]
I didn't implemement that timestamp thingi, and to be honest I've never used it either. I'd have to read myself into the code bevore I could tell you whats going on.
