### ISSUE TITLE
view/play the "Watch Later"

### ISSUE THREAD

**Issue by chichicuervo** [TeamNewPipe/NewPipe#2601]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I use the "Watch Later" list extensively.. every day actually.

I've gone through the app for hours and cannot find a way to access/view/play that list... Also I find it extremely odd it's barely mentioned in this list of issues.

Please add this feature.

**Comment by Stypox** [comment]
You can just create a playlist called "Watch Later" and add videos to it.
If you want to sync it with your "Watch Later" on youtube, this can't be done since NewPipe will never provide a Google login.

**Comment by Gymcap** [comment]
I do what @Stypox suggests, though a more robust feature to mark watched videos off the playlist might be an option once threshold and watched tags are sorted.

**Comment by chichicuervo** [comment]
okay so you don't support the feature b/c you don't actually connect as an authenticated user?

**Comment by Stypox** [comment]
@chichicuervo yes, that's why
