### ISSUE TITLE
The next video cannot play after changing the quality of previous video

### ISSUE THREAD

**Issue by quoctrungdhqn** [TeamNewPipe/NewPipe#2603]
Test case:
- Open a video in full-screen mode
- Change the quality of this video (from current quality to other quality, ex: 720p -> 360p)
- Click another video, it cannot play.
Hope you guys can fix this bug as soon as possible. Thank you, NewPipe team.

**Comment by quoctrungdhqn** [comment]
Does anyone figure out this bug?

**Comment by Stypox** [comment]
I can't reproduce... could you send a video or a screenshot of all of the steps, please?

**Comment by quoctrungdhqn** [comment]
Hi @Stypox 
- https://drive.google.com/file/d/10X70ticzPAKIi70P--cWgz-EdgdbmGZW/view?usp=sharing
- https://drive.google.com/file/d/10Tq9idH55S6sMmqeWScf3isbCRPqcCR8/view?usp=sharing
Please check the videos.

The next video did not play (or wait a long time can be played) after changing the video quality of the previous video.

**Comment by Stypox** [comment]
OK, now I can reproduce

**Comment by opusforlife2** [comment]
@Stypox So what was the issue?

**Comment by Stypox** [comment]
I have no idea ;-)
The logic changed in 0.20.0, so I'm closing this. Reopen if it can be reproduced again.
Also @quoctrungdhqn could you provide two direct urls to videos? Those Gdocs urls do not work anymore
