### ISSUE TITLE
Options to disable queueing on new downloads

### ISSUE THREAD

**Issue by pbajno** [TeamNewPipe/NewPipe#2605]
Hi. My new downloads always queue. Actually I would like them to be downloaded automatically. I download tons of stuff on my tablet and phone, but it's very exhausting when I always need to click in the downloads panel on the setting menu for each download, and click start.

Starting should be automated when I click download choosing video or audio format.

Please fix it :(

**Comment by gkeegan** [comment]
What version of NewPipe are you on?

It should be working so that once the first download finishes that the next one will start automatically.

**Comment by kapodamy** [comment]
You can disable the queueing under download settings
