### ISSUE TITLE
rss youtube adresse error

### ISSUE THREAD

**Issue by mouarfff** [TeamNewPipe/NewPipe#2607]
When i use the rss button to have rss link, there is on slash / between xml and ? : 
https://www.youtube.com/feeds/videos.xml/?channel_id=
instead : 
https://www.youtube.com/feeds/videos.xml?channel_id=

**Comment by Stypox** [comment]
Could you provide the url of a channel on which this occours? I can't reproduce, on my end rss links are correct (without the slash /)

**Comment by mouarfff** [comment]
i had this with the previous version (fully buggued :) ), now i can't reproduce it too
