### ISSUE TITLE
Feature: New video Notifications

### ISSUE THREAD

**Issue by ramsin31** [TeamNewPipe/NewPipe#2608]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Could you please add a feature that send a push notification when a new video is available from your subscribers?

**Comment by Stypox** [comment]
Duplicate, will be implemented in #2335
