### ISSUE TITLE
Error (not crash) if search results would contain an official VEVO channel

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#2612]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I confirmed this by comparing results between Newpipe and Invidious. When I say "official" VEVO, I mean those channels which currently show 0 subscribers in Invidious.
- "vevo" - error.
- "eminem vevo" - error. "eminemvevo" - error.
- "vsauce vevo" - error. "vsaucevevo" - no error (channel with that name exists).
- "pewdiepie vevo" - error. "pewdiepievevo" - no error (channel with that name exists).
- oddly enough, both "markiplier vevo" and "markipliervevo" give no error.

One exception:
- "blah vevo" - error. "blahvevo" no error, even though there are only 4 search results, none of which is an official VEVO.

Possibly related to #2425.

**Comment by Stypox** [comment]
Fixed by TeamNewPipe/NewPipeExtractor#191
