### ISSUE TITLE
Cannot watch or background any youtube video

### ISSUE THREAD

**Issue by nhamilakis** [TeamNewPipe/NewPipe#2618]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Since this afternoon i can no longer watch any content on YouTube. Search function works normally but when you open them it shows video not available. When you try to put the audio in the background a small message pops up and says stream not available. The app worked fine this morning. I include some screen grabs, also i am on the latest version 0.17.1

![70195701_822736271507475_2949798021522522112_n](https://user-images.githubusercontent.com/8939997/64733395-f9cb6800-d4e4-11e9-87ee-c5cc61515b06.png)

![69764586_393376298037764_8397969216229081088_n](https://user-images.githubusercontent.com/8939997/64733426-094ab100-d4e5-11e9-9a46-be5f99ead979.png)

![69980678_1108330152699905_2361279651046752256_n](https://user-images.githubusercontent.com/8939997/64733520-38f9b900-d4e5-11e9-81a4-6bfee004c8a9.png)

**Comment by thanosme** [comment]
See #2615
