### ISSUE TITLE
0.17.2 App not installable

### ISSUE THREAD

**Issue by megaxlr** [TeamNewPipe/NewPipe#2619]
Release 0.17.2 apk from the releases page does not let me install. 
I'm on Android 9 (patch level april 1st)

**Comment by Ex-Ark** [comment]
I am having a fail on upgrade too, the error message says something about a package conflict. 

Was the released apk signed with the same key as usual or the debug key?

Thanks for the update anyway :+1

**Comment by JustMeErazem** [comment]
Did you download the original app from F-Droid before. Because if so, the new release and the F-Droid release have different signatures. So you'll have to back up any existing data, uninstall the F-Droid release and install the one from their website.

**Comment by Ex-Ark** [comment]
For my case yes I did install it from Fdroid. But the update is not available in their sources right now so I tried to manual install.

Will try complete uninstall. Thanks

**Comment by megaxlr** [comment]
@JustMeErazem That's it! Thanks mate! I'll keep this issue open just so duplicates will be avoided (I hope)

**Comment by theScrabi** [comment]
fdroid and non fdroid version are not yet compatible.

**Comment by mouarfff** [comment]
I don't understand why u have two version ?

Last time i had to use github bversion because f-droid didn't make any update.

But it's a problem because i don't have only this app to update

**Comment by JustMeErazem** [comment]
There aren't two versions. F-Droid uses the code and generates their own builds. If you want faster updates, use the Github version, it has an update checker built-in.

**Comment by theScrabi** [comment]
Well we should just finally start taking on this project of making newpipe reproducable.

**Comment by mouarfff** [comment]
i don't know how to ...

Many times, the f-droid version is too old and it doesn't work at all, but f-droid method should be the best way

**Comment by erazemkokot** [comment]
@mouarfff The point is, for now you can use the Github release and when F-Droid and NewPipe properly implement reproducible builds, you'll be able to install updates faster directly from F-Droid, but they will have the same signature as the Github release, so you'll be able to install from both.

**Comment by mouarfff** [comment]
Ok thx a lot for your app !!!  👍 :)

**Comment by erazemkokot** [comment]
@mouarfff You have @theScrabi and others to thank for, I just use NewPipe :)

**Comment by mouarfff** [comment]
lol ok :)
