### ISSUE TITLE
Time indicators are extremely hard to see

### ISSUE THREAD

**Issue by 12people** [TeamNewPipe/NewPipe#262]
As the time indicators are black text on a dark background, they can be very hard to see. Please consider making them white.

I'm using the Samsung Galaxy Note 10.1 with Android 4.1.2 (with Samsung's TouchWiz on top)

**Comment by CHRINIMUE** [comment]
Do it look like this? (NP 0.7.8)
![screenshot_2016-05-26-09-32-30](https://cloud.githubusercontent.com/assets/15434539/15567208/43934342-2325-11e6-917b-ef214cc2cb30.png)
![screenshot_2016-05-26-09-31-50](https://cloud.githubusercontent.com/assets/15434539/15567207/438f57d2-2325-11e6-9543-5a44ee29c084.png)
If yes, I think it's ok. If not, we need to fix it ...

**Comment by 12people** [comment]
I'm talking about the ones when the video is playing (the red rectangles show what I mean when I say time indicators):
![time_indicators](https://cloud.githubusercontent.com/assets/7361228/15609933/0bfb94ee-2423-11e6-8261-8ee14dae3073.png)

**Comment by theScrabi** [comment]
Its that god damn vido player interface. I hate it since I've created it. Kill it with -9, Burn it, its evil. Would be nice if some day we could have a proopper player UI, but I have no idea from where we should get it. Maybe VLC player.

**Comment by CHRINIMUE** [comment]
Ah, ok. Sorry. I thought you mean the time indicator of the search results.

**Comment by 12people** [comment]
@theScrabi I'd recommend against using the VLC UI. The gesture-driven make it very hard to use, at least on this tablet.

**Comment by theScrabi** [comment]
That may be, but writing my own feels like some sort of PITA.

**Comment by mauriciocolli** [comment]
New UI now, yay!
