### ISSUE TITLE
blocked on youtube? legacy 16.02

### ISSUE THREAD

**Issue by coffeecult** [TeamNewPipe/NewPipe#2620]
hi.
hope this finds you well!!

apologies for the possible alarmist subject.

for the past 12 hours or so,  attempting to watch/hear YouTube produces a message
video not available.

same on newpipe..

videos run fine on YouTube app, as well as others like music piped, etc..

tried various connections, no joy.

even turning the phone off and on isn't helping 😉

any clues?

cheers and many thanks!

ti
xxc

**Comment by dogtopus** [comment]
see #2615
