### ISSUE TITLE
Add Invidious support

### ISSUE THREAD

**Issue by e-edgren** [TeamNewPipe/NewPipe#2621]
I would love to see an option in NewPipe's settings, where you can choose to connect to the Invidious network instead of YouTube, and also be able to change instance. What I know of, Invidious does not have any app for their service. Why not change that? 🙂

**Comment by Gymcap** [comment]
I agree with this. It would also be nice to be able to use our own instance.

**Comment by airon90** [comment]
See #2488

**Comment by dimqua** [comment]
It's good move, but it'd even better to completely "disconnect" from YouTube (and other google services) by using Invidious API instead.

**Comment by Z3ROGRAV1TYx** [comment]
Would love to see this!

**Comment by danialbehzadi** [comment]
This would be awesome 😍

**Comment by KonoromiHimaries** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/3136

**Comment by KonoromiHimaries** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1819

**Comment by trymeouteh** [comment]
I think users should be able to add invidious instances just like you can add peertube instances. And have invidio.us as the default instance.

**Comment by danialbehzadi** [comment]
> I think users should be able to add invidious instances just like you can add peertube instances. And have invidio.us as the default instance.

Invidious is not a network like Peertube, but an interface/proxy for YouTube. It should be able to redirect incoming YouTube URLs to selected Invidious instance.

**Comment by grravity** [comment]
@danialbehzadi But there's different Invidious instances. For example the load on the main one is pretty bad, so if someone wanted to selfhost their own personal instance or use a friends they'd have that option to specify which one. Not exactly the same as PeerTube, but kinda the same idea just as a wrapper frontend

**Comment by danialbehzadi** [comment]
@grravity That could be easily done with an entry in settings, just like NitterizeMe is doing.

**Comment by grravity** [comment]
@danialbehzadi Yes ofc, but I was just clarifying I believe that is what he was asking for

**Comment by pluja** [comment]
This would be amazing! Being able to use Invidious and never connect to Youtube

**Comment by B0pol** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1867
