### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by archi-doctor** [TeamNewPipe/NewPipe#2622]
Every video gives video not available, just comments are showing.

**Comment by dakotagrvtt** [comment]
Just update to [v0.17.2](https://github.com/TeamNewPipe/NewPipe/releases/download/v0.17.2/NewPipe-v0.17.2.apk).

**Comment by archi-doctor** [comment]
So I have to delete the f-droid version. Okay, I will use the github stream. Thanks
