### ISSUE TITLE
YouTube reverted their changes (0.17.1 still works)

### ISSUE THREAD

**Issue by TheFrenchGhosty** [TeamNewPipe/NewPipe#2623]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

This is weird, but YouTube cancelled what they changed and even with after https://github.com/TeamNewPipe/NewPipe/issues/2615 0.17.1 still works (tested on 2 devices).

**Comment by floss-birdy** [comment]
True.,..😪 sad the devs worked so hard and ....... It. Ends up like this

**Comment by smalos** [comment]
The change could be made again at any time. Perhaps it is good to be prepared.

**Comment by Stypox** [comment]
The good thing is that 0.17.2 works too, and the new code is better than the old one, so it's ok
