### ISSUE TITLE
Switching to lock screen when a video starts playing

### ISSUE THREAD

**Issue by gorlapraveen** [TeamNewPipe/NewPipe#2624]
- [*]  I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

- [*] I checked if the issue/feature exists in the latest version.
- [*] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When a video starts playing, it abruptly switching to lock screen and again I need to unlock the screen to watch (observed in version 0.17.2, 0.17.1, 0.16.2)

**Comment by Stypox** [comment]
Duplicate of #2378
