### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by brodudeman** [TeamNewPipe/NewPipe#2627]
Do not have a log for this but it seems that scrolling down through comments or recommended videos is smooth but when you go back up it just almost instantly pulls the video preview up. It works fine but the activation for it to trigger is super sensitive. Ive tested holding a finger on the screen to stop it from scrolling and that works but if it has even a little motion (without a finger on the screen) going back towards the video bam instantly pop preview back up.

**Comment by mouarfff** [comment]
I can confirm too
