### ISSUE TITLE
Subscription count shows to small values

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [TeamNewPipe/NewPipe#2632]
version: 0.17.3 debug
android 8

Hi , problem with numbers follower channel ,

number follower display is false / wrong

**Comment by fossopensource** [comment]
Same problem in 0.17.2 ..

**Comment by madeindjs** [comment]
Same problem on 17.1

![Screenshot_20190915-132734](https://user-images.githubusercontent.com/11815139/64920886-c591c900-d7bc-11e9-9c9f-154223e80685.jpg)
![Screenshot_20190915-132721](https://user-images.githubusercontent.com/11815139/64920888-caef1380-d7bc-11e9-9c98-8e05b0dad1fc.jpg)

**Comment by TobiGr** [comment]
YouTube changed the numeric value to a mix of numbers and words which causes the extracted subscriber count to be too small. 
``` HTML
<span class="yt-subscription-button-subscriber-count-branded-horizontal subscribed yt-uix-tooltip" title="4,86&nbsp;Mio." tabindex="0" aria-label="4,86&nbsp;Mio. Abonnenten">4,86&nbsp;Mio.</span>
```
The problem is that we need to translate e.g `4,86 Mio` to 4 860 000 which is quite tricky because the words which are appended to the number are different for each language. I tried to find a library which can do this, but I wasn't successful. 

@Stypox, @theScrabi any ideas how we can solve this without creating a Map which contains the abbreviations for all the languages?

**Comment by Stypox** [comment]
If we need to manually build something we could draw inspiration from https://github.com/MycroftAI/lingua-franca

But are you sure there is no other reference to the number of subscribers in the page?

**Comment by omarroth** [comment]
You can force English with `&gl=US&hl=en` which will always provide subscriber count in the `6.88M`, `10.1K`, etc. format.

See also omarroth/invidious#753 and relevant commit omarroth/invidious@b1fc80b79ae498f7bfd6ad7a32ebee98fabdaf4a.

**Comment by TobiGr** [comment]
@Stypox I've searched the whole document, but could only find the `span` above which contained a number which started with 48 (or 4,8 / 4.8).

@omarroth This is probably the best solution since the content language is quite irrelevant when viewing a channel.

**Comment by fightthepower** [comment]
I dont know java but can I give a suggestion. why can't we extract and clean the sub count from the title parameter itself?

For example in python we can do this
```
title="4,86&nbsp;Mio."
title.replace('&nbsp;'," ")
```
with output `4,86 Mio.`

**Comment by justpicked** [comment]
Will the problem be fixed?
