### ISSUE TITLE
Rename feature on Downloads Section 

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#2635]
Can we have rename on the downloads file section, now we have to go all the time manually on the folder and do it :)

![](https://i.imgur.com/M7ZJDqr.jpg)

**Comment by opusforlife2** [comment]
Rather than that, I think it would be more useful to just have a menu entry in Downloads to open the video or audio download folder in the file browser so we can perform all such operations there.

**Comment by opusforlife2** [comment]
I did end up noticing that the names of the menu options for choosing video and audio download folders are inconsistent. One says "Video download path", other says "Audio download folder".

Yo, @Stypox @TobiGr could you help me with changing it? I wanna learn how to make pull requests. Best start with trivial stuff.

**Comment by Stypox** [comment]
@opusforlife2 Here is the process, I assume you know a little bit of `git`.

- Fork NewPipe on GitHub
- Install `git`, if you haven't already
- Open a terminal
- Run `git clone URL_OF_YOUR_FORKED_REPO` in terminal to clone your forked repository on your pc
- Change the files you want to change inside the cloned folder
- Navigate to the repository root folder
- Using `git status` you can view all of the changed files (in red)
- Mark the files you really wanted to change with `git add` followed by the path of the files shown in the status. Then run again `git status` to check if you did all correctly (files that are going to be committed are shown in green)
- Run `git commit -m "MESSAGE"` to commit.
- Run `git push` to upload the commit to your forked repo on GitHub. You will be asked for password. If git complains about branches and suggests another command, run that one.
- Head over to your forked repo on GitHub, and click on "New pull request". Then the instructions should be on screen.

If you have any further question, feel free to ask :-)

**Comment by TobiGr** [comment]
It might be good to create a new branch by running `git checkout -b NEW_BRANCH_NAME` before adding the files (`git add FILE_PATH`).
For more info on branching, see https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by opusforlife2** [comment]
... guys. I did everything through Github in the browser. Please don't kill me. #2637

**Comment by goxr3plus** [comment]
Thanks for the directions guys, of course I know git and good Java, just my Android experience is limited, i am Full Stack not mobile developer yet.

Just wanted to point out a missing feature not demanding.

But really thank you, i will try to collaborate :)

**Comment by Stypox** [comment]
@opusforlife2 All is good, it is ok to do things on GitHub. The newline character was added by Android Studio, but afaik it is ok.

**Comment by opusforlife2** [comment]
@Stypox Cheers! I realise that I should only do such minor changes on Github, and any major stuff should be done by downloading the source and testing changes myself first.

**Comment by opusforlife2** [comment]
@goxr3plus The directions were for the noob (me) not you. :P

**Comment by opusforlife2** [comment]
> Rather than that, I think it would be more useful to just have a menu entry in Downloads to open the video or audio download folder in the file browser so we can perform all such operations there.

@Stypox Opinion?

**Comment by Stypox** [comment]
I agree with you, using the file browser to do file-related actions is a good idea: it means there are less (device-specific) features to maintain in NewPipe, and also gives more options

**Comment by opusforlife2** [comment]
Is it something that can be easily added? If it's simple enough, I could try doing it.

**Comment by Stypox** [comment]
Yeah, it should be rather simple to add a button that shows a file in the file explorer

**Comment by opusforlife2** [comment]
Never mind. I had a look. I don't even know what file to modify. I thought it was DownloadActivity.java, but the more I stare at it, the more unsure I become.

**Comment by Stypox** [comment]
There should be a menu for the download activity, and you can deduce the class where it's being used using "Find usages (Alt+Shift+F7)". Also, you could find a string related to the download activity in strings.xml and find its usages

**Comment by B0pol** [comment]
Also, really useful shortcut: ctrl shift F, it's like ctrl F but for the whole android studio project (so for newpipe, project is newpipe)

**Comment by opusforlife2** [comment]
Okay. I was looking through Github. I didn't know you were talking about Android Studio, Stypox. B0pol cleared that up. So I forked and cloned the repo in Android Studio.

Everything was going fine, then something called Gradle sync started. Eventually, it showed this error:

`NDK Resolution Outcome: Project settings: Gradle model version=5.4.1, NDK version is UNKNOWN`

What should I do?

**Comment by wb9688** [comment]
@opusforlife2: Is that actually an error? We don't even use the NDK afaik. Check if you could successfully build it (with that button at the top-right), and if so, just ignore that.

**Comment by opusforlife2** [comment]
@wb9688 Which button? There is a Build menu. If I click on Make Project, nothing happens.

**Comment by wb9688** [comment]
@opusforlife2: The green hammer. It should say something about your build progress on the bottom. Btw if you connect your phone and enable adb on it, you could press the green play button to also install your compiled app and run it.

**Comment by opusforlife2** [comment]
The green hammer is Make Project. As I said, it doesn't do anything.

**Comment by Stypox** [comment]
@opusforlife2 that's not an error, you can just ignore it. The green hammer builds the project, but your project is probably already built, hence it does nothing.
Android Studio should work fine in the situation you are in: on the left open the Project bar (if it's not already open) and e.g. navigate to strings.xml by following this path in folders: "app->res->values->strings->strings.xml" . Then you can do what I told you above (sorry, my bad for not specifying you need to be on Android Studio ;-) ).

When you want to test the app:
- Enable debugging on your phone from developer settings
- Connect your phone to the computer
- Press the green triangle (that looks like a "play" button) in the top bar and the app should install on your phone directly

**Comment by opusforlife2** [comment]
Analysis so far: I think the menu shown for each downloaded file takes entries from mission.xml and strings from strings.xml, and the file URI is known to the StoredFileHelper class in StoredFileHelper.java, which is used by DownloadMission.java and then FinishedMission.java.

But I have no idea how those xml entries are being used to populate the menu. And I don't know which method is creating the menu in the first place. I think I'll need to learn some Java and then Android first...

**Comment by opusforlife2** [comment]
By the way, in my Android Studio, all 6 icons to the left of "Attach debugger to android process" are greyed out. I went with the default setup, but I think I need to install or set up something more.

**Comment by Stypox** [comment]
No, it should work out of the box, I never had to do anything on any NewPipe repo

**Comment by opusforlife2** [comment]
Can you try to rename/backup your project and clone the repo afresh through Android Studio? Everything was going fine until I hit the gradle sync error regarding the NDK.

**Comment by Stypox** [comment]
I did that just a week ago, so that can't be the issue...
Could you send a screenshot of AndroidStudio while it's not working?

**Comment by opusforlife2** [comment]
Here you go:
![Capture](https://user-images.githubusercontent.com/53176348/75120360-1d453200-5683-11ea-8c12-11d3ad61fd61.PNG)

**Comment by B0pol** [comment]
I also have NDK warning, this is not a problem. It's something else.
In add configuration, what happens?
Normally, you should select module "app".

Also, you can search for the issue:
https://www.qwant.com/?q=no%20value%20has%20been%20specified%20for%20this%20provider&client=opensearch&r=GB.

**Comment by opusforlife2** [comment]
🤦‍♂ 

While trying random things, I tried to Build > Make Module Newpipe, which led to the error that android SDK-28 wasn't installed. After installing that, gradle magically began to sync. That took a few years to finish, and now I can finally build the app.

**Comment by opusforlife2** [comment]
Congratulations to me. I have a non functional download item entry "Open folder". Now to figure out how to make it work. 👀

**Comment by opusforlife2** [comment]
@Stypox I've searched online and people struggle to find ways to pass an intent to file managers to open a folder. Android doesn't provide a standard intent. Someone should alert Google about this.

Basically I've taken on an impossible task that even the Syncthing guys are struggling with. Unless you or anyone else here knows of a way to do this, I'm out of ideas.

**Comment by wb9688** [comment]
@opusforlife2: Use SAF or our internal file picker, depending on what option the user chose in the settings.

**Comment by opusforlife2** [comment]
@wb9688 The idea was to foist the functionality off on the user's installed file explorer, as Stypox says here:

> I agree with you, using the file browser to do file-related actions is a good idea: it means there are less (device-specific) features to maintain in NewPipe, and also gives more options

I thought that would be a nice little thing to have. Apart from that, this feature request doesn't make sense, as you get the option to rename the download in the download dialog itself.

**Comment by opusforlife2** [comment]
It is ridiculous that Android doesn't let you show a file even in the default AOSP file explorer, though.

**Comment by Stypox** [comment]
@opusforlife2 mmmh, ok, sorry if I told you this was a simple task... I thought an Intent existed to do exactly that, but apparently it does not exist. Thank you for your interest, anyway :-D

**Comment by opusforlife2** [comment]
No problem. :)

I would have liked to see my efforts in understanding the code base and trying to contribute a little pay off, but I learned some things along the way, so I'm not that disappointed.

**Comment by Stypox** [comment]
Closing this since it can't unfortunately be done in a reliable way due to Android limitations. See my comment above
