### ISSUE TITLE
Select and Download Multiple Videos as Videos or Audio. 

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#2638]
Can we have an option for example we have the beloe videos

![](https://i.imgur.com/ZCKF8mz.jpg)

We randomly select some of them like 4 or 5 and click share and then the menu to download appears.

:) Waould be great.

**Comment by Stypox** [comment]
#2583 would probably suit your needs :-)

**Comment by goxr3plus** [comment]
@Stypox Very close :)

**Comment by Stypox** [comment]
Closing in favour of #2380
