### ISSUE TITLE
Exit and Refresh options in menu

### ISSUE THREAD

**Issue by ponypower** [TeamNewPipe/NewPipe#264]
Would be cool having an **Exit** option in the popup menu so _I shouldnt have to press back several times_ to close the app. This option is pretty common with other FOS applications I use.

Rarely the internet connection breaks up because of nonapp related reasons and the app obviously cannot load the page. _After reconnection I have to go back and tap again_ on the desired thingy to reload the page. Please include a **Refresh** option in the popup menu for this occurrence. I'm sure there are other reasons to do that.

**Comment by CHRINIMUE** [comment]
Actually I am working on a Swipe Refresh(Layout). There are some problems, but I think I will be able to fix it. 

But my question is: What do you mean with "Exit" Button/Option? I mean, there is a home button to quit the app? (Or do you use an Android phone whitout these button?) Sorry, but what exactly do you mean?

**Comment by ponypower** [comment]
So by pressing the Home button you only put the app in the background. It remains in the memory and sometimes it does use the cpu and the app is practically allowed to do its funny business. Some of the apps I use have an Exit (or Kill) option in the popup menu so I can totally close the app, knowing that it wont do anything anymore.

NewPipe stays in the memory after I press the home button and it stays listed at the active application list with some memory usage (no cpu though). I can only really close the app by pressing the Back button several times (it quits from the search page). When Im watching a video, it takes 3 presses to do that.

For example Tinfoil for Facebook and Firefox (optional) have the Exit option in its popup menu.

**Comment by hp77-creator** [comment]
Hey there! I am new to NewPipe. I would like to see this feature in the application as how the OP pointed out the app stays in background if back gesture is used. I think it will be convenient to provide a popup with an exit button, which simply kills the application. I am new to Android Development, like this will be first time I will be doing something like this. So, I would appreciate if you have any resources or such to implement widgets i guess, I have begun study from my side on the codebase of the application. I look forward to working on this issue. Thank you.

**Comment by opusforlife2** [comment]
Retrying is now part of the app, and you can exit by swiping the app from Recents.
