### ISSUE TITLE
[Feature request] manually mark videos as watched

### ISSUE THREAD

**Issue by woj-tek** [TeamNewPipe/NewPipe#2642]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

-----

I welcomed addition of 'watched videos' feature and it's really great. However just today I figured out that quite often I watch videos on the internet (invidious) and it would be helpful to be able to manually mark video as watched (so, in the future, I would be able to filter them out of channel views for example)

**Comment by Stypox** [comment]
Related: #1163

**Comment by woj-tek** [comment]
Thanks @Stypox for linking (I'd love to see that issue implemented as well).

**Comment by Stypox** [comment]
Also related: #2567
