### ISSUE TITLE
0.17.3 apk shows version name 0.17.2

### ISSUE THREAD

**Issue by johanw666** [TeamNewPipe/NewPipe#2645]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
The latest published apk (0.17.3) has 0.17.2 in the version name field. (which is obviously incorrect). The source looks correct, is the correct apk uploaded?

**Comment by TobiGr** [comment]
I guess not. @theScrabi Could you please take a look into this?

**Comment by AlexFrost** [comment]
Same issue with version and all 17.2 bugs are reproduced on 17.3

**Comment by TGWGitHub** [comment]
Version 0.17.3 has build number of 770 while the RC1 had a higher number 780 .. thus the new version cannot update the RC1 .. is this normal?

**Comment by TGWGitHub** [comment]
The newly released version is showing as v0.17.2 Build 770.

Can't update the already installed 0.17.3 RC1 Buld 780.

**Comment by theScrabi** [comment]
Did i build the wrong version,m

**Comment by theScrabi** [comment]
Yes I did. I'm sorry. I now build and uploaded the right version.
