### ISSUE TITLE
Wrong number of subscribers

### ISSUE THREAD

**Issue by xxkfqz** [TeamNewPipe/NewPipe#2652]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
---
# NewPipe
![Screenshot_2019-09-19-17-57-05-623_org schabi newpipe](https://user-images.githubusercontent.com/52203435/65246335-c2be0d80-db07-11e9-8634-787188f239c8.png)
![Screenshot_2019-09-19-18-01-45-881_org schabi newpipe](https://user-images.githubusercontent.com/52203435/65246336-c356a400-db07-11e9-978c-89060cef844f.png)

# YouTube
![Screenshot_20190919_175937](https://user-images.githubusercontent.com/52203435/65246194-7a9eeb00-db07-11e9-84bf-8a874472c223.png)

**Comment by Stypox** [comment]
This is fixed in 0.17.3

**Comment by xxkfqz** [comment]
> 
> 
> This is fixed in 0.17.3

It's not fixed in 0.17.3. Do you see that I checked "I checked if the issue/feature exists in the latest version."?

**Comment by Stypox** [comment]
It's because the wrong apk was uploaded on the release page, please download it again

**Comment by xxkfqz** [comment]
Nope, bug is still here
