### ISSUE TITLE
Lot of bug

### ISSUE THREAD

**Issue by StellarisStudio** [TeamNewPipe/NewPipe#2653]
Since today, cannot import content anymore, cannot watch video anymore, ask for FUCKING google captcha and crash...... Bye NewPipe !!

**Comment by Stypox** [comment]
Could you please share the crash report? This is a know issue but so far we have not been able to investigate it

**Comment by TobiGr** [comment]
Please calm down and help us to fix this. Please post the crash log below so we can get the important info from it. Please also tell us the country from where you try to access YouTube
