### ISSUE TITLE
When having a VPN connection enabled, it takes an infinite amount of time to download all content on Newpipe.

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2654]
- [x] I carefully read the [contribution guidelines](https:/) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When having a VPN connection enabled, it takes an infinite amount of time to download all content on Newpipe. All videos etc. just keep loading.

**Comment by AnthonyKL** [comment]
Can confirm.

This is an important issue because probably many NewPipe users uses a VPN service to prevent Google from knowing their IP address.

@theScrabi , are you aware of this issue?

**Comment by AnthonyKL** [comment]
@TobiGr 

Are you looking into this?

**Comment by opusforlife2** [comment]
Has _anyone_ looked into this? Ghost users, both, but this seems important.

**Comment by Stypox** [comment]
This should be closed imo. If someone else encounters this issue he will open a new one, but with the little information provided here there is nothing that can be done
