### ISSUE TITLE
Finished download stuck in pending section

### ISSUE THREAD

**Issue by bew** [TeamNewPipe/NewPipe#2656]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Downloading this video https://www.youtube.com/watch?v=UpFpfvDNPdE (from share > download > video) never ends: the download goes to 100% (and I can play it completely from my file manager) but it stays in the "pending" section. I tried to pause then start it without success.

It does not seems to happen with other videos.

**Comment by OffifialMITX** [comment]
Happens to me as well at random. Re-downloading might help or might not at random as well.

**Comment by kapodamy** [comment]
¿in what resolution? is in mp4?

**Comment by bew** [comment]
Yes, mp4

**Comment by OffifialMITX** [comment]
@kapodamy I usually download in 720p, 720p60 and 1080p.

**Comment by OffifialMITX** [comment]
[Example](https://i.imgur.com/ImJUoMN.png)

**Comment by OffifialMITX** [comment]
This happened during a low storage situation, with 720p.

**Comment by kapodamy** [comment]
cannot reproduce this issue. if the storage runs out of space you get an error but not in this way, is strange

**Comment by OffifialMITX** [comment]
Hm, which format did you try to download in? Also what happens after you continue the download after clearing up space?

**Comment by kapodamy** [comment]
@OffifialMITX 
1_ all formats
2_ yes

**Comment by OffifialMITX** [comment]
"Yes" isn't quite an insightful answer for "what happens…?".

**Comment by kapodamy** [comment]
nothing, download appears in finished section.

**Comment by thezerobit** [comment]
I'm having the same issue, downloading 720p videos with the latest NewPipe from FDroid. Plenty of storage space on my device, running the latest Android version on my Nexus 5X.

**Comment by opusforlife2** [comment]
@bew @MrHeating Can you check if this is still the case?

**Comment by bew** [comment]
Didn't get this behavior since a while, so I'd say it's gone, thanks!
