### ISSUE TITLE
NEXT video is chosen randomly

### ISSUE THREAD

**Issue by drji3m** [TeamNewPipe/NewPipe#2658]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

If I search for a video, say the old tv series Matlock, I get a whole screen full of matches. If I pick one and play it the NEXT to play cone from some deep and mysterious place in youtube. It would be great if next cam from that origin set of search results. 

The current time NEXT choices seem random, unrelated and chaotic and I have to admit that it uncovers some interestING things. Like from Matlock to Sid Cedar or Bevwrly Hillbillies or even stranger results. 

I would like a "play all" option to be available with any set of search results.

**Comment by Stypox** [comment]
The NEXT video is not chosen by NewPipe but it is just the first video of the suggestions provided by YouTube.

Would #2583 suit your needs? It would provide a way to select multiple videos from every list.

**Comment by drji3m** [comment]
Probably. I realize youtube is picking the next videos based on my neural
model and their purposes. I thought maybe newpipe could keep a list of what
was returned from the search and make it into a playlist which  could be
used or discarded.

I like to binge watch old tv series and my main problem is keeing track of
what i've watched since there is no order to the results.

Newpipe is already far superior to the Youtube app (which i keep
disabled,). It can only get better.

**Comment by OffifialMITX** [comment]
@drji3m Right now you could probably just use the enqueue options you get when ypu long-click a video. Or even create playlists for later.

**Comment by drji3m** [comment]
Thanks for the suggestion. One problem is there may be one or two hundred
episodes and even a playlist won't track watched ones. Or start from the
middle?

**Comment by OffifialMITX** [comment]
Well you may just set the playback position to somewhere in the middle do it remembers your last position (with according settings, which is then visually represented.

**Comment by drji3m** [comment]
Great. Will try it.

**Comment by PeterHindes** [comment]
Not exactly sure what the issue is here. Is this a complaint about how useless autoplay is? Could you restate your problem please.
