### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by ponypower** [TeamNewPipe/NewPipe#266]
Here is a new design for the NewPipe logo. It's more pipy!
![newpipe-logo](https://cloud.githubusercontent.com/assets/16841860/14457918/41ebc68e-00ae-11e6-81c9-7c207a97d795.png)

**Comment by theScrabi** [comment]
Hm thanks, I'll put it into our assets folder, if you send it to me as an svg. But I will not make it our new logo, since it does not follow google design guidelines.

**Comment by ponypower** [comment]
**A logo to fall in love with ...**

Here is a more appropriate logo for the product. I would like to emphasize that this is not a google product, therefore it does not need to be a google like logo. 

![4 1](https://cloud.githubusercontent.com/assets/16841860/14592004/6b22854a-051a-11e6-8ca2-1c08a0b4e741.png)

The app uses YouTube. Therefore this NewPipe logo resembles the YouTube for Android logo with the triangle shape and the colors. It uses the official red color of the flat YouTube logo. This NewPipe logo shapes the two main letters - N and P - of the title with lower-case letters for simplicity with continous thick lines resembling a pipe system to visually connect the logo to the title. The sharp edges stand for showing details, indicating precision and transparency in the code. The lack of shadows reflects the lightweight feature of the app an also stands for transparency in the code.

That's it. Tell me guys what do you think.

**Comment by ponypower** [comment]
Here is the NP logo compared to a few other android logos
![1](https://cloud.githubusercontent.com/assets/16841860/14592517/e1f1d716-051f-11e6-9678-8b959647b5a6.png)

**Comment by theScrabi** [comment]
Hm I need to think about that. I admid it doesn't look that bad.

**Comment by ponypower** [comment]
Well, on the other hand there are a few things against keeping the current logo. These things are actually the other android palyer logos... Make a quick search at google play for "player". I guess it talks for itself. Dont miss the "Video Player for Android" app which practically has the same logo as NewPipe.

The current logo is just simply generic. It literally says "yap, just an other player app in the million".

**Comment by darkon5** [comment]
> I would like to emphasize that this is not a google product,
> therefore it does not need to be a google like logo. 

It's not about being Google-like, it's about following the Material Design guidelines in order to fit the whole Android environment.

Putting that aside, I personally love that last logo :) Great work!

**Comment by ImAnnoying** [comment]
Maybe make it a bit like the Support app in the picture? Also instead of a flat line make it (simplified) pipes :)

**Comment by comradekingu** [comment]
![newpipe](https://cloud.githubusercontent.com/assets/13802408/14931310/b0676f4a-0e6a-11e6-97e4-3fb283db01cf.png)

![newpipe2](https://cloud.githubusercontent.com/assets/13802408/14931315/b616215c-0e6a-11e6-8cd2-c7fcf6034df0.png)

Introducing the bent pipe aesthetic is something to explore.

**Comment by theScrabi** [comment]
Ow boy xD. I've said it in a mail recently. Id like to stick to that simple "triangle in a circle" design. You guys could try to make that look better :)

**Comment by ponypower** [comment]
I collected a few red&white triangle&circle logos from **various sources**, like google play apps, stock logos/icons and I included the current NewPipe logo too. Let's find it! :)

![omlesztve mini](https://cloud.githubusercontent.com/assets/16841860/15003788/e2ea4fc6-11af-11e6-8cc4-05dd291cce66.png)

[It is the top right]

Small design changes in the "simple triangle in a circle" wont make it a logo. It's like every car logos would imitate a wheel. It wont stand out. On the other hand you rightfully worry about that drastical changes in the logo would confuse the users and maybe damage the brand of NewPipe. Most of the users got used to the logo even when the logo is generic. But from an other approach maybe it's time to give the users a real logo which they can truly associate with the app.

So here is the simplified pipy logo:

![7](https://cloud.githubusercontent.com/assets/16841860/15004142/a1af304a-11b3-11e6-81e1-595beb1dfd06.png)

- triangle & circle
- red & white
- and uniquely pipy with a P

**Comment by comradekingu** [comment]
![liney](https://cloud.githubusercontent.com/assets/13802408/15022210/df33d16a-122a-11e6-8b7e-3140caaaf953.png)
![pipey](https://cloud.githubusercontent.com/assets/13802408/15022216/e9540a02-122a-11e6-9569-4f05a65d9225.png)

**Comment by ponypower** [comment]
awesome :)

**Comment by ponypower** [comment]
my helmet for the Logo War:
![x vicces](https://cloud.githubusercontent.com/assets/16841860/15026064/b35bce5a-123c-11e6-986d-ff9db68f6615.png)

**Comment by theScrabi** [comment]
@ponipower i like your new pipy logo :))

**Comment by comradekingu** [comment]
![bowliney](https://cloud.githubusercontent.com/assets/13802408/15090051/21c2c886-1417-11e6-9984-75d39adf13e0.png)
![bowlpipey](https://cloud.githubusercontent.com/assets/13802408/15090053/2f9897b0-1417-11e6-8a8b-9ae7987fd05a.png)

**Comment by Gracecr** [comment]
Sorry to bump, but @ponypower 's last logo is gorgeous (Not the helmet one, though that is neat too). Would be great to distinguish NewPipe from all the other player apps.

**Comment by theScrabi** [comment]
I consider some sort of relaunche. Than I'd like to use ponypowers logo.

**Comment by theScrabi** [comment]
Hei @ponypower id like to use your icon now. Can you send me an svg of it?

**Comment by theScrabi** [comment]
All right never mind here is my version of your logo:
![https://raw.githubusercontent.com/theScrabi/NewPipe/master/assets/new_pipe_icon_5.png](https://raw.githubusercontent.com/theScrabi/NewPipe/master/assets/new_pipe_icon_5.png)

**Comment by ponypower** [comment]
Hi, I've just sent you the SVG of the original since i cant upload it.
I see you added some shadows to look more fancy, but they say less is sometimes more. Check the mega logo, no shadows either https://mega.nz. They could have added shadows but did not. Simplicity rocks. The original version follows the same principle.
![1](https://cloud.githubusercontent.com/assets/16841860/17276620/98c5a1d8-572e-11e6-8636-5c20dc257c63.PNG)

**Comment by theScrabi** [comment]
It's actually the old logo with that new triangle. And a darker color.
Id like to take your version as our logo, but my version as the app icon, since i made the experience that an icon without a shadow looks ugly on android. Also the old icon (also the now one now) is accurately crafted after the roles of material design.

**Comment by zoff99** [comment]
its a bit close to the "Bundesagentur für Arbeit" https://www.arbeitsagentur.de/

![ic_launcher](https://cloud.githubusercontent.com/assets/6833516/19014668/afcaaf7c-87f3-11e6-97bd-612c2f0bf6b6.png)
![unbenannt](https://cloud.githubusercontent.com/assets/6833516/19014670/c0978820-87f3-11e6-97fc-e2caa257df48.PNG)

**Comment by theScrabi** [comment]
Yea I know that.

**Comment by zoff99** [comment]
do you know anyone that can help me with a new logo style for my app?

**Comment by KeizerDev** [comment]
@zoff99 what's your app link/about?

**Comment by zoff99** [comment]
https://github.com/zoff99/zanavi/

**Comment by theScrabi** [comment]
Write me an email I can redirect it to ponipower I have his mail address.

**Comment by ponypower** [comment]
Damn those `Bundesagentur für Arbeit` designers could have found something different! :)
I guess we gotta find a new one. I will put together something.

**Comment by theScrabi** [comment]
Ring free for round to. FIGHT :P

**Comment by comradekingu** [comment]
![newpipelogo](https://cloud.githubusercontent.com/assets/13802408/19133356/226527a8-8b58-11e6-8c00-6e0ad45d7793.png)
Center-aligned, and transparent backdrop with fading effect.

**Comment by ponypower** [comment]
Here is an experiment with pipes under the triangle.
I haven't got it right yet but thought I would share them.
![csoves](https://cloud.githubusercontent.com/assets/16841860/19186634/7f409d92-8c87-11e6-8067-46ff44f3d91a.png)

**Comment by zoff99** [comment]
i like the 1st one on the left

**Comment by theScrabi** [comment]
Jup that would fit to my plans of NewPipe.

**Comment by comradekingu** [comment]
@theScrabi 

https://www.youtube.com/yt/brand/using-logo.html

### →The YouTube icon 

> The identity system must not be altered or manipulated. Always present the logo and icon fully, being clearly visible. The examples below illustrate some of the most common application errors.
> Do not...

✔ alter or partially cover the logo or icon. 
✔ alter the proportions, position or letter spacing.
✔ stretch, condense, distort or separate logo or icon elements.
 alter the color or add effects (drop shadow, glow, etc).
✘ replace the logotype with another typeface.
✔ place an image within the logotype.
✘ rotate (vertically, horizontally or diagonally) or flip. 

> Any usage not addressed by the guidelines on this site needs special approval and must be submitted in English through the
https://support.google.com/youtube/contact/brand_request

There I imagine it will be read by a lawyer with no other option than to deny you the right to use it, whereby the ability to specify it's use in trademark law balances.

Yes there is a specific guideline for the YouTube icon, the notion that one can copy their logo lingers on the fact that others have been allowed to in similar fashion before. Then again it is not a vetted process, because it couldn't possibly be.
What I know about the law here and the legal apparatus you would be facing suggest however you have no chance should this actually go under the radar long enough to ever get in the way of their revenue. https://en.wikipedia.org/wiki/United_States_trademark_law
Ironically flying the YouTube icon ties NewPipe to YouTube services, when it's use is tangibly useful for a lot of other things, and for YouTube services in ways that necessitate differentiation, like website links.

**Comment by ponypower** [comment]
Here are some new contestants
![2](https://cloud.githubusercontent.com/assets/16841860/19220688/a9384ed0-8e33-11e6-8dfb-13eb76eb931c.png)
Tell me if you find one of the 8 concepts good enough.

**Comment by theScrabi** [comment]
@ponypower well I'd like the first and the third one but ...

Remember when you submited the version where you tryed to build the laters NP into to logo ![logo](https://cloud.githubusercontent.com/assets/16841860/14592004/6b22854a-051a-11e6-8ca2-1c08a0b4e741.png)

what would it look like if you made these two later a triangle?

**Comment by theScrabi** [comment]
Well when I look at it that way the 5th one kind of is the best one.

**Comment by ponypower** [comment]
I'm going to put together a couple other concepts too including your suggestion. On the other hand I would like to know when you are planning to change the current one so I can work accordingly.

**Comment by ponypower** [comment]
Hi @theScrabi, did you think of something like these? 
![b](https://cloud.githubusercontent.com/assets/16841860/20649833/3c490ad8-b4c8-11e6-8528-26a03a5cb3ee.jpg)

**Comment by theScrabi** [comment]
Yea something like that. But now I'm not sure anymore. What do you think? What's your favorite Icon?

**Comment by ponypower** [comment]
Here is another one
![6 kockas](https://cloud.githubusercontent.com/assets/16841860/21958404/a4a99c18-daad-11e6-9c8d-9dc2711bfc3b.png)

**Comment by ImAnnoying** [comment]
Love the last one 😍

**Comment by Lokesh-Krishna** [comment]
The last one indeed is very gorgeous!

**Comment by theScrabi** [comment]
Hm I like it to :)

**Comment by comradekingu** [comment]
I think this has a problem in that it is predictably also what the other YouTube style icon programs will do. At some point in the future, the downfall of the commons will mean we are back to dealing with the original problem.
Trying to predict the future, YouTube will still have it's appeal as a "major" platform insofar as being the 'red app' ties in with that. The logical extension of diversifying a field of variations upon this theme, would be to go with a different colour. However, that does not build any recognition in the interim.

A program that does more than YouTube will want to do so in a generic fashion, like the name already does. Case in point, https://rg3.github.io/youtube-dl/supportedsites.html

**Comment by mueller-ma** [comment]
@ponypower Can you submit your icon as svg to the numix icon theme? https://github.com/numixproject/numix-core/issues/3697

**Comment by theScrabi** [comment]
Well maybe we should consider a new icon espacially since @mauriciocolli did so much work recently, and made NewPipe look more elaborate.

**Comment by wb9688** [comment]
Yeah, and NewPipe will also support other services in the future.

**Comment by theScrabi** [comment]
right

**Comment by ponypower** [comment]
omg, all that work with the last logos, for what!? :D
guys, this time give me directions what you want it to express / what message to deliver / what attitude to represent,
tbh it makes me sad that some of the logos i find pretty okay will never show up on an android screen :/

**Comment by TobiGr** [comment]
I agree with @ponypower that there are several good logos. And if we change the color of the logo, we need to change the new design of the website.
If you want to change the logo's color, we should make a design concept for the logo, the app and the website. Otherwise we all will spend a lot of work unnecessarily.

**Comment by theScrabi** [comment]
I'm sorry, you guys are right. Let's say I just gave a stupid pitch, but nothing that should be taken for granite.

@ponypower @TobiGr you two did a great work, and that should not be for nothing.

**Comment by B0pol** [comment]
I found the next logo guys:
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fhabitat-eco-action.fr%2Fwp-content%2Fuploads%2F2016%2F10%2FLogo-Pole-Emploi.png&f=1&nofb=1">

<sup><sub> /s. And i close as outdated.</sub></sup>
