### ISSUE TITLE
Face issue in FlingBehavior Class when add google admob ads dependency 

### ISSUE THREAD

**Issue by sheikhazeem** [TeamNewPipe/NewPipe#2664]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by gkeegan** [comment]
This isn't an issue of NewPipe.
