### ISSUE TITLE
Question | How to open all Youtube URLs in NewPipe?

### ISSUE THREAD

**Issue by dovydasgulbinas** [TeamNewPipe/NewPipe#2665]
Greetings,

I wanted to know if there is a way I could open any Youtube URL in NewPipe? Because by default all Youtube URLs are opened in Youtube official app.

Thanks.

**Comment by gkeegan** [comment]
If you're on Pie, you can go to settings>apps>default apps>opening links>find youtube and set it to never open supported links, and set newpipe to always open.

**Comment by dovydasgulbinas** [comment]
> If you're on Pie, you can go to settings>apps>default apps>opening links>find youtube and set it to never open supported links, and set newpipe to always open.

Thank you for getting me on the right track 👍 

For my Redmi Note 7 (MIUI 10) URL handling was under different settings menu:

Settings -> Manage apps -> [...] -> Default apps -> Opening links -> YouTube -> Open supported links -> Don't open

Hope this will be useful to someone.

**Comment by B0pol** [comment]
Better: Go to Newpipe's app info, open by default, open supported links and choose open in this app. It will open all compatible links to NewPipe
