### ISSUE TITLE
Videos can be downloaded at 720p

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#2674]
[Linus Tech Tips](https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw)

Since two weeks or so I can't download any videos from that channel anymore. The error just says "Not found"

**Comment by gkeegan** [comment]
I can download their videos just fine. What version of NP are you on, and what is your location?

**Comment by OffifialMITX** [comment]
@gkeegan I'm on F-Droid's latest 0.17.1 build and am located in Germany.

**Comment by gkeegan** [comment]
Ah there is a problem. 1080p downloads fine but 720p doesn't. Confirmed issue.

**Comment by omarroth** [comment]
Testing a few videos I can also confirm. Likely related to omarroth/invidious#750.

**Comment by Aimmig** [comment]
I'm having a similar issue: Using MPEG-4 720p quality doesn't play some videos (all other qualities work). Switching to WebM Video-Format everything works just fine

**Comment by sohmc** [comment]
I can confirm the same problem.  WebM works fine.

**Comment by AnXh3L0** [comment]
Chiming in to confirm I have the same issue.

**Comment by OffifialMITX** [comment]
Ok, so since today I can download any resolution and framerate but it's in a format that VLC (on my phone) can barely handle it, I can pretty much only play videos with hardware accleration disabled and I can't do any skipping or else it starts to glitch out. Anyone experiencing something similar?

**Comment by OffifialMITX** [comment]
Ok, disregard that, apparently it's just due to my phone not handling WebM properly.

**Comment by Stypox** [comment]
Duplicate of #2415
