### ISSUE TITLE
Videos in WebM and 3GP containers are not seekable

### ISSUE THREAD

**Issue by ksio89** [TeamNewPipe/NewPipe#2676]
Don't know if it's actually a bug or not, but at least on my device (Moto G6 Plus) noticed NewPipe (0.17.3) downloads videos in WebM and 3GP containers (both use VP9 video and Opus audio formats) that are not seekable, unlike MP4. I played the files on MX Player on Android and Media Player Classic on Windows and in neither of them seeking worked properly. However, seeking works just fine on WebM videos downloaded with JDownloader 2 Windows application, on both applications mentioned. I believe seeking would also work in 3GP videos, but this container doesn't show up in the list of available ones, only Matroska, MP4 and WebM.

Using well known MediaInfo tooI to analyse the same video, NewPipe WebM video uses Format version 2, while jDownloader uses version 4 and employs Lavf to encode the videos. I wonder if that difference might be related to why video seeking feature works in one application but not in other.

Also unsure whether it's a related issue to mine, but in another issue in which a user relates that an Opus audio file downloaded with NewPipe is not seekable, apparently because it's not encapsulated in the appropriate (OGG) container: https://github.com/TeamNewPipe/NewPipe/issues/2340.

**Comment by kapodamy** [comment]
for WebM was an regresion but 3GP is not touched just saved as-is downloaded

**Comment by ksio89** [comment]
OK, thanks for making notice of this issue, I appreciate it.  Having seeking support for just WebM is fine.
