### ISSUE TITLE
Slow to open 

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#2678]
Hello, the application becomes too much slow specially when i enter to the video and to return back, it happens when i added many channels to the principal interface

![Screenshot_20191001-083401](https://user-images.githubusercontent.com/11852634/65943251-4d1f3f00-e42f-11e9-8074-d240df2b2de1.jpg)

![Screenshot_20191001-081001](https://user-images.githubusercontent.com/11852634/65942738-34faf000-e42e-11e9-8ef3-bcc351ba57e0.jpg)

**Comment by wb9688** [comment]
Could you test this with the APK from #3201? There it should only load tabs when they're visible or next to a visible tab, instead of all tabs. If that APK fixes the issue, I'll make a separate PR just for that.

**Comment by heberjeur** [comment]
I try it, it can't open videos, my phone is huawei y7 prime 2019, my internet 4mo,i have 15 tabs in the main screen
I have recorded this video 
https://youtu.be/i7vGc6-83dI

**Comment by wb9688** [comment]
@heberjeur: Could you post the crash report here? Btw did it fix the tab problem?

**Comment by heberjeur** [comment]
It works when I have returned to the default tabs

**Comment by heberjeur** [comment]
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "fr_TN",
   "service": "none",
   "package": "org.schabi.newpipe.debug.tabs",
   "version": "0.18.6",
   "os": "Linux HUAWEI\/DUB-L41\/HWDUB-Q:8.1.0\/HUAWEIDUB-LX1\/155(C185):user\/release-keys 8.1.0 - 27",
   "time": "2020-04-23 20:53",
   "exceptions": [
      "java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 568008 bytes\n\tat android.app.ActivityThread$StopInfo.run(ActivityThread.java:4719)\n\tat android.os.Handler.handleCallback(Handler.java:809)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:166)\n\tat android.app.ActivityThread.main(ActivityThread.java:7555)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)\nCaused by: android.os.TransactionTooLargeException: data parcel size 568008 bytes\n\tat android.os.BinderProxy.transactNative(Native Method)\n\tat android.os.BinderProxy.transact(Binder.java:769)\n\tat android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4652)\n\tat android.app.ActivityThread$StopInfo.run(ActivityThread.java:4703)\n\t... 7 more\nandroid.os.TransactionTooLargeException: data parcel size 568008 bytes\n\tat android.os.BinderProxy.transactNative(Native Method)\n\tat android.os.BinderProxy.transact(Binder.java:769)\n\tat android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4652)\n\tat android.app.ActivityThread$StopInfo.run(ActivityThread.java:4703)\n\tat android.os.Handler.handleCallback(Handler.java:809)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:166)\n\tat android.app.ActivityThread.main(ActivityThread.java:7555)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)\n"
   ],
   "user_comment": ""
}

**Comment by wb9688** [comment]
@heberjeur: Hmm… I don't have that issus myself, though I'll look into that later. I could make an APK for you to test with just the fix for this issue tomorrow.

**Comment by heberjeur** [comment]
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "fr_TN",
   "service": "none",
   "package": "org.schabi.newpipe.debug.tabs",
   "version": "0.18.6",
   "os": "Linux HUAWEI\/DUB-L41\/HWDUB-Q:8.1.0\/HUAWEIDUB-LX1\/155(C185):user\/release-keys 8.1.0 - 27",
   "time": "2020-04-23 21:26",
   "exceptions": [
      "java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 585232 bytes\n\tat android.app.ActivityThread$StopInfo.run(ActivityThread.java:4719)\n\tat android.os.Handler.handleCallback(Handler.java:809)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:166)\n\tat android.app.ActivityThread.main(ActivityThread.java:7555)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)\nCaused by: android.os.TransactionTooLargeException: data parcel size 585232 bytes\n\tat android.os.BinderProxy.transactNative(Native Method)\n\tat android.os.BinderProxy.transact(Binder.java:769)\n\tat android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4652)\n\tat android.app.ActivityThread$StopInfo.run(ActivityThread.java:4703)\n\t... 7 more\nandroid.os.TransactionTooLargeException: data parcel size 585232 bytes\n\tat android.os.BinderProxy.transactNative(Native Method)\n\tat android.os.BinderProxy.transact(Binder.java:769)\n\tat android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4652)\n\tat android.app.ActivityThread$StopInfo.run(ActivityThread.java:4703)\n\tat android.os.Handler.handleCallback(Handler.java:809)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:166)\n\tat android.app.ActivityThread.main(ActivityThread.java:7555)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)\n"
   ],
   "user_comment": ""
}

**Comment by heberjeur** [comment]
This with 10 tabs

**Comment by heberjeur** [comment]
OK I will test it as soon as possible

**Comment by wb9688** [comment]
I could reproduce the crash now

**Comment by heberjeur** [comment]
I have an issue when I open this app and quickly I open videos, it's crashes and restart

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "fr_TN",
   "service": "none",
   "package": "org.schabi.newpipe.debug.tabs",
   "version": "0.18.6",
   "os": "Linux HUAWEI\/DUB-L41\/HWDUB-Q:8.1.0\/HUAWEIDUB-LX1\/155(C185):user\/release-keys 8.1.0 - 27",
   "time": "2020-04-23 21:37",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference\n\tat org.schabi.newpipe.util.AnimationUtils.slideUp(AnimationUtils.java:372)\n\tat org.schabi.newpipe.fragments.list.channel.ChannelTabFragment.handleResult(ChannelTabFragment.java:107)\n\tat org.schabi.newpipe.fragments.list.channel.ChannelTabFragment.handleResult(ChannelTabFragment.java:37)\n\tat org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0$BaseListInfoFragment(BaseListInfoFragment.java:125)\n\tat org.schabi.newpipe.fragments.list.-$$Lambda$BaseListInfoFragment$prYfqK19mXhZc0JDsOoy9kGzYpE.accept(Unknown Source:4)\n\tat io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)\n\tat io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)\n\tat io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)\n\tat android.os.Handler.handleCallback(Handler.java:809)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:166)\n\tat android.app.ActivityThread.main(ActivityThread.java:7555)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)\n"
   ],
   "user_comment": ""
}

**Comment by wb9688** [comment]
@heberjeur: Could you try the new APK from #3476?

**Comment by heberjeur** [comment]
The app don't crashs now but, it's still slow specially when I return to main screen.
In this video you can see also that the channel picture refresh many times

https://youtu.be/HopnSW8b4AI

**Comment by heberjeur** [comment]
This is an other lack of performance, it happens when I enter to video and I return back to the channel
https://youtu.be/CIunWa4fEnQ

**Comment by mhmdanas** [comment]
@heberjeur is this still happening with 0.20.5?

**Comment by heberjeur** [comment]
Yes !

**Comment by Feuerswut** [comment]
Is this still an issue or can this be closed
