### ISSUE TITLE
Use an external download manager

### ISSUE THREAD

**Issue by devnoname120** [TeamNewPipe/NewPipe#268]
It would be nice if I could use ADM for downloading videos instead of the default download manager.

**Comment by theScrabi** [comment]
Yup, I still wasn't able to refactore downloading, but if I am this is one of the things that needs to be done.

**Comment by satiricon** [comment]
How about I add an option to download with an external download manager or the new GigaGet based one?

**Comment by theScrabi** [comment]
Yes sounds god.

**Comment by rmenessec** [comment]
@satiricon, tell me more about this GIgaGet-based download manager? ;)

**Comment by satiricon** [comment]
@rmenessec I'm working on adding better download capabilities to NewPipe adding code from GigaGet. #243

**Comment by rmenessec** [comment]
@satiricon - Oh. Sorry, I misunderstood. I thought you were referencing a new download manager app based on GigaGet--which appears abandoned.

Using GG code in NewPipe does seem like a good move, though.

**Comment by satiricon** [comment]
@rmenessec 

I'll probably make a fork of GigaGet and I'll work on it as a pet project when I get some time.

**Comment by pravi** [comment]
I was going to suggest using GigaGet code, good to see its being considered already.

**Comment by timofonic** [comment]
@satiricon
So there's an Open Source alternative to ADM, good to know! 

Are there a list of download managers? 

Thanks for your interest in making it alive again :D

**Comment by devnoname120** [comment]
While embedding GigaGet in the app is nice, having everything in ADM helps me to keep my downloads centralized, so it would be great if external download manager support could be added nonetheless.

**Comment by satiricon** [comment]
@devnoname120 An option to chooce between the internal or anexternal download manager is in my list. Don't worry about it.

**Comment by theScrabi** [comment]
closing if favour of https://github.com/TeamNewPipe/NewPipe/issues/962
