### ISSUE TITLE
Statistics about using the application.

### ISSUE THREAD

**Issue by IT-Tool** [TeamNewPipe/NewPipe#2689]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It's no secret that now the consumption of video content on YouTube is very high. I would like to receive statistics of your activity on YouTube through this app.
•  How many channels in total and some folders?
•  Which ones do you watch more often?
•  How much time per day is spent watching videos, etc.

**Comment by Stypox** [comment]
I think this would be rather difficult to implement, and it wouldn't add something very useful the app, so I don't think it is worth the effort. My thoughts, though ;-)

**Comment by AnXh3L0** [comment]
I also agree with @Stypox and don't feel like it is useful to have, being possible to implement doesn't mean we should (just my opinion though).

**Comment by TobiGr** [comment]
I also consider this to be not useful for the majority of users and agree with both of you that this should not be added. I'll close this issue for that reason.
However, @IT-Tool, thanks for the input and suggestions!

**Comment by TobiGr** [comment]
Just a thought, this might be an interesting aspect for a child mode. Don't get me wrong, I do not support tracking the children's app usage, but tracking the time spend using NewPipe might be a good feature for parents.
_Off topic_: maybe we should open some projects to keep track of ideas for later features like child mode, offline / data save mode etc.

**Comment by Stypox** [comment]
AFAIK tracking app time is a feature of Android 10, so there is no need to implement it here
