### ISSUE TITLE
Cannot backup a playlist

### ISSUE THREAD

**Issue by darkwarrior3** [TeamNewPipe/NewPipe#2693]
I've changed my phone and I lost all of my playlists because their is no option to backup or share a playlist.
Please consider to add this option.
It'll be very helpful.

Thank you

**Comment by TobiGr** [comment]
You can export your data. Go to the settings > content > export database. This backup contains playlists.

**Comment by dimqua** [comment]
Could we close this issue then?

**Comment by dimqua** [comment]
@TobiGr does it contains subscriptions too?

**Comment by Stypox** [comment]
I think it's ok to keep the question as reference. It is not going to create misunderstandings since it's labelled as "question", not as "bug"

**Comment by theScrabi** [comment]
Faq?

**Comment by opusforlife2** [comment]
FAQ.
