### ISSUE TITLE
Additional Donate option - PayPal

### ISSUE THREAD

**Issue by 11x314** [TeamNewPipe/NewPipe#2698]
Feature request
PayPal Donate

**Comment by Stypox** [comment]
Do you want to donate to NewPipe or to YouTube channels?

**Comment by Stypox** [comment]
Doesn't [LiberaPay](https://liberapay.com/TeamNewPipe/) support PayPal?

**Comment by Vormgear** [comment]
I went to make a donation through libreapay. There doesen't appear to be a direct method to donate using paypal for the newpipe project.

**Comment by opusforlife2** [comment]
@TheAssassin @theScrabi Make a decision?

**Comment by AudricV** [comment]
LiberaPay supports PayPal now (you can see by yourself that it is listed as a way to donate to us). Closing as fixed.
