### ISSUE TITLE
Issue: Closing App doesn't close popup player

### ISSUE THREAD

**Issue by JBird1977** [TeamNewPipe/NewPipe#2700]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [N/A] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Greetings! I would like to report an issue where the popup player doesn't close when NewPipe is closed. The only workaround I found is to restart my phone. 
How to recreate: 
1. Open NewPipe and find a video to play. Make sure you have the option to use the popup player enabled. 
2. Drop focus on new pipe. New Pipe opens video in popup player. 

3. Close NewPipe (on the Samsung models I hit the button to show all apps that are open and I swipe up on NewPipe to close it). 

4. PopUp player still plays. Expanding the player presents no option or ability to close it. Thus the player is now ever present on my phone with no way to remove it unless I restart my phone.

Potential solution would be to create a close button that appears when a user taps on the popup player (similiar to how a user can choose resolution etc. by doing same). Alternatively create an option to allow the popup player to be closed if the app is closed.

**Comment by gkeegan** [comment]
This is an Android thing afaik. When you close an app by swiping it away, it doesn't force close the app the same way going to the app's page in settings and closing it would.

To close the popup player, drag it onto the red X on the bottom of the screen.

**Comment by opusforlife2** [comment]
Fixed by #2907.
