### ISSUE TITLE
verry low Framerate at WebM 720p60

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#2702]
[Example](https://www.youtube.com/watch?v=PD0reW7WtYo)

NP v 0.17.1 and 0.17.3 tested
Android 7.1.1
Device: XT1771

Handles MPEG-4 720p60 and 1080p60 just fine on my 720p60.25 display (framerate according to [CPU info](https://f-droid.org/app/com.kgurgul.cpuinfo)), but stutters noticeably with WebM 60fps (from what I can percieve it's about ≈15fps), but only inside the player, the Android interface is smooth as always.

**Comment by DafabHoid** [comment]
According to [this](https://www.gsmarena.com/motorola_moto_e4_plus-8722.php), your device has a MediaTek MT6737 CPU, is that correct? This chip does not have a hardware VP9 decoder built in ([specifications for MT6737](https://www.mediatek.com/products/smartphones/mt6737)), but VP9 is the codec used when you play Webm video. Your device then has to decode it in software, which is a lot slower as you have noticed.  
So my advice is to stay with MPEG-4 for this device.

**Comment by OffifialMITX** [comment]
Oh ok, yes, this is indeed my SoC. Thank you very much for the insight! ^^

I guess I'll close this now since it's not NewPipe's fault.
