### ISSUE TITLE
Add feature Custom color primary and color accent 

### ISSUE THREAD

**Issue by joliegrace** [TeamNewPipe/NewPipe#2708]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
I think this would be only be used by few users, but it would require two new options and (I think) a fair amount of developer time.

**Comment by blackCauldron7** [comment]
I would really love this feature. Please make this happen some customisation options would be super neat for NewPipe.

**Comment by SameenAhnaf** [comment]
@litetex This issue should be closed in favor of https://github.com/TeamNewPipe/NewPipe/issues/6272#issuecomment-856608962
