### ISSUE TITLE
Take the UI form Timber

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#271]
The background music player is currently only controllable via notification. I don't have time to write a UI for it so why don't take a UI that already exists. What would you guis think if we took te [Timber](https://github.com/naman14/Timber)?

**Comment by Ayukiba** [comment]
Would this mean completely changing the current look?

**Comment by theScrabi** [comment]
No but all the UI ellements that are necesary to build an audio player.

**Comment by FaizKhan5** [comment]
Close this

**Comment by Stypox** [comment]
This has been implemented
