### ISSUE TITLE
[Feature] Functionality to automatically fix video decoding problem

### ISSUE THREAD

**Issue by MatthewR37** [TeamNewPipe/NewPipe#2711]
Hi,

I thought of a potential solution to problem of:
- NewPipe becoming non-functional after YouTube changes their decoding method.

Current fix: 
- Pushing an update that can take over a week to roll out.

My idea:
- A script that tries to download a video and reverse engineers the decoding method. The script would run upon a decoding failure. I don't know how to do it, but I'd imagine it's possible. Pretty much the script would go through the same process the programmer would go through to figure out how to decide the video. 

What do you think?

**Comment by Stypox** [comment]
I was also thinking about a way to work around F-Droid update delay. But I don't think that a script could automatically scrape and understand a webpage by itself: it would have to do many things that only humans can do (e.g. understanding language).

Another option would be to automatically update the extractor inside the NewPipe app, either by rewriting it as a script (and downloading it from a server on every update) or by loading Java classes from a remote server.

But both these two options would be problematic for security

**Comment by PeterHindes** [comment]
You could use a modular parsing system. Such as an array of strings for search, which are fetched from your site every day or 12 hours.

**Comment by Stypox** [comment]
@PeterHindes I'm sorry, I don't understand what you wrote

**Comment by opusforlife2** [comment]
Majorly improved by Newpipe's own repo. Apart from that, there is https://github.com/TeamNewPipe/NewPipeExtractor/pull/297.
