### ISSUE TITLE
Fast forward/rewind buttons in background mode 

### ISSUE THREAD

**Issue by silbopower** [TeamNewPipe/NewPipe#2722]
In background mode:
implementation of buttons or gestures that permits to go forward or backward of some seconds, like it's yet developed in standard mode tapping twice on left (-10") or right (+10") screen side.

As is implemented in podcasts apps where there are 2 main buttons:
+30 seconds
-10 seconds
That should be useful to resume easily some audio content that is lost during the listening.

Another helpful implementation could be a finest scrolling of timeline for long contents, putting time in manual mode or timebar in widescreen when mobile is tilted..

Thanks and btw... AMAZING APP!!

![Screenshot_2019-10-11-11-21-22-324_com google android googlequicksearchbox](https://user-images.githubusercontent.com/56430866/66705103-c9186180-ed22-11e9-8358-2e7b56ac17a8.png)

**Comment by PeterHindes** [comment]
The notification already has this I think.

**Comment by Stypox** [comment]
Yeah, the notification has it, but the background player activity does not.

**Comment by PeterHindes** [comment]
Which file has the background player? I think It could replace one of the duplicate playback speed buttons.

**Comment by gillhash** [comment]
+1

**Comment by Stypox** [comment]
@PeterHindes https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/BackgroundPlayerActivity.java

**Comment by rithans** [comment]
option of rewind and forward (missing in only audio mode in notification screen  /  background video play)

previous version has at least feature of  forward or backward, but now neither from notification bar nor from background play has this option.

its possible to rewind and forward the audio / background video. and if done through finger on timeline, its jumps to far or lesser interval.. which requires intense finger precision.

so would request to add this feature  either in any place or at both place i.e in notification screen, and background screen.

![image](https://user-images.githubusercontent.com/60955553/79634603-13bede80-8189-11ea-98de-1380f6b401d0.png)
