### ISSUE TITLE
My Google account got suspended because of NewPipe

### ISSUE THREAD

**Issue by haistakaavittukaikkisaatana** [TeamNewPipe/NewPipe#2723]
My Google account got suspended yesterday, I was like what the heck is going on. First I got an email from Google saying that I was using 3rd party app outside of Play Store to go around Youtube ads, also it said that my account has been suspended. I got locked out of my Google account, I had to factory reset my phone and create a new Google account.

NewPipe is the only app that I downloaded outside of Play Store, so beware guys.

I really have no idea how they can suspend my account since NewPipe isnt even using any Google account information, it only retrieves the video source.

**Comment by haistakaavittukaikkisaatana** [comment]
Maybe its Google Backup that triggered it, somekind of algorithm that noticed 3rd party app or settings and traced the app, who knows.

**Comment by gkeegan** [comment]
How long have you used NewPipe? I've downloaded hundreds of gigabytes over the few years and have had no issues. Also, what region are you in?

If you have a screenshot of what the email said could you attach it here?

**Comment by TobiGr** [comment]
That sounds serious. Could you please show us the mail content?

**Comment by haistakaavittukaikkisaatana** [comment]
Unfortunately I dont cant access my Gmail anymore since its suspended, and I forgot to take a screenshot, Im sorry.

Im from Finland, and Ive been using NewPipe around 2 weeks.

I didnt install NewPipe yet after factory resetting my phone, I will stick to default Youtube app for now.

And I didnt download anything with NewPipe, only used it to watch videos.

**Comment by TobiGr** [comment]
Hmm. That's bad and I am sorry for you. I have never hear of this happen because of NewPipe. You can try these [steps to restore your account](https://support.google.com/accounts/answer/40695?hl=en).

**Comment by haistakaavittukaikkisaatana** [comment]
I tried to restore my account by using my phone number, but I was unable to restore it due to violation of Googles terms.

Oh well, its not the end of the world though.

**Comment by undeadfox** [comment]
> and Ive been using NewPipe around 2 weeks.

Have you used subscriptions import/export?

**Comment by haistakaavittukaikkisaatana** [comment]
No I didnt use that feature.

**Comment by haistakaavittukaikkisaatana** [comment]
Now that I think this more it couldnt be Google Backup either because I have it set to manual to save some battery life, and I didnt backup my phone yesterday.

**Comment by Iolaum** [comment]
How old was your Google Account when it was suspended? Maybe your usage was irregular enough to trigger something related to abuse detection?

**Comment by duiker101** [comment]
That's crazy, does this mean they could ban your account for using ublock on youtube?

**Comment by resynth1943** [comment]
Downvoted because this is shocking. I'm so sorry to hear you've gone through this bullshit.

**Comment by pampasdev** [comment]
@duiker101 that day will also come now I think.

**Comment by resynth1943** [comment]
Ask them what evidence they have that proves you've been ~~a naughty boy~~ using NewPipe.

**Comment by duiker101** [comment]
@resynth1943 ask who? Google is notoriously hard to contact. And when you do they don't really car. Remember, with Google you are not a customer but the product.

**Comment by resynth1943** [comment]
@duiker101 I've dealt with companies like this before, GitHub and NPM. Just threaten them with GDPR, and they'll run a mile for you.

**Comment by resynth1943** [comment]
Also, I'm going to be old-fashioned and *say what I see*, and here, I can see spyware.

**Comment by hkzlab** [comment]
@haistakaavittukaikkisaatana Did you have Play Protect enabled in the play store? That indeed scans the applications you have installed in your unit, afaik it also sends info to Google for analysis

**Comment by iyesin** [comment]
@hkzlab Play Protect is enabled by default on new devices.

**Comment by hkzlab** [comment]
@iyesin Which is a good way for Google to know that he installed NewPipe...

**Comment by mngad** [comment]
@iyesin can you disable it?

**Comment by iyesin** [comment]
@hkzlab true. As same as other "misbehaving" applications.

**Comment by dhruvasagar** [comment]
@mngad Yes we can disable it, I just did. You have to click on the 'settings' button on the top right and disable it.

**Comment by iyesin** [comment]
@mngad sure. Both in Google account settings and in Play Store settings. This, most likely, would prevent some critical applications to start. (i.e. some banking apps and Google Pay).

**Comment by dhruvasagar** [comment]
@iyesin @mngad Google Play Store and Chase app are both able to start. Not sure about others.

**Comment by resynth1943** [comment]
This was bound to happen someday, anyway. I use YouTube Vanced and NewPipe, so I guess that's double the risk? :stuck_out_tongue:

So, from what I can see here, users that use third-party applications that do naughty things (that aren't on the Play Store) should disable Play Protect as a start. That scans all your apps, as suggested by a previous commenter. 

I'll definitely be keeping my ear to the ground on this one. Let us know if Google gets back to you.

**Comment by iyesin** [comment]
@dhruvasagar I wasn't taking about Play Store. I recently had bad experience (just silent crash on login screen) with Commerzbank app.

**Comment by echelon** [comment]
This is getting a lot of attention as the top-voted submission on Hacker News. It'll draw the attention of Google engineers, which can hopefully help corroborate and assist in fixing this issue. 

Let's hope they reach out and offer some background on this.

**Comment by mngad** [comment]
Especially to OP

**Comment by ssarkisy** [comment]
@resynth1943 so they scanned the apps, found NewPipe, sent the info to Google servers and then decided to "protect" the user by banning him for some terms violation. Nice protection. I feel safe now.

**Comment by mrusme** [comment]
From my experience it helps to have a paid Gsuite account in order to not lose access to your own stuff just like that. I know this isn’t great, but quite frankly speaking the Gsuite support is usually super friendly and helpful.

**Comment by sova** [comment]
I think Larry and Sergey would actually be pretty frustrated with an outcome like this.  Anybody got their e-mail?

**Comment by dessant** [comment]
@mrusme, government regulation that forces these monopolies to give users the right for due process regarding their accounts is also helful. Someone losing their account because they have used an app that does not align with the business interests of Google is sickening.

Actions like these can ruin people's lives, and platforms that act with such ruthlessness should bear the responsibility.

**Comment by resynth1943** [comment]
@sova They won't, but hopefully the publicity of this will scare them.

**Comment by hkzlab** [comment]
@notpushkin I use microG on all my devices that still have a tie to google services (and the rest do not have even that, totally google free). So I'm a huge proponent of it even between colleagues and family.

That said, it's important to remember that even microG sends information to google if so configured (e.g. if you add a google accound, or, worse, if you installed a patched Play Store, which is the default with a NanoDroid installation, i think).

So, well, it's not a panacea :(

**Comment by ganeshkrishnan1** [comment]
Scare Google? They give two shits on a popsicle about this. Threaten them with gdpr? By emailing No-reply@google.com?

**Comment by wodim** [comment]
I still see absolutely no proof about your account having been banned. Show us a screenshot at least of the message you see when you try to log in.

**Comment by TobiGr** [comment]
@Redirion That's what I though, too. Please give us evidence @haistakaavittukaikkisaatana (like the email). We might need to lock the conversation until we now this is not a fake.

**Comment by EVODelavega** [comment]
I'm not sure if it's fair to dismiss this as "a troll". For all we know, it might be a genuine issue someone encountered, which wasn't casued by NewPipe, but rather a rather draconic implementation of Google's ToS compliance stuff. The fact that @Redirion just off-handid brands this report as trolling without evidence is concerning to say the least.

**Comment by Talal916** [comment]
Heavy accusation and really damaging to NewPipe and similar apps like Vanced. Without any evidence, this shouldn't be taken seriously.

**Comment by villesinisalo** [comment]
Warning: This story gives me a worrying tickle on the troll radar. Not least because OP's handle is essentially a string of random Finnish-language profanities (something like: "F**k you all, d*mn it!").

**Comment by samboy** [comment]
The matter in question, if true, is a serious matter. However, without the Google account name, screenshot of the account being locked, or any other evidence besides the original poster’s claim, we can not verify the claims, and they very well could be falsified. 

Just because an unverified claim supports a world view we have does not mean we should believe it credulously.

**Comment by hkzlab** [comment]
@villesinisalo Or maybe the person was so frustrated that he/she could not think of anything else when registering a github account to post this!
 But yes, we need proof of this before we start worrying or people start disabling their play protect feature (yep, my fault for suggesting it).

**Comment by russeg** [comment]
> First I got an email from Google saying that I was using 3rd party app outside of Play Store to go around Youtube ads ...

No you did not. Google does not reveal reason for account suspensions. 

Fake.

**Comment by user849281** [comment]
Google logs all Android apps start time, namespace, device etc. installed from Google Play, F-Droid etc. You can see it in Google My Activity: https://myactivity.google.com/

**Comment by graynk** [comment]
> I got an email from Google saying ... said that my account has been suspended. I got locked out of my Google account

So where did you receive this email, if your account has been suspended and you got locked out?

**Comment by shr1k** [comment]
> @villesinisalo Or maybe the person was so frustrated that he/she could not think of anything else when registering a github account to post this!

Except the account has been around since August 2019 and they've got some minor activity *only* in this repository. I'm dubious about the claim being made, since I've been using NewPipe quite liberally for the last year or so on my Play Protect-enabled stock Android device without any problems.

**Comment by DeepLinkCode** [comment]
Maybe Google Found a way to block NewPipe. ~~ in Google-Free ROM only this app way.

In Stock ROM there many hidden service run by Google which may trigger such Terms Violation Condition in contrast with PlayProtect.

Once a blog about NewPipe Said :-

> Given how this app is treading on murky waters, it remains to be seen how long before Google attempts to block it, one way or another. That said, Google can’t do so easily without potentially breaking features that other blessed third-party apps use. And since NewPipe is open source, it won’t be too hard for others to take up the torch to keep it moving forward.

**Comment by TheAssassin** [comment]
**Guys, this has gone too wild**.
Please stop posting off-topic, please leave analysis to the team. The amount of messages is making it nearly impossible to grasp what's relevant for @haistakaavittukaikkisaatana's report and what's not. Nobody cares what you think "Larry and Sergey" think (sorry whoever posted that, it sounds harsh, but it's a good example for off-topic).

We don't know for sure what's going on as we have zero evidence so far (the OP can't provide any, the reasons sound reasonable), and even if this happened to the OP, this is not the end of the world. Even the OP says it's okay.

**Lessons learnt for now:**

  * Keep your phone as proprietary-service-provider-free as possible. You can never know what's really going on. Only free implementations (like MicroG) allow you to check the source code. I've had an Android phone for around 4 years (my first real smartphone, I was pretty late), and I've always kept it completely Google-free. It's doable!
  * Don't rely too much on your Google account. Use separate mail/messaging/... providers or at least different accounts. Ideally you use privacy-friendly services for mail and messaging, and especially nothing that relies on a phone number...
  * Don't share too much information with things like Google.
  * For <god|not god|multiple gods|Spongebob|Superman|Jebus|whoever>'s sake, **make backups!** Not being able to provide evidence any more is one thing, not being able to use services any more or even data loss are more than just annoying.

Please keep the discussion within here limited to @haistakaavittukaikkisaatana's original report. We'll clean up this thread soon by hiding or deleting non-related messages.

This is no offense and I'm sorry if this sounds a bit harsh. It's a maintainers' measure to reduce the heat, analyze based on **facts** and allow the devs to work efficiently. We do not try to censor you in any way, this is just not the place for this type of conversation.
I can highly recommend joining our IRC channel #newpipe on Freenode to continue this discussion. That's what IRC is meant for. And I can join you speculating about what Google's founders would've thought about this situation!

@TobiGr @theScrabi let's clean up a bit.

**Comment by coffeewine** [comment]
noice bait /g/entle

**Comment by spinda** [comment]
@haistakaavittukaikkisaatana

> I tried to restore my account by using my phone number, but I was unable to restore it due to violation of Googles terms.

Could you please post a screenshot of this message?

**Comment by gkeegan** [comment]
@spinda As OP said, they no longer have access to the account to get a screenshot.

**Comment by TheAssassin** [comment]
@gkeegan that's the point. @spinda was asking whether @haistakaavittukaikkisaatana could *try again* to unlock it, which we know will likely yield in an error message. @spinda wants to see a (anonymized!) screenshot.

**Comment by Noiwex** [comment]
If I remember correctly, NewPipe doesn't even require you to input any credentials. Seems like someone trying to spread FUD or trolling.

**Comment by TheAssassin** [comment]
@Noiwex you seem to have missed the point. It's not about missing credentials *for NewPipe*, but Google having banned someone's account for ToS violation supposedly caused by using NewPipe, which rendered the phone unusable. The OP couldn't log into any other Google service any more. Not just NewPipe.

**Comment by woohooatb** [comment]
> My Google account got suspended yesterday, I was like what the heck is going on. First I got an email from Google saying that I was using 3rd party app outside of Play Store to go around Youtube ads, also it said that my account has been suspended. I got locked out of my Google account, I had to factory reset my phone and create a new Google account.
> 
> NewPipe is the only app that I downloaded outside of Play Store, so beware guys.
> 
> I really have no idea how they can suspend my account since NewPipe isnt even using any Google account information, it only retrieves the video source.

Post proofs or GTFO faggot

**Comment by gkeegan** [comment]
@TheAssassin Oh I see now. Thanks for explaining. 

@woohooatb Please don't use that language.

**Comment by resynth1943** [comment]
I really can't reproduce this, or say it's happened to me, but I'm not trying to invalidate the OP.

I've had NewPipe *and* YouTube Vanced (another naughty YouTube app) on my Android device(s) for many years now (with Play Protect active) and I haven't ever got this (an account suspension). I'd be interested to hear more about where you installed it from (it may have been a virus) and other determining factors.

Many thanks,
resynth1943

**Comment by Salamandar** [comment]
Same here @resynth1943 , I've even been using Youtube to open Newpipe (for my subscriptions). I've been developping Android apps with embedded YT videos (those shouldve shown YT ads I guess), and no warning from Google whatsoever.

**Comment by danialbehzadi** [comment]
WTF Google? 😒

**Comment by TheAssassin** [comment]
This more and more looks like a (somewhat successful) attempt to troll. Please don't be fooled. There's tons of evidence that disproves what the OP describes. Also, the OP's statements contradict in a few ways. The Internet™ think so, too. And the OP's nick also makes this pretty obvious (once you have the translation).

P.S.: I still strongly recommend anyone to read  https://github.com/TeamNewPipe/NewPipe/issues/2723#issuecomment-541767279, they tips I gave are applicable in general.

**Comment by SuperSandro2000** [comment]
Didn't find a better translator but see yourself
https://translate.google.com/?text=haistakaa%20vittu%20kaikki%20saatana

**Comment by theScrabi** [comment]
Uff.

**Comment by jimmycheck** [comment]
*oof ;p

**Comment by resynth1943** [comment]
Ouch, that hurt after getting most of my comments hidden lmao

**Comment by theScrabi** [comment]
Well I thought I'd have to say a last word about the whole situation that will contain an assumption as well as a wise word  for rounding up the whole discussion.

**Comment by KeepBotting** [comment]
so as of yet there is no confirmation that this happened due to NewPipe's presence on an Android device, or indeed that it happened at all?

**Comment by TheAssassin** [comment]
@KeepBotting no, there isn't. See also https://github.com/TeamNewPipe/NewPipe/issues/2723#issuecomment-541913082.

As said, if this was an attempt to troll, it had some success. If not, the OP is free to post a reaction. But I doubt they will.

**Comment by ivanosh** [comment]
fake until you provide us email/screenshot/support chat

**Comment by TheAssassin** [comment]
I'm tired of reading more of these well established statements. A lot of people already wrote that above. I marked a lot of it as off-topic.

The issue has been closed, so there's no need to keep discussing. To avoid any further spam to the participants in this discussion, I'm going to lock this conversation for now.

Thanks to everyone who analyzed this story.
