### ISSUE TITLE
Newpipe Default player issue

### ISSUE THREAD

**Issue by koli6faizakhan** [TeamNewPipe/NewPipe#2728]
Hii Iam using this app in smart TV. all working is fine but only one issue this app.That issue is Newpipe default player properly not control Tv remote so reslove next update.

**Comment by Stypox** [comment]
@Alexander-TX is this fixed in your PR #2701 ?

**Comment by Alexander-TX** [comment]
@Stypox Yes, specifically in commits 8e0926be51 (overall UI) and ca843f1779bcf (seek bar). You also need commit fe3b76534469 (which makes NewPipe actually recognize all modern TV devices as Android TV).

**Comment by koli6faizakhan** [comment]
Hii bro Iam not understand this codec. So please fix it default player issue next update.
