### ISSUE TITLE
Please increase the `paddingbottom` for the seekbar.

### ISSUE THREAD

**Issue by treble2019** [TeamNewPipe/NewPipe#2730]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Please increase the `paddingbottom` for the seekbar. In landscape orientation it is so low that scrolling along the seek bar becomes very difficult. Say for example in a tablet.

Thanks

`app/src/main/res/layout/activity_main_player.xml
`

**Comment by Nico-late** [comment]
I dind't really understand for which device size the issue is really annoying ? Do you  think the paddingbottom should be increased for all tablets in landscape orientation or only the very big ones ?

**Comment by treble2019** [comment]
I mean in my hdpi resolution phone with BEZELS -  landscape mode has difficulties to scroll video. May be everyone is modern with bezelesss phones :-(

Vlc also have a reasonable padding. Please view a video in vlc and check. Thank you

**Comment by TobiGr** [comment]
@treble2019  Please post a screenshot

**Comment by treble2019** [comment]
Sorry about the delay. 

Top image with NewPipe

![1](https://user-images.githubusercontent.com/52563208/75684161-8a1a8680-5c98-11ea-9141-27617293913c.png)

with VLC. (Please note: This is not meant to offensive to compare different software. Mainly that touch screens are mainly designed to be used mainly portrait. IIRC, if you rotate your phone display by 180°, using it is uncomfortable because of the way, pixels and touch sensors are oriented). A small offset would mean people with 'butter or large' fingers can also scroll easily.

with VLC:

![2](https://user-images.githubusercontent.com/52563208/75684370-f301fe80-5c98-11ea-9bbd-5ffbdd0e265f.png)
