### ISSUE TITLE
toggleorientation should be directly displayed on the mainplayer window

### ISSUE THREAD

**Issue by treble2019** [TeamNewPipe/NewPipe#2731]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

On the main videoplayer there is (left to right)

Title      360p   1x    playlist    ^   

Fit        headphone    +   Toggle Share

I would recommend that the toggle be directly available instead of 2-step process. Press the 'down or open' extra stuff and then 'Toggle'. Most people fix their phones in 'portrait' - then every time while viewing video - they need to do more work  to turn orientation.

What do you think?

![screencap2](https://user-images.githubusercontent.com/52563208/66935087-caf06680-f03b-11e9-9d62-30cda1d22e41.png)

PS: I made the toggle button very big for my convenience. You could have regular size.

**Comment by Stypox** [comment]
I don't agree, since the button does not have to be used every time a video is opened: the button was designed to save its state once used, so it would have to be clicked once and from then on the video would always open in portrait mode.
