### ISSUE TITLE
Should we found a NewPipe e.V. (registered association) to support and maintain NewPipe?

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/NewPipe#2732]
@theScrabi, @TobiGr and I have been discussing this idea for a while. There are many reasons that justify founding a public association to support and maintain the NewPipe development. As we're Germans, we came up with the idea of funding a NewPipe Förderverein e.V. (a registered association in the German jurisdiction). This is of course not meant to be for German or European people only, it'd be open for everyone to join.

There are many free/open source software projects that founded an e.V. to sustain and organize their projects. The most prominent example is probably [KDE e.V.](https://ev.kde.org), the organization backing the [KDE desktop and all associated projects](https://kde.org). Further examples involve [J and Beyond e.V.](https://jabev.de) or [SfE e.V.](https://sfe-ev.org/), internationally there's e.g., GNU with the FSF, the Apache Software Foundation, the Document Foundation, the Linux Foundation and many more.

For us, the advantages of having an e.V. are mostly based on legal thoughts. A registered association in Germany is a really well-regulated form of non-profit organization. The board ("Vorstand") cannot do what it wants to, as the members have strong instruments to control them . They're organized in a very democratic way. Developers as well as users can become members and make better decisions what ways the project should go.

Legally, there's plenty advantages as well. Such an assocation could:

- host services that support development and marketing (that includes our website)
- receive and manage donations (allowing for more transparency *who* you're donating to and *what* is done with the money)
- perhaps even sell and/or distribute merchandise (stickers, shirts, ..., with our logo)
- protect the NewPipe trademark
- basically handle all legal issues without having to have some random private persons that could be held liable
- host conferences on NewPipe (and free software in general) and invite people from all over the world (maybe even fund their trips, based on donations collected for these events)
- send members to conferences, paying for their travel costs

Of course, this comes at a price. First and foremost, founding an association is not for free. You have kick-off costs (you have to pay a notary that will take care of registering you with the court that is responsible for your district). Also, writing a Satzung (constitution) is a lot of work and needs to be reviewed to be safe (we already prepared a half-finished draft and we already discussed the rest of it, we'd just need to finish the final text and have some lawyer have a look). You need to have a board of members which volunteer to do all the administration.

Another difficult bit is to decide how the software project and whether the association should take over governance or not. Doing so means more democracy and allows users to "control" the project, but comes at the risk to put off maintainers (they put in all the work and are most experienced with the project and code, so they usually have the last word, which usually is a good idea). These and other issues have to be ruled out before investing time and money into founding some sort of organization to sustain the NewPipe project and keep up the awesome work.

This issue is not a public announcement that we're going to fund such an association. It's rather a "we thought about it, started the preparations, but want to hear some feedback from you" kind of issue.

**What do you think? Would you join such an association? Would you be willing to help fund it? Please feel free to post your thoughts below!**

**Comment by TheAssassin** [comment]
CC @TobiGr @theScrabi #2668

**Comment by theScrabi** [comment]
As @TheAssassin said I'm fully behind his work. We are currently getting abouy 40€ a week of donations. I am a little concetned of this money, as most of it goes in my pocket atm, however I don't feel well with that, as I am not making NewPipe, but you do. Letting the NewPipe foundation having its own bank account would mean this money would go to that place and not my private account. Which is one of the issues this foundation can solve.

Overall I think this is a useful foundation for many things. Which is why I highly support this project.

**Comment by Gymcap** [comment]
This sounds like a very well planned out idea. It seems as if NewPipe is growing up and is getting bigger and bigger every day. It makes me happy to see this on the horizon.

I would be thrilled to both join the association, and to help fund it with donations.

**Comment by treble2019** [comment]
Good to do this association thing. But could @theScrabi  please comment on issue addressed in https://github.com/TeamNewPipe/NewPipe/issues/2719

**Comment by Poolitzer** [comment]
I very much like the idea of having an e. V. behind Newpipe. It will make integrating new maintainers in the project easier as well.

**Comment by Poolitzer** [comment]
An association has been founded in Germany. We are working on an online presence.

**Comment by ecurrencyhodler** [comment]
Hi NewPipe Team. It's terrible to hear what happened to your funds with Bountysource. 

If you are looking for another platform to post bounties, I'd like to suggest our bounties site: https://community.sphinx.chat/bounties. 

It's bitcoin-based but we also offer a way for people to pay for bounties outside of our platform. 

If you're open to it, it may be worth while to also consider using bitcoin (although I completely understand any hesitancy and resistance to it). But you'd be able to raise funds in Bitcoin without using a custodian and using multisig where ownership can be split across multiple people. Then you can easily transfer it to hunters all over the world. 

If any of this is something that interests you, please feel free to reach out. I'd love to help you out in any way that I can.
