### ISSUE TITLE
NewPipe (Web Version)

### ISSUE THREAD

**Issue by joek85** [TeamNewPipe/NewPipe#2733]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hello, i would like to offer my project:
https://github.com/joek85/trooveo

It has similar functionalities like NewPipe, made using VueJs (Front-End) and Node (Back-End), Please check it out and help us improve it.
I remember i was reading somewhere that NewPipe needs some backend help for downloads, so i hope my project can helps.
If you feel that my post isn't belong to here, please feel free to let me know so i can remove it.
Enjoy!

**Comment by PeterHindes** [comment]
This seems to be entireley unrelated to NewPipe. The NewPipe backend can be found [here](https://github.com/TeamNewPipe/NewPipeExtractor] if you would like to contribute. Your project seems quite nice though. Thanks for sharing.

**Comment by Pentaphon** [comment]
The only web support I would like to see on Newpipe is invidious account support to sync subscriptions.
