### ISSUE TITLE
Subscribers count of subscribed channels broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [TeamNewPipe/NewPipe#2734]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

The subscribers count of subscribed channels will only update in the subscriptions UI when the channel page associated to it is loaded.

**Comment by Stypox** [comment]
Closing in favour of #2088
