### ISSUE TITLE
[General Polish] Square Playlist Thumbnails Are Zoomed Instead Of Fit

### ISSUE THREAD

**Issue by PeterHindes** [TeamNewPipe/NewPipe#2735]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

The square playlist thumbnails are cropped and have the edges missing. This may also be an issue with video thumbnails, however I haven't tested that yet.

<img src="https://i.imgur.com/7tkqA0k.png" height="150" />
<img src="https://i.imgur.com/LMWW1Cr.png" height="80" />

[An Example](https://www.youtube.com/playlist?list=OLAK5uy_nUqtdb0l_KweNUGw1l63QRQwYczMrxneo)

**Comment by opusforlife2** [comment]
They seem fit now. Can you confirm?
