### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by unknowndelicateboy** [TeamNewPipe/NewPipe#2740]
Bug: disabling the watch history does not disable the playback positions.
FR: add option to disable the playback positions only.

**Comment by Stypox** [comment]
This can already be done, just use the "Positions in list" option

**Comment by unknowndelicateboy** [comment]
@Stypox i disabled the positions in list and its still on, it is a bug not something you can switch on and off.
app version 0.17.3

**Comment by Stypox** [comment]
You probably need to reopen the app
