### ISSUE TITLE
Can't download to external SD card

### ISSUE THREAD

**Issue by charlottesweb** [TeamNewPipe/NewPipe#2741]
Apparently this problem still exists. Using Samsung TAB-A with Android 9 and Newpipe 0.16.2 

Error message is: Code 1003. Action denied by system. Java.ioexception: Permission denied. 

As a workaround, I download YT videos to device memory, then move to the SD card.

**Comment by gkeegan** [comment]
Is SAF enabled in NewPipe's downloading settings?

**Comment by TemporaryAccount0x1** [comment]
> Newpipe 0.16.2
there's your Problem right there. use the latest version and activate SAF in the settings.

**Comment by charlottesweb** [comment]
Forgot to mention that I don't find SAF in download settings. It isn't there.

**Comment by gkeegan** [comment]
Oh. As @TemporaryAccount0x1 said, update to the latest version of NewPipe.

**Comment by charlottesweb** [comment]
Checked my cell phone which uses Android 7.11 and which version of Newpipe was installed. It was 0.17.3

That version is not offered from F-droid on my tablet, only version 0.16.2 which I am using. 
So I found APK 0.17.3, downloaded and installed it onto the tablet. NOW SAF option is there and I turned it on. And, I can now download directly to the SD card. :)

**Comment by gkeegan** [comment]
That's good that it works now then. As for F-Droid not showing 0.17.3, are you sure it was "NewPipe" and not "NewPipe Legacy"? Legacy's latest version there is 0.16.2, so that would explain it.

**Comment by charlottesweb** [comment]
On the tablet in F-droid, when I searched for NewPipe, there is a NewPipe Legacy for OS versions 4.x and NewPipe Lightweight YouTube Frontend. I chose the latter and it offers 0.16.2
When I scroll down to Versions and touch on that, it shows 0.16.2, 0.16.1 and 0.16.0 from top to bottom. The last entry is 0.17.3 "Installed" because I found the APK online and installed it. 

So, the current version 0.17.3 was not offered. The version of F-droid is 1.7

Anyway, thanks for your help!

**Comment by Stypox** [comment]
This is what I see on F-Droid... have you updated the repositories?
![Screenshot_20191021-003313](https://user-images.githubusercontent.com/36421898/67167465-96adda80-f39a-11e9-8e47-40ddaa9e3fb7.png)

**Comment by charlottesweb** [comment]
Hi and thanks for the tip. Apparently one needs to force updating of the repositories. The other day when I opened F-droid it looked like it was updating, but it seems that was not the case. So, I just now tapped on Updates and when done, I see that NewPipe is now offering version 0.17.3 :)

Regards.
___________________
October 20, 2019 3:35 PM, "Stypox" <notifications@github.com (mailto:notifications@github.com?to=%22Stypox%22%20<notifications@github.com>)> wrote:
	This is what I see on F-Droid... have you updated the repositories?
 (https://user-images.githubusercontent.com/36421898/67167465-96adda80-f39a-11e9-8e47-40ddaa9e3fb7.png)
