### ISSUE TITLE
Filter clickbait content

### ISSUE THREAD

**Issue by mightymiff** [TeamNewPipe/NewPipe#2743]
Thanks for this software as it makes Youtube (almost) usable again.

This has veen brought up, but it did not receive enough attention.  Advertisements are only half the problem. Useless, vapid, and maliciously appealing "content" is at least as big a problem as ads ever were. The list of content viewable from the Trending page is unsurprisingly a good example of the kind of "content" I am referring to here. The issue is not with this page _per se_, but the fact that users must contend with garbage like that for every query with no ability to filter it out. It is, quite frankly, intolerable.

**My point**:
It is ***essential*** for users to be able to filter out low quality and malicious content from the platform, permanently.  I do not want **you** to filter it, but to prioritize making it filterable via a whitelist/blacklist method, or through exposing the ranking function. Technology exists to rank creators based on the quality of their content and identify [clickbait](https://github.com/LorenzoNorcini/Clickbait-Detector/blob/master/clickbait.dat). Do you not use a spam filter for your email? Why aren't we using one here?

**Comment by theScrabi** [comment]
How should we build such a filter? How will we know what is clickbait and what is not?

However the idea you bring up is not bad. I've seen clickbati protectors. They are plugins for firefox that don't show you the thumbnail the crators gave the video, but instead show an arbitrary thumbnail from the video. This way at leaset the "thumbnail clickbait" is prohibited. I would guess this would make a valuable addition to NewPipe :)

**Comment by Stypox** [comment]
> They are plugins for firefox that don't show you the thumbnail the crators gave the video, but instead show an arbitrary thumbnail from the video.
See #2505 (and maybe #2506, to repolace all-uppercase titles)
The ability to blacklist videos and channels was proposed in #1815

**Comment by Stypox** [comment]
Closing in favour of #1815. Also, thumbnails can be disabled from settings
