### ISSUE TITLE
[Feature Request] Add playlist as main page

### ISSUE THREAD

**Issue by eomobile** [TeamNewPipe/NewPipe#2749]
How can we add a playlist instead of trend videos

example https://www.youtube.com/playlist?list=PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj

**Comment by TobiGr** [comment]
I moved this to the correct repository. @eomobile Can you please check whether a related issue already exists?

**Comment by Stypox** [comment]
@TobiGr this is a duplicate of #1781
