### ISSUE TITLE
Content Warning  

### ISSUE THREAD

**Issue by niuyaweiqq** [TeamNewPipe/NewPipe#2750]
youtube_url:  https://www.youtube.com/watch?v=m5dnjPadgPU
errorinfo:This video may be inappropriate for some users. Sign in to confirm your age

Is there any good solution? Please enlighten me. Thanks

**Comment by Stypox** [comment]
For me that video works

**Comment by opusforlife2** [comment]
@niuyaweiqq Bug report, if it's still happening.
