### ISSUE TITLE
[Feature] "Open channel" in long press menu

### ISSUE THREAD

**Issue by milklineep** [TeamNewPipe/NewPipe#2751]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
(N/A: no bug reports)

Hello!
I usually have the following flow to open a channel I'm subscribed to: Subscriptions tab -> Open Stream -> Open Channel. But a broken video (e.g. a Premiere or Premium/Red) breaks this flow. Therefore I would like you to consider adding an option to open the associated channel from the lomg-press menu for more convenience. Sure, I can do a search and open the channel; it's just more convenient (and maybe more data-saving?) to do it this way.

I know the longterm goal is to get rid of the long-press menu entirely but I still think this is a useful function whether the long-press menu exists or not.

Steps to reproduce:
1. Subscribe to TheFatRat
2. Attempt to open the channel from the Subscriptions tab

**Comment by Stypox** [comment]
Couldn't you just open the channel from the subscribed channels list?

**Comment by milklineep** [comment]
Oh yes true haha never mind then
