### ISSUE TITLE
More subtitle options 

### ISSUE THREAD

**Issue by underlineGalaxy** [TeamNewPipe/NewPipe#2753]
• [x] I carefully read the contribution guidelines and agree to them.
• [x] I checked if the issue/feature exists in the latest version.
• [x] I did use the incredible bugreport to markdown converter to paste bug reports

I would like to request a few features regarding subtitles:

- allow for download of the auto YouTube generated ones (automatic translation)
- allow so that I can hardcode the subtitles on the video

Thats it. It would greatly my (and I believe of others) watching experience, thanks

This might be similiar to  https://github.com/TeamNewPipe/NewPipe/issues/1329

**Comment by leechunkit** [comment]
> allow for download of the auto YouTube generated ones (automatic translation)

It works for me for this [video](https://www.youtube.com/watch?v=Yz09DG-LgpQ) using version 0.19.5.

**Comment by leechunkit** [comment]
> hardcode the subtitles on the video

By this, do you mean hardsubbing a downloaded video?

**Comment by opusforlife2** [comment]
Bullet 1 is there. Bullet 2 has been rejected as too large in scope.
