### ISSUE TITLE
Video start delay - long buffering - player hangs

### ISSUE THREAD

**Issue by ThaChillera** [TeamNewPipe/NewPipe#2754]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi, 

Im running into a newpipe issue with my device (samsung galaxy s7 edge). 

When I play a video for the first time, its stuck loading the video for the first 20 seconds or so. Sometimes before the video starts, sometimes after the first 5 seconds (ish) of the video. After stopping and starting the video again the loading period isnt required anymore. This never happens when I play a video in 'background' mode.

I experience this issue on every wifi network I'm on, and other phones dont have this behaviour. I also don't have this behaviour in the youtube native or web app, so its definitely not my internet speeds.

Thanks for your time, I hope this can be resolved

**Comment by Fusseldieb** [comment]
Also a S7 Edge owner here. I don't know if this happens only on our model, but basically what happens is following:

- I open a video
- The loader begins spinning
- ... and spins
- ... and spins
- And after 10-20 seconds it decides to play (somethimes even longer than that)

A workaround is following:

- Open a video
- The loader begins spinning
- <Change the resolution to something else than the selected one>
- It begins playing straight away

**Comment by dotslasher** [comment]
I have the same issue. But on a galaxy s10 plus.
Doesn't happen on YouTube original app, or on YouTube vanced. 

On newpipe the loading takes forever. 20 plus seconds.
The white progress icon keeps spinning. 
If I interrupt it and play the video, it will immediately start. 
If I don't do anything it will take a while before it automatically starts. 

Is there anything I can provide to help you guys analyse the issue?

**Comment by ThaChillera** [comment]
I've also tested this on an s9, it doesn't have these issues

**Comment by Z3ROGRAV1TYx** [comment]
Same issue on lgv40

**Comment by seanssel** [comment]
Same issue for me on the LG G7 ThinQ. I have to manually select a lower resolution to start playback.

**Comment by dotslasher** [comment]
Seems solved since 0.17.4

**Comment by ThaChillera** [comment]
I still have this issue in 1.7.4, f-droid version

**Comment by dotslasher** [comment]
Yes I spoke too soon. First video worked. Then had the issue with all
others after that.

Op di 12 nov. 2019 10:53 schreef ThaChillera <notifications@github.com>:

> I still have this issue in 1.7.4, f-droid version
>
> On November 12, 2019 12:03:07 AM GMT+01:00, dotslasher <

**Comment by ThaChillera** [comment]
If one of the devs can give me pointers on how to see what the loading gets stuck on, I'd be happy to take a look. I've already looked at the code but don't really understand iwhere to start looking, the ExoPlayer isn't the right spot I think, and I can't find a 'youtubeservice' as can be derived from [the beta docs](https://teamnewpipe.github.io/documentation/03_Implement_a_service/)

**Comment by Z3ROGRAV1TYx** [comment]
@ThaChillera If not already, I find I encounter more issues with webm playback. Still some issues with mp4 but nowhere near as much as webm

**Comment by Stypox** [comment]
@TheChillera the YouTube extractor service is located in the NewPipeExtractor repo: https://github.com/TeamNewPipe/NewPipeExtractor/
Anyway the problem probably does not lie there, since it happens randomly after the extractor has done its job (i.e. extracting the urls)... But who knows ;-)

**Comment by opusforlife2** [comment]
Still an issue, guys? Stypox updated Exoplayer in May, which made videos load much faster.

**Comment by grravity** [comment]
I've actually noticed more hangups and trouble playing videos personally, I feel like more videos than ever just don't want to play now. Was gonna come comment, just couldn't find this thread and have been a little distracted lol

**Comment by opusforlife2** [comment]
What about the unified player apk? There as well?

**Comment by wb9688** [comment]
@grravity: Not playing at all or playing after a long time of waiting? If the first, see #2415.

@opusforlife2: That shouldn't change anything here.

**Comment by grravity** [comment]
Both actually but mainly the first, thanks

**Comment by wb9688** [comment]
Then we should still keep this issue open for the latter

**Comment by ThaChillera** [comment]
I still experience this issue, version 0.19.8. The workaround of changing a setting (resolution, subs, anything) still helps to start playing instantly after the change

**Comment by opusforlife2** [comment]
And what about on 0.20.0?

**Comment by ThaChillera** [comment]
Seems like its fixed for me. Performance is similar to an S9 (that didn't have this issue. First video opens in ~5 seconds, videos after that in a second.

Closing issue

**Comment by opusforlife2** [comment]
Thanks for confirming!

**Comment by werjany** [comment]
Same problem on Android 12 (Xiaomi Mi Note 10, MIUI 13), NewPipe v0.22.1
It buffers forever when clicking play or popup button once. Clicking alternately play - popup - play / popup very often seems to help starting playing the video.

**Comment by opusforlife2** [comment]
@werjany Don't bump a zombie issue. Comment in or open a new issue.
