### ISSUE TITLE
One-click channel download like a podcast app

### ISSUE THREAD

**Issue by treble2019** [TeamNewPipe/NewPipe#2755]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

in a nutshell: 
Turn it more like a podcast autodownload app. As you know it looks like this so called podcasting is becoming a big again. :-)

This feature could be implemented in many ways and different places. You can think what is best:
 in 'Subscriptions- > Selected Channel' or on Whats New.

1. Lets say you are in "Whats New."
Would be nice to have from the menu button a new option to say -
Download the newest <whatever number> videos... Then these would be queued and then downloaded.

2. Lets say you are in "Whats New."

Press and hold any video then you have a "checkbox" in the left side for all videos. Tick whatever you want and then download these.

3. You are in a selected channel or playlist.

Each channel gets a setting that says: Download the last [X] videos.

**Comment by Stypox** [comment]
#2583 will probably fix your problem, even tough it is not exactly what you suggest. I think it would be too difficult to implement the specific things you suggest (that will only be used by not-so-many people). A shared way of doing things (even though it requires some more clicks) is better in my opinion. Feel free to leave feedback on #2583 :-)

**Comment by RalfKo** [comment]
I am looking for a "pocast like" app for YouTube, and in my eyes NewPipe lacks exactly the features mentioned in this here!
Most of all I would really like to have a "Autodownload of new uploads" feature per channel!
thx

**Comment by Stypox** [comment]
Closing in favour of #2380
