### ISSUE TITLE
Live stream cannot be watched

### ISSUE THREAD

**Issue by Jimmy89** [TeamNewPipe/NewPipe#2756]
- [X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X ] I checked if the issue/feature exists in the latest version.
- [X ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

It seems there is an issue with NewPipe and watching live streams. The following video https://youtu.be/RCiccdQObpo (React conf 2019 live stream of day 1) cannot be watched on NewPipe. I get an error that NewPipe was not able to parse the stream. I'm not getting this with any other video.

**Comment by kapodamy** [comment]
I get a similar error, but with OutOfMemory exception and crash.

**Comment by Stypox** [comment]
Please provide a bug report. Also, which version are you using? Livestreams were recently fixed (I think in v0.17.1)

**Comment by Jimmy89** [comment]
I'm sorry for the radio silence. Unfortunatly, after the stream was completly broadcasted the video worked just fine. It was during live stream using v0.17.1, but I have no bug report to send. Sorry about that.
