### ISSUE TITLE
Playlist Thumbnail is not updated

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#2759]
Steps to reproduce:

1. Select item, `Add To Playlist` -> `New Playlist` -> `test1`
(Item Thumbnail will be used as Playlist Thumbnail)

2. Go to `test1` playlist, `Delete` item.
(Playlist Thumbnail will remain, but it should be removed)

3. Select item, `Add To Playlist` -> `test1`
(Playlist Thumbnail will remain, but it should be updated)

It's a dup of #1330 and the expected behaviour is to update Thumbnail. The current behaviour confuses users (I've done tests on four different users.)

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
:thinking: yeah, this could be improved

**Comment by TobiGr** [comment]
Maybe we can add a default thumbnail. But why don't we delete playlists with zero items?

**Comment by decarvalhobo** [comment]
Hello! Keeping a playlist with zero elements can be useful when you want to wipe the videos from it in order to replace them with most recent ones. But indeed there is no many use cases.

I am interested in contributing on this project. Can I work on this issue?

**Comment by 532910** [comment]
The most used zero-elements playst for me is "watch later".

**Comment by Stypox** [comment]
@decarvalhobo yeah, nobody is working on this AFAIK. If you have any question feel free to ask!
If you want you can take a look at the other "good first issue" issues, so that you can familiarize with the code. ;-)

**Comment by TobiGr** [comment]
Fixed in #2837
