### ISSUE TITLE
Freetube JSON import doesn't work

### ISSUE THREAD

**Issue by stemy2** [TeamNewPipe/NewPipe#2760]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hello,

I exported my datas from freetube on a newpipe format, but when i import it to the app, it says «no content», even if i have much subscriptions, favorites and unwatched videos.

**Comment by Stypox** [comment]
Could you provide the data, so we can reproduce? Feel free to use a [JSON editor](https://jsoneditoronline.org/) to remove sensitive data. Anyway, this is probably a bug on Freetube's end, since JSON exports from NewPipe can be reimported without problems.

**Comment by opusforlife2** [comment]
@stemy2 Still an issue?
