### ISSUE TITLE
Vorbis+Ogg support for audio? 

### ISSUE THREAD

**Issue by MorenK1** [TeamNewPipe/NewPipe#2763]
The music player I use in my phone doesn't seem to support opus files, neither does my bf's
Most of my music is in Ogg and it would seem reasonable to be able to download in an opee format that is also widely compatible on Android

**Comment by Pentaphon** [comment]
1) Youtube only uses opus and m4a now so you're limited to that no matter what. 
2) Ogg is deprecated, use a player that supports Opus. There's lots of them now.

**Comment by gkeegan** [comment]
I suppose an option to mux the files to mp3 or something could be useful. It would slow down downloading a bit though.

**Comment by Gymcap** [comment]
If converting the files to mp3 is made an option, it should be made clear to the user that the resulting file will be of lower quality than the source file.

This is intrinsic to converting files of [lossy formats](https://wikipedia.org/wiki/Lossy_compression), and cannot be avoided.

**Comment by Pentaphon** [comment]
>I suppose an option to mux the files to mp3 or something could be useful. 

There's already a project that does that. 
https://dentex.github.io/apps/youtubedownloader/

We don't need Newpipe to re-encode to mp3. It just wastes quality and time. .m4a has just as much support as mp3 so re-encoding to mp3 is not only pointless, but stupid. 

The only improvement I see would be remuxing the raw .opus downloads to .opus instead of the webm container.

**Comment by gkeegan** [comment]
Some apps I've used had issues with seeking in the m4a file. Sorry if it was a bad idea :(

**Comment by Pentaphon** [comment]
>Some apps I've used had issues with seeking in the m4a file. 
Find better apps.

**Comment by Stypox** [comment]
Is #2542 duplicate/related?

**Comment by Pentaphon** [comment]
>Is #2542 duplicate/related?
No. That issue is fine because it is asking for Opus audio downloads to be remuxed as .opus instead of .webm, which makes sense. 

This issue should be closed because it is asking for Vorbis downloads from Youtube, which it cannot provide.
