### ISSUE TITLE
Ucmate

### ISSUE THREAD

**Issue by dimqua** [TeamNewPipe/NewPipe#2768]
There's an app called [Ucmate](https://www.ucmate.info). It's definitely based on NewPipe, but the source code of the app isn't public. That's why IMO it violates the licence (GPLv3) of this project.

**Comment by theScrabi** [comment]
It does.

**Comment by theScrabi** [comment]
Please help reporting ucmate at the sites wher its published.

**Comment by ucmatestudio** [comment]
I remove my app from all site. Thats it. Happy?

**Comment by theScrabi** [comment]
Yes thank you.

**Comment by dimqua** [comment]
Are serious? The app is not only still preset on many websites like apkpure.com (and similar), but even on the official website. Most importantly, it doesn't matter _where_ it's published, the GPL only talking about how: _if you release the modified version to the public in some way, the GPL [requires you to make the modified source code available](https://www.gnu.org/licenses/gpl-faq.en.html#GPLRequireSourcePostedPublic) to the program's users, under the GPL_.

**Comment by theScrabi** [comment]
@ucmatestudio honestly if you just opensouced your code I was more happy then if you took it down.

**Comment by ucmatestudio** [comment]
Ok i upload source code.

**Comment by NilsIrl** [comment]
> Ok i upload source code.

I haven't really followed this, but where is the source code available? @ucmatestudio

**Comment by gkeegan** [comment]
@NilsIrl I can't find it either, but it doesn't seem like too much of an issue. They haven't released any new updates since they said they would take it down, so they've learned their lesson. It probably doesn't even still work because of the changes YouTube makes from time to time.

**Comment by Sonickyle27** [comment]
@ucmatestudio Please publish your source code if you're going to continue making updates to your app. Your website says that the last update was on 2020-01-24.

**Comment by TobiGr** [comment]
Apart from that, you should link it from the website and the app as well as that your app is based on NewPipe.

**Comment by mhmdanas** [comment]
License violations are to be reported in #539. This one has already been reported there though: https://github.com/TeamNewPipe/NewPipe/issues/539#issuecomment-546945046
