### ISSUE TITLE
New website design

### ISSUE THREAD

**Issue by ponypower** [TeamNewPipe/NewPipe#277]
Here is the stuff i was working on. **Not yet finished** but its something.

![weblap](https://cloud.githubusercontent.com/assets/16841860/14773120/51e3bb26-0aa6-11e6-93bd-5dbfe60a261f.png)

**Comment by Ayukiba** [comment]
It looks pretty good, nice job!

**Comment by theScrabi** [comment]
![amazed cat](http://rack.0.mshcdn.com/media/ZgkyMDEyLzEyLzA0LzlkLzE1YmVzdGNhdG1lLmFIOC5qcGcKcAl0aHVtYgk5NTB4NTM0IwplCWpwZw/81fb5716/5f7/15-best-cat-memes-ever-meow--3283dd863e.jpg)

**Comment by ponypower** [comment]
Heyo, 

Here is the next version with more design features. Open the image on a new tab with your browser and zoom in, so you can kinda check it like a webpage.

![weblap5](https://cloud.githubusercontent.com/assets/16841860/14944331/02542a92-0ff0-11e6-8162-728f80c627fa.png)

A few notes:
- making the background image montage (under the red) scroll sensitive would give it an extra punch
- the app would be animated just as it is at the current website
- the "Main Feature" blocks would be click sensitive bringing up some extra details about the selected feature
- there would be a sub page for donations, offering paypal, bitcoin and maybe flattr options (it needs further in-depth discussion)
- other sub pages for the footer elements (support, privacy&cookies, ...)

Now tell me what do you think

**Comment by theScrabi** [comment]
Even better :)

**Comment by TobiGr** [comment]
I like this new design and I think it is really good. Good job ;)

Perhaps you could change the font-family or make it a little more bold/fatter, so the white text above the red slider with this many images doesn't get lost. To get the same effect, you could increase the slider's opacity.

**Comment by TobiGr** [comment]
Do you have an idea for a design on _small devices_?

We should think about this first, otherwise we have restructure our code later.
So my questions for small screens are:
- What about the phone and it's animations?
- Where do we put the logo?

On mobile devices there are performance-problems with background-images (and scrolling as well).

- Skip the background-images _on mobile devices_ / small screens and

- make a full-colored background like in the first design proposal?

**Comment by ponypower** [comment]
Thanks for the kind words. I was pretty busy lately but now I'm back to business. I'm going to do a little research on the best design practices for low-res displays and come up with a working solution.

**Comment by TheAssassin** [comment]
As mentioned in #435, the discussion should be continued in the [website repository](https://github.com/TeamNewPipe/website/issues).
