### ISSUE TITLE
Video freezes after few seconds

### ISSUE THREAD

**Issue by dmlemos** [TeamNewPipe/NewPipe#2770]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
~~- [] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.~~

---

Every time I start a video, it pauses forever at ~8 seconds into the video. Not sure what else can be provided to help further debugging.

I am using version `0.17.3`, but it has been happening from at least `0.17.1`.
Android 7.1.1

**Comment by Stypox** [comment]
Try v0.17.4 with the updated ExoPlayer (though that's probably not the issue)

**Comment by dmlemos** [comment]
Sadly, I don't think it did

**Comment by Stypox** [comment]
Could you provide a link to a video showing this behaviour and the problematic resolution(s)? Does this also happen with audio? What happens when you download the video? Thanks :-)
@dmlemos

**Comment by Stypox** [comment]
So this is apparently an issue with the player, since you said downloading works fine...🤔

**Comment by dmlemos** [comment]
I've done more testing over the course of these last days.

@cybe Same behaviour with 720p. Also switching to webm for video and m4a for audio didn’t work.
Using external audio player, same thing.

**Comment by dmlemos** [comment]
It could be related to this #2804

**Comment by dmlemos** [comment]
I'll add it could be related to #2770. Having the issue still with the same version.

**Comment by opusforlife2** [comment]
@dmlemos Could you try 0.20.0?

**Comment by dmlemos** [comment]
@opusforlife2 I've tried. It doesn't seem to happen anymore. It takes a good while to load, but doesn't freeze I believe.

**Comment by opusforlife2** [comment]
Thanks!
