### ISSUE TITLE
application17.4 freezes when downloading audio

### ISSUE THREAD

**Issue by jediafr** [TeamNewPipe/NewPipe#2773]
sorry to report that i have foremost issue with the new update : the application now freezes when downloading audio (with the share feature).
How to reproduce :
Share a link and select Newpipe.
The download dialog appears and i select audio (i leave the default options for the encoding).
Newpipe then starts downloading but freezes. (previous 17.3 works fine with the same link).

Had to rollback to 17.3 for the time being.

- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by gdevenyi** [comment]
Just experienced the same bug, but I'll add a little more detail.

The UI interface seems to get hung somehow. The download proceeds correctly, but the interface is hung and I need to switch applications to get back to where I was before.

In addition to this but probably related, when I share another link to the newpipe target the original share populates the download dialog. I have to share twice to get the new link.
