### ISSUE TITLE
"Default Kiosk" string is not available for translation

### ISSUE THREAD

**Issue by bboa** [TeamNewPipe/NewPipe#2778]
- [*] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [*] I checked if the issue/feature exists in the latest version.

Please add a new string to strings.xml to able translate it. [https://imgur.com/a/46z3xut](url)

**Comment by TobiGr** [comment]
Thank you for the report
