### ISSUE TITLE
apps not properly installing after a dozen attempts

### ISSUE THREAD

**Issue by Kukulkan2019** [TeamNewPipe/NewPipe#2779]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
Are you updating it over an F-Droid version? There are probably signature clashes. Take a look at the repo README.md file.

**Comment by Kukulkan2019** [comment]
Yes it's F-Droid, I finally got it working...the problem seemed to be in
the wifi settings, I'm using 4G...

On Tuesday, November 5, 2019, Stypox <notifications@github.com> wrote:
> Are you updating it over an F-Droid version? There are probably signature
clashes. Take a look at the repo README.md file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/MJu4dlu5EaDxutsOtDgTj_Sf9mCBncrJ_BgJcXfD49U0l7y5IM3TCrAusJHqbxoKARyKk2IZ0WkckijxlLaubT6ju__W6t7XFwmhuMdDzzvVj8eqsJbOAl28pzMz8ioAfhjbIdVfFbfkU3nB1lJNweF4OdJPp_BwKfIt1mLjZ11ZwG0VFDtfpUooEczCNXob9drZhB0l_h9syO9YbLxGrGflald9pzA7vJie7hz8QQ=s0-d-e1-ft#https://github.com/notifications/beacon/AMHMGMLJSUYXCWWGYQIT44DQSBFBRA5CNFSM4JISCRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC73VHI.gif
>

-- 
Android strong, be all you can be, end transmission.
