### ISSUE TITLE
Player config empty

### ISSUE THREAD

**Issue by HartOfWave** [TeamNewPipe/NewPipe#278]
With the 0.7.6 version I can search for a video but when I go to the video page a "player config empty" pops up at the bottom and the video isn't there, just a black box. I can play the video only if I use the new share to newpipe thing but the audio only option isn't there.

**Comment by HartOfWave** [comment]
Reinstalling did nothing but a reboot of my phone fixed the issue, I can now get video but the button for audio only is missing?

**Comment by theScrabi** [comment]
You may install 0.7.8 No support for older versions.
