### ISSUE TITLE
XML Subscriptions import not working

### ISSUE THREAD

**Issue by dducro** [TeamNewPipe/NewPipe#2784]
This xml file couldn't be imported in NewPipe v0.17.4

```
<opml version="1.1">
    <body>
    <outline text="YouTube Subscriptions" title="YouTube Subscriptions">
        <outline text="shaycarl" title="shaycarl" type="rss"
                 xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC77WzpPRrYr0W5oeFjVIqwQ"/>
    </outline>
    </body>
</opml>
```

(removed all channels except one)

**Comment by Stypox** [comment]
Sorry if I finally got to this so late... I forgot about it :-\
I tried to import an xml file with the above content and it worked correctly: I got the `shaycarl` channel. I'm using NewPipe 0.18.0.

**Comment by dducro** [comment]
Thanks for testing, I'll try it again with 0.18.0.

**Comment by dducro** [comment]
Hey, I installed 0.18.2.
I checked if the app had the file access permission, that was correct. However it can't open the file. Do you have any suggestions?
![screenshot](https://user-images.githubusercontent.com/2156884/73607747-66d9ba00-45ba-11ea-9b67-f15ea9aed44d.jpeg)

**Comment by Stypox** [comment]
@dducro could you test if the apk provided in https://github.com/TeamNewPipe/NewPipe/pull/3777#issuecomment-667650552 fixes this issue? Are you on Android 10?

**Comment by opusforlife2** [comment]
Closing until @dducro replies.
