### ISSUE TITLE
recapcha issue

### ISSUE THREAD

**Issue by Ksanbah** [TeamNewPipe/NewPipe#2788]
Hey we seem to have an issue with recapcha. Can it be fixed? 
![Screenshot_2019-11-07-02-15-05-77](https://user-images.githubusercontent.com/51513596/68337033-91a99480-00d7-11ea-913a-629e1972bb8a.png)

**Comment by Stypox** [comment]
What happens if you resolve the captcha, click submit and then click the back arrow in the toolbar?

**Comment by Ksanbah** [comment]
It just takes me to the android browser YouTube. Last I checked.

**Comment by Ksanbah** [comment]
I'm unfortunately unable to bring out the result now. It has disappeared
and now just bombard me with errors.

**Comment by whywhywhyHah** [comment]
I had only once this recaptcha View. After this im getting this kind of error [#2787](https://github.com/TeamNewPipe/NewPipe/issues/2787)

**Comment by fabiano-araujo** [comment]
the latest update from newpipe extractor was able to make the app show recapcha, but there is some error taking the recapcha cookie and sending it to downloader.class for some users.  sometimes i'm having nullpontedException.  The problem is certainly in the Recapcha activity in the method that takes the recapcha cookie parameters.

**Comment by Ksanbah** [comment]
Will you update soon

**Comment by Stypox** [comment]
This issue is difficult to fix because ReCaptchas can't be forced or simulated...

**Comment by Ksanbah** [comment]
Is there anything you can do? Anything? Was really loving the app.

**Comment by Ksanbah** [comment]
Hey so I was using another app. And got similar results. I got this example
now

**Comment by Ksanbah** [comment]
Maybe you can add a floating button. For downloads and such.

**Comment by Stypox** [comment]
How does that relate to recaptcha?

**Comment by Ksanbah** [comment]
After I did the captcha on that app, it took me to the browser version of
YouTube. Their  app was designed to accommodate the browser version, with
the floating download button, which I can use to download videos. The
button at the bottom.

**Comment by Ksanbah** [comment]
The app is from Savefrom.Net.

**Comment by Ksanbah** [comment]
Hi TeamNewPipe/NewPipe
So after the captcha, now the Newpipe app just crashes with unsupported URL
or app crashes. Can you help?

**Comment by Gymcap** [comment]
I recently got the recaptcha while using my mobile data. Solving the captcha seemingly did nothing, though I was using Firefox Klar which could have blocked some kind of verification. 

I turned on a vpn as a temporary fix and not too much later the recaptcha disappeared from my vanilla mobile data connection. 

If I get it again I will do more testing with a standard browser. It seems this is a temporary IP tag that will eventually go away on its own if not resolved.

**Comment by Ksanbah** [comment]
OK
Hope it gets fixed.

**Comment by Ksanbah** [comment]
Hey I just checked it again. It's working now. Must be because I had just
returned home from college, if IP address is concerned .

**Comment by MuntashirAkon** [comment]
Related to #2795

**Comment by BoFFire** [comment]
Recaptcha challenge when IP is supposed "blacklisted" by Google : https://mstdn.fr/@ButterflyOfFire/103268103935090093

**Comment by Stypox** [comment]
Could you test this apk? The reCAPTCHA activity is shown, the user can resolve the reCAPTCHA (or follow the instructions, or do whatever they want), and then press back or "Done" to exit.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4119347/app-debug.zip)
@BoFFire @MuntashirAkon @Ksanbah @Gymcap @fabiano-araujo @whywhywhyHah

**Comment by Ksanbah** [comment]
It doesn't seem to download. Help

**Comment by Stypox** [comment]
What do you mean by "it doesn't seem to download"? It is a zipped file, so you have to extract it before installing.

**Comment by Stypox** [comment]
Here is a direct apk download: [app-debug.apk](https://github.com/Stypox/NewPipe/releases/download/untagged-e35050f79c5922b192d5/app-debug.apk)

**Comment by Ksanbah** [comment]
OK

**Comment by Ksanbah** [comment]
Still doesn't install.
