### ISSUE TITLE
Large videos fail to download.

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/NewPipe#2790]
I get a Http 200 error whenever downloading larger files (>1gb or so). 

This is using 1080p download option on this video: https://www.youtube.com/watch?v=BbI9xkzNHQI

It happens on many other large videos besides that one.

Tested on 0.17.3 and also on latest commits on dev branch.

**Comment by kapodamy** [comment]
same as https://github.com/TeamNewPipe/NewPipe/issues/2111

**Comment by gkeegan** [comment]
@kapodamy I saw that issue but it seems like a different bug? Videos don't even make it to post processing. They get to like 40% downloading done then get an error

**Comment by LoganTRowley** [comment]
Having the same issue. It seems like any video over 2GB errors out and crashes the app. Using MotoG7 Power.

**Comment by cassdotcom** [comment]
Having the same issue here too, I'm running 0.18.6.

**Comment by kapodamy** [comment]
@cassdotcom video url?

**Comment by gillhash** [comment]
Same issue here. running 0.18.6 mix-auto playlist handler PR debug by XiangRongLin

Tried downloading 2.4 GB 1080p Video, failed at 80%.

**Comment by rlister-gh** [comment]
Hi @kapodamy,

I'm having this issue to on loads of videos for example
https://www.youtube.com/watch?v=qoSKknHO6fU
They all get to about 75-85% then error with http 200
App version 0.18.7
Let me know if you need anything else
