### ISSUE TITLE
Rotation problem

### ISSUE THREAD

**Issue by rissilver** [TeamNewPipe/NewPipe#2796]
- [ x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x ] I checked if the issue/feature exists in the latest version.
- [ x ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

System Auto-Rotate Screen is disable - Open video in newpipe, in the video change rotation to Landscape view - go back the whole application is on Landscape view - reopen, application is on Prtrait view - when play video, Video play on Landscape view and whole application -  and so everything revolves in a circle. 

I hope you understood what I wanted to explain.

**Comment by iamrishav** [comment]
I can't understand what you are trying to say?

**Comment by iamrishav** [comment]
Can you explain It bit more, also check the latest version of newpipe , it is possible this bug may be fix on latest version..
