### ISSUE TITLE
Downloading Audio Naming Problem When Shared from YouTube

### ISSUE THREAD

**Issue by qey12** [TeamNewPipe/NewPipe#2797]
- [✔] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [✔] I checked if the issue/feature exists in the latest version.
- [✔] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

on version 0.17.4 when sharing a video from youtube to newpipe to download as audio... on the first try the file name that shows up is the file name from the previously downloaded audio... upon the second try to download it then gets it correct name... happen for all downloads... if i remember correctly i think the first time using this version when dwnloading using my method the first file name came up empty..

**Comment by slishnevsky** [comment]
I confirm the issue. 
Ver 0.16.2 is good.
Very 0.17.x - problem.
Also starting from v. 0.17.x after downloading from YouTube, YouTube hangs.

**Comment by pchebel** [comment]
I have also noticed that the downloaded video is the wrong one and I have managed to recreate this issue on V 0.17.4 by:
1) Downloading a video by sharing from the YouTube app
2) Switching back to YouTube app
3) Sharing a new YouTube video to NewPipe

The problem seems to be fixed by adding a "OnNewIntent" method in RouterActivity:

``` java
protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);

        currentUrl = getUrl(intent);
    }
```

**Comment by Stypox** [comment]
@pchebel you could open a pull request ☺
