### ISSUE TITLE
Plugin like systems for other streaming services

### ISSUE THREAD

**Issue by fightthepower** [TeamNewPipe/NewPipe#2803]
I love newpipe and mostly I use it for streaming youtube but some times I also streams soundcloud audios and mediaCCC conferences. I love how new pipe can be used as a single app for streaming different streaming services. Not only these streaming sites I also love watching videos from vimeo and daily motion which are not available in new pipe now. Currenly newpipe is stuck with only three streaming services youtube, soundcloud and mediaCC and most likely will stay the same because most of the newpipe  dev's doesn't want to beak it by adding more streaming services.

My recommendation for this problem is a plugin like system where users with mediocre programming skils (like myself) can create a pluging for different streaming services which then can be pluged into the newpipe's video engine. For example If I want to stream dailymotion videos then  I can make a newpipe plugin for dailymotion using the dailymotion url parameters or some other way and use this way to play videos in newpipe.

DailyMotion follows certain url patterns 

```
videos: https://www.dailymotion.com/video/xxxxxx
channels: https://www.dailymotion.com/xxxxxx
playlist: https://www.dailymotion.com/playlist/xxxxxx
```

The advantage of this system is that it can stay independent of the main newpipe development and relax the hands of main developers here.

**Comment by Stypox** [comment]
Have you seen the NewPipeExtractor repo? It contains the needed tools to create an extractor for any service

**Comment by gloschtla** [comment]
Short URLs of dailymotion: dai.ly/{video-ID}
