### ISSUE TITLE
Video position lost after phone locks out

### ISSUE THREAD

**Issue by dmlemos** [TeamNewPipe/NewPipe#2804]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
~~- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.~~

---

Sometimes when the phone locks out, and the video was in a fixed position, when unlocked it gets skewed and goes back to the beginning.

It is not something I can say it happen all the time, so cannot reproduce easily.

version: `0.17.4`

**Comment by LukasThyWalls** [comment]
Hello

I don't know if my issue is exactly the same of the original issue, but his explanation fits perfectly with the issue i was going to post.

In my case, it happens always: When i pause the video and then it blocks, when i return and press play it goes to the beginning of the video.
However, the detail is when i return to the video from the lock screen, the image video it's from the beginning (not the actual time) but the time bar is in the position i left the video, but when i press play it goes to 00:00.
![NewPipe_ReturnFromUnlockScreen](https://user-images.githubusercontent.com/1467366/72751398-d8c80180-3bbf-11ea-9d49-0a4912fdcd39.jpg)
Somehow, the gui remembers the position, but the player has been reset. Maybe the phone battery optimization has something to do with this (i can test all options there).

Specs: Xiaomi Mi 9 Lite, Android 9, MIUI 11.3.4.0, NewPipe 0.18.0 (F-Droid).

Thanks in advance.

**Comment by dmlemos** [comment]
This is exactly what happens to me!

**Comment by LukasThyWalls** [comment]
With some time testing this, i want to add more info, but i don't think it's enough:

* I can say now it doesn't happen always. In fact, to me, it happens always in a concrete youtube channel, and now i don't remember happening in other one, as i can recall in the past two months. The only different thing is those videos from this channel are premieres, i don't see them where are premieres, i see them later when are "normal" videos (one or two hours later they were "aired"). However, i saw live shows (not premieres) also later and this not happens. I can post the links if needed.

* The phone battery optimization has nothing to do with this. In fact now i have configured the app as "no restrictions" and it does the issue as equal as i set "battery economy" or "restrict background apps/activity".

**Comment by wb9688** [comment]
Are all of you using Xiaomi devices? And could you test it with v0.18.5 from GitHub releases?

**Comment by dmlemos** [comment]
I'm using OnePlus, haven't changed.

**Comment by LukasThyWalls** [comment]
After some days of testing (the first days waiting F-droid to update the APK but i give up) with 0.18.6 in my Xiaomi Mi 9 Lite it still happening. Maybe, and i said maybe, is not happening as repeatdly as before (in two different videos at different times i paused three times, with only once happening the issue, and in a older video i tried pausing two times and didn't happen. Before was happening almost every time) but don't quote me on this, maybe is a mislead impression.
For sure is still happening.

**Comment by opusforlife2** [comment]
Still happening in 0.20.0?

**Comment by LukasThyWalls** [comment]
For me,should be closed because in my case it's not happening since some releases, i can't know since when, but it's not happening.
Thanks.

**Comment by opusforlife2** [comment]
Thanks for confirming!
