### ISSUE TITLE
A small part of the sidebar is in the status bar

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2810]
Hi,

when I open the sidebar under Android 7 in the NewPipe app (0.17.4). You can see a small part of the sidebar in the status bar.

![20191117_134543](https://user-images.githubusercontent.com/57863489/69007661-eb645700-0940-11ea-8c98-379700363d73.png)

I've seen friends using a much bigger Android phone (Samsung Galaxy S10+ - Android 9) that even the "NewPipe logo + NewPipe" in the sidebar is almost in the status bar and it doesn't look right anymore.

**Comment by TobiGr** [comment]
The navigation drawer should be under the status bar as you can read and see [here](https://material.io/components/navigation-drawer/#anatomy) in the material guidelines. 

>I've seen friends using a much bigger Android phone (Samsung Galaxy S10+ - Android 9) that even the "NewPipe logo + NewPipe" in the sidebar is almost in the status bar and it doesn't look right anymore.

This needs to be addressed, though.

**Comment by Stypox** [comment]
@mauriciocolli since you messed with the drawer layout in #3259, do you have any idea how this could be solved? Image for reference:
<img src="https://user-images.githubusercontent.com/36421898/78217497-86a73480-74bc-11ea-84e2-c17cf40cc2c5.png" width="300px" />

**Comment by mauriciocolli** [comment]
@Stypox should be fixed in #3334.

**Comment by TobiGr** [comment]
Fixed in #3334
