### ISSUE TITLE
 "user_action": "get suggestions", Error

### ISSUE THREAD

**Issue by grandsource** [TeamNewPipe/NewPipe#2812]
"exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:73)\n\tat com.amaderwap.youtube.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:105)\n\tat com.amaderwap.youtube.util.-$$Lambda$ExtractorHelper$CYYJVkcyRKUWPtv3UMIq4rqkJs0.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)\n\tat io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)\n\tat io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)\n\tat io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)\n\tat io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: com.grack.nanojson.JsonParserException: Unexpected token 'ml' on line 1, char 1\n\tat com.grack.nanojson.JsonParser.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.createHelpfulException(Unknown Source:119)\n\tat com.grack.nanojson.JsonParser.advanceToken(Unknown Source:83)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:0)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:15)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:63)\n\t... 26 more\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
Please format ypur report using the bug report importer, and change the title.
