### ISSUE TITLE
Going full-screen from pop-up does not work

### ISSUE THREAD

**Issue by SinTan1729** [TeamNewPipe/NewPipe#2815]
Device : Redmi K20
Newpipe Version : 0.17.4 (latest)
Issue : Going from pop-up to full screen mode not working
Steps to reproduce : 
1. Open any video in pop-up mode.
2. Try to go to full screen (by pressing the button in the top-right).
3. The pop-up closes but full-screen playback doesn't start.

- [x] I carefully read the [contribution guidelines](hjithake...ttps://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
I can't reproduce. Which Android version are you running? Also, do you get any error or simply nothing happens?

**Comment by SinTan1729** [comment]
I'm running MIUI 11 (based on Android 9). Here's a screenrecord of the incident.

https://imgur.com/a/yM1JUBb

**Comment by Stypox** [comment]
Mmmh, strange

**Comment by opusforlife2** [comment]
@SinTan1729 Can you test 0.20.0?

**Comment by SinTan1729** [comment]
> @SinTan1729 Can you test 0.20.0?

It works now. Can confirm.

**Comment by opusforlife2** [comment]
Great!
