### ISSUE TITLE
iOS version?

### ISSUE THREAD

**Issue by myrmatrix** [TeamNewPipe/NewPipe#2818]
Hello,

I used this app on Android in the recent past, and I really loved it.  It made YouTube a sincerely enjoyable rather than merely tolerable experience.  Thanks to all of you for your work on this app.

I have for various reasons moved away from Android however, and am wondering if there are any plans for an iOS port of NewPipe.  It would be really awesome to use it at some point on an iphone or ipad.  Are there any plans to create a port?  Thanks.

**Comment by gkeegan** [comment]
As far as I know this would require a complete rebuild of the app. The NewPipe extractor could probably be reused, but aside from that it would need to be redone. This makes it unlikely that it'll happen soon.

**Comment by myrmatrix** [comment]
Fair enough.  Thanks for the response.  If/when it does happen, I’ll be looking forward to it.

**Comment by Serkan-devel** [comment]
Wouldn't this type of app be banned from the Appstore?

**Comment by kuaile1993** [comment]
Hope to support windows macos and ios

**Comment by Serkan-devel** [comment]
Possibly will only work when jailbroken, but otherwise https://github.com/TeamNewPipe/NewPipe/issues/1051

**Comment by Mercurial** [comment]
can anyone explain why it will require jailbreak?

**Comment by Stypox** [comment]
Because it could not be added to the store

**Comment by Mercurial** [comment]
> Because it could not be added to the store

and why is that?

**Comment by gkeegan** [comment]
Apple would never allow it into the store.

**Comment by Mercurial** [comment]
> Apple would never allow it into the store.
> 
> I believe it breaks some of their terms.

why its not pirating or having adult content, I don't understand. this is basically a browser of videos

**Comment by JayBrown** [comment]
There's always the AltStore: https://altstore.io/

https://github.com/rileytestut/AltStore

**Comment by kylemsguy** [comment]
> > Apple would never allow it into the store.
> > I believe it breaks some of their terms.
> 
> why its not pirating or having adult content, I don't understand. this is basically a browser of videos

The same reason why MxTube/McTube and ProTube got removed from the App Store.

**Comment by sebma** [comment]
@kylemsguy 


> > > Apple would never allow it into the store.
> > > I believe it breaks some of their terms.
> > 
> > 
> > why its not pirating or having adult content, I don't understand. this is basically a browser of videos
> 
> The same reason why MxTube/McTube and ProTube got removed from the App Store.

What does that reason may be ?

**Comment by Stypox** [comment]
I'm closing this in favour of #1051. Let's keep all of the discussion about ports of NewPipe there.
> What does that reason may be ?

The reason is probably that it breaks Google's ToS, and Apple does not want people to break a competitor's ToS for legal reasons (I don't know, though)

**Comment by GTO683** [comment]
A lot of us jailbroken users want a NewPipe badly lol I've been waiting forever > Apple would never allow it into the store. 
> 
> I believe it breaks some of their terms.

**Comment by sebma** [comment]
@Stypox Issue #1051 is about a "Windows/Linux/macOS DESKTOP Version?" 

Can you please re-open this issue regarding an iOS version ?

**Comment by ChiefMikeK** [comment]
Or just rename #1051 `¯\_(ツ)_/¯`
---
## [DISCUSSION] Version other than Android

**Comment by sebma** [comment]
@ChiefMikeK I didn't create #1051 so I can't rename it.

I beleive #1051 is dedicated for PCs hence the name "Windows/Linux/macOS DESKTOP versions ?"

Why do you mind re-opening this one ?

**Comment by ChiefMikeK** [comment]
> @ChiefMikeK I didn't create #1051 so I can't rename it.
> 
> I beleive #1051 is dedicated for PCs hence the name "Windows/Linux/macOS DESKTOP versions ?"
> 
> Why do you mind re-opening this one ?

devs have requested **all of** this/these conversations in a single thread. see above re.

**Comment by opusforlife2** [comment]
Guys, I've changed the issue title for #1051. If there is ever an actual effort to port Newpipe to a new platform, a new issue will naturally be created for that. But until then, everything goes in that one issue.

**Comment by guysoft** [comment]
Any idea what this is?
Is it a fake that needs to be reported?
https://apps.apple.com/cd/app/newpipe-music-videos/id6450053445
