### ISSUE TITLE
We "need" an optional black theme for amoled users

### ISSUE THREAD

**Issue by ministro** [TeamNewPipe/NewPipe#282]
I will try to scrap some code from other open source apps.
Then I'll attempt to integrate it coherently.
Help appreciated! Will post progress in this thread.

**Comment by ministro** [comment]
I suppose the following modifications would be correct:

- Add button to NewPipe/app/src/main/java/org/schabi/newpipe/SettingsActivity.java
- Add method to NewPipe/app/src/main/java/org/schabi/newpipe/NewPipeSettings.java
- Modify value of theme to dark, (where?)

**Comment by timofonic** [comment]
I use black themes because bright stuff makes me somehow fuzzy. I hate that, but bright colors stew everywhere and is a neverending battle :/

**Comment by krompus** [comment]
I agree!
