### ISSUE TITLE
Donate (NewPipe)

### ISSUE THREAD

**Issue by MikeGajewsky** [TeamNewPipe/NewPipe#2826]
Добрый День!
Моё имя Майк!
Нашей команде очень понравился Ваш продукт!
Я бы хотел обсудить с Вами поддержку Вашего проекта на постоянной основе! 

Вы сделали очень хороший вклад, это впечатляет!
Мы считаем что у Вашего проекта большое будущее. Каждый юзер может смотреть, слушать любимый контент! Развиваться, делать больший вклад в ИТ сообщество.

Я уверен, что мы сможем вместе достигнуть большего. 
Спасибо.

Больше деталей можем обсудить по этим контактам:
ak@ultradistribution.com.ua

**Comment by developerfromjokela** [comment]
Привет, пожалуйста напишите на английском, к сожалению они не понимают русский язык. 😉

**Comment by MikeGajewsky** [comment]
> Привет, пожалуйста напишите на английском, к сожалению они не понимают русский язык. 😉

Спасибо. Надеялся на гугл переводчик. Но потом понял что пончик не интересен 🤣

**Comment by MikeGajewsky** [comment]
Hello to all!
My name is Mike!
Our team really liked your product!
I would like to discuss with you support for your project on an ongoing basis! Now I'm talking about money. More serious than can think.

You have made a very good contribution, it is impressive!
We believe that your project has a great future. Each user can watch, listen to their favorite content! They are developed, contribute more to the IT community.

I am sure that we can achieve more.
Thanks.

We can discuss more detailed information on these contacts:

**Comment by theScrabi** [comment]
Please report @MikeGajewsky for spam.

**Comment by MikeGajewsky** [comment]
> Please report @MikeGajewsky for spam.

No pls. Sorry! this is my mistake
Its not spam!

**Comment by MikeGajewsky** [comment]
get pls your mail. I send cooperation offer.
Sorry....😉 I really want to discuss cooperation with you
