### ISSUE TITLE
21:9 Fullscreen support

### ISSUE THREAD

**Issue by developerfromjokela** [TeamNewPipe/NewPipe#2827]
Hello,

(**This is a feature request** )

I'm using 21:9 phone, and watching 16:9 on 21:9 is little bit annoying. Google's YouTube app has that feature, so it will be nice one to have in NewPipe.

 
**update** 

I've found way to do it, it's the Fit button.
But for excellent UX, you can implement it like Google, just to do a zoom gesture, and done.

**Comment by B0pol** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3181

**Comment by developerfromjokela** [comment]
How is this a duplicate if I requested the feature way before him?

**Comment by Stypox** [comment]
That's not the point. The point is that only one issue should stay open, and that other issue is a little bit more clear, and has already been pointed to by a pr

**Comment by developerfromjokela** [comment]
Ok
