### ISSUE TITLE
NewPipe doing network requests its not supposed to do

### ISSUE THREAD

**Issue by fw190d13** [TeamNewPipe/NewPipe#2834]
Hi!
Everything is working well with NewPipe but while using it I have encountered a very strange thing. Besides using things to watch videos NewPipe is also using addresses that are not in my subscriber list or not even visited with NewPipe. They were visited with my browser (Firefox) but NetGuard has popped a message about new connections made by NewPipe and that is how I have discovered it and had to manually block it with NetGuard. See attached photo. NewPipe has also wanted to connect to:
android.clients.google.com
maps.google.com
google-analytics.com
apis.google.com
google.com
cd.ampproject.com
chrome.google.com
play.google.com

and a bunch of blogger blogs. Something fishy is going on here ;)

![Screenshot_20191201-181648](https://user-images.githubusercontent.com/10887378/69917597-8a1fa600-145f-11ea-9946-e50eb868db95.png)

**Comment by gkeegan** [comment]
Where did you download NewPipe from?

**Comment by gkeegan** [comment]
Also, are these sites visited from links in comments/descriptions? Or visited entirely from the browser?

**Comment by fw190d13** [comment]
NewPipe is straight from F-droid. I didn't click any links from the comments or video description. The china defense blog as posted in the screenshot was visited with Firefox but the outgoing link was from an RSS app Feeder also from F-droid. Other links from blogger were visited from Firefox and there is no chance that they could be from NewPipe/comments or video descriptions.

**Comment by gkeegan** [comment]
Odd. I don't maintain the code here so I have no idea what the cause of this could be. Maybe @TobiGr could help you?

**Comment by licaon-kter** [comment]
Keep in mind that Netguard shows IP-domain name relationships as they come, now if it first saw that ip resolved to maps or blogspot, both Google properties, it doesn't mean anything...Google can allocate whatever IP it chooses, and I bet it does that rather often.

Press that entry...then on the popup menu press the right arrow...are there multiple entries?


Or go to Settings/Advanced/last option to see resolved, menu...use both Clean options.

Then reopen ONLY Newpipe....what happens?

**Comment by TobiGr** [comment]
Uh what?!
@fw190d13 Can you please elaborate what actions you performed when you used NewPipe?
These are the domains where content is requested from when using NP. I tracked them down by using the network profiler tool which is included in Android Studio. I watched a video, opened trending, a channel and read some comments.
- youtube.com
- googelvideo.com => video and audio streams
- ggpht.com => user thumbnails
- ytimg.com => video thubnails

However, the Google Play Store might track which apps you use. Nevertheless, this information would be sent by the play store itself and not via NewPipe.

Unfortunately, NetGuard does not have an issue tracker on GitHub, but an endless XDA feed, so I could not check whether this is a known NetGuard bug.

Just for the record: NewPipe does not access your browser history or any other app data. We just use the storage permission to allow you to download videos or backup/import NewPipe's app data.

**Comment by licaon-kter** [comment]
@TobiGr Not a Netguard bug, neither a Newpipe one.

**Comment by gkeegan** [comment]
Something can be said about the fact that only Google owned services were showing up. I think @licaon-kter was right when they said 

>it doesn't mean anything...Google can allocate whatever IP it chooses, and I bet it does that rather often

Also, @TobiGr is correct, NewPipe isn't tracking browser histories. If it was, you would see a request to some spy server to upload collected data.

I bet if the IP was looked up it would show that it was used for YouTube at some point.

**Comment by fw190d13** [comment]
> Keep in mind that Netguard shows IP-domain name relationships as they come, now if it first saw that ip resolved to maps or blogspot, both Google properties, it doesn't mean anything...Google can allocate whatever IP it chooses, and I bet it does that rather often.
> 
> Press that entry...then on the popup menu press the right arrow...are there multiple entries?
> 
> Or go to Settings/Advanced/last option to see resolved, menu...use both Clean options.
> 
> Then reopen ONLY NewPipe....what happens?

I have pressed that entry and for the suspected connections in the log. I can only see two connections. One is to the domaine which is suspected and the second one, with gray colour is to yt3.ggpht.com (as I understand some photo domain of google?) The older entries in the log show no information like this - I can tap the arrow but nothing pops out. I don't know if this is due to some sort of log cleanup which happens with time or that there were non connections like this.

"Settings/Advanced/last option" - this log is too poluted with other domains as it logs everything so it is hard to look through it.

"use both Clean options" - I don't understand this part.

@TobiGr I have GooglePlayServices, GoogleFramework and GooglePlayStore turnedOff except regular bi monthly software updates (I use mostly F-droid). There is a possibility that something went sideways when I have turned on thos 3 services and it happened than but this needs further inspection. I'm not accusing you fo evil craftsman ;) Just wanted to be a responsible FOSS user and filled a bug when spotted something strange.

**Comment by licaon-kter** [comment]
@fw190d13 
> "use both Clean options" - I don't understand this part.
In the "resolved" page... use the upper right menu, clean all entries, clean journal too.

> "Settings/Advanced/last option" - this log is too poluted with other domains as it logs everything so it is hard to look through it.
There's a Save option there.

> What bothers me is that non of the blogs I have visited (like china defense) were watched with NewPipe as I only read them. 
But they where read "through" Netguard...so it "recorded" that IP

>  Firefox is hardened and has uBlock with block google domains list turned on and NetGuard has an additional hosts file which is build in and is also used. 
I doesn't matter, Netguard would still resolv the DNS, yes block them but the entries still appear in the domains page.

/close as invalid

Ref: https://github.com/M66B/NetGuard/blob/master/FAQ.md#user-content-faq48
Ref: https://github.com/M66B/NetGuard/blob/master/FAQ.md#user-content-faq63

**Comment by fw190d13** [comment]
> 
>     What bothers me is that non of the blogs I have visited (like china defense) were watched with NewPipe as I only read them.
> 
> But they where read "through" Netguard...so it "recorded" that IP

But why in NewPipe? Those pages were visited by Firefox so should pop up in Firefox log and not in NewPIpe log.

**Comment by licaon-kter** [comment]
@fw190d13 Not Newpipe, Netguard recorded it and shows it when that IP pops-up again.

**Comment by TobiGr** [comment]
> I'm not accusing you of evil craftsman ;) Just wanted to be a responsible FOSS user and filled a bug when spotted something strange.

Yes, I know. But I wanted to write that down for other people who might come across this and jump to false conclusions.

> But why in NewPipe? Those pages were visited by Firefox so should pop up in Firefox log and not in NewPipe log.

All domains from which your browser has requested content belong to Google. As @licaon-kter suggested, I suspect Google routes the requests through a few servers, which in turn know which Google servers are running the requested service and where capacity is available to process the request quickly. NetGuard stores the IP addresses and domain names to save data when an IP is accessed later. When NewPipe requests youtube.com or one of the other domains listed in my earlier post, NetGuard only sees the IP and searches the list, which it had compiled before, to find any domains affiliated to that IP. That's probably why those various blogs and content delivery services (e.g. cd.ampproject.com) appear in the list.

Thank you @gkeegan and @licaon-kter for the references and help :)
