### ISSUE TITLE
"Whats New" Isn't Actually New

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [TeamNewPipe/NewPipe#2840]
The whats new area isn't exactly whats new. I see videos from a month ago there, and more. Many of my subscriptions have posted videos, sometimes I see them othertimes I don't. I end up seeing a lot of the same videos from a month ago, or two months ago or sometimes years back.

**Comment by cool-student** [comment]
yeah this is a known issue and is being worked on here https://github.com/TeamNewPipe/NewPipe/pull/2309 and here https://github.com/TeamNewPipe/NewPipe/pull/2547. For the time being you can use the test apk from https://github.com/TeamNewPipe/NewPipe/pull/2547 which has recently been compiled.
