### ISSUE TITLE
Update Background Player Notification To Use The New Android Q [10] Model

### ISSUE THREAD

**Issue by PeterHindes** [TeamNewPipe/NewPipe#2845]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

The Android Q media player notification is much improved over the current notification NewPipe uses. Allowing for seeking in the notification and some new animations. It might be time to update the notification.

**Comment by Stypox** [comment]
Also see #1660

**Comment by cool-student** [comment]
@PeterHindes check out my work in progress test apk
https://github.com/TeamNewPipe/NewPipe/issues/1660#issuecomment-578630151

**Comment by PeterHindes** [comment]
@cool-student Can you link me a pull request for that feature? I want to add it to a custom build for my use.

**Comment by cool-student** [comment]
@PeterHindes I'm still working on this and my code is a bit messy so there is no PR at the moment, my current eta is Wednesday (march 4th) for a PR.

**Comment by PeterHindes** [comment]
@cool-student Very cool. I guess pull request was the wrong word, do you have a repo online right now? I'm interested in the messy code ;P

**Comment by wb9688** [comment]
@cool-student: Just FYI: NewPipe is licensed under the GPL. The GPL requires you to provide the source code to anyone you've distributed a binary to within a reasonable time. I (or anyone else who downloaded one of your apk's) could sue you if you don't provide me the exact code you produced the apk's you've published from, though obviously I won't sue you. Next time it'd be smart to open a (draft) PR before you upload any apk's.
