### ISSUE TITLE
warrnigs

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#2847]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

whay get many warrnigs???
completed successfully | 2 m 3 s 772 ms
-- | --
Run build | 2 m 3 s 665 ms
Load build | 3 ms
Configure build | 188 ms
Calculate task graph | 129 ms
Run tasks | 2 m 3 s 242 ms
null |  
[kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (NON_INCREMENTAL), icepick.processor.IcepickProcessor (NON_INCREMENTAL), com.google.auto.service.processor.AutoServiceProcessor (NON_INCREMENTAL). |  
null |  
Missing class: javax.swing.JFrame |  
Missing class: java.awt.event.KeyListener |  
Missing class: javax.swing.filechooser.FileFilter |  
Missing class: javax.swing.JTable |  
Missing class: javax.swing.event.TreeExpansionListener |  
Missing class: java.awt.event.ActionListener |  
Missing class: javax.swing.event.DocumentListener |  
Missing class: javax.swing.event.TreeModelListener |  
Missing class: javax.swing.JInternalFrame |  
Missing class: javax.swing.tree.TreeModel |  
Missing class: javax.swing.JPanel |  
Missing class: java.awt.event.MouseAdapter |  
Missing class: javax.swing.table.TableCellEditor |  
Missing class: javax.swing.table.TableCellRenderer |  
Missing class: java.awt.event.KeyAdapter |  
Missing class: javax.swing.JDialog |  
Missing class: javax.swing.event.PopupMenuListener |  
Missing class: javax.swing.CellEditor |  
Missing class: javax.swing.tree.DefaultTreeSelectionModel |  
Missing class: javax.swing.JPopupMenu |  
Missing class: javax.swing.JMenuBar |  
Missing class: javax.swing.table.AbstractTableModel |  
Missing class: java.awt.event.ComponentListener |  
Missing class: javax.swing.event.ListSelectionListener |  
Missing class: javax.swing.JTextArea |  
Missing class: javax.swing.event.InternalFrameAdapter |  
Missing class: java.awt.event.WindowAdapter |  
Missing class: java.awt.event.MouseListener |  
Missing class: java.awt.event.ContainerListener |  
Missing class: javax.swing.JTree |

**Comment by Stypox** [comment]
Is this Android Studio (gradle) output?

**Comment by rahuldeshwal21** [comment]
> Is this Android Studio (gradle) output?

Yes but Normally  Not showing this line. :)

**Comment by Stypox** [comment]
When, at the first opening of the project, Android Studio asked you whether you wanted to update gradle or not, did you answer "No"?
