### ISSUE TITLE
Comments time translated wrong

### ISSUE THREAD

**Issue by Faeb35** [TeamNewPipe/NewPipe#2848]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi fellows,

I'm currently travelling in Japan, but I'm from Switzerland. So my settings for NewPipe are:
Preferred Content Country: Switzerland
Preferred Content Language: Switzerland

When I read comments here in Japan, the information, how long ago the comment has been posted is written in Japanese characters. When I make a VPN back to Switzerland, I get the characters in English. Nothing serious, but just wanted to mention this :-)

Thank you guys for providing this awesome software! I truly love it every day :-)

All the best,

Faeb35

![image](https://user-images.githubusercontent.com/9485516/70375109-741d5400-193d-11ea-8978-9ab3fb65bc42.png)
![image](https://user-images.githubusercontent.com/9485516/70375114-77184480-193d-11ea-8542-493bd5489fb8.png)

**Comment by B0pol** [comment]
Fixed by #2921 . Please close this @Stypox
