### ISSUE TITLE
Xiaomi Redmi Note 7+ JBL Tune 500 BT no audio?

### ISSUE THREAD

**Issue by cfv1984** [TeamNewPipe/NewPipe#2855]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hi! I'm using 0.17.4, downloaded it from your releases section. 

I can hear audio without the headphones, but not through them. Selecting external video and later external audio did not help in any way. 

Any ideas on how to troubleshoot this?

**Comment by TobiGr** [comment]
Hm strange. Do you use any custom ROMs or which Android version is installed on your device?

**Comment by cfv1984** [comment]
... Not really? Also, sound spontaneously came back when I re-linked the phone and the headphones, somehow

**Comment by opusforlife2** [comment]
So, no issue then? If there is still one, drop a comment.
