### ISSUE TITLE
Update is slow😂

### ISSUE THREAD

**Issue by jojoxl01** [TeamNewPipe/NewPipe#2857]
Why not update it? When will the new UI interface appear?

**Comment by cool-student** [comment]
I believe we're waiting for @mauriciocolli so he can rebase https://github.com/TeamNewPipe/NewPipe/pull/2309 after that we should be good to go. people are simply busy with other stuff (college, work, hobbies etc ...) such is always the case with open source projects.

**Comment by TobiGr** [comment]
@cool-student is right. We are quite busy atm (it is only a few days before Christmas, so there are plenty of other things to do). Nevertheless, my plan is to release a new version before Christmas.
Therefore #2309 will not make it into the next release. I'll bring out the first RC during the week.

**Comment by jojoxl01** [comment]
Thank you so much to all the developers for what they have done for this project in their free time, to bring such a good experience to users!!!

**Comment by TobiGr** [comment]
Closing in favor of #2861 and #2862.
