### ISSUE TITLE
出现recaptcha会循环崩溃

### ISSUE THREAD

**Issue by gsced** [TeamNewPipe/NewPipe#2866]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
Please use English and write a proper description, possibly with a crash report
