### ISSUE TITLE
Alllw directly opening videos

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#2869]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
Hello, can you add a toggle so that if I click a video, I am taken directly to the video player, skipping the video page that comes in between

**Comment by Stypox** [comment]
Could you give some feedback in #2583 ?

**Comment by nikhilCad** [comment]
That seems a better solution.
I hope that you continue with that.
