### ISSUE TITLE
videos suddenly became unavailable

### ISSUE THREAD

**Issue by Andre601** [TeamNewPipe/NewPipe#2872]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I use New Pipe for a few months now and it never gave any issues.
That said, I recently received the issue, that certain videos became unplayable.
The app shows the text "Content not available" with a grey background and a sad smiley on it. The video itself will be skipped when playing it from a playlist.
I didn't change a thing and the videos did previously work.

**Comment by gkeegan** [comment]
Do the videos work on the regular YouTube app or the YouTube website?

**Comment by Andre601** [comment]
Yes.
The videos do show and play in the YouTube app and on the website itself.
The videos, in particular, I had issues with are [`The Nightmare Before Christmas - This is Halloween - Acapella Cover (Lyric Video)`](https://www.youtube.com/watch?v=HN-W3kqwUlo) from Triforcefilms and [`Opia`](https://www.youtube.com/watch?v=Ftv6EaBD1UE) from Shirobon - Topic

**Comment by justanidea** [comment]
Both videos work for me with the last debug 0.18.0 app
Which version are you using?

**Comment by Andre601** [comment]
I use 0.17.1
I never received any notifications from F-Droid about updates so I assumed so far that I run the latest version.

**Comment by gkeegan** [comment]
@Andre601 what country do you live in? Can you try a VPN to another country to see if it isn't some regional blocking or something?

**Comment by Andre601** [comment]
I live in Switzerland and I can't (and honestly won't) use a VPN for multiple reasons.
Like I mentioned earlier did it work before and those two vides (so far) are the ones I can no longer get.

**Comment by gkeegan** [comment]
Using a VPN to Switzerland, I could not get Opia to load (didn't see the content not available, just kept loading forever after opening video), but the Acapella song did work.

**Comment by gkeegan** [comment]
Both worked fine in browser.

**Comment by primozcerar** [comment]
I too have the same issue.
Specifically this video: [https://www.youtube.com/watch?v=H-3rxh8kZHE](https://www.youtube.com/watch?v=H-3rxh8kZHE)

It works in browser and youtube app.

**Comment by opusforlife2** [comment]
All 3 videos linked here open and play fine for me on 0.17.4.

**Comment by Andre601** [comment]
And how do we update it?
F-Droid doesn't mention any update of NewPipe being available

**Comment by primozcerar** [comment]
Manually updated from 0.17.1 to 0.17.4 and it works.

Thank you.

**Comment by Stypox** [comment]
There is no new version, 0.17.4 is the latest and it was released some weeks ago

**Comment by primozcerar** [comment]
> And how do we update it?
> F-Droid doesn't mention any update of NewPipe being available

Go to updates in F-Droid and pull down to refresh.

**Comment by Andre601** [comment]
Seems to now work again.
