### ISSUE TITLE
Report crash directly to crash log server (do not rely on e-mail)

### ISSUE THREAD

**Issue by kekukui** [TeamNewPipe/NewPipe#2873]
NewPipe currently uses e-mail to report crashes -- but many phones & tablets do not have an e-mail service configured.  NewPipe should use an error log server or crash analytics service for automatic crash reporting.

https://duckduckgo.com/?q=crashlytics+alternatives

**Comment by cool-student** [comment]
I believe NewPipe already uses [ACRA](https://github.com/ACRA/acra) so crash reports are already reported automatically.

**Comment by kekukui** [comment]
After a crash, NewPipe asked if I want to send a crash report by e-mail.  There was no option to use another method like ACRA.  So if it wants to use only e-mail, then I must presume ACRA is not implemented, or the log server is unreachable.  If the server is unreachable, then it should inform the user, since they might have a firewall and just need to unblock the address.  So we still have some kind of user interface issue here. 🙂

**Comment by cool-student** [comment]
I'm not a NewPipe dev so I can only guess... I think @TobiGr was working on an improved crash report interface once but I can't find the issue. There's definitely room for improvement for the interface and also functionality.

**Comment by opusforlife2** [comment]
@cool-student #1816?

**Comment by opusforlife2** [comment]
Since the crash report can be directly copied in Markdown for Github, do we still want this?

**Comment by Stypox** [comment]
No, in my opinion, also because there would be more privacy issues

**Comment by opusforlife2** [comment]
Alright.
