### ISSUE TITLE
Player automatically resumes video after unlocking the phone

### ISSUE THREAD

**Issue by finn0** [TeamNewPipe/NewPipe#2874]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

NewPipe automatically resumes video after unlocking phone, even if, it was paused before locking the phone. Is it a feature or bug? I can't find any option in settings to disable this behavior.

### Steps to reproduce:
* Play any video.
* Pause it.
* Lock your phone using (un)lock button.
* Unlock the phone.

and wait for few seconds, video will automatically resume.

**Comment by Stypox** [comment]
Disable `Settings -> Video & Audio -> Resume on focus gain`, and tell me if it solves your issue

**Comment by finn0** [comment]
>Disable `Settings -> Video & Audio -> Resume on focus gain`, and tell
>me if it solves your issue

Thanks, it solved the issue. But I wonder, is this intentional? Because "resume on focus" feature should resume the video when video was paused due to some interruption like phone call (in these cases I didn't pause the video intentionally); then why does it resume the video when I intentionally paused the video. Isn't it a bug?

**Comment by bew** [comment]
Looks like a bug to me as well

**Comment by Stypox** [comment]
Yeah, this is a bug, but it has already been reported (though I could not find the other issue in the little time I have now). Also, there is an open pr that aims to solve this and similar issues: #2917

**Comment by finn0** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2239 and https://github.com/TeamNewPipe/NewPipe/issues/2391 (currently tracks it).
