### ISSUE TITLE
Mute button

### ISSUE THREAD

**Issue by RickyM7** [TeamNewPipe/NewPipe#2876]
It would be amazing if you could put a button to mute the app regardless of the volume of the smartphone, similar to what it has in MX Player, for example.  This function would be sensational.

**Comment by karkaminski** [comment]
I would like to take this one. Is it ok?

**Comment by RickyM7** [comment]
@karkaminski I don't know if I understand, because English is not my main language, but if you add this function to NewPipe, I would find it wonderful!

**Comment by Stypox** [comment]
@karkaminski I think you can take it.  But I'm not sure how this could be implemented without cluttering the GUI by adding a button that would be used rarely. @TobiGr what do you think?

**Comment by karkaminski** [comment]
Maybe adding this button to the upper drawer would be good? 

![image](https://user-images.githubusercontent.com/44138626/72499891-622faa80-3833-11ea-874b-7e98a97363cb.png)

**Comment by Stypox** [comment]
I thought about that, too, but how would it behave? Would its value be reset every time the video is opened or would the previous state be restored?

**Comment by karkaminski** [comment]
In my opinion: if you mute one video, you mute for every other video (if you have queue for instance). It corresponds with second scenario you've mentioned - restore previous state. 
Other questions are:
1. What after reloading whole app?
2. What when you muted the video, and after that picked "backgroud mode" or "popup window"? 
For popup I would keep it muted. Not sure if for backgroud should be the same. Maybe dialogbox asking if you want to unmute? I think it is a rare situation when one would like to have muted video in the background... ;)

**Comment by Stypox** [comment]
About the queue, as you said, the previous state should be restored.
1. After the whole app is reloaded, I'd reset the state to "Not muted". It would be strange if one used NewPipe always muted, so resetting upon restart seems a good choice.
2. The "Muted" state only makes sense in main and popup players, and since this is obvious, I don't think a dialogbox is needed.

**Comment by Stypox** [comment]
By the way, the button should be accessible from the popup player queue, otherwise how would one mute/unmute the popup player? Also, the plan with players is #2907, so it is a good idea to add buttons to queue views.

**Comment by karkaminski** [comment]
> 2. The "Muted" state only makes sense in main and popup players, and since this is obvious, I don't think a dialogbox is needed.

So, if user watches muted video, and use background option -> video should gone to background and unmuted ?

**Comment by Stypox** [comment]
Yes. Then, if the user goes back to main/popup player, the video should become muted again.

**Comment by RickyM7** [comment]
For some reasons I would mutate and use a muted background queue for a long time, so it would be nice if the button was implemented when playing a background playlist as well, and keep mutating as much as one wants, even if the queue  in the background, completely mute.  Since I'm not a programmer, I don't know how hard it is to implement something like that, but I hope you can do that.  (Sorry for my bad English, I'm using Google translate to translate.)

**Comment by Stypox** [comment]
Mmmh ok, then I assume adding a button to the background queue should be good @karkaminski.
@TobiGr what do you think about all of this?

**Comment by karkaminski** [comment]
I am still working on this, but I get some doubts... :)

I've added "mute-button" in 2 places currently:
1. In main player upper drawer (pic below)
![image](https://user-images.githubusercontent.com/44138626/72832202-b51abf00-3c84-11ea-9191-fe263a36523c.png)
![image](https://user-images.githubusercontent.com/44138626/72832229-c368db00-3c84-11ea-9dc1-5cf908cdba04.png)
2. In background player's menu in notification drawer
![image](https://user-images.githubusercontent.com/44138626/72832302-e4c9c700-3c84-11ea-8aac-876764dac7fc.png)
![image](https://user-images.githubusercontent.com/44138626/72832334-f317e300-3c84-11ea-9a1f-09af53fdf477.png)

Using "mute" funcion, user mutes the music chanel in Android:
![image](https://user-images.githubusercontent.com/44138626/72832508-4f7b0280-3c85-11ea-81f7-af2b9635af2b.png)

Is this approach we are looking for?

**Comment by RickyM7** [comment]
@karkaminski I liked the position of the buttons, however, muting the music channel is not what I expected.  I was thinking of something like muting the app's audio regardless of the Android music channel, as you can see in Mx Player when you disable the option to synchronize the volume of the sound with the system volume, for example.  So you could leave a muted list playing in the background while you listen to other things in another app or watch a muted video on Newpipe while listening to music with another app in the background.  I don't know if you could understand what I meant because of my English, but I hope so.  I also hope that what I said is possible to do.

**Comment by StyXman** [comment]
should I open another issue for 'mute by default?'

**Comment by karkaminski** [comment]
Sorry for delay guys.
I've implemented mute button in some places. I am wondering where else i should put it, so any advice/suggestions would be much appreciated. Check below screenshots. White icon = video is muted.
1. Main player
![Screenshot_1582480302](https://user-images.githubusercontent.com/44138626/75117252-1e209880-5670-11ea-8dc5-2ea9c6058a43.png)
![Screenshot_1582480331](https://user-images.githubusercontent.com/44138626/75117253-1fea5c00-5670-11ea-9a72-189b1bf67cf1.png)
2. Background player
![Screenshot_1582480649](https://user-images.githubusercontent.com/44138626/75117280-558f4500-5670-11ea-8792-5b691b68dd9c.png)
3. Popup player. I put mute-button just in notification drawer. I think there is to little place to put it there. 
![Screenshot_1582480695](https://user-images.githubusercontent.com/44138626/75117318-94bd9600-5670-11ea-9f2a-31b57055f785.png)

**Comment by wb9688** [comment]
@karkaminski: Do not put it in notifications, as we'll move to Android's standard media notifications, where that won't be possible.

**Comment by RickyM7** [comment]
@karkaminski

**Comment by RickyM7** [comment]
@karkaminski For me it's great, but if it won't work if it is in the notifications, as the friend said above, then I think you could add the mute button directly in that part where we control the list in the background. Anywhere in that area marked in orange the mute button would be fine.
![IMG_20200223_153737](https://user-images.githubusercontent.com/24703825/75117936-b01aa800-5654-11ea-9b4c-8e1c48641fab.jpg)

**Comment by Stypox** [comment]
@RickyM7 since it would be a feature used very rarely by just a few users it would be better to add it to the dot menu, IMO

**Comment by RickyM7** [comment]
@Stypox It will indeed be a rarely used feature, but it is still a good one. And for me I think that it doesn't matter where the button is, as long as it works, whether in notifications or anywhere else. (Sorry for my bad English.)

**Comment by karkaminski** [comment]
> @RickyM7 since it would be a feature used very rarely by just a few users it would be better to add it to the dot menu, IMO

I gave it a try. It doesn't look cluttered. What you think?
![Screenshot_1582498746](https://user-images.githubusercontent.com/44138626/75121986-c26b0500-5699-11ea-8359-0e9e7f9b720b.png)
![Screenshot_1582498750](https://user-images.githubusercontent.com/44138626/75121988-c434c880-5699-11ea-9e01-ba6d2a427215.png)
![Screenshot_1582499038](https://user-images.githubusercontent.com/44138626/75121990-c72fb900-5699-11ea-9711-b752ab3610a2.png)

**Comment by RickyM7** [comment]
@karkaminski In my opinion, this is wonderful.
