### ISSUE TITLE
Default Resolution & "Higher Resolutions"

### ISSUE THREAD

**Issue by AeliusSaionji** [TeamNewPipe/NewPipe#2878]
The current implementation allows you to select resolutions up to1080p, or "best available". There are resolutions above 1080p that are therefore inaccessible as default. In my case, I have a 1440p screen and there is no way for newpipe to select that resolution automatically- and the "best resolution" is usually 2160p.

The `show higher resolutions` toggle should show higher resolutions in the settings for `default resolution`, too.

While you're at it, #1090 could be addressed with a simple checkbox option: `play 60fps where available`. That would improve the UX and reduce confusion as well- it's currently very unclear if selecting 720p as the default resolution will choose 30fps over 60fps- and the "default quality" really should let you choose a framerate.

Thanks!

**Comment by Stypox** [comment]
Closing in favour of #2141. Pr open: #2968
