### ISSUE TITLE
{Add Feature}popup resize problem 

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#2880]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Add a feature for popup video player to easy resize it.
Problem -- Many time size so big and lock  screen size.
https://apkpure.com/popup-video-player-multiple-popup-video-player/toolsdeveloper.popupvideoplayer
like the app show the button..

image -- https://image.winudf.com/v2/image/dG9vbHNkZXZlbG9wZXIucG9wdXB2aWRlb3BsYXllcl9zY3JlZW5fMF8xNTI1MjA0OTM3XzA3MQ/screen-0.jpg?h=355&fakeurl=1&type=.jpg

**Comment by XiangRongLin** [comment]
You can resize it by pinching/stretching the popup with 2 fingers.

**Comment by Stypox** [comment]
@rahuldeshwal21 could you test the apk provided in #3075?
