### ISSUE TITLE
Won't play or download certain video

### ISSUE THREAD

**Issue by JohnVeness** [TeamNewPipe/NewPipe#2881]
Hi. NewPipe doesn't seem to want to play (spinner just keeps spinning) or download ("Download failed") this video:

https://youtu.be/kwYHnzyMeiE

All other videos that I've come across so far seem OK, just this one isn't working.

0.17.4.

**Comment by smilearric** [comment]
Could it be the same issue for this video?

https://www.youtube.com/watch?v=c8b1BRLZswI

Unexpected end of stream.

Still affecting 0.18 in this case.

**Comment by gillhash** [comment]
One more here
https://youtu.be/Liw-n_L0RG8

**Comment by gkeegan** [comment]
@gillhash what version are you using? That video plays fine for me and can start a download fine on 0.18.3.

**Comment by gillhash** [comment]
Video in question is live stream later uploaded video. This doesn't play in these formats:
MPEG-4 360p & 720p even with Latest 0.18.4 or 0.18.3 NewPipe.
It plays in Webm 720p. See also..
https://github.com/TeamNewPipe/NewPipe/issues/2683#issuecomment-590047997

**Comment by opusforlife2** [comment]
Probably 2415, if someone can confirm.

**Comment by Stypox** [comment]
Yeah, #2415 (@opusforlife2 it is ok to mention issues, I think)

**Comment by opusforlife2** [comment]
If they might be unrelated, I try not to, as it would just clutter the thread. See 2907.
