### ISSUE TITLE
"video not available" problem

### ISSUE THREAD

**Issue by sliceanddice9** [TeamNewPipe/NewPipe#2883]
It seems now that most videos do not play when I try to watch them on NewPipe. I just get a "video not available" message with a sad face image. I'm using 0.17.1 which is the latest version, have uninstalled and reinstalled, Ive tried clearing all history and catche etc  but the issue remains. It wasn't doing this a few days ago. Anyone know how to fix this?

**Comment by Stypox** [comment]
0.17.4 is the latest version. Anyway the issue is there, but we have no way to debug since it happens rarely and completely at random

**Comment by Classy-Cube** [comment]
Had the same issue and version, updated to the newest version resolved it for me.

**Comment by sliceanddice9** [comment]
Yep I did not know there was a 0.17.4 updated version. Downloaded and installed it last night and it fixed the problem for me.
