### ISSUE TITLE
Download - video, audio, captions can be checkboxes instead of radio buttons

### ISSUE THREAD

**Issue by contrapunctus-1** [TeamNewPipe/NewPipe#2885]
Didn't see a similar request despite much searching.

Currently, when one taps 'download', one is presented with radio buttons to select 'video', 'audio', and 'captions'. It may be nicer to change these to checkboxes.

**Comment by opusforlife2** [comment]
Is the goal just to be able to download these simultaneously, or do you want an option for captions to be embedded in the video?

**Comment by contrapunctus-1** [comment]
I believe players usually load the subtitles automatically, if the files have the same name...so embedding might not be necessary.

**Comment by Stypox** [comment]
Oh, now I see the use case, thank you. I am soon going to open a PR with a redesigned Download dialog, so I will try to find a way to suit your needs.

**Comment by opusforlife2** [comment]
Who's doing the download PR, @Stypox? You or @wb9688? I've seen both of you mention it here and there.

**Comment by Stypox** [comment]
I was doing it, then stopped, since it would imply migrating the database, and I have no experience with that. So I think wb9688 is going to do this in the future

**Comment by mehedihasanziku** [comment]
Still no progress of this suggestion, please make an option in backend, download auto subtitle of downloading video, if this option turned on, subtitle will be downloaded automatically otherwise it will not. This feature available on Tubemate, Please think about it

Thanks

**Comment by opusforlife2** [comment]
Closing in favour of #5534 because of proper explanation of use case.
