### ISSUE TITLE
Web Interface to Control Player

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipe#2888]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi,

I was wondering if it would be possible to have NewPipe to host a web interface on a LAN network so that the player can be controlled remotely. This would really be helpful along with the background player.

Thanks

**Comment by Stypox** [comment]
I think this would be better done with a separate app that acts like e.g. bluetooth headphones, that is communicating media actions to the app (which can already be done afaik)

**Comment by opusforlife2** [comment]
Accept or reject?

**Comment by FireMasterK** [comment]
I really don't think this should be a priority at the moment, there are so many other things that are more important than this, I think this should either be closed or put in a backlog of some sort.

**Comment by Stypox** [comment]
Yeah, this is out of scope for NewPipe, and as I said above could be accomplished with other apps
