### ISSUE TITLE
Deprecate TLS 1.1

### ISSUE THREAD

**Issue by danielzgtg** [TeamNewPipe/NewPipe#2898]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

#2792 enabled TLS 1.1 and TLS 1.2. However, there are concerns that TLS 1.1 is vulnerable. The whole web has already started phasing out TLS 1.1. If left enabled, it makes it easy to execute a downgrade attack.

Are we sure that we need both TLS 1.1 and TLS 1.2? If we only need the latter then it's better to have only TLS 1.2 enabled.

**Comment by TobiGr** [comment]
I agree. @mqus could you please check whether it is necessary to enable TLS 1.1?

**Comment by mqus** [comment]
No, we don't need TLS 1.1. Youtube, mediaCCC, Soundcloud and propably all peertube instances support tls 1.2 by now so 1.1 is not neccessary. 

Just to be sure though, TLS 1.1 was only "enabled" for Kitkat (Android 4.4.2) devices and fixing that is easy. I don't know what tls versions are enabled/disabled by default on the other androids, the [android docs](https://developer.android.com/reference/javax/net/ssl/SSLSocket) suggest that 1.1 and even tls 1.0 are enabled on all newer platforms by default.

But I also think that the security risk is limited, even browsers still have tls 1.1 enabled and Newpipe doesn't even handle information which is sensitive. 

So to summarize, I don't think we *need* tls 1.1 right now, but removing it does require a bit of work** which I find not worth the effort. We would also preserve a bit of backwards-compatibility in the *rare* case that a peertube instance doesn't support tls 1.2. But feel free to correct me if I'm wrong here.

**(for platforms other than kitkat)

**Comment by DI555** [comment]
the bad thing of dropping tls 1.1 will be dropping support andoid 4.4, am i wright? (if so , would be sadly)

**Comment by mqus** [comment]
no, not at all, #2792 added support for tls 1.1 *and* 1.2 , so just disabling 1.1 would totally be possible and easy for android kitkat. (I have only an android 4.4 smartphone myself and would like to keep running newpipe for a bit longer :wink:  )

**Comment by TobiGr** [comment]
Thanks @mqus. Can you create a PR to remove TLS 1.1, please?

**Comment by mqus** [comment]
Sure, but that will only apply for Android 4.4, all other android versions will have enabled TLSv1.0,v1.1,v1.2 and also v1.3 if new enough. 

Disabling TLSv1.1 (or TLSv1.0) for those other androids is something I would rather leave to a time when the browsers actually stop supporting TLS. I'm also not sure yet how to implement this. Adding TLS 1.2 for only a small subset of users (like I did) with a workaround is something i can get behind but using the same workaround to disable TLSv1.1/1.0 for ALL users is not something I would like to do and then confidently stand behind.

**Comment by bleedingcrow** [comment]
Will this force np to abandon kitkat users?

**Comment by mqus** [comment]
> no, not at all, #2792 added support for tls 1.1 and 1.2 , so just disabling 1.1 would totally be possible and easy for android kitkat. (I have only an android 4.4 smartphone myself and would like to keep NewPipe for a bit longer 😉 )

(Please read [above](https://github.com/TeamNewPipe/NewPipe/issues/2898#issuecomment-569454870))

To summarize: we'll keep tls 1.2 and disable 1.1.

**Comment by mqus** [comment]
While searching for a fix for #3021, I found https://guardianproject.info/code/netcipher/ .
This is mostly a generalized version of my workaround (#2792) and will enable the appropriate TLS versions and ciphersuites for the matching android versions. They don't include any ciphers or crypto on their own and just configure the built-in crypto of android (at least for now, they seem to look at including a wrapped version of the Google Conscrypt library and using it in older android versions). For example. they already disabled support for TLS 1.1 and 1.0 if 1.2 is enabled.

We could use NetCipher to replace `util.TlsSocketFactoryCompat` with their version and then apply it where it's needed. As I assume that they know more than me about Android & Connection security, we could just ride on their changes and save the effort for something else.

**Comment by mqus** [comment]
Tbh, I tried to implement it but got stuck on https://gitlab.com/guardianproject/NetCipher/issues/13. As long as that issue isnt solved, I can't really make progress.

**Comment by Redirion** [comment]
this project looks like it is not well maintained. If you check here: https://dl.bintray.com/guardianproject/CipherKit/info/guardianproject/netcipher/netcipher/

the last version that included the matching okhttp3 dependency was 2.0.0-alpha1

**Comment by opusforlife2** [comment]
Anything changed here?

**Comment by wb9688** [comment]
@opusforlife2: No, imho we should only do it as soon as we move to minimum Android version of 5.0, which has to be before the end of 2021.

**Comment by mqus** [comment]
tbh TLS 1.1 can be deprecated right now but the "how", especially on Android >=5 is not clear. For Android 4.4 this is simple.

**Comment by wb9688** [comment]
@mqus: Meh, there are quite some 4.4 devices not supporting TLS 1.2 unfortunately

**Comment by mqus** [comment]
@wb9688 There are? I thought that Android did support this on all devices but each app has to enable it, because it was "experimental" at the time. But I'm not an expert and device vendors do all sorts of terrible things.

**Comment by wb9688** [comment]
@mqus: That was the idea, however device vendors are indeed terrible ;)

**Comment by danielzgtg** [comment]
> But I also think that the security risk is limited, even browsers still have tls 1.0/1.1 enabled and Newpipe doesn't even handle information which is sensitive.

This is no longer true. [Chrome 84 (August 2020)](https://en.wikipedia.org/wiki/Google_Chrome_version_history) has [removed TLS 1.1](https://developers.google.com/web/updates/2020/05/chrome-84-deps-rems).

> Removing TLS 1.1 support for Kitkat

I now believe it's not worth the effort bothering to remove TLS1.1 for KitKat.

Old Android versions are end-of-life and don't get security updates. They have so many security vulnerabilities left unpatched whether due to Google discontinuing support or manufacturers' planned obsolescence. Of particular relevance to NewPipe are the infamous MediaServer vulnerabilities that plague Android and mean that just playing a video might allow someone to take over the device.

Trying to secure Android 4's TLS is like "locks on the chimney with the front door wide open." Only securing [Android 8 and other supported versions](https://en.wikipedia.org/wiki/Android_version_history) will make a difference.

**Comment by FireMasterK** [comment]
Can't we add TLS 1.3 support with https://github.com/google/conscrypt?

**Comment by mqus** [comment]
> Can't we add TLS 1.3 support with https://github.com/google/conscrypt?

I haven't looked at it but it should be possible. netcipher also planned to build on(/wrap) conscrypt... but as written above, it is sadly no longer maintained.

**Comment by Redirion** [comment]
> 
> 
> Tbh, I tried to implement it but got stuck on https://gitlab.com/guardianproject/NetCipher/issues/13. As long as that issue isnt solved, I can't really make progress.

@mqus there has been progress at Netcipher. 2.1.0 and 2.2.0alpha have been released with okhttp dependencies in April und May respectively: https://mvnrepository.com/artifact/info.guardianproject.netcipher

Do you want to give it another shot?

**Comment by ShareASmile** [comment]
Close ?

**Comment by danielzgtg** [comment]
Closing as I assume you're saying this is already implemented
