### ISSUE TITLE
Add gesture to change display brightness

### ISSUE THREAD

**Issue by utack** [TeamNewPipe/NewPipe#290]
Hi,

could you please consider adding a swipe up/down gesture to change display brightness?
That is extremely useful

Thanks

**Comment by 912d** [comment]
There is option in Android, that allows you to set brightness by swipe the status bar. 

Swipe up/down in left part of the screen like in Mplayer to set display brightness? This is great option. 
Maybe, by the way, we could add similar option to change level of sound, by swipe up/down in right part of the screen, though.

@theScrabi We can write this request on ExoPlayer page, and "outsource" our work to somebody ;- )

**Comment by theScrabi** [comment]
@912d right

**Comment by theScrabi** [comment]
@912d and yes please...
