### ISSUE TITLE
Add support for 1080p

### ISSUE THREAD

**Issue by utack** [TeamNewPipe/NewPipe#291]
As the title says, support for Full-HD and possibly more would be really nice. Thanks

**Comment by theScrabi** [comment]
I'm pretty sure this issue was requested a couple of times already. But my answer is still, we need proper support for ExoPlayer, since 1080p is not delivered as the other formats. 1080p comes without an audio stream, and mixing streams is not possible with the available players at the moment.

**Comment by utack** [comment]
Sorry, could not find any previous request.
Thanks for letting me know.
Hope it is planned at some point, mostly the 60fps would be nice.

Am 18. Mai 2016 01:28:50 MESZ, schrieb Christian Schabesberger <notifications@github.com>:

**Comment by doodhout** [comment]
Just a wild idea: would't it be possible to code a muxer that would merge these streams into a proper framed&timestamped container so that it can be passed on to a normal video player like with lower-res streams atm?

**Comment by doodhout** [comment]
It seems that another popular youtube-download-tool (https://github.com/rg3/youtube-dl/) has already implemented a workflow to download and mux 1080p files (of which there are several format incarnations on youtube, it seems), so it would be trivial and just a matter of copy and pasting their solution to get this working, I think.

**Comment by theScrabi** [comment]
Have you tried it with youtube dl? If yes you will find out it 1080p vids come along with no sound. Thats because the youtube player combines audio and video streams, which come separated. So in order to combine both streams and sync them we need a special player, and the build in player, as well as the external players are not capable of doting this. Exoplayer however can do this, but it had to be implemented first.

**Comment by smalltock** [comment]
theScrabi, if you call youtube-dl like this: `youtube-dl ${VIDEO_URL} -f bestvideo+bestaudio`
it will combine both streams.  When I want to watch a youtube video on the fly in full HD, I'll usually call it like this: `mpv ${VIDEO_URL} --ytdl-format=bestvideo+bestaudio` ... I think this uses ffmpeg, so it might be difficult to implement in newpipe.

**Comment by theScrabi** [comment]
Right thefore ... Expolayer xD

**Comment by utack** [comment]
Works great, especially 60fps makes a big difference
