### ISSUE TITLE
How does What's New work?

### ISSUE THREAD

**Issue by dmoa** [TeamNewPipe/NewPipe#2911]
How does the What's new tab work?

Any way to order it only by upload date?

Cheers.

**Comment by gkeegan** [comment]
There are two PRs working on sorting on by upload date.

**Comment by Monirzadeh** [comment]
any update on this issue?
it's so annoying first video on my whats' new is for 1 year ago !!!

**Comment by Stypox** [comment]
@Monirzadeh see #2309

**Comment by Monirzadeh** [comment]
Thanks @Stypox  so I should wait for merge

**Comment by justanidea** [comment]
There are some test apk provided in the pr so if you cant wait until merge you can use them

**Comment by nzlorca** [comment]
Please merge ;)

**Comment by denilsonsa** [comment]
Since #2309 has been merged, I think this issue can be closed.
