### ISSUE TITLE
Error in downloading video from youtube

### ISSUE THREAD

**Issue by khsuzan** [TeamNewPipe/NewPipe#2916]
I have a issue with cant find link when i am trying
 to download from youtube..and i am using v 0.18.0 
Here is a screen shot
![Screenshot_20200101-070732~2-picsay](https://user-images.githubusercontent.com/59402978/71637250-628f4980-2c68-11ea-9ce2-3336d059c1c7.png)

**Comment by khsuzan** [comment]
I faced that trouble in all video for download and the popup wont showing the download options

**Comment by Stypox** [comment]
Could you send here the shared content (you could do this for example by sharing it with a messaging app and the copying the message content)

**Comment by khsuzan** [comment]
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.18.0",
   "os": "Linux Android 8.1.0 - 27",
   "time": "2020-01-04 14:19",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method
'java.lang.String[] java.lang.String.split(java.lang.String)' on a null
object reference\n\tat
org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.find_access_cookies(ReCaptchaActivity.java:128)\n\tat
org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.onPageFinished(ReCaptchaActivity.java:113)\n\tat
cn.b(PG:2)\n\tat Lz0.handleMessage(PG:64)\n\tat
android.os.Handler.dispatchMessage(Handler.java:106)\n\tat
android.os.Looper.loop(Looper.java:164)\n\tat
android.app.ActivityThread.main(ActivityThread.java:6747)\n\tat
java.lang.reflect.Method.invoke(Native Method)\n\tat
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)\n\tat
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)\n"
   ],
   "user_comment": ""
}

**Comment by Stypox** [comment]
Convert it to Markdown please (the link to the converter should have been there when you created the issue)

**Comment by TGWGitHub** [comment]
Same issue, it happens on some videos not all.

Here is an example:

https://youtu.be/4WkoZZ319HU

**Comment by bunaif** [comment]
> Here is an example:
https://youtu.be/4WkoZZ319HU


![Screenshot_20200115-151306](https://user-images.githubusercontent.com/20098154/72429600-c9a11800-37a9-11ea-9d26-59dce5cbdda1.jpg)

**Comment by yvesined** [comment]
I'm facing this issued with almost every Video I want to watch or download and it ist not age-restricted:
https://youtu.be/t3yL6m-um50

Any help with this?

**Comment by opusforlife2** [comment]
Anything changed with 0.19.8?

**Comment by opusforlife2** [comment]
Guys can you test on 0.20.0? Make sure Age restricted content is ON and Youtube restricted mode is OFF.
