### ISSUE TITLE
Resizing popup player

### ISSUE THREAD

**Issue by Oizaro** [TeamNewPipe/NewPipe#2918]
Popup player doesn't incrementally scale its size with gestures, but follow fingers until these not moving to the end of lateral display edges.

A pinch to zoom way could be much better.

**Comment by Stypox** [comment]
Hold the finger on the popup to make it full-size

**Comment by Oizaro** [comment]
Oh thanks...its a great trick (in the meanwhile).

**Comment by Stypox** [comment]
@Oizaro could you test the apk provided in #3075?

**Comment by Oizaro** [comment]
@Stypox 

Tested and answered in dedicated thread posted by you 👍
