### ISSUE TITLE
Switch from fullscreen to popup player when leaving the app

### ISSUE THREAD

**Issue by sedrubal** [TeamNewPipe/NewPipe#2919]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

---

It would be great if newpipe automatically switches to picture in picture / pop-up player when you leave the full screen player e.g. by pressing the home button or app switcher button. VLC behaves the same way.

**Comment by Stypox** [comment]
This already exists in `Settings -> Video & Audio -> Minimize on app switch`
