### ISSUE TITLE
Cannot record live streams

### ISSUE THREAD

**Issue by solarelf** [TeamNewPipe/NewPipe#2920]
Hi devs,

I wonder is it "by design" or what, that NewPipe lacks ability to record (capture) live streams from YouTube streams? This feature would be a "rule changer" for emerging Android devices like Tabs, Samsung DeX etc., because currently there is only one possibility to capture streams - using PC.

Can you add the feature (if not yet added) to your todo list? Or otherwise explain us, why not?

Thank you!

**Comment by gkeegan** [comment]
Do you mean a screen recording or to download the files themselves from YouTube?

**Comment by Pentaphon** [comment]
> Do you mean a screen recording or to download the files themselves from YouTube?

He means download and save livestreams to disk as they are happening, but those livestreams are saved for later viewing on Youtube so its not really a big deal.

**Comment by opusforlife2** [comment]
@Pentaphon Except for those live streams that run 24x7, for example radio channels like Chilled Cow. I'm sure there must be others which are of more consequence than study music, though.

**Comment by gkeegan** [comment]
>those livestreams are saved for later viewing on Youtube so its not really a big deal 

Yeah that's why I asked. I already download live streams so I was confused as to what was meant here.

**Comment by opusforlife2** [comment]
Is this feasible?

**Comment by Stypox** [comment]
In my opinion it is out of scope for newpipe, since it would be a hard to integrate feature with a really really small usecase

**Comment by solarelf** [comment]
> > those livestreams are saved for later viewing on Youtube so its not really a big deal
> 
> Yeah that's why I asked. I already download live streams so I was confused as to what was meant here.

Well, sorry for late reply,

thank you everybody for your discussion here,

well, a live stream capture us what is sounds like, literally, not downloading a saved after-broadcast one. There are many online streams which are streamed but not recorded, so these could not be downloaded. However having an ability to directly capture, record and encode a stream as a named file saved locally, would change the way I organize my workflow dramatically, because now I have to use my PC for that task, and then export to my tablet the cuts, while I would prefer to do both the tasks on my mobile Tablet.

**Comment by solarelf** [comment]
> In my opinion it is out of scope for newpipe, since it would be a hard to integrate feature with a really really small usecase

You are missing the point... there are lots of bloggers nowadays who needs to be extremely mobile and on-the-go, 

> In my opinion it is out of scope for newpipe, since it would be a hard to integrate feature with a really really small usecase

I would not say we are few, too few to bother with the issue) there is a growing number of what is called "real-time bloggers" who are busy creating short "reactions" just on-the-site or on-the-go, so what they basically need is a mobile tool for live capturing shorts from 15 secs to dozen of minutes for later clipping and composing a "reaction" soon after live stream is ended.
