### ISSUE TITLE
Op7/Android 10 This permission is needed to open in popup mode.

### ISSUE THREAD

**Issue by famewolf** [TeamNewPipe/NewPipe#2922]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ n/a I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

One a oneplus 7 Pro running the latest Android 10 international firmware if set to minimize to the popup player when you hit home a small message appears over the home button saying "This permission is needed to open in popup mode" but it doesn't identify what permission.  Additionally I went into the permissions for Newpipe and the only one available is Storage which has already been allowed.  I assume you need permission to overdraw screens but it doesn't say that nor give me opportunity to enable it.   Since the app did not crash I didn't include that.  Reasonably certain it's either an oxygenos or Android 10 issue but figured I would provide the heads up.

Additionally when I chose the option to play in background it worked after a brief pause in the music however even after the song ended newpipe continued to cause excessive battery drain until Oxygenos flagged it and prompted me to force kill it.

![Screenshot_20200104-232707](https://user-images.githubusercontent.com/4558832/71775225-09b30000-2f4b-11ea-9d73-e2d027fdf32c.jpg)

**Comment by famewolf** [comment]
I did eventually resolve this by finding the permission to display over other apps and enabling newpipe there but in other occasions it's taken me exactly to where I needed to enable it.  I'll leave this open due to that but feel free to close if not of interest.

**Comment by harshlele** [comment]
I think the reason it doesn't send you to the settings is because the user is exiting the app, so forcefully sending them to the settings wouldn't be good.
One way this could be solved is to get the permission from the user right when the setting is enabled.

**Comment by harshlele** [comment]
@Stypox this happens on my device(Nokia 6.1) running Android 10 too, so i dont think its device specific. I tested it on a Android 6 emulator and there when you press the home button, it shows that toast, then takes you to the settings window, but then when you give it permission, it doesnt actually open the popup. I think this happens on any device running android 6 and above. 
I still think the permission should be asked when the user actually sets it to popup when home is pressed.

**Comment by TobiGr** [comment]
Fixed by #3004
