### ISSUE TITLE
[Feature request] Lock screen rotation status

### ISSUE THREAD

**Issue by MF-Debug** [TeamNewPipe/NewPipe#2925]
It would be very handy if we can lock the screen rotation to either portrait or landscape when viewing a video in any of the mentioned state so that the screen doesn't go back to another state while moving the phone.

**Comment by Stypox** [comment]
It already works this way... when I open a video fullscreen I can't change rotation unless I click the corresponding button: moving the phone does nothing

**Comment by MF-Debug** [comment]
i meant the behavior when auto-rotation is also enabled via the quick toggle menu

**Comment by Stypox** [comment]
Since the option already exists in the phone's quick toggle menu, I don't see the point of adding it to NewPipe

**Comment by TobiGr** [comment]
> i meant the behavior when auto-rotation is also enabled via the quick toggle menu


To lock the player orientation, tap on the screen and you'll se the normal overlay. Tap on the arrow on the right site to collapse a menu. Tap on the 
![image](https://user-images.githubusercontent.com/17365767/71819225-92d15080-308b-11ea-84db-1a462d824eae.png) icon to lock the player orientation.

**Comment by MF-Debug** [comment]
how could i haven't seen that button! that's what i needed, thank you!

**Comment by Stypox** [comment]
Closing in favour of #4500 as this refers to pre-unified and everything changed <sub>when ~~the fire nation~~ we developers attacked (sorry I could not stop ;-) )</sub>

**Comment by SameenAhnaf** [comment]
@Stypox I think, this issue still makes sense. Sometimes, the user only wants to lock rotation status, nothing else. What do you think??
