### ISSUE TITLE
In App Update Function Exist or Not ? If Yes where function? 

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#2927]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
 ----> I am new beginner programmer. i use newpipe version 0.17.0 so 0.18.0 is release  on github  an f-droid  it's manually process. not get notification in this app for app Update... :)

**Comment by Stypox** [comment]
If you installed via F-Droid then you just have to wait some time. If you want to get 0.18.0 right away then download it here: https://github.com/TeamNewPipe/NewPipe/releases

**Comment by rahuldeshwal21** [comment]
No.. No.. I talk about In app Update for without  going  anywhere  like  Facebook. With out  use  Google Play Service 
So  I find on Google for  this function but more Confusing. To this please support for Single  but Confusing problem🤔🤔

**Comment by yausername** [comment]
Do you see the updates section like in the screenshot below? If not then your have the fdroid version of the apk and you will have to download the apk from fdroid only.
![output](https://user-images.githubusercontent.com/5203007/71836135-604e4480-30d9-11ea-9230-e593300a96c2.png)

**Comment by rahuldeshwal21** [comment]
》》I compare both  versions so f-droid version not  showing update btn like ^^ this  image but github version  Showing  this  button . So learn  this  concept of notification  on open  newpipe app. What code  works  in Update btn  showing notification on update  is available... and  Go to  Link on click Notification Go to new  version link of Github

》》 github.../newpipe0.18.apk

Because  I clone  this  newpipe 0.17.4 app code  and I make Release Version of this App Code  Bundle . So this btn nI learn  about  this Function  so many  helpful  For  My  Other  Apps.  😀😀😀

**Comment by B0pol** [comment]
I'm closing since the question has been answered (no) and it won't be implemented (see https://github.com/TeamNewPipe/NewPipe/pull/3141)
