### ISSUE TITLE
hi.. Suggest How you Are Use in app update   like newpipe github Version 

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#2933]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

》》I compare both versions so f-droid version not showing update btn like ^^ this image but github version Showing this button . So learn this concept of notification on open newpipe app. What code works in Update btn showing notification on update is available... and Go to Link on click Notification Go to new version link of Github

》》 github.../newpipe0.18.apk

Because I clone this newpipe 0.17.4 app code and I make Release Version of this App Code Bundle . So this btn nI learn about this Function so many helpful For My Other Apps. 😀😀😀

**Comment by Stypox** [comment]
I am sorry, I do not understand

**Comment by rahuldeshwal21** [comment]
> notification  on App update  Is available  in newpipe

**Comment by Stypox** [comment]
This already exists, as you have been told in #2927
