### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by 62673** [TeamNewPipe/NewPipe#2936]
Hi
When im using new pipe sometimes the vídeo stop and my connection its good
Do you know what can i do ?

**Comment by Stypox** [comment]
There are [many issues](https://github.com/TeamNewPipe/NewPipe/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ayoutube) similar to this one, but this bug has not been resolved yet. A temporary solution could be to clear cache or reopen the video.
