### ISSUE TITLE
Formatter crash due to urdu alphabet

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#2940]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Urdu strings import_soundcloud_instructions and did_you_mean are causing crash.
Here is the crash log : 

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.18.0
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2641)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2602)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2770)
	at androidx.preference.ListPreference.getSummary(ListPreference.java:178)
	at androidx.preference.Preference.onBindViewHolder(Preference.java:584)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:381)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:45)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
</p></details>
<hr>
I exactly know why it's crashing  but can't fix it (alphabet weirdies)

The string in english : ```<string name="did_you_mean">Did you mean: %1$s\?</string>```
In urdu : ```<string name="did_you_mean">کیا آپ کا مطلب تھا: %1$s \?</string>```
as you can see %1$s is not in the right order

same for import_soundcloud_instructions : 
English : ```<string name="import_soundcloud_instructions">Import a SoundCloud profile by typing either the URL or your ID:\n\n1. Enable \"desktop mode\" in a web-browser (the site is not available for mobile devices)\n2. Go to this URL: %1$s\n3. Log in when asked\n4. Copy the profile URL you were redirected to.</string>```
Urdu : 
```<string name="import_soundcloud_instructions">URL یا آپ کی ID ٹائپ کرکے ایک SoundCloud پروفائل درآمد کریں:
\n
\n1. ویب براؤزر میں \"ڈیسک ٹاپ موڈ\" کو فعال کریں (سائٹ موبائل آلات کے لئے دستیاب نہیں ہے)
\n2. اس URL پر جائیں: %1 $ s
\n3. پوچھا گیا میں لاگ ان کریں
\n4. پروفائل یو آر ایل کاپی کریں جو آپ کو ہدایت کی گئی تھی.</string>```

If someone succes to make %1$s in the right order, it will be fixed.

**Comment by TobiGr** [comment]
Thanks!
We might need to add some scripts which check the translations for these kind of issues. I recently saw plural translations which did not have any `%1` arguments although the source strings had.
IIRC the F-Droid project wrote some python scripts to check translations. But I don't know what they do exactly.

**Comment by B0pol** [comment]
To be precise, with urdu :
Lines causing app crash :
+ [lines 196 and 197](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L195-L203) NewPipe can't even load. I fixed it in #2921 .
+ [line 356](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L353-L358) when you load subscriptions / import-export subscriptions / Soundclound. I didn't succed to fix.
+ [line 11](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L11) is causing app crash, I don't remember where because weirdly android studio says it has no usage.
+ [line 309](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L309) is causing crash on settings / appearance / scroll a bit

Lines that have %1$s wrongly written and it's not causing crash : 
+ [line 352](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L348-L352) is NOT causing crash but the link is not shown well :   [screenshot](https://user-images.githubusercontent.com/58657617/72166981-2d9a9980-33c2-11ea-8cff-bae010a34bb0.png)
+ [line 185](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L185)
+ https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L246


Lines that are missing %1$s or %s (then it's not causing crash but content is missing) :
+ [line 5](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L5)
+ [line 4](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L4)
+ [line 308](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L308)
+ [line 439](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L439)

**Comment by abusarimhindi** [comment]
> To be precise, with Urdu :
> Lines causing app crash :
> 
> * [lines 196 and 197](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L195-L203) NewPipe can't even load. I fixed it that (and only that) in #2921 .
> * [line 356](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L353-L358) when you load subscriptions / import-export subscriptions / Soundclound. I didn't succed to fix.
> * [line 11](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L11) is causing app crash, I don't remember where because weirdly android studio says it has no usage.
> * [line 309](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L309) is causing crash on settings / appearance / scroll a bit
> 
> Lines that have %1$s wrongly written and it's not causing crash :
> 
> * [line 352](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L348-L352) import youtube subscription : the link is not shown well :   [screenshot](https://user-images.githubusercontent.com/58657617/72166981-2d9a9980-33c2-11ea-8cff-bae010a34bb0.png)
> * [line 185](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L185)
> * [line 246](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L246)
> 
> Lines that are missing %1$s or %s (then it's not causing crash but content is missing) :
> 
> * [line 4](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L4)
> * [line 5](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L5)
> * [line 308](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L308)
> * [line 439](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L439)

Edited all above said strings.
Now reviewing all the translated Urdu strings.

I have previous experience of localization of some apps, i.e. Telegram, Mobogram, Facebook, Graph Messenger, etc. Also translated many bots of the Telegram.

**Comment by B0pol** [comment]
Great job!
I took the file from weblate and tested it, everything is solved except 1 strings:
> Lines causing app crash
> [line 356](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L353-L358) when you load subscriptions / import-export subscriptions / Soundclound.

@abusarimhindi

**Comment by abusarimhindi** [comment]
> Great job!
> I took the file from weblate and tested it, everything is solved except 1 strings:
> 
> > Lines causing app crash
> > [line 356](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-ur/strings.xml#L353-L358) when you load subscriptions / import-export subscriptions / Soundclound.
> 
> @abusarimhindi
> 
> By the way, I don't know if we can do something about it:
> Links are working, clickable, but are displayed badly: ![](https://camo.githubusercontent.com/03b319f282530f4ae93f82c05552b029638f246e/68747470733a2f2f692e706f7374696d672e63632f477234765a4a6d462f53637265656e73686f742d32303230303132342d3031333430322d4e65772d506970652d44656275672e706e67) ![](https://camo.githubusercontent.com/a88bacebd954876408882ea9c7fe745bdcfda6aa/68747470733a2f2f692e706f7374696d672e63632f72464a7074504d5a2f53637265656e73686f742d32303230303132342d3031333431312d4e65772d506970652d44656275672e706e67)

I checked and rectified.
The reason of this badly display is RTL & LTR combination. How could the URL start from RTL?

**Comment by abusarimhindi** [comment]
One problem is with me when I am applying Urdu language on the NewPipe app, the interface still remains in English.

**Comment by B0pol** [comment]
> One problem is with me when I am applying Urdu language on the NewPipe app, the interface still remains in English.

This is the normal behaviour, content language is used to get content with service, and the language displayed in NewPipe is phone's language.
In #2921 , I added a "NewPipe's language" selector, which allows to change the app language with only restarting the app, changing system's language is not needed.
The APK is available inthe last comment, if you wanna test

**Comment by B0pol** [comment]
I close this issue as it _will be solved_ as soon as someone update strings with Weblate.
Feel free to open an issue for the related problem that @TobiGr mentionned here https://github.com/TeamNewPipe/NewPipe/issues/2940#issuecomment-572476782, some other language are missing %1$s or %s.
