### ISSUE TITLE
Ability to select default 2K/4K resolution

### ISSUE THREAD

**Issue by RuthlessRuler** [TeamNewPipe/NewPipe#2941]
It would be good to have 2K and 4K resolution in default Resolution under settings. I know we can have them enabled it and select the best but for devices who have 2k display or people with slower internet where 4K gets a bit overkill, 2K becomes a sweetspot. So please see if this can be done.

**Comment by Stypox** [comment]
Isn't 2K just 1080p?

**Comment by B0pol** [comment]
> Isn't 2K just 1080p?
> https://en.wikipedia.org/wiki/2K_resolution

No, 2K, is originally from cinema, is really close to 1080p, but in common language 2K means 1440p.

**Comment by RuthlessRuler** [comment]
Yeah. 2K is 14440p and sometimes I like to view the 2K video on a 4K device due to my Slower Internet at different parts of My Home.

**Comment by theoasispc** [comment]
Any update on this?

Thanks

**Comment by Obscure2020** [comment]
Well, look at that. Made a duplicate issue. Whoops!

I'm here to throw my hat in the ring in support for this feature as well. Come on guys, this feature request's been around for TWO YEARS!

I'm in the 1440p display camp. I have a OnePlus 8 Pro, with a screen resolution of 1440x3168.

When the `Show higher resolutions` option has been enabled, then the `Default resolution` menu should add the options `1440p`, `1440p60`, `2160`, and `2160p`.

**Comment by theoasispc** [comment]
> Well, look at that. Made a duplicate issue. Whoops!
> 
> I'm here to throw my hat in the ring in support for this feature as well. Come on guys, this feature request's been around for OVER TWO YEARS!
> 
> I'm in the 1440p display camp. I have a OnePlus 8 Pro, with a screen resolution of 1440x3168.
> 
> When the `Show higher resolutions` option is enabled, the `Default resolution` menu should add the options `1440p`, `1440p60`, `2160`, and `2160p`.

Yeah it's been ages

With my Note 4 (1440p) and LG V20 (1440p) I use 2160p option until the meantime in the magical future when there will be a option of 1440p/60fps :))

I get that the 1440p club is niche but it's been too long imo.

**Comment by Obscure2020** [comment]
So the devs have refused to do anything about this **_basic_** feature for two years, but they happily close my duplicate issue mere _minutes_ after I open it.

Well now! We have solid proof the devs don't care about this project. I'm uninstalling and finding something else.

**Comment by theoasispc** [comment]
> So the devs have refused to do anything about this **_basic_** feature for two _years_, but they happily close my duplicate issue mere _minutes_ after I open it.
> 
> This does not look good for you, devs. Do you realize how many people are going to be checking out your app over the coming months? Vanced has been shut down, and guess what: nearly every webpage and article on the internet written for fans leaving Vanced mentions or recommends NewPipe.
> 
> If you don't have nearly every feature Vanced had within the next few months, you are going to disappoint a _lot_ of people.
> 
> And you don't have to do too much! NewPipe seems quite promising to me so far, as a new user. I've already managed to import my subscriptions, and I'm working on setting it up the way I like. You guys have a really solid base! You only need to make a few additions and changes to bring NewPipe closer to Vanced's glory. Just a few tweaks and quality-of-life changes here and there.
> 
> Like allowing people to set their preferred resolution to 1440p.
> 
> Come on, guys. It's just a bullet point in a menu. Vanced could do it. Make it happen.

Be patience. The devs don't get paid at all. I think someone in this another github newpipe thread had some code which worked and they were going to put it in but the user left.

**Comment by TiA4f8R** [comment]
> Come on, guys. It's just a bullet point in a menu.

Indeed, it's an easy change, which could be easily done by new contributors.

Also, please be respectful and avoid this behavior in the future. We are doing this on our free time (which is very little right now) and like theoasispc said, we are not paid for our work.

> I think someone in this another github newpipe thread had some code which worked and they were going to put it in but the user left.

You're right, the author of the PR linked around the top of the issue didn't continue their work.

**Comment by opusforlife2** [comment]
> So the devs have refused to do anything about this basic feature for two years, but they happily close my duplicate issue mere minutes after I open it. This does not look good for you, devs.

Ahahahahahaha-no. Not every issue maintainer is a developer, and vice versa. Sometimes, our assumptions come back to bite us. This does not look good for you, @Obscure2020.

> If you don't have nearly every feature Vanced had within the next few months, you are going to disappoint a lot of people.

So be it. In fact, I'm gonna have popcorn _while_ watching a lot of disappointed people.

> Come on, guys. It's just a bullet point in a menu. Vanced could do it. Make it happen.

Come on @Obscure2020, it's just a bullet point in a menu. Make it happen. Chop chop! Bet you could do it in 5 minutes. Stop wasting time and start coding!

----

### The point:

This is a volunteer FOSS project. Try to maintain the etiquette expected from users regarding FOSS projects, which you can find aplenty online. One example: https://gomakethings.com/open-source-etiquette/

**Comment by Coder246** [comment]
What’s the current state of this issue?
I can try to work on it…

**Comment by venkat2305** [comment]
Any update?

**Comment by AudricV** [comment]
Unfortunately, no, @Coder246 didn't apply our requested changes and closed their pull request since three months.

The issue can be taken by someone else.

**Comment by Edwardsoen** [comment]
i can try to work on this. 
Need this feature for my tab

**Comment by halfbytecode** [comment]
> i can try to work on this. Need this feature for my tab

I would really appreciate if this can be added, since a lot of the newer devices have native 1440p resolution. I would be thankful if this can we worked on!

**Comment by Ranzionu** [comment]
I also hope this will be added soon. My new tablet can't play 2160p60 videos, it for some reason just crashes. I had hoped NewPipe would fix this, but NewPipe also can't play 2160p60 yt videos. 1440p60 works fine tho, but the default of 1080p is too low, and "best available" crashes the video lol.

**Comment by Ranzionu** [comment]
> > I had hoped NewPipe would fix this
> 
> The app can't overcome a limitation of your hardware. If the device doesn't support it, the app can't play it.

The S5e had no issues playing these videos in the past, but ever since a youtube update 2 years or so ago it broke. Hence I hoped since NewPipe is a different player maybe NewPipe would not suffer from that bug.

**Comment by Edwardsoen** [comment]
finished working on this issue a while back, i think last time somee part of github was down causing the tests to fail. It would be greaat if someone can run the tests again
