### ISSUE TITLE
Title and notification bar

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#2945]
Hello, when I make full window I get in the same place the title of the video and the notification bar, is it normal?, my phone is huawei y7 prime 

![Screenshot_20200110-230046](https://user-images.githubusercontent.com/11852634/72189849-4032c400-33fe-11ea-9f12-ac53d8b92595.jpg)

**Comment by Stypox** [comment]
No, that's not normal. Have you tried waiting some time for controls to disappear and then tapping anywhere to make them reappear (hopefully without the notification bar)? Anyway, this is probably a device-specific issue, since I can't reproduce on Huawei p9 lite.

**Comment by heberjeur** [comment]
I used this version #2907 but in the normal version, it's OK
![Screenshot_20200112-175542](https://user-images.githubusercontent.com/11852634/72222438-f1ec0500-3564-11ea-89cc-af32239d00bb.jpg)

**Comment by Stypox** [comment]
Then go report the issue in #2907 ;-)
