### ISSUE TITLE
Redesigning the video downloader to use non-blocking I/O instead of threading?

### ISSUE THREAD

**Issue by h1nk** [TeamNewPipe/NewPipe#2946]
From my very minimal understanding, NewPipe currently implements the video, audio and caption download functionality in the app's source itself and not via a library dedicated to downloading YouTube videos? If my further understanding is correct, NewPipe also uses the variable amount of operating system threads that the user sets on a video download task to parallelize the process of downloading different chunks of the desired video. I'm just somewhat confused about the rationale of using operating system threads for download tasks instead of using non-blocking I/O since it's been readily available in Java SE for some time (see https://github.com/TeamNewPipe/NewPipe/issues/373#issuecomment-258250134). It just seems like the strict use of threads is a really inefficient way to go about accelerating I/O bound operations like downloading files over the Internet concurrently etc. Is there any specific reasons for this current design? Could this potentially make for a future improvement?

Edit: not sure if this issue would be more relevant to the "NewPipeExtractor" repository rather than the app itself?

**Comment by Stypox** [comment]
It has nothing to do with the extractor, this is the correct place.

**Comment by Stypox** [comment]
This is strictly related to #866 so I am closing in favour of that one. I copy-pasted what you wrote there, thanks :-)
