### ISSUE TITLE
Rotating thrice instead of once on exiting video

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#2948]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
When you play a video in landscape and your phone is in portrait mode, so almost all videos, on exiting the video, it will rotate to portrait (that's what we want), but then it rotates to landscape, and back to portrait again. It should only rotate once.

**Comment by opusforlife2** [comment]
Am I right in inferring that you're facing this issue on LOS 15.1? #1993

**Comment by B0pol** [comment]
I'm on [/e/ OS](https://e.foundation), and yes it is based on Lineage OS, and as my build is on android 8.1,it's basel on Lineage OS 15.1

I'm closing this issue then.

**Comment by B0pol** [comment]
Reopened because it can be fixed, and is fixed by #2907
