### ISSUE TITLE
Can't play "Nasty Freestyle"

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#295]
With this app I can play almost every video, except for [Nasty Freestyle](https://m.youtube.com/watch?v=hGKK8eGQQEk). It just keeps loading forever…

**Comment by theScrabi** [comment]
You propably use an old version. The newest one tells you it couldn't get stream information.

**Comment by wb9688** [comment]
I'm using the latest version from F-Droid: v0.7.8

**Comment by theScrabi** [comment]
Can you provide a link please.

**Comment by wb9688** [comment]
https://youtube.com/watch?v=hGKK8eGQQEk

**Comment by theScrabi** [comment]
I see something is different here...

**Comment by mauriciocolli** [comment]
No issue now.
