### ISSUE TITLE
Get remote  Update  Force update  newpipe 

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#2951]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug.

Get remote  Update  Force update  newpipe 
Get  Notification  on When Newpipe newest  Version  is available.

**Comment by Stypox** [comment]
This is already implemented in the GitHub version
