### ISSUE TITLE
XML: prefix must not be bound to one of the reserved namespace names

### ISSUE THREAD

**Issue by khurramengr** [TeamNewPipe/NewPipe#297]
Hy everyone.
While building the project in AndroidStudio I am getting the following error
**Error:(2) Error parsing XML: prefix must not be bound to one of the reserved namespace names** in almost all the translation files.
**\NewPipeYoutubePlayer\app\build\intermediates\res\merged\debug\values-de\values-de.xml.**
Can anyone assist me?

**Comment by khurramengr** [comment]
@theScrabi any clue?

**Comment by theScrabi** [comment]
Jup head that error before. Did you try to build with gradle 2.10? Because that does not work. You have to stick to 1.5 somehow.

**Comment by theScrabi** [comment]
I couldn't the origin of that error, but i think its weblate.
