### ISSUE TITLE
New Pipe not downloading audio/video error code

### ISSUE THREAD

**Issue by Kukulkan2019** [TeamNewPipe/NewPipe#2970]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Kukulkan2019** [comment]
It was working fine for months then all of a sudden it was not, uninstalled/reinstalled the app, latest version today, still not working. All settings are normal, the device is functioning normally, Android 9.0, the problem is on the New Pipe end.

**Comment by gkeegan** [comment]
What version of NewPipe are you using?

**Comment by gkeegan** [comment]
What region are you in? Mine works fine.

**Comment by gkeegan** [comment]
Also what error code do you get? Please use the bugreport to markdown converter.

**Comment by Kukulkan2019** [comment]
No error code specifically, just error, region Philippines


![Screenshot_20200119_100754_org schabi newpipe](https://user-images.githubusercontent.com/51299121/72673367-7cbc8a80-3aa4-11ea-9fb7-71a5cd9c0e68.jpg)
![Screenshot_20200119_100718_org schabi newpipe](https://user-images.githubusercontent.com/51299121/72673368-7d552100-3aa4-11ea-8bb5-c8737540b1a5.jpg)
![Screenshot_20200119_100700_org schabi newpipe](https://user-images.githubusercontent.com/51299121/72673369-7d552100-3aa4-11ea-9a35-b1a5f5ea43d3.jpg)


`

**Comment by Kukulkan2019** [comment]
Also, I'm using the latest version New Pipe, I just uninstalled /reinstalled about an hour ago and it was already the latest version... I have about 10 gigabytes of info downloaded into the SD card over the past 10 months all settings are the same, device and everything else functioning normally... All of a sudden not downloading, the same problem that crept up with many users not too long ago...

**Comment by gkeegan** [comment]
Why close this?

The video you showed in the screenshot isn't available in 480p on NewPipe. You can download in 720p in the meanwhile. 

@TobiGr it seems like some videos have missing resolutions.

**Comment by Kukulkan2019** [comment]
I accidentally closed the thing and there is no apparent way to reopen,
that's just a sample same video, it's happening across the board on a wide
variety of audio and video since last night...




Google gaming Archmage, legendary hero, great hero, EK League...

**Comment by Kukulkan2019** [comment]
There is nothing on this page to reopen, it's just showing a red box...

**Comment by Kukulkan2019** [comment]
Reoprn

**Comment by Kukulkan2019** [comment]
Note to self, I finally figured out how to reopen by default by simply making a new comment...

**Comment by Suchy1** [comment]
I have a problem with downloading audio from the newest NewPipe. I can download video, but when I want to download audio-only I'm getting error message saying that: "file can't be created". Any ideas what this could mean?

**Comment by Suchy1** [comment]
Ok, Fixed it, just changed folder for downloaded files and it works fine.

**Comment by AbsurdlySuspicious** [comment]
I'm able to download and watch this video in 360p but any attempt to do something with any other resolution fails:

- playing results in endless loading; nothing useful pops up in logcat while loading icon is on screen
- download fails in the same way as OP posted above

Link: https://youtu.be/xI9TWYjA5Ho

**Comment by Kukulkan2019** [comment]
![Screenshot_20200123_082617_org schabi newpipe](https://user-images.githubusercontent.com/51299121/72946495-14c6b680-3dba-11ea-90e9-480487ecb4fc.jpg) I got mine working again, but haven't extensively tested it, by unistalling & reinstalling the app and leaving the New Pipe system settings as is and into the SD card... previously I had changed the download folder for some reason... This is what they are set out now... ♞

**Comment by AbsurdlySuspicious** [comment]
Tried with clean data too (on 0.18.0 and 0.18.1) - no difference

**Comment by AbsurdlySuspicious** [comment]
0.18.2 doesn't fix that.

I also noticed that playable/downloadable resolution is different for different videos but always only single one is available. It's clearly visible if you take a look on format list at download dialog

**Comment by kaikun97** [comment]
I have this same problem. It looks like we are back to the older problem that happened in the past where some videos do not have the audio available for higher resolutions. This seems to be the case for a lot of music videos.

**Comment by opusforlife2** [comment]
Linking a previous comment of mine here because it's relevant. https://github.com/TeamNewPipe/NewPipe/issues/2673#issuecomment-583069389

**Comment by Kukulkan2019** [comment]
Chrome browser will not open new update 18.1 that just came out today... ♞

**Comment by gkeegan** [comment]
Open from files app.

**Comment by Kukulkan2019** [comment]
I don't know what a files app is, the New Pipe notification thing directs users to the browser... ♞

**Comment by Kukulkan2019** [comment]
If you mean the tablet built in files app, there is nothing in there concerning any update, for example, what would you expect to be in the internal storage or external storage unless I put it in there myself? (Rhetorical)... Thanks anyway, I already have the link... ♞

**Comment by opusforlife2** [comment]
@Kukulkan2019, if your problem is solved, please close the issue.
