### ISSUE TITLE
message notification stopping music player and videos always playing back to where it last stopped

### ISSUE THREAD

**Issue by jean-moltes** [TeamNewPipe/NewPipe#2973]
Hi newpipe team
Thank you for this amazing app.
I only faced two issues so far.
One being that every time I get a text message while playing a video on newpipe in any mode, it stops the video from playing. That can be kind of annoying.
Second being the fact that if I want to play a video that I've already played, it will start back from where it last stopped. This is a great feature but it would be even greater if there was an option to play these videos right from the beginning and not from where I left it.
Thank you guys, looking forward to see these kind of improvements.

**Comment by Stypox** [comment]
> every time I get a text message

Which messaging app does the message come from? Which Android version are you using? This is most probably an issue with the messaging app, that plays notification audio as Media and not as Ringtone.

> option to play these videos right from the beginning

Turn off `Settings -> History & cache -> Positions in lists`

Also: next time open two different issues if you have two different problems.
