### ISSUE TITLE
Low frame rate for 1440p and up? 

### ISSUE THREAD

**Issue by Fatcakes** [TeamNewPipe/NewPipe#2974]
I have been using this app for a few years now and it's never worked for me and I just assumed it was a bug that would get worked out eventually. I get around 10 fps for any video above 1080p60hz. Maybe it's the webm format? I'm using a nexus 6 and it has done it on every rom I have ever used. I'm currently on lineageos 15.1 oreo 8.1.0.

**Comment by Stypox** [comment]
Which resolution does your phone have?

**Comment by gkeegan** [comment]
Nexus 6 is 1440x2560.

**Comment by bleedingcrow** [comment]
Can you play 1440p videos smoothly in kodi?

**Comment by Fatcakes** [comment]
Yeah, Kodi plays YouTube fine in 1440p but anything above that chugs in the same way Newpipe does. It uses the webm/vp9 mpeg dash input adaptive format.

**Comment by opusforlife2** [comment]
Could this be because of a lack of hardware decoders for those codecs? There is a much higher chance that AVC would use hardware decoding on your phone than VP9. If the CPU struggles at software decoding, stutters will happen.

**Comment by opusforlife2** [comment]
@Fatcakes Does the problem still exist in 0.20.0?
