### ISSUE TITLE
Please define a download folder malfunction... 

### ISSUE THREAD

**Issue by Kukulkan2019** [TeamNewPipe/NewPipe#2975]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

A box prompting 'Please define a download folder' or some such term occasionally and annoyingly flashes unexpectedly at the bottom of the screen even after exiting the app, while on homescreen, or even in another app... What's funny about it in a strange and puzzling way is that I don't even have that setting activated, 'Ask where to save files' which is the only thing in the settings that even remotely has anything to do with that prompt... This has happened now since installing /unistalling the app twice, latest version, etc., showing you that there is some kind of problem with the downloading in the app's mind... I have downloaded some 10 gigabytes of info through New Pipe into the SD card over the past 10 months with relatively no problems until recently, all device permissions & settings are the same, all other device functions are functioning normally... ♞

**Comment by gkeegan** [comment]
I get this notification as well.

**Comment by Kukulkan2019** [comment]
Oh okay, no for me sometimes it prompts for no apparent reason... I also can't find this 'markdown converter' where is it? I looked in settings, but it's not there... Other than these recent download anomalies New Pipe is an outstanding app with no substitute that I know of and I have tried the open source Skytube & Webtube... One of the things I like about the New Pipe is the ability to download audio as well as video, no ads, and turn off suggestions, so the downloading is a big thing in my mind... 🦉

**Comment by Stypox** [comment]
The Markdown converter is used for bug reports. You can click on the link in the issue you wrote ("incredible bugreport to markdown converter" is a link). But you don't need it in this case, there are bug reports.

**Comment by Stypox** [comment]
Could you send a video of what happens before you get the out-of-place prompt?

**Comment by Kukulkan2019** [comment]
I'll check on the bug report thing later, I'll also try to get a screenshot
of the prompt or box, but it would be very difficult as it only appears for
a few seconds then disappears...



Google gaming Archmage, legendary hero, great hero, EK League...
