### ISSUE TITLE
Download all videos by playlist

### ISSUE THREAD

**Issue by evanoliv** [TeamNewPipe/NewPipe#2978]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
Duplicate of #1236, pr: #2018

**Comment by rithans** [comment]
> * [ ]  I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
> * [ ]  I checked if the issue/feature exists in the latest version.
> * [ ]  I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

1.  no,  in app there is option to only watch all the video from playlist

2.  to download one has to select them individually.
