### ISSUE TITLE
NPE on reCAPTCHA challenge

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#2979]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ FR
* __Service:__ none
* __Version:__ 0.18.1
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.find_access_cookies(ReCaptchaActivity.java:128)
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.onPageFinished(ReCaptchaActivity.java:113)
	at t6.b(PG:15)
	at ld.handleMessage(PG:43)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
</p></details>
<hr>
I was scrolling what's new in peertube.co.uk instance. It happens everytime I scroll to look at a few videos

**Comment by Neboer** [comment]
Same to me. Google ask me for recaptcha and newpipe will crask when I click the square.

**Comment by bleedingcrow** [comment]
Recaptcha is robot racism.

**Comment by Stypox** [comment]
Thank you, this is finally a reproducible ReCaptcha that can be looked into :-D

**Comment by Stypox** [comment]
Could you test this apk? The reCAPTCHA activity is shown, even though the website just shows "Too many requests", and the user can then press back or "Done" to exit. @B0pol @Neboer @bleedingcrow 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4119347/app-debug.zip)

**Comment by B0pol** [comment]
I can't install it, "the package appears to be corrupt."

**Comment by Stypox** [comment]
@B0pol did you unzip it? For me (on Android 7) the apk installs flawlessly.

**Comment by Stypox** [comment]
Here is a direct apk download link: [app-debug.apk](https://github.com/Stypox/NewPipe/releases/download/untagged-e35050f79c5922b192d5/app-debug.apk)

**Comment by B0pol** [comment]
Yeah of course
It doesn't run on both my phone and old phone
Your link returns a 404 page

**Comment by Stypox** [comment]
I didn't publish the release I used to upload the apk, here it is again, sorry: [app-debug.apk](https://github.com/Stypox/NewPipe/releases/download/for_apk_uploads/app-debug.apk)
