### ISSUE TITLE
Play protect 

### ISSUE THREAD

**Issue by mohamedelberkani** [TeamNewPipe/NewPipe#2980]
i have generate a signed apk but every time try to install it  the app blocked by play protect .
can have any solution 
![photo_2018-07-17_10-20-41](https://user-images.githubusercontent.com/44003568/72994122-d8657b80-3df6-11ea-82ab-2aacac175223.jpg)

**Comment by Stypox** [comment]
Doesn't it work if you press "Install anyway"?

**Comment by impreza233** [comment]
Press "Install anyway" or disable Play Protect in Play Store. This is a normal behaviour in that install monitor.

**Comment by mohamedelberkani** [comment]
yes i know that , i wanna not showing this message to users although the app not in store .
i wanna published the signed apk in other platform .

**Comment by TheFrenchGhosty** [comment]
You can't, this is a warning because google don't like when people install applications from a source that isn't them.

**Comment by mohamedelberkani** [comment]
if you try to install newpipe or snaptube or vidmate from uptodown or other platform you will not get play protect alert although this app its not live in store . so how can do that ?

**Comment by gkeegan** [comment]
@mohamedelberkani If you plan to publish the apk somewhere you MUST publish your source code.
