### ISSUE TITLE
Rename NewPipe to "NewestPipe".

### ISSUE THREAD

**Issue by castrated** [TeamNewPipe/NewPipe#2986]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [x ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Just a suggestion. Eventually, a competitor may arise, and by the name of "NewerPipe". Might as well beat them to the punch to declare this project as the newest possible pipe.

**Comment by gkeegan** [comment]
Stop trolling. Your post history is full of this crap.

**Comment by TheAssassin** [comment]
Oh dear... seriously? @gkeegan looks like you're right. Closing as trolling.

*Hint: there's a "report" feature on GitHub for issues... just saying...*

**Comment by gkeegan** [comment]
>Hint: there's a "report" feature on GitHub for issues... just saying...

Roger roger. @TheAssassin

**Comment by castrated** [comment]
methinks you fellas think i'm not serious.
each of the issues i create are dead serious. trolling contributes nothing to repos/projects, and i've advised against it on my website for a long time now.
if you would like, i can do a writeup to "contribute" to this issue, but beyond that i'm not sure what i can do...

**Comment by theScrabi** [comment]
@castrated have you considdered a Nintendo styled naming: New NewPipe?

**Comment by castrated** [comment]
@theScrabi why nintendo?
