### ISSUE TITLE
Decryption of video URL

### ISSUE THREAD

**Issue by champion174** [TeamNewPipe/NewPipe#2987]
This is the best Application I've ever seen.
It works well yesterday but now I can't able to play any of the videos in that. 
It's showing the error; could not decrypt the video URL signature.
Hope it'll be fixed soon

**Comment by gkeegan** [comment]
Duplicate of #2981.

Download the new release from GitHub. See instructions here: https://github.com/TeamNewPipe/NewPipe/blob/dev/README.md#Updates.

**Comment by tianxuefeng** [comment]
implementation 'com.github.TeamNewPipe:NewPipeExtractor:ff61e284'
Hi, use this!

**Comment by champion174** [comment]
thank you, got it
