### ISSUE TITLE
video unavailable :( but in browser all fine

### ISSUE THREAD

**Issue by f242** [TeamNewPipe/NewPipe#2988]
https://youtu.be/YR9b9NyOi1g
in v.18.2  i see splash with text "video unavailable :(", in previous v.18.1 was something like crash in this case but in browser it playing fine without authorization

**Comment by WheresAlice** [comment]
Possible duplicate of #2981 - please provide more information if that doesn't apply

**Comment by f242** [comment]
i think is not duplicate because link from #2981 playing fine

**Comment by Stypox** [comment]
Duplicate of #2900
