### ISSUE TITLE
Fallback players (browser or VLC) when the extractor is broken

### ISSUE THREAD

**Issue by Pentaphon** [TeamNewPipe/NewPipe#2989]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When Newpipe gets broken by Google, we should have an easy, obvious fallback method to play videos while waiting for a hotfix. 

When 18.1 was broken by Google today, I noticed 2 things:

1. The menu navigation and search was working fine and only playback produced an error. 

1. VLC was still able to play videos when sharing videos to VLC.

Even when Google breaks Newpipe's playback, Newpipe is still able to scrape information up until the playback of videos. 

Therefore, I propose the following 3 stage feature request;

1. An option in the settings menu called "Fallback Player" that allows users to select a fallback playback solution, whether it's the default browser, VLC or whatever other app can still play videos when Google has broken Newpipe. 

1. A play button on the error report page that when pressed, plays the video in the selected fallback player. 

1. When navigating through search results and channels, add another option to the "press and hold" menu that allows us to quickly open the video with our desired fallback player so we don't have to see the error report option when we know Google has broken Newpipe. 

Thoughts?

**Comment by opusforlife2** [comment]
Of course, if https://github.com/TeamNewPipe/NewPipe/issues/1981 is worked out, this wouldn't be needed.

**Comment by Pentaphon** [comment]
> Of course, if #1981 is worked out, this wouldn't be needed that badly.

It would still be useful to have a quick fallback because a) we still have to wait for the fix to be merged and released b) f-droid doesn't just automatically push the update to our phones as soon as the repo is updated

Also, I personally prefer to use the Github version since it updates Newpipe faster by notifying us as soon as Newpipe is opened.

**Comment by opusforlife2** [comment]
> f-droid doesn't just automatically push the update to our phones as soon as the repo is updated
The issue I linked is literally about addressing this very shortcoming.

I agree with point (a) though.

**Comment by brandsjek** [comment]
I don't see #1981 to make this obsolete. I can see why people don't want to use any repos not provided by F-Droid, and as @Pentafon noted there's still a notable amount of time between the issue being noted and a fix being pushed to the repo.

**Comment by opusforlife2** [comment]
Hopefully, https://github.com/TeamNewPipe/NewPipeExtractor/pull/297 will pull through.

**Comment by mhmdanas** [comment]
I understand why having an option to open the video in the browser when extraction is broken would be useful. However, I fail to see how it would be useful with external players. When NewPipe can't play a video, it would probably be because NewPipe can't extract the stream URL (if this assumption is mistaken, please ignore this comment, as my whole argument would be moot), so it wouldn't even be able to give the URL to an external player.

**Comment by opusforlife2** [comment]
I'm surprised I forgot to mention this here (though I did mention it in another issue): the youtube-dl version of mpv-android from a PR in that repo works perfectly fine. It even lets you update the youtube-dl version, so it's guaranteed to never break, or at least to be fixed pretty quickly.

We don't need any extra options or buttons here. You can just share the URL to mpv-android (youtube-dl).
