### ISSUE TITLE
'Could not play this stream' Error

### ISSUE THREAD

**Issue by 1emirozdemir** [TeamNewPipe/NewPipe#2992]
Hello, What is the reason I have been getting this error in videos since yesterday? How to fix

**Comment by B0pol** [comment]
duplicate of #2981
How to fix: download the latest version here https://github.com/TeamNewPipe/NewPipe/releases/, v0.18.2, the APK file, and open it to install.

**Comment by 1emirozdemir** [comment]
Thanks
