### ISSUE TITLE
[Question] Does Newpipe generate clicks?

### ISSUE THREAD

**Issue by RaihnerZufall** [TeamNewPipe/NewPipe#2994]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports

Does Newpipe generate Clicks on YouTube videos?

**Comment by Stypox** [comment]
No, NewPipe only downloads video info pages without sending any data about the user, so YouTube does not know whether you watched the video or not

**Comment by RaihnerZufall** [comment]
Thank you, good to know
