### ISSUE TITLE
Downloading this stream results in a corrupt video file

### ISSUE THREAD

**Issue by cool-student** [TeamNewPipe/NewPipe#2997]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I'm on:
Android 10
using NewPipe 0.18.2

I tried downloading this stream as video: https://www.youtube.com/watch?v=kB5d5w42Dis @ 1080p the resulting .mp4 file seems corrupt, when I try to play it using vlc it will only play as an audio file and when I try to play it with mx player it will play as a video but the screen stays black and when trying to seek mx player will simply play the next video file. 

I tried it first with SAF disabled and later I tried it again with SAF enabled but it makes no difference.

This is the first stream that I have encountered that has this oddity and I usually download 4 to 5 files per day.

Any idea @kapodamy ?

**Comment by B0pol** [comment]
I can confirm. I can only play audio with VLC

**Comment by kapodamy** [comment]
let me check

**Comment by kapodamy** [comment]
fixed in https://github.com/TeamNewPipe/NewPipe/pull/2959/commits/342377e69ae3157c0b11a03d32721b80844a0b7b
