### ISSUE TITLE
New Pipe still isnt working on latest install from FDroid

### ISSUE THREAD

**Issue by keshrum23** [TeamNewPipe/NewPipe#3002]
![Screenshot_20200125-074338_NewPipe](https://user-images.githubusercontent.com/48739804/73122101-7451cd00-3f46-11ea-87e0-0886211ab341.jpg)

**Comment by gkeegan** [comment]
FDroid hasn't updated NewPipe to 0.18.2 yet. Once that is available as an update it will work.
