### ISSUE TITLE
Fix App not installed in Android Marshmellow

### ISSUE THREAD

**Issue by mvincent514** [TeamNewPipe/NewPipe#3005]
Hi All,
As you all know, F-droid is kind of slow to update their repo as they have to make additional mods and checks and recompile.
So i couldn't access videos anymore with version 18.0 nor with version 18.1 and version 18.2 seems to have fixed the extractor issue but was not available yet in f-droid repo.
So I decided to pick the release 18.2 from github and install it in android marshmellow.
IT DIDN'T WORK, i was getting the msg: "App not installed" period.
So after some thought, i decided to get rid of the app completly and then install the github version... 
So, i made a backup of my history (which I love so much, thank you devs) and it was not straight forward to find : "settings->content-->export database", saved the zip file and went on uninstalling Newpipe FROM F-DROID APP MANAGER... i figured out if there was some key of any sort it would get erased.
Success this time!!! I could install the github version with no issues and even imported back my database and started enjoying NEWPIPE again.
Many thanks to the hard working devs!!!
I don't know if it's the right place to post this feedback, but I thought it can help others continue to enjoy Newpipe without having to switch back to youtube nasty player!!!
Feel free to close this issue or pin it until fdroid updates its repo.
Thanks again.

**Comment by TobiGr** [comment]
FYI. In our [FAQ](https://newpipe.schabi.org/FAQ/) it says:

> Maybe you installed the F-Droid version and want to update with an APK from GitHub or vice versa? Android does not allow app upgrades when the signing keys differ. This ensures the original developer has condoned the app.
> 
> This means, you need to either get the APK from the same source, or backup your NewPipe database, uninstall and reinstall the new app. Without a backup, current app data is lost, including subscriptions, history, playlists and settings. Follow [this tutorial](https://newpipe.schabi.org/FAQ/download/tutorials/import-export-subscriptions/#) to do so.
> 
> The final solution to this problem is to have reproducible builds for NewPipe in F-Droid. We are working on this with the F-Droid developers [here](https://github.com/TeamNewPipe/NewPipe/issues/1981).

**Comment by mvincent514** [comment]
@TobiGr thanks for pointing that out! I should have read the FAQ, my mistake... sorry!
Just wanted to help others by sharing experience!
My sincere apologies.

**Comment by TobiGr** [comment]
Thanks for posting the detailed walk through here. It helped me to realise, that we did not link to the FAQ in the readme. Your post helped a bunch of people, so there is no reason to apologise :)

**Comment by odman** [comment]
I walked through every step carefully and I still get the "app not installed" error. I am on android oreo huawei mate 10 lite.

**Comment by cool-student** [comment]
@odman it's possible that you uninstalled the app and the signature was not deleted you can remove it if you are rooted by doing
`su bash `
and then
`pm uninstall "org.schabi.newpipe"`
or via adb using similiar commands. There might be some other ways too.
