### ISSUE TITLE
Newpipe stopped working.

### ISSUE THREAD

**Issue by SanguineRose34** [TeamNewPipe/NewPipe#3006]
Since updating the app, everything I try to watch/background fails to load and says "could not play this stream". I've tried restarting the app, restarting my phone, uninstalling and reinstalling, and downgrading to an older version. I'm still getting the issue.

**Comment by boomer1ultimum** [comment]
Something went wrong! Could not decrypt URL Signature!

**Comment by justanidea** [comment]
Can you please read the previous threads???

**Comment by justanidea** [comment]
Or, better, update to 0.18.2

**Comment by mvincent514** [comment]
Try this fix:
https://github.com/TeamNewPipe/NewPipe/issues/3005
