### ISSUE TITLE
Need version 18.2

### ISSUE THREAD

**Issue by craven144** [TeamNewPipe/NewPipe#3009]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by craven144** [comment]
F-droid has version 18.1 it still doesn't work! It says could not play stream

**Comment by gkeegan** [comment]
FDroid takes a while to update. Use #3008 to get the new version.
