### ISSUE TITLE
When can resolve the problem for newpipe ?

### ISSUE THREAD

**Issue by monirul-bd1** [TeamNewPipe/NewPipe#3011]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by TobiGr** [comment]
Which problem? Please be more specific. We released version 0.18.2. Consider updating when using an older version.

**Comment by landry314** [comment]
nothing is loading at all. " could not decrypt video url signature

**Comment by TobiGr** [comment]
Please update to 0.18.2

**Comment by landry314** [comment]
im 100% updated. i deleted the app and reinstalled it. still, cant watch anything.

**Comment by TobiGr** [comment]
What version are you using? Where are you located?

**Comment by landry314** [comment]
oh sorry, i read other issues where it said the f-droid version is not updated yet. i am using 0.18.1. i'll wait.

if i get the apk off of github im worried the signature will be different and id have to manually check f-droid for 0.18.2 to get back in the update stream.

**Comment by landry314** [comment]
im in new york city.

**Comment by monirul-bd1** [comment]
Dear sir,

Many people use newpipe 0.17.3. Not working now. Please solve this problem soonest.

B. Regards!
Monirul.
     On Sunday, 26 January 2020, 2:41:20 AM GMT+6, Landry Racoon <notifications@github.com> wrote:  
 
 
oh sorry, i read other issues where it said the f-droid version is not updated yet. i am using 0.18.1. i'll wait.

if i get the apk off of github im worried the signature will be different and id have to manually check f-droid for 0.18.2 to get back in the update stream.

**Comment by monirul-bd1** [comment]
Dear sir,

Many people use newpipe 0.17.3. Not working now. Please solve this problem soonest.

B. Regards!
Monirul.


     On Sunday, 26 January 2020, 2:36:33 AM GMT+6, Tobias Groza <notifications@github.com> wrote:  
 
 
What version are you using? Where are you located?

**Comment by monirul-bd1** [comment]
Dear sir,

Many people use newpipe 0.17.3. Not working now. Please solve this problem soonest.

B. Regards!
Monirul.


     On Sunday, 26 January 2020, 2:31:01 AM GMT+6, Tobias Groza <notifications@github.com> wrote:  
 
 
Closed #3011.

**Comment by monirul-bd1** [comment]
Dear sir,

Many people use newpipe 0.17.3. Not working now. Please solve this problem for old version soonest.

B. Regards!
Monirul.

     On Sunday, 26 January 2020, 2:14:53 AM GMT+6, Tobias Groza <notifications@github.com> wrote:  
 
 
Which problem? Please be more specific. We released version 0.18.2. Consider updating when using an older version.

**Comment by gkeegan** [comment]
How are people supposed to fix the old version without an update? Just use 0.18.2.
