### ISSUE TITLE
How do I download/open the 0.18.2 Newpipe?

### ISSUE THREAD

**Issue by jimmyrustles** [TeamNewPipe/NewPipe#3014]
Hi guys, I'm a complete noob so forgive me if I'm not sure how to do this properly. How do I actually download and open this new version of Newpipe? I take it you have to go to this page ![Screenshot_20200127-072659](https://user-images.githubusercontent.com/5096684/73142133-1b656e80-40d7-11ea-9584-b930c4bb080b.png) and select 'download link'? I've done that but I only have an app called 'Files' on my phone, I go to Downloads 
![Screenshot_20200127-074051](https://user-images.githubusercontent.com/5096684/73142253-79468600-40d8-11ea-8892-4a6d04fdeacb.png) but I can't open it
![Screenshot_20200127-074043](https://user-images.githubusercontent.com/5096684/73142266-8c595600-40d8-11ea-9f13-5570a8a30739.png) is there another app I should be using to open exe's on Android or something? Please help.

**Comment by gkeegan** [comment]
The files you are downloading aren't the apk, or aren't downloading properly somehow. The size of the files is way too small.

https://github.com/TeamNewPipe/NewPipe/releases/download/v0.18.2/NewPipe_v0.18.2.apk

Open that link in browser and download. You should be able to install from the files app.

**Comment by jimmyrustles** [comment]
Thanks mate.
