### ISSUE TITLE
Bugreports unusable

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#302]
Hello,

today I've tried to evaluate the bug reports people send me all the time. But somehow Mail clients destroy the json format inside the mail, and render the report unusable. Me and a colleague at my university are trying to reconstruct the json data, but for the future we need to change the way bug reports are send.
I just wanted to ask if you have any idea how to get the reports to me via mail without destroying the contend. Base64 or don't use json?

rgds schabi

**Comment by wb9688** [comment]
That's because of some limitations of e-mail. It would be much easier to
not use e-mail at all…

**Comment by theScrabi** [comment]
I had this discusion with a fried. It's just that i want it transparent for the user.

**Comment by SirCmpwn** [comment]
I'll write up and host a simple service to receive and store bug reports as json over HTTPS if that would be useful to you.

**Comment by wb9688** [comment]
Maybe you can have a Firefox-like bug/crash reporter: ![Firefox Crash
Reporter screenshot](
https://support.cdn.mozilla.net/media/uploads/gallery/images/2013-07-05-02-40-13-88a20a.png).
When you press the "Details…" button it shows a popup with the JSON data to
be sent…

**Comment by theScrabi** [comment]
A friend of mine suggested to use Sentry would that be a sutable solution. I'd like it, what would you think?

**Comment by timofonic** [comment]
use k9. Is this guilty of that? I sent many crash reports. 

My email is my username.

**Comment by theScrabi** [comment]
My colleague wrote a backed for sentry, so that reporting through e-mail will keep being the same.
@wb9688 Is the the Sentry fronted the free software?

**Comment by theScrabi** [comment]
[Here](https://github.com/getsentry/sentry). I think he said to me he wanted to set it up at a local server, so we will not use their service.

**Comment by wb9688** [comment]
Ah, that makes sense…

**Comment by theScrabi** [comment]
He also said that reconstructing json files wasn't that bad. Some bugreports are unusable by now, but the most are usable.
