### ISSUE TITLE
Can't Play Videos + Error Page

### ISSUE THREAD

**Issue by Norman191** [TeamNewPipe/NewPipe#3020]
After choosing any video to play it, i got the **Error Report Page**.
And looking for the issue using android studio we got this :

**Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern ";([A-Za-z0-9_\$]{2})\...\( inside of var kea=function(a){a=a.split("");var b=[-184395239,-1302549814,-919195204,-1448551649,1167263185,function(c,d){for(d=(d%c.length+c.length)%c.length;d--;)c.unshift(c.pop())};"**

in java class [**ExtractorHelper.java:115**]

Any help or update please ?

**Comment by Stypox** [comment]
Fixed in 0.18.2

**Comment by Norman191** [comment]
Thank you.

Is there a java code instead of kotlin ?

**Comment by Stypox** [comment]
This app is built in Java (a part from some recent Kotlin additions)
