### ISSUE TITLE
Recaptcha crash on app open

### ISSUE THREAD

**Issue by snow-frog** [TeamNewPipe/NewPipe#3023]
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [x ] I did use the [incredible bugreport to markdown converter]

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.18.2
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.find_access_cookies(ReCaptchaActivity.java:128)
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.onPageFinished(ReCaptchaActivity.java:113)
	at e6.b(PG:2)
	at on.handleMessage(PG:63)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8147)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

```
</p></details>
<hr>

**Comment by Stypox** [comment]
Which service were you using?

**Comment by snow-frog** [comment]
I'm not sure what you mean. Just opening newpipe leads me to a captcha and crashes it, probably fetching the "Hottest" videos (which is always youtube-curated i never watch and could do whitout entirely)

**Comment by Stypox** [comment]
Ok, thanks. I will provide a fix in a few hours

**Comment by Stypox** [comment]
@snow-frog could you test this apk? The reCAPTCHA activity is shown, the user can resolve the reCAPTCHA (or follow the instructions, or do whatever they want), and then press back or "Done" to exit.
[app-debug.apk](https://github.com/Stypox/NewPipe/releases/download/untagged-e35050f79c5922b192d5/app-debug.apk)

**Comment by snow-frog** [comment]
I'm not getting the recaptcha anymore on the production app or the debug one, i cant say if it works sadly

**Comment by Kellett** [comment]
I'm also having this issue. I tried the APK @Stypox posted and it didn't help.

**Comment by Stypox** [comment]
What does it mean that it didn't help? @Kellett 
Also, please try the apk in #3037
