### ISSUE TITLE
Please push v0.18.2 to F-Droid

### ISSUE THREAD

**Issue by primozcerar** [TeamNewPipe/NewPipe#3024]
We need the update to resolve [#2981](https://github.com/TeamNewPipe/NewPipe/issues/2981).
It's been 4 days since a fix has been committed. Please push it to F-Droid.

Thank you for your continued work on NewPipe.

**Comment by primozcerar** [comment]
Closed without a comment and update not available in F-Droid?

**Comment by ChiefMikeK** [comment]
[NewPipe | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/en/packages/org.schabi.newpipe/) it takes a few days for an update to get published please be patient, remember that they are not a humongous corporation and 

> **F-Droid is powered by your donations!**

**Comment by Stypox** [comment]
It was closed without comment because it was a duplicate of many many other issues

**Comment by primozcerar** [comment]
I don't wish to sound ungrateful but I don't see another issue asking for version 0.18.2 on F-Droid.
Asking for the same thing in a different context is not a duplicate in my opinion.
