### ISSUE TITLE
"seconds" string is not available for translation

### ISSUE THREAD

**Issue by bboa** [TeamNewPipe/NewPipe#3025]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hey friends, please add ["seconds"](https://github.com/TeamNewPipe/NewPipe/blob/5bf1df9f1403cbd4de9d9cc7d4f8945ac98ef29e/app/src/main/res/values/settings_keys.xml#L33) string to able translate it. [https://imgur.com/r1wAow8](https://imgur.com/r1wAow8)

 #translation #localization

**Comment by TobiGr** [comment]
The hardcoded strings must be remove [here](https://github.com/TeamNewPipe/NewPipe/blob/5bf1df9f1403cbd4de9d9cc7d4f8945ac98ef29e/app/src/main/res/values/settings_keys.xml#L33) and a formatted string requested [here](https://github.com/TeamNewPipe/NewPipe/blob/2d39e65b5cf204ea80d74c7d7919315bbfbd6d8e/app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java).

**Comment by B0pol** [comment]
It will be fixed by #2944 if merged
