### ISSUE TITLE
How do you Update new pipe /new pipe legacy. Need steps 1-however many steps!

### ISSUE THREAD

**Issue by craven144** [TeamNewPipe/NewPipe#3029]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
Either wait for Fdroid to provide you with another version or uninstall the app and reinstall it from the apk provided in releases.

**Comment by Stypox** [comment]
See #3005
