### ISSUE TITLE
Unrecoverable Player Error

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3036]
720p/480p won't play. 
there is a message w/o actual error page, just a small message that disappears after a second. 

360p works fine.

v18.2

**Comment by Stypox** [comment]
Duplicate of #2673

**Comment by eladkarako** [comment]
doesn't seems to be related, it isn't webm, but mp4 stream.

**Comment by Stypox** [comment]
Both issues are about missing resolutions and would be fixed by the same thing, most probably
