### ISSUE TITLE
"Resume on focus gain" doesn't work with browser

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3047]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

On spotify, when you listen to music, then go play another media, eg youtube video, it pauses the music, like newpipe does.
But Spotify resumes the music when you paused or left the media.

I think this is a cool feature, and would be great to have in NewPipe, for the background player and the popup player.

**Comment by TobiGr** [comment]
There is an option in den video and audio settings, called "Resume on focus gain".

**Comment by B0pol** [comment]
Yeah, but it doesn't cork with browser, spotify,
Works with newpipe and vlc tho.

**Comment by Stypox** [comment]
Closing in favour of #3481
