### ISSUE TITLE
Audio stops working after 6:21

### ISSUE THREAD

**Issue by depner** [TeamNewPipe/NewPipe#305]
Hi Chris,

first of all thanks for all your work and for releasing it as FLOSS! :)

I've encountered a bug on my Samsung Galaxy S5 (klte) running Android 6.0.1/CyanogenMod 13 and NewPipe 0.7.8 downloaded via F-Droid.
Everytime I play a video immediately after playing a video for exact 6 minutes and 21 seconds the sound turns off somehow. It is reproduceable with any video, the bug(?) even comes up if I start watching a video on any other timeslot - after 6 minutes and 21 seconds the sound is gone. The only workaround I've found so far is to go back to the search results and watch the video again from the point where the audio stops.

However, I didn't have the ability to check this on another device so maybe it is just me having this issue.

Have a nice day!

Gerrit

**Comment by theScrabi** [comment]
Have you tried using an external player?

**Comment by depner** [comment]
The audio did not stop on the external player (VLC 1.9.0)

**Comment by theScrabi** [comment]
All right then. It may be the android build-in player again. We try to switch to another player anyway.

**Comment by CarbonFixer** [comment]
Have this issue on two phones (S4 mini and nexus 5x), both running CM13 without gapps, installed from f-droid.

**Comment by kvnco** [comment]
My issue is a bit different but may be related: videos played are stopped after 6:21 and cannot be resumed. The only workaround I found is the same as @depner (going back to the search results and watching the video again from this point).

It looks reproducible every time with lots of (every?) videos.
Running NewPipe 0.8.7, installed from F-Droid, on a Moto X Play with Android stock 6.0.1.

**Comment by CarbonFixer** [comment]
I think it's fixed for me after upgrading to Lineage OS 14.1 from CM13.

**Comment by amatus** [comment]
I'm having this same issue with 0.8.7 on my Nexus 6 with Omni ROM 6.0.1

**Comment by mauriciocolli** [comment]
If it still happening, tell me.
