### ISSUE TITLE
Accessing YouTube videos needs completing Captcha.

### ISSUE THREAD

**Issue by NazcaLine** [TeamNewPipe/NewPipe#3050]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
This is the normal and intended behaviour

**Comment by Stypox** [comment]
Oh, sorry, for some reason I thought you were already using the fixed version... could you please test the apk provided in #3035?

**Comment by Stypox** [comment]
Here is a direct link: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4145262/app-debug.zip)

**Comment by NazcaLine** [comment]
It works!

Thanks and closed.
