### ISSUE TITLE
Main to popup

### ISSUE THREAD

**Issue by vkhomenk** [TeamNewPipe/NewPipe#3051]
Changing from main view to popup opens both popup and background playback and randomly choses one to play.

**Steps to reproduce:**
1. Click on youtube video to open main view.
2. Go to popup view.
3. Opens both popup and background and plays one of them.

**Expected behaviour:**
...
3. Opens popup and plays it

**Configuration:**
Oneplus 7
Android 10
OxygenOS 10.3.0GM57AA

**Comment by Stypox** [comment]
After 1. and 2. are there two notificantions in the app bar, one for the background player and one for the popup player?

**Comment by Stypox** [comment]
Duplicate of #2070

**Comment by vkhomenk** [comment]
Yes there are two of them
