### ISSUE TITLE
Twitching in portrait view

### ISSUE THREAD

**Issue by vkhomenk** [TeamNewPipe/NewPipe#3052]
**Steps to reproduce:**
1. Click on youtube video to open main view.
2. Turn to portrait view and wait second till controls disappear.
3. Tap to reveal controls.
4. Video jumps up for a moment.

**Configuration:**
Oneplus 7
Android 10
OxygenOS 10.3.0GM57AA
NewPipe 0.18.3

[video_2020-02-04_12-53-58.zip](https://github.com/TeamNewPipe/NewPipe/files/4152831/video_2020-02-04_12-53-58.zip)

**Comment by opusforlife2** [comment]
Drop a comment if the problem still exists in 0.19.8.
