### ISSUE TITLE
Playlist dragging/editing is too easy to get mistriggered when scrolling with single hand

### ISSUE THREAD

**Issue by dogtopus** [TeamNewPipe/NewPipe#3054]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

As long as the scrolling happens on the edge of the screen (which is very common for me if I scroll through the playlist with only a single hand) NewPipe thinks it's a dragging event. Due to this, I ended up with a playlist with messed up order most of the time when I try to scroll with one hand. This is especially true when I used my left hand because the thumbnail area is really big compared to the right side which only has a small icon that triggers the dragging.

I would suggest to change the dragging gesture to a long press on the thumbnail or the icon on the right side to minimize the chance of mistriggering.

**Comment by Stypox** [comment]
This would be fixed by #2583 if I get to implement it

**Comment by opusforlife2** [comment]
Add 'fixes' linkage in that case?

**Comment by Stypox** [comment]
No, this has not yet been fixed

**Comment by litetex** [comment]
Closing this issue in favor of #6544.

Also:
> As long as the scrolling happens on the edge of the screen

Scrolled on the left side down and had no problems.
This happens on the right side as there is a rearrange button.
