### ISSUE TITLE
this is a feature request.

### ISSUE THREAD

**Issue by benchpress826** [TeamNewPipe/NewPipe#3056]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by gkeegan** [comment]
If you have a request please add it or this will end up being closed.

**Comment by benchpress826** [comment]
Microphone feature must be found in the search section

search filter must be available


![20200205_013503](https://user-images.githubusercontent.com/60674025/73793734-0912c100-47b8-11ea-98ec-a852c0db9d48.jpg)

![20200205_013536](https://user-images.githubusercontent.com/60674025/73793790-22b40880-47b8-11ea-8188-279d354d4ee4.jpg)


must be what appears in the photos.

**Comment by benchpress826** [comment]
Thank you for your interest 🙏🙂

**Comment by Stypox** [comment]
What would that microphone do?
