### ISSUE TITLE
Information playback problem

### ISSUE THREAD

**Issue by ldxw** [TeamNewPipe/NewPipe#3061]
When the message comes, it will stop playing automatically. You need to click manually to continue playing

**Comment by gkeegan** [comment]
Can you explain your issue more please and add more detail?

**Comment by ldxw** [comment]
> Can you explain your issue more please and add more detail?

![stop.gif](https://i.loli.net/2020/02/05/iPDOIWQqxNw3vLg.gif)

**Comment by ldxw** [comment]
Resolved, focus recovery turned on, thank you
