### ISSUE TITLE
reCAPTCHA challenge

### ISSUE THREAD

**Issue by T-rex2017** [TeamNewPipe/NewPipe#3062]
Not able to play video's or even open info section.  While it loads it shows this screen and when it finishes shows a browser version of YouTube 
Haven't checked other things 
![Screenshot_2020-02-05-16-58-31](https://user-images.githubusercontent.com/29393932/73838892-b9290e00-483a-11ea-927d-c24053c9ec98.png)
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
Try the apk provided in #3035
