### ISSUE TITLE
[Bug] Tag Editors cannot edit Opus (160 kbps)

### ISSUE THREAD

**Issue by Whoareyouagain** [TeamNewPipe/NewPipe#3067]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

NewPipe version: 0.18.2
Phone: Samsung Note 8
Android OS: 9

Hello, I seen there are similar report regarding Opus. However, my reporting is about Opus file is using wrong extension and incorrect kbps. And this cause issues with tag editors that is unable to edit the tag due to incorrect extension. That why I am not sure if I should report it in other issues (#2542, #1372, #2340 & #2904) since my issues with the file is about the tags. 

I discovered that NewPipe downloads the audio file as Opus 160 kbps will use the incorrect format whereas it should be webm. I used various audio players on my PC and my Android phone. They all played the file just fine despite the incorrect file format. Currently my main player is PowerAmp. I stumbled an issue when I am trying to edit the .opus file tag in PowerAmp and it couldn't save the tags. I tried to google the issue and it seem it is not PowerAmp issue which lead me to believe that it is the files I am using. Then I decided to open the file in my Windows 10 with Mp3tag and TagScanner, they are unable to save the tag I edited it in as well. Then I used MediaInfo to check the files to see if there is some disparity. I see the part in General section, it said that the files are _FileExtension_Invalid: webm_ and the bit rate is lower than what NewPipe are downloading. That mean I downloaded over 50 YouTube videos as audio .opus 160 kbps in a wrong format and various bit rates (from 125 kbps to 60 kbps). And add to that, tag editors (Mp3Tag, TagScanner & MusicBrainz Picard) can't edit webm files even PowerAmp can't edit webm tags.

I tried to download the file again but as Opus 70 kbps, MediaInfo reported the file is all clear. The format showing it as ogg (audio is opus) and 67.4 kbps. The tag editors can edit the tag of the file without issue. So, it seems that the bottom last option (Opus 160 kbps) are causing this and using the wrong extension and huge disparity in kbps.

**Comment by Stypox** [comment]
@opusforlife2

**Comment by opusforlife2** [comment]
I just checked both 70 kbps and 160 kbps downloads. Poweramp can edit tags for both of them. So can Kid3.

You might have faced this issue with downloads using earlier versions. Are you sure you've faced it with downloads made _specifically_ from 0.18.2?

**Comment by Whoareyouagain** [comment]
Ahh yes, you must be correct. Most of them was downloaded from a older version of NewPipe that are causing this issue. I thought I already updated it but it didn't, I am having issue with F-Droid are not updating NewPipe. I am not sure why but I managed to get it updated after the third attempt. I am able to edit and save the tags without issues. Thank you for your patience.
