### ISSUE TITLE
Show out of memory error if ran out of memory

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#3068]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When my device runs out of memory, the player crashes and show a toast error "Could not play stream". First I though it might be Wifi issue but took me long time to find out it was caused by out of memory. This error more caused when seeking. 
Sadly my tablet has 512 MB RAM but by rooting and tweaking it, makes it run more smooth and more space in RAM. I have other small tablet with 512 MB RAM that my brother using and it works perfectly without issue. It's more optimized for running low RAM than mine actually. I would have to reboot my device in this case

Maybe make the error message a bit more sense like "Could not play stream because your device ran out of memory" ?

Logcat if you are interested
[could not play stream.txt](https://github.com/TeamNewPipe/NewPipe/files/4175147/could.not.play.stream.txt)

**Comment by opusforlife2** [comment]
User is gone. Is that log helpful?

**Comment by wb9688** [comment]
@opusforlife2: No, someone (you?) using the leaks thing (needs to be enabled in settings) while doing random stuff for some time in NewPipe would help for knowing what could cause it (hint: there are lots of memory leaks). That person should then create an issue in which he copy-pastes all the leak traces as text. There is #3697, which aims to fix a certain category of memory leaks, but it's very WIP.

**Comment by opusforlife2** [comment]
If it is something that can be documented, then 'Memory Leak Testing' should be part of the documentation somewhere, I think.
