### ISSUE TITLE
External Kiosks (Trending pages) for NewPipe

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#3069]
Hei guys,

recently I had a talk with the people from [jedentageinset.de](https://jedentageinset.de) if it was ok to integrate their site into NewPIpe. They come from Nuremberg, the same  city I am from, and the provide a non profit platform where they audit electronic and minimal sets mainly from SoundCloud. I like their platform as I am using it almost daily. 
This is why I would love see it be integrated in NewPipe as a Kiosk for SoundCloud.
I wrote an integration for this site once, but it was rejected because of the justified fear of advertising.
For this reason I think we need to have a discussion about weather we want to provide third party trending pages/kiosks integrated into NewPipe services.
I personally have a more open view on this. For example I would also integrate trending pages like the one from [invidio.us](https://invidio.us) or [hooktube.us](https://hooktube.com/).

What is your opinion on this?

**Comment by theScrabi** [comment]
@TobiGr @TheAssassin what is your opinion?

**Comment by yausername** [comment]
Hi @theScrabi 
Third party trending pages are acceptable if they are community curated like invidio.us or hooktube.us. But promoting specific channels/playlists/feeds goes into the "advertisement" domain which we should stay away from.

Also, the criteria for addition of new services is quite open. So people can add a new service if it qualifies of being one. jedentageinset.de is more a channel than a service.

We can add an option to import rss feeds for feeds that do not have a channel/playlist on one of our supported services.

**Comment by theScrabi** [comment]
@yausername yes you bring up good points. I would not implement an additional support for external RSS, as this could easly be done with an RSS reader and does not belong to one of our tasks. Additionally thinking about jedentageinset.de it would require additional code which would disqualify it for rss. Maybe if I have time then I'll write an additional app for their site then :)

**Comment by mqus** [comment]
I wrote a small forwarding server to provide a podcast feed for all jedentageinset sets, it "scrapes" the site using the wordpress json api and then converts the soundcloud links to actual media urls using youtube-dl. If there is interest, I can upload it to github. 

Personally I then use AntennaPod on Android, which covers my usecase pretty much. There are obviously limitations, such as not having all past tracks or allowing search for them but listening to the recent ones works fine. Some (5~10%?) can't be parsed so you have to open them manually.
