### ISSUE TITLE
autoplay in SoundCloud

### ISSUE THREAD

**Issue by radopas** [TeamNewPipe/NewPipe#3070]
Hello,
I don't see the option Autoplay available when using SoundCloud. It is available when using YouTube.

**Comment by B0pol** [comment]
If I understood, it's because [this line returns null](https://github.com/TeamNewPipe/NewPipeExtractor/blob/9112a106eab9c05ca5c9e574623d4908ecc15656/extractor/src/main/java/org/schabi/newpipe/extractor/services/soundcloud/SoundcloudStreamExtractor.java#L238)

**Comment by TobiGr** [comment]
If this is the case, we should select either the first or a random related video.

**Comment by wb9688** [comment]
Duplicate of #3684, PR open already
