### ISSUE TITLE
Youtube Music link support

### ISSUE THREAD

**Issue by champion174** [TeamNewPipe/NewPipe#3073]
Please include YouTube music in newpipe, just like you've added SoundCloud, Mediacloud and some others.it'll help a lot
I hope your dedication can do this.

**Comment by gkeegan** [comment]
Not sure about the difficulty of making YouTube Music into it's own tab, but YouTube Music videos/audios would be a simple implementation I believe. 

Take this track: https://music.youtube.com/watch?v=9XvXF1LrWgA&list=PLrEnWoR732-DtKgaDdnPkezM_nDidBU9H

If you remove the `music` and the `&list=PLrEnWoR732-DtKgaDdnPkezM_nDidBU9H`, you just get the singular track on YouTube, which could then be downloaded. 

I've wanted to get more involved with the code aspect of NewPipe, so I would like to attempt this via the extractor.

**Comment by gkeegan** [comment]
If you could test the apk in #3074 that would be appreciated. It seems like there was already stuff for YouTube Music in the extractor, so I don't think I'll have much work to do.

**Comment by B0pol** [comment]
Also, playlists generated from YouTube Music are not handled.
https://music.youtube.com/playlist?list=PL4fGSI1pDJn5Je5NXSbA_Y-pSwa16FntZ
It crashes, it should give top 100 tracks in the world.

**Comment by PeterHindes** [comment]
Youtube Music Links Are supported in 18.6 latest release. Just share your albums from the youtube music app.

**Comment by B0pol** [comment]
It should be reopened, it's not supported by the manifest file, then it opens in browser instead of NewPipe. Once this is achieved, we can say NewPipe supports Youcube music links

**Comment by wb9688** [comment]
@B0pol: I already noticed and re-opened ;)

**Comment by wb9688** [comment]
See #3177

**Comment by opusforlife2** [comment]
I think Youtube Music should be a separate entry in the service selector. Since the focus is on audio, it should have a Soundclound-like UI, where only background playback is available. Video playback is a waste of data in this case.

**Comment by B0pol** [comment]
> I think Youtube Music should be a separate entry in the service selector. Since the focus is on audio, it should have a Soundclound-like UI, where only background playback is available. Video playback is a waste of data in this case.

I don't think so. There are videos on music, clips. Why would you want to block videos when you have the possibility to play audio only?

**Comment by wb9688** [comment]
YouTube Music is only another UI for YouTube, and has the same streams and everything, just a different search engine. There is no need for it to be a separate service in NPE.

**Comment by opusforlife2** [comment]
Hmm. Are these videos separate from the ones accessible from the main Youtube site? If not, then the user could access them from there, no?

**Comment by wb9688** [comment]
No, it has the same videos you could also access from YouTube's main site.

**Comment by opusforlife2** [comment]
I suppose if the UI clearly categorises songs separately from videos, anything would be fine.

**Comment by opusforlife2** [comment]
If you were to tap on the thumbnail of an audio, though, what should happen? Should it play audio only, or the video as well? The video is just the thumbnail in all the frames.

**Comment by PeterHindes** [comment]
Youtube musics main feature is the search and likes are filtered to only include songs. It also includes automatic playlists for albums of supported artists.

**Comment by jlpb97** [comment]
The app should prioritize YOUTUBE MUSIC results

**Comment by PeterHindes** [comment]
No it should be an option to use results from each search provider.

**Comment by jlpb97** [comment]
Yes Peter, I think that is a better approach

**Comment by B0pol** [comment]
It's now supported.
