### ISSUE TITLE
Change text of lonpgress menu

### ISSUE THREAD

**Issue by bkqtnte10** [TeamNewPipe/NewPipe#3076]
I often find myself confused what to tap when I want to play a video in the queue.

I now realised that the wording of the long press popup is unintuitive:
Especially "Enqueue in a new popup" is confusing. Is it played in a new popup or later?

Proposed solution is to change wording and what is displayed:
- If nothing is currently playing only show "Play in background" and "Play in popup"
- If something is playing, additionaly show "Enqueue in background" and "Enqueu in popup"

Maybe the icons for the respective functions could also be added: Headphones for background picture-in-picture for popup.

**Comment by OffifialMITX** [comment]
Additionally a "play triangle" on the bottom left corner for starting playback now and a plus on said corner on queue buttons.

IMO the whole menu, including the share function could be replaced with an icon-only (with text on long-press) one.

**Comment by Stypox** [comment]
The plan is #2583

**Comment by opusforlife2** [comment]
Hence close.
