### ISSUE TITLE
Tor/proxy support

### ISSUE THREAD

**Issue by cs-nero** [TeamNewPipe/NewPipe#3077]
Hey,
I would appreciate if NewPipe would add a support for proxys (Type, Host, Port).
I think it is a feature which many users would like, because NewPipe is important for privacy.

Please let me know what you think about that and sorry for my bad english.

**Comment by OffifialMITX** [comment]
As it is right now, you can use Orbot's "VPN" mode to force NP to use Tor. Generally it does not cause issues.

**Comment by Stypox** [comment]
Duplicate of #1129

**Comment by Ryu945** [comment]
> 
> 
> As it is right now, you can use Orbot's "VPN" mode to force NP to use Tor. Generally it does not cause issues.
That has an issue though.   You generally use a regular VPN as the system wide VPN and then connect to Tor through that.   If you use Orbot, you have to turn off your system wide VPN.

**Comment by cs-nero** [comment]
I am not using Orbot, I have a server for that and I wanna use that.

**Comment by Ryu945** [comment]
> 
> 
> I am not using Orbot, I have a server for that and I wanna use that.

That is why I would like New Pipe to have built in Tor connection.  You can't always rely on having that server.
