### ISSUE TITLE
[Bug] Video lags behind audio

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3078]
- [x] I checked if the issue/feature exists in the latest version.

Sometimes while watching a video, the audio goes out of sync (the video lags behind). From that point, any video I watch continues to have this lag. I _think_ this may be caused by frequent skipping of the video backward and forward.

Nothing except a force stop of the app from settings can remedy this when it happens.

**Comment by Stypox** [comment]
This is new to me, never heard of something like this. Can you provide more information about when the problem arises? Is there any way to reproduce consistently?

**Comment by opusforlife2** [comment]
I've bookmarked two videos that I know it happened on for sure, so I can keep testing.

It JUST happened to me again on one of them. This time, it was after unlocking the phone and pressing play. Audio went out of sync. But then I tried it again and it didn't happen. So I can't reproduce it reliably yet.

**Comment by opusforlife2** [comment]
Well, after some more testing it turns out that the common factor in all these videos... was the fact that I used Bluetooth headphones instead of wired ones. (facepalm)

So there is no issue after all.

**Comment by opusforlife2** [comment]
Just leaving this here for future searchers (https://xkcd.com/979/ ;) ). Turning the Bluetooth headphones off, then back on again fixes the lag.
