### ISSUE TITLE
Shortened invidio.us link support

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#3079]
NewPipe supports shortened yt links and invidio.us links, but not shortened invidio links.

Example:
> https://invidio.us/X8avbciUP3c

will lead one to the browser, and only then to NewPipe, whereas
> https://invidio.us/watch?v=X8avbciUP3c

leads to NewPipe directly.

Can this please be implemented=

**Comment by B0pol** [comment]
Do you have the lastest version ? They are supported.

**Comment by OffifialMITX** [comment]
I have the 0.18.2 from F-Droid, but, according to the changelog, that doesn't seem to change in 0.18.3.

**Comment by OffifialMITX** [comment]
"good first issue"? I'm genuinely flattered, thank you :)

**Comment by Stypox** [comment]
It means that the issue is simple to solve and thus can be solved by a newbie

**Comment by OffifialMITX** [comment]
Oh. And here I thought my issue was so unique and impressive >_<

**Comment by B0pol** [comment]
Look at this video
https://vimeo.com/390798674

It's supported. But indeed, it first open browser, whereas the same video above with youtu.be link didn't open browser, but newpipe directly.

By the way, the one working on it should pay attention to other invidious instances: invidiou.sh… They have the same behavior as invidio.us for shortened links (at least invidiou.sh)

**Comment by OffifialMITX** [comment]
@B0pol You're right, that's what I meant, but I might have worded it poorly. The issue is with whatever says the Android system which URLs it can handle.
