### ISSUE TITLE
1080p downloads cannot be opened

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/NewPipe#3081]
As the title suggests, I can't open/play any 1080p downloads from either SD card or internal storage. I'm using a build of the latest dev commits as of this issue.

This was supposedly fixed by #2959, but somehow isn't?

It was working fine with a build from when 0.18.2 was released, but now doesn't work.

**Comment by gkeegan** [comment]
Example video: https://www.youtube.com/watch?v=6Ljs9_yIiY0

**Comment by gkeegan** [comment]
I contemplated just posting this to #2997, but my issues seem slightly different. For me the video won't open at all or play as audio.

**Comment by kapodamy** [comment]
the `stss` box has less keyframes that a file muxed by ffmpeg (newpipe 77 ffmpeg 96). but plays ok.
¿what player app are using? VLC??? MX Player????

**Comment by gkeegan** [comment]
VLC on Android. It's strange that it works fine for you. I'm on Android 9, but perhaps it is device specific?

**Comment by kapodamy** [comment]
@gkeegan sorry i missed a commit on #2959. thats why works on my device
