### ISSUE TITLE
Brightness resets on first gesture brightness change after playback activity open

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#3084]
Thia bug persists since a long time, I didn't come around reporting it.

Stock Android 7.1.1
XT1771

**Comment by Stypox** [comment]
The brightness changes according to the position of the finger in the gesture. So the brightness changes to where your finger is as soon as you begin a brightness gesture. So this is intended, or am I understanding something incorrectly?

**Comment by OffifialMITX** [comment]
But it's always the relative position change, isn't it? I can start in the upper third of the screen and the very first time it'll still reset to minimum brightness, but after that it'll reuse the last set position and relative movement. Note that the volume changes start at the right value regardless of when or where it was last set.

**Comment by Stypox** [comment]
OK, I see

**Comment by JCU0** [comment]
This bug is here again after the unified player update. (current v0.20.10)
Please consider reopening this issue.

**Comment by MrHeating** [comment]
I'm on 0.20.10 as well and can't reproduce.
