### ISSUE TITLE
Request: when choosing to download video/audio, also allow to make it skip relatively (or 100%) silent parts

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [TeamNewPipe/NewPipe#3085]
- [ X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ X] I checked if the issue/feature exists in the latest version.
- [X ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

As the title says.
I've noticed we have this for playing the video/audio, but not for download.
It could be nice if it was possible. Please add settings for both, to set the threshold of what is considered "silent-enough". Maybe while changing, allow to play a test sound to show how silent it is.

**Comment by opusforlife2** [comment]
You mean silent parts shouldn't be downloaded?

**Comment by AndroidDeveloperLB** [comment]
Yes.
But maybe have some settings about this. 
For example: 

1. Start trimming only if it's longer than X seconds (5 by default, perhaps)
2. Trim only on start,end, middle (multi-choice, but start&end checked by default).
3. Trim only if lower than X decibels (and allow to make a sound of this, to demonstrate what the chosen X means) ...

**Comment by wb9688** [comment]
As far as I know this isn't really possible for us to do.

**Comment by AndroidDeveloperLB** [comment]
@wb9688 Why not? It works on playback, so why not when downloading?
It could do it post downloading, too, if needed.

**Comment by wb9688** [comment]
@AndroidDeveloperLB: On playback it works because ExoPlayer supports skipping silent parts. On download we would need to cut those parts of the audio (and perhap video) stream, which is complicated. Anything other than muxing is just out of scope for NewPipe.

**Comment by AndroidDeveloperLB** [comment]
@wb9688 Too bad. Not possible even with ffmpeg  ?

**Comment by opusforlife2** [comment]
Search for ffmpeg in issues. It's been decided it will not be included.

**Comment by AndroidDeveloperLB** [comment]
@opusforlife2 OK sorry :(

**Comment by opusforlife2** [comment]
I don't mind, dude. XD It's a valid question.

**Comment by AndroidDeveloperLB** [comment]
Do you think there is an alternative for this? Maybe using something of Android or exoplayer?
How does exoplayer do it? Maybe you could grab what's important from there ?

**Comment by opusforlife2** [comment]
Personally, I would do something like this using https://github.com/mifi/lossless-cut.

**Comment by AndroidDeveloperLB** [comment]
Can it somehow be added to NewPipe?

**Comment by opusforlife2** [comment]
That giant Electron app? ... No. I can confidently say, without even asking a dev, that it won't be added.

**Comment by AndroidDeveloperLB** [comment]
I mean only the relevant part, of course. No need to import everything...

**Comment by opusforlife2** [comment]
Ah. Well, a dev has said no above. Maybe another dev or a contributor could think of something.

**Comment by AndroidDeveloperLB** [comment]
Why close it then :(

**Comment by opusforlife2** [comment]
@wb9688 Closed as technically infeasible or out of scope?

**Comment by AndroidDeveloperLB** [comment]
But it's not "technically infeasible" because it is possible via other apps.
And it's not " out of scope" because even the player can do it. Plus even if the player didn't have it, it's not nice to download something and then hear a lot of it is silent...

**Comment by opusforlife2** [comment]
It's easy in the player because Exoplayer handles a lot of stuff. But downloading is entirely on Newpipe, and for that I recommend you have a look at the code in one of kapodamy's download related PRs. Dealing with bitstreams and codecs and everything is next level stuff.

You and I aren't qualified to decide what's infeasible or out of scope because we aren't the developers, who know the codebase intimately.

**Comment by AndroidDeveloperLB** [comment]
@opusforlife2 Right, but it's not "technically infeasible". It's more "too much work for this app".

**Comment by opusforlife2** [comment]
Well... that's the definition of infeasible... I didn't say 'technically impossible'.

**Comment by AndroidDeveloperLB** [comment]
@opusforlife2 Oh, sorry. English isn't my main language so I thought it's the same as "impossible".

**Comment by wb9688** [comment]
Yeah, the only thing the downloader in NewPipe will ever do is downloading and (de)muxing. Muxing means putting an encoded audio/video in a container. We currently only have (de)muxing because YouTube serves audio and video separately and when you download a video you of course want to have audio in it as well.

**Comment by AndroidDeveloperLB** [comment]
So this means users have a choice of : audio, video, audio&video ?
