### ISSUE TITLE
Weird back button behaviour 

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#309]
When playing a video in full screen, the back button brings you back at the video details page (closes the full screen video player)
But when navigating back to newpipe from the recent apps list (which brings you back to the full screen video player) the back button brings you back to the previous app (the one that was open when hitting the recent apps button) 

Meaning that, once you leave newpipe from the video player activity, there's no way to get back to the search activity. 

So to see what I mean:
- Open up a video and play it in full screen
- press the home button
- press the recent apps/multitask button and hit newpipe
- try going back to the search activity :)

**Comment by theScrabi** [comment]
Meh that whole player UI is messed up. Would be cool if someone could take advantage of it.

**Comment by JasperWeiss** [comment]
Sidenote, are you still looking into the Tor issue? Currently traffic still isn't transparently routed through the proxy so I'm using WebTube atm (which unfortunately, has weird stuttering in the audio playback)

**Comment by theScrabi** [comment]
JasperWeisss. Yes actually I want tor to work, but at the moment I'm focusing on the core features of NewPipe again, but I'll ask for help.
However have you tried VPN using Orbot? So all the networktrafick will go through tor? So does that work?

**Comment by JasperWeiss** [comment]
Well it works in that all Traffic is routes through Tor transparantly. It's just not necessarily great for anonymity since that includes e.g WhatsApp, Google Play services, etc. So it gives away your identity (not completely though, assuming you're not the only person comming from that exit node.)

**Comment by theScrabi** [comment]
Should be fixed by v0.9.10
