### ISSUE TITLE
reCAPTCHA challenge requested

### ISSUE THREAD

**Issue by stukgrub** [TeamNewPipe/NewPipe#3093]
there is problem when i watch use vpn.
![Screenshot_2020-02-13-19-13-32-37_ee8807d2de22f1831269d80920e33a3b](https://user-images.githubusercontent.com/31304277/74434801-13d5f180-4e5b-11ea-9a98-ecb3a02ba24a.png)

**Comment by Stypox** [comment]
Wait for 0.18.4, the problem will be  solved. In the meantime use the apk in #3035
