### ISSUE TITLE
Store unplayed items in queue

### ISSUE THREAD

**Issue by barudaret** [TeamNewPipe/NewPipe#3097]
If I had a nickel for every time I had a long queue lined up and accidentally pressed the back button while in the fullscreen player, thus losing the whole queue...

And just now, I had a long queue in the popup player, and pressed the fullscreen button, only the fullscreen player never appeared, it just ate my queue.

Oh and sometimes, my connection's not that great, so NewPipe just decides "can't play this stream" so that video gets deleted out of my queue, not to be found in my history or anything.  Even better when NewPipe discards like 10 videos before I realize anything's up.

Other scenarios include crashes and the like.  It would prevent a lot of grief if NewPipe would save the queue and offer to restore it on boot or somewhere in the UI

**Comment by Stypox** [comment]
I have already seen a feature request about storing the queue, though I can't find it anymore ;-)

**Comment by gillhash** [comment]
+1 for this
