### ISSUE TITLE
Gesture controls don't disable on downloaded videos

### ISSUE THREAD

**Issue by nabakolu** [TeamNewPipe/NewPipe#3104]
Disabling gesture controls in settings does not disable them, when viewing downloaded videos.

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by gkeegan** [comment]
When you view downloaded videos, they open in another app (such as VLC). NewPipe can't control the settings of an external app.
