### ISSUE TITLE
Create local playlists and repeat videos

### ISSUE THREAD

**Issue by wesen1** [TeamNewPipe/NewPipe#311]
With a google account you can create playlists and add videos to those lists. I would like to have this feature in NewPipe without the need of a google account. Instead, the playlists should be saved locally on the smartphone.
Another feature which I think would be useful is repeating videos.

**Comment by timofonic** [comment]
I agree. 

I have tons of them on YouTube. It would be nice to be able to import them.

**Comment by satiricon** [comment]
To have this feature would be awesome. We could use a sqlite DB to store a list of YT keys and then show them somehow in some activity.

**Comment by aksiksi** [comment]
I'm interested in working on this. I don't have much time currently, but I'll see how much I can get done.

What I'm currently thinking:

1. Playlist list activity: show current playlists, create new, delete
2. Playlist activity: show videos in current playlist, add new, remove videos
3. Add a "add to playlist" button on video page, perhaps under the video
4. Create a Playlist model class that represents a single playlist, data stored in local SQLite DB as (id, playlist_name, video_url). SELECT * FROM playlists WHERE id = id when retrieving the videos in a playlist.

**Comment by satiricon** [comment]
@aksiksi That would be awesome. I would also add an "Add to Playlist" button in the search results list as well.

**Comment by exomar** [comment]
Would be awesome to have this feature.

**Comment by theScrabi** [comment]
Is in work right now

**Comment by theScrabi** [comment]
Is coming with next release.
