### ISSUE TITLE
[Feature request] Copy URL from info page 

### ISSUE THREAD

**Issue by lepieru** [TeamNewPipe/NewPipe#3110]
The info page, in the top right menu, do not offer the feature to copy the URL.

I often open a video in the Web browser and then copying the URL from it when the "Share" button does not fit to my need, but it's kind of boring.

**Comment by Stypox** [comment]
This is an issue with many apps, just install "Share to Clipboard":
https://f-droid.org/app/com.tengu.sharetoclipboard

**Comment by lepieru** [comment]
@Stypox Thanks for the tip! :D
