### ISSUE TITLE
Can't play and make phone reboot

### ISSUE THREAD

**Issue by cxp1991** [TeamNewPipe/NewPipe#312]
Information: 
Galaxy S3, android 4.4.4, CyanogenMod Rom

Log: 
06-10 14:22:16.090 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:16.090 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e15cdd8)
06-10 14:22:17.530 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:17.530 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e0f5720)
06-10 14:22:18.995 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:18.995 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5daaa3c0)
06-10 14:22:22.010 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:22.010 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e0c1350)
06-10 14:22:22.090 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:22.090 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e149670)
06-10 14:22:22.105 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.105 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.105 7863-7863/org.schabi.newpipe D/OpenGLRenderer: GL error from OpenGLRenderer: 0x501
06-10 14:22:22.105 7863-7863/org.schabi.newpipe E/OpenGLRenderer:   GL_INVALID_VALUE
06-10 14:22:22.120 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.120 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.125 7863-7863/org.schabi.newpipe D/OpenGLRenderer: GL error from OpenGLRenderer: 0x501
06-10 14:22:22.125 7863-7863/org.schabi.newpipe E/OpenGLRenderer:   GL_INVALID_VALUE
06-10 14:22:22.140 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.140 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.140 7863-7863/org.schabi.newpipe D/OpenGLRenderer: GL error from OpenGLRenderer: 0x501
06-10 14:22:22.140 7863-7863/org.schabi.newpipe E/OpenGLRenderer:   GL_INVALID_VALUE
06-10 14:22:22.155 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.155 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.155 7863-7863/org.schabi.newpipe D/OpenGLRenderer: GL error from OpenGLRenderer: 0x501
06-10 14:22:22.155 7863-7863/org.schabi.newpipe E/OpenGLRenderer:   GL_INVALID_VALUE
06-10 14:22:22.170 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.170 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.170 7863-7863/org.schabi.newpipe D/OpenGLRenderer: GL error from OpenGLRenderer: 0x501
06-10 14:22:22.170 7863-7863/org.schabi.newpipe E/OpenGLRenderer:   GL_INVALID_VALUE
06-10 14:22:22.190 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.190 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface_):1610: failed to dequeue buffer from native window (0x5f5dbca0); err = -16, buf = 0x0,max_allowed_dequeued_buffers 3
06-10 14:22:22.195 7863-7863/org.schabi.newpipe D/OpenGLRenderer: GL error from OpenGLRenderer: 0x501
06-10 14:22:22.195 7863-7863/org.schabi.newpipe E/OpenGLRenderer:   GL_INVALID_VALUE
06-10 14:22:24.785 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:24.785 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e106458)
06-10 14:22:24.900 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:24.900 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e0f2990)
06-10 14:22:24.910 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:24.910 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e0e2128)
06-10 14:22:24.965 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:24.965 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e005238)
06-10 14:22:25.000 7863-7863/org.schabi.newpipe E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-10 14:22:25.000 7863-7863/org.schabi.newpipe E/[EGL-ERROR]: void __egl_platform_queue_buffer(mali_base_ctx_handle, egl_buffer_):1301: unable to queue buffer (0x5e005610)
06-10 14:22:34.820 7863-7868/org.schabi.newpipe I/dalvikvm: threadid=3: reacting to signal 3
06-10 14:22:34.895 7863-7868/org.schabi.newpipe I/dalvikvm: Wrote stack traces to '/data/anr/traces.txt'
06-10 14:22:39.345 7863-7863/org.schabi.newpipe A/libc: Fatal signal 6 (SIGABRT) at 0x00007be0 (code=0), thread 7863 (.schabi.newpipe)

**Comment by theScrabi** [comment]
Please try an external player.

**Comment by 912d** [comment]
If your S3 is rebooting while using NewPipe, enable 

> Allow purging of assets
in the Settings->Performance->Memory management

In my case it helped me to get rid of S3 rebooting.

**Comment by theScrabi** [comment]
I wonder if I still have large memory usage enabled ...
