### ISSUE TITLE
Single comments (that exist on Youtube) not shown in NewPipe

### ISSUE THREAD

**Issue by soshial** [TeamNewPipe/NewPipe#3126]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## BUG: "no comments" seen in NewPipe
(while THERE ARE COMMENTS on YouTube)

### 1. On Youtube:

![Screenshot_20200221-074508](https://user-images.githubusercontent.com/100644/75023348-56717c80-54a0-11ea-8c79-7be7569e576e.png)

### 2. On NewPipe:

![Screenshot_20200221-074531](https://user-images.githubusercontent.com/100644/75023359-5bcec700-54a0-11ea-8be8-9f05fca18a18.png)

### 3. In browser (it is hidden, which is probably the reason of the bug):
<img width="1249" alt="Screenshot 2020-02-21 at 11 41 28" src="https://user-images.githubusercontent.com/100644/75023547-a94b3400-54a0-11ea-8ab2-2953af0d9b78.png">

The bug was reproduced with this video : https://www.youtube.com/watch?v=t_gl0Dvmxlc
Thank you so much!

**Comment by B0pol** [comment]
On www.youtube.com you can't see it unless you sort by new. And on m.youtube.com you can't sort by new.
I don't think something can be done, it's a youtube bug.

**Comment by soshial** [comment]
I see. Maybe it is possible to pass some GET parameter to sort them "by new"? I thought that NewPipe uses some Youtube API, but turns out, it parses Youtube webpage for info, right?

**Comment by B0pol** [comment]
See #3115. Basically, for Youtube comments we use mobile website. There are no options shown on youtube website to sort by new, so maybe it's hidden and we should find it, maybe it's not available and would need more work to switch to desktop website.

**Comment by soshial** [comment]
Looks like currently all comments are shown on mobile Youtube: https://m.youtube.com/watch?v=t_gl0Dvmxlc

Anyone can confirm it?

**Comment by B0pol** [comment]
Can confirm. By the way, you can see the comment in NewPipe now.

**Comment by opusforlife2** [comment]
@B0pol What's the status now?

**Comment by B0pol** [comment]
I can't reproduce this issueb

**Comment by opusforlife2** [comment]
Can you link a single comment video?

**Comment by RaveZero** [comment]
> Can you link a single comment video?

Basically any video on YouTube, here is an example:
https://www.youtube.com/watch?v=RvhxAgHj5VU

**Comment by soshial** [comment]
@Stypox, I tested it on v0.20.6 and it seems Youtube started to show single comments. So I guess this has fixed on its sown.
