### ISSUE TITLE
[Bug] Seek duration of 5 seconds makes audio rewind impossible

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3127]
- [x] I checked if the issue/feature exists in the latest version.

- Set the seek duration to 5 seconds.
- Play an audio till 30 seconds or so.
- Try rewinding.

It will do so once until the timestamp is a multiple of 10 seconds. Then tapping rewind just keeps taking you to that timestamp, not allowing you to go further back.

If you rapidly jam the rewind button, though, you overcome this 'barrier' of sorts and get taken quite far back.

This issue exists only for the 5 second duration.

**Comment by Stypox** [comment]
@XiangRongLin could you look into this? ;-)

**Comment by XiangRongLin** [comment]
@Stypox Will do

**Comment by XiangRongLin** [comment]
@opusforlife2 Could it be that you have "Use fast inexact seek" on?

**Comment by opusforlife2** [comment]
@XiangRongLin Yep.

**Comment by XiangRongLin** [comment]
If i understood it correctly, this is just the way exo player works when using inexact seek.
According to this article (https://medium.com/@takusemba/deep-understanding-of-seek-4e10079165ec), it just seeks to the closes sync point with the current config [here](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java#L206), which appears to be every 10 seconds. So if you want to rewind 5 seconds the closest sync point is the current one. You can also notice it when seeking forward. Although the setting is 5 second, the next closes point is 10 seconds away.

If you use 15 or 25 seconds you will also notice that the left over 5 seconds gets ignored.

**Comment by opusforlife2** [comment]
I was guessing it would be something like that.
It does indeed ignore anything modulo 10. Good find.

Why is it that it only happens with audio, though? This works perfectly well for videos.

**Comment by XiangRongLin** [comment]
My guess would be that the sync points are different. Like the article mentioned those sync points depend on your media type and streaming protocol

**Comment by opusforlife2** [comment]
Strange. The article mentioned streaming protocol and container format. They should both be the same for audios as well as videos + audios.

**Comment by opusforlife2** [comment]
@XiangRongLin I've seen comments (regarding resolutions) that certain list options can be hidden if a preference is toggled. Can the same be done with inexact seek? If it is on, the options 5, 15 and 25 should be hidden.

**Comment by XiangRongLin** [comment]
This idea should work.
The inexact seek description would need to be extended to include this Information.

What should then happen if the setting is at 5/15/25 and the user activates inexact seek? Automatically set it back to 10?

**Comment by opusforlife2** [comment]
Yes. And inexact seek description should say that it only allows 10, 20 and 30 second options. No need to explain _why_ that is, though.

**Comment by XiangRongLin** [comment]
@opusforlife2 PR is open
