### ISSUE TITLE
Make drawer accessible from every activity

### ISSUE THREAD

**Issue by surrodox2001** [TeamNewPipe/NewPipe#3135]
Probably related to #3128, could you add other options like downloads to (now-gone) app bar?
IMO this can make navigation bit faster.

Or a potentially better way, adding an option to the settings to return UI back to pre-0.18.3 design?

**Comment by Stypox** [comment]
@TobiGr apparently it was a bad idea to remove menus from everywhere, they should probably be reintroduced. The only place that should stay without menus is the main page, where the drawer is openable.

**Comment by gillhash** [comment]
> Apparently it was a bad idea to remove menus from everywhere, they should probably be reintroduced. The only place that should stay without menus is the main page, where the drawer is openable.

Yes, agree with you @Stypox we should  revert changes ,  as most users are accustomed to it.

**Comment by opusforlife2** [comment]
I still maintain that having the drawer instead of the 3 dot menu everywhere except a few screens is the better way to go. It gives the user immediate access to a wider variety of menus and options.

Why should the user have to back out all the way to the home screen if they feel like having a glance at their Bookmarked Playlists, for example?

**Comment by Stypox** [comment]
Adding the drawer would force us to remove the back button though

**Comment by wb9688** [comment]
@Stypox: No, look at how you could still access the drawer by swiping at for example the 'My apps & games' screen in the Play Store

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/3114#issuecomment-589933918 Mwahahaha

**Comment by Stypox** [comment]
@opusforlife2 my bad, I missed that comment ;-)

**Comment by Hashik-Donthineni** [comment]
Hey everyone, I made a PR addressing this can you please take a look :)

**Comment by surrodox2001** [comment]
Closing this issue as this doesn't apply to 0.20.x versions (the entire top bar is gone). I'll look after this again if the old UI resurfaces or the devs decided to reimplement the top bar again.
