### ISSUE TITLE
Incorrect profile pictures

### ISSUE THREAD

**Issue by helght** [TeamNewPipe/NewPipe#3144]
Channels without avatar have a seemingly random avatar image on video pages.

To reproduce, find a channel without avatar and open their video.

(easy way: go to some popular video that has comments, click on a profile without photo and see if they have videos uploaded)

- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ +] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by helght** [comment]
Correction - ALL channels seem to have wrong profile images, not just those without them.

**Comment by wb9688** [comment]
What version are you using? v0.18.5?

**Comment by helght** [comment]
I'm on 18.5

If you don't see this bug I can post screenshot

**Comment by wb9688** [comment]
Could you link an example channel?

**Comment by helght** [comment]
Ok, a random channel that shows this bug

https://youtube.com/channel/UCXKbVIhNjWkSZolb7tjdfOg

**Comment by helght** [comment]
Here is what it looks in newpipe
![Screenshot_20200226-192208_NewPipe](https://user-images.githubusercontent.com/57073591/75364909-7dc7af80-58cd-11ea-8271-7bd8d255bdf3.jpg)

**Comment by helght** [comment]
Try what I said - choose random vid, check comments, click on someone, then click on their video

**Comment by wb9688** [comment]
I found the issue: it was getting the avatar of the uploader of the recommended video to watch next.
