### ISSUE TITLE
Crash when downloading videos to extSdCard

### ISSUE THREAD

**Issue by waqas** [TeamNewPipe/NewPipe#315]
0.8.0: I guess this is something to do with GigaGet integration, because GigaGet also crashes on extSdCard. I am using a Samsung phone with 5.1.1.

It was working fine on 0.7.8.

**Comment by waqas** [comment]
also, just curious, why not give an option to share/copy download URL so it can work with any download manager, e.g. ADM Pro?

**Comment by nado** [comment]
I also dont know where are the downloaded files with 0.8.0, they dont appear in my directory configured in the settings, but i can play them while starting them *from* NewPipe (Menu "Downloads").
These downloaded musics dont show up in my music application.
Downgrading to 0.7.* for now.

**Comment by satiricon** [comment]
@waqas The option to download with an external DM is in my todo list. I'll get to it probably next week.

**Comment by satiricon** [comment]
I can replicate this error only when downloading to a sdcard. This is the exception:

```
06-16 12:10:39.868 25279-27160/org.schabi.newpipe E/AndroidRuntime: FATAL EXCEPTION: Thread-2198
java.lang.RuntimeException: java.io.IOException: open failed: EROFS (Read-only file system) at us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:212)
     Caused by: java.io.IOException: open failed: EROFS (Read-only file system)
       at java.io.File.createNewFile(File.java:948)
       at us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:204)
     Caused by: libcore.io.ErrnoException: open failed: EROFS (Read-only file system)
       at libcore.io.Posix.open(Native Method)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
       at java.io.File.createNewFile(File.java:941)
       at us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:204) 
```

**Comment by satiricon** [comment]
@waqas Can you give me a little information about your setup? Where is the SDcard mounted? I thought the sdcard was auto mounted to `/storage/sdcard1` and NewPipe throwed the exception when I configured it to use that directory. But the card was actually being mounted to `/Removable/MicroSD` in my asus tf700. When I changed the setting and pointed to that directory it worked and downloaded to the sdcard flawlessly.

**Comment by waqas** [comment]
On my phone (Samsung Galaxy J5, unrooted) the SD Card is mounted at /storage/extSdCard.

**Comment by PacoBell** [comment]
For Android 6.0+, this needs to be addressed:

https://source.android.com/devices/storage/#runtime_permissions

**Comment by plusterkopp** [comment]
Samsung user here (S5Neo, Android 6). Did anybody get this to work yet? 0.7.8 was OK, but I keep getting ULR errors lately and can not use any recent version due to this annoying bug.

**Comment by arayan22** [comment]
This also happens to me.  Samsung T280 tablet.

**Comment by mglinux** [comment]
Same problem here. Running lineage Android 7. Path: /storage/sdcard/

_Gesendet von meinem Samsung SM-G900F mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
