### ISSUE TITLE
Video is not downloaded

### ISSUE THREAD

**Issue by Henry2o1o** [TeamNewPipe/NewPipe#3150]
current 0.18.5

already since the last versions
If I change / shorten the video name, it works better.

**Comment by wb9688** [comment]
What smartphone are you using? What Android version are you using? Are you using SAF in NewPipe? To what folder are you downloading? Do you know whether older versions of NewPipe worked? Is it possible to create a file with exactly the same 'long' name in another app? Does it happen with all videos? If not, could you link a video where it happens and a video where it doesn't happen?

**Comment by Stypox** [comment]
Closing for lack of information
