### ISSUE TITLE
Download-button causes "send and view SMS" permission request - is this intended?

### ISSUE THREAD

**Issue by ronidee** [TeamNewPipe/NewPipe#3151]
When I press the download button below a video NewPipe requests to send and view SMS messages and doesn't show the download-dialog if I deny.
Is this intended and if so, why does NewPipe requires SMS access?
I apologize if this is the wrong place to ask, but I couldn't find anyting related to that and only observed this behavior as of this version.
Version: 0.18.5
OS: LineageOS-17.1 (UNOFFICIAL)
Device: Redmi Note 7
Dev/App lang.: English

Sincerely,
ronidee

**Comment by wb9688** [comment]
Where did you download NewPipe from? We never ask for SMS permission, see https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/AndroidManifest.xml for the permissions we have.

**Comment by ronidee** [comment]
Turns out it's a mistake by the ROM I'm using. The permission names/descriptions are messed up, apparently.
I wrote a little test-app which only asks for `Manifest.permission.WRITE_EXTERNAL_STORAGE` and it says "SMS" in the dialog too.

Sorry that I bothered you guys, but you can imagine how confused I was. Thank you very much for your quick response.
