### ISSUE TITLE
Search returns "No results" while results exist

### ISSUE THREAD

**Issue by bovergaauw** [TeamNewPipe/NewPipe#3153]
When doing a search for "all saints", v0.18.5 returns "No results", but when selecting almost anything other than just "all saints" from the suggestions list appearing while typing "all saints", a proper list of results show up.

**Comment by wb9688** [comment]
Could confirm. I'll look into it tomorrow.

**Comment by opusforlife2** [comment]
What happens if you perform the same search again? If I get 'no results', I tap on the search bar and tap search again. This usually does bring up results.

**Comment by wb9688** [comment]
This is caused by those search queries having a `promotedSparklesTextSearchRenderer` at the top (i.e. that advertisement for "AllSaints.eu - AllSaints Official Online Shop - AllSaints New Season"), in a separate object in the `contents` array.
