### ISSUE TITLE
Crash report email bounce (see #3040) 

### ISSUE THREAD

**Issue by jhoc2000** [TeamNewPipe/NewPipe#3158]
The original issue #3040 has been closed and I have tried to indicate that it is still relevant. Please read 
#3040 and reopen the issue.

I have downloaded the latest version of NewPipe from F-Droid. 0.18.3 is the latest version there. 

- [ y] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [y] I checked if the issue/feature exists in the latest version available on F-Droid. 
- [n ] I did use the [incredible bugreport to markdown converter] I tried to use but I can't use because of this issue. (https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by TheAssassin** [comment]
Please do not open duplicates just to "raise awareness" for another comment.
