### ISSUE TITLE
Enable comments and enable "similar videos and next" arent in the same setting category

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#3166]
Small thing. I wanted to check if by removing comments/videos suggestions  the info page's loading would have been speeded up, and i realized that "comments" setting is in Content, and "Videos suggestion" was in Appearance: that's quite disturbing since these functionnalities are visible at the same place - under the video/details, but separated in settings, thus it could lose more than one user searching for them :)

**Comment by opusforlife2** [comment]
I could try this.
