### ISSUE TITLE
User interface - menu layout suggestions

### ISSUE THREAD

**Issue by kekukui** [TeamNewPipe/NewPipe#3167]
## 1.  NewPipe displays the last-used service sub-menu at launch.

![image](https://user-images.githubusercontent.com/20834957/75629346-3da74c00-5baf-11ea-8c55-f410db73509c.png)

This is confusing and counter-intuitive because the name of the service does not appear on screen.

**_The existing layout does not make it obvious that NewPipe supports multiple sites & services -- and it is not mentioned on the NewPipe web site (or the app listing in F-Droid)._**

Recommendation: include the service name & logo / favicon

![image](https://user-images.githubusercontent.com/20834957/75629369-970f7b00-5baf-11ea-9ba0-52a13a6a94a8.png)

## 2. This gadget toggles between the entire service list & and the options menu for a single service.  (Very confusing & counter-intuitive, since no other app works this way.)

![image](https://user-images.githubusercontent.com/20834957/75629501-9d522700-5bb0-11ea-9f70-188a074c635d.png)

Recommendation: 

Display services menu at launch with heirarchical sub-menus.

![image](https://user-images.githubusercontent.com/20834957/75629549-f621bf80-5bb0-11ea-850b-0407452b83a9.png)

Alternative menu layout concept.

![image](https://user-images.githubusercontent.com/20834957/75629724-506f5000-5bb2-11ea-85c1-1eff0e8af1a8.png)

**Comment by jniniinoinoino** [comment]
;)

**Comment by opusforlife2** [comment]
@Stypox take a look.

**Comment by Stypox** [comment]
Closing in favour of #650 (I posted your suggestions there)
