### ISSUE TITLE
Seek duration not shown in languages other than english

### ISSUE THREAD

**Issue by s3tnex** [TeamNewPipe/NewPipe#3169]
Hello. I apologize in advance if I am not writing there. in Russian localization, for some reason, the text stopped showing, although in the main language (English), it is shown. why it happens?
![Screenshot_2020-03-02-01-51-32-053_org schabi newpipe](https://user-images.githubusercontent.com/61666708/75634124-a41e7f80-5c2c-11ea-99c1-1347fc2fc010.png)
![Screenshot_2020-03-02-01-51-37-095_org schabi newpipe](https://user-images.githubusercontent.com/61666708/75634136-b698b900-5c2c-11ea-93fa-bdf4aa27e865.png)
#2738 #2740

**Comment by s3tnex** [comment]
#2738 #2740

**Comment by TobiGr** [comment]
Which version are you using? How is the setting called in English?

**Comment by B0pol** [comment]
It also happens with french. It's seek duration setting

**Comment by s3tnex** [comment]
> Which version are you using? How is the setting called in English?

0.18.6
Video & audio --> Fast-forward/-rewind seek duration.

**Comment by uli-on** [comment]
Same here for the German localisation, independent from light or dark UI. 

Android 6.0.1, Moto G4
NewPipe v0.18.6

**Comment by uli-on** [comment]
... and also in French, just tried. So maybe the title might be changed in order to collect more results?
