### ISSUE TITLE
Dim select regions of the UI of the video when touching the screen while playing

### ISSUE THREAD

**Issue by treble2019** [TeamNewPipe/NewPipe#3172]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Play video.
Touch screen; the whole screen dims (or something like darkens - not sure exact word).
Better would be dim the 'seek bar area' and the top area.

Why:
Leaving the rest of the screen clean would *allow* the user to see the video while 'mucking' about.

Example:
See VLC:
![2](https://user-images.githubusercontent.com/52563208/75684765-b5ea3c00-5c99-11ea-91ad-ebebd83a85c1.png)

**Comment by opusforlife2** [comment]
@Stypox Yes or no?

**Comment by Stypox** [comment]
#1073 is a better solution which does not imply using a non-modern-looking UI like VLC
