### ISSUE TITLE
Video Dates

### ISSUE THREAD

**Issue by Siorrr** [TeamNewPipe/NewPipe#3175]
When you change the list view mode to grid from list you can't see when the video was uploaded (If it's a new or old video) unless you go to the description box. Which can be annoying at times. And also why can't I change the font to make it bigger because I have vision problems and the words are a little small. Can new videos that are uploaded be easier to find besides the "what's new" feature?
[Capture+_2020-03-02-11-51-21](https://user-images.githubusercontent.com/61703469/75698166-3c902080-5c7c-11ea-9617-374470a6058e.png)
![Capture+_2020-03-02-11-51-40](https://user-images.githubusercontent.com/61703469/75698177-41ed6b00-5c7c-11ea-882c-503b2101db59.png)
![Capture+_2020-03-02-11-51-54](https://user-images.githubusercontent.com/61703469/75698193-46198880-5c7c-11ea-9d68-441511d29e57.png)

**Comment by Siorrr** [comment]
![Capture+_2020-03-02-11-51-21](https://user-images.githubusercontent.com/61703469/75698930-904f3980-5c7d-11ea-8dcd-92d8327004fb.png)

**Comment by Stypox** [comment]
This is known and was reported before, not sure where though. Thank you for the detailed report!
