### ISSUE TITLE
Comments dissapear.

### ISSUE THREAD

**Issue by Kristofp** [TeamNewPipe/NewPipe#3179]
Every time I visit a video that's not part of my subscription from within the app via the suggested videos in the next section of videos, my comments everywhere dissapear and I need to reset and reimport my subscription to get my comments back.

**Comment by Stypox** [comment]
I am not sure what you mean? You can disable comments via settings, have you checked they are enables?

**Comment by Stypox** [comment]
Closing due to lack of information
