### ISSUE TITLE
webm audio stored in /Movies

### ISSUE THREAD

**Issue by XeR** [TeamNewPipe/NewPipe#318]
Hello,
When downloading audio in webm format in version 0.8.0, the file is stored in /Movies instead of /Music.
The icon shown is the icon of a video in the download manager.
The fils is playable in a music player and its weight (~3Mb) hints that it is indeed an audio-only file.
m4a audio format is stored in /Music in version 0.8.0.
This problem does not exist in version 0.7.8

**Comment by theScrabi** [comment]
Have you tried to change the music path in the settings?

**Comment by XeR** [comment]
It does not seem to work.
Problem may come from [NewPipe/app/src/main/java/us/shandian/giga/util/Utility.java, line 150](https://github.com/theScrabi/NewPipe/blob/aee26fcffca50e8a4bf590f1a973d6c38e0273cd/app/src/main/java/us/shandian/giga/util/Utility.java#L150): files are classified according to their extension, and not their MIME type.
The "webm" extension is ambiguate as the file can be a video or an audio file

**Comment by Paviluf** [comment]
I have this problem too.

**Comment by theScrabi** [comment]
[fixed](https://github.com/TeamNewPipe/NewPipe/commit/f9ac199c1fb9386ab4b79f86ee202d75a9a9d6a0)
