### ISSUE TITLE
Issues noted when running on Sony Bravia TV

### ISSUE THREAD

**Issue by undercoverbeatles** [TeamNewPipe/NewPipe#3180]
Couple of issues noted when running on Sony Bravia TV

1. The newpipe Internal player shows a portrait view on a landscape screen size on all video playback. Can this be fixed?  
2. No icon is created by this app (so cannot add to app to TV homescreen by default). Having to use external launch app to start program.

Thanks :)

**Comment by Stypox** [comment]
Issue 1 I think can be solved by tapping on the rotation button in the main player UI (not sure though, I don't have a smart tv)

**Comment by opusforlife2** [comment]
Test this apk and reply if your issues still persist: https://github.com/TeamNewPipe/NewPipe/files/5022321/app-debug.zip
