### ISSUE TITLE
Livestreams on external players

### ISSUE THREAD

**Issue by vapormusic** [TeamNewPipe/NewPipe#3182]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I have problems playing livestreams on external players (i.e MX Player). It can only play the first 5 seconds then it stops completely.

**Comment by Stypox** [comment]
Probably MX Player is not able to handle HLS urls. Have you tried with VLC?

**Comment by tva2000hn** [comment]
Yes, I tried MX Player, VLC and Kodi but the problem persists.

**Comment by opusforlife2** [comment]
So not a Newpipe issue?
