### ISSUE TITLE
UI remove search icon when in search mode

### ISSUE THREAD

**Issue by treble2019** [TeamNewPipe/NewPipe#3183]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

If you look at  the email app, after tapping search, it loads the 'search field'.

![22](https://user-images.githubusercontent.com/52563208/75883081-b4984b00-5e22-11ea-9599-4d80b8e09696.jpeg)

**Comment by jonas-skywalker** [comment]
Hey, i would really like to try this. I looked around in the code a little bit to get familiar. Could someone please point me into a direction where this could be done?

**Comment by PeterHindes** [comment]
nice first pull request :)

**Comment by PeterHindes** [comment]
if anyone else is interested in doing more work, the search should be scoped to the fragment, so for example if you are in the history screen, the search button should search through your history.
