### ISSUE TITLE
[Feature Request] Propose an "audio playlist of the day" in menu bar

### ISSUE THREAD

**Issue by SoftCyD** [TeamNewPipe/NewPipe#3186]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I usually listen to audio playlists in my car via bluetooth, but I always listen to the same ones, the ones I put in my bookmarks.
In order to discover albums by known or unknown artists, the team could suggest playlists to discover (rap, pop, rock, classic, etc ...).

Thank you for reading me.

**Comment by Domiuns** [comment]
Try spotify, discover selection

**Comment by Stypox** [comment]
I don't think this is doable, we would need music experts

**Comment by gkeegan** [comment]
I agree with @Stypox on this. This would require a lot of work to consistently make these, and everyone has different tastes in music (or even different languages spoken).
