### ISSUE TITLE
Option to download using Android's manager

### ISSUE THREAD

**Issue by XeR** [TeamNewPipe/NewPipe#319]
Hello,
The previous download manager was in perfect harmony with Android's default manager.
It is also used by other applications such as Firefox.
I think that it's more convenient to keep track of all my downloads at the same place.
On first sight, it does not seem to be possible to use GigaGet and keep track of the download in Android's manager.
Can you add an option to use it instead of the new one based on GigaGet introduced in 0.8.0?

**Comment by theScrabi** [comment]
I could make you chose either the newpipe build in GigaGet, or the android build in download manager.

**Comment by satiricon** [comment]
@theScrabi Want me to fix this download stuff?

**Comment by theScrabi** [comment]
Would be cool :)
