### ISSUE TITLE
hide videos from gallery

### ISSUE THREAD

**Issue by huckvrni** [TeamNewPipe/NewPipe#3191]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Because I'm moving alot from places with great and no reception I'm downloading videos alot to watch them later.
The feature request is to add a setting to make these videos not show in my gallery.
This can be done manually by adding a '.nomedia' file to my download folder but should be available in the app settings for ease of use.
Also, it would help when switching default download directories.

Thanks in advance!.

**Comment by baraa272** [comment]
No offense though m8 , just create the .nomedia file yourself it's not really that hard

**Comment by opusforlife2** [comment]
@Stypox Yes or no?

**Comment by Stypox** [comment]
> just create the .nomedia file yourself it's not really that hard

Yes, do this. This is a too-niche feature to ever be implemented.
