### ISSUE TITLE
UI automatically retracts when Notification dropdown is active

### ISSUE THREAD

**Issue by anoadragon453** [TeamNewPipe/NewPipe#320]
The player is set to automatically reset when no input is received after a short amount of time, which is admittedly a nice feature. However, it would improve usability if this feature were disabled while the notification drop down is active and on screen, as checking notifications or network settings while a video is open is not possible, due to the UI retracting after mere moments of leaving Newpipe's UI.

Using NewPipe version: 0.8.0

Steps to reproduce:
- Watch video
- Pull down from top to reveal top bar and/navigation buttons.
- Pull down again to access notification drop down
- Feabily attempt to do something before UI is forced back to the video

Thanks!

**Comment by theScrabi** [comment]
I know about this issue, and I hate it.

Once more: The UI of NewPipes internal player is crap and needs to be rewritten. I couldn't do it so my question is still who wants to write a proper UI for NewPipes video player?

**Comment by anoadragon453** [comment]
At least on my Android P device, this doesn't seem to be a problem anymore. Can anyone confirm?

**Comment by Stypox** [comment]
This issue does not seem to occour anymore
