### ISSUE TITLE
[Feature Request] Limit search to autogenerated music videos

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3202]
- [x] I checked if the issue/feature exists in the latest version.

You can, by including the word "topic" and through some trial and error, find music videos auto-generated by Youtube which are licensed from music companies. Could there be a checkbox or toggle so that the user could specifically search for such videos?

**Comment by wb9688** [comment]
A better option would be to just do a search on music.youtube.com then

**Comment by opusforlife2** [comment]
Is that something that could be done from within Newpipe?

I know that you can paste links into the search field and Newpipe will directly load the video fragment, but for that I would have to search in the browser and then copy the relevant link.

**Comment by PeterHindes** [comment]
YoutubeMusic support is being worked on. You can currently share the playlist into newpipe from the youtube music app. keep in mind that youtube music will fill albums with the music videos if they exist instead of the album track.

**Comment by opusforlife2** [comment]
That last part is a bit unclear. Will it fill albums with music videos if _they_ exist or will it fill them with music videos if the corresponding _audios_ don't exist?

**Comment by PeterHindes** [comment]
It prefers videos, and will slowly replace your audios with videos.

**Comment by opusforlife2** [comment]
Okay, now I'm a bit more confused. What do you mean by "your audios"? For some context, I have never installed Youtube Music. I'm only concerned with what I can access from Newpipe.

**Comment by PeterHindes** [comment]
Videos that have only audio. They just use the muic video instead. That's
how it shows up in NewPipe aswell

**Comment by opusforlife2** [comment]
Ah. That's fine as long as you can search for an audio and get the correct result in Newpipe.

**Comment by PeterHindes** [comment]
One could implement a search for youtube music in the app, but currently
search is done through the main site. It would likely need new extractor
code to work.

**Comment by opusforlife2** [comment]
How should this be presented to the user?

The most straightforward way seems to be to add Music/Audios to the search filter menu with the other radio buttons, but that doesn't clarify that the user is accessing Youtube Music.

**Comment by wb9688** [comment]
@opusforlife2: That's exactly what will happen. There isn't really a way to do it differently.
