### ISSUE TITLE
NewPipe Play/Download YouTube Movies

### ISSUE THREAD

**Issue by alanyee** [TeamNewPipe/NewPipe#3203]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

YouTube has a variety of legal movie streams on its platform: https://www.youtube.com/channel/UClgRkhTL3_hImCAmdLfDE4g. Some of them require money, and others are free. I would like some way to watch these movies via NewPipe.

**Comment by XiangRongLin** [comment]
Wouldn't you need to be logged in to buy the movies/watch bought movies?

As for free one, do you have an example url?

**Comment by alanyee** [comment]
You would have to log in to buy movies, and regardless if they are free or not, you would have to log in to watch mature movies.

Otherwise, free movies do not require a login: https://www.youtube.com/watch?v=zKQGAv8gtBA

**Comment by gkeegan** [comment]
I believe these movies have some sort of DRM (WideVine?) on them, so trying to do this would be incredibly difficult, if not illegal in most jurisdictions.

I believe this since my phone (which only has the lowest WideVine support) can't play most resolutions and it says "there was an error licensing this video".

**Comment by PeterHindes** [comment]
I dont know about that, it plays on a laptop, so it might not need it unless you use the official app.

**Comment by gkeegan** [comment]
Most browsers have have settings that let you play DRM content. I'm away from my laptop currently so if you could try playing it with in Firefox with the "play DRM protected content" setting off to test that would be nice.

**Comment by alanyee** [comment]
Confirmed on Firefox that turning off `Digital Rights Management (DRM) Content` does prevent the browser from playing the movie.

**Comment by gkeegan** [comment]
Yeah then this feature is not possible.

**Comment by PeterHindes** [comment]
Ok, thanks for confirming.
