### ISSUE TITLE
Some WebM videos are still not seekable in 0.18.6

### ISSUE THREAD

**Issue by ksio89** [TeamNewPipe/NewPipe#3204]
Back in 0.17.3, I created an issue #2676 reporting that YouTube WebM videos didn't have seeking support. Now in 0.18.6 (github build), I noticed that most WebM videos have are seekable, but occasionally some aren't. 

I explained there that just for comparision's sake, Windows application jDownloader2 is able to generate seekable WebM and mkv videos just fine, so this issue is on NewPipe's muxer. I prefer WebM container because most videos in this format are way smaller that in MP4, I'd say 80% of them are, so you might understand why fixing this issue is so important for me.

In #2676 issue thread I got a reply that this was fixed in pull request #2679, but checking that, it says the change was still required and that it was a regression from #2149. The change was listed there as "Webm muxer fixes and strings.xml changes".

I wonder if it's a problem with my phone? My device has VP9 hardware encoding, but I don't see how that would be causing this, as it doesn't dictate how the muxer works. Anyway, I think it's worth reporting this issue again, as it was only partially fixed. Thanks in advance.

**Comment by kapodamy** [comment]
can you upload the webm file and tell me in what video url, resolution?

**Comment by ksio89** [comment]
OK, here they are, both videos from the same channel:

seekable: https://www.youtube.com/watch?v=QrlgAvJI3WU

not seekable: https://www.youtube.com/watch?v=5ufOfV40fx0

Played them on Android (MX Player) and Windows (MPC-HC), and the behaviour for each video is the same. I can immediately know if the video is not seekable because the duration is not shown on the thumbnail.

**Comment by ksio89** [comment]
I hate to sound repetitive, but the bug still hasn't been fixed in 0.18.7. I would like to know if someone else can reproduce this issue, I'm beginning to wonder if this is an issue with my device.

**Comment by wb9688** [comment]
@ksio89: v0.18.7 was only a hotfix for SoundCloud, nothing else got included in that release. Anyway, that issue got fixed in #3220, but that PR wasn't merged yet. Hopefully it'll be in the next proper release.

**Comment by ksio89** [comment]
I see, I saw #3220 pull mentioning this issue and thought the fix would be implemented in the latest release. I'll wait for 0.18.8 and not pest NewPipe devs then, thanks for clarifying it.
