### ISSUE TITLE
Thumbnails preview on seek bar

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#3207]
Youtube offers a way to preview the frames when hovering the progress bar. This is very convenient when you want to go directly to a certain moment of a video or to watch it again.
![Screenshot_20200309-182505](https://user-images.githubusercontent.com/11852634/76241009-7640c880-6234-11ea-9a9f-189e850f49e2.jpg)

**Comment by FreddieOliveira** [comment]
I'd love to have that feature

**Comment by B0pol** [comment]
Invidious has this feature and it's called storyboard by YouTube.
It's available via `playerResponse.storyboards.playerStoryboardSpecRenderer.spec`.
The relevant code is [here](https://github.com/omarroth/invidious/blob/750ef296c63d20dfcd8ea311a44c5cfa28ca196e/src/invidious/videos.cr#L711) and [here](https://github.com/omarroth/invidious/blob/750ef296c63d20dfcd8ea311a44c5cfa28ca196e/src/invidious.cr#L3719) (not exactly this line, scroll down a bit).

**Comment by MD77MD** [comment]
this would be awesome if it can be added to newPipe 0.20.1

**Comment by opusforlife2** [comment]
@MD77MD It would be awesome if this could be added to _any_ version.

**Comment by MD77MD** [comment]
sometimes I just wonder how could the newPipe members find the time to implement all these great ideas.

**Comment by litetex** [comment]
Spoiler alert:
I was a bit annoyed that this feature is still missing and tried to implement it by myself.
Worked out pretty well so far:
![grafik](https://user-images.githubusercontent.com/40789489/120869540-f7515180-c596-11eb-9529-cf41108ca9e8.png)

Hopefully I'll be able to create a pull request in the next few days - if everything is final and working fine 😄

**Comment by Mhowser** [comment]
That's awesome @litetex!  Have you made a pull require st yet?

**Comment by opusforlife2** [comment]
> That's awesome litetex! Have you made a pull request yet?

@Mhowser So excited you forgot to read the last line of the comment? xD

**Comment by litetex** [comment]
> 
> 
> > That's awesome litetex! Have you made a pull request yet?
> 
> @Mhowser So excited you forgot to read the last line of the comment? xD

😆

Anyway, the PR is now ready → #6434

Happy reviewing 😉

**Comment by Mhowser** [comment]
> > That's awesome litetex! Have you made a pull request yet?
> 
> @Mhowser So excited you forgot to read the last line of the comment? xD

Yep lol, my ADHD brain does this a lot.
