### ISSUE TITLE
Last Played section has the wrong amount of views

### ISSUE THREAD

**Issue by apptester235** [TeamNewPipe/NewPipe#3214]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment]
That's the number of times you played the video
