### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SakiburisBoss** [TeamNewPipe/NewPipe#3215]
Set up a way to backup those playlists which were saved in youtube account.

**Comment by Stypox** [comment]
Unfortunately Youtube does not provide a way to export private playlists, so this can't be done

**Comment by SakiburisBoss** [comment]
> Unfortunately Youtube does not provide a way to export private playlists, so this can't be done.
> Also, "Feature Request" is not a meaningful name for an issue

Thanks for sujjestion
