### ISSUE TITLE
What's new

### ISSUE THREAD

**Issue by Vldm11r** [TeamNewPipe/NewPipe#3219]
Sort what's new in order of time.
![Capture+_2020-03-12-20-59-57](https://user-images.githubusercontent.com/59932374/76557651-a2628080-64a4-11ea-9cb3-84206ad26bbe.png)

**Comment by Vldm11r** [comment]
How to enable sorting of new videos as they come out?

**Comment by B0pol** [comment]
It's a known bug. See #2309

**Comment by Vldm11r** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/3219#issuecomment-598390095
But this bug is already more than a year old, which is not fixable at all?

**Comment by gkeegan** [comment]
Not a bug, but the feature has been a work in progress for quite some time.

**Comment by Vldm11r** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/3219#issuecomment-598395307
> Not a bug, but the feature has been a work in progress for quite some time.

So time sorting is possible in at least one of the application versions? Now I have a version with f-droid 0.18.6

**Comment by TobiGr** [comment]
It worked when the feature was introduced and the info provided by YouTube was different.
Next time, search for a similar issue first to create no duplicates, please.
