### ISSUE TITLE
Small text on Android TV in grid view mode

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#3221]
I use android TV ,in Newpipe grid mode there are many videos in the screen even I can't read texts unlike the official version of youtube and youtube TV.
I suggest to cahnge grid layout to have 6 videos similar to youtube version.

![IMG_20200312_212453](https://user-images.githubusercontent.com/11852634/76566660-87483e80-64ad-11ea-9e55-5c86f56c7f78.jpg)
![IMG_20200312_212535](https://user-images.githubusercontent.com/11852634/76566883-ff166900-64ad-11ea-937e-266b0998881f.jpg)

![IMG_20200312_212630](https://user-images.githubusercontent.com/11852634/76566663-89aa9880-64ad-11ea-8d5a-4e880d68ce6d.jpg)

**Comment by Stypox** [comment]
@Alexander-- could #2806 fix this issue?
@TobiGr I think we will need a new "Android TV" label in the future

**Comment by Alexander--** [comment]
@Stypox

No. In #2806 I focused on other issues: broken player controls, broken lists, and broken video descriptions.

**Comment by TobiGr** [comment]
>  I think we will need a new "Android TV" label in the future

Done

**Comment by sorryusernameisalreadytaken** [comment]
>  I suggest to cahnge grid layout to have 6 videos similar to youtube version.

Oh jeah I agree with that suggestion too. Would be awesome.

**Comment by allendema** [comment]
Related #2347

**Comment by opusforlife2** [comment]
Duplicate of #3139.
