### ISSUE TITLE
Notch area isn't darkened

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3227]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Steps to reproduce:
+ Have a phone with a notch, or simulate it with developer options -> display cutout (android 9+ only).
+ Watch a 16/9 video or any video which width is smaller than your screen (so most of the videos)
+ zoom or fit.
+ tap on the screen

Result: <img src="https://i.ibb.co/rpTbxyn/Screenshot-20200314-124858-New-Pipe-1.jpg">

Actual: the area where the notch is (for my phone and with this orientation, at the right) is lighter than the rest of the screen

Expected: be darkened as the rest of the screen, when you tap on it.

It should have been done with https://github.com/TeamNewPipe/NewPipe/pull/2967

**Comment by B0pol** [comment]
I edited step one. With an android 9 phone / emulator, you can emulate a notch with developer settings -> Display cutout.

See the relevant documentation: https://developer.android.com/guide/topics/display-cutout/#test_how_your_content_renders

**Comment by opusforlife2** [comment]
@B0pol Still an issue in 0.20.0?

**Comment by B0pol** [comment]
Yes

**Comment by B0pol** [comment]
No

**Comment by opusforlife2** [comment]
xD
