### ISSUE TITLE
Motorola E4 - App Not Installed

### ISSUE THREAD

**Issue by ArthurMucsi** [TeamNewPipe/NewPipe#3229]
I tried to install in my phone (Motorola E4) and it doesn't install. I've tried an older version, but it still not work (Android 7.1.1 Nougat). I tried to install in FDroid too and still not work.

**Comment by Stypox** [comment]
Do you have NewPipe already installed? Have youi tried disabling Play Protect? Otherwise this error should not have anything to do with NewPipe itself.

**Comment by wb9688** [comment]
Try uninstalling NewPipe before installing NewPipe again.

**Comment by opusforlife2** [comment]
Drop a comment if you do try it.
