### ISSUE TITLE
[Bug] Name of app flashes momentarily when opened through 3rd party link

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3236]
- [x] I checked if the issue/feature exists in the latest version. (ambiguous wording here, it _doesn't_ exist in the latest version but I _did_ check ;) )

When you open the app through a link from another app, the name of the app from #3201 ("Newpipe tabs") flashes for a moment at the place where the resolution drop down is. It also happens in the app from #3178, where the name is "Newpipe notification" instead.

This doesn't happen in the release apk. Which means it's something in the dev branch causing the issue.

**Comment by Stypox** [comment]
Is this still an issue? I can't reproduce

**Comment by opusforlife2** [comment]
Hmm. Still doesn't happen in release. But it happens in wb's YT Music apk too. Maybe it only happens in debug apks? In that case, I think it is a non issue.

One way to check would be to create a debug apk by changing nothing in the code.

**Comment by opusforlife2** [comment]
Happens in release candidates as well, I just noticed.

**Comment by wb9688** [comment]
@opusforlife2: RC is just a debug APK ;)

**Comment by opusforlife2** [comment]
Welp, seeing as the entire top bar is gone now, this isn't a problem anymore. 😆
