### ISSUE TITLE
Playing videos directly in Google Play

### ISSUE THREAD

**Issue by dealelopez** [TeamNewPipe/NewPipe#3241]
I can't play videos directly in Google Play. Is this correct?

**Comment by Stypox** [comment]
If I understood correctly, you want to watch videos in Google Play Store. I haven't been using it in a long time, but if I remember correctly clicking on a video opens it in the app associated with YouTube urls. So NewPipe should work correctly.

**Comment by dealelopez** [comment]
Yes, you understood it correctly. Some versions ago it was possible to reproduce Google Play videos with NewPipe. Now I can't and was wondering if it was my config, Google Play or NewPipe.

**Comment by Stypox** [comment]
The only NewPipe setting I could think of affecting this is "Video & audio -> Preferred 'open' action". Try to set it to "Always ask". Otherwise this is a (volountary) limitation of Google Play.

*(unrelated suggestion: take a look at Aurora Store, a free and open source Play Store client)*

**Comment by dealelopez** [comment]
Thanks! I'll check Aurora Store.
