### ISSUE TITLE
Could not decrypt video URL signature.

### ISSUE THREAD

**Issue by peteksobota** [TeamNewPipe/NewPipe#3244]
Hi!

I am getting the following error on all videos 

`{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=p-XV2XRsu7E",
   "content_language": "en_US",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.18.6",
   "os": "Linux Android 9 - 28",
   "time": "2020-03-17 18:32",
   "exceptions": [
      "org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not load decrypt function\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:747)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:633)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:65)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:61)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: java.net.ConnectException: Failed to connect to youtube.com\/0.0.0.0:443\n\tat okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)\n\tat okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)\n\tat okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)\n\tat okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)\n\tat okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)\n\tat okhttp3.RealCall.execute(RealCall.java:93)\n\tat org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:159)\n\tat org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70)\n\tat org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:42)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:727)\n\t... 30 more\nCaused by: java.net.ConnectException: failed to connect to localhost\/127.0.0.1 (port 443) from \/127.0.0.1 (port 56926) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)\n\tat libcore.io.IoBridge.isConnected(IoBridge.java:278)\n\tat libcore.io.IoBridge.connectErrno(IoBridge.java:187)\n\tat libcore.io.IoBridge.connect(IoBridge.java:129)\n\tat java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)\n\tat java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:228)\n\tat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)\n\tat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)\n\tat java.net.Socket.connect(Socket.java:621)\n\tat okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)\n\tat okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)\n\t... 51 more\nCaused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)\n\tat libcore.io.IoBridge.isConnected(IoBridge.java:267)\n\t... 61 more\n"
   ],
   "user_comment": ""
}`

**Comment by TobiGr** [comment]
1. Pleas convert the report to markdown hen posting it on GitHub
2. This is a network error as you can see at the end of your crash report. Are yoou using a VPN?
`
Caused by: java.net.ConnectException: failed to connect to localhost\/127.0.0.1 (port 443) from \/127.0.0.1 (port 56926) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)\n\tat libcore.io.IoBridge.isConnected(IoBridge.java:278)\n\tat libcore.io.IoBridge.connectErrno(IoBridge.java:187)\n\tat libcore.io.IoBridge.connect(IoBridge.java:129)\n\tat java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)\n\tat java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:228)\n\tat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)\n\tat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)\n\tat java.net.Socket.connect(Socket.java:621)\n\tat okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)\n\tat okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)\n\t... 51 more\nCaused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)\n\tat libcore.io.IoBridge.isConnected(IoBridge.java:267)\n\t... 61 more\n
`

**Comment by peteksobota** [comment]
But I need to use VPN. Why doesn't it work over VPN?
