### ISSUE TITLE
Allow Youtube Account login - e.g. to download unlisted/private videos

### ISSUE THREAD

**Issue by eGit** [TeamNewPipe/NewPipe#3246]
- [ x ] I checked if the issue/feature exists in the latest version.
- [ x ] I did use the [incredible bugreport to markdown converter]

I would like to download private videos from my Youtube account. Making login possible is no option?

**Comment by wb9688** [comment]
No, see [our FAQ](https://newpipe.schabi.org/FAQ/).

**Comment by gkeegan** [comment]
Downloading unlisted videos is possible, you just need a link to the video.
