### ISSUE TITLE
[Feature Request] Support Youtube Music mixes

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3250]
#### Is your feature request related to a problem? Please describe it
With the ability to search music.youtube.com (#3240), it would be nice to be able to play Youtube Music mixes. See: https://github.com/TeamNewPipe/NewPipe/pull/3240#issuecomment-601758968

**Comment by wb9688** [comment]
More info: playlist ID for those are RDAMVM + video ID, and should be requested from music.youtube.com (NOT youtube.com, as then it'll load the YouTube mix that has RD as prefix instead of the YouTube Music mix, so we can't really reuse YouTube mix code).

**Comment by opusforlife2** [comment]
Guys, the feature request template is HUGE. It needs to be trimmed down a little. Most of it was unnecessary here, for example. I didn't realise this while reviewing the PR, but the template should look inviting in the write box as well, where the text is still plain. Using it for the first time just now was... forbidding.

**Comment by XiangRongLin** [comment]
In what way do they differ from youtube mixes?

**Comment by wb9688** [comment]
@XiangRongLin: YouTube Music mixes only exist for streams that are on YouTube Music, and only contain streams that are on YouTube Music.

**Comment by opusforlife2** [comment]
Whoops. Added in https://github.com/TeamNewPipe/NewPipeExtractor/pull/788.
