### ISSUE TITLE
Autoplay switch highlight color

### ISSUE THREAD

**Issue by haggaie** [TeamNewPipe/NewPipe#3254]
The autoplay switch shows up in the same color regardless whether it is on or off. This makes it difficult to tell what's its current state is.

It would be nice to highlight the switch with color when it is turned on.

**Comment by opusforlife2** [comment]
Good first issue label?

**Comment by Bawya1098** [comment]
Hello @haggaie ,  I would like to try and Contribute and work on this.

**Comment by haggaie** [comment]
Hi @Bawya1098, I'll be happy to test your code out.

**Comment by Bawya1098** [comment]
@haggaie 
![Screenshot_1597821517](https://user-images.githubusercontent.com/47107708/90604453-79e06e80-e21a-11ea-97f1-a58a421489e4.png)
Where do I find the autoplay button? 😕

**Comment by justanidea** [comment]
@Bawya1098 dont expand the description, and if you see comments under, swipe right and you'll be able to see suggested videos: just over them you will see the switch

**Comment by Bawya1098** [comment]
@justanidea , @haggaie  . 
[please do take look at it ](https://github.com/TeamNewPipe/NewPipe/pull/4162#partial-pull-merging)

**Comment by opusforlife2** [comment]
By the way
> The autoplay switch shows up in the same color regardless whether it is on or off.

This isn't actually the case. Disabled, it's grey. Enabled, it's white (or off-white). But I agree it should be changed.

**Comment by haggaie** [comment]
Hi @Bawya1098 
> [please do take look at it ](https://github.com/TeamNewPipe/NewPipe/pull/4162#partial-pull-merging)

I'm sorry for the delay. I wasn't sure if you still wanted me to test this version based on the comments from the pull request. Anyway, I see the autoplay toggle as red, which looks more pronounced to me than the previous color. I see it is red for all services though.

**Comment by opusforlife2** [comment]
@haggaie PR related comments in the PR, please. ^
