### ISSUE TITLE
Sort By Date Feature

### ISSUE THREAD

**Issue by mehedihasanziku** [TeamNewPipe/NewPipe#3257]
I would like to see this feature in newpipe, it will help us to find latest videos faster instead of scrolling.

![IMG_20200322_220456_884](https://user-images.githubusercontent.com/48652123/77254176-ac953380-6c89-11ea-974a-25f2d55050ec.JPG)

Hope Team NewPipe will implement this feature very soon.

**Comment by Stypox** [comment]
Closed in #2309

**Comment by Stypox** [comment]
Oh and if this is about search it is a duplicate of #2251

**Comment by mehedihasanziku** [comment]
Yes, it was about search filter.

**Comment by rithans** [comment]
additional sorting option will be also useful to everyone to sort playlist  by alphabetically and by last played.

**Comment by mehedihasanziku** [comment]
recent filter really required....
