### ISSUE TITLE
video URLs with appended playlist code are not played in background

### ISSUE THREAD

**Issue by gloschtla** [TeamNewPipe/NewPipe#3258]
In android open a youtube address which is contained in the middle of a playlist via NewPipe's "Background player" and you will realise, it wrongly starts playing at the first playlist entry.

https://www.youtube.com/watch?v=1HMshnQOQTQ&list=PLrgUJTSd4L4tvFXOMe2WrFZcyqbWNkdoc&index=6&t=0s

**Comment by Stypox** [comment]
#928
