### ISSUE TITLE
Unsupported URL after recent update to 0.18.7

### ISSUE THREAD

**Issue by slishnevsky** [TeamNewPipe/NewPipe#3260]
After I updated NewPipe to v 0.18.7, I began to receive 'Unsupported URL" error for every video I want to share.

**Comment by slishnevsky** [comment]
![Screenshot_20200323-022913](https://user-images.githubusercontent.com/2932739/77288541-6dc5a480-6cae-11ea-9845-192741632967.jpg)
This happens when I try to open any video by it's URL in NewPipe

**Comment by Stypox** [comment]
This has nothing to do with URLs. This is another time a problem in YouTube extractor @wb9688

**Comment by wb9688** [comment]
You shouldn't have removed the issue template and you should've used the incredible bugreport to markdown converter. Bug report is useless like this, plus I don't get that error when requesting that stream.

**Comment by slishnevsky** [comment]
I checked a few hours later and it worked. Not sure what happened.

**Comment by daraul** [comment]
I think I am having this problem on v0.20.2. I just get this when I attempt to share to newpipe:

![Screenshot_2020-11-12-10-45-39-553_org schabi newpipe](https://user-images.githubusercontent.com/2440975/98954541-41c49100-24d4-11eb-8bc6-e90eaa20b2ec.jpg)

**Comment by opusforlife2** [comment]
@daraul What's the link you're sharing? Could you paste it here?

**Comment by daraul** [comment]
Sure, it's https://youtu.be/qNGQyRDFoNc

**Comment by opusforlife2** [comment]
@daraul Works fine for me. Are you sure you're sharing this very URL? It's not a part of a bigger URL or shared from some website that modifies the URL?

**Comment by daraul** [comment]
I share it from the YouTube app (and YouTube vanced) and get the same thing. 

I just reinstalled the app, and it works fine, now.
