### ISSUE TITLE
Returning from video to channel does not work, returns to search

### ISSUE THREAD

**Issue by Beep6581** [TeamNewPipe/NewPipe#3269]
### Version
0.18.7
- 

### Steps to reproduce the bug
1. Search YouTube for a channel, e.g."jre"
2. Open the channel from the search results, e.g. "PowerfulJRE"
3. Click on a video. You would do this to e.g. download the audio.
4. Click the return arrow in the top-left corner.

### Expected behavior
I return to the channel, and the app scrolls to the same place I was at before.

### Actual behaviour
The app returns to the search results. I have to re-open the channel and scroll down to where I was.
Note: if I return not using the app's return arrow in the top-left corner of the screen, but using Android's return arrow at the bottom of the screen, then it returns correctly to the channel and to the same scroll position.

**Comment by TriplEight** [comment]
Another repro:
 if you started the app via YouTube link,
 There's no way to get from it to the UI, like channel, info, comments.

**Comment by wb9688** [comment]
@Beep6581: That's intended behavior. There is a difference between the up and the back button.

@TriplEight: What do you mean? Have you set that as action in Settings -> Video & audio -> Preferred 'open' action?
