### ISSUE TITLE
Make the mute button faster accessible for pop-up and background player

### ISSUE THREAD

**Issue by Poolitzer** [TeamNewPipe/NewPipe#3275]
this is related to #3165.

### Pop-up Player:

Currently, to mute a video playing in pop-up, I need to scroll down my notifications, press on the NewPipe one, then it's in the upper corner. If the pop-up window is big enough though, there is space after the captions string. Someone could use that to implement the mute button.

<img src="https://user-images.githubusercontent.com/25934244/77593630-bd27f280-6eb1-11ea-8662-5fb0a97c33f6.jpg" alt="screenshot of the pop-up player" width="300px">

I hope the red arrow makes clear what I mean.

### Background Player:

Currently, to mute a video which is playing in the Background, I need to scroll down my notifications, press on the NewPipe one, then it's in the upper right corner. This process can be simplified if we add the mute button between the repeat and the back control directly in the notification.

<img src="https://user-images.githubusercontent.com/25934244/77594358-94a0f800-6eb3-11ea-9eee-6a6f42c3b5cc.png" alt="screenshot of the pop-up player" width="300px">

I hope the red arrow makes clear what I mean.

**Comment by Stypox** [comment]
I don't think this should be done. In the popup player there are already too many icons, and when it is not full-sized it looks strange. In the background notification there is almost not enough space for the repeat button on phones with lower `dpi`s. Also, the background notification will be replaced soon.
@TobiGr what is your opinion? I don't think this should be implemented, also because the mute button is not used by so many people

**Comment by Poolitzer** [comment]
Both of your issues can be countered with "only display the button if enough place is there". At least for the pop up window this works, not sure about the notification.

**Comment by Stypox** [comment]
Yeah but there are more important buttons that could be fit instead

**Comment by wb9688** [comment]
About putting that in the notification: not possible after #3178

**Comment by B0pol** [comment]
> About putting that in the notification: not possible after #3178

no, that's false. It will even be better, because you can choose in settings which one to choose. Now there are more important buttons that could be in notifications, but if user can choose, there is no problem to add it via settings.

**Comment by opusforlife2** [comment]
What's the use of having a mute button for background audio, anyway? The PR linked issue just asked for MX Player like functionality, which I can understand as it's for video. For example, you could watch a math problem being solved while another app is playing music. What about audio, though?

**Comment by Poolitzer** [comment]
I am not sure, I just wanted to provide feedback for a way to easier access it :)

**Comment by opusforlife2** [comment]
Oh, I am asking everyone for their opinion. Just seems like a pointless addition to the app. I thought for a moment that it might be useful to mute when sponsored sections start, but then you have the much better option of directly skipping them. Can anyone think of a use for the mute button in the background player?

**Comment by Poolitzer** [comment]
The idea of adding it in general? I guess you are a bit too late for that?

**Comment by opusforlife2** [comment]
> The idea of adding it in general? I guess you are a bit too late for that?

NUKE THE CODE, I SAY! MWAHAHAHAHAH!

**Comment by Poolitzer** [comment]
Oh okay. Uhm sure. Let me just see where I put the code nukes...

*Steps away*

**Comment by opusforlife2** [comment]
_sinister giggles_

**Comment by opusforlife2** [comment]
Yes or no?

**Comment by Stypox** [comment]
This was chosen this way since the mute button is a niche feature. So it does not deserve a exclusive space
