### ISSUE TITLE
Background player randomly closes (stops playing)

### ISSUE THREAD

**Issue by Andre601** [TeamNewPipe/NewPipe#3280]
### Version

- 0.18.7 (Updated today)

### Steps to reproduce the bug

1. Select a saved playlist (Skip this for single song)
2. Select a song to play in background, or start a playlist to play in background.

### Expected behavior
The music should play as normal and without any issues.

### Actual behaviour
The music randomly stops.

### Screenshots/Screen records
If applicable, add screenshots or a screen recording to help explain your problem. GitHub should support uploading them directly in the issue field. If your file is too big, feel free to paste a link from an image/video hoster here instead.

### Logs
If your bug includes a crash, please head over to the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/). Copy the result. Paste it here:

### Additional information
It happens with pretty much any song and is completely random, when it stops. Sometimes does it stop after only a few seconds, sometimes does it work for a few minutes.
This issue also occured before updating to newest version, which made me check, if there is an update and after updating did it still occur.

The player doesn't just stop but rather completely close.
No crashes, or any kind of error messages shown.

This happens no matter if you use any other apps (including some which don't even require/use audio features) or just have the player itself open (NewPipe app closed).

**Comment by Stypox** [comment]
Do you have battery optimizations enabled? Which phone and OS version do you have?

**Comment by Andre601** [comment]
> Do you have battery optimizations enabled? Which phone and OS version do you have?

Do you mean under `Device care > Battery > Power mode`?
It is set to Optimised

Version: Android 10

**Comment by Stypox** [comment]
Try to disable that and tell me if it fixes your issue. Also, try to find if there is a way to take NewPipe out of the battery-optimized apps, so that it is left free to run and play audio in the background.
Thank you :-)

**Comment by Andre601** [comment]
I disabled the adabtive battery option, which would put not used apps into standby and it seems to work again now...
I'll close this for now. If there is still this issue in the future will I reopen this and let you know.
