### ISSUE TITLE
This specific video cannot play or be downloaded

### ISSUE THREAD

**Issue by AnotherLife** [TeamNewPipe/NewPipe#3285]
https://youtu.be/niCfPZgWLqY

That video does not play in Newpipe's current stable version, I get "Content unavailable". It doesn't play on the Youtube app either, I get "This video is unavailable on this device". I also tried using onoine youtube downloaders but none worked! Why is this? I can see the comment section and some people mention not being able to watch it on tablets.

**Comment by Grandolf49** [comment]
Hi, @AnotherLife I noticed that even on my laptop this particular video throws an error saying "Content Unavailable". I'm guessing this issue is not related to the android application but from the uploader's or youtube's end.

**Comment by AnotherLife** [comment]
Yes, it seems it doesn't play anywhere!
