### ISSUE TITLE
ParsingException: Malformed url

### ISSUE THREAD

**Issue by yxd0018** [TeamNewPipe/NewPipe#3290]
When I share youtube video from podcast addict on Android 10 to newpipe 0.18.7, I get parse website error.

{
   "user_action": "requested stream",
   "request": "vnd.youtube:HB7xrWHqoKQ, opened with video_player",
   "content_language": "en_US",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.18.7",
   "os": "Linux Android 10 - 29",
   "time": "2020-03-28 14:00",
   "exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Malformed url: vnd.youtube:HB7xrWHqoKQ\n\tat org.schabi.newpipe.extractor.utils.Utils.getBaseUrl(Utils.java:185)\n\tat org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:47)\n\tat org.schabi.newpipe.extractor.StreamingService.getStreamExtractor(StreamingService.java:261)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:61)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.Single.subscribe(Single.java:3424)\n\tat org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:551)\n\tat org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:523)\n\tat android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)\n\tat android.os.Handler.dispatchMessage(Handler.java:107)\n\tat android.os.Looper.loop(Looper.java:214)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: java.net.MalformedURLException: unknown protocol: vnd.youtube\n\tat java.net.URL.<init>(URL.java:608)\n\tat java.net.URL.<init>(URL.java:498)\n\tat java.net.URL.<init>(URL.java:447)\n\tat org.schabi.newpipe.extractor.utils.Utils.stringToURL(Utils.java:146)\n\tat org.schabi.newpipe.extractor.utils.Utils.getBaseUrl(Utils.java:183)\n\t... 29 more\n"
   ],
   "user_comment": ""
}

**Comment by XiangRongLin** [comment]
Please don't just delete the template and actually follow the template so we can get a proper bug report.

This is a duplicate of #3091 and already solved and about to be released with v0.19.0

**Comment by yxd0018** [comment]
Thanks.
