### ISSUE TITLE
Channel item too small in mixed grid lists

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3291]
### Version

- 0.18.7

### Steps to reproduce the bug

1. Put grid mode if you are not already using it (settings -> appearance -> list view mode -> grid)
2. Search a channel
3. You will get the channel in the first results, with its popular / recent videos.

### Expected behavior
I expect the channel item to be at a reasonable size 

### Actual behaviour
The channel item is really small

### Screenshots/Screen records
What happens | Same with playlists | It's ok with channels though
------------------- | ------------------------- | ---------------------------------
<img src="https://user-images.githubusercontent.com/58657617/77825043-c063ee00-70fe-11ea-9e9b-bb999e762745.png"> | <img src="https://user-images.githubusercontent.com/58657617/77825045-c3f77500-70fe-11ea-8a60-c736ae09cb01.png"> | <img src="https://user-images.githubusercontent.com/58657617/77825048-c528a200-70fe-11ea-8c71-d0ed6caa9b4c.png">

**Comment by alxlg** [comment]
Do you want like me less margins where marked in the image below?

![](https://i.imgur.com/Ahy4dPS.png)
