### ISSUE TITLE
Feed Groups should be renamed to Channel Groups in the Subscriptions tab

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3297]
It makes more sense, since we're grouping channels _into_ feeds. The feeds _are_ the groups.

@B0pol

**Comment by B0pol** [comment]
You can edit yourself.
[Just rename this](https://github.com/TeamNewPipe/NewPipe/blob/5f549a8fc688157dfea8329408311e52e7e8c88f/app/src/main/res/values/strings.xml#L620) @opusforlife2

**Comment by opusforlife2** [comment]
Ah. I got the impression that it was a more involved process. https://github.com/TeamNewPipe/website/pull/145#discussion_r399853523

**Comment by opusforlife2** [comment]
@Stypox could you do it? You can directly make the change in the dev branch, right?

**Comment by Stypox** [comment]
You should be able to just edit the file on github and then create a pr, in a few seconds. I don't have the permission to write to dev ;-)

**Comment by opusforlife2** [comment]
https://github.com/opusforlife2/NewPipe/commit/e2d2c578a608b26d5fd444580769aa4f7e031480 ヽ(｀Д´)ﾉ

**Comment by mauriciocolli** [comment]
@opusforlife2 Why don't you [just use weblate for changing that](https://hosted.weblate.org/translate/newpipe/strings/en/?checksum=3ebd36970e6552cc)? We don't want more even more conflicts by changing it here.

**Comment by opusforlife2** [comment]
I had no idea you could do that. What do you mean by conflicts?

**Comment by mauriciocolli** [comment]
@opusforlife2: Ignore the conflicts part, Weblate should be able to deal with these type of changes just fine. Regardless, why not just use it?

**Comment by opusforlife2** [comment]
As I said, I didn't know. Is the Weblate method objectively better than a pull request? Only, I'd prefer not having to make and maintain yet another account, just to make string related changes.

**Comment by mauriciocolli** [comment]
IMO yes, that's why we have a translation system in the first place: to not spam our repository with pull requests related to translations.

I consider this as a sort of translation because you didn't rename the string name or the classes. At the core, the original name will stay the same, as they still make sense there (`FeedGroup` → the group feature _related_ to the feed feature).

>I'd prefer not having to make and maintain yet another account

You can login with your Github account.

**Comment by opusforlife2** [comment]
Made the change and saved it. What does the Suggest button on Weblate do, though? It doesn't say.

**Comment by B0pol** [comment]
This issue was closed in 8b73d2d
