### ISSUE TITLE
Improved timeStamp pattern matching

### ISSUE THREAD

**Issue by scde** [TeamNewPipe/NewPipe#330]
Hi,

another user on [reddit](https://www.reddit.com/r/linuxmasterrace/comments/4sgin4/when_youre_doing_a_speedrun_and_suddenly_windows/d594ulh) noticed that there is bad pattern matching with certain timestamps (unlabelled seconds with more than 3 digits).
You can reproduce the issue. This link:
[https://youtu.be/sVUpBYPogpY?t=2571](https://youtu.be/sVUpBYPogpY?t=2571)
opens in NewPipe at 4:17 (257 seconds => ?t=257)
although it should open at 42:51 (2571 seconds => ?t=2571).

The problem is that the RegEx in 
NewPipe/app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
in line 571 should match against more than 3 digits.
So instead of
`secondsString = Parser.matchGroup1("t=(\\d{1,3})", timeStamp);`
maybe go for
`secondsString = Parser.matchGroup1("t=(\\d{1,7})", timeStamp);`
because youtube videos can apparently get very [long](http://www.huffingtonpost.com/2011/07/27/longest-youtube-video-ever_n_910012.html)
or
`secondsString = Parser.matchGroup1("t=(\\d+)", timeStamp);`

I haven't tested anything so take the code suggestions with a grain of salt.

Thanks for your work and have a nice day =)

**Comment by theScrabi** [comment]
Can you give an example for a video where the timestamp is displayed wrong.

**Comment by scde** [comment]
The one I posted above should work.
[https://youtu.be/sVUpBYPogpY?t=2571](https://youtu.be/sVUpBYPogpY?t=2571)

In the browser it seeks to 42:51 but if you open it with the NewPipe it seeks to/opens at 4:17 because the parsing of the "?t=2571" is not correctly working. It only parses the first three digits so "257" and not "2571".

> YoutubeStreamExtractor.java
> line 571

could be the cause.

**Comment by theScrabi** [comment]
ow its the seeking problem. Yes i know.

**Comment by scde** [comment]
Yeah I guess I didn't make myself clear beforehand. Sorry if this is a duplicated bug report.

**Comment by Gracecr** [comment]
I just tested @scde 's proposed fixes. Both seem to fix the issue, the video is given the correct time stamp. The second solution seems to be the most flexible allowing for arbitrarily large timestamps. I submitted a PR [here](https://github.com/theScrabi/NewPipe/pull/331).

**Comment by theScrabi** [comment]
Great thanks :)
