### ISSUE TITLE
(help) infinite loading and cant play in VLC

### ISSUE THREAD

**Issue by ShoopDaWhoop1** [TeamNewPipe/NewPipe#3306]
Hi guys. i'm having this issue for about 2 weeks, when i press play it stucks in an infinite loading screen, (soundcloud is working fine) tried all versions from 16.2 to the newest and i get the same "bug".

tried open with vlc and got this: https://i.ibb.co/6XXwR4Z/bug-newpipe.png

I am running android 7.1.1, moto E4

thanks!

**Comment by Stypox** [comment]
Take off that photo, it contains your ip 😅

**Comment by Stypox** [comment]
Duplicate of #2415
