### ISSUE TITLE
ReCAPTCHA works only with stock Android System Webview

### ISSUE THREAD

**Issue by Ristovski** [TeamNewPipe/NewPipe#3310]
On the latest (v.19.0) version of NewPipe, ReCAPTCHAs work only when the `WebView implementation` option under `Developer Settings` of Android is set to `Android System WebView` aka the stock Android webview.

Setting this to `Chrome`, and thus using the WebView provided by an installed Chrome version (like Beta/Dev) makes it so NewPipe endlessly gets captchas over and over again.

In both scenarios the captcha can be solved, but using any non-stock WebView implementation makes it so the captcha appears again in an endless loop.

I haven't looked into the code yet, but could this be related to how NewPipe gets the cookies from the WebView?

**Comment by Stypox** [comment]
Thank you for the detailed report, this was needed since a long time! You can take a look [here](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java) at how cookies are obtained
