### ISSUE TITLE
"Open in YouTube" feature under video settings

### ISSUE THREAD

**Issue by miladmaz12** [TeamNewPipe/NewPipe#3314]
#### Is your feature request related to a problem? Please describe it
No

#### Describe the solution you'd like
Add an open in YouTube option directly under video settings on NewPipe.

#### How will you/everyone benefit from this feature?
If I want to like a video I'm watching on YouTube, I have to do extra steps from the NewPipe app to get there, rather than just add a quick and easy option under NewPipe video settings.

**Comment by gkeegan** [comment]
Open in the YouTube app? You can use the share menu. Also please use the template next time. More detail = more likelihood someone will consider adding it.

**Comment by XiangRongLin** [comment]
@gkeegan Does that even work, since the youtube app only accepts urls in the vnd format (vnd.youtube:videoId) and not the normal url of a video.

**Comment by mauriciocolli** [comment]
@miladmaz12 there's already an option to do that: in a video page, open the menu (the "⋮" button) and select "Open in browser".

I think we should change that to "Open in external app" or something more obvious, but it is there. Another thing is that it also doesn't open directly to the YouTube app, but it will be an option to you if you have it installed.

**Comment by PetbkA** [comment]
> You can use the share menu

> @miladmaz12 there's already an option to do that: in a video page, open the menu (the "⋮" button) and select "Open in browser".

It won't help if browser is set to open all _YouTube_ links in _NewPipe_, so if you choose to open link in browser, it'll just redirect it to _NP_

**Comment by B0pol** [comment]
Fixed by https://github.com/TeamNewPipe/NewPipe/pull/3501. Open in browser will really open in browser, if you have Android 6+. It will be included in the next version.
