### ISSUE TITLE
Older feed UI switch

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [TeamNewPipe/NewPipe#3315]
Dear newpipe team,
Please add an option to switch back to older UI in what's new tab,
I've subscribe to multiple channels including a news channel in newpipe.
Now when i go to what's new tab I can only see recent videos from the news channel and recent videos of other channels are slipped below and I had to scroll a lot to see what's new with other channels.(I know if a new videos is available from other channels it will be shown at the top but news channel updates more frequently)
In older UI newpipe only showed most recent video which was more convenient for me.
I created feed groups to but it was not helpful.

Screenshots:

![Screenshot_20200331-104929](https://user-images.githubusercontent.com/38154154/77990346-b6303280-733e-11ea-9c2d-85ca09f0ead9.png)

![Screenshot_20200331-104922](https://user-images.githubusercontent.com/38154154/77990456-060ef980-733f-11ea-97a6-7bbcc85c3ada.png)

**Comment by gkeegan** [comment]
I think the best solution for you would be to use the subscription groups feature, which I see you already have some groups. Add all the non-news channels to one group then view it. What is not satisfactory with this?

Making a toggle to go back to the old implementation would more be work than it is worth for how much usage it will get when there is already a solution.

**Comment by Ashutosh-Kukreti** [comment]
@gkeegan Thank you very much for the suggestion.
I guess I'll adjust to the new UI.
An option to remove the group Feed = ALL would be helpful since it will save a lot of space as we already have what's new tab.

**Comment by ritmation** [comment]
> Making a toggle to go back to the old implementation would more be work than it is worth for how much usage it will get when there is already a solution.

@gkeegan I also miss the old behavior. Would it be hard to add an option which would control how many videos from each channel are shown in the feed? If there was such an option, I could set it to 1 and get the best of both worlds: chronologically sorted videos and only the latest video from each channel in the feed.
Thank you.

**Comment by gkeegan** [comment]
@ritmation I actually think that is a great idea and would be possible as far as I know.

**Comment by MD77MD** [comment]
although the new feed UI has been a long awaited feature.. old feed UI definitely had its uses... combining both would be really awesome
I would suggest to add  swipe left and right (like the one used between comments and related videos) to switch between two panels
-the first panel is used for listing feeds by upload time (new feed UI)
-the second panel will show latest video from each channel (old feed UI)..  i would also like the ability to go to the channel from here directly added.. maybe by adding channel icon next to video or by an option in video menu.

**Comment by Stypox** [comment]
Closing in favour of #3827
