### ISSUE TITLE
Sort bookmarked playlists in main page

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3316]
#### Is your feature request related to a problem? Please describe it
NOT related to #3263, because it's about inner playlist sorting. I'm talking about bookmarked playlists you can add or create in main page. I'll explain below.

#### Describe the solution you'd like
I've several playlists created or added in main page, and they are currently sorted by name (automatically). I'd like to sort them as I want, to move some playlists up, other down.
Open a playlist **that you have created**, you'll see at the right two —, and when you click on it, you can move up or down a video. That's exactly what I want (not mandatory this design), but in main page.

#### How will you/everyone benefit from this feature?
Convince us! How does it change your NewPipe experience and/or your life?
The better this paragraph is, the more likely a developer will think about working on it.
It is really cool when you have a lot of playlists, you want to sort them. For example, I'd like to put all the music playlists at the top, and the coding playlists at the bottom.

**Comment by blackholeearth** [comment]
This is really good if you have lots of playlist. 

You can push old ones to bottom.
Keep the newly added lists at top.

 i have local tv series 10 of i watched last year 5 im currently watching. 

İ wanna push 5 current  tv series to top. So old 10 playlist wont distract/ get in my way

**Comment by createchange** [comment]
I would like to see this implemented. The first playlist I had was a "Watch Later" playlist. I have since added enough new playlists to where I have to scroll down to add new videos to this playlist.

Being able to sort playlists manually (or at least pin selected ones to the top) would be wonderfully helpful.

**Comment by Stypox** [comment]
Please test if https://github.com/TeamNewPipe/NewPipe/pull/8221 works well :-)

**Comment by createchange** [comment]
@Stypox, Thanks for your work on this! It's a wonderful app that is my sole portal into Youtube. Saw the rewrite thread for the first time just now - hoping that you guys are finding enjoyment in keeping this thing afloat!
