### ISSUE TITLE
Feature Request: Pull to refresh What's New feed

### ISSUE THREAD

**Issue by Pentaphon** [TeamNewPipe/NewPipe#3321]
#### Is your feature request related to a problem? Please describe it
The tiny button to refresh feeds is all the way up at the top right of my screen. It would be much easier for people to be able to pull to refresh their feeds, especially if they have bigger phones. 

#### Describe the solution you'd like
A pull to refresh function on the what's new feed!

#### How will you/everyone benefit from this feature?
Phones keep getting bigger and taller, so a pull to refresh feature on the what's new feed would make refreshing easier for everybody!

**Comment by wb9688** [comment]
We'll need to add `androidx.swiperefreshlayout:swiperefreshlayout:1.0.0` as dependency for that :/

**Comment by Stypox** [comment]
Closing in favour of #3321
