### ISSUE TITLE
Background Player Control Buttons

### ISSUE THREAD

**Issue by marianov1** [TeamNewPipe/NewPipe#3324]
I'd like to have the regular buttons, play, pause, etc., while playing on "background" (sound only).
Once I start playing in background, I hear the sound track, but can't even pause it without closing the app.
Player controls in the notification area while playing in background would be a plus!

**Comment by Stypox** [comment]
Player controls in the notification area while playing in background exist, aren't you seeing them? :thinking: 
By the way, *please **follow the issue template** when creating an issue, don't just delete everything*. Now I have to ask questions you would have already answered: which version are you using? What's your Android version and what's your phone?

![IMG_20200401_195256](https://user-images.githubusercontent.com/36421898/78170200-e23cd800-7452-11ea-9877-080efa11c8dc.png)

**Comment by marianov1** [comment]
Ok, sorry about that. It was my first time here, next time I'll follow the template.

My phone is a Moto E4 XT1762;
Android 7.1.1
NewPipe 0.18.7

**Comment by gkeegan** [comment]
@Stypox many GitHub apps don't load the template, so a lot of the time when this happens it could be that.

I know mine doesn't and I have to copy-paste it in.

**Comment by marianov1** [comment]
> @Stypox many GitHub apps don't load the template, so a lot of the time when this happens it could be that.
> 
> I know mine doesn't and I have to copy-paste it in.

Sorry @gkeegan, I'm new here. What do you mean by copy-paste?
Can you explain how to do it, please?

**Comment by gkeegan** [comment]
@marianov1 You can copy the contents of the right template (either for bug report or for feature request) from https://github.com/TeamNewPipe/NewPipe/tree/dev/.github/ISSUE_TEMPLATE and paste it into a new issue then fill it out. (Just remove the first few lines between the "---"s.) 

The GitHub mobile app recently got support for automatically loading templates so it might not be a problem anymore if you use that.

**Comment by zelds** [comment]
Same issue.
Nokia 7.1
Android 10
Version 19.2

**Comment by opusforlife2** [comment]
Do you guys have notifications turned off for Newpipe? Might be a good idea to check this first.

**Comment by zelds** [comment]
> Do you guys have notifications turned off for Newpipe? Might be a good idea to check this first.

It use access only to storage.

**Comment by opusforlife2** [comment]
Reply if this is still a problem.
