### ISSUE TITLE
No comments on every video

### ISSUE THREAD

**Issue by AndhikaWB** [TeamNewPipe/NewPipe#3326]
### Version

- 0.19.1 (also happened on 0.18.7, not sure on older version). Still, it used to work before.

### Steps to reproduce the bug

1. Open NewPipe
2. Click on any YouTube video
3. Check on the comments section

### Expected behavior
All comments should appear.

### Actual behaviour
No comments appeared and "No comments" text is always here.

### Screenshots
![Screenshot_20200402-013529_NewPipe](https://user-images.githubusercontent.com/17119394/78174852-21cfe800-7484-11ea-8c89-28bd76f6d663.png)

### Other notes
Fresh install, no settings is changed. Using LineageOS 17.1. I think it happened after the (major) extractor update on NewPipe..

**Comment by wb9688** [comment]
>I think it happened after the (major) extractor update on NewPipe..

Not possible, since I didn't change anything about the comments extractor. I do sometimes have this issue as well though, but definitely not always and I've had it before v0.18.5 iirc.

**Comment by AndhikaWB** [comment]
> > I think it happened after the (major) extractor update on NewPipe..
> 
> Not possible, since I didn't change anything about the comments extractor. I do sometimes have this issue as well though, but definitely not always and I've had it before v0.18.5 iirc.

I'm just guessing it based on the changelog, maybe it's just coincidental but I don't have these problem on lower version. Although I don't know the exact version (yet).

One more info: I replaced stock AOSP Webview with Bromite Webview on this ROM, but I don't think it will cause this issue since the package name is the same.

**Comment by wb9688** [comment]
>I'm just guessing it based on the changelog, maybe it's just coincidental but I don't have these problem on lower version. Although I don't know the exact version (yet).

Try if it works in v0.18.4 then.

>One more info: I replaced stock AOSP Webview with Bromite Webview on this ROM, but I don't think it will cause this issue since the package name is the same.

That could only affect reCAPTCHA, not the normal extraction.

**Comment by AndhikaWB** [comment]
It still doesn't work but I think I know what caused it: Android private DNS. I disabled it (I was using `dns-family.adguard.com`) and the comments are back.

**Comment by AndhikaWB** [comment]
I also realized that maybe I was still on Android 9 when using older version of NewPipe. It's strange because I also used private DNS back then.

My only guess is that something changed on Android 10 if the problem isn't caused by NewPipe itself.

**Comment by AndhikaWB** [comment]
@firepainting I'm using NextDNS with my own configuration, imo it's way more customizable compared to Adguard. I don't have a child though, I'm using it for myself 😅
