### ISSUE TITLE
Still getting ArrayIndexOutOfBoundsException error with 19.0.1

### ISSUE THREAD

**Issue by givemestella** [TeamNewPipe/NewPipe#3327]
Still getting the

ArrayIndexOutOfBoundsException
Error closed in #3296

{
   "user_action": "download post-processing",
   "request": "hiiden" [ {type=video format=MPEG-4 quality=1080p60 videoOnly=true}  {type=audio format=m4a bitrate=128} ]",
   "content_language": "en_GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.19.1",
   "os": "Linux Android 10 - 29",
   "time": "2020-04-01 21:27",
   "exceptions": [
      "java.lang.ArrayIndexOutOfBoundsException: src.length=28 srcPos=-431884372 dst.length=8192 dstPos=0 length=8192\n\tat java.lang.System.arraycopy(Native Method)\n\tat us.shandian.giga.io.CircularFileWriter$BufferedFile.write(CircularFileWriter.java:405)\n\tat us.shandian.giga.io.CircularFileWriter.write(CircularFileWriter.java:231)\n\tat org.schabi.newpipe.streams.Mp4FromDashWriter.outWrite(Mp4FromDashWriter.java:502)\n\tat org.schabi.newpipe.streams.Mp4FromDashWriter.outWrite(Mp4FromDashWriter.java:497)\n\tat org.schabi.newpipe.streams.Mp4FromDashWriter.make_ftyp(Mp4FromDashWriter.java:629)\n\tat org.schabi.newpipe.streams.Mp4FromDashWriter.build(Mp4FromDashWriter.java:263)\n\tat us.shandian.giga.postprocessing.Mp4FromDashMuxer.process(Mp4FromDashMuxer.java:22)\n\tat us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:174)\n\tat us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:702)\n\tat us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(Unknown Source:0)\n\tat us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(Unknown Source:2)\n\tat java.lang.Thread.run(Thread.java:919)\n"
   ],
   "user_comment": ""
}

**Comment by wb9688** [comment]
Fixed in #3325, wait until v0.19.2
