### ISSUE TITLE
Improve "What's New" refresh experience: auto refresh, pull to refresh

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#3329]
###  Is your feature request related to a problem? Please describe it 

Related to Issue #3321  
Refreshing the what's new page feels slower/clunkier than it needs to.
Refreshing is a commitment, especially if you have a lot of subscriptions. I feel like I need to check all of the videos I've loaded before I take the 2 minutes needed to refresh 200 channels.

### Describe the solution you'd like

A few things:

Add #3321 (pull to refresh)

Option to refresh on app start.

When refreshing, the loading bar should be contained in the status box which currently holds the refresh button. Additionally, the old data should be kept until the new data has been loaded. 

Ideally, the new data is loaded "over" the old data, pushing it further down the list, using the current position in the list as an anchor (either near the top of the list, or the items you're viewing in the list). 

For example, if I've refreshed and stayed near the top, the old videos will be pushed down/unloaded if needed, whereas if I had scrolled down to view older content, the new data would be loaded above the old, as to not lose my place in the list. (in this case, data that should be unloaded will be unloaded once the user has navigated to another screen)

### How will you/everyone benefit from this feature?

The what's new page is amazing, and much thanks to @mauriciocolli for all their hard work, but I personally believe that refreshing is a bit clunky and could use a touch up.

I think if these proposals can be achieved, then the what's new page will have near seamless and intuitive interaction. Pull to refresh is near universal now, and if you have a lot of subscriptions, if gives you newish stuff to look through while newer stuff is loaded.

**Comment by Gymcap** [comment]
Unrelated: My GitHub app doesn't load the default issue template, I had to copy it from someone else. This could be why so many don't follow the templates, that would have been my case in the past.

**Comment by HTSamurai** [comment]
I think the old What's New feed was MUCH better

**Comment by blshkv** [comment]
This should be trivial to fix. Could you increase a priority for this issue? It is very basic and yet useful feature which bugs so many users.

**Comment by okan35** [comment]
If noone is doing this, I would like to start with addio pull to refresh and later auto refresh. @Stypox

**Comment by Stypox** [comment]
@okan35 nobody is planning to do it, so you can go for it. Thank you! :-D

**Comment by okan35** [comment]
I was going to open another issue but since the title starts with "Improve what's new experience" I didn't open another one. I think that we don't need to see how many videos are loading from how many channels on main screen.

This prevents user from checking content while new videos are loading and this can take a while depending on subscribed channel number.

Instead of showing loading videos' number on the screen, we can just keep the notification for that and let user to see the videos, check channels etc while new videos are fetched and if user wants to see what is going on, we have notification for that.

**Comment by Rult** [comment]
Does #4893 add auto refresh feature? If not then I think this issue should stay open.

**Comment by opusforlife2** [comment]
@Rult You could open a new issue. It's better that a single issue focuses on one, and only one, feature.
