### ISSUE TITLE
Download doesn't work sometimes

### ISSUE THREAD

**Issue by Paviluf** [TeamNewPipe/NewPipe#333]
Download doesn't work sometimes. Here is a [Logcat.txt](https://github.com/theScrabi/NewPipe/files/367855/2016-07-17-15-23-55.txt).

**Comment by satiricon** [comment]
I'll look at it... thanks.

**Comment by theScrabi** [comment]
Please try it with the upcomming version 0.8.5 is it still occuring?

**Comment by Paviluf** [comment]
It seem to work well now. Thanks !
