### ISSUE TITLE
[Question] Why using m.youtube.com to load comments?

### ISSUE THREAD

**Issue by C0D3D3V** [TeamNewPipe/NewPipe#3331]
Is there a reason why m.youtube.com is used to load comments instead of youtube.com?  When I add m.youtube.com to the host list with Adaway I don't see any comments anymore.

**Comment by wb9688** [comment]
That's because that was much easier to implement back when we were still parsing YouTube's old site. I'm going to work on the comments soon, including changing this

**Comment by C0D3D3V** [comment]
Thank you very much :)
