### ISSUE TITLE
Block nonessential domains loaded

### ISSUE THREAD

**Issue by Gordalf** [TeamNewPipe/NewPipe#3341]
#### Is your feature request related to a problem? Please describe it
Nonessential Google domains loaded

#### Describe the solution you'd like
Block all 1e100.net

When Newpipe is used many connections to 1e100.net are created. If the user blocks them via the hosts file Newpipe still works 100%

#### Additional context
Example: ams16s29-in-f54.1e100.net

#### How will you/everyone benefit from this feature?
Added privacy

**Comment by opusforlife2** [comment]
DEVS.

**Comment by wb9688** [comment]
@Gordalf: How do you know that those domains are loaded?

**Comment by Gordalf** [comment]
I looked at my DNS requests, but it seems like it has been fixed. I do not see any requests being made to 1e100.net anymore using Newpipe. 

Thanks for the awesome app btw.
