### ISSUE TITLE
Add addiction free mode

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#3343]
Can you add a mode in which only bookmark playlist and whats new feed are accesible. Even search should be disabled. Will help me a lot.

**Comment by opusforlife2** [comment]
Wow. You swing from one extreme to another. From wanting Pornhub to wanting an addiction free mode. :P

**Comment by Stypox** [comment]
Bounty of $30 by @sulyniv in #2319

**Comment by 07416** [comment]
> 
> 
> Bounty of $30 by @sulyniv in #2319

This ticket is not the same as the feature suggested.

 I only want to disable the 'trending' menu option.

**Comment by Stypox** [comment]
Closing in favour of #4081
