### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by Siorr** [TeamNewPipe/NewPipe#3346]
I've been having issues with videos loading I thought it was my WiFi or mobile data but I think that it is within the app like the video will take a while to load or not even load at all.

**Comment by opusforlife2** [comment]
Use the template. It is there for a reason. Open New Issue, copy the bug report template from there, paste it in this comment, and fill it out.

**Comment by gkeegan** [comment]
Change quality to 720p. Does it load better now?

**Comment by Stypox** [comment]
Duplicate of #2415
