### ISSUE TITLE
What to have khmer language😭

### ISSUE THREAD

**Issue by Visophea** [TeamNewPipe/NewPipe#3351]
Can put Khmer language in this app or anything I can help?

**Comment by Visophea** [comment]
> Can put Khmer language in this app or anything I can help?

**Comment by Visophea** [comment]
> Can put Khmer language in this app or anything I can help?

**Comment by Visophea** [comment]
> Can put Khmer language in this app or anything I can help?

**Comment by gkeegan** [comment]
Please stop closing and reopening...

Translations happen in weblate. I'm not sure if you can add a new language without a permission, but once it is there you can translate by going to https://hosted.weblate.org/projects/newpipe/strings/#translations and logging in with your GitHub account.

**Comment by Visophea** [comment]
I don't want to do that I'm trying to delete this  comment but how?

នៅ​ថ្ងៃទី សៅរ៍ 4 ម.ស 2020, 5:07 AM Keegan <notifications@github.com>
បាន​សរសេរ​ថា៖

**Comment by Stypox** [comment]
@Visophea you can't delete issues, you can only close them

**Comment by Visophea** [comment]
Ok I got it but I really want Khmer language in the app but in translate
project I can't Khmer language even when i start a new project i still
couldn't find it! Help me!!

នៅ​ថ្ងៃទី សៅរ៍ 4 ម.ស 2020, 1:07 PM Stypox <notifications@github.com>
បាន​សរសេរ​ថា៖

**Comment by Stypox** [comment]
Oh then you shouldn't neither delete nor the issue ;-)

**Comment by wb9688** [comment]
Someone with access to Weblate has to enable these languages or someone needs to create an empty strings.xml in this repository and then wait for a merge by Weblate.

After that, you could just translate it on Weblate.

**Comment by B0pol** [comment]
> > Someone with access to Weblate has to enable these languages or someone needs to create an empty strings.xml in this repository and then wait for a merge by Weblate.
> 
> After that, you could just translate it on Weblate.

It's false, you can just add a language on weblate.
Just [select your language here](https://hosted.weblate.org/new-lang/newpipe/strings/) and then translate it.
That's how tchouvache (cv) was added, I tried with a random language.

Though for a good newpipe implementation, you'll need to add [your language here]( https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values/settings_keys.xml#L1028) and its [language code here](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values/settings_keys.xml#L963) **in alphabetical order**.
By doing this the language will be selectable by user not having this language as system language. But this doesn't require any weblate rights, just a PR.

For the language code, most of them are given by weblate, when you go on a language and look at the url, there is written /project/newpipe/strings/**language code**,  for example there would be **en** for english.

IMO one should make the pr for adding a language to the selector when it's already translated in a good part. So @Visophea good luck with weblate and translating, I've given useful links above (how to add your language).


<sup>I will add this explaination somewhere in contributions guidelines and/or somewhere else</sup>

**Comment by TobiGr** [comment]
> I will add this explaination somewhere in contributions guidelines and/or somewhere else

@B0pol I think the wiki is a good place for this

**Comment by B0pol** [comment]
> > I will add this explaination somewhere in contributions guidelines and/or somewhere else
> 
> @B0pol I think the wiki is a good place for this

I just created [How to add a new language to NewPipe — Wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/How-to-add-a-new-language-to-NewPipe). Anyway, I'll update contributing file because there are a lot of outdated things, and I'll link this wiki page.

**Comment by B0pol** [comment]
I'm closing this since I gave the steps to add the language.
