### ISSUE TITLE
missing videos in feed group 

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#3354]
### Version

- 19.2

### Steps to reproduce the bug

![Screenshot_20200404-060920](https://user-images.githubusercontent.com/63132171/78417459-dad82300-763a-11ea-97bb-db24dd83ec12.png)

Go to a feed group that has old channels
### Expected behavior
Tell us what you expected to happen.
see new videos from those channels
### Actual behaviour
Tell us what happens instead.
missing videos from those channels or a completely empty group
### Screenshots/Screen records
If applicable, add screenshots or a screen recording to help explain your problem. GitHub should support uploading them directly in the issue field. If your file is too big, feel free to paste a link from an image/video hoster here instead.

### Logs
If your bug includes a crash, please head over to the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/). Copy the result. Paste it here:

**Comment by gkeegan** [comment]
Does pressing the "oldest subscription update" at the top do anything?

Also, can we have a link to one of these channels in this feed?

---

On a side note to the team, I really think the template is way too much and is too confusing to understand. I haven't seen many issues properly use it yet compared to the many that haven't.

**Comment by MD77MD** [comment]
pressing on the updated feed bar does nothing...
an example could be a channel could "recode"
https://www.youtube.com/channel/UCMDxbhGcsE7EnknxPEzC_Iw

put it in a group and you'll have the same issue

I'm not sure, but i noticed that all missing feeds are videos older then a month.. if this is the case, what would be the best approach to tackle this issue

**Comment by Stypox** [comment]
That's normal if you activate fast mode afaik, because youtube xml feeds do not contain old videos

**Comment by opusforlife2** [comment]
> On a side note to the team, I really think the template is way too much and is too confusing to understand. I haven't seen many issues properly use it yet compared to the many that haven't.

I'll try to improve it.

**Comment by MD77MD** [comment]
perhaps the solution suggested in issue #3315 switching between new Ui and old Ui could be a great workaround to start from.

3315
> although the new feed UI has been a long awaited feature.. old feed UI definitely had its uses... combining both would be really awesome
> I would suggest to add swipe left and right (like the one used between comments and related videos) to switch between two panels
> -the first panel is used for listing feeds by upload time (new feed UI)
> -the second panel will show latest video from each channel (old feed UI).. i would also like the ability added to go to any channel from here directly.. maybe by adding channel icon next to its related video or by an option in video menu.
> 
> if the swiping solution is not easy.. maybe a tab next to feed refresh bar would do the trick... or maybe make to tabs above the feed refresh bar, one called (new videos) and another called (channels).
> 
> also maybe you can make it an option to have it in settings... same as comments

**Comment by opusforlife2** [comment]
> That's normal if you activate fast mode afaik, because youtube xml feeds do not contain old videos

So closing, then.

**Comment by MD77MD** [comment]
![Screenshot_20201011-043522](https://user-images.githubusercontent.com/63132171/95668343-60ed9d00-0b7b-11eb-858e-14b91894638e.jpg)

@opusforlife2 
problem is still there and no, i am not using fast mode for loading feeds.

**Comment by opusforlife2** [comment]
Oh.

**Comment by MD77MD** [comment]
not anymore 

> Is this still an issue on the latest version 0.27.2?
