### ISSUE TITLE
Disable or remove "Lock screen video thumbnail" on KitKat

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#3355]
### Version

- 0.19.0

### Steps to reproduce the bug

1. Get a device or emulator running KitKat or below
2. Go to settings > video & audio. 
3. See that `Lock screen video thumbnail` setting is enabled by default
4. Play a stream using the background player
5. Lock screen

### Expected behavior
See stream thumbnail on lockscreen

### Actual behaviour
No thumbnail on lock screen

### Solution / Fix
This feature is only available for Lollipop and later. The setting should be either disabled or not visible on unsupported devices.

### Related tickets
#2690

**Comment by Stypox** [comment]
Closed by #3178
