### ISSUE TITLE
occasionally noisy sound

### ISSUE THREAD

**Issue by Rominet13** [TeamNewPipe/NewPipe#3359]
Hi
First, your app is wonderful ! I used it a lot to listen to music.
Since around 3 versions back, I noticed a lot of noise, which is making me not using the app. I first hoped that it would be solved in the following updates, but it isn't the case.
Can you please solved this issue ?
I use a Nokia 8.1 with android 10, I don't have any other sound issue (VLC, YouTube, YouTube music, web browser etc).

**Comment by TobiGr** [comment]
We should let the user choose the audio quality like we allow choosing video resolutions.

**Comment by wb9688** [comment]
Could you tell me since what exact version this happens?

I don't think it could be ExoPlayer-related, for example we haven't updated ExoPlayer for 2(!) years.

**Comment by Rominet13** [comment]
Exactly @TobiGr !! Because sometimes the quality is correct, and sometimes it is horrible.
I have noticed it for 2 months max, ~3 releases before.
Thanks for the quick reply.

**Comment by Rominet13** [comment]
Is the sound quality linked to the video quality ?! Because I set the video quality to minimum since I only use background music !

**Comment by wb9688** [comment]
@Rominet13: No, except when you're watching the video in certain resolutions. What have you set in Settings -> Video & audio -> Default audio format? And could you link a stream where the quality is horrible?

**Comment by Rominet13** [comment]
WebM but I have seen the difference with M4A.
But if I set the video quality to 144p, does it lower the sound quality ?

**Comment by wb9688** [comment]
@Rominet13: Only if you watch the video, not when you listen in the background. But still, could you link a video where the sound quality is horrible?

**Comment by Rominet13** [comment]
You want the music on YouTube ?  I have the problem on every but not all the time. Maybe it is linked to a poor Network.

**Comment by wb9688** [comment]
@Rominet13: Oh, I thought you meant some videos have the poor quality and some don't. This is strange…

**Comment by Rominet13** [comment]
Yes, this is strange. I will try to record it next time it happens (don't loose too much time on this). I l surprised I m the only one to have this issue.
Thanks for the support.

**Comment by opusforlife2** [comment]
Drop a comment whenever you are able to reproduce.
