### ISSUE TITLE
Lyrics search support

### ISSUE THREAD

**Issue by hbarylskyi** [TeamNewPipe/NewPipe#336]
Hi. I'd like to add a feature which would allow a user to see lyrics of songs (if user is watching a music video). 

That's how I see it working:
While watching a video, user would click a button. My code would parse the title of the video, look for lyrics in online databases and, in case something was found, a partially transparent box of text with lyrics would show up on the screen. User would be able to scroll the text and close the box.

What do you think about this feature? Any thoughts, suggestions?

As far as I understand, Exoplayer is coming to replace the old videoplayer. So should i try adding this "lyrics" button to Exoplayer?
Any suggestions on where/how should I add this button?

P.S. Maybe I would also be able to add subtitles support in similar way (issue #55)

**Comment by theScrabi** [comment]
Well feel free to try it. But that thing with subtitles I would forget until we have exoplayer.

**Comment by EmanuelLoos** [comment]
QuickLyric is also GPLv3, available on F-Droid and supports a few different Lyrics Platforms which means it's code could be used in NewPipe.

However it doesn't seem to be completely GPLv3-or-later, so it might be good to check that back before using its code to keep NewPipe compatible with newer GPL licenses. (I checked one file which was GPLv3-or-later licensed)

Even though you could implement its code I think it might also be a good way to keep Lyrics a separate option:
- QuickLyric seems to have some GPLv3-only parts which could cause problems whenever a GPLv4 comes out.
- Extra apps for extra functionality would enable NewPipe to stay lightweight to still run on older devices (storage, performance)

I actually used QuickLyric with NewPipe before, however there are some errors (mostly at YT(-Music)'s tagging and NewPipe's extraction of it) which could be fixed:
- "Auto generated by YouTube" on YT Music
  - YouTube adds " - Topic" to the YT channel if the artist doesn't have a YT channel, when playing in background NewPipe presents the YT channel's name as the artist's name and QuickLyric won't find Lyrics for a song by "Any Name - Topic"
  - If the artist does have a YouTube channel which's name differs from the real artists name QuickLyric also won't find lyrics
    *** How to fix: This issue can easily be fixed by using the artist's name provided by YT Music (instead of the channel's name provided by YT) as the YT Music search function already does.**

If you like you could also implement an API into QuickLyric and NewPipe to show them directly (and more smooth) in NewPipe.
