### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ondernuray** [TeamNewPipe/NewPipe#3360]
1) Play all button in custom feeds
2) Download all button like podcast > to able to set time range, format audio or video, bitrate by default for offline listening automatically for custom created youtube feeds

Please see screenshot for example > https://photos.app.goo.gl/sQDyCf71n34wZYet7

3) Zoom in / Zoom out while watching videos. It is useful while learning programming languaes on Youtube via small screen mobile phone.

Thanks
Onder

**Comment by ondernuray** [comment]
1) Play all button in custom feeds > to be able to listen all of them in order in the background as a audio.

**Comment by Stypox** [comment]
Could you open a different issue for each? (but not the third one, which is a duplicate)
