### ISSUE TITLE
Feature Request: Download all button like podcasts in custom youtube feeds

### ISSUE THREAD

**Issue by ndr48291** [TeamNewPipe/NewPipe#3363]
1) Download all button like podcasts in custom youtube feeds above the menu on the right > to able to set time range, audio or video type, bitrate and codec selection by default for offline listening automatically

Please see screenshot for example > https://photos.app.goo.gl/sQDyCf71n34wZYet7

Thanks
Onder

**Comment by Stypox** [comment]
Could you provide some feedback in #2583? This will be implemented at some point ;-)

**Comment by Stypox** [comment]
Closing in favour of #2380
