### ISSUE TITLE
Feature Request: Android TV support

### ISSUE THREAD

**Issue by ondernuray** [TeamNewPipe/NewPipe#3365]
I am volunteer to be a test user on Android TV. I can test, debug and send report / logs to you

I have Philips 55PUS6501/12 Android smart tv
version 8.0.0
security update: 01.09.2019
kernel: 3.10.79 build_ci@inblrlx046 #1
platform: OPR5.170623.014 release-keys

Thanks
Onder

**Comment by Stypox** [comment]
Great, thank you! :-D
Go take a look at #2806, that pull request will add Android TV support, hopefully in the next version

**Comment by Stypox** [comment]
Closed by #2806 which will be in 0.19.3 :-D
