### ISSUE TITLE
error: Cannot find getter for field.     private long id;

### ISSUE THREAD

**Issue by akindemiroz** [TeamNewPipe/NewPipe#3366]
![error-newpipe](https://user-images.githubusercontent.com/62177224/78463202-c51e3880-76e2-11ea-8d00-758f0371b314.jpg)

e: C:\Users\3Nokta\Desktop\NewPipe-yeni\NewPipe-0.19.2\app\src\main\java\org\schabi\newpipe\database\history\model\SearchHistoryEntry.java:25: error: Cannot find getter for field.
    private long id;
                 ^

How we can solve this problem?

**Comment by Stypox** [comment]
What are you trying to build? The dev branch?

**Comment by akindemiroz** [comment]
I opened the application in android studio I want to use without any changes. he made a mistake like this

**Comment by wb9688** [comment]
Are you using Java 8? If not, try that.

**Comment by akindemiroz** [comment]
When I say java 8 I did not know where the java version is

Sorry, I have no code information

:(

**Comment by akindemiroz** [comment]
If you are talking about JDK, I installed the latest version

**Comment by Stypox** [comment]
Try to install the jdk 8, as Android does not support the latest one

**Comment by opusforlife2** [comment]
We can reopen whenever there is a reply.
