### ISSUE TITLE
A button to show only "ungrouped" channels in "select subscriptions"

### ISSUE THREAD

**Issue by juanfra684** [TeamNewPipe/NewPipe#3377]
#### Describe the feature you want

Many thanks for the new feature for organize the subscriptions!

At this moment I have ~270 subscriptions. The new feature is really useful but not enough to work with so many subscriptions. I will try to explain what's missing with an example.

I've a lot of subscriptions to channels about electronics. I would like to organize them in various groups, e.g. "Electronics-01", "Electronics-02", "Electronics-03", etc. I start with my favorites in the 01 group, and then filling the other groups with other channels. The problem is that I can't remember what channels are already in a different group.

So, my request is adding a button (or whatever you want) in the "select subscriptions" view to hide the channels which are already in other groups. Something like "show only ungrouped channels".

#### Is your feature request related to a problem? Please describe it

No.

#### How will you/everyone benefit from this feature?

It will help to users with a lot of subscriptions.

**Comment by denemier** [comment]
**NO don't**, i am using a channel related to multiple feeds.

I have local news channels in multiple feeds like
-news worldwide (includes local german channels)
-news only germany

but i am not against a button to filter it live for other users like you, but i need this way.
