### ISSUE TITLE
Post-processing Failed on Video Download

### ISSUE THREAD

**Issue by rlister-gh** [TeamNewPipe/NewPipe#3379]
- 0.19.1

### Steps to reproduce the bug
Try to download
https://www.youtube.com/watch?v=tiJ2u3H94w0
At 1080p-60

### Expected behavior
The video to download
### Actual behaviour
The post-processing threw an array index out of bounds exception
### Screenshots/Screen records
![image](https://user-images.githubusercontent.com/62563431/78555648-63a2ba80-7805-11ea-8384-e9acafea5316.png)

**Comment by wb9688** [comment]
Already fixed in v0.19.2, please upgrade.

**Comment by rlister-gh** [comment]
Hi wb, I am using F-droid to manage this app and it says it is up to date at 0.19.1 ("Updated 5 days go")
Do you know if I can do anything to get 0.19.2 other than wait?
