### ISSUE TITLE
Android 4.0.3 support?

### ISSUE THREAD

**Issue by malekairmaroc7** [TeamNewPipe/NewPipe#3380]
Hello!

Can you add an Android 4.0.3 and up support? My Android Box has Android 4.0.3 but YouTube is horrible on it so that NewPipe is the last hope.

Thank you!

**Comment by B0pol** [comment]
No, it won't be supported.
The support for Android 4.X (except 4.4 which is still supported ay NewPipe) has been dropped to [NewPipe legacy (F-Droid)](https://f-droid.org/app/org.schabi.newpipelegacy) | [GitHub](https://github.com/TeamNewPipe/NewPipe-legacy).
