### ISSUE TITLE
Broken title in drawer

### ISSUE THREAD

**Issue by vladislav805** [TeamNewPipe/NewPipe#3381]
### Version

- 0.19.2

### Steps to reproduce the bug

1. Open drawer menu

### Expected behavior

Normal logo.

### Actual behaviour

Broken logo as
```
NewPip
e
```

### Screenshots/Screen recordings

![Screenshot_20200407-004109](https://user-images.githubusercontent.com/10882576/78608300-54555880-7869-11ea-839f-ea110d3d2cab.png)

### Logs

none

### Phone info
Xiaomi Mi A1, Android 7.1.2 AOSP
! Installed custom font from further version of Android — Google font !

**Comment by Stypox** [comment]
Ping @mauriciocolli

**Comment by mauriciocolli** [comment]
@vladislav805 it should be fixed in #3412, can you test it?

Try to switch between the app names (as described there) and tell me if any is not positioned correctly.

**Comment by vladislav805** [comment]
Yes, tested, fixed.

![Screenshot_20200410-173511](https://user-images.githubusercontent.com/10882576/78998707-d4254080-7b51-11ea-8270-265ab43b4013.png)
![Screenshot_20200410-173513](https://user-images.githubusercontent.com/10882576/78998709-d7b8c780-7b51-11ea-8d35-5d5f6ef4d379.png)
![Screenshot_20200410-173516](https://user-images.githubusercontent.com/10882576/78998716-dab3b800-7b51-11ea-81b3-56b8e5b3465a.png)
