### ISSUE TITLE
Bug-Report via Email not working anymore properly

### ISSUE THREAD

**Issue by gloschtla** [TeamNewPipe/NewPipe#3383]
After "Guru Meditation" I am offered by NewPipe to send the bug-report to the developer via email. After accepting the privacy policy, I press on the "send" button, which opens my email client with the address to the developer. But what I see in the latest version: The email is empty. The content of the bug report is neither attached, nor written into the text field. Also the email Subject is empty.

**Comment by wb9688** [comment]
Please use the issue template.

I could confirm that it doesn't work with NewPipe v0.19.2 and Gmail, but it works with Outlook. I haven't tested older versions of NewPipe or other e-mail clients.
