### ISSUE TITLE
Can't open or subscribe to channels from other regions

### ISSUE THREAD

**Issue by SHGuy1** [TeamNewPipe/NewPipe#3387]
### Steps to reproduce the bug

1. Open Adult Swim
2. Try to open both, the UK channel and the Deutschland (germany) channel

### Expected behavior

should be able to subscribe to both or at least view both
### Actual behaviour
Clicking on adult swim (regular) forwards to adult swim deutschland (germany)

**Comment by Stypox** [comment]
I can't reproduce. By doing a channel-only search with "Adult Swim" I get both "Adult Swim" and "Adult Swim Deutschland", and both of them redirect to their corresponding channel

**Comment by PeterHindes** [comment]
I believe this is on YouTube side so it may be impossible to prevent the redirection. newpipe doesn't forward any of your requests through a proxy so YouTube will do what it does with a regular request as if you loaded the webpage on your computer.

**Comment by SHGuy1** [comment]
Thought of the same reason. This happens on my pc with regular youtube as well.
It is solved by changing the region settings, although doing that in newpipe didn't do anything

**Comment by opusforlife2** [comment]
So... close?
