### ISSUE TITLE
Thumbnail for Downloads

### ISSUE THREAD

**Issue by oiiiiiiii** [TeamNewPipe/NewPipe#3389]
If you could see the thumbnails of the downloaded videos, it would be much easier to identify them. Sometimes, when downloaded many videos it takes some time to find out which is which.

**Comment by opusforlife2** [comment]
@wb9688 This would also pair _extremely_ well with the Youtube Music PR #3240.

**Comment by wb9688** [comment]
This is only possible to do after we've thrown out GigaGet, see #962. That won't be for some time though.

<sup><i>Well, technically it's possible to do that before throwing out GigaCrap, but that's not worth it.</i></sup>

**Comment by opusforlife2** [comment]
Well, I gave a suggestion there that got no reply. https://github.com/TeamNewPipe/NewPipe/issues/962#issuecomment-513747036 Is this something that could help?

**Comment by opusforlife2** [comment]
Actually, is it possible to download the thumbnail separately, just like the subtitle file?

**Comment by wb9688** [comment]
@opusforlife2: Nah, we should just write our own thing using OkHttp (through our `DownloaderImpl`), RxJava, and Room.

**Comment by opusforlife2** [comment]
Ohkay. And what about downloading separately?

**Comment by Stypox** [comment]
#1014
