### ISSUE TITLE
Force indexing new downloaded files

### ISSUE THREAD

**Issue by Magissia** [TeamNewPipe/NewPipe#340]
Hello, when downloading a video, the video is not automatically indexed by the media provider as soon as the download is finished, it would be useful to force index the newly downloaded file.

**Comment by theScrabi** [comment]
Can you tell me how to do that?

**Comment by wb9688** [comment]
For music, it can be done with the following code:

scanner=new MediaScannerConnection(getApplicationContext(),
            new MediaScannerConnectionClient() {

      public void onScanCompleted(String path, Uri uri) {
              scanner.disconnect();
      }

      public void onMediaScannerConnected() {
              scanner.scanFile(path, "audio/*");
      }
  });

  scanner.connect();
