### ISSUE TITLE
The player controls don't hide when using external controls

### ISSUE THREAD

**Issue by Poomex** [TeamNewPipe/NewPipe#3403]
### Version

0.19.2

### Steps to reproduce the bug

1. Play video with a bluetooth speaker connected
2. Press "pause" on the bluetooth speaker
3. Press "play" on the bluetooth speaker
4. The video starts playing again

### Expected behavior

The player controls should hide after a few seconds
### Actual behaviour

The player controls remain on screen and disappear only when it is tapped. This means that the play/pause controls on the bluetooth speaker become useless.

**Comment by B0pol** [comment]
I can reproduce with my remote & Android TV

**Comment by Generator** [comment]
I can confirm that on v0.19.3. 
Tested on an Android TV Box and Phone.

Same issue, when used media keys the screen controls stay on screen till send cursor 'click', also pressing on play icon on screen controls, they don't hide.

### How to reproduce 
* With any keyboard with media keys or Air Mouse connect thought USB OTG or device standard USB (USB Type-A).

* Press 'pause key' to pause and resume.

**Comment by Stypox** [comment]
Please test the apk provided in #3537

**Comment by Generator** [comment]
Done a quick test of #3537. 
Pressing 'Play' icon now hides screen controls.
Pressing 'pause/resume' key on the remote, controls don't hide.

**Comment by Stypox** [comment]
> Pressing 'pause/resume' key on the remote, controls don't hide.

I don't understand if this is considered bad behaviour or not ;-)

**Comment by B0pol** [comment]
On my remote play / pause / next / previous buttons are used for background player, then it's really useful until #3515 is fixed.

**Comment by PetbkA** [comment]
**0.20** - same with Mi Band 2: play controls doesn't disappear after resume until I tap on the _Play_ button

**Comment by cbiere** [comment]
0.20.1 on Xiaomi Mi A1: I can reproduce this with a wired headset (3.5 mm audio jack) that features a pause/play button. May be related: Newpipe doesn't resume playing after replugging the headset unlike AntennaPod which resume instantaneously.

**Comment by Poomex** [comment]
Unfortunately still not fixed as of 0.21.15
