### ISSUE TITLE
Default speed setting

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#3405]
#### Describe the feature you want
Can you make default speed setting like default resolution in video & audio page. 

#### Additional context
![Screenshot_20200409_173436](https://user-images.githubusercontent.com/11852634/78920131-3703d280-7a93-11ea-83a1-4d8edf7b1159.jpg)

#### How will you/everyone benefit from this feature?
I'm used to watching videos with 1.25s so it's painful to do this for each video, YouTube application records speed settings.

**Comment by Stypox** [comment]
Closed by #3288
