### ISSUE TITLE
[UI] Share button does not work for future-planned live videos

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3407]
While the video is not yet available such as in this channel (they always have live events planned) the share button seems to not react. 

https://www.youtube.com/watch?v=b8g1o8Ph7LQ 

![Screenshot_20200410-012728_NewPipe](https://user-images.githubusercontent.com/415238/78946281-fde75480-7aca-11ea-8727-2f24073e7750.jpg)

also (might worth opening a feature request?) there probably is a better way presenting an unavailable content information, for example when the live event will start, this is better than showing 'content unavailable' message.

**Comment by TheAssassin** [comment]
You seem to have blocked Team NewPipe. Therefore, we will close this issue now. If you unblock us, we can reopen the issue.
