### ISSUE TITLE
I can't play anything due to unsuccesful decrypting of video url signature

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#341]
Since today I can't watch anything. I can search, thumbnails do load, but when I click on some result, it just doesn't load up anything.

Gives me 'could not decrypt video url signature'.

**Comment by satiricon** [comment]
I can't confirm, it's working perfectly for me. @pigeon7i can you paste a stack trace?

**Comment by pigeon7i** [comment]
I won't, because now it works. Later, if it'll happen once more, I definitely will.

**Comment by theScrabi** [comment]
I happen to notice that you sometimes have to refresh the page (go back and open again), in order to actually load the video info correctly.

**Comment by timofonic** [comment]
What about this and lots other opened issues? The issue tracker seems saturated!

**Comment by theScrabi** [comment]
Have mercy I have a life outside of the computer. Also since I don't get payed for what I do, I can decide when and where I do what.

If you don't like it why don't YOU try to fix all that crap? That would be better than frequently complaining about everything.

**Comment by Ravenstine** [comment]
This has started happening with me on 0.8.6.  Upgraded to 0.8.8 and the problem persists.  Not a single video will play now.  I've tried different wifi networks and my 4G LTE.  I'm on Android 6.0.1.

**Comment by AJtranscita** [comment]
I believe Google/YouTube changed their code recently.  As soon as NewPipe implements the changes, everything should be back to normal.

**Comment by Spielmops** [comment]
I can't play anything due to "unsuccessful decrypting of video URL signature" too - as of today. Yesterday everything was OK, but today not. I tried it with 3 different devices and the Newpipe-versions 0.8.5, 0.8.6 and 0.8.8. Then tried to view with Skytube with the same result and naturally the same error-message. It seems, that Youtube changed something.

Spielmops

**Comment by theScrabi** [comment]
Fix went out a couple of hours ago.

**Comment by Spielmops** [comment]
Whow, that's fast! Thank's a lot!

Spielmops
