### ISSUE TITLE
Create a Tor friendly app, please

### ISSUE THREAD

**Issue by jniniinoinoino** [TeamNewPipe/NewPipe#3418]
# Describe the feature you want
A clear description would be. Please dear NewPipe Team, I was wondering if you could make the current NewPipe app able to handle the Tor Network better/friendlier. What I want, is for NewPipe to work with the Tor Network as in "flawless execution".

I was hoping for you guys to make it so whenever I change Tor Identity it refreshes the app, internally. Not so much as it restarts the app, but allows me to clear the network cache. So I can get right back into browsing. Meaning I still want to be able to load a video,  and whenever it fails, I press change Tor Identity and I continue browsing right away.

# Is your feature request related to a problem? Please describe it
Whenever I use Tor, I get reCAPTCHAs every ~5 minutes. A very annoying procedure to fix as I have to reQuit the app, both the background player and the app itself. Change Tor Identity, and reOpen the app. Sometimes multiple times before it works. And then refind the video I watched, or research the thing I was searching for.

# How will you/everyone benefit from this feature?
As Google works to fingerprint our lives, Tor is the only thing that is free to use and heavily protects users. Not a thing we should take lightly. I remember when I watched NewPipe videos without Tor enabled. Later that day I opened the third-party official YouTube app(Vanced). With my Google account logged in. I got recommendations of the videos I had just watched on NewPipe. Which is NOT what I want. NewPipe is the private client I wish for it to be. But without the Tor network I will never be able to enjoy it fully. :'c 

I had always wished for NewPipe to be my #1 YouTube client and so I can ditch the official one. As the features gets merged, I really really want to switch over fully. But not as long as this annoying reCAPTCHA interrupts everything, everytime. Please dear NewPipe Team, make my life easier. I beg of you!

**Comment by Stypox** [comment]
I'm trying to fix recaptchas. Could you test the apk provided in #3414? I have already been informed of an issue when switching networks, but at least the first recaptcha should solve fine

**Comment by jniniinoinoino** [comment]
> but at least the first recaptcha should solve fine

I'm not really fond of completing recaptcha as its data collection to Google. But also the most important is that it takes minutes to complete one with the Tor network. Would prefer not doing them at all. And just changing networks as you told me, you are working with that I hope. Really glad to hear it :)

Should we continue the conversation here or #3414
