### ISSUE TITLE
Search suggestions

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#3419]
#### Describe the feature you want
Show search suggestions, i.e. "Did you mean: …".

#### Additional context
NewPipeExtractor already has the relevant code to extract it, but apparently that's never called in the app.

**Comment by B0pol** [comment]
It requires extractor changes. Currently, the provided method doesn't work for youtube or youtube music (and for other services it returns `null`)

**Comment by wb9688** [comment]
@B0pol: What's https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeSearchExtractor.java#L66 and https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeMusicSearchExtractor.java#L130 then? I'm pretty sure they both work.

**Comment by B0pol** [comment]
I found there are in fact two way to have suggestion. For example, test on youtube music "duo lipa", it will show you "dua lipa". If you try with Newpipe extractor and getSearchSuggestion, it will be empty.
