### ISSUE TITLE
I can't play anything

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#342]
Since today I can't watch anything. I can search, thumbnails do load, but when I click on some result, it just doesn't load up anything.

Gives me 'could not decrypt video url signature'.

**Comment by theScrabi** [comment]
Please try it with the latest version, and till me if it still happens.

**Comment by substanceof** [comment]
Same problem. 
0.8.7 worked well on cm13 (android 6), but recently i switched to lineage 14.1 (android 7.1.1) and newpipe has stopped working. Updating yo 0.8.8 isn't helps at all. I can provide any logs if they needed.

**Comment by theScrabi** [comment]
It is considered to be fixed.

**Comment by Johnstone-Tech** [comment]
I recieved the same error last week updated to 0.8.8 didnt seem to fix anything for me. Can provide more information if required.

**Comment by d-kr** [comment]
It was fixed in 0.8.9 for me.

**Comment by Johnstone-Tech** [comment]
Apologies i hadnt updated fdroid repos

**Comment by theScrabi** [comment]
No its ok It was not online until yesterday.
