### ISSUE TITLE
Add "System default" theme option.

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3420]
#### Describe the feature you want

I would like NewPipe theme to follow Android theme
#### Is your feature request related to a problem? Please describe it

If I change Android theme, it won't change NewPipe theme.
#### How will you/everyone benefit from this feature?

It will need less effort to change theme of my apps (apps without system theme option, including NewPipe).
It would also fix https://github.com/TeamNewPipe/NewPipe/issues/1535 for people who can set a system-wide theme settings (Correct me if I'm wrong, Android 10+ users, LineageOS 16 (and custom ROMs based on Lineage 16), and other custom ROMs implementing system-wide theme settings).

**Comment by xmha97** [comment]
+1

**Comment by opusforlife2** [comment]
@xmha97 To show agreement you give a thumbs up on the top comment, not add another comment.

**Comment by julian-fairfax** [comment]
I'm just dropping in to say that I would also greatly appreciate this feature being added, as it would improve the integration with the android system, and would thus be a welcome change for me. Thanks for all the work you've put into this wonderful app!

**Comment by LongJohn-Silver** [comment]
Will this be added or something or why was it closed, @Redirion ?

**Comment by Redirion** [comment]
Yes as PR #3632 added this option. It will be part of the next NewPipe version

**Comment by opusforlife2** [comment]
@LongJohn-Silver "X closed this in #abcd" means that issue was closed by a linked PR which fixes the bug/implements the feature request.

**Comment by LongJohn-Silver** [comment]
@opusforlife2 Sorry I am using a third party client which did not show all the details.
