### ISSUE TITLE
Simple request, bigger comment font size

### ISSUE THREAD

**Issue by raniesantos** [TeamNewPipe/NewPipe#3421]
Sorry for not following the format but this feature request is pretty much self-explanatory.

**Comment by gkeegan** [comment]
Changing the system font size does the job, but I agree that the size of comments is smaller than everything else. Making it bigger shouldn't require making everything else on the phone huge.

**Comment by Stypox** [comment]
The comment font size looks like to be equal to the one used in other places of the app (e.g. various info item descriptions)
