### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by samatzhusup** [TeamNewPipe/NewPipe#3426]
How i can Solve? 
I show this on run

![2020-04-13_12-37-23](https://user-images.githubusercontent.com/50781959/79098344-9871bd00-7d83-11ea-91da-0c2f4e2ff501.png)

**Comment by B0pol** [comment]
We are using checkstyle to ensure cove quality. You can check the [documentation of checkstyle](https://checkstyle.sourceforge.io/).

Here, you can see that there is one error: [LineLength] in file Mp4DashWriter, line 714, the line has too many characters (101, max is 100).
