### ISSUE TITLE
Built-in Audio conversion

### ISSUE THREAD

**Issue by killk4809** [TeamNewPipe/NewPipe#3427]
Not every phone can play opus audio files, some can't even play m4a audio files. So built-in Audio conversation would be much appreciated.

**Comment by mittorn** [comment]
install vlc

**Comment by PeterHindes** [comment]
There is a setting to choose your preferred codec. Real-time conversion would use too much battery.

**Comment by Stypox** [comment]
> Real-time conversion would use too much battery

That's would only be an issue for the user: here the real problem is that it would drastically increase apk size to include `ffmpeg`. Also, this is a duplicate of #507
