### ISSUE TITLE
this "thing" takes about 40 million centuries to open a video

### ISSUE THREAD

**Issue by DialexG91** [TeamNewPipe/NewPipe#3432]
How about deleting it and going to repeat the Android development course?

**Comment by gkeegan** [comment]
........ Let's not be rude. You pay nothing for NewPipe. You're free to use regular YouTube if you want to be toxic.

But to be helpful, the loading issue is known. Workaround:

1. Change defaults to 720p
2. Open a video
3. Once it starts playing, switch to 1080p, it should be loading much faster than when 1080p was default
4. Repeat 2 and 3 for each new video you watch
