### ISSUE TITLE
Shuffle all for playlists content

### ISSUE THREAD

**Issue by heretoenhance** [TeamNewPipe/NewPipe#3433]
#### Describe the feature you want

It would be nice to have a "shuffle all" for playlists content.

#### How will you/everyone benefit from this feature?

It would be really useful especially for music playlists, I really think any NewPipe user would like this feature.

**Comment by B0pol** [comment]
You can already do this:
1. Go on your playlist and hit "background"
2. Open notification and hit shuffle button, at the right of next track button.
