### ISSUE TITLE
Feed sorting inconsistent if multiple videos released at the same day

### ISSUE THREAD

**Issue by denilsonsa** [TeamNewPipe/NewPipe#3438]
### Version

- 0.19.2 (from F-droid)

### Steps to reproduce the bug

1. Subscribe to multiple channels. Even better if those channels publish multiple videos on the same day.
2. Go to *What's New* tab, tap the refresh button.
3. Observe carefully the order of the videos.
    * For this issue, you should have many videos listed as "2 days ago".
4. Go watch a video and come back. Or exit the app and come back.

### Expected behavior

The order should be the same.

### Actual behaviour

The order of the videos change each time I look at them.

I believe this happens because NewPipe parses "2 days ago" from scraping the page, and then multiple videos have the same age, so they all end up "equal" in the sort comparison. A workaround would be to add extra conditions (such as the channel name/id and the video id) for when the timestamp is the same. (Note: this is a guess, without looking at the source-code.)

**Comment by opusforlife2** [comment]
Does it matter, though?

**Comment by Stypox** [comment]
Yeah, I don't see why this would count, and there is obviously nothing that can be done to get more information from yt

**Comment by denilsonsa** [comment]
> there is obviously nothing that can be done to get more information from yt

But there is something that can be done to keep the sorting consistent:

> A workaround would be to add extra conditions (such as the channel name/id and the video id) for when the timestamp is the same.

In other words, sort by time, then (if time is equal), sort by video id. I'm not asking for the order be the real publication order; instead, just to be consistent.

Why does it matter? Because if the user looks at the list of videos, watches one, then comes back to watch another; it gets very confusing if the order changes each time. It improves the UX.

---

Still, it's been a while since I noticed this bug. I don't know if it still exists. I'm not familiar with Android development, so I'm sorry I won't contribute with any PR.
