### ISSUE TITLE
Responsive Title

### ISSUE THREAD

**Issue by dmoa** [TeamNewPipe/NewPipe#3442]
Using latest version of Newpipe.
![Screenshot_20200416-014107](https://user-images.githubusercontent.com/44374106/79402342-7ba3d800-7f83-11ea-9d41-bfc515b948e4.jpg)

Newpipe title is getting cut off as seen in the photo. This is very nit picky, but also very fixable.

**Comment by wb9688** [comment]
Already fixed by #3412
