### ISSUE TITLE
directly open the videos from mobile's notification screen which are suggested by youtube app

### ISSUE THREAD

**Issue by rithans** [TeamNewPipe/NewPipe#3443]
#### Describe the feature you want

new or suggested videos are notified in phone notification, when it clicked, it opens youtube app, instead opening youtube app, if it directly opens in newpipe then it will be very convenient, 

#### How will you/everyone benefit from this feature?

as it will save time from opening youtube link from notification which opens youtube app, then from there,  forward it again  to newpipe to watch it.

**Comment by Stypox** [comment]
I think this is not solvable, as a click on a YouTube notification obviously opens the video in youtube, and that can't be changed

**Comment by opusforlife2** [comment]
Also, invalid.
