### ISSUE TITLE
Incomplete requests, completed reCAPTCHA not persistent

### ISSUE THREAD

**Issue by asdf512** [TeamNewPipe/NewPipe#3446]
Newpipe 0.19.2
On successful completion of reCAPTCHA, selecting 'Done', user is taken to Newpipe main page. Newpipe does not continue with the request made before reCAPTCHA. reCAPTCHA is triggered again, immediately after previous reCAPTCHA when a new request is made.

**Comment by Stypox** [comment]
Take a look at #3414
