### ISSUE TITLE
Allow resume of download

### ISSUE THREAD

**Issue by z3ntu** [TeamNewPipe/NewPipe#345]
Hey,
I tried downloading a video but didn't finish the download (about 30% downloaded). When I tried to resume the download a few days later it said "Error" in the download (probably cause some link expired). It would be awesome to be able to resume the download but apparently it just overwrites the already-downloaded file with the new one.

Thanks.

**Comment by theScrabi** [comment]
Hm the problem with youtube is that links expire, so i cant help there.

**Comment by z3ntu** [comment]
But maybe it is possible to save the Youtube url and renew the link and resume the download.

**Comment by KaMyKaSii** [comment]
@theScrabi You still think the same? I am not a developer but the idea of ​​updating the link seems simple. I have a slow connection and it drops a lot and this feature would be extremely useful

**Comment by wb9688** [comment]
This could be implemented, but will probably be done after we get rid of GigaGet.

**Comment by theScrabi** [comment]
Yea most likely.
