### ISSUE TITLE
Can't some play videos at 720/ 480p 

### ISSUE THREAD

**Issue by Raul1198** [TeamNewPipe/NewPipe#3451]
### Version

- 19.2

### Steps to reproduce the bug

1. Go to 'https://youtu.be/7q12_f3UM9g'
2. Select the 480p Quality from either the Downoad or Play Option

### Expected behavior

the video should be playing in 480p

### Actual behaviour

the video isnt playing in 480p but im getting  black loading screen

### Screenshots/Screen recordings

![Screenshot_20200418-112707](https://user-images.githubusercontent.com/29801315/79629478-ca11cc00-8167-11ea-88d8-42ce5c9e14be.png)

**Comment by gkeegan** [comment]
**PLEASE** follow the issue template. Edit your issue and fill it in.

**Comment by Raul1198** [comment]
now is it ok

**Comment by Stypox** [comment]
Duplicate of #2415
