### ISSUE TITLE
Sound Cloud No longer Working

### ISSUE THREAD

**Issue by killk4809** [TeamNewPipe/NewPipe#3455]
![Screenshot_20200418-172622](https://user-images.githubusercontent.com/52140333/79671664-2beb2980-819a-11ea-8991-6268c521da95.jpg)
![Screenshot_20200418-172658__01](https://user-images.githubusercontent.com/52140333/79671670-30174700-819a-11ea-8e64-9ff1b7de7537.jpg)

Should have I done this via email?
Because I never get any update from that way.

**Comment by gkeegan** [comment]
It's fine to report here. Please edit your issue and follow this issue template, since otherwise it's hard to help you.

**Comment by Stypox** [comment]
Duplicate of TeamNewPipe/NewPipeExtractor#290
