### ISSUE TITLE
Back button when viewing downloads info takes back to home rather than downloads

### ISSUE THREAD

**Issue by twig** [TeamNewPipe/NewPipe#3457]
### Version

- v0.19.2

### Steps to reproduce the bug

* go to downloads list
* [show info](https://i.imgur.com/QZ624wm.jpg)
* [press either back or up button](https://i.imgur.com/pwXqx3Z.jpg)
* [where I end up](https://i.imgur.com/bC1YuNr.jpg)

### Expected behavior

Expected to end up back in downloads list

### Actual behaviour

ended up home page

**Comment by Stypox** [comment]
Duplicate of #2358
