### ISSUE TITLE
[feature request] copy video/playlist/channel link

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3461]
Would be great to have an easy way to copy the current URL of whatever I am viewing, 

currently, I'm "sharing" it to gmail and copying the text (it creates draft emails which I have to delete afterwards..)

YouTube has an entry in the "share menu" for copying the URL (it copies the short URL).

**Comment by B0pol** [comment]
We are using default android share menu. Normally you should have a clipboard option in this menu.
If not, install an app to share to clipboard (E.g.  [this app](https://f-droid.org/en/packages/com.tengu.sharetoclipboard/))
This isn't within our remit.

**Comment by eladkarako** [comment]
<img src="https://i.kym-cdn.com/entries/icons/original/000/032/668/Geralt_Hmm_Banner.jpg" />
