### ISSUE TITLE
Any hope of support on Android TV platform?

### ISSUE THREAD

**Issue by 3nkpem** [TeamNewPipe/NewPipe#3467]
#### Describe the feature you want

I am generally very pleased with Newpipe. I sincerely hope that someone would test it out on a decent Android TV platform (I have a MiBox4). 

I must point out that I am by no means a developer. 

#### Is your feature request related to a problem? Please describe it

The builtin player does not seem to be working properly. It insists on "portrait" aspect - not very appropriate for a TV screen. However, video shows the right direction, though in a narrow middle band, compressed.

Also, it would be nice if initial pointer position could be on the video play frame.

#### How will you/everyone benefit from this feature?

I hope many more people will see all possibilities with Android TV.

    Harald E,  Skien Norway

**Comment by wb9688** [comment]
Take a look at #2806
