### ISSUE TITLE
Timestamps are opened in Pop-up mode, even if i'm playing media with backround player.

### ISSUE THREAD

**Issue by allendema** [TeamNewPipe/NewPipe#3470]
### Version
19.2
-

### Steps to reproduce the bug
  
   1. Open any video.   Example: https://www.youtube.com/watch?v=RLWcYADoV84
      2. Play it with backround player.
      3. Click timestamps on description or comments.
    4.  Now even if you are playing it with backround player, it opens the timestamp on pop-up mode.

### Expected behavior

As you already have it playing with backround player, I expect to just open the timestamp with backround player, which means to just forward/backward it to the desired timestamp.

### Actual behaviour

After clicking the timestamp, it opens on Pop-up mode.

**Comment by Stypox** [comment]
Check out #2907

**Comment by allendema** [comment]
I will check it out.

**Comment by opusforlife2** [comment]
> Check out #2907

Didn't fix it.

**Comment by opusforlife2** [comment]
Closing in favour of #4241, as it must be a single solution for the unified player now.
