### ISSUE TITLE
Not able to see the length of the video before playing it.

### ISSUE THREAD

**Issue by somerandomcandy** [TeamNewPipe/NewPipe#3472]
0.19.2 Version

-

### Actual behaviour

![Screenshot_2020-04-23-00-48-45-47](https://user-images.githubusercontent.com/64163517/80024212-53285a80-84fc-11ea-806c-06a8859440fe.jpg)

like in  this screenshot length of only two videos is shown which are the ones which i have already seen

**Comment by jniniinoinoino** [comment]
+1 
Has been annoying when I don't know how long the video is. It does this to every video, watched or not watched.

**Comment by B0pol** [comment]
It's intended. Either you can use **fast mode**, or `feth from dedicated feed` which have some info missing (duration, live status), or you can use default mode, when `fetch from dedicated feed` is off.

To change to not fast mode (and vice-versa), go to Settings, Content, and disable `fetch from dedicated feed`. You'll see it's much slower if you have a lots of subscriptions, but some info are missing.

We wished we could have video length and live status too, but YouTube doesn't provide it :/

<sup><sub>We should write about that in [newpipe.net/faq](https://newpipe.net/faq)</sub></sup>

**Comment by somerandomcandy** [comment]
How much do you mean by a lot of subscription, you are talking qualitatively, like i have around 130 subs, is it a lot? or in what range will you count it?
