### ISSUE TITLE
no valid zip file when trying to import old setup

### ISSUE THREAD

**Issue by raginginril** [TeamNewPipe/NewPipe#3473]
### Version

- 0.19.2

### Steps to reproduce the bug
1. go to settings
2. import a previous new pipe set up
3. select the file from your phone

### Expected behavior

for me to have all of my music back so I can keep all of my play lists and my watch history
### Actual behaviour

I get told "no valid zip file" everytime I try to import the setup and my playlists stay the same

**Comment by Stypox** [comment]
What extension does the exported data have? Could you attach here the file, if that's not a problem?

**Comment by raginginril** [comment]
[NewPipeData-20200422_124142.zip](https://github.com/TeamNewPipe/NewPipe/files/4602506/NewPipeData-20200422_124142.zip)

**Comment by Stypox** [comment]
That file is only ~50 bytes, so I guess it does not contain any information. While it was exported it got corrupted. Maybe it is an issue in the app, maybe it is caused by the system interrupting the export operation halfway through, who knows. Do you remember what happened after you pressed the export button?

**Comment by wb9688** [comment]
@Stypox: I've once seen it generate a 0-byte .zip file. I'm pretty sure it said "Exported" at the bottom like usual.

**Comment by raginginril** [comment]
I tried to test if the export worked and imported it onto the same export, and it seemed like it worked perfectly (everything looked fine), so I uninstalled the app and installed a newer version.

**Comment by opusforlife2** [comment]
What to do here? This was a one time thing.

**Comment by Stypox** [comment]
Yeah, there is no way of reproducing this whatsoever
