### ISSUE TITLE
MX Player Force Close

### ISSUE THREAD

**Issue by zQueal** [TeamNewPipe/NewPipe#348]
Since about 2 days ago any video I attempt to play using MX Player (external video player) causes an immediate error.

![screenshot_20160813-222845](https://cloud.githubusercontent.com/assets/239193/17651264/2fc4ed98-6231-11e6-862e-ef4bfbeb41a0.png)

It persists with _any_ video. Nothing in the environment changed and I've tried older versions of MX Player all to no avail. Using the built in video viewer with NewPipe works fine.

Any guidance?

**Comment by theScrabi** [comment]
This seems weird. Sorry I can't help you. You may have to check logcat.
