### ISSUE TITLE
Automatic pause when playing 

### ISSUE THREAD

**Issue by vavavoum44** [TeamNewPipe/NewPipe#3481]
#### Is your feature request related to a problem? Please describe it

Good morning,
First of all thanks for tour work on NewPipe. The application is very good. 
I just have a problem and don't know where to Ask my question (sorry for Bad english, i am french) because I sée no forum concerning the app.

My problem is the following:
When I listen to music with NewPipe, even if I put it in background, when I do it at the same Time I play poker with the winam... android application (it is also the same with any application that usually automatically put youtube in pause when there is an action on it), every time there is an action on the poker  table (every 5 seconds :-)), the video is put in pause and I have to manualy put play even when I chose in NewPipe parameters the option "resume reading after interruption (ex: phone call"). 

I am pretty sure tour team thought about that an I missuse the app but how should I do?

Thanks you for tour work again
Regards,

Boris

**Comment by androidSwDev099** [comment]
If I have NewPipe playing in background player and
1. I make a phone call, NewPipe stops during phone call and resumes at end of phone call.
2. If I start another non-phone call app that starts producing audio, NewPipe will stop and won't automatically resume playing even if the non-phone call app stops producing audio or I quit that app.

So it seems that the "Resume playing" setting is only applies to resuming after interruptions caused by phone call apps and other audio producing apps like games, YouTube, audio/video players, news apps, etc.

**Comment by opusforlife2** [comment]
Now that every player spawns a notification, can the media session be made high priority to override or use volume ducking for interrupts?

**Comment by Stypox** [comment]
I don't know if this is a good idea, since implementing this would create issues for apps where instead it is expected that newpipe does not restart as soon as it can.

**Comment by opusforlife2** [comment]
@Stypox For example?

**Comment by Stypox** [comment]
For example starting another player (e.g. vlc) supposedly means the user is not interested in newpipe's one anymore, and also similar scenarios... I don't think there is a clear best option, certainly many times you'd want newpipe to restart after the interruption, but I'd prefer the current implementation as it is the least invasive

**Comment by opusforlife2** [comment]
But normally media apps handle these things fine. If your music player is playing, and you get a notification, the volume ducks for a moment. If you get a call, the player pauses, then resumes after it ends. If you start another media session like VLC, the player pauses and doesn't resume at all.

**Comment by Stypox** [comment]
Oh ok then, we should go with what you said:

> Now that every player spawns a notification, can the media session be made high priority to override or use volume ducking for interrupts?

**Comment by opusforlife2** [comment]
Same as #2681?
