### ISSUE TITLE
Video start in portrait mode even though the video is in landscape

### ISSUE THREAD

**Issue by ThomasLeigh** [TeamNewPipe/NewPipe#3485]
Hello,

I’ve just installed NewPipe v0.19.2 on SAVIO Smart TV Box TB-P01 (Android 7.1 Nougat), running on Samsung TV UE46ES5500WXXH. The thing is that I cannot force videos to be displayed on full screen - they are displayed in a very small size (I don’t mean a popup window - which also is small and I can’t enlarge it), even if permissions to display over the apps are granted.

**Comment by wb9688** [comment]
Could you test the RC of v0.19.3? It should have fixed a lot of Android TV related stuff

**Comment by ThomasLeigh** [comment]
Yeah, it could be fantastic! Where can I find it? Cannot see this ver. on GitHub release page.

**Comment by ThomasLeigh** [comment]
Oh, I see: https://github.com/TeamNewPipe/NewPipe/issues/3479 Haven’t known that such a ver. exists.

**Comment by wb9688** [comment]
#3479

**Comment by ThomasLeigh** [comment]
@wb9688  Unfortunately it didn’t help. :( The issue persists in my case. I’ve tried all the available picture adjustments while viewing a video (upper right icons), to no avail.

**Comment by wb9688** [comment]
Hmm… is "very small" about 32% of the screen (assuming your screen is 16:9 and your video is 16:9 as well)? If so, you probably have it in portrait mode instead of landscape mode. Could you try pressing the button to switch?

**Comment by ThomasLeigh** [comment]
> Could you try pressing the button to switch?

Thank You very much, **it works**!

I’m not sure should I create a separate thread for this, but there is one more thing: whenever I add a NewPipe icon to desktop icons (this particular smart tv has its own method for adding app icons to desktop), another icons shows up alongside the NewPipe’s: a yellow shield. Once I choose it it displays “Leaks in org.schabi.newpipe.debug”.

**Comment by Stypox** [comment]
@ThomasLeigh that's normal, as what you downloaded is a debug apk. When the new version will be released it won't exist ;-)

**Comment by TobiGr** [comment]
We should enforce landscape on TVs if the video is a landscape video otherwise use portrait.
That should be quite easy to do.

**Comment by B0pol** [comment]
Why this behavior only or TVs? I've never understood why videos are in portrait on fresh NewPipe installs, when most of the videos actually are landscape.

Btw https://github.com/TeamNewPipe/NewPipe/pull/2907 fixed it
