### ISSUE TITLE
YouTube video flagged as inappropriate crashes NewPipe

### ISSUE THREAD

**Issue by dariox86** [TeamNewPipe/NewPipe#349]
The video at [https://www.youtube.com/watch?v=bP7BWmZsbcQ](url) was flagged as inappropriate and it crashes NewPipe when launching it.

**Comment by theScrabi** [comment]
All right thanks.

**Comment by theScrabi** [comment]
@dariox86 although I'm glad that NewPipe crashes conserning that type of video ;)

**Comment by dariox86** [comment]
Eh eh. :) As of version 0.8.5, it still throws a guru meditation error. Is it normal?

**Comment by theScrabi** [comment]
No send that crash over to us I see what i can do.

**Comment by dariox86** [comment]
I have just sent the crash report through the application.

**Comment by theScrabi** [comment]
All right thanks
