### ISSUE TITLE
Allow user to specify a default download type (Video, Audio, or Captions, etc)

### ISSUE THREAD

**Issue by androidSwDev099** [TeamNewPipe/NewPipe#3490]
#### Describe the feature you want

Currently when a users wants to download contents of a video, the download type in the Download dialogue box always defaults to the Video radio button being selected.

I propose an enhancement that allows the user to specify the default download type radio button selection (the three types I'm aware of are Video, Audio, and Captions - are there others?).   

This could  be accomplished by:
1. Create a new "Default download type" setting option under Settings -> Download which lets the user specify default download type as Video, Audio, or Captions. 

or

2. The last download type the user selected in the download dialogue would be the default selected for the next download.  For example if the user downloads Audio for the current video selected, then the default download type would now be Audio so that the next time the user initiates a download for a video, the Audio radio button would be selected by default in the Download dialogue box.  

Of course if the current default download type is not applicable for the next video download request (e.g. default is Captions and the current video doesn't support captions download), then software logic would have to detect this condition and select a valid download type for this video download request and show a valid radio button selected for the download.

In all cases the user could still change the download type before selecting the OK button in the Download dialogue box just as things currently work.

#### How will you/everyone benefit from this feature?

The enhancement will allow users who want to download a sequence of videos with the same download type other than Video to do so with fewer clicks. I mostly use NewPipe to download the audio content of a video, so this enhancement will significantly reduce the number of times I have to change the download type radio button.

For users who exclusively download Video, this enhancement would have no impact.

**Comment by TobiGr** [comment]
The better approach is to store the last used download type and auto-select it.
