### ISSUE TITLE
Playback speed performance regression.

### ISSUE THREAD

**Issue by ZoomRmc** [TeamNewPipe/NewPipe#3493]
Somewhere along the **0.18-0.17** cycles a regression was possibly introduced which increased CPU consumption on unhooked speed change, both for video or background audio and regardless of video resolution. Now my device glitches even on a pedestrian 1.10-1.15x speed. Previously I had no stutters up to 1.75x range at least. Current high CPU load persists on **0.19.2** and **0.19.3RC1** versions.

Unfortunately, I can't recall when the regression started, since I upgrade regularly. I can't check it either since older version crash with current YT (#1052 is essential, BTW, I don't really get why it's not implemented).

Sorry, don't know how to reproduce previous better behaviour.

Also, I'd like to stress that NewPipe gave me better performance and better sound quality than VLC's speed change (it will be embarrassing to hear if the use the same code for this), so I'd like to continue using it, preferably for downloaded content also.

Thanks for the hard work, NewPipe is awesome!

**Comment by wb9688** [comment]
That's likely caused by the major ExoPlayer upgrade done in #2697

**Comment by Redirion** [comment]
@wb9688 unfortunately I failed upgrading to the latest ExoPlayer 2.11. What are your suggestions? Could you maybe take a look at my attempt in PR #2859?

**Comment by Stypox** [comment]
@ZoomRmc could you test the apk provided in #3513?

**Comment by ZoomRmc** [comment]
Sorry, no noticeable change for me. Crackling still starts at 1.2x.

I'm starting to entertain the possibility that's a problem on my end, but don't recall changing anything on my device that would introduce some constant activity degrading the overall performance. Anyway, it would be great to see some confirmation of the regression actually existing.

**Comment by opusforlife2** [comment]
Reply if it still happens in 0.19.8.
