### ISSUE TITLE
Download crashes at 99.93%

### ISSUE THREAD

**Issue by DavidBrazSan** [TeamNewPipe/NewPipe#3499]
This happens when I start the download and leave the app in the background. When I go to see the download it's stuck. so i need to pause and start again so it ends.

Android: 5.1.1
Device: Samsung Galaxy J2 J200M

**Comment by wb9688** [comment]
Does that happen both with and without SAF?

**Comment by gkeegan** [comment]
I have noticed this problem as well with SAF on (not sure if it happens with it off, haven't tested). It isn't always so close to the completion of the download, but it is more common at the end.

**Comment by DavidBrazSan** [comment]
> Does that happen both with and without SAF?

It happens both. But it's not always.

**Comment by opusforlife2** [comment]
Reply if it happens with 0.19.8.
