### ISSUE TITLE
Support direct youtube links in the search

### ISSUE THREAD

**Issue by Susurrus** [TeamNewPipe/NewPipe#35]
It'd be nice if pasting a YouTube URL (especially the m.YouTube.com-style URLs would bring you to that specific video in the app.

**Comment by theScrabi** [comment]
Hm ok.

**Comment by mairsbw** [comment]
Ideally this could replace the YouTube app for no-gapp devices like mine. I don't know what your plans are for this, but the mobile YouTube experience sucks, so having an app to intercept youtube links would be awesome.

**Comment by theScrabi** [comment]
Yep I'll keep that in mind.

**Comment by timofonic** [comment]
What about modifying hosts file to hear all requests to YouTube.com and show a list of them in the app? 

This could be browser independent and maybe there's already done mind if network logger that can be used for that.

**Comment by theScrabi** [comment]
You mean we should track which sides the user visits? If so, Hell no!!!

**Comment by locutis-of-borg-1999** [comment]
I've pasted the ID of videos into the search field, a few revisions ago (now on 0.7.5), and got unexpected results.  It showed SEVERAL cloned results, of the same, sole video.  I don't recall valid playback.  

Also, I think it had killed the ability to download, ENTIRELY, which returned upon upgrade.  I hesitate to try again, as downloading is a useful feature.

**Comment by theScrabi** [comment]
1. Pasting links in the searchbar is not yet supported.

2. Please put the download problem in it's own thread. It has nothing to do here.

**Comment by locutis-of-borg-1999** [comment]
1.  I do not refer to the pasting of links, but of the video's unique identifier string, withOUT the URL/query syntax.

2.  I didn't do any debugging, and would prefer to keep the installation working, rather than replicate the problem.

**Comment by theScrabi** [comment]
When I put the id of a video in the search bar of youtube I get no result. Since NP uses the same way for search this shows searching for ID is seemingly not possible. So if it worked before then It was most likely a change coming from Youtube.

**Comment by locutis-of-borg-1999** [comment]
Yes, well Google wants, what Google wants.  And, often, they get their way.  (Google, as you probably know, owns Youtube, and Yahoo, more or less.)

Anyway thanks for a great app'.

**Comment by theScrabi** [comment]
Thanks.

But that does not mean we couldn't implement something like that on newpipe. I don't know when but I think "Support direct youtube links in the search" and ID's should be coming.

**Comment by locutis-of-borg-1999** [comment]
:-)

**Comment by Paviluf** [comment]
That's a really useful feature. I hope it will be implemented soon :)

**Comment by theScrabi** [comment]
well bump :)

**Comment by Paviluf** [comment]
Hello @theScrabi do you think that feature can be implemented now ?
Thanks !

**Comment by theScrabi** [comment]
Not now, but when I have time to. If you want it asap try to implement it your self.

**Comment by Paviluf** [comment]
> If you want it asap try to implement it your self.

I'm not a developer, so no :(

**Comment by timofonic** [comment]
I miss this feature a lot. This and playlists are the ones most missed by me.

**Comment by Paviluf** [comment]
Thanks !
