### ISSUE TITLE
Add a time stamp suffix for share? 

### ISSUE THREAD

**Issue by poppypundit** [TeamNewPipe/NewPipe#3500]
http://www.youtubetime.com/#

Like the above, Can we add a script that adds a suffix that plays from a specific time as part of the share function?

**Comment by Stypox** [comment]
This already exists, try sharing a video while it is playing and it will be shared from there. If you want a better menu for sharing, there are already some open issues: https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aopen+share+menu
