### ISSUE TITLE
“Leaks in org.schabi.newpipe.debug”

### ISSUE THREAD

**Issue by ThomasLeigh** [TeamNewPipe/NewPipe#3503]
I use NewPipe on SAVIO Smart TV Box TB-P01 (Android 7.1 Nougat). This device has its own method to put chosen apps on desktop. When I put NewPipe on desktop, it always comes with yet another icon (yellow shield). Once tapped, it shows this message: “Leaks in org.schabi.newpipe.debug”.

Could someone explain what does it mean?

**Comment by wb9688** [comment]
That only appears in debug builds of NewPipe, not in release builds. That's a tool for developers to find memory leaks (i.e. NewPipe not freeing up memory when going to another screen while it should).
