### ISSUE TITLE
Backup/restore Channel Groups from the Subscriptions tab

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3505]
#### Describe the feature you want

I would like for the "Export to file" and "Import from previous export" options to include Channel Groups. It just seems like a natural addition now that you can group channels.

#### Is your feature request related to a problem? Please describe it

Currently, importing subscriptions from a file leaves you with just the bare list of subscriptions. You would have to group the channels again manually.

#### How will you/everyone benefit from this feature?

Convenience in importing subscriptions. You don't have to set up channel groups all over again.

**Comment by androidSwDev099** [comment]
@opusforlife2,
Export/import database includes the channel group when I use them? Is there a different method you are using that I don't know of?

**Comment by wb9688** [comment]
@androidSwDev099: Export/import DB and export/import subscriptions are 2 totally different things.

**Comment by Stypox** [comment]
Closing in favour of #4076

**Comment by opusforlife2** [comment]
@Stypox Why'd you close this? #4076 is about modifying/changing database import/export. This one is about subscription import/export.

**Comment by MD77MD** [comment]
> @Stypox Why'd you close this? #4076 is about modifying/changing database import/export. This one is about subscription import/export.

actually it falls under export import options which includes subscriptions.... meaning when done,  there should be only one setting to export/import anything you want.

**Comment by opusforlife2** [comment]
That's a longer term goal. We still have two import/export options for now, so we shouldn't block features until a dev decides to begin the larger import/export rewrite.
