### ISSUE TITLE
Show subtitles when using external player

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#3510]
#### Describe the feature you want

I use vlc as external player. But I cant understand english accent(though I can read it). Would be great if you could somehow provide subtitles to VLC.
#### Is your feature request related to a problem? Please describe it

Yes, I litellary cant watch english videos in vlc without this

#### How will you/everyone benefit from this feature?

I think it might be a little hard, but still possible. This feature will allow me to use all great features of external players like equalizer etc  Hence I think it is useful and will be nice to have.

**Comment by wb9688** [comment]
As far as I know it's not possible for an Android app to pass the URL of external subtitles together with the URL of the video to an external app for playback.

**Comment by opusforlife2** [comment]
Did you have a look at VLC's code?

**Comment by Stypox** [comment]
> I think we shouldn't add app-specific features

Yeah

**Comment by opusforlife2** [comment]
So, close?
