### ISSUE TITLE
Too Much Recaptcha

### ISSUE THREAD

**Issue by Babissimo** [TeamNewPipe/NewPipe#3512]
### Version

-0.19.2

### Steps to reproduce the bug

Do anything that interacts with YouTube

### Expected behavior

I expect to be able to watch videos and view channels and refresh feeds etc
### Actual behaviour

I get shown a Recaptcha but once doing it nothing happens
### Logs

It didn't crash or break or recognise a bug so I have no logs

**Comment by wb9688** [comment]
Please try the RC of v0.19.3
