### ISSUE TITLE
License dialog closes on rotation

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#3518]
### Version
v0.19.3 (and v0.19.2 as well, not sure about earlier versions, but there probably as well)

### Steps to reproduce the bug
1. Open About
2. Go to licenses and open one
3. Rotate your device

### Expected behavior
The dialog with the license is still shown

### Actual behaviour
The dialog with the license has gone away

**Comment by opusforlife2** [comment]
Duplicate of #4113. That one has fixes linkage, too.
