### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#3519]
#### Describe the feature you want

please add option to set custom User Agent string

#### Is your feature request related to a problem? Please describe it

no

#### How will you/everyone benefit from this feature?

replace default UA for testing

**Comment by Stypox** [comment]
*Please **follow the issue template** when creating an issue, don't just delete everything!* If you had followed it, I would know what the purpose and the advantages of this would be. Pleas edit the issue by copy-pasting the template

**Comment by opusforlife2** [comment]
Related: #3136.

**Comment by Stypox** [comment]
I'm closing this since I really don't see why it would be useful, and nobody provided a reason for it. Testing is done in the extractor, not in this repo, so this issue should be there, but anyway I don't see what would be the purpose of changing UA
