### ISSUE TITLE
update rate

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#3520]
#### Describe the feature you want

please add options to set custom global update rate for all subscriptions and update rate for each subscription apart

#### Is your feature request related to a problem? Please describe it

no

#### How will you/everyone benefit from this feature?

custom autoupdate of subscriptions

**Comment by opusforlife2** [comment]
Why, though? I don't get the point. Keep the fastest update threshold. Open any custom feed and tap update. Just don't tap update in the feed where you want slower updates. You have to do it manually, anyway.
