### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#3539]
### Version

- 0.19.3

### Steps to reproduce the bug

1) block address "suggestqueries.google.com" in firewall
2) search any video
3) a message "Network error	Retry" is displayed

### Expected behavior

found videos were shown earlier

### Actual behaviour

error message

**Comment by wb9688** [comment]
Disable search suggestions or don't block domains that are needed

**Comment by anpic** [comment]
> Disable search suggestions or don't block domains that are needed

NewPipe works in earlier versions without "suggestqueries.google.com"
this address is only needed for displaying suggestions not for video searching

**Comment by Stypox** [comment]
Yes, so disable search suggestions
