### ISSUE TITLE
Show search history even when search suggestions are disabled 

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#3540]
### Version

- 0.19.3

### Steps to reproduce the bug

1) enable Search history
2) disable Search suggestions
3) enter some search queries
4) check search history
5) search history is empty :(

### Expected behavior

store search queries locally

### Actual behaviour

search history is empty

**Comment by Stypox** [comment]
Well, queries are saved into search history even though suggestions are disabled (I just tested), but they never show up in the suggestion list. Is the issue you are pointing out that local search history is not shown as search suggestions?

**Comment by anpic** [comment]
> Is the issue you are pointing out that local search history is not shown as search suggestions?

yes, of course :)

**Comment by Stypox** [comment]
@anpic could you try the apk provided in #3546?

**Comment by anpic** [comment]
> @anpic could you try the apk provided in #3546?

it works :)
