### ISSUE TITLE
Idk why i can't import subcription

### ISSUE THREAD

**Issue by DayatXD** [TeamNewPipe/NewPipe#3541]
![Screenshot_2020-05-06-20-31-28-721_org schabi newpipe](https://user-images.githubusercontent.com/47524544/81177164-cf30a100-8fd8-11ea-95c9-042a67acae2b.jpg)

**Comment by Stypox** [comment]
*Please **follow the issue template** when creating an issue, don't just delete everything!* Now I have to ask questions you would have already answered: which version of NewPipe are you using? Which buttons have you pressed? Which kind of file were you trying to import (i.e. from youtube or from a previous export)?

**Comment by DayatXD** [comment]
Oops sorry i didn't pay attention, i dont see the import button on the youtube button. Iam trying to import it from previous export thats why it didn't work

**Comment by DayatXD** [comment]
Maybe you should add background/move the button to center where we can see it easily i think...

**Comment by AnXh3L0** [comment]
What kind of file are you trying to import? Is that an export coming from an older version of NewPipe (done via the Settings menu) or what?

**Comment by Stypox** [comment]
> Maybe you should add background/move the button to center where we can see it easily i think...

It is already pretty visible, imo
