### ISSUE TITLE
No way to ensure NewPipe doesn't download via Mobile Data

### ISSUE THREAD

**Issue by jsoftwareengineering** [TeamNewPipe/NewPipe#355]
The version of NewPipe on F-Droid (haven't had time to check the current version on here, so please tell me if I out of date on this) doesn't have an option to restrict downloads to Wi-Fi. Moreover, it ignores Android settings that restricts its use of background mobile data. 

For example, I have background mobile data use restricted for NewPipe through Android 7 settings, and owing to me disconnecting from Wi-Fi during a download (due to router problems) I have around 600 MB of background data used by NewPipe.

**Comment by theScrabi** [comment]
That may be. This option has never been implemented.

**Comment by okias** [comment]
@jsoftware tou can solve this by using AFWall (android firewall) by allowing NewPipe use only WiFi connection

**Comment by theScrabi** [comment]
Yea but that requires root access.

**Comment by wb9688** [comment]
On some phones there's also an option in the settings to prevent an app
from using mobile data.

**Comment by anonymau5** [comment]
@okias Unfortunately AFWall isn't perfect on 7.1+.  Many times it will not block or will not allow despite the settings set which seems to be at random on which ones it works on and which ones it doesn't.  It would be nice if this app could prevent itself from using any mobile data.

**Comment by anonymau5** [comment]
Seems even on 8.0 AFWall is still unable to prevent this.  It would be nice if this could be implemented within the app itself.

**Comment by mauriciocolli** [comment]
I really don't like that much of `GigaGet` as it's [deprecated/discontinued](https://github.com/PaperAirplane-Dev-Team/GigaGet) (last update was in 2014).

After we implement the playlists and some other high-priority issues/features, this is the next thing to improve and I'll try to make sure that it have an option to do this.

**PS**: We can find some good libraries in [Android Arsenal](https://android-arsenal.com/tag/179?sort=created&category=1) (I already found [Fetch](https://github.com/tonyofrancis/Fetch) that seems to be good, and it already have an network policy built in).

**Comment by TobiGr** [comment]
fixed in #1759
