### ISSUE TITLE
[SUGGESTION] More video services, more fun !

### ISSUE THREAD

**Issue by forart** [TeamNewPipe/NewPipe#3552]
In the [previous tip](https://github.com/TeamNewPipe/NewPipe/issues/3532) I learned that NewPipe can - through NewPipeExtractor - playback from other video services too.

I just discovered that [Android Oembed Video](https://github.com/TalbotGooday/Android-Oembed-Video) claims to be: 
_"A simple library for parsing and playing links from YouTube, YouTube Music, Vimeo and Rutube and others in the WebView without the need to connect data API services."_

Dunno if could be useful, but hope that inspires.

**Comment by Stypox** [comment]
If someone wants to implement new services, they are obviously welcome ;-)

**Comment by gasull** [comment]
Also LBRY.

**Comment by HTSamurai** [comment]
twitch?
