### ISSUE TITLE
video breaks off

### ISSUE THREAD

**Issue by Evgen-nn** [TeamNewPipe/NewPipe#3553]
Hello. 
I am trying to use NewPipe v0.19.3 on my Android tv-set, but any video breaks off after 1min play. Anyway  the same version of NewPipe works perfect on my smartphone with the same videos at the same time.
What can I do to solve this?

Android 7.1.1 on BBK tv-set;
Realtec chip rtd284x;
Memory - 8Gb;
RAM - 1Gb;
LAN Internet connection;
NewPipe v0.19.3.

**Comment by Stypox** [comment]
Could you try the apk provided in #3513?

**Comment by Evgen-nn** [comment]
> Could you try the apk provided in #3513?

I tried, without changes.

**Comment by Stypox** [comment]
What do you mean by "it breaks off"?

**Comment by Evgen-nn** [comment]
the video stops, the sound disappears, the last frame from the played video remains on the screen. If you scroll a bit after that, the video will begin playing, but only for one minute and everything will stop again.

**Comment by Stypox** [comment]
Can the device you are using be considered a low-ram or low-performance one? Anyway, do videos from i.e. MediaCCC generate the same issue? Maybe #3348 is related

**Comment by opusforlife2** [comment]
@Evgen-nn Could you try 0.20.0?
