### ISSUE TITLE
Videos unavailable or cannot be played on device

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#3554]
Version: 19.3
Steps to reproduce the bug:
Exhibit A: https://www.youtube.com/watch?v=XSPtMamKJGc
Exhibit B: https://www.youtube.com/watch?v=d7a17z9EQ4M

Note: 'Exhibit A' can be played directly on YT, but not on NP
Note: 'Exhibit B' cannot be played on NP or YT on devices.

Expected behavior: Video being viewable.
Actual behaviour: As mentioned above
___
Thank you for your time and attention.

**Comment by Stypox** [comment]
A is a movie, and NewPipe currently does not contain the needed code to license films.
B is a video that was made unavailable by youtube, so there is nothing that can be done.
