### ISSUE TITLE
Infinite loading in lists when items aren't filling the screen

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3555]
### Version

- 0.19.3

### Steps to reproduce the bug

1. Go to PeerTube, open any kiosk, channel, or go to SoundCloud and open any kiosk

### Expected behavior

Infinite loading

### Actual behaviour

It finishes to load and display items

### Screenshots/Screen recordings

![IMG_20200509_130106_1](https://user-images.githubusercontent.com/58657617/81472021-e217c100-91e4-11ea-9137-8463c9d1643a.jpg)
![IMG_20200509_130123_1](https://user-images.githubusercontent.com/58657617/81472035-e93ecf00-91e4-11ea-8ad1-22f7141f7795.jpg)
![IMG_20200509_130156_1](https://user-images.githubusercontent.com/58657617/81472042-efcd4680-91e4-11ea-874f-ad7384dd876b.jpg)

### Additional context

On Youtube, the number of items loading per page is higher: for kiosks, Peertube: 12, SoundCloud: 10, YouTube: 30, and for channels: 29 on Youtube, SoundCloud 17, PeerTube 12.
Maybe we should set if possible (control with API) all at the same value.

It happens on large devices where the items are not filling the first screen, therefore you can trigger the continuation process by scrolling down.

**Comment by Stypox** [comment]
This was already reported a while ago, but I can't find the duplicate issue. But this definitely needs to be solved

**Comment by B0pol** [comment]
found it https://github.com/TeamNewPipe/NewPipe/issues/1974
