### ISSUE TITLE
Old videos aren't shown in feed

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3557]
### Version

- 0.19.3

### Steps to reproduce the bug

1. Have no subscriptions (export and clear data or build dev branch).
2. Subscribe to [Roddy Rich](https://soundcloud.com/roddyricch), and [Ariana Grande](https://invidious.snopyta.org/channel/UC9CoOnJkIBMdeijd9qYoT_g), _or any channels doing few videos per year_.
3. Go to your subscriptions

### Expected behavior

You see some musics from roddy rich and ariana grande, or your channel you've picked in step 2.
At least what has been fetched for the first page (15 videos for xml feed: fast mode, and 29 for dedicated feed method on YouTube, about 15 videos on Peertube…).
### Actual behaviour

Only one music from ariana grande (it was released yesterday) and no other musics.
### Screenshots/Screen recordings

<img width="200" src="https://user-images.githubusercontent.com/58657617/81473051-a16f7600-91eb-11ea-9c4f-c72ee020f4bf.png"> <img src="https://user-images.githubusercontent.com/58657617/81473066-b3511900-91eb-11ea-8594-439e57d23676.png" width="200">

as you can see, the channel doesn't have only one video, it's just three months old (and 5 for roddy rich):

<img src="https://user-images.githubusercontent.com/58657617/81473061-aa604780-91eb-11ea-86a4-64a66ec08f7a.png" width="200">

**Comment by opusforlife2** [comment]
Is this fast mode or slow mode?

**Comment by B0pol** [comment]
Both

**Comment by wb9688** [comment]
With fast mode, it's not possible to have more AFAIK. With slow mode, it would be possible, but I don't know how desirable that would be, especially with lots of subscriptions.

**Comment by Stypox** [comment]
Isn't this the same as #3354?

**Comment by B0pol** [comment]
It is

**Comment by leonardojorgelayun1972-lab** [comment]
Hola 👋 desde 🇦🇷 ARGENTINA 🇦🇷 desde hace un tiempo estoy notando qué todas las plataformas de NEWPIPE no están funcionando correctamente todas te tiran un error 1 / NEWPIPE PIPE REVO FEFACTOR / 2 / NIGHTLY / 3 / 4 / REVO / 5 / ZING / 5 / TUBULAR / 6 / X / entre otros que permanentemente te tiran un error gracias ojalá lo puedan solucionar rápido así seguimos disfrutando de los videos
