### ISSUE TITLE
Allow to Play Video File

### ISSUE THREAD

**Issue by DayatXD** [TeamNewPipe/NewPipe#3560]
#### How will you/everyone benefit from this feature?

Can you make newpipe can play video file like .mp4 or .mkv, i would love that because i want play my video with newpipe pop up player!

**Comment by DayatXD** [comment]
Why its labelled bug

**Comment by Stypox** [comment]
https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aopen+offline

**Comment by cauerego** [comment]
just for reference

#478

it's probably the same intention...

i also can't see how it would allow to play downloaded videos but not videos from elsewhere! 😁
