### ISSUE TITLE
Mini player dissappears when pressing on a notification. 

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#3563]
Version: 0.19.3

Device: Galaxy S10

Notes: Audio still plays in the background but If receiving a notification and pressing it to view it in full the mini player is no where to be found while audio still goes on clearly.

**Comment by opusforlife2** [comment]
@Flam3z Still an issue in 0.20.0?

**Comment by Flam3z** [comment]
@opusforlife2 nope :)

**Comment by opusforlife2** [comment]
Awesome!
