### ISSUE TITLE
Download playlist

### ISSUE THREAD

**Issue by tnekent** [TeamNewPipe/NewPipe#3568]
#### Describe the feature you want

It would be awesome if you can add a feature to download playlists, or rather, every item in the playlist automatically.

#### Is your feature request related to a problem? Please describe it

Most of the time I want to download all of the songs in the playlist, but sometimes the number of items in the playlist are big so it would be **very** tiring to click each item only to repeatedly download it (with the same format).

#### How will you/everyone benefit from this feature?

I think it would save a lot of time for many of us trying to download YouTube playlists, and this feature is already supported by other downloaders, so why not?

**Comment by wb9688** [comment]
Please look for duplicate issues first

**Comment by venkat2305** [comment]
hope this feature comes soon

**Comment by opusforlife2** [comment]
Don't bump a zombie issue, especially if you have no information to add.

**Comment by venkat2305** [comment]
Ok

**Comment by SameenAhnaf** [comment]
@venkat2305 This issue is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5482
