### ISSUE TITLE
Can't import playlist

### ISSUE THREAD

**Issue by rogerxed** [TeamNewPipe/NewPipe#3569]
If there is a option to import youtube playlists, that would be really helpful. In your website you mentioned import playlist option, but I couldnt find anything like that in your app. Please add it.

**Comment by androidSwDev099** [comment]
Open the Subscriptions menu in the Subscriptions tab.... It's there.

**Comment by rogerxed** [comment]
That is for import subscriptions, no option to import youtube playlist,

**Comment by androidSwDev099** [comment]
Are you referring to a playlist that's already on YouTube or one you created? I can save existing ones on YouTube by clicking on the icon at the top with the + symbol.

**Comment by rogerxed** [comment]
Yes. I have lots of it, it takes so much time. Iam wondering what they mentioned in their site as "import playlists" (bookmarks and local playlists)

**Comment by Stypox** [comment]
Is there a way to export playlists in Youtube? If yes, then this is doable, otherwise not

**Comment by AwesomelyHumble** [comment]
I'm having a similar issue. I can find the playlist on YouTube. When I copy the share link for that playlist and paste it into Newpipe, I can save the playlist in Newpipe by pressing the + button. BUT when I view that playlist it does not show any videos. It shows the channel name, playlist name, and number of videos in the playlist but does not show any of the videos. I've attached a screen shot. Here is a url to the playlist I'm trying to save https://www.youtube.com/playlist?list=PL8dPuuaLjXtOAKed_MxxWBNaPno5h3Zs8
![Screenshot_20200513-055346](https://user-images.githubusercontent.com/28993697/81814873-22758880-94de-11ea-8eb2-eeef1935ebec.jpg)

**Comment by wb9688** [comment]
@AwesomelyHumble: For me it just works:

![Screenshot_20200513-145957_NewPipe](https://user-images.githubusercontent.com/46277131/81815595-773ef080-952a-11ea-8c7c-bfcd4d49fa5f.jpg)

Do you see the items in the playlist before adding it? If not, when you open it in your desktop browser, do you see anything (e.g. advertisement) above the actual playlist items?

**Comment by AwesomelyHumble** [comment]
@wb9688 What the?! How did you do that? Okay, something is wrong on my end then, thanks for the screenshot. I am able to view the videos in the browser, just not in Newpipe before adding the playlist. I am able to add individual videos, so it appears this is playlist specific. I'll dig around the settings to see if I'm missing something. I have the latest version (as of now, 0.19.3). I also have AdGuard installed, maybe that is somehow blocking the playlist, though not sure how. I only mention this because it does block a lot and I'll have to add to whitelist or unblock at times.

**Comment by B0pol** [comment]
I can reproduce the issue with the first playlist. For the second one, it shows only 8 out of 17.

**Comment by wb9688** [comment]
@B0pol: I could reproduce the 8/17 issue and I'll fix that in a few minutes.

**Comment by Stypox** [comment]
Let's keep only #1751 open
