### ISSUE TITLE
Essentially needed features 

### ISSUE THREAD

**Issue by degarb** [TeamNewPipe/NewPipe#3570]
New pipe Essential needs The pop out needs a pop in button, since if I am taking notes I can jump back into full screen without killing new pipe.... Record/dL entire playlist to audio or video with single click, rather than 400 clicks for 100 videos in a playlist.

**Comment by wb9688** [comment]
1. Please fill in the issue template.
2. Please search if there are existing issues first.
3. Create separate issues for separate feature requests / bug reports.
