### ISSUE TITLE
Keyword Blocker

### ISSUE THREAD

**Issue by brigglybaile** [TeamNewPipe/NewPipe#3571]
#### Describe the feature you want

I exclusively use this app to avoid spoilers on YouTube however even then it is possible to get the ending/spoilers video no matter how careful I get. Which essentially means that I have to use Chrome YouTube Blocker extension on my pc if I want to watch gameplay or stuff. Is it possible to add a features which blocks videos that have a certain keyword(s)?
#### How will you/everyone benefit from this feature?

Avoiding spoilers is one of the main features of this app and this certainly make it the best YouTube app to use on mobile.

**Comment by Stypox** [comment]
I edited #1815 to include your suggestion, i.e. keyword-based blocking
