### ISSUE TITLE
Crash if „what's new” is added to main page.

### ISSUE THREAD

**Issue by alekksander** [TeamNewPipe/NewPipe#3572]
This crash occurs only when app language is set to polish. Otherwise i can't reproduce. 

{"user_action":"ui error","request":"App crash, UI failure","content_language":"pl_PL","service":"none","package":"org.schabi.newpipe","version":"0.19.3","os":"Linux Android 8.1.0 - 27","time":"2020-05-11 07:26","exceptions":["java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  \n\tat java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4398)\n\tat java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3091)\n\tat java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3049)\n\tat java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2816)\n\tat java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)\n\tat java.util.Formatter.parse(Formatter.java:2557)\n\tat java.util.Formatter.format(Formatter.java:2504)\n\tat java.util.Formatter.format(Formatter.java:2458)\n\tat java.lang.String.format(String.java:2814)\n\tat android.content.res.Resources.getString(Resources.java:458)\n\tat androidx.fragment.app.Fragment.getString(Fragment.java:873)\n\tat org.schabi.newpipe.local.feed.FeedFragment.updateRefreshViewState(FeedFragment.kt:283)\n\tat org.schabi.newpipe.local.feed.FeedFragment.handleResult(FeedFragment.kt:210)\n\tat org.schabi.newpipe.local.feed.FeedFragment$onViewCreated$1.onChanged(FeedFragment.kt:73)\n\tat org.schabi.newpipe.local.feed.FeedFragment$onViewCreated$1.onChanged(FeedFragment.kt:42)\n\tat androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)\n\tat androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)\n\tat androidx.lifecycle.LiveData.setValue(LiveData.java:289)\n\tat androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)\n\tat androidx.lifecycle.LiveData$1.run(LiveData.java:91)\n\tat android.os.Handler.handleCallback(Handler.java:790)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6606)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)\n"],"user_comment":""}

**Comment by wb9688** [comment]
Look for open issues first: #3524. Plus if you're posting a crash here, use [this](https://teamnewpipe.github.io/CrashReportToMarkdown/).

This is caused by the Polish (and some other translations at other places) translation being incorrect, and for feature releases we'll check for such incorrectness before releasing.
