### ISSUE TITLE
Allow boosted sounds

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#3573]
#### Describe the feature you want

Some players like vlc and MX player allow volume to go up to 200%. It will be great to see such feature in Newpipe

#### Is your feature request related to a problem? Please describe it

Some videos have low sound, so it will be helpful
#### How will you/everyone benefit from this feature?

Four letters ASMR

**Comment by B0pol** [comment]
If this implemeted, made it opt-in option. I don't want my ears to be destroyed accidentaly.

**Comment by grravity** [comment]
@B0pol This, especially because I never have the need to go past 100%

**Comment by wb9688** [comment]
Not possible: https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L728
