### ISSUE TITLE
Reddit comments support

### ISSUE THREAD

**Issue by gabriellluz** [TeamNewPipe/NewPipe#3577]
#### Describe the feature you want
Right now we can't comment on any video. What about using Reddit to comment on every video? The user would need a Reddit account. Of course, this is optional.

Right now, you can use this Chrome extension to write comments for YouTube videos using Reddit
https://chrome.google.com/webstore/detail/reddit-comments-for-youtu/oeehccpigolildhagkmlpofjplfajiam

#### Is your feature request related to a problem? Please describe it

It's not possible to write comments.

#### How will you/everyone benefit from this feature?
People will be able to comment on videos.

**Comment by B0pol** [comment]
For logging and posting, see https://github.com/TeamNewPipe/NewPipe/pull/2668 https://github.com/TeamNewPipe/NewPipe/issues/2929.
And there is one another problem: Reddit is a private company, where NewPipe / Invidious are libre project and PeerTube is a non-profit association, all three with privacy and freedom as values. It's not the case for Reddit.

Secondly, we could maybe add viewing reddit comment, with Invidious API: see https://github.com/omarroth/invidious/wiki/API#get-apiv1commentsid

Finally, sort by new & comment replies are prioritised over Reddit comments

**Comment by AudricV** [comment]
As Reddit made usage of their public API way harder than before in July 2023, we may have to rely on their internal API, which can be difficult to maintain, especially with our limited bandwidth.

I also do not see a lot of support for this request, which should be hard to implement correctly technically.

For the reasons stated above, I am closing this issue as won't fix. This could be reconsidered in the future, even if I don't think this will happen.
