### ISSUE TITLE
Youtube chapter support

### ISSUE THREAD

**Issue by adosikas** [TeamNewPipe/NewPipe#3578]
#### Describe the feature you want

Some YouTube videos have chapters, it would be nice if this feature would be integrated with NewPipe.

In particular I would love to see this as option on downloads, adding chapters to the file or splitting it into separate files with suffix corresponding to the timestamps.

#### Is your feature request related to a problem? Please describe it

The chapter are handy when you want to skip over certain sections of a video/podcast via the timestamps in the description, which obviously doesn't work for downloads or when you don't have the description open (background/popup playback).  
Making a script to extract the timestamps from the description, downloading the video, split it and finally send it to my phone works, but doing it directly from NewPipe would be much simpler.

#### Additional context

Article with example video: https://www.androidpolice.com/2020/04/13/youtube-is-rolling-out-video-chapters-to-help-you-skip-to-the-parts-that-matter/, but it seems to have rolled out to many other videos and creators.

Prior to this, many videos already had timestamps in their descriptions, so backwards compatibility for that method would be nice-to-have as well.

Having to option to unselect chapters while downloading would be another nice-to-have, if one knows ahead of time which chapters one is not interested in, saving both bandwidth/storage and having to manually skip them when playing back.

I would think this feature be would similar to SponsorBlock (#3205) in implementation, maybe some work can be reused or made generic.

#### How will you/everyone benefit from this feature?

When watching videos in places with limited connectivity (subway, rural areas, ...) being able to navigate through the video without having to manually scrub through the timeline or clicking timestamps would be nice.

For people listening to audio-only podcasts while otherwise occupied (car, exercise, ...) this would be a major improvement as skipping parts (or rewinding to listen to a chapter again) is not possible without looking at the screen or blindly skipping ahead (if the playback device / headphones support fast-forwarding at all). This applies to both background playback and downloaded files.

**Comment by B0pol** [comment]
Requires https://github.com/TeamNewPipe/NewPipe/issues/3207

**Comment by dragonchaser** [comment]
Especially splitting the downloads in chapters would be a great plus!

**Comment by FireMasterK** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/pull/479 has been merged, this no longer needs extractor changes.

**Comment by mhmdanas** [comment]
Fixed by https://github.com/TeamNewPipe/NewPipe/pull/5274.
