### ISSUE TITLE
[ISSUE] NP won't play in my (cheap) Android TV

### ISSUE THREAD

**Issue by forart** [TeamNewPipe/NewPipe#3586]
I do own a cheap 4K TV (Mstar-based, Android 6, [QT43K03](https://qbell.it/prodotti/qt43k03/) by Qbell) and, since it works correctly for browsing & searching, NP won't play any video at any resolution.

Do I need to install something other ?

**Comment by allendema** [comment]
@forart Can you check it again with the latest relase, if that does not help, change the video format say from 3GP to MPEG-4.
Also be sure that you have not blocked Yt related domains which are used for streams.

**Comment by opusforlife2** [comment]
@forart Still having this issue in 0.20.0?
