### ISSUE TITLE
Version 19.3 'content unavailable' 

### ISSUE THREAD

**Issue by BM-010** [TeamNewPipe/NewPipe#3591]
### Version

- v19.3

### Steps to reproduce the bug
 it keeps happening regardless of what I do. There are no steps. 

 I just used the search engine, tried to pick a video and it throws 'content unavailable' in my face. 

### Expected behavior
 I expected to actually be able to play the video. 

### Actual behaviour
 I pick a video and the error comes up. No matter what I search, any video at all. This comes up. 

### Screenshots/Screen recordings
 
![Screenshot_2020-05-15_003339](https://user-images.githubusercontent.com/65374559/81995957-bf056b00-9643-11ea-81ab-61b595b279c8.jpg)

**Comment by B0pol** [comment]
I can't reproduce

**Comment by BM-010** [comment]
(Sorry, I fell asleep.) I meant to give an update on the matter, saying that everything seems to be going OK now. I just had to wait a few minutes.
