### ISSUE TITLE
Make possible to select subscription groups from the subscribe button

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#3598]
Is your feature request related to a problem? Please describe it

This idea is going along @opusforlife2 's feature requests: making easier the subscription groups use. For now, the only way to edit these groups is from the subscription tab and its not always that handy.

Describe the feature you want

The idea would be to have the possibility to add a channel to a/some group(s) once you've hit the "subscribe button"
For this i imagined two possible ways, that could complete each other:
- by long pressing the subscribe button, opens a menu showing the different groups, making easier choosing each ones.
- Right after subscribing: showing a message down to the screen (not a toast, more like the errors are displayed with the recent versions in newpipe)
This would permit to give a hint to the user for this function, so it makes it more user friendly.
On the other hand, the first way would permit modifying groups without having to "unsubscribe- subscribe" to show again the dialog,  thats why i think these two ways go along together :) 

Feel free to discuss this, if interested

**Comment by jniniinoinoino** [comment]
That's justanidea

**Comment by justanidea** [comment]
Yeay, someone said this

**Comment by MD77MD** [comment]
#3352
Add new subscribed channels to feed groups directly from button #3352

Describe the feature you want
The ability to add new subscribed channels to feed groups directly from the subscription button

Additional context
My suggestion is to add a drop down menu when pressing the subscription button containing all feed groups with a checkbox next to them. this is inspired from what youtube use to add videos to playlists

How will you/everyone benefit from this feature?
This would make adding new channels to groups immediate.. and would save so much effort especially if your adding the new channel to multiple groups. maybe try to add a channel to multiple groups to see what i mean.

**Comment by justanidea** [comment]
@MD77MD Right, im sorry. Should i close mine or would you close yours?

**Comment by MD77MD** [comment]
let that for the developers... i would like them to read both of our ideas first, so they can implement this future in the best possible way.
