### ISSUE TITLE
Play overlay needs to be thicker

### ISSUE THREAD

**Issue by PanderMusubi** [TeamNewPipe/NewPipe#360]
The latest play overlay button is too thin, especially compared to the other control buttons. Please make it thicker to prevent 'white wash out', for example use the new logo as play overlay.

**Comment by theScrabi** [comment]
Sure? It's not meant as a button. It should make you see the thumbnail behind it, but still tell you that you have to tab there.
The whole thumbnail is the button.

**Comment by PanderMusubi** [comment]
Yes, that I understand, only the lines are very very thin and disappear on a white background.

**Comment by theScrabi** [comment]
I put a shadow around the lines, so they will always be visible. Does that work?

**Comment by PanderMusubi** [comment]
Yes, thanks. Let me know when to test it.

**Comment by theScrabi** [comment]
No I mean it's the current version xD

**Comment by PanderMusubi** [comment]
Thanks, looks very nice!

**Comment by theScrabi** [comment]
Sure? So I should not make it darker than?!?

**Comment by PanderMusubi** [comment]
It is good. Test with https://www.youtube.com/watch?v=YVDWR1v1mpc
