### ISSUE TITLE
Live stream not showing in subscriber Feed

### ISSUE THREAD

**Issue by dipuburman** [TeamNewPipe/NewPipe#3605]
### Version

-

### Logs

App v 0.19.3
Live streams asr not showing in the subscribeed feed. After searching for the channel and search inside than only it will showing

**Comment by wb9688** [comment]
That happens when you're using the dedicated feed iirc

**Comment by Stypox** [comment]
Yes, this is intended and there is nothing that can be done about it because the information is missing. @dipuburman use the other slower but more info-complete method.
