### ISSUE TITLE
Add option to play in pip mode when I go back from a playing video. 

### ISSUE THREAD

**Issue by dipuburman** [TeamNewPipe/NewPipe#3606]
#### How will you/everyone benefit from this feature?

V 0.19.3
When I press the back button while watching a video it will stop the video immediately.
Please add a feature that the video can still playing in pip mode when i press the back button while watching.

**Comment by Stypox** [comment]
There is already the button to manually switch to popup, and you can just press the button to show recent apps with "Minimize on app switch" and the popup will appear. Also, having the back button open the popup would not be what you would expect. (if someone disagrees, reopen the issue)
