### ISSUE TITLE
[Question] How do I hide this annoying "Feed groups" thingy in the Subscriptions tab?

### ISSUE THREAD

**Issue by azat11** [TeamNewPipe/NewPipe#3607]
When did it appear anyway? I want the former layout.

**Comment by Stypox** [comment]
Well, that's the new layout for the subscription tab. It now allows to group subscriptions toghether for better organization. See #2309

**Comment by azat11** [comment]
I have ten or so channels I watch that post very rarely. So an option to hide that would be nice. Right now I rolled back to 0.18 and I'll use that for as long as I can.

**Comment by OffifialMITX** [comment]
@azat11 well good luck for like two weeks or so until YT changes again.

**Comment by ingingin** [comment]
Wait, the former layout? Was that even better? Oh it just hit me. Well maybe there should be a way to see which videos has been added after an update. I'll create an issue for that :D

**Comment by Stypox** [comment]
@ingingin there is already an open pr which would add support for hiding watched videos

**Comment by Stypox** [comment]
Anyway, I don't see what the issue is here. @azat11 can't you just ignore the feed groups and scroll down a little?

**Comment by ingingin** [comment]
> @ingingin there is already an open pr which would add support for hiding watched videos

Aw, that would also work. But I don't usually watch every video that is uploaded. Most people have subscriptions that they just subscribe to cuz they wanna see what they upload. Like most of YouTube, (the inactive subscribers) 

Would it not be better to add something to display which new videos have been added?

**Comment by ingingin** [comment]
Please close my #3611 if you feel like it, I couldn't wait too long to submit the issue for a respond. :)
