### ISSUE TITLE
youtube.com/username channel links aren't supported

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3608]
### Version

- 0.19.3

### Steps to reproduce the bug

Try to open this link https://youtube.com/DIMENSI0N

### Expected behavior

It opens DIMENSI0N's youtube channel
### Actual behaviour

Unsupported URL

Invidious supports this type of link. Try https://invidious.snopyta.org/DIMENSI0N

**Comment by Bartoshr** [comment]
Hi. I would like to fix this one. 
As I understand it correctly this link should be handled like https://www.youtube.com/c/DIMENSI0N.

**Comment by B0pol** [comment]
It seems like, yeah

**Comment by B0pol** [comment]
Yes

> If eligible, you can give fans an easy-to-remember web address, called a custom URL, for your YouTube channel. This will look like youtube.com/yourcustomname or youtube.com/c/yourcustomname.

https://support.google.com/youtube/answer/2657968?hl=en
