### ISSUE TITLE
Pressing Download button in PeerTube mode, halts NewPipe entirely [needs to be killed manually][used to work]

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3609]
Switching to any instance of peertube (I'm using for example https://peertube.social), 
clicking on the download button halts the entire application. 

![GIF-200518_003950](https://user-images.githubusercontent.com/415238/82160773-549d3680-98a0-11ea-8043-6d742198b516.gif)
and it must be killed. 
![Screenshot_20200518-002933_V Recorder](https://user-images.githubusercontent.com/415238/82160771-523adc80-98a0-11ea-8f7d-4a39444e6cc7.jpg) 
this is the OS dialog saying the app is not responding. 

b.t.w. Its not related to way the content actually downloads (standard/storage access framework) since it happens in both ways the download is configured. Probably earlier in the resource fetching cycle.

It used to work fine two versions ago.

**Comment by wb9688** [comment]
I could confirm it. I'll look into it tomorrow.

**Comment by wb9688** [comment]
I did a `git bisect` and it's caused by fda5405e48f7cb1f4f4b9df89052d55c90e8b167 (i.e. my Checkstyle fixes) :/

**Comment by eladkarako** [comment]
`git bisect` is great, and if you'll have a script for testing that outputs exit code 0 when it passes you can find bugs automatically with bisect run. NewPipe has a decent test suite doesn't it?

**Comment by wb9688** [comment]
@eladkarako: Not really. I just ran `./gradlew installDebug` every time and checked on my phone whether the issue was happening. Obviously I also had to uninstall the app a few times, as you can't install an app with a lower version code.
