### ISSUE TITLE
There is no animation of downloading pages anymore

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#361]
Since version 0.8.5 there is no animated ring, indicating downloading of pages. It is no longer possible to determine if it is the end of video list or it is a connection error.

**Comment by theScrabi** [comment]
Yea thats true I copleatly reworked the list viewes. They are now based on NastedListView. However i had to remove the footer view since I could not find a way to implement there.

**Comment by teod0r** [comment]
Can you add the animation ring somewhere else?

**Comment by theScrabi** [comment]
Well I thought about adding this new reload indicator of lollipop to the bottom. But I could not figure out how.

**Comment by teod0r** [comment]
The main problem is that new version DOES NOT NOTIFIES about a connection error. The animaited ring was a way to find out if a page was not loaded because of a connection error. Now it is not possible to find out if it is the end of video list or it was not downloaded because of error.

**Comment by teod0r** [comment]
I've found out that there is a notification about connection error through android notification system, not through the window of NewPipe. The reason that I didn't know about that is that I turned off notifications for NewPipe.

**Comment by theScrabi** [comment]
Thats strange behavior. Have you checked if it only applies on your phone?

**Comment by teod0r** [comment]
What do you mean?
I'm using a tablet, not a phone.
