### ISSUE TITLE
Continue playlist and shortcut widget

### ISSUE THREAD

**Issue by caogia** [TeamNewPipe/NewPipe#3616]
#### How will you/everyone benefit from this feature?

Hello,
How do I continue to play a playlist that I've saved?  Everytime I open saved playlist. i need to tap Play all, then tap Next video to the one that I've had played before.
Many thanks

**Comment by ingingin** [comment]
@caogia Go to a playlist, click **"Background"**, open your notifications area and tap the video playing in the background. There you would get the whole list. Tap the video you want to play. Then press the **...** menu at the top right.  Select **"Switch to Main"**

**Comment by wb9688** [comment]
@ingingin: The main player also just has a button that shows the playlist. No need to switch to the background player for that.

**Comment by ingingin** [comment]
@wb9688 You're right. Never really touched the video part as all I do it play the video and forget about it. xD

**Comment by ingingin** [comment]
@wb9688 Nah man. I opened a video and pressed the Playlist button. It only shows the next playable video. Not my entire playlist :C

**Comment by Stypox** [comment]
Related: #2566

**Comment by ingingin** [comment]
I think this was more of a question than feature request lol
