### ISSUE TITLE
Add Video (not Audio or Popup) to Queue

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3619]
#### Describe the feature you want

Long pressing on the video thumbnail on the video details fragment should add the video to the video queue (the one which you access through the queue/list icon in the player. Currently, it just gets highlighted, then plays the video when you lift your finger.

#### Is your feature request related to a problem? Please describe it

You can long press to add an audio or popup to the queue, but can't do it with the full video.
#### Additional context

This feature request requires #2611 to be fixed first. Otherwise, adding a video to an empty queue will just play the video, defeating the entire point.
#### How will you/everyone benefit from this feature?

You can then conveniently build a queue to watch videos.

**Comment by opusforlife2** [comment]
Actually, considering we have the ability to minimize the player after 2907, how about a direct "Enqueue in main player" option instead? Or, in Stypox's info items PR, a button to enqueue in the main player?

**Comment by Stypox** [comment]
The Enqueue button lets you build a queue even on the main player.
