### ISSUE TITLE
(Bug) Opening channel URL from Browser, auto-plays the latest video.

### ISSUE THREAD

**Issue by allendema** [TeamNewPipe/NewPipe#3624]
### Version

-  0.19.3 - Android 10
### Steps to reproduce the bug
 Open YouTube in Firefox ESR browser, go to a channel, and open it with NewPipe by clicking the Android icon on the right side.
Alternatively, you can do this by sharing the url via the burger menu.

This is more or less the same as #3608 

### Expected behavior

Open the channel page to see the latest videos.
Just click the channel name to go view the channel.

### Actual behaviour

NP opens the latest video automatically, clicking the channel name from the video player doesn't open the channel page.

### Example Link 
[https://m.youtube.com/user/Mozilla](https://m.youtube.com/user/Mozilla)

**Comment by B0pol** [comment]
I can't reproduce with both Firefox and Firefox preview versions.

**Comment by allendema** [comment]
> I can't reproduce with both Firefox and Firefox preview versions.

Where do you land when u share the link with NP? 
Also, when you click the channel name inside the video player, top left side, it opens the channel page?

**Comment by B0pol** [comment]
<img src="https://user-images.githubusercontent.com/58657617/82492774-0cbc2080-9ae7-11ea-8839-25bb9ebec7ef.png" width="200">
I land here

And if you are talking about NewPipe player for the second question, it doesn't open channel page.

**Comment by allendema** [comment]
> I land here

 Somehow at my side it automatically opens the latest video, i don't recall changing any setting about that.
> And if you are talking about NewPipe player for the second question, it doesn't open channel page.

Yes, opening the channel page from top left side would be a very handy feature.

**Comment by Stypox** [comment]
What have you selected as "Preferred 'open' action" in "Video & audio" settings? If you have selected "Video player", obviously the video player starts when opening links and this is the expected behaviour

**Comment by allendema** [comment]
Great, that was it @Stypox
