### ISSUE TITLE
ReCAPTCHA challenge loads a blank page

### ISSUE THREAD

**Issue by arnoldsecret** [TeamNewPipe/NewPipe#3626]
### Version

- 0.19.3

### Steps to reproduce the bug
Load any video, ReCAPTCHA challenge requested, loads nothing at all.

### Expected behavior
ReCAPTCHA loads.

### Actual behaviour
Nothing happens.

### Screenshots/Screen recordings
![Screenshot_20200521_121851](https://user-images.githubusercontent.com/41223243/82523136-d4a3f480-9b5d-11ea-8c56-5de5e6016d25.png)

**Comment by Stypox** [comment]
Could you capture a logcat of this happening via adb with a debug apk (e.g. this one from #3478)?

**Comment by arnoldsecret** [comment]
closed, it seems that the issue has fixed itself after a while, but it's something to take note of.

I cannot capture a logcat due to my phone not having root access.
