### ISSUE TITLE
Add option to hide videos with release date in the future from the feed

### ISSUE THREAD

**Issue by therichkid** [TeamNewPipe/NewPipe#3628]
**Describe the feature you want**
Some channels like NFL and MLB already announce videos in advance that then occur in the top of the "What's new?" feed without a possibility to watch them. The user then has to scroll down in order to go to the videos that were actually already released and are viewable.

An option to hide videos with a release date in the future would come in handy.

**Is your feature request related to a problem? Please describe it**
No.

**Additional context**

**How will you/everyone benefit from this feature?**
It is more convenient to see and watch the newest released videos.

**Comment by wb9688** [comment]
FYI use dedicated feed has that as side effect

**Comment by B0pol** [comment]
@wb9688 is right, you can use dedicated feed avaible in content settings. Plus, _[NewPipe does not have to be an airplane cockpit.](https://teamnewpipe.github.io/documentation/07_maintainers_view/#keep-it-streamlined)_

**Comment by therichkid** [comment]
Thanks, I did not know about this side effect. Using the dedicated feed is a viable workaround for me.
