### ISSUE TITLE
New logo really looks like that of German social services

### ISSUE THREAD

**Issue by Natureshadow** [TeamNewPipe/NewPipe#363]
The new logo looks a lot like that of the German "Agentur für Arbeit" (a bad substitute for social services):

https://de.m.wikipedia.org/wiki/Datei:Bundesagentur_f%C3%BCr_Arbeit_logo.svg

Maybe something can be done so it doesn't strike me every time I start it ;).

**Comment by zoff99** [comment]
dpulicate of #266

**Comment by theScrabi** [comment]
Ow boy xD. Well that reminds me I should do some work :P
