### ISSUE TITLE
[Feature Request] Allow Android TV/FireTV users to update Github version with remote

### ISSUE THREAD

**Issue by Pentaphon** [TeamNewPipe/NewPipe#3630]
#### Describe the feature you want
I want to be able to upgrade Newpipe on my FireTV or Android TV with just my remote, similar to the way https://smartyoutubetv.github.io does it. 

#### Is your feature request related to a problem? Please describe it
There's currently no way to update Newpipe with the TV GUI without having to install it manually from Github via a browser or F-Droid which is not TV-friendly, so it would be nice to make it easy for Newpipe TV users to update their Newpipe using just their remote. 

#### Additional context
https://smartyoutubetv.github.io can already do this. When the app is opened and it detects a new upedate, it presents you with a changelog and offers to update the app or not to update. When you choose to update, it downloads the new version from Github and opens up an install prompt, which you can confirm with just your remote. 

#### How will you/everyone benefit from this feature?
Everybody with a FireTV or Android TV box will be able to update their Newpipe just as easily as they already can on their phone, except by using their remote control. This is especially helpful when Google changes something on their end, so we can get a quick fix without going through the hassle of installing the new version manually with a browser.

**Comment by B0pol** [comment]
See https://github.com/TeamNewPipe/NewPipe/pull/3141

**Comment by Pentaphon** [comment]
@B0pol that's different from a remote-compatible updater.

**Comment by B0pol** [comment]
No, it doesn't change anything. Read why it has been closed #3141. It doesn't change if you use android TV.
You could use [Firefox for Fire TV](https://github.com/mozilla-mobile/firefox-tv), it works great for android TV too. And you can watch [this issue](https://gitlab.com/fdroid/fdroidclient/-/issues/1430) for F-Droid

**Comment by Pentaphon** [comment]
@Stypox please confirm if this issue is not needed anymore because the issue B0pol referenced does not mention support for updating Android TV installs at all. We need to make sure both touchscreen and remote control users can upgrade their Newpipe.

**Comment by Stypox** [comment]
@Pentaphon as described in the issue pointed out by B0pol, we won't support in-app updating for various reasons (mainly to comply with regulations)

**Comment by Pentaphon** [comment]
Ah, fair enough then. I was confused since the latest version has an updater but I guess that updater is going away now and we will just rely our own F-Droid repo?

**Comment by Stypox** [comment]
The latest GitHub version only has a service that notifies the user if there is a new update available, but does not update anything on its own
