### ISSUE TITLE
Video Playback at 480p

### ISSUE THREAD

**Issue by Nzzyme** [TeamNewPipe/NewPipe#3631]
Hello,

I have been using NewPipe on my phone since the past few weeks and observed videos either don't play or play after a long delay when the default resolution set is 480p.

**Steps to reproduce**:
1. Open the app and search for anything
2. From the search results, tap on any video
3. The video page opens. Tap on the play button now.
4. The video won't play and the progress animation keeps rotating.

Note: For majority of the videos, it won't play in 480p resolution. However, when I change the resolution to a higher one (Ex: 720p), it plays immediately.

NewPipe version Installed: 0.19.3
Android Version: 6.0.1 MMB29M

Let me know if you need more information.

**Comment by gkeegan** [comment]
This issue has been around for months now and should have been a release-blocker when it was first known as an issue.

**Comment by Stypox** [comment]
#2415
