### ISSUE TITLE
[Feature Request] Support using Invidious as alternative server instead of Google

### ISSUE THREAD

**Issue by taminaru** [TeamNewPipe/NewPipe#3635]
With the recent privacy scandals authored by Google, I would like to cease my use of Google services and opt for privacy-focused services. Therefore, I believe adding [Invidious](https://invidio.us) support to your product would strengthen the open-source ideology behind your product, as you no longer make users rely on Google services. This would increase user-privacy and the open-source spirit pioneered by NewPipe, as Invidious is open-source software.

However, I appreciate the work being done with NewPipe, and I can't wait to see what the future brings. ❤︎

**Comment by B0pol** [comment]
#1867

**Comment by taminaru** [comment]
Ah, I see... sorry for not searching if this issue was already made.
