### ISSUE TITLE
Q gesture

### ISSUE THREAD

**Issue by SkiZo1** [TeamNewPipe/NewPipe#3638]
![Screenshot_20200523-183344~2](https://user-images.githubusercontent.com/60398971/82737979-17172e00-9d24-11ea-928a-9b47f5ab244d.jpg)
App triggering the seekbar when using fullscreen gestures Q magisk module 

Here is the video describing my problem, as the English language is not my native language
 https://drive.google.com/file/d/18GieWS18dA5qw_kJPbmP79Kp0uZVFHyb/view?usp=drivesdk

Thanks in advance.

**Comment by Stypox** [comment]
Follow the issue template and provide more information

**Comment by opusforlife2** [comment]
Closing until @SkiZo1 replies.
