### ISSUE TITLE
"Copy link" option when clicked on "Share" option

### ISSUE THREAD

**Issue by alittlebitofit** [TeamNewPipe/NewPipe#3640]
#### Describe the feature you want

I think it would be nice if you add "Copy link" feature when clicked on "Share".

#### Is your feature request related to a problem? Please describe it

I was typing in a 'XYZ' chat in WhatsApp and then I went to a video in NewPipe.
I clicked on Share button, and selected WhatsApp and then selected that 'XYZ' chat to share the link with.
Now that  'XYZ' chat is open with the YouTube link in the chat box.
But the previously typed text is gone.
So it'd be better if I could copy the link and manually paste in between the message I was typing.
This way I won't have to retype the whole text.

#### How will you/everyone benefit from this feature?

This feature will help us copy the link and paste it in notepad/memo too.

**Comment by B0pol** [comment]
We are using default android share menu. Normally you should have a clipboard option in this menu.
If not, install an app to share to clipboard (E.g.  [this app](https://f-droid.org/en/packages/com.tengu.sharetoclipboard/))
This isn't within our remit.

**Comment by alittlebitofit** [comment]
Ah thanks for the alternative. :)
