### ISSUE TITLE
"Start playing in full screen" & "Enqueue playing in full screen" option in playlist

### ISSUE THREAD

**Issue by alittlebitofit** [TeamNewPipe/NewPipe#3641]
#### Describe the feature you want

I think it would be nice if you add "Start playing in full screen" & "Enqueue playing in full screen" feature in playlist.

#### Is your feature request related to a problem? Please describe it

Right now there's an option to `Enqueue in a new popup` and `Start playing in a new popup`.
But I would like to have an option where it allows me to play the playlist from any video in full screen.

#### How will you/everyone benefit from this feature?

This feature will save the extra step by first playing in popup and then continuing in full screen.

**Comment by Stypox** [comment]
#2510

**Comment by alittlebitofit** [comment]
Thx!
