### ISSUE TITLE
Limited time ads-free implementation

### ISSUE THREAD

**Issue by ondernuray** [TeamNewPipe/NewPipe#3643]
You deserve make money. Your application is best. You can add thin ads page bottom of application and lets users, if they watch 30 seconds ads, then they can use application 24 hours ads-free.

Thanks
Onder

**Comment by Stypox** [comment]
No. It would be against I don't know how many copyright laws (because of the usage of youtube's content without permission to make money), and totally against the free-and-open-source-software way of thinking

**Comment by 71walceli** [comment]
Not only that, but a user could also support their favorite YouTubers by watching their ads. One might also get useful ads that can actually offer a discount is some other benefits both to NewPipe devs, to YouTubers and even the users.

**Comment by Stypox** [comment]
@71walceli see #1819

**Comment by B0pol** [comment]
You can donate here https://newpipe.schabi.org/donate/

On top of @Stypox comment, adding any ads would add another antiFeature flag to NewPipe on F-Droid : [Ads](https://f-droid.org/wiki/page/Antifeature:Ads).

**Comment by ingingin** [comment]
Please close this issue. Its making me literally sick thinking how people can even mention the implementation of ads like any other malware/adware apps you find on the Play Store.

**Comment by TheAssassin** [comment]
@ingingin I think these people are maybe just not educated well enough in terms of the spyware problems arising from advertising stuff. Also, there _are_ non-privacy-invasive ways to advertise, e.g., RTD's ethical advertising project.

Generally this kind of thinking does not match our project's vision and mission. @ondernuray @71walceli there shall never be any form of advertising in this project. It is not our intent to make money from this work, and it would not comply with our privacy goals.

Therefore, closing this issue. Please refer to our donation page if you want to support and sustain NewPipe's development.
