### ISSUE TITLE
Option to convert to MP3

### ISSUE THREAD

**Issue by wayneLaw1** [TeamNewPipe/NewPipe#3645]
#### Describe the feature you want

Option to convert to MP3 when downloading sound only.

#### Is your feature request related to a problem? Please describe it

Some YouTube channel supply M4a that cannot be read on some music players

#### How will you/everyone benefit from this feature?

MP3 is the most used music format and can be played on all media/ system so no post conversats needed 🙂

**Comment by B0pol** [comment]
Search mp3 on the issue tracker
