### ISSUE TITLE
reporting bug through email do not attach the actual exception details to the email's body (sharing the report to the email works though)

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3647]
![GIF-200525_052714](https://user-images.githubusercontent.com/415238/82772788-f268a680-9e48-11ea-9458-2f1e5f7744ec.gif)
  
an alternative work-around is clicking the top left share button and choosing 'email', which works fine in putting the content in the email's body, but it does not fill-in the actual email addresses, for reporting the bug, of course...

**Comment by wb9688** [comment]
It used to work for Gmail and it still works for Outlook. Anyway, I've already fixed this in #3580.
