### ISSUE TITLE
[feature request] improve message to users when channel has no public videos to display

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3648]
see https://github.com/TeamNewPipe/NewPipe/issues/3646#issuecomment-633343361

I'm not sure if this should be a feature request or a bug report though...

**Comment by Stypox** [comment]
The error message seems correct to me: those kind of channels are not yet supported by NewPipe.

**Comment by eladkarako** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/3646#issuecomment-633536819
