### ISSUE TITLE
[feature request] parse channel's public playlists

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3649]
Although one can search for playlists (if their name is known), currently scraping/parsing/displaying channel's public playlists is not supported.  

Users do not always know the name of the playlist, so since NewPipe supports registering to playlists, my work-around is browsing through the channel's content on the official YouTube app, then sharing a playlist from the official YouTube app to NewPipe to watch it. 

Discovering channel's public playlists is a great feature to have, making NewPipe closer to a YouTube app alternative, and making more content available "organically" (meaning through using just NewPipe itself) for the users,
since some channels are exclusively publishing content into playlists, skipping the public section or avoiding the direct discovery of videos by setting videos' visibility (when uploaded to YouTube) as "unlisted" and adding them to a public playlist, as a way to keep the channel's content more organised (some publishers upload videos in weird times and  schedules that do not always make sense, but then organise them in playlists in their correct timeline).

see https://github.com/TeamNewPipe/NewPipe/issues/3646#issue-623998886  
for an example for such channels.

**Comment by wb9688** [comment]
Also a duplicate, please search for existing issues first.

**Comment by eladkarako** [comment]
possibly,
but I haven't found one in the first four pages of 
https://github.com/TeamNewPipe/NewPipe/issues?page=2&q=is%3Aissue+is%3Aopen+playlists  
or any of the results in  
https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aopen+public+playlists  
it might be a closed one or tagged with other keywords. 
🤷‍♂️

**Comment by eladkarako** [comment]
main dup. is https://github.com/TeamNewPipe/NewPipe/issues/2414
