### ISSUE TITLE
Can't play or download specific video

### ISSUE THREAD

**Issue by Pronian** [TeamNewPipe/NewPipe#365]
The video in question is  [Rihanna - Needed Me (Slightly NSFW)](https://www.youtube.com/watch?v=wfN4PVaOU5Q)

All other videos that I tried work great, but this one fails. Maybe it has something to do with age restricted content, but the video still fails regardless of the age restriction setting.

NewPipe version: 0.8.5
Android version: 6.0
Phone: LG G4 H-815

**Comment by theScrabi** [comment]
That should not be the case. Can you tell me what exactly is happening?

**Comment by theScrabi** [comment]
Well for me even fails to get any stream.

**Comment by Pronian** [comment]
Pressing play on the video open the internal player with a "Can't play this video" message (http://i.imgur.com/7x16zBZ.png). Trying to download it simply puts a new entry in the downdoads page with the title "Error", without creating any kind of file in the downloads folder.

I tried to view the link that's generated by NewPipe by opening the video with VLC, but I'm afraid the link is cropped out by the VLC interface for being too long http://i.imgur.com/wpq8mgk.png

**Comment by theScrabi** [comment]
Of course this is a but, but you could try to get around it by using tor.
