### ISSUE TITLE
[Meta] NewPipe subreddit

### ISSUE THREAD

**Issue by snappyapple632** [TeamNewPipe/NewPipe#3651]
NewPipe currently has a semi-official subreddit that seems to have fallen out of date. It seems that there is only one moderator, which is @wb9688 . I'm pointing this out because the subreddit has around 750 concurrent viewers, and I feel that it should be more composed if it is to grow, and having only one mod is a bad idea.

I would like to volunteer to be a moderator because I want to get started in community management as a career and that I have been active in this community for some time now, I would like to contribute more to the project (beyond some of the documentation). Learning CSS and general moderation are my main goals.

**Comment by theScrabi** [comment]
I'm on this sub from time to time
I can't see why not. Who is currently responsible for it?

**Comment by snappyapple632** [comment]
It seems like wb9688 is the only mod on the list. The last online date says 23 days ago, but he is active on various help threads.
![Capture](https://user-images.githubusercontent.com/40573129/82951351-d6095e80-9f5b-11ea-8af9-c915acf59eea.PNG)

**Comment by wb9688** [comment]
The subreddit is unofficial and wasn't even created by me, though I'm active on there and asked the creator to add me as a mod, which he did.

**Comment by snappyapple632** [comment]
Right, but the creator hasn't been online in two months. On a slight chance, do you have the permissions to make others mods @wb9688 ?

**Comment by wb9688** [comment]
It looks like the original creator left and I do in fact have full permissions.

**Comment by snappyapple632** [comment]
Hmm... If he did leave, we may have to post on r/RedditRequest to gain ownership of the subreddit, but that is something we have to discuss with the lead devs.

**Comment by TobiGr** [comment]
I think this is a good idea.

**Comment by snappyapple632** [comment]
Any objections? If we're clear, then I will PM wb9688 to promote me to mod.

**Comment by snappyapple632** [comment]
@wb9688 you will receive a PM from u/NewPipe_snappyapple with the subject line "NewPipe Moderator", which is me. Please promote that user to moderator. Thank you.

**Comment by snappyapple632** [comment]
It has been done.
