### ISSUE TITLE
Import YouTube subscription directly into NewPipe via "complete action using"

### ISSUE THREAD

**Issue by tbm** [TeamNewPipe/NewPipe#3652]
#### Describe the feature you want

I wanted to import my YouTube subscription. I went to "Subscriptions", "Import from YoutTube" and got the helpscreen with the URL to click.

I clicked on the URL and Android opened a screen "Complete action using" with two options:

* Download (Firefox logo)
* Add Podcast (AntennaPod logo)

Would it be possible to get NewPipe listed there as an option, or would that mean subscribing to some Android API that you can't use?

#### How will you/everyone benefit from this feature?

Makes it easier to import subscription.

**Comment by Stypox** [comment]
Newpipe would have to open a webview, having you login to your yt account, retrieving the download files and then using it. It would mean that you would need to look up for the password, etc. So this is not an option imo

**Comment by tbm** [comment]
Thanks for the explanation. That makes sense.

I'm not sure what a webview is.  Would that use the user's default browser?  I wonder if there's a way to use the default browser (where someone is likely logged in already) to download the file and then for Newpipe to import that file.  That would avoid the manual step of loading the file.

If this is not possible, maybe NewPipe could look in the download folder to see if the file is there now.  i.e. I click on the URL, use my browser to download, click "OK" in NewPipe and NewPipe says "oh look what I found in Downloads, let's load that".

I have no idea about Android development and if any of these ideas makes sense in an Android context, but I'm just trying to find ways to avoid the manual import step.

But if it's not possible, just close this ticket.  People won't do import very often anyway.

**Comment by B0pol** [comment]
A webview is provided by the system, it's a sort of the minimum function required to browse internet. It is possible to use them in an app (we do that for the reCAPTCHA challenge for example). It's not possible to use default browser in app, but we can open it, thus the user will quit the app.

I don't think it's good to search in Download folder. That would mean NewPipe will see what files we have in Download folder, sort to find the good file format… Even if it's only local and nothing is sent on internet, it's not something I'd like personally.

**Comment by tbm** [comment]
well, I doubt there are many opml files in `Download`, but I think you guys are much more privacy conscious than I am.

Feel free to close.
