### ISSUE TITLE
[Feature Request] 10 seconds fast rewind/forward buttons an Android TV.

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#3653]
Feature Request: 10 seconds fast rewind/forward buttons an Android TV.

**Comment by ondernuray** [comment]
Will we see this minor improvement in next releases?

**Comment by Jurijnator** [comment]
I dont know if this will be the same feature which I like to have, because I have no AdroidTV. But I want a fast forwad/reqind button for playing videos in the background. Or should I open a knew issue for that request?

**Comment by opusforlife2** [comment]
@Jurijnator You can select those buttons in the Settings in the Notification menu.

**Comment by Jurijnator** [comment]
I do not find that option. I do not find the Notification settings in the App. And no option for those buttons in the Notification settings of my android os

**Comment by opusforlife2** [comment]
@Jurijnator Update to the latest version.

**Comment by Jurijnator** [comment]
@opusforlife2 Thank you. I checked F-Droid for updates before, but F-Droid was not up to date. It confusing for me that I have to uncheck them for the fast forward feature. I would suggest Radio Buttons for that setting. What do you think?

**Comment by opusforlife2** [comment]
@Jurijnator Tap on the entries anywhere except the check boxes. You can select which button should have what action.

**Comment by Jurijnator** [comment]
@opusforlife2  Thank you again. Now it is like I want to have it. Maybe it should be marked, that it can be clicked or a dropdown where you could choose one of those actions or nothing. The text above describes what I have to do. But I did not read it :D

**Comment by beccare** [comment]
I find this 10 seconds rewind already implemented in 20.4.
But I would suggest _3 seconds_, since when you do not understand a particular word/sentence, in practice 10 seconds are to long a wait if you need repeating it a few times.

**Comment by zubayy** [comment]
#6985 fixes this issue, as the dpad on an Android TV remote skips forward/backwards 10 seconds at a time.

**Comment by litetex** [comment]
Closing this as it's fixed by #6985

@zubayy 
Thank you for find the related issue 😄
