### ISSUE TITLE
update public invidious instances

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3654]
Remove down instances, add new ones, for v0.19.4 version

https://github.com/omarroth/invidious/wiki/invidious-instances

**Comment by B0pol** [comment]
It seems like they are all down (blockedqby Google), let's wait.

**Comment by TheAssassin** [comment]
There's an API on invidious's homepage that you could use, too. A manual refresh button might do.

**Comment by ingingin** [comment]
What does this issue do? Are you @B0pol adding Invidious to NewPipe :D

**Comment by B0pol** [comment]
> There's an API on invidious's homepage that you could use, too. A manual refresh button might do. https://instances.invidio.us/

We cannot update dynamically instances in NewPipe because it has to be hardcoded in manifest.xml. However we can dynamically allow invidious instances in NewPipeExtractor, that's why I've opened https://github.com/TeamNewPipe/NewPipeExtractor/issues/334.
And fetching instances.invidio.us would be a bad idea imo, wiki is more often updated. instances.invidio.us is great for some info, I also like https://uptime.invidio.us/
but the thing is instances.invidio.us lists only public instances, whereas if we do a call to the invidious api and get a good answer, we could use it in newpipe (private instance for example).
