### ISSUE TITLE
I'm tired of this bug, GO TO HELL

### ISSUE THREAD

**Issue by DialexG91** [TeamNewPipe/NewPipe#3655]
![Screenshot_2020-05-27-00-33-59](https://user-images.githubusercontent.com/43056994/82981639-0bee2780-9fdc-11ea-8402-217449c755f6.png)

**Comment by Stypox** [comment]
Do you really think that by being rude you will obtain something? Or are you just trying to troll? If that was your intent, yeah, you made me facepalm ;-)
