### ISSUE TITLE
live stream video playing in full hd

### ISSUE THREAD

**Issue by MrRobotGOD** [TeamNewPipe/NewPipe#3664]
when i play live stream video there is no option for resolution change and even i set normal resolution 240p and mobile data limit 240p its playing in full hd
i am using latest v0.19.3
here is screen shot
https://imbt.ga/PCiYL6gdxS
play any live stream video there is no resolution change option available

**Comment by B0pol** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1239
