### ISSUE TITLE
Option to disable removal of unplayable streams from current playlist

### ISSUE THREAD

**Issue by micah-k** [TeamNewPipe/NewPipe#3665]
#### Describe the feature you want

The automatic removal of streams that could not be played from a playlist is a feature I can see many people using, as it streamlines usage for most people in the event that a video is no longer listed and prevents them from having to manually troubleshoot playback. However, I live in an area with terribly spotty internet and cell service, and very frequently when listening to playlists of 100+ shuffled songs I will hit a dead spot in my connection between songs, and open my phone after a period of silence to find it rapidly deleting every remaining song in the playlist in sequence. This is usually followed by me having to find a song that the app still thinks is playable and will let me pause on, and then depending on the extent of the damage either wrack my brain to figure out what's gone missing or just give up and reshuffle through dozens of already played songs. Having the ability to disable the automatic removal of unplayable streams would allow me time to troubleshoot on my own, especially in cases where this happens while I'm driving and by the time I can pull over into a parking lot and fix things the playlist has entirely emptied.

**Comment by B0pol** [comment]
The removal of unplayable tracks is a feature, it't there if there was some trouble with the track and it should not be changid. What has to be done is to fix the issue causing that, and it has been done. See #3576

**Comment by micah-k** [comment]
The issue you linked is only one example of a much larger list of playback errors for me; as I stated previously this occurs on a regular basis whenever I lose connection. If you somehow have a way to fix my local cell reception I'm all ears, but as it stands a "feature" to empty my playlist when I lose connection is not desirable and the only programmatic solution is an option to disable this "feature."
