### ISSUE TITLE
Bug with views

### ISSUE THREAD

**Issue by piNot3** [TeamNewPipe/NewPipe#367]
Hi! Love your app!
I want to report a bug. The app shows X views instead of XK or XM.
- [ x ] I carefully reed the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x ] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
When and where? Can you give an example.

**Comment by piNot3** [comment]
Yeah, for sure. [A picture is worth a thousand words
](prnt.sc/cvsby9)

**Comment by piNot3** [comment]
Have no more problems. Weird.

**Comment by theScrabi** [comment]
Hm strange. Well maybe god did bit flipping again xD.
