### ISSUE TITLE
Play next in queue

### ISSUE THREAD

**Issue by ariel-moczulewski** [TeamNewPipe/NewPipe#3672]
I think there should be an option in the longpress menu to play a video after the one currently playing both with popup and background player.

Would be useful with a long queue.
Thanks

**Comment by Stypox** [comment]
This can already be done: `Enqueue on background player`

**Comment by wb9688** [comment]
@Stypox: No. That adds it as the last item in the queue, not as the next item in the queue.

**Comment by Stypox** [comment]
#4136
