### ISSUE TITLE
Youtube links dont work throws an exception

### ISSUE THREAD

**Issue by tbunday** [TeamNewPipe/NewPipe#3674]
![Screenshot_20200529-210437](https://user-images.githubusercontent.com/66148538/83315753-20a30900-a1f0-11ea-8e4d-5685ae84ae5c.png)
{
   "user_action": "requested stream",
   "request": "https:\/\/youtu.be\/Dgs2SYBPKMI",
   "content_language": "US",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.14.1",
   "os": "Linux lge\/cv5a_lao_com\/cv5a:9\/PKQ1.190522.001\/19323113853f4:user\/release-keys 9 - 28",
   "time": "2020-05-30 01:04",
   "exceptions": [
      "org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function \n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:725)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:598)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:48)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:55)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3$ExtractorHelper(ExtractorHelper.java:113)\n\tat org.schabi.newpipe.util.ExtractorHelper$$Lambda$3.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4073)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14349)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4073)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3310)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \";([A-Za-z0-9_\\$]{2})\\...\\( inside of var mea=function(a){a=a.split(\"\");var b=[function(c,d){d=(d%c.length+c.length)%c.length;c.splice(d,1)};\"\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:65)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:713)\n\t... 30 more\n"
   ],
   "user_comment": ""
}

**Comment by gkeegan** [comment]
Update NewPipe.

**Comment by tbunday** [comment]
It's already updated to 14.1

Sent from Yahoo Mail on Android 
 
  On Fri, May 29, 2020 at 9:12 PM, Keegan<notifications@github.com> wrote:   


Update NewPipe.

**Comment by gkeegan** [comment]
The latest version is 0.19.4???

**Comment by tbunday** [comment]
What?  Fdroid says 14.1 is the current and legacy its 18.6. I have both neither one work correctly.  Anything newer I assume is not in the repository.

Sent from Yahoo Mail on Android 
 
  On Fri, May 29, 2020 at 10:19 PM, Keegan<notifications@github.com> wrote:   


The latest version is 0.19.4???

**Comment by gkeegan** [comment]
Weird that it isn't showing. Here's a direct link to 0.19.3's apk from F-Droid. You can sideload it. 

https://f-droid.org/repo/org.schabi.newpipe_930.apk

**Comment by Byebyesky** [comment]
On my device 19.3 is also broken with a few videos.
19.4 from the github fixes that issue though.

**Comment by gkeegan** [comment]
Yeah 0.19.3 is currently not ideal so you'll have to either switch to GitHub version (make sure to backup data) or wait for F-Droid to get 0.19.4.
