### ISSUE TITLE
New & hot in soundcloud doesn't work and Top 50 redirects to New & hot

### ISSUE THREAD

**Issue by surrodox2001** [TeamNewPipe/NewPipe#3676]
When I open New & hot in soundcloud with the latest version (0.19.4), I get a no videos screen and sometimes a error occured message:

![Screenshot_2020-05-30-09-36-19](https://user-images.githubusercontent.com/49476868/83316770-84fab280-a25a-11ea-83c3-0d48b29a02b2.png)

[﻿{_user_action___requested kiosk_,_reque.txt](https://github.com/TeamNewPipe/NewPipe/files/4704912/_user_action___requested.kiosk_._reque.txt)

The issue doesn't occur with older versions as far as I can tell.

**Comment by wb9688** [comment]
I could confirm that issue, and it also happens for e.g. PeerTube.

Error occured for SoundCloud isn't a new issue though.

**Comment by surrodox2001** [comment]
> Error occured for SoundCloud isn't a new issue though.

Can iterate on that?
