### ISSUE TITLE
Channel tab enhancement, playlist and networked channels

### ISSUE THREAD

**Issue by sh3zb0t** [TeamNewPipe/NewPipe#3678]
#### Describe the feature you want

Ability to see youtube channels tabs like playlists or to see networked channels that this user recommends/are similar like you can on actual youtube app 
#### How will you/everyone benefit from this feature?

Mobile users could find playlists more easily, share them or enqueue to their currently playing playlists just from the channels page, the networked channels thingy could help explore new content and could help to leave official youtube app completely.

**Comment by Stypox** [comment]
#2414
