### ISSUE TITLE
BEST youtube player ever!! what a dream - this is a must have app!

### ISSUE THREAD

**Issue by 2SI3NX** [TeamNewPipe/NewPipe#368]
Sorry for posting this under issues, but i wanted to send my appreciation for this app.

When i discovered NewPipe, i never expected it to be so lightweight and easy to use and most of all, so SIMPLE.
No account registrations needed, it plays every video through Shazam as well, Youtube is NOT EVEN NEEDED anymore. how amazing??!!

Thank you so much for creating this open source software!! i love you! keep up the good work guys.

**Comment by piNot3** [comment]
I also want to say thank you to the team and your awesome job!

**Comment by theScrabi** [comment]
:) Thats awesome. Still nice to hear that people appreciate my shady work :P

**Comment by mueller-ma** [comment]
I love the dedicated "play with kodi" button
