### ISSUE TITLE
v0.19.4 - [Bug] Video lengths are not correct on channel view

### ISSUE THREAD

**Issue by ondernuray** [TeamNewPipe/NewPipe#3681]
![image](https://user-images.githubusercontent.com/58657617/83321376-8672ad80-a24f-11ea-98fa-3ba3a712f8d3.png)
![image](https://user-images.githubusercontent.com/58657617/83321382-92f70600-a24f-11ea-9d56-690116600fb9.png)
https://invidio.us/channel/UCkwHQ7DWv9aqEtvAOSO74dQ

Thanks
Onder

**Comment by Pentaphon** [comment]
Yep, this happens with every long video.
