### ISSUE TITLE
Autoplay next stream toggle only appears in YouTube

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3684]
### Version

- 0.19.4

### Steps to reproduce the bug

1. Go to any PeerTube / SoundCloud stream
2. If you were on comments, switch to related streams

### Expected behavior

I can see this, and toggle autoplay next stream easily without needing to go in settings.
![Screenshot_20200530-100325_NewPipe_1_1](https://user-images.githubusercontent.com/58657617/83323126-094e3500-a25d-11ea-8f0a-143cbeec806d.png)
### Actual behaviour

The toggle is not available

**Comment by wb9688** [comment]
That's because only YouTube has a separate next stream and related streams. We should just prepend the next stream to the related streams, drop the separate next stream thing and use the related streams in NewPipe.
