### ISSUE TITLE
The file can't be created when downloading Youtube videos.

### ISSUE THREAD

**Issue by albertpinto9** [TeamNewPipe/NewPipe#3686]
![Screenshot_20200530-160015](https://user-images.githubusercontent.com/66164366/83326147-2ac81480-a28f-11ea-831a-8a2fd71fea2e.png)
app version-19.4
Android version-10

**Comment by wb9688** [comment]
Enable SAF or wait for v0.19.5

**Comment by cesarmoi** [comment]
hello team

about the last version 0.19.4 is not worked on the most phone as Huawei and Samsung that have version android 10 the major problem the old version are nt still worked also .

hope find solution as soon as possible
![WhatsApp Image 2020-05-30 at 17 14 52 (3)](https://user-images.githubusercontent.com/25723596/83336158-6bd12080-a2b1-11ea-806e-a109cbb92706.jpeg)

**Comment by CodeSandwich** [comment]
@cesarmoi After enabling SAF have you changed the download directory? You must do it so NewPipe can request permission from the OS to write there.

**Comment by Stypox** [comment]
Install 0.19.5

**Comment by freshmre** [comment]
Had this problem after I deleted the folder NP was set to save the downloads to.
Recreating the folder or changing "Video download folder" in Settings -> Download to an existing folder solves the problem.
