### ISSUE TITLE
Wrong duration of the video on trend page

### ISSUE THREAD

**Issue by zervankoru** [TeamNewPipe/NewPipe#3688]
I am using latest 0.19.4
Open trends for Russia and the problem is in SpaceX video, it's duration is different in trends and if you just open it.
Also providing screenshot of official Youtube app.
![Screenshot_20200530-144410712](https://user-images.githubusercontent.com/39313092/83327508-24349f80-a285-11ea-883d-f7d64d60b64e.jpg)
![Screenshot_20200530-145100925](https://user-images.githubusercontent.com/39313092/83327515-2bf44400-a285-11ea-9d5e-6d9f870dc99b.jpg)
![Screenshot_20200530-144455233](https://user-images.githubusercontent.com/39313092/83327520-31518e80-a285-11ea-9f56-8239ef306479.jpg)

**Comment by Stypox** [comment]
Fixed, see #3681
