### ISSUE TITLE
RSS bug

### ISSUE THREAD

**Issue by marteaurouge** [TeamNewPipe/NewPipe#369]
Some channels RSS are not usable on Newpipe (you can't click on the RSS button, to send the url to your aggregator).

Explanation: Youtube is using two kind of RSS feeds, depending on your channels name:
- if your channel's name is not set, the syntax is:
  https://www.youtube.com/feeds/videos.xml?channel_id=CHANNEL-ID
- if your channel's name is set, the syntax is (both works)
  https://www.youtube.com/feeds/videos.xml?user=username
  or https://www.youtube.com/feeds/videos.xml?channel_id=channelid 

Example with NBC News (username is set, both RSS work):
https://www.youtube.com/feeds/videos.xml?user=NBCNews
https://www.youtube.com/feeds/videos.xml?channel_id=UCeY0bbntWzzVIaj2z3QigXg

How to check for this? just go to a channel, and open the "videos'' tab,
you'll either get:

https://www.youtube.com/user/USERNAME-HERE/videos
or
https://www.youtube.com/channel/CHANNEL-ID-HERE/videos

So Newspipe at the moment is only managing the RSS if the channel has a username set.

Example of a channel with no username set: https://www.youtube.com/channel/UCFIrTpC6LJDqzPMeBfgAGrQ/videos (RSS won't work on Newspipe)

**Comment by aladar42** [comment]
Just wanted to pop in and say I would appreciate this bug being looked at very much. Thank you. :)

**Comment by mauriciocolli** [comment]
This issue is related to the [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor).
