### ISSUE TITLE
Sugerencia Funcionalidad

### ISSUE THREAD

**Issue by DavidCLuna** [TeamNewPipe/NewPipe#3694]
Hola a todos. 
Me encanta esta app, pero qué tal si se puede programar apagados automático, como spotify, me acuesto a dormir y pongo que e apague la música dentro de 10 minutos, sería genial

**Comment by wb9688** [comment]
Speak English please

**Comment by TobiGr** [comment]
Translated via [Deepl](https://www.deepl.com/translator#es/en/Hola%20a%20todos.%0AMe%20encanta%20esta%20app%2C%20pero%20qu%C3%A9%20tal%20si%20se%20puede%20programar%20apagados%20autom%C3%A1tico%2C%20como%20spotify%2C%20me%20acuesto%20a%20dormir%20y%20pongo%20que%20e%20apague%20la%20m%C3%BAsica%20dentro%20de%2010%20minutos%2C%20ser%C3%ADa%20genial):

> Hi, everybody.
> I love this app, but what if you could set it to turn off automatically, like spotify, go to sleep and turn the music off in 10 minutes, that would be great

See #2892
