### ISSUE TITLE
Allow duplicating playlists created by other users

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#3695]
#### Describe the feature you want

Say some user has made a public playlist. I want to duplicate that playlist so that I get all the videos if that playlist, *and the ability to edit it*
#### Is your feature request related to a problem? Please describe it

I have bookmarked a 200 video playlist and want to watch the whole playlist. Say I reach the 50th video, then I have to scroll ALL the way down to watch that.

With this feature, I will just duplicate the playlist and keep removing videos after watching them.
#### How will you/everyone benefit from this feature?

I personally have a lot of long playlists as I am currently preparing for an exam. This feature will a lot of my time, and will allow me to concentrate my time on watching, instead of preparing to watch.

**Comment by Stypox** [comment]
As a workaround you can enqueue the whole playlist in the background, then open the queue and scroll down untill every video in the playlist is shown, and then press the "save queue to playlist" button

**Comment by B0pol** [comment]
wait what??? where is this button? can you pick a screenshot?

**Comment by wb9688** [comment]
@B0pol: At the top, before the mute button

**Comment by nikhilCad** [comment]
After unified update, the method by @Stypox no longer works. Though my exam is done now so I don't need it but still.........

**Comment by Stypox** [comment]
@nikhilCad for me it still works: just load the whole playlist, then enqueue it all and then save it.

**Comment by nikhilCad** [comment]
This is fixed now

**Comment by mhmdanas** [comment]
This was added in https://github.com/TeamNewPipe/NewPipe/pull/7355, if anybody wants to know.
