### ISSUE TITLE
Feeds are always outdated

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [TeamNewPipe/NewPipe#3696]
### Version

-
19.05
### Steps to reproduce the bug

1. Go to settings,content and set feed threshold to always update
2. Do not enable fetch from dedicated fieldd
3. Restart the app

### Expected behavior

Feed should be updated after restart
### Actual behaviour

Feeds do not get updated

**Comment by B0pol** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3329

Always update means you can always press the refresh button, not it will do it automatically.

**Comment by Ashutosh-Kukreti** [comment]
This issue was not present in old version with old layout , feeds used to get updated automatically on startup,Why did you guys removed that feature? :(
