### ISSUE TITLE
Additional Donate option - playstore

### ISSUE THREAD

**Issue by John3** [TeamNewPipe/NewPipe#3709]
#### Describe the feature you want

I know there is some issues involving playstore and Im pretty sure may not possible, but not sure if the team can add a "donate app" in playstore, like did the guy from "Simple Mobile Tools" in his app "com.simplemobiletools.thankyou" that actually do nothing.

#### Is your feature request related to a problem? Please describe it

Nop

#### Additional context

Is just an app that you buy, install, but do nothing, is for donation purpose.

#### How will you/everyone benefit from this feature?

Dunno other users, but for me sometimes friends/relative gift me money in google play, as you may know that money can't be cash out, so I donate that money. Maybe will be helpful for other people too and have that option to donate money, or if someone have a better idea.

**Comment by B0pol** [comment]
We are not using play store. Plus if we make such app, Google would eat 30% of the donations. Just look here: https://newpipe.schabi.org/donate

**Comment by test2a** [comment]
i would suggest adding more cyptos rather than just bitcoin because btc has the issue of high fees. Conversely, you can use something like coinpayments.net and they support payments from lots of currencies.

**Comment by John3** [comment]
> We are not using play store. Plus if we make such app, Google would eat 30% of the donations. Just look here: https://newpipe.schabi.org/donate

Yeah well, I get it, I know the other methods for donation, I was just asking 😅 😅 Either way is an alternative (for the non-paranoid), to be able to use that money inside gplay that some people may have or even will be easier for some to donate, not everyone know where to buy or how use btc.

Thanks 😃 great app 👍 
 
> i would suggest adding more cyptos rather than just bitcoin because btc has the issue of high fees. Conversely, you can use something like coinpayments.net and they support payments from lots of currencies.

Exactly I was thinking the same, to add other crypto, not just for the high fees but to avoid the hassle of convert to another crypto, adding the main ones not the shitty cryptos 😄 This should go in other issue, I will close this one.
