### ISSUE TITLE
invidio.us support for evading YouTube Tor Exit blocks

### ISSUE THREAD

**Issue by ctirxr** [TeamNewPipe/NewPipe#3710]
Hi I'm a big fan of Newpipe and I use it with Orbot. Google has been blocking Tor IPs and I run into CAPTCHAs almost every time. After a few minutes I get another captcha as the connection expires and goes through another Tor exit. The experience is unbearable. Please add official invidio.us support so we don't have to bother with Google's bullshit.

**Comment by B0pol** [comment]
Duplicate of #1867

**Comment by ingingin** [comment]
Omg you closed it right when I was going to comment lol. Anyways, #1867 and [#3612(Comment) ](https://github.com/TeamNewPipe/NewPipe/issues/3612#issuecomment-634916646)
