### ISSUE TITLE
Add streamable.com upload support

### ISSUE THREAD

**Issue by KonoromiHimaries** [TeamNewPipe/NewPipe#3712]

**Comment by Stypox** [comment]
*Please **follow the issue template** when creating an issue, don't just delete everything!* Anyway, NewPipe would never allow logging in to upload things, so this is not a valid service

**Comment by KonoromiHimaries** [comment]
> logging in to upload things

streamable doesn't require any account to upload 10min video fragment. that's not much but is perfect to send someone a fragment with a timestamp of the video.

YouTube originally allow sending link with timestamp, but NewPipe do not have that option

example
```
https://youtu.be/aqz-KE-bpKQ?t=241
```

**Comment by Stypox** [comment]
Open the video, seek to the timestamp you want to send, and press share in the menu
