### ISSUE TITLE
security problem!

### ISSUE THREAD

**Issue by cion49235** [TeamNewPipe/NewPipe#3715]
Do you guys know?

I would like to ask you how to solve the problem below. 

The app's Google Cloud Platform (GCP) API key is exposed.

org.schabinewpipe.extractor.services.youtube.YoutubeParsingHelper-><clinit>

**Comment by wb9688** [comment]
No

**Comment by TobiGr** [comment]
Hey @wb9688,
please explain a bit more. @cion49235 thank you for getting in touch. We use the YouTube’s website key to access the website api. It is changed from time to time and is mostly generated for one user when accessing the site for the first time (i.e. No cookies set) or when the old one is expired. So there is no key exposed.

**Comment by wb9688** [comment]
We don't have API keys of any service, and we aren't using GCP. In the class you mention, there are some hard-coded keys that are embedded in the HTML/JS of the service. There is code that checks whether the hard-coded keys are still valid, and if not, try to retrieve a new key.

You also shouldn't disclose security issues publicly, but send an e-mail privately to our team. Only if we don't respond in a reasonable amount of time, it would be appropriate to make the issue public.

**Comment by mohamedkhaledalizayed** [comment]
i have the same issue 
any suggestions?
![WhatsApp Image 2023-04-11 at 8 53 20 PM](https://user-images.githubusercontent.com/27522640/231328781-f679066f-9cd1-467e-a653-5773b158e029.jpeg)
