### ISSUE TITLE
Allow sharing video url with timestamp query parameter

### ISSUE THREAD

**Issue by personaaleatoria** [TeamNewPipe/NewPipe#3717]
First thanks for the great software!! :)

I see youtube desktop allows for sharing the video url and attach a timestamt with the number of seconds as a query parameter like these:

`https://youtu.be.com/&v=asdfg?t=60` or something like that..

Meaning when the user clicks the shared link the video will start right away from second 60.

The official youtube app does not allow for this feature so I have to turn Desktop mode in the mobile browser to do that (disappoint) :( 

This is youtube giving a bad user experience to mobile users :) and I think newpipe can fix that

Hope you consider!

**Comment by personaaleatoria** [comment]
Scenarios

- I share a timestamped url from mobile with newpipe to a desktop youtube user.
- I share a timestamped url from mobile with newpipe to a mobile official app user.

**Comment by wb9688** [comment]
It's already possible: in the main player, go to the timestamp you want and tap on share

**Comment by personaaleatoria** [comment]
Amazing, I've just updated. thanks!
