### ISSUE TITLE
Show upload date on video screen 

### ISSUE THREAD

**Issue by Nowaker** [TeamNewPipe/NewPipe#372]
It seems to be done for search results in https://github.com/TeamNewPipe/NewPipe/issues/23. But when I open a video link from a different app, I only see this screen and upload date isn't shown. It should  be displayed just like views and votes are. Probably on the right? 

![screenshot_2016-10-30-10-53-23-218_org schabi newpipe](https://cloud.githubusercontent.com/assets/611746/19837785/2523e520-9e8f-11e6-98df-fac2a2bdd55d.png)
- [x] I carefully reed the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
Hm make sense.

**Comment by mauriciocolli** [comment]
For someone with the same "problem", you can view the date by expanding the description (clicking in the title, notice the arrow).
