### ISSUE TITLE
Soundcloud doesn't work

### ISSUE THREAD

**Issue by chrystian4** [TeamNewPipe/NewPipe#3721]
### Version
1.9.5

-

### Steps to reproduce the bug

1. Switch to the SoundCloud tab
2. Press on search
3. See the app crash and give report error. 

Alternatively, 
1. Open SoundCloud link
2. See the app crash and give report error. 

### Expected behavior

Be able to search in soundcloud tab, or be able to hear songs/open links of soundcloud in app.
### Actual behaviour

App crashes giving report error
### Screenshots/Screen recordings

https://mega.nz/file/NpgTABYb#Lam2dTr3PkQMmeDs5fv7_eLsuZ5RwKtlaY5UNDZY34g

### Logs

{"user_action":"get suggestions","request":"none","content_language":"US","service":"SoundCloud","package":"org.schabi.newpipe","version":"0.19.5","os":"Linux Android 9 - 28","time":"2020-06-02 14:47","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:48)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:107)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)\n\tat io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)\n\tat io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)\n\tat io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)\n\tat io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0\n\tat com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:4)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:41)\n\t... 26 more\n"],"user_comment":""}

**Comment by Stypox** [comment]
#2915
