### ISSUE TITLE
reCAPTCHA error

### ISSUE THREAD

**Issue by Shinra845** [TeamNewPipe/NewPipe#3722]
im staring at it for 5 minutes straight and nothing shows up. my connection is fine so im wondering whats wrong...thanks
![Screenshot_20200603-113138_NewPipe](https://user-images.githubusercontent.com/66347065/83593421-46813280-a58f-11ea-809a-112eb9695f05.jpg)

**Comment by Stypox** [comment]
See my answer in #3714
