### ISSUE TITLE
Add a thumbnail grabber

### ISSUE THREAD

**Issue by lazyDevPro** [TeamNewPipe/NewPipe#3724]
#### Describe the feature you want

Add an option to download the thumbnail of a video. The app can now download video and audio so the thumbnail grabber make the app feels complete.

#### How will you/everyone benefit from this feature?

Simply this feature make more sense and feels complete. If you can download videos and audios then why not the thumbnails.

**Comment by Stypox** [comment]
I don't see a use case for the mean user. This would be a very specific feature only used by... who? That is, who would benefit from this feature?

**Comment by varishali** [comment]
Whoever wants I guess, I personally need it that is correct. But I have seen some online tools doing similar thing so I thought this could be worthy feature.

**Comment by B0pol** [comment]
See #3389

**Comment by levoothan** [comment]
I still think this would be a nice little feature. I mean why have the ability to copy title or comments? Those seem equally as useless.

**Comment by gkeegan** [comment]
Having the ability to copy title and comments can allow you to search based on what they contain.

**Comment by gkeegan** [comment]
Having the ability to copy title and comments can allow you to search based on what they contain.

**Comment by opusforlife2** [comment]
> I don't see a use case for the mean user.

@Stypox folder.jpg/cover.jpg, for example. Not that it can't be obtained from elsewhere, but it would be highly convenient.

**Comment by Stypox** [comment]
@opusforlife2 wdym with folder.jpg/cover.jpg?

**Comment by opusforlife2** [comment]
@Stypox Cover art/Album art could be downloaded from Youtube Music for your songs from one album/artist.

**Comment by shivasagarrao** [comment]
This feature has been implemented in [SkyTube](https://github.com/ram-on/SkyTube) which uses NewPipe extractor.
