### ISSUE TITLE
Option to disable unplayable stream removal

### ISSUE THREAD

**Issue by micah-k** [TeamNewPipe/NewPipe#3725]
#### Describe the feature you want
Seeing as I cannot reopen #3665 I am posting once again on the topic. I struggle with connectivity issues in many places both at home and during my commute, and if my active playlist transitions between songs during these connectivity hiccups my playlist will begin rapidly discarding streams until it is empty or it wraps around to streams that are still loaded. The last time I made this request it was closed as being derived from #3576; however, I have installed the latest update for NewPipe that was meant to fix #3576 and verified that my issue still remains in the most current version. As I stated in my reply to the previous issue, a "feature" that empties my playlist at the slightest sign of a bad connection is not one I want to have active, and while I can understand its existence in the case of deleted videos and the like that truly cannot ever be played, it is much easier for me to troubleshoot a single song not loading because there's nothing to load than it is for me to reassemble my entire playlist because I walked under the wrong shingle.

**Comment by B0pol** [comment]
It will be fixed by #3704
