### ISSUE TITLE
Update Newpipe without losing saved playlists

### ISSUE THREAD

**Issue by cerebos7** [TeamNewPipe/NewPipe#3729]
Hello

I'm not sure whether it is a bug report or a feature request or just ignorance about the right use of the app.

When a new version of NewPipe is released, the update seems to result in the removal of the former data, including playlists. I'm sure I don't suppress local/cache memory files. 

Is there a way to keep the playlists and find them again when new versions are installed ? 

Thank you in advance

**Comment by cerebos7** [comment]
Well, this time (a few sec ago), I've just installed the new version and the playlist were still available 
(the first time in maybe 10 updates). I keep your process in mind in case the problem arises again.

Thanks

**Comment by eladkarako** [comment]
you must have exported the settings from a too old version (database format has changed/fixed). Try exporting the settings again from a newer version.

**Comment by opusforlife2** [comment]
@cerebos7 Drop a comment if this happens again.
