### ISSUE TITLE
"Main" as a "tab"

### ISSUE THREAD

**Issue by DmKaleid** [TeamNewPipe/NewPipe#3730]
<table>
<tr>
<th>This page</th>
<th>as an option here</th>
<th>to select here</th>
</tr>
<td><img width="200px" src="https://user-images.githubusercontent.com/66369488/83677147-2020be80-a5b2-11ea-94ac-92b5c7f41356.jpg"/></td>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/66369488/83677158-24e57280-a5b2-11ea-80f9-ef13f64467a6.jpg"/></td>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/66369488/83677169-27e06300-a5b2-11ea-82ac-9aef807c5eeb.jpg"/></td>
</table>

**Comment by TobiGr** [comment]
I don't think this is a good idea. especially with the new application workflow which will be introduced in the next release.
