### ISSUE TITLE
[feature request] open with YouTube (menu entry)

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3735]
I was wondering why when clicking the share button on a video in the YouTube app there is an entry of NewPipe (as a target),  
  
![20200604_032926](https://user-images.githubusercontent.com/415238/83701864-aa4d3f00-a613-11ea-9f52-0ee011cae82e.jpg)  
  
but sharing a video from NewPipe does not display the YouTube app as a target.
 
Although I use NewPipe as my main go to app for YouTube content, I do sometimes want to comment or like to show my support for content creators, 
and it sure be easier to be able to quickly "switch" on the same content back and forth from NewPipe to YouTube.  

Thanks!

**Comment by Stypox** [comment]
This is an issue with youtube not accepting shared urls, I don't think there is much that can be done

**Comment by eladkarako** [comment]
Hmm.. 🤔  
  
As a workaround I was sharing the URL to Google notes, then opening the URL through select/open/YouTube, but those are three or four steps extra..  
Just pitching here..
maybe an 'open with..' as a sub-menu?  
<code>*.youtube.com</code> URL opening-handler is always working fine with any app that supports it.  
and there is always the more specific 'open with YouTube' exclusively with <code>vnd.youtube://</code>.  

I simply feel that NewPipe does not have to be an end point. 

As a workaround I was sharing the URL to Google notes and selecting and opening the URL through YouTube (3,4 extra steps).

**Comment by Stypox** [comment]
If you unset the browser default and then click "Open in browser", it should show a dialog also containing Youtube

**Comment by eladkarako** [comment]
I have no issues opening videos when I have a URL. 
(for example when I have it in Google notes). As far as I can see NewPipe doesn't 'open with', does it?

**Comment by AnotherLife** [comment]
Why did "Open in Youtube" button get removed from the upper right menu?!?!

**Comment by eladkarako** [comment]
> Why did "Open in Youtube" button get removed from the upper right menu?!?!

what... wha? this feature was existing at some time before?

**Comment by AnotherLife** [comment]
Yes, until very recently, I was using it all the time. Now it's just Settings and Open in browser.

Bring back the YT button, please!

**Comment by TheAssassin** [comment]
You seem to have blocked Team NewPipe. Therefore, we will close this issue now. If you unblock us, we can reopen the issue.
