### ISSUE TITLE
Background/pop-up/full-screen players open at the same time

### ISSUE THREAD

**Issue by theFireProjet** [TeamNewPipe/NewPipe#3737]
### Version
0.19.5

### Steps to reproduce the bug
1. Go to a video
2. Start background playback
tap 'Background'
3. Start popup player
tap 'Popup'
4. Start in-app full screen player
tap play button on the video thumbnail

### Expected behavior
If a video is started in a different playback mode (background/popup/full-screen) while NewPipe is already playing a video, the first playback mode should be fully stopped, not only paused.
There should only be one player or playback mode open at a time.

*Examples*
- There shouldn't be a paused pop-up player over the full-screen player playing a video.
- There shouldn't be a paused background player (in the form of a second NewPipe notification) while a video is playing in pop-up mode.
- When the playback method is changed, the notification of the first playback mode (background/popup) should be removed.

### Actual behaviour
If done in the right order, it's possible to have two NewPipe playback notifications active, a pop-up player and the full-screen player at the same time.

*Explanation*
This behaviour doesn't make any sense because it's only possible to play one mode at a time. I don't need a paused pop-up player in front of my full- screen player if I'm trying to watch in full-screen mode. Also it is disturbing to have two playback notifications at the same time: A paused background player and a playing pop-up player. It only leads to mistakes because of tapping the wrong notification.

#### Video player
![Screenshot_20200604-055625_NewPipe](https://user-images.githubusercontent.com/61639215/83714662-b04f1a00-a62b-11ea-9fd7-7ea78ca8f80b.jpg)
<sup> &nbsp;&nbsp; *pop-up player and full-screen player
&nbsp;&nbsp; two NewPipe notifications on the notification bar* </sup>

#### Notification center
![20200604_062132](https://user-images.githubusercontent.com/61639215/83714666-b47b3780-a62b-11ea-96a5-4fb7ed3176e2.jpg)
<sup> &nbsp;&nbsp; *duplicate NewPipe playback notification* </sup>

**Comment by androidSwDev099** [comment]
I would prefer to be able to have multiple players at the same time. I may be listening to a playlist in background mode with the background playing. Now I decide to take a break and watch a video outside of the background player - either in a popup player or full screen player while the background player is paused. When I finish watching this break video, I currently have the option to resume the background player.  Please don't disable the flexibility to use multiple players in NewPipe.

**Comment by wb9688** [comment]
That's because they're totally separate things currently, will be fixed by #2907

**Comment by micah-k** [comment]
I personally use this functionality if the itch strikes me to listen to a different song in the middle of my current playlist; merging the players will force me to either stop my current playlist entirely for that single song, or open the playlist and spend the time to slowly drag the new song up to the next play spot. Fixing this "issue" will actually remove functionality from the app for no discernible reason.

**Comment by MD77MD** [comment]
This issue will be solved once the development of (#2907 Expandable player with unified UI) is done.
