### ISSUE TITLE
Unify playback queues and notifications for background/pop-up player

### ISSUE THREAD

**Issue by theFireProjet** [TeamNewPipe/NewPipe#3739]
#### Context
If a video is started in the background and another video is started in the pop-up player, there are two playback notifications. When the user taps on the notifications, they can view the two different playback queues for the background and the pop-up player.

![20200604_102633](https://user-images.githubusercontent.com/61639215/83733507-e69d9100-a64d-11ea-8acb-f4367aa325d6.jpg)

#### Feature request
Merge the two queues for the background and the pop-up player into a single one that is used for all playback modes.
Show the same notification for the pop-up player as for background playback. When a video is started in a different playback mode (background/pop-up) or the playback mode is switched, the notification has to control the player (background or pop-up player) that is currently playing.
I.e. if the pop-up player is open all the time but a video is started in background mode, from that point the notification has to change to the video that is played in the background until the pop-up playback is continued.

#### User benefit
Usually, every media player has a playback queue. But not more than one. It's known to the users and expected that way. It's convenient because it's simple, common and it doesn't work any worse.
There is just no point in having multiple playback queues for one app that can only play one video at a time. It's only extra load that doesn't bring any advantage.

The same explanation applies for the duplicate playback notification. Currently, two notifications are necessary to access the different playback queues. Beyond that, it's only annoying that basically the same notification can be displayed twice while at the same time only one of them has an actual purpose. It doesn't make any sense that the pop-up player notification is different. It misses the skip buttons and the progress bar. Apart from that there is no difference, so it could as well be only one notification.

#### Related problems
The disadvantages described in this issue are related to a different problem in issue 'Background/pop-up/full-screen players open at the same time' #3737.
In that issue I stated that it's unnecessary to have different players open at the same time, as only one can play at a time, anyway. The fact that pop-up player and background playback can be open simultaneously is the condition for the two notifications showing up at the same time. Still, it is an independent problem that there are two different notifications in the first place.
Also the transition from which playback mode is controlled by a single notification (background or pop-up mode) would be easier if their was only one playback mode open at a time.

**Comment by ariel-moczulewski** [comment]
I wouldn't mind if there was an option for one playback mode or if it was even default one but it would be a major inconvenience if it was the only one. The app doubles down as a music app and a video player while most apps have one or more narrow purposes.

**Comment by MD77MD** [comment]
#2907
