### ISSUE TITLE
Playing in background doesn't play correctly

### ISSUE THREAD

**Issue by alexanderadam** [TeamNewPipe/NewPipe#374]
Hey guys,

first of all: NewPipe is really awesome!
Everything works fine for me except the play in background feature.
It's like it plays a second, then a pause, then again a second sound and so on.
Sounds like a weird buffering issue.
Playing in full screen works flawlessly tough.

I'm using version 0.8.5 of the F-Droid build on Nexus 5 with stock android 6.0.1 (Patch level of 5th october 2016).

- [x] I carefully reed the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them. *<<< reed?* :wink: 
- [x] I checked if the issue/feature exists in the latest version.

**Comment by devnoname120** [comment]
Could it be because your Internet connection is not fast enough?

The MP3 playback uses a high-quality stream. Does 720p videos play without any stuttering or buffering?

**Comment by alexanderadam** [comment]
Definitely can't be the internet connection.
720p videos work fine and on the same internet connection Netflix in FHD works flawless as well.

**Comment by theScrabi** [comment]
> <<< reed? 😉

[Uhh well :P](https://github.com/TeamNewPipe/NewPipe/commit/3bd477631c8e848051394aa199dcafa6a431eef7)

It might be due to the internal Player of android. I already noticed that that thing sometimes does weird stuff. I always tell people I'm going to switch to explayer one day... still waiting for that day sorry.

**Comment by renatocan** [comment]
I' ve observed the same problem. Video playback works fine but audio in the background keeps pausing and returning.

Thanks!

Renato.
