### ISSUE TITLE
New Pipe not working properly

### ISSUE THREAD

**Issue by maheshkumararaju** [TeamNewPipe/NewPipe#3743]
### Version

-

**Comment by maheshkumararaju** [comment]
![photo_2020-06-05_08-31-07](https://user-images.githubusercontent.com/53971467/83832280-e7462e00-a706-11ea-90f3-bb02f0cfe898.jpg)
![photo_2020-06-05_08-31-03](https://user-images.githubusercontent.com/53971467/83832284-e9a88800-a706-11ea-89ef-6a1ea72d9e5a.jpg)

**Comment by maheshkumararaju** [comment]
For past 2 weeks... NewPipe is not working fine and receiving the above results if I search anything!

**Comment by wb9688** [comment]
Upgrade to the lastest version and next time please properly fill in the issue template
