### ISSUE TITLE
[bug]No search suggestions and history

### ISSUE THREAD

**Issue by 0xTyagi** [TeamNewPipe/NewPipe#3744]
NP doesn't showing any Search suggestions or history despite search history is on.

Version 0.19.5
Android version 7.1.2 (api25)
ROM: MIUI 11
Device: redmi 4x

if i clear the data then it work but when i import database it doesn't show any history or suggestions.

Wipe cached metadata and clear search history doesn't helping

![Screenshot_2020-06-05-11-31-06-817_org schabi newpipe](https://user-images.githubusercontent.com/59569506/83843154-056d5780-a722-11ea-9255-0523a0670c5d.jpg)

**Comment by Stypox** [comment]
Settings -> Content -> Search suggestions

**Comment by 0xTyagi** [comment]
> Settings -> Content -> Search suggestions

oh! that was off.  

Next time when introducing new setting, kindly preserve old settings state
