### ISSUE TITLE
Trying to search for anything just shows a bunch of "Network error" screens

### ISSUE THREAD

**Issue by Daniel-Brum** [TeamNewPipe/NewPipe#3745]
### Version

- 0.19.5

### Steps to reproduce the bug

1. Click on the search button
2. Type any character

### Expected behavior

Normally showing search suggestions

### Actual behaviour

The "Network error screen automatically closes the keyboard and appears once for every character typed. When you tap search on the keyboard, then click on Retry on the screen, the page is correctly loaded after a second.

### Screenshots/Screen recordings

https://youtu.be/iyka-QgLWgA

**Comment by wb9688** [comment]
Don't block suggestqueries.google.com on your network

**Comment by Daniel-Brum** [comment]
Worked perfectly, thanks for the fast reply
