### ISSUE TITLE
Newpipe not closing audio sessions after playback?

### ISSUE THREAD

**Issue by Nephiel** [TeamNewPipe/NewPipe#3746]
### Version

- 0.19.5

### Steps to reproduce the bug

1. Install [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet)
2. Start playing any video with Newpipe.
3. Check the Wavelet notification, note it shows _Apps using Wavelet: Newpipe_.
4. Close the video, exit or otherwise force-close Newpipe.
5. Check the Wavelet notification, note it still shows _Apps using Wavelet: Newpipe_ (meaning the audio session is still open or at least not properly closed).
6. Start playing any video with Newpipe again.
7. Check the Wavelet notification, note it shows _Apps using Wavelet: Newpipe, Newpipe_ (meaning Newpipe started a new audio session but the existing one is still not closed).
8. (Optional) Repeat steps 4-7. Note how a new audio session is created every time and the existing sessions are never cleared.

### Expected behavior

Newpipe should close the audio session after playback.

### Actual behaviour

It seems Newpipe does not properly close the audio session after playback.

### Screenshots/Screen recordings

![Screenshot_20200604-142021](https://user-images.githubusercontent.com/2184015/83872073-8f70ec80-a731-11ea-9398-f792ba5327c7.jpg)

### References:
[XDA thread](https://forum.xda-developers.com/showpost.php?p=82744303&postcount=119)

**Comment by leoyinjou** [comment]
Thanks for making this bug report! I was going to do something about it, and i actually talked to Wavelet's dev to confirm if it is NewPipe's issue.
I can confirm i get the exact same problem with NewPipe, attaching screenshot here.
![Screenshot_20200605-173013](https://user-images.githubusercontent.com/64910443/83884095-f9f84b80-a776-11ea-9a1b-59d8ed6b4c87.jpg)

**Comment by Stypox** [comment]
#2373
