### ISSUE TITLE
Total No Tracker NewPipe

### ISSUE THREAD

**Issue by CodENooBUseR** [TeamNewPipe/NewPipe#3747]
#### How will you/everyone benefit from this feature?

hello,
im newpipe user
i like the privacy concern concept of your app but when i scan the app with classyshark, the newpipe app still has 1 tracker inside.
maybe you can consider to remove it.
i attached the result photo.

Thank You
![Imagepipe_0](https://user-images.githubusercontent.com/42958910/83898178-c8847d80-a780-11ea-9599-478a169aad84.jpg)

**Comment by wb9688** [comment]
ACRA is a library to catch crashes. It's not set up to send those crashes automatically to use, but show a screen showing the exception and an option for the user to send the crash report via e-mail.
