### ISSUE TITLE
Playlist Support [Duplicate]

### ISSUE THREAD

**Issue by AnotherJavaCoder** [TeamNewPipe/NewPipe#375]
This is only a suggestion but won't this app be more amazing if it can load public playlists ?

**Comment by theScrabi** [comment]
I think that was requested already.

**Comment by AnotherJavaCoder** [comment]
Sorry haven't search in issues that are a year old

**Comment by theScrabi** [comment]
No problem.
But all probs to BlenderViking you might like what he [does](https://github.com/TeamNewPipe/NewPipe/tree/playlist) ;)
