### ISSUE TITLE
Search filter for youtube: CC/Subtitle

### ISSUE THREAD

**Issue by kaitou1412** [TeamNewPipe/NewPipe#3750]
I think it would be nice if you add feature *search filter* which makes searching video that have subtitle possible. Or maybe specifically Subtitle for chosen language.

For example, i want to search for youtube videos that have arabic Subtitle.
Currently youtube mobile doesn't have this feature. The youtube desktop have feature
to filter videos that have subtitle, but Not spesific to the language. 

The image below is from youtube desktop
![Screenshot_20200606-070610](https://user-images.githubusercontent.com/5919461/83931236-c7297400-a7c5-11ea-8561-1677b281fdec.jpg)

**Comment by Stypox** [comment]
#110 #2251
