### ISSUE TITLE
Reccomendation Tab

### ISSUE THREAD

**Issue by doki-doki-exe** [TeamNewPipe/NewPipe#3757]
Hey i was thinking Reccomendation tab would be a good idea. When i choose the reccomendation tab i would be given a list of genres to choose from lets say i choose movies,games,science then the tab will show videos that the new pipe community suggested to watch. The videos will be picked by users who lets say will share the video to reccomendation and select the genre. I always want new videos of the things i like watching and the wats new tab and subscription tab does not really show new channels. It will take some tike to function properly but i feel it will be great and many will like it as well.

**Comment by test2a** [comment]
are you suggesting this as a separate feature from youtube? who would add videos to each genre? how to check wrong entries? who would moderate it?

**Comment by Stypox** [comment]
#2256
