### ISSUE TITLE
Add Instagram profiles support

### ISSUE THREAD

**Issue by arseniy17** [TeamNewPipe/NewPipe#3765]
I think it would be great if you added the ability to add people profiles from Instagram.  (The people I follow, the ones I follow) would like to receive news, photos, posts.  How much is realizable)) 
I’ve been looking for an application for a long time that can collect data from different hosting platforms like YouTube, Instagram, vk.com to simplify the process of accepting information.  And each individual application has its own add-ons that are simply not needed, but they interfere very much.  For example, in YouTube there is a recommended tab and navigation that cannot be removed.  In YouTube, I need one tab, these are my subscriptions, the same with instagram.  Instagram feed takes a lot of time, you can’t turn it off, but I just need to follow the people I follow and nothing more
I’m Russian guys, so if there are strange sentences in the request that I wrote to you, write it off to a bad translation from Russian into English
Firstly, if this function appears, I will finally delete the instagram, usually I spend 5 hours a day on it, with this function I can reduce the time it takes to receive information to a maximum of an hour.  It turns out that I save 4 hours daily, I do not scroll the tape in instagram, I use the phone less, so I sit less.  Based on the foregoing, I have 4 free hours a day, and this is 28 hours a week (plus one day a week, is it really true?) And I will save more than 1460 hours a year, which is 60 full days.  During this time, which I will have, I will be able to get in shape and participate in a mens physicist or or read 60 books or write my book or fly back to the ISS 225 times, in general, time is very valuable and I hope that you guys will be interested  this cool addition.  Thank you all for your time.

**Comment by arseniy17** [comment]
Forgot the most important) Here is a photo of my cat
![15916777921249201986234503931989](https://user-images.githubusercontent.com/35500553/84106888-f7228280-aa24-11ea-8901-a759b298026d.jpg)

**Comment by B0pol** [comment]
NewPipe is a streaming app

> I’ve been looking for an application for a long time that can collect data from different hosting platforms like YouTube, Instagram, vk.com to simplify the process of accepting information

>  In YouTube, I need one tab, these are my subscriptions, the same with instagram

You are looking for an [RSS Reader](https://en.m.wikipedia.org/wiki/News_aggregator) 
![Screenshot_20200609-084512_Flym_1](https://user-images.githubusercontent.com/58657617/84115006-99deff00-aa2d-11ea-98fa-0dd648c5ad4e.png)

You can make a folder (here Twitter is a folder) for Instagram and another one for YouTube.

You just need to add the RSS feeds, on NewPipe you can get it by clicking on the RSS logo
![Screenshot_20200609-084736_NewPipe_invidious_1](https://user-images.githubusercontent.com/58657617/84115186-ea565c80-aa2d-11ea-823c-b77527c63a8d.png) and then you copy the link in your RSS reader, for Instagram [Bibliogram]( https://bibliogram.snopyta.org/) provides RSS feeds and you don't need an account, just paste the link of an account in the home page and then click on RSS

Should I close this issue?

**Comment by arseniy17** [comment]
> NewPipe - потоковое приложение
> 
> > Я давно искал приложение, которое может собирать данные с разных хостинговых платформ, таких как YouTube, Instagram, vk.com, чтобы упростить процесс приема информации.
> 
> > В ютубе мне нужна одна вкладка, это мои подписки, тоже самое с инстаграм
> 
> Вы ищете [RSS Reader](https://en.m.wikipedia.org/wiki/News_aggregator)
> ![Screenshot_20200609-084512_Flym_1](https://user-images.githubusercontent.com/58657617/84115006-99deff00-aa2d-11ea-98fa-0dd648c5ad4e.png)
> 
> Вы можете создать папку (здесь Twitter - это папка) для Instagram и еще одну для YouTube.
> 
> Вам просто нужно добавить RSS-каналы, на NewPipe вы можете получить его, нажав на логотип RSS,
> ![Screenshot_20200609-084736_NewPipe_invidious_1](https://user-images.githubusercontent.com/58657617/84115186-ea565c80-aa2d-11ea-823c-b77527c63a8d.png)а затем скопировать ссылку в своем RSS-ридере, поскольку Instagram [Bibliogram](https://bibliogram.snopyta.org/) предоставляет RSS-каналы, и вам не нужна учетная запись, просто вставьте ссылку учетной записи на домашней странице, а затем нажмите на RSS
> 
> Должен ли я закрыть эту проблему?

Я так и не понял, то есть это можно реализовать через New pipe?  Если да, то можно скинуть фото где находится красный значок rss.   

I still do not understand, that is, it can be implemented through New pipe?  If so, you can throw off the photo where the red rss icon is located

**Comment by rssoc** [comment]
It's certainly doable, but it is something that is outside of the scope of the NewPipe project. Like B0pol already mentioned, NewPipe is a front-end for streaming from audio/video services, it is not supposed to be a twitter/facebook/instragram client.

**Comment by arseniy17** [comment]
> Это, конечно, выполнимо, но это то, что выходит за рамки проекта NewPipe. Как уже упоминалось в B0pol, NewPipe - это интерфейс для потоковой передачи из аудио / видео сервисов, он не должен быть клиентом twitter / facebook / instragram.

Got it, I literally a minute ago set everything up for an rss feed with another application, thanks to everyone who answered and helped.  Today is likely to make a big difference in my life, I have long wanted to configure everything with rss, but there was not enough knowledge.  Have a good time🤝
