### ISSUE TITLE
IronSource Ads Are Not Running In 0.19.5. They were running fine in 0.18.2.

### ISSUE THREAD

**Issue by SArsalanK** [TeamNewPipe/NewPipe#3773]
IronSource Ads Are **Not Running In 0.19.5**. They were running **fine in 0.18.2**. Can anyway this release (0.19.5) or newer releases than 0.18.2 could halt IronSource Ads from getting displayed?

**Comment by wb9688** [comment]
Have you read NewPipe's license? Then you very well know that what you're doing is illegal.

**Comment by SArsalanK** [comment]
I just did read it. I was not aware of it. Thanks for letting me know. Removing the ads now.

**Comment by SArsalanK** [comment]
But is it doing it? And how? Just Curious!

**Comment by TobiGr** [comment]
That's not our responsibility as we aim to provide an app which grants enhanced privacy protection.

**_Important_**: you **_must_** publish your code and list the changes when modifying it. Your [NewPipe repo](https://github.com/SArsalanK/NewPipe) is out of date. If you distribute a binary without publishing its code, this is a license violation.
Apart from that, IronSource is closed source (proprietary) and therefore cannot be included in any NewPipe fork. This would also be a license violation.

**Comment by TheAssassin** [comment]
A friendly reminder: Don't use source code without checking the license. You are very likely to violate that license then, which is a copyright offense and might lead to consequences.

Also, we are not responsible for un-breaking stuff, especially if it doesn't comply to what we thing the project should be like, that doesn't work in your proprietary application.

This tool is entirely focused about privacy. Adding some tracking (well, you call it ads) is likely not only a violation of copyright (those are almost exclusively proprietary), but also morally extremely questionable.

It's been said before, and I'll say it again: **Please feel free to reuse this application, but only if you comply with the license!** Please see https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic for more information.

**Forking NewPipe to add ads (and earn money with our collective work) is bad!** You're likely violating the license, and it also gives you **bad karma**!

**Comment by SArsalanK** [comment]
**Agreed & Understood. Thank you!**
