### ISSUE TITLE
High battery drain on LineageOS

### ISSUE THREAD

**Issue by MrCodebody** [TeamNewPipe/NewPipe#3775]
![IMG_20200610_175705](https://user-images.githubusercontent.com/66831265/84503259-2d2c6480-acba-11ea-99dc-ca321406f3a0.jpg)
I am using LineageOS MicroG signed, NewPipe almost always in streaming PopUp mode.
Is it maybe because I have no Google Library's, Services,..?

**Comment by B0pol** [comment]
We don't use google play services.

43% for 2 hours usage way too much indeed.
But 37% for aurora store for only 21 minutes???

There is definitely something wrong with your battery.
