### ISSUE TITLE
Auto Rotate Isn't Working

### ISSUE THREAD

**Issue by DecodeRecode** [TeamNewPipe/NewPipe#3778]
#### Describe the feature you want

Auto rotation (landscape) doesn't seem to work when I am playing videos on my  Pixel 2XL. Now, I see that I can bring down a set of options from the drop-down menu (small triangle) but I have to manually make the video rotate. Can this feature be automatically added to the settings options for able/disable functionality?

**Comment by Stypox** [comment]
For me autorotation works fine

**Comment by DecodeRecode** [comment]
Stypox, I figured out that the problem was my phone. I updated my phone to a new ROM and now the auto-rotate feature works just fine. Sorry for the confusion. Thanks for the assistance.
