### ISSUE TITLE
ownCloud support

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#378]
- [x] I carefully reed the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

What if we added ownCloud support, and make it possible that [ocDonloader](https://apps.owncloud.com/content/show.php/?content=169974) remotely downloads videos we tell it to download?

**Comment by FaizKhan5** [comment]
Close this.
