### ISSUE TITLE
Feed Update fail in What's New

### ISSUE THREAD

**Issue by angriness-sleek** [TeamNewPipe/NewPipe#3784]
the top bar in "What's New", which says "Last Updated...", which you press (or maybe you press the refresh button on the right side) to refresh the feed only works once after a fresh install. Hitting it again does nothing at all, you have to clear storage, reimport backup and hit again to refresh again, and when you press the refresh again after that, nothing happens again.

**Comment by wb9688** [comment]
No, it does nothing until after x amount of time, which is configurable in the settings.

**Comment by angriness-sleek** [comment]
oh lol I see, don't get the logic tho, like the setting should auto refresh it and when I hit it, it should do a manual refresh whenever I want?
