### ISSUE TITLE
Android Auto integration

### ISSUE THREAD

**Issue by broggini** [TeamNewPipe/NewPipe#3786]
#### Describe the feature you want

It would be great if the player would show up in the Android Auto app when connected to the car. (as seen with Spotify here: https://cnet1.cbsistatic.com/img/DAAONKN9618H-jNFYOGodAtbbbg=/2019/08/07/ff2f17d2-0e64-4818-945d-cd8a0a71ca34/rs-tech-android-auto-update-holdingstill.jpg)
I think this should be straight forward and w/o royalties since the free MP3 player Musicolet has this feature as well.

#### How will you/everyone benefit from this feature?

Everybody who listens to music in the car would benefit from this feature.

**Comment by Redirion** [comment]
Unfortunately (and I would love to have that too), it is not possible. See https://github.com/TeamNewPipe/NewPipe/issues/1758

NewPipe is not available in PlayStore and does not use GMS Services.

However you can still use NewPipe with the "Play in Background" function when Android Auto is active.

**Comment by Pretorianer** [comment]
Actually it should be possible to use Newpipe inside Android Auto in rooted phones. Like Carstream does for example https://github.com/thekirankumar/carstream-android-auto
