### ISSUE TITLE
Black channel name in background player

### ISSUE THREAD

**Issue by primarto** [TeamNewPipe/NewPipe#3788]
### Version

- 0.19.5

### Steps to reproduce the bug
 Play any videos in Background 
Open background player

### Expected behavior

The channel name is not visible on a dark background
### Actual behaviour

The name of the channel to have a different color to make it visible
### Screenshots/Screen recordings

![4d7cf95f-c815-40a5-9d3b-94b7c5fe7ab7](https://user-images.githubusercontent.com/62907157/84998030-95ae9200-b14f-11ea-92c9-e382260f9500.jpg)
![991b86d4-5d8d-4101-8f5f-328d38f2176a](https://user-images.githubusercontent.com/62907157/84998074-a65f0800-b14f-11ea-85e5-de9e61fd5f31.jpg)
![5f24310c-096d-4d88-bb4d-b8d3158e24d7](https://user-images.githubusercontent.com/62907157/84998108-afe87000-b14f-11ea-8189-35da68168a1a.jpg)

**Comment by Stypox** [comment]
#2586
