### ISSUE TITLE
stack trace on download, followed by asking for permission to access files

### ISSUE THREAD

**Issue by travisfw** [TeamNewPipe/NewPipe#379]
A successive attempt succeeded. Seems like there's an error with the order of operations.

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "en",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.8.5",
   "os": "Linux Android 6.0 - 23",
   "time": "2016-11-14 20:10",
   "exceptions": [
      "java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to get length of null array\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:2905)\n\tat android.app.ActivityThread.access$1900(ActivityThread.java:157)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:148)\n\tat android.app.ActivityThread.main(ActivityThread.java:5551)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)\nCaused by: java.lang.NullPointerException: Attempt to get length of null array\n\tat us.shandian.giga.get.DownloadManagerImpl.loadMissions(DownloadManagerImpl.java:73)\n\tat us.shandian.giga.get.DownloadManagerImpl.<init>(DownloadManagerImpl.java:30)\n\tat us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:47)\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:2895)\n\t... 8 more\njava.lang.NullPointerException: Attempt to get length of null array\n\tat us.shandian.giga.get.DownloadManagerImpl.loadMissions(DownloadManagerImpl.java:73)\n\tat us.shandian.giga.get.DownloadManagerImpl.<init>(DownloadManagerImpl.java:30)\n\tat us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:47)\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:2895)\n\tat android.app.ActivityThread.access$1900(ActivityThread.java:157)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:148)\n\tat android.app.ActivityThread.main(ActivityThread.java:5551)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)\n"
   ],
   "user_comment": "pressed the download button for https:\/\/youtu.be\/t99N223fqCo"
}

**Comment by theScrabi** [comment]
Please read the [contribution notes](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md#crash-reporting) first. You are not suppost to post stacktraces here.
