### ISSUE TITLE
Unsupported URL from Google Search results and/or Google video search

### ISSUE THREAD

**Issue by webber-naut** [TeamNewPipe/NewPipe#3790]
### Version
0.19.5

### Steps to reproduce the bug
Google anything that returns youtube video. Also you can choose video tab for video search only.
Click to share to newpipe returns error. Unsupported URL. 

URL scheme is: https://www.google.com/url?paramaters&url=https://m.youtube.com/watch....

### Expected behavior
Play video with newpipe

### Actual behavior
Returns Unsupported URL error at bottom of screen. Needs to parse the link to get url parameter.

**Comment by Stypox** [comment]
Could you provide a full link?

**Comment by Stypox** [comment]
Nevermind, I found one: https://www.google.it/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&cad=rja&uact=8&ved=2ahUKEwi8ofOr-KHqAhVN2KQKHfD6AnsQtwIwAHoECAIQAQ&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DHu80uDzh8RY&usg=AOvVaw1vaKuHxMMagizHHo-AZ-zC

**Comment by B0pol** [comment]
Uh, google has google.com fr it en es… all regional TLD, moreover it would say open NewPipe and say unsupported URL for every non-youtube google links

**Comment by Stypox** [comment]
@B0pol I'm currently implementing this for every service, with a utility function called in `LinkHandlerFactory.fromUrl` and all of its overriders

**Comment by B0pol** [comment]
What about calling `openUrlInBrowser` on unsupported URL? It would make sense, wouldn't it?

**Comment by Stypox** [comment]
It would be confusing imo: if I shared something to NewPipe, I don't expect a browser to be opened

**Comment by B0pol** [comment]
true. what about a prompt: This URL is unsupported, would you want to open it in your browser?

**Comment by eladkarako** [comment]
it's Google redirect service, can be removed by taking only the URL and do the equivalent of decodeURIComponent in java to save actual traffic.
