### ISSUE TITLE
Videos from specific channel only not playing

### ISSUE THREAD

**Issue by jonek2k3** [TeamNewPipe/NewPipe#3795]
### Version

-0.19.5

### Steps to reproduce the bug
videos from one and only this one channel don't work at all. can't watch them, can't download them. they work fine in defferent app.
channel name: HerbtheNerd
videos: tryed 3 newest one, neither works

**Comment by wb9688** [comment]
If you could still reproduce it, could you install a debug version, connect your phone to your PC through USB, open Chrome, go to `chrome://inspect`, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send me that HAR? Then I might be able to fix this issue.

**Comment by jonek2k3** [comment]
yes i can reproduce it, if you can tell me how to install debug version.

**Comment by wb9688** [comment]
@jonek2k3: The zipped APK attached in for example #3777 should work, just download it, unzip it and install the APK as usual (it'll install as a separate NewPipe app).

**Comment by jonek2k3** [comment]
right ok so it's bit weird but maybe it will make sense to you. 720p version works but there is nothing appearing in log, 1080p doesn't and again nothing in log. just from my own curiousity i played other video and i see log is filling with many informations. anyway logs attached. didn't allow me to upload HAR files so i packed it.
[herbthenerd.zip](https://github.com/TeamNewPipe/NewPipe/files/4804547/herbthenerd.zip)

**Comment by wb9688** [comment]
@jonek2k3: Hmm… the 720p HAR only contains a search suggestion page, while the 1080p HAR only contains 2 search suggestion pages, 1 search result page, and 2 images. I don't see the video page in it.

However, I've now been able to reproduce it myself (YouTube likes to mess around with the videos, so not everyone could always reproduce issues like this) and those resolutions appear to be `sq`. Currently only `range` works in NewPipe unfortunately.

**Comment by jonek2k3** [comment]
yeah i've noticed that log doesn't fill after choosing video in search result. that occured to me, only with this channel. when i choose different video all is good. ok thanks for help, i will watch that one channel in 720p for now. reegrds.

**Comment by Stypox** [comment]
#2415
