### ISSUE TITLE
[Peertube] rename "videos" search filter with "all" 

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3797]
As we are not searching for videos only but also channels, playlists…
<sub><sup>sorry for the template</sup></sub>

**Comment by wb9688** [comment]
No, we don't: https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/peertube/extractors/PeertubeSearchExtractor.java#L69

We should add support for channels in search results though, see e.g. https://framatube.org/search?search=Framasoft
