### ISSUE TITLE
Tooltip jump crashes android totally.

### ISSUE THREAD

**Issue by aasutossh** [TeamNewPipe/NewPipe#3799]
### Version

- 0.19.5

### Steps to reproduce the bug

1. Launch app
2. Long press the _Trending_ tab (having fire symbol). 
3. After a popup shows up, long press the same _Trending_ tab again. 
4. Crashes my phone (Android 6.0), but if I lock I can hear the locking sound. 

### Screenshots/Screen recordings

I could record the video from another device. Let me know if you people need it.

**Comment by TobiGr** [comment]
Thank you for the report. I don't think a video is needed, because I can reproduce this on my Android 6 device, but cannot reproduce this with Android 9. We might want to test this with different OS versions to find the cause of this bug.

**Comment by aasutossh** [comment]
Yeah. Thank you for the confirmation.

Btw, when the popup is gone, long pressing won't crash the device. It only crashes when you long press the tab when the popup is already present.

**Comment by jwmh** [comment]
Unable to reproduce on:
- app: Newpipe 0.19.5 (current latest on F-Droid)
- OS: Android Go - 8.1.0 (stock; NOT rooted)
- Hot Pepper Poblano,  VLE5

When I try to follow...
... The "Trending" popup simply vanishes as soon as I touch a second time.
It does not appear to crash anything.

I don't have a non-"Go" version of Android to test with, 
 so cannot confirm that this isn't an issue for non-Go 8.1.0 devices
(nor indeed any other OS version).

**Comment by TobiGr** [comment]
Some more info. This issue only happens to the first item in the row. When long-pressing on others twice, the tooltip jumps to the left. So I guess we get a crash, because the tooltip wants to jump out of the screen. This is prevented in newer Android versions because the tooltip vanishes as soon as one stops pressing on the display.
I tested this with AuroaStore and got the same behaviour and the same crash. I guess we cannot do much about it. 
###### _(Maybe updating some libs?)_

**Comment by aasutossh** [comment]
@TobiGr I wanted to point out that behavior but couldn't put it into words. So, I skipped it. Thank you for verbalizing it.

**Comment by wb9688** [comment]
>(Maybe updating some libs?)

@TobiGr: The relevant libs are up-to-date (when ignoring beta versions). I could reproduce on an API 21 AVD.

**Comment by opusforlife2** [comment]
So, close as an OS problem?

**Comment by Stypox** [comment]
I also got the same behaviour on the official GitHub client for Android, so it is certainly not our fault

**Comment by opusforlife2** [comment]
Still, is it possible to prevent the tooltip from showing again if one is already visible?
