### ISSUE TITLE
No sound in the middle of the video

### ISSUE THREAD

**Issue by rugk** [TeamNewPipe/NewPipe#380]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to  them.
- [x] I checked if the issue/feature exists in the latest version.

In every video I watch (no matter how long) near the middle there is no sound anymore. Switching to another position of the video and back to the original position, I'll work again.

CM 13 based on Android 6

**Comment by theScrabi** [comment]
I've noticed that, but it even happens with external players, so for now I can't help. Sorry.

**Comment by rugk** [comment]
Okay, so what's the reason for that?

**Comment by theScrabi** [comment]
I don't know. Youtube normally delivers video and audio in separate streams.

**Comment by raichiss** [comment]
I have the same issue. Audio seems to drop after about 8 minutes no matter where you start the video from.

**Comment by mauriciocolli** [comment]
No problem here, If it still happens feel free to open another issue.
