### ISSUE TITLE
Add Shuffle option for a playlist.

### ISSUE THREAD

**Issue by bvkrish83** [TeamNewPipe/NewPipe#3801]
If i want to always play the playlist with shuffle on, there is no provision as of today. Its better to provide an option to enable shuffle (and probably repeat) at a playlist level.

**Comment by B0pol** [comment]
It's available.

Here is a screenshot from a randon playlist (I typed "music" and filtered by playlist)

<img src="https://i.ibb.co/PrfZ3w5/Screenshot-20200621-165622-New-Pipe-1-1.png" width="200">

Click on the notification and you'll get this menu, a.k.a backgroud player

**Comment by bvkrish83** [comment]
Yes, i am aware of this option. With your suggestion, i need to follow these steps each time i need to play this playlist. Instead it would be better to store this information in the playlist.

My suggestion is to have this shuffle and repeat as a persisted option for each playlist. So that the users need not repeat these steps each time

**Comment by bvkrish83** [comment]
@B0pol Yes, i am aware of this option. With your suggestion, i need to follow these steps each time i need to play this playlist. Instead it would be better to store this information in the playlist.

My suggestion is to have this shuffle and repeat as a persisted option for each playlist. So that the users need not repeat these steps each time

**Comment by B0pol** [comment]
If you want this, open a new issue and **follow the feature request template**.
