### ISSUE TITLE
[feature request] settings option to set default playback speed

### ISSUE THREAD

**Issue by r3dhash** [TeamNewPipe/NewPipe#3802]

**Comment by B0pol** [comment]
We won't do this. Currently it remembers the last speed, therefore if you set to 1.25 it will play at x1.25 next time. There is no need for a setting

**Comment by r3dhash** [comment]
> We won't do this. Currently it remembers the last speed, therefore if you set to 1.25 it will play at x1.25 next time. There is no need for a setting

That is why I asked it tho😅, if I change it I also need to reset it

maybe, "reset playback/pitch settings on new video request" ?

**Comment by Stypox** [comment]
> reset playback/pitch settings on new video request

That was the old behaviour, but most people did not like it, so we went for this. ;-)

**Comment by r3dhash** [comment]
> That was the old behaviour, but most people did not like it, so we went for this. ;-)

damn those most peoples
