### ISSUE TITLE
Newpipe provided as "TubeMate" in Samsung Store

### ISSUE THREAD

**Issue by Pokemetti** [TeamNewPipe/NewPipe#3804]
In the Samsung Store a lightliy modified version of Newpipe is advertised as TubeMate. The differences I found so far are the launch screen, how the app calls itself and ads.
I don't know about the license of Newpipe, is that allowed? Open source software isn't open so people can claim it their own and make money off ads.
Link: http://apps.samsung.com/appquery/appDetail.as?appId=vddl.video.downloader

**Comment by MD77MD** [comment]
that's really bad..  how can people do such immoral thing.

**Comment by MD77MD** [comment]
![Screenshot_20200621-212313_Galaxy Store](https://user-images.githubusercontent.com/63132171/85232137-822c5100-b405-11ea-8caf-503679a6757e.jpg)
this is my review.... I wanted to do at least something.

**Comment by gkeegan** [comment]
Could a link to this be provided? And do they have a link to source code?

**Comment by B0pol** [comment]
Thanks for the report! Please next time post in #539
