### ISSUE TITLE
Re-Try playing video on pop-up player queue when network error

### ISSUE THREAD

**Issue by rancidfrog** [TeamNewPipe/NewPipe#3806]
When playing video on pop-up player queue, a toast is displayed on network error/ bad reception.
There is no way to retry playing video.
Sometimes it takes a few seconds to display toast, which causes issues as more than one video should be queued and the link is lost. Link does not appear on history either.

Instead of a toast, maybe a dialog should appear with a retry button.
Also, the case where a second song also is queued, but bad connection causes network error should be handled as well so that both videos should be retried.

**Comment by Stypox** [comment]
Fixed in #3704
