### ISSUE TITLE
Android Q auto dark mode 

### ISSUE THREAD

**Issue by spectkiller** [TeamNewPipe/NewPipe#3807]
#### Describe the feature you want

ANDROID Q have introduced new automatic dark mode feature which make the apps to follow the system default theme.
For example :- If system default theme is light, the app (which supported this feature like all Google apps including YouTube) default theme will be light mode and vice-versa in dark mode 

Dev can also consider to give option in newpipe to choose between default dark theme as regular dark or complete black in app when system default theme set as dark 

#### Additional context

Here are some screenshots from swift backup app as a reference 
![Screenshot_20200622-204245358](https://user-images.githubusercontent.com/37000900/85305439-b158c600-b4ca-11ea-94bb-0b50427372ae.jpg)
![PicsArt_06-22-08 48 13](https://user-images.githubusercontent.com/37000900/85305483-be75b500-b4ca-11ea-901f-5cbe615c20bb.jpg)
![PicsArt_06-22-08 46 43](https://user-images.githubusercontent.com/37000900/85305484-bfa6e200-b4ca-11ea-98c1-38615f3fd0b7.jpg)
![PicsArt_06-22-08 45 41](https://user-images.githubusercontent.com/37000900/85305489-c03f7880-b4ca-11ea-86d4-a4017b2dfb33.jpg)

#### How will you/everyone benefit from this feature?

This feature will help those user including me :D who want to have light mode in newpipe during day and dark mode during night by simply changing the device theme.
This way all my apps will have dark theme including newpipe if I set the system default theme to dark and vice-versa if set the system default theme to light.

**Comment by Stypox** [comment]
#3420
