### ISSUE TITLE
playing in foreground inside basic view

### ISSUE THREAD

**Issue by brainchild0** [TeamNewPipe/NewPipe#3809]
Thank you to the maintainers and developers for undertaking this project.  While relying on YouTube as  a content source,  I also have relied on the *Vanced* modifications to contend with usability issues following from the *crippled by design* problem of the official client. Use of this combination of closed and nonstandard software is not optimal, and I am grateful to this team for providing an alternative.

However,  the official client currently has the advantage of readily supporting the  single most basic use case I can imagine, which is to play a video in the main view for that asset, without full screen,  simply by pressing the central *play* symbol, such that the only visual change is a still image being replaced by a moving one.

In the case of NewPipe, running the F-Droid distribution, version 0.19.5, I  not only find that this behavior is not the effect of pressing the symbol, but also find no way whatsoever to achieve it. Perhaps I have misunderstood the operation of the interface, or perhaps the application functions differently from its design  on my device.  

Nevertheless, I would urge better support for this functionality, whether the appropriate means  is a feature enhancement or a bug fix.

**Comment by MD77MD** [comment]
such feature is already in development (even better than youtube client😊)... please read this for more info #2907

**Comment by B0pol** [comment]
… meanwhile you can use the popup player and move it at top

**Comment by brainchild0** [comment]
Ok, well I was not aware that this work is ongoing. It seems that the contributor who submitted the PR has committed quite a bit of effort through several attempts to include his features. I watched his video  and feel that  he has made a strong demonstration for how the new features are a vast improvement for the user experience.  Hopefully he and the core contributors can overcome their technical and personal differences in order to enter the features into a release that will appear in the near future. I thank all of them for their contributions.

To be clear about my first comment,  I am not suggesting that NewPipe should try to mimic the  official YouTube client, or should include all the features of it. The official client,  both bloated and crippled, is not a good model.



However, building upwards from a basic foundation is more important than building outwards. I would suggest that any features that are important for familiarity and usability, even if they are common with the official client,  should have a higher priority, compared to  features that extend the capabilities beyond those of the official client.

**Comment by B0pol** [comment]
> Hopefully he and the core contributors can overcome their technical and personal differences in order to enter the features into a release that will appear in the near future

It should be released in 0.20.0, the next major version https://github.com/TeamNewPipe/NewPipe/milestones

**Comment by Stypox** [comment]
#2882
