### ISSUE TITLE
Someone on XDA took NewPipe, added ads and called it "BokeTube" - GPL Violation?

### ISSUE THREAD

**Issue by pizzadude** [TeamNewPipe/NewPipe#381]
I was browsing the apps & games forum on XDA and found this. According to the screenshots (didn't install it), it's just NewPipe with ads on top. I think this is a GPL violation. If so, it should be reported. I reported it to XDA but the moderator says they need proof. So I sent them the screenshots the dev posted which are hosted on TinyPic.

http://forum.xda-developers.com/android/apps-games/app-boketube-t3503301

Screenshots the dev provided, notice how it looks familiar...

http://i64.tinypic.com/2q9goxf.jpg
http://i63.tinypic.com/14awvmh.jpg
http://i67.tinypic.com/1grerl.jpg
http://i64.tinypic.com/rgwj6t.jpg
http://i66.tinypic.com/2u91oaa.jpg

**Comment by theScrabi** [comment]
Yes It's a shady fork, but I can't post into the thread since I'm not yet allowed to by XDA. Would someone want to do that for me?

**Comment by pizzadude** [comment]
The moderator closed the thread and removed the links from the post.

**Comment by theScrabi** [comment]
All right thanks to tho that moderator.
