### ISSUE TITLE
Ability to control playback speed until 3x through pop-up player

### ISSUE THREAD

**Issue by Y-T-G** [TeamNewPipe/NewPipe#3810]
#### Describe the feature you want

It would be nice if the playback speed can be adjusted until 3x in the pop-up player rather than just until 2x as is the case now.
#### Is your feature request related to a problem? Please describe it

I usually want to slow down a video playing at above 2x speed, for example 2.75x to 2.5x. I can't do it without going fullscreen. I can see the drop down list getting too long if options until 3x gets added. If it is a design choice, maybe the drop down list options can take into account the current playback speed. So if the speed is above 2x it can show the options until 3x and exclude the options below 1x, as there isn't usually a need for going from greater than 2x speed to less than 1x speed.

**Comment by Stypox** [comment]
Open the popup player queue from notification for better controls. Adding this to the popup player is not a good idea, since a huge menu would open every time instead of a simple spinner.
