### ISSUE TITLE
Poorer and Lower quality audio when streaming youtube videos in newpipe comparing to a web browser

### ISSUE THREAD

**Issue by fightthepower** [TeamNewPipe/NewPipe#3813]
I am using the latest version  0.19.5 of NewPipe and this problem exists only  in 

1. YouTube videos which are very older 

2. YouTube videos which have inherently poorer audio

Take this example YouTube video https://www.youtube.com/watch?v=EB5GbDSM5io , when played in NewPipe it has lower volume and it is harder to hear the sound. But the quality of audio increases significantly when playing the same video in a web browser. The poorer the quality of video it becomes tougher to hear the audio in NewPipe.

**Comment by eladkarako** [comment]
as far as I can see for audio only streams it has one m4a 128kbps and three opus at 120, 60, 48kbps.
and no video-audio combined stream (all other streams are video only webp and mp4). 

maybe it's a new thing for youtube..

when playing yt pairs v/a together. NewPipe too probably. maybe the bug 🐛 is in which NewPipe selects a low quality audio stream, regardless of the video quality.

I only speculate. 

I query the streams w/ dentex.youtube.downloader

![Screenshot_20200625-011923_YouTube Downloader](https://user-images.githubusercontent.com/415238/85633466-f8d58280-b681-11ea-8c19-ce2593aa96ab.jpg)

**Comment by opusforlife2** [comment]
@fightthepower Can you confirm that this happens when you use WebM? My guess is that you were using MP4 and the single m4a audio stream available is of poor quality.

**Comment by fightthepower** [comment]
@opusforlife2 yes the subtle but the problem still exists with webm also. I kindly request to reopen the issue.

**Comment by opusforlife2** [comment]
Thanks for confirming!

**Comment by Feuerswut** [comment]
Status?
