### ISSUE TITLE
the weird case of a zero byte video (ok when played on yt app)

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3814]
https://www.youtube.com/watch?v=PnF3LQoWsaQ 

(from https://www.youtube.com/playlist?list=PLv67DJABiuAifIkMCTT53YkYkiywp9OB2) 

ok when played on yt app, np and dentex.youtube.downloader which share similar way of extracting the encrypted signature acts same (weird) - NewPipe just shows the rotating loading animation, dentex.youtube.downloader explicitly shows 0 bytes. 

non of the streams working, 720p (webp), and 480p,360p,240p,144p.

It used to be unlisted, in a public playlist, I don't know if that matter, but I made it public.

v0.19.5

![Screenshot_20200624-234336_NewPipe](https://user-images.githubusercontent.com/415238/85625771-9cb83180-b674-11ea-81ea-19a8cf9425d5.jpg)

![Screenshot_20200624-234327_NewPipe](https://user-images.githubusercontent.com/415238/85625788-a3df3f80-b674-11ea-9f1b-65b614f5be9a.jpg)

Can it be a thing for newly uploaded videos (old videos loads ok).

Also those do not have ads (I never put ads on videos), but they have copyright claim (but are not blocked as far as I know).

![Screenshot_20200624-234918_YouTube Downloader](https://user-images.githubusercontent.com/415238/85626306-865ea580-b675-11ea-8865-4d9f2a8cf15c.jpg)

**Comment by Stypox** [comment]
I think this has the same cause as #2415

**Comment by eladkarako** [comment]
Interesting.  
I believe you might be right for HLS-streams,  
I query this video and it seems that most of the resolutions are DASH/HLS,  
I was pretty \~shocked\~ since I thought the lower resolutions were always classic-style one file v/a combined MP4. 

Apparently just the 'format-code-18' (360p) is the old-school MP4,  
but probably isn't being used since there are DASH/HLS alternatives for 360p too. 

it is probably there just for old web-clients. 

I think it only applies for new uploaded videos! 
if the video is old enough YouTube probably still stores the classic MP4 streams up until 720p probably (1080p was always split a/v but those were not HLS either, just two files).

..Woa! I need to remember that...!

<pre>
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz)
251          webm       audio only DASH audio  140k , webm_dash container, opus @160k (48000Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
134          mp4        640x360    DASH video  599k , mp4_dash container, avc1.4d401e, 30fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
136          mp4        1280x720   DASH video 2238k , mp4_dash container, avc1.64001f, 30fps, video only
18           mp4        640x360    360p  494k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 6.87MiB (best)
</pre>



<details>
<title>details gathered with YouTube-DL verbose mode</title>
<pre>
[youtube] PnF3LQoWsaQ: Downloading webpage
[youtube] {18} signature length 103, html5 player 68f00b39
send: b'GET /watch?v=PnF3LQoWsaQ&gl=US&hl=en&has_verified=1&bpctr=9999999999&disable_polymer=true HTTP/1.1\r\nHost: www.youtube.com\r\nCookie: PREF=f1=50000000&f6=8&hl=en\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3657.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Cache-Control: no-cache
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: Content-Encoding: gzip
header: Expires: Tue, 27 Apr 1971 19:44:06 GMT
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: Strict-Transport-Security: max-age=31536000
header: Content-Type: text/html; charset=utf-8
header: Date: Sat, 27 Jun 2020 23:16:22 GMT
header: Server: YouTube Frontend Proxy
header: X-XSS-Protection: 0
header: Set-Cookie: YSC=ao4f0bpAwX4; path=/; domain=.youtube.com; secure; httponly; samesite=None
header: Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
header: Set-Cookie: GPS=1; path=/; domain=.youtube.com; expires=Sat, 27-Jun-2020 23:46:22 GMT
header: Set-Cookie: VISITOR_INFO1_LIVE=VhxTVm6X680; path=/; domain=.youtube.com; secure; expires=Thu, 24-Dec-2020 23:16:22 GMT; httponly; samesite=None
header: Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube] {136} signature length 107, html5 player 68f00b39
[youtube] {247} signature length 103, html5 player 68f00b39
[youtube] {135} signature length 103, html5 player 68f00b39
[youtube] {244} signature length 103, html5 player 68f00b39
[youtube] {134} signature length 103, html5 player 68f00b39
[youtube] {243} signature length 103, html5 player 68f00b39
[youtube] {133} signature length 107, html5 player 68f00b39
[youtube] {242} signature length 107, html5 player 68f00b39
[youtube] {160} signature length 107, html5 player 68f00b39
[youtube] {278} signature length 107, html5 player 68f00b39
[youtube] {140} signature length 103, html5 player 68f00b39
[youtube] {251} signature length 107, html5 player 68f00b39
[youtube] PnF3LQoWsaQ: Downloading MPD manifest
[info] Available formats for PnF3LQoWsaQ:
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz)
251          webm       audio only DASH audio  140k , webm_dash container, opus @160k (48000Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
134          mp4        640x360    DASH video  599k , mp4_dash container, avc1.4d401e, 30fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
136          mp4        1280x720   DASH video 2238k , mp4_dash container, avc1.64001f, 30fps, video only
18           mp4        640x360    360p  494k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 6.87MiB (best)
send: b'GET /api/manifest/dash/expire/1593321382/ei/RtP3XvGpMY-hlQTwka6gBQ/ip/123.45.67.89/id/3e71772d0a16b1a4/source/youtube/requiressl/yes/playback_host/r2---sn-nhpax-ua8r.googlevideo.com/mh/sP/mm/31%2C29/mn/sn-nhpax-ua8r%2Csn-aigl6ned/ms/au%2Crdu/mv/m/mvi/1/pl/21/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1051250/vprv/1/mt/1593299731/fvip/2/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgNY1cXLjQc8oK9-vDIAqXtx3g14OZjjWT4UT5oHgK7JwCIQDKRvTjAvL6MV7xm4swhphi4KCeVdaPtFbVN3FNNJEBLw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAJGklCAkxFjg5aXaaX5Q659MYeT1XwFbGPxFq-fEiEVkAiEAiL4-YUgT2aqQnGpblC-pfXH66DymiNgAQW5gaNVZmJE%3D?disable_polymer=true HTTP/1.1\r\nHost: manifest.googlevideo.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3657.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: video/vnd.mpeg.dash.mpd
header: Date: Sat, 27 Jun 2020 23:16:25 GMT
header: Pragma: no-cache
header: Expires: Fri, 01 Jan 1990 00:00:00 GMT
header: Cache-Control: no-cache, must-revalidate
header: Content-Encoding: gzip
header: Server: HTTP server (unknown)
header: X-XSS-Protection: 0
header: X-Frame-Options: SAMEORIGIN
header: Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
</pre>
</details>

**Comment by Stypox** [comment]
@eladkarako check if #3803 fixes the issue

**Comment by eladkarako** [comment]
no mobile at the moment, it was smashed and diced by the teeth of my neighbour's dog "tiny" 🐶📱 (a 40Kg "puppy"). But I'm without you guys in spirit!
