### ISSUE TITLE
smooth transition between modes

### ISSUE THREAD

**Issue by alexmo1997** [TeamNewPipe/NewPipe#3816]
newpipe has the modes to play videos in fullscreen, popup and in background. It would be a great enhancement if when switching between those modes, it would, like in the youtube video player, not stop the playing for a second or so to restart again, but at least have the audio keep running.

**Comment by MD77MD** [comment]
#2907 this is already in development.

**Comment by alexmo1997** [comment]
That's great! I did not know that this PR would solve this. Should this be closed or kept open until fixed by merging it?

**Comment by wb9688** [comment]
Issues should be kept open until the relevant PR has been merged.

**Comment by Stypox** [comment]
#2863
