### ISSUE TITLE
YT OPLM file import issue

### ISSUE THREAD

**Issue by wwg1wga904** [TeamNewPipe/NewPipe#3818]
I have NewPipe v 0.17.3 installed on my android phone and i can't import my YT (OPLM) subscription manager export file into the app. When i click Import file and go to the path where the file is located, NewPipe doesn't see the file.

**Comment by wwg1wga904** [comment]
Just installed the latest 0.19.5 and still having same issue as with version 0.17.3. it doesn't see the file.

**Comment by wb9688** [comment]
What Android version are you using? Is the file on an external storage device (e.g. SD card)? Does it work with the APK in #3777?

**Comment by wwg1wga904** [comment]
wb9688 - thanks for your reply

android 8.1.0 LG Stylo 4. I have tried to access from the internal storage and SD card and the same result.

**Comment by belindasuvaal** [comment]
I have the same issue, on both 0.19.6, 0.19.7 and newest 0.19.8 version. Opml file on internal storage (android 8.0), error message says invalid zip file.

**Comment by wb9688** [comment]
@belindasuvaal: You should import the OPML in Subscriptions -> Subscriptions -> Import from -> YouTube.

**Comment by wb9688** [comment]
@belindasuvaal: You should import the OPML in Subscriptions -> Subscriptions -> Import from -> YouTube

**Comment by polyesterbebe** [comment]
> 
> 
> @belindasuvaal: You should import the OPML in Subscriptions -> Subscriptions -> Import from -> YouTube.

importing subscribtions through the settings kept giving me "No Valid ZIP file"; importing through subscriptions worked for me

**Comment by vuurvogelblog** [comment]
> > @belindasuvaal: You should import the OPML in Subscriptions -> Subscriptions -> Import from -> YouTube.
> 
> importing subscribtions through the settings kept giving me "No Valid ZIP file"; importing through subscriptions worked for me

Yes, worked for me too on android 8. Have another android 6 phone on which it worked through settings/import. Happy both phones have smooth synched Newpipe running, thumbs up for the newpipe Team for their new version.

**Comment by Stypox** [comment]
Seems like #2784
