### ISSUE TITLE
Implementing youtube autoplay on newpipe

### ISSUE THREAD

**Issue by jul-debug** [TeamNewPipe/NewPipe#3820]
#### Describe the feature you want

It would be cool to implement the autoplay next song/video option that youtube (desktop mode) has to NewPipe. This would make the app easier to use in a lot of situations, e.g. a party or when studying/working.

#### Is your feature request related to a problem? Please describe it

No, not that I'm aware of.

#### Additional context

/

#### How will you/everyone benefit from this feature?

This could potentially add a _second_ USP to the NewPipe app (the other one being playing videos in background, I'm sure) since this feature could have the potential to convert this app into an alternative for streaming platforms out there. Indeed, it could let you "discover" new music, that can be played in the background, using Google's algorithms. 

Other than that, such a feature would surely improve the UX of those who already use the app.

**Comment by ggNovelty** [comment]
Settings > Video & audio > Auto-queue next stream

**Comment by Stypox** [comment]
Or under any video detail -> Autoplay toggle
