### ISSUE TITLE
Bring back the old simple "what's new" alongside the current feed

### ISSUE THREAD

**Issue by ofiala-a51** [TeamNewPipe/NewPipe#3821]
I am not sure how many people feel the same, but I actually preferred the old what's new design as I always knew what is the last video a channel has released. The new feed has a great advantage of showing more than one latest video so that you won't miss any new stuff, but it's disadvantage is that if you'l are subscribed to a channel that posts a lot, then the other channels' videos might get a little buried by it. I know you can create a separate group just for those frequently posting channels, but I feel like separating more active channels from the rest in this way isn't the best solution. So what I am proposing is to offer the old what's new behavior as an alternative to the current feeds. There could be a switch in the settings that would change between the old and the new behavior. This would add options so that people can turn on the old design if it suits them better while it wouldn't impact the current users of feeds in any way as that would remain the default.

**Comment by Stypox** [comment]
#3315
