### ISSUE TITLE
A global language filter

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#3824]
#### Describe the feature you want

It would be nice if a global language filter can be implemented so that newPipe would only show videos from selected languages... the idea was inspired from Thorium project, they have an option in settings where you can select multiple languages then the app would only show videos from those selected languages globally, this includes trending videos, searches,...etc.
#### Is your feature request related to a problem? Please describe it

This would solve the problem when I search for videos on a certain subjects... many videos would show in the search list with languages that I cannot understand, to the point where sometimes they would overtake the whole search list... for example: if I search for "redmi note 9", most of the videos that come up are in Hindi. but there is no indication to whether it's in English or Hindi (because they use English titles). this forces me to open them one by one. 
#### How will you/everyone benefit from this feature?

it would make our lives a lot easier and stop wasting our precious time and data for opening videos we do not want. 
also this would stop the false increase in views number which I assume is a strategy used by some channels.

**Comment by Stypox** [comment]
Unfortunately there is no way to determine the language of a youtube video before fully fetching its info. Also, content country does not work and that's a known issue (only english is supported).

**Comment by B0pol** [comment]
> Unfortunately there is no way to determine the language of a youtube video before fully fetching its info. Also, content country does not work and that's a known issue (only english is supported).

Even when you fetch it. Unless I don't know something, but auto-generated captions are not reliable

**Comment by MD77MD** [comment]
although skyTube uses newPipe extractor library, it has this feature implemented. the filtering in note perfect by any means, but still looking into how it's implemented could be useful.
https://skytube-app.com

**Comment by leo-wiz** [comment]
Ukraine here. Our country was being Russified for centuries. Russia spent lots of money for this.
We really need language restrictions to protect our kids from russification here in Ukraine.
It would be great to protect the content-language option by password so a kid can't change the option.
Thanks.
