### ISSUE TITLE
Url parsing exception at recommended videos

### ISSUE THREAD

**Issue by domitori3** [TeamNewPipe/NewPipe#383]
{ "user_action": "requested stream", "exceptions": [ "java.lang.IllegalArgumentException: supplied String is not a valid Youtube URL\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:54)\n\tat org.schabi.newpipe.detail.StreamInfoWorker$StreamExtractorRunnable.run(StreamInfoWorker.java:63)\n\tat java.lang.Thread.run(Thread.java:856)\n" ], "os": "Linux Android 4.0.3 - 15", "time": "2016-11-09 12:52", "ip_range": "130.180.0.0", "request": "", "package": "org.schabi.newpipe", "service": "Youtube", "content_language": "en", "user_comment": "", "version": "0.8.5" }

steps to reproduce: 
1. login to your youtube account in a browser (opera mini in my case) 
2. open one of subscribed videos, and choose to play it via newpipe 
3. open one of listed recommended videos

expected result: 
recommended video opens. since it listed anyway

actual result: 
exception about url parsing occurs

additional info: 
issue is not reproducible, if you open any video from newpipe search, and try to open any recommended video. reproduces only from 'logged in' subscribed videos captured from a browser.

**Comment by domitori3** [comment]
Sorry, I've written "recommended" instead of "related". Related ones. That are listed below the video. Thanks.

**Comment by domitori3** [comment]
Issue is still reproducible on NewPipe 0.8.6

**Comment by theScrabi** [comment]
For crashes please use the newpipe internal crash reporter.

**Comment by theScrabi** [comment]
However can you try to paste the url here?

**Comment by domitori3** [comment]
Additional tests uncovered origin of the issue: it's all about URL of mobile version of YouTube. If we do share the following URL to NewPipe: 
https://m.youtube.com/watch?v=K-Ec7gzVZv0&itct=CM4FEKQwGAAiEwj3-q7O4qvRAhUJfxwKHZocBBwyCmctdnJlYy1yZWNaDUZFcmVjb21tZW5kZWQ%3D&client=mv-google&gl=UA&hl=en
it would open correctly, but choosing related videos would throw an exception. 

But the same video shared as: 
https://www.youtube.com/watch?v=K-Ec7gzVZv0&itct=CM4FEKQwGAAiEwj3-q7O4qvRAhUJfxwKHZocBBwyCmctdnJlYy1yZWNaDUZFcmVjb21tZW5kZWQ%3D&client=mv-google&gl=UA&hl=en&persist_app=1&app=desktop
would work just fine. 

It seems, there is some incorrect handling of "m." links.

**Comment by theScrabi** [comment]
looks like it. The code to that error can be found [here](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamUrlIdHandler.java#L47).

**Comment by theScrabi** [comment]
Nah also for me it works. Please try the newest version.

**Comment by topviral** [comment]
Here how the error coming on this page : https://www.youtube.com/watch?v=2f7RD47Kkws i am not able to see the video clearly any person update this
