### ISSUE TITLE
Error opening player from other app

### ISSUE THREAD

**Issue by yxd0018** [TeamNewPipe/NewPipe#3830]
It seems the problem of opening shared link from other app comes back again. 
Here is the error:

{"user_action":"requested stream","request":"vnd.youtube:9jTcPJDZrK0, opened with background_player","content_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.19.5","os":"Linux Android 10 - 29","time":"2020-06-29 18:12","exceptions":["org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14935)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.Single.subscribe(Single.java:3652)\n\tat org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:666)\n\tat org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:638)\n\tat android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)\n\tat android.os.Handler.dispatchMessage(Handler.java:107)\n\tat android.os.Looper.loop(Looper.java:214)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\n"],"user_comment":""}

**Comment by Stypox** [comment]
The issue here has nothing to do with opening links, instead there are problems with the video itself, probably being unavailable or deleted. And since you are opening the video by link there is no way for NewPipe to tell you that the video is unavailable but to crash
