### ISSUE TITLE
Incorrect video length in playlist

### ISSUE THREAD

**Issue by StructuralFailure** [TeamNewPipe/NewPipe#3831]
Sometimes, NewPipe displays the wrong video length in the preview when scrolling through a list of videos, e.g. in a playlist or when searching. It happens especially with longer videos (> 1h), where the app will incorrectly state that the video is only about half an hour long.

At least on my end, it can be reproduced with the video that shows up when you search for "Browser hacking: Painting the text selection". The video is 1:27:44 long, which is correctly displayed once you open the video's page, but the search result list incorrectly states 28:45.

**Comment by wb9688** [comment]
Already fixed
