### ISSUE TITLE
Using Invidious links in Newpipe to watch all videos

### ISSUE THREAD

**Issue by Chilled-ops** [TeamNewPipe/NewPipe#3832]
Using Invidious links in Newpipe to watch all videos,
https://invidio.us/

because YouTube website to record IP address and all the using website records by IP address, and others information. Some like UntrackMe:

UntrackMe (Transform Youtube and Twitter links into Invidious and Nitter links) - https://f-droid.org/app/app.fedilab.nitterizemelite

Invidious is included all the videos of YouTube.

**Comment by wb9688** [comment]
This is a duplicate. Btw it's already in development at TeamNewPipe/NewPipeExtractor#352
