### ISSUE TITLE
No images 

### ISSUE THREAD

**Issue by joksim** [TeamNewPipe/NewPipe#3834]
Starting from some time in the past 24 hours, no images are shown for videos, channels, etc.

![Screenshot_20200630_105651_org schabi newpipe](https://user-images.githubusercontent.com/460917/86106118-78b77e80-bac0-11ea-8f5a-5bf880e6570e.jpg)
![Screenshot_20200630_105706_org schabi newpipe](https://user-images.githubusercontent.com/460917/86106158-84a34080-bac0-11ea-92bb-0d46f1521176.jpg)

**Comment by wb9688** [comment]
What Android version are you using? What VPN are you using? Does it work when you turn off that VPN?

When you go to www.youtube.com in your browser on your phone in desktop mode, do you see the thumbnails?

If you see the thumbnails then, could you install a debug version of NewPipe, connect your phone to your PC through USB, open Chrome, go to `chrome://inspect`, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send me that HAR? Then I might be able to fix this issue.

**Comment by joksim** [comment]
Sorry, I was making a quick issue on mobile. Now I'm on a PC and gonna file appropriately....





### Version

- NewPipe 0.19.5 installed from the github release page

### Steps to reproduce the bug

Open the application and images are no longer showing up. I tried wiping the cache (Settings -> History & Cache -> Clear data (clicked all of them).



### Expected behavior

Images should be showing

### Actual behaviour

Images not showing

### Screenshots/Screen recordings

See above

### Logs

None to report, not a crash



### Android version and phone
Android 10, Huawei Honor 8xm (JSN-L21), EMUI version 10.0.0

### VPN
I use DNS66 from fdroid for add blocking. Same result with or without it on...

No error is reported by NewPipe. Tried youtube on FF Preview and Brave, both showing images in mobile and desktop mode.

I'll try to make a debug report soon...

**Comment by gkeegan** [comment]
Disable DNS66 *and clear NewPipe's cache*. That will force those images to reload if it is in fact a problem with the blocker.

**Comment by Stypox** [comment]
Also, are you sure you have "Settings -> Content -> load thumbnails" active?

**Comment by joksim** [comment]
My bad, I didn't realize that option was unchecked.
Please ignore my issue and forgive my ignorance
