### ISSUE TITLE
How to go from fullscreen to detail view?

### ISSUE THREAD

**Issue by darkenedcolossal** [TeamNewPipe/NewPipe#3835]
When I open a link in Newpipe it goes to background player. Fron there I can switch to main and then it is fullscreen. But I want the detail page with video description, comments etc. How can I achieve that?
Was this the right place to ask such a question?

**Comment by B0pol** [comment]
Long press the video, click on details

<sup>Otherwise you could just click on the title when #3808 will be merged, probably not in the next version</sup>

**Comment by darkenedcolossal** [comment]
> Long press the video, click on details
Ahh, this is how we do it. Directly from the background player! :) Funny there is no direct way from fullscreen mode... But this should not end up in a feature request but in a **thank you**. :)

**Comment by hunkjazz** [comment]
In what version this feature is implemented?

I can't reproduce steps mentioned by @B0pol.

**Comment by Stypox** [comment]
@hunkjazz he is talking about long pressing videos in background/popup queues
