### ISSUE TITLE
UI change

### ISSUE THREAD

**Issue by killk4809** [TeamNewPipe/NewPipe#3836]
#### Describe the feature you want

A more YouTube like UI. I get that you don't want to copy them, but I'm not asking for a 100% copy. I'm just asking for a YouTube **like** UI; simulator to YouTube UI but with defining differences.
#### Is your feature request related to a problem? Please describe it

The current UI is hard/weird to navigate and somethings it's just "why?". I often find myself having to repeat the same action because I tap something and it just sends me straight back to the beginning. I often find myself looking for something and taking 2-3mins to find it when it should have been 1-4 seconds. These are problems that discourages everyone from using your app as a replacement for YouTube, ect. and it hurts newcomers the most. The UI is the face of your app and if it's not easy to use then ppl won't use your app. Making it more like YouTube would fix everything and be the easiest/most effective fix. 

#### How will you/everyone benefit from this feature?

This will help everyone easier understand and use the apps user interface.

#### Thank you :)

**Comment by Stypox** [comment]
#2882
