### ISSUE TITLE
Please make your metadata OPTIONAL!

### ISSUE THREAD

**Issue by shuttittuppitt** [TeamNewPipe/NewPipe#3839]
I used "New pipe" (0.19.5) to download a video from youtube. The video plays as expected. However, I looked at the video with "Media info" for android, & I found this.

"Title: ISO Media file created in NewPipe (A libre lightweight streaming frontend for Android)."

The addition of this METADATA is a privacy concern. It's also not needed in order to PLAY a video. Plus, adding any metadata to ANY file always increases that file's size.

Give us the OPTION of NOT adding ANY metadata to a downloaded video.

**Comment by TobiGr** [comment]
https://github.com/TeamNewPipe/NewPipe/blob/9cf76a918ef9a7dc0d2c18f6913bea28256f72f4/app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java#L851-L867
Line 856 - 866 should be removed.

**Comment by wb9688** [comment]
@TobiGr: You can't just remove all those bytes and expect it to work…

**Comment by TobiGr** [comment]
That's what we need to test.  I guess, we can replace them with `0x00`

**Comment by wb9688** [comment]
@TobiGr: No, you should read what the specification says, and possibly look at other implementations, not just guess

**Comment by TobiGr** [comment]
Found one  more:

https://github.com/TeamNewPipe/NewPipe/blob/9cf76a918ef9a7dc0d2c18f6913bea28256f72f4/app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java#L729

**Comment by mgolden356** [comment]
@shuttittuppitt I can't find this metadata on properties on any of my file manager apps. How would I be able to view this metadata?

**Comment by shuttittuppitt** [comment]
I found it when I used this on a video that I downloaded. I usually use it to find a video's bit rate, among other things.

https://play.google.com/store/apps/details?id=net.mediaarea.mediainfo

**Comment by 07416** [comment]
This metadata also draws attention to NewPipe. I don't know what effect a DMCA takedown would have on the development.

**Comment by 07416** [comment]
>Please make your metadata OPTIONAL!

And off by default, of course.

**Comment by TobiGr** [comment]
We will remove that completely. @kapodamy Do you have time to help us with that?

**Comment by shuttittuppitt** [comment]
@TobiGr
I just remembered that according to "Media info", that same metadata is included not only for the "video" part of the downloaded video, but also for the "audio" part too. So there may be another part of the source code that has it specifically for the audio part.

**Comment by kapodamy** [comment]
@TobiGr 
Yes i can, but dont scare me
