### ISSUE TITLE
Music won't load at all. 

### ISSUE THREAD

**Issue by LoneStarGamer** [TeamNewPipe/NewPipe#3844]
Videos will load just as long as it doesn't contain music.

 The image below is what happens when I click on videos with music. 

![Screenshot_20200703-193917_NewPipe](https://user-images.githubusercontent.com/67810795/86502082-ea175b80-bd64-11ea-97ba-cdcf0b81200b.jpg)

The image below is to show that the app works just fine when loading videos that don't contain music. 

![Screenshot_20200703-194302_NewPipe](https://user-images.githubusercontent.com/67810795/86502152-90636100-bd65-11ea-860f-2a67a7b26651.jpg)

**Comment by snappyapple632** [comment]
Please follow the issue template for reporting Guru Meditation errors. Screenshots of them are not helpful. Thank you!

**Comment by wb9688** [comment]
Upgrade to the latest version

**Comment by LoneStarGamer** [comment]
But I have the latest version.

**Comment by wb9688** [comment]
No, you don't. The screenshot shows you're using v0.19.3, while v0.19.5 has been released a while ago.

**Comment by LoneStarGamer** [comment]
Sorry, I just noticed that. How do I download the new version? It isn't
showing on F-Droid.

**Comment by LoneStarGamer** [comment]
That's the version it shows as the newest version.

**Comment by wb9688** [comment]
Have you done a pull-to-refresh on the main page of F-Droid's app? v0.19.5 has been on F-Droid since 4 June.

**Comment by LoneStarGamer** [comment]
Thank you.

**Comment by LoneStarGamer** [comment]
But why doesn't it update on it's own?

**Comment by gkeegan** [comment]
That is how F-Droid works. If you want it to automatically refresh repositories that is on the F-Droid client, nothing to do with NewPipe.

**Comment by LoneStarGamer** [comment]
Alright, thanks.
