### ISSUE TITLE
Unable to import subscriptions from .xml file

### ISSUE THREAD

**Issue by ShayneIsAlive** [TeamNewPipe/NewPipe#3849]
### Version
0.19.5, on Pixel 3 with CalyxOS on Android 10

### Steps to reproduce the bug
Go to "Subscriptions" tab, click on "Import from previous export", choose a " subscription_manager.xml" from a recent export.

### Expected behavior

Subscriptions imported from file to app.
### Actual behaviour

Error message, "Could not import subscriptions".
### Screenshots/Screen recordings

![Screenshot_20200706-103929](https://user-images.githubusercontent.com/58682442/86568998-72207f80-bf76-11ea-9f08-afa820445252.png)

**Comment by wb9688** [comment]
`subscription_manager.xml` isn't a previous export from NewPipe. Use the appropriate option i.e. "YouTube".

**Comment by ShayneIsAlive** [comment]
My bad, used the file from "Youtube" in "Previous export". Now works as intended, thanks. Feel free to close
