### ISSUE TITLE
NewPipe @ 33c3

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#385]
Hello,

I yust wanted to announce that I will give a 1 hour talk about NewPipe.
I will talk about how NewPipe is build internally, how you can help, and where it goes in the future.
You can find more about it here:
https://events.ccc.de/congress/2016/wiki/Session:NewPipe

rgds Schabi

**Comment by comradekingu** [comment]
I went looking for this a day early, and on the actual day time just flew by.
Is there an offline version anywhere?

**Comment by theScrabi** [comment]
No Im sorry, but I can upload the slides. However they wouldn't tell you much.

**Comment by disrupted** [comment]
wish this talk was recorded for people who didn't have the chance to be there

**Comment by theScrabi** [comment]
All right, I ma do a Video on it :)

**Comment by disrupted** [comment]
where can I find the video?

**Comment by theScrabi** [comment]
There is no video. The room where I hald the talk didn't have a camera :/
I may have to do a statement one day.

**Comment by disrupted** [comment]
yeah, that's what you told me. I thought you wanted to do one though after your comment.

> All right, I ma do a Video on it :)
