### ISSUE TITLE
Add background play when in full screen

### ISSUE THREAD

**Issue by JeffeTheExtremo** [TeamNewPipe/NewPipe#3850]
It'd be more convenient to add this so that way you wouldn't have to use the minimize button or listen button in order to listen in the background/when your phone is off and you could have a full screen video without having to replay it.

**Comment by Stypox** [comment]
The way it works is intended (I personally prefer the player to stop playing when I turn off my phone, and it was designed for this purpose). The popup implements the behaviour you want.
