### ISSUE TITLE
YT URL time argument not passed in Discord

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#3851]
### Version

-0.19.5

### Steps to reproduce the bug

1. Send or Receive URL to a YT video containing the time argument.
2. Click on it and wait for NewPipe to open it.

### Expected behavior

The video is supposed to start playing on the time in the "?t=" or "&t=" in seconds.

### Actual behaviour

The video starts playing from the beginning no matter what time is passed.

### Screenshots/Screen recordings

![Screenshot_20200705-225143_Discord~2](https://user-images.githubusercontent.com/26146502/86582383-d8f76600-bf81-11ea-8fe1-f83d5ab87138.jpg)
![Screenshot_20200705-225149_NewPipe](https://user-images.githubusercontent.com/26146502/86582400-ddbc1a00-bf81-11ea-86e7-483e3e3bb0e5.jpg)

**Comment by wb9688** [comment]
That feature works for me. Could you install the app "Intent Intercept" from F-Droid, click on the link that doesn't work, open it with "Intercept the Intent", click the copy button at the top, and post that text here?

**Comment by kubo6472** [comment]
> That feature works for me. Could you install the app "Intent Intercept" from F-Droid, click on the link that doesn't work, open it with "Intercept the Intent", click the copy button at the top, and post that text here?

I can try, but was adding that discord stuff moments before your reply.

**Comment by kubo6472** [comment]
Okay, this is 100% discord side issue. Closing it here. It doesn't work when I try loading the video from the big preview (seen on pic 1 in my original post). But DOES WORK when I click on the URL. Sorry for wasting your time.

**Comment by wb9688** [comment]
Does this issue happen in the official YouTube as well? If not, could you still please do the Intent Intercept steps? It might be possible that Discord uses another format for passing the time that isn't yet recognized by NewPipe.

**Comment by kubo6472** [comment]
### Clicking the URL (passes the time): intent://www.youtube.com/watch?v=QTSS8BM6emE&t=662s#Intent;scheme=https;launchFlags=0x3000000;i.android.support.customtabs.extra.TITLE_VISIBILITY=0;i.android.support.customtabs.extra.TOOLBAR_COLOR=-13223617;B.android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true;end
------------
ACTION: android.intent.action.VIEW
DATA: https://www.youtube.com/watch?v=QTSS8BM6emE&t=662s
URI: intent://www.youtube.com/watch?v=QTSS8BM6emE&t=662s#Intent;scheme=https;launchFlags=0x3000000;i.android.support.customtabs.extra.TITLE_VISIBILITY=0;i.android.support.customtabs.extra.TOOLBAR_COLOR=-13223617;B.android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true;end
FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP
EXTRAS:
1 EXTRAS:
Kann Extras nicht lesen

------------
AUFRUFBARE ACTIVITIES
YouTube (com.google.android.youtube - com.google.android.youtube.UrlActivity)
NewPipe (org.schabi.newpipe - org.schabi.newpipe.RouterActivity)
Samsung Internet (com.sec.android.app.sbrowser - com.sec.android.app.sbrowser.SBrowserLauncherActivity)

### Clicking the preview (does not pass the time): intent://www.youtube.com/embed/QTSS8BM6emE?start=662s#Intent;scheme=https;launchFlags=0x3000000;i.android.support.customtabs.extra.TITLE_VISIBILITY=0;i.android.support.customtabs.extra.TOOLBAR_COLOR=-13223617;B.android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true;end
------------
ACTION: android.intent.action.VIEW
DATA: https://www.youtube.com/embed/QTSS8BM6emE?start=662s
URI: intent://www.youtube.com/embed/QTSS8BM6emE?start=662s#Intent;scheme=https;launchFlags=0x3000000;i.android.support.customtabs.extra.TITLE_VISIBILITY=0;i.android.support.customtabs.extra.TOOLBAR_COLOR=-13223617;B.android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true;end
FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP
EXTRAS:
1 EXTRAS:
Kann Extras nicht lesen

------------
AUFRUFBARE ACTIVITIES
YouTube (com.google.android.youtube - com.google.android.youtube.UrlActivity)
NewPipe (org.schabi.newpipe - org.schabi.newpipe.RouterActivity)
Samsung Internet (com.sec.android.app.sbrowser - com.sec.android.app.sbrowser.SBrowserLauncherActivity)

### The YouTube App copies NewPipe's behavior
Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: wb9688 <notifications@github.com>
Datum: 06.07.20 12:26 (GMT+01:00)
An: TeamNewPipe/NewPipe <NewPipe@noreply.github.com>
Cc: Jakub <kubo6472@gmail.com>, State change <state_change@noreply.github.com>
Betreff: Re: [TeamNewPipe/NewPipe] YT URL time argument not passed in Discord (#3851)


Does this issue happen in the official YouTube as well? If not, could you still please do the Intent Intercept steps? It might be possible that Discord uses another format for passing the time that isn't yet recognized by NewPipe.

**Comment by Stypox** [comment]
@kubo6472 does that intent work or not?

**Comment by kubo6472** [comment]
Clicking on the preview in discord app (shown on pic 1 in the original post) does not start the video on the desired timestamp specified by the argument.



Von meinem Samsung Galaxy Smartphone gesendet.

**Comment by Stypox** [comment]
And what's the intent for clicking on the preview?

**Comment by kubo6472** [comment]
The second one, titled "clicking on the preview"



Von meinem Samsung Galaxy Smartphone gesendet.

**Comment by wb9688** [comment]
Apparently GitHub messes up your e-mail's formatting.

Anyway the issue is that embeds use start= instead of t=, which NewPipe doesn't know. I'll fix this issue later today.
