### ISSUE TITLE
Popup player closing when battery charges to full

### ISSUE THREAD

**Issue by xvwyh** [TeamNewPipe/NewPipe#3852]
### Version
Compiled from faa6cb5c7d40796b3fd854eb3079dd525e8065fe with some minor custom UI changes that are unrelated to the issue. But it's been happening throughout the entire time I've been using NewPipe, which is around 1.5 years at minimum.

### Steps to reproduce the bug
1. Let the battery charge percentage drop
2. Open a video in popup player, paused
3. Plug the charger into your device, leave it be, let the screen turn off
4. Later, after the device has been charged to 100%, discover that the popup player has been closed

### Expected behavior
Popup player should never be closed automatically unless the system is stressed for resources.

### Actual behaviour
Popup player closes for an unknown reason whenever the device is charged to 100%. I don't know if this is a problem with just my device (Lenovo K6 Note), but I've never experienced any other app closing except for NewPipe popup player. Haven't tested the background or fullscreen player.

I've never been able to pinpoint the exact moment the player closes, as the prospect of watching my phone charge isn't particularly enticing to me, but it's a 100% track record that whenever I leave my device to charge fully I end up with the player closed. Charging it NOT to 100% does not close the player.

It doesn't seem like the player is being closed gracefully, because the progress into the video isn't getting saved when the player closes in this way.

**Comment by Stypox** [comment]
What a strange issue... I don't know if this is related to NewPipe, since if the app gets force closed there is not much that can be done about it

**Comment by opusforlife2** [comment]
@xvwyh Still an issue with 0.20.0?

**Comment by xvwyh** [comment]
Tried charging up 4 times so far, and it hasn't closed on me yet, so I suppose it's fixed.

**Comment by xvwyh** [comment]
Although... 2 out of these 4 times the popup player would refuse to display the video. Sound would play as normal, but a blank black background would be displayed instead of the video. Sometimes, when resizing the popup, for a short instant a video frame would become visible that was last seen before the screen was turned off, albeit I cannot yet confirm if this problem only occurs while charging or if it can happen at any time.

**Comment by opusforlife2** [comment]
Make sure you open a new issue once you figure it out.
