### ISSUE TITLE
Videos get added to playlist out of nowhere when using "Play on background" mode

### ISSUE THREAD

**Issue by ludinenzo** [TeamNewPipe/NewPipe#3856]
### Version

-0.19.5

### Steps to reproduce the bug
1. Start playing any video in background mode.
2. Click on the notification to go to the playlist.

### Expected behavior

That video and ONLY that video is seen on the playlist.
### Actual behaviour

Another video (seemingly from the "related videos" section) gets added to the playlist. When selecting that video, another one appears on the playlist out of nowhere. When playing that new one, another one appears, and so on...

**Comment by B0pol** [comment]
It is the expected behaviour since auto-queue next stream is enabled. If you don't want this, go to `Settings -> Video & Audio -> auto-queue next stream` and disable it
