### ISSUE TITLE
Add language selectors for new translations

### ISSUE THREAD

**Issue by jwtiyar** [TeamNewPipe/NewPipe#3858]
Hey
I did Translated NewPipe to Central Kurdish from Weblate, When it will be merged to the app?

**Comment by wb9688** [comment]
We only merge Weblate commits just before a release. The next release, v0.19.6, should happen in about a week.

**Comment by jwtiyar** [comment]
> We only merge Weblate commits just before a release. The next release, v0.19.6, should happen in about a week.

Thank you bro.

**Comment by B0pol** [comment]
We need to add it in the selector. Thus I reopen this issue

**Comment by TobiGr** [comment]
6 languages were added in 0.19.6: `kab` `jv` `bn-rlN` `ar-rLY` `af` `ckb`

**Comment by jwtiyar** [comment]
Thanks
