### ISSUE TITLE
search videos within a channel

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#3859]
#### Describe the feature you want

I wish if you can add the ability to search videos within a channel. this include searching within all videos or searching within a playlist from that channel.
#### Additional context

I'm not sure if searching local playlists and history falls within this feature but I wish it can be added too.

#### How will you/everyone benefit from this feature?

YouTube had this feature but was removed it, probably to make people waste more valuable time finding a video while watching a couple more videos along the way.

many times I would want a video from a certain channel perhaps to compare another product or a follow-up. or maybe search for another topic but from the same channel because I like they way he explaine's things. everyone has a different reasons to use this feature but I guarantee it will benefit us all.

**Comment by Stypox** [comment]
#2414
