### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by anilsarwal** [TeamNewPipe/NewPipe#3860]
Could you please improve the sound. The other app like thop TV provide 5.1 channel sound. Thanks

**Comment by wb9688** [comment]
If you could link any videos that actually has 5.1 sound. So far I haven't found any.

Also, please just fill in the issue template.

**Comment by Stypox** [comment]
"thop TV" is for TV channels, not for YouTube. If TV channels provide 5.1 channel sound, that doesn't mean Youtube does. So this is not possible for Youtube.
