### ISSUE TITLE
disable duplicate videos on bookmarked playlists or help the user remove it

### ISSUE THREAD

**Issue by hunkjazz** [TeamNewPipe/NewPipe#3865]
#### Describe the feature you want

I think it would be nice if you add a feature that would not allow 
users to add duplicate videos to bookmarked playlists.

Optionally, or on top of that, this should be considered as well:

Allowing users to remove duplicate videos from bookmarked playlists.

#### Is your feature request related to a problem? Please describe it

This feature would solve common issues, like:

- adding duplicate videos to a playlist;
  - when user is not sure whether it was added before.
- playlists bloated with duplicate videos.

#### Additional context

disabling duplicate videos

In this first option: when adding a duplicate video, the user would be 
adverted that it is bookmarked already. Nothing else.

removing duplicate videos

- users would need to go to its bookmarked playlist page;
- tap kebab menu (top right corner);
- tap "remove duplicate".

#### How will you/everyone benefit from this feature?

From my experience: I can say that this would save users time and 
patience, because prior to this feature we are required to:

- check whether video is present on bookmarked playlist;
- remove duplicate videos, one by one, if failing to do the former.

This is, especially, painful when we are talking about huge playlists. 
Because it's large and we don't have a feature to search videos on 
bookmarked playlists, users have read each video title, until the 
duplicate video is found.

Can you imagine going through a 300 videos playlist, in order to avoid 
playing the same stuff multiple times? _let the machines do it..._

**Comment by Stypox** [comment]
#1473
