### ISSUE TITLE
unlink background playback speed controls from popup and main player

### ISSUE THREAD

**Issue by hunkjazz** [TeamNewPipe/NewPipe#3866]
#### Describe the feature you want

I think it would be nice if you could add a feature under background
"playback speed controls" that would unlink its settings from popup 
and main players.

example:

>- [ ] link to other players

#### Is your feature request related to a problem? Please describe it

Users, mainly watch videos on popup and main player. Now, when it comes 
to listening to songs they go to background player.

Because "playback speed controls" are not unlinked, users need to 
tweak it every time they want to listen to a song. 

This is because songs quality are easily affected by changes in _tempo_ 
and _pitch_.

#### Additional context

It should be unlinked by default.

When re-linking players, popup and main player settings must remain 
and be addressed to background player.

If changes in _tempo_ and _pitch_  does not affect a user, it can 
always disable unlinking:

>- [x] link to other players

#### How will you/everyone benefit from this feature?

When users want to listen to a songs playlist, they'll switch 
to background player, likely.

If the background player is unlinked from other players, it will not be 
necessary to reset "playback speed controls" settings.

**Comment by Stypox** [comment]
I second this, but unfortunately this wouldn't be a good UX after Unified UI is merged. Since there will only be one player, I think it would be confusing for the user if the speed changed suddenly when he switched, etc.
