### ISSUE TITLE
[QUESTION] What are the consequences of bookmarking a YouTube public playlists?

### ISSUE THREAD

**Issue by hunkjazz** [TeamNewPipe/NewPipe#3868]
I noticed that we can bookmark these playlists but they are not editable.

Does that mean NewPipe will be constantly fetching for updates for it, 
like title changes and video addition/removal?

If not: wouldn't it be better to refactor this feature so these playlists 
are copied and made editable?

**Comment by Stypox** [comment]
Those playlists will be fetched again only every time they are opened. If you want to transform a remote playlist into an editable one, just play it on background/popup and then from the queue press on the save queue button. #2293
