### ISSUE TITLE
East-asian-friendly number format wanted

### ISSUE THREAD

**Issue by chr56** [TeamNewPipe/NewPipe#3871]
When people meet large numbers,such as 1234567890,we separate them into groups.European and North Amerian separate them by 3 digits ,like 1,234,567,890.But East-asian traditionally separates them by 4 digits,like12,3456,7890.
So does the language: In English,dividing it by 3 digits ,first comma from right side stands for"thousand",second stands for "million"...But,some east-asian ,such as Chinese, dividing it by 4 digits,first comma from right side ,in "4-digits-mode",has its own name(not like"ten thousand“ but a unique name)...
However,NewPipe uses first form,and not localizes the numbers for East-asians.
So,there are only "thousand""million"billion" to be translated in resource.

**Comment by AudricV** [comment]
Is it still an issue with 0.26.1?
