### ISSUE TITLE
Feed update after set time doesn't work

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#3873]
### Version

-0.19.5

### Steps to reproduce the bug

1. Open settings
2. Then "Content"
3. Set feed actualization (second setting from bottom) to 1 day
4. After roughly 1 day, update the feed.

### Expected behavior

Feed updates for all channels and resets the timer properly.
### Actual behaviour

The feed updates for 7/8 channels I am subscribed to and sets itself to be late 23 hours (like telling me: "try again in an hour")
### Screenshots/Screen recordings

Right after the 1 day update:
![Screenshot_20200710-210351_NewPipe](https://user-images.githubusercontent.com/26146502/87189775-87d4d280-c2f1-11ea-97ea-302fe792e4de.jpg)

**Comment by Stypox** [comment]
Are you sure more that 24 hours passed? This would be a really strange issue. What happens if you update again?

**Comment by kubo6472** [comment]
The next update makes it 1 hour old. So as expected from the original one, unless it sometimes fail (like the original update) for more than one channel, where it makes it 23 hours old again. Sometimes it makes it 1 day old, so I can update it right away (this last behavior however, I wasn't able to reconstruct reliably).

**Comment by Stypox** [comment]
@mauriciocolli could you look into this?

**Comment by kubo6472** [comment]
Fixed by new versions.
