### ISSUE TITLE
Incorrect display in the launcher

### ISSUE THREAD

**Issue by netz-filter** [TeamNewPipe/NewPipe#3877]
Hello, on amazon Cube 2 the picture from the NewPipe app is not displayed.  

Bug or feature request?

![0097](https://user-images.githubusercontent.com/44233425/87244688-44887a00-c43f-11ea-918c-d1e1aef4aecc.jpg)

Note/Supplement: With my sideload app Kodi, the image is displayed in all Fire OS versions.
On the amazon Fire TV Stick 4K the image of Newpipe also lights up correctly.

**Comment by Stypox** [comment]
Maybe the problem is that the apk you are using is a debug one (not signed), so you could try to download one from release 0.19.5 for now

**Comment by netz-filter** [comment]
The display problem is also present with 0.19.5...

**Comment by opusforlife2** [comment]
@netz-filter Hi. Could you test if this is still a problem with 0.20.0? Make sure you take a backup of your database if you're upgrading from 0.19.8, as you might want to go back.

**Comment by Speciesx** [comment]
Bug is still present in the V0.20.6 release!
![20201210_225542](https://user-images.githubusercontent.com/1196375/101837211-05219f00-3b3f-11eb-9da1-3f5a7fb3874e.jpg)

**Comment by netz-filter** [comment]
@opusforlife2

Yes, the error persists. How does it actually look on the new FireTV surface?

https://stadt-bremerhaven.de/amazon-fire-tv-verteilung-der-neuen-oberflaeche-gestartet/

 Maybe you should wait until the new FireTV interface has been made available for all devices ...

**Comment by Speciesx** [comment]
> How does it actually look on the new FireTV surface?

Also without the logo.
