### ISSUE TITLE
reCAPTCHA error

### ISSUE THREAD

**Issue by Abdel-ilah** [TeamNewPipe/NewPipe#3878]
reCAPTCHA verification error time 01:46 GMT

**Comment by Abdel-ilah** [comment]
![Screenshot_2020-07-13-01-47-48-660_org schabi newpipe](https://user-images.githubusercontent.com/28925960/87262836-ec875d00-c4aa-11ea-9afd-704a537095f3.jpg)

**Comment by Stypox** [comment]
*Please **follow the issue template** when creating an issue, don't just delete everything!* Now I have to ask questions you would have already answered: what is the problem? What are you expecting and what happens instead?

**Comment by Abdel-ilah** [comment]
It's work fine now thank you

**Comment by MD77MD** [comment]
@Abdel-ilah 
don't use 3g only WiFi... newPipe is blocked on 3g.

**Comment by B0pol** [comment]
@MD77MD it's 4G+ and why would newpipe not work on 3G?? It works fine for me, just your experience may be degraded because 3G has less bandwith, therefore it takes more time to load videos
