### ISSUE TITLE
[BUG] Incorrect list of videos

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#388]
First 20 results are displayed twise, they are dubblicated

**Comment by BlenderViking** [comment]
Hi,

I don't have this problem. 

Can you provide some screenshot, device and network capacities ?

Regards,

**Comment by teod0r** [comment]
Unfortunatly I can't provide screenshots because my devise does not provide the ability to take screenshots. I also tryed apps from markets and they didn't work too. I don't know if it is aproblem of ROM or device.

What do you mean by device and network capacities?
I use samsung galaxy tab 4 10.1 with cyanogenmod 11 (android 4.4.4)

**Comment by theScrabi** [comment]
I can confirm that bug, I noticed that to.

**Comment by coffeemakr** [comment]
This bug should be resolved [Version 0.8.6](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.8.6)
