### ISSUE TITLE
PeerTube integration to Youtube RSS feed.

### ISSUE THREAD

**Issue by defini-tiv** [TeamNewPipe/NewPipe#3880]
#### Describe the feature you want

Since PeerTube supports rss and  NewPipe already can play PeerTube videos, shulden't it be possible to add not only Youtube channels, but PeerTube instances to the rss feed too?
So that you have videos from both platforms seamless integrated in the "What's New"-section.

#### Is your feature request related to a problem? Please describe it

I think Youtube's monopoly position is so hard to break because they have all content in one space. It dosn't matter if there are alternatives. As long as people hanging around on Youtube(because not every content is available on alternative plattforms), they will watch videos on Youtube, even if they are available on other platforms, because they are on Youtube anyway.

#### How will you/everyone benefit from this feature?

This feature could make the "What's New"-feed a single place where everything you want/need comes together, but a bit more platform independent.

**Comment by Stypox** [comment]
Peertube channels are already in the what's new feed. If you are talking about considering instances as channels, I am not  sure in which cases this would be useful, but I guess it has its uses for small instances ;-)

**Comment by defini-tiv** [comment]
I think i was talking about channels, im new to peertube...
Okay, now i know how it works ... it isn't actually that hard.
But i was kind of expecting a "add" button for manual adding the link in the subscription section.
Should i change this thread or make a new?

**Comment by B0pol** [comment]
I don't understand either. The “ "add" button „ is subscribe. 

And anyway, I already implemented RSS extractor instead of normal selector, I did some tests and decided not to push it, because it's actually slower:
The channel id to get the RSS feed is not the usual id, it seems like a number counting when you registerd (eg your id is 10 -> you're the 10th account to register on this peertube instance), thus two requests were needed instead of one.

**Comment by defini-tiv** [comment]
I thought of the add button as a way to add directly rss links of channels in the subscriptions section, without having to pull up the corresponding instance with your channel and open the channel in newpipe.

**Comment by Stypox** [comment]
Why would you only have the rss feed of a channel and not its url? If you have the latter you can just open it in newpipe and subscribe to it

**Comment by defini-tiv** [comment]
I meant the url.
For example my note app supports no links. There seems to be no way of sharing the link directly in the browser, so relies on other apps being able to contain and open links.
In fact, even with a note taking app that supports links would it be way more complicated to copy the link to this app just to open it with newpipe after it, than just pasting it directly into newpipe.

**Comment by wb9688** [comment]
@defini-tiv: You could paste the URL in the search field

**Comment by defini-tiv** [comment]
Newpipe wants not to open the link, i get only to choose between Feeder and Firefox.

**Comment by wb9688** [comment]
@defini-tiv: Again, you should paste the link into the search inside the NewPipe app. In v0.19.6 some PeerTube instances have been added to the manifest, so that you could share links for those with NewPipe.
