### ISSUE TITLE
Support to Stream Google Drive Video Files

### ISSUE THREAD

**Issue by DayatXD** [TeamNewPipe/NewPipe#3881]
Hey i would like to add support Play Google Drive Video so i can play my GDrive Video with Floating Player!

**Comment by wb9688** [comment]
No, Google Drive is not a media streaming service.

**Comment by DayatXD** [comment]
Or maybe add feature to Play Network Stream via Link!

**Comment by Stypox** [comment]
Use vlc for that

**Comment by DayatXD** [comment]
Vlc floating player is trash....
