### ISSUE TITLE
Remember search option

### ISSUE THREAD

**Issue by jlpalaciosb** [TeamNewPipe/NewPipe#3883]
Do not reset search options to "All" after the user change it.

#### Describe the feature you want

If the user change search options (e.g.: to "Songs"), do not reset it to "All", the app does this reset when returning to home page or closing the app.

#### Is your feature request related to a problem? Please describe it

No.

#### How will you/everyone benefit from this feature?

The user will not have to set the option he/she uses the most every time.

**Comment by gkeegan** [comment]
I think a setting for "remember search preferences" would be better than automatically keeping it since this is more of a niche feature.

**Comment by B0pol** [comment]
The downvotes were not personal attack, we just feel this feature should not be implemented.

Most people only use All, and if they change it's only one time to search a playlist or a channel or whatever, but only **once**.
Then I'm closing for this reason <img src="https://i.ibb.co/gT6YNqD/Screenshot-20200718-075919-Browser-1.png" alt="niche feature">

**Comment by jlpalaciosb** [comment]
Ok
