### ISSUE TITLE
[Feature Request] Hide Everything Relating To YouTube When Switching To Another Platform, Improved Platform Based Main Page

### ISSUE THREAD

**Issue by grravity** [TeamNewPipe/NewPipe#3886]
Suggesting to hide everything relating to YouTube when swapping to another platform. For example: 

I have my main page set to show What's New, Playlists, Subscriptions, Default Kiosk, History. So when I swap from YouTube to PeerTube, most of those should be empty due to not being signed into PeerTube so you wouldn't have anything under What's New or Subscriptions (unless local). 

A secondary improvement would be to set different Main Pages per platform, so on YouTube I can have it like above, but when I switch to PeerTube it removes Subscriptions and What's New if I wanted.
Also being able to add catagories from the side menu onto the main page would be nice. So like Soundcloud has "Top 50", if I wanted to add that to my Main Page instead of needing to swipe to the side menu I can. 

Also I assume it's a bug or just poorly thought out, but the What's new and Subscriptions pages even on the sidebar show YouTube content when PeerTube is selected.

**Comment by Stypox** [comment]
Let's keep the discussion in #650, I'm copying your comment there

**Comment by grravity** [comment]
> Let's keep the discussion in #650, I'm copying your comment there

Thank you, tried searching before I posted here and didn't find that. Will do though, thank you!
