### ISSUE TITLE
Playback positions aren't synchronized for stream when foreground and/or background and/or popup player are opened at the same time or switched

### ISSUE THREAD

**Issue by vkay94** [TeamNewPipe/NewPipe#3888]
### Version

- NewPipe Version 19.6 (official)

### Steps to reproduce the bug
1. Open any video in details view (tested with YouTube)
2. Press the buttons for background playback and popup player (+ optionally on the video itself to open the main player)
3. Keep the video playing or seek to any position in popup player/main player

### Expected behavior
There are actually two different expections depending on whether the app should allow multiple instances for a single stream or not:

- If the three player types are allowed to be open simultaneously: The current position should be shared/synchronized between all players, so when it is switched (e.g. popup player => main player) the video should resume at the latest position.
- If not allowed: The previous player type should close and the other player should resume at its last position.

### Actual behaviour

The current position is not synchronized, so your current progress is not saved when switching the type.

### Screenshots/Screen recordings
<img src="https://user-images.githubusercontent.com/6626210/87531933-b7d5fa00-c692-11ea-8a43-eaa495f2bbb7.png" height=700px />

**Comment by wb9688** [comment]
Those players are completely separate and this will be solved bu #2907
