### ISSUE TITLE
Notifications for new updates

### ISSUE THREAD

**Issue by champion174** [TeamNewPipe/NewPipe#3896]
Hello team Newpipe, you've been really working hard to make this app better and take my suggestion while doing the next update. Here's my suggestion;  So many newpipe users have subscribed their favourite YouTube channels as like they've subscribed in Official youtube. But the problem here is they need to checkout every singe channel they've subscribed to see the new updates everyday. They don't have free time all the time to find each and every channel they've subscribed, So please enable notifications for new updates from any channel that we've subscribed in newpipe. I hope you people can do it. And I'm waiting for the next update.

**Comment by Redirion** [comment]
see PR #2335 it will hopefully be merged soon™

**Comment by Stypox** [comment]
#1086
