### ISSUE TITLE
Share button on mobile to auto-open Youtube videos in Newpipe

### ISSUE THREAD

**Issue by Lucipo** [TeamNewPipe/NewPipe#3898]
#### Describe the feature you want
Pressing share on a video on the Official Youtube App should have Newpipe pop up, and clicking Newpipe should automatically open the shared video up in NewPipe.
Optionally, also describe alternatives you've considered.
Example: I considered making a playlist to put the music I wanna get on NewPipe, but this would be simpler and easier for everyone.

#### Is your feature request related to a problem? Please describe it
Not really, just the issue that I cant copy the title of a youtube video on the official app from mobile, but thats Youtube's problem.

#### How will you/everyone benefit from this feature?
It will make it a lot easier and quicker to download music, for one instance, and just to open any Youtube video in NewPipe. My biggest reason for this is sometimes the title is in a different language, like Japanese, and I cant type it from youtube into newpipe solely on mobile, I have to use my PC to get the Japanese text into NewPipe.

**Comment by wb9688** [comment]
NewPipe is already in the share menu (though you probably have to unset YouTube as default opener)
