### ISSUE TITLE
player with [unknown] title can get stuck in the notification bar

### ISSUE THREAD

**Issue by 07416** [TeamNewPipe/NewPipe#3903]
### Version

- 0.19.6 on LineageOS 16 (Android 9)

### Steps to reproduce the bug

Occurs erratically, not consistently, on my device.

### Expected behavior

No blank, redundant player notification which always has to be dismissed manually.

### Actual behaviour

An occasional redundant player notification which always has to be dismissed manually. Seems to only be related to video playback, not audio.

### Screenshots/Screen recordings

![Screenshot_20200718-135037_Slide_1](https://user-images.githubusercontent.com/14923168/87851300-253a9280-c900-11ea-812e-e9c1a98b9296.png)

**Comment by opusforlife2** [comment]
Your issue is probably the same as the rest of us. Intents sent by inserting a headphone jack or long pressing on volume buttons will try to start the last used player, which is probably Newpipe in this case. If your music player/video player is the last used media app, that will start instead.

**Comment by 07416** [comment]
For the record, I haven't connected headphones or anything else to the 3,5mm jack in years. Of "long-pressing" the volume buttons I know nothing of - do I frequently trigger something accidentally?

**Comment by opusforlife2** [comment]
Those two are the most common causes for me, personally. There could be others, like Bluetooth connect/disconnect.

**Comment by Stypox** [comment]
#3071
