### ISSUE TITLE
Issues with the white highlight box/marker on FireTV

### ISSUE THREAD

**Issue by k9janer** [TeamNewPipe/NewPipe#3904]
When controlling NewPipe on a FireTV using the remote, selected on screen items have a white line around them.

Unfortunately there are a few situations where the highlight marker is displayed when it shouldn't be or its behaving unexpectedly.

Personally I would differentiate between 1 major annoyances and a few minor glitches/issues, of which 2 are worth reporting:

Major annoyance:

![Topright](https://user-images.githubusercontent.com/26097284/87853093-96317880-c907-11ea-9079-8fd552d380e5.jpg)
1. Enable autoplay
2. Wait for the next video to autoplay

Result: Now there will be a white box on top of the fullscreen video on the top right.

Solution: Press down on the remote to remove this box.

This is a major issue in my opinion as this issue occurs at the start of every autoplay video. In addition, in the long term there is the chance of burnout on OLED screens.

Then there are a few minor issues/glitches, 2 of which are worth reporting:

Minor annoyance 1:

![Middle](https://user-images.githubusercontent.com/26097284/87853105-ab0e0c00-c907-11ea-8342-e3fb2a86c4af.jpg)
1. Open the on screen menu with the "back", "play/pause", "forward" menu items
2. Close this menu 
3. Press the button "<<" or ">>" on the remote

Result: Now an empty white box is displayed on top of the video where the "play/pause" button was.

Solution: Press the back button to remove this box.

Minor annoyance 2:

![whole](https://user-images.githubusercontent.com/26097284/87853108-b103ed00-c907-11ea-9a82-56f9a5e4a87c.jpg)
1. Open a video from the list "next" on the right side of a video.
2. The video will load but the white highlight box will be around the whole lower part of the app.

Result: You can't press the okay button to start the video.

Solution:

1. Press down on the remote.
2. The highlight marker will now jump down to the 3. comment but then automatically shoot up to the first comment again.
3. Press up on the remote to highlight the video.

**Comment by Stypox** [comment]
@Alexander-- could you take a look at this?

**Comment by Alexander--** [comment]
I will look into 1 and 2. Third might be working as intended, unfortunately.
