### ISSUE TITLE
[UX Feedback] Make the video rotation button more accessible 

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#3908]
Right now, the video rotation button's placement is very cumbersome and requires that the users go through this process;

1. User clicks the video
2. Video's thumbnail is loaded in a new screen with play button
3. User clicks on the play button
4. As the video starts playing the user has to click the down arrow button
5. Then click the video rotation button to go full screen

**Note:** The user loses a few seconds of the video while doing this. So they need to rewind the the video to the start. So it's more than just a burden of clicking a few buttons. 

This process can be improved, if the placement of the video rotation button is moved and placed on the side of video playing progress bar like how official YouTube app on Android does (screenshot¹) or somewhere on the video playing screen like the MX player (see the screenshot²) or the down arrow button (please see the screenshot⁵ if you are not sure what I'm talking about) could be expanded by default but it'll make the video playing screen more cluttered so I don't suggest actually doing that.

The importance of letting users easily rotate video without setting Android system auto-rotation toggle enabled can be seen in some of the apps like YouTube, MX player, various video players (see the screenshot ² and screenshot⁴ of MX player and VLC video player respectively)  and even Android itself (see the screenshot³)! Making video rotation very easy and accessible is _really_ important, I think.

### Screenshot¹:

![Screenshot_20200719_080951.jpg](https://user-images.githubusercontent.com/68282543/87866874-6dab8c00-c9a4-11ea-993a-dd52393d6f59.jpg)

### Screenshot²: 
![Screenshot_20200719_091743.jpg](https://user-images.githubusercontent.com/68282543/87866876-78feb780-c9a4-11ea-99eb-f6d3adb5535b.jpg)

### Screenshot³:

![Screenshot_20200719_091937.jpg](https://user-images.githubusercontent.com/68282543/87866895-b06d6400-c9a4-11ea-9666-40bcc90f443a.jpg)

### Screenshot⁴:

![Screenshot_20200719_100533.jpg](https://user-images.githubusercontent.com/68282543/87867139-997c4100-c9a7-11ea-9046-458a58eee195.jpg)

### Screenshot⁵:

![Screenshot_20200719_093449.jpg](https://user-images.githubusercontent.com/68282543/87866887-96338600-c9a4-11ea-8027-40e6fa802738.jpg)

I'm not sure if this feature is in consideration, I made sure I searched the repository but it returned nothing matching, that's why I'm filing this issue.

Thanks! :)

**Edit:** Since filing this issue, I have noticed that the videos by default don't auto-rotate and play vertically but if once the rotation button is clicked to make the video full-screen then all videos always play in full-screen (horizontally). I think this shouldn't be the default behaviour as users may click the rotation button to make just one video play vertically that they're watching. And instead a seperate preference could be provided to enable the always open the videos vertically or horizontally. And make the video play by default vertically if they're shot vertically or horizontally if shot horizontally and a more accessible button to provide the flexibility of rotating the video however the user wants.

**Comment by Stypox** [comment]
#2907 will probably fix the problem you are facing by enhancing the way autorotate works

**Comment by SameenAhnaf** [comment]
@Stypox Shouldn't this be closed in favor of #3908?

**Comment by Stypox** [comment]
@SameenAhnaf this *is* #3908 ;-)

**Comment by SameenAhnaf** [comment]
@Stypox I meant #4500. Sorry. 😶

**Comment by Stypox** [comment]
Ok, thank you ;-)
