### ISSUE TITLE
downloads missing

### ISSUE THREAD

**Issue by tutulesnija** [TeamNewPipe/NewPipe#391]
there is an issue that i have.After downloading videos or audio i can see them in the downloads folder.If i exit the application and re-enter the downloaded audio/video are gone.Tested on two smartphones.I tried re installing several times and issue persists

**Comment by theScrabi** [comment]
Yes I noticed that to.

**Comment by tutulesnija** [comment]
any fix soon?

**Comment by theScrabi** [comment]
Not at the moment sorry.
