### ISSUE TITLE
Captions Contain HTML

### ISSUE THREAD

**Issue by evanspy1** [TeamNewPipe/NewPipe#3911]
### Version

- 0.19.5

### Steps to reproduce the bug

1. Go to a Video where the creator inserted custom captions that contain Bold, Italics, etc.
2. Turn on captions

### Expected and actual behavior

When the captions display, they show up as `<b>` and `<i>` for bold and italics respectively, instead of correctly formatting the text so it is bolded or italiciesed.  The auto-generated captions don't do this, but when the creator sets captions, they are able to bold and italicise.

### Screenshots/Screen recordings

This isn't really neccesary, just imagine the caption box displaying `this is a <b>test</b>`, with bold and italicised captions displaying in raw HTML instead of being parsed.

### Logs

N/A

**Comment by TobiGr** [comment]
Can you please give us a video with these captions?

**Comment by opusforlife2** [comment]
Closing until @evanspy1 provides such a video.
