### ISSUE TITLE
Broken preview thumbnails

### ISSUE THREAD

**Issue by opal06** [TeamNewPipe/NewPipe#3912]
Starting a few days ago, the thumbnails in the preview are strangely broken. Although still showing, they have a lot of noise. It is not related to an update of NewPipe, as it worked fine previously also on version 19.5 (F-Droid). 

Screenshot: 

![](https://i.imgur.com/zcLIYdw.jpg)

Expected behaviour:
Normal preview thumbnail

Experienced behaviour:
Noisy preview thumbnail, Thumbnails in list view are fine. Streams play as expected.

Used Version: NewPipe 19.5 (F-Droid)

**Comment by opal06** [comment]
Probably related to some strange ROM behaviour, closer

**Comment by Stypox** [comment]
You could try to clear the cache of thumbnails or disable/reenable thumbnails
