### ISSUE TITLE
Downloads tab should open the same way as the others

### ISSUE THREAD

**Issue by TacoTheDank** [TeamNewPipe/NewPipe#3914]
## Describe the feature you want
Not a feature, per se, but...

The "Downloads" tab seems to open by sliding upwards from a point, while the others simply fade/change in the background.

This can easily be seen by simply switching between the tabs and seeing how the Downloads tab differs when opening.

I think it should be changed to match the other tabs.

#### How will you/everyone benefit from this feature?
I think it'll make the UI more consistent.

**Comment by wb9688** [comment]
It's because e.g. Downloads, Settings, and About are activities instead of fragments. It's probably possible to change the animation, but imho it's better to just make them fragments as well.

**Comment by Stypox** [comment]
#3477
