### ISSUE TITLE
Add a Progress bar

### ISSUE THREAD

**Issue by Pranab009** [TeamNewPipe/NewPipe#3916]
Add a Progress bar (for Downloads ) & Pause / Start buttons in notification panel.

**Comment by Stypox** [comment]
*Please **follow the issue template** when creating an issue, don't just delete everything!* Now I have to ask questions you would have already answered: "Better describe the feature you want", "Is your feature request related to a problem? Please describe it" "How will you/everyone benefit from this feature?", "Additional context"

**Comment by Pranab009** [comment]
Hello sir,
Every time, it is not possible that open the app and see how much download remain..
& Video downloading or not.
 
It is very easier way to see your download progress in nonfiction panel.
Almost every time we see the notification panel.

**Comment by opusforlife2** [comment]
#3332.
