### ISSUE TITLE
change trending to Non US 

### ISSUE THREAD

**Issue by goldalworming** [TeamNewPipe/NewPipe#3917]
Hi, do you already have any way to change trending to another country trending.
It's very helpful to have choice to see another country trending so it make apps more interesting.

**Comment by Stypox** [comment]
Unfortunately this is not possible for now, as it is not possible to correctly parse the website in the many available languages

**Comment by wb9688** [comment]
@Stypox: You're wrong: language can't be changed, but country, which is what this issue is about, can be changed.

**Comment by Stypox** [comment]
Oh, then what are these issues about, if everything already works?

**Comment by wb9688** [comment]
@Stypox: I have no idea, but it actually works and you could even choose another in Settings -> Content -> Default content country
