### ISSUE TITLE
[Android TV emulator] Fast Forward key on remote not working in MainPlayer

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#3922]
While testing #3920 I encountered a problem with the emulator's dpad. More specifically the fast forward key.
I played a video in the MainVideoPlayer and pressed the fast forward button - nothing happened. Pressing the rewind button worked. @Alexander-- Do both buttons work for you on a real device? It turned out that the emulator returned  `KEYCODE_UNKOWN` when pressing the fast forward key, but `KEYCODE_MEDIA_REWIND` when pressing the rewind button. I guess this is a bug in the emulator... 

While debugging I found that piece of code:

https://github.com/TeamNewPipe/NewPipe/blob/176d57b35af464d632ffaf7934973996a3ecf676/app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java#L220-L225

It looks like I didn't do a good job while reviewing previous PRs. @Alexander-- Do you know why you added `default: break;` to skip the switch?

**Comment by Alexander--** [comment]
@TobiGr 

`default: break;` means, that keys, not listed in switch, will not be handled by switch. The `default` case can be at any position in switch, not necessarily at the end (it will always have the same effect either way).

I want `onKeyDown` to trigger default responses for all keys other than specified keys (e.g. super.onKeyDown). By using a `default` case at beginning of switch I am making that more explicit, I guess.

**Comment by TobiGr** [comment]
Oh yes. Nevertheless, we should put it at the end for better readability / keep the coding style.

Were you able to test the fast forward button?

**Comment by allendema** [comment]
Both forward and rewind keys are functioning on my device.

**Comment by TobiGr** [comment]
@allendema Good. Thank you for confirming!
