### ISSUE TITLE
[FR] Add Full Range colorspace support

### ISSUE THREAD

**Issue by Kein** [TeamNewPipe/NewPipe#3924]
#### Describe the feature you want
By default NP play all videos (when format is MPEG-4 that has HW acceleration) in limited -- also called TV -- range. You can check it by playing the same video in Chromium or Firefox with avc1 forced (`h264ify`) and look at dark scenes/black-filed frames.

#### Additional context
Full-range is 0-255, limited range is 16-235 where black color look "washed out". LR is a default setup for any avc1/h264 accelerated video because "muh TV" legacy so we have to suffer forever now.
There should be a way to let decoder/playback device know what we want.

#### How will you/everyone benefit from this feature?
Everyone can benefit by having proper blacks with MPEG-4 and proper acceleration unlike with WEBM.

**Comment by eladkarako** [comment]
some screenshots would be useful.

**Comment by Kein** [comment]
I want to add them when opened the issue but sadly I'm unable to make any proper screenshots (proper screenshots on a phone is suffering in general).
Take this trailer for example:
https://www.youtube.com/watch?v=jZENtOGdMkc
at 00:50 there is a mostly black (with noise) backdrop with some animated text. If you compare how it looks in Chrome (either vp8/9 or avc1) and in NewPipe you will notice the latter is noticeable "brighter" - that is range cutting.

This also might depend on device, though, my case is Redmi Note 7/MIUI 10/Android 9. Either way, even if that is the case - a custom option to use full-range that can be passed to video renderer would be real nice and it should not require much work.

**Comment by Stypox** [comment]
@Redirion do you know something about this?

**Comment by Redirion** [comment]
@Stypox I didn't but I just checked.

Each Track has a Format which holds the ColorInfo: https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/video/ColorInfo.java

from a quick glance by grepping "colorInfo" in the current ExoPlayer, it appears to be only used for the media extensions vp9 and ac1 (only place where the colorInfo is actually set to the outputBuffer). So support is similar to what @Kein showed with the Chrome example.

So at the moment ExoPlayer (and therefore NewPipe) don't support different colorspaces in MPEG-4.

**Comment by Kein** [comment]
> don't support different colorspaces in MPEG-4. 

I'm a bit confused, from what I've assumed NewPipe downloads [MPEG-4 part 10](https://en.wikipedia.org/wiki/Advanced_Video_Coding) avc1 encoded videos from YT CDN (from what I know, only VP8, 9 and avc1 available publicly, the rest internal), which as you said should support [colorRange](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/video/ColorInfo.java#L43)

>  it appears to be only used for the media extensions vp9 and ac1

am I missing something?

**Comment by Redirion** [comment]
Sorry, I meant vp9 and av1. These are succesors of H264/AVC1 and only supported as extensions of ExoPlayer. See here: https://github.com/google/ExoPlayer/tree/release-v2/extensions

These are not used in NewPipe

**Comment by Stypox** [comment]
@Redirion could those extensions be integrated into NewPipe without creating problems?

**Comment by Redirion** [comment]
it complicates building of NewPipe as these extension will have to be referenced as local projects in gradle.

**Comment by wb9688** [comment]
@Redirion: Nope, the extensions are also just published on Maven

**Comment by Redirion** [comment]
@wb9688 for the MediaSession extension that NewPipes uses, this is correct.
https://github.com/google/ExoPlayer/tree/release-v2/extensions/mediasession
`The easiest way to use the extension is to add it as a gradle dependency`

for other extensions like av1 and vp9 it is more complicated.
https://github.com/google/ExoPlayer/tree/release-v2/extensions/av1
https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9

`To use this extension you need to clone the ExoPlayer repository and depend on its modules locally. `

**Comment by wb9688** [comment]
@Redirion: Ah, I didn't see that, though those use JNI, which we previously already decided against.

**Comment by Redirion** [comment]
from my point of view this is more a issue for ExoPlayer. The extractor of ExoPlayer does only parse the fps from the metadata of mp4. If more metadata would be parsed the media framework of the device could handle the full color space if supported.

**Comment by Stypox** [comment]
Then I guess this should be closed, as it is unfortunately not fixable until further changes on exoplayer's side. Thank you @Kein and @Redirion for the effort :-)

**Comment by Kein** [comment]
I wanted to say _"Keep issue open to track possibility to address it in the future?"_ but then I've noticed Issues count and yeah...

On the bright side, though, it is indicator how popular and needed the app is, so that's good.

**Comment by Stypox** [comment]
@Kein yeah, leaving it open even though this is not fixable in the near future is not that different from closing it, as it would be forgotten. If ExoPlayer will support this, we will be able to add it without much work, too, but until then... 😅
