### ISSUE TITLE
Black player screen on Formuler Z8 Android box

### ISSUE THREAD

**Issue by brunoli49** [TeamNewPipe/NewPipe#3927]
Hi,

I only have sound when playing video NP on the formuler Z8. No video...

YT and other video's app are ok..     Any idea ?

**Comment by TobiGr** [comment]
I guess, when starting to play a video, you only see a black screen. Is that correct?

Is it running AOSP or a different kind of Android OS? [Their website](https://www.formuler.tv/z8#comp-jqxn7puxinlineContent) says, they are using Android 7, but not which Android base. I know there are problems with some AOSP TV devices.

**Comment by brunoli49** [comment]
Hello,
Yes, black screen ...
In settings, I see : Android V7.0.  Correct 11/01/19  Build NRD90M. Kernel 3.18.24....

**Comment by AnyoeDove** [comment]
try switch video format to MPEG-4

**Comment by brunoli49** [comment]
Hi,
Tried MPEG-4 but the same.
I found this : 
The video seems to be played in background (behind the black UI). When I push on 'exit', I need to push 2x and I see the video for some milliseconds...

**Comment by davidebeatrici** [comment]
I'm encountering the same issue on a TV running Android 7.0, Linux 3.18.25.

https://github.com/ram-on/SkyTube and other players work fine.

The board is identified as `CVT_MT5886_EU_1G`. It's powered by a MediaTek MT5886, a Mali-450MP and 1 GB of RAM.

**Comment by opusforlife2** [comment]
How's the situation on 0.20.0?

**Comment by brunoli49** [comment]
> 
> 
> How's the situation on 0.20.0?

still the same on 0.20.2

**Comment by Redirion** [comment]
@brunoli49 @davidebeatrici 

please try the app-debug.apk: https://github.com/Redirion/NewPipe/releases/tag/tunneldisabled

please run logcat and look for ExoPlayerLib

I need the line containing something like this: [ExoPlayerLib/2.12.3] [Hi3798MV200, Formuler CC, FORMULER, 24]

We can then implement a workaround that will fix the issues for you.

**Comment by youkd** [comment]
@Redirion Hi. I captured log.

03-31 11:26:47.420 14972 14972 I ExoPlayerImpl: Init 371cba3 [ExoPlayerLib/2.12.3] [Hi3798MV200, Formuler CC, FORMULER, 24]
03-31 11:26:48.031 14972 14972 I ExoPlayerImpl: Release 371cba3 [ExoPlayerLib/2.12.3] [Hi3798MV200, Formuler CC, FORMULER, 24] [goog.exo.core, goog.exo.mediasession]
03-31 11:26:48.039 14972 14972 I ExoPlayerImpl: Init 6253ff8 [ExoPlayerLib/2.12.3] [Hi3798MV200, Formuler CC, FORMULER, 24]

**Comment by Redirion** [comment]
@youkd thank you. Which device is that?
from this news here: https://www.formuler.tv/single-post/march-2021-formuler-software-update
I would assume that all those Formuler devices use the same SOC (Hi3798MV200).

So the workaround for the Hi3798MV200 will enable NewPipe on Formuler Z8 Pro, Z8, CC, Z Alpha, Z+ Neo

**Comment by youkd** [comment]
@Redirion It's CC device. Please officially release the applied one.  Thanks.

**Comment by brunoli49** [comment]
Nice ! Hope we'll receive solution..
