### ISSUE TITLE
Make channel playlists available on channel profile

### ISSUE THREAD

**Issue by github-throwaway** [TeamNewPipe/NewPipe#3929]
#### Describe the feature you want
I think it would be nice if you add the feature *channel playlist* which makes it possible to view playlists created by the channel. This would be added to the profile / channel page.

#### Is your feature request related to a problem? Please describe it
Right now you have to search for the name of the playlist and there is no way to discover playlists by looking at the channel.

#### How will you/everyone benefit from this feature?
This is especially useful for home workouts which are often bundled in playlists. But this obviously also useful for any series split into several parts or content which is presented in a context.

**Comment by eladkarako** [comment]
duplicate (there are several, https://github.com/TeamNewPipe/NewPipe/issues/3649 )

**Comment by Stypox** [comment]
#2414
