### ISSUE TITLE
Download the media while playing it

### ISSUE THREAD

**Issue by ssibb** [TeamNewPipe/NewPipe#3932]
#### Download the media while playing it

It would be really useful being able to watch/listen in the background the media while downloading (or, if you prefer, downloading it while you are watching/streaming in the background), so when you are looking for something specific you won't waste bandwidth downloading the wrong media or streaming and then having to download it again.

Of course, this option will need to have just one active downloading thread.

Thank you for this great project!

### Prerequisite : #478

**Comment by Stypox** [comment]
Will be fixed by #2907 (closing the issue now because that PR will be merged really soon)

**Comment by Stypox** [comment]
I think I misunderstood. If you are talking about watching the video file while it is being downloaded, then I'd refer for now to #478 which is about the ability to play downloaded video files. Since your issue is also about playing the file while it is being downloaded, I added that to the aforementioned issue. Thank you and sorry for the misunderstanding ;-)

**Comment by opusforlife2** [comment]
@Stypox Isn't this something like what browsers do with PDFs? You can view them as they load, and once they load fully in the browser, you can click on the download button, which seems to just move the PDF from the browser's temp directory to your downloads directory.

**Comment by litetex** [comment]
Is this still a thing?
#478 got closed - see https://github.com/TeamNewPipe/NewPipe/issues/478#issuecomment-960959193

**Comment by opusforlife2** [comment]
> Prerequisite : #478

They clearly mean to have this built on top of in-app playback, so this has to be closed anyway. Any new proposal can come as a new issue in the repo.
