### ISSUE TITLE
Audio only button from pop out

### ISSUE THREAD

**Issue by Stallonious** [TeamNewPipe/NewPipe#3933]
I would like to see an audio only headphone button on the pop out player so that we can easily switch between pop out player to audio only instead of having to go from pop out player to main screen then to audio only. 
All those buttons on the task bar widget would be nice too. Thanks!

**Comment by Stypox** [comment]
This can already be done: click on the notification for the popup and then in the three-dot menu press on "Switch to Popup". If you are asking about a button directly ON the player, then unfortunately this is not possible, as there not enough space for new buttons.
