### ISSUE TITLE
Audio unsynchronised

### ISSUE THREAD

**Issue by HappyClem** [TeamNewPipe/NewPipe#3935]
### Version

-0.19.5

### Steps to reproduce the bug

1. Open newpipe
2. Launch a video (any quality, any speed)
3.Look closely and after sometimes (2-5 minutes) you should see that the audio is slightly behind the video

### Expected behavior

Audio and video synchronised throughout the video

### Actual behaviour

After some times the audio lag behind the video. Closing and opening the video fix the problem but it start again after some time (in the same video)
### Logs

Xiaomi Mi 9T - Android 9

**Comment by wb9688** [comment]
Update to v0.19.6
