### ISSUE TITLE
Alternative Newpipe Release: Sharepipe: Just for using powerful features

### ISSUE THREAD

**Issue by bncbg** [TeamNewPipe/NewPipe#3939]
#### Describe the feature you want

A lite modded Newpipe for just downloading, background and popup playing. No any main page, trending, subscriptions, what's new, search...etc. I called it "Sharepipe" Name can alterable of course.

#### Additional context

The new lite app "Sharepipe" should work only with share option. Scenario is simple: 

- Open Youtube, use and watch as usual. 
- If you want special features, just share to Sharepipe. It shows popup window: Video player, Popup player, Background player, Download.

#### How will you/everyone benefit from this feature?

WHY?

Because I have a kid. You know parental controls could be very important. He uses official YouTube with restricted mode. If I install Newpipe he *may* change the some settings. Also I control his watch/search history with the account. If he use Newpipe I cannot track, he can delete history easily...

Just for kids? No... I think, it will help some people who try Newpipe but do not like its interface. You know, some people like to login or they got to used the official interface. But Newpipe does not have this features. This new modded version would be a great idea to use powerful features as an extension.

**Comment by gkeegan** [comment]
This seems like it would be far too niche of an app, but the NewPipe extractor would make it possible for someone to create it if they wanted to.

**Comment by wb9688** [comment]
I agree with @gkeegan. I think we should add better parental controls to NewPipe though.

**Comment by opusforlife2** [comment]
> The new lite app "Sharepipe" should work only with share option. 

Use a launcher which can hide apps. Then just hide Newpipe, and use it through sharing. Simple.

**Comment by Domiuns** [comment]
Controll kids when use phone :)
Use this app forma set pin on newpipe https://play.google.com/store/apps/details?id=com.symantec.applock
Or set app lock from system setting (search on google) android have some parent controll setting as television. Not need app feature.

**Comment by bncbg** [comment]
Thanks for replying. We use Google's Family Link app. It's very powerful. However the topic is not just about parental control.

I had recommended Newpipe to my friends. Some of them didn't love it. It sounds very strange but we can't judge. This is just an user habit. The main issue that I see, Newpipe seems completely new platform. They think "if I use these unique features I should stay in Newpipe's system". Of course I had told that they could use with sharing option, but they couldn't catch.

If we can create new alternative concept, more people can adopt. Let's give an example, if you want to search some torrents, should you stick with the built-in web browser of bittorrent client?

Ok, I hope everyone can understand what I want to say and I hope someone will try to create it. (Btw, I really wish I knew how it would change the codes)

**Comment by avently** [comment]
I just found today the app that is must have for you. Take a look: https://github.com/sadr0b0t/yashlang
It uses newpipeextractor too and realty cool

**Comment by opusforlife2** [comment]
And it's already on F-Droid: https://f-droid.org/en/packages/su.sadrobot.yashlang/

**Comment by mafjmafj** [comment]
I really would want parental option: no search no browsing no subscription.
The usecase: home schooling. 

We get videos from teachers the kids need to play. The videos will not play with YouTube kids. And YouTube kids is no solution - it is not about content it is about time sink hole. 

Now it is so easy for kids to get distracted and get sucked into endless spiral of videos YouTube kids or YouTube or new pipe regardless. We do not want this during school hours.

Separate build of the app just for playing  links would be easy to integrate with family link. As you could have separate schedule for new pipe and share pipe.

**Comment by mhmdanas** [comment]
Since the team has no plans to do something like this, I'll be closing this issue. As suggested above, you can try out Yashlang.
