### ISSUE TITLE
Design proposals

### ISSUE THREAD

**Issue by realpixelcode** [TeamNewPipe/NewPipe#3941]
First of all: NewPipe is so great! I really like it so my criticism is "Grumbling at a high level" as we say in Germany. NewPipe looks good. But I want it to look _**best**_. So I've decided to make the following design proposals. Unfortunately, I have no clue how to design an Android app so I can only contribute some example images.

# **1) Better context menu** 
In my opinion, it takes the user too long to understand what all the options mean. The context menu lacks good distinguishability of the individual items. So this is my proposal: add icons, group the items and put the share option as an icon to the top. Also, the video title needs to be really emphazised because it just gets kinda lost. By the way: those are Bootstrap icons. I created the last 2 ones myself from existing ones.  And maybe make the edges more rounded.

![NewPipe new context menu](https://user-images.githubusercontent.com/52963327/88476588-fdaf7f80-cf28-11ea-96db-bdc164937398.png)

# **2) Swipe to delete home tab**
You can delete a home tab by dragging/sliding it in the settings to the right out of the window. There should be a red indicator.

![NewPipe swipe to delete](https://user-images.githubusercontent.com/52963327/88468764-de3c3680-ced7-11ea-92a3-2fa93138fb3b.png)

# **3) PeerTube instances**
In the left menu you can select PeerTube as the video source. But if you have several PeerTube instances NewPipe gives you this little really annoying dropdown menu which I'd like to have replaced by a grouped/seperated list.

![NewPipe PeerTube](https://user-images.githubusercontent.com/52963327/88468846-bbf6e880-ced8-11ea-9ee5-4635bc47c08a.png)

# **4) Pull to refresh**
Please add the option to pull-refresh the feed tab. Searching and unsuccessfully tapping the little, little reload button is sooo annoying.

![NewPipe pull to refresh](https://user-images.githubusercontent.com/52963327/88468880-2f005f00-ced9-11ea-8d16-a09bf1d240d6.png)

Thanks for your work! Love it

**Comment by test2a** [comment]
This kinda does look significantly better. What about bringing thus ux to other pages on the app too?

**Comment by opusforlife2** [comment]
I like 1, but the general push is towards having this: https://github.com/TeamNewPipe/NewPipe/pull/3936.
Agree with 2 and 4.

**Comment by realpixelcode** [comment]
> I like 1, but the general push is towards having this: #3936.

Hm, something like [this](https://github.com/TeamNewPipe/NewPipe/issues/2583#issuecomment-564769979) is not bad but I think buttons should generally always be labeled. One should not rely on the presumption that really everyone understands them. Well, e.g. the home icon can't be misinterpreted, but not everyone can necessarily understand something like the playlist icon.

**Comment by snappyapple632** [comment]
4 has been mentioned in the past, and I completely agree with it. I just forgot why they didn't do anything about it.

**Comment by Stypox** [comment]
Thank you for the ideas! Please do not create a single issue with multiple contents next time.
1. Submit the solution in #2583 
4. #3329

Please open separate issues for 2. and 3.
