### ISSUE TITLE
Next/prev or fast forward/backward randomness

### ISSUE THREAD

**Issue by gigiboeru** [TeamNewPipe/NewPipe#3942]
Hi,

This seems to be a bug, but usually when I open a video from the playlist or history I get the fast forward / backward buttons, but when I search for something I get the previous/next buttons. Is this intended? I've attached 2 screenshots as I'm not confident about reproducing the bug (although I've tested this on 2 different phones).

Best, 
G

![PSX_20200726_041647](https://user-images.githubusercontent.com/30387275/88470751-603c5780-cef8-11ea-9ce6-f79b5adf056a.jpg)
![PSX_20200726_041716](https://user-images.githubusercontent.com/30387275/88470752-60d4ee00-cef8-11ea-8709-3c80f0d14c39.jpg)

**Comment by Stypox** [comment]
Yeah, this is intended. When there is only one stream in the queue the fast forward/backward buttons are there, otherwise the next/previous ones appear.
