### ISSUE TITLE
Search limited to only twenty videos

### ISSUE THREAD

**Issue by Kukulkan2019** [TeamNewPipe/NewPipe#3945]
### Version 0.19.5

-

### Expected behavior

To have more than twenty videos or only one page per search 
### Actual behaviour

Only one page per search, search won't move off page

**Comment by wb9688** [comment]
Duplicate of #3921

**Comment by Kukulkan2019** [comment]
Why are you closing this, the problem still persists...

**Comment by Kukulkan2019** [comment]
Why are you closing this, problem still persists...



Brennan Mulrennan end message...♞
