### ISSUE TITLE
Won't load videos with pop-up warnings

### ISSUE THREAD

**Issue by scheng80** [TeamNewPipe/NewPipe#3946]
Can't handle videos that have a pop-up warning about the content that you have to acknowledge first before video loads. 

Example of this is "the untamed episode 50" video at:

 https://www.youtube.com/watch?v=yyBkKooh9Qk

(This is the warning you get -- it is flagged because the video hints at LGBT between the main characters, which is considered offensive in China. There is no nudity or swearing.

![image](https://user-images.githubusercontent.com/37228105/88577537-045af700-cffc-11ea-94ff-1e93230379eb.png)

**Comment by opusforlife2** [comment]
Why link a Google search result and not the actual video? It will probably show different results for you and someone else. Please share the link from the Youtube dot com video page.

**Comment by scheng80** [comment]
> Why link a Google search result and not the actual video? It will probably show different results for you and someone else. Please share the link from the Youtube dot com video page.

Sorry, fixed.

**Comment by opusforlife2** [comment]
Ah. Sorry. Someone else will have to find a way to test it. This video isn't available in my country.

**Comment by Stypox** [comment]
*Please **follow the issue template** when creating an issue, don't just delete everything!* Now I have to ask questions you would have already answered. Could you explain exactly what happens and eventually provide a bug report?

**Comment by opusforlife2** [comment]
Closing until @scheng80 replies.
