### ISSUE TITLE
Hungarian translation completed

### ISSUE THREAD

**Issue by kelna** [TeamNewPipe/NewPipe#395]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

I completed the HU translation:
https://gist.github.com/68da4b38bb54e639c2a04dfbd8c38202

**Comment by theScrabi** [comment]
All right would you want to do a pull request?

**Comment by kelna** [comment]
I've never done a pull request and I don't know how to. Could you include the file without a PR?

**Comment by Poussinou** [comment]
Hi @kelna have a look here here, very good tutorial on how to do a PR https://www.youtube.com/watch?v=YTbRzhQju4c
I assume you used Stringlate to translate the app?;)

**Comment by theScrabi** [comment]
Also it seems to me like the [hungarian translation in the repository](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/res/values-hu/strings.xml) is a bit more elaborate, can that be?

**Comment by mauriciocolli** [comment]
If someone wants to translate, use [weblate](https://hosted.weblate.org/projects/newpipe/strings/).
