### ISSUE TITLE
recapcha challenge requested

### ISSUE THREAD

**Issue by abelfn** [TeamNewPipe/NewPipe#3964]
### Version 

-0.19.7

### Steps to reproduce the bug

1.Go to any videos from search or trending
2.Press on the video to play

### Expected behavior 

open the player activity and play the video

### Actual behaviour 

recapcha challenge requested 

only white background shows no capcha

### Screenshots/Screen recordings

![recapcha](https://user-images.githubusercontent.com/63355586/88614151-cd3a2380-d097-11ea-8cd1-9d4d6efe82a9.jpg)

**Comment by Stypox** [comment]
#3714
