### ISSUE TITLE
Media player enhancements

### ISSUE THREAD

**Issue by demonff1** [TeamNewPipe/NewPipe#3969]
Hey guys, love what ur doing. Infact I can't shut my mouth of requesting some features. These are some of the tweaks I would like to see.

#I loved the interface and ur external player. Could u make the app media player to play videos saved locally in the phone. The UI is great and it's a shame we users can't use it as a video player.
#And the second thing I want is custom subtitles. We can upload locally saved srt files to be used as cc. 
It would be a neat feature I think. If u can't make the video player possible atleast make it possible for vids downloaded through newpipe.

**Comment by Stypox** [comment]
*Please **follow the issue template** when creating an issue, don't just delete everything!* You posted two things inside one issue, which makes everything more difficult to track. And you didn't explain why those features would be useful.
1. #1052 and #478 
2. #2902
