### ISSUE TITLE
Weblate keeps suspending

### ISSUE THREAD

**Issue by AioiLight** [TeamNewPipe/NewPipe#3986]
![image](https://user-images.githubusercontent.com/13918537/88652110-59cefb00-d105-11ea-9718-af1876a5367b.png)

When will we resume? Is there a clear reason?

**Comment by TobiGr** [comment]
Oh. I contacted them via contact form on Friday. Seems like I need to write someone an email to get a faster response.

**Comment by AioiLight** [comment]
I see this problem is depending on Weblate. Thank you!

**Comment by TobiGr** [comment]
Michal responded quickly.

**Comment by yarons** [comment]
Happens again.

**Comment by TobiGr** [comment]
Not sure, why that was locked. Fixed

**Comment by yarons** [comment]
Thanks!
