### ISSUE TITLE
YouTube errors

### ISSUE THREAD

**Issue by BaphometTechnology** [TeamNewPipe/NewPipe#3990]
No matter what video or whether I choose play, pop-up, or background the videos do not play. This is with the most recent version of the app.

**Comment by strongwinderic** [comment]
"Could not play this stream" is the error message.

**Comment by soladev** [comment]
Duplicate of #3951. The isse has been fixed and the release is coming **SOON**

**Comment by wb9688** [comment]
Use v0.19.8
