### ISSUE TITLE
Apparently not able to install the latest NewPipe version(s) on Android 6.0.1 device

### ISSUE THREAD

**Issue by CEHitchens** [TeamNewPipe/NewPipe#3993]
### Version
Currently F-Droid's 0.19.5 version - manual *.apk downloads of 0.19.8, 019.7 would not install.

### Steps to reproduce the bug
1. Downloaded the last two NewPipe releases from here
2. Opened file manager on the Android 6.0.1 device
3. Tapped the according apk file
4. "Do you want to install?",  Yes
5. Device was busy for a few moments, then let me know that the app was not installed.
6. First removing the app using F-Droid and then installing the apk directly showed the same result > not installed.

### Expected behavior
App to be installed

### Actual behaviour
Still on the F-Droid's version 0.19.5

### Logs
Would I use logcat or something like that for this?

**Comment by wb9688** [comment]
You can't upgrade from a F-Droid to a non-F-Droid APK. You'll need to uninstall it first (and if you want to retain your subscriptions, playlists, etc, Settings -> Content -> Export database).

**Comment by CEHitchens** [comment]
@wb9688 that's what I tried as well. uninstalled NewPipe through F-Droid > no luck. funnily enough installing by using Android's launcher now led to success. Thanks for the quick response.
