### ISSUE TITLE
A thank you note

### ISSUE THREAD

**Issue by electronoob** [TeamNewPipe/NewPipe#3994]
I felt a strong need to say thank you for the fast update to Newpipe. I'm glad it's resolved but also have experienced rolling out software for free to the public who expect instant fixes when the breaking changes came from an external source yet now became my problem. Thankfully those days are over for me but I vividly recall the frustration and stress it caused me. So while most of your users have zero understanding of the problem, situation, or your dedication, there are some of us who do understand and are very grateful indeed.

 Thank you for making my life that little bit easier.

**Comment by malespiaut** [comment]
Hello,

I'm commenting on this issue to avoid creating a duplicate.
I would like to say thank you as well for the developpers of NewPipe.

NewPipe is one of the few applications that I use, and that I use daily. It's well designed, and does the job well. Especially the ability to subscribe to any channels without YouTube accounts, and avoid displaying comments under videos to minimize distractions (watching videos is taking time away enough by itself).

Thank you for your time and effort in developping this great piece of open-source software.

Best regards!
