### ISSUE TITLE
Automatically download Google Encryption Certificates

### ISSUE THREAD

**Issue by chenzhendong** [TeamNewPipe/NewPipe#3996]
Is it possible Newpipe could check and download the latest encyption certificates published on some fix url.  So team don't need a code fix and hash release for the similar issues in the future?

**Comment by FireMasterK** [comment]
That's not how it works unfortunately, it's a lot more complicated than a SSL certificate.

**Comment by Stypox** [comment]
There is already some work being done to achieve this. Please refer to TeamNewPipe/NewPipeExtractor#255. The fixing pr is TeamNewPipe/NewPipeExtractor#297.
