### ISSUE TITLE
Can't install NewPipe.

### ISSUE THREAD

**Issue by C077eeGuy** [TeamNewPipe/NewPipe#3997]
### Version 0.19.5 with Android 6.0.1

- Thank you for solving the [latest issue](https://github.com/TeamNewPipe/NewPipe/issues/3951) but I still have the problem because I can't install the newest version of NewPipe
- Yes I know I should use the latest version but wasn't able to install the versions after mine and the app worked quite well. But since the latest bug my version didn't work too.

### Steps to reproduce the bug
1. I downloaded the latest version (and the ones before).
2. I tried to install the apk the usual way (yes installing from unknown sources is still enabled).
3. A notification appeares that says the app hasn't been installed

### Expected behavior
The NewPipe should have been installed

### Actual behaviour
See above

![NewPipe](https://user-images.githubusercontent.com/68919626/88710922-a0c5ec00-d117-11ea-971c-0e7d78ee4a48.jpg)

Thanks for any help!

**Comment by wb9688** [comment]
You can't upgrade from a F-Droid to a non-F-Droid APK. You'll need to uninstall it first (and if you want to retain your subscriptions, playlists, etc, Settings -> Content -> Export database).

**Comment by C077eeGuy** [comment]
I finally installed NewPipe again and got rid of the bug mentioned above. Except for the reCAPTCHA issue NewPipe works fine.

Thank you!
