### ISSUE TITLE
Newpipe support for 19:9 screen aspect ratio and higher

### ISSUE THREAD

**Issue by elsaversailles** [TeamNewPipe/NewPipe#3999]
![Screenshot_2020-07-29-09-08-28-38](https://user-images.githubusercontent.com/50725388/88745513-d3ee9680-d17c-11ea-931e-ebd8e578a497.png)
#### Newpipe video playback
![Screenshot_2020-07-29-09-13-23-45](https://user-images.githubusercontent.com/50725388/88745686-3a73b480-d17d-11ea-90c5-89b8596fccfe.png)
#### Describe the feature you want
Add support for video playback for devices with 19:9 Aspect ratio and derivatives. Allowing the user to zoom/fill in the whole display while playing the video. 

#### Is your feature request related to a problem? Please describe it
No, though this is a good GUI and playback enhancement for high aspect ratio devices.

#### Additional context
![Screenshot_2020-07-29-09-08-26-63](https://user-images.githubusercontent.com/50725388/88745921-c8e83600-d17d-11ea-9ecb-ddffb52103f1.png) **Newpipe video playback screen**
On Newpipe player, there's no option to increase the aspect ratio size of the video frame by the common default gesture.
![Screenshot_2020-07-29-09-13-35-89](https://user-images.githubusercontent.com/50725388/88745955-dd2c3300-d17d-11ea-8359-c764759b9848.png)
**YouTube playback screen**
Here we can see that it fills both side of the screen only leaving the horizontal black lines behind.

#### How will you/everyone benefit from this feature?
A increased user familiarity as this is a default feature on YouTube built in progressive player. As such, adding this feature in new pipe will give us (the user ) the same familiarity and efficiency on watching YouTube videos on Newpipe client. While allowing the app to leverage the screen real estate and space for more immersive watching.

**Comment by wb9688** [comment]
Try the V button at the upper right and then switching between fit/fill/zoom.

**Comment by mittorn** [comment]
Try add this in manifest application tag: `<meta-data android:name="android.max_aspect" android:value="10000.1" />`

**Comment by opusforlife2** [comment]
Closing until @elsaversailles replies.
