### ISSUE TITLE
Repo link not https (NewPipe blog)

### ISSUE THREAD

**Issue by ChiefMikeK** [TeamNewPipe/NewPipe#4002]
Click this link should be https
[Team NewPipe publishes own F-Droid repository](https://newpipe.schabi.org/blog/announcement/f-droid/pinned/f-droid-repo/)
![fdroid repo](https://user-images.githubusercontent.com/20070053/88757960-e2977680-d199-11ea-9f11-20f3a744ebc3.png)
```
Address  

  http://archive.newpipe.net/fdroid/repo  

  Description  
  Official mirrors  
  User mirrors  

  https://archive.newpipe.net/fdroid/repo  

This repository has not been used yet. You need to enable it to view the apps it provides.  
```

>  I had to remove the repo then reinstall it after changing to https

**Comment by Stypox** [comment]
Could you move this issue to https://github.com/TeamNewPipe/website
