### ISSUE TITLE
Imported data is only updated  after restart of NewPipe

### ISSUE THREAD

**Issue by Imarok** [TeamNewPipe/NewPipe#4006]
### Version

- 0.19.6
- 0.19.8

### Steps to reproduce the bug
1. Export database
2. Uninstall NewPipe from F-Droid repo
3. Install NewPipe from NewPipe repo
4. Import database

I could experience the bug when going from the 0.19.6 F-Droid repo version to the 0.19.8 NewPipe repo version.

### Expected behavior
All the exported data gets applied instantly

### Actual behaviour
- The recently played tab shows not the recently played videos but some random suggestions as if this was a cleanly new installed version.
- The subscribed channels tabs shows the subscriptions. But when I tap on a channel I can subscribe again. Then it is listed twice in the subscription list.
- The tab that normally shows new videos of subscribed channels is empty.

After I restarted NewPipe it seems like the imported data was applied correctly. But I still have this one channel (that I subscribed to again before the restart) twice in my subscription list.

**Comment by Stypox** [comment]
#3312

**Comment by Imarok** [comment]
> #3312

I'm not sure this is the same bug.
As I understand #3312 only happens when you change the order of tabs.
And the only issue that is observed in #3312 is the wrong ordering of the tabs.
So this is definitely a related bug but not automatically the same.
This issue (#4006) goes even deeper as it can cause bugs even after the restart: If you subscribe to an, in theory already subscribed,  channel before restarting you'll have this channel twice in your subscription list even after restart.
