### ISSUE TITLE
Importing subscriptions from previous export failed

### ISSUE THREAD

**Issue by iamrobox001** [TeamNewPipe/NewPipe#4010]
### Version
19.8

### Steps to reproduce the bug
1. Go subscriptions tab
2. Press on Import from previous export

### Expected behavior
The subscriptions and saved playlists should be imported from the file
### Actual behaviour
A flashing message appears and it says "Could not import subscriptions".

### Screenshots/Screen recordings
![Screenshot_20200729-220330](https://user-images.githubusercontent.com/38200989/88828326-b8b97080-d1e8-11ea-8cdc-697b60f6acae.jpg)

### Logs
Nothing crashes, so no logs

#### The file in question
The file had been exported from NewPipe version 19.5 from the f-droid repository. Import is tried to be done on version 19.8 downloaded from GitHub release section.

Here:
[NewPipeData-20200729_205152.zip](https://github.com/TeamNewPipe/NewPipe/files/4996281/NewPipeData-20200729_205152.zip)

**Comment by Stypox** [comment]
That's not a subscription file, that's a database file (which contains all data about the app, among which subscriptions). You need to import it from "Settings -> Content -> Import database"

**Comment by GitterDoneBoi** [comment]
@Stypox it's the same issue when I try it with a subscription file. The "Import from previous export" option fails to import, but when I press on "Import from YouTube" and then press "Import file" it works as expected.

**Comment by iamrobox001** [comment]
> That's not a subscription file, that's a database file (which contains all data about the app, among which subscriptions). You need to import it from "Settings -> Content -> Import database".
> 
> Maybe we should change the error message so that it says that "if you were trying to import a .zip database file, try from Settings -> Content -> Import database"

oh.
