### ISSUE TITLE
"Could not play this stream" Error on select video in v0.19.8

### ISSUE THREAD

**Issue by nemm7CEXDYC9q0xN0Kd20GQAc** [TeamNewPipe/NewPipe#4017]
Trying to play this video https://www.youtube.com/watch?v=Xs9rnAH3VAQ, results in the error "could not play this stream" and then it loads until I close the video. I am able to watch other videos, and have tested this video on 2 devices but couldn't watch it on either.
I can play in background successfully, but downloading the video results in a playable file that is clearly corrupted as it skips forward repeatedly while displaying a black screen and playing static. I am able to download other videos successfully.

**Comment by TheProgrammingDog** [comment]
I also had this issue with different videos, you can get around it by playing the video at a different resolution (e.g. 1080p instead of 720p) or changing the default video format in Settings > Video and Audio to WebM.

It's been discussed a lot in #2415.

**Comment by nemm7CEXDYC9q0xN0Kd20GQAc** [comment]
> 
> 
> I also had this issue with different videos, you can get around it by playing the video at a different resolution (e.g. 1080p instead of 720p) or changing the default video format in Settings > Video & Audio to WebM.
> 
> It's been discussed a lot in #2415.

Thank you, that solved the issue. I don't this post adds anything new from #2415, so I will close it.
