### ISSUE TITLE
NewPipe responds to pressing Bluetooth Earphone media buttons when it shouldn't

### ISSUE THREAD

**Issue by TheProgrammingDog** [TeamNewPipe/NewPipe#4020]
### Version

- 0.19.8

### Steps to reproduce the bug

1. Have Newpipe installed but closed and not playing anything
2. Connect a Bluetooth earphone with a media control/button
3. Press the media button while on the Android homescreen or in another app

### Expected behavior

Newpipe ignores the input
### Actual behaviour

An empty player controls notification is created
### Screenshots/Screen recordings

![Screenshot_20200730-200615_Chrome](https://user-images.githubusercontent.com/68926464/88963812-5459e800-d2a0-11ea-9fc4-8d0b9e1633e3.jpg)

### Logs

N/A

### Additional Info
I only have one pair of Bluetooth earphones so I'm not sure if this only affects the model I have. Also, if another application is actively playing media then Newpipe doesn't interfere but it does interfere when trying to change the volume using the earphone's built in touch controls while no media is playing.

**Comment by wb9688** [comment]
Known issue, fixed in #2907
