### ISSUE TITLE
Go back to previous screen on Guru Meditation errors

### ISSUE THREAD

**Issue by KhushrajRathod** [TeamNewPipe/NewPipe#4026]
#### Describe the feature you want

Go back to the previous screen on Guru Mediation website parse errors

#### Is your feature request related to a problem? Please describe it

Whenever I encounter a website parse error (or any guru meditation error), and go back, it leads me to the home screen. It's better to go back to the previous screen, so users can retry.

#### Additional context

Steps:
1. Press back on getting a Guru meditation error

2. You'll be on the home screen instead of for ex. The search screen where you searched for your video

#### How will you/everyone benefit from this feature?

It's easier to retry when this feature is implemented

**Comment by cwyc** [comment]
Even better, handle the exception and show a retry button.

**Comment by Stypox** [comment]
What do you think of #5148
