### ISSUE TITLE
[Feature Request] ability to view and post comments for YouTube videos

### ISSUE THREAD

**Issue by mikeloeven** [TeamNewPipe/NewPipe#403]
In order to be an Effective replacement for the YouTube app NewPipe really needs to support the comment and rating system by allowing users to both of you and post comments to the current video

**Comment by theScrabi** [comment]
That would require to login to Youtube, and that will not be supported.
However if you want to see commends you can try [SkyTube](https://f-droid.org/repository/browse/?fdfilter=skytube&fdid=free.rm.skytube.oss), and if you also want to comment your self try [WebTube](https://f-droid.org/repository/browse/?fdfilter=webtube&fdid=cz.martykan.webtube).
