### ISSUE TITLE
Background player with no media controls Android 11

### ISSUE THREAD

**Issue by Dr-Fate** [TeamNewPipe/NewPipe#4031]
Hey there, im enjoying this app quite a lot for some years now.
I have a Pixel 2xl Android 11 beta 2.5 now, i can't use background media player properly, it doesn't show the media control.
I'll post some pics to show.
Thanks for your work guys! i love this alternative!
https://ibb.co/V3jHhPK
https://ibb.co/CKJ1XKM

**Comment by wb9688** [comment]
#3178 adds new notifications that will work on Android 11.

Btw could I ask you to test [this](https://github.com/TeamNewPipe/NewPipe/pull/3777#issuecomment-666176793) (see the linked comment for details)? It adds proper support for Android's built-in file picker, but we need someone to test it on Android 11 (as we don't have any Android 11 device yet). Thanks in advance.

**Comment by Dr-Fate** [comment]
For the meantime I can't download the #3178 seems Firefox send is in maintenance.
On other hand your "use sar by default" apk doesn't do the trick, sorry.
I'll attach image.
![Screenshot_20200731-122518](https://user-images.githubusercontent.com/6537159/89050953-d9d5aa80-d329-11ea-81b8-db0ac8d0aa0d.png)

**Comment by nmz787** [comment]
Same issue here, even swiping up from the multitask view doesn't stop the player. Android 11 is horrible stuff on all accounts for me so far.

**Comment by Stypox** [comment]
@nmz787 please test release 0.20.0 in #4332

**Comment by nmz787** [comment]
Worked a few times, now no longer

**Comment by Dr-Fate** [comment]
Hey guys, pixel 2xl android 11 here... 
I've been trying this test release 0.20.0... RC4
Landscape mode... with media controls working and visible (was an issue before)
Background play working fine (i use the option "hide player when the media session has ended" OFF in android settings) so if i dismiss the notification it just keeps playing... and the notifications appears again with the rest of the media.
I can resume a background play anytime.
I can open the app while i have a video in background and start playing the video almost instant... (if i want to see the video i was listening from the background)... i used to have some trouble with this... not anymore.
I downloaded videos....audios too... no problem.

About @nmz787 saying "swiping doesn't stop the player".... well... it does... when you have in "Behavior" "minimize on app switch"... to NONE... but.. if you set to  "minimize to background player" of course... it will continue...... at least in my case. (i love this actually... and the possibility to decide what to do)

So... rounding up... this version is awesome!

**Comment by opusforlife2** [comment]
There was a lot to unpack here. 😅

Just to be clear, you're saying you see no more bugs with the latest RC?

**Comment by nmz787** [comment]
I did notice something last night, where a video I played earlier kept showing up when hitting back to return to my search results. I would be in the search results, click one, play it briefly (I was using both video and background variously), then hit back to (attempt) to return to the results, but instead would be brought back to a previous video page, hitting back once more returned me to the search results. A little annoying to have the extra back button press, but nothing obviously broken in a severe way.

**Comment by opusforlife2** [comment]
> then hit back to (attempt) to return to the results, but instead would be brought back to a previous video page

That's intended. The back button navigates you through the videos you've opened in reverse order. The queue is saved in the minimized player so that you don't lose it. For this particular navigation you want to do, get used to swiping down to minimize instead of tapping back.

**Comment by nmz787** [comment]
Ok, if I swipe away the background player notification, how do I get back to it? The application is now opening videos by default when I enter them, causing previously playing background audio to stop. But if I enter a list of videos it doesn't stop the background audio, and I can long press the background button at the top of the list and it says "adding to background queue"... But how do I view this queue? I was playing a song in background, then added a list to the background queue, then went to another video intending to background queue that too... But it started autoplaying, which presumably destroyed the earlier background queue (but I can't access this, at least not obviously, so I can't really check).

**Comment by opusforlife2** [comment]
Don't swipe away the notification for now. The notification PR was finished in a rush and this bug was known, but couldn't be fixed because of lack of time. Can you open a new issue for this bug, though? This definitely must be fixed.
