### ISSUE TITLE
Improve Update function

### ISSUE THREAD

**Issue by stoneubi** [TeamNewPipe/NewPipe#4032]
Hi there, 

I would like to ask for some improvements about the update function. 

Basically I share newpipe within my family and friend. Fdroid is by far the slowest way to get new updates on newpipe. 

Github is the fastest way but for a standard user to complicate to find / download / install newpipe. 

A very cute way to manage alternative apks is Aurora Droid, a play store for apps. 

My feature request is:
* could there be any better way to integrate a update function within newpipe -> one button update function
* or is there any way to provide the repoID or any other info to add the existing github repo to the aurora droid store?

I was not able to get this working with this data:
https://archive.newpipe.net/fdroid/repo/?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501

My main question would be to get some easy working update function within newpipe or e.g. aurora droid to speed up the update possibility. Actually, there is a lack of time between the github release time and the froid publish time of days. 

Many thanks
Stoneubi

**Comment by vdbhb59** [comment]
AuroraDroid is just another front end for F-Droid, as an alternative. It fetches applications from repositories itself, and does not hold its own repo. The GitHub ones and F-Droid ones have one difference. F-Droid Main repo holds all FOSS/FLOSS apps which have no analytics/trackers. At least AFAIK.

**Comment by stoneubi** [comment]
I finally got this to work in Aurora Droid - benefit is, that updating newpipe is much easier. 

Add a new repo in Aurora Droid add Repository - Manually add repo

Enter the following data:
* RepoID = Newpipe
* RepoName = Newpipe
* https:// = https://archive.newpipe.net/fdroid/repo/
* Fingerprint = E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501

Maybe this will help other users as well to manage updates easier for e.g. family members :-)

Best regards
Stoneubi

**Comment by vdbhb59** [comment]
As I said, it is all repo. You can do the same with F-Droid, M-Droid or Foxy Droid.

**Comment by stoneubi** [comment]
@ vdbhb59: yes this is right. In my experience in aurora droid you can add own repos. By adding https://archive.newpipe.net/fdroid/repo/ is shows, that the latest version of newpipe is available by July 28 while the lastest verison on fdorid is available by June 30. Would is be faster to get the latest version of newpipe by downloading it from the above repo instead of waiting for the repo publishment to froid?

**Comment by vdbhb59** [comment]
Actually no. What you did was add repo. F-Droid main repo holds newpipe too, while newpipe repo holds only its own app(s). F-Droid main takes 5-7 days to build and publish as it takes time for all analysis and ensuring safe apps are delivered. While you can view the same app via newpipe repo, but F-Droid main repo publishes once it is built.

**Comment by DI555** [comment]
diar sirs, could you please explain me what the difference between 2 builds in f-droid's newpipe page:  normal newpipe.apk  and  newpipe_cb84069.apk ???

**Comment by opusforlife2** [comment]
Closing as answered.
