### ISSUE TITLE
Constant ping sound during background play

### ISSUE THREAD

**Issue by SirExtremis** [TeamNewPipe/NewPipe#4033]
### Version

- 0.19.8

### Steps to reproduce the bug

Play any music in background play.

I am getting this issue in Oneplus 6T running the latest update.

### Expected behavior

No ping sounds when audio plays 

### Actual behaviour

Constant ping sounds in short intervals during background play.

### Screenshots/Screen recordings

None.
### Logs

No crashes as such.

**Comment by SirExtremis** [comment]
Additional information: this issue does not happen on Amazon Prime Music, Spotify, or a local player.

**Comment by Stypox** [comment]
Could you check if #3178 fixes the issue? Specifically, test [this apk](https://github.com/TeamNewPipe/NewPipe/files/5012955/app-debug.zip)

**Comment by SirExtremis** [comment]
Yep seems to solve the issue. No pinging sounds from background play anymore.
