### ISSUE TITLE
Follow up on decryption problems

### ISSUE THREAD

**Issue by snappyapple632** [TeamNewPipe/NewPipe#4035]
Some people on the subreddit are reporting that they are no longer encountering any decryption errors on v0.19.5-0.19.7.

This has never happened as far as I could tell and is quite the anomaly. Anything worth discussing?

**Comment by opusforlife2** [comment]
Oh wow. I have test apks based on 0.19.5 and 0.19.6, and they all work.

**Comment by puppykickr** [comment]
I just came here to report the same thing.
I saw this post, so did not make a new issue.

I run 4 devices, and thought that I had updated them all.

Tonight I saw that one was not updated, but was sure that I had used NewPioe on it recently.

I checked again, and sure enough, 0.19.5 is running just fine on my 8.1.0

**Comment by Stypox** [comment]
This already happened with older versions. YouTube just reverted a change they made
