### ISSUE TITLE
Content not centered with 18:9 screen -> weird behaviour with navigation bar

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#4040]
### Version

- d8b5549fd98e43f18b993c5f36f2385cf9a80620 

### Steps to reproduce the bug
1. Look for a vertical video, eg [this one](https://www.youtube.com/watch?v=KRntP-q_R9s)
2. Launch fullscreen

### Expected behavior

It is centered, and there the video doesn't "jump" to give space for navigation bar
### Actual behaviour

It's not centered, then when you click, the video goes up so that there is space for navigation bar
### Screenshots/Screen recordings

0.19.8 
<img src="https://user-images.githubusercontent.com/58657617/89109563-8dca5900-d442-11ea-98a5-4b20b2aa2696.png" alt="0 19 8_nav_bar_1" width="300"> <img alt="0 19 8_nav_bar_2" src="https://user-images.githubusercontent.com/58657617/89109564-8f941c80-d442-11ea-9749-922b6016b2aa.png" width="300">

unified
<img alt="unified_nav_bar_1" src="https://user-images.githubusercontent.com/58657617/89109565-915de000-d442-11ea-9120-0badf5213891.png" width="300"> <img alt="unified_nav_bar_2" src="https://user-images.githubusercontent.com/58657617/89109566-9327a380-d442-11ea-8a91-18ad08940451.png" width="300">

gif for this "jump" with unified
<img src="https://user-images.githubusercontent.com/58657617/89102586-2a710480-d40b-11ea-9819-63297598c381.gif" width="300">

**Comment by avently** [comment]
Didn't changed anything. Works ok. Are you able to reproduce it at emulator? If so, on which emulator and what params should it have?

[newpipe.zip](https://github.com/TeamNewPipe/NewPipe/files/5079155/newpipe.zip)

**Comment by wb9688** [comment]
@avently: I could confirm that this issue happens on my Samsung Galaxy A50 with Android 10.

**Comment by avently** [comment]
@wb9688 
> Samsung Galaxy A50

It has cutout.

@B0pol your phone has it too? And you thought it's not important to mention?:)

Anyway, this is only happens on devices with cutout on vertical videos and in mutliWindow mode. I don't know how to deal with such devices. 
The solution could be made somewhere inside `setControlsSize` function inside `VideoPlayerImpl class`. If don't know how to fix it too the only thing I can suggest is to disable presenting of navigation bar and status bar for devices with cutout. It is how every video app do.

**Comment by avently** [comment]
After reading [the docs](https://developer.android.com/guide/topics/display-cutout) I found a solution. It is still not perfect on vertical videos (top controls panel has too much top padding and video attached to the bottom) but there is no jump and the player works perfectly in multiWindow mode.
If you want to fix issues I mentioned with vertical videos, this is incomplete solution:
Add this:
```java
activity.getWindow().getAttributes().layoutInDisplayCutoutMode =
                WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_DEFAULT;
```
here: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L1975

add this: 
```java
activity.getWindow().getAttributes().layoutInDisplayCutoutMode =
                WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_NEVER;
```

here: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L1988

[app-release.zip](https://github.com/TeamNewPipe/NewPipe/files/5081415/app-release.zip)

**Comment by B0pol** [comment]
> @B0pol your phone has it too?

yes

> And you thought it's not important to mention?:)

I thought it was related to 18:9, but most 18:9 screen have cutout 

> app-release.zip

I tested it and it's fixed, thanks. Could you open a PR?

**Comment by avently** [comment]
Take a look #4154
