### ISSUE TITLE
Different behaviour for when leaving full screen video play through minimize and back button

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#4041]
### Version

- dev branch (unified player)

### Steps to reproduce the bug

1. Start a video in full screen (horizontal).
2. Press the "back" button of the phone (for me "back" gesture)

### Expected behavior
The video continues to play in the vertical mode. As if i pressed the minimize button.

### Actual behaviour
Playback stops

**Comment by avently** [comment]
The behavior you want works currently when you have locked global orientation.
When global orientation is unlocked back button acts like you described (pauses the player). This is useful for viewing comments or selecting another video from recommendations. It's totally uncomfortable thing to see rotation when you just pressed back button. Also I don't get how you think you'll get phone orientation rotated to portrait from landscape with global autorotation enabled and phone rotated horizontally. If you have orientation unlocked why not just rotate the phone to portrait and to get desired portrait orientation?

**Comment by terrytw** [comment]
I hope we at least get an option for this. 
I think pressing back means you want to go back to the last page, for people like me, it means going back to portrait mode with the video playing, because that is what we were doing before manually switching to landscape mode.

**Comment by opusforlife2** [comment]
But now you can do so with the full screen button.

**Comment by terrytw** [comment]
@opusforlife2 Yes, I am aware that the full screen button serves the purpose. But like I said, it was more intuitive for a lot of people, and more convenient too. (You need 2 taps, first to bring up the UI, the other to exit full screen mode, and the button is small), whereas a tap (swipe if you use gesture) would do the same, and back button/gesture is much more accessible for most people.

**Comment by opusforlife2** [comment]
I'm wondering about the purpose now. I always watch videos in fullscreen, so when I tap Back, that means I want the video to pause. In that sense, tapping the fullscreen button to rotate but continue playback makes sense to me.

What is your intent when you tap Back?

**Comment by terrytw** [comment]
For me, tapping back is just an easier way to exit full screen mode, oftentimes I would watch the video for sometime, then wants to go back reading comments with the video still playing. Maybe after reading comments I would go back watching in full screen mode. If I want to pause the video, I would tap on the video. 
It is like when you tap back in portrait mode, the video does not pause, instead it retracts into a small bar at the bottom of the screen and continue playing sound while I look at other videos from my feed.

**Comment by opusforlife2** [comment]
Oh. You don't need to go back to portrait mode for that! Just swipe up on the fullscreen button and you can read comments in landscape.

**Comment by terrytw** [comment]
Thanks for the heads up. But the problem is that, for example, like I mentioned earlier, if I want the player to retract into a small bar at the bottom of the screen and continue playing sound while I look at other videos from my feed, I would need to tap on screen to bring up the UI, tap again on the full screen button to go back to portrait mode, then tap back to go back looking at my feeds. Whereas if that could be accomplished by 2 back taps, that would feel so much more convenient. 
Also on one of my devices, swiping up the fullscreen button would bring up google assistant half of the time.... I guess it is at the right bottom, so it was recoginsed as swiping up from corner.

**Comment by opusforlife2** [comment]
Nope. In landscape mode, with player controls showing, you can swipe down in the title region to minimize the player.

**Comment by terrytw** [comment]
Oh! Thank you again! That is handy! A lot of thoughts were put into it. I just need to grow used to it.

**Comment by opusforlife2** [comment]
Yeah, all this is in the release notes in the RC issue. Read them and you might find more such things. ;)
