### ISSUE TITLE
Add information about repository for fdroid to main page

### ISSUE THREAD

**Issue by aevw** [TeamNewPipe/NewPipe#4042]
From time to time YT changes keys and NewPipe stops working. I guess that by letting users know that there is a dedicated repository that pushes new fixed version of NewPipe ASAP you could avoid so many duplicates everytime it happens.
![IMG_20200801_142829](https://user-images.githubusercontent.com/69059460/89107180-86d12580-d405-11ea-9cc0-11dcea68dc44.jpg)

**Comment by Stypox** [comment]
Could you move this to https://github.com/TeamNewPipe/website ?

**Comment by aevw** [comment]
Ok, I did post it there as well.
