### ISSUE TITLE
Exporting subscriptions with channel groups data

### ISSUE THREAD

**Issue by aevw** [TeamNewPipe/NewPipe#4044]
When doing exporting from 
Subscription --> Export to --> File 
custom channel groups are not saved in file. 

With every new installation you have to redo groups. It would be nice if channel groups could be imported from previous export.

**Comment by wb9688** [comment]
That's intended, use export database in the settings instead

**Comment by aevw** [comment]
I really missed that option in settings, thanks for pointing it out.
