### ISSUE TITLE
Search length an options

### ISSUE THREAD

**Issue by bigbavarian** [TeamNewPipe/NewPipe#4046]
#### How will you/everyone benefit from this feature?

hi,
first i want to thank you for this great APP!

is there any chance for, to become a searchfeature for more resultes? maybe an option to set a maximum nummer oft resultes he had to show? is there a chance to filter the resultes for date, length, language and options like this. special the date option would help to find new stuff.

thanks

**Comment by Stypox** [comment]
#110
