### ISSUE TITLE
The audio is muted when NewPipe is minimized

### ISSUE THREAD

**Issue by davidhedlund** [TeamNewPipe/NewPipe#4049]
### Version
0.19.8

### Steps to reproduce the bug
1. Play any media in NewPipe with audio.
2. Minimize NewPipe

### Expected behavior
The audio is muted.

### Actual behaviour
The audio should stay alive. It's not possible to enjoy music with NewPipe and use other apps on the smartphone at the same time.

**Comment by wb9688** [comment]
Switch to the background player

**Comment by davidhedlund** [comment]
> Switch to the background player

Thanks. Most people don't know about this. How do I do that?

And why is that not done automatically?

**Comment by davidhedlund** [comment]
> Switch to the background player

The background player, Google Play Music, didn't do shit.

**Comment by wb9688** [comment]
>How do I do that?

By pressing the button with the headphones icon

**Comment by davidhedlund** [comment]
> > How do I do that?
> 
> By pressing the button with the headphones icon

Oh I see it, but the "Background" button is not implemented in the "Download" tab.

**Comment by davidhedlund** [comment]
Can you please re-open this issue?

**Comment by Stypox** [comment]
What do you mean?

**Comment by davidhedlund** [comment]
> What do you mean?

Download a video, then visit the "Downloads" tab. There's no "Background" button for each media in there.

**Comment by Stypox** [comment]
#478

**Comment by davidhedlund** [comment]
> #478

Thank you.
