### ISSUE TITLE
bugreport email is undeliverable

### ISSUE THREAD

**Issue by sm4rk0** [TeamNewPipe/NewPipe#405]
Delivery to the following recipient failed permanently:

     crashreport@newpipe.schabi.org

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain newpipe.schabi.org [89.163.224.75].

The error that the other server returned was:
554 5.7.1 <mail-wj0-f181.google.com[209.85.210.181]>: Client host rejected: Access denied

**Comment by theScrabi** [comment]
@TheAssassin your turn :)

**Comment by MarcoWilli** [comment]
Also tnp@schabi.org does not work

**Comment by theScrabi** [comment]
I see. All right.

**Comment by TheAssassin** [comment]
It appears that only Google Mail is affected by this bug. I am investigating the issue. Please give me a day to have a look at it.
