### ISSUE TITLE
History settings toggles have misconfigured functionality

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4053]
### Version

- 0.19.8 (and dev branch)

### Steps to reproduce the bug

1. Enable Watch history. Ensure Resume playback and Positions in lists are disabled (in 0.19.8 Positions in lists is automatically greyed out).
2. Play a few videos from the same list.
3. Reopen that list.

### Expected behavior

You don't see playback positions in the list.
### Actual behaviour

You can see playback positions in the list

This is clearly a bug because Watch history has the Positions in lists functionality built in somehow. Moreover, as @avently says, in 0.19.8, Positions in lists is just a dummy toggle that doesn't do anything. In the dev branch it currently has a single function that is specific to the unified player backstack.

So these two toggles currently mislead users. At least Resume playback does what it says.

The solution for this bug is that the Positions in lists toggle should regain its original function, and Watch history should lose the (same) extra function.

**Comment by avently** [comment]
This is the last usage of the setting that should control "position in list" toggle:
https://github.com/TeamNewPipe/NewPipe/pull/2517/files#diff-5b97b6c787e8fbad31d373380daed5aeL175

Just for the reference for future contributors.

**Comment by Trust04zh** [comment]
I would work on this issue.
