### ISSUE TITLE
Sound doesn't stop on incoming call

### ISSUE THREAD

**Issue by C0rby** [TeamNewPipe/NewPipe#406]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When playing a video in background and the phone is receiving a call the video/sound doesn't stop playing.

**Comment by theScrabi** [comment]
Right that does not work so far :/

**Comment by mauriciocolli** [comment]
Fixed (but still have another issue #519)
