### ISSUE TITLE
Is it possible in newpipe to play only Youtube audio in the default player? like opus or aac?

### ISSUE THREAD

**Issue by fabiorug** [TeamNewPipe/NewPipe#4062]
It would be a great feature, but I don't know if you could add this.

**Comment by wb9688** [comment]
What do you mean? Please fill in the issue template.

**Comment by ingingin** [comment]
Bruh, background player is what you gotta use then.

**Comment by fabiorug** [comment]
I'm interested to play only the audio of a video on my smartphone because my laptop headphone jack broken.
Is that possible?

**Comment by ingingin** [comment]
Dude what the heck is wrong with u LOL. I just told you man, background player .. Click on that

**Comment by puppykickr** [comment]
@fabiorug 
Why not just use the background player?

**Comment by fabiorug** [comment]
i'm trying

**Comment by ingingin** [comment]
How?

**Comment by fabiorug** [comment]
i clicked in background (but in this way it plays only audio or even video)?

**Comment by ingingin** [comment]
It will only play audio

**Comment by fabiorug** [comment]
but it downloads even the video and it plays only audio or it downloads only audio and it plays only audio?

**Comment by ingingin** [comment]
It "downloads" the audio of that video

**Comment by fabiorug** [comment]
thanks for your patience. you can close issue.
