### ISSUE TITLE
Rename Tamaziɣt Taqbaylit to Taqbaylit

### ISSUE THREAD

**Issue by BoFFire** [TeamNewPipe/NewPipe#4065]
Hi,
We should rename `Tamaziɣt Taqbaylit` to `Taqbaylit` only.
Working on the string.

**Comment by BoFFire** [comment]
Check PR https://github.com/TeamNewPipe/NewPipe/pull/4066

**Comment by TobiGr** [comment]
AH perfect, I was about to push my commit :)

**Comment by SelyanKab** [comment]
Thank you @BoFFire , yes the native name of kabyle is: Taqbaylit.
