### ISSUE TITLE
Can't play videos since last update

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#407]
After updating to the latest version (0.8.7) I can't watch videos if I:

1. Do any search
2. Click on any link
3. Go to the profile
4. Click on any link
5. Tap on the big video thumbmail

If I do it nothing happens after 5.

**Comment by theScrabi** [comment]
Noticed that, It's a nasty bug :/

**Comment by yenon** [comment]
It does work after forcing screen rotation, maybe a listener is not being set? I'm on Android 7.1.1, if that helps.

**Comment by swarnk** [comment]
Same thing. I can't watch next or suggested videos. Big play button do nothing...

**Comment by theScrabi** [comment]
Tasty bug :/

**Comment by theScrabi** [comment]
Ok I'm debugging it.

**Comment by OffifialMITX** [comment]
I've installed 0.8.7, no problems at all.

**Comment by theScrabi** [comment]
I see. I tried to diff master with 0.8.6 but I can't find anything. Even debugging does not help.

**Comment by OffifialMITX** [comment]
I found something that could be useful, it looks like an invisible element appears in front of the button. Also for some reason the standard resolution is being ignored.
<table><tr><td><img alt="Screenshot 1" width="300" src="https://cloud.githubusercontent.com/assets/22666602/21981619/9d2d1f5a-dbe8-11e6-8946-96b3e56542ef.png"></td><td><img alt="Screenshot 2" width="300" src="https://cloud.githubusercontent.com/assets/22666602/21981697/efeddd1a-dbe8-11e6-963d-ec9d3e17d442.png"></td></tr></table>

**Comment by OffifialMITX** [comment]
I also found out that if you tap on the top part of the thumbmail (above the play button) it works.

**Comment by swarnk** [comment]
Confirm this. Tap above the play button is works for me too.

**Comment by coffeemakr** [comment]
For me it works when renaming onActivityCreated to onStart. The activity already exists so this method is not called.

**Comment by OffifialMITX** [comment]
This invisible "barrier" disappears on orientation change.

**Comment by theScrabi** [comment]
aha thats it O.o
Now that's ugly. Ok now basicly there is a transparent button laying on top of the thumbnail, and in the image on the right side that button was resized, on the left site it was not resized properly.

**Comment by theScrabi** [comment]
Should work now.
