### ISSUE TITLE
Fix video player option from preferred open action (open in fullscreen)

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#4070]
### Version

- https://github.com/TeamNewPipe/NewPipe/commit/b7f50c3e124365b75fa28df5af64f94f32b10ab2 (after unified player, #2907)

### Steps to reproduce the bug
1. In audio-video settings, set "video player"
2. Open a video (from an external url?)

### Expected behavior
It open the video in fullscreen, either portrait (vertical video) or landscape mode (horizontal video).

### Actual behaviour
It open the video just like "Show info" would do.

### Additional note

"Video player" should be renamed to fullscreen ~ or something like that
People which have chosen "Video player" in settings should have fullscreen ~ preference selected

**Comment by B0pol** [comment]
It should open the video in fullscreen IMO

**Comment by ingingin** [comment]
I have something I wanna say. 

I always have the need to check the thumbnail. Currently 0.19.8 I can click a video and see the thumbnail clear and big. Now using the Unified Player I have always brought myself back to 0.19.8... I kinda miss looking at the thumbnail before I watch the video. Sometimes I don't want to watch the video but check the thumbnail or just read the comments. :)

**Comment by opusforlife2** [comment]
@ingingin Just turn off Autoplay in Video settings. This option was added by the same PR. ;)

**Comment by eladkarako** [comment]
<sub><blockquote><em>Fennec really doesn't like pressing backspace.</em></blockquote><br/>default (Samsung) keyboard helps with the "double backspace" thing..b.t.w. Fenec/FF45 hasn't got a fix for neither Meltdown nor Spectre... fyi..😱</sub>

**Comment by opusforlife2** [comment]
> It should open the video in fullscreen IMO, because that's what people wanted when choosing video player.

And the string should be changed to convey that instead.

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/4071#issuecomment-686742703 pasted here unchanged:

Ok, wait, I just tested with the Always Ask option in the latest debug apk. Both Show Info and Video Player have the exact same behaviour for autoplay off: they open the video details but don't play it. For autoplay on, both open video details, and the video additionally plays if Video Player was selected.

Now, I think a better solution than my comment above is to tweak the behaviour in this way:
- if autoplay is off, the app should show Show Info as an option, but hide Video Player. (or grey it out)
- if autoplay is on, the app should show Video Player as an option, but hide Show Info. (or grey it out)

This ^ is for the Always Ask dialog when opened externally, and for the Preferred open action dialog in Settings. Moreover if Video Player is selected as the preferred open action, then turning autoplay off should replace it with Show Info, but keep that radio button selected, and vice versa.

I think this set of behaviours will be the most intuitive.

**Comment by opusforlife2** [comment]
Also, avently's investigation for context: https://github.com/TeamNewPipe/NewPipe/issues/4071#issuecomment-686677481

**Comment by tgp1994** [comment]
I see the issue is closed, was this bug fixed? My player still opens to the info screen (non-fullscreen) when opening a link with the **Video player** option, unlike before when it would directly open the video fullscreen.
