### ISSUE TITLE
import subscription from YT not working

### ISSUE THREAD

**Issue by suchyraz** [TeamNewPipe/NewPipe#4073]

**Comment by wb9688** [comment]
Please fill in the issue template. Btw does the file you try to import start with `<opml` when you open it in a text editor?

**Comment by suchyraz** [comment]
The file is downloading from youtube site but when it's saved on phone and i want to import it to newpipe i see online this bubble message that claims the import isn't possible.
Sony Xperia Z5 premium
Android ver. 7
