### ISSUE TITLE
can't import subscription from file

### ISSUE THREAD

**Issue by suchyraz** [TeamNewPipe/NewPipe#4075]
The file is downloading from youtube site but when it's saved on phone and i want to import it to newpipe i see only this bubble message that claims the import isn't possible.
Sony Xperia Z5 premium
Android ver. 7
Newpipe ver. 0.19.8

**Comment by Stypox** [comment]
*Please **follow the issue template** when creating an issue, don't just delete everything!* Now I have to ask questions you would have already answered: what are the exact steps leading to the bug? Could you provide the subscription file downloaded from yt, if it does not contain sensitive data?

**Comment by suchyraz** [comment]
I can but dont know how. I'm from Poland and my English is pretty poor.

**Comment by suchyraz** [comment]
That is why didnt fill all template

**Comment by Stypox** [comment]
@suchyraz to upload files to GitHub, just drag them over the comment you are writing

**Comment by elsaversailles** [comment]
Happened to me too... Though some of my subscription actually get recognized some not...

**Comment by ItCameFromSpace** [comment]
I also have this issue. The XML file you export from the Subscription Manager can't be accepted by the app, as it requires a zip. Not sure if this is a separate issue as OP but this might be in the right direction

**Comment by wb9688** [comment]
@ItCameFromSpace: No, you need to use Subscriptions > Subscriptions > Import from > YouTube

**Comment by caugner** [comment]
I followed the instructions and got a `subscription_manager.bin` file. However, importing into NewPipe fails with a "Could not import subscriptions" notification.

**Comment by suchyraz** [comment]
@caugner
Exactly as in my case

**Comment by caugner** [comment]
According to the [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor) tests for the `YoutubeSubscriptionExtractor`, the subscriptions export used to be a XML format:
* https://github.com/TeamNewPipe/NewPipeExtractor/blob/5c420340ceb3912b7f54e2df7eb4e27c401f0536/extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeSubscriptionExtractorTest.java#L37-L38
* https://github.com/TeamNewPipe/NewPipeExtractor/blob/5c420340ceb3912b7f54e2df7eb4e27c401f0536/extractor/src/test/resources/youtube_export_test.xml

However, the `subscription_manager.bin` seems to be a binary file (at least according to the file extension).

**Comment by tylers86** [comment]
** FIX **

To successfully import the subscription file, do not select the .XML file produced by the NewPipe link. Instead, use a browser to navigate to YouTube.com/subscription_manager and ** VIEW THE PAGE IN DESKTOP MODE. **

Scroll to the bottom of this page and there is an export button with a tool tip about RSS Feeds. Click that export button to begin the download. 

It will download a file named "subscription_manager". It has no file extension, do not give it one. 

Now simply go to NewPipe Subscriptions tab, tap YouTube, tap Import, navigate to the file with no file extension, and select it. 

It seems that when acquiring the subs export file within NewPipe, it will download an XML file that has the XML extension already. Using 0.19.8 of NewPipe Whenever I attempted to import that XML file it would accept the file, but a "imported" notification would come up almost right away, with no import actually have taken place. 

Although the exported file with no extension has all XML syntax as it's content, not having an XML extension permits NewPipe to parse all of the XML data within the file for a proper input. 

Hope this helps.

**Comment by kelvinkad** [comment]
I know (maybe) what's happening. At least in my case it did work!
Assuming you already downloaded the "subscription_manager.xml" file from your youtube account, do the next:

Check if you are clicking the option "import from" then "Previous export".
If you are clicking this button IT WON'T WORK

You have to click the second option "Youtube" and THEN click on the bottom of the page  "IMPORT FILE"
And now choose the file you previous downloaded from youtube (in my case it was a XML file)
Now it may work.

Check the attached images to see where to click.

![47431415-0a270700-d79c-11e8-96ff-972d4ad5863f](https://user-images.githubusercontent.com/69553241/89961379-e7d3d700-dc17-11ea-8f3a-3bbf43d1fcba.jpg)
![shot_subscriptions_export_light](https://user-images.githubusercontent.com/69553241/89961381-e86c6d80-dc17-11ea-82fb-c585adc1815d.png)

**Comment by Stypox** [comment]
Let's keep only TeamNewPipe/NewPipeExtractor#384 open
