### ISSUE TITLE
Sort videos by duration

### ISSUE THREAD

**Issue by enderBJ** [TeamNewPipe/NewPipe#4079]
Dear all, 

I have subscribed to a few video channels, follow them and download the interesting ones using Newpipe. However, if you follow for instance news channels, they will have a lot of very short videos (1~2 minutes) mix with few longer videos (let's say at least longer than 10 minutes). I'm only interested in finding the long videos which are often lost between the short ones. I was wondering if Newpipe had some sorting feature allowing to display only the long videos of a channel ? (or only display videos longer than a certain time) 

Thanks in advance for your answers.

**Comment by Stypox** [comment]
#2414
