### ISSUE TITLE
Back button doesn't work with channel view

### ISSUE THREAD

**Issue by epitron** [TeamNewPipe/NewPipe#408]
Steps to reproduce: 
1. Go to a video's info page 
2. Click the channel (user name) 
3. Click a video in that channel 
4. Press back button

Expected behavior: goes back to channel videos 
Actual behavior: NewPipe exits 

Interestingly, back does work if you press back after step 2!

**Comment by theScrabi** [comment]
Yea, I noticed that the back behavior is rubish.

**Comment by theScrabi** [comment]
Should be fixed with v0.9.10

**Comment by epitron** [comment]
Woot!
