### ISSUE TITLE
NewPipe won't start after crash (if ACRA is disabled)

### ISSUE THREAD

**Issue by hunkjazz** [TeamNewPipe/NewPipe#4083]
_**ACRA**: Application Crash Reports for Android._

### Version

- 0.19.8

### Steps to reproduce the bug
1. Disable crash reports using Warden app;
2. Do something that makes NewPipe crash;
3. Try to re-open NewPipe;
4. NewPipe keeps closing.

### Expected behavior

I think NewPipe should be able to start, even if crash reports are disabled.

### Actual behaviour

NewPipe keeps closing, right after starting it.

### Context

Of course, crash reports helps debugging and improving the app. Although, I don't think _starting_ should require ACRA, at all.

I don't know if this is a good practice, but: what if there were a place for logs, under settings?

In this way, people would be able to browse a history of crash reports and report whenever they feel like.

In cases where NewPipe crashes right after starting (making it impossible to reach logs history), people could always:

- re-enable crash reports for NewPipe;
- download a third party app, for reading it.

**Comment by Stypox** [comment]
Why do you need to disable acra in the first place?

**Comment by wb9688** [comment]
Plus NewPipe does not send any information anywhere in the crash reporter, unless you press the button to send an e-mail about it and then press send in whatever e-mail client you use.

Also note how there is a bug with how we handle ACRA in the current version of NewPipe, which already got fixed for the next release.
