### ISSUE TITLE
add a download button on a playlist

### ISSUE THREAD

**Issue by Ratakor** [TeamNewPipe/NewPipe#4084]
I think it would be nice if you add a download button on playlist like the one under video.

![Screenshot_20200805-223002119 (1)](https://user-images.githubusercontent.com/45130910/89461536-6b9b4880-d76c-11ea-8282-f5e6316c4b79.jpg)

It's great because Newpipe will be more like Spotify or Soundcloud to listen music !

**Comment by opusforlife2** [comment]
Did you search for "playlist download" in existing issues?

Duplicate of #2380.

**Comment by Ratakor** [comment]
oh mb sorry i didn't found it when i search
