### ISSUE TITLE
Cancel button on "Reloading feed..." notification doesn't actually do anything

### ISSUE THREAD

**Issue by floral-qua-floral** [TeamNewPipe/NewPipe#4086]
### Version

- V0.19.8

### Steps to reproduce the bug

1. Ensure you are subscribed to a sufficient number of channels - about 20 will work if you have a slow connection, more will be required if your connection is faster. This is to provide sufficient time to press Cancel before the feed can finish refreshing.
2. Go to the What's New page and tap the refresh button at the top.
3. Before the feed can finish refreshing, open the notification tray and expand the "Loading feed..." notification. This should reveal a "CANCEL" button.
4. Tap the CANCEL button.

### Expected behavior

The CANCEL button should close the notification and cause NewPipe to stop attempting to reload the subscriptions. Alternatively, the notification could just not have a CANCEL button since it doesn't do anything and doesn't seem essential.

### Actual behaviour

The notification doesn't change or go away, and the NewPipe app continues reloading subscriptions until it either finishes or times out. Pressing the button multiple times has no effect.

### Screenshots/Screen recordings

My internet is unfortunately quite slow at the moment (that's why I was able to notice the bug), so I can't get GitHub to accept my screenshot. If anyone else would like to provide a screenshot of the expanded notification to display the CANCEL button, that would be appreciated.

**Comment by opusforlife2** [comment]
Cancelling once works perfectly fine for me. Try it with 50 or so subscriptions. The notification updates pretty slowly, so while it might show you 10 done, in reality it might have finished all 20.

**Comment by floral-qua-floral** [comment]
Aw, whoops, it looks like you're right. Just tried it out and it does indeed cancel like it's supposed to, it just takes a few seconds most of the time. My bad!
