### ISSUE TITLE
A few thoughts concerning newpipe's design

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4088]
Hi!

Well i've always had several ideas about the ui of the app, But Unfortunately due to my inability to develop for android (although i'm learning!!) i couldn't contribute anything to the project.
nonethless Here are a  few ideas with the hope that someone can implment them-if they are actually implementable - (@Stypox seems to be the right guy):

| The menu      | The front page | The search page |
| -----------         | -----------            | -----------  |
| ![path923](https://user-images.githubusercontent.com/66388840/89549448-d80f5980-d7f7-11ea-9a63-c7d983446a4b.png) | ![rect4278](https://user-images.githubusercontent.com/66388840/89549607-0b51e880-d7f8-11ea-835e-3e378dc8c038.png)        | ![path3998](https://user-images.githubusercontent.com/66388840/89549720-376d6980-d7f8-11ea-8ee7-103cd2ebee38.png)        |

sorry for the difference in size between the pictures. and thank you guys for everything you've done to this great project <3.

**Comment by Stypox** [comment]
I am not sure what you are proposing, since the pictures provide the same functionality already implemented
- for picture 1, if you mean to improve the newpipe logo, the drawer header text unfortunately cannot be changed from what it is currently, since it changes dynamically based on the name of the app. And the name of the app changes in debug/testing apks, so it wouldn't be possible to fit a different name statically.
- for picture 2, I can't spot the difference. Is it the white toolbar? If that's the case, I think it should be kept multicolor, since it gives a hint to the user what service is currently active.
- for picture 3, I also don't understand what you want to change. To me the search ui seems already intuitive and similar to other apps. Having a clear button directly there is not a good idea imo, because it would be simple to press it by accident. Also, search suggestions from history can be already deleted by swiping them away

**Comment by opusforlife2** [comment]
> Also, search suggestions from history can be already deleted by swiping them away

And deleted all at once from settings.

**Comment by panacist** [comment]
> I am not sure what you are proposing, since the pictures provide the same functionality already implemented
> 
>     * for picture 1, if you mean to improve the newpipe logo, the drawer header text unfortunately cannot be changed from what it is currently, since it changes dynamically based on the name of the app. And the name of the app changes in debug/testing apks, so it wouldn't be possible to fit a different name statically.
> 
>     * for picture 2, I can't spot the difference. Is it the white toolbar? If that's the case, I think it should be kept multicolor, since it gives a hint to the user what service is currently active.
> 
>     * for picture 3, I also don't understand what you want to change. To me the search ui seems already intuitive and similar to other apps. Having a clear button directly there is not a good idea imo, because it would be simple to press it by accident. Also, search suggestions from history can be already deleted by swiping them away

thank you for your reply, and sorry about the missing details but what i am really suggesting here is to change the overall look of the app esspecially in it's light theme form.
black on red don't seem to be a good experience really.
well let me go about your objections one by one:
#1 
i am unaware about how things work from an android coder perspective but a static image in the header seems to me about just  and when the user changes the service then image changes just like it does now
example :
![screen1](https://user-images.githubusercontent.com/66388840/89573845-c1c6c500-d81a-11ea-9f29-0660a7586db1.jpg)
of course changing the youtube logo as well ^^
#2
life is hard on black on red that's why i tried to think of how to bypass that muh that's the only idea that came to my mind and i think it looks similar to what youtube is using.
black on read:
![screen2](https://user-images.githubusercontent.com/66388840/89574698-1a4a9200-d81c-11ea-82d5-809f389a5fa2.jpg)
#3
to add a clear all functionality and even a toggle to switch back n forth between dark and light theme to me is important. people usually go with the easy road and don't like to screw the settings up or maybe out of laziness or technological illeteracy perhaps.
telegram have this functionality and i got inspired by that :
![screen3](https://user-images.githubusercontent.com/66388840/89575289-1b2ff380-d81d-11ea-93bf-c649a56bf249.jpg)

**Comment by Stypox** [comment]
1 would be an improvement, but imo not an important one, as the curret ui is already pleasant to my eye. But it would involved adding much code, so I'd not do it.
2 there are already open issues and PRs for this #3482, and we want to go with the white icons on red (or other service colors) status bar
3 as I said it would be better not to add a clear all button there, as it would be too simple to click by accident. If one often deletes search history, he is better off just deleting it. As for the theme button, you could open a separate issue (putting multiple problems in a single issue is never a good idea), but please not there are already some theme improvements coming #3632

I appreciate your dedication and ideas anyway, thank you for them :-D
