### ISSUE TITLE
Showing results for:

### ISSUE THREAD

**Issue by pomberito** [TeamNewPipe/NewPipe#4091]
when searching for a musician  "felipelli" newpipe search for "filippelli"
i remember listening his music, so it seems like a regression.
### Version

- 0.19.8

### Steps to reproduce the bug
search on youtube a phrase with a grammatical error

 
### Actual behaviour
under the search box it says: "showing results for:**correct search**" 
and only shows the corrected phrase results.
### Expected behavior
it should say: "showing results for:**correct search** , search instead **incorrect search*"
or "did you mean: **correct search**?"

**Comment by Stypox** [comment]
Afaik the thing being searched is the exact same as before, the difference is just that now a note is shown. This is not something which can be fixed, since it's built into youtube.

**Comment by B0pol** [comment]
yes, it's the same behaviour with a note. showing results for: won't change anything, but did you mean: let you change the search query, and that's an improvement.

**Comment by Estecka** [comment]
Surrounding the search string with double-quotes doesn't change anything for me, it's still being auto-corrected. \
(For instance `wanderlast` is being aggressively replaced with `wanderlust`.)

**Comment by opusforlife2** [comment]
Strange. I tried it with and without quotes and I get 'did you mean wanderlust', not 'showing results for'.

**Comment by Estecka** [comment]
Trying other mistyped words at random, some of them _do_ land me on "Did You Mean", but a handful still land me on "Showing result For". For me, this matches the behaviour of Youtube's app and website, minus the missing "Search for **uncorrected**" option.

I supposed I could get a different result by changing my region or language, but that doesn't seem to change anything either. (My defaults being France and UK english, I tried switching to US and US english.)

Assuming Newpipe works using URLs : \
For me, clicking "Search for **uncorrected**" when available will add a variable to the URL's query string :
```
Showing result for Wanderlust - `/results?search_query=wanderlast`
Did you mean: Wanderlust      - `/results?search_query=wanderlast&sp=QgIIAQ%253D%253D`
```
The added bit seems to be the same regardless of the search query, and works on both desktop and mobile websites. Adding it to search queries that do not have auto-correction don't seem to affect the results in any way.
