### ISSUE TITLE
Limited channel videos and limited channel videos from search page

### ISSUE THREAD

**Issue by cor00** [TeamNewPipe/NewPipe#4094]
### Version

-v0.19.8

### Steps to reproduce the bug

Go to Lowell Vanderpool channel or theRadBrad channel

### Expected behavior

Channel videos must be listed when scrolling to bottom or show more like youtube and playlist videos in the channel must be shown along side with other videos.

### Actual behaviour

sometimes channel videos keeps loading when scrolls to bottom sometimes not and playlist videos is not showing up in the channel along side with other videos(not playlist or single video) ,so i cant see more videos in the channel.

### Screenshots/Screen recordings

youtube from browser

![youtube from browser](https://user-images.githubusercontent.com/69377840/89702561-326cff00-d94b-11ea-8083-e629e487b596.jpg)

newpipe

![newpipe](https://user-images.githubusercontent.com/69377840/89702570-50d2fa80-d94b-11ea-9b18-709fad2a8abd.jpg)

**Comment by opusforlife2** [comment]
Playlists aren't implemented yet for Channels. There is a Channel Tabs PR in the works (not for the upcoming release, though.)

Otherwise, confirmed. There is some sort of hidden timer which decides if you can scroll further. You open it and scroll fast enough, it'll load the next set. If you get stuck, reopen the channel and try again, you can go further and further. But if you're not fast enough, you might get stuck with the first set of videos again.

**Comment by cor00** [comment]
It is working if I scroll fast at first, but if I watch and return back, I can't scroll, so what is the point unless I can't scroll anytime to see more videos if I scroll long and watch some videos and back to see other videos that means I have to scroll the previous long scroll again. This problem also applies to search activity only limited search is shown.

**Comment by opusforlife2** [comment]
> This problem also applies to search activity only limited search is shown.

Wait what? That was fixed. I just checked and it's working. Check again. Maybe there is a problem with a specific search term.

**Comment by cor00** [comment]
Whatever I search, it's not working only limited search is shown max <20

**Comment by wb9688** [comment]
@cor00: Are you actually using v0.19.8? That issue should've been fixed in v0.19.7. Is your device small enough for it to not show all 20 items at once?

**Comment by cor00** [comment]
This is weird if I tried it on memu play emulator on my laptop, it is working, but with my phone I can only see max 19 or sometimes 20 at once. My screen 540 X 960 (888 usable)
Android 8.1.0 oreo
If I use browser to browser YouTube I have no problem scrolling until I had enough.

**Comment by cor00** [comment]
@wb9688 i was having could not parse website problem and start searching if it already asked and found this.

https://github.com/TeamNewPipe/NewPipe/issues/4012

At the bottom you provide apk so I tried it and works. I solve recaptcha problem by repeatedly closing the captcha activity and click on the same video again and again for 3 times. Is this different from the current latest version.

**Comment by Stypox** [comment]
Hopefully fixed by #7659
