### ISSUE TITLE
Default content country not working for some countries

### ISSUE THREAD

**Issue by cor00** [TeamNewPipe/NewPipe#4095]
### Version

-v0.19.8

### Steps to reproduce the bug

Change the country to Ethiopia or Eritrea and restart the app.

### Expected behavior

changing content country must change the loaded content in trending.

### Actual behaviour

if i change the country to france or egypt the content is loaded with france or egypt language channel but if change the country to ethiopia or eritrea the content is loaded with english lanuage channel

### Screenshots/Screen recordings

France

![france](https://user-images.githubusercontent.com/69377840/89703055-e2dd0200-d94f-11ea-918b-efeb3430ac07.jpg)

Egypt

![egypt](https://user-images.githubusercontent.com/69377840/89703071-0d2ebf80-d950-11ea-9625-60b6363a3a32.jpg)

Ethiopia and Eritrea

![ethiopian and eritrean](https://user-images.githubusercontent.com/69377840/89703078-29caf780-d950-11ea-8fe1-f2418a3710ba.jpg)

**Comment by wb9688** [comment]
First of all, content country and content language are not the same thing.

On www.youtube.com, is Ethiopia an option you could choose for content country?

**Comment by cor00** [comment]
Choose your location, Can't see Ethiopia and Eritrea. Does that mean it's not supported?

**Comment by Stypox** [comment]
Yeah, those are unfortunately not supported by YouTube itself. This is not NewPipe's fault, and even though those content country entries do nothing for youtube, they will have to stay there since I guess other services could support them

**Comment by abelfn** [comment]
@Stypox, If I browse YouTube on the computer even though Ethiopia is not listed in choose your location, but Amharic language is listed in choose your language and I can choose Unites States for choose your location and choose Amharic for choose your language and I can access YouTube in Amharic, but in NewPipe this is not working.
