### ISSUE TITLE
The timestamp shouldn't be included when sharing an ongoing livestream

### ISSUE THREAD

**Issue by MrHeating** [TeamNewPipe/NewPipe#4098]
# Version
0.19.8

### Steps to reproduce the bug
1. Go to an active livestream
2. Share to anywhere from the player

### Expected behavior
The time shouldn't be shared. Not only is it unnecessary, but NewPipe's time doesn't correspond to anything once the stream is >30s long

### Actual behaviour
Time is shared

**Comment by nmurali94** [comment]
Hey! First time contributor here, can I take this one?

**Comment by wb9688** [comment]
@nmurali94: Sure.

Also join #newpipe on Freenode if you have any questions regarding NewPipe development. (If you don't know about IRC, we suggest using Matrix through app.element.io and then joining #freenode_#newpipe:matrix.org)
