### ISSUE TITLE
load video then load comments & related videos

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#4099]
#### Describe the feature you want

I was wandering if we can make the player start playing the video first while the comments & related videos sections catchs up
#### Is your feature request related to a problem? Please describe it

now the player starts loading comments then starts to playing the video. this in my opinion unnecessarily increases video loding time  depending on internet speed, 5-10 sec in my case (😭 crazy i know). in which more then half is for loading comments & related videos section. as you can see this is exaggerated because of my slow internet connection 😑.
#### How will you/everyone benefit from this feature?

 reducing video loading time is awesome for everyone, however this will really benefit users with slow internet connections like mine or users with modest devices (either old or budget devices). 
thanks for everyone, and I'm willing to helping with testing and anything I can.

**Comment by Stypox** [comment]
Related videos are downloaded in the same package/page as the video info, so those don't count. But even though comments are downloaded separately, the downloading is anyway done cuncurrently. Comments are usually much faster to load because much less data is tranferred, so loading them after the video info, instead of simultaneously, would hardly change any loading time.

**Comment by MD77MD** [comment]
the idea came from using YouTube app. when I use YouTube, videos load almost instantly, then everything else including: video info, comments and related videos. if this can be done in newPipe, the user experience will be much improved... 

>so loading them after the video info, instead of simultaneously, would hardly change any loading time.

I disagree with you on this point, as I mentioned videos in newPipe takes on average about 5 sec to load while instantly in YouTube. times that to the number of videos you watch everyday and then it starts to add up. perhaps users with high internet speed don't relate to this problem, but newPipe is all over the world I imagine. 

if it can be done in YouTube and YouTube Vincent then I woul love to have the same experience in newPipe as well.. so please reconsider this request. 😅

**Comment by wb9688** [comment]
@MD77MD: What you suggested isn't easily possible. What we want to do in the future is use RxJava to load all the stuff simultaneously and show stuff as soon as it's available, instead of waiting for everything to be available and only then show everything.

**Comment by Stypox** [comment]
The issue here is that a big webpage has to be downloaded to show video info; comments really hardly create any slowdown. And Youtube/Youtube Vanced are faster because they use the internal Yt API, which is built exactly to suit this usecase, unfortunately the webpage isn't.

**Comment by MD77MD** [comment]
I see, thank you anyway, newPipe is still great even without this feature and will always be my default player 😋😁.. maybe new tools can make this possible in future
