### ISSUE TITLE
Better quality for videos 

### ISSUE THREAD

**Issue by humr135** [TeamNewPipe/NewPipe#410]
Please better quality videos at least 1080p ... Meybe I meybe I want some another codec for music flac or mp3 :(

**Comment by BoBeR182** [comment]
Youtube does not offer FLAC. +1 for 4K and 1080p video.

**Comment by theScrabi** [comment]
Samse as here: https://github.com/TeamNewPipe/NewPipe/issues/291
Sorry status has not changed so far.
