### ISSUE TITLE
Android 11 No play/ pause option in pulldown menu

### ISSUE THREAD

**Issue by deathgrape** [TeamNewPipe/NewPipe#4101]
### Version

-0.19.8

### Steps to reproduce the bug

0. This is on Android 11 Beta, I'm using it on my Pixel 3 XL.
1. Play something in the background player
2. Swipe down Android pulldown menu to reach the background player
3. The controls are missing, can't play, pause, skip, etc. Also, tapping the background player in the pulldown menu does not launch Newpipe.
As a side note, I can't seem to find a way to reach the background player from within the app.

### Expected behavior

A play/pause, skip, etc. button will be there.
### Actual behaviour

The area is blank, and nothing happens when you tap the player.

### Screenshots/Screen recordings

https://imgur.com/a/1PS6XNm

**Comment by Stypox** [comment]
For now use the apk in #3178 (coming in the next version, 0.20.0)
Since you have Android 11, could you please test Pull Request #3777 (see the instructions provided there)?
