### ISSUE TITLE
follow youtube links internally instead opening browser or youtube app

### ISSUE THREAD

**Issue by vladtepesch** [TeamNewPipe/NewPipe#4107]
#### Describe the feature you want

Links in video desscription that refer youtube content or channels should be handled internally in newpipe.
Currently the browser or youtube app opens on clicking a link.

Also handle you tube short links (like youtu.be)

pasting youtube urls into the search bar should also be possible to easily get to the content of a specific url.

#### How will you/everyone benefit from this feature?

navigation between content will be more easy.
Currently it is difficult to jump to other referenced material.
Even if the link is copied it is difficult to navigate to the video because there is no way to open a specific url in newpipe (or at least i found none)

**Comment by opusforlife2** [comment]
> pasting youtube urls into the search bar should also be possible to easily get to the content of a specific url.

This already works. Try it.

> Also handle you tube short links (like youtu.be)

This as well, if you're talking about opening it from another app or pasting in Newpipe.

> navigation between content will be more easy.

That's true. And it raises more possibilities, like: these URLs could be added to the backstack. Currently, you lose your entire browsing backstack if you open such a link, since it treats it as a new Newpipe session.

**Comment by vladtepesch** [comment]
> This already works. Try it.

hm - I tried this and got  no search results. cannot reproduce it atm. so ignore this part of the request.



> That's true. And it raises more possibilities, like: these URLs could be added to the backstack. Currently, you lose your entire browsing backstack if you open such a link, since it treats it as a new Newpipe session.

yes, i would love to see this feature.

**Comment by opusforlife2** [comment]
> hm - I tried this and got no search results.

You're not supposed to get any. You simply tap enter after pasting the URL and it will take you to the video page, just like entering a URL in a browser's address bar.

**Comment by Stypox** [comment]
I can't find it, but I am pretty sure this has been proposed in another issue.

**Comment by vladtepesch** [comment]
i searched before opening the issue. if you also could not find one - why adding duplicate?

**Comment by vhouriet** [comment]
I think we can clos this issue.

> Links in video desscription that refer youtube content or channels should be handled internally in newpipe.
> Currently the browser or youtube app opens on clicking a link.

It does open in Newpipe for me on the latest version.

> Also handle you tube short links (like youtu.be)

It also works for me.

> pasting youtube urls into the search bar should also be possible to easily get to the content of a specific url.

When pasting the url in the search bar of Newpipe, it opens the video in question like opusforlife2 mentionned.

**Comment by Stypox** [comment]
Yes, fixed in last versions
