### ISSUE TITLE
[Feature Request] pasting the URL into search should open the video directly

### ISSUE THREAD

**Issue by mikeloeven** [TeamNewPipe/NewPipe#411]
Sometimes you will end up in a position where you need to copy a URL to the clipboard in order to use it. Currently if you enter a URL into the search box of new pipe it will either crash in the case of certain formats (such as shared or YouTube mobile links) or display a list of often irrelevant search results. Please add support for parsing URLs within the the search box allowing videos to be opened directly

**Comment by teod0r** [comment]
Also need to have ability to paste and open 11-numberic IDs of videos

**Comment by teod0r** [comment]
Also opportunity to copy link is needed

**Comment by mauriciocolli** [comment]
Duplicate #35
