### ISSUE TITLE
f-droid new builds. question

### ISSUE THREAD

**Issue by DI555** [TeamNewPipe/NewPipe#4111]
in f-droid repo there are appeared 2 different tipes/names of builds ..
who knows, what the difference between them in f-droid's newpipe page: normal newpipe.apk and newpipe_cb84069.apk ???

is it one of them - the one that may be used to seamless move from insalled f-droid's build to github's one ???

**Comment by opusforlife2** [comment]
Yes. If you notice carefully, one of them says:
> It is built and signed by F-Droid

and the other says
> It is built and signed by the original developer. 

This second one is the new reproducible build which has the same signature as the apk on Github, and the apk in Newpipe's personal F-Droid repo. This is the one where you can install one over the other from a different source.

The one which is signed by F-Droid has a different, incompatible signature. Can't interchange this one.

**Comment by DI555** [comment]
@opusforlife2 , oh, i see, thank you so much!
and is any chance to skip from f-droid builds to github builds seamlessly ?
may be is it possible via somehow 'magically' signed build ?
or only via root and/or export-import ?

**Comment by opusforlife2** [comment]
You mean from the incompatible F-Droid signed build to the others? Nope. That is the entire _point_ of apk signatures. They prevent "update fraud" of the kind where a malicious developer names their app exactly like a legitimate one and presents it like an innocent update.

Anyway, export-import of the entire app database is already a perfect solution, so such a thing doesn't need to be devised. I think I remember from an earlier conversation, that only download history is not restored. Rest everything is.

**Comment by DI555** [comment]
@opusforlife2 , yes, thanks!

and anyone knows ,how to see more history builds in f-droid's app page???
i see only 3 or 4 last builds(((...

**Comment by opusforlife2** [comment]
@DI555 Enable the F-Droid Archive repo from settings.
