### ISSUE TITLE
License dialog disappear after device rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [TeamNewPipe/NewPipe#4113]
### Version

-0.19.2

### Steps to reproduce the bug

Open licenses dialog and rotate

### Expected behavior

License dialog with correct reading position should remain there

### Actual behaviour

License dialog disappear

### Screenshots/Screen recordings

![Screen Shot 2020-08-11 at 7 48 28 PM](https://user-images.githubusercontent.com/67744580/89893975-e2708f80-dc0b-11ea-90f9-97d04528fa72.png)
![Screen Shot 2020-08-11 at 7 48 35 PM](https://user-images.githubusercontent.com/67744580/89893978-e3a1bc80-dc0b-11ea-8443-2c86235393b3.png)

**Comment by opusforlife2** [comment]
Confirmed on 0.19.8 as well.

**Comment by panacist** [comment]
please who ever is going to fix this make  sure to fix it for the help thing on the what's new page!

**Comment by Stypox** [comment]
> please who ever is going to fix this make sure to fix it for the help thing on the what's new page!
@nmurali94 could you fix take care of the above comment?

**Comment by nmurali94** [comment]
I'll take a look. I think I have an idea on how to handle these in a unified way rather than duplicating the current solution everywhere

**Comment by nmurali94** [comment]
This https://github.com/TeamNewPipe/NewPipe/pull/4224 contains the fix for the help popup on what's new
