### ISSUE TITLE
What will NewPipe do after invidious shuts down?

### ISSUE THREAD

**Issue by esotericDisciple** [TeamNewPipe/NewPipe#4117]
*Note that as of writing this it occurred to me that github should have a forum/discussion tab like sourceforge had/has (does anyone still use sourceforge?), because having a password manager taking up gigabytes of space because every software has to have is own forum is part of what's wrong with the world...But I'm too sleep-deprived and probably won't look up how to suggest that feature to github, let alone actually write up the proposal, today... 

Anyway, this is distressing: https://omar.yt/posts/stepping-away-from-open-source
Does that mean NewPipe will go down with invidious? Rather than that would it be possible for the team to move over to gtk-straw-viewer's project to make their UI more user-friendly? Currently that's been the most reliable player...although it's API is also invidious-dependent, I just realize...but there's no automation for subscriptions and no playlists or other user/accessablility-friendly features...

**Comment by PrestonN** [comment]
NewPipe doesn't use the Invidious API.  They have a built-in extractor that they use to parse information from YouTube and it has always been this way.  NewPipe can use Invidious links to navigate to a YouTube video, however that functionality still doesn't depend on Invidious.

Invidious shutting down will have very little impact on NewPipe and will continue to operate as usual.

**Comment by esotericDisciple** [comment]
But doesn't the search and the actual video page rely on invidio.us? Even when switching instances some channels like GameGrumps are turning up blank (no videos) and often even if youtube's embedded player is the default in settings the video page often won't load...that's not an invidio.us api issue but an issue with the app itself?

**Comment by PrestonN** [comment]
That's correct.  Pointing it to a different instance doesn't change anything functionally.  No functionality within NewPipe relies on Invidious.  If you're having issues with data not loading, I'd suggest creating a new issue or see if an issue already exists.

**Comment by opusforlife2** [comment]
I just want to clarify for anyone seeing this thread that **Invidious is not going anywhere**. Just the main instance so far, invidio.us, is going to be shut down. Other instances will work just as before.

**Comment by Anthchirp** [comment]
> *Note that as of writing this it occurred to me that github should have a forum/discussion tab like sourceforge had/has (does anyone still use sourceforge?)

[GitHub Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) is [planned to go live in Q4 2020](https://github.com/github/roadmap/issues/104). 
This is how it will look like: https://github.com/vercel/next.js/discussions
