### ISSUE TITLE
UI color doesn't change from subscriber view

### ISSUE THREAD

**Issue by zalefin** [TeamNewPipe/NewPipe#4119]
### Version

- 0.19.8

### Steps to reproduce the bug

1. Go to YouTube
2. Go to PeerTube (beta) - UI becomes orange
3. Go to subscriptions
4. Go to a saved youtuber subscription

### Expected behavior

I expected the UI to switch from Orange to Red upon switching from PeerTube context to YouTube context 

### Actual behaviour

The UI stayed orange even after switching from PeerTube to YouTube context

**Comment by opusforlife2** [comment]
Services are separated only to the extent that your searches will go to the currently selected service indicated by the colour. Apart from that, there is no other separation in the GUI yet.

**Comment by Stypox** [comment]
Yeah, this is supposed to stay this way. The color should remain an indicator of the currently active service

**Comment by opusforlife2** [comment]
What _should_ happen is that your Youtube subscriptions shouldn't be visible at all from another service. Only that service's subscriptions should be.

**Comment by wb9688** [comment]
@opusforlife2: I don't agree, you might want to view both channels in e.g. your feed.

**Comment by opusforlife2** [comment]
Then there should be clear separators demarcating the zone of each service.
