### ISSUE TITLE
[Bug] access external sdcard failes

### ISSUE THREAD

**Issue by mikeloeven** [TeamNewPipe/NewPipe#412]
In lollipop and higher when you set a default download location to a folder on an external SD card an app needs to invoke certain intents to request read write permissions on that folder the following link contains a brief explanation of the new API. Please ensure that this is properly implemented since new pipe currently crashes when attempting to download files to an external SD card

http://amp.androidcentral.com/lollipop-brings-changes-way-your-sd-card-works-kind-youll?client=ms-opera-mobile&espv=1

**Comment by theScrabi** [comment]
Yea thats right.

**Comment by Yowlen** [comment]
Pretty sure this & #315 are the same.

**Comment by theScrabi** [comment]
No this is about the new Android 6 api for getting access to the SD card. The thread you linked to was on Android 5.1

**Comment by Yowlen** [comment]
Android 5.1 requires permission to access external SD card, too, or was the implementation of how it's done changed in 6.0+?

**Comment by theScrabi** [comment]
Oh I didn't know that :P

**Comment by Yowlen** [comment]
Yep. The external storage access was restricted in Kitkat, and the access UI implemented in Lollipop.

In terms of actual implementation in the app, I did some searching just now & the top answer here is very detailed on it: http://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-android-5-0-lollipop

Generally speaking, whenever the app first goes to interact with the storage API, the app would detect if it has access to the external SD card, and if not, it would prompt the user to select it. Most apps that use multiple folders like NewPipe generally check on startup & if there's no access, they have the user select the root folder of SD card and use that single URI as the base for all operations to it.

**Comment by theScrabi** [comment]
closing if favour of https://github.com/TeamNewPipe/NewPipe/issues/962
