### ISSUE TITLE
Replace invidio.us URLs with invidious.tube

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#4124]
invidio.us will bet shutting down on Sept 1st. I personally think the next best invidious instance to use is invidious.tube.

**Comment by opusforlife2** [comment]
Newpipe doesn't use any invidious instance yet. It just takes in the invidious URL and queries Youtube anyway. There is a PR in the works for Invidious support: https://github.com/TeamNewPipe/NewPipeExtractor/pull/352
