### ISSUE TITLE
Youtube recaptcha Error

### ISSUE THREAD

**Issue by saammaibal** [TeamNewPipe/NewPipe#4125]
I have just switched to newpipe and using for a day. Now whenever I try to open youtube video it shows `recaptcha challenge` but didnt show anything to solve despite waiting for ages. Kindly look into this bug has made the youtube unaccessable from this app.
Version: 0.19.8
![Screenshot_20200814-165919](https://user-images.githubusercontent.com/68259771/90247205-8f871a00-de4f-11ea-9901-5a2b1c13dde5.jpg)

**Comment by saammaibal** [comment]
Now it is playing within browser I think but error is still there
![Screenshot_20200814-171530](https://user-images.githubusercontent.com/68259771/90248317-e988df00-de51-11ea-80da-4f13fcce87ad.jpg)

**Comment by Stypox** [comment]
See my comments in #3714
