### ISSUE TITLE
[unified player] Swiping away the last stream in the queue does not close player

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#4129]
### Version

- Apk in the regression kanban: d2e6700dd1f746ba5aba59d39a4f0f53d56ec89e (2020-08-04 13:18 UTC)

### Steps to reproduce the bug
1. Play a (single) stream in the background
2. Open the background play queue through the notification
3. Swipe away the stream

### Expected behavior
The player should stop and close

### Actual behaviour
The stream keeps playing as if nothing happened, controls are still working, but there is no stream in the play queue.

### Analysis
When the only stream playing is removed, [player.onPlaybackShutdown() is called](https://github.com/TeamNewPipe/NewPipe/blob/d1d942f3fdd6c803502d75eaf8a3dd1b778f025b/app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java#L221). But [that function](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java#L621-L626) does absolutely nothing, and there is even a comment asserting that it should do nothing:
```java
    @Override
    public void onPlaybackShutdown() {
        if (DEBUG) {
            Log.d(TAG, "onPlaybackShutdown() called");
        }
        // Override it because we don't want playerImpl destroyed
    }
```
@avently why is this the case? Shouldn't that function be removed alltoghether if it does nothing? Anyway,  `onPlaybackShutdown()` is used in the situation discussed above and when an unrecoverable error occours. Is it safe to have that function to what it ought to, i.e. shutting down everything?

**Comment by avently** [comment]
> why is this the case?

I added this blank `override` after I noticed that when errors occurs player view get destroyed (i.e. it becomes `null`) so I just wanted to make the view alive until service gets destroyed without worrying about NullPointerExceptions. 

>  Is it safe to have that function to what it ought to, i.e. shutting down everything? 

I think, yes. If the service will be shutted down too then everything will be fine
