### ISSUE TITLE
VR support? and 360 videos?

### ISSUE THREAD

**Issue by BoBeR182** [TeamNewPipe/NewPipe#413]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Is there planned support for VR or 360 videos? I want to be able to use my phone without needing GAPPS installed as a VR headset.

**Comment by theScrabi** [comment]
Probably not, I think that sounds like an extra project xD sorry.

**Comment by rugk** [comment]
Maybe you do not need to support VR things or Cardboard or so, but just a way to use touch to move the camera around in the 360°, similar how you can do it on the YouTube website.

**Comment by theScrabi** [comment]
First we need a player that would support this.

**Comment by r2308145** [comment]
nothing has changed in the regards of 360videos? wanted to ask the same question..

**Comment by renatobellotti** [comment]
What about using [this project](https://github.com/sujitkjha/360-Video-Player-for-Android)? I'm not familiar with the code of Newpipe and haven't used the library... But I'd love to have this feature :)

**Comment by Julmik647** [comment]
You can also try using code of [this](https://docs.bivrost.pro/webplayer-docs/).
