### ISSUE TITLE
[unified player] Closing through notification does not close minimized player

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#4131]
### Version
- Apk in the regression kanban: d2e6700dd1f746ba5aba59d39a4f0f53d56ec89e (2020-08-04 13:18 UTC)

### Steps to reproduce the bug
1. Launch a video
2. Minimize it (you should see trending page)
3. Close the video with the X cross in notification
4. The minimized video stopped, but it's not closed

_Originally posted by @B0pol in https://github.com/TeamNewPipe/NewPipe/pull/3178#issuecomment-668171000_

### Considerations
Maybe this behavoiur is ok: keeping the history of viewed videos even though the notification was closed does not seem a bad idea. And the minimized player can always be closed by pressing `X` again. @opusforlife2 @B0pol what do you think?

**Comment by avently** [comment]
I completely disagree with the idea to close the whole player with a fragment after pressing on `close` in notification. It's opposite of a useful thing.
When I press X in notification I expect that the player will be shutted down and will gone from background but UI in the fragment is not a part of the player and the service which holds the player. 
As you mentioned, 

> this behavoiur is ok: keeping the history of viewed videos even though the notification was closed does not seem a bad idea

this should be work like this. Let's say you were in background (in other app) and decided to get rid of notification. After you press X the notification will gone but underlaying history as well as active stream doesn't and it's great.

> And the minimized player can always be closed by pressing X again

Yep, this is true and this is why it was made like this.

**Comment by opusforlife2** [comment]
True. Interacting with just the notification should not interfere with the backstack, and the minimised player is what holds that backstack. Let it be.

**Comment by Stypox** [comment]
I agree with you ;-)
