### ISSUE TITLE
Feature Request: Add "Play next" button

### ISSUE THREAD

**Issue by TimmySkinny** [TeamNewPipe/NewPipe#4136]
#### An option to put a video on the top of the background queue.
I think it would be great to have such an option, as it saves a lot of time scrolling through the background queue, and you can play a song instantly without having to skip the current video or deleting the queue.

**Comment by MD77MD** [comment]
@TimmySkinny please see https://github.com/TeamNewPipe/NewPipe/pull/3936#issuecomment-673820846
>also long pressing on the play button could act as enqueue next. this would be even more useful after updating to unified player.

your suggestion could easily fit to what @Stypox  is working on #3936

**Comment by BruhMomient** [comment]
Would love to see this, because of the way that moving items in the playlist works, it's practically impossible to move a song from the bottom of an 800 track playlist to the top if you want for it to play next, especially with how buggy it can be sometimes.

**Comment by z3r0r4** [comment]
I intent on implementing this.

**Comment by z3r0r4** [comment]
I implemented this.

**Comment by TimmySkinny** [comment]
Thank you so much!

**Comment by z3r0r4** [comment]
really wanted this feature as well.
lets hope i can make it pass the reviews.
