### ISSUE TITLE
[Feature request] Add ability to go to search from opened video

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#414]
When I select video from an app NewPipe opens in another icon in  "Recent Apps" HW Button since latest versions. After I close NewPipe and later open it with "Recent Apps" list it opens last video, but there is no way to open search home screen unless to reopen NewPipe with desktop icon

**Comment by teod0r** [comment]
If I press BACK in reopend window it closes the program

**Comment by teod0r** [comment]
When just opening video without reopening window NewPipe does not have ability to go to search too

**Comment by theScrabi** [comment]
Hm that whole "get back" thing has to be rethought completely.

**Comment by teod0r** [comment]
As "Back" button already works, I  suggest to improve this by adding "Forward" button, also history of  searches, opened videos, visited channels

**Comment by teod0r** [comment]
А можно сделать, чтобы после просмотра видео, при нажатии хардварной кнопки НАЗАД, закрывало программу, а не переходило на поиск? Потому что удобней после просмотра нажать назад для закрытия программы

**Comment by theScrabi** [comment]
English pls

**Comment by teod0r** [comment]
Could you please make the program to exit by pressing BACK hardware button aftwr watching video instead of going to search. It is more comfortable to close the program by  hardware BACK aftaer watching video. Or make it by an option in settings.

**Comment by theScrabi** [comment]
So you mean go directly to search form the player. Instead of showing the video detail screen?

**Comment by teod0r** [comment]
No. I mean to close the program by hardware BACK instead of going to search

**Comment by theScrabi** [comment]
Oh yea you are right, that is a problem, that's right.

**Comment by teod0r** [comment]
точнее не всегда оно должно закрываться по кнопке НАЗАД. оно должно закрываться, если было открыть видео из другой программы. т.е. я открыл видео из другой программы. запустился NewPipe , проиграл видео, нажал хардварный  НАЗАД -- NewPipe должен закрыться. А если я открыл видео из NewPipe и нажал НАЗАД, оно конечно не должно закрываться

**Comment by theScrabi** [comment]
@teod0r Still use english language.

**Comment by teod0r** [comment]
More precisely it should not always close by BACK hw button. It should close if video was opened from another program. I mean if I opened a video from another program, NewPipe started, the vide was played, I pressed hw BACK button -- NewPipe should close. But if I opened a video from NewPipe and pressed hw BACK it deffinitely should not close.

**Comment by theScrabi** [comment]
Yea I know what you mean, this annoys me to.

**Comment by mauriciocolli** [comment]
@teod0r please don't mix issues together, #548 already describe the last one you posted.

**Comment by Stypox** [comment]
Closing in favour of #1873
