### ISSUE TITLE
In non-full-screen, vertical drags occasionally change volume or brightness

### ISSUE THREAD

**Issue by nyanpasu64** [TeamNewPipe/NewPipe#4142]
### Version

I found this bug on https://github.com/TeamNewPipe/NewPipe/issues/4121#issuecomment-674570482 (a slightly modified build from today), and reproduced the issue in e9d4303fdb60ffe9fe19a80790ee824597d4ef20 (latest dev).

### Steps to reproduce the bug

- Install recent dev build with unified player.
- Open a video in the main player, in portrait mode (split between the player and description).
- With the seek bar hidden (didn't test with it visible), drag the left or right side of the screen vertically.

### Expected behavior

Usually, if you drag the video up, it does nothing, but holding your finger and dragging down minimizes the video. If you drag the video down, it immediately minimizes it. It's self-consistent, but you can't scroll the video up by dragging the video body, which I don't know if it's intentional.

### Actual behaviour

Around 20% of the time, it changes the brightness or volume for a split second before scrolling. This is demonstrated in my video, before 0:23.

### Screenshots/Screen recordings

https://youtu.be/CZKbFxFZxqc

I'm on a Moto G5 Plus running Android 8.1.0.

This bug may be somewhat related to https://github.com/TeamNewPipe/NewPipe/issues/4121 . I found #4143 while experimenting with this bug.

**Comment by opusforlife2** [comment]
I'll do one better and show how you can reproduce this consistently. 😆 

Hold down your finger on any area other than the video (except the area showing views, likes and dislikes, for some strange reason). Then quickly swipe on the video with another finger. Viola. Volume and brightness gestures galore. You can only do this once, though. If you stop adjusting and lift your finger, you'll have to lift and hold down your other finger again.

So I suspect another finger of yours happens to touch the screen accidentally when you swipe and successfully change volume/brightness.
