### ISSUE TITLE
In non-full-screen, dragging vertical twice causes video to jitter instead of minimizing

### ISSUE THREAD

**Issue by nyanpasu64** [TeamNewPipe/NewPipe#4143]
### Version

I found this bug on https://github.com/TeamNewPipe/NewPipe/issues/4121#issuecomment-674570482 (a slightly modified build from today), and reproduced the issue in e9d4303fdb60ffe9fe19a80790ee824597d4ef20 (latest dev).

### Steps to reproduce the bug

- Install recent dev build with unified player.
- Open a video in the main player, in portrait mode (split between the player and description).
- Drag the video so it partially minimizes but springs back up when you release. Release the finger, and while it's springing up, press again.

### Expected behavior

Nothing weird happens. Either finger movements are ignored, are treated as trying to drag the video down, or change brightness/volume.

### Actual behaviour

When you move your finger *downwards*, the video title appears as if you were dragging the video *downwards*, but the top of the video doesn't move and the screen jitters *upwards*. Nothing happens when you move your finger up. This is demonstrated at 0:23 and later.

### Screenshots/Screen recordings

https://youtu.be/CZKbFxFZxqc

I'm on a Moto G5 Plus running Android 8.1.0. I don't know if this is an OS bug.

This bug may be somewhat related to https://github.com/TeamNewPipe/NewPipe/issues/4121 . I found this bug while recording a video for #4142.

**Comment by opusforlife2** [comment]
Confirmed.
