### ISSUE TITLE
Bookmark merge

### ISSUE THREAD

**Issue by yougoog** [TeamNewPipe/NewPipe#4144]
#### Describe the feature you want

Please add bookmark merge option when importing from file. By doing this, the bookmark in the current file will not be lost/overwrite by old one.
#### Is your feature request related to a problem? Please describe it

No
#### How will you/everyone benefit from this feature?

This is for merging multiple bookmarks file into present bookmarks without loosing the current one.

**Comment by opusforlife2** [comment]
Always fill in the template with as much detail as you can provide. Just one line with no explanations or examples is no better than ignoring the template entirely.

**Comment by yougoog** [comment]
Please chk now, i updated the template. English is not my official language, so please excuse my english.

**Comment by opusforlife2** [comment]
Ah! Now I get it. Thanks for clarifying!

**Comment by MD77MD** [comment]
this is exactly what I was talking about in this example:https://github.com/TeamNewPipe/NewPipe/issues/4076#issuecomment-668665077

**Comment by opusforlife2** [comment]
Duplicate of #4076.
