### ISSUE TITLE
Amoled support

### ISSUE THREAD

**Issue by blackCauldron7** [TeamNewPipe/NewPipe#4148]
#### Describe the feature you want

Full Pitch black UI support for amoled devices to save battery. Currently the black theme still leaves a lot of UI elements colored like the top bar.
#### Is your feature request related to a problem? Please describe it

Not exactly but yes high battery consumption.
#### How will you/everyone benefit from this feature?

The extra battery life would be worth for every amoled user.

**Comment by opusforlife2** [comment]
Test the apk in #3632 and reply if it doesn't match your expectations.

**Comment by blackCauldron7** [comment]
#3532 doesn't match my expectations @opusforlife2 as it still leaves things like the top bar colored.

**Comment by opusforlife2** [comment]
Thanks!

**Comment by B0pol** [comment]
> The extra battery life would be worth for every amoled user.

[The "extra battery life" is **really really** small](https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/)

**Comment by blackCauldron7** [comment]
@B0pol it piles up as newer phones screen gets bigger and bigger and people tend to use newpipe for quite a good chunk of time so pretty sure it would be worth it.

**Comment by mhmdanas** [comment]
I would expect most people to spend most of their time in NewPipe watching stuff, not navigating the app, so even if you disregard @B0pol's comment, the gains are probably very negligible.

**Comment by andrewbanchich** [comment]
I'd love this just for the aesthetic.

**Comment by blackCauldron7** [comment]
@mhmdanas tbh for me its just worth it for the look, all my other apps are all black. And i usually watch videos while reading the comments so theres that

**Comment by mhmdanas** [comment]
I am not against adding this; I'm just saying that the battery life gains from this change are extremely negligible.

**Comment by k9janer** [comment]
I would also appreciate a completely black title bar for night time use and to protect OLED and Plasma tvs.

Also I think NewPipe looks really sleek in black 😁
![nsmail-1_crop_crop](https://user-images.githubusercontent.com/26097284/121231299-8957a380-c890-11eb-82cf-9e1d5d4b4560.jpg)

**Comment by SameenAhnaf** [comment]
@litetex This should be closed in favor of https://github.com/TeamNewPipe/NewPipe/issues/6272#issuecomment-856608962

**Comment by litetex** [comment]
Closing this issue.

Why?
* https://github.com/TeamNewPipe/NewPipe/issues/6272#issuecomment-856608962
* There is no such thing as "Amoled support" - It's more like "Better optimization for amoled displays"
* As seen in https://github.com/TeamNewPipe/NewPipe/issues/4148#issuecomment-731596470 there is no too little battery saving.
* "... still leaves a lot of UI elements colored like the top bar" 
  * The search-bar at the top is currently the **only** place that is large enough (uses ~7% of the screen on my phone) to be considered in this issue. 
  * I don't think that really matters considering battery usage. 
When using NewPipe you want to watch videos. When watching a video there is little to no UI of the app visible. So the battery usage then depends on the type of video you are watching - Nothing we as app developers can influence.

Feel free to leave a comment.

**Comment by mhmdanas** [comment]
@litetex I think this issue should be kept open. The major reasons you closed this issue for are not valid. You didn't take into consideration that people also want this for its aesthetic value:

https://github.com/TeamNewPipe/NewPipe/issues/4148#issuecomment-731606442
https://github.com/TeamNewPipe/NewPipe/issues/4148#issuecomment-731611805

In additon, regarding your first bullet point, the issue Stypox commented on was requesting that the user be allowed to customize the app's theme to a high granularity; it's not relevant to this issue.

**Comment by opusforlife2** [comment]
@mhmdanas It would be better to open a new issue just asking for a full black theme. This thread is too much about the battery saving angle.
