### ISSUE TITLE
Video jump glitch when swiping up from seekbar

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4149]
### Version

- latest unified player test apk (3rd version here: https://github.com/TeamNewPipe/NewPipe/projects/17#card-42918515)

### Steps to reproduce the bug

1. Play a video in fullscreen.
2. Swiping up on the seekbar or the fullscreen button causes the video to "jump" down to accommodate the status bar appearing.

Nothing to see here. Move on. This issue is just to document the bug. It is **already fixed** in this test apk: https://github.com/TeamNewPipe/NewPipe/issues/4121#issuecomment-674570482

**Comment by opusforlife2** [comment]
@avently Please add fixes linkage whenever you open the PR.

**Comment by avently** [comment]
Man, stop posting useless issues, please. Don't steal our spare time!

**Comment by opusforlife2** [comment]
XD I'm not stealing anyone's time but my own. And I'll just add the fixes linkage myself, you lazy bum.
