### ISSUE TITLE
Update check feature in about (enhancement)

### ISSUE THREAD

**Issue by tomazx** [TeamNewPipe/NewPipe#4151]
Hello

I want suggest a feature that users can check new updates for NewPipe in About section
Maybe it's a button to check the update
After new update is available, throw the NewPipe download link

Thanks

**Comment by opusforlife2** [comment]
This functionality exists, and is only disabled for builds signed by F-Droid's official buildserver. The apk you can get from Github, from Newpipe's custom F-Droid repo, and from F-Droid itself (it's marked as signed by the developer) will have this option in the Settings menu.
