### ISSUE TITLE
Dont make unnecessary updates

### ISSUE THREAD

**Issue by BeingDatta** [TeamNewPipe/NewPipe#4153]
Dear Team Newpipe,

Plese I beg u dont make unnecessary inferior updates in such a way that instead of providing with features u guys provide us with non operative bullshit.

Today I was about to watch a Motivational Video which was mind u no porn or no violence or 18+ but you recently updated 0.19.8 gave me an error "Video Unavailable" i guess its also a new feature u guys introduced right ?

Regards.

**Comment by opusforlife2** [comment]
Being antagonistic helps no one. From the front page:

"WARNING: THIS IS A BETA VERSION, THEREFORE YOU MAY ENCOUNTER BUGS. IF YOU DO, OPEN AN ISSUE VIA OUR GITHUB REPOSITORY."

So yeah. Explain what you mean, give a link to the video, etc,etc.

**Comment by wb9688** [comment]
Could you confirm that "YouTube restricted mode" is disabled and that you could view that video in your browser?
