### ISSUE TITLE
Lock video player status

### ISSUE THREAD

**Issue by blackCauldron7** [TeamNewPipe/NewPipe#4157]
#### Describe the feature you want

I think it would be nice if you add a feature to lock the video player which prevents accidentall touches on elements like the seekbar.
#### Is your feature request related to a problem? Please describe it

Yes I sometimes accidentally touch the seekbar and it messes up my viewing experience.
#### How will you/everyone benefit from this feature?

UX Improvement

**Comment by Stypox** [comment]
#1575
