### ISSUE TITLE
Clarify the Need to Click-Press the Checkmark After completing a reCaptcha or Adapt the UI

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [TeamNewPipe/NewPipe#4163]
It seemed the UI was stuck on the reCaptcha screen after completing the challenge.  But a checkmark in the upper-righthand corner of N.P. needed to be pressed/clicked.  Users should know this or else it should be handled automatically.

**Comment by Stypox** [comment]
I found any other way of detecting the resolution unstable and unreliable, so I decided to let the user press the button when he has finished. Isn't the subtitle "Press Done when solved" explanatory enough?

**Comment by Stypox** [comment]
Also, again, please use the template! I can't think of an alternative solution, so if you have one please write it here (as you would have already done if you had followed the template)

**Comment by opusforlife2** [comment]
> Isn't the subtitle "Press Done when solved" explanatory enough?

@Stypox How about "Tap on check mark in top right corner when solved"?

**Comment by Stypox** [comment]
Too long
