### ISSUE TITLE
Add support brandnewtube.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [TeamNewPipe/NewPipe#4166]
#### Describe the feature you want

Add support for site `https://brandnewtube.com/`

**Comment by KonoromiHimaries** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/pull/325

**Comment by lionirdeadman** [comment]
This just looks like a terrible conspiracy site... do we want this?

**Comment by TobiGr** [comment]
We have put there a template which should be filled out. Please don't leave it empty.

Being a few seconds on [their landing page](https://user-images.githubusercontent.com/17365767/90830692-734d1680-e342-11ea-8dd3-80fd5f864a22.png) seems to be enough to see what kind of misinformation is spread by them intentionally (featured and highlighted at the top!). We have been crystal clear about [our position regarding these services](https://github.com/TeamNewPipe/NewPipeExtractor/pull/325#issuecomment-626801193), which claim to provide "free speech", in the past. This one is just one more example for a conspiracy theories' and dubious propaganda spreader.
