### ISSUE TITLE
Please make a BitChute frontend

### ISSUE THREAD

**Issue by cubetronic** [TeamNewPipe/NewPipe#4167]
I love NewPipe.

I think it would be really useful, especially for playlists and playing in the background, so I can control music videos with my stereo, etc.

BitChute is in. YouTube is out.

Thanks!!!

**Comment by TobiGr** [comment]
There was a discussion about this already. We will not add BitCute for multiple reasons as you can read here: https://github.com/TeamNewPipe/NewPipeExtractor/pull/325#issuecomment-626801193
