### ISSUE TITLE
getting the wrong error message

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4174]
### Version

-0.19.8

### Steps to reproduce the bug

1. Go to https://libre.video/video-channels/894b5a3b-aaf6-445f-9fde-b2f780ca03c9@peertube.live/videos
2. there you have it 

### Expected behavior

anything other than a network error would make sense 
### Actual behaviour

getting a network error while it is obviously not 

(actually all of the videos on that channel don't work as well)

**Comment by opusforlife2** [comment]
Confirmed.

**Comment by Stypox** [comment]
Could you check if [this apk](https://github.com/TeamNewPipe/NewPipe/suites/1836810430/artifacts/35510945) from the ci in #5148 solves the error-reporter-crashing issue?
