### ISSUE TITLE
Some 4k vertical videos don't play

### ISSUE THREAD

**Issue by mobd** [TeamNewPipe/NewPipe#4175]
### Version

0.19.8

### Steps to reproduce the bug

Go to a vertical 4k video and play it in 2160p (or sometimes 1440p too). It doesn't happen for all videos but here are some examples:
https://m.youtube.com/watch?v=izPbP1ByyBs
https://m.youtube.com/watch?v=Rwyr4Q6tD4Q (many videos on this channel give an error)
https://m.youtube.com/watch?v=Ah0Ys50CqO8

### Expected behavior

The video is played.
### Actual behaviour

The video exits immediately and an error says "Unrecoverable player error occurred".
### Screenshots/Screen recordings

![Screenshot_20200822_142058_org schabi newpipe](https://user-images.githubusercontent.com/66154603/90956140-e9a56200-e483-11ea-9e35-748e47fc1e56.jpg)

**Comment by opusforlife2** [comment]
@mobd A Play Store search had this result https://play.google.com/store/apps/details?id=com.stream.video.exoplayer which doesn't have any ads. You could try this one.

**Comment by wb9688** [comment]
@opusforlife2: That one hasn't been updated for like 2 years plus I don't think it's a good idea to recommend proprietary stuff here.

**Comment by opusforlife2** [comment]
Then the only option I see is to build the default Google Exoplayer apk to hand out for testing.

**Comment by mobd** [comment]
I installed that app but it doesn't show up as an option to use, so I don't think it can handle the right intent. The same would probably be true for google's demo app.

**Comment by Stypox** [comment]
> The third link (Billie Eilish) gives me a search suggestion when I enter it in the search field in Newpipe. The suggestion is the same URL, except all the capital letters are made small case.

I can't reproduce @opusforlife2, are you sure you copied the url correctly?

**Comment by opusforlife2** [comment]
Of course. If I enter the link directly, it takes me to the video. If I tap the suggestion, it says "Content unavailable".

If suggestions are provided by Youtube directly, then I think it's possible lots of people pasted that URL into the search box on Youtube and it just saved the URL in its database after formatting it or something.

**Comment by Stypox** [comment]
@opusforlife2 oh sorry, I misunderstood. I can't reproduce even now that I understand, but this is reasonable as until you press search newpipe does not know it is being fed a url, so it obviously tries to fetch search suggestions

**Comment by opusforlife2** [comment]
_Why_ doesn't Google provide a ready to install APK for Exoplayer/Simple Exoplayer/whatever?

**Comment by opusforlife2** [comment]
@wb9688 F-Droid finally got an Exoplayer-based app. No internet permission!

Just (Video) Player (Simple video player based on ExoPlayer library) - https://f-droid.org/packages/com.brouken.player

@mhmdanas @Stypox You could bookmark this URL for when it is needed for testing.

**Comment by litetex** [comment]
Can't reproduce any of the above problems....

Is this still a problem?

**Comment by mobd** [comment]
I still get the same error with version 0.21.9

**Comment by litetex** [comment]
Than it has to be something device/OS specific.. or did you change your device/OS in the meantime?

**Comment by opusforlife2** [comment]
> Ah, those both have their own players, could you try an external player that uses ExoPlayer?

@mobd Since I've linked a FOSS Exoplayer app above, could you try this now?

**Comment by mobd** [comment]
@opusforlife2 If I use the external exoplayer I get a MediaCodecVideoRenderer error, so I suppose this is not an issue with Newpipe. Should I close the bug?

**Comment by opusforlife2** [comment]
No idea. @Redirion?

**Comment by Redirion** [comment]
@mobd please collect logs with logcat. I am also unable to reproduce the issue.

**Comment by litetex** [comment]
@mobd 

You may also checkout the experimental build from https://github.com/TeamNewPipe/NewPipe/pull/7142 which enables reporting player errors:
[app.zip](https://github.com/TeamNewPipe/NewPipe/files/7227274/app.zip)

Knowing the exact error will help diagnosing it further 😄

**Comment by AudricV** [comment]
Is it still an issue on the latest version? If yes, what does the report generated from the error notification gives?
