### ISSUE TITLE
10 seconds forward jump plays next video

### ISSUE THREAD

**Issue by William6868** [TeamNewPipe/NewPipe#4181]
### Version

0.19.8

### Steps to reproduce the bug

1. Go to Menue -> Bookmarked Playlists
2. Press on a playlist 
3. Press on Background
4. Swipe down from the very top of the screen to see the current video playing in background in the notifications list
5. Press the "10 seconds forward jump" button

### Expected behavior

The video should jump 10 seconds forward

### Actual behaviour

Usually it works well but sometimes it starts the next video on the list. I couldn't figure out when it does that.

**Comment by opusforlife2** [comment]
Are you sure you're not accidentally tapping the "Play Next" button? It's right next to the Skip Forward button.

**Comment by William6868** [comment]
I'm not using the background playlist. In 4. I wrote:
"Swipe down from the very top of the screen to see the current video playing in background" - in the notifications list. 
Just updated the original post to make it clearer also.

There is only "jump backwards" + Play/Pause + "Jump forward" buttons there.

**Comment by opusforlife2** [comment]
If you play only one video in the background, you get the skip forward and backward buttons. If you have a queue, then those buttons become the play next/previous buttons instead. You can't skip backward/forward from the notification if you have a queue.

**Comment by William6868** [comment]
Just tested it and you're right.

Is there an option to change it? It's very confusing.
I would love to add it to the settings if you have a pc I can remotely work on it :-) I don't have pc I can work on it locally here :-/
I will also love to contribute to the development in general :-) I love it :-D

Thanks for everything!

**Comment by opusforlife2** [comment]
@William6868 This is going to be solved by the new Notifications PR. Feel free to test the latest apk in #3178.

> I will also love to contribute to the development in general :-)

You're most welcome! Come on the Newpipe IRC channel to chat and see where you could help out!
