### ISSUE TITLE
Video not working with new version

### ISSUE THREAD

**Issue by FlorianSteenbuck** [TeamNewPipe/NewPipe#4182]
Some workmate come to up with a issue on mutiple videos

### Version

- v0.19.8

### Steps to reproduce the bug
1. Go to 'Subscription'
2. Open the Channel 'Helm-Peter Kultfan' - https://www.youtube.com/channel/UCGKUfatkkZNkp8Dberm8GXQ
2. Press on video 'Auch wenn es nur ein Test war gegen so ein Gegner darf man nicht verlieren!Daniel hat noch sehr viel' - https://youtu.be/0mYr1x7m9UY

### Expected behavior
should find the video like the web version of youtube

### Actual behaviour
can not find video

**Comment by Redirion** [comment]
I am unable to reproduce it. This video and a newer one are found. I guess this one could be solved by the feature request of issue #3329 
The pull to refresh should also be added in the ChannelFragment

**Comment by opusforlife2** [comment]
> can not find video

You'll need to be more specific. If there is a toast, what does the toast say? If there is an error, paste the log.

**Comment by FlorianSteenbuck** [comment]
I can give you a screenshot:
![Screenshot_20200824-143812](https://user-images.githubusercontent.com/13929591/91154886-5e65df80-e6c2-11ea-8420-fd45e9379c9f.jpg)

**Comment by wb9688** [comment]
Have you enabled "YouTube restricted mode"? If so, disable that.

**Comment by FlorianSteenbuck** [comment]
@wb9688 works now, what is that option for ?

**Comment by wb9688** [comment]
It'll enable https://support.google.com/youtube/answer/174084
