### ISSUE TITLE
Shuffle at playlist start

### ISSUE THREAD

**Issue by EliasKomar** [TeamNewPipe/NewPipe#4188]
#### Describe the feature you want

It would be nice if there was a way of starting a playlist so that it is shuffled from start on, instead of the current way (which is: start playing, access queue, select shuffle)

#### How will you/everyone benefit from this feature?

This is especially helpful for people listening to music, because at the moment you always have to listen to the first song of the playlist whether you are shuffling or not and it simply drives one crazy to listen to the same song so often.

**Comment by opusforlife2** [comment]
Would #4089 address your use case?

**Comment by EliasKomar** [comment]
Yes and no it would kind of fix this problem to save whether you want to shuffle it or not. The shuffling feature itself is very much concealed and i didn't actually know it existed before I looked it up. So I would suggest to make it more obvious.

**Comment by opusforlife2** [comment]
It would be made more obvious by the new notification style. Check it out in #3178.

**Comment by EliasKomar** [comment]
Could you tell me whic specific part would resolve that problem so that we can agree wheter or not this issue should be closed in favour of #3178

**Comment by opusforlife2** [comment]
You can have Shuffle as one of the 5 action buttons that show in the notification.

**Comment by EliasKomar** [comment]
Ok that settles it

**Comment by EliasKomar** [comment]
A point that I forgot about, is that #3178 doesn't fix that you have to listen to the first song of a playlist until you shuffle and skip to the next. It's better if It is shuffle from the start on.

**Comment by opusforlife2** [comment]
You forgot about this: https://github.com/TeamNewPipe/NewPipe/issues/4188#issuecomment-680153554
