### ISSUE TITLE
Android TV: YouTube (music) videos flicker black frames and glitchy audio

### ISSUE THREAD

**Issue by qu4ntumrush** [TeamNewPipe/NewPipe#4191]
### Newpipe Version
0.19.8, not in 19.5 or 19.6 (19.7 couldn't run)

### Steps to reproduce the bug
Found in almost every video while playing on Tivo Stream 4K Version 9, Kernel 4.9.113

### Expected behavior
Videos look smooth with no flickering/blinking/black frames and consistent audio

### Actual behaviour
Most videos flicker or blink black frames every few seconds, and some resolutions have crackly audio

### Screenshots/Screen recordings
Example: https://www.youtube.com/watch?v=iKftXPcogRw flickers on 1080p and 480p, less flickering but crackly audio on 720p

### Random observation
Seems to be less prevalent in video game streams but far more prevalent in music-related videos

**Comment by Stypox** [comment]
> 0.19.8, not in 19.5 or 19.6 (19.7 couldn't run)

Strange, we didn't make changes to the player in 0.19.7 and 0.19.8. Maybe #3920 is related?
Also, could you test if [this apk](https://github.com/TeamNewPipe/NewPipe/files/5168628/app-debug.zip), containing the last development and ui changes, solves your issue by chance? Thank you ;-)

**Comment by opusforlife2** [comment]
Closing until @qu4ntumrush replies.
