### ISSUE TITLE
Sound Cloud kiosks not working

### ISSUE THREAD

**Issue by HieuKQ** [TeamNewPipe/NewPipe#4193]
**Newpipe Version**
0.19.8

**Steps to reproduce the bug**
Select sound cloud service

**Expected behavior**
Kiosk videos load from sound cloud 

**Actual behaviour**
No video has loaded from sound cloud.

**Comment by opusforlife2** [comment]
Search works. Kiosks don't.

**Comment by opusforlife2** [comment]
Closing in favour of #4204 since it contains an error report.
