### ISSUE TITLE
fullscreen mode too small

### ISSUE THREAD

**Issue by chekmanh** [TeamNewPipe/NewPipe#4194]
### Version
- compiled from source (origin/dev) and downloaded from fdroid store

### Steps to reproduce the bug
open video in landscape fullscreen mode. 

### Expected behavior
actual full screen mode. Extending over the camera punchhole. 

### Actual behaviour
the fullscreen mode does not go over the camera punchhole.

### Screenshots/Screen recordings
using fdroid:
![Real](https://user-images.githubusercontent.com/58632831/91390146-993e5380-e839-11ea-9a67-10811ed052fd.jpeg)
Actual fullscreen mode, extending over the camera punch hole.

compiling from source:
![Scam](https://user-images.githubusercontent.com/58632831/91390164-9a6f8080-e839-11ea-8386-06baff1cc4e5.jpeg)
See the black bar on the left??? The camera punch hole is there. But the fullscreen mode does not cover that space.

### Hardware
I'm using the huawei p40 pro

**Comment by Stypox** [comment]
Duplicate of #4040, see #4154
