### ISSUE TITLE
What's new as a home page

### ISSUE THREAD

**Issue by mbnoimi** [TeamNewPipe/NewPipe#4196]
#### Describe the feature you want
I suggest to:
* Add an option for setting "**What's new**" as a home page.
* Add n option to hide/show "**Trending**" tab in the home page

#### How will you/everyone benefit from this feature?
* I use NewPipe basically for my kids's TV Box (Xioami) so I want to keep them follow "**What's new**" easily without the need to expand the side menu for showing "**What's new**".
* "**Trending**" page is very annoying for kids, it shows unneeded content for kids so hiding it would be very useful.
* Personally I use NewPipe in my phone just like my kids I don't care about "**Trending**" I prefer to followup "**What's new**" so adding it to the home page is really practical feature.

**Comment by wb9688** [comment]
Settings -> Content -> Content of main page

**Comment by mbnoimi** [comment]
OOOh silly me. I tried the feature it works just like what I requested but under Android TV (Xiaomi Mi Box S 4K) I'm unable to sort the tabs using the remote control.
My you please guide my how to sort the tabs under Android TV?

![image](https://user-images.githubusercontent.com/284547/91412574-a4ea4400-e852-11ea-89c4-761841311641.png)

**Comment by opusforlife2** [comment]
@mbnoimi #3687 is open for Android TV gesture replacements/workarounds. You can give your suggestions there.

Also... I'm pretty sure we all know what a remote control looks like. 🤭

**Comment by mbnoimi** [comment]
> Also... I'm pretty sure we all know what a remote control looks like. hand_over_mouth

hehehe, I posted the type of the remote control because there are some advanced remote controls works fine with this kind of the issues.
