### ISSUE TITLE
Compatibility on Moto Display

### ISSUE THREAD

**Issue by HellxDo** [TeamNewPipe/NewPipe#4198]
#### Describe the feature you want

Moto Display Is a feature for all Motorola phoned, which is a way to access notifications quick and easy, without opening your phone. there are countless examples of Music Players working with this feature, one of the more popular ones being youtube Music and Spotify, I'll be showing photos of examples down below. I would love to have this feature for new pipe, a simple forward/replay and pause/play buttons being implemented, it would be convenient for us, specially with background music playing 

#### Is your feature request related to a problem? Please describe it

As of now when clicking on the notification of new pipe through Moto Display, we don't see absolutely nothing

#### Additional context

![screen-0.jpg](https://user-images.githubusercontent.com/70299147/91524401-7bbec780-e8d5-11ea-8ed9-a4e097329699.jpg) Moto Display in action.
![Screenshot_20200828-021415.png](https://user-images.githubusercontent.com/70299147/91524425-8f6a2e00-e8d5-11ea-897d-b6b45e76e30c.png) Moto display with a Music player (closed)
![Screenshot_20200828-021424.png](https://user-images.githubusercontent.com/70299147/91524455-a872df00-e8d5-11ea-9fe9-c2b14090cde4.png) by clicking on the notification, you can see a music player now on screen, which you can control freely your audio as you wish.

#### How will you/everyone benefit from this feature?

This feature will not only be more convenient, it will help with battery consuming and time, instead of turning on the phone, simply pick it up and control the background music quick and easy.

**Comment by wb9688** [comment]
Does it work with the APK at the end of #3178?

**Comment by HellxDo** [comment]
> Does it work with the APK at the end of #3178?

What do you mean?

**Comment by HellxDo** [comment]
> Does it work with the APK at the end of #3178?

Oh yeah I think so!

**Comment by Stypox** [comment]
Closing since #3178 will soon be merged and no more issues can be linked
