### ISSUE TITLE
Download doesn't start

### ISSUE THREAD

**Issue by ata2001** [TeamNewPipe/NewPipe#42]
If i try to download for example this video: https://www.youtube.com/watch?v=GZiJQ3bXtfo download manager fails with this error:
09-23 21:37:27.064 I/DownloadManager(13000): Download 40 finished with status FILE_ERROR

**Comment by ata2001** [comment]
I have CM 11 (Android 4.4.4), no gapps, same issue with all versions.

**Comment by theScrabi** [comment]
Hm I was able to download that video. Please tell me your download directory. You can find it in the Settings screen. Its the second preference.

**Comment by ata2001** [comment]
/storage/sdcard0/NewPipe

I tried to change the directory with no luck.

Playing with VLC, and Kodi is fine, but i can't save the most video.

**Comment by theScrabi** [comment]
Try writing a slash between sdcard and 0. Like so: /storage/sdcard/0/NewPipe :)

**Comment by ata2001** [comment]
Why? My sd is mounted to /storage/sdcard0

**Comment by theScrabi** [comment]
Owww.... my fail sry. I got confused with /storage/emulated/0

**Comment by theScrabi** [comment]
Yes i have the similar problems when i want to download something on my external sdcard. This is what my log says:
java.lang.SecurityException: Destination must be on external storage: file:///storage/sdcard0/NewPipe/Two%20Steps%20From%20Hell%20-%20Unforgiven.m4a

**Comment by theScrabi** [comment]
I gues the problem is that /storage/external/0 is your specific "external" user directory. So because /storage/sdcard0 (although it might have the same contend) is beyond that directory the download manager refuses downloading there. Therefor all Android devices with 4.4.0 and later should have trouble downloading to /storage/sdcard0 with NP.
