### ISSUE TITLE
Just use Youtube-dl/FFmpeg directly as a backend and allow us to update them from within the app

### ISSUE THREAD

**Issue by Pentaphon** [TeamNewPipe/NewPipe#4202]
Can somebody explain to me why we aren't just using Youtube-dl/FFMpeg as a backend instead of using the extractor we currently have? Why do we have to keep maintaining a "newpipe extractor" when we can just use youtube-dl/ffmpeg directly and make Newpipe the best Android frontend for those 2 applications?

**Comment by Stypox** [comment]
#2568

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/2415#issuecomment-683421792
