### ISSUE TITLE
Disable Commenter Image from Loading

### ISSUE THREAD

**Issue by Xcelceor** [TeamNewPipe/NewPipe#4205]
Hello Newpipers,

 Is there an easy way to disable the image associated with a commenter? I want them disabled or not to load in in the first place.

Any help would be greatly appreciated!

**Comment by Redirion** [comment]
currently there is no option for this. However it could be added relatively easy.

CommentsMiniInfoItemHolder the ImageLoading path could be excluded and the width of the itemThumbnailView could set to 1 pixel.

**Comment by wb9688** [comment]
@Redirion: Why would you change its width instead of just making it `GONE`?

**Comment by Redirion** [comment]
in list_comments_mini_item.xml and list_comments_item.xml the other layout elements of a single comment entry are aligned right to the thumbnailView. The layout would be messed up if the visibility was just changed to GONE.

**Comment by eladkarako** [comment]
In addition to hiding the container (or maybe just making their opacity 100%), 
you would better save some traffic and avoid downloading the "avatar" image (as I believe those user-images are known as).

https://yt3.ggpht.com/a/AATXAJwGn7pUtGfiXQFYeM5UsY0ysCR9A0dMtaZenoWm=s48-c-k-c0xffffffff-no-rj-mo

https://yt3.ggpht.com/a/AATXAJwGn7pUtGfiXQFYeM5UsY0ysCR9A0dMtaZenoWm=s48-c-k-c0xffffffff-no-rj-mo

I guess a rooted user can also add on his own a rule to his HOSTS file:
<code>0.0.0.0 yt3.ggpht.com</code>.

**Comment by Aditya-Srivastav** [comment]
Hey,
I'm new here and was going through this issue.
This is how it looks like when visibility of the itemThumbnailView is set to **gone**.

<img src="https://user-images.githubusercontent.com/54016427/93568469-d962a300-f9ad-11ea-9554-a001b21bbd7e.png" width="350">

For imageLoader i've set the imageUri to null that way the default image is loaded to the itemThumbnailView .

**Visibility is not set to gone (Just for reference )**

<img src="https://user-images.githubusercontent.com/54016427/93569868-cc46b380-f9af-11ea-9cf1-ee6fc2bbe1dc.png" width="350">



Is it what was to be done ?

**Comment by Stypox** [comment]
@Aditya-Srivastav the first screenshot is the way to go in my opinion, in combination with setting imageUri to null. You could add a little bit of padding on the left though (only when images are disabled), so that it look more polished. Thank you, feel free to open a PR :-D

**Comment by Xcelceor** [comment]
> Hey,
> I'm new here and was going through this issue.
> This is how it looks like when visibility of the itemThumbnailView is set to **gone**.
> 
> <img alt="" width="350" src="https://user-images.githubusercontent.com/54016427/93568469-d962a300-f9ad-11ea-9554-a001b21bbd7e.png">
> 
> For imageLoader i've set the imageUri to null that way the default image is loaded to the itemThumbnailView .
> 
> **Visibility is not set to gone (Just for reference )**
> 
> <img alt="" width="350" src="https://user-images.githubusercontent.com/54016427/93569868-cc46b380-f9af-11ea-9cf1-ee6fc2bbe1dc.png">
> 
> Is it what was to be done ?

Did you ever get this implemented? I have no clue how to compile and build an copy of this in the newest release and it looks like the apk you out out no longer works or load videos. Any help would be greatly appreciated!

**Comment by 4D17Y4** [comment]
Hey @Xcelceor 
I had implemented this and this was merged, you can look at the implementation details on the PRs linked, the last one was squashed and merged with the codebase.
Since then I've lost track of this, so I'm unaware if there was some trouble with the code or this feature was removed altogether.
@Stypox can u confirm this.
Thanks.
