### ISSUE TITLE
update readme: About the use of Youtube API

### ISSUE THREAD

**Issue by qlcom** [TeamNewPipe/NewPipe#4208]
As @TobiGr said in https://github.com/TeamNewPipe/NewPipe/issues/4199#issuecomment-683424370

Oh, we should change the descriptions. We moved away from the old (non-material) YouTube website version, because YouTube announced to disconiue it. We only interact with the API YouTube is using to run the website. There is a session id (don't know how it is called atm) that allows tracking YouTube one session

**Comment by qlcom** [comment]
@TobiGr

**Comment by qlcom** [comment]
Isn't there anyone to update the doc?

**Comment by opusforlife2** [comment]
This question has not been answered yet: https://github.com/TeamNewPipe/NewPipe/issues/4199#issuecomment-683425348

**Comment by qlcom** [comment]
someone please take a look at it.

**Comment by qlcom** [comment]
@Stypox @TobiGr

**Comment by Stypox** [comment]
Is there anything I should do? You could create a PR over at the [docs](https://github.com/TeamNewPipe/documentation) and one at the [website](https://github.com/TeamNewPipe/website) and add what @TobiGr said.

**Comment by qlcom** [comment]
i don't know how  newpipe actually work, so i can't write it.

**Comment by Stypox** [comment]
Neither do I know how the website works ;-)

**Comment by qlcom** [comment]
you misunderstood  what i said. you, the maintainers know how newpipe work. so it should be written by a maintainer.

**Comment by qlcom** [comment]
i can't help this.

**Comment by qlcom** [comment]
20 days, yet no one have done it.
