### ISSUE TITLE
Prevention of Duplicate entries in playlist

### ISSUE THREAD

**Issue by umunais** [TeamNewPipe/NewPipe#4212]
Please add an option to not automatically add a particular video link again and again to a playlist of its already there 

### Version

-

**Comment by wb9688** [comment]
Please fill in the issue template.

**Comment by opusforlife2** [comment]
Before even that, first check if the issue already exists before opening... although in this case it is understandable if you didn't find anything because #4186 doesn't use the word 'duplicate' even once. O.o
