### ISSUE TITLE
Ignore last character in YouTube URL if it ends with a closing parenthesis 

### ISSUE THREAD

**Issue by kirisakow** [TeamNewPipe/NewPipe#4213]
On mobile, I enjoy opening links in NewPipe from web browser. And it works well — unless the URL is enclosed in parentheses of which the closing one is sometimes rendered as part of the URL. 

YouTube itself seems to handle this case by somehow trimming the last “)” character on-the-go. While NewPipe regards such URLs as unsupported (says `"Unsupported URL"` in the front end, and `"No service can handle the url"` in logcat). And I think NewPipe should also be empowered to handle such cases.

To test it empirically, I invite you to open this very page in your favorite **web browser for Android**, and try to **open with NewPipe** each one of the two links below: the first shall work, whereas the second shall not.

1. [https://www.youtube.com/watch?v=mBuoZY7kAlg](https://www.youtube.com/watch?v=mBuoZY7kAlg)
2. [https://www.youtube.com/watch?v=mBuoZY7kAlg)](https://www.youtube.com/watch?v=mBuoZY7kAlg%29)

You can watch me reproduce the issue with my Android device in Firefox for Android web browser:

https://youtu.be/bZP0jtp9WrQ

**Comment by kirisakow** [comment]
Sorry guys, it won't build after my commit. Even though I updated the test class too.

**Comment by starboi02** [comment]
Can I work on this issue?

**Comment by opusforlife2** [comment]
As you can see above, there is already a PR in the works to fix this issue. :)
