### ISSUE TITLE
Settings option to change default playback to background play

### ISSUE THREAD

**Issue by wreuven** [TeamNewPipe/NewPipe#4218]
I have an Android tablet on my wall for the sole purpose of playing music from YouTube.

The problem is that everytime I walk into the living room, one of my kids is using this device to watch youtube video.

To avoid this, I set the screen timeout to 15 seconds so it is not comfortable to use for video playback, but that only works if playback is done in background mode.

So I'd like to change settings so that all playback is done in the background.

**Comment by opusforlife2** [comment]
Can this not be solved by using a lockscreen password?

**Comment by Stypox** [comment]
Yeah, I think this change is a little bit out of context for NewPipe
