### ISSUE TITLE
UI FR: Add Icons to the "Play as" - Popup menu

### ISSUE THREAD

**Issue by paskalito** [TeamNewPipe/NewPipe#4221]
#### Describe the feature you want

I would like to have icons on the "Play as" - Popup menu.
I really love the modularity of NewPipe and therefore also the option on how to play something, but as there are many options i always struggle a bit to find the one i want.
I feel that adding graphical symbols to the options (as well as maybe sort them in a specific way) would improve that situation/experience greatly.

![Screenshot_20200903-160159](https://user-images.githubusercontent.com/8012793/92127573-bce93700-ee01-11ea-851b-ffede7e30af4.png)

#### Is your feature request related to a problem? Please describe it

its related to not ideal usability as you are confornted with ~5 Options to play something al just described as text.

#### Additional context

I think this is also applicable if you open a newpipe compatible link from outside the app. ( as you have the same/similair options) < where it is already implemented as i just saw. (maybe there is space for the "add to queue icon (see below))

#### How will you/everyone benefit from this feature?

it will greatly lower the amount of thought you need to decide on how to play something, and will therefore free up brainspace for more important thoughts and improve the amazing usability of newpipe even further.

#### Implementation thoughts

I think for most parts we should use the icons that are already present here

![Screenshot_20200903-160153](https://user-images.githubusercontent.com/8012793/92128674-e9518300-ee02-11ea-832c-e6e3ba35c1f5.png)

also i suggest to add an icon for "add to queue." (maybe a ... or some sort of arrow) so:  "add to popup queue" would be the popoup symbol followed by the queue symbol.

**Comment by Stypox** [comment]
Check #2583
