### ISSUE TITLE
KWGT don't show tracks with NewPipe in background mode

### ISSUE THREAD

**Issue by x70b1** [TeamNewPipe/NewPipe#4225]
### Version
- the latest 0.19.8

### Steps to reproduce the bug
1. play a single track/video in `background` mode
2. take a look at KWGT

### Expected behavior

KWGT should show the current track if NewPipe runs in background mode.

### Actual behaviour

KWGT have a function to display the current playing track and other information related to a music player. I dont know much about Androids internals. But I assume that there is something like a defined protocol or something so share this information between apps.

KWGT works with other player apps and shows a track. It even works with NewPipe in `popup` mode for a single track. It works if I play a playlist in `background` mode. But it works not if it plays a single track in background mode.

This has worked before. That was a long time ago. Maybe months or a year. But I never reported it.
My guess is that there is something wrong with the music information publishing.

**Comment by opusforlife2** [comment]
Please test the apk in #3178.

**Comment by x70b1** [comment]
I have tested the APK. Now all information has disappeared. That makes it worse than better.

**Comment by Stypox** [comment]
@x70b1 could you test [**this apk**](https://github.com/TeamNewPipe/NewPipe/files/5190780/app-debug.zip) (taken from #3178)? I just installed KWGT on my phone and added "MusicMicro - Mini music info" from "Base Pack - Kustom Industries", and it works as expected: info is shown for playlists, single tracks, popup, etc.

**Comment by x70b1** [comment]
@Stypox Thx a lot for your work here!
I tested the apk and it looks good now.

**Comment by opusforlife2** [comment]
Alright. Closing this as it can't be linked to the PR (which is already at 10 linked issues).
