### ISSUE TITLE
Already downloaded videos should play locally (not redownload/stream)

### ISSUE THREAD

**Issue by voltcraft1** [TeamNewPipe/NewPipe#4227]
#### All previously downloaded videos should not be redownloaded.

1. Search for something
2. Download video
3. close/swipe away newpipe from Android/tasks
4. Open newpipe
5. Go to Downloads
6. Press the 'three-vertical-dots' -> Show Info
7. Play
8. Currently newpipe re-downloads video while playing 

I verified (8) by looking at network transmission and enabling aeroplane mode

#### Is your feature request related to a problem? Please describe it

It is some how related to this [697] but different. 
https://github.com/TeamNewPipe/NewPipe/issues/697

#### How will you/everyone benefit from this feature?

Bandwidth.. especially everyone --- including service providers :-)

**Comment by opusforlife2** [comment]
Always check for duplicates before opening. #478.

**Comment by voltcraft1** [comment]
> Always check for duplicates before opening. #478.

Sorry for that.

At the same time, I am **not** asking for NewPipe to be a replacement to VLC/or all videos inside phone (as in #478). 

My suggestion is if I watched and downloaded a video inside NewPipe. If I again even search and find the same video, it should locally play - from checking the downloads folder.

*Only* videos that were downloaded in NewPipe should not be redownloaded. 

Hope I made it clearer. And I think  #478 is a 'total' complete solution but I am not suggesting that. 

Thank you for considering my comment.

**Comment by opusforlife2** [comment]
I know what you mean. I want this feature too. The thing is, the functionality that has to be added is the same from a coding perspective. File URIs/Content URIs have to be stored in a table along with the corresponding video URLs. So it's better that you add your thoughts in a comment on that issue. It will anyway be discussed and debated whenever it is implemented.
