### ISSUE TITLE
yet another "turn off internet connectivity get unexpected results" issue

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4229]
### Version

-0.19.8

### Steps to reproduce the bug

1. turn off internet
2. go to history (you should have some for the issue to occur)
3. long press the first video on the list and start playing in the background
4. wait a few seconds and try closing it from the notification bar
5. god luck trying to close it ?

### Expected behavior

should be closed normally without any issues
### Actual behaviour

stuck in the notification bar even after the internet is back

**Comment by opusforlife2** [comment]
> god luck trying to close it ?

Closes just fine. This too, could be a custom ROM issue. Which one is it?

**Comment by panacist** [comment]
@opusforlife2 yes using a custom rom the RR-os

**Comment by opusforlife2** [comment]
Which Android version? If it is 9+, then you might have to wait for a few seconds for the notification to close, even though it looks like nothing's happening.

**Comment by panacist** [comment]
@opusforlife2 it's android 7 and if you mean the rr-os version i think it's 5.8 and i have waited for more than one hour and nothing happens the only solution is to force the app to close.
btw enqueue in the background works fine and closes fine ! only playin in the background causes the issue

**Comment by avently** [comment]
@panacist 
>god luck trying to close it ?

Thank you for the luck! It helped me to close the notification without problems on android 9 (background and popup players). 
Maybe without the luck it works too, didn't checked without the luck.:)

**Comment by opusforlife2** [comment]
Try the same solution here, @panacist. A buggy build of your ROM could be the problem.

**Comment by panacist** [comment]
@avently @opusforlife2 thanks guys for your responses (and avently's sense of humour) i think you are right it's due to the custom ROM i'll try rebuilding it ! feel free to close this issue .

**Comment by avently** [comment]
@panacist you can close it yourself when you be sure that the problem in custom rom. Otherwise post a crash report here

**Comment by opusforlife2** [comment]
@panacist Don't leave us hanging. :P Did changing the ROM fix it?

**Comment by panacist** [comment]
@opusforlife2 sorry was a busy day yesterday but i've tested the app on a stockrom and it closes fine so i assume it's just my buggy custom ROM

**Comment by opusforlife2** [comment]
Thanks for confirming.
