### ISSUE TITLE
[unified player] everything crashes after playing a video on fullscreen

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4230]
### Version

-latest apk provided by B0pol

### Steps to reproduce the bug
1. Go to any video 
2. play on fullscreen
3. voice keeps playing for a while and the video stops 
4. now every video on my phone can't be played for some reason

### Expected behavior

should be playing normally as it does for the latest newpipe version
### Actual behaviour

the app crashes and after forcing it to stop i no longer can play any video on my phone even from gallery  [it may be something with my phone custom rom (RR Nougat) but it never happened this is the first time].
to fix the issue i just restart the phone

**Comment by Kukulkan2019** [comment]
No audio or video play back of any selected item, sent crash report via gmail, restarting device doesn't help.

**Comment by avently** [comment]
Looks like you got a crash of your codecs. That's why you can't play any video. I don't think it's related to the unified player but to your custom OS. 
And are you really think that with your steps to reproduce anyone can reproduce it? I mean, it's working fine for everyone because everyone uses fullscreen videos and could meet the crash already. So if you want help, try to isolate a problem and to give a really reproducible instructions. 

> No audio or video play back of any selected item, sent crash report via gmail

We have no access to mailbox you sent email to. Show the crash here

**Comment by wb9688** [comment]
@avently: Crash reports get imported into sentry.schabi.org (which I think you don't have access to), though there are a lot of incorrectly formatted e-mails (e.g. Gmail likes to insert line breaks and e.g. Outlook likes to add something like "Download Outlook for Android", which causes the JSON to be invalid) that won't be imported successfully. But even if it gets imported successfully, we can't know what crash report was sent by who (for privacy reasons), so we still don't know what crash report he refers to.

@panacist: A logcat would also be useful.

**Comment by opusforlife2** [comment]
Ah. Interesting. Try flashing a different build of your ROM, @panacist. Maybe that particular build has a bug.

@Kukulkan2019 Do you also have a custom ROM? You haven't given any details.

**Comment by Kukulkan2019** [comment]
No 'steps to reproduce it' the app isn't working and has obviously been sabotaged as happens about every month, crash reports are sent from the app itself, routine, I have no custom ROM...I haven't given any details because I sent several crash reports from the app itself, the only details are that the app isn't working just as in previous problems about a month ago. P.S. I just tried taking a screenshot of the crash report from new pipe but won't upload here due to 'low memory' even though my device has plenty of memory.

**Comment by avently** [comment]
@Kukulkan2019 you don't need a screenshot, you can just copy a text from crash report window and paste it here.

If the app is not working, I.e. you have crashes, it's not a problem to make a crash again and to send it's text here

**Comment by Kukulkan2019** [comment]
I sent the crash report via gmail like it says in the app that's all I can do, the app isn't working, it's not playing any video nor audio and I imagine that you'll get a lot more feedback about it.

**Comment by avently** [comment]
@Kukulkan2019 
"App is not working, I sent crash reports, I don't want to attach crash reports here". Ok, cool, you can continue to not do anything which devs asks  and finally receive no result.

**Comment by opusforlife2** [comment]
@Kukulkan2019 

https://user-images.githubusercontent.com/17365767/81796016-24a30b80-950d-11ea-9b0d-a263b1932f53.png

See the bottom two buttons? Copy using that button, and paste the report here.

**Comment by panacist** [comment]
@opusforlife2 @avently @wb9688 yeah mine is probably due to the custom ROM and how it deals with codecs, same thing happens on replicant os whenever i play a video using the mpeg4 encoding

**Comment by avently** [comment]
@opusforlife2 so now you can attach screenshots, interesting:)

I mean you can select a text by long tapping on it, then press copy. Or attach screenshot from the start.
GaiException is a network problem, just for the info

**Comment by opusforlife2** [comment]
I lifted that from the PR that implemented those two buttons. 🤭

**Comment by Kukulkan2019** [comment]
I sent the crash reports, instead of insulting users, fix your app, this thing crashes or malfunctions on a routine basis about once a month like clockwork

**Comment by avently** [comment]
@Kukulkan2019 just read it https://github.com/TeamNewPipe/NewPipe/issues/4230#issuecomment-687613609
And try to attach crash reports here.

**Comment by opusforlife2** [comment]
> But even if it gets imported successfully, we can't know what crash report was sent by who (for privacy reasons), so we still don't know what crash report he refers to.

Did you read this? Your gmail crash reports will **not help**, which is why we're asking for the crash report _here._ I've given you a method to do it with an accompanying screenshot. Please do so.

@avently There's no need to be rude. If you get annoyed by something let someone else handle it.

**Comment by Kukulkan2019** [comment]
I already tried to attach crash reports here, low memory on your end, I
also just uninstalled/reinstalled, still not working...




Brennan Mulrennan end message...🦎

**Comment by Kukulkan2019** [comment]
Yeah, I I read it opusforlife or whatever your name is, your blocked...

**Comment by avently** [comment]
@opusforlife2 
>There's no need to be rude. If you get annoyed by something let someone else handle it.

Where I was rude?

**Comment by opusforlife2** [comment]
This https://github.com/TeamNewPipe/NewPipe/issues/4230#issuecomment-687623691 wasn't called for.

**Comment by Kukulkan2019** [comment]
Fix your app, I'm just reporting a malfunction, you're blocked...

Brennan Mulrennan end message...🦎

**Comment by panacist** [comment]
@avently not rude but more like impatient and thinks like everyone should be familiar with the app i mean cool it down man  and everything is gonna be alright :) !!
@Kukulkan2019 please be a bit understanding those guys aren't getting paid to serve ya or me so with just a bit of clarifications and help from your side they can fix it !

**Comment by Kukulkan2019** [comment]
Thanks, I'm just an Android user, not a programmer, these malfunctions are happening on a routine basis, okay, no custom is or ROM, just a standard Android tablet, the same ROM, is, etc., that I'm using when your app is working or not working, which is about once a month...🦎

**Comment by Kukulkan2019** [comment]
If they're not getting paid then maybe you should hire some professionals
and the app might not crash routinely, like once a month for about the past
year since I've been using it.



Brennan Mulrennan end message...🦎

**Comment by avently** [comment]
It looks like a comedy show.
@panacist let us know if you have the same problems on another phone or stock-like OS.

I always use custom ROMs and know that problems with codecs happens often. So you just need to find a normal rom to be sure that the problem is with NewPipe.

**Comment by Kukulkan2019** [comment]
I thought you were the Jedhi knights of open source... You have thousands of issues, I have other open source apps going back to early Android with only one or two issues if that...the app is malfunctioning, I have only one device, Android 9, all my other apps are working flawlessly, I hope that you can fix your app...🦎

**Comment by panacist** [comment]
@avently sure and i'll also test the app on replicant os but due to it's lack of any proprietary blobs i ain't sure enough wether the app will even function.
@Kukulkan2019  usually whenever i encounter a problem with the app i do this: 
-make sure i am running the latest version
-look for any errors showing up on the screen
-clear data and cache and see if things can go back to normal
-check github issues to see if i have similar issue
-otherwise i open an issue and with plain simple english i try to describe the issue and how it happens usually in steps and include the error crash report (if any is avaible)
-and just wait for someone to notice the issue you know 
please don't be angry and showing that on comments it won't do ya no good.
just because none can respond to your issue the way you want they are ignoring you. no they are usually trying to figure out what you mean so yeah and just because you are taking from your time to comment on this issue means you like the app and wants the best for it that's how i see it.

**Comment by Kukulkan2019** [comment]
It's not my issue, your app is malfunctioning again, okay, I'm not even the author of this thing...it's the latest version, 0.19.8...oh, it's a big consumption of my time, as other users I'm sure,  again, I sent the crash reports via gmail like it says in the app, if that function doesn't work, then why have it (rhetorical) I hope that you can fix your app, otherwise, there is no point in any further communication...🦎

**Comment by opusforlife2** [comment]
> I already tried to attach crash reports here, low memory on your end, I
also just uninstalled/reinstalled, still not working...

When do you get this error? When you tap on "Copy formatted report" from the screenshot I posted? Or when you tap "Report error on Github"? Or when you use the Share button at the top right?

**Comment by theScrabi** [comment]
@avently please be a bit more patient and calm. Please use "please" a bit more often. Some users might not know how things work. If you are patient and nice you will see they will be patient and nice with you to.

@Kukulkan2019 this is a community development. We don't get commercially yet we do the best we can. Please be aware that sometimes things might not work perfectly. However you are always welcome to support us either financially or by helping us getting rid of erros. Making NewPipe work is a task that involves all of us. You are currently not helping by blaming people. Either you communicate friendly and cooperative with us or you leave this discussion. I am willing to report you if this will not work one or another way!

**Comment by Kukulkan2019** [comment]
You can block my legitimate responses all you want, your app isn't working...its not my fault your app isn't working, and there is nothing 'disruptive' about my comments reporting an issue about your app malfunctioning, again, in response to that individual's unwarranted responses...Again, you have Thousands of issues, fix your app, and stop insulting users, or we will respond in kind...

**Comment by opusforlife2** [comment]
If you'll notice, the "unwarranted response" was minimized as well. Can you answer these https://github.com/TeamNewPipe/NewPipe/issues/4230#issuecomment-687634820 questions instead of complaining?

**Comment by avently** [comment]
@theScrabi 
> please be a bit more patient and calm. Please use "please" a bit more often

I don't want to do something that I think is incorrect. You know, even if you written `please` multiple times it didn't stop that user to answer to you as he answered after your comment. Just read his message and you'll understand what i'm talking about. 
`please` costs nothing most of the time. But what actually matters is an explanation. If the explanation didn't help, I don't care about the guy who ignores my explanation.

>If you are patient and nice you will see they will be patient and nice with you to.

Most of the people in this issue were patient and nice and you see the result. So I can say that your thought is not always correct. That's why we should be flexible instead of kind. 

> Either you communicate friendly and cooperative with us or you leave this discussion. I am willing to report you if this will not work one or another way!

It's not a kind words but it's the right way to talk in the situation with this person.

I think we understand each other.

**Comment by Kukulkan2019** [comment]
Fix your app, it's not working, it's not about me or any other user, we will leave our reviews.

**Comment by Kukulkan2019** [comment]
> If you'll notice, the "unwarranted response" was minimized as well. Can you answer these [#4230 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/4230#issuecomment-687634820) questions instead of complaining?

Yes, fix your app and stop insulting users.

**Comment by Kukulkan2019** [comment]
> > I already tried to attach crash reports here, low memory on your end, I
> > also just uninstalled/reinstalled, still not working...
> 
> When do you get this error? When you tap on "Copy formatted report" from the screenshot I posted? Or when you tap "Report error on Github"? Or when you use the Share button at the top right?

I already told you, I always get the error, I'm done with you.

**Comment by opusforlife2** [comment]
> 
> 
> > > I already tried to attach crash reports here, low memory on your end, I
> > > also just uninstalled/reinstalled, still not working...
> > 
> > 
> > When do you get this error? When you tap on "Copy formatted report" from the screenshot I posted? Or when you tap "Report error on Github"? Or when you use the Share button at the top right?
> 
> I already told you, I always get the error, I'm done with you.

I gave you 3 options and you gave an ambiguous answer in return. If you're not going to be helpful, why are you here at all? Why even bother replying?

**Comment by panacist** [comment]
@opusforlife2 @avently i've tested the app using 4 different ROMs 2 of them are stockroms and two are custom roms and here are the results :
replicant os: everything crashes right after pressing on any video (doesn't happen with the current version).
RR os: crashes after tapping on the fullscreen icon.
android 5 (stockROM) : plays welll with a bit of gliching (not in a smooth way) before the video starts i bet it's due to  playing the video on the notifications !! + when pressing the fullscreen icon a black screen is shown for a second or two while sound keeps playing.
android  4.4 (stockROM): same as android 5.
(a bad expirence is expected with low memory phones so if you have one please try it out yourself ! also i've spotted a few erros i'm going to open a new issue for them)

**Comment by avently** [comment]
@panacist can you just send a crashreport?

**Comment by panacist** [comment]
@avently when i said the app crashes i mean it literally crashes haha so no crash report is available ?

**Comment by panacist** [comment]
@avently it even forced my phone to restart on replicant os so dunno how am i supposed to get a crash report hmmm

**Comment by opusforlife2** [comment]
That's very odd. Even if the app crashes badly enough to take you to the home screen, it opens up the Error report activity right after.

**Comment by panacist** [comment]
@avently sure thing i just didn't know a logcat would be helpful in that case but yeah gimme a few minutes

**Comment by panacist** [comment]
@avently @opusforlife2 here are the logs (keep in mind i did put logcat in debug mode(or method) ) :
[logs.zip](https://github.com/TeamNewPipe/NewPipe/files/5183771/logs.zip)

**Comment by avently** [comment]
What's that? It's not a logs. Are you exceprience problems in reading logs? It's easy and the guy who can change OS can easily make logs. Try one more time. Just connect to a PC, run terminal, enter `adb logcat` and make the app crashed then copy output from terminal window. Text should be there. 

> keep in mind i did put logcat in debug mode

If you mean you tried to get logs in recovery mode it will not help. You need to attach the phone to PC while the phone is working. Make sure you have enabled adb debugging in developer settings. If you will not send a real logs, I'll be unable to help.

**Comment by opusforlife2** [comment]
No need to copy the text from terminal either, just do `adb logcat > logcat.txt` and it'll create the file automatically, which you can edit at your convenience.

Also,
> user: god, group: god

Amazing. xD

**Comment by panacist** [comment]
@avently @opusforlife2  here's what i did in details :
connect my phone to the computer and wrote in terminal:
adb logcat org.schabi.newpipe.debug:D >> logcat.txt
tried to reproduce the crash after that i ctrl+c 
is there something other than this am unaware of ???

**Comment by panacist** [comment]
ah and i zipped the file using the tar command

**Comment by panacist** [comment]
oh my bad guys i think the file got curropted somehow hahah i just took a look at it now

**Comment by opusforlife2** [comment]
Tar doesn't compress the file. It just creates a single file out of multiple ones. If you just renamed the file  to zip after creating a tar, that could explain the issue. Use 7z to compress it to zip directly. Don't tar.

**Comment by panacist** [comment]
@opusforlife2 yeah that's the issue instead of naming the output file logs.tar i did name it logs.zip and @avently is so mad at me hahah

**Comment by avently** [comment]
> @avently is so mad at me hahah

Nope, I just want to find the reason of such mysteriuos crash. So where it the right archive? Simply renaming to tar didn't help

**Comment by opusforlife2** [comment]
He needs to upload a new one. I think Github messed it up in transition because of the incorrect file extension.

**Comment by opusforlife2** [comment]
> and avently is so mad at me hahah

That's because he cares about users very much. It's out of love.

**Comment by panacist** [comment]
@avently @opusforlife2 here are they :
[fuckinglogs.zip](https://github.com/TeamNewPipe/NewPipe/files/5183949/fuckinglogs.zip)

**Comment by opusforlife2** [comment]
Yup. Those are logs indeed.

**Comment by panacist** [comment]
@opusforlife2 
> Tar doesn't compress the file. Use 7z to compress it to zip directly. Don't tar.

i tar all the time and tar does compress files use cvf flags ;)
> That's because he cares about users very much. It's out of love.

yeah i know but he should be a bit patient for errors occur from time to time

**Comment by opusforlife2** [comment]
He has a sarcastic sense of humour, it just tends not to come across well on the Internet. I enjoy it, though. xD

> i tar all the time and tar does compress files use cvf flags ;)

Never knew that was possible.

**Comment by avently** [comment]
Make a screenrecord. 
Just don't understand where the app freezes. Looks like ANR happens but the problem with ANR that you never know what happens and where the app stays in a loop.

**Comment by panacist** [comment]
@avently i can tell you exactly where the app freezes because making a screenrecord isn't an available option (again proprieatry firmware/software issues) :
the app works fine before pressing the full screen icon
after pressing it phone rotates screen the audio keeps playing on the background while the video freezes
trying to go back to normal view will do nothing new audio keeps playing and so on and so on
i stop the video from playing go back to main page and the app freezes entirely 
a few seconds later the system pops up a force to close dialogue 
(on replicant os none of that happen hahah and don't be mad)

**Comment by avently** [comment]
Is there any difference if instead of pressing on fullscreen button you just enable global autorotation and rotate the phone manually into landscape orientation?

**Comment by avently** [comment]
2.) Also what if you rotate your phone in landscape before even entering to NewPipe, then launch the app, play any video. Is it playing ok? If yes, what if you change orientation without button to partrait? What do you see?

**Comment by panacist** [comment]
@avently playing video while on landscape view right from the start didn't cause any problem and if i try to rotate the phone again audio keeps on the background and so on and so on
problem happens right after i rotate !
(doesn't happen on the current newpipe version tho)

**Comment by avently** [comment]
3) Also please follow instructions from here: https://developer.android.com/topic/performance/vitals/anr#pull_a_traces_file  and upload here traces file that create right after you trigger a crash. It may help finding the cause of ANR,

You can even with root file manager go to /data/anr/ and copy the latest file here

**Comment by panacist** [comment]
@avently note that rotating the video on a stockrom without pressing the fullscreen icon is smoother and doesn't cause the 2s blank screen to occur.
and sure give me till tomorrow i have to go to work now !

**Comment by avently** [comment]
@panacist please, upload the file now. I'll probably will not help you later because of lack of time.

**Comment by panacist** [comment]
@avently here is the file:
[traces.txt](https://github.com/TeamNewPipe/NewPipe/files/5184276/traces.txt)

**Comment by panacist** [comment]
i got rid of the build fingerprint tho :)

**Comment by avently** [comment]
[1.zip](https://github.com/TeamNewPipe/NewPipe/files/5184279/1.zip)

Could you test this APK? It's unrealated to trace file you sent, just want to make sure that it's the problem is not caused by one piece of code.

About traces: 

In traces I can clearly see that ANR happens because SimpleExoPlayer can't release itself for unknown reason. And more importantly that it tries to release itself on the response of CLOSE event that only happens after pressing on close button in notification. I don't get how it's possible if you didn't press on close button?

**Comment by panacist** [comment]
@avently none of the apks you provided are working both of em are corrupted and regarding the close event i believe i've pressed the close button in the notifications in an attempt to get rid of the player because it stucks there even after killing the app from recent apps.
but look if you are 100% sure it's just a problem with my weird ROMs it's fine i can deal with it myself and thank you for your hardwork again much love!

one last note: man just don't let the player run on the notifications when people are actually watching a video somehow i feel it takes a relevant amount of ram and cpu that's why the app doesn't run smoothly on old phones (i've tested it on a new phone and it does run super great tho no issues). test it yourself and give me a feedback on it please.

**Comment by avently** [comment]
> none of the apks you provided are working both of em are corrupted

By corrupted you mean the app still freezes?

If so, launch currently testing apk from b0pol (not these two I sent), disable autoplay in settings, enable global autorotation, relaunch the app, open any video without playing it, rotate the phone into different screen orientation. Will the app freezes? I want to know if the freeze is related to player or not. Without playing the video the player will not be started too.

Also, please, make a screenrecord somehow (with reproducing of the bug, not with experiment above). Maybe I will see something interesting. And send /data/traces file once you catch the freeze but don't press on close button. Just wait when the system shows a freeze window and force close the app. I just need to receive a real file with a real cause of the freeze (not the close button like in your previous comments).

> but look if you are 100% sure it's just a problem with my weird ROMs

I can't be sure before finding a reason

**Comment by panacist** [comment]
@avently i meant the apks themselve are corrupted (can't be installed)

**Comment by opusforlife2** [comment]
"Can't be installed" can be due to other reasons, like if you already have an apk with the same package name installed.

> making a screenrecord isn't an available option 

You seem to have multiple phones. Make a video directly?

**Comment by panacist** [comment]
@avently 
@avently doing your lil expirement didn't cause any problems 
@opusforlife2 nope if i had an app with similar package name i would have a message on the screen like "conflicting packages issue" or of that sort not the package appears to be corrupted.
and yeah that's what i am going to do make a video directly .

**Comment by opusforlife2** [comment]
I just checked 1.zip. It isn't installing for me either, @avently. I get "App not installed".

**Comment by avently** [comment]
[1-new.zip](https://github.com/TeamNewPipe/NewPipe/files/5190139/1-new.zip)
[2-new.zip](https://github.com/TeamNewPipe/NewPipe/files/5190124/2-new.zip)

New apks same instruction, should be installed fine

**Comment by avently** [comment]
@panacist will you do the testing today or I just waiting without reason?

**Comment by opusforlife2** [comment]
He went to work around the same time yesterday so I'm guessing tomorrow.

**Comment by panacist** [comment]
@avently @opusforlife2 thank you guys for your patience and everything i've tested both of the apks you provided and nothing new same old stuff!
but i've investigated the matter further and i found out something helpful .
the crash happens on both RR os and replicant os only when using mpeg4 i tried using webm for both audio and video and surprisingly the crash didnt occur so i assume this is all related to the encoding algorithm in use but i'll make a video showing the crash now so you can make sure avently +reallly thank you again and opus as well  !
(sorry about yesterday i really had to go you know life responsabilities)

**Comment by avently** [comment]
@panacist but you said you don't have such problems with current release, don't you? Does both versions (release and dev) use the same mp4 format?

**Comment by panacist** [comment]
@avently yeah current version plays mpeg4 without any issues (RR os not replicant os) as far as i know i've been using it for years now

**Comment by panacist** [comment]
@avently here's the video showing the crash (sorry for the quality and my fimiling skills):
[output.zip](https://github.com/TeamNewPipe/NewPipe/files/5197189/output.zip)

**Comment by avently** [comment]
Yep, you were right, it doesn't help. But /data/traces may help since the app is actually freezing.

> And send /data/traces file once you catch the freeze but don't press on close button. Just wait when the system shows a freeze window and force close the app. I just need to receive a real file with a real cause of the freeze (not the close button like in your previous comments).

**Comment by avently** [comment]
@panacist  do you have a time today? I can send multiple APKs with some changes. We can try to isolate the problem until we find a line of code that ruins everything.

**Comment by panacist** [comment]
@avently am i supposed to send ya the traces file again ? and if so then i think this may take a while for without trying to close the app from the notifications it takes awhile to appear i mean the freeze window as you call it.
but look as i said long time ago if it is a ROM issue then its fine we can close this looong issue and invest your time on something more valuable now i think after sending ya that video it should be clear to you whether we should investigate the matter further or not .
one thing i really hate is to waste other people's time.

**Comment by panacist** [comment]
> @panacist do you have a time today? I can send multiple APKs with some changes. We can try to isolate the problem until we find a line of code that ruins everything.

only about 30 min but yeah you can send you apks i may test them at any given moment and give you feedback and thank you a lot man !!

**Comment by avently** [comment]
ok, let's be fast
[3.zip](https://github.com/TeamNewPipe/NewPipe/files/5197364/3.zip)

**Comment by panacist** [comment]
@avently let's be fast
my tor setup : hold my network !

**Comment by avently** [comment]
[4.zip](https://github.com/TeamNewPipe/NewPipe/files/5197421/4.zip)

**Comment by avently** [comment]
Disabled everything in onPause, onStop, onResume

[5.zip](https://github.com/TeamNewPipe/NewPipe/files/5197448/5.zip)

**Comment by panacist** [comment]
@avently keep in mind that everytime i test an apk i have to restart my phone (which is encrypted and have to provide the password every time i do so ) so testing all of these apks should take me a long delay so don't get bored haha

**Comment by avently** [comment]
Than start from the 5, to 4, etc. If 5 will not work non will work

**Comment by opusforlife2** [comment]
Less time talking, more time testing! Chop chop!

**Comment by avently** [comment]
Like 5 but without OnDestroy too. (no content observers, broadcast receivers, nothing)
[6.zip](https://github.com/TeamNewPipe/NewPipe/files/5197510/6.zip)

**Comment by panacist** [comment]
@avently
5 doesn't work it freezes the app once i click on the fullscreen icon and the funny thing is that it doesn't play video on fullscreen it just rotates the screen haha
4 same old things 
3 my phone is restarting to test it 

and i will certainly be late at work so i will try to test the 6 apk when i come late at night i dunno if you will be around or not

**Comment by panacist** [comment]
and once again thank you !!!!!

**Comment by avently** [comment]
Man, that's strange. I literally commened almost every piece of code that works between rotations. 

>and the funny thing is that it doesn't play video on fullscreen it just rotates the screen

That's ok. The main thing is to find what makes the freeze happening.

All in 6 + No saveCurrentAndRestoreDefaultBrightness, no setup brightness, no save/restore instance state, no fragment listener
[7.zip](https://github.com/TeamNewPipe/NewPipe/files/5197643/7.zip)

Actually I'm not sure what else I can remove. If non of the apks works, just send traces. Out of ideas without them.

**Comment by opusforlife2** [comment]
What happens when he presses the back button, though? The rotation part will be the same, but the video should pause. Whether that happens or not might give more insight, no?

**Comment by avently** [comment]
> Whether that happens or not might give more insight, no?

No. In apks I sent the video already pauses but it doesn't help

**Comment by panacist** [comment]
@avently @opusforlife2 okay good news the 7 apk didn't  cause the app to crash but when rotating the screen (autorotate enabled) a black screen on the video show up for 1 to 2 seconds before it starts playing(i suspect its due to proccessing power constraints haha) .
but two things : 
first i don't think it is a codec issue but rather a format container issue because technically speaking i guess we can wrap any codec around any format without any problems.
second thing, if i can find you a free software that uses exoplayer and works fine should this be helpful to you to find the causes of this crash ?

and regarding the anr i think it is unlikley to happen if i don't press the screen Continuously in a response to the app being frozen so just waiting for that to pop up is kinda absurd.

**Comment by avently** [comment]
@panacist what about 6 apk?

**Comment by panacist** [comment]
@avently oops didn't test it wait a second please!

**Comment by avently** [comment]
actually 1 and 2 apks have the same code difference as 6 vs 7

**Comment by panacist** [comment]
weird i will retest 2 and see again but 7 did actually play video

**Comment by panacist** [comment]
@avently working!! sorry i think it was a human mistake from my side,
but yeah working although i have to click play everytime i rotate the screen

**Comment by panacist** [comment]
@avently have you thought about the possibility that the player on the notifications is the problem try to get rid of it and see!? hahaha

**Comment by avently** [comment]
> working!! sorry i think it was a human mistake from my side,

Man, please, test better next time. Two days just gone for nothing. Glad that I found the cause. Will post apk with actual fix.

> although i have to click play everytime i rotate the screen

It will not be like that, just for quick testing

**Comment by panacist** [comment]
@avently sorry didn't mean to so what was the issue? not the codecs right?

**Comment by panacist** [comment]
@avently was going to forget thank you man !

**Comment by avently** [comment]
Of course not. If you have a working video in portrate, then nothing should stop you from viewing the same video in landscape:)
The problem is I saved into `saveInstanceState` the whole playQueue but KitKat have less space allowed for such data. On emulator it works fine but on some devices probably the allowed payload size is smaller and cause such behaviour. Fix is pretty simple so

**Comment by avently** [comment]
Also you may noticed that the problem with progress indicator is fixed too

**Comment by avently** [comment]
Right now I need to update my app in Google Play, after a couple of hours I upload apk with a fix here and maybe make a PR.

**Comment by panacist** [comment]
@avently yesterday i was listening to "stuck in the middle with you" while trying to fix the issue and thinking man we will never fix it, btw the chorus of the song goes something like this :
" clowns to the left of me (RR os )
   jokers to the right (replicant os ) 
   here i am stuck in the middle with you avently ahahah "
i recommend you listen to it too it's something from the 70's (back before the industry got sexualized and music bastardized).
@opusforlife2 thank you too for your help!

**Comment by avently** [comment]
Check this one. Is it work ok for you?

[without-freeze.zip](https://github.com/TeamNewPipe/NewPipe/files/5204357/without-freeze.zip)

P.S. comment number 100. Too much for one issue:)

**Comment by avently** [comment]
see #4272
