### ISSUE TITLE
[unified player] please don't play video on the notification bar

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4231]
#### Describe the feature you want

i think when playing a video it shouldn't be played on the notification bar as well [except if i choose to play it in the background] just as in every other video streaming app and just as it actually does on the latest version of the app

#### Is your feature request related to a problem? Please describe it
i don't know ?

#### Additional context

nothing.

#### How will you/everyone benefit from this feature?
simplicity ? i can't see why would anyone want the video to be played on the background while they are watching it

**Comment by opusforlife2** [comment]
The players are unified. The notification is additionally shown for the main player, that's the only change. The reason is so that the stream can be kept open when you close one player and open another.

**Comment by panacist** [comment]
@opusforlife2 thanks for the clarfication! but do you really think it's a good thing to have?
i mean i've never seen such a behavior on any other video streaming app so i dunno man

**Comment by opusforlife2** [comment]
Other apps generally don't have popup and background players in addition to a main player, where you can _switch between them_ seamlessly.

**Comment by panacist** [comment]
@opusforlife2 such a great argument this is i'm convinced!!

**Comment by opusforlife2** [comment]
✌️

**Comment by avently** [comment]
@panacist the notification exists because Android requires to show it when the app starts a long running service. Without the notification Android can kill the app whenever it wants. 
Also the notification helps to control playback when you hide the app and listening in background (audio only)
