### ISSUE TITLE
[question] a question regarding the HAR file

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4238]
@wb9688  @Stypox i think you should guys ask for a specific object that is relevant or helpful to you on the http archive rather than for the entire file because i believe the har format contains security and privacy sensitive data (as the specification stated) something such as the cookies object. so what do you think about this guys and am i wrong ?

**Comment by opusforlife2** [comment]
@panacist Come on IRC to ask questions of this sort. Issue tracker is to track issues with the app.
