### ISSUE TITLE
Playback speed inconsistent & resets randomly

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#4239]
### Version

-0.19.8

### Steps to reproduce the bug

1. Start a video in the background player.
2. Set the speed to something else.
3. Pause the playback.
4. Open a stream in other player (pop-up, fullscreen)

### Expected behavior

The playback speed will be the same everywhere, or (feature idea) every player form will have it's own playback speed.
### Actual behaviour

The video will play at the other speed defined previously, however the video in the background player will show 1X and play at normal speed. When clicking on it, it will show the set speed, but not use it.
P.S. The background player will show 1X on every reopen.

### Screenshots/Screen recordings

![Screenshot_20200905-232608_NewPipe](https://user-images.githubusercontent.com/26146502/92313732-397d4080-efcf-11ea-8426-a4b5c1265b76.jpg)
![Screenshot_20200905-232613_NewPipe](https://user-images.githubusercontent.com/26146502/92313734-3d10c780-efcf-11ea-9780-8f51918ae39a.jpg)

**Comment by opusforlife2** [comment]
Can you test this in the unified player APK? You can get to it from the pinned issue.

**Comment by Stypox** [comment]
This is most probably duplicate of #3416

**Comment by kubo6472** [comment]
Yep, it is a duplicate in that regard. But @opusforlife2 it happens to some extent. When paused on the background player, it keeps the old speed. But when you open a new video somewhere else, it starts playing at the new set speed, even though it old playback and its speed remains unchanged.

**Comment by opusforlife2** [comment]
@kubo6472 
> however the video in the background player will show 1X and play at normal speed

This part has changed in the unified player. Now it _shows_ 1X but it plays at the chosen speed, since it's playing the new video.

Can you test this and confirm https://github.com/TeamNewPipe/NewPipe/issues/3416#issuecomment-687866169?
