### ISSUE TITLE
Can't play recommended videos

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#424]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When I try to play a video, it works fine, but when I tap on one of the recommended videos, the play button does nothing, so I've to manually search for that video, which is very annoying.

**Comment by theScrabi** [comment]
Tab on the top of the video than it will play.

**Comment by wb9688** [comment]
Ah, what's the relevant issue?

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/407
