### ISSUE TITLE
628 issues for a 3rd party clone

### ISSUE THREAD

**Issue by automenta** [TeamNewPipe/NewPipe#4240]
Indicative of controlled opposition or inability to replicate equivalent functionality on p2p network?

**Comment by opusforlife2** [comment]
I have no idea what this question means, but it sounds like a philosophical discussion, not a bug or feature request. You're welcome to elaborate on our IRC channel, but this issue tracker should be kept for tracking issues.

Easiest way to join IRC is to sign up on a Matrix instance and join #freenode_#newpipe:matrix.org.
