### ISSUE TITLE
Settings > Video Audio > Preferred 'open' action not working

### ISSUE THREAD

**Issue by wreuven** [TeamNewPipe/NewPipe#4244]
Reproduce:

Set the preferred 'open' action to 'background player'
Search for a video and tap it
Tap the 'Play' icon to play the video.
Video is opened in Foreground.

**Comment by avently** [comment]
@wreuven preferred open action is about playing the video after sharing a link/clicking on a link from an external app not from NewPipe

**Comment by opusforlife2** [comment]
We could change the description to say "Default action when opening content **from external links**" to eliminate ambiguity.
