### ISSUE TITLE
a few minor bugs

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4245]
here are a few minor bugs i've spotted (sorry for not filling the template) :
| issue 1       | issue 2     | issue 3     |
| :------------- | :----------: | -----------: |
|  ![Screenshot_2020-09-06-23-31-34](https://user-images.githubusercontent.com/66388840/92399041-2b3b3b80-f119-11ea-8ed0-d669fe5b3444.png) | ![Screenshot_2020-09-06-23-32-39](https://user-images.githubusercontent.com/66388840/92399069-355d3a00-f119-11ea-806d-4573d200be4d.png) | ![Screenshot_2020-09-06-23-50-10](https://user-images.githubusercontent.com/66388840/92399590-101cfb80-f11a-11ea-87bb-a6f927420044.png) |
| the size of the notification bar | look closley on the time indicator | missing fullscreen icon when auto rotation is enabled |

and apart from all of this can you please tell me what is the difference between the share icon and the globe(earth?) icon (aren't they doing the same function?)

**Comment by opusforlife2** [comment]
> the size of the notification bar

This is the old notification style. It will be replaced by the new one in #3178. You can test the APK there.

> missing fullscreen icon when auto rotation is enabled

Intentional, because it will change orientation with the phone, so you don't need the button.

**Comment by panacist** [comment]
@opusforlife2 
> This is the old notification style. It will be replaced by the new one in #3178. You can test the APK there.

thank you i will test it as soon as possible
> >Intentional, because it will change orientation with the phone, so you don't need the button.
well i think it shouldn't be this way? i really though it's a bug at first and other users may have similar impression because it's an unusual feature

**Comment by opusforlife2** [comment]
The whole UI is new, and full of new things users will have to get used to with time. But what is the _problem_ you're facing with the button?

**Comment by avently** [comment]
> the size of the notification bar

Don't get me wrong but, please, make sure your custom rom is not something that makes the bug happened. I really started to think that any issue you post can be considered as a custom rom bug.

**Comment by avently** [comment]
And yes, you can unlable `Unified player` because it's not related to Unified player even if you prove that the problem with NewPipe itself

**Comment by opusforlife2** [comment]
And always, _always_ state only one bug/feature per issue.

**Comment by panacist** [comment]
@avently @opusforlife2 not this time the phone doesn't use a custom rom !

**Comment by panacist** [comment]
and what's wrong with using a custom rom ? i use replicant os and you should guys try to have support for it (just as you do with the current version(partially at least)) ? i mean it's free software and everything so it deserves the support

**Comment by opusforlife2** [comment]
Most custom ROMs work fine, but I think Replicant in particular might have issues because of disabling non-free codecs, as avently said. If your phone doesn't have a decoder for VP9 (and no phone has an AV1 decoder) then you need an H.264 decoder, which is probably proprietary.

**Comment by avently** [comment]
> and what's wrong with using a custom rom ?

No one wants to deal with a badly working OS. We make software, not fixing custom rom issues.

**Comment by panacist** [comment]
@opusforlife2 
i just keep wondering why the current version actually loads the videos (well using webm) while the unified player just crashes everything !!
 @avently 
yeah absolutley it's not your problem but i think most of the people who don't want to use the youtube proprieatry app actually are using a custom rom (lineage os is a popular one) so providing a way around is always a good step and a huge learning expirience.

**Comment by opusforlife2** [comment]
> and apart from all of this can you please tell me what is the difference between the share icon and the globe(earth?) icon (aren't they doing the same function?)

The globe icon is to open the video in your default browser. The Share button will bring up the share sheet. What happens in your case?

**Comment by opusforlife2** [comment]
@panacist Does issue 2 happen with 0.19.8?

**Comment by panacist** [comment]
@opusforlife2  
> The globe icon is to open the video in your default browser. The Share button will bring up the share sheet. What happens in your case?

on android 5 it opens the "share with" thing but with fewer options(chiefly chrome, youtube ,newpipe itself and internet browser) than the share button.


> @panacist Does issue 2 happen with 0.19.8?

as far as i know nope it doesn't happen

**Comment by opusforlife2** [comment]
Have you set a default browser?

> as far as i know 

Check, dude. Narrow it down.

**Comment by panacist** [comment]
@opusforlife2 
> Have you set a default browser?

yup did so !

> Check, dude. Narrow it down.

did check and yup yup it doesn't happen as i said before

**Comment by avently** [comment]
Second thing is reproducible, the first - not.

**Comment by opusforlife2** [comment]
Sorry, you're saying you can reproduce Issue 2, avently?

**Comment by avently** [comment]
yep, fixed it already.

**Comment by opusforlife2** [comment]
Damn, you're too fast. XD

**Comment by avently** [comment]
>what was the cause?
https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/layout/player.xml#L358

**Comment by opusforlife2** [comment]
Ah. And appcompat is used for Android versions below...?

**Comment by avently** [comment]
Problem is padding, not AppCompat

**Comment by opusforlife2** [comment]
No I got that, but panacist has Lollipop, and this problem didn't appear on newer Android versions. So appcompat was needed for Android 5? 6?

**Comment by avently** [comment]
@opusforlife2 I have no idea why it's used here. Maybe for 4.4 because the slider will look old-fashioned on 4.4

**Comment by opusforlife2** [comment]
> on android 5 it opens the "share with" thing but with fewer options(chiefly chrome, youtube ,newpipe itself and internet browser) than the share button.

Ah. Default apps were introduced in Android 6, which is why the globe button is giving him multiple options. Is this expected behaviour or can something be done about it?

**Comment by avently** [comment]
I don't know and not interesting in making something with it

**Comment by opusforlife2** [comment]
> yep, fixed it already.

Alright. Please link the PR fix for Issue 2 to this one whenever you're done with it, since Issue 1 and 3 have been discussed and are not a problem.

**Comment by opusforlife2** [comment]
@panacist Again, make sure you only open one issue per item in the future.

**Comment by avently** [comment]
@opusforlife2 

>on android 5 it opens the "share with" thing but with fewer options(chiefly chrome, youtube ,newpipe itself and internet browser) than the share button.

So this is how it should work everywhere, because youtube link can be opened in browser, in youtube and in newpipe. this is how it works on every phone, even on 4.4. Share button shows more options

**Comment by opusforlife2** [comment]
Oh weird. I have Fenix Nightly as my default browser and tapping the globe directly opens it in Fenix. But if I change my default browser to Fennec, then I get the "Share with" menu containing apps which can open the link.

**Comment by panacist** [comment]
@opusforlife2 
> @panacist Again, make sure you only open one issue per item in the future.

SIR YES SIR!!

> I get the "Share with" menu containing apps which can open the link.

yeah that's why i though it's a bug or something at first

**Comment by avently** [comment]
see #4272
