### ISSUE TITLE
Allow loading captions from a (collection of) git repo(s)

### ISSUE THREAD

**Issue by SoniEx2** [TeamNewPipe/NewPipe#4249]
#### Describe the feature you want

Youtube is removing community captions. Let's make our own, using git(hub) repos. This would bring all the benefits of git(hub) to closed captioning - forks, pull requests, merging repos with no common root commits, etc.

#### Is your feature request related to a problem? Please describe it

Closed captions are extremely important for usability, and youtube is removing (some of) them.

#### How will you/everyone benefit from this feature?

This will make it easier to have high quality captions on videos. It also need not be restricted only to youtube videos, so this feature benefits non-youtube videos as well. In particular, this would be extremely handy for peertube videos.

We would suggest such repos to have a tree similar to this:

```
|-- youtu.be/
|   |-- video_id-human-readable-name.ass
|   `-- etc
|-- peertube-instance.example/
|-- btih/
`-- etc
```

but we don't know if this is a good approach. it's just a very basic idea. (we think the human readable name can be whatever and doesn't have to match the video title fwiw.)

**Comment by opusforlife2** [comment]
I think this is _far_ outside Newpipe's purview. If something like this already existed and was proposed to be added to Newpipe (like in Sponsorblock's case) I would understand.

@Stypox

**Comment by Stypox** [comment]
Yeah, this is offtopic for NewPipe
