### ISSUE TITLE
[Unified player] Selecting another video from streams tab doesn't update playlist dialog if kept opened

### ISSUE THREAD

**Issue by vkay94** [TeamNewPipe/NewPipe#4253]
### Version

- Unified player test apk: https://github.com/TeamNewPipe/NewPipe/commit/a801d0994f6cc1fe246c0d5ffff98aed09888ea8 (2020-09-06)

### Steps to reproduce the bug
1. Open a video stream and turn on Autoplay switch
2. Open the playqueue/playlist within the player (next to Playback Speed Controls)
3. Start another stream in the "Next streams"-tab

### Expected behavior
One of these depending on the head dev's preference (I guess):
- In the dialog the chosen (and next stream if autoplay/autoqueue is still enabled) should change accordingly to the current played stream
- When the other stream has been chosen the dialog should be dismissed and not opened again

### Actual behaviour
When the other stream has been shosen the playlist dialog is dismissed but opened again with the same videos (currently playing video =/= selected video in the playlist/queue + they can't be selected). When you close it and open in again the items are correct again.

### Does it appear on v0.19.8?
No. In v0.19.8 you can't choose another stream from the tab while the playlist dialog is opened.

### Video preview
https://streamable.com/kcm6p5

**Comment by avently** [comment]
Video costs a thousand of  words

**Comment by avently** [comment]
see #4272
