### ISSUE TITLE
Android 11, background playback & notifications

### ISSUE THREAD

**Issue by SheepKid12** [TeamNewPipe/NewPipe#4256]
### Edit
I'm putting this here since this is pinned, but this is actively being worked on (see #3178). Test APK's are being provided there, so you should go there to report issues.

### Version
- Latest from GitHub (running on a Pixel 3a XL)

### Steps to reproduce the bug
- Start background media playback.

### Expected behavior
- A notification type thing show up with playback controls.

### Actual behaviour
With the new Android 11 update, media playback controls were moved to a separate section away from normal notifications. Since you have your own notification for media playback separate from Android's default one, this may be why the one for NewPipe is empty (see attached screenshot).

### Screenshots/Screen recordings
![Screenshot_20200908-210025](https://user-images.githubusercontent.com/60110745/92545980-05945c00-f217-11ea-92f4-56d2b24230f7.png)

**Comment by opusforlife2** [comment]
😆 
I knew Android 11 issues would start popping up the moment I saw the news Android 11 released yesterday.

Newpipe is switching to a new style of notifications which will work on Android 11. The current notification code doesn't work, as you can see. Visit #3178 and test the APK. Mention any issues you have there.

I'm not closing this so that anyone else who visits can see this and not open duplicates.

**Comment by Poolitzer** [comment]
Hey I have this issue too. Look at me having Android 11 already, haha.

**Comment by opusforlife2** [comment]
> Look at me having Android 11 already, haha.

(brings out the knives)

You wanna die or something, bruh? O_O

**Comment by Stypox** [comment]
@Poolitzer @SheepKid12 could you test this apk? [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5204058/app-debug.zip)

**Comment by Poolitzer** [comment]
Is that different from the one I linked? If yes how?

**Comment by Stypox** [comment]
@Poolitzer it contains the latest fixes, see https://github.com/TeamNewPipe/NewPipe/pull/3178#issuecomment-690618400

**Comment by opusforlife2** [comment]
It's the same. Stypox went back and edited most links to point to the latest apk. 👍

**Comment by linucksrox** [comment]
On a related note, how do you get to the play queue in new pipe aside from tapping the media notification? When the notification isn't working it's a little tricky to get the music to stop playing, but shouldn't there be a way to get there from within the app?

**Comment by B0pol** [comment]
Fixed by #3178.

Latest apk available here

https://github.com/teamnewpipe/newpipe/projects/17

A release is coming soon

**Comment by nikhilCad** [comment]
Why is this still pinned?

**Comment by opusforlife2** [comment]
Until 0.20.0 releases.

**Comment by nikhilCad** [comment]
How do I go to landscape mode directly?
Do I now always have to wait for portrait mode to load and then switch to
landscape??

**Comment by opusforlife2** [comment]
@nikhilCad Follow #4152.
