### ISSUE TITLE
Reduce minSdkVersion to 17 (Android 4.2) in Build.gradle file

### ISSUE THREAD

**Issue by hamzajeljeli95** [TeamNewPipe/NewPipe#4257]
#### Describe the feature you want

The new feature is actually to target older Android 4.2 devices. a lot of tablets out there still runs on Android 4.2 and it would be a great idea if such a change is implemented.
#### Is your feature request related to a problem? Please describe it

Well, not really !

#### Additional context

I tried myself compiling version 0.19.8 to my Android 4.2 Tablet and it worked like charms just by changing `minSdkVersion 17` in the **Build.gradle** file and that's it !

#### How will you/everyone benefit from this feature?

Well, as i mentionned earlier, NewPipe will target more devices :) .

**Comment by wb9688** [comment]
No, it really doesn't just work when only editing `minSdkVersion`. Btw there is NewPipe Legacy for such old devices.

**Comment by B0pol** [comment]
https://f-droid.org/fr/packages/org.schabi.newpipelegacy/

https://github.com/teamnewpipe/newpipe-legacy

**Comment by hamzajeljeli95** [comment]
I can send for you a version with the modification, you can test if if you want.
