### ISSUE TITLE
Related videos show at the wrong place if comments are disabled

### ISSUE THREAD

**Issue by ryota-hasegawa** [TeamNewPipe/NewPipe#4260]
### Version

- 0.19.8
- latest dev branch

### Steps to reproduce the bug

1. Disable comments from "Settings -> Content -> Show comments"
2. Open any video in portrait
3. Rotate the screen to landscape

### Expected behavior

Related videos should be shown only on the right side of the screen.
### Actual behaviour

Related videos are shown under the player and the right side.
### Screen Recording

https://www.youtube.com/watch?v=voW6Fe6GFAo

**Comment by opusforlife2** [comment]
Is this also present in 0.19.8 or no?

**Comment by ryota-hasegawa** [comment]
@opusforlife2 
Yes
