### ISSUE TITLE
Recomendations feature request

### ISSUE THREAD

**Issue by GregoryIT** [TeamNewPipe/NewPipe#4263]
(Sorry for my english)
Since NewPipe doesn't require a google account as it does YouTube, it's completely obvious why there is no recommendations based on your interests. So I would like to suggest a recommendations feauture which is not needed an account. As you can see a set of related videos goes right down after the video you are watching. So it can be used to form a special personalised recommendations. Which way? So for example you've watched 3 videos called "1", "2" and "3". And there were some related vids to them, for the first one there were videos called "24", "25" and "26", for the second one there were "24", "28" and "26" and for the 3d one there were "24", "55" and "56". So video "24" has 3 matches, 26 - 2 matches, all the others - 1 match. So it's being based a set of related vids with different priorities. Most relevant could be used in recommendations list. Also some trend videos also could be used in recomendations (for example 20% - trends, 80% - related videos). If user doesnt like any video in recomendations he can tap "options" dropdown and choose "hide this video". Also those videos already viewed would be not used in recomendations.

And the second feature is the ability in settings to choose which tab is the first to be shown after the app opens. I don't want for example to see trends, I wanna see my subscribtions.

And the 3d feature is connected with notifications. NewPipe can update new videos in the background and when a new video comes out NewPipe will send a notifications about it (if the user has tapped on a channel bell of course).

I believe the first feature about reccomendations is so important as NewPipe doesnt provide recomendatios which is pretty sad :( I guess many users would have switched to NewPipe if only it had this feature).

**Comment by opusforlife2** [comment]
Always state only one feature/bug in one issue.

Your 2nd request already exists. You can change order of tabs and which tabs to show in "content of main page". Did you not browse the app's settings after installing it?

Your 3rd one also exists. You can search issues to see which issue number it is.

**Comment by opusforlife2** [comment]
Personally? I don't need it.

**Comment by GregoryIT** [comment]
Alright then. I just shared my idea with you. It's up to you whether to implement or not this feature. Thanks for attention 👍🏻

**Comment by opusforlife2** [comment]
Dude, I'm not a developer, nor am I an authority on what can be or can't be added to the app. XD

Wait for other people to see it, will you?

**Comment by GregoryIT** [comment]
I will 👍🏻

**Comment by HellxDo** [comment]
#4253 seems related to the first option

**Comment by HellxDo** [comment]
#4235 looks similar to the first Issue/Idea

**Comment by opusforlife2** [comment]
Found the original: #2256.

@GregoryIT please post your suggestion as a comment on that issue.
