### ISSUE TITLE
Playback Speed gesture control

### ISSUE THREAD

**Issue by EliasKomar** [TeamNewPipe/NewPipe#4265]
#### Describe the feature you want

Similarly to the video and brightness gesture control you could add a playback speed guesture control, where you could modify the playback speed by sliding your finger left to right <---> and maybe also a reset to normal playback speed.
This could be switched on and off in settings.

#### How will you/everyone benefit from this feature?

As a person who often watches educational videos, I regularly change the playback speed. Implementing a gesture for playback speed, even if off by default, would make the controls much easier to use and NewPipe way better for watching educational videos.

**Comment by avently** [comment]
Sliding from left to right should change video position, not speed

**Comment by Stypox** [comment]
#1823
