### ISSUE TITLE
[unified player] bug after half brightness (+50%) don't hold value:

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#4271]
### Version

using Unified player debug

if you set brightness at any value above 50% let's say 75%, then if you start a new or same video and try to adjust brightness to 90%... your spouse to increase brightness from 75% to 90% by sliding brightness up... however instead the brightness value starts to adjust from 50% instead from 75%, meaning it  does not hold the correct value (which is in this case 90%) to adjust brightness from there.

this does not happen if brightness value was -50%, meaning if brightness is seat to 20% and another video was opened.. brightness  will start to adjust from 20% as it should be.

to reproduce this bug:
- simple open any video 
- set brightness to about 90% 
- press back
- open a new or same video
- try to adjust brightness to 100%
- instead the slider will start from 50%

This does not happen in NewPipe 19.8 nor NewPipe 19.8 legacy

**Comment by avently** [comment]
WIll be fixed in the next series of small fixes. Already fixed locally.

**Comment by MD77MD** [comment]
@avently 
😭 i wish I know.... I had so much trouble explaining it as English is not my first language😁

**Comment by avently** [comment]
see #4272
