### ISSUE TITLE
Change default video quality

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#4274]
#### Describe the feature you want

I'd like to change the default quality. 360p is a bad quality.

#### Is your feature request related to a problem? Please describe it

It's 2020, 360p is really bad, time to change quality.
People may think NewPipe is bad because of very low video quality.

#### Additional context

I think 720p60 should be the default one, it requires less bandwith than 1080p but still look great on smartphones.

And I think we 480p should be the default one for mobile data / popup player, to reduce bandwith for mobile data, and because it's smaller there is no need for a huge resolution.

According to you, what should be the default quality?

**Comment by opusforlife2** [comment]
Fully agreed. My view here is the same as for the default minimize option being set to background. The user should be made aware the feature is there, they can decide on their own whether they want it or not.

Making 720p60 the default would let them know Newpipe supports 60Hz videos. And 480 streams are small enough compared to 720, but not too big compared to 360. It's a good middle ground.

> People may think NewPipe is bad because of very low video quality.

They definitely do, in my experience. I can show them the default quality can be changed, but by that time the first impression has already been made.

**Comment by B0pol** [comment]
From an IRC user, @LjL

> i don't really notice 360p being bad quality on the phone, and i'd be happy to keep it for mobile data, but i'd also be okay with 480p. i think wifi should be 720p or "whatever is highest".

**Comment by Stypox** [comment]
I agree with you on the 720p increase, but I'm not sure if popup really needs 480p. Popups won't most probably be used at more than half the screen's size (multitasking would be impossible in landscape with popup of >½ the screen's size, and in portait popups can't even grow as much as that), so I think having half the resolution is enough. I'd use 360p for popup then, but I could be wrong about the assumptions above

**Comment by opusforlife2** [comment]
Remember how it was discussed that Newpipe (strangely) prefers the video stream that already contains audio for 360p instead of the video-only one? This legacy encode is generally only slightly smaller than -- but most of the time even _bigger_ than -- the 480p stream. On average, I think we will help users save data. And it comes with the bonus of a higher resolution! Win-win.

**Comment by B0pol** [comment]
Good point. I picked three random trending videos, here is the size

<img src="https://i.ibb.co/3pZp0ts/Screenshot-20200912-234007-New-Pipe.png"> <img src="https://i.ibb.co/TH9BSh1/Screenshot-20200912-233852-New-Pipe.png"> <img src="https://i.ibb.co/N93M6hb/Screenshot-20200912-233818-New-Pipe.png">

As you can see 360p doesn't save lots of data compared to 480p, then there is no valid reason to use it over 480p.

@Stypox I often use popup with long press to expand and sometimes I feel the need to have more than 360p. I'm probably not the most common use case, bus as you can see above (or test with more videos) there isn't a big difference on the size side.

I will do that before 0.20.0, it should be really easy and NewPipe will have more new users than usual update.

**Comment by TobiGr** [comment]
I'd vote for 720p, but not 720p60 for normal video player.

**Comment by opusforlife2** [comment]
🤣 Actually, there are many cases where even 720p60 is smaller than 720p.

But in general, most file sizes are quite similar, and even in the worst case, it never exceeds roughly 1.5x the size of the 720p stream.

**Comment by MD77MD** [comment]
worth mentioning... 

there are a lot of YouTube users who can not watch in 720p or higher because of bandwidth limitations... this category of users should be considered because if 720p was the only default then newpipe would struggle to open videos without stutter thus giving bad impression... perhaps an option to choose default resolution at the first lunch of the app would be better... something like this:

choose default video quality:
360 - 720p - 720p60
this can be changed latter in settings

anyway i hope my constant feedback isn't too annoying though 😔

**Comment by TobiGr** [comment]
Yes, we really need https://github.com/TeamNewPipe/NewPipe/issues/859 with some setting screens in the intro.

**Comment by opusforlife2** [comment]
What do you think about opening the Settings Activity directly upon first start of the app? Specifically, the Video and Audio menu, where we could flash/highlight the resolution setting temporarily to draw attention to it?

I think this could encourage users to browse the rest of the settings too.

I'm thinking of a welcome dialogue shown in Settings, something like:

"Hi! Welcome to Newpipe! This app is quite different from Youtube, Soundcloud or other apps you may have used in the past, so we encourage you to have a look through the settings and change them to your preference. Some important ones you may want to know about:
- Default resolution (for the main player, and also the popup player)
- Preferred 'open' action (default action when opening a link from another app)
- Minimize on app switch (should Newpipe continue playing in the background if you switch to another app?)
- Gesture controls for volume and brightness
- Download folder (Yes! You can download too!)
- App theme (self-explanatory)
- Watch and Search History (who wants to know what I'm watching!? ( ⚆ _ ⚆ ) )
- App language and content language
- Content of main page (which tabs to show, in what order)
- Import and Export Backup

Once you're done, back out of the settings to see the main interface! We hope you enjoy using the app!"

This way, we don't have to design an entire app tour which is used only once and never again. An app tour would have to be updated constantly to explain new features and to not conflict with changed code.

**Comment by B0pol** [comment]
@opusforlife2 discuss about that in #859. This is not the point of this issue.

@MD77MD but I don't think it's the majority of users, and I prefer that a minority of users with low bandwith must lower quality than the majority must increase quality.
