### ISSUE TITLE
Video not available - content unavailable in Newpipe This video is restricted. Try signing in with G Suite account in mobile browser

### ISSUE THREAD

**Issue by damascene** [TeamNewPipe/NewPipe#4278]
When I click on some videos in my feed I get the Video not available - content unavailable screen. 
![image](https://user-images.githubusercontent.com/411046/93124350-273b8a80-f6d2-11ea-92a5-e217209ff506.png)

### Version
0.19.8

### Steps to reproduce the bug
Open any of those videos in Newpipe
https://www.youtube.com/watch?v=kJ2qisYAIvs
https://www.youtube.com/watch?v=MnvRbANZfYg

### Actual behaviour
It shows the unhappy face with Video not available - content unavailable message

I suspect that those video are somehow shadow banned or something because I see them in the feed but when I visit the respected channels I don't find them listed. I've noticed this issue two days ago with some videos.

Those videos and similar ones don't work in mobile browser and I see this warning in youtube.
**Try signing in with G Suite account in mobile browser**
on computer browser it opens without any issue.

I'm using the smart fast feed.

**Comment by Stypox** [comment]
Do you have YouTube's restriction option on?

**Comment by damascene** [comment]
> Do you have YouTube's restriction option on?

No

**Comment by Stypox** [comment]
Could you install a debug apk (for example [this one](https://github.com/TeamNewPipe/NewPipe/files/5204058/app-debug.zip)), connect your phone to your PC through USB, open Chrome, go to `chrome://inspect`, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send us that HAR? Then we might be able to fix this issue.

**Comment by damascene** [comment]
done
[newpipe-tPADtMN8lkI.har.zip](https://github.com/TeamNewPipe/NewPipe/files/5230119/newpipe-tPADtMN8lkI.har.zip)

**Comment by opusforlife2** [comment]
Thanks!

**Comment by timjefferies** [comment]
I have had this issue for a while. I think it started around the time the restricted option was added. No restricted videos will play and toggling the option does nothing.

**Comment by RaihnerZufall** [comment]
I've had this problem in the past, it's not a newpipe problem, it's more of a shadow ban. If you look into the settings of the official YouTube app, the restricted mode is enabled and you can't switch it off (button is grey). No matter what device or client I was using (official Youtube app, Youtube browser or newpipe), I couldn't see any comments (in the official Youtube app it said "the restricted mode has hidden comments for this video") nor watch all videos. The only way I was able to get around this was to use a different IP

**Comment by damascene** [comment]
I've used different IPs and the issue still present when I connect from mobile phone. I can use computer with no issue and I can use link like this on mobile browser: 
https://yewtu.be/watch?v=MY8Nfzcn1qQ (from invidio.us)
but shows the warning "this video is restricted" when I visit normal youtube link in mobile browser 
https://m.youtube.com/watch?v=MY8Nfzcn1qQ

**Comment by shivvvvvv** [comment]
> I've used different IPs and the issue still present when I connect from mobile phone. I can use computer with no issue and I can use link like this on mobile browser:
> https://yewtu.be/watch?v=MY8Nfzcn1qQ (from invidio.us)
> but shows the warning "this video is restricted" when I visit normal youtube link in mobile browser
> https://m.youtube.com/watch?v=MY8Nfzcn1qQ

> I've used different IPs and the issue still present when I connect from mobile phone. I can use computer with no issue and I can use link like this on mobile browser:
> https://yewtu.be/watch?v=MY8Nfzcn1qQ (from invidio.us)
> but shows the warning "this video is restricted" when I visit normal youtube link in mobile browser
> https://m.youtube.com/watch?v=MY8Nfzcn1qQ

You have any kind of parental control or something similar enabled in your phone?

"this video is restricted" issue happened with me too some time ago. I was using the adguard family dns on my android which blocks adult stuff. I did not knew what was going on with some youtube videos being blocked by youtube and it keeps asking for me to sign in with Gsuit account.

Later I switched to normal adguard dns and then I never saw such warning again.

Edit : I just reproduced the issue you having with adguard family dns and I can see "video not available" popup with the youtube links you provided.

**Comment by timjefferies** [comment]
>  I was using the adguard family dns

I can confirm this was this issue for me. Changed it to normal adguard and it also resolved it. :+1:

**Comment by opusforlife2** [comment]
Can everyone else please try this so we can confirm whether this is a Newpipe issue? ^

**Comment by damascene** [comment]
I can confirm the issue isn't present currently with adguard family filter disabled. I wonder how a DNS issue has effect on what Youtube shows or doesn't.

**Comment by opusforlife2** [comment]
@Stypox We really need a FAQ.

Close?

**Comment by Stypox** [comment]
> done
> [newpipe-tPADtMN8lkI.har.zip](https://github.com/TeamNewPipe/NewPipe/files/5230119/newpipe-tPADtMN8lkI.har.zip)

Thank you @damascene ;-)
I looked into it, but unfortuntely there does not seem to be a way to solve this, as YouTube won't return the valid data in any way. The video is correctly identified as an age restricted video by NewPipeExtractor, thus it is handled in a different way, but even then YouTube still returns errors (other age restricted videos are handled correctly though). So this might really require a Google account and there is no way around it.

**Comment by spvkgn** [comment]
@Stypox 
I'm getting the same error with some videos, YT restriction option disabled, NP 0.20.2, AdGuard disabled

[a4BJ7Q3YVf8](https://www.youtube.com/watch?v=a4BJ7Q3YVf8)

Here is .har [a4BJ7Q3YVf8.har.zip](https://github.com/TeamNewPipe/NewPipe/files/5456418/a4BJ7Q3YVf8.har.zip)

**Comment by ashoklathwal** [comment]
https://wealthquint.com/fix-newpipe-content-unavailable-63068/
