### ISSUE TITLE
Support Youtube shortened url

### ISSUE THREAD

**Issue by angriness-sleek** [TeamNewPipe/NewPipe#4283]
Possibly the url format of the new [Youtube Shorts](https://india.googleblog.com/2020/09/building-youtube-shorts-new-way-to.html), newpipe cannot currently open this url: http://www.youtube.com/w/-pdo6QUoOxo
Would be nice if this can be supported in near future :)

**Comment by B0pol** [comment]
No, it's not youtube shorts

It's just another shortened url, the full url is https://youtube.com/watch?v=-pdo6QUoOxo

**Comment by opusforlife2** [comment]
I'll just open another issue requesting Youtube Shorts support. 😆
