### ISSUE TITLE
[Feature Request] Resizing/customizing Subscription Thumbnails

### ISSUE THREAD

**Issue by wisor12** [TeamNewPipe/NewPipe#4287]
Is there a way to resize the thumbnails in the subscription category/panel?

There are too many listed and the thumbnails are too small with the default grid view. And when you switch to list view there is lots of wasted space and it's not centered. Just like with the default youtube desktop page.

Do you plan to add a resizing feature? I mean google themselves are doing it i.e. the Home section has much bigger thumbnails/icons for instance.

Thanks a bunch.

**Comment by Stypox** [comment]
#3291 #3139
