### ISSUE TITLE
Newpipe Inexplicably Closes During Background Play

### ISSUE THREAD

**Issue by Charred-Almonds** [TeamNewPipe/NewPipe#4289]
There's never any sort of error message or notification, it just seems that more often, NewPipe will close itself while I'm playing audio in the background. This is a recent issue, and I'm not sure why it would happen all of the sudden. Does anyone have any ideas? I use a Samsung Galaxy A51.

**Comment by Stypox** [comment]
Try the apk provided in #3178 and check if it fixes the issue

**Comment by mhmdanas** [comment]
@Charred-Almonds I also use Galaxy A51, and I don't recall ever having this issue. Did you disable battery optimizations for NewPipe?

**Comment by opusforlife2** [comment]
Closing until user replies.
