### ISSUE TITLE
Video constantly freezes on 0.8.8

### ISSUE THREAD

**Issue by aladar42** [TeamNewPipe/NewPipe#429]
Ever since updating to 0.8.8, my video constantly freezes - first, the actual video portion of the stream will freeze, and then, eventually, the whole stream will stop. This happens every few minutes on most videos. I'll be happy to provide closer information if you can direct me to some way to collect the relevant info.

**Comment by theScrabi** [comment]
If you use the internal player please use an external than.

**Comment by mauriciocolli** [comment]
We now have ExoPlayer, if the problem still happening, just tell me.
