### ISSUE TITLE
Subscription Icons - Condensed Layout in Portrait Like Landscape View

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#4290]
#### Describe the feature you want

Just like landscape mode, having a condensed layout for all the subscription channel icons will greatly reduce scrolling pain. Also half of right side of portrait view under Subscription go unused. But once you rotate and see landscape mode, all icons are condensed and nicely gathered occupying whole interface.

#### Is your feature request related to a problem? Please describe it

No, this is not about a problem.

#### Additional context

This will help create better interface with icons of subscribed channels easily available to click on instead of scrolling action.

#### How will you/everyone benefit from this feature?

Users might like to see more in less space. And such space right now is available in Subscription page. Landscape view already has it and this feature will reduce headache of finding that one good channel you wan to watch more quickly!

**Comment by avently** [comment]
Settings -> Appearance -> List view mode -> Grid
Isn't it what you want?

**Comment by desmonk** [comment]
You are right! I tried that options but since the change is not immediate and only works after you exit and restart the app again, I never noticed the difference and always used to use on default "Auto" mode.

Thank you very much for this!
