### ISSUE TITLE
Youtube Shorts support

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4291]
Youtube has released a new content format called Shorts. Newpipe should support it.

**Comment by B0pol** [comment]
from what I've seen it's currently only beta in India and just a tool to upload short videos.

… And is already supported because nothing has changed, e.g. [this video](https://invidious.snopyta.org/watch?v=ua3Dwtctm80) is a YouTube short.

Then can you clarify what do you want by "support"?

**Comment by opusforlife2** [comment]
Ah. Okay then.

**Comment by B0pol** [comment]
![image](https://user-images.githubusercontent.com/58657617/93671100-80276c00-faa0-11ea-8b39-8da0fea79d83.png)
source https://support.google.com/youtube/thread/71081044

you can reopen this when we can access shorts from the homepage

**Comment by opusforlife2** [comment]
I don't think we need anything special. We should just show whatever the Youtube home page does. Maybe another default tab for Shorts, or make the Trending tab swipe-able to the left or right to view the Shorts shelf.

I'm sure Youtube will show recommended Shorts when/after you view one, so that will be symmetrical to recommended videos.
