### ISSUE TITLE
Status bar is not dismissed after video quality change

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#4292]
### Version

- b69e477ecdf576d0406c0de87db3c8a2866ce741

### Steps to reproduce the bug

1. play a video
2. change quality
3. wait few seconds

### Expected behavior

The status (hour, notifications, battery level…) and navigation bars should be dismissed.

### Actual behaviour

It stays indefinitely

**Comment by avently** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/4272#issuecomment-695350659
