### ISSUE TITLE
Can't scroll subtitles anymore

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#4293]
### Version

- https://github.com/TeamNewPipe/NewPipe/commit/b69e477ecdf576d0406c0de87db3c8a2866ce741

### Steps to reproduce the bug

1. Open a video with lots of subtitles, e.g. https://invidious.snopyta.org/watch?v=58hoktsqk_Q
2. press the arrow button
3. click on subtitles and scroll

### Expected behavior

It scrolls
### Actual behaviour

You can't scroll anymore
### Screenshots/Screen recordings

![newpipe_0_19_8_subtitles](https://user-images.githubusercontent.com/58657617/93671647-00e86700-faa5-11ea-9d2c-f1e10e1770c7.png)

![newpipe_0_20_0_pre-version](https://user-images.githubusercontent.com/58657617/93671649-0645b180-faa5-11ea-9260-8c84af91a7a9.png)

you can notice that the bar at the right for 0.19.8 (first screenshot) which shows the position, is not visible anymore

**Comment by opusforlife2** [comment]
You can still scroll in portrait (video details), but you can't scroll in landscape.

**Comment by avently** [comment]
Already fixed in #4272
Apk: https://github.com/TeamNewPipe/NewPipe/pull/4272#issuecomment-694354182

**Comment by opusforlife2** [comment]
Confirmed.
