### ISSUE TITLE
Subtitle text area is smaller for no reason than 0.19.8

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#4294]
### Version

- https://github.com/TeamNewPipe/NewPipe/commit/b69e477ecdf576d0406c0de87db3c8a2866ce741

### Steps to reproduce the bug

1. set newpipe language to french
2. open a video with subtitles; e.g. https://invidious.snopyta.org/watch?v=58hoktsqk_Q
3. press the arrow button

### Expected behavior

If there is room, notice "Aucun sous-titre" (no subtitles)
### Actual behaviour

There is room for it but only "Aucun sous…" is shown
### Screenshots/Screen recordings

![newpipe_0_19_8_subtitles](https://user-images.githubusercontent.com/58657617/93671647-00e86700-faa5-11ea-9d2c-f1e10e1770c7.png)

![newpipe_0_20_0_pre-version](https://user-images.githubusercontent.com/58657617/93671649-0645b180-faa5-11ea-9260-8c84af91a7a9.png)

**Comment by avently** [comment]
The reason is portrait mode and long caption name

**Comment by B0pol** [comment]
That's a reason for portrait mode, not for landscape. In landscape there is more space, hence it should be larger.

**Comment by opusforlife2** [comment]
Can the width be dynamic? That is, from the Fit setting until wherever the first drop down setting icon starts, plus some padding space.

**Comment by avently** [comment]
It can be dynamic but it that case I need to replace LinearLayout with RelativeLayout which will hurt performance and I don't want this. I will make the maxWidth based on window size. So on small window (regardless of landscape because you can have the app in landscape but in multiwindow mode with small app window) the caption will be shorted and longer in a large window

**Comment by opusforlife2** [comment]
Oh. Good point. It's not important enough to sacrifice performance.

**Comment by avently** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/4272#issuecomment-695350659
