### ISSUE TITLE
Auto download / cache audio for specific playlists in the background player

### ISSUE THREAD

**Issue by mafrailea** [TeamNewPipe/NewPipe#4300]
#### Describe the feature you want

I use NewPipe as a music player. I've created several public playlists in Youtube that I launch in the background player.

It would be nice if NewPipe background player could automatically download and store audio tracks of specific playlists on the phone storage, so future iterations of that song don't need to download the track again.

In addition, it would allow offline playing of specific playlists.

#### Is your feature request related to a problem? Please describe it

Not related with an issue.

#### Additional context

I think it could be implemented like this:
- Add an "offline mode" option for specific playlists in the playlists tab, so the user can select which playlists should be kept for offline use when using the background player.
- When playing such a marked playlist on the background player, NewPipe should download the track to internal storage if it doesn't exist yet, or play it from storage if it was already downloaded.
- All downloaded tracks of different playlists could be stored in the same configurable folder using their corresponding YouTube ID, so it's easy for the player to locate them and tracks that exist on different playlists aren't downloaded more than once.

**Comment by Stypox** [comment]
#478

**Comment by opusforlife2** [comment]
Post your suggestions as a comment there.
