### ISSUE TITLE
Latency Compensation for Audio and Subtitles

### ISSUE THREAD

**Issue by sack0fd3mon** [TeamNewPipe/NewPipe#4301]
#### Is your feature request related to a problem? Please describe it

Wireless headphones often have latency as they aren't sent over a cable, while some newer codecs can offer up better latency, not all headphones support these new codecs. A solution to this would be to offer up supports for latency compensation, for both subtitles and audio, preferably on a 10ms step.
#### How will you/everyone benefit from this feature?

This feature would be very useful in videos with audio and video that are supposed to be in sync with one another, such as live concerts with the lighting that matches the rhythm of the music, or faulty subtitles that are consistently ahead or behind the video.

**Comment by wb9688** [comment]
@Redirion: Do you happen to know if ExoPlayer supports this?

**Comment by sack0fd3mon** [comment]
I don't know, but VLC supports this feature.

**Comment by sack0fd3mon** [comment]
Actually, I've found out that the latest debug version included this and that the videos matched up with the audio very well, I think that it's because it finds that I've configured and saved this in VLC before.
