### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by muhendis46** [TeamNewPipe/NewPipe#4302]
problem of changing the tone when accelerating the sound
audio download options no mp3 format

**Comment by Stypox** [comment]
Duplicate of #507; won't fix because adding an mp3 converter would greatly increase the app's size. Please use a third party converter instead

**Comment by opusforlife2** [comment]
> problem of changing the tone when accelerating the sound

Make sure the "Unhook" box is selected, and the Pitch remains at 100% no matter what the Tempo is.
