### ISSUE TITLE
Network Error (Retry) midway through refreshing Feed

### ISSUE THREAD

**Issue by bonej5** [TeamNewPipe/NewPipe#4304]
### Version

-0.19.8

### Steps to reproduce the bug

-Go to "What's new"
-Refresh
- It loads until 182 subs
- BTW I am on stable wifi

### Actual behaviour

-Retry button got me in the loop
-I had to close the app
-Then after restart it shows me videos from the last successful scan (before network error)
### Screenshots/Screen recordings

![Screenshot_20200921-191433](https://user-images.githubusercontent.com/68895088/93800224-91a77a00-fc40-11ea-9901-2963de8a7189.png)

**Comment by opusforlife2** [comment]
Related: #3368, #3923.

**Comment by AudricV** [comment]
Is it still an issue? I think the app now continues to fetch the feed when it gets errors and shows a message at the top of the feed once the refresh is complete indicating the number of non-loaded channels.
