### ISSUE TITLE
Larger thumbnails

### ISSUE THREAD

**Issue by drewblasphemepatchwork** [TeamNewPipe/NewPipe#4305]
#### Describe the feature you want

Feature to make the thumbnails bigger, like in the official Youtube app. Thumbnail from side to side and title under it.

I considerd changing the list view mode to "grid", however this is not what I'm looking for

#### Is your feature request related to a problem? Please describe it
 I don't think it's related to any problem.

#### Additional context

https://ibb.co/47ZZGdg

Picture of the layout in the official Youtube app

#### How will you/everyone benefit from this feature?

Everyone could benefit from this since switching to Newpipe would be easier due the more familiar layout. Scrolling through videos would be more pleasant if they were bigger. Looking for details in a thumbnail wouldn't be so hard for example.

**Comment by Stypox** [comment]
#3291 #3139
