### ISSUE TITLE
[Feature Request] Sharing settings beetwen apps

### ISSUE THREAD

**Issue by pawlosck** [TeamNewPipe/NewPipe#4306]
Hi

I would like to propose to add feature which allow to share settings beetwen apps.
Currently, I think about newpipe and Freetube, but if other similar apps exists, then these apps can be added too.

I think about sharing settings like:
- subscriptions
- movie status (watched, unwatched, current time)

Config file could contain syntax like this
timestamp,id_movie,movie_status,channel

- timestamp - when movie status was saved -> this option could be used to findings which program was used to watch movie (latest watching). For example. If Newpipe will check config file and find in Freetube config file newer timestamp, then Newpipe will use movie_status from Freetube to start watching movie.
- id_movie - url of movie or other id
- movie_status - watched, unwatched, time of movie (hh:mm:ss)

All apps will use own config file, so one app will not overwrite config file second app.
All apps will use specific dir to save config file and next, other synchro app will synchronise these config files.

I will create issues for newpipe and for freetube
FreeTube: https://github.com/FreeTubeApp/FreeTube-Vue/issues/147

**Comment by Stypox** [comment]
#3249
