### ISSUE TITLE
Не хочет воспроизводить видео в окне и при разделении экрана

### ISSUE THREAD

**Issue by person16091** [TeamNewPipe/NewPipe#4311]
Сижу смотрю видео и приложение закрывается (само) при разделении экрана и всплывающем окне(разрешения всё выданы)
![1600928903](https://user-images.githubusercontent.com/71587402/94119636-dc4f0f00-fe57-11ea-9295-ec37b8d7cdbe.jpg)
![1600928906](https://user-images.githubusercontent.com/71587402/94119644-dd803c00-fe57-11ea-8849-d698ea14752f.jpg)

**Comment by Stypox** [comment]
This is a known crash when closing popup. Use english next time.

**Comment by avently** [comment]
Новая версия, которая ещё не вышла, содержит уже совсем другой код и, скорее всего, не содержит этого бага. Потому что я это вижу первый раз. Так что подожди чуток новую версию.

**Comment by person16091** [comment]
> Новая версия, которая ещё не вышла, содержит уже совсем другой код и, скорее всего, не содержит этого бага. Потому что я это вижу первый раз. Так что подожди чуток новую версию.

Здравствуйте ещё раз.
Может эта информация вам поможет:
У меня это было с Ванседом и т.д. и проблема устранилась после того как я вытащил SD-карту
