### ISSUE TITLE
Option to change user agent 

### ISSUE THREAD

**Issue by dorrisowens** [TeamNewPipe/NewPipe#4313]
AFAIK, Newpipe uses androidwebview which uses google chrome like useragent and also have device model in it, which tells google about the device and IP which connects to google. While IP problem can be solved with a VPN, I request to give an option to use custom useragent for webview so, that we can hide our device details from google as well.

**Comment by Stypox** [comment]
Are you talking about ReCaptcha's webview? If that's the case, then this should definitely be solved.
