### ISSUE TITLE
Share does not work from soundcloud

### ISSUE THREAD

**Issue by garawaa** [TeamNewPipe/NewPipe#4316]
Sharing does not work

**Comment by TobiGr** [comment]
When playing a video and sharing it, the timestamp is appended to the URL. Removing it makes SoundCloud recognize it.

**Comment by TobiGr** [comment]
Ah wait. We produce an invalid URL here in the first place. We should check the cause for this, too.

**Comment by wb9688** [comment]
@TobiGr: And this is why `URL` exists… we really shouldn't append `String`s and hope it becomes a valid URL.

**Comment by spacemonkey1101** [comment]
Hey, I would love to work on this. Can you assign me?

**Comment by opusforlife2** [comment]
> I guess people only thought about YouTube when changing the share logic.

(sideways glance at @Stypox 🤭)

**Comment by opusforlife2** [comment]
@spacemonkey1101 Sure.

**Comment by spacemonkey1101** [comment]
I am unable to build because of the checkstyle errors already present. Should I solve them one by one or is there a way to disable checkstyle checks.

**Comment by B0pol** [comment]
> I am unable to build because of the checkstyle errors already present. Should I solve them one by one or is there a way to disable checkstyle checks.

could paste the error log?

there should be only warnings, no errors. Anyway if you want to disable checkstyle [comment or remove runCheckstyle here](https://github.com/TeamNewPipe/NewPipe/blob/e0f02d40805f121180a6ef75e24421989386b00f/app/build.gradle#L138).

**Comment by opusforlife2** [comment]
@spacemonkey1101 So, could you get past the build issue?
