### ISSUE TITLE
[Bug] Webm Audio Saved in Video's Folder

### ISSUE THREAD

**Issue by Yowlen** [TeamNewPipe/NewPipe#432]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

When "webm" is selected as the default format in Settings, downloaded files are saved to the videos folder, regardless of whether it's video or just the audio.

**Comment by utack** [comment]
that is odd, because I definitely downloaded a vorbis in webm that ended up in my Music folder

**Comment by codermess** [comment]
@Yowlen I also can't reproduce it, I get it downloaded under Music. Do you remember how it happened? Could it have been fixed since then?

**Comment by Yowlen** [comment]
Ah. I'm sorry. I gotta remember to go through my old bug reports once in a while. Yes, this has been fixed since my initial report.

**Comment by codermess** [comment]
No problem, I thought I could go through old bugs to see their status :)
