### ISSUE TITLE
Built In APK Downloader Within NewPipe App - So Updates are Fetched Automatically - Irrespective of App Source Download Location

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#4323]
#### Describe the feature you want

I had Signal installed using their APK available on the site directly not via Play Store. And app surprisingly (WhatsApp does that too and so is Play Store), has built in feature to download the latest updated APK for users. Also, (I am not sure if it is even possible.) can it be possible to fetch such updated automatically irrespective of a user installation method of the app.

Say, a user has installed from F-Droid or Git or Web then the app automatically makes sure to fetch future updates from respective sources.

This is totally not a popular method of using the app but such method will be the fastest one to install the latest update available by dev team. This is less secure, but just had a thought about it.

#### Is your feature request related to a problem? Please describe it

Not a problem but this can help streamline update process for users more efficiently. 

#### Additional context

I don't have any to add.

#### How will you/everyone benefit from this feature?

Biggest benefit will be faster and more easier update process. App decides itself that it is time to update and fetches the APK for a user to install it later on. How awesome is that!

Anyways, I am always thankful for using NewPipe. Thank you very much!

**Comment by opusforlife2** [comment]
The idea of an internal updater has already been rejected in #3141.

**Comment by desmonk** [comment]
Wow! In didn't realize that went so brief and faced so many hurdles and thinking. Still hope some easier way gets introduced soon cause I'm sure users will love that. An app taking care of it's own update is good. Thank you again and I'm sorry for not searching properly for closed issues before.

**Comment by opusforlife2** [comment]
It's okay. This was a PR and you wouldn't have known to search them beforehand. But is the custom Newpipe F-Droid repo not convenient enough?

**Comment by desmonk** [comment]
No, it is fine absolutely.

But I was thinking users are lazy. I sure one of those who often forget to update apps. Signal has started this really good way of putting a giant (little bit aggressive) banner inside the app that asks users to update as current version is set to expire. This is a bit extreme example but this little intrusion actually saves a lot of work.

Problem with F-Droid is the updates are fetched but then since most devices are not rooted, users have to install each update manually. This is what is painful. Play Store obviously has all the rights to deal with this downside along with better security. There is no auto install for F-Droid.

If NewPipe gets the update itself then users won't face any annoyance as above. Only one time they have to allow the permission to install the app. And that's it!

Plus control will be in developer's hand. So no more delays and always up to the date updates.

I mean if Google is allowed to do whatever they want then why an app that is actually benefiting users like NewPipe is bound like this? Users will be delighted.

Can we run a poll or something?

**Comment by opusforlife2** [comment]
For auto install from F-Droid you need the privileged extension, which needs root to be installed. Android should not have locked down the root user from the beginning for all phones. No one complains about the Admin account on Windows the same way.

**Comment by desmonk** [comment]
That's true. I still wouldn't recommend a root though as most users don't need that for both privacy and security. A PC is not that of a personal device than a mobile is. Mobile has far more personal things going on. And now we are in post PC world.

One fine example is Facebook. I remember how they didn't take care of mobile users when they had IPO and crashed. Now mobile is where data is.

I am not in disagreement here but an average user is naive and unaware. Who knows what apps from where get on phones. And it takes one bad actor to ruin the play for all.
