### ISSUE TITLE
Remove "Remember popup properties" toggle and make it the default behaviour

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4329]
Opened after discussion on IRC.

There doesn't seem to be much use for a case where the user would prefer that the app _doesn't_ remember popup size and position. So the default behaviour should be for the app to remember, and the setting should be removed entirely.

**Comment by panoreak** [comment]
Hello! Can I work on this?

**Comment by opusforlife2** [comment]
Absolutely! Go ahead.

**Comment by DI555** [comment]
why you're deleting the choice of using options!
the option should be workable!
who give you the right to choose for others ???
personally, i, and many others should have the option to not save popup positions!!!
