### ISSUE TITLE
[Bug] Audio download only changeable via default in Settings

### ISSUE THREAD

**Issue by Yowlen** [TeamNewPipe/NewPipe#433]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Current behavior: Downloading audio chooses format based on default in Settings
Better behavior: Downloading audio chooses format based on currently-selected format like video
Reasoning for change: Consistent behavior

**Comment by utack** [comment]
Would be nice to add opus as download option too then  
I think you need the muxed video to play it back(?), but when only downloading the audio stream, this would be great

**Comment by theScrabi** [comment]
Hm that should be changed.
