### ISSUE TITLE
Add to playlist results in flashing if no playlist created before

### ISSUE THREAD

**Issue by vkay94** [TeamNewPipe/NewPipe#4339]
### Version
- v0.19.8 / 0.20.0 RC

### Steps to reproduce the bug
1. Do a clean install or delete all created local playlists.
2. Search for a stream and long press on it to open the menu.
3a. Choose "Add to playlist" (or whatever it is called in the English version) or
3b Schedule the stream into the background player and click on the "Add to playlist"-button in the toolbar (more clearly visible)

### Expected behavior
The "create new playlist"-dialog should appear directly.

### Actual behaviour
**UI**: Before the actual dialog is visible there is a flash (sometimes)
**Code**: The app opens `PlaylistAppendDialog` and inflates the view. If no playlist exists it calls `dismiss` and opens `PlaylistCreationDialog`.

**Comment by Stypox** [comment]
@vkay94 since you already investigated where the bug lies, would you consider also fixing it? Thank you in advance ;-)

**Comment by vkay94** [comment]
@Stypox Alright, I'm looking into it, but it may take some time since I'm quite a noob at RxJava (I'm more experienced at Kotlin's Coroutines regarding reactive programming) :)
