### ISSUE TITLE
buffer bar not showing buffer position

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#4343]
### Version

- 0.19.8
- 0.20.0 RC

### Steps to reproduce the bug

the buffer bar does not update buffer position unless you interact with the player such as skipping.

this is to say:  even if the video is already 20s buffered ahead, the buffer bar will not show it unless you tab one of the player buttons such as skipping backwards

### Expected Behavior
to show and update buffer regardless of user's interaction.

**Comment by avently** [comment]
What do you mean by saying buffer bar?

**Comment by opusforlife2** [comment]
Seekbar. The buffered section only seems to update when the thumb reaches the end of the currently buffered section, even though we can see that the video is already buffered beyond the current section (you can skip to a point beyond the current section and it will instantly play, not buffer).

**Comment by avently** [comment]
@opusforlife2 but in my case I see how buffered positions goes beyond current time. You can clearly see it on a small video (like 2 minutes). That's why I don't understand the existence of the issue

**Comment by opusforlife2** [comment]
This problem doesn't exist on small videos, yeah. Try a 15 minute video or something. Basically, the buffered section will expand until it reaches the set limit (which seems to be 2 minutes), then it will stop there until the thumb reaches the end of the section. Then it will rapidly expand once again until 2 minutes ahead, and stop again.

Maybe this was done to prevent constantly updating the buffered section and slowing down the player or something. Even so, I think we could get away with updating the section after every 10 seconds or 20 seconds?

**Comment by avently** [comment]
@opusforlife2 
>Then it will rapidly expand once again until 2 minutes ahead, and stop again.

In this place the player starts loading. So like you said it loads fixed part and then loads more and more. It shows buffered position as soon as it loads. What's a problem?

**Comment by opusforlife2** [comment]
For example, let's say you are at 3:00, and the buffered section is shown till 5:00. Now you reach 4:00. The buffered section still shows till 5:00, but if you tap around 5:30, it will load instantly, no buffering (because the video was actually buffered until 6:00 by then). If instead you were to tap around 6:30, the video would buffer, then play. If the buffered section was actually reflecting the buffered part of the video, you should not have been able to seek to 5:30 and get instant playback.

It's not easy to reproduce, but once you see it, you'll know for sure.

**Comment by avently** [comment]
@opusforlife2 did you make this experiment with internet disabled? Like in your example, what happens if you disable internet before choosing 5:30? Will it load or not? I hardly believe in your words because in my case there are no invisibly loaded progress.

**Comment by opusforlife2** [comment]
Wow, I just tried it. If you let it buffer, then wait for one minute, and disable internet, the video keeps playing _past_ the visibly buffered section, but the buffered section never updates. You can tap to seek before and after the buffered section, no problem. The buffered section only updates, as MD77MD says, after you double tap to seek. Try it.

**Comment by MD77MD** [comment]
> Could you check if this is still reproducible in 0.27.4?

its been fixed... closing
