### ISSUE TITLE
Controls missing in android 11

### ISSUE THREAD

**Issue by Jamal-A-Mohamed** [TeamNewPipe/NewPipe#4346]
### Version

19.8
-

### Expected behavior

Have the ability to play/pause or skip

### Actual behaviour

A banner with the title of the video but no controls.

### Logs

![Screenshot_20200928-215830](https://user-images.githubusercontent.com/37128483/94508170-fb8ec900-01d6-11eb-8e77-4995b50b8259.png)

**Comment by opusforlife2** [comment]
This will be fixed by the new release. You can test the RC to check.
