### ISSUE TITLE
New Website for NewPipe

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#435]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

![https://cdn.meme.am/instances/400x/75205884.jpg](https://cdn.meme.am/instances/400x/75205884.jpg)

We need a new Website for NewPipe.

[SkyTube](https://github.com/ram-on/SkyTube/)s website looks like [this](http://skytube-app.com/).
[Our](https://cdn.meme.am/images/400x/332591.jpg) website looks like [this](https://newpipe.schabi.org/).

Anyone interested?

**Comment by ponypower** [comment]
Well, there are already some design ideas: https://github.com/TeamNewPipe/NewPipe/issues/277. With some polishing and adding some "pipeness" I can make it look like a website. On the other hand I can't code to get it work so we will need someone else for that part.

**Comment by wb9688** [comment]
@ponypower: I'd be able to code the site…

**Comment by ponypower** [comment]
@theScrabi the skytube guys use a simple website template from here http://www.scoopthemes.com so no magic there.

**Comment by nate2014jatc** [comment]
I also have some HTML5/CSS3 experience that I'd be willing to loan y'all

**Comment by phly95** [comment]
I personally like the current website, simple, plain, not trying to market or convince you to download it. Of course, if you can improve the website, I'm totally for it.

**Comment by TobiGr** [comment]
Besides my studies, I am a web developer. Therefore, I would be happy to help developing the new website.

**Comment by TobiGr** [comment]
What about a responsive design of the new website?
I just started to implement the good design in #277. Here are two snapshots:
![screenshot full](https://cloud.githubusercontent.com/assets/17365767/22664275/3a732890-ecb0-11e6-8b84-d83e116e939c.png)
![screenshot mobile](https://cloud.githubusercontent.com/assets/17365767/22664277/3a9575a8-ecb0-11e6-94d3-a9a84ef60c65.png)
Is this okay or should I wait until the whole design is finished?

**Comment by theScrabi** [comment]
I think thats cool :)

**Comment by TobiGr** [comment]
@theScrabi: It's out of HTML5, Javascript, JQuery and CSS.
I'm using [Bootstrap](http://getbootstrap.com) so everything is responsive and we won't have to much work to do.

Perhaps it's a good idea to create a new repository so @ponypower can upload the images and everyone like @wb9688 and @nate2014jatc can code, too.

**Comment by theScrabi** [comment]
Deffinetly.

Should we make it public?

**Comment by KeizerDev** [comment]
Yeah, you should. I want to check it out too!

**Comment by wb9688** [comment]
I think this should be public, since NewPipe itself is also public, so
could you create a repo for the website and add write access for us? Btw do
we have a Slack/Gitter/whatever channel to discuss this?

**Comment by TobiGr** [comment]
Yes. Public should be better.

**Comment by nate2014jatc** [comment]
Discord with a trello board could work.
Or there's also Telegram, but that's more for one on one communication

**Comment by TobiGr** [comment]
I think Slack is the most common way to communicate, because Slack's features make developing more comfortable (group and private massages, filesharing, ...).
Is there a Slack channel for NewPipe?

**Comment by wb9688** [comment]
I'd suggest a GitHub repo (`TeamNewPipe/website` or something like that)
with GitHub Issues/Projects and a Gitter channel.

**Comment by theScrabi** [comment]
Well why not.

**Comment by TobiGr** [comment]
I just finished the simple things. Now I need the information / answers to my questions in #277 and everything specific (font-family, font-size, images, ...). After that it won't look as ugly as now ;)

![screenshot full 2](https://cloud.githubusercontent.com/assets/17365767/22709376/dbf62cfc-ed79-11e6-8533-b7d22f79de43.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/17365767/22709375/dbf3a1f8-ed79-11e6-9161-25ae1766a004.png)

**Comment by wb9688** [comment]
@TobiGr: I think we should plan before we start actually working on the
website. So, does everyone agree with my suggestion? If so, could
@theScrabi set it up?

**Comment by TobiGr** [comment]
@wb9688 I agree with you. I just copied an old project and changed the colors and content. So there wasn't much work jet.

**Comment by theScrabi** [comment]
Well I set up a repo so you can send the pull request when ever you want.

**Comment by TobiGr** [comment]
I can't send a pull request because 'access denied'. The repo is empty, so I can't fork it. 
Any suggestions?

**Comment by theScrabi** [comment]
All right i have to do an initial commit.

**Comment by TobiGr** [comment]
@theScrabi Did you do the initial commit?

**Comment by theScrabi** [comment]
No sorry ... um busy.

**Comment by theScrabi** [comment]
[Done](https://github.com/TeamNewPipe/website)

**Comment by TobiGr** [comment]
@theScrabi thanks.
I had lot of other work to do, so I did the pull request only know.

**Comment by theScrabi** [comment]
Ok no problem :)

**Comment by TobiGr** [comment]
@ponypower the main work is done. Now we need all the specific stuff like fonts, colors and graphics. If you want, just upload the Photoshop- / Gimp- / whatever-file and I'll do the rest. Of course, you can also upload all files to the [repository](https://github.com/TeamNewPipe/website).

**Comment by ponypower** [comment]
Awesome! I'm bringing all the stuff the upcoming week!
Important question; do we wanna dump the existing logo or not? ... since the logo has a significant influence on the design overall.

**Comment by theScrabi** [comment]
Uh good question I got used to the logo and I like it, but still we have this "Arbeitsamt" issue :/

**Comment by theScrabi** [comment]
Should we vote for a Logo?

**Comment by ponypower** [comment]
I think we should vote. My idea is that the dev team picks the best ones including the current logo and then make a public vote about it. We would also participate in it ofc.

**Comment by ponypower** [comment]
NewPipe, something, something, NewPipe :)
Basically this is the concept what I thought would be simple enough for a small screen and still look good.
(The idea of using rectangles is coming from the shape of screens/videos. I'm a genius ... I know ... and a masochist.)

There are some things we gotta discuss:
- Do you like it?
- What are the necessary things we want to display on the site. Am I missing anything?
- I need a decent smartphone template ...
- ... and cool mobile screenshots matching the ratio of the template (and no copyright issues)
- I gotta improve the feature logos and fine-tune the font size, the general spacing and everything.

So, what do you guys think?

![mobil weblap-01](https://cloud.githubusercontent.com/assets/16841860/22996498/46c9eb30-f3cf-11e6-828c-fbc416a3ed7f.png)

**Comment by wb9688** [comment]
@ponypower: "Main Features" isn't very readable, because of it's color, I
recommend having it pass at least WCAG 2.0 Level AA (or even better: Level
AAA), which you could check with eg.
http://webaim.org/resources/contrastchecker/.

**Comment by theScrabi** [comment]
@ponypower but it's just awesome as always 👍

**Comment by TobiGr** [comment]
@ponypower It's a good starting point :+1: 

But it could be a little difficult for the costumer to focus on the important things (logo, titile, subtitle / slogan) because the important first view is to busy / full of eye-cathcing elements. 

Even so I thing the idea of using red colred blocks for the header-background is great and they are something you will remeber. To make the header or the second container with rectangles more organized, you could reduce the number of retangles and make them all bigger.

We should also name all features off the app because phone user will always use small devices. After the visited site with a phone, the won't visit the site with an other device. 

It's also difficult to change the whole site for phone sizes, because reducing the browser window on a computer will create the smaller site. And it will be really confusing for costumers when they see to different websites with different information and different images for the same product.

At the moment there is a (not good - but working) design for small devices included in the website in the repository for the website. If you want, have a quick look. Maybe it can help you designing.

**Comment by ponypower** [comment]
@theScrabi Thanks!

@wb9688 Yeah, I'm aware of that. It was a conscious decision since it holds no real information so I use the text just as a design element. I will consider changing it.

@TobiGr 
I admit it's a little too busy. I will make the background of "NewPipe" darker to get a better overall contrast with the text making it less busy. On the other hand the inspiration behind looking chaotic is that noone watches videos in an organised way :)
As I mentioned before I'm going to implement these design elements into the regular screen version so there will be a pretty decent similarity between the appearance of different screen sizes. Don't worry.

Just for the note; everyone has a different taste and everyone would design the website differently. In the end I'm doing it the way I find it good and the way I can, just as always. Cheers!

**Comment by TobiGr** [comment]
@ponypower I'm sorry if it sounded rude to you. It wasn't meant like this.

**Comment by ponypower** [comment]
I've asked for your opinion and you gave me yours. All good. Thanks for the input.

**Comment by nate2014jatc** [comment]
@ponypower, have you posted this on a repo? 
I'd like to have a look at it if I may. 

Have you got it set up as a responsive site?

**Comment by TobiGr** [comment]
@ponypower you mentioned in #277 that 

> the "Main Feature" blocks would be click sensitive bringing up some extra details about the selected feature

Do you have any ideas for the details?

What do you thing about some more pictures of the app at the website?
For example we could include images of the settings, downloads, dark mode (which could be mentioned as feature, too).

**Comment by TobiGr** [comment]
Here are some screenshots.
First desktop, second tablet, third and fourth mobile. For touch devices additional information in the features container will expand by clicking on them.
Maybe we can join both designs to make a perfect one. For example, I can't find a good way to include the screenshots on small screens :(

![screenshot 4 full](https://cloud.githubusercontent.com/assets/17365767/23086142/b2811a36-f56b-11e6-86c1-2fd289fc9d56.png)

![screenshot 4 tablet](https://cloud.githubusercontent.com/assets/17365767/23086141/b2807964-f56b-11e6-91f0-4f4cc971b5df.png)

![screenshot 4 mobile - 1](https://cloud.githubusercontent.com/assets/17365767/23086140/b2802d7e-f56b-11e6-9498-333a3ea1a253.png)

![screenshot 4 mobile - 3](https://cloud.githubusercontent.com/assets/17365767/23086143/b293d8e2-f56b-11e6-89fd-76f075f432c3.png)

**Comment by TheAssassin** [comment]
The look itself is nice. It's getting closer to "done" with every commit. But it doesn't appear too professional yet, there's a few naming issues (e.g. it is F-Droid and not FDroid), a lot of half sentences, inconsistent capitalization (especially in the "main features") and a few other minor problems that I'd like to see fixed before finally deploying the page. Also, until the copyright question is solved ([#3](https://github.com/TeamNewPipe/website/issues/3)), we should not deploy the page.

Regarding project management, I have close this issue and ask you to continue these discussions in the [website repository](https://github.com/TeamNewPipe/website/issues). I am also going to close #277 as it is redundant to the website repository's issue tracker, too.

@ponypower: you might be able to add features of your design to the website repository, too. I like both designs, and a merge would be neat.
