### ISSUE TITLE
Add a sponser Block Feature

### ISSUE THREAD

**Issue by Aadesh001** [TeamNewPipe/NewPipe#4352]
#### Describe the feature you want

YouTube Vanced has now inbuilt sponser block feature. But I don't want to use Vanced as it still requires Gmail account to sign in. Would be very helpful if this feature is enabled in Newpipe.

#### How will you/everyone benefit from this feature?

Sponsers are inbuilt ads in the video, if enabled, the viewer can save time by watching just the content he/she wants

**Comment by opusforlife2** [comment]
Always check for duplicates. #2554.
