### ISSUE TITLE
Mp3 Tags visibility in external Audioplayer

### ISSUE THREAD

**Issue by bovasjohn** [TeamNewPipe/NewPipe#4356]
Mp3 tags should display in external Audioplayer

I am using newpipe for continuous Audioplayback for audiostream i prefer Poweramp music player. 

Currently when i use external Audioplayer it show's "video playback" no details or mp3 tags are visible like newpipe player does.

Please include this feature in next update

Thank you.

**Comment by opusforlife2** [comment]
Try the RC from the pinned issue.

**Comment by bovasjohn** [comment]
> Try the RC from the pinned issue.

What do you mean by that

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/4332

Try the apk from here.

**Comment by Stypox** [comment]
This was fixed in #3178 and will be available in the next version, 0.20.0. You can test a preview of that version by downloading the apk provided in #4332.

**Comment by opusforlife2** [comment]
This was discussed further in IRC. Turns out the feature you want is very hard to achieve through code, for barely any gain. So this is not something that will be added.

**Comment by bovasjohn** [comment]
> This was fixed in #3178 and will be available in the next version, 0.20.0. You can test a preview of that version by downloading the apk provided in #4332.

Hi , I've tried that version problem persists
