### ISSUE TITLE
Ability To Pass A Youtube-DL Command To External Player

### ISSUE THREAD

**Issue by grravity** [TeamNewPipe/NewPipe#4359]
Suggesting an option to pass a youtube-dl command to an external videop layer such as mpv, in hopes to not he restricted on resolution for video+audio. No issues just using mpv on linux which uses youtube-dl, I figure Newpipe could just pass a youtube-dl command to the external player.

**Comment by opusforlife2** [comment]
Why don't you ask in the youtube-dl PR in the mpv-android repo how to do this? Maybe there is a way to configure this within MPV.

**Comment by grravity** [comment]
I would assume I would be able to open links in mpv, the issue is using Newpipe alongside it? Otherwise I'd need to copy and exit and open mpv and paste in every single Youtube video url into mpv which is extremely tedious.

**Comment by Stypox** [comment]
@grravity then this is an issue with mvp, if it does not support sharing links to it

**Comment by opusforlife2** [comment]
You can just share the video to MPV. It shows up in the Share Sheet along with Newpipe.

**Comment by grravity** [comment]
Mpv seems to crash when sharing using the share menu, either way it would be nice if we could have an option so when newpipe is set to use external player, it just passes the command to mpv. It'd be more seamless. Again, I (think, I could be wrong) this would fix the issue with shit support for video resolution and audio. For example currently external player limits video to 480p on some videos, no issues with youtubedl though.

And yes mpv on android does support opening url's.

**Comment by opusforlife2** [comment]
> Mpv seems to crash when sharing using the share menu

That's an MPV problem. Try the MPV build from Nanolx's F-Droid repo instead. That works perfectly fine for me.

**Comment by Stypox** [comment]
Closing as this is not an issue with NewPipe, and we do not want to create custom code to handle any random external player out there.

**Comment by grravity** [comment]
My original point was in attempt to fix the issue with external players basically being unable to play videos. I don't understand the point of even having that option if it can only play videos at 360p with audio.
This would've been a workaround, could a toggle not be added that just passes the youtube link to whatever external player a user chooses when they click on the video for more seamless integration?

**Comment by opusforlife2** [comment]
That toggle is called the Share button. And it works perfectly for me with MPV and youtube-dl.

**Comment by grravity** [comment]
Except it takes 3 extra button presses and searching for the mpv icon within the share menu amongst all other apps.

**Comment by opusforlife2** [comment]
Wut? No. You long press on the video, then use Share from the menu. That's what I do.

**Comment by grravity** [comment]
> 
> 
> Wut? No. You long press on the video, then use Share from the menu. That's what I do.

Yes, and then that opens the Android share menu, in which you have to find the mpv amongst all other apps and click it. It's essentially extra steps that could be compacted into one.

We literally have an option to use an external player, why can't that do exactly what this is doing? All it would do is automatically pass the link directly onto the app of choice, so users can just click the video in newpipe and it brings up whatever player and plays it, instead of needing to go through the share menus. It's far more convenient and after many videos it's a PITA to click the share option, dig through all the apps and find mpv. Again the external player option already exists to just click play in newpipe and opens in mpv.. The issue is it's limiting on what quality it provides for some reason. However when going directly through the link, it is not.

**Comment by opusforlife2** [comment]
Modifying the external player setting to work this way would break existing functionality. That is the issue. You can either have the setting pass the stream (like it currently does) or pass a simple link.

**Comment by grravity** [comment]
Could a toggle not just be added to pass the link however? I fail to understand why it would conflict with the external player setting if it was added as it's own thing, and I can't imagine it'd be much to implement?

Is there any specific reason we are passing the stream instead of just the link right now? Because it seems extremely limiting.

**Comment by opusforlife2** [comment]
Because we don't know what media app the user is using. If we just pass a link and the app doesn't know how to handle it, then that's breaking functionality for the user.

Regarding a separate toggle, Stypox has already replied above.
