### ISSUE TITLE
"Couldn't decrypt video-url-signature" 

### ISSUE THREAD

**Issue by Denoxx** [TeamNewPipe/NewPipe#436]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Since today I am not able to watch any videos anymore. The search works fine, but as soon as I click a video (no matter which one) an error-message pops up saying something like "Couldn't decrypt video-url-signature". It's german so thats only a rough translation.

It then just keeps loading but nothing ever happens. Yesterday evening everything was working fine, I also rebooted the phone, nothing changed. Maybe something on Youtube's side has changed?

**Comment by Denoxx** [comment]
![screenshot_20170131-234924](https://cloud.githubusercontent.com/assets/25468737/22487971/f07d62f4-e80f-11e6-9484-022a1dec5fc7.png)

**Comment by erenkibar** [comment]
I am having the same problem. Probably there is a change with youtube urls.
