### ISSUE TITLE
Overlapping fonts

### ISSUE THREAD

**Issue by iamthelara** [TeamNewPipe/NewPipe#4363]
![02_10_20_14_54_09](https://user-images.githubusercontent.com/50659607/94909299-97168700-04c0-11eb-85bb-427ef0fc6b0e.jpg)

### Version 0.20.0 RC4 even i tried with stable version 0.19.8

-

**Comment by opusforlife2** [comment]
That's a custom font, right? Isn't this a duplicate of #1292?

**Comment by iamthelara** [comment]
There is no costum font. Problem is same as you mentioned and my device is Samsung S8. Help me

**Comment by opusforlife2** [comment]
Check #1008.

**Comment by wb9688** [comment]
This is indeed a duplicate and happens when you set font size higher than the default. Please look if there already is an existing issue before creating a new issue.
