### ISSUE TITLE
Setting "Minimize on app switch: Minimize to popup player" should not change behavior of Close button at the end of a video

### ISSUE THREAD

**Issue by mrbob55** [TeamNewPipe/NewPipe#4368]
### Version

- 0.19.8

### Steps to reproduce the bug

1. Go to Settings -> Video & audio -> Minimize on app switch -> Minimize to popup player.
2. Play a video and go to the end. Let the end screen appear.
3. Click the <kbd>Close</kbd> button in the center of the screen.

### Expected behavior

The video should not be popped out. It should be closed, just as when using the back button.

I don't think the behavior of the <kbd>Close</kbd> button should be impacted by this setting.

### Actual behaviour

The video is popped out to the popup player.

### Screenshots/Screen recordings

I recorded a video. First I show the usual behavior when the setting is set to "None". Then I change the setting and show how the video pops out.

[newpipe.mp4.zip](https://github.com/TeamNewPipe/NewPipe/files/5320755/newpipe.mp4.zip)

### Logs

N/A

**Comment by opusforlife2** [comment]
The button has been removed entirely in the upcoming release. Try this with 0.20.0 after it comes out.
