### ISSUE TITLE
{feat req} long press on item listed opens video's menu 

### ISSUE THREAD

**Issue by tassoman** [TeamNewPipe/NewPipe#437]
After a search, as user I would like to long press a video in listed results in order to obtain video's menu with : open, share, copy URL, download options

If you think it's a good idea, please upvote ☺️

**Comment by opusforlife2** [comment]
Fixed already.

**Comment by opusforlife2** [comment]
Added already.

**Comment by wb9688** [comment]
@opusforlife2: Well, downloading from there isn't possible yet

**Comment by opusforlife2** [comment]
I think that part is invalid? Downloading requires fetching all the streams, which in turn requires the video info that is loaded upon opening. Same difference.

**Comment by opusforlife2** [comment]
Although I suppose if Stypox's list item expansion feature is implemented, you could directly open the download menu from there, though it will still take time for the details to be fetched.

**Comment by wb9688** [comment]
@opusforlife2: That's not different from playing something from there

**Comment by Stypox** [comment]
There are other feature requests requesting fast download actions: #2171
