### ISSUE TITLE
No media controls in Android 11

### ISSUE THREAD

**Issue by heyitswither** [TeamNewPipe/NewPipe#4373]
### Version

- 0.19.8

### Steps to reproduce the bug

Update to Android 11, Start something playing in the background on newpipe, bring down the notification bar, see there is no pause/back/forward/etc in the media controls.

### Expected behavior

I expect there to be pause, back, forward, etc media controls in the notification area.
### Actual behaviour

![Screenshot_20201003-100639](https://user-images.githubusercontent.com/26576706/94997663-8407c380-0561-11eb-91cf-4fab451a6380.png)
![Screenshot_20201003-100647](https://user-images.githubusercontent.com/26576706/94997667-85d18700-0561-11eb-9b51-ecda2032385f.png)

**Comment by opusforlife2** [comment]
Missed the pinned issue?
