### ISSUE TITLE
New 0.20 UI messes up experience for Android TV/FireTV users

### ISSUE THREAD

**Issue by Pentaphon** [TeamNewPipe/NewPipe#4384]
### Checklist

- [x ] I am using the latest version. 
- [x ] I checked, but didn't find any duplicates of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

The new UI is very touch-friendly and great for those screens but for people using a remote on Android TV/FireTV, the new UI creates notifications you don't want, is harder to watch in fullscreen, and creates a bottom bar at the bottom of your TV. 

There needs to a way to detect that you're using Newpipe on a TV device and simplify/optimize the UI for those devices instead of having the new touch UI show up and mess up the experience for people using a remote control on a TV.

**Comment by opusforlife2** [comment]
This is more of general feedback instead of a bug report. If you have anything specific in mind you want implemented or a specific issue you're facing, then open an issue so we can track it. Otherwise, come on IRC and we can discuss possible scenarios for Android TV.

**Comment by Pentaphon** [comment]
> This is more of general feedback instead of a bug report.

I disagree. The new 0.20 UI basically broke the way Newpipe works on Android TV and it has to be corrected so that users can enjoy Newpipe on all their devices with the appropriate UI elements. I think this issue should be left open so that it can be addressed with a solution that fixes the experience for people who use Newpipe on their TV, which is just as appropriate for Newpipe as any other device. 

@TobiGr and @Stypox reviewed the initial Android TV support. What do they think of how the new UI has affected the use of Newpipe on AndroidTV/FireTV?

**Comment by opusforlife2** [comment]
> creates notifications you don't want

> is harder to watch in fullscreen

> creates a bottom bar at the bottom of your TV

You mention 3 things that matter for issue tracking. Make a bug report for each of them. And if you have possible solutions/alternatives in mind for them, mention those, too. If not, that's fine as well; someone else will chime in.

If you have a 4th and 5th thing in mind, you're welcome to open issues for them too.

**Comment by Pentaphon** [comment]
> You mention 3 things that matter for issue tracking.

Those 3 things (and possibly more) are just a summary of how the new UI ruins the experience for people using a TV box. They should be grouped together because all of them need to be addressed before Newpipe can be used on a TV box without issues.

**Comment by opusforlife2** [comment]
Sure. I've created a new project to track Android TV regressions/issues involving the Unified UI. Now we can put bug reports and feature requests in them. ;)

https://github.com/TeamNewPipe/NewPipe/projects/18
