### ISSUE TITLE
Wiedergabe Player in app

### ISSUE THREAD

**Issue by leminsc8er** [TeamNewPipe/NewPipe#4386]
Es wäre super wenn man über die app den Wiedergabe Player öffnen könnte, sollte man eine Video im Hintergrund (als Audio) abspielen. Derzeit kann man den Player nur über den Android Benachrichtigung öffnen, sodass er in der App im Vollbild angezeigt wird.

**Comment by opusforlife2** [comment]
Duplicate of #3515.
