### ISSUE TITLE
Fullscreen in portait is misisng 

### ISSUE THREAD

**Issue by baraa272** [TeamNewPipe/NewPipe#4389]
Fullcreen in portrait mode is missing or button not found 

![Screenshot_20201004-231535](https://user-images.githubusercontent.com/32843097/95026102-94ba5580-0697-11eb-8fdb-0005b115035c.png)

**Comment by Stypox** [comment]
You have autorotation enabled, so just rotate your phone ;-) 
This is intended behaviour

**Comment by opusforlife2** [comment]
@baraa272 Read the blog post. You'll get to know other things as well.
