### ISSUE TITLE
Be able to reset a played video and/or delete the watch history for a video

### ISSUE THREAD

**Issue by e-edgren** [TeamNewPipe/NewPipe#4393]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I want to reset the playback or remove the watch history for only one video that I have long-pressed on from a list (for an example, the subscription list)

#### How will you/everyone benefit from this feature?
There will be less videos showned as not completely watched from lists.

**Comment by Stypox** [comment]
You can already go to history and delete videos. Doesn't that suit you? And if you don't want to see the progress bar you can disable that, too.
If none of these things suit you, could you explain better why you would really need such a feature?

**Comment by e-edgren** [comment]
Yeah, but if you delete a video from history, the progress bar are still there. I don't want to disable the progress bar since I find it useful when I have to stop watching a video because something else came up (like, when a friend show up).

I want to reset the playback time (progress bar) on watched videos (and not completely watched videos) from the long press context menu on a video on for an example the What's New tab.

**Comment by Stypox** [comment]
You still did not explain why this would be useful

**Comment by e-edgren** [comment]
If you start to watch a video and maybe 30% in of the video think, "blergh, this stinks" and don't want to watch it anymore, you can just reset the playback and be done with it. No more annoying "hey, you've not finished watched this video" in the feed.

**Comment by Stypox** [comment]
Thank you for explaining further ;-)
Adding another action to the long-press menu is not an option, since there are already too many and this option would probably be unused by most people. As a workaround you can just seek to 0:00 before closing the video and you will get the result you want.
Though removing a video from the watch history should definitely also remove the watch time, this is a bug that needs fixing

**Comment by Stypox** [comment]
@e-edgren please test the apk in #4413

**Comment by e-edgren** [comment]
I have now tried the APK and the bug seems to be fixed.

I started a random video, skipped to middle of it, went back, changed tab and then back again to make sure the progress bar were there for that videon. It was. Went to the watch history and deleted the video from there and went back again. The progress bar was gone.
