### ISSUE TITLE
What's New: Feed update

### ISSUE THREAD

**Issue by blshkv** [TeamNewPipe/NewPipe#4395]
Hi, I would like to suggest for additional feature which wasn't addressed at the following bug report previously:
https://github.com/TeamNewPipe/NewPipe/issues/3784

To me, "What's new" screen is the main tab and I need it updated on startup. That's not the case currently.
Additionally, that tiny "reload" icon with circle arrow is really TINY. It's hard to press it. 

Can you update that tab on start up (can be optional in settings) and add "screen pull down" feature to duplicate that tiny refresh button?

Thank you for your great work!

P.S. I do have "Feed update threshold" set to "always update" but it doesn't update feeds automatically

**Comment by opusforlife2** [comment]
Don't just delete the template. It is given for a reason. In your case, you didn't check for duplicates. #3329.
