### ISSUE TITLE
"Download" doesn't use the specified location, or name the file correctly

### ISSUE THREAD

**Issue by epitron** [TeamNewPipe/NewPipe#44]
I noticed that the download feature has an issue: it ignores the directory in the settings (always puts it in the `Download` dir), and always names the file `videoplayback` (with no file extension).

(This might be related to #42)

I see that you're using `setDestinationUri` to specify the destination/filename. I tried a few other approaches:

``` java
request.setDestinationInExternalFilesDir(context, null, title + suffix);
request.setDestinationInExternalPublicDir(null, title + suffix);
request.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, title + suffix);
```

None of them worked.

I'm an Android noob, so I'm not sure what's going wrong. Any ideas?

**Comment by theScrabi** [comment]
Not yet. I also noticed, when downloading music NP only downloads .webm, even if I tell it to download m4a. 
So I think we should go away from the android downloader approach.
I don't know if it was better if we had our own downloader in NewPipe, but it had two advantages. 1. Downloads would not show up in the android downloader 2. We could make a download history and 3. We had better control over it.

**Comment by ata2001** [comment]
I'm not a coder, but you can't make a dependencie,  for an existing download manager?

**Comment by epitron** [comment]
If you can't get the android downloader to work, then I guess the only solution is your own downloader.

I like the android downloader, personally, because it allows you to use alternative download managers (like ES File Manager). It gives a better download progress meter, and lets me open it in different apps.

**Comment by theScrabi** [comment]
Hm well actually... i think we could stick to the download manager. But i think its more important to make a proper UI that remembers and displays the downloaded files, and responds to download cancellation.

**Comment by epitron** [comment]
Heh, yeah... The default downloader does technically do that via the notification screen, but it's not great.

**Comment by theScrabi** [comment]
We may have to add the ability to use other methods than the build in download. I noticed that the default downloader can only access internal memory. It can't access external memory like the sdcard.

**Comment by timofonic** [comment]
Aren't there a replacement for the official download manager? I broke it after massively removing Google crap and lots of other ones on my phone.

**Comment by theScrabi** [comment]
There are. You can even download thinks directly. This is why I want to implement several methods for downloading.

**Comment by timofonic** [comment]
Can you please elaborate more about it, please?

 Are there one that replaces and disguises to the official one, yet is more similar to Aria2 and jdownloader? ADM is okay, but is weird to use.
