### ISSUE TITLE
[Feature request] Add option to disable video autoplay

### ISSUE THREAD

**Issue by ofiala-a51** [TeamNewPipe/NewPipe#4400]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I generally don't like autoplay, which is why I have liked the way pre-0.20.0 NewPipe worked. This is a feature request to bring back the old behavior so that I don't have to keep NewPipe at 0.19.8.

#### Is your feature request related to a problem? Please describe it

Autoplaying videos is annoying as hell, especially since I sometimes just want to take a look at video description/comments, etc.

#### How will you/everyone benefit from this feature?

Users will be able to choose their preferred behavior, meaning users that dislike autoplay won't be forced to have autoplaying videos.

**Comment by opusforlife2** [comment]
Settings > Video and Audio. Scroll to the bottom section and change Autoplay to Off.

**Comment by opusforlife2** [comment]
Make sure you read the release blog post. You'll get to know other cool things too.
