### ISSUE TITLE
How to share videos without playing the video in version 0.20.0 interface?

### ISSUE THREAD

**Issue by annada-behera** [TeamNewPipe/NewPipe#4401]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Click on any video reach the details page.

### Actual behaviour
There is no share icon. It used to be in the top bar in version < 0.20.0 but that to bar has disappeared. The only way to see that share icon is to play the video and the share icon appears in OSD.

### Expected behavior
Put the share icon somewhere on details page instead of OSD.

**Comment by opusforlife2** [comment]
Follow #4039.
