### ISSUE TITLE
Add link "play in external player"

### ISSUE THREAD

**Issue by Wiredframe** [TeamNewPipe/NewPipe#4402]
The new update is awesome. There's one thing I'm missing though. I'm using Vega Cast as an external player to play videos on Chromecast. But I don't want to permanently enable the "use external player" option. 

I'd rather like to have a "play in external player" link besides the "share" and "open in browser" links. Or any other workaround to be able to occasionally use an external player.

**Comment by opusforlife2** [comment]
Related: #4039.

**Comment by avently** [comment]
@Stypox do you want to implement a feature we have talked about? It will fix this issue too

>Maybe long click on play in mini player can be bound to showing alertDialog with possible options like audio, video, popup, external player, etc. And it can work like this even with currently playing stream and allows to switch players. I think it's useful and interesting feature. If you want, you can create it:)

**Comment by opusforlife2** [comment]
@Wiredframe Added your proposed button to OP in #4039.
