### ISSUE TITLE
last update features missing

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#4407]
this app is great because it gives you features that YouTube doesn't. Now where did the full screen and rotation controls go?

**Comment by Stypox** [comment]
If you have autorotation active on your phone, there is no point in showing a fullscreen button. If you disable autorotation then the fullscreen button will be there

**Comment by hp8wvvvgnj6asjm7** [comment]
![Screenshot_2020-10-06-06-47-40](https://user-images.githubusercontent.com/45887282/95160069-e77f3480-079f-11eb-86f7-e1d2b0b30b6f.png)

@Stypox 
But the rotation button disappeared

**Comment by opusforlife2** [comment]
Read the blog post, yet? It has all the details about the changes.

**Comment by hp8wvvvgnj6asjm7** [comment]
@opusforlife2 
So I can watch a video in full screen in vertical ?

**Comment by opusforlife2** [comment]
Yup. Try it.
