### ISSUE TITLE
"Open in browser" from playback page in 0.20.0

### ISSUE THREAD

**Issue by ltlnx** [TeamNewPipe/NewPipe#4411]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

In the previous versions, there is an "open in browser" link in the menu of the playback page. However it's gone in 0.20.0.

#### Is your feature request related to a problem? Please describe it

I use the function often (to reply to comments)

**Comment by Stypox** [comment]
You can access it in the miniplayer submenu

**Comment by ltlnx** [comment]
I see, thanks for the quick reply!
