### ISSUE TITLE
Audio Player

### ISSUE THREAD

**Issue by Oizaro** [TeamNewPipe/NewPipe#4419]
Tapping on notification, after tapping on "background button" under a video being played, will open the audio player.

Shouldn't this avoided with unified players?

**Comment by Oizaro** [comment]
@Stypox @avently

**Comment by avently** [comment]
Why do you want it to be avoided?

**Comment by Oizaro** [comment]
> Why do you want it to be avoided?

Because:

1) This player is bugged: if you try to make the closing app gesture, time cursor will move.

2) It's redundant, there is already (unified) video player.

**Comment by avently** [comment]
@Oizaro 
1. Show a screenrecord
2. Without this queue you'll not be able to control background (audio) playback and its params (speed, stream position, etc)

**Comment by Oizaro** [comment]
> @Oizaro
> 
> 1. Show a screenrecord
> 2. Without this queue you'll not be able to control background (audio) playback and its params (speed, stream position, etc)

1. <img src="https://camo.githubusercontent.com/05261b978f5948672f5dc9cf8e8f26907e343cbe/68747470733a2f2f73342e67696679752e636f6d2f696d616765732f536d61727453656c6563745f32303230303531332d3231313734315f47616c6c6572792e676966">

2. Can't you just move this to notification or video player?

**Comment by opusforlife2** [comment]
1. If the closing app gesture is to swipe up from the bottom, then that's being interpreted as a drag on the seekbar. @avently You already implemented a fix for this in the main player, right?

2. As in tapping the notification should open the main player?

**Comment by avently** [comment]
@opusforlife2 this guy probably doesn't have an android gesture but custom one without displayed navbar. So no fix for this

**Comment by opusforlife2** [comment]
I think I have seen such a thing on Realme phones.

**Comment by Stypox** [comment]
Let's close in favour of #3515
