### ISSUE TITLE
Could not decode video URL signature

### ISSUE THREAD

**Issue by noto10** [TeamNewPipe/NewPipe#442]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I have been getting this error since a day or so ago with 0.8.7 and 0.8.8.

**Comment by kevinf89** [comment]
Same here with 0.8.7 and 0.8.8 from F-Droid, started about the same time

**Comment by Seferi** [comment]
Already solved.. Update is coming soon..

https://github.com/TeamNewPipe/NewPipe/issues/430

**Comment by kevinf89** [comment]
Awesome. Thanks!

**Comment by Wiredframe** [comment]
The build doesn't seem to be on F-Droid and there's also a notice that build failed.

**Comment by theScrabi** [comment]
Yes [here](https://f-droid.org/wiki/page/org.schabi.newpipe/lastbuild_23).

**Comment by Wiredframe** [comment]
Would love to get the new build soon. Great work!

**Comment by hodor22** [comment]
thy for fixing - ove the app and spreding it around my friends and family

**Comment by ledditorandproud** [comment]
Why not upload a compiled apk in the meantime? I want to check out the app but it's been unusable for days. I keep it around waiting for the update, but right now it's just useless.

**Comment by theScrabi** [comment]
You can find a download link on top of the readme.

**Comment by Wiredframe** [comment]
Thanks. But since it's unsigned I can't install it. Will the F-Droid release be available anytime soon?
Thanks in advance!

**Comment by theScrabi** [comment]
I dont know i asked them but im wairing to.

**Comment by windz2009** [comment]
Hello!
You can download working apk here http://4pda.ru/forum/index.php?showtopic=694195&view=findpost&p=58008048
It is my build signed with cert! All is working! Thanx to theScrabi for his great work

**Comment by Wiredframe** [comment]
I'd rather wait for the official build. Thanks anyway.

**Comment by teod0r** [comment]
ждём ебилдов

**Comment by theScrabi** [comment]
`ждём ебилдов` : `waiting ebuilds`
@teod0r English please :)

**Comment by theScrabi** [comment]
Also update is finally online (phuuu) :)

**Comment by tgp1994** [comment]
Excellent news, thank you!

**Comment by Wiredframe** [comment]
Great news, thanks! Finally got the best YouTube app working again :)
