### ISSUE TITLE
Nested comments and a more advanced video search

### ISSUE THREAD

**Issue by Oizaro** [TeamNewPipe/NewPipe#4420]
Such already described in title: would be useful if NewPipe will capable to shows also reply comments, instead of only the main ones.

Same thing for search box, where searching for hours/week/year is still missing.

**Comment by Oizaro** [comment]
@Stypox

**Comment by opusforlife2** [comment]
Didn't check for duplicates? #110 and #2277.

**Comment by opusforlife2** [comment]
You deleted the template entirely. Don't do that in the future.
