### ISSUE TITLE
Hover events trigger a white overlay on Samsungs and other devices

### ISSUE THREAD

**Issue by hipunk** [TeamNewPipe/NewPipe#4422]
### Checklist

- [X] I am using the latest version. 
- [ ] I checked, but didn't find any duplicates of this issue in the repo. This is a duplicate of: #4357 but it doesn't only involve a mouse but also loads of Samsung phones. o_O  
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug and the actual behaviour:

1. Open a video in fullscreen
2. Hover your finger over the screen within a 3cm distance on a Samsung Galaxy S4 or newer. Or use a S-Pen with a Samsung Galaxy Note then hover it over the screen or move Androids mouse cursor using a bluetooth or a USB mouse 
3. A milky white transparent overlay appears over the whole screen, some hover event is apparently being triggered and makes an overlay appear! :)

### Expected behavior

No white overlay.
Suggestion: Show controls when you detect a hover event! It's fine like it was before 0.20 as well.

### Device info

 - Device models affected: GT-I9500, GT-I9506, GT-I9515, GT-I9505, GT-N7000, GT-N7100, SM-G930, SM-G935, probably many more + all devices with bluetooth and USB mice

**Comment by opusforlife2** [comment]
What?
