### ISSUE TITLE
Lock Video Controls

### ISSUE THREAD

**Issue by Nzzyme** [TeamNewPipe/NewPipe#4423]
Hello, I was thinking that it would be a good idea to add a 'lock' icon on the video player so that when we tap on that and enable locking, all the player controls would be freezed so that even when we swipe up on the right side, the volume should not go up, etc.

Similarly, when we tap on the lock icon again to unlock it, the controls should be working again normally.

This is already implemented in many media players like MX Player (for example) and would be good to have it in NewPipe too. Can you please consider this and add this feature?

Thanks

**Comment by opusforlife2** [comment]
You deleted all the check boxes. You were supposed to go through them. One of them was looking for duplicates. And now this issue will be closed because you didn't. #1575 :(

**Comment by Nzzyme** [comment]
Apologies. Let me go through
