### ISSUE TITLE
Add Left to Right Swipe Gesture To Navigate Forward

### ISSUE THREAD

**Issue by Nzzyme** [TeamNewPipe/NewPipe#4424]
Currently, we have swipe gesture controls for Volume and Brightness while watching a video.

Can you please add another swipe gesture so that when we swipe from left to right while watching a video, the video progresses forward according to extent of the swipe and when released, it starts playing from that new position?

This is already implemented in other YouTube players like SnapTube and think it should not be that difficult to implement. Please consider and add this feature.

Thanks

**Comment by opusforlife2** [comment]
Go through the checklist first. Then I'll reopen this.

**Comment by Nzzyme** [comment]
Let this remain closed. I believe this was already raised but still not implemented. 
https://github.com/TeamNewPipe/NewPipe/issues/889

**Comment by opusforlife2** [comment]
Behold! The power of searching for duplicates beforehand. 👍
