### ISSUE TITLE
Add option for embed subtitles instead of downloading them separately

### ISSUE THREAD

**Issue by PrivatePP** [TeamNewPipe/NewPipe#4426]
### Checklist
- [ ] I checked, but didn't find any duplicates of this issue in the repo. I've found a similar request (#2365) but it wasn't very clear/detailed.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Add the possibility to add the srt file in the mp4, so you can enable/disable it from the player instead of having to download the file separately.

#### Is your feature request related to a problem? Please describe it

Kinda related. You cannot download subs using the "open" action pop-up (eg. share video on YT > NewPipe).

#### Additional context

This is what the feature looks like in the Videoder action pop-up. It's the app I used to use before NewPipe.
![Screenshot_20201006-162431](https://user-images.githubusercontent.com/68356334/95216499-6b620c80-07f2-11eb-9d73-fdba59416a4e.png)

#### How will you/everyone benefit from this feature?

Right now you have to repeat the download procedures twice (first video, then subs) if you want subtitles, which can be a bit annoying if you want to download multiple subbed videos. It could also potentially **halve the number of files** in a folder (making it easier to browse/organise), which is the main reason I prefer embed subtitles.

**Comment by opusforlife2** [comment]
> I've found a similar request (#2365) but it wasn't very clear/detailed.

But the end result is the same. Our resident downloader dev said it is too much effort for very little gain.

Thank you for checking for duplicates first, though! You rock! 🥳

> Right now you have to repeat the download procedures twice (first video, then subs) if you want subtitles, which can be a bit annoying if you want to download multiple subbed videos.

Follow #2885 for downloading as separate file, but at the same time.
