### ISSUE TITLE
Option to turn off auto-start

### ISSUE THREAD

**Issue by A1S1R** [TeamNewPipe/NewPipe#4428]
### Checklist

- [✅] I checked, but didn't find any duplicates of this issue in the repo. 
- [✅] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [✅] This issue contains only one feature request. I will open one issue for every feature I want to request.

In new version when you click a video it automatically starts. I would like to give us the option to turn this off.

It would be helpful when you accidently click a video.

Thank you in advance 😄

**Comment by opusforlife2** [comment]
Settings > Video and Audio > Autoplay.

Did you not read the blog post? If not, make sure you do. You'll discover many new things.

**Comment by wb9688** [comment]
Settings -> Video & audio -> Autoplay

When creating an issue next time please replace the space in [ ] with a x (like: [x]) to check the checkboxes.
