### ISSUE TITLE
Viewbinding PR opinions

### ISSUE THREAD

**Issue by TacoTheDank** [TeamNewPipe/NewPipe#4429]
Have a question: How does the team feel about PRs that introduce viewbinding into the app? Would they like each class to be its own PR? Or would it be okay to do it by package, or all at once?

You can probably figure out why :^)

**Comment by Stypox** [comment]
Possibly all at once, see #3697
That PR needs to be continued, though we didn't do that before merging unified ui in order not to create conflicts, but now it can be continued

**Comment by wb9688** [comment]
@Stypox: And because of having trouble with certain cases

**Comment by opusforlife2** [comment]
@TacoTheDank Rebased. 👍

**Comment by TacoTheDank** [comment]
@wb9688 @opusforlife2 @Stypox I see. Thank you!
