### ISSUE TITLE
0.8.9 not available

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#443]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

I want to use newpipe, but I can't find the new apk anywhere and the old one doesn't work anymore. Where can I get the new apk for newpipe?

**Comment by Yowlen** [comment]
Please read and follow the contribution guidelines before posting. #442 already answered your question.

**Comment by theScrabi** [comment]
Yes, the [f-droid build](https://f-droid.org/wiki/page/org.schabi.newpipe/lastbuild_23) failed somehow. I'm sorry there happend some more errors the past few days. We are on it.

**Comment by theScrabi** [comment]
All right, it should be fixed by now. Se [here](https://gitlab.com/fdroid/fdroiddata/issues/596).

**Comment by tgp1994** [comment]
@theScrabi Sorry you've been getting a lot of pressure from us, thank you for your hard work and staying on top of this! Looks like it's on F-Droid now to put your update on the repository

**Comment by theScrabi** [comment]
Yea well its not because of you, its also me. I want to see it online my self.

**Comment by theScrabi** [comment]
There is a download link on top of the readme now.
