### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by hjagaty** [TeamNewPipe/NewPipe#4430]
Hi,
   I am right now using your app New youtube which is great app. I have been looking for such app for a long time. Earlier I was using another app called YouTube Vanced. However I found this one having more features and light weight. I have a feature request. Kindly consider it if it is possible to add. I am sure many people will find it useful.

   Due to time limitations and frequent distractions people watch video in parts and most of the time not in full.  If you can keep some kind of book mark option which will store the time that has been watched, so that people can continue from there the next time they open the same video. This feature exists in apps like tubi TV etc.

**Comment by Stypox** [comment]
This feature already exists: make sure you have it enabled in
Settings -> History & Cache -> Positions in lists

Then NewPipe will show you how long you watch every video and automatically resume.

**Comment by opusforlife2** [comment]
Also, make sure you use the bug report or feature request template next time. Don't open a blank issue.

**Comment by opusforlife2** [comment]
> This feature already exists: make sure you have it enabled in
Settings -> History & Cache -> Positions in lists

@Stypox That setting doesn't work. The user needs to enable Watch History. See https://github.com/TeamNewPipe/NewPipe/pull/2907#issuecomment-667663409 and #4053.
