### ISSUE TITLE
Unable to access Background Player & Notification Seek Issue

### ISSUE THREAD

**Issue by PrimeGinseng** [TeamNewPipe/NewPipe#4433]
**Phone:** Google Pixel 3a XL
**Android ver:** 11 (Sept 5 update)
**Video demo:** https://youtu.be/0s_q1ds7jM4

After the latest update, enqueuing or playing videos in the background makes the playlist inaccessible without overwriting the queue.

Videos are indeed sent to the background, however pressing on the notification area player does nothing, where it used to bring you the queue list.

The only way I have been able to access the list is by playing another video normally, which brings up the in-app player, where the list icon is available, which overwrites the queue. 

There are no controls in the Notification area either, except the seekbar, sometimes. 
Regarding the seek issue: in the notification area, the seekbar accepts input, but upon seeking, will remove the control from being visible.

**Comment by Stypox** [comment]
This is really really really strange, as we had a bunch of people testing this on Android 11 and everything worked fine. I have no idea why the notification would be so broken...

**Comment by PrimeGinseng** [comment]
Here is a video demonstration, if that helps!
https://youtu.be/0s_q1ds7jM4

**Comment by whatlab** [comment]
I had the same problem with Newpipe 0.19.8 after updating to Android 11.
For me the issue was resolved by updating to Newpipe 0.20.0.

Phone: Google Pixel 3a, Android 11 (sept 5)

**Comment by PrimeGinseng** [comment]
> 
> 
> I had the same problem with Newpipe 0.19.8 after updating to Android 11.
> For me the issue was resolved by updating to Newpipe 0.20.0.
> 
> Phone: Google Pixel 3a, Android 11 (sept 5)

Huh... You know, I just assumed I was on the latest version because I checked F-Droid for an update and there was none. After installing NewPipe 0.20.0 from the Releases page the issue is resolved. That's my bad. Gonna get my releases from here from now on.

Thanks!

**Comment by opusforlife2** [comment]
... This is why you're supposed to fill the issue template.

**Comment by whatlab** [comment]
> Huh... You know, I just assumed I was on the latest version because I checked F-Droid for an update and there was none. After installing NewPipe 0.20.0 from the Releases page the issue is resolved. That's my bad. Gonna get my releases from here from now on.

Updates will arrive faster in F-Droid if you add Newpipe's repository to F-Droid.
See [https://newpipe.schabi.org/FAQ/tutorials/install-add-fdroid-repo/](https://newpipe.schabi.org/FAQ/tutorials/install-add-fdroid-repo/) for more information.

> Thanks!
You're welcome.
