### ISSUE TITLE
background player randomly pauses

### ISSUE THREAD

**Issue by nussfell** [TeamNewPipe/NewPipe#4435]
(Ping opus for the log)

### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open a video (I tried different music videos that are about 3 minutes long) in the background player and wait.

### Actual behaviour

The background player randomly stops playing and tries to load the stream but fails. This happen usually in the first or second minute of the video. The GUI looks similar to a lost internet connection (an hourglass instead of a play button in the notification and an endless circle on bottom half of the player page) but mine was working fine. No error message appears. When I close the player and the app and reopen it, everything works fine for a while and then it happens again. 

### Expected behavior

I expect the player to play the video properly without stopping (unless I press pause).

### Logs

NewPipe does not show an error message at all but I attached a log made with logcat.

### Device info

 - Android version/Custom ROM version: stock android 8.1
 - Device model: Moto G5

**Comment by opusforlife2** [comment]
Thanks!

**Comment by AnotherLife** [comment]
It's not just the background player, it happens when in popup, too. It just stops. When it happens I change the resolution from 360p to 240p and it reloads and continues from where it was.

**Comment by marmeladema** [comment]
I can confirm it also happens on Android 11 with a Pixel 3. All the videos I tried to listen to in background mode randomly stop. I cannot continue playback, I have to switch videos.
I haven't tried foreground / popup mode.
Since the last updates, newpipe is basically not usable anymore :-/

Is there anything we can do to help fixing this bug? I have very little knowledge about android app development but with the right guidance I should be able to provide logs or other kind of traces.

**Comment by Charred-Almonds** [comment]
I'm having the exact same issue. The only way to resolve it is to reload the video and press the BG play button, but that also clears the queue :(
![20201007_182200](https://user-images.githubusercontent.com/71480987/95401348-3a550b00-08ca-11eb-8300-ffabf77356d6.jpg)

**Comment by wb9688** [comment]
@nussfell: In the log I see that you're using NetGuard. Could you test if it happens without?

**Comment by avently** [comment]
@wb9688 no, I don't have an idea. I've no access to my PC so can't check.

**Comment by Stypox** [comment]
#4432

**Comment by nussfell** [comment]
@wb9688 it still happens without NetGuard

**Comment by opusforlife2** [comment]
@nussfell Can you post a screen record?

**Comment by nussfell** [comment]
@opusforlife2 I tried it once without NetGuard and it stopped but I somehow can't reproduce it while recording, it just works

**Comment by opusforlife2** [comment]
Then maybe you should keep recording your screen. It scares away the bugs. :P

On a serious note, maybe use the screen recorder every now and then while you're using Newpipe? You're bound to come across it again, I'm sure.

**Comment by nussfell** [comment]
yeah, I'm sure too :) also, it looks like the picture posted by @Charred-Almonds in this issue
