### ISSUE TITLE
Fool YouTube ads system by loading but not showing ads

### ISSUE THREAD

**Issue by Piruzzolo** [TeamNewPipe/NewPipe#4437]
#### Describe the feature you want
Since NewPipe reads the page html, would it be possibile to load the ads but not showing them, somehow fooling YT ads system? I mean, let them load/play but somehow "in the background", without actually showing them to the user

#### How will you/everyone benefit from this feature?
This way creators get their money but the user is not bothered with ads

**Comment by wb9688** [comment]
That's a bad idea
