### ISSUE TITLE
It loads up a different website when opening up the update

### ISSUE THREAD

**Issue by Edholland123** [TeamNewPipe/NewPipe#4438]
When I open up New Pipe on my phone I get a notification saying "New update 20.0" I click on it and it sends me to a different website which really bugs me because I want to update the app please fix this and thank you 

Mr schabowskis

**Comment by opusforlife2** [comment]
Which website?

**Comment by Edholland123** [comment]
All sorts of websites that I go to

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Edholland123** [comment]
For example I go to Amazon it will load me up on the Amazon website.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by opusforlife2** [comment]
Newpipe has nothing to do with that. It just passes a link to the Releases page to your default browser (Chrome or whatever you use). Check your browser settings to see what's going wrong.

**Comment by Edholland123** [comment]
Ok thank you

Mr schabowskis

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wb9688** [comment]
@opusforlife2: We link directly to the .apk and Chrome doesn't open that for "security"
