### ISSUE TITLE
[feature suggest] explicitly GPU acceleration on manifest - '<application...' level

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#4439]
adding `android:hardwareAccelerated="true"`

to 

```xml
 <application android:allowBackup="true" android:appComponentFactory="androidx.core.app.CoreComponentFactory" android:banner="@mipmap/newpipe_tv_banner" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:logo="@mipmap/ic_launcher" android:name="org.schabi.newpipe.App" android:requestLegacyExternalStorage="true" android:resizeableActivity="true" android:theme="@style/OpeningTheme">
```

On application level, please!

<a href="https://webcache.googleusercontent.com/search?ie=UTF-8&q=cache:https%3A%2F%2Fdeveloper.android.com%2Fguide%2Ftopics%2Fgraphics%2Fhardware-accel">https://webcache.googleusercontent.com/search?ie=UTF-8&q=cache:https%3A%2F%2Fdeveloper.android.com%2Fguide%2Ftopics%2Fgraphics%2Fhardware-accel</a>

The reasoning (TL;DR) is that if a user choose to force GPU processing for all apps rendering it will enhance / lower CPU on the overall app usage. This is quite known trick (known enough to enter the the developers' docs, just a small trick of making apps run smoother on many platforms). see: <a href="https://gist.github.com/eladkarako/5694eada31277fdc75cee4043461372e#file-tweaked_default-prop-L54-L55">https://gist.github.com/eladkarako/5694eada31277fdc75cee4043461372e#file-tweaked_default-prop-L54-L55</a>.

<blockquote>Beginning in Android 3.0 (API level 11), the Android 2D rendering pipeline supports hardware acceleration, meaning that all drawing operations that are performed on a View's canvas use the GPU. Because of the increased resources required to enable hardware acceleration, your app will consume more RAM.

Hardware acceleration is enabled by default if your Target API level is >=14, but can also be explicitly enabled. If your application uses only standard views and Drawables, turning it on globally should not cause any adverse drawing effects. However, because hardware acceleration is not supported for all of the 2D drawing operations, turning it on might affect some of your custom views or drawing calls. Problems usually manifest themselves as invisible elements, exceptions, or wrongly rendered pixels. To remedy this, Android gives you the option to enable or disable hardware acceleration at multiple levels. </blockquote>

Virtually no effort.

**Comment by opusforlife2** [comment]
@eladkarako I got no notification of this issue being opened. Have you blocked me? If so, why?

**Comment by Stypox** [comment]
Quoting from [this SO](https://stackoverflow.com/questions/52091715/setting-androidhardwareaccelerated-true-in-activity-or-in-application):

> Hardware acceleration is enabled by default so you don't have to set it unless you need to disable it.

So it is already enabled, and there is no need for any action

**Comment by eladkarako** [comment]
arrrggg... that's a mistake (－‸ლ).. \*sign\*. messed with cron automation with GitHub API and my user meta data, just noticed... unblocking (manually)...
