### ISSUE TITLE
Video doesn't play on foreground with 720p, loading icon sometimes even stops.

### ISSUE THREAD

**Issue by allendema** [TeamNewPipe/NewPipe#4440]
### Checklist

- [×] I am using the latest version. 
- [×] I checked, but didn't find any duplicates of this issue in the repo. 
- [×] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [×] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open this [random](https://www.youtube.com/watch?v=MI7EoM0uVtU&t=0) stream.
2. Choose 720p as video quality.

### Actual behaviour

Stream doesn't start on Foreground with 720p selected as quality.
Pressing Android home button and thus continuing the stream in background works fine.

### Expected behavior

The video to be opened on 720p.

### Logs

[Logcat](https://del.dog/atturfistu.txt) 

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Pixel

**Comment by Stypox** [comment]
I can't find any useful information in the logcat, but I can reproduce the issue. I'll look further into this later, but I suppose it's just one more instance of an unsupported DASH stream

**Comment by opusforlife2** [comment]
@allendema The log seems to suggest you're using MP4. Can you try using WebM?

**Comment by allendema** [comment]
@opusforlife2 That does not resolve it.

**Comment by opusforlife2** [comment]
Oh. That stream is not random at all. @wb9688 this is one of those DASH videos. There is only a 360p and 720p stream. We know 360p and 1080p play correctly, but this rogue 720p has some issue. I can't play it either.

**Comment by Stypox** [comment]
Shouldn't those be blacklisted by TeamNewPipe/NewPipeExtractor#400?

**Comment by opusforlife2** [comment]
If they're not OTF streams, then no. 360p is a known progressive HTTP stream. This 720p is the unknown quantity.

**Comment by Stypox** [comment]
youtube-dl gives these possible formats:
```
139          m4a        audio only DASH audio   50k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
251          webm       audio only DASH audio  116k , webm_dash container, opus @160k (48000Hz)
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
134          mp4        640x360    DASH video  326k , mp4_dash container, avc1.4d401e, 30fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 30fps, video only
18           mp4        640x360    360p  369k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 12.36MiB
22           mp4        1280x720   720p  782k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)
```

So all `DASH video` streams are trimmed by TeamNewPipe/NewPipeExtractor#400, but two normal resolutions remain: `360p` and `720p`, as NewPipe shows. I don't know why the 360p resolution would not work: even exoplayer does not write anything in the logcat (I tested this with an emulator).

**Comment by opusforlife2** [comment]
>  I don't know why the 360p resolution would not work

I don't know either, because as I said, it does work. 🤔

**Comment by xibr** [comment]
> 1. Open this [random](https://www.youtube.com/watch?v=MI7EoM0uVtU&t=0) stream.
> 2. Choose 720p as video quality.
> 

The video cannot be downloaded (720p) using youtube-dl so I don't think it's NewPipe's issue.

**Comment by Stypox** [comment]
@xibr is there a report for this bug on youtube-dl's repo?

**Comment by xibr** [comment]
I think this issue [youtube-dl#3721](https://github.com/ytdl-org/youtube-dl/issues/3721)

```youtube-dl -f 22 https://youtu.be/MI7EoM0uVtU                                [youtube] MI7EoM0uVtU: Downloading webpage                                       [youtube] MI7EoM0uVtU: Downloading MPD manifest
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries```

**Comment by Stypox** [comment]
Oh, then this is a YouTube issue. We should implement automatic fallbacks, though, when a resolution raises an error

**Comment by litetex** [comment]
> We should implement automatic fallbacks, though, when a resolution raises an error

If still required and useful, this would be a new issue.
