### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by shnoah641** [TeamNewPipe/NewPipe#4441]
Background audio player randomly stops and buffers but never starts back up it just stalls out

**Comment by opusforlife2** [comment]
Like #4432 or #4435?

**Comment by shnoah641** [comment]
Yes it is exactly like that and I am on a Galaxy J3 Prime. I do not know how to capture a log file though.

**Comment by opusforlife2** [comment]
We might not need yours. We have two already.

**Comment by shnoah641** [comment]
Ok thanks for your help and hope you find a way to fix it. I love the app interface so far with the update.
