### ISSUE TITLE
"Could not play this stream" after a minute

### ISSUE THREAD

**Issue by oguz-ismail** [TeamNewPipe/NewPipe#4446]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Try playing this video with NewPipe: https://www.youtube.com/watch?v=pPdaqbrCaA0

### Actual behaviour

After a minute or so the player stops and *Could not play this stream* message is shown, if I try to resume it later I'll see the same message over and over. It never plays. I tried wiping cache, metadata, etc but the same thing happened again.

### Expected behavior

The video to play seamlessly to the end.

### Device info

 - Android version/Custom ROM version: Android M
 - Device model: Samsung Galaxy J5

**Comment by Stypox** [comment]
#4432

**Comment by opusforlife2** [comment]
Are we sure? We really need a screen record from all three reporters.

**Comment by Stypox** [comment]
Yes, we are not completely sure, but they seem like really similar issues that all popped up after 0.20.0

**Comment by opusforlife2** [comment]
@oguz-ismail Could you post a screen record, please?

**Comment by dogtopus** [comment]
I'm getting the same issue from a [different video](https://www.youtube.com/watch?v=5uWXfoX1x3A). The background playback freezes after ~1 min. However unlike the mentioned issue there's no hourglass symbol showing. Foreground player immediately shows "could not play this stream" and quits on the same timestamp. Manually skip past the timestamp and immediately get the same error as well. Download works normally. Also I noticed that the logcat was flooded by some decoder error when the bg player freezes.

**Comment by opusforlife2** [comment]
@dogtopus Are you using MP4 or WebM? Can you try the other one?

**Comment by oguz-ismail** [comment]
> @oguz-ismail Could you post a screen record, please?

It really seems like the issue @Stypox linked above. I deleted /sdcard/Android/data/org.shabi.newpipe and it doesn't happen anymore

**Comment by dogtopus** [comment]
@oguz-ismail This fixed the issue for me as well. I only deleted `cache/exoplayer` under the external storage though.

**Comment by opusforlife2** [comment]
@Stypox @wb9688 Shouldn't we add a Clear Cache option, even if just to debug?

**Comment by Flashwalker** [comment]
I'm getting the same.

**Comment by opusforlife2** [comment]
@Flashwalker Tried the RC?
