### ISSUE TITLE
Crash report doesn't work with ProtonMail mobile app

### ISSUE THREAD

**Issue by asereze** [TeamNewPipe/NewPipe#4452]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. The app crashes
2. Press on 'Report this error via email'
3. Select the ProtonMail app

### Actual behaviour
The app only opens up an empty draft. No email address, no subject, no text and no attachments. 

### Expected behavior
To have a draft with data to send and with an address to send it to.

### Device info

 - Android version/Custom ROM version: LineageOS 16.0 (Android 9.0)
 - Device model:  Xiaomi Redmi Note 4X

**Comment by wb9688** [comment]
Where could I find the source code of that crappy app? We do it exactly [as recommended](https://developer.android.com/guide/components/intents-common#Email): https://github.com/TeamNewPipe/NewPipe/blob/14486782dcfb3ac99965b995c1e45c6368c05ce5/app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java#L284-L288

**Comment by asereze** [comment]
> Edit: From looking at their code, I don't immediately see what's wrong there. Are you in fact using the latest version of ProtonMail's app?
Yes, I am.

**Comment by B0pol** [comment]
https://github.com/ProtonMail/proton-mail-android @wb9688

**Comment by wb9688** [comment]
From another look at ProtonMail's code, it seems like it would only fill in the recipient. Are you sure that the recipient is not filled in?

**Comment by asereze** [comment]
> From another look at ProtonMail's code, it seems like it would only fill in the recipient. Are you sure that the recipient is not filled in?

Yes, it isn't. It did fill that in (just that, as you wrote) some time ago, but I don't know if the difference was thanks to an older version of their app or to an older version of NewPipe.

**Comment by AudricV** [comment]
Is it still an issue? Like said in https://github.com/TeamNewPipe/NewPipe/issues/4452#issuecomment-705721192, this should be not an issue from our side but from the ProtonMail Android app.
