### ISSUE TITLE
app freezes when trying to delete popup while another video initializes

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#4454]
![Screenshot_2020-10-08-22-24-58](https://user-images.githubusercontent.com/45887282/95509844-52558900-09b5-11eb-8ad6-bd9abfe24ffc.png)

I was deleting a pop-up, but at the same time the other video loaded. Something strange happened.

**Comment by avently** [comment]
Without screenrecord I can't even imaging what happens here. Could you make it?

**Comment by hp8wvvvgnj6asjm7** [comment]
i can't seem to reproduce it again, i guess i'll do a video immediately next time. thx
