### ISSUE TITLE
Replace menu under arrow button with a dialog

### ISSUE THREAD

**Issue by avently** [TeamNewPipe/NewPipe#4456]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Right now we have to select arrow down button in order to see second line of buttons like subtitles, aspect ratio, open in browser, etc. This is fine until someone will want to show more buttons inside this line. All the buttons from second line should be replaced with AlertDialog or BottomSheet or Popup menu with enabled icons. I'm not sure which one is the best, needs testing to be sure. Popup menu allows to show submenu for subtitles and aspect ratio which is useful.

By making this change we can leave arrow down button but make it working like a scroller to the description. This will allow to tap on it and to see a description even in fullscreen. Once someone make a swipe-to-go-to-description even this button can be removed.

So the proposed look of the buttons in non-fullscreen:
Close video ------------ quality | speed | setup

In fullscreen:
 ------------ quality | speed | setup | arrow down

If the `setup` button will be a three dots icon it should be the last in a row in landscape too.

#### Is your feature request related to a problem? Please describe it

The problem is there are to many buttons. Some users want to add even more buttons. I don't think this UI element like second line with buttons is a great element in the case of many buttons.

#### How will you/everyone benefit from this feature?

We can close many issues after this idea is implemented. Also the player will be much faster in case of view relayout because it will lose some buttons.

**Comment by Stypox** [comment]
@avently I'd keep all of the discussion about this in #1317
