### ISSUE TITLE
"Ask for confirmation before clearing a queue" doesn't work if queue contains only one track

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [TeamNewPipe/NewPipe#4459]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Enable the option "Ask for confirmation before clearing a queue".
2. Add a single track to the background queue (either playing or paused).
3. Play another video in NewPipe normally.

### Actual behaviour
The video starts playing, and background queue is deleted. 

### Expected behavior
A warning "The active player queue will be replaced" should appear. Just because I have only one track in the queue, doesn't mean that I want NewPipe to remove it without warnings.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Pixel 3a

**Comment by avently** [comment]
@nbmrjuhneibkr you or anyone else can remove this line:
https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L2078

And get the behavior you want. I didn't think that one stream is important and shouldn't be replaced.

**Comment by nbmrjuhneibkr** [comment]
Is "just edit the code and build the app yourself from now on" going to be the official fix for this?

**Comment by opusforlife2** [comment]
Don't worry. I'm here to the rescue. 😎 

Sure just that one line @avently? I could open a PR in a few minutes.

**Comment by avently** [comment]
@nbmrjuhneibkr nope, I just showed the place that fixes the problem. Anyone that can make a PR can made a fix based on info I provided. It may be even you. Or @opusforlife2 if he wants.

@opusforlife2, yeah, I think so.

**Comment by opusforlife2** [comment]
Gimme a few minutes.
