### ISSUE TITLE
Once video is finished, pressing the back button opens player repeatedly

### ISSUE THREAD

**Issue by tgp1994** [TeamNewPipe/NewPipe#446]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Currently on 0.8.9 (yay, F-Droid!), although I was seeing this issue while 0.8.8 was working as well.

If you press the back button after watching a video, the player screen closes back to the video info screen, then almost immediately opens the player screen again like I had tapped on the play button. Previously, the player window would just close to the video info screen, then another tap would return to the previous open app.

**Comment by tgp1994** [comment]
It looks like v.0.8.10 has a comment saying this issue was addressed, however it's still present.

**Comment by theScrabi** [comment]
The backbutton problem is not related to that video problem. This bug is not yet fixed sorry.

**Comment by tgp1994** [comment]
I'd like to say that in 0.9, the issue isn't present in the new default player.

**Comment by theScrabi** [comment]
So i think this issue can be regarded as closed.
