### ISSUE TITLE
Display PeerTube search results

### ISSUE THREAD

**Issue by jibe-b** [TeamNewPipe/NewPipe#4461]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

PeerTube is streaming videos peer-to-peer using WebRTC.

There now is a search engine: https://sepiasearch.org/

and one may install their own scraper, index and serve a search portal too, using the code https://framagit.org/framasoft/peertube/search-index

What would be interesting would be that Freetube sends the searched request to a PeerTube search API and displays the results among the results.

You may mutualize with the FreeTube team to implement this once for both projects.

**Comment by mhmdanas** [comment]
Done in https://github.com/TeamNewPipe/NewPipe/pull/5257.
