### ISSUE TITLE
Back button behavior makes no sense

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [TeamNewPipe/NewPipe#4462]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open any list of videos (channel, playlist, search results...)
2. Open a video.
3. Press the back button to return to the list.
4. Play another video from the list.
5. Press the back button again.

### Actual behaviour
NewPipe opens previously played video.

### Expected behavior
Back button should do exactly what it always does in every other app - go back. In this case - go back to the video list.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Pixel 3a

**Comment by opusforlife2** [comment]
The back button has been assigned a new behaviour, which is to go backwards in your video history. This is a new feature. The replacement action for going back to a list is to swipe down to minimise the player.

**Comment by nbmrjuhneibkr** [comment]
Why can't I choose how the back button works? Why am I now being forced to use a "feature" that contradicts common sense? Why not give users more choice?

**Comment by opusforlife2** [comment]
Because we can't have an option for every possible interaction with the app. That will make it unmaintainable. If you have a better flow in mind, you can open a new issue and suggest some ideas, like I did with the missing share button in #4039.

**Comment by nbmrjuhneibkr** [comment]
My "better flow" would be to revert back to how it worked in 0.18, but I already know what response I'm going to get.  
What purpose does this new feature serve? Why does the back button need to direct me to a video that isn't even added to my queue?  
Also, current implementation is inconsistent, which makes it more confusing: on step 3 it returns to the list, but on step 5 it doesn't.

**Comment by opusforlife2** [comment]
It's building up a queue in reverse order. The idea is (and this is mentioned in the blog post), you browse a few pages and tap on a bunch of videos to watch, and then as you finish each one you keep tapping back to go to the next one in the "reverse queue".

**Comment by opusforlife2** [comment]
> on step 3 it returns to the list, but on step 5 it doesn't.

On step 3 you have opened only 1 video, so your queue is 0. (or 1?)

**Comment by nbmrjuhneibkr** [comment]
>It's building up a queue in reverse order.
It certainly doesn't build a queue in a traditional way, since I cant access it. And why would it even build a queue if the user never asked it to do this?

This behavior makes sense if I play one of the related videos from the 1st video page and then want to return to it, but it makes no sense if I go back to the list of videos. I've already pressed the back button on video #1 once, so I shouldn't end up on that video's page again by going back later.

**Comment by opusforlife2** [comment]
The minimised player "contains" the queue so that you can carry it around as you browse. The browsing ability of the app is what has gained the most in this exchange, compared to before. Earlier, you could only browse linearly: video 1 > channel 1 > video 2 > video 3 > channel 3. Now you can go wherever you want and not lose the videos you were watching.

Anyway, if you close the minimised player, the queue will disappear.

**Comment by nbmrjuhneibkr** [comment]
I guess I'll have to request a setting that disables the minimized player then.

**Comment by avently** [comment]
@opusforlife2 thank you for the smart answers you post. My work definitely gave you more questions needs to be answered, sorry for that.

**Comment by opusforlife2** [comment]
The problem is that Newpipe doesn't have app tours, which are most definitely needed for such drastic changes. So many other apps completely rewrite their UIs, but since they show the users what changed and how to do old things in the new UI one by one, it's not as overwhelming as updating one fine day and just being completely lost.

**Comment by streaps** [comment]
>  This is a new feature

shitty feature
