### ISSUE TITLE
could not parse json response

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4465]
i am not sure if this is an issue but i preassume that whenever an error report pops up it means it's an issue to be handled differently. 

steps to reproduce the issue :
1. go to any video 
2. copy a very long comment
3. paste it in the search box and wait for suggestions
4. you will get an error to report

**Comment by opusforlife2** [comment]
@panacist Don't delete the template. Edit your issue and fill it properly.

**Comment by panacist** [comment]
@opusforlife2 sorry about it i will retry again . but aren't the steps provided helpful to reproduce the issue ? have you tried them?

**Comment by opusforlife2** [comment]
The template is there for a reason. It's not optional, dude. The point is to follow a set format so that issues are easy for a user/developer to view and a maintainer to classify.
