### ISSUE TITLE
issues i have no idea how to reproduce

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4466]
| issue 1 |   issue 2  |   issue 3 |
| :--- | :-----: | -----: |
| ![Screenshot_20200923-183700](https://user-images.githubusercontent.com/66388840/95608687-06eeb980-0a4d-11eb-86a7-dacb9171c25d.png) | ![Screenshot_20200906-231120](https://user-images.githubusercontent.com/66388840/95608984-8086a780-0a4d-11eb-99f3-0b01d42c304f.png) | ![Screenshot_20201008-132523](https://user-images.githubusercontent.com/66388840/95608824-3e5d6600-0a4d-11eb-8da8-9bf5a82be9fd.png) |
| what is that ? idk.  | sometimes channel name, views  or date are missing | those buttons to switch between comments and suggested videos |

**Comment by opusforlife2** [comment]
Also, 3 problems = 3 separate issues.

**Comment by panacist** [comment]
@opusforlife2 man i don;t know what am i to say about them that's why i didn't fill the template !!!
and those happen randomly

**Comment by panacist** [comment]
@opusforlife2 oh holly cows i relied on you to fix the bad presentations and seperate the issues because i really don't like it haha

**Comment by opusforlife2** [comment]
> that's why i didn't fill the template !!!

@panacist Again, the template isn't optional. In the section where it says Steps To Reproduce, just say you haven't found them yet.

Also, as avently said, the second screen is from the old version of the app. If you didn't delete the template and went through the checklist like you're supposed to, then you would have known you were on an older version.

**Comment by panacist** [comment]
@avently some are old because whenever i see a bug that is irrepoducible (bad spelling) i take a screenshot of it
the first ones are from 0.19.8 and the last one is from 0.20.0

**Comment by panacist** [comment]
@opusforlife2 i know the template is important and seperating issues as well it just takes time and effort sometimes and i dunno what to include in an issue and what not but calmer vous tout est bien!! i will fill in the template!

**Comment by opusforlife2** [comment]
٩( ᐛ )و

**Comment by avently** [comment]
@panacist why do you even create an issue for something that you meet once and can't even reproduce? What's a point of it? It's not hurt you usage. You think we just wanted to find more work?:)

**Comment by panacist** [comment]
@avently lol not really, maybe just to bring newpipe forward? like imagine a bug-free newpipe (impossible but settiing this as an ultimate goal will cause no harm)

**Comment by avently** [comment]
@panacist imaging everyone will create issues that took our time like this one. Who will develop this ideal impossible correctly working app then?
