### ISSUE TITLE
[Feature Request] Allow zoomed viewing and downloading of profile pictures, thumbnails, etc individually

### ISSUE THREAD

**Issue by UX0l0l** [TeamNewPipe/NewPipe#4468]
Hey, NewPipe team! first of all I really respect your guys' dedication to the project and all the effort you put into it, not to mention all the reading you need to do lol (more than 700 open issues rn, damn). but anyways, the title says it all. being able to download profile pics and thumbnails individually or at least get a better view of the picture can be really helpful to some people, and it's just a nice additional feature to have. thanks you guys, and I hope you implement this in future updates.

**Comment by opusforlife2** [comment]
Hey. We have a feature request template. Please edit your issue and fill it out. Thanks!

**Comment by UX0l0l** [comment]
ok sure, will do that lol. I'm doing this on an app on my phone so it didn't show me the template
