### ISSUE TITLE
Use Sepia API as default PeerTube instance

### ISSUE THREAD

**Issue by Booteille** [TeamNewPipe/NewPipe#4470]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Weeks ago, Framasoft, which is developping PeerTube, [released Sepia](https://framablog.org/2020/09/22/sepia-search-our-search-engine-to-promote-peertube/), a search engine frontend (with an API) to search through videos from PeerTube.
I think it would be a good idea to use [Sepia](https://sepiasearch.org/) as the default search engine for PeerTube, instead of relying to a specific instance.

Alternatively, NewPipe project could also host their own index and use it as the default search engine.

#### Additional context
Sepia source code: https://framagit.org/framasoft/peertube/search-index/

If you read the blog post, you should've read that Sepia is using [Framasoft's instances index](https://instances.joinpeertube.org/instances). It should satisfy most uses to stay under the French law (and most others, I guess) but if it does not fit well enough to NewPipe's need, using another index could be an option.

**Comment by wb9688** [comment]
Hmm… imho it would make sense to add that as an additional search option (like YouTube Music is for YouTube), because it isn't an actual service providing videos.

**Comment by test2a** [comment]
tubelab on f-droid was recently updated with sepiasearch and that works fine right now. this would be a good enhancement for newpipe

**Comment by B0pol** [comment]
I don't think it should be the default option. 
PeerTube is designed in a decentralized way, that's why on PeerTube instances default search engine is the local one. 
Global search with sepia search is here to answer the need of content, but it's not the default search index on peertube instances (it's the local one), and is not enabled by default (you can read "has to be explicitely enabled by admins" on v2.3.0 changelog). 

What do you think @TobiGr @Stypox?

**Comment by test2a** [comment]
look. you are right. when you have a "home instance" you are logged in to, you get to access sepia search if admins have enabled it or you can directly access sepia search to get new content.
when a user is using newpipe, we do not have an instance we can log into and consequent to that, be restricted by that instances terms. we can already follow multiple peertube instances so do you accept sepia search constraint from one instance to another based on what their admins have enabled?
second thing. if i open youtube, i get access to all of youtube search. 
if i select say tilvids.com on newpipe to be at top, would i be only able to search between results from that instance only? what about discovery as you said. 
the idea of sepia search is to bring content discovery. newpipe can help immensely with that goal

**Comment by Stypox** [comment]
@B0pol I agree with @wb9688 about the fact that sepia search should be a search option like Youtube Music, not the default one (also for the problems you pointed out). Other than that I don't have a strong opinion
