### ISSUE TITLE
Vertical Fullscreen missing since 0.20.0

### ISSUE THREAD

**Issue by sao37lyy5r** [TeamNewPipe/NewPipe#4474]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

One Feature i really like is watching videos in vertical fullscreen with zoom. Especially for videos filmed vertically or with a person speaking right in the middle. Unfortunately this feature seems to be missing since version 0.20.0

I think it would be really great if you could implement it back.

Thank you

#### How will you/everyone benefit from this feature?

![Screenshot_20201010-105833_NewPipe](https://user-images.githubusercontent.com/72648991/95651210-fab83a00-0ae8-11eb-8319-d7db378a14b7.png)

**Comment by opusforlife2** [comment]
There is a full screen button. Did you try to use it on a vertical video?

**Comment by streaps** [comment]
takes more taps than before, because the full screen button is not displayed befor I tap the video. It feels like everything behaves differently. What a  mess ...

**Comment by opusforlife2** [comment]
@streaps Refer to #4152.

**Comment by Fandrelo** [comment]
The feature was removed and it never made it back.

Basically can't change orientation while on fullscreen and zoomed in.

**Comment by opusforlife2** [comment]
@Fandrelo You've already commented on the correct issue, so I'm minimising this one.
