### ISSUE TITLE
Show completely watched videos

### ISSUE THREAD

**Issue by sojusnik** [TeamNewPipe/NewPipe#4480]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
At the moment a red bar under a thumbnail shows the last watched position. But if a video was watched till the end, then this bar is gone, making it impossible to know if this video was already watched. As a solution to this, I propose to show the complete red bar under a thumbnail, if a video was watched completely. Another solution could be a checkmark placed over a thumbnail, replacing the full red bar, to make those watched videos stand out even more.

#### How will you/everyone benefit from this feature?
Everybody would get a better overview of their completely watched videos!

**Comment by lucanomax** [comment]
Since that probably needs some caching or w/e, I would like to suggest also an automatic clear.

**Comment by opusforlife2** [comment]
You're right. It's strange that it doesn't.

**Comment by eladkarako** [comment]
interesting, never thought what makes a video "fully watched",  
say you skip to last second and press play, should it be considered "played",  
if not, we need to maintain a percentage of play duration relative to the full length of the video, and what threshold should be considered 'acceptable as "played"'...  
this all becomes too complex,  
and employ a lot of logic to a pretty much useless and silly feature (no offence..),  

How about "visited" video instead,  
similar to a link history in HTML (blue is new, purple is visited),  
any video that started playing ('show info' does not count) can be safely considered "visited".  

Any thoughts?

**Comment by lucanomax** [comment]
> a lot of logic to a pretty much useless and silly feature

Yeah, I understand perfectly. And if you clear cache it's gonna clear that feature too.

**Comment by Netpilgrim** [comment]
Having watched videos clearly marked as such would be great. A further improvement would be a filter for hiding watched videos in lists.
Also related: #2642 (manually mark videos as watched)

**Comment by vhouriet** [comment]
Watched videos seeam to have the full red bar now, I believe we can close this.
![Screenshot_20211109-222216](https://user-images.githubusercontent.com/89147152/141006981-173a2d5b-3da7-462c-bdaf-31f779ee8258.png)
 
Tested in 21.13

**Comment by opusforlife2** [comment]
@vhouriet Nice catch! Closing as fixed.
