### ISSUE TITLE
Totally broken user experience in 0.20

### ISSUE THREAD

**Issue by yiiii777** [TeamNewPipe/NewPipe#4482]
Hello!

I am the author of a multimedia application myself. And I know how difficult it is to adapt such applications to new versions of Android. How difficult it is to add new features, especially if you were going to do it a long time ago and have to rewrite half of the application.

But you showed me how IMPORTANT it is to stop on time. How important it is not to throw away old features, but to enable the user to switch to them. Even though they are not supported anymore.

The current version 0.20 is completely inconvenient. Small examples:

1. How I can share opened video? I don't have actionbar in videoinfo anymore. I used this feature many-many times per day.
2. How I can view video in fullscreen by single click, like in previous versions? I found "fullscreen" icon, like in original YouTube player, same crappy experience...
3. How I can STOP video immediately? At first, I need click "back" button as usual, but then I need click small "x" at bottom of screen. Very usable, even of high density screens.

This makes me angry. I understand, this is free project, but I not your guinea pig for UI experiments.

## A little story

Basically, I could use the original Google app. It is overloaded with unnecessary functions, but it lacks basic ones. But if there is no choice, I can use it.

Many years ago I found youtube-dl for android and used it to watch videos. This was very inconvenient as I had to first copy the link into the application and then get the download link. But instead of downloading, I just pasted it into the browser and watched the video inside the browser. It was better than the official app.

Then I found a new and young project called NewPipe. In those years, it was similar to "Hello World", but it was quite acceptable.

Then, I switched to another project - Skytube. It had a nice and elaborate interface. There was support for viewing comments here. It was really cool, especially after NewPipe. But the author of Skytube made a contract with the devil: he used official libraries and keys to access YouTube. And once, when fame and popularity came to him, these keys began to be lacking. For some time I even put up with this, believing that YouTube consumption should be reduced. But besides this, the author added unnecessary functions. And he added a prohibition to rebuild the application, so its keys did not work anymore. It was very sad, but all I had to do was curse the author and uninstall the application.

I switched back to NewPipe. It was difficult to live with a primitive interface, no comment support or good playlists. But over time, it all appeared. I have been rewarded for my patience. I was very happy.

But unfortunately I sometimes got page parsing errors. This is not critical, but I was still hoping for some bug fixes. And I updated to 0.20. After a fit of rage, I removed 0.20 and installed 0.18 as my last hope.

**Comment by FriendlyNeighborhoodShane** [comment]
You can share the link of a video with the share button inside the player window. But of course, that requires you to first play the video, and even then it shares with a timestamp.

Another problem is that whenever you open a video screen without playing it, it gets added to the queue, *even when* autoplay is disabled. Then whenever you go back and open another video screen from any list (channels, homepage, etc.) and press back, you annoying end up back onto that first video's page. This behaviour *might* have made sense when autoplay were enabled or the video was played manually, but it happens even when it's not.

Honestly, as someone who was neither much fond of the original Newpipe UX nor of the Youtube UX that this update tries to copy, this was somewhat of a functional downgrade. But to be fair, UX is arguably the most complex part of any machine as it's the part that has to deal with silly opinionated humans and their wishes, and is almost impossible to please everyone with.

**Comment by opusforlife2** [comment]
Thanks for the feedback and all, but two of your mentioned issues are duplicates (#4039, #4152), so could you please open an issue just for the third one? Thanks.

**Comment by yiiii777** [comment]
> so could you please open an issue just for the third one? Thanks.

I ask not for fixing some issues, I ask about feature BRING BACK all old interface. For me, new UI is 1 big mistake.

**Comment by opusforlife2** [comment]
Since you're a developer, you know that the UI can't just "be reverted". A huge amount of development has happened since 2907 (unified player) was merged, so the only way forward is to merge new PRs.

**Comment by avently** [comment]
@yiiii777 am I understand correctly that you have two issues (third is non-issue I think because it just require one more click) and you so angry because of them? Even after this two issues be fixed you will be angry too?
