### ISSUE TITLE
unify behavior of clicking 'back' (device's key) vs. clicking the backward-pointing arrow (top-menu button)

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#4483]
Clicking the device back key usually results with a better consistency  
to the user's navigation history (including both video playing and app's section visiting),  
while clicking the top back-button usually is a lot rougher, cutting out fine-"navigation history",  
and goes back to the initial program section,  
if it is "whats new" or search results.  

It does not really seems to be consistent behavior,  
and for the lack of 'bread-crumbs' or actual record of user actions,  
there isn't really a visual button to be an alternative to the device's physical (or logical..) back button, and it's really confusing that the menu-button is a backward-pointing arrow which implies "go back", similar to browser navigation.

**Comment by TheAssassin** [comment]
You seem to have blocked Team NewPipe. Therefore, we will close this issue now. If you unblock us, we can reopen the issue.
