### ISSUE TITLE
support a head-up-display mode (HUD)

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#4485]
OK, this is really quirky suggestion,  
If you're not familiar with a HUD ( https://en.wikipedia.org/wiki/Head-up_display )  
its a simplified control-set where all the fine-tweaks and knobs are hidden,  
replaced with a very big, clean UI, usually it is also named 'driving mode'.  

Not implying that one should 'youtube and drive' (seems risky as much as 'drink and drive' if not more),  
HUD sometimes supports horizontal mirroring of the UI,  
which makes it usable a a partially reflected image through the drivers' windshield (assuming one is safely parking of course).  
This allows videos (and subtitles) to be viewed correctly after being reflected,  
and it's kind-of like watching a cinema in your car.  

Cool factor aside (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
I've just wanted 'HUD way of watching videos' for a long time,  
I never found a 3rd-party app that will allow globally mirroring of the entire device's content,  
(maybe Xposed-framework will be suitable for that...)

And the closest I've came is a firefox-addon that allows youtube (website) to be mirrored,  
https://github.com/eladkarako/chrome_extensions/blob/store/MirrorX/README.md  

<img src="https://raw.githubusercontent.com/eladkarako/chrome_extensions/store/MirrorX/resources/screenshot_1.png"/>  

Just want to leave this one here,  
and hear your thoughts... ( ಠ ͜ʖ ಠ)

**Comment by TheAssassin** [comment]
You seem to have blocked Team NewPipe. Therefore, we will close this issue now. If you unblock us, we can reopen the issue.
