### ISSUE TITLE
Swipe to open menu/drawer only available on main page

### ISSUE THREAD

**Issue by nahuhh** [TeamNewPipe/NewPipe#4487]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to a channel and Swipe to open the menu Or
1. Perform a search, (optionally play a video) and Swipe to open the menu 

### Actual behaviour

Unless you go back to the main page, nothing happens when you try to access the menu

### Expected behavior

Consistency with behavior on main page. (Menu opens)

### Screenshots/Screen recordings

![Screenshot_20201011-030644.png](https://user-images.githubusercontent.com/50635951/95672514-5e854600-0b6f-11eb-88f4-bb6c3d8b6350.png)
"Swipe to open menu" is possible on the main and videos played from there (screenshot) but inaccessible from search results or a channel page.

### Device info

 - Android version/Custom ROM version: 8.1.0 stock 
 - Device model: BlackBerry keyone

**Comment by opusforlife2** [comment]
See #3156.

**Comment by Stypox** [comment]
#3135
