### ISSUE TITLE
Add option to disable notification color adjustment to video thumbnail

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#4488]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Add an option to make notification color not adjust to thumbnail of video. Use default colors of NewPipe.

#### Additional context
I already mentioned this in the v0.20.0 release.
https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-699675761

<img src="https://user-images.githubusercontent.com/41164160/95673077-dcfcda80-0ba5-11eb-9f9e-a298fc66b71a.png" height=300>

#### How will you/everyone benefit from this feature?
With everything on my phone being darkmode you have NewPipe which produces brightly colored notifications.

**Comment by opusforlife2** [comment]
MediaStyle notifications should have gotten a variable to set the notification theme to Dark, Light or System when Google finally added system-wide dark more in Android 10.

**Comment by XiangRongLin** [comment]
@Stypox Are you going to do this soon? Since i want this feature before going to v0.20.x and the current v0.19.x version has a lot of extractor problems.
If not im going to do it myself, since i think I found the place where it is set.

**Comment by opusforlife2** [comment]
@XiangRongLin We have lots of things on our plate to fix after 0.20.0. If you could give us a hand it would be a great help.
