### ISSUE TITLE
[Regression] Option to not show video thumbnail in lockscreen

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#4489]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

An option to not show the video thumbnail in the lockscreen.

#### Additional context
With v0.20.0 the option to not show the video thumbnail in the lockscreen is gone. With the Android feature "Hide sensitive content on lockscreen" i just get a blurry mess.
I already mentioned this in the release issue: https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-699769484
<img src="https://user-images.githubusercontent.com/41164160/95673044-91e2c780-0ba5-11eb-9c04-31278a45862b.png" height=300>

#### How will you/everyone benefit from this feature?

I can see my own wallpaper again, which i like very much.

**Comment by lucanomax** [comment]
I think that's a permission you can give to apps. Unfortunately I don't remember how It's called.
