### ISSUE TITLE
[BUG] NewPipe reloads content of search results when switching between apps

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#449]
NewPipe reloads search results after switching between apps. Even if search results are scrolled down it reloads them after switching back to NewPipe window.

**Comment by theScrabi** [comment]
Thats because NewPipe does not save the results, but the query. Therfore its has to reload the results every time it reloads the activity.

**Comment by teod0r** [comment]
This is bad. Do something with that. Can you make it to remember results? It seemes to me that earlier there was not such problem, or not?

**Comment by theScrabi** [comment]
It was ... this is how NewPipe was developt

**Comment by teod0r** [comment]
It even reloads list when opening video and going back! I'm absolutely shure that it was not doing that before! Fix it please

**Comment by theScrabi** [comment]
Sorry that would require huge re factoring.

**Comment by teod0r** [comment]
it was not doing that before!!!

**Comment by theScrabi** [comment]
I know, but therefore it did a couple of other nasty things.

**Comment by teod0r** [comment]
I think it fixed

**Comment by teod0r** [comment]
only partialy fixed. now does not reload when switching between apps, but reloads when opening a video and going back

**Comment by mauriciocolli** [comment]
Yes I just fixed the switching part, going back is more complicated (memory management, de-loads the images, save the list...), but it is on my TODO list...

**Comment by Wabuo** [comment]
@mauriciocolli Hey while you are at it I wold love if New Pipe would check if the search results are still working eg. If you change the network or if you wait to long(some days) the play button will yust trow an error but if you reload/research it works fine again.

**Comment by theScrabi** [comment]
The question is how often does something like that happen, and would it be worth implementig.

**Comment by Wabuo** [comment]
For me it happens often enough that it started to anoy me.

But most of the time it is because of switching between networks. That is a really frequent use case for me because I live in a student dorm and just by walking to the kitchen or visiting a Flor-mate my device will use an other WiFi ...

**Comment by Wabuo** [comment]
@mauriciocolli Hey I just want to report that minimizing works now *but* going back with the arrow in the top left(hardware back button works as intended) will bring you to the apps starting screen is this intended if yes I suggested to change the Icon.

**Comment by mauriciocolli** [comment]
@Wabuo that's the intended use of the "Up button", bring the user to the first screen ("Parent activity").

Let's say that you visit a lot of videos, if you want to go back to the  "Main" screen, you would have to press back a lot of times and often you would over-press the back button, exiting the app, and that's where the up button is useful, with just one click, it brings the main screen.

You can try that in the Play Store for example, it's very useful (in my opinion) and when we have a decent Main screen (featured videos, recommended, idk), I think this will be useful too.
