### ISSUE TITLE
Cannot load video stream when skipping far ahead (+ workaround/temporary fix)

### ISSUE THREAD

**Issue by lucanomax** [TeamNewPipe/NewPipe#4490]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open a Video
2. Skip to half video
3. Video stream error

**Workaround**

4. Clear cache (from settings > apps)
5. Open Video and skip ahead (not double tap quick skip)
6. It actually load the video without stream errors

**I'm still trying to understand the cache limit when this error appears.**

### Actual behaviour
A stream error appears. When you clear cache manually It loads video stream.

### Expected behavior
Should start buffering (depending on internet speed) and load it without you have to clear cache.

### Device info

 - Android version/Custom ROM version: Aosp Extended 7.3
 - Device model: Xiaomi (vince)

**Comment by chenzhendong** [comment]
I expereince vides spin and hold forever on 0.20.0 randomly. When I rollback to 0.19.8, the problem would never happen in the same network condition.

**Comment by opusforlife2** [comment]
@chenzhendong How is this related to the bug described in the OP?

**Comment by lucanomax** [comment]
After 2 days I experienced this bug, I'm not experiencing it anymore. I guess it was a problem with network or some settings I changed.
I had this bug like 3 times a day before opening the issue, now i can't even experience it again to look for a solution or for logs.

**Comment by chenzhendong** [comment]
> @chenzhendong How is this related to the bug described in the OP?

Since I reopen the video, it jumps to points that it was playing.  So I think it is related with skip far ahead problem.  And I just want people aware 0.20.0 is not stable enough for use at least for me, I have to rollback and lose all my bookmarks.

**Comment by opusforlife2** [comment]
I always export my database before updating.

Yours seems to be more of a cache problem, @chenzhendong. See if any other issue describes your problem. If not, open a new one.
