### ISSUE TITLE
Thumbnail looks stretched on 16:9 devices

### ISSUE THREAD

**Issue by Rubbix** [TeamNewPipe/NewPipe#4491]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
 
     1. Go to 'Any song or video you want to play on the background'
     2. Press on 'Background'
     3. Go to lockscreen and hit the preview of 'The song or vide you wanted to listen in the Background'

### Actual behaviour

If you play any songs/videos and you open the preview on your lockscreen, the thumbnail looks stretched and wierd.

### Expected behavior

If you play any songs/videos and you open the preview on your lockscreen, the thumbnail looks stretched and wierd, this should not be happening !

### Screenshots/Screen recordings

![Screenshot_20201011-131217_Samsung Experience Home](https://user-images.githubusercontent.com/27083995/95675995-c06f9b00-0bc3-11eb-87c2-877e99c51c9e.jpg)
![Screenshot_20201011-131232_NewPipe](https://user-images.githubusercontent.com/27083995/95675996-c1a0c800-0bc3-11eb-91d7-8db7ae559671.jpg)

### Device info

 - Android version/Custom ROM version: 8.0 Oreo Stock
 - Device model: Samsung Galaxy A5 2017

**Comment by opusforlife2** [comment]
Try toggling the aspect ratio setting in Notification settings.

**Comment by Rubbix** [comment]
I tried togging the aspect ratio option setting in Notifications settings and it didn't fix anything, it's still the same.

**Comment by Rubbix** [comment]
https://youtu.be/GGQ4ETyzpLY
Here is a video that states specifically what I did and what are the steps to reproduce it

**Comment by Rubbix** [comment]
Sorry if I ping an old issue but is this problem acknowledged ?
I don't want to rush anything but this was a know bug I had for a while and wanted to get sure it's getting fixed. 
Thanks for the work you guys did so far, grateful for the progress so far on NewPipe !

**Comment by Feuerswut** [comment]
This has likely been adressed or is no longer an issue due to newer Android versions. Close issue?
