### ISSUE TITLE
colour

### ISSUE THREAD

**Issue by mittalrahul074** [TeamNewPipe/NewPipe#4492]
The colour red is too bad can you change it too blue its will look classy

**Comment by opusforlife2** [comment]
Sorry, you'll have to fill in the template first.

**Comment by vkay94** [comment]
You can do it really yourself: since all colors are saved as resources:
1. Create a fork of the project.
2. Go to `res/values` and change all red colors in `colors` and `colors_services` (In AS the preview is shown, so it's done in 1 minute)

**Comment by TobiGr** [comment]
IMO there is no need to change the colors. Every service has its own color. If we changed YouTube's color, we'd need to change the colors of all other services as well.
