### ISSUE TITLE
reCaptcha challenge

### ISSUE THREAD

**Issue by aliglelo** [TeamNewPipe/NewPipe#4494]
Every time i open newPipe i encounter recaptcha challenge and even in that it does not let me solve that instead shows a blank white screen and never lets me use the app.
I have been facing the issue from last 2 updates more frequently.

### Checklist

- [x] I am using the latest version. 
- [X] I checked, but didn't find any duplicates of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open the App.
2. Play any video.
3. And you get a recaptcha challenge.

### Actual behaviour

App should either play the video or at least let me solve the recaptcha instead of just throwing a blank white screen.

### Expected behavior
recaptcha challenge appers no matter i have re-installed the app.

### Device info

 - Android version/Custom ROM version: Android 10.0 | MIUI.eu 11
 - Device model: Redmi 7

**Comment by opusforlife2** [comment]
Do you have a network that is modified in any way? An app (like a VPN) on the phone or a service on your router?

**Comment by Stypox** [comment]
See #3714
