### ISSUE TITLE
Cannot load YouTube URLs when Background player is active

### ISSUE THREAD

**Issue by gloschtla** [TeamNewPipe/NewPipe#4495]
Since I installed the latest version 0.20.0, I can no longer open youtube video addresses in newpipe's info page, if the background player is still active from a previous video which i started from the info page of the previous video. 

Instead of opening the latest youtube video, it re-opens the infopage of the previously played video.

**Comment by Stypox** [comment]
#4403

**Comment by gloschtla** [comment]
This problem still exists in the newest version 0.20.3
 I don't understand why you closed my this issue report.
 I miss this feature from the older version.

**Comment by opusforlife2** [comment]
Same as the other issue. It's a duplicate of the issue mentioned above.
