### ISSUE TITLE
The sharing button disappeared from youtube video info view.

### ISSUE THREAD

**Issue by gloschtla** [TeamNewPipe/NewPipe#4496]
When I wanna share a Video from its info page, i am forced to play the video so i can see the sharing button in the frame of the video player. In earlier versions of Newpipe 0.20.0 this sharing button was still there. 

I disabled the autoplaying of videos on the video info view page.

**Comment by avently** [comment]
See #4039. We trying to invent a new UI for such buttons.

**Comment by gloschtla** [comment]
This problem still exists in the newest version 0.20.3
 I don't understand why you closed my this issue report.
 I miss this feature from the older version.

**Comment by opusforlife2** [comment]
Because it's a duplicate of 4039, as mentioned above.
