### ISSUE TITLE
Not the same playback position when changing players

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#4497]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play the video in video details / full screen for some time (few tens of seconds)
2. Switch to background by turning off your screen or clicking on popup button

It does not _always_ happen, I don't know why

### Actual behaviour

The playback position is current minus about 20s

### Expected behavior

Same playback position when changing players

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: pocophone F1

**Comment by opusforlife2** [comment]
For me, Newpipe has always resumed a little behind where I pause it when I switch to other apps. I thought that was a feature, trying to maintain continuity. But only something like 5-10 seconds.

If that is indeed how the code works, maybe there is a bug in it?

**Comment by MD77MD** [comment]
also but not so related.... if you play video A, then play video B, then go back to video A... video A will start from the beginning

I can open a new issue if my comment here is not sufficient.

**Comment by opusforlife2** [comment]
@MD77MD Do you have Resume turned off?

**Comment by MD77MD** [comment]
@opusforlife2 

😲......Yub 🤣, but i have no memory off turning it off 🤑 lol... thanks bro

**Comment by opusforlife2** [comment]
Wow, you're right. It doesn't work. @avently some sort of regression has happened here. We've tested this. It used to work properly.

@MD77MD Please open a new issue.

**Comment by MD77MD** [comment]
#4506 playback position from video B to video A bug

**Comment by avently** [comment]
@ildar I never had this problem. So nothing to fix until someone provides 100% reproducible procedure

**Comment by SameenAhnaf** [comment]
This issue should be closed as https://github.com/TeamNewPipe/NewPipe/issues/7427 has a more updated discussion.
