### ISSUE TITLE
Allow viewing profile pics and thumbnails individually

### ISSUE THREAD

**Issue by UX0l0l** [TeamNewPipe/NewPipe#4501]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I want to be able to download metadata individually (e.g. profile pictures, thumbnails, etc) and to be able to view them individually in a zoomed view/image viewer

#### Is your feature request related to a problem? Please describe it
it's not related to a problem, but it's much more convenient for me to have this feature

Related: #3724.
#### Additional context
for example, if I go to a creator's channel (on any platform) and click on their profile pic, I wanna see the full quality, full-size image in front of me with the ability to zoom, and a download button and share button on the top right corner of the screen, or that's how I imagine it at least. and for the thumbnails an option could be added in the download menu on a video next to "audio" and "video" that says "thumbnail".

#### How will you/everyone benefit from this feature?
This feature allows me to download this data more easily, instead of needing to use something like youtube-dl, it can also be used as just a zoom tool to see these pics more clearly if someone has sight problems, or the picture just isn't clear, etc. it just makes the experience better for the user in my opinion

**Comment by UX0l0l** [comment]
this is also a followup to issue #4468 after being asked to rewrite it, I just got the time to do so lol

**Comment by opusforlife2** [comment]
Thanks!

**Comment by Stypox** [comment]
#3724

**Comment by opusforlife2** [comment]
@Stypox That feature request doesn't contain the viewing part. Let's keep that one for downloading, and this one just for viewing.

**Comment by shivasagarrao** [comment]
This feature has been implemented in [SkyTube](https://github.com/ram-on/SkyTube) which uses Newpipe extractor.

![SkyTube view thumbnail](https://user-images.githubusercontent.com/46630255/103102195-e9d78900-4640-11eb-8037-ccc2fa4b2f26.png)

**Comment by UX0l0l** [comment]
I don't see why not to implement it in Newpipe too

**Comment by opusforlife2** [comment]
Only half of this issue is addressed. Still no way to view profile pics. Should this be reopened?

**Comment by opusforlife2** [comment]
@Stypox?
