### ISSUE TITLE
the latest release was a total gnome move

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#4502]
the latest release was a total gnome move. Can someone please fork this project before it gets out of hand? Bug reports have spiked. Most people don't like the unified player.

**Comment by opusforlife2** [comment]
As I said regarding your comment on #4460, use the fork button yourself. ✌️ 

Also, don't delete the template next time, @hp8wvvvgnj6asjm7.
