### ISSUE TITLE
Allow to share video without starting it

### ISSUE THREAD

**Issue by EverEve** [TeamNewPipe/NewPipe#4503]
Hi, first of all I want to thank you for the effort. I've been looking for an app like this for years.

The only thing I probably really miss from the "normal" YouTube app is the possibility to share a video without starting it: sometimes you only want to send a link to someone and I think that the "share" button could be located near the "download" button. 

Now the only way to share a video is starting it, then tap the arrow in the top-right corner and finally tap the "share" button.

Thanks again.

**Comment by opusforlife2** [comment]
Don't delete the template. It is there for a reason. If you had gone through the checklist as required, you would have searched for duplicates and found #4039.
