### ISSUE TITLE
open in external player - no sound. scrape this feature! 

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#4504]
this feature should not be allowed to work on VO an AO streams which is now the majority of hls videos in yt. 
it only works when it is an old a/v stream (which we don't serve anymore).
Unless we want to mux in the background and serve that to the external player over buffer, 

this feature IS NOT suitable for the current versions of NewPipe and should be kept on ice (not just disabled by default).

Note that external audio player is fine for obvious reason.

**Comment by nbmrjuhneibkr** [comment]
Most YT videos have at least 1 format with audio+video, usually it's MP4 720 (format 22 in yt-dl) and MP4 360 (18 in yt-dl). If yt-dl can detect this with its --list-formats, NewPipe could do the same and highlight a/v formats in the list that appears when external player is enabled.

**Comment by eladkarako** [comment]
> Most YT videos have at least 1 format with audio+video, usually it's MP4 720 (format 22 in yt-dl) and MP4 360 (18 in yt-dl). If yt-dl can detect this with its --list-formats, NewPipe could do the same and highlight a/v formats in the list that appears when external player is enabled.

That is no longer the case for 6 months now. as i explain, the 360p or 240p or 144p that used to be that are  ALSO  provided with hls, which we prefer. 

I've supported for a long time of 360p and below to be explicitly served as their AV versions of their in NewPipe, but it eventually went to globally hls unless in the rare cases where query for streams does not find any hls, just old-school tag 18 for example.. FYI.

**Comment by nbmrjuhneibkr** [comment]
I just tested 10 videos from different channels, all of which are less than 1 month old. They all have formats 18 and 22 available, and play with audio just fine when opened in an external player from NewPipe (720p30 = format 22).

**Comment by Stypox** [comment]
> NewPipe could do the same and highlight a/v formats in the list that appears when external player is enabled.

NewPipe already does that. I don't think this issue should be embraced: people using external players are already tech-savy people, so it is probably common for some of them to open an external player exactly as a way not to hear audio. Also, since as I said the external player feature is already targeted at a niche, refining that niche by removing something that can already be done makes no sense imho.
