### ISSUE TITLE
[Feat Req] Add Setting to Choose Between Underscores and Spaces

### ISSUE THREAD

**Issue by irmbpqln** [TeamNewPipe/NewPipe#451]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by TobiGr** [comment]
You can do this in the settings > download > `Allowd characters in filenames` and `Replacement character`. If you want something else, please provide a more details.
