### ISSUE TITLE
Unusuable on AndroidTV/FireTV

### ISSUE THREAD

**Issue by fliegentoeter** [TeamNewPipe/NewPipe#4511]
Hi, 

the latest version of newpipe works great on phones, but it seems to be a downgrade and totally unusable on android tv, like my FireTV 4k.

First of all, videos do not play in fullscreen, which seems to be noticed as a bug.
But the worst part for me is that if I decide to stop watching a video and press my "back" button on my remote, the video minimized to the bottom. So if I click the next one and decide to stop watching, my screen does not switch back to my subscriptions, but to the last video I watched.

And the worst part is that I can't switch back to Version 0.19 because Fdroid is not working properly on my FireTV stick and won't let me see Versions....
If I download version 19 on my phone and try to install it on my FireTV Stick it just states, that the app seems not to be installed :(

Any help on how to switch back to 0.19 is apprechiated until newpipe can be used on androidTV again.

Thanks

**Comment by opusforlife2** [comment]
You have to uninstall 0.20.0 first. Then install 0.19.8. Android doesn't allow "downgrades" for security reasons.

Having said that, since the problems you mention are being discussed in other issues, I'll close this one.
