### ISSUE TITLE
Fixes needed ASAP

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4513]
The linked project contains those issues which we consider urgent for the next point release to fix regressions caused by 0.20.0:

https://github.com/orgs/TeamNewPipe/projects/7

**Comment by nbmrjuhneibkr** [comment]
Kind of sad that https://github.com/TeamNewPipe/NewPipe/issues/4460 is not on the list, considering the feedback that it's getting - but understandable.  
Such a major regression may not be easy to fix, so it would probably cause a big delay for the next release.

**Comment by opusforlife2** [comment]
@nbmrjuhneibkr Added. :)

**Comment by avently** [comment]
@opusforlife2 the whole purpose of the issue was to add only important things... Now it has no purpose.

**Comment by opusforlife2** [comment]
The purpose of the project is to give the devs something to focus on for the next release. Whether or not those issues turn into actual PRs is a different matter.

**Comment by AnotherLife** [comment]
The popup player keeps pausing and not buffering a few seconds after I open video details in the main app. I have autoplay disabled and browse around my subscribed channels while a video is playing in popup. And the popup keeps pausing, I have to constantly switch from 240p to 360p and the other way around to make it resume. Is this a separate issue?

On Android KitKat.

**Comment by tfga** [comment]
Maybe #4738 should be added too?

**Comment by nbmrjuhneibkr** [comment]
The "ASAP" part did not age well...

**Comment by opusforlife2** [comment]
Indeed.
