### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by osoyoguiconbubu** [TeamNewPipe/NewPipe#4519]
Good afternoon,
Where is the "Share" option in playback mode?
In the previous version, it did exist with the "<" symbol at the top next to the selection of the reproduction quality.
In the latest version 0.20.0, I can't find it. 

Regards

**Comment by nbmrjuhneibkr** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/4039

**Comment by avently** [comment]
It is located now only inside the player itself, click on arrow down button from top right corner of the video. Share button will appear

**Comment by nbmrjuhneibkr** [comment]
If autoplay is disabled, Share and other options are now inaccessible unless you start the playback. Which is why https://github.com/TeamNewPipe/NewPipe/issues/4039 is open.

**Comment by osoyoguiconbubu** [comment]
> It is located now only inside the player itself, click on arrow down button from top right corner of the video. Share button will appear

Good evening,
The problem is that if I have activated the option "Use external video player", I cannot access that arrow.

**Comment by avently** [comment]
@osoyoguiconbubu yep, didn't think about it. We're still searching for a better solution

**Comment by osoyoguiconbubu** [comment]
> 
> 
> @osoyoguiconbubu yep, didn't think about it. We're still searching for a better solution

Good Morning,
Will there be a solution soon?

Regards

**Comment by opusforlife2** [comment]
@osoyoguiconbubu You can test the APK uploaded in the PR linked to #4039.
