### ISSUE TITLE
[Fullscreen]: hide playback controls when playback is resumed

### ISSUE THREAD

**Issue by PetbkA** [TeamNewPipe/NewPipe#4521]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I'm using Xiaomi Mi Band 2 to play/pause remotely. The problem is that overlay with playback controls doesn't disappear after resuming if I don't tap Play button, and it's not happening 'cause I'm tapping the button on Mi Band. So I have to tap on smartphone display to remove overlay or continue watching with overlay.

It would be nice if overlay would disappear not when Play button is tapped but when playback is resumed.

**NewPipe version**: 0.20

**Comment by opusforlife2** [comment]
Could you add your case as a comment on #3403? Thanks!
