### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by Goggle36** [TeamNewPipe/NewPipe#4522]
### Checklist

- [x] I am using the latest version. 
- [ ] I checked, but didn't find any duplicates of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by opusforlife2** [comment]
Go through the checklist properly. It is not optional. Fill the template properly.
