### ISSUE TITLE
Always says something went wrong when searching something

### ISSUE THREAD

**Issue by Peakgolden** [TeamNewPipe/NewPipe#4531]
Started having this problem from yesterday . When I search something , it says "Something went wrong, try again" . It repeats even after trying for multiple times . And I also have infinite loading when playing any video from my playlist .

**Comment by opusforlife2** [comment]
Please edit your issue and fill the bug report template.

**Comment by Peakgolden** [comment]
> Please edit your issue and fill the bug report template.

Done .

**Comment by opusforlife2** [comment]
This is the template: https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by opusforlife2** [comment]
Oh wait. Don't bother.

**Comment by opusforlife2** [comment]
Duplicate of #4201.

**Comment by Peakgolden** [comment]
> Duplicate of #4201.

I guess so . Any solution ?
