### ISSUE TITLE
Could you guys add Twitch to the NewPipe app?

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#4532]
Right. This might be extremely hard, but would it be possible to add Twitch as a platform you can view alongside YouTube, SoundCloud, MediaCCC, and PeerTube? I really love the streams people do on Twitch. Also, could you make it an option to have chat on or off, or just not have it like with YouTube live streams because I don't wanna see chat.

Thanks so much!

**Comment by opusforlife2** [comment]
This will probably be lower in priority because Twire already exists on F-Droid.

**Comment by HTSamurai** [comment]
> This will probably be lower in priority because Twire already exists on F-Droid.

I would rather use a trusted app that I know and just be able to easily access it.

**Comment by mehedihasanziku** [comment]
Maybe it will make heavy newpipe, then it will change the motive behind newpipe

**Comment by Stypox** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/issues/76
