### ISSUE TITLE
Maybe add a way to enter a video/livestream website and it somehow takes videos and browses on it? 

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#4533]
Crazy, maybe impossible idea, but could it be possible to add your own streaming services to the NewPipe app? I think with searching it could work by taking listings shown (the pictures, views and title, that's it.) from a URL such as "https://www.somevideowebsite.tv/search=%s" and have it replace%s with your search query. Maybe you could add a colour for it? For example if I added twitch to my NewPipe app I will make it purple. This could be super hard, and maybe you just put in a URL and it goes on the website with an optional adblocker. Thanks anyways.

**Comment by opusforlife2** [comment]
Not possible. Every website is different and needs a special extractor made just for it in Newpipe. This is how youtube-dl works as well.

Meanwhile, you can use mpv-android with youtube-dl built in to access services which are not yet in Newpipe.

**Comment by HTSamurai** [comment]
Thanks
