### ISSUE TITLE
youtube widevine drm on the way?

### ISSUE THREAD

**Issue by atempgithubacc** [TeamNewPipe/NewPipe#4536]
hey guys,
i think youtube may be enabling widevine drm for all "their" videos. i was just randomly watching videos on youtube when suddenly it required me to enable the widevine drm module in the browser in order to play this video. i always disable widevine in the firefox and its the first time i ever came across this.

![youtube_drm](https://user-images.githubusercontent.com/73000114/96307769-70993580-1002-11eb-8e23-ef207cf91123.PNG)

**Comment by wb9688** [comment]
Nope. See #3538 or #3203

**Comment by opusforlife2** [comment]
Oh. XD

Phew!
