### ISSUE TITLE
[Feature request] Add ability like video blocker plugin for ff/chrome/opera

### ISSUE THREAD

**Issue by Shtirla** [TeamNewPipe/NewPipe#454]
Its really need for android

**Comment by theScrabi** [comment]
What do you mean? Please describe it further.

**Comment by Shtirla** [comment]
the ability to block by channel.
In android its impossible now. Realy so many channels with unwanted content,especially for children. many people will tell wery thanks.
Try this plugins on the PC and you will understand.
 
Sorry for my little english.

**Comment by theScrabi** [comment]
No thats ok.
Well sounds like a great idea, but I doubt I will find time for implementing that soon.

**Comment by GoatPlushie** [comment]
I also want this. The closest we have to channel blocking on android is Blocktube (requires you refresh the page for the blocking to take effect), since Iridium's block button doesn't work on mobile, instead taking you to the video you're trying to block the channel of.

**Comment by Stypox** [comment]
Closing in favour of #1815
