### ISSUE TITLE
Accessing details from `play queue` window breaks playback

### ISSUE THREAD

**Issue by pew-pew** [TeamNewPipe/NewPipe#4541]
Thanks to @AnotherLife I was able to reproduce the issue which was annoying me for a long time (since version 20.0). Here is his comment: https://github.com/TeamNewPipe/NewPipe/issues/4513#issuecomment-710558557

### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
0. Start the app with an empty play queue
1. Enqueue a youtube video in background (for example via push-and-hold menu entry in history)
2. Go to play queue by touching android player/notification
3. Press and hold on current track entry and select `details`
4. Try to seek to an arbitrary position in the player in the android notification panel (or by using controls in play queue window in the bottom).

### Actual behaviour

Playback stopped and pause button icon changed to loading icon. Seeking to other places or playing other tracks in a queue doesn't help.

### Expected behavior

Playback continues normally, as if I didn't access details from play queue.

### Device info

 - Android version/Custom ROM version: Android 10, magic UI 3.1.0
 - Device model: Honor 20 (YAl-L21)

### Important note
The main problem is that playback breaks even if I don't try to seek forward/backward (it's just a way to quickly reproduce the issue), it's enough just to access details once. And I have to completely wipe my play queue to get rid of frozen playback and lose all my history and queued tracks because of this.

**Comment by AnotherLife** [comment]
Thanks, I will test 0.20.1 soon. Doing my typical usage of browsing around my subscriptions and enqueing videos in the popup player, while it is playing.

**Comment by AnotherLife** [comment]
It is the same ... very annoying :(

**Comment by opusforlife2** [comment]
> Try to seek to an arbitrary position in the player in the android notification panel.

This requires Android 10 to test. Whoever has 10, please see this.

**Comment by pew-pew** [comment]
> 
> 
> > Try to seek to an arbitrary position in the player in the android notification panel.
> 
> This requires Android 10 to test. Whoever has 10, please see this.

Just checked - bug can be reproduced by seeking using play queue controls at the bottom too. (I'll update issue description)

**Comment by opusforlife2** [comment]
Ah. Confirmed. 👍

**Comment by opusforlife2** [comment]
@AnotherLife Is this the exact issue you were describing in your comment https://github.com/TeamNewPipe/NewPipe/issues/4513#issuecomment-710558557?

**Comment by AnotherLife** [comment]
> @AnotherLife Is this the exact issue you were describing in your comment [#4513 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/4513#issuecomment-710558557)?

Yes, it is!

**Comment by opusforlife2** [comment]
Alright. Minimizing it there.

**Comment by Stypox** [comment]
@avently could you look into this, please? I tried for something like two hours but couldn't understand why this happens.

**Comment by avently** [comment]
@Stypox I'm traveling without my PC so can't check the code. Can only see it via phone and trying to figure out what's happening.
I was able to reproduce and it looks like the problem with 
https://github.com/TeamNewPipe/NewPipe/blob/31814b70dad2ff3e5aeefc4098495d60cbc2cbc7/app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java#L86

Try to comment it out and send to the user.

**Comment by pew-pew** [comment]
> @Stypox I'm traveling without my PC so can't check the code. Can only see it via phone and trying to figure out what's happening.
> I was able to reproduce and it looks like the problem with
> 
> https://github.com/TeamNewPipe/NewPipe/blob/31814b70dad2ff3e5aeefc4098495d60cbc2cbc7/app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java#L86
> 
> Try to comment it out and send to the user.

Tried it myself - it worked! Seeking works fine with this `if` commented out.

**Comment by avently** [comment]
@pew-pew thank you for testing this!

@Stypox looks like here
https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L865
One more check needed like `player.videoPlayerSelected()`. I missed this possibility. With this check everything should be fine too and "disabled preloading" feature will still be functional.

**Comment by Stypox** [comment]
@avently thank you! I was just about to ask you under which conditions should preloading be disabled. I'm going to do that and fix also some navigation issues I found along the way

**Comment by avently** [comment]
@Stypox is #4432 has the same problem? I can't reproduce it
