### ISSUE TITLE
Can't download YouTube Stories

### ISSUE THREAD

**Issue by stralpt** [TeamNewPipe/NewPipe#4542]
http://www.youtube.com/shorts/IOS2fqxwYbA
[URL NOT SUPPORTED]

**Comment by opusforlife2** [comment]
@B0pol This is different from before, right? New URL format.

**Comment by stralpt** [comment]
@B0pol yes it was

**Comment by eladkarako** [comment]
Would you need to also update the <code>intent-filter</code> for YouTube with those path for NewPipe to target those URLs as well?  

![2020-11-10_131230](https://user-images.githubusercontent.com/415238/98666989-790d3380-2356-11eb-95ec-7efb1084b1d6.png)
