### ISSUE TITLE
[UX Regression] since version v0.20.0 it takes three taps to play video fullscreen instead of just one

### ISSUE THREAD

**Issue by doodhout** [TeamNewPipe/NewPipe#4544]
### Checklist

- [x] I am using the latest version, v0.20.0. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to any video details screen, in landscape mode
2. Press on button to start playing the video -> video starts playing while video details remain visible, video plays but has same size as thumbnail in details page, i.e. not fullscreen
3. Tap the playing video to make the controls show up
4. Very carefully tap the on-screen full screen button to make the video show up in fullscreen

### Actual behaviour
1. Tap button to start playing video in video details screen -> video doesn't play in fullscreen
2. Tap somewhere inside video player to display controls
3. Tap fullscreen button to make video play fullscreen

### Expected behavior
1. Tap button to start playing video in video details screen -> video immediately starts playing in fullscreen, like in 0.19.18

### Addendum
At least give us the option to choose between current bevaviour as seen in 0.20.0 and previous behaviour as seen in 0.19.18.

**Comment by Stypox** [comment]
#4152

**Comment by doodhout** [comment]
Apparently I did not think to look at issues from before 0.20.0 was released. My bad.
