### ISSUE TITLE
Cannot download some videos in v0.20.1

### ISSUE THREAD

**Issue by ndr48291** [TeamNewPipe/NewPipe#4545]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to for example https://www.youtube.com/watch?v=DDgLnA-CdJ4&t=1
2. You cannot see download button.

### Actual behaviour

This live video recorded on Wednesday 14/10/2020. It should be available for download.

### Expected behavior

I dont see download button

### Screenshots/Screen recordings

https://photos.app.goo.gl/yse1p5PMxBy1x8U5A

### Device info

 - Android version/Custom ROM version: Picsel Experience 10 September 2020
 - Device model: Xiaomi Mi 9T (davinci)
 - Newpipe version : v0.20.1

**Comment by opusforlife2** [comment]
Live videos take some time to be converted to normal ones that can be downloaded. This is totally up to Youtube. Newpipe can do nothing but wait.
