### ISSUE TITLE
New videos in YouTube subscriptions do not appear

### ISSUE THREAD

**Issue by jahway603** [TeamNewPipe/NewPipe#4552]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Subscriptions.
2. Click on the Subscription named "AwakenWithJP". I have had this occur with numerous subscriptions, but will use this one as the example here.
3. The video which came out today is not displayed.
4. Then go to YouTube in a web browser, visit https://www.youtube.com/user/AwakenWithJP/videos, and see the video which was created today display in your web browser.

### Actual behaviour

The latest video is not displayed in NewPipe.

### Expected behavior

The latest video would be displayed in NewPipe.

### Device info

 - Android version/Custom ROM version: LineageOS 15.1
 - Device model: ZTE A2017U

### Additional notes
- NewPipe works as expected behavior on a Nexus 5X with LineageOS 15.1, which is confusing me

**Comment by opusforlife2** [comment]
Was it a live stream?

**Comment by Stypox** [comment]
If the video which came out today is ["How To Change Someone’s Mind About the Election"](https://www.youtube.com/watch?v=brQcuncO4wc), then I'm able to view it correctly in NewPipe.

**Comment by Stypox** [comment]
> NewPipe works as expected behavior on a Nexus 5X with LineageOS 15.1, which is confusing me

Oh, then this might be a locale issue. Do you have the same "Content country" set in both phones?
Also, does clearing cache solve the issue? If you had opened that channel before and then never closed NewPipe, its content will be stored in cache, so the channel info won't be updated until you close and reopen NewPipe or clear the cache

**Comment by jahway603** [comment]
@opusforlife2, It was not a live stream.
@Stypox, It was that video. Now it appears in NewPipe, but if/when a different new video comes out then it would not appear as the initial PR reported. Both phones have the same "Content country" set. I was force closing and re-opening the app yesterday, so I'm not sure if clearing the cache will help or not. I noticed some configuration differences between the phones & just changed the "Age restricted content" and "YouTube restricted mode" to Off in the "Content" settings on the ZTE to reflect what was configured on the fully functional Nexus to see if this will help resolve this issue. Will see if I can try to re-create this when new content is released. Thank you.

**Comment by opusforlife2** [comment]
Closing until then. Make sure to let us know if you still encounter it.
