### ISSUE TITLE
(Android 10) "On app switch" triggers on screen lock

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#4558]
### Checklist
- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open settings
2. Video & audio
3. Minimize on app switch
4. Set it to minimize to pop-up
5. Go and load a video on main player
6. Lock the phone

### Actual behaviour

The video switches to popup, but since the device is locked, you only hear it. On unlock, you see playing popup window.

### Expected behavior

Locking the screen isn't considered an app switch and the player pauses on the main form.

### Screenshots/Screen recordings
<table><tr><td><img src="https://user-images.githubusercontent.com/26146502/96363187-f1efe580-1132-11eb-888a-b74040947652.jpg"/></td><td><img src="https://user-images.githubusercontent.com/26146502/96363189-f74d3000-1132-11eb-8bc6-5fcf5f36fc20.jpg"/></td><td><img src="https://user-images.githubusercontent.com/26146502/96363193-fc11e400-1132-11eb-9d15-5e730378b170.jpg"/></td></tr></table>
On the third image look carefully: it's a playing popup.

### Device info

 - Android version/Custom ROM version: 10 - API 29
 - Device model: Samsung Galaxy A70; Also appeared in older version on: Samsung Galaxy A5 2017 (I currently don't use the device anymore, so can't confirm on the latest version.)

**Comment by opusforlife2** [comment]
Works fine for me on Android 9.

**Comment by opusforlife2** [comment]
A user confirmed the bug is present in Android 10. Interesting.

**Comment by opusforlife2** [comment]
Possibly related: #2223.

**Comment by kubo6472** [comment]
I totally forgot: I tested this a few weeks ago on my Android Oreo (8) phone and it works fine. (Popup appears in paused form) But still happens on this Android 10 one.

**Comment by kubo6472** [comment]
> Works fine for me on Android 9.

So what does it do on your phone? Does it stay in the main player, or does it go to a paused popup?
