### ISSUE TITLE
(Android 10) Timestamps don't work

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#4560]
### Checklist
- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Click on timestamps in a video description on a playing or paused video.

### Actual behaviour
The video continues playing exactly where it was.

### Expected behavior
The video would jump to the desired time

### Screenshots/Screen recordings
Left: before; Right: after
<table><tr><td><img src="https://user-images.githubusercontent.com/26146502/96365893-35068480-1144-11eb-92bd-fc2678586d4d.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/26146502/96365897-3afc6580-1144-11eb-803c-bda5f32ed448.jpg"></td></tr></table>

### Device info
Android 10 - API 29
Samsung Galaxy A70

**Comment by kubo6472** [comment]
I accidentally clicked on the checkbox (that's why there are edits).

**Comment by opusforlife2** [comment]
Timestamps are supposed to open the video in a popup. Do you have the permission toggled off?

**Comment by kubo6472** [comment]
#4558 I'm sure it's allowed. Yea, I found the other issue that mentions why it opens in a popup, but no. It doesn't open at all. It's probably device/software specific.

**Comment by opusforlife2** [comment]
Hmmm. It could have something to do with #2223?

**Comment by kubo6472** [comment]
@opusforlife2 check #4918 there it works just fine, so it probably should be added to #4513

**Comment by TiA4f8R** [comment]
@kubo6472 #5523 fixes the issue?

**Comment by kubo6472** [comment]
Since I'm not on Android 10 anymore, I can't properly verify this. Also for some reason I didn't get any email about the label, just the bot. Can there possibly be a delay like Stale has? @litetex

**Comment by litetex** [comment]
> Since I'm not on Android 10 anymore, I can't properly verify this

Than I guess it's not a problem anymore.
No one else got it so I think we can close this issue so far.

> Also for some reason I didn't get any email about the label, just the bot

I think that's normal but depends on your notification settings.
However you should got an mail when you were mentioned over 6 months ago in https://github.com/TeamNewPipe/NewPipe/issues/4560#issuecomment-772689295

> Can there possibly be a delay like Stale has

I don't think so. 
We waited for >6 months, there were fundamental changes to starting position and no one ever stated that there is a problem.
If the issue comes up again, please open a new one 😄

**Comment by kubo6472** [comment]
> If the issue comes up again, please open a new one 😄

Thanks, will do if it comes up again.
