### ISSUE TITLE
add shuffle button to notification area

### ISSUE THREAD

**Issue by nonetrix** [TeamNewPipe/NewPipe#4564]
want to use this as my default music player but I can't seem to shuffle music apparently theirs a way but it's not very obvious and I can't find it here is how it should be added
![Screenshot_20201019-023741](https://user-images.githubusercontent.com/45698918/96415708-95350f00-11b4-11eb-9c62-074ca9cd8cd5.png)

**Comment by opusforlife2** [comment]
Use the Notification menu to modify the available buttons. And make sure you read the release blog posts so that you know about new features when they are added.

**Comment by connectety** [comment]
I didn't understand the explanation, so i'm just gonna assume, you didn't either.

You can either click on the left to middle site fourth or fifth action button and select shuffle (aka it is already added).
If you want to see it as one of your 3 actions buttons, when the notification is colpsed, don't forget to tick the checkbox.

Also congrats on your first issue.
