### ISSUE TITLE
Newpipe cannot be used

### ISSUE THREAD

**Issue by yixuancc** [TeamNewPipe/NewPipe#4567]
Newpipe cannot be used, network error will be prompted, and it will be loaded all the time. How to solve this problem?
![S01020-00572761](https://user-images.githubusercontent.com/43173400/96487905-d76f5680-126f-11eb-9db5-a1a87381214e.png)

**Comment by opusforlife2** [comment]
Please don't ignore the template. Go through the checklist and fill out the template.
