### ISSUE TITLE
show toolbar for resolution, share, ... when video is not playing

### ISSUE THREAD

**Issue by Surras** [TeamNewPipe/NewPipe#4568]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
With the new UI since release 0.20.0 the toolbar in the video detail page is gone (and the three dots in the upper right corner too). The UI looks more stylish, indeed, but the problem is, that the video options are only visible if the video is playing. So to share a video / open in browser, I need to start the video first, wait if its loaded and started, and NOW I can share the video to others.

It would be nicer if the option buttons are available, still when the video is paused / not started yet. My "workflow" normaly is: watch a video, talk with others about it, go back to newpipe and share it. But now, I need to replay the video again to share it. 

#### How will you/everyone benefit from this feature?
- faster access to share, open in browser, change video quality
- lesser clicks to acces video options (currently: touch -> start video, wait for video, touch -> show toolbar, touch -> expand video options, touch -> click desired option. Thats 4 touch + 1 wait :) )

**Comment by Stypox** [comment]
#4039

**Comment by Stypox** [comment]
Could you provide feedback in #4534?
