### ISSUE TITLE
Queue downloads

### ISSUE THREAD

**Issue by PacoBell** [TeamNewPipe/NewPipe#457]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Downloading multiple videos results in the download manager downloading all of them simultaneously. This is inefficient use of network resources, not to mention that it causes the UI thread to become unresponsive. Please only allow one video to download at a time. Thanks.

**Comment by theScrabi** [comment]
I keep that in mind.

**Comment by TobiGr** [comment]
implemented in #1759
