### ISSUE TITLE
"Could not play this stream" message, after pausing by tapping the video

### ISSUE THREAD

**Issue by Porkepix** [TeamNewPipe/NewPipe#4571]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

I sadly have no reliable STRs, but how this happened is it's a youtube video I got from another application (opened in newpipe through the share with feature). At first it played. Then I somehow paused the video/escaped full screen, and since then I got this "Could not play this stream" message. It also appeared when I tried again to open the video after a phone reboot from history.

### Logs
Joined are very big logs (thousand lines). Although the many lines of AAC errors doesn't have the same PID as NewPipe, this is definitely related, as when I reproduce the issue by trying to tap Play, it throw away this very large amount of logs, including these AAC errors.

[newpipe-logs.txt](https://github.com/TeamNewPipe/NewPipe/files/5412019/newpipe-logs.txt)

### Device info

 - Android version/Custom ROM version: Android Marshmallow/6.0.1; Sony stock ROM
 - Device model: Xperia Z3 Compact

**Comment by opusforlife2** [comment]
Related: #1265.

**Comment by AudricV** [comment]
> I get this error report with these logs (probably unrelated to this issue)

Yes, it is unrelated and has been already fixed (you're not using 0.26.1 which is currently the latest version).

> Couldn't reproduced the same issue

Based on your feedback, I am closing this issue as fixed, thanks for your comment.
