### ISSUE TITLE
[feature request] few small modifications to AndroidManifest.xml - global hardware acceleration and large heap - massive performance improvement for low-end devices.

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#4575]
I found that the following modifications to the android manifest xml,  
result with a much better performances on several low-end devices.  
<code>android:hardwareAccelerated="true" android:largeHeap="true"</code>.  

and (optionally)  
![Screenshot_20201021-052437-01](https://user-images.githubusercontent.com/415238/96665867-8722f200-135e-11eb-9580-609dba2ba9ee.jpeg)

Optionally for production builds I set explicitly: <code>android:debuggable="false" android:appCategory="productivity"</code>.  

And this was meant for for a 'straight up' http connection <code>android:usesCleartextTraffic="true"</code> but it makes connections less buggy for some reason on any protocol. not sure why.

all those are added to <code>&lt;application</code> to effect all views/activities.  

<a href="https://github.com/TeamNewPipe/NewPipe/files/5576365/newpipe_v198.0.22.2_mod_nolanguages_hardwareacceleration_nodebug_oldui_newextractor_signed_aligned.apk.zip">newpipe_v198.0.22.2_mod_nolanguages_hardwareacceleration_nodebug_oldui_newextractor_signed_aligned.apk.zip</a>  
<a href="https://github.com/TeamNewPipe/NewPipe/files/5478241/NewPipe_v0.20.2_mod_nodebug_nolanguages_largeheap_globalhardwareaccelerated_signed_aligned.apk.zip">NewPipe_v0.20.2_mod_nodebug_nolanguages_largeheap_globalhardwareaccelerated_signed_aligned.apk.zip</a>  

I'm doing my modding the lazy way with APKTool, then sign with my generic keystore and 4byte align.  
since I prefer the default English I also delete all of the languages (original APK is about 7.5MB, modded one is 4.80MB)

<del><em>all reference is in android developer docs... (yes, lazy).</em></del>
<strong>edit:</strong>  
<a href="https://developer.android.com/guide/topics/graphics/hardware-accel#application-level">https://developer.android.com/guide/topics/graphics/hardware-accel#application-level</a>, <a href="https://developer.android.com/guide/topics/manifest/application-element#hwaccel">https://developer.android.com/guide/topics/manifest/application-element#hwaccel</a>.  
<a href="https://developer.android.com/guide/topics/manifest/application-element#largeHeap">https://developer.android.com/guide/topics/manifest/application-element#largeHeap</a>.  

  
note: since I use a different signature you need to uninstall previous versions if you want to install it (can still import settings of course..).

**Comment by mhmdanas** [comment]
Mind making a PR for this?

**Comment by TheAssassin** [comment]
You seem to have blocked Team NewPipe. Therefore, we will close this issue now. If you unblock us, we can reopen the issue.
