### ISSUE TITLE
Question: Regarding Invidious Instances

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [TeamNewPipe/NewPipe#4576]
Hey there,

I can see that there is [a project for invidious support](https://github.com/TeamNewPipe/NewPipe/projects/16). However, I'm not sure if it for making it possible to watch videos from one of several invidious instances out there. It appears to me to a project to merely:
1. Share videos with invidious links
2. Login to invidious accounts
3. Accepting Invidious' speed parameters.

I was wondering if there is work going on to actually support the various invidious instances for playback. Perhaps an option to switch to an invidious instance instead of just normal YouTube? If such work is not on-going, could it be possible to have that feature? An Invidious support in the same vein as PeerTube support? That would be super helpful.

Also, thank you for the awesome software!

**Comment by opusforlife2** [comment]
There are PRs which will implement proper Invidious support. You can search PRs here and in the Extractor and find them pretty easily.

**Comment by peanutbutterandcrackers** [comment]
@opusforlife2 - Hey there, is this the right place to follow the developments: https://github.com/TeamNewPipe/NewPipe/projects/16 ?

**Comment by opusforlife2** [comment]
@peanutbutterandcrackers https://github.com/TeamNewPipe/NewPipeExtractor/pull/352

**Comment by peanutbutterandcrackers** [comment]
@opusforlife2 - Thank you very much!
