### ISSUE TITLE
[Bug] NewPipe plays the same video the whole time

### ISSUE THREAD

**Issue by Shimakima** [TeamNewPipe/NewPipe#458]
When NewPipe is called from another app and has autoplayed enabled, once you go back NewPipe relaunchs the video again.
If you press the back button twice, you exit from the app, but when you press it once, realaunchs the video

**Comment by milesbennetdyson** [comment]
I thought it was just me! It only started happening with the new update. Love the app, but this is quite annoying. Still better than Youtube app!

**Comment by theScrabi** [comment]
Oh yes that might be.
