### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by kiehl77** [TeamNewPipe/NewPipe#4581]
please new menu button button to sort the videos from short to long duration,and swipe from the right page of newpipe to access downloaded videos,and everytime i play the downloaded video using external player(i use mx player),the newpipe was closed and i have to open newpipe again and start typing my searching again
`<!--` The comments between these brackets won't show up in the submitted issue (as you can see in the preview). -->

### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by opusforlife2** [comment]
Edit your issue and fill the template properly.
