### ISSUE TITLE
[REQUEST]Previous selection of bottom bar is very annoying

### ISSUE THREAD

**Issue by B1530P** [TeamNewPipe/NewPipe#4583]
**Add setting to turn off this bar.**

I'm not sure, but I think this bar is the reason why the popup player doesn't work properly.
and, If you have already selected a video and have a bottom bar, selecting a different video and pressing the back button will always return you to that selected video screen, which is very annoying.

It's also annoying to always choose the quality when playing the video.

**Comment by opusforlife2** [comment]
There are bug report and feature request templates given at https://github.com/TeamNewPipe/NewPipe/issues/new/choose. Don't open blank issues like this.
