### ISSUE TITLE
Notification control isn't needed when watching video in normal mode.

### ISSUE THREAD

**Issue by demonff1** [TeamNewPipe/NewPipe#4584]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Please remove notification when watching videos in normal mode.
There is no need for seamless transition from normal to background by default unless I ask for it specifically like the background button in earlier version.

#### Is your feature request related to a problem? Please describe it

Notification gets clustered and there is privacy concerns that anyone can see what I watched even I shoved to home tab.

#### Additional context

It's acceptable if I play in background to have notification controls but not so much. And I should click on the background tab like earlier version to have seamless transition from normal to background mode.

**Comment by opusforlife2** [comment]
If you had read the blog post, you would know why the notification has been added for normal mode. It's not just there for fun, you know?
