### ISSUE TITLE
Video Details tab is in landscape after watching video.

### ISSUE THREAD

**Issue by demonff1** [TeamNewPipe/NewPipe#4586]
### Checklist

- [x] I am using the latest version. 
- [ x] I checked, but didn't find any duplicates of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Newpipe'
2. Press on 'any video'
3. Watch on fullscreen where landscape is default

### Actual behaviour

Now after finishing video, if u go back to video details page/ overview, it's in landscape mode even though my phone is set to portrait mode.

### Expected behavior

It should be that the overview page to be in portrait even though I watched a vid in landscape.

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: 
![Screenshot_2020-10-21-20-36-32-533_org schabi newpipe](https://user-images.githubusercontent.com/68889858/96735221-25ee3380-13dd-11eb-89b5-a21480fc48f0.jpg)

**Comment by opusforlife2** [comment]
Tap the Back button. It will rotate the phone back to portrait mode.

**Comment by demonff1** [comment]
Using the cross button should also make the app in default portrait mode. It's a minor bug n the tab is present in the bottom of u click the cross button.

**Comment by opusforlife2** [comment]
Could you change your issue to say that instead, then? Thanks.
