### ISSUE TITLE
Background Player: notification seek bar and time progress stuck when player plays other songs

### ISSUE THREAD

**Issue by leewp14** [TeamNewPipe/NewPipe#4590]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a YouTube song with background player. 
2. Go back to search another song and play it in background player. 
3. Swipe down the notification panel, the NewPipe notification will have a stucked seek bar and time progress. 

### Actual behaviour
The NewPipe notification will have a stucked seek bar and time progress from the previous song, and will remain stuck unless the player is being closed and activated again. 

### Expected behavior
The NewPipe notification should have the current song's time and playing progress after changing songs. 

### Screenshots/Screen recordings

https://streamable.com/fpou5o

### Logs

*none*

### Device info

 - Android version/Custom ROM version: 9/Havoc 2.8
 - Device model: SM-N910G

**Comment by opusforlife2** [comment]
Your Android version is 10, not 9. There is no seek bar on 9.

**Comment by leewp14** [comment]
> Your Android version is 10, not 9. There is no seek bar on 9.

I'm using custom ROM, so probably it is backported. Please refer to my attached video for reference.

**Comment by leewp14** [comment]
Maybe someone with lineage16 (which also has this seekbar media notification) or any android 10 device can check on this issue. If it's not reproducible then will consider as a ROM specific issue, and I will close this issue.

**Comment by opusforlife2** [comment]
LineageOS *17.1 (16 is Android 9). Interesting that the feature was backported.

Anyway, a user reproduced this on Android 10, so it's not your ROM. Something about the feature itself.

**Comment by 532910** [comment]
![Screenshot_20201114-230524_NewPipe](https://user-images.githubusercontent.com/14617699/99156013-903d7f80-26ce-11eb-8de0-04bf06b97398.png)

Am I right this issue is show on the screenshot? But I dunno how to reproduce it.

**Comment by yephny** [comment]
So am I on LineageOS Android 10.

**Comment by nourserry** [comment]
I'm having a variation of this issue, where the track duration is stuck to that of the first track played, but the time progress and seek bar work.
Then when the seek bar reaches the duration length , only time progress continues. 
![Screenshot_20230302_195217](https://user-images.githubusercontent.com/59970301/222513229-ebda2d90-00f5-4175-8c59-95b01447b273.jpg)
![Screenshot_20230302_195336](https://user-images.githubusercontent.com/59970301/222513240-06f70a4f-e252-4cd5-9900-81160ddeaa51.jpg)

Device: Huawei P30 Lite
Android 10
