### ISSUE TITLE
Background Player: current song won't replay when user plays again

### ISSUE THREAD

**Issue by leewp14** [TeamNewPipe/NewPipe#4591]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a song in background **from the beginning** till finish. 
2. Play the song again by clicking the play to background option

### Actual behaviour
After the current song ended, the player cannot replay the song when user click to play the song again. It seems like the play in background button plays from last location, because if you jump the time (seek) and let the song play finish, pressing the play to background button will actually play from the time that you seek just now. 

### Expected behavior

The player should replay the song from beginning when user clicks to play again in background, if the song has finished playing. 

### Screenshots/Screen recordings

https://streamable.com/wodfdn

### Logs

*none*

### Device info

 - Android version/Custom ROM version: 9/Havoc 2.8
 - Device model: SM-N910G

**Comment by tsiflimagas** [comment]
This is fixed by #7014 is guess.

**Comment by AudricV** [comment]
Is it still an issue on 0.26.1?
