### ISSUE TITLE
Background Player: when buffering, the in-app bottom player bar shows play button instead

### ISSUE THREAD

**Issue by leewp14** [TeamNewPipe/NewPipe#4593]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a song and try to simulate a network disconnection. 

### Actual behaviour
The player enters buffering and the NewPipe notification shows buffering icon correctly. However in app, the bottom player bar shows a clickable play button. 

### Expected behavior
When buffering, the bottom player bar in app should show buffering/loading or relevant icons indicating that the player is buffering, and shouldn't be clickable. 

### Screenshots/Screen recordings

![Screenshot_20201022-075957](https://user-images.githubusercontent.com/17796518/96802882-6382a900-143d-11eb-8243-1fd620cbd5ec.jpg)

### Logs

*none*

### Device info

 - Android version/Custom ROM version:  9/Havoc 2.8
 - Device model: SM-N910G

**Comment by ShareASmile** [comment]
is it still a issue on v0.27.0 ?
