### ISSUE TITLE
Question: Please, how do I turn this 'feature' off?!?

### ISSUE THREAD

**Issue by puppykickr** [TeamNewPipe/NewPipe#4597]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

Question...
OMG
How can I turn this most annoying 'feature' off?
I can't get rid of it, and it is driving me insane!

![Screenshot_2020-10-22-07-06-01](https://user-images.githubusercontent.com/44860287/96869811-9a54c100-1435-11eb-9eb8-1d0575f48602.png)

Specifically, the area at the bottom that relentlessly returns me to whatever video I already saw.

Please, for the love of all that is holy, tell me how to get rid of that 'feature'!

**Comment by opusforlife2** [comment]
The checklist isn't optional. Please do what it says and then edit your issue.
