### ISSUE TITLE
Search page: sorting

### ISSUE THREAD

**Issue by roytam1** [TeamNewPipe/NewPipe#4599]
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Inside filter panel of youtube's search page, there is "Sort by" section for sorting videos by:
Relevance
Upload date
View count
Rating

#### Is your feature request related to a problem? Please describe it

People can't find latest video regarding search terms.

#### Additional context

cross reference: issue #2251

#### How will you/everyone benefit from this feature?

the default sorting can't search for latest video regarding search terms, having "sort by" menu can help people to find their interested videos easily.

**Comment by pavi2410** [comment]
I'd like to work on this issue

**Comment by SameenAhnaf** [comment]
@opusforlife2 This should be closed, I think.

**Comment by opusforlife2** [comment]
BTW, no need to ping specific members, Sameen. Any member who is maintaining issues at the time can handle it.
