### ISSUE TITLE
Audio backgound mode!

### ISSUE THREAD

**Issue by KarmaLoco** [TeamNewPipe/NewPipe#4602]
While on audio mode if I were to watch video then it starts from the beginning - not where I stopped.

Thanks for reporting an issue with NewPipe. To make it easier for us to help you please enter detailed information in the template we have provided below. If a section isn't relevant, just delete it, though it would be helpful to still provide as much detail as possible.
-->

### Checklist

- [x] I am using the latest version. 
- [ ] I checked, but didn't find any duplicates of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: 10
 - Device model: Asus ZenFone 6

**Comment by opusforlife2** [comment]
Please edit your issue and fill in the template properly with all the details.
