### ISSUE TITLE
Parse error with New pipe 0.20.0

### ISSUE THREAD

**Issue by lameventanas** [TeamNewPipe/NewPipe#4603]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by lameventanas** [comment]
Steps to reproduce:
1. Click on Search
2. Look for "trump 60 minutes video"
That's it, there are no results, instead I get this exception:

{"user_action":"searched","request":"trump 60 minutes video","content_language":"en","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.20.0","os":"Linux Android 10 - 29","time":"2020-10-23 05:49","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:203)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:222)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:298)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:233)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)\n\tat org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:55)\n\tat org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:81)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(Unknown Source:8)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \"window\\[\"ytInitialData\"\\]\\s*=\\s*(\\{.*?\\});\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:72)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:200)\n\t... 20 more\n"],"user_comment":""}

**Comment by SFR-git** [comment]
0.20.0 *isn't* the latest version. 0.20.1 is.

**Comment by B0pol** [comment]
Yup. It was fixed in 0.20.1

**Comment by opusforlife2** [comment]
@lameventanas Next time, when you tick the box ` I am using the latest version. `, then actually make sure you're on the latest version, don't assume it. It saves us all time.

**Comment by lameventanas** [comment]
Of course, that's the first thing I checked.
I installed it from droid, and it is the latest available there.
I guess they haven't updated it yet.

**Comment by opusforlife2** [comment]
The comment next to it in the template asks you to compare the version in About to the latest version on the Releases page, not F-Droid.
