### ISSUE TITLE
Idea to really improve NewPipe - i cards and the videos/icons that show at the end of some videos.

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#4607]
Sometimes I watch a video and at the end they point in the air and say something along the lines of "Check out this video, YouTube reccomends it to you" and also I would like to see the I card because it feels kinda weird. I've been using the app for years, but this is the one thing that feels wrong. These would be cool additions.

**Comment by opusforlife2** [comment]
Duplicate of #2854. Always check before opening a new issue.
