### ISSUE TITLE
Unlikely to happen, but maybe a new pipe website? 

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#4608]
Not much to say. It would be cool for PC users to be able to use newpipe.

**Comment by mhmdanas** [comment]
@HTSamurai you may want to try FreeTube. It's a desktop frontend for Youtube.

**Comment by mhmdanas** [comment]
Wait, sorry, it's not a duplicate.

**Comment by selurvedu** [comment]
What do you mean by "NewPipe website"? There's https://newpipe.net
If you mean a version of NewPipe that is usable in a web browser, see https://github.com/iv-org/invidious and #1051. It's highly unlikely NewPipe will ever get a web version since it's a native Android app and you can't simply port it to web.

**Comment by HTSamurai** [comment]
Yes I meant for use in a browser

**Comment by HTSamurai** [comment]
(Why did this get a comment so much later though, I thought this was closed)

**Comment by mhmdanas** [comment]
@selurvedu well, you can use NewPipeExtractor in a website's backend, and some people are already experimenting with that (e.g. https://github.com/TeamPiped/Piped).

@HTSamurai this issue wasn't closed, but I personally find it unlikely to happen. Others may create websites with backends using NewPipeExtractor, but an official NewPipe web version doesn't sound like it's happening, for me at least.

**Comment by selurvedu** [comment]
@mhmdanas

> Piped

That's interesting, thank you. I thought of mentioning a possible use of extractor for building a website, but the question was about NewPipe itself, so I disregarded that.

**Comment by mhmdanas** [comment]
I'll be closing this issue since we currently don't plan to do this. You can check out [Piped](https://github.com/TeamPiped/Piped) instead.
