### ISSUE TITLE
Google is blocking non-logged in users

### ISSUE THREAD

**Issue by JaapJoris** [TeamNewPipe/NewPipe#4609]
Since Google rolled out the "cookie consent banner" changes, the website www.youtube.com has become nearly unusable for non-logged in users. Here's what happens:

1. You open an incognito/private browser window.
2. You request _any_ youtube.com URL (video link, search results, etc.)
3. The following cookie popup appears: ![banner](https://user-images.githubusercontent.com/9511578/97005012-205c2f00-153e-11eb-92f6-295d096bd472.png)
4. Then, the next banner appears: 
![banner](https://user-images.githubusercontent.com/9511578/97005236-77fa9a80-153e-11eb-93e8-0274ed9bd390.png)
5. After clicking "No thanks", the video fails to play...

NewPipe also crashes sometimes (it would be nice for it to have better auto-recover features), but at least it's more usable for me than the youtube website. I am worried that Google might one day decide to block non-logged in users completely, at which point NewPipe also would become unusable.

**Comment by mhmdanas** [comment]
Please fill out a template when opening an issue.

**Comment by kidcuddi** [comment]
Having error issues. Every time I try to use newpipe I get an error. No lodi g

**Comment by NathanielJS1541** [comment]
This should be dedicated to NewPipe issues. Any issues with YouTube are irrelevant and shouldn't be mentioned?

**Comment by opusforlife2** [comment]
This is not fit for discussion in our issue tracker because it's not a Newpipe issue. However, you're most welcome to discuss it more on  our IRC channel.
