### ISSUE TITLE
Thousands abbreviation in shortened numbers in English should be K not T

### ISSUE THREAD

**Issue by jkollross** [TeamNewPipe/NewPipe#461]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

K is the most frequently used abbreviation for thousands. T is almost never used; it usually represents trillions. Please change the abbreviation to K.

**Comment by theScrabi** [comment]
Oh you are right xD tnaks.
