### ISSUE TITLE
optional automatic fullscreen playback setting

### ISSUE THREAD

**Issue by ShrimpBFM** [TeamNewPipe/NewPipe#4617]
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one feature request. I will open one issue for every feature I want to request.

I would like an option to have the video player behave as it did a couple of versions ago.
By that I mean that if you click a video, the player automatically goes fullscreen and then starts playing the video.

As someone who only watches videos in fullscreen, what I had to do for complete fullscreen playback (begiining to end of the video) in the past was the following: 
- tap on the video.

Now with the new player I have to do the following:
- tap the video
(it starts playing)
- tap it again to make the player HUD appear
- tap the small fullscreen symbol
- tap the video to make the HUD appear
- rewind the video so I can watch it in fullscreen from the beginning

An optional setting to turn the player back to it's old behavior would be appreciated.
If the behavior of the new player should be desired in certain instances, the user could still use the buttons for popup or background playback to achieve the same effect, without the inconvenience of having to go back to the options and switching the setting back.

The benefit for everyone would be more customization to the users' personal preferences of how they'd like NewPipe to function.

**Comment by opusforlife2** [comment]
Didn't come across #4152 when you searched for duplicates?
