### ISSUE TITLE
Youtube-dl disabled due to a DMCA takedown. We are next.

### ISSUE THREAD

**Issue by imShara** [TeamNewPipe/NewPipe#4618]
![2020-10-24_00-11](https://user-images.githubusercontent.com/4913196/97054501-8f14a900-158d-11eb-8ec3-f218e2b5d7c2.png)

https://github.com/ytdl-org/youtube-dl

Need to move to standalone git or p2p repo.

**Comment by partacce** [comment]
NewPipe should immediately remove the screenshot of downloading Adele's Skyfall. This was one of the points they mentioned as a reason: The Readme gives introductions on how to download a copyrighted song.

**Comment by ValdikSS** [comment]
When my account had been blocked, people recommended me the following services:

https://notabug.org/
https://gitgud.io/
https://codeberg.org/
https://repo.or.cz/

**Comment by krystean** [comment]
> NewPipe should immediately remove the screenshot of downloading Adele's Skyfall. This was one of the points they mentioned as a reason: The Readme gives introductions on how to download a copyrighted song.

And screenshots that include the "Download" button.

**Comment by ValdikSS** [comment]
There's also distributed p2p github alternative: Git Center on ZeroNet network. It's very cool, but not very good UI-wise and not bug-free. But it's totally censorship-free.

**Comment by izzues** [comment]
Also, someone better make a backup of whatever isn't in the repo itself (e.g. issue pages) ASAP!

**Comment by ValdikSS** [comment]
>NewPipe should immediately remove the screenshot of downloading Adele's Skyfall.
>And screenshots that include the "Download" button.

No, please don't do that. By removing the information which RIAA (or any other DMCA copyright claimer) doesn't like now, you're openly telling you will obey their blatant demands in the future.

This crap should be handled with technologies, and not by putting our heads to the sand hoping they won't spot the project.

**Comment by krystean** [comment]
Remove screenshots from README. They're unappealing. Until we find suitable ones, section must be removed.

**Comment by RainbowAsteroids** [comment]
Did this happen just now?

**Comment by Kein** [comment]
Removing them wont do anything, they are part of repo history and can be easily referenced and will withstand scrutiny.

The only way out of this is different source hosting as suggested above.

**Comment by imShara** [comment]
Also, project can be exported to standalone https://gitlab.com/ instance via [GitHub importer](https://docs.gitlab.com/ee/user/project/import/github.html)

**Comment by RainbowAsteroids** [comment]
Will GitLab be any better? I think running a standalone git may be best for the long term.

**Comment by partacce** [comment]
> Will GitLab be any better? I think running a standalone git may be best for the long term.

You can host GitLab yourself

**Comment by Kein** [comment]
That wont really stop them going up-the-chain, to ISP, though. I guess you could try to find a hosting in some god frosaken 3rd world hole that gives 0 shit about international DMCA claims, but it is gonna be quite some effort, probably high price as well and terrible quality. Most likely also IP-range banned in USA and some other western countries due to aforementioned perks.

**Comment by Pentaphon** [comment]
Time to self-host Gitlab. Microsoft won't be defending us.

**Comment by dakotagrvtt** [comment]
> Also, project **with whole issues and e.t.c** can be exported to standalone https://gitlab.com/ instance via [GitHub importer](https://docs.gitlab.com/ee/user/project/import/github.html)

@TobiGr @Stypox @wb9688 @theScrabi @mauriciocolli 
@TeamNewPipe can [export their GitHub data](https://github.blog/2018-12-19-download-your-data/) to backup all of the issues, pull requests, releases, etc. Hopefully they catch this in time.

**Comment by piegamesde** [comment]
None of you seem to have contributed to this project, yet to are talking about decisions like you were maintainers. This is not constructive. Please lock the thread to collaborators only.

**Comment by ValdikSS** [comment]
@Kein DMCA is applicable only in the USA. As long as you host in another country, or rent the VPS from the hoster registered not in the USA, you're fine. OVH with the server in France, for example, does not react to DMCA emails and does not require for you to answer them.

This is offtopic though. Let's restrain from offtopic discussions.

**Comment by Kein** [comment]
@ValdikSS Incorrect, as a part of international copyright law and countries that respect it there are some variations of DMCA-like claims that are respected by the aforementioned countries. 
For your example: https://www.reddit.com/r/wowservers/comments/3zbg83/dmca_notice_on_ovh_eu_france/

**Comment by Pentaphon** [comment]
> None of you seem to have contributed to this project, yet to are talking about decisions like you were maintainers. This is not constructive. Please lock the thread to collaborators only.

I think it's worth allowing users to voice their concerns about the project for at least one public thread until countermeasures are set up.

**Comment by locutus** [comment]
@Kein From what I know Switzerland has pretty good laws regarding streaming and downloading content: Legal for private use independent of source as long as you do not upload anything. That implies that something like youtube-dl should not infringe swiss law and therefore could not be taken down by a DMCA takedown notice easily.

**Comment by markozajc** [comment]
IANAL, but from what I know France is a good option as well. VideoLAN seems to explain that more in-depth here: https://www.videolan.org/legal.html

**Comment by cha0t1c1** [comment]
The F-Droid page still has problematic screenshots, like a download dialog for Adele - Skyfall.

**Comment by 6543** [comment]
I just recomend [Codeberg](https://codeberg.org/) because:
 * hosted in the EU (no DMCA takedown should be posible)
 * has a build in migrator for github
 * is explicit for OpenSource Projects

**Comment by cha0t1c1** [comment]
OVH is lax, but in recent years they have started taking down sites, so I wouldn't recommend them.

Jurisdiction is half of the equation, the hosting provider looking the other way is the other half. I know of three data centers in Europe that will ignore DMCA and only start caring when the legal system in their jurisdiction gets involved. A reseller of the most warez friendly of the three is selling VPS for an affordable price and they accept crypto. The reseller also has quite a reputation for not complying with DMCA. If anyone running this project wants to know more, I'll tell them in private. Not knowing who the hosting provider is makes it a lot more difficult to take down. Then just slap [DDoS-Guard](https://ddos-guard.net/en/store/web) on top of it and let their vodka powered servers take the heat. They're a CDN based in Russia that couldn't care less about copyright. They're the reason Nyaa (the world's largest public anime torrent tracker) never has DMCA takedowns.

**Comment by 6543** [comment]
https://codeberg.org/Codeberg/Community/issues/314

**Comment by cha0t1c1** [comment]
@6543 Just because a site is hosted in Europe does not mean that they're immune to DMCA. A lot of European hosting providers still view DMCA notices as valid copyright infringement notices. Codeberg in particular is a German organization hosted by Hetzner in Germany. Hetzner does not allow public piracy on their servers and Germany has some of the strictest copyright laws in the world (they're pretty much up there with the US).

**Comment by Mhowser** [comment]
I think we should look into using git-ipfs as either the main repo or a mirror.

https://docs.ipfs.io/how-to/host-git-style-repo/

**Comment by TheAssassin** [comment]
We're locking this discussion, as there's a lot of speculation and off-topic discussions. Be assured, the maintainer are informed and develop backup concepts.

We will post a statement once we finished analyzing the situation. NewPipe's situation isn't completely comparable with the situation of youtube-dl, as far as I can see.

**Comment by TheAssassin** [comment]
Please see https://newpipe.schabi.org/blog/announcement/youtube-dl-dmca-analysis/. It links to an in-depth analysis of the situation.

In any case, any kind of actionism does not make sense, and spreading misinformation is a bad idea as well. Moving from one big service to another is also not useful in any way, as they might be sent takedown letters as well. Self-hosting is not an option for us either, as we don't have the resources to take care of all the legal implications that come with that (e.g., data protection).
Be assured we're taking steps to mitigate the potential risks of being taken down. A discussion is going on in e.g., #4619.

I think that the youtube-dl takedown will have to end up in court, whose decision is either positive for us (and will prevent similar attacks in the future), or shows that we need better laws in the context of copyright. But right now, let's rather focus on improving NewPipe than waste time thinking about hypothetical situations!
