### ISSUE TITLE
System UI keeps stopping!!!

### ISSUE THREAD

**Issue by arid12** [TeamNewPipe/NewPipe#4621]
### Checklist

- [x] I am using the latest version - 0.20.1 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

when i enqueing any video in the background or playing the video. 

### Actual behaviour
 phone display flickers for some time then phone gets restarted, some of the times displaying the message 'system UI keeps stopping'.

### Expected behavior
the video gets played without restarting the phone. No error with the previous versions. 

### Device info

 - Android version/Custom ROM version: 10
 - Device model:motorola one power (p30 note)

**Comment by opusforlife2** [comment]
The checklist isn't optional, mate. Please edit your issue and fill it properly. Closing until then.
