### ISSUE TITLE
Design proposal: customized layout

### ISSUE THREAD

**Issue by Mallegrissimo** [TeamNewPipe/NewPipe#4622]
It's a great app.

Any plan to support customized layout?
(or provide some layout templates for user to choose)?
Customized layout such as:
1. Display [what's new] instead of [Trending] as landing page.
2. Similar to above customize landing page tabs to [what's new], [subscriptions], [history]

**Comment by vkay94** [comment]
You can change the order in the settings. Go to Settings -> Content -> Content of main page and set "What's New" to the first position and so on.
