### ISSUE TITLE
ParsingException: Could not get ytInitialData

### ISSUE THREAD

**Issue by SArsalanK** [TeamNewPipe/NewPipe#4625]
**ParsingException: Could not get ytInitialData**

{"user_action":"searched","request":"Slow motion SONG","content_language":"en-GB","content_country":"GB","app_language":"en_GB","service":"YouTube","package":"org.schabi.newpipe","version":"0.20.1","os":"Linux Android 5.1 - 22","time":"2020-10-24 09:09","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:203)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:222)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:298)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:233)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)\n\tat org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:55)\n\tat org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)\n\tat org.verox.videodownloaderforyoutube.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:81)\n\tat org.verox.videodownloaderforyoutube.util.-$$Lambda$ExtractorHelper$-LvMJ9Du27js1ZqnWfooOqpDZc8.call(lambda)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)\n\tat java.lang.Thread.run(Thread.java:818)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \"window\\[\"ytInitialData\"\\]\\s*=\\s*(\\{.*?\\});\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:72)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:200)\n\t... 21 more\n"],"user_comment":""} /
Type a message

**Comment by xibr** [comment]
This issue was solved, in version 0.20.1 did you change the version number?

**Comment by opusforlife2** [comment]
Did you read the issue template carefully?
