### ISSUE TITLE
Wish: mp4-format as standard 

### ISSUE THREAD

**Issue by Spielmops** [TeamNewPipe/NewPipe#463]
Smartphones are built with a graphics-chip, that can decode mp4 in hardware. So it should be possible to set not only the video-size but the video-format. Webm is a god format but brings phones often to stutters.

Spielmops

**Comment by mission712** [comment]
MP4 format is a patented and a non-free format. I do not support this.

**Comment by turboteckel** [comment]
Would be nice to have it as a default option for downloading. More a quality of life change than anything else.

**Comment by Spielmops** [comment]
> MP4 format is a patented and a non-free format. I do not support this.
I read the same years ago written by the mozilla-developers-team. And now the standartd-plugin is "mp4-codecs". Fact is the mp4-hardware-decoding ability of smartphones and fact is: if normal users get stuttering video-playing, then Newpipe is out, deinstalled, gone, forget it ....

**Comment by theScrabi** [comment]
We could add something to the settings than you guys can select your favorite format.

**Comment by Spielmops** [comment]
> to **set** not only the video-size but the video-format
That all I wished for ....

**Comment by utack** [comment]
@mission712 you already supported all proprietary codecs by buying a phone that can decode them in hardware  
Might as well use that capability now

**Comment by fbis251** [comment]
I understand that there's the free vs proprietary codec aspect to this, but making this an option in the settings would be great. Each user would then be able to pick their preferred default codec

**Comment by theScrabi** [comment]
All right :)

**Comment by sebma** [comment]
Hi, the default 360p format in Newpipe 0.9.0 is WebM, but my problem is that WebM video does not show on my device, only the audio works.

Therefore, I'm really interested in this feature of being able to change the default format because I have to select MPEG-4 360p each time I want to play a video and it's a pain...

**Comment by theScrabi** [comment]
All right I added a preferred preference, so you can choose your favorite format.
Will be available with 0.9.1

**Comment by sebma** [comment]
Thanks a lot :)

**Comment by Spielmops** [comment]
**Herzlichen Dank!**
Spielmops
