### ISSUE TITLE
Tracks Skipping 5 Seconds Into the Song

### ISSUE THREAD

**Issue by Moon-Palace-16** [TeamNewPipe/NewPipe#4637]
### Checklist

- [x] I am using the latest version - 0.20.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Use the skip track or previous track buttons, either on the app itself or on headphones. Sometimes this also happens even if you don't skip a song, and it plays through the queue normally.

### Actual behaviour

The app skips forwards/backwards or rewinds the track, but it skips the first 5 seconds of the song.

### Expected behavior

It should move to the beginning of whatever song you've skipped. If I want to hear a song again, the previous track button should go to the beginning of the song, not five seconds in. Similarly, if I skip to the next track, or move to a previous one, I should not miss 5 seconds of the track. Pressing the previous button again when it does this doesn't work. It then moves to the previous track, but 5 seconds into it.

I've never had an issue with this in previous versions of the app, and I use this app almost every day, and for hours each day.

### Device info

 - Android version/Custom ROM version: Android 5.1.1 (Lollipop)
 - Device model: Samsung Galaxy S5

**Comment by opusforlife2** [comment]
Please edit your issue and fill the template properly.

**Comment by Moon-Palace-16** [comment]
I edited it. Is it alright now?

**Comment by opusforlife2** [comment]
Thanks!
