### ISSUE TITLE
"no results" error PERMANENTLY

### ISSUE THREAD

**Issue by Electromaxim** [TeamNewPipe/NewPipe#4648]
I'm getting "no results" error permanently when try to search any item, regardless of what is it: video, channel, playlist etc.
In a search bar I start typing a search word, I can see drop-down list of popular search terms. However once I tap any of them it brings me to the same gray screen: "no results". 
I've updated the app to the latest version, it didn't help;
I've deleted, rebooted and reinstalled the app from scratch, this didn't work either;
I'm using latest Xiaomi shell on tip of the latest Android version and the version ig the app is now 0.20.0

**Comment by xibr** [comment]
latest version  is 0.20.1, Please before opening a new issue check if there is one, also the issue template not optional.

**Comment by opusforlife2** [comment]
@Electromaxim Don't delete the template next time.

**Comment by Electromaxim** [comment]
Please read carefully the description, this is NOT exactly the same issue as described in the adjacent topic

**Comment by opusforlife2** [comment]
> Please read carefully the description, this is NOT exactly the same issue as described in the adjacent topic

Well...
> and the version of the app is now 0.20.0

> **latest version is 0.20.1,** Please before opening a new issue check if there is one

**Comment by Electromaxim** [comment]
> @Electromaxim Don't delete the template next time.

Which template? Error report generated by the app? I've attached it above

**Comment by opusforlife2** [comment]
Can you read the bold part in my comment above yours?

**Comment by Electromaxim** [comment]
Nothing changes. Version 20.0/_.1/_.02 
the same error. The app isn't working. Can you at least take a look before closing the issue?

**Comment by opusforlife2** [comment]
> Can you at least take a look before closing the issue?

Not if you don't follow the template and provide required information, no.

So, to be doubly sure, you're on version 0.20.2 now? Do you get the same crash report as the one you linked in the top comment? Can you paste it here?
