### ISSUE TITLE
unable to play Amazon channel YouTube videos

### ISSUE THREAD

**Issue by srinivasm14** [TeamNewPipe/NewPipe#4649]
Issue:1)
Since this morning, I am unable to play Amazon YouTube channel videos, it is showing the error "couldn't stream" while rest other videos I can view.
Issue:2
Past 3 days, even I am also facing the same issue (app crash) when we click to view any video.

**Comment by opusforlife2** [comment]
Please use the bug report template here: https://github.com/TeamNewPipe/NewPipe/issues/new/choose
