### ISSUE TITLE
Option to not show thumbnail inside notification

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#4651]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
An option to not show the thumbnail on the right side of the notification.

#### Additional context
<img src="https://user-images.githubusercontent.com/41164160/95673077-dcfcda80-0ba5-11eb-9f9e-a298fc66b71a.png" height=300>

**Comment by opusforlife2** [comment]
Why?

**Comment by XiangRongLin** [comment]
I don't like it. In the image above you can see the guy screaming into your face.
And in the wide world of youtube you'll get a lot of more outrageous thumbnails, that are just clickbait at best.

**Comment by Stypox** [comment]
Doesn't the PR removing the lock screen art also solve this?

**Comment by XiangRongLin** [comment]
> 
> 
> Doesn't the PR removing the lock screen art also solve this?

That's what i thought/hoped for too. But it's apparently set at a different place, which i have not found yet.
