### ISSUE TITLE
The new behavior of Newpipe

### ISSUE THREAD

**Issue by Spielmops** [TeamNewPipe/NewPipe#4654]
I find the new operating concept bad, I now need 2 more buttons: the full screen button to enlarge the picture on the whole screen and the close cross to stop the video player. Both buttons are not easy to hit on the smartphone. Instead, the back button no longer does what it should always do: undo the last action. In this way, Newpipe is just as difficult to use as Youtube in the web browser.

When I call up a Youtube link from another app, the picture is shown to me in a small video player and I have to look for the full screen button again. If I am then in full screen, I need the back button 3 times to return to the calling app. So far it was: Calling up the link with Newpipe, the link was played in full screen, back button, back to the starting point.

You don't seriously want to tell me that this behavior is better, do you?

Spielmops

**Comment by opusforlife2** [comment]
Bug trackers aren't for general feedback. They are for tracking individual bugs. You can look for the various issues which your feedback pertains to and add your comments there if you see that your points haven't been mentioned before, or you could join the Newpipe IRC channel to have a conversation. You could also do both.
