### ISSUE TITLE
Switching to other program or program overview ("alt-tab") stops/resets playback

### ISSUE THREAD

**Issue by TheRealMarnes** [TeamNewPipe/NewPipe#466]
If I even so much as go to the alt-tab-ish overview of programs and switch right back to newipe, the video that was playing is reset to a fresh state as if I only opened it upon switching back. Playback continues from 0 and the video has to be downloaded again. Was like this half a year ago when I first tried newpipe too.

**Comment by theScrabi** [comment]
Yes that player window will be recreated anyway.

**Comment by TheRealMarnes** [comment]
Can't it be prevented?

**Comment by theScrabi** [comment]
Hm I can't guarantee when I'll be able to fix that problem, but I'll note it down as urgent.
However you can always of course use an external player like MXplayer or VLC.

**Comment by natrius** [comment]
Sometimes i just want to listen to music and still do something else (without downloading) and its not possible because if you lock the screen for power-saving or change the app for browsing, music stops immediately.

**Comment by theScrabi** [comment]
xD I don't know how often I need to tell this to people (maybe because of bad ui design) NewPipe has an audio only stream function. Tip on the headphones at the video details screen, and you can listen to music.

**Comment by natrius** [comment]
You are kidding... Yepp, works, thanks. And even possible to search another video while its palying. *lol*
What got a bit confusing at first right now was the first video playing at background and starting a new video/song and it plays at the same time. While it may be useful in some situations (you know, start rain and a nice chill song parallel) its confusing for most of the time.

Maybe add an interactive tutorial somehow? You know, when you enter the screen the first time grey anything else out and add a short description to the button. 
Or the easy way, add in settings a point thats like "Play music in background: pres the headphone button at the video detail screen" so i can find it when i search in settings at least.

**Comment by theScrabi** [comment]
Hm I'll keep that in mind.
