### ISSUE TITLE
Impossible de copier guru méditation

### ISSUE THREAD

**Issue by amand76** [TeamNewPipe/NewPipe#4676]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by opusforlife2** [comment]
Please edit your issue and fill the template properly.
