### ISSUE TITLE
求助，作者频道的视频标题原本是中文的，newpipe里全部显示成英文了。。。

### ISSUE THREAD

**Issue by jay00128** [TeamNewPipe/NewPipe#4678]
求助，有没中文地区朋友，我在youtube点开作者频道是中文的，但是导入到newpipe上点开作者频道一看，全部标题变成全英文的了。。。虽然不影响视频观看，但是看着确实难受。。。试过把语言 地区 全部改了都不行。。过来求助。。图片以 美食作家王刚 为例子。。
![Screenshot_20201028-183555_NewPipe](https://user-images.githubusercontent.com/52487796/97439538-3e23fc80-1961-11eb-9545-f1e669416fd9.jpg)
![Screenshot_20201028-183616_YouTube](https://user-images.githubusercontent.com/52487796/97439544-3fedc000-1961-11eb-8cb7-1439a534b401.jpg)

**Comment by Stypox** [comment]
English please, and follow the template

**Comment by opusforlife2** [comment]
@jay00128 See #3089.
