### ISSUE TITLE
All Versions of the New Player 0.20.xxxx Freezes Screen On Fullscreen Mode

### ISSUE THREAD

**Issue by krtfwd** [TeamNewPipe/NewPipe#4679]
### Checklist

- [x] I am using the latest version - 0.20.2
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Find a video
Play the video
Video plays normally like expected without issues
Tilt the phone sideways to get fullscreen / or just press the fullscreen button

### Actual behaviour

Screen Freezes with the latest frame still on the screen / audio mostly keeps playing (somtimes cuts off after a while )
Screen is unresponsive hardware buttons or tapping on anywhere don't seem to work
Only solution is to turn off the phone and turn it back on again

### Expected behavior

Fullscreen videoplayback like normal

### Screenshots/Screen recordings

unable to take a screenshot phone/screen becomes unresponsive

### Logs

unable to get a crash log phone/screen unresponsive

### Device info

 - Android version/Custom ROM version: 7.1.2
 - Device model: Asus Zenfone ZE551ML /Z00A

**Comment by eladkarako** [comment]
Happened to me too,
too often so I'm now only using external player (MX player) with NewPipe,
I suspect the built in player is the cause or maybe the way lineageos uses media decoder.
(see  
https://github.com/TeamNewPipe/NewPipe/issues/4835#issuecomment-723560909  
)

**Comment by krtfwd** [comment]
> Happened to me too,
> too often so I'm now only using external player (MX player) with NewPipe,
> I suspect the built in player is the cause or maybe the way lineageos uses media decoder.
> (see
> [#4835 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/4835#issuecomment-723560909)
> )

yeah mine is a similar lineage fork aswell 
for now i am using this apk someone made that has the old player with the current extractor
 https://github.com/TeamNewPipe/NewPipe/issues/4686
it works fine

**Comment by eladkarako** [comment]
> yeah mine is a similar lineage fork aswell
> for now i am using this apk someone made that has the old player with the current extractor
> #4686
> it works fine

**Thank you very much for sharing this**,  
the 're-build' script there that uses APKTool is very smart,  
essentially updating the smali for the newly created extractor in the old UI,  
as long the method names stay the same it should work nicely.
it even properly sign and align the apk, very nice work indeed!

**Comment by gschaffner** [comment]
I also have this issue on an LG G3 + LineageOS 17.1 (Android 10). For me, freezing isn't restricted to just fullscreen mode. It occurs in portrait mode as well, and still freezes the whole system. Sometimes the freeze recovers without restarting the phone, but sometimes I need to remove the battery and restart the device. I haven't tested the background/popup players but I can if this would be helpful. I've also noticed excessive heat from the phone when playing a video in Newpipe v0.20+, but this may be unrelated.

**Comment by krtfwd** [comment]
Yeah

> 
> 
> I also have this issue on an LG G3 + LineageOS 17.1 (Android 10). For me, freezing isn't restricted to just fullscreen mode. It occurs in portrait mode as well, and still freezes the whole system (including audio). Sometimes the freeze recovers without restarting the phone, but sometimes I need to remove the battery and restart the device. I haven't tested the background/popup players but I can if this would be helpful. I've also noticed excessive heat from the phone when playing a video in Newpipe v0.20+, but this may be unrelated.

I was able to recover the freeze ( very rarely ) by quickly tapping somewhere else before the fullscreen transition once or twice, and overtime realized it does not only happen on fullscreen, it also happens while changing from background player or while executing similar newplayer related features. My phone is bricked atm ( hopefully not related to new pipe ^^. I am sure it's not they say its a mb failure ) I am in the process of picking a new one gonna install LOS 18 or 17.1 on it and see if it crashes there too. Did newpipe overheat my phone to DEATH ? we'll never know ... (  I am almost %100 sure it's unrelated , is there a chance ? now I am wondering... )

**Comment by litetex** [comment]
Is this still a problem?
