### ISSUE TITLE
Unable to view age restricted content

### ISSUE THREAD

**Issue by Educatejag** [TeamNewPipe/NewPipe#4681]
### Checklist

- [x] I am using the latest version - 0.20.2
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
-  [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by Educatejag** [comment]
![Screenshot_20201028-192918](https://user-images.githubusercontent.com/73597016/97446018-e6cb5f80-1953-11eb-846b-2900f8ded429.png)

**Comment by Educatejag** [comment]
Unable to watch age restricted adult contents. I am using version 0.20.2. Earlier I used to watch many semi nude videos etc. Was very enjoyable. Now the feature is missing. Please restore this. I love NewPipe.

**Comment by opusforlife2** [comment]
Confirmed.

**Comment by Kusurisan** [comment]
have the same issue. before updating to 0.20.2 i watched a few age restricted ASMR videos, now i can't anymore. if i click on them on my history it isn't able to play them. if i open them in my browser, they work (after login to bypass the age restriction)

**Comment by Stypox** [comment]
I'm gonna fix this in a few days

**Comment by kubo6472** [comment]
So, adding this here: YouTube's [new age restriction guidelines](https://youtu.be/2gTNFJhSHok)  are limiting it more drastically.

**Comment by Stypox** [comment]
Could you all test TeamNewPipe/NewPipeExtractor#447

**Comment by Stypox** [comment]
@Educatejag  @Kusurisan @spvkgn @argonfilm @prasumoholkar @TippyLion28 @Thundernirmal could you all test the last apk I provided in TeamNewPipe/NewPipeExtractor#447?

**Comment by kubo6472** [comment]
Works on vid I had problems with.

**Comment by huckleberrypie** [comment]
The debug APK works on my end. For those who want to try it out without having to actually watch NSFW content, try the Mafia Game channel as most of their videos are age-restricted for violence.

**Comment by Kusurisan** [comment]
did test the first apk and it seems to work for the videos that had issues for me. couldn't yet test the other videos thought since i'm now not on my laptop anymore.

(tried it out with the channels "Dude thats lewd asmr", "VaryanaHub" and 1-2 others)
