### ISSUE TITLE
Freshly installed 0.20.2 is no more usable on a TV box

### ISSUE THREAD

**Issue by bodqhrohro** [TeamNewPipe/NewPipe#4682]
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Install LazyIPTV.
2. Download/create a playlist with YouTube links.
3. Open the playlist and open some link in NewPipe.

### Actual behaviour

I can't set NewPipe up to open the videos in fullscreen player by default anymore.

### Expected behavior

Before the recent YouTube breakage, I had NewPipe set up to open and play YouTube links in fullscreen when opened from LazyIPTV. I don't remember how already. *Maybe* I opened it in the popup player, enabled the mouse emulation, hit the fullscreen button, and NewPipe remembered that and didn't open the tiny player anymore.

Because of the breakage, I did lots of temporary things: made the settings backup from 0.20.1, wiped the application data several times, then uninstalled NewPipe and installed NewPipe polish (which already had this issue), then I uninstalled NewPipe polish and installed NewPipe 0.20.2. But even after importing the old settings, I can't restore the old behaviour anymore.

I presume this is related to the Unified UI thing. This would be strange though, as the status quo persisted even with the 0.20.1 build from F-Droid (did it have this feature enabled already?) I also can't test the behaviour with old versions, as they don't work with YouTube anymore :(

*(Huh, why do I end every paragraph with **anymore**?)*

### Device info

 - Android version/Custom ROM version: 7
 - Device model: x96 mini

**Comment by opusforlife2** [comment]
Nothing changed between 0.20.1 and 0.20.2 except the exact code which was needed to fix Youtube video playback. Please check your setup again.

**Comment by bodqhrohro** [comment]
Can you then suggest how do I achieve this behaviour? If I hit the fullscreen button in popup mode, it just opens the video info activity, instead of going to fullscreen directly. If I enable an external video player (which was surely disabled though), NewPipe just fails to start with a toast complaining that no streams were found.

**Comment by opusforlife2** [comment]
I don't know your setup, obviously, but from what you describe, maybe instead of the popup player, you enabled autoplay on video details, and used mouse emulation to click the full screen button?

**Comment by bodqhrohro** [comment]
Autoplay was definitely disabled, though it makes the behaviour close to the previous one, thanks. But pressing the Back button now exits the fullscreen, rather than quitting NewPipe completely, like it was before.

I made some investigation and found out that the translations contain `autoplay_by_calling_app_title` and `autoplay_by_calling_app_summary` keys, which don't seem to be used already in the code though. Also, I can't find any autoplay-related setting neither in the recent settings backup nor in the earlier one made in July. So I still presume that there was some special action for opening links from external apps in fullscreen, which was removed from the action list in some version (possibly accidentally), but still remains in the code as a dead action. This explains pretty well why it worked even after I wiped the application data (the action binding still remained), but got broken when I reinstalled the app completely.

**Comment by bodqhrohro** [comment]
Oh, and I recall that I didn't actually have to hit that tiny fullscreen button with the mouse cursor before. When I searched and opened some videos from NewPipe UI, focused the video viewport with D-Pad and pressed OK, it went to fullscreen automatically too rather than starting to play in the tiny viewport.

**Comment by bodqhrohro** [comment]
> I made some investigation and found out that the translations contain `autoplay_by_calling_app_title` and `autoplay_by_calling_app_summary` keys, which don't seem to be used already in the code though.

Nah, bisection has shown that those are remnants of a big rework in cbfe91f36f626fad343d4475f7aefd67e8f28901; that's surely irrelevant as I started using the app this year only.

**Comment by opusforlife2** [comment]
O_o

**Comment by bodqhrohro** [comment]
If that helps, the first version I ever installed on this box seems to be 0.19.3, so it got broken somewhere in between.
