### ISSUE TITLE
Limited Legacy Support for Version 0.19.8

### ISSUE THREAD

**Issue by MapleWheels** [TeamNewPipe/NewPipe#4686]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Temporary legacy support for NewPipe App for version 0.19.8. This would be limited to porting updates from the NewPipeExtractor and critical bugfixes only and would be dropped once usability features are improved. The goal is to simply keep it working as-is.

#### Is your feature request related to a problem? Please describe it
There are a host of issues with the new unified app UI flow which make the new version of NewPipe (0.20.x) very unusable to the point where multiple people I know are switching to alternatives instead of 0.20.x, as recently NewPipeEx got an update.

To list a few (on mobile so cannot link to the multiple issues on tracker):

- Playing a video wipes the background playlist. This makes NewPipe useless as a music player due to;

- Enqueue-ing individual songs from the popup/modal menu in a playlist instead replaces the entire play queue with that playlist instead.

- No quick save/overwrite function for playlists so quick saving the current queue is cumbersome since it requires deleting the old temporary playlists later. This is now an issue due to the above.

- Unified App results in NewPipeExtractor errors in main player clearing the entire play queue as it's treated as a crash (was fine before since queues were separate).

- Audio tracks save their last played timestamp, even when disabled in the settings, so when cycling through songs while driving, if I skip a song track right before it ends, it picks up there the next time the song/audio is played and just effectively skips the track. 

> This is compounded by the 'Fast Forward Silence' feature, which seems to not record that it skipped to the end of the track which results in that track being unplayable (always skips everytime it's played since it starts playing the song from the silence at the end and you don't have the time to force it to restart from the beginning due to Blue Tooth controls input lag).

To emphasize how bad this is, I messed up my playlist while trying to add one song to the queue which instead wiped and replaced the queue. As I was afterwards, I couldn't do anything until I stopped again.

Then later on the app errored out (NPEx error) and wiped the entire play queue.

So I switched to Pi Music Player for the rest of the drive while filling fuel. This ate my data as it plays video instead of audio only.

#### Additional context
Next time, please kindly make and advertise a beta branch for these things and get usability feedback before pushing such major changes all at once. It's fine to try out new things but the release versions are supposed to be for mass consumption and stable. 

#### How will you/everyone benefit from this feature?
It will allow us to stay on that version until the current usability issues are resolved to a reasonable degree. 

Either this or people are going to switch to alternatives and if they're satisfactory, they won't migrate back once the changes are implemented. 

I personally like NewPipe a lot and would like to remain with it.

**Comment by nonremittal** [comment]
This please. The new version crashes my phone and it's generally a UX nightmare. I have no idea what the back key does any more!

NewPipe used to feel so lean and simple, then it became a confusing mess out of nowhere. Normally I can adjust to new interface changes fairly quickly, but this time around I think I'll wait for a fork or new alternative.

Personally I've been using VLC. If you paste a YouTube URL in as a New Stream, it plays the video and you can set it to Play as Audio. However like you said about Pi, it plays the video instead of audio only.

**Comment by heretoenhance** [comment]
I agree with @MapleWheels that a beta branch would be beneficial for these kind of major updates in order to thoroughly test them before general release.

I don't think that the app has become unusable UI/UX wise but some polishing and more testing could be good.

I really believe that having more features and functionalities added is always positive, and even rebuilding or rethinking stuff like the Unified Player is a sign of good developmente and will become, once it will start to work as expected, what makes this app the best of its kind.

NewPipe is awesome and I would never think about switching (as long as it remains open source) and I believe many people would agree with me.

So thank you guys for your amazing and incredibly fast work, I'm sure that, as always, you will find a way to mix stability and feature progression.

**Comment by MapleWheels** [comment]
> I agree with @MapleWheels that a beta branch would be beneficial for these kind of major updates in order to thoroughly test them before general release.
> 
> I don't think that the app has become unusable UI/UX wise but some polishing and more testing could be good.
> 
> I really believe that having more features and functionalities added is always positive, and even rebuilding or rethinking stuff like the Unified Player is a sign of good development and will become, once it will start to work as expected, what makes this app the best of its kind, as it has been already.
> 
> NewPipe is awesome and I would never think about switching (as long as it remains open source) and I believe many people would agree with me.
> 
> So thank you guys for your amazing and incredibly fast work, I'm sure that, as always, you will find a way to mix stability and feature progression.

I don't have a problem with 0.20.x as a whole, man6 parts of redesign feel nicer and the app seems more responsive. The problem is that,  as per my original post, there are severe issues  and regressions as part of the design choice. Again, none of this was tested large-in-part publicly before committing.

If this had been a public beta/alpha and these UX issues had been addressed with a few/some issues remaining, but still workable, then we'd live with it and just wait until i lt was fixed. 

The problem is as of now, we can't use this app as both a video and audio player, which was one of it's major selling points over the official YT app (since bg play is a paid option).

Again, if I could 'cache' the current play queue before playing a video and quick load it back then I could work with the new unified UX until the other issues are fixed. 

To be clear, I appreciate the unpaid work the devs put into this project, I am just expressing my grievances with this decision. There's a reason why companies maintain legacy support for their older products when newer ones are released.

**Comment by XiangRongLin** [comment]
I would be willing to provide a limited time support for NewPipe v0.19.8 while the issues described above get addressed. It would only contain updating the extractor version and fixing things if the public API of the extractor changes. Unless there are major changes in the extractor this would be ok for me since i plan to use it myself.

For now i have a debug build with NewPipe v0.19.8 and Extractor v0.20.2
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5468644/app-debug.zip)
The changes needed for this one are very minor: https://github.com/XiangRongLin/NewPipe/commit/bc71819d2053af1a4ccbdbfccce68c26b73bf988

**Comment by krtfwd** [comment]
> I would be willing to provide a limited time support for NewPipe v0.19.8 while the issues described above get addressed. It would only contain updating the extractor version and fixing things if the public API of the extractor changes. Unless there are major changes in the extractor this would be ok for me since i plan to use it myself.
> 
> For now i have a debug build with NewPipe v0.19.8 and Extractor v0.20.2
> [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5468644/app-debug.zip)
> The changes needed for this one are very minor: [XiangRongLin@bc71819](https://github.com/XiangRongLin/NewPipe/commit/bc71819d2053af1a4ccbdbfccce68c26b73bf988)


it says corrupt :(

**Comment by XiangRongLin** [comment]
@krtfwd I updated the file in my comment above. please try again

**Comment by MapleWheels** [comment]
> @krtfwd I updated the file in my comment above. please try again

I thank you for your service and can confirm that it is working.

**Comment by krtfwd** [comment]
> 
> 
> @krtfwd I updated the file in my comment above. please try again

Thank you very much it works without any issues. The dev team should def put this on the website or next to the official releases for everyone having trouble with the 0.2.xxx versions

**Comment by MapleWheels** [comment]
Or they can just pin this issue ticket in the tracker.

**Comment by ShareASmile** [comment]
Thank you @XiangRongLin very much. I appreciate your efforts.❤ and of all the developers who contributed in the past to make this app great.

**Comment by Fatcakes** [comment]
Just downloaded after seeing this in the subreddit and I want to kiss you. I can't get the app to install though and I removed all other
instances of newpipe. If sponsorblock got merged to this also would be great.

**Comment by DI555** [comment]
any plans to make a repo:
https://github.com/TeamNewPipe/NewPipe-preunified
???

**Comment by XiangRongLin** [comment]
> @XiangRongLin , any plans to make a repo:
> https://github.com/TeamNewPipe/NewPipe-preunified
> ???
> 

nope. it's only supposed to be a temporary solution. not a fork of the project.

And im not part of the TeamNewPipe organization, so it's not up to me to decide

**Comment by yiiii777** [comment]
[newduck.txt](https://github.com/TeamNewPipe/NewPipe/files/5489399/newduck.txt)

**Comment by yiiii777** [comment]
[newduck.zip](https://github.com/TeamNewPipe/NewPipe/files/5489406/newduck.zip) - binary build

See more for details: https://github.com/TeamNewPipe/NewPipe/issues/4791

**Comment by DI555** [comment]
i would wish to see here another repo with this preunified version...
i like preunified version, and this ui became comfortable for me...
could anyone do this?

**Comment by eladkarako** [comment]
<a href="https://github.com/eladkarako/NewPipe-ESR/releases/download/v198.0.22.2/newpipe_v198.0.22.2_mod_nolanguages_hardwareacceleration_nodebug_oldui_newextractor_signed_aligned.apk.zip">newpipe_v198.0.22.2_mod_nolanguages_hardwareacceleration_nodebug_oldui_newextractor_signed_aligned.apk.zip</a>

it is too based on suggestion from https://github.com/TeamNewPipe/NewPipe/issues/4791
for creating a hybrid based on v0.19.8-UI and the extractor from v0.22.2.

and suggestions from https://github.com/TeamNewPipe/NewPipe/issues/4575  
turning ON global GPU hardware acceleration and extra-large heap.  

It also a lite version, with all languages removed but the default EN.

version format has changed to reflect the UI version and the extractor version,  
the name is kept NewPipe but it has different signature (so you must uninstall other versions).  

it supports importing settings from newer versions.

for faster browsing, I suggest turning off comments and related videos.

**Comment by Isayso** [comment]
I have made a version for my phone in my storage called NewPipe19.

**Comment by opusforlife2** [comment]
@XiangRongLin Could you open a new issue and post the latest APK in the top comment? Then I can pin it.

**Comment by opusforlife2** [comment]
'Fixed' by #4918.

**Comment by eladkarako** [comment]
the script in https://github.com/TeamNewPipe/NewPipe/issues/4686#issuecomment-721851901 works fine on 0.20.2, but breaks in 0.20.3 when clicking the subscriptions' 'what's new' section (even before an update).

**Comment by yiiii777** [comment]
[newduck20-6.zip](https://github.com/TeamNewPipe/NewPipe/files/5691152/newduck20-6.zip)
[newduck-20-6.txt](https://github.com/TeamNewPipe/NewPipe/files/5691160/newduck-20-6.txt)

@eladkarako, I updated script and binary build.
Create backup before update, for data safety

**Comment by Littlemac123** [comment]
> [newduck20-6.zip](https://github.com/TeamNewPipe/NewPipe/files/5691152/newduck20-6.zip)
> [newduck-20-6.txt](https://github.com/TeamNewPipe/NewPipe/files/5691160/newduck-20-6.txt)
> 
> @eladkarako, I updated script and binary build.
> Create backup before update, for data safety

can you please update this with the v0.21.1 newpipe extractor. newpipe 0.19.8 menus are way better then what has happen now

**Comment by Littlemac123** [comment]
i cant stand that the zoom setting is just gone now

**Comment by opusforlife2** [comment]
@Littlemac123 #4918.
