### ISSUE TITLE
Allow playlists in external audio player

### ISSUE THREAD

**Issue by nonremittal** [TeamNewPipe/NewPipe#4689]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Playing a playlist in the background with with the "Use external audio player" setting enabled should play each of the audio files in an external player.

#### Is your feature request related to a problem? Please describe it
The background player is currently broken for some users. I can play a single audio in the background using VLC, but opening a YouTube playlist or one of my own playlists and hitting 'Background' causes it to play in NewPipe's own background player instead.

#### Additional context
I also have settings customized in VLC so it's jarring going from one audio player to another.

#### How will you/everyone benefit from this feature?
This would create a unified external audio playing experience for people who want it.

**Comment by Stypox** [comment]
This is not doable, as there is no standard way of sending around playlists to other players.

**Comment by nonremittal** [comment]
Is there no way you could use the current queueing/playlist system, but send each new video/audio to the external player instead of using the NewPipe player? Do external players not return a value when they're finished? (Not too familiar with how Android works.)
