### ISSUE TITLE
Audio Tag Support (M4A, ID3)

### ISSUE THREAD

**Issue by anonwins** [TeamNewPipe/NewPipe#469]
So apparently m4a supports ID3 tagging BUT there's something wrong with the header of the m4a files.
Tagging software show 'incorrect header info' on newpipe's downloaded audio files.

Please check on this, I believe it's important for those who make music collections from downloaded tracks

**Comment by anonwins** [comment]
![screenshot_2017-03-02-00-44-56](https://cloud.githubusercontent.com/assets/26126049/23484932/d419c650-fee1-11e6-8b06-3ce3f13afa07.jpg)
AutomaTag App

**Comment by theScrabi** [comment]
That may be, but I have no influence over the datafiles itself. NewPipe can only handle Urls.
So in other words we might ned a converter to acheve that, but that would be a lot of work.

**Comment by mauriciocolli** [comment]
Basically it's downloading a `mp4 dash-audio (fragmented)` 
The `youtube-dl` corrects the header with `ffmpeg` https://github.com/rg3/youtube-dl/issues/3681#issuecomment-71235224

More info [here](http://stackoverflow.com/a/35180327)

**Comment by ksaerdna** [comment]
Tagging fragmented mp4 files is not supported by every tagger or tagging library, but at least by kid3. This program is available on Linux, macOS and Android (I did not care about others).

I would appreciate any conversion tool or script or whatever, but so far I could not find any.

**Comment by opusforlife2** [comment]
@anonwins @ksaerdna Do you still face this problem with the latest release?

**Comment by viviskas** [comment]
- [ ]

**Comment by viviskas** [comment]
``

**Comment by ccpp** [comment]
> [@anonwins](https://github.com/anonwins) [@ksaerdna](https://github.com/ksaerdna) Do you still face this problem with the latest release?

I can reproduce this with the Classucal Music Tagger app, not being able to tag exactly one download (f-droid current version of date 2024-11-08 was used to download)

I suggest to reopen this issue

![Image](https://github.com/user-attachments/assets/5fa43d19-471c-4319-b759-697054de4b2e)

**Comment by Andreas-Kromke** [comment]
There is no need to reopen this issue. It's not the fault of NewPipe, but the fault of Classical Music Tagger, which uses the Jaudiotagger library, and this one does not support mp4-dash.
