### ISSUE TITLE
Include Channel Groups as part of subscription exports

### ISSUE THREAD

**Issue by TippyLion28** [TeamNewPipe/NewPipe#4690]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Please include subscription groups as part of the exported subscriptions file. Groups can get pretty big and it can be a PITA to set them up again on a different device. 

#### How will you/everyone benefit from this feature?

This will lessen the time spent organising subscriptions and subsequently increase time spent watching YouTube :D

**Comment by opusforlife2** [comment]
> I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

#3505. :|

**Comment by TippyLion28** [comment]
My apologies. I did find that issue when I was searching however I interpreted it as different to my issue. I have done a stupid c:
