### ISSUE TITLE
"Could not parse website" 0.20.1 guru meditation

### ISSUE THREAD

**Issue by xxxxme** [TeamNewPipe/NewPipe#4697]
With the latest version on F-droid, 0.20.1, I get the following crash report when attempting to view any video info, after the comments have loaded:
https://dpaste.com/CTWC8DKCN.txt

**Comment by jonilaw** [comment]
use latest version 0.20.2 found in github. older version does not work anymore.

**Comment by opusforlife2** [comment]
Preferably, use our custom F-Droid repo link from the website.
