### ISSUE TITLE
Not playing any youtube video

### ISSUE THREAD

**Issue by globalsummitf** [TeamNewPipe/NewPipe#4699]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by canismajori** [comment]
The same problem about 4 days.

**Comment by xibr** [comment]
make sure you're using latest version. 0.20.2
