### ISSUE TITLE
[FEATURE] Subscriptions

### ISSUE THREAD

**Issue by ksyko** [TeamNewPipe/NewPipe#470]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by ksyko** [comment]
Now that we have channels in the list, we could make a subscription list. 
So, what class creates the video list.

**Comment by theScrabi** [comment]
Opening and closing all the time wont help.

**Comment by theScrabi** [comment]
But yes that's the plan.
