### ISSUE TITLE
Video is not opening

### ISSUE THREAD

**Issue by nabeelmn** [TeamNewPipe/NewPipe#4704]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by erenayar5** [comment]
I don't want to be a time traveler but I think this issue is going to be closed soon.

**Comment by opusforlife2** [comment]
Edit your issue and fill the template properly.
