### ISSUE TITLE
APP closes without error message

### ISSUE THREAD

**Issue by daniel-lenz** [TeamNewPipe/NewPipe#4707]
# Checklist

- [x] I am using the latest version - 0.20.2
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a chosen Video 
2. After approx. 01:30 the APP closes immediately without any error message.

### Actual behaviour

1. Open APP again and start same Video, it plays Form 01:30 until 03:15, then APP closes again.
2. Open APP again and start same video, it starts to play again from 01:30 until 03:15 and APP closes again.

### Expected behavior

Video should play until it finished and APP should be open to use.

### Device info

 - Android version/Custom ROM version: Android 5
 - Device model: FireTV Box Model 2017

**Comment by Stypox** [comment]
Could you test if #4562 fixes this by chance?
