### ISSUE TITLE
No share button under video come on

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#4709]
Well i really need the share button under the videos, what i do now is search for the video title long press and press share. This is crazy.... where did my share button under the video go...

YouTube has it perfectly

Please add on New Pipe dear fellas

![Screenshot_20201029-194735.jpg](https://user-images.githubusercontent.com/20374208/97612348-fdd78380-1a1f-11eb-9c33-5918770ffa80.jpg)

**Comment by vkay94** [comment]
The share button has moved into the player. Click on the arrow in the player's toolbar and choose the share button. Please use the issue search function next time to avoid repeating the same question/complaint. Thanks

**Comment by goxr3plus** [comment]
Hol up :)

What if i don't want to play the video and i just want to share it.

By the way i don't completely understand the above description of where i can find.

Can i have a screenshot, thank you.


Finally i think share should be where youtube has it its the best design. I am ui/ux designer by the way :)

**Comment by vkay94** [comment]
>What if i don't want to play the video and i just want to share it.

>Finally i think share should be where youtube has it its the best design


Yeah, there were many complaints about this change, I'd recommend to keep an eye on #4039 for ongoing progress regarding this.

>By the way i don't completely understand the above description of where i can find.

When the video starts to buffer/play and you click on the player view, the controls appear. To the top right corner there is an arrow-down button which shows the share option after clicking it.

**Comment by Stypox** [comment]
Search for dup
