### ISSUE TITLE
Move kodi button to better position

### ISSUE THREAD

**Issue by mueller-ma** [TeamNewPipe/NewPipe#471]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hi,

I really like the "play on kodi" button, however it is in the dropdown menu and not accessable as quick as it could be. I have appended an image with the kodi button on a better position. In this case it might be better to diable the feature by default, because people could get distraced by a second play button without purpose for them.

![newpipe-kodi](https://cloud.githubusercontent.com/assets/22525368/23559094/34911920-0036-11e7-9340-a46859e2137e.jpg)

**Comment by mueller-ma** [comment]
Can you have a look at https://github.com/mueller-ma/NewPipe/commit/f40c8f525f65d3f4971ff20211b7bbb97051ae23

**Comment by mauriciocolli** [comment]
I was thinking in doing something like that, I guess the share is not as important as an option of the user, so it can be in the dropdown if it don't have enough space.

You can open a pull request, but keep in mind that when you enable/disable the option in the settings, the option are not appearing unless the application is restarted (or exiting the video fragment, and enter again), so it requires another change as I forgot to include this button/option as an update of the UI.

And I'll open a PR fixing this soon.

**Comment by theScrabi** [comment]
@mauriciocolli as long as you keep leting the user decide weather he wants to see the share or the kodi button in the action bar I'm fine with that :)

**Comment by mauriciocolli** [comment]
@theScrabi I guess, who enable the Kodi **will** want easier access (use often/constantly) to that feature than the share and it's not like the share will be gone, so I think an option just for that would be overkill.

What do you think?

**Comment by mueller-ma** [comment]
Can we use this: Share, Kodi, Download and change Download to "ifRoom" and Share to "always"

**Comment by theScrabi** [comment]
All right, I'm good with that :)

**Comment by mueller-ma** [comment]
I make a PR

**Comment by mauriciocolli** [comment]
I think that `Download` should always be visible in the actionbar, as it is one of our "primary" features.

And just changing the order of the `Play on Kodi` and `Share` is enough...

**Comment by theScrabi** [comment]
@mauriciocolli yea you are right. Of course the download must stay visible, just that slot aside of it can vary.

**Comment by mueller-ma** [comment]
@mauriciocolli @theScrabi I think when someone manually enables the kodi button than it is more important than the download

**Comment by mauriciocolli** [comment]
@mueller-ma that's what I said in the previous post, except that it was to "replace" the share.

But the download button HAVE to be the first button and always be visible, the share that is interchangeable. And I think in all phone made in the last years (the screen size average) will be showing 2 items, so there's no problem leaving the Download button as first.
