### ISSUE TITLE
Player: app does not show bottom bar player after exiting NewPipe with active background player

### ISSUE THREAD

**Issue by leewp14** [TeamNewPipe/NewPipe#4712]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a song in background
2. Exit NewPipe with back button
3. Open back NewPipe

### Actual behaviour

When reopen NewPipe  while the background player is active, NewPipe does not show the bottom player bar to indicate active playing. 

### Expected behavior

When reopen NewPipe with a background player active, the NewPipe app should show the bottom player bar like how it is before the app was closed. 

### Screenshots/Screen recordings

![Screenshot_20201030-030829](https://user-images.githubusercontent.com/17796518/97621751-4e6dd180-1a5e-11eb-8dfd-dc41570009ae.jpg)

### Logs

_none_

### Device info

 - Android version/Custom ROM version: 9/Havoc 2.8
 - Device model: SM-N910G

**Comment by Stypox** [comment]
Does the last apk provided in #4562 solve the issue?
<sub>If it is not yet there, it means it is still being uploaded<sub/>

**Comment by leewp14** [comment]
> Does the last apk provided in #4562 solve the issue?
> If it is not yet there, it means it is still being uploaded

Guess I'm late to the party, sorry! But yes, the issue is resolved. It's working as intended now.
