### ISSUE TITLE
Continuous Search from everywhere, especially while in a channel

### ISSUE THREAD

**Issue by drogga** [TeamNewPipe/NewPipe#4719]
The "YouTube" app and others like "SkyTube" show the "Search" icon and allow searching from any\every screen, even while in a channel, so you can do a continuous searches from absolutely everywhere, but NewPipe (Legacy) doesn't (only from the main window screen)...

For example - you may want to search for another channel or a video while you are on a channel's screen, without going back from\closing that one, or you may want to check the uploads of a few\couple of a channels, let's say 5 and you want to watch the content of each one after the other, without having to do a separate new search for every single one of them.
My use case is like this (on the device where this actually works), but I still have to use SkyTube because it can actually do this and I have no other choice - I don't use any accounts to log-in and I have to daily (manually) check some channels (like LTT, MKBHD, Unbox Therapy and a few others) for new uploads and start watching from the last to the first one and just going back once to the previous one, once I finish with it, without having to type \ do a new search again.

———

_Some other things that need attention:
Comment's Usernames are misplaced {...when they even bother to load...} - they are on top of the icons (covering them), instead next of them and some texts in suggestions are overlapping - top right [layout issues];

A Notification shows up for every single playback, which is completely unnecessary... it should only show while\when it plays in a background or a Pop-Up window, but not when the app is on focus.;

720p MPEG-4 doesn't show the video of most music videos, only the audio plays (with a black screen) and in order to see it, you need to bump the rez to 1080p+, but that's an issue when your device can't handle it, especially when most of them are in WebM for higher than 720p, which makes this rez basically useless for those.;

The app never cleans it's video cache on exit or when the video is closed, there's always 60 MB+ (at least) of unnecessary app cache, which is not from thumbnails or\and icons...;

It will be awesome if some filtering can be added to the searches, like by uploaded date (newest on top) at least if not others, cuz search is basic AF currently..._

**Comment by Stypox** [comment]
#2414

**Comment by drogga** [comment]
@TobiGr Hi, you shouldn't moved this, as it's partially related to the "Legacy" only, so if I wanted it here, I would've created it here in the first place.
@Stypox Hi, you didn't understand correctly the things I meant here, it's not related to any of those in "2414", so it's definitely not a dupe, it's also partially related/meant only to/for the "Legacy" git repo, so you shouldn't closed it, tho it wasn't meant for/to be in this "upstream" repo at all, and I definitely didn't wanted it here...
