### ISSUE TITLE
NewPipe Extractor now Seperatly available

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#472]
Hello,

as I said on on my CCC talk, I wanted to pull out the extractor from NewPipe itself. Now you may have seen it, I did that now.

The extractor is available [here](https://github.com/TeamNewPipe/NewPipeExtractor).

A small example program showing how the extractor can be used can be found [here](https://github.com/TeamNewPipe/np-cli).

rgds Schabi

**Comment by SUguy** [comment]
Is there a video of the talk online. I cant find it.

**Comment by theScrabi** [comment]
No we did not have a cam there :/
