### ISSUE TITLE
[Request] Seamless Update

### ISSUE THREAD

**Issue by zero77** [TeamNewPipe/NewPipe#4722]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Can you please implement [Phonegap Build](github.com/phonegap-build) to handle updates.

I have seen it used by other apps and it has made the update process completely streamline.
For example, upon opening the app Phonegap Build automatically checks for updates, and if found then asks whether to ignore or update and restart, after this there is no additional action required by the user.
Thanks

**Comment by Stypox** [comment]
This has already been discussed in #3141, and the answer is unfortunately that this can't be done for privacy reasons
