### ISSUE TITLE
Please restore usability on mobile devices (back button, maximized/fullscreen mode, no overlay playlist)

### ISSUE THREAD

**Issue by CEHitchens** [TeamNewPipe/NewPipe#4724]
IF YOU DON'T FILL IN THE TEMPLATE PROPERLY, YOUR ISSUE IS LIABLE TO BE CLOSED. If you feel tired/lazy right now, open your issue some other time. We'll wait. 
Maybe it will be closed or even deleted, if so, so be it. I simply couldn't find a better communication channel than this to express my view.

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
>> "Check whether your issue/feature is already fixed/implemented." >> Is not the case.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Please restore usability on mobile devices or at least allow for a user experience to what it was before version 20. Why break something that worked well for many users for years?
Since version 20 using NewPipe feels like having to tap dance (pun intended). 
- 2 additional taps to get to maximized/fullscreen view and when you rotate the device, unlike pre version 20, it loses the maximized/fullscreen view. Landscape video and device held upright only using a fraction of screen estate? Well, that's to be expected unless set otherwise in OS or app's defaults).
- Back button can not be used in such a way as before. Another tap dance to first minimize the current video, close this new backstack (?!) at the bottom which also can not be disabled, only to stop the currently playing video.
- Please re-add ablity to go to pop-out video from maximized/fullscreen view.

Don't get me wrong, I love(d) NewPipe. It had been THE app to convince people to e.g. take a look at the F-Droid store, NewPipe having been one, if not THE, true gem in that store.

I will admit that I have spotted similar if not identical posts here, some were closed, some are still open. Since there is no forum (yes, I believe that I understand why - more work) to debate such topics or have a vote to get user feedback, I went to the freenode IRC channel, which had little activity (when I last visited it). 
Obviously I can only speak for myself and I fail to see the _technical_ necessity for some of these changes. and to users using this app for years now it feels like a "It's been decided, deal with it. Get used to the tap dance." kind of thing.

Looking forward to future updates restoring some sanity.

#### Is your feature request related to a problem? Please describe it
Other than the introduced changes from v20.x, no.

#### Additional context
I have stolen enough of your time already.

#### How will you/everyone benefit from this feature?
- Long time users will feel at home. 
- Users will have to do less tap dancing > Efficiency = postive user experience.
- Users will be given the opportunity to choose. Why "fix" something which wasn't broken?

**Comment by opusforlife2** [comment]
> Maybe it will be closed or even deleted, if so, so be it.

Oh well. Since you saw this coming...
