### ISSUE TITLE
Back button doesn't exit the app.

### ISSUE THREAD

**Issue by killoid** [TeamNewPipe/NewPipe#473]
pressing back button doesn't exit the app. i am using the latest version from f-droid on my galaxy note 3 sm-n9005 running LOS 14.1 without any gapps. let me know if you need more info. thanks.

**Comment by theScrabi** [comment]
No i disabled it, but i see i need to bring it up agauin.

**Comment by killoid** [comment]
oh thanks for letting me know. i hope you will enable it in next version.

**Comment by theScrabi** [comment]
should be fixed with v0.8.12
