### ISSUE TITLE
Please add the share button back in video details

### ISSUE THREAD

**Issue by bunyevacz** [TeamNewPipe/NewPipe#4732]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Additional context

In older newpipe version, there was a 'share' button in youtube video details (top right corner), and I could open it in a webbrowser.

Right now it is impossible to retrieve the video's url.

#### How will you/everyone benefit from this feature?

The main reason for the share button is to be able to read youtube nested comments.
Right now newpipe only shows top level youtube comments no subcomments (replies).

**Comment by LeLorax** [comment]
The location of the buttons has changed.
![20201030_232934](https://user-images.githubusercontent.com/48091185/97762280-4e2a1080-1b08-11eb-8b2f-bbfc0798ab7f.jpg)

**Comment by opusforlife2** [comment]
> I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

#4039 O_O

**Comment by bunyevacz** [comment]
Thank you for the pointers and the original bugreport, my search-fu let me down.

This change has a serious drawback, I will comment it on the original bugreport.
