### ISSUE TITLE
[0.20.2] Age restriction shows some videos "removed"

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#4737]
### Checklist
- [x] I am using the latest version - 0.20.2
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.)
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open [this](https://youtu.be/kLoJaVYI2Zc) video in NewPipe

### Actual behavior
The video is shown as removed. You can only play it on youtube.com or in the official app when logged in.
Possible reason: [New age restriction](https://youtu.be/2gTNFJhSHok)

### Expected behavior
The video would be playable.

### Device info

 - Android version/Custom ROM version: 10/API 29
 - Device model: Samsung Galaxy A70

**Comment by opusforlife2** [comment]
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

#4681. O_O

**Comment by kubo6472** [comment]
Damn I'm blind
