### ISSUE TITLE
Queues mixing disadvantage

### ISSUE THREAD

**Issue by Flashwalker** [TeamNewPipe/NewPipe#4748]
After upgrading to the current version, the Floating Window Player and Background Player queues are now mixed. When I have items in the background player queue, if I add a new one to play in a floating window, the entire background player queue becomes a floating player queue, and there is no way back.

If you close the floating window, the background player queue will be lost.

This is a big disadvantage compared to previous versions, where the queues were separated.

Is it posible to get separated queues now?

**Comment by Stypox** [comment]
This was part of a decision done in #2907, we knew some people would not like it but we decided it was the best choice for most users, so this won't be reverted

**Comment by opusforlife2** [comment]
@Flashwalker Follow #4460.

**Comment by Flashwalker** [comment]
Well... when you have two options and choose the first to push into the background and getting the second one... it looks like there is a risk of misunderstanding in the operation of the application when you wait for one and get another
