### ISSUE TITLE
Releasing apk on github.

### ISSUE THREAD

**Issue by killoid** [TeamNewPipe/NewPipe#475]
f-droid is very slow to update the app when an update is available on source. so it would be nice if you build the apk file & release it on github for easy updating.

**Comment by theScrabi** [comment]
Fdroid failes all the time. The latest build did not build again, so I again have to figure out why.

**Comment by killoid** [comment]
will be waiting for it. take your time.

**Comment by rancidfrog** [comment]
This is duplicate of https://github.com/TeamNewPipe/NewPipe/issues/250
APK to release section for direct download already requested before
I hope it will be added

**Comment by killoid** [comment]
oh i see! then i should close this issue. less issues, less headache for developer!

**Comment by rancidfrog** [comment]
But you should probably add your comments in that issue with the problem you are facing.
