### ISSUE TITLE
ReCAPTCHA challenge but there is no Captcha

### ISSUE THREAD

**Issue by Peakgolden** [TeamNewPipe/NewPipe#4750]
When opening a video , it redirects to the ReCAPTCHA Challenge but no captcha is shown there . It's just a blank white page .

### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1 . Open any video .

### Screenshots/Screen recordings

![Screenshot_20201101-155811_NewPipe](https://user-images.githubusercontent.com/57090191/97800018-c6551b00-1c5b-11eb-9085-65e3a75a88b8.jpg)

### Device info

 - Android version/Custom ROM version: 9
 - Device model: SM-G950F

**Comment by Stypox** [comment]
You didn't search for duplicates
