### ISSUE TITLE
Download the whole playlist with one tap .

### ISSUE THREAD

**Issue by Peakgolden** [TeamNewPipe/NewPipe#4751]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be better if one could download an entire playlist with one tap instead of having to individually download every one of them .

#### Is your feature request related to a problem? Please describe it

Not related to any problem .

#### How will you/everyone benefit from this feature?

It will be way less time consuming and overall be a useful feature for users .

**Comment by Stypox** [comment]
You didn't check for duplicates
