### ISSUE TITLE
Back button not closing NewPipe

### ISSUE THREAD

**Issue by aikobel** [TeamNewPipe/NewPipe#476]
Just to let you know that the back button stopped closing NewPipe on Android 4.1.2 (Samsung S3 Mini) since v0.8.10.

**Comment by killoid** [comment]
it is fixed with v0.8.12. close this issue, already opened similar one.

**Comment by aikobel** [comment]
It's all sorted, thanks mate!

**Comment by killoid** [comment]
please close this issue.
