### ISSUE TITLE
Need same UI/UX as official Youtube app

### ISSUE THREAD

**Issue by prasumoholkar** [TeamNewPipe/NewPipe#4763]
We love New pipe app,and current UI/UX is good but it would be nice if u add same UI/UX as official youtube app or youtube vanced app.

**Comment by opusforlife2** [comment]
Edit your issue and fill the template.

**Comment by TobiGr** [comment]
Not necessary.  We are not a copy of YouTube. NeePipe supports various services and thus YouTube's UI/UX is not suitable.
