### ISSUE TITLE
[BUG] Rotating causes empty channel view

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#477]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
Rotating the device while a channel is displayed causes an empty channel view. The loading symbol is spinning but nothing happens. There is no difference whether you start rotating in landscape or portrait format.
This issue occurs on Android 5.0.1 and 6.0., NewPipe versions 0.8.10 and 0.8.11 are affected.
![rotating causes empty channel view](https://cloud.githubusercontent.com/assets/17365767/23802504/e26b9dae-05b3-11e7-938f-9ca42837af58.png)

**Comment by theScrabi** [comment]
Right noticed that.

**Comment by theScrabi** [comment]
[Fixed](https://github.com/TeamNewPipe/NewPipe/commit/e3baf69533a3df95d72a8d7f3d02292638a1a1aa)
