### ISSUE TITLE
Main Player is closed if app is booted from RAM

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4777]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play any video in Main Player.
2. Pause it. (The notification disappears.)
3. Switch to another app. (If Minimize is set to None, the Main Player will be automatically paused.)
4. Do RAM-heavy stuff until Newpipe gets removed from RAM.
5. Switch back to Newpipe.

### Actual behaviour

You are taken back to video details for the video that was open earlier. The thumbnail is shown.

### Expected behavior

The app should resume at the point where you left, with the Main Player open at the timestamp it was paused at, ready to play further. This is what happened in 0.19.8.

**Comment by eladkarako** [comment]
can you check if it happens with 
https://github.com/TeamNewPipe/NewPipe/issues/4575 
(one of the apks) 
you need to clean the stored cache and uninstall previous versions since it uses a different signature.

the apk has some instructions to assign a larger heap in the memory than usual. might solve things and speed up overall experience.

**Comment by mhmdanas** [comment]
@eladkarako @opusforlife2 wanted me to tell you that you appear to have blocked them unintentionally, so neither of you will get any notifications involving the other.

**Comment by opusforlife2** [comment]
Whoops. Duplicate of #6408. Sorry.

**Comment by mhmdanas** [comment]
When you open a duplicate of your own issue:
