### ISSUE TITLE
UX: consistent behavior for long press in play queue

### ISSUE THREAD

**Issue by Sohalt** [TeamNewPipe/NewPipe#4778]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
When I long press on a list item in the play queue that you get to by clicking on the little list icon in the top right of a playing video, the item gets deleted from the queue. When I long press on a list item in the play queue that you get to by clicking on the notification, while playing a video in pop-up mode, I get a context menu with options to delete, view details, add to playlist, or share. I would like to have both behaviors be consistent (with my personal preference being, that both show the context menu).

#### Is your feature request related to a problem? Please describe it

I sometimes accidentally delete a video from the queue when long pressing in the view that you get to by clicking the list icon from a playing video, because I confuse it with the list view that you get to by clicking on the notification while a video is playing in pop-up mode.

#### How will you/everyone benefit from this feature?

Less confusion. No accidentally deleted videos from play queue.

**Comment by opusforlife2** [comment]
That sounds like a bug. Long pressing shouldn't delete anything.

**Comment by MD77MD** [comment]
I agree with you, consistent is key in good design/ behavior.

I Like what @Sohalt suggested, we should get the context menu in both enqueue lists.
![Screenshot_20201102-221515](https://user-images.githubusercontent.com/63132171/97909364-28477a80-1d59-11eb-9976-d5d7601ef071.png)


 beside we can already delete video by swiping them away... so why do we still need long press to delete.

**Comment by opusforlife2** [comment]
@Stypox Good first issue?

**Comment by XiangRongLin** [comment]
@mhmdanas Are you still working on this? since you assigned yourself

**Comment by mhmdanas** [comment]
Ah, sorry, I completely forgot about this. I'm not working on this right now, so if anybody wants to give it a try, feel free to make a comment and I'll assign you to this issue.
