### ISSUE TITLE
Auto-queue button color issue for color blind people

### ISSUE THREAD

**Issue by Istvanbraun** [TeamNewPipe/NewPipe#4785]
I have poor eyesight and quite a bit of color blindness. Newpipe is fine for me, except the auto-queue button color when it is on is hard to differentiate from when it is off. A deeper blue would be best. That's it, this is not the biggest problem in the world but it's annoying for me. 
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x ] I checked, but didn't find any What about if you synchronised the clocks with a mechanical connection, such as a rod of metal that rotated and synchronised he clocks? Would not the clocks be exactly synchronised at a distance? (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
 the color changes from Blue to White but it's so hard for me to tell the difference I had to use a magnifying glass to look at the colors. 

### Expected behavior
 I would like the blue to be much deeper. The blue on my Google keyboard on my Android device for the carriage return would be perfect. There is no error so I'm not going to post a screenshot of the error page. I think everyone understands what I'm talking about but I can post a screenshot if it really is necessary. 

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Samsung galaxy tab S6

**Comment by opusforlife2** [comment]
Please try the APK in #4162. It will install separately from the official app.

**Comment by SameenAhnaf** [comment]
@Istvanbraun Does this bug still persist for you? Service colour is now applied to auto-queue button as shown in #6456.

**Comment by Istvanbraun** [comment]
The but has been solved. I am now seeing a definite color difference.

**Comment by opusforlife2** [comment]
Thanks! Closing as fixed by #6456, then.
