### ISSUE TITLE
Did background looping got removed with the new unified player?

### ISSUE THREAD

**Issue by Plugdemholes-Imeanpatchdembugs** [TeamNewPipe/NewPipe#4788]
I'm not sure if that feature existed and got removed with the new unified player, since I'm rarely using Newpipe to loop music.
But wasn't there an option that allowed to loop the audio a wanted number of times before (single track as far as I remember)?
Currently it seems to be gone or am I mistaken?

**Comment by opusforlife2** [comment]
You can change the notification buttons using the Notification menu in settings. Repeat is one of them.
