### ISSUE TITLE
Extended support for versions 0.19 (with old player)

### ISSUE THREAD

**Issue by yiiii777** [TeamNewPipe/NewPipe#4791]
This is not really a feature request. This is the result of my despair. The result of my pain. Pain that started in version 0.20. it is called "reluctance of authors to bring back old user experience". Or maybe "unwillingness to maintain old code".

Okay!

My gift to all those who can NOT use the new versions of the application (since they want to throw their phone against the wall because of the new interface).

```
#org.schabi.newpipe_953.apk - last usable apk
#NewPipe_v0.20.2.apk - fresh version with working extractors

java -jar apktool_2.4.1.jar d org.schabi.newpipe_953.apk -o newduck
java -jar apktool_2.4.1.jar d NewPipe_v0.20.2.apk -o newshit

mkdir tmp
mv newduck/smali/org/schabi/newpipe/extractor/stream/SubtitlesStream.smali tmp
rm -rv newduck/smali/org/schabi/newpipe/extractor/
rm -rv newduck/smali/org/jsoup/
cp -r newshit/smali/org/jsoup/ newduck/smali/org/
cp -r newshit/smali/org/schabi/newpipe/extractor newduck/smali/org/schabi/newpipe/
cp tmp/SubtitlesStream.smali newduck/smali/org/schabi/newpipe/extractor/stream/

find newduck/ -type d -name "*/newpipe" | while read aa; do mv "$aa" `sed "s,newpipe,newduck,g" <<< "$aa"`;done
find newduck/ -name "*newpipe*"| while read aa; do mv "$aa" `sed "s,newpipe,newduck,g" <<< "$aa"`;done
find newduck/ | while read aa; do sed -i "s,newpipe,newduck,g" "$aa";done

# photoshop DUCK on icon
[ ! -e "little-rubber-duck.png" ] && wget --referer="https://www.iconspng.com/" https://www.iconspng.com/uploads/little-rubber-duck.png
[ ! -e "duck.png" ] && convert little-rubber-duck.png -transverse -rotate -90 -trim -resize 1024x1024 -gravity center -background none -extent 1024x1024 +repage duck.png

find newduck -iname "*triangle*.png" -o -iname "*launcher*.png" | while read aaa; do 
echo "Photoshopping ${aaa}..."
SIZE=`identify -format "%w" "$aaa"`
HSIZE=$(($SIZE/2))
convert "$aaa" -level 70%,100% -trim -gravity center -background none -extent ${SIZE}x${SIZE} -gravity southwest -compose over \( duck.png -resize ${HSIZE}x${HSIZE} \) -composite +repage "$aaa"
done

# Enchange privacy

sed -r -i "s,crashreport[^\"]+,fuck@127.0.0.1,g" newduck/smali/org/schabi/newduck/report/ErrorActivity.smali
sed -r -i "s,https?://[^\"<>]+,http://127.0.0.1,g" newduck/res/values/strings.xml
sed -r -i "s,https?://[^\"<>]+,http://127.0.0.1,g" newduck/smali/org/schabi/newduck/CheckForNewAppVersionTask.smali
sed -i "/ACRA;->init/d;/execute/d" newduck/smali/org/schabi/newduck/App.smali

# build final
rm -rv newduck/dist/
java -jar apktool_2.4.1.jar b newduck/

rm newduck.jar
mv `find newduck/dist/ -iname "*.apk" | head -n1` newduck.jar

[ ! -e "newduck.jar" ] && exit

[ ! -e "shit.key" ] && keytool -genkey -keyalg rsa -keystore shit.key -storepass shit123 -keypass shit123 -alias shit -keysize 1024 -dname "CN=1, OU=2, O=shit" -validity 10000
jarsigner -verbose -keypass shit123 -storepass shit123 -keystore shit.key newduck.jar shit
zipalign 4 newduck.jar newduck.apk
```

This is not really a fork, since I was not able to build the application from source, but it allows you to use the application further.

Thanks to the developers for a great product!

**Comment by DI555** [comment]
duplicate
https://github.com/TeamNewPipe/NewPipe/issues/4686

**Comment by opusforlife2** [comment]
You can post this as a comment there.

**Comment by eladkarako** [comment]
very smart use of APKTool,  
luckily the smali for the extractor is nicely separated from the main app,  

May I suggest using <code>0.0.0.0</code> instead of <code>127.0.0.1</code> to save a little delay and timeout of looking for a local web-server.  

Nicely done including a proper signing and aligning to the end of the process,  
I explicitly use sha1 for compatibility reasons for old phones (the signer goes by default to use sha256 otherwise).

https://gist.github.com/eladkarako/caa019c0ee5abff8e14ad26f44236c3a#file-generate_keystore-cmd-L36
https://gist.github.com/eladkarako/caa019c0ee5abff8e14ad26f44236c3a#file-sign-cmd-L56-L57

**Comment by eladkarako** [comment]
the script here (or in https://github.com/TeamNewPipe/NewPipe/issues/4686#issuecomment-721851901) works fine on 0.20.2, but breaks in 0.20.3 when clicking the subscriptions' 'what's new' section (even before an update).
