### ISSUE TITLE
request feature : reply, add 2 UI, subscribe list search, etc

### ISSUE THREAD

**Issue by atuolol** [TeamNewPipe/NewPipe#4792]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
1. feature to show "reply" from each comment. 
2. option change look for "UI for player". there old UI (with bar) and new UI (no bar)
3. search only for "available subscribe list"
4. add build-in browser feature

#### Is your feature request related to a problem? Please describe it
1. i can see the comment but no with the reply
2. old bar where there is an option to change video resolution, share button, 1 click full screen auto play
3. i have a lot of subscribe lists, sometimes it takes too long to scroll. so it will be easy if i type the word in the search bar to find the list of available subscriptions
4. with build-in browser feature, you can login to comment, reply, etc

#### Additional context
1. help view the reply column
2. help users choose the UI they like
3. help find their subscribe list
4. help to login as browser app

#### How will you/everyone benefit from this feature?
1. i want to know if there is a detailed response of each user. with this feature i don't need to open the video in the browser to view the reply.
2. instead of changing the entire player UI with a new look. there should be 2 options to switch to the old UI or the new UI, because each user has different liking. for examples like "i like the old UI especially the old bar". 
sometime i use share button option before play the video. and sometime i want change the resolution before play the video. 
3. makes it easy to find many subscribe lists
4. with build-in browser feature is possible to login within app without depending on other browser apps. absolutely no need for google services.

**Comment by opusforlife2** [comment]
>  This issue contains only one feature request. I will open one issue for every feature I want to request.

_goes on to list multiple features..._
