### ISSUE TITLE
add built-in browser for login to comment

### ISSUE THREAD

**Issue by atuolol** [TeamNewPipe/NewPipe#4796]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
add a built-in browser with a feature that pretends to be mobile and PC for comment. when the user login then the anon comments tab is changed with the real comments tab from the built-in browser also the subscribe button is connected to the account activity.

#### Is your feature request related to a problem? Please describe it
with build-in browser feature, you can login to comment, reply, etc

#### Additional context
help to login as browser for comment, like, subscribe within app

#### How will you/everyone benefit from this feature?
with built-in browser feature is possible to login within app without depending on other browser apps. absolutely no need for google services.

**Comment by opusforlife2** [comment]
Newpipe will never implement login functionality for Youtube. This is by design and on principle. If you're asking for login to Peertube, then there is an open issue for that. You can search for it.

**Comment by atuolol** [comment]
> Newpipe will never implement login functionality for Youtube. This is by design and on principle. If you're asking for login to Peertube, then there is an open issue for that. You can search for it.

ok, i really understand sir 😔
