### ISSUE TITLE
Tablet Mode in minimize of video

### ISSUE THREAD

**Issue by prasumoholkar** [TeamNewPipe/NewPipe#4799]
If u add new Tablet mode in new pipe app then it just awesome .
Currently if i minimise video i have to put video in down side then video with cross button( close button appears at bottom of screen when is good but old fashion ) insted of that put video in tablet mode so that if we put video at down side then video appears at down with right side and small box then swipe left to close video or swipe down to close video.

Very small but very useful gesture and it will great if u add this in next update.

**Comment by opusforlife2** [comment]
Please edit your issue and fill the template properly.
