### ISSUE TITLE
heads up.. YouTube-DL re-updated their extractor (2020.11.01.1)

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#4802]
F.Y.I

http://youtube-dl.org/downloads/latest/youtube-dl.exe  
(windows)  

http://youtube-dl.org/downloads/latest/youtube-dl  
(python)  

will get you the latest release without accessing through GitHub (which is not possible... :|)

<a href="https://www.anonymz.com/?https://github.com/eladkarako/youtube-dl-p/commit/4666180f3b9b430624d6bab2c617d2ad786635e6#diff-ae6d30f4d5d230f74245c8b248866e9584db06a82cbda8e26c3363f9c41f89f2" rel="nofollow">...............</a>

<blockquote>(ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.)</blockquote>

<hr/>

Ps.
If you want to prevent the mysterious "call home" of YTDL (<code>--no-call-home</code> does nothing..),  
first block (<a href="https://en.wikipedia.org/wiki/Hosts_(file)">HOSTS</a>) with:  
<pre>
0.0.0.0 www.youtube-dl.org
0.0.0.0 youtube-dl.org
</pre>

and curl (with explicit resolving) to download ;)
<pre>
curl --ipv4 --anyauth --insecure --location-trusted --verbose --resolve "youtube-dl.org:443:95.143.172.170" --resolve "youtube-dl.org:80:95.143.172.170" --url "http://youtube-dl.org/downloads/latest/youtube-dl.exe" --output "youtube-dl.exe"

curl --ipv4 --anyauth --insecure --location-trusted --verbose --resolve "youtube-dl.org:443:95.143.172.170" --resolve "youtube-dl.org:80:95.143.172.170" --url "http://youtube-dl.org/downloads/latest/youtube-dl"     --output "youtube-dl.rar"
</pre>

**Comment by mhmdanas** [comment]
What does this have to do with NewPipe? NewPipe does not use youtube-dl in any way.

**Comment by eladkarako** [comment]
<blockquote> What does this have to do with NewPipe?</blockquote>

<del>🙄</del> - sorry.  

<em>fyi.</em>

YouTube encrypted data (HTML/JS) requires some pattern matching in-order to fetch the actual playable (or downloadable) streams (the given URLs in the HTML or video-info API does not include some of the carry-on data in the GET-request).  

Whenever the placement or string format slightly changes,  
NewPipe (and several other apps) stops working, and 'you' get several bugs saying "videos stopped playing".  

YouTube-DL developers are quite fast in identifying the new pattern,  
and we (NewPipe lads) often just slightly transform the Python syntax of Regular-Expression or string matching to something the extractor (Java) can use.  

I've noticed the recent change,  
when I've updated one of my projects that uses YouTube-DL,  
and figured, since it was more recent than the latest release of NewPipe,  
we (NewPipe lads again) might benefit from it,  

Also,  
It was a good way of placing some information on how to fetch the latest release of YouTube-DL,  
for the benefit of maintainers that might want to help in the future,  
since the repository of YouTube-DL in GitHub is no longer "directly" accessible,  
<strong>but still functional</strong> if you got the right syntax.  

That is essentially it.  

Ps.
Now that I've come to think of it...   
an "early warning system" (based on fetch/diff of YTDL's youtube module),  
can be optionally built,  
which might help us identify a signature change faster,  
and deploy a fix/release for it,  
avoiding all (most) of the "videos not playing" bugs  (note that YouTube deploys its changes gradually),  

There should probably be a new issue (feature request?) opening to discuss this idea...

**Comment by eladkarako** [comment]
<blockquote> What does this have to do with NewPipe?</blockquote>

<del>🙄︎</del> - sorry.

<em>fyi.</em>

YouTube encrypted data (HTML/JS) requires some pattern matching in-order to fetch the actual playable (or downloadable) streams (the given URLs in the HTML or video-info API does not include some of the carry-on data in the GET-request).  

Whenever the placement or string format slightly changes,  
NewPipe (and several other apps) stops working, and 'you' get several bugs saying "videos stopped playing".  

YouTube-DL developers are quite fast in identifying the new pattern,  
and we (NewPipe lads) often just slightly transform the Python syntax of Regular-Expression or string matching to something the extractor (Java) can use.  

I've noticed the recent change,  
when I've updated one of my projects that uses YouTube-DL,  
and figured, since it was more recent than the latest release of NewPipe,  
we (NewPipe lads again) might benefit from it,  

Also,  
It was a good way of placing some information on how to fetch the latest release of YouTube-DL,  
for the benefit of maintainers that might want to help in the future,  
since the repository of YouTube-DL in GitHub is no longer "directly" accessible,  
<strong>but still functional</strong> if you got the right syntax.  

That is essentially it.  

Ps.
Now that I've come to think of it...   
an "early warning system" (based on fetch/diff of YTDL's youtube module),  
can be optionally built,  
which might help us identify a signature change faster,  
and deploy a fix/release for it,  
avoiding all (most) of the "videos not playing" bugs  (note that YouTube deploys its changes gradually),  

There should probably be a new issue (feature request?) opening to discuss this idea...

**Comment by mhmdanas** [comment]
Oh, that makes more sense. Opening a GitHub issue for a heads up is fine, but it's a better solution to write such things on the IRC room. As for your early warning system idea, you might want to open that as a separate issue.

**Comment by eladkarako** [comment]
> IRC room

never used or going to ever use that.

**Comment by mhmdanas** [comment]
No problem. I just said it's better to write stuff like this on the IRC room, but you can still do it here.

**Comment by eladkarako** [comment]
> IRC room

never used or going to ever use that.  

An issue is persistent, crawl'able (can be found by Google),  
and searchable (GitHub and Google once crawled), thus far more superior.  

'side, IRC IZ 4 D0RKS ;)

**Comment by eladkarako** [comment]
> IRC room

never used or going to ever use that.  

An issue is permanent/long-lasting, crawl'able (can be found by Google),  
and searchable (GitHub and Google once crawled), thus far more superior.  

'side, IRC IZ 4 D0RKS ;)

**Comment by opusforlife2** [comment]
Thanks. We're aware we can get the source from the official website if we need to.
