### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by naddel81** [TeamNewPipe/NewPipe#4811]
link to YT sub manager does not create XML file, but opens https://www.youtube.com/feed/channels

please help. tried even on PC.

**Comment by naddel81** [comment]
why closed?

**Comment by Stypox** [comment]
You opened two identical issues

**Comment by naddel81** [comment]
oh, sorry. do you know how to export the needed XML?

**Comment by Stypox** [comment]
You can't for now. You'll have to wait for 0.20.3 to land or try the apk in #4759

**Comment by naddel81** [comment]
20.3 there yet?

**Comment by opusforlife2** [comment]
@naddel81 The release candidate is out for you to test. Check the pinned issue.

**Comment by naddel81** [comment]
great. youtube import is working again?
