### ISSUE TITLE
Age restricted videos can't be watched

### ISSUE THREAD

**Issue by Mancusoo** [TeamNewPipe/NewPipe#4818]
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
 Although viewing age restricted content is allowed in the settings, restricted videos won't start. Instead there is the notification, that the video is not available. 

### Expected behavior

Video should start like any other video. 

### Screenshots/Screen recordings
https://s12.directupload.net/images/201106/qapf4d9s.png

### Device info

 - Android version/Custom ROM version: Android 10 / Evolution X 4.7
 - Device model: ONEPLUS 2 A2003

**Comment by Stypox** [comment]
#4681

**Comment by opusforlife2** [comment]
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

O_O
