### ISSUE TITLE
Long (>100 items) youtube playlists won't load beyond the 100th item

### ISSUE THREAD

**Issue by LunaDragofelis** [TeamNewPipe/NewPipe#4819]
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Method A
1. Open any youtube playlist that is longer than 100 items
2. Scroll to the bottom of the playlist view

Method B
1. same as method A
2. use the "play in background" feature
3. tap on the notification to open the background play queue
4. scroll to the bottom of the queue view

### Actual behaviour
NewPipe doesn't load the playlist items beyond the 100th, preventing access to them from NewPipe. It doesn't even show the spinning circle.

### Expected behavior
NewPipe would previously (until yesterday, but already unreliably for a while) show the spinning circle for a few seconds, then show more items from the playlist

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Motorola moto g7 play

**Comment by Drakim42** [comment]
This bug started a few hours ago for me.  There were no signs of it before today. 

LineageOS 14.1
Nvidia Shield K1

**Comment by opusforlife2** [comment]
Which service is this? Youtube? Soundcloud?

**Comment by Drakim42** [comment]
Youtube. (Edited my previous post with the missing info)

**Comment by opusforlife2** [comment]
Do other services work?

**Comment by Drakim42** [comment]
Soundcloud only loads 10 items at a time. The other services seem to be working.

**Comment by Drakim42** [comment]
Soundcloud only loads 10 items at a time and displays a constant loading animation at the bottom. The other services seem to be working.

**Comment by opusforlife2** [comment]
Alright. Let's keep this one for Youtube.

**Comment by PrSunflower** [comment]
Same bug for me with NewPipe 0.20.2 on Nokia 7.2. Everything worked fine with the previous version, the bug appeared on the newer version (it was released to fix a major bug that prevented every video from playing).

**Comment by opusforlife2** [comment]
@PrSunflower Could you reinstall 0.20.1 and confirm this bug doesn't exist there?

**Comment by Drakim42** [comment]
The bug is still there after reinstalling every version going back to 0.19.7. That version never had this problem for me, but now it does.

(Possible coincidence)
YouTube Vanced started having problems playlist-wise right before I encountered NewPipe's playlist bug.

**Comment by PrSunflower** [comment]
> @PrSunflower Could you reinstall 0.20.1 and confirm this bug doesn't exist there?

Hi @opusforlife2 , thank you for replying. I just did and surprisingly long playlists still don't load 😮

I tried NewPipe **0.20.0** and **0.19.8**, the bug happens too! I swear I didn't have this problem before, could it be my phone (Nokia 7.2) which received an update and now blocks NewPipe from loading long playlists?

**Comment by FireMasterK** [comment]
I can replicate this, let me know what's needed to debug further.

**Comment by FireMasterK** [comment]
Correct me if I'm wrong but I believe youtube-dl has a fix for this: https://github.com/l1ving/youtube-dl/pull/32/commits/ba51eec692a33a977b0a0fab1f4af5eb3646f7b0

**Comment by CrazyCodeTM** [comment]
is the bug still being resolved?

**Comment by CrazyCodeTM** [comment]
Same problem here version 0.20.2 android 8.1.0 Moto G4 Plus
Is the bug still being resolved?

**Comment by XiangRongLin** [comment]
I fixed the issue in the PR linked above. You can check out the debug apk there and report any problems there if it still doesn't work.

**Comment by pat277** [comment]
This has been happening (for me) since 20.1, and still occurs for 20.3

**Comment by PrSunflower** [comment]
I have just installed 0.20.4 and the playlists now load correctly!

Thanks a lot everyone 😄

**Comment by CrazyCodeTM** [comment]
Thank you very much devs, you are beautiful :heart_eyes: , here is working perfectly, for those who want it is here on this [link](https://github.com/TeamNewPipe/NewPipe/releases/download/v0.20.4/NewPipe_v0.20.4.apk)
