### ISSUE TITLE
[Feature Request] Manual update check

### ISSUE THREAD

**Issue by willemijns** [TeamNewPipe/NewPipe#4820]
Hello,

We do not know when auto update check is done so a button to force manual check can be useful.

**Comment by HansCronau** [comment]
I'm not entirely sure if it is what you are looking for, but you can find a manual refresh under Subscriptions > All. At the top you will see a bar reading 'Feed last updated'. You can press it to update your feed manually.

**Comment by willemijns** [comment]
I thought to the software update (settings/update) not a feed update ;)

**Comment by Stypox** [comment]
Update checks are done each time you open the app, if downloaded from GitHub. Since you didn't fill in the template, I have no idea why this would be useful, so I'm closing
