### ISSUE TITLE
Can't install 0.20.2 from apk or custom repo

### ISSUE THREAD

**Issue by Saroumane** [TeamNewPipe/NewPipe#4822]
I tried both ways available now :
- custom newpipe repo in fdroid
- direct download of the apk from this github
Both failed "to install due to an unknown error"

### Device info

 - Android version/Custom ROM version: GrapheneOS 3/11 update (Android 11)
 - Device model: Pixel 3a

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe#updates

**Comment by Saroumane** [comment]
Sorry but I don't understand you response.
Yes I followed methods n°2 and n°3 (as n°4 is not ready and n°1 is out of my scope.)
Of course I didn't try to update from a different source : I tried to install from a fresh start.

**Comment by opusforlife2** [comment]
Just making sure.

**Comment by Stypox** [comment]
This is likely an issue with the OS, since no other Android 11 users ever reported it, and with the few information Android gives (i.e. the useless "unknown error") I don't think there is much that can be done

**Comment by brase** [comment]
This happens for me aswell. Using Android 9.

**Comment by brase** [comment]
Okay, for me this happend cause I still had the fdroid version installed. Uninstalling it before installing the apk from github fixed it.

**Comment by opusforlife2** [comment]
> I tried to install from a fresh start.

@Saroumane Like @brase said, he had an incompatible version installed. Are you absolutely sure that's not the case for you?

**Comment by Saroumane** [comment]
100% sure.

**Comment by pgenderson** [comment]
Do other Graphene users have the same problem?

**Comment by Stypox** [comment]
@Saroumane when F-Droid's repo (not ours) finally builds 0.20.2 could you test it from there?

**Comment by Saroumane** [comment]
Sure.
For information : I just created a separate android user profile and I installed fdroid, then newpipe custom repo. Same problem : I cannot install anything coming from newpipe custom repo.

I tried to install tor browser from Guardian custom repo : no problem.@

**Comment by opusforlife2** [comment]
> Do other Graphene users have the same problem?

Good point. @job3rg do you face the same issue?

**Comment by Stypox** [comment]
@Saroumane could you try to capture a logcat while you try to install the APK? Though it might not contain anything useful

**Comment by PFDaily** [comment]
I'm pretty sure I have this issue on Android 6.0.1, but mine is related to the OS not allowing unsigned code even in developer options. I have the Google play scan turned off. I'm stuck waiting for whenever fdroid team can manually sign the code.

**Comment by Stypox** [comment]
@PFDaily the NewPipe APKs distributed on GitHub and in our fdroid repo ARE signed, aren't they? @TheAssassin

**Comment by ldnpub** [comment]
I have the same issue, with oxygen os 9.
Custom repo: nok
Classic repo: nok
Github apk: nok

**Comment by eladkarako** [comment]
Just out of curiosity, how DO you sign the APKs?  
<sup>(jar signer / signature schemes <sup><a href="https://source.android.com/security/apksigning/v3">(v3)</a></sup>)</sup>

**Comment by StyXman** [comment]
I have a similar issue with f-droid and the NP repo, but the error is different: `Error installing NewPipe: /data/user/0/org.fdroid.fdroid/cache/apks/archive.newpipe.net--1/ repo failed to verify!`. I double checked the fingerprint (E2 40 2C ... 7E 75 01) and it matches the one here: https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/ (I used the manual version; the link didn't work). This is FP2 with an Android 7.1.2, f-droid 1.10. Let me know if I should open another ticket or provide more info.

**Comment by ukanuk** [comment]
> I have a similar issue with f-droid and the NP repo, but the error is different: `Error installing NewPipe: /data/user/0/org.fdroid.fdroid/cache/apks/archive.newpipe.net--1/ repo failed to verify!`.

I get the same error as @StyXman, using a Galaxy S10e with Android 10 and the December 2020 security patch.

However, I was able to download and install the APK directly from github.

**Comment by nerfpops** [comment]
Getting the same error on pixel 2 xl, android 11

**Comment by TriplEight** [comment]
Dame with my pixel 3axl android 11, added your repo as in manual
https://archive.newpipe.net/fdroid/repo/?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501 it's shown as signed in the repos list.
And now I'm getting `repo failed to verify!` error.
![Screenshot_20201229-091119](https://user-images.githubusercontent.com/17856421/103269395-0fa0bd00-49b6-11eb-8e8d-281e69528a1a.png)

**Comment by moerkey** [comment]
Can not update/install to the current version 0.21.16.
I am getting the same error: Failed to install due to an unknown error.
I tried it via apk and F-Droid with upstream repo.

I don´t have a problem with installing the previous version 0.21.15.

Model name: Samsung Galaxy XCover 5
Model number: SM-G525F/DS
Android 11 Security Patch Level 01/22

![Screenshot_20220204-194605_F-Droid](https://user-images.githubusercontent.com/39277712/152586820-602997b6-fc2f-4260-96e9-49353971e7a0.png)

**Comment by ThisIsPaulDaily** [comment]
I just did this the other day on my second phone. The first time you add the Newpipe upstream repo, you'll need to export your data from the app. Then uninstall the F-Droid signed app, close and re-open F-Droid and install Newpipe again (and import the export you created). 

This is a Key signature substitution issue. You can't directly update an app that has mismatched keys.

**Comment by moerkey** [comment]
> I just did this the other day on my second phone. The first time you add the NewPipe upstream repo, you'll need to export your data from the app. Then uninstall the F-Droid signed version of the NewPipe app, close and re-open F-Droid and install NewPipe again (and import the export you created).
> 
> This is a Key signature substitution issue. You can't directly update an app that has mismatched keys.

Yeah, thank you. I already did that and it does not work.

But I found out that your repo is showing multiple entries for the previous versions.

![Screenshot_20220209-064430_F-Droid](https://user-images.githubusercontent.com/39277712/153132376-30664fd8-e3bd-4d9a-85fe-3bf30591ee67.png)

0.21.15 was added on 23.12.2021 and then later on 28.12.2021. 
Guess which one can not be installed?
Yes, the one from 23.12.2021.

Someone in here was asking for the signing of the packages. Maybe that is a clue?

**Comment by ThisIsPaulDaily** [comment]
Hey, I'm just a guy on the internet trying to help not even someone who has submitted a PR to the project yet so it's not "my repo" Just so we can be certain though you followed these instructions for adding the NewPipe Repo? https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

The duplicated entries are coming from two repositories one named "F-Droid" and one is the "Upstream" repository. Can you also check you have the latest version of F-Droid? It probably doesn't matter, but my Versions screen for the repo looks much different and I don't have the duplicate entries like you do. Are you sure you uninstalled the F-Droid repo version of the app?

Can you re-check that you followed those steps for me? Go into F-Droid and click settings, then Repositories, then verify it is enabled (toggle in the same position as "F-Droid") tap "NewPipe upstream repository" and verify the reported "Last Update" Date for me. I think as of 2022-02-11 @ 10:41AM CST the last update date should be "February 2, 10:01PM"* Though it could be newer when you check. 

*I'm not entirely certain if that is the last time I updated an app using that repo, or the last time that repo was updated, either way following the steps linked again should help. 

Please circle back with what you find out!

**Comment by moerkey** [comment]
Uninstalled  NewPipe.
Uninstalled F-Droid.
Reinstalled F-Droid (1.13.1 is suggested version).
After updating the repos I got offered NewPipe 2.21.16.
Installed NewPipe.
Everything runs fine without the F-Droid repo.
So I will monitor F-Droid for releases and reinstall it manually.

**Comment by ThisIsPaulDaily** [comment]
I'm not saying to uninstall the F-Droid app. I'm sorry for giving that impression. 
The NewPipe Upstream repo is the one that you want, it will be the same as the one you would download from github. 
The one you download from the "F-Droid" repo is verified and checked by the F-Droid team manually and then signed by them. This signing process delays released apps and is why F-Droid supports alternative repos. 

See on 28/11/2021 Repository in your screenshot is listed as F-Droid on one version, and on the second version in your screenshot it shows (scrolling text) upstream repository. 

Given that you're trying to install NewPipe from a downloaded file and the version tags are probably the same version, it doesn't need to install. 

I don't know why you would uninstall the latest version and try to install it again.  It looks like you did everything correctly until you tried to install an alternative download. 

I am thinking that when you said "NewPipe 2.21.16" you mistyped and meant 0.21.16 as that is the current version and any version with a newer tag is not likely signed by the NewPipe repo keys and would be flagged as a duplicate and fail to install.

**Comment by moerkey** [comment]
Thank you for your effort. But I just skim your posts. They are too long and you keep repeating yourself.
JFYI: I followed the instructions on https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/.

I have now a workaround which works: 

1. Create backup: Settings > Content > Export Database
2. Uninstall NewPipe
3. Uninstall F-Droid
4. Install F-Droid
5. Install NewPipe (without repo) 

The repo for me didn´t work out in my situation. Maybe it helps others. I will test sooner or later.

Dropping out of this topic. It is getting off topic anyway.

**Comment by ThisIsPaulDaily** [comment]
Ok, so where did you source the NewPipe package that you installed? You mentioned 2.21.16 was your version string and I wanted to clarify that it didn't come from NewPipe if that was the version string. 

If you re-opened this ticket, you can close, it but I'm concerned that you're just going to be back here when the next update releases as you didn't solve your issue. I linked those instructions as did others. 
You don't need that work-around. You're trying to install the version of NewPipe that you already have installed and therefore can't install it. 
0.21.16 IS the same package as NewPipe Upstream Repo through the link you gave as it is from directly downloading from Github. 

This issue can respectfully be closed again as user error/ PEBKAC

**Comment by opusforlife2** [comment]
One thing that might be causing an issue is that the Newpipe F-Droid repo wasn't added properly. F-Droid is supposed to verify a repo's fingerprint before being able to use apps from it. The repo's name should appear in the list of repos, instead of the repo URL. Is that the case?
