### ISSUE TITLE
Can't play any video

### ISSUE THREAD

**Issue by Hussain-Ruhullah** [TeamNewPipe/NewPipe#4826]
![Screenshot_20201106_205233_org schabi newpipe](https://user-images.githubusercontent.com/21989914/98408800-09efc080-2072-11eb-829d-fd33411356a0.jpg)

**Comment by vkay94** [comment]
Please update to latest version (0.20.2) which fixes this problem. You can find it on the GitHub releases page (F-Droid is not updated yet).
