### ISSUE TITLE
Pls add Bitchute video hosting

### ISSUE THREAD

**Issue by ah1102** [TeamNewPipe/NewPipe#4827]
Please add video hosting Bitchute https://www.bitchute.com . Many bloggers from youtube go there. It is now gaining relevance. 

![Снимок экрана 2020-11-07 в 00 20 15](https://user-images.githubusercontent.com/58341369/98415818-09b1ee00-208f-11eb-8070-3b50d8eb4f47.png)

**Comment by opusforlife2** [comment]
Service requests go in the Extractor repo, not here.
