### ISSUE TITLE
Cast to kodi entire playlist

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#4828]
### Checklist
- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Build a playlist
2. Cast it to kodi
3. Tested with both adding to queue and playing now

### Actual behaviour
Only the currently playing video gets casted

### Expected behavior
Enqueue the entire playlist

### Device info
 - Android version/Custom ROM version: 10/ API 29
 - Device model: Samsung Galaxy A70

**Comment by opusforlife2** [comment]
>  I am using the latest version - x.xx.x

Is your version going to stay a secret? :P

**Comment by kubo6472** [comment]
> > I am using the latest version - x.xx.x
> 
> Is your version going to stay a secret? :P

0.20.2 added. Probably just missed it. I know it's the latest.

**Comment by seniorm0ment** [comment]
mopidy casting would be nice as well

**Comment by seniorm0ment** [comment]
Does closed mean not being implemented, or?

**Comment by kubo6472** [comment]
I have no idea, closed it myself, since it didn't seem to move anywhere in the last 3 years
