### ISSUE TITLE
Put a download option in the context/hold down menu

### ISSUE THREAD

**Issue by RainbowAsteroids** [TeamNewPipe/NewPipe#4834]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Whenever you download a video, it can be a hassle trying to wait for all the metadata to load, and then pressing on the button. This is okay if you're only looking to download one video, however if you plan on downloading several, such as from your feed, this becomes tiresome. It would be great if I could hold down on the video and press download.

#### Is your feature request related to a problem? Please describe it

I guess it solves the problem of being able to start a download quicker than before.

#### Additional context

If you hold down on a video, such as from your feed, trending, searches, etc, you will get a menu with a few options. I will call this the context menu since I have no idea what it's officially called.

#### How will you/everyone benefit from this feature?

It will help everyone download videos more efficiently. It will also allow you to download videos without interrupting the one you're watching at that moment, so you can watch it later or something.

**Comment by opusforlife2** [comment]
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

#2171. O_O
