### ISSUE TITLE
[more information needed] after playing few videos, sound freezes, overall phone freeze, device must be restarted (memory leak?)

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#4835]
I've noticed something weird in 20.0-20.2,  
that might be related to a seriously nasty memory leak, I believe to be origin from the embedded player,  

It is somewhat inconsistent (perhaps related to limited memory if other apps runs in the background on limited memory of my device) but usually after playing 4-5 videos,  
in any order, usually with pausing one, pressing back and selecting another (start playing, and repeat the process),  
both when using head-phones or speaker.

The sound will "crack" (the last few tunes will play forever"),  
the screen will freeze and the entire device will stop reacting.  

I believe it might be origin from the embedded player due to inefficient memory release (thus not 100% directly related to new-pipe, but that is just a hunch/ gut feeling - it might as well be the way the player is implemented).  

my workaround is currently to switch on using external player for audio and video,  
it only works on 720p (which for some reason is A/V - other streams such as 240p have V-only streams so they play with no audio on external player).

<hr/>

I need more information,  
may you direct me to a recent DEBUG version (so I'll inspect the stack usage collect memory dumps and such..)

**Comment by krtfwd** [comment]
this kinda reminds me of my issue which is also tagged info needed and i think noone is looking into it
 https://github.com/TeamNewPipe/NewPipe/issues/4679

**Comment by eladkarako** [comment]
yes, very possibly a duplicate.
I wasn't too specific regarding the state the screen, and I am too using custom firmware lineageos (lineage-14.1-20181012-UNOFFICIAL-MONTHLY-ja3gxx) on my Samsung Galaxy S4 and the media pipe is acting weird and disables something related to media decoding:  

```
media.stagefright.legacyencoder=1
media.stagefright.less-secure=1
```

(by default) 
which utilise a one stack shared by all process.


I'm closing this one.
