### ISSUE TITLE
Android TV - Video does not start as full screen automatically

### ISSUE THREAD

**Issue by ndr48291** [TeamNewPipe/NewPipe#4841]
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Watch a video on Android TV
2. It is not started as a full screen automatically
3. See the picture in the attachment.

### Actual behaviour

Video does not start as a fullscreen

### Expected behavior

Video should start as a fullscreen

### Screenshots/Screen recordings

![IMG_20201108_120033](https://user-images.githubusercontent.com/46603635/98468252-b9e83980-21ea-11eb-93ce-0b18eb38d4b2.jpg)

### Device info

 - Android version/Custom ROM version: Android TV 8.0
 - Device model: Philips PUS550112 55" Android TV

**Comment by opusforlife2** [comment]
Related: #4152.

**Comment by Stypox** [comment]
@opusforlife2 let's keep everything in #4152
