### ISSUE TITLE
"Content unavailable" for videos available in the browser.

### ISSUE THREAD

**Issue by gasull** [TeamNewPipe/NewPipe#4849]
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to https://m.youtube.com/watch?v=9WfZuNceFDM on your browser, not on NewPipe.
1. Share page to NewPipe.

### Actual behaviour

I get the error "Content unavailable".

Same error happens if posting the URL on the search box of NewPipe.

And the video won't be found by the title using NewPipe search.

### Expected behavior

The video should be found and played on NewPipe.

### Device info

 - Android version/Custom ROM version: LineageOS (Android version 9)
 - Device model: ASUS_X00TD

**Comment by opusforlife2** [comment]
Works just fine for me. Could you try sharing to Newpipe again?

**Comment by Stypox** [comment]
@gasull do you have "YouTube restricted mode" active or "Show age restricted content" inactive in content settings?

**Comment by gasull** [comment]
> @gasull do you have "YouTube restricted mode" active or "Show age restricted content" inactive in content settings?

I had "YouTube restricted mode" active.  It works now.  Thank you.
