### ISSUE TITLE
Video Intent Filter Hijacking/Really cool idea

### ISSUE THREAD

**Issue by GeitHub** [TeamNewPipe/NewPipe#485]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [N/A] I checked if the issue/feature exists in the latest version.

So in F-Droid there are several apps that allow you to "hijack" intent filters for things like URLs (to pick a browser) and location data (to pick a location app to gleam GPS data from). No such app exists to share with video players. The closest such app is NewPipe. For Example:

1. [Download the latest NewPipe](https://f-droid.org/repository/browse/?fdfilter=newpipe&fdid=org.schabi.newpipe
)
2. [Download the latest (auto-updating) Firefox Aurora build](https://www.mozilla.org/en-US/firefox/android/aurora/all/
)
3. [Download the latest VLC Nightly for your device's architecture](http://nightlies.videolan.org/) (FYI the F-Droid VLC maintainer is working with upstream to [get the latest stable build into F-Droid](https://forum.f-droid.org/t/where-is-the-vlc-app/108/4))
4. Launch NewPipe and tick the external Video/Audio player checkboxes, as well as the autoplay when called from another app box
5. Launch Firefox and open a YouTube [video](https://www.youtube.com/watch?v=UjXi6X-moxE
)
6. Click the grey Android icon in the URL bar to share with another App, choose NewPipe
7. Select VLC as the video player of choice when NewPipe opens and set the preference to 'Always'
8. Close the first-run popup fluff from VLC
9. Tweak the various options for playback such as adjusting video speed (just like desktop youtube)
10. Attempt to use the popup/overlay player, after allowing the permission feel sad when NewPipe still thinks you've just shared the link and throws you right back into the full VLC player
11. Uncheck 'autoplay' in NewPipe's settings
12. Launch VLC and tweak some of the stranger settings to your liking (like disabling the odd ability to adjust brightness by sliding your finger on the player)
13. Try this with a few videos and notice how much more stable VLC on Android has become (unless you grabbed a bad nightly, then try an older nightly)
14. Possibly notice the occasional [bug](https://github.com/TeamNewPipe/NewPipe/issues/263) that requires you to tap the NewPipe play button a few times before it finally sends the request to VLC
15. [Download this newly released completely local FOSS RSS app from F-Droid](https://f-droid.org/repository/browse/?fdfilter=feeder&fdid=com.nononsenseapps.feeder)
16. Launch NewPipe, navigate to a YouTube channel, click subscribe, open with Firefox, tap Android's menu button, select the Share icon, tap "Subscribe to feed", click enter, click the result, tag the feed (optional), add the feed
17. Launch Feeder, swipe down to refresh, click a video, share with NewPipe
18. Notice how close this is to working beautifully together
19. Suddenly remember the fact that VLC also has a Playlist feature as well as the ability to pull in video metadata including YouTube's auto-generated subtitles for deaf users
20. Recall that [SkyTube](https://f-droid.org/repository/browse/?fdfilter=sky&fdid=free.rm.skytube.oss) offers the ability to display YouTube comments
21. Imagine how awesome it'd be if this all of this under one roof!
22. (jk, it'd probably be a nightmare to work that all out lol)

That's basically my system for watching YouTube videos on Android. I thought outlining it might give you some ideas for future development of the app. For me personally though, a big sticking point is the ability to share videos with VLC without the need of the full NewPipe GUI as a middle man. I've been using this system for awhile now (with spaRSS instead of Feeder), but now that you've separated the NewPipe logic into a CLI I'm wondering if you would consider drafting a quick and dirty repo for an APK I could fork around with in order to do just that. I ask this given your experience with crafting a 'share with' application in the past for NewPipe before baking it into NewPipe itself. I haven't any experience with Java/Android programming, but I've spent some time reading up on VLC's [(outdated?)](https://wiki.videolan.org/Android_Player_Intents/) documentation about intents, (outdated) stackoverflow threads about the pitfalls/challenges of VLC's intent variables, as well and the official Android documentation, but any help on your end would be much appreciated given that your approach more or less 'just works.'

Thanks!

edit: here's the most straightforward example of what I mean by an 'hijacking' application btw:
https://f-droid.org/repository/browse/?fdfilter=browser+intercept&fdid=com.intrications.android.sharebrowser

**Comment by mauriciocolli** [comment]
If I understand what you said...
Something like this?
![externalplayer](https://cloud.githubusercontent.com/assets/13389907/24229103/b940b8f4-0f56-11e7-8044-9c742c046b48.gif)

**Comment by GeitHub** [comment]
@mauriciocolli precisely!

**Comment by theScrabi** [comment]
Yea go on, te extractor was pulled out from NewPipe in order to allow projects like this.

**Comment by GeitHub** [comment]
@mauriciocolli have you got an APK to share? I can't seem to find build instructions in the extractor repo

**Comment by theScrabi** [comment]
Do it like it's done one np-cli. You have to create a directory called `org/schabi/newpipe` in your src dir. Than you enter that dir and clone the extractor in it `git clone https://github.com/TeamNewPipe/NewPipeExtractor.git extractor`
Now make sure your project has the following libs available:
- org.json
- Mozilla rhino
- org.jsoup

Now you are good to go.
How ever future gowl is to make NPExtractor a Marven repo ...

**Comment by mauriciocolli** [comment]
I was thinking in implementing this, is really useful for me, but I was wondering how I would make that an option and I think I'll do it like the video in the previous post.

But there's another problem, too many option in the share menu (and "Open With" too), then I guess an option in the settings, for those who don't want this, will be useful:

![o](https://cloud.githubusercontent.com/assets/13389907/24270097/853f2224-0ff2-11e7-8da5-fc7fcbf162c7.gif)
###### _It'll be something like this_

What do you guys think?

PS: @GeitHub I'm not behind the YT+, as the project don't accept code modifications (and I don't know much about JavaScript), I just report bugs and improve translation.

**Comment by theScrabi** [comment]
What is YT+ ?!?

**Comment by SkyzohKey** [comment]
@theScrabi @mauriciocolli YT+ ? https://pastebin.com/FVAttLFw

**Comment by mauriciocolli** [comment]
It's a extension for Youtube.
