### ISSUE TITLE
Download of Youtube subscriptions no longer possible with "in-app" method.

### ISSUE THREAD

**Issue by Awebb** [TeamNewPipe/NewPipe#4850]
### Checklist

- [x] I am using the latest version - v0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.  (#4810 has been closed due to reporting fuck-up)
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to Channel groups tab
2. Expand "Subscriptions"
3. Under "Import from" click on Youtube
4. Click on the provided URL

### Actual behaviour

The URL is being redirected to https://m.youtube.com/feed/channels. No file is being downloaded.

### Expected behavior

https://www.youtube.com/subscription_manager?action_takeout=1 is supposed to generate a downloadable file.

### Attempts to analyse and fix
1. Force the desktop page in Android chrome, in case the m. transition is to blame >> No fix.
2. Navigate to the URL with desktop Chrome >> No fix.
3. Navigate to the URL with desktop Firefox >> No fix.
4. Ignore the redirection with curl >> No fix.
5. Append ?action_takeout=1 to the redirected URL >> No fix.
6. Could not find a method to get the feed from the site manually.

### Screenshots/Screen recordings

No relevant screenshot available.

### Logs

No log has been generated.

### Device info

 - Android version/Custom ROM version: 8.0.0 stock
 - Device model: RNE-L22

**Comment by opusforlife2** [comment]
>  (#4810 has been closed due to reporting fuck-up)

But it also contains a link to the original issue which is already fixed?

**Comment by Awebb** [comment]
Outch. Lesson of the day: Breakfast first, then bug reports!
