### ISSUE TITLE
Feed not loading when using the fast method

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#4866]
- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

Whenever I try to refresh my feed it gets a bit in, and has a network error. Nothing seems to be wrong with my wifi.

**Comment by opusforlife2** [comment]
> it gets a bit in

What do you mean?

**Comment by personaaleatoria** [comment]
Same problem here. The feed loads only up to a certain point, then a "Network Error - Rety" message appears.

**Comment by opusforlife2** [comment]
Ah. Some of it loads. Thanks for clarifying.

**Comment by pratheep15** [comment]
same issue for me too, feed loading stops in middle with network error.

**Comment by opusforlife2** [comment]
Is there anyone here who has channels of only one service, like only Youtube?

**Comment by pratheep15** [comment]
> Is there anyone here who has channels of only one service, like only Youtube?

I do.. using only for youtube.

**Comment by opusforlife2** [comment]
Then it's possible this is a Youtube issue. Although I've tried refreshing the feed a couple of times and it works fine for me.

**Comment by opusforlife2** [comment]
Oh wait, are you all using the full feed update method or the fast method?

**Comment by pratheep15** [comment]
Guys I disabled 'settings - content - fetch from dedicated...' & feed fetch is working now..
check it.

**Comment by HolySoap** [comment]
@opusforlife2 fast method, also I heard YouTube was down last night (on my local time), I assume they changed a lot behind the scenes.
I checked twice and yes fast feed is bugged.

**Comment by opusforlife2** [comment]
Thanks for confirming, guys. Meanwhile, everyone should switch to using the full method.

**Comment by HTSamurai** [comment]
Why is this open
It was fixed ages ago
