### ISSUE TITLE
Phone enters a lock loop when certain videos are played

### ISSUE THREAD

**Issue by atranson** [TeamNewPipe/NewPipe#4868]
### Checklist

- [x] I am using the latest version - 0.20.2 (though the same occurs with 0.20.3-RC1)
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Find this video: https://www.youtube.com/watch?v=YR_wIb_n4ZU
2. Press the button to play audio in background or simply play the video (either through a manual action or via the autoplay when entering the video page)

### Actual behaviour
The phone instantly locks up then unlocks every few seconds. If the video was launched instead of the audio, the NewPipe interface will be visible for a few instants before the phone locks up again.
The only way out of this loop, apart from rebooting the phone, is to interrupt playback. I usually do that by entering photo mode and recording a video (which I can do from the lock screen) but it also works if I unplug headphones.
Once the playback is stopped, I can properly see the NewPipe notification with the background matching the video and the various buttons to interact with it. Pressing the play button there triggers the same behaviour.

Note that either way, the audio is playing normally during the lock loop.
This doesn't happen with all videos, for example, this one: https://www.youtube.com/watch?v=Xpkc-NU1KA0 works fine as many others. I could not notice any pattern regarding why a certain group of videos work while the other does not. 
The only thing I am pretty sure of is that this issue has been affecting the same videos consistently since I updated to 0.20.2.

### Expected behavior
Video plays normally in the chosen mode.

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Sony Xperia Z2 Compact

**Comment by opusforlife2** [comment]
Could you switch formats in settings and try again? If it's mp4, use webm and vice-versa.

**Comment by atranson** [comment]
Switching default video format in settings does not seem to fix the issue.
I tried to do the same with the default audio format but nothing changed either.

**Comment by opusforlife2** [comment]
Can you make a database backup from settings and check a few other versions to see if they work? Check 0.20.1 and 0.19.8 at the minimum.

**Comment by atranson** [comment]
The 0.20.1 is not able to parse extract any metadata for any video which is the reason why I updated to 0.20.2.
Since I can't access any video in previous versions, I can't reproduce the issue with those.

**Comment by opusforlife2** [comment]
Oh yeah. Sorry, that slipped my mind. There is a working 0.19.8 version in #4686. Could you test that?

**Comment by atranson** [comment]
Ah yes, [this build](https://github.com/TeamNewPipe/NewPipe/issues/4686#issuecomment-719897601) does not show the issue at all. I tried with multiple videos that produced the problem on 0.20.2 and everything seems ok on this specific version.

I guess I can stick with this version for now then :)
That being said, I'm still interested if a fix comes along for the 0.20.x versions. As I mentioned in the first post, the issue is still there in 0.20.3-RC1 so if you want me to test other builds, I'm up for it.

**Comment by opusforlife2** [comment]
Have you tried multiple resolutions? Try 144p or 240p, for example.

**Comment by atranson** [comment]
I just tried and the result is the same.
The thing is, I mostly use NewPipe for its background playback feature and that's how I discovered the issue. So I don't think the video quality would affect this.

On a side note, the issue also occurs when "faulty" videos are in a background audio playlist with videos that are working.
I just created a two tracks playlist that starts with a video which is working properly and then I appended the video mentioned above. I then locked my phone. The background playback worked ok and I could unlock my phone without problem as long as I was in the first track. As soon as I entered the second track though, the problem appeared. It was not apparent if I kept my phone locked but trying to unlock it would show the exact same behaviour I described earlier.

**Comment by opusforlife2** [comment]
Thanks for testing extensively. I'm personally out of ideas for more tests or what the issue could be, but we'll probably ask for a logcat later.

**Comment by thefaboss** [comment]
Hi,
I'm unfortunately glad to see someone else with the same problem than me...
I've got a Sony Xperia XZ2 Compact like you in Android 10 build 52.1.A.3.49.

This lock loop issue came with New Pipe 0.20 I think. And my other devices (Samsung A40 and Sony Xperia Z3T Compact) are OK).

In my case, I had no other solution to hard reboot my phone to get out this infinite loop :\
But thank's to your description, I've just disabled the NewPipe background playback option that I never use. And now, when I launch a video that locks my XZ2C, it's not infinite loop anymore ! Just a "normal" lock.

Even better, I can see now 2 notifications in the lock screen : 
- Effets du theme (in french, so in english I might say "Theme effects" ?)
- com.sonymobile.runtimeskinning.com

When I unlock the phone, these 2 notifications are gone :(
May be this informations will be usefull to debug.

**Comment by joelpierredupont** [comment]
Hi,

I have the same issue : doesn't happen with all videos
Same phone : Sony Xperia XZ2 Compact in Android 10 build 52.1.A.3.49.

Mb it would be something on the phone.

**Comment by nonremittal** [comment]
Same issue as #4638?

**Comment by thefaboss** [comment]
Not quite the same, but looks like similar.

**Comment by arielshulman** [comment]
Well, it seems the issue https://github.com/TeamNewPipe/NewPipe/issues/4638 is really alike.
I've just managed to find a temporary workaround here https://github.com/TeamNewPipe/NewPipe/issues/4638#issuecomment-727259530.
You can try the apk I've posted to validate if it's really the way to solution or if it's another reason for crash.

**Comment by ScratMan** [comment]
Same issue with an Xperia XZ2 Compact with Android 10.
Downloaded the debug version shared in the above comment, and I confirm it fixes the issue.
