### ISSUE TITLE
Missing first "related video" in chronological series

### ISSUE THREAD

**Issue by Tenchi2xh** [TeamNewPipe/NewPipe#487]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I feel like there might be an off by one in the extractor: when watching a video that is part of a series with numbered episodes, Youtube always makes sure that the next episode chronologically is the first element in the suggested videos.

However in NewPipe, the next episode not only isn't in the first position but isn't in the suggested list at all.

This might be an off by one, but it could also that the extractor doesn't parse the "Up next" box that is before the list of suggested videos on each Youtube page.

**Comment by theScrabi** [comment]
Yea that's an issue. Confirmed.

**Comment by mauriciocolli** [comment]
Here's the bug, it checks if the `nextVideo` is not null before it assigns: 
https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/stream_info/StreamInfo.java#L243

**Comment by theScrabi** [comment]
Yea I just thew it out after it did not work at the first time. That one recycler view was a small hack :/ after I switched away from ScrollView.

However I thought about putting the next video on top of the related view list, so an extra ui element is not necessary. What do you think?

**Comment by Tenchi2xh** [comment]
The video in "up next" used to be just the first element of related videos. IMHO it doesn't separate UI part

**Comment by mauriciocolli** [comment]
Hey, almost finished, that's how it looks:
![join](https://cloud.githubusercontent.com/assets/13389907/24436676/4544b0e2-1413-11e7-8ecc-b1eb0c372c5c.png)

And yes, it's just one view, I just added a separator below the first (the next) related video, and as you can see a little more spacing between the first and the others.

What do you guys think about the position of the "Next Video" title and the spacing (related videos list)?

**Comment by theScrabi** [comment]
It's good :)
