### ISSUE TITLE
Deployment of Release 0.20.2 on f-droid

### ISSUE THREAD

**Issue by nikur** [TeamNewPipe/NewPipe#4872]
I noticed that you released a new version to support the new code scheme YouTube is using. However, f-droid still hosts 0.20.1 as latest release. Could you please deploy the latest release also on f-droid?

If you are planning not to rely on f-droid anymore, could you post an instruction on how to install the latest version from an APK file without losing the search and play history?

Thank you!

**Comment by Disqu3-mirOir-qt** [comment]
use newpipe repository for get more faster not newpipe issue processus f-droid

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe#updates
