### ISSUE TITLE
F-Droid Repo not showing Verison 0.20.2

### ISSUE THREAD

**Issue by PlatypusRebellion** [TeamNewPipe/NewPipe#4876]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Update to Version 0.20.2 on F-droid.

#### Is your feature request related to a problem? Please describe it
 
Update to version 0.20.2 on F-Droid app manager.

#### How will you/everyone benefit from this feature?

It will keep from getting duplicate bug reports by having newest versions pushed out to users.

**Comment by PlatypusRebellion** [comment]
Fixed by 0.20.2 gdammit guys you're amazing.
Please push your updates to F-droid Repo for F's sake. I can't be checking every github page for all my apps apks.

**Comment by opusforlife2** [comment]
@PlatypusRebellion Use our custom repo. https://github.com/TeamNewPipe/NewPipe#updates
