### ISSUE TITLE
Enqueuing a song stops the current song. 

### ISSUE THREAD

**Issue by merrcury** [TeamNewPipe/NewPipe#4878]
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Start one video in background. 
2. Now Enqueue another video to background. 

### Actual behaviour

Video enqueued successfully. But current video stops and remain stuck on loading. Just for fact Its not a network issue. 

### Expected behaviour

Video should enqueue successfully and should not interfere with any other video and with its playback. 

### Logs

No Logs

### Device info

 - Android version/Custom ROM version: Android 7.0 / MIUI 11.0.2
 - Device model: Xiaomi Redmi Note 4 (codename: mido)

**Comment by vkay94** [comment]
Enqueuing is changed in 0.20.3 which solves your problem. I'd recommend switching to/trying 0.20.3 RC1 anyway (see pinned issue).
