### ISSUE TITLE
Increasing the volume beyond 100%.

### ISSUE THREAD

**Issue by deliciouslytyped** [TeamNewPipe/NewPipe#4879]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.
I did my best to check for duplicates or find if this is already implemented.

#### Describe the feature you want
I would like to increase the volume beyond 100%.

#### How will you/everyone benefit from this feature?

Your neighbors will throw more bricks in your window so they can hear your music better. Maybe you can build your dream house one of these days.
As an EXTRA EXTRA added bonus you will be able to listen to things that are too quiet.

**Comment by eladkarako** [comment]
meanwhile, as a workaround (until this will be implemented..)  
you may switch ON the use of external player,  
MX Player allows you up to 300%  
(note that mostly just 360p and 720p streams are with audio though),  
this is my current set-up :]

**Comment by Stypox** [comment]
This is not something that should be done by single apps. This should be doable system-wide, either by the system itself or by a specific app if the system does not support it. But it is a too niche feature to have in NewPipe, and as I said shouldn't be NewPipe-only

**Comment by aksrikanth** [comment]
I agree that this should be a system wide setting, but as that is unlikely to be added to Android, can we please leave this on the table? We don't always get to make changes that are optimal.

**Comment by MrNessuno** [comment]
> This is not something that should be done by single apps. This should be doable system-wide, either by the system itself or by a specific app if the system does not support it. But it is a too niche feature to have in NewPipe, and as I said shouldn't be NewPipe-only

After 6 years this isn't a system wide option and probably never will.
On YouTube there are low volume videos due to bad uploading or poor recording conditions that can be difficult to ear if not in a complete silent room.
Can this be re-evaluated?
Thank you

**Comment by ShareASmile** [comment]
@MrNessuno The issue is being triaged at #5735 & see PR #13762.
