### ISSUE TITLE
Socks5 Proxy

### ISSUE THREAD

**Issue by peylight** [TeamNewPipe/NewPipe#4881]
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I thint it would be nice if you add socks5 proxy. 
it seems you already drop this request in #1593, But actually shadowsocks and many VPN's work with two options:
1. The whole android applications will be through VPN.
2. Proxy mode that you can add to that application settings.

So many applications have proxy settings like Telegram...

#### Is your feature request related to a problem? Please describe it

Actually i don't want to use VPN for all my applications. I just need it for youtube.

#### Additional context

Nothing anymore...

#### How will you/everyone benefit from this feature?

I can use NewPipe application.(Actually i like it!)

**Comment by opusforlife2** [comment]
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

No item on the checklist is optional. You _must_ look for duplicates before opening your issue.

**Comment by opusforlife2** [comment]
I see you found a closed issue and commented on it. When you searched for "proxy" or "socks5" did you not come across #992?
