### ISSUE TITLE
Wrong entry for Gigaget in Licenses dialog

### ISSUE THREAD

**Issue by ypnos** [TeamNewPipe/NewPipe#4890]
### Checklist

- [x] I am using the latest version - 0.20.2
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

- Go to "About NewPipe"
- Switch to "Licenses" tab

### Actual behaviour

"Giga Get" is listed with GPLv2 license.

### Expected behavior

"Giga Get" is not listed at all as it was removed from the sources, or it is listed with GPLv3 license.
The source of GigaGet, https://github.com/PaperAirplane-Dev-Team/GigaGet states that the license is actually GPLv3.
Note that GPLv2 would be incompatible with GPLv3 and the inclusion of GPLv2 sources into NewPipe a license violation.

**Comment by TheAssassin** [comment]
> Note that GPLv2 would be incompatible with GPLv3 and the inclusion of GPLv2 sources into NewPipe a license violation.

Just to avoid confusion in the future: this remark is irrelevant to this specific dependency, as it is licensed under the GPLv3, just like NewPipe.

> The source of GigaGet, https://github.com/PaperAirplane-Dev-Team/GigaGet states that the license is actually GPLv3.

Indeed. Listing it as GPLv2 is wrong (I don't think it's a big deal, but it needs to be fixed).

> "Giga Get" is not listed at all as it was removed from the sources, or it is listed with GPLv3 license.

Are you sure it's not used any more? In that case, let's just get rid of it.

**Comment by Stypox** [comment]
No, gigaget is still used, though completely changed in many parts
