### ISSUE TITLE
F-Droid version is not updated to v0.20.2

### ISSUE THREAD

**Issue by szotsaki** [TeamNewPipe/NewPipe#4896]
Please, update the [F-Droid](https://f-droid.org/packages/org.schabi.newpipe/) release to the latest one because everyone who uses that software repository is now [unable to load](https://github.com/TeamNewPipe/NewPipeExtractor/pull/441) YouTube videos.

**Comment by Stypox** [comment]
We are aware of this. 0.20.3 will be on fdroid. 0.20.2 wasn't because of this: https://gitlab.com/fdroid/fdroidserver/-/issues/797

**Comment by szotsaki** [comment]
Thank you for your quick response and showing the background cause. Now, I'll wait for the newer version :).
