### ISSUE TITLE
Not all download selection from video and audio is shown.

### ISSUE THREAD

**Issue by abelfn** [TeamNewPipe/NewPipe#4899]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to https://www.youtube.com/channel/UCW6nm_LXhzk457g3SSNLKRw

2. After live video finished, try to download.It only shows few dowload selection from video and  audio.I had to wait long hours or another day to get all download selection.

### Actual behaviour

Only few download selection from video and audio is shown.

### Expected behavior

All  download selection from video and audio suppose to be shown

### Screenshots/Screen recordings

Video:

![video1](https://user-images.githubusercontent.com/70645835/99216958-fec23080-27e7-11eb-9a0b-c49b2216123d.jpg)

![video2](https://user-images.githubusercontent.com/70645835/99217241-ac354400-27e8-11eb-8b09-fd534983d05a.jpg)

Audio:

![audio1](https://user-images.githubusercontent.com/70645835/99217026-274a2a80-27e8-11eb-86a7-2147cadc5b8d.jpg)

![audio2](https://user-images.githubusercontent.com/70645835/99217042-316c2900-27e8-11eb-90d9-99a1d5c3de1f.jpg)

### Device info

 - Android version/Custom ROM version:8.1.0
 - Device model:SM-A260G

**Comment by Stypox** [comment]
This is how YouTube works: it takes some time to analyze the livestream and convert it into multiple formats. We can't do anything about this (though some enhancements will come of we implement DASH streaming and downloading)
