### ISSUE TITLE
Question/potential request: is there a way to open unlisted videos and playlists?

### ISSUE THREAD

**Issue by JobLeonard** [TeamNewPipe/NewPipe#490]
Hey, happy user of NewPipe here! Just a question: I have a bunch of unlisted youtube videos - either uploaded by myself, or sometimes through subscriptions on Patreon. I'd like to watch them on NewPipe but I can't figure out how to do so.

**Comment by theScrabi** [comment]
Good question, I never tried either.

However could try to share the link of one of your private videos to NewPipe. By means put it in an text editor, mark the link, tap on share, and select share to NewPipe.

Than tell us if it worked.

**Comment by mauriciocolli** [comment]
Unlisted video are just like normal videos, they just don't show up on search and related videos.
Here, do a quick test (click and open with NewPipe): https://www.youtube.com/watch?v=bX9CvhbfQgg

Private videos are not possible yet, as this requires login.

And regarding how to open, login on YouTube in some browser that let you share a link by just long pressing them (Firefox), and enable "Autoplay when open by another app" in the NewPipe's settings.
Example:
![o](https://cloud.githubusercontent.com/assets/13389907/24502561/bca3b752-1524-11e7-92ae-1ca6b2cde766.gif)

**Comment by JobLeonard** [comment]
Thanks! 

Although it would be nice if I could just paste in the link directly so I wouldn't have to go through another app to open it. Wouldn't it be possible to detect if text in the search field is a youtube link and directly open it?

**Comment by theScrabi** [comment]
Yea that was requested a couple of times already.

**Comment by JobLeonard** [comment]
Ah ok, then I can safely close this issue :)
