### ISSUE TITLE
Nightly releases on github

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#4901]
As part of creating more regular releases, i created a github action which will build the app every night and release it on github.

My current approach is that the seperate repo runs the action itself. It pulls the NewPipe repo, builds it and releases it to its own repository.
Another possibility is that the NewPipe repo executes the action and uploads the release to the other repo. Advantage here would be, that one could easily create a modified version of the action for releases on every commit to dev. But i have yet to figure it out how to create releases for a different repo, because debugging github actions is very cumbersome.

Setup required in the repo are the secrets needed for app signing https://github.com/marketplace/actions/sign-android-release. Also `CheckForNewAppVersion` may need to be adjusted to account for a new release type. Same with the api behind https://newpipe.schabi.org/api/data.json

What are your opinions about this?

https://github.com/XiangRongLin/NewPipe-nightly/blob/github_actions/.github/workflows/nightly.yml
https://github.com/XiangRongLin/NewPipe-nightly/releases (I triggered it manually for now)

Related: #3940

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/4059#issuecomment-723540550

**Comment by Stypox** [comment]
@XiangRongLin thank you for this! It's something we wanted to do for a while, but could not setup the correct config. I think this should be implemented into this repo, along maybe with a pinned issue providing always the latest apk

**Comment by XiangRongLin** [comment]
@Stypox Do you mean that the job uploads the apk somewhere and modifies the download link in the issue to point to the new apk?

**Comment by Stypox** [comment]
Yes, having hundreds of releases would clutter the releases page and make it impossible to find non-nightly releases. Would it be possible to have apks be put in an issue?

**Comment by XiangRongLin** [comment]
> 
> 
> Yes, having hundreds of releases would clutter the releases page and make it impossible to find non-nightly releases. 

Thats why there should be a seperate repository with nightly releases only

>
>
> Would it be possible to have apks be put in an issue?

With enough effort it can certainly be done. But since debugging is essentially changing something and trying it out on github, i won't make that effort to figure it out.

**Comment by Stypox** [comment]
> Thats why there should be a seperate repository with nightly releases only

Oh, ok then, let's go for this for now ;-)

**Comment by eladkarako** [comment]
That's cool, maybe you can work on embedding the ISO (yyyyMMdd) date as a supplement to the main version in some way (or at least for the archive's name),  
and I like that you are using the v3 signing scheme it allows a much faster apk installation, (you can also add v4 for android 11 which adds key rotation),  
just one note, since you use the original package name <code>org.schabi.newpipe</code> and your own generated keystore (newpipe uses this <a href="https://github.com/TeamNewPipe/NewPipe/issues/4822#user-content-open123">one</a>) it is worth to mention to people whom want to install your apks, that they first need to uninstall their old version of newpipe, otherwise it won't install (can't upgrade apps with different signatures).

**Comment by XiangRongLin** [comment]
The last few runs failed, because the default github access token doesn't have right to update workflow file. I needed to do this while updating the repo to the latest version which had in #5132 it
To fix this i created a bot account @np-bot, which has write-access to the repo and created a public access token (pat) for it with repo and workflow rights. That pat then also needs to be added to the secrets of the repo

**Comment by XiangRongLin** [comment]
closing in favor of #7534

**Comment by nicoursi** [comment]
I was wondering if it could be feasible to have a notification every time a new nighty gets realised,  just like with the official release.
