### ISSUE TITLE
Allow 1080p 30fps option for video quality

### ISSUE THREAD

**Issue by TheProgrammingDog** [TeamNewPipe/NewPipe#4902]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

An option for 1080p at 30fps in the video quality dropdown

#### Is your feature request related to a problem? Please describe it

This used to be an option on all videos with 1080p, but now I can only see it if there is no 60fps option. I've got pretty bad Internet that can just about handle 1080p but not 1080p60. One of the main reasons I started using NewPipe was because the original YouTube app didn't give a 30fps option while NewPipe did.

#### How will you/everyone benefit from this feature?

It allows people with bad Internet to watch videos in glorious 1080p!

**Comment by opusforlife2** [comment]
Wow. That's really interesting that we can have both 720p and 720p60 as options, but only 1080p60 if it exists. Never noticed that before.

**Comment by Redirion** [comment]
I checked the source. 1080p should be supported when the stream is available at this resolution. So this has probably to do with how youtube handles 60fps uploads. Maybe the 1080p@30fps gets omitted by default, so it is missing.
So from my side this issue can be closed as it can't be handled by NewPipe / NewPipeExtractor.

**Comment by Pentaphon** [comment]
That's weird. I thought 1080p was always 30fps unless you have 1080p60. Why does this not already work by default?

**Comment by Redirion** [comment]
that's exactly how it is @Pentaphon 
However it appears that if there is 1080p60 offered, usually the "regular" 1080p is missing at the available streams. This is a Youtube issue where NewPipe can't do anything in my opinion.

**Comment by Pentaphon** [comment]
> that's exactly how it is @Pentaphon
> However it appears that if there is 1080p60 offered, usually the "regular" 1080p is missing at the available streams. This is a Youtube issue where NewPipe can't do anything in my opinion.

I checked Youtube-dl and you're right. @TheProgrammingDog just needs to use 720p60 and close this issue.

**Comment by opusforlife2** [comment]
Hmmm. Maybe they decided that someone who is using 1080p naturally doesn't care about saving data, so they might as well get rid of their 30 fps, giving _them_ massive storage savings.
