### ISSUE TITLE
YouTube's policy on downloads of music subject to copyright.

### ISSUE THREAD

**Issue by flawpc** [TeamNewPipe/NewPipe#4904]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by flawpc** [comment]
I pose this question as food for serious, yes, serious, and extended thought by any and all developers.

**Comment by flawpc** [comment]
Let us get real:

     Please help discourage the massive improper downloading of music from, e.g., YouTube. All legally safeguarded interests deserve the intended respect, adhering to legal restrictions, with downloads requiring a price or permission, with so many unaware or misled by lax advice (some do not care). Much of the material is beyond the Webs quick push of a button, fast and easy norm, unfortunately, the dire situation fed by app developer buttons and a moral peak for many of buried language in end-user agreements. **Is there even any hope for a mere ethical download button reminder?**Legal advice is not the intention under any circumstance, specific or otherwise. Recording Industry Association of America (RIAA), About Piracy, https://www.riaa.com/resources-learning/about-piracy/; Laws.com, Cyber Laws, Quick and Easy Overview of Illegal Downloads, https://cyber.laws.com/internet-piracy/illegal-downloading/illegal-downloads; Quora, Is downloading YouTube music illegal?, https://www.quora.com/Is-downloading-YouTube-music-illegal; Digital Music News, YouTube to MP3 Downloaders: Are They Illegal to Use?, https://www.digitalmusicnews.com/2016/10/10/youtube-to-mp3-sites-illegal/; Cornell University, Legal Music and Video Sources, https://it.cornell.edu/security-and-policy/legal-music-and-video-sources.

**Comment by Stypox** [comment]
After we add license extraction support to the extractor, we could show a toast stating that it could be illegal to download content whose license is not Creative Commons

**Comment by flawpc** [comment]
May God bless you for whatever you can do.
