### ISSUE TITLE
Bring timeline back to background notification widget

### ISSUE THREAD

**Issue by rikishi0071** [TeamNewPipe/NewPipe#4905]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Bring timeline back to background notification widget. Since version 0.20.0, timeline in background notification widget was removed and this decision is very strange!

#### Is your feature request related to a problem? Please describe it
No. Just want to bring functionality back that always existed.

#### Additional context
This is how it looked like ALWAYS before version 0.2x.x (until NewPipe rebranding):
![ScreenshotNew](https://user-images.githubusercontent.com/18183855/99415889-560bf200-2909-11eb-831e-814be8865e95.jpg)
This is how now notification widget looks like:
![ScreenshotNewPipe](https://user-images.githubusercontent.com/18183855/99416285-c0bd2d80-2909-11eb-92c8-93071a6ae288.jpg)
This is what I want to be present in NewPipe 0.2x.x (This is VERY important feature):
![ScreenshotNewPipe1](https://user-images.githubusercontent.com/18183855/99416319-cadf2c00-2909-11eb-9016-74b418c0c3a6.jpg)

#### How will you/everyone benefit from this feature?
Everyone will be able to find out where video or music ends and the current position of play. This is EXTREMELY important using NewPipe in background!

**Comment by opusforlife2** [comment]
Mediastyle notifications only have this feature for Android 10+, sadly.

**Comment by rikishi0071** [comment]
I's strongly sure that it's not Open Source style answer. I strongly suggest one of two ways to solve that problem:

1. Rewriting notification widget to support all Android versions;
2. Rewriting notification widget and adding it to NewPipe Legacy;
3. Provide a way to use NewPipe Extractor with old NewPipe releases (before 0.20.0) since new interface is very disputed.

**Comment by opusforlife2** [comment]
@rikishi0071 Read the blog post for the 0.20.0 release. The rationale is provided there.
