### ISSUE TITLE
Provide old-style NewPipe interface (before 0.20.x) with relevant NewPipe Extractor

### ISSUE THREAD

**Issue by rikishi0071** [TeamNewPipe/NewPipe#4906]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Provide NewPipe Legacy apk's (via F-Droid) based on old-style NewPipe interface (before 0.20.0) but including a relevant NewPipe Extractor. I wonder that new NewPipe interface isn't widely disputed. A lot of people are addicted to old interface and some features like timeline in widget notification now works only in Android 10+.

#### Is your feature request related to a problem? Please describe it
Yes. Some features such as timeline in widget notification now works only with Android 10+ but earlier it worked for everyone.
https://github.com/TeamNewPipe/NewPipe/issues/4905

#### How will you/everyone benefit from this feature?
Millions of people who addicted to old interface will be able to use NewPipe as they used to.

**Comment by c-shubh** [comment]
similar to #4686 ?
