### ISSUE TITLE
Navigation bar is not visible due to lack of contrast

### ISSUE THREAD

**Issue by n00b12345** [TeamNewPipe/NewPipe#4914]
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open Newpipe
2. Navigation buttons are white and lack contrast

### Actual behaviour

The navigation bar on other apps has a proper contrast. Newpipe's navigation bar lacks contrast and appear white.

Please see this screenshot and look at the navigation bar at the bottom:

![1F9E518A-52CB-4AF0-A6BF-F87E36A16C44](https://user-images.githubusercontent.com/17707852/99550102-5925e180-29e0-11eb-88ff-35cb2c0d5d14.jpeg)

### Expected behavior

Proper contrast like so (please see the navigation bar below)

![1F32526B-6652-4950-88AB-5338455C037C](https://user-images.githubusercontent.com/17707852/99550030-457a7b00-29e0-11eb-9078-afa93d512704.jpeg)

### Screenshots/Screen recordings

Already attached.

### Logs

Probably not needed, UI issue.

### Device info

 - Android version/Custom ROM version: 10 (Oxygen OS)
 - Device model: OnePlus 7T

**Comment by Stypox** [comment]
This is a problem with the system afaik, NewPipe has no power over what colors the system chooses for the navigation bar

**Comment by n00b12345** [comment]
> This is a problem with the system afaik, NewPipe has no power over what colors the system chooses for the buttons in the navigation bar

Thank you for helping.

I have only upgraded to Newpipe from its own repository today. Previously I was using the F-Droid version. The F-Droid versions (till the latest available one) never had a problem with this light theme. It just could be something to do with the version in the repository, maybe.

I have narrowed down the issue to the Light theme. The Dark and Black themes work perfectly. Please see this screenshot.

![47E515D7-593F-4BDD-9491-C9B02490A31A](https://user-images.githubusercontent.com/17707852/99559659-0b62a680-29eb-11eb-87db-f3ace4e17e5a.jpeg)

**Comment by Stypox** [comment]
The fdroid version is exactly equal to GitHub's one

**Comment by n00b12345** [comment]
> The fdroid version is exactly equal to GitHub's one

Oh okay. I'll still to the dark theme then :)

Should I choose this issue or leave it open?
