### ISSUE TITLE
CAPTCHA loads m.youtube.com

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#4916]
### Checklist

- [x] I am using the latest version - 0.20.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Happens randomly and now it's frequent enough for me.

### Actual behaviour

CAPTCHA either opens a blank page (already an issue for). Or it opens m.youtube.com homepage. Clicking "done" reopens the popup, either blank or again with m.youtube.com

### Expected behavior

The CAPTCHA doesn't appear at all like before. Or now, when it literally appears on every single video, it would just appear, and let me solve it.

### Screenshots/Screen recordings

![Screenshot_20201118-224758_NewPipe](https://user-images.githubusercontent.com/26146502/99594332-57194e00-29f3-11eb-83e6-f0ee82ac4ada.jpg)

### Device info

 - Android version/Custom ROM version: 10/API 29
 - Device model: Samsung Galaxy A70

**Comment by Stypox** [comment]
Thank you for the report. Unfortunately we can't do anything to solve this, we only show what youtube serves. Let's keep only #3714 open.
