### ISSUE TITLE
Alarm Clock feature ?? :)

### ISSUE THREAD

**Issue by jdsys271** [TeamNewPipe/NewPipe#4917]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I think it would be REALLY amazing...if you could add an "Alarm Clock" feature that will play a specified "Video" or the option to play the playlist (in Audio only obviously) at a specified time in the order the playlist was fixed prior.
Together with this, i was going to suggest a Sleep Timer as well, but it seems that has already been requested, however still being implemented?

Alarm Clock:
For example, i have a playlist or a specific "Video" i want to hear waking up, and all i do is push the "Set for Alarm" button to activate either the specified playlist or single "Video" to wake me up at a certain date/time. (if the internet gets disconnected for some reason before the audio starts, it should skip all songs until it finds a song that has been cached already and will play that. Else it will fail to play anything.)

#### Is your feature request related to a problem? Please describe it

Yes. The problem is that i cant wake up in the morning anymore to a dull alarm ding on my phone lol.

#### How will you/everyone benefit from this feature?

This feature will help people wake their ass up in the morning with the playlist/Audio they have pre-selected to play which will motivate them, and in turn creates a better, less-grumpier world?
Have you ever woken up to your favorite track that made you so energetic like you wanted to rule the world? i have!
Granted i doubt anyone would need a whole playlist to wake up. But the option should be there in addition to the **Primary** option of having any single "Video" play as Audio at a specific time.
Another example, a user could want to wake up to their daily news from a channel that starts at 8am (like a radio used to wake us up back in the day!)

#### Additional context

I did search about this, and didnt find anything.
I love NewPipe, im just trying to throw some cool ideas out there. and i also love the NewPipe team forever and ever and ever ever.. ever ever. Thank you.

**Comment by huckvrni** [comment]
I think that is somwhat out of context for this application, IMO implementing all the features in one application just makes it bloated and unusable.
My suggestion then would be that you use tasker or a similar program to start playing music in a specified time using the media api.
On that note, a better approach would be to implemente a broadcast receiver for better interaction with 3rd party apps, or better yet a plugin support system, although again you reach behind the scope of the application original purpose.

**Comment by opusforlife2** [comment]
A _much_ easier solution is to just download the (Creative Commons licensed!) songs that you want and play them with an alarm app which has such a feature.
