### ISSUE TITLE
Some videos are not being listed

### ISSUE THREAD

**Issue by BruceMustache** [TeamNewPipe/NewPipe#4919]
### Checklist

- [x] I am using the latest version - 0.20.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to channel [Gabriel pato](https://www.youtube.com/channel/UC70YG2WHVxlOJRng4v-CIFQ) in the browser and see his [last video](https://m.youtube.com/watch?v=G4EpA6ZHKw8) labeled "Hacker analisa as Invasões de Watch Dogs"
2. Go to the [channel](https://www.youtube.com/channel/UC70YG2WHVxlOJRng4v-CIFQ) using newpipe and you can't see that video
3. Open this [video link](https://m.youtube.com/watch?v=G4EpA6ZHKw8) with newpipe and you'll see a error

### Actual behaviour

Some videos isn't being listed by newpipe

### Logs

No logs are shown
Just say "content unavailable"

**Comment by kubo6472** [comment]
Make sure to turn "allow adult content" to on. And "restricted mode" to off.

**Comment by BruceMustache** [comment]
I had check age restriction button
Sorry for that mistake
The  videos are showing correctly now
