### ISSUE TITLE
Downloading multiple Videos more effectively

### ISSUE THREAD

**Issue by oiiiiiiii** [TeamNewPipe/NewPipe#4922]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Currently, when you want to download many videos it downloads one video, the others get queued. Once the first video finished downloading the post processing starts. However, the next video doesn't start downloading, which it could. It only starts, once the post processing finished. This way, a lot of time is spent downloading nothing, which I think could be avoided by starting the next download when the postprocessing of the first video starts.

#### Is your feature request related to a problem? Please describe it

I think it is unnecessary to wait with the download for the next, queued video until postprocessing the first is completed. I think it could start once the download of the first video ended.

#### How will you/everyone benefit from this feature?

It will save time.

**Comment by opusforlife2** [comment]
"Limit download queue" in Download settings.

**Comment by mehedihasanziku** [comment]
> "Limit download queue" in Download settings.

Well this option is available, can you make an option/slider, so we can limit 2/4/6/custom, right now limit to 1.

Please make an possible option for us.

Thanks.

**Comment by opusforlife2** [comment]
Please don't make new feature requests in closed issues, @mehedihasanziku. Search for your issue among the current ones, and open a new issue if you don't find it.
