### ISSUE TITLE
Please put the latest version on f droid

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#4923]
I would like to update your version on f droid as it is still 0.20.1. It somewhat had issues which were later fixed so I would like for you to update your vereion on f droid. Thank you

**Comment by Thewisem** [comment]
And It would be awesome to see the small window which can be used for watching video outside the app. Would really love that option to come back in latest version

**Comment by Stypox** [comment]
It will be on Fdroid

**Comment by mrmotallebi** [comment]
Still waiting... :'(

**Comment by Thewisem** [comment]
It is going too long. How longshould I wait

**Comment by MichaelSp** [comment]
⏳
