### ISSUE TITLE
Volume gesture not working everywhere in fullscreen

### ISSUE THREAD

**Issue by SuNNjek** [TeamNewPipe/NewPipe#4926]
### Checklist

- [x] I am using the latest version - 0.20.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Change video player settings to only have volume gesture enabled (i.e. disable the brightness gesture)
2. Open any video in fullscreen mode
3. Try and change the volume by moving finger up and down on the left side on the screen

### Actual behaviour

Nothing happens. If you instead try the same gesture on the right side of the screen, it works as expected.

### Expected behavior

The volume gesture should work across the entire screen. This used to work on previous verisions, but doesn't anymore.

### Screenshots/Screen recordings

Sorry for the low resolution, I tried to get a small gif (since GitHub doesn't support any video formats). I think you can still clearly see the problem though.

![screen-20201119-183505](https://user-images.githubusercontent.com/20151081/99703154-0f4c0280-2a97-11eb-80d7-4a99df111614.gif)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Google Pixel 3a

**Comment by SuNNjek** [comment]
Did a quick bisect, apparently the commit that introduced the bug is 268304376226457e99aea640aedfa3ccc22c59bb

**Comment by vkay94** [comment]
Oh, I didn't pay attention to this setting (I did the change). I'm aware of this option but thought I just disables the gesture on the side. I'll create a fix in a while which respects the setting. @opusforlife2 You can assign me to this issue if you'd like.
