### ISSUE TITLE
Endless buffering on duplicate videos in queue

### ISSUE THREAD

**Issue by RickyM7** [TeamNewPipe/NewPipe#4940]
### Checklist
- [x] I am using the latest version - 0.21.1 (But this bug happens at least since the v0.20.4)
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a video in background that is duplicated in a playlist (the duplicate has to come right after the video) and the bug will occur when the duplicate plays.

### Actual behaviour
The video basically gets on an endless buffering and never starts playing or moves on to the next playlist video (unless you do it manually).

### Expected behavior
The video, whether duplicate or not should play normally.

### Device info

 - Android version/Custom ROM version: MIUI 11 (Android 7.0)
 - Device model: Redmi Note 4

**Comment by sqtvrnqliq** [comment]
Can confirm this issue is still prevalent in the newer releases

**Comment by RickyM7** [comment]
@sqtvrnqliq I tested all the apks in actions and none shows the videos in the list, so there is no way to see if it was fixed. Btw, I think you opened a duplicate of this issue with the #5225

**Comment by jowiejow** [comment]
I have the same issue

**Comment by RickyM7** [comment]
@Stypox I'm sorry to be asking, but do you have any idea when this bug will be fixed?
Even though this bug is not something very urgent, it still gets in the way of some occasions and this makes it very frustrating.

**Comment by ekiniko12** [comment]
Seems like we still have this issue on 0.21.6. Are we going to get any fixes?

**Comment by Stypox** [comment]
@ekiniko12 @RickyM7 @sqtvrnqliq could you check if #6712 solves the issue?

**Comment by RickyM7** [comment]
> @ekiniko12 @RickyM7 @sqtvrnqliq could you check if #6712 solves the issue?

I just tested it and the bug was fixed, thank you very much!

- Device: Redmi Note 4 (ArrowOS v11 - Android 11)
