### ISSUE TITLE
Please add an option to disable "immersive mode" in ExoPlayer

### ISSUE THREAD

**Issue by Rinzler005** [TeamNewPipe/NewPipe#495]
Hi, 
I am getting playback issues on Andoid 4.4.2 KitKat... when starting a video the ExoPlayer starts in immersive mode  causing the playback buttons to disappear completely.....the navigation bar also disappears in immersive mode. The Popup Player of ExoPlayer works perfectly. The Mediaframework
player is also workly correctly without any issues. Only ExoPlayer is having problems.

**Comment by mauriciocolli** [comment]
In short, are you saying that when you start a video, the controls are immediately hidden?
If it is, I'll soon create a pull request that, among other things, change this behavior (I think is bad too).

**Comment by Rinzler005** [comment]
Lastest Update has fixed the issue. Thank You TeamNewPipe for this amazing app!
