### ISSUE TITLE
YouTube import not possible - subscription_manager redirects to feed/channels

### ISSUE THREAD

**Issue by MightyPork** [TeamNewPipe/NewPipe#4953]
Hi, I was trying to import YouTube subscriptions, but the URL `https://www.youtube.com/subscription_manager?action_takeout=1` now just redirects to the new subscription list (`https://www.youtube.com/feed/channels`) that does not have the export buttons anymore. 

The same results are in desktop mode and in a desktop browser, both firefox and chrome. 

I wonder if google deliberately broke it to make NewPipe harder to use... The link definitely worked about two weeks ago.

this is the bottom of the new list, no export button:
![Screenshot_20201121_125051](https://user-images.githubusercontent.com/2041118/99876706-b1cfc700-2bf8-11eb-8a6c-a7ec7291ca1b.png)

Any idea how to get the OPML now?

**Comment by vkay94** [comment]
It seems that you're using an outdated version. This import-way was removed by YouTube some time ago. There is a new way by importing from `https://takeout.google.com`. All steps are explained in 0.20.3.

**Comment by MightyPork** [comment]
Strange, I literally just an hour ago installed it from FDroid

**Comment by vkay94** [comment]
Yeah, FDroid is outdated most of the time. I'm not involved so I can't tell you why there is a delay. I recommend to use the versions on Github anyway you find [here](https://github.com/TeamNewPipe/NewPipe/releases). The versions are equal. You'll get notifications for updates, too ;)

**Comment by MightyPork** [comment]
Thanks, it worked. Extracting zip on android was not the easiest thing in the world, but I got it.

**Comment by salfter** [comment]
I only found this after having knocked together a bit of Python to mangle YouTube's takeout file into NewPipe's import/export JSON.  If for some reason you can't upgrade NewPipe to 0.20.3 or newer, maybe this will be useful:

```
#!/usr/bin/env python

import json

with open("subscriptions.json") as json_file: # as exported by YouTube
    data=json.load(json_file)

c=0
subscriptions=[]
for sub in data:
    subscriptions.append({})
    subscriptions[c]["service_id"]=0
    subscriptions[c]["url"]="https://www.youtube.com/channel/"+sub["snippet"]["resourceId"]["channelId"]
    subscriptions[c]["name"]=sub["snippet"]["title"]
    c=c+1

export={}
export["app_version"]="0.20.1"
export["app_version_int"]=955
export["subscriptions"]=subscriptions

with open("newpipe_subs.json",mode="w") as export_file:
    json.dump(export, export_file)
```
