### ISSUE TITLE
the status bar should be black themed in video page.

### ISSUE THREAD

**Issue by unknowndelicateboy** [TeamNewPipe/NewPipe#4956]
https://user-images.githubusercontent.com/36302515/99888845-cd6eb800-2c60-11eb-8fe4-bab03857480b.jpg

**Comment by c-shubh** [comment]
@unknowndelicateboy, read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and follow the template
