### ISSUE TITLE
DesugarGregorianCalendar crash? Huh?

### ISSUE THREAD

**Issue by AnotherLife** [TeamNewPipe/NewPipe#4957]
Latest stable on an old tablet running Android 4.4

When switching BACK to the app it crashes

{"user_action":"ui error","request":"App crash, UI failure","content_language":"en","content_country":"GB","app_language":"en_US","service":"none","package":"org.schabi.newpipe","version":"0.20.3","os":"Linux Android 4.4.4 - 19","time":"2020-11-21 22:28","exceptions":["java.lang.NullPointerException\n\tat j$.util.DesugarGregorianCalendar.from(:1)\n\tat org.schabi.newpipe.extractor.localization.DateWrapper.date(DateWrapper.java:51)\n\tat org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.getFormattedRelativeUploadDate(StreamInfoItemHolder.java:98)\n\tat org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.getStreamInfoDetailLine(StreamInfoItemHolder.java:83)\n\tat org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.updateFromItem(StreamInfoItemHolder.java:65)\n\tat org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)\n\tat org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:360)\n\tat androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)\n\tat androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)\n\tat androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)\n\tat androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)\n\tat androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)\n\tat androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)\n\tat androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)\n\tat androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:388)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)\n\tat android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1660)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1436)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:388)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:388)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)\n\tat com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:380)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:388)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1434)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:388)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1434)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:388)\n\tat android.view.View.layout(View.java:14834)\n\tat android.view.ViewGroup.layout(ViewGroup.java:4631)\n\tat android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:574)\n\tat android.view.Choreographer.doFrame(Choreographer.java:544)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)\n\tat android.os.Handler.handleCallback(Handler.java:733)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:136)\n\tat android.app.ActivityThread.main(ActivityThread.java:5133)\n\tat java.lang.reflect.Method.invokeNative(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:515)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)\n\tat dalvik.system.NativeStart.main(Native Method)\n"],"user_comment":""}

**Comment by ShareASmile** [comment]
@Isira-Seneviratne maybe related to
https://github.com/TeamNewPipe/NewPipeExtractor/pull/417

**Comment by Isira-Seneviratne** [comment]
I fixed the issue here: https://github.com/TeamNewPipe/NewPipe/pull/4921
