### ISSUE TITLE
Failed to play this video

### ISSUE THREAD

**Issue by tgp1994** [TeamNewPipe/NewPipe#496]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When trying to play certain YouTube videos, the player closes back out and shows a notification reading "Failed to play this video" (no reason why specified). A couple of examples:

https://youtu.be/Ft_xchynHuk
https://www.youtube.com/watch?v=EtFVHg03QxM&feature=youtu.be&t=1m5s

**Comment by theScrabi** [comment]
Hm for me it worked. Have you tried to play it with he most recent version?

**Comment by tgp1994** [comment]
Sorry, I forgot to mention: I was using 0.9.0 at the time of the errors, but I see you just released 0.9.1 - I'll give it a try once F-Droid sends it out.

**Comment by theScrabi** [comment]
Yea no, 0.9.1 wount fix that.

**Comment by tgp1994** [comment]
Well, shoot... The links are working for me too now. In the future, do you know how I can collect debugging information?

**Comment by theScrabi** [comment]
Well normaly newpipe will collect and send a crashreport if something failes, so the user will be promptet to send that report.

However it seems like the player has not yet been hocked up to the crashreport function.

**Comment by tgp1994** [comment]
Understood. Should we chalk this up to maybe a couple of network errors on my part and call it closed?

**Comment by theScrabi** [comment]
Hm well I gues so.
However next time it does not work you could provide a log :)

**Comment by tgp1994** [comment]
That's actually what I meant, how do I provide a log next time so I can be more help?

**Comment by theScrabi** [comment]
Hm yea xD. Well the next time you can try to figure out what happens using logcat.
