### ISSUE TITLE
Android 4.4.4 : no video in the app or in fullscreen ; floating player okay, sound okay

### ISSUE THREAD

**Issue by breversa** [TeamNewPipe/NewPipe#4963]
### Checklist

- [x] I am using the latest version - 0.20.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Install NewPipe 0.20.3
2. Start any video

### Actual behaviour
3. No video is displayed in the app. Sound is fine though. On-picture controls (pause, skip in timeline) are fine too.
4. Switch to fullscreen : still no video
5. Switch to floating player : video is here !

### Expected behavior
Video is displayed in the app and in fullscreen.

### Screenshots/Screen recording
Imagine a black screen :-)

### Logs
No crash, no log

### Device info

 - Android version/Custom ROM version: Android 4.4.4 / CyanogenMod 11
 - Device model: Acer Iconia Tab A210

Yep, I know this is ancient hardware. I haven't found any ROM more recent (AFAIK it's because Tegra support has been dropped starting with Android 5), but I'd love to use this old tablet as a video player, as it's got a rather big screen and pretty powerful speakers. :-)

**Comment by opusforlife2** [comment]
> Yep, I know this is ancient hardware.

No, NewPipe is supposed to work properly on Kitkat. The bigger concern here is that your build of CM 11 might have a bug. It was only a few years ago that the LineageOS team came up with their device charter, ensuring that everything works on devices with official ROMs. So an old build like yours might have been harbouring a bug that just silently stayed there until we updated some library or the other.

This is all speculation, though. It might be an easily fixable bug.

**Comment by breversa** [comment]
Thanks for your reply. I've tried looking at the logcat but could find anything remarkable so far.

By the way, changing the video format yields worse results, where the videos generally won't appear at all.
Audio still play fine.

**Comment by breversa** [comment]
Hello @litetex !
I gave it another try with the current version of NewPipe Legacy, and video now works properly ! :)

The device should indeed support exoplayer, at least for video playback.

Thanks for your help !
