### ISSUE TITLE
Playlist Download and playback

### ISSUE THREAD

**Issue by mayank1470** [TeamNewPipe/NewPipe#4964]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think one good feature to have would be ability to download/play all videos in a playlist. 

#### Is your feature request related to a problem? Please describe it

I wanted to download a playlist consisting around 68 videos. A button was missing to download the whole playlist. 

#### How will you/everyone benefit from this feature?

This will add a new and important functionality that should be there in a streaming app. I am a rookie developer myself and would love to contribute to enable this feature.

**Comment by mayank1470** [comment]
Not sure what was ignored :)

**Comment by opusforlife2** [comment]
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

This one.

**Comment by opusforlife2** [comment]
Ignore my edits on the top comment. That's my touchpad being stupid.

**Comment by mayank1470** [comment]
I checked and did not find something similar lol

**Comment by opusforlife2** [comment]
Issue - #2380.
PR - #2018.

However, that PR is quite old, and the dev also mentioned a lack of time to work on it.
