### ISSUE TITLE
show on screen display overlay for a longer period of time

### ISSUE THREAD

**Issue by AndySchroder** [TeamNewPipe/NewPipe#4966]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
When playing in full screen, one can tap to bring up an overlay of the seek bar, video title, playback speed controls, etc.. Taping will bring this overlay up for about a second. Would prefer a longer default time that the overlay stays up before going away. It is way to short to read the video title in most cases, even harder to read the video title AND also see where you are at in time in the playback of the video. In addition to having a longer default display time, I would prefer the time to be customizable. Would be even better if it was smart enough to count the characters in the title of the video and make it longer if the title is longer. Would also like to see the ability to keep the title and seek bar (nothing else) up continuously as an option.

**Comment by opusforlife2** [comment]
Pause the video. The overlay stays _forever_. :O
