### ISSUE TITLE
Importing Youtube Subscriptions doesn't work

### ISSUE THREAD

**Issue by SerjSX** [TeamNewPipe/NewPipe#4968]
### Checklist

- [x] I am using the latest version - 0.20.1 (the latest on F-Droid, not my fault if there are newer in other places) 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.(i did check, i hope i didnt skip any) 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to the second tab that has 'Subscriptions'.
2. Press on Youtube under 'Import From'.
3. Go to the URL, and you'll see it sends to channel list.

### Actual behaviour
After clicking on the link it sends to Channel list that your account has instead of downloading the file.

### Expected behavior
I hope this is fixable, if it's from Youtube's end then that's unfortunate.

### Screenshots/Screen recordings

No screenshots, everything is obvious.

### Logs

No logs.

### Device info

 - Android version/Custom ROM version: LineageOS 14.1 | Android 7.1.2
 - Device model: GT-P5210 | Galaxy Tab 3 10.1

**Comment by Rult** [comment]
> I am using the latest version - 0.20.1 (the latest on F-Droid, not my fault if there are newer in other places) 

As it's mentioned on NewPipe website, you can add NewPipe repository to your F-Droid client to get new versions faster (but you need to backup database and uninstall the app first).
https://archive.newpipe.net/fdroid/repo/?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501

**Comment by TobiGr** [comment]
This was fixed in either 0.20.2 or 0.20.3 (don't remember). As @Rult mentioned, you can [add and use our own F-Droid repository](https://newpipe.schabi.org/FAQ/tutorials/install-add-fdroid-repo/) to get updates.
