### ISSUE TITLE
[MAJOR] No video for WebM 360p format

### ISSUE THREAD

**Issue by sebma** [TeamNewPipe/NewPipe#497]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hi,

I have just updated your great application upto 0.9.0 today and launched it to play a video on YouTube using the WebM 360p format and it appears that only the audio works.

Can you please fix this issue ?

**Comment by mauriciocolli** [comment]
Here's working fine, could you give more details (like what video are you trying to watch, which player...)?

**Comment by sebma** [comment]
I didn't change the default player so I guess It should be ExoPlayer.
My phone has Android 4.2.2

**Comment by sebma** [comment]
I forget to precise the screen is black when playing any YouTube video using the default format for 360p (seems it defaults to WebM). but MPEG-4 360p works.

In the meantime, it is possible to setup the application to default to MPEG-4 360p format instead ?

**Comment by sebma** [comment]
I can have an adb shell and root access to my phone so if I can help debugging this issue, please tell me what to do.

**Comment by mauriciocolli** [comment]
There's another issue open with this request #463.

Can you say the model of your device? Seems to be a incompatibility with Exoplayer specific for your phone.

**Comment by sebma** [comment]
Samsung GT-I9105P (Samsung Galaxy S2 Plus)

**Comment by mauriciocolli** [comment]
Could you test the [`ExoPlayer demo`](https://github.com/google/ExoPlayer) to see if the problem still occurs there? [Here](https://google.github.io/ExoPlayer/demo-application.html)'s how to build it (If you can't build it, I can send you)

In the demo app you'll see various formats, choose the `webm` and give it a try (of course, you can test the others to make sure that it's working).

**Comment by sebma** [comment]
I tried building apps from my Ubuntu for android but without success, I'd prefer the apk if you don't mind.

**Comment by sebma** [comment]
for android >= 4.2

**Comment by mauriciocolli** [comment]
As Github don't support upload of apks, I will zip the file [demo-noExtensions-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/907459/demo-noExtensions-debug.apk.zip)

**Comment by sebma** [comment]
ok, I just installed it.

**Comment by sebma** [comment]
MP4,H264 works but for WebM,VP9 only the audio plays

**Comment by mauriciocolli** [comment]
So yeah, there's nothing we can do (as it is a device incompatibility), and I'll implement the preferred format soon, so I think you can close this issue.

**Comment by sebma** [comment]
Yes, the only workaround is [request #463](https://github.com/TeamNewPipe/NewPipe/issues/463).

**Comment by sebma** [comment]
Thanks a lot for your help.

**Comment by sebma** [comment]
The videos I first tested with ExoPlayer are WebM/VP8 actually.
VLC plays them without any problem.

**Comment by theScrabi** [comment]
All right I added a preferred preference, so you can choose your favorite format.

**Comment by sebma** [comment]
Thanks a lot :)
