### ISSUE TITLE
Can't import subscriptions

### ISSUE THREAD

**Issue by DarkenLX** [TeamNewPipe/NewPipe#4973]
### Checklist

- [X] I am using the latest version - 0.20.4 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

##Pre note
This is not an app bug its more a website/instructions etc from what i can tell it's looks like something has changed with YouTube / Google site layout, data and whatnot. Also the only way ive found to get the subscription information which seems to be tied into the "Google Account Data" now which is to download a copy of your account data [This info here](https://support.google.com/accounts/answer/3024190?hl=en) 
Which is a zip file but it's not and doesn't currently contain the currently correct file that newpipe wants. It does contain the information it should need though.

### Steps to reproduce the bug
Click on the youtube subscriptions link on the new pipe website to obtain the "check-out" data (yes im logged in)
And attempt to follow the import instructions.. which seems to be very incorrect now.

### Actual behaviour
Youtube redirects the link to a "Subscriptions Manager" page which 1. Is not what import instructions state. 
2. Does not have a place to download the required file or files for import (unless its hidden somewhere) (please see pre note tag above)

### Expected behavior
What is stated in the import instructions on the website. Which is a fille is supposed to be downloaded for import via the app

### Device info

 - Android version/Custom ROM version: Android 9.0 PIE
 - Device model: LG ThinQ V40

**Comment by DarkenLX** [comment]
The template was ignored because most of it doesn't apply to this specific issue it's not the app itself it's the data that google provides the youtube subscriptions in the app no longer imports it

**Comment by DarkenLX** [comment]
Should i just leave things blank then?

**Comment by opusforlife2** [comment]
> I am using the latest version - x.xx.x 

This is a "canary in a coal mine" test. If you didn't fill this in, it means you didn't read the template properly. End of story.

Anyway, your issue is a duplicate. Subscription from Youtube has been fixed (indeed using Google Takeout, which is another indication that you didn't check for duplicates) in 0.20.3.
