### ISSUE TITLE
please integrate an option to add podcasts by there RSS links

### ISSUE THREAD

**Issue by michael9602** [TeamNewPipe/NewPipe#4974]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
it will be very convenient if you add an option to add podcasts by bye there feed URL

**Comment by opusforlife2** [comment]
The checklist isn't optional. Please follow it and edit your issue afterwards.
