### ISSUE TITLE
Cut silent moments

### ISSUE THREAD

**Issue by bphd** [TeamNewPipe/NewPipe#4977]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it

Did you make yourself the function to cut silent moments in video or you took it from elsewhere? I'd like to cut automatically silent moment in my personal videos (not on YouTube so)

**Comment by Redirion** [comment]
that's a feature of ExoPlayer. See here: https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/SilenceSkippingAudioProcessor.java

**Comment by bphd** [comment]
Neat
