### ISSUE TITLE
Time is not resetted when another video in play queue is chosen

### ISSUE THREAD

**Issue by HenriDellal** [TeamNewPipe/NewPipe#4983]
### Checklist

- [x] I am using the latest version - 0.20.4
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Add multiple videos in play queue
2. Open play queue
3. While one of the videos is playing, choose another video

### Actual behaviour

Time is not resetted. E.g. if the video is at 2:30, another video chosen starts at the same time mark, not at 0:00

### Expected behavior

Time resets and video plays from the start

### Device info

 - Android version/Custom ROM version: 9.0
 - Device model: Samsung Galaxy A10

**Comment by Feuerswut** [comment]
I cant reproduce. Close issue?
