### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by EBiForE** [TeamNewPipe/NewPipe#4990]
NewPipe from F-Droid is not updated

**Comment by TobiGr** [comment]
Unfortunately, we cannot do anything about that. We update the metadata in F-Droid's GitLab repo, the app is built, but not signed correctly.

**Comment by tuxayo** [comment]
Here we can follow the fix of the root cause: https://gitlab.com/fdroid/fdroidserver/-/issues/797
