### ISSUE TITLE
Multiple kinds of feed

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#4991]
Who remembers the pre-v0.19.0 What's New feed? I want to have it back, so I was thinking in either Content or Appearance settings, you could have an option named "Feed type" where it pulls up a popup menu, and you can click on A-Z (that would be the old one,) Grouped - latest releases (the current one) Grouped - unwatched (pretty self-explanatory)
and A-Z - unwatched. I would like this feature because the new feeds take a while to load/refresh, whereas with the old method, it was, indeed, very fast.

**Comment by mhmdanas** [comment]
Please don't open issues without the template. You can open a new issue with the template using https://github.com/TeamNewPipe/NewPipe/issues/new/choose.
