### ISSUE TITLE
Opens and crash

### ISSUE THREAD

**Issue by AltTabris** [TeamNewPipe/NewPipe#4992]
v20.4 first time happening that even rebooting phone then launching newpipe would keep crashing and restarting. Also, rebooting show a message system process not responding and I think that was newpipe. But it wasnt like it happened as soon as it was installed. V20.4 was working normally but i think the order of events was: 1.having newpipe in middle of watching video. 2. Open a new app like Chrome and newpipe is not playing video but a minimized app. 3. Tap link to youtube video in Chrome to launch new video in newpipe. 4. Watch a little but then use back button arrow on phone till you return to original video.... Then that was when it went foobar. Happened on old phone android 6.0

**Comment by richq** [comment]
Yeah, before #4921 NewPipe would crash showing the error dialog when it was removed from RAM and then you return to it, now it doesn't crash but the behaviour is arguably worse. NewPipe closes itself and restarts over and over until I hit the home button and restart the app again from scratch.

**Comment by Younes-L** [comment]
Experienced the same thing but didn't know how to reproduce it. Newpipe was in background mode and paused, and then I watched a video on YouTube and the newpipe background notification either disappeared or became dismissable (normally newpipe notification isn't dismissable)
Then when I opened newpipe again from launcher it went crazy opening and closing itself over and over again until I hit the home button, after which everything was normal and newpipe opened correctly.
(android pie , pixel 2  fwiw)

**Comment by mhmdanas** [comment]
@AltTabris please use the bug report template from [here](https://github.com/TeamNewPipe/NewPipe/issues/new/choose).
