### ISSUE TITLE
Importing subscriptions via XML is no longer supported, need ability to import JSON from Google Takeout

### ISSUE THREAD

**Issue by profucius** [TeamNewPipe/NewPipe#4997]
Google changed their Youtube website to no longer allow exporting subscriptions using the old method. The only way to export subscriptions now is to use Google Takeout and export them as a .JSON file. It is not possible to download this as XML any longer.

Please update NewPipe to import using the new JSON format.

**Comment by mhmdanas** [comment]
This issue was fixed in 0.20.3.

Also, please don't remove the template. If you hadn't removed it and followed all of its instructions properly, you would've found that there already exists an issue for this (#4720), and that it was already fixed.

**Comment by profucius** [comment]
I apologize for not finding that previous issue, I did a search but didn't find it previously. However, the latest NewPipe v20.4 still does not import the JSON file. I read the issue you linked above, and it does not mention that the issue is "fixed" but mentions a "workaround" using some scripting. I am unable to use scripting at this time, so I am asking for a proper fix to the importing of the existing JSON format.

**Comment by mhmdanas** [comment]
> I was using the latest from F-Droid, which does not include the JSON importing fix.
I never knew about this. I'll ask about it.

**Comment by profucius** [comment]
When I uninstall Newpipe and then look at the Newpipe app page inside F-Droid, the changelog shows as 20.1 being the latest version. It appears the JSON importing issue was resolved in debug 20.2. That would explain the mismatch.

**Comment by mhmdanas** [comment]
Ah, the latest version on the F-Droid repo is not 0.20.4, which is what confused me. The fix was published along with 0.20.3.
