### ISSUE TITLE
Double press back button to exit or showing a dialog prompt to exit

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#5001]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
1. I think it would be nice if you add double back button to exit (User: press back button once - Action: show toast message "Press back button again to exit" for few seconds - User: press back button again - Action: exit the app )
2. Or showing a dialog box, prompting the user to exit
3.  Option to show toast message (feature 1) or dialog box (feature 2) as per user preference which is customizable in settings.  

#### Is your feature request related to a problem? Please describe it

When on home screen of the app, pressing the back button directly exits the app.
Most of the time, I just want to swipe between different pages, and accidental swipe from the edge of the screen causes the back button press (function of android 10 gesture) and directly exits the app without any prompt.

#### How will you/everyone benefit from this feature?

It prevents accidental shutdown of the app and is useful for people who spams back button to reach home page of the app, like me, after reaching several layers deep into the app.

**Comment by mhmdanas** [comment]
The checklist isn't optional. Please follow it and edit your issue afterwards.

**Comment by skyGtm** [comment]
@mhmdanas I have edited my issue. Please consider it. Thankyou

**Comment by mhmdanas** [comment]
@skyGtm you opened another issue (#5003) about this which is open right now.
