### ISSUE TITLE
Learning playlist "views" mislabeled as "videos"

### ISSUE THREAD

**Issue by SovietScout** [TeamNewPipe/NewPipe#5004]
### Checklist

- [x] I am using the latest version - 0.20.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open this playlist: https://www.youtube.com/playlist?list=PLjEaoINr3zgEL9UjPTLWQhLFAK7wVaRMR

### Actual behaviour

The playlist "info bar" shows that it has 291,955 videos.

### Expected behavior

The playlist "info bar" should be showing that it has 291,955 views (or 10 videos).

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/51880998/100190390-27e36f00-2f14-11eb-9361-d07a40b1a3fd.png)

### Logs

N/A

### Device info

 - Android version/Custom ROM version: Android 9/EMUI 9.1
 - Device model: Honor Play

### Additional Notes
This seems to be only happening with "learning playlists".
The comma placement has nothing wrong with it, it is just following the Indian Numbering System.

**Comment by litetex** [comment]
Looks like YouTube somehow doesn't transmit the video count:

[![grafik](https://user-images.githubusercontent.com/40789489/127707015-07ed1c9c-7eef-4ee3-bc88-46feb440b173.png)](https://www.youtube.com/playlist?list=PLFs4vir_WsTzcfD7ZE8uO3yX-GCKUk9xZ)
vs
[![grafik](https://user-images.githubusercontent.com/40789489/127706968-cf918ff6-c0df-4159-8cbc-7c81fad7a045.png)](https://www.youtube.com/playlist?list=PLjEaoINr3zgEL9UjPTLWQhLFAK7wVaRMR)

This causes the extractor to fail: It selects the view count instead.

However it works in the mobile version:
[![grafik](https://user-images.githubusercontent.com/40789489/127707160-dc180f99-01bb-40f8-9d03-d6e50e918ddd.png)](https://m.youtube.com/playlist?list=PLjEaoINr3zgEL9UjPTLWQhLFAK7wVaRMR)

**Comment by yashpalgoyal1304** [comment]
wowwww, awesome. i had no hope that this issue would have been filed.

* Reproduced on: Newpipe **v0.21.16** on Android 11 based realme UI v2.0
* With: [Think Like A Coder](https://www.youtube.com/playlist?list=PLJicmE8fK0EgogMqDYMgcADT1j5b911or) LearningPlaylist
* Related: https://github.com/TeamNewPipe/NewPipe/issues/7609
* Found with 🔍 : [playlist video number](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aopen+playlist+video+number)

**Comment by yashpalgoyal1304** [comment]
@litetex cant the playlist's classic mode be inspected to see if the playlist number is exposed there?? if it is, then maybe the element can be searched in the current mode of yt desktop as well.

i dont remember what the link is to force the classic mode, so, couldnt test this idea further
