### ISSUE TITLE
Stream is not smooth

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5008]
I would like for you to smoothen the streaming service. Newpipe streaming is not live. It will always be behind the original stream. When red line is dragged to live, it jerks and goes back. You could fix the red indication animations on streams.But main problem, it stops after some interval of time.(No my wifi isnt the problem, I had seen streams before). It would be fantastic if you could smoothen the streaming service.

**Comment by mhmdanas** [comment]
Please don't remove the template. You can fill it from [here](https://github.com/TeamNewPipe/NewPipe/issues/new/choose).

**Comment by Thewisem** [comment]
Wha?

**Comment by mhmdanas** [comment]
When you were writing the issue, there was a template pre-filled for you. You removed the template. Am I wrong?

**Comment by mhmdanas** [comment]
In general, we close all issues that don't use a template or don't follow its instructions properly.
