### ISSUE TITLE
Multiple kinds of feed (with the template this time)

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5009]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Who remembers the pre-v0.19.0 What's New feed? I want to have it back, so I was thinking in either Content or Appearance settings, you could have an option named "Feed type" where it pulls up a popup menu, and you can click on A-Z (that would be the old one,) Grouped - latest releases (the current one) Grouped - unwatched (pretty self-explanatory)
and A-Z - unwatched. I would like this feature because the new feeds take a while to load/refresh, whereas with the old method, it was, indeed, very fast.

#### Is your feature request related to a problem? Please describe it

I want to use the old What's New feed as stated earlier, but there is no way as of now.

#### How will you/everyone benefit from this feature?

This feature would be good for people who find the current channel group loading slow, or want to see A-Z.

**Comment by Stypox** [comment]
The way we want to go is #3827, which allows for more flexibility while not adding too old entries. Also this exact solution was already proposed and is thus a duplicate
