### ISSUE TITLE
Failed Travis-CI

### ISSUE THREAD

**Issue by jsroyal** [TeamNewPipe/NewPipe#501]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I have been through Travis-ci but could understand Why is still failed.
If anybody here is error Log
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/travis/build/TeamNewPipe/NewPipe/app/src/main/java/org/schabi/newpipe/player/AbstractPlayer.java:303: error: cannot find symbol
            Log.d(TAG, "playVideo() called with: videoStream = [" + videoStream + ", " + videoStream.url + ", isVideoOnly = " + videoStream.isVideoOnly + "], autoPlay = [" + autoPlay + "]");
                                                                                                                                           ^
  symbol:   variable isVideoOnly
  location: variable videoStream of type VideoStream
/home/travis/build/TeamNewPipe/NewPipe/app/src/main/java/org/schabi/newpipe/player/AbstractPlayer.java:337: error: cannot find symbol
            Log.d(TAG, "buildMediaSource() called with: videoStream = [" + videoStream + ", " + videoStream.url + "isVideoOnly = " + videoStream.isVideoOnly + "], overrideExtension = [" + overrideExtension + "]");
                                                                                                                                                ^
  symbol:   variable isVideoOnly
  location: variable videoStream of type VideoStream
/home/travis/build/TeamNewPipe/NewPipe/app/src/main/java/org/schabi/newpipe/player/AbstractPlayer.java:359: error: cannot find symbol
        if (!videoStream.isVideoOnly) return mediaSource;
                        ^
  symbol:   variable isVideoOnly
  location: variable videoStream of type VideoStream
/home/travis/build/TeamNewPipe/NewPipe/app/src/main/java/org/schabi/newpipe/util/Utils.java:159: error: cannot find symbol
            if (audioStream.avgBitrate > audioStreams.get(highestQualityIndex).avgBitrate) highestQualityIndex = i;
                           ^
  symbol:   variable avgBitrate
  location: variable audioStream of type AudioStream
/home/travis/build/TeamNewPipe/NewPipe/app/src/main/java/org/schabi/newpipe/util/Utils.java:159: error: cannot find symbol
            if (audioStream.avgBitrate > audioStreams.get(highestQualityIndex).avgBitrate) highestQualityIndex = i;
                                                                              ^
  symbol:   variable avgBitrate
  location: class AudioStream
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
:app:compileDebugJavaWithJavac FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1 mins 19.226 secs
The command "./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleDebug lintDebug testDebugUnitTest" exited with 1.

**Comment by mauriciocolli** [comment]
Hey, 
The reason for the fail is that my pull request depends on the update of the submodule `NewPipeExtractor`, as I opened a pull request there too.

So yes, you can close this.

**Comment by jsroyal** [comment]
>The reason for the fail is that my pull request depends on the update of the submodule NewPipeExtractor, as I opened a pull request there too.

I didn't get it. What is the problem?
As you said to open the PR for submodule-> Is that only submodule does not pass test case?

**Comment by jsroyal** [comment]
@mauriciocolli  If you want to close it then your choice but as I think before passing all test case do not close this issue.

**Comment by mauriciocolli** [comment]
This pull request depends on the other.
So it have to:
- Merge the pull request on the **submodule**
- Merge the pull request **in this** repository
- Then it have to update the submodule in **this repository** to point to the latest version

In this case I can't do nothing, because how am I suppose to update the submodule in this repository to the latest version, if the latest version doesn't exist yet?
And as latest version I mean the changes that I did, don't exist there (in the submodule) yet.

And I'm just a contributor, so it's your choice to close it.

**Comment by jsroyal** [comment]
Is this PR #500  related to this?
But your PR still failed. So I think it will be open till this issue re-solve.

**Comment by mauriciocolli** [comment]
I think you can close it now.

**Comment by jsroyal** [comment]
Sure! Thanks.
