### ISSUE TITLE
Unable to update NewPipe (F-Droid, APK)

### ISSUE THREAD

**Issue by ssliackus** [TeamNewPipe/NewPipe#5012]
Hi Guys, 

Thanks for amazing program.

Sorry if I am posting this to a wrong place, I simply don't know where else to look for a help.

I am unable to play videos because I stuck with NP v20.1 - this is the latest version on F-Droid channel.
Tried to install APK, but no success  - get the messege "App not installed" and no any further details or error messages of any kind on this. Did that on two devices (Xiaomi, Asus), both failed.

Please, can I get help on that?

Thank you

S

**Comment by mhmdanas** [comment]
The reason is probably [this](https://newpipe.schabi.org/FAQ/download/#download-signing-keys).

You can also use the NewPipe F-Droid repository, which gets updates immediately. See https://newpipe.schabi.org/FAQ/tutorials/install-add-fdroid-repo/. You'll have to export your database (Settings > Content > Export database), delete the app, install it from the NewPipe F-Droid repository, and then import your database (settings > Content > Import database) from your new NewPipe installation. These instructions also apply if you want to install the APK from GitHub.

Also, please, please don't remove the template next time you open an issue. This will give both you and us a far easier time discussing the issue.

**Comment by ssliackus** [comment]
ok sorry for the template, this is my first post to Github.

ok, thank you for instructions, I was able to update, but I couldn't create a backup copy of data due to some error. I've created and emailed this as bug report.

S

**Comment by mhmdanas** [comment]
Could you post the error here?

**Comment by ssliackus** [comment]
{"user_action":"ui
error","request":"","content_language":"en","content_country":"GB","app_language":"en_US","service":"none","package":"org.schabi.newpipe","version":"0.20.1","os":"Linux
Android 9 - 28","time":"2020-11-26
14:02","exceptions":["java.io.FileNotFoundException:
/storage/0000-0000/4chat/NewPipeData-20201126_140216.zip (Permission
denied)\n\tat java.io.FileOutputStream.open0(Native Method)\n\tat
java.io.FileOutputStream.open(FileOutputStream.java:308)\n\tat
java.io.FileOutputStream.(FileOutputStream.java:238)\n\tat
java.io.FileOutputStream.(FileOutputStream.java:119)\n\tat
org.schabi.newpipe.settings.ContentSettingsFragment.exportDatabase(ContentSettingsFragment.java:198)\n\tat
org.schabi.newpipe.settings.ContentSettingsFragment.onActivityResult(ContentSettingsFragment.java:180)\n\tat
androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)\n\tat
android.app.Activity.dispatchActivityResult(Activity.java:7458)\n\tat
android.app.ActivityThread.deliverResults(ActivityThread.java:4354)\n\tat
android.app.ActivityThread.handleSendResult(ActivityThread.java:4403)\n\tat
android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)\n\tat
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)\n\tat
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)\n\tat
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)\n\tat
android.os.Handler.dispatchMessage(Handler.java:106)\n\tat
android.os.Looper.loop(Looper.java:193)\n\tat
android.app.ActivityThread.main(ActivityThread.java:6692)\n\tat
java.lang.reflect.Method.invoke(Native Method)\n\tat
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)\n\tat
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)\n"],"user_comment":""}

**Comment by mhmdanas** [comment]
Did you give it permission to access your storage?

**Comment by tuxayo** [comment]
About the update, here we can follow the fix of the root cause: https://gitlab.com/fdroid/fdroidserver/-/issues/797
