### ISSUE TITLE
Audio / Video delay

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#5018]
### Checklist

- [x] I am using the latest version - 0.20.4 (also 0.20.3 and .2) 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Description

2 users reported on #newpipe:matrix.org a a/v delay, "by ten plus seconds".

Using the YouTube service:

Every single video gets way out of sync (5-10 seconds) very soon after video starts. Also lots of stuttering and stop start playback. But that comes and goes. The syncing is the big problem. The video is ahead of the audio.

The problem was there in 0.20.2, .3 and .4. (and probably 0.20.0 because .1 and .2 were bug fixes)
The a/v delay is not there in legacy for one user (android 7), but not for the other one (with graphene os)

### Device info

 - Android version/Custom ROM version: Graphene OS, /e/ OS (7/nougat)
 - Device model:  Google Pixel 3, Samsung S4 mini

@Stypox @TobiGr

**Comment by infinitewaveparticle** [comment]
I have been noticing this happening on my Samsung Galaxy S7 Edge since at least 0.21.10. It's not 10 seconds, but it's about 2 on average... So this may be a different issue? Since it's so related I won't create a new issue. It's been happening most times I've used Newpipe for the past month or two.

**Comment by malzwei** [comment]
This has been happening on and off for me too for different Versions of NewPipe: Video is synchronous at start, after 2-3s video freezes for 1-2s but audio continues. After that the video lags.

**Possible workaround:** I noticed this behavior only with low battery (around 20%), after a full charge everything goes back to normal. Might be different for different people though.

However, this is not reproducible. The fix seems to work every time, but low battery not always causes the described behavior. Also this is independent from Androids Battery Saver-settings, as well as NewPipes video/audio format and playback load interval size.

Not a problem I'm not willing to live with :smile:
