### ISSUE TITLE
No music downloading

### ISSUE THREAD

**Issue by danielsoos1987** [TeamNewPipe/NewPipe#5021]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
Please open a new issue with the template filled.
