### ISSUE TITLE
Could not play the stream when playing from history

### ISSUE THREAD

**Issue by Suncatcher** [TeamNewPipe/NewPipe#5023]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'History'
2. Tap on video
3. The error received

I found [this similar bug](https://github.com/TeamNewPipe/NewPipe/issues/4571) but it is related to pausing the video, and I haven't done pause, it throwed from the video start at History. The same error is thrown when trying to play it via search or subscriptions, [this video](https://www.youtube.com/watch?v=UjWamsdYSMk) was successfully played yesterday but suddenly broken today.

### Actual behavior

The below error is received

### Expected behavior

The stream should be played

### Screenshots/Screen recordings

![photo_2020-11-28_18-21-36](https://user-images.githubusercontent.com/6388034/100520493-ceb54e80-3152-11eb-9b40-39005c1a6a5f.jpg)

### Logs

Logs from the Logcat [are here](https://pastebin.com/KkHA0f71), I didn't find anything relevant to this error

### Device info

 - Android version/Custom ROM version: Android 10, MIUI12
 - Device model: Redmi Note 8

**Comment by mhmdanas** [comment]
> I am using the latest version - x.xx.x

Please specify your NewPipe version.

**Comment by Suncatcher** [comment]
0.20.4

**Comment by vkay94** [comment]
It's a source type error (`ParserException: Invalid NAL length`). Did you also try other resolutions for these videos and face the same issue?

**Comment by Suncatcher** [comment]
> Did you also try other resolutions for these videos and face the same issue?

No, now I cannot reproduce this.

**Comment by litetex** [comment]
Closing: Not reproduceable
