### ISSUE TITLE
ExoPlayer volume/brightens too sensitive 

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#503]
@mauriciocolli 

The left and right area for brightens, and volume are a little bit to sensitive. Can you please make them less sensitive.

![screenshot_20170415-132720](https://cloud.githubusercontent.com/assets/1891273/25063270/0755532e-21e0-11e7-8151-880118904c70.png)

**Comment by Generator** [comment]
Notice that too, swipe controls way too sensitive.  
Something more smooth like on VLC would be nice.

**Comment by mauriciocolli** [comment]
Just a temporary fix, I guess I'll rewrite the gesture detector when I have more time...

**Comment by ildar** [comment]
devs: logarithmic scale is the key here IMHO. Emm, exponential to be precise.
@theScrabi : please, tOO, not tO

**Comment by theScrabi** [comment]
> @theScrabi : please, tOO, not tO

What do you mean by that?

**Comment by utack** [comment]
He is a grammar comcast, he literally only meant the spelling of the word 'too'

**Comment by wb9688** [comment]
@theScrabi: He meant that you wrote 'to', but it should be 'too'. 'to' is
used before inifinitive verbs, while 'too' is an adverb like 'extremely'.

**Comment by ildar** [comment]
😀 I'm not really that "comcastish" harsh usually. It's just the error
makes the issue title obscure, I had to dive in just to get its meaning.
Sorry for inconvenience.

**Comment by theScrabi** [comment]
Oh I see :P. Well... thank you.

**Comment by TheMatten** [comment]
@theScrabi #1604 introduced new gestures behavior - do you think it resolves this issue?

**Comment by theScrabi** [comment]
Lets se, if not we reopen it.
