### ISSUE TITLE
No new version notification shows on 0.20.3

### ISSUE THREAD

**Issue by huckvrni** [TeamNewPipe/NewPipe#5030]
When using the previous version newpipe didn't show a notification a new version was available, I can't check if that bug stayed for that version though until the next one comes up.

**Comment by PFDaily** [comment]
Hello,

Is this related to fdroid not having the latest version? Issue #4772 I believe discussed this and determined it was related to a bug in the fdroid store. 

You can get updates faster by adding the newpipe release repo. Check the project readme for more information. 

You should skip 0.20.4 update if you can and wait for 0.20.5

**Comment by mhmdanas** [comment]
@huckvrni please don't remove the template when opening an issue. You can open a new issue about this, but please keep the template and follow its instructions properly.
