### ISSUE TITLE
Stream stutter

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5032]
I would like for you to smoothen the streaming service. Newpipe streaming is not live. It will always be behind the original stream. When red line is dragged to live, it jerks and goes back. You could fix the red indication animations on streams.But main problem, it stops after some interval of time.(No my wifi isnt the problem, I had seen streams before). It would be fantastic if you could smoothen the streaming service.

**Comment by mhmdanas** [comment]
Like I said in your previous issue (which this one is copy-pasted from), you should not remove the template when opening an issue. Also, you should follow all of the template's instructions.
