### ISSUE TITLE
export also saves settings

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#5036]
Every time I use export I afraid if app settings will not be saved. Please update note for the export action.

### Checklist

- [x] I am using the latest version - 0.20.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to settings
2. Read Export database comment

### Actual behaviour

`Export history, subscriptions and playlists`

### Expected behavior

`Export history, subscriptions, playlists and settings`

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/14617699/100562436-d00a8680-32cc-11eb-8668-300a5a0a32fa.png)

### Device info

 - Android version/Custom ROM version: LineageOS 17.1
 - Device model: OP3T

**Comment by mhmdanas** [comment]
I think it might be better to make this "Export everything except download history" instead to be clearer.

**Comment by B0pol** [comment]
True. But you can choose not to import settings later

**Comment by mhmdanas** [comment]
Regardless of what one chooses to import later, settings are still exported.
