### ISSUE TITLE
wrong back action

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#5039]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

0. Make some search, or open a playlist
1. Open some video
2. Start playback
2. Press back (page will be collapsed, playback will continue, the screen requested on the step 0 will be shown)
3. Open another video (playback will be stopped)
4. Press back

### Actual behaviour

The video page from step 1 will be shown

### Expected behavior

The screen requested on the step 0 must be shown

### Screenshots/Screen recordings

![ScreenRecord-2020-11-30-08-24-33](https://user-images.githubusercontent.com/14617699/100572099-bde91200-32e5-11eb-9349-77cca4f55552.gif)

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by kaikun97** [comment]
I have this issue too on 0.20.4, especially with muscle memory from the official Youtube app :D

The issue seems to be that if you don't close the mini player first before loading another video, it will always go back to the video that the mini-player originally showed. I hope this gets fixed.

**Comment by Stypox** [comment]
This is the expected behaviour and has been discussed multiple times

**Comment by 532910** [comment]
I see nothing expected in this behaviour.

**Comment by 532910** [comment]
Back button should lead to the previous screen shown.

**Comment by kaikun97** [comment]
I'm sorry but I am going to have to disagree with you @Stypox 

I do not feel this should be the expected behavior, its counter intuitive for users who are coming from the official app.

Please can you re-consider this? Perhaps an optional feature?

**Comment by Stypox** [comment]
> It would go to the miniplayer regardless of the back stack and I think that would work out for all users.

Except that there wouldn't be a way to navigate the backstack.

> Should I make a separate issue for this suggestion?

No, as I said it has been discussed multiple times in multiple places. So unless there is a seamless solution for everyone, until there is no way to satisfy everyone this will stay as it is. If you want you can add your points where the issue has already been discussed. Btw, I agree with you that this behaviour is not the perfect one, but changing it would be probably worse unless a good solution is proposed
