### ISSUE TITLE
[Feature]Auto sync for imported Subscriptions

### ISSUE THREAD

**Issue by dtoxic47** [TeamNewPipe/NewPipe#5047]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Autosync option for imported subscriptions (youtube,or others) with a user defined interval (minutes,hours)

#### How will you/everyone benefit from this feature?

Well it,s 2020-21 almost all other software is automated,why not and On/Off option for Newpipe?

Checking for updates in subscriptions manually gets tedious after a while at best, on top of that an average user tends to forget to check manually for subscription updates and might miss an important video.

**Comment by mhmdanas** [comment]
Are you speaking about the subscription feed (the "What's New" kiosk) or the subscription list?

**Comment by sick13** [comment]
What's New that one,when you import your subscriptions from youtube and see new videos (sorry i am new to newpipe so just making sure we are on the same page)

**Comment by mhmdanas** [comment]
This is very similar to #4967. The difference is that this issue requests auto-refresh within a time interval, while that issue requests auto-refresh on app launch. So the question is, do we implement both, or only one of them?

**Comment by sick13** [comment]
hmmm well to more options we have more users configure it the way they like,what i think...personally i like the interval option to set it to check every 6 hours (that's what i have on majority of my apps)

**Comment by Rult** [comment]
> do we implement both, or only one of them?

@mhmdanas One that's easier to implement. And I think as NewPipe doesn't run as daemon at the moment, update on the launch should be easier to implement.

**Comment by sick13** [comment]
> 
> 
> > do we implement both, or only one of them?
> 
> @mhmdanas One that's easier to implement. And I think as NewPipe doesn't run as daemon at the moment, update on the launch should be easier to implement.

while it might be easier to implement what's to point of having that? start the app and save you one tap?
Auto sync should run in the background and update feed's at user customizable interval,that's the point of auto sync (not opening the app manually so you can update the feed's)

**Comment by illustribe** [comment]
+1 for this request! :D

**Comment by SameenAhnaf** [comment]
Wouldn't enabling new stream notifications get the job done? You might disable `New stream` notification category if you don't want the notifications.

**Comment by LuanHimmlisch** [comment]
Any news on this feature? I was going to create an issue myself, but saw this was already proposed (as I imagined). 

I have a large subscription count, and everyday I want to watch new videos I have to wait more than a minute to refresh. 

For me, this is the only thing NewPipe needs in order to be perfect.

**Comment by opusforlife2** [comment]
Doesn't the new stream notification feature solve this completely? There is a time interval setting in it as well.

**Comment by LuanHimmlisch** [comment]
@opusforlife2 the stream notification syncs all new videos from all subscriptions?

**Comment by opusforlife2** [comment]
@LuanHimmlisch Open the notification settings and see how nice the feature is. ;)
