### ISSUE TITLE
Stream smoothness

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5048]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

I am currently using newpipe version 0.20.4. I am using android 7 tablet.
My issue is not actually an issue. Just a small problem
I would like for you to smoothen the streaming service. Newpipe streaming is not live. It will always be behind the original stream. When red line is dragged to live, it jerks and goes back. You could fix the red indication animations on streams.But main problem, it stops after some interval of time.(No my wifi isnt the problem, I had seen streams before). It would be fantastic if you could smoothen the streaming service.
I went and opened a streaming service and this problem occured. Sadly Id have any logs. Hope to fix this in coming versions

**Comment by Stypox** [comment]
#1634 #1239 and you ignored the template again
