### ISSUE TITLE
Announce media playback to system

### ISSUE THREAD

**Issue by utack** [TeamNewPipe/NewPipe#505]
Unfortunately the new player does not seem to "announce" the playback to the system.
So if you are playing music, it continues when newpipe starts playing a video.
Could you integrate it better, so the system knows media is playing, and other meda is stopped?
Thank you

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by mauriciocolli** [comment]
I'm already implementing this and I'm almost finished, so expect it in the next few days

**Comment by mauriciocolli** [comment]
Sooner than I thought...

Tell me if it works for you.
