### ISSUE TITLE
[Updates] Don't download APK directly, open Releases page instead... 

### ISSUE THREAD

**Issue by aand18** [TeamNewPipe/NewPipe#5056]
**... as it gets people used to installing APKs that got downloaded by their browser, without verifying the origin.**

My proposition is to instead open the Releases page, easily verifiable as the official project page hosted on Github.com. 

I feel that the current process trades a little comfort with a lot of security, i.e. making the user ignore the exact origin of the APK he's installing (I doubt many verify the URL to be from github) . 

When you tap the "New version available" notice, the browser gets opened and a supposedly genuine NewPipe APK file gets downloaded.
I feel that I can't trust that download, thinking of the possibility the app update notification process gets somehow compromised, and I get redirected to a malware APK.

Admittedly I'm a bit paranoid but nowadays I find you must be, in order to keep yourself out of trouble. I hope you'll find this change sensible.

**Comment by Younes-L** [comment]
This download doesn't work for me, it opens browser then nothing happens. So I have to manually go to releases page anyway :/

**Comment by mhmdanas** [comment]
@Younes-L are you using Fennec? Somebody reported before that they couldn't download the APK when using Fennec. If you are using Fennec, maybe try another browser (like Bromite).

@aand18 your concern is legitimate, but please don't remove the template when opening an issue. Please open an issue with the feature request template and follow all its instructions properly. Thanks in advance!

**Comment by Younes-L** [comment]
@mhmdanas I'm using Chrome. I like to read the changelog before downloading and sometimes take a look at any new issues, so in the end I only use that notification as a notification x)

**Comment by TiA4f8R** [comment]
@Younes-L Chrome disabled downloading APKs opened in new tabs for "security reasons".

**Comment by krushia** [comment]
Instead of passing a URL intent, would it be possible for NewPipe to download the apk itself? Would that alleviate security concerns? Or have two clickable buttons in the notification, one for the apk and another for releases page?

As it operates now, I can download the apk from the notification without having to open a browser (today I used Download Navi). I would lose that convenience if the link went to the releases page.

**Comment by Younes-L** [comment]
@TiA4f8R I see, thanks for pointing out

@krushia a button in notification would be nice, by default and to cause the least discomfort for existing users, the button would open releases pages while the notification's body (expanded or not) would continue working as before (download link directly).
Ideally a setting to toggle what the notification does could be considered, although it's a bit overkill, the "updates" screen in settings is pretty empty x)

Right now a button in notification would serve as a shortcut to releases page (tapping the download link notification opens a new tab that's immediately closed)

**Comment by TiA4f8R** [comment]
@krushia @Younes-L You should comment your ideas on #3429
