### ISSUE TITLE
Add the new updates on fdroid

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5069]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it
 I would like to adress the huge situation of update on fdroid. I don't know why, but in fdroid there is only 0.20.1

#### How will you/everyone benefit from this feature?
 This will help everyone use fdroid to update their app. Your app situated in fdroid is used by many people and it would help greately if you could improve it.

**Comment by mhmdanas** [comment]
This is not an issue with NewPipe, but rather with F-Droid. In the meantime, we heavily encourage [using the NewPipe F-Droid repository instead](https://newpipe.schabi.org/FAQ/tutorials/install-add-fdroid-repo/) as even if the issue with the main F-Droid repo gets fixed, it will always be behind, while NewPipe's custom repo will show updates instantly when they are published.

**Comment by mrmotallebi** [comment]
With all respect and admiration I have for this app, I strongly disagree with having a separate repository for NewPipe on F-Droid. If each app was to have it's own repository, then it wouldn't make sense to have a central app store like F-Droid. Nor would NewPipe get much visibility. At least the alternate repository should not be considered as a replacement for F-Droid repo, IMHO.

**Comment by DestyNova** [comment]
What exactly is the issue with the F-Droid repo? The version there is quite buggy at the moment. Can we contact the F-Droid team to help push the update through? After they holding it back for some reason?

By the way, I did enable the Newpipe repo and it still wouldn't update in F-Droid. Maybe there was a network problem there, but in the end I had to directly download the APK for v20.5.

**Comment by mhmdanas** [comment]
@mrmotallebi I get your concern, but I think NewPipe is an exception. Its updates are much more time-sensitive than other apps, so having to wait a day or two for an update while NewPipe isn't working at all wouldn't be a good thing.

Note: the above is my personal opinion only.

**Comment by mhmdanas** [comment]
> What exactly is the issue with the F-Droid repo? The version there is quite buggy at the moment. Can we contact the F-Droid team to help push the update through? After they holding it back for some reason?

From what I know, it's a signing-related bug. They're not holding back or anything.

> I did get that to work, but had to uninstall the app first and lost my playlists. Oops.

You could export the database (Settings > Content > Export Database) to avoid this in the future.

**Comment by StephenCarboni** [comment]
Shouldn't the README and front page guide the user to using the newpipe repo? This seems to be an eternal issue with the official repo, maybe it's time to take the app off of it.

**Comment by mhmdanas** [comment]
@StephenCarboni see #5051. I'm planning to open a PR today for it.

**Comment by TobiGr** [comment]
We update the meta data on F-Droid when publishing a new release. The problem: we use reproducible builds and F-Droid's buildserver fails to validate our APK with their generated binary (since 0.20.2). We first thought that this was caused by a bug in their server tools, because NewPipe was not the only reproducible app which was not built correctly.
However, we might have caused the build to fail by enabling desugaring. If that is the case, https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7854 is going to fix the build for the 0.20.5 release and creating a release APK will be more complicated for future releases.

**Comment by JulienPalard** [comment]
Still no updates on f-droid. I understand there's other ways to install it, but for discoveravility I think f-droid ils important (because NewPipe is so good it deserve to be known <3)

**Comment by TobiGr** [comment]
we are in contact with the F-Droid team on a regular basis. If anyone knew a solution to this issue, be assured that we would implement it immediately.

**Comment by mrmotallebi** [comment]
Just a thought, but what do you think about someone creating a fork of NewPipe and submitting it to F-Droid as a separate app (even with a different name)?

**Comment by KingDuckZ** [comment]
Is it possible to just revert whatever commit(s) caused the issue? I feel like having one less feature (that I never had anyways) is better than having no NewPipe at all. I haven't been able to use it for a really long time now. And before anyone tells me, I agree with @mrmotallebi on not wanting to circumvent F-Droid.

**Comment by proletarius101** [comment]
let me look into it :P 
Reproducible builds should be encouraged

**Comment by TobiGr** [comment]
small update: build is reproducible, but signing fails. I'll get in touch with the F-Droid team to figure out why.

**Comment by obfusk** [comment]
There has been progress on the [f-droid reproducible build signing issues](https://gitlab.com/fdroid/fdroidserver/-/issues/797#note_538051778). It looks like we may have a solution soon. It would however [require setting `android.useNewApkCreator=false` in `gradle.properties`](https://fdroid.gitlab.io/fdroid-website/en/docs/Reproducible_Builds/#zipflinger).

**Comment by KingDuckZ** [comment]
Very sorry but I moved away from NewPipe as it just wasn't working. I installed NewPipe Legacy instead, which is identical, or at least I can't tell the difference, except that it works.

**Comment by mhmdanas** [comment]
I forgot to announce this here, so here I go: the latest versions of NewPipe are on F-Droid now. See #5421 for more details.
