### ISSUE TITLE
Mention creators in video titles & descriptions

### ISSUE THREAD

**Issue by developersop** [TeamNewPipe/NewPipe#5078]
Can we add Mention feature in video titles & descriptions?

![Screenshot_2020-12-03-09-32-06-824_com google android youtube](https://user-images.githubusercontent.com/73459162/100962513-6f887d00-354a-11eb-85c3-76cfdd073610.jpg)

**Comment by mhmdanas** [comment]
Please don't remove the template when opening an issue. You can open a new issue with the feature request template filled from [here](https://github.com/TeamNewPipe/NewPipe/issues/new/choose). Thanks in advance!

**Comment by developersop** [comment]
> Please don't remove the template when opening an issue. You can open a new issue with the feature request template filled from [here](https://github.com/TeamNewPipe/NewPipe/issues/new/choose). Thanks in advance!

Can you add this request

**Comment by mhmdanas** [comment]
We will discuss that when you open an issue with the template properly filled.
