### ISSUE TITLE
It will be great if add feature to import saved play list from YouTube to NewPipe (just like importing of subscription )


### ISSUE THREAD

**Issue by Atharvega** [TeamNewPipe/NewPipe#5079]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by mhmdanas** [comment]
Filling the checklist is not optional, and you can't leave the rest of the sections empty. Please edit your issue to follow the template properly then ping me and I'll re-open it. Thanks!
