### ISSUE TITLE
Can't close/out the player's float window

### ISSUE THREAD

**Issue by konkor** [TeamNewPipe/NewPipe#508]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
![screenshot_1492775604](https://cloud.githubusercontent.com/assets/1891273/25276487/bf519d0c-269a-11e7-8e7d-36ea7c8c7e0f.png)

**Comment by konkor** [comment]
Yes, I found this too. But how to close Fullscreen window? :)

**Comment by wb9688** [comment]
With your device's back button.

**Comment by mauriciocolli** [comment]
###### Assuming that "Fullscreen window" is the fullscreen player

Pressing the back button (the "sideways triangle") should close it...

**Comment by konkor** [comment]
Heh now it's working... It's stopped working when I didn't close some float window... I'll test more. Sry
