### ISSUE TITLE
Startloop

### ISSUE THREAD

**Issue by Suncatcher** [TeamNewPipe/NewPipe#5089]
### Checklist

- [ ] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Seems like it entered a loop and cannot get out of it, nothing helps except pressing Home button. I experienced this multiple times.
It was shot on NewPipe 0.20.4, but I bet it exists on 0.20.5 as well, it's just a matter of time when I reproduce it on 0.20.5.

### Expected behavior

Normal start

### Logs

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6388034/100984523-7ff12580-3553-11eb-9958-bdbe80b6e125.gif)

[Full video](https://streamable.com/3tbsf5)

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Kyocera E6910

**Comment by mhmdanas** [comment]
No, this was fixed in 0.20.5. See #5017.

**Comment by Suncatcher** [comment]
Ok, good. Then I searched bad.
