### ISSUE TITLE
Player control is flickering on Google Nexus 4

### ISSUE THREAD

**Issue by konkor** [TeamNewPipe/NewPipe#509]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I can't even press back button. Only pausing helps through the hardware Power button.

**Comment by theScrabi** [comment]
Can you tell us which version you use?

**Comment by konkor** [comment]
The latest official Android 5.1.1 for Google Nexus 4

**Comment by theScrabi** [comment]
No I mean which NewPipe version

**Comment by konkor** [comment]
0.9.2 from f-droid

**Comment by konkor** [comment]
When I'm selecting old or external player all work fine.

**Comment by mauriciocolli** [comment]
Can you please take some screenshot or record the screen demonstrating the bug?

**Comment by konkor** [comment]
But on Asus tf300 all fine with Android 4.2.1. So I want to ask if you don't mind. Is This app working on cyan

**Comment by konkor** [comment]
CyanogenMod without Google apps installed?

**Comment by konkor** [comment]
OMG I'm writing on my phone... Heh sry

**Comment by mauriciocolli** [comment]
Please stop spamming, use the edit button instead, for users that receive notification emails, like me, it's very annoying.

But did you read my last post?

**Comment by konkor** [comment]
I made this screencast:
https://youtu.be/fzIR9AsoMZ8

**Comment by mauriciocolli** [comment]
I saw in your video that you have debug activated, can you provide a logcat with this debug version?

Here it is [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/947882/app-debug.apk.zip), and if you don't how to get the log, just run this command
 `adb logcat > log.txt`, reproduce the bug and press `Ctrl + C` to stop it.

**Comment by konkor** [comment]
@mauriciocolli Here is related logcat. I have pressed a few times so.
```
D/audio_hw_primary(  190): select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
D/ACDB-LOADER(  190): ACDB -> send_afe_cal
D/audio_hw_primary(  190): enable_snd_device: snd_device(2: speaker)
I/ActivityManager(  570): START u0 {cmp=org.schabi.newpipe/.player.ExoPlayerActivity (has extras)} from uid 10183 on display 0
D/audio_hw_primary(  190): enable_audio_route: apply and update mixer path: low-latency-playback
V/WindowManager(  570): addAppToken: AppWindowToken{1a947637 token=Token{114dc736 ActivityRecord{200bd0d1 u0 org.schabi.newpipe/.player.ExoPlayerActivity t5295}}} to stack=1 task=5295 at 1
D/AbstractPlayerImpl.ExoPlayerActivity( 7882): buildMediaSource: cacheDir = /storage/emulated/0/Android/data/org.schabi.newpipe/cache/exoplayer
I/art     ( 7882): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art     ( 7882): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art     ( 7882): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art     ( 7882): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art     ( 7882): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/ExoPlayerImpl( 7882): Init 2.3.1 [mako, Nexus 4, LGE, 22]
V/WindowManager(  570): Adding window Window{39e13a10 u0 org.schabi.newpipe/org.schabi.newpipe.player.ExoPlayerActivity} at 7 of 13 (after Window{343a23b0 u0 org.schabi.newpipe/org.schabi.newpipe.MainActivity})
V/WindowManager(  570): Adding window Window{2c4a870e u0 SurfaceView} at 7 of 14 (before Window{39e13a10 u0 org.schabi.newpipe/org.schabi.newpipe.player.ExoPlayerActivity})
I/ActivityManager(  570): Displayed org.schabi.newpipe/.player.ExoPlayerActivity: +326ms
I/VideoCapabilities( 7882): Unsupported profile 4 for video/mp4v-es
I/OMXClient( 7882): Using client-side OMX mux.
E/OMXMaster( 7882): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
W/OMXNodeInstance( 7882): [1:google.vp8.decoder] component does not support metadata mode; using fallback
E/ACodec  ( 7882): [OMX.google.vp8.decoder] storeMetaDataInBuffers failed w/ err -1010
E/OMXNodeInstance( 7882): getParameter(1:google.vp8.decoder, ParamVideoAndroidVp8Encoder(0x6f600007)) ERROR: UnsupportedIndex(0x8000101a)
I/OMXClient( 7882): Using client-side OMX mux.
E/OMXMaster( 7882): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
E/WifiStateMachine(  570): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=132,63 rxSuccessRate=169,60 targetRoamBSSID=any RSSI=-61
```

**Comment by mauriciocolli** [comment]
It seems that is not the debug version that I posted in the previous post, that log does not contain any useful information for this problem...

**Comment by konkor** [comment]
@mauriciocolli ohh my bad sry. here is the link for debug version https://pastebin.com/0ej19UAE

**Comment by konkor** [comment]
@mauriciocolli so it's not like a flickering it's more like showing control and immediately hiding after i releasing finger from the screen. So i can't pause or press any control button even system button hiding  immediately. Only hardware Power Button can pause player and i can out or continue play.

**Comment by konkor** [comment]
So when I'm touching screen and holding nothing happens.

**Comment by konkor** [comment]
Don't focus on this issue it's only on Nexus 4. So NewPipe is working fine with any external player Google Photos, QuickPic... Maybe it's hardware issue some accelerated layer I dunno...
PS: So i tried similar project MinTube https://github.com/imshyam/mintube and there is all working fine control for Nexus4 but it's pausing video on touch event and then showing control. But your project is better and under development when other seems stopped development.

**Comment by mauriciocolli** [comment]
I have a **suspicion** that is a bug with your ROM, it seems like the `delay` of the animation to hide the controls are not respected.

Just to confirm, can you please provide a logcat with the time in it?
The command to do that is `adb logcat -v time`

**Comment by konkor** [comment]
How to pop-up player if I can't get player control? So how to resize pop-up player?
So if my flash memory broken I could break my phone if I'll

**Comment by mauriciocolli** [comment]
There's another way to open popup, in this debug version there's a option called "Popup" next to the like/dislike bar.

**Comment by konkor** [comment]
Pop-up player works well. Can I change the size of the pop-up player?

**Comment by mauriciocolli** [comment]
Hey @konkor, I think your issue is the same as #536, as I can see in your video the animations are instantaneous.

Could you try setting `Animator duration scale` in developer settings to 1x and testing again?

**Comment by konkor** [comment]
@mauriciocolli Yeah It's fixed the issue. Can you set this parameter within the player app and/or restore on exit?

**Comment by mauriciocolli** [comment]
Yeah I can set this value to normal via reflection, but I don't want to do that, some (low-end) devices come with this option to off or some people don't like of the animations, so I'm working on another fix.

**Comment by konkor** [comment]
I guess I did it. I turned this option off. Sorry

**Comment by uNouss** [comment]
hello i have same issue in my sony xperia E4G, despite that i setting "animator duration scale". i use NewPipe 0.9.5 fdroid

**Comment by mauriciocolli** [comment]
@uNouss that release don't contain the fix yet, in the next it will (I don't control the releases, so I don't know when)

**Comment by uNouss** [comment]
@mauriciocolli okay thank you ^^
