### ISSUE TITLE
[Feature request] import/export Local bookmarks.

### ISSUE THREAD

**Issue by konkor** [TeamNewPipe/NewPipe#510]
It'd be great to have an ability to import/export bookmarks for videos/channels without any Log in.

**Comment by theScrabi** [comment]
saving bookmarks was already requested a douzend of times.
Look at the [comming features](https://github.com/TeamNewPipe/NewPipe#coming-features) section of the README, there you will see that entry NR. 1 is bookmarks support.

However Import/export of Bookmakrs is new :)

**Comment by konkor** [comment]
Nice work! )

**Comment by arteteco** [comment]
Any update? Exporting bookmarks would be a useful feature indeed!

**Comment by opusforlife2** [comment]
This is either about subscription import/export, or import/export of bookmarked playlists. If the first, it is already implemented. If the second, then closing this in favour of #4076.
