### ISSUE TITLE
Video not found while add to the playlist from custom list

### ISSUE THREAD

**Issue by vinibali** [TeamNewPipe/NewPipe#5105]
### Checklist
- [x] I am using the latest version - 0.20.5
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to the custom list's page on the browser
2. Longpress the video you want to hear/watch
3. Share the URL with NewPipe
4. Click on "Play on background"

### Actual behaviour
Error got "NewPipe: Content not found"

### Expected behavior
Audio got played in the background

### Screenshots/Screen recordings
N/A

### Logs
Example URL: https://www.youtube.com/watch?v=BLAVIDEO&list=BLALIST&index=1&t=78s

### Device info

 - Android version/Custom ROM version: 10.0.0 factory
 - Device model: Oneplus 5T

**Comment by Stypox** [comment]
You provided an invalid url, obviously that's a content not found

**Comment by vinibali** [comment]
That was just an example. I replaced the video id with a BLAVIDEO and the list is with a BLALIST.
Let's have an real one here. It has the same error with the latest 20.8 version. Could you please reopen this issue?
https://www.youtube.com/watch?v=kMLfRh-BBKE&list=PL6Az3D4GL-TdsK14I9ZjFKnG7dN3qK8_e&index=1&t=78s

**Comment by Stypox** [comment]
Uhm, strange. That url is part of a playlist which does not exist: https://www.youtube.com/playlist?list=PL6Az3D4GL-TdsK14I9ZjFKnG7dN3qK8_e
I don't know what we could do with this, the current behaviour is theoretically the correct one, as the content is really not available.

**Comment by Stypox** [comment]
> Go to the custom list's page on the browser

I can't understand what this passage means. What is a custom list? Is it a private playlist? If that's the case then there is not much we can do, as private playlists are not publicly queriable and we can't know whether a playlist is private or not before deciding whether to show the playlist or to show the single video.

**Comment by vinibali** [comment]
Yes, that's a playlist in the reproduce test.
The playlist I showed in the example is one of my private ones, however the URL which was opened in NewPipe is real.
I used to open Youtube in Firefox, which has a shortcut to the list I used to play in the car. And I long click on one of the videos from the list and share it with Newpipe. This is the way how I insert the links and I click on "Play on the background" on the popup.
I would say, if the list is not available Newpipe should just play the video/audio.

**Comment by tech705** [comment]
please unsubscribe/take me off email list for newpipe

**Comment by vinibali** [comment]
@Stypox, can you please consider to reopen this bug? We can even call it as a feature or improvement :)
For now, I need to use another bunch of private lists, which are still not usable in NewPipe.
I think using a logic, if the video is unavailable with full URL and has other elements in the address:
* NewPipe can try to strip down the list element and tries to play the video without it
What do you think?

**Comment by Stypox** [comment]
This is not doable with the current architecture. Please refer to #928

**Comment by vinibali** [comment]
Thanks for you reply
