### ISSUE TITLE
Replace usages of newpipe.schabi.org with newpipe.net

### ISSUE THREAD

**Issue by mhmdanas** [TeamNewPipe/NewPipe#5109]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Use https://newpipe.net instead of https://newpipe.schabi.org.

#### Is your feature request related to a problem? Please describe it
No.

#### Additional context
See TeamNewPipe/website#203.

#### How will you/everyone benefit from this feature?

https://newpipe.schabi.org may stop working in the future.

**Comment by TiA4f8R** [comment]
@mhmdanas This should be done with my two pull requests: #5236 and #5184.
