### ISSUE TITLE
FullScreen button

### ISSUE THREAD

**Issue by JuanCarlosM1** [TeamNewPipe/NewPipe#5111]
you can put the FullScreen button all the time as before, the button doesn’t appear here and always the bug when I turn the phone

**Comment by mhmdanas** [comment]
Please don't remove the template when opening an issue. You can open a new issue using the bug report template from [here](https://github.com/TeamNewPipe/NewPipe/issues/new/choose), but please don't remove the template; you should follow its instructions too (e.g. check for duplicates). Thanks!
