### ISSUE TITLE
Nord VPN and newpipe

### ISSUE THREAD

**Issue by levoothan** [TeamNewPipe/NewPipe#5113]
I saw earlier issues reported about using a VPN while connected but those seemed to get fixed in patches years ago. Currently no matter what VPN server I use newpipe simply refuses to connect instead showing retry. However once I disconnected my VPN it allowed me to connect. Is this something others are currently facing or is this a bug that has just resurfaced?

**Comment by mhmdanas** [comment]
Please open an issue with the template followed properly from [here](https://github.com/TeamNewPipe/NewPipe/issues/new/choose). Thanks!
