### ISSUE TITLE
Seekbar for audio only

### ISSUE THREAD

**Issue by Rhymezz** [TeamNewPipe/NewPipe#512]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

There is a lot of 1-2 hour podcasts-like discussions on youtube that I often litsen to. Newpipe offers audio only and ability to have the screen off when litsening but you dont have a seekbar, so you get forced to litsen to 20 minutes of an intro that is just music or something and cant go directly to the when the podcast starts.

It would be nice if there was more for the audio-only interface like a seekbar. That would be nice.

**Comment by theScrabi** [comment]
Absolutely, I just didn't find time to implement It yet :) But I see forward to that to :)

**Comment by Rhymezz** [comment]
cool :)

**Comment by Wabuo** [comment]
@Rhymezz Use an external audio player I use VLC then you can use the seekbar from the external player works like a charm ...

**Comment by markreg** [comment]
There is also an issue with Background Audio stopping after 15-20 mins with the app minimized and the screen off. At least on LTE that's what I've experienced. The seekbar would allow one to go back to the time the stream stopped.

**Comment by cyphar** [comment]
@Wabuo I've had problems with seeking using VLC if you have a _really_ long (several hours) video. From my experience the only really reliable audio seeking implementation is the built-in one in NewPipe.

**Comment by Stypox** [comment]
This has been implemented
