### ISSUE TITLE
NewPipe starts by itself

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#5122]
### Checklist

- [x] I am using the latest version - 0.20.5 (official repository) 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. NewPipe closed without being in background (all recent apps cleared)
2. Notification appears, see picture
3. Volume starts changing by itself

### Actual behaviour

NewPipe is closed (not in background or recent tab switcher/screen), after some time notification/app control widget (see picture) shows up triggered by itself. This notification also shows up when the phone screen is locked. Following this, all of the sudden system's volume appear and (by itself) changes volume level.

Not sure if this is related to new updates after 0.20.1 (before that everything was fine) or to headphone jack (because those are the only things that changed).

### Expected behavior

Closed NewPipe not starting up by itself.

### Screenshots/Screen recordings

![newpipe](https://user-images.githubusercontent.com/74458162/101359727-77625d00-387b-11eb-92b1-92e44db5b476.png)

### Logs

It's very random, hard to know what causes it and when.

### Device info

 - Android version/Custom ROM version:10
 - Device model:

**Comment by avently** [comment]
You probably clicked on media button on your headphones. In this case NewPipe starts. However the blank notification shouldn't be show. The regression is somewhere

**Comment by sansnil** [comment]
I can confirm this bug as well in the .20.6 version. Seems to happen for me when a notification sound plays it will trigger the NewPipe notification. No headphones involved.

**Comment by gigiboeru** [comment]
Thai happens to me only if I mark the new pipe notifications as priority (on one plus 7)

**Comment by mhmdanas** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/5778#issuecomment-797862125.

**Comment by AudricV** [comment]
This should have been fixed by #10578, released in 0.26.0. I am closing this issue as fixed. Please comment if that's not the case and I will reopen this issue. Thank you.
