### ISSUE TITLE
Shuffle function does not work properly

### ISSUE THREAD

**Issue by govinda9** [TeamNewPipe/NewPipe#5123]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The Shuffle function only mixes the last 100 songs. If there is a  youtube playlist with around 500 songs, only the last 100 songs will be played, no earlier songs show up in the beginning of the schuffled list.  And the shuffle option is only available, when I reopen Newpipe from the notification panel. Can you please fix this?

**Comment by mhmdanas** [comment]
Well, according to #875, it's the opposite. This is confusing.

Also, you opened this issue using a feature request template. Could you open a new issue with the bug request template instead?

> And the shuffle option is only available, when I reopen Newpipe from the notification panel. Can you please fix this?

You can edit the actions shown in the notification from Settings > Notification.
