### ISSUE TITLE
Nested lists || Nested tags for lists

### ISSUE THREAD

**Issue by JeffRockatansky** [TeamNewPipe/NewPipe#5128]
### Checklist
* [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
* [x] I have read the contribution guidelines given at [CONTRIBUTING.md](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
* [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

### Describe the feature you want
Ability to subcategorize lists:
* playlists
* channel groups

Implementation options:
* Direct nesting, similar to how files and folders usually work.
	* Strict hierarchy, single-rooted tree.
* Parallel nesting, with tags and subtags. More convenient, when you just can't put something in only one category.
	* Loose hierarchy, more like a graph or mesh.

### Is your feature request related to a problem? Please describe it
I've created quite a lot of playlists and channel groups, and now it's hard to navigate. Also many of them are related and could be grouped.

### How will you/everyone benefit from this feature?
It will be much more convenient to use subscriptions and playlists.

**Comment by not-the-avatar** [comment]
i also have a lot of playlists and thought it would be good to have a way to organize them, i could try to implement this feature.

**Comment by JeffRockatansky** [comment]
@not-the-avatar 
> i could try to implement this feature.

Sounds cool! Even though I don't have any android development experience, I'd like to participate in this effort.

**Comment by not-the-avatar** [comment]
@JeffRockatansky 
> Sounds cool! Even though I don't have any android development experience, I'd like to participate in this effort.

i dont have any experience with android either, i guess you could try grouping channels feature i will try for playlists

**Comment by JeffRockatansky** [comment]
@not-the-avatar
> i dont have any experience with android either, i guess you could try grouping channels feature i will try for playlists

First of all, we need to choose which option we will implement.

I vote for hierachical tags because it's much more flexible. But more complex and harder to implement though.

Secondary, we need to start from simple, basic and abstract, and only then come to more complex and specific.

**Comment by not-the-avatar** [comment]
@JeffRockatansky 

this has been discussed here https://github.com/TeamNewPipe/NewPipe/issues/1982#issuecomment-528029200 before and they seem to have agreed on using folders

i too think folders are better, it would be a hassle to implement and maintain hierarchical structure

**Comment by JeffRockatansky** [comment]
> **parallel** hierarchical structure
Bc folders are already a single root hierarchy. But I agree, it is much simpler an could be later changed if properly prepared and designed.

I just think parallel hierarchies or graphs are able to store much more complete representation of category data.

For example, a video on how to **build from source** and **install on Linux** a **video editing app** is simultaneously a part of these structures:
* `OS > UNIX > Linux > Administration > Package Management`
* `Software > Apps > Media > Video Editing`
* `Software > Licensing > FOSS`

From my perspective, it could not be separated from either, as it is evenly described by all three tags (`Package Management`, `Video Editing`, `FOSS`). If we decide to use only one hierarchy, we loose important categorization data.

**Comment by not-the-avatar** [comment]
I agree graphs would be much more flexible but i dont think i could implement this by myself 

also this kind of categorization wont be useful to most users

**Comment by mhmdanas** [comment]
Closing in favor of #1313.
