### ISSUE TITLE
After minimizing and reopening the app is like newly opened

### ISSUE THREAD

**Issue by Wabuo** [TeamNewPipe/NewPipe#513]
Bug appeared in 0.9._f-droide

Hey if I minimize the App after I searched for something the results are gone - annoying but at least the search string is still there.

But if I minimize in the Video detail screen everything is gone and it is like I had closed and reopened the app. That makes the app nearly useless for me ...

If you need something just ask =)
Maby it has something to do with this #449

**Comment by mauriciocolli** [comment]
Yes is related with the other issue, so you can close this.

Also, I'm almost finished implementing the correct behavior, so soon it'll be fixed.

**Comment by Wabuo** [comment]
@mauriciocolli OK thx

And nice work!
