### ISSUE TITLE
Split Player

### ISSUE THREAD

**Issue by Github-com-foss** [TeamNewPipe/NewPipe#5133]
Split a player into two part Top and bottom

If read a comments section or view related video. The playing video will not hidden to the top if swipe up to view comments and related videos. So, split top and bottom in player. Only Bottom part swipable form not top part. So, watching videos and viewing comments at same time.

IMAGE SAMPLE ATTACHED
![Screenshot_20201209-172410_NewPipe-01_1_1_1](https://user-images.githubusercontent.com/75672019/101630022-4420f900-3a48-11eb-8124-d5fbaf87f34b.jpeg)
![Screenshot_20201209-172415_NewPipe-01_1_1_1](https://user-images.githubusercontent.com/75672019/101630027-46835300-3a48-11eb-98a8-93ed869b6a3c.jpeg)

**Comment by mhmdanas** [comment]
Duplicate of #4484.

Also, please don't remove the template next time you open an issue. Thanks!
