### ISSUE TITLE
 NewPipe not loading anything

### ISSUE THREAD

**Issue by AndyP2002** [TeamNewPipe/NewPipe#514]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Not sure since when but NewPipe is not opening/loading any youtube links from Reddit is Fun app. 
NewPipe loads ok but I just get the spinning cursor.(same videos open and play fine in youtube itself)
Also entering any search term causes same blank page and spinning cursor. 
I was still on a previous version but have installed latest now - no change. 
Android version is v5.1 (Lollipop)

**Comment by mauriciocolli** [comment]
Can you test the latest releases?

**Comment by pizzadude** [comment]
I had the same issue today, a router reboot fixed it.

**Comment by mauriciocolli** [comment]
If it still happening, tell me.

**Comment by AndyP2002** [comment]
Sorry for delay replying, been away. 
I can confirm issue is no longer occuring now. Have updated to latest version but unsure if that is what cured it or if it went away by itself.
Thanks
