### ISSUE TITLE
[Amazon Fire TV] UI doen't fit 

### ISSUE THREAD

**Issue by Speciesx** [TeamNewPipe/NewPipe#5140]
### Checklist

- [x] I am using the latest version - v0.20.6 

### Screenshots/Screen recordings

![20201210_225557](https://user-images.githubusercontent.com/1196375/101837264-19659c00-3b3f-11eb-83f9-7dfc0b67978d.jpg)

![20201210_225613](https://user-images.githubusercontent.com/1196375/101837267-1a96c900-3b3f-11eb-8629-e8b5a818a7d7.jpg)

![20201210_231025](https://user-images.githubusercontent.com/1196375/101837271-1bc7f600-3b3f-11eb-9fd6-95ce188cf79b.jpg)

![20201210_231036](https://user-images.githubusercontent.com/1196375/101837275-1d91b980-3b3f-11eb-9f8d-802a128dbfa5.jpg)

![20201210_231111](https://user-images.githubusercontent.com/1196375/101837279-1ec2e680-3b3f-11eb-80ce-850d0a499369.jpg)

### Device info

 - Android version/Custom ROM version: Fire OS 7.2.2.x
 - Device model: Amazon Fire TV stick 3. Generation

**Comment by revathskumar** [comment]
Did you tried [Calibrate Your Display to Fire TV](https://forums.tomsguide.com/faq/how-to-calibrate-your-display-to-fire-tv.212713/) ?
