### ISSUE TITLE
v0.20.6 not suggested in custom F-Droid repo

### ISSUE THREAD

**Issue by FintasticMan** [TeamNewPipe/NewPipe#5141]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to F-Droid with the NewPipe custom repository enabled
2. Find Newpipe, and look at the versions list
3. Notice that the v0.20.6 release is not marked as suggested

### Actual behaviour

The latest version isn't marked as suggested, which means that the F-Droid app doesn't give you an update notification, and doesn't auto-update.

### Expected behavior

The latest version should show as suggested, so that automatic updates work properly.

### Device info

 - Android version/Custom ROM version: Official LineageOS 16 / Android 9
 - Device model: Huawei P20 lite

**Comment by B0pol** [comment]
@TheAssassin

**Comment by danvim** [comment]
Wait, so why is this closed? I'm on 0.20.1 and F Droid cannot find an update for the app. 

I only see the following versions in F Droid.

- 0.20.1
- 0.20.0

I'm using Android 10.

Did New pipe stop using F Droid?

**Comment by FintasticMan** [comment]
The issue here is that for some reason (as far as I know, we don't know exactly why) the builds of newpipe aren't entirely reproducible, and so the main ("official") F-Droid repository won't accept it.  This is why the latest version on the main F-Droid repo is 0.20.1.  There is however a newer build available, which you can find if you're using the custom F-Droid repo, which can be found here: https://github.com/TeamNewPipe/NewPipe/#updates.  In this issue I was referring to that repository.
