### ISSUE TITLE
[Feature] More customizable UI

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5144]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

This is a bit of a big request, so I doubt it will be added, but it's worth a shot. What I want is a way to change the colour at the top from red with a colour picker, new icons for channel groups, a way to move the top bar to the bottom, and a way to change what icons are where (or be able to remove some!) in the video player.

#### Is your feature request related to a problem? Please describe it
No, this is just a cosmetic change that users could use to make it look nice.

#### Additional context
*Simple mock-up with text overlay*
![IMG_20201211_085345](https://user-images.githubusercontent.com/71007160/101882953-7e94ae00-3b8e-11eb-8f3a-b5b1321f385d.jpg)

#### How will you/everyone benefit from this feature?
This feature will help people customize newpipe even more to their liking!

**Comment by k9janer** [comment]
Having the ability to change the color would be great. Not just from an aesthetic purpose, but also to reduce the chance of screen burn out on OLED screens and screen uniformity issues on Plasma screens.

Unfortunately the red color of the bar in NewPipe is probably the worst possible color in terms of burn out as the red color is usually the one that burns out the fastest on OLED screens. It's not just tvs - smartphones and tablets with OLED screens can also be affected though they are usually replaced after just a few years.

Currently I'm using NewPipe on my LG C9 OLED tv but every time I spent more than a minute in my subscription box, I worry that the red bar will eventually cause permanent damage to my hardware. :(

You will find a lot of images where red elements have caused burn out - things like red news banners or the red Netflix logo like this: https://www.avforums.com/attachments/burn-pic-jpeg.1440245/

So for this reason I would love to have the option to change the color or - preferably - to just turn the bar completely black.

**Comment by opusforlife2** [comment]
@HTSamurai You have opened a number of issues before, so you know perfectly well that there is supposed to be only one feature request per issue. You even ticked the box in the checklist.
