### ISSUE TITLE
Show "Stream to Kodi" in context menu

### ISSUE THREAD

**Issue by lameventanas** [TeamNewPipe/NewPipe#5157]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

This is very easy.
There already is a function to send a video to Kodi, but you first have to open it.
I would like to have a "Send to Kodi" function in the context menu of searches, 

#### Is your feature request related to a problem? Please describe it

![2020_12_12_092430](https://user-images.githubusercontent.com/11934069/101966721-2cba5980-3c5c-11eb-9d06-05ca958a61e4.png)

#### How will you/everyone benefit from this feature?

It will make it much better for owners of Kodi devices.

**Comment by lameventanas** [comment]
Now that I think about it, a "Queue to Kodi" would also be good.

**Comment by khimaros** [comment]
this would be awesome. a few code pointers:

[callback for current "Play in Kodi" video action](https://github.com/TeamNewPipe/NewPipe/blob/531859ac607d55ecda0b67fcc9ce4932d27d9a82/app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java#L906)

[where the list of context menu items are constructed](https://github.com/TeamNewPipe/NewPipe/blob/7c80233f2625a28b96d07108e67c62d704b542f2/app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java#L21)

[implementation of playWithKore()](https://github.com/TeamNewPipe/NewPipe/blob/c4a739bef66aaed3149595b7e4f4f38fde716961/app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java#L616)

i believe queue vs. play is handled by Kore itself.
