### ISSUE TITLE
Functional like button

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5159]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I don't know how nobody has made an issue for this, but basically make the like and dislike buttons add to a Liked/disliked videos playlist.

#### Is your feature request related to a problem? Please describe it
A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.

#### Additional context
*Mock up images edited from base NewPipe screenshots*
<img alt="IMG_20201212_122106" src="https://user-images.githubusercontent.com/71007160/101983785-110f7d00-3c75-11eb-8b76-c48e00f19819.jpg" height=600 />

#### How will you/everyone benefit from this feature?
People will be able to help people mark the videos they like! *and maybe help us colonize the galaxy*

**Comment by HTSamurai** [comment]
Oops, forgot to include this other
*Mock up*
![Uploading IMG_20201212_122106.jpg…]()

**Comment by TobiGr** [comment]
Local likes sound great to me!
That should be pretty easy to implement.

**Comment by HTSamurai** [comment]
> Local likes sound great to me!
> That should be pretty easy to implement.

That's the two reasons i thought this was good.
Another *Mock up* i made is:
![Screenshot_2020-12-12-13-19-38-716_com miui gallery](https://user-images.githubusercontent.com/71007160/101984983-b9750f80-3c7c-11eb-989d-84376b970873.jpg)

**Comment by notramo** [comment]
What about bookmarking instead?

**Comment by HTSamurai** [comment]
> What about bookmarking instead?

Well that isn't quite the same. You could just have a bookmark playlist for that so I think this is better.

**Comment by Newpipeuser** [comment]
i agree i would love to see a like or dislike button functional

**Comment by ggdorman** [comment]
I'll be honest I'm not a fan of the idea and find it quite pointless.

>Is your feature request related to a problem? Please describe it
>
>A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.

If this is the problem, then why not just add the option to sort videos by date added and in ascending/descending order. This is something I am already opening a request for, and ti doesn't bloat the app with pointless features.

#5201

**Comment by HTSamurai** [comment]
> I'll be honest I'm not a fan of the idea and find it quite pointless.
> 
> > Is your feature request related to a problem? Please describe it
> > A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.
> 
> If this is the problem, then why not just add the option to sort videos by date added and in ascending/descending order. This is something I am already opening a request for, and it doesn't bloat the app with pointless features.
> 
> #5201

That isn't as convenient as a way to upvote/downvote

**Comment by HTSamurai** [comment]
like/dislike*

**Comment by ggdorman** [comment]
> > I'll be honest I'm not a fan of the idea and find it quite pointless.
> > > Is your feature request related to a problem? Please describe it
> > > A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.
> > 
> > 
> > If this is the problem, then why not just add the option to sort videos by date added and in ascending/descending order. This is something I am already opening a request for, and it doesn't bloat the app with pointless features.
> > #5201
> 
> That isn't as convenient as a way to upvote/downvote

It isn't, but liking/disliking is a pointless feature in an app designed to be account-less.

**Comment by HTSamurai** [comment]
> > > I'll be honest I'm not a fan of the idea and find it quite pointless.
> > > > Is your feature request related to a problem? Please describe it
> > > > A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.
> > > 
> > > 
> > > If this is the problem, then why not just add the option to sort videos by date added and in ascending/descending order. This is something I am already opening a request for, and it doesn't bloat the app with pointless features.
> > > #5201
> > 
> > 
> > That isn't as convenient as a way to upvote/downvote
> 
> It isn't, but liking/disliking is a pointless feature in an app designed to be account-less.

It's a local feature like the subscribing and lets you keep track of videos you like. If you don't like it then don't use it

**Comment by ggdorman** [comment]
> > > > I'll be honest I'm not a fan of the idea and find it quite pointless.
> > > > > Is your feature request related to a problem? Please describe it
> > > > > A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.
> > > > 
> > > > 
> > > > If this is the problem, then why not just add the option to sort videos by date added and in ascending/descending order. This is something I am already opening a request for, and it doesn't bloat the app with pointless features.
> > > > #5201
> > > 
> > > 
> > > That isn't as convenient as a way to upvote/downvote
> > 
> > 
> > It isn't, but liking/disliking is a pointless feature in an app designed to be account-less.
> 
> It's a local feature like the subscribing and lets you keep track of videos you like. If you don't like it then don't use it

But why do you want local rating? It doesn't contribute to the like/dislike rating of the video online, it creates extra work the developer to add a pointless feature that does something you can already do (using playlists). Why complicate the app unnecessarily?

**Comment by HTSamurai** [comment]
> > > > > I'll be honest I'm not a fan of the idea and find it quite pointless.
> > > > > > Is your feature request related to a problem? Please describe it
> > > > > > A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.
> > > > > 
> > > > > 
> > > > > If this is the problem, then why not just add the option to sort videos by date added and in ascending/descending order. This is something I am already opening a request for, and it doesn't bloat the app with pointless features.
> > > > > #5201
> > > > 
> > > > 
> > > > That isn't as convenient as a way to upvote/downvote
> > > 
> > > 
> > > It isn't, but liking/disliking is a pointless feature in an app designed to be account-less.
> > 
> > 
> > It's a local feature like the subscribing and lets you keep track of videos you like. If you don't like it then don't use it
> 
> But why do you want local rating? It doesn't contribute to the like/dislike rating of the video online, it creates extra work the developer to add a pointless feature that does something you can already do (using playlists). Why complicate the app unnecessarily?

So I can mark if I like a video so I can come back to it without having a huge playlist, and if I didn't like it I can press thumbs down, and then it could hide the video in search and other pages, and let me know if I somehow got onto it that I wouldn't wanna watch it

Sorry for the long wait for the reply by the way

**Comment by SameenAhnaf** [comment]
@litetex It should be closed in favor of #8323

**Comment by litetex** [comment]
@SameenAhnaf This issue is more specific so I will keep it open. Closing #8323 instead ;)

---

My statement to this issue:
I don't think it would be useful a lot.
I don't know how users behave exactly but I think most of us
a) watch new videos and then very unlikely watch them again ("what's new"-feed style) or
b) listen to same music/videos a lot

I don't know if this feature is really helpful in one of such cases...
Considering a) from above: Liking or disliking a video won't help you or anyone since you most likely watch that video ever again.
Considering b): Uhm... just use a playlist?

**Comment by opusforlife2** [comment]
> A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.

**Comment by opusforlife2** [comment]
> A normal playlist just doesn't do the job well, and it adds to the end of the playlist rather than the start.

Doesn't do the job well _how_? What is "Add to playlist" missing?

And appending to the start or end of a playlist is a separate issue. Open a new one.

**Comment by ChiefMikeK** [comment]
RFC @HTSamurai    
My 2¢ 
---
Having a 👍 or thumb 👎 change color would be misleading to users who would be thinking they are voting for it online.

I'd suggest instead adding a short **text-input-field** to the watched history database instead,  
if you long press either thumb opens a pop-up `add_a_reminder` ,
then the user could input an emoji(s), ★⯪☆☆☆ or, short text limited to about 8 characters 💡 🗯
