### ISSUE TITLE
Optional disable save playback position 

### ISSUE THREAD

**Issue by minsk21** [TeamNewPipe/NewPipe#5160]
This function interferes when listening to music.

**Comment by TobiGr** [comment]
I already noticed that, too. We should get TeamNewPipe/NewPipeExtractor#306 merged and save the playback position depending on the stream category.

**Comment by minsk21** [comment]
Does this feature recognize music videos from YouTube?  If not, is it possible to recognize by the length of the video?

**Comment by mhmdanas** [comment]
@minsk21 could you please open a new issue without removing the template and make sure you follow its instructions properly? Thanks!
