### ISSUE TITLE
Newpipe 0.20.6 Wifi switches off on Standby Lineageos 17.1

### ISSUE THREAD

**Issue by Starfoxfs** [TeamNewPipe/NewPipe#5164]
Hi,

i have issues with Wifi disconnects with Newpipe 0.20.6 and Lineageos 17.1 20201213-nightly-klte on my Samsung Galaxy S5 KLTE SM G900F.

I Play Music with Newpipe and Switch it to Background Mode and disable the Display. It works for a while and then Music stopps playing.
It restarts after i re-enabling the Display and klick on the Sandbox in the middle of the Display, at this time Wifi re-enabling.

I think it´s a problem with Wifi Standby ?

I don´t know it´s a Newpipe or a Lineageos issue ?!?

**Comment by Singh00427** [comment]
stop no massageSent from my Huawei phone-------- Original message --------From: Starfoxfs <notifications@github.com>Date: Sun, 13 Dec 2020, 11:08 amTo: TeamNewPipe/NewPipe <NewPipe@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [TeamNewPipe/NewPipe] Newpipe 0.20.6 Wifi switches off on Standby Lineageos 17.1 (#5164)

Hi,

i have issues with Wifi disconnects with Newpipe 0.20.6 and Lineageos 17.1 20201213-nightly-klte on my Samsung Galaxy S5 KLTE SM G900F.

I Play Music with Newpipe and Switch it to Background Mode and disable the Display. It works for a while and then Music stopps playing.

It restarts after i re-enabling the Display and klick on the Sandbox in the middle of the Display, at this time Wifi re-enabling.

I think it´s a problem with Wifi Standby ?

I don´t know it´s a Newpipe or a Lineageos issue ?!?

**Comment by mhmdanas** [comment]
@Starfoxfs please open a new issue without removing the template and don't forget to follow its instructions properly. Thanks!
