### ISSUE TITLE
Hide / disable recommendations

### ISSUE THREAD

**Issue by Zambito1** [TeamNewPipe/NewPipe#5173]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

I would like to be able to disable video recommendations, including the trending page seen at launch, and related videos shown when viewing a video. I personally would be okay with these areas being left blank when this option is turned on.

I find YouTube recommendations and trending videos to be distracting, and sometimes emotionally manipulative. I use a Firefox extension to block recommendations and trending videos when I use YouTube in my browser, but when I use the NewPipe app I currently cannot avoid recommendations.

I would only like to see videos that I have directly searched for, and hiding recommendations makes it easier for me to do that.

**Comment by vkay94** [comment]
There shouldn't be an option necessary.

>I would like to be able to disable video recommendations, including the trending page seen at launch

Go to _Settings -> Content -> Content of main page_ and removing the trends page.

>and related videos shown when viewing a video.

Simply stay at the comment page, the app remembers it. So as long as you don't swipe you won't see recommendations at all.

**Comment by B0pol** [comment]
Settings -> content -> show next and similar videos

**Comment by Zambito1** [comment]
Thank you for the tip! That worked for hiding recommendations on videos.

In case someone runs into this in the future and finds this issue, here is how the trending page can also be hidden:

Settings -> Content -> Content of main page -> Swipe "Default Kiosk" section to delete it. The + button can be used to add a blank page in its place.
