### ISSUE TITLE
Videos in playlists not visible

### ISSUE THREAD

**Issue by phmiusq** [TeamNewPipe/NewPipe#5174]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Play a playlist with 100+ videos and view the queue (or add the queue to a new playlist to see number of videos)

### Actual behavior
Only the first 100 videos are visible in the queue

### Expected behavior
Seeing all videos present in the queue

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
@phmiusq This is working for me. When I scroll to the end of the queue, it loads a batch of new videos and shows them. Perhaps we could get a screen recording?
