### ISSUE TITLE
what about including sponsor skip api  

### ISSUE THREAD

**Issue by gursewakk** [TeamNewPipe/NewPipe#5179]
So the newpipe app for android must have the ability to skip sponsor content on a video automatically. The website of API for sponsor block is https://sponsor.ajay.app/.

**Comment by mhmdanas** [comment]
This was requested before (#2554) and was decided against. If you want this feature, you can use [this fork](https://github.com/polymorphicshade/NewPipe). Also, please don't remove the template next time you open an issue. Thanks!
