### ISSUE TITLE
[Feature request] Option to select quality depending if you are with wifi or 3/4G

### ISSUE THREAD

**Issue by logos88** [TeamNewPipe/NewPipe#518]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hi! You are doing a great work with Newpipe lately! I think it could be interesting to been able to select the quality depending to where you are connected. For instance, if I am using my 4G data I'd prefer 360p to not consume so much, but if I am with my wifi I'd prefer 1080p since I don't care of the size anymore

**Comment by theScrabi** [comment]
I'ts due to @mauriciocolli he is doing the great job :)

I keep your suggestion in mind :)

**Comment by Wiredframe** [comment]
Would be really helpful, just burned 200MB for 2 videos on LTE ^^

**Comment by theScrabi** [comment]
ouch xD

**Comment by B0pol** [comment]
close this, it was fixed by #1339
