### ISSUE TITLE
paused background audio/pop-up video re-enables itself after another audio process is terminated

### ISSUE THREAD

**Issue by oncle-anatole** [TeamNewPipe/NewPipe#519]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hello,

Since 0.9.3 it seems that paused background audio or paused poped-up video re-enables themselves after another process involving the audio stack is terminated.
In concrete terms: 
- I start playing a video on background audio with newpipe, I pause it, then I play a song on my stock music player, I eventually close my music player (terminating the process, not letting it run on background) > NewPipe's background audio immediatly re-enables itself
- another example : with a paused background audio, I end a call > ditto, NewPipe re-enables itself
- With my phone's notification profile set to ring on notification reception, paused NewPipe background audio re-enables itself just after my phone receives an audible notification

This is happening on a 6.0.1 based OEM rom (ZTE's MiFavor).

**Comment by theScrabi** [comment]
Confirmed
