### ISSUE TITLE
A feature to edit download parameters after pausing download

### ISSUE THREAD

**Issue by GordonMul** [TeamNewPipe/NewPipe#5194]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

A feature to edit download parameters (the number of threads) after pausing downloading videos. This will help downloading in different network conditions. 

#### How will you/everyone benefit from this feature?

Tweaking network options shall aid in poor network conditions.

**Comment by ggdorman** [comment]
This is quite an obscure feature. What issues are you having that would be solved by this feature?
