### ISSUE TITLE
Add Yatse remote to the open in Kodi option 

### ISSUE THREAD

**Issue by Fatcakes** [TeamNewPipe/NewPipe#5196]
Yatse is a better remote than Kore, and is used at least by the same amount of people. Anyway to get that option integrated into the button as all that shows up for me currently is more and I have both remotes installed.

**Comment by mhmdanas** [comment]
Can't happen because Yatse is not free software. See https://github.com/TeamNewPipe/NewPipe/issues/2157#issuecomment-467002113. For a workaround, see https://github.com/TeamNewPipe/NewPipe/issues/2157#issuecomment-468031789.
