### ISSUE TITLE
No long able to open playlists

### ISSUE THREAD

**Issue by dpearson2182** [TeamNewPipe/NewPipe#5199]
In previous versions you were able to send a playlist link from youtube into Newpipe and were given the prompt to select how you would like to open the media. The current version says "could not recognize Url" hoping this is fixed soon as it is the main way I use the app.

Using newest version 20.6
Device info
One plus 6t Beta 35

**Comment by mhmdanas** [comment]
Could you please open a new issue without removing the instructions in addition to following its instructions properly? Thanks!
