### ISSUE TITLE
Touching the back arrow results in going back to the blank start screen

### ISSUE THREAD

**Issue by oncle-anatole** [TeamNewPipe/NewPipe#520]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hello,

Since 0.9.3 it seems that touching the app-integrated back arrow on the top-left when browsing through videos results in going back to NewPipe's blank start screen instead of the actual previous screen/activity. This doesn't happen when touching the navbar's back button though, it correctly results in going back to the last screen displayed.

I'm using a 6.0.1 based OEM rom (ZTE's MiFavor)

**Comment by theScrabi** [comment]
This is wanted behavior. The arrow in the toolbar should bring you back to the beginning. The hardware back button of you device however should bring you back one step.

**Comment by wb9688** [comment]
@theScrabi: Reading [Navigation - Patterns - Material design guidelines](https://material.io/guidelines/patterns/navigation.html#navigation-up-back-buttons), I don't think that's wanted behaviour:
>The Up button returns users to the previous screen they viewed. It navigates upward in the app’s hierarchy until the app’s home screen is reached.

**Comment by theScrabi** [comment]
Hm in some sense you are right, but it seems to be more complicated:
https://developer.android.com/design/patterns/navigation.html

**Comment by mauriciocolli** [comment]
If the user come from the search (searched something and went to other videos), we should go to the search, and if he came from another app, to the main screen.

**Comment by tgp1994** [comment]
I agree, I noticed this new behavior after the update and I don't find it especially desirable. If I came from an app to watch a YouTube video, I don't want to have to press a button more times than before to get back to what I was doing. I think you used to be able to get back with just one or two presses?

**Comment by bisam** [comment]
I found this rather confusing and annoying. I don't think the hardware and software "back" button should have a different functionality. If, it should be obvious. Right now I just get annoyed if I accidentally press the new-pipe back button and I have to enter my search string again.

Actually I think this button is useless. If I want to search something else I click on the "X" near the search bar. If I want to go back, I press the back button on my phone.
