### ISSUE TITLE
No download option on some videos

### ISSUE THREAD

**Issue by dewijones92** [TeamNewPipe/NewPipe#5205]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to this video in newpipe https://youtu.be/-DZocuLlFgE
You will not see the "Download" option. **This error can not be reproduced reliably.**

### Expected behavior
I should be able to see the download button

### Screenshots/Screen recordings
https://lh3.googleusercontent.com/-8C9kTTUZ1-I/X9seOw_NVFI/AAAAAAAAb68/IdZNf7IlJ3kIlGNAmVcThCNyA2Pkz4naACK8BGAsYHg/s0/2020-12-17.png

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Blackview A80 pro

Many thanks 😊

**Comment by vkay94** [comment]
The problem is that the app is handling this video as a livestream (see the LIVE indicator) even if it's already finished. Seems to be a rarity, I can't reproduce it with other finished livestreams of this and other creators at least.

**Comment by dewijones92** [comment]
@vkay94 
btw in the instances when this bug occurs I can download just fine with youtube-dl FYI
Many thanks

**Comment by Stypox** [comment]
Yeah, this is an issue with finished livestreams, which will be supported only after HLS/DASH is implemented, so let's stick to that issue
