### ISSUE TITLE
Show Media.ccc.de most recent uploads

### ISSUE THREAD

**Issue by yoshimo** [TeamNewPipe/NewPipe#5206]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
The media.ccc.de section should have a list of the most recent uploads on the first page. The news tab is empty and seems to be rather for subscriptions

**Comment by shivasagarrao** [comment]
What is media.ccc.de? How is it different from YouTube?

**Comment by TobiGr** [comment]
https://media.ccc.de is the media platform of the Chaos Computer Club. It mostly contains recordings of talks
