### ISSUE TITLE
Newpipe Video Download folder instead of downloading to phone gallery 

### ISSUE THREAD

**Issue by Newpipeuser** [TeamNewPipe/NewPipe#5207]
Sent from my Galaxy

Hello I got a suggestion for newpipe can you please add a dowload folder for videos instead of downloading them to the gallery and wasting storage space in update 0.20.7

**Comment by c-shubh** [comment]
Follow contribution guidelines:

https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md

**Comment by mhmdanas** [comment]
@Newpipeuser no storage space is being wasted. Allowing choosing the download directory is possible, but it won't help decrease the space used in any way. Also, if you still want this feature, could you please open a new issue with the template properly filled? Thanks!
