### ISSUE TITLE
Allow "What's New" option for "Content of main page" to filter to specific Channel Groups

### ISSUE THREAD

**Issue by MasterEric** [TeamNewPipe/NewPipe#5209]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I did not find a duplicate for this issue when searching, and I could not find this option in the app.

The basic concept is that in the Settings -> Content -> Content of main page menu, adding a "What's New" tab would display an additional menu. This would allow you to select between "All" or one of your configured channel groups.

Selecting the channel group will create a new tab, whose icon is the configured icon for the channel group, and which has the same "filtered What's New" display as if the user navigated to the Subscriptions tab and selected the channel group.

#### Is your feature request related to a problem? Please describe it

The current alternative in the user interface is to navigate to Subscriptions -> Channel Groups and click the relevant channel group every time I want to view a different channel group. This is slower and not integrated with the customizable tab-based main view.

#### How will you/everyone benefit from this feature?

The end result would allow the user to create several channel groups, then set the tabs of their main page to be those channel groups, allowing them to switch channel groups by merely swiping between tabs.

An example use case is that the tabs could be differentiated by interest, and the user could view the channel groups of those interests conveniently on the main page.

**Comment by Stypox** [comment]
#3559

**Comment by MasterEric** [comment]
Thank you, sorry I couldn't find this when attempting to search for it.
