### ISSUE TITLE
Duplicates on Playstore

### ISSUE THREAD

**Issue by prateekmedia** [TeamNewPipe/NewPipe#5213]
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### Steps to reproduce
1. Go to this link https://play.google.com/store/apps/details?id=com.yancedev.allvideodownloader 
2. Press on Report button from three dot menu
3. Swipe down to Copycat option and done

This app had copied everything from newpipe v0.19 or so and he has published it on play store after removing the download feature from YouTube category and added two more site Like Facebook and Instagram to download from.

I think that he also has not disclosed the source as the GPL-v3 states + He had advertisement on it.

## They are everywhere

Same goes for https://play.google.com/store/apps/details?id=you.tube.vanced this one uses new 0.20. Something version as base

Also note that the both are having comments parsing issue as the old newpipe.

https://play.google.com/store/apps/details?id=com.utube.videotube.vanced.kit

#### Mostly all apps that uses YouTube vanced/newpipe in their tags are based on newpipe and they are also running ad's or in app purchases

**Comment by dAtA-TRoN** [comment]
Reported. Keep up the good work 😊!

**Comment by Stypox** [comment]
Plese keep everything in #539 ;-)
