### ISSUE TITLE
Requesting more than 100 videos loaded in a playlist at a time

### ISSUE THREAD

**Issue by runawayhitchhiker** [TeamNewPipe/NewPipe#5216]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Hello team! I wanted to say that I really appreciate the app.
My request is more than 100 videos loaded on a playlist at a time. When I open the background player with a long playlist, only the first 100 videos are initially loaded in the play queue. I have to scroll down again and again as videos load in 100 at a time to load the whole playlist. I would like all the videos in the playlist to appear immediately in the play queue.

#### Is your feature request related to a problem? Please describe it

The play queue only loads 100 videos intially, and only 100 more every time I scroll all the way down the queue.

#### How will you/everyone benefit from this feature?

This feature is necessary because if I want to shuffle a playlist, the playlist only shuffles and plays the first 100 videos in the playlist, rather than the whole playlist. It is a minor inconvenience to have to load the whole playlist manually, 100 videos at a time, to be able to shuffle the whole playlist.

**Comment by c-shubh** [comment]
Related #875

**Comment by Stypox** [comment]
Closing in favour of #875
