### ISSUE TITLE
Playlist queue functions incorrectly, only plays 1st video then permanently buffering of the video is duplicate.

### ISSUE THREAD

**Issue by sqtvrnqliq** [TeamNewPipe/NewPipe#5220]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any playlist that has a duplicate after the original video.
2. Play it in background or with play all feature.
3. Wait until the 1st video is over or fast forward to the duplicated video.

### Actual behaviour

Next queued video will fail to load and will be stuck on a buffering hourglass symbol.

### Expected behavior

The duplicate video will play as it normally should.

### Screenshots/Screen recordings

I created this account solely for this bug since I've realised it's been here since around the 0.20.2 build. Please be patient if I don't understand anything as I'm not the brightest when it comes down to coding and coding terminology. I also did try checking for duplicate problems but the closest ones didn't list the problem that I have.

### Device info

 - Android version/Custom ROM version: 9
 - Device model: Samsung J5 (2017)

**Comment by shivasagarrao** [comment]
>  I am using the latest version - x.xx.x

Specify the version you are using.

I'm currently using 0.20.6 version. Play all or Play in background both are working for me in a playlist.

**Device info**

- Android version: 6.0.1

- Device model: Redmi Note 3

**Comment by sqtvrnqliq** [comment]
I'm also using the 20.6.0 ver, I suppose I forgot to put that down.
