### ISSUE TITLE
Why functionality is gone?

### ISSUE THREAD

**Issue by Flashwalker** [TeamNewPipe/NewPipe#5223]
Why does the functionality of the program continue to disappear?  
Why do developers worsen the application?  
Why do convenient options and functions disappear?  
What further deterioration of UX planned?

**Comment by opusforlife2** [comment]
ᕕ( ᐛ )ᕗ

**Comment by Flashwalker** [comment]
Playback in separated players  
Buttons to open/share not inside running playback  
Enque list of bookmarks enstead of enque only sekected one
