### ISSUE TITLE
Download Notification 

### ISSUE THREAD

**Issue by vrindavan** [TeamNewPipe/NewPipe#5226]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Right now it does not show up any progress of the current download going on, it needs clicking upon to see the details that's why if it is possible then it would be good to see the current download progress in the notification itself and also that how many downloads are currently in the queue

**Comment by SameenAhnaf** [comment]
@litetex This issue addresses the key aspect of https://github.com/TeamNewPipe/NewPipe/issues/3332. So, this issue should be closed.
