### ISSUE TITLE
Search, add and play public playlists

### ISSUE THREAD

**Issue by ewan86** [TeamNewPipe/NewPipe#523]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

On you tube there are public playlists, such as full albums with all the separate tracks. If you could search these and play in the background so auto forwards to the next song in playlist would be a great feature.

**Comment by ewan86** [comment]
On you tube there are public playlists, such as full albums with all the separate tracks. If you could search these and play in the background so auto forwards to the next song in playlist would be a great feature.

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/377

**Comment by ooyellow58** [comment]
How to access the playlists
