### ISSUE TITLE
Streamingfailure

### ISSUE THREAD

**Issue by andike82** [TeamNewPipe/NewPipe#5234]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by shivasagarrao** [comment]
@andike82 What's your issue?

**Comment by mhmdanas** [comment]
@andike82 we can't do anything without any info. Could you edit your issue with the needed info? Thanks!

**Comment by andike82** [comment]
{"user_action":"requested stream","request":"https://www.youtube.com/watch?v=H_9Wn_LzJQo","content_language":"de-AT","content_country":"AT","app_language":"de_AT","service":"YouTube","package":"org.schabi.newpipe","version":"0.20.1","os":"Linux motorola/kane_reteu/kane_sprout:10/QSA30.62-33/c150f:user/release-keys 10 - 29","time":"2020-12-21 07:24","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: YouTube did not provide player config even after three attempts\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:664)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14935)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\n"],"user_comment":""}

**Comment by mhmdanas** [comment]
It appears you are using an outdated version of NewPipe (0.20.1). Upgrading to the latest version (0.20.6) should fix the issue (https://github.com/TeamNewPipe/NewPipe#updates).

**Comment by akien-mga** [comment]
I landed here searching for the same issue. 0.20.1 is the latest version on Fdroid - is it no longer maintained there? If so, I would advise getting it removed from Fdroid.

Then, what's the recommended distribution? Manual install of APK from GitHub Releases?

**Comment by mhmdanas** [comment]
It isn't that it is not maintained. There is an issue causing this, and we're trying to fix it. The recommended methods are downloading the APK from GitHub releases and using the custom F-Droid repo (see (https://github.com/TeamNewPipe/NewPipe#updates). The GitHub and custom repo APKs can't be installed over F-Droid ones. You will have to export your database, uninstall the app, install the most recent version, and then import the database. Unfortunately, there were a fewl reports of issues importing a database exported from 0.20.1 on a recent version, so take care.

**Comment by andike82** [comment]
Thank you, that worked well.

Mohammed Anas <notifications@github.com> schrieb am Mo., 21. Dez. 2020,
08:36:
