### ISSUE TITLE
Some thumbnails won't load until clicked on

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5242]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go on the What's New feed
2. Find a video with no thumbnail shown

### Actual behaviour

A video thumbnail doesn't show.

### Expected behavior

A video thumbnail *should* show

### Screenshots/Screen recordings

![IMG_20201221_100830](https://user-images.githubusercontent.com/71007160/102765432-83b6e180-4374-11eb-8f20-03ff3876ab8b.jpg)

### Logs

None are shown.

### Device info

 - Android version/Custom ROM version: Android 10 MIUI 11
 - Device model: Redmi 8

**Comment by shivasagarrao** [comment]
Check this option once
Settings > Content > Load thumbnails
Load thumbnails should be toggled on.

![Screenshot_2020-12-22-12-34-54-060_org schabi newpipe](https://user-images.githubusercontent.com/46630255/102859644-49237680-4452-11eb-81fc-57a9b7cb52bb.png)


**Additional:**
I also see from your screenshots video length isn't being displayed for all videos. If you want video lengths to be displayed disable fast mode.

Tap on three dots (top right corner) > Help > Disable Fast Mode

![IMG_20201222_124023](https://user-images.githubusercontent.com/46630255/102859921-e383ba00-4452-11eb-980e-c6eed690ce26.jpg)

**Comment by HTSamurai** [comment]
> Disabling fast mode might work.
> Tap on three dots (top right corner) > Help > Disable Fast Mode
> Video length will be displayed for all videos if we disable Fast Mode. But I don't know regarding thumbnails.
> 
> ![IMG_20201222_124023](https://user-images.githubusercontent.com/46630255/102859921-e383ba00-4452-11eb-980e-c6eed690ce26.jpg)

I have fast mode on because normal is too slow. thumbnails are on and most do load without clicking the video.

**Comment by mhmdanas** [comment]
@HTSamurai do all the thumbnails always load when fast mode is disabled? If so, this is expected behavior. I'll be closing this issue for now, but if even with fast mode disabled you get no thumbnails sometimes, please make a comment and I'll re-open this issue.
