### ISSUE TITLE
Xbox Support

### ISSUE THREAD

**Issue by ovz93br43v7** [TeamNewPipe/NewPipe#5249]
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

Most of the time I use my Xbox to watch Youtube videos but I'm really annoyed from so many ads -.-
Therefor I would like to use your app on my Xbox.

I considered to block the youtube ads with pihole for all devices inside my network but this is according to pihole team not possible. I would prefer a network wide solution when it is available. 

Could your filter technique somehow improve piholes ad blocking function for youtube or is a network wide use of new pipe filter technique somehow possible?!?

**Comment by mhmdanas** [comment]
We don't use any "filtering." We get the video without any ads. Actually, it would be much more difficult to put the ads back.

**Comment by ovz93br43v7** [comment]
Ok probably a misunderstanding. (language issue on my side)
I don't want to put back any ads.

I would like to use your app on my xbox, probably you can release it there also?!?

Additionally I explained that I use pihole to block most ads inside my network but this doesn't affect youtube ads. With "filtering" I meant you extract somehow the main video.
Could this technique to extract only the main video applied to all network devices which request a youtube video? (for example when it is not possible to install new pipe?)

**Comment by mhmdanas** [comment]
> I would like to use your app on my xbox, probably you can release it there also?!?

NewPipe is written for Android and can't be used on other platforms. However, its core, NewPipeExtractor, has no ties to Android, so it can be used on other platforms. However, I am not sure how feasible writing Java programs for the XBox would be.

> Could this technique to extract only the main video applied to all network devices which request a youtube video? (for example when it is not possible to install new pipe?)

I don't think so.
