### ISSUE TITLE
Song list

### ISSUE THREAD

**Issue by FrankNapster** [TeamNewPipe/NewPipe#5261]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by FrankNapster** [comment]
When I select the "songs list" after chosing the autor/singer/band, the "Song list" don't work. Please check and solve the issue ASAP. 
Thanks.

**Comment by kubo6472** [comment]
Please fill in the version and the template. You can edit the comments and delete your own :) @FrankNapster

**Comment by FrankNapster** [comment]
When I select the "songs list" after chosing the autor/singer/band, the "Song list" don't work. Please check and solve the issue ASAP. Newpipe version 0.20.6.
Please look at the attached files, I think it is clear now.
Android version: Android 10
Hardware version: 5.0
Model version: TA-1043
NOKIA 6.1

![Screenshot_20201224-112401](https://user-images.githubusercontent.com/76540508/103083272-4bb1d780-45dc-11eb-9ac5-4780c527d0c3.png)
![Screenshot_20201224-112421](https://user-images.githubusercontent.com/76540508/103083276-4c4a6e00-45dc-11eb-9fe9-1fd7711a2d0a.png)
![Screenshot_20201224-112439](https://user-images.githubusercontent.com/76540508/103083277-4ce30480-45dc-11eb-8ead-d7a4bed1da6e.png)
![Screenshot_20201224-112454](https://user-images.githubusercontent.com/76540508/103083278-4d7b9b00-45dc-11eb-8525-9e1feccbfa46.png)

Thanks.

**Comment by TobiGr** [comment]
That's a duplicate.
Will be fixed by https://github.com/TeamNewPipe/NewPipeExtractor/pull/484

**Comment by kubo6472** [comment]
Please try the APK in #5245

**Comment by FrankNapster** [comment]
I try the APK in #5245 release 0.20.7 but the problem remain the same. Please let me know if you can fix the issue in the next version. 
This app is fantastic and I hope will use it properly  like before. 
Thanks

**Comment by TobiGr** [comment]
the APK in #5245 does not yet contain the fix

**Comment by kubo6472** [comment]
Okay, I just missed Tobi's comment by a few seconds, look at the PR he links in the extractor repo, and try that instead. Since it isn't merged, it probably won't make it into the release yet, but what do I know. Maybe they'll merge it in time.

**Comment by kubo6472** [comment]
Right, the same happened again :D

**Comment by FrankNapster** [comment]
I tried also with the #5246. Nothing.

Il gio 24 dic 2020, 12:06 Jakub <notifications@github.com> ha scritto:

**Comment by kubo6472** [comment]
> That's a duplicate.
> Will be fixed by [TeamNewPipe/NewPipeExtractor#484](https://github.com/TeamNewPipe/NewPipeExtractor/pull/484)

@FrankNapster this one has app-debug.zip try this instead please.

**Comment by FrankNapster** [comment]
Sorry I don't understand what I have to do? I downloaded the app-debug.zip
but when I try to open this one don't do anything. Sorry for my bad
english!

Il gio 24 dic 2020, 12:30 Jakub <notifications@github.com> ha scritto:

**Comment by kubo6472** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/files/5736791/app-debug.zip this is a direct link copied from that PR, feel free to compare it. You download this, unzip this and click install. Then try the search there.

**Comment by FrankNapster** [comment]
Ok now it work good like before!! So you will put on the next release this
version of app debag? For example newpipe version 0.20.7 with this
implementation? Let me now please and thanks a lot!!

Il gio 24 dic 2020, 12:51 Jakub <notifications@github.com> ha scritto:

**Comment by TobiGr** [comment]
Yes, that fix is planned for 0.20.7, but still needs to be reviewed

**Comment by FrankNapster** [comment]
Ok, I hope It will come soon better than before. Now there Is the song list
but there other problems: when I go to open the song and press "in the
background" it asks me whether to open it with Google play music or you
tube music and it doesn't open automatically as before.  When I quit the
app to do something else, playback stops.  The music player is no longer
the same as before and there is no external player for when the phone is in
standby even if in the options I have selected "show external audio
player".  I hope it is because it is the app-debag and in the updated
version that you will do everything as before, obviously including the
various lists of artists.  Thanks.

Il gio 24 dic 2020, 13:10 Tobias Groza <notifications@github.com> ha
scritto:

**Comment by FrankNapster** [comment]
Forget it!  I changed some options in the app.  Now the reader is as
before.  I look forward with joy to the new release!

Il gio 24 dic 2020, 13:24 Francesco Nappi <franknappi91@gmail.com> ha
scritto:
