### ISSUE TITLE
[Feature request] Improved usability on FireTV Stick

### ISSUE THREAD

**Issue by ovz93br43v7** [TeamNewPipe/NewPipe#5262]
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I would like to use your app on my FireTv Stick. It runs on the FireTV stick but it is a bit hard to control with the remote control, some buttons I can't reach (for example sub titles). And the videos always start in windows mode so you have to go with the remote to the maximize button.

**Comment by mhmdanas** [comment]
This issue is a bit too broad. Mind making an issue for each of your complaints if it doesn't already exist? Thanks!
