### ISSUE TITLE
Can't pause video while buffering

### ISSUE THREAD

**Issue by Rult** [TeamNewPipe/NewPipe#5263]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

0. Use an unstable Internet connection
1. Open any video
2. Wait some time for the video to go buffering
3. Tap on the screen to access the pause button and tap on it

### Actual behaviour

Pause button doesn't work and video continues to play the moment buffering is done.

### Expected behavior

Video is paused, so you can wait until more video chunks are loaded.

### Device info

 - Android version/Custom ROM version: 6.0.1
 - Device model: Xiaomi Redmi 4

**Comment by HTSamurai** [comment]
Same problem here

**Comment by Douile** [comment]
Still an issue in 0.21.0

**Comment by Rult** [comment]
The issue is still here in 0.21.1. Someone please check it too.

**Comment by opusforlife2** [comment]
@Rult The fix wasn't included in 0.21.1. It is intended to be released in 0.21.2. You can test the release candidate by checking out the pinned Release issue.
