### ISSUE TITLE
Tutorial explaining features when you first install NewPipe like SkyTube

### ISSUE THREAD

**Issue by shivasagarrao** [TeamNewPipe/NewPipe#5267]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I need a small tutorial which explains that if swipe up/down we can control brightness and volume and also if we double click in middle it pauses the video.

#### Additional context

[SkyTube](https://github.com/ram-on/SkyTube) app does this as I requested.

Video of SkyTube app tutorial

https://user-images.githubusercontent.com/46630255/103104135-830b9d00-464b-11eb-949b-a154932cc1d5.mp4

#### How will you/everyone benefit from this feature?

This is generally useful for first time users who are naive and don't like tinkering all the options available on NewPipe.

**Comment by c-shubh** [comment]
Like these #859?

**Comment by shivasagarrao** [comment]
Yes it's similar issue.
