### ISSUE TITLE
NewPipe should really fix these shortcomings

### ISSUE THREAD

**Issue by Oizaro** [TeamNewPipe/NewPipe#5269]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

- After many months and versions, NewPipe is still not able to show a more detailed options to search a video...meanwhile also the YouTube website offer this possibility: <img src="https://i.ibb.co/CnnV1DX/Cattura.png">

- Ok comments are available, but really I not understand why somebody should just read the main ones without can see the answers (again...like on website).

- Switch between only audio and video plaback should happen smoothly, without interruptions or previous second (of video) repetition.

**Comment by shivasagarrao** [comment]
Filtering of a video is also present in YouTube app.

Filtering of a video issue [#110](https://github.com/TeamNewPipe/NewPipe/issues/110) is open  since 2015.

**Comment by mhmdanas** [comment]
@Oizaro thanks for taking the time to open an issue! The checklist is not optional, so when if you open an issue again, please make sure to follow it. As for your suggestions,  every one of them has an existing issue:
- Search filters: #110 (like @shivasagarrao said)
- Comment chains: #2277
- Interruptions when switching player: #5016

**Comment by Oizaro** [comment]
> @Oizaro thanks for taking the time to open an issue! The checklist is not optional, so when if you open an issue again, please make sure to follow it. As for your suggestions, every one of them has an existing issue:
> 
> * Search filters: #110 (like @shivasagarrao said)
> * Comment chains: #2277
> * Interruptions when switching player: #5016

I will, but I promise nothing. Searching an already opened request is not easy in this "chaos".

**Comment by mhmdanas** [comment]
I get that finding duplicates is not easy, but taking one or two minutes at least to check for existing issues will help immensely in most cases. However, when I said you should follow the checklist, I primarily meant that you should open a separate issue for each feature request, not aggregate them like you did here.

**Comment by Oizaro** [comment]
> I get that finding duplicates is not easy, but taking one or two minutes at least to check for existing issues will help immensely in most cases. However, when I said you should follow the checklist, I primarily meant that you should open a separate issue for each feature request, not aggregate them like you did here.

Yeah, understandable...

P.S: The third check is not optional? I mean...is not something can be checked or not, based on intentionality of who make a request?

**Comment by mhmdanas** [comment]
No, every part of the checklist should be followed. We use the checklist here as a kind of "TODO list."
