### ISSUE TITLE
suggestqueries.google.com "Network error"

### ISSUE THREAD

**Issue by Lvl4Sword** [TeamNewPipe/NewPipe#527]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Blocking suggestqueries.google.com within the HOSTS file ( through AdAway, manually, PiHole, or otherwise ) makes the program believe there's a Network error.

You can type one or two letters a time in the search bar before it stops you and says Network error.

Doesn't remove what you typed, but it's **INCREDIBLY** annoying.

**Comment by theScrabi** [comment]
I can't confirm, I'm using AdAway myself, but I never hat any trouble before.

**Comment by mauriciocolli** [comment]
But why in the world would you block this host (try to put that in the whitelist if it is from some hosts list)? It host ads?

The error raised when fetching the suggestions serves as a detection for a network error, because the only possible cause is through some network error.

**Comment by Lvl4Sword** [comment]
@theScrabi It's not default, I've added it myself
@mauriciocolli Not a fan of Google suggesting things to type
There are better ways to prove a network issue. There's a permission for that..

**Comment by mauriciocolli** [comment]
The most effective way of proving that there's no connection is, well, trying to connect to an host (not depending in checking if some interface is connected, etc.).

But anyway, I can add an option to disable the suggestions in the search bar, what do you think?

**Comment by theScrabi** [comment]
Well a Network issue always occures if data could not be gathered (maybe we should not call it Network error than).

**Comment by theScrabi** [comment]
Yea why not. :)

**Comment by Lvl4Sword** [comment]
Sounds good :smile:
