### ISSUE TITLE
Content doesn't load on mobile data

### ISSUE THREAD

**Issue by verycoolperson** [TeamNewPipe/NewPipe#5279]
### Checklist

- [x] I am using the latest version - 0.20.7
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Be on mobile data not WiFi
2. Let a video play in the background for around 3-4 minutes
3. Open Newpipe and open a video or search something

### Actual behaviour

When you open the app again things like search results or videos don't load

### Expected behavior

Content is expected to load normally

### Device info

- Android version/Custom ROM version: Android 10
- Device model: Samsung Galaxy A30s

**Comment by verycoolperson** [comment]
Also turning off mobile data then back on again seems to fix this issue until you leave things again in the background

**Comment by TacoTheDank** [comment]
Hello, does this issue still occur on the latest version?
