### ISSUE TITLE
play without full screen

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#528]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

-------------

it will nice to play video without full screen.

**Comment by theScrabi** [comment]
Please give a small explenation.

**Comment by cwgt** [comment]
when I click on play button it looks like this 

![screenshot_2017-05-03-21-45-27](https://cloud.githubusercontent.com/assets/17215321/25669037/3b254164-304a-11e7-8718-71f903825173.png)

but I like play this way (I know popup will be resizable.)

![screenshot_2017-05-03-21-46-25](https://cloud.githubusercontent.com/assets/17215321/25669094/62cfc072-304a-11e7-8724-6afdf04cdec6.png)

**Comment by theScrabi** [comment]
Maybe it's because of the content of the video.

**Comment by cwgt** [comment]
I played some videos but all of them works this way. (I am using android 4.2.2)

**Comment by cwgt** [comment]
@theScrabi

I was trying to build it myself (not a Android dev) with AIDE.

but it can not find 'APPLICATION_ID' and 'VERSION_NAME' (not a member of BuildConfig). how to generate them?  (tried to add `buildConfigField` with no luck)

**Comment by theScrabi** [comment]
Hm strange, version code and version name can be found [here](https://github.com/TeamNewPipe/NewPipe/blob/master/app/build.gradle#L11)

Did you try to build the app without the IDEA Ide? You could try to build it via commandline:
`[dir/to/NewPipe/root: ]$ ./gradlew assemble`

**Comment by cwgt** [comment]
I was trying to build it on android (AIDE is a android app).

it seems, it was a problem of AIDE
 (https://plus.google.com/112950748876729349038/posts/8wKAAqaqVEm).

**Comment by theScrabi** [comment]
Please use your computer to build it.

**Comment by SkyzohKey** [comment]
@theScrabi I guess he's wanting to say that the player should be able to play the video without going fullscreen as it currently do. Something similar to how YouTube official app handle that. :)

**Comment by cwgt** [comment]
@SkyzohKey exactly. I can get expected result by using resizable popup.

**Comment by SkyzohKey** [comment]
I'm working on this right now, you can expect a PR at the end of the day I guess.

**Comment by cwgt** [comment]
@SkyzohKey :smile:

**Comment by SkyzohKey** [comment]
OK it's almost ready. That's the first time I contribute to Java/Android code, I come from a C/Vala/PHP background so my code is probably really shitty but I hope it make @theSchabi to understand what I'm speaking about. 😂

**Comment by mauriciocolli** [comment]
We already got rid of this VideoView, take a look at the `player` package, you can find implementations of ExoPlayer that you can easily plug in the fragment.

**Comment by SkyzohKey** [comment]
@mauriciocolli Just copied some code from the actual player from `PlayVideoActivity.java` :/

**Comment by mauriciocolli** [comment]
@SkyzohKey that's the old player, just ignore it, look at the others for examples

**Comment by SkyzohKey** [comment]
Do you have an example file ?

**Comment by Zero3K** [comment]
Any news regarding the implementing of this suggestion?

**Comment by theScrabi** [comment]
What do you mean by that?

**Comment by noersetiawan** [comment]
So.. any news about this issue? Is playing without fullscreen will be implemented? Being worked on? Or simply "won't fix"?

**Comment by wb9688** [comment]
It currently isn't being worked on, since we're busy with more important
things, like improving playlist support.

**Comment by sucotronic** [comment]
I've reviewed de open PRs and seems that nobody is working just now on this. I could give it a try, just want to know that I'm not duplicating work ;)

**Comment by arihan-1560795** [comment]
Wanted to comment that playing videos in portrait mode without it switching to fullscreen so I may read comments/ look at other suggested videos would be really nice! A work around right now is to have the stream "pop up", but this isn't really elegant.

**Comment by Stypox** [comment]
#2907 @arihan-1560795
