### ISSUE TITLE
Could not import youtube subscriptions

### ISSUE THREAD

**Issue by MBZ-07** [TeamNewPipe/NewPipe#5285]
Hi, I've followed your guide here https://newpipe.net/FAQ/tutorials/import-export-data/#import-youtube to import my youtube subs to no avail.
I'm running Android 7.1, NexPipe Legacy 0.20.2 and NewPipe 0.20.1
My JSON file of 5.58KB size.

**Comment by TobiGr** [comment]
update to 0.20.7 and try again https://github.com/TeamNewPipe/NewPipe#updates
