### ISSUE TITLE
video does not work on my mobile

### ISSUE THREAD

**Issue by cwgt** [TeamNewPipe/NewPipe#529]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version

-------

video won't play on my mobile (android 4.2.2, mt6572). only audio works.
[SCR_20170503_170223.mp4.zip](https://github.com/TeamNewPipe/NewPipe/files/973097/SCR_20170503_170223.mp4.zip)

**Comment by cwgt** [comment]
`using old player` fixes this problem.

**Comment by mauriciocolli** [comment]
Can you try to play in `WebM` format? 

Change in the `Settings` the option `Preferred Video Format` to WebM, then choose the "WebM 360p" in the resolutions menu and press play.

**Comment by cwgt** [comment]
works with `WebM`.
(I also tried with `3GPP` but didn't work)

**Comment by mauriciocolli** [comment]
So it's a specific incompatibility with your device, we can't do anything.
