### ISSUE TITLE
Audio keeps stuttering on my phone

### ISSUE THREAD

**Issue by Kmambu** [TeamNewPipe/NewPipe#5290]
Device : Sony Xperia X
Android version : 8
Newpipe version : 0.20.7
Context : when playing videos on background mode
Problem : Sometimes, audio starts to stutter

Hi everyone, 
Just like I wrote above, the audio of my videos stutter from time to time when I play videos on background mode. When I try to switch to another player mode (PiP, or embedded player) the video keeps its audio track stuttering, which may indicate the issue is with the buffering. 

I don't know if the issue also appears when playing normal videos, at least I wasn't able to replicate the bug when playing a video using the normal player.

I've used Newpipe on at least 3 other phones and this is the first time I experience this bug. I already experienced it on this phone when I was still using version 0.19.x, so it did not appear when transitioning to 0.20.0 and later

**Comment by mhmdanas** [comment]
Thanks for opening an issue! Could you please open a new issue for this from the GitHub website using the bug template? Thanks!
