### ISSUE TITLE
I would like to see the sub comments and also want timestamps to work

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5291]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I would like to see the replies made by people in some comments. It would be amazing if you could do that. I would also like for comment timestamps to work. It would help in giving me the required clip that I want to watch in that video. Currently when I click a timestamp it sends me to youtube to that video and the place of timestamp in that video

#### How will you/everyone benefit from this feature?

It would help people to see the replies of the comments they made in youtube. :)

**Comment by anidealone** [comment]
I noticed quite a few versions back that the comments no longer load. Every video says no comments. Was that intentional or is something else going on?

**Comment by Thewisem** [comment]
Yeah about that timestamp, it works now buuuut it only works in pop up mode and not normal video mode ( Just saying although thanksmfor fixing it) :)

**Comment by mhmdanas** [comment]
@anidealone there was a bug preventing comments from loading, but it's fixed now. If it still doesn't work for you, try upgrading to the latest version.

@Thewisem there's [an issue to make timestamps seek in the main player](https://github.com/TeamNewPipe/NewPipe/issues/4241). For the comment replies, it was requested in #2277. Again, please don't ignore the template when opening an issue.
