### ISSUE TITLE
Instant pause/play.

### ISSUE THREAD

**Issue by ThomasLeigh** [TeamNewPipe/NewPipe#5297]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one feature request. I will open one issue for every feature I want to request.

Some time ago it was possible to pause / resume playing a video simply by one single tap on it. Now I need to tap it twice :( . Could it be possible to restore the previous ability to fantastically pause / resume playing by a single tap?

**Comment by Younes-L** [comment]
I agree, the same behaviour as YouTube app would be good. Now the control buttons disappear immediately after tapping "play"

**Comment by SameenAhnaf** [comment]
The same thing should happen for other activities on full screen too. There could be a 2 seconds break between choosing an action and automatically hiding the interface.

**Comment by tsiflimagas** [comment]
This has been fixed.

**Comment by SameenAhnaf** [comment]
@mhmdanas I think, this issue should be closed as @tsiflimagas suggested to.

**Comment by mhmdanas** [comment]
Does anybody face this issue anymore?
