### ISSUE TITLE
[Repository] Enable Discussions

### ISSUE THREAD

**Issue by Andre601** [TeamNewPipe/NewPipe#5298]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

This isn't directed to the product (the app) but more specifically the repository.
GitHub now has their Discussions feature in open Beta, meaning any public repo can have it enabled to try it out.

I strongly believe that it would be beneficial to have Discussions enabled in this repository.

But why should that be done is the question now, right? Well, the most obvious one would be to have a more central place to ask questions and get support.
While IRC sure is an option is not everyone a fan of it, nor do they want to create a (temp-)account just to ask a single question. And since this repo doesn't have a "Question" template for its issues is asking a question in the issue tracker also not really an option.

Discussions are kinda like StackOverflow questions, meaning authors of posts can select answers which in the end could help creating a large and healthy knowledge-base on GitHub itself.

Another benefit could be to make dedicated announcements which wouldn't take an issue or PR.

#### Is your feature request related to a problem? Please describe it

The "Problem" was described above, which is, that for support, you either have to create an issue which may get closed for not following the template, or you have to go to the IRC and create an account just to ask a question there with no real way to get an answer without registering an account (By that I mean getting e-mails or something when you were away and your question was answered in that time).

#### How will you/everyone benefit from this feature?

The benefits where mentioned before but I make a quick summary here:

- Allows a central place for asking questions/seeking support
- Can be used to create a knowledge-base
- Better place for making important announcements

**Comment by ChiefMikeK** [comment]
##FYI there is also this ⤵️

> https://www.reddit.com/r/NewPipe/

**Comment by Andre601** [comment]
That's true but same core issues persist: Not everyone wants to create a separate account just to ask one question that may not even get answered at all when it gets flooded away from unrelated posts.

**Comment by ajayyy** [comment]
IRC doesn't have accounts

**Comment by opusforlife2** [comment]
But it doesn't have a good way to access info either. You ask a question and it will get lost in the deluge a week later, and that's assuming you access it through Matrix or are running an always-on IRC client.

**Comment by Angelk90** [comment]
@mhmdanas, @Andre601  : Is there any news on this?

**Comment by mhmdanas** [comment]
Not really, and I don't see the need anymore; there's a question template now, so you can ask questions as an issue. I'm closing this, but if anybody still thinks this is not enough, feel free to make a comment.

**Comment by Angelk90** [comment]
@mhmdanas: In my opinion it is useful, let's consider that I wanted to discuss a part of the ui.
By opening a discussion one could deepen the discussion to arrive at ideas, and then open an issue where these ideas are collected and finally developed.

For example:
You could open a discussion for the video player ui.

**Comment by mhmdanas** [comment]
Would that not be solved by adding a discussion template for issues?

**Comment by Andre601** [comment]
Not everything can or even should be put through the issues system.
While I can see benefits of using issues (i.e. having everything at one place) does it lack features and options that Discussions do offer such as marking a response as an answer which may or may not end up as a result in search queries on Google and similar.
On issues would I need to not only find the one answering my question but also need to then find the comment that answers the question I have.

In addition can discussions, as Angelk mentioned, deepen certain conversations by having conversations for specific replies.

Like you can imagine the discussion structure as follows:
```
Question
  |
  |- Answer #1
  |    |
  |    |- Response #1
  |    |- Response #2
  |    |- ...
  |
  |- Answer #1
  |    |
  |    |- Response #1.
  |    |- Response #2
  |    |- ...
  |
  |- ...
```
And here for comparison a issue conversation:
```
Question
  |
  |- Answer #1
  |- Response #1
  |- Response #2
  |- Answer #2
  |- Response #1
  |- Response #2
  |- ...
```
As you can see do issues have a much more linear and strict line while discussions allow more in-depth conversations about stuff without it being lost in the timeline due to others posting their answers.

Again, I can see reasons for using issues, but they clearly lack options for building a Q&A base to provide commonly asked questions.
But truth be told, I don't care either way. I even forgot this issue existed to begin with...

**Comment by Angelk90** [comment]
@mhmdanas : What have you thought about doing?

**Comment by mhmdanas** [comment]
I personally don't think GitHub Discussions should be enabled, but I didn't want to pretend that my opinion is the official Team NewPipe position on the matter, so I asked the team to discuss this matter.
