### ISSUE TITLE
Swipe up on a video to go to full screen

### ISSUE THREAD

**Issue by verycoolperson** [TeamNewPipe/NewPipe#5299]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be really cool if we had a feature that when you swipe up on a video in portrait mode it would automaticaly go to fullscreen/landscape mode

#### Additional context

The feature that I am proposing is the exact same feature that the official youtube app has

#### How will you/everyone benefit from this feature?

I think it would make the whole video viewing experience feel a little bit more smooth since you could go to fullscreen and back only by swiping. Personally it kinda feels that this way I can navigate the UI a little faster or that I have a little bit more control idk. I understand that this feature isn't like anything huge but I think that little things like this make a difference :)

**Comment by Stypox** [comment]
This will not be implemented, as we decided to instead solve the problems with fullscreen another way, see #5459

**Comment by Poopooracoocoo** [comment]
Note: the official YouTube app has this gesture.
