### ISSUE TITLE
Screenshots need updating

### ISSUE THREAD

**Issue by PanderMusubi** [TeamNewPipe/NewPipe#530]
The screenshots are out of date. Please update these.

**Comment by TobiGr** [comment]
You are right. There is a discussion in context of the new website ([TeamNewPipe/website#13](https://github.com/TeamNewPipe/website/issues/13)).

**Comment by theScrabi** [comment]
Yea even the screencast I did for the new website whis is already two or three months old is obsolete already. :/ NewPipe shure changed a lot recently xD
