### ISSUE TITLE
limited search results

### ISSUE THREAD

**Issue by bingoxo** [TeamNewPipe/NewPipe#5300]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Search anything

i have the latest version 0.20.8 (i tried other older versions too still same issue) : getting exactly 20 search results no matter what i search for just like : https://old.reddit.com/r/NewPipe/comments/hxlm2c/searching_only_shows_limited_results/
 and https://old.reddit.com/r/NewPipe/comments/gwsysl/im_having_very_limited_number_of_search_results/
 
 works fine on a samsung phone i have , but i have the issue with my new phone (pixel 4 xl) , i tried uninstalling reinstalling deleting cache/data , but no luck

### Actual behaviour
Only 20 searches are shown

### Expected behavior
get as much as results as possible

### Screenshots/Screen recordings
The problem and the fix is here in the video
https://mega.nz/file/2FlVGKRC#mkS_Cwn9iXit1jo9nNTCicPqbY5pJRVqOwigt-9OEeg

my system default was Morocco (detected from ip) , changing to any country (including Morocco would fix the issue)

small note : Changing to Palestine doesn't do anything (it just gives you system default and thus didn't fix the issue , and is probably another issue itself)

### Device info

 - Android version/Custom ROM version: Android 11 GrapheneOS
 - Device model: Pixel 4 XL

**Comment by vkay94** [comment]
Aren't new results loaded at all? I just tried it and encountered that the loading indicator isn't showing up only - the next page is loaded as expected and I could scroll to new results (keep an eye on the list indicator on the right edge).

PS: Please don't delete the template - bug reports which don't follow the template are getting closed otherwise ;)

**Comment by TobiGr** [comment]
Please post a screenshot

**Comment by bingoxo** [comment]
I love the quick the responses guys , i managed to fix it though , so here is the video of the problem with the fix : https://mega.nz/file/2FlVGKRC#mkS_Cwn9iXit1jo9nNTCicPqbY5pJRVqOwigt-9OEeg

for some reason i ignore : changing the content country fixed it

**Comment by XiangRongLin** [comment]
@bingoxo in the video it shows the content country as system default. So what's the system default? Can you also add it to your initial post

**Comment by XiangRongLin** [comment]
I tried it with content country as Morocco and System Default (germany in my case i think) but both times it worked normally. I'm also running Android 11 so it should not be that.

**Comment by bingoxo** [comment]
> 
> 
> I tried it with content country as Morocco and System Default (germany in my case i think) but both times it worked normally. I'm also running Android 11 so it should not be that.

the problem is not the countries themselves , it's that the system default at the start is messing something up in my case , could be due to the ROM but i'm not sure

**Comment by rancidfrog** [comment]
I was having the same issue.
For some reason my default content country was set to:
![](https://i.imgur.com/4QQk7VV.jpg)
Which caused search to limit result to 20.
But, I changed it to
![](https://i.imgur.com/wnDefIb.jpg)
And now it searches for more as you scroll down.
Strange how default content country causes search to not search for more results on scroll down

**Comment by woheller69** [comment]
Same problem on my Samsung Galaxy Tab A7. Sometimes 19, sometimes 20 results. Changing country does not help, unfortunately.
Android 11.

**Comment by woheller69** [comment]
I found a possible reason for this. If I go into Android developer settings and change minimum screen width to a smaller value (in my case from 752 pixels to e.g. 400) everything is being displayed much larger. That large that less than 19 or 20 entries fit on one screen. And now I can scroll and scroll and more and more search results will be presented.

**Comment by woheller69** [comment]
I guess that also makes sense as the Pixel 4XL of @bingoxo has a very high number of pixels

**Comment by woheller69** [comment]
Increasing font size works as well

**Comment by woheller69** [comment]
without knowing the code OnScrollBelowItemsListener sounds like something that could be involved...

**Comment by woheller69** [comment]
probably related to #7638 

using list view instead of grid also works

**Comment by Stypox** [comment]
Yes, fixed by #7659
