### ISSUE TITLE
Backup preferences

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5302]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

I would love to have a backup for my bookmarks or subscription. It would help greatly. But it should be local backup file. An example is musicolet. When you uninstall and reinstall it, the preferences will still be there because it will be backed up locally.( Although its propietary software.). Would love to have a backup solution incase I accidently uninstall it :)

**Comment by mhmdanas** [comment]
You can already backup everything except downloads from "Settings > Content > Export database" and then import all that from "Settings > Content > Import database." If you mean auto-backups, then there's an issue for that: #3558. Also, please, please don't open issues and then ignore the template.
