### ISSUE TITLE
[Feature request] re-add resolution/quality dropdown before first playback

### ISSUE THREAD

**Issue by mrdude87** [TeamNewPipe/NewPipe#5304]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I have the "auto play" setting turned off and the default open action set to "show info" so I can decide which resolution prior to starting the video to save data. It was recently removed and Im forced to start playing -sometimes at high resolutions even with the limit set, before lowering down. would sure love to have that option back. Perhaps, if it was only removed to make the view more appealing, you could add a setting in the video/audio section to toggle its visibility?

#### Is your feature request related to a problem? Please describe it

i can no longer set a desired resolution prior to playback

#### How will you/everyone benefit from this feature?

I would save data which is expensive in my country

**Comment by SameenAhnaf** [comment]
@Stypox Shouldn't this be closed in favor of #5591?
