### ISSUE TITLE
New UI for Andoid TV 

### ISSUE THREAD

**Issue by AlexN1997** [TeamNewPipe/NewPipe#5307]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Thanks for this great app (v0.20.8)
I have some suggestions to make the Andoid TV UI better, this because the current NewPipe UI is optimized for smartphone/tablet use and not for a TV with a remote controller.
So here are some points of interest to tweak the UI for Andoid TV's:
- Add a setting to "force" Andoid TV UI with:
	- Removing number 1 and 2 and place them in the menu (pic 2);
	- Sadly I am unable to close a video I watched (number 3), so remove this or add a new function (press back to make it small, press back again to close);
	- When you are on one of the videos on the left (pic 1, eg Michou) and than press left, it should open the menu as in pic2;
	- Playing a video in fullscreen is quite hard to do, so is it possible to make somekind of button in the video pop-up to play a video fullscreen?. maybe also add these: (back 10sec, full screen/small screen, pauze,close video, advance 10sec. when pressing down it should go to the timeline of the video) ; 
	- If possible, add a feature to update the app from wihtin newpipe. My TV sucks when using a browser and does not give me the pup-up for a new version...;
	- Refressing the playlist is also hard to do, I suggest making a "long press to refresh" function to refresh the playlist.

![np1](https://user-images.githubusercontent.com/76731207/103280141-ebea7080-49cf-11eb-8ace-3e637859475b.png)
![np2](https://user-images.githubusercontent.com/76731207/103280157-f3aa1500-49cf-11eb-80b8-6cbeb99c75b4.png)

If someone could have a look at these points for any future update would be great, I am willing to test the alpha version

**Comment by mhmdanas** [comment]
Thanks for opening an issue! As you can see in the last point of the checklist, each feature request should be in a separate issue, so please open an issue for each feature request if one doesn't already exist.

**Comment by AlexN1997** [comment]
Thanks for replying, I am new to github.
As you have seen I am suggesting a new ui for NewPipe when using an android tv.
Therefor I can't say I want a new ui and thats it. Thats why I suggested multiple points of interest to modify the ui in one post to make a better overview.
I have no other idea to suggest my points...

**Comment by mhmdanas** [comment]
> Thats why I suggested multiple points of interest to modify the ui in one post to make a better overview.

For various reasons, we don't want multiple feature requests in a single issue. Each issue should only contain one feature request/bug. If you don't mind opening new issues for each feature request, also please check that your issue is not a duplicate (that is, there are no existing issues that request the same feature, whether open or closed).

Thanks!
