### ISSUE TITLE
Improve icon at top of screen

### ISSUE THREAD

**Issue by PanderMusubi** [TeamNewPipe/NewPipe#531]
Please use the triangle with a small opening from the logo as basis for the play icon at the top of the screen. That is, all the icons which filenames are ic_play_circle_*.png

The current play icon look too similar to that of Telegram and is confusing. Using the icon will contribute to improved branding and less confusion.

PS The new_play_arrow.png may also be based on the triangle with the small opening.

**Comment by theScrabi** [comment]
Yea you are right, that's a good point into which i run my self.

Let's change it.

**Comment by codermess** [comment]
I believe this has been done? When playing a video in popup mode, the logo on the notification bar is the same as the app logo.

**Comment by theScrabi** [comment]
Yes
