### ISSUE TITLE
Add credits for the translators in the app 

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#5314]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Credits for the people who contributed the translation project on Weblate.

#### Is your feature request related to a problem? Please describe it

No.

#### How will you/everyone benefit from this feature?

Hi, thank you for making this wonderful app you really made allot of people's life easier. I would like to suggest the creators to add credits for the people who contributed the translation project.

**Comment by mhmdanas** [comment]
I think one way to do this is get a list of contributors, which will include translators because their translations are turned into commits. Showing translators separately from other contributors though will require checking the commit message and/or description, which is not foolproof.
