### ISSUE TITLE
Play queue not accessible on Android 11 when closing the app

### ISSUE THREAD

**Issue by Poolitzer** [TeamNewPipe/NewPipe#5316]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Start a play queue in the background via closing the app.
2. Press on the "notification"

### Actual behaviour
The last window is shown again

### Expected behavior

The play queue should be openend

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/25934244/103373885-6dc4c180-4ad6-11eb-9dc4-9cded7caecf9.mp4

### Device info

 - Android version/Custom ROM version: stock android 11
 - Device model: Pixel 2

**Comment by XiangRongLin** [comment]
Did you start the background player explicitly by clicking on the button? Or was it with the "Minimize on app switch" option

**Comment by Poolitzer** [comment]
Oh it was with closing the app. With the button it works, great catch!

**Comment by XiangRongLin** [comment]
I think thats a design decision. With the "minimize" option it goes back to video player from background mode when you click on the notification

**Comment by Poolitzer** [comment]
I would wait for a dev comment but I don't like this decision then ;P

**Comment by Stypox** [comment]
Yes, this is a design decision, since the real player is still the main player, even though it switched its stream to audio-only
