### ISSUE TITLE
Video and Android Studio Emulator

### ISSUE THREAD

**Issue by cmilousi** [TeamNewPipe/NewPipe#5318]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

The application launches perfectly , but everytime I click on a video to play the whole process stops !
The Android Studio emulator goes away (I'm using the default emulator that it already has Pixel_3a_API_30_x86)
At first I thought it was Android Studio's issue but it happens everytime . Furthermore , I launch other apps and this has never
happened before.

### Expected behavior

Click a video and it should play . 

### Screenshots/Screen recordings
    [https://www.dropbox.com/s/4xz180gn5w3p5gk/20201230_224149.mp4?dl=0](url)
          Android Studio is EXTREMELY slow so please show some understanding !!

### Device info

 - Android version/Custom ROM version: Launched inside Android Studio
 - Device model: studio64.exe

**Comment by TobiGr** [comment]
That's a bug in Android Studio, not in NewPipe.
Do not run the emulator inside Android Studio. There is an option to run it inside an own window.

**Comment by cmilousi** [comment]
Oh ! Thanks for the correspondence and I'm so sorry for the misunderstanding.

**Comment by TobiGr** [comment]
no problem. I faced the same problem after updating Android Studio a while ago.

**Comment by cmilousi** [comment]
One more thing. Running the emulator in a new window is faster? That's why you suggest it?
