### ISSUE TITLE
Video Appears Brighter in Full Screen Mode on Android TV Box

### ISSUE THREAD

**Issue by Nzzyme** [TeamNewPipe/NewPipe#5320]
I have installed the latest version (0.20.8) on my Android TV box (running Android 8.1). When I play any video in the app in full screen mode, the video appears brighter as though the brightness has been increased to max (I checked and see that the brightness level is normal).

I also connected a wireless mouse to my TV box and observed that when I click and hold the left mouse button while playing the video in full screen mode, the quality looks fine but as soon as I release the mouse button, it again appears bright. 

Steps to reproduce the bug

1. Open the app and play any video
2. Click on the maximize icon to play the video in full screen
3. You will observe that the video appears slightly brighter. 

Please fix.

**Comment by mhmdanas** [comment]
Thanks for opening an issue! Please open a new issue that follows the template properly. 

Regarding your problem, I'm not totally sure, but I think it has to do with the brightness gesture, which can't be used on Android TV. Can you check if disabling `Settings > Video and audio > Brightness gesture control` fixes your problem?
