### ISSUE TITLE
No thumbnails/previews shown

### ISSUE THREAD

**Issue by Sogolumbo** [TeamNewPipe/NewPipe#5321]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

(open the app and got to news/trends)

### Actual behaviour

No thumbnails/previews are shown. In some cases only the background color is shown, in others a default symbol is shown.

### Expected behavior

The thumbnails should be shown or an error message.

### Screenshots/Screen recordings

![IMG_20201231_102935](https://user-images.githubusercontent.com/33571916/103404829-e5cdce80-4b4c-11eb-949f-6e732f350d04.png)
![IMG_20201231_102824](https://user-images.githubusercontent.com/33571916/103404830-e6666500-4b4c-11eb-8ea2-1d78a9e65980.png)

### Logs

No crash.

### Device info

 - Android version/Custom ROM: 6.0 (API 23)
 - Device model: DlG-L21HN (Honor 6C)

**Comment by HTSamurai** [comment]
I have the same problem!

**Comment by mhmdanas** [comment]
I can't reproduce this. Can you check if `Settings > Content > Load thumbnails` is enabled?

**Comment by Sogolumbo** [comment]
Thumbnails were enabled when I ran into this bug, I made sure of that.

But I found another interesting thing:
After disabeling the thumbnails I get this:
![IMG_20201231_135821](https://user-images.githubusercontent.com/33571916/103411571-9dbca500-4b68-11eb-9ec6-0d2c5e01ef7a.png)
![IMG_20201231_135805](https://user-images.githubusercontent.com/33571916/103411572-9e553b80-4b68-11eb-9ff3-3bbc946e2d4d.png)
Not that the visual appearence changes depending on the tab and the appearance 'flips' when toggling the thumbnails.

**Comment by Sogolumbo** [comment]
This is a debugging nightmare.
The exact visual appearance is not exactly reproducible. The only thing that's reproducible is that I don't get to see the thumbnails.

**Comment by Sogolumbo** [comment]
I just restarted my phone, the problem is gone now.
