### ISSUE TITLE
stream is not reachable at all!

### ISSUE THREAD

**Issue by Ra57in** [TeamNewPipe/NewPipe#5332]
![Screenshot_20210102-025201__01](https://user-images.githubusercontent.com/74661086/103447822-8c2ce780-4ca5-11eb-81da-73bf690d7d89.jpg)

### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
Thanks for opening an issue! Upgrading to 0.20.8 should fix your problem (https://github.com/TeamNewPipe/NewPipe#updates). Also, please fill out the template properly when opening an issue.
