### ISSUE TITLE
Full Screen gone

### ISSUE THREAD

**Issue by voiceofvraja** [TeamNewPipe/NewPipe#5341]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Just play any video

### Actual behaviour
The button to toggle full screen is gone

### Screenshots/Screen recordings
![Screenshot-20210103-114939-NewPi.JPG](https://user-images.githubusercontent.com/50140643/103473070-7230f900-4dba-11eb-94ad-f1b5317e7376.JPG)

### Device info

 - Android version/Custom ROM version: A10 OneUi 2.5 Core
 - Device model: Galaxy M21

**Comment by piegamesde** [comment]
Why was this closed?

**Comment by HTSamurai** [comment]
Just turn your phone. Then you'll be in fullscreen
