### ISSUE TITLE
NewPipe class not found

### ISSUE THREAD

**Issue by gssinghgautam** [TeamNewPipe/NewPipe#535]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

All the classes inside the extractor package is missing

**Comment by mauriciocolli** [comment]
The folder `extractor` is a submodule of this project, just search on google how to clone submodules...
(I suppose you used git)

So you can close this issue as this is not a problem with NewPipe.
