### ISSUE TITLE
[Meta] Static code analysis with SonarQube

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#5350]
SonarQube is a code quality/security tool, which performs static code analysis on the code and provides a report about it.
https://www.sonarqube.org/

It can be integrated into a CI process with https://sonarcloud.io/ which provides it for free for open source projects. Alternativly it can be self hosted with their community edition, although with less features (no PR checks, https://www.sonarqube.org/downloads/)
I integrated it into my fork of this project to show what it can provide.
- good PR: https://github.com/XiangRongLin/NewPipe/pull/7
- bad PR: https://github.com/XiangRongLin/NewPipe/pull/6 (I activated PR comments in this one)
- complete report of repository: https://sonarcloud.io/dashboard?id=XiangRongLin_NewPipe
- running with github actions: https://github.com/XiangRongLin/NewPipe/blob/sonarqube-fixes/.github/workflows/sonar.yml

#### Pro
- Automatic check for code quality
  - Easier reviews of PR
  - Avoid further degradation
- Visualization of test coverage (needs to be generated seperatly)
- Duplicate code check
- Provides issues for (first time) contributors. (like https://sonarcloud.io/project/issues?id=XiangRongLin_NewPipe&resolved=false&rules=java%3AS1155&types=CODE_SMELL)
  - Especially the higher priority issues are easy fixes for bugs/problems that could actually occur (https://sonarcloud.io/project/issues?id=XiangRongLin_NewPipe&open=AXbPOnIjJg7-hBPWInPV&resolved=false&severities=BLOCKER&types=BUG) 

#### Contra
- A lot of noise at the start
- Setup and maintenance cost (rules, excluded files, false positives) 
- "Another" code quality tool beside checkstyle (checkstyle report can be integrated into sonarqube)
- 6min CI job

This is just what i could think of, there are bound to be more

Overall i liked it a lot at my work. With it I also learned some nifty stuff about the langauage/framework that i did not know about.
I used it by just checking in once a day and see if something new popped up. It should not used as an hard requirement, but instead as something to occasionally check and improve on. So over the long time the code base overall can be improved.

**Comment by XiangRongLin** [comment]
@Stypox @TobiGr Any opinions about this?

**Comment by Stypox** [comment]
This seems like a good idea to me. Obviously there is going to be some noise at the beginning, but then it would hopefully prevent more bugs from arising. In order to prevent some hassle I'd add this directly with checkstyle support. Is there a similar tool which does Android-specific inspections, though (which would e.g. highlight the view binding issues?)?

**Comment by XiangRongLin** [comment]
I only know this from work so i dont know other tools that are also free for open source or which you can self host.

As for Android related rules there currently are only 4
https://rules.sonarsource.com/java/tag/android

But custom rules can be added for ourselves or even submitted as PR to their repo
https://docs.sonarqube.org/latest/user-guide/rules/
https://docs.sonarqube.org/latest/extend/contributing/
https://github.com/SonarSource/sonarqube

**Comment by Stypox** [comment]
Oh ok, I see. Well, I would be in favour of adding this anyway, it seems like it could be helpful.

**Comment by Stypox** [comment]
I also found [LGTM](https://lgtm.com/), maybe we should compare them

**Comment by XiangRongLin** [comment]
> I also found [LGTM](https://lgtm.com/), maybe we should compare them. This is the [alert page](https://lgtm.com/projects/g/TeamNewPipe/NewPipe/alerts/?mode=list).

From a quick glance it seems more security focused rather than been generic code quality. Which also is visible in the number of issues that are found. 33 vs ~950. some of those are certainly noise. But many are still useful which LGTM seems to not cover. Like the one about `isEmpty()` that i linked on top as good issues for news contributors

**Comment by TobiGr** [comment]
I agree that we need some static code analysis to improve code quality. We should compare a few tools. I have no idea what tools are available for Android development.

**Comment by TobiGr** [comment]
i took a look at some other android open source projects and these which used code analysis, used Sonar. So let's go with that.

**Comment by XiangRongLin** [comment]
@TobiGr I requested acces from sonarcloud.io for NewPipe and NeePipeExtractor. i think you should get notified in some way

**Comment by TobiGr** [comment]
i granted access and create the sonarcloud organization `teamnewpipe`.

**Comment by XiangRongLin** [comment]
@TobiGr  Can you set the `SONAR_TOKEN` as secrets in the resprective repositories. They will be needed during the CI job.

You can see the token here:
https://sonarcloud.io/project/configuration?analysisMode=GitHubActions&id=TeamNewPipe_NewPipe
https://sonarcloud.io/project/configuration?analysisMode=GitHubActions&id=TeamNewPipe_NewPipeExtractor

**Comment by XiangRongLin** [comment]
I created a project, with stuff that needs to be done.
https://github.com/TeamNewPipe/NewPipe/projects/20
