### ISSUE TITLE
Miniplayer maximize button not working out of the app

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5351]
### Checklist

- [x] I am using the latest version - 0.20.8
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Click on any video
2. Open the popup player
3. Go on another app, or you're home screen
4. Try and click the fullscreen button to no success

### Actual behaviour
Nothing happens. No fullscreen for you, my friend! 

### Expected behavior
I expect it to just open the regular player on NewPipe

### Screenshots/Screen recordings
*I tried but picking the video just adds a new line*

### Device info

 - Android version/Custom ROM version: Android 10, MIUI 11.0.3.0
 - Device model: Xiaomi Redmi 8 Global version

**Comment by mhmdanas** [comment]
For me, it does work  but you have to wait for a bit after you press the button. Can you see if that's the case for you too?

**Comment by HTSamurai** [comment]
Still doesn't work

**Comment by avently** [comment]
Maybe screenrecord could help

**Comment by HTSamurai** [comment]
> Maybe screenrecord could help

K

**Comment by HTSamurai** [comment]
Here is the video:
![Uploading NewPipe.GIF…]()

**Comment by avently** [comment]
@HTSamurai link is broken

**Comment by mhmdanas** [comment]
@HTSamurai you have to wait for the video to finish uploading.

**Comment by HTSamurai** [comment]
Oh

**Comment by mhmdanas** [comment]
@HTSamurai well, when will we get the video?

**Comment by HTSamurai** [comment]
I thought it sent but it didnt

**Comment by HTSamurai** [comment]
Sorry the mp4 won't upload

**Comment by avently** [comment]
@HTSamurai put the video inside a zip archive and then upload

**Comment by HTSamurai** [comment]
It says zips are unsupported

**Comment by Stypox** [comment]
GitHub now supports mp4s afaik

**Comment by HTSamurai** [comment]
This is working now in v0.20.11 so I should close

**Comment by iamthesenate1** [comment]
For me it doesn't work and I have 0.20.11

**Comment by HTSamurai** [comment]
It might be a software problem. I got Newpipe 0.20.11 around when I updated
my phones OS from MIUI 11 to MIUI 12 and it works now
