### ISSUE TITLE
[Feature] listing all available vcodec

### ISSUE THREAD

**Issue by jefferson018200306** [TeamNewPipe/NewPipe#5353]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
 I think it is much better for newpipe to list videos we like to download with full details such as vcodec values, it makes us to ensure that the video we are downloading is at its best format .

Listing all the available video formats is also a good alternative. Not as good as choosing between MPEG-4 WebM and 3GP on the settings, but at least it will turn out to be a good idea because of this feature we will not worry anymore for compatibility issues. And automatically merge it on the separate audio that we've downloaded

#### Is your feature request related to a problem? Please describe it
 Because some of the videos will not play on every media player, i recommended that you add this request or features in order for us to play it on it (such as TV player or DVD player)

#### How will you/everyone benefit from this feature?

This feature will help us to download youtube videos at its best quality, and it will now play for every media player we like to use. We can also make sure that this feature will help us videophiles to be more productive when this is accepted 🙂

**Comment by mhmdanas** [comment]
Thanks for opening an issue! This issue contains multiple feature requests, but each issue should contain one feature request or bug, as stated in the last item of the checklist. Also, you're not following the template properly. At least the "Describe the feature you want" and "How will you/everyone benefit from this feature?" sections should be filled. Mind opening an issue for each of your suggestions and making sure that it follows the template properly? Thanks again!

**Comment by jefferson018200306** [comment]
> Thanks for opening an issue! This issue contains multiple feature requests, but each issue should contain one feature request or bug, as stated in the last item of the checklist. Also, you're not following the template properly. At least the "Describe the feature you want" and "How will you/everyone benefit from this feature?" sections should be filled. Mind opening an issue for each of your suggestions and making sure that it follows the template properly? Thanks again!

There you go, i hope nothing is incorrectly filled up

**Comment by mhmdanas** [comment]
Thanks! I'll re-open this issue, but could you also change the title to be more descriptive? "add features like X" isn't really a good title.

**Comment by mhmdanas** [comment]
What is the difference between this issue and #5364?

**Comment by jefferson018200306** [comment]
> What is the difference between this issue and #5364?

I thought I can't reopen the issue so i create new

**Comment by jefferson018200306** [comment]
> Thanks! I'll re-open this issue, but could you also change the title to be more descriptive? "add features like X" isn't really a good title.

It is more detailed now

**Comment by mhmdanas** [comment]
Great, but why isn't the last item in the checklist checked?

**Comment by jefferson018200306** [comment]
> Great, but why isn't the last item in the checklist checked?

Because vcodec and acodec listing features is two different things to do right?

**Comment by mhmdanas** [comment]
Well, the checklist is compulsory, so you can keep this issue for video codec but create another one for audio codecs.

**Comment by jefferson018200306** [comment]
> Well, the checklist is compulsory, so you can keep this issue for video codec but create another one for audio codecs.

Okay so i will create 2 request with same content like this. Entitled vcodec and acodec request. Is it ok?

**Comment by mhmdanas** [comment]
You can create two other issues, but it would be better to change this one for video codecs, and create another one for audio codecs.

**Comment by jefferson018200306** [comment]
> You can create two other issues, but it would be better to change this one for video codecs, and create another one for audio codecs.

Done, thanks!

**Comment by jefferson018200306** [comment]
> You can create two other issues, but it would be better to change this one for video codecs, and create another one for audio codecs.

#5365 is now it's another feature request. Thank you for guiding me through this

**Comment by mhmdanas** [comment]
You're welcome. We're almost done with this. The last thing you have to do is edit both this issue's and that one's contents. Both reference audio and video codecs.

**Comment by jefferson018200306** [comment]
> You're welcome. We're almost done with this. The last thing you have to do is edit both this issue's and that one's contents. Both reference audio and video codecs.

I'm done editing the content of both reference. Please check if it is now done

**Comment by mhmdanas** [comment]
Yes, I think we're done. Thanks for taking the time to follow my suggestions!

**Comment by jefferson018200306** [comment]
> Yes, I think we're done. Thanks for taking the time to follow my suggestions!

It's been 4 days now, do you think the developer is going to do this feature now? 😅I need updates about this

**Comment by mhmdanas** [comment]
We have 700+ issues in our issue tracker, and working on NewPipe isn't our job; we work on it in our spare time. And even if we were paid to work full-time on NewPipe, adding all feature requests in less than a week is too much. So please cut the developers some slack. I don't know when the devs are going to add this.
