### ISSUE TITLE
Import Youtube Music Playlist (.csv)

### ISSUE THREAD

**Issue by tokenwizard** [TeamNewPipe/NewPipe#5355]
Is there a way to import the "music-library-songs.csv" or any of the "Playlist" csv files from a Google Takeout export of YouTube and YT Music?

I have been able to pull in the subscription.json from my YouTube video account just fine. But I use YT Music about 200% more than YoutTube for videos. The Inability to pull in all my Music playlists is the last thing keeping me from fully ditching YouTube Premium.

I would happily donate to have this feature added as I'm sure would many others. 

![image](https://user-images.githubusercontent.com/24832561/103695183-1c9b4e80-4f6a-11eb-9be9-dc6e99856672.png)

![image](https://user-images.githubusercontent.com/24832561/103695203-2ae96a80-4f6a-11eb-8804-29e8152b375f.png)

**Comment by mhmdanas** [comment]
@tokenwizard thanks for opening an issue! Could you please open an issue from the GitHub website so that you can use the feature request template?

**Comment by tokenwizard** [comment]
I posted this on the Github page, under the Issues section. I'm not seeing any Feature Request sections on the GitHub. I must be missing it.

**Comment by mhmdanas** [comment]
When you press the "New issue" button on GitHub's website (not a third-party client) issued page, it should show you a bunch of templates to choose from.
