### ISSUE TITLE
Instrumented tests don't run

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#5359]
### Checklist

- [x] I am using the latest version - dev branch 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Connect Android phone to PC/ start Android emulator
2. Execute `gradle app:connectedCheck` to run instrumented tests

### Actual behaviour

It fails at `:app:compileDebugAndroidTestJavaWithJavac`
with
```
app\src\androidTest\java\org\schabi\newpipe\report\ErrorInfoTest.java:29: error: incompatible types: Object cannot be converted to ErrorInfo
        final ErrorInfo infoFromParcel = ErrorInfo.CREATOR.createFromParcel(parcel);
```

### Expected behavior

The tests to run

### Potential solutions
1. Upgrade to kotlin 1.4.20
    - Requires (manual) testing for regressions
2. Revert https://github.com/TeamNewPipe/NewPipe/commit/340b92e32b8ae32c7779a05be25831122ff5adec
    - looses benefits of annotation

### Device info

- OS: Windows 10 

related: https://youtrack.jetbrains.com/issue/KT-25807

**Comment by Stypox** [comment]
This would also be solved by #5148
