### ISSUE TITLE
Player controls flicker when Animator duration scale is off

### ISSUE THREAD

**Issue by nvllsvm** [TeamNewPipe/NewPipe#536]
When the 'Animator duration scale' in Developer options is set to off, the ExoPlayer controls are visible for only a split second when the screen is touched.

Video here: https://sol.nullsum.net/nextcloud/s/8XdElbVYcGY9zfY

**NewPipe:** 0.9.4 from F-Droid
**Device:** OnePlus 3T
**Android:** 7.1.2
**ROM:** SultanXDA's LineageOS 14.1-20170430

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

**Comment by mauriciocolli** [comment]
When you change the  `Animator Scale Factor`  to off, the `sDurationScale` is set to 0f.

I used `setStartDelay` in the some animations of NewPipe, but that's the tricky part, it will multiply the `delay * scale`, and of course it'll be zero, as you can see here [ValueAnimator.java#994](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/animation/ValueAnimator.java#994).

And some low-end devices comes with it disabled by the manufacturer (set to 0).
I'm already working in a fix and I think will be done in the next few days.
