### ISSUE TITLE
[Feature] Ability to read video subtitles own their on without download

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5362]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
This feature would let you "read" videos on NewPipe and it would work similarly to downloading subtitles but without downloading.

#### Is your feature request related to a problem? Please describe it
Sometimes if I am on data, or want to be quick, I'd want to read it but I don't wanna download the subtitles.

#### Additional context
*Mock-up* time
![IMG_20210106_183226](https://user-images.githubusercontent.com/71007160/103807533-69f0ec00-504e-11eb-80f0-561129d1267b.jpg)
![IMG_20210106_182527](https://user-images.githubusercontent.com/71007160/103807538-6cebdc80-504e-11eb-8113-54162e033180.jpg)

#### How will you/everyone benefit from this feature?
People could easily and quickly read subtitles!

**Comment by SameenAhnaf** [comment]
@litetex This issue should be closed in favor of #7375.
