### ISSUE TITLE
List full audio & video codecs info

### ISSUE THREAD

**Issue by jefferson018200306** [TeamNewPipe/NewPipe#5365]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I think it is much better for newpipe to list audios and videos we like to download with full details such as acodec or vcodec values, it makes us to ensure that the audio or video we are downloading is at its best format . Listing all the available audio or video formats is also a good alternative. Not as good as choosing between M4A and WebM, or MPEG-4 WebM and 3GP for video, on the settings, but at least it will turn out to be a good idea because of this feature we will not worry anymore for compatibility issues. And automatically merge it on the separate file that we've downloaded.

#### Is your feature request related to a problem? Please describe it
Because some of the audios and videos will not play on every media player, i recommended that you add this request or features in order for us to play it on it (such as TV player or DVD player)

#### How will you/everyone benefit from this feature?
This feature will help us to download youtube audios and videos at its best quality, and it will now play for every media player we like to use. We can also make sure that this feature will help us audiophiles and videophiles to be more productive when this is accepted 🙂

**Comment by jefferson018200306** [comment]
#5353 is it's another feature request

**Comment by jefferson018200306** [comment]
It's been 4 days now, do you think the developer is going to do this feature now? 😅I need updates about this

**Comment by Stypox** [comment]
If someone wants to implement this, then it's going to be accepted

**Comment by Stypox** [comment]
I merged back the two issues, since if they are being implemented they should be done together

**Comment by jefferson018200306** [comment]
> I merged back the two issues, since if they are being implemented they should be done together

Thank you @Stypox

**Comment by jefferson018200306** [comment]
#6154 is it's new request. Hopefully it is implemented now
