### ISSUE TITLE
Schedule dark mode

### ISSUE THREAD

**Issue by Timmy183-ui** [TeamNewPipe/NewPipe#5368]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Not many android devices run on Android 10 and above, and it is a pain to go to settings to toggle dark mode depending upon time. So it would be real nice to have an option to turn of night mode during specific periods of time like 6pm to 9am which can be user configurable 

#### Is your feature request related to a problem? Please describe it
Yes, the problem being devices running Android 9 or lower don't have automatic dark mode. 

#### How will you/everyone benefit from this feature?
It would be a huge improvement in terms of ui and functionality

**Comment by Redirion** [comment]
I don't think this would be a widely used feature and just "bloat" for NewPipe. You could use another app that brings automatic dark mode to your Android 9 phone like this one: https://play.google.com/store/apps/details?id=systems.maju.darkmode

This way all apps that support dark themes, would be able to profit, not just one app.

**Comment by Timmy183-ui** [comment]
> I don't think this would be a widely used feature and just "bloat" for NewPipe. You could use another app that brings automatic dark mode to your Android 9 phone like this one: https://play.google.com/store/apps/details?id=systems.maju.darkmode
> 
> This way all apps that support dark themes, would be able to profit, not just one app.

But.. I don't have an android 9 or above device☹️

**Comment by Redirion** [comment]
The App that I have found with Google requires 4.4. Did you try it or any alternative?

**Comment by Redirion** [comment]
@Stypox opinion?

**Comment by Stypox** [comment]
I agree this is way too niche for newpipe
