### ISSUE TITLE
Toast message gets queued up instead of cancelling

### ISSUE THREAD

**Issue by SreeHaran** [TeamNewPipe/NewPipe#5369]
### Checklist

- [x] I am using the latest version - 0.20.8
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1.Go to HistorySettingsFragement, under the clear data section
2.Just click those views (Clear search history, delete playback positions, etc.)
3.Toasts keeps on showing

### Actual behaviour

the toasts just get queued up and takes more time to disappear. The toast still displays even after closing the entire app.

### Expected behaviour

Instead queuing the previous toasts, it is better to cancel the previous toast and show the new toast. (I know it is very minor, but yet :) )

### Device info

 - Android version/Custom ROM version:  Android 10(API level 29) / realme UI
 - Device model: Realme X

**Comment by Stypox** [comment]
This is normal behaviour on Android and even if what you say is doable I wouldn't consider deleting old non-expired toast a good idea.

**Comment by SreeHaran** [comment]
No, it is not normal in android, also it is doable, Instead of directly calling toast... create a private toast variable in the class and also create a method for toast. And, call cancel method on the toast object if it is not null.. Like:

void createToast(int message){
    if(Toast != null) Toast.cancel();
    Toast = toast.makeToast(this, message, Toast.LENGTH_SHORT);
    Toast.show();
}

That's it...

**Comment by Stypox** [comment]
This works in a single activity, but we have too many activities and fragments to be able to do this without adding too much code. Also, I don't understand why it is an issue if there are multiple toasts... They're there for a reason, aren't they? We can't just dismiss them if they contain random info before the user is able to even read it

**Comment by SreeHaran** [comment]
Ok
