### ISSUE TITLE
FR: Resume position of a video in backstack

### ISSUE THREAD

**Issue by gerroon** [TeamNewPipe/NewPipe#537]
Hi

It would be great if NP can remember play positiitions of past played videos. For example I play a video then change to another in the middle of it. I would like NP to remember the time of where I left of when I get back to the first video.

thanks

**Comment by theScrabi** [comment]
Hm cool idea actually.

**Comment by mauriciocolli** [comment]
I think it'd great to integrated this feature with the history (when we implement it)

**Comment by Loedje** [comment]
this feature to resume videos where you left off is a really handy feature on the youtube website when you're logged in and I would love to have it in the newpipe app.

**Comment by ildar** [comment]
Very demanded feature.
Though the title of this issue needs to be changed as it's currently obscure.

**Comment by rollac01** [comment]
It would be amazing to have this feature added if possible :-)

**Comment by theScrabi** [comment]
Yea lets see, we have some stuff to do first, but maybe some day :)
