### ISSUE TITLE
Display Subtitles/CC tag

### ISSUE THREAD

**Issue by tiwarys** [TeamNewPipe/NewPipe#5378]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be nice if you add a tag which displays Subtitles/CC if a video has them like YouTube website does.

#### Additional context

![YouTube Subtitles](https://user-images.githubusercontent.com/46630255/104108938-d558e900-52ee-11eb-86e6-7cf8ff9d6846.png)

#### How will you/everyone benefit from this feature?

Without opening a video we can identify whether a video has subtitle(s) or not.

**Comment by mhmdanas** [comment]
Closing in favor of #7226.
