### ISSUE TITLE
Change "No comments" message on videos where creator disabled comments

### ISSUE THREAD

**Issue by TotalCaesar659** [TeamNewPipe/NewPipe#5380]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I want to see "Comments are turned off." instead of "No comments" on videos with disabled comments.

#### Is your feature request related to a problem? Please describe it

There is "No comments" on videos with disabled comments (e.g. https://www.youtube.com/watch?v=Z-AFsvnstM0) like on ones just with 0 comments.

#### Additional context

![1](https://user-images.githubusercontent.com/14265316/104119761-d6b40100-5342-11eb-822f-262d4ffa8065.png)

#### How will you/everyone benefit from this feature?

NewPipe users will know that uploader doesn't want comments for his video instead of thinking nobody commented it.

**Comment by mhmdanas** [comment]
Thanks for opening an issue!

I disabled comments by turning Settings > Content > Show comments off and I can't scroll to the comments tab; I only have the video suggestions. Can you say what version of NewPipe you have?

**Comment by HTSamurai** [comment]
> Thanks for opening an issue!
> 
> I disabled comments by turning Settings > Content > Show comments off and I can't scroll to the comments tab; I only have the video suggestions. Can you say what version of NewPipe you have?

They meant how on some videos, the uploader disables commenting on the video so instead of it saying no comments it might say comments disabled.

**Comment by mhmdanas** [comment]
Oh, that makes more sense. I'll change the title to make that clear.

**Comment by litetex** [comment]
Was fixed by https://github.com/TeamNewPipe/NewPipe/pull/6483 with Release 0.21.9 https://github.com/TeamNewPipe/NewPipe/issues/6841

![grafik](https://user-images.githubusercontent.com/40789489/132069163-347ca46d-5f9b-4a5a-8606-d683a812df12.png)
