### ISSUE TITLE
Choose default tab to open.

### ISSUE THREAD

**Issue by molitona** [TeamNewPipe/NewPipe#5386]
Hi, if you can add a feature to let us choose what tab appears by default when we open the app.
I wanna always get "What's New" tab initially, please add it. Thanks!

**Comment by mhmdanas** [comment]
Thanks for opening an issue! If you go to `Settings > Content > Content of main page`, you can add tabs (press the plus button at the bottom of the screen), remove them (drag item to left or right), or change their order (drag while pressing on the two lines at the end of each item). By default, the first tab is the one that is opened when the app is launched.
