### ISSUE TITLE
Restrict viewing to WiFi connection

### ISSUE THREAD

**Issue by herrdeh** [TeamNewPipe/NewPipe#5388]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I'm using a cheap mobile data plan with 400MB per month included. That's way enough for me - except the case my phone loses WiFi when watching video and eats up a large amount of data in a few minutes - and I don't even notice. It would be nice if I

- either could just limit NewPipe to WiFi-only operation
- or opt for an alert in case WiFi is lost

#### Optionally, also describe alternatives you've considered.
There is additional software for this, see #355. But with restricted SD card size, you want to avoid any additional bit of software.

#### Is your feature request related to a problem? Please describe it
In #355 the same issue is covered about downloading. But I think it's about watching as well.

#### How will you/everyone benefit from this feature?
Finding that NewPipe ate up a large fraction of the data plan - for nothing, just by accident - is frustrating. So it would be great if we could ensure that does not happen.

In case there already is a solution I could not find, please apologize - and give me a hint.

**Comment by Redirion** [comment]
We could switch to audio only and show a warning that wifi has been lost and switch back to video+audio once wifi is recovered. Or would you rather like to stop playback completely?

**Comment by herrdeh** [comment]
Wow - such a quick reply! (-:
I'd be happy with both solutions - a switch to administer would be the de-luxe-solution.

**Comment by Redirion** [comment]
meanwhile you could set your preferred video resolution to 144p when on mobile. This will probably very notable and also consume less data.

**Comment by herrdeh** [comment]
Thank you for pointing me to that control - hadn't noticed it before. Extending it with the options  "stop playback" and "playback audio only" should do the job.

A default setting as "stop playback" with an alert - "playback stopped because WiFi is lost - change settings at..." would make it close to dummy-proof (meaning: suitable for me}, I assume.


Am 11. Januar 2021 16:00:02 schrieb Robin <notifications@github.com>:

**Comment by Stypox** [comment]
Adding a setting just for this would be niche for most users, cluttering the logic. Installing another app shouldn't use more than 2-3MB. Adding this to NewPipe is out of scope, sorry

**Comment by herrdeh** [comment]
Can't agree. Everybody is in risk to loose WiFi occasionally. And another setting for behaviour at WiFi / mobile is a breeze.
