### ISSUE TITLE
Ability to delete Main Page tabs in "Content of main page"

### ISSUE THREAD

**Issue by YizhongHu** [TeamNewPipe/NewPipe#5389]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The "Contents of main page" page offered options to add, but no options to delete tabs. We can restore back to defaults, but this means that the default tabs cannot be removed, possibly leading to overcrowding the tabs.

#### How will you/everyone benefit from this feature?

It increases customizability as not everyone is interested in every tab. The "Trending videos" for example, may not be of interest to everyone. Adding too many tabs, however, may lead to overcrowding.

**Comment by TobiGr** [comment]
you can remove tabs by swiping them to the right.

We really need a tour / UI hints to make those actions visible to the user or introduce them properly.

**Comment by YizhongHu** [comment]
Thank you! I should have fiddled around a little bit more.
