### ISSUE TITLE
[Feature] Family Friendly mode...? 

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5391]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

This would be a way that the app scans the subtitles and if swear words are found, it doesn't show that video. 

#### Is your feature request related to a problem? Please describe it
Hearing F-bombing isn't fantastic. I don't think anyone likes that.

#### Additional context
*Mock-up* time! 
![IMG_20210111_210303](https://user-images.githubusercontent.com/71007160/104238066-f89ba980-5450-11eb-9c46-20c5bace7de0.jpg)

#### How will you/everyone benefit from this feature?
People won't need to put up with levels of swearing that are just not ok.

**Comment by Stypox** [comment]
I don't think this is doable. Parsing the entire subtitles just to check for this would be slow and uneffective, since auto-generated subtitles are not trustworthy

**Comment by HTSamurai** [comment]
Fair enough.
