### ISSUE TITLE
[Feature Request] playlists

### ISSUE THREAD

**Issue by Rob--W** [TeamNewPipe/NewPipe#54]
Searching, playing and navigating through playlists.

**Comment by theScrabi** [comment]
Will come.
When? I don't know :)

**Comment by Rob--W** [comment]
@BlenderViking 
I see activity in #382 and elsewhere. Is playlist support ready?

@theScrabi If the release is stable, could you publish an update in Fdroid?

**Comment by BlenderViking** [comment]
@Rob--W 
You can build the app with the code on in `playlist` branch. In my case, I use this version without occurred bug.

**Comment by theScrabi** [comment]
Maybe we could offer an alternate build as long as this branch is not merged.

**Comment by tpeg5stan** [comment]
I agree with theScrabi, is it possible to publish a version of the app with playlists, call it beta for example ?

I would really like the playlist functions.

**Comment by theScrabi** [comment]
Now It's to late, the changes on NewPipe are so havy that It would not make sense to release that patched version.

However we are making progress anyway, [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor) already has the ability to handle Playlists. It's only the UI that is not yet prepared for it.

**Comment by tpeg5stan** [comment]
Ok, thanks for the news :+1: 

I hope we will soone get the playlists in the app.

**Comment by kkuhle** [comment]
+1 - this would be really nice!

**Comment by theScrabi** [comment]
Yea tha bach end is already supportig playlists. So It'll not be such a big problem. When I'll find time I'll do this :)

**Comment by mase76** [comment]
Are you talking about the channel playlists or queuing videos to an own?

**Comment by theScrabi** [comment]
I'm talking about channel playlists. Queuing videos would be a fronted implementation, and that needs to be done some day in the future.

**Comment by mase76** [comment]
Channel playlist support would be fine.

**Comment by theScrabi** [comment]
Basic play list support is there. Advanced play list support is WIP :)

**Comment by NicTanghe** [comment]
came hre to say plz us to vieuw a users playlists when you go to his profile(not just his videos)
