### ISSUE TITLE
Popup not moveable

### ISSUE THREAD

**Issue by Nas-Uddin** [TeamNewPipe/NewPipe#540]
The popup player opens in the top left hand corner, but when I drag it to move it, a transparent layer moves but the window that's playing the video stays where it is. Play/Pause has to be done through the transparent layer. Attached is a screenshot of the issue. 

OnePlus 3T Running Resurrection Remix (7.1.2)

![screenshot_20170508-100857](https://cloud.githubusercontent.com/assets/25305380/25807949/88652770-33d6-11e7-91c3-926273d03bcb.png)

**Comment by mauriciocolli** [comment]
Could you try the latest version just to make sure that is still happening?
(Fdroid didn't built it yet, you cand find it [here](https://github.com/TeamNewPipe/NewPipe/releases))

**Comment by Nas-Uddin** [comment]
Removed and wiped app data for the old version, the new one from your link (v0.9.5) is giving me the same issue as before.

**Comment by mauriciocolli** [comment]
Can you provide a `logcat` with this debug version?
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/988318/app-debug.apk.zip)

**Comment by Nas-Uddin** [comment]
Attached is the requested logcat


[2017-05-11-09-02-03.txt](https://github.com/TeamNewPipe/NewPipe/files/993056/2017-05-11-09-02-03.txt)

**Comment by mauriciocolli** [comment]
Sorry for the delay.

I think the issue is with you ROM specifically (I even tested Resurrection Remix in my device, but here is working fine), but maybe you updated/change the rom in the meantime, so, is it happening yet?
