### ISSUE TITLE
Share button when playing in background

### ISSUE THREAD

**Issue by illustribe** [TeamNewPipe/NewPipe#5400]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
-x [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Hello,
As it is now, there's no "share" button anywhere on the currently playing screen of a video that's playing in the background. The only two ways to share it are either tapping on the video, then it turns into normal playing (not background) and THEN the share button is accessible by clicking on the top right downward arrow. That's a nuisance since there's a short cut in the sound when changing from background to normal playing. The other way is to drag down the notification bar, tapping on the newpipe play control section taking you to the playing queue, and THEN long tapping on the video to get the Share option... It's a lot for such a used function as the Share one, IMO.
My suggestion is to add a share button somewhere on the currently playing screen :)
Thank you!

#### Is your feature request related to a problem? Please describe it

Nope

#### How will you/everyone benefit from this feature?

By saving a lot of clicks -and maybe a quick cut in the sound- to do a very often routine! ;D

Thx

**Comment by c-shubh** [comment]
Duplicate of #4039

**Comment by illustribe** [comment]
I see, yeah I guess it's within the scope of that PR... Thanks a lot!
