### ISSUE TITLE
Only old versions of NewPipe in F-Droid 

### ISSUE THREAD

**Issue by deejay73** [TeamNewPipe/NewPipe#5411]
In F-Droid sind nur alte Versionen von NewPipe bis Version 0.20.1 verfügbar. Warum?

In F-Droid are only old versions of NewPipe available. Version 0.20.1 is the newest available version. Why is this so?

**Comment by mhmdanas** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/5069#issuecomment-740712193 for an explanation. See https://github.com/TeamNewPipe/NewPipe#updates on how to upgrade.
