### ISSUE TITLE
newpipe does not switch back to fullscreen after rotating back to landscape

### ISSUE THREAD

**Issue by vladtepesch** [TeamNewPipe/NewPipe#5413]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. turn tablet into landscape
2. start playing a video
3. make it full screen
3. turn to portrait
4. turn back to landscape

### Actual behaviour

video is not played in fullscreen anymore

### Expected behavior

after rotating back fullscreen should be reenabled

**Comment by Stypox** [comment]
Fixed in 0.20.9

**Comment by mhmdanas** [comment]
What? Is 0.20.9 out?

**Comment by Stypox** [comment]
No, but it was fixed in a PR that was merged: #4939
