### ISSUE TITLE
Confirmation before deleting all downloads

### ISSUE THREAD

**Issue by kcpatricio** [TeamNewPipe/NewPipe#5419]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

My suggestion is to make a pop up confirmation when selecting the "delete downloaded files" option or a trash can so we can recover those deleted files

Having a single touch wipe is way too dangerous for a backup
As my own experience, a single missclick cost all my backup of temporary videos I had for studying

**Comment by SpinHit** [comment]
Hello we are two students who want to work on this issue, this is the first time we are contributing to a project if you could help us a little bit it would be great.

**Comment by kcpatricio** [comment]
Yeah
How could I help you?

**Comment by kcpatricio** [comment]
> Hello we are two students who want to work on this issue, this is the first time we are contributing to a project if you could help us a little bit it would be great.

Yeah
How could I help you?

**Comment by XiangRongLin** [comment]
@kcpatricio Is this even still the case now?
You have to first click on the "trash" icon, then select "Delete downloaded files", which are 2 actions.

After confirming both, you get a snackbar at the bottom with the "undo" option.

**Comment by kcpatricio** [comment]
> @kcpatricio Is this even still the case now?
> You have to first click on the "trash" icon, then select "Delete downloaded files", which are 2 actions.
> 
> After confirming both, you get a snackbar at the bottom with the "undo" option.

Yes
{
1 click (trash icon)
1 click (delete downloaded files)
*All files deleted*
3-4 seconds notification at the bottom with undo option
}
But no confirmation request before deleting
My suggestion is to prompt a warning about the wipe action, requesting a confirmation before executing it
Or to change from "delete" to "send to bin" where it would hold files till a given expiration date or manual deletion

**Comment by SameenAhnaf** [comment]
@kcpatricio I am not sure why this process has to be so complicated. Personally, I think, a 'Trash' tab under "Downloads" could be added.

Let the videos under "Trash" tab completely undeletable. All information could be automatically deleted 30 days after deletion or after redownloading the video in same or any other resolution.

**Comment by vhouriet** [comment]
Personnaly, I feel like the way it currently works is pretty good. It would add an unecessary step IMO. However, I think the single file delete should have a confirmation dialog instead / in addition of the "Undo" snackbar. It's more likely to delete the wrong file than to delete all the downloads accidentaly.

**Comment by litetex** [comment]
> My suggestion is to make a pop up confirmation when selecting the "delete downloaded files" option or a trash can so we can recover those deleted files
> 
> Having a single touch wipe is way too dangerous for a backup

I don't understand the problem in the first place.
There is already a popup, when clicking the trash can (top right corner), which asks you if you want to delete all downloaded files, just clear the history or cancel the action.

So why should we need another one?

**Comment by litetex** [comment]
I had some discussion with other devs and the following proposal seems like a good solution:
* Remove the delete button (trash-can)
* Add an overflow menu with 2 entries: "Delete all downloaded files", "Clear download history"
* When clicking a entry a confirm dialog should show up, saying something like "Really delete all downloaded files?" or "Really clear complete download history?"
