### ISSUE TITLE
Sorting and Filterung

### ISSUE THREAD

**Issue by MichiFr** [TeamNewPipe/NewPipe#5420]
Hi!

Maybe I did not found, maybe it does not yet exist: after searching for YT vids, I'm missing an option to filter and sort the results.

Right now I see many videos in an unsorted order, but I want the lastest to be sorted on top of the list.

Thanks,
Michael

**Comment by AlexN1997** [comment]
Repost of[#4599](https://github.com/TeamNewPipe/NewPipe/issues/4599)
