### ISSUE TITLE
Background player - change song

### ISSUE THREAD

**Issue by CJZup** [TeamNewPipe/NewPipe#5422]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by Stypox** [comment]
Check Settings -> Notification
