### ISSUE TITLE
Videos on loading loop after tabbing back into app.

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#5423]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play any video for any limited amount of time.
2. Go into a phonecall or go to any other application for at least a minute.
3. Tab back into NewPipe

### Actual behaviour

The video gets stuck on loading no matter how fast your internet speed may be. A workaround I found is to just close the video or app then reopen it.

### Expected behavior

I expected the video to resume once I had hit play again.

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Samsung GalaxyS10

**Comment by mhmdanas** [comment]
Mind specifying your NewPipe version?

> Android version/Custom ROM version: 0.10.0

Just to be sure, did you mean Android 10, or are you using version 0.10.0 of a custom ROM?

**Comment by Flam3z** [comment]
My apologies, thought I stated it correctly.
