### ISSUE TITLE
"Unrecoverable Player Error occurred" on almost every Youtube video

### ISSUE THREAD

**Issue by shoffmeister** [TeamNewPipe/NewPipe#5426]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Almost every video on Youtube will yield the "Unrecoverable Player Error occurred" error message.

A (rare!) working video is https://www.youtube.com/watch?v=C-u5WLJ9Yk4 ("Britney Spears - ...Baby One More Time (Official Video)"), a video yielding the error message is, for instance, https://www.youtube.com/watch?v=w8KQmps-Sog ("Muse - Uprising [Official Video]") - and both videos apparently were uploaded around the year 2009.

NewPipe appears to work well in all other aspects - except for actually playing video (see above).

Steps: 
* Try to play the Muse video (https://www.youtube.com/watch?v=w8KQmps-Sog ("Muse - Uprising [Official Video]"))

### Actual behaviour

//exp: plays video

### Expected behavior

//act: "Unrecoverable Player Error occurred"

### Screenshots/Screen recordings

n/a

### Logs

n/a

### Device info

 - Android version/Custom ROM version: Custom Android ROM, AICP https://www.aicp-rom.com/ (Android Q, 15.0 -> https://dwnld.aicp-rom.com/device/castor_windy/WEEKLY/aicp_castor_windy_q-15.0-WEEKLY-20210115.zip)
 - Device model: Sony Xperia Z2 Tablet WiFi (castor windy) -> Qualcomm Snapdragon 801, 32(!) bit

**Comment by shoffmeister** [comment]
Is there a way to obtain more information related to "Unrecoverable error occurred"?

The error context provided makes is rather difficult to forward useful information for analysis, I am afraid.

Also, I cannot tell whether this is a regression (in whatever component in the stack), and/or a recent one at that - I hadn't used the device in a while, and now it's all refreshed and patched up and NewPipe is unhappy.

**Comment by Stypox** [comment]
You may try to get logs from logcat via adb

**Comment by mhmdanas** [comment]
@shoffmeister I'm not sure if this will work, but I suppose you could, as a temporary workaround, use an external player by enabling `Settings > Video and audio > Use external video player`.

**Comment by FestplattenSchnitzel** [comment]
> A (rare!) working video is

This one does not work for me either.

**Comment by Soundtoxin** [comment]
I hit this error on videos that are over a certain age. If you search "floor buffer fail", many results don't work. 9 year old and 11 year old vids fail, 2 and 5 year old videos work.

**Comment by plata** [comment]
(At least for me) it is related to the resolution of the video:
If default resolution is set to highest or 1080p, I get this error for certain videos. If default resolution is set to 720p or lower, I can play those videos. However, if I try to set the resolution to 1080p after the video starts playing, I get the same error.
If default resolution is set to 720p, some other video, which works with default resolution 1080p, gives this error. I noticed that the WebM was listed for 720p for this video (all other resolutions MPEG4).

**Comment by TiA4f8R** [comment]
> - video 2 has a 720p mp4, so why does it only show the webm even if MPEG-4 is set as default?

Because this stream was disabled, see https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/ItagItem.java#L55. No MP4 720p stream with audio and video in the same file is returned with videos protected with cipher URLs by the YouTube website, contrary to other videos.

**Comment by infinitewaveparticle** [comment]
I just wanted to add that I've been experiencing this issue recently on some videos using versions 0.21.6 & 0.21.7. It happens when clicking Play after opening a video, but it's not often. Next time I see it happen I will note the video and share it here.

**Comment by HanoJing** [comment]
Hi all,
I have the same device (Xiaomi Redmi 6A) as xxkfqz from 
LineageOS 17.1 is running on mine.
I get the exact same issue since version 0.21.14

########
Resolution:

Playing the video in the background works (Sound works).

So I selected the WebM aswell as 3GP video formats instead of MPEG4 and now, many videos work but only older ones seem to work. Ones younger than one year may not work, according to my tests.
########

In 0.21.13 a Little amount of videos would not work and throw the error.

Keep in mind that the CPU of the Xiaomi Redmi 6A is armv7l which is 32-bit, this may be a reason for the occurance.

**Comment by shoffmeister** [comment]
> Hello, does this issue still occur on the latest version?

I am afraid, but I have lost access to the original hardware, the Sony Xperia Z2 Tablet WiFi. I am therefore unable to retest.

**Comment by opusforlife2** [comment]
Alright. Closing as obsolete, then. Thanks for confirming!
