### ISSUE TITLE
reCAPTCHA challenge

### ISSUE THREAD

**Issue by tchnonsvvy** [TeamNewPipe/NewPipe#5427]
![Screenshot_20210114-134109_NewPipe](https://user-images.githubusercontent.com/77541726/104816365-aeb41a00-57e8-11eb-9685-420b81855382.jpg)

### Checklist

- [x] I am using the latest version - 0.20.8
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open app click on any yt video and immediately the captcha challenge appears
2. If the challenge instructions are followed, the main yt web homepage will appear inside newpipe app and the yt webpage is functional. 
3. ALL yt videos trigger this, whether trying to access from newpipe app...or...trying to access newpipe app FROM yt via "Share". 

### Actual behaviour
see above

### Expected behavior

Normal newpipe experience 

### Screenshots/Screen recordings
attached

No error report generated. App behaves as if this is normal.

### Logs
na

Na

### Device info Android 10

 - Android version/Custom ROM version: android 10
 - Device model:samsung a11

**Comment by Stypox** [comment]
This IS normal. Your connection generates ReCAPTCHAs and NewPipe shows a webview to allow you to solve them

**Comment by tchnonsvvy** [comment]
Hello!
Thanks for your reply.
    But solving the CAPTCHA and thus opening the YouTube webpage inside
NewPipe makes all of the NewPipe features such as play in background,
download, or add to NewPipe playlist non-existent.
    Since this IS normal, I was unaware that it was because I couldn't find
anything about it in the threads, is there not some trick I can do on my
phone to get around it?
    This situation showed up literally over night. It just started without
warning one morning without having made any updates or changes to my phone.
Any help would be appreciated.
Thank You

**Comment by TobiGr** [comment]
did you press the checkmark in the top right after solving the CAPTCHA?

**Comment by tchnonsvvy** [comment]
Oops😬 🤭 . I had a toggle from another app parked there. I apologize for
not being more diligent. Sorry to take up everybody's time. I will be more
careful next time.
Thank You

**Comment by Abdulee** [comment]
Hello I am having an issue similar to this I solve the captcha the checkmark turns green and then I hit the checkmark in the top right corner of the app and then the captcha opens again. My version is the same as the person who opened the issue
