### ISSUE TITLE
Toast notification when download started

### ISSUE THREAD

**Issue by illustribe** [TeamNewPipe/NewPipe#5428]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think having a toast notification for when a download has started would be useful. Sometimes I wonder if I clicked correctly or just closed the download prompt without having it started, and then I have to go to downloads screen to double-check... That's it! :)

#### Is your feature request related to a problem? Please describe it

No

#### How will you/everyone benefit from this feature?

I think toast notifications are quite widespread and standard and users maybe used to them or waiting for them...

**Comment by WoodyMats** [comment]
Hello! I'd like to work on this enhancement. Can i assigned to this issue? :)

**Comment by XiangRongLin** [comment]
@WoodyMats Go for it

**Comment by WoodyMats** [comment]
#5519 I made a pull request that contains code which has this enhancement. :)
