### ISSUE TITLE
Display non-English READMEs like the English one

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#5432]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

When you click other READMEs on the main page it's displayed differently (a bit ugly and confusing) like it's not recognized as a Readme. It would be great if when users switch the language the Readme is displayed like the English one. Of course that's if it's possible on GitHub.

#### Additional context

*non-English Readme:
![Screenshot_20210116-201249](https://user-images.githubusercontent.com/59365236/104818581-843e7d00-5839-11eb-8937-5ecdc70f00cc.png) 

*English Readme:
![Screenshot_20210116-201158](https://user-images.githubusercontent.com/59365236/104818584-89033100-5839-11eb-8947-77f0508d6e6f.png)

#### How will you/everyone benefit from this feature?

It's more consistent and it has the Releases at the bottom plus the user won't think they opened another page.

**Comment by mhmdanas** [comment]
Unfortunately, that's something we can do nothing about since GitHub doesn't support it.
