### ISSUE TITLE
Bluetooth audio sync

### ISSUE THREAD

**Issue by drov-drov** [TeamNewPipe/NewPipe#5440]
Aim: Add bluetooth audio sync option to internal audio player of NewPipe
Result: It will be very useful feature for bluetooth-headphones-users

**Comment by HTSamurai** [comment]
I'm assuming this would make the audio come out slightly early?

**Comment by mhmdanas** [comment]
I use Bluetooth headphones myself, and I don't think I've ever noticed something odd. What does this "syncing" feature do exactly? Is it like @HTSamurai says?

**Comment by mhmdanas** [comment]
Anyway, @drov-drov please open a new issue and follow the template instead of removing it.
