### ISSUE TITLE
Longpress option for video to directly go to the belonging channel

### ISSUE THREAD

**Issue by Plugdemholes-Imeanpatchdembugs** [TeamNewPipe/NewPipe#5444]
Hi,
I've noticed when you randomly browsing with the current model of mainscreen for search and "pop-up bar" for video consumption, it gets a bit tricky if you currently have a video running or one you want to finish, that if I find a video from another channel but first want to know what this channel's main subjects are, then I currently only have the option to either directly search for the channel again, so I get the channel icon that directly transports me to this channels videos. Or to click the new video directly of the channel I found, which then, of course, loads a new video, before I have the option to just directly get a link via longpress to this channel's YT video page.

Would be a nice little addition if, in the longpress menu, there was some option, to just directly go to this video's YT channel overview page. :)

Happy and healthy new year 2021!

**Comment by mhmdanas** [comment]
Thanks for opening an issue! Could you please open a new issue without removing the template, instead following it properly?

**Comment by Plugdemholes-Imeanpatchdembugs** [comment]
Yes, just saw after posting the three boxes have to remain?
Sry, only my second post ever ^^"

**Comment by mhmdanas** [comment]
No worries. See [this comment](https://github.com/TeamNewPipe/NewPipe/issues/5443#issuecomment-761839245) for some help on this topic.
