### ISSUE TITLE
mp3/m4a cover pic feature request

### ISSUE THREAD

**Issue by brnwlshubh** [TeamNewPipe/NewPipe#5445]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
While downloading mp3/m4a file the cover image of the image is blank/empty.
I want to request the feature update of downloading the video thumbnail as a cover image of that(mp3/m4a) file.

The alternative app that has this feature is YMusic.
It can download Thumbnail as a Cover Image in the file itself.

#### Is your feature request related to a problem? Please describe it
 Yes As I download the mp3/m4a file it has no image while playing in Mp3 player it doesn't look good. 
That is why I am requesting this feature update.

#### How will you/everyone benefit from this feature?
This feature is available only in YMusic as in my knowledge.
I want the Newpipe as an Exclusive & All In One Video & Audio related app(like downloading,surfing,etc.)app.
And also it is a popular,free,open source app.
That is why. I ❤ Newpipe.

**Comment by shivasagarrao** [comment]
Duplicate of #4341

**Comment by mhmdanas** [comment]
Again, that issue is quite general. It requests addition of all sorts of metadata, but this one requests one specific type, so I think this should stay open.

**Comment by brnwlshubh** [comment]
How much time it will take to implement in the app?

**Comment by mhmdanas** [comment]
That's almost impossible to predict. Also, there is no way to know when somebody will even start working on implementing this.

**Comment by brnwlshubh** [comment]
No issue. I'll help Newpipe as much as possible for improving and stabilisation of app.🤗
Thank you.

**Comment by brnwlshubh** [comment]
@mhmdanas I found 2 github apps which has this same feature.
Can I share the link for further info.?

**Comment by brnwlshubh** [comment]
@Stypox @TobiGr Sir please try to implement this in next release(after 0.20.9) or ASAP.
Thanks in advance.

**Comment by mani445** [comment]
> ### Checklist
> * [x]  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
> * [x]  I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
> * [x]  This issue contains only one feature request. I will open one issue for every feature I want to request.
> 
> #### Describe the feature you want
> While downloading mp3/m4a file the cover image of the image is blank/empty.
> I want to request the feature update of downloading the video thumbnail as a cover image of that(mp3/m4a) file.
> 
> The alternative app that has this feature is YMusic.
> It can download Thumbnail as a Cover Image in the file itself.
> 
> #### Is your feature request related to a problem? Please describe it
> Yes As I download the mp3/m4a file it has no image while playing in Mp3 player it doesn't look good.
> That is why I am requesting this feature update.
> 
> #### How will you/everyone benefit from this feature?
> This feature is available only in YMusic as in my knowledge.
> I want the Newpipe as an Exclusive & All In One Video & Audio related app(like downloading,surfing,etc.)app.
> And also it is a popular,free,open source app.
> That is why. I ❤ Newpipe.

Thanks @brnwlshubh for creating this issue.
Music library may have many songs.Favorite Songs can easily identify by its cover pic. Song can be identify by reading file name,hearing is other. 
Only a rare asking this feature.
I searched Google "cover art new pipe" this came as result.
Link⬇️
https://amp.reddit.com/r/NewPipe/comments/bmv0c9/video_thumbnail_as_cover_art_for_audio_downloads/
Many genius coders of new pipe thinking that cover art is useless feature.But I don't know why?
Thank you dev.
Sorry for my bad English.

**Comment by mhmdanas** [comment]
> Many genius coders of new pipe thinking that cover art is useless feature.

Please don't assume that just because the devs aren't working on something, they think it's useless. We now have 850+ issues on our issue tracker, and the number of active devs can be counted on one or two hands. Please cut them some slack.

**Comment by mani445** [comment]
Given below screenshot of some app.
Find whatsapp
![rsz_what-is-an-app](https://user-images.githubusercontent.com/73056033/110141601-58805200-7dfb-11eb-94ac-b5d6edaf66cc.jpg)

I found whatsapp by 
1. Seeing icon(image art)
2. Reading name under it.

**Comment by mhmdanas** [comment]
To be clear, I was not commenting on the merit of the idea. I was just trying to make it clear that there are hundreds of issues, but the active devs are small in number.

**Comment by Stypox** [comment]
This can't be done without embedding ffmpeg (too big for a lightweight app), so unless someone finds another way to do this this will never be implemented.

**Comment by mani445** [comment]
> This can't be done without embedding ffmpeg (too big for a lightweight app)
Use ymusic ffmpeg.

**Comment by mangoepic** [comment]
> This can't be done without embedding ffmpeg (too big for a lightweight app), so unless someone finds another way to do this

https://github.com/TeamNewPipe/NewPipe/issues/183

There seem to be some ideas in this thread

**Comment by brnwlshubh** [comment]
> This can't be done without embedding ffmpeg (too big for a lightweight app), so unless someone finds another way to do this this will never be implemented. I'm sorry for this.

@Stypox Sir Please look into

**Comment by mhmdanas** [comment]
Why was this closed?
