### ISSUE TITLE
Longpress (menu) option for direct channel videos overview access (tablet optimisation)

### ISSUE THREAD

**Issue by Plugdemholes-Imeanpatchdembugs** [TeamNewPipe/NewPipe#5447]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
A longpress menu option that takes me directly to the channel's videos overview (YT channel content).

#### Is your feature request related to a problem? 
Currently, with the 1.mainpage for searching and the 2."pop-up bar" for currently playing video, there's no way to access **another channel's** videos overview, unless a) I'm starting a new search for the channel or b) starting a new video to get access to the channel's name with a direct link to the channel's videos overview.

Other option:
UI element in the "pop-up bar" video player to jump back again to the previous video.
Currently, NewPipe does not keep track of the previously shown video, backtracking only happens between YT channel page and Newpipe start page.  

#### Additional context
This is all in relation that I most likely don't want to close my current video or search for the newly found channel, since the longpress option is much faster than typing.

#### How will you/everyone benefit from this feature?
Most of the time I'm using NewPipe on a tablet, typing even with optimized keyboard spacing is rather slow in comparison to a smartphone. Therefore I think a longpress menu option for direct YT channel's videos overview would come in handy and extend the usefulness for tablets without greater changes.

Happy and healthy new year 2021!

**Comment by SameenAhnaf** [comment]
Could you please link issue https://github.com/TeamNewPipe/NewPipe/issues/5783 and https://github.com/TeamNewPipe/NewPipe/issues/5836 too? That would be highly appreciated.
