### ISSUE TITLE
Better search filter

### ISSUE THREAD

**Issue by Falcon342** [TeamNewPipe/NewPipe#5448]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
 a better search filter similar to the one in the YouTube app for android

#### Additional context

![Screenshot_20210117-214159_1](https://user-images.githubusercontent.com/75455018/104866697-2ed3a000-590d-11eb-877b-803c88791c3b.png)

#### How will you/everyone benefit from this feature?

This feature would allow users to get better and more accurate search results from Newpipe

**Comment by XiangRongLin** [comment]
duplicate #2251
