### ISSUE TITLE
[Feature Request] Watch a Video While Scrolling Through Comments

### ISSUE THREAD

**Issue by DataStream3** [TeamNewPipe/NewPipe#5450]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be cool for the video to anchor, allowing you to scroll through the comments while also being able to watch the video.

#### Is your feature request related to a problem? Please describe it

The problem is, when scrolling through the comments the video doesn't anchor and you have to scroll back to the top to be able to watch the video.

#### Additional context

![alt text](https://i.ibb.co/z5mjJJk/Feature-Request.png)

#### How will you/everyone benefit from this feature?

This feature will help people read comments while they are watching a video. Makes a video a lot more enjoyable.

**Comment by XiangRongLin** [comment]
#4484

**Comment by skyGtm** [comment]
@DataStream3  Use some hacky way until update comes as requested.
you can use Popup window, resize and reposition at the top. Now you can scroll comments while video playing at the top.

https://user-images.githubusercontent.com/50160188/104988561-86265d00-5a40-11eb-82bb-e2d092a1efee.mp4

**Comment by Shadow-302** [comment]
> @DataStream3  Use some hacky way until update comes as requested.
> you can use Popup window, resize and reposition at the top. Now you can scroll comments while video playing at the top.
> 
> https://user-images.githubusercontent.com/50160188/104988561-86265d00-5a40-11eb-82bb-e2d092a1efee.mp4
> 
> 

Nice. Never really thought about this. 😅
