### ISSUE TITLE
Feed fetching errors has bad UI/UX

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#5452]
### Checklist

- [x] I am using the latest version
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open Feed
2. Pull down to update
3. Some feed(s) fail to update

### Actual behaviour
Network Error - Retry
No videos are shown, even if 99% of feeds successfully fetched.
Some PeerTube feeds repeatedly fail, probably because of enterprise firewall and alike.

### Expected behavior
Successfully retrieved feeds/videos are shown
The error would show on top of the list like: "xx out of yy channels failed to update. Pull down again to retry"

**Comment by MD77MD** [comment]
I keep getting this error too. in my case, the videos do show up but i would keep getting an error message after every action within the app. 

i usually solve this by coloring the app after updating feed them reopening it. or i don't fetch feed of groups that have those problematic subscriptions, as i yet to identify witch channels are causing the problem.


I wich if newpipe would report or even move out such channels to a dedicated group so the user can then decide what to with them.

**Comment by ildar** [comment]
Excuse me, I don't see the problem fixed for *network* errors.
I see the PR mentioned above fixes terminated channels only (by
description).
Can anybody confirm?

**Comment by opusforlife2** [comment]
@ildar Do you still encounter the same errors with the APK in that PR?

**Comment by ildar** [comment]
I see that PR was merged and a new release happened since. I use it and see
no changes.

**Comment by TobiGr** [comment]
The PR is going to be included in 0.21.6

**Comment by ildar** [comment]
Yes, I see definitive improvement in this. Now a user can see the feed even
if some errors occurred.
But that dialog is quite annoying: would be nice to have a checkbox "Don't
show again".
