### ISSUE TITLE
[Secondary controls] Scrolling bug when opening links at the top of the description of a video

### ISSUE THREAD

**Issue by TiA4f8R** [TeamNewPipe/NewPipe#5453]
### Checklist
- [x] I am using the latest version - 0.20.10
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Make sure that description tab is the default tab before trying to reproduce the bug.
2. Open a video with links at the top of its description.
3. Observe app's behavior.

### Actual behavior
Description is scrolling, without opening the link sometimes.

### Expected behavior
Description links just open without scrolling. This bug isn't present on 0.20.9 release.

### Screenshots/Screen recordings
https://user-images.githubusercontent.com/74829229/104947010-4bc6ac80-59bb-11eb-8a46-a91f11a7b526.mp4

If the description tab is the default tab before opening a content (after an app start), the description view scrolls a little bit, like in this screen recording:

https://user-images.githubusercontent.com/74829229/107982192-e36fe880-6fc3-11eb-808a-fcb41347b241.mp4

### Device info
 - Android version/Custom ROM version: EMUI 10 / Android 10
 - Device model: Honor 9X

**Comment by Stypox** [comment]
Does [this apk](https://github.com/TeamNewPipe/NewPipe/suites/1857209245/artifacts/36065666) from ci in #5460 fix the issue?

**Comment by TiA4f8R** [comment]
Unfortunately, no. See screencast below:

[No fix fix-scroll-description apk.mp4.zip](https://github.com/TeamNewPipe/NewPipe/files/5836484/No.fix.fix-scroll-description.apk.mp4.zip)

**Comment by Stypox** [comment]
I don't know how to fix this. Android seems to like moving views around when giving focus to them (even though they are already visible), and I don't know how we could prevent that. @vkay94 do you have any idea how this could be solved? I found [this SO](https://stackoverflow.com/questions/5375838/scrollview-disable-focus-move) but wasn't able to find a good solution (i.e. I could disable automatic scrolling when tapping on links but then selecting would not work)

**Comment by vkay94** [comment]
@Stypox I'll take a look into it (I have to look into the implementation first)

**Comment by Stypox** [comment]
@vkay94 this also happens when the description is the first tab that shows up when opening a video

**Comment by vkay94** [comment]
Perfect timing :') So it isn't intentional (I was focussing on the tab switch). To fix it (scrolling on tab) you just have to add `clickable="false"` to `TextView` with id = "detail_description_view" in fragment_details layout.

**Comment by Stypox** [comment]
Does [this other apk](https://github.com/TeamNewPipe/NewPipe/suites/1886112616/artifacts/36861859) from ci in #5460 fix the issue?

**Comment by TiA4f8R** [comment]
@Stypox No, it doesn't but there is a change: when clicking the description tab, the description view doesn't scroll to the top of the screen. However, clicking on a link scrolls the description view to top of the screen.

**Comment by Stypox** [comment]
@TiA4f8R then I can't reproduce

**Comment by Stypox** [comment]
@TiA4f8R I pushed another commit to #5460, could you test it when it gets built? I tried with something else

**Comment by TiA4f8R** [comment]
@Stypox Same result as the previous :(

**Comment by TiA4f8R** [comment]
@Stypox @vkay94 With 0.20.10, this bug is now more strange. It just scroll a bit if the description tab is the default tab before opening a content for the first time you open an instance of the app. See the second screencast in the top comment.

**Comment by Stypox** [comment]
Ok, so I tried to investigate this a little bit more. It seems like this is not a bug in NewPipe's code, but in how things are implemented in Android. When text in a `TextView` is made selectable, and the `TextView` is in a layout where the app bar (i.e. the player, in NewPipe's case) collapses when scrolling, things start behaving strangely. Actually, I tried [another simple test app](https://github.com/mishra3452/coordinatorlayout-example), which uses a similar scrolling behaviour to NewPipe's, and as soon as I add `isTextSelectable="true"` [here](https://github.com/mishra3452/coordinatorlayout-example/blob/master/app/src/main/res/layout/content_scrolling.xml#L11-L15) the flickering behavior appears. I doubt there is any better way to solve this other than making the text not selectable and then think of another way to let the user copy the text.

**Comment by Stypox** [comment]
Could you confirm that this APK fixes the scrolling bug (even though it does not allow selecting, and tapping links does not show the white background underneath)?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6239017/app-debug.zip)

**Comment by TiA4f8R** [comment]
@Stypox Yes
