### ISSUE TITLE
Missing strings (Weblate)

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#5454]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. ~~Search any video and the published time/date (e.g 18 hours ago, 1day/month/year ago) of the content is stuck with English even though you switched the language (in this case Somali)~~ Edit: This happened to be social date formatter PrettyTime which NewPipe uses so I translated the language for the project. This is SOLVED.
2. "Next" on video page acts the same way.
3. "Cancel" key on the app language picker (edit: and some other places i just found out) is the same although cancel in other places of the app is translated fine. 
Edit: the cancel not being translated button isn't limited to language picker but also on other places like creating new chanel groups

See screenshots for context.

### Actual behaviour

"Next" on video page isn't following the app language, that's due to "Next" string missing from translation strings on Weblate.

The "Cancel" key on the app language picker and some other places in the app.

### Expected behavior

Complete strings on Weblate for the app to be consistent.

### Screenshots/Screen recordings

~~*on search (published time)~~ Edit: SOLVED.

*on video page ("Next")
![](https://user-images.githubusercontent.com/59365236/104948402-4cb50980-59ce-11eb-9622-bfa176837263.png)

*on creating new chanel groups and some other places ("Cancel") :

![Screenshot_20210119-143134](https://user-images.githubusercontent.com/59365236/105029423-66546080-5a63-11eb-929f-64f886bfddb0.png)

@TobiGr

**Comment by TobiGr** [comment]
@stypox any idea, why `exo_controls_next_description` is used? I did not noticed, that it was changed.
I suggest to use something different, because "next track" is not always true (e.g. the queue can contain other streams which are up next). What about "related content" or "similar content" or "related streams"?

**Comment by nadiration** [comment]
> @stypox any idea, why `exo_controls_next_description` is used? I did not noticed, that it was changed.
> I suggest to use something different, because "next track" is not always true (e.g. the queue can contain other streams which are up next). What about "related content" or "similar content" or "related streams"?
> 
> About the upload time: that seems to be a bug, because some lib should be responsible for that.

The "Cancel" key on the app language picker is also the same although cancel is translated fine on other places in the app

**Comment by TobiGr** [comment]
In the content settings? That is a standard android dialog We cannot change that.

**Comment by nadiration** [comment]
> In the content settings? That is a standard android dialog We cannot change that.

The cancel button on the bottom of the languages list on Settings > Contents > App language? I just checked with some other languages and it changes on some of the languages and some it just stays cancel.

**Comment by TobiGr** [comment]
I guess that depends on the languages which are installed on your device.

**Comment by nadiration** [comment]
> I guess that depends on the languages which are installed on your device.

Probably. This one isn't big deal anyway. Thanks.

**Comment by Stypox** [comment]
@TobiGr 11e048abb1fc1eee6588b93da87657d197381c27 is the responsible commit: I assumed that the exoplayer strings were translated in all languages. I just tried a couple of languages and the strings were all translated, but apparently ExoPlayer does not fully support Somali (i.e. some strings are translated, some others not). The commit should probably be reverted.

**Comment by nadiration** [comment]
@TobiGr i think the untranslated "cancel" is a bug and it's not related to standard Android dialog because i just saw some other normal in-app dialogs that the word didn't change like when creating a new channel groups on subscriptions tab

*Untranslated "Cancel" on creating new chanel groups: 
![Screenshot_20210119-143134](https://user-images.githubusercontent.com/59365236/105029622-a4ea1b00-5a63-11eb-9c5a-5b079fee027a.png)

**Comment by XiangRongLin** [comment]
@nadiration It's the android cancel. see line 210 and 218

https://github.com/TeamNewPipe/NewPipe/blob/9a65f02d5bbab2e224083db3ab8e8fe5ab34d84e/app/src/main/res/layout/dialog_feed_group_create.xml#L204-L218

**Comment by nadiration** [comment]
@XiangRongLin 
In the code they are both android strings but why is one string (create) changed and the other (cancel) not??

**Comment by XiangRongLin** [comment]
@nadiration the "cancel" is an android string (prefixed with android), the create is our own one (prefixed with string). So i would assume the same thing that TobiGr said:

>I guess that depends on the languages which are installed on your device.

**Comment by nadiration** [comment]
@XiangRongLin  > the "cancel" is an android string (prefixed with android), the create is our own one (prefixed with string). 

Can we use our own "cancel" string instead of prefixed android string?

**Comment by nadiration** [comment]
@XiangRongLin  >the "cancel" is an android string (prefixed with android), the create is our own one (prefixed with string). 
> 
Can we use our own "cancel" string instead of prefixed android string?

**Comment by nadiration** [comment]
Can we use our own "cancel" string instead of prefixed android string?
> @nadiration the "cancel" is an android string (prefixed with android), the create is our own one (prefixed with string). So i would assume the same thing that TobiGr said:
>

**Comment by nadiration** [comment]
@XiangRongLin Can we use our own "cancel" string instead of prefixed android string?
> @nadiration the "cancel" is an android string (prefixed with android), the create is our own one (prefixed with string). So i would assume the same thing that TobiGr said:
>

**Comment by nadiration** [comment]
@XiangRongLin Can we use our own "cancel" string instead of prefixed android string?
> @nadiration the "cancel" is an android string (prefixed with android), the create is our own one (prefixed with string). 
>

**Comment by XiangRongLin** [comment]
I'm against it. This should be fixed in Android not from us. Using our own would require translating it for all languages

**Comment by nadiration** [comment]
@XiangRongLin 🤦‍♂️ it's just one word which by the way is already translated for all languages as there are other local 'cancel' strings in the app and can be self-referenced lol do you know how many strings are translated everyday 

> I'm against it. This should be fixed in Android not from us. Using our own would require translating it for all languages

**Comment by nadiration** [comment]
@Stypox any solution??
> @TobiGr [11e048a](https://github.com/TeamNewPipe/NewPipe/commit/11e048abb1fc1eee6588b93da87657d197381c27) is the responsible commit: I assumed that the exoplayer strings were translated in all languages. I just tried a couple of languages and the strings were all translated, but apparently ExoPlayer does not fully support Somali (i.e. some strings are translated, some others not). The commit should probably be reverted.

**Comment by nadiration** [comment]
@TobiGr, @XiangRongLin, @Stypox    I fixed the date/time display as it was PrettyTime social date structure missing Somali language so I translated the language for the project and now it works fine. The only problem is the "Cancel" string which is still stuck with Android prefixed string. This makes the app inconsistent and it's really confusing some old people that only know Somali and use the app regularly. They always ask me about it and it confuses them. As @Stypox mentioned this can be fixed by reverting the commit he mentioned or simply using our own local string. 
Thank you for your attention.

**Comment by nadiration** [comment]
@TobiGr, @XiangRongLin , @Stypox   I fixed the date/time display as it was PrettyTime social date structure missing Somali language so I translated the language for the project and now it works fine. Now the remaining problems are "Next" and "Cancel" key. the "Cancel" string which is still stuck with Android prefixed string. This makes the app inconsistent and it's really confusing some old people i know that only know Somali and use the app regularly. They always ask me about it and it confuses them. As @Stypox mentioned this can be fixed by reverting the commit he mentioned or simply using our own local string. 
Please consider this. Thank you for your attention.

**Comment by Stypox** [comment]
The "Next" string should be fixed by exoplayer, not us. Maybe we could add the "Cancel" string, as it's just one string.

**Comment by nadiration** [comment]
> The "Next" string should be fixed by exoplayer, not us. Maybe we could add the "Cancel" string, as it's just one string.

@Stypox yeah man ok. Please fix the cancel string it's tiny but very important for us.

**Comment by Stypox** [comment]
Oh, the cancel string was actually already included in the translated strings in newpipe, we were just using the incorrect string in some places

**Comment by Stypox** [comment]
#6848 @nadiration
