### ISSUE TITLE
Feature request: Fill video to non 16:9 screens

### ISSUE THREAD

**Issue by Wiredframe** [TeamNewPipe/NewPipe#547]
There are numerous devices now that feature a non 16:9 screen. The LG G6 with it's 18:9 or the BlackBerry KEYone with its 3:2 screen.

Therefore it would be awesome to have a button to completely fill the screen, maybe even an option to set this behaviour as default. 

One more feature that would make NewPipe better than the native YouTube app.

**Comment by Zero3K** [comment]
I agree with this suggestion.

**Comment by theScrabi** [comment]
Sounds good :)

**Comment by djfoxer** [comment]
It's awsome feature! Please add this. LG G6, Samsung Galaxy S8 and more has 16:9 screens and fill button will be great future for NewPipe app!

**Comment by SkyzohKey** [comment]
Bump! Is this being worked upon? If not how where should I look for the class(es) in ordre to make a PR ?

**Comment by theScrabi** [comment]
Hi not yet. You might want to take a look at [this class](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java).

**Comment by SkyzohKey** [comment]
Ok did some quick search and it looks that it's super simple to do, as ExoPlayer supports it natively. Here are some links for reference before I do tests to see what's the best way to do that.

- [ExoPlayer `AspectRatioFrameLayout.java`](https://github.com/google/ExoPlayer/pull/3187/files#diff-1e339a4b00febd4473bc19e73fa52eb0)
- [NewPipe `VideoPlayer.java`](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java#L114)

**Comment by theScrabi** [comment]
The next beta release will feature the change of the zoom :D... Im going to relese it today so it will be online on fdroid in a few days.

**Comment by Androidphonetoucher** [comment]
@theScrabi You Sir are an officer and a gentleman! ;) Many thanks, this is awesome news!!

**Comment by Wiredframe** [comment]
Thanks so much :) 👍

**Comment by theScrabi** [comment]
Don't thank me thak @karyogamy, who wrote this feature:
https://github.com/TeamNewPipe/NewPipe/pull/1067

**Comment by Androidphonetoucher** [comment]
@karyogamy Thanks for your hard work on this, it's much appreciated! :)
