### ISSUE TITLE
live, video not available

### ISSUE THREAD

**Issue by alnkike** [TeamNewPipe/NewPipe#5477]
I am using the latest version - 0.20.8 

When i want to open a live music or other thing in live (search live music) the video doesn't appear, i have just an image with video not available.
I have try to change the video and audio format but it's the same.
I think this problem appears after 0.20.4 around 2 month.

![Screenshot_2021-01-22-17-00-22-020_org schabi newpipe](https://user-images.githubusercontent.com/77536807/105514721-20ea9a00-5cd4-11eb-96b7-5921876cf4fc.jpg)

### Device info

 - Android version/Custom ROM version:  android 11 RKQ1.200826.002
 - Device model:M2002J9G xiaomi mi 10 lite 5G

**Comment by HTSamurai** [comment]
Same thing on my Redmi 8 Android 10/MIUI11

**Comment by mhmdanas** [comment]
@alnkike thanks for opening an issue! Could you please open a new issue without removing the template?

**Comment by alnkike** [comment]
done thank you
