### ISSUE TITLE
Revamp the popup player

### ISSUE THREAD

**Issue by alienthief** [TeamNewPipe/NewPipe#5478]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The current popup player needs some revamp like:
1. Changing the bottom X button that closes the player by dragging towards it to an X inside the mini player (see screenshot for context). This one is a hustle sometimes you should try multiple times to get that spot that highlights the player in red and closes
2. Smooth switching between popup and regular player. Currently when you swith between the two players it stops for a second
3. The resizing text when adjusting the popup size needs to go, everybody knows they are resizing!

#### Is your feature request related to a problem? Please describe it

Yes because sometimes inconvenience is a problem.

#### Additional context

A popup player from another video player (MX):

![Screenshot_20210122-193051](https://user-images.githubusercontent.com/77839854/105519142-23f08500-5cea-11eb-805c-0b2d70acba94.png)

#### How will you/everyone benefit from this feature?

People will benefit from this because they will no longer be hustling to close the mini player they will just  click the x button in the player to close, they won't experience that delay at the player switch and finaly they won't see that big ugly resizing text when adjusting the player size.

**Comment by HTSamurai** [comment]
Great idea! This would be a welcome addition for me

**Comment by skyGtm** [comment]
Point 1 has been fixed https://github.com/TeamNewPipe/NewPipe/pull/5458

**Comment by alienthief** [comment]
> Similar issue corresponding to point 1 is [#5455 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/5455#issuecomment-762604619)
> This has been fixed #5458
> Wait until release version of the app

The issue/comment you referenced which is yours btw is no way close to this and also that PR you referenced is about "fixing x close button animation". I don't know if you understood what I'm talking about but you were supposed to read before commenting

**Comment by vkay94** [comment]
Your second point (smooth switching) is not limited to the popup, it happens for all kinds of types. There is also a duplicate:  #5016

**Comment by opusforlife2** [comment]
It's actually older than that: #2863.

**Comment by mhmdanas** [comment]
@alienthief this issue requests multiple features. Could you please open separate issues for each of those (except 2, since there's #5016 for that)?

**Comment by alienthief** [comment]
@mhmdanas 🤦‍♂️ it's a revamp about one specific feature. popup player. it was supposed to have multiple points that's why i wrote "revamp" on the title please reopen the issue

**Comment by mhmdanas** [comment]
It doesn't matter that we're talking about one existing feature. The issue is precisely with the multiple points.

**Comment by alienthief** [comment]
@opusforlife2 what do you think about @mhmdanas point of closing this issue?

**Comment by opusforlife2** [comment]
@alienthief Of your 3 points, point 2 is a duplicate as vkay and I linked already.

Anyway, this is not a revamp. It's two separate feature requests/bugs. Why? Because the code/UI changes aren't related at all. A dev could browse through issues, stumble on one of those, and choose to implement the removing "resizing" one, for example, and it would have no effect on the other.

So it is better that there are two different issues for it.

**Comment by B0pol** [comment]
I don't think we should change the popup player UI. It's a legacy piece of code IMO. 

We should use Android's Picture in Picture API instead (Android 7/8+). There is an issue for that: https://github.com/TeamNewPipe/NewPipe/issues/2223

**Comment by SameenAhnaf** [comment]
It's made intentionally a little complicated only for avoiding mistakes and accidents.
