### ISSUE TITLE
improvement in visual section

### ISSUE THREAD

**Issue by alexspain632** [TeamNewPipe/NewPipe#5488]
They should add a button to like or dislike as well as leave a comment in the videos, and leave the library section so that the videos you like and the playlists are displayed, and the video cells that are larger

**Comment by HTSamurai** [comment]
Those would have to be local but I'd love that!

**Comment by mhmdanas** [comment]
@alexspain632 see #5147 and #5159. Also, please don't remove the template when opening an issue. Thanks!
