### ISSUE TITLE
Use Android Download Manager for files downloading ?

### ISSUE THREAD

**Issue by SkyzohKey** [TeamNewPipe/NewPipe#549]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

The title should be pretty self explanatory I guess :grin:.

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/319
