### ISSUE TITLE
Replaying livestreams

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#5499]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

When i start watching a livestream and would like to go back to the beginning i could only watch like the ladt 30 seconds. It would be nicer to have the ability to scroll back all the way.

#### Is your feature request related to a problem? Please describe it

No.

#### How will you/everyone benefit from this feature?

People wouldnt have to wait for the livestream to end just to watch the first parts.

**Comment by demonff1** [comment]
I would also like to add that common features like resolution or speed changing option are not available in Livestream.
Many a time Livestream are in 360p or worse 240p. Would love to see Livestream from the beginning in newpipe in good resolution.

**Comment by B0pol** [comment]
duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1634

@demonff1 duplicate` `of #1239
