### ISSUE TITLE
[Feature request] Subtitles

### ISSUE THREAD

**Issue by rrooij** [TeamNewPipe/NewPipe#55]
Subtitles are currently not supported. It would be nice to have this feature.

**Comment by theScrabi** [comment]
I'll keep it in mind.

**Comment by timofonic** [comment]
Thanks!

I often use them to improve my English. Even the autogenerated ones can help me understanding spoken English many times.

**Comment by theScrabi** [comment]
Hm could someone figure out how to extract subtitles? And how to read those?

**Comment by rrooij** [comment]
@theScrabi
youtube-dl is able to extract the subtitles, maybe it is worth looking at their source code.

As for reading them, I don't know. They are SRT-formatted, they use another file extension, but it is basically the same how Youtube uses it.

**Comment by timofonic** [comment]
If you are able to add that option (I hope so!), please consider automatic
subtitles. Despite they might be awful, it often helps me to understand
spoken English.

**Comment by timofonic** [comment]
Did anyone looked into this?

**Comment by theScrabi** [comment]
Not yet.

**Comment by timofonic** [comment]
And now? ;)

**Comment by theScrabi** [comment]
Still no. This may take a while until i finaly find time to care about that. Still there are hundred other things to do first.

**Comment by KOLANICH** [comment]
Here is the implementation http://google2srt.sourceforge.net/en/

**Comment by theScrabi** [comment]
Good thanks :)

**Comment by ZatsuneNoMokou** [comment]
Any change?

**Comment by theScrabi** [comment]
Yep exoplayer actually supports subtitles, so at least its possible to implement something like that. But unless we get proper exoplayer support, it's no worth speaking about it. So far exoplayer support is still an experimental early bird.

**Comment by theScrabi** [comment]
I wished NewPipe development would go faster :/

**Comment by rrooij** [comment]
@theScrabi What about adding the label `help needed` to this issue or add a TODO list with things that need to be done? That way, volunteers can quickly get an overview of what needs to get done. There's an overview in `README.md` but it doesn't state what the status of those developments is.

**Comment by timofonic** [comment]
I would love subtitles, including autmatic ones. Despite they are inaccurate, they help me a lot to understand spoken English!

Also, please see this too!

https://github.com/agermanidis/autosub

**Comment by theScrabi** [comment]
That autosub thing is Python we cant integrate it into NewPipe.

Also guys if you want to have subtitles, and asome other advanced features help me make exoplayer possible :). One thing I'd really like to so see, and I think its not that hard, is a new UI for the new player. With version 0.7.7 I'll deliver an experimental support for exoplayer, than you will see how it looks. However the UI of the current player is kind of a mess, I don't like that ugly MediaInterface, and the hide/show UI thing never worked correctly. I'd really appreciate it if someone could try to help me a bit with that :)

**Comment by Paviluf** [comment]
That's a really useful feature. I hope it will be implemented soon :)

**Comment by theScrabi** [comment]
Still I had to implement exoplayer in order to make this feature work, it's just gowing forward realy realy slow :/

**Comment by niteshkumardebnath** [comment]
I will just +1 it because that's the best I can do :D

**Comment by theScrabi** [comment]
Yea this should come :)

**Comment by tonakriz** [comment]
Ive checkes how 'youtube-dl' gets its subtitles, it's actually pretty simple method, even without understanding python, I am sure it's pretty easy to implement, since its just loading two files and parsing them.

Python code from youtube-dl:

     def _get_subtitles(self, video_id, webpage):
            try:
                subs_doc = self._download_xml(
                    'https://video.google.com/timedtext?hl=en&type=list&v=%s' % video_id,
                    video_id, note=False)
            except ExtractorError as err:
                self._downloader.report_warning('unable to download video subtitles: %s' % error_to_compat_str(err))
                return {}

            sub_lang_list = {}
            for track in subs_doc.findall('track'):
                lang = track.attrib['lang_code']
                if lang in sub_lang_list:
                    continue
                sub_formats = []
                for ext in self._SUBTITLE_FORMATS:
                    params = compat_urllib_parse_urlencode({
                        'lang': lang,
                        'v': video_id,
                        'fmt': ext,
                        'name': track.attrib['name'].encode('utf-8'),
                    })
                    sub_formats.append({
                        'url': 'https://www.youtube.com/api/timedtext?' + params,
                        'ext': ext,
                    })
                sub_lang_list[lang] = sub_formats
            if not sub_lang_list:
                self._downloader.report_warning('video doesn\'t have subtitles')
                return {}
    return sub_lang_list

**Comment by wb9688** [comment]
@tonakriz: Could you implement it yourself and submit a PR to NewPipeExtractor?

**Comment by tonakriz** [comment]
@wb9688 I can try to

**Comment by tonakriz** [comment]
NewPipeExtractor supports subtitles from this moment. Would be great if someone could implement it to NewPipe.

**Comment by oxwivi** [comment]
This is one of my pain points for me as a regular viewer of TED talks. I can do a but of Java, so if you've any leads, do tell if there's anyhow I can help.

**Comment by theScrabi** [comment]
Well someone had to pull the subtitles out of the extractor, and put them into ExoPlayer.

**Comment by oxwivi** [comment]
What exactly is ExoPlayer in context?

**Comment by theScrabi** [comment]
ExoPlayer is the player framework we use to display the video.

**Comment by KOLANICH** [comment]
How about using subtitles and audio with external players like VLC?

**Comment by tonakriz** [comment]
[Here](https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file) is some help you might need. I am sorry for not working on this issue anymore, but I have a lot of work to do.

**Comment by moshpirit** [comment]
Not a developer but I found that [SimpleExoPlayer has SubtitleView](https://github.com/google/ExoPlayer/issues/2017#issuecomment-259633365) but I'm not sure if this is relevant enough since it's a 2016 Nov post. This said, [there's still a lot of issues related to the subs](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=is%3Aissue+subtitle)

**Comment by theScrabi** [comment]
We have exoplayer support this all isn't a big problem anymore. Just someone had to link things together :)
