### ISSUE TITLE
Clicking YouTube video TimeStamps on Video description and Comment Section shows different behaviour

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#5507]
### Checklist

- [x] I am using the latest version - v0.20.9_RC4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to any YouTube video
2. Press on Time Stamp @ video description
3. Press Time Stamp @ video comment  (if available)

### Actual behaviour

clicking TimeStamp on video description --> opens Action Picker
clicking TimeStamp on video comment --> opens Popup player

### Expected behavior

For now, I think it will be good to open Popup player in both cases.
Because some videos has long description and long comment list.
(i am telling it, because you( developers ) may have future plan to open timestamp in Main Player but i prefer a popup player
for description timestamp also)

Also, I like to mention that I know new version of NewPipe now support stream segments #5274 for description based timestamps. 
But I also prefer to click timestamps available at video description.

### Screenshots/Screen recordings

![Screenshot_2021-01-30-10-14-32](https://user-images.githubusercontent.com/50160188/106347675-9b28a900-62e8-11eb-9d6d-def50ee01580.png)

![Screenshot_2021-01-30-10-15-46](https://user-images.githubusercontent.com/50160188/106347677-9e239980-62e8-11eb-9b8a-39e0c9c696c1.png)

### Device info

 - Android version/Custom ROM version: 
 - Device model:

**Comment by demonff1** [comment]
I think it would be better to have customization on whether pop up player or main player. It should be left to the user end.
Personally I'd love the main player like the YouTube app tho 🙃

**Comment by Kohoshi12** [comment]
Maybe the timestamp should just follow the format the user is already using: main, audio or pop-up. It'll complicate the settings more than it's if that's the case.

**Comment by TiA4f8R** [comment]
The timestamps will be recognized by #5523 and will open the popup player when clicked like for comments (don't ask me to change the action, I don't have the knowledge to do it, so you will to wait that another person creates a PR for this).
