### ISSUE TITLE
Certain channels not appearing in search and their channel page only shows old videos

### ISSUE THREAD

**Issue by xuvatilavv** [TeamNewPipe/NewPipe#5509]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to the Trending view.
2. Search `GameGrumps` or `scholagladiatoria`.
3. Copy & paste the channel link from a browser into search because the channel did not appear.
4. Inspect the channel's videos.

### Actual behaviour

The correct channel is not present in the search results. After pasting the link to open the channel directly, only older videos are shown (2 or 3 weeks ago as the most recent video, other devices/official Youtube app show the channel having many newer videos as recent as 9 hours).

### Expected behavior

The correct channel appears at the top of the search results, and going to that channel page shows recent videos.

### Device info

 - Android version/Custom ROM version: latest OTA stock ROM
 - Device model: Pixel 3a

I'm posting this for a friend I was helping remotely, I didn't ask their Android version but can update with it tomorrow. I just know they're fully updated. They installed NewPipe about 2 weeks ago and the issue has been present since then.

Curiously, this doesn't happen with all channels. We also tried `lockpickinglawyer`, which appeared in search and showed all the latest videos on their channel page.

We've already tried rebooting, clearing the history & cache from within NewPipe, clearing NewPipe's cache from system settings, connecting to different networks, reinstalling NewPipe, and with Fast Mode both enabled and disabled. The only thing that had any different behavior is that enabling Fast Mode changed the timestamps from e.g. "3 weeks ago" to "2 weeks ago", but the videos were the same.

Related issue: #5372

**Comment by HTSamurai** [comment]
Using a VPN or changing my DNS server has fixed this for me

**Comment by ShareASmile** [comment]
@mhmdanas s This can be closed.

**Comment by AudricV** [comment]
Is it still an issue on 0.26.1?

**Comment by xuvatilavv** [comment]
We have tested with 0.26.1 and it works correctly now, thanks!
