### ISSUE TITLE
Opt-in/Out ACRA

### ISSUE THREAD

**Issue by strikersh** [TeamNewPipe/NewPipe#5511]
User should be able do choose if they do want to send crash reports without building from source (like f-droid do).

**Comment by mhmdanas** [comment]
Can you elaborate? Crash reports are not sent automatically at all.

**Comment by strikersh** [comment]
I've seen that ARCA is bundled in the official build, and not in f-droid. 
And since I haven't found any option to enable or disable it I thought it was automatic

**Comment by Stypox** [comment]
@strikersh ACRA is bundled in any build and its only purpose is to catch unhandled errors in order to be able to show you a report screen. No data is collected by ACRA itself at all, it is only used to handle uncaught exceptions.

**Comment by Stypox** [comment]
As @mhmdanas, data about crash reports is collected only if you choose to send the email from the report screen, and that's a totally different mechanism from ACRA (i.e. it just sends an email with the crash report information)

**Comment by strikersh** [comment]
My bad, I'll close the issue.
ClassyShark3xodus do report ARCA on both build.
I did discover that months ago and I might just have compared to the report on exodus website who says there is no tracker
