### ISSUE TITLE
Disable just the lock screen thumbnail or give some display options

### ISSUE THREAD

**Issue by gigiboeru** [TeamNewPipe/NewPipe#5513]
Hi,

As the title says, the lock screen thumbnail is too ugly - low resolution and it has no option to scale/center it etc.

I'd like to have the thumbnail just for the notifications.

A more customizable option for the lock screen is also welcomed, but I do realize that will take some time to be implemented, so for the first stage a simpler option to disable the thumbnail for the lock screen is really needed.

Thanks!

**Comment by Stypox** [comment]
This is not doable using MediaStyle notifications afaik

**Comment by mhmdanas** [comment]
Since this seems to not be possible, I'll be closing this issue. If you find a way to do this, feel free to open a new issue that follows the template properly and tell us how we can do it. Thanks!
