### ISSUE TITLE
Remove "Resizing" text from popup player

### ISSUE THREAD

**Issue by alienthief** [TeamNewPipe/NewPipe#5514]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The resizing text when adjusting the popup size needs to go, everybody knows they are resizing

#### Additional context

For context open a video in popup and resize it with your fingers.

#### How will you/everyone benefit from this feature?

People won't see that big ugly resizing text when adjusting the player size.

-------

I created a detailed revamp for popup player #5478  but wrongfully closed by @mhmdanas

**Comment by karkaminski** [comment]
I would like to do it. may I? :)

**Comment by alienthief** [comment]
@karkaminski Thanks. go ahead with it and create a PR
