### ISSUE TITLE
[Question] Is it really over for age-restricted content on NewPipe?

### ISSUE THREAD

**Issue by alienthief** [TeamNewPipe/NewPipe#5518]
Since Google has made some drastic changes to viewing age-restricted content on YouTube making it compulsory to login with your account inorder to access contents like the below video, is it over for age-ristructed content on NewPipe or are there any workarounds planned?

Context: https://m.youtube.com/watch?v=r4JWI4UDOrc

**Comment by nbmrjuhneibkr** [comment]
These changes aren't new, and they don't seem to apply to all age-restricted videos. I still see videos (including newly-uploaded ones) that can be accessed with usual methods.
As for the videos like this one - yt-dl should still be able to handle them (by allowing you to log in or import cookies), so it shouldn't be impossible to implement some similar solution in NewPipe.

**Comment by Zakkumaru** [comment]
Just throwing this out there, but maybe a module could be made to use nsfwyoutube in order to bypass login, if this is still an issue.

**Comment by Hoodlook** [comment]
Not even nsfwyoutube works anymore.

**Comment by FireMasterK** [comment]
The example link shows: "This video isn't available anymore"

**Comment by litetex** [comment]
Fixed by https://github.com/TeamNewPipe/NewPipeExtractor/pull/780

**Comment by bannovdaniil** [comment]
Again https://youtu.be/tIxMW_RSV_0
