### ISSUE TITLE
Freezes when downloading multiple videos

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#552]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

NewPipe freezes when I'm downloading multiple videos.

**Comment by theScrabi** [comment]
Have you tried to use fewer threads when downloading a video?
Also did you take a look at logcat when it happens?

**Comment by wb9688** [comment]
With less threads, it doesn't freeze completely, but then the UI is
responding very slow. Btw I haven't looked at logcat.

**Comment by theScrabi** [comment]
Hm, what smarthphone/android version are U using?

**Comment by wb9688** [comment]
@theScrabi: I'm using a Huawei ALE-L21 (aka P8 lite) with EMUI 4.0 (Android
6.0).

**Comment by theScrabi** [comment]
Hm maybe it's because of their specialized android :/
How much videos are you trying to download simultaneously?

**Comment by wb9688** [comment]
@theScrabi: At 2 videos, the UI is already responding a bit slower, at 3+
videos with 1 thread, the UI responding very slow and at 3+ videos with 3
threads, it freezes completely.

**Comment by theScrabi** [comment]
Hm no I can't confirm that.
Maybe it's related to your phone.

**Comment by wb9688** [comment]
@theScrabi: Hmm… how could I debug this?

**Comment by theScrabi** [comment]
logcat ... I doubt you have any other chance.

**Comment by mauriciocolli** [comment]
I'm assuming you have Android Studio...

You can use Method Tracing:
![trace](https://cloud.githubusercontent.com/assets/13389907/26029443/804e1644-380b-11e7-8385-2111d698e456.png)
It'll create a `.trace` file in the `<root of the project>/captures` folder, then you can send it here to us to analyze it.

PS: I tested 4+ videos downloads with 32 threads and didn't notice anything, and my phone is not one of the fastest

**Comment by wb9688** [comment]
@mauriciocolli: When I do that, the UI is already responding very slow when I'm downloading one video, but the CPU usage is only around the 20% and other apps work fine. Btw what devices are you using?

**Comment by mauriciocolli** [comment]
@wb9688 You have to start when is already slow (let it running 30s to 1min), the method tracing (at least in my device) slow down significantly the app.

That usage is not that high, but nevertheless a trace is good to see if something is suspicious comes up, and I'm using a Moto G1 with Android 7.1.2.

PS: Just to know, what is the other usages (Memory, GPU, network)?

**Comment by wb9688** [comment]
@mauriciocolli: The memory is around the 20-30 MB and the network is around the 0 KB/s. NewPipe has also crashed once and now I can't reproduce this behavior as reliably (and only with 4+ videos). You could find my trace [here](https://gist.github.com/wb9688/0be40b7c40b2a1e54a7454b435d375cf).

**Comment by mauriciocolli** [comment]
@wb9688 I think uploading to Gist killed the encoding (my traces have a binary part, below the text), can you check the file size?

**Comment by wb9688** [comment]
@mauriciocolli: I checked and the file is indeed fucked up, but I've already removed it locally, so I'll post a new one tomorrow.

**Comment by mauriciocolli** [comment]
I'll close this for now.
