### ISSUE TITLE
Searching yields no results

### ISSUE THREAD

**Issue by captaincupcakes** [TeamNewPipe/NewPipe#5520]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'search'

### Actual behaviour
whenever I used to search bar nothing comes up, it just says no results regardless of what I look for. 

### Expected behavior
 show what I am looking for in the search bar
![Screenshot_20210201-005134](https://user-images.githubusercontent.com/78338675/106420198-1f357a80-6428-11eb-9da7-68393aab86f5.png)

### Device info

 - Android version/Custom ROM version: android 10 build 58.0.A.28.51
 - Device model: sony xperia 5 II XQ-AS62

**Comment by mhmdanas** [comment]
What is your NewPipe version?

**Comment by captaincupcakes** [comment]
0.20.8

**Comment by mhmdanas** [comment]
That is quite odd; I can't reproduce. Perhaps this is related to #5279. I _think_ you're using Wi-Fi (from the screenshot), but just to be sure, if you're using mobile data, can you see if this issue is present with Wi-Fi?

**Comment by captaincupcakes** [comment]
Am using WiFi..

**Comment by captaincupcakes** [comment]
Wifi or LTE don't matter,it still shows the same results regardless of what I look for.
Also my pixel 2 xl with the same version displays the same behavior.

0.20.7 didn't had this glitch

**Comment by nikhilCad** [comment]
It sometimes happens with me too, but it goes away when I search the same thing again

**Comment by captaincupcakes** [comment]
Mine doesn't...I can look up the same thing several times and still does it

**Comment by Oktayey** [comment]
I'm also experiencing this issue; it happened when I completed a Captcha, then switched from mobile data to WiFi. I'm on a Samsung Note 9 on the latest Android 10 patch.

**Comment by SaraRWarren** [comment]
I had same issue and was able to fix by clearing cache and 're-captcha data' 
![SmartSelect_20210211-170541_NewPipe](https://user-images.githubusercontent.com/29682363/107709919-a33efc00-6c8b-11eb-96d1-987bd534e7e0.jpg)

**Comment by captaincupcakes** [comment]
This did it.. able to search again

**Comment by locustangerine** [comment]
I am running 0.20.11 and have the same issue. I can view videos, but search is inoperative. I've uninstalled and reinstalled, cleared cache, used WiFi and cellular, used VPN and not. No search results for any search term.

**Comment by HTSamurai** [comment]
Works fine for me

**Comment by OutRunKnuckles** [comment]
I've had this issue for a while. After clearing the re-captcha data specifically, the searching was working as expected. I also cleared all the other data in 'history and cache' before this as well. 
I suggest moving the option to clear re-captcha data from the 'content' tab to the 'history and cache' tab, as that is where I expected it to be.

**Comment by guru-of-sound** [comment]
I have this issue but it only happens on videos which I have not previously played with newpipe and have not imported it using the playlist imported. If I wait a few seconds and repeat the search, the videos will populate.

**Comment by locustangerine** [comment]
> I've had this issue for a while. After clearing the re-captcha data specifically, the searching was working as expected. I also cleared all the other data in 'history and cache' before this as well.
> I suggest moving the option to clear re-captcha data from the 'content' tab to the 'history and cache' tab, as that is where I expected it to be.

This is what resolved it for me. I didn't know about the recaptcha setting, as it was not in the "history and cache" area.

**Comment by 12people** [comment]
Same issue, here's the output I got from NewPipe:

> ## Exception
> * __User Action:__ searched
> * __Request:__ gardiner bryant
> * __Content Country:__ US
> * __Content Language:__ en-US
> * __App Language:__ en_US
> * __Service:__ YouTube
> * __Version:__ 0.21.2
> * __OS:__ Linux Android 10 - 29
> <details><summary><b>Crash log </b></summary><p>
> 
> 
> ```
> org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
> at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:280)
> at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:298)
> at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:376)
> at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:234)
> at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)
> at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
> at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:60)
> at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)
> at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:80)
> at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$qyxpuXgomWa-cbONQns-pd7zxm0.call(Unknown Source:8)
> at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
> at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
> at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
> at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
> at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
> at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)
> Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "var\s*ytInitialData\s*=\s*(\{.*?\});"
> at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
> at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)
> at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:54)
> at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:276)
> ... 20 more

Clearing Recaptcha data also solved it for me. It's in the "Content" category, for all those wondering.

Perhaps recaptcha should be cleared automatically whenever NewPipe catches an error like this?

**Comment by 12people** [comment]
@mhmdanas You added a "More info needed" label a while back. Is the info provided above sufficient?

**Comment by 12people** [comment]
@mhmdanas Yup, you're right — that seems to be exactly what my problem is.

@captaincupcakes Could you include your crash log as well so that it's clear whether your issue is the same or not?

**Comment by appcreatorguy** [comment]
@12people ok, clearing captcha worked for me 😀

**Comment by opusforlife2** [comment]
@captaincupcakes Please state if your issue is solved or not to avoid confusing future readers.

**Comment by vehosah** [comment]
> [@12people](https://github.com/12people) ok, clearing captcha worked for me 😀

Yeah if we could find the captcha we could have solved it 😀
