### ISSUE TITLE
Unified Player not maintaing state when orientation is changed in a video which was opened after end of first video and the player is returned to the first video.

### ISSUE THREAD

**Issue by prateekmedia** [TeamNewPipe/NewPipe#5522]
### Checklist

- [x] I am using the latest version - 0.20.8 + 0.20.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Any random video
2. Swipe down and find another video in Recommandation and click on it
3. Do not play the video just rotate your device to the other position i.e. Portrait --> landscape OR landscape --> Portrait

### Actual behaviour

You are returned to the previous video and it is time stamped at start.

### Expected behavior
It should retain the latest video opened info and should not return to the old video.

### Device info

 - Not needed, reproducible on latest version and beta version of newpipe

**Comment by HTSamurai** [comment]
Same problem on Redmi 8

**Comment by mhmdanas** [comment]
@prateekmedia could you please edit the title to be more descriptive?

**Comment by prateekmedia** [comment]
> @prateekmedia could you please edit the title to be more descriptive?

Is that enough descriptive?

**Comment by mhmdanas** [comment]
That's more than enough. Actually, I'd say it's a bit too much, so it would be great if you can make it more concise. But if you can't, that's fine.

**Comment by mhmdanas** [comment]
The issue with your previous title is that it didn't describe the issue in any way. It just said that this is a "serious bug." You should avoid that and at least attempt to describe the problem/feature request itself.

**Comment by MD77MD** [comment]
I've been getting this too

**Comment by Kohoshi12** [comment]
It have been too long since I noticed that. Thanks for making the issue.

**Comment by MD77MD** [comment]
@avently could you check this issue please.

**Comment by ResuUman** [comment]
Possible duplucate
https://github.com/TeamNewPipe/NewPipe/issues/5268#issue-774543973

**Comment by prateekmedia** [comment]
> Possible duplucate
> [#5268 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/5268#issue-774543973)

Yeah, but these issues need some look over them otherwise they would be lost like the one you linked here.
