### ISSUE TITLE
back button causes videos to block

### ISSUE THREAD

**Issue by MrFeelgoood** [TeamNewPipe/NewPipe#5524]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play a video
2. Go to suggested videos and play one of these videos
3. Tap back( or go back) to previous video ( either with android gestures or back button in navigation bar)
4. You will see that previous video doesn't load and doesn't play. To solve this you have to close the player and re open it.

### Actual behaviour
 When you tap back from a video to a previous, previous video is stuck and doesn't play. 

### Expected behavior
 Tapping back from a video to a previous one should make the previous video playable.

### Device info

 - Android version/Custom ROM version: OxygenOs
 - Device model: Oneplus 6t

**Comment by TacoTheDank** [comment]
Hello, does this issue still occur on the latest version?
