### ISSUE TITLE
Some YouTube "Topic" fail to load

### ISSUE THREAD

**Issue by 89z** [TeamNewPipe/NewPipe#5529]
For some reason this video wont load in NewPipe, but it does with YouTube:

- 9 Lazy 9 - Topic
- https://www.youtube.com/watch?v=1PohhankfXc

at first I thought it was because it was a "Topic" video, but other Topic work
fine:

- Phil Mison - Topic
- https://www.youtube.com/watch?v=B6iLj4_SUZs

**Comment by mhmdanas** [comment]
Both of these videos load just fine for me. Can you check if you're using the latest version (0.20.8)? If that's the version you're using or you upgraded and still can reproduce this bug, can you open a new issue that follows the bug template properly? Thanks!
