### ISSUE TITLE
Playlist append broken on newer versions

### ISSUE THREAD

**Issue by 89z** [TeamNewPipe/NewPipe#5530]
Previously, I would hold on a link, then choose "Open With NewPipe App". If I did
this with multiple videos, then one would play after another.

Now with version 0.20.8, if I open a second video, it stops the first video and
starts the second, instead of adding to playlist.

**Comment by 89z** [comment]
It looks like the last version to work correctly is 

https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.20.2

and the first broken version is

https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.20.3

**Comment by 89z** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/4425

**Comment by vkay94** [comment]
@89z Yeah, the behavior change is because of the combined enqueue option PR (but not directly intended at this situation), to answer your comment in that PR. 

There is already a issue which is similar: #4779 . In fact, the option itself is "Background player" and not "Append to background player", it's more like "Start this stream in background player", isn't it?

**Comment by 89z** [comment]
You can only choose if its popup player or background player. You dont have a choice of whether it starts a new playlist or adds to existing. The fact that you dont have that option, combined with the fact that the default has also been changed, makes me frustrated.

I have reverted to the older version until this is resolved. This is not good UX.

**Comment by 89z** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/4779
https://github.com/TeamNewPipe/NewPipe/issues/5530
https://github.com/TeamNewPipe/NewPipe/pull/4562

**Comment by 89z** [comment]
So it seems you can do this with newer versions, but the steps are awful. First,
change your NewPipe default from "Background player" to "Show info". Then, here
is what you have to do **for each video to be added**:

1. Long press link
2. Click Open With NewPipe App
3. Long press Background

Compared to previous:

1. Long press link
2. Click Open With NewPipe App

https://github.com/TeamNewPipe/NewPipe/pull/4562#issuecomment-719766107

I will continue to use the old version until this is resolved.

**Comment by s1awek** [comment]
I started to look for alternalive app because of that bug.

**Comment by 89z** [comment]
@s1awek if you find one that is better let me know, this is really bad decision from the developers.

**Comment by mhmdanas** [comment]
@89z could you open a new issue that follows the template properly? Thanks in advance!

**Comment by 89z** [comment]
Since this is still an issue, here is the last good version:

https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.20.2
