### ISSUE TITLE
Feature Request: Favorite Videos

### ISSUE THREAD

**Issue by 2SI3NX** [TeamNewPipe/NewPipe#554]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.

It would really be awesome if you could maybe swipe left or right from the home screen of NewPipe and could easily access favorite videos that you favorite or <3.  Each video watched should have a little heart to be favorited!!.  And if you have a long list and favorite the same video twice it should tell you, "already in list".

**Comment by mauriciocolli** [comment]
Duplicate #14
