### ISSUE TITLE
Incorrent translation in Download Popup

### ISSUE THREAD

**Issue by GalaxJann** [TeamNewPipe/NewPipe#5546]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open up any Video in NewPipe with a device that has set to "Germany"
2. Click on "Herunterladen" (Or "Download" in english)

### Actual behaviour
In the label of the "Threads" bar (I think it is the `msg_threads` value in your `string.xml` of `values-de`) there is the word "Themen", which is the german translation of "topic" or "subjects". It has a wrong meaning.

### Expected behavior (possible translation)
I would say either use such as "Gleichzeitige Verbindungen" (which means "simultaneous connections" in english) or leave it "Threads" in the german version.

### Screenshots/Screen recordings
![Screenshot_20210209-170310](https://user-images.githubusercontent.com/42975382/107391790-59bea780-6af9-11eb-945b-1bff2ceabc32.png)

### Device info

 - Android version/Custom ROM version: Android 11 (RP1A.201005.004.A1)
 - Device model: Google Pixel 2 XL

**Comment by mhmdanas** [comment]
Thanks for opening an issue! You can fix this yourself. See https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#translation for instructions. Search for the incorrect string and then fix it. If you face any problem feel free to ask me in a comment.

**Comment by TobiGr** [comment]
Fixed. I also added an explanation to the string so the usage of it is clear to all translators
