### ISSUE TITLE
Unable to view videos past a certain amount

### ISSUE THREAD

**Issue by cgray2418** [TeamNewPipe/NewPipe#5548]
Version: 0.20.8
Android 10

I am only about to see a handful of videos from any channels. The videos don't want to load past a certain point. This happens with every channel that I have experienced.

**Comment by mhmdanas** [comment]
Thanks for opening an issue! It seems like you're using a GitHub client instead of the official website, so could you create the issue from the official website and choose the bug report template then fill it out? Feel free to make a comment in case you face any problems.
