### ISSUE TITLE
Channel not loading all videos.

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#5550]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, and found a duplicate (closed) of this issue in the repo. 
- #5548 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Search for any term, and select a video.
2. Pause the video and tap on the name of the channel.
3. When on the channel's main page, scroll to the bottom.
4. Encounter the bug.

### Actual behaviour

It scrolls for 1 "page" of videos, then stops loading the next set/page of videos.

### Expected behavior

It should be loading all the videos from the channel.

### Additional notes

In a possibly (un)related issue, I was recently bombarded with captcha verification requests for 3 or 4 days, that issue resolved itself about 2 days ago, but seems to coincide with this bug appearing.

### Logs

No crash, No log.

**Comment by blind51de** [comment]
This is also occuring in Newpipe Legacy. Whether you access a channel's videos directly or from your subscriptions menu, it will only list up to the end of the first page. It simply DOES NOT LOAD subsequent pages. This has happened for the last few days. Updating and reinstalling the app does not remedy the problem.

You can try to search the playlist for a channel's videos and it will show and load the list in full there, but that's not always reliable.

It looks as though YT changed their API in some way that breaks Newpipe.

Here is an attached screenshot. You should see the indicator that I'm unsuccessfully hitting the bottom of page one to no effect.

![Screenshot_20210210-153039_NewPipe Legacy](https://user-images.githubusercontent.com/71541448/107582138-50dfdb80-6bb6-11eb-9e7d-af8f76329b0a.jpg)

**Comment by johnth3doe** [comment]
Solved in #5564.
With that, I will be closing the issue.
Thank you to the team for the swift fix.

**Comment by Ammako** [comment]
This is basically happening again, except instead of stopping at the end of the first page, it tries to load but then the page goes blank and it says "Content unavailable"
