### ISSUE TITLE
Certain videos cannot be played

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#5552]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to https://www.youtube.com/watch?v=BONSAFTiafY (The Darkness 2)
2. Try to view it
3. Encounter the bug

### Additional notes

I have attempted to play it in the main, pop-up and background; all failed. Other videos from the same channel are still visible and functional during different searches (like The Darkness 1)

### Actual behavior

It just results in a sad face saying "Video not available" and "Content not available" where the channel icon should be. That being said, comments are still loading fine.

### Expected behavior
It should load and play as per usual.

### Logs
No crash, No log.

### Device info

 - Android version/Custom ROM version: Android 4.4

**Comment by mhmdanas** [comment]
I tried to watch it in YouTube's website and it tells me that "this video is unavailable on this device." So I believe this is not actually an issue with NewPipe.

**Comment by PrSunflower** [comment]
Same for me.

![image](https://user-images.githubusercontent.com/59576952/109851834-8f286200-7c6d-11eb-8d60-c68ec7ccced0.png)


<br>

<br>

<br>

It is the first time I read this error message on YouTube though. Don't know what it means.

**Comment by mhmdanas** [comment]
Since this is not an issue with NewPipe, I'll be closing this issue.
