### ISSUE TITLE
Remove Duplicate Entries From Queue 

### ISSUE THREAD

**Issue by Zakkumaru** [TeamNewPipe/NewPipe#5558]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
A button or a passive feature in the options to have all duplicate entries in the playlist removed

#### Is your feature request related to a problem? Please describe it
My problem is related to bug https://github.com/TeamNewPipe/NewPipe/issues/5557 causing several duplicate entries in Playing Queue

#### How will you/everyone benefit from this feature?
1. Trying to create master playlists with hundreds of songs to shuffle, it becomes increasingly more difficult to tell which ones have been added to the list
2. Would be useful for creating a playlist out of multiple playlists without having duplicate entries.  ie: "Nonvocal Liquid Bass" and "Beethoven Remixes" could be combined for whatever study music you're suddenly in the mood for, but if they had overlapping interests (and thus, some of the same songs), you would have to manually remove those entries in order to not have them in the list multiple times.  This could be especially bothersome, again, if you had a lit of songs in each list.

(To be clear, I'm referring to songs of the same ID -- removing entries with similar titles would be a different issue)

**Comment by AlexN1997** [comment]
Have you looked at #5334 ?

**Comment by Zakkumaru** [comment]
> Have you looked at #5334 ?

I didn't notice it, although I had tried searching for something similar.  I would consider this a separate feature since the features apply to preexisting entries, as opposed to checking one at a time at the time of adding them to the list.  Plus, #5334 wouldn't apply retroactively.

**Comment by onelharrison** [comment]
I can try implementing this functionality.

**Comment by ShareASmile** [comment]
Fixed in [v0.25.1 ](https://github.com/TeamNewPipe/NewPipe/issues/9870) by #9707
