### ISSUE TITLE
Bookmarked Playlist Backup?

### ISSUE THREAD

**Issue by theappuser** [TeamNewPipe/NewPipe#5567]
Is there a way in addition to also backup bookmarked playlists as well?

**Comment by theappuser** [comment]
Found it. Thanks

**Comment by theappuser** [comment]
You can close this. I found out how. I was trying to delete this request but I guess I can't.

**Comment by mhmdanas** [comment]
> I was trying to delete this request but I guess I can't do it myself?

You don't have permission to do that. From https://docs.github.com/en/github/managing-your-work-on-github/deleting-an-issue:

> You can only delete issues in a repository owned by your user account. You cannot delete issues in a repository owned by another user account, even if you are a collaborator there.

Issues should not be deleted except in exceptional cases. They should be closed instead.
