### ISSUE TITLE
The Videos on the Channel Are Not Loading.

### ISSUE THREAD

**Issue by houson1817** [TeamNewPipe/NewPipe#5568]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by houson1817** [comment]
No Channel Has Video Released for 4 Days.  Only 1 Line Appears and cannot be scrolled down.

**Comment by mhmdanas** [comment]
Fixed in 0.20.9 (see https://github.com/TeamNewPipe/NewPipe#installation-and-updates on how to upgrade).
