### ISSUE TITLE
More logic renaming of playlists

### ISSUE THREAD

**Issue by Kohoshi12** [TeamNewPipe/NewPipe#5570]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Make the user able to change the name of playlists using the 3 dots on the playlist interface. 

#### Is your feature request related to a problem? Please describe it

Many Android apps use the 3 dots to set basic functions and Newpipe is missing the basic use of 3 dots.

#### Additional context

Use of the 3 dots of playlists: 
![Imagepipe_0](https://user-images.githubusercontent.com/74657968/107841138-be307e00-6dfb-11eb-9f0e-3ee2a14528cd.jpg)

#### How will you/everyone benefit from this feature?

It will make the use similar to many Android apps. Although the ability to change the playlist's name is already there by pressing the playlist box on the playlist area, it would make the use more simple.

**Comment by PulkitGarg67** [comment]
Hello @Kohoshi12 & @mhmdanas, I would like to try and contribute to this.
