### ISSUE TITLE
Video Play issues

### ISSUE THREAD

**Issue by Basarkar123** [TeamNewPipe/NewPipe#5571]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
Unfortunately, we can't really help you if you don't provide us with any information about your issue. Could you please edit your issue to follow the template and then make a comment?
