### ISSUE TITLE
When I try to download the New pipe 20.9 update it says "Forbidden"and it doesn't allow me to proceed with the download.  

### ISSUE THREAD

**Issue by StevenGaaming** [TeamNewPipe/NewPipe#5573]
When I try to download the New pipe 20.9 update it says "Forbidden"and it doesn't allow me to proceed with the download.

**Comment by TiA4f8R** [comment]
Can you reproduce this bug again with 0.21.2? If yes, please tell me in a comment. For now I am closing this issue because the bug that you reported was present when downloading the 0.20.9 version, not the 0.21.2 version.
