### ISSUE TITLE
Latest subscription videos list in chronological order

### ISSUE THREAD

**Issue by maxlinux2000** [TeamNewPipe/NewPipe#5575]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be nice if newpipe could scan the subscribed channels, and show the latest video, from each channel, and compile a list of videos in chronological order in a new tab or something else.

#### Is your feature request related to a problem? Please describe it

what really prevents me from using newpipe every day is that there is no list of the latest videos, based on my subscriptions. Google doesn't do well either, but it's better than nothing. 

#### How will you/everyone benefit from this feature?

In this way we are going to replace the google algorithm with something that really interests us

**Comment by igorcmelo** [comment]
It already existis:
![IMG_20210215_044719_897](https://user-images.githubusercontent.com/59902451/107918643-d19d2f80-6f48-11eb-947b-9bfb96ee8e58.jpg)

**Comment by maxlinux2000** [comment]
It's true and it works.
I therefore propose that the name of the icon be changed to "Latest".
"All" is too generic and you don't understand what this button does.

**Comment by B0pol** [comment]
They are all sorted by "latest", "All" group contains all your subscriptions

**Comment by mhmdanas** [comment]
As the feature requested is already available, I'll be closing this issue.
