### ISSUE TITLE
Login to YouTube and Soundcloud

### ISSUE THREAD

**Issue by mailsantam** [TeamNewPipe/NewPipe#5577]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I will login to YouTube and Soundcloud because of my playlists.

**Comment by Beatz106** [comment]
There are already problems with Google after using an account through YouTube Vanced, for security reasons it is impossible to include this feature in Newpipe.

**Comment by mhmdanas** [comment]
@mailsantam That's not happening. See [this question in our FAQ](https://newpipe.net/FAQ/#bugs-google-login). Also, please don't ignore the template when opening an issue.
