### ISSUE TITLE
Default Resolution

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#558]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Why is the default resolution of the pop-up player (480p) higher than the default resolution of the normal player (360p)? That seems weird to me, because the pop-up player is usually smaller than the normal player.

**Comment by mauriciocolli** [comment]
Yeah, I must've forgotten to change it when I opened the pull request.
