### ISSUE TITLE
Importing any subscribers from any file format not working in CalyxOS

### ISSUE THREAD

**Issue by mattfj10** [TeamNewPipe/NewPipe#5580]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

I recently switched to CalyxOS then installed NewPipe as it's my go-to alternative to the youtube frontend. I decided to download my subscription information from invidious and import it into NewPipe, however no matter which format I choose it refuses to import the data.

### Actual behaviour

1. If the format is from youtube takeout it will error out saying it couldn't import subscriptions.
2. If it's in youtube JSON format from invidious it will say it imported it but change nothing
3. if file is in XML format (aka newpipe format exported from invidious) it will also say it can't import the subscriptions. 

### Expected behavior

When I import the file I expect it to go out and collect all the subscriptions I have in the file and add them to my feed.

### Device info

 - Android version/Custom ROM version: CalyxOS Sargo on Android Version 10
 - Device model: Pixel 3a

**Comment by mhmdanas** [comment]
> If the format is from youtube takeout it will error out saying it couldn't import subscriptions.

That's weird. Could you make sure that you followed the steps properly? For example, did you extract the JSON file and then import it, or did you import the ZIP?
