### ISSUE TITLE
What's up with "Release" 0.20.9??

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#5583]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

The app is old NewPipe with with no new features. It's like 0.20.8 renamed to 0.20.9

### Expected behavior

The release was supposed to have all the new commits

### Screenshots/Screen recordings

![Screenshot_20210214-104620_NewPipe](https://user-images.githubusercontent.com/59365236/107871381-fb574780-6eb1-11eb-9bc9-66234d16e777.jpg)

**Comment by HTSamurai** [comment]
I know right! I have been waiting for a month now and they swiftly changed
it to being 0.20.10.

**Comment by nadiration** [comment]
@HTSamurai i don't really mind renaming it to .10 but why tf is 0.20.8 released as 0.20.9

**Comment by mhmdanas** [comment]
@nadiration see https://github.com/TeamNewPipe/NewPipe/issues/5455#issuecomment-778742434.

**Comment by HTSamurai** [comment]
I know they fixed a bug where a limited amount of videos load in channel
page. That's all 0.20.9 is now

**Comment by nadiration** [comment]
@HTSamurai weird release

**Comment by HTSamurai** [comment]
It was a pretty serious bug.
