### ISSUE TITLE
Share button is missing

### ISSUE THREAD

**Issue by Krawei** [TeamNewPipe/NewPipe#5584]
After searching a video and finally found what I've been looking for I wanted to share my result with a friend. While checking Newpipe's icons i noticed, that the share button wasn't available.

### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
No share button available

### Expected behavior
Share button available, NewPipe allows me to share my finding

### Device info

 - Android 10, Firmware RMX2170_11_A30
 - Device model:Realme 7 Pro

**Comment by mhmdanas** [comment]
In 0.20.10, the share button can be shown by pressing on the arrow besides the video title.
