### ISSUE TITLE
Not downloading when saving to custom location

### ISSUE THREAD

**Issue by Hx2-code** [TeamNewPipe/NewPipe#5593]
When I enable the option to save videos to cusom location, after selecting the location the download does not start.

**Comment by mhmdanas** [comment]
@Hx2-code thanks for opening an issue! Can you see if the APK in #5415 fixes this issue? If not, could you please open a new issue following the bug report template properly?

**Comment by Hx2-code** [comment]
@mhmdanas There is no file. When I click on the link containing apk, it shows 404 error.

**Comment by mhmdanas** [comment]
Can you try downloading from [this link](https://github.com/TeamNewPipe/NewPipe/files/5986375/app.zip) then?

**Comment by Hx2-code** [comment]
@mhmdanas Its not working.

**Comment by TobiGr** [comment]
Uhm. Do you live in a country which blocks certain internet traffics and websites?

**Comment by Hx2-code** [comment]
@TobiGr No and I am from India.

**Comment by Hx2-code** [comment]
@mhmdanas Well its working now when I restarted my device but it does not work when I try to download by share option.
