### ISSUE TITLE
"Hide description" option doesn't work as expected

### ISSUE THREAD

**Issue by lucanomax** [TeamNewPipe/NewPipe#5595]
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. **Disable** description, meta info, comments, suggested videos
2. Open a video
3. Description still shows

---

1. **Enable** description and meta info, disable the rest.
2. Open a video
3. Description shows as expected while comments and suggested videos don't show (everything is fine).

### Actual behaviour
When you disable everything, video description still shows.

### Expected behavior
When you disable everything, the video page should be empty.

### Screenshots/Screen recordings
![screenshot1](https://i.imgur.com/RLixZRk.jpg)
![screenshot2](https://i.imgur.com/hQqtgqh.jpg)
![screenshot3](https://i.imgur.com/Du0IPqQ.jpg)

### Device info

 - AeX 7.3 (Android 10)
 - Xiaomi R5Plus (codename: vince)

**Comment by mhmdanas** [comment]
Curiously, I seem to not be getting the same behavior. If I disable everything, nothing shows, as expected. However, if I enable the description and meta info, I can't see the description, but I can see the comments, which are disabled in the settings.

**Comment by lucanomax** [comment]
> 
> 
> Curiously, I seem to not be getting the same behavior. If I disable everything, nothing shows, as expected. However, if I enable the description and meta info, I can't see the description, but I can see the comments, which are disabled in the settings.

Since I also can no longer replicate that, I'm closing this.
But I must do a consideration: Is that possible that descriprion loading/parsing may depend on the extractor and RSS feeds? Because as you can see by the screenshots the description was loaded anyway, I did a refresh just now to check and it seems to work as expected. All I can think of is that the extractor parsed the descriprion when I took the screenshots but now it don't.

**Comment by mhmdanas** [comment]
I don't think the extractor uses RSS feeds except when fetching the feed using the fast method. Take that with a grain of salt though, as I don't know much about the extractor.
