### ISSUE TITLE
Video keeps pausing and unpausing

### ISSUE THREAD

**Issue by TI84boy** [TeamNewPipe/NewPipe#5601]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung Galaxy S21 5G

**Comment by mhmdanas** [comment]
@TI84boy we can't really help you if you don't provide us with any details. Could you fill the template properly and then make a comment?

**Comment by TI84boy** [comment]
Oh I'm sorry. I typed it within the brackets. I'll just redo it.
