### ISSUE TITLE
Video keeps pausing and unpausing

### ISSUE THREAD

**Issue by TI84boy** [TeamNewPipe/NewPipe#5608]
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to NewPipe
2. Start any video
3. Video will freeze up for a second and then keep playing, but only for a few seconds before it pauses and un-pauses again.
4. Swiping down on the video in portrait view (so that it goes to a minimized view in still in the app, the issue is still there, but now you can see the pause/play icon switching from pause to play while it freezes.
5. Playback has no issues when the video is playing in the background or while the screen is off.

### Actual behaviour

After you open a video, the video will start to play and then immediately start to pause and un-pause. When you go into the minimized version in the app, like if you were to search for another video while still watching one, you will see the pause/play icon going back and forth as it glitches. There is no problem with the playback when the video is playing in the background. Sometimes the issue can be fixed by letting it play in the background for a while and then going back into the app, but other times it will just keep glitching in the app. 

### Expected behavior

 I expect the playback to be smooth whether I am in the app watching the video or in another app with the video playing in the background

### Screenshots/Screen recordings

 https://mail.google.com/mail/u/0?ui=2&ik=caf7a38b5a&attid=0.1&permmsgid=msg-a:r4944840459388579644&th=177a775b8b8dad89&view=att&disp=safe&realattid=177a77310949594f6241

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung Galaxy S21 5G

**Comment by TI84boy** [comment]
Apologies if I  messed this up again. This is my first interaction with Github. Thanks for your help!

**Comment by JCU0** [comment]
It looks like an internet connection problem. Connection is too slow and video is buffering every few seconds. Try official app or site with the same video quality. If you'll see the same problem, then ask your Internet provider or try to reduce quality or download videos and watch them offline.

**Comment by TI84boy** [comment]
Ahh got it. Thanks

**Comment by mhmdanas** [comment]
Since this does not seem like an issue with NewPipe itself, I'll be closing it. If you disagree, feel free to make a comment. Thanks!

**Comment by EpicLemon99** [comment]
I am having the same problem. It doesn't happen in any official app or website.

**Comment by Creeps642** [comment]
Same problem. Not my connection for sure. It happens on random videos until I kill NewPipe

**Comment by enzosanchezewe** [comment]
Yup, same. When I switch to the browser version/app of youtube it just plays normally

**Comment by mhmdanas** [comment]
You all are probably facing https://github.com/TeamNewPipe/NewPipe/issues/6510.
