### ISSUE TITLE
video description not shown for any video

### ISSUE THREAD

**Issue by vladtepesch** [TeamNewPipe/NewPipe#5612]
since the 0.20 update on android tablet no video description is shown for any video I tried.

### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

open any video, click on the 'v' symbol.  

### Actual behaviour
only the "share"-icon and the "open in browser"-icon appears.

### Expected behavior
video description schould be shown

### Screenshots/Screen recordings
example: https://m.youtube.com/watch?v=QKdLP1cP3Dg

Tablet newpipe:
![grafik](https://user-images.githubusercontent.com/1601159/108177087-1076e500-7103-11eb-9cf6-8937a6f0b1c9.png)

Tablet Browser:
![grafik](https://user-images.githubusercontent.com/1601159/108177215-38664880-7103-11eb-950f-aacc6e2ef8d1.png)

### Device info

 - Android version/Custom ROM version: 8.0.0
 - Device model: huawei BAH2-W19

**Comment by mhmdanas** [comment]
You can barely see at the bottom of the comments section two icons, which are buttons to switch between tabs. Swiping to the left on the comments section or pressing the button at the right should switch you to the description. Part of the buttons not being shown is not a good thing though.

**Comment by vladtepesch** [comment]
sorry, i did not recognized this ui change.
okay, if i scroll down a bit, the buttons fully appear.
maybe they should be put on top, as tabs normally are above the content. but i guess, once you know it, it's fine

**Comment by bonswouar** [comment]
This is really unusual UI/UX. 
Thank You!! I've just found this issue (not thanks to github search though, it is really bad)
...I thought descriptions were broken for years!
