### ISSUE TITLE
[Bug] Description timestamps of video leads to youtube website

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5617]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to newpipe
2. Press on a video
3. Check video description
4. Click on the timestamp of the video

### Actual behaviour

Ir will go to the youtube app to the timestamped part of the video.

### Expected behavior

It would continue on the newpipe app and the video will start on the timestamp

### Device info

 - Android version/Custom ROM version: Android version Nougat.
 - Device model: Samsung Galaxy Tab A

**Comment by HTSamurai** [comment]
If you update to v0.20.10, any videos will have a button that looks similar
to the play queue button called "chapters" and it will show all of the
timestamps. Tap one and you get sent to the timestamp in app.

**Comment by HTSamurai** [comment]
That's a good temporary fix

**Comment by Thewisem** [comment]
Ummm well I don't mean inside the video I mean in the description part of the video soooooo yeah we need to fix that as the comments timestamps are almost fixed

**Comment by HTSamurai** [comment]
I think the chapters were to replace the description timestamps.

**Comment by Thewisem** [comment]
Huh really? Then sorry I didn't know

**Comment by TiA4f8R** [comment]
@Thewisem See #5523.

**Comment by Thewisem** [comment]
Hope you could fix the popup mode in description timestamp.
