### ISSUE TITLE
Download a full playlist with the same resolution

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5628]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by mhmdanas** [comment]
This is a duplicate of #5428. Also, please fill out the template when opening issues.

**Comment by SameenAhnaf** [comment]
> This is a duplicate of #5428. Also, please fill out the template when opening issues.

Could you please explain me how this is a duplicate? The question you described is toast download notification which is clearly a different thing 😑.

**Comment by mhmdanas** [comment]
Sorry, I had linked the wrong issue. It's actually #5482.
