### ISSUE TITLE
Crash when using search function

### ISSUE THREAD

**Issue by Columbo2318** [TeamNewPipe/NewPipe#5632]
When trying to search the app will crash. This is happening every time after most recent release. Tested on Oneplus 7t. Reinstalling helped briefly but did not fix permanently. Clearing cache does not fix issue.

**Comment by mhmdanas** [comment]
Thanks for opening an issue! It seems like you're using a third-party GitHub client or something similar instead of the GitHub website. Could you please go to the website and open a new issue that follows the bug template?
