### ISSUE TITLE
Add 'Screenshot' and 'Auto-pause' options to video interface

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5635]
### Checklist

 

*I know "Screenshot" and "Auto-pause" are completely two different options but related to the same need. I often take screenshot by long pressing the home button. Well, that's not possible as the video is played on full screen by default. An option in settings to automatically pause the video while showing the interface will also make sure to avoid missing necessary scene.

One more thing, screenshot should be taken according to the video, not stretched or zoomed. I can zoom in screenshot later in the gallery." * -->

#### How will you/everyone benefit from this feature?

*This feature will enable us taking screenshot in a better way." -->

**Comment by opusforlife2** [comment]
@SameenAhnaf Hey. You're practically an unofficial issue maintainer by now. Would you like to join the team officially as a maintainer? It will allow you to properly close issues and apply labels.

**Comment by opusforlife2** [comment]
@SameenAhnaf If you open the team org's page or the repo's main page, you should see an invite link.

**Comment by opusforlife2** [comment]
@SameenAhnaf You also need to join the IRC channel. #newpipe:libera.chat
