### ISSUE TITLE
NewPipe For iOS

### ISSUE THREAD

**Issue by akczht** [TeamNewPipe/NewPipe#5637]
Hey Guys , is there a plan to release iOS binaries cause i miss newpipe .

**Comment by mhmdanas** [comment]
No, there are no plans to release the app on iOS. One reason is that the app is designed for Android.

**Comment by akczht** [comment]
Ok , No Prob .

**Comment by chadify** [comment]
Check out yattee.

**Comment by Akczht** [comment]
Just checked it out . It's good , But I use Vinegar Tube Cleaner a Safari extension.
