### ISSUE TITLE
Videos not loading 

### ISSUE THREAD

**Issue by kskarthik** [TeamNewPipe/NewPipe#564]
From today morning newpipe is no longer able to load YouTube videos. I tried reinstalling the app but no use. It worked quiet well until yesterday night. 

I am on Lineage OS 14.1

**Comment by edcaron** [comment]
Tried cleaning data?

Settings > apps > NewPipe > Storage > Clear data.

**Comment by kskarthik** [comment]
Yes. Tried. No use.

**Comment by mauriciocolli** [comment]
Do you use some sort of VPN or have some internet issue? Can you access YouTube in another device?
The only possible culprit that I can see here is the network, because that's all that NewPipe do...

Also what error it gives to you? Describe in more details what happens.

**Comment by kskarthik** [comment]
No error. When I search for any video spinner goes  in loop, results arent diaplayed. YouTube mobile site works fine on browser.

**Comment by kskarthik** [comment]
And I am not using any VPN

**Comment by mauriciocolli** [comment]
Which version are you using?

**Comment by kskarthik** [comment]
Works fine after phone reboot. Thanks for the help !
