### ISSUE TITLE
COVID / Censorship warning on content I'm viewing

### ISSUE THREAD

**Issue by maderunner** [TeamNewPipe/NewPipe#5641]
Pick a team! I opted for AOSP with no Google Apps to not see their opinions on my phone screen. If I'm getting the same trash I got with Youtube, I'm taking 10,000 users with me.

**Comment by mhmdanas** [comment]
You can turn it off by going to "Settings > Content > Show meta info."

**Comment by maderunner** [comment]
Not a solution; additional content about the stream creator, stream content, or a search request go along with it.

**Comment by Poolitzer** [comment]
can you give an example video where turning of the meta info does not result in not showing meta info?
