### ISSUE TITLE
Unable to parse package

### ISSUE THREAD

**Issue by johnstonandrew** [TeamNewPipe/NewPipe#5642]
Downloaded the most current version from GitHub and am unable to install. See link below

### Checklist

- [x] I am using the latest version - x.xx.x 
- [ x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Screenshots/Screen recordings

https://youtu.be/z0xkMa5RKdI

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Galaxy S10+

**Comment by xibr** [comment]
Download the APK from [Github Releases](https://github.com/TeamNewPipe/NewPipe/releases) and install it.

See https://github.com/TeamNewPipe/NewPipe#installation-and-updates

**Comment by johnstonandrew** [comment]
Still not working

https://youtu.be/z-SN_8HaMRk

Andrew Johnston
416 Albert Street
Cape Girardeau, MO 63703
(573) 270-7065
johnston.andrew.d@gmail.com

**Comment by TiA4f8R** [comment]
@johnstonandrew Does this bug still happen with 0.20.11 version?

**Comment by johnstonandrew** [comment]
No it's fixed now. Thank you for following up

Andrew Johnston
416 Albert Street
Cape Girardeau, MO 63703
(573) 270-7065
***@***.***

**Comment by TiA4f8R** [comment]
Closing as fixed.
