### ISSUE TITLE
Add "Duplicate playlist" for long press menu on others' playlists

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5646]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Allowing duplication of playlists will immensely help us.This editing the way should be as editing own playlist. "Duplicate" option should be accessed from three dots button and long press menu. Then, it should turn into an own playlist.

A rename popup (same as current rename menu for created playlists) should appear. Name of original playlist should be already included here. "Keep original playlist" checkbox will be useful for accessing the original playlist and creator later.

#### Additional context

Related issues: #5779, #5782, #5783

#### How will you/everyone benefit from this feature?

Sometimes, we save others' playlists but need to add or don't need some certain videos. Often, the title or video arrangement is not up to our needs. Creating a completely new playlist just to organise a few videos is a hassle.

**Comment by ahtaarra** [comment]
I think a good way to go is to add two distinct options in the 'add playlist' option:
- bookmark playlist (will not make it editable by the user here but will be updated when the playlist creator modifies it)
- import playlist (only modifiable by the importing user)

Giving the user to edit a playlist someone else created and still expect the playlist to keep up with the original author's changes would probably complicate things.

But just labeling a playlist as either, letting one convert a playlist from the former type to the latter and maybe using tooltips to clarify their differences would be a great addition!

**Comment by SameenAhnaf** [comment]
> I think a good way to go is to add two distinct options in the 'add playlist' option:
> 
> * bookmark playlist (will not make it editable by the user here but will be updated when the playlist creator modifies it)
> * import playlist (only modifiable by the importing user)
> 
> Giving the user to edit a playlist someone else created and still expect the playlist to keep up with the original author's changes would probably complicate things.
> 
> But just labeling a playlist as either, letting one convert a playlist from the former type to the latter and maybe using tooltips to clarify their differences would be a great addition!



> I think a good way to go is to add two distinct options in the 'add playlist' option:
> 
> * bookmark playlist (will not make it editable by the user here but will be updated when the playlist creator modifies it)
> * import playlist (only modifiable by the importing user)
> 
> Giving the user to edit a playlist someone else created and still expect the playlist to keep up with the original author's changes would probably complicate things.
> 
> But just labeling a playlist as either, letting one convert a playlist from the former type to the latter and maybe using tooltips to clarify their differences would be a great addition!

There's already an option in settings to import and export playlists settings. It might be confusing for users to call the feature "Import playlist".

Instead, a separate section called "Created playlists" for all types of playlists modified and created by the user  "Add to created playlist" option in three dots menu on every bookmarked playlist can be included.

If a user wants to revert back or access, he can do that from "Bookmarked playlists". If a user wants to have self control or edit by his own, he can do that from "Created playlists". If a user doesn't want to get overcrowded with too many similar playlists, he can remove the bookmark from others' playlist as well.

**Comment by SameenAhnaf** [comment]
An option "Keep original playlist while self editing" option can be added if a user wants to keep or delete original playlist and access the creator channel.

Another option "Always name self-edited playlist by the original name" option in the settings can be added too. If enabled, a new rename popup won't appear. If disabled, a new popup will ask for renaming the self-edited playlist.

**Comment by Nurietzsche** [comment]
Could somebody explain me how do I import my YTplaylists? I was looking forward to import all YouTube data from Google Takeout but I didn't find the way. There's little information about NewPipe's settings

**Comment by SameenAhnaf** [comment]
@Nurietzsche You can import only subscriptions from Google Takeout. Unfortunately, importing playlists is still not available. However, you can set playlists public (accessible via both link and your channel) or unlisted (accessible only via link). Then, you can save playlists by sharing your playlists' links.

**Comment by mhmdanas** [comment]
@SameenAhnaf let's keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/3695. Your suggestion has not been made there, so just make a comment.
