### ISSUE TITLE
[feature request][documentation] make 'https://newpipe.net/api/data.json' more known

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#5647]
I know <code>https://newpipe.net/api/data.json</code> is mostly just for the app to fetch the latest apk, but it is such a super useful data for developers and tech-blogs,  
(and the fact it has CORS makes it great for dynamic-content websites).  

Adding even just a one line in either https://github.com/TeamNewPipe/web-api/blob/master/README.md  
or https://github.com/TeamNewPipe/NewPipe/blob/dev/README.md  
will be fine.

also, if possible,  
a link to the changelog would be great,  
either actual text version of it or linking to the blog entry or something like GitHub-API artifact description is also fine,  
oh, and a JSONP version (<code>https://newpipe.net/api/data.json?callback=Self.updateMethod</code>) would be nice too :]'

I've also very documented it (just for me..) in here:  
https://gist.github.com/eladkarako/47c925a19172dfb694a8195b76a94612#file-newpipe-json-api-for-newest-latest-version-with-cors-http-headers-md  
(including some notes and other APIs..).

well, that's all for feature request.  

As for official documentation,  
it might worth for transparency/privacy sake to mention to users that the app will make a connection to <code>newpipe.net</code> and that it will send no private information with it (version checking is done in client-side) since some web-analytics tools (virustotal and such..) shows the app external traffic log, so it might be best to clear up that the requests are not logged and no user unique id is created or collected (I personally don't care so much about it but I'm sure some users do).

**Comment by mhmdanas** [comment]
Thanks for opening an issue! Please open a new issue following the template properly.

**Comment by eladkarako** [comment]
Right <code>(¬_¬)</code>
