### ISSUE TITLE
[Feature Request] Import/Export and group subscriptions

### ISSUE THREAD

**Issue by swidi** [TeamNewPipe/NewPipe#565]
I'd like to suggest to implement a way to import/export them so that it's easier if you have multiple devices. Also a way to group subscriptions to have separate feeds would be cool to see in the future. Thanks!

**Comment by Elaram** [comment]
I really like your app! do you know if the subscription feature will be possible soon?

**Comment by raniesantos** [comment]
Just commenting to say I'm interested in the subscription folders/grouping feature.

Years ago YouTube actually had that feature and they killed it. I've missed it ever since.

**Comment by Stypox** [comment]
@raniesantos see #2309
