### ISSUE TITLE
Read a playlist randomly ?

### ISSUE THREAD

**Issue by kido63** [TeamNewPipe/NewPipe#5652]
Hello,
Is it possible to listen a playlist randomly and not according to the normal order ? 
Thanks

**Comment by sp33dsk8** [comment]
Yes, open playlist then... Follow 
https://github.com/TeamNewPipe/NewPipe/issues/5937#issuecomment-809915385[These Steps](https://github.com/TeamNewPipe/NewPipe/issues/5937#issuecomment-809915385)
