### ISSUE TITLE
Show captions while playing on the background

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5655]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I can't play my songs and captions or lyrics together. I can download and view lyrics on other player. But I can't stream so on Newpipe.

#### How will you/everyone benefit from this feature?

Viewing lyrics will be helpful for non-native speakers of the song language.

**Comment by mhmdanas** [comment]
A background player is supposed to play stuff, well, in the _background_. I think in this case the popup player is more suitable to the task, as it already supports captions.

**Comment by SameenAhnaf** [comment]
> A background player is supposed to play stuff, well, in the _background_. I think in this case the popup player is more suitable to the task, as it already supports captions.

All users might not have the same bandwidth all the time. For example, I can't stream even 360p videos at night as everyone in my family uses Wi-fi. Plus, many music streaming platforms already have it. It would be great to see Newpipe as an allrounder app.

**Comment by mhmdanas** [comment]
What I'm saying is, that the background player should always play exclusively in the _background_. If we want to fix this issue, another method should be used (e.g. add ability to load only audio and captions with the popup player).

**Comment by SameenAhnaf** [comment]
> What I'm saying is, that the background player should always play exclusively in the _background_. If we want to fix this issue, another method should be used (e.g. add ability to load only audio and captions with the popup player).

I should be able to access them while managing the enqeued list. I don't need it anywhere else. It could be placed above the player(In a position like orange box as shown in the screenshot)

![IMG_20210224_114202](https://user-images.githubusercontent.com/79245641/108953590-ab3c6a00-7695-11eb-8d37-c95134022d50.jpg)

**Comment by mhmdanas** [comment]
Then I think you should make that clearer in the issue's title and body. Instead of "show captions while playing on the background," you could instead say "show captions while in queue page."

**Comment by SameenAhnaf** [comment]
> Then I think you should make that clearer in the issue's title and body. Instead of "show captions while playing on the background," you could instead say "show captions while in queue page."

Extremely sorry for your inconvenience. I should have been more alert than before.
