### ISSUE TITLE
Use basic function shortcuts on swiping left and right for bulk selection and playlists

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5657]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Sometimes, we need to choose a lot of videos for bulk selection. Somehow, we need all videos but have chosen to the wrong action for a few videos. The case might be opposite too. We want to select all videos. But the actions will be performed in seperate ways. In such cases, swiping left and right gestures might be helpful. Screenshots are here for better understanding my need. Sorry for my bad editing.

Most people will prefer swiping right for removing videos. However, there are left handed people too. This is why, both swiping left and right should be customisable for different actions.

In my opinion, basic functions include
1. Remove
2. Download
3. Add to popup
4. Add to background
5. Add to main
6. Add to playlist
7. Share

Users may need to do same actions with selected videos. That's why, bulk selection menu should be dismissed only after choosing 'Close' (or 'Cancel') option.

Once bulk selection is activated, an easy video selection gesture should be usable. This gesture could activate bulk selection as well. The reason why I want to keep long press on bulk selection is that users may want a simple common gesture as different views have different gestures.

For list and 1×1 grid view: Scroll through thumbnails
For grid view: Swipe through the videos with two fingers continuously.

The positions of selected videos should be readjustable just like playlists or enqeued lists.
#### Additional context

![108604664-7c926b00-73d9-11eb-8399-1f4acfb66c4f](https://user-images.githubusercontent.com/79245641/108629062-54ae1080-7488-11eb-839f-ac31d55f5aa1.jpg)

More options can be added in three dots menu on the right of top bar.
1. Remove from playlist (exclusive for created playlists)
2. Add to main
3. Checkbox for "Exclude other actioned videos": If checked, swiped (but not removed) videos will be excluded from main action.

![IMG_20210402_103742](https://user-images.githubusercontent.com/79245641/113380982-91cac400-939f-11eb-9abc-4343b3fd1b3f.jpg)

![IMG_20210221_211059](https://user-images.githubusercontent.com/79245641/108629344-97bcb380-7489-11eb-9d1c-f6a69f807fc2.jpg)

![IMG_20210221_172753](https://user-images.githubusercontent.com/79245641/108629348-9f7c5800-7489-11eb-82e7-b80615c03ab3.jpg)

**Comment by SameenAhnaf** [comment]
I would love to see these gestures here as well.
![IMG-20210314-WA0004](https://user-images.githubusercontent.com/79245641/111063778-cb17be80-84da-11eb-9599-5f9d537dd6a0.jpg)

**Comment by chouhanyang** [comment]
@SameenAhnaf I don't have enough experience for NewPipe main UI since I rarely use it. However, bulk selection is fairly complex as it involve many moving parts. There is an online guide that google is publishing called Material DesignI find really helpful: 

https://material.io/design/interaction/selection.html#item-selection

Which can be a good reference for UI designs. Cheers!

P.S. One thing I noticed is that it would be a lot easier for people to read if you could resize the screenshots to around 400px wide.

**Comment by SameenAhnaf** [comment]
@chouhanyang Thanks for your efforts and opinion. Actually, I am not good at editing. 

Long press on thumbnail is a useful gesture that I already suggested in #5832. However, we also need to reconsider where to keep existing long press menu. So, please read that issue for more details.

**Comment by rieje** [comment]
Yes, I find bulk selection essential for quickly deleting videos in playlists. It is a pain to delete them one by one long-pressing each of them.

**Comment by SameenAhnaf** [comment]
Users may need to do same actions with selected videos. That's why, bulk selection menu should be dismissed only after choosing 'Close' (or 'Cancel') option.

**Comment by SameenAhnaf** [comment]
Users may need to do same actions with selected videos. That's why, bulk selection menu should be dismissed only after choosing 'Close' (or 'Cancel') option.

Plus, an easy video selection gesture should be added.
For list and 1×1 grid view: Scroll through thumbnails
For grid view: Swipe through the videos continuously

**Comment by SameenAhnaf** [comment]
Users may need to do same actions with selected videos. That's why, bulk selection menu should be dismissed only after choosing 'Close' (or 'Cancel') option.

Once bulk selection is activated, an easy video selection gesture should be usable. This gesture could activate bulk selection as well. The reason why I want to keep long press on bulk selection is that users may want a simple common gesture as different views have different gestures.

For list and 1×1 grid view: Scroll through thumbnails
For grid view: Swipe through the videos continuously
