### ISSUE TITLE
Snackbars queued when deleting downloads instead of flushing immediately

### ISSUE THREAD

**Issue by ix5** [TeamNewPipe/NewPipe#5660]
### Checklist
- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Download multiple videos/audio files
2. Go to download page
3. Delete multiple videos quickly one after another

### Actual behaviour
Snackbars at the bottom of the UI keep queuing up. You need to wait for all of them to dismiss themselves for files to actually be deleted. If you close NewPipe before all snackbars are dismissed, your files will not be deleted and show up again next time you start NewPipe.

### Expected behavior
Deleting a second, third etc. file should flush the handler queue and immediately delete the previously marked-for-deletion file and dismiss its snackbar.

### Screenshots/Screen recordings

See [this screen recording](https://ix5.org/files/newpipe.mp4)

### Logs
(This bug is not about crashes)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Any, e.g. emulator

---

Now that this newbie template is filled out, let's get down to the actual issue.

Codepath:
https://github.com/TeamNewPipe/NewPipe/blob/1f77e00df41756185fdbe79e6c34e3b14736ce15/app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java#L690
https://github.com/TeamNewPipe/NewPipe/blob/1f77e00df41756185fdbe79e6c34e3b14736ce15/app/src/main/java/us/shandian/giga/ui/common/Deleter.java#L57-L62
https://github.com/TeamNewPipe/NewPipe/blob/1f77e00df41756185fdbe79e6c34e3b14736ce15/app/src/main/java/us/shandian/giga/ui/common/Deleter.java#L71-L78
This causes `next()` to be posted with a delay of 350ms (doc: [Handler.postDelayed](https://developer.android.com/reference/android/os/Handler#postDelayed(java.lang.Runnable,%20long)))

https://github.com/TeamNewPipe/NewPipe/blob/1f77e00df41756185fdbe79e6c34e3b14736ce15/app/src/main/java/us/shandian/giga/ui/common/Deleter.java#L80-L91

A message with `commit()` as runnable is then posted to the handler queue with a timeout of 5 seconds.

https://github.com/TeamNewPipe/NewPipe/blob/1f77e00df41756185fdbe79e6c34e3b14736ce15/app/src/main/java/us/shandian/giga/ui/common/Deleter.java#L93-L115

Only `commit` then really hard-deletes the file.

---

### Possible solution

My idea would be to flush the queue when running `append()` by calling `commit()` directly before inserting into `items` and cancelling all current callbacks via [removeCallbacks](https://developer.android.com/reference/android/os/Handler#removeCallbacks(java.lang.Runnable,%20java.lang.Object))

Tokens in some kind of form might be required?

Hopyfully some Android wizards more familiar with this codebase can chime in. I see @TiA4f8R @Isira-Seneviratne touched this whole GigaGet-imported component last.

**Comment by TiA4f8R** [comment]
I just changed methods to open and share a file, not other things. Also, I am not an Android wizard/developer. So I will not fix this.

**Comment by ix5** [comment]
@kapodamy maybe you have an idea

**Comment by kapodamy** [comment]
@ix5 
yes, when you leave the download activity all pending files are deleted, but, if instead you switch another app the file deletion is "paused"
