### ISSUE TITLE
Add more search filters for videos

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5662]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Although, Newpipe has most basic filters, advanced video search is a little mess. Please add all types of filters soon.

#### Additional context

![IMG_20210219_212821](https://user-images.githubusercontent.com/79245641/108641489-b6429f00-74c9-11eb-8008-f086ab9a1574.jpg)

#### How will you/everyone benefit from this feature?

It will help users search for the most appropriate video in the most accurate way.

**Comment by HTSamurai** [comment]
Oh yes!

**Comment by SameenAhnaf** [comment]
Duplicate of #110
