### ISSUE TITLE
Multiple User agent support

### ISSUE THREAD

**Issue by demonff1** [TeamNewPipe/NewPipe#5667]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Newpipe changes too quickly. That leaves too many ppl bitter when the interface is changed. How bout various user agent to keep everyone happy?

#### Is your feature request related to a problem? Please describe it

New interface might not be well received by the crowd. How bout the tweaks that the devs are planning on be in beta user agent ( a separate experimental one) and users can be asked whether they appreciate the changes. If it is well received, then it will be added as a new user agent.

#### Additional context

Also, Don't jump on changing interfaces too much, there needs to be some regulator. Newpipe is evolving too fast.

#### How will you/everyone benefit from this feature?

 
Users will  transition better to new tweaks. Also ppl need time to be accustomed to the ins and outs. N the time we got familiar with the interface, the users r slammed with another new one right after that. I find that frustrating!

**Comment by SameenAhnaf** [comment]
Why not a video.on new features and UI changes after installing and launching every single new version? A notification may appear to watch the video and know more about features Newpipe may choose either YouTube or their website as it's a single video. This notification should be optional as all might not need the video.

**Comment by AudricV** [comment]
NewPipe is a not web platform, so user agents do not apply to its content. In general, it is not possible for us to maintain multiple UIs for our app.

Closing as won't fix.
