### ISSUE TITLE
Sort, Order and Set limit for videos

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5669]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Video sorting is a really useful feature. Unfortunately, Newpipe doesn't have it anywhere. Sometimes, only certain number of videos uploaded on a certain time are required. In such cases, set limit option is useful.

Following options can be added for video sorting anywhere. Extra options should be available as checkboxes
1. Most popular
2. Upload date: Last hour, today, before or after certain date
3. By video title
4. By channel name (This option might be removed from channel feed)
5. By video length
6. Custom (This option might be for created playlists only. Sometimes, we don't want to change the order of videos but want to filter out only a few videos on the front)
7. Features: Live, 4K, HD, Cc, creative commons, vr180, 360, 3D, HDR, Location
8. Type: Video, Channel, Playlist, Film, Programme

All sorting options should come with ascending and descending order. 

A niche addition might be able to sort uploads, live streams and premiers. Suppose, some people want to see live streams at first, then premiers snd uploads at last. In such cases, "Filter by video type" will be helpful. Users should have "Uploads", "Live Streams" and "Premiers". They should have been rearranged just like tabs in "Content on main page".

Setting limits for videos will be really helpful especially when you only need a certain number of videos. "Set Limit" option should also follow "Sort by" and "Order" options.

Limit options may be like
1. Unlimited: All videos will be loaded.
2. Video number: A certain number of videos will be loaded.
3. Video length: Only videos of certain length will be loaded.
4. Total video length: Videos will be loading until it exceeds a certain time.
5. Keywords: Include or exclude videos with certain keywords in title and description.
6. Channel: This option might show or hide videos from only certain channels. If chosen, all subscriptions will be shown. However z still a search icon for searching channels as users may want to block certain channels. It might not be included in channel feed.

"Sort by", "Order" and "Set Limit" buttons should appear in a row under the "Background, Enqeue all and popup row". The case will remain same for playlist group and subscription group as #5737 is suggested.

Some limit options (based on above options) should have the ability to be added in the "Set Limit" option. For example, I need 10 videos from one channel, 20 from another one. In such cases, user should be able to keep "Video number: 10" and "Video number:20" options in "Set Limit" from settings or a checkbox might appear while setting the box.

On the popup, if a certain limit or number is set and "OK" is pressed, videos will be loaded accordingly. If the "Keep this limit as an permanent option", this option will be kept in "Set Limit" button. If this is unchecked, the limit will be a one time option.

Default settings might be "Sort by: Date added", "Order: Descending", "Set Limit: Unlimited". However, all these settings should be seperately customisable for
1. Channel feed
2. Subscription feed
3. Subscription group feed
4. Playlist feed
5. Playlist group feed
6. What's new feed
7. Search results

#### Additional context

Read this issue to fully understand my suggestion

Add "Background, Enqeue All and Popup" row for playlist category and subscription category #5737
.

**Comment by demonff1** [comment]
That's a good idea. That way the channels that upload too many content won't shadow the channel that doesn't upload much.

**Comment by Angelk90** [comment]
@SameenAhnaf : There are news regarding this, in the app I do not find the similar function.


![image](https://user-images.githubusercontent.com/20476002/128170650-9d107d28-847b-4623-ac41-64b98c481c01.png)

**Comment by SameenAhnaf** [comment]
@Angelk90 @demonff1 Please keep further discussion in #6145.
