### ISSUE TITLE
Add 6 options on "Exit video from full screen" in settings

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5675]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

In current version, Newpipe plays the background on exit. This might not fulfill everyone's needs. Plus, one need to tap thrice to fully exit from a full screen video. Once, to return to video info. Twice, to start playing on background. Thrice, to cancel streaming. Nobody actually needs so many options at once!!!

Here are my suggested options on "Exit video from full screen".
1. Main player: Continue viewing video in main player after exiting full screen. Tap back once again to fully exit.
2. None: Playing full screen video will be turned off just after tapping back once.
3. Play popup: Playing full screen video will switch to popup
4. Play background: Playing full screen video will switch to background
5. YouTube: Recommended for default option. Quite similar to as of now but not the same. Currently, if we minimize the main player within the app, the video starts playing behind title bar. However, this is pretty strange and should be fixed. The video should be playing on thumbnail just like YouTube app.
6. Always ask: A popup with "Main player", "Background", "Popup" and "Exit video" will appear. If no option is chosen before tapping back once again, the video will continue playing on full screen.

#### How will you/everyone benefit from this feature?

Users won't need to toil too much while switching between players as users will be able to choose when to do what. I wanted to keep Newpipe simple as the past days. Play the video and enter full screen. Press back button and exit the video. However, advanced options are still there for fulfilling needs of all users.

**Comment by futureisfoss** [comment]
Hey, this is a nice feature and would go well with  #5459. Why is this issue closed though ? 🤔
