### ISSUE TITLE
Group and sort playlists (just like subscription groups)

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5681]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

There's no way to sort and categorise playlists properly. Only creation time sorting  is available. Following sorting options should be included too.
1. Title (Alphabetical)
2. Total Video number
3. Fully played video number
4. Partially and fully played video number
5. Not played video number
6. Played time
7. Left time
(Suppose, two playlists have two and three hours of videos respectively. Both playlists are played for one hour. In terms of played time, they are the same. But in terms of left time, they are not. That's why, "Played time" & "Left time" should be separate sorting options)
8. Total Length
9. Watched length
10. Left length

All sorting options should have ascending and descending order option.

One more thing, categorising playlists under a name will be awesome. Playlist categories should be swiped from left to right just like subscription category. An option to add "a playlist category" on home page should be available. Seperate sorting option for every single category will be appreciated.

#### Additional context

Be noted that this issue is about playlist sorting, not video sorting. Don't consider it a duplicate of #5669 where I discussed about video sorting.

#### How will you/everyone benefit from this feature?

Managing playlist experience will be a breeze.

**Comment by SameenAhnaf** [comment]
One more thing, while accessing "Bookmarked Playlists" tab, playlists should still stay categorised unlike subscription category. Plus, playlist sorting should appear under playlist category tiles. Just like subscription category tile, playlist categories should have the ability to be edited on a playlist category tile.

Another great thing to have is to hide a category by clicking on the title. In this way, certain playlists can be hidden if they seem to be distracting while working.

Playlist categories should appear in alphabetical order just like subscriptions. However, playlist category tiles might be arranged according to recently created.

Subscriptions are not as complex as playlists. That's why, subscriptions don't require such a huge management. Alphabetical sorting is enough.

**Comment by SameenAhnaf** [comment]
One more thing, while accessing "Bookmarked Playlists" tab, playlists should still stay categorised unlike subscription category. Plus, playlist sorting should appear under playlist category tiles. Just like subscription category tile, playlist categories should have the ability to be edited on a playlist category tile.

Another great thing to have is to hide a category by clicking on the title. In this way, certain playlists can be hidden if they seem to be distracting while working.

There should be a "Feed Update Button" while accessing playlist category tile (just like subscription category tile) to see if new videos added in playlists.

Playlist categories should appear in alphabetical order just like subscriptions. However, playlist category tiles might be arranged according to recently created.

Subscriptions are not as complex as playlists. That's why, subscriptions don't require such a huge management. Alphabetical sorting for channels is enough.

**Comment by SameenAhnaf** [comment]
One more thing, while accessing "Bookmarked Playlists" tab, playlists should still stay categorised unlike subscription category. Plus, playlist sorting should appear under playlist category tiles. Just like subscription group tile, playlist groups should have the ability to be edited on a playlist group tile.

Another great thing to have is to hide a category by clicking on the title. In this way, certain playlists can be hidden if they seem to be distracting while working.

There should be a "Feed Update Button" while accessing playlist category tile (just like subscription group tile) to see if new videos added in playlists.

Playlist groups should appear in alphabetical order just like subscriptions. However, playlist group tiles might be arranged according to recently created.

Subscriptions are not as complex as playlists. That's why, subscriptions don't require such a huge management. Alphabetical sorting for channels is enough.

**Comment by SameenAhnaf** [comment]
One more thing, while accessing "Bookmarked Playlists" tab, playlists should still stay grouped unlike subscription group. Plus, playlist sorting should appear under playlist group tiles. Just like subscription group tile, playlist groups should have the ability to be edited on a playlist group tile.

Another great thing to have is to hide a category by clicking on the title. In this way, certain playlists can be hidden if they seem to be distracting while working.

There should be a "Feed Update Button" while accessing playlist category tile (just like subscription group tile) to see if new videos added in playlists.

Playlist groups should appear in alphabetical order just like subscriptions. However, playlist group tiles might be arranged according to recently created.

Subscriptions are not as complex as playlists. That's why, subscriptions don't require such a huge management. Alphabetical sorting for channels is enough.

**Comment by SameenAhnaf** [comment]
One more thing, while accessing "Bookmarked Playlists" tab, playlists should still stay grouped unlike subscription group. Plus, playlist sorting should appear under playlist group tiles. Just like subscription group tile, playlist groups should have the ability to be edited on a playlist group tile.

Another great thing to have is to hide a category by clicking on the title. In this way, certain playlists can be hidden if they seem to be distracting while working.

There should be a "Feed Update Button" while accessing playlist category tile (just like subscription group tile) to see if new videos added in playlists.

Playlist groups should appear in alphabetical order just like subscriptions. However, playlist group tiles might be arranged according to recently created.

Adding any "Playlist group" as a tab on main page will be really nice.

Subscriptions are not as complex as playlists. That's why, subscriptions don't require such a huge management. Alphabetical sorting for channels is enough.

**Comment by SameenAhnaf** [comment]
One more thing, while accessing "Bookmarked Playlists" tab, playlists should still stay grouped unlike subscription group. Plus, playlist sorting should appear under playlist group tiles. Just like subscription group tile, playlist groups should have the ability to be edited on a playlist group tile.

Unlike channel groups, playlist groups should always be shown for sorting.

Another great thing to have is to hide a category by clicking on the title. In this way, certain playlists can be hidden if they seem to be distracting while working.

There should be a "Feed Update Button" while accessing playlist category tile (just like subscription group tile) to see if new videos added in playlists.

Playlist groups should appear in alphabetical order just like subscriptions. However, playlist group tiles might be arranged according to recently created.

Adding any "Playlist group" as a tab on main page will also be really nice.

Subscriptions are not as complex as playlists. That's why, subscriptions don't require such a huge management. Alphabetical sorting for channels is enough.

**Comment by SameenAhnaf** [comment]
Playlist group tile should be only for others' playlists. This will let us stay up-to-date about newly added videos.

One more thing, while accessing "Bookmarked Playlists" tab, playlists should still stay grouped unlike subscription group. Plus, playlist sorting should appear under playlist group tiles. Just like subscription group tile, playlist groups should have the ability to be edited on a playlist group tile.

Unlike channel groups, playlist groups should always be shown for sorting.

Another great thing to have is to hide a category by clicking on the title. In this way, certain playlists can be hidden if they seem to be distracting while working.

There should be a "Feed Update Button" while accessing playlist category tile (just like subscription group tile) to see if new videos added in playlists.

Playlist groups should appear in alphabetical order just like subscriptions. However, playlist group tiles might be arranged according to recently created.

Adding any "Playlist group" as a tab on main page will also be really nice.

Subscriptions are not as complex as playlists. That's why, subscriptions don't require such a huge management. Alphabetical sorting for channels is enough.

**Comment by RohitSingh107** [comment]
I want this feature to group/folder playlists to categorize them for a long time. I really need this feature, I am a student, coder, I have to create, add lots of playlists but not able to categories or folder them really make me crazy. And I am sure I am not alone, many of long time users of NewPipe want this feature.

I hope you implement it soon :)

**Comment by SameenAhnaf** [comment]
Closing in favor of #1313.
