### ISSUE TITLE
Network bug at the end of fetching subscription feed

### ISSUE THREAD

**Issue by d4f5409d** [TeamNewPipe/NewPipe#5682]
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'What's new'
2. Press on 'Update feed'
3. Wait until the fetching's end

### Actual behaviour

The big part of it gets refreshed,
but when it comes to the end of the subscription feed it says me 'Network error'. I'm sure I don't have network error, because I've tried multiple times, it is still buggy for me. And when I
relaunch the app,  the feed is refreshed, but it says 'Updated 5 days ago'.
### Expected behavior

Refreshing the subscription feed and replacing 'Updated 5 days ago' to Updated 1 min ago.

### Screenshots/Screen recordings

I can't now, I'll try later

### Logs

It wasn't there

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Samsung Galaxy S8

**Comment by XiangRongLin** [comment]
maybe related? #3313

**Comment by d4f5409d** [comment]
No it didn't drop me a log page. And it happens after updating to 0.20.10.

**Comment by d4f5409d** [comment]
### Solved!

Okay, it is now fine. It could have been a YouTube website bug? After 6 days it is finally not dropping me network error. (As I mentioned, this wasn't a connectivity issue because I'm using the same settings and WiFi as 6 days ago.)
