### ISSUE TITLE
All resolutions are not available for some videos

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5684]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

As you can see on the screenshot, some resolutions are not accessible. However, I can stream them on YouTube web. But, I can neither download nor stream some resolutions.

#### Additional context

![IMG_20210223_144202](https://user-images.githubusercontent.com/79245641/108863803-ca96b100-761b-11eb-9c78-a3e35dd9d708.jpg)

However, they are available on YouTube app for the same video
![IMG_20210303_182512](https://user-images.githubusercontent.com/79245641/109805736-03eba400-7c4e-11eb-8c93-682a41ade41d.jpg)

**Comment by SureshCBE** [comment]
Hi,
I am also facing this issue on my phone.

Nokia 4.2.
Android 10
NewPipe v0.20.10

**Comment by TiA4f8R** [comment]
Other qualities that aren't shown are unsupported by NewPipe: it's YouTube OTF stream format, which works only with DASH and not progressive HTTP. See TeamNewPipe/NewPipeExtractor#400 and #4440.

**Comment by opusforlife2** [comment]
Duplicate. This issue is long known. Please search existing issues more thoroughly next time.
