### ISSUE TITLE
Add support for Google Podcasts

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5685]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Could you please add Google Podcasts for streaming and downloading podcasts? It's a really amazing website for audio files and podcasts. Please add support for both streaming and downloading podcasts. Subscription and subscription categories are also necessary.

And, yes, support for importing history and subscription from Google Podcasts through Google Takeout will be great.

**Comment by mhmdanas** [comment]
Service requests go in https://github.com/TeamNewPipe/NewPipeExtractor.

**Comment by SameenAhnaf** [comment]
> Service requests go in https://github.com/TeamNewPipe/NewPipeExtractor.

Could you please explain me why this issue was closed? I am not programmer or something. Just a typical user.

**Comment by mhmdanas** [comment]
Sorry if I wasn't clear enough. What I'm saying is that issues that request adding new services should be opened in https://github.com/TeamNewPipe/NewPipeExtractor, not here.
