### ISSUE TITLE
Add i button to know all suggested (i button, description links and popup suggestions) videos

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5686]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Sometimes, many videos are suggested on i button, popup suggestions and description. But I can't access any video if not suggested in description. Plus, popup video suggestions are a little distracting. Including all videos in one single button will make accessing videos much easier. 

#### How will you/everyone benefit from this feature?

Accessing suggested videos will be a piece of cake

**Comment by mhmdanas** [comment]
Closing in favor of https://github.com/TeamNewPipe/NewPipe/issues/8811, as its description is clearer and more detailed.
