### ISSUE TITLE
Notification bell for New Videos from Channel and Bookmarked Playlist

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5688]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It will be great to get notified for new videos from channel. The bell icon could be placed on the right side of "Subscribe" and "Bookmark playlist" button in cases of channel and playlist seperately. Bell icon should be applied for each channel and playlist seperately as all videos might not be required.

"Count as new videos" option in settings should be added. This setting should have following options
1. When I last opened the app: All videos uploaded after last opening of the app will be notified.
2. When I last opened the channel or playlist: All videos after the last opening of the channel or playlist will appear.
3. When I last opened their videos: Sometimes, we might play their videos somewhere else. For example, from another Playlist, search results etc., not directly from the channel or playlist
4. Videos uploaded or added within last certain time: This option should be customisable for minutes, hours and days. If a video is uploaded within this time, that will be considered new.

More options like "Exclude Watched Videos for Notification" and "Notify for All Videos" in settings will be great too .

"See for New Videos Every" option could act like "Feed Update threshold". But the process should be automatic.No reload button should persist. App will automatically see for new videos when certain time is gone and the phone is online. 

One more thing, many people don't like notifications. In such cases, an optional feature "Show New Videos' Number" in the settings can be added. It should be an independent feature. By enabling it, users will be able to see the number of new videos on the top left corner of the icon of channel or playlist as white text in a red dot. It should also use "Count as New Videos", "Exclude Watched Videos" and "See for New Videos" options  in the same way as mentioned above. However, these options should be seperated for "Show New Videos' Number" feature to avoid conflict.

And, yes, a "Subscribe" and "Bell" button can be added for channels while accessing the search feed. In list view, the buttons should appear on the right corner of the channel title. In grid view, the buttons should appear on bottom side of the channel icon.

**Comment by SameenAhnaf** [comment]
> ### Checklist
> * [x]  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
> * [x]  I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
> * [x]  This issue contains only one feature request. I will open one issue for every feature I want to request.
> 
> #### Describe the feature you want
> It will be great to get notified for new videos from channel. The bell icon could be placed on the right side of "Subscribe" and "Bookmark playlist" button in cases of channel and playlist seperately. Bell icon should be applied for each channel and playlist seperately as all videos might not be required.
> 
> "Count as new videos" option in settings should be added. This setting should have following options
> 
> 1. When I last opened the app: All videos uploaded after last opening of the app will be notified.
> 2. When I last opened the channel or playlist: All videos after the last opening of the channel or playlist will appear.
> 3. When I last opened their videos: Sometimes, we might play their videos somewhere else. For example, from another Playlist, search results etc., not directly from the channel or playlist
> 4. Videos uploaded or added within last certain time: This option should be customisable for minutes, hours and days. If a video is uploaded within this time, that will be considered new.
> 
> More options like "Exclude Watched Videos for Notification" and "Notify for All Videos" in settings will be great too .
> 
> "See for New Videos Every" option could act like "Feed Update threshold". But the process should be automatic.No reload button should persist. App will automatically see for new videos when certain time is gone and the phone is online.
> 
> One more thing, many people don't like notifications. In such cases, an optional feature "Show New Videos' Number" in the settings can be added. It should be an independent feature. By enabling it, users will be able to see the number of new videos on the top left corner of the icon of channel or playlist as white text in a red dot. It should also use "Count as New Videos", "Exclude Watched Videos" and "See for New Videos" options in the same way as mentioned above. However, these options should be seperated for "Show New Videos' Number" feature to avoid conflict.
> 
> And, yes, a "Subscribe" and "Bell" button can be added for channels while accessing the search feed. In list view, the buttons should appear on the right corner of the channel title. In grid view, the buttons should appear on bottom side of the channel icon.
> 
> #### Is your feature request related to a problem? Please describe it
> #### Additional context
> #### How will you/everyone benefit from this feature?

One more thing, if 5 new videos are uploaded from belled channels or playlists,  only one notification like "5 new videos found" should appear. Notification from every single channel or for every single video is unnecessary.

**Comment by MasterEric** [comment]
This would require a service which regularly queries the relevant channels and sends notifications in the event the channels have updated.

Many users who use this app do so for the fact that their phone isn't constantly pinging Google's servers, but adding a notification bell would be explicitly an opt-in feature, so this is not a concern.

**Comment by SameenAhnaf** [comment]
@MasterEric Doesn't this app pinge GitHub website for app update notifications? Just like "Subscribe" button, notification bell could be included and kept optional for users. No feature is or should be forced on users.

**Comment by SameenAhnaf** [comment]
Closing in favor of https://github.com/TeamNewPipe/NewPipe/issues/1086
