### ISSUE TITLE
Video playing frozen in landscape mode

### ISSUE THREAD

**Issue by 7lb** [TeamNewPipe/NewPipe#569]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Playing a video in portrait orientation works, but when switching to landscape the video freezes, although the audio and interface keep working correctly.

Starting the video directly in landscape mode doesn't help, since it stays frozen on the first frame.

Switching back to portrait does not restart the video, it stays frozen.

Checked versions 0.9.6, 0.9.5 and 0.9.4, on a motorola moto g 2015 (osprey), with official lineage os nightly 20170511 (android 7.1.2).

**Comment by mauriciocolli** [comment]
What format and resolution are you trying to play?

And can you provide a `logcat` with this debug version? [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/1012872/app-debug.apk.zip)

**Comment by 7lb** [comment]
I am sorry, after some more testing I think this issue is invalid. I don't believe NewPipe to be bugged, but rather something in the OS itself, since the bug manifests itself with another app too.

I can provide a logcat anyway if it's deemed useful.

**Comment by 7lb** [comment]
I can confirm that flashing lineage os 20170518 fixed the problems.

I'm taking the liberty of closing the issue, I'll be more careful next time

**Comment by damianmonelle** [comment]
How did this solve the matter I slightly same situation ... I can't move the pop out video stuck in right hand corner

**Comment by JuniorJPDJ** [comment]
I've same issue, audio is playing but video is freezing.
Official Lineage 14.1 20180123 on jfltexx
