### ISSUE TITLE
Access timestamps of description on video interface (just like chapters)

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5690]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Accessing video chapters is really useful to watch certain part of a video. However, most uploaders actually put timestamps in the description. Ability to access them like chapters will be actually great.

**Comment by mhmdanas** [comment]
YouTube chapters are actually accessed from the description itself. See https://support.google.com/youtube/answer/9884579?hl=en.

**Comment by SameenAhnaf** [comment]
Are you sure? Why can't I access my chapters then? Look at the screenshot please. I can't find any chapter icon😭.


![IMG_20210224_044525](https://user-images.githubusercontent.com/79245641/108918400-81fee800-765b-11eb-9198-359d08cde4c3.jpg)

**Comment by mhmdanas** [comment]
That's because the first chapter has to always start at 0:00.

**Comment by SameenAhnaf** [comment]
Could you guys do something about it? Like accessing timestamps even without starting at 0:00? Ability to access them from chapter icon will be an awesome addition.

I can neither access timestamps from the description (as you can see on screenshot), but somehow from comments. Not sure if it's a bug or not. But it will be a welcome addition to access all timestamps of description just like chapters instead.

One more thing, accessing timestamps from comments should not open a new popup. Rather, the video should continue playing on video player. Plus, the video player gets hidden while scrolling the description or comments which should not be happening.

**Comment by mhmdanas** [comment]
> Could you guys do something about it? Like accessing timestamps even without starting at 0:00? Ability to access them from chapter icon will be an awesome addition.

No, I meant that YouTube Chapters only work if the first timestamp is 0:00. I think timestamps should work in all cases, so this maybe be a bug, but I'm not sure.

> One more thing, accessing timestamps from comments should not open a new popup. Rather, the video should continue playing on video player.

There's #4241 for that.

> Plus, the video player gets hidden while scrolling the description or comments which should not be happening.

See #4484.

**Comment by SameenAhnaf** [comment]
> > Could you guys do something about it? Like accessing timestamps even without starting at 0:00? Ability to access them from chapter icon will be an awesome addition.
> 
> No, I meant that YouTube Chapters only work if the first timestamp is 0:00. I think timestamps should work in all cases, so this may be a bug, but I'm not sure.
> 
> > One more thing, accessing timestamps from comments should not open a new popup. Rather, the video should continue playing on video player.
> 
> There's #4241 for that.
> 
> > Plus, the video player gets hidden while scrolling the description or comments which should not be happening.
> 
> See #4484.

Won't it be nice to access them all timestamps regardless of being chapters or not? There's no need to exit the video from full screen, scroll down to the description, find the timestamp and click on them. It could be a two step task instead. Click on icon and clock on desired timestamp.

**Comment by SameenAhnaf** [comment]
> > > Could you guys do something about it? Like accessing timestamps even without starting at 0:00? Ability to access them from chapter icon will be an awesome addition.
> > 
> > 
> > No, I meant that YouTube Chapters only work if the first timestamp is 0:00. I think timestamps should work in all cases, so this may be a bug, but I'm not sure.
> > > One more thing, accessing timestamps from comments should not open a new popup. Rather, the video should continue playing on video player.
> > 
> > 
> > There's #4241 for that.
> > > Plus, the video player gets hidden while scrolling the description or comments which should not be happening.
> > 
> > 
> > See #4484.
> 
> Won't it be nice to access them all timestamps regardless of being chapters or not? There's no need to exit the video from full screen, scroll down to the description, find the timestamp and click on them. It could be a two step task instead. Click on icon and clock on desired timestamp.

**Comment by mhmdanas** [comment]
The issue is that timestamps that are not chapters won't have any names, so you'll have nameless timestamps sandwiched between chapters (or vice versa), which I'm not sure is a great thing.

**Comment by mhmdanas** [comment]
Anyway, this is an off-topic discussion here, so if you still want it, you should open a new issue.
