### ISSUE TITLE
[Bug] Can't access timestamps from description but comments

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5695]
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

I can't access my timestamps from description. However, I can do them so from comments. This needs to be fixed.

### Expected behavior

Timestamps from anywhere should be able to open the video at the certain moment. Those timestamps should stay underlined as well.

### Screenshots/Screen recordings

[https://drive.google.com/file/d/1sE2Yu2iXf1ouERz8Vf391CqxHOnepHiG/view?usp=sharing](https://drive.google.com/file/d/1sE2Yu2iXf1ouERz8Vf391CqxHOnepHiG/view?usp=sharing) 

### Device info

 - Android version/Custom ROM version: Android 10 QP1A.190711.020
 - Device model: Xiaomi Redmi Note 8 Pro

**Comment by Thewisem** [comment]
If you want to watch those timestamps. There is an button on upper part called chapters

**Comment by Thewisem** [comment]
Its a 3 line looking button on the upper part of the video you can access the timestamps using that

**Comment by SameenAhnaf** [comment]
> Its a 3 line looking button on the upper part of the video you can access the timestamps using that

Only chapters (timestamps starting from 0:00) can be accessed. Add all types of timestamps.

**Comment by Thewisem** [comment]
What No? I got the chapters in seperate parts. Would you mind sending a pic to show your video. It usually doesn't do that

**Comment by SameenAhnaf** [comment]
> What No? I got the chapters in seperate parts. Would you mind sending a pic to show your video. It usually doesn't do that

https://drive.google.com/file/d/1sE2Yu2iXf1ouERz8Vf391CqxHOnepHiG/view?usp=sharing

**Comment by Thewisem** [comment]
*sigh*
![Imagepipe_5](https://user-images.githubusercontent.com/74511929/109291498-1c1c8700-783a-11eb-994a-f55e5fc330f9.jpg)

**Comment by Thewisem** [comment]
Check this out

**Comment by Thewisem** [comment]
![Screenshot_20210226-135454](https://user-images.githubusercontent.com/74511929/109291647-42dabd80-783a-11eb-9c83-83209c54c073.jpg)
It will come somewhat like this

**Comment by SameenAhnaf** [comment]
> ![Screenshot_20210226-135454](https://user-images.githubusercontent.com/74511929/109291647-42dabd80-783a-11eb-9c83-83209c54c073.jpg)
> It will come somewhat like this

That wasn't my issue at all!!! Why didn't you check my video? My issue was that I can't access timestamps from description. However, I can do so from comments.
https://drive.google.com/file/d/1sE2Yu2iXf1ouERz8Vf391CqxHOnepHiG/view?usp=sharing

**Comment by Thewisem** [comment]
Hmmm I see. It is not being recognized as timestamps. Oh ok

**Comment by TiA4f8R** [comment]
@SameenAhnaf Can you test #5523 with the provided debug APK and see if it works? Thank you in advance.
