### ISSUE TITLE
Sometime crash & Sometime Hang in my device

### ISSUE THREAD

**Issue by yfaisal3** [TeamNewPipe/NewPipe#5698]
when i'm play music already download using repeat & background play sometime crash &  hang please fix it

### Device info

 - Android version/Custom ROM version: V7.0
 - Device model: Evercoss M50A Max

**Comment by TiA4f8R** [comment]
We couldn't help you with the information you provide. Can you please try to capture logs from Android logcat?
I just searched your device on the web and it has only 1GB of RAM. If you add RAM use of your system, you can really use only 500 or 600 MB, which is really low. I don't know if we can do something for these problems. Try to clean other apps and background apps that NewPipe.

Also please follow the template.

**Comment by litetex** [comment]
Is this still a problem?
