### ISSUE TITLE
Add sponsorblock support

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5704]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Newpipe blocks ads perfectly. Unfortunately, intros and sponsor promotions are still irritating fact to handle. Adding this extension will be immensely helpful.

**Comment by nikhilCad** [comment]
Look at #3205 devs don't want it
