### ISSUE TITLE
[Feature Request] Option to choose default audio bitrate?

### ISSUE THREAD

**Issue by tlshum** [TeamNewPipe/NewPipe#571]
Two YouTube audio formats that I'm interested in choosing are formats 249 and 250, which are Opus audio @ ~50kbps and Opus audio @ ~70kbps respectively. As of now, NewPipe doesn't expose any way to let the user choose those two formats. Being able to choose to play audio at those bitrates would be great for those on limited data plans.

**Comment by tlshum** [comment]
I ended up noticing that [formats 249, 250, and 251 are explicitly commented out](https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/services/youtube/YoutubeStreamExtractor.java#L151) because of a lack of support on older devices.  I don't think this feature would need to be implemented if that's the case.

**Comment by o-l-a-v** [comment]
Opus came in Marshmallow. How about enabling Opus for devices running Android >= 6.0.0? Opus at 160kbps (format 251) is easily transparent, it would give the absolute best audio quality.

**Comment by theScrabi** [comment]
We discussed opus at another thread, but yes this is something we want to add.

**Comment by utack** [comment]
@theScrabi hey sorry to hijack this closed issue, where is this opus discussion going on at the moment? Thanks
