### ISSUE TITLE
Regarding the add to queue button

### ISSUE THREAD

**Issue by CEHENNEMDARK** [TeamNewPipe/NewPipe#5711]
Select a video from YouTube, click Share > New Pipe, click the 'play in background' button, and when I add another video, it will delete and open the first video I added from the queue. It would add it directly to the queue in older versions but it is not available right now, just because of this I don't want to update the app. I would appreciate it if you add a button like 'add to queue' directly to that part.

**Comment by SameenAhnaf** [comment]
I'm not sure what you are talking about. There's an Enqeue button instead for your requirement. If you are playing your videos on background, enqeuing will let you add your videos to play on background. If you are playing your videos on popup, enqeuing will let you add your videos to play on popup.

You can also switch to main or popup any time by clicking on media player notification and tapping on three dots.
![IMG_20210226_183311](https://user-images.githubusercontent.com/79245641/109301610-674a9000-7862-11eb-8fc9-d32c32416220.jpg)
![IMG_20210226_183928](https://user-images.githubusercontent.com/79245641/109301620-69acea00-7862-11eb-8cc3-71eb96371958.jpg)

**Comment by CEHENNEMDARK** [comment]
I just want an "add to queue" button in the dropdown here. Hope it was
revealing, thanks for your feedback
You removed the feature in versions after 20.2, I don't want to bother
going into the app and searching for the video.

26 Şub 2021 Cum 15:44 tarihinde SameenAhnaf <notifications@github.com> şunu
yazdı:

**Comment by mhmdanas** [comment]
@CEHENNEMDARK as @SameenAhnaf said, what you want already exists, but its name is "enqueue" instead of "add to queue." I'll be closing this issue, but if I misunderstood, please make a comment.

**Comment by CEHENNEMDARK** [comment]
I just want it to queue up another video after playing the video in the background. What I just did works in the old version:

https://drive.google.com/file/d/10y7dRPl2YoHwfSjJENdWif9apbR1DkGP/view?usp=drivesdk

**Comment by CEHENNEMDARK** [comment]
I know how to do it directly from the application, I don't need to specify especially those places, since you are removing it, just bring an additional button

**Comment by mhmdanas** [comment]
Oh, yeah, sorry, I understand what you want now. See #4779, which requests the same thing.

**Comment by CEHENNEMDARK** [comment]
I'm trying to understand too yeah but it looks like you won't bring it again, it's okay

One last thing, I want to integrate Kurdish language into your application, how can I join the translation group directly?

**Comment by mhmdanas** [comment]
> I'm trying to understand too yeah but it looks like you won't bring it again, it's okay

That's not correct; there are plans to bring it back, although I'm not sure when that will happen.

> One last thing, I want to integrate Kurdish language into your application, how can I join the translation group directly?

You don't need to join any translation group; see https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#translation for instructions. Kurdish seems to be mostly translated, but any corrections or additional translations are still appreciated! If you have any problems feel free to tell me.

**Comment by cehnemdark** [comment]
Now I have a small problem, I reached the instructions from the link you gave, but the Kurdish in it is written in the Sorani alphabet, adapted from the Arabic alphabet. I know Northern Kurdish from the Latin alphabet and I would like to open a new title to write with it. Under the name of 'Northern Kurdish'.  I would be very happy if you make the name of the previous one in Southern Kurdish.  Thank you for your help

"«Spas ji bo alîkariya we»" < An example from Northern Kurdish (thank you).

- https://en.m.wikipedia.org/wiki/Kurmanji
- https://en.m.wikipedia.org/wiki/Sorani

**Comment by cehnemdark** [comment]
> Now I have a small problem, I reached the instructions from the link you gave, but the Kurdish in it is written in the Sorani alphabet, adapted from the Arabic alphabet. I know Northern Kurdish from the Latin alphabet and I would like to open a new title to write with it. Under the name of 'Northern Kurdish'.  I would be very happy if you make the name of the previous one in Southern Kurdish.  Thank you for your help
> 
> "«Spas ji bo alîkariya we»" < An example from Northern Kurdish (thank you).
> 
> - https://en.m.wikipedia.org/wiki/Kurmanji
> - https://en.m.wikipedia.org/wiki/Sorani 

I think I managed to get it done
