### ISSUE TITLE
DOWNLOADING LIST - for later downloading.

### ISSUE THREAD

**Issue by NewNewPipe** [TeamNewPipe/NewPipe#5714]
I suggest adding a DOWNLOAD LIST just like a playlist.

On a given channel, on a given video in the menu / options / function to select - add to download list for later downloading. In addition, the name of the channel should be automatically added to the video name at the end after the space or "-" "_" etc.

Sorry but I do not know how to fill out the template correctly. The only thing that appears is a post, where you can enter the content.

**Comment by SameenAhnaf** [comment]
> I suggest adding a DOWNLOAD LIST just like a playlist.
> 
> On a given channel, on a given video in the menu / options / function to select - add to download list for later downloading. In addition, the name of the channel should be automatically added to the video name at the end after the space or "-" "_" etc.
> 
> Sorry but I do not know how to fill out the template correctly. The only thing that appears is a post, where you can enter the content.

I think it's wiser to create a "Download Later" playlist by yourself. Only "Download a full playlist" feature is required.

**Comment by NewNewPipe** [comment]
Good idea. Provided the downloaded files have channel names automatically added, and additionally the NewPipe script could add the date the video was published on YouTube.

**Comment by opusforlife2** [comment]
Then I'm closing this issue as solved. You can open a new issue for further requests, although I think download metadata is already requested in another issue.
