### ISSUE TITLE
Disabling "Show description" disables comments

### ISSUE THREAD

**Issue by krushia** [TeamNewPipe/NewPipe#5719]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Turn off Show description in Content settings page.

### Actual behaviour

Description remains under each video, but comment tab is hidden.

### Expected behavior

Description should be hidden and comments unchanged.

### Device info

 - Android version/Custom ROM version: 9
 - Device model: SM-P200

**Comment by d4f5409d** [comment]
For me comments are currently not loading at all. It loaded on a few vids in the past days, but now it is gone and I can't see the comments.

**Comment by r2308145** [comment]
> 
> 
> For me comments are currently not loading at all. It loaded on a few vids in the past days, but now it is gone and I can't see the comments.

it's the same for me, can't see comments at all

**Comment by peat80** [comment]
I can reproduce this on androidtv. If you disable comments it hides description instead. If you disable everything description stays also and the rest is hidden. Similar things happen on handy too. If you hide some content it does not always really hide instantly.

However, i've experienced enced that if you properly close the app after changing content settings and then reopen it everything works as expected as you setup it. Works on androidtv and on normal android also.

So the solution would probably to somehow to either internally force an ui update after changing content setting or show a similiar toast like on a language change that you have to exit the app to properly display the choosen content that was setup by the user. 🤔 🤷🏻‍♂️ 😀

**Comment by TobiGr** [comment]
I cannot reproduce this in the latest version. Does the bug still occur on your devices?

**Comment by peat80** [comment]
Tried again on phone and tv with nightly 60 and hiding comments and co. works fine on both. 😎👌
