### ISSUE TITLE
Replay not working

### ISSUE THREAD

**Issue by Multipanda** [TeamNewPipe/NewPipe#5722]
### Checklist
- [x] I am using the latest version - v0.20.10
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.
### Steps to reproduce the bug
Any youtube video ending and me trying to push replay
### Actual behaviour
It doesn't replay and video doesn't start either if I jump into a point on the video. I can only make it play again if I change the resolution, thereby forcing it to reload the stream.

(Videos also sometimes freeze where I have to also change resolution for the stream to continue, so I think underlying cause might be the same, or at least related.)

### Expected behavior
For video to start replaying when pushing replay button

### Device info

 - Android version/Custom ROM version: Android 7.1.2 (LineageOS 14.1)
 - Device model: Samsung Galaxy Tab S (T800)

**Comment by tsiflimagas** [comment]
This has been fixed. Could you confirm?
