### ISSUE TITLE
History tab on a main screen

### ISSUE THREAD

**Issue by JCU0** [TeamNewPipe/NewPipe#5731]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
History is currently hidden under hamburger menu. 

I want 4 global tabs:
- Subscriptions
- Playlists
- **History** (new tab)
- Hot (useless trash for me)

#### Is your feature request related to a problem? Please describe it
Some streams and educational videos are quite long, so I want an easy way to return to a video I watched earlier.

#### Additional context
History is usually related to privacy, so I think it should be an option to show/hide global History tab.

#### How will you/everyone benefit from this feature?
Less clicks before you can return to a video you watched earlier.

**Comment by defini-tiv** [comment]
You can already change the tabs in the settings

**Comment by mhmdanas** [comment]
It's as @defini-tiv says. Go to "Settings > Content > Content of main page" and then click on the plus button, then choose history from the dialog.

**Comment by JCU0** [comment]
Didn't know it was already implemented. Thank you.
