### ISSUE TITLE
Implement sponsorblock in newpipe

### ISSUE THREAD

**Issue by Hx2-code** [TeamNewPipe/NewPipe#5732]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Implement  [Sponsorblock](https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone?hl=en) in newpipe. 

#### How will you/everyone benefit from this feature?

It will save a lot of time of everyone whtching videos.

**Comment by XiangRongLin** [comment]
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

**Comment by Hx2-code** [comment]
Sorry actually nothing showed up when I searched for duplicates.

But can you say why the feature is not implemented.

**Comment by XiangRongLin** [comment]
> 
> 
> Sorry actually nothing showed up when I searched for duplicates.

In this case you'll have to search in closed issues, can't know it so yeah. https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed+sponsorblock

> 
> But can you say why the feature is not implemented.

As for the reason you'll have to sift through here. But it boils down to, that the team does not want the feature:https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed+sponsorblock

**Comment by Hx2-code** [comment]
Thanks for the link.
