### ISSUE TITLE
Feature request - tagging

### ISSUE THREAD

**Issue by mani445** [TeamNewPipe/NewPipe#5736]
There is lot of song downloading software available for windows,Mac's 

But only some few rare for android. 

New pipe is nice one.Youtube music have collection of music those music song downloaded but it's tags are not completely. I think the below library/repo can ⬇️ 

https://github.com/sigma67/ytmusicapi 

This is a feature request.If new pipe add this feature, that's good. 
Sir What you think?

**Comment by mangoepic** [comment]
Related Issues:
#4341 Add metadata while downloading files
#5445 mp3/m4a cover pic feature request

**Comment by Stypox** [comment]
Youtube music support is already available as a search filter. For the other things, look at the related issues.
