### ISSUE TITLE
Add "Enqeue Method" drop-down menu, "Popup" and "Background" button for subscription group feed, playlist group feed and What's New feed

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5737]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Currently, there are options for "Background", "Play All" and "Popup" while accessing channel and playlist feed. Unfortunately, they are not available for subscription group and playlist group feed.

"Enqeue Method" drop-down menu, "Popup" and "Background" options should be added for subscription category feed, what's new feed and playlist category feed. I have already discussed why "Play All" button should be replaced by "Enqeue Method" drop-down menu #5741 and playlist group in #5681.

And, yes, all these options should appear under "Feed Update Button".

#### Additional context

Please read following issues to fully understand my suggestion
Replace "Play All" button with "Enqeue Method" drop-down menu #5741 
Group playlists #5681

**Comment by SameenAhnaf** [comment]
And, yes, all these options should appear under "Feed Update Button".

**Comment by SameenAhnaf** [comment]
And, yes, all these options should appear under "Feed Update Button".

**Comment by chrstfer** [comment]
I like this, but we need better queue support in general. Viewing/Modifying the queue is impossible right now I think (at least, i use newpipe every day and dont know how to do it). 

Maybe this should be a subtask in a larger "rework queue" issue/project. I would include your other related issues too, @SameenAhnaf.  I'd do it if i weren't just browsing on my phone right now rather than at my computer for a while; i might later if no one else does.

**Comment by SameenAhnaf** [comment]
@chrstfer Thank you so much. There's no rush in doing it. Take your time.

**Comment by SameenAhnaf** [comment]
Closing in favor of https://github.com/TeamNewPipe/NewPipe/issues/7047#issuecomment-913089778. Section F of that comment suggests to play new videos of each group feed on last player.

**Comment by beatnickgr** [comment]
I'd love to see this happening! Thanks :)

**Comment by grappas** [comment]
![obraz](https://github.com/TeamNewPipe/NewPipe/assets/1036957/8a109f54-7cec-47e1-a821-a16ab1881f01)
Grayjay has this godsend feature.
