### ISSUE TITLE
10 More options on long press on playlist

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5738]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Currently, only "Remove" option is available for long press on playlist which is just boring. I am not in favour of quick shortcuts (mentioned in #5661) for playlists as that will make the UI too overcrowded. Rather, following options should be implemented as well.

1. Bookmark: Only for others' playlists
2. Allow self edit: Know more in #5646 
3. Categorise: Know more in #5681
4. Start playing: All videos will start playing in full screen
5. Start playing in the background
6. Start playing in popup
7. Download: Download the full playlist (Downloading playlist and enqeued list should have options in #5657)
8. Merge: A new popup should appear which will have upper and lower menu. The lower menu should show bookmarked and created playlists. The upper menu should show the playlists to be merged. Playlists should appear from lower menu to upper menu by clicking on them once. The playlists in upper menu should be rearrangable and removable (just videos on enqeued list). Clicking on "OK" will finish merging and a new popup ask for saving previous playlists. A checkbox for "Don't show this again" can be added to always save or delete playlists. Then, a new popup will appear for asking new playlists' name.
9. Enqeue: The whole playlist will be enqeued
10. Set a playlist thumbnail: All video titles and thumbnails will appear. Selecting a video title should set that video thumbnail as the default playlist thumbnail.

Split playlist option is not required as the playlist has to be open ultimately. Bulk selection gestures (mentioned in #5657) should be added as soon as possible.

#### Additional context

Please read following issues too.
Quick shortcuts #5661
Allow self edit playlists #5646 
Categorise and sort playlists #5681
Bulk selection gestures #5657

**Comment by XiangRongLin** [comment]
> This issue contains only one feature request. I will open one issue for every feature I want to request.
