### ISSUE TITLE
"Content unavailable" when scrolling down a channel or playlist

### ISSUE THREAD

**Issue by windows-server-2003** [TeamNewPipe/NewPipe#5739]
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any channel with videos of more than one page.
2. Scroll down until it loads the second page

### Actual behaviour
All the videos disappear, and it shows "Content unavailable"

### Expected behavior
The videos in the second page will be loaded

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: TCL Plex

**Comment by BenyBalazs** [comment]
Same thing happens with long playlists as well.

**Comment by PrSunflower** [comment]
Exactly, I am having the same issue.

Scrolling down playlists longer than 100 videos or channel pages clears the page and shows a blank "Content unavailable" message.

![Screenshot_20210303-220506](https://user-images.githubusercontent.com/59576952/109851090-b3377380-7c6c-11eb-9f3a-ea3de27d78b4.png)

**Comment by TiA4f8R** [comment]
Extractor issue: TeamNewPipe/NewPipeExtractor#566

**Comment by BrunoDSL** [comment]
I have the same issue too.

**Comment by TiA4f8R** [comment]
Does my debug APK works for you, for channels and long playlists?
https://github.com/TiA4f8R/NewPipe/suites/2178388837/artifacts/44814609

**Comment by edenheijer** [comment]
> Does my debug APK works for you, for channels and long playlists?
> https://github.com/TiA4f8R/NewPipe/suites/2178388837/artifacts/44814609

Can confirm that long playlist will load with this fork
![Screenshot_2021-03-04-21-23-09-576_org schabi newpipe debug fixytchannelsplaylists](https://user-images.githubusercontent.com/3668157/110025581-d7a85400-7d2f-11eb-9f51-0a4c4bd97669.jpg)

**Comment by windows-server-2003** [comment]
Confirmed working too.

**Comment by windows-server-2003** [comment]
I just noticed the release and it's indeed fixed !
Thank you for such a quick fix.
