### ISSUE TITLE
Unused resource strings

### ISSUE THREAD

**Issue by antonv6** [TeamNewPipe/NewPipe#574]
I've noticed that title_activity_channel string (saying "ChannelActivity" in English currently) is not used anywhere in the UI (as far as my grep skills allow me to know). It's been sitting there confusing translators for some time (9a0f61e60bf325811fe8529880acaf97386f08bb) and there's now a variety of different kinds of translations people came up with, otherwise I wouldn't raise this issue. So can we remove this string?

Or maybe there's a bigger question. I'm not an android developer, but is there a way to see if a particular string is unused currently? Can it be automated in a way that makes sense and put into e.g. CI?

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by mauriciocolli** [comment]
Yes there's a way, running a `lint` in the code should bring up unused resources.

And I've just ran and there's 40+ unused strings, some of them are not used yet, but will be in the future, so I'll see if I can do a clean up (if I delete something that'll be used, there's the history in git anyway).
