### ISSUE TITLE
Add all 6 YouTube tabs in channel feed

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5747]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Newpipe has come a long way providing an identical YouTube experience without having an account. However, it still has a long way to go. Adding following tabs will be be appreciated.

All tabs in a swipable row (from left to right) on the top of the channel page like YouTube App. However, profile information (profile picture, story ring around the profile picture, Subscribe button, Bell button in #5688) should be kept steady on the above. That will let users subscribe the channel easily even if they scroll too down the channel.

Home: It will include tagged video (I dunno how to address the huge thumbnail video. Let me know if I am wrong), popular playlists and most popular videos.

Videos: Playing and sorting option might be exclusive for this tab of the channel page as this is where all videos can be accessed. Playing options' row (mentioned in #5741) should be the first row and sorting options' row (mentioned in #5669) should be the second row. Videos will be shown under these rows.
These rows should not be kept steady as that will keep too much of the screen steady. Plus, if a user is supposed to sort videos, he will do so earlier, not in the middle of scrolling videos.

Playlists: All necessary playlists will be shown (mentioned in #5203 ).

Community: Add this tab to access stories and updates.

Channels: Subscriptions and Featured Channels will appear (mentioned in #5644)

About: Show description, joining date and important links of the channel (mentioned in #5746).

#### Is your feature request related to a problem? Please describe it

Related issues: #5644, #5746, #5203
.
#### How will you/everyone benefit from this feature?

Users will find Newpipe experience identical to YouTube app and never miss a single update from the channel.

**Comment by mhmdanas** [comment]
> But those options are necessary to complete the experience.

I don't think a "complete" experience is a reason to add a feature. If no one wants a feature, it should not be added. I'm not saying I'm against add the home and community tab, but if the only reason to add them is a "complete experience," then I don't think they should be added.

> I know, something is better than nothing. That's why, some Newpipe developers want to see a single feature in a single issue. But there's no offense in viewing all requirements at a glance, is there?

I'm not sure I understand what you're trying to say, but there are multiple reasons to not want issues that request multiple features. For example, the comments are likely to be a mix of people talking about different parts of the issue. In this case though, the issue references other issues for most of its requests, so I'm not sure if this is against the contributing guidelines or not.

**Comment by SameenAhnaf** [comment]
> > But those options are necessary to complete the experience.
> 
> I don't think a "complete" experience is a reason to add a feature. If no one wants a feature, it should not be added. I'm not saying I'm against add the home and community tab, but if the only reason to add them is a "complete experience," then I don't think they should be added.
> 
Complete experience is mainly required to make this app identical to YouTube app. This will let new users find Newpipe easier to use with extra functionalities and privacy. Plus, Community tab is actually required to access stories (mentioned in #5476) although request for tab is not directly stated. Also, Home and Community tabs have some unique information which some users would like to know.
> > I know, something is better than nothing. That's why, some Newpipe developers want to see a single feature in a single issue. But there's no offense in viewing all requirements at a glance, is there?
> 
> I'm not sure I understand what you're trying to say, but there are multiple reasons to not want issues that request multiple features. For example, the comments are likely to be a mix of people talking about different parts of the issue. In this case though, the issue references other issues for most of its requests, so I'm not sure if this is against the contributing guidelines or not.

Some developers like @polymorphicshade actually prefer viewing all requirements at a glance. That's one of the main reasons why I opened this issue.I know it may hinder developer's opinion regarding a specific topic or make the whole issue a mess. But there are some good reasons why I created an "All in one" issue.
1. Make the app identical to YouTube
2. Address where to keep "Background, Play All, Popup row" and sorting options.
3. How to organise channel tabs if added (We have already planned to include four tabs. Let's include all 6 tabs and let the channel page just be alike YouTube app.)
4. Access stories from Community tab.

If any developer wants to work on a specific issue, four separate issues are there. But requirements of all developers should be kept in mind.

**Comment by SameenAhnaf** [comment]
Following functions should still be available while loading the channel.
1. Subscribe/Unsubscribe
2. Group/Ungroup
3. Choose among any feed

**Comment by SameenAhnaf** [comment]
Closing in favor of #2414.
