### ISSUE TITLE
Comments don't work since v.0.20.10

### ISSUE THREAD

**Issue by r2308145** [TeamNewPipe/NewPipe#5749]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

Since the newest version I can't see the comments on any video, no matter the settings, they just dont show up.. might be related to bug #5719 maybe?

### Device info

 - Android version/Custom ROM version: 7.0 Nougat

**Comment by DanieLoche** [comment]
Duplicate. Already raised in issue #5585 ...
