### ISSUE TITLE
[Question] Why does Newpipe get buggy even before an update is released

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5752]
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Newpipe is an amazing app in a word. Unfortunately, it is not free from bugs. Especially, not updating the app turns everything into a mess. Such problems are actually rare in most other YouTube downloader apps. Although, it's not a major problem. But it should be fixed to make users' update schedule at least a little flexible.

But the key problem is that app often starts to get buggy much before an update is released. For example, #5739. The channel feed shows "Content Unavailable" just after scrolling a little down.

 
### Actual behaviour

Users most often face bugs even though no update is released.

### Expected behavior

Users should not encounter any kind of bug until an update is released.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
Unfortunately, this is not something in our control. Whenever YouTube changes anything, there is a possibility that it will break NewPipe. That's just an inherent limitation of scraping data from web pages like NewPipe does.

**Comment by davidasunmo** [comment]
Well would you rather the bugs happen after the update, requiring another update?

**Comment by SameenAhnaf** [comment]
@davidasunmo That's not how it works. @mhmdanas has already mentioned an answer.

>Unfortunately, this is not something in our control. Whenever YouTube changes anything, there is a possibility that it will break NewPipe. That's just an inherent limitation of scraping data from web pages like NewPipe does.

**Comment by SameenAhnaf** [comment]
@mhmdanas I don't know how web scraping works. But will most of the bugs get solved if the "Scrap after loading full web page" is added? I know some features like "Unload thumbnails" will be missing. But regular users like us find it frustrating to encounter bugs for 3 to 4 days every month. Should I open a new issue regarding this and where? Here or in extractor forum?

**Comment by mhmdanas** [comment]
@SameenAhnaf I'll try to explain. Imagine that NewPipe used some kind of API from YouTube. YouTube would have an obligation to not break the API, at least between versions. However, NewPipe loads YouTube's web page and extracts data from it (which is what web scraping is), but YouTube has no obligation to keep the page constant. Thus, even small changes in e.g. internal names that users of the YouTube web page won't notice might break NewPipe.

> But will most of the bugs get solved if the "Scrap after loading full web page" is added?

No, since that is not the cause of the bugs.

**Comment by mhmdanas** [comment]
I assume that by "loading full web page" you mean loading every single image and resource before scraping. If that's correct, then again, it won't help reduce the bugs and will only waste resources.

**Comment by SameenAhnaf** [comment]
@mhmdanas Thank you so much for the explanation.

**Comment by davidasunmo** [comment]
> @davidasunmo That's not how it works. @mhmdanas has already mentioned an answer.
> 
> > Unfortunately, this is not something in our control. Whenever YouTube changes anything, there is a possibility that it will break NewPipe. That's just an inherent limitation of scraping data from web pages like NewPipe does.

@SameenAhnaf I was being sarcastic x)

**Comment by SameenAhnaf** [comment]
@davidadriao Me too, lol 🤣🤣🤣

![IMG_20210309_070340](https://user-images.githubusercontent.com/79245641/110402497-b59f3080-80a5-11eb-9032-29aba15f5191.jpg)
