### ISSUE TITLE
Subscriptions json file fails to be imported

### ISSUE THREAD

**Issue by s6o1lu** [TeamNewPipe/NewPipe#5753]
### Checklist
- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Tap the 'Hamburger Menu'.
2. Tap on 'Subscriptions'.
3. Under 'Import from', tap 'Previous export'.
4. Select the 'subscriptions.json' file previously downloaded from your youtube account.
5. In the 'Do you want to continue?' pop-up, tap 'OK'.
6. 'Could not import subscriptions.' message appears.  

### Actual behaviour
The subscriptions fail to load.

### Expected behavior
Subscriptions get loaded.

### Device info

 - Android version: 9PKQ1.180917.001/Custom ROM version: MIUI Global 12.0.4|Stable 12.0.4.0 (PDMMIXM)
 - Device model: Redmi 6 Pro

**Comment by mhmdanas** [comment]
Thanks for opening an issue! You're choosing the incorrect option. "Previous export" is for exports from NewPipe. To import YouTube subscriptions, press on "YouTube," which is directly under "Previous export." If you face any issue, feel free to write a comment.

**Comment by s6o1lu** [comment]
Thanks for the response. I tried that too. Followed the procedure mentioned for importing from youtube. Downloaded the zip file. Unzipped it. Selected the 'subscription.json file, and then clicked 'Import File'. Clicked 'OK' on the 'Do you want to continue?' popup.  A message appeared stating 'Imported', but no subscriptions were loaded. Note that, I already had subscriptions loaded in the app, but since I had added new subscriptions on YouTube, I wanted the list on NewPipe to be refreshed. When importing from youtube did not refresh the list, I reinstalled NewPipe and tried from scratch, but was still unsuccessful.
