### ISSUE TITLE
Problem loading channels old videos

### ISSUE THREAD

**Issue by Igivegoodadvice** [TeamNewPipe/NewPipe#5755]
When I am focused on a channel  @and I start scrolling back to see their old videos it reaches a certain point but it then stops and says that the content is unavaliable. If you guys are looking for things to add, extending this would be a great idea.
Thanks in advance.

**Comment by gigiboeru** [comment]
This a new bug, it started a few hours ago, I'm getting the "content is unavailable" soon after I start scrolling. YouTube must have done something.

**Comment by nottheend** [comment]
Same here, first videos of channel loads fine

**Comment by jithinjames916** [comment]
content is unavailable in subscription channels in subscription tab... Please do the need full

**Comment by mhmdanas** [comment]
Duplicate of #5739.
