### ISSUE TITLE
NewPipe won't use the VPN

### ISSUE THREAD

**Issue by gasull** [TeamNewPipe/NewPipe#5758]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Set up a VPN on your phone.
2. Go to Settings -> Apps and notifications -> NewPipe -> Data usage -> disable WiFi data and Cellular data, and enable VPN data
3. Play any video on NewPipe

You'll get "Network error" and a red "RETRY" button.

(Other apps including the browser work perfectly when restricted to the VPN in the same way).

### Actual behaviour

"Network error" and a red "RETRY" button.

### Expected behavior

The video should be played.

### Device info

 - Android version/Custom ROM version: Android 9 / lineage_X00TD-userdebug 9 PQ3A.
 - Device model: Asus X00TD

**Comment by litetex** [comment]
Thank you for the issue.

Is this still a problem?

Assuming that you are using YT: Does it work in the browser when using a VPN?

**Comment by LukasBauza** [comment]
I am having this same issue, turning off the VPN allows it to work again.
