### ISSUE TITLE
[feature request] watch cropped area only / dynamic zoom

### ISSUE THREAD

**Issue by okias** [TeamNewPipe/NewPipe#576]
Many YT videos has thanks to uploading protection "video in video". Could be possible to make NewPipe allow cropping view to area where is real video?

**Comment by Wiredframe** [comment]
You can use MX Player and set "use external player" in the NewPipe options. In MX Player you can enable pinch zooming and automatically zoom to fit the screen. It's perfect for non 16:9 screens.

**Comment by Stypox** [comment]
In both popup and main player you can choose how the video should be displayed: "Fit", "Fill" and "Zoom". So I think that suits your needs. If it's not, feel free to reopen the issue :-)
