### ISSUE TITLE
Channel content not available when scrolling.

### ISSUE THREAD

**Issue by NewNewPipe** [TeamNewPipe/NewPipe#5761]
### Checklist

- [x] I am using the latest version - 0.10.20 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Logs

No logs

### Device info

 - Android version/Custom ROM version: 10
 - Device model:

Bug report:

On a YT channel scrolling through the list of videos after a few pages of scrolling the message "content unavailable" even though there are many more videos on the channel. Checked on several channels. Until recently it was OK.

**Comment by mhmdanas** [comment]
Thanks for opening an issue! I believe this is a duplicate of #5739.

**Comment by NewNewPipe** [comment]
Sorry.

Problem described 2 days agoSorry


https://github.com/TeamNewPipe/NewPipe/issues/5739

Closed.
