### ISSUE TITLE
Error when trying to play youtube video

### ISSUE THREAD

**Issue by broggini** [TeamNewPipe/NewPipe#5763]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by XiangRongLin** [comment]
No useable information here
