### ISSUE TITLE
Clicking on background playing notification does not open app correctly

### ISSUE THREAD

**Issue by sorab2142** [TeamNewPipe/NewPipe#577]
The app opens to an activity that is not in sync with the amount played.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by Stypox** [comment]
This now works as expected: when the app is opened from the notification the play time is synced correctly.
