### ISSUE TITLE
Unable to import subscriptions from YouTube

### ISSUE THREAD

**Issue by s6o1lu** [TeamNewPipe/NewPipe#5770]
### Checklist
- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Tap the 'Hamburger Menu'.
2. Tap on 'Subscriptions'.
3. Under 'Import from', tap 'YouTube'.
4. Follow the instructions to download the zip file from 'takeout' and extract the 'subscriptions.json' file.
6. Click the 'IMPORT FILE' option.
7. Choose the 'subscriptions.json' file through the file explorer.
8. In the 'Do you want to continue?' popup, tap 'OK'.
9. Message appears stating 'Imported'.

### Actual behaviour
The subscriptions fail to load.

### Expected behavior
Subscriptions get loaded.

### Device info

 - Android version: 9PKQ1.180917.001/Custom ROM version: MIUI Global 12.0.4|Stable 12.0.4.0 (PDMMIXM)
 - Device model: Redmi 6 Pro

**Comment by achazot** [comment]
Did you verify the contents of the JSON file ? Mine was empty when using Google Takeout directly. I had to take the following route to get the full subscription list:
Connect to youtube > Click on your profile pic > "Your Data" > dashboard > "more" > "Download your youtube data"
Then it will redirect to google takeout, and then you can download your populated JSON file.

**Comment by s6o1lu** [comment]
> Did you verify the contents of the JSON file ? Mine was empty when using Google Takeout directly. I had to take the following route to get the full subscription list:
> Connect to youtube > Click on your profile pic > "Your Data" > dashboard > "more" > "Download your youtube data"
> Then it will redirect to google takeout, and then you can download your populated JSON file.

This resolves the issue.

**Comment by Marcello6** [comment]
I experienced the exact same thing so I tried the solution. I noticed that JSON files are not available at the takeout, only CSV files. Is this a recent change?
