### ISSUE TITLE
Wrong language is shown

### ISSUE THREAD

**Issue by mueller-ma** [TeamNewPipe/NewPipe#578]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When I search for a video it displays "vor 5 tagen" (5 days ago), but when I click on a channel i see this in the contry language where I am.

**Comment by mauriciocolli** [comment]
@theScrabi I was wondering, why the hell do we have a content language selector? Just to mix the languages of the content and the titles/strings/interface of the app?

If changing the language of the entire app was intended, is a bad idea anyway, as we don't have all the languages of that list translated (just YouTube have).

A solution that I'm thinking is:

We get the device country code (the language/country code, e.g. `en`, `pt`, `de`) and put that in every request, that way, this mixing would not occur and both the interface and content would be in "sync".

**Comment by theScrabi** [comment]
yea we could use the selected language as the language that will be used for search/suggestion. However, I would leve the option to choose the language to search videos from.

**Comment by trymeouteh** [comment]
Not sure if this would help but I figured out what causes it. VPNs. When I am connect to a VPN server in another country were the language is not english it will display the video date in another language.

**Comment by AWalton** [comment]
This is still an issue. Despite being in an English speaking country and setting the phone and app languages to English it still shows as a foreign language. Why??

**Comment by B0pol** [comment]
This is because of the language of the app is system language (or VPN), but the content is English. It's fixe by #2921
