### ISSUE TITLE
Allow renaming export file

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5780]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Could you please add an option to rename the file while exporting? It's frustrating that we can't name it on our own. Every single time, it creates file with a different name.

If a new export file has the same name of any previous file in that folder, a popup should appear like "Np.xml already exists." Three options can be added as reply, "Replace file", "Save as Np1" and "Cancel exporting"

#### How will you/everyone benefit from this feature?

It becomes really difficult as there is no way to replace the previous file. Plus, keeping more files also turns things confusing. Allowing renaming will also let us avoid mixing up files with similar names.

**Comment by mhmdanas** [comment]
I have nothing to say for the feature request itself, but please fill out the "how will you/everyone benefit from this feature?" section of the template. Right now, you're putting what should be there in "describe the feature you want" section. Thanks in advance.

**Comment by SameenAhnaf** [comment]
@mhmdanas Okay, thanks for your suggestion.

**Comment by ATofighi** [comment]
I'll make a PR for this issue soon.

**Comment by Stypox** [comment]
@SameenAhnaf with SAF enabled I can rename the export file without problems. I wouldn't add support for it in the old file picker, just use SAF instead.

**Comment by SameenAhnaf** [comment]
@Stypox Yeah, I noticed it forcefully enabled in the latest update. You may close #6321 as well.
