### ISSUE TITLE
Add Download option for Long Press on Playlists

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5782]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

"Download" option for playlist will be immensely helpful. It will help us download a full playlist. One more thing, it should not directly download the full playlist. Users may need to deselect a few videos.
"Deselect all" or "Select all" should appear on the basis of all selected or not all videos selected respectively.
![IMG_20210408_190944](https://user-images.githubusercontent.com/79245641/114032457-23ee3300-989e-11eb-9c59-73f49a85834c.jpg)

#### How will you/everyone benefit from this feature?

Bulk download will be much more easier.

**Comment by NewNewPipe** [comment]
A similar proposal of mine has already been made. 8 days ago.

DOWNLOAD LIST - for later downloading.

https://github.com/TeamNewPipe/NewPipe/issues/5714

**Comment by SameenAhnaf** [comment]
@NewNewPipe Thanks, but that's not what I actually asked. I asked to download all videos of the playlist on a single click. Bulk selection options #5657 should be added to enhance downloading experience.

You asked for a option to download later. I asked to download right here and now.

**Comment by SameenAhnaf** [comment]
@mhmdanas Would you please on this issue as Nikilchad suggested in https://github.com/TeamNewPipe/NewPipe/pull/6309#issuecomment-846441294 ? Thanks in advance.

**Comment by mhmdanas** [comment]
@SameenAhnaf please avoid repeatedly pinging people in issues where they are not participating.

**Comment by opusforlife2** [comment]
@SameenAhnaf It is impolite to ping developers asking them to work on issues they may not be interested in. The developers are team members. They are generally aware of the goings-on in the repo, and if they're not, that means they are busy in real life. If they see an issue they are interested in working on, they will do so without needing to be prompted by anyone. For developers who contribute to the repo but aren't part of the team, it is okay to mention them in issues related to things they have already worked on, but even there it is better to exercise caution before doing such a thing.

In general, I have been noticing your activity in this repo, and I must say that your commenting frequency is a bit much (you joined GitHub 3 months ago and have already opened, or commented in, over 100 issues and PRs). As a result, team members (and anyone else subscribed to those issues) get a very high number of notifications from issues they might not be interested in.

At times, you seem to realise this yourself, as seen in your comment [here](https://github.com/TeamNewPipe/NewPipe/issues/6357#issuecomment-847096147).

So my advice is to calm down a bit, avoid pinging users unnecessarily, and reduce your commenting frequency, please. You're not breaking any rules, per se, but every community has a culture that new users have to learn to adapt to. :)

If you wish to talk about the project in general, you're more than welcome to make a Matrix account (or use an IRC client if you prefer) and join us in Newpipe's IRC channel at #newpipe:libera.chat. No one will mind if you go off-topic there, and usually, a team member will suggest you open an issue if there is something worth looking at.

P.S.: Your conversations with developers or users about what a particular feature should look like, and so on, are perfectly fine as feedback, and part of the development process.

**Comment by alik604** [comment]
I'm the opener of the duplicate, [#6487 - playlist download functionality](https://github.com/TeamNewPipe/NewPipe/issues/6487), wanted to voice my support here to show demand :)  
I considered putting up a bounty, but I decided to go with libra pay instead, _Transaction ID: 37559_. Now I just saw [this](https://www.bountysource.com/issues/56456257-feature-request-playlist-downloading-syncing), must be harder than I thought. 

_I guess us users should: youtube-dl -> dropbox/box/drive -> phone's local storage-> special mp3 app to play in that particular folder._

**Comment by opusforlife2** [comment]
Closed because?
