### ISSUE TITLE
Small close button when video is minimized makes it easy to accidentally open

### ISSUE THREAD

**Issue by j-james** [TeamNewPipe/NewPipe#5785]
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play a video while holding phone vertically
2. Swipe down on video
3. Tap the bottom right corner to close video
4. Repeat
5. Observe missing the close button and popping back up the video frequently

### Actual behaviour

It's quite easy to tap the area between the red button and the green / blue lines shown in the screenshot below. This opens up the video again, while tapping in that spot almost always is intended to close it.

### Expected behavior

Either the close button should take up more space, or some of the area between the red button and green / blue line should also trigger closing the video.

### Screenshots/Screen recordings
![Screenshot_20210307-002654_1](https://user-images.githubusercontent.com/35242550/110236141-103f5d80-7ee9-11eb-89e5-d95695a92975.png)

### Device info

 - Android version: GrapheneOS 11
 - Device model: Pixel 4a

**Comment by SameenAhnaf** [comment]
Actually, there's no need of "Cancel" option. Opening next video should automatically cancel the previous video if the new video is not enqeued.

**Comment by SameenAhnaf** [comment]
@j-james Let this issue stay open. I really need this.
