### ISSUE TITLE
Recaptcha 

### ISSUE THREAD

**Issue by hagueyno1** [TeamNewPipe/NewPipe#5788]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

I've had to perform a recaptcha once a day for the last 4 days so far, I didn't think to screenshot unfortunately, I just wondered if this is normal now or something that's either easy to fix or a problem my end with YouTube. 

### Expected behavior

To just open newpipe as normal and have it perform as it usually does, normally I get a recaptcha every so often not daily. 

### Device info
Samsung galaxy 
 - Android version/Custom ROM version:8.0.0
 - Device model:s7

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
There's nothing the Dev's can do about this, they said it earlier in a similar issue, it's just your network sending unusual traffic

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
While implementation of #5528 will solve this

**Comment by hagueyno1** [comment]
Hi, apologies then for repeating, I honestly did look and didn't find it,
maybe I should've scrolled further.
Thanks for letting me know, I'll delete some unwanted apps and have a clear
out that might go some way to helping it.
Thanks again, James.

**Comment by mhmdanas** [comment]
Since this isn't an issue with NewPipe itself, I'll be closing this issue. If you disagree, feel free to write a comment.

**Comment by hagueyno1** [comment]
Hi, that's fine.
Can I ask how I move all my playlists and subscriptions from one phone to
another? I don't have a memory card, I've just set the new one up using
smart switch between 2 galaxy phones but would love an easy way to transfer
it all rather than do it all one song at a time again like last time.
Thanks Paul.

**Comment by mhmdanas** [comment]
Go to `Settings > Content > Export database` on your old device to export your data. Move the resulting file to your new device, then go to `Settings > Content > Import database` and choose the file.
