### ISSUE TITLE
YouTube "seasons" (or series) are not discoverable in search results

### ISSUE THREAD

**Issue by omentic** [TeamNewPipe/NewPipe#5793]
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Search a phrase that would normally bring up a series (season? I'm not entirely sure what they're called) in YouTube and Newpipe - ex. Essence of Linear Algebra

### Actual behaviour
The series doesn't show in NewPipe's results. The attached screenshots show it as the top result on YouTube's website.

### Expected behavior
NewPipe should show series in its search results - perhaps as playlists?

### Screenshots

![Screenshot_20210307-165042](https://user-images.githubusercontent.com/35242550/110261534-7a95e380-7f65-11eb-8c6b-4e97bee246bc.png)
![Screenshot_20210307-165047](https://user-images.githubusercontent.com/35242550/110261540-7cf83d80-7f65-11eb-912b-bc6f73777296.png)

### Device info

 - Android version: GrapheneOS 11 
 - Device model: Pixel 4a

Also, loving the new unified interface!

**Comment by yashpalgoyal1304** [comment]
* yeah, wow, i hit the same issue while searching for *exact same series*.
* What more, the series dont open even with link on v0.21.13
* Example: 
try opening this link in newpipe: [Essence of linear algebra]

[Essence of linear algebra]: https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab

**Comment by yashpalgoyal1304** [comment]
@j-james can u please small the screenshots?? 

> when you send screenshots, could you please make them properly sized? 
> Use `<img src="INSERT_LINK_HERE" height="300px"/>`
> _- https://github.com/TeamNewPipe/NewPipe/issues/6841#issuecomment-892756057_
