### ISSUE TITLE
Holding "Add to" button opens All Playlists

### ISSUE THREAD

**Issue by n-ce** [TeamNewPipe/NewPipe#5794]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

If holding on downloads button brings up all downloads, then holding on add to button should bring up all playlists.

#### Is your feature request related to a problem? Please describe it

Not Related to any problem.

#### How will you/everyone benefit from this feature?

Faster access to playlists when needed.

**Comment by Marius1501** [comment]
I would work on this issue. 😃

**Comment by Stypox** [comment]
I'm sorry, but this is counterintuitive and is not what you would expect from an "Add to" button. You can open the drawer by swiping from left to right and then tap on "Bookmarks" to achieve the same thing in roughly the same amount of time.
