### ISSUE TITLE
spaces converted to %20 in existing download directories

### ISSUE THREAD

**Issue by turboteckel** [TeamNewPipe/NewPipe#580]
If I have a folder with a space in its name and point NewPipe to download to it, it will create a new folder with the same name but with the spaces converted to %20. Haven't tested it with other characters.

NewPipe 0.9.7
Android 4.3

**Comment by coffeemakr** [comment]
Good catch and thanks for reporting.
The issue should be resolved in the next release.

**Comment by coffeemakr** [comment]
@theScrabi you can close this issue
