### ISSUE TITLE
In Romanian translation 1 minute is wrongly translated [localisation/translation]

### ISSUE THREAD

**Issue by iamthesenate1** [TeamNewPipe/NewPipe#5805]
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Select Romanian language
2. Refresh subscription list
3. Wait one minute "fluxul a fost actualizat acum 1 minuta"

### Actual behaviour

It will say "fluxul a fost actualizat acum 1 minuta"

### Expected behavior

It shout say "fluxul a fost actualizat acum 1 minut"

### Screenshots/Screen recordings

![Screenshot_2021-03-10-21-11-09-595_org schabi newpipe](https://user-images.githubusercontent.com/77978836/110684520-eab29c80-81e5-11eb-9386-5bd8c5ce9b7d.jpg)

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
You can fix that yourself by using Weblate. See [our contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#translation). If you have any issues please feel free to make a comment.

**Comment by iamthesenate1** [comment]
That's the problem. I corrected that before 0.20.9 but it is still there
![Screenshot_2021-03-11-09-49-46-664_mark via gp](https://user-images.githubusercontent.com/77978836/110753489-50873e80-824f-11eb-9bb0-72e995df3400.jpg)

**Comment by mhmdanas** [comment]
Oh, sorry, seems like I misunderstood the root of the issue. This issue seems to be from https://github.com/ocpsoft/prettytime. You probably want to report this there.

**Comment by iamthesenate1** [comment]
Ok. Thanks

**Comment by iamthesenate1** [comment]
One question. I made a PR on https://github.com/ocpsoft/prettytime and I would like to know, when it will be merged, how much time will it take NewPipe to implement it.
