### ISSUE TITLE
Viper4Android Support.

### ISSUE THREAD

**Issue by killoid** [TeamNewPipe/NewPipe#581]
can [this](https://github.com/vipersaudio/viper4android_fx) equalizer support be added in this app? currently i have viper4android installed & it works fine except on newpipe. the audio processed through it isn't affected by viper4android. it would be great to have the support of this equalizer.

**Comment by mauriciocolli** [comment]
NewPipe uses Exoplayer in both background and video player, so there must be some incompatibility with it, maybe the equalizer don't affect "low level" media APIs that this library uses.

Can you tell me if the official Youtube app is affected by the equalizer (it uses ExoPayer too)?

**Comment by killoid** [comment]
oh i see. official app also doesn't support it. i don't use magisk so i can't test it out.

**Comment by mauriciocolli** [comment]
It's a incompatibility specifically with your phone/rom, so this issue can be closed.

**Comment by Crystal-RainSlide** [comment]
Anyone having this kind of problem should try install or reinstall & reconfigure the Audio Compatibility Patch module first: https://github.com/Magisk-Modules-Repo/acp
