### ISSUE TITLE
Unable to minimize video.

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#5811]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. View the video in pip mode
2. Maximize the video from the pip window
3. Attempt this a few times to possibly get similar bug results.

### Actual behaviour

The button to maximize or minimize the video does not register at all with my finger pressing and I am forced to close the whole app every time.

### Expected behavior

To be able to change the size of the video at will without the button getting stuck.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Galaxy S10

![NewPipe Screenshot 3-12](https://user-images.githubusercontent.com/57234536/110923729-33a24800-82ef-11eb-8a72-5fee1cf37187.jpg)

**Comment by tsiflimagas** [comment]
Does this problem still occur?
