### ISSUE TITLE
Quality of Life Improvement Requests

### ISSUE THREAD

**Issue by esotericDisciple** [TeamNewPipe/NewPipe#5814]
(*Submitted using FastHub-Libre)

1.  Having an option to not present any notification regarding channel/feed fetch errors after syncing— Studio Mudprints ( https://www.youtube.com/channel/UCc2aNk4wPtcuGyT4ZtSUloA ) was only gone for a few hours and that "sorry, something went wrong" message was popping up with every app interaction...

2. Playbar is too small, making seeking to specific times near impossible because of the slipperiness of the screen and the accidental switching to buttons too close in proximity. A thicker playbar and selection handle, or even just switching to a scrollbar-style UI, is pretty much an essential change that needs to be made...

3. There needs to be an auto-fullscreen option for phones with higher resolutions and/or higher minimum width. Right now playing a video leaves recommended videos and other clutter on the screen:
![](https://i.imgur.com/FGrGjy3.png)

And no I can't lower the screen width as it ruins the layout of sites like NPR:

![](https://i.imgur.com/0UEMSnl.png)

Lower widths removes the ability to control the playlist and/or toggle the autoplay features:
![](https://i.imgur.com/TcvRF3n.png)

And having to toggle the fullscreen from the video causes it to play with the ui covering and tinting the video, forcing me to have to use the awful seeking UI to try and go back so I can see that part with nothing covering it...

**Comment by TiA4f8R** [comment]
Please follow the issue template and edit your issue.

**Comment by esotericDisciple** [comment]
This is a feature imperative, but I couldn't  find a way to navigate to the feature submissions page in FastHub-Libre, which also did not have any template for the issue submissions page...

**Comment by ChiefMikeK** [comment]
> This is a feature imperative, but I couldn't find a way to navigate to the feature submissions page in FastHub-Libre, which also did not have any template for the issue submissions page...

[New Issue · TeamNewPipe/NewPipe](https://github.com/TeamNewPipe/NewPipe/issues/new/choose )
