### ISSUE TITLE
Unable to load feed

### ISSUE THREAD

**Issue by ebanDev** [TeamNewPipe/NewPipe#5817]
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Install Newpipe
2. Refresh feed (My subscription list is available in attachment)
3. See that it blocks while loading feed

### Actual behaviour

The feed don't load

### Expected behavior

It should load 🤷

### Screenshots/Screen recordings

![Screenshot_20210313-152037_Fennec](https://user-images.githubusercontent.com/57091497/111033054-ad315780-840f-11eb-8a03-02a7616d5903.png)

### Device info

 - Android version/Custom ROM version: LineageOS 17.1
 - Device model: Lenovo Z5 pro GT

**Comment by ebanDev** [comment]
[NewPipeData-20210313_151530.zip](https://github.com/TeamNewPipe/NewPipe/files/6134936/NewPipeData-20210313_151530.zip)

**Comment by mhmdanas** [comment]
Do you live in the EU or use a VPN that connects to the EU? If so, this might be a duplicate of #5977.

**Comment by ebanDev** [comment]
Yes, I'll try that thanks
