### ISSUE TITLE
Can you add the multi-sharing feature

### ISSUE THREAD

**Issue by muhmd10** [TeamNewPipe/NewPipe#5819]
https://www.mediafire.com/file/6s8c7y5462einj2/0.20.2__good.mp4/file 

https://www.mediafire.com/file/ij6dusedl5pmq16/0.20.11_bad.mp4/file

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by TiA4f8R** [comment]
Please follow the template properly and edit your issue.
