### ISSUE TITLE
[SonarQube] Configure exclusions

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#5822]
In SonarQube files can be excluded from the analysis. I would propse to exclude following files
1. xml files
2. test files
3. ~~database entities (they all seem to end with `Entity` or `Entry`)~~ Thinking again, there definetly are ways to do db entities wrong
4. html files

It's important to at least exclude xml before the first run. Otherwise the analysis has a bunch of useless files

**Comment by XiangRongLin** [comment]
@TobiGr @Stypox what are you thought on this?

**Comment by XiangRongLin** [comment]
If no one has any objections until saturday im going with the list in the body

**Comment by TobiGr** [comment]
List above looks good to me.

**Comment by XiangRongLin** [comment]
Done by adding
`**/*.xml` and `**/*.html` to `sonar.exclusions`
