### ISSUE TITLE
Many bugs related to Android TV, newpipe 0.20.11

### ISSUE THREAD

**Issue by PulkitBhardwaj1** [TeamNewPipe/NewPipe#5828]
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/69087924/111076394-29ac5f00-8512-11eb-8f38-dd7c6ef3dd86.mp4

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by TiA4f8R** [comment]
@PulkitBhardwaj1 Can you please let us know what's wrong and fill the template properly please? We couldn't help you with the information you provide.

**Comment by opusforlife2** [comment]
Closing until more info is provided.
