### ISSUE TITLE
Show video and audio thumbnail in Download Manager

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5834]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Video thumbnail is not shown in download manager. It's a little frustrating. Sometimes, I have to deal with video titles like "Episode 65" and "Episode 66" which are slightly confusing although video thumbnail could solve the problems easily.

**Comment by Stypox** [comment]
#5445
