### ISSUE TITLE
50kbps Opus Audio Streaming Option

### ISSUE THREAD

**Issue by n-ce** [TeamNewPipe/NewPipe#5838]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

An option to enable 50kbps Opus background playback (audio).

#### Is your feature request related to a problem? Please describe it

Not related to any software issue.

#### Additional context

The 50kbps option could be embedded in the player itself, just like the video player has resolution options.

#### How will you/everyone benefit from this feature?

For people with limited and slow internet access, it will open doors to seamless music streaming which is unprecedented using opus as the codec.

**Comment by mhmdanas** [comment]
Thanks for opening an issue! I believe this is a duplicate of #1583. If you disagree, feel free to make a comment.

**Comment by halovilyx** [comment]
download videos on musics not work please fixed
