### ISSUE TITLE
Install button for newpipe in f-droid does nothing 

### ISSUE THREAD

**Issue by mcattell** [TeamNewPipe/NewPipe#5842]
After watching a video promoting newpipe I decided to try it by first installing f-droid. After searching for and finding newpipe, I clicked the "install" button. Nothing happened. I rebooted my device (Huawei p30 Pro) and tried again with the same result. Am I missing something?

**Comment by mhmdanas** [comment]
Thanks for opening an issue! This seems like an issue with F-Droid, not NewPipe, so you'll probably have better luck asking in their forums.
