### ISSUE TITLE
Pressing fullscreen in popup mode should directly go to fullscreen instead of opening the app

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#5845]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Click on an external Youtube link, open in popup mode. Click fullscreen. Newpipe app opens. Instead of opening the app, video should directly go to fullscreen without opening the app(Draw the video over entire screen and don't open the app)

#### Is your feature request related to a problem? Please describe it

Problem is that I use my RSS reader to subscribe to channels and Newpipe to watch them. With this feature I won't have to open and close the app repeatedly.

#### Additional context

None

#### How will you/everyone benefit from this feature?

For those who use RSS readers and don't want to seaparately go to Newpipe to check subscriptions this feature is great. Idk about any other use cases though.

**Comment by mhmdanas** [comment]
I don't think I fully understand the problem here. Can you clarify a bit more?

**Comment by nikhilCad** [comment]
When you click the full screen button in pop up video it opens tje newpipe app.

It should NOT open the app, but just directly start playong the video in fullscreen(in popup mode the app is not made).

This is only for videos opened in popup mode OUTSIDE the app, like if you click this link below and open it in pop up mode

https://www.youtube.com/watch?v=KhtAvZAw5sg

**Comment by micah-k** [comment]
As I understand Android, the pop-up mode is essentially a picture-in-picture mini app, so NewPipe actually is open when the pop-up player is active. It wouldn't actually be possible to play in fullscreen without NewPipe being open.

**Comment by opusforlife2** [comment]
@nikhilCad Rotate to landscape and pinch to expand to full screen.

**Comment by nikhilCad** [comment]
@opusforlife2 wait what how? Note that I am asking for videos opened for outside the app.

Say you open this link from your mobile using pop up player
https://www.youtube.com/watch?v=rwjmyZUA2O8

I want the ability to play it in fullscreen without opening the ui of the app, as pressing the fullscreen button opens the ui of the app.

Or if you have a little time on hand, can you share a video of how to do itif possible? Because I don't understand from your comment.

**Comment by nikhilCad** [comment]
@opusforlife2 that still requires auto rotation open though.
Clicking on the fullscreen button should go into fullscreen without opening the app UI regardless I guess.

**Comment by opusforlife2** [comment]
Alright. Let's see if someone wants to work on this. (Though I think this might tiptoe the line of UI clutter/feature bloat.)

**Comment by avently** [comment]
@opusforlife2 why this button should open video in fullscreen? It's designed for another usage. This button should just open the app like it is structured, no more no less. So i think this issue can be closed but it's up on you.

**Comment by opusforlife2** [comment]
I was thinking any solution to this would involve adding a new button. The 'switch to app' button doesn't need to be changed.

**Comment by SameenAhnaf** [comment]
@https://github.com/avently I understand your case. But many users like me actually keep auto rotation off. In my opinion, video info is less likely required in the middle of streaming a video.

Turning to portrait and portrait button are always available for video info. I know, the same goes for current state. But why would I have to handle an info which is actually not required? Everything should be practical instead of just logics like "This is how this works. So, I am gonna make that."

**Comment by SameenAhnaf** [comment]
@avently I understand your case. But many users like me actually keep auto rotation off. In my opinion, video info is less likely required in the middle of streaming a video.

Turning to portrait and portrait button are always available for video info. I know, the same goes for current state. But why would I have to handle an info which is actually not required? Everything should be practical instead of just logics like "This is how this works. So, I am gonna make that."

**Comment by Stypox** [comment]
What do you think of #5459?

**Comment by SameenAhnaf** [comment]
@Stypox I think, there should be options to switch to both main and full screen players seamlessly. 

In most cases, users don't require main player. By starting popup player, the user has already clarified that he or she is prioritizing the video itself and multitasking. No need of other stuff.

The opposite is also true. Suppose, the summary of the video is discussed right at the beginning of the video. In such case, the user may want to take notes and highlights quickly and take a deep dive into description and comments later.

#6785 suggests "Long press to full screen" which should work in most cases, I hope.

Btw, you may have a look at #6784 as it is more related to that PR. I discussed an another alternative which may be useful for external player users as well.
