### ISSUE TITLE
Desktop Web Version.

### ISSUE THREAD

**Issue by KeithBarrows** [TeamNewPipe/NewPipe#5852]
While I am certainly excited about an Android app that does what this does, I do 95% of my YT watching on a desktop.  Any thoughts of opening up a web site with this fantastic engine?

**Comment by selurvedu** [comment]
(Somehow every time I open NewPipe issue tracker, a request like this shows up...)

**Comment by lawson85** [comment]
Flash Android x86 on a USB stick and use that, or use LDPlayer emulator and get NewPipe as a workaround

**Comment by mhmdanas** [comment]
@KeithBarrows we currently have no plans for an official web interface. You can instead take a look at https://github.com/TeamPiped/Piped (which uses NewPipeExtractor behind the scenes) or https://github.com/iv-org/invidious (doesn't use NewPipeExtractor, but currently supports more features and has many public instances).

Also, please don't remove the template next time when opening an issue.
