### ISSUE TITLE
Constant Recaptcha request when trying to use Newpipe

### ISSUE THREAD

**Issue by oXvTV** [TeamNewPipe/NewPipe#5853]
Constant Recaptcha request when trying to use Newpipe. I've tried uninstalling and reinstalling and same thing happens. Any help, explanation or fix would be much appreciated. Thanks.

**Comment by TobiGr** [comment]
Solve the ReChaptcha and press "done" in the right corner afterwards

**Comment by oXvTV** [comment]
It doesn't seem to work unfortunately, another new recaptcha just appears after

**Comment by oXvTV** [comment]
Strange. When on mobile data, solving the recaptcha works. But on wifi, the recaptcha constantly reappears. Of course I would like to be able to use newpipe on wifi as well

**Comment by SameenAhnaf** [comment]
It's really, really strange. I use mobile data by Grameenphone mobile operator from Bangladesh and I face constant recaptchas. However, I didn't face such issues from any other mobile operator or Wi-Fi. Please fix this asap

**Comment by treble2019** [comment]
This is likely that you are having some spyware that is making google/youtube suspicious of the your connection - they think you are bots. Test NewPipe from a different Wifi network or ask your friend to install NewPipe and see. Or can you test it with browser - is it OK. Or with a laptop?

Issues with Recaptcha always means there are issues with your network.

**Comment by mhmdanas** [comment]
This is not an issue with NewPipe, but with your network, so we unfortunately can not do anything to fix this. However, there are possible ways to bypass the reCAPTCHAs altogether. For example, see #5528.
