### ISSUE TITLE
Add channels to feed groups directly from channel page

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#5865]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The ability to add subscribed channels to feed groups directly from channel page.

#### Is your feature request related to a problem? Please describe it

anyone uses the group feed will soon find it hard to create new groups or maintaining them because it becomes harder and harder to keep track. also subscribing to a new channel and adding it to multiple related groups is not easy in itself. 

#### Additional context

My suggestion is to add a button next to the subscription button. taping the button will show a drop down menu containing all feed groups with a checkbox next to them. the channel will then be added to the selected groups by the user.

this is inspired from what youtube use to add videos to playlists. off course the button will only show up in channels the user is already subscribed to.
![IMG_20210321_033550](https://user-images.githubusercontent.com/63132171/111890266-dc8c2980-89f8-11eb-8b7a-bf367972eed2.jpg)

#### How will you/everyone benefit from this feature?

This would make adding new channels to groups immediate.. and would save so much effort especially if your adding the new channel to multiple groups. maybe try to add a channel to multiple groups to see what i mean.

also this make it a lot  easier to organize and maintain subscribed channels right from the channel page, no more hunting for that channel in every group.

**Comment by mhmdanas** [comment]
I think we can track this in #5836. You can post your mockup there.

**Comment by UmBottesWillen** [comment]
I'd very much like to see this feature get implemented, along with an easy way to see the channelspresent in a channel group or the channel groups per channel.
