### ISSUE TITLE
Request Mute Channel. Copying subs from YT also brought "suggested videos"

### ISSUE THREAD

**Issue by ScotterMonk** [TeamNewPipe/NewPipe#5868]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I imported all my subs from YouTube and I see them in NewPipe. And... I see other "popular" ?recommended by YT? bullshit coming up. I can't merely unsubscribe from them because they show up as not subscribed. I wonder if you plan on adding a "mute channel" feature? Or is there something *I* can do?

#### Is your feature request related to a problem? Please describe it
I want my stream to be less cluttered with YouTube recommended junk. 

#### How will you/everyone benefit from this feature?
Hopefully, this feature will help people declutter their timeline and more quickly see the videos they *want* to see. 
Thank you!

**Comment by mhmdanas** [comment]
Can you send a screenshot? You may be actually seeing the "Trending" tab (which is the default initial tab) and confusing it with the subscription feed. You can see the latter by opening the drawer (press on the three horizontal lines on the top left of the screen) and then pressing on "What's New."

**Comment by ScotterMonk** [comment]
Aha! Thank you! That was the issue!
