### ISSUE TITLE
Youtube: Hide/disable certain types of content (announcements / live streams)

### ISSUE THREAD

**Issue by SwallowYourDreams** [TeamNewPipe/NewPipe#5875]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
It'd be great if we could disable two types of content in the Youtube module of Newpipe: live streams and announced videos (which is the term I will use for videos that will be released in x days, as set by the content creator).
Why would anyone want to disable these types of content? Well, both types are sorted to the very top of Newpipe's "What's new" section, which makes sense: after all, a live stream is always the most presently-posted content, and announced videos are in the future. However, there are many channels that either
- permanently livestream (such as certain news outlets) or
- post announcements of videos to be released in 14+ days. In this regard, Newpipe is actually _more_ annoying than the default Youtube experience, which, after all, does not show any videos to be released in the future.

If subscribed to many such channels, users will be left with utterly cluttered "What's new" lists that permanently have something pinned to the very top even though that content isn't, in fact, "new" to them, and probably not even desired. After all, why would I want to spend days on end staring at the announcement of a video to be released in a fortnight?

#### Additional context
UI suggestion: the feature could be integrated into the UI in the form of two new sliders, which might be placed in the Settings > Content menu. There you can already disable certain types of content (e.g. adult content).

#### How will you/everyone benefit from this feature?
See above: users subscribed to certain channels will have the option to customise their viewing experience, make a conscious choice about the content they're interested in (instead of having to accept whatever content creators toss their way) and unclutter their feed.
I for one, am not interested in video announcements at all. I do not see why they should be given priority in my feed list and grab my attention above all else in my feed for weeks on end. If a video is released, it will show up in the list. _Until_ it's released, though, I don't care about it and don't want to have it show up in the list.

**Comment by BinFlush** [comment]
Yes! This is really needed.
I've already had to unsubscribe from several creators that I'm otherwise interested in, just because they constantly hog the top of my "new videos" page.

**Comment by Camfly** [comment]
![IMG_20211226_092122](https://user-images.githubusercontent.com/10359782/147396537-2ad7873e-ef55-40f1-b46a-d58842d7f08c.jpg)
When I said they should be visually distinctive, this was not what I meant.

**Comment by SwallowYourDreams** [comment]
> When I said they should be visually distinctive, this was not what I meant.

This visual style is applied to all new content, not just live and future videos.

**Comment by Justicefpv** [comment]
This feature is desperately needed, premiering videos take up half of the whats new feed and are just clutter. An option to remove premiering in x hours videos from the what's new feed would be perfect and greatly appreciated.

**Comment by shom13** [comment]
Any update on this ?

**Comment by lazycalcium** [comment]
Hello, any update on this? Sometimes channels schedule out a video a week in advance and it is pinned to the top of the whats new page that entire time.

**Comment by SwallowYourDreams** [comment]
> I don't want to have to unsubscribe from a YouTuber just to have that real estate at the top back.

I have, in fact, gone this route in the past. I've unsubscribed from notorious video schedulers and permanent live streamers in order to clean up my feed. Seemed like the lesser of two evils. But one shouldn't have to resort to such desparate measures. Unfortunately, there seems to be no update from the devs on this. Doesn't seem like at top priority atm.

**Comment by SameenAhnaf** [comment]
@litetex This should be closed in favor of https://github.com/TeamNewPipe/NewPipe/issues/8069

**Comment by theresyourproblem** [comment]
👍 and he's gone. Clock at the top.
![Screenshot_20230402-102637_NewPipe](https://user-images.githubusercontent.com/95443363/229362790-e051954f-4dc8-48c7-b112-4b2dcfdfc7f3.png)

![Screenshot_20230402-102651_NewPipe](https://user-images.githubusercontent.com/95443363/229362826-42c0ca4c-0b44-4bbd-8a95-c8039a3f104b.png)

**Comment by xXTeMmiE07Xx** [comment]
i have to scroll down so so much to get to actually new videos because of 24/7 streams
please let us hide them

**Comment by SwallowYourDreams** [comment]
Ever since "Show the following streams" dropped, along with the ability to hide "Upcoming" vids, I was hopeful that livestreams would be added shortly thereafter. At least we've now got a place where the option could go.

**Comment by SwallowYourDreams** [comment]
> What happens if you disable Live under Content > Fetch channel tabs?

Pretty much what the setting says: the "Live" tab disappears from the channel page. Any live *feeds* will still hog the top of the "new videos" feed.

**Comment by SwallowYourDreams** [comment]
> And then there's a Fetch channel tabs menu, much below. 

Now I get it. Thanks for pointing that out! This actually does what I wanted and made live streams disappear from the feed. It'd still be a good idea to push this behaviour into the "eye symbol* menu at the top of the feed rather than hide it way down in the settings.

That said: I'm a very happy camper now. Thanks!

**Comment by SwallowYourDreams** [comment]
Either way, the eye icon could use a "hide live feeds" entry since it's the most obvious place for users to look for this very functionality.
