### ISSUE TITLE
[Feature request] Default video display mode

### ISSUE THREAD

**Issue by cyaneko** [TeamNewPipe/NewPipe#5880]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Add an option to use fill, enlarge or fit video to screen mode by default

#### Is your feature request related to a problem? Please describe it
Enlarge mode which is enabled by default cuts off vital portions of the videos I'm trying to watch all the time; I have to manually change it to "fit" or "fill" every time I watch a new video which is very annoying

#### Additional context
My phone (Samsung Galaxy M31s) has a nonstandard aspect ratio

#### How will you/everyone benefit from this feature?
It removes an annoyance from the UX.

**Comment by mhmdanas** [comment]
It IS supposed to save the option you choose, but recently a bug was introduced which causes it to save the wrong option. The fix will be released in the next update. See https://github.com/TeamNewPipe/NewPipe/issues/5613.
