### ISSUE TITLE
Bug: Infinite loop

### ISSUE THREAD

**Issue by Joe23232** [TeamNewPipe/NewPipe#5884]
I love NewPipe and I have now replaced it with the YouTube app. However the problem is that plenty of times whenever I open the app, it will go in an infinite loop of loading screen until I close the app and open it up again. This happens many times so I believe this is a bug.

I just installed the app a few days ago

**Comment by TiA4f8R** [comment]
Please fill the template properly and try to update to the last version.

**Comment by Joe23232** [comment]
Honestly after seeing the censorship you guys support I am done with this app. See how support for censorship actually loses your people? I was excited to use this app but then after seeing the censorship you guys support (I don't know if you specifically supported it or not) I am not bothering with this app anymore!

**Comment by TiA4f8R** [comment]
@Joe23232 The thing that you don't understand is that we cannot help you with the information you provided. The template is here in order to give the ability to help you and maybe fix what's wrong if it's a problem within the app (and not your system), with useful informations such as your device information, your app version, and the steps to reproduce a bug. It isn't against you.
Please add a screencast if you can, the device you're using and its ROM, and logs if you can capture any. Also check if you're using 0.20.11 version.

Sorry to be rude, but when you triage a lot of issues which are duplicates and duplicates of existing issues or not understandable, you are tired of people who doesn't follow templates.

**Comment by Joe23232** [comment]
> @Joe23232 The thing that you don't understand is that we cannot help you with the information you provided. The template is here in order to give the ability to help you and maybe fix what's wrong if it's a problem within the app (and not your system), with useful informations such as your device information, your app version, and the steps to reproduce a bug. It isn't against you.
> Please add a screencast if you can, the device you're using and its ROM, and logs if you can capture any. Also check if you're using 0.20.11 version.
> 
> Sorry to be rude, but when you triage a lot of issues which are duplicates and duplicates of existing issues or not understandable, you are tired of people who doesn't follow templates.

All good mate, I understand that I should follow a template that I can understand mate and I have no issue in that at all.

However the members of this project have shown that they like and support censorship as seen in this [issue](https://www.bloomberg.com/news/articles/2021-03-23/microsoft-said-to-be-in-talks-to-buy-discord-for-more-than-10b).

The members were also given a lot of likes and dislikes (more dislikes than likes) which shows that the members support censorship rather than freespeech. At this point I fail to see the difference between NewPipe and YouTube when both sides support censorship all because some contents doesn't conform to their ideologies and their opinons are dismissed as "conspiracy theories" and "extremists".

Yes you get bad content but that is also on YouTube as well. There are also plenty of good contents on BitChute (for example) as well. Its like saying you are going to ban the Internet because there are lots of bad contents (and illegal contents) on it. The Internet has good and bad stuff, so does BitChute.

Hell YouTube's censorship has gotten so bad that people using public domain music in their videos or even showing hell a [short footage of a duck](https://www.youtube.com/watch?v=pFCUGemAy6Y&t=1s) gets their videos demonitised or even removed or having their accounts suspended. This is why I prefer freedom of speech

I believe that everyone should be entitled to their own opinion. Yes people can have an opinion that others may or may not like, simply censoring people is not the right move.

I was very excited to use this app and to maybe even contribute to it or donate to it, but after seeing this disgusting behaviour from the memebers (I am not saying it is you) I don't want to have this app anymore let alone contributing and donating to this app.
