### ISSUE TITLE
Add personlisation based on the content watched and the channels we have subscribed to

### ISSUE THREAD

**Issue by Joe23232** [TeamNewPipe/NewPipe#5885]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Hi I think it would be a great idea if there was personalisation (similar to what YouTube does) based on the content we watch and the channels we subscribed to.

#### How will you/everyone benefit from this feature?

I believe people can find the contents they love more easily and see the stuff they are interested in, this is something I miss when using YouTube

**Comment by mhmdanas** [comment]
This is not going to happen, as all the videos are fetched directly from YouTube/SoundCloud/whatever service you use. They're the ones who decide what you're shown.
