### ISSUE TITLE
Please add rewind and forward buttons.

### ISSUE THREAD

**Issue by Joe23232** [TeamNewPipe/NewPipe#5886]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it

Please add rewind and forward buttons to make it easier to go back and forward.

#### How will you/everyone benefit from this feature?

Currently it is difficult to go back or forward if somebody has missed something and it is hard to use the scrubber.

**Comment by TobiGr** [comment]
Please add more info: where do you want to got back and forward? In the background player, the popup player or the "normal" player (fullscreen or preview mode while seeing the video's description, comments etc.)
In general, you can tap twice on the left side of the screen to go back or twice on the right side of the screen to go forward.

**Comment by Joe23232** [comment]
Ok thanks I didn't know that
