### ISSUE TITLE
Consider adding the ability to like/dislike a video as well as to add comments to the video.

### ISSUE THREAD

**Issue by Joe23232** [TeamNewPipe/NewPipe#5887]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Additional context

I understand that there is no "sign in" in to google account in order to prevent Google from tracking you, but what if it can be done in such a way where ONLY if the user clicks on a like/dislike and adds comments/replies then in those sense Google might track it, but for the rest of the stuff such as your history, your local subscriptions (which is done within new pipe and not from YouTube) is not sent back to Google?

#### How will you/everyone benefit from this feature?

This can make this app a complete/better replacement of YouTube.

**Comment by TobiGr** [comment]
Google can still track you via the phone's IP address. so either Google or no Google. Once you signed in on the phone from an IP address, Google can still track you via the IP address you used when signing in, at least for some time. On the other hand, if we add a log in feature, the app needs to be comply with the Google and YouTube TOS.
In other words, this feature will not be implemented
