### ISSUE TITLE
Give an ability to add another video streaming service such as BitChute.

### ISSUE THREAD

**Issue by Joe23232** [TeamNewPipe/NewPipe#5888]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

Currently services such as BitChute are growing due to YouTube's severe censorship and therefore alternative services such as BitChute are able to provide alternative content. Unfortunately New Pipe only shows contents from a limited sources such as YouTube, PeerTube etc. I wish that the app also allows users to add whatever platforms they would like to it.

Additionally it would be nice if there was a section where it would show all the desired content from different platforms (for example YouTube, BitChute etc).

**Comment by TobiGr** [comment]
We have discussed BitChute several time now. The answer is still the same: https://github.com/TeamNewPipe/NewPipeExtractor/pull/325#issuecomment-626801193

**Comment by Joe23232** [comment]
I saw your comment and it seems like you support censorship over freespeech. Yes there are terrible contents but the way how YouTube has been treating innocent videos including a video of a [duck that was demonitised](https://www.youtube.com/watch?v=pFCUGemAy6Y) YouTube is no longer a viable source.

And anyways it seems like you did not read my entire post. I wanted an ability to add any video platform to my list not limiting to Bitchute. I didn't ask for to add Bitchute as well.

**Comment by Joe23232** [comment]
As Linus Torvalds says he has seen projects have so much political correctness that a project no longer focuses on the project itself. Why bring politics into technology?

And I was not suggesting to add Bitchute as an official video platform. I was suggesting the ability to add any video platforms.
