### ISSUE TITLE
The ability to add different video platforms

### ISSUE THREAD

**Issue by Joe23232** [TeamNewPipe/NewPipe#5889]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

Additionally it would be nice if there was a section where it would show all the desired content from different platforms

**Comment by mhmdanas** [comment]
Can you clarify what you mean by "adding video platforms"? It's not clear what you're trying to say.

**Comment by Mesum-Hussain** [comment]
It's probably going to be difficult to give user the ability to add platform they like. Each platform is a new feature entirely, which needs to get support from the NewPipe's side.

**Comment by mhmdanas** [comment]
@Mesum-Hussain I don't know if that's what the issue author meant, but you're absolutely right.

**Comment by mhmdanas** [comment]
@Mesum-Hussain I don't know if that's what the issue author meant, but you're absolutely right.

**Comment by mhmdanas** [comment]
@Mesum-Hussain I don't know if that's what the issue author meant, but you're absolutely right.

**Comment by Mesum-Hussain** [comment]
> @Mesum-Hussain I don't know if that's what the issue author meant, but you're absolutely right.

I don't know, maybe you are right. I interpreted it that way because 5889 was mentioned in a discussion about a feature request for adding LBRY access to NewPipe..... I came here from there.

**Comment by mhmdanas** [comment]
I didn't mean that you're wrong, just that with so little info provided by the author, we can't be sure what they mean. Since the author hasn't answered on my reply that was posted in March, I'm closing this.
