### ISSUE TITLE
Q: Does NP give any feedback about the watching time to YTs APIs?

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#589]
I've recently seen some videos which say (I know that it actually doesn't have to mean anything) that since the last time the most important thing is not how many clicks a video has but how long it has been watched, so now I have kinda bad feelings about using this app because I assume that it doesn't report anything.

**Comment by theScrabi** [comment]
No it does not report how long the video is watched, and since it's NPs goal to keep the trafic with google as low as possible this will also not come. Sorry.

**Comment by OffifialMITX** [comment]
No need to feek sorry, the point about Google is more important in my opinion. Thanks for the answer.

Am 17. Juni 2017 13:22:14 MESZ, schrieb Christian Schabesberger <notifications@github.com>:
>No it does not report how long the video is watched, and since it's NPs
>goal to keep the trafic with google as low as possible this will also
>not come. Sorry.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TeamNewPipe/NewPipe/issues/589#issuecomment-309209270

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by theScrabi** [comment]
You know when we have this discussion now, It would be interesting to know if the view count was increased when newpipe is used. I doubt it though.

**Comment by OffifialMITX** [comment]
I'll test it.

Am 17. Juni 2017 15:43:06 MESZ, schrieb Christian Schabesberger <notifications@github.com>:
>You know when we have this discussion now, It would be interesting to
>know if the view count was increased when newpipe is used. I doubt it
>though.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TeamNewPipe/NewPipe/issues/589#issuecomment-309215929

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by OffifialMITX** [comment]
Well that's strange... I've tried to watch a video on my own channel, and while the video itself didn't get a higher view count, just like the other videos, my total view count increased by one.

**Comment by MehediBlaze** [comment]
When downloading audio new pipe is not capturing the cover art.I think it should be added in the next update.

**Comment by OffifialMITX** [comment]
I'm not saying that wouldn't be a nice feature but how is this related to this issue?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by theScrabi** [comment]
@MehediBlaze please reed the contribution manual, and open up a separate Issue for your question.
