### ISSUE TITLE
Hide watched videos in what's new feed

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#5894]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

In the subscription feed/what's new, it would be handy to allow hiding of watched videos (and manually marking as watched) as well as having a max time threshold (eg. No videos older than 1 week) to keep the subscription feed clean.

#### Is your feature request related to a problem? Please describe it

Seeing videos you've already watched in a subscription feed makes the feed feel like there's more stuff than there is. It's like an itch you can't scratch.

#### How will you/everyone benefit from this feature?

This will allow users to reach the YouTube equivalent of Inbox zero for subscriptions.

**Comment by SameenAhnaf** [comment]
Please change your title into "Hide watched videos in what's new feed" . Your title is slightly misleading as it doesn't match your description. Also, please fill in the template properly. You are not supposed to remove it.

![IMG_20210324_125031](https://user-images.githubusercontent.com/79245641/112267379-91477480-8c9f-11eb-8f80-f218a4c13733.jpg)

**Comment by SameenAhnaf** [comment]
The preview should be alike this.

![IMG_20210324_132326](https://user-images.githubusercontent.com/79245641/112270698-37957900-8ca4-11eb-873a-4ad601cc7b66.jpg)

**Comment by phly95** [comment]
Sorry, I was posting from my phone and the cursor was misbehaving to the point where that was my only choice.

**Comment by mhmdanas** [comment]
Fixed by #3371.
