### ISSUE TITLE
"Trending" no longer loads

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#5900]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

No videos ever load (this just started happening yesterday)

### Expected behavior

Trending videos should load

### Device info

 - Android version/Custom ROM version: stock Android 8.0
 - Device model: Samsung Galaxy S7 Edge

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can confirm!

**Comment by TobiGr** [comment]
Already fixed. We will release a new version shortly

**Comment by mariojuggernaut22** [comment]
Thanks for reporting. I know it just not me
