### ISSUE TITLE
the "Share" icon should be available under every video and the t parameter should be optional

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#5903]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Not every video has a share option under it. Some you have to hit the down arrow in the upper right corner while playing the video. Please add the share button as a permanent fixture under every video and either put a setting in Settings to disable the t parameter (for time of the video) or have a dialog box appear asking to share "from the beginning" or "from this point" of the video.

#### How will you/everyone benefit from this feature?

This will make sharing easier and less work (won't have to manually delete the t= parameter or set it to 0.

**Comment by mhmdanas** [comment]
If you press on the video's title below the player, a share button will be shown, which also won't add a `t` argument to the URL.

**Comment by infinitewaveparticle** [comment]
Not all videos had that button even after clicking the title. That's why I made this request. Only *some* videos had the share button in that location. The issue seems to be fixed in the latest release. I'll let you know if I see a video without it.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mhmdanas** [comment]
Sorry, I didn't notice that part of the issue when I made that comment.
