### ISSUE TITLE
Subtitle support

### ISSUE THREAD

**Issue by dimqua** [TeamNewPipe/NewPipe#592]
Please add support for subtitles (closed captions).

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
I think since we have exoplayer this might actually work.

**Comment by tonakriz** [comment]
This is duplocate of https://github.com/TeamNewPipe/NewPipe/issues/55 . I would preffer to continue with discussion on this topin in the older issue.
