### ISSUE TITLE
Loading circle and bar both appear 

### ISSUE THREAD

**Issue by DaringRaspberry** [TeamNewPipe/NewPipe#5923]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'what's new'
2. Press on 'Feed last updated:'

### Actual behaviour

There is the loading circle and the loading bar.

### Expected behavior

Only the loading bar to show 

### Screenshots/Screen recordings

![Screenshot_20210327-123742](https://user-images.githubusercontent.com/78709186/112721308-17132c00-8efb-11eb-916d-da4a40c58eab.png)

### Device info

 - Android version/Custom ROM version:Android 10
 - Device model:Motorola moto g7 power

**Comment by avently** [comment]
Loading circle means that you can't refresh again until the refreshing process is done. So it's useful

**Comment by Stypox** [comment]
Yes, this is expected. It may look strange, but the circle actually tells you that that's a SwipeRefreshLayout and that you cannot refresh again, and the bar tells you the process.
