### ISSUE TITLE
[SonarQube] Follow up to Sonar analyzing old branches

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#5926]
This addresses #5906

I looked into it and it looks like the analyisis is getting resubmitted after a PR is merged. So those are not old PR, but a duplicate.
Take: https://sonarcloud.io/dashboard?id=TeamNewPipe_NewPipe&pullRequest=215
If you take a look at the new lines, meaning what changed, you can see that it were changes from the 24. March: https://sonarcloud.io/code?id=TeamNewPipe_NewPipe&pullRequest=215&selected=TeamNewPipe_NewPipe%3Asrc%2Fmain%2Fjava%2Forg%2Fschabi%2Fnewpipe%2Futil%2FThemeHelper.java&line=172

I have no idea why this occurs and how to solve it. But i also don't see a problem, since the branches will get deleted after 30 days of inactivity.

So I would say we can enable sonar again.

@TobiGr

**Comment by XiangRongLin** [comment]
@TobiGr So yes? 🙏

**Comment by litetex** [comment]
Can we re-enable SonarQube then?

Would certainly help finding issue like this one (although it's in the Extractor it can also happen here): 
https://github.com/TeamNewPipe/NewPipeExtractor/pull/709#discussion_r697804942

**Comment by XiangRongLin** [comment]
Obligatory quaterly ping to @TobiGr to active it or give me rights to do it.

**Comment by TobiGr** [comment]
Sorry, @xiangronglin. You should be able to edit the settings now

**Comment by XiangRongLin** [comment]
@TobiGr I don't have access to activate the sonarcloud integration under: https://github.com/TeamNewPipe/NewPipe/settings/installations

Can you do it?

**Comment by TobiGr** [comment]
Done
