### ISSUE TITLE
Error screen keeps on appearing

### ISSUE THREAD

**Issue by Allen-B1** [TeamNewPipe/NewPipe#593]
Every time I try to play videos that I downloaded an "Error" screen keeps on appearing and it's really annoying

**Comment by mauriciocolli** [comment]
Can you explain/detail a little more your problem? A screenshot would be very helpful.

**Comment by Allen-B1** [comment]
I download a video. I go on a car (that doesn't have internet). I view the video. After a few minutes into the video, an error screen pops up saying "Can't load image."

**Comment by theScrabi** [comment]
That sounds like an error of the player you use. Try using another videoplayer.

**Comment by Allen-B1** [comment]
Oh, ok

**Comment by mauriciocolli** [comment]
@Allen-B1 are you saying that you are trying to play in the already open video page (inside Newpipe)? 

If that's the case, you have to understand that NewPipe doesn't work like that (although it'd be a cool idea), it does cache some things which explain how you could go to that point.

And as you can see in the class [ImageErrorLoadingListener](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/ImageErrorLoadingListener.java), when it can't load a image (offline for example), the application crashes and open the report activity (which is **NOT** a good idea), instead, it should show a error/default image.

Is that what the error looks like?
[<img src="https://user-images.githubusercontent.com/13389907/27452534-3e256772-5769-11e7-9db8-341cb9afa3c1.png" width=220>](https://user-images.githubusercontent.com/13389907/27452534-3e256772-5769-11e7-9db8-341cb9afa3c1.png)

**Comment by Allen-B1** [comment]
Yes something like that
