### ISSUE TITLE
Phone keeps shotdowning

### ISSUE THREAD

**Issue by jithinjames916** [TeamNewPipe/NewPipe#5931]
When I open the app and play a vedio, nothing goes wrong but if I choose another vedio from suggested list, phone poweroff...
It's not in legacy version or with any other app...
I love ur app... & Use it a load..
Hope u find about this and fix it soon

**Comment by TiA4f8R** [comment]
We cannot help you with the information the provide. What's your app version, what's your OS/ROM? Please edit your issue and fill the template (we know that some GitHub clients doesn't display the template when creating an issue) properly.
