### ISSUE TITLE
Make playlist randomly shuffleable.

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#5937]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

**This ties into issue #2414 and #5498** Can we have an option to shuffle videos in playlists?

**Comment by mhmdanas** [comment]
What would be the use case here other than shuffling the order in which the playlist's items play (which you can already do by shuffling the queue)?

**Comment by Hogerys** [comment]
@mhmdanas im unaware of an option like that. Where can i find it?

**Comment by sp33dsk8** [comment]
Once playlist/queue is playing, in player view next to 1x playback speed button click the list button in top right.  Shuffle is in the queue list next to repeat in top left.
