### ISSUE TITLE
Strange behaviour downloads

### ISSUE THREAD

**Issue by turboteckel** [TeamNewPipe/NewPipe#594]
In the latest version (0.9.8) downloads seem to be behaving strangely. Downloads don't automatically start and starting a download makes my phone incredibly slow and/or unresponsive (Galaxy S3 Android 4.3)

**Comment by turboteckel** [comment]
After leaving the screen up for a few minutes I got an error the other day and I just send them per email. Is that still valid or should I post the errors here?

**Comment by theScrabi** [comment]
No, if you send it via mail that should do it.

**Comment by turboteckel** [comment]
This issue is still there in 0.9.9

**Comment by TheAssassin** [comment]
Please be patient until someone gets to have a look. We get so many e-mails a day, and although our analysis tool does a good job combining equivalent bug reports, a developer has to have a look and check for relevant issues. This is a project of volunteers with jobs and a real life, you cannot expect problems to be fixed instantly. It all takes time, and we don't have that much of it.

Unless someone announces an ETA, you can either be patient or step in and send a PR that fixes the problem.

**Comment by turboteckel** [comment]
Wasn't meant like that. Just reporting that it still existed in an update in case someone worked on it. Just trying to be helpful.

**Comment by TheAssassin** [comment]
Okay, in that case, thanks for keeping the  issue up to date.

**Comment by FaizKhan5** [comment]
Close this issue.

**Comment by Stypox** [comment]
Fixed in #2149
