### ISSUE TITLE
Distracting buttons when commemts are deactivated

### ISSUE THREAD

**Issue by defini-tiv** [TeamNewPipe/NewPipe#5943]
The ”Report“ and ”Retry“ buttons may be useful when there is an extractor error. But many of the videos I watch the comments are deactivated intentionally. In this case the buttons are distracting and suggesting something went wrong.

A bad ux, especially for new or not technical users.

Please make the buttons gray. At least as long as there is no differentiation between deactivated comments and actual errors.

**Comment by mhmdanas** [comment]
To be clear, there IS an extractor error. This is a bug in the extractor that was introduced recently: https://github.com/TeamNewPipe/NewPipeExtractor/issues/577.
