### ISSUE TITLE
Crash at very early startup, looks like unable to get cache dir

### ISSUE THREAD

**Issue by crass** [TeamNewPipe/NewPipe#5947]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Install NewPipe from apk in Github releases
2. Start NewPipe

### Actual behaviour
When starting the app, the phone appears to freeze. No UI elements are drawn. Swiping to change apps works and the app can then be killed.

### Expected behavior
I'd like for NewPipe to start and be able to be used normally.

### Logs
NewPipe does not initialize enough to get to a crash report dialog.
Adb logcat: [newpipe-crash.log](https://github.com/TeamNewPipe/NewPipe/files/6218314/newpipe-crash.log)

### Device info

 - Android version/Custom ROM version: GrapheneOS 3/21 Patch update
 - Device model: Google Pixel 4a

**Comment by crass** [comment]
I believe this happens as a result of the restore process and not the fault of NewPipe, so closing.

**Comment by TobiGr** [comment]
Did you report that crash via IRC, too? That user also had GrapheneOS on their phone. I asked them for more details, but they were gone at the time I sent the message.

**Comment by crass** [comment]
Yep, that was me. Sorry about the noise.
