### ISSUE TITLE
Sponsor block

### ISSUE THREAD

**Issue by NSTAdventure** [TeamNewPipe/NewPipe#5948]
### Checklist

- [√] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ √] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [√ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
<!-- A clear and concise description of what you wish should happen.

Actually This Idea Come From Youtube Vanced
So I Want You To Add Sponsor Block

You can skip any promotion (paid or by self)
You can skip any intro and outro video

Optionally, also describe alternatives you've considered.

Nope no alternative

#### Is your feature request related to a problem? Please describe it
<!-- A clear and concise description of what the problem is. Maybe the developers and the community could brainstorm and come up with a better solution to your problem. If they exist, link to related Issues and/or PRs for developers to keep track easier.
I really hate that god damn Sponsor 😤

#### Additional context
<!-- Add any other context, like screenshots, about the feature request here.
Hey There Is No Cat You Clown

#### How will you/everyone benefit from this feature?
Skip useless Video Part:
-Intro And Outro 
-Promote (Self Or Paid)
-Non Music Part (Blah Idk How I Can Describe This)

More Info:
https://sponsor.ajay.app/

JakubWeg Is Developer Of SponsorBlock API FrameWork

**Comment by mhmdanas** [comment]
See #2554. Also, please follow the template properly.

**Comment by NSTAdventure** [comment]
What? Did i do something wrong on template

**Comment by mhmdanas** [comment]
You did check the items on the checklist, but you also have to describe the feature in the section below the checklist.

**Comment by SameenAhnaf** [comment]
You should type 'x' (exe) to check the checkbox. If you want sponsorblock, you can try this fork by polymorphicshade https://github.com/polymorphicshade/NewPipe/releases
