### ISSUE TITLE
Video without sound

### ISSUE THREAD

**Issue by C-500** [TeamNewPipe/NewPipe#595]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

"Autoplay when called from another app" option make videos start without sound. Tested on two different devices (kitkat, nougat). v0.9.8 from f-droid.

**Comment by theScrabi** [comment]
Try rebooting your phone.

**Comment by C-500** [comment]
yes, it helped me with my smartphone (thank you!), but it's still happens everytime on my TV box since I updated newpipe (0.9.3 -> 0.9.8). I turn on TV box, use it something about hour and turn it off, it doesn't work all time like phones. I mean... it doesn't need to be rebooted because it just turned on few minutes ago...

**Comment by mauriciocolli** [comment]
Are you sure the media volume is not zero _before_ you try to open? Because I don't see why this would happen, NewPipe don't set any volume when it start playing.

If it isn't, can you make a more detailed step-by-step to this bug?

**Comment by C-500** [comment]
it's not about media volume I guess, it's exactly video without sound. 

how it happens:
1. starting newpipe from another app;
2. it ask me to choose a player;
3. I choose, video is starting (usually at this time loading takes a long time);
4. video opens without sound.

if I go back (when video already started without sound or when it just asking to choose a player) and press 'play' again in newpipe's interface (that still opened) - video has a sound.

I made short video, please, take a look.

https://cloud.mail.ru/public/5Qro/MbWbhFunk

this happens with every single video, btw.

**Comment by theScrabi** [comment]
Thats odd, but it's definitely a problem of the player. Have you tried using another, or the NewPipe internal player?

**Comment by mauriciocolli** [comment]
Okay, I know what's happening, due to a bug (recently discovered) in the autoplay, it is choosing some resolution without audio and when you go back, then NewPipe choose the correct resolution.

**Comment by C-500** [comment]
it happened again on my smartphone today (yesterday I rebooted it). and another strange thing - if I go back from video without sound and go back again to leave newpipe's video page and come back to the browser (on smartphone it's UC browser) with opened YouTube page and than I share video to newpipe again - newpipe is opening with that video page but it doesn't ask me to choose player anymore (autoplay doesn't work?). than I close it in multitasking page, go to the browser, share video to newpipe, it ask me to choose player, and... I see video without sound again... I tried at least MX player and VLC.

Yes! information about video in MX shows, first start is 1920x1080 and video stream only, second start - 1280x720 with two streams - video and audio. resolution in newpipe's setting - 720p.

**Comment by mauriciocolli** [comment]
Yeah, I'm already aware of these bugs (wrong resolution and sometimes autoplay doesn't work), I'm pretty sure that it'll be fixed in the next release.

**Comment by C-500** [comment]
wheee!:) thank you guys!

**Comment by mauriciocolli** [comment]
That should be fixed now, if you wanna test it just to make sure, here it is: [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/1107345/app-debug.apk.zip)
