### ISSUE TITLE
Add a "Temporary close" button on popup video interface

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5952]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

A "Temporary close" button could be added in orange doodled space. This button will allow the user to pause the video and close the popup. But it will not clear the queue or hide media player notification bar. If video is resumed from notification, then the video popup will be resumed again.
![IMG_20210401_224133](https://user-images.githubusercontent.com/79245641/113326475-880f7500-933b-11eb-910c-927e9cfa92e6.jpg)

Popup should not be absolutely hidden if paused as we may need to take screenshots from the video or take notes while watching the video. So, adding a separate button for this action will be more appreciated.

#### How will you/everyone benefit from this feature?

It will help us hide the popup temporarily and resume the video a few moments later. Suppose, you received an important message and you need concrete focus. In such case, you won't want to clear the queue. Rather, you will prefer resuming it later. I can resize the video. But I will have to resize and change the position again after I am done which is a little hassle. Adding a separate button could let us avoid the hassle of resizing and popup position.

**Comment by chrstfer** [comment]
Honestly we need a total queue rework. I keep meaning to write up a compilation of these suggestions and my own thoughts, but always remember just minutes before I'm headed to bed.

If we had a unified queue in the background that would come with the ability to easily background the app without losing the queue by switching to the background playback mode and leaving it paused (and a unified queue that persists when you switch between playback modes would solve a ton of other issues too).

I dont think we need a new UI element to temporarily minimize the app*. The app should just keep your queue by default when you close the popup, and either pause the video or background play it depending on a setting. Queue clearing should be reserved to a manual action or when the app resets (like a force-stop or something).


\* If a specific new UI element is critical, maybe it could use the bubbles feature from Android 11? I'm still not sure what exactly you need it to do that wouldn't happen normally (if we assumed the queue worked as described above). I think it would be pretty cool to have a bubble with the video+related videos just a tap away without leaving the game/app you're in.

**Comment by SameenAhnaf** [comment]
@chrstfer I was not talking about multiple queues. 

Suppose, I was scrolling Tweets but I need to read something important. What will I do? I will pause the video and prefer to keep it hidden for a few moments. It's not only about switching queues. I may need to multitask while using other apps.

How will I get back to the video? I can get back from media player notification bar.

**Comment by chrstfer** [comment]
@SameenAhnaf multiple queues just plays into what you're talking about. If we had a fully functional queue system you could dismiss the video popup and get it back at the same time in the video, preserving the queue.

**Comment by SameenAhnaf** [comment]
@chrstfer You may have a look at this. I suggested an idea on multiple queues https://github.com/TeamNewPipe/NewPipe/issues/5940#issuecomment-812322894

**Comment by opusforlife2** [comment]
xD
