### ISSUE TITLE
Add songs to a bookmarked playlist 

### ISSUE THREAD

**Issue by Nurietzsche** [TeamNewPipe/NewPipe#5958]
I already imported some of my playlists from YouTube Music and bookmarked them in NewPipe (since it's the only way I know of saving that playlist in the app). I can play the songs of these playlists perfectly but, when it comes to  adding new songs, I can't find the way. I see the "add song to playlist" button but it will only show me playlists that I have created in NewPipe (which are empty because I don't want to start new playlists from scratch). I just wanted to know if that's an error (then I'd love the help to solve it) or just the functioning of the apk. 

Thanks a lot

**Comment by mhmdanas** [comment]
Bookmarked playlists are not stored locally on NewPipe, so you can't modify them. That is, bookmarked playlists are parsed from services (e.g. YouTube or SoundCloud), unlike local playlists which are stored, well, locally. However, there is an open issue to allow "importing" bookmarked playlists so you can modify them locally: #5646.

**Comment by Nurietzsche** [comment]
Could somebody explain me how do I import my YTplaylists? I was looking forward to import all YouTube data from Google Takeout but I didn't find the way. When I'm trying to import some files from takeout, NewPipe shows a warning saying that my zip file is not valid.

There's little information about NewPipe's settings

**Comment by mhmdanas** [comment]
You can't; that feature still isn't added. And when you import from Google Takeout, you don't import the ZIP file; you extract `subscriptions.json` and import that.
