### ISSUE TITLE
Can't subscribe to channels without videos

### ISSUE THREAD

**Issue by cybersphinx** [TeamNewPipe/NewPipe#5959]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Search Youtube for "subscribers without videos", tap on a channel that doesn't show any videos. 

The search term is just to find empty channels, I don't want to subscribe to those, but sometimes people announce new channels that don't have videos yet and it would be nice to have them in Newpipe so they show up in the new video feed once videos get uploaded.

### Actual behaviour

The channel header with subscribe button shows up for a moment, then gets replaced by a "No videos" message.

### Expected behavior

Channel header stays, the "No videos" message only occupies the space where the videos would go, so the subscribe button is always visible.

There's also a loading circle animation when looking for videos on a channel that seems to do the same and could also just be below the header instead of replacing it to keep the UI less busy.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by sauravrao637** [comment]
I would love to try fixing this bug :)

**Comment by HTSamurai** [comment]
Why would you need to sub to a channel without videos
