### ISSUE TITLE
App Crashes when no videos in last played and user interacts with playlistController

### ISSUE THREAD

**Issue by sauravrao637** [TeamNewPipe/NewPipe#5968]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1.Open the app
2. Watch any video/s
3. Click on 'History' in navigation pane
4.Clear watch history by clicking on 3 dots in top right corner 
5.PlaylistController is still visible!! interact with it to see the magic (click on "Play All" button)  

### Actual behaviour

App crashed (TT)

### Expected behavior

Anything but crash.

### Screenshots/Screen recordings

![photo_2021-03-31_16-59-44](https://user-images.githubusercontent.com/56369484/113137759-929a1380-9242-11eb-9c18-df216699a92e.jpg)

### Device info

 - Android version/Custom ROM version: LineageOS
 - Device model: Redmi Note 5

**Comment by wangear** [comment]
Hello! I'd like to work on this enhancement. Can i assigned to this issue? :)

**Comment by sauravrao637** [comment]
> Hello! I'd like to work on this enhancement. Can i assigned to this issue? :)

I've been working on this and fixed it in [this](https://github.com/TeamNewPipe/NewPipe/pull/5971) PullRequest 
Any suggestions or improvements are most welcome .   :)
