### ISSUE TITLE
Show mini player (even on main player, full screen is the exception)

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5972]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Minimized player could be always shown for easy management. Only, full screen video is the exception.

Mini player could be added in main player (above bottom row is more appreciated, this will let positions of bottom row buttons consistent) to show playback progress could be shown as a red line above the title bar. Title in mini player could be like "Marvel Studios' Black Widow । Special Look (0:38/1:31)" to show playback time.

Users in #5785 report small close button makes it easy to close the video. That's why, only seperate `Pause` button should be included. Users can swipe down to close the player. Following gestures can be included.
1. Swipe up: Manage the queue (Queue should be managed even if single video is queued as many users may still prefer buttons).
2. Single tap on thumbnail: Open the video info.
3. Single tap on title bar: Queue selection menu if multiple queues are implemented.
4. Double tap on thumbnail: Previous.
5. Double tap on title bar: Next.
6. Long press on thumbnail: Rewind.
7. Long press on title bar: Fast forward.
8. Swipe left to right: Seek position (Playback progress should be shown on the top of title bar. Time could only be shown in the thumbnail while seeking position)
9. Pause: On the right side of title bar.
10. Double tap on pause: Shuffle (Toast `Queue shuffled` should be shown).
11. Long press on pause: First long press should repeat only the current video (Toast `Current media on repeat`). Second long press should repeat should repeat the whole queue (Toast `Queue on repeat`). Third long press should cancel repeat (Toast `Nothing on repeat`).
12. Swipe down: Close both the player and queue

"Smart `Next` and `Previous` button for minimized player" in settings could be added as no more gesture can be assigned for that option.

#### How will you/everyone benefit from this feature?

It will be similar with most music players. Especially, helpful for music lovers. Users will be able to have features on their fingertips. Easy playback management with one hand will be a breeze. No need to pull down notification panel.

**Comment by SameenAhnaf** [comment]
@TiA4f8R Is it OK now?

**Comment by SameenAhnaf** [comment]
@TiA4f8R Hello? Is it OK? Please let me know.

**Comment by TiA4f8R** [comment]
Now yes
