### ISSUE TITLE
[Request] Display and Launch Update In App

### ISSUE THREAD

**Issue by zero77** [TeamNewPipe/NewPipe#5978]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Could you please display an update banner with in NewPipe with a download option to download.
Then launch the installer from within the app and let the user finish the install themselves.

#### Additional context

At the moment an update notification is displayed in the android notification menu which can be missed.
Also, this requires opening a browser and manually downloading and then finding and launching the apk.

#### How will you/everyone benefit from this feature?

This will hopefully simplify and speed up the update process for users and make them harder to miss.

**Comment by TiA4f8R** [comment]
We are against this for privacy reasons, see #3141. Closing.

**Comment by zero77** [comment]
I don’t think that is what I am after, I was asking for NewPipe download and launch the apk.
Then, leave users on the start of the android install wizard so users can complete the rest of the process themselves.

**Comment by TiA4f8R** [comment]
Personally, I was thinking of showing the changelog and three buttons for download the update, when a user click on the notification: one which redirects the user to the GitHub APK or page of the release, one which redirects you to the APK URL in our F-Droid repository and one to open the app details in F-Droid.

We will not provide an internal updater, so can you edit your issue and remove the part to open the downloaded APK (it's a part of an internal updater)? Thanks!
I will reopen the issue when you removed this part.
