### ISSUE TITLE
Support !/"Bang" search

### ISSUE THREAD

**Issue by uncertainquark** [TeamNewPipe/NewPipe#598]
So if you use a search app on Android, like DuckDuckGo search or Firefox search widget, and perform a !bang search, this is what happens:

![screenshot_20170628-120824](https://user-images.githubusercontent.com/22585732/27623699-27ac0d4e-5bcd-11e7-9ee8-096b11ab09bb.png)

NewPipe is not listed to be able to directly direct the search there.

**Comment by theScrabi** [comment]
Ow right.

**Comment by TheAssassin** [comment]
Cool idea. PRs welcome.

**Comment by litetex** [comment]
Updated the title as it's completely wrong (has nothing to do with android).

I checked it with the latest Firefox versions and DuckDuckGo browser on Android however these do not work.

Also it looks like the search is managed by the app-provider: https://duckduckgo.com/bang?
So I don't think we can actually do anything on app-side.

I think we should close the issue when there is no further activity.
