### ISSUE TITLE
No longer installing in Android 4.4.2 

### ISSUE THREAD

**Issue by josuesoto1** [TeamNewPipe/NewPipe#5986]
Hi. This is a great project. I use it to make my old smart tv have access to YouTube. However last update cannot be installed on Android 4.4.2. An error occurs while installing. Application not installed. Either updating previous version neither new installation. Is there anything I can try to keep having new releases working?

**Comment by sauravrao637** [comment]
Yes you are right, it's because minimum sdk version is Android 4.4 (API level 19). So the only option is to use previous version of the app :)

**Comment by TobiGr** [comment]
Use the legacy Version,
https://github.com/TeamNewPipe/NewPipe-legacy

**Comment by ShareASmile** [comment]
@josuesoto1 You can also try NewPipe legacy preunified (v19 UI) version having latest extractor from
https://github.com/XiangRongLin/NewPipe-preuinified/releases
and download legacy version apk.
