### ISSUE TITLE
Copyrighted videos do not play or download

### ISSUE THREAD

**Issue by Redst0neFlux** [TeamNewPipe/NewPipe#5990]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to any video that is copyrighed
2. Press on the play button or attempt to download the video

### Actual behaviour

playing: The video attempts to load indefinitely 
downloading: Download failed notification after a few minutes

### Expected behavior

The video plays or starts downloading

### Screenshots/Screen recordings

![Screenshot_20210402-131437_NewPipe](https://user-images.githubusercontent.com/69603438/113414738-9b5f2680-93b5-11eb-9abf-060e9d64629d.jpg)

### Device info

 - Android version/Custom ROM version: 8.0.0
 - Device model: SM-A320FL

**Comment by TobiGr** [comment]
Please give us the link to that video

**Comment by Redst0neFlux** [comment]
https://www.youtube.com/watch?v=AGeLUXNl--0
the bug happened with any licenced video (videos with this text block in description: 
![image](https://user-images.githubusercontent.com/69603438/113418287-14ae4780-93bd-11eb-80a3-54388ae2fd08.png)

**Comment by hvjufg** [comment]
dupe of #5769

**Comment by Redst0neFlux** [comment]
the videos work again now

**Comment by hvjufg** [comment]
> the videos work again now

lmao, it seems that the nsa was toying with your network queries
