### ISSUE TITLE
[feature request] search history

### ISSUE THREAD

**Issue by daniell1** [TeamNewPipe/NewPipe#6]
A search history would be sweet as well :smiley:

**Comment by theScrabi** [comment]
I could provide an offline search history.

**Comment by epitron** [comment]
A viewing history would be excellent too!

**Comment by JasperWeiss** [comment]
Actually it should be optional. I mean at least let people opt-out for storing anything since I personally would rather not have search and view history and I'm assuming more people do

**Comment by epitron** [comment]
Search history doesn't matter to me, but view history would be very helpful. I like to watch lectures, and I rarely finish them in one sitting. I usually have to search for them again, and then load them again, and then seek to where I left off. A history would remove at least one of those steps. :)

**Comment by theScrabi** [comment]
Yes, view history would be nice :)

**Comment by ericfont** [comment]
I would definite like a view history and/or search history.  I think by default should store history, but providr option to turn off.  People who are concerned about their history privacy should be smart enough to know that it is stored locally and would likely already be taking adequate measures to lock their phone down.

**Comment by Nutomic** [comment]
Looks like this was already implemented in #626, so the issue should be closed.
