### ISSUE TITLE
Adding Independent Streaming Services

### ISSUE THREAD

**Issue by Callahan092** [TeamNewPipe/NewPipe#6005]
Hello,

If it's possible, please add independent streaming services like Bitchute.com, banned.video, londonreal.tv, odysee.com into your app.

Thanks.

**Comment by sauravrao637** [comment]
Hi thanks for raising an issue !
Suggestions are always welcome but please use the specified issue template otherwise your efforts may get ignored by the core team.

**Comment by mhmdanas** [comment]
As @sauravrao637 says, please use the template when opening an issue. When you want to request new services, please only request one per issue, and those issues should be opened in https://github.com/TeamNewPipe/NewPipeExtractor, not here. I don't know about the others, but Bitchute was suggested and the team decided against adding it. See TeamNewPipe/NewPipeExtractor#320.
