### ISSUE TITLE
Add SponsorBlock implementation

### ISSUE THREAD

**Issue by Trantorien** [TeamNewPipe/NewPipe#6007]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
[SponsorBlock](https://sponsor.ajay.app/) is a browser extension that allows users to indicate a part of the video containing a commercial message. This extension causes that portion of the video to be skipped to subsequent users, saving them brain time for advertisers. 

This extension was somehow ported to the mpv player and I think we should do the same in newpipe. I think we should add an option in the settings to enable SponsorBlock, but also something that counts the time we missed watching sponsors (like the firefox extension does). 

#### How will you/everyone benefit from this feature?
Newpipe already allows you to avoid advertising on YouTube, but does not allow you to avoid commercial messages. If you look at the amount of time you can spend listening to commercial messages, you might be surprised. These messages can be due to quite aggressive commercial campaigns, and for which we hear the same advertisement in every video.

- Blocking them allows us to realize how much time we waste with these messages,
- Blocking them, avoids us to be manipulated by too much advertising.
- There may be other benefits I haven't thought of

**Comment by jimman2003** [comment]
see https://github.com/polymorphicshade/NewPipe#newpipe-x-sponsorblock

**Comment by SameenAhnaf** [comment]
Sorry, devs don't want it. See: https://github.com/TeamNewPipe/NewPipe/pull/3205

You can check out this link though
>See https://github.com/polymorphicshade/NewPipe#newpipe-x-sponsorblock
