### ISSUE TITLE
Please include block screenshot/video inside the app

### ISSUE THREAD

**Issue by razercrypto** [TeamNewPipe/NewPipe#6014]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Please include block screenshot and video inside newpipe app

#### How will you/everyone benefit from this feature?
It will enhance privacy

**Comment by SameenAhnaf** [comment]
Personally, I am in favour of blocking screenshot permanently and include "Screenshot" button only from main video interface. This will improve our privacy immensely and only manual "Screenshots" will be available. More details #5674.

**Comment by mhmdanas** [comment]
@SameenAhnaf I don't think that's a good idea. People like to take screenshots in all sorts places in the app, and taking that option away from them without a way to disable it is not a good idea.

**Comment by arshiamoghimi** [comment]
I'm working on this issue.

**Comment by XiangRongLin** [comment]
In what way does this improve privacy? Only the user themself can make screenshots/video meaning it's an active decision.

The content displayed is also completly publicly available from youtube. Not like some chat app.

**Comment by Stypox** [comment]
Yeah, I wouldn't add this feature, even if it's under a switch

**Comment by XiangRongLin** [comment]
If no counterpoints are going to be made by tomorrow, then I'm going to close the issue and the corresponding PR
@razercrypto @arshiamoghimi

**Comment by razercrypto** [comment]
It is possible that device manufacturer can see what you are doing. Privacy centered apps have this screenshot/video blocking option including tor browser.

**Comment by mhmdanas** [comment]
I don't think merely blocking screenshots is going to stop a malicious manufacturer from seeing what you are doing (i.e. it gives a false sense of security).

**Comment by razercrypto** [comment]
Ok. Then iam going to close this issue. Thank you.
