### ISSUE TITLE
Some videos fail to play (in both foreground/background)

### ISSUE THREAD

**Issue by campbellkerr** [TeamNewPipe/NewPipe#6017]
### Checklist

- [x] I am using the latest version -  v0.21.0  
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to https://www.youtube.com/watch?v=rc4PHKmjnMU (Search for Harold Budd - Jane 8) - for example
2. Tap the search result/long tap (for background play)
3. Try "Play" or "Play in background"

### Actual behaviour
The video/audio never loads/starts

### Expected behavior
Video should start playing, or be able to be played in the background (audio)
OR
an error/message

If I share the video to my browser (Firefox Android), it plays fine.

### Screenshots/Screen recordings
(screen recording available on request)

### Device info

 - Android version/Custom ROM version: Android v9 (stock)
 - Device model: Huawei P10

**Comment by sauravrao637** [comment]
Hi! 
It's working fine on my device (custom LineageOS ,android 10) .Is there any other video ,  I can reproduce the bug with?
Also will be helpful if u share the screen recording of the same.

**Comment by alex-dp** [comment]
I have had the same issue on and off for many months. very often yt blocks (censors) traffic from this app

**Comment by TiA4f8R** [comment]
@campbellkerr @alex-dp First of all, are you using a VPN? If yes, Google can block the IP used by this VPN.

Can you enable the option to play with an external player and see if streams are playable in VLC or Total Commander for example? Can you also use [Intent Intercept](https://f-droid.org/packages/de.k3b.android.intentintercept/) to copy the url of the stream and open it in a browser to see if you can play streams generated by NewPipe? I think the googlevideo servers returns 403 (forbidden) to your device and the IP you are using.

@campbellkerr, like @sauravrao637 said, a screencast can be helpful to us. Can you please share one? Thank you in advance!

**Comment by campbellkerr** [comment]
@TiA4f8R Nope, not using any VPN. 

Good news - it's working today 😃 (I can't reproduce the issue). I also tried with the new NewPipe version and all good. If it happens again I'll record it and try VLC etc and let you know. Cheers

**Comment by TiA4f8R** [comment]
I close this issue until you can reproduce it again. Please let me know if you can reproduce it again and I will reopen this issue in this case.
