### ISSUE TITLE
Downloads do not finish

### ISSUE THREAD

**Issue by lowgan123** [TeamNewPipe/NewPipe#602]
I was downloading a video, and it downloaded like normal until it reached 100 percent, and then the software completely froze up and I had to exit out and restart the app. When I did this, it showed a white screen, and then informed me that the UI had crashed.  When I checked on the downloads, it had stopped and gave me the option to "start" which would start the loop all over again, or to "delete" which would get rid of the download and the app would function normally again. Is there any fix to this?

**Comment by cwgt** [comment]
I am also getting some problem with downloader.

after reaching 100% download, the downloading speed decrease to some-hundreds-bits/second. it takes some seconds to minutes (depending on length of video)  to complete download from 100%.

if I try to download several videos at a time, downloading will pause/downloading at kilobytes speed/removing one item will cause short hang. (may be limiting simultaneous download will fix it)

I find the downloader of `YMusic` (not open source) is less buggy. even I had to use it to download some drama.

**Comment by theScrabi** [comment]
I was not yet able to test this.

**Comment by abhayjaiswal** [comment]
Why you close this bugs so it is actual user issue .   
During download large file progress show 100% but file downloading running in background. #731

**Comment by yesokcool** [comment]
I just started using NewPipe, but seeing this and the fact that it's still a bug after 3 months is kind of disappointing. It is a pretty big issue that I ran into within the first 5 minutes of using the app.

**Comment by TobiGr** [comment]
The download post-processing received a major update with #1759. This bug should be fixed with NewPipe 0.15.0 which has not been released yet.
