### ISSUE TITLE
add „pre-queue“ option

### ISSUE THREAD

**Issue by defini-tiv** [TeamNewPipe/NewPipe#6026]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

A „pre-queue“ option would appear in the context-menu of a video only when there is a active stream already. Pressing it would play the video immediately and shift the media played before toching the button (and all enqueued) below it in the queue.

(Maybe it would be possible to remember the progress of the before consumed stream and skip there, after a video is finished?)
#### Is your feature request related to a problem? Please describe it

It is a easy and undistructive partial replacement for multiple queues.

#### How will you/everyone benefit from this feature?

It is for watching a video when you have listened to something else before and want to continue afterwards

**Comment by SameenAhnaf** [comment]
Do you want each player (background, main, popup) to remember videos seperately? You can consider using this fork.
https://github.com/XiangRongLin/NewPipe-preuinified/releases/

**Comment by defini-tiv** [comment]
@SameenAhnaf Thanks for the suggestion but i want to use the unified player. 
And i consider the „pre-queue“ option as function that allwos partially simmilar functionality as the fork to the unified player and something that everybody might agree on as a bridge funciton.(or forever if it prooves itself super useful)

**Comment by SameenAhnaf** [comment]
@defini-tiv Then, you may consider waiting. Multiple queues will have a comeback. https://github.com/TeamNewPipe/NewPipe/issues/5940

**Comment by MapleWheels** [comment]
> @SameenAhnaf Thanks for the suggestion but i want to use the unified player.
> And i consider the „pre-queue“ option as function that allwos partially simmilar functionality as the fork to the unified player and something that everybody might agree on as a bridge funciton.(or forever if it prooves itself super useful)

There's already a discussion concerning add multiple queues support in the new player. The thread has just stalled because everyone is busy irl and there's no man power to implement the feature at this point. New Pipe itself has 100s of active issue tickets.

**Comment by SameenAhnaf** [comment]
@defini-tiv I hope, you will be suited by #6872.
