### ISSUE TITLE
LBRY/Odysee Support request

### ISSUE THREAD

**Issue by supersalbai** [TeamNewPipe/NewPipe#6031]
Hi,
is it possible to get LBRY/Odysee support - just exactly like the YouTube surface.
I love to use LBRY and I am sure there are many others like me. So the update will connect the great NewPipe surface and the wonderful decentralised video platform LBRY.
Thank!

**Comment by ShareASmile** [comment]
See:
https://github.com/TeamNewPipe/NewPipeExtractor/issues/434

**Comment by PHLA7** [comment]
that is a really good idea. it would introduce LBRY for a lot of people and would help them a lot. I don't think we need the crypto thing in new pipe, only the player would be perfect.

**Comment by mhmdanas** [comment]
Service requests go to https://github.com/TeamNewPipe/NewPipeExtractor. This was already requested though as noted by @ShareASmile in TeamNewPipe/NewPipeExtractor#434.
