### ISSUE TITLE
Android TV (Xiaomi Mi Box S) - Audio distorsion while playing videos with 2140p WebM or 1440p WebM quality

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#6038]
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

- Play a video on NewPipe at Xiaomi Mi Box S with 2140p WebM or 1440p WebM quality

### Actual behaviour

- Audio distortion happens. No issues while playing on NewPipe client with 1080p or 720p quality.
- No issues while playing same videos on default Youtube client of Xiaomi Mi Box S TV Box with 2140p WebM or 1440p WebM quality. Audio streams smootly.

### Expected behavior

- Audio should stream smootly while playing on NewPipe client with 2140p WebM or 1440p WebM quality

### Screenshots/Screen recordings

- No screenshot

### Logs

- No logs

### Device info

TV: Philips 55PUS6501/12
Using HDMI 2.1 certified cable. My TV Philips 55PUS6501/12 and Xiaomi Mi Box S support HDMI 2.0
No issues while playing same videos on default Youtube client of Xiaomi Mi Box S with 2140p WebM or 1440p WebM quality. Audio streams smootly.

Android TV Box: Xiaomi Mi Box S
Android version: 9
Kernel: 4.9.113 - #1 Wed May 12 CST 2021
Build: PI.3595 release-keys
SPL: March 5 2021

**Comment by litetex** [comment]
I think we need more logs/screen recordings here...

Unfortunately the author has deleted his account so I don't think we will get this information.

Closing the issue for now. Can be reopened if someone has the same problem.

**Comment by casimoes03** [comment]
I would like to reopen these issue. I'm using newpipe version 0.23.0 and the problem still persists. Please could you show me how to post the logs here?
