### ISSUE TITLE
Store backup location

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#6039]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

NewPipe should store the backup location in a setting like all other apps do (and just like Newpipe does for downloads).

#### Is your feature request related to a problem? Please describe it

Currently, you have to navigate to the folder where you store your Newpipe backups each time you take a backup or restore one.

#### How will you/everyone benefit from this feature?

Saved time and effort for everyone.

**Comment by XiangRongLin** [comment]
If someone intends to works on this, they need to consider edge cases, where the store location does not exist anymore.

**Comment by SameenAhnaf** [comment]
Related: https://github.com/TeamNewPipe/NewPipe/issues/5780

**Comment by ATofighi** [comment]
Hi.
I'll work on it soon.

**Comment by SameenAhnaf** [comment]
@ATofighi If you don't mind, would you please work on https://github.com/TeamNewPipe/NewPipe/issues/5780 too? Thanks in advance.

**Comment by ATofighi** [comment]
@SameenAhnaf nice, I'll do a try for that issue too. Thanks.
