### ISSUE TITLE
Newpipe ignoring video quality setting when openet from other app

### ISSUE THREAD

**Issue by Rikests** [TeamNewPipe/NewPipe#604]
I have set the video quality to 360p, but when i try to open a video from different app, newpipe starts playing it in highest avaiable quality, you can see this in the video.
https://gfycat.com/AltruisticVengefulAdouri
Im using One plus X with lineage OS android 7.1.2

**Comment by mauriciocolli** [comment]
You are affected by the same bug as the #595 and I already fixed it, are you sure that you're using the latest version? (F-Droid don't have it yet)

It doesn't show in the video, but I'm pretty sure that it is the problem.

**Comment by Rikests** [comment]
Ok, this seems to be the case. Yes, i am getting this app from fdroid.

**Comment by mauriciocolli** [comment]
If you wanna test if the latest version works, you can found it in the [releases](https://github.com/TeamNewPipe/NewPipe/releases) page.
