### ISSUE TITLE
PiP player should able to adjust to the portrait mode video.

### ISSUE THREAD

**Issue by NanyangTaiji** [TeamNewPipe/NewPipe#6048]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by mhmdanas** [comment]
The title is not enough for us to properly understand your request. Please edit your issue to follow the template properly (i.e. fill the checkboxes and at least some of the sections).
