### ISSUE TITLE
Manual update check button in the Updates page of the app

### ISSUE THREAD

**Issue by illustribe** [TeamNewPipe/NewPipe#6049]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Hello, 
Just now I swiped away unpurposedly the new version update notification from my notifications screen, without clicking on it. So then I went to the settings/Update expecting to find a way to start the update from there, as it works when one taps in the prompt in notifications. But found there's no way to do it now -as far as I can tell- but either wait or go to github and download it and run the installation, which is more time consuming than when one clicks on the prompt.
So my suggestion is to add a button on Settings/Update to launch the update process right away (when there are updates available).

#### How will you/everyone benefit from this feature?

Just save time if ever happens that one swipes away the update prompt in notifications :)

**Comment by SameenAhnaf** [comment]
An option to make the notification permanent (until clicked) will be more useful, I guess.

**Comment by vhouriet** [comment]
I'd like to work on this issue if no one else is working on it.

@TiA4f8R How do I make the "Update" settings appear in the main settings ? Can I simply remove the code that checks for the Github APK in [MainSettingsFragment.java](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/settings/MainSettingsFragment.java) ?
