### ISSUE TITLE
Video not closing after I moved it down completely [Video Available]

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6054]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any video
2. Let it play for some time and try to xlose it
3. Check notifications and find out if it is actually closed

### Actual behaviour

Even though it was suppose to close it didn't

### Expected behavior

Close the video

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/74511929/114323832-c07b3400-9b2f-11eb-81bd-5a08f516da4d.mp4

### Device info

 - Android version/Custom ROM version: Android 7 Nougat
 - Device model: Samsung Galaxy Tab A

**Comment by Feuerswut** [comment]
No longer an issue. Close as Fixed
