### ISSUE TITLE
IP blocked by Youtube after upgrade to 0.21.1 ?

### ISSUE THREAD

**Issue by bitterbyter** [TeamNewPipe/NewPipe#6056]
_This may not be a bug._ 

I upgraded to 0.21.1 on a LineageOS device yesterday. Today, around 8:00 CET, Youtube (YT) started showing reCaptcha prompt on all devices on my network. Chromecast on the network would not play any video on YT. Trying to open YT videos on a browser gave me the reCaptcha prompt. 

Then I contacted my ISP and they managed to restart my router and assign a new IP address. YT started working fine on Chromecast and iPad (YT apps). Then I opened NewPipe on the LineageOS device and immediately got the reCaptcha again upon trying to open a video. Chromecast stopped playing YT videos almost at the same time! 

Is this a known issue? I have been a long time NewPipe user.  This is the first time I am getting into reCaptcha loops in the app.  Any help would be greatly appreciated.

**Comment by trinity-geology-unstable** [comment]
I am experiencing this issue also. When I select a video to watch I am given the option to solve a captcha, but after I do that I am returned to the same screen and asked to solve a captcha again. Repeat ad-infinitum.

I am also running a custom ROM and using a commercial VPN provider.

**Comment by TobiGr** [comment]
Are you located in the EU?

**Comment by trinity-geology-unstable** [comment]
Yes

**Comment by bitterbyter** [comment]
I am in the US and do not use a VPN.

**Comment by Symbian9** [comment]
> Are you located in the EU?

For curious reason switching *"Default content country"* from `United Kingdom` to `United States` fixes similar issue in my case.

**Comment by PulkitBhardwaj1** [comment]
Same issue
