### ISSUE TITLE
My phone keep shouting down on selecting a new vedio from recommended list

### ISSUE THREAD

**Issue by jithinjames916** [TeamNewPipe/NewPipe#6061]
when I update to the latest version, it installs fine on my phone but when I play a vedio and choose another from the recommended list, phone shut down..
It's a nightmare...
I test it in some other device which work fine. My phone is Nokia 3.2
Android 11
The version that worked without this issue is 0.20.11
Hope you fix the in update.
![Screenshot_20210413-090500~2](https://user-images.githubusercontent.com/56216946/114493355-0de2c880-9c38-11eb-8b53-ca67d095d821.png)

**Comment by mhmdanas** [comment]
I think this is a duplicate of #5961.
