### ISSUE TITLE
(Double of #3556)

 Can't add a Channel Group in Main Page Content

### ISSUE THREAD

**Issue by DaisyF8** [TeamNewPipe/NewPipe#6066]
### Checklist

- [x] I am using the latest version - 0.21.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go into Settings/Content/Content of Main Page
2. Click add to choose content for Tab

### Actual behaviour
You cant select a Channel Group

### Expected behavior
Add a channel group as a tab. I don't think I'm now asking for a new feature, this should be possible... maybe... ? :)

### Device info

Android version/Custom ROM version: Android 9 - Kernel version 4.9.125
Device model: Bravia_UR2_4K

**Comment by peat80** [comment]
Unnfortunately this is no bug but a missing feature. 😒
There exists an old pr that should implement this, but they never got merged. Hopefully this feature will be implemented in a future release soon. That would be awesome. 😎👍

Feed group main-page tab #3556

**Comment by peat80** [comment]
Feed group main-page tab #3556

**Comment by DaisyF8** [comment]
Thx for explaining :)
