### ISSUE TITLE
Endlessly "Recovering from player error" after pausing and resuming stream

### ISSUE THREAD

**Issue by boringhexi** [TeamNewPipe/NewPipe#6077]
### Checklist

- [x] I am using the latest version - 0.21.1 (also was able to reproduce in 0.21.2 RC1) 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Start playing a stream, e.g. https://m.youtube.com/watch?v=DWcJFNfaw9c
2. Pause the stream for a while, 90 seconds seems to work.
3. Resume the stream. Wait for minute or so, and playback will attempt to catch up to the stream, at which point the problem occurs. (Or instead of waiting a minute, you may bring up the app switcher and switch back to NewPipe.)

### Actual behaviour

The stream stops playing, and it repeatedly shows "Recovering from player error". To make it stop, I have to close the video and open it again (just closing the play queue and resuming the video is not enough)

### Expected behavior

Playback should catch up to the stream, which would result in a brief pause but not stop the stream entirely.

### Screenshots/Screen recordings

![Screenshot_20210414-093141](https://user-images.githubusercontent.com/36807140/114719222-dbeb6800-9d04-11eb-982c-0c163ec08cc5.png)

### Logs

None, app does not crash.

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Moto G Power (XT2041DL)

**Comment by AudricV** [comment]
Is it still an issue on the 0.26.1 version?
