### ISSUE TITLE
No audio in downloaded videos and screen freezes in video plays

### ISSUE THREAD

**Issue by FitnessRegiment** [TeamNewPipe/NewPipe#608]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Device: Samsung S7
F-Droid/Newpipe fully updated.

When watching videos, video freezes after a few seconds, audio continues.

When downloading videos, there is no option to have the audio as well? There is just a no-audio sign on the left of it, why can't I download audio?

**Comment by mauriciocolli** [comment]
In what resolution and framerate this happens?

Regarding the no-audio, it's the way that YouTube works, it delivers the video and audio in different streams (happens more with WebM), the only thing that we could do is merging them, but that would require some libraries that I'm not sure we're going to include (I'm studying that option though).

**Comment by FitnessRegiment** [comment]
4k resolution 30fps every time.

**Comment by mauriciocolli** [comment]
I think that it's using WebM format (for that resolution probably the only available), the bitrate of these videos is just huge and it's not designed for any mobile device to handle it (similar to the issue #597).

However, from what I can see (http://wiki.webmproject.org/hardware/socs) your device is quite powerful and it does have hardware decoding for VP9, so I don't know exactly what it's happening, it seems like a bug in your device or in ExoPlayer, so I can't help you with this problem, sorry.

Anyway, just out of curiosity, can you tell me what is the max resolution that the official YouTube client shows to you?

**Comment by FitnessRegiment** [comment]
YouTube says 1080p but newpipe has 3k and 4k option.

what is exoplayer? I just installed f-droid apk and then installed newpipe
0.99

what could be broken? it's so weird I didn't have this issue a month ago or
so.

On 5 Jul 2017 13:22, "Mauricio Colli" <notifications@github.com> wrote:

I think that it's using WebM format (for that resolution probably the only
available), the bitrate of these videos is just huge and it's not designed
for any mobile device to handle it (similar to the issue #597
<https://github.com/TeamNewPipe/NewPipe/issues/597>).

However, from what I can see (http://wiki.webmproject.org/hardware/socs)
your device is quite powerful and it does have hardware decoding for VP9,
so I don't know exactly what it's happening, it seems like a bug in your
device or in ExoPlayer, so I can't help you with this problem, sorry.

Anyway, just out of curiosity, can you tell me what is the max resolution
that the official YouTube client shows to you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TeamNewPipe/NewPipe/issues/608#issuecomment-313086974>,
or mute the thread

**Comment by FitnessRegiment** [comment]
also my device can easily handle these bitrates. I watch larger files using
vlc quite often.
