### ISSUE TITLE
Subscription Feed Clickable Through Refresh Popup

### ISSUE THREAD

**Issue by kenktk** [TeamNewPipe/NewPipe#6081]
Not sure if this is actually a bug. Pardon me if this is already an issue (I couldn't find the ticket). 

Version: 0.21.1
System: Pixel 3a, GrapheneOS

As the title suggests, I can still click on items in my subscription feed upon refreshing it. 

![Screenshot_20210414-232602](https://user-images.githubusercontent.com/82561022/114813979-d596d380-9d78-11eb-81b0-7598593ef607.png)

The screenshot shows a video I clicked whilst refreshing feed.

**Comment by HTSamurai** [comment]
Yeah, that happens for me too on my Redmi 8. I've used this when I've seen
an interesting video just as I clicked refresh.
