### ISSUE TITLE
Fullscreen button doesn't appear for a certain video

### ISSUE THREAD

**Issue by kuba-orlik** [TeamNewPipe/NewPipe#6082]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open this video in newpipe (Video Player mode): https://www.youtube.com/watch?v=deBdzC5QVQw

### Actual behaviour

The video plays, but there's no "fullscreen" button.

### Expected behavior

The fullscreen button is visible

### Screenshots/Screen recordings

![Screenshot_20210415-074152_NewPipe](https://user-images.githubusercontent.com/2697916/114819731-309ee980-9dbe-11eb-93b9-da58cd89fe35.png)

### Device info

 - Android version/Custom ROM version: LIneageOS  15.1 (Android 8.1.0)
 - Device model: LG Nexus 5X

**Comment by mhmdanas** [comment]
You probably have auto-rotation enabled, which is the reason why the fullscreen button is not visible. Can you confirm if this is the case or not?

**Comment by kuba-orlik** [comment]
I do have auto-rotation enabled, but when I turn the phone sideways, the video does not go fullscreen

**Comment by mhmdanas** [comment]
Then can you open a separate issues for that?
