### ISSUE TITLE
Soundcloud sharing is not working

### ISSUE THREAD

**Issue by garawaa** [TeamNewPipe/NewPipe#6085]
When sharing a song from soundcloud gives message like:

Could not recognize the URL. Open with another app

**Comment by mhmdanas** [comment]
What version of NewPipe are you using?

**Comment by ShareASmile** [comment]
@garawaa  Don't ignore Issue Template. Filling of Issue template is mandatory. Now we have to ask number of questions to find about the issue you faced.

**Comment by garawaa** [comment]
> What version of NewPipe are you using?

last version 0.21.1

**Comment by TiA4f8R** [comment]
I think that you are using the SoundCloud app. Duplicate of #5025 in this case.
Like @ShareASmile said, please follow the corresponding issue template next time.
