### ISSUE TITLE
Comments, info, queue buttons appear on full screen portrait mode

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#6089]
### Checklist

- [x] I am using the latest version - 0.21.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

I can't reproduce at the moment but happened a few times already so might be able to recreate the issue soon.

### Actual behaviour

Full screen portrait mode shows the comment, info and queue buttons.

### Expected behavior

Should not appear.

### Screenshots/Screen recordings

![IMG_00213123](https://user-images.githubusercontent.com/55331939/114886968-8c399900-9df7-11eb-91c7-5b0f75b2c619.jpg)

### Logs

Not any.

### Device info

 - Android version/Custom ROM version: 10
 - Device model: OnePlus

**Comment by opusforlife2** [comment]
@desmonk Any luck?
