### ISSUE TITLE
Requesting a privacy friendly analytics service into NewPipe

### ISSUE THREAD

**Issue by d4f5409d** [TeamNewPipe/NewPipe#6095]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I would request a privacy friendly analytics tool in NewPipe implemented. I thought Matomo would be a good choice. Fathom is  a good alternative to Matomo, but it's not as famous as Matomo. (Element uses Matomo too) It should be for everyone disabled as by default, but the user could opt-in or if they wouldn't want to send reports anymore, an opt-out.

#### Is your feature request related to a problem? Please describe it

I want to have a system, that sends crash reports to NewPipe directly, automatically, when it happens. So I could contribute, and I wouldn't even have to worry about posting here on GitHub.

#### Additional context

-

#### How will you/everyone benefit from this feature?

This feature would let NewPipe developers fix the issues in NewPipe so fast. It would be convinient to contribute to the project, and also it could be helpful.

**Comment by TobiGr** [comment]
Hey there, thank you for the suggestion.

We use ACRA to compile the error reports. You can send the reports via email if you do not want to open GitHub issues. ACRA is also capable of sending the reports directly to an specified endpooint. We did not configure ACRA do to this for privacy reasons. E.g. many crash reports are extractor related and thus contain information on which video / audio streams a person watched or which search query was performed while the error occurred. This is sensitive information and for this reason, a user should be able to review it before sending a crash report or posting it publicly on GitHub.

On the other hand, there need to be devs with spare time which they dedicate to NewPipe and fixing bugs. And we ran out of free time and devs taking care of the app and the extractor lately. So there is no benefit for the devs or the users to send crash reports automatically at the moment. We are aware of many bugs, but do not have the manpower to fix them.
