### ISSUE TITLE
Being able to use a youtube account.

### ISSUE THREAD

**Issue by MELON119** [TeamNewPipe/NewPipe#6096]
Dear newpipe team,
Can you add a option where you can use your youtube account?

Sincerely,
M E L O N

(by the way why do I have to follow steps to just request a feature)

**Comment by sauravrao637** [comment]
Hi!
Thanks for requesting a feature,
NewPipe is an open source project and relies on contributions from developers around the globe ,  template helps them understand the feature well and ensure the request is not ignored .
Please follow the template strictly next time :)

**Comment by opusforlife2** [comment]
@MELON119 You follow the template so that you don't waste our time and yours. If you had followed the template, you would have known your request is a duplicate.
