### ISSUE TITLE
Long press on pause should shuffle and double tap should mute the queue

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6099]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Shuffle and mute are highly used features. Especially, if you are playing videos on popup or background. However, there's no way to activate these features easily. Personally, I recommend long press and double tap to activate shuffle and pause respectively.

Pause button from
1. Main player
2. Full screen
3. Mini player
4. Popup player

**Comment by mhmdanas** [comment]
I really think if this is added, it should be customizable which gesture does what.

**Comment by mhmdanas** [comment]
@SameenAhnaf please avoid closing issues without an explanation.
