### ISSUE TITLE
Spotify or YouTube Music Support Request

### ISSUE THREAD

**Issue by swarupbhanjachowdhury** [TeamNewPipe/NewPipe#6100]
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

As the web version of Spotify and actual Youtube Music is available on the web, can we get support of any of them?

open.spotify.com
music.youtube.com

**Comment by SameenAhnaf** [comment]
It already supports, dude! You can access it from three dots menu while searching.
![IMG_20210417_212917](https://user-images.githubusercontent.com/79245641/115118249-133b6c80-9fc4-11eb-9f3a-b014ada974f7.jpg)

**Comment by swarupbhanjachowdhury** [comment]
@SameenAhnaf yes but I'm also asking about Spotify 😐

**Comment by mhmdanas** [comment]
@swarupbhanjachowdhury service requests go to https://github.com/TeamNewPipe/NewPipeExtractor, not here. Please open an issue there for Spotify instead.
