### ISSUE TITLE
Startup loop on opening URLs (prob. device specific)

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#6103]
### Checklist

- [x] I am using the latest version - 0.21.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open any YT link with newpipe selected as a default app.

### Actual behaviour

Startup loop

### Expected behavior

Video opens

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/26146502/115139444-37ce2d80-a032-11eb-8b59-546ece2ed422.mp4

XiangRongLin/NewPipe-preuinified#3
I'm using this modified version most of the times. I downloaded the original app just to test this bug out. I hope it would be as easy as possible to backport the code that solves this. The video shown is from this app, but the exact same happened with "upstream" app.

### Device info

 - Android version/Custom ROM version: 11/API 30
 - Device model: Samsung Galaxy A70

**Comment by TiA4f8R** [comment]
Can you try the APK in #6052 and see if it works? Thanks!

**Comment by kubo6472** [comment]
Yup, works. Could you please point me to a PR that might have fixed this?

**Comment by kubo6472** [comment]
Fixed by #6053
