### ISSUE TITLE
Downloads: How do I change the default external media player?

### ISSUE THREAD

**Issue by davidhedlund** [TeamNewPipe/NewPipe#6104]
How do I change the default external media player that is launched when I click on play on a song in the Downloads tab?

I could not find anything related to this under Settings.

**Comment by eladkarako** [comment]
that's in player itself app settings, clear defaults (not NewPipe related).

**Comment by mhmdanas** [comment]
This is not handled by NewPipe; it's handled by Android. Search "how to change default apps in Android."

**Comment by davidhedlund** [comment]
The available media players are not listed in Default apps.

**Comment by mhmdanas** [comment]
Again, that's all handled by Android, not NewPipe, so we can't do anything. However, I can still try to help you resolve the issue. First, can you give your Android/ROM version and device?

**Comment by davidhedlund** [comment]
Oh, that's very kind of you! It's my mother's phone. Here are the specs:
Android version 10 with kernel 4.9.193
Phone: LG G7 ThinkQ

**Comment by davidhedlund** [comment]
> Again, that's all handled by Android, not NewPipe, so we can't do anything. However, I can still try to help you resolve the issue. First, can you give your Android/ROM version and device?

Oh, that's very kind of you! It's my mother's phone. Here are the specs:
Android version 10 with kernel 4.9.193
Phone: LG G7 ThinkQ

**Comment by mhmdanas** [comment]
Do you mind joining the IRC room so that we can communicate a bit faster? It would be much more convenient for me.

**Comment by davidhedlund** [comment]
> Do you mind joining the IRC room so that we can communicate a bit faster? It would be much more convenient for me. [Link](https://webchat.freenode.net/?channels=newpipe)

What is your nick?

**Comment by mhmdanas** [comment]
I'm `mhmdanas[m]` (because I'm using the Matrix bridge).

**Comment by davidhedlund** [comment]
> I'm `mhmdanas[m]` (because I'm using the Matrix bridge).

I'm hellomhmdanas but I cannot find you.

**Comment by mhmdanas** [comment]
It does not look like you joined the room to me.

**Comment by davidhedlund** [comment]
> It does not look like you joined the room to me.

I see 39 people in the room.

**Comment by mhmdanas** [comment]
That's not the correct room then. The #newpipe room has more than a hundred members.

**Comment by davidhedlund** [comment]
> That's not the correct room then. The #newpipe room has more than a hundred members.

Well I clicked on your link. How do I connect to the correct room then?

**Comment by mhmdanas** [comment]
Try writing `/join #newpipe` in the chat below and sending it.

**Comment by davidhedlund** [comment]
> Try writing `/join #newpipe` in the chat below and sending it.

That didn't help. I'm sorry but I give up. Thank you for your support though!

**Comment by mhmdanas** [comment]
Sorry for your wasting your time. Anyway, back to the issue on hand: could you post a screen recording showing where you go to the "default apps" thing in the settings and where you can't find any listed media players?

**Comment by davidhedlund** [comment]
> Sorry for wasting your time. Anyway, back to the issue on hand: could you post a screen recording showing where you go to the "default apps" thing in the settings and where you can't find any listed media players?

No sorry, but I go to Settings -> Apps & Notifications -> Default apps -- Neither VLC or Vanilla (the two media players) are listed there

**Comment by davidhedlund** [comment]
> Sorry for wasting your time. Anyway, back to the issue on hand: could you post a screen recording showing where you go to the "default apps" thing in the settings and where you can't find any listed media players?

Solved, I just followed this guide: http://www.technostarry.com/how-to-change-default-apps-on-android/

**Comment by davidhedlund** [comment]
Feel free to delete your history in this issue like I did to keep it clean if you want.

**Comment by davidhedlund** [comment]
Thank you very much for your effort in trying to help me again, that was kind of you.
