### ISSUE TITLE
Captions are censored

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#6105]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug/feature. I will open one issue for every bug/feature report I want to file.

### Actual behaviour
As stated above, the generated captions are censoring the language.

### Expected behavior
The captions should not be censoring anything.

#### Describe the feature you want
A way to either toggle or completely remove the censorship (such as the one shown) in the prevalent example.

#### Is your feature request related to a problem? Please describe it
N/A

### Notes
1. The settings (age setting off, restricted mode off) that should affect this are turned off.
2. The is present on the web version too.

#### How will you/everyone benefit from this feature?
It makes it more sincere when viewing a video without the sound on, and for those that are not so sensitive, it should be a choice what they do/don't want censored.

###P.S.
1. I apologize for going a little off-script on the issue template.

**Comment by mhmdanas** [comment]
There's nothing NewPipe can do about this, since NewPipe isn't the one generating the captions, but YouTube.
