### ISSUE TITLE
App crashes when i download in Pop-up mode

### ISSUE THREAD

**Issue by Stenledtrap** [TeamNewPipe/NewPipe#6107]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'a video'
2. Press on 'Pop-up mode'
3. Press on  'the channel and download any video while Pop-up is playing, it crashes.'

### Actual behaviour

The app crashes.

### Expected behavior
 Proceed to Download the selected video

### Screenshots/Screen recordings
!
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: The callable returned a null value
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Caused by: java.lang.NullPointerException: The callable returned a null value
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by Stenledtrap** [comment]
> 
> 
> 
> 
> 
> 
> ### Checklist
> 
> 
> - [x] I am using the latest version - x.xx.x 
> - [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
> - [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
> - [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.
> 
> ### Steps to reproduce the bug
> 
> 1. Go to 'a video'
> 2. Press on 'Pop-up mode'
> 3. Press on  'the channel and download any video while Pop-up is playing, it crashes.'
> 
> 
> 
> 
> 
> ### Actual behaviour
> 
> The app crashes.
> 
> 
> 
> ### Expected behavior
>  Proceed to Download the selected video
> 
> 
> 
> ### Screenshots/Screen recordings
> !
> ## Exception
> * __User Action:__ ui error
> * __Request:__ ACRA report
> * __Content Country:__ US
> * __Content Language:__ en-GB
> * __App Language:__ en
> * __Service:__ none
> * __Version:__ 0.21.0
> * __OS:__ Linux Android 10 - 29
> <details><summary><b>Crash log </b></summary><p>
> 
> ```
> io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: The callable returned a null value
> 	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
> 	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
> 	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
> 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
> 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
> 	at android.os.Handler.handleCallback(Handler.java:900)
> 	at android.os.Handler.dispatchMessage(Handler.java:103)
> 	at android.os.Looper.loop(Looper.java:219)
> 	at android.app.ActivityThread.main(ActivityThread.java:8349)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
> Caused by: java.lang.NullPointerException: The callable returned a null value
> 	at java.util.Objects.requireNonNull(Objects.java:228)
> 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
> 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
> 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
> 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
> 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
> 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:929)
> 
> ```
> </details>
> <hr>
> 
> 
> 
> 
> 
> 
> ### Logs
> 
> 
> 
> 
> 
> 
> 
> 
> ### Device info
> 
>  - Android version/Custom ROM version:
>  - Device model:
> 

The bug happens inconsistently.
Sometimes i have no problem, other time it crashes

**Comment by sauravrao637** [comment]
I would love to try fixing this error :)

**Comment by sauravrao637** [comment]
@Stenledtrap Can you please test the [apk](https://github.com/TeamNewPipe/NewPipe/suites/2536964778/artifacts/55045845) with this [pull request](https://github.com/TeamNewPipe/NewPipe/pull/6118).

**Comment by TobiGr** [comment]
@Stenledtrap Can you give us an URL to the stream you tried to download so we can test a few more things?

**Comment by Stenledtrap** [comment]
> @Stenledtrap Can you give us an URL to the stream you tried to download so we can test a few more things?

So im watching this (https://www.youtube.com/watch?v=IQ-i7eS-G3o&t=21) in Pop-up and then i go to https://www.youtube.com/watch?v=BgZu89utnLU&t=0 and i press to download that video, then the app crashes.

**Comment by TobiGr** [comment]
@Stenledtrap Can you try to reproduce the bug with [this debug APK](https://github.com/TeamNewPipe/NewPipe/suites/2538411972/artifacts/55095127)?
