### ISSUE TITLE
Move or duplicate location of "clear recaptcha cookies" setting

### ISSUE THREAD

**Issue by cegfault** [TeamNewPipe/NewPipe#6108]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The location of "clear recaptcha cookies" should be under the "History and cache" menu.

I recently had an issue where comments were not showing up on any video, and cleared all the cache options under "History and cache" to no avail.  Updated the app.  No avail.  It wasn't until two days later that I read elsewhere to "clear recaptcha cookies", and didn't realize that was an option. Went hunting, found it, solved my problem.

It feels very non-intuitive to have this setting elsewhere, as it feels like a "cache" thing, but is not in the "cache" menu!

#### How will you/everyone benefit from this feature?

This will make problem solving and basic self-diagnosis steps a lot easier, as I can just go to the one menu option and click all the "clear" options.  If I didn't know where the option was (or even that it existed!!), I'm sure other users are getting frustrated and (potentially spending your time by filling out issues) when there's a simple solution.

**Comment by SameenAhnaf** [comment]
@litetex Already implemented.

**Comment by TiA4f8R** [comment]
Indeed, it has been done by #7586. Closing as fixed.
