### ISSUE TITLE
Cannot pause video when buffering

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#6110]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

If I wanted to pause the video when buffering I couldn't. This is a bit problematic, because if the internet connection is poor then the video only buffers a little bit, plays that one-fourth of a second video then goes back to buffering hence making difficult to pause the video. It would be great to have the option to pause when buffering.

#### Additional context

This is what it looks like when a video buffers: i cannot interact with the pause icon

![buffering](https://user-images.githubusercontent.com/74684948/115258711-86162600-a131-11eb-8199-fd272a3cf0eb.jpg)

#### How will you/everyone benefit from this feature?

Smoother experience, native youtube app also allows this.

**Comment by Redirion** [comment]
please check if you still can't pause while buffering when using the current RC of the upcoming release: https://github.com/TeamNewPipe/NewPipe/issues/6052

**Comment by mhmdanas** [comment]
This should be fixed by #5929. If not, please make a comment on that PR.

**Comment by Hogerys** [comment]
Yep, fixed, thank you.
