### ISSUE TITLE
Video shouldnt autostart after unlocking phone

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#6111]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start video
2. Lock phone
3. Unlock phone
4. Video autos starts

I don't know if this is considered a bug or not. I turned off all auto-continue settings.

### Actual behaviour

Video automatically starts to play after unlocking phone.

### Expected behavior

Video shouldn't autoplay, rather show a play icon to continue.

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Xiaomi Redmi 6

**Comment by SameenAhnaf** [comment]
I suggested a solution in #6142.
Turn off screen if video interface is hidden: Switch to background
Turn off screen if video interface is shown: Pause the video

This setting should be applicable for main player, full screen and popup player. If video is paused and interface is hidden, turning off screen should stay the video paused.

I know, it's more logical to pause the video directly by turning off the screen. But here are the reasons why I didn't propose so.
1. Popup player always works this way.
2. "Pause+Show interface / Resume+Hide interface" and "Pause / Show interface / Resume+Hide interface" touch actions are expected to be added. Switching to background while showing the interface is unexpected.
3. Consistent actions in all players.

**Comment by SameenAhnaf** [comment]
You may easily get your desired feature sby following these steps for now.
1. Go to 'Settings'
2. Select 'Video and audio' section
3. Scroll down and reach 'Behavior' subsection.
4. Select 'Minimize on app switch'
5. Select 'None'

**Comment by Hogerys** [comment]
@mhmdanas Its only happening when I'm in fullscreen and pause the video. I pause it, lock it, then unlock it. Is it a feature? Can i turn it off?

**Comment by Hogerys** [comment]
@HTSamurai Its off.

**Comment by Hogerys** [comment]
@mhmdanas I noticed that I wrote the reproduction list wrong. Instead of Start video I should've wrote Start video, then Stop video, then continue. So anyway I tested this on a non MIUI OS (screw MIUI) and it works fine so I'm closing it. Reopen this if other Xiaomi users have reported similar issues or make someone test this on their device. Otherwise ty.
