### ISSUE TITLE
No bug, simple question: How to open fullscreen mode?

### ISSUE THREAD

**Issue by Lalarian** [TeamNewPipe/NewPipe#6115]
Hello, I am new to NewPipe and just installed 21.1 to my phone,
But I cannot find a fullscreen button. Can someone help me, please?
Thanks! :)

**Comment by ImPureSilver** [comment]
Welcome aboard! I am assuming you're talking about how to fullscreen a video. To do so, play any video of your liking. While the video is playing, tapping on it once should bring up a few video player toggles. In the bottom right, you should see a square box. Tapping the box will fullscreen the video.

**Comment by mhmdanas** [comment]
@Lalarian it's as @ImPureSilver says. If you can't find the fullscreen button, it's probably because you have autorotation enabled. Just rotate your screen to get the fullscreen video, or otherwise disable autorotation and the button will be shown.

**Comment by Lalarian** [comment]
Thank you!
