### ISSUE TITLE
It would be nice if there is a theme option that we can make the top red panel black.

### ISSUE THREAD

**Issue by ilhanyurek** [TeamNewPipe/NewPipe#6116]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by TiA4f8R** [comment]
Closing as a duplicate of #6119.
