### ISSUE TITLE
please add a simple line to manifest for multiwindow support?

### ISSUE THREAD

**Issue by denemier** [TeamNewPipe/NewPipe#6117]
Can't use the app as multiwindow app on samsung tab 4 7 android 7, on internet it says it's just about manifest update since the app is responsive.

**Comment by sauravrao637** [comment]
Hi!
We can already use NewPipe in split mode if that's what u mean :)

**Comment by TiA4f8R** [comment]
Yes, @sauravrao637 is right, see [here](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/AndroidManifest.xml#L27). If you don't have this option, it's something about your ROM and not about the app. Try enabling `Force activities to be resizeable` option of the Developer Options in your device's settings if you don't have this option on your tablet.

Please follow the template next time. I close this issue. Thanks!
