### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by ilhanyurek** [TeamNewPipe/NewPipe#6119]
It would be nice if there is a theme option that we can make the top red panel black.

**Comment by TobiGr** [comment]
NewPipe has three themes: light, dark and black. You can choose you preferred one on the Appearance settings. Support for individual themes is out of scope for now.

**Comment by ilhanyurek** [comment]
Complete black like mod apks

**Comment by mhmdanas** [comment]
Duplicate of #4148.
