### ISSUE TITLE
Screen dims when rotating device to landscape

### ISSUE THREAD

**Issue by 9mido** [TeamNewPipe/NewPipe#6126]
In portrait orientation, the screen is full brightness. In landscape orientation, the screen dims almost all the way and the screen can barely be seen. Keeping the screen brightness of the host device is desirable no matter what the device orientation is. This happens when a video is being played.

**Comment by mhmdanas** [comment]
Do you have the brightness gesture enabled? If so, I believe that's the reason. Use the gesture to change the brightness of the video. If not, please open a new issue that doesn't remove the template and follows it properly.
