### ISSUE TITLE
Support for improved 144p

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#613]
- [y] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [y] I checked if the issue/feature exists in the latest version.

It seems you use the flip-phone version of youtube's 144p (3GPP), however, youtube has improved compression and offers much better looking 144p (not sure about bitrates though, but compare 144p in newpipe compared to 144p on youtube's website). It would be nice if you offered the improved codec version along with a choice in audio bitrate for people who are data constrained (16-64k audio would work), but would like better video quality.

A compression server that converts to 16k opus would be cool, but I'm sure that would require too many resources on the newpipe server, unless youtube already offers it.

**Comment by utack** [comment]
There is a "ready to go" muxed version, which is really sh*t  
`17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k`
and video to choose from as separate stream
`278          webm       256x144    144p  118k , webm container, vp9, 30fps, video only, 3.93MiB  
160          mp4        256x144    DASH video  133k , avc1.4d400c, 30fps, video only, 4.49MiB  
330          webm       256x144    144p60  204k , vp9.2, 60fps, video only, 6.06MiB  
`

**Comment by mauriciocolli** [comment]
The thing is, opus is supported only in Android 5.0+ [(from android official)](https://developer.android.com/guide/topics/media/media-formats.html#audio-formats), there are extensions for playing opus in every device (in ExoPlayer), but I really don't want to include it in the app, as it'll requires native code.

Currently, the chosen audio stream that we play together with a video only stream, is the one that matches the preferred format (in the settings) and have the highest bit rate available.

And some videos have the `139` stream (a very low quality audio m4a), I'm thinking in using it when the user selects such low qualities (144p), but that is just an idea for now.

**Comment by utack** [comment]
@mauriciocolli sorry to hijack this issue, but does "webm" use opus on devices that support opus playback or always vorbis?

**Comment by mauriciocolli** [comment]
@utack no it doesn't (you can see the list [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/services/youtube/YoutubeStreamExtractor.java#L153)), but I was thinking in doing that.

**Comment by utack** [comment]
would be nice, since lately it is not just the better codec, but also getting more bitrate than AAC as well

**Comment by phly95** [comment]
Huh, 144p60 is an option. That would be a very interesting combination to see in action. I wonder if it would be possible to use the 24k m4a stream along with these interesting resolutions. Maybe quality needs to be a nested menu where you select video quality > FPS > Format > Audio format > bitrate . The issue with offering this much choice however could mean confusing both the users and developers though, so I'm not quite sure how viable that would be.

**Comment by FaizKhan5** [comment]
Close this issue.

**Comment by opusforlife2** [comment]
Already added.
