### ISSUE TITLE
go to lanscape mode when rotation lock is on

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#6131]
I donk know why the latest version remove the newpipe legacy function
Where if you try to open a video to fullscreen now in the latest new pipe version with rotation lock on for some reason it 
rotate to lanscape mode first then fullscreen
Rather then
Newpipe legacy version where it doesnt matter if you have rotation lock on or off when you open it to fullscreen it doest have this issue it just lock to whatever your screen rotation is

**Comment by SameenAhnaf** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/5459 is in work as a solution.
