### ISSUE TITLE
error code each time

### ISSUE THREAD

**Issue by aaazv** [TeamNewPipe/NewPipe#6132]
Im getting this error code each time opening a video by a link. #
![Screenshot_20210421-152243_NewPipe](https://user-images.githubusercontent.com/19729879/115542907-04033a00-a2b6-11eb-9cec-4d964c2b3f57.jpg)

And no I dont have expressvpn installed and my rom is fresh

**Comment by TiA4f8R** [comment]
Unfortunately, it isn't something related to NewPipe. Where did you download the app? From [F-Droid](https://f-droid.org/packages/org.schabi.newpipe), the [GitHub releases page](https://github.com/TeamNewPipe/NewPipe/releases), or from our [website](https://newpipe.net/#download)? If you didn't download the app from one of these origins, please uninstall the app and post the link of the source you downloaded this app in a comment, it can be a malware, an adware, or just a commercial modified (especially if it comes from the **Google Play Store**, the app cannot be published by ours on it), except if you downloaded the app from a **trusted source**, like for example the SponsorBlock fork, which is on [GitHub](https://github.com/polymorphicshade/NewPipe). If it isn't the case, please check the apps in your device's settings and uninstall any app that you didn't install yourself and isn't a part of your system.

Also please follow the corresponding template. There are good reasons not to remove it, especially to save the time of everyone with the same feature(s) requests or bug reports or by asking the questions which are in the template.

**Comment by aaazv** [comment]
> Unfortunately, it isn't something related to NewPipe. Where did you download the app? From [F-Droid](https://f-droid.org/packages/org.schabi.newpipe), the [GitHub releases page](https://github.com/TeamNewPipe/NewPipe/releases), or from our [website](https://newpipe.net/#download)? If you didn't download the app from one of these origins, please uninstall the app and post the link of the source you downloaded this app in a comment, it can be a malware, an adware, or just a commercial modified (especially if it comes from the **Google Play Store**, the app cannot be published by ours on it), except if you downloaded the app from a **trusted source**, like for example the SponsorBlock fork, which is on [GitHub](https://github.com/polymorphicshade/NewPipe). If it isn't the case, please check the apps in your device's settings and uninstall any app that you didn't install yourself and isn't a part of your system.
> 
> Also please follow the corresponding template. There are good reasons not to remove it, especially to save the time of everyone with the same feature(s) requests or bug reports or by asking the questions which are in the template.

Downloaded from github

**Comment by TiA4f8R** [comment]
So please check the apps in your device's settings and uninstall any app that you didn't install yourself and isn't a part of your system.

**Comment by aaazv** [comment]
Checked the toast source and it is frok android system app.
I dont have express vpn installed, why should it send thist error pop up?

**Comment by TiA4f8R** [comment]
By saying Android System app, are you referring to the `android` package? If yes, I recommend you to check your VPN settings and remove any app that you can found in the list and you don't trust. If it doesn't help you, I recommend you to reset your network settings and then reset your system or flash again your system, if it the network settings reset does nothing.

Again, next time, use our templates. It seems that you're using a custom client which doesn't support they, check these links for the templates: [bug report](https://raw.githubusercontent.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md), [feature request](https://raw.githubusercontent.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by aaazv** [comment]
![Screenshot_20210502-191856_Settings](https://user-images.githubusercontent.com/19729879/116817383-53c9e700-ab7b-11eb-8c98-01369d416efc.jpg)
![Screenshot_20210502-191918_Toast Source](https://user-images.githubusercontent.com/19729879/116817386-575d6e00-ab7b-11eb-92f6-523a8fceecb7.jpg)


This is what I mean

**Comment by TiA4f8R** [comment]
Please check my comment an follow its instructions. If you don't know how find the package name of the "Android System", check some apps like [Package Manager](https://f-droid.org/packages/com.smartpack.packagemanager/). Thank you.

**Comment by aaazv** [comment]
My rom is fresh, did a network reset and still the same problem.
Still, sorry for not following the template, Im not a pro in github so just thought of reporting the issue I found to help your app.

**Comment by TiA4f8R** [comment]
Don't worry about that, we are not good at everything. By checking one of your screenshot, it seems that you're using a VPN. Can you confirm?

**Comment by aaazv** [comment]
Thanks.
Yes, its shadowsocks. Not express vpn

**Comment by TiA4f8R** [comment]
Can you search for VPN in your device's settings?

**Comment by aaazv** [comment]
Yes I did, removed the two vpns enabled there. and still the same happened.

**Comment by aaazv** [comment]
Even tried a different vpn and the same thing happened. The toast appears.
Im using 1.1.1.1 and shadowsocks.
