### ISSUE TITLE
Button back doesn't back

### ISSUE THREAD

**Issue by rosariotech** [TeamNewPipe/NewPipe#614]
Wheb searching, back button of the interface go back to a blank page, while back button of the android go back correctly.

**Comment by TheAssassin** [comment]
We need confirmation. Anyone who cane reproduce the problem, please let us know. Please include your Android version, and ROM name.

**Comment by utack** [comment]
it is really simple

- Search anything
- Tap result
- Use the back button in the top left corner
- Blank page

https://youtu.be/kXVoBt2BsAI

v 0.9.9 on Lineageos 14.1

**Comment by theScrabi** [comment]
This is how the button is supposed to work.
The top left corner button should bring you back to the start of the app, while the hardware back button should put you back one step.

This is how android apps are supposed to be designed.

**Comment by mauriciocolli** [comment]
I think it's better to go back to the search first (up button go to a "top level") because, for example, if the user search for something, navigate through a bunch of videos and channels, I think that the his "mental map" will be something like this flow:


```
                    +---------------+
                    |  Main Screen  +----+
                    +-------+-------+    |
                            |            |
                            ▲ Up         | Search Button
                            |            |
                       +----+-----+      |
          +------------+  Search  |◄-----+
          |            +----+-----+
          |                 |
          |                 ▲ Up
   Open   |                 |
something |    +------------+-------------+
          |    |                          |
          |    |  Video    <->  Channel   |
          +---►|  Channel  <->  Playlist  |
               |  Video    <->  ....      |
               |                          |
               +--------------------------+
```

**Comment by rosariotech** [comment]
It's exactly this. It just few awkward working in different ways with the hardware button and the interface button.

I use Lineage OS 14.1 (Android 7.1.2).
