### ISSUE TITLE
Video should pause or switch to background if player interface is shown or shown respectively while turning off screen

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6142]
### Checklist

- [x] I am using the latest version - 0.21.0
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

I am not sure how this feature actually works as I rarely use it. In current versions of Newpipe, the video switches to background regardless of being interface shown or hidden.

However, users should be given the choice to pause the video easily. Video should pause instead if the interface is shown while turning off the screen.

### Actual behaviour

Video automatically switches to background if the interface is shown.

### Expected behavior

Video should pause if the interface was shown while turning off screen.

### Device info

 - Android version/Custom ROM version: MIUI 12.0.3
 - Device model: Xiaomi Redmi Note 8 Pro

**Comment by mhmdanas** [comment]
I'm having a hard time understand what the problem is and what you're proposing. Can you give an _explicit_ list of steps that showcase the behavior you described and clarify the alternative you propose?

**Comment by SameenAhnaf** [comment]
@mhmdanas I tried to figure out the steps. It seems like that this incident is actually based on "Minimize on app switch" setting.

If 'None' is enabled:
1. Go to main player or full screen
2. Turn off the screen
3. Video stays paused
4. Turn on the screen
5. Video still stays paused

If "Switch to background player" is enabled:
1. Go to main player or full screen
2. Turn off the screen
3. Video switches to background
4. Turn on the screen
5. Video switches back to main player

If "Switch to popup player" is enabled:
1. Go to main player or full screen
2. Turn off the screen
3. Video switches to background
4. Turn on the screen
5. A. If 'Main player' was selected: Switches to popup as usual.
B. If "Full screen" was selected: This is what happens. Only popup player functions can be done. Clicking elsewhere switches back to full screen. However, closing the popup still doesn't switch to full screen. The video still stays paused.
![IMG_20210422_233918](https://user-images.githubusercontent.com/79245641/115761300-0653ba00-a3c4-11eb-91d4-ca609a12bdb1.jpg)


This is just weird. "Minimize on app switch" and "Turn off screen on main player and full screen" are two different things.

My proposal: I suggested a solution in #6142.
Turn off screen if video interface is hidden: Switch to background
Turn off screen if video interface is shown: Pause the video

This setting should be applicable for main player, full screen and popup player. If video is paused and interface is hidden, turning off screen should stay the video paused.

I know, it's more logical to pause the video directly by turning off the screen. But here are the reasons why I didn't propose so.
1. Popup player always works this way.
2. "Pause+Show interface / Resume+Hide interface" and "Pause / Show interface / Resume+Hide interface" touch actions are expected to be added. Switching to background while showing the interface is unexpected.
3. Consistent actions in all players.

This extra option will be highly appreciated.
Video paused+ Headphone connected
1. Volume up+ Pause: Switch to background and resume playback. Turning on screen should switch back to main/popup/full screen.
2. Volume down: Switch to background and resume playback. Turning on screen should not get back to previous player.
I don't know if the same feature could be applied for device volume buttons. But reconsider its implementation if possible.
Suppose, I am watching a music video. I want to do an emergency work. After coming back, I don't want to turn on the screen again. Just want to continue to my segment. It will let me get done a 2 in 1 job.

#6111 asks for the same solution. However, I explained him everything. So, just close that issue.

**Comment by mhmdanas** [comment]
I think I get your idea, but I'm not really a fan of using headphones' volume buttons to control anything other than volume.

**Comment by SameenAhnaf** [comment]
@mhmdanas That's true, bro. My music lover friends didn't find it interesting.

**Comment by SameenAhnaf** [comment]
Closing in favor of #4558.
