### ISSUE TITLE
No "show channel details" in long-press menu in feed or local playlist items

### ISSUE THREAD

**Issue by mhmdanas** [TeamNewPipe/NewPipe#6155]
### Checklist

- [x] I am using the latest version - 0.21.2 RC/latest dev build 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open any feed (e.g. What's New) or local playlist
2. Long press on an item

### Actual behaviour

There's no "show channel details" shown in the menu.

### Expected behavior

There should be a "show channel details" option in the meu.

### Additional context
https://github.com/TeamNewPipe/NewPipe/pull/5851#issuecomment-823188251

### Device info
This is platform-independent, but I filled this out for completeness.

 - Android version/Custom ROM version: Android 11
 - Device model: Galaxy A51

@opusforlife2

**Comment by SameenAhnaf** [comment]
As you can see, there are problems only in subscription or playlist feed. Sorry for too fast videos. I had to cover within the file size limit.

https://user-images.githubusercontent.com/79245641/115942116-6d5b9680-a4ca-11eb-9c13-db72f5c28bde.mp4

However, such problems don't persist in channel feed or search results.

https://user-images.githubusercontent.com/79245641/115942203-dc38ef80-a4ca-11eb-9c64-e5a80ca021da.mp4

**Comment by mhmdanas** [comment]
@SameenAhnaf I haven't actually taken a look, but I believe it's because these feeds aren't saved to the database, so the uploader URL isn't lost.

**Comment by nihalanand697** [comment]
just to add that even in search results if you open a playlist there is no menu for "show channel details".

**Comment by mhmdanas** [comment]
@nihalanand697 hmm, that's odd, and it might invalidate my original hypothesis. Anyway, I'll be actually taking a look sometime soon.

**Comment by XiangRongLin** [comment]
@ktprograms opened an PR for this issue. Can you guys check if it solves your problems
