### ISSUE TITLE
Newpipe is extremly slow

### ISSUE THREAD

**Issue by ebanDev** [TeamNewPipe/NewPipe#6160]
### Checklist

- [x] I am using the latest version - 0.21.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Just open the app and see the loading is sloooow

### Actual behaviour

1. Loading is very slow

### Expected behavior

1. To load ? 😅

### Device info

 - Android version/Custom ROM version: LineageOS 17.1 (Android10)
 - Device model: Lenovo Z5 pro GT

### Additional infos
- I have IPv6
- From the website YouTube loads perfectly and isn't slow 
- I'm in the UE

**Comment by mhmdanas** [comment]
Assuming by UE you mean the European Union, this is probably a duplicate of #5977. Try the APK there or connect to a non-EU country using a VPN and see if it works. I'll be closing this issue for now, but if I was mistaken, feel free to make a comment and I'll re-open the issue.
