### ISSUE TITLE
Please make caption text stable and suitable

### ISSUE THREAD

**Issue by LeoK987** [TeamNewPipe/NewPipe#6165]
(Auto-generated) Caption texts are justified centrally, making their locations shifts when changing lines, which then makes them difficult for the eye to track.  Justifying them to the left might be ideal, as YouTube does.

Also, the default caption size is too big.  if I want to change the size, I have to go through Accessibility and turn on Caption for the entire system, which I don't want to do.  Can it be done through other means?

**Comment by mhmdanas** [comment]
For the first request, please open a separate issue that follows the template properly. For the second request, you should be able to change the font size by going to `Settings > Appearance > Captions`. I don't think you have to enable the captions from settings for the change to take effect. However, if you have any trouble, feel free to make a comment.
