### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by 1kaiser** [TeamNewPipe/NewPipe#6169]
When we add something by share from youtube app. The dialog box could contain "enque" option that will place it in now playing list.

When the app gets freezed, Its not possible to get this queue of items,
So could there be a list automatically keeping items in queue, after its watched or played it may move it to watch history.

Can we get to sync our watch history sync to youtube as a option.?

**Comment by mhmdanas** [comment]
For the first request, see #4779. For the second one, I'm not sure I understand; could you clarify? For the third one, that will never happen, as it goes directly against the project's goals.

Also, please don't remove the template next time you open an issue.

**Comment by 1kaiser** [comment]
The list in enque gets lost if the app freezes, can it keep the items in the list sync to watch later list in new pipe so that the list can be picked up again,l.
