### ISSUE TITLE
Can't download videos with audio in 480p.

### ISSUE THREAD

**Issue by AquaVirus** [TeamNewPipe/NewPipe#617]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [Not really, too many issues to read] I checked if the issue/feature exists in the latest version.

The title says it all. It's a bug. I don't see why you shouldn't be able to download videos with audio in 480p. It used to work in older versions, too.

**Comment by mauriciocolli** [comment]
###### From https://github.com/TeamNewPipe/NewPipe/issues/608#issuecomment-312904335
> Regarding the no-audio, it's the way that YouTube works, it delivers the video and audio in different streams, the only thing that we could do is merging them, but that would require some libraries that I'm not sure we're going to include (I'm studying that option though).

And in  older versions there wasn't 480p available, this change was quite recently introduced.
