### ISSUE TITLE
Any download freezes on serviio media server about half way through.

### ISSUE THREAD

**Issue by Stinggy** [TeamNewPipe/NewPipe#6174]
For some reason anything I download seems to freeze about half way through on serviio media server. I can download the same file using other downloaders and I have no issues. I am wondering if I should try the legacy version as a test.

**Comment by Stinggy** [comment]
What does doesn't follow template mean. Anyways it is obviously an issue of some sort the way it is compiling the download anything else will work including vidmate

**Comment by TiA4f8R** [comment]
It seems that you are using a GitHub which doesn't support issue templates. Check the difference by trying to create a new issue with the GitHub website: https://github.com/TeamNewPipe/NewPipe/issues/new/choose.

**Comment by litetex** [comment]
No feedback - Closing this issue.
