### ISSUE TITLE
Someone knows what happens, I already solved the captcha and it is not solved

### ISSUE THREAD

**Issue by Carlos502gt** [TeamNewPipe/NewPipe#6175]
![Screenshot_20210425-231421_NewPipe.jpg](https://user-images.githubusercontent.com/81324987/116032043-309fb480-a61c-11eb-8171-f1d8bd6a21d4.jpg)

**Comment by TiA4f8R** [comment]
Duplicate of #6055. Please don't remove the template next time, there are reasons to keep it.
