### ISSUE TITLE
Custom sort services & hide services

### ISSUE THREAD

**Issue by ChunkyProgrammer** [TeamNewPipe/NewPipe#6178]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x]  This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think the ability to sort and hide services would be a good addition. I don't feel like this is a priority at the moment but with the addition of new services this feature could come in handy. 

#### Is your feature request related to a problem? Please describe it

Services might get too cluttered in the future

#### Additional context
 I did a rough mockup

![Sort+HideServices](https://user-images.githubusercontent.com/78101139/116105135-07644000-a67f-11eb-8577-38e9a9e8455b.jpg)

I'm thinking that this page can be accessed by going to "Settings" and clicking on a "Services" setting.

#### How will you/everyone benefit from this feature?

Users can hide services that they don't use/ hide services specific to languages that they don't speak.

**Comment by ChunkyProgrammer** [comment]
I am not 100% sure whether I should have done separate issues for sorting and hiding but I feel like they're pretty similar especially considering the moqup. Let me know if I should create two issues instead.

**Comment by ChunkyProgrammer** [comment]
Somewhat similar to #4081

**Comment by SameenAhnaf** [comment]
@litetex This issue should be closed in favor of https://github.com/TeamNewPipe/NewPipe/issues/1116, I think.
