### ISSUE TITLE
Videos begin in the paused state

### ISSUE THREAD

**Issue by dbenjaminmiller** [TeamNewPipe/NewPipe#6179]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Go to play a video.
### Actual behaviour
Whether autoplay is on or off, the video begins in the paused position and must be manually begun. If autoplay is on, this means one tap (so, effectively, autoplay does not work). If autoplay is off, this means two taps.

### Expected behavior
Videos should begin in the playing state.

### Screenshots/Screen recordings

https://streamable.com/0pvyx1 / https://streamable.com/bknr08

### Device info

 - Android version: 11
 - Device model: Sony Xperia 1ii

**Comment by mhmdanas** [comment]
Introduced in 0.21.2; see https://github.com/TeamNewPipe/NewPipe/issues/6052#issuecomment-818006660.

**Comment by Redirion** [comment]
could this PR have caused the regression? https://github.com/TeamNewPipe/NewPipe/pull/5929

**Comment by SameenAhnaf** [comment]
Strange enough. But it a user switches to full screen before the buffering ends, video starts or can be paused (while and after buffering) as usual.

Also, main player cannot recognise if buffering icon was pressed or not. Video always stays paused at the beginning.

**Comment by SameenAhnaf** [comment]
Strange enough. But it a user switches to full screen, video begins to start.

Also, main player cannot recognise if buffering icon was pressed or not. Video always stays paused at the beginning.

**Comment by opusforlife2** [comment]
> But it a user switches to full screen, video begins to start.

Only when the full screen video is landscape. If it's a portrait video, then the video stays paused even on tapping the full screen button.

**Comment by SameenAhnaf** [comment]
@opusforlife2 I hardly watch portrait videos. So, I didn't notice that. Thanks for noting that.

**Comment by Douile** [comment]
That does seem like it would be causing this issue.

**Comment by litetex** [comment]
I submitted a PullRequest, which should fix the problem.

I the meantime you can try enable "History and cache>Resume playback" and check if this fixes the problem :)
