### ISSUE TITLE
cannot navigate with arrow keys?

### ISSUE THREAD

**Issue by blueskiesokie** [TeamNewPipe/NewPipe#618]
I have a Sonim XP5 phone. It has Androd 4.4.2. It doesn't  nkshave touchscreen, only keypad and directional pad with select button. 
Is it possible to get a version that has this?

Thanks

**Comment by geebotron** [comment]
This is basically the same feature request: Allow proper navigation using the arrow keys.

I'm actually wanting to use this app on a Amazon FireBox via the remote. There are two things I have noticed (but there are probably other similar things):

1. Search doesn't pop up the soft "arrow friendly" keyboard
2. Search results cannot be selected via arrow keys (fire remote)


Thanks

**Comment by theScrabi** [comment]
Yea sounds cool :)

**Comment by B0pol** [comment]
fixed by https://github.com/TeamNewPipe/NewPipe/pull/2806
