### ISSUE TITLE
Progress bar not matching short video

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6180]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to newpipe
2. Watch this video https://www.youtube.com/watch?v=s-MsZo02dos
3.  Look at the progress animation

### Screenshots/Screen recordings

![Screenshot_20210427-040728](https://user-images.githubusercontent.com/74511929/116169882-573e1800-a70e-11eb-9a02-23b2d1af958a.jpg)
![Screenshot_20210427-040738](https://user-images.githubusercontent.com/74511929/116169886-5907db80-a70e-11eb-95a2-63e398daaeea.jpg)

### Device info

 - Android version/Custom ROM version: Android v7 Nougat
 - Device model: SM P555

**Comment by Thewisem** [comment]
I know you updated the app like hours ago

**Comment by Thewisem** [comment]
And this happend in the updated one

**Comment by litetex** [comment]
Should be fixable using:
```DIFF
diff --git a/app/src/main/java/org/schabi/newpipe/player/Player.java b/app/src/main/java/org/schabi/newpipe/player/Player.java
index c10307b98..23f520985 100644
--- a/app/src/main/java/org/schabi/newpipe/player/Player.java
+++ b/app/src/main/java/org/schabi/newpipe/player/Player.java
@@ -2253,6 +2253,8 @@ public final class Player implements
             stopProgressLoop();
         }

+        binding.playbackSeekBar.setProgress(binding.playbackSeekBar.getMax());
+
         showControls(500);
         animate(binding.currentDisplaySeek, false, 200, AnimationType.SCALE_AND_ALPHA);
         binding.loadingPanel.setVisibility(View.GONE);
```
