### ISSUE TITLE
The new version is very laggy on low end android device. I use 520 mb ram phone and i used newpipe as an alternative because it was smooth. But the latest version feels laggy. I cant scrool through smoothly any more. Please fix the issue as soon as possible and make the app smooth again 

### ISSUE THREAD

**Issue by yamiamin** [TeamNewPipe/NewPipe#6183]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by Flam3z** [comment]
You must provide additional information to your bug report as well as follow the bug reporting guidelines do the devs can understand your issue better.

**Comment by TiA4f8R** [comment]
Closing until you follow the template properly.

**Comment by theoasispc** [comment]
You just need to clear the cache data and it fixes this problem.
