### ISSUE TITLE
Swipe to delete item from History/Playlists

### ISSUE THREAD

**Issue by iamthesenate1** [TeamNewPipe/NewPipe#6187]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be nice if you added swipe to delete item from History/Playlists as it would be an usability/fluidity improvement.

Still, I think the current method should remain for the users of Android TV.(I'm not sure, correct me if I'm wrong)

Also, after deleting I think there should be a notification(I don't know how to call it, like the one when the app couldn't fetch comments from a video, in older versions(not the new menu that appears)) that would give the user the ability to undo the action.(maybe)
#### Is your feature request related to a problem? Please describe it

Not really, maybe usability

#### Additional context

As pointed out on IRC by @mhmdanas, #2432 exists but was closed by the author for some reason.

#### How will you/everyone benefit from this feature?

It would be easier to delete items from Playlists/History.

**Comment by Hamedamz** [comment]
I'll work on this.

**Comment by Angelk90** [comment]
@iamthesenate1 , @Hamedamz : Is there any news on this?

**Comment by iamthesenate1** [comment]
@Stypox Since @Hamedamz's PR has been closed, I think he shouldn't be assigned anymore.

**Comment by Stypox** [comment]
@iamthesenate1 we are not implementing swipe actions as:
- they would conflict with other gestures 
- they would only allow adding at most two actions 
- it would be difficult to choose two actions without getting users complaining
- adding a setting page to customize swipe actions for every possible view would be really really complicated and would probably introduce bugs

We are staying with the long press menu, and there are plans to improve it.

**Comment by SameenAhnaf** [comment]
@Stypox If solving this issue is not possible, #2306 should stay open neither.

**Comment by Stypox** [comment]
You are right

**Comment by wizdom13** [comment]
For reference, our independent NewPipe fork, [[WizeStream](https://github.com/wizdom13/WizeStream)](https://github.com/wizdom13/WizeStream), has implemented swipe-to-remove for videos in local playlists, together with an immediate **Undo** action.

The implementation is deliberately limited to local playlists and does not add swipe actions to every history or queue view.

WizeStream is independent and is not affiliated with or endorsed by TeamNewPipe.
