### ISSUE TITLE
NewPipe displays 0kbps as maximum audio bitrate(?) for a video

### ISSUE THREAD

**Issue by AquaVirus** [TeamNewPipe/NewPipe#619]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
( The "?" besides "bitrate" is because I'm not sure it's called bitrate. )
There's this video (https://www.youtube.com/watch?v=-y2lEB6uwwI) that if I try to download its audio, it shows "m4a 0kbps", but when I downloaded the audio, the file played just fine.

**Comment by AquaVirus** [comment]
Another weird thing is that I can't download its audio as WebM. It just downloads it as m4a anyways.

**Comment by theScrabi** [comment]
Can please you post a screenshot of that problem.

**Comment by AquaVirus** [comment]
Sure. http://i.imgur.com/flB11er.png

**Comment by AquaVirus** [comment]
Found one more video this happens on. https://youtu.be/dGRDwfqMT24

**Comment by mauriciocolli** [comment]
Oh just found the culprit, is the [DashMpdParser.java#L84](https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/DashMpdParser.java#L84) (those memeTypes...), is passing 0 to the bitrate.

But the `YoutubeStreamExtractor` needs a refactor anyway, for example you can't get some things without calling others first (only one of the existent problems).

**Comment by mauriciocolli** [comment]
It's working fine now:

<img src="https://user-images.githubusercontent.com/13389907/28097831-ef4c911e-6688-11e7-9b36-1ab599608706.png" width="280">

**Comment by doixuihen** [comment]
It seem really silly but could you share the video you've attempted to download in 2017?
And if you want to share it privately, this is my email: doixuihen@gmail.com

**Comment by AquaVirus** [comment]
@doixuihen Sorry for the late reply. The video has been deleted, but here's a reupload: https://www.youtube.com/watch?v=ctBR15WnpII
