### ISSUE TITLE
Unable to download some 1080p youtube videos

### ISSUE THREAD

**Issue by deepalwije** [TeamNewPipe/NewPipe#6192]
Hi,
Iam using your softwear since last two months on my samsung tab S7+ and i found following issue on it.
when I try to download youtube video  which shows multiple resolution (for example 360,480,720,1080) newpipe app ONLY allows me to download 360P video .

If you want to try pls try to download the 1080P video file from the link below using NEWPIPE app.( for me when i try to download this particular youtube video newpipe app ONLY allow me to download 360P resolution file , but actually in youtube it has 1080P video)

sample youtube video link: https://www.youtube.com/watch?v=HSNYnvaLf0s

Please resolve this issue on future version update.

NOTE: This issue not happens to all youtube videos. I mean it can download some 1080P videos with out any issue using newpipe app.

thx
Deepal

**Comment by botistreamer** [comment]
Maybe related to #2415

**Comment by Feuerswut** [comment]
Close as fixed
