### ISSUE TITLE
Cannot pause queue manager or notification player while buffering

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6196]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Pause/Play doesn't work on notification player or queue manager player while buffering. It works completely fine on main player or full screen.

### Expected behavior

Ability to select pause or play should work normally for notification and queue manager player just like main player.

### Device info

 - Android version/Custom ROM version: MIUI 12.0.3
 - Device model: Xiaomi Redmi Note 8 Pro

**Comment by SameenAhnaf** [comment]
It seems like that it neither works for popup player. The feature was only added for main player. However, the buffering still misbehaves at the beginning.

**Comment by EvilGremlin** [comment]
It doesn't work in fullscreen as well. Extremely annoying, because it also tends to switch between buffering and play 2-3 times a second, which is another old unfixed bug.

**Comment by SameenAhnaf** [comment]
@EvilGremlin Wait, I can pause the player if buffering occurs in the middle of a video. But pause and buffering icons get smudged mentioned in #6215.

Also, "Pause on start" is a requested feature in #6040 for the buffers occuring at the beginning.

It seems like that these three issues should be solved altogether. Unless, users won't be able to exactly know what is exactly happening.
