### ISSUE TITLE
Replace position of "Queue manager button" to left of seek bar of main player, full screen player and popup player

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6197]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It's hard to understand if queues or chapters are in existence. Both icons are in similar positions which makes it harder to differentiate between functions. That's why, I prefer to keep queue manager on the left of seek bar.

There's no easy to manage queue for popup player. However, it could have been easily implemented on the left of seek bar for popup player as well.

#### How will you/everyone benefit from this feature?

1. Users won't face trouble while distinguishing between "Chapters" and "Queue Manager" icons.
2. User won't have to get confused if chapters or queue are existing
3. Easier navigation as whole title bar can be used for managing queue (just like empty space of notification player). 
4. Popup viewers will also be able to manage queue easily within the  popup itself easily without opening the app.

**Comment by 1kaiser** [comment]
![enque](https://user-images.githubusercontent.com/26379748/116558858-81b1f000-a91d-11eb-99b2-8a8d4a76992c.png)

**Comment by SameenAhnaf** [comment]
@1kaiser Sorry for not being clear, my issue was about messing up 'Chapters' and 'Queue manager' icon on main player. I discussed about enqueue options here: #5940.

**Comment by SameenAhnaf** [comment]
On the left of seek bar is a better position, I guess. No need to turn the title bar cluttered.

**Comment by SameenAhnaf** [comment]
Closing in favor of #7973
