### ISSUE TITLE
If resume playback is off, clicking on a video while the player is open causes a reboot

### ISSUE THREAD

**Issue by djhorine** [TeamNewPipe/NewPipe#6201]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to settings
2. Go to history and cache
3. Disable resume playback
4. Start a video
5. While the first video is open (through miniplayer, popup, or main player), click a second video

### Actual behaviour

The screen momentarily freezes, then the phone displays the boot animation before going back to the lockscreen as if rebooted.

### Expected behavior
The second video should start in place of the first video.

### Screenshots/Screen recordings

I haven't been able to capture any before the device reboots.

### Logs

No crash screen displays before the reboot.

### Device info

 - Android version/Custom ROM version: Android 11 RP1A.200720.009 (Stock)
 - Device model: Google Pixel 2 XL (taimen)

**Comment by sheepdestroyer** [comment]
Pixel 2xl here too, same symptoms

**Comment by arima0k** [comment]
Confirmed.

Pixel 2 version 0.23.0.

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?
