### ISSUE TITLE
Whe using dark mode, change the color of red elements so they have a dark pale shade of red

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#6203]
#### Describe the feature you want
When using the dark mode, make red colored elements to have a dark pale shade of red. 

#### Is your feature request related to a problem? Please describe it
The current red, that is very vivid, causes eye strain.

#### Additional context
![imgonline-com-ua-twotoone-Iku5fRLxPNu](https://user-images.githubusercontent.com/78433932/116641758-c3559180-a943-11eb-9a47-17e794257592.jpg)

Left: purposed design¹ | Right: currently

¹In the phone, it's a lot more vibrant than it is when viewing through a PC, so this mockup may look weird on some phones '-'

#### How will you/everyone benefit from this feature?
To reduce eye strain, the accent have to be dark and pale. Putting a red vivid color in dark mode is not aligned with the purpose of this mode.

**Comment by sauravrao637** [comment]
Hi !@blackandyellowgecko 
Do u like it now (check the [apk ](https://github.com/TeamNewPipe/NewPipe/suites/2662811221/artifacts/58619169)generated from [PR#6244](https://github.com/TeamNewPipe/NewPipe/pull/6244)) or would u like  it more darker (^_^)?

**Comment by mhmdanas** [comment]
I am not a fan at all of changing the colors to be darker _by default_. I'm fine if it's a toggle in the settings though.

**Comment by iamthesenate1** [comment]
> I am not a fan at all of changing the colors to be darker _by default_. I'm fine if it's a toggle in the settings though.
> 
> Thoughts?

I ageree. This should be optional. In my opinion it should be the default but there should be more user feedback.
A little off-topic, but I think it would be good if polls would be a feature of the Newpipe website (and after an update peple could vote if they want a feature or not).
Also this can be further improved by integrating the feature directly in the app.

**Comment by iamthesenate1** [comment]
> A little off-topic, but I think it would be good if polls would be a feature of the Newpipe website (and after an update people could vote if they want a feature or not).
> Also this can be further improved by integrating the feature directly in the app.
As this is off topic should I make an issue?

**Comment by sauravrao637** [comment]
@iamthesenate1 I think you should proceed and never hesitate to do such things

**Comment by blackandyellowgecko** [comment]
> Hi !@blackandyellowgecko
> Do u like it now (check the [apk ](https://github.com/TeamNewPipe/NewPipe/suites/2662811221/artifacts/58619169)generated from [PR#6244](https://github.com/TeamNewPipe/NewPipe/pull/6244)) or would u like it more darker (^_^)?

Looks way better! Another possible solution would be a transparent top bar, following Material Design 2 guidelines.

**Comment by blackandyellowgecko** [comment]
> Hi !@blackandyellowgecko
> Do u like it now (check the [apk ](https://github.com/TeamNewPipe/NewPipe/suites/2662811221/artifacts/58619169)generated from [PR#6244](https://github.com/TeamNewPipe/NewPipe/pull/6244)) or would u like it more darker (^_^)?

Looks way better, congrats! The status bar still show the vivid red color, so does the splash screen. Another possible solution would be a transparent top panel, following Material Design 2 guidelines (for example, YouTube and Play Store ditched the red and the green background in the top panel).
