### ISSUE TITLE
Propsal

### ISSUE THREAD

**Issue by ilhanyurek** [TeamNewPipe/NewPipe#6208]
Proposal

It would be great if invidious support comes.

**Comment by mhmdanas** [comment]
What do you mean by Invidious support? Sharing YouTube URLs as Invidious URLs (#2351)? Extracting from Invidious instead of YouTube in the extractor (TeamNewPipe/NewPipeExtractor#427)? Logging in to Invidious (#3198)? Please clarify.

Also, please don't remove the template when opening an issue.
