### ISSUE TITLE
Please add posibility of copying URLs and opening URLs

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#621]
Sometimes it is needed to copy or paste URLs in NewPipe

**Comment by TheAssassin** [comment]
I think an even more convenient way would be to integrate NP into the "share" menu. Sharing is often (mis)used for convenience functionality not supported by Android
# , for instance you can just open non-clickable URLs in the browser by sharing them using this nifty app: https://gitlab.com/marc.nause/openlink. There's more examples e.g. on F-Droid. Would something like this be sufficient for you?

(By the way, as NP intercepts youtube.com URLs, I guess the above app provides the functionality you're seeking for already.)

**Comment by theScrabi** [comment]
NewPipe is already integrated into share menu.

**Comment by teod0r** [comment]
Sometimes I need to copy an URL from NewPipe and have to open the video in browser and copy from there. Pasting URLs would be usefull too.

**Comment by chilliger** [comment]
Maybe a good solution would be to show the copied youtube URL (or the parsed title of the URL) as the first suggestion when searching in newpipe? And to know that this entry in the search suggestions is coming from the clipboard, display a clipboard icon next to the URL.

**Comment by TobiGr** [comment]
That's a good idea

**Comment by opusforlife2** [comment]
Already added.
