### ISSUE TITLE
Opening videos became very slow

### ISSUE THREAD

**Issue by Saddam-KGB** [TeamNewPipe/NewPipe#6210]
Hello guys 
I am grateful to you for this amazing, great program
İ have installed the latest Newpipe version 0.21.2, but unfortunately Youtube videos run very slowly, there are some bugs that make Newpipe very slow to run or download YouTube videos, sometimes some videos don't be openable.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just want to confirm that this is still happening in 0.21.7

**Comment by litetex** [comment]
Thank you for the issue!

Is this still a problem?
If yes, could you please provide any screen recordings / logs, etc?
