### ISSUE TITLE
Replaying a video in any player requires tapping the replay button twice

### ISSUE THREAD

**Issue by j-james** [TeamNewPipe/NewPipe#6217]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
A weird bug, but also weirdly consistent. 
1. Start playing a video in any player.
2. Wait for it to finish.
3. Swipe down to open up the notification tray, and tap the "replay" button, or tap the button in the main/popup player.
4. Observe the video doesn't replay.
5. Tap the replay button again, and watch it replay.

### Actual behaviour

Included above. Funnily enough, this behavior also persists after closing the notification tray or locking the phone - eg. if you tap it once, turn off the phone, and then turn it on and tap it again, it'll play.

### Expected behavior

The video should replay after one tap.

### Device info

 - Android version/Custom ROM version: GrapheneOS 11
 - Device model: Pixel 4a

**Comment by j-james** [comment]
Oh, this is also a regression from one or two versions ago.

**Comment by SameenAhnaf** [comment]
It seems like that it is the case with all players. Sorry for poor quality. I had to cover the file size limit.

https://user-images.githubusercontent.com/79245641/117383782-60479a00-af03-11eb-8ed3-c3838b94655e.mp4

**Comment by j-james** [comment]
Something similar also appears to happen when selecting a video to play for the first time.

**Comment by SameenAhnaf** [comment]
@j-james #6179 is there for that.

**Comment by skyGtm** [comment]
Although no crash has been mentioned, this issue might be related with crash report mentioned in #6401
