### ISSUE TITLE
Contribution: Add a guide that explains how to setup this project for developing

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#6220]
Preamble: I'm not sure if this is a bug or feature request, it's more like a "meta"-issue.

### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
When someone wants to contribute to this project, it would be nice if he knows what he needs to do that (e.g. Android Studio, Android SDK, Java)...
A little setup guide (e.g. first install X then Y, if you install Y make sure you use option Z, ...) could also be good idea.
It would be nice to know the requirements for contributing (where to download them, what version, etc.) and how to set them up.

Currently I was not able to find anything related to this topic.
I checked:
* https://github.com/TeamNewPipe/NewPipe/blob/dev/README.md
* https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#code-contribution - only tells you how to handle the code / best practices
* https://newpipe.net/FAQ/

but none of them mentions this topic.

#### Is your feature request related to a problem? Please describe it
Newcomers have a hard time figuring out what to do if they want to contribute to the project. 
This can be depressing and even lead to the point, where they are not even more in the mood for contributing and abandon that try.

#### Possible solution(s)
Add a "developing.md" somewhere, where the above is explained.

Other projects that explain how to build/develop:
* https://github.com/barbeau/gpstest#building-the-project
* https://github.com/notepad-plus-plus/notepad-plus-plus#build-notepad
* https://github.com/desktop/desktop/blob/development/.github/CONTRIBUTING.md#set-up-your-machine

**Comment by ChunkyProgrammer** [comment]
There's this https://teamnewpipe.github.io/documentation/00_Prepare_everything/#setting-up-your-dev-environment but it definitely needs to be easier to find

**Comment by litetex** [comment]
A guide how the checkstyle plugin has to be installed/configured/used would be nice 😄

**Comment by Stypox** [comment]
@litetex check out #6482

**Comment by litetex** [comment]
@Stypox 
I did a quick review and it looks already pretty good.
If I have enough time I will do a detailed review in the next days.

Good work! 😄
