### ISSUE TITLE
Fit/Fill/Zoom Doesn't work

### ISSUE THREAD

**Issue by mazejk** [TeamNewPipe/NewPipe#6221]
When i press on the Fit/Fill/Zoom it does nothing at all, just word changes to next mod
Version 0.21.2
Device: Casper VIA M3

Device info:
screen size - 5.5 inch
storage - 32gb
ram - 3gb
battery - 3000 mAh
CPU Frequency - 1.3 GHz
CPU Core - 4 Core
Screen to Body Ratio - 70.15 %
Screen resolution - 720x1280 (HD) Pixels
Android 7.0

**Comment by opusforlife2** [comment]
@mazejk Why?
