### ISSUE TITLE
Downloads speeds are incredibly slow and stall

### ISSUE THREAD

**Issue by ipoopedmypantsuups** [TeamNewPipe/NewPipe#6223]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Any YouTube Video in Newpipe'
2. Press on 'Download'
3. Swipe down to 'Choose Audio or Video'
4. Wait for it to download...slowly
5. Download eventually stalls after a short while without user interaction

Internet speeds from Speedtest.net:

![image](https://user-images.githubusercontent.com/73392805/116828764-bcf72d80-ab6e-11eb-9f0a-9c79bab800bd.png)
Causes/Factors: Unsure. Internet speeds are great (fiber optic connection) but might be due to old phone hardware. I am less than 1 room away from the router in my home (bedroom) and have noticed same speeds house-wide. 
### I have tried: 
1. Changing router settings
2. Changing connected WiFi network
3. Rebooting phone
4. Reinstalling Newpipe

### Actual behaviour

Download will start and the first few MB might go fast, but eventually the download slows to a crawl and just straight up stops or stalls. *E.g; I went to download a 20 minute video from youtube in audio format. Went to get some food and coffee, keeping the phone away. Found the download stalled at 56/200 MB and is not moving.*

### Expected behavior

Video or Audio should download smoothly without stalling after only a few minutes. Download should be able to be completed in a (somewhat) timely manner, even with slow internet.

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/73392805/116828893-9e456680-ab6f-11eb-9838-ef42ba816131.png)

### Device info

 - Android version/Custom ROM version: 8.1.0 / crDroid version 4.6.1
 - Device model: SM-G900T

**Comment by mikeloeven** [comment]
I can confirm download performance issues Downloading the audio track from a video seemed to cap out around 500-600 kbps while browser or file manager downloads were about 2-3 megabytes per second. albiet its an older S5 so the hardware is a bit limited but I still would expect the 2-3 megabytes per second when downloading over wifi instead of DSL speeds

**Comment by Broeckelmann** [comment]
Maybe just download one at a time and increase the threads per download 🤔

**Comment by mikeloeven** [comment]
@Broeckelmann this is with only a single download active also with older devices increasing threads can cause worse issues and lead to file corruption if the CPU does not have multiple cores

**Comment by Broeckelmann** [comment]
Sorry didn't knew that, was just an idea. Than it is likely a Software & Hardware thing.
