### ISSUE TITLE
Remote Stack Trace Crash

### ISSUE THREAD

**Issue by whoogle** [TeamNewPipe/NewPipe#6224]
Hi
I am currently using NewPipe version 0.21.2 Github build. I am facing this error on previous versions of Newpipe even on my earlier android 10 device.

This crash happens suddenly whenever i was watching some content on Newpipe & it just exits automatically. After that i am unable to open Newpipe again.

To fix this error temporarily i cleared app data & restored the Playlist & channels subscription backup only. If settings also restored then this error again came frequently.

After i used this temporary fix same error came again after long usage time period of Newpipe like around 2-3 weeks approx according to my usage.

• Crash logs:
https://del.dog/aisapamest.txt

• Device details:
Device Name: Realme 5 Pro (RMX1971)
Android 11
OS: Custom ROM Nusantara OS
Newpipe Version: 0.21.2 Github build

I hope soon an workaround will be implemented in next updates.
Thanks for making an awesome app.

**Comment by TiA4f8R** [comment]
That's strange, I had this service on my app, downloaded on GitHub too. Can you try again by reinstalling the app (export your database before if you can)? If it doesn't work, this bug may be related to your custom ROM.

Also, don't remove the template when opening an issue.

**Comment by litetex** [comment]
Closing because
* no feedback (since >3 months)
* links are dead
* version is now outdated
* template got ignored
