### ISSUE TITLE
Sponsor Skip

### ISSUE THREAD

**Issue by wolf075** [TeamNewPipe/NewPipe#6226]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be helpful to save time and avoid irrelevant and annoying sponsor spots in videos if the Sponsor Skip browser extension can be integrated into NewPipe.

#### Additional context

The Sponsor Skip adon is available on browsers and it has been integrated into Youtube Vanced app.

#### How will you/everyone benefit from this feature?

This feature will avoid wasting time on irrelevant sponsor spots in different countries.

**Comment by SameenAhnaf** [comment]
Extremely sorry, but devs don't want it. See: https://github.com/TeamNewPipe/NewPipe/pull/3205

You may check out this fork though. It has SponsorBlock implemented.
https://github.com/polymorphicshade/NewPipe
