### ISSUE TITLE
Display and scrolling issues

### ISSUE THREAD

**Issue by ishai8** [TeamNewPipe/NewPipe#6228]
Sometimes after playing a video  minimizing and after that closing it. the bottom area where the video was previously played is left blank during scrolling

**Comment by litetex** [comment]
Thank you for the issue!

If this is still a problem, can please fill the issue out according to our template: 
https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md

Screen records and logs would be great 😄
