### ISSUE TITLE
Kore (kodi remote control) not open

### ISSUE THREAD

**Issue by black00019** [TeamNewPipe/NewPipe#6239]
When press a button to share video on Kodi, the "Kore" App report a toast for install, but kore is installed and working, (i have install Kore from Fdroid Repo and setting up for my Kodi installation).

N.B. in a older version of newpipe the function work (i remember)
Thanks

### Device info

 - Android version/Custom ROM version: Lineage OS 17.1 
 - Device model: marlin

**Comment by TiA4f8R** [comment]
Duplicate of #5599. Please don't remove the template next time.
