### ISSUE TITLE
Square thumbnails

### ISSUE THREAD

**Issue by fynngodau** [TeamNewPipe/NewPipe#6245]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Square thumbnails should be displayed more true to the original by not displaying them in a landscape, but rather in a square ImageView.

#### Is your feature request related to a problem? Please describe it

All thumbnails are currently center-cropped to fit the landscape thumbnail slot by the NewPipe app.

#### Additional context

Both Soundcloud as well as Bandcamp provide cover arts that are square and not landscape.

(For Bandcamp, there's no strict requirement for cover arts to be square, but most cover arts are square anyway.)

#### How will you/everyone benefit from this feature?

Improved compatibility to non-video services, making NewPipe more enjoyable with the two supported music services.

**Comment by opusforlife2** [comment]
Related: #4106
