### ISSUE TITLE
Hybrid Feed Loading

### ISSUE THREAD

**Issue by BayKanguru** [TeamNewPipe/NewPipe#6246]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

A hybrid of fast and slow feed loading strategies that first loads with fast load and than slowly fills out details with slow load. This would probably use more data but an option would be good.

#### Is your feature request related to a problem? Please describe it

Information on if a video is live or its lenght are useful but loading those are very slow especially if you're loading a lot of channels' feeds.

#### How will you/everyone benefit from this feature?

With this feature you can get speed of fast loading with information from slow one. Only comprimise is data and that can be fixed by making this optional and not the default behaviour.

**Comment by HTSamurai** [comment]
Ooh this is a good idea. Maybe this would replace old fast feed?

**Comment by SameenAhnaf** [comment]
Is this any different from #4934?
