### ISSUE TITLE
Crop in feature

### ISSUE THREAD

**Issue by mythe4th** [TeamNewPipe/NewPipe#6247]
Hi guys I think this feature already exists, its the crop in feature for a video but i cant figure out how to do it. It doesnt work when i try to do it like in the youtube app. And I cant find anything in the settings. Is it a bug that it doesnt work for me or what is going on?

I'am on 21.2 and using a galaxy s10 with one ui 3.1 android 11.

**Comment by SameenAhnaf** [comment]
Please follow these steps.

1. Go to main player.
2. Click on 'Secondary Controls' icon on video interface
3. Choose 'Fit', 'Fill' or 'Zoom' according to your necessity.


https://user-images.githubusercontent.com/79245641/117285860-4cac1d00-ae8a-11eb-8c96-5c80d055b54c.mp4



Also, please follow the templates from next time.
