### ISSUE TITLE
Update notification changed my amazon password

### ISSUE THREAD

**Issue by wtrocki** [TeamNewPipe/NewPipe#6248]
Not really bug but I have noticed that notification I got from new pipe about new version available redirected me to amazon security warning page: `Someone is trying perform operation on amazon on your behalf`

Then my password to amazon was changed. I lost access to my amazon account.

Used APK from releases.

**Comment by TiA4f8R** [comment]
That's really strange and is not related to NewPipe itself or its repository. However, from what I know, GitHub uses some AWS (Amazon Web Services) servers. I don't know why this happened. I suggest you to reset your password with your email if you can do it. Also check if you have any strange apps on your phone which can be malware.

**Comment by wtrocki** [comment]
@TiA4f8R Notification is being issued from NewPipe App `New version of NewPipe is available` once user opens the app. 
Then if you click on the local notification is steals your Amazon account (changes password).

How this can be not related to NewPipe installed from apk from releases page?

**Comment by wtrocki** [comment]
I have contacted Amazon to confirm that this happened. Changed password and decompiled APK to confirm that this is happening.

Created Reddit Thread: 
https://www.reddit.com/r/NewPipe/comments/n64gay/newpipe_released_version_has_backdoor_that_steals/

**Comment by TiA4f8R** [comment]
Can you install [Intent Intercept from F-Droid](https://f-droid.org/packages/de.k3b.android.intentintercept), remove your default browser if you have one and click again on the notification (you need to change your system date to 1 day after today), open the notification with Intent Intercept and post the URL or a screenshot of the Intent Intercept app? Thanks!

**Comment by wtrocki** [comment]
ok. So somewhat apk i had installed was different. using releases has redirected me to releases page properly. Not sure where i got this fake APK

**Comment by wtrocki** [comment]
So to make it clear. I'm 100 sure I got this APK from fdroid not release section of the repo. APK from release are fine

**Comment by TobiGr** [comment]
Can you send us a copy of the APK which caused the problem?

**Comment by TobiGr** [comment]
Did you get the APK from our custom F-Droid repo or the official F-Droid repo?

**Comment by TiA4f8R** [comment]
@wtrocki ^

**Comment by TheAssassin** [comment]
> Used APK from releases.

That's not very precise. Please send us the exact link you used. And if you can upload the APK, that would be highly appreciated as well. We have some experience in reverse-engineering on Android, and if there's a criminal attack ongoing, we need to notify our entire userbase.

**Comment by wtrocki** [comment]
Yes. Sorry. I done that long time ago, but problem happened when clicked on update:
Trick is that I cannot find APK for the NewPipe - it was F-Droid APK. 

I have tracked history and I think that I could not figure where I got this and the only APK I have in downloads is f-droid.apk
I think that this is clearly case of me having APK from wrong place.

**Comment by TheAssassin** [comment]
Can you please check whether your F-Droid client uses custom package repositories?

**Comment by TiA4f8R** [comment]
@wtrocki Did you install 0.21.2 from our releases page or do you always have the "malicious" APK? If the answer to my second question is yes, please upload the APK in ZIP format. You can extract the APK by using [Apk extractor](https://f-droid.org/packages/axp.tool.apkextractor) Also, can you get the signature using [App Manager](https://f-droid.org/packages/io.github.muntashirakon.AppManager)? Go to NewPipe in Apk Manager, go to the Signatures tab, then compare with this screenshot from the official signature:

![Screenshot_20210506_174222.jpg](https://user-images.githubusercontent.com/74829229/117328339-d3b1c300-ae93-11eb-9e87-eff0573812e3.jpg)

Thank you in advance.

**Comment by wtrocki** [comment]
It looks like out of stupidity I have lost version that caused issue and do not have original APK availabe
