### ISSUE TITLE
Play downloaded medias with internal players instead of external players

### ISSUE THREAD

**Issue by NanyangTaiji** [TeamNewPipe/NewPipe#6252]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment]
You may try out this fork by polymorphicshade: https://github.com/polymorphicshade/NewPipe

**Comment by NanyangTaiji** [comment]
Thanks for the quick response!
