### ISSUE TITLE
Downloading via share menu using SAF while no dowload folder was set before does not work

### ISSUE THREAD

**Issue by iamrahatul** [TeamNewPipe/NewPipe#6256]
Download from in-app works, but when I try to download from outside the app, with Vanced, by sharing, it doesn't work. It just creates an empty file, and it won't even show in the download manager.

### Checklist

- [x] I am using the latest version - **0.21.2** 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to YouTube Vanced
2. Choose any video, click on share, choose NewPipe
3. Tap Download

### Actual behaviour
 Download screen pops up
![Screenshot_20210508_162637](https://user-images.githubusercontent.com/35030968/117535963-506ea980-b01a-11eb-8baa-7ad2095160ca.jpg)

Creates a file
![Screenshot_2021_0508_162915](https://user-images.githubusercontent.com/35030968/117536022-a6435180-b01a-11eb-8a93-9971e62a365f.jpg)

But won't download, 0.00 kb

### Expected behavior

I expected it to download the video, like it does when downloading from inside the app.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Vivo Y220

**Comment by SameenAhnaf** [comment]
On my device, I am facing the exact opposite bug. "Download" from video info crashes the app.

**Comment by TobiGr** [comment]
Tested with latest dev: that problem is only present when SAF is used and no download folder was set before
