### ISSUE TITLE
Not able to play the subscription videos.

### ISSUE THREAD

**Issue by mauricioph** [TeamNewPipe/NewPipe#6259]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mauricioph** [comment]
This happened every time I go to the subscription and select any videos from there. 
Trending videos work fine, but sometimes it requires to complete a captcha before playing.
On the subscription tab it was prompting for captcha few days ago. But now it just throw an error.

**Comment by sauravrao637** [comment]
@mauricioph ,did u try clearing captcha cache?

**Comment by mhmdanas** [comment]
@mauricioph do you get an error? If so, could you please post in here?

Also, please edit your issue to follow the template properly.

**Comment by litetex** [comment]
Closing this issue for now because 
* no feedback
* template got ignored
