### ISSUE TITLE
Setting to change the order of bottom tabs or to change the one that opens by default

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#6265]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Sometimes I want to read comments. This is very rare. And I usually more interested in looking at upcoming videos or a description of the video instead of comments. But I also dont want to disable comments because if I would have to reenable it in the settings.

So I propose a setting tht gives the user the ability to either change the order of these tabs (so the first one opens up always) OR change the one that opens by default. Perhaps even both.

#### Additional context

![Screenshot_2021-05-10-18-26-08-844_org schabi newpipe_1_1](https://user-images.githubusercontent.com/74684948/117778729-3ad9c980-b23e-11eb-9531-78f69eb985c1.jpg)

#### How will you/everyone benefit from this feature?

More customizability / convenience.

**Comment by SameenAhnaf** [comment]
I think, YouTube alike UI for main player should be introduced. No need to keep comments or description optional. Only, related videos could be kept optional. If a user requires them, he will just click on it to do so.

Short press on title bar: Show description with buttons
Short press on 'Secondary controls' icon: Show buttoms only
Short press on 'Comments': Show comments

![IMG_20210613_230436](https://user-images.githubusercontent.com/79245641/121827932-c03e1700-ccdf-11eb-80b5-dc73155b7dec.jpg)

**Comment by Hogerys** [comment]
@SameenAhnaf Yes that would be a better option.

**Comment by Hogerys** [comment]
@SameenAhnaf Is there an issue already recommending to create a layout similar to YouTube? I'll close this just in case. Otherwise reopen it.
