### ISSUE TITLE
customization of themes

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#6272]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

ability to change colours of various elements in app(eg. changing seekbar to blue, changing buffered time to white, in a colour picker tool in settings)

#### Is your feature request related to a problem? Please describe it

currently, there is only three themes available, white dark, amoled, no option to custom themes

#### How will you/everyone benefit from this feature?

we can choose how we want the app to look, customization

**Comment by SameenAhnaf** [comment]
Just a reminder that top bar colour should not get changed. Each top bar accent colour represents the service. Only, empty area under top bar should get changed for each theme.
<details><summary>Screenshot for theme colour</summary>
![IMG_20210516_151324](https://user-images.githubusercontent.com/79245641/118392181-04df7f80-b65a-11eb-8c5f-5a0841bbe76d.jpg)
</details>

Also, always ask share menus and long press menus don't get pitch colour. The background screen gets dim enough to identify the menu. So, it should be resolved.

<details><summary>Screenshot share menu</summary>
![IMG_20210516_145746](https://user-images.githubusercontent.com/79245641/118392191-145ec880-b65a-11eb-8993-d50b85fc7edb.jpg)
</details>

<details><summary>Screenshot share menu</summary>
![IMG_20210516_145824](https://user-images.githubusercontent.com/79245641/118392193-16288c00-b65a-11eb-9e15-1bbe6c9aa15a.jpg)
</details>

Also, I have been facing this weird bug whenever I try to download a video for the first time after clearing data each time.
<details><summary>Screenshot bug</summary>
![IMG_20210515_131525](https://user-images.githubusercontent.com/79245641/118392264-8afbc600-b65a-11eb-8da1-652b35764948.jpg)
</details>

**Comment by castrik** [comment]
well, its custom, so anyone can change it to any color 
eg. someone may want to make a complete amoled black or white theme and don't need to see if its youtube or soundcloud as they may not use them
also @SameenAhnaf you can just decide not to change the colors, I'm asking for customization, not new in-built themes

**Comment by SameenAhnaf** [comment]
@castrik That's okay. If I am not wrong, you requested for customising following features. Not an entire theme.

1. Top bar colour (These colours should be a little darker compared to empty area colour. Applying same colour for both would look odd. An option 'Automatic' should be added to match top bar colour according to service)
2. Empty area colour
3. Seek bar colour
4. Buffering icon
5. Volume and Brightness icons

**Comment by agerhard0** [comment]
I second the request of castrik, as I am missing even basic customization options (e.g. for YouTube Service switching from red to blue or green top bar colour) in the app.

**Comment by prirai** [comment]
One thing makes me worry for sure. Some hackers (idk) have been making mods of this app by changing colors and even the app name and icon. It's really frustrating.

**Comment by k9janer** [comment]
I'm using NewPipe on my OLED tv. Currently the red color of the Youtube section is kind of dangerous for my tv as there are a lot of examples on older OLEDs where part of the screen with static red banners and logos has burned in. The Netflix logo is a common example.

So for OLED tv owners the ability to change the colors isn't just about customization, it's also about ensuring the longevity of their device by switching to a different color - or preferably just black.

(If a customization option is still ways off, I think making a minor tweak to the black theme so it always uses a black top bar color would also be a great mitigation for this issue and it would also make the black theme better in my opinion.)

**Comment by SameenAhnaf** [comment]
@prirai Let's keep that discussion in https://github.com/TeamNewPipe/NewPipe/issues/539. Handling copycats is not related to this issue and ability of changing themes will neither solve the problem.

**Comment by Stypox** [comment]
I'd rather not do this. It would introduce much complexity into the app with only some small benefits for a niche of users.
