### ISSUE TITLE
video not available

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#6277]
hi

I get the message video not available on youtube on many videos while the videos are reallyon youtube.

**Comment by dreamsoftunitedkingdom** [comment]
It seems it has something to do with youtube's new age verification for certain videos.
I get the error 'video not available' for each youtube video thar required the age verification.

This is normal in newpipe or is there a fix for this available?

**Comment by iamthesenate1** [comment]
Can you give examples?

**Comment by dreamsoftunitedkingdom** [comment]
just take any video on youtube that required age verification...
they all have this error

**Comment by TiA4f8R** [comment]
Did you enabled `Show age restricted content` in Settings, Content? If no, can you try again please? Thank you!

**Comment by seanking2919** [comment]
> 
> 
> Did you enabled `Show age restricted content` in Settings, Content? If no, can you try again please? Thank you!

I have "Show age restricted content" enabled. And I can't even access videos like [Toy Soldier](https://www.youtube.com/watch?v=uoB_MDSkHms) per se.

**Comment by dreamsoftunitedkingdom** [comment]
stupid crap software!!!

**Comment by seanking2919** [comment]
> 
> 
> > Did you enabled `Show age restricted content` in Settings, Content? If no, can you try again please? Thank you!
> 
> I have "Show age restricted content" enabled. And I can't even access videos like [Toy Soldier](https://www.youtube.com/watch?v=uoB_MDSkHms) per se.

As of v0.21.3, my issue with "age restricted content" is fixed.

**Comment by opusforlife2** [comment]
Well, ghost is ghost, and @seanking2919 says the issue is fixed.
