### ISSUE TITLE
a built-in web browser is missing within your APK.

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#6281]
Good morning, my suggestion to improve the APK is 
* Add an anonymous web browser that has an ad blocker.
* The current problem with Google is that when you select a video within Google, it automatically redirects it to YouTube, and not to your APK.

**Comment by mhmdanas** [comment]
I personally believe such a feature is out of scope for NewPipe.

> The current problem with Google is that when you select a video within Google, it automatically redirects it to YouTube, and not to your APK.

Can you check that NewPipe is set to open YouTube links by default and not the YouTube app?

Also, please don't remove the template when opening an issue.

**Comment by car53** [comment]
> Personalmente, creo que esta característica está fuera del alcance de NewPipe.
> 
> > El problema actual con Google es que cuando seleccionas un video dentro de Google, lo redirige automáticamente a YouTube y no a tu APK.
> 
> ¿Puede comprobar que NewPipe está configurado para abrir enlaces de YouTube de forma predeterminada y no la aplicación de YouTube?
> 
> Además, no elimine la plantilla al abrir un problema.

Amigo pero dónde o cómo puedo enviar mis sugerencias a  new Pipe entre todos deberíamos pedirle que incluya esa función. No crees?
