### ISSUE TITLE
UI overlay stays when unpausing from bluetooth.

### ISSUE THREAD

**Issue by EvilGremlin** [TeamNewPipe/NewPipe#6282]
Well, that. Any android version (6,7,9), any BT device, any NewPipe version of last year or so.

**Comment by mhmdanas** [comment]
Can you clarify what an "overlay" is? Also, please don't remove the template when opening an issue.

**Comment by EvilGremlin** [comment]
UI overlay is all controls etc.
Issue is waaay too simple and easily reproduceable to warrant lengthy template imo.

**Comment by mhmdanas** [comment]
Duplicate of #3403.

**Comment by EvilGremlin** [comment]
Ahaha, so i just serched for wrong words. Again.
