### ISSUE TITLE
Calidad de audio

### ISSUE THREAD

**Issue by car53** [TeamNewPipe/NewPipe#6283]
Can someone tell me what is the best audio quality with which the audio can be downloaded in new Pipe?

**Comment by TiA4f8R** [comment]
It depends of the service: for YouTube, the best qualities are Opus, around 160kbps (depend of the video, WEBM container) and AAC, 128kbps (M4A container); for SoundCloud, it's MP3 128kbps and Opus 64 kbps; for Bandcamp, it's MP3 128kbps (you may get a better quality by doing the download process on the website, see [here](https://newpipe.net/blog/pinned/release/newpipe-0.21.0-released/#isso-1080) for more information).
I don't know about media.ccc.de and Peertube instances.

Note also without having a premium account for SoundCloud and YouTube, you can't get the highest qualities.
