### ISSUE TITLE
Minimum brightness during landscape playback on Samsung S8

### ISSUE THREAD

**Issue by theSusurrus** [TeamNewPipe/NewPipe#6291]
### Checklist
- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a youtube video on Samsung S8
2. Switch to fullscreen

### Actual behaviour

The screen brioghtness goes to the minimum value. Changing the brightness with the notification panel slider is no longer possible.

### Expected behavior

The brightness should stay at the previous level

### Screenshots/Screen recordings

The effect is not visible on screenshots and screen recordings, since the bug affects backlight brightness, not the video streams.

### Device info

 - Android version: Android 9, kernel 4.4.111-21427293 (Apr 6 19:35:29 KST 2021)
 - Device model: Samsung S8 (SM-G950F Baseband version G950FXXUCDUD1)

**Comment by avently** [comment]
Swipe left side of the video in landscape from bottom to top

**Comment by theSusurrus** [comment]
Wow, I didn't know this program hijacked the brightness controls. Perhaps it would be a good idea to introduce a warning at first startup. Or maybe such a warning exists and I didn't notice. Thanks for the clarification!

**Comment by avently** [comment]
You can disable gestures in settings if you want to
