### ISSUE TITLE
Time navigation 

### ISSUE THREAD

**Issue by Gowthamthiraviyam** [TeamNewPipe/NewPipe#6293]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by mhmdanas** [comment]
Please edit your issue to fill in the template properly.
