### ISSUE TITLE
Back button does nothing on Error Report page

### ISSUE THREAD

**Issue by cppcodeer** [TeamNewPipe/NewPipe#6298]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Disconnect network so that app won't be able to connect to the server.
2. Wait till loading finishes and click on Report button.
3. In Error report page click on back button in the navbar

### Actual behaviour

App does nothing.

### Expected behavior

App should get back to the last page before clicking on the Report button.

### Screenshots/Screen recordings

[Gif of the problem](https://bayanbox.ir/view/3001501061727106664/untitled.gif)
Sorry for jittering. My screen recorder was not able to properly record.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Google Pixel 3a

**Comment by ATofighi** [comment]
I will make a PR for this issue soon.
