### ISSUE TITLE
Move to a better place!

### ISSUE THREAD

**Issue by soheilkhanalipur** [TeamNewPipe/NewPipe#6299]
Unfortunately, I have to say that you have put this program in a bad place! GitHub!
This app deserves places like: Codeberg, Gitea, GitLab (Instances), and wherever better…
GitHub boycotts users, removes apps, and actually says "Whatever I want is going to be saved and whatever I don't need Is going to be deleted." The app has not paid attention to users' requests for RTL support for years, and says this is not a priority!
Free software should be free somewhere, which GitHub does not have!
Aren't these enough to leave GitHub?

**Comment by opusforlife2** [comment]
Hi Soheil. Please check out #1499 for a long discussion on this issue. You can read the existing comments and see if you want to add points there.

Also, we have an issue template that your 3rd party Github app is not respecting. In the future, please use the Github website to open an issue and follow the template.
