### ISSUE TITLE
0.9.10 - crashing device (Note 4 with Nobel (6.0.1) rom(6.0.1)

### ISSUE THREAD

**Issue by b1k3rdude** [TeamNewPipe/NewPipe#630]
Downloaded the 0.9.10 apk just now - 

1. Its not available on F-droid, so I assume this version is beta..?
2. upon changing the video from embedded to pop-out and then back to embedded, my phone crashed.

b.

**Comment by mauriciocolli** [comment]
> Its not available on F-droid, so I assume this version is beta..?

 F-Droid has a "delay" of 2-3 days for the build to appear (the build occurs in their servers).


> upon changing the video from embedded to pop-out and then back to embedded, my phone crashed.

Can you describe more about the second issue? Like what playback speed it was, what resolution, what kind of crash happened, etc.
