### ISSUE TITLE
Provide alternative cryptocurrency for donations (Ethereum, Cardano, Polkadot)

### ISSUE THREAD

**Issue by G-i-o** [TeamNewPipe/NewPipe#6304]
Thank You for providing this invaluable app for those who care about their privacy and opensource projects.

Thank You also for accepting (a) cryptocurrency for donations as it makes it much easier for some and also gives a choice to those who want to support alternative, somewhat more ethical, opensource and decentralized finance.

With this, I'd like to encourage you to add at least one or more cryptocurrencies. The reasons being the environmental issues and the relatively high costs annexed to BTC mining and, generally to all or most PoW coins. In particular, with BTC, there are elevated incentives to produce electronic devices (Asic miners) which are most times used for relatively short periods and then discarded with currently narrow changes of being used for other purposes.
As you may know, electronic devices contain highly polluting minerals and other materials that are very difficult to recycle and generally speaking are most often released into the environment one way or another. All this, setting aside the (real) mining of minerals which comes with associated abuse of human rights and further negative environmental impacts.

Also, given that we have mentioned privacy, there's also the issue of BTC transactions being fully public.

If I may, I'd like to suggest to add a (or more) PoS coin, such as Cardano, Polkadot, Ethereum (which will turn a PoS soon) and many more to mitigate the above mentioned environmental issues and a data-protection coin such as PIVX if you want also to offer the option of additional privacy to your donors. This can easily be achieved on your part by either having a multicoin wallet, such as Coinomi, Flits, AtomicWallet etc., or using a payment gateway, which usually offers FIAT conversion and other tools for merchants and organizations and have minimal charges (Usually around 0.5-1%).

Thank You for reading and considering and keep up for the good work. 🙏🏼

**Comment by Mhowser** [comment]
Basic Attention Token is a pretty good option as well. Its basically designed for this purpose.

**Comment by AudricV** [comment]
We do not provide anymore cryptocurrencies as a way for donations and we do not plan to change this for the time being. Closing this issue as won't fix.
