### ISSUE TITLE
Not showing NewPipe in App Chooser

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#6306]
### Checklist

- [x] I am using the latest version - v0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any description of any Youtube video ( I used Linus Tech Tips video)
2. Press on (if available )Youtube channel link (youtube.com/channelname)

### Actual behaviour

Doesn't show NewPipe in action chooser.(Figure below)

### Expected behavior

Must show NewPipe in application chooser for every youtube link clicked.

### Screenshots/Screen recordings

1. Description of Youtube video `https://www.youtube.com/watch?v=RUI1k-KHXNk`
![Capture2](https://user-images.githubusercontent.com/50160188/118349999-1189a800-b574-11eb-8955-274f50b56efa.PNG)

2. Action chooser when clicking the `Red marked` link [ Missing NewPipe ]. `Yellow Link`s are working fine.
![Capture](https://user-images.githubusercontent.com/50160188/118350015-29f9c280-b574-11eb-87d7-77ff92904797.PNG)

### Device info

 - Android version/Custom ROM version: 9.0 (Pie)
 - Device model: Huawei Nova 3i

**Comment by brnwlshubh** [comment]
It may be working due to "HTTPS".

**Comment by skyGtm** [comment]
Duplicate of #6184
