### ISSUE TITLE
trending video still loading 

### ISSUE THREAD

**Issue by devkhali** [TeamNewPipe/NewPipe#6315]
in first page no video    is still loading 
how it fixed ?
![WhatsApp Image 2021-05-16 at 22 00 17](https://user-images.githubusercontent.com/84289057/118412492-37a56a00-b692-11eb-9db7-108be902ec3a.jpeg)

**Comment by mhmdanas** [comment]
What are your NewPipe version, device, and Android version? Also, do you live in the EU or connect to EU servers using a VPN?

Also, please don't remove the template when opening an issue.

**Comment by devkhali** [comment]
im used version of code v0.20.11   but i want keep this version and i want fix only the issue loading video trending .  i want to guid me to numbre fixe it

**Comment by TiA4f8R** [comment]
You can't if you don't update to a newer version, it's a YouTube change. Closing.

**Comment by devkhali** [comment]
thank u  for your reply 
yes i know if i do update it fixed  . as im developer i want to know which part fixed to resolve this issue  which parte in java is modificate
