### ISSUE TITLE
Unable to view replies to comments

### ISSUE THREAD

**Issue by vrgovinda** [TeamNewPipe/NewPipe#6332]
Hello. Thanks for this amazing project. I have a small suggestion/complaint though.

In the comments section of every video, we are currently unable to see the replies to the comments. 

It'll be nice if we can have that small feature built-in. Else what is happening at least with me is that I have to go to the YouTube app just to see the updated comment and it's reply. 

Regards

**Comment by Disqu3-mirOir-qt** [comment]
the problem only for EU users i use my vpn switzerland and all fine , 

Freetube already patched

**Comment by vrgovinda** [comment]
But I am not in EU. I'm in India.
What should I do?

**Comment by skyGtm** [comment]
Duplicate: #6323

**Comment by skyGtm** [comment]
Duplicate: #2277

**Comment by vrgovinda** [comment]
Yes, I agree that this is a duplicate. But it would be great to see this
feature in NewPipe.

Thanks anyway.

Regards.
