### ISSUE TITLE
Large downloads (~>100mb) tend to keep "downloading" after completing 100%

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#634]
It usualy takes even longer than the download itself and 80% causes the UI not being rendered untill it's completely done.

**Comment by OffifialMITX** [comment]
Oh wait, it's open already, but I can't close the issue now.

**Comment by cwgt** [comment]
duplicate
https://github.com/TeamNewPipe/NewPipe/issues/602#issuecomment-312475449

@theScrabi please comment on this.
