### ISSUE TITLE
Add Disscussion page 

### ISSUE THREAD

**Issue by iamthesenate1** [TeamNewPipe/NewPipe#6341]
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Add the Disscusions page to the newpipe github page.

#### Is your feature request related to a problem? Please describe it

Some comments that are marked as off topic could be made as disscutions.

#### Additional context

This could also be applicable to controversial changes.

#### How will you/everyone benefit from this feature?

This should help to get more feedback from more people.

**Comment by mhmdanas** [comment]
Please keep the discussion in #5298.

**Comment by iamthesenate1** [comment]
> Please keep the discussion in #5298.

Sorry. Didn't have time to check and made this issue in a hurry.
