### ISSUE TITLE
Question about compatibility

### ISSUE THREAD

**Issue by itsagustinca** [TeamNewPipe/NewPipe#6344]
Hello, it is not to report an issue, I just want to ask, if NewPipe is compatible with X86 architecture (like a Chromebook)?

**Comment by itsagustinca** [comment]
I did not find any information on its compatibility and since much of the application is compiled in Java I thought it might be compatible with X86 architectures as I am considering buying a Chromebook.

**Comment by mhmdanas** [comment]
NewPipe uses no native libraries, so it should probably work on a Chromebook. However, I can't confirm that, as I have no Chromebook to test this on. Can anybody do that?

**Comment by skyGtm** [comment]
@itsagustinca I think Chromebook has PlayStore and it can install android apps. But NewPipe is not available in Playstore so, you may have to sideload "NewPipe.apk" file. But I don't know if it is possible to sideload app in Chromebook. For good help from the users of chromebook, you might wanna ask questions in reddit.com/r/chromebook/ or google search "How to sideload apk files in chromebook" or "how to install android apps in Chromebook".


@opusforlife2 I think this answers the question. maybe worth closing this issue.

**Comment by opusforlife2** [comment]
Let's wait for the user to confirm or deny that this works?

@itsagustinca Please get back to us with whether or not you found a way to make it work, so that other users searching for a solution can read it, and then we'll close this issue.

**Comment by itsagustinca** [comment]
I close the issue, in the end I didn't buy the Chromebook, I bought a Chromecast with Google TV, anyway thanks.
