### ISSUE TITLE
fast forward instead of next

### ISSUE THREAD

**Issue by NESC1US** [TeamNewPipe/NewPipe#6349]
hi!
i like to listen to long videos and would prefer nmultimedia buttons on my bluetooth for next and back to only seek forwards or backwards instead of stating again from start in a 4 hours lecture.

**Comment by MapleWheels** [comment]
This is already an option under Settings -> Notifications. Just change the option buttons for 2 and 3. I've done it on my end for when I'm on the road (car BT).

**Comment by mhmdanas** [comment]
It's as @MapleWheels says. If this didn't fix the issue for you, please make a comment and I'll try to help. Also, please don't remove the template when you open an issue. Thanks!

**Comment by NESC1US** [comment]
it works! but i an sure this was not there somewhat recently, thanks a lot!

**Comment by NESC1US** [comment]
thanks, i tested this, but it doesn't work - i set those as rewind and fast forward, but when i try to use it, it always only triggers previous/next.

**Comment by mhmdanas** [comment]
Can you send a screenshot of the notifications page in the settings where you configure the buttons?

**Comment by NESC1US** [comment]
> Can you send a screenshot of the notifications page in the settings where you configure the buttons?
![1024-2048](https://user-images.githubusercontent.com/15976294/133887719-53ef067e-4479-4989-aed7-f9aac534585e.png)

**Comment by mhmdanas** [comment]
Ah, I think I got you now. That feature has not been implemented yet; see #3027.
