### ISSUE TITLE
Trying to use popup on Android TV crashes the app.

### ISSUE THREAD

**Issue by OtBe21666** [TeamNewPipe/NewPipe#635]
I know were not supposed to report crashes here, but I don't have an email client installed on the Shield to send the crash report in! Everything else, including background play, functions as it should. Thanks for an otherwise amazing app, looking forward to future builds!

**Comment by theScrabi** [comment]
I guess the reason for popup to crash on android tv might be that android tv might not be supposed to support pop up.

**Comment by mauriciocolli** [comment]
You can use the share button (the button on the top-right) and then copy from some other app.

**Comment by OtBe21666** [comment]
iYTBP & several other apps support PIP/Pop up playback on Android TV, so that theory isn't very sound.

**Comment by OtBe21666** [comment]
iYTBP & several other apps support PIP on Android TV, so that theory isn't very sound.

**Comment by mauriciocolli** [comment]
@OtBe21666 read my previous post.

**Comment by sorryusernameisalreadytaken** [comment]
It worked and does not crash on my AndroidTV device with this build here:
https://github.com/TeamNewPipe/NewPipe/pull/2806#issuecomment-598957705

I am not able control the popup window with dpad but it worked.
![screen_newpipe_pictureInPicture](https://user-images.githubusercontent.com/12913436/77245988-58576880-6c23-11ea-8539-ee74db9ce650.png)

**Info**: You need to aloud this app manually to the list of apps with overlay features.

**Comment by agosto-levitomes** [comment]
I see the same behavior as @sorryusernameisalreadytaken/ with correct permissions pop up works on a 2025 shield.

**Comment by Stypox** [comment]
That pr (#2806) was merged and this should have been fixed
