### ISSUE TITLE
Car bluetooth play  cause newpipe freeze

### ISSUE THREAD

**Issue by snowzhangy** [TeamNewPipe/NewPipe#6352]
I love using newpipe to listen videos while driving. But everytime when i turn off my car or switch audio device. The newpipe background player also freeze.
I cannt click play or restart. I have to switch to main video ui and find which clip i am listensing and restart play , switch to background.
I really hope this only bug for me been fixed. Thank you

**Comment by litetex** [comment]
@snowzhangy 

Please fill out the issue template accordingly.
