### ISSUE TITLE
Jumps to beggining of media

### ISSUE THREAD

**Issue by invinciblevenom** [TeamNewPipe/NewPipe#6355]
When I switch to Background Play in middle while watching a video, many times it starts playing from the very beginning. Can't take any logs for same
Using NewPipe v0.21.2 on Android 11

**Comment by SameenAhnaf** [comment]
Well, the bug is not consistent. Sometimes, the videos play just as expected. Sometimes, from a couple of seconds ago and sometimes from the beginning.


https://user-images.githubusercontent.com/79245641/119252587-f6034a80-bbce-11eb-8333-5bcb8f76da1b.mp4

**Comment by invinciblevenom** [comment]
> 
> 
> Well, the bug is not consistent. Sometimes, the videos play just as expected. Sometimes, from a couple of seconds ago and sometimes from the beginning.
> Screenrecorder-2021-05-23-13-53-08-173.mp4

Yes it isn't consistent. Thanks for the screen record this will surely help the developers.

**Comment by ShrimpBFM** [comment]
Be it in normal, pop-up or background play, pausing a video makes it un-resumeable and changing between these methods makes videos start from the beginning again.
