### ISSUE TITLE
I was wondering if it would be possible  to add the abillity to search  via long time vs short time.

### ISSUE THREAD

**Issue by smartieyoung** [TeamNewPipe/NewPipe#6362]
i was hoping we could get a sort feature that is like by how long the file is short vs long time.0
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
-[ x] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by TiA4f8R** [comment]
Please fill the template properly and edit your issue. Closing until it's done.
