### ISSUE TITLE
Add option to see full comment text, without tap

### ISSUE THREAD

**Issue by vitaly-zdanevich** [TeamNewPipe/NewPipe#6367]
I tired to tap to read full text. Looks like [I am not alone at this](https://www.reddit.com/r/NewPipe/comments/njsp56/tired_to_tap_to_every_comment_to_see_it_full).

**Comment by TiA4f8R** [comment]
Please don't remove the template when opening an issue. Closing. I will reopen the issue when the body of your issue will follow the feature request template.

**Comment by vitaly-zdanevich** [comment]
Done https://github.com/TeamNewPipe/NewPipe/issues/6370

**Comment by vitaly-zdanevich** [comment]
Oops I needed to edit this issue, sorry.

**Comment by TiA4f8R** [comment]
Don't worry about that.
