### ISSUE TITLE
License fraud?

### ISSUE THREAD

**Issue by gsantner** [TeamNewPipe/NewPipe#638]
This may be worth a look. Just pasting:

* https://codecanyon.net/item/tubemate-video-downloader/19278162?s_rank=18
* https://codecanyon.net/item/tubemate-video-downloader/screenshots/19278162

@theScrabi  @BlenderViking  @TheAssassin

**Comment by theScrabi** [comment]
G** d*** thanks. This Tubmate thing is spamming into our but report system.  But we couldn't find it. Here we go thanks.

**Comment by TheAssassin** [comment]
Yeah, we had to take measures like DNS changes etc. to get rid of the majority of the mails sent by Tubemate users.

If you can find more of those, please let us know. This kind of contribution is highly appreciated.

I can compile a list of Java package names of (suspected) forks which violate our license. We still receive such mails of others, and there's not really anything we can do about it but sort them out by hand in our stacktrace aggregator.

P.S.: we get notified by GitHub anyway.

**Comment by gsantner** [comment]
maybe do a search on the plattform for more youtube stuff

Am 25. Juli 2017 10:46:28 MESZ schrieb Christian Schabesberger <notifications@github.com>:
>G** d*** thanks. This Tubmate thing is spamming into our but report
>system.  But we couldn't find it. Here we go thanks.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TeamNewPipe/NewPipe/issues/638#issuecomment-317671638

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gsantner** [comment]
![gnome-shell-screenshot-cv5n3y](https://user-images.githubusercontent.com/6735650/28635041-7ee7be32-7239-11e7-91ef-dc170e3c2736.png)

there the comment goes :D

btw: one of my apps was there too. had to send a DCMA to the support and then it was removed about an hour later

**Comment by theScrabi** [comment]
All right :) thanks for the comment.

**Comment by mauriciocolli** [comment]
> This item is no longer available

@theScrabi did you filed a DCMA too?
If not, I think they finally reviewed that comment (the one @gsantner post previously).

**Comment by TheAssassin** [comment]
@mauriciocolli and @gsantner: It's called a "DMCA takedown notice", the law is called Digital Millennium Copyright Act. When it comes to legal stuff, you should make sure your terminology is correct.

**Comment by wb9688** [comment]
Isn't DMCA America-only?

**Comment by TheAssassin** [comment]
You have to file such requests/notices in the country the server is located in. That means you have to use the legal measures available in that country. As @gsantner implied, the server is located in the USA. I have to admit I have not checked that, I only corrected the wrong terminology.

**Comment by wb9688** [comment]
@TheAssassin: Doesn't a company need to comply with the laws from all the
countries they're active? Wouldn't in this case they be active in all the
countries in their country list in their checkout page (starting with
Afghanistan and ending with Åland Islands)? Btw have you studied laws or
something? I've just noticed you're always reacting to law-ish (is that a
word?) things here.

**Comment by TheAssassin** [comment]
No, I have not studied anything law-ish. As a system administrator, internet person and privacy/data protection advocate, I have a lot of experience and knowledge about law and jurisdictions. I do a lot of research on topics I am interested in anyway.

Technically you're right, but that can get quite difficult and expensive, except for some edge cases. It is generally safer to file a complaint in the company's jurisdiction, as for the home state it is easier to actually enforce the law. Think of, how would a country in the European Union properly enforce their law in, say, south america? If there is no treaty regulating the details of law enforcement of foreign jurisdictions, you have no chance. And even if there is, you can't go into another country and say "hey, you've been sued in my country and I've won, give me your car" or something. That just doesn't work.

(In the EU, it's generally possible to sue someone in another member state, usually they accept the verdict, and if not, there's institutions like the ECJ which negotiate afterwards. The EU is anyway interested in harmonizing the jurisdictions, so stuff gets more and more common anyway.)

I'd say, send them a DMCA takedown notice, and if they don't react, go ask a real lawyer about options. That's probably the safest approach.

**Comment by gsantner** [comment]
Maybe take also a look at the codester plattform <https://www.codester.com/items/4097/meme-generator-android-app-source-code> . I got the message by community that one of my gpl apps is there too.

**Comment by wb9688** [comment]
Btw couldn't this issue be closed now that that TubeMate is down?

**Comment by TheAssassin** [comment]
@wb9688:

> I can compile a list of Java package names of (suspected) forks which violate our license. We still receive such mails of others, and there's not really anything we can do about it but sort them out by hand in our stacktrace aggregator.

We have tons of forks of which we presume that they violate the terms of the GPL.

**Comment by wb9688** [comment]
Right, I thought this issue was just about this specific one.

**Comment by theScrabi** [comment]
@mauriciocolli I didn't do anything. I guess the comment did it already.

@gsantner you created memetastic? Lol, I love your app.

@wb9688 there is a thead for copycats so we dont need this thread here. However I should not call it copycats but Licence froud(s).

**Comment by TheAssassin** [comment]
@theScrabi then please link to the other thread, and close the issue as a duplicate.

**Comment by theScrabi** [comment]
#539
