### ISSUE TITLE
License fraud?

### ISSUE THREAD

**Issue by vanitasvitae** [TeamNewPipe/NewPipe#639]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hi! While searching for copyright infringing copies of my apps, I stumbled across an app that looks like a rip-off of NewPipe: 
https://codecanyon.net/item/tubemate-video-downloader/19278162?s_rank=18

I thought this might interest you, since all references to you and your team were removed from that app and it's also apparently sold for money.

That site has a whole bunch of Android apps and this is not the first stolen app I found, so everybody might want to take a look :)

**Comment by gsantner** [comment]
#638 :D

**Comment by pboulerie** [comment]
By the way, please note that there is already another thread about how to :
- Handle Copycats (License fraud)
https://github.com/TeamNewPipe/NewPipe/issues/539
