### ISSUE TITLE
Add YouTube homepage like Pure Tuber on Play store

### ISSUE THREAD

**Issue by quoctrungdhqn** [TeamNewPipe/NewPipe#6395]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
*I think it would be nice if you add feature like YouTube homepage same as this app: https://play.google.com/store/apps/details?id=free.tube.premium.advanced.tuber*

#### Is your feature request related to a problem? Please describe it

*No*

#### Additional context

*No*

#### How will you/everyone benefit from this feature?

*This feature will help us fetch more videos and stay the app much more time. Only show trending videos make a poor experience for users.*

**Comment by mhmdanas** [comment]
Can you explicitly describe what you'd like to be added? Giving a screenshot from YouTube of what you'd like to be added with an explanation would be very helpful.

**Comment by quoctrungdhqn** [comment]
You can install that app (Pure Tuber) and check the home page, you will see that feature.
It like a home page of a YouTube app, show a list of random videos.

**Comment by Ammako** [comment]
> You can install that app

No thanks

You could just take a screenshot and add it in a reply here

**Comment by KatoriYuu** [comment]
@mhmdanas @Ammako I've just tried it. This would make the experience with Newpipe even closer to the original Youtube app. Pure Tuber seems to be a fork of Newpipe, so I think adding this feature is possible.
![Screenshot_20210612-120843](https://user-images.githubusercontent.com/42930110/121765877-4b9c9880-cb78-11eb-8fb4-fa91476c8e90.png)

**Comment by Ammako** [comment]
> Pure Tuber seems to be a fork of Newpipe

Interesting. Where's the source code?

**Comment by Ammako** [comment]
Also https://github.com/TeamNewPipe/NewPipe/issues/2256

**Comment by KatoriYuu** [comment]
@Ammako Sorry I can't find the source code anywhere. I just perceived that there were some similarities between them (especially the UI). I can give you the link in case you want to have a look: http://play.google.com/store/apps/details?id=free.tube.premium.advanced.tuber

**Comment by Ammako** [comment]
No need to be sorry, it's just that *if* it's a fork of NewPipe, then they are breaking GPL in several ways.

I'm a bit skeptical about it being a NewPipe fork though, but without installing it and playing around with it to get a feel for it, I can't really say for certain.

**Comment by jechaviz** [comment]
I think sky-tube has the same request as this because thumbnails are as wide as screen width., instead of the current 2 column layout of thumbnails (they are too small).

Skytube is using as base newpipe code as far as I know.
https://github.com/SkyTubeTeam/SkyTube

Thank you.

**Comment by mhmdanas** [comment]
> Skytube is using as base newpipe code as far as I know.

To be clear, SkyTube uses [NewPipeExtractor](https://github.com/teamnewpipe/newpipe) as a backend, as does NewPipe. The actual apps' UI code is not related as far as I know.

**Comment by SameenAhnaf** [comment]
@Stypox https://github.com/TeamNewPipe/NewPipe/issues/8266#issuecomment-1104006793 applies here too, right?

**Comment by Stypox** [comment]
Yes, it does, thank you. @quoctrungdhqn you can ask for a spefic piece of UI to be changed giving some reasons why; you can't ask the whole UI to be adapted to a different way to use the app. Btw, I am pretty sure there is already an open issue about not putting Trending by default in the home screen (which if you didn't know can be changed from settings)

**Comment by opusforlife2** [comment]
So... close it, @Stypox.
