### ISSUE TITLE
Automatically updates Newpipe Debug from the repository.

### ISSUE THREAD

**Issue by Drakesdrs** [TeamNewPipe/NewPipe#6399]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
A feature which simply downloads the archive file from the actions page and automatically updates the NewPipe Debug app when a commit was pushed to main

Optionally, also describe alternatives you've considered.
It could simply just make a popup notification to download the latest Debug build but that is not what I am asking.

#### Is your feature request related to a problem? Please describe it

no

#### How will you/everyone benefit from this feature?

People will be able to test the debug builds for errors before it updates for everyone else, without manually downloading from actions page.

**Comment by AudricV** [comment]
Updating NewPipe debug versions is not planned. However, [NewPipe Nightly](https://github.com/TeamNewPipe/NewPipe-nightly/) with an app store which is able to install automatically updates on an Android 12 and higher device would be probably able to achieve the goal you want once TeamNewPipe/NewPipe-nightly#2 is resolved.

Closing as wontfix.
