### ISSUE TITLE
All types of age-gated videos don't get loaded

### ISSUE THREAD

**Issue by OhMyLove666** [TeamNewPipe/NewPipe#6403]
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Link:https://www.youtube.com/watch?v=61i0AoRh5Ws

### Actual behaviour

Only, specific age-restricted videos don't load.

### Expected behavior

All types of videos should load normally.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=61i0AoRh5Ws
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.21.3
* __OS:__ Linux Redmi/begonia/begonia:10/QP1A.190711.020/V12.0.7.0.QGGMIXM:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.AgeRestrictedContentException: This age-restricted video cannot be watched.
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:759)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: MIUI 12, Android 10
 - Device model: Xiaomi Redmi Note 9

**Comment by opusforlife2** [comment]
Confirmed, at least with the provided video link.

But I tried several other NSFW videos and they all open. So the criterion for this error seems to be more specific than just "18+".

Could you find more of such videos so we can narrow it down further, @OhMyLove666?

**Comment by OhMyLove666** [comment]
I am not sure about the bug but all age-gated videos from this channel don't load properly. Note that only latest three videos are age-gated, others are not.

https://www.youtube.com/channel/UCWUQQ1LsNMBRpcTjcbCIH6Q

**Comment by opusforlife2** [comment]
Found more. Several videos on this channel show this error: https://www.youtube.com/channel/UCBE3huCQcUOd-G2jHAr8emQ

Though all of them seem to be NSFW, some videos do open. If you turn off the age-restricted content setting, then more of them show the same error.

**Comment by mobd** [comment]
This age-restricted video on a safe channel also doesn't work for me: https://m.youtube.com/watch?v=Fiu9GSOmt8E

**Comment by opusforlife2** [comment]
@mobd That video opens fine for me. Sure your age restriction setting is on?

**Comment by Symbian9** [comment]
> > I am not sure about the bug but all age-gated videos from this channel don't load properly.
>
> That video opens fine for me. Sure your age restriction setting is on?

It's may be affected by EU-specific issue; see `youtube-dl`'s issue https://github.com/ytdl-org/youtube-dl/issues/28578

- https://news.ycombinator.com/item?id=27353917#27359776

**Comment by opusforlife2** [comment]
If there are multiple 'levels' of age restriction, then Newpipe should be aware of them, at least. Whether or not it is able to extract every such stream is secondary. But there should definitely be different error messages.

**Comment by AndnixSH** [comment]
Damn. Even connecting to US VPN no longer works on Newpipe and  Youtube app still asking for verification.it seems Google is detecting VPN now

Log if you are curious

`{"user_action":"requested stream","request":"(removed)","content_language":"da-DK","content_country":"DK","app_language":"da_DK","service":"YouTube","package":"org.schabi.newpipe","version":"0.21.5","os":"Linux motorola/nairo_retaile/nairo:11/RPN31.Q4U-39-27-5/20ead:user/release-keys 11 - 30","time":"2021-06-18 10:31","exceptions":["java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference\n\tat java.io.StringReader.<init>(StringReader.java:50)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:6)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchVideoInfoPage(YoutubeStreamExtractor.java:802)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:731)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:923)\n"],"user_comment":""} `

**Comment by SameenAhnaf** [comment]
@AndnixSH Change the VPN server and check. Also, keep the discussion related to this issue only.

**Comment by AndnixSH** [comment]
@SameenAhnaf I am talking about this issue, excatly #6514. that's what i'm getting when trying to play age restricted videos, and using VPN no longer works no matter what non-EU servers I have choosen.

I'm sure they recently make changes which is affecting all apps and extension which is bypasses age restriction, like this Tampermonkey script https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/18

**Comment by Para-lyzed** [comment]
I can confirm that I am experiencing this issue with the show age-restricted content setting on for the following videos. I am not able to load either video on a VPN, or on a native connection in the US, so at the very least, this does not seem to be entirely related to EU. I am running a fresh install of the latest version (reinstalled to troubleshoot). Note that while the age-restrictions on the videos I linked were requested by the uploader, there are other videos in this thread that were not, so it does not seem to be specific to an uploader requested age-restriction.

https://www.youtube.com/watch?v=le4DvQCrNF0
https://www.youtube.com/watch?v=bf7swGfhdZg

**Comment by OhMyLove666** [comment]
@AndnixSH Wait. Do only age-gated videos cause problems on VPN? I am having issues with only a number of age-gated videos and only they don't load regardless of the VPN I use.

**Comment by Para-lyzed** [comment]
> Wait. Do only age-gated videos cause problems on VPN? I am having issues with only a number of age-gated videos and only they don't load regardless of the VPN I use.

@OhMyLove666 Not as far as I can tell. I experience the same issue whether I'm using a VPN or not. I live in the US, so I can also confirm it isn't an issue specific to the EU as was mentioned earlier.

**Comment by zerodytrash** [comment]
For videos that are embeddable, the following parameters on the `/get_video_info`  endpoint seem to help at the moment: `&c=TVHTML5&cver=7.20190319`

Example-Video: https://www.youtube.com/watch?v=Fiu9GSOmt8E
=> https://www.youtube.com/get_video_info?html5=1&video_id=Fiu9GSOmt8E&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FFiu9GSOmt8E&c=TVHTML5&cver=7.20190319
=> playabilityStatus: OK

Tested from EU, with and without login.

**Comment by opusforlife2** [comment]
Interesting update: Now all videos except one from the channel link in my comment here https://github.com/TeamNewPipe/NewPipe/issues/6403#issuecomment-851858414 refuse to open. Something changed in the meanwhile.

**Comment by awasay905** [comment]
Is there any hope for this problem to be solved?

**Comment by scifirenegade** [comment]
This is something to do with Google asking for ids, because the EU went full "think of the children" mode. Maybe using a VPN may help?

**Comment by Para-lyzed** [comment]
@scifirenegade US user here. I still experience this issue whether I use a VPN or not, regardless of where in the world the VPN is from (tried all sorts of countries, and yes, that includes multiple states in the US). As such, it is not localized to the EU, though it seems to have been caused by the EU's new policies.

**Comment by mitomenai** [comment]
Same. I believe they deployed the changes worldwide a few days ago. All age gate bypass websites are now broken as well.

EU might be partially responsible, but I do also suspect it's just another step in locking down videos behind a login. Google's making good on their promise to ban accounts that are not "commercially viable".

**Comment by scifirenegade** [comment]
Google now requires your phone number to created new accounts. And the alternative is giving them your ID.
So much for user datat protection. Well done EU...

**Comment by coderkei** [comment]
Any reason why this issue was suddenly closed without any reason?
