### ISSUE TITLE
Prettytime update

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#6404]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Prettytime update to 5.0.1.Final 

#### How will you/everyone benefit from this feature?

People will benefit from this update by getting the latest localizations and features

**Comment by iamthesenate1** [comment]
I would like this merged ASAP because it fixes #5085

**Comment by mhmdanas** [comment]
I'll open a PR for this.
