### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#641]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I was listening (with the background player) to a song on YouTube. Then the crash reporter told me about some array out of bounds error in the notification, so I tried playing that song again. It crashed my phone and my phone fast rebooted, so I couldn't report it with the built-in crash reporter.

**Comment by mauriciocolli** [comment]
@wb9688 can you send the link of this video? Maybe some very specific thing is causing this.

**Comment by wb9688** [comment]
@mauriciocolli: Well, I don't remember what song it was. I've listened many times to that song though. But NewPipe just shouldn't cause my phone to fast reboot. Btw my phone is a Huawei ALE-L21 (P8lite) running EMUI 4.0.3 (Android 6.0).

**Comment by TheAssassin** [comment]
@wb9688 you might want to check for similar issues on Sentry.

**Comment by kdulep** [comment]
My ASUS selfie phone Android 6  recently sometimes get rebooted on youtube ASMR video [https://youtu.be/RVod4B_r2Yk](url)
