### ISSUE TITLE
[Bandcamp] when trying to seek with seekbar, track restarts

### ISSUE THREAD

**Issue by 5lttrz** [TeamNewPipe/NewPipe#6417]
### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Bandcamp in Newpipe'
2. Press on 'any track'
3. Press play
4. Slider bar cannot be moved and if we try to move forward or backward into a song it restarts at 00:00. Also, the total time duration of the song shows up as 00:00.

### Actual behaviour

Restarts the song when slider is moved.

### Expected behavior

Expected to move forward and backward into the song when the slider bar is moved.

### Screenshots/Screen recordings

![Screenshot_20210603-100528_NewPipe.png](https://user-images.githubusercontent.com/75839799/120588240-8013a480-c454-11eb-92f4-1867b966494f.png)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung Galaxy M21

**Comment by 5lttrz** [comment]
Still not fixed in 0.21.4

**Comment by opusforlife2** [comment]
That's because no one's fixed it yet.

A better way to communicate that it's still present in the latest version is to bump the version number in your issue description. I've done it for you this time.
