### ISSUE TITLE
Many Bandcamp playlists not visible

### ISSUE THREAD

**Issue by iAmAGitUser5** [TeamNewPipe/NewPipe#6418]
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Bandcamp
2. Press on any channel/artist
3. Check for albums/playlists visible in their actual Bandcamp vs Playlists visible in Newpipe.

### Actual behaviour

Many playlists do not show up, even though the artists have many more playlists in their Bandcamp

### Expected behavior

All playlists should be visible.

### Screenshots/Screen recordings

![Screenshot_20210531-145206_NewPipe.png](https://user-images.githubusercontent.com/75839799/120593240-cf5dd300-c45c-11eb-87e4-929bb3c1c7c0.png)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung Galaxy M21

**Comment by ChunkyProgrammer** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/issues/585

**Comment by 5lttrz** [comment]
> https://github.com/TeamNewPipe/NewPipeExtractor/issues/585

Its been over a year since the fork, any updates yet on when it'll be added?

**Comment by AudricV** [comment]
This should have been fixed with the introduction of channel tabs in 0.26.0, therefore I am closing this issue. Please comment if that's not the case and I will reopen this issue. Thank you.
