### ISSUE TITLE
Battery Drain

### ISSUE THREAD

**Issue by BeshoyMagdy99** [TeamNewPipe/NewPipe#6422]
Newpipe consumes a lot of battery in a short time, the latest update has solved all the problems, but it has not solved it.

### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Screenshots/Screen recordings

![IMG_20210602_072719](https://user-images.githubusercontent.com/85212846/120774919-072f4e00-c523-11eb-80c4-c6f964b6fc7e.jpg)

### Device info

 - Android version/Custom ROM version: miui global 12.0.10
 - Device model: xiaomi redmi note 10

**Comment by mhmdanas** [comment]
Assuming you were watching videos in those 7 minutes, if you compare it to the YouTube app below, it sounds about the same. If you were indeed watching videos, then that battery usage is expected, but if you were just navigating around the app, then this could indeed be a bug. Can you confirm which is the case?

**Comment by BeshoyMagdy99** [comment]
I was listen to music in the background and the reason for this short period every time I use Newpipe I find the battery draining and

**Comment by BeshoyMagdy99** [comment]
No, what I was doing was listening to music in the background The reason for this small period of use is that every time I use the app, I find a huge drain on the battery, even after each update, so I stop using it again.

**Comment by opusforlife2** [comment]
> This issue was closed.

Well that's new. Why two closing events? One by ghost and one by the universe?
