### ISSUE TITLE
Buffering while playing videos

### ISSUE THREAD

**Issue by Slicer32** [TeamNewPipe/NewPipe#6425]
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

The problem of buffering while playing videos using wifi ..other apps like Youtube works fine..it sometimes occur and other times it is fine.. the problem both occurs in full view mode and pip mode. To an extent, it buffers, plays for a few seconds and buffers again.

### Expected behavior

I expect the app to be smooth  as using wifi does not hinder the YouTube app. Besides the buffering im loving this app..better features and lightweight than You tube...keep up the good work!

### Device info

 - Android version/Custom ROM version: stock android 9(pie)
 - Device model: Asus ZenFone Max Pro M2

**Comment by nzimas** [comment]
I can confirm this report. 
The app is practically unusable at this point.
Buffering happens regardless of the type of internet connection.

**Comment by mhmdanas** [comment]
Could you both check if this issue is also present on the YouTube website (NOT the app)?

**Comment by Slicer32** [comment]
So far the YouTube (website not app) is fine, no buffering that i have experienced

**Comment by SmoothJaz** [comment]
I can also confirm this issue. I've actually had it since the previous version but couldn't work out how to correctly report it. Videos will buffer every few seconds regardless of mobile data or wifi connections. The same videos work fine because I often have to resort to the YouTube app to watch the videos

**Comment by XNUConner** [comment]
Can confirm this issue as well, have had this happen for a few weeks now sporadically. Videos will play but stop, buffer for a second, then resume. The only solution I've found is to wait a few hours and try again or lower the resolution below 480p. Its become so common that I've been using the website in the meantime.

Xiaomi Redmi Note 9S
Android 11

**Comment by castrik** [comment]
happening to me as well, gigabit connection and I can watch at 8k 60fps no buffer in web browser or even 4k on youtube app, but seeing buffer on newpipe on 480p and above

Samsung S21 ultra
Android 11

**Comment by mhmdanas** [comment]
Do you live in the EU or use a VPN that connects to the EU? If so, it might be #5977. Not confident about this, but it's worth asking.

**Comment by SmoothJaz** [comment]
> Do you live in the EU or use a VPN that connects to the EU? If so, it might be #5977. Not confident about this, but it's worth asking.

No, Australian with no VPN running

**Comment by bibin-v2020** [comment]
Same for me. It's not there for all videos but for some. I'm from India (no VPN). Now a day's it's happening to often.

**Comment by opusforlife2** [comment]
This is a hunch, but could all of you try TeamNewpipe/NewpipeExtractor#604. There is a further link to the actual test APK in the top comment.

**Comment by SmoothJaz** [comment]
> This is a hunch, but could all of you try [TeamNewPipe/NewPipeExtractor#604](https://github.com/TeamNewPipe/NewPipeExtractor/pull/604). There is a further link to the actual test APK in the top comment.

if i could work out how to do this i would love to try and help! I'm a lowly end user here to provide feedback and dont really have much knowledge on how to navigate and understand this site

i tried following that link, and another link that said to "see the checks for the APK" (over at https://github.com/TiA4f8R/NewPipe/pull/3/checks ) But wasnt able to find an APK to download. If you could link me directly id be happy to download the apk or whatever and daily drive it a bit to see how the results go, however.

**Comment by opusforlife2** [comment]
@SmoothJaz Artifacts on the top right. You can download from there.

**Comment by SmoothJaz** [comment]
@opusforlife2 aha! Thanks, from the initial get-go it seems to not have the same issue, and all the videos im trying right now seem to be playing fine. I'll continue using it for a while and see if i come across the issue. I'd like some others having this problem to also give the apk a trial run and see how they go too

**Comment by SmoothJaz** [comment]
So, I just came across the issue again on the other apk from https://github.com/TiA4f8R/NewPipe/pull/3/checks

Constant buffer pausing every second or so, tried on different networks and problem still persists

Anyone got a way I can attempt to debug the network traffic or something to see what's causing this issue?

**Comment by bibin-v2020** [comment]
tested this apk (https://github.com/TiA4f8R/NewPipe/pull/3/checks) for some hours, till now no buffer issue reported... Let's see

**Comment by TiA4f8R** [comment]
Note that we (ExoPlayer I think) are not fetching video and audio ranges with the same way as YouTube (which make a range request to the video/audio stream with `range`, `rbuf`, and `rn` params append to the base streaming URL): the app fetches range requests with the `Range` header (using `Range: bytes=start-end` in the GET request). It may explain the issue.

**Comment by Slicer32** [comment]
Hello guys, here is the example of the video buffering.

https://user-images.githubusercontent.com/85346554/120968937-22f15900-c79c-11eb-8841-3b45d972c649.mp4

**Comment by Flam3z** [comment]
Can also confirm, all my other apps just require internet work fine but NP bufferd videos out of nowhere.

Galaxy S10 
Version 0.21.3

**Comment by TobiGr** [comment]
Please test the APK from #6444 and tell us whether the problem is gone.

**Comment by snsgnq** [comment]
Hi, I have this issue since a few days as well. This does not happen on all channels though! On some channels, their videos are loading quick, like 5mbps and some channels they go 200kbps, which makes videos unplayable.

**Comment by opusforlife2** [comment]
@snsgnq Please try the linked APK.

**Comment by snsgnq** [comment]
> @snsgnq Please try the linked APK.

Will do, thanks!
Just trying collaborate on what hasn't been said yet, as far as I've read. Also, WiFi or 4G doesn't make a difference for me.

**Comment by opusforlife2** [comment]
Guys, the linked PR didn't actually fix the issue. But we have a new PR for you to try: #6524. Please test this and tell us if the buffering problem is solved for you.

The more people test and confirm it works, the more confident we can be about the proposed solution.
