### ISSUE TITLE
adding music from youtube to newpipe cancels out current song

### ISSUE THREAD

**Issue by cuilean** [TeamNewPipe/NewPipe#6427]
before when i would add a song to newpipe through the share feature on youtube, it create a playlist, playing the song after the one i was listening to at the time. now for at least the 4 new updates it cuts off the song i'm currently listening to and immediately plays the song i wanted newpipe to play after the first one.

**Comment by mhmdanas** [comment]
See #4779:
> Until newPipe 0.20.2, while playing a video in background or pop-up mode, sharing another video from others apps to newPipe would enqueue them directly. However this is changing in the upcoming release because it was determined to be bad UX #4562.

Also, please don't remove the template when opening an issue.
