### ISSUE TITLE
Replace the System.exit calls with getActivity.finishAffinity()

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#6428]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
From https://github.com/TeamNewPipe/NewPipe/pull/6402#issuecomment-852970989
> could we take the opportunity and replace the System.exit calls with getActivity.finishAffinity() and launch of the main activity?
>so
>System.exit(0);
>to
>`getActivity().finishAffinity();
>startActivity(getActivity().getPackageManager().getLaunchIntentForPackage(getActivity().getPackageName()));

#### Is your feature request related to a problem? Please describe it

 I don't know, @Redirion Whats the upside if this?

#### Additional context

- Replace here https://github.com/TeamNewPipe/NewPipe/blob/332b90d6c18b52bc671271ec7589c072b71ff785/app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java#L273

#### Testcriteria
(for whoever picks this up)
- Settings are still loaded correctly after importing them

**Comment by Redirion** [comment]
System.exit kills the app and the Android OS will try to restart it. This is similar to an FATAL Exception. A FATAL Exception is of course not desired and should be an "Exception" and no normal operation to reload the app.

FInishing the app with finishAffinity will give the app the opportunity to gracefully shut down as the usual lifecycle methods onStop / onDestroy and so on will be called to stop things such as backgroundplayback and free resources.

**Comment by XiangRongLin** [comment]
@Redirion Am i correct in my assesment, that it should be an easy issue for newcomers?

**Comment by opusforlife2** [comment]
> XiangRongLin added good first issue and removed good first issue labels 

How the hell did you manage that? xD

**Comment by danielmbutler** [comment]
Hi Guys, I would like to help out on this one, I also found another System.Exit call in the below file, do you want this changing also?

src/main/java/org/schabi/newpipe/ExitActivity.java
line 51

**Comment by XiangRongLin** [comment]
I don't know what that activity does. If the reasoning from Redirion also applies there then you can do that.

**Comment by danielmbutler** [comment]
Thanks Xiang, the ExitActivity is called from the PanicResponderActivity class and there are comments in there that mention restarting the app so I believe the same reasoning applies here.

**Comment by Stypox** [comment]
> This solution works 99% of cases. However, it will not destroy the process, so for example Dagger will not be cleared. In those rare cases, where killing the process is required, System.exit(0) is the only solution that worked for me. – Slav Jun 27 '18 at 13:53

> In addition to `@Slav` answer I can add that in using Koin you will also see this problem. Even when you use finishAndRemoveTask - it will still keep the instances in the memory after reopening the app. finishAffinity + System.exit(0) help me – Edgar Khimich Jul 22 '19 at 20:25

Are we sure these two comments from [this SO answer](https://stackoverflow.com/a/27765687/9481500) do not affect us?

**Comment by Redirion** [comment]
do we use an dependency injection framework in NewPipe?

**Comment by XiangRongLin** [comment]
> 
> 
> do we use an dependency injection framework in NewPipe?

Nope

**Comment by Redirion** [comment]
then I would say the two comments do not affect us

**Comment by Stypox** [comment]
Ok, great
