### ISSUE TITLE
[Request] Option to autoplay in background when started from another app

### ISSUE THREAD

**Issue by bytegeist** [TeamNewPipe/NewPipe#643]
While it's already possible to auto-play the video when started from another app or to share to the pop-out mode, a feature I'm missing is the ability to have the link auto-play in the background (audio only) immediately after sharing the link.

**Comment by theScrabi** [comment]
Hm, well I don't want to add to much options to the share menu, since that would it up, and that could be a disadvantage for many android users.

**Comment by bytegeist** [comment]
Thanks for the quick reply.

You already have the [option menu entry](https://user-images.githubusercontent.com/3391322/28870198-ac8a33ec-777f-11e7-848b-29ccf3e36c91.png) "Autoplay when called from another app".

A really useful addition here would be a *suboption* to "Autoplay in background".

**Comment by mauriciocolli** [comment]
The problem with this option is that we have to load the page, so it doesn't give the seamless experience that this option need it.

I'm think in doing this:

- An option in the settings like: "Show 'Open with player...' in share menu", that the user controls whether they want to who it or not.
- When we try to open a video with this option, a dialog will appear asking which player the user want to use to play that specific video, something like this:

   ![openwith](https://user-images.githubusercontent.com/13389907/28873568-9e105ad2-7764-11e7-94ee-91476f808300.gif)

**Comment by bytegeist** [comment]
That looks great. How would that avoid the loading issue though, you mean to use the optional share menu as a splash screen for the loading process? Is it not possible at all to directly share to background play within android?

**Comment by mauriciocolli** [comment]
I meant that the option "Open with player..." would be optional, if it was disabled by the user, it wouldn't appear in the share menu. And what exactly do you mean by loading issue?

> Is it not possible at all to directly share to background play?

It is possible and I'm considering creating a option in the settings for those who want that, it'd be disable by default because otherwise, the share menu would be bloated (too much options).

###### Share menu = the menu that opens when you click on a link

**Comment by bytegeist** [comment]
Great, seems like I misunderstood.

As I mentioned before, you might consider moving the decision from the share dialog to the options menu and let users configure the share behavior in-app mostly. For example keeping the auto play option that's already included but adding suboptions for 'normal player', 'background' and 'pop-out'. 

Just like in the mock up but moved to the in-app settings menu enabling the users to either choose a default behavior or choose each time they share. This way you only need 1 entry in the share menu and could even get rid off the 2nd entry.

**Comment by mauriciocolli** [comment]
If I understood correctly, something like this?

**Settings:**
<img src="https://user-images.githubusercontent.com/13389907/28883826-24a267f4-7786-11e7-9dd2-bdc9a3c62bae.png" width="250">

**Share menu:**
<img src="https://user-images.githubusercontent.com/13389907/28883344-73ff908a-7784-11e7-8a6c-b5ed603a368e.png" width="250">

**Comment by bytegeist** [comment]
Yeah, like that. Maybe you don't even need the 2nd share destination anymore as the share behavior can be implied by the configuration inside the app.

**Comment by bytegeist** [comment]
Yes, a setting like that would be perfect.

**Comment by mauriciocolli** [comment]
Yes, there are even the old player option to consider.

**Comment by wisdomtooth** [comment]
This was great! How does one go about changing the new chosen default, though?
