### ISSUE TITLE
Only remember certain amount of history entries or only remember history entries for a certain amount of time

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#6431]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request. 

#### Describe the feature you want

I think it would be great to only retain a certain amount of history. This could be a specified amount of entries or time elapsed. Some of us would only use history if the app would crash or we didn't remember a certain video perhaps switched to a new video and we want to continue the old one which is present in the history. It's unnecessary to collect days of data and it's a bit easier to automate the deletion process. Also when deleting we wouldn't have to delete the fresh history.

#### How will you/everyone benefit from this feature?

This could prevent the database from stockpiling huge amounts of history data and it would give more privacy.

**Comment by rey0n** [comment]
+1 would be useful. Total no history or total erase are too radical.
