### ISSUE TITLE
Adding same video via enqueue causes issues when selecting one or the other

### ISSUE THREAD

**Issue by rancidfrog** [TeamNewPipe/NewPipe#6439]
# Checklist

- [x] I am using the latest version - Version 0.21.3
- [x]   I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x]   I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md .
- [x]   This issue contains only one bug. I will open one issue for every bug report I want to file.

# Steps to reproduce the bug

1. Add same video twice to queue. (Enqueue different videos before reenqueuing first video)
1. Remove the bottom video.
1. Top video is removed

# Actual behaviour

When the same video is queued more than once, selecting and removing one sometimes removes the other video.
This is more apparent if there are different videos in between first and second appearance of the same video.

# Expected behavior
When long pressing and removing a video, the video selected should be affected, regardless if the same video appears twice in queue

**Comment by MapleWheels** [comment]
There's an extended bug here as well, if you have the same video queued multiple times, trying to play a later-queued entry will cause it to play the first instance of it in the queue. This has the effect of making repeat a small section of the playlist instead of the whole thing.

**Comment by rancidfrog** [comment]
Yes, indeed.
There is a pointer issue. Which can also be seen by clicking to play one instance, causes it to playback the first or other instance of the same video.

**Comment by ShinyLuxray** [comment]
I believe PR #6712 fixes this issue among many others related to duplicate items in the play queue. Versions 0.21.9 or higher this fix is implemented. Adding a duplicate video to the play queue then deleting the later one works correctly, I tested on version 0.21.10.

**Comment by opusforlife2** [comment]
Thanks for confirming, @ShinyLuxray!
