### ISSUE TITLE
be on sha2017

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#644]
I will be At [sha2017](https://sha2017.org/) who will be there to?

If you want to meet vissit [Königlich Bayrisches Amtsvillage](https://wiki.sha2017.org/w/Village:K%C3%B6niglich_Bayerisches_Amtsvillage) or watch out for [me](https://wiki.sha2017.org/w/User:7h35cr4b1).

**Comment by theScrabi** [comment]
DECT: 2007

**Comment by comradekingu** [comment]
@theScrabi Nice seeing you there. Can be closed.
