### ISSUE TITLE
Folders for subscriptions

### ISSUE THREAD

**Issue by MaDDmin** [TeamNewPipe/NewPipe#6446]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

*Folders for subscriptions*

#### Is your feature request related to a problem? Please describe it

*Once your subscription list has grown past let's say, 200 channels, it becomes quite impossible to keep track on their news by theme group. It would be really ideal to be able to classify subscriptions by folders.*

#### Additional context

*Telegram recently added folders to chats and it is exactly the feature I miss on NewPipe.*

#### How will you/everyone benefit from this feature?

I think this would enhance this app tremendously.

**Comment by mhmdanas** [comment]
This feature already exists in the form of channel groups. Go to the subscriptions page, then to the "channel groups" section, and press the "New" button. If I misunderstood and this is not what you actually meant, feel free to make a comment to inform me. Thanks!

**Comment by MaDDmin** [comment]
Wow! Impressed and embarrassed about the fact that I've been missing this all this time!
Thanks, @mhmdanas, I think it's gonna be exactly what I meant.
