### ISSUE TITLE
Start playing in the background stops on random video from playlist

### ISSUE THREAD

**Issue by MatthewJohn5** [TeamNewPipe/NewPipe#6449]
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Start playing in the background a video from a playlist.

https://www.youtube.com/playlist?list=PLfm0UlAaFizvaDCpgeRGD-es6bq5LRO49

### Actual behaviour
Sometimes it will stop on random video from the list but most of the time it is https://www.youtube.com/watch?v=hvHi7N8kc8s&list=PLfm0UlAaFizvaDCpgeRGD-es6bq5LRO49&index=36

Can be any video in the list, this bug started from version 0.20.0 with the unified player.

Once it stops it will not play any video in background and in the unified player, the only way to fix it is to close the unified player tapping the X on the right of the video title, exit newpipe tapping back button, clear newpipe from the ram memory.

### Expected behavior
Tap Start playing in the background a video from playlist with screen off.

### Device info

 - Android version/Custom ROM version: Android 6.0 Marshmallow
 - Device model: Samsung J1 Mini 2016

**Comment by avently** [comment]
Open https://www.youtube.com/watch?v=hvHi7N8kc8s&list=PLfm0UlAaFizvaDCpgeRGD-es6bq5LRO49&index=36 in a browser and notice that the next video (37) is restricted for viewing. Some videos in this playlist are restricted too. So it's not a "random stops", it's stop before retricted videos

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?
