### ISSUE TITLE
Wrong order of downloads after restarting the app

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#645]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

When you download a video and then open the download dialog, the last downloaded video or audio is shown in the upper left corner.  After restarting the app the order of the items in the downloads view has changed and the downloads don't seem to be listed in a logical order (download date, file name, file size or file extension).

As I did some tests on this I recognized some other issues with this downloads view. Normally you can differentiate whether a file is a video or audio by the icon and the color of the tile. This works fine, except you have a `.web` file. Because these files can provide a video and an audio stream **or** only an audio stream, the video icon is displayed even when if there is no video stream. Is it possible to find out whether a video stream exists in this file?

I also wondered why we color all tiles with `.3gp` files different then the others. Is there a reason for it?

Furthermore we could also add a text like `This is the place where your can control your downloaded files once you have started a download.` to the download activity if no download is listed.

**Comment by FaizKhan5** [comment]
Close this issue.
