### ISSUE TITLE
Show hearts in comments

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#6458]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Some comments have hearts given, newpipe should show them

#### Is your feature request related to a problem? Please describe it

N/A

#### Additional context

N/A

#### How will you/everyone benefit from this feature?

better comments, see when creator likes certain comments, etc.

**Comment by Taratect** [comment]
Also replies too

**Comment by castrik** [comment]
> Also replies too

that's in #2277

**Comment by mhmdanas** [comment]
The extractor already supports this; it's just a matter of showing it in NewPipe.
