### ISSUE TITLE
A better ui for tags in description

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#6459]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Version 0.21.4 has feature to show tags in description but currently, its only in a small space, it should be in a vertically expanded, more like a table order so we can see it better

#### Is your feature request related to a problem? Please describe it

its incredibly hard to see all the tags, we have a single line which is very short and we have to scroll horizontally to see the tags, some can't even fit in the small space

#### How will you/everyone benefit from this feature?

a better way would be to let us click on TAGS to see it expand vertically or have it expanded already

**Comment by SameenAhnaf** [comment]
The thumbnail URL could be placed above the tags. That way, we won't have to worry if there are too many tags to scroll down and reach the tags.

**Comment by mhmdanas** [comment]
It was decided against having tags expanded by default because it would look incredibly ugly when the tags are but more than a few. However, it could be possible to add both solutions somehow.

@Stypox what do you think? (sorry for the ping)

**Comment by Stypox** [comment]
Putting the tags at the end would probably be a solution. Doing fancy things with expandable menus (like adding a "MORE" chip or putting the chips on two lines) is not viable, as there is no support by the Chips library and the whole logic would have to be written from scratch.

**Comment by SameenAhnaf** [comment]
I agree with Stypox. There's no need to add 'More' button or something alike that. Let the 'Tags' option stay in bottom.

No need to make a huge list by keeping each tag in every single line. Fit tags as much as possible in the screen and scroll down vertically for more. No need to keep a separate scroller for tags either. Pardon me for my poor editing.
![IMG_20210609_175021](https://user-images.githubusercontent.com/79245641/121349976-ea907d00-c94b-11eb-882e-a5314d53d1fb.jpg)

**Comment by Stypox** [comment]
@castrik what do you think of #6463?
@SameenAhnaf I tried to do what you suggested but it looked misplaced: putting tags at the end and letting them wrap around didn't look good unfortunately.
<img width="300px" src="https://user-images.githubusercontent.com/36421898/121365118-a9db3880-c938-11eb-96d6-e283db2fdda8.png"/>

**Comment by SameenAhnaf** [comment]
@Stypox Well, I tested the apk in #6463. Unfortunately, it doesn't actually solve the problem of this issue. The tags are still in a single line.

>its incredibly hard to see all the tags, we have a single line which is very short and we have to scroll horizontally to see the tags, some can't even fit in the small space

Honestly, the screenshot doesn't look that bad. It's just my personal opinion. It's always good to hear others' opinions.

If you still don't like this, you may just put each tag in each line of list view as well. Many users may just want to have a glance at the tags and scrolling within a single line is really obnoxious. It misses the flexibility of scrolling down in description which is possible in a pretty wide space.

@mhmdanas @castrik What do you think about Stypox's screenshot? I think, the tags could start from the right side of screen and it will seem great.

**Comment by mhmdanas** [comment]
@SameenAhnaf

> What do you think about Stypox's screenshot?

I agree with @Stypox that it doesn't look very good (mostly the fault of people who just put anything and everything in tags, but I digress).

> I think, the tags could start from the right side of screen and it will seem great.

If that means what I understand it to (the tags start from the end instead of the start), then I see how that might help make it look better. However, I'd like not to judge prematurely without seeing a screenshot.

**Comment by skyGtm** [comment]
Starting chips from next line, and center aligning `TAGS` would look good?
`TAGS` textview however looks small so, increasing textSize and renaming it to `VIDEO TAGS` might be better in my opinion.


![121365118-a9db3880-c938-11eb-96d6-e283db2fdda8](https://user-images.githubusercontent.com/50160188/121391931-a06cc300-c96e-11eb-8e6f-78e7827f4c59.png)

**Comment by castrik** [comment]
@Stypox the apk in 6463 is basically the same, sure we get 50% more space to scroll, but still, we have to scroll way too much, but its managable
your screenshot is exactly what I want
although, screenshot by @skyGtm looks more clean imo

**Comment by Stypox** [comment]
I updated #6463 with the suggestion @skyGtm made. @skyGtm @castrik @SameenAhnaf is it ok now?

**Comment by Stypox** [comment]
You are right, that happens to me too. Github probably has some issues. I re-ran the jobs, try again in a few minutes

**Comment by skyGtm** [comment]
@castrik I have the file, if you want

https://ufile.io/vzypp1yi

**Comment by castrik** [comment]
@skyGtm thanks
@Stypox yes, it works exactly as intended

**Comment by skyGtm** [comment]
>renaming TAGS to VIDEO TAGS might be better 

@Stypox  what is your opinion on this.

Since tags are long and the title as 'TAGS' just looks small in comparision to actual chips.
So renaming it to `VIDEO TAGS` will make it stand out as a title for those chips below

**Comment by Stypox** [comment]
Thank you for the reminder and sorry for not answering before. I didn't want to rename "TAGS" to "VIDEO TAGS" since:
- only in English "TAGS" is short, in italian it would be "ETICHETTE" which is long enough
- prepending "VIDEO" is not consistent with all of the other metadata labels. For consistency we would need to use "VIDEO CATEGORY", "VIDEO LICENCE", ... everywhere, but that's definitely not an option.
- it is obvious that we are talking about the video tags, so adding more text to read which does not provide any new information just worsens the experience
