### ISSUE TITLE
Video marked as "not loaded"

### ISSUE THREAD

**Issue by stemy2** [TeamNewPipe/NewPipe#6460]
### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
I can't update videos from my subscriptions since 2 months. It shows "feed last updated: [some time], not loaded: 48" (i currently have 48 subscriptions).

### Expected behavior
Feed updating

### Logs
It leaves no trace in the debug logs.

### Device info

 - Android version/Custom ROM version: /e/ 0.16
 - Device model: samsung galaxy s7

**Comment by skyGtm** [comment]
Settings> Content> Feed Update Threshold, and set your choice.
I was running into same issue few days ago.
This might help.

**Comment by stemy2** [comment]
I just set it to "always update", but it didn't changed anything.

**Comment by mhmdanas** [comment]
I smell #5977. Do you live in the EU or use a VPN that connects to the EU?

**Comment by stemy2** [comment]
I actually live in EU, but i don't think it's related. Newpipe worked fine in the past and the debug version (0.21.0) doesn't have a such problem.

**Comment by mhmdanas** [comment]
No, it's totally related. #5977 doesn't happen to all the people in the EU. Some people even reported that it started working suddenly, so it's definitely #5977.
