### ISSUE TITLE
Some simplified Chinese translations in app are missing

### ISSUE THREAD

**Issue by Geeyun-JY3** [TeamNewPipe/NewPipe#6468]
### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Setting > Video and audio > Behavior > Fast-forward/-rewind seek duration (screenshot 1)
Setting > Content > Feed > Feed update threshold (screenshot 2)

I change the translation, adding a space between the `%d` and units. I don’t know if it is related.

### Actual behaviour

Some translations in dialog components are missing.

### Expected behavior

No translations is missing.

### Screenshots/Screen recordings

![Screenshot_20210610221318](https://user-images.githubusercontent.com/49396421/121546855-36235380-ca3e-11eb-8171-8b3cd5b6da9f.jpg)
Coresponding missing string: [`%d seconds`](https://hosted.weblate.org/translate/newpipe/strings/zh_Hans/?checksum=5f0105ea651dca8f)

![Screenshot_20210610221356](https://user-images.githubusercontent.com/49396421/121546866-37ed1700-ca3e-11eb-81bb-1854b6db1504.jpg)
Coresponding missing strings: [`%d minutes`](https://hosted.weblate.org/translate/newpipe/strings/zh_Hans/?checksum=b05b55ee2946e430), [`%d hours`](https://hosted.weblate.org/translate/newpipe/strings/zh_Hans/?checksum=7b0c93293a28f3f), [`%d days`](https://hosted.weblate.org/translate/newpipe/strings/zh_Hans/?checksum=4136d50a44f28f5d)

### Device info

 - Android version/Custom ROM version: Android 9 MIUI 10 9.9.3
 - Device model: Mi 8

**Comment by chr56** [comment]
![image](https://user-images.githubusercontent.com/30681738/122908588-dd7d8000-d386-11eb-8662-95917b8ad66d.png)
These strings are never missing . They are just in the wrong plural item.
The correct plural item should be "`other`".


It seems that Weblate can not put these localizations into correct plural item .
