### ISSUE TITLE
Sentry data loss // revived and back in business

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/NewPipe#647]
Good evening (or whatever time it is in your end of the world).

I have to inform you that our Sentry instance has suffered from severe data loss due to a configuration issue. The issue is resolved, and the backup infrastructure has been extended. Further, the Sentry instance has now better monitoring, and we are confident this won't happen again.

## What happened

We use Docker to host all the software components that make Sentry this great. During an upgrade, the containers got deleted, and new ones were instantiated with the same configuration. Unfortunately, the data from the containers, especially the database container, has never been saved to the volumes that were configured. This meant that the new containers were pretty much equal to a fresh installation.

## Revival

As you can imagine, I had to re-setup ***everything***. This means I had to re-process the several 10ks of e-mails that we have collected in the past months. Due to a Sentry limitation, error reports older than 30 days cannot be imported, though. This does not mean that they are lost forever, but they won't be available in Sentry. I decided that either the issues have been re-reported and thus are available somewhere, or they have silently been resolved and are no longer of any relevance. I hope that's okay for anyone. If anyone should care about something older, please contact me and I'll do my best to grep through the on-disk archives and send you the relevant data.

## Back in business

The new Sentry instance has seen some improvements. We now have **official GitHub integration**, meaning that registered people can link to their GitHub account using GitHub's OAuth2 integration, and transfer issues from Sentry right to GitHub! I think that's a very nifty feature, and will further improve the workflow.

I **strongly** advice you to check the description Sentry generates before creating issues on GitHub. 

Private data ***must be removed*** from Sentry's suggestions, just like from the title. Private data includes IP addresses, e-mail addresses and anything that *could lead to the identification of a user* in extreme circumstances. If you are not sure, you're advised to ask in #newpipe on Freenode or send an e-mail to the organisation's mail account. **Failure to adhere to this rule may result in immediate revocation of your permissions on Sentry and/or on TeamNewPipe!**

Please post your experiences with this brand new feature! I'd like to see how well it'll work for you, and where we could further improve the experience.

**Beware:** migration of issues is **only** supported for the main NewPipe repository! For NewPipeExtractor etc. you'll have to use the traditional way and post your issues manually!

**Sentry and the Sentry GitHub integration are only available for members of TeamNewPipe!**

**Comment by TheAssassin** [comment]
## Registration

You will have to register on https://sentry.schabi.org/. A owner of the organization (currently me and @theScrabi) will have to confirm your registration and add you to the Sentry team.

## GitHub Integration

The GitHub integration will be available from the single issues' pages. If you click on an issue, there will be a new tiny dropdown called "GitHub" where you can choose to either create a new issue or link with an existing one. On first use, Sentry will prompt you to link to your GitHub account. This is a mandatory step for this feature.

See the attached screenshots.

![screenshot_1](https://user-images.githubusercontent.com/4503202/28895048-19c467e6-77d7-11e7-996c-fa51d936ed74.png)

![screenshot_2](https://user-images.githubusercontent.com/4503202/28895009-ff263248-77d6-11e7-9c14-1aeba992caa1.png)

**Comment by theScrabi** [comment]
You can re register to sentry at [sentry.schabi.org](https://sentry.schabi.org)

**Comment by TheAssassin** [comment]
**Update:** Sentry is down again. This time, the failure has been induced by the hosting provider, and many other services I host are down as well. The data has been backed up though, and I am working at the moment to get everything back up.

Due to dissatisfaction about these recent problems, I even think about moving to another provider, and upgrade my infrastructure a bit. The higher costs will hopefully pay out in better uptime.

**Comment by mauriciocolli** [comment]
@TheAssassin I noticed that in 16 days there's no new reports in Sentry, is this related to that problem or just nobody reported anything in the meantime (a bit unlikely)?

**Comment by TheAssassin** [comment]
The importer is deactivated until sentry has been migrated to the new system. You need to tell @theScrabi to get going and join me this weekend on Mumble or somewhere so we can finish this. Then, I can also fix and deploy @TobiGr's brand new website.

The mail system has already been migrated to the new server, and as I was debugging a few minor issues induced my the migration, I was seeing lots of NewPipe messages (the main source of mail traffic btw), so be assured that NewPipe hasn't become bug-free overnight.

**Comment by theScrabi** [comment]
@TheAssassin didn't you say you wanted me to change the ip address for your server?

**Comment by TheAssassin** [comment]
@theScrabi I told you I need you to change the IPs of all systems one by one on request, i.e., not at once.

**Comment by theScrabi** [comment]
all right

**Comment by TheAssassin** [comment]
Closing as it's rather outdated and the service has been very stable since its revival.
