### ISSUE TITLE
Lack of tiny feature

### ISSUE THREAD

**Issue by SalihBulmaz** [TeamNewPipe/NewPipe#6471]
I use the app with mobile data oftenly. To save some data i want to watch vids 480p or less, especially music vids. When i choose any res. lower than 720p the next video is 720p again. Sometimes i hate rearranging the quality over and over again. Pls make the app recognise the recent quality preferrence. That would help a lot.

**Comment by skyGtm** [comment]
Settings> Video and Audio> Limit Resolution when using Mobile Data --> Set it to desired value.
Hope that helps.

But I also like your idea to remember recent quality preference that is set from the player.

**Comment by ShareASmile** [comment]
> Settings> Video and Audio> Limit Resolution when using Mobile Data --> Set it to desired value.

It is not working since many versions as back as (i think v0.19..) reported in #4486 

> I use the app with mobile data oftenly. To save some data i want to watch vids 480p or less,

Try changing default resolution to 480p in Video & Audio Settings if that works!

> But I also like your idea to remember recent quality preference that is set from the player.

Agree

**Comment by cbiere** [comment]
What you actually want is just audio playback with no video, don't you? Doesn't background playback do this? I'd be surprised if background playback loaded the video stream.
