### ISSUE TITLE
can't get past recaptcha loop since two months

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#6484]
I posted this issue already but still no fix.

Solving captcha won't display the video, I get prompted to solve again.

**Comment by hp8wvvvgnj6asjm7** [comment]
I stopped using this app since then, but I occasionally come back to see if it changed. looking forward.

**Comment by mhmdanas** [comment]
Please, PLEASE don't open duplicate issues. There's already #6311. Also, please don't remove the template next time you open an issue.
