### ISSUE TITLE
Youtube Icon seems to be rendered incorrectly

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#6492]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open Drawer Menu

### Actual behaviour
Youtube Icon is missing center triangle.
![Capture](https://user-images.githubusercontent.com/50160188/122050139-e9a39380-ce02-11eb-8406-745b60a069b4.PNG)

### Expected behavior
Should show icon similar to Youtube i.e. with triangle at the center of the icon.
![Capture3](https://user-images.githubusercontent.com/50160188/122050026-c973d480-ce02-11eb-999a-2acb3603db6f.PNG)

### Device info

 - Android version/Custom ROM version: 9.0 EMUI
 - Device model: Nova 3i

**Comment by TobiGr** [comment]
That's intended
