### ISSUE TITLE
Adding to queue while another another video from playlist is playing makes the new video take so long

### ISSUE THREAD

**Issue by pokegamer5547** [TeamNewPipe/NewPipe#6498]
- [x] I am using the latest version -  0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play a video from playlist
2. Search for a video and select add to queue

### Actual behaviour
The video added to queue goes all down in qeuue list  making playlist videos have to end in order to play the queued video.

### Expected behavior
When another video is playing already by a playlist and i add a new video to queue, i except the new video (qeuued) to play first after current video ends instead of whole playlists.

### Device info

 - Android version/Custom ROM version: android 10 miui 12
 - Device model: redmi note 9 pro

**Comment by MapleWheels** [comment]
This is intended behaviour and it works the same on YouTube as well. Not a bug, this dhould be a feature request to be added to the options.

**Comment by pokegamer5547** [comment]
@MapleWheels oh well i guess you are right, sorry about that. Can i change the just change the label or should i create new issue and delete this one?
