### ISSUE TITLE
[LOW] Typo

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [TeamNewPipe/NewPipe#6508]
### Checklist

- [x] I am using the latest version - 0.21.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open NewPipe for SoundCloud
2. Find a track that was posted 1 month ago
3. Experience the typo as seen in the screenshots

### Actual behaviour

Shows "Monatn" (comparable with "monhs") instead of "Monaten" (months).

### Expected behavior

Show "Monaten" (months) instead of "Monatn" (comparable with "monhs").

### Screenshots/Screen recordings
![Screenshot_20210617-180139_NewPipe.png](https://user-images.githubusercontent.com/17967646/122434439-a114e300-cf86-11eb-8295-e5de27f344d7.png)
![Screenshot_20210617-180547_NewPipe.png](https://user-images.githubusercontent.com/17967646/122434457-a5d99700-cf86-11eb-8955-b9a0be9531b1.png)

### Logs

Nothing here but the chirping of the crickets ¯\_(ツ)_/¯

### Device info

 - Android version/Custom ROM version: crDroid 7.6 (based on Android 11)
 - Device model: OnePlus A6013 (OnePlus 6T)

**Comment by mhmdanas** [comment]
This is a mistake in https://github.com/ocpsoft/prettytime, not NewPipe. Please report the issue there.
