### ISSUE TITLE
A version of new Pipe is missing via the Apple store.

### ISSUE THREAD

**Issue by Hei3h** [TeamNewPipe/NewPipe#6517]
This is a feature request. I ask the developers and the community in general that is in charge of this project to launch a version within the Apple mobile application store, better known as apple Store. I understand that Google does not allow new Pipe in the play store, but it would not be the same with Apple since Google and Apple are different companies. Please new Pipe community, make it possible. Thanks.

**Comment by SameenAhnaf** [comment]
I recommend you to keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/1051 ??
