### ISSUE TITLE
3x playback speed options

### ISSUE THREAD

**Issue by dirtyid** [TeamNewPipe/NewPipe#652]
Would be useful to expand playback speed with 2.5x, 3x speed as well as set default playback speed in options.

**Comment by wb9688** [comment]
I'd rather want an option to manually input the playback speed.

**Comment by PacoBell** [comment]
Yes, manual input would be a better option if we're thinking of bloating the UI further. Also, NewPipe remembering the last playback speed would be nice, but that's a different request.

**Comment by wilfriedroset** [comment]
You have the ability to set the playback speed up to 3x in v0.13.1.
Not sure if it's relevant to keep this issue open.
