### ISSUE TITLE
New servers support

### ISSUE THREAD

**Issue by NewNewPipe** [TeamNewPipe/NewPipe#6527]
I am making a request to be added to Newpipe's support of servers:

Bitchute
Brighteon
Banned.Video

**Comment by mhmdanas** [comment]
Bitchute was rejected in #664. For the other two, please make two separate issues on https://github.com/TeamNewPipe/NewPipeExtractor.

**Comment by TobiGr** [comment]
Banned.video is definetly not going to be included. The same thing said about Bitchute applies for that platform as well.
