### ISSUE TITLE
Can't download WebM with audio

### ISSUE THREAD

**Issue by gappleto97** [TeamNewPipe/NewPipe#653]
I can stream WebM with audio just fine, but when I go to download it has a muted icon next to it. What's up with that?

**Comment by mauriciocolli** [comment]
###### From https://github.com/TeamNewPipe/NewPipe/issues/608#issuecomment-312904335
> Regarding the no-audio, it's the way that YouTube works, it delivers the video and audio in different streams, the only thing that we could do is merging them, but that would require some libraries that I'm not sure we're going to include (I'm studying that option though).

**Comment by gappleto97** [comment]
I would like to formally request that you include them, please

**Comment by theScrabi** [comment]
That would require to convert the video locally on your phone. At the moment we can not provide this function.

**Comment by gappleto97** [comment]
I realize that. That's why I'm requesting it. I had forgotten that they were separate streams, but that was silly of me since I've used youtube-dl before.
