### ISSUE TITLE
reCAPTCHA Requested

### ISSUE THREAD

**Issue by NancyTheNewbie** [TeamNewPipe/NewPipe#6535]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

When I try to watch any video, the app presents a YouTube popup requesting a reCAPTCHA challenge. After completing the challenge, it takes me to a YouTube window (ads and all) within newpipe as if I'm watching in a browser. It presents reCAPTCHA before any video I click on. 

### Expected behavior

I expect to be able to watch a video. 

### Logs

 - Android version/Custom ROM version: Unofficial LineageOS for Sofiar
 - Device model: Moto GPower

**Comment by NancyTheNewbie** [comment]
FYSA, I'm running a VPN, but have never had an issue with it before the last couple of days. I've changed servers, but it still presents the issue.

**Comment by TobiGr** [comment]
try the APK in #6464
