### ISSUE TITLE
Add the option to have NewPipe *not* share videos with a timestamp

### ISSUE THREAD

**Issue by Eggo-Plant** [TeamNewPipe/NewPipe#6543]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

By default, when you copy the link to a video using share, it automatically includes the timestamp in the link. I've found this very annoying sometimes because I accidentally send videos with the timestamp when I don't want that. I think that there should either be an option in the settings to disable this feature, or it could give you an option to share it with the timestamp when you click on the share button.

#### Is your feature request related to a problem? Please describe it
This feature request just solves a minor annoyance with a relatively simple solution.

#### How will you/everyone benefit from this feature?

This feature will prevent accidental sending of YouTube links where it's in the middle of the video. Saving you from embarrassment from your friends as they're left in confusion, as to why you linked to specifically into the two thirds point in the "How It's Made" video on trumpets from 2015 (not speaking from experience).

**Comment by skyGtm** [comment]
![Capture](https://user-images.githubusercontent.com/50160188/122873364-65489780-d351-11eb-850f-e578aefcba16.PNG)

Hope this helps
