### ISSUE TITLE
Implement sponsorblock

### ISSUE THREAD

**Issue by stemy2** [TeamNewPipe/NewPipe#6546]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
A clear and concise description of what you wish should happen.
Sponsorblock is an utility to block sponsored sections in a video based on a huge online database. It exists as browser addon and as feature in the freetube app, it could be useful to implement it into newpipe.

https://sponsor.ajay.app/

#### How will you/everyone benefit from this feature ?

Newpipe already blocks ads, the app could go further to user friendliness with a sponsor blocking.

**Comment by SameenAhnaf** [comment]
Devs don't want it. See: https://github.com/TeamNewPipe/NewPipe/pull/3205

**Comment by skyGtm** [comment]
@stemy2 
https://github.com/polymorphicshade/NewPipe#newpipe-x-sponsorblock
