### ISSUE TITLE
[FTR] Add to a group from the channel page.

### ISSUE THREAD

**Issue by FOSS-Love** [TeamNewPipe/NewPipe#6552]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Add to a group from the channels page

#### Is your feature request related to a problem? Please describe it

Whenever i visit a channel i wouldn't know what groups that i have placed it in, and is also easy to assign a freshly discovered channel to a group.

**Comment by SameenAhnaf** [comment]
I recommend you to keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/5836
