### ISSUE TITLE
Aspect ratio is messed up

### ISSUE THREAD

**Issue by LokiLinux** [TeamNewPipe/NewPipe#6559]
### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Just watch a video (that's what the app is for, you know).

### Actual behaviour

When I watch full screen, the things are horizontally stretched i.e. they look wider.

### Expected behavior

The aspect ratio shouldn't change.
(I checked all the settings in the app but there is no option to let it not fill the screen/fit to screen or whatever it's called.)

### Screenshots/Screen recordings

1. From NewPipe:
![Screenshot_2021-06-23-19-46-30-597_org schabi newpipe](https://user-images.githubusercontent.com/77105020/123115592-d83f3480-d45d-11eb-9170-263b4fc74099.jpg)

2. From YouTube app: (for reference)
![Screenshot_2021-06-23-19-59-52-260_com google android youtube](https://user-images.githubusercontent.com/77105020/123115673-e4c38d00-d45d-11eb-81f0-8a233112c3a9.jpg)

I think NewPipe is filling the screenand there is no option to ask it not to.

### Device info

 - Android version/Custom ROM version: MIUI Global 12.0.4
 - Device model: Redmi Note 10

**Comment by SameenAhnaf** [comment]
Hope, this helps!😀

![IMG_20210623_213246](https://user-images.githubusercontent.com/79245641/123125723-97015180-d46a-11eb-9639-ca5e2280a013.jpg)
