### ISSUE TITLE
Download queue makes no distinction for metered connections

### ISSUE THREAD

**Issue by ballo** [TeamNewPipe/NewPipe#6564]
The download queue just ate all my mobile data for an entire month in a few minutes. I paused the download then left the wifi and it sucked it dry.

Other apps like LibreTorrent don't do this.

**Comment by SameenAhnaf** [comment]
I think, turning on these options from 'Settings'>'Downloads' should help.
![IMG_20210624_085952](https://user-images.githubusercontent.com/79245641/123195867-b4660800-d4ca-11eb-97c3-bab5be19212e.jpg)
