### ISSUE TITLE
Focus skips over resolution and playback speed button on Fire TV Stick with remote

### ISSUE THREAD

**Issue by vishnuraghavb** [TeamNewPipe/NewPipe#6571]
### Checklist

- [x] I am using the latest version - 0.21.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

On Fire TV Stick

1. Open a video and go to the main player.
2. Using the remote try navigating to the video resolution and speed control button. You can see the focus skips from the close and playlist button. Actually, these buttons were focusable in versions prior to 0.20

### Actual behaviour

Focus jumps between close and playlist button.

### Expected behavior

Focus video resolution and speed control button on the main player using the remote.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/39849268/123430294-a527ad00-d5e5-11eb-999d-76e582916669.mp4

### Device info

 - Android version/Custom ROM version: Fire OS v5.2.7.8
 - Device model: Amazon Fire TV Stick Gen 1

**Comment by Stypox** [comment]
I can't reproduce as of 0.22.1 when testing on an emulator, please reopen if you still experience it in the latest version :-)

**Comment by KR4U7H3R** [comment]
I encounter the same bug. I am on version 0.24.1 and use a Fire TV Stick 4K (Fire OS 6.2.9.3).

Info
    I am using the latest version: 0.24.1 
    Android version/Custom ROM version: Fire OS 6.2.9.3
    Device model: Amazon Fire TV Stick 4K


While using the remote it is not possible to navigate to the video resolution and speed control button. The same goes for the caption and fit button.

Workaround for Video resolution is adjusting it in the settings.

**Comment by opusforlife2** [comment]
Please check for duplicate, then yes, please open a new issue.
