### ISSUE TITLE
To be able to switch to fullscreen before starting playback

### ISSUE THREAD

**Issue by azat11** [TeamNewPipe/NewPipe#6573]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
It would immensely logical to be able to switch to fullscreen BEFORE starting playback. And I want that.
No alternatives here. Starting playback to be able to switch to fullscreen is stupid.

#### Is your feature request related to a problem? Please describe it
I want to switch to fullscreen BEFORE starting playback, but I can not.

#### Additional context
I could do this in some previous old versions afair. But not anymore. And it's extrenely inconvenient and illogical.

#### How will you/everyone benefit from this feature?
We could enjoy watching videos in fullscreen from the start.

**Comment by azat11** [comment]
#6574

**Comment by SameenAhnaf** [comment]
PR #5459 is already in work for this issue.

**Comment by mhmdanas** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/4152.
