### ISSUE TITLE
An option to disable auto playback on switching to fullscreen

### ISSUE THREAD

**Issue by azat11** [TeamNewPipe/NewPipe#6574]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I want to be able to start playback myself after switching into fullscreen, to disable auto playback on switching to fullscreen.

#### Is your feature request related to a problem? Please describe it
When I press "fulscreen" I have to turn my phone, and playback starting immediately makes it start before I have it in the right position, which leads to me always skipping backwards to the start of the video.

#### Additional context
There's a request connected to this one. I will try and link it here.

#### How will you/everyone benefit from this feature?
More convenient behavior of the app, less unnecessary gestures/taps.

**Comment by azat11** [comment]
#6573

**Comment by SameenAhnaf** [comment]
I recommend you to keep the discussion in #6437.
