### ISSUE TITLE
Pop up swipe to exit.

### ISSUE THREAD

**Issue by t-rocks** [TeamNewPipe/NewPipe#658]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by t-rocks** [comment]
I saw a post here about "popdown", or something to the effect.  The discussion seemed to go off the rails a bit, but mostly it was about a way to exit the popup without entering the app.  I'd like to suggest a swipe right action to close the pop up at any point in the video.

**Comment by theScrabi** [comment]
That would be a nice feature.

**Comment by Zero3K** [comment]
I agree.

**Comment by ashishthukral** [comment]
Please add swipe to exit or a Cross 'x' icon in the pop-up mode.

**Comment by bboa** [comment]
Very nice ideas
