### ISSUE TITLE
Title bar on full screen player is shown under the seek bar at times

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6583]
### Checklist

- [x] I am using the latest version - 0.21.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Well, the bug is extremely inconsistent. So, I don't know what is exactly happening. After returning from recent apps or home seems to solve the bug.

### Actual behaviour

Title bar is shown under seek bar. Note that I can't scroll do anything in the info section. It just stays there.

### Expected behavior

Nothing from info section (Title bar, buttons etc.) should not be shown. Just a clean full screen player experience.

### Screenshots/Screen recordings

![IMG_20210628_140251](https://user-images.githubusercontent.com/79245641/123601513-96c1d700-d819-11eb-916f-42ad10c5ea89.jpg)

### Device info

 - Android version/Custom ROM version: MIUI 12.0.8
 - Device model: Xiaomi Redmi Note 8 Pro

**Comment by opusforlife2** [comment]
Do you have system auto-rotate turned off? If so, you can drag up on the full screen button to scroll down to the description/comments/etc. Maybe you accidentally dragged up on the full screen button a little?

**Comment by SameenAhnaf** [comment]
>Do you have system auto-rotate turned off?

Yes, I try to drag up on the full screen as you said. But often the app misbehaves. This bug doesn't seem to be frequent. Probably, it occurs 1 or 2 out of 15 times.

**Comment by opusforlife2** [comment]
What I mean is, maybe in those rare cases your finger or thumb accidentally drags the full screen button a little.

**Comment by SameenAhnaf** [comment]
>What I mean is, maybe in those rare cases your finger or thumb accidentally drags the full screen button a little.

Wait, what?! This was an intended feature? Feel free to close the issue then. 

If this was intended, how I can access the same if auto-rotation is enabled??

**Comment by opusforlife2** [comment]
The point of the feature is that if you have auto-rotate enabled, then you can simply tilt your phone. But if you have it disabled, then you need the full screen button to enter full screen.

If you want to scroll down even with auto-rotate enabled, then you can long-press on the arrow button at the top right of the player.
