### ISSUE TITLE
NewPipe for PC

### ISSUE THREAD

**Issue by sauravrao637** [TeamNewPipe/NewPipe#6591]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I think it will be great if we make New Pipe for PCs.

#### How will you/everyone benefit from this feature?

It will help expand New Pipe's reach and benefit more users.

**Comment by SameenAhnaf** [comment]
See: https://github.com/TeamNewPipe/NewPipe/issues/4608#issuecomment-774522797

**Comment by sauravrao637** [comment]
#4608 is about website, this is request for a software which can be installed on the machine.

**Comment by TiA4f8R** [comment]
Duplicate of #1051.
