### ISSUE TITLE
Import playlist CSV

### ISSUE THREAD

**Issue by denthebro** [TeamNewPipe/NewPipe#6595]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Please make it possible to import individual playlist CSV files downloaded from YouTube

#### Is your feature request related to a problem? Please describe it

I want to move all of my playlists from YouTube to NewPipe. I tried the import database feature, but it only imported my subscriptions.

#### Additional context

Just a simple import CSV as bookmarked playlist feature would be nice.

#### How will you/everyone benefit from this feature?

Makes it easier to migrate everything from YouTube to NewPipe.

**Comment by SameenAhnaf** [comment]
For now, Newpipe only supports importing subscriptions. For now, you may make your playlists 'Unlisted' or 'Public', copy the links and manually save the playlists.

**Comment by mhmdanas** [comment]
Duplicate of #1348.
