### ISSUE TITLE
First tell people what the program does do

### ISSUE THREAD

**Issue by jidanni** [TeamNewPipe/NewPipe#6598]
README.MD says,
> Description
> NewPipe does not use any Google framework libraries, nor the YouTube API. Websites are only parsed to fetch required info, so this app can be used on devices without Google services installed. Also, you don't need a YouTube account to use NewPipe, which is copylefted libre software.

Errr... don't you think you should **first** tell people what the program **does do**, then only **second** tell people what the program **doesn't do**.

**Comment by mhmdanas** [comment]
It already gives a general idea before it:
> A libre lightweight streaming frontend for Android.

But yes, you do have a point.

Anyway, I will be closing this, #6599, #6600, #6601, and #6602. Please create new issues for each of these, making sure that you fill in the template properly for each one (if you're not aware, there was some text already there for you, but you seem to have removed it in all your issues).
