### ISSUE TITLE
Pause button stays on the screen for too long, or should not be in the centre

### ISSUE THREAD

**Issue by rombick** [TeamNewPipe/NewPipe#660]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
Please describe your problem a little further.

**Comment by emes27** [comment]
I think what he meant is, that after the play button was pressed after the video was paused, the pause symbol || stays for a certain time while the video already plays.

Additional:
At the same time the screen is faded to darker brightness, what can also be some kind of annoying if one wants to see any detail directly from the re-beginning of the video.

May this be fixed,please?
