### ISSUE TITLE
No way to seek in background mode

### ISSUE THREAD

**Issue by jidanni** [TeamNewPipe/NewPipe#6606]
Once one chooses play video in background, one gives up the possibility of advancing ahead a few minutes or back a few minutes. Any touching the video screen assumes the user now wants the exit background mode and watch the video itself.

**Comment by SameenAhnaf** [comment]
Hope, this helps.
![IMG_20210703_170943](https://user-images.githubusercontent.com/79245641/124352359-9febe300-dc21-11eb-860d-3956b2d85642.jpg)

**Comment by mhmdanas** [comment]
It's as @SameenAhnaf says. Note that the seekbar is not available on older Android versions. Also, please don't remove the template when opening an issue

**Comment by jidanni** [comment]
Well all this should be documented somewhere.
