### ISSUE TITLE
All videos show unrecoverable error

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#6609]
Edit: Updated findings.

### Checklist

- [x] I am using the version - 0.21.3 (but also tested on latest) 
- [x] I checked, and found a closed duplicate of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
Unrecoverable player error on all videos

### Expected behavior
All videos should play as normal

### Screenshots/Screen recordings
N/A

### Logs
N/A

### Notes
1) Everything was functional a few hours ago.
2) Quality of stream is irrelevant. All show the error.
3) Changing format to WebM doesn't fix it.
4) Playing in external player does circumvent the issue for now. 

### Device info

 - Android version/Custom ROM version: Android 7
 - Device model: Samsung
___
Thank you for your time and consideration.

**Comment by johnth3doe** [comment]
Update: Rebooting the device seems to have resolved the issue in total. Not sure why this is the case, but glad it was solved.

Thank you for your time and consideration.

**Comment by opusforlife2** [comment]
Did you not get a crash report? If so, could you please paste it here, regardless of your issue being resolved on its own?

**Comment by johnth3doe** [comment]
> Did you not get a crash report? If so, could you please paste it here, regardless of your issue being resolved on its own?

I apologize, however there was no crash, therefore no report or log that I could provide. It is why I specifically labeled the respective area as "N/A" when submitting the issue. The only thing I was presented with was a toast notification showing the message that is the title of this issue.

What I can offer is some additional context;
1) The closed issue I was referring to (who had a similar experience was [#5556](https://github.com/TeamNewPipe/NewPipe/issues/5556#issuecomment-777548500)
2) I had the same issue as mentioned in #6510 every few videos, and rebooting has (so far) alleviated that too.
3) The only unique consideration in this case is that I had multiple long (2 hours average) videos (totaling double digit hours) en-queue. So I assume that may have been a contributing factor? I don't know if such is the case, so pardon my assumption if I am not right about this.
___
Thank you for your time and consideration.
