### ISSUE TITLE
constant video jerking, buffering problem.

### ISSUE THREAD

**Issue by retropassion** [TeamNewPipe/NewPipe#6611]
Hello, 

For some time I have been experiencing a rather annoying problem (version 21.5 on Android)
All videos (Youtube) are not played correctly, it makes jerks every second. There is a problem of cache and buffering of the videos. 
I must admit that it is very problematic (Same problem with 4G or WIFI)

Can you report this problem to the developers ? 

Thank you very much for this application and your work !

**Comment by Doctor-blob** [comment]
Same Problem here

**Comment by Disqu3-mirOir-qt** [comment]
same for me need clear cache every time after 2-3 video see

**Comment by botistreamer** [comment]
Duplicate of #6510.

Atleast check the pinned issues before making a new issue.

**Comment by TiA4f8R** [comment]
Also, don't remove the issue template when opening an issue.
