### ISSUE TITLE
How can I play a youtube link that my friend sent to me directly,  https://youtu.be/E5ImPFlg4BQ

### ISSUE THREAD

**Issue by NanyangTaiji** [TeamNewPipe/NewPipe#6620]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

**Comment by SameenAhnaf** [comment]
Hope, this helps. Just click the link and select 'Newpipe'. If you set any other default browser, 'Clear defaults' from that browser app info.

https://user-images.githubusercontent.com/79245641/124756959-e78aab80-df4e-11eb-820d-d0a0892220ec.mp4

If 'Share' option is available, you can also directly share the link to Newpipe.
