### ISSUE TITLE
available on pc

### ISSUE THREAD

**Issue by tarbear123** [TeamNewPipe/NewPipe#6629]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?
it will affect everyone that likes newpipe and wants it on pc's

**Comment by ShareASmile** [comment]
Duplicate of #1051

**Comment by Gottarocket** [comment]
Install freetube

**Comment by tarbear123** [comment]
> Install freetube

does it have the features of newtube and is there a windows app?

**Comment by Gottarocket** [comment]
Yes you can download it to all os https://freetubeapp.io/#download
