### ISSUE TITLE
Search and sort newpipe playlists

### ISSUE THREAD

**Issue by chris47368** [TeamNewPipe/NewPipe#6631]
I would find it very useful if I was able to search the name for a playlist I created within newpipe. This will be a very useful feature for someone like me who has dozens of playlists.

Being able to sort playlist order by attributes such as alphabetical order,date created and date modified will also be very useful.

Thanks!

**Comment by SameenAhnaf** [comment]
Please keep the discussion in #3263.

**Comment by TiA4f8R** [comment]
Also, use issues templates the next time you open issue. To do so, create your issue using [GitHub's website](https://github.com/TeamNewPipe/NewPipe/issues/new/choose).
