### ISSUE TITLE
Allow pasting direct YouTube links in the search bar to load a video

### ISSUE THREAD

**Issue by timjefferies** [TeamNewPipe/NewPipe#6635]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it

At the moment I can't see any way to do this. If I want to load a direct link to a YouTube video and it's clickable, then Newpipe can pick that up.

Sometimes though I have the YouTube link in the clipboard, but there is no way to get Newpipe to play it.

It would be great if I could paste the link in the Newpipe search and have it load up the video.

Right now, as a work around I have to WhatsApp/fb message the copied link to myself so I can click on it.

**Comment by TiA4f8R** [comment]
I could not understand your feature request.

> Sometimes though I have the YouTube link in the clipboard, but there is no way to get Newpipe to play it.
>
> It would be great if I could paste the link in the Newpipe search and have it load up the video.

You can already paste a video YouTube URL into NewPipe's search bar to open it in the app. To do so, long press the search bar and use the Paste option, then use the Enter button of your digital keyboard. The video should load in NewPipe.

**Comment by timjefferies** [comment]
You are correct. I made a mistake (it was unrelated to Newpipe)
