### ISSUE TITLE
Feature: Add support for Bitchute

### ISSUE THREAD

**Issue by 2E0PGS** [TeamNewPipe/NewPipe#664]
Feature request for additional platform support.

Since YouTube is becoming more and more censored alot of people are now jumping ship to Bitbchute.

I feel this P2P technology is the future for a decentralized net. Anyway I wonder if it would be a worth while exercise to implement the necessary web-torrent technology (open source) and API code to support Bitchute on Newpipe. 

The other option is possibly wait until someone else makes a Bitchute mobile client which is standalone. Hopefully open source. 

Bitchute website: https://www.bitchute.com

Thanks,
2E0PGS

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by 2E0PGS** [comment]
Web Torrent technology Bitchute uses for backend network: https://github.com/webtorrent/webtorrent
Maybe not worth implementing due to it using a totally different model. Newpipe is currently client - server based. This would need a P2P library added to NewPipe for it to function as intended properly.

**Comment by theScrabi** [comment]
I don't think that would be a good Idea to import an P2P lib into NewPipe. Couldn't we make advantage of their website?

**Comment by mauriciocolli** [comment]
Yeah we can use their "web seeds" to play the video, but that would sort of defeat the purpose, wouldn't it?

**Comment by 2E0PGS** [comment]
@mauriciocolli Indeed I did think that and came to same conclusion.

**Comment by theScrabi** [comment]
I just had this rather strange idea. (Just an idea).
What if we set up server, that do the p2p stuff, and than let the mobile NewPipe client use our server instead of connecting to bitchute directly?

**Comment by KeizerDev** [comment]
What's the idea of p2p then? :stuck_out_tongue:

**Comment by 2E0PGS** [comment]
@theScrabi that's the best option indeed.

**Comment by wb9688** [comment]
@theScrabi: I don't think that's a good option, because that'd cost much bandwidth for your server and Bitchute might contain illegal content and I think you'd be doing illegal stuff if you 'rehost' that content.

**Comment by 2E0PGS** [comment]
they don't promote illegal content... they only promote free speech. Ref illegal content that is the same for any website or even YouTube... anyone can upload something illegal it just takes time for admins to find it. Re hosting illegal well you dont have to rehost for bitchute you can just leech. That would make more sense for this application. However average users separate from this should seed since they can control what they click on but a server with loads of users cannot. If you did a client side webtorrent implementation it would also avoid all these issues!

**Comment by wb9688** [comment]
@2E0PPGS: Well, I haven't really looked into Bitchute. Btw how could they
remove things if it's P2P?

**Comment by 2E0PGS** [comment]
they can remove the indexing of such things. they can also remove the initial web seeds on their own servers but they cannot ofc stop others seeding it still. However if others still seed it they would need to find a way to index that themselfs since bitchute just wont show it on their site. therefore bitchute are not to blame once they stop indexing it and remove any seeds from their servers of the offending content.

**Comment by trymeouteh** [comment]
Adding Bitchute and Dtube support would be great. I do know that Bitchute and DTube are working on their own apps right now too for their platforms. But adding this feature into NewPipe would be a cherry on top for me.

**Comment by theScrabi** [comment]
I am currently working on a tutorial that will enable 3. party devs to add srvices to NP. If your interested give it a try ;D

**Comment by ale5000-git** [comment]
@theScrabi

It would be nice to have something like VLC.
They use scripts in LUA language to add support for opening urls directly, for example a streaming site.

The nice thing is that they are textual script that are executed directly, so you don't need a compiler to create them.

**Comment by theScrabi** [comment]
> urls directly

if it was done by just posting a url directly that was awesome, because that way we could embeded yt-dl. However life is not that easy, if you want to support a service you have to do more, therfore we have the [NewPipeExtractor](https://github.com/teamnewpipe/newpipeextractor).

**Comment by ale5000-git** [comment]
I haven't explained it clearly, for example [this script in lua](https://www.opendesktop.org/p/1154050/) parse the html or xml pages of the RAI website and return a sort of playlist of video streamings or other webpages that can be parsed later with the same script.

I haven't updated it in a while so I'm not sure it is still completely working but I will verify it in the future.

**Comment by TheGoldmasterCorporation** [comment]
love to see this i was going to add this myself. that way we can have popup and background playback from bitchute and dtube

**Comment by kevATin** [comment]
no news on this?

**Comment by trymeouteh** [comment]
It looks like the next update will have Peertube, hopefully Bitchute will get added soon too!

**Comment by hp8wvvvgnj6asjm7** [comment]
This is so important. Can't wait.

**Comment by ramsin31** [comment]
This is now more important than ever, screw YouTube!

**Comment by KonoromiHimaries** [comment]
good idea is use a peertube https://github.com/Chocobozzz/PeerTube/issues/2410#issuecomment-574281081 as cdn or embark, as selfhosted serverless solution https://github.com/embarklabs/embark like cdn https://github.com/Chocobozzz/PeerTube/issues/2115#issuecomment-535620939

**Comment by KonoromiHimaries** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1349

**Comment by grravity** [comment]
Personally am not for adding Bitchute, it requires non-free js to run on site, and is centralized.
Lbry is a better step but not great still.
Imo PeerTube is THE best solution, but it needs uploaders. I'm not entirely sure what the deal is with all the creators flocking over to Bitchute or Lbry is when PeerTube exists, and is absolutely amazing, minus the fact it just needs more people on it.

**Comment by TheAssassin** [comment]
> it requires non-free js to run on site

That's not really a criterion for NewPipe, a completely free software. Servers are often proprietary anyway. Using NewPipe actually allows you to get rid of the non-free JavaScript. We don't have to base decisions on what the original web frontends use therefore.

> Imo PeerTube is THE best solution, but it needs uploaders. I'm not entirely sure what the deal is with all the creators flocking over to Bitchute or Lbry is when PeerTube exists, and is absolutely amazing, minus the fact it just needs more people on it.

Not sure if you're a bit naive there, but it's all about revenue. Making videos costs money. A lot of money. Equipment, time, etc., nobody's paying there. For instance Bitchute allows users to generate some income from their content. I don't see how this would work for PeerTube. You will only get creators to move to this platform if they can compensate their expenses. Not every content creator is in the position to fund it all by themselves, most aren't even interested in this "service to the community" (and there is nothing wrong with that, really!).

Not even the creators have to spend money, though. Video streaming generates a lot of traffic. You need beefy servers with highly capable upstream connections to serve such content. In contrary to e.g., YouTube, PeerTube server owners usually cannot pay for their expenses at least. They kind of donate their service to the community as well.

NewPipe in fact also is a "free rider" for services, considering that using NewPipe generates neither an income for the creator nor the platform. Of course, this can be compensated by asking for voluntary donations, but donations only work out as intended in a few cases. The majority of donation-based services cannot fund themselves completely with that income.

Unless creators (and to some extent platforms) are motivated enough to go for such completely free solutions, we're unlike to see more creators share content there. If you can motivate them (e.g., by sponsoring them via Patreon or ideally Liberapay), why should they move away?

Unless you can come up with funding models, you're really requesting too much, @grravity.

**Comment by kakolisgay** [comment]
Bumping this. Bitchute is a genuine alternative to YouTube at this point, if YouTube is supposed by NewPipe then BitChute should seriously be considered. Especially when PeerTube is supported despite having significantly less of a community

**Comment by TobiGr** [comment]
See https://github.com/TeamNewPipe/NewPipeExtractor/pull/325#issuecomment-626801193
