### ISSUE TITLE
Playlist with more than 101 videos 

### ISSUE THREAD

**Issue by MissMisana** [TeamNewPipe/NewPipe#6644]
I am using Newpipe 21.5 and it has been a few updates since I have this problem where playlists with more than 101 videos write that there is no video (whereas on the YouTube App the videos and Playlists are working correctly). I never reported this issue as I was hoping it would be fixed in future updates.

**Comment by mhmdanas** [comment]
Please give an example of such a playlist.

**Comment by MissMisana** [comment]
Hello,I have attached to this email two screens (one for the playlist name (even if it is for several playlists that I have saved) and a screen when I open the playlist).Cordially.Have a nice day.Le 11 juil. 2021 21:30, Mohammed Anas ***@***.***> a écrit :
Please give an example of such a playlist.

**Comment by MissMisana** [comment]
The second did not join.Le 12 juil. 2021 14:21, Miss Misana ***@***.***> a écrit :Hello,I have attached to this email two screens (one for the playlist name (even if it is for several playlists that I have saved) and a screen when I open the playlist).Cordially.Have a nice day.Le 11 juil. 2021 21:30, Mohammed Anas ***@***.***> a écrit :
Please give an example of such a playlist.

**Comment by mhmdanas** [comment]
I am sorry, but it seems like GitHub doesn't show e-mail attachments in its UI. To make it easier for me and you, could you give direct links to those playlists?

**Comment by MissMisana** [comment]
Here are some playlist links having over 101 videos.- https://www.youtube.com/playlist?list=PLsK0gCOg4x1f_-bnjsxKaOG6AOy0qDnGF- https://www.youtube.com/playlist?list=PLCeAl6UQGbsz1o6UskrjoiGECD4RfNz3Y- https://www.youtube.com/playlist?list=PLrb6ANHv_X8P7yWh76QCRlU7c8fTjvKbuLe 12 juil. 2021 14:48, Mohammed Anas ***@***.***> a écrit :
I am sorry, but it seems like GitHub doesn't show e-mail attachments in its UI. To make it easier for me and you, could you give direct links to those playlists?

**Comment by chrstfer** [comment]
@MissMisana not trying to nitpick, just help you get this issue solved faster, but.... youll have much better luck if you get over here to the site and follow the requested formatting guidelines and tell us the requested info. Everyone here has to make the decisions on where to budget their donated time in order to beat serve this project, and that choice is rarely gonna end up picking the terse unformatted email-reply without any of the specifics easily findable in a nice issue-info table.

**Comment by litetex** [comment]
Closing this issue for now, because
* Links are dead
* No feedback
* doesn't follow template
