### ISSUE TITLE
Add smart cache or auto cache system for yt soundcloud and etcc...

### ISSUE THREAD

**Issue by nine07** [TeamNewPipe/NewPipe#6646]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by mhmdanas** [comment]
Sorry, your suggestion is not clear. Please fill in the template properly and then I'll re-open this issue.
