### ISSUE TITLE
recaptcha loop hell since three months!

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#6653]

**Comment by SameenAhnaf** [comment]
It will be fixed by#6464.

**Comment by mhmdanas** [comment]
@hp8wvvvgnj6asjm7 I understand that you are frustrated, but keeping opening an issue for this over and over won't magically fix it, and serves only to clutter the issue tracker. You are free to use #6464 for now, as @SameenAhnaf says.

**Comment by nadiration** [comment]
> @hp8wvvvgnj6asjm7 I understand that you are frustrated, but keeping opening an issue for this over and over won't magically fix it, and serves only to clutter the issue tracker. You are free to use #6464 for now, as @SameenAhnaf says.

@mhmdanas You know #6464 doesn't work. I've been in this captcha loop for like two and half months tried everything and nothing works except for when i use vpn! Wich may seem opposite but i don't like using vpn all the time so sadly i uninstalled newpipe. I hope someone fixes this.

**Comment by mhmdanas** [comment]
@nadiration I am sorry, I was not aware that the PR did not fix the issue for you. Nevertheless, the original point that issue is unnecessary still stands.
