### ISSUE TITLE
I found 2 Newpipe forks on Google Play Store

### ISSUE THREAD

**Issue by Freddie-Green** [TeamNewPipe/NewPipe#6656]
I found 2 Newpipe forks on Google Play Store, one called Video Play Tube (Vanced Play once installed) and another called Pure Tuber

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### Additional context

Video Play Tube/Vanced Play screenshot
![Screenshot_20210713-194039_Vanced Play](https://user-images.githubusercontent.com/44444510/125507666-f8979bb6-1ed4-4c23-ae0d-d15818b4f863.jpg)

Pure Tuber screenshot
![Screenshot_20210713-194356_Pure Tuber](https://user-images.githubusercontent.com/44444510/125507709-bd72a63e-05aa-4ecc-bc6e-0139cf6dd4e8.jpg)

**Comment by litetex** [comment]
Looks like a duplication of #539. 
Anyway thank you for reporting! 😄 


"Vanced Kit" was already reported at https://github.com/TeamNewPipe/NewPipe/issues/539#issuecomment-748435154
"Free Tuber" was already reported at https://github.com/TeamNewPipe/NewPipe/issues/539#issuecomment-850889822
