### ISSUE TITLE
Lyrics should be in place of comments for Music videos

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#6661]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Music videos don't have comments and the space in newpipe app is wasted, we can have lyrics there.
If the song doesn't have lyrics, we can show error for "no lyrics found" insted of "Sorry, something went wrong. REPORT RETRY"

#### Additional context

![Screenshot_20210714-162724_NewPipe](https://user-images.githubusercontent.com/84063610/125612999-f9656f00-9b0c-41af-8ef7-839701e45021.jpg)

here is how youtube music app handles this
![Screenshot_20210714-163928_YouTube Music](https://user-images.githubusercontent.com/84063610/125613000-cfa05b5c-af5b-4403-9642-7088687ff1c0.jpg)
![Screenshot_20210714-163919_YouTube Music](https://user-images.githubusercontent.com/84063610/125613030-91a55cd0-f40f-4a8f-ae83-59d2a1b7aaac.jpg)

#### How will you/everyone benefit from this feature?

Better look and features

**Comment by mhmdanas** [comment]
> Music videos don't have comments and the space in newpipe app is wasted, we can have lyrics there.

Do they actually not have lyrics (as in even in the YouTube app or website), or do you mean that they just show an error on NewPipe currently?

**Comment by castrik** [comment]
they do have lyrics in the official app, I placed a screenshot of the same song playing in newpipe and official app, youtube have lyrics for that song, but newpipe just shows no captions provided and only have option for auto generated captions

I guess newpipe extractor doesn't support fetching lyrics from music videos

also if it does, it should be shown in the blank big space, as it is useless because music videos don't have comments

**Comment by TiA4f8R** [comment]
Note that lyrics are only available in YouTube Music (and on YouTube with subtitles: for autogenerated contents, they are sometimes available but they are autogenerated from a language which doesn't match most of times the language of lyrics; for music videos, they are added by the artist or by the community). I think this request should go with #4844, especially for development purposes (the biggest purpose is the implementation in the extractor).

**Comment by mhmdanas** [comment]
Sorry, that was a stupid mistake. I meant lyrics instead of comments.

**Comment by SameenAhnaf** [comment]
@litetex This issue should be closed in favor of #7375.
