### ISSUE TITLE
0.21.6 Tablets thumbnails+title too big

### ISSUE THREAD

**Issue by onkq** [TeamNewPipe/NewPipe#6664]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open app on a tablet
2. Find all the videos messed up

### Actual behavior

The thumbnails of the videos is too big. See screenshot

### Expected behavior

Its supposed to fit?

### Screenshots/Screen recordings

![image2](https://user-images.githubusercontent.com/84337276/125737081-3006d036-b4a2-4315-8750-d6440256997c.png)

### Device info

 - Android version/Custom ROM version: LineageOS 16. Android 9
 - Device model: SM-T813

Related: #6674

**Comment by skyGtm** [comment]
Have you tried Tablet Mode?
Settings > Appearance > Tablet Mode -> ON

**Comment by onkq** [comment]
Yes. It doesnt change anything. Tried them all. I have tried alot of stuff

**Comment by TobiGr** [comment]
I assume this was caused by fdb6679d2d8eada1a28cb2ab5c6547b15e39538a.
@Stypox Do you have time to take a closer look?
