### ISSUE TITLE
[meta] Press kit

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/NewPipe#667]
Based on the idea of a Wikipedia article described in #666, we should probably create a press kit.

A press kit is a package filled with texts, information, media and other promotional material that magazines, blogs etc. can pick up and use. This should make it easier for media sites to write articles about NewPipe, understand what it actually is, who its developers are and what the primary design goals are.

There's a software called [dopresskit](http://dopresskit.com/) I found on the internet which attempts to make this easier for developers. But I think our designers (CC @TobiGr) could build one that is as awesome as NewPipe and its website.

It would probably be hosted on the website, but I guess we should create a separate repository to maintain the press media.

But first of all: What do you think? Is the idea worth a try? Given the list of references I posted in #666, I think it's time to create more promotional media.

**Comment by TobiGr** [comment]
I think it is a good idea to publish a lot information about NewPipe so other people can use it to promote the app. That is also the idea of the [NewPipe Blog](https://github.com/TeamNewPipe/website/issues/20). Maybe we can combine blog and press kit to get a good news platform by tagging posts as press information. The blog could have a dashboard with general information about NewPipe and a collection of these tagged articles. Another idea is to include the press kit into the blog as a sub page with only static information. 
The problem of the blog solution is wether @theScrabi and others like @TheAssassin have enough time to write more or less frequently articles. But if we have a good plan for the articles' content we can use their information to write a nice Wikipedia entry.

**Comment by TheAssassin** [comment]
A press kit itself serves as a static source of information. A combination with a blog is possible, but they wouldn't share the same information, the press kit would probably be served on some kind of "about" page. Furthermore, I think that the press kit definitely has a higher priority, considering we want to use it for promotion and marketing. NewPipe serves as a more private and lightweigt alternative to the established YouTube app, and we should sell that fact more prominently.

I would be willing to write articles from time to time, they don't have to be super long, and we could collaborate on them, e.g. via Etherpad. Also, it'd be great to see third parties write blog articles. And we could write short relinks to other sites writing about NewPipe, and serve as an aggregator for those. And I could blog about some related projects and things as well, or about e.g. privacy and data protection related topics within the scope of NewPipe.

The primary reason asking third parties to write the Wikipedia article is that Wikipedians prefer independent (well, at least to some extent) people to write about topics. And since we have such a nice community, that might be possible for them with ease.
That said, as mentioned before, those people are invited to write blog articles as well, as soon as we have one.

**Comment by TobiGr** [comment]
I think of something like this, but I don't have any ideas of what I can put on the Factsheet and References & Links page except for some basics information. Maybe you guys can help.
![icon page](https://user-images.githubusercontent.com/17365767/32992874-7f886ea0-cd50-11e7-89a1-c6f47d6690cf.png)
![screenshots page](https://user-images.githubusercontent.com/17365767/32992968-bc4bfd1a-cd51-11e7-8fdc-95a1ac9eec8b.png)
![bildschirmfoto am 2017-11-19 um 17 56 04-fullpage](https://user-images.githubusercontent.com/17365767/32993061-2dc755ce-cd53-11e7-91ce-faf4504b37e7.png)


@TheAssassin You wanted to use another repo for this. I thought to put the press kit to newpipe.schabi.org/press and as we are using the same images and also other resources like Bootstrap, FontAwesome, etc, we can also put it into the website repository. If yes, we can move this discussion to the other repo.

**Comment by TheAssassin** [comment]
@TobiGr looks awesome. I'm fine with the URL you proposed, but I'd like to hear @theScrabi's opinion first.

**Comment by theScrabi** [comment]
Go for it :) very nice 👌

**Comment by TobiGr** [comment]
I have some questions to complete the content:

- We need some contact details for queries. Which information would you like to add about you?
- What do you think about some graphics (Contributions, etc.)?
-

**Comment by TheAssassin** [comment]
> We need some contact details for queries. Which information would you like to add about you?

The e-mail address of Team NewPipe will suffice. See its GitHub profile.

> What do you think about some graphics (Contributions, etc.)?

You mean, screenshots of the contributions summary on GitHub? Please elaborate.

**Comment by TobiGr** [comment]
> You mean, screenshots of the contributions summary on GitHub? Please elaborate.

Yes, something like this. A nice curve so you can see that NewPipe matter to a growing number of people. With the intention that people who see this think that NewPipe is getting more important and is well know in many parts of the world. Maybe something like a map with markings on countries developers come from is possible too.

**Comment by TheAssassin** [comment]
@TobiGr I'd rather provide links than providing outdated screenshots (or introducing the need to update those regularly, even if that could probably be automated with the help of Travis CI and its cron feature -- we could even generate our own style graphs using GitHub's API using our CD, if someone developed that for tables and graphs).

**Comment by TobiGr** [comment]
@theScrabi @TheAssassin A press kit always contains some announcements (In our case I'd say some information about new features, the separation of the extractor #472 or presentations on CCC). Can you give me some texts for that or other information which I could include?

**Comment by theScrabi** [comment]
Hm I should add and mark more announcement Issues.

**Comment by TobiGr** [comment]
@theScrabi The [blog](https://github.com/TobiGr/NewPipe-Blog) is almost ready to use, so maybe it could be the right place for announcements to not spam our GitHub issue tracker. I am going to open a PR for the press kit soon, so you guys can have a look at the content.

**Comment by theScrabi** [comment]
All right, I prepare for it. We should write an initial block post where we announce the block :)

**Comment by TobiGr** [comment]
We can close this now. I don't have permission to do that.

**Comment by TheAssassin** [comment]
You should be able to now. Check your mails.

**Comment by TobiGr** [comment]
Thanks
