### ISSUE TITLE
No option to download audio of video

### ISSUE THREAD

**Issue by dewijones92** [TeamNewPipe/NewPipe#6670]
### Checklist

- [x] I am using the latest version - 0.21.6 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to https://youtu.be/i6e-YTOzkT0
2. Press Download

### Actual behavior

No option to download audio, just the video

### Expected behavior

There should be an option to download audio too

### Device info

 - Android version/Custom ROM version: 11
 - Device model: Pixel 4a

**Comment by TiA4f8R** [comment]
Unfortunately, this is a YouTube issue: there are no adaptive formats returned by the website (audio and video only formats): there are only video formats with audio in the same file (called formats in the player response of YouTube). So we cannot do nothing about this, You should wait until YouTube adds adaptive formats or you can extract the audio from the video (the one of 720p stream is the audio with the highest bitrate (128 kbps)). Closing this issue.

**Comment by dewijones92** [comment]
@TiA4f8R  thanks
