### ISSUE TITLE
Option to save for watch later videos when shared to newpipe

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6671]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

A bookmark include option and your list of bookmarks

#### Is your feature request related to a problem? Please describe it

I want to watch a link of a video on social media later but I can't. I have to create popup window, load the video then close the video and finally look at the history later

#### How will you/everyone benefit from this feature?

People could watch a video they have been keeping off for later and not forget about it

**Comment by SameenAhnaf** [comment]
I'd recommend you to keep the discussion in #5858.
