### ISSUE TITLE
Can't Play or resume a video (not live or Stream). NewPipe should have a option to reset played video status (to watch from start irrespective of resume settings).

### ISSUE THREAD

**Issue by saharandinesh** [TeamNewPipe/NewPipe#6676]
### Checklist

- [x] I am using the latest version - 21.6 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Turn on Resume video option in New Pipe 21.6
2. Start any video and pause at any point before ending video.
3. Minimize New Pipe (press home button or relevant gesture) {it does't mean you're playing in background}
4. Keep phone locked for a while. (to enforce Deep sleep/Doze).
5. Now open New Pipe (which we minimized) and Tap Play button of paused video (video from step 2).
6. Now it will not play video either from puased point or start but will throw error "could not play this stream".

**This video not played until i forcefully ended it by seeking forward, not even played after app force close or phone restart.**

Encountered with one video others are working fine, i guess open video cant save its Crucial background data for playback later.

### Actual behavior

It should throw a error for any video "Could not play this stream" (no matter that video was stream/live/normal video).

### Device info

 - Android version/Custom ROM version: 10/Miui 12.0.3
 - Device model: Mi 9T Pro

**Comment by SameenAhnaf** [comment]
Could you please share how you set up these three settings? As our devices have the same software, I should be able to reproduce the bug.

<details><summary> Settings>Video and Audio> Minimize on app switch </summary>

![IMG_20210716_093628](https://user-images.githubusercontent.com/79245641/125888168-4185232c-c743-42bf-ab0f-09488068ca51.jpg)

</details>

<details><summary> Settings>Video and Audio> Resume playing </summary>

![IMG_20210716_093527](https://user-images.githubusercontent.com/79245641/125888226-05f79812-2dcd-4f36-8e21-135d6c98aa41.jpg)

</details>

<details><summary> Settings>History and Cache> Resume playback </summary>

![IMG_20210716_093451](https://user-images.githubusercontent.com/79245641/125888351-b4010500-8dde-4d95-b82b-0aa98b2dd8c3.jpg)

</details>

**Comment by saharandinesh** [comment]
1. Screenshot 
![IMG_20210716_091725.jpg](https://user-images.githubusercontent.com/77373581/125888943-ee29b3f0-cdb9-4e02-ab9b-978efd703b7e.jpg)

2. Screenshot
![IMG_20210716_091658.jpg](https://user-images.githubusercontent.com/77373581/125888973-ae3109ee-86c5-4e1b-99ac-878fee82108a.jpg)

3. Screenshot
![IMG_20210716_091725.jpg](https://user-images.githubusercontent.com/77373581/125888986-d7a780b4-0a8f-40fb-8bfa-3759116b41b0.jpg)

**Comment by saharandinesh** [comment]
1. Screenshot
```
![IMG_20210716_091725.jpg](https://user-images.githubusercontent.com/77373581/125889101-53ce38eb-f687-4a3b-9927-b81bc504b6b6.jpg)
```

2. Screenshot 
```
![IMG_20210716_091658.jpg](https://user-images.githubusercontent.com/77373581/125889116-567a7091-f1e3-4d20-b17e-fe537d991b0c.jpg)
```

3. Screenshot
```
![IMG_20210716_091618.jpg](https://user-images.githubusercontent.com/77373581/125889129-cde1ebf6-061c-4b21-b726-d4520e0039ad.jpg)
```

**Comment by saharandinesh** [comment]
1. Screenshot  `![IMG_20210716_091725.jpg](https://user-images.githubusercontent.com/77373581/125889443-61aa4d75-6cea-4a9b-95af-93ca420412e6.jpg)`

2. Screenshot `![IMG_20210716_091658.jpg](https://user-images.githubusercontent.com/77373581/125889454-e4d29124-8f37-45b9-a84b-44e128731692.jpg)`

3. Screenshot `![IMG_20210716_091618.jpg](https://user-images.githubusercontent.com/77373581/125889467-3649bd97-ba88-423e-8778-3d7eb93bfbbe.jpg)`

**Comment by SameenAhnaf** [comment]
>Encountered with one video others are working fine, i guess open video cant save its Crucial background data for playback later.

Hmm, I guess it's limited to a certain number of videos then. Could you please share the video link you are facing the bug with?

**Comment by saharandinesh** [comment]
> >Encountered with one video others are working fine, i guess open video cant save its Crucial background data for playback later.
> 
> Hmm, I guess it's limited to a certain number of videos then. Could you please share the video link you are facing the bug with?

Still can't play it (though recently played by forced seek-forward and then it played normally)

**But after closing app and reopening it shows resumable video as in screenshot, and without any error just can't play, only buffering ring appears, no data fectch from server.

![IMG_20210716_100452.jpg](https://user-images.githubusercontent.com/77373581/125892718-be0268b4-aa26-4e43-bc76-5322e59c6c48.jpg)

Link for video : https://www.youtube.com/watch?v=kxfoXfjs0bk

**Comment by skyGtm** [comment]
It's always tedious to dig into settings to enable and disable things.
what do you think of the idea mentioned in https://github.com/TeamNewPipe/NewPipe/issues/6380

**Comment by saharandinesh** [comment]
> It's always tedious to dig into settings to enable and disable things.
> what do you think of the idea mentioned in https://github.com/TeamNewPipe/NewPipe/issues/6380

Agree, that popup confirmation is a must have feature for this app.
