### ISSUE TITLE
In Download Dialog UI, margin is not even

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#6677]
### Checklist

- [x] I am using the latest version - v0.21.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Try to download any video
2. When dialog box shows up Click the Radio Buttons
- Video 
- Audio 
- Captions
_I have marked the region I am talking about._

![a](https://user-images.githubusercontent.com/50160188/125912963-398147dc-bd01-45ef-8fd9-22973bf05f3e.jpg)
![b](https://user-images.githubusercontent.com/50160188/125912976-e557c74d-0789-4aab-85d0-13ceb674e8f4.jpg)

### Actual behavior

The margin seems like more than needed and is uneven.

### Expected behavior

Even margin for marked region.
Or may be some redesign I purposed in https://github.com/TeamNewPipe/NewPipe/issues/5508

### Device info

 - Android version/Custom ROM version: 9 Pie
 - Device model: Huawei Nova 3i

**Comment by litetex** [comment]
Looks like the offset is caused by a not existing mute button:
![grafik](https://user-images.githubusercontent.com/40789489/126001439-064dfd81-967a-4dea-8e9b-a5e27988392e.png)

Related code:
* https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/layout/stream_quality_item.xml
* https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java#L110-L124

**Comment by TobiGr** [comment]
That's what I got yesterday while trying to fix the bug. No idea what that means.
```
2021-07-18 12:10:36.273 4130-4130/org.schabi.newpipe.debug D/DownloadManagerService: onCreate
2021-07-18 12:10:36.274 4130-4130/org.schabi.newpipe.debug D/DownloadManager: new DownloadManager instance. 0x3cf70ef
2021-07-18 12:10:36.283 4130-4130/org.schabi.newpipe.debug D/skia: --- Failed to create image decoder with message 'unimplemented'
```
