### ISSUE TITLE
[SUGGESTION] Remote party (aka watch/hear videos/music in synch with others)

### ISSUE THREAD

**Issue by forart** [TeamNewPipe/NewPipe#6679]
There are many interesting open projects that realize this, but it would be really cool to have this feature embedded in player.

Some - maybe - useful resources:
- https://github.com/ahmedsadman/redparty
- https://github.com/nsht/stream_sync
- https://github.com/fishuke/ytmparty
- https://github.com/sk89q/theater-with-friends
- https://github.com/ZalakBhojani/Youtube-Party
- https://github.com/tusharmoraye/WatchYoutubeTogether

Hope that inspires !

**Comment by mhmdanas** [comment]
Please open a new issue that follows the template properly. Thanks!
