### ISSUE TITLE
[SAVE DATA] How to save my subscriptions, playlists etc.?

### ISSUE THREAD

**Issue by LavenderSolus** [TeamNewPipe/NewPipe#6694]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Is there a way to save all my subscriptions and playlists (that I made here in NewPipe), so that if I uninstall the app for some reason, and when I install back I don't have to set up all again? (Like an account or something?)

**Comment by mhmdanas** [comment]
You can export your database by pressing Settings > Content > Export database. You can import it by pressing Settings > Content > Import database.
