### ISSUE TITLE
Too hard to tell Newpipe from official apps

### ISSUE THREAD

**Issue by jidanni** [TeamNewPipe/NewPipe#6699]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?
 Currently this app's color is red and white.

By coincidence, those are the same colors that YouTube uses.

Therefore, please choose some other colors!

When using the app, as the app's name does not appear anywhere on the page, I have to double-check that I'm not at that I am not actually using YouTube.

Sure, there are differences between this app and YouTube, but if this app was all blue, it will be easier to tell at a glance what app I'm using.

**Comment by mhmdanas** [comment]
Each service has its own color which is used when it is open (e.g. YouTube is red, SoundCloud is yellow, Bandcamp is blue). I believe changing YouTube's colors to blue will break this convention, but maybe customization for each service's color would solve this use case.

**Comment by jidanni** [comment]
I see. In my little world I only use the YouTube part of this app. Maybe making it red but with zebra stripes would help.

**Comment by jidanni** [comment]
In fact, with so many parts of the app looking so much like parts of the official website, for instance the subscribe button, you're walking a thin line against one day getting sued by the YouTube Corporation. So I would start to make it look a little different.

**Comment by jidanni** [comment]
Somewhat related: https://github.com/indywidualny/FaceSlim/issues/25

**Comment by XiangRongLin** [comment]
> 
> 
> In fact, with so many parts of the app looking so much like parts of the official website, for instance the subscribe button, you're walking a thin line against one day getting sued by the YouTube Corporation. So I would start to make it look a little different.

@jidanni You do realize that NewPipe crawling YouTube is a way bigger problem than NewPipe looking similiar to the official app.

**Comment by mhmdanas** [comment]
@XiangRongLin it's not likely to be a problem. See https://github.com/TeamNewPipe/NewPipe/issues/969#issuecomment-355787851.

**Comment by chrstfer** [comment]
I think scraping api's that have intentionally been served for the public is implicitly allowed, but thats kind of an unsettled question in US Federal Law.

Back to the matter at hand: Im not fully convinced it actually looks similar enough, but either way i think that for similar reasons to the scraping Newpipe ends up in the clear. 

I'm fully, enthusiastically in support of theming though, maybe implementing something similar to how the simplemobiletools.com/ apps can all sync themes.

**Comment by CharString** [comment]
I have the dark theme set, and they differ like night and day!

**Comment by jidanni** [comment]
The official YouTube app seems to be in a dark theme when viewing an individual movie too these days...
But it doesn't matter.
I'm not talking about an actual slice in time.
I'm talking about years of accumulated impressions of the official YouTube website and app:
Red, white, black, and their font choices etc.
I swear, especially as there is no "branding on the page" (of Newpipe, in at least some views) I can't be sure of what app I am using, at least at a glance.

**Comment by chrstfer** [comment]
I find it pretty obvious, but also thats simply gonna happen in an app ecosystem based on a predefined set of design guidelines and libraries/components. I dont think this is really an issue so much as a philosophical discussion and matter of opinion. Newpipe doesn't use any youtube assets or branding, and youtube doesnt own the color red.

**Comment by litetex** [comment]
I think we should close this issue as there is a ton of negative feedback form the community (17 downvotes + comments).
