### ISSUE TITLE
Google Assistant, launching New pipe as default

### ISSUE THREAD

**Issue by lacolos** [TeamNewPipe/NewPipe#670]
It seems if you set the settings in the YouTube app to not open and set New pipe to open YouTube links that Google Assistant will just load the YouTube app anyways. I've tried disabling and force stopping the YouTube app but everytime it launches the YouTube app when asked the "play" command

**Comment by Stypox** [comment]
I think this is a problem with Google Assistant: they probably hardcoded the official Youtube app because they don't want anyone using another client...
