### ISSUE TITLE
Filter the What's New feed by toggling groups on or off

### ISSUE THREAD

**Issue by nurupo** [TeamNewPipe/NewPipe#6703]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Ability to filter either the All Feed or What's New views by excluding Channel Groups from it.

The way I imagine it working, is that either the All Feed or What's New views have a list of all groups at the top, similar to how the Subscriptions view currently has them, which you can press on to toggle the group on/off. There should also be a convenience option to toggle all groups off/on at once. If a group is on, its videos appear in the view, if it's off - they are filtered out.

This functionality doesn't necessarily have to be added to the existing All Feed or What's New views, some new Filtered view could be added if that would make more sense.

#### How will you/everyone benefit from this feature?

Currently the only thing you can do with groups is view a single group's feed, which I find a bit limiting. With this feature, you would be able to filter the feed of all channels by subtracting groups from it, which has more flexibility as you can now have a view that combines multiple groups' feeds.

My personal use case is that I'm subscribed to a lot of channels, and in total they publish 400 videos daily. Depending on the mood, I might want to view all the videos except music and tutorial videos. That's a lot of videos to ignore, so it would be a great help if I could just filter out the Music and Tutorials groups from the feed of all videos.

**Comment by SameenAhnaf** [comment]
@litetex Close in favor of #4334
