### ISSUE TITLE
Sponserblock Integration

### ISSUE THREAD

**Issue by yesNOmaybe69420pogchamp69** [TeamNewPipe/NewPipe#6711]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Is it possible to have sponserblock integration?

#### Is your feature request related to a problem? Please describe it

No, it's not related to a problem

#### Additional context

There's already a fork that has this. Would love to see it in the official app
Here's da fork: https://github.com/polymorphicshade/NewPipe

#### How will you/everyone benefit from this feature?

Sponsers are annoying

**Comment by mhmdanas** [comment]
This idea has already been rejected. See https://github.com/TeamNewPipe/NewPipe/pull/3205.
