### ISSUE TITLE
download location fail in 0.21.6

### ISSUE THREAD

**Issue by ojhadv** [TeamNewPipe/NewPipe#6717]
### Checklist

- [x] I am using the latest version - 0.21.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

When sharing a video from youtube app to newpipe to make download, newpipe 0.21.6 doesn't save it and keeps asking for save location permission- select the phone storage - allow access. Even after allowing access it doesn't save or download anything. Clearing data or reinstall doesn't solve issue, or changing file save location in newpipe download settings keep on repeating to ask fole save permission. Uninstall and installed 0.21.5 version which works fine and download and store everything.
I am using Xiaomi Mi10 miui12.5.5 latest stock rom

### Expected behavior

I expect new pipe 0.21.6 to download my request and save it on my phone.

### Device info

 - Android version/Custom ROM version: Android 11 - Miui Stock 12.5.5
 - Device model: Xiaomi Mi10 pro 5G

**Comment by TobiGr** [comment]
Fixed in 0.21.7
