### ISSUE TITLE
coudn't watched videos useing mobile internet

### ISSUE THREAD

**Issue by shahariarnavil** [TeamNewPipe/NewPipe#6718]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Screenshots/Screen recordings

![IMG_20210720_231901.jpg](https://user-images.githubusercontent.com/86552801/126367768-d3f33ad0-a81e-4b94-b40d-ce0e3b44273f.jpg)

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by SameenAhnaf** [comment]
Please stop opening same issue over and over again. You may test the APK in #6464 to check if the issue is solved.

Also, please fill in the template properly.
