### ISSUE TITLE
 org.schabi.newpipe.extractor

### ISSUE THREAD

**Issue by limelect** [TeamNewPipe/NewPipe#672]
org.schabi.newpipe.extractor is empty all needed files are not there
like
import org.schabi.newpipe.extractor.stream_info.StreamInfo;
org.schabi.newpipe.extractor.stream_info.VideoStream
How do i get  org.schabi.newpipe.extractor files?

**Comment by wb9688** [comment]
At the moment, NewPipeExtractor is a submodule, so you've to do a recursive
clone (eg. `git clone --recursive
https://github.com/TeamNewPipe/NewPipe.git`). When #669 is merged, it'll be
a Gradle module. Btw the repository of NewPipeExtractor is located at
https://github.com/TeamNewPipe/NewPipeExtractor.git.

**Comment by theScrabi** [comment]
Please wait until the merge.
