### ISSUE TITLE
Please add an option to hide videos form feed pags

### ISSUE THREAD

**Issue by VaradDongre** [TeamNewPipe/NewPipe#6723]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment]
I'm not sure what you mean by 'Feed page'. Please send a screenshot to clarify it.

Also, please fill in the template properly when you open an issue every time.
