### ISSUE TITLE
AAC (M4A) download downloads a corrupted file.

### ISSUE THREAD

**Issue by FrameXX** [TeamNewPipe/NewPipe#6727]
If you download M4A file from YouTube you will find out that downloaded file is corrupted. It's not whole corrupted, but like 1. second of audio is always missing. This is annoying especially when downloading music. If I use opus always get full audio no problem.

Note that I am using latest 0.21.7 version but this bug was already there in the previous version.

**Comment by opusforlife2** [comment]
@FrameXX See https://github.com/TeamNewPipe/NewPipe/issues/2640#issuecomment-873167100.

For future reference, please use the Github website so that you can see and fill the issue template, instead of a 3rd party Github app that doesn't support them.

**Comment by mgolden356** [comment]
I notice that the file tends to be corrupted when it comes from a "Topic" channel, and m4a's from elsewhere are safe.
