### ISSUE TITLE
UI freezes when unbuffered

### ISSUE THREAD

**Issue by gappleto97** [TeamNewPipe/NewPipe#673]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Considering that the biggest thing people will want to do during this state is change to a lower resolution, this is a problem.

**Comment by mauriciocolli** [comment]
Yes, this a problem that I'm having sometimes.

**Comment by Stypox** [comment]
It doesn't seem like this is happening anymore.
![example](https://user-images.githubusercontent.com/36421898/59975726-6bb5a480-95bb-11e9-88b3-e3bad4f57b86.gif)
