### ISSUE TITLE
Dialog box after feed update error in 0.21.6/0.21.7

### ISSUE THREAD

**Issue by chrispembs** [TeamNewPipe/NewPipe#6742]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Why is it necessary to have a dialog box pop up after every feed update error? I have downgraded to 0.21.5 until an option is provided to suppress this x

**Comment by AudricV** [comment]
Is it still an issue on 0.26.1?
