### ISSUE TITLE
Hitbox for scroll bar should be bigger

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#6749]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

currently, the scroll bar on the right is really thin in appearance, but also in actual area where we can grab it it should be easier to hold

#### Is your feature request related to a problem? Please describe it

if we are in a playlist with many videos, the scrollbar becomes so thin, its nearly impossible to hold it
but forget that, if you have a phone with curved edges, the problem becomes even worse

#### How will you/everyone benefit from this feature?

I don't want the scroll bar to become thicker, it looks good as it is, but the hitbox for it is really small, make it so that, the area where we can grab it becomes bigger, di it's easier to handle

**Comment by SameenAhnaf** [comment]
I'd recommend you to keep the discussion in #6544.

**Comment by litetex** [comment]
Closing this in favor of #6544
