### ISSUE TITLE
F-Droid appereance

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#675]
Since F-Droid version 0.103 and later developers have new awesome possibilities to promote their apps. 

At the moment NewPipe looks like almost every other app on F-Droid. We can make the app page more interesting like the devs did it with these apps (from Guardian and F-Droid repo):
- Wikipedia
- Telegram
- Osmand
- Ripple
- Checkey
- Firefox Focus (German Firefox Klar)
Open F-Droid and take a look. It's worth it.

To improve our appearance we should add/change following things:

### Screenshots

Basically screenshots have the function to show the user how the app looks like. [That's the way Telegram](https://gitlab.com/fdroid/fdroiddata/blob/3efc17a03c861de0c7cfdd8f578f82c9bae3d816/metadata/org.telegram.messenger/en-US/phoneScreenshots/04.png) uses the images. I'd prefer to do it [like OSMand](https://gitlab.com/fdroid/fdroiddata/blob/3efc17a03c861de0c7cfdd8f578f82c9bae3d816/metadata/net.osmand.plus/en-US/phoneScreenshots/02.png) and add small texts to the screenshots which explain the screenshot a little further. But we can also create a wallpaper like they did for Firefox Focus (please have a look in F-Droid). 

### Feature Graphic

The feature graphic usually contains the logo and/or a slogan. More information and a collection of good graphics can be found [here](https://gitlab.com/fdroid/artwork/issues/8) and [here](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en). We can use something like [this](https://user-images.githubusercontent.com/17365767/30036456-d312cd00-91b3-11e7-9af6-5a3c728d6060.png). It's a first sketch, so some fine tuning needs to be done, but what do you think of it? @TheAssassin Does it cause license problems when we use the SoundCloud and YouTube logos?

### Changelog

As we already have a changelog in the release details we can copy it to an additional file too, so people can see [directly what changed](https://user-images.githubusercontent.com/17365767/30029261-d68a76a2-9188-11e7-9d7f-63e85ca72e0e.png) before upgrading the app.

### Description

We should improve the app description along with #674.  Furthermore I think we can remove following sentences:
> This a very early version of the app, so not all functionality is implemented, and there may still be a lot of bugs. But all in all it's doing what it is supposed to do. It makes it possible to watch YouTube videos. So don't be cruel to this app. It will improve...

And if our awesome translators have some time left, we can localize the description and screenshots too.

**Comment by TheAssassin** [comment]
@TobiGr see https://www.youtube.com/yt/brand/, https://support.google.com/youtube/answer/6009004?hl=en-GB, 

I wouldn't use the YouTube logo. As they correctly state, their trademark must not be used without consent. I'd rather write out YouTube. Note that therefore, I didn't even bother with copyright issues here.

The situation is similar for SoundCloud. Albeit their logo is not protected by copyright (see e.g., https://commons.wikimedia.org/wiki/File:SoundCloud_logo,_orange_color,_plain.svg), they [hold a trademark as well](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4802:op9q2i.3.1). I wouldn't bother with that either.

Unless someone steps up to them and asks them whether you're allowed to use their trademarks, you must not use them. And I wouldn't bother them too much, as they're most likely no friends of this app.

As usual: this is no legal advice, and can't be held liable for this!

**Comment by theScrabi** [comment]
I don't like the new UI of fdroid. It's not yet elaborate :/
Tho I'd love it once it works proper. So I'd like supporting the features of the new versions. However I'm with @TheAssassin about that YouTube thing. I would still just mention Youtube in the description, but I would not show it in the banner as well as in the screenshots. This not only because of legal reasons, but also because NewPipe is becoming a player not only for Youtube.

**Comment by ildar** [comment]
FYI https://fdroid.gitlab.io/fdroid-website/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by TobiGr** [comment]
@TheAssassin @theScrabi Thanks for your feedback. Here are three other feature graphics. In the [first picture](https://user-images.githubusercontent.com/17365767/30128488-2a40fa94-9343-11e7-91b7-45851cae02bf.png) the NewPipe logo and text are centred. In the [second graphic](https://user-images.githubusercontent.com/17365767/30128979-c854fd88-9344-11e7-97c2-d424e7f9f533.png) I did not centred them but yet I prefer it. [Here](https://user-images.githubusercontent.com/17365767/30132677-7de5e462-9351-11e7-852e-ee60856d434b.png) are the icons a little smaller which also looks pretty good and is better for user who view the app page in landscape mode.

@ildar Thanks for the link. I forgot to add it.

**Comment by theScrabi** [comment]
I like the second.

**Comment by bagelcake** [comment]
While I'm signed on, I'm going through random threads to add my two cents. Sorry.
 
Anyway, I suggest changing the current "Play", "Download", and "Listen" to "Watch", "Listen", and "Save" for several psychological and aesthetic reasons.

**Comment by theScrabi** [comment]
I like it, tho can you try a font with less space between letters, and more bold? :)

**Comment by bagelcake** [comment]
Yeah, I can do that but this is also a crappy mock-up. Do you have a graphics guy?

If not,
Is there a better version of the logo somewhere?
What is the default font for NewPipe?
What is the hexcode for the NewPipe red?
Is that the dimension for the image or are there other specifications?
Include any other relevant things.

**Comment by theScrabi** [comment]
We once had a designer @ponypower, but he left the project.
He created the general design of the website as well as this [slides](https://github.com/TeamNewPipe/NewPipe/blob/dev/CCC_NewPipe_presentation.pdf). He didn't create a CI, but he almost did creating these things. I think if you stick to the design of them you will be good to go.
However @TobiGr created the website, he might also help you out :)

**Comment by TobiGr** [comment]
@bagelcake That looks good.
We use `Arial` on our website. Our primary red is `#CD201F` which is also used in the logo. The secondary red is `#AA1D1D`. You can find a complete stylesheet with other colors [here](https://github.com/TeamNewPipe/website/blob/master/css/style.css). [Here](https://github.com/TeamNewPipe/NewPipe/blob/dev/assets/NP%20logo%20v2.svg) is our logo and [this one](https://github.com/TeamNewPipe/NewPipe/blob/dev/assets/new_pipe_icon_5.svg) is our logo with a shadow. If you need the logo with a border, I can upload it for you.
A feature graphic should be 1024x500. All other specs and some tips are listed [here](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en). If you have any further questions, feel free to ask.

**Comment by bagelcake** [comment]
Psd file available if anyone wants to mess with this.

![npfg 1](https://user-images.githubusercontent.com/32154895/30724759-9afff10c-9f2f-11e7-966e-b78ce904015f.png)
![npfg 2](https://user-images.githubusercontent.com/32154895/30724760-9b02ed44-9f2f-11e7-8082-70fc4d82a703.png)
![npfg 3](https://user-images.githubusercontent.com/32154895/30724761-9b1797b2-9f2f-11e7-88ed-4caeed6a27d5.png)

**Comment by theScrabi** [comment]
Uii I like the second. Fancy 👌

**Comment by TobiGr** [comment]
Yes I like second too. Good job 👍 

> Now we just have to find the best way to store all those files, so fdroid can use them.

If you guys are worried about to much large files in the NewPipe repository, we could open an artwork repository including all images/SVGs from the app and the website. This could also help to find them. 
But I don't know if git supports symlinks.

**Comment by theScrabi** [comment]
Hm this just has to be compatible with what fdroid needs to show the files.

**Comment by wb9688** [comment]
@TobiGr: Git doesn't have cross-repository symlinks, but Git does have
submodules.

Btw what's the difference between the second and the third?

**Comment by TobiGr** [comment]
I don't want to move all file. I just want to move the old icons and the unused SVGs. So basically some stuff from `/assets`. That should be possible.

**Comment by wb9688** [comment]
The assets are included in the F-Droid data repository. See OsmAnd for an
example at
https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/net.osmand.plus/en-US
.

**Comment by theScrabi** [comment]
But isn't this something to prevent, i remember to have red that its' possible, but they don't like it.

**Comment by theScrabi** [comment]
I added fastlane support:
https://github.com/TeamNewPipe/NewPipe/tree/fastlane

**Comment by mueller-ma** [comment]
Remeber:

> The last important detail is that the texts in the app’s metadata file will override all other descriptive texts from Fastlane/Triple-T. That is specifically Name/AutoName, Summary, and Description. Once an app’s descriptive texts have been moved into the source repo, then file a merge request or issue to remove Summary and Description from the app’s metadata file.

from https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#directly-in-the-f-droid-repo

**Comment by TobiGr** [comment]
@theScrabi Can you please consider to add a changelog file for future releases? Just sum up the most notable changes and store them in a file:
`fastlane/metadata/android/en-US/changelogs/VERSION_CODE.txt`
This is just a minute of work for you, but a nice feature for people using F-Droid and a time saver for people writing the "[This week in F-Droid](https://f-droid.org/en/2018/05/11/this-week-in-fdroid-w19.html#updated-apps)" post. And as I've said before, I'd like to integrate the changelog on the website too. I can't use the GitHub release notes, because they contain to  much information.

**Comment by wb9688** [comment]
I'm closing this due to those things now being in our F-Droid listing
