### ISSUE TITLE
AuroraStore-like anonymous account login

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#6762]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

For those unaware, Aurora Store is a foss app that allows users to login to the Google Play Store using anonymous accounts created by Aurora. I don't know exactly how they do it, but the first connection made by the app is to a domain that is hosted by the developer. From there it then connects to some google servers and logs in. You can also spoof the location and/or device, allowing you to download and install apps from other countries and ones that are specific to certain devices. It's a great way to login to google without having to worry about privacy implications. Furthermore, compared to all the connections made by the original Google Play Store app, Aurora Store only makes the essential ones so you can update, download, install, search, etc. It doesn't allow for app purchases or leaving ratings for apps. If this seems like a tall order, well, Aurora Store is open source. Perhaps you could utilize that portion of the dev's code - and switch what's necessary - or even collaborate with him to use the same accounts he uses for Aurora Store users. The dev is really good at what he does and may welcome a collaborative effort since he also values privacy. Please see the project here: https://gitlab.com/AuroraOSS/AuroraStore. The website is https://auroraoss.com.

My suggestion is to offer the same function, only for logging into youtube using an anonymous account. Since playlists and history, etc, are all stored locally on NewPipe, this wouldn't interfere with that. Making comments and liking/disliking can still be disabled as well. Why, you may ask? See below.

#### Is your feature request related to a problem? Please describe it

Yes. Logging in to an anonymous account would - hopefully - permanently fix the age restriction #6726 and captcha - #6311 & others - issues. I'm not knowledgeable enough to know if it could help with throttling #6673 but maybe it could. It might help with other things I'm unaware of too.

#### How will you/everyone benefit from this feature?

This will potentially solve a ton of problems - perhaps long-term - while still preserving the privacy that NewPipe strives to offer its users.

**Comment by castrik** [comment]
I think Newpipe's goal was to give as little amount of data to google as possible
if you have an account and write comments, like videos and watch videos, that will help train google's ai

but if devs bring this feature as an option, I think many would love this

also, google can know who this anonymous account is, since if someone has an account and uses same device/ip address to use both accounts and watch same types of videos, google won't be stupid enough to know who this anonymous user is, that would render newpipe kinda useless and just another youtube client

**Comment by infinitewaveparticle** [comment]
@castrik I agree that such an implementation needs to limit the amount of data shared with google. For one, writing comments should be disabled, same with liking/disliking. Also, as far as I know, Aurora Store uses only a small number of anonymous accounts to do this (not one per user)... so if it's enacted in NewPipe the same anonymous account would have tons of IP addresses and watch histories. NewPipe already limits the data sent to Google to what's absolutely necessary for it to function. My knowledge about this is limited, but could it be possible to modify the tracking parameters set by youtube's (googlevideo.com's) https traffic? If you look at the traffic there are, I believe, two parameters that track IP addresses - "ip" and "mip". These could be set to always be youtube's (or whatever's) IP address or even set to be a different, randonly generated IP address for each video (limited to valid, non-blacklisted IP addresses, of course).

Furthermore, if a NewPipe user logs in anonymously, all traffic could be routed through a server between the user and Google (is this what invidio.us does?), effectively making everyone's traffic coming from an IP address associated with no individual.

Another idea is to simply use these anonymous accounts only for age-restricted videos... so when someone clicks to watch an age-restricted video a popup asks the user to login anonymously. Afterwards, clicking on any video that doesn't require age verification could automatically log the user out and return to normal newpipe youtube browsing (assuming other issues are fixed).

**Comment by infinitewaveparticle** [comment]
With the limitations and features and possibilities listed in my comment above this is a game-changing idea if someone can implement it.

**Comment by Stypox** [comment]
NewPipe will not implement Google login

**Comment by infinitewaveparticle** [comment]
I'm not suggesting that you implement an option for users to login with their own google accounts, but rather shared anonymous accounts. If you fully study what Aurora Store does you should find my suggestion quite interesting, as it doesn't give Google anyone's personal data... and you could likely code such an implementation to not only send Google completely junk data, but also prevent NewPipe from using any of the data returned from Google's algorithms. The main point is to completely and 100% defeat the age restrictions and other issues that arise from not being logged in. Is such an implementation easy? No, but you'd have the most amazing YouTube app in existence if you pulled it off. Perhaps someone who has both the time and the knowledge should try to tackle this one day. The creator of Aurora Store may even be willing to help, as I believe he did it himself with his anonymous version of Google Play Store, which continues to work flawlessly to this day.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
* ^ @Stypox ^ (sorry, can't edit via email)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by 0xc0000007b** [comment]
> If you fully study what Aurora Store does you should find my suggestion quite interesting, as it doesn't give Google anyone's personal data...

Arguably an IP address is all that's necessary for Goolag to know exactly who you are. Perhaps you will inspire someone to take a crack at this, though I don't personally see it as a necessity whereas Aurora Store has to implement such a feature (although Huawei is quickly erroding that need as is F-Droid and friends).

**Comment by infinitewaveparticle** [comment]
I trust the goolag.store site, as it's registered to Aurora (its creator). If it were Google's site I wouldn't trust it at all. goolag.store provides the auth tokens that allow you to login to the Play Store. I think if it were forwarding people's IPs to Google, then Google would surely have blocked their actual accounts or IPs by now. My thought is that Aurora might spoof a permanently whitelisted IP for everyone's connection... Either that, or if Google doesn't blacklist IPs, then perhaps everyone just openly seems to be coming from the same IP address in India (goolag.store's IP). That would at least make each login seem to come from the same place and therefore seem like they're good accounts (albeit with many, many different devices). Aurora used to go down all the time, but since their latest update (several months ago) to 4.07 there doesn't seem to be any further changes made and it's still working very, VERY well despite a couple annoying bugs present when trying to download/update a small number of apps. I also use a double VPN all the time and change servers regularly anyway.

Note you can also spoof almost anything with the Aurora Store such as your
device or your sdk level or your language and you can maintain multiple
accounts. The search on Aurora is fantastic too and far better than anything
you'd ever get on the Play Store. Another very useful feature is that the Aurora Store automatically saves all
your APK downloads (or it can automatically delete them, as you wish).

And yeah, I definitely use a ton of different app stores and apkmirror. I hadn't used any version of Google Play Store for years until Aurora came along, but I really enjoy the usefulness and efficiency of it. You can find most apps on the Play Store in other places, but not the way Aurora presents them. It's a genius app built and maintained primarily by one guy.

I do hope I will inspire someone to take a crack at it, and hey... Maybe if you reached out to Aurora's dev he might agree to help implement the login part of it using the same system, only on your server (newpipe.net) instead of his (goolag.store). From there someone else would have to parse the incoming/outgoing data to keep it inline with NewPipe's values and intentions... But if the implementation worked as well as Aurora Store's does it certainly would defeat many recurring issues.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by 0xc0000007b** [comment]
Thanks for the info. Curious which issues adding a login might address other than getting at private content?

**Comment by infinitewaveparticle** [comment]
In addition to age-restricted content I believe some people are still having some issues with buffering as well... It should also be able to set some cookies that do away with any potential captcha issues. Tricking YouTube into thinking you're logged in to a personal account and using an IP address that isn't problematic should give users at least the same viewing experience as using the YouTube app or Vanced.

If this and other Feature Requests (for example, adding strong, specific search parameters, filters, list organization - like "By Date", "By Creator", "By Length", "By Views", "By Like Count", etc), were implemented, NewPipe would quickly become the most popular YouTube viewing app on Earth.

Sent from ProtonMail mobile

-------- Original Message --------
