### ISSUE TITLE
Cannot play age limited videos

### ISSUE THREAD

**Issue by clauz07** [TeamNewPipe/NewPipe#6764]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by iiSnewoNL** [comment]
+1

**Comment by Mrnobody1411** [comment]
I'm having the same problem right now

**Comment by bookkojot** [comment]
Bump issue
