### ISSUE TITLE
Add the option to let us CLEAR the list of videos that Newpipe downloaded.

### ISSUE THREAD

**Issue by shuttittuppitt** [TeamNewPipe/NewPipe#6765]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

I have looked at SOME of the issues (both open & closed), but I won't lie & claim that I searched through ALL of them. IF there is a way to SEARCH them, I could be more certain that I'm not accidentally duplicating another issue, but I can't find a "search" option for issues either.

- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

Yes, I HAVE read that file/link/whatever.

- [x ] This issue contains only one feature request. I will open one issue for every feature I want to request.

Okay.

#### Describe the feature you want

I have no idea if the above stuff is REQUIRED to be INCLUDED in any new issue from now on, but the way that the "warning" part of all of that (currently) reads makes it sound easier to just include it in case somebody decides that it DOES have to be included. If it's NOT REQUIRED to be included in a new issue, feel free to remove it (if that's possible.)

Anyway, here's the feature request. (It might have been this way for much longer than I noticed, because I only started DOWNLOADING videos recently.) Anyway, in Newpipe's list of "Downloads", it shows videos that you downloaded with it. However, I have NOT found a way to CLEAR that list. (If there IS a already a way to do that, then it is harder to find than it should be.) Actually, I assume that DELETING those videos would remove them from that list, but I don't WANT to DELETE them. So, either add a way for us to clear Newpipe's "Downloads" list (without us having to delete those videos), or if that feature already exists, make it easier to find it. Thank you.

**Comment by SameenAhnaf** [comment]
This option in the screenshot will only clear download history, not the files.
![IMG_20210726_051721](https://user-images.githubusercontent.com/79245641/126916524-4a64bdb5-17d9-4360-a3d5-769d7f12ef13.jpg)

**Comment by mhmdanas** [comment]
@shuttittuppitt I think that it can't get any easier to find than a button with a trash icon which shows a dialog with pretty explicit text for its buttons. Do you perhaps have any suggestions?

**Comment by shuttittuppitt** [comment]
@mhmdanas
I DID (& still do) see the trash can icon, but I never tried to use it because MOST programs use that icon to mean DELETING something. So I think that either that icon needs to be replaced with a different icon, or else replace it with a short TEXT (example = Clear downloaded history).

I promise you that I'm NOT the only user who has simply TOLERATED having a constantly growing downloads list just because the developers didn't realize that HIDING the option to clear the downloads list behind a trash can icon could cause confusion.

**Comment by opusforlife2** [comment]
You could simply take a database backup and try the button. There was no need for the extreme caution you seemed to have been operating under.

Anyway, this was not an enhancement, but a question, which has been answered.
