### ISSUE TITLE
Implementing Sponsorblock API in NewPipe

### ISSUE THREAD

**Issue by Loki-L1130** [TeamNewPipe/NewPipe#6774]
How about implementing [SponsorBlock](https://github.com/ajayyy/SponsorBlock) API as it was made in YouTube Vanced ?

**Comment by SameenAhnaf** [comment]
Devs don't want it. See: #3205.

**Comment by TiA4f8R** [comment]
@SameenAhnaf is right. I am closing this issue.

Also, please don't remove the template when opening an issue, there are good reasons to keep it, like to prevent duplicates.

**Comment by SameenAhnaf** [comment]
@TiA4f8R How am I supposed to know if a user didn't receive the template at all? I used to type, "Also, please fill in the template properly." But I don't know how to figure that out.

Note that I'm using mobile GitHub website.

**Comment by mhmdanas** [comment]
@SameenAhnaf if a label was not automatically applied to the issue, then they were probably not shown the templates.
