### ISSUE TITLE
Folders for subscriptions

### ISSUE THREAD

**Issue by abelfn** [TeamNewPipe/NewPipe#6777]
### Checklist

- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I have read this:-

https://github.com/TeamNewPipe/NewPipe/issues/6446

and this

https://github.com/TeamNewPipe/NewPipe/issues/797

The already implemented channel group loads feeds from the subscriptions added to channel group.

But what i want is subscriptions to be added to channel group not their feeds.

EX:-Gameplay subscriptions inside Gameplay channel folder not the Gameplay subscription feeds.

#### Is your feature request related to a problem? Please describe it

Channel group is not organizing subscriptions it only groups subscriptions feed added to the channel group.

It's creating a mess!

#### How will you/everyone benefit from this feature?

Makes it easy to organize subscriptions.

**Comment by SameenAhnaf** [comment]
Do you want a way to access "Channel list of group"?

**Comment by abelfn** [comment]
Yes, but right now if i create new channel group let's say Gameplay and from select subscriptions l select theRadBrad and create the group,going to channel Gameplay folder and click you will get theRadBrad channel videos not theRadBrad channel as list

Gameplay channel group:-
  1.theRadBrad
  2.MKIceAndFire
  3. ...etc

**Comment by SameenAhnaf** [comment]
Then, this issue is a duplicate of #5592.

**Comment by abelfn** [comment]
I didn't see that.
