### ISSUE TITLE
[FR] Precaching video for offline use

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#678]
Once for a very short period YouTube entered a feature: user could start viewing video on a broadband connection and then go on at mobile internet. The Google app cached the video so user could have no problem finishing his video.
I wonder if devs and users like the feature now?

**Comment by theScrabi** [comment]
Well you could download the video an than watch ir on the go.

**Comment by ildar** [comment]
Yep! And that's good indeed.
What do you think about the initial idea?

**Comment by theScrabi** [comment]
In my opinion it's the same. So I wouldn't think it's worth the effort.

**Comment by ildar** [comment]
The difference is in need for cleanup versus app doing that for you
