### ISSUE TITLE
After Subscription-Update Channel Group is "stuck in the past"

### ISSUE THREAD

**Issue by d-albrecht** [TeamNewPipe/NewPipe#6781]
### Checklist

- [x] I am using the latest version - 0.21.7 from f-droid, issue already existed on 0.21.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Note: This only works if at least one of the included channels has a new video posted that the app hasn't received yet, so you might have to check this precondition with a different device or have to be a bit lucky with when you try to reload the channel information. Any attempts to look this up in the same app will prevent the issue from showing up!
1. Open the app
2. Switch to the "Subscription"-Tab
3. Select a Channel Group
4. Swipe down to reload the channel information for the channels included in this group (might also work with the default "All" group but given the mentioned problem that there has to be an update to load for this issue to occur, I haven't checked every single possibility, for me this always happens in the one group I'm actually interested in).

### Actual behavior

The group view seems to be "stuck" exactly where it was before the information update. So, if there was a video A at the very top of the list, this video will still be at the very top of the screen. If now some newer video is available, this new video B won't be visible at first. Only swiping down will reveal whether there were newer videos or whether the reload hasn't found any updates. In case there were no updates, swiping down will show the "reload-arrow"-indicator (the "if you release the finger now, the app will reload" overlay). If there were updates for the app to fetch, you will see video B sliding in from above video A.

As a little add-on for this bug report, there is the issue that videos in this list can swap positions after reload. But I guess this issue is out of your control. I assume that the video timestamps that YouTube reports to you are inexact and ambiguous such that 
the app simply has no final information to create an ultimate sorting order that will never change. But the reason why I bring this up here is, that through this other phenomenon, videos can "disappear" after a reload. If video A is on top of the list and video B is below video A, but both have more or less the same timestamp, after the reload video B can be sorted above / newer as video A and - as I said - disappear until you swipe back down to reveal that video B was just swapped with video A. But because video A appears to be the anchor point for this view, video B was out of sight after the reload.

I haven't encountered what happens if video A is no longer available (marked as private/unlisted) on its channel. This video seems to be the anchor, so if this video is just gone, the app might even show stranger behavior.

### Expected behavior

With an older version that I used to run until a few days ago (I assume this was 0.21.5 but I'm not exactly sure here, I only check version numbers if something goes wrong ;) ) this view behaved exactly like I would assume this view to still work. If I swipe down to update the information, I have to be at the top of the list (otherwise swiping down would simply scroll up the list). So after the update-process finished I expect to still be at the top of the list. If you update the information with the small arrow-button, this might not be the same (I could see an argument that if you use the arrow-button you might want to stay at the position you were before especially because you don't have to be at the top of the list to update using the arrow-button), but the swiping method clearly indicates (to me) that I want to be at the top of the list, and not somewhere far down the list (depending on the number of videos that were published since I last updated the list).

That means that if there are updates in the group, I want the known videos to actually move down (as they did in the older version of the app) and the newly published videos to be actually and immediately visible. With this new behavior of the Channel Group update process, I don't get any visual feedback on whether the update found new videos or not unless I swipe down again. That is highly inconvenient.

### Screenshots/Screen recordings

I could try to screen record this, but this would need a decent set up for me (I haven't tried screen recording before, so I had to get familiar with that first), so unless my description isn't clear enough, I hope no recordings is fine, too.

### Logs

No technical error, so no error log for this issue.

### Device info

 - Android version/Custom ROM version: Android 7.1.2 / Fairphone Open 19.05.2
 - Device model: Fairphone model 2

**Comment by infinitewaveparticle** [comment]
Is this somehow related to #6650 ? Like the same bug, but at a different part of the UI?

**Comment by d-albrecht** [comment]
@infinitewaveparticle Okay, I guess this is a duplicate then. I checked the list of open and closed issues but must have missed this one. The wording is close enough that I should have seen this, but apparently still too different from what I was looking for to overlook it.

**Comment by infinitewaveparticle** [comment]
I'm not 100% sure it's a duplicate, as it concerns two different areas of the UI... But it could be...? Someone more knowledgeable about the code would have to answer this.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by d-albrecht** [comment]
To be honest, I wasn't 100% sure about how to proceed now that I've read the linked issue. But given that apparently one of the points on the checklist isn't true anymore (there is a duplicate) I decided closing (for now) would be the best reaction.

Regarding your concern: On the one hand, the description and the video more or less exactly match my case, so it's hard not to call it a duplicate. On the other hand, you could be right that fixing the linked issue won't directly fix this one. But if the NewPipe-developers/-contributors know what they are doing, it should be almost impossible to fix one without simultaneously fixing the other. When the next update arrives in f-droid, the linked issue is closed but I still encounter this issue, I will re-open it. But to minimize the risk of this happening, I will mention my findings in the linked issue such that the developer who is working on a fix is aware that another view suffers the same issue.

PS: What I think I did better than the linked issue, is to describe the phenomenon, but on the one hand that is a subjective opinion and on the other hand that doesn't change the fact, that I created an unnecessary (because duplicate) issue.
