### ISSUE TITLE
Redesign video info thumbnail

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6784]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Button positions
Top: Left: External video player, Right: External audio player
Bottom: Left: Play with Kodi, Right: Full Screen

Long press on the mentioned buttons should make the selected player open by default. 
On TV, full screen player can be easily enabled by turning off tablet mode. Other behaviors on TV will remain the same as of now.

#### Is your feature request related to a problem? Please describe it

Before v0.20.0, users could easily switch to full screen at any time. It would be great if users could choose external player or full screen whenever video info is shown. 

#### Additional context

![IMG_20210728_062911](https://user-images.githubusercontent.com/79245641/127245616-25d1bace-ce38-44b2-99dc-036487fadc9c.jpg)

#### How will you/everyone benefit from this feature?

A better way to interact with the app and choose freely favorite player without much dependence on settings. Also, if an easier way to choose resolution right before video playback (something alike top bar on preunified versions), the experience will be even better.

**Comment by Stypox** [comment]
There are the buttons below... These buttons hide the thumbnail.

**Comment by SameenAhnaf** [comment]
@Stypox Not available for external audio and video players. Users need to be fully dependent either of the player.

Plus, there's no way to choose any external player while starting the main player, neither in the long press menu.

Plus, buttons don't need to be too big. The buttons' background could have a glassy shade like in Windows 11. If the 'Play' button doesn't cover much of the screen, why will the other four buttons do so? It's definitely possible to make them useful as well.

**Comment by Stypox** [comment]
Then let's add some buttons to the expandable menu below, and there is already an open issue about missing accessability to external players
