### ISSUE TITLE
Long press on empty space of player should switch to full screen

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6785]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Long press on main player, popup player and video info thumbnail should let the users switch to full screen seamlessly. 

Unfortunately on TV, I couldn't find any way to keep both full screen and main player at the same time. But turning off tablet mode should get the job done.

#### How will you/everyone benefit from this feature?

It could have been great if users could switch between players easily. Entering full screen player every now and then is like a nightmare whenever auto-rotation is disabled. It might also solve #5594, #5299 and #5459.

**Comment by Stypox** [comment]
Same answer as #5299: 

> This will not be implemented, as we decided to instead solve the problems with fullscreen another way, see #5459

Let's not fill the ui with strange gestures
