### ISSUE TITLE
Full Screen Minimize Gesture Conflicts with Background Player Track Progress / Seek Bar

### ISSUE THREAD

**Issue by blindm0use** [TeamNewPipe/NewPipe#6788]
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Try 'Start playing any video/music/playlist in the background'
2. Navigate and maximize/open 'Background player queue that is found in the notification bar'
3. If the phone has full screen gestures activated, and the selected video/music/playlist is running 'Try to minimize the currently open background player screen with a swiping action from bottom edge of the screen towards the middle'

### Actual behavior

The finger will interact with seekbar and make the track jump exactly to the position where the finger crossed it while attempting to minimize the background player screen/window.

### Expected behavior

Full screen gestures shall not overlap or interact with any of the navigational elements within the application. Otherwise it creates false inputs as stated above.

### Screenshots/Screen recordings

![Screenshot_20210721-142840_NewPipe](https://user-images.githubusercontent.com/47911521/127290658-b60b625f-6e5f-4f80-831c-4f602d36e5ab.jpg)
[Video of the bug with 'Show visual feedback for taps' activated. (streamable.com)](https://streamable.com/hyk9e9) 

### Logs

N/A

### Device info
 - Android version: Android 11 / OneUI 3.1
 - Device model: Samsung Galaxy S10e

**Comment by SameenAhnaf** [comment]
Please close #6722 as that doesn't follow template. Also, you already checked the checkbox.

>I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

**Comment by blindm0use** [comment]
> Please close #6722 as that doesn't follow template. Also, you already checked the checkbox.
> 
> > I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

The old bug report I submitted did not follow the template, but this bug report does follow the template. Have already closed the old one, and, please, be so kind to review the new one.

**Comment by SameenAhnaf** [comment]
Please delete the comment as well to avoid pissing off other devs with unnecessary comments.

**Comment by phigjm** [comment]
I have the same problem and try to rearrange the control elements.
