### ISSUE TITLE
Adding login support

### ISSUE THREAD

**Issue by HinamoreCh4n** [TeamNewPipe/NewPipe#679]
Hello, I was wondering if login support is going to be added so users can view playlists and history and so on or if at all that feature is wanted by the community. Thanks

**Comment by theScrabi** [comment]
No.

Playlists and History can be implemented locally. We don't need to login for that.

The reason we don't implement that is that NewPipe was designed to use as less google as possible. This the core reason NP exists.

Please also consider to wait. The next version will support playlist and history.
