### ISSUE TITLE
Newpipe Search button sometimes become unresponsive.

### ISSUE THREAD

**Issue by Taratect** [TeamNewPipe/NewPipe#6790]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Newpipe'
2. Press on 'search button'

The problem is that sometimes the search button seems unresponsive as the keyboard don't appear on screen. The problem started when that new 'show played videos' button was added beside the search button

### Actual behavior

When clicking the the search icon, the keyboard doesn't appear no matter how much click on it.

### Expected behavior

The keyboard should appear when the search button is clicked.

### Screenshots/Screen recordings

![Screenshot_2021-07-28-21-01-06-471_org schabi newpipe](https://user-images.githubusercontent.com/84506636/127347948-ba6e4054-a668-476b-aa0a-df762025daa7.jpg)

### Device info

 - Android version/Custom ROM version: 10 (MIUI 11)
 - Device model: Redmi 8

**Comment by ggdorman** [comment]
Can confirm this is an issue.

**Comment by arozaqf** [comment]
need to open search the second time to make keyboard show

**Comment by litetex** [comment]
We need more info here.
Does this happen on different devices or e.g. just on devices with MIUI?

Could someone collect the logs when this happens?

**Comment by litetex** [comment]
Closed in favor of #7490
