### ISSUE TITLE
Clicking on a channel link opens a video on that channel

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#6793]
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to https://www.youtube.com/watch?v=C4QDn6kD9Ng
2. Navigate to the video info
3. Scroll down to the link https://www.youtube.com/channel/UCwSozl89jl2zUDzQ4jGJD3g and click on it
4. Select NewPipe
5. A video from that channel will then open instead of simply opening the channel. If you have open videos in popup by default the popup will also be on the screen.

### Actual behavior

A video from a channel plays.

### Expected behavior

The channel'e main page with Subscribe button and list of videos should be opened (and the popup or other alternative default method should be ignored since this isn't a video link).

### Device info

 - Android version/Custom ROM version: 8.0
 - Device model: Samsung Galaxy S7 Edge

**Comment by SameenAhnaf** [comment]
Did you check this option? Go to 'Settings'>'Video and Audio'>Scroll down to 'Behavior'> Check "Preferred 'Open' Action
![IMG_20210729_085357](https://user-images.githubusercontent.com/79245641/127424406-a95f7817-3859-4c6c-8b8b-024dd581b55b.jpg)

It's the usual behavior if the open action is set as "Video Player".

**Comment by infinitewaveparticle** [comment]
@SameenAhnaf This is for opening a channel, not a video, so regardless of what that setting is it should open the channel page.

**Comment by SameenAhnaf** [comment]
@Stypox Shouldn't this be closed in favor of #4331?

**Comment by Stypox** [comment]
@SameenAhnaf yes

**Comment by infinitewaveparticle** [comment]
My issue is very specific and pertains to opening a channel from a link in a description. I think closing it may pass over the fixes needed for it, as opening a channel from a search works just fine even though there are no options for what to do when opening it.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
If anything this full issue should be copied to the other issue and included in it.

Sent from ProtonMail mobile

-------- Original Message --------
