### ISSUE TITLE
Can I use new pipe in desktop

### ISSUE THREAD

**Issue by Akpsaheer** [TeamNewPipe/NewPipe#6795]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

**Comment by nikhilCad** [comment]
Windows 11 will support side loading apks by default. You may also use some emulator but the current ones are kind of intrusive.

You may also use Desktop specific foss youtube apps like freetube, or just use an adblocker.

**Comment by mhmdanas** [comment]
Like @nikhilCad says, I would recommend using desktop alternatives like FreeTube instead. If you insist on using NewPipe itself, also like @nikhilCad said, Windows 11 will support running Android apps, while for Linux there's Anbox, and you could use an Android emulator generally.

Also, please fill in the template properly next time you open an issue.
