### ISSUE TITLE
Buffering lag during quality switching 720 to 480

### ISSUE THREAD

**Issue by arjunmsujathan** [TeamNewPipe/NewPipe#6799]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: android 10
 - Device model: realme

**Comment by mhmdanas** [comment]
Please fill the template properly, then make a comment that you did and I'll re-open this issue.
