### ISSUE TITLE
Notification when a new video uploaded by subscribed channel

### ISSUE THREAD

**Issue by arjunmsujathan** [TeamNewPipe/NewPipe#6800]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment]
A PR for this issue #2335 is under progress.

**Comment by mhmdanas** [comment]
Duplicate of #1086. Also, please follow the template properly when opening an issue.
