### ISSUE TITLE
Version 0.21.7 Broke Subscriptions Page Condensed Grid Layout

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#6802]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Recent update 0.21.7 made grid layout of "Subscriptions" page less condensed somehow. Attached screenshots are both in portrait mode and yet you can see the visible change

### Actual behavior

Same as prior.

### Expected behavior

Should remain unchanged.

### Screenshots/Screen recordings

![IMG_000008](https://user-images.githubusercontent.com/55331939/127537205-6105acb1-1332-49c1-a1c7-5704ed27bb11.PNG)
![IMG_000009](https://user-images.githubusercontent.com/55331939/127537211-1217e427-bba7-4d26-88d1-10c40a76eb5f.PNG)

### Logs

NA

### Device info

 - Android version/Custom ROM version: 11
 - Device model: OnePlus

**Comment by mhmdanas** [comment]
I believe the only grid-related PR merged in 0.21.7 is #6705. If I'm right about this, I expect https://github.com/TeamNewPipe/NewPipe/suites/3277311604/artifacts/76378391 (the APK for the commit right before the PR merge commit) to not have the issue, but https://github.com/TeamNewPipe/NewPipe/suites/3276913491/artifacts/76366095 should have it. Can you test this?

**Comment by desmonk** [comment]
Yes, that is correct.

**Comment by mhmdanas** [comment]
@Stypox any ideas?

**Comment by Stypox** [comment]
@desmonk could you test #6814?

**Comment by desmonk** [comment]
Yes, that did solve it!

**Comment by mhmdanas** [comment]
The PR has not been merged yet, so please keep this issue open.

**Comment by desmonk** [comment]
Alright.

**Comment by mhmdanas** [comment]
The PR was merged, so closing this.
