### ISSUE TITLE
Add "Pick random"/shuffle for YouTube playlists

### ISSUE THREAD

**Issue by Deadiy** [TeamNewPipe/NewPipe#6818]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be nice if you add feature Y which makes X possible.

Y = "Pick random"/ shuffle

X = binging an entire YouTube channel's playlist unique each time, or randomly play live music streams from YouTube from user made list 

#### Is your feature request related to a problem? Please describe it

Several YouTube channels I follow have playlists filled with all of their videos for that topic, up to 300 videos sometimes, but there's no easy way to just dive right into the content.

Also sometimes I want to chill with some random live music streams from YouTube, but there's no way of randomly playing one from playlists.

#### Additional context

I don't know Java, but I know Unity/C#. Here is how I would code it to a button in the playlist page:

1- Get length of playlist.
2- Random.range(zero, length of playlist -1).
3- pick the Random.range index from the playlist.
4- play said video from playlist.
5- either make "next video" button trigger the function again or make a temporary playlist from the user's playlist and randomise it completely in the background

#### How will you/everyone benefit from this feature?

(Misread on the first time)
Sometimes people add random music's they like to a YouTube playlist, it's been free with ads for years, and sometimes just tapping a button and either getting ass blasted with cringe or nostalgia is a fun time with loved ones

**Comment by SameenAhnaf** [comment]
"Shuffle" feature is already available in Newpipe app.

Alternative-1: Access from playback manager
1. Start background or popup playback.
2. Short press on notification player.
3. Playback controls including 'Shuffle' is available at the bottom.

Alternative-2: Access from notification player directly (Step 1 to 5 is a one-time process)
1. Open 'Drawer'
2. Go to 'Settings'
3. Choose 'Notification'
4. Choose 'Shuffle' as fourth or fifth action button.
5. Restart the app.
6. Start playback. 
7. Pull down notification panel and access "Shuffle" from the player.


https://user-images.githubusercontent.com/79245641/127757721-435f7e81-d17a-4ad6-80fb-73f4464eee5d.mp4
