### ISSUE TITLE
Newpipe still unable to pass CAPTCHA

### ISSUE THREAD

**Issue by Camfly** [TeamNewPipe/NewPipe#6819]
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. The one I did find, did not follow the template.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any video and attempt to load it. 
2. Newpipe will notify you of a CAPTCHA request. 
3. Solve the CAPTCHA. The Web browser will then load the video correctly. 
4. Mark the CAPTCHA solved. 
5. (this bug appears periodically, but has survived a CAPTCHA cookie purge and a clean reinstall)

### Actual behavior
The Web browser will close, but Newpipe will fail to load the video and still request a CAPTCHA. 

### Expected behavior
Newpipe will load the video. 

### Screenshots/Screen recordings

https://ln4.sync.com/dl/c214c6730/kd5e233f-ipznn7t5-pi9z9jrr-hu5g7jnz

### Device info

 - Android version/Custom ROM version: MIUI 12.5.7 (Android version 11)
 - Device model: Xiaomi 10S (M2102J2SC)

**Comment by Bjorn99** [comment]
It does happen on my device too but only when I use mobile data. On WiFi, It works fine and I don't face any issues then.

**Comment by Bjorn99** [comment]
Changing the DNS service provider seems to do the trick. See if you get the same issue after using a VPN. If not, I recommend changing the DNS service provider.

**Comment by Camfly** [comment]
> Changing the DNS service provider seems to do the trick. See if you get the same issue after using a VPN. If not, I recommend changing the DNS service provider.

Can confirm, set my Private DNS to Cloudflare and the issue cleared up. Still keeping the issue open, as the app shouldn't have this problem in the first place.

**Comment by Feuerswut** [comment]
Is this still an issue?
