### ISSUE TITLE
Queue shuffle button highlighted when queue is not shuffled

### ISSUE THREAD

**Issue by Douile** [TeamNewPipe/NewPipe#6825]
### Checklist

- [x] I am using the latest version - 4bf5ddbfe9100c025203b79f63a8dcad855e936a (development build) >= 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a video
2. Return to feed and long-press then enqueue another video
3. Return to player and open queue menu

### Actual behavior

The shuffle button is highlighted (like it would be if it is active)

### Expected behavior

The shuffle button is greyed out as the queue is not actually shuffled yet

### Notes
Tapping the shuffle button twice will return the shuffle button to a greyed state.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: N/A

**Comment by Douile** [comment]
I will look into fixing this issue

**Comment by 0x416c6578** [comment]
A quick and easy fix is to add `setShuffleButton(binding.shuffleButton, false);` after initializing the listeners in `setupFromView` in `Player.java`. This doesn't fix the underlying issue (which I haven't been able to figure out yet) but it fixes the UI bug.

**Comment by Douile** [comment]
@0x416c6578 setShuffleButton just changes the opacity of the image, so maybe can just set the opacity in the layout and be fine. Calling the function might be better though as would reflect the actual shuffle state (i.e. if queue is already shuffled)

**Comment by 0x416c6578** [comment]
AFAIK the queue state always returns to unshuffled when reloading the view (try loading a playlist -> shuffling -> closing -> reloading; it will be unshuffled by default). I think there is something that is done for the other buttons in their initialization that makes sets them to _unselected_ that isn't done for the shuffle button.

**Comment by 0x416c6578** [comment]
yeah thats what I meant. In `initPlayback` they set the image whereas the shuffle button isn't set so it stays 100% opacity.
