### ISSUE TITLE
NewPipe feels slower than before

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#683]
I noticed that the current dev version (v0.10.0) is loading content much slower then the version (v0.9.10) online on fdroid.
Can anyone a approve?

**Comment by theScrabi** [comment]
So I've checked if v0.10.0 creates more requests than older versions, and no it does not.
So the delay comes from local processing, but why.

**Comment by theScrabi** [comment]
I'm starting to feel its ReactivX ...

**Comment by wb9688** [comment]
Are you running a release build of both? If that doesn't make a difference,
can't you take a look at the profiler of Android Studio?

**Comment by theScrabi** [comment]
> Are you running a release build of both
No I tried only debug and beta build.
I'm so lit. Release is fast as nothing. :)
Wellp thank you.
