### ISSUE TITLE
Denial Of Service video loading

### ISSUE THREAD

**Issue by cryptoxico** [TeamNewPipe/NewPipe#6831]
Few videos make my phone crash and reebot in BIOS phone ( Xiaomi A2 )
Video make crash
https://www.youtube.com/watch?v=3LJepkIijHU
Video don't make crash 
https://www.youtube.com/watch?v=y9xQeg_vjdc

**Comment by litetex** [comment]
Please fill out the template accordingly.

The first video isn't available (at least my NewPipe app / YouTube on my phone says that) and it crashes with https://github.com/TeamNewPipe/NewPipe/issues/6726

However it's very very unlikely this causes your complete phone to crash. 
If that really happens try to increase the systems stability by updating the underlying OS, try reinstalling NewPipe and so on. (There are a lot of helpful sites online, e.g. https://support.google.com/android/answer/7664448?hl=en)

Closing this for now.

**Comment by TiA4f8R** [comment]
I think it's a duplicate of #4638 or #5961. But like @litetex said, please follow the template properly when opening an issue.
