### ISSUE TITLE
Tablet aligning information

### ISSUE THREAD

**Issue by Angelk90** [TeamNewPipe/NewPipe#6832]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any video
2. Go to the description

### Expected behavior

That the part that is in the blue rectangle is aligned with the text.

### Screenshots/Screen recordings

![127997777-3acdf487-5a70-4078-b700-9b5f960c626d](https://user-images.githubusercontent.com/20476002/127998325-3ae009eb-5948-47ea-8415-e7e61f0884f2.png)

### Device info

 - Android version/Custom ROM version: 9.0
 - Device model: Tablet

**Comment by SameenAhnaf** [comment]
This is the expected behavior. See: #5946.

Also, mention your installed Newpipe version properly.

**Comment by Angelk90** [comment]
@mhmdanas : But having all that space on the tablet version isn't very nice.

**Comment by mhmdanas** [comment]
There is a different UI for tags in 0.21.9. Please give it a try: #6841
