### ISSUE TITLE
Incorrect number of views

### ISSUE THREAD

**Issue by Angelk90** [TeamNewPipe/NewPipe#6833]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open any video

### Actual behavior

![20210803_120135](https://user-images.githubusercontent.com/20476002/127999269-34e2fa04-d714-41e9-9d7b-d4b44e1a68d8.jpeg)

### Expected behavior

![20210803_120112](https://user-images.githubusercontent.com/20476002/127999263-ccb4e553-04eb-434e-88bd-f2e833062189.jpeg)

### Device info

 - Android version/Custom ROM version: 9.0
 - Device model: Tablet

**Comment by SameenAhnaf** [comment]
Do you know 'Views' is an information updated every single second? Moreover, Olympic highlights is a trending topic. Why did you think such an information static for such popular videos?

**Comment by mhmdanas** [comment]
It is as @SameenAhnaf says. This is a non-issue.
