### ISSUE TITLE
Videos are not loading, search not giving results

### ISSUE THREAD

**Issue by greyduck1** [TeamNewPipe/NewPipe#684]
I'm able to successfully install and open NewPipe, but once inside, nothing works properly. When I search for a video, I don't get any results (the loading icon persists), and when I open a video through an external link, it never loads, not even the basic title and description of the video.

My phone is the Moto E³ Power (model number XT1706) which runs on MediaTek MT6735P.

**Comment by openpaul** [comment]
Same Herr, but only recently this startend. I am using lineagoes 14 with microg so i suppose maybe its my fault

**Comment by wb9688** [comment]
I think it's because of YouTube's new design.

**Comment by mauriciocolli** [comment]
@wb9688 if that was the case, wouldn't it be throwing an error (for trying to parse nonexistent elements)? 
Although this issue seems like a network problem.

But that's a possibility, maybe we should start using `&disable_polymer=true` temporarily until it migrates completely to it.

**Comment by wb9688** [comment]
@mauriciocolli: Hmm… I didn't think about that, but there could be another
bug somewhere that causes it to wait infinitely instead of just throwing an
error, btw wouldn't a network problem also throw an error?

**Comment by TobiGr** [comment]
I have experienced this issue several times in the last three or four month. A phone reboot helped. So maybe it is a network problem.

**Comment by mauriciocolli** [comment]
It could be that the connection didn't timeout and they thought that was a problem.

@greyduck1 @openpaul how much time did you waited? Can you wait a very long time to see if it throws an error?

**Comment by TobiGr** [comment]
I didn't get an error. But I can try to catch a logcat next time.

**Comment by wb9688** [comment]
@TobiGr: Hmm… how long have you waited? More than 2 minutes? I think 2
minutes is the default timeout, but I'm not sure though.

**Comment by greyduck1** [comment]
@mauriciocolli I have waited for more than 5 minutes a few times, but nothing new happens. Rebooting does not help either. Could it still be a network problem if my friend is able to use NewPipe properly on the same network? I also use the official YouTube app and it works just fine.

**Comment by wb9688** [comment]
>Could it still be a network problem if my friend is able to use NewPipe
properly on the same network?

@greyduck1: Then it maybe is an issue with the network stuff of your phone,
but that's unlikely if every other app works fine. Could you try getting a
logcat with a debug version of NewPipe? Btw are you using a VPN or similar?
If so, does it work if you disable it?

@mauriciocolli: Is it possible to intercept requests NewPipe makes with my
computer so that I can add cookies? If so, I can try to reproduce it by
adding the cookies to force it to get the new YouTube design.

**Comment by theScrabi** [comment]
@wb9688 You can use [mitmproxy](https://mitmproxy.org/).

**Comment by greyduck1** [comment]
@wb9688  Sorry for the late response, was a bit busy. I don't have experience using logcat, but I tried using it. I'm getting a ton of logs through adb, how do I send them to you or how do I filter the logs specific to NewPipe? I have installed the debug version of NewPipe.

**Comment by wb9688** [comment]
@greyduck1: For filtering the logs specific to NewPipe, you should first
type `ps | grep newpipe` in `adb shell` and remember the number in the
second column. After that you could just `adb logcat` and then filter for
that number.

**Comment by greyduck1** [comment]
Thanks, I did as you said (although I might have let it run too long) and stored the logs [here.](https://pastebin.com/cqmyAFeM)

**Comment by mauriciocolli** [comment]
The debug log was disabled in the version that you tested, although I saw some exceptions that could be relevant with this problem (some timeouts).

Here's the version with log enabled ([app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/1308595/app-debug.apk.zip)), and besides that, it could fix your issue as the one you have is an old version.

 You can do the same thing as @wb9688 told previously, but this time, look for a process with the name `org.schabi.newpipe.debug` (note the .debug) and you might want not to filter the output, as it could have some relevant information.

**Comment by greyduck1** [comment]
Oh, alright. [Here](https://gist.github.com/greyduck1/1392bb1ad351d43b36948351d73246b5/raw/9dbfea12793246f3f8e561b40e8d87aab8572c71/newpipe_684.txt) are the logs for the debug version you linked (issue still persists in this version) with no filtering of logcat output.

And if necessary, here is the filtered log specific to NewPipe Debug too: [newpipe_filtered.txt](https://gist.github.com/greyduck1/b55bba76d5454b69f1f6152fc6f9b47c)

**Comment by mauriciocolli** [comment]
I saw some pauses in the log, did you exit the application during the search? The ideal situation was pressing search and let the phone alone during 1-2 minutes to see if timeout or whatever happens.

But nevertheless, it definitely seems some sort of network issue as the requests _seems_ to get stuck on `getInputStream`, so please, can you give another log with this even more detailed debug log?
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/1309214/app-debug.apk.zip)


**PS**: I removed the logs for the unfiltered one as they **_may_** have some sensitive information (I didn't dig it, but it's possible that it has), I suggest that you do the same with the gists (delete it).

**Comment by greyduck1** [comment]
Oops, removed the gist. Thanks! I have uploaded the new logs with the new debug version you linked [here.](https://gist.githubusercontent.com/greyduck1/6c2c2fa2e0e4e79cbfdae85887593994/raw/df9df41232b1201a11c8ce548e1ebfb20e2168ab/newpipe2_logs.txt)

**Comment by greyduck1** [comment]
@mauriciocolli @wb9688 Any progress on the issue?

**Comment by greyduck1** [comment]
NewPipe is working fine with the new release. Thanks for taking your time to fix this issue.
