### ISSUE TITLE
Subscription error

### ISSUE THREAD

**Issue by maverickvb** [TeamNewPipe/NewPipe#6843]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: android 10
 - Device model:
K20pro

Whenever I'm trying to import subscription json file it's showing error pls fix that issue ASAP ,TY!

**Comment by mhmdanas** [comment]
Duplicate of #6757 probably.
