### ISSUE TITLE
YouTube exporting to CSV

### ISSUE THREAD

**Issue by xdestviz** [TeamNewPipe/NewPipe#6864]
Hi all,

I have tried searching for the answer for hours, with no success, so I decided to post here. No matter what I do, YouTube keeps exporting my subscriptions as CSV files. No online converters that I have tried work, and I have tried downloading my entire Google account with different categories and file types selected, but it still exports as CSV. Any idea how to get it to export to json?

**Comment by SameenAhnaf** [comment]
Please keep the discussion in #6757.
