### ISSUE TITLE
Impossible to export subscriptions

### ISSUE THREAD

**Issue by Flashwalker** [TeamNewPipe/NewPipe#6866]
Looks like In recent release the method of accessing the storage for subscriptions export has been changed.

Now, if you don't have the default android **Documents** app, you can't export subscriptions.
The button just do nothing.  

It's realy bad idea to rely on third party app. 

UPD: i found that method of accessing storage for export subscriptions can be toggled in Downloads settings

**Comment by SameenAhnaf** [comment]
Please keep the discussion in #6757.

**Comment by ShareASmile** [comment]
@SameenAhnaf  6567 is about importing subscriptions into NewPipe app from YouTube. This issue is about exporting subscriptions from NewPipe to storage.

@Flashwalker I think this issue should be re-opened.
And also please fill in issue template accordingly next time.

**Comment by SameenAhnaf** [comment]
Mistake of two letters 😑

**Comment by NioAntoVenice** [comment]
I have a problem esporting subscriptions from youtube, the export file inside the takeout folder contain only a file named "iscrizioni.csv" and not .json .. how can i solve it? Thank you

**Comment by mhmdanas** [comment]
@NioAntoVenice you're looking for #6757.

**Comment by tsiflimagas** [comment]
I guess this can be closed. com.android.documentsui shouldn't be removed as it serves as provider for SAF framework, thus it's not just a regular file manager. A solution was found anyway though.

**Comment by opusforlife2** [comment]
@mhmdanas?
