### ISSUE TITLE
Add full black theme.

### ISSUE THREAD

**Issue by krompus** [TeamNewPipe/NewPipe#687]
The addition of the black theme was one of my favourite recent additions.

I wonder if you might consider adding a full black theme; doing away with the red bars. I find them quite distracting; they clash with my all-black theme elsewhere.

**Comment by theScrabi** [comment]
What's up with all those all black guys. It seems to become a trend now :P .
I have some friends who have the same issue.
However might be considerable :)

**Comment by krompus** [comment]
@theScrabi You wouldn't understand unless you were black. ;)

**Comment by theScrabi** [comment]
I use some black themes. I like black my self, but sometimes to black does not look good in my opinion.

**Comment by bagelcake** [comment]
Maybe to satisfy everybody separate themes into a primary/base color and an accent color? So for base, there's black, dark and light. And for accent, it's NewPipe red plus whatever or have a color picker.

Otherwise just throw in a pure black theme called "all those all black guys black" or AMOLED black?

**Comment by theScrabi** [comment]
I see, its the toolbar that is still missing. Well i thought when we have multi service support we could theme the bar according to the service used, but overriding this behaviour by hand is fine as well.

**Comment by andrewbanchich** [comment]
Any update on this? I would really love to have a dark theme without the red. It doesn't have to be all black, but at least some neutral color like dark gray would be really nice. The red is very distracting.

**Comment by theScrabi** [comment]
not yet.

**Comment by mhmdanas** [comment]
Subsumed by #4148.
