### ISSUE TITLE
Add New/Updated label to videos that were apart of the last subscription update

### ISSUE THREAD

**Issue by christopher-wilson** [TeamNewPipe/NewPipe#6879]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

For subscriptions, it would be useful to have a label or a badge to indicate videos that have appeared since the last update. Something as simple like a green rounded label that says *New* would be sufficient, I would think.

#### Is your feature request related to a problem? Please describe it

It is pretty difficult to tell what's new in our subscriptions list, and if you have a lot of videos, you eventually just waste time scrolling over videos that aren't recent.

#### Additional context

I'm primarily a user on an Google TV, so there is a lot of browsing instead of deliberate searching, like there is on a phone.

#### How will you/everyone benefit from this feature?

Adding labels will allow users to quickly access what they want and not spend time browsing over older videos. It also lets users gauge how much time is necessary to catch up on their feed because they'll be able to see haw many new videos there. 

Lastly, it is a feature that is common in things like RSS readers, podcast clients, media centers, but oddly, YouTube doesn't seem to have it.

**Comment by SameenAhnaf** [comment]
Recent videos already appear with bold title and border around videos.

<img src="https://user-images.githubusercontent.com/79245641/154010320-4fc398cf-a4d4-4258-a4fc-a77f3ae75753.jpg" height="150px"/>

@litetex `Waiting for author` label should be added, I think. 🤔
