### ISSUE TITLE
oldversion Support Please  NewPipeExtractor:0.20.2 Bug fix DeobfuscateException

### ISSUE THREAD

**Issue by cion49235** [TeamNewPipe/NewPipe#6887]
NewPipeExtractor:19c0e8700db3af35e5dfc58e4eea50e75d7c4c61
NewPipeExtractor:0.20.2

Hello, dear and respectful Newpipe, I am eager to get your help.
The reason we use the older Device version above is because it runs well on older and newer devices, so we've been using it well. However, from this afternoon, the detailed view of VideoDetailFragment.class will not be displayed. This seems to be an error while unencrypting YouTubeStreamExtractor.DeobfuscateException. 
I sincerely ask you to settle this and commit it.

The reason for using the above version is because the older Android devices are well supported. I'm going to make a donation, so please help me.

**Comment by SameenAhnaf** [comment]
Won't https://github.com/TeamNewPipe/NewPipe-legacy suit you? It's mainly built for older devices and has almost all the features. 

Also, please fill in the template properly. You are not supposed to remove it.

**Comment by cion49235** [comment]
Thank you for your reply. I'm sorry I couldn't keep the form. I'm in a hurry. https://github.com/TeamNewPipe/NewPipe-legacy =>v0.21.8 I know, but it's not supported on older devices. For example, OS 8.0 or lower level devices are not supported. NewPipeExtractor:0.20.2  of the above version VideoDetailFragment.class decoding n parameter in stream URLs If you support the issue, I'd like to make any donation or compensation. Please!   회사 단톡방 스트레스 치료는 '네이트온'
------ Original Message ------
Date: Tuesday, Aug 10, 2021 02:47:32 PM

**Comment by SameenAhnaf** [comment]
You may put a bounty for this issue to specifically highlight this issue. I  Also, you can donate here to support the whole project: https://newpipe.net/donate/

@TobiGr Could you please transfer this issue to Legacy repository? Thanks in advance.

**Comment by cion49235** [comment]
@TobiGr 

NewPipeExtractor:19c0e8700db3af35e5dfc58e4eea50e75d7c4c61
NewPipeExtractor:0.20.2

Hello, dear and respectful Newpipe, I am eager to get your help.
The reason we use the older Device version above is because it runs well on older and newer devices, so we've been using it well. However, from this afternoon, the detailed view of VideoDetailFragment.class will not be displayed. This seems to be an error while unencrypting YouTubeStreamExtractor.DeobfuscateException.
I sincerely ask you to settle this and commit it.

The reason for using the above version is because the older Android devices are well supported. I'm going to make a donation, so please help me.

**Comment by opusforlife2** [comment]
Okay. Lots of confusion here that needs to be cleared up.

First of all, @cion49235 the minimum supported Android version by Newpipe is 4.4. For Newpipe-legacy, it is 4.1. I don't know where you saw that 8.0 and lower aren't supported.

@SameenAhnaf Newpipe-legacy hasn't been updated since January, so avoid recommending it for now, especially since Youtube extraction was broken and just fixed in 0.21.8. Instead, you can tell users to try Xiang's pre-unified APKs.

@cion49235 Try the latest release from the link given in #4918. Also, did you read this line in the template?:

> IF YOU DON'T FILL IN THE TEMPLATE PROPERLY, YOUR ISSUE IS LIABLE TO BE CLOSED. If you feel tired/lazy right now, open your issue some other time. We'll wait.

So ignoring the template is still not an excuse.
