### ISSUE TITLE
New Pipe for Linux distributions

### ISSUE THREAD

**Issue by bungadrum** [TeamNewPipe/NewPipe#6891]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Can you add New Pipe in Linux Software Center, flathub or flatpak ? since it's not a web version or a .exe could it be possible to add it like a application and download it for a desktop?

#### Optionally, also describe alternatives you've considered
There is Invidious, LBRY, MiniTube and FreeTube that are already available on flathub, but they are not as good as New pipe 

#### How will you/everyone benefit from this feature?
Instead of depending only on a smartphone or tablet we would have the option to use the app on a desktop only for Linux users for starters, but that is also a start. Instead of creating a web version if you upload it as a app in Flathub or Flatpak users could install it that way. There are already some apps uploaded there why not New pipe as well?

**Comment by mhmdanas** [comment]
See #1051. TL;DR we have no plans of doing this any time soon.

> There are already some apps uploaded there why not New pipe as well?

NewPipe is designed for _Android_ only; it will require significant effort to port to Linux.

Did you take a look at [Piped](https://github.com/TeamPiped/Piped)? It's not a native app, but it might satisfy your needs.

**Comment by vitaly-zdanevich** [comment]
> Did you take a look at [Piped](https://github.com/TeamPiped/Piped)?

But what about subscriptions and viewed progress sync?
