### ISSUE TITLE
Internal error when updating "What's new" feed

### ISSUE THREAD

**Issue by andrei-belkin** [TeamNewPipe/NewPipe#6896]
### Checklist
- [x] I am using the latest version - 0.21.8
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to the "What's new" content page.
2. Update the subscriptions feed by pulling down or pressing the "Feed last updated" button.

### Actual behavior
After updating, an error pops up, titled "Error loading feed" and containing the following body:
> Could not load feed for '(Name of channel here; I tried refreshing five times, three times it was a different channel name)'. Got error:"INTERNAL": Internal error encountered.

The "Feed last updated" button now also has "Not loaded: x" written on it. I tried refreshing five times, x changed every time.

First try - 21 not loaded
Second try - 12 not loaded
Third try - 4 not loaded
Fourth try - 1 not loaded
Fifth try - 0, everything loaded correctly without any error popping up

### Expected behavior
What happened on the fifth try - a successful update of the subscriptions feed, no error popup, no "Not loaded" banner.

### Screenshots/Screen recordings
![The error popup](https://user-images.githubusercontent.com/59848424/128948523-58757f09-6401-4d50-b4ce-a02b0a1d289c.png)

### Logs
N/A

### Device info

 - Android version/Custom ROM version: GrapheneOS (Android 11), build number RQ3A.210805.001.A1
 - Device model: Google Pixel 4a

**Comment by TiA4f8R** [comment]
The error was a YouTube error: see https://support.google.com/youtube/thread/120697082/fixed-known-issue-8-10-videos-playlists-not-appearing-in-channel-pages. The issue should have been fixed for most of the channels. I am closing this issue because NewPipe can't do nothing for this bug.
