### ISSUE TITLE
hide recommendations

### ISSUE THREAD

**Issue by 2000prasanth** [TeamNewPipe/NewPipe#6903]
think that the options to
-> hide thumbnails
->hide comments
->hide recommended videos
Should be made more accessible in the settings tab

**Comment by SameenAhnaf** [comment]
Please fill in the template properly.

Also, if I am not wrong, following settings are already accessible on the app. Go to 'Settings'>'Content'>Scroll down a little and you will find the necessary options.

![IMG_20210811_171206](https://user-images.githubusercontent.com/79245641/129019442-c8fefa61-57e9-48f6-9cff-744b75694d85.jpg)

**Comment by litetex** [comment]
A solution was provided and no feedback since a week -> closing the issue.
