### ISSUE TITLE
Custom Theme Support

### ISSUE THREAD

**Issue by erneandroid** [TeamNewPipe/NewPipe#6906]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think that can be nice with this feature:
Custom Theme Support, also this source can help to the development of this feature:
https://github.com/jaredrummler/ColorPicker

#### Is your feature request related to a problem? Please describe it

No, just a suggestion

#### Additional context

You can check how it's work looking for FlorisBoard project.

#### How will you/everyone benefit from this feature?

This feature gonna make a interface change, and people gonna use theme editor for make themes and share. ( This help to make a big community because people like customize functions)

**Comment by mhmdanas** [comment]
This feature request has been decided against previously; see https://github.com/TeamNewPipe/NewPipe/issues/6272#issuecomment-856608962.
