### ISSUE TITLE
How do I move the files from Downloads in Newpipe-legacy to Downloads in Newpipe?

### ISSUE THREAD

**Issue by davidhedlund** [TeamNewPipe/NewPipe#6908]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
How do I move the files from Downloads in Newpipe-legacy to Downloads in Newpipe?

**Comment by mhmdanas** [comment]
Can't you do that using whatever filie manager you have installed?
