### ISSUE TITLE
Could not import subscriptions on Android phone

### ISSUE THREAD

**Issue by rezeerou** [TeamNewPipe/NewPipe#6911]
can't import the youtube subscriptions file due to miss matched file type from the takeout zip file which is not js file but instead i got csv subscriptions file
n the app requires a js file but the file from takeout is csv file so it return an error
i also have converted it to a js syntax n renamed the type to js but still failed to import it
n i do follow the notes on how to import it but i got csv file
idk if my converted js file was not matched with the app import function
maybe someone can give me a basic syntax of the js subscriptions file itself so i can copy it n retry it again
n if still failed i'll guess the error is from the file explorer 
tq

**Comment by annandr12** [comment]
have the same issue here.

**Comment by mhmdanas** [comment]
Duplicate of #6757.
