### ISSUE TITLE
Search for Time

### ISSUE THREAD

**Issue by PixelzNamikaze** [TeamNewPipe/NewPipe#6918]
When I search for something I miss the option to sort the content by a certain time e.g. By 24h, 7 days, 1 month, 1 year.

**Comment by mhmdanas** [comment]
Can you clarify? Do you want the search results to contains only results published later than a certain date, or you want the search results to have different sections for each time period?

Also, you removed the template. Please edit your issue to fill in the template properly and then I'll re-open this issue.
