### ISSUE TITLE
Clicking and watching a new video, then going back to the previous video ALWAYS restarts it

### ISSUE THREAD

**Issue by Suplex6** [TeamNewPipe/NewPipe#6921]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Click on/watch any vid for a minute
2. Click any vid in "related videos" section, and watch it
3. Use the "previous page/back" fuction on your device to return to the original video

### Actual behavior
Going back to the previous video always results in progress being lost, and it being restarted

### Expected behavior
Go back to previous vid, which should resume where you left off

### Device info

 - Android version: 8.1.0
 - Device model:Samsung Galaxy J2
 - *Issue occurs regardless of hardware/software combo, I've tested a few different devices

**Comment by Suplex6** [comment]
I tried multiple times, but everything I type doesn't show up in the actual post. Can a mod fix this please?

Steps to reproduce the bug


### Actual behavior




### Expected behavior

**Comment by SameenAhnaf** [comment]
Did you enable these two options? Go to 'Settings'>'History and Cache'

![IMG_20210814_170956](https://user-images.githubusercontent.com/79245641/129444460-5badb456-92f3-4b1b-8d22-4b51e1103eb4.jpg)

**Comment by opusforlife2** [comment]
As it says in the template:
> The comments between these brackets won't show up in the submitted issue (as you can see in the Preview).

Your stuff is between the brackets. You can edit your issue and paste the text outside them.

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?
