### ISSUE TITLE
Can't import YouTube takeout data

### ISSUE THREAD

**Issue by Th3Bruno** [TeamNewPipe/NewPipe#6923]
New pipe can't import the youtube abo data from Google takeout.
Probably Google changed the way of exporting their data.
Newpipe expects a JSON file but you get from "https://takeout.google.com/takeout/custom/youtube" only CSV files.

Used version: 21.8

**Comment by Th3Bruno** [comment]
Is already fixed 
6882

**Comment by opusforlife2** [comment]
It's _not_ already fixed, but it will be soon.

But this issue is a duplicate of already existing ones, so it would have been closed anyway.
