### ISSUE TITLE
MP4 file not supporting Sony TV (audio not supported)

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6925]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to newpipe
2. Download a video
3. Send it to a usb and then connect that to tv
4. Play the video
5. See audio error

### Actual behavior

The video plays but the audio isn't supported

### Expected behavior

Video and audio to be supported

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by litetex** [comment]
Doesn't look like a NewPipe-problem for me when it occurs outside of the NewPipe app on a completely different device.

You may update your TV.

Please also fill out the template accordingly next time 😄 

PS: When the problem also occurs on more devices like PC, Smartphone, Tablet, etc. you may fill out another issue (and add e.g. the link to the downloaded video, options you choose etc)
