### ISSUE TITLE
Video player slow loading on first tap

### ISSUE THREAD

**Issue by swarup13** [TeamNewPipe/NewPipe#6927]
### Checklist

- [x] I am using the latest version - 0.21.8  
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo, It is a completely different issue, please read before marking as closed
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to ' What's New/Trending page'
2. Press on 'Any video'

### Actual behavior
It is taking too much time to load a video,  with the contents like description etc. Sometimes I have to close the window or app to play the video. Sometimes it doesn't even load the player.
See it's not related to buffering during already playing video, or not even related to Internet. 

### Expected behavior
The expected behaviour is fast video player loading

### Screenshots/Screen recordings

![Screenshot_20210815-154029864](https://user-images.githubusercontent.com/55395995/129474974-78045ad4-223e-4383-a2f1-05105bd17108.jpg)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Redmi note 10 (Sunny/Mojito)

**Comment by Gottarocket** [comment]
When clicking on YT links it used to open newpipe fine now it says loading content getting info on notification and then opens app and above bug takes few more seconds again to load video

**Comment by swarupbhanjachowdhury** [comment]
Yes correct @Gottarocket

**Comment by akiyev** [comment]
I have this problem too.

**Comment by akiyev** [comment]
strange, puretube opens video faster than newpipe

**Comment by tsiflimagas** [comment]
Is this still a problem on 0.23.1?

**Comment by opusforlife2** [comment]
Closing. Please open a new issue if needed.
