### ISSUE TITLE
Guys I hope the algorithm is impartial  or not politicized anyway  ;-)

### ISSUE THREAD

**Issue by PlasticPlates** [TeamNewPipe/NewPipe#6929]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?

I searched for MSNBC and it gives me results accordingly, but after I watch the first clip the second and succeeding clips are all Fox.  I don't think this is how it was intended to work ?  Or Well I just hope the algorithm would give me a fair deal that's all.  Searching for MSNBC means not Fox right  ? Hmmm... Coincidence ?  I did the same using YouTube and the results showed MSNBC clips and I played the same first clip and the succeeding lineup only had one Fox way down near the bottom.  Just hoping NewPipe would have an impartial algorithm that's all.  Just a concern.  Thanks  !

**Comment by XiangRongLin** [comment]
NewPipe has no algorithm or anything of that sort. It just makes a request to youtube for the video and takes all of the information of the webpage it receives, including suggestion. So suggestions are still coming from youtube and their algorithms

**Comment by mhmdanas** [comment]
I believe the question has been answered. If you don't think so or want some clarification on something, please make a comment.
