### ISSUE TITLE
Seekbar jumps on AndroidTV very long

### ISSUE THREAD

**Issue by 0metz0** [TeamNewPipe/NewPipe#6937]
Seekbar jumps are to long (minutes) on AndroidTV over remote.

Please make the time jumps on seekbar to 20 seconds per tap on the remote and not scaling with the video time.

**Comment by litetex** [comment]
Please fill out the issue template accordingly. 

I don't understand the problem, however you can try to change the "fast-forward/-rewind" seek duration under Settings>Video and audio if it's that what you want.

**Comment by h-s-c** [comment]
The setting is not working for the seekbar you have to use on TVs with your remote. The seek duration seems percentage based. The longer the video the longer the seek duration. For 1h+ long videos this can mean 3min+ seek duration.
