### ISSUE TITLE
Video-Player is visible on wallpaper after the app is closed

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6939]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

There is a popup at the side of the video when closing newpipe

### Expected behavior

Nothing

### Screenshots/Screen recordings

![Screenshot_20210818-073717](https://user-images.githubusercontent.com/74511929/129837947-92b977c9-d63e-4b99-b251-aec24c42088f.jpg)

### Device info

 - Android version/Custom ROM version: Version 7.1.1 Nougat
 - Device model: Samsung Galaxy Tab A

**Comment by Thewisem** [comment]
This is not a popup as you can see
![Screenshot_20210818-074038](https://user-images.githubusercontent.com/74511929/129838063-61db62cf-e705-4c1a-8d72-40a4c8da5741.jpg)

**Comment by mhmdanas** [comment]
i don't understand the issue _at all_. Could you explain the problem more clearly?

**Comment by Thewisem** [comment]
When I escape from the app in multitask, this weird popup occured which stays in my bacground until I go back to multitab and close it.

**Comment by Thewisem** [comment]
Close newpipe

**Comment by Thewisem** [comment]
To prove that this was real I showed the second picture where it is behind the background

**Comment by litetex** [comment]
@Thewisem 
Could you please fill out
> Steps to reproduce the bug

I also don't understand what 
> There is a popup at the side of the video when closing newpipe

means...
Which video?

Anyway looks probably like a hardware/software specific problem.

**Comment by Thewisem** [comment]
I don't know how to reproduce it

**Comment by Thewisem** [comment]
When you open fhe app and open the video, it has a position where it shows the video right? For tablets,it shows in the upper left corner. This occurs rarely and I don't know how to reproduce it sadly. So when you use multitab and close from it. Rarely you see this popup of where the video was being played in the position where it originally played in newpipe. This popup occurs in the background and apps can be put in front of it(as you can see). It is almost like a wallpaper

**Comment by Thewisem** [comment]
![Screenshot_20210818-215952](https://user-images.githubusercontent.com/74511929/129956483-08738ef6-b115-45ab-bab3-9878d26b1b26.jpg)
You see the position the video is being played? That is where the popup comes and newpipe closes.

**Comment by litetex** [comment]
Okay so you don't use popup mode, that's good to know.

Then it's very likely a software device specific problem with the underlying firmware (Android OS).
You may try updating it 😄

**Comment by litetex** [comment]
Also renamed the title because "Rare occurence of a bug" is not very meaningful

**Comment by Thewisem** [comment]
You did. And I didn't know what to call it and it rarely occured to me

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?
