### ISSUE TITLE
Please enable cache for webviews in the extractor

### ISSUE THREAD

**Issue by akiyev** [TeamNewPipe/NewPipe#6946]
Please enable cache for webviews in the extractor. Every time you open the first video it opens very slowly

**Comment by mhmdanas** [comment]
There are no web views in the extractor per se. I think it's unlikely your issue is a problem with caching, but instead it is probably a bug. In any case, please create a new issue that follows the template properly if you didn't find an existing issue for this.

**Comment by akiyev** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/6927
