### ISSUE TITLE
Long titles in Settings don't wrap to the next line

### ISSUE THREAD

**Issue by Aga-C** [TeamNewPipe/NewPipe#6951]
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

I know that this issue was already raised (#6601), but it was closed due to ignored template.

### Steps to reproduce the bug

1. Open the app.
2. Go to Settings.
3. Tap "Video and Audio" section.
4. Scroll down to the end of the page.

### Actual behavior

Long titles in Settings are not wrapped to the next line. I have to rotate the device to horizontal mode to see them whole.

### Expected behavior

Long titles should be wrapped to the next line to be fully visible in vertical view.

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/85929121/130314053-a75e7a91-5eae-49db-b6b8-79d635efb7fb.png)

### Logs

N/A

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: OnePlus 9 Pro

**Comment by TobiGr** [comment]
That's easy to fix. We need to add `app:singleLineTitle="false"` to the preferences.

**Comment by Aga-C** [comment]
@TobiGr I've tried to add it, but it doesn't work. Here's the code:
```
        <SwitchPreferenceCompat
            android:defaultValue="false"
            android:key="@string/auto_queue_key"
            android:summary="@string/auto_queue_summary"
            android:title="@string/auto_queue_title"
            android:singleLineTitle="false"
            app:iconSpaceReserved="false" />
```
and that's the result (in emulator):
![image](https://user-images.githubusercontent.com/85929121/130320529-f509c07c-cec4-445d-819a-79858a702e1c.png)

Ellipsis is still visible.
