### ISSUE TITLE
Classic music player

### ISSUE THREAD

**Issue by fallabdoulaye93** [TeamNewPipe/NewPipe#6953]
Hello team, which version of NewPipe contains a audio player like classic music players ? (Not Youtube like interface).

**Comment by mhmdanas** [comment]
> which version of NewPipe contains a audio player like classic music players

All versions in recent memory. There are many ways to play things in background, like pressing the background button below the video title.

Note that having an interface suited similar to traditional Android music players is not a goal of NewPipe. You would be better served by other projects in that regard.

Also, please don't remove the template when opening an issue.
