### ISSUE TITLE
Consistent choppy player back

### ISSUE THREAD

**Issue by fluxtom** [TeamNewPipe/NewPipe#6963]
when watching a videos using the inbuilt player, the video player will consistently skip. Using MPV (or any other video player) an external player means that this issue completely dissapears. 

### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to: any video
2. Press on: play

### Actual behavior

The video plays however constustently skips forward consistently causing play back to be choppy. 

### Expected behavior

There should be no skipping. 

### Screenshots/Screen recordings

https://streamable.com/ahzzc0

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: OnePlus 6

**Comment by mhmdanas** [comment]
Here's the YouTube link for the video: https://youtube.com/watch?v=bRjwr086jdU

**Comment by mhmdanas** [comment]
@fluxtom why did you close this?
