### ISSUE TITLE
Newpipe - Request for newly updated search and Live button, since 2015 requests 100s of thousands requests in youtube, please just give us that magic button with search by upload date and or live button. 2 button request, easy as pie.

### ISSUE THREAD

**Issue by githubuser123** [TeamNewPipe/NewPipe#6964]
Request for newly updated search and Live button, since 2015 requests 100s of thousands requests in youtube, please just give us that magic button with search by upload date and or live button. 2 button request, easy as pie.

**Comment by mhmdanas** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/4599.

> easy as pie.

Please don't assume that something is "easy as pie." You can never know what things crop up when trying to implement something.

Also, please don't remove the template next time you open an issue.
