### ISSUE TITLE
挂载vpn后总是显示发生错误

### ISSUE THREAD

**Issue by kkhwg** [TeamNewPipe/NewPipe#6967]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by kkhwg** [comment]
![Screenshot_20210824_145335_org schabi newpipe](https://user-images.githubusercontent.com/50423102/130570945-aa9a1f95-ae20-4fb8-b090-120afcb45d6c.jpg)

**Comment by XiangRongLin** [comment]
Please fill out the template and use englisch
