### ISSUE TITLE
Youtube Subscriptions

### ISSUE THREAD

**Issue by DarkAlterEgo81** [TeamNewPipe/NewPipe#6972]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Trying to import youtube subscriptions.... The guide states there will be a subscription.json file however there is no .json. Google does not allow me to change the data type type from .csv to .json and Newpipe will not import the .csv. I have tried everything I can think of.... Retrieving the Google data via multiple browsers and have tried converting the .csv to .json using multiple methods with no luck on the import. Any information would be much appreciated.

**Comment by mhaaz** [comment]
I have exactly the same issue as described. NewPipe tells me to look for a JSON file, however Google takeout only makes a CSV available.
