### ISSUE TITLE
Option to toggle off (or on) the trending tab

### ISSUE THREAD

**Issue by meximan** [TeamNewPipe/NewPipe#6973]
Please consider adding the option to toggle off (or on) the Trending tab in the appearance settings.

It is highly distracting as the first thing you see when opening new pipe and would be very helpful in staying focused and in searching what you want only. Adults have limited time as it is. The most disciplined people don't exert themselves rather they reduce temptation. Other FOSS (freetube, unhook youtube) software has this feature. This feature will save a lot of people time.

Thank you for your time and hardwork!

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by Ammako** [comment]
You can change the order in which tabs appear, so you can have your subscriptions page as the first one you see by default. But it would be nice to be able to remove some of those default tabs completely if one wishes.
