### ISSUE TITLE
Subscription Xml Support

### ISSUE THREAD

**Issue by budsterblue** [TeamNewPipe/NewPipe#698]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version. 

So I was able to successfully build NewPipe with subscription support and was wondering if it would be possible to add xml support. What I mean by this is at the bottom of the [subscription manager page](https://www.youtube.com/subscription_manager) there is an "Export to RSS readers" button. I was wondering if it would be possible to import subscriptions that way since the current method takes forever.

**Comment by kzshantonu** [comment]
would really love this <3

**Comment by drfunkencluck** [comment]
How did you build it with subscription import love to see this on newpipe

**Comment by theScrabi** [comment]
It's in work right now.

**Comment by mauriciocolli** [comment]
Almost finished, pull request later on.

**Comment by drfunkencluck** [comment]
would be cool to link up google account then the app can pull subscriptions and saved playlists into newpipe

**Comment by theScrabi** [comment]
No, we want to keep away from google as good as possible.

**Comment by drfunkencluck** [comment]
what about saved playlists

**Comment by speednroll** [comment]
You could simply publish the playlists that you saved in your google account and add them to Newpipe, you will not be able to modify them from here but from your google account

**Comment by justanidea** [comment]
Could we save in local the playlists we find on youtube (like a bookmark) ?

**Comment by drfunkencluck** [comment]
thats an option maybe where newpipe uses a rss feed or channel user-name/ channel id that when i update a playlist or add a subscription on youtube web then new pipe updates.

**Comment by speednroll** [comment]
@justanidea I think that @karyogamy was also working on this in #1004, but I think that you can not modify the remote playlists (which you do not make locally in Newpipe)

**Comment by justanidea** [comment]
Mmh right
