### ISSUE TITLE
Disable descriptive audio. 

### ISSUE THREAD

**Issue by Yuseldin** [TeamNewPipe/NewPipe#6981]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be nice to have an option (maybe in the CC menu) to disable/enable descriptive audio.

#### Is your feature request related to a problem? Please describe it

I was recently watching a video with descriptive audio enabled and I couldn't find anywhere to disable it. 

#### How will you/everyone benefit from this feature?

This app and the people developing are great. Getting features that the competition already has will only make NewPipe Better

**Comment by litetex** [comment]
Viewed the same video on my smartphone and the Android emulator and did encounter any problems...
Maybe it was a short YT problem...

Does the problem still persist?

**Comment by Yuseldin** [comment]
Yes, when I open it on NewPipe descriptive audio is on. 

I originally opened it from this link. https://youtu.be/TjxC-evzxdk

**Comment by uusijani** [comment]
I'm affected by this. Storied from PBS appears the only one of my followed channels to exhibit this, though it may very well be the only one with audio description tracks provided. For instance, [this video](https://youtu.be/3AGesQimq10) has the first description [at t=71](https://youtu.be/3AGesQimq10?t=71) ("A huge orange eye opens"). As with Yuseldin's example, the descriptive track is available, but not selected by default when I open the video in a browser.

**Comment by opusforlife2** [comment]
Ah, yes. I can hear that "orange eye opens" thing. Are streams for such videos doubled or something, and Newpipe is choosing the wrong one?

**Comment by AudricV** [comment]
Indeed, only the first audio streams found are chosen and the other ones are ignored, because streams which have the same properties are currently only added once (there is no way to know the language of an audio stream in the extractor right now).

Merging this issue in the one to support multiple audio tracks, which requires player and extractor changes: #5854. Thank you!
