### ISSUE TITLE
Livestream -> Background: unrecoverable player error

### ISSUE THREAD

**Issue by CBSkarmory** [TeamNewPipe/NewPipe#6989]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to a Youtube livestream (unfortunately I can't provide any links since they are no longer live)
2. Press on `Background` button (icon of headphones)

### Actual behavior

pop-up: "Unrecoverable player error occurred"

However, playing as video and then pressing the android home button allows it to play in the background (though tapping the notification will bring back the video rather than the usual audio-only control interface)

### Expected behavior

It should play in the background (audio only)

### Logs

N/A, no crash/prompt to report bug

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Redmi Note 9S

**Comment by Denisdjt07** [comment]
Hi.
I have noticed exactly the same.
No crash log to report.
Device Model: LG Q6
Android 7

**Comment by mhmdanas** [comment]
Are you facing the issue on a specific video? What service are you using (e.g. YouTube or SoundCloud)?

**Comment by Denisdjt07** [comment]
> Are you facing the issue on a specific video? What services do you face the issue on (e.g. YouTube or SoundCloud)?

It's happened again today. This time I was trying to listen to this livestream as background (https://youtu.be/6vTb5Tmg14g).
I just can run as background when I am playing the video and then a press the android home button.
Every time I try to run using the "background option" I got the error but without trace log.

**Comment by CBSkarmory** [comment]
Edited issue: the "steps to reproduce the bug" section was commented out

**Comment by boringhexi** [comment]
Seems to have been introduced by dfa941a9e78a72a54801be9da6b8b79590121543, going by my testing. 

My steps for testing were: add Lofi Girl stream (currently [here](https://www.youtube.com/watch?v=5qap5aO4i9A)) to a new playlist, then Background play the playlist and see if I get an unrecoverable player error.

**Comment by saurabhinabys** [comment]
> ### Checklist
> * [x]  I am using the latest version - 0.21.9
> * [x]  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
> * [x]  I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
> * [x]  This issue contains only one bug. I will open one issue for every bug report I want to file.
> 
> ### Steps to reproduce the bug
> 1. Go to a Youtube livestream (unfortunately I can't provide any links since they are no longer live)
> 2. Press on `Background` button (icon of headphones)
> 
> ### Actual behavior
> pop-up: "Unrecoverable player error occurred"
> 
> However, playing as video and then pressing the android home button allows it to play in the background (though tapping the notification will bring back the video rather than the usual audio-only control interface)
> 
> ### Expected behavior
> It should play in the background (audio only)
> 
> ### Screenshots/Screen recordings
> ### Logs
> N/A, no crash/prompt to report bug
> 
> ### Device info
> * Android version/Custom ROM version: Android 11
> * Device model: Redmi Note 9S

Same Error on Redmi Note 10 pro with Stock or Custom ROM, Android 11

**Comment by diyachan** [comment]
Reporting similar issue on Samsung M20 running LineageOS 18.1 (Android 11)

**Comment by xxxxme** [comment]
> Oddly enough I found a condition where it works - start playing in the foreground and then switch to another app with the OS task switcher.

This was mentioned earlier.

Issue still present in 0.21.13

**Comment by kavemang** [comment]
issue still present 0.21.13 S9+ but Im chiming in because im almost positive this this work around ^ causes the player to keep consuming a 480p video stream rather than switching to audio only stream as the background play would do 

im burning through a lot of data while driving because of it :(

**Comment by kavemang** [comment]
> Oddly enough I found a condition where it works - start playing in the foreground and then switch to another app with the OS task switcher.

ive been using this workaround for months but almost positive the phone keeps consuming a video stream based on the bandwidth use, during real audio only background play before this bug started the bandwidth use was around 1/6th what it is with the workaround

**Comment by etienne1911** [comment]
same issue here, I want to save bandwith while watching live stream but get this error while trying to play the live feed in background mode.
I'm on pixel 4a running grapheneOS based on android 12.

**Comment by nofishonfriday** [comment]
Getting this too (Lineage OS/Micro G 18.1), however for me it works tapping on the Play button to play in background after the 'Unrecoverable Player' error occured (since noone seemed to mention it yet).
Here's a screencast, first showing the error this issue is about, then my 'workaround' in the end. 

https://user-images.githubusercontent.com/7658194/147623537-ea5a0620-b16c-4b10-bf61-6179a903fb51.mp4

**Comment by etienne1911** [comment]
I've tryied your tip  but if you pay attention you see the video stream playing behind,  which means it is not audio background only and as a result still consume normal video bandwidth

**Comment by Mr5quid** [comment]
I've noticed since 0.22.1 (haven't noticed it before so I can't tell if it's something new or not) but playing a live stream (Lofi) in background works fine when using wifi but not cellular data.
If using cellular data I get the same error as @TiA4f8R : 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=1] occurred while playing https://www.youtube.com/watch?v=5qap5aO4i9A
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux Android 11 - 30 (LineageOS 18.1)
* __LOS Build number__: lineage_fajita-userdebug 11 RQ3A.211001.001 10038629
* __Device:__ OnePlus 6T
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.4D401F, 1568726, null, [854, 480, 30.0], [-1, -1]), format_supported=YES
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:223)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(3, null, null, video/avc, avc1.4D401F, 1568726, null, [854, 480, 30.0], [-1, -1])
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1051)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:606)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1465)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:713)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:998)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:830)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
... 3 more
Caused by: java.lang.IllegalArgumentException: The surface has been released
at android.media.MediaCodec.native_configure(Native Method)
at android.media.MediaCodec.configure(MediaCodec.java:2127)
at android.media.MediaCodec.configure(MediaCodec.java:2043)
at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:50)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1137)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1044)
... 10 more

```
</details>
<hr>

**No error when using wifi and plays live stream in background as expected**.
If switching from cellular to wifi, I need to completely close the app first (exit from notification drawer + remove from multitask view), otherwise the error still occurs. Interestingly, switching back and forth from wifi to cellular once the stream is playing properly in background does not break it, i.e live stream keeps playing in background (maybe up until a certain point? Only tried for a couple of minutes each time).

**Comment by mhmdanas** [comment]
Fixed by https://github.com/TeamNewPipe/NewPipe/pull/8020.
