### ISSUE TITLE
[Feature] Allow typing Directories

### ISSUE THREAD

**Issue by Omar-tamer** [TeamNewPipe/NewPipe#6997]
I recently had an issue where i had removed google's file manager from my phone using adb which ended me up with not being able to set my downloads directory and crashing newpipe on import /export,
after i reinstalled G file manager using an apk ,I uninstalled its updates which should have reset it to factory 

However, doing so made it a bit buggy I think as it gets stuck in directories, icons overlap and doesnt show internal storage even when i select it in the hamburger menu and then open the menu from the left.
as a result
i'm currently unable to set my downloads foldernn to anything except for:
content://com.android.providers.downloads.documents/tree/downloads .
which got me a bit infuriated  so....
I think i just had a good idea why not just type out the directory myself? Brilliant, I know...lol.
so i was wondering wether or not it would be possible to implement this functionality as a feature in Newpipe
 I love Newpipe so much and Google's file manager has actually plagued me quite a bit ever since update 2.6 .

you could just add a little pen icon to edit the directory of the downloads folder for music and videos at the right end of the button .clicking on it would make the keyboard and a little place where you can type popup while pressing anywhere else would open the normal file manager

oh also picking the quality on a livestream would also be nice.
Thx a ton in advance : )
P.S.
sorry if this isn't where im supposed to request features i'm kind of a github noob.

**Comment by litetex** [comment]
I would strongly oppose that feature as NewPipe is not a file manager...

This would add new code which requires maintenance, etc.

Simply install and use a normal/the built-in file-manager and everything works as expected 😄

**Comment by opusforlife2** [comment]
@Omar-tamer Try the app Material Files by zhanghai. It's on F-Droid. It offers to become the default content provider so you could check if it solves your problem.
