### ISSUE TITLE
Multi-video selection

### ISSUE THREAD

**Issue by TippyLion28** [TeamNewPipe/NewPipe#6998]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be helpful if long-pressing a video thumbnail would activate a multi-item selection mode. At present, there is no way currently to batch perform operations on large playlists/feeds. 

#### Is your feature request related to a problem? Please describe it

No

#### Additional context

Happy to explain further if this is unclear in any way

#### How will you/everyone benefit from this feature?

I've recently migrated my enormous BubbleUPNP playlist over to NewPipe (wrote a NodeJS app that converts the XML data to SQL queries that run against the NewPipe database - that was fun) 

While it's nice that I now have my playlist in NewPipe, it's a pain having to perform operations on multiple videos at a time. Being able to select a bunch and delete them for example would be awesome.

**Comment by SameenAhnaf** [comment]
Duplicate of #5832.

**Comment by TippyLion28** [comment]
My bad
