### ISSUE TITLE
[feature request] auto replay

### ISSUE THREAD

**Issue by daniell1** [TeamNewPipe/NewPipe#7]
Last feature for today: auto replay :wink:

**Comment by theScrabi** [comment]
Hm. Ok i'll keep that in mind.

**Comment by theScrabi** [comment]
How about i add a button when you click on it video restarts?

**Comment by timofonic** [comment]
That's nice. And if doing long press, you make it automatic replay.

This could be useful for memorizing and music.

**Comment by theScrabi** [comment]
Ok replaying for music and video. Would you like to add an issue for that?
