### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#70]
Hello there,

I plan to use [TravisCI](https://travis-ci.org/) for developing NewPipe. Therefore we might need to introduce Unit Tests. To all the NewPipe Developers, what do you think about that idea?

**Comment by shekhar12020** [comment]
Yes, that's a good idea. :blush:

**Comment by theScrabi** [comment]
Ok on saturday im on a devops bar camp there i hope to get it started.

**Comment by rrooij** [comment]
A good idea!

**Comment by theScrabi** [comment]
Oh yes well CI is working, but it would be helpfull if there where some tests for the crawler. So wed have a pre warning mechanism if youtube changed their side aigain, or we did something wrong.
