### ISSUE TITLE
Differents icons for popup mode and normal mode

### ISSUE THREAD

**Issue by AndroKev** [TeamNewPipe/NewPipe#700]
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.

Hello,

i don't know if it is possible. But i think it is usefull that the share menu has differents icons for the normal mode and the popup-mode, so you can see with one look which mode you choose.

here is an example:
![screenshot_2017-09-18-12-15-02](https://user-images.githubusercontent.com/3259510/30542156-8030da52-9c7e-11e7-91c2-6abb5698699f.jpg)

**Comment by Stypox** [comment]
The share-to-newpipe has been redesigned
