### ISSUE TITLE
Video not found

### ISSUE THREAD

**Issue by ale5000-git** [TeamNewPipe/NewPipe#7001]
### Checklist

- [x] I am using the latest version - v0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open: https://m.youtube.com/watch?v=ZoqkOUmFC5E&feature=youtu.be
2. NewPipe say: Video not found (it works from the browser)

### Actual behavior

It say: Video not found

### Expected behavior

See the video.

### Device info

 - Android version/Custom ROM version: 10
 - Device model: Ulefone Armor 10 5G

**Comment by litetex** [comment]
Thank your for reporting an issue!

> NewPipe say: Video not found (it works from the browser)

The video is age restricted.

You have to enable age-restricted videos in "Settings>Content>Show age restricted videos"

However the errorview which should tell you that it's age restricted fails to show up. 
I will report this as a new issue.
