### ISSUE TITLE
Weird glitching effect when pinching in popup mode

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#7007]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open newpipe
2. Start a video
3. Open in popup mode
4. Pinch to zoom
5. See issue

### Actual behavior

It glitches.

### Expected behavior

Smooth zooming

### Screenshots/Screen recordings

https://mega.nz/file/KoVE0JAR#LP4OGAgUx4F3is5-Qi3uNESCu2E8BqCj5ayL409BIXY

### Device info

 - Android version/Custom ROM version: 9.0
 - Device model: Samsung Galaxy A8+

**Comment by litetex** [comment]
Why is your screen resolution so low?
And/Or your font size/text so big?

Have you tested it with "normal" screen resolution / font size / text?
Does the error also happen there?

Couldn't reproduce the problem on Android emulator or my smartphone, so it has to be a device / software specific one.

What version are you using? You didn't fill it out in the template.

**Comment by Thewisem** [comment]
I did, it is version 9

**Comment by Thewisem** [comment]
Its not my phone. It belongs to an elderly person who has issues reading smaller texts, so yeah the text size is big.

**Comment by litetex** [comment]
> I did, it is version 9

Oh bad specification from my side: 
I meant the version of the app 😄

**Comment by Thewisem** [comment]
I ticked the latest version

**Comment by Thewisem** [comment]
0.21.9

**Comment by litetex** [comment]
Filled it in for you.

However please note:
``- [x] I am using the latest version - x.xx.x <!-- Check https://github.com/TeamNewPipe/NewPipe/releases -->``

**Comment by Thewisem** [comment]
Ohhh so we have to write it, ok. Anyways thanks

**Comment by Thewisem** [comment]
:)

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?
