### ISSUE TITLE
Better handling of ExoPlayer/unrecoverable player errors

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#7008]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Having some sort of error dialog would be nice when a "unrecoverable player error" occurs.

Basically all code that's in here:
https://github.com/TeamNewPipe/NewPipe/blob/793b88a7d48bd6ce7b24620c94729d73448fa365/app/src/main/java/org/schabi/newpipe/player/Player.java#L2472-L2569

Maybe it would be also a good idea to have a option to dis/enable the error-dialog in the settings.

#### Is your feature request related to a problem? Please describe it
There have been multiple issues in the issue-tracker where a (somewhat) random unrecoverable player error occurs.
However no one can tell what happens because there is just a tiny toast-message that says "unrecoverable" player error.

#### How will you/everyone benefit from this feature?
Issues/Errors with more information → more information to diagnose the problem → faster problem fixing 😄

**Comment by litetex** [comment]
Fun fact the same code is used since 2017 / v0.11.0 and no one ever changed it (very much) 😆 → https://github.com/TeamNewPipe/NewPipe/commit/1fb3774e0332f39c7ac48ea17b6a82544b29aba7

**Comment by opusforlife2** [comment]
Absolutely! It's so infuriating to encounter this error but not know what exactly went wrong. It's even more annoying when other people you recommend Newpipe to encounter such errors. It makes a bad impression and you can't even tell them it's a known bug that will be fixed soon.

**Comment by litetex** [comment]
Okay, I did a bit of experimenting/digging around:
* It's very hard to get an player error in the first place, so for debugging proposes there should be a new button to simulate one
  * I was only able too reproduce an error with https://github.com/TeamNewPipe/NewPipe/issues/6989 in the emulator
* It's difficult to impossible to show a specific player error dialog when the player is running in popup or background mode (no UI). "Normal" mode works fine. → Add a setting to report player errors to acra would be best
