### ISSUE TITLE
Use Retrolambda to simplify Code

### ISSUE THREAD

**Issue by Nutomic** [TeamNewPipe/NewPipe#701]
Retrolambda brings Java 8 lambdas to Android, which makes code involving callbacks much simpler. This should work especially well with RxJava.

https://medium.com/swlh/party-tricks-with-rxjava-rxandroid-retrolambda-1b06ed7cd29c
https://github.com/evant/gradle-retrolambda

**Comment by Nutomic** [comment]
@theScrabi @mauriciocolli Does anything speak against this? If you like it, I can make a PR.

**Comment by theScrabi** [comment]
Maybe the fact that we put another library into newpipe. They got quite a lot lately.

**Comment by wb9688** [comment]
@theScrabi: Retrolambda isn't really a library, it's more like a
transpiler. You run it with Gradle and it makes Java 7 bytecode from Java 8
bytecode.

**Comment by theScrabi** [comment]
I see.

**Comment by wb9688** [comment]
@theScrabi: The only con I see is that it is Java 8-only, so you can't
compile NewPipe with Java 7 then and probably not with Java 9, which will
be officially released tomorrow, either.

**Comment by theScrabi** [comment]
Also even if its not a lib, it will introduce a new dependency. Which i would rather prevent.

So its a no from my side its a no.

**Comment by wb9688** [comment]
@theScrabi: Why would you want to prevent another dependency? Btw it's also
a no from my side, because it's Java 8 only.

**Comment by Nutomic** [comment]
@wb9688 What makes you think that it won't work with Java 9? Maybe it won't be supported initially, but I'm sure support would be added soon in that case.

@theScrabi There is absolutely nothing wrong with having many dependencies. Especially when they simplify the code and make development easier.

**Comment by theScrabi** [comment]
Because the more dependencies you introduce the more you relay on the work of others. This can become a hell on some point. Just think if someone foes not want to continue a project (GigaGet great examble), or some destroys or revokes a pavkage/repo. Remember the node.js disaster where someone revoked a package, and brokr hundreds of projects with that.

Also it blowds things, so im rather against "repo hording/repo shopping" :D

**Comment by Nutomic** [comment]
Maven Central [doesn't allow deleting packages](https://stackoverflow.com/a/9789816/1837158), so this is not something to worry about. And if the project owner doesn't want to work on it any more, it can just be forked.

**Comment by theScrabi** [comment]
Still.
I mean it's not like i would prevent adding repo/preprocessor, but it has to have real advantage for the project.

**Comment by theScrabi** [comment]
Yea but still i think its good to try to ceep dependency low.

**Comment by mauriciocolli** [comment]
The good news is, we don't need another dependency: 
https://developer.android.com/studio/write/java8-support.html

The bad one is that we have to use Android Studio 3.0, which is still in beta. I would prefer to wait a little more too see if we'll have a stable one soon.

It has some limitations, but the main things are already supported and we definitely would make good use out of it, especially after we introduced RxJava.

**Comment by Nutomic** [comment]
FYI lambdas are now officially supported by the Android Gradle plugin.
