### ISSUE TITLE
0.21.9 crashes while Listening

### ISSUE THREAD

**Issue by Starfoxfs** [TeamNewPipe/NewPipe#7012]
Newpipe 0.21.9 crashes while listening to music.

Don't know if this is the same Wlan disconnect issue that i posted here [https://github.com/TeamNewPipe/NewPipe/issues/5168](https://github.com/TeamNewPipe/NewPipe/issues/5168)

Device is Galaxy S4 GT-I9505 with Lineageos 18.1

After Crash Wlan is enabled but disconnected continuously

[crashlog.txt](https://github.com/TeamNewPipe/NewPipe/files/7072413/crashlog.txt)

**Comment by litetex** [comment]
Likely the same issue as stated in #5168 

Exception: 
``Unable to resolve host "www.youtube.com"...``

→ network problem, no NewPipe problem

Also please use a template next time for the issue - if possible.
