### ISSUE TITLE
Stuck at landscape mode

### ISSUE THREAD

**Issue by atul1503** [TeamNewPipe/NewPipe#7017]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play any non-shorts video in fullscreen mode such that the video plays in horizontal mode.
2. Let it finish.
3. Groan/Laugh/Cry at what shows up next...

### Actual behavior

The whole app is stuck at landscape mode/horizontal mode. BTW I m surprised no one reported this issue before.

### Expected behavior

Suppose if I am using the app in vertical mode and just to watch the video I play it in fullscreen mode and the video starts playing in horizontal mode(no issue here at all) but after the video ends it should revert to non-fullscreen mode (or to the mode the app was on before the video was fullscreen-ed) 
But the whole app is stuck at landscape mode/horizontal mode.
Even after clicking the back button you would expect that the app will remember and acquire the mode that it was on before going on the fullscreen mode to watch the video..but no. You have to kill the app to get the normal mode back on restart.
And, auto rotation was off the whole time.

### Device info

 - Android version/Custom ROM version: 9 PKQ1.180917.001
 - Device model: Redmi 6 Pro

**Comment by XiangRongLin** [comment]
Can you check the setting "Appearance > Tablet Mode" and turn it off to see if this changes anything?

**Comment by atul1503** [comment]
I did it just now.It didn't make any difference.Although,if 
auto rotate is off,and if you hold it vertically,the mode changes to portrait mode..but please make it work without auto rotate.

**Comment by Ammako** [comment]
#5967

**Comment by atul1503** [comment]
After the locked landscape mode,If I click on fullscreen button,it changes back to portrait mode.So,I m closing the issue.
