### ISSUE TITLE
Can I Change Quality/Resolution On Livestream? If Can, How? 

### ISSUE THREAD

**Issue by UguBuga** [TeamNewPipe/NewPipe#7019]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

**Comment by SameenAhnaf** [comment]
Unfortunately, no at this moment. There's already #1239 for that.

**Comment by mhmdanas** [comment]
It's as @SameenAhnaf says. Also, please fill in the template properly next time you open an issue.

**Comment by UguBuga** [comment]
I am very sorry, I just started using xda like 1 weeks ago and i am rarely
online so i don't know how to open issues properly. Thank you for helping
me. I am really appreciate it. Sorry for bad English.

**Comment by UguBuga** [comment]
Oh it's not xda, it is github. I am really sorry for that.

**Comment by mhmdanas** [comment]
No worries, just try to be more careful next time.

**Comment by UguBuga** [comment]
Thanks, I will.
