### ISSUE TITLE
Option to move the Main & Subscription bar to the top.

### ISSUE THREAD

**Issue by tigbit** [TeamNewPipe/NewPipe#702]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It gets really bothersome when i have to reach for the nav buttons and accidentally press on the bottom tabs, this was the reason why i had to stop using the official youtube app. Plus i think it would give the app a much more streamlined look specially when someone is using onscreen nav bar. Bottom tabs on top of nav bar really clutters the whole U.I.

I did read [this](https://github.com/TeamNewPipe/NewPipe/issues/650) thread but didn't see the bottom bars discussion to reach to conclusion and v0.10.0 just released which just placed the main & subscription at the bottom of the screen. 

So, if its possible, an option in setting which allows us to move the tabs to top would be much appreciated and very convenient since the tabs are swipe-able.

**Comment by theScrabi** [comment]
The tabs will (hopefully) move up anyway. As far as I know the reason for the tabs to be at the bottom right know was that for now it was easier to implement.  However I'm not sure but I thought that now where @mauriciocolli re factored everything including the UI, moving tabs up might now be possible.

**Comment by wb9688** [comment]
@theScrabi: Implementing tabs at the bottom is easier indeed. We'll indeed
move them to the top in #693. I've already quickly looked into that and I
came to the conclusion that we'll need to refactor it a little bit more,
but like I've said, I'm not that good with Android UI stuff and I'm
currently busy with the PipeCast library, so I won't do that.

**Comment by theScrabi** [comment]
That is absolutely fine :)

**Comment by tigbit** [comment]
That's great to hear! 
Keep up the good work.
