### ISSUE TITLE
Limited support of 0.19.8 version with 0.21.9 extractor

### ISSUE THREAD

**Issue by bookkojot** [TeamNewPipe/NewPipe#7020]
I created this hybrid for those who love the good old video viewer. Not a modern monster.

Compared to the previous version:
* comments work
* works 18+ videos
* updated extractor to the latest version (0.21.9)

You can download a script for the building or a ready-made build. 
[newduck-0.21.9.zip](https://github.com/TeamNewPipe/NewPipe/files/7074293/newduck-0.21.9.zip)
[newduck-21-9.txt](https://github.com/TeamNewPipe/NewPipe/files/7074294/newduck-21-9.txt)

**Comment by mhmdanas** [comment]
Why does this have the exact same name as #5172 (Newduck)? If it is indeed based on Newduck, I would close this issue and create a comment there instead, to avoid cluttering up the issue tracker.

**Comment by nbmrjuhneibkr** [comment]
https://github.com/XiangRongLin/NewPipe-preuinified also exists.
