### ISSUE TITLE
Newpipe can access storage without permission.

### ISSUE THREAD

**Issue by Kjafr** [TeamNewPipe/NewPipe#7021]
### Checklist

- [x] I am using the latest version - 0.21.9
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x]  This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Deny storage permission for Newpipe
2. Open Newpipe and download any video
3. Starts download without asking for storage permission in pop-up notification

### Actual behavior
I deny Newpipe access to device storage permission but the app can still freely access and download videos and audio.

### Expected behavior
After pressing the download button a pop-up notification to appear asking if I want to give Newpipe storage permission.

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Galaxy A02s

**Comment by Ammako** [comment]
It can't, actually. It can only download if you explicitly tell it to by pressing the buttons. That's how Storage Access Framework works.

If you want to revert back to the old and less-secure style of storage access permissions, just turn off SAF under Downloads, in the options.

**Comment by skmdab** [comment]
But I installed newpipe  today after seeing your issue I checked in my Phone the app really granted any permissions or not..
But there is no single permission granted in my phone.
The app is working freely.

**Comment by skmdab** [comment]
![Screenshot_20210831-003200.jpg](https://user-images.githubusercontent.com/57156958/131390984-87660ca2-a5a3-4439-bf5d-dc6d36fa4a5a.jpg)

**Comment by skmdab** [comment]
But for it asking for permission to access when downloading first time..

**Comment by skmdab** [comment]
On second time download Time it doesn't ask for any permissions..

**Comment by Kjafr** [comment]
I have never given it the permission to access storage. I enter into my settings and it states ''permission denied'' on the storage permission but when I enter the app I can still download content without the android prompting me to allow Newpipe to access storage.

**Comment by Kjafr** [comment]
![288740e3-9467-4ec7-98e5-03139117e43a](https://user-images.githubusercontent.com/89753845/131404868-5fb8777a-5372-4ce4-9089-4aa3c9d24f62.jpg)

**Comment by Kjafr** [comment]
Despite what app permissions states in the image above, I can still download from Newpipe, unlike most apps where denying this permission disallows downloads until permission is given. Newpipe Legacy does ask for permission to access storage when I attempt to download a file and storage permission is denied. What could be the cause of Newpipe being able to surpass this permission be?

**Comment by Kjafr** [comment]
> On second time download Time it doesn't ask for any permissions..

My problem here is that it never appeared in the first place.

**Comment by Kjafr** [comment]
> It can't, actually. It can only download if you explicitly tell it to by pressing the buttons. That's how Storage Access Framework works.
> 
> If you want to revert back to the old and less-secure style of storage access permissions, just turn off SAF under Downloads, in the options.
> 
> SAF means an app only gets read/write access to the specific file you're giving it access to, and it can only use that access once. It can never just access stuff without permission.

![d4425db0-7f80-4d2b-b3e3-538458b35643](https://user-images.githubusercontent.com/89753845/131440806-e45228f6-404c-4801-802f-bb250c55aaf9.jpg)

It's greyed out in my case. Would you mind going into more detail? as I don't fully understand.

**Comment by skmdab** [comment]
> I have never given it the permission to access storage. I enter into my settings and it states ''permission denied'' on the storage permission but when I enter the app I can still download content without the android prompting me to allow Newpipe to access storage.

Me too same

**Comment by Ammako** [comment]
It literally does not matter. I suggest you read up on how SAF works. An app cannot simply act by itself to access your files. It can only access the specific file(s) you give it access to by selecting them in the file picker.

https://developer.android.com/guide/topics/providers/document-provider

That's the whole point. Enabling apps to read or write what they need without having to grant them full access to your entire storage.

Regardless, if you truly believe you've found a bug that allows an app to bypass Android permissions, it should be reported to AOSP. The app has nothing to do with it.

**Comment by Kjafr** [comment]
> It literally does not matter. I suggest you read up on how SAF works. An app cannot simply act by itself to access your files. It can only access the specific file(s) you give it access to by selecting them in the file picker.
> 
> https://developer.android.com/guide/topics/providers/document-provider
> 
> That's the whole point. Enabling apps to read or write what they need without having to grant them full access to your entire storage.
> 
> Regardless, if you truly believe you've found a bug that allows an app to bypass Android permissions, it should be reported to AOSP. This wouldn't be the app's responsibility.

I understand now. I apologize for taking up any time better used somewhere else. Thank you for the explanation.
