### ISSUE TITLE
While importing Youtube Subscription Json file to newpipe it gives error that 
It doesn't importing file..

### ISSUE THREAD

**Issue by skmdab** [TeamNewPipe/NewPipe#7025]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

**Comment by mhmdanas** [comment]
Duplicate of #6757. Also, please fill in the template properly when opening an issue.
