### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by sagarikachavan** [TeamNewPipe/NewPipe#7026]
### Version Update

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by mhmdanas** [comment]
I think the error is fairly self-explanatory: if you use Android Studio, update it; if you use IntelliJ IDEA, update the Android Support Plugin. Don't hesitate to make a comment if you face any more trouble.
