### ISSUE TITLE
Remember step for playback speed controls

### ISSUE THREAD

**Issue by Massimo-B** [TeamNewPipe/NewPipe#7031]
Make playback the step width in percent a sticky option, which saves its last state. Usually it's always reset to 25% if you re-open the option dialog on the video screen.

I usually work with 1,15x average speed for speech channels and 5% step width, with the need to adjust according to content and situation, but I always need to adjust the width first, which is annoying.

**Comment by SameenAhnaf** [comment]
Thanks for opening an issue. Renaming the title as ` Remember step for playback speed controls ` sounds more natural to me.
