### ISSUE TITLE
Retain timestamp position while switching between background/normal/popup mode.

### ISSUE THREAD

**Issue by afya** [TeamNewPipe/NewPipe#704]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Currently if I press background playback in the middle of the video, the background player starts from the beginning. Is it possible to have an option for it to retain the time position where I switched mode? And possibly the reverse?

Or simply allow the video to continue playing while screen is off.

**Comment by Stypox** [comment]
This seems to work correctly now.
![ezgif-4-05a387fd4d1b](https://user-images.githubusercontent.com/36421898/59975929-70c82300-95be-11e9-9eff-640062692d96.gif)
