### ISSUE TITLE
Backup and restore subscribed channels

### ISSUE THREAD

**Issue by abhinav96** [TeamNewPipe/NewPipe#705]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Now that v0.10.0 has support for channel subscription, it would be great to have an option to backup and restore the list of subscribed channels. This feature was requested before ([#565](https://github.com/TeamNewPipe/NewPipe/issues/565)), mixed with other requests.

**Comment by theScrabi** [comment]
Yes sounds good :)

**Comment by chanakyashah** [comment]
And it would be nice if we could sort it as well. Like with Relevance, Time or Views.

**Comment by BleuDiamant** [comment]
Yes this will be awesome if you able to export an xml file with your subscription (https://www.youtube.com/subscription_manager?action_takeout=1)

**Comment by jojo313** [comment]
Yes please I dont want to search up 150+ channels again.

**Comment by mauriciocolli** [comment]
See #1145.
