### ISSUE TITLE
Screen rotation

### ISSUE THREAD

**Issue by arjunmsujathan** [TeamNewPipe/NewPipe#7060]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
We can't help you fix the issue if you don't give us any info at all. Please fill in the template and then make a comment when you're done.
