### ISSUE TITLE
Video ending set at 0:00

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#7064]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to newpipe and set bandcamp
2. Play a video
3. Look at when it ends

### Actual behavior

It shows 0:00

### Expected behavior

It should show the length of the video.

### Screenshots/Screen recordings

![Screenshot_20210906-023037](https://user-images.githubusercontent.com/74511929/132144416-826dc5cc-1449-4955-88a8-9f1b1ee3ade3.jpg)

### Device info

 - Android version/Custom ROM version: Android 7.1.1
 - Device model: Samsung Galaxy Tab A SM P555

**Comment by opusforlife2** [comment]
@Thewisem Only Bandcamp? Or other services as well?

**Comment by Thewisem** [comment]
Only noticed on bandcamp
