### ISSUE TITLE
Full Screen video resumes automatically after taking screenshot

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#7067]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Turn auto-rotation off.
2. Open a video in full screen.
3. Pause the video.
4. Take a screenshot and return to the video.
5. Video resumes automatically.

### Actual behavior

Video resumes automatically after returning to player.

### Expected behavior

Video should stay paused if it was manually paused.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/79245641/132243439-874ac360-0237-4b46-85c7-f5b6cb507125.mp4

### Device info

 - Android version/Custom ROM version: Android 11, MIUI 12.5.1
 - Device model: Xiaomi Redmi Note 8 Pro

**Comment by litetex** [comment]
Doesn't occur on my device with the latest release:
* Android version/Custom ROM version: Android 9.1, EMUI 9.1
* Device model: Huawei P20 lite
