### ISSUE TITLE
Screen Rotation

### ISSUE THREAD

**Issue by arjunmsujathan** [TeamNewPipe/NewPipe#7072]
While watching videos in landscape the screen rotation doesn't work properly

**Comment by litetex** [comment]
> While watching videos in landscape the screen rotation doesn't work properly

It's impossible to tell what is wrong here without using the template properly.
Please open another valid bug report or fill out the template.

**Comment by arjunmsujathan** [comment]
The app is not responding screen rotation properly

**Comment by opusforlife2** [comment]
@arjunmsujathan Here's a link to the template chooser. It  doesn't seem to be supported by 3rd party apps yet: https://github.com/TeamNewPipe/NewPipe/issues/new/choose
