### ISSUE TITLE
"Search Suggestions" setting not imported

### ISSUE THREAD

**Issue by XiangRongLin** [TeamNewPipe/NewPipe#7075]
### Checklist

- [x] I am using the latest version - curent dev branch and soon to be 0.21.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to Settings > Content > Search Suggestions and uncheck "remote xyz"
2. Go to Settings > Content > Export database and export it
3. Go to Settings > Content > Search Suggestions and check "remote xyz"
4. Import the database from step 2
5.  Go to Settings > Content > Search Suggestions

### Actual behavior

"remote xyz" is checked

### Expected behavior

"remote xyz" is unchecked

### Device info
not relevant

### Note
It took me more time writing this issue, than fixing it myself. So I would appreciate if it was actually left for newcomers

**Comment by laksh-21** [comment]
Hi! I'd like to work on this.
