### ISSUE TITLE
Inconsistent app behaviour media fast forward and rewind

### ISSUE THREAD

**Issue by tarun0** [TeamNewPipe/NewPipe#7079]
### Checklist

- [x] I am using the latest version - 0.21.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Execute input key event keycode_media_fast_forward (90) keycode_media_rewind (89) by using some scripting program or using any keyboard/mouse with media control (an emulator can be used from Playstore - serverless mouse by appground io)
2. The bug can be observed irrespective of foreground/background state.

### Actual behavior

In fast forward event the video goes ahead by 15 seconds and in rewind event the video goes back by 5 seconds irrespective of the settings defined in the app

### Expected behavior

Consistent rewind and fast forward duration as specified in the settings. Usually both are same for example 10 seconds. It should be same as double tap on the video player

### Device info

 - Android version/Custom ROM version: API 26 stock rom emui 8
 - Device model: Huawei tablet 10 inch

**Comment by tarun0** [comment]
should be related to  https://github.com/TeamNewPipe/NewPipe/pull/6985

**Comment by opusforlife2** [comment]
@tarun0 So is it fixed in the current RC? You can get it from the pinned issue.

**Comment by tarun0** [comment]
@opusforlife2 Confirmed issue Not fixed in the latest update and in fact aggravates it. Fast forward jumps by 30 sedonds and rewind by 15 seconds.
