### ISSUE TITLE
"Continue watching" toast notification

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamNewPipe/NewPipe#7081]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Currently there is an option to continue a partially watched movie from the point the user stopped watching, or just ignore playback positions. It would be nice to have an option to show a toast notification asking the user if they want to "continue watching".

#### Additional context

Many browsers use toast notifications. Here is a screenshot from firefox:
![firefox-qwe](https://user-images.githubusercontent.com/50382414/132594535-4922f8e6-017b-4e3c-be63-bf30e59d53dd.jpg)

**Comment by SameenAhnaf** [comment]
Please keep the discussion in #6380.

**Comment by litetex** [comment]
Consolidated into #6380
