### ISSUE TITLE
Potential performance problem with MediaSessionManager#get/setMetadata

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#7087]
### Checklist
- [x] I am using the latest version - 0.21.9 / develop
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Run the app / play a video (in the background).

What I did:
Opened a video and ran it in the background.

### Details
NewPipe performs a progress update when the player is active every 500ms/1s (was increased to 1s in #7071).

However when this progress update is executed the ``setMetadata``-method seems to be very costly (takes 40-80% of the time of the complete progress update) as seen when profiling the app:

<details><summary>Emulator Pixel 3a</summary>

[cpu-emulator-Pixel3a.zip](https://github.com/TeamNewPipe/NewPipe/files/7146749/cpu-emulator-Pixel3a.zip)

<img src="https://user-images.githubusercontent.com/40789489/132923638-8e16eea3-44e2-4077-84a4-5c1683f2c9f4.png">

</details>

<details><summary>Emulator Pixel C</summary>

[cpu-emulator-PixelC.zip](https://github.com/TeamNewPipe/NewPipe/files/7146750/cpu-emulator-PixelC.zip)

<img src="https://user-images.githubusercontent.com/40789489/132923471-e51a6810-2cdb-4fd9-a410-369fde396eec.png">
<img src="https://user-images.githubusercontent.com/40789489/132923587-1d8ad1ee-b3cc-4db6-9860-2ffd0ba086bc.png">

</details>

Note: I'm unable to determine if this is just a android emulator problem as I can't profile my real phone (crashes with SIGSEV in HeapTaskDaemon/libc when running the profiler)

### Device info
 - Android version/Custom ROM version: Android 11 - API 30
 - Device model: Android Emulator Pixel 3a/Pixel C

**Comment by Redirion** [comment]
while looking at setMetaData I noticed another issue:

`// setMetadata only updates the metadata when any of the metadata keys are null
        mediaSessionManager.setMetadata(getVideoTitle(), getUploaderName(),
                showThumbnail ? getThumbnail() : null, duration);`

in other words, if showThumbnail is false, metaData updates do never happen!

I will create a PR for that. 

For the performance of this method I wonder if this is not an issue of inspecting the performance on the debug build. Did you also try to check how the performance is, without all the Logs?

**Comment by Redirion** [comment]
@litetex can you check your logcat: does "setMetadata: N_Metadata update" appear every 1 seconds? that would be a bug. Please try my PR in comparison. Do you have "Show thumbnails" set to "off"?

**Comment by litetex** [comment]
Okay I tested the stuff a bit and found out that the metadata updates - that are done every second - are completely useless.
They should only be done when the metadata changes e.g. when opening a new video.

**Comment by Redirion** [comment]
yes, and that's how it works / should work. When I was testing my PR, it was working this way.
What is the log output of setMetadata: N_Metadata update for you?

**Comment by litetex** [comment]
@Redirion 
It seems to be fixed as it only occurs once in the log 😄
With my code on top - where the update only occurs when the metdata is changed - this is definitely fixed.
