### ISSUE TITLE
Suggestion for the most complete app

### ISSUE THREAD

**Issue by Jeiel17** [TeamNewPipe/NewPipe#7091]
I suggest that the app has a way of interacting with like videos, comments, subscribing... becoming obsolete from YouTube.

similar to this app: https://play.google.com/store/apps/details?id=free.tube.premium.advanced.tuber 

And improve the designer by mixing two gradient colors.

[Google translate 🇧🇷]

**Comment by opusforlife2** [comment]
Please use Google Translate to understand and fill out the template. Not filling it is not an option.

**Comment by mhmdanas** [comment]
> I suggest that the app has a way of interacting with like videos, comments, subscribing... becoming obsolete from YouTube.

That's probably not going to happen, at least not for YouTube; see https://github.com/TeamNewPipe/NewPipe/issues/679#issuecomment-328049404. There are various other reasons too.

Please note that the app you mentioned is an illegal modified version of NewPipe. Please don't use it.

> And improve the designer by mixing two gradient colors.

You can open a separate issue for that, but my gut tells me it probably won't be implemented.
