### ISSUE TITLE
Youtube Takeout is csv

### ISSUE THREAD

**Issue by Aesew** [TeamNewPipe/NewPipe#7093]
Newpipe only support subscriptions.json but even after i tried so many times my takeout file type is subscriptions.csv . Because of this i can't import my subscriptions to newpipe.

**Comment by jackleson** [comment]
this is already an open issue. check for existing issues before making a new one.

**Comment by Aesew** [comment]
> 
> 
> this is already an open issue. check for existing issues before making a new one.

Okay, i didnt saw it. Thanks for mentioning can you give me a link so i can follow it :)

**Comment by jackleson** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/7066

read under the "new" item 22

**Comment by Aesew** [comment]
> 
> 
> #7066
> 
> read under the "new" item 22
> waiting for release 21.10 myself as well.

Thanks, it's good thats a incoming feature. Also i did a little search that i should have maked before making this thread and here is my findings.
>  https://github.com/TeamNewPipe/NewPipe/issues/5370
>  https://github.com/TeamNewPipe/NewPipe/issues/1751
>  https://github.com/TeamNewPipe/NewPipe/issues/6757
Also found this link from last link https://tbjgolden.github.io/newpipe-csv-json-fixer/  .
I think ,hope, this will work until the update releases.
