### ISSUE TITLE
Playback speed profile or Easier adjusts

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [TeamNewPipe/NewPipe#7096]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I often use 2.0x speed for videos in my native language, 1.3x speed for English videos, and 1.0x speed for musics.
I want to adjust videos exactly at that speed especially for musics, but the speed adjuster is a little bit hard to handle.

If I can save these settings and switch them instead of drag the bar every time it would be better.
Or simply use another method to adjust the playback speed, like direct input or fine tune button together with the drag.

**Comment by SameenAhnaf** [comment]
No, this feature is useful. The slider option isn't as smooth as expected.

**Comment by Liquid-Aristocracy** [comment]
> No, this feature is useful. The slider option isn't as smooth as expected.

I just found the -25% +25% on playback speed control are two buttons, and the step settings below it may adjust the step, so I closed this issue because I think that's enough for me. Do you think playback profile would worth to implement?

**Comment by SameenAhnaf** [comment]
Many users require different number of steps but similar speed options. For example, users may require 0.91x, 2.54x and 1.8x.

0.91x: Turn step 10%. Decrease for one time from 1x. Again, turn step 1%. Increase 1%.
2.54x: Turn step 100%. Increase for one time. Again, turn step 50%. Increase for one time. Again, turn step 1%. Increase for four times.
1.8%: Turn step 10% and increase for eight times. Tapping the same button eight times is no joke!

When I used Newpipe for the first time, I myself really got frustrated while understanding the step option as it's a pretty uncommon thing for most users. Swiping the bar on small screen also comes with a lot of trouble.

Predefining upto 5 options should make the experience hassle-free and any specific speed option will be easily accessible.

**Comment by RashimNarayanTiku** [comment]
Please add a setting to enable predefined playback speeds just like YouTube, fiddling with scrollbar is hard whenever I want to reset the speed.

It would improve the experience by allowing one click to increase the playback speed instead of two clicks now.
