### ISSUE TITLE
Option to auto-trigger Background or Popup from video list

### ISSUE THREAD

**Issue by apoapostolov** [TeamNewPipe/NewPipe#710]
In Preferences, please add an option with a dropdown of what happens when you click on a video in a list:
* Video Screen (the current default)
* Background Play (stay on search/videos list but video plays in background)
* Popup (stay on search/videos list but video starts playing in a popup)

Also, another such option for videos opened from another app:
* Video Screen (the current default)
* Background Play (the video starts playing in the background without loading NewPipe UI)
* Popup (the video appears in popup without loading NewPipe UI)

**Comment by theScrabi** [comment]
We spoke about the second option before, but we came to the conclusion, that doing this directly would spam the android share menu full with NewPipe options. So we came to the conclusion we should add a sub menu there. However it didn't get implemented yet.

**Comment by mauriciocolli** [comment]
Here's the issue for the second request #643.

**Comment by apoapostolov** [comment]
Hello @theScrabi

Thank your feedback. I am not suggesting that we add a context menu for every click on a video in the in-app videos list, or we add a share menu options for every behavior.

I am asking that we add in the Preferences of NewPipe two options:

Default playback in-app: normal [defaut]; auto-fullscreen (directly landscape full screen video); background playback (without entering video screen); popup (without entering video screen).

Default playback when opened from other apps: normal [defaut]; auto-fullscreen (directly landscape full screen video); background playback (without entering video screen); popup (without entering video screen).

**Comment by theScrabi** [comment]
All right, that sounds reasonable.

**Comment by Stypox** [comment]
I think this is partially solved via the long-press menu

**Comment by Stypox** [comment]
Please give some feedback about the proposed solution in #2583 :-)

**Comment by Stypox** [comment]
I am closing this, since it's not going to be implemented, or at least not this way. The long press menu is available instead.
