### ISSUE TITLE
Disappearing downloads

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#7105]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start a download and exit the app
2. Use another app for a while or clear NewPipe from recents
3. Come back to NewPipe and check the downloads, the downloading file is gone
4. Try redownloading the same video it will say 'download already exists replace?' and when you click replace it starts from scratch.

### Actual behavior

The downloading files disappear after switching to other app or clearing NewPipe from recents. This bug seems to be with the last two versions. This may be connected to the already existing bug (#5542) of background downloading in which the app 'stops' the download when you switch to other app and continues when you come back

### Expected behavior

The downloads to continue in the background and not disappear.

**Comment by NewNewPipe** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/7059
