### ISSUE TITLE
Use Oreo PiP mode for floating videos

### ISSUE THREAD

**Issue by flipflop97** [TeamNewPipe/NewPipe#712]
Android 8.0 has introduced a native PiP mode. Can this be used instead of the custom overlay window? In my opinion it works much more intuitively.

**Comment by theScrabi** [comment]
We would have to add it as an additional function. Someone had to implement it.

**Comment by krompus** [comment]
they both do different things; PiP can't resize like Newpipe; native popups. I do agree that PiP support would be great. The swipe to close is much nicer than pulling down the notification drawer and dismissing the notification.

**Comment by Zykino** [comment]
Wait you ca resize with NewPipe's overlay? I was about to create an issue for that.
I didn't tryed the Oreo PiP yet but for now I find the Twitch Overlay smoother than NewPipe one:
* Pin with 2 fingers to resize
* Touch the live to make 2 buttons appear for 10sec
  * First button show the live in the app
  * Second button close the PiP overlay

**Comment by theScrabi** [comment]
Yea we talked about two finger mode, but so far it did not yet get implemented.

**Comment by arvindbadri** [comment]
@Zykino double tap and drag :)

**Comment by theScrabi** [comment]
It has been impemented now :)

**Comment by opusforlife2** [comment]
Closing in favour of #2223.
