### ISSUE TITLE
Audio Video Cropping

### ISSUE THREAD

**Issue by umunais** [TeamNewPipe/NewPipe#7120]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

Please introduce video/audio cropping from YouTube videos by specifying start and end timings

**Comment by mhmdanas** [comment]
Duplicate of #4122.
