### ISSUE TITLE
Video going back to start

### ISSUE THREAD

**Issue by dewijones92** [TeamNewPipe/NewPipe#7128]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play a video in pop-up mode
2. Press the fullscreen icon

### Actual behavior

The video plays from the beginning

### Expected behavior

The video should resume from the same position

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Pixel 4a

**Comment by SameenAhnaf** [comment]
Please keep the discussion in #6472.

**Comment by mhmdanas** [comment]
It's probably as @SameenAhnaf says. If you disagree, feel free to make a comment.
