### ISSUE TITLE
Ability to download audio/video with custom tempo/pitch

### ISSUE THREAD

**Issue by IJohnDoeI** [TeamNewPipe/NewPipe#7129]
I think it would be a good addition to be able to (as the title suggests) download audio/video with a custom pitch/tempo.

I think this would benefit everyone as it allows people to mix up the media they consume and gives a creative edge. For example i love downloaded songs at different pitches/tempos as it spices up an old song.

I hope this has convinced you.

Thank you so much for all your work :).

**Comment by SameenAhnaf** [comment]
Won't you be suited by #478? Your suggestion is definitely useful but may cause confusion. Original speed is required sometimes. It's so important that Newpipe player even has a dedicated "Reset" button for this.

**Comment by IJohnDoeI** [comment]
I don't think #478 is on about the same thing. I know it may cause confusion as some may download with a different tempo/pitch without realising but as you say a reset button would solve this, or a pop up asking if you wanted to download it with a pitch/tempo different to the original.

**Comment by SameenAhnaf** [comment]
>I don't think #478 is on about the same thing.

You can always customize speed options in Newpipe player and the same player was suggested to be supported for downloaded files. I know, it's not a direct solution. But the job should get done.

>but as you say a reset button would solve this

But when should the button exactly appear in case of already downloaded files? Unless Newpipe itself has the ability to play downloaded files, it won't be possible to get back to the actual tempo. Moreover, adding such an option will only add complexities while downloading files as most users won't be able to recognize what the option is about.

**Comment by infinitewaveparticle** [comment]
Maybe in Settings there should be an option to enable this option - and other such features that only some people want. It's a common theme for me that apps should be simple on the standard UI, but as customizable as possible in the Settings... I even like the idea of adding Beginner, Mid-Level, and Expert level Settings... Expert level would basically let you control everything. Difficult for a free app made by a few developers in their spare time tho.

**Comment by SameenAhnaf** [comment]
@infinitewaveparticle That's too general for solving this issue. Advanced features should be added as plugins as recommended in #2807.

Having Newpipe as media player should solve most problems. As I stated earlier, there should be always an option to return to original tempo.

**Comment by infinitewaveparticle** [comment]
For sure. I'm in favor of plugins too... Anything for maximum customization. Too bad there's not an AI interface between our brains and github that can understand what we all want in an app and then write the code for it, compile it, and email each of us our own custom apk file.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by brunoais** [comment]
I think this doesn't belong to NewPipe. I think you should do that in a different app after you download the content.
In other words:

1. Download the video
2. Load the video into an app that does such distortion
3. Export the distorted audio.

**Comment by opusforlife2** [comment]
Please edit your issue and fill out the template properly.
