### ISSUE TITLE
Add adaptive icon

### ISSUE THREAD

**Issue by flipflop97** [TeamNewPipe/NewPipe#713]
Android 8.0 introduced adaptive icons, can this be added to the app so it looks less out of place with the rest?

**Comment by theScrabi** [comment]
What can adaptive icon do?

**Comment by flipflop97** [comment]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by mauriciocolli** [comment]
If anyone wants to see the difference (very briefly: it adapts to the user preference, notice the shape of the icons):

<img src="https://user-images.githubusercontent.com/13389907/30725796-8af1e5de-9f1d-11e7-9ea5-8efa68683f49.png" width="350"/>
