### ISSUE TITLE
Intent filters for YT shorts

### ISSUE THREAD

**Issue by ravilov** [TeamNewPipe/NewPipe#7130]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

Parsing URLs for YT shorts works fine, as per teamNewPipe/NewPipeExtractor#418. However NP is not registered in the system to be able to handle shorts URLs. Can this be added to intent filters in AndroidManifest.xml? If I tap on a link in another app and it's a "normal" YT link it happily opens in NP but if it's a "shorts" link it will open in the browser. I'd like it if shorts opened directly in NP as well. 🙂

**Comment by shambu2k** [comment]
Is anyone working on this? This is much needed for me too

**Comment by mhmdanas** [comment]
This sounds like an easy enough issue that I can fix it myself.
