### ISSUE TITLE
NewPipe v0.21.10 broke 'Search History' functionality

### ISSUE THREAD

**Issue by astatine** [TeamNewPipe/NewPipe#7133]
### Checklist
- [x] I am using the latest version - v0.21.10
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Press the search icon
2. Search YouTube for anything, say 'Taylor Swift' and click any of the search suggestions

### Actual behavior
The search itself works, but my searched text 'Taylor Swift' doesn't get added to my search history

### Expected behavior
The searched text 'Taylor Swift' should get added to my search history

### Device info
 - Android version/Custom ROM version: MIUI v12.0.3 running Android 10 32-bit
 - Device model: Xiaomi Redmi 7A (2GB RAM, 32GB storage, 17GB free space)

**Comment by jstetten** [comment]
Even before this release, roughly ⅓ of my newest search terms have sporadically failed to be recorded in my search history. I'm not certain when the problem first appeared, but it's been happening for several if not many weeks. (I use the built-in app GitHub updates).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Im not sure if it belongs here but if the search history is being displayed, it is now displayed in a weird order since the last update.

**Comment by jstetten** [comment]
Yes!

I was going to create a separate issue about this exact problem because it is a much more serious violation of data consistency and it was introduced solely in v0.21.10.

Is it actual timestamp corruptions in the database from the upgrade process, or some sort of sorting error in the app UI layer? I don't know but it is the first showstopper bug I've ever had with this wonderful app, making this version unusable for me.

**Comment by litetex** [comment]
When I reset the app / install it into a fresh emulator I get the same problem. 
However searching once fixes the problem.
Probably some kind of invalid state at startup.

**Comment by Flam3z** [comment]
Wanted to chime in as well stating that I also have a similar issue, seems to be a very low chance that my searched ever get saved at all even after trying different way to get it saved such as, pressing into a suggested search, searching then hitting enter.

**Comment by Anon1444** [comment]
The search history does appear but it doesn't appear in chronological order. I search something, say xyz, then xyz should appear at the top of search history but instead it appears somewhere in between other older searches.
