### ISSUE TITLE
NewPipe doesn't remember last position when I toggle between popup-bg-normal

### ISSUE THREAD

**Issue by NabilAKROUD** [TeamNewPipe/NewPipe#7138]
When changing the player mode (Background, pop-up or normal), NP maintains the original time position.

it's annoying for long videos, for example when I watched a big part of one of it, and for any circumstance I change to popup it will return me to the beginning.

**Comment by SameenAhnaf** [comment]
Duplicate of #6472. Also, please fill in the template properly.

**Comment by NabilAKROUD** [comment]
apologies... thanks👉🏽 #6472
