### ISSUE TITLE
Switch to landscape automatically

### ISSUE THREAD

**Issue by flipflop97** [TeamNewPipe/NewPipe#714]
When you play a video that has a landscape format (almost all of them) you get a small video with black letterboxes beneath and above it. For these videos it would probably more convenient if the device is switched to landscape automatically.

**Comment by davidadriao** [comment]
Not really, I may want to keep the device in portrait mode all the time. It can be a quick video and I don't want the hassle to rotate the device. It's a good idea for a switchable option though.

**Comment by Metaception** [comment]
I think it would be better if we could define the default orientation for the video.
See issue #735.

**Comment by Stypox** [comment]
Video orientation is automatically remembered now, so the problem you are having is resolved
