### ISSUE TITLE
After searching and clicking on a video link, clicking back goes to home screen

### ISSUE THREAD

**Issue by compumaster** [TeamNewPipe/NewPipe#715]
It should go back to search results.

**Comment by theScrabi** [comment]
Dont take the button in the top left take your native buttons to go back.

**Comment by compumaster** [comment]
https://developer.android.com/design/patterns/navigation.html

Hm, you're right.

**Comment by mauriciocolli** [comment]
I think we should go back to search, if the user come from there  (in fact there's a situation quite similar with this in the guide). [Here's what I think (#614 comment)](https://github.com/TeamNewPipe/NewPipe/issues/614#issuecomment-315072921).
