### ISSUE TITLE
SUGESSTION AND PRACTICAL ASPECTS OF NEWPIPE APP

### ISSUE THREAD

**Issue by CebulowyPolaczek** [TeamNewPipe/NewPipe#7155]
This are few things:

- app needs Vr possibility to open this kind of Vr Videos, because they are more popular nowadays,

- the aspect that we can do our own bases of subscriptions is great, but when they are made and I click to them I do not have the list view of this channels with icons I have only the suggestion of new videos which have been added and also without logic of time of adding. So the best solutions could be: I click to my list of saved subscriptions, then I see the option to go to this list with icons or see the last video uploads with logical time added squence,

- the last very important thing is the aspect of research. When I want to find video about specific topic from for example last week I cannot - there is no such option - I can not choose for example from last year, month or week, so as a result I get illogical search results sometimes,

I would be so much grateful and thankful to You if You could change that valuable aspects of using NewPipe application.

**Comment by SameenAhnaf** [comment]
Duplicates of #2835, #5592 & #6878 respectively. Also, please fill in the template properly and only one suggestion at a time.
