### ISSUE TITLE
[Possible Feature] Add Slider to Control in Background Player Notification

### ISSUE THREAD

**Issue by ricksee** [TeamNewPipe/NewPipe#716]
Aside from the forward and backward buttons in the music player in the notification when in the background, is it possible to add a slider to it.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
No. We need a propper ui beside the notification.
