### ISSUE TITLE
Ability to select different Default Video Resolution for `Youtube Shorts` videos

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#7163]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Ability to select different video resolution for Youtube Shorts videos (apart from Normal Videos)

#### Is your feature request related to a problem? Please describe it

I have set default video resolution to 480p. When played in LandScape fullscreen mode, 480p resolution is fine for me.

But problem arises when the Youtube Shorts is played. 
Since these videos are Portrait in nature, when played in full screen mode, the player automatically flips to Portrait FullScreen mode (my phones' Autorotate is turned off, ). I have noticed that the quality of the shorts video in 480p (my default resolution) FullScreen Portrait Mode doesnot look good.
_Note: I could have turned ON phones' Autorotate feature to play video in Landscape mode. But I think Youtube shorts are best enjoyable in FullScreen Portrait Mode_ 

And I am tired of changing the resolution of video from the player as per video being played.  
So I think it would be better to have ability to automatically detect Shorts Videos and play at different Video Resolution (set by user from Settings).

#### How will you/everyone benefit from this feature?
Improves UX.

**Comment by mhmdanas** [comment]
Closing in favor of https://github.com/TeamNewPipe/NewPipe/issues/7170. If you disagree, feel free to make a comment.
