### ISSUE TITLE
Video autopause if exiting fullscreen

### ISSUE THREAD

**Issue by legacychimera247** [TeamNewPipe/NewPipe#7167]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

The video pause itself

### Expected behavior

The video should continue playing

### Device info

 - Android version/Custom ROM version: android 9 (not custom)
 - Device model: sony xperia xa2
Anyway, i reported it on here because i think it's a bug, but if it's not then i will file a request for thi, because i feel video shouldn't autopause...very inconvenient...

**Comment by opusforlife2** [comment]
The video only pauses if you use the Back button to exit full screen. It does not pause if you use the Full Screen button to exit full screen instead. This is intended behaviour.
