### ISSUE TITLE
Channels Playlists on Channel Page

### ISSUE THREAD

**Issue by AnonymousSeal** [TeamNewPipe/NewPipe#7171]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

On the channel page, there should be an option to see the playlists made by the channel.

#### Additional context

Could be integrated in the three point menu or like the comments and video description, they could be shown upon swiping right or left.

#### How will you/everyone benefit from this feature?

It would be so much easier to find a Channels Playlists if they were on the channel site.

**Comment by SameenAhnaf** [comment]
Please keep the discussion in #2414.
