### ISSUE TITLE
How can I remove or make the searching in NewPipe impossible?

### ISSUE THREAD

**Issue by ichbinbusy** [TeamNewPipe/NewPipe#7185]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
(Sorry for my English)
So I have been struggling with Youtube addiction lately and would find this really helpful to be unable to search anything, but still have the ability to watch videos from my subscriptions. I can import my set up from back up file so that I would not have to search for any of these channels.

I'm completely zero in mobile programming, so couldn't figure out this myself. It's not supposed to be only removal, if it is hard to do, but if the search disfunctioning is also fine for me. It would be nice if I could do it with a deletion of some file or a line of code by myself from the instructions, because I need to update NewPipe once in a while.

**Comment by mhmdanas** [comment]
The problem with implementing this into NewPipe directly is that it would have to be a setting that can be turned on or off, which wouldn't be much of a deterrent in your case. However, I can take a bit of time soon to try to know how to remove it and then show you how to do it.

**Comment by ichbinbusy** [comment]
Yeah, I am not really in a hurry. Thanks a lot!

**Comment by mhmdanas** [comment]
So I quickly took a look, and this is actually quite easy. To disable search, open `app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java`, search for the `openSearchFragment` method, and comment out the body, like so:
```patch
From d090000b92bb221192c12e231b2e1ba0c4140d17 Mon Sep 17 00:00:00 2001
From: mhmdanas <triallax@tutanota.com>
Date: Thu, 21 Oct 2021 19:14:52 +0300
Subject: [PATCH] Disable search

---
 .../java/org/schabi/newpipe/util/NavigationHelper.java    | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java b/app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
index 1c94743d0..3169ae173 100644
--- a/app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
+++ b/app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
@@ -304,10 +304,10 @@ public final class NavigationHelper {
 
     public static void openSearchFragment(final FragmentManager fragmentManager,
                                           final int serviceId, final String searchString) {
-        defaultTransaction(fragmentManager)
-                .replace(R.id.fragment_holder, SearchFragment.getInstance(serviceId, searchString))
-                .addToBackStack(SEARCH_FRAGMENT_TAG)
-                .commit();
+//        defaultTransaction(fragmentManager)
+//                .replace(R.id.fragment_holder, SearchFragment.getInstance(serviceId, searchString))
+//                .addToBackStack(SEARCH_FRAGMENT_TAG)
+//                .commit();
     }
 
     public static void expandMainPlayer(final Context context) {
-- 
2.30.1 (Apple Git-130)
```

This doesn't actually hide the search button itself, but from your comments I think you're fine with this. However, it shouldn't be too hard to remove the button either.

Feel free to make a comment here if you have any trouble.
