### ISSUE TITLE
No stream player found

### ISSUE THREAD

**Issue by Throlo** [TeamNewPipe/NewPipe#7197]
### Checklist

- [x] I am using the latest version - 0.21.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to a video
2. Press on "Background"

### Actual behavior
A message saying "No stream player found. Install VLC?" appears

### Expected behavior
The video play in background normally

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: SMA-A515F (Galaxy A51)

**Comment by Throlo** [comment]
https://user-images.githubusercontent.com/82319992/135779926-e451377e-2f03-4d8a-83da-524f1868f5b3.mp4

**Comment by CloverBadland** [comment]
Do you have enabled `Use external audio player` from settings? If so:

Go to `Settings` > `Video and audio` > Find the `Player` section > Disable `Use external audio player`

**Comment by Throlo** [comment]
Oh. External player was enable. Sorry for the trouble
