### ISSUE TITLE
Bars on top and at the bottom of the video

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#7199]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1.Open a video in popup mode
2.Use a different app and divide the app between the screen (basically multitasking funcitonality in samsung)
3. Then expand the other app to the whole screen
4. Then go back to the app and see error

### Actual behavior

Bars around the video and no way of moving. Only when you click the expand button on popup mode does it fix.

### Expected behavior

Normal activity

### Screenshots/Screen recordings

![grafik](https://user-images.githubusercontent.com/40789489/137190634-fa061077-e823-4281-8fe4-cedf54e08aea.png)

### Device info

 - Android version/Custom ROM version: Android 7.1.1 Nougat
 - Device model: Samsung Galaxy Tab A

**Comment by Thewisem** [comment]
Check above and below the thumbnail. You see those brown bars? Yeah That's what I am talking about.

**Comment by Thewisem** [comment]
Its a comparison of how it is normally and how it shows in the issue page.

**Comment by litetex** [comment]
I hide your comments with the screenshot where there is no bug because it just distracts people.

Even in the popup player in the first picture I can't see any brown bars:
![grafik](https://user-images.githubusercontent.com/40789489/136837517-c4353587-1f7f-4d44-8e94-6d3877ce19c5.png)
![grafik](https://user-images.githubusercontent.com/40789489/136837524-4730d3d0-2ddb-44bb-b867-b65205ed7840.png)

**Comment by Thewisem** [comment]
Not popup the original place.
![1634010971218_1](https://user-images.githubusercontent.com/74511929/136889124-d982b76c-e276-491c-863a-7d0c9c22d8f0.jpg)

**Comment by Thewisem** [comment]
That is embarassing

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?
