### ISSUE TITLE
Cant download to external SD card

### ISSUE THREAD

**Issue by arthurvaverko** [TeamNewPipe/NewPipe#720]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "en",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.9.10",
   "os": "Linux Android 6.0 - 23",
   "time": "2017-09-21 04:33",
   "ip_range": "77.126.0.0",
   "exceptions": [
      "java.lang.RuntimeException: java.io.IOException: open failed: EACCES (Permission denied)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\nCaused by: java.io.IOException: open failed: EACCES (Permission denied)\n\tat java.io.File.createNewFile(File.java:939)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:334)\nCaused by: android.system.ErrnoException: open failed: EACCES (Permission denied)\n\tat libcore.io.Posix.open(Native Method)\n\tat libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)\n\tat java.io.File.createNewFile(File.java:932)\n\t... 1 more\njava.io.IOException: open failed: EACCES (Permission denied)\n\tat java.io.File.createNewFile(File.java:939)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:334)\nCaused by: android.system.ErrnoException: open failed: EACCES (Permission denied)\n\tat libcore.io.Posix.open(Native Method)\n\tat libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)\n\tat java.io.File.createNewFile(File.java:932)\n\t... 1 more\nandroid.system.ErrnoException: open failed: EACCES (Permission denied)\n\tat libcore.io.Posix.open(Native Method)\n\tat libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)\n\tat java.io.File.createNewFile(File.java:932)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:334)\n"
   ],
   "user_comment": ""
}

**Comment by arthurvaverko** [comment]
When i think about it i never got a propt to give permission to newPipe for the externalSD card...

**Comment by wb9688** [comment]
You should get a permission prompt the first time you press the download
button. If not, could you please go to Settings > Apps > NewPipe >
Permissions and enable Storage?

**Comment by arthurvaverko** [comment]
I have the storage permission turned on ..but access to external SD car is
restricted and has to be asked specifically..

android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by arthurvaverko** [comment]
Sorry i saw you added this .. But i did not have acces to external sd card

**Comment by arthurvaverko** [comment]
I mean the one you jnsert externallynot the buit in storage ..i dontreally know how but apps that need aceess to this card will requetst this access specifaclly by openning a file browser and causing the user to navigate to the external card root and click select .. I knwo this because FX file explorer did this so that write access will be allowed

**Comment by arthurvaverko** [comment]
I think the new permiasion migth be 
WRITE_MEDIA_STORAGE

**Comment by theScrabi** [comment]
Yea that is indeed a problem, I can confirm that, and we need to fix this.

**Comment by morfikov** [comment]
[I had similar issue with SimpleFIleManager](https://github.com/SimpleMobileTools/Simple-File-Manager/issues/98). And as you can see in the link, the needed permission was MANAGE_DOCUMENTS . But in this case, theere's no the extra permission. Even in the log:

```
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "en",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.10.0",
   "os": "Linux Android 7.0 - 24",
   "time": "2017-10-03 09:06",
   "ip_range": "94.254.0.0",
   "exceptions": [
      "java.lang.RuntimeException: java.io.IOException: Permission denied\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\nCaused by: java.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:334)\njava.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:334)\n"
   ],
   "user_comment": ""
}
```

But you can see that it clearly says: File.createNewFile, so maybe it also needs the MANAGE_DOCUMENTS permission?

**Comment by burbilog** [comment]
I have the same problem, latest NewPipe + LineageOS 14.1. It silently crashes if I try to download to external SD card.

**Comment by theScrabi** [comment]
@morfikov I think we simply have to request that permission then.

**Comment by spaetz** [comment]
current NewPipe (fdroid) crashes with permission denied when I select an external SD card as path. I have given NewPipe the Storage permission. This is Android 7.1.2 (lineageos).
One solution woukd be to use the new Android Storage Framework which would ask for the storage location.

**Comment by TheFireRed** [comment]
I have this issue too. Is it still in process?

**Comment by theScrabi** [comment]
Yes

**Comment by M2ck** [comment]
Same issue here on Oxygen OS v3.1.4 (Android v6.0)

**Comment by joshvro** [comment]
Sorry to resurrect an old thread, but is this still in process?

**Comment by theScrabi** [comment]
Not atm. But We have it in mind.
However a little help was nothing we said no about :)

**Comment by placidcasual98** [comment]
Yeah it still crashes when will this be fixed, this is a major flaw 
{
"user_action": "ui error",
"request": "App crash, UI failure",
"content_language": "GB",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.13.1",
"os": "Linux Android 7.1.2 - 25",
"time": "2018-04-02 21:12",
"exceptions": [
"java.lang.RuntimeException: java.io.IOException: Permission denied\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:350)\nCaused by: java.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\njava.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\n"
],
"user_comment": ""
}

**Comment by theScrabi** [comment]
We know that it's not yet working. We knwo we need to fix it.

**Comment by theScrabi** [comment]
I mark this as duplicate in favour of https://github.com/TeamNewPipe/NewPipe/issues/412
