### ISSUE TITLE
[Feature Request] App Auto-Updater

### ISSUE THREAD

**Issue by bagelcake** [TeamNewPipe/NewPipe#721]
I searched and did not find this feature request.

Pretty self-explanatory. Add an optional check for app updates during startup. Make sure it can be disabled so people don't complain.

**Comment by wb9688** [comment]
Why? F-Droid updates NewPipe already, right?

**Comment by bagelcake** [comment]
I don't have F-Droid. Recently rediscovered NewPipe through Reddit.

**Comment by theScrabi** [comment]
Yea that's where reddit might have got it wrong. The official repository is fdroid, and you should get it there. The release note has a warning embodied telling this.
