### ISSUE TITLE
Newpipe for pc /window

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#7219]
I am daily user of newpipe 

But when I switched to laptop 
I was missing newpipe . 
And I just tried to find some alternative but . They are just waste 

 It would be better if someone tell me a alternative same as newpipe for windows 10 
Or Dev will launch the newpipe for window

I am begging u please 😭 tell me a app like newpipe for windows 

Please give as much suggestions as u can

**Comment by mhmdanas** [comment]
> i am sorry about my behaviour

No worries, just try to avoid it.

> but what if it actually doesn't meet my requirement

Well, what _are_ your requirements exactly?

**Comment by mhmdanas** [comment]
Hmm, I don't use FreeTube, so I don't know if it has all of those features, so I recommend you just try it. Also give [Invidious](https://github.com/iv-org/invidious) and [Piped](https://github.com/teampiped/piped) a try if you're fine with using a web browser.

**Comment by JsRoadYT** [comment]
android emulator of your liking with newpipe on it if it's that important to you
