### ISSUE TITLE
★★★ Hit the 2000 mark ★★★

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#723]
## Hit the 2000 ★ mark this morning 
![memetastic_meme](https://user-images.githubusercontent.com/1891273/30686232-dee0c18a-9eb7-11e7-9253-20038729cde1.jpg)

A celebratable moment I think.
A huge thanks to @mauriciocolli @TheAssassin @wb9688 @TobiGr  @coffeemakr @BlenderViking, and all NewPipe contributors.

**Comment by TheAssassin** [comment]
So who's those 16 guys who put us away from 2048? Quickly, unstar the project!

![1w9192](https://user-images.githubusercontent.com/4503202/30687759-8b592f8e-9ebc-11e7-9178-336f5e8309da.jpg)

**Comment by theScrabi** [comment]
![memetastic_meme 2](https://user-images.githubusercontent.com/1891273/30690676-49994f80-9ec5-11e7-889d-d821b6f7d3e1.jpg)

**Comment by wb9688** [comment]
@TheAssassin: Or better: quick, star this project 2021 times (so that we get 4096 stars)!

**Comment by wb9688** [comment]
Hit the 3000 mark now! :tada:

**Comment by TheAssassin** [comment]
I think we need to set up some monitoring for this...

**Comment by theScrabi** [comment]
Yea totally :'D

**Comment by theScrabi** [comment]
Scary sh***

**Comment by justanidea** [comment]
Your project is snowballing :)

**Comment by theScrabi** [comment]
![bildschirmfoto vom 2018-04-08 12-34-44](https://user-images.githubusercontent.com/1891273/38466437-4787edfe-3b29-11e8-8de0-e79272552c0e.png)

**Comment by TheAssassin** [comment]
Closing as we're about to reach the 4000 mark soon. We'll open another issue then.

**Comment by varunest** [comment]
Congratulations 💯

**Comment by theScrabi** [comment]
> Closing as we're about to reach the 4000 mark soon. We'll open another issue then.

![giphy](https://user-images.githubusercontent.com/1891273/42135563-d3e7d790-7d4c-11e8-94fc-70a25de4c08f.gif)

### Soon
