### ISSUE TITLE
Não consigo importar minhas playlist, então não é possível?

### ISSUE THREAD

**Issue by Joseiltonslv** [TeamNewPipe/NewPipe#7243]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

**Comment by SameenAhnaf** [comment]
Issues are only accepted in English. Also, please fill in the template properly with a detailed description.
