### ISSUE TITLE
App crashes when playing back any content 

### ISSUE THREAD

**Issue by PieceDeResisting** [TeamNewPipe/NewPipe#7251]
My device is Lenovo M10 HD 2nd Gen.  

### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
Please fill out the template properly, or it'll be pretty hard to help you.

**Comment by danmanrana** [comment]
By playing back do you mean playing anything? I started using the latest version today and nothing played, but it might've been because I had another music app open.
