### ISSUE TITLE
Being able to open remote files

### ISSUE THREAD

**Issue by Angelk90** [TeamNewPipe/NewPipe#7256]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

To be able to open video files located on:
- http://
- mms://
- rtsp://

#### Why do you want this feature?

The possibility of being able to watch videos located on a specific address on the internet, using the application's player as a player without having to install other apps.

**Comment by litetex** [comment]
Closing this due to https://github.com/TeamNewPipe/NewPipe/issues/478#issuecomment-960959193

**Comment by opusforlife2** [comment]
> using the application's player as a player without having to install other apps.

Have a look at Just Video Player (https://f-droid.org/en/packages/com.brouken.player/), instead. It is also Exoplayer-based.
