### ISSUE TITLE
A typing error need to be corrected

### ISSUE THREAD

**Issue by trmdi** [TeamNewPipe/NewPipe#728]
https://github.com/TeamNewPipe/NewPipe/blob/51ff371083b85b0a3ddc9d5c5dd9596e5573075c/app/src/main/res/values-vi/strings.xml#L8

It should be "trình" instead of "teinhf"

@vybuivn

**Comment by wb9688** [comment]
You could fix that through our Weblate at
https://hosted.weblate.org/engage/NewPipe/.

**Comment by trmdi** [comment]
Thank you @wb9688
