### ISSUE TITLE
Target SDK 31

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#7281]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

TARGET SDK 31.

#### Why do you want this feature?

The target SDK indicates what is the highest version of Android with which the app is designed to work. Every year Android brings many privacy and security changes. Apps targeting SDK 31 (Android 12) introduce a lot of new privacy and security improvements, which are listed [here.](https://developer.android.com/about/versions/12/summary)

It would be great if Newpipe could support the latest SDK. Right know it targets SDK 29 (Android 10).

**Comment by jcperil** [comment]
Any update on this issue?

**Comment by rusty-snake** [comment]
#9306
