### ISSUE TITLE
longpress menu should display over video popup

### ISSUE THREAD

**Issue by bkqtnte10** [TeamNewPipe/NewPipe#7282]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

If a video is running in popup and another video is longpressed, that popup should be over the video popup

#### Why do you want this feature?

It is the intuitive way. When longpressing the interaction is more important than the video. The popup wont be open for long.

**Comment by Stypox** [comment]
No, this is not doable
