### ISSUE TITLE
Downloaded Videos Do Not Finish Play

### ISSUE THREAD

**Issue by caltrop2075** [TeamNewPipe/NewPipe#7283]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

download issues with YouTube

download video and then to play on PC
one video showed 1:20:34, played about 5m and quit, some videos never downloaded but showed progress

not all videos are affected, but about 75% are affected

### Actual behavior

videos either did not download or do not play completely since the latest update

### Expected behavior

video download and play

### Device info

 - Android version/Custom ROM version:
 - Device model: Android 10, Moto G7

**Comment by caltrop2075** [comment]
just found the latest release and it fixed the SHARE issue

just in time for my visit to the Library Wi-Fi


Liz 😼
Enjoy The Collapse
🤪🔥💥💀

**Comment by Feuerswut** [comment]
Is this still an iasue?

**Comment by caltrop2075** [comment]
the issue is pointless anymore
my phone BLEW UP!
