### ISSUE TITLE
Small things to do next

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#729]
Now where we finally have Playlist support (not ultimate, I know but @karyogamy is working on that) we can now also implement smaller things.

What I would like to implement/have to be impelmented:
- [x] Kiosk. Replace the blank start screen with a trending screen.
- [x] Live stream support

This would round up our current UI, and make the app more elaborate, also I think it's not that hard to implement.

**Comment by wb9688** [comment]
And what about finishing #693? I don't think it's that hard to do, but I
just don't have time for that atm and I prefer more 'backend'-ish stuff
like working at NewPipeExtractor or PipeCast.

**Comment by theScrabi** [comment]
Thats totally ok :) you don't have to do what I suggested. I just say this was something todo.
Actually on the Kiosk thing I'm working on my self atm.

**Comment by karyogamy** [comment]
> Live stream support

It might be better to push this until after play queue is done, though, as I am currently making some major changes to the core players (dynamic media source and track selections, so we can have better transition between quality switch as well as captions support).

 I agree with @wb9688, having different services injected from NewPipeExtractor and UI dynamically created on the client would make our project a lot more appealing.

**Comment by wb9688** [comment]
Yeah, and I just said that was also something to do. Btw how far are you
with that kiosk thing? I'm almost at the point I can play a video with
PipeCast through UPnP.

**Comment by theScrabi** [comment]
@karyogamy do your thing first, Live stream support is not yet even implemented in the backend. So i don't expect toe front end to support it soon.

About kiosk, i first have to get familiar with the recent changes, so it's only slowly getting forward. I'm willing to work on it tomorrow tho.

**Comment by Gitaroony** [comment]
The main reason I use newpipe and install it for anyone who wants a yt alt, is that it has minimal UI.

Please reconsider not adding a trending to start screen.  Sometimes I even install it on kids tablets, and the trending, what's hot, etc are some of the things I wish to avoid.

If you need to have something, a FAV tab to start would be a better idea, if favourites feature is ever implemented.

Thanks!

**Comment by theScrabi** [comment]
Fav as start can be selected with the next version.

**Comment by Gitaroony** [comment]
Would it be possible to add an export/import feature for all settings, favs, history and watched?

That way if one was to change phones, restore etc it can all be imported again.

Another good reason is if one wanted to install the app from here because a new version is out that fixes major bugs, but has the fdroid version installed, then we can install without worry and import all settings, etc,,, because fdroid takes so long to update ( latest version still not up).

thanks.

**Comment by theScrabi** [comment]
> latest version still not up

Thats because a build fail happend. Fixed it tho it will take a while.
+1 for Import/Export. I see it like you. One would have to create a jason based import export tool. Maybe there is also a librarie that can do that.

**Comment by 2SI3NX** [comment]
Live Stream support would be awesome to have!

**Comment by theScrabi** [comment]
Thanks to @karyogamy we have it now: https://github.com/TeamNewPipe/NewPipe/pull/1147
