### ISSUE TITLE
Resuming from saved position regression(downgraded to a previous version and it started working again)

### ISSUE THREAD

**Issue by Meandmyfurbies** [TeamNewPipe/NewPipe#7298]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1.Tap on a video
2.Watch it to a certain point
3.tap on the x button in top left of screen(in portrait mode)
4.tap on the video again

### Actual behavior

Video starts from beginning

### Expected behavior

Video resumes from point I watched to

### Device info

 - Android version/Custom ROM version: LineageOS 18.1-20210902-microG-bonito
 - Device model: Google Pixel 3A XL

**Comment by opusforlife2** [comment]
>  I am using the latest version - x.xx.x 

Please ensure the template is filled properly.
