### ISSUE TITLE
Bountisource does not accept calaim 

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#730]
Bountysource does not accept my claim, and I've seen that no one else got accepted there.
Without getting accepted from them Bountysource makes no sense right now, so I'm going to send them a mail why nothing happens.

**Comment by ahmadudin** [comment]
Yeah, me too. Its been a month already and still no response from bountysource.

**Comment by wb9688** [comment]
@ahmadudin: But you aren't an official member of Team NewPipe.

**Comment by ahmadudin** [comment]
Im not. I just wanna share the issue.

**Comment by TobiGr** [comment]
@theScrabi Any progress on this? We'd like to publish the donation page.

**Comment by theScrabi** [comment]
No ... I wrote them a Mail. They don't respond.
I'm not sure about bounty source anymore. I've claimed multiple times, send them mails, they don't respond.
Quite Infuriating.

**Comment by wb9688** [comment]
@theScrabi: Yeah, especially since they say they'd process it within 2
business days. Their GitHub doesn't look very active either. Are there any
good alternatives for Bountysource?

**Comment by theScrabi** [comment]
I know you can self host something like that @TheAssasine. What do you think, any Ideas
