### ISSUE TITLE
"Start in full screen" bug: Switching audio -> main player causes "unrecoverable error" on rotation

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#7302]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Turn on the "Start main player in fullscreen" toggle.
2. Set "Autoplay" to Never.
3. Open any video details in portrait mode.
4. Start background playback.
5. Tap on the thumbnail to switch to the main player.

### Actual behavior

Newpipe rotates to landscape. The thumbnail keeps showing. After a short gap, the "Unrecoverable player error occurred" toast shows up. Nothing else happens.

If you tap on the thumbnail again, then the main player opens normally, resuming playback at the correct timestamp.

### Expected behavior

The main player should start properly, without any error.

### Device info

 - Android version/Custom ROM version: LOS 17.1
 - Device model: Mi 5

**Comment by AudricV** [comment]
Is it still an issue on the `dev` branch, especially since the player refactor PR?

**Comment by opusforlife2** [comment]
It's not even occurring on 0.23.1, actually! 🎉
