### ISSUE TITLE
Main -> audio -> main OR Audio -> main -> audio: either causes playback to restart

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#7303]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play any stream in the background.
2. After a while, switch to the main player.
3. After a while, switch back to background.

OR

1. Play any stream in the main player.
2. After a while, switch to background.
3. After a while, switch back to the main player. 

### Actual behavior

At step 3 in either case, the playback restarts from the beginning.

### Expected behavior

The playback should resume from whatever timestamp was reached in the other player, no matter how many times the player type is switched.

### Device info

 - Android version/Custom ROM version: LOS 17.1
 - Device model: Mi 5

**Comment by Wouter997** [comment]
Same issue here with latest version.

**Comment by jus78help** [comment]
> Duplicate of #6472.

Now that issue is closed in favor of this one. I am also facing the same issues 0.21.13 on Android 9.

**Comment by Flam3z** [comment]
Had this issue for a couple versions now.

Android 11

**Comment by mycosavant** [comment]
This issue persists in the latest version - 0.21.14

Switch from main player to background and back will restart play from where it was when minimized or, in my case, mostly when the screen is locked. 

This happens even if I'm on other videos through auto-queue or use the "play all" in playlist; the player will revert to whatever video was playing at the time the app was minimized to background

**Comment by litetex** [comment]
Closing this issue in favor of #7427
