### ISSUE TITLE
Trending page shows duplicate videos

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [TeamNewPipe/NewPipe#7314]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Scroll through the trending page and notice duplicate videos.

### Actual behavior

The trending page shows duplicates instead of other videos. This isn't a Newpipe issue because it also occurs on FreeTube. YouTube probably changed something on their end. See https://github.com/FreeTubeApp/FreeTube/issues/1858

### Expected behavior

Dont show duplicates.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/73130443/139096228-e2795518-7e86-4877-b278-0fd680f46259.mp4

### Logs

None.

### Device info

 - Android version/Custom ROM version: Android 12 Graphene OS
 - Device model: Pixel 3a XL

**Comment by AudricV** [comment]
Fixed with TeamNewPipe/NewPipeExtractor#920.
