### ISSUE TITLE
Option to change pitch by semitones

### ISSUE THREAD

**Issue by haklc** [TeamNewPipe/NewPipe#7322]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

NewPipe currently allows for changes of pitch using percentages. This works fine for generally increasing or decreasing the frequency but doesn't really have a practical application.

I'd like to add the option of changing the pitch by [semitones](https://en.wikipedia.org/wiki/Semitone) which will allow for instant [transposition](https://en.wikipedia.org/wiki/Transposition_(music)) of a song into any key. The range of semitones could range from -12 (effectively splitting the frequency) to +12 (doubling the frequency).

A practical way of switching between percentages and semitones will be to add a toggle to Settings -> Video and audio.

#### Why do you want this feature?

This will allow for instant change of key which will make it very practical for musicians playing or singing along to backing tracks which can be found on YouTube or wanting to transcribe (learn a song by ear) in a key different from the original.

By selecting i.e. +2 you will be able to change the key of a song from C major to D major. By selecting -3 the key will change to A major. By selecting -12 the song will still be in the same key but will sound an octave lower.

**Comment by litetex** [comment]
> This works fine for generally increasing or decreasing the frequency but doesn't really have a practical application.

If you play a video at e.g. x3 you can "pitch it" a bit down so that it sounds better.


I don't think that this is practicable implementable into NewPipe:
1. The feature purely refers to songs - No idea how this should work/behave with "normal "videos
2. I don't know if it's even possible to detect and change semitones with ExoPlayer and the current included stuff.
3. I don't think a lot of people will use this in total.

**Comment by haklc** [comment]
I understand the way the way pitching is currently used, with the most useful use case being leaving it at 100% so that the sound is least distorted. But changing it to any other value besides 100% has limited use (except using it as the [Chipmunk](https://en.wikipedia.org/wiki/Alvin_and_the_Chipmunks#Recording_technique) effect or Darth Vader voice).
Raw percentages are quite hard to comprehend when it comes to (hearing) changes in frequency, but semitones are very natural for us humans to understand. That's why semitones are used in all types of Western music and instruments are built with them in mind, and not just percent-values.

1. With _normal_ videos not much would change since non-musical content is not sensitive to being slightly out of tune compared to the original. The suggested feature would of course be optional, so all existing use would remain intact. Even while using this feature, selecting 0 semitones would be the equivalent to currently selecting 100% so I don't see this as a real issue.
2. I have tried and succeeded with making this work without using any external libraries.
3. I know quite a few people who would be willing to use NewPipe just because of this added feature:
- all singers that do not share their voice range with that of the singer in a particular recording
- all improvisers when they wish to play with the abundance of backing tracks found on YouTube in a different key
- guitarists who previously had to use a capo or tune down to learn or play along to a song
- other instrumentalists who have instruments that are locked to just one or couple of the 12 possible tunings

I will go on with implementing all the necessary adjustments and will keep this post updated with the progress since I didn't encounter any major issues so far. I would also like to get comments from other contributors.

**Comment by lukatavcer** [comment]
I would also find this feature very useful.

**Comment by opusforlife2** [comment]
Changing the pitch by semitones seems way more logical than an arbitrary percentage slider. This has actual meaning behind it.

I would argue let's remove the percentage slider completely in favour of this.

**Comment by haklc** [comment]
Thanks for the support!

I think the percentage slider can still be useful when the audio is slightly out of tune (less than a semitone). It might be better to make semitones the default option while still enabling to switch to percentages when needed, the same way you can switch to semitones in the currently submitted code. I do think "unhooking" should also be on by default too.
