### ISSUE TITLE
Add in-built Equalizer

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#7325]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Add an in-built equalizer in the app, probably in App Settings

#### Why do you want this feature?

Currently Using PowerAmp Equalizer but having an in-built equalizer will be nice

**Comment by nikhilCad** [comment]
I originally wanted this feature because lowest volume in my phone was too loud. If anyone wo has Stock Android 10 stumbles on this thread an has same issue, go to Sound > Other Sound and Vibrations > Sound Enhancement and turn it off. The voice will be lowered

**Comment by opusforlife2** [comment]
@nikhilCad Have you read about XY problems? https://en.wikipedia.org/wiki/XY_problem
