### ISSUE TITLE
It is not possible to import subscriptions

### ISSUE THREAD

**Issue by NilsIrl** [TeamNewPipe/NewPipe#7326]
### Checklist

- [x] I am using the latest version - 0.21.13
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Export subscription list
2. Attempt to import it (the json file will not be selectable)

### Actual behavior

When attempting to select the file, it is not selectable.

### Expected behavior

It is possible to select the file.

### Screenshots/Screen recordings

File is grayed out and not selectable:

![Screenshot_20211029-142638_Files](https://user-images.githubusercontent.com/26231126/139443431-1f3be59f-4479-4d19-b8c1-117f4d7e3c3a.jpg)

The cause for this is the fact Android doesn't support the JSON mime type.

See: https://github.com/TeamNewPipe/NewPipe/pull/6820#issuecomment-951817661

On SM-N9500, Android 9

**Comment by Ammako** [comment]
It works totally fine here, so you might want to provide more information about your phone and OS to help figure out where the incompatibility might come from.

**Comment by GaryMericano** [comment]
Ammako when you say it works fine for you, did you try with a fresh export from YouTube/Google? I exported 3 different accounts this week and they all come with a .json inside a folder inside a folder inside of a .zip. newpipe accepts subscription imports from csv files or .zip files containing .csv files.
Unless you were using an older subscription export or Google is formatting exports different for different people, this function is currently broken.

**Comment by GaryMericano** [comment]
Disregard, I just exported one of those 3 accounts and got a zip with a csv file.... Google apparently changed export to Json for a few days? In the export menu the only aspect of YouTube that has multiple formats selectable is history which allows you to select between HTML and Json, subscriptions has csv only with no other option  I'm not sure how it was last week.....

**Comment by s6o1lu** [comment]
Google has removed the ability export subscriptions as a JSON file. Exports are now only possible as CSV files. Need a NewPipe enhancement which allows the ability to import CSV files.

**Comment by opusforlife2** [comment]
@GaryMericano @s6o1lu Newpipe already has the ability to handle Google Takeout exports of Youtube subscriptions.

**Comment by CebolaBros64** [comment]
I'm running into the same issue described by OP. Phone is a TCL L9 (5159J), running Android 8.1.0.
Unlike OP however, the workaround of appending ``(1)`` to the file extension doesn't seem to affect anything.
![photo_2021-11-12_15-15-34](https://user-images.githubusercontent.com/15020325/141515315-1cb24428-7d76-4ae2-b92e-4f000b0dfab2.jpg)
![photo_2021-11-12_15-22-39](https://user-images.githubusercontent.com/15020325/141516110-87ef73c1-970c-4a7f-bf16-8c34619f87a6.jpg)

**Comment by Ammako** [comment]
Looks like the same file picker/file manager, any idea which one it is? Stock or custom OS?

**Comment by CebolaBros64** [comment]
Stock OS. As for the file picker, it's the default one used by the OS; I can't seem to find an option to use a file manager of my choice (it's usually by the sandwich sidebar, but not on this case).

**Comment by opusforlife2** [comment]
> I can't seem to find an option to use a file manager of my choice

@CebolaBros64 Try this: https://f-droid.org/packages/me.zhanghai.android.files/

**Comment by fohfuu** [comment]
Chipping in to say that it WILL let me select the csv file, but crashes unexpectedly if I try:

Import from > YouTube > Import > select subscriptions.csv > OK

App crashes, no subscriptions were imported.

Sometimes it displays the error when after re-opening:

`## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@a2126b with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{31907a9 12954:org.schabi.newpipe/u0a260} (pid=12954, uid=10260) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{31907a9 12954:org.schabi.newpipe/u0a260} (pid=12954, uid=10260) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5728)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6820)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2935)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
	... 8 more

```
</details>
<hr>
`

**Comment by CebolaBros64** [comment]
> Try this: https://f-droid.org/packages/me.zhanghai.android.files/

@opusforlife2 This worked, I was able to choose Material Files as the file picker. There, the .json files were selectable and I was able to import my subscriptions just fine.

**Comment by opusforlife2** [comment]
@NilsIrl Could you try this app as well?

**Comment by NilsIrl** [comment]
It works, but I don't know if using a different files app can be considered a good workaround, not that there is one that is available.

**Comment by opusforlife2** [comment]
> I don't know if using a different files app can be considered a good workaround

Best you can get in this situation, since this is a bug in your OS, and not in Newpipe, as several others have tested it and it works.

Thanks for confirming!

**Comment by EvilGremlin** [comment]
> > Try this: https://f-droid.org/packages/me.zhanghai.android.files/
> 
> @opusforlife2 This worked, I was able to choose Material Files as the file picker. There, the .json files were selectable and I was able to import my subscriptions just fine.

Still very much an issue. Changing file manager doesn't work for me at all, and all file managers works fine for other apps. Maybe remove extension filter?

**Comment by opusforlife2** [comment]
@EvilGremlin How is it possible that the import accepts ZIPs for you? It's supposed to accept _only_ JSON. Are you importing from Contents settings instead of the Subscriptions tab?

**Comment by EvilGremlin** [comment]
Yes, from settings, where else? There's nothing in subs tab after first import.

**Comment by opusforlife2** [comment]
> There's nothing in subs tab after initial import.

@EvilGremlin You can tap the `Subscriptions` header with the arrow next to it to open a drop down menu of Import/Export options.

@TeamNewPipe/appdev 

Guys we have quite a UI problem here. It's not obvious that the header can be expanded if you don't already know that. It probably looks like there is a header with an arrow saying "look, here are your subscriptions right below, go click on them".

**Comment by EvilGremlin** [comment]
Wow that's horrible UI design... How could i know that other than by accidental tap? Which didn't happen in 2 years of me using it. And arrow icon clearly looks like it's for list collapse, which i have no reason to do ever.

**Comment by litetex** [comment]
> Guys we have quite a UI problem here. It's not obvious that the header can be expanded if you don't already know that. It probably looks like there is a header with an arrow saying "look, here are your subscriptions right below, go click on them".

Well then please create a new issue - preferably with a screenshot. This issue is closed.
Thx.
