### ISSUE TITLE
Still accidentaly swiping items from history

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#733]
I still accidentally swipe items away from the history page. Now i know this is why the snack bar exists tho its still undoubtingliy annoying. It's just not good to have the items remove, and switch page swipe in the same direction.

We really should make items selectable there and not make them swipable.

**Comment by 2SI3NX** [comment]
true. agreed!

**Comment by theScrabi** [comment]
Fixed tho.
