### ISSUE TITLE
Native SponsorBlock Support

### ISSUE THREAD

**Issue by cebeyip876** [TeamNewPipe/NewPipe#7332]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
 sponsorblock (the popular Browser addon)

#### Why do you want this feature?
 Blocking sponsors and other uneccesary filler content

**Comment by Geeyun-JY3** [comment]
Use https://github.com/polymorphicshade/NewPipe

**Comment by SameenAhnaf** [comment]
See: https://github.com/TeamNewPipe/NewPipe/pull/3205
