### ISSUE TITLE
Add animation when opening more features (Share, etc.) on comment page

### ISSUE THREAD

**Issue by d4f5409d** [TeamNewPipe/NewPipe#7334]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

When clicking on the dropdown menu to share the video --> ![Screenshot_20211101-092117.jpg](https://user-images.githubusercontent.com/76624594/139642680-cf9771ab-91a0-4c0b-a74d-4000b3c4919c.jpg)

#### Why do you want this feature?

Because the UI could become more smooth :)

**Comment by mhmdanas** [comment]
Please fill the template properly. As of now, it's not clear to me what kind of animation you are proposing exactly, and what the benefits are.
