### ISSUE TITLE
Android TV doesn't support importing files

### ISSUE THREAD

**Issue by Navixer** [TeamNewPipe/NewPipe#7336]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Use Android TV 9 operating system. (Xiaomi Mi Box S)
Go to Import from Youtube
Click on Import file to import a .csv file.

### Actual behavior

After clicking on import file it will say "You don't have an app that can do this"
Android TV doesn't have a file picker app. Sideloading android 9's "com.android.documentsui" didn't help. Maybe there is a version that works but I couldn't find it.

### Expected behavior

Clicking on import file button should bring up file picker but there is none. Being able to use a link to provide the csv file can help.

### Device info

 - Android version/Custom ROM version: 9
 - Device model: Mi Box S

**Comment by mhmdanas** [comment]
Can you see if https://f-droid.org/packages/me.zhanghai.android.files works? In any case, I think disabling SAF should also work, though I can't remember where you can do that from the settings.

**Comment by Navixer** [comment]
It turns out it doesn't have to be the official documents app. It worked flawlessly! Thank you so much.
