### ISSUE TITLE
Please add that when i slow the video and i download it download with the slowness

### ISSUE THREAD

**Issue by Danielking132** [TeamNewPipe/NewPipe#7337]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment]
Did you mean "Show Download Speed" feature? Also, please give a detailed description by filling the description properly. Devs are unable to help with such a little amount of information.

**Comment by Survingo** [comment]
I think OP's feature request is the ability to download video with a custom tempo and pitch, which would make it a duplicate of #7129.

Please correct me if I am wrong

**Comment by opusforlife2** [comment]
Please fill the template properly.
