### ISSUE TITLE
Seem less video while maximising video/popup

### ISSUE THREAD

**Issue by Murkur** [TeamNewPipe/NewPipe#734]
Would help with the seem less experience if the video didn't freeze while switch between popup and regular.

Also enabling popup with picture in picture would be cool using the PIP keycode 171

More of an enchantment love the app

**Comment by nimosu** [comment]
Found this before opening new issue. Would be awesome.

**Comment by Murkur** [comment]
oh my this is old dont even own a phone anymore. but yes others seem to want it so why not

**Comment by Stypox** [comment]
#2863
