### ISSUE TITLE
Need a NewPipe update which allows the ability to import CSV files for subscriptions.

### ISSUE THREAD

**Issue by s6o1lu** [TeamNewPipe/NewPipe#7342]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Google has removed the ability export subscriptions as a JSON file. Exports are now only possible as CSV files. Need a NewPipe enhancement which allows the ability to import CSV files.

### Device info

This issue is not device specific.

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/7326#issuecomment-956389667
