### ISSUE TITLE
More default settings

### ISSUE THREAD

**Issue by Metaception** [TeamNewPipe/NewPipe#735]
Similar to how you can define the default video quality, it would be useful to define default values for other settings.
Particularly, the orientation and playback speed are settings I am interested in.

These two options have dedicated buttons on the playback screen, just like the video quality, so you should still be able to adjust them if the default values do not suffice.

Anyways, Newpipe is a great piece of software!
Also, [newpipe.schabi.org/donate/](https://newpipe.schabi.org/donate/) leads to a 404

**Comment by wilfriedroset** [comment]
Agreed. And this even more needed since recent change when there is no quick access to x2 playback speed. I use to need 3 click to get to x2 (display control, display playback speed, select x2), now I need a lot of them (display control, display playback speed, slider or + button multiple time).

**Comment by markifi** [comment]
Don't close it! Skip silence, timescale speed

**Comment by theScrabi** [comment]
in my opinion having to much settings is not a god design. I would rather want to remember certain configurations rather then overbloading the settings ui.

**Comment by markifi** [comment]
That's fair. Is it possible to do this in a hidden config file edit? All I'm looking for is default speed, skip silence. That's my main reason for using your app, it works rather well.

**Comment by bill-mcgonigle** [comment]
FWIW I'm not currently using the app because I listen to everything at 1.5 and it's too much hassle to do it for every video.  I'm subscribed to this issue so I can know when to switch over (if ever?).

**Comment by nikolayhg** [comment]
+1

**Comment by syene** [comment]
Totally, I would prefer setting my default speed at something greater than 1 as well; and it would be such a timesaver.

I've almost memorised the routine of adjusting the playback speed as I open videos. Those 3-5 seconds definitely add up with how much some of us consume yt now that I think, and it would definitely be an upgrade if the app would let us set a default playback speed.

As for a setting for default orientation, I don't personally find a need for that; the app remembers the last setting and that's works for me.

The app using our last set playback speed for subsequent videos, however, won't work as well: I like the idea of setting something like 1.75x as my default (it would work with the majority of videos) and then adjusting it slightly either ways as the need arises (for the select few where they're going too slow or fast). And I feel this would be the most convenient and least intrusive implementation for all... 

+1 from me.

**Comment by Korayem** [comment]
no need to add options to set default values, just store whatever i chose previously and keep it so
* playback speed
* pitch
* unlink speed and pitch
* skip silence

problem solved

**Comment by 532910** [comment]
As I said before there must be an option to save or not 
previously selected values. Like VLC does.

**Comment by XiangRongLin** [comment]
I have an PR open for this but there was another suggestions in the PR. If anyone is still subscribed here, they could add their opinion in the PR.
https://github.com/TeamNewPipe/NewPipe/pull/3288#issuecomment-605813481

**Comment by Stypox** [comment]
Closed by #3288
