### ISSUE TITLE
Unable to download video only

### ISSUE THREAD

**Issue by Zhorschi** [TeamNewPipe/NewPipe#7359]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'youtube video'
2. Press on 'download'
3. Select "Video"
4. Press on "OK"

### Actual behavior

When i tap download, it says: Error, The file cannot be created
Audio is completely fine

### Expected behavior

When i tap download it should download the video

### Device info

 - Android version/Custom ROM version: Android 10; EMUI 11.0.0
 - Device model: LYA-L29
![Screenshot_20211104_160730_org schabi newpipe](https://user-images.githubusercontent.com/93709706/140339846-f89945c3-b03b-49c9-8168-c9c1396e8a58.jpg)
:

**Comment by litetex** [comment]
We need more information here:
* Is the storage maybe full?
* What video is affected/was downloaded?
* What options have been chosen for the download? (e.g. mp4, 720p, etc)

Also logs would be **extremely** helpful as they likely indicate what kind of error happened.
Could you download the latest development build (from https://github.com/TeamNewPipe/NewPipe/actions/runs/1421981541) and collect logs using logcat?

**Comment by opusforlife2** [comment]
Can a standard Newpipe error report be generated from this kind of error?

**Comment by Zhorschi** [comment]
The storage wasn't full, any Video that i Trier didn't Work and any Video Options like mp4, 420p either.

**Comment by opusforlife2** [comment]
Can you check if your video download folder is set correctly? Either way, try setting it again?

**Comment by Zhorschi** [comment]
It works now. The Filder wasn't Set correctly.

**Comment by opusforlife2** [comment]
Okay, thanks! Closing as answered.
