### ISSUE TITLE
[Feed] "Show watched items" not saved

### ISSUE THREAD

**Issue by Fassi96** [TeamNewPipe/NewPipe#7362]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Subscriptions'
2. Press on 'All'
3. Press on 'Show watched items'
4. Close the app
5. Open the app
6. Go to 'Subscriptions'
7. Press on 'All'

### Actual behavior

The setting to show items that have already been watched or not is not saved when the app is closed.

### Expected behavior

The setting that elements that have already been watched are displayed or not should be saved even after closing the app.

### Screenshots/Screen recordings

Link to Video: https://netherghast-my.sharepoint.com/:v:/g/personal/matthias_hanisch_netherghast_de/EWP_Xrcy6CBGoAEiDa1EhjIBO1Qx-jKKVQ6_YBV-jv-ceQ?e=2gfZhA

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung Galaxy Note20 Ultra 5G (SM-N986B/DS)

**Comment by SameenAhnaf** [comment]
Check the APK in #6895.

**Comment by SameenAhnaf** [comment]
You can already do that with the marked button. Make sure to enable `Watch History` from `Settings` to use `Remove Watched` feature.

![IMG_20211105_064156](https://user-images.githubusercontent.com/79245641/140439659-158168e0-07a4-4de1-8936-c8ce118bef30.jpg)

**Comment by mhmdanas** [comment]
@SameenAhnaf the issue author knows about that; they're just saying that it's not saved.

**Comment by litetex** [comment]
Changed the title to make it more understandable what is meant.

**Comment by iambaji** [comment]
hi, I made some changes that should fix this issue, please check this out, let me know if I should update anything at all. thanks.

**Comment by Fassi96** [comment]
Unfortunately, nothing has changed in terms of behavior.

**Comment by Fassi96** [comment]
Will the fix already be included in the next update? 

And thanks for the quick help :)

**Comment by iambaji** [comment]
thanks for testing. not sure about when this will be added, I am new to this project and  it is still an open pr.

**Comment by litetex** [comment]
> Will the fix already be included in the next update?

If the devs merge it in time into the dev-branch - yes.
This will likely be the case as there are only minor code changes (<10 lines of code affected).

**Comment by Fassi96** [comment]
> thanks for testing. not sure about when this will be added, I am new to this project and it is still an open pr.

Hey iambaji,
unfortunately, today I encountered a problem with your fix.  The setting remains saved, but the implementation (i.e. the removal of the elements that have already been seen) only takes place after deactivating and then reactivating the option.

Here is a link to a screen video showing the problem:
https://netherghast-my.sharepoint.com/:v:/g/personal/matthias_hanisch_netherghast_de/EXbxkbqNWL5BrP-Yvt_MTEoBvCdlyhElny2o2SX3F75nvA?e=REilcM

**Comment by litetex** [comment]
@Fassi96 
Should be fixed now.

**Comment by iambaji** [comment]
good catch @Fassi96, how could I miss that! thanks for the fix and refactoring @litetex . your wording makes better sense :)
