### ISSUE TITLE
Weblate does have enough characters to translate string

### ISSUE THREAD

**Issue by AlexN1997** [TeamNewPipe/NewPipe#7366]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
As the title, Weblate does have enough characters to translate the whole string.
For Example, the original text has about 1800 characters, but the translated text is limited to 500 characters... (see image lower right corner)

#### Additional context

![afbeelding](https://user-images.githubusercontent.com/76731207/140614851-b4be6a9f-7f75-4814-bea5-02217dc8c6f4.png)

**Comment by mhmdanas** [comment]
That's an old release changelog; you don't have to (nor are you supposed to) translate it any more. Now we make all new changelogs 500 characters long or below (by the way, the 500 character limit comes from F-Droid).
