### ISSUE TITLE
Blurry Thumbnails

### ISSUE THREAD

**Issue by Monstanner** [TeamNewPipe/NewPipe#7371]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Is it normal that some thumbnails are blurry? I have attached two pictures. So for me there's nothing bad about the thumbnail.

#### Additional context

Blurry Thumbnail in Search result list

![Screenshot_20211108-055950_1_1](https://user-images.githubusercontent.com/45621250/140687458-ce0c197e-fb31-44e1-b0dd-d874ada36776.png)

Normal Thumbnail when I open the Video

![Screenshot_20211108-055957_1](https://user-images.githubusercontent.com/45621250/140687730-a9918028-09da-4c66-b39e-402b6e98c440.png)

This happens only rarely. Nevertheless, I wanted to know if this is normal. Because in the release notes nothing of this "feature" is written.

**Comment by litetex** [comment]
The thumbnail is blurred because the video is age-restricted.

**Comment by Monstanner** [comment]
> The thumbnail is blurred because the video is age-restricted.

Ah ok. I didn't know. Thanks for the reply.

**Comment by litetex** [comment]
> Ah ok. I didn't know. Thanks for the reply.

No problem.
I think YT introduced this just recently. That's why I also didn't notice it before.
