### ISSUE TITLE
Show subtitles in video's details tab

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#7373]
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.   
i searched, but didnt find any exact match: 🔍 [show subtitles](https://github.com/teamnewpipe/newpipe/issues?q=is%3Aissue+is%3Aopen+show+subtitles)  
However, there was a ~~tangentially related~~ subset issue: #6661
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

The available subtitles in the videos can be displayed in the video details tab.

#### Why do you want this feature?

Limitation faced: Currently, there is no option to read the subtitles continuously. This is very crucial many times, like:
- for reading lyrics (the mentioned issue above)
- for reading the course content
- for skimming through video
- when watching/listening video/audio is prohibited

#### References
  - Youtube : [sample🡭][yt]
- Khan Academy : [sample🡭][ka]
- Linked Course videos : [sample🡭][li]

[yt]: https://www.youtube.com/watch?v=bqHNpNLa7ew
[ka]: https://www.khanacademy.org/math/statistics-probability/probability-library/basic-set-ops/v/intersection-and-union-of-sets

[li]: https://www.linkedin.com/learning/autocad-mechanical-essential-training-3

<img src="https://user-images.githubusercontent.com/19423063/140698483-d28e71e4-bfe0-452f-b03d-a7e3bee13eca.png" height="270px">
<img src="https://user-images.githubusercontent.com/19423063/140697711-ab96760c-6844-48e9-bbcb-f791de46dfe0.png" height="200px">
<img src="https://user-images.githubusercontent.com/19423063/140699254-6b20f384-ac59-4498-8e83-9adaf8e17ce3.png" height="300px">

**Comment by litetex** [comment]
> ![pic](https://user-images.githubusercontent.com/19423063/140698483-d28e71e4-bfe0-452f-b03d-a7e3bee13eca.png)

3 dialogs overlay each other... I think that is very bad UX and won't work well on Android devices.
However there are definitely alternatives available :)

**Comment by yashpalgoyal1304** [comment]
@litetex hmm?? that image i posted above is composed of two different images 😅 the left overlay (the **open transcript** one - sky bluish color) is seperate, and the right one "Toggle timestamps" - red one is separate.

and this image i didnt post as the direct reference to be took inspiration from, it was just to put different options for easy access.

**Comment by yashpalgoyal1304** [comment]
moved over to #7375
