### ISSUE TITLE
Show chapters in video details

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#7374]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
🔍 [show chapters in video details ](https://github.com/teamnewpipe/newpipe/issues?q=is%3Aissue+show+chapters+in+video+details)
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Showing chapters in video details page can be helpful

#### Why do you want this feature?

mainly, this feature request is like a part of the request i will open next. this feature request on it's own doesnt make much sense i guess 😅 , but combined with that feature request #7375 i guess this will be nice to have

**Comment by mhmdanas** [comment]
Do note that unless a video uses automatic video chapters (see (see https://support.google.com/youtube/answer/9884579?hl=en), you can just open the description, since that's where the video's chapters are taken from. If I'm misunderstanding your request do make a comment.

**Comment by yashpalgoyal1304** [comment]
moved over to #7375
