### ISSUE TITLE
Background playbacks resume isn't working

### ISSUE THREAD

**Issue by RickyM7** [TeamNewPipe/NewPipe#7380]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Just pause a playing video and the bug occurs (but that only happens sometimes).

This bug occurs when you start another video/music in another app and NewPipe pause, or when you pause the NewPipe by the statusbar, or even when it pauses a reproduction within the NewPipe itself. This always in background reproductions because I have never had this problem with reproductions in the foreground (videos).

### Actual behavior
The video/music does not play again after clicking the play/pause button. You have to close the current playback and start a new one for the video to play again.

### Device info

 - Android version/Custom ROM version: Android 11.0 (ArrowOs 11)
 - Device model: Redmi Note 4

**Comment by RickyM7** [comment]
The bug no longer occurred after I reinstalled the rom. If it happens again I'll reopen the issue.

**Comment by eternal-sorrow** [comment]
This happens for me too.
