### ISSUE TITLE
Sound is completely gone after using app for some time

### ISSUE THREAD

**Issue by Jazun** [TeamNewPipe/NewPipe#7382]
### Checklist

- [x] I am using the latest version - v0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Use the app? It's not exactly known how it happens and I don't even know if there's a way to fix it, all I would usually do is listen to random stuff overnight with newpipe in the background and usually when I woke up in the morning it'd be paused, presumably ended. I'm pretty sure that when I went to use the app the night after, the bug would occur.

### Actual behavior

The sound breaks and I'm unable to hear anything, all videos I select are silent (but still do play) and I've tried everything from an app restart to force stopping it and re-opening it again. I've tried clearing cache and app data, nothing changes.
The only thing that has worked is reinstalling the app, but I'm not doing that every single time I want to listen to something the day after.
Note that this has been happening across multiple versions, and only now am I speaking about it.

### Expected behavior

There should be sound that play along with the videos and it would work completely fine.

### Device info

 - Android version: 10
 - Device model: SM-J600FN

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?

**Comment by Jazun** [comment]
You're a bit late. No, this is no longer an issue.
