### ISSUE TITLE
Feature request: Option to remove watched videos from feed 

### ISSUE THREAD

**Issue by Broeckelmann** [TeamNewPipe/NewPipe#7383]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I would like to have an option to remove watched videos from the subscriptions feed, like it happens in FreeTube.

#### Why do you want this feature?

Because it makes the subscription feed much cleaner.

**Comment by litetex** [comment]
What is "subscription feed"?

The normal feed (and also subscription groups) contain a button on the top left which says "Show/Hide watched items":
![grafik](https://user-images.githubusercontent.com/40789489/140991313-f454d983-9de9-4f21-ba5a-e0dcb7a4bd7e.png)

**Comment by Broeckelmann** [comment]
Oh, wow never saw that before 😄.
Sorry for opening this and yeah that is what I meant 😅.
