### ISSUE TITLE
Downloads do not automatically start

### ISSUE THREAD

**Issue by mgood7123** [TeamNewPipe/NewPipe#7387]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Try to download audio (or video)

### Actual behavior

The download does not start automatically

### Expected behavior

The download starts automatically

### Screenshots/Screen recordings

https://imgur.com/a/tsk37Jw

https://imgur.com/a/PRScAxK

### Logs

I don't know how to get one without laptop

### Device info

 - Android version/Custom ROM version: Lineage OS 9
 - Device model: Samsung Galaxy S8

This happens on other ROMs including the stock official rom

**Comment by H4XKER** [comment]
Same here the download will always in queue and i need to manually start it. Its annoying

**Comment by Ammako** [comment]
By any chance, is your network connection metered?

**Comment by mgood7123** [comment]
> By any chance, is your network connection metered?

no, it is unmetered

**Comment by opusforlife2** [comment]
@mgood7123 Wi-fi or mobile data?

**Comment by mgood7123** [comment]
> @mgood7123 Wi-fi or mobile data?

Wi-fi

**Comment by opusforlife2** [comment]
@mgood7123 Which OS has data saver for wifi?

**Comment by mgood7123** [comment]
AOSP and Samsung

AOSP specifically has Battery Saver

Both AOSP and Samsung have Battery Restriction and Optimization settings
that further affect background activity

**Comment by mgood7123** [comment]
And AOSP specifically has data saver

**Comment by opusforlife2** [comment]
@mgood7123 But you said your network connection is unmetered? If you have Data Saver turned on, doesn't that mean the connection is metered?

Either way, does turning it off make downloads work as expected for you?

**Comment by mgood7123** [comment]
I think data saver/battery saver prevents internet usage while the app is
in background

**Comment by mgood7123** [comment]
And data saver can be turned on regardless of if the connection is metered
or not

**Comment by mgood7123** [comment]
On Samsung, the default settings are

Allow background activity - Off

Optimize Battery Usage - (Optimized)


This causes NewPipe to stop downloads when the app is closed (dismissed
from recents screen)

And NewPipe shows no notifications to indicate downloading anything

It creates the video however it is corrupted

If you turn background activity to

Allow background activity - On

Then it allows background downloading

And NewPipe works as expected

**Comment by opusforlife2** [comment]
Then isn't everything working as expected? If you try to download in the background, Newpipe would need to be able to consume battery in the background, for which it needs the permission.

**Comment by mgood7123** [comment]
> Then isn't everything working as expected? If you try to download in the background, Newpipe would need to be able to consume battery in the background, for which it needs the permission.

yea, it should notify the user about this by default whenever they open the app

**Comment by opusforlife2** [comment]
@mgood7123 Then please open a new issue asking for that, since it is an enhancement. I'm closing this one.
