### ISSUE TITLE
Repeating channel content

### ISSUE THREAD

**Issue by M1N0RM1N3R** [TeamNewPipe/NewPipe#7388]
### Checklist

- [x] I am using the latest version - v0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Pick a channel, any channel. Open its channel page.
2. Start scrolling through the channel page. After about 50-70 items, the list will start to repeat itself.

### Actual behavior

Channel content repeats itself after a few tens of videos. 

### Expected behavior

Channel content should continue to load as it would on the YT app.

### Device info

 - Android version/Custom ROM version: Samsung One UI 3.1 (Android 11)
 - Device model: Galaxy A32 5G (model number SM-A326U)

**Comment by AudricV** [comment]
Is it still an issue on 0.26.1?
