### ISSUE TITLE
Cropped video in full screen

### ISSUE THREAD

**Issue by stemy2** [TeamNewPipe/NewPipe#7389]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to some video
2. Play it in fullscreen

### Actual behavior

Video are cropped in fullscreen mode, no matter the resolution.

### Expected behavior

Video not cropped

### Screenshots/Screen recordings

![Screenshot_20211110-074427_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/22192600/141064132-50c145fb-0d21-412a-af22-a9a2b43d1d23.png)
The strange white dots at the bottom are supposed to be forced subtitles.

### Device info

 - Android version/Custom ROM version: 8.1
 - Device model: Galaxy S7

**Comment by litetex** [comment]
> 1. Go to some video
> 2. Play it in fullscreen

Works as expected on my device.

What version of NewPipe are you using? (not filled out) Is it the last one?
What video causes the problem on your device?

Also did you see that there is a Fit/Zoom/Fill button on the top left when you expand the options menu (top right)?

**Comment by litetex** [comment]
Oh the issue was closed.
So is the problem fixed now?

**Comment by stemy2** [comment]
Yep, sorry for the PEBKAC.
