### ISSUE TITLE
Play List Download

### ISSUE THREAD

**Issue by mablue** [TeamNewPipe/NewPipe#7390]
Please add a button or menu button to download playlist videos one by one...:)

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5482. Also, please fill in the template properly. You are not supposed to remove it.

**Comment by litetex** [comment]
Duplicate of #5482

**Comment by mablue** [comment]
Thanks for responses 😌
Sorry for small t.i.
But I searched and find out this:
https://github.com/TeamNewPipe/NewPipe/issues/746#issuecomment-443459870

If no one want to work on it just say me where can I find the list variable that contains list of playlist links to write the code my own and than i will send pr
