### ISSUE TITLE
Showing  Video duratiom

### ISSUE THREAD

**Issue by Gottarocket** [TeamNewPipe/NewPipe#7394]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'feeds'
2. Most of the videos dont have video duration
3. Press and hold on 'video' without duration on thumbnail 
4. Click on show channel details and it shows the video duration as to how to long it is on thumbnail 
5. Go back to video under feeds now that video shows duration on thumbnail

### Actual behavior

Thumbnail which didnt show duration shows it after last step

### Expected behavior

Show beforehand under feeds 
Also this is also for videos which are not played yet but played videos show duration which shouldnt be the case when you want to know how long the video is before watching it

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by litetex** [comment]
![grafik](https://user-images.githubusercontent.com/40789489/141185994-99c75dd8-d4fd-4295-b27a-5d5505047302.png)
