### ISSUE TITLE
Community tab support

### ISSUE THREAD

**Issue by itsmeboy0** [TeamNewPipe/NewPipe#7399]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
See the community section of a channel.

#### Why do you want this feature?
It is a widely used feature and is the only thing moving me away completely to NewPipe.

**Comment by mhmdanas** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/2414.
