### ISSUE TITLE
Subscription Refresh

### ISSUE THREAD

**Issue by fnkwuweh** [TeamNewPipe/NewPipe#740]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

It would be great to have a "pull to refresh" option to update the subscription feed.

**Comment by wb9688** [comment]
Yeah, I think this shouldn't be hard to implement.

Off-topic: if you put a x (instead of the √ you're using) between the
brackets, it'll become a checked checkbox.

**Comment by Stypox** [comment]
This will be implemented in #2309

**Comment by Stypox** [comment]
#3321
