### ISSUE TITLE
Wonky aspect ratio while in fullscreen

### ISSUE THREAD

**Issue by dougabugg** [TeamNewPipe/NewPipe#7401]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any video
2. Start the video, observe aspect ratio in portrait mode
3. Switch to fullscreen/landscape mode, observe aspect ratio is wonky

### Actual behavior

Video appears to be "stretched" horizontally while in fullscreen, making the aspect ratio wonky.

### Expected behavior

I expected the video's aspect ratio to not be wonky

### Screenshots/Screen recordings

From these 2 screenshots, notice how the graphic circle turns into an oval shape when in landscape/fullscreen mode

[Screenshot_20211113-230544](https://user-images.githubusercontent.com/18294318/141668536-8927521e-ee0f-46f1-90e1-c20beec8ce95.png)
[Screenshot_20211113-230609](https://user-images.githubusercontent.com/18294318/141668535-f72dc954-c71f-46a1-b87a-322b01531a9d.png)

### Logs

NewPipe does not crash, no logs to post

### Device info

 - Android version/Custom ROM version: Android 12, SP1A.211105.002, 4.9.270-gd728658b095f-ab7709094
 - Device model: Pixel 3a

**Comment by SameenAhnaf** [comment]
Did you try changing video zoom mode? Also, note that different videos have different aspect ratios.

1. Open the secondary panel by clicking on the top right icon.
2. Choose "Fit/Fill/Zoom" according to your preference.


(A) Fit: Stream the video in actual aspect ratio.
(B) Fill: Stretch the video upto the edge of screen.
(C) Zoom: Crop the video to match device aspect ratio.

![IMG_20211114_113452](https://user-images.githubusercontent.com/79245641/141669267-8512f6b4-f129-48cb-893b-c83bddbccb3c.jpg)

**Comment by dougabugg** [comment]
Ah! I don't remember ever changing that option, must have toggled it by accident, but that fixed the wonky aspect ratio! Not a bug, but a simple user-error of type ID10T 😛
