### ISSUE TITLE
Cannot readd video to playlist

### ISSUE THREAD

**Issue by Ojd2000** [TeamNewPipe/NewPipe#7402]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a Playlist
2. Reproduce a video inside it in foreground
3. While still reproducing, remove it from the playlist, even without waiting
4. Without exiting the playlist, try readding it to the same playlist.
5. It should not work, until you close and reopen the playlist and readd it again.

### Actual behavior

The video cannot be readded to the same playlist it was just removed from without closing and reopening the playlist first.

### Expected behavior

I'd expect to readd it without having to close and reopen the playlist.

### Device info

 - Android version/Custom ROM version: Lineage OS 18.1 for microG
 - Device model: Oneplus 5

**Comment by dtcxzyw** [comment]
This bug can be reproduced on the latest dev branch. Can I try to fix it?
