### ISSUE TITLE
gesture-changing brightness while switching to portrait causes the "gesture image" to replace video

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#7409]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play any video in landscape
2. Use gesture to modify brightness and while doing so turn phone to portrait

### Actual behavior
 The "brightness gesture wheel" remains as a still image and the video image is gone.

### Expected behavior

The gesture should be canceled when switching to portrait or, since in most cases this is likely accidental, the switch to portrait should be ignored while a landscape-only gesture is being performed.

### Device info

 - Android version/Custom ROM version: 8
 - Device model: Samsung Galaxy S7 Edge

**Comment by defini-tiv** [comment]
Not reproducible for me.
It just doesn't rotate before i lift my finger.

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?

**Comment by infinitewaveparticle** [comment]
Not on my new phone. I'll have to check on the device I originally used and get back to you

Sent from Proton Mail mobile

-------- Original Message --------
