### ISSUE TITLE
Tilting Screen Aspect Ratio Bug

### ISSUE THREAD

**Issue by Feuerswut** [TeamNewPipe/NewPipe#7414]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play a video in vertical orientation.
2. Tilt the device
3. BUG: Sometimes the video is still in the small preview in the upper left corner. 
4. Workaround: Push the fit to screen button

### Actual behavior

Video has original preview resolution from when playing horizontally. 

### Expected behavior

The video plays properly, e.g. it touches at least 2 sides of the screenspace 

### Screenshots/Screen recordings

Bug demonstrated:
[YouTube Video](https://www.youtube.com/watch?v=XVTOZ249yuk) 

### Device info

 - Android 12, stock (patch Nov/21)
 - Pixel 6

**Comment by litetex** [comment]
Looks like a duplicate of #7262

**Comment by Feuerswut** [comment]
yes its a duplicate
