### ISSUE TITLE
Searching for "game grumps" causes an exception

### ISSUE THREAD

**Issue by xtj-9182** [TeamNewPipe/NewPipe#743]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I'm posting this here since the email thing didn't work for me, I don't have an email app apparently.

How to reproduce ? Search for "game grumps" without "

This is the Exception log that new pipe generated:

[newpipev010exception0.txt](https://github.com/TeamNewPipe/NewPipe/files/1336946/newpipev010exception0.txt)

**Comment by rockybulwinkle** [comment]
I couldn't reproduce the bug.

**Comment by theScrabi** [comment]
No there is one thats true.

**Comment by Stypox** [comment]
Closing in favour of #2371
