### ISSUE TITLE
nicovideo support

### ISSUE THREAD

**Issue by soracqt** [TeamNewPipe/NewPipe#7437]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I want to play videos from https://nicovideo.jp with this client

#### Why do you want this feature?

I like nicovideo yea

Thank you!

**Comment by SameenAhnaf** [comment]
Please open issues about new Services on https://github.com/TeamNewPipe/NewPipeExtractor instead.

**Comment by litetex** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipeExtractor/issues/719
