### ISSUE TITLE
Search crash

### ISSUE THREAD

**Issue by xtj-9182** [TeamNewPipe/NewPipe#744]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Unfortunately I can't reproduce this crash, as far as I remember I had searched for something and was going through the list and watched videos and went back to the search result and at some point I think I double clicked back and it crashed but I can't reproduce it. I thought it was worth posting the stacktrace just in case:

[newpipev010exception3.txt](https://github.com/TeamNewPipe/NewPipe/files/1336998/newpipev010exception3.txt)

**Comment by coffeemakr** [comment]
I can reproduce it by switching orientation and typing something into the search bar but it doesn't happen always.

I'll investigate this issue.

**Comment by coffeemakr** [comment]
https://sentry.schabi.org/sentry/newpipe/issues/382/
