### ISSUE TITLE
Hashtags with accented characters not properly recognised

### ISSUE THREAD

**Issue by edewaele** [TeamNewPipe/NewPipe#7441]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

- Search Youtube for "déconspirateurs 05"
- In the results, open "Les Déconspirateurs - l'émission 05"

### Actual behavior

See the description, whenever a hashtag contains an accented character, Newpipe generates a link which stops before the first accented character. For example, #extrêmisme is rendered as a #extr instead, while the rest is displayed as regular text.

### Expected behavior

Newpipe should consider accented characters as regular letters.

### Screenshots/Screen recordings

<img src="https://user-images.githubusercontent.com/1607217/143439151-6fceee5a-3b7b-4e90-ac75-5955ace623b1.jpg" width="300px" alt="Screenshot_2021-11-24-21-47-39-571_org schabi newpipe">

### Device info

 - Android 11 / MIUI 12.5.6
 - Device model: Redmi Note 10 Pro

**Comment by Jaspann** [comment]
Creating PR for this issue now 😀
