### ISSUE TITLE
When will it be compatible with Android 11？

### ISSUE THREAD

**Issue by zhangyinglong1993** [TeamNewPipe/NewPipe#7443]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by tsiflimagas** [comment]
The app works on a11. I don't know if you mean something specific by compatibility. Also, you should have filled out the template and put the question (in a more complete form) in it, instead of putting it in the title.
