### ISSUE TITLE
Android TV -- Settings Import broken (shows "You don't have an app for that" toast)

### ISSUE THREAD

**Issue by championdoughreferral** [TeamNewPipe/NewPipe#7446]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. On Android TV, go to Settings > Content > Import database and attempt to import a database

### Actual behavior

Toast pops up saying "You don't have an app for that" suggesting Newpipe can't access the file system.

### Expected behavior

The Import modal should pop up and allow you to select a file.

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Sony Bravia XBR-55A9G / Bravia 4k UR2

**Comment by litetex** [comment]
1. Do you have a file manager installed? If not try to install one like https://f-droid.org/en/packages/me.zhanghai.android.files/
2. Try to enable/disable "Use system folder picker (SAF)" in the download-settings.

**Comment by championdoughreferral** [comment]
Aha! Disabling SAF did the trick. The modal now shows up. Thanks!

**Comment by ckran** [comment]
On CCwGTV using NewPipe 22.1 am getting the same error. I have Solid Explorer and I installed f-droid. On the Settings Download page the "Use system folder picker (SAF)" toggle is grayed out in on position.

**Comment by opusforlife2** [comment]
Try the file manager linked in the comment above. Not all file managers offer this option.

**Comment by ckran** [comment]
Thanks. I understand now. I installed Material Files; it works.
