### ISSUE TITLE
Android TV -- Playlists (non-user created) -- Unable to scroll through videos in List View

### ISSUE THREAD

**Issue by championdoughreferral** [TeamNewPipe/NewPipe#7447]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Search for a playlist and click on it.
2. Attempt to scroll down and select a video.

### Actual behavior

You are only able to select the playlist buttons (Background, Play All, Popup). Attempting to get to the video section by pressing Down just loops back to the channel name just below the playlist name.

### Expected behavior

I am able to press Down multiple times and select the videos in the playlist.

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Sony Bravia XBR-55A9G / Bravia 4k UR2

**Comment by Stypox** [comment]
Please check if this is still reproducible in 0.22.1, as there have been some fixes to lists
