### ISSUE TITLE
[Feature Request] Channel Groups Tab

### ISSUE THREAD

**Issue by Coderdude112** [TeamNewPipe/NewPipe#7448]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

It would be nice to have a tab (Like we have for "What's New", history, ect) exclusively for channel groups.

#### Why do you want this feature?

As someone who has tons and tons of subscriptions, I group them into channel groups so I have around ~10 different channel groups, but currently the way to access channel groups is limited to a single row with small icons. Getting a tab exclusive to channel groups with each group the size of bookmarked playlists would be helpful and nice.

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3559

**Comment by Coderdude112** [comment]
Thanks @SameenAhnaf I'll close this.
