### ISSUE TITLE
[Feature request] Bulk video-audio downloader for subscription, channel and search feeds

### ISSUE THREAD

**Issue by Mikkelsman** [TeamNewPipe/NewPipe#746]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hello NewPipe people! :)
I have been using the app for a long time now and I must begin by thanking everyone for their labor of love that they have put towards making the app what it is today - I have great respect for you all.

Yesterday when I updated to the latest version I was thrilled to see that subscriptions had been added as a feature: it's killer! :) I personally use NewPipe mainly to download videos for offline viewing. Because I spend a lot of time outdoors where I've had limited amounts of power available to me, I try to minimize activities such as streaming content or using the internet in the woods as much as possible to conserve power. Therefore, once I visit civilization, I download many days' worth of content at a time that I can then watch offline when in the woods.

However, so far it has been pretty labor-intensive to check my subscriptions using the official YouTube app, then opening those videos one by one in NewPipe to download them, switching back to the YouTube app and repeating the process. I'm happy to see that including subscriptions directly in NewPipe makes this a little bit easier. :) However, the job of opening up individual videos to download them one by one still exists. Therefore, what I would like to suggest here, to complement the new subscriptions feature and to add into the existing NewPipe experience, is a bulk video-audio downloader feature.

Essentially what I've been thinking about is that you could open up the subscriptions feed (the What's New feed), which would show videos in nice chronological order and loading more videos as the user scrolls downwards, dating back a good amount of time. You could also view a YouTube channel. Then, either by long-pressing a video or pressing a separate button, you would essentially enter a checkbox selection mode, just like in many file managers for Android, that would let you select multiple videos at a time and then downloading them all with the same quality setting with just one click. To add further functionality without making things more complicated, when entering the selection mode, next to every video in the list there would be a togglable video/audio button (or two separate buttons) where you could select whether you want to download the video as video or audio. 

Then, once you're done selecting the videos to download, you would select the resolution and number of threads for the videos and the format and number of threads for the audios as usual. All to-be-downloaded videos and audios could use the same format/quality settings for simplicity, but of course some power users could appreciate being able to select the resolution for each one separately (perhaps a drop-down menu next to the video-audio toggle button next to each video), but that's probably a pretty small number of people and it could complicate things a little bit for the average user by giving too many options although you could argue that that's never a bad thing.

Entering the selection mode by long-pressing a video would be very intuitive and neat but not necessarily most user-discoverable, especially if there isn't any mention of it anywhere. Other ways to enter the selection mode could be having a button for it when clicking the three dots on a channel or the what's new feed or having, for example, a download-style icon with an arrow pointing down next to the three dots. Perhaps it wouldn't be completely unreasonable to add the bulk downloader to the search results as well to make it consistent throughout the app.

This feature would make it very easy to go through, for example, two weeks' worth of content from your subscriptions by scrolling the feed and selecting which videos to download and whether you want them as video or audio (for example, if there are podcasts, music or similar) very easily and neatly and in absolutely no time at all, without ever having to go to the pages of individual videos. I'm no programmer at all, but it sounds to me like such a bulk downloader wouldn't be too diffiult to implement, although I absolutely understand and respect the fact that you have limited time available and probably more important stuff to do, so no pressure at all here. :)

I realise this may be a little bit of a niche power-user feature but given that the ability to download videos and audio is very core functionality in NewPipe, and may be why many users are using it, I think it could be useful to make it as robust as possible. However, I don't intend to be demanding in any way here, whether or not you would like to implement this feature is completely fine to me. Above all, thanks again for all that you do for the app, you guys rock! :)

Please pardon me for the wall of text, I don't know how it ended up being this long. I greatly appreciate you taking the time to read to the very end.

**Comment by cwgt** [comment]
plus add a option to limit concurrent downloading item.

**Comment by Mikkelsman** [comment]
I realized I suggested an unnecessarily complicated way of doing this and I think I found a better way. :)
It would be to implement a three-dot menu next to every video.

Pressing on the three dots next to each video would present you with options:
"Download video using default settings"
"Download audio using default settings",
or to make it shorter via alternate spellings like: 
"Download video/audio using defaults" (may be a little bit tech-slangy) or 
"Quick/Instant/1-click video/audio download".
For these options, there would have to be a configurable default setting for the number of threads to use for these downloads in the settings menu, either under "Settings" ---> "Video & Audio" or 
"Settings" ---> "Download".

There would also be a "Download..." option in the three-dot menu, which would open up the regular download window on top of the search results/channel/subscription feed you are currently looking at, without unnecessarily taking you to the individual video (which you would have to come back from, adding hassle). This would be useful if you want to download some videos in higher quality than what the default settings are set to.

A neat way to implement these in the menu could be just the NewPipe download icon plus "Video/Audio" after it (for the 1-click downloads) and just the download icon (with or without "..." after it) for the "Download..." option but I don't know how well it would fit with the rest of the menu to combine text with icons for some menu items but not all. I don't know if this would be a good idea.
    
Using the three-dot menu to implement the bulk downloader would be a great moment to implement
the three-dot menu in general (it would appear everywhere in the app next to videos for consistency and
power users). The three-dot menu is also very clear to the user as to what it does and also looks very neat and takes very little space. 

And you could then add other options to the menu as well like sharing and adding to a playlist or "watch later" list to facilitate doing such actions faster if such features are implemented in the future (sharing
is, of course, already available), which would be really cool. :) 🙂

Even though the three-dot menu would take almost twice the clicks compared to the very power-user-targeted, perhaps complicated and unaesthetic way I suggested in my first post, it would already bring things down to a very acceptable level of effort in my opinion (at least for average, even for very frequent use), and is still a lot faster and easier than what is currently available (the new subscription feature already eliminates having to use the official YouTube app in combination with NewPipe for subsciption downloads). :)
In fact, I think the ease and simplicity of the three-dot method could more than compensate for the extra
clicks and it's also just very neat.

Maybe this suggestion should be made into a separate issue as the whole three-dot menu thing is kind of a big thing? :)

**Comment by opusforlife2** [comment]
The UI/UX for multiple video selection and performing operations on them is being considered in #2583 right now. But I don't think bulk downloading should be added. There are too many variables involved (which format and resolution for each video, which format and bitrate for each audio, what to do if a chosen stream is missing in one of the videos, etc.). Operations of that complexity should be done with youtube-dl instead.

**Comment by Nico-Romero** [comment]
> The UI/UX for multiple video selection and performing operations on them is being considered in #2583 right now. But I don't think bulk downloading should be added. There are too many variables involved (which format and resolution for each video, which format and bitrate for each audio, what to do if a chosen stream is missing in one of the videos, etc.). Operations of that complexity should be done with youtube-dl instead.

What about letting the user configure the preferred formats as a list and the best quality [resolution/bitrate] desired?
That way for each video you will almost always have a candidate. If there is no candidate (because you selected a resolution/bitrate too low), the video is not downloaded, but an alert with a link to the video is displayed somewhere.

I also think this would be a great feature. I would definitely download all the videos from some of my channel suscriptions on the wifi to be watched offline later (on the plane or just as a data and power saving strategy...).
I downloaded a few of them, but going one by one is a no... you spend too much time doing something that could be easily automated... at the end I want to see the video/listen to the audio, the quality option is important, but in this case I would care more about having the possibility of downloading all.

Great job with the app! Thanks!

**Comment by opusforlife2** [comment]
> but an alert with a link to the video is displayed somewhere.

Or simply, just don't remove those videos from the download list/queue, so the user could change resolutions right from there.

**Comment by litetex** [comment]
Closing in favor of #5482
