### ISSUE TITLE
Playlist shuffle doesn't load WHOLE playlist until you scroll and load it all

### ISSUE THREAD

**Issue by erosyte** [TeamNewPipe/NewPipe#7463]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1.go on a playlist
2.Select play all or background
3. Go on playlist and select shuffle

### Actual behavior
 shuffle only shuffles loaded song list(~20 songs), not whole playlist.
You have to scroll down and load all the playlist in order for it to shuffle everything.

### Expected behavior
 shuffle the WHOLE playlist

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by XiangRongLin** [comment]
#875
