### ISSUE TITLE
Issue with queueing videos in background

### ISSUE THREAD

**Issue by shadowcyberdeck** [TeamNewPipe/NewPipe#7464]
**Checklist**:

- [x] I am using the latest version - 0.21.13 
- [x]  Potentially related to issues #7235, #5741, and/or#5677
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

**Steps to reproduce the bug**:
1. Go to any youtube channel or video
2. Long press on a video
3. Click "start playing in background"
4. Swipe down on the notification tray
5. Click on the video playing in the background to get to the background queue
6. See below, also see video attached

**Actual behavior**:

After step 5 above, you should just see that one video you just queued in the background player queue.

**Expected behavior**:

Seeing entire play history in queue, as well as the video i just queued for background playing.

However, I will note that every now and then queued background option does work as intended. I think it might have to do with if you queue the video from your watch history vs. A channel page or what's new page. This started happening within the past week. I've been on version 0.21.13 since it was released.  Ill try downgrading to 0.21.12 if I have time later today and report back.  No error messages have been generated by newpipe for this error.

**Screen recording**: https://mega.nz/file/RNIB1aAQ#5UaMxBq4Xya7Cqt3C_-bUAMo_j-VcZ_Bg-Fys6rdzlQ

**Notes for the screen recording**:
- From the start until 10 seconds in, is the dupliacted actual behavior I'm see quite frequently.

- From 10 seconds on I was able to duplicate the expected behavior.

Device info
 - Android version: Android 10
 - Device model: Samsung Galaxy Note 9

**Comment by opusforlife2** [comment]
Closed in favour of #8499.
