### ISSUE TITLE
Donate link in root README.md is 404

### ISSUE THREAD

**Issue by Schlaefer** [TeamNewPipe/NewPipe#747]
Further information about donations points to https://newpipe.schabi.org/donate/ which is not found.

**Comment by TobiGr** [comment]
This can be closed now.

**Comment by trulex** [comment]
It's 404 again

**Comment by TobiGr** [comment]
CC @theAssassin

**Comment by TheAssassin** [comment]
Please report issues directly in https://github.com/TeamNewPipe/website, which I monitor.
