### ISSUE TITLE
Release 0.21.14

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#7473]
For newcomers:
This is a preview for the next release.
Feel free to test it, so we can fix any regressions before releasing.

## APK
[app-RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/7636889/app.zip)
Built from corresponding PR: #7475

### New
6 - Add a "add to playlist" option in the share menu #7194 
14 - Add "Check for updates" button in update settings #7296 
15 - Add support for y2u.be links #7304 
17 - Support PeerTube short links #7353 
23 - Show action to mark stream as watched all long press menus #7160 

### Improved
1 - Fix clicking timestamp shows Toast "Playing in popup mode" #7202
5 - Check if background player already active before displaying player toast #7224 
7 - Added the 'Show Channel Details' menu item to the Queue long press menu #7222 
13 - Use custom TextViews and EditTexts in all XML resources #7061 #7348
19 - [Feed] Save "Show watched items" toggle's status #7370
22 - Simple playback-speed-controls improvements #7363
24 - Rework feed new items handling #7050 

### Fixed
16 - Fixed shuffle button opacity UI bug #6844
25 - Prevent automatic replay after returning from background #7381 
30 - [YouTube] Likes and dislikes extraction #7467 / TeamNewPipe/NewPipeExtractor#753

### Localization
31 - Updated translations #7474 

### Development
2 - Update AndroidX Media library to 1.4.x #7148 
3 - Deduplicated drawer code in MainActivity #7215 
4 - Use the correct TAG in NavigationHelper #7196 
8 - Clean up .gitignore files #7264 
9 - Remove deprecated setUserVisibleHint #7265 
10 - Update pager workaround code to Fragment 1.3.6 #7149 
11 - Update some libraries #7263 
12 - Update RecyclerView & Groupie libraries #7261
18 - Gradle: Replaced deprecated 'with' with 'using' #7395 
20 - Update ExoPlayer to 2.14.2 #7005 and #7408
21 - Remove JCenter #5843
26 - Add gradle wrapper Sha256 #7418 and  #7442
27 - Use DefaultLoadcontrol #7406 
28 - Some code cleanup(s) #7412 
29 - Better player error handling #7142 

## Changelog of NewPipeExtractor
see https://github.com/TeamNewPipe/NewPipeExtractor/pull/758

**Comment by litetex** [comment]
## litetex's ultimate release checklist (draft):
👉 https://teamnewpipe.github.io/documentation/05_releasing/

### Preparing the release
- [x] Determine the next release versions (major, minor, etc)
- [ ] (if applicable) NPExtractor: Create a release branch in your fork (ensure that your local repo is up-to-date)
  - [ ] Increment the version
  - [ ] Create a PR to ``master``
  - [ ] Create a new draft release
- [ ] Sync weblate (get the newly translated stuff)
- [ ] Create a release branch in your fork (ensure that your local repo is up-to-date)
  - [ ] Increment the version
  - [ ] Create a changelog file (max. 400 bytes)
  - [ ] Create a PR to  ``master``
  - [ ] Create a new draft release
- [ ] Create an issue
- [ ] Add a release candidate to that issue (can be built using ``./gradlew debug releaseCandidate?``)
- [ ] Sync weblate (publish the changelog file, etc)

### In the meantime (when there is a release candidate but the release itself is not published)
- [ ] Look for any regressions
- [ ] Update the RC accordingly (see above)
- [ ] (optional) Sync weblate

### Releasing
- [ ] (if applicable) NPExtractor: Release
  - [ ]  Merge the PR
- [ ] Ensure the up-to-date NPExtractor version is used
- [ ] Sync weblate (to get the translations of the changelog file, etc)
- [ ] Merge the PR
- [ ] Build an unsigned APK (``<Insert_build_command_here>``)
- [ ] Send it to TheAssassin (in an encrypted and signed E-Mail)
- [ ] Receive the signed APK; Check the sent back signed APK locally on your device(s)
- [ ] Add the signed APK to the GitHub release draft
- [ ] Create a new tag for the release (should match with the release e.g. ``v0.12.3``) on the master branch (may be done with the next step)
- [ ] Check everything again
- [ ] Publish the GitHub release
- [ ] Update the main F-Droid repo → https://teamnewpipe.github.io/documentation/05_releasing/#publish-on-f-droid
- [ ] Check/Ask TheAssassin if our repo is up-to-date

**Comment by CHECK-1234** [comment]
I have a issue with the release 0.21.14. I am in PHH's Android 12 AOSP GSI.

1.The app takes longer to open. This is not happening to me in 0.21.13.

2. When navigating through the settings in 0.21.14, it takes long to load the setting options that I press.

When I use PHH's AOSP Android 12 GSI, the app "YouTube Vanced" was also having the problem of opening slow compared to Android 11 PHH AOSP. 

So I switched to using NewPipe instead, which was 0.21.13 and it did not take long to open. But then I downloaded 0.21.14 from the post, and now it now has the same problem as "YouTube Vanced", where it takes a long time to open.

**Comment by Tom4tot** [comment]
> I have a issue with the release 0.21.14. I am in PHH's Android 12 AOSP GSI.
> 
> 1. The app takes longer to open. This is not happening to me in 0.21.13.
> 2. When navigating through the settings in 0.21.14, it takes long to load the setting options that I press. This is not happneing to me in 0.21.13.
> 
> When I used PHH's AOSP Android 12 GSI, the app "YouTube Vanced" was also having the problem of opening slow compared to Android 11 PHH AOSP GSI. I used "YouTube Vanced" because it was taking less power when playing a video compared to NewPipe (tested using "CpuFloat" app, using "Battery current" option).
> 
> So I switched to back to using NewPipe instead of "YouTube Vanced". I used NewPipe 0.21.13 and it did not take a long time to open. But then I downloaded 0.21.14 from the post, and now it now has the same problem as "YouTube Vanced", where it takes a long time to open in Android 12 PHH AOSP GSI.

Pixel 6 ProtonAOSP (A12), I'm not experiencing such behavior.

**Comment by Stypox** [comment]
> Update the main F-Droid repo

The documentation is probably outdated, but you don't need to do anything to get the new version published on the official F-Droid repo, their automatic updater takes care of adding new versions to the file

**Comment by pokegamer5547** [comment]
hello, i recently made an issue #7486 and i noticed it's still exists in this version and it's really annoying.

**Comment by tsiflimagas** [comment]
> hello, i recently made an issue #7486 and i noticed it's still exists in this version and it's really annoying.

If it was fixed, it would be mentioned in the changelog. Also, you opened that issue less than a day ago. Annoying or not, this interval is short for an issue to be addressed.

**Comment by pokegamer5547** [comment]
> > hello, i recently made an issue #7486 and i noticed it's still exists in this version and it's really annoying.
> 
> If it was fixed, it would be mentioned in the changelog. Also, you opened that issue less than a day ago. Annoying or not, this interval is short for an issue to be addressed.

ah i think you're right, well i'm sorry about that. i just thought i should mention it again since it could cause problem to some users. but i understand what you mean too.

**Comment by IngwiePhoenix** [comment]
I am not too familiar with the way NewPipe handles releases but due to the missing updates to the Dislike extractor, I get a lot of choppy playback and tons of error messages showing up on the bottom of the screen way too often. So basically, this update ca't come soon enough :)

Therefore I wanted to ask what the ETA currently is?
I am on Razer Phone 2, Android 9 stock (sadly...) and installed via the F-Droid repo.

**Comment by NewNewPipe** [comment]
#7059 Downloading error / problem.

0.21.14 RC2

Still the same problem. No change.

**Comment by Stypox** [comment]
@NewNewPipe only report new issues here! That is, issues caused by this release that were not present in the previous release.

**Comment by litetex** [comment]
@CHECK-1234

Your problems are likely caused by the fact that the provided version is a debug version of NewPipe.
I also had this problems but when I built a release version locally and compared the speed it was similar to 0.21.13.

**Comment by CHECK-1234** [comment]
> @CHECK-1234
> 
> Your problems are likely caused by the fact that the provided version is a debug version of NewPipe. I also had this problems but when I built a release version locally and compared the speed it was similar to 0.21.13.

I tested a release from the "Actions" tab that was 0.21.13, and it was a debug apk. When I opened it, it did have the same slow opening speed. You are right, sry if I cause any misunderstandings. I guess the issue was just because of it being a debug version.

**Comment by lnwor** [comment]
I opened a video and the volume on my earphones was very high, returning to the launcher and then back to newpipe (while the video wqs playing in background) fixed the issue

**Comment by Stypox** [comment]
@lnwor is this caused by this release?

**Comment by lnwor** [comment]
Yes, it happened just once though, it could be a rare bug or the cause could be the bluetooth earphones. I wanted to report it in case it happened to anyone else

**Comment by Kr1sh1** [comment]
This update is still not available on fdroid, I am using the newpipe repo. It's never taken longer than ~12 hours before, is something wrong?
