### ISSUE TITLE
It will not play one of my playlists and says something went wrong

### ISSUE THREAD

**Issue by Jaydenssbd** [TeamNewPipe/NewPipe#7477]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
Please fill the template properly; we can't help you with that little info.
