### ISSUE TITLE
Wrong german translation string in NewPipe 0.21.13

### ISSUE THREAD

**Issue by christfried** [TeamNewPipe/NewPipe#7478]
Sorry to open a bug report for this but I was not able to find the string on weblate. [This](https://hosted.weblate.org/translate/newpipe/strings/de/?q=tag) does not seem to be it.
When using NewPipe in german, there is an issue with the release date of the videos shown as "1 day ago". This shows up as "vor 1 Tagn" but it should be "vor 1 Tag" instead ("vor einem Tag" would be even better).
Please do not hesitate to get me started on finding the correct string on weblate ...

**Comment by mhmdanas** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/6050. You're not finding the strings because they're not there; this is handled by the [PrettyTime library](https://github.com/ocpsoft/prettytime). An issue has already been filed there: https://github.com/ocpsoft/prettytime/issues/218
