### ISSUE TITLE
fsfe tube

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#7480]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.   
🔍 - [fsfe tube](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aopen+fsfe-tube) | [fsfe tube](https://github.com/TeamNewPipe/NewPipeExtractor/issues?q=is%3Aopen+fsfe+tube)
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Support for fsfe-tube
- [home page](https://media.fsfe.org/)
- [example video](https://media.fsfe.org/w/7cH6EATpmPwaMsEZN8vfyj)

#### Why do you want this feature?

The videos there looked like of interest to me, and there seemed to be ample videos there. So, if that's not much debt to have this, then i guess it will be cool to have.

**Comment by yashpalgoyal1304** [comment]
this issue moved out from NewPipeExtractor repo to here, since as mentioned in "Additional context" of https://github.com/TeamNewPipe/NewPipe/issues/7456 fsfe tube is already supported (being a peertube instance).

**Comment by yashpalgoyal1304** [comment]
hey yeah, i forgot to ask an OT ques, how did u know/figured out that it is a peertube instance?

**Comment by mhmdanas** [comment]
For me, the first one. PeerTube instances generally look pretty similar across the board. For example, compare https://media.fsfe.tube with https://framatube.org.

>  maybe there's some other mechanised method for checking newpipe related stuff etc

Hmm, not sure about that.

**Comment by litetex** [comment]
> how did u know/figured out that it is a peertube instance?

![grafik](https://user-images.githubusercontent.com/40789489/145456129-c77a9867-f20a-42af-bd4b-a493ea1c2d9a.png)

**Comment by yashpalgoyal1304** [comment]
> _image_

oh good lord, my observation power has really degraded in the last couple of months 😅
