### ISSUE TITLE
Sync across devices

### ISSUE THREAD

**Issue by AtomicNess123** [TeamNewPipe/NewPipe#7488]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Is there the possibility to log in and sync across devices? Checked issues, did not find anything.
Thanks!

**Comment by AtomicNess123** [comment]
Updated question. Template acknowledged.

**Comment by mhmdanas** [comment]
No, there is no login nor syncing currently. See related issues #1163,  #2278, #3198, #3249, and #5325.
