### ISSUE TITLE
"something went wrong" error while opening videos

### ISSUE THREAD

**Issue by ynsnf** [TeamNewPipe/NewPipe#7503]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
While opening and resuming a video, I get the error message shown below. 

### Screenshots/Screen recordings

![error](https://user-images.githubusercontent.com/95400016/144747756-7a297bb0-5609-4403-bc85-11cc5851bc1f.jpeg)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Note 8

**Comment by TiA4f8R** [comment]
Duplicate of #7405. Please look at exisiting issues (especially the pinned ones) first before opening a new issue. Thank you.
