### ISSUE TITLE
"Unsupported URL" Error: Opening channels with special or non-latin characters (UTF-8 Hex)

### ISSUE THREAD

**Issue by numeral-omega** [TeamNewPipe/NewPipe#7506]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any youtube channel with special or non-latin characters in their URL with Newpipe.

Example: "SBS Radio 에라오" https://youtube.com/c/SBSRadio%EC%97%90%EB%9D%BC%EC%98%A4

### Actual behavior

Error message displayed when opening YT channels with special or non-latin characters in their URL  (i.e é or 에) with Newpipe or sending the URL to Newpipe. There is no error when accessing the channel from within the app. 

### Expected behavior

The channel in question should open in Newpipe without any errors.

### Screenshots/Screen recordings

![20211119_082824](https://user-images.githubusercontent.com/94675770/142591111-46d2faba-ad6c-4ee4-a582-27996e235021.jpg)

### Device info

 - Android version/Custom ROM version: Android version 10
 - Device model: Samsung Galaxy S9 - SM-G960F

**Comment by numeral-omega** [comment]
This issue has not been resolved but the error message has changed. it now simply says 'Sorry, Something went wrong'.

**Comment by AudricV** [comment]
Fixed with TeamNewPipe/NewPipeExtractor#964.
