### ISSUE TITLE
Add an auto-play option, it's a BASIC feature!

### ISSUE THREAD

**Issue by jjgh** [TeamNewPipe/NewPipe#751]
Playing a video should automatically enqueue other videos and play them in order.
I am using NewPipe since 3/4 months and I can't believe this has not been dealt accordingly to how important and basic this feature is.

**Comment by coffeemakr** [comment]
Duplicate of #165

**Comment by theScrabi** [comment]
> I am using NewPipe since 3/4 months and I can't believe...

Well because it's basically not that easy to implement that BASIC feature so fast. You are using NewPipe since 3/4 months and I can't believe why you still write on github instead of helping us implement this BASIC feature :*

**Comment by jjgh** [comment]
@theScrabi I apologise :)
