### ISSUE TITLE
Youtube Video Chapters not present on any of my devices

### ISSUE THREAD

**Issue by MarcK95** [TeamNewPipe/NewPipe#7515]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Im using NewPipe on a Huawei P30 (Android 10) and on a Samsung Galaxy Tab S6 (Android 11), on both of these devices the icon for video chapters wont appear though they are present on the web. Is this a known issue for some devices? What am I doing wrong?

**Comment by yashpalgoyal1304** [comment]
i think sharing the example video link may help investigate the issue better

**Comment by MarcK95** [comment]
@yashpalgoyal1304 It's a general problem, I don't see the chapter icon on any video.

**Comment by mhmdanas** [comment]
Still, can you please share the URL?

**Comment by pokegamer5547** [comment]
I'm having same issue tho only for some videos.
Example this
https://www.youtube.com/watch?v=xjUqYHyOJPM

**Comment by MarcK95** [comment]
@mhmdanas https://www.youtube.com/watch?v=0sGL_x5rnOA&ab

**Comment by mhmdanas** [comment]
That's odd, the chapters are present on my side. Can you please confirm that you're using the latest NewPipe version (0.21.14 as of now)? If not, can you try reproducing on that version?

**Comment by MarcK95** [comment]
I was on 0.21.13 and after updating to 0.21.14 it works
