### ISSUE TITLE
"View in Browser" only suggests opening in New Pipe or New Pipe pop up mode

### ISSUE THREAD

**Issue by cbartondock** [TeamNewPipe/NewPipe#752]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

I often run into the situation where I would like to comment on a video I am viewing in NewPipe. The easiest way to do this used to be to hit "view in browser" and select chrome from the apps it suggests. Now, however, at least on Android 8, the only suggestions are new pipe itself and new pipe's pop up mode. Thanks!

**Comment by yaomtc** [comment]
This has been happening to me on the latest LineageOS nightlies (Android 7.1.2). I have both the default Jelly browser and Firefox installed, but neither appears as an option. Instead I have to hit Share, Firefox, Open In Firefox.

**Comment by lingislong** [comment]
Yes it is so on version 0.14.1 :(
i use android ver 6.0.1 galaxy s5....

**Comment by yaomtc** [comment]
This has since been fixed for me. Using 0.14.2 on Android 8.1.0, "Open In Browser" used the YouTube app if it was enabled, and if it wasn't, it gave the options of NewPipe or Firefox.

**Comment by Stypox** [comment]
ACTION_VIEW is [being used](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/util/ShareUtils.java#L10) when creating the browser Intent, as suggested [here](https://stackoverflow.com/questions/2201917/how-can-i-open-a-url-in-androids-web-browser-from-my-application). So this is probably a problem of the browser or the OS.
