### ISSUE TITLE
Search only searches "corrected" terms

### ISSUE THREAD

**Issue by timonoj** [TeamNewPipe/NewPipe#7522]
Hi!

Seems the Newpipe search is unable to explicitly search for a word when it believes a corrected version might be more suitable. I.e, I'm trying to find a video under the name "UNVOXED", as it's a word play between vox and unboxed. No dice. Newpipe auto-corrects to "unboxed" videos, and there's no way to tell it otherwise. Quoting the search terms doesn't change the result. Youtube frontend does have this behavior, but it offers a second option after the fact, to actually search what you indeed wanted in the first place instead.

Can you help to fix this? I reckon it shouldn't be too much of a change.

Thanks!

**Comment by opusforlife2** [comment]
What happened here? When the feature was being worked on, I remember YouTube's behaviour was referenced. Was it decided to defer this or not add it at all?

**Comment by rogerval** [comment]
(@opusforlife2  So this was what I was looking for? 🙂)
I'd love this feature, too (but I'll be patient! 😁)

**Comment by opusforlife2** [comment]
Aha! See? With your help, we were able to find out that even this is a duplicate! Closing in favour of #6032.
