### ISSUE TITLE
We NEED a close button

### ISSUE THREAD

**Issue by mushnamukk** [TeamNewPipe/NewPipe#753]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Whether it is a button in one corner, the ability to drag the window to the bottom to close it, or SOMETHING needs to be instituted to allow the pop-up window to be closed. 

Currently my only option is to swipe down my notifications and find the video playing and then hit the X. Why not add one to the pop-up window?

**Comment by vctrac** [comment]
An easier way to close the pop-up would be great, or an "Close pop-up after video ends" toggle option.

**Comment by wb9688** [comment]
In v0.11.0 we've new pop-up gestures, including swipe-to-close.

@theScrabi: Could you close this one too?

**Comment by theScrabi** [comment]
I guess so :)
