### ISSUE TITLE
Video open at the wrong timestamp (thousands place digit ignored)

### ISSUE THREAD

**Issue by lestofante** [TeamNewPipe/NewPipe#7530]
### Checklist

- [x] I am using the latest version - 0.21.14 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
100% reproducible

1. Open link 'https://www.youtube.com/watch?v=y9aP4Ur-CXI&t=3939s'
2. The video will open at timestamp ~15:40 instead of ~1:05:40

### Device info

 - Android version/Custom ROM version: LineageOS 11
 - Device model: Redmi note 9s (EU)

**Comment by lestofante** [comment]
did you try with big timestamp too? maybe is some kind of overflow, or some singularity in the calculation.
Also this is a VOD of a live stream, maybe there are some special handling for those?

**Comment by opusforlife2** [comment]
I encountered this too. Some quick math revealed that the 4th digit (the thousands place) is ignored. If `t=1234s`, you're taken to `t=234s` instead.

**Comment by mhmdanas** [comment]
Sorry for the spam, I was force-pushing more than I should have. _nervous laughter_

Can you try the APK in the description of https://github.com/TeamNewPipe/NewPipeExtractor/pull/775?
