### ISSUE TITLE
Resuming app from background plays wrong video from queue

### ISSUE THREAD

**Issue by AlertSubject** [TeamNewPipe/NewPipe#7531]
### Checklist

- [x] I am using the latest version - 0.21.14 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Create a queue of videos
2. Watch a few videos from the queue
3. Wait til a video starts buffering 
4. Minimize app and let background playback start 
5. App started playing the previous video from the queue 
6. Reopen app 
7. The video before that current starts playing 

### Actual behavior
Newpipe plays videos from that queue that have already been watched 

### Expected behavior
Newpipe should continue the current video instead of jumping to a previous queued one 

### Screenshots/Screen recordings

The video shows the currently running video. After minimizing the app another video starts ("what's up guys" in the background) and after opening the app again it immediately jumps to another video from my queue. Which you can see in the video again 
https://youtu.be/Tf4jVVlY7l8

### Device info

 - Android version/Custom ROM version: Android 11, Oxygen OS
 - Device model: Oneplus9 Pro

**Comment by drewsat** [comment]
Yep it's really annoying

**Comment by fhteagle** [comment]
I am also seeing this when part way through a queue and switching to "split screen" mode. Queue is restarted immediately from the beginning. Old (desired) behavior was to continue playing current video on switch to split screen.

**Comment by WickyNilliams** [comment]
Also seeing weird behaviour around background playing. E.g if I click play all on a channel, when I turn screen off, it starts playing the first video. Not always, but most of the time. Not sure if related, but I'm also seeing a lot more buffering when app is in background, where I didn't previously

**Comment by MD77MD** [comment]
having the same issue.... to what version did you roll back

**Comment by WickyNilliams** [comment]
`0.21.13`

**Comment by TiA4f8R** [comment]
Does #7693 fix this issue?
