### ISSUE TITLE
Self-Hostable API For Subs, History, etc.

### ISSUE THREAD

**Issue by seniorm0ment** [TeamNewPipe/NewPipe#7544]
Something that really sucks about switching to Newpipe is you have to deal with exports. While this is not really an issue for just using on one device, it means you can't stay 100% updated across different devices or while using something like Invidious.

My suggestion, is to make a simple, minimal, API or some service users can self-host on their servers, that allows users to login. Then basically they can sync all of their subscriptions, watched history, and everything.
All they would need to do is plug their login or api token or whatever into any of their clients, and it should just sync everything.

This would be VERY nice. I know this isn't exactly a Newpipe specific request, but I think it would combine very nicely, and be a nice alternative to data exporting/importing.

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1163

**Comment by seniorm0ment** [comment]
Nice, thanks
