### ISSUE TITLE
v0.21.14 -  MPEG 1080p60 stuttering and buffering before video completely stops playback

### ISSUE THREAD

**Issue by perseusbiscuitsakira** [TeamNewPipe/NewPipe#7546]
- [x] I am using the latest version - v0.21.14 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to https://www.youtube.com/watch?v=cf9UT23TAC8
2. Select 'MPEG 1080p60' from drop down resolution menu

### Actual behavior
Video will play for between 10-20 seconds before sever frame rate drop (sub 5 frames per second) before video will try to buffer and then completely stop, only able to resume video by selecting lower resolution

### Expected behavior
v0.21.13 and previous releases, MPEG 1080p60 playback was flawless with no discernible frame drops

### Device info

 - Device model: Amazon Fire HD 10 Plus tablet

**Comment by TiA4f8R** [comment]
@perseusbiscuitsakira Could you check if you can reproduce this bug with the latest version (0.21.15)?

**Comment by perseusbiscuitsakira** [comment]
It's running smoothly now in 0.21.15, no problems, what ever the update did it fixed the problem, thanks

**Comment by TiA4f8R** [comment]
Then I am closing this issue. Free feel to let us know here if you can reproduce the issue or not.
