### ISSUE TITLE
Unable to import database and settings from old Newpipe installation

### ISSUE THREAD

**Issue by Aanai** [TeamNewPipe/NewPipe#7548]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### Additional context

My videos were glitching a bit so I uninstalled and reinstalled Newpipe on my Android phone. Before uninstalling I exported Newpipe database (Settings>Export database (Export history, subscriptions, playlists and settings). I got a .zip file with two files in it - newpipe.db and newpipe.settings. Now I am unable to import these files back into my fresh Newpipe installation. When I use the import database option, the newpipe.db and newpipe.settings files are greyed out.

**Comment by mhmdanas** [comment]
You are supposed to import the zip file itself, not unzip it and import the extracted files. If you have any further questions, feel free to ask.
