### ISSUE TITLE
[Feature request] Add an option "Move popup above the keyboard when keyboard is activated"

### ISSUE THREAD

**Issue by programings** [TeamNewPipe/NewPipe#755]
If the popup is positioned on top of the Android keyboard when it's activated (comes on focus), it will cover some keys and the user should bother to move the popup to use these keys.

There should be a setting to automatically move the popup above the active keyboard and restore it's inital position when the keyboard is no longer active.

**Comment by Stypox** [comment]
This seems not to be a problem anymore (at least with huawei keyboard):
![ezgif-4-b545797ebb11](https://user-images.githubusercontent.com/36421898/59976639-afaea680-95c7-11e9-968d-fb1d725bf90e.gif)
