### ISSUE TITLE
Playlist resets when sent to background 

### ISSUE THREAD

**Issue by LillB0** [TeamNewPipe/NewPipe#7559]
Every time the app is sent to the background with a playlist playing it will reset to the start of the first video in the playlist.
It does not matter if the playlist has been created in NewPipe or imported.

### Steps to reproduce the bug
1. Start playlist 
2. Send app to background 

### Actual behavior
Playlist stops with loading icon or starts at the beginning of the first video in the playlist 

### Expected behavior
The playlist should continue at the current video withou skipping to the start or the playlist 

### Device info
 - Android version/Custom ROM version: 9
 - Device model: Samsung Galaxy S8 (SM-G950F)

**Comment by MD77MD** [comment]
I'm having this same issue as well

**Comment by Zackyist** [comment]
Same problem on MIUI Global 12.0.8.0 (Android 10), it appeared after I updated from v0.21.13 to v0.21.15.

On my device the playback continues (as audio) on the current video when sent to the background but after I return to the app it immediately switches to the first video on the playlist. But if the current video is the first one, it continues playing normally as it should - so my current workaround is just swiping all watched videos on the playlist to the right before switching apps.

**Comment by drewsat** [comment]
I'm afraid the only work around is to downgrade to V10 as that's the only one that works, v13, 14 and 15 have this issue

**Comment by m77e4t** [comment]
I am also having the same issue. I like listening to songs from a particular playlist in background, either screen On or Off. But, if I move to a different app for a few seconds and return back to newpipe, the app starts playing the first video (song) again.

 The current workaround recommended is to downgrade the application. It might not be possible for me as the older versions were quite buggy, the latest versions seem to have solved all major bugs. 
 
 I would like if the newer versions solve this issue.

**Comment by MintMain21** [comment]
In general, switching from video to background play and/or back again tends to screw with video playback, whether it's restarting an individual video or an entire playlist. A fix would be most welcome.

**Comment by TiA4f8R** [comment]
Fixed with #7693, which will be included for the next release (0.22.0).

**Comment by LillB0** [comment]
Not really a duplicate since the problem description is not the same.
In #7531 the playlist started playing the previous video. In my case it started the very first video. Also it happened every time not just when the app was minimized during buffering.

**Comment by TiA4f8R** [comment]
@LillB0 Yes, you are right, but that's just one of the ways to reproduce the issue. Some comments of this issue are like the case you describe and the issues topics are the same, so I thought it would be relevant to close this issue. 

Anyway, it should be have been fixed with my PR so that's not needed to reopen this issue.
