### ISSUE TITLE
Accessibility: quickly switch between the player and the content list

### ISSUE THREAD

**Issue by bmivzkrp** [TeamNewPipe/NewPipe#7571]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Dear NewPipe developers!
Please make it possible to quickly switch between the player and the content list.
For example, during playback, there is a Go To Player button next to the pause / play and close buttons. The player, respectively, has a button Go to the content list. An alternative could be to assign a gesture to this feature. That is, the user can specify which gesture he wants to use.
I open this as a function request, because from the point of view of a blind user who uses a screen reader, there is nothing like it.

#### Why do you want this feature?

To get to the player, I need to do the following:
1. Turn on playback;
2. Go to the notifications panel;
3. Remove the name of the content being played and activate it.
This is inconvenient, because both content and speech synthesizer are played at the same time.
In the settings, I turned on the display of the player in full screen, but it seems that it does not help.

I will be grateful for resolving this issue.

**Comment by SameenAhnaf** [comment]
Please keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/3515

**Comment by litetex** [comment]
Thank you for the issue.

Feedback from my side:
1. There is no "content list" in this app - I don't know what you mean: The search? The "start" screen? ... 
I also can't follow the "To get to the player, I need to do the following:"-manual
2. As @SameenAhnaf already mentioned: This issue should be closed in favor of #3515

**Comment by bmivzkrp** [comment]
@litetex You must have misunderstood me:
1. I like the ability to switch to the player from the notification bar. But the fact that such a possibility exists, a blind user must guess ...
2. I would like to have a faster way to get to the player from the content list or subscription list. That is an alternative.
3. I do not mind closing this issue.
