### ISSUE TITLE
Data Speed too Fast for NewPipe?

### ISSUE THREAD

**Issue by jhorner555** [TeamNewPipe/NewPipe#7576]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?

This may sound a bit odd but when my phone is connected to 5G UC, running at roughly 430MB/s, videos don't load and I get a retry option. But when I connect to my mobile hotspot, a cool pad surf running at around 25 MB/s, everything works fine. Is it possible that such high speeds are too fast for NewPipe to handle and just crashes?

**Comment by litetex** [comment]
Thank you for the issue.
I don't think that these problems are related to the network speed. We have users here that have a 1GBit/s+ downlink and everything works fine.
Some tips to narrow down the problem and validate if it's related to network speed:
* Did you try viewing the same video in another app, e.g. the YT app or a mobile browser?
* Did the problem only occur on one specific video?
* Does your ISP maybe block the streaming service or did an outage occur during a specific time-frame that affected you?
* Did you try to disable 5G on your phone and use e.g. 4G/LTE?

Btw I think it's also really unlikely that a streaming service provides unlimited 3.4GBit/s (430MB/s) downlink to a single user.

**Comment by jhorner555** [comment]
Read it and weap, young grasshopper. I get the retry with a lot of videos from different channels. Has nothing to do with my phone or isp.

**Comment by opusforlife2** [comment]
> Read it and weap, young grasshopper.

What?

> I get the retry with a lot of videos from different channels.

Thank you for testing. Please address the other bullet points as well.

**Comment by SC1040-TS2** [comment]
> ### Checklist
> * [x]  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
> * [x]  I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
> 
> #### What's your question(s)?
> This may sound a bit odd but when my phone is connected to 5G UC, running at roughly 430MB/s, videos don't load and I get a retry option. But when I connect to my mobile hotspot, a cool pad surf running at around 25 MB/s, everything works fine. Is it possible that such high speeds are too fast for NewPipe to handle and just crashes?
> 
> #### Additional context

Greetings. Some additional information is required.

1. What phone model are you using?
2. What version of Android is it running?
3. What version of NewPipe were you using at the time?
4. Did you download it from the F-Droid dnfault repository, or the NewPipe Upstream Repository used for the latest version releases due to F-Droid's cataloguing overhead?
