### ISSUE TITLE
Background player completely broken, please back old version

### ISSUE THREAD

**Issue by gotofuckinghell** [TeamNewPipe/NewPipe#7579]
Please hit the idiot who introduced the current version of the background player, it is now completely broken. 
Continued playback in the background does not take into the current playback time, the video starts playing from 0:00.
Return the old version (pre 0.14ver) of the background player, where you could watch any video, without any problems for the (bkgd)playlist. 
The current player, with a carousel of back button clicks, is simply unbearable.
Thank you

**Comment by tsiflimagas** [comment]
Since the guy who made the changes is an idiot, then you may fix this issue. 
And get some manners, you talk as if you've grown up in a cave.

**Comment by gotofuckinghell** [comment]
>pleese donate
>plesee support

>oh no, fix it by yrself

are u mad?
