### ISSUE TITLE
Feed Failed to Update

### ISSUE THREAD

**Issue by roflrabbit** [TeamNewPipe/NewPipe#758]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Upon checking my feed to see if any new videos were made, I still haven't seen a single new video for the past few days. The only ones that always were there was the most recent video that the creator uploaded as soon as I installed the app, **the feed doesn't update**.

Edit: I have the newest version and I was really impressed, minus the old problem in a previous bug report when you would rotate the screen while it was loading something, causing it to fail.

**Comment by karyogamy** [comment]
The feed can become outdated if it is using a stale cache. This can happen if the app hasn't been terminated for some time. Try force closing the app and see if the problem persist.

**Comment by Stypox** [comment]
Refer to #740 for refreshing, that would solve this issue
