### ISSUE TITLE
Add toast to advise user to restart app after successful database import

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#7581]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

The app should show a toast after a successful database import, telling the user they need to restart the app for all settings to be applied.

#### Why do you want this feature?

As far as I'm aware, we still need a manual restart before the imported settings come into effect.

**Comment by litetex** [comment]
> As far as I'm aware, we still need a manual restart before the imported settings come into effect.

This shouldn't be the case:
https://github.com/TeamNewPipe/NewPipe/blob/215880207e1c89012a2445234c6de1f223a8c5b9/app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java#L273

I assume we can close the issue then or was it any specific setting that didn't work?

**Comment by opusforlife2** [comment]
Indeed. I was operating on old info. Fixed here: https://github.com/TeamNewPipe/NewPipe/commit/fda0a550fdbef3d95a1b02b1f469c79c9eebb69e.
