### ISSUE TITLE
App no longer plays videos after changing download location

### ISSUE THREAD

**Issue by ballo** [TeamNewPipe/NewPipe#7585]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Change download location (I'm my case I copied the link to my sdcard/tubes or "/storage/754F-EBC8/tubes"
2. Download YouTube video

100% reproducible on my phone 

### Actual behavior

3. Video will download to the correct location
4. NewPipe is unable to play the video. The error is "File not found"

### Expected behavior

Obvious normal behavior of being able to play and delete videos from within the app.

### Device info

 - Android version/Custom ROM version:
 - Device model:
Android 9 Samsung s8

**Comment by litetex** [comment]
1. Please fill out the template accordingly as described in the (issue) template: ``<!-- IF YOU DON'T FILL IN THE TEMPLATE PROPERLY, YOUR ISSUE IS LIABLE TO BE CLOSED...``
2. What are you meaning with "tubes"?
3. Are you using the SAF folder picker (setting can be found under "Downloads")? I think it has to be enabled otherwise saving to external locations is not or only limited possible.

**Comment by ballo** [comment]
tubes is just the name of the folder.

As I said, it downloads the videos fine. It just has no idea where

**Comment by litetex** [comment]
@ballo 
Okay, but could you please [answer my above questions](https://github.com/TeamNewPipe/NewPipe/issues/7585#issuecomment-1001226035) accordingly?

**Comment by ballo** [comment]
SAF setting was enabled

**Comment by litetex** [comment]
Tried to reproduce the problem with the limited information: Works as expected on my emulator.

Without a properly filled issue template I can't do anything.
Closing this issue.
