### ISSUE TITLE
Create playlist from search results

### ISSUE THREAD

**Issue by bphd** [TeamNewPipe/NewPipe#7588]
- [ ] https://www.reddit.com/r/youtube/comments/3wcd85/is_there_a_way_to_auto_play_all_videos_from_a/

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by litetex** [comment]
Please fill out the template accordingly.

"Create playlist from search results" doesn't sound like a good idea.
Example: User searches for "a" → results in a few million search results...
![grafik](https://user-images.githubusercontent.com/40789489/147829470-bb9cd009-9edd-44fe-b552-4fa1ddd4705f.png)
