### ISSUE TITLE
[bug] "Open in browser" does not work

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#759]
1.open a video
2. go to channel
3. click three dots
4. select "open in browser"
nothing happens

**Comment by Amethystafyy** [comment]
IDK what happend but mine doing fine.

**Comment by teod0r** [comment]
reinstalled the app and rebooted -- nothing helpes

**Comment by teod0r** [comment]
"open in browser" for a video works, but does not work for a channel

**Comment by teod0r** [comment]
downgrading to version 0.9.10 solved the problem

**Comment by coffeemakr** [comment]
Can confirm this bug. I'm working on a fix.
