### ISSUE TITLE
When switching from video player to background play, the video / audio is not synced

### ISSUE THREAD

**Issue by Blest1** [TeamNewPipe/NewPipe#7591]
While using the latest version and the previous version, I noticed that the video and audio is not synced when I switch from video player to background audio player. 

Even when I switch from videos, and go back to the video player from the background player, it is still out of sync. 

This means that the correct video / audio is not playing.

Using Android, version 11

**Comment by opusforlife2** [comment]
Hi, the template is provided so that we don't have to ask people the same questions each time. Please edit your issue and fill it out.
