### ISSUE TITLE
Use system video player without downloading the whole video?

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#7593]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
How do I use Mi Video player for online videos? The option to use external video player asks to open in the browser.

**Comment by litetex** [comment]
> Use system video player without downloading the whole video?

I don't think that is possible.
Video players that are preinstalled can usually only be used for local files.

> The option to use external video player asks to open in the browser.

I think this was done e.g. for other apps that support the links (e.g. the YT app). But I'm not completely sure because I never used that feature.

**Comment by opusforlife2** [comment]
@litetex It's for VLC, mpv-android, etc. Players which can play from a URL.

**Comment by SameenAhnaf** [comment]
>Use system video player without downloading the whole video

I'm not sure what you are asking for. But you can use system video player for streaming videos.

https://user-images.githubusercontent.com/79245641/147875070-78c7140a-fee7-436b-b7c2-e0cd2f60ae2d.mp4
