### ISSUE TITLE
Fix remembered search results

### ISSUE THREAD

**Issue by Etim-Orb** [TeamNewPipe/NewPipe#7597]
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Search for `technoblade`
2. After going back and searching again `technoblade` is not at the top
3. As typed progressively the results inconsistently change based on the entered characters

Let's say I searched for something before and I want to go back to that entry again. For the sake of example I will be using the string `technoblade`. After opening the search field again the result is nowhere near the top where it should be because I just made a search for it. After beginning to type the string to "bring the entry closer to the top" the icon that marks the entry has been searched before changes to a regular result, then changes back and is overall inconsistent

### Actual behavior

The results are inconsistent

### Expected behavior

The results are no inconsistent, the last searched result is on the top, and the icons does not change.

### Screenshots/Screen recordings

<img width=200 src="https://user-images.githubusercontent.com/94188674/147689175-9a480309-07a1-44b5-b489-1d8a8c3c6d05.png" /> <img width=200 src="https://user-images.githubusercontent.com/94188674/147689182-794f3d95-b822-47d9-9ef1-026ea0da1d51.png" /> <img width=200 src="https://user-images.githubusercontent.com/94188674/147689184-51bafe11-dda3-45b6-95c0-409801b69aca.png" /> <img width=200 src="https://user-images.githubusercontent.com/94188674/147689185-b30be762-ab40-4e47-acea-6ece16550d46.png" />

### Device info

 - Android version/Custom ROM version: Android 11, OneUI 3.1
 - Device model: Galaxy A52s 5G

**Comment by litetex** [comment]
Shrunk the images a bit.

I think currently the most searched results are shown at the top.
@Stypox is this working as expected? Or am I missing something.

**Comment by Stypox** [comment]
@Etim-Orb could you provide a list of ordered searches with which we can reproduce the bug?

**Comment by Etim-Orb** [comment]
@Stypox Sorry but what exactly you need me to do?

**Comment by Stypox** [comment]
Oh, obviously this doesn't work, the version with the fix (#7491) has not been released yet... Closing as already fixed, sorry for the confusion
