### ISSUE TITLE
Feature request: Resume from original time after failure to play

### ISSUE THREAD

**Issue by sxmichaels** [TeamNewPipe/NewPipe#760]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=50090160)](https://www.bountysource.com/issues/50090160-feature-request-resume-from-original-time-after-failure-to-play)

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I tend to listen to very long (several-hour) lectures on my phone via NewPipe's popup mode. One thing I've noticed happing frequently is that if I pause a video for quite a while and later resume it, it typically stops playing after a few seconds with a message to the effect of "failed to play video." (Presumably it has lost its streaming connection to Youtube.) This completely loses my place in the video I was watching, and particularly in cases where I am passively listening, I do not always know where to return to.

Is it possible to implement **a feature that saves the current place in a video when it fails to play, and resumes from that place when it is re-opened**? I don't think it would be necessary to save this data for long periods of time or per-video; I suspect that if it was just enough to resume a video immediately after it failed, that would be sufficient in 95% of cases.

**Comment by theScrabi** [comment]
I noticed that to. It might be a considerable issue :)

**Comment by wazateer1** [comment]
I came here to comment this exact thing. If not saving the timestamp, could you at least display the time on the crash screen (and maybe a youtu.be/videoid?t=timeofcrash link to restart it)?

**Comment by rockybulwinkle** [comment]
Same, I'd love to see this feature. I've come to rely on it from Google's YouTube app

**Comment by theScrabi** [comment]
@karyogamy I think you have to claim that bounty:
https://www.bountysource.com/issues/50090160-feature-request-resume-from-original-time-after-failure-to-play
