### ISSUE TITLE
how to use one's personal android Newpipe version on PC 

### ISSUE THREAD

**Issue by cerebos7** [TeamNewPipe/NewPipe#7604]
Hi there

My question is very specific, I will try  to formulate it clearly.

On my PC internet browser, I have a lot of youtube links saved as favourites.
When the titles of the clips are written latin, I usually tape it manually on my phone : I use the research function on newpipe, find the clips and save it on playlists.

However, when the clips titles saved in my PC are not written in latin, I cannot reproduce their name manually on my phone.

That's why I would like to be able to use my own version of newpipe on my pc **so that I can copy the name of the videoclips from YT and paste it on newpipe, projected on PC.** 

I know how to project my phone apps on PC. I did it with Newpipe on half of my PC screen. 
The problem is that the interaction between the Newpipe's projected window and my regular system is limited : my PC mouse can interact with the window projected of Newpipe, I can use my PC keyboard but the copypaste function is not able.

Do you have any idea for my request ? 

Thanks in advance

**Comment by opusforlife2** [comment]
Wow, that sounds like a truckload of effort. Why not copy the video _URLs_ instead of the names? This will avoid the tedious middle step of searching for every video, and open it directly. (You can paste video URLs in the search bar and Newpipe will open them directly.)

From what I understand, your goal is to be able to save YT videos on your PC inside playlists in Newpipe.

So all you need is the ability to copy URLs from the PC to the phone. For this, you can use KDE Connect. When you install it on both your PC and phone, it lets you share the contents of the clipboard between them.

Also, please don't remove the issue template in the future; we've written it up for a reason.

**Comment by XiangRongLin** [comment]
I can recommend https://github.com/Genymobile/scrcpy for a using your phone from you PC. I has a shared clipboard too, with which you can copy from your PC and then paste into your phone.

I personally use it when developing, so I don't have to touch my phone.

**Comment by cerebos7** [comment]
Thanks guys for your replies. Sorry for the templates, I'll be careful next time.

@opusforlife2 yes, I can also copypaste urls, it may be better I didn't.
I've installed kdeconnect and paired my smartphone & PC. However I don't really know what to do know.
I sure can share files from one device to another. Do you suggest that I create a file on my PC (word for example) in which I copypaste all the urls. And then I transfer this word file on my phone ? 

Maybe the solution of @XiangRongLin is more what I seek : project my Newpipe screen on my PC and copypaste there datas from my PC device. Correct me if I'm wrong ?

**Comment by opusforlife2** [comment]
Actually, Xiang's suggestion is better because the work of copying and pasting will become much faster. Try both ways and see which one is more comfortable for you. You'll have to open each video's page in Newpipe either way; that is one step that cannot be avoided.

**Comment by cerebos7** [comment]
That's what I thought. The fastest way I have in mind is having on my PC screen two windows side by side : the one of my PC browser and the one of my NP's projection, and make interactions between the two.

**Comment by opusforlife2** [comment]
Alright. Problem solved, then.
