### ISSUE TITLE
Playlist link for youtube series is not supported

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#7609]
### Checklist

- [x] I am using the latest version - 0.21.15 (see this: [comment] )
I am using the older version - 0.21.13
- [x] I checked 🔍 : [series] , and following is a related (but not duplicate) issue: 
https://github.com/TeamNewPipe/NewPipe/issues/5793
- [x] I have read the [contribution guidelines]
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

[comment]: https://github.com/TeamNewPipe/NewPipe/issues/7609#issuecomment-1007239568
[series]: https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+series+is%3Aopen
[contribution guidelines]: https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md

### Steps to reproduce the bug

1. Go to a channel > playlists > series. That is, channel which have series: like:
    * [3blue1brown]
    * [TedEd]
2. Open any of the series' link in newpipe, like: 
    * [Essence of linear algebra] : SE (episodes) - 3blue1brown
    * [TED-Ed Riddles : Season 1] : SE (episodes) - TedEd 
    * ...  through to "Season 4"

[3blue1brown]: https://www.youtube.com/c/3blue1brown/playlists?view=50&sort=dd&shelf_id=3
[TedEd]: https://www.youtube.com/teded/playlists

[Essence of linear algebra]: https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
[TED-Ed Riddles : Season 1]: https://www.youtube.com/playlist?list=PLJicmE8fK0EhMjOWNNhlY4Lxg8tupXKhC

### Actual behavior

* it shows me this message with a frown face:
```
(ಠ_ಠ)
No videos
```

### Expected behavior
* The playlist should open
* Or atleast a message should be shown that series playlists are not supprted yet
* 'Cz otherwise it looks like a perfectly normal playlist link, 
and person may get confused and feel that newpipe is less reliable

### Screenshots/Screen recordings

![image]

### Device info

 - Android version/Custom ROM version: realme UI V2.0
 - Device model: realme RMX3381

[image]: https://user-images.githubusercontent.com/19423063/147868693-af5175ac-3b1a-49c3-a88d-02a83398f53a.png

**Comment by yashpalgoyal1304** [comment]
3. For investigation, some other series/seasons (SE), and "Learning playlists" (LP) opened fine:
(i tried with playlists which show the episode/video count in the bottom bar in playlist thumbnail, as against in the right side for normal playlists)
    * [There's a Poem for That : Season 1] : SE (episodes) - teded
    * [Myths from Around the World] : SE (episodes) - teded
    * [Think Like A Coder] : LP (videos) - teded
    * [Cells] : LP (videos) - [KhanAcademy]
4. So, like categories in blueish: 1 (normal), 2 (learning), and 3 (??) work, 
    * but red category 4 (??) doesnt work
    * the confusion is that category 3 and 4 look exactly same
![image](https://user-images.githubusercontent.com/19423063/147869991-98ba12c2-76e4-495a-8855-d045ded1ad41.png)


[KhanAcademy]: https://www.youtube.com/c/khanacademy/playlists?view=1

[There's a Poem for That : Season 1]: https://www.youtube.com/playlist?list=PLJicmE8fK0Egxi0hgy5Tw-NFyLcpJ4bzJ
[Myths from Around the World]: https://www.youtube.com/playlist?list=PLJicmE8fK0EjW2AVwcSc4NvGyJJaw7bzh
[Think Like A Coder]: https://www.youtube.com/playlist?list=PLJicmE8fK0EgogMqDYMgcADT1j5b911or
[Cells]: https://www.youtube.com/playlist?list=PLSQl0a2vh4HAMkwzY9aUz8Xam3PGlKLMr

**Comment by yashpalgoyal1304** [comment]
And entering in the scope of other issue:
* the Category 1 (normal), and 2 (learning/videos) are searchable but
* the Category 3, & 4 (??/episodes) are NOT searchable

**Comment by yashpalgoyal1304** [comment]
Summary:

| Category | Appearance <br/> of thumbnail | Links in Npipe | Search in NPipe |
| -- | -- | :--: | :--: |
| 1. Normal P | * video count on right | v | v |
| 2. Learning P | * video count on bottom <br/> * have a special label | v | v |
| 3. Se--?? | * episode count on bottom | v | x |
| 4. Se--?? | * episode count on bottom | x | x |

**Comment by yashpalgoyal1304** [comment]
(i am on the last version as i didnt like the changes in v0.21.4)

**Comment by opusforlife2** [comment]
> (i am on the last version as i didnt like the changes in v0.21.4)

Regardless of what version you use, you need to reproduce the issue in the latest version for it to be actionable.

**Comment by yashpalgoyal1304** [comment]
i agree with that, but this issue is very easy to test. i thought that at least someone from community (not saying from team) will post their "Reproduction report" here.... but seems that's not the case on this tracker.

**Comment by BrightDV** [comment]
- [x] I am using the latest version - 0.21.15

### Steps to reproduce the bug
- Open with NewPipe [this serie link (Essence of linear algebra, as written before) ](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab).  Same for [TED-Ed Riddles : Season 1](https://www.youtube.com/playlist?list=PLJicmE8fK0EhMjOWNNhlY4Lxg8tupXKhC)

### Actual Behavior
 
- If you open the link by clicking on it, this notification will appear and ~5 seconds after disappear, without NewPipe opening it.
<img src="https://user-images.githubusercontent.com/92821484/148517934-e5a4f4c7-6428-46e2-b526-b7c1edaddacc.png" height="100">


- If you open the link by pasting it in NewPipe directly, it will show a blank screen.
<img src="https://user-images.githubusercontent.com/92821484/148517625-621ec63c-e35f-441f-bbc1-90416757d096.png" height="400">

**Comment by opusforlife2** [comment]
> but this issue is very easy to test 

Then why not do so? 🤦 All you need is a database import and you have a duplicate Newpipe ready to test.

**Comment by yashpalgoyal1304** [comment]
> a duplicate Newpipe ready to test.

how duplicate?? that will override my existing newpipe. such type of testing is much easier done on windows, but for android, i dislike the fact that you cant do it without using some good trickery

**Comment by yashpalgoyal1304** [comment]
> someone from community will post their "Reproduction report" here with latest version.... 

how about having a label like "need reproduction on latest"

**Comment by opusforlife2** [comment]
> won't that override my existing newpipe??

Huhuhuhu... No. 😈 

> some good trickery

Hah. Our trickery is the best.

**Comment by yashpalgoyal1304** [comment]
the horn-y emoji says it all lo. anyways, this is offtopic now. i dont think it's good to have this talk here. will hide and self mark mine as OT

**Comment by opusforlife2** [comment]
@yashpalgoyal1304 Pfffft. I was actually serious. You can install PR APKs side by side with the release version. It's been this way for over a year.

Anyway, even if you don't trust this, you can just take a database backup before messing around.

**Comment by mhmdanas** [comment]
@opusforlife2 yes, PR APKs, but not release APKs. Be careful.
