### ISSUE TITLE
Is there any guide or explain of this app or how it work?

### ISSUE THREAD

**Issue by Amethystafyy** [TeamNewPipe/NewPipe#761]
Hi, first i wana thank you for your incredible works for this app :) 
And recently i'm doing a homework related to building a youtube client and i found you :)
As the title, is there any guide expain how the code working, especially the java classes? I'm like a salt in the sea and the code like jungle to me......... 
Thank you so much :)
English is not my mother tongue, sorry for any mistake.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
Hello, well sadly there is no documentation so far, but you can use [np-cli](https://github.com/teamnewpipe/np-cli) as an example how to build a simple youtube app.
The core of newpipe, meaning the parts u use of getting the information is [NewPipeExtractor](https://github.com/teamnewpipe/newpipeextractor). So embedded this library into your project.

**Comment by gkeegan** [comment]
This fixes the issue: https://github.com/TeamNewPipe/documentation

**Comment by theScrabi** [comment]
https://teamnewpipe.github.io/documentation/
