### ISSUE TITLE
Add SponserBlock to NewPipe.

### ISSUE THREAD

**Issue by Mesum-Hussain** [TeamNewPipe/NewPipe#7611]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Please add [SponserBlock](https://github.com/ajayyy/SponsorBlock) to NewPipe like [YouTube Vanced](https://github.com/ajayyy/SponsorBlock) did.

#### Why do you want this feature?

It saves the viewers from annoying sponsored segments baked into the videos they are watching and would save hours compiling all the time saved.

**Comment by SameenAhnaf** [comment]
Rejected by devs. See: https://github.com/TeamNewPipe/NewPipe/pull/3205

**Comment by Mesum-Hussain** [comment]
> Rejected by devs. See: https://github.com/TeamNewPipe/NewPipe/pull/3205. You may use [Newpipe Sponsorblock](https://github.com/polymorphicshade/NewPipe)

Thanks 👍🏻

**Comment by eternal-sorrow** [comment]
Is it possible to implement this feature, but hide this setting in some kind of "advanced settings" and also warn users about ethical and privacy concerns when enabling this feature?

**Comment by Mesum-Hussain** [comment]
> Is it possible to implement this feature, but hide this setting in some kind of "advanced settings" and also warn users about ethical and privacy concerns when enabling this feature?

You can use [Newpipe Sponsorblock](https://github.com/polymorphicshade/NewPipe). It's working fine in my opinion. Have been using it for a while.

**Comment by eternal-sorrow** [comment]
I know about this project. It's good, but it would be better to have this feature in the main app.

**Comment by Mesum-Hussain** [comment]
> I know about that project. It's good, but it would be better to have this feature in the main app.

Would be better but probably never going to happen. The maintainers are strictly against it.

**Comment by eternal-sorrow** [comment]
>The maintainers are strictly against it.

Well, that's too bad. I understand their concerns, but it's still not a reason not to add this feature. User should have a choice. The app may inform the user about these concerns, but the choice should be ultimately given to the user.

And no, the fork is not a good solution. Using the fork instead of the main app has its own problems.

**Comment by voxrie** [comment]
> > The maintainers are strictly against it.
> 
> Well, that's too bad. I understand their concerns, but it's still not a reason not to add this feature. User should have a choice. The app may inform the user about these concerns, but the choice should be ultimately given to the user.
> 
> And no, the fork is not a good solution. Using the fork instead of the main app has its own problems.

There should be a poll on this subject! This decision should be with the users as you said. If the developer team is reading this please make it happen.
