### ISSUE TITLE
Where is the fullscreen button?

### ISSUE THREAD

**Issue by AlexMiniReal** [TeamNewPipe/NewPipe#7615]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Where is the fullscreen button?

#### Additional context

**Comment by SameenAhnaf** [comment]
See: https://github.com/TeamNewPipe/NewPipe/issues/4478

**Comment by litetex** [comment]
Closing as duplicate
