### ISSUE TITLE
Checkbox that adds -channel name- to [download context GUI] -> file name   (organisation optimisation)

### ISSUE THREAD

**Issue by Plugdemholes-Imeanpatchdembugs** [TeamNewPipe/NewPipe#7616]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

A checkmark box added to the **download context GUI** that automatically extends the _**file name**_ by a "by -channel name-" after the original **_video title / file name_**.

#### Why do you want this feature?

I've notice though for most channels, one can/could retrospectively very easily add the creators channel name to the video to avoid confusion, there are channels, that stop uploading and/or have less recognizeable features from the creator (no voiced narration, 3d animation projects that use stock assets for example) and since all video downloads currently end up in the same folder, one needs to dump the videos regularly from the device to avoid confusion.
As another example, I download dance routines and not all channels have water marks in their videos and/or the background as well as faces are not as recognizable to me as hearing a voice, which you usually don't hear in these videos. 

This could extend the usefulness of the **download context GUI** for as long as _individual download folders for channels_ aren't an option in the **download context GUI**.

Happy new year 2022! :)
That's all.

**Comment by SameenAhnaf** [comment]
It should be closed in favor of https://github.com/TeamNewPipe/NewPipe/issues/2282
