### ISSUE TITLE
Add subscription folders

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#762]
- [✔️ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [✔️ ] I checked if the issue/feature exists in the latest version.

I don't want to bundle all my subscriptions together. It would be nice to filter subscriptions in folders like music, tech, creepypastas, news, animation, etc.

**Comment by Stypox** [comment]
Closing in favour of #1725
See pull request #2309
