### ISSUE TITLE
When switching to background player or pop up player video plays from starting

### ISSUE THREAD

**Issue by Isssuemaker** [TeamNewPipe/NewPipe#7623]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

###

When switching to background player or pop up player video plays from starting

Excepted Behaviour: Video plays from where it is paused

### Device info

 - Android version/Custom ROM version:10
 - Device model: Gionee Max

**Comment by pc00per** [comment]
Pinned issue. Duplicate of #7427.

**Comment by TiA4f8R** [comment]
Please follow the template and its compulsory checklist and check for duplicates the next time you open an issue. Indeed, that's a duplicate of #7427, a pinned issue. Thank you.
