### ISSUE TITLE
Tap video length to toggle playback countdown

### ISSUE THREAD

**Issue by pc00per** [TeamNewPipe/NewPipe#7626]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Tapping progress bar video length (right corner) to toggle countdown for playback remaining time.

#### Why do you want this feature?

Useful while listening to hourly podcasts. Easier to implement too in my opinion.

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7207

**Comment by pc00per** [comment]
> Duplicate of #7207

Oh, okay. Title was different. So I couldn't search it down for duplicates.
