### ISSUE TITLE
Debugging Souncloud tab

### ISSUE THREAD

**Issue by AbduAmeen** [TeamNewPipe/NewPipe#7629]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

0. Clone the project
1. Build the project
2. Open the application and navigate to the soundcloud tab
3. Try to load any internet content

### Actual behavior

Network Error screen

### Expected behavior

Internet content should load as normal

### Logs

2022-01-02 15:40:28.577 13990-13990/org.schabi.newpipe.debug E/class org.schabi.newpipe.error.ErrorActivity: javax.net.ssl.SSLHandshakeException: Chain validation failed

### Device info

 - Android version/Custom ROM version: Android 12
 - Device model: Pixel 5 API 31 Emulator

**Comment by litetex** [comment]
Tried to reproduce the bug but works as expected on my machine.

> 2022-01-02 15:40:28.577

Is this some old log?
If your phone/emulator has the wrong time maybe https://stackoverflow.com/a/57304450 helps.

**Comment by AbduAmeen** [comment]
It seems like that fixed the issue. Thanks
