### ISSUE TITLE
Add advanced search

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#763]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Currently, YouTube allows you to specify things like length of video (limited though), whether it's 3d, HD, sort by relevance, view count, and plenty more options. Would it be possible to integrate this into NewPipe's search?

**Comment by theScrabi** [comment]
Yes

**Comment by wb9688** [comment]
@theScrabi: How will we do that? Not every service supports the same
filtering options and if we just make a generic filtering interface and
implement it for every filtering option available in a service, we have the
same translation problem as with the kiosk.

**Comment by theScrabi** [comment]
Wed have to make the services tell the UI what sorting options it does offer.

**Comment by phly95** [comment]
well, something that would be useful would be to offer searching through tags and topic pages, which youtube itself doesn't offer, but using the hidden tags in the page source of the videos could result in a slow, but effective search, unless of course, the reverse engineered search API already has options like that, making it less demanding of a search.

**Comment by coffeemakr** [comment]
Is related to #110
