### ISSUE TITLE
Slow initial video buffer

### ISSUE THREAD

**Issue by pc00per** [TeamNewPipe/NewPipe#7630]
### Checklist

- [x] I am using the latest version - 0.21.15.981 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Start playing random unopened videos

### Actual behavior
Initial loading time of an unopened video is too high.

### Conditions while reproducing the bug
1. Default video format = webm/240p
2. Internet speed is 100Mbps
3. No issues in the device & it's OS.

### Expected behavior
Videos should start playing instantly.

### Screenshots/Screen recordings

[Here's the screen recorded proof.](https://youtu.be/9Ld63Br4aR0) 

### Logs

Not generated. I could verbose log, if been asked.

### Device info

 - Android version/Custom ROM version: 11/crDroid 7.13/4.14.190 perf
 - Device model: Redmi Note 10/sunny/mojito

**Comment by mhmdanas** [comment]
Please fill your NewPipe version in the first checklist item.

**Comment by pc00per** [comment]
> Please fill your NewPipe version in the first checklist item.

Edited. It's latest version btw.

**Comment by foreignmeloman** [comment]
I upvote this issue.

**Comment by shom13** [comment]
I was about to open a new issue, but found this one. I agree it takes a while for videos to load initially, which is not a desirable behaviour

**Comment by karyogamy** [comment]
Hi @pc00per @foreignmeloman @shom13, 
Please test fix #7919 and let me know if it works for you.
The apk can be found by going to https://github.com/TeamNewPipe/NewPipe/pull/7919/checks, click on CI on the left, and scroll down to Artifacts.
NOTE you need to enable the fix by going to Settings -> Video and audio -> Playback load interval size -> choose a small value (e.g. 16 KiB).

**Comment by foreignmeloman** [comment]
@karyogamy I'm using the latest build (v0.22.0) and yet there is no such option in the settings
![Screenshot_20220225-130037](https://user-images.githubusercontent.com/11769352/155686909-e5dbb462-768d-41e7-836e-a5ffd75520d6.jpg)

**Comment by shom13** [comment]
@karyogamy sorry for late update, but after testing extensively with the new setting its got a lot better than before. The stream starts as expected. Thank you so much

**Comment by karyogamy** [comment]
@foreignmeloman You'd have to install a test build instead of v0.22.0 by going to https://github.com/TeamNewPipe/NewPipe/pull/7919/checks, click on CI on the left, and scroll down to Artifacts. 

@shom13 Thanks for testing! Have you experienced any side effects with lower values, for example, more frequent buffering? Could you also post your internet speed? Would be interested to see how this works with slower network.

**Comment by shom13** [comment]
@karyogamy no i have not encountered any buffering issues with lower value, tested with 16kb settings. I could test with lower settings if that would help, do let me know. And my broadband speed is 75Mbps to be precise.

**Comment by karyogamy** [comment]
Do you notice any difference between 1kB vs 16kB? If not, might be best to just drop one of them from the selection.

**Comment by shom13** [comment]
I dont particularly notice much difference between the two, but with 1kb it seemingly loads a bit faster, the difference is minimal though. But given the choice i would prefer 1 over 16. I will post after testing a bit more, this is based on a just a very short test.

**Comment by shom13** [comment]
After going through enough videos, 1kb seems a touch faster than 16, but the difference is negligible to none.

**Comment by foreignmeloman** [comment]
@karyogamy thanks for the instructions. After installing the build I can confirm that 16 KiB setting greatly improves the load time.

**Comment by pc00per** [comment]
@karyogamy I've tested #7919 & it solved the buffer issue. The current default ExoPlayer interval has some issues. But after switching to (any) interval value you had in the list, worked out well. The issue could be something related to ExoPlayer, not the internet.

**Comment by karyogamy** [comment]
Thanks for testing guys, and sorry I forgot a big caveat: the player has cache enabled all the time. 
So if you have been using the same video or previously watched video in the test, then it's probably using the cached video instead of loading a new one, and that could be why all the settings had the same load time for @pc00per.
If you've been testing with new videos only, then it is still good.

**Comment by shom13** [comment]
@karyogamy I have been testing with new videos, not previously watches or played ones. So cache should not have been a problem in my case.

**Comment by pc00per** [comment]
v0.22.2 still did not include the fix of this closed issue...

**Comment by shom13** [comment]
Initial load buffer will be fixed with version 0.23 as its out for testing, hopefully will be released very soon. https://github.com/TeamNewPipe/NewPipe/pull/8231

**Comment by sleeply4cat** [comment]
0.23.1 is still insanely slow

**Comment by pc00per** [comment]
> 0.23.1 is still insanely slow

Incomplete info. Slow where? Buffering, UI, UX ?

**Comment by sleeply4cat** [comment]
> Slow where? Buffering, UI, UX ?
Initial page load and video buffering may take several minutes.

**Comment by pc00per** [comment]
> > Slow where? Buffering, UI, UX ?
> 
> Initial page load and video buffering may take several minutes.

No issues here. Try resetting newpipe.
