### ISSUE TITLE
Show UI via settings

### ISSUE THREAD

**Issue by Gitaroony** [TeamNewPipe/NewPipe#764]
-  [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I've been using Newpipe for a while, firstly because of its minimal UI and no crowded home screens, such as trending, popular, recommended etc. like other apps.

But I realize that slowly more and more features will be added such as subs, fav/bookmarks, history, etc..

I find all those features to be a nice addition, but would still love my newpipe start screen to be as minimal as  possible.

Would it be possible then to add UI changes to the settings menu under a UI category?

So for example, ALL UI tabs or features could initially be hidden, and if one wants just a Favorites tab, then it can be checked in the UI settings to unhide it, or if one wanted all features showing, then they could just check all to unhide.

This is especially a nice feature is one wanted to use newpipe on a kids tablet instead of yt or even yt kids..

Thanks for a great app!

**Comment by theScrabi** [comment]
All right I'll keep that in mind.
However [this](https://github.com/TeamNewPipe/NewPipe/pull/732) pull request will add a front page, tho it will also give you the option to bring back the old BlackPage.
