### ISSUE TITLE
TikTok for NewPipe Extractor

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#7645]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
So lately I came across the fact that I may want to follow the one or the other TikTok channel. However just like with the YouTube App I have little Interest to install the original one. So why can't NewPipe support TikTok? Well I guess the UI is not really TikTok friendly. It is more or less made for YouTube. However the exctractor does not care. So I could imagine first adding TikTok support to the extractor and then write a really basic App like "PipPop" or ... "PipeTok" that only shows the TikTok extractor and behaves TikTok like?
What do you think? I guess I'd be willing to pay some money for a proper implementation in the extractor.

#### Why do you want this feature?
I want to watch some TikTok videos.

**Comment by SameenAhnaf** [comment]
Rejected by devs. See: https://github.com/TeamNewPipe/NewPipeExtractor/issues/695. You may have a discussion there.

**Comment by theScrabi** [comment]
So here you go. The TikTok extractor of yt-dlp:
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/tiktok.py

760 lines of code, and access to an api. (I don't know if a token is required). Also extractor seems to change a lot, because tiktok changes oftenly, but still I'd try this :)

**Comment by opusforlife2** [comment]
> PipPop

I'm dying.

**Comment by the4anoni** [comment]
I'm seconding this. Having tiktok in app which just doesn't collect as much data as original app is good idea.

**Comment by opusforlife2** [comment]
This issue doesn't belong here. Please comment in https://github.com/TeamNewPipe/NewPipeExtractor/issues/695 instead.
