### ISSUE TITLE
Full-screen doesn't fill bottom half of screen on Android 12

### ISSUE THREAD

**Issue by EthanZeigler** [TeamNewPipe/NewPipe#7655]
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to any YouTube video, any resolution 
2. Press the full screen button

### Actual behavior
Full screen is "smushed" to the top section of the screen. Opening and closing full screen repeatedly will eventually stop the issue. 

### Expected behavior
Video fills screen

### Screenshots/Screen recordings

![Screenshot_20220114-131353.png](https://user-images.githubusercontent.com/9123320/149565752-b13002d7-23ac-49ac-8fa1-3e414fd95792.png)

![Screenshot_20220114-131353.png](https://user-images.githubusercontent.com/9123320/149591836-2fe5d278-47fd-4521-961b-212b6d7dbf6b.png)

### Logs

N/A
### Device info
- Android 12
- Update October 5, 2021
- Pixel 3

**Comment by litetex** [comment]
#7262

**Comment by EthanZeigler** [comment]
@litetex apologies. I did search quite a bit for an existing issue since I thought there was no way it wasn't documented. Guess it slipped past me.

**Comment by litetex** [comment]
@EthanZeigler No problem it happens 😄
