### ISSUE TITLE
HD channel art fetch for Channel overview page

### ISSUE THREAD

**Issue by Feuerswut** [TeamNewPipe/NewPipe#7656]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

_This is a small fix/enhancement._
**HD channel art fetch for Channel overview page. (YouTube extractor)**

#### Why do you want this feature?

NewPipe currently extracts YouTube channel art at extremely low quality,  the preview (on a channel preview page) looks pixelated.

NOTE: HD channel art seems to be fetched and shown in a search (using the search tool in the results) or in the comment section 
-> everything there works properly. 
This is NOT the case on the channel page (e.g. after clicking on a channel in the comments/search; look at the image in the upper right corner).

This can be fixed in the following way:
- Keep the current extreaction method.
- Try fetching the HQ image using either an existing method, or truncate the image url from this:

https://yt3.ggpht.com/ytc/AKedOLTU70U7Q6PAhn2C7Wght2Zi7ZZbQzBQHB-XXXXXXX=s100-c-k-c0x00ffffff-no-rj

to this

https://yt3.ggpht.com/ytc/AKedOLTU70U7Q6PAhn2C7Wght2Zi7ZZbQzBQHB-XXXXXXX

_provided that you have the url_
(e.g. truncate anything after the '=' char.)
Note: example url, NOT functional

_A plain browser displays the 2nd url-image without issue._

**Comment by Balaklks** [comment]
Any updates to this?
