### ISSUE TITLE
Add option to show tabs in home page on bottom of screen

### ISSUE THREAD

**Issue by blaze-107** [TeamNewPipe/NewPipe#7658]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Make the Menu Panel on bottom.
Search bar easy acces on bottom corner.

#### Why do you want this feature?
 want a better ui

**Comment by mhmdanas** [comment]
I'm not sure I understand your request; could you please provide screenshots?

**Comment by dude-shah** [comment]
> I'm not sure I understand your request; could you please provide screenshots?

![IMG_20220115_213459.jpg](https://user-images.githubusercontent.com/63038690/149629787-9525a291-dea5-49af-ae56-e8d1ff9efd1b.jpg)

Can you make the menu panel from to bottom and also allow the users to choose ui color (white marked area in screenshot)

**Comment by mhmdanas** [comment]
> Can you make the menu panel shift to bottom(blue marked in screenshot)

That makes sense, thanks for clarifying.

> also allow the users to choose ui color (white marked area in screenshot)

This has been suggested before and rejected, see https://github.com/TeamNewPipe/NewPipe/issues/6272.

**Comment by Marius1501** [comment]
I would work on this feature.
