### ISSUE TITLE
Playback speed for live videos

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamNewPipe/NewPipe#7664]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

If the user is watching a live video and if playback speed is larger than one, then play the live video at 1x speed.

#### Why do you want this feature?

I normally have my playback spees higher than 1. Currently I have to manually select the speed every time for live feeds.

**Comment by litetex** [comment]
What is a "live video" or "live feed"? Do you mean a live-stream? 
If you mean a live-stream: You can't watch a live-stream with another playback speed then 1x because it's live.

**Comment by SameenAhnaf** [comment]
@litetex That is unfortunately not the current scenario in case of live stream.
https://youtu.be/rsk4DlxmihQ

**Comment by litetex** [comment]
Closed in favor of #7664
