### ISSUE TITLE
Can't re-watch live stream from the beginning, only from the moment I joined in

### ISSUE THREAD

**Issue by Vrihub** [TeamNewPipe/NewPipe#7665]
### Checklist

- [x] I am using the latest version - 0..21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. A live stream has already started, you begin watching it
2. The stream ends, the video is kept available on the youtube channel for re-watching it
3. You try to re-watch the video from the beginning

### Expected behavior

I expect being able to re-watch the entire video.

### Actual behavior

I am only able to re-watch the video from the point I started watching it during the live streaming, not from its very beginning.

I tried switching to another channel, re-loading the channel, letting the video re-play until the end, force-stopping the newpipe app. No way.

Interestingly, in the video list view, the correct time for the video is displayed in the lower-right corner of the video thumbnail image (i.e. the duration of the whole live stream), but however I try to play it, it always starts playing from the moment that I originally joined the live stream.

I guess that maybe disabling the "Resume playback" and/or using the "Clear watch history" options could provide a workaround for this bug, but I haven't tried them, because I don't want to lose the playback position info for all my other videos. It could be very convenient to have an option to forget about the playback position just for an individual video.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: Samsung phone

**Comment by Vrihub** [comment]
Ok I tried on another device, on which I hadn't watched the live stream. The advertised video length is still correct (about 7 hrs), but newpipe only let me watch exactly the last 4 hours of the video. It seems there's a hard-wired limit for video duration?

BTW I can watch the whole video in the youtube app and website, so it's not a problem with this particular video.

**Comment by Stypox** [comment]
Unless further information is provided, this issue will be closed, since many things have changed about livestreams lately and you @Vrihub still haven't provided an example

**Comment by mujehoxe** [comment]
Most live streams has these limits, for instance this following video on the youtube website i can go back to up to 12 hrs while i can only get 1 hr on new pipe.
https://www.youtube.com/watch?v=jfKfPfyJRdk

**Comment by AudricV** [comment]
This issue has been solved since 0.23.1. You just need to clear metadata in cache, close the stream (not only stop its playback from the notification, but close it from the mini player for instance) and launch it again or restart the app.

@mujehoxe Unfortunately, this is quite hard to do, as it would require us to create custom live DASH manifests (or intercept or fake responses) and several custom ExoPlayer components (the HLS manifest of the iOS YouTube app is used). Help is really appreciated for this feature, which is not related to this bug.
