### ISSUE TITLE
Option to remove watched videos.

### ISSUE THREAD

**Issue by clicky6** [TeamNewPipe/NewPipe#7666]
Add an option to remove watched videos show that they don't show anywhere.

**Comment by litetex** [comment]
@clicky6 
Can you please fill out the issue according to our https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/feature_request.md AND check if there is already an issue for this feature?

**Comment by clicky6** [comment]
I have checked and found no issue on this feature.

**Comment by opusforlife2** [comment]
You still need to fill the template. Removing it is not an option.
