### ISSUE TITLE
Show download screen after giving permissiom

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#767]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Currently when I install NewPipe and press download for the first time, it asks for permission, but doesn't open the download screen, instead I've to press the download button again, which is slightly annoying and probably easy to fix.

**Comment by theScrabi** [comment]
Yea could be done :) Wed have to listen to a callback there.

**Comment by TobiGr** [comment]
Fixed
