### ISSUE TITLE
Unrecoverable player error occurs! 

### ISSUE THREAD

**Issue by iTzMAS** [TeamNewPipe/NewPipe#7675]
When you tap the full screen button on the pop-up mode it opens the app and tries to go to full screen but it fails and gets stuck in a weird way with a notice saying that "unrecoverable player error occurred"! 

### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Play any video in pop up mode, then press the icon with the square on it to go to the full screen player. 

### Actual behavior

App locks down in horizontal mode and you can't do anything and it says "unrecoverable player error occurred" 

### Expected behavior

App should play the video in mini mode without glitching

### Screenshots/Screen recordings

Recording in the reddit: 

https://www.reddit.com/r/NewPipe/comments/s9fza2/why_does_it_do_this_when_i_come_back_to_app_from/

### Device info

 - Android version/Custom ROM version: android 11/miui 12.5.5.0 global (RKHMIXM) 
 - Device model: poco F3 (alioth)

**Comment by litetex** [comment]
Works as expected on my phone.

Video that was viewed: https://www.youtube.com/watch?v=UOUF70E8VeQ

**Comment by mascraft** [comment]
As I said in the template I'm using the last version 0.21.15.

**Comment by opusforlife2** [comment]
@mascraft "x.xx.x" is not the latest version. You're supposed to replace that so that we are assured you double checked your version before possibly opening an already redundant issue.

**Comment by mascraft** [comment]
Oh my bad, it's my first time trying to report a bug in here so I didn't know I had to use that, should I send my bug report again? What do I have to do?

**Comment by litetex** [comment]
>Oh my bad, it's my first time trying to report a bug in here so I didn't know I had to use that, should I send my bug report again? What do I have to do?

Editing the issue - which you already did - is perfect 👍

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?
