### ISSUE TITLE
Video Description Links broken

### ISSUE THREAD

**Issue by eLement87** [TeamNewPipe/NewPipe#768]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hi Guys,

i've updatet NewPipe from 0.9.8 to 0.10.0 last Week. And from now on im won't be able to open a Link from the Video Description.

It seems the link is cut off and shall not correctly committed to the Browser. It is fair to say that the link is cut of by the showed dots. I know that the three Dots are indicators und truncate the whole, but i think there are not operate correctly.

Thanks and have a nice Sunday ;)
eLement87

![screenshot_20171015-145338](https://user-images.githubusercontent.com/1385582/31585063-12b8bbaa-b1bb-11e7-9927-de4666b35052.png)

**Comment by theScrabi** [comment]
As long as I know we removed that function. Due to problems with timestamp links.

**Comment by TobiGr** [comment]
Fixed in a previous release. works with 0.14.2
