### ISSUE TITLE
Copy the urls or all videos in a playlist

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamNewPipe/NewPipe#7680]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I would like to bulk download an entire playlist. Since these are local and private to newpipe, this is not easily done. I am willing to use another program to handle the bulk downloading, but I need all the urls.

#### Why do you want this feature?
 
Videos can be deleted from youtube. For some videos an offline version is nice.

**Comment by Donkey-Doug** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/1788

**Comment by SameenAhnaf** [comment]
I think, sharing the playlist to Snaptube app will be a lot better for you. It doesn't require Google login and will save you a lot of clicks.


https://user-images.githubusercontent.com/79245641/150625891-389323b8-b1b0-4a89-860b-fd26c842a121.mp4

**Comment by Donkey-Doug** [comment]
But what about my personal playlists? There is no share button.
