### ISSUE TITLE
2 weird placed pixels on background player tab

### ISSUE THREAD

**Issue by Fawaytish** [TeamNewPipe/NewPipe#769]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Not really a big deal but there are 2 weird placed pixels on the background player tab. I marked them by a red circle on the screenshot. EMUI 4.0 navbar, honor 4C, android 6.0

![screenshot_2017-10-16-17-56-48](https://user-images.githubusercontent.com/25621690/31622571-14b9e90a-b29d-11e7-9285-17172be15cff.png)

**Comment by theScrabi** [comment]
xD that is the infotext.

![screenshot_20171018-113717](https://user-images.githubusercontent.com/1891273/31711636-1acd7c6e-b3f9-11e7-87c2-92c6788834a4.png)

**Comment by Fawaytish** [comment]
Lol, poor emui users.

**Comment by theScrabi** [comment]
Well ...

**Comment by theScrabi** [comment]
Android secmentation fuu...
