### ISSUE TITLE
Captions not working for age-restricted videos

### ISSUE THREAD

**Issue by x9a** [TeamNewPipe/NewPipe#7698]
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any age restricted video
2. Check for captions, none appear
3. Check the video through browser, captions appear to be working there

### Actual behavior

Captions do not work for age restricted videos.

### Expected behavior

Captions should work on age restricted videos

### Note
 I only tested this on videos with auto-generated captions since I couldn't find an age restricted video with normal ones.

**Comment by x9a** [comment]
> Does this issue also occur on non-age-restricted videos?

No.

**Comment by TiA4f8R** [comment]
Does the APK of #6537 fixes the issue? In the corresponding extractor PR, I removed the check which disables the extraction of subtitles if the content is age-restricted (see https://github.com/TeamNewPipe/NewPipeExtractor/pull/663/files#diff-e07bd9a3dfb657e0ac68c2847533825c0c25d9cc8486c9a5a0dab1d413d54d42L551).

**Comment by x9a** [comment]
> Does the APK of #6537 fixes the issue? In the corresponding extractor PR, I removed the check which disables the extraction of subtitles if the content is age-restricted (see https://github.com/TeamNewPipe/NewPipeExtractor/pull/663/files#diff-e07bd9a3dfb657e0ac68c2847533825c0c25d9cc8486c9a5a0dab1d413d54d42L551).

Yeah this apk appears to be working without that issue.

**Comment by TiA4f8R** [comment]
Ok, because I focused the new delivery methods extractor PR on its topic, I separated this fix in a new PR: TeamNewPipe/NewPipeExtractor#829. You can test it by using the APK in this pull request.
