### ISSUE TITLE
Layout issue with fab button & Wrong info bar behaviour

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#77]
Hello there,
1. I have a problem make the InfoBar behave right when playing a video via PlayVideoAcitivty. 
   [getWindow().setFlags()](https://github.com/theScrabi/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/PlayVideoActivity.java#L257) inside [hideUi()](https://github.com/theScrabi/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/PlayVideoActivity.java#L246), does not only hide the InfoBar, but also the notification drop down if its open, and this is rather annoying. If I remove the function, InfoBar does not hide when hideUi() is called. I am not able to get this fixed. Maybe someone has an idea how to solve this problem :)
2. The footer view of the content of [FragmentVideoItem](https://github.com/theScrabi/NewPipe/blob/master/app/src/main/res/layout/fragment_videoitem_detail.xml#L196) is there so that the [fab button](https://github.com/theScrabi/NewPipe/blob/master/app/src/main/res/layout/fragment_videoitem_detail.xml#L204) is not floating on top of the content itself. However the layouting is not very good. Sometimes this button still floats on top of content. But i'm not able to find a way to get this fixed. @darkon5 since you were working on that layout already, could you try to fix that?

**Comment by JasperWeiss** [comment]
I see what you mean now, with youtube the notification drawer stays open regardless of the infobobar auto hiding after 3 seconds.
I'm not a programmer myself but you could probably have a look at vlc media player's code

**Comment by theScrabi** [comment]
hm... i see. I'll take care if i find time to do it.
