### ISSUE TITLE
Mudança 

### ISSUE THREAD

**Issue by Matheus8988** [TeamNewPipe/NewPipe#7701]
Oi! Seria legal adicionar uma função onde pode criar uma conta anônima ou conta real pará a pessoa decidi se que colocar a conta real (seria legal também quando for adicionar for possível adicionar uma conta poderia ter uma função onde você pode transferir suas informações do da conta tipo histórico, inscrições e tudo do YouTube)

**Comment by mhmdanas** [comment]
Translation:
> Hi! It would be nice to add a function where you can create an anonymous account or real account for the person to decide if I want to put the real account (it would also be nice when adding it is possible to add an account there could be a function where you can transfer your information from the account type YouTube history, subscriptions and everything)

---

YouTube login will probably not be added. From https://newpipe.net/FAQ/bugs/#bugs-google-login:

> NewPipe's goal is to as effectively as possible protect its user's privacy. This means, the app only sends information to external servers which is needed to view search results or watch videos.
>
> Having said this, the developers of NewPipe hope it is understandable that they will not implement any form of authentication which might allow tracking a user.

Also, you can transfer subscriptions at the moment, see https://newpipe.net/FAQ/tutorials/import-export-data/#import-youtube. Importing other things isn't supported at the moment though.
