### ISSUE TITLE
Update youtube subscriptions import instructions for .csv files

### ISSUE THREAD

**Issue by chrisbeardy** [TeamNewPipe/NewPipe#7705]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

- Go to subscriptions -> import from Youtube.
- instructions show to download and extract the .json file.
- The susbscriptions are actually now a csv file, (which NewPipe imports just fine)

**Comment by mhmdanas** [comment]
They mention CSV on my side (I checked with English and Arabic). It's possible the language you use with NewPipe didn't have that text updated to match the new behavior yet. What language do you use with NewPipe?

**Comment by chrisbeardy** [comment]
i downloaded newpipe from the f-droid store. And have not changed the language. I am in the UK, I cant actually see anywhere on the app where I can change language. 

I'm running version 0.21.15, which is the latests from the f-droid store I can see

Screenshot of text I see:

![image](https://user-images.githubusercontent.com/20585410/151074526-dbfa2199-1f8c-46d7-8dda-1b5f0c355272.png)


If I'm looking in the right place (app/src/main/res/values-en-rGB/strings.xml), this appears to be text?

Maybe all the strings.xml files for each language need updating?

**Comment by mhmdanas** [comment]
> I cant actually see anywhere on the app where I can change language.

You can do that from Settings > Content > App language.

> Maybe all the strings.xml files for each language need updating?

Not sure I understand you. Could you clarify?

Anyway, I updated the string for English (United Kingdom), so I'm closing this issue. If anybody else finds outdated strings and wants to update them, follow the instructions in https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#translation.
