### ISSUE TITLE
[Desync audio/video] Audio ahead of the video

### ISSUE THREAD

**Issue by OilSubjectLoss7** [TeamNewPipe/NewPipe#7708]
I'm using the latest version

### Steps to reproduce the bug

I downloaded an hour long video in mp4 480p format with an audio m4a

### Actual behavior

Desync audio, it's ahead of the video

### Expected behavior

Normal video

**Comment by mhmdanas** [comment]
Please don't remove parts of the template at your discretion. I wouldn't have had to ask you about the version if you had filled it properly.

1. You said you're using the latest version, but can you specify it please?
2. Can you share a link to the video?
