### ISSUE TITLE
'Open in web browser' instead of playing the video

### ISSUE THREAD

**Issue by DrRoetker** [TeamNewPipe/NewPipe#7713]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

The bug started after updating my CalyxOS to android 12. Downgrading my version of NewPipe fixed it. The bug was: I received a list of of possible resolutions. After choosing a resolution the menu would try to redirect me to opening the video in the browser on YouTube.
Update: bug now also shows up in downgraded version of NewPipe (see screenshot)

### Expected behavior

Playing the video in the NewPipe application without a resolution menu.

### Screenshots/Screen recordings

<img src="https://user-images.githubusercontent.com/98641421/151656598-99931754-7b4b-4d10-9f0c-2e95a8dc8a51.png" width="300px" alt="Screenshot_20220129-105648">

### Device info

 - Android version/Custom ROM version: CalyxOS android 12.
 - Device model: Google Pixel 5

**Comment by TiA4f8R** [comment]
That's probably not a bug, you may have the `Use external video player` option enabled.

Could you follow these steps and see if NewPipe's player is back?

- go to NewPipe's settings
- go to the `Video and audio` page
- in the `Player` section, disable the `Use external video player` (and probably `Use external audio player` if you want to use NewPipe's background player when pressing Background on a content too)

**Comment by DrRoetker** [comment]
@TiA4f8R oh, I wasn't aware. I probably switched it on when fiddling with the settings. It was idd the problem. Can be closed thanks!
