### ISSUE TITLE
Share custom playlists

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamNewPipe/NewPipe#7719]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Playlists from channels can be shared. I would like a similar feature for playlists I created myself offline.

#### Why do you want this feature?

Sharing multiple videos with someone.

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2414

**Comment by mhmdanas** [comment]
@SameenAhnaf that's a different issue. This is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1788.
