### ISSUE TITLE
NewPipe bug when playing YouTube playlists when a track is missing

### ISSUE THREAD

**Issue by rrgerber** [TeamNewPipe/NewPipe#7720]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Search for  https://www.youtube.com/playlist?list=PLa3pQvnJLLvp-3Mzdg4bYppqmpe8KhrM5
2. Queue the playlist to play in the background.  
3. The issue occurs at the 12th track, which no longer public (L'Infinito)
4. You can skip to the 11th track (Adelante Adelante) via the Play Queue, and then try to advance to the 12th track.
5. You will see that NewPipe will not ignore the 12th track, and go to the 13th track.  Rather, it will loop back to the 2nd track.
6. This is totally repeatable, for any playlist containing some tracks which are no longer on YouTube

### Actual behavior
When playing a YouTube playlist in the background, when NewPipe cannot play a track (usually because that video was removed), it skips back to a track that was already played, usually the first or second tune in the playlist.  This happens on all playlists with missing tracks.  (See steps)

### Expected behavior
Before the current version, NewPipe skipped over missing tracks in a large playlist.  Now it will not go beyond the missing track; rather it cycles back to a previous track.

### Device info

 - Android version/Custom ROM version: Android version 10
![WhatsApp Image 2022-01-29 at 6 08 28 PM](https://user-images.githubusercontent.com/17125479/151681787-4f2f1e7c-4cd8-46c4-a3dc-173cbb64cf64.jpeg)

 - Device model: Hwawei P30 Pro, Model VLOG-L29, EMUI version 11.0.0

**Comment by TiA4f8R** [comment]
Is this bug fixed with the latest release candidate (0.22.0)?

**Comment by rrgerber** [comment]
I will install it and will report the results.  Thanks for looking into this.

**Comment by rrgerber** [comment]
> Is this bug fixed with the latest release candidate (0.22.0)

Yes!  I installed the release candidate and the problem is gone.  Thanks so much for fixing it.  I will close this issue.

**Comment by rrgerber** [comment]
A developer fixed this problem.  Hence I am closing the issue.

**Comment by TiA4f8R** [comment]
> A developer fixed this problem

It's me :)

**Comment by rrgerber** [comment]
Well thank you very much!  Can I pay you a bounty for fixing this?  NewPipe is my favorite app, I use it every day.  It is essential for me; I can't get a paid subscription to YouTube music because they banned me for life over there.  Long story.  🤣
