### ISSUE TITLE
Include  "channel groups" exporting

### ISSUE THREAD

**Issue by cyberspy09** [TeamNewPipe/NewPipe#7721]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment]
Please fill in the template properly while opening an issue. At this moment, you can export all subscription groups together. However, if you'd like to export specific channel groups separately, have a look at https://github.com/TeamNewPipe/NewPipe/issues/4076
