### ISSUE TITLE
newpipe on amazon fire tv stick

### ISSUE THREAD

**Issue by mrbarnie** [TeamNewPipe/NewPipe#7724]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
would live to have newpipe on AFTV stick 

#### Why do you want this feature?
to avoid nasty ads on youtube and regain privacy

**Comment by SameenAhnaf** [comment]
Please keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/1051

**Comment by mhmdanas** [comment]
@mrbarnie I think you should already be able to sideload APKs on Fire OS. Search how to do it online, and if you're having any issues, make a comment here.

**Comment by Bugginme** [comment]
@mrbarnie follow this guide
https://www.youtube.com/watch?app=desktop&v=_h9Cj_bl7rU

**Comment by mrbarnie** [comment]
@mhmdanas 
thanks a lot!!
I know and I already did this but newpipe did not work correctly after i launched it.
this was the reason why I asked.

**Comment by mhmdanas** [comment]
@mrbarnie then you should've told us that from the beginning. What's not working exactly? Is there an error? If so, can you share it? A screen recording would also be helpful.
