### ISSUE TITLE
Sponsorblock?

### ISSUE THREAD

**Issue by OpenSourceMovement** [TeamNewPipe/NewPipe#7733]
I know that some advertisements are ethical, but 
we should leave an option for it nonetheless in the settings.

**Comment by davenewham** [comment]
The new pipe dev team have already said they would be not implementing Sponsorblock. There is a third party fork however which adds this functionality already

**Comment by SameenAhnaf** [comment]
Rejected by devs. See: https://github.com/TeamNewPipe/NewPipe/pull/3205

**Comment by ZaneHannanAU** [comment]
PolymorphicShade/NewPipe @OpenSourceMovement

**Comment by ZaneHannanAU** [comment]
But yeah https://newpipe.schabi.org/blog/pinned/newpipe-and-online-advertising/

**Comment by flexagoon** [comment]
@OpenSourceMovement there's a fork of NewPipe with sponsorblock. The official app will not have this.
