### ISSUE TITLE
NewPipe broken

### ISSUE THREAD

**Issue by Dylan901** [TeamNewPipe/NewPipe#7744]
The NewPipe no longer wont watch any vids as its said:
Sorry something went wrong.
Cleared data and i do retry watch vids and still doesnt work.
That should not happens but its bugged.

**Comment by ZaneHannanAU** [comment]
#7732

**Comment by warbbd** [comment]
This "could not parse website" happens every now  and then.
Get NewPipeLegacy  to watch/listen  etc
When  one  is broken because "youtube"  the other one  usually works.
Swap them  whwn 1 is not working.
P.s.  i  made  the account  just  for  this, to  let you guys know :)

**Comment by TiA4f8R** [comment]
Please follow issue templates and their instructions the next time you open an issue. Thank you.
