### ISSUE TITLE
Age restricted content option not working

### ISSUE THREAD

**Issue by lacolos** [TeamNewPipe/NewPipe#776]
When I turn off 'show age restricted content' I still get the same results as if it were enabled and NSFW items appear in my results.

**Comment by wb9688** [comment]
AFAIK it only applies to loading the actual video detail fragment.

**Comment by lacolos** [comment]
I was hoping this feature would be similar to YouTube not allowing 18+ content from showing unless you log in by account verification

**Comment by wb9688** [comment]
Well, it shows the exact same results as the YouTube website, since it just
scrapes that.

**Comment by lacolos** [comment]
Just a thought: with 'show age resticted content' disabled, don't load any results that have the 18+ content flag

**Comment by lacolos** [comment]
Any ideas if this is implementable?

**Comment by theScrabi** [comment]
@wb9688 is there a way to see on in the infoitems comming from yt if the item is a 18+ or not?

**Comment by theScrabi** [comment]
I've seen that the show restricted video options is getting ignored by NewPipe. Tho the extractor says it can get Videos, so we just needed to find out why this option gets ignored.

**Comment by minhnv174** [comment]
We are not working

**Comment by DonnieDarko666** [comment]
Whenever I try accessing via NewPipe [org.schabi.newpipe_740.apk] on the said videos I get a NewPipe crash log within the NewPipe app.

**Comment by lacolos** [comment]
Sorry to resurrect an old thread but this feature is still not working. Toggling the switch on or off provides me the same content.

**Comment by EdaNano** [comment]
Still not working after two years this was first reported, is this difficult to debug?
It is an important bug as we would like to recommend NewPipe to everybody, including parents for their child phones or tablet. 

So, enabling or disabling age content restriction changes nothing in search results. I compared that with youtube.com website age restriction content parameter, it worked directly on youtube.

**Comment by Z3ROGRAV1TYx** [comment]
Would like to bud in and say I think the option should state "show age restricted content" instead of just "age restricted content", just to clear up exactly if toggling it on means enabling or disabling age restricted content.
