### ISSUE TITLE
Move translated READMEs to subfolder

### ISSUE THREAD

**Issue by albertomosconi** [TeamNewPipe/NewPipe#7762]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Move all translations of the main README.md file into a subfolder (for example [`doc`](https://github.com/TeamNewPipe/NewPipe/tree/dev/doc)).
#### Why do you want this feature?

This would clean up the repo's landing page a bit.

**Comment by mhmdanas** [comment]
I thought about this before, and I like the idea. Do you want to open a PR for this?

**Comment by albertomosconi** [comment]
Yep, I'm on it
