### ISSUE TITLE
Recover subscriptions in Newpipe

### ISSUE THREAD

**Issue by sr7n** [TeamNewPipe/NewPipe#7766]
Is there any way to not lose my subscriptions in newpipe after uninstalling Newpipe? I've to install new update and it won't update ubless I uninstall current version which will cost me my 150+ subscriptions.
If I can get a subscription.csv file like that, then I'll be glad

**Comment by DrFelixWeird** [comment]
You can go to Settings -> Content -> "Export Database" to backup all settings, subscriptions, playlists. You can import the file l under "Import database" to restore all data.

**Comment by MDP43140** [comment]
Bruh, you can open NewPipe, go to its Settings > Content > Export database

**Comment by mhmdanas** [comment]
It's as @DrFelixWeird says. Also, may I ask why you have to uninstall NewPipe to update it in the first place? That shouldn't be happening.

Also, please don't remove the template next time you open an issue.

**Comment by malick-2892** [comment]
> It's as @DrFelixWeird says. Also, may I ask why you have to uninstall NewPipe to update it in the first place? That shouldn't be happening.
> 
> Also, please don't remove the template next time you open an issue.

He probably follows official guideline:
https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

I've stumbled upon, but would't uninstall the app. Got my backup done. Awaiting NewPipe's f-droid repo to be hit with the latest (0.21.16) package.

**Comment by Atemu** [comment]
The page says:

> In case NewPipe is already installed on your device, make sure to [backup your application data](https://newpipe.net/FAQ/tutorials/import-export-data/#export-database).
Uninstall NewPipe before proceeding and reinstall it once your are done following the instructions below. After that [import your backup](https://newpipe.net/FAQ/tutorials/import-export-data/#import-database).

Failing to notice this big red warning would be user error.
