### ISSUE TITLE
Newpipe Has Stopped Working Suddenly, Help!

### ISSUE THREAD

**Issue by brajeshkedia** [TeamNewPipe/NewPipe#7770]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by xMxster** [comment]
You're not supplying any info, how is people suppose to know what went wrong?

Also, it's very likely a duplicated of #7734

**Comment by TheAssassin** [comment]
This issue has been closed because it blatantly ignores the entire issue template, and also ignored all the *existing* issues.
