### ISSUE TITLE
The dumdum CI shouldn't run when non-code files are modified.

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#7774]
_Originally posted by @opusforlife2 in https://github.com/TeamNewPipe/NewPipe/issues/7773#issuecomment-1027273948_

That's it.

Also, notice how we're bypassing the issue template here. Cool. Not.

**Comment by mhmdanas** [comment]
This is a simple fix, just some additions to `paths-ignore`. I think the changes should be made in #7773, since that's the PR that adds the new issue form templates. Thus, I'm closing this issue.
