### ISSUE TITLE
New pipe 

### ISSUE THREAD

**Issue by Mrmillay** [TeamNewPipe/NewPipe#7780]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment]
There's literally no information in the issue, so we can't help you. Please fill in the info requested by the template and then make a comment.

**Comment by Isssuemaker** [comment]
+2
