### ISSUE TITLE
Enqueue option missing when popup player launched from external app. 

### ISSUE THREAD

**Issue by ThisIsPaulDaily** [TeamNewPipe/NewPipe#7788]
### Checklist

- [x] I am using the latest version - 0.21.16 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Share a video from an external app into popup player such. 
For example share to external app from a firefox browser youtube video. 

Then open the NewPipe app and try to enqueue a video into the active popup player. 
In my example I go to "What's New" and try to enqueue a video. 

Note that the "Enqueue " option is missing and only "Start Playing" options are available. Photos shown below. 

### Actual behavior

Note that the "Enqueue " option is missing and only "Start Playing" options are available. Photos shown below. 

![signal-2022-02-02-085037_002](https://user-images.githubusercontent.com/11018948/152388663-153b307e-8b9c-4f6c-a8d1-1a3815806ee1.png)

### Expected behavior
The Enqueue option should be on the list. 

![signal-2022-02-02-085037_001](https://user-images.githubusercontent.com/11018948/152388645-ecfedb20-f26f-4616-a1b6-bdc877693afd.png)

### Device info
	(It's not device specific)
   -Android version/Custom ROM version: Android 11 Lineage OS February 1st build. 
   -Device model: Moto G7+ (Lineage Lake)

**Comment by Zehra** [comment]
Does closing the popup player and reattempting to open as popup player work? (I noticed a similar issue, it may be the same.)

**Comment by ThisIsPaulDaily** [comment]
Yes I believe it does as that's how I created the screenshots. Have I duplicated a prior ticket? @Zehra 

Sorry for the delayed response, I missed the notification. 

> Does closing the popup player and reattempting to open as popup player work? (I noticed a similar issue, it may be the same.)

**Comment by rancidfrog** [comment]
Duplicate.

There are many issues bringing up this problem.
Search...
This has been brought up multiple times since a change was made removing enqueue option from newpipe.

#7266
Is a pull request which tries to solve this issue, but so far it has not been merged.

**Comment by ThisIsPaulDaily** [comment]
@rancidfrog I'm actually very aware of #5850 and its successor #7266. This is different.

**Comment by ThisIsPaulDaily** [comment]
To better see the difference note the difference in the screenshot options.

**Comment by rancidfrog** [comment]
#1487, #4779, #4460
There are a lot of issues since the version iteration that caused queuing/enqueue to disappear.
This is a known issue.

**Comment by Zehra** [comment]
@ThisIsPaulDaily Sorry for the possible confusion. I noticed a bug with a similar trigger on my end, but can now safely conclude the bugs are in fact the same.

Steps done:
1. External link opened in NewPipe. (Web browser in my case.)
2. Video opened as popup.
3. Switch back and opened another link with NewPipe.
4. Attempt to play video as popup.

The only differences were in the way the video was attempted to be played in the menu, but this indicates and clarifies that this bug only appears to be triggered when a video is opened as an external link.

**Comment by ThisIsPaulDaily** [comment]
My ticket is meant to note the explicit lack of dialog box option to enqueue rather than the sharing to newpipe from external app. While I understand that changes were made to how enqueueing works happened in version 19 ish,

**Comment by ThisIsPaulDaily** [comment]
I didn't mean to close it* I misclicked while commenting on mobile. 

This ticket is explicitly meant to address the dialog box option to enqueue being absent when it is normally present. 

I'm not asking about sharing to open enqueue or anything. 
This is just the dialog box button state machine not checking if an active popup player is open. I haven't looked at the code, but I'm guessing it just needs to check if popup player is open on app launch.

**Comment by Poilaucul** [comment]
<img alt="image" src="https://github.com/TeamNewPipe/NewPipe/assets/2638123/964b06d6-8f56-4d2d-9894-6725898a05cc" width=523 />
