### ISSUE TITLE
Download counter

### ISSUE THREAD

**Issue by NewNewPipe** [TeamNewPipe/NewPipe#7789]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
Suggestion to add a new functionality to the Downloads tab with downloaded video and audio files on the top bar to add a counter of video and audio files in the directory to which they are downloaded.

#### Why do you want this feature?
A practical and useful feature that extends the application and makes it easier to manage over downloaded files.

**Comment by litetex** [comment]
Please fill out the template properly

**Comment by NewNewPipe** [comment]
I searched the list of closed and open tasks for a similar topic. I didn't find it, check 1 checkbox from checklist.

P.s.
You can remove the template-ignored label. :)

**Comment by opusforlife2** [comment]
> This checklist is COMPULSORY

Read the template carefully.
