### ISSUE TITLE
Download list disappearing after app exist 

### ISSUE THREAD

**Issue by shockergit** [TeamNewPipe/NewPipe#7794]
I just downloaded a video 50% using public wifi. After reaching home and checked the apps download tab its gone. Now i have to download again. Please fix this
Also please add the resolution name also with file name so we can download multiple resolutions of video at the same time.

**Comment by brnwlshubh** [comment]
Duplicate #7059

**Comment by shockergit** [comment]
Also please add resume support for all files

**Comment by mhmdanas** [comment]
Duplicate of #7059.
