### ISSUE TITLE
design

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#78]
The design feels a bit empty, I'd like to submit some idea's.

On home, I'd imagine the same sort of tab interface that the official youtube app has (whatsapp has this aswell), but instead the tabs - since you said this is something you are going for - are different services possibly? Like youtube, vimeo and what not. 
And then just like youtube, have just the icon and the full text above that. 
So youtube has, home trending, subscriptions etc
Newpipe has Youtube, other service, other service etc.

When searching, the results have a tiny grey bar which looks rather not materialish.
The bar should also turn greyish white without the search/options icon when searching. With an arrow at the left pointing left to cancel search.

At the video page, it has a floating play icon in addition to a play icon on the bar. What about having a transparant play icon on the center of the video instead?
And when scrolling down have the video preview remain at the top with the description sliding behind it?
Another possibility is spotify's implementation. (Even nicer) Where the image stays at the top and the content below flows over the image. And the bar is completely transparant.
If you could have a look at the spotify app and scroll down an album you'll know what I mean.
An then have the play button on the image.

**Comment by theScrabi** [comment]
1. Thats what i'm handing for. But i don't want to wast my time on creating a temporary ui for the home until multiservice support is finaly supported.

2. Id rather care about the programming behind the UI. I'd would be grate if someone could care about the design, because i know it looks like a mess :/

3. The fab Button is also just causing trouble i will probably get rid of it :) The rest sounds like a lot of work. And again, I don't have time for that. So it would be great if someone could care about design.

**Comment by JasperWeiss** [comment]
I'm getting started on android development, design shouldn't be that hard. I'll see if I can get this done

**Comment by theScrabi** [comment]
All right. If you have questions about the code ask them :)

**Comment by JasperWeiss** [comment]
Okay managed to figure out the basics. Got a signed apk with a different color scheme as a test. Now if only there was a nicely designed open-source app to draw some inspiration from :)
Perhaps I can get something done by the end of the week

**Comment by theScrabi** [comment]
Cool thanks. But remember we need to care about the design for phones as well as for tablets. (I tend to forget this from time to time.)

**Comment by JasperWeiss** [comment]
Okay, I'll keep that in mind. I'm thinking a simple option in the settings to change the color scheme would be an easy start. After which I'll see if I can get a nice video info page design thing

**Comment by chschtsch** [comment]
Guys, what do you think about current icon?
Isn't it too generic? Lots of apps use a play sign in their icons.
What do you think about more [YouTube-stylized logo](https://imgur.com/rGpTsk2)?
Or what about using a picture of a smoking pipe in logo, so it'd be like a pun (new pipe)?

**Comment by JasperWeiss** [comment]
It's generic, yes. But frankly, I like it :)
I do think the in-app color scheme should match the icon a bit more though.

**Comment by theScrabi** [comment]
I've changed the icon 3 times in two months now. Give me a break xD i want to care about the code again. Also i had a lot of complains about the integrity of the icon with the new material design. The icon we have at the moment fit the [design guidelines](https://www.google.com/design/spec/style/icons.html#). But in the long term @chschtsch is right.

**Comment by darkon5** [comment]
IMHO, the design needs right with utmost priorities:

- A landscape rework. (that works with phones and tablets)
- Design a welcome screen (with locally saved subscriptions, playlists,...)
- Go full Material Design. (I'm working on making a card-style list for the video search)

**Comment by JasperWeiss** [comment]
That sounds great! 
I do think we should emphasize the 'local' part. I'd also like to have an option to pick a color scheme.
A material dark theme would be great aswell.
I'm still learning this stuff so I'm kinda limited to what I can do.

**Comment by darkon5** [comment]
I chose the new color looking at a lot of information about coloring and design. Here's a difference between the reds:

![newpipe colors](https://cloud.githubusercontent.com/assets/560832/11145127/c7d41120-8a02-11e5-9d57-557c1259bc24.png)

- Top: The icon's red color.
- Bottom: "NewPipe Red" color.

Notice the second one is stronger, but still not too bright.

I would agree to add a theming engine too, but looking at TO-DO the list... However, if you're able to make it and it's easily merge-able, it would be awesome! =D

**Comment by JasperWeiss** [comment]
I'll give it a try this weekend :)

**Comment by theScrabi** [comment]
About the color of the app. I'm aming that each service will later have its own color. If you use youtube NP will be red (youtube red in some way). If you use vimeo its blue, and if you use vine its green, and so on.

Also before you go and implement a card design wait a second !!! I've planed to add a navigation drawer. Through witch you can select
* the curent service
* the channels you subscribed to
* download/favorites/history activity
* settings
* and for what you want so search (video, playlist, channel, (shows))

@darkon5 please keep that in mind when you go on :)

**Comment by timofonic** [comment]
What about if you want to search in multiple services at once?

**Comment by JasperWeiss** [comment]
@timofonic that would probably become a mess and seems hard to implement, so I don't think we should.

**Comment by theScrabi** [comment]
@timofinc it would be possible, but see it like this. If you searched for 10 or 20 services at the same time, you would have to request the websites of all of these services at the same time. So I don't think this is a good idea either.

**Comment by chschtsch** [comment]
A nice solution for that would be one searchbar for all services and if you want to search on different services, you just swipe to another service and hit the search button, so the text you just searched remains and you don't need to type it again.

**Comment by JasperWeiss** [comment]
@chschtsch If you know a way to list all results in one list, let us know :)

As it is now, the results are simple fetched from youtube. But intergrating multiple services in 1 search would require us to make a custom search engine that puts all results in the right order based on relevance. I'm not a programmer (yet) but that seems like a very hard thing to make.

**Comment by theScrabi** [comment]
@JasperWeiss I think that would not be the problem. You'd just need to give the search query to all implementations of the SearchEngine class, and fetch all results. Id would just be very slow I guess.
Anyway I kind of like the idea of chschtsch.

**Comment by JasperWeiss** [comment]
@theScrabi wouldn't that result in having all results from each server below each other e.g 100 youtube videos followed by 100 vimeo etc.
How would you mix these results in one list?
I mean if that's possible, go for it! Seems cool.

**Comment by timofonic** [comment]
If I understand it, this would require to do massive parallel connections.
How does that work on Android?

What about having the same video in different services? Would it be
possible to identify them? What about showing the best quality ones based
on selected default quality and bandwidth/connection?

**Comment by theScrabi** [comment]
I said it would work, I didn't say it would be a nice solution.
1. we could only show a small amount of results form each service.
2. it would be very slow.

But the ide @chschtsch had is very good. You type in one query, and just by swiping from one service to another, you can get the results from another service.

**Comment by JasperWeiss** [comment]
That would be great, so bassically you have different tabs for each service with 1 search bar/icon. And then when you swipe across it keeps the same search query

**Comment by chschtsch** [comment]
Check out this new icon I just drew: https://i.imgur.com/9R7CrGd.png
I'm not the best in vector graphics, but you got the idea. What do you think, guys?
A material 45deg shadow also could be added for hipness.

**Comment by JasperWeiss** [comment]
It looks good, I'm not sure if we should take the pipe thing that literally though :D

**Comment by theScrabi** [comment]
xD it looks ... nice. Although i didn't think of a pipe first. I'd kind of looks like the nike symbol.

**Comment by wb9688** [comment]
That logo indeed looks like the nike logo. For the problem of showing search results for all services we can wrap the views from the video sites and sort it by views. And the app can be faster when we use the JNI for some things that requires more power.

**Comment by theScrabi** [comment]
@wb9688 na. The parsing works pretty fast, and using jni would be beside the point.

**Comment by medavox** [comment]
@wb9688 I agree with @theScrabi, 99% of any latency you might experience is network/server latency. Speeding up the app would not make a perceptible difference.

**Comment by chschtsch** [comment]
Need to notify, I'm currently working on design to improve layouts once again and separate all the values to dimens.xml (according to screen size and orientation). Also, work on CardView implementation is started. I won't be done until CardView is finished, so it's a long-term change. I created [cardview](https://github.com/chschtsch/NewPipe/tree/cardview) branch, so make pulls there if you want to add your changes to design/layouts.

And I encourage everybody to join our [slack team](newpipe.slack.com) to discuss or track work status further on.

**Comment by chschtsch** [comment]
Done this job in #114.

**Comment by krackers** [comment]
I think the text and icons on the actionbar should be white in order to provide better contrast (look at the official youtube app for reference).

**Comment by wb9688** [comment]
Yep, I thought the same...
Op 15 feb. 2016 21:37 schreef "krackers" <notifications@github.com>:

**Comment by OffifialMITX** [comment]
Hey, what about show the downloads on the home menu?

**Comment by ildar** [comment]
There are many other useful things to show on the initial screen. I wonder
when we see there anything to discuss 😉

**Comment by theScrabi** [comment]
I'd like to put flaming content there. Maybe I'll do it in the next few days.

**Comment by theScrabi** [comment]
Flaming contend is now implemented in the backed as "Kisok", which supports more then only "trending". Tho UI is till missing.
