### ISSUE TITLE
Unspecified error while trying to download big videos

### ISSUE THREAD

**Issue by KaMyKaSii** [TeamNewPipe/NewPipe#780]
Hello, I tried to download a video that has almost 4h at 720p in webm and the download simply fails with the size "-1 B". But the audio download worked. Is this some limitation of NewPipe with the size of the video? I have 4.9GB free and the video has 2.53GB. Below is the video for anyone who wants to test
![screenshot_20171024-113535](https://user-images.githubusercontent.com/17092335/31946398-79e12280-b8b0-11e7-8ded-17d4372ae5cc.png)
![screenshot_20171024-113918](https://user-images.githubusercontent.com/17092335/31946403-7f6e5a60-b8b0-11e7-9307-64a5adccc173.png)

https://www.youtube.com/watch?v=MxeJUWCCYTg

**Comment by theScrabi** [comment]
Confirmed

**Comment by codermess** [comment]
The point where this fails for me is in DownloadManagerImpl, at https://github.com/TeamNewPipe/NewPipe/blob/49f9d36718a3977b5ff2866b005ec01c375c135a/app/src/main/java/us/shandian/giga/get/DownloadManagerImpl.java#L309
where the returned length is -1, stopping the mission.

**Comment by TobiGr** [comment]
This should be fixed with the next version (#1759)
