### ISSUE TITLE
Headset controls

### ISSUE THREAD

**Issue by targ8ter** [TeamNewPipe/NewPipe#781]
The background playback is incredibly useful for me, but it would be far more useful if I could play/pause with my headphone button. Given that background play works best for content that doesn't require the screen, it would be great for users to be able to control playback workout using the screen.

Also, I'm hoping that there will soon be a way to adjust the playback speed of background streams.

**Comment by theScrabi** [comment]
Hm ... I thought of that to.

**Comment by slyscorpion** [comment]
I would also like to request the ability to control the volume with headset controls, if possible. This would be especially useful if you are playing a long audio only video, for lack of a better word, in the background. 

There is an application called YMusic from XDA that does this but I like NewPipe better.

**Comment by ZoomRidge** [comment]
Is this feature still able to be implemented? Skipping, Rewind, and Play/Pause support would be extremely useful. I do think that at least if it couldn't be implemented into the default player then maybe an option to use Android's default audio player which natively supports it?

**Comment by switchtegrax1** [comment]
Skipping and play/pause works for me in the latest version,don't know about rewinding tho

**Comment by Stypox** [comment]
This was implemented in #1433
