### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by dlewisfuller** [TeamNewPipe/NewPipe#7824]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by dlewisfuller** [comment]
i have freedom phone, and youtube just errors everytime I try to play it

**Comment by dlewisfuller** [comment]
cna the calander be viewed online or can i add this calander to an online calander

**Comment by mhmdanas** [comment]
It's not clear what you want to report. Fill the template properly please and then make a comment.

**Comment by dlewisfuller** [comment]
New pipe won't play YouTube videos

Thanks, D Lewis Fuller

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mhmdanas** [comment]
Update to 0.21.16 then.

**Comment by dlewisfuller** [comment]
Thank you

Thanks, D Lewis Fuller

Sent from ProtonMail mobile

-------- Original Message --------
