### ISSUE TITLE
Share with playback progress

### ISSUE THREAD

**Issue by brandflake11** [TeamNewPipe/NewPipe#7835]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Share button with current playback progress embedded. This would allow one to share where the video is currently at to whichever app I want. I imagine when you click the share button, a separate prompt with a checkbox would appear and ask if you want to include the playback progress in the share, and if yes, it would automatically fill in the playback time, but would also have a text box that you could include a custom time. You wouldn't need to insert this time manually, but you could if you wanted to share a video at a certain time. Look to how youtube does this on their site. Newpipe could just mimic this feature.

#### Why do you want this feature?

I constantly go back and forth between my computer and phone while listening to youtube videos. I use kdeconnect to share currently playing videos from my phone to my computer to continue them on a bigger screen. This feature would save me time in having to manually put in the playback progress and let me just share where it's currently played back. Around one click and I would be instantly watching the video where I was from my phone on my desktop.

This feature could also be useful for individuals who want to share a certain clip of a video, say on a chatting app like discord, or to a web browser for chatting on forums. It could even be used to open the video from newpipe in the phone's web browser to open on youtube, in case a user wanted to do that.

**Comment by SpiritAxolotl** [comment]
Don't know specifically Java but I think this would be relatively easy to implement. 
Get the current time of the playhead, convert it into seconds, and then if using the youtu.be link, add `?t={sec}` to the end of it, and for normal youtube.com/watch links, add `&t={sec}` to the end of it. Might even learn a bit of Java just to make a pull request of this :)
Good idea. I use this way too often also.

**Comment by SameenAhnaf** [comment]
You can already share playback progress. The violet marked button shares the video link only. The orange one shares with playback progress.

<img src="https://user-images.githubusercontent.com/79245641/152928422-597afbbe-1b45-442b-a2c1-282e503e8606.jpg" height="150px"/>

**Comment by brandflake11** [comment]
That is great this is already implemented. I think maybe there should be a change in how one of these buttons look, so that one knows the orange one shares the playback progress. I had no idea this existed because of how both buttons look the same, but maybe this is a cause for a new enhancement to be opened.

**Comment by mhmdanas** [comment]
@brandflake11 since this is already implemented, I'm closing this. As you already stated, we may want to make the distinction clearer, so feel free to make an issue requesting that (I'm honestly not a fan of using something else than the share icon though, but maybe that's just me).
