### ISSUE TITLE
iOS Build

### ISSUE THREAD

**Issue by SpiritAxolotl** [TeamNewPipe/NewPipe#7837]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I want an iOS build of NewPipe. Doesn't matter whether it's released on the App Store, requires jailbreaking, etc. Just some way to get this app on an iOS device. 

#### Why do you want this feature?

I own an Apple iPhone; not an Android. In my current situation, I am unable to get an Android phone. However, I really want NewPipe. It's extremely useful and I think that many Apple users would also benefit from this app. I understand that Apple is probably a thousand times harder to work with than Android but if it's possible, I would like to see it happen. 
Note that I'm just asking for a _build_. As long as it works on iOS, we'll figure out a way to install it. It may be impacting and/or jailbreaking (or maybe even a third-party installation site, although I haven't heard of one for iPhones.) Anyways, I'm ready for everyone to explain to me **"why exactly iOS won't work for NewPipe"** or something like that, but I just want the answer; that it's either possible or not. If it's not, so be it. But if it _is_, then that's great! Shut up and take my ~~money~~**support**! But that's all I have to say. Thank you for reading.

**Comment by SameenAhnaf** [comment]
Please keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/1051
