### ISSUE TITLE
Add playlist download feature

### ISSUE THREAD

**Issue by Sayori1576** [TeamNewPipe/NewPipe#7848]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Add all video in playlist download to the app.
#### Why do you want this feature?
I think it will be convinent to add playlist batch download

**Comment by mhmdanas** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5482.

**Comment by NewNewPipe** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/7390

**Comment by Sayori1576** [comment]
Sorry.

**Comment by mhmdanas** [comment]
> I get banned for that.

Hmm, I don't recall anyone getting banned over posting duplicates, and even if it were to happen, bans should be utilized only when it gets excessive.

**Comment by Sayori1576** [comment]
When I searched for 'download playlist', I didn't find anything, so I thought there was no overlap.  sorry.
