### ISSUE TITLE
Video cannot play in the background

### ISSUE THREAD

**Issue by Windigo1** [TeamNewPipe/NewPipe#7850]
The video cannot play in the background while using another app or with the screen off. This had always worked before. I use Newpipe for music and this is essential. Please fix this version

### Checklist

- [x] I am using the latest version -0.21.16 on Android 10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo Yes. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md. Yes
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Android app play any video switch to another app or shut down the screen and playing stops. 
2. 

### Expected behavior

1. Go to Android app play any video switch to another app or shut down the screen and playing stops. Expected behavior is the video is still playing this worked for all version of Newpipe until the last release. 

### Device info

 - Android version/Custom ROM version: Android 10 EMUI 11.0.0 
 - Device model: Huawei P30 Pro

**Comment by opusforlife2** [comment]
@Windigo1 Please check the "Minimize on app switch" preference under Video and audio settings.

**Comment by Windigo1** [comment]
Works great thanks!
