### ISSUE TITLE
Audio not playing properly

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#7854]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

play any video
doesn't matter if its from youtube,youtubemusic,soundcloud,peertube
listen to the audio

### Actual behavior

sounds like a tornado

### Expected behavior

audio in the video

### Screenshots/Screen recordings

you can see speakers of my phone are working fine as it can play same video from the browser easily

https://user-images.githubusercontent.com/84063610/153560436-c011df6f-e969-4202-a9ba-2222ec0862ac.mp4

### Device info

 - Android version/Custom ROM version:Android 10, One ui 2.5
 - Device model:Samsung S9(checked on Poco f1, only happens in S9)

**Comment by castrik** [comment]
btw, its happening in yt-dlp for streaming as well(I used mpv-android with yt-dlp, same behaviour
but when I used dvd app from fdroid to download the video using yt-dlp, it played normally with audio

**Comment by castrik** [comment]
https://vimeo.com/676199152

vimeo link since because for some reason, github cut out video

**Comment by castrik** [comment]
wow! it works after resetting!
why did this happen?

**Comment by SameenAhnaf** [comment]
>why did this happen?

Wrong pitch was accidentally selected.
