### ISSUE TITLE
fast forward/backward buttons on locked screen (One UI)

### ISSUE THREAD

**Issue by Hubert21** [TeamNewPipe/NewPipe#7856]
Thanks for this great app :)
On the locked screen, on android phones, there is a small set of infos/controls displayed when an audio or video is playing ; however the very useful 10 sec backward and 10 sec forward buttons are not shown on One UI, and they would be very useful
Thanks

<img alt="lockscreen" src="https://user-images.githubusercontent.com/16777725/153718830-fed62911-e908-40d4-af02-3a34b8550e17.png" height=600 />

**Comment by opusforlife2** [comment]
@Hubert21 In the notification settings inside the app, you can choose which action buttons to show. You can only select up to 3 buttons for the lockscreen notification.

**Comment by Hubert21** [comment]
Thanks for pointing it out. I changed the buttons (the back and forward buttons with 10sec backward and 10sec forward, and with the correct checkboxes selected) but it does not seam to take it in account, as I still have the same buttons in the lockscreen notification. I tried to reboot both NewPipe and the phone.
I am using android 11 and NewPipe 0.21.16

Also, each of the 5 buttons would be of use on the lockscreen notification ; so maybe my request can remain in case some other users might also think it could be useful for them? If it is not due to some known android limitation of course.

**Comment by SameenAhnaf** [comment]
Some Android devices show three buttons at max for lock screen notification. I doubt, if Newpipe devs could do something about it. 
<img src="https://user-images.githubusercontent.com/79245641/153718442-5bf72927-b6c7-4859-b036-c498cd2e5a9b.jpg" height="150px"/>

**Comment by opusforlife2** [comment]
@Hubert21 Can you send a screenshot of the notification menu with the selected checkboxes visible?

**Comment by Hubert21** [comment]
![settings](https://user-images.githubusercontent.com/16777725/153718820-530a2096-7ce6-46b5-97ee-b1bee947ecf0.png)
and in the lockscreen I have :
![lockscreen](https://user-images.githubusercontent.com/16777725/153718830-fed62911-e908-40d4-af02-3a34b8550e17.png)

**Comment by opusforlife2** [comment]
You've changed the action buttons entirely. You didn't need to do that. And you have duplicate Rewind buttons now. That might be part of the bug.

Select the checkboxes of the middle 3 buttons. And change the 1st and 5th buttons back to what they were.

**Comment by opusforlife2** [comment]
Hmmm. This is looking like a One UI issue. Reopening so that someone can investigate it.

**Comment by rey0n** [comment]
The thing that buttons in this window can be changed Must be mentioned somewhere in app! 
I was desiring for rew/ffrwd feature on lock-screen player, and did find this window with buttons, but as there were only checkmarks and no explanation, i thought it's only about switching those on/off(couldn't imaging one can change buttons by long-press).

**Comment by opusforlife2** [comment]
> but as there were only checkmarks and no explanation

Do you not have the giant paragraph above the checkboxes, like the screenshot above?

**Comment by rey0n** [comment]
> Do you not have the giant paragraph above the checkboxes, like the screenshot above?

I'm using localized version and apparently translation was not clear/proper, at least now i know it.




> Works fine here. Still a OneUI problem, probably.

Well, i have Xiaomi with MIUI and problem of wrong buttons on blocked screen is here.

![Screenshot_2022-11-06-13-21-54-010_org schabi newpipe2](https://user-images.githubusercontent.com/31791550/200164810-77dd70cf-0681-4f10-839a-7944c8a46d4f.jpg)
Buttons settings.

![Screenshot_2022-11-06-13-22-11-318_org schabi newpipe2](https://user-images.githubusercontent.com/31791550/200164624-d6e3a0ba-c5c8-47fe-8967-504dafbec45c.jpg)
Notification panel, here buttons are correct.

![Screenshot_2022-11-06-13-22-22-268_lockscreen2](https://user-images.githubusercontent.com/31791550/200164623-8c5346bb-9072-42a2-9955-6a535583bf2a.jpg)
Locked screen, here buttons are wrong, it's still Prev Next.

**Comment by opusforlife2** [comment]
@rey0n Instead of the top 3, try setting the middle 3 buttons and tick them.

**Comment by rey0n** [comment]
@opusforlife2 tried your hint, no luck, still Prev/Next buttons.

**Comment by opusforlife2** [comment]
I just realised that it's very likely that this lockscreen notification is generated by the OS instead of letting the app do it.

One test would be if all other media apps show a notification which looks exactly like this, or very similar to it.

**Comment by rey0n** [comment]
> One test would be if all other media apps show a notification which looks exactly like this, or very similar to it.

Damn, for pity that's right, checked few other apps and notification looks totally same. I guess this means in my case there is no solution, still thank you for helping to figure this out.
