### ISSUE TITLE
Content of main page - cannot choose dynamic playlists

### ISSUE THREAD

**Issue by yasinalm** [TeamNewPipe/NewPipe#786]
As you know, there are automatically created playlists in youtube, like playlists in Music channel. It is also interesting to see this option in the "Content of the main page" preference. For example, user may want to see the best musics in his/her country on the main page.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
That's true, tho It'll be a little more complicated to implement so I didn't do it yet.
