### ISSUE TITLE
Screen unresponsive when using popup player

### ISSUE THREAD

**Issue by daracula** [TeamNewPipe/NewPipe#7871]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.21.16

### Steps to reproduce the bug

1. Open a youtube link using the popup player. 
2. Touch any part of the screen outside the player. 

### Expected behavior

Device responds to touch input outside the player.

### Actual behavior

Screen area outside the player is unresponsive while player is active. 

### Screenshots/Screen recordings

https://imgur.com/a/rJbbGiF

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S20 FE 5G

### Additional information

Started occurring after the recent update to OneUI 4.0.
- The player itself can be moved around the screen and interacted with.
- Opening the popup player from an external app causes the screen outside the player to be unresponsive, except for the navigation bar and the notification/quick panel at the top.
- When opening a video from within the NewPipe app and selecting popup, the screen responds to touch input as normal while using the app.
- If the app is exited (either by pressing the home or recent apps buttons) and the popup player remains on screen, the unresponsive behaviour continues.

**Comment by TiA4f8R** [comment]
> - [X] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Really? Is it not easy to check pinned issues before trying to open a new issue instead of checking a checkbox by probably laziness? Please avoid this in the future. Thank you.

Duplicate of #6770.
