### ISSUE TITLE
Channel organization

### ISSUE THREAD

**Issue by CyberaxAnnon** [TeamNewPipe/NewPipe#7877]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When going to a YouTube channel, having to ability to sort the videos by popularity or newest to oldest.

### Why do you want this feature?

So it would be easier to find a specific video instead of typing it out or searching the channel specifically.

**Comment by SameenAhnaf** [comment]
This issue should be closed in favor of https://github.com/TeamNewPipe/NewPipe/issues/5324
