### ISSUE TITLE
Opening video with a playlist link will play first video in the playlis instead of the linked video

### ISSUE THREAD

**Issue by matejdro** [TeamNewPipe/NewPipe#7878]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.21.16

### Steps to reproduce the bug

1. Open https://www.youtube.com/watch?v=w2IhccXakkE&list=PLbpi6ZahtOH4ANPsJ3BbLC_fpxNarTayV&index=4 link in NewPipe

### Expected behavior

`Polo G - RAPSTAR (Official Video)` should be playing, since it's the linked video

### Actual behavior

`Pooh Shiesty - Back In Blood (feat. Lil Durk) [Official Music Video]` plays, which is a first video in playlist that is included in the video link.

### Affected Android/Custom ROM version

Android 12 / Krypton ROM

### Affected device model

OnePlus 7 Pro

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7643

**Comment by matejdro** [comment]
Huh, title of that issue is much different, I did not find it. Will close my issue.
