### ISSUE TITLE
Not responding Newpipe with 150+ downloads 

### ISSUE THREAD

**Issue by robovoice1** [TeamNewPipe/NewPipe#7879]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.21.16

### Steps to reproduce the bug

After 150 and more downloads (from short 100 kb up to 400 Mb ) m4a files go to "downloads".
You can scroll down the listed files a bit, but the a message appears App Newpipe is not responding, close, wait.

### Expected behavior

Responding newpipe

### Actual behavior

After tapping on downloads it takes 10 sec until the downloaded files are shown.
Message appears that newpipe is not responding.
Close/wait

### Affected Android/Custom ROM version

Android 12 Graphene Os (latest beta channel release)

### Affected device model

Pixel 6 Pro

### Additional information

Copying some downloaded files to another folder solves this.

**Comment by AudricV** [comment]
Is it still an issue with 0.26.1?
