### ISSUE TITLE
Downloading getting error when the network is slow 

### ISSUE THREAD

**Issue by Praveen0899** [TeamNewPipe/NewPipe#788]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by Praveen0899** [comment]
Why can't we get get trending videos  when we got started into newpipe

**Comment by theScrabi** [comment]
This will come with the next version.
Thread might be related to this:
https://github.com/TeamNewPipe/NewPipe/issues/780

**Comment by Praveen0899** [comment]
Why can't we get get trending videos when we got started into newpipe

**Comment by Praveen0899** [comment]
Why can't we get get trending videos when we got started into newpipe
