### ISSUE TITLE
Sound NOT Working. Extractor Broken Again

### ISSUE THREAD

**Issue by PrivacyOsint2** [TeamNewPipe/NewPipe#7887]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.21.16

### Steps to reproduce the bug

Search someone account by name or watch video on soundcloud.
Click on there account.
Gives Error.

### Expected behavior

Can't watch video or look at accounts.

### Actual behavior

..

### Screenshots/Screen recordings

..

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 6

### Additional information

na

**Comment by litetex** [comment]
> Gives Error.

Without an error report or some kind of logs we can't help you. Please add them.

**Comment by PrivacyOsint2** [comment]
It working now. Someone fixed somthing. Wasn't work since 18 days ago.
