### ISSUE TITLE
missing main-bar on the bottom and subscribe-button in channel view

### ISSUE THREAD

**Issue by DamageIncorporated** [TeamNewPipe/NewPipe#789]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hey, 

I am experiencing a strange issue with NP on a Samsung Galaxy S4 Active with hardware buttons instead of the android soft button bar (if that is related?) The device is rooted but uses the stock rom.

On the home screen there is no bottom bar saying "overview / subscriptions".

In the channel view, the subscribe button is also missing. The RSS-Button to follow with other apps is visible and works, but I cannot subscribe with Newpipe.

I also use a nexus 5 with the same version of the app. On that phone everything looks and works as expected..

I am willing to help with further information if asked for and testing on the mentioned device 

Greetings from Germany, Earth

Markus

**Comment by theScrabi** [comment]
Hello, these are strange errors that sound like they are more likely related to your phone. Also I can not reproduce these errors, I wouldn't even know how. Try to find more intel about your problem.

**Comment by DamageIncorporated** [comment]
Would an exerpt from a system log help?

I'm not a developer and not very fluent at this stuff but I have adb installed to install custom roms and would be willing to dive into this.. 

could take some time though :)

Greetings, Markus

**Comment by wb9688** [comment]
Most likely not, but in the next version we'll have top tabs anyway.

**Comment by TobiGr** [comment]
@DamageIncorporated if this issue still exists, please reopen this ticket. I'll close it due to inactivity and a bunch of changes in the main view.
