### ISSUE TITLE
Replacement for YouTube API? microG integration?

### ISSUE THREAD

**Issue by timofonic** [TeamNewPipe/NewPipe#79]
Hello.

Can NewPipe work as a YouTube API replacement? In order to remove Google stuff and make other apps still work as orbit.

It can be part is microG package, that aims to replace Google Services API and such.

https://developers.google.com/youtube/android/player/
https://github.com/microg/

**Comment by theScrabi** [comment]
I don't know. Ask them.

**Comment by timofonic** [comment]
Okay ;)

**Comment by theScrabi** [comment]
Made any progress?

**Comment by theScrabi** [comment]
According to @mar-v-in there is no need for this.
