### ISSUE TITLE
Player UI hidden during portrait mode playback

### ISSUE THREAD

**Issue by AlertSubject** [TeamNewPipe/NewPipe#7912]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

1. Open this video https://www.youtube.com/watch?v=dh6cCKTtliM
2. Go full screen
3. Click on screen to bring up the player UI
4. Find out that it has disappeared 

### Expected behavior

The player shouldn't just disappear 

### Actual behavior

The player did disappear 

### Screenshots/Screen recordings

![grafik](https://user-images.githubusercontent.com/40789489/155015404-adebf22e-6dd9-4005-914d-3ca7cf0e883d.png)

### Affected Android/Custom ROM version

Android 11, OxygenOS 

### Affected device model

Oneplus 9 pro

**Comment by zer0fl0w** [comment]
can't reproduce on oneplus 8t.

**Comment by AlertSubject** [comment]
> can't reproduce on oneplus 8t.

Try entering full screen playback once the video has started playing, not before

At least I can reproduce it that way

**Comment by zer0fl0w** [comment]
ok. confirmed.

**Comment by nospace-here** [comment]
Can reproduce on Pixel 4a, Android 12

**Comment by litetex** [comment]
Problem is caused by #7451
