### ISSUE TITLE
pr #7451 messes up landscape view

### ISSUE THREAD

**Issue by zer0fl0w** [TeamNewPipe/NewPipe#7913]
this pr [#7451](https://github.com/TeamNewPipe/NewPipe/pull/7451) alters the way fullscreen landscape view is shown for displays with punchhole camera. before the video truly played fullscreen also overlaying the camera area. it used far more screen in total then now with v22 where the whole camera bar is blacked out/not used. viewing area is decreased and unsymmetrical. i understand the idea behind it but it is a regression for devices without a notch.

issues is seen [here](https://i.imgur.com/skkkT74.jpeg) and [here](https://i.imgur.com/zJaVJnM.jpeg) 

the red line marks the area which was used by versions before v22. it was tested with two different devices running latest stock software: huawei nova 5t and oneplus 8t.

**Comment by nospace-here** [comment]
Same on the Pixel 4a. The "fit" position also is pushes the video to the left side, making content on the rounded corners cut off. Previous newpipe version did it correctly.

**Comment by litetex** [comment]
Closed in favor of #7915 (← has a template)
