### ISSUE TITLE
[MIUI] Crash with "Transformation PICASSO_PLAYER_THUMBNAIL_TRANSFORMATION_KEY mutated input..."

### ISSUE THREAD

**Issue by NormanMises** [TeamNewPipe/NewPipe#7914]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

App crashes as soon as some videos are clicked

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ JP
* __Content Language:__ zh-TW
* __App Language:__ zh_TW
* __Service:__ none
* __Version:__ 0.22.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Transformation PICASSO_PLAYER_THUMBNAIL_TRANSFORMATION_KEY mutated input Bitmap but failed to recycle the original.
	at com.squareup.picasso.BitmapHunter$6.run(BitmapHunter.java:490)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8211)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 MIUI 13

### Affected device model

Xiaomi mi 10

**Comment by Stypox** [comment]
Yes, I'm pretty sure this is not a bug in our code. When I implemented the thumbnail-cropping for the notification, I took care of preventing that exception by making sure to create a **new** bitmap each time and then **recycle** the original, [as you can see here](https://github.com/TeamNewPipe/NewPipe/blob/bd5eda92a714cd51ac7479bebdb423dc7fbb85bf/app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java#L127-L153) and as requested by the exception description.

**Comment by Bec-de-Xorbin** [comment]
Yes, it was indeed fixed at least by Xiaomi.eu. So no, not a bug in your code. No idea if this bug still appears in official MIUI
