### ISSUE TITLE
Notch not filled in full screen mode

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [TeamNewPipe/NewPipe#7915]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

1. open video
2. the video is not full screen even in fill mode

### Expected behavior

before the last update, there was a similar problem with the menu, but now the videos are not displayed in full screen. my screen has a small cutout for the camera, but this does not prevent me from using the interface or watching videos until the latest version is released

### Actual behavior

the video is not full screen even in fill mode

### Screenshots/Screen recordings

![Screenshot_2022-02-20-23-14-46-208_org schabi newpipe](https://user-images.githubusercontent.com/52075465/154862467-faa33b38-e32a-439a-afee-1de0c881ed49.jpg)
![Screenshot_2022-02-20-23-14-37-055_org schabi newpipe](https://user-images.githubusercontent.com/52075465/154862476-0ad0d6b3-19d8-48e3-adf1-290aa7894dbb.jpg)

### Logs

-

### Affected Android/Custom ROM version

Android 11 miui 12

### Affected device model

Xiaomi 11 lite 5g ne

**Comment by SameenAhnaf** [comment]
This is intentional. Now, notch is always hidden on landscape. See: https://github.com/TeamNewPipe/NewPipe/pull/7451

**Comment by litetex** [comment]
From #7913:

> this pr [#7451](https://github.com/TeamNewPipe/NewPipe/pull/7451) alters the way fullscreen landscape view is shown for displays with punchhole camera. before the video truly played fullscreen also overlaying the camera area. it used far more screen in total then now with v22 where the whole camera bar is blacked out/not used. viewing area is decreased and unsymmetrical. i understand the idea behind it but it is a regression for devices without a notch.
> 
> issues is seen [here](https://i.imgur.com/skkkT74.jpeg) and [here](https://i.imgur.com/zJaVJnM.jpeg)
> 
> the red line marks the area which was used by versions before v22. it was tested with two different devices running latest stock software: huawei nova 5t and oneplus 8t.

**Comment by AnkS4** [comment]
> This is intentional. See: https://github.com/TeamNewPipe/NewPipe/pull/7451
> 
> You may optionally show notch all the time. Go to`Settings`>`Display`> Show `Notch in invidual apps`>Select `Always show notch` for Newpipe app

For MIUI 14, it's in `Settings`>`Notifications & Control Centre`>`Status Bar`>`Notch in invidual apps`>Select `Always show notch` for Newpipe app.
