### ISSUE TITLE
sponsorblock

### ISSUE THREAD

**Issue by binex-dsk** [TeamNewPipe/NewPipe#7920]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add integration with SponsorBlock. Skip sponsors by default, allow users to toggle it off, etc.

Additional functionality could include the ability to submit sponsor segments, and {dis,}like submitted segments.

### Why do you want this feature?

Providing the best possible UX and because I don't want to listen to people blabber about Hot New VPN 9000 for a minute and a half.

### Additional information

my cat

<img alt="PXL_20220220_224324576" src="https://user-images.githubusercontent.com/65276418/154885642-2d3a775b-8392-4ee4-bbf1-0da570b858e7.jpg" height=600 />

**Comment by BowDown097** [comment]
my cat
![PXL_20220207_153309054](https://user-images.githubusercontent.com/42720004/154885955-928f6f8f-9c73-4a85-9bea-79f14caac9f4.jpg)

**Comment by SameenAhnaf** [comment]
Rejected by devs. See: https://github.com/TeamNewPipe/NewPipe/pull/3205

**Comment by binex-dsk** [comment]
> my cat <img alt="PXL_20220207_153309054" height="600" src="https://user-images.githubusercontent.com/42720004/154885955-928f6f8f-9c73-4a85-9bea-79f14caac9f4.jpg">

Nice calves
