### ISSUE TITLE
Playlist or saved video tab

### ISSUE THREAD

**Issue by kgoerbig** [TeamNewPipe/NewPipe#793]
There is a subscription tab, to save subscriptions, which is great. Can you add a similar tab to create video playlists, and bookmark individual videos?

**Comment by drfunkencluck** [comment]
Would be cool if we can sign in with our Google account or use channel I'd to get playlists we have saved from other YouTube channels as well as getting our made playlists

**Comment by speednroll** [comment]
@drfunkencluck it would be a bit more complex to enable it to newpipe, but surely everything can be done. by the way, if that happened, it would be nice if you have the possibility to use your playlist locally or with your google accounts (both options in a settings menu).

**Comment by rattan77** [comment]
I strongly back @kgoerbig request. At least I will have my playlist (saved videos).

**Comment by opusforlife2** [comment]
Already added.
