### ISSUE TITLE
Status bar not being used in Fill mode

### ISSUE THREAD

**Issue by Kromppo** [TeamNewPipe/NewPipe#7930]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

1. Start playing any video in fullscreen landscape
2. Switch display mode to Fill in drop-down menu

### Expected behavior

In Fill mode, the video will use the whole screen to display content, including where the status bar usually is. 

### Actual behavior

The status bar region is not used and it cuts off part of the video. This also applies to when you try to use seek gestures. The pop up when you skip forward gets cut off by the status bar. This is hard to see in the second screenshot below, but if you look closely at the top right it will be cut off. 

### Screenshots/Screen recordings

![Screenshot_20220222-152551](https://user-images.githubusercontent.com/72403056/155224130-4c90bef7-96a1-490e-bbe8-86259c5c9f2f.jpg)
![Screenshot_20220222-152531](https://user-images.githubusercontent.com/72403056/155224158-86df8451-5f98-4e32-9755-0df0c962768d.jpg)

### Affected Android/Custom ROM version

Android 11 OxygenOS 11.0.14.16.KB09CB

### Affected device model

OnePlus 8T (Rooted)

**Comment by litetex** [comment]
Already fixed by #7924
