### ISSUE TITLE
Create an app-wide `Disposable` to be used for app-wide actions

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#7942]
### Checklist

- [X] This issue contains only one bug.
- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

### Affected version

After (but also before) #7570

### The problem

In the NewPipe codebase there are many methods that use RxJava to perform resource/time/io-heavy actions in the background. When these actions finally result in a change in the activity/fragment/dialog that originally triggered them, then an RxJava `Disposable` should be passed to those functions, so that if the activity/fragment/dialog is dismissed before the action can complete, the action can be `dispose()`d. This is what is correctly being done in the [text linkifier class](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java#L237-L238): they take a text view and set its text once it has been linkified, but if in the meantime the activity/fragment/dialog associated to the text view was destroyed, the linkification of the text [will stop](https://github.com/TeamNewPipe/NewPipe/blob/3d47d73ba9b39bdc0b5415734d4308f3bd1917f6/app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java#L68-L71) (otherwise it would result in calling `setText()` on a non-existing text view).

Sometimes, though, an action is not really associated with the activity/fragment/dialog that triggered it. If the user want to start playing something in a popup, he may tap on the popup button in the long-press menu of the feed fragment, and then maybe he instantly (i.e. before the popup player had a chance to load) closes the feed fragment to switch to another app. If the disposable for playing in popup was added to the `Disposable`s associated with the feed fragment, the loading of the popup player would stop. So currently what is being done instead is basically just not saving disposables anywhere so they are never disposed, for example [checkout this](https://github.com/TeamNewPipe/NewPipe/pull/7570#discussion_r810488988). Though this behavior mostly works fine, I don't think it is a good practice and may lead to problems, so I think we should create an app-wide `Disposable` to which all disposables related to app-wide actions can be added.

**Comment by AudricV** [comment]
@Stypox As we want to rewrite the app and migrate it to Kotlin and use coroutines, is this issue still relevant?

**Comment by Stypox** [comment]
No, and it's also a bad idea. We should use dependency injection.
