### ISSUE TITLE
Chrome browser open videos 

### ISSUE THREAD

**Issue by cmtrkr83** [TeamNewPipe/NewPipe#7955]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1.  I search a video on chrome browser APK.
2. And i click a video from result
3. Video open in chrome. (Because i disabled youtube APK)
4. Not open in newpipe apk.
5.  I checked all default apps settings....

### Expected behavior

New pipe my default video apk. All result and all platform 

### Affected Android/Custom ROM version

Android 11 miui 12.5.6

### Affected device model

Redmi note 10 pro

**Comment by cmtrkr83** [comment]
https://youtube.com/shorts/twc57bBb4AY?feature=share

**Comment by litetex** [comment]
Closed in favor of #7961
