### ISSUE TITLE
About YouTube Shorts Feature

### ISSUE THREAD

**Issue by saurabhkk12345** [TeamNewPipe/NewPipe#7956]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

There should be a separate section for YouTube Shorts..

### Why do you want this feature?

This will be amazing experience for me not to download youtube for its Shorts videos...
Thanks for Open Source NewPipe Application....

**Comment by SameenAhnaf** [comment]
This should be be closed in favor of https://github.com/TeamNewPipe/NewPipe/issues/7644

**Comment by litetex** [comment]
> I made sure that there are no existing issues

No you didn't.

Closed.
