### ISSUE TITLE
Please add a subscription button below the YouTube videos

### ISSUE THREAD

**Issue by ShovanSaha2020** [TeamNewPipe/NewPipe#7966]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Please add a subscription button below the YouTube videos. Currently, I have to go to a channel home page to subscribe to that channel.

### Why do you want this feature?

I want this feature because it will make subscribing to a channel easier and faster.

### Additional information

![Screenshot_2022-02-28-12-36-52-41_ee8807d2de22f1831269d80920e33a3b-01](https://user-images.githubusercontent.com/65008778/155936083-07d6607a-9b3e-41c7-b62e-d975809fb8e6.jpeg)

**Comment by brnwlshubh** [comment]
#7277

**Comment by litetex** [comment]
> I made sure that there are no existing issues

No, duplicate

**Comment by ShovanSaha2020** [comment]
I am sorry. I am not familiar with GitHub issue posting system. I actually
tried to search if any one else posted about this but got lost in
the process.
