### ISSUE TITLE
Cover Image in Queue not refreshing

### ISSUE THREAD

**Issue by mmilicbucevic** [TeamNewPipe/NewPipe#7971]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Enqueue a couple of songs. (at least 3-4)
2. Start the first song by choosing "Start playing in the background".
3. Use the _right arrow_ (**>|**) in the notification bar menu to skip to the next song in the queue.
4. The cover image is not changed, although new song is being played. 
_Note: If it changes, try skipping to the next song in the queue, until the bug occurs._ 

### Expected behavior

The cover image, corresponding to the new song, should be updated. 
In particular, when I skip from 'Praise the Lord' song to 'Ball w/o You', the new cover image should be the one of the 'Ball w/o You' song.

### Actual behavior

The cover image of the new song remained the same as of the previous one. It is not refreshed. It does not reflect the new one.
In particular, 'Ball w/o You' song displays 'Praise the Lord' song cover image.

### Screenshots/Screen recordings

<img alt="queue" src="https://user-images.githubusercontent.com/78053738/156088562-e6ff512a-70cf-439d-98fa-e0f2ea505963.jpg" height=550 />
<img alt="queue" src="https://user-images.githubusercontent.com/78053738/156088572-459cd1d9-01e9-4761-a6b9-8fd6fa12dbd4.jpg" height=250 />
<img alt="queue" src="https://user-images.githubusercontent.com/78053738/156088577-a53e8ad5-8047-4c7c-b30e-53b344275d76.jpg" height=250 />

### Affected Android/Custom ROM version

MIUI 11.0.2 | Stable

### Affected device model

Redmi Note 4X

### Additional information

The bug may take a couple of songs to be reproduced. Be sure to have a longer queue list if needed.

**Comment by AudricV** [comment]
Is it still an issue on 0.26.1?
