### ISSUE TITLE
Update ExoPlayer to 2.17.0

### ISSUE THREAD

**Issue by teaerror** [TeamNewPipe/NewPipe#7972]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Please update to the latest version of ExoPlayer and raise minimum API to 21 (litetex already has pr bumping SDK).

### Why do you want this feature?

Updating should help fix HLS buffering, allows NewPipe to update OkHttp to newer versions, and helps with android 12 support.

**Comment by opusforlife2** [comment]
I don't think we need a separate issue for this? We always intend to keep pace with ExoPlayer updates. It's just blocked sometimes by something or the other, so we lag behind a little.

Closing because this 'enhancement' is inevitable. :)
