### ISSUE TITLE
Feature request: add videos sent to kodi to list of watched videos

### ISSUE THREAD

**Issue by axelsimon** [TeamNewPipe/NewPipe#798]
Hello,
I've realised that if I search for videos, pick one, then send it to Kodi using the (convenient) button, it doesn't get registered as watched and doesn't show up in the history.

I think it would be helpful to count it as watched, given that from a user's perspective, it _was_ watched and it was watched using (in part) NewPipe.

Maybe make it a setting under “Show ‘Play with Kodi’ option”: “Mark videos watched in Kodi as watched locally”.

Thanks!

**Comment by theScrabi** [comment]
Na it should count as watched locally this or that way.

**Comment by axelsimon** [comment]
Sorry, I'm not sure I understand your answer, but looking at the commit, it looks like you've implemented this, cool :)

A new idea that came to me: in the history, mark the videos that were sent to Kodi with a Kodi logo on the bottom right of the history entry box (or even a discrete background logo for the entry, could look nice).
This could help find a video in the history, as we humans are likely to remember the context in which we watched the video (at home on Kodi, or anywhere on our smartphone).

Thanks!
