### ISSUE TITLE
Sonarcloud: Remove Security hotspots from quality gate

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#7980]
There are major problems with the quality gate which causes every build to have a red ❌ 

According to Sonarcloud we should review 
![grafik](https://user-images.githubusercontent.com/40789489/156435810-760840b2-1fa3-40aa-9e60-598e58a8d151.png)
after merging https://github.com/TeamNewPipe/NewPipe/pull/7782 which is completely unrelated to the PR...

I would update the quality gate myself but I don't have permission to do so `(╯°□°）╯︵ ┻━┻`

@XiangRongLin @TobiGr

**Comment by XiangRongLin** [comment]
As far as I know the sonarcloud memberships are synced with the github menberships. So if you log in there with your GitHub account du should be able to change it

**Comment by XiangRongLin** [comment]
I just marked it as fixed for now

**Comment by XiangRongLin** [comment]
@litetex nevermind. The memberships are synced, but not the admin status

**Comment by litetex** [comment]
Thank you for the quick response.

I removed the condition for now:
![grafik](https://user-images.githubusercontent.com/40789489/156821555-7fbc1804-8ad0-4421-8f51-ea626ec65087.png)

So I guess the issue should be fixed 😄
