### ISSUE TITLE
System crash when playing new video when existing video is already playing

### ISSUE THREAD

**Issue by kuroodo** [TeamNewPipe/NewPipe#7992]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Play a video
2. Wait for video to load or begin playing
3. Play a different video

### Expected behavior

Previous video stops playing and new video begins to play

### Actual behavior

Phone abruptly crashes and reloads: screen goes black, goes to google logo, then back to lock screen, then phone starts loading as if it just booted up.

### Affected Android/Custom ROM version

Android 11

### Affected device model

Pixel 2

### Additional information

Bug can be avoided by closing (not pausing) the current playing video before selecting a new video. This crash does not occur if you play the video in the background or as a popup.

**Comment by litetex** [comment]
Looks like a duplicate of #5961

Could you please collect logs when this error happens and paste them here?

**Comment by kuroodo** [comment]
I have posted the logs as well as some new information for reproducing the crash in the other issue. Thanks.
https://github.com/TeamNewPipe/NewPipe/issues/5961#issuecomment-1060002122
