### ISSUE TITLE
There is slight buffering while playing 1080p videos.

### ISSUE THREAD

**Issue by developeranaz** [TeamNewPipe/NewPipe#7995]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Play a 1080p(Not in other quality) video 
2. Increase video speed x1.8
3. Play a minute it will buffer.
Please close this issue if it is a temporary issue or my fault.

### Expected behavior

Play without buffer

### Actual behavior

1080p video buffering.

### Screenshots/Screen recordings

no screenshot

### Logs

no logs

### Affected Android/Custom ROM version

Android 9 , EMUI 9.1.0

### Affected device model

Honor 7X | BND-AL10

### Additional information

* Tried playing other than 1080p all work fine
* Tried Restarting wifi
* Tried restarting phone
* Tried switching to mobile data

**Comment by developeranaz** [comment]
Sorry for posting this weird issue, now the video seems to be working fine, maybe its YouTube problem or mine, thanks for this great app, this app is very light and this app is very useful for students especially for learning purpose. Because the original YouTube app shows a lot of ads and other videos suggestions while studying.
Sorry again for posting this trash issue i’mm closing this.

**Comment by opusforlife2** [comment]
Don't worry. It's quite normal to find more information when you're in the process of opening an issue. It happens all the time to me.
