### ISSUE TITLE
supported web addresses

### ISSUE THREAD

**Issue by Blutsauger13** [TeamNewPipe/NewPipe#7999]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

unfortunately, after each update I have to set the web addresses to be supported again.
Is there a solution for this problem?

With kind regards

**Comment by litetex** [comment]
> unfortunately, after each update I have to set the web addresses to be supported again.

Can't quite follow you 🤔
What do you mean with "web addresses"? Or which ones?

**Comment by Blutsauger13** [comment]
Sorry for my poor explanation. In the app properties under "open by default" you can specify the web addresses to support, such as youtube.com etc.... After each update of the app via f-droid these are reset again.
@android 12

**Comment by litetex** [comment]
Ah yes Android 12... where google broke half of this app (*_cough_* popup-player).

I think we have to sooner or later implement something like this:
https://developer.android.com/training/app-links/verify-site-associations#provide-context
or simply reroute all links into NewPipe (there is also an issue for that somewhere).

Anyway I think #7436 is what you are looking for.

**Comment by Blutsauger13** [comment]
Thank you for your information. 
It is exactly this problem. It was also described in detail in post #7436. 👍
