### ISSUE TITLE
Bountysource page available

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#800]
Our [Bountysource](https://www.bountysource.com/teams/newpipe) Page is now available, you can donate using:
- bitcoin
- paypal

Spread the word :)

**Comment by Snugface** [comment]
Guys, this is amazing!
I've been waiting both for this and the history for myriads of months ever since I discovered your app.
Please add some of this info into the actual app

**Comment by Snugface** [comment]
Guys, this is amazing!
I've been waiting both for this and the history for myriads of months ever since I discovered your app.
Please add some of this info into the actual app

**Comment by theScrabi** [comment]
Hm adding a donation hint into the app would not be a bad idea :)

**Comment by TobiGr** [comment]
Yes. This sounds good. We can place it in the About activity between "Contribution" and "NewPipe's License".

**Comment by opusforlife2** [comment]
Close now? This was news in 2017.
