### ISSUE TITLE
Videos take longer to load?

### ISSUE THREAD

**Issue by CyberaxAnnon** [TeamNewPipe/NewPipe#8000]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1: Open the app
2: Pick a video and play

### Expected behavior

To load the video in a reasonable amount of time. 

### Actual behavior

It takes up to a minute in some cases to load a video. 
I understand this is not using google APIs and relies on the webpage, but it doesn't feel like it when compaired to previous versions. 

I have a VPN and manage to attain 50mb/s on a 2.4ghz network and load webpages normally.

### Affected Android/Custom ROM version

Android 11

### Affected device model

Xiaomi Note 9 Pro

**Comment by brnwlshubh** [comment]
https://github.com/TeamNewPipe/NewPipe/suites/5494503468/artifacts/175647715

Test this apk

**Comment by brnwlshubh** [comment]
Issue fixed by this PR https://github.com/TeamNewPipe/NewPipe/pull/7919



> https://github.com/TeamNewPipe/NewPipe/suites/5494503468/artifacts/175647715
> 
> Test this apk

**Comment by ChungusAmongus2** [comment]
To add to this, when using an external player it opens up a link that never finishes loading. Some videos work perfectly while others do not.

Max Fang - Majestic (works)
[Max Fang - Majestic](https://rr1---sn-uhvcpax0n5-vgql.googlevideo.com/videoplayback?expire=1646772227&ei=o2snYsfLDIOTigSv2qOwCA&ip=2607%3Afb90%3Aa3fe%3A6400%3A69b5%3A42cb%3Aa228%3A62cc&id=o-AD8QlT2Mre0hZr488xtBzwKOj8FKKL1ELyYJz4GLScvQ&itag=140&source=youtube&requiressl=yes&mh=pw&mm=31%2C29&mn=sn-uhvcpax0n5-vgql%2Csn-vgqsknlz&ms=au%2Crdu&mv=m&mvi=1&pl=40&initcwndbps=393750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=5359890&dur=337.432&lmt=1532138494786432&mt=1646750259&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgCopgN56XarOjfh50F8wr7fk8KctToaZLbRk2zYjbilkCIBxk0rlz0CQUnwtBHFeB6AxEFnZVihK0xD7t9Z74Clvd&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgWmPSWV2jx6S-WYmfYUfAd8exUs9-PNWMKwLKFEQ5hPYCIQDlDAXMH0e4cbhLOtiyCJvY8rV_Ll4molrMmy3Q6DEx6g%3D%3D) 

[My Way (2008 Remastered) (Won't finish loading)](https://rr4---sn-uhvcpax0n5-vgqs.googlevideo.com/videoplayback?expire=1646772324&ei=BGwnYqGcAY-Uir4P4NaOoA8&ip=2607%3Afb90%3Aa3fe%3A6400%3A69b5%3A42cb%3Aa228%3A62cc&id=o-AD4Fj4hu6Iq9Ns_-zr9ZZjnDg_lvSwmcic83ryvrYOri&itag=140&source=youtube&requiressl=yes&mh=qM&mm=31%2C29&mn=sn-uhvcpax0n5-vgqs%2Csn-vgqsrnes&ms=au%2Crdu&mv=m&mvi=4&pl=40&gcr=us&initcwndbps=12695000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=4473403&dur=276.253&lmt=1628119565162082&mt=1646750259&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKyqofpOjNB91Hiu0Q73uCGIjfQAZlvzrT31dQlt0_1FAiEA3AgFCq21rqi-JFMJ_l6rTgHcjKx4Y4qjb-Sfcu7G1hY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOzPjgvfAgPF-DS74F8_5pDLO6kzL1WrD8q0ehpfK80nAiEA-rIXvpu-mrmGj-KHOS5Nu3KfWXLyzXZ44BXJ-JEV4uE%3D) 

On mobile the loading bar is at around 70% and just stood there.

**Comment by CyberaxAnnon** [comment]
There was a significant difference in loading times, but is there an ETA on when this can be added as soon as possible?
As again for now since my wifi is fine. The test APK when switching to 16kb does make a difference when compared to 16kb.

**Comment by litetex** [comment]
![grafik](https://user-images.githubusercontent.com/40789489/157513107-4a106853-5056-4b2f-bdd9-d13c0cc1b583.png)

It was already merged so it will be shipped with the next release.
