### ISSUE TITLE
playlist playback is not synchronised when the screen is on and when it is off.

### ISSUE THREAD

**Issue by Mesum-Hussain** [TeamNewPipe/NewPipe#8001]
When I play a playlist and watch some videos, is works fine. But after that if I off my screen, the playlist starts playing from the beginning instead of playing the video that was running while the screen was on.  Essentially if I want to listen to a playlist, all the progress is lost if I switched the screen on and then off.

**Comment by TiA4f8R** [comment]
Could you confirm you are using the latest version of the app (0.22.1)?

Also, please open an issue using GitHub web interface to follow our issue forms next time.

Thanks!

**Comment by Mesum-Hussain** [comment]
I was using 0.21.16. Just updated seeing your comment. The issue is fixed in the latest version. Thanks! 🙂
