### ISSUE TITLE
Provide a method to access the background play queue directly from the main interface

### ISSUE THREAD

**Issue by Roy-Orbison** [TeamNewPipe/NewPipe#8006]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Provide some button, tab or menu item to directly view the background playlist queue from the main interface. An item in the hamburger/side menu, or a content tab (enabled by default) would be great.

### Why do you want this feature?

Presently, one has to pull down the device's system notifications to open the background play queue, which is like exiting the app to get into the app. It's very unintuitive.

### Additional information

![catvid-smol](https://user-images.githubusercontent.com/28617290/157560358-e692c25d-ede4-4a13-9522-7c7df24cfeb1.jpg)

**Comment by Roy-Orbison** [comment]
Thanks @SameenAhnaf, I did search but didn't find that issue (there are many!)

**Comment by vhda** [comment]
I'm unable to access the queue from the notification under Android 12, one ui 4.1, Samsung phone. I also can't find any menu button referring the queue. Did this regress?

Thanks in advance.

**Comment by opusforlife2** [comment]
@vhda What happens when you tap on the notification?

**Comment by vhda** [comment]
@opusforlife2 I can move forward and backward the queue, but I can't *access* the queue. I'd like to see what is queued next, or even reorder the queue.

**Comment by opusforlife2** [comment]
@vhda I don't mean tapping the buttons. I mean tapping the space apart from the buttons.

**Comment by Roy-Orbison** [comment]
@vhda @opusforlife2 This issue was closed as a duplicate. If you want to track its progress, go to #3515, but don't add to the noise with comments that don't help others, we're all aware of the problem.

**Comment by opusforlife2** [comment]
@Roy-Orbison If you're worried about noise, you can easily unsubscribe. We don't have Discussions enabled, so closed issues are a good place to help users without adding noise to _open_ issues. I'm sure you're subscribed to 3515 already.

**Comment by Roy-Orbison** [comment]
@opusforlife2 I already unsubscribed, but thanks for the @.
