### ISSUE TITLE
updater inside app for don't need separate app to look if have update

### ISSUE THREAD

**Issue by seba2282** [TeamNewPipe/NewPipe#8010]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Updater inside new pipe

### Why do you want this feature?

Is easier know if is new version and to update from new pipe app. And to my suggestion idea please add notifications too when new version and for possible update options like automatic, or only inform and update manually. How much apps has inside them for don't need separate apps or find by browser after new versions

**Comment by seba2282** [comment]
I don't know if i all wrote good or checked to issue. But updater inside new pipe with notifications about if new versions was good idea for future.

**Comment by SameenAhnaf** [comment]
Rejected by devs. See: https://github.com/TeamNewPipe/NewPipe/pull/3141

**Comment by seba2282** [comment]
I observe topic what you tagged here. And if i understood good was telling about that. But that type future without F-droid is inside new pipe? Example. I download app new pipe from official site and will be see next update normally. To can update and it work?

**Comment by litetex** [comment]
Sorry, I can't understand a word.

As Sameen stated above this is a duplicate.

**Comment by seba2282** [comment]
Me didn't knew, was topic about that. So i want tell sorry if topic is duplicate. And thanks for help.

**Comment by opusforlife2** [comment]
@seba2282 Follow these instructions: https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

**Comment by seba2282** [comment]
I look in that topic from link. Thank you
