### ISSUE TITLE
Trim trailing/preceding whitespaces from search inputs

### ISSUE THREAD

**Issue by tsiflimagas** [TeamNewPipe/NewPipe#8012]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I think it would be better if trailing and/or preceding whitespaces are trimmed from search inputs. 

### Why do you want this feature?

By not having those whitespaces trimmed, it's easy to get duplicates in the search history. YouTube app does it this way too. 

### Additional information

Not sure if this could be considered a bug in some way, so pardon me for labeling it as a feature request,  if that's the case.

**Comment by dtcxzyw** [comment]
It's really weird not to trim the whitespaces in the search string. If you think this enhancement is necessary, I'll be happy to help.

**Comment by TiA4f8R** [comment]
> If you think this enhancement is necessary, I'll be happy to help

You can implement this feature, but keep in mind you should add a database migration to remove duplicate entries to keep the trimmed ones.
