### ISSUE TITLE
red dot notification on youtube channel icon not showing

### ISSUE THREAD

**Issue by lukaszzankiety** [TeamNewPipe/NewPipe#8015]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. subscribe channel
2. watch videos
3. when new video show up on channel, there is no more red dot on channel icon in subscribed tab.

### Expected behavior

In previous version red dot icon show up on channel icon, in subscribe tab, when nev video was added to channel.
Please bring it back. 

### Actual behavior

In previous version red dot icon show up on channel icon, in subscribe tab when nev video was added to channel.
Red dot not showing and i have to open every channel one by one to check new videos. Please repair this.

### Screenshots/Screen recordings

<img alt="noreddot" src="https://user-images.githubusercontent.com/99500533/158009704-258dc516-f1d0-4833-a701-af661f69c688.png" height=600 />
<img alt="howitshoullook" src="https://user-images.githubusercontent.com/99500533/158009706-4675529f-31ea-4045-881f-ca10900eacc2.png" height=600 />

### Logs

no crash

### Affected Android/Custom ROM version

android 11

### Affected device model

motorola g60 XT2135-2, huawei P Smart 2019 POT-LX1

### Additional information

This dots worked in previous versions (20.x.x or 21.x.x i think)

**Comment by opusforlife2** [comment]
> Red dot not showing and i have to open every channel one by one to check new videos. 

Why not use the What's New feed? `Settings > Content > Content of main page > Floating action button`.
