### ISSUE TITLE
Share with current timestamp

### ISSUE THREAD

**Issue by lurlo** [TeamNewPipe/NewPipe#8018]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add the `?t=seconds` to url with current timestamp

### Why do you want this feature?

The manual proccess is very time expensive:
- get link (e.g. https://youtu.be/CODE)
- get time (e.g. 1:30)
- convert to seconds (e.g. 90)
- add to url (https://youtu.be/CODE?t=90)

The Youtube website do this automatically

**Comment by AzaleeBleue** [comment]
There is a second share button that will share the video at the time it currently is.
Once the playing has started, you can access it through the upper right arrow.
![Screenshot_20220312-174201_NewPipe_1](https://user-images.githubusercontent.com/73590822/158026829-9db789a6-1b1d-4f19-b567-2a3cb9fa7266.png)
![Screenshot_20220312-174209_Système_Android_1](https://user-images.githubusercontent.com/73590822/158026857-9189a33c-9a77-4fc9-b2ad-332454f1ae7a.png)

**Comment by litetex** [comment]
@SameenAhnaf
I think I read recently an issue about the same topic where you participated.
However I'm unable to find it...
Do you coincidentally have a link?

**Comment by SameenAhnaf** [comment]
@litetex https://github.com/TeamNewPipe/NewPipe/issues/7835

**Comment by opusforlife2** [comment]
@SameenAhnaf `<td rowspan="4">`

**Comment by opusforlife2** [comment]
Answered in 1st reply.

**Comment by opusforlife2** [comment]
Duplicate of #7835
