### ISSUE TITLE
Watching unlisted vids 

### ISSUE THREAD

**Issue by Raif1** [TeamNewPipe/NewPipe#8022]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I want watch "unlisted" tagged vids on newpipe.

### Why do you want this feature?

To view unlisted vids

**Comment by SameenAhnaf** [comment]
You can watch unlisted videos by sharing the video link to Newpipe or pastung the link on search bar.

**Comment by Raif1** [comment]
But i need to find each video link to watch them from a channel

**Comment by SameenAhnaf** [comment]
I don't think Google would expose such info absolutely for free.

**Comment by Raif1** [comment]
Why u do think? Isnt this supposed to be publicly accessable by everyone? This aint any secret

**Comment by SameenAhnaf** [comment]
Do you know any project which could implement this?

**Comment by Raif1** [comment]
I guess this . cant find any. I think theres a site to watch and find unlisted vids.But u need to find the vids via searching the title.And u cant view unlisted vids from a certain yt channel.Plus most fo the time i cant find the vid i want.

Uaa the site is **_https://unlistedvideos.com/indexm.html_**

**Comment by litetex** [comment]
> I want watch "unlisted" tagged vids on newpipe.

You can watch unlisted videos in NewPipe.
However you can't find them with the search (that queries youtube) because they are *unlisted*.

I don't see any resolution to this unless we implement a search engine into the app which is a complete overkill or some proprietary service.

Closing this for now.

**Comment by Raif1** [comment]
Well it will be usefull for me i guess hope the issue gets opened again
