### ISSUE TITLE
How can I find out which subscriptions aren't loading?

### ISSUE THREAD

**Issue by Etim-Orb** [TeamNewPipe/NewPipe#8026]
When I fetch my video feed there are a few channels that are "Not loaded". How could I find out which ones it is?

**Comment by litetex** [comment]
1. Please use [a template](https://github.com/TeamNewPipe/NewPipe/issues/new/choose) when opening an issue.
2. That is a valid problem. I recommend creating a new feature request for a better UI where this can be displayed.
3. As a workaround: Under "subscriptions" you can create channel groups. When you click on a channel group (e.g. "All") it shows you the feed for that channels. You can use it to narrow down the problem.

**Comment by Etim-Orb** [comment]
@litetex Thank you for the response, I currently use a 3rd party client and issue templates seem to be broken. I will make sure to open a new issue.
