### ISSUE TITLE
In light of Vanced's discontinuation

### ISSUE THREAD

**Issue by CONIGUERO** [TeamNewPipe/NewPipe#8027]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Considering YouTube Vanced decided to shut down after recieving a C&D letter from Google/YouTube, I think it's important to ask these questions:

In case of a similar letter by Google/YouTube, will you shut down too?

Do you have the resources to afford ignoring it/fighting back? Is hiring a lawyer possible with the donation pool you currently have?

**Comment by litetex** [comment]
> I made sure that there are no existing issues

→ #8025
