### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.node...

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#804]
https://sentry.schabi.org/sentry/newpipe/issues/670/

```
Stacktrace (aktuellster Aufruf als erstes):

  File "Thread.java", line 818, in run
  File "ThreadPoolExecutor.java", line 588, in run
  File "ThreadPoolExecutor.java", line 1113, in runWorker
  File "ScheduledThreadPoolExecutor.java", line 269, in run
  File "FutureTask.java", line 237, in run
  File "ScheduledRunnable.java", line 52, in call
  File "ScheduledRunnable.java", line 61, in run
  File "Scheduler.java", line 452, in run
  File "SingleSubscribeOn.java", line 89, in run
  File "Single.java", line 2700, in subscribe
...
(551 additional frame(s) were not displayed)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference 
```

**Comment by theScrabi** [comment]
It's fixed, but we should consider to release soon, since this affects a loot of people right now.

**Comment by theScrabi** [comment]
If we need a little longer on v0.11.0 I could create a v0.10.2 and just fix this on the master branch.

**Comment by wb9688** [comment]
I think we'll need a bit longer for v0.11, so I guess you could cherry-pick
the fix.

Off-topic: I think we should do https://stackoverflow.com/a/30838648
instead of the current ParallaxScroll.

**Comment by karyogamy** [comment]
Can someone add me on Sentry? I'd like to see the full error report, though I understand it's already fixed.

**Comment by theScrabi** [comment]
@wb9688 A fix for our parallax scroll is on the way, and already merged. I asked over at their github page.

**Comment by wb9688** [comment]
@theScrabi: I saw that, but I still think that'd be the better way.

**Comment by theScrabi** [comment]
If you can make it that it will look like it does right now I'd be ok with it :)

**Comment by theScrabi** [comment]
I release v0.10.2 with the fix.

**Comment by bhumikash-tech** [comment]
What is the solution to the mentioned problem ?
