### ISSUE TITLE
i can't import youtube subscriptions on newpipe

### ISSUE THREAD

**Issue by juertus** [TeamNewPipe/NewPipe#8040]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. I downloaded new pipe app.
2. Open and go to the import subscriptions.
3. Choose youtube and import subscriptions.csv

### Expected behavior

I just want import my youtube subscriptions. Thanks

### Actual behavior

I just download Newpipe to my phone. And ı want import my youtube subscriptions. But app always app crashing itself.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ TR
* __Content Language:__ tr-TR
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@2266c47 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{6fc764 8863:org.schabi.newpipe/u0a235} (pid=8863, uid=10235) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4657)
	at android.app.ActivityThread.access$2000(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{6fc764 8863:org.schabi.newpipe/u0a235} (pid=8863, uid=10235) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5890)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6973)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3339)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1675)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1622)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

android 12/ crDroid 8.2

### Affected device model

Xiaomi Redmi Note 8

**Comment by Pokemetti** [comment]
This feature is not there to import the subscriptions from official Youtube but from another Newpipe version (It's a json file and can include a lot of other things such as settings, local playlists and histories). Thus this isn't a bug but a feature request to make it possible to import subscriptions from the Youtube subscriptions.csv .

**Comment by s4980** [comment]
Are you sure @Pokemetti ??
The Import screen gives you instructions how to generate csv with your subscriptions from a YouTube service using takeout.google.com page.
For me this sounds like a functionality that should allow you to import your subscriptions from YouTube and another Newpipe.

**Comment by augt** [comment]
The file you get when you export your youtube subscriptions from google take out used to be a json file up util a few months ago. Now that file file has a "csv" extentions it doesn't work anymore. I'm looking for a way to convert this csv file to json.

**Comment by Pokemetti** [comment]
I actually didn't consider that option, thanks @s4980 . But I tried it with a csv file and it worked for me. That CSV file is pretty old though, so maybe the format somehow changed.

**Comment by xchimx** [comment]
this problem still exist, any solutions yet?

**Comment by juertus** [comment]
> this problem still exist, any solutions yet?

Yes, the solution is simple.  By not using it....

**Comment by xchimx** [comment]
> > this problem still exist, any solutions yet?
> 
> Yes, the solution is simple. By not using it....

Well...this version fix the problems: [v0.23.0](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.23.0)

**Comment by juertus** [comment]
> > > this problem still exist, any solutions yet?
> > 
> > 
> > Yes, the solution is simple. By not using it....
> 
> Well...this version fix the problems: [v0.23.0](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.23.0)

Oh really? I'll try. Thanks

**Comment by CostaRich** [comment]
I just downloaded 0.25.0 and it would not import my Youtube subscriptions. I went through the instructions provided onscreen in NewPipe and it apparently doesn't understand the format that youtube/google is now using.  So I wrote a little go program on this playground below and pasted the csv file results into the bottom of the doc and then put the json formatted text in a file and put it on an sd card for newpipe to import.  And that worked fine.    You are welcome to try using the process below.

https://go.dev/play/p/xAMP268Tae_1

**Comment by Waldorf3** [comment]
Why is this closed, it's still not working as of today.  How do you expect people to move from Youtube to Newpipe if there is no way to transfer your history over?

**Comment by aeroncastle** [comment]
Why is this issue closed? Nothing was done about it and the import function doesn't work despite the gaslighting in the FAQ and here. Wtf. It's maddening to try I don't know how many times to do a thing and you guys do this on purpose with people. In the moment you discovered that YouTube changed everything and nothing worked anymore your guys should have written so in the FAQ. Even better would be to fix it, but not gaslighting people is good enough.

**Comment by Pokemetti** [comment]
Can you guys chill? This is an open-source project, you guys are getting software for free and yet you complain like the writers owe you anything. The reason this issue was closed was probably because noone wanted to implement this feature is what I'm guessing.
If you want this feature so badly anyways, learn to program Android apps, add this feature to the source code and open a pull request. Sit down, be humble, and maybe try to write a little more respectfully ("gaslighting"? sure, the devs *definitely* didn't just forget to update the FAQ or whatever, they definitely did it *on purpose*).

**Comment by Xoias** [comment]
I am facing the same issue with the 0.26.1 version. Any solution for this issue? I am not well versed with coding, so I will appreciate a bit of detail on the steps to follow. Thanks in advance for the good tips :)

**Comment by Xoias** [comment]
> > > this problem still exist, any solutions yet?
> > 
> > Yes, the solution is simple. By not using it....
> 
> Well...this version fix the problems: [v0.23.0](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.23.0)

At least in my case, it seems that the only way was to install the 0.23 version in order to import the subscriptions. Only afterwards, you can upgrade/install the last version.
Thanks!

**Comment by aeroncastle** [comment]
the feature has been dead for 2 years now, the appearance of it in the app is just to bait you in thinking it is something that is possible to do

**Comment by lukstafi** [comment]
Note: I couldn't import a file from Google Drive, after reading through the discussion here and scratching my head, I downloaded the file, selected the local file (using the same UI), it worked.

**Comment by GALVATRON-GALVATRON** [comment]
> Note: I couldn't import a file from Google Drive, after reading through the discussion here and scratching my head, I downloaded the file, selected the local file (using the same UI), it worked.


The CSV file worked for you on which version of newpipe?

**Comment by lukstafi** [comment]
> 
> The CSV file worked for you on which version of newpipe?

0.25.2.

As someone noted on another issue I brought it up, it's likely an Android / Google Drive problem rather than NewPipe.

**Comment by survivor303** [comment]
google dosnt make csv file from subscriptions anymore, the zip has only html on it, which is just a catalog of the takeout and it is empty.

**Comment by webmediart-github** [comment]
> I just downloaded 0.25.0 and it would not import my Youtube subscriptions. I went through the instructions provided onscreen in NewPipe and it apparently doesn't understand the format that youtube/google is now using.  So I wrote a little go program on this playground below and pasted the csv file results into the bottom of the doc and then put the json formatted text in a file and put it on an sd card for newpipe to import.  And that worked fine.    You are welcome to try using the process below.
> 
> https://go.dev/play/p/xAMP268Tae_1
> 

I think there is missing an output. At least on my end I cannot see any converted output. :(

**Comment by jfefleming** [comment]
> > https://go.dev/play/p/xAMP268Tae_1
> 
> I think there is missing an output. At least on my end I cannot see any converted output. :(

At the bottom, below the script, you'll see a line of text which you need to save down into a text editor and save as a .csv.

Interestingly, the output worked for me with LibreTube, but while NewPipe says it has imported, its not showing the subscriptions.
