### ISSUE TITLE
the word "доступность"

### ISSUE THREAD

**Issue by IErnest134** [TeamNewPipe/NewPipe#8042]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Open any video;
2. Open description (the language of the program must be Russian)

### Expected behavior

The word "доступность" must be spelled correctly

### Actual behavior

From the word "доступность" the last letter moved down

### Screenshots/Screen recordings

<img alt="NewPipe" src="https://user-images.githubusercontent.com/99507421/158452917-692681c2-41dc-45a6-9289-4aea1466c66e.jpg" height=600 />

### Affected Android/Custom ROM version

android 10

### Affected device model

Huawei P smart 2021

**Comment by litetex** [comment]
> The word "доступность" must be spelled correctly

Is there a typo inside the word? If so you can edit it on weblate (→ https://hosted.weblate.org/engage/newpipe/).

> From the word "доступность" the last letter moved down

This is intended because there is not enough space left.

**Comment by bolshoytoster** [comment]
@IErnest134 @litetex  it looks like it's just wrapping to the next line.

It would probably look better with a `-` though. i.e.:
```
доступнос-
ть
```
I can probably do this if it would be good solution.

**Comment by bolshoytoster** [comment]
@IErnest134 @litetex  it looks like it's just wrapping to the next line.

It would probably look better with a `-` though. i.e.:
```
доступнос-
ть
```
I can probably do this if it would be good solution.
