### ISSUE TITLE
Modify trending tab

### ISSUE THREAD

**Issue by john325** [TeamNewPipe/NewPipe#8047]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I want newpipe to have the ability to customize the trending tab, change the videos of trending.

### Why do you want this feature?

I want to see content that i like, the content on trending is irrelevant for me, thx

**Comment by SameenAhnaf** [comment]
@john325 Are you looking for https://github.com/TeamNewPipe/NewPipe/issues/1805?

**Comment by ericjs** [comment]
> If you want to see videos you like, why not check your subscription feed for that? The very definition of "trending" videos is videos that are a big hit, so what's the point in changing them?

Unfortunately, as far as I can tell, you can't open NewPipe without having to see the dumpster fire of stupid nonsense that is what's usually trending on you tube.
