### ISSUE TITLE
display the list of not loaded subscriptions

### ISSUE THREAD

**Issue by dev-a** [TeamNewPipe/NewPipe#8055]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hello I have more than 100 subscriptions with newpipe.
Tonight I notice that 24 subscriptions are not loaded. (maybe there is a bug behind this)
However, there is no way to see the 24 subscriptions not loaded. (in the past it seems that the name of the subscription was listed but it was not user friendly, it's better that way)

### Why do you want this feature?

I think that it could be interesting to put in gray or red level the not loaded feeds in the activity subscriptions ( this one :
https://github.com/TeamNewPipe/NewPipe/blob/dev/fastlane/metadata/android/en-US/images/phoneScreenshots/shot_02.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
+1 im also having trouble finding out what is not being loaded. If i cross reference with FT i do not notice any videos missing

**Comment by janTaja** [comment]
I suspect there is a bug with the extractor that counts some channels as not loaded because of some error, even though it does load at least the recent videos. I’ll open an issue for the extractor.

Being able to see the list of not loaded channels would still be a great feature, though.

**Comment by janTaja** [comment]
And this issue is a dublicate of #7201
