### ISSUE TITLE
Automatically add email address to send bug report

### ISSUE THREAD

**Issue by fabmazz** [TeamNewPipe/NewPipe#806]
When a bug happens, it will be nice to have the email address automatically added in the intent, so that it's easier to send a bug report to the development team.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by theScrabi** [comment]
Isn't it added?

**Comment by wb9688** [comment]
Here it does

**Comment by fabmazz** [comment]
I can't get the email address to send it. I'm using galaxy s7 with official Samsung android 7.0. Maybe the fault is with them.

**Comment by TobiGr** [comment]
@fabmazz Do you still have this problem?

**Comment by fabmazz** [comment]
No, I don't. I have managed to send a few bug reports actually.

Il giorno Ven 7 Dic 2018, 15:14 Tobias Groza <notifications@github.com> ha
scritto:

**Comment by TobiGr** [comment]
That's good to hear.
