### ISSUE TITLE
Videos loading very slow on first attempt

### ISSUE THREAD

**Issue by LECAGO** [TeamNewPipe/NewPipe#8070]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1, also tested on 0.22.0

### Steps to reproduce the bug

1. Play any video that has not been played in the current session (starting when app was opened)
2. Video will load continuously for ~10 seconds
3. Video plays

### Expected behavior

Video loading should take <1s, for any attempt at playing videos.

### Actual behavior

Video loading on first attempt takes ~10 seconds.

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Samsung Galaxy S7

### Additional information

This bug is not 100% consistent, sometimes videos can load in <1s on first attempt. However switching to fullscreen before loading is completed will always cause the video to load slowly / infinitely. I also tested on version 0.22.0, and the same issue occurs, likely it is an API problem.

**Comment by Kromppo** [comment]
I also started noticing this issue recently. I'm Not sure if it started right when I updated to 0.22.1 or after, but it's been going on for about a week or two. Came here to make a big report and saw this post. The video will usually load quickly if you manually switch to a different resolution, even if the resolution you switch to is higher.

I'm currently running:
Android 11 February Update
OxygenOS 11.0.15.17.KB09CB
Rooted

**Comment by LECAGO** [comment]
> I also started noticing this issue recently. I'm Not sure if it started right when I updated to 0.22.1 or after, but it's been going on for about a week or two. Came here to make a big report and saw this post. The video will usually load quickly if you manually switch to a different resolution, even if the resolution you switch to is higher.
> 
> I'm currently running: Android 11 February Update OxygenOS 11.0.15.17.KB09CB Rooted

It started happening roughly a week after 0.22.1 release
