### ISSUE TITLE
shorts

### ISSUE THREAD

**Issue by Artemis-Arrow** [TeamNewPipe/NewPipe#8074]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

you know youtube shorts? yeah that

### Why do you want this feature?

it'd make watching vids that were originally posted to shorts more convenient, and btw

**Comment by mhmdanas** [comment]
Please clarify your request. NewPipe already supports YouTube shorts.
