### ISSUE TITLE
Mark as watched all videos on channels feed

### ISSUE THREAD

**Issue by miquecg** [TeamNewPipe/NewPipe#8078]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like to quickly mark as watched all videos listed on channels feeds. More or less like a feed reader where you can just mark everything as read and keep your count at zero.

### Why do you want this feature?

When I go through the list I usually watch a few videos, maybe save a few others to a list and, if implemented, I'd like to mark the rest as watched so next day they are no longer there. This is because I treat the feed as an inbox.

I recognize the feature is not critical per-se as long as I remember where I left it but sure it will be nice to have. Moreover, when you add a new channel to a feed all the recent history of videos appear and it's really annoying.

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7231

**Comment by miquecg** [comment]
Yeah, that's it. Closing.
