### ISSUE TITLE
Bitchute and Odysee support

### ISSUE THREAD

**Issue by Destroyinator69420** [TeamNewPipe/NewPipe#8079]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Both Bitchute and Odysee use p2p networks to distribute their videos, which means it would be very easy to integrate them into the newpipe extractor. Bitchute uses webtorrent, and Odysee uses the lbry protocol.

### Why do you want this feature?

I sometimes use bitchute and odysee when I want to follow YouTube's that do bitchute and odysee exclusives or just to watch without google watching too.

### Additional information

Both Bitchute and Odysee use p2p networks. Bitchute uses webtorrent, and Odysee uses its own protocol called lbry. For reference, Bitchute uses the same webtorrent as Peertube, so integrating Bitchute should be very easy.

**Comment by SameenAhnaf** [comment]
Service requests go to [Newpipe Extractor](https://github.com/TeamNewPipe/NewPipeExtractor)
