### ISSUE TITLE
Add more tests for methods involving the database

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#8080]
### Checklist

- [X] This issue contains only one bug.
- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.

### Affected version

Every version, but in particular this issue was opened after #2335

### The problem

We should add more tests for methods that query/use the database, after mocking the NewPipeExtractor. These kind of tests would not be too difficult to do (android tests would, instead, I think), but would anyway allow us to ensure things work correctly faster. For example we could start by adding a test for the [`SubscriptionManager.rememberAllStreams()`](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt#L126) method introduced in #2335, see https://github.com/TeamNewPipe/NewPipe/pull/2335#discussion_r764894903.

**Comment by Stypox** [comment]
Also e.g. #2758 should be testable

**Comment by SydneyDrone** [comment]
I would like to work on this issue. I'm new to open source, so can someone walk me through the process ?

**Comment by ktprograms** [comment]
@SydneyDrone Sure, I'd be glad to.

Do you have experience with Git?

The general process is:
- Fork the repo in GitHub
- Clone your fork
- Create a feature branch
- Make your changes and commit them
- Push the feature branch to your fork
- Make a pull request from your feature branch to NewPipe's `dev` branch

**Comment by SydneyDrone** [comment]
@ktprograms Sorry my mistake:(
I have no problem using git, but it's the first time for me to write database tests, so if there is a quickstart  maybe I can finish it more quickly.

**Comment by Stypox** [comment]
@SydneyDrone you could for example copy this other database test into a new file and then make changes based on it: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt

Put the newly created file in the same java package as the file it is supposed to test (just under androidTest/ instead of main/)

**Comment by SydneyDrone** [comment]
> @SydneyDrone you could for example copy this other database test into a new file and then make changes based on it: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt
> 
> Put the newly created file in the same java package as the file it is supposed to test (just under androidTest/ instead of main/)

@Stypox Thank you, I'll give it a shot.

**Comment by MustkimKhatik** [comment]
@SydneyDrone you are working on this issue right now ?

**Comment by SydneyDrone** [comment]
@MustkimKhatik Yes, I'm currently working on this issue.
