### ISSUE TITLE
"Copy link" and "Copy link with actual timestamp" buttons

### ISSUE THREAD

**Issue by horvathlaszlogyorgy** [TeamNewPipe/NewPipe#8087]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The YouTube Vanced app has two buttons in the video player:
- the first button copies the current video URL to the clipboard
- the second button works similarly, but also puts the current time in the URL parameters

Screenshot:

![](https://i.ibb.co/jTyHJQ1/Screenshot-20220320-204105.jpg)

### Why do you want this feature?

Because it is convenient.

### Additional information

How "t" parameter works: https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414

**Comment by SameenAhnaf** [comment]
See: https://github.com/TeamNewPipe/NewPipe/issues/6543

**Comment by horvathlaszlogyorgy** [comment]
@SameenAhnaf @TiA4f8R 
Yeah, I found this feature, however, it cannot handle the timestamps. In addition, the feature I requested is much more user friendly in my opinion. Please reopen the issue, if possible.

**Comment by TiA4f8R** [comment]
> it cannot handle the timestamp

Are you talking about the YouTube app? Because I checked with websites and they can handle the timestamps properly.

**Comment by horvathlaszlogyorgy** [comment]
@TiA4f8R Yes you are right, but it also shows that the current implementation is not clear

**Comment by horvathlaszlogyorgy** [comment]
@TiA4f8R 

![](https://i.ibb.co/x5Qzyzr/Screenshot-20220320-211729-New-Pipe.jpg)

**Comment by opusforlife2** [comment]
@horvathlaszlogyorgy This is a new feature request, different from the one in the OP. Please open a new issue.
