### ISSUE TITLE
Feed not loading Channels.

### ISSUE THREAD

**Issue by Jodast11** [TeamNewPipe/NewPipe#8091]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

When I refresh the "What's New" feed, I get the message "Not loaded: 25".
After some experimenting I noticed this only affect subscriptions, where shorts have been uploaded.
After I removed all subscriptions that had once uploaded shorts, I didn't get this message anymore.
One example of such an channel would be "Dude Perfect" (https://www.youtube.com/c/DudePerfect).

### Expected behavior

I expect all feeds to be updated.

### Actual behavior

I get the message "Not loaded: 25"

### Affected Android/Custom ROM version

Android 11

### Affected device model

Motorolla G8 Power

**Comment by aaronhuggins** [comment]
I can confirm that this is happening to me, too. No error messages or opportunity for debug log.

Android 11, Pixel 4, NewPipe v0.22.1

**Comment by aaronhuggins** [comment]
Related to #8034, probably can close as this is being worked there.

**Comment by Jodast11** [comment]
Ok, thanks!
