### ISSUE TITLE
Tune up or down video by semitone

### ISSUE THREAD

**Issue by AlexSanga** [TeamNewPipe/NewPipe#8099]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hi Guys, great job on this app NewPipe on android.
A feauture already exists to pitch up or down, works well. the problem is that the setup proposed to user is to pitch by %
For changing speed it is ok . To pitch ,% doesnt mean nothing  , especially for musicians like me
Would be so great to implement pitching by semitone up or down. A semi tone is the space between 2 notes : E and F, C and C# etc..
You have this free feature implemented in audacity software
![image](https://user-images.githubusercontent.com/10711324/159890306-0d5326d0-0e6b-4a29-ba57-d02ed53c5c96.png)

### Why do you want this feature?

For musician or singer purpose
pitching by % doesnt make any sense.

**Comment by SameenAhnaf** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/7565 is expected to be included in next release.
