### ISSUE TITLE
Add Rutube service to NewPipe

### ISSUE THREAD

**Issue by 5EOTlGWT** [TeamNewPipe/NewPipe#8104]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like to thank the team very much for best android os-application!

I turn to russian developers...
Add please Rutube service to NewPipe

Thanks again to the whole team

### Why do you want this feature?

Expand the possibilities and improve the application
YouTube is heavily censored

### Additional information

and think about others... Vimeo, more services Peertube to default...

**Comment by SameenAhnaf** [comment]
Service requests go to [Newpipe Extractor](https://github.com/TeamNewPipe/NewPipeExtractor). For Vimeo, see: https://github.com/TeamNewPipe/NewPipeExtractor/issues/690

**Comment by TacoTheDank** [comment]
> I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).

**Comment by TacoTheDank** [comment]
> I would like to thank the team very much for best android os-application!

Also thank you, we do indeed try our best to improve the app wherever possible :)

**Comment by opusforlife2** [comment]
> I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).

_Sigh._

**Comment by DI555** [comment]
whanted to post the same issue, but found it already requested 👍 .
