### ISSUE TITLE
Cant see views and subs counter since v0.10.1

### ISSUE THREAD

**Issue by r2308145** [TeamNewPipe/NewPipe#811]
Until v0.10.0 I could see number of views of every video and number of subs of every channel, but since v0.10.1 this disappeared and the only thing I can see are likes and dislikes of certain video.. The newest version 0.11.0 didnt fix this... thinking of returning to v0.10.0 because of that

**Comment by wb9688** [comment]
Could you give an example of a video and a channel where it fails?

**Comment by theScrabi** [comment]
Please send a screenshot.

**Comment by r2308145** [comment]
here are the screens if it helps: https://imgur.com/a/M25Ce

it doesnt matter which channel or video I browse, the number of views/subs simple is nowhere.. btw tried to install newpipe to my 2nd phone and it is the same problem

**Comment by wb9688** [comment]
It works here:

![Screenshot](https://i.imgur.com/AMn2W5A.png)

What have you set as content language? And what's your phone's language?

**Comment by r2308145** [comment]
yeah it works for you.. for me it looked like that until v0.10

content is english (US), phone is czech.. but I dont think thats related

**Comment by theScrabi** [comment]
You could try to change your system language, and see if you can see something then.

**Comment by r2308145** [comment]
thanks, that fixed it! I forgot that since v0.10.1 the newpipe UI uses the system language as default..

this brings me to a question if more languages will be supported in the future (i.e czech) or if we could have an option in the newpipe settings to change not only the content language but the app UI language aswell

**Comment by r2308145** [comment]
Thanks for help! You can tag this thread as solved for now but would be good if the issue described here will be assesed somehow... it's quite annonying when you have to change the system language of the phone just to be able to see the views/subs numbers

**Comment by theScrabi** [comment]
Maybe the strings involved got translated wrongly into czech. That most likely rases no exception, but it wouldn't work anyway.

**Comment by r2308145** [comment]
But until v0.10 it worked? Im not sure what exactly you mean by your comment.. I would rather use newpipe in english than not be able to see the counts

**Comment by theScrabi** [comment]
Could be that that special string changed from 0.10.0 to 0.10.1.

**Comment by r2308145** [comment]
ok, I hoped it is rather a bug that can be fixed in the future... would hate to have to change the system language everytime before launching the app

**Comment by TobiGr** [comment]
@r2308145 Do the words view/views have the same translations for singular and plural in Czech? It seems to be like that, because they are translated the same:
```    
<plurals name="views">
	<item quantity="one">%s shlédnutí</item>
	<item quantity="few">%s shlédnutí</item>
	<item quantity="many">%s shlédnutí</item>
```

**Comment by r2308145** [comment]
@TobiGr that is indeed the case.. but correct translation for views in this case its not "shlédnutí" but "zhlédnutí"

**Comment by TobiGr** [comment]
@r2308145 If you want, you can correct it [here](https://hosted.weblate.org/translate/newpipe/strings/cs/?checksum=9e3838a1ab55a0d3) and help us to complete the Czech translation. You can login to our Weblate service using your GitHub account.
@theScrabi With 0.10.0 @mauriciocolli added the `plurals` and in 0.10.1 they were translated to Czech. So I guess there is a problem with them.

**Comment by TobiGr** [comment]
Why is there a `<item quantity="other"/>`? That must be the reason. We should replace `<item quantity="many">%s shlédnutí</item>` with `<item quantity="other">%s zhlédnutí</item>`.

**Comment by r2308145** [comment]
@TobiGr I logged in and may give it a try but the Weblate UI is a little bit confusing for me... as for the <item quantity="other"/> that maybe is the problem causing the issue

**Comment by TobiGr** [comment]
I think we'll need to fix the `<item quantity="other"/>` problem manually in the source code. I can do this.

**Comment by r2308145** [comment]
that would be really great.. meanwhile I was trying to complete the czech translation + also corrected a lot of mistranslated stuff

**Comment by karyogamy** [comment]
@r2308145 The latest update brings in play queue, hold-to-append lets you enqueue a video/audio to an existing queue by holding down the backgrounf/popup button on the details page.

**Comment by r2308145** [comment]
@karyogamy yeah I know what it does now, but dont think the english formulation of this function is the best thus find a way to translate it correctly wasnt easy
