### ISSUE TITLE
Scrobbler for NewPipe

### ISSUE THREAD

**Issue by goodcoderfromeurope** [TeamNewPipe/NewPipe#8113]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

I'm looking for working scrobbler for NewPipe.
Thanks in advance for any help.

**Comment by litetex** [comment]
Not sure if this is a question in the first place because there are no questions inside...

Also as far as I know there is no scrobbler for NewPipe, see https://github.com/TeamNewPipe/NewPipeExtractor/issues/426

**Comment by oddtoddy** [comment]
Scroball is working fine for me. https://play.google.com/store/apps/details?id=com.peterjosling.scroball&hl=en_US&gl=US
