### ISSUE TITLE
Moto Display showing pixelated and enlarged album art covers

### ISSUE THREAD

**Issue by AndresPzaa** [TeamNewPipe/NewPipe#8116]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Play a music video or song in the background
2. Lock your Motorola device 
3. Move your Motorola device for Moto Display to show up
4. You will see the album art (cover) is blurry and doesn't fit the screen well

### Expected behavior

I expect a normal size album art cover with good resolution like this example
<img alt="160257402-90c3e885-265a-47d9-9b65-c4ecc80b43a3" src="https://user-images.githubusercontent.com/40789489/160292306-5c0ad150-36c8-4952-b1f8-44ce3af32c1b.jpg" height=600 />

### Actual behavior

It's very pixelated and enlarged 
<img src="https://user-images.githubusercontent.com/40789489/160292321-7f7bb379-9840-49c5-a0f3-70460a122baa.jpg" height=500 />

### Affected Android/Custom ROM version

Android 11 

### Affected device model

Moto g31

### Additional information

Moto Display Is a feature for all Motorola phones, which is a way to access notifications quick and easy, without opening your phone. there are countless examples of Music Players working with this feature, one of the more popular ones being youtube Music and Spotify.

**Comment by litetex** [comment]
I don't think we can fix this:

* NewPipe gets a thumbnail from the corresponding service, that has a limited size (so that it doesn't needs much data).
* NewPipe displays this thumbnail - which works as expected on every normal/stock android device
* "Moto Display" stretches/zooms the thumbnails so that it fits onto the complete screen (horizontally) → it gets pixelated

I would recommend disabling Moto Display or disable "Show thumbnail" in the Notification settings.

**Comment by Stypox** [comment]
Fixed by #9479
