### ISSUE TITLE
Is it normal for certain valid YouTube URLs to not open automatically with NewPipe?

### ISSUE THREAD

**Issue by TheMCNerd2017** [TeamNewPipe/NewPipe#8117]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Is it normal that certain valid YouTube URLs (like https://youtube.com/HashNightflux) don't open automatically in NewPipe regardless of me allowing NewPipe to handle supported links?

### Additional information

Screenshots and video of the behavior and the open by default settings for NewPipe:

<img alt="Screenshot_20220326-205009" src="https://user-images.githubusercontent.com/25375242/160261898-881db3a7-f7a4-48aa-b2eb-e744739c8b48.png" height=600 />

<img alt="Screenshot_20220326-204011" src="https://user-images.githubusercontent.com/25375242/160261710-c7bcfc04-da74-4963-acf6-142c8acb8f91.png" height=600 />

https://user-images.githubusercontent.com/25375242/160261720-1f966407-6a8f-40f1-b277-324e317044e7.mp4

**Comment by mhmdanas** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/6184.

**Comment by TheMCNerd2017** [comment]
> See #6184.

Sorry for not knowing this was an issue that was already reported. That issue for some reason never came up when I searched.
