### ISSUE TITLE
PeerTube Video Playback is skipping it self

### ISSUE THREAD

**Issue by blusewill** [TeamNewPipe/NewPipe#8119]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Playing Video on the PeerTube instance I set up (https://wiwi.video)

### Screenshots/Screen recordings

[https://youtu.be/aKqC1Zua-pE](https://youtu.be/aKqC1Zua-pE)

### Affected Android/Custom ROM version

Android 11 / OneUI 3.1

### Affected device model

Samsung Galaxy A32 5G

### Additional information

Sometimes the Video will playback fine but after sometime it's will skipping it self
The fastest way to do it it's to change the Video resolution

**Comment by opusforlife2** [comment]
This sounds similar to https://github.com/TeamNewPipe/NewPipe/pull/6307#issuecomment-841657014

Could you check this and confirm?

**Comment by blusewill** [comment]
That happend on me too but I mean when I click on the play button it's will skipping it self

**Comment by TiA4f8R** [comment]
This will be fixed when proper support of PeerTube HLS streams is added: see #8153.

**Comment by blusewill** [comment]
Ok thanks for your reply

**Comment by TiA4f8R** [comment]
Don't close the issue, please, as the bug is still in the app.
