### ISSUE TITLE
Is it possible to get the personalized feed in NewPipe?

### ISSUE THREAD

**Issue by Darkmaster006** [TeamNewPipe/NewPipe#8120]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

My question is pretty simple: is it possible to get the 'personalised feed', that is, the feed you get when you open Youtube, with the algorithm and all (maybe another algorithm) in Youtube? Kind of like the 'trending' section but with your account, maybe exporting some stuff like what you do with subscriptions? I personally do not want this, but there are some people I know that want this so I thought I'd ask.

**Comment by SameenAhnaf** [comment]
It shouldn't be impossible at least. This info could be derived from similar videos of watch history. For recommendations, see: https://github.com/TeamNewPipe/NewPipe/issues/2256. For new Trending pages, see: https://github.com/TeamNewPipe/NewPipe/issues/1805

**Comment by Darkmaster006** [comment]
> It shouldn't be impossible at least. This info could be derived from similar videos of watch history. For recommendations, see: #2256. For new Trending pages, see: #1805
Thanks, so the feature is not present but is being considered, or at least some similar features.
