### ISSUE TITLE
Constant Buffering at ~3x Playback Speed

### ISSUE THREAD

**Issue by cyphar** [TeamNewPipe/NewPipe#8128]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Play any video.
2. Set the playback speed to 3x.
4. Notice that it begins stuttering.

Even if I pause playback for several minutes, the next few minutes video do not seem to be buffered (in an issue from 2020 it was mentioned that NewPipe buffers the next 2 minutes). The same issue occurs when playing in the background (audio-only). I've had the issue occur a few times when playing at 2x speed as well, but it becomes more apparent at 3x speed.

### Expected behavior

The video should play smoothly at 3x speed, with enough of the video being buffered to provide that smooth playback.

### Actual behavior

The video buffers every 5-10 seconds or so. Sometimes it doesn't buffer as badly, sometimes it buffers worse.

### Affected Android/Custom ROM version

Android 12

### Affected device model

Google Pixel 4a

### Additional information

This is very unlikely to be an internet speed issue:

- I have a fibre connection and can play YouTube videos at >3.5x speed without buffering on my laptop over WiFi.
- I've had several instances where 2x speed also buffered pretty badly -- while the official YouTube app (and the website in the mobile browser) could easily play the same video at 2x speed.
- I can download the whole video pretty quickly through the app, indicating it's just an issue with streaming videos (or audio).
- This is a new regression, as previous releases did not have this stuttering issue (and my internet setup has not changed during that time).

**Comment by TiA4f8R** [comment]
YouTube seems to throttle more and more streams when not using the same way as YouTube stream them I'm afraid.

I am closing this issue in favor of #6949, in which you can probably find a fix for your issue :)
