### ISSUE TITLE
There should be an in-built player for downloaded audios and videos 

### ISSUE THREAD

**Issue by Saiful1919** [TeamNewPipe/NewPipe#8131]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

There should be an in-built player for downloaded audios and videos. 
And please change the red colour of app ,it is distracting during night.I think the colour of top bar should change to other colour except for red  in black theme.

### Why do you want this feature?

Red color is distracting

**Comment by TiA4f8R** [comment]
> - [x] This issue contains only one feature request

No, it doesn't.

> There should be an in-built player for downloaded audios and videos.

No, we rejected this: see #478.

Seems like you just joined GitHub, please learn to respect repositories rules such as following issue templates/forms next time.

For your second feature request, I will let you search it on our repository by looking at existing issues.

Thank you.

**Comment by SameenAhnaf** [comment]
For your second feature request, see: #7846

**Comment by Saiful1919** [comment]
@TiA4f8R i have no idea how github works, joined git recently just to raise this issue.

**Comment by opusforlife2** [comment]
@Saiful1919 No time like the present to start learning. Search for "open source etiquette" online and read a few articles.
