### ISSUE TITLE
Podczas odtwarzania muzyki przy zablokowanym ekranie nie odtwarza się sama kolojna muzyka

### ISSUE THREAD

**Issue by Squako77** [TeamNewPipe/NewPipe#8132]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Brak działania przy zablokowanym ekranie nie przewija playlisty 

### Expected behavior

Gdy aplikacja działa w tle chciałbym żeby sama się przelaczala playlista

### Actual behavior

Playlista nie przewija się tylko leci ten sam utwór albo w ogóle

**Comment by litetex** [comment]
Why are you filling in Polish sentences into a English form?

Correct them to English and reopen the issue,
