### ISSUE TITLE
What is the last version that will run for Android 4.3? 

### ISSUE THREAD

**Issue by manilenio** [TeamNewPipe/NewPipe#8133]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Because Vanced was sacked, I lost my player on my car head unit. NewPipe legacy (0.20.8) works, but the Trending tab is empty and it just loads and loads with no results. Can anybody give me the last version that will install on Android 4.3 please?

### Additional information

n/a

**Comment by opusforlife2** [comment]
Newpipe (not legacy) hasn't had support for Android 4.3 for quite a long time. The current minimum version is Android 4.4.

Newpipe-Legacy, which does support Android 4.3, doesn't have a maintainer right now to keep it up to date. If you are able to step up yourself, or know someone who could help maintain that project, you're more than welcome to let us know.

If not, you're out of luck, sorry.

**Comment by manilenio** [comment]
> Newpipe (not legacy) hasn't had support for Android 4.3 for quite a long time. The current minimum version is Android 4.4.
> 
> Newpipe-Legacy, which does support Android 4.3, doesn't have a maintainer right now to keep it up to date. If you are able to step up yourself, or know someone who could help maintain that project, you're more than welcome to let us know.
> 
> If not, you're out of luck, sorry.

Ah, that's truly unfortunate. Thank you for clarifying.
