### ISSUE TITLE
Vidéos j'aime (liked video)

### ISSUE THREAD

**Issue by Paul-HB64** [TeamNewPipe/NewPipe#8137]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Je souhaite savoir si il est possible d'accéder aux vidéos j'aime à partir de newpipe (there is an acces to liked videos on newpipe) ?

**Comment by SameenAhnaf** [comment]
At this moment, it’s not possible to import liked videos or any other playlist from YouTube account. See: https://github.com/TeamNewPipe/NewPipe/issues/1348

Also, there's an issue on functional like button. See: https://github.com/TeamNewPipe/NewPipe/issues/5159

**Comment by TiA4f8R** [comment]
En effet, comme l'a dit Sameen, ce n'est pas possible actuellement (et ce sera difficile voir impossible car notre application ne supporte pas (et ne supportera pas, pour des raisons de confidentialité, je vous laisse voir la FAQ de notre site web pour savoir pourquoi : https://newpipe.net/faq) la connexion à YouTube).

Je vous laisse regarder les tickets qu'il/elle a liés dans celui-ci.

@Paul-HB64 : Vous êtes sur un dépôt qui fonctionne en anglais, pensez donc à directement parler anglais la prochaine fois car c'est le [seul langage supporté ici](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#issue-reportingfeature-requests=). Pensez également à bien vérifier les tickets ouverts et fermés la prochaine fois !

Merci !
