### ISSUE TITLE
Can we have playlist tab in the near future ?

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#8138]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Is any chance to add playlist tab ?, I think that someone can use this pull request #3201

**Comment by sudocanttype** [comment]
It looks like that PR is dead. There may be a chance to add the playlist tab, but I don't think it is considered high priority currently.

**Comment by opusforlife2** [comment]
Don't couch your duplicate feature request as a question.
