### ISSUE TITLE
[YouTube] Downloads frequently slow down

### ISSUE THREAD

**Issue by n-buna404** [TeamNewPipe/NewPipe#8147]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Click any video.
2. Click download ( I always choose 4 threads)

### Expected behavior

Expected the download speed be fast around 3-4 MB/s consistently since I had 50mbps connection.

### Actual behavior

Initially the download speed be fast but it then throttle to 5-30kbps.
The only way to bypass is manually pause and start when see it throttle until the download finished

### Screenshots/Screen recordings

link to screen recordings
https://www18.zippyshare.com/v/FqIKCChl/file.html

### Affected Android/Custom ROM version

android 9 ( stock android)

### Affected device model

Xiaomi Mi A1

**Comment by TiA4f8R** [comment]
Unfortunately, that's YouTube which is throttling more and more streams (generally when HTTP chunk size reaches 10MB) when you are not using the same way official clients use to fetch streams.

Could you try the APK of TeamNewPipe/NewPipeExtractor#780 and see if by any chance, the issue is solved? Thank you in advance.

You may also try as a workaround to set 32 download threads.

**Comment by n-buna404** [comment]
> Unfortunately, that's YouTube which is throttling more and more streams (generally when HTTP chunk size reaches 10MB) when you are not using the same way official clients use to fetch streams.
> 
> Could you try the APK of [TeamNewPipe/NewPipeExtractor#780](https://github.com/TeamNewPipe/NewPipeExtractor/pull/780) and see if by any chance, the issue is solved? Thank you in advance.
I tested the debug apk but the issue still persists.
> You may also try as a workaround to set 32 download threads.
The workaround of 32 threads will still throttle but it takes a bit longer before the speed was throttle down.

Since it was Youtube feel free to close the issue if needed.

**Comment by NewNewPipe** [comment]
I noticed the same thing, freezing the download during or towards the end. If at the end of the download then I pause and redo the download, then it is complete.

Android 10

Current version of Newpipe 0.22.1

3 or 4 threads of downloading.

**Comment by dumdam** [comment]
> I noticed the same thing, freezing the download during or towards the end. If at the end of the download then I pause and redo the download, then it is complete.
> 
> Android 10
> 
> Current version of Newpipe 0.22.1
> 
> 3 or 4 threads of downloading.

Similar issue #4514

**Comment by moriel5** [comment]
Yeah, I remember when this started happening to me a few years ago, though at the time I thought it was due to my had cellular reception (I have always had 32 download threads set).

Nowadays, I just figured it must be YouTube throttling all connections, so I didn't think of posting a big report.
For me, it generally starts throttling at ~88-98%.

**Comment by NewNewPipe** [comment]
There is a strange problem with some video files from YT. The downloaded file in the place where originally something is shown is unchanged as if in a loop although the sound is OK. In the original YT application there is no such problem. Moreover, when the VLC player plays such a file to the end of the original time it continues to play this "looped" video significantly exceeding the original duration. Presumably the strange download occurs when there is a stop download, then I pause the download and then resume. This is mainly when I notice the strange problem.

**Comment by NewNewPipe** [comment]
This problem with incompatibility of the video downloaded via newpipe and the original is currently only noticed on one particular channel. It's not the first time this has happened, on a previous version of NP it sometimes happened too. Shadow ban??? The timeout in your program mpv also occurs when a download from that particular channel is inconsistent with the original and shows the video in a loop. Maybe I will prepare a separate topic with examples but unfortunately it will take a while through the template.
P.s. I downloaded the same video using another competing program and there is a 100% compatibility with the original as well as with the native YT.

**Comment by NewNewPipe** [comment]
![Screen-Playback time exceeded](https://user-images.githubusercontent.com/76656204/166743722-b23d7df7-3f05-49d7-bba0-b04ea4f1f6a3.jpg)

Playback time exceeded.

**Comment by NewNewPipe** [comment]
![screen-original-video-fromYT-download-via-Videoder](https://user-images.githubusercontent.com/76656204/166745609-ffcca8ae-9287-4abd-855f-5f1191b0ead8.jpg)
![screen-video-downloading-via-newpipe](https://user-images.githubusercontent.com/76656204/166745621-82fff881-a301-4492-b656-f5fa3e91b362.jpg)

First screen

Video original other download, conformity to the original.

Second screen

Video downloaded by newpipe, no match to original, image in loop and original playback time exceeded.

**Comment by moriel5** [comment]
@NewNewPipe I have seen this issue in the past, not just with NewPipe and VLC but with pretty much anything.

In all cases, it was due to slight corruption of the file, because of networking conditions, and redownloading the files (unless the source files were corrupted) fixed the issue.

**Comment by opusforlife2** [comment]
> it was due to slight corruption of the file

@NewNewPipe This entire discussion should have happened in its own issue. I've marked the latest comments as off-topic, but don't hesitate to confirm if this is indeed the case.

**Comment by NewNewPipe** [comment]
It looks like some kind of download error but strange something like shadow ban noticed only on a specific channel on several videos with the same effect of not matching the original also on previous versions of NP.
I will keep an eye on the situation on the channel, if the problem recurs I will let you know in a new topic.
Another VD program downloads the video correctly so it looks like the problem is on the NP side unfortunately.
