### ISSUE TITLE
Bug - Ability to select country for trending in latest version

### ISSUE THREAD

**Issue by Sgt-Miller** [TeamNewPipe/NewPipe#815]
Would be cool if we could select location for trending videos, like you can do on YouTube.com

**Comment by theScrabi** [comment]
You mean the country of the trending videos?

**Comment by wb9688** [comment]
I'm not sure, but isn't that also set with the content language setting?

**Comment by r2308145** [comment]
I think it is, but Kiosk ignores default content language setting as seen here (Issue 785)
https://github.com/TeamNewPipe/NewPipe/issues/785

**Comment by theScrabi** [comment]
Yep it's a bug.
