### ISSUE TITLE
Andrid Auto compatibility

### ISSUE THREAD

**Issue by fjllacer** [TeamNewPipe/NewPipe#8155]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hello

I am using NewPipe 0.22.1 on my phone and it works great.
I would like to use it in my car connecting the phone via android auto service but it is not possible as it seems it is not certified for use with android auto because I cannot select the NewPipe app as the audio app to appear in android auto, as it is possible with other apps like spotify.

Am i missing something or is it just the NewPipe app is not certified to work in android auto ?

Kind regards

**Comment by opusforlife2** [comment]
I think the last word on this was https://github.com/TeamNewPipe/NewPipe/issues/1758#issuecomment-709908869.

**Comment by litetex** [comment]
I think we can close this in favor of #1758.

**Comment by opusforlife2** [comment]
Agreed. 👍
