### ISSUE TITLE
Live News 不能播放

### ISSUE THREAD

**Issue by badfather** [TeamNewPipe/NewPipe#8163]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

NewPipe_v0.22.1

### Steps to reproduce the bug

1.
<img alt="Screenshot_2022-04-07-17-00-07" src="https://user-images.githubusercontent.com/103177970/162162973-f5dea36d-4674-4db4-84f5-376d4ecf8744.png" height=600 />

2.
<img alt="Screenshot_2022-04-07-17-02-09" src="https://user-images.githubusercontent.com/103177970/162163114-48665d5f-f5a6-45d1-af0a-21085eb8b7eb.png" height=600 />

3.
<img alt="Screenshot_2022-04-07-17-01-16" src="https://user-images.githubusercontent.com/103177970/162163190-509ce7f7-e052-4979-a433-d501906b4f66.png" height=600 />

### Screenshots/Screen recordings

<img alt="Screenshot_2022-04-07-16-47-57" src="https://user-images.githubusercontent.com/103177970/162161052-4616f01b-f438-4087-ac79-362520b937de.png" height=600 />

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ TW
* __Content Language:__ zh-TW
* __App Language:__ zh_TW
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 4.4.2 - 19
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Bad notification posted from package org.schabi.newpipe: Couldn't create icon: StatusBarIcon(pkg=org.schabi.newpipeuser=0 id=0x7f0800d1 level=0 visible=true num=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 4.4.2

### Affected device model

Redmi 1

**Comment by TiA4f8R** [comment]
Already fixed by #7977, which will be included in the next release. Thank you!
