### ISSUE TITLE
Significantly increased loading time before playing for 1080p and 1080p60 videos

### ISSUE THREAD

**Issue by j-james** [TeamNewPipe/NewPipe#8168]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Find a video that you have not watched before (so it's not cached) that offers 1080p playback.
2. Set your default playback quality to "Best resolution".
3. Open the video, and observe as the video takes anywhere between 10 and 20 seconds to begin playback on a fast connection.

### Expected behavior

The video should begin playback near-instantaneously, with maybe a second or two of preload time.

### Actual behavior

The video takes anywhere between 10-20 seconds to load before beginning playback. 

This is a performance regression from earlier versions, and was either introduced in 0.22.1 or 0.22.0.

### Affected Android/Custom ROM version

Android 12 / GrapheneOS

### Affected device model

Pixel 4a

**Comment by pc00per** [comment]
Fix merged https://github.com/TeamNewPipe/NewPipe/issues/7630 Wait for the release

**Comment by j-james** [comment]
Fantastic!
