### ISSUE TITLE
Please Add A Settings to to change Default video Orientation

### ISSUE THREAD

**Issue by Jithendra-V-Kumar** [TeamNewPipe/NewPipe#817]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
This will Be More Useful

**Comment by theScrabi** [comment]
I want to add a function that NewPipe will remember the last used orientation.

**Comment by theScrabi** [comment]
With this last screen orientation can be remembered:
https://github.com/TeamNewPipe/NewPipe/pull/895
