### ISSUE TITLE
Issue Reporting Via Email

### ISSUE THREAD

**Issue by 4181715** [TeamNewPipe/NewPipe#8171]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Tried submitting issue via email

### Expected behavior

Email to be received

### Actual behavior

The following message to <crashreport@newpipe.schabi.org> was undeliverable.
The reason for the problem:
5.1.0 - Unknown address error 530-'5.7.0 Must issue a STARTTLS command first'

Reporting-MTA: dns; ipmail06.adl3.internode.on.net

Final-Recipient: rfc822;crashreport@newpipe.schabi.org
Action: failed
Status: 5.0.0 (permanent failure)
Remote-MTA: dns; [88.99.208.206]
Diagnostic-Code: smtp; 5.1.0 - Unknown address error 530-'5.7.0 Must issue a STARTTLS command first' (delivery attempts: 0)

### Affected Android/Custom ROM version

Android 10

### Affected device model

Motorola G7 Plus

**Comment by litetex** [comment]
> Must issue a STARTTLS command first

You are trying to transmit an email unencrypted. Enable encryption.
See also https://en.wikipedia.org/wiki/Opportunistic_TLS
