### ISSUE TITLE
Is there a way to make NewPipe look more like the real Youtube App?

### ISSUE THREAD

**Issue by magicweirdoo** [TeamNewPipe/NewPipe#8174]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Is there a way to make NewPipe look more like the real Youtube App?
Or would you be able to do that?

**Comment by SameenAhnaf** [comment]
You may keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/7047 with your suggestions.

**Comment by litetex** [comment]
> Is there a way to make NewPipe look more like the real Youtube App?
> Or would you be able to do that?

Yes and yes, however we won't do so because NewPipe is not designed to be a YT vanced and follows it's own styling.
Also NewPipe is - from the usability aspect - pretty similar to the YT app.

If you want to specify anything more properly, feel free to do so in #7047
