### ISSUE TITLE
A paused video starts playing when switching to fullscreen

### ISSUE THREAD

**Issue by novocaiin** [TeamNewPipe/NewPipe#8177]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Pause a video while in portrait
1. Tap on the fullscreen button

### Expected behavior

Video switches to fullscreen

### Actual behavior

Video switches to fullscreen and starts playing

### Affected Android/Custom ROM version

Android 12

### Affected device model

Google Pixel 5

**Comment by opusforlife2** [comment]
Playing the paused video when going full screen is done for convenience.

What use case do you have where you want to go into full screen but want the video to remain paused?

**Comment by novocaiin** [comment]
What's the convenience in that?
The official app doesn't do it, and I've never felt the need for something like that either.
It just seems like a very random behavior.

>What use case do you have where you want to go into full screen but want the video to remain paused?

Idk just looking at the frame more closely?
You generally open in fullscreen to see more detail.
It just starting playback immediately is pretty disorienting.

**Comment by opusforlife2** [comment]
> What's the convenience in that?

One less finger tap. If you're going into full screen on a paused video, it is extremely likely you want to resume playing it.

> Idk just looking at the frame more closely?

That is quite niche. I don't see why we should change the behaviour then.

**Comment by pc00per** [comment]
The same goes when media runs in fullscreen app & then you hit back, it just pauses the video? This one's more like an inconvenience I'd say.
I donno why newpipe's automating the flow of a video while navigating through UI.

**Comment by novocaiin** [comment]
>it is extremely likely you want to resume playing it.

But not immediately.
The app shouldn't decide for the user what the user wants to do, but especially _when_ the user wants to do it.

I think the problem of convenience is created by the UI immediately disappearing after tapping the fullscreen button which means you have to perform an extra tap to be able to resume playback.
That is again an unintuitive and fairly random behavior.

>That is quite niche.

No I think that's the most likely scenario.
If you didn't want to look more closely then you wouldn't have paused the video to begin with, you'd have just switched to fullscreen without pausing prior.

**Comment by novocaiin** [comment]
>The same goes when media runs in fullscreen app & then you hit back, it just pauses the video? This one's more like an inconvenience I'd say.

This too.
Also the UI disappearing immediately after tapping play.
The video is often paused to read some text in it or something and hitting the right frame may require a few tries.
It disappearing immediately just means I have to continuously tap to make it reappear every time.

>I donno why newpipe's automating the flow of a video while navigating through UI.

Exactly.

**Comment by opusforlife2** [comment]
> The same goes when media runs in fullscreen app & then you hit back, it just pauses the video? This one's more like an inconvenience I'd say.

@pc00per If you want the video to keep playing, why not use the Full Screen button? The Back button is for 'going back'. The Full Screen button is for 'changing how the video is being viewed'. Why should both buttons do the same thing?

> The app shouldn't decide for the user what the user wants to do, but especially when the user wants to do it.

@novocaiin If we change this so that the video stays paused like you say, that is _also_ the app deciding for the user what the user wants to do, which is "I want this video to stay paused when I go into full screen". You can't just decouple user intention from app behaviour like that. Every single behaviour of a program is a translation of user intention.

> I think the problem of convenience is created by the UI immediately disappearing after tapping the fullscreen button which means you have to perform an extra tap to be able to resume playback.

But the playback is being resumed automatically, negating the need for that extra tap. Can you clarify this part?

> If you didn't want to look more closely then you wouldn't have paused the video to begin with, you'd have just switched to fullscreen without pausing prior.

You're assuming a lot with that sentence. 'Looking at a frame more closely' is _very_ far away from the most common reason for pausing a video, which is 'doing something else' outside of the context of the video. That 'something else' could be anything and everything, from doing something else within the app, to switching to another app, to leaving your device and doing something in the physical world.

> The video is often paused to read some text in it or something and hitting the right frame may require a few tries. It disappearing immediately just means I have to continuously tap to make it reappear every time.

But the player UI doesn't disappear when you seek to a frame, though? Why do you have to play the video while trying to read some text in it? If you mean that the player doesn't seek to the exact timestamp you want, try turning off "fast inexact seek" in Video and audio settings.

**Comment by novocaiin** [comment]
>If you want the video to keep playing, why not use the Full Screen button? The Back button is for 'going back'. The Full Screen button is for 'changing how the video is being viewed'. Why should both buttons do the same thing?

Because it involves fewer actions.
The official app has a solution for that, i.e. swipe down to exit (and swipe up to enter).

>If we change this so that the video stays paused like you say, that is also the app deciding for the user what the user wants to do, which is "I want this video to stay paused when I go into full screen".

That sounds like some sort of semantic game.
No, that is the app doing nothing.
If the video was playing and the user switches to fullscreen, switch to fullscreen.
If the video was pause and the users switches to fullscreen, switch to fullscreen, not switch to fullscreen _and start playing the video_.

>But the playback is being resumed automatically, negating the need for that extra tap. Can you clarify this part?

My point is if the UI didn't just disappear immediately there would be no need to resume playback immediately.
That would be a much more elegant solution because it wouldn't involve making any unfounded assumptions about what the user wants or doesn't want to do.

Even Google who undoubtedly have a much bigger sample to gauge from don't dare making such default behavior decisions (on the website _or_ the official apps).

>>If you didn't want to look more closely then you wouldn't have paused the video to begin with, you'd have just switched to fullscreen without pausing prior.
>
>You're assuming a lot with that sentence.

How so?
Someone who wants to switch to fullscreen wouldn't _pause it, then switch to fullscreen_. They'd just _switch to fullscreen_.
Someone who has deliberately paused the video doesn't necessarily want it to resume immediately upon switching.
I really don't see how that doesn't make sense.
If anything, I'm assuming a lot less than whatever is assumed by the current behavior.

>Why do you have to play the video while trying to read some text in it? 

Not sure what you're asking.
I'm watching a video, there appears some text I want to read, so I pause, scrub back a little and tap play until the text portion appears, then pause and read.
The problem is as soon as I tap play, the UI disappears, so I have to tap _again_ for it to reappear and to be able to pause.

**Comment by SameenAhnaf** [comment]
@opusforlife2 Is this different from #6437?

**Comment by pc00per** [comment]
@novocaiin We know what we're dealing with here mate. At this point, it isn't worth arguing over "assuming what user does here & let us automate that" part. Let's leave this here, unless you want them to close this issue with reason being "locked as too heated and limited conversation to collaborators".
My suggestion is that we could fork the project & correct these issues & build ourselves, or just stick to the official app...¯\\\_(ツ)_/¯

**Comment by oneandonlyjason** [comment]
> Even Google who undoubtedly have a much bigger sample to gauge from don't dare making such default behavior decisions (on the website or the official apps).

But Google makes this Decision for you? NewPipe Just follows Googles way here. At least the Way of the Youtube Website. When i Pause a Video on the Website and then go into Fullscreen it auto starts playing. So in my Opinion its good that NewPipe also does this.

**Comment by opusforlife2** [comment]
Ah, sorry, I didn't know this was a duplicate and has been rejected already: https://github.com/TeamNewPipe/NewPipe/issues/6437#issuecomment-887344129.

**Comment by novocaiin** [comment]
>But Google makes this Decision for you? NewPipe Just follows Googles way here. At least the Way of the Youtube Website. When i Pause a Video on the Website and then go into Fullscreen it auto starts playing.

That is definitely not the default behavior and is something on your end.
Neither the website, nor any of the official apps, nor any other major streaming services behave this way.
Anyone picking up NewPipe will be at the very least confused because the UX differs so drastically from the norm.

I've looked through the linked issue.
The closing reason cited is

>niche options get in the way of 99% of users

What is the current behavior but a niche option that is bound to confuse most users who are used to their streaming app doing what they tell it to?

I would understand deviating from the norm if this were something that the vast majority of people _explicitly wanted_, but that obviously not the case.
So what was the actual reasoning for starting to assume the user intent of when to start playing or overriding the default overlay timing?

**Comment by pc00per** [comment]
> What is the current behavior but a niche option that is bound to confuse most users who are used to their streaming app doing what they tell it to?

Btw, everyone knows that Newpipe itself, is a niche frontend. We can't expect youtube's default behaviours over NewPipe, as it's developers decided "to assume whatever they think, is the default behaviour that's common everywhere", which infact, it is not.

**Comment by opusforlife2** [comment]
> What is the current behavior but a niche option that is bound to confuse most users who are used to their streaming app doing what they tell it to?

@novocaiin Why would users expect an app that is clearly not Youtube, to behave exactly like Youtube? It's a different app with a very different UI and UX. Any user who wants to start using it should come in with minimal expectations and assumptions.

> Btw, everyone knows that Newpipe itself, is a niche frontend. We can't expect youtube's default behaviours over NewPipe, as it's developers decided "to assume whatever they think, is the default behaviour that's common everywhere", which infact, it is not.

@pc00per Be careful, passive-aggressive comments aren't welcome at all.

**Comment by novocaiin** [comment]
It shouldn't behave exactly like YouTube, of course not.
But I think certain core things like media playback behavior that are present in YouTube and other "major" streaming services could benefit from being consistent across platforms and frontends.

I apologize if I came off aggressive in some of my comments.
Sadly I can be like that when I'm passionate about some subject.
I understand you folks are trying to strike a balance between functionality and good UI/UX while trying to keep maintenance manageable, and I think you've mostly achieved that currently in that NewPipe is quite nice to use.

And too many options is indeed not good, but I think a simple flip along the lines of "Hide overlay on Play" and "Pause/resume playback when toggling fullscreen" would be useful additions without cluttering things up.
