### ISSUE TITLE
Tablet UI enhancements

### ISSUE THREAD

**Issue by ranpy13** [TeamNewPipe/NewPipe#8178]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The current tablet UI is good, but it could be better. Now, I know android tablets are not as big of a concern as it comprises of only a very small percentage of users, so I understand if it won't be feasible or not in the large interest to consider these suggestions. You guys are putting in a lot of effort and I really appreciate it. Thank You. 
These are some things that I wished were there in the interface.

- The home screen, or the overview tab, the homepage I mean. The thumbnails are a little on the smaller side. They could be bigger, like a 3x3 gird view in landscape mode and 2x4 in portrait mode would be better perhaps, similar to the official YouTube or SkyTube implementations. The UI elements in general can be a bit bigger, the tabs icons, the menu, search icon etc can be enlarged a bit and the top red ribbon can be shrunken in height.
![shot_11](https://user-images.githubusercontent.com/85052085/162938479-778d1459-9f2b-4271-bb87-08e19edfd206.gif)

- The minimized video player mode in landscape mode covers only about a quatre of screen state as of now. I think that can be pushed a little further probably. The list of next videos to watch on the right pane is a little too wide, again with the thumbnails being a little smaller. Once again, the official YouTube implementation maintains a better ratio, with the video covering about 60-75% of screen with the list of videos in the right pane narrowed down with larger thumbnails and narrower titles estate. 
![shot_12](https://user-images.githubusercontent.com/85052085/162938540-922a164e-6766-498f-8e0c-23b4edf91125.gif)

- It's not entirely related but it would be nice if you could add community posts and shorts shelf which would show community posts and shorts in news like cards view, multiple on one page in order to scale properly to the larger screen and landscape orientation.

### Why do you want this feature?

Since tablets are generally harder to use one handed, and especially when held in the hands, i.e. not resting on a surface, our thumbs are basically our only input source, and in a large screen format, especially in landscape mode, there is only so far our thumbs can reach. Having so many video thumbnails in the current setup makes it impossible to tap and play the videos farther from the edge. Therefore having a homescreen with only three videos horizontally would certainly improve usability and experience. 
Same can be said about the video player interface. There is simply a lot of wasted space. When the video is not full screen, the chapters toggle and basically all the menu items which are present in the top right corner of the video, they are just plain not accessible without lifting ours hands, which is generally not a nice experience as holding tablets with one hand can be difficult sometimes, when they are in heavier keyboard cases for instance. 
In general, I think this will be a better cleaner interface.

### Additional information

![shot_12](https://user-images.githubusercontent.com/85052085/162938540-922a164e-6766-498f-8e0c-23b4edf91125.gif)
![shot_11](https://user-images.githubusercontent.com/85052085/162938479-778d1459-9f2b-4271-bb87-08e19edfd206.gif)

**Comment by opusforlife2** [comment]
> This issue contains only one feature request.

**Comment by PandoraHayami** [comment]
Sad, I really wanted all this.

**Comment by opusforlife2** [comment]
@PandoraHayami You can open several new issues that contain _one_ feature request each from this issue.
