### ISSUE TITLE
Download popup file already exists action buttons display issue

### ISSUE THREAD

**Issue by GrandKoala** [TeamNewPipe/NewPipe#8179]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Go to "Settings" -> "Video and audio" -> Behavior / Preferred 'open' action -> Select "Download"
2. Open Chrome (should work with other web browner)
3. Go to a video link (search "me at the zoo" for example)
4. Open the link with NewPipe
5. The NewPipe download box will open, click on OK to download the video.
6. Wait the download is over
7. On Chrome, select again the same video link
8. Open the link with NewPipe
9. The NewPipe download box will open, click on OK to download the video.
10. The popup "A downloaded file with this file name is already exists" will open but the action buttons "Cancel" and "Overwrite" will not be display

### Expected behavior

Action buttons "Cancel" and "Overwrite" should be display in the the popup "A downloaded file with this file name is already exists"

### Actual behavior

Action buttons "Cancel" and "Overwrite" are not display in the the popup "A downloaded file with this file name is already exists"
The button are there because we can click on them to have the good behavior but they are not displayed.

### Screenshots/Screen recordings

<img alt="Screenshot_20220412-121359" src="https://user-images.githubusercontent.com/62350288/162940955-c9efa457-e696-4b4e-92bb-09e01f5337e1.jpg" height=600 />
<img alt="Screenshot_20220412-122153__01" src="https://user-images.githubusercontent.com/62350288/162941169-4ee58d47-c26a-4e15-9a91-e274b279ac21.jpg" height=600 />
<img alt="Screenshot_20220412-122147__01" src="https://user-images.githubusercontent.com/62350288/162941433-3216aede-0e59-49c1-94dd-b5740e56c189.jpg" height=600 />
Expected : 
<img alt="Screenshot_20220412-122330" src="https://user-images.githubusercontent.com/62350288/162941760-58cc2978-bb15-460a-95d7-22566c800a5e.jpg" height=600 />

### Affected Android/Custom ROM version

Android 11 / OxygenOS 11.1.2.2

### Affected device model

OnePlus 6T

**Comment by blackwang08** [comment]
I would like to work on this issue. I successfully reproduce this bug. I found that in some cases, the button is still exist, but only because the text color become white so it seems to be invisible.

**Comment by GrandKoala** [comment]
I validate the fix of this bug
