### ISSUE TITLE
Download Queue

### ISSUE THREAD

**Issue by umunais** [TeamNewPipe/NewPipe#818]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
Please add an option to queue the download and limit simultaneous number of downloads

**Comment by umunais** [comment]
How come this issue is closed?

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/457
