### ISSUE TITLE
[FIXED] [YouTube side issue which affected official clients too] Mandatory reCAPTCHA challenge opens an HTTP 405 error page

### ISSUE THREAD

**Issue by delthas** [TeamNewPipe/NewPipe#8183]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

- Open the app.
- The reCAPTCHA challenge appears and prevents watching any video.
- Click on solve

### Expected behavior

I am redirect to some kind of reCAPTCHA page that where I can solve a reCAPTCHA and press Done.

### Actual behavior

I am redirected to a page with an HTTP error 405.

The page reads:
> Google
> 405. That's an error
> The request method GET is inappropriate for the URL /youtubei/v1/guide. That's all we know.

### Screenshots/Screen recordings
<img src="https://user-images.githubusercontent.com/40789489/163046346-6b240edf-ce85-4b5e-8b42-05693a4e0188.png" height=500 /> <img src="https://user-images.githubusercontent.com/40789489/163046379-45df528c-cf21-422a-9f61-970dd7cd5284.png" height=500 />

### Affected Android/Custom ROM version

Android 11

### Affected device model

Google Pixel 4a

### Additional information

Two other users on IRC and one friend of mine also have the issue.

For all the users, NewPipe worked fine yesterday. It is highly likely that something broke after a change from Google, since yesterday.

**Comment by ourslfs** [comment]
have the same issue

**Comment by Skywolf285** [comment]
On my device NewPipe crashes with an UI error. Already posted this on another issue report (that was made 2 minutes before this one yet was the only one showing up for me) but for completion sake I will put it here as well. Unsureif unrelated issue though.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: reasonPhrase can't be empty.
	at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
	at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
	at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedHttpError(WebViewContentsClientAdapter.java:641)
	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:218)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
</details>
<hr>

**Comment by TiA4f8R** [comment]
For everyone: please test the APK of TeamNewPipe/NewPipeExtractor#780 and let me know if you can reproduce the issue. Thanks!

**Comment by Skywolf285** [comment]
> For everyone: please test the APK of [TeamNewPipe/NewPipeExtractor#780](https://github.com/TeamNewPipe/NewPipeExtractor/pull/780) and let me know if you can reproduce the issue. Thanks!

This build solves is for me!

**Comment by onkq** [comment]
Bruh. Well I guess you were 9 minutes faster than me...

**Comment by MichaelFedora** [comment]
> For everyone: please test the APK of [TeamNewPipe/NewPipeExtractor#780](https://github.com/TeamNewPipe/NewPipeExtractor/pull/780) and let me know if you can reproduce the issue. Thanks!

reCAPTCHA requirement is gone, didn't even have to solve it. Thank you for your work!

**Comment by TiA4f8R** [comment]
If you want to know, here is what YouTube returns right now to the app:

<img src="https://user-images.githubusercontent.com/74829229/163044000-b3663d76-a668-426c-9327-cf5965f39c6b.png" width="500px" alt="error response">

This issue also affects official YouTube clients, so there is nothing we can do until it's solved by YouTube.

**Comment by TiA4f8R** [comment]
The issue has been solved by YouTube, so I am closing this issue.

**Comment by CrimsonFork** [comment]
Issue happens again.
![Screenshot_20241029_122300_Tubular](https://github.com/user-attachments/assets/dc9cd687-b8a1-40e7-aa4f-dbd7b0c0437f)

**Comment by CBSkarmory** [comment]
I am also encountering this issue again (405 on pressing the solve button). Should a new issue be created or would re-opening this issue be better?
