### ISSUE TITLE
Can't open up reCAPTCHA due to HTTP Error 405

### ISSUE THREAD

**Issue by MichaelFedora** [TeamNewPipe/NewPipe#8185]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

- Get booted from YouTube because it needs a reCAPTCHA
- Click "solve"

### Expected behavior

I'd have a captcha solve popup that worked.

### Actual behavior

I got a `405` with the following details:

> Google
> **405.** That's an error.
> **The request method GET is inappropriate for the URL /youtubei/v1/guide.** That's all we know.

### Affected Android/Custom ROM version

Lineage 18.1

### Additional information

It prompts me to solve it on both LTE and WiFi, so I'm not sure what's going on. No VPNs, nothing of that sort. Never had to solve a reCAPTCHA before either.

**Comment by delthas** [comment]
Duplicate of #8183 .

**Comment by Skywolf285** [comment]
Likely related but on my device I get an UI error when tapping Solve:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: reasonPhrase can't be empty.
	at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
	at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
	at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedHttpError(WebViewContentsClientAdapter.java:641)
	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:218)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
</details>
<hr>

**Comment by MichaelFedora** [comment]
> Duplicate of #8183 .

Beat me by 2 minutes lol. I'll close.

**Comment by mycosavant** [comment]
same bug on OneUI 3.1 android 11

**Comment by MichaelFedora** [comment]
> Likely related but on my device I get an UI error when tapping Solve:
> ## Exception
> 
>     * **User Action:** ui error
> 
>     * **Request:** ACRA report
> 
>     * **Content Country:** US
> 
>     * **Content Language:** en-US
> 
>     * **App Language:** en_US
> 
>     * **Service:** none
> 
>     * **Version:** 0.22.1
> 
>     * **OS:** Linux Android 7.1.2 - 25
> 
> 
> Crash log

Hey @Skywolf285, you should probably open a new issue for that. I don't crash when clicking solve so that's a different bug I would think.
