### ISSUE TITLE
reCAPTCHA Solving Gives Me 405 Error

### ISSUE THREAD

**Issue by TheBrokenRail** [TeamNewPipe/NewPipe#8186]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Open App
2. It will ask you to solve a reCAPTCHA.
3. Click "Solve"
4. Get Error

### Expected behavior

It shows me a reCAPTCHA.

### Actual behavior

I get this 405 error: "The request method GET is inappropriate for the URL /youtubei/v1/guide.".

### Screenshots/Screen recordings

<img alt="Screenshot_20220412-152248_NewPipe" src="https://user-images.githubusercontent.com/17478432/163038763-6574a8c5-5d48-412c-aeb8-aefe9ba0e7e4.jpg" height=600 />

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S21

**Comment by delthas** [comment]
Duplicate of #8183 .

**Comment by TheBrokenRail** [comment]
How did I miss that? Sorry!
