### ISSUE TITLE
reCAPTCHA requested, shows "GET is inappropriate for the URL"

### ISSUE THREAD

**Issue by onkq** [TeamNewPipe/NewPipe#8189]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Open NewPipe.
2. Trend page has a big Solve button, press it.
3. Profit

### Screenshots/Screen recordings

<img alt="Screenshot_20220412-212750" src="https://user-images.githubusercontent.com/84337276/163039608-e9b9aa74-5a43-4d35-b530-1e277876f8f2.png" height=600 />

### Logs

No logs. 

### Affected Android/Custom ROM version

GrapheneOS stable

### Affected device model

Pixel 6

**Comment by kmodexc** [comment]
Duplicate of #8183.

**Comment by onkq** [comment]
Yes thank you for noticing while I wrote this my man delthas was 9 min faser
