### ISSUE TITLE
Can't import newpipe subscriptions in Android TV

### ISSUE THREAD

**Issue by theobs3rver** [TeamNewPipe/NewPipe#8195]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Go to Subscriptions.
2. Click on the Previous export option.

### Expected behavior

File manager should open up to select the file to be imported.

### Actual behavior

A notification is seen: "This feature is not supported on this device"

### Affected Android/Custom ROM version

Android 9

### Affected device model

Sanyo XT-43A082U

### Additional information

The affected device is an Android TV

**Comment by peat80** [comment]
Sounds device specific. Works just fine on ShieldTV. Probably your tvs firmware has no filepicker included.

You could try if it helps to disable saf in newpipes download options.

**Comment by moneytoo** [comment]
Basically no Android TV device (except for only Nvidia Shield devices) have the SAF file chooser. The official Android TV emulator also doesn't have SAF file chooser. https://issuetracker.google.com/issues/202985150

**Comment by peat80** [comment]
Did not know this. 🤔 So maybe newpipe should force its internal file manager for android tv devices? 🤔 Worked well on shield tv too last time i used it. 🤔
This is not possible anymore because SAF is forced on android 9 and above.

**Comment by peat80** [comment]
I just got a new bravia tv and there you can set your installed file manager to browse for the export files which works also fine. 🤔 So there is no filepicker installed on this rom but you can install one.

**Comment by opusforlife2** [comment]
> Basically no Android TV device (except for only Nvidia Shield devices) have the SAF file chooser. 

@Stypox so should NNFP be enforced for TVs?

**Comment by theobs3rver** [comment]
> You could try if it helps to disable saf in newpipes download options.

It worked. Thanks.

**Comment by Stypox** [comment]
> so should NNFP be enforced for TVs?

Uhm, I don't know. From API 29 NNFP does not even work anymore. On Fire TVs NNFP is already disabled by default, see [the setting migration](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java#L79). It would not be too difficult to create another migration that turns off SAF

**Comment by opusforlife2** [comment]
@moneytoo How do Android 10+ TVs handle file management if not through SAF?

**Comment by moneytoo** [comment]
@opusforlife2 Android TV apps are supposed to used MediaStore API (but it's limited to mostly media files of known mime types to the system). File managers can use the legacy file API with the MANAGE_EXTERNAL_STORAGE permission to access all files on all volumes. The last option is to use the legacy file API but it's limited to media files on the internal storage only. Accessing some binary (application/octet-stream) files is limited to the application scope only (the Android/data/... folder).

**Comment by opusforlife2** [comment]
So... if I'm understanding this right... Google just broke file browsing in newer versions of Android TV?

**Comment by moneytoo** [comment]
@opusforlife2 Exactly. Because of this, apps like game emulators need MANAGE_EXTERNAL_STORAGE permission, just to read .nes files for example. The irony is that large number of media players also request this permission, just to read formats like wmv or less used subtitle formats (which kind of defeats the purpose of this all).
As NewPipe is not on the Play Store, it could use this permission for the import/export.

**Comment by opusforlife2** [comment]
@Stypox ^ What say?

**Comment by Stypox** [comment]
I think this would require us to add yet another way to access storage which might not be simple. If some developer wants to do that, he can go ahead. Check out #5415 for some information.

**Comment by opusforlife2** [comment]
@moneytoo Could I implore you to open a new issue explaining what we need? (I can then slap the Android TV label on it for future contributors to stumble upon it.)
