### ISSUE TITLE
Found an interesting but minor bug.

### ISSUE THREAD

**Issue by xepheratu** [TeamNewPipe/NewPipe#820]
I have found, that when a video is finished, it has the little "replay" button in the center, and while it does that it also has a smaller image of the videos thumbnail. Well if you lock the screen while the video has the "Replay" button on it, and then unlock it and hit the replay button, the entire video will have the small version of the thumbnail in the middle of the video. Nothing super huge but I figured you would like to know. This happened one my samsung galaxy note 3, rooted, running android 4.4.2 with newpipe version 0.10.2, not sure if it happens to others but I figured you'd like to know.

**Comment by theScrabi** [comment]
Confirmed .... Uu make it an easter egg!!!

**Comment by Stypox** [comment]
This does not seem to be there anymore, at least not in the normal ExoPlayer
