### ISSUE TITLE
Video length not visible in a thumbnail (RSS list) until the video is played.

### ISSUE THREAD

**Issue by werjany** [TeamNewPipe/NewPipe#8201]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Open the app
2. Click on RSS list

### Expected behavior

All video lengths should appear on the list of thumbnails.

### Actual behavior

Information about the length of a video appears only after the video has been played (even for 1 second) and the whole list has been refreshed after playing. Working only for that particular video, not the whole list.

### Screenshots/Screen recordings

<img alt="Screenshot_2022-04-14-23-38-01-887_org schabi newpipe" src="https://user-images.githubusercontent.com/103181582/163482002-1451fb70-e629-4e25-986c-fbdb231eb782.jpg" height=600 />

### Affected Android/Custom ROM version

Android 12 / MIUI 13.0.1

### Affected device model

Xiaomi Mi Note 10 Lite

**Comment by yant0** [comment]
Disable fast mode.....?

**Comment by yant0** [comment]
Dude, press the `?` button and read the the warning again. This is the trade off for faster fetching, not a bug.

**Comment by yant0** [comment]
disable fast mode....? Pretty sure its not a bug. If you do have fast mode enabled (check on `?` top right) you can disable it, it will be slower since it fetches more information.

**Comment by Stypox** [comment]
Yes, this is intended and explained in the `?` menu

**Comment by Atemu** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/4934 for a possible solution.
