### ISSUE TITLE
0.22.2 not installing on Android 11

### ISSUE THREAD

**Issue by darthspiffiest** [TeamNewPipe/NewPipe#8226]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

Attempted to install APK from Files. Was notified that "Something went wrong. The app was not installed." Deleted APK and tried again, same issue 

### Expected behavior

Update from 0.22.1

### Actual behavior

App is not installed, error message produced. 

### Screenshots/Screen recordings

![Screenshot_20220416-082551-716~2](https://user-images.githubusercontent.com/103830926/163675018-86a1fc67-3a96-45c7-a63e-3c81642d0aec.png)

### Affected Android/Custom ROM version

Android 11 

### Affected device model

Motorola moto g power (2021)

**Comment by TiA4f8R** [comment]
You are probably using the F-Droid version of the app. See the [Installation and updates](https://github.com/TeamNewPipe/NewPipe#installation-and-updates) part of our README to solve this issue.
