### ISSUE TITLE
Certain video resolutions occasionally not playing

### ISSUE THREAD

**Issue by rhynec** [TeamNewPipe/NewPipe#8241]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Open [this](https://youtu.be/aDtnSrGq9dM) specific video on NewPipe.
2. Select 720p resolution.

### Expected behavior

Video loads after buffering.

### Actual behavior

Video seems to buffer indefinitely; changing resolutions or switching to background playback allows the video to play normally.

### Affected Android/Custom ROM version

Android 11

### Affected device model

Moto G Fast

### Additional information

The provided video link may be time-sensitive for tests. I have experienced this issue with other videos in the past, only for the problem to go away after a few days/hours.

**Comment by litetex** [comment]
Works as expected now. So I guess YT had some problems?

**Comment by rhynec** [comment]
> Works as expected now. So I guess YT had some problems?
> 
> I think we can close the issue or?

Yeah, the issue is gone for me as well. Though, I did test accessing the video through YouTube directly while the problem was occurring, and the 720p resolution loaded normally. This typically occurs to me with a handful of newly published videos, specially popular ones. Not sure if someone else has experienced this before...

Anyway, feel free to close the issue (since it may just be a problem with my device), and then someone else can use it as reference if they run into the same problem.
