### ISSUE TITLE
github login on bountysource is broken

### ISSUE THREAD

**Issue by amon84** [TeamNewPipe/NewPipe#825]
I wanted to create an account at bountysource to vote for some issues. I wanted to use my pre-existing github account and instead got redirected to the following website:
https://api.bountysource.com/auth/github/callback?error=application_suspended&error_description=Your+application+has+been+suspended.+Please+contact+support%40github.com.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23application-suspended&state=eyJyZWRpcmVjdF91cmwiOiJodHRwczovL3d3dy5ib3VudHlzb3VyY2UuY29tL3NpZ25pbi9jYWxsYmFjaz9wcm92aWRlcj1naXRodWJcdTAwMjZmb2xsb3dfdHJhY2tlcl9pZHM9IiwiYWNjZXNzX3Rva2VuIjpudWxsLCJpcCI6Ijc3LjE4MC4xNzIuMjUxIiwibXBfaWQiOiJudWxsIn0_

single content is:
 {"error":"Internal server error."}

seems to be an issue on your end.

instead i created a login using my twitter, but maybe this needs fixing after all. it's up to you.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by wb9688** [comment]
No, it's Bountysource's issue and they know it already.

**Comment by amon84** [comment]
okay. i'm gonna close the issue then ^^;
