### ISSUE TITLE
[YouTube] Auto-generated subtitles rendered too fast and covering whole screen

### ISSUE THREAD

**Issue by MDP43140** [TeamNewPipe/NewPipe#8254]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Open NewPipe.
2. Open any video that has *non-english automatic* translation (https://youtu.be/TuJkjPGtibY).
3. Turn-on subtitle that is non English and automatic (which in my case was 'Indonesian (auto)' subtitle, this didnt affect non-automatic subtitles).

### Expected behavior

the subtitle should working fine and not render ~too fast or produces~ more than 2 lines of text.

### Actual behavior

The subtitle runs SO FAST that it renders text more than 2 lines and EVEN COVERING the WHOLE screen, and it makes this RIDICILOUS glitch (see video).

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/68391650/163752416-0587e527-7bcd-46dc-9acd-4223d797971b.mp4

### Affected Android/Custom ROM version

Android 10 / OneUI 2.5 (Custom ROM)

### Affected device model

Samsung Galaxy J5 Prime (SM-G570Y)
### Additional information
Edit: i realized that YouTube made some *stupid* changes in auto subtitle recognition that caused bunch of garbage added to the text making it rendered too fast (try to watch the video in youtube web).

**Comment by opusforlife2** [comment]
Close, then?
