### ISSUE TITLE
DUPLICATE: Continue playing videos from the playlist when one video from it is selected

### ISSUE THREAD

**Issue by spagootie** [TeamNewPipe/NewPipe#8261]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

It would be nice if upon playing one video from inside a playlist, after the video finishes, NewPipe starts playing the next video in the playlist, and so on.

Currently this doesn't happen, and instead NewPipe begins playing a recommended video after the selected video finishes playing.

### Why do you want this feature?

It's the behavior of the YouTube website and official mobile app, as well as music streaming services like Spotify. It's also very convenient if I'm listening to a playlist of videos and want to start in the middle of it, especially if I'm driving and can't use my phone. To do this currently, I have to tell NewPipe to play the entire playlist, and then skip to the video that I want to watch. This gets less and less practical with large playlists, and isn't an ideal solution to begin with.

### Additional information

I'm running NewPipe v.0.22.2 on Android 8.1.0.

EDIT: Sorry, I just realized this issue is a duplicate after searching more thoroughly through other issues. Please close this issue.

**Comment by TiA4f8R** [comment]
> Please close this issue.

Don't hesitate to close issues yourself 😉

**Comment by spagootie** [comment]
It seems this is a frequently requested feature here. I was able to find other feature requests concerning this:

#4805
#6999
#2510
#5741 

According to #2510, this feature used to be in NewPipe but was accidentally broken. I saw one person argue that somebody might want only one video to play, but to do that they could just turn off autoplay.

**Comment by BartFarley** [comment]
Here we are again. I get to walk on eggshells, as to not hurt anybody's feelings. I'll try not to sound threatening, especially when stating facts.
  Again, this feature was implemented a long time ago. It used to work for playlists as well as for channels. Handy.
  Someone intentionally, NOT accidently (as you stated) deleted all the code for this functionality, then refused to restore it. Even as a good number of people voiced a desire to have it work again. I'm not a developer, but a simple copy/paste exercise should have brought that code back.
What did we get instead? We got red herrings thrown in our faces.
Yes, I'm still a bit peeved.

**Comment by neekt** [comment]
For anyone else who lands here, this is a duplicate of #6999 specifically. 

The other issues mentioned in this thread relate to the "Play all" button, enqueueing functionality, and "play from here" menu option which, while related, are different feature requests.
