### ISSUE TITLE
About allowing X-plore - like file managers to be allowed to be chosen on subscription import

### ISSUE THREAD

**Issue by mart-hill** [TeamNewPipe/NewPipe#8268]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I noticed that in Android TV on Philips PUS8546 series (Android 10 and current 11) or NewPipe 0.22.x doesn't allow listing X-plore or FX Explorer app as file manager during import.
https://f-droid.org/packages/me.zhanghai.android.files app "registers" as file manager correctly, but crashes itself at permission setting.
Other file managers register themselves to be seen by NewPipe (like this package: dev.dworks.apps.anexplorer.pro), but show Downloads or Documents folders totally empty.

All this causes NewPipe unable to import anything from the file system.

Is it possible for NewPipe to be able to use X-plore - like application as a file manager app for importing?

The similar issue is with web browsing (Youtube subscriptions download link), but I circumvented it by shoving Samsung Browser into this TV.

### Why do you want this feature?

For importing subscriptions from YT, or my NewPipe phone installation.

**Comment by opusforlife2** [comment]
> https://f-droid.org/packages/me.zhanghai.android.files app "registers" as file manager correctly, but crashes itself at permission setting.

Maybe you could open a bug report there about this? Seems like the most straightforward solution, since we have no control over which file managers have what features.

**Comment by mart-hill** [comment]
I fear that it might be Google being a d*ks - I hope there's a workaround for that, cause if not - all Philips Android TV users are screwed - they cannot import (invoke a file manager to select a file), nor they can click on a web link (to open a selected - factory installed! - browser) on Android version 10 and 11 for 2021 xxPUS85xx (The One) product line.

**Comment by ChiefMikeK** [comment]
Possibly some additional NewPipe-Setting(s) to recover the most recent saved settings/playlists from the _default_ export URI?  
feature~request? v
this would also make re-installation simpler.  
@mart-hill
- do you think this would work?
- since you paid for `dev.dworks.apps.anexplorer.pro` then email them for support it may help others with simular issues!

**Comment by opusforlife2** [comment]
Newpipe just uses standard Storage Access Framework intents. It's up to the OS to capture and handle the intent in the best way possible.

> Maybe you could open a bug report there about this?

Did you try this?

**Comment by moneytoo** [comment]
(Based on my tests) on Android 11 and newer, only system apps are allowed to register the SAF intents. I know that Material Files app use this and it no longer worked for me on Android 11. Not sure if this applies to Android TV as well though...

**Comment by opusforlife2** [comment]
@Stypox ^

**Comment by mart-hill** [comment]
> Did you try this?

Not yet - I'll go to Philips software update area, and bring this up.

**Comment by mart-hill** [comment]
> (Based on my tests) on Android 11 and newer, only system apps are allowed to register the SAF intents. I know that Material Files app use this and it no longer worked for me on Android 11. Not sure if this applies to Android TV as well though...

It seems to apply - Material Files crashes the moment I'll "Allow" it the SAF intent.

**Comment by moneytoo** [comment]
@mart-hill Try granting the requested permission to Material Files by running this: `adb shell appops set --uid me.zhanghai.android.files MANAGE_EXTERNAL_STORAGE allow` (based on a test in emulator, it should help)

**Comment by opusforlife2** [comment]
> Not yet - I'll go to Philips software update area, and bring this up.

I meant the Material Files repo.

**Comment by mart-hill** [comment]
> > Not yet - I'll go to Philips software update area, and bring this up.
> 
> I meant the Material Files repo.

Oh. I didn't think of that - I thought it's no longer being developed!
By the way, I wanted to try workaround with Google Drive, but NewPipe doesn't allow to call that either - is it possible to use it for import/export in the future?

**Comment by mart-hill** [comment]
> @mart-hill Try granting the requested permission to Material Files by running this: `adb shell appops set --uid me.zhanghai.android.files MANAGE_EXTERNAL_STORAGE allow` (based on a test in emulator, it should help)

Thanks for the suggestion! I wonder though, can I connect the TV to the PC to issue ADB commands through USB?

**Comment by mart-hill** [comment]
It worked with the Material Files app! I had to go to internal memory management (yes) to display apps, to be able to apply file access permission (always) to the manager, and then NewPipe imported the subscriptions! It's a nice workaround!

**Comment by mart-hill** [comment]
> On fire TVs SAF is already not enabled by default. But we can't just disable SAF on Android TVs, since on those with Android 10+ we are forced to use only SAF anyway

I didn't think of disabling SAF, I only thought that NewPipe could parse all available (for detected Android) file access possibilities, but that is already probably implemented. :)

**Comment by Stypox** [comment]
@mart-hill see #5415 for an explanation of what Storage Access Framework and NoNonsense-FilePicker are ;-)

**Comment by mart-hill** [comment]
> @mart-hill see #5415 for an explanation of what Storage Access Framework and NoNonsense-FilePicker are ;-)

Thank you! Of course, I'm not even thinking of downloading anything to the TV's storage (1.5GB free space, so I didn't test the saving yet), but an USB storage... Might be interesting. :)

**Comment by Stypox** [comment]
@opusforlife2 wait, why are we discussing the same thing on two issues? ;-)

**Comment by opusforlife2** [comment]
I don't know. I last commented 4 days ago. :P

Anyway, that's just how the conversation played out. The solution moneytoo gave in the closed issue needs its own new issue. Then this can be closed as well.

**Comment by mart-hill** [comment]
I'll show how ProfiMail (it's from the X-Plore developer) handles the file import on the same AndroidTV:
![profimail import](https://user-images.githubusercontent.com/55754730/166801309-0bde8e72-9457-493b-b757-c1e9c3b229be.jpg)

So it seems, it's possible to parse more sources! :) 
Exporting mail profiles and settings also worked flawlessly after simple "question-answer" allowing ProfiMail filesystem access. I forgot to mention, but **NewPipe won't even start exporting a subscriptions file, cause displays the same error information "No application can handle this action"**.
