### ISSUE TITLE
UseAsFrontPage causes crash when orientation was changed

### ISSUE THREAD

**Issue by avently** [TeamNewPipe/NewPipe#827]
There is an option useAsFrontPage. It works as expected until a phone changed its orientation. 
Steps to reproduce:
Open NewPipe with kiosk as a home page
Turn your phone in landscape mode with Android's autorotation enabled
Tap on any item.
I will see a crash.

This happens because baseListFragment loses its value for useAsFrontPage when orientation changed. And since then initListeners() can't do it job right.

**Comment by theScrabi** [comment]
confirmed.

**Comment by lawonga** [comment]
I opened up a PR for this. :)

**Comment by avently** [comment]
@lawonga how did you understand that the problem is a missing @State annotation? And what it means (@State)? Quick googling does nothing

**Comment by wb9688** [comment]
@avently: Well, on rotation the view is recreated (I think) and thus it
needs to save and restore the state, which is what we're using Icepick, the
library that provides that annotation, for.

**Comment by avently** [comment]
@wb9688 cool library, thanks.
