### ISSUE TITLE
Auto-generated music not showing on channels

### ISSUE THREAD

**Issue by FuriousGamer1356** [TeamNewPipe/NewPipe#8271]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. look for music
2. find music (music plays normally)
3. check description
4. find "Auto-generated by youtube"
5. go to the channel that made the song
6. channel shows no "Auto-generated" music

### Expected behavior

What I expected was the "Auto-generated" music to show on the channel page.

### Actual behavior

The channel shows normal videos, but not the "Auto-generated" music.

### Affected Android/Custom ROM version

Android 11

### Affected device model

Samsung galaxy a51

### Additional information

The version of newpipe is a fork of newpipe with sponsorblock but the bug persists throughout normal newpipe.

**Comment by pc00per** [comment]
If you referring to "Topic" Channels, then yes. Those auto-generated 1x1 music tracks won't exist in the Channel. Because they're explicitly kept unlisted by YouTube to keep them separate to YouTube Music.

**Comment by opusforlife2** [comment]
Newpipe's support for Youtube Music is quite barebones. We would need to flesh it out for things like supporting music artists and albums, to be able to show them properly in the UI.

**Comment by pc00per** [comment]
To make it possible, NewPipe needs to update it's Extracter mechanism to adapt YouTube Music API.

**Comment by opusforlife2** [comment]
We could probably learn from https://beatbump.ml how to do it.
