### ISSUE TITLE
Add remote control queue

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#828]
I'd like to be able to remotely control the queue.

**Comment by karyogamy** [comment]
Related to #781 perhaps? Should be labeled as enhancement.

I took a look into this, but didn't go too far. Will come back to this later though. But if anyone else is interested, implementing [this](https://medium.com/google-developers/understanding-mediasession-part-2-4-ad291fd32d60) seems promising.

**Comment by Stypox** [comment]
What karyogamy is suggesting was implemented in #1433
