### ISSUE TITLE
Long Lag to Start 1080p Videos

### ISSUE THREAD

**Issue by SenorFusion** [TeamNewPipe/NewPipe#8291]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2 (and at least 6-8 months prior)

### Steps to reproduce the bug

1. Play any video at 1080p or 1080p60

### Expected behavior

Video begins playing immediately

### Actual behavior

Nothing happens for 10-12 seconds, then video plays normally.

App shows black background with red circle arrow icon in video player, with no other movement or anything for 10+ seconds.

### Affected Android/Custom ROM version

GrapheneOS Lates

### Affected device model

Pixel 6

### Additional information

This happens on every single video if set on 1080p.

This happens if it is set to play in full screen or not

720p videos start immediately.

1080p videos played on youtube.com in browser on the same device start immediately.

My connection is 300 mpbs up / 300 mpbs down and I am on a Pixel 6, so the connection and hardware should have no trouble playing the video normally.

This has been happening for many months and previous versions of NewPipe I just keep forgetting to create an issue.

**Comment by SenorFusion** [comment]
EDIT: After I posted this I found #7919 in the 0.23.0 Changelog, which also references #7630 and #6927

I can't tell if this is the same issue I am experiencing or not?

**Comment by litetex** [comment]
@SenorFusion 
Yes, it's a duplicate ;)
