### ISSUE TITLE
I can't scroll or use any other app when popout mode is on for Newpipe

### ISSUE THREAD

**Issue by PopRocks234** [TeamNewPipe/NewPipe#8297]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Newpipes 22.2

### Steps to reproduce the bug

I encounter the bug by going in the app and just pressing on popout mode and I try to go on another app expecting that i can still see the video and going on a different app doing my thing. But I can't swipe nor do anything in other app.

### Actual behavior

I went on the app and press popout. I can't move any other app.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/79923706/165398681-8142d337-37ab-426b-8c3a-6acd4658be4c.mp4

The recording closed before I got to show you on how I can't access on any other app. 

### Affected Android/Custom ROM version

Android 12

### Affected device model

Galaxy S20 FE

**Comment by anas-almzoghy** [comment]
Already known bug with android 12 due to api changes.  #6770

It's also already fixed in version 0.23.0 but still in beta, download it from here and try it for feedback #8230  or apply the adb fix from #6770 as a temporary workaround until stable 0.23.0 is out.

Good luck :D
