### ISSUE TITLE
download profile pictures

### ISSUE THREAD

**Issue by HyperHatter** [TeamNewPipe/NewPipe#8300]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

add a download button when you click on a youtubers profile pic in newpipe

### Why do you want this feature?

It's a cool feature that i would like to be added to newpipe

**Comment by litetex** [comment]
I don't think we should add that:
1. I don't think a lot of people would use that feature
2. It's already possible to download such a picture with a browser (open the Channel page, long click the channel thumbnail, select save graphic)

**Comment by litetex** [comment]
Closing due to userfeedback
