### ISSUE TITLE
YouTube video description not displayed

### ISSUE THREAD

**Issue by Melud** [TeamNewPipe/NewPipe#8306]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

Play any video and try to display the associated description by clicking the arrow

### Expected behavior

Should display the description

### Actual behavior

Does not display the description : only show "share" and "open in browser" buttons

### Screenshots/Screen recordings

![Screenshot_20220429-112532_NewPipe](https://user-images.githubusercontent.com/34193773/165919153-382947ae-6f02-4659-82cc-525b0949571c.jpg)
Whereas the real description for this video is this
<img alt="Screenshot_20220429-112943_Firefox" src="https://user-images.githubusercontent.com/34193773/165919474-16328107-d9d9-4590-ad87-ae8f41483069.jpg" height=600 />

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung galaxy 20 FE

**Comment by opusforlife2** [comment]
The description is accessed through the bottom tabs, not the title arrow.
