### ISSUE TITLE
Cannot scroll (probably issue of player; Smartisan OS)

### ISSUE THREAD

**Issue by CBpbxEcmecmBeH** [TeamNewPipe/NewPipe#831]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
It seems that this better quality of the audio is causing problems with my player. I'm running Smartisan OS. It's the default player.

**Comment by theScrabi** [comment]
Please describe how to reproduce that error.

**Comment by CBpbxEcmecmBeH** [comment]
It's kind of difficult, coz you may need to install Smartisan OS. Then download  a.M4a file and try to play it through the default music player. MP3s work, ogg work.. 
I'm on mobile, can you tell me how to attach images..

**Comment by CBpbxEcmecmBeH** [comment]
You can tell it's my first time..

**Comment by theScrabi** [comment]
When you open an m4a, file with another app it is not NewPipe that fails. It may have todo with your setup.

**Comment by CBpbxEcmecmBeH** [comment]
X-plore does the same with build 0.11.0. It just shows no possibility to move forward.
