### ISSUE TITLE
v0.22.1 delivery-methods-v2 still plays videos quicker than v0.23.0

### ISSUE THREAD

**Issue by EveryGoodUsernameIsTaken** [TeamNewPipe/NewPipe#8311]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.23.0

### Steps to reproduce the bug

Regardless of which playback load interval size you choose, v0.22.1 delivery-methods-v2 will still play videos quicker (less buffering) than v.0.23.0.

### Expected behavior

I know I'm nitpicking, but could you please apply whatever makes v0.22.1 delivery-methods-v2 so quick to all future releases?

**Comment by opusforlife2** [comment]
This is an ETA in disguise, which I'm sure you know is very bad etiquette in FOSS communities.

**Comment by EveryGoodUsernameIsTaken** [comment]
I'm new to Github and don't know how things work around here. I'm not a dev, nor am I particularly tech savvy. I don't know what ETA or FOSS mean. I'd just like Newpipe to buffer less.

v0.22.1 delivery-methods-v2 is reasonably quick, so I'd appreciate if you could incorporate whatever makes it quick into the stable release.

I'm sorry if you find this request offensive.

**Comment by opusforlife2** [comment]
Oh. Sorry. I'll explain the terms, then.

ETA: Expected Time of Arrival. This means asking anything along the lines of "When will this be added/fixed?" Since this and similar projects are fueled by volunteered time of contributors, it's the equivalent of saying "You're wasting time on other stuff but not the stuff I care about".

FOSS: Free and Open Source Software.
