### ISSUE TITLE
Crash with default progressive load info

### ISSUE THREAD

**Issue by Douile** [TeamNewPipe/NewPipe#8312]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0 (debug build of b59a601b5242551fdb21b551dd284ee47396580c )

### Steps to reproduce the bug

1. Play video

### Expected behavior

Video plays

### Actual behavior

App crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.NumberFormatException: For input string: "default"
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4198)
	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.player.helper.PlayerHelper.getProgressiveLoadIntervalBytes(PlayerHelper.java:434)
	at org.schabi.newpipe.player.helper.PlayerDataSource.<init>(PlayerDataSource.java:42)
	at org.schabi.newpipe.player.Player.<init>(Player.java:433)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:106)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
	... 8 more

```
</details>
<hr>

### Affected Android/Custom ROM version

LineageOS 18.1

### Additional information

- Going to settings -> video and audio -> playback load interval size, and setting to any value fixes the issue
  - This could just be caused by my weird update path through debug builds (I will validate update from 0.22 to 0.23 soon)

**Comment by opusforlife2** [comment]
> I will validate update from 0.22 to 0.23 soon

Try to finish all such bug confirmation steps before you open the issue (though I understand that some things only occur to us in the process of creating the bug report).

**Comment by Stypox** [comment]
Did you import a db from a temporary/RC apk? Because the crash you reported would be impossible in the current version, since the current version does not contain the value "default" in the progressive load interval array, but contains "exoplayer_default" instead. I can actually set "Exoplayer default" without issues on my phone.

**Comment by Douile** [comment]
Yeah sorry, not repeatable

**Comment by syphyr** [comment]
> Did you import a db from a temporary/RC apk? Because the crash you reported would be impossible in the current version, since the current version does not contain the value "default" in the progressive load interval array, but contains "exoplayer_default" instead. I can actually set "Exoplayer default" without issues on my phone.

If I remove app data for newpipe, then this crash is reproducible.  If I grep for "exoplayer_default" I expect more than one result, but I only see one.

**Comment by Stypox** [comment]
And if you grep for "default" you should see none

**Comment by syphyr** [comment]
-        <item>default</item>
+        <item>@string/progressive_load_interval_exoplayer_default_value</item>

Shouldn't the string for progressive_load_interval_exoplayer_default_value be equal to what is replacing?  It is changed to exoplayer_default and nowhere else.

+    <string name="progressive_load_interval_exoplayer_default_value">exoplayer_default</string>

**Comment by syphyr** [comment]
Perhaps this is only an issue with legacy devices using java 8

**Comment by syphyr** [comment]
I figured out the problem.  This bug occurs only when upgrading from a previous version of NewPipe.  If I uninstall the previous version of NewPipe and then install the latest version, there is no issue.  So, basically, if "default" is used instead of "exoplayer_default", the upgrade path does not break and the app data does not have to be cleared.
