### ISSUE TITLE
Improve Channel Groups: Channel group selection directly from What's New tab

### ISSUE THREAD

**Issue by Mrnofish** [TeamNewPipe/NewPipe#8319]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Provide ways to switch channel groups without having to visit the Subscriptions tab.

### Why do you want this feature?

Channel groups allow browsing a subset of channels, which is useful when one has many subscriptions and/or channels that post new videos very frequently.

The main What's New tab currently can only aggregate videos from all subscriptions at once.

In the conditions described above, the main What's New tab become essentially useless, as it becomes highly cluttered and is unwieldy to browse.

Switching to a different channel group requires moving on to the Subscriptions tab, which only displays subscriptions and channel groups, and not any content.

This transition is very slow and jarring.

### Additional information

The switch could be handled in a few ways that can coexist:

- Swipe left/right on the top bar as switch to preceding / following channel group
- Long press on the main What's New Feed brings up a list of channel groups.
- Tap on the Channel Group name when in a specific Channel Group's "What's New" view would also bring up the list of channel groups.

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3388. You might include your suggestions on how the feature should be implemented in that issue.

**Comment by Mrnofish** [comment]
This was never about having a list of feeds inside the subscriptions tab.

I asked for a way to switch the What's New view to a channel group without having to switch tabs.

>  You might include your suggestions on how the feature should be implemented in that issue.

Such graciousness, I'm in awe of your majesty.

**Comment by opusforlife2** [comment]
> Such graciousness, I'm in awe of your majesty.

@Mrnofish Beware. Passive-aggressive comments are highly unwelcome.

**Comment by Mrnofish** [comment]
> Beware

Threatening to remove my privileges is not only terrible manners and ham-fisted moderation (you're intervening on the wrong end of the discussion), but also completely pointless.

Do you seriously think I pine for the chance to spend my time detailing long-standing issues that exist with the application, only for that, albeit small, effort to be summarily discarded by someone whose only contribution to this project appears to talk endlessly in circles to make issues go away by attrition and disregard ?

Feel free to keep whatever contributors you value, the dysfunctional practices, and your threats, as well, as I don't care for any of that and whatever little free time I have, you were very successful in convincing me, it is better spent on other projects with a healthier climate and better practices.

**Comment by tsiflimagas** [comment]
The only impolite individual is see here is you. You're whinning for having your issue **totally politely** indicated as duplicate, as if that's an insult (in what specific way?!). If you don't understand how things work, then try to understand, don't attack others. There's over 1000 open issues, and there are new reports everyday. That volume of backlog is unmanageable, thus being scrutinous about duplicate issues is required, and people taking care of that should be credited for their efforts, instead of attacked. Even if he got it wrong, you could have explained in the same kind way he wrote.

**Comment by opusforlife2** [comment]
@Mrnofish I didn't threaten you with anything. You made that up in your mind. All I did was make you aware about our policy regarding discussion between community members. Anyway, if this is your mindset and way of interacting with open source communities, then you are most welcome to boycott this project. For some reason, I think we can manage without you.

@SameenAhnaf I would like to add my voice to tsiflimagas's and say that your work is highly appreciated. Don't let any naysayers bother you.
