### ISSUE TITLE
FR: Include metadata for fdroid

### ISSUE THREAD

**Issue by mueller-ma** [TeamNewPipe/NewPipe#832]
When providing metadata via a fastlane directory, fdroid automaticly shows them in the store. You dont need to install fastlane, just create the folder

Example: https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android/en-US
Info: https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots

**Comment by TobiGr** [comment]
See #675. I'm working on it.
