### ISSUE TITLE
Improve Channel Groups: exclude channels in a Channel Group from Main What's New tab

### ISSUE THREAD

**Issue by Mrnofish** [TeamNewPipe/NewPipe#8320]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Include an option to exclude a specific Channel or a Channel Group from the main What's New tab, so that the relevant content is only displayed when viewing that Channel or Channel Group.

### Why do you want this feature?

A high number of subscription and/or subscribing to channels that post many videos very frequently can render the main What's New tab almost useless.

Since the tab becomes highly cluttered, Channel Groups become the most convenient way to interact with the app.

Excluding individual channels or channel groups from the main view, would clear up the default What's New feed.

This provides a more focused default landing spot for the app, as the main What's New view would only display the content that is most relevant to the user.

While at the same time still providing a way to view those channels quickly, i.e. without having to unsubscribe and search for those channels manually.

### Additional information

Channel groups already have a set up dialog, to which an option "Exclude from Main Feed" (or similar) could be easily added.

Individual channels don't, so the option could be added as a checkbox perhaps under the Subscribe button in the Channel view.

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4334.

>Individual channels don't, so the option could be added as a checkbox perhaps under the Subscribe button in the Channel view.

That's irrelevant from this issue. Anyway, already asked in https://github.com/TeamNewPipe/NewPipe/issues/5836

**Comment by Mrnofish** [comment]
> That's irrelevant from this issue

Jesus, no need to be rude...

> Anyway, already asked in https://github.com/TeamNewPipe/NewPipe/issues/5836

...especially when it's not even the case.

Might want to double check your stuff before you go harsh mistress on well-meaning folks --or maybe just try and be nice every now and then, since we're all in the same effing boat, anyway.
