### ISSUE TITLE
Newpipe's Comments 

### ISSUE THREAD

**Issue by TheGoldenSun** [TeamNewPipe/NewPipe#8322]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

As you all Improve the more with other bugs that's still hidden within your newpipe app, we as the users of newpipe can't help but I wonder why can't we type our comments within your app? We should type any comments that's deemed necessary for us, can be this possible?

### Why do you want this feature?

The comments in your app shows many non-newpipe users comments which is understandable but for us newpipe users it is restricted and limited. 

### Additional information

**Comment by litetex** [comment]
https://newpipe.net/FAQ/bugs/#bugs-read-comments
