### ISSUE TITLE
Newpipe's Likes and Dislikes 

### ISSUE THREAD

**Issue by TheGoldenSun** [TeamNewPipe/NewPipe#8323]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Newpipe users should be allowed to like or dislike a video they either hardly watch or maybe like watching in your platform, please allow that to happen. 

### Why do you want this feature?

Whenever I tap the like and dislike within your platform app it doesn't show the color blue but only stays at the visible color of white instead, please fix it as you improve.

**Comment by ChiefMikeK** [comment]
Having a 👍 or thumb 👇 change color would be misleading to users who would be thinking they are voting for it online.   

I'd suggest adding a short text-field-input to the watched history database instead, if you long press either thumb ie. pop-up 🔳 MyNote-Save,   
then the user could input an emoji(s),  ★⯪☆☆☆ or, short text limited to 8 or 16 characters 💡 🗯

**Comment by litetex** [comment]
Closed in favor of #5159
