### ISSUE TITLE
Where is paused download list ?

### ISSUE THREAD

**Issue by 007chaand** [TeamNewPipe/NewPipe#8325]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

I  have started download a video , my video downloaded about 70% then I paused downloading.
After some time I thought let's resume my video downloading ,But the strange thing is that I didn't get the video anywhere and didn't show any option.

**Comment by pc00per** [comment]
Open NewPipe Sidebar & you'll see "Downloads" section.

**Comment by pc00per** [comment]
> > Open NewPipe Sidebar & you'll see "Downloads" section.
> 
> But there is only download completed videos I am looking for videos that I have paused

Did you even try checking Downloads section after pausing it?
The paused downloads do show on my side. I donno what's wrong on your side.
https://ibb.co/GRFpWfq

**Comment by RealGJ** [comment]
I confirm

> > Open NewPipe Sidebar & you'll see "Downloads" section.
> 
> But there is only download completed videos I am looking for videos that I have paused

I'm also facing this issue on version 0.22.2 android 11 Redmi note 8

**Comment by discovererer** [comment]
I'm also facing this issue on version 0.23.1,
the download list will clear at next app start, and its show only complete download list,
I have to wait until the video download get complete
