### ISSUE TITLE
Progress bar doesn't fetch video length

### ISSUE THREAD

**Issue by lawson85** [TeamNewPipe/NewPipe#8335]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Go to https://www.youtube.com/playlist?list=PLW_NpxKH1uD8LLK8RfQffDnp09Twn1sWk. It should be the Now 74 playlist!

2. Press background.

3. Watch and see. The error occurs here.

### Expected behavior

The progress bar should show the actual remaining time rather than getting stuck. The song plays as expected but the progress bar doesn't move. This is the YouTube service, not tested on other services.

### Actual behavior

Progress bar sits at what it thinks is the end, this happens over the course of multiple tracks. 

### Screenshots/Screen recordings

<img alt="Screenshot_20220502_123440_com facebook mlite" src="https://user-images.githubusercontent.com/52282566/166228473-e6fa3ae4-5beb-49de-94e0-0d12fb774cb6.jpg" height=600 />

### Logs

There's no logs

### Affected Android/Custom ROM version

A10/EMUI 10.0.0.293

### Affected device model

Honor 10 lite UK {HRY-LX1}

### Additional information

you have disabled all animations on device from developer options.

**Comment by opusforlife2** [comment]
Isn't this reported in #4590?

**Comment by lawson85** [comment]
It could be similar but I cannot quite tell

**Comment by opusforlife2** [comment]
Went through the whole thing. It is.
