### ISSUE TITLE
Search bar keyboard does not pop-in after Player UI swiped down

### ISSUE THREAD

**Issue by pc00per** [TeamNewPipe/NewPipe#8337]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Keep running Player UI
2. Swipe down the Player UI
3. Try to access search bar

### Expected behavior

Keyboard should pop up immediately.

### Actual behavior

Keyboard does not pop up at all. Instead, I have to press back to remove search bar, then access it again to pop up keyboard.

### Screenshots/Screen recordings

https://youtu.be/2mr0xPygenU

### Affected Android/Custom ROM version

Lineage OS 18.1 / March 2022

### Affected device model

Redmi Note 10

**Comment by opusforlife2** [comment]
Works fine here. Try a different keyboard app.

**Comment by pc00per** [comment]
> Works fine here. Try a different keyboard app.

Tested thoroughly & it's keyboard independent bug. Exists on my other devices too.
Are you sure you followed the screenrecord exactly as I've provided above?

**Comment by opusforlife2** [comment]
Yup. I followed your video exactly. Even paused the video to make sure there was no difference in our steps.

What keyboard apps have you tried this with? Maybe give Florisboard a try. I'm using Google Keyboard (from before it changed to GBoard).

Also, do you have multiple keyboard apps enabled and do you switch between them? Try reproducing this with only one app enabled. Maybe that will help narrow this bug down.

**Comment by SameenAhnaf** [comment]
@opusforlife2 It happens on my Xiaomi Redmi Note 8 Pro too. Interestingly, if you press `Back` and click on `Search` icon again, the keyboard works fine.

**Comment by opusforlife2** [comment]
> Interestingly, if you press Back and click on Search icon again, the keyboard works fine.

Yeah the video shows that.

@pc00per Are those other devices also Xiaomi? Or some other company?

**Comment by pc00per** [comment]
@opusforlife2 I only use GBoard & had AOSP default keyboard disabled.
Also as I specifically said to "Swipe Down" Player UI & then access search bar, unlike the usual back button to reproduce this issue.

**Comment by SameenAhnaf** [comment]
I noticed that this bug only appears if auto-rotation is disabled.

**Comment by pc00per** [comment]
> I noticed that this bug only appears if auto-rotation is disabled.

That's more strange. Not the case for me, it's same regardless of orientation lock.

**Comment by SameenAhnaf** [comment]
Sorry, I misunderstood the steps. Here's how to reproduce the bug actually.

1. Exit from Newpipe app.
2. Share a video to Newpipe.
3. Swipe down and minimize the player.
4. Click on `Search` icon.

Keyboard doesn't appear.

**Comment by TiA4f8R** [comment]
I'm pretty sure this issue is a duplicate of #7647. Please test the APK of the PR which closed the issue.

**Comment by pc00per** [comment]
@TiA4f8R I've tested #7647 fix & it fixed. Seems like PR merged 15 days ago, which does mean, will it be in the next release?

**Comment by TiA4f8R** [comment]
@pc00per Yes, it will be included in the next release.
