### ISSUE TITLE
follow system animation speed

### ISSUE THREAD

**Issue by pc00per** [TeamNewPipe/NewPipe#8342]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Link in-app animations to match the speed of Android's animation speed that's been modified from developer options.

### Why do you want this feature?

For coherent experience throughout the device as well as NewPipe when switching between viceversa.

### Additional information

Should also have ability to completely nuke animations when Android animations set to 0x.

**Comment by mhmdanas** [comment]
@pc00per can you give examples of animations in NewPipe that don't follow the system animation speed? It seems to me like some things do follow it (e.g. opening a new page, overflow menus), but the ones that don't (e.g. opening or closing the drawer) also don't follow it in the other apps I tried.

**Comment by pc00per** [comment]
@mhmdanas Sidebar & PlayerUI swipe animations.

**Comment by mhmdanas** [comment]
If by sidebar you mean the drawer, then as I said before, it seems to be always animated the same in the rest of the system.

For the "PlayerUI swipe anaimations," can you clarify what you mean? A screenshot or screen recording would be helpful for me to understand.

**Comment by pc00per** [comment]
I meant the animation of swiping "main player" screen to bottom, to reveal kiosk mode.
It's usually animated, nonethless of disabling or keeping animations.

**Comment by pc00per** [comment]
I feel like no need of this for now

**Comment by Mangallkashyap** [comment]
> ### Checklist
> * [x]  I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> * [x]  I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
> * [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
> * [x]  This issue contains only one feature request.
> * [x]  I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
> 
> ### Feature description
> Link in-app animations to match the speed of Android's animation speed that's been modified from developer options.
> 
> ### Why do you want this feature?
> For coherent experience throughout the device as well as NewPipe when switching between viceversa.
> 
> ### Additional information
> Should also have ability to completely nuke animations when Android animations set to 0x.
