### ISSUE TITLE
chapter timestamp share

### ISSUE THREAD

**Issue by pc00per** [TeamNewPipe/NewPipe#8343]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Can be implemented either in two ways:
1. Put share button beside each chapter
2. Or Hold the chapter to share the link with the chapter timestamp included

### Why do you want this feature?

To quickly share the link with timestamp included, so that the stream would play from that timestamp instead of beginning.

### Additional information

As an example, the timestamp option append looks like `&t=1m30s` at the end of the link

**Comment by Callisto404** [comment]
Hey, I'd like to attempt this feature if that is okay.

**Comment by opusforlife2** [comment]
@Callisto404 Great! Could you give a rough idea of how you will implement this, before taking this up?

**Comment by Callisto404** [comment]
Hey, first time contributor so correct me on anything and everything. To my knowledge the segmentAdapter in the MainPlayerUI class uses the getStreamSegmentListener() to implement the interface which is described in the StreamSegmentAdapter Kotlin class. If we wanted to use the OP's 2nd option for sharing with a long click could I just change the Kotlin interface to also require an onItemLongClick method with which I can use the ShareUtils class to share with the timestamp of that chapter? 
I'm sure I am misunderstanding something so any feedback is welcome, thanks.

**Comment by opusforlife2** [comment]
I'm not a dev, sorry. I'll see if a team dev can have a look at your question.
