### ISSUE TITLE
Channel Groups not showing all videos

### ISSUE THREAD

**Issue by IronGibbet** [TeamNewPipe/NewPipe#8346]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

This is not for every video! But it happens more regularly (more common with clips than longer videos)
1. Watch a video listed in a Channel Group to the end or the point where NewPipe would start it from the beginning when opening it again.
2. After going back from the video to the Channel Group the just watched video won't show up anymore or (less common) some vanish after refreshing the Channel Group but none have shown up again.

### Expected behavior

After going back to the specific Channel group from the video said video should still show up.

### Actual behavior

Some videos don't show up anymore.

### Affected Android/Custom ROM version

Android 9

### Affected device model

XiaoMi Mi A1

**Comment by opusforlife2** [comment]
There's an eye icon in every channel group which hides watched items. Please see if that's enabled or disabled.

**Comment by IronGibbet** [comment]
@opusforlife2 thanks a lot! It was ticked.
Strange that it didn't hide all of the watched videos for me.
