### ISSUE TITLE
No buffering when paused?

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamNewPipe/NewPipe#8348]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Is it supposed to be the case that the video does not buffer while the video is paused?

### Additional information

Not buffering when paused is infortunate when connection is poor. It might contribute to the "intermittent loading" issue that is pinned.

**Comment by opusforlife2** [comment]
No. The buffering happens, but the seekbar doesn't get updated that frequently. If you seek close to the edge of the buffered section, you'll notice that it expands rapidly. You might have to play the stream for it to happen.
