### ISSUE TITLE
Download duplicates file existed in list

### ISSUE THREAD

**Issue by Munkiiedude** [TeamNewPipe/NewPipe#835]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

This issue occurs on version 0.11.0.

I tried downloading some mobile phone reviews and when I switched to other apps, back to Newpipe, the app took a long time to load. I exited Newpipe by swiping, relaunch it and from download list each item duplicated. From file explorer I checked the file has both .mp4 and .giga file. 

So what I did was either I chose one of it to download, when download completed, the video won't play and file explorer shows only .mp4. And the duplicated file on download list which I start download, after completion, the video still won't play and file explorer shows only .mp4. (usually on file explorer will show thumbnails but just video icon)

Conclusion, I used mobile data to download the videos and seems a waste of data if download list deceived the completion but can't play video plus duplicates same file at same partly downloaded file with same percentage.

**Comment by theScrabi** [comment]
Have you checked the size of the .giga file? Could it be that these are just gigaget metafiles?

**Comment by Munkiiedude** [comment]
Yes I did check the .giga file sizes, it's within kB rather in mB. While  .mp4 exact size of download according to selected resolution in mB, which was in complete size but not filled with video data.

**Comment by theScrabi** [comment]
Hm well. The problem is that gigaget is broken. We have to replace it anyway.
