### ISSUE TITLE
Some Downloaded Videos Desynced at 480p

### ISSUE THREAD

**Issue by TheAbsntDrknss** [TeamNewPipe/NewPipe#8350]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Go to a video (Such as https://www.youtube.com/watch?v=lt9u-8rp4mE)
2. Download said video at 480p
3. Play the downloaded video
4. If it works like normal, try another video (Almost all of 8-BitRyan's Subnautica 1.0 playlist at https://www.youtube.com/playlist?list=PLSIYrUsOI8i6a1vDZ7x-f9o0QGcVhCePd have this issue)

### Expected behavior

The video downloads and plays like normal.

### Actual behavior

Some videos, when downloaded at 480p have audio that plays like normal, but the visuals are slowed to about half speed, causing a big and very noticable desync in the video. When those same videos are downloaded at 720p, however, they are perfectly fine and play like normal

### Screenshots/Screen recordings

Here is the link to a recording in my Google Drive: https://drive.google.com/file/d/1p51-rrk_ApTgTkSQ1mEF0imOCpRcCaKY/view?usp=drivesdk

### Affected Android/Custom ROM version

Android 9

### Affected device model

Samsung Galaxy Note 8

**Comment by opusforlife2** [comment]
Please try this on another device.
