### ISSUE TITLE
Mark as wached and watched progress not working for youtube "shorts"

### ISSUE THREAD

**Issue by grrrrr** [TeamNewPipe/NewPipe#8352]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. go to any youtube #shorts (video is in portrait view) in your personal subscriptions
2. either play it or `mark it as watched` via the long press menu
3. refresh the feed

### Expected behavior

The video will display with the "watched progress bar" at the bottom of the thumbnail

### Actual behavior

no  "watched progress bar" appears on the short video

### Affected Android/Custom ROM version

Android 10

### Affected device model

Samsung Galaxy S9

### Additional information

This behavior is not seen if you search for shorts and mark them as watched,  they instead behave as expected.   

All other videos (those in landscape) regardless of length behave as expected

I have cleared caches from within the app as well as via the app info option in android.

This was also observed happening for at least 2 releases prior to 0.23.0

**Comment by litetex** [comment]
This is likely related to https://github.com/TeamNewPipe/NewPipe/issues/8034

**Comment by Stypox** [comment]
> This is likely related to https://github.com/TeamNewPipe/NewPipe/issues/8034

Yes, and we can't do anything about this unfortunately. I'm closing this in favour of #8034
