### ISSUE TITLE
Use MANAGE_EXTERNAL_STORAGE permission on Android TV to properly access storage

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#8359]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Newpipe should use the MANAGE_EXTERNAL_STORAGE permission on Android TV devices so that file I/O works properly/bug-free.

### Why do you want this feature?

Storage access seems to be broken on Android TV, which affects Newpipe's file I/O operations, such as importing subscriptions.

See https://github.com/TeamNewPipe/NewPipe/issues/8195#issuecomment-1115165403 and https://github.com/TeamNewPipe/NewPipe/issues/8195#issuecomment-1115232521 for context.

**Comment by opusforlife2** [comment]
@moneytoo Is this info accurate? Anything to add?

**Comment by litetex** [comment]
_Not sure who is working at Google and thought "Android TV is production ready" while they forgot to "implement" the only working storage framework... WTF_

Can't recommend adding that permission to the overall app:

https://developer.android.com/training/data-storage/manage-all-files
> An app can request All files access from the user by doing the following:
> 1. Declare the [MANAGE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#MANAGE_EXTERNAL_STORAGE) permission in the manifest.

As far as I know we can only ship one manifest file for the complete app.

Also:
> You should request the MANAGE_EXTERNAL_STORAGE permission only when your app cannot effectively make use of the more privacy-friendly APIs, such as Storage Access Framework or the Media Store API.

Not sure if accessing all data is a good idea - from a security viewpoint.

**Comment by opusforlife2** [comment]
> As far as I know we can only ship one manifest file for the complete app.

So that means if we go ahead with this, there would need to be a separate build for Android TV?

**Comment by opusforlife2** [comment]
We have already applied the Android TV label, though? Why device/software specific, @litetex?

**Comment by litetex** [comment]
@opusforlife2 

> https://commonsware.com/blog/2019/12/08/more-missing-saf.html 

From one of the comments in the PR.
According to the article it works on ~~some~~ ``¯\_(ツ)_/¯`` TVs.

**Comment by Stypox** [comment]
> Can't recommend adding that permission to the overall app:

Yes, we switched to fully SAF exactly to switch away from that permission. We can't reintroduce it.

**Comment by PrzemekSkw** [comment]
Hello, I cannot import on Canal+ android tv box but I can in FireTV stick 4k max.
Regards.

**Comment by opusforlife2** [comment]
> We can't reintroduce it.

So, close as wontfix, @Stypox?

**Comment by Stypox** [comment]
Yes, unfortunately
