### ISSUE TITLE
Add ability to filter videos after search by time or by viewing count

### ISSUE THREAD

**Issue by GNHANNA** [TeamNewPipe/NewPipe#8361]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add ability to filter videos after search by time or by viewing count

### Why do you want this feature?

To. Make search more easy and accessible

**Comment by SameenAhnaf** [comment]
This issue should be closed in favor of #2251
