### ISSUE TITLE
Spotify-like Listen Along feature using free WebRTC Signaling Servers

### ISSUE THREAD

**Issue by theArtechnology** [TeamNewPipe/NewPipe#8366]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The title is self-explanatory. 

but TLDR;

- Join a session with someone using a QR or a key,
- When something is changed in the app,
 - Add to playlist
 - Currently played music
 - Play/Pause/Stop
 - Seek
 - All these events are sent to the Signaling server, which is shared to everyone in the session, enabling every one to listen along

### Why do you want this feature?

Having a background music app is cool. Having friends to listen music with, is even cooler. What do you think ?

### Additional information

An example here:

https://github.com/saltyrtc/saltyrtc-demo

**Comment by opusforlife2** [comment]
Is that not possible through existing music servers, like MPD, Subsonic, Funkwhale, etc?

**Comment by mujibultanim** [comment]
It would be better for listening YouTube podcasts if they had added *sleep timer* feature in the app.

**Comment by theArtechnology** [comment]
I don't know, surely we can check that out, but honestly having free p2p network available should be good to go.

**Comment by mhmdanas** [comment]
While I do agree that this would be pretty cool, I believe it's out of scope for NewPipe. What do the other team members think?

**Comment by opusforlife2** [comment]
It is, especially if it can be done through the software solutions I listed above. @theArtechnology You should at least test them if you're interested.
