### ISSUE TITLE
playback control is not working on tv 

### ISSUE THREAD

**Issue by Jknavy** [TeamNewPipe/NewPipe#8369]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

This app is lifesaver against tyranny of YouTube. 
A request. 
The playback speed control was working on tv in previous versions but now it is not working.
It was the best feature. You will be loved if you rectify it.
With love....... 

### Why do you want this feature?

To listen to slow speakers to save precious time.

**Comment by TiA4f8R** [comment]
When something stopped working in the latest version and was working before, it is a regression, and so a bug. For such cases, use the bug report template instead of the feature request template.

Could you edit your issue to use the bug report template and fill all required details, or open a new issue with the bug report template? Thank you!

**Comment by pc00per** [comment]
By the time it gets resolved, I suggest you to try SmartTubeNext. It's the best project for Android TV as it adapts well on that platform.
