### ISSUE TITLE
[Request] Support for opt-in setting for Opus downloads

### ISSUE THREAD

**Issue by sigmarelax** [TeamNewPipe/NewPipe#837]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Opus downloads have been [left out due to inconsistent support on pre-Android 5.0 devices](https://github.com/TeamNewPipe/NewPipeExtractor/blob/b9d09414113eba7ceab6ccc1a17a3ba055d2b0b7/src/main/java/org/schabi/newpipe/extractor/services/youtube/ItagItem.java#L37). This is unfortunate because the audio-only bitrate for most videos in NewPipe is 128kbps, even though Opus@160 is available. Additionally, low bitrate Opus is very efficient and the codec is more free/libre than AAC.

I propose adding a setting for NewPipe that enables Opus downloads (with default=false). Here's a quick mockup: https://i.imgur.com/97Gsjij.png

Opus has been mentioned in other submitted issues, but a similar proposal has not been made. Adding this option for users is appropriate at this point since 80% of all Android devices are on 5.0+. This percentage is likely higher for the install-base of NewPipe and will only continue going up.

**Comment by theScrabi** [comment]
Sounds reasonable.

**Comment by Cormak** [comment]
I'm honestly surprised this was the reason for leaving it out when Newpipe is supposed to be a libre-alternative to Youtube and Opus downloads would have served millions of people just fine.

**Comment by theScrabi** [comment]
But I remember two years ago when I maped the youtube itags to the corresponding formats that I used a slightly outdated list, and I only mapped a small part of that list. I'm with you tho opus support should be added.

**Comment by theScrabi** [comment]
will be closed in the sake of #1059
