### ISSUE TITLE
How to resize thumbnail with clear image 

### ISSUE THREAD

**Issue by tahiyat206** [TeamNewPipe/NewPipe#8378]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

few days ago I'm start learning newpipe for increase my knowledge. And now trying to do something new experiments. When I'm resize the video thumbnail, image not loading clearly
How can i load image clearly with any size?
Please let me know

### Additional information

I'm trying everything but i can't increase thumbnail image size with newpipe

**Comment by litetex** [comment]
> I'm start learning newpipe

You can't learn NewPipe. It's an app. I think you are reffering to Android or?

> When I'm resize the video thumbnail, image not loading clearly

More context please (code snippet).
Is this related to NewPipe (something inside the app) or is it related to Android in general?
If it's related to Android it probably doesn't belong here.

**Comment by tahiyat206** [comment]
![Screenshot_20220512-014003_NewPipe Debug](https://user-images.githubusercontent.com/97298249/167932599-8dd8552b-c36f-480c-bf8e-51da572633a6.jpg)
![Screenshot_20220512-013955_NewPipe Debug](https://user-images.githubusercontent.com/97298249/167932607-d86c0200-3bd6-4c13-9628-7023f7fc2992.jpg)
Check this 2 screen soot. I'm just resize the stream item size. You can see the result. Trending page and suggestion screen stream item isn’t clear image you can see in screen soot but when click then video it’s loading clear quality. I hope you can understand now what I'm saying about. Now can you let me know how can i load clear quality stream item thumble images?

**Comment by tahiyat206** [comment]
Okay i can understand. But can you please let me know how songtube loading clear thumbnails using your extractor?  Checkout screenshots and sorry for my English 😅
![Screenshot_20220517-010156_SongTube](https://user-images.githubusercontent.com/97298249/168663930-ec039d10-5352-4640-8911-2fdc4efdada8.jpg)
![Screenshot_20220517-005948_SongTube](https://user-images.githubusercontent.com/97298249/168663937-cd28bfc6-841d-4023-b6c4-2e7e693854b1.jpg)

**Comment by litetex** [comment]
@tahiyat206 
I'm not involved into SongTube so I guess you have to ask the corresponding developer instead ;)

However it looks like they are using a modified version of our extractor:
https://github.com/SongTube/SongTube-App/blob/4879e7bbc1988c1c28eb3e3f206fa77586808016/lib/ui/layout/streamsLargeThumbnail.dart#L191-L205
Here ``infoItem.thumbnails.maxresdefault`` is called. However there is no such method inside our normal extractor (because ``maxresdefault`` is YT specific).
Look like it was somehow added in 
https://github.com/SongTube/NewPipeExtractor_Dart/blob/f9a47abfa07ecb71cb1ca2de308d9e4a7975e756/lib/utils/thumbnails.dart#L13

**Comment by TiA4f8R** [comment]
See also #3190 and the pull requests linked (in the issue or in the pull requests themselves).

**Comment by tahiyat206** [comment]
thank you issue solved
