### ISSUE TITLE
[QoL] Customizable left/right swipe gestures in video lists.

### ISSUE THREAD

**Issue by rey0n** [TeamNewPipe/NewPipe#8388]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

What's the most used action in app? Long-press menu with actions - user has to long-press on video-cards dozens of times every day as that's how one operates with items.
I propose adding 2 customizable swype gestures(swype left, swype right) for user to select couple most used action for those. Constant repeating actions of "long-press + select action" would just work with a swype.

### Why do you want this feature?

This would make interacting with app much more comfortable, without need to constantly use long-press menu, and instead use swypes for most needed actions. Plus, as it would be configurable, both right- and left-handed users will be pleased.

For example, user can configure swypes as:
- Swype Left: Add to Queue      - Swype Right: Go to channel
- Swype Left: Mark as watched  - Swype Right: Open in browser
- Swype Left: Share                   - Swype Right: Delete

### Additional information

I checked 9 search pages and acknowledge [this issue](https://github.com/TeamNewPipe/NewPipe/issues/5657) is somewhat similar, BUT my topic is in no way a duplicate, just similar desire directions. Yet that wish was about bulk/mass selection, while mine is about actions with individual video-cards.

**Comment by SameenAhnaf** [comment]
Rejected as mentioned in https://github.com/TeamNewPipe/NewPipe/issues/6187#issuecomment-904445140
