### ISSUE TITLE
Popup player and "display over apps" disables touch screen as a whole

### ISSUE THREAD

**Issue by flacito13** [TeamNewPipe/NewPipe#8393]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

Go to 'pop up player'
Go to another app while running pop up player
Touch screen is disabled. Screen does kit respond to feedback.
Fix by disabling pop up screen

 Rom: MIUI EU 13.0.3
Pooxo pro f3 

### Expected behavior

Go to 'pop up player'
Go to another app while running pop up player
Touch screen is disabled. Screen does kit respond to feedback.
Fix by disabling pop up screen

 Rom: MIUI EU 13.0.3
Pooxo pro f3 

### Actual behavior

Go to 'pop up player'
Go to another app while running pop up player
Touch screen is disabled. Screen does kit respond to feedback.
Fix by disabling pop up screen

 Rom: MIUI EU 13.0.3
Pooxo pro f3 

### Logs

No logs 

### Affected Android/Custom ROM version

Miui 13.0.3 eu 

### Affected device model

Poco f3

### Additional information

Go to 'pop up player'
Go to another app while running pop up player
Touch screen is disabled. Screen does kit respond to feedback.
Fix by disabling pop up screen

 Rom: MIUI EU 13.0.3
Pooxo pro f3

**Comment by SameenAhnaf** [comment]
>[x] I am able to reproduce the bug with the latest version.

No, 0.22.2 is not the latest version. Please update your app to 0.23.0.

**Comment by flacito13** [comment]
Latest version fixes the issue. May j recommend a notification when new version is available or is this already in the app?

**Comment by SameenAhnaf** [comment]
Go to `Settings`>`Updates`> Enable `Updates: Show a notification to prompt app update`
