### ISSUE TITLE
Video titles in Newpipe and on YouTube website are different

### ISSUE THREAD

**Issue by heuwerk** [TeamNewPipe/NewPipe#8394]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Search for *c't 3003* on Newpipe
2. Open the *c't 3003* Channel
3. Navigate with Webbrowser to `https://www.youtube.com/ct3003`
4. Click on Video Tab
5. Compare Video Titles

### Expected behavior

The video title should also be identical for all platforms.

### Actual behavior

The video title in Newpipe is different from the one on the YouTube website. Most of the time it is displayed in English instead of German.

### Screenshots/Screen recordings

# Newpipe Screenshot
<img alt="Screenshot_20220513-172520" src="https://user-images.githubusercontent.com/75751604/168316371-a9777ee6-482a-4c79-aa21-bb556bfc8898.png" height=600 />

# Screenshot from Webbrowser

![grafik](https://user-images.githubusercontent.com/75751604/168316584-cac5b989-c944-4bd9-bd44-c32f27a2246c.png)

### Affected Android/Custom ROM version

Android 12L / GrapheneOS

### Affected device model

Google Pixel 5

**Comment by czarkoff** [comment]
@heuwerk ,  how is your default content language set in Options/Content?

**Comment by heuwerk** [comment]
The default content language is set to system default, which is german in my case.

**Comment by alkorang** [comment]
My system default language is Korean. Some Korean vidoes has translation of titles and descriptions in English. In YouTube app or Chrome, those titles are shown in Korean. In NewPipe, they display in English. I tried to change the NewPipe language setting from system default to Korean, but NewPipe still shows their English titles instead of Korean titles.

**Comment by heuwerk** [comment]
**Correction:** The titles are only in English in the subscription box and on the channel page, in the search they are correct.

**Comment by heuwerk** [comment]
I switched the YouTube website to English and sure enough, the titles were the same as in the subscription box and on the channel page (Although I did not set Newpipe to English).
I think then it is not a bug and this issue can be closed.

**Comment by alkorang** [comment]
> in the search they are correct.

In my case, NewPipe always displays titles of some videos in English, even if they have titles in Korean in youtube.com. Unless someone explicitly mention that NewPipe always loads English titles and descriptions first, then I think that this is a valid issue.
