### ISSUE TITLE
New Rutube service

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#8408]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add a new Rutube service to NewPipe
link: https://rutube.ru/

### Why do you want this feature?

Firstly, this service is almost like YouTube, but there are free movies, series, radio and videos.
Secondly, if there is no video that you are looking for on other services, you can search here, but for the most part, the service is Russian (as I understand it).
But still the service is good and I would like to have the ability to switch to the Rutube service in NewPipe.

### Additional information

And if possible, could you write that it will be added or Why not added?

**Comment by TiA4f8R** [comment]
> - [x] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).

This is not a request for NewPipe itself. Read the template carefully the next time you want to open an issue. Thank you.
