### ISSUE TITLE
Swap the chapter and queue icon

### ISSUE THREAD

**Issue by AinulAbir** [TeamNewPipe/NewPipe#8409]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

As title states swap the two icons, or change to new icon
![Screen Shot 2022-05-17 at 12 19 24 PM](https://user-images.githubusercontent.com/33160846/168861429-93a931cc-a507-4054-a2c2-43845d606b25.png)
s

### Why do you want this feature?

To clear up any confusion, I still get confused between the two. The queue icon should be the numbered one as that makes more sense.

**Comment by SameenAhnaf** [comment]
Your another issue #8410 asks for play queue as a video info tab. Should this still be considered separately?

**Comment by mhmdanas** [comment]
@AinulAbir I agree that this is somewhat confusing, but even if the two were switched, I think confusion could still arise. Replacing one of the icons with another icon may be a better solution.

@SameenAhnaf this issue and #8410 are not mutually exclusive; the queue button in the player is still useful when watching a video in fullscreen.

**Comment by tutacat** [comment]
Swapping the two wouldbe more confusing... just need a new icon
