### ISSUE TITLE
Title loss after orientation change 

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#841]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

The title of the main page gets lost under Android 6.0 when rotating the device. It only happened to me with the YouTube/trending kiosk using the current dev.

Steps to reproduce:
1. Select YouTube/trending as content of your main page
2. Go to main and notice the "Trending" in the app bar.
3. Rotate your device and "Trending" is gone. ("Subscriptions" title is still there)

**Comment by lawonga** [comment]
Fixed

**Comment by lawonga** [comment]
Fixed
