### ISSUE TITLE
Font size and/or thumbnails too small

### ISSUE THREAD

**Issue by Gelip** [TeamNewPipe/NewPipe#8412]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The font and/or thumbnails should be slightly larger, e.g. like in the YouTube plugin:
![newpipe](https://user-images.githubusercontent.com/16385203/168955149-00362f06-8471-4459-8e08-46a0cbd19386.png)
![youtube](https://user-images.githubusercontent.com/16385203/168955177-2820c212-1f9a-4703-b320-bcfb0ac3ec30.png)

### Why do you want this feature?

I use NewPipe on SmartTV Box with Android in 1280x720 screen resolution the font is not readable because it is too small.

**Comment by mhmdanas** [comment]
Did you try to increase your system's font size in the system settings?

**Comment by Gelip** [comment]
> Did you try to increase your system's font size in the system settings?

Yes, increasing the font in the system helps but NewPipe would use better if the font and thumbnails would be slightly larger.

**Comment by AinulAbir** [comment]
It would be better if newpipe adjusted better based on screen/device or a manual zoom option would have been better. Even on tablets the icons and fonts seems slightly to small

**Comment by laraib07** [comment]
Even on mobile, I think thumbnail preview is quite small.

**Comment by mahendranv** [comment]
@SameenAhnaf Updated the thumbnail size for w800. Tablets and TV will have ~3 items per row.

Existing 164x92
New 280x160

If anyone wants to try, here is the apk: [Large_thumbs_TV.zip](https://github.com/TeamNewPipe/NewPipe/files/9944454/Large_thumbs_TV.zip)

![image](https://user-images.githubusercontent.com/6584143/200134714-f9495af8-acac-48bf-a4f0-246f9569e41e.png)

**Comment by peat80** [comment]
On a 4k tv probably 4 items also would fit fine.
I get 5 per default on my shield now. 
3 is a little bit too big for my taste. Maybe 4 would be idea.
But i could also live with 3 items per row.

Could you also change the subscription layout for tv please? I get 7 items per row per default. Could this also be reduced to at least 5 or less per default?

**Comment by mahendranv** [comment]
@peat80 Grid span is calculated based on screen size. In your TV you might get 4 items. Please try the test build.

> Even better would be if one would be able to configure the grid maybe.
This might take some effort rewriting the existing logic. Let's park the above solution as temporary solution and grid customization shall follow as separate FR.

**Comment by Gelip** [comment]
> Existing 164x92
> New 280x160

Thanks, now it's much better :-)

**Comment by Stypox** [comment]
Apparently some users have a different opinion: https://github.com/TeamNewPipe/NewPipe/pull/9310#issuecomment-1407615544
