### ISSUE TITLE
can't minimize the video page while on one hand mode

### ISSUE THREAD

**Issue by pokegamer5547** [TeamNewPipe/NewPipe#8422]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Play any video
2. Enter one hand mode
3. Try swiping down on video.

### Actual behavior

when swiping down on video, it doesnt minimize the video page when running one hand mode.

### Screenshots/Screen recordings

<img alt="Screenshot_20220519-203027_NewPipe" src="https://user-images.githubusercontent.com/65234485/169328413-f8421b4d-170a-49c4-95cb-521f9bd9e604.png" height=600 />

### Affected Android/Custom ROM version

Android 12L/CherishOS

### Affected device model

poco m2 pro

**Comment by litetex** [comment]
Android doesn't seem to have a one handed mode by default (my official emulators don't have one).
I also don't know that kind of one-handed mode. The one on my smartphone (Huawei; Android 9; see https://consumer.huawei.com/en/support/content/en-us00785200/) works fine with NewPipe.

Looks like a device/OS specific problem to me.

**Comment by pokegamer5547** [comment]
@litetex yes you're right, one hand mode i'm using  was added in android 12 for first time back then.

**Comment by Jean-BaptisteC** [comment]
It's not a bug on Newpipe. One handed mode are created like this.
With all app in one handed mode we can't access to the bottom app.

**Comment by pokegamer5547** [comment]
> One handed mode are created like this. With all app in one handed mode we can't access to the bottom app.

i see :( so it can't be fixed then. I understand, i'll close this issue.

**Comment by litetex** [comment]
@Jean-BaptisteC 
> One handed mode are created like this.
> With all app in one handed mode we can't access to the bottom app.

What are you talking about?
This looks like a device/OS specific problem. Did you even read the issue or my comment above?

I would say we wait a bit - maybe the device manufacturer delivers an update which fixes the issue.
Or maybe Google adds a one handed mode inside there emulators so we are able to reproduce the problem.

Otherwise this issue can be closed.

**Comment by Jean-BaptisteC** [comment]
I am able to reproduce on Pixel 6 / Android 12L.
I have test with app Youtube, no problem we can reduce video.
