### ISSUE TITLE
Soundcloud links sometimes fail to open

### ISSUE THREAD

**Issue by Fasto5** [TeamNewPipe/NewPipe#8426]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

When I click 'share' on Android, on a soundcloud link and select to New Pipe, I get the following error:

I have had this error via sharing from discord, and also via sharing from Brave Browser.

I've tried the mobile version of the soundcloud URL and the desktop version.

Eg, this URL fails to open
https://soundcloud.com/asitiz/praxis-april-tech-asitiz-remix/s-zdp7y9diIL2

Whereas this URL DOES WORK
https://soundcloud.com/samathdnb/samath-the-magician-1k-followers-free-dl

### Expected behavior

Soundcloud links should open when shared to New Pipe 

### Actual behavior

I've explained it clearly above.
<img alt="Screenshot_20220522-133655_NewPipe" src="https://user-images.githubusercontent.com/82982095/169677312-add04e48-12e4-40e2-b415-5c12aafaf9ea.jpg" height=600 />

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung galaxy s20

**Comment by TiA4f8R** [comment]
The `s-zdp7y9diIL2` part of the URL means that the track is private/unlisted (this is a secret token, required in order to access to the track). Tracks, playlists and albums with secret tokens are not supported by NewPipe Extractor.

I am merging this issue into #4863, which explain more how this works (and also applies for albums and tracks).
