### ISSUE TITLE
displaying over other apps even background playing.

### ISSUE THREAD

**Issue by rayhantajichalt** [TeamNewPipe/NewPipe#8428]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

pressed background playing

### Actual behavior

android system gives a presistent (displaying over other apps) notification even i selected audio only background play not Picture in Picture.

### Screenshots/Screen recordings

<img alt="Screenshot_20220522-230632_Chrome" src="https://user-images.githubusercontent.com/35326882/169704858-0ae595c7-54fb-4489-93d4-7357b46bc32d.jpg" height=600 />

### Affected Android/Custom ROM version

android 12 / One UI 4.1

### Affected device model

Samsung Galaxy A51

**Comment by randomizzerr** [comment]
This bug also occurs on Pixel 6 (Android 12 / 5 June 2022 security update). 
Just mentioning this to say that it's not specific to the Samsung/OneUI device.

**Comment by Stypox** [comment]
Can you test if #8170 solves this?

**Comment by tsiflimagas** [comment]
At least I can no longer reproduce it.

**Comment by Stypox** [comment]
Ok, then I will close as the fix will be present in next release. If the issue was not actually fixed by #8170, feel free to reopen
