### ISSUE TITLE
Preferred 'open' action setting does not work as intended

### ISSUE THREAD

**Issue by osshelper** [TeamNewPipe/NewPipe#8429]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Go to settings
2. Go to 'Video & Audio'
3. Navigate to 'Behavior' section
4. Set the "Preferred 'open' action" as "Background Player"

### Expected behavior

On clicking a video, it should start playing in the background

### Actual behavior

The video plays in the video player

### Screenshots/Screen recordings

<img alt="2022-05-22 23-29-27 High Res Screenshot" src="https://user-images.githubusercontent.com/106005675/169709195-b81ff04d-a1da-4f4b-b0e7-5332b631ecd6.png" height=600 />

**Comment by mhmdanas** [comment]
I believe that only applies to links sent from other apps for NewPipe to handle, and so this _is_ working as intended.
