### ISSUE TITLE
Popup Default Resolution Setting Ignored

### ISSUE THREAD

**Issue by Yowlen** [TeamNewPipe/NewPipe#843]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

When playing as a popup, the player defaults to whatever is selected in the video.
![screenshot_2017-11-12-18-53-48](https://user-images.githubusercontent.com/17078692/32704907-0b950528-c7db-11e7-8a92-aabbad74fe39.png)
For example, playing the video from the above screenshot in a popup window would render it in 720p despite having 360p set in the Settings:
![screenshot_2017-11-12-18-55-02](https://user-images.githubusercontent.com/17078692/32704911-2fa051a2-c7db-11e7-87a6-a21a541cf07a.png)

**Comment by karyogamy** [comment]
This is the expected behavior. If you are on the latest release (v0.11), then you can long click the popup button to start the video as a queue, where the player will use the default resolution. You will need to close the existing popup first though, as queuing on an existing player will use the selected quality on the player.

**Comment by Yowlen** [comment]
Oh, good to know. I updated to 0.11 before filing the report to ensure it was still present, tbh.

Still, that setting could probably use a footnote added to it to let the user know it only applies to queueing.

**Comment by Yowlen** [comment]
Still an issue because the user has no way of knowing about this behavior.

**Comment by Yowlen** [comment]
Now the setting is ignored completely, even on fresh popups. Pretty sure it's been this way for quite a few versions, but it didn't really click for me that this was happening until now.

**Comment by Yowlen** [comment]
Sorry for the previous (now deleted) comment. I forgot the way the intended behavior was supposed to work.

Still, since I'm here, is there any update on letting the user know this from within the app? Cuz judging by how someone else filed a duplicate report a few months ago, I'm clearly not the only one getting tripped up by it.

Even just renaming the setting to "Default Enqueued Popup Resolution" would be a big improvement and make it less likely to trip people up, though a little question mark that can be tapped for more detailed information would be even better.

**Comment by opusforlife2** [comment]
@Yowlen This seems to have been automatically resolved by the unified player (@avently you marvellous angel) so can you test this apk and confirm? https://github.com/TeamNewPipe/NewPipe/files/5083926/app-debug.zip

**Comment by Yowlen** [comment]
Yes, I can confirm that it's solved in that build. The new in-window player looks great too. Needs the top bar with the back button put back imo, since NewPipe has different behavior for it than it does for the Android system's back button when opening external links and depending on the situation, I often use both. It'd be a pain to have to have to close NewPipe, return to the home screen, and then re-open it from there as an alternative to that back button.

**Comment by opusforlife2** [comment]
Alright. Closing this as fixed by #2907.

**Comment by opusforlife2** [comment]
The back button is still there on all views except the Video Details page. There, instead, you have the ability to swipe down to minimize the player.
