### ISSUE TITLE
Making updating more faster by doing local patching

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#8434]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Currently when ever a new version of NewPipe come up we can have to download the full APK and reinstall it.
The apk file size is about `7 MB` which isn't that huge, but for people who have slow internet that kinda sucks.
I think that it's possible to apply the "`[HotFix](https://de.m.wikipedia.org/wiki/Hotfix) `" techniq for the android platform.
How ever my idea is a little bit different, which is to create a create a patch file and applying it localy by fetching the current apk from system than performing the patch, the result will be a apk of the new version of NewPipe.
I tried to create a patch file with `diff` but didn't work, since it doesn't create binary patches.
Even though `bsdiff` might be right one here.
And what about applying the patch?
Ok, maybe creating a simple patch system for NewPipe.

### Why do you want this feature?

Cause I want to be able to get the latest version more faster, and also to save a couple of MB.

**Comment by SameenAhnaf** [comment]
Implementing https://github.com/TeamNewPipe/NewPipe/issues/7009 is a better solution, I guess. That'd also let the user to choose whichever version they prefer.

**Comment by dynfactor** [comment]
@SameenAhnaf it's also a good solution to update the extractor :)
But what if NewPipe adds or removes permissions or add new libraries? Unfortunately updating the extractor won't be enough.

**Comment by pc00per** [comment]
Hotfix updates are rarely used because when you skip many updates, patches will get piled up more than the actual size of the app & complicate itself. And also causes confusion for new users to even begin with.

**Comment by tsiflimagas** [comment]
I don't think such gimmicks would work for Android, though I'm not sure. It would to have to be done the way Playstore does, if that mechanism is known. Else, I haven't seen any such thing on any other opensource project. As for the size, even on the worst network ever, I don't think it really hurts anyone to download 7Mb (which really is small) every few months, or repeat after a while for hotfix updates. If that was the case, it would hurt them much more watching YouTube videos on that slow network.

**Comment by dynfactor** [comment]
I agree with you @tsiflimagas at some points, but still thought this feature will be nice :)

**Comment by litetex** [comment]
Closed.

1. The author delete his account - no further discussion is possible.
2. If you have problems downloading a 7MB apk file (which is done on a 5MBit/s connection within 20s) you probably can't even watch videos.
3. The author is using largely buzzwords without any idea how to implement this on the Android platform or if it's even possible.
4. The amount to implement this largely prevails it's actual useage.
5. https://github.com/TeamNewPipe/NewPipe/issues/8434#issuecomment-1138297746
