### ISSUE TITLE
Cannot import subscriptions file on Android tv Box

### ISSUE THREAD

**Issue by PrzemekSkw** [TeamNewPipe/NewPipe#8435]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23

### Steps to reproduce the bug

I try to import Google takeout zip file on Canal+ Android tv box but when I click IMPORT button I get info that there's no application to do that task.
Do I have to install some additional dependences?

### Expected behavior

Open browser to choose zip file.

### Actual behavior

Don't open anything when click IMPORT button.

### Affected device model

Canal+ Android TV Box

**Comment by ChiefMikeK** [comment]
see #8359
