### ISSUE TITLE
Great preview of the video

### ISSUE THREAD

**Issue by Legoks** [TeamNewPipe/NewPipe#8445]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Enlarge video preview!

### Why do you want this feature?

It was better to be like that!

**Comment by litetex** [comment]
You clearly didn't check the existing issues.

I already closed at least 2 duplicates of the same "feature" request this year.

Example: #7558
