### ISSUE TITLE
button to "clone" paylist from playlist page wthout going to queue page

### ISSUE THREAD

**Issue by dasapa4746** [TeamNewPipe/NewPipe#8450]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

add the cloning or duplicating/copying playlist option that appears when you enqueue a playlist to the playlist page so you dont have to enqueue it to clone it

### Why do you want this feature?

this is also not my desperately wanted feature, but would be nice to have long term. it cuts a few steps if you want to copy and edit a playlist

### Additional information

here is a mockup of what it could look like
![Screenshot_20220527-185307](https://user-images.githubusercontent.com/106407544/170795033-39e8d821-59cc-4eef-afce-9911ef7702e9.png)

**Comment by SameenAhnaf** [comment]
Already fixed by https://github.com/TeamNewPipe/NewPipe/pull/7355 and expected to be included in next version.
