### ISSUE TITLE
Play for playlist Offline (audio only)

### ISSUE THREAD

**Issue by gcandrade10** [TeamNewPipe/NewPipe#8459]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like to be able to listen a playlist w/o internet using the the background player.

This one is related to [#5482](https://github.com/TeamNewPipe/NewPipe/issues/5482) But it's not the same

### Why do you want this feature?

My use case of the app is mainly for audio, I love the background play!

When I don't have internet or the connection is not stable I just can't use NewPipe.

My alternatives are like download a full album and play it with vlc but then I can't skip.

Or just download one by the one and then create a playlist by hand which is very tedious!

**Comment by gcandrade10** [comment]
Sorry fot the enhancement label, this is Feature Request but I can edit the labels :(

**Comment by SameenAhnaf** [comment]
You may edit the title into `Save playlist info while downloading videos`.

**Comment by mhmdanas** [comment]
> Sorry fot the enhancement label, this is Feature Request but I can edit the labels :(

By "enhancement" we do mean "feature request."

**Comment by opusforlife2** [comment]
Haven't we rejected offline playback as out of scope for Newpipe?

**Comment by gcandrade10** [comment]
That's a shame @opusforlife2 I decided to do it myself and it's almost done 😅 
I will try to clean my code and create a PR on the weekend

**Comment by mhmdanas** [comment]
Ah, my bad, I didn't take a good at the issue, or I would've told you that it was rejected from the start. However, since you worked on it, you can at least use the feature yourself. :)

> I will [...] create a PR on the weekend

You can do that, but as stated by @opusforlife2 already, we won't be merging it.
