### ISSUE TITLE
client.name =WEB_REMIX =>>client.name = ANDROID_MUSIC

### ISSUE THREAD

**Issue by Jiang00** [TeamNewPipe/NewPipe#8463]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Is there a way to get client.version with client.name = ANDROID_MUSIC
The player interface passes {clientName: "ANDROID_MUSIC"
clientVersion: "xxx"} will get the unencrypted playback address

**Comment by SameenAhnaf** [comment]
Are you asking for sharing external stream URLs? It's still not implemented. See: https://github.com/TeamNewPipe/NewPipe/issues/3448

**Comment by opusforlife2** [comment]
I think it's a development question, in which case it belongs in the NPE repo. @Jiang00 please clarify.
