### ISSUE TITLE
Nothing will load

### ISSUE THREAD

**Issue by TangledStardustxxx** [TeamNewPipe/NewPipe#8481]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

4.4+

### Steps to reproduce the bug

Open new pipe 
Nothing will load

### Expected behavior

When app is opened everything will load

### Actual behavior

When app is opened nothing will load

### Affected Android/Custom ROM version

Latest Android 

### Affected device model

Samsung a41

### Additional information

None

**Comment by TangledStardustxxx** [comment]
Still won't work

**Comment by tsiflimagas** [comment]
There's no 4.4+ version of Newpipe.

**Comment by TangledStardustxxx** [comment]
> There's no 4.4+ version of Newpipe.

I ment my phone version sorry

**Comment by tsiflimagas** [comment]
But the field is for your Newpipe version 🙄 And 4.4+ isn't a specific Android version anyway. "Latest Android" isn't very specific either, since you could be meaning an older Android version out of not being informed. Just try to be precise.
About your problem, do you use some VPN service?

**Comment by TangledStardustxxx** [comment]
> But the field is for your Newpipe version 🙄 And 4.4+ isn't a specific Android version anyway. "Latest Android" isn't very specific either, since you could be meaning an older Android version out of not being informed or whatever, we can't know. Just try to be precise. About your problem, do you use some VPN service?

Yes I use surfshark

**Comment by tsiflimagas** [comment]
Try disabling it then, and see if your issue gets fixed.

**Comment by TangledStardustxxx** [comment]
> Try disabling it then, and see if your issue gets fixed.

It worked thanks

**Comment by TangledStardustxxx** [comment]
This has been resolved just a vpn issue
