### ISSUE TITLE
Inactive Newpipe notification resists closing by swiping

### ISSUE THREAD

**Issue by cherti** [TeamNewPipe/NewPipe#8482]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

Steps to reproduce are not entirely clear, but I think 
1. Listen to a video, audio only, in the background. Newpipe will generate a notification.
2. Pause or let the video terminate, the notification remains.
3. Try to swipe this notification away to close it.

### Expected behavior

The Newpipe notification will vanish, just as it would if you'd press the 'x' on the notification.

### Actual behavior

Notification will stay, no matter how violent one swipes to the side. One has to explicitly press the 'x' button, which, however, only appears when Newpipe is the currently active (and largest notification), otherwise, this button is absent, requiring first to enlarge the notification to see it and then press it, which can be fiddly particularly with one hand.

### Additional information

It is unclear if this is a bug report or a feature request, but this behavior exists unanimously over all apps I am aware of, allowing to swipe away inactive notifications, including sound playing ones, which includes (but is probably not limited to) AntennaPod, VLC media player and Firefox.
Newpipe does very much feels broken here, typically requiring at least two actions, the second one having to be comparatively precise, instead of one swiping gesture, actively resisting to get out of the way, hence I opted for the bug report flavor.
Sound playing apps do resist being swiped away, but only while they are actively playing audio, not while they just remain because they used to play sound a while back.

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4335

**Comment by cherti** [comment]
Dang, somehow missed that when going through the issue tracker. Thanks for pointing that out!
