### ISSUE TITLE
When will the new update be available?

### ISSUE THREAD

**Issue by Legoks** [TeamNewPipe/NewPipe#8483]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

When will the new update be available?

**Comment by TiA4f8R** [comment]
When it will be. Please avoid asking this question on this type of project,.

See https://github.com/TeamNewPipe/NewPipe/issues/8126#issuecomment-1086690624 for more details. Thank you.
