### ISSUE TITLE
[Feature request] Ability to import/export settings

### ISSUE THREAD

**Issue by tmbgreaves** [TeamNewPipe/NewPipe#849]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=51556592)](https://www.bountysource.com/issues/51556592-feature-request-ability-to-import-export-settings)

Making a specific feature request for use on Bountysource[0], branching from a comment on #729 regarding ability to import/export settings. Original request from @Gitaroony was:

> Would it be possible to add an export/import feature for all settings, favs, history and watched?

+1 - I would very much like to see this added too. Thanks!

[0] Alas, it doesn't allow fine-grained bounties added to comments in issues, at least as far as I can see.

**Comment by theScrabi** [comment]
All right :)

**Comment by tmbgreaves** [comment]
Big thanks for all your work on this - works great for me on Lineage 14.1 (suruzan) and is a significant upgrade on my previous termux+youtube-dl solution :-) Thank you!

**Comment by theScrabi** [comment]
Thank you :)

**Comment by Somethingweirdhere** [comment]
I would give this a try if no one else is currently working on it :)

**Comment by Somethingweirdhere** [comment]
Alright, done. It took longer than expected because another function I was trying to use was broken, but now it all seems to work! 

@theScrabi How long does a dev branch need to get merged into master? I have tested it as well as I could, but I really don't want to screw up peoples exports/backups if I have done something wrong.

**Comment by theScrabi** [comment]
Currently its about a week or two. However did you test importing a zip that has no settings but only the database embodied?

**Comment by Somethingweirdhere** [comment]
Yeah, i added an if statement that checks if the settings file can be extracted from the zip.

**Comment by theScrabi** [comment]
ok

**Comment by theScrabi** [comment]
This got implemented by @Somethingweirdhere. :D You may pick up your reward.

**Comment by Somethingweirdhere** [comment]
@theScrabi Thanks, but how? It says the issue needs to be closed first.

**Comment by TobiGr** [comment]
If I recall correctly, you have to be member of the GitHub team to claim the bounty.

**Comment by theScrabi** [comment]
No, @Somethingweirdhere you just need to sign up at boutysource.

**Comment by Somethingweirdhere** [comment]
@theScrabi Alright, I am, but I still need to wait for it to be accepted by the backer. I will reinvest it in another feature when I get it :)

**Comment by theScrabi** [comment]
@tmbgreaves please remember to do that soon.

**Comment by tmbgreaves** [comment]
@Somethingweirdhere - thank you! :-)
@theScrabi - sorting it out now.

**Comment by tmbgreaves** [comment]
@Somethingweirdhere - I think that's accepted, give me a shout here if it hasn't gone through (first time I've used bountysource!).

**Comment by Somethingweirdhere** [comment]
Yes, it worked! Thank you :)

**Comment by tmbgreaves** [comment]
Great :-) Thanks for your work implementing this - as someone on a custom rom, who fairly often ends up rebuilding from scratch, and with a long list of subscriptions, this is a seriously useful thing to have.

**Comment by TaranQ** [comment]
Doesn't seem to work here OnePlus 6 Android 8.1.
Importing a freshly exported database clears all history playlists and subscriptions.
