### ISSUE TITLE
Howto open a hard to find playlist from a browser on FireStick to newpipe

### ISSUE THREAD

**Issue by sebma** [TeamNewPipe/NewPipe#8498]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hi, I have newpipe with the Downloader app on my FireStick.
I have playlists on my Youtube channel that I could not find using the newpipe search feature on FireStick even with the playlist filter selected.
I tried to use the Amazon Silk browser to browse my Youtube channel but then from there I cannot have Silk to open a playlist with NewPipe.
How can I do that ?

**Comment by opusforlife2** [comment]
Playlists should open just fine from a shared link from the browser. Try it from Firefox, so that we can rule out issues with Silk.
