### ISSUE TITLE
Dev Workflow

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#85]
Hello there, 

I've been to a Devops bootcamp this weekend, there i made a reverse session about continuous integration, because i thought we could use that for NP. But they told me to also care about using git the right way, and managing git projects right. Thats why i opened up this issue.
Since I'm new to that topic we should first elaborate and agree to a certain work-flow before applying it to the project. This work-flow might later on fail. If so no problem we then just need to try another one.

What we need to talk about  
- Managing branches.  
  For example some projects have version branches some use feature branches.
- Style/code guidelines  
  We should agree to a certain pattern of coding. So the project looks homogeneous, an one can understand the work of another one.
- etc  
  Well find out.

Also it's important to notice, we should not try to enable everything by tomorrow. This can be a longer process.

**Comment by theScrabi** [comment]
I still think about a first concept, with witch I'll come up with the next few days :)

**Comment by medavox** [comment]
* Managing branches
    - Personally I'd go with feature branches, a that's what I've been doing on my local machine (I have a "refactoring" branch). But I'm open.
    - I think we need some kind of stable/feature-freeze branch, which only has bugfixes applied to it, and its minor version incremented. That way, we can release minor updates without disturbing feature development, should there be an app-breaking bug, such as a YouTube website change which ruins the regex scraping rules. Just my opinion though.
* Code Style
    - I've been following the implicit guidelines of the existing code, which I've observed as:-
        * 4-space tabs
        * 100-column lines
        * opening braces on same line as statement (I think that's uncoddled?)
        * catch blocks begin on closing brace line of try statement

        * There are probably lots of other things worth thinking about, such as where instance fields should go (top of class declaration? or bottom?), and where to catch Exceptions in general (in the throwing scope, or further up? currently in the throwing scope, I think)

It'd be worth looking at other code style guidelines ([ for example](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style)), and seeing

**Comment by theScrabi** [comment]
@medavox 
* About Merging branches: I totally agree to that.
* About Code Style: agreed with following additions:  
 * instance fields to the top, as well as declaration/definition
 * throw catch in the same scope: I think that depends on the error 
Errors occurring inside a Service class should be caught by the other side of the interface.

**Comment by MarvAmBass** [comment]
hey there I'm new to this project

so for the code style, why don't you just use the official oracle
Code Conventions for the Java TM Programming Language
http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html
or the 
Google Java Style
https://google.github.io/styleguide/javaguide.html

it has the benefit of being well integrated into IDE Code Formatters/Tidy Plugins and Checkstyle
and it's quite common in the java world

and another thing about the dev workflow

where do we discuss the software design especially for new features
I don't think issues will be a good idea for this - it could get pretty crowded here, especially with real issues and feature requests

maybe we could also split up some work

I don't want to waste time implementing some features which later won't merged because they won't fit with the ideas you have in mind. Maybe we could use the wiki for that.

**Comment by theScrabi** [comment]
Hm. I never used the wiki of github. But I also see that that issues are not the best place for discussions about implementations.

**Comment by medavox** [comment]
I also think using the wiki is a good idea. I'm away from my Dev machine this weekend, so i can't help set it up.

But good idea!

**Comment by theScrabi** [comment]
ok :)

**Comment by chschtsch** [comment]
Guys, what do you think about creating Slack conf for NewPipe? It's useful when you want to share your opinion and ideas with many people. Or ask for their thoughts on topic. Or you can make polls.

Chat-like services fit better for this, I think. Because you ask one time and make a summary of what people think. After that you don't need all these message logs. But in GitHub this may get messy and result in hundreds of comments. (Not everyone would like to read them all to be informed)

**Comment by theScrabi** [comment]
Yes I guess that might be useful :)

**Comment by theScrabi** [comment]
There are huge code changes comming up the next days. I've worked my self all the way through the lint errors to (hopefully) get a cleaner code. I had to modify almost every file of the project. The changes are so big that I've opened a feature branch witch I will upload the next few days. So if you like you can review it then. 

What would you say if we try to take lint more serious in the future? Some colleges are using it, and they say it's useful.

**Comment by medavox** [comment]
@theScrabi Awesome :) I look forward to seeing these changes.
As far as I know, I'm already using the automatic linter in Android Studio? Unless you mean something else...

@chschtsch I've never used Slack before (first thing that popped into my mind was the ancient Linux distro), but it definitely looks like it could be useful for keeping track of discussion.

See, this is why I wanted to get involved in a collaborative dev project: to learn about skills & tools related to dev from other people :)

**Comment by theScrabi** [comment]
@medavox I'm concerned that these changes won’t be that great. I guess they will be rather annoying, because I promise our code will collide in some point :/

We are using slack for our "Freifunk" project. The only bad thing about it though is that 1. It is a non free service, and therefore centralized. 2. The Android App to Slack is even not free.
But I think for now it will do.

**Comment by medavox** [comment]
@theScrabi as long as they don't break existing functionality, I'm sure they'll be fine. As I said in the [refactor thread](https://github.com/theScrabi/NewPipe/pull/100#issuecomment-160006807), pretty much all my current work is on a brand new class, BackgroundPlayer. So you can't collide with what you don't have yet ;)

Regarding Slack: yes it is non-free, which also perturbs me slightly. But I'm happy to go with it for now, seeing as it does solve a problem we have right now.

**Comment by theScrabi** [comment]
right :)

**Comment by chschtsch** [comment]
I just deployed inviter app for slack: http://invite.chschtsch.ml/
Used [slack-invite-automation](https://github.com/outsideris/slack-invite-automation) by @outsideris

**Comment by theScrabi** [comment]
ok I've added the link to the README.

**Comment by theScrabi** [comment]
You can find information about the workflow over at the [contributing file](https://github.com/TeamNewPipe/NewPipe/blob/master/.github/CONTRIBUTING.md).
