### ISSUE TITLE
Discoverability of the subscription import/export menu

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#8504]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The "Nothing here but crickets" in the Subscriptions fragment should be replaced with a "You can import and export subscriptions from the three-dot menu", or something similar, in order to have better discoverability. Note that this means that that message will show up only when there are no subscriptions, but I think that's fine. For reference, see #7458.

**Comment by NewNewPipe** [comment]
Will it be possible to import the subscription list locally from a file?

**Comment by Stypox** [comment]
That's already possible

**Comment by NewNewPipe** [comment]
Thanks, it iż indeed three and working. I was confused by the message about high data usage when importing the file, hence I thought the file would be downloader grom the cloud or YT and bot locally. But I confirmed the message and the export file loaded correctly. I have my subscription list tranferred. Thanks.

**Comment by Poslovitch** [comment]
I'll work on it this week-end. Seems like an easy task for onboarding.
