### ISSUE TITLE
Add a pop up menu when long clicking on a video in a list (search list, ...)

### ISSUE THREAD

**Issue by Massedil** [TeamNewPipe/NewPipe#851]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

---

Add a pop up menu when long clicking on a video in a list (search list, ...) with those options :
- Play video immediately
- Play audio immediately
- Play video next
- Play audio next
- Add video into the play queue
- Add audio into the play queue

It will permit to do not open the video view and save time.

**Comment by theScrabi** [comment]
>  - Play video immediately
>  - Play audio immediately

We disused why we don't want this two options. They would open a second pathway to playing videos, and I think this is not good in terms of UI consistency.

>  - Play video next
>  - Play audio next

Isn't this the same as the next two options?

>  - Add video into the play queue
> - Add audio into the play queue

Will be coming in the next version.

**Comment by Massedil** [comment]
> Isn't this the same as the next two options?

No, here is the logic : 

1. song A (currently playing)
2. ___Play audio next___
3. song B
4. song C
5. song D
6. ___Add audio into the play queue___

I don't know how to well name those menu options. 

[Vanilla Music Player for Android](https://github.com/vanilla-music/vanilla) has the two options and it's useful.
