### ISSUE TITLE
Does not continue playback after audio from other program is played (Gmaps)  

### ISSUE THREAD

**Issue by Synthacon** [TeamNewPipe/NewPipe#8510]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1.play video
2.use google maps navigation during the playback
3.after gmaps play navigation audio video playback does not continue.
4.have to press "play" after every audio from external program.

### Expected behavior

After gmaps play navigation audio video playback does not continue. Have to press "play" after every audio from external program.

### Actual behavior

Same as above.

### Affected Android/Custom ROM version

Android 11

### Affected device model

Oneplus 8Pro

**Comment by opusforlife2** [comment]
Did you explore the app's settings menus? There is a "Resume playing" toggle.
