### ISSUE TITLE
Make refreshing load screen less intrusive

### ISSUE THREAD

**Issue by Donskiye** [TeamNewPipe/NewPipe#8511]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

To change the refresh loading screen that currently takes up the entire screen in favour of something less intrusive. 
I have no specific request on how it should look, just that it should be less intrusive. The following are some ideas to illustrate alternative ways:
- Making the current white loading background transparent. Possibly also moving the left over bar and number count down or up,
- Making the current 'pull-down to refresh' icon spin to indicate loading (like on the Youtube app),
- Making a small loading bar that sits at the top or bottom of the video list,
- Making a small loading icon that sits at the top or bottom of the video list.

### Why do you want this feature?

The reason I want this feature is that the current refresh loading screen is very intrusive. It is impossible to do anything in your subscription tab while it is loading. You basically have to refresh and wait. I have a lot of subscriptions 300+ (and a budget phone if that's related). It takes around 15 seconds to scan all my subscriptions and load the videos. This is time that I could also be looking at my subscription tab for a video to watch, or even just mindlessly scrolling.

**Comment by litetex** [comment]
Closed in favor of https://github.com/TeamNewPipe/NewPipe/issues/8525
