### ISSUE TITLE
App keeps crashing when you play a song with screen off

### ISSUE THREAD

**Issue by shnoah641** [TeamNewPipe/NewPipe#8517]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Play a song in background 
2. Then turn off screen while playing in background 
3. Music will stop playing aftee so long 

### Affected Android/Custom ROM version

Android 11

### Affected device model

Motorola one 5G ace

**Comment by lawson85** [comment]
I don't see any issues. Try to follow steps at dontkillmyapp.com

**Comment by litetex** [comment]
You may checkout https://newpipe.net/FAQ/tutorials/bugs-huawei-background-player-workaround/.

If the problem persists please add a stacktrace of the crash.

**Comment by shnoah641** [comment]
Still having issues even with the website instructions you gave me

**Comment by opusforlife2** [comment]
> If the problem persists please add a stacktrace of the crash.

^

**Comment by shnoah641** [comment]
Issue has resolved itself sorry for the late reply thank you so much for helping me
