### ISSUE TITLE
The french translation of "Pop-up" is not well displayed

### ISSUE THREAD

**Issue by Massedil** [TeamNewPipe/NewPipe#852]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

---

May be call it "Pop-up", it's used in french ?

![screenshot_20171116-195005](https://user-images.githubusercontent.com/20357783/32910093-3d4fd318-cb00-11e7-9075-00b5be10ee93.png)

**Comment by TobiGr** [comment]
Thank you for that report @Massedil. We manage our translation with Weblate. You can correct this translation along with other strings containing "popup" [here](https://hosted.weblate.org/translate/newpipe/strings/fr/?q=popup&search=ftx&source=1&target=1&type=all&offset=0) to get the credit for it.

**Comment by Massedil** [comment]
I think it's the "controls_popup_title" string.

I don't have an account on Weblate. You can do the change and take the credit, no problem ! ;)

And may be if you want to keep "Lecture flottante" (which is "good french"), it's possible just increase the height of the control so "flottante" will appear.

**Comment by joedf** [comment]
`popup` should be fine... otherwise... `fenêtre contextuelle` ?

**Comment by Massedil** [comment]
`fenêtre contextuelle` will be on 2 lines, like the current `Lecture flottante`, same problem. 

But I agree that `fenêtre contextuelle` is better understandable in French than `Lecture flottante`.

**Comment by TobiGr** [comment]
@Massedil You can login login to Weblate with your GitHub account. If people understand `popup` without problems, I'd rather take it instead of two lines, because there are problems with too long words in the channel view as well.

**Comment by Massedil** [comment]
I think it's done. Can you confirm it ?

**Comment by TobiGr** [comment]
Yes. Thank you. Can you also please change the other Strings which contain `Lecture flottante` so there is a consistent translation of the English `popup`? Otherwise people are looking for `Pop-up` in the settings but only find `Lecture flottante`.

**Comment by Massedil** [comment]
Ok ! I think it's done. Can you confirm it ?

**Comment by TobiGr** [comment]
Thank you @Massedil. Your changes will be included in the next release. We can close this issue now.
