### ISSUE TITLE
[FR] Default download with audio

### ISSUE THREAD

**Issue by Zykino** [TeamNewPipe/NewPipe#853]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

When I download a video the default option is usually : 1080p60 (no sound)
Is it possible to have an option to default to "highest resolution up to (1080/720/...) **with sound**" ?
Just saw that in the settings I can change the video and audio format... maybe have a bit of explanation that WebM doesn't have all audio but MP4 have (or I don't know what the truth is with Youtube).

I also see a "Number of threads" in the download popup.
With my 4G/WIFI what is the best choice?
When I'm on a slow H+ network (~20kB/s) what should I prefer?
Is it really an option an end user should see? I f I had a cursor "my internet is fast/slow, reliable/unreliable" and let NewPipe do the translation I would be happy enough with it!

I know I posted 2 issues in the same one but they are both "download popup UX" related so I feel the are good t think about together.

**Comment by theScrabi** [comment]
> highest resolution up to (1080/720/...) with sound

No. The problem is that every stream higher than 1080p or with 60Hz is delivered without audio. So we have to download an audio only stream separately to the video stream, and mix both together. For playing a video this is not a problem, but for downloading one we'd have to re encode the file, and therefore we needed ffmpeg.

Over at another issue I said that I'm not going to put ffmpeg into NewPipe, if we want re encoding we should create a seperate app that embeds ffmpeg and which can be called by NewPipe.

**Comment by Zykino** [comment]
I understand your concern about adding ffmpeg.
I understand that saving the video and the sound isn't a good option either for most users.

What I want is that when I click to download a video, the selected flux is "best quality with sound up to 1080p60" instead of "be 1080p60 even if there is no sound"

I'm ok with downloading a 720p version of the same video as long as the audio is there. But each time I download I have to select this flux.

So either a default to "best with sound" or a "keep last download setting" is nice for me (the 2nd may be less user friendly if Youtube change the way they work or if the user use to download 4k but sometime also download 360p).

**Comment by trmdi** [comment]
@theScrabi 
So can we download both the video and audio, then we could still use Newpipe to play them offline ?

**Comment by theScrabi** [comment]
That could be done, but someone had to implement a the play offline part.

**Comment by Zykino** [comment]
So no one else just click on:
Download
Select the resolution of the video    < Both this steps could be skipped with a default value
select 720p                                     < or with a parameter with the preferred resolution
Start the download

**Comment by gkeegan** [comment]
I actually would like that to be implemented, so long as there is an option to set the default to any quality the user selects in settings.

**Comment by opusforlife2** [comment]
@Stypox This issue has been solved for several versions and can be closed.
