### ISSUE TITLE
Subtitles already supported in another open project ( SmartTubeNext )

### ISSUE THREAD

**Issue by jeremyzed6250** [TeamNewPipe/NewPipe#8532]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

This is a great little app, unfortunately BlueStacks is really bad at emulating the app in android VM. It's got no issues with NewPipe.

https://github.com/yuliskov/SmartTubeNext

### Why do you want this feature?

Sometimes Audio isn't appropriate..

### Additional information

It's open and free, maybe with authors permission, the bits needed to implement subtitles could be used.

**Comment by SameenAhnaf** [comment]
Did you mean transcript? Please keep the discussion in https://github.com/TeamNewPipe/NewPipe/issues/7375.

Subtitles are already supported in Newpipe. Go to secondary panel and choose `No captions` to see secondary panel. If `No captions` is not shown, then no caption is available. (I know, it's a weird implemented. https://github.com/TeamNewPipe/NewPipe/issues/6339 asks to show the state clearly)

![IMG_20220622_093124](https://user-images.githubusercontent.com/79245641/174937831-b4c4fa82-3781-4327-be74-b79adf7e6ce5.jpg)
