### ISSUE TITLE
slide title feature

### ISSUE THREAD

**Issue by BillyAppetie** [TeamNewPipe/NewPipe#8535]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [ ] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [ ] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Feature Suggestion: Be able to slide video title when long pressed at video. Maybe it similiar if you slide long url on url bar in your browser.

### Why do you want this feature?

When there is video with long title, i can't read the whole title so i long pressed that video to see complete title but the app move the title slowly so i want to be able to slide it to read quickly.

### Additional information

sorry if my english is bad

**Comment by SameenAhnaf** [comment]
Rejected as mentioned in https://github.com/TeamNewPipe/NewPipe/issues/6187#issuecomment-904445140
