### ISSUE TITLE
When video goes full screen it will not go back to vertical mode.

### ISSUE THREAD

**Issue by elfusfarkus** [TeamNewPipe/NewPipe#8538]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Turn off rotation on your android (and remain in vertical view)
2. Launch New Pipe, launch any video 
3. When video is running go to full screen mode
4. The video will go to full screen (horizontal mode) but when you try to go back to normal view, New Pipe interface will remain in horizontal mode even if the video is not full screen. (Unless you have auto-rotate enabled in your android.

### Expected behavior

I expect that the New Pipe interface and menu go back to vertical mode after i turn off "full screen mode". 

### Actual behavior

New Pipe Interface remains rotated to horizontal mode unless i turn on auto-rotate feature of android.

### Affected Android/Custom ROM version

Android 9

### Affected device model

Galaxy Note 8

**Comment by mhmdanas** [comment]
It seems to be what @SameenAhnaf speaks of. If @SameenAhnaf's suggestion doesn't fix your issue, please make a comment. Also, note that 0.23.0 is the latest NewPipe version, not 0.22.2. I encourage you to update NewPipe.

**Comment by elfusfarkus** [comment]
It works!!! Thanks so much.
------- Original Message -------
