### ISSUE TITLE
Downloaded audio files retain the .bin file extension

### ISSUE THREAD

**Issue by wquindt** [TeamNewPipe/NewPipe#8539]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. go to subscriptions -> channel groups -> all
2. select video 
3. select download -> audio -> ok

### Expected behavior

Downloaded audio files get the .m4a file extension

### Actual behavior

Downloaded audio files retain the .m4a.bin file extension

**Comment by mhmdanas** [comment]
Cannot reproduce this. Please give your device model and Android/Custom ROM version. A screen recording would also be highly helpful.
