### ISSUE TITLE
Opening YouTube links keeps loading forever

### ISSUE THREAD

**Issue by jomo** [TeamNewPipe/NewPipe#854]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

----

- Searching and playing videos from within NewPipe works as expected
- Opening a {www,m}.youtube.com link with NewPipe just keeps "loading" forever
- No video information or thumbnail is shown (see [screenshot](https://i.imgur.com/9fQDpb8.png)). Same effect in popup mode.
- Opening YouTube links in the browser works just fine

Here's the logcat output:

```logcat
  972  8513 I PackageManager: Setting last chosen activity org.schabi.newpipe/.RouterActivity for user 0:
  972  8513 I PackageManager:   Action: "android.intent.action.VIEW"
  972  8513 I PackageManager:   Category: "android.intent.category.BROWSABLE"
  972  8513 I PackageManager:   Category: "android.intent.category.DEFAULT"
  972  8513 I PackageManager:   Scheme: "https"
  972  8513 I PackageManager:   Authority: "www.youtube.com": -1
  972  8513 I PackageManager:   Path: "PatternMatcher{PREFIX: /watch}"
  972  8513 I PackageManager:   AutoVerify=false
  972  5659 I ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://www.youtube.com/... flg=0x3000000 cmp=org.schabi.newpipe/.RouterActivity} from uid 10128 on display 0
  972  6868 I ActivityManager: START u0 {flg=0x10008000 cmp=org.schabi.newpipe/.MainActivity (has extras)} from uid 10159 on display 0
23048 23048 D VideoDetailFragment@16b2468: pushToStack() wasn't equal
  972   993 I ActivityManager: Displayed org.schabi.newpipe/.MainActivity: +291ms (total +398ms)
```

The only log from NewPipe itself is `pushToStack() wasn't equal`, coming from here:

https://github.com/TeamNewPipe/NewPipe/blob/c485e7e167971eb82b8d5b10f5a67b565926eab9/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L659-L664

This has been an issue for several months, spanning multiple versions of NewPipe.  
Reinstalling does not help, either.

**Comment by theScrabi** [comment]
How do you open the links? Via share menu or do you paste the link into the search bar?

**Comment by jomo** [comment]
I was using the share menu but pasting into the search bar seems to do the same thing.

**Comment by TobiGr** [comment]
@jomo Does this still haben or can we close this ticket?

**Comment by reaysawa** [comment]
@TobiGr it still happens to me on 0.14.2

Opening with ”Share with -> NewPipe” or pasting the URL makes the video load forever. It seems like channel's videos aren't working either. I can't watxh the ones on this channel:

https://www.youtube.com/channel/UCHn3px69jb1bx5EOWyCIgFg

Opens fine through the browsers.

**Comment by Stypox** [comment]
Is this still happening? For me it works correctly.

**Comment by reaysawa** [comment]
@Stypox its been quite a few months since I posted here so I don't remember. Sorry! But IIRC later I found out that the video would load in the end, it just took a **very** long time to resolve (like one minute or something).

However, I tried to use the "Share -> Video Player" route a few times currently and didn't have this problem. Consider it fixed from my side. : ]

**Comment by Stypox** [comment]
Yeah, I am closing this, since the last not-working update was the 18/11/2017
