### ISSUE TITLE
Rotation race condition? Wrong scaling after turn into landscape orientation.

### ISSUE THREAD

**Issue by Scyten** [TeamNewPipe/NewPipe#8552]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Play a video in portrait orientation.
2. Turn the phone to get landscape orientation.

### Expected behavior

Always show video correctly scaled, when turned into landscape fullscreen ui. 

### Actual behavior

NewPipe goes to fullscreen video playback ui. The video it self rotates but in 50% of the tries (random, not every second time) it does not scale (still same size as in portrait before)
-> only a quarter of the screen is filled by the video

### Screenshots/Screen recordings

![Screenshot_20220625-223903](https://user-images.githubusercontent.com/16176275/175790264-8b54ba66-55ef-4496-842d-f7b329b3f60d.png)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 3 XL

### Additional information

The bug is not new it happens since some versions. Maybe since the Android 12 update.
The randomness of this bug let me think of a race condition while rotating.

When pausing the video, turn into landscape and press play it scales correctly every time.

**Comment by mhmdanas** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7262.
