### ISSUE TITLE
"Background playing by default" setting is broken

### ISSUE THREAD

**Issue by JPGuillemin** [TeamNewPipe/NewPipe#8555]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1 go to settings -> Video&Audio -> Behaviour / Prefered Playing Method
2 Select Background Playing in the list 
3 Go back to the medias screen
4 Launch a song
5 The video is still played , not just audio as expected : you have to manually press the "play in background" button to get audio only

(Above translated menu titles from french interface.)

### Expected behavior

Selecting background playing as default behavior should play all songs without video 

### Actual behavior

You have to manually press "play in background" button even if you have configured newpipe to play in background by default 

### Affected Android/Custom ROM version

Android 12 IMUI13

### Affected device model

Xiaomi 12

**Comment by SameenAhnaf** [comment]
Actually, that's not the purpose of `Preferred 'Open' Action`. This setting is supposed to work for supported shared links only, not for videos inside the app. 


https://user-images.githubusercontent.com/79245641/175889705-76b2ae68-6cbd-4e19-ad5f-65cc22a4c68f.mp4

**Comment by opusforlife2** [comment]
#2610 covers what you want, but it's much broader. You could open a more focused issue for your specific request.

**Comment by JPGuillemin** [comment]
> #2610 covers what you want, but it's much broader. You could open a more focused issue for your specific request.

Great !! Thanks

**Comment by litetex** [comment]
I guess we can close this then
