### ISSUE TITLE
Is there any way to use NewPipe on a Smart TV?

### ISSUE THREAD

**Issue by tedomedo** [TeamNewPipe/NewPipe#8556]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Thanks to NewPipe and Ublock Origin, i don't see youtube ads on android and pc. Now next device with youtube is Samsung smart tv. How to remove ads there? I saw somewhere that we could block sites where ads come in router's firewall or parent control. Didn't try yet. 
Is NewPipe available on smrt tv ? Or another application showing youtube videos without ads?

**Comment by mhmdanas** [comment]
If the smart TV runs Android, it probably can run NewPipe too. If not, you can also try using Invidious or Piped on the TV's web browser, though I have no idea how ergonomic that would be with the navigation controls of a TV's remote.

> How to remove ads there? I saw somewhere that we could block sites where ads come in router's firewall or parent control. Didn't try yet.

I know of https://pi-hole.net/, but there are probably other options too.

**Comment by markusgerber76** [comment]
You probably need https://github.com/yuliskov/SmartTubeNext

**Comment by peat80** [comment]
I think Samsung uses Tizen as Operating System for their Smart TVs.
So NewPipe and also SmartTubeNext will not work there.

**Comment by tedomedo** [comment]
I know, Samsung smart tv isn't android tv. That's why i ask that let NewPipe create web site, unless Piped is already its site.

**Comment by mhmdanas** [comment]
You didn't ask for any website for NewPipe (something which we have no plans of creating). Also, to be clear, Piped isn't an official project of Team NewPipe.

Since your question was answered (no, you cannot run NewPipe on Tizen), I'm closing this issue.
