### ISSUE TITLE
An option to choose YouTube's whole videos content source

### ISSUE THREAD

**Issue by lookerloo** [TeamNewPipe/NewPipe#8568]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

An option to choose whole youtube content from privacy friendly frontent such as piped, invidious etc.

Place the option in settings under content category

1. Piped
2. Invidious
3. YouTube

### Why do you want this feature?

If we choose whole youtube content from piped we can hide our ip address from google, and improves video loading time, and also we can bypass youtube content restriction in some countries.

**Comment by opusforlife2** [comment]
There are already individual issues open for these front-ends, so I'm closing this as duplicate.
