### ISSUE TITLE
Download queue

### ISSUE THREAD

**Issue by gh4chris** [TeamNewPipe/NewPipe#8577]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Select multiple items at once to add to the queue

### Why do you want this feature?

It's an in and out just to build up queues for replay or download

**Comment by mhmdanas** [comment]
> Select multiple items at once to add to the queue

The download queue or play queue?

**Comment by gh4chris** [comment]
Download queue preferable. What gives me another headache is the missing ability to sort the hit lists after searches by various criteria like length, views etc.
