### ISSUE TITLE
Empty playlist are not showed in playlist bookmarks when are more than one empty

### ISSUE THREAD

**Issue by LukasThyWalls** [TeamNewPipe/NewPipe#8582]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Have multiple playlist. (In my case, i have four: "**- PODCAST -**" (Local), "**- VER MÁS TARDE -**" (_Watch Later_, Local), "**Música**" (_Music_, Local), and other user playlist (Subscribed Playlist). First one (**- PODCAST -**) have some videos, second one (**- VER MÁS TARDE -**) only one video, third one (**Música**), empty.

2.  I you go to any video and try to add to a playlist, it shows three options, as the local playlist are. That's fine.

3. If you remove the video from the playlist **- VER MÁS TARDE -** (_Watch Later_), it still shows in the playlist bookmarks, the **Música** (_Music_) playlist dissapears.

4. Then, if you go to any video to add to playlist, it only shows two options **- PODCAST -**, **- VER MÁS TARDE -** (_Watch Later_), and the **Música** (_Music_) playlist is gone.

5. HOWEVER, if you add a video to the playlist **- VER MÁS TARDE -** (_Watch Later_), the **Música** (_Music_) playlist appears again everywhere.

### Expected behavior

The empty playlist should be there always and not disappears, unless if it's decided that empty playlist should be removed altogether with its last video, but then the playlist should not come back (I wouldn't prefer that, but at least make sense).

### Actual behavior

Some empty playlists appear and disappear in specific circumstances with no sense, at least in this case, when other playlist is empty or not. 

### Screenshots/Screen recordings

1. Initial playlists:
<img alt="NewPipe_2EmptyPlaylistIssue_1-AllPlaylist" src="https://user-images.githubusercontent.com/1467366/177515195-24628f6a-1277-447a-b64b-cceb621d788c.jpg" height=600 />

2. Initial add playlist options:
<img alt="NewPipe_2EmptyPlaylistIssue_2-AllPlaylistAdd" src="https://user-images.githubusercontent.com/1467366/177515401-36cde596-3849-4bd2-be51-9a4beed0cfd0.jpg" height=600 />

3. After removing video from **- VER MÁS TARDE -** (_Watch Later_):
<img alt="NewPipe_2EmptyPlaylistIssue_3-NoPlaylist" src="https://user-images.githubusercontent.com/1467366/177515594-83f7f914-db85-47e3-b86e-8e98f374b289.jpg" height=600 />

4. Add playlist options with **- VER MÁS TARDE -** (_Watch Later_) empty:
<img alt="NewPipe_2EmptyPlaylistIssue_4-NoPlaylistAdd" src="https://user-images.githubusercontent.com/1467366/177515822-2fabcbc7-4109-496c-a5f1-03f28bf860e4.jpg" height=600 />

5. After adding a video in **- VER MÁS TARDE -** (_Watch Later_), the screenshot is the same as (1) and (2), **Música** (_Music_) playlist appears again everywhere. 

### Affected Android/Custom ROM version

Android 10 (MIUI 12.0.10/QKQ1.190828.002)

### Affected device model

Xiaomi Mi 9 Lite

### Additional information

I'm aware than having empty playlist only can be done at the moment creating them in Add playlist options and later removing the videos, but the behavior should make sense: If you can have empty playlist, Newpipe should show all empty playlist, and if you can't have empty playlist, after removing the last video the playlist should be gone and don't come back.
I would prefer have empty playlist available (and i think it's what Newpipe devs want) but something is happening there than prevents show some empty playlist in specific circumstances.

Thanks!

**Comment by Jared234** [comment]
While I was working on some other issues, I also found this bug.
I can work on it and will create a PR in the next few days.

**Comment by PVTejas** [comment]
This bug has reappeared in v0.25.2

**Comment by LukasThyWalls** [comment]
Yes, i confirmed that. The 4º screenshot in the OP is still happening in v0.25.2.

What i don't know is someone can open this issue again (i can't), or we need to create a new issue.

**Comment by PVTejas** [comment]
I'm thinking of waiting 24h for a dev reply. If there's nothing, I'll create a new issue.
