### ISSUE TITLE
Add a Sponsor Block Option

### ISSUE THREAD

**Issue by Mdhakkim7** [TeamNewPipe/NewPipe#8586]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

It will save our time by skipping promotions and unwanted section in the videos

### Why do you want this feature?

It will save our time by skipping promotions and unwanted section in the videos

### Additional information

It will save our time by skipping promotions and unwanted section in the videos

**Comment by AudricV** [comment]
Please read https://github.com/TeamNewPipe/NewPipe/pull/3205#issuecomment-732396178.
