### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by BienAtGitHub** [TeamNewPipe/NewPipe#8593]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

This app, https://play.google.com/store/apps/details?id=vn.com.giangdev.jazzvanced, is currently using NewPipe's code without any permissions/credits.
He basically built NewPipe from source, with Google's Material You theme, and changed app name **COMPLETELY**.
And, **there's no source code shared to public.**
(And seriously, he released it on the PLAY STORE, so he is also violating Play Store's ToS as well!)
There's also no mention of NewPipe in the app's description.
Please check it out.

**Comment by SameenAhnaf** [comment]
Please keep this discussion in https://github.com/TeamNewPipe/NewPipe/issues/539

**Comment by TobiGr** [comment]
The app is developed by someone called [Phan Ba Giang](https://play.google.com/store/apps/dev?id=7342662140510541996).
Following the Developer link on GPlay, I get to https://giangphandev.blogspot.com/
They link the GitHub profile of @giangphan11  in their navbar right at the top who has also linked the website mentioned above in their account bio. Maybe we can ask them directly to publish the source code :)

**Comment by mhmdanas** [comment]
Closing in favor of #539.
