### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by shahariarnavil** [TeamNewPipe/NewPipe#8597]
{"user_action":"play stream","request":"Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=r4j_F2NkaKw","content_language":"en-","content_country":"US","app_language":"en","service":"YouTube","package":"org.schabi.newpipe","version":"0.23.1","os":"Linux Android 11 - 30","time":"2022-07-10 06:57","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:236)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: Read timed out\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)\n\tat com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:923)\nCaused by: java.net.SocketTimeoutException: Read timed out\n\tat java.net.SocketInputStream.socketRead0(Native Method)\n\tat java.net.SocketInputStream.socketRead(SocketInputStream.java:119)\n\tat java.net.SocketInputStream.read(SocketInputStream.java:176)\n\tat java.net.SocketInputStream.read(SocketInputStream.java:144)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)\n\tat com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)\n\tat com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)\n\tat com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)\n\tat com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)\n\tat com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)\n\tat com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)\n\tat com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)\n\tat com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)\n\tat com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)\n\tat com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)\n\tat com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)\n\tat com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)\n\t... 10 more\n"],"user_comment":""}

**Comment by litetex** [comment]
Please open [a new issue](https://github.com/TeamNewPipe/NewPipe/issues/new/choose) with the corresponding template.

Also 

> ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT

You are offline.

**Comment by AudricV** [comment]
> > ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT
>
> You are offline.

Maybe not, as this issue seems to also happen to users with a working connection (already reported in https://github.com/TeamNewPipe/NewPipe/issues/8548#issuecomment-1166992710 with an active connection). I would say network issues or volountary non-response of YouTube (as `YoutubeHttpDataSource` sends an empty body in a POST requests for stream URLs of mobile clients, which is not the case on mobile clients (at least the Android one which send a Protobuf body in `videoplayback` requests)).

I will open a PR which will include removal of this behavior in the coming days.

Anyway, duplicate of #8579. Please search (better, with different keywords?) for duplicates and use our issue templates the next time you want to open an issue. Thank you.
