### ISSUE TITLE
[discussion] I'm working on playlist/queue downloading

### ISSUE THREAD

**Issue by dcoder-mm** [TeamNewPipe/NewPipe#860]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Hello guys,

I'm trying to implement batch-downloading feature to NewPipe. It will be useful to download playlist with music or some video series. 

Now it's done, i think, by 30%:
- [x] "download" button on playlist view
- [x] separate dialog for downloading playlist
- [ ] separate mission_item for playlist (one item for whole list in "downloads" view, not individual for every single video\audio) with downloaded items counter
- [ ] changes in downloader for making it possible to download list of videos one-by-one

New download dialog has option to create subfolder (in /Audio or /Video directory, depending on selection) to store all downloaded playlist items. 

Format and quality can't be defined exactly (because some videos may have only low quality, etc), so i decided to add "Preferred quality" option. Now it's just a list with typical quality options (1080p60, 1080p, 720p, etc down to 144p) and format selection (m4a/WebM) for audio. 

Downloader will try to download video in quality that equal or lower than selected. Ex. if 720p hasn't sound, 480p (but not 1080p) will be selected. For audio i think to select best quality with chosen format.
(i can't figure out how to do quality selection in a better way, so any suggestions are welcomed)

Here is screenshot of "playlist download" dialog with new options
<img src="https://user-images.githubusercontent.com/2083052/32988024-b39993da-cd0b-11e7-86dd-daf1c6a29aef.png" width="250">

P.S. I'm not very skillfull in android programming. Actually this is my first attempt to add a feature to existing project. (ofcourse, i'm following codestyle and etc while making any changes)

P.P.S. And my englist isn't best, so don't be angry at mistakes :)

**Comment by wb9688** [comment]
1. How will you handle video-only streams?
2. In the dialog it should be 'preferred', not 'preffered'.

**Comment by dcoder-mm** [comment]
@wb9688 
1. I think in this case downloader should switch to stream with closest lower qualty. For example if user chose 720p and in some videos 720p is video-only, 480p will be selected (if it has audio)
2. fixed

**Comment by dcoder-mm** [comment]
@theScrabi i'm planning to add download button to queue view (background/popup/main). So user can enqueue videos, delete or append some and then download entire queue

**Comment by johnjacobkenny** [comment]
Would it make sense to provide check boxes (maybe on long press of any video in the list), and have the options BACKGROUND, ALL, POPUP, DOWNLOAD use this filtered list of videos?

**Comment by 2SI3NX** [comment]
Dude, ive tried your playlists option and it rocks! :1st_place_medal: 
Some feedback from my end:

1.  When putting audio in the queue, it will collect the list until you start playing one of the audio's while you're busy adding. For eg. i find vid1, add it to the queue, find vid2, add it to the queue, find vid3 and start playing it before adding it to the queue - this now causes the playlist to CLEAR OUT and have to start from scratch.

2. Make feature to SAVE playlists with custom playlist name. But dont auto-download. only if the user wants to play them on demand only.

3. Create playlist button in the frontend to easily jump to playlists.

4. The background audio player used to be able to foward or rewind by pressing the << >> buttons, now it doesnt anymore. Please fix.

Thanks in advance!

**Comment by theScrabi** [comment]
Still on the work?

**Comment by ProNoob135** [comment]
How do I install this?

**Comment by theScrabi** [comment]
I have the bad feeling this got abandoned :/ 
@dcoder-mm how are you doing?

**Comment by FaizKhan5** [comment]
Close this.
