### ISSUE TITLE
Add option to display channel groups as list instead of grid

### ISSUE THREAD

**Issue by pc00per** [TeamNewPipe/NewPipe#8605]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

A list form of channel group instead of Grid form

### Why do you want this feature?

Some users have long lengthy list of channel groups, which also make them hard to sort & also scrolling them from left to right, seems unintuitive.

### Additional information

And I personally don't like manual channel group sorting & Instead prefer Alphanumeric order (might need to open another issue for this)

And also, an another problem of Grid Layout is that it masks bigger Group titles & show only first 8 of their characters on the small dpi displays.

**Comment by plasticanu** [comment]
Hi, we are an assignment group (6 people) studying computer science at the Australian National University. We would like to work on this issue, and we have 19 days left to write code and open a pull request. Can you assign this issue to us?

**Comment by mhmdanas** [comment]
@plasticanu somebody will assign you to the issue eventually, but you don't have to wait for that to happen before you actually start working on it.

**Comment by opusforlife2** [comment]
@plasticanu You've offered to work on a bunch of issues. Do you plan to work on any one, a few, or all of them? Please clarify so that I can start assigning.

**Comment by plasticanu** [comment]
> 

Hi, sorry for the late reply. I am going to work with 2 people from my team. So we'll be a 3 people team.

**Comment by cernunnos1710** [comment]
Hello, I would like to also worked on this issue with @plasticanu.

**Comment by cernunnos1710** [comment]
Hi! For the list layout, Is it alright if I add a toggle to change it into a vertical version of the card layout instead of completely overhauling into a list view?

**Comment by pc00per** [comment]
@cernunnos1710 Nice work mate. I'm kinda expecting some sort pre-defaults aside custom, like alphebetic & reversed.

**Comment by pc00per** [comment]
@cernunnos1710 Nice work mate. So how did you implement sort function ?

**Comment by cernunnos1710** [comment]
Well the sort was already there so nothing had to be done with it. All I need to do now is to make the list toggle-able.

**Comment by opusforlife2** [comment]
@cernunnos1710 Looks great! Please go ahead!

BTW, does this new toggle follow the List/Grid mode setting by default? The user could always tap the toggle to change it, but the default view should respect the setting.

**Comment by cernunnos1710** [comment]
@opusforlife2 Yes. I did not change anything related to the card view other than those related to new layouts (some files were added because of this).

**Comment by cernunnos1710** [comment]
@opusforlife2 @SameenAhnaf 
![Screenshot_20221026-004841](https://user-images.githubusercontent.com/57896620/197791338-f8512197-7826-4b3e-94f9-1953c7e5e5bf.png)

Please take a look at my current implementation of card view. I am going to work on replacing the list view with the reorder dialog

**Comment by cernunnos1710** [comment]
Also, if I completed my implementation of the list view (given that the change would not be major if at all, UI wise) , would it be okay to create a PR?

**Comment by opusforlife2** [comment]
Potential problem: if a user switched to list mode and has several channel groups, their subscriptions could be pushed down very far, needing a lot of scrolling.

I'm thinking maybe channel groups should have their own tab beside Subscriptions? Then it would be easier to have list/grid modes separately for channels and channel groups, without inconveniencing the user.

**Comment by cernunnos1710** [comment]
My implementation of the list view would likely be a copy of what FeedGroupReorderDialog's list look like, which is quite small.

I also think it would be a bit weird since you're adding subscribed channels to channel groups, where both are directly related.

**Comment by opusforlife2** [comment]
Alright. The separate tab discussion can happen later. Please go ahead.

> replacing the list view with the reorder dialog

What does this mean?

**Comment by cernunnos1710** [comment]
My bad. I meant replacing the list layout for channels to the one in reorder dialog where you can drag each item.

**Comment by plasticanu** [comment]
I think you should keep the list size from the reorder dialog list view, but add a gray color background to the text as you did in the earlier PR. @cernunnos1710

**Comment by Stypox** [comment]
(if you open the PR I can take a look at the code ;-))

**Comment by cernunnos1710** [comment]
@Stypox Opened the PR! :)

(I might have opened the wrong one though since I submitted the one that is highly problematic).
