### ISSUE TITLE
NewPipe has started ignoring 't' or time parameter

### ISSUE THREAD

**Issue by tgp1994** [TeamNewPipe/NewPipe#861]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
NP version: 0.11.0

NewPipe used to respect the 't' parameter in URLs and jump to the appropriate time in videos correctly. At some point recently, NewPipe has stopped doing this. Open this URL for example: https://www.youtube.com/watch?t=64&v=YD3fyiVPNDA and note that NewPipe starts at time 0 rather than at 64 seconds like one would expect.

**Comment by theScrabi** [comment]
Confirmed

**Comment by wb9688** [comment]
Confirmed, NewPipe used NewPipeExtractor's `YoutubeStreamExtractor#getTimeStamp()` method for that, but now I don't see any call to that method in NewPipe. (`grep -r getTimeStamp` returns nothing)

**Comment by tgp1994** [comment]
Was a fix for this bug able to make it in to the 11.1 release just now or is it planned for a later release?

**Comment by stalks** [comment]
Having the same issue. Will this be in the next release?

**Comment by theScrabi** [comment]
No seemed not yet fixed.

**Comment by moshpirit** [comment]
New NP user here. Is it related with NP opening the videos in the background/popup from the beginning?

**Comment by theScrabi** [comment]
yes

**Comment by tgp1994** [comment]
@theScrabi Is this a large bug? I see version 0.11.5 was posted to F-Droid but it looks like this bug hasn't been addressed yet.

**Comment by mauriciocolli** [comment]
Fixed in #1268

**Comment by tgp1994** [comment]
Thank you for keeping us informed. It will be nice to see this fixed!

**Comment by theScrabi** [comment]
@mauriciocolli 
If you merge a fix/feature please add a not for it at the [release page](https://github.com/TeamNewPipe/NewPipe/releases)
