### ISSUE TITLE
[YouTube] Downloads slowing down then halting around 90%

### ISSUE THREAD

**Issue by rafallamas** [TeamNewPipe/NewPipe#8619]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Click download 
2. Choose video resolution (happens in any resolution)
3. Wait for download to reach around the 90% mark 

### Affected device model

Huawei Y9s

**Comment by notjedi** [comment]
i can reproduce this issue. the download speeds are very slow after 95%. i'm facing this issue for a long time now. (about 7-8 months)

**Comment by Crystal-RainSlide** [comment]
The percentage may depend on the total size. I got it at 97% more oftenly.
