### ISSUE TITLE
[REQUEST] When searching, be able to sort by "Last Hour, Today, This week..."

### ISSUE THREAD

**Issue by espinosaluis** [TeamNewPipe/NewPipe#862]
This is very useful for some videos that gets uploaded daily from TV shows and you want to get the latest.

**Comment by TobiGr** [comment]
Duplicate of #110.

**Comment by espinosaluis** [comment]
Sorry about that.

**Comment by johnjacobkenny** [comment]
@espinosaluis Please close this issue if it is a duplicate 😄
