### ISSUE TITLE
[Cosmetic] Make settings switches more obvious (red?) when turned on

### ISSUE THREAD

**Issue by Cormak** [TeamNewPipe/NewPipe#863]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

This is very minor but an easy way to polish the look of Newpipe.

In the settings, switches go from dark grey when turned off to brighter grey when turned on. These switches should instead become a bright red when turned on in order to a) make it more obvious they are turned on b) match more with the Newpipe red on both dark and light themes. c) follow what other Material design apps look like.

Again, very minor, but every other modern app has colored settings switches when they are turned on.

**Comment by TobiGr** [comment]
That sounds good.
