### ISSUE TITLE
0.23.1 Failed to start (regression in resources)

### ISSUE THREAD

**Issue by mittorn** [TeamNewPipe/NewPipe#8630]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

Update to new version

### Expected behavior

NewPipe works

### Actual behavior

When trying to launch it does nothing, logcat shows exception

### Logs

```
07-15 04:29:55.959 25930 25930 E ACRA    : ACRA caught a IllegalStateException for org.schabi.newpipe
07-15 04:29:55.959 25930 25930 E ACRA    : java.lang.IllegalStateException: Child drawer has absolute gravity LEFT but this DrawerLayout already has a drawer view along that edge
07-15 04:29:55.959 25930 25930 E ACRA    :      at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1171)
07-15 04:29:55.959 25930 25930 E ACRA    :      at android.view.View.measure(Unknown Source:250)
07-15 04:29:55.959 25930 25930 E ACRA    :      at android.view.ViewGroup.measureChildWithMargins(Unknown Source:42)
07-15 04:29:55.959 25930 25930 E ACRA    :      at android.widget.FrameLayout.onMeasure(Unknown Source:65)
07-15 04:29:55.959 25930 25930 E ACRA    :      at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
07-15 04:29:55.959 25930 25930 E ACRA    :      at android.view.View.measure(Unknown Source:250)
07-15 04:29:55.959 25930 25930 E ACRA    :      at android.view.ViewGroup.measureChildWithMargins(Unknown Source:42)
07-15 04:29:55.959 25930 25930 E ACRA    :      at android.widget.LinearLayout.measureChildBeforeLayout(Unknown Source:6)
```

### Affected Android/Custom ROM version

Android 8.1 MIUI

### Affected device model

Xiaomi Mi Pad 4

**Comment by mittorn** [comment]
0.23.2 still not functional, 0.23.1 does not work anymore

**Comment by opusforlife2** [comment]
Try it on a different device.
