### ISSUE TITLE
video always starts in full screen on unihertz titan pocket

### ISSUE THREAD

**Issue by cheesehead544** [TeamNewPipe/NewPipe#8636]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

play a video with screen rotation locked in portrait. 
the video starts in portrait mode full screen even though the option is off. 
the exit full screen button does nothing. 
2
I believe this may have something to do with the fact that the titan pocket has a 716*720(so almost 1:1) screen. some apps misinterpret what is landscape / portrait mode.
I tested from the latest version down to 22.2.

### Expected behavior

when playing a video with the "start in full screen option" disabled I would expect the video to stay at the size it is before you click play

### Actual behavior

the video switches to full screen automatically and I am unable to leave it without pressing the back button / stopping video playback

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/32103720/179356958-74219e1d-f8fc-4180-a358-a6d979832c38.mp4

### Affected Android/Custom ROM version

android 11

### Affected device model

unihertz titan pocket

edit: added video

**Comment by cheesehead544** [comment]
actually it might not be rotation-related as the interface is not rotated after entering full screen compared to before.

**Comment by SameenAhnaf** [comment]
I think, https://github.com/TeamNewPipe/NewPipe/pull/6059 is the reason. It forces video to be played on full screen while using split screen.

**Comment by cheesehead544** [comment]
I can confirm forcing tablet mode on fixes the problem. I wonder is this just a quirk with how newpipe detects splitscreen? because I don't use that feature at all but leaving tablet mode on auto seems to result in it being turned off

**Comment by opusforlife2** [comment]
It's probably the quirky resolution, with width smaller than height, which causes this.
