### ISSUE TITLE
[Feature Request] History view in kiosk 

### ISSUE THREAD

**Issue by eojjn** [TeamNewPipe/NewPipe#864]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I use newpipe mostly for listening to funky tunes and have found the history page really useful for finding music I've listened to recently or a while ago. Before the introduction of the history feature I depended entirely on my memory+searching or related videos, both of which were pretty restrictive. 

The history feature was a really great addition and also the queue feature, obviously. They've both revolutionised my music listening experience so I'd like to take the opportunity to express my thanks to the team, you're doing an awesome job!

**Comment by r2308145** [comment]
If you like devs work you can consider [donating](https://newpipe.schabi.org/donate/)

**Comment by theScrabi** [comment]
Yes that would actually be a good idea :)

**Comment by 2SI3NX** [comment]
+1 Yes! an easy click history-button and Watched-button would be awesome in the main page kiosk
