### ISSUE TITLE
Small stutter when using popup mode upon unlock of phone

### ISSUE THREAD

**Issue by arvindbadri** [TeamNewPipe/NewPipe#865]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

This was ABSENT in 0.10.0 which I earlier had and PRESENT in 0.11.0.

Steps to reproduce:
1. Open the video in popup mode
2. Lock the phone or put it to sleep
3. Unlock using fingerprint scanner

Video stutters for a few milliseconds or so. It is minor but noticeable.

**Comment by wb9688** [comment]
Hmm… we've updated ExoPlayer from r2.5.1 to r2.5.4 between those releases. Iirc we've also changed stuff in the video players.

**Comment by karyogamy** [comment]
This is because the popup player now stops the video renderer when you turn off your screen. No video decoding when the screen is off == uses less battery usage when playing in the background.  Of course, this comes at the cost of needing to seek once the screen is active again. We can revert this feature if it becomes too annoying.

**Comment by arvindbadri** [comment]
There's gotta be a middle ground, though, right? I'm going to be naive and suggest that we allow the user to toggle between the battery saver mode of stopping the video render when screen is turned off, or the buttery smooth mode of keeping it running.

**Comment by karyogamy** [comment]
Not naive at all. I'll probably add this to the settings the next time I work on the players, but if anybody else is interested, it's up for grabs. Thanks for the suggestion.

**Comment by arvindbadri** [comment]
I'm bored at work, maybe this will be my first open source contribution in
life! Forking now.

**Comment by arvindbadri** [comment]
@karyogamy -- to trivially remove this behaviour, I would simply have to go to org.schabi.newpipe.player.PopupVideoPlayer.java line 627 and comment out enableVideoRenderer(false) right?

**Comment by opusforlife2** [comment]
Didn't happen for me when I checked just now.

**Comment by wb9688** [comment]
@opusforlife2: Probably device specific, but a 3 year old issue about this isn't that useful
