### ISSUE TITLE
While in full-screen, pressing the back button stutters playback

### ISSUE THREAD

**Issue by stdedos** [TeamNewPipe/NewPipe#8658]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Open a video in full screen
2. Press the back button to leave full screen

### Expected behavior

Video continues playback

### Actual behavior

Video/Audio stutters

### Affected device model

S8

### Additional information

_Related to: Playback stutters also when moving back-and-forth in the Background player_

**Comment by opusforlife2** [comment]
> Press the back button to leave full screen

This is supposed to pause the playback after leaving full screen, so if your video still plays, that's another bug entirely.

If you want the video to keep playing after leaving full screen, tap the full screen button.

**Comment by stdedos** [comment]
> This is supposed to pause the playback after leaving full screen, so if your video still plays, that's another bug entirely.

Huh ... you are right! 🤦 I need to remember deeper _what I think the bug is exactly_

> If you want the video to keep playing after leaving full screen, tap the full screen button.

This requires accuracy to do so; the "swipe up for back" (Samsung gestures) does not 😕

**Comment by opusforlife2** [comment]
Ah. Well, NP isn't really adapted to system gestures yet.
