### ISSUE TITLE
cannot play （https://m.youtube.com/watch?v=y-6NvTqG3Yg&ab_channel=MidnightCoffee）

### ISSUE THREAD

**Issue by beasonshu** [TeamNewPipe/NewPipe#8665]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

https://m.youtube.com/watch?v=y-6NvTqG3Yg&ab_channel=MidnightCoffee
above url can not  play in newpipe

**Comment by opusforlife2** [comment]
Wrong template. And the URL plays fine.
