### ISSUE TITLE
[ISSUE]Some videos are not loading

### ISSUE THREAD

**Issue by warlockers** [TeamNewPipe/NewPipe#867]
Hello, 
some videos are not working with NewPipe, for example - https://www.youtube.com/watch?v=Akiv3kwfrXc
When you hit play button, loading screen appeard and jump back with error message "failed to connect stream". I have no issue when i tried to play this video with stock youtube app. 

-Tested on-
Android 4.4. and 5.1
NewPipe 0.11 (latest)

**Comment by johnjacobkenny** [comment]
It works for me. I'm running NewPipe v0.11 on Android 8.0

**Comment by wb9688** [comment]
Confirmed. 1080p, 720p60, 480p, 240p and 144p fail.

**Comment by concatime** [comment]
It may be related, but. On Firefox (without H.264 according to `youtube.com/html5`), I only have `360p`, and no `1080p, 720p60, 480p, 240p and 144p`. But on the other side, Chrome is able to display 144p, 360p, 480p, 720p60 & 1080p60. So, concerning NewPipe, I think that YouTube needs time to internally convert an uploaded MP4 video to WebM, which in this case, the video is 30mn long. That may explains why NewPipe failed on this.
Notes: These are only my speculations.

**Comment by warlockers** [comment]
I found another bug @wb9688 , When i play any videos at 60 fps, after few minutes sound starts chopping, but video still goes well. I think, that issue is at new version of exoplayer, because after downgrade to 0.9.10 everything working fine. All videos are playeable, even the link at the first post ! And also, videos are working in 720p/60fps / 1080p/60fps with no defects. Of course, i miss some features like subscribe option:-( .... I hope that all will be fixed in future version.

**Comment by FaizKhan5** [comment]
Close this issue.
