### ISSUE TITLE
Livestream background playback uses too much bandwidth

### ISSUE THREAD

**Issue by axujen** [TeamNewPipe/NewPipe#8673]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

Open any livestream, in my case https://www.youtube.com/watch?v=9uKjr5RNoXc
Play in background
monitor bandwidth usage and compare to regular videos

### Expected behavior

Livestream videos played in background shouldn't use as much bandwidth as they do atm

### Actual behavior

livestreams background play uses too much data

### Affected Android/Custom ROM version

MIUI 11

### Affected device model

Xiaomi Redmi Note 7

### Additional information

im not an expert, but i understand that this "issue" may not be fixable if youtube does not provide a seperate audio stream for livestreams which is the only way to reduce the amount of data used, if so please close this.
however i also noticed that livestreams have no quality selector so maybe https://github.com/TeamNewPipe/NewPipe/pull/8603 could help reduce data usage by selecting the lowest quality

**Comment by opusforlife2** [comment]
It's not a "bug" because that's how livestreams are meant to work currently. You can open a feature request asking for this functionality to be added. Hopefully someone works on it.

**Comment by AudricV** [comment]
Unfortunately, even if we disable the video and text tracks like we do on seamless transition, HLS video and text tracks are still fetched due to an ExoPlayer issue, so no change would happen on YouTube unless they make working DASH manifests (with which the issue doesn't occur), which should not happen at all I think.

The corresponding ExoPlayer issue has been marked as low priority unfortunately, so there is nothing we can do about this until this issue is fixed for YouTube, sorry :/

**Comment by opusforlife2** [comment]
Any idea why YT uses HLS for livestreams instead of DASH? Technical issues?

**Comment by GameKyuubi** [comment]
Might it be possible to force the lowest video resolution as a stopgap measure?
