### ISSUE TITLE
audio downloads slow down to ~ 15 KB/S towards the very end (99%)

### ISSUE THREAD

**Issue by bughit** [TeamNewPipe/NewPipe#8674]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. download the audio of any youtube video (m4a, 48 kbit)

### Expected behavior

no slowdonw

### Actual behavior

it will slow down towards the end and take more time to finish than it should

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 3a

**Comment by mhmdanas** [comment]
Can you reproduce the same issue with a video download?

**Comment by opusforlife2** [comment]
It's a known problem. Some issues are also open about it.

Don't need to ping specific people. Just commenting is enough to trigger a notification.
