### ISSUE TITLE
delayed audio downloads notification on android 12

### ISSUE THREAD

**Issue by bughit** [TeamNewPipe/NewPipe#8675]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. download the audio of any youtube video

### Expected behavior

the download progress notification should open immediately when the download starts

### Actual behavior

the notifications is delayed ~ 10s

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 3a

**Comment by opusforlife2** [comment]
Is this specific to audio downloads?
