### ISSUE TITLE
Feature: virus

### ISSUE THREAD

**Issue by DamianTC1903** [TeamNewPipe/NewPipe#8688]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

contains viruses, takes advantage of users, report to github.
https://www.virustotal.com/gui/file/9a589053843ec96daf364ab648a1f58c364173e25d752dde36625ec1868e1c55/detection

### Why do you want this feature?

Virus

### Additional information

Virus

**Comment by mhmdanas** [comment]
Please don't open two identical issues. Thank you.
