### ISSUE TITLE
Control enhancements

### ISSUE THREAD

**Issue by v0idst4r** [TeamNewPipe/NewPipe#869]
- [✓] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [✓] I checked if the issue/feature exists in the latest version.
What I'm thinking is, a single press of the forward/reverse button will act as it did in older versions (skip some seconds in the currently playing video) and a long press of these buttons will act as it does now (skip the entire video in the queue)

**Comment by theScrabi** [comment]
Will get back in the next version.
There it will show the skip seconds buttons when u play only one tune, and the next buttons if you play a playlist.
