### ISSUE TITLE
Downloading speeds dies at 95% to 99% even while haveing good internet connection (pls fix) so anoying 

### ISSUE THREAD

**Issue by Hanankhan1983** [TeamNewPipe/NewPipe#8695]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

In the latest version 🙂 (0.23.1)

### Steps to reproduce the bug

There one thing that is helpful for the bug
Click on the pause button and turn it on again the speed will be good Again but who will just keeps clicking pause then turn it on again 😣😅

### Expected behavior

No

### Actual behavior

No

### Screenshots/Screen recordings

No

### Logs

No

### Affected Android/Custom ROM version

Android: 10 but the version doesn't matter the bug is happening with Eveyone Right now 

### Affected device model

Lenovo

### Additional information

There's a very anoying bug in new pipe :( the downloading speed dies at 90% to 99% downloading Done pls fix it so anoying
Thank you (ask any questions if you want)

**Comment by J4CKED** [comment]
The problem still occurs (v24.1).
