### ISSUE TITLE
GreenTube

### ISSUE THREAD

**Issue by zeref-dragneel** [TeamNewPipe/NewPipe#8699]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I want Newpipe app to update look and feel like GreenTube

### Why do you want this feature?

I just found a redesigned app based on Newpipe's open source code with a brand new look and feel. I want Newpipe to update the interface to do the same. Newpipe's interface now looks very classic. I wish Newpipe had a more modern and beautiful interface.

### Additional information

https://play.google.com/store/apps/details?id=by.green.tuber

**Comment by AudricV** [comment]
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

A design modernization would be made first with a design migration of components to Material Design 2 or 3/You.

Also copying design of other apps is not a good idea, and may lead to legal issues for specific cases and apps.

Closing in favor of #7595.

Thank you for reporting this copycat by the way, which seems to not provide source code of its changes, even if the licence require to.
