### ISSUE TITLE
Add local playlist feature

### ISSUE THREAD

**Issue by caogia** [TeamNewPipe/NewPipe#870]
[![](https://api.bountysource.com/badge/issue?issue_id=51898501)](https://www.bountysource.com/issues/51898501-feature-request)

Hi, not sure how to request new feature on github. Please make a favorite/watch later/playlist/ or something that i could play it some moment later.
Does this available ? Thank you

**Comment by theScrabi** [comment]
I think what you request is some sort of local Playlist management. We where discussing about this, and its on our agenda.

However please formulate you request a little more detailed, and please use a more meaningful tittle.

**Comment by theScrabi** [comment]
This could all be implemented allowing local playlists.

**Comment by theScrabi** [comment]
@karyogamy 
Apparently you earned yourself 15$
Please claim them [here](https://www.bountysource.com/issues/51898501-add-local-playlist-feature)

**Comment by karyogamy** [comment]
@theScrabi Thanks.
