### ISSUE TITLE
Make it possible to bookmark channels

### ISSUE THREAD

**Issue by johanw666** [TeamNewPipe/NewPipe#8702]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Make it possible to add Youtube channels to the bookmark list.

### Why do you want this feature?

Currently, when I want to see if there are new videos on a channel, I open a video from that channel in the bookmarks, press the channel name that is printed below it and look for new videos. When the channel can be directly bookmarked this process is much faster.

**Comment by mhmdanas** [comment]
You could create a subscription group called "bookmarks" and add your "bookmarks" to that group. Does that solve your issue?

**Comment by opusforlife2** [comment]
> When the channel can be directly bookmarked this process is much faster.

The Subscriptions tab is exactly for that. Subscribing to/bookmarking channels.

@mhmdanas Wut.

**Comment by mhmdanas** [comment]
@opusforlife2 it seems like they don't want that channel's videos in their feed, but maybe I'm wrong.

> @mhmdanas Wut.

s/subscription group/channel group

**Comment by SameenAhnaf** [comment]
@johanw666 Are you asking any of the following?
Home screen shortcut: https://github.com/TeamNewPipe/NewPipe/issues/1558
App icon long press menu: https://github.com/TeamNewPipe/NewPipe/issues/8044

**Comment by johanw666** [comment]
> > When the channel can be directly bookmarked this process is much faster.
> 
> The Subscriptions tab is exactly for that. Subscribing to/bookmarking channels.

Ah, I didn't realize that I can subscribe to a channel without logging in as a user (I have no Youtube account).

But showing those channels in the bookmarked playlists list would be nice.

**Comment by SameenAhnaf** [comment]
>But showing those channels in the bookmarked playlists list would be nice.

There's already a dedicated tab known as `Subscriptions` which will show all channels. Should we mix up channels and playlists into the same page? 

Btw, https://github.com/TeamNewPipe/NewPipe/issues/3525 asks to add videos into what's new feed from both subscriptions and bookmarked playlists.

**Comment by opusforlife2** [comment]
@johanw666 As a general rule, always read the project README for any software you use. It clearly states this exact functionality.
