### ISSUE TITLE
ACRA configured opt-out?

### ISSUE THREAD

**Issue by IzzySoft** [TeamNewPipe/NewPipe#8705]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

While in the past, ACRA always asked the users' consent before sending reports, this [seems to have changed](https://www.acra.ch/docs/Interactions): if not explicitly configured otherwise, it will now send "silent reports", without asking the users. I've [searched Newpipe's code](https://github.com/TeamNewPipe/NewPipe/search?q=acra) and it seems you're using defaults – which would mean "silent reports" and thus needing the `Tracking` anti-feature with F-Droid. But then I'm no Android dev and might have missed a piece.

Can you please check and state (ideally making sure you've set it to opt-in)? Thanks!

**Comment by TobiGr** [comment]
NewPipe does only collect crash reports via email and GitHub issues. Both methods require user interaction (i.g. click on "report this error via email" or "report on GitHub") and the user is in full control of the shared data. When the user intends to send a crash report via email, they are prompted to read NewPipe's privacy policy and must agree to it allowing us to process the email. For that reason I think that the ACRA config change is irrelavant. Please corerct me if i am wrong.

**Comment by IzzySoft** [comment]
Thanks for your fast answer! I'm no Android dev, so I can hardly tell. I have to take your word here – or find someone who can check and confirm. Let's see if a confirmation can be given by someone "in the knows".

**Comment by TobiGr** [comment]
The magic in ACRA happens in the [AcraReportSender](https://github.com/TeamNewPipe/NewPipe/blob/0039312a64e7271fec2e0a295db1d6979e83cf3f/app/src/main/java/org/schabi/newpipe/error/AcraReportSenderFactory.java#L37-L44). The corresponding factory is initialized via an annotation and is therfore not directly visible in the [App where the other ACRA initializaion is done](https://github.com/TeamNewPipe/NewPipe/blob/cacce6d2d0946ecf2b3cd79e20129031c2c0ca45/app/src/main/java/org/schabi/newpipe/App.java#L202-L210).
 

As you can see below, the AcraReportSender does only open our ErrorActivity which gives the user the options mentioned above.

https://github.com/TeamNewPipe/NewPipe/blob/4058277b7a0caf653a0dea81826e31ea468908f8/app/src/main/java/org/schabi/newpipe/error/AcraReportSender.java#L32-L43

**Comment by IzzySoft** [comment]
Thanks! So that means Newpipe is definitely not affected by the changed strategy of ACRA? That's very good. I shall then add a corresponding MaintainerNote (linking here) should the question come up again at F-Droid's end, e.g. due to a scan.

**Comment by TobiGr** [comment]
>  So that means Newpipe is definitely not affected by the changed strategy of ACRA?

Yes.

> I shall then add a corresponding MaintainerNote (linking here) should the question come up again at F-Droid's end, e.g. due to a scan.

Thank you!

**Comment by IzzySoft** [comment]
Thank you for the details! MaintainerNote added.
