### ISSUE TITLE
NewPipe showing me english videos but the audio is in arabic? 

### ISSUE THREAD

**Issue by Asimopostin** [TeamNewPipe/NewPipe#8710]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

How do i change the language audio of the video?

**Comment by AudricV** [comment]
You can't, only the first audio streams found are extracted by the extractor and so used by the app.

See #5854 to track progression on multiple audio tracks extraction and the corresponding support by the app.
