### ISSUE TITLE
[Feature Request] Auto-play next YouTube suggested vids

### ISSUE THREAD

**Issue by jjgh** [TeamNewPipe/NewPipe#872]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hi, I would love if NewPipe could have an option for auto-playing next YouTube suggested vid when not already playing a playlist or a background queue. For playlist and queues there could be an option for starting auto-play when the playlist/queue reaches the end.

On YouTube this usually lets me discover a lot of amazing music and it's great when you just want to lay back and experience some randomness :)

Couldn't find this mentioned in other feature requests... I hope you miss this as much as I do! (I am forced to depend on official YouTube app - and keeping the screen on - just because of this feature.. :/ . Also, in my case I could finally kick Spotify away...). What do you think?

**Comment by coffeemakr** [comment]
I think the feature you want is already requested by #165 :)

**Comment by jjgh** [comment]
Oops :) I really did it again haha! That shows how much I'm craving that feature 😃
Anyway the referenced feature request is 2 years old now.. any hope it will finally get some love? :) I can't help coding but set a bounty on it and I will be the first one to contribute! ✌️ Just make it happen please! :)
