### ISSUE TITLE
Settings toggle to disable 60 fps videos/streams

### ISSUE THREAD

**Issue by RAPXT** [TeamNewPipe/NewPipe#8723]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

In Video and Audio settings there should be a toggle to disable 60fps videos/streams.

### Why do you want this feature?

I'm watching videos on an 9-year old LG V500 tablet running LineageOS 14 (Android 7). The preferred resolution is set to 1080p (just like the resolution of the screen). Sometimes I stumble upon videos where 1080p is just available in 60 fps, but with this framerate my tablet begins to stutter and looses frames/sync. In these cases NewPipe should automatically switch quality to the next best 30 fps resolution.

**Comment by mhmdanas** [comment]
Assuming you're referring to YouTube videos, unfortunately, this does not appear to be possible. See https://github.com/TeamNewPipe/NewPipe/issues/4902#issuecomment-728993437.
