### ISSUE TITLE
Audio language in Arabic/Persian (?) whereas the official YouTube client or website plays in English 

### ISSUE THREAD

**Issue by DavidH-2022** [TeamNewPipe/NewPipe#8726]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.23.1

### Steps to reproduce the bug

1. Go to Mr Beast's "world's most dangerous escape room" video (https://www.youtube.com/watch?v=3jS_yEK8qVI)
2. play at any resolution 

### Expected behavior

the audio language is in English 

### Actual behavior

the audio is in arabic/persian(?)

### Affected Android/Custom ROM version

Android 11

### Affected device model

OnePlus 8T

**Comment by DavidH-2022** [comment]
the screen recording is too large for github

**Comment by mhmdanas** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/8710#issuecomment-1200248958.
