### ISSUE TITLE
[Feature Request] search filter for restricting search to YT username field and returning the provided username playlists (not feeds!) 

### ISSUE THREAD

**Issue by jjgh** [TeamNewPipe/NewPipe#873]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I collect a lot of music inside YouTube playlists so that I can access them from anywhere, no app needed, no account needed (public playlists). 
I would love if NewPipe could support searching for a YT username and show all its playlists (not feeds).

As of now when I search for a username I see a lot of noise including some of the given user playlists, results from similar search terms, stuff from the user channel... all mixed up together in a big messy list.

It would also be cool if there was an option for seeing a given user playlists as default in NewPipe home screen, when you're subscribed to that user/channel (this could also be upgraded to showing all subscribed usernames names in home screen and then their respective playlists when clicking on one of them!).

Thank you for what you did so far!

**Comment by theScrabi** [comment]
Yes thats true, that would be nice.

**Comment by Stypox** [comment]
Closing in favour of #110 and #2414
