### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by Duderine** [TeamNewPipe/NewPipe#8732]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hey! Since I'm able to download video and audio from youtube, eas just thinking if it would not be interesting to have the opportunity to subscribe to podcasts, by rss or even (better) using goggle (and others) podcast repositories 

### Why do you want this feature?

This way the app gets more complete and I can merge two apps into only one
.
.
.
.
.

**Comment by SameenAhnaf** [comment]
>subscribe to podcasts, by rss

https://github.com/TeamNewPipe/NewPipe/issues/1869

>using goggle (and others) podcast repositories

https://github.com/TeamNewPipe/NewPipeExtractor/issues/565
