### ISSUE TITLE
Queue accessibility 

### ISSUE THREAD

**Issue by 0Karakurt0** [TeamNewPipe/NewPipe#8733]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I think it would be really helpful to add a button to open background player from UI, the same one you access if you tap on player notification.

### Why do you want this feature?

 - On my phone I almost always loose player notification (idk if this is NP issue, even though NP is the only one affected), and regularly find myself in a situation when I want to edit the queue, but if I click on video I will almost certainly loose the queue (when switching from bg player to fg video player).
Or even worse, I get completely desynchronized from what is currently playing, if at the moment of notification disappearance I was viewing not the video playing in bd. And the only way to access currently playing one is through history tab, but even then I do not follow automatically to the next video.
 - Consistency, there's no other way to get to that menu other than player notification
 - it could be used later for improving fg video queue - current way is workable but limited, one cannot save or shuffle current fg video queue, for example

### Additional information

I have a feeling that implementation of #8353 would be a stepping stone for mine issue as it would make sure that queue does not disappear while transitioning from bg to fg player

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3515

**Comment by 0Karakurt0** [comment]
@SameenAhnaf My bad, did not find it. Thanks
