### ISSUE TITLE
Playlist not being found in search

### ISSUE THREAD

**Issue by DeadManIV** [TeamNewPipe/NewPipe#876]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

One of my playlists isn't found when I search for it. YouTube has the same problem and doesn't show it in search results when I search for my username. I am able to find some of my other playlists however. I have checked to make sure that it is public.

My playlist for reference:
https://www.youtube.com/playlist?list=FL3hm1ymIqH41ZKDnr1TW5Iw

My search on YouTube:
https://www.youtube.com/results?search_query=deadmaniv

My username: deadmaniv

P.S. Thanks for all your hardwork, NewPipe is a really useful app!

**Comment by theScrabi** [comment]
I cant find it on the web youtube UI either.

**Comment by wb9688** [comment]
I can confirm that it doesn't show up on both YouTube.com and NewPipe.

>YouTube has the same problem

Then it's a problem on YouTube's side, so we can't do anything about it.
