### ISSUE TITLE
Videos not playing, Google change something.

### ISSUE THREAD

**Issue by Dalimit** [TeamNewPipe/NewPipe#8762]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

Nnnn

### Expected behavior

Jnnnn

### Actual behavior

Nnnnjnn

### Screenshots/Screen recordings

Hnnnn

### Logs

Bnnnnnjjjjj

### Affected Android/Custom ROM version

Jsjsj

### Affected device model

Nnn

### Additional information

Njnnnn

**Comment by xorbital** [comment]
Checklist ignored, duplicate issue of #8760

**Comment by kubeele** [comment]
same to you
