### ISSUE TITLE
Only partially works with Android 4.4: should use external player by default

### ISSUE THREAD

**Issue by ksaerdna** [TeamNewPipe/NewPipe#877]
I use the app with an old Nexus S running Android 4.4 (Cyanogen) without gapps.

Browsing works fine, but whenever trying to play it I get a failure explanation and a long crash report.

But however, when I touch the triangle on the movie preview, the video is being played using "gallery" as external player application.

Conclusion: There should be an option or method to avoid the failure -- as it always happens -- and to directly proceed with playing the video using the gallery application (that comes with Cyanogen in my case).

**Comment by Zykino** [comment]
Parameters -> Video & Audio -> Player : Use external [video/audio] player

**Comment by ksaerdna** [comment]
_Einstellungen -> Video & Audio -> Player -> Benutze externen Videoabspieler_

is already activated.
There is also

_Benutze externen Audioabspieler_

which is NOT activated.

Do I have to activate both?

**Comment by theScrabi** [comment]
Yes

**Comment by ksaerdna** [comment]
I did, but no change. Still getting "Entschuldigung. Es sind einige Fehler aufgetreten. MELDEN". After about ten seconds the message vanishes, and everything is fine.

**Comment by jojo313** [comment]
4.4 is still a thing? Maybe you should upgrade... A Moto G4 Plus is 160€ @ mediamarkt.

**Comment by ksaerdna** [comment]
This device is mainly used for development and testing. It's necessary to make sure that my program (https://f-droid.org/packages/de.kromke.andreas.unpopmusicplayerfree/) is compatible with older devices.

**Comment by theScrabi** [comment]
Hm I normally don't say this, but @ksaerdna can you please post the error here?

**Comment by ksaerdna** [comment]
When preparing to test the app, it just was updated (via F-Droid) to 0.11.1, and the problems are gone, i.e. it seems to work flawlessly. I am sorry for any inconvenience caused.

**Comment by timoteo7** [comment]
What Version of NewPipe is compatible with Android 4.4 ? (SDK: API 19)
