### ISSUE TITLE
Play video in playlist doesn't queue playlist videos.

### ISSUE THREAD

**Issue by DeadManIV** [TeamNewPipe/NewPipe#878]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

In the official YouTube app, when I open a video in a playlist, it plays the video and queues the playlist. This does not happen in NewPipe. In NewPipe, there is a Play All button, but I think that there is no reason for it not to queue the rest of the videos if I scroll down a playlist and select a video - this wouldn't harm the experience of users who just want to watch one video in a playlist, because they can just back out, but it would enhance the experience of users who open a playlist and scroll down, then select a video, with the intent to watch more videos in the playlist. Currently NewPipe will only play the video selected, unless you click Play All.

I hope that makes sense, please ask me for further explanation if necessary, it was a bit tough for me to explain this one. It's not a bug, it's a possible enhancement.

**Comment by theScrabi** [comment]
Atm you can tab on play all videos, and than select the Video you want to watch in your local playlist screen.

**Comment by DeadManIV** [comment]
@theScrabi Yes, but I think it would be nice if the playlist videos were queued anytime you tapped on a video in a playlist instead of just using the Play All button. It's a very small gripe, it's not particularly important.

**Comment by TobiGr** [comment]
It is possible to do that by pressing on the video in the list. This will open a dialog in which you can choose "Start here".
