### ISSUE TITLE
Newpipe v0.23.2 not on Fdroid

### ISSUE THREAD

**Issue by SouriyaRoy** [TeamNewPipe/NewPipe#8785]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hey guys, the froid repo is still not updated to v0.23.2
The Fdroid app is still broken. Is the update coming soon?

**Comment by yasenn** [comment]
There is a workaround: apk is available on [Releases](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.23.2) page

**Comment by Gitoffthelawn** [comment]
@SouriyaRoy My understanding is that, to ensure the executable binaries match the source code, F-Droid builds each project independently in a sandboxed environment.  This takes some time, as F-Droid handles building hundreds of different projects.

Once F-Droid successfully builds the latest release of this project, it will be made it available in the official F-Droid repo.  In the meantime, if you can use the GitHub release as mentioned by @yasenn.

**Comment by SouriyaRoy** [comment]
Thanks guys. Closing the issue.

**Comment by opusforlife2** [comment]
https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

**Comment by lrq3000** [comment]
Warning for those who used the f-droid release: to install from the apk, you need to first uninstall the fdroid version as the signatures don't match, which means you'll lose your subscription and playlists that were saved inside the app. So first make a backup.
