### ISSUE TITLE
[Crash]ERROR_CODE_DECODER_INIT_FAILED

### ISSUE THREAD

**Issue by hkaancaliskan** [TeamNewPipe/NewPipe#8788]
https://youtu.be/IHfqcgIjeMM
I got this error when i try to play on Galaxy A52, Android 12

`{"user_action":"play stream","request":"Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=IHfqcgIjeMM","content_language":"tr-TR","content_country":"TR","app_language":"tr_TR","service":"YouTube","package":"org.schabi.newpipe","version":"0.23.2","os":"Linux Android 12 - 31","time":"2022-08-14 11:09","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(315, null, null, video/x-vnd.on2.vp9, vp9, 30650916, en, [3840, 2160, 60.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.vp9, Format(315, null, null, video/x-vnd.on2.vp9, vp9, 30650916, en, [3840, 2160, 60.0], [-1, -1])\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1017)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437)\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)\n\t... 4 more\nCaused by: android.media.MediaCodec$CodecException: Error 0xfffffff4\n\tat android.media.MediaCodec.native_configure(Native Method)\n\tat android.media.MediaCodec.configure(MediaCodec.java:2176)\n\tat android.media.MediaCodec.configure(MediaCodec.java:2092)\n\tat com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:167)\n\tat com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)\n\tat com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:111)\n\tat com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:128)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1095)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1006)\n\t... 11 more\n"],"user_comment":""}`

**Comment by hkaancaliskan** [comment]
Looks like problem is on 4K playback.
I can play other 4K videos flawlessly. If 4K play fails like this, imo newpipe should try lower resolutions.

**Comment by litetex** [comment]
1. Please create an issue with a proper template (you can find them here: https://github.com/TeamNewPipe/NewPipe/issues/new/choose)
2. I see "NO_EXCEEDS_CAPABILITIES" → This likely means that your device can't handle the video.
