### ISSUE TITLE
Uploader profile page doesn't have playlists tab

### ISSUE THREAD

**Issue by DeadManIV** [TeamNewPipe/NewPipe#879]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When I go to an uploader's profile in NewPipe, it only shows the uploaded videos. So I would like to request a Playlists tab, like in the official YouTube app, because there is otherwise no way for me to access all of my playlists within NewPipe itself. Currently what I do is open the official YouTube app, go to my profile page, open my playlist then share it to NewPipe.

I assume this is probably something that is in the works, or a planned feature, but I'm not sure, so I decided to create this as an issue. Feel free to delete it if true.

**Comment by theScrabi** [comment]
No it's not yet in implementation, and it's not yet planed.

**Comment by DeadManIV** [comment]
Then I hope you'll be okay with adding this feature. I am a programmer myself, but I cannot give time to other projects right now, I am too busy with my own work. If I were to attempt to implement it.. the earliest I could try would be in June 2018.. next year..

**Comment by TobiGr** [comment]
@DeadManIV I'm not sure if I understand you correctly, but do you want to go to a channel and then play all videos?

**Comment by theScrabi** [comment]
No I think he means that in Youtube playlists can be associated with channels. Currently NewPipe does not show the playlists that belong to a certain channel.

**Comment by DeadManIV** [comment]
![screenshot](https://user-images.githubusercontent.com/9134591/33439642-dfa66510-d5e5-11e7-92c6-972c6a9c4c3c.png)
@TobiGr 
Yes, @theScrabi is correct. Like in the screenshot from the official YouTube app.

**Comment by coffeemakr** [comment]
I think this corresponds to the following link: https://www.youtube.com/user/MARVEL/playlists?sort=dd&view=1&shelf_id=0

**Comment by DeadManIV** [comment]
@coffeemakr that's it exactly.

**Comment by justanidea** [comment]
What about this request today? :)

**Comment by Stypox** [comment]
Closing in favour of #2414
