### ISSUE TITLE
share button from soundcloud does not work

### ISSUE THREAD

**Issue by garawaa** [TeamNewPipe/NewPipe#8792]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

select or play any song in soundcloud app. select share then newpipe. It just reopens soundcoud app.  It should be opened in  newpipe with shared song.

### Affected Android/Custom ROM version

android 12

### Affected device model

samsung note 10 5g

**Comment by opusforlife2** [comment]
Could you paste an example link here?
