### ISSUE TITLE
MPEG-4 1080p60 streams lose audio and video sync on Samsung Galaxy Tab A7

### ISSUE THREAD

**Issue by TDavLinguist** [TeamNewPipe/NewPipe#8797]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Set default video and audio formats to MPEG-4 and M4A
2. Play a video on my Samsung Galaxy Tab A7 which has <s>either</s> 1080p60 <s>or 720p60</s> format
3. Observe that the video plays in slow-motion (the video is played at 30fps when it is actually 60fps) and that the audio is thus out of sync with the video
4. Switch to 720 (30 fps) and observe that the video and audio are perfectly in sync
5. Switch default video and audio formats to WEBM
6. Observe that the video plays normally
I first noticed it on [this Louis Rossmann video](https://www.youtube.com/watch?v=ypQqSTmR0uA).

### Expected behavior

The MPEG-4 1080p60 <s>or 720p60</s> streams should have perfect video and audio sync.

### Actual behavior

The MPEG-4 video on the 60fps stream plays at half speed while the audio plays at normal speed, thus bringing the video and audio streams out of sync.

### Affected Android/Custom ROM version

Android 11 Kernel 4.19.152

### Affected device model

Samsung Galaxy Tab A7 SM-T500

### Additional information

This issue does not occur on my phone (Samsung A20, running Android 9 with kernel 4.4.111) with MPEG-4 as default video and audio format.

**Comment by TDavLinguist** [comment]
Edit: The original post mentioned 720p60 as well, but when I tested again, only the 1080p60 stream displayed this behavior. I'm changing the report to reflect this.

**Comment by AudricV** [comment]
I'm afraid that this behavior, playback shuttering, is device specific and cannot be fixed by us, as it is due to device capabilities and limits.

(This also affects me on WEBM 1080p60 streams, as it seems I don't have an hardware WEBM decoder on my Honor 9X running official EMUI.)

Closing as can't fix.

**Comment by PandaCuddles** [comment]
Not sure if this will help, but MPEG-4 1080p60 worked on an earlier version of newpipe (I think it was 0.23) for the Galaxy Tab A7, and an update broke the playback (this was on android 11).
