### ISSUE TITLE
Bug: progress bar not moving

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#88]
As soon as the video controls dissapear the progress bar stops moving. At the end of the video it's still at the point where the controls dissapeared. Not sure if that made any sense to you guys so let me know if I was to vague.

**Comment by theScrabi** [comment]
I think i get you. But if i get it right i might not be able to help (at least not with a simple workaround). The video controls are the standard video controls. All you need to do is hock them up to a videoview. So i don't actually know how these two objects are communicating with each other. Means the error is most likely the fault of android itself. (We may need our own video controls one day)

**Comment by JasperWeiss** [comment]
I see, it's only when the video ends though so it's not such a big or a deal.

**Comment by theScrabi** [comment]
Ow ok than I didn't get you xD. Yes I know this. But since it isn't such a big deal I didn't care about it yet.
