### ISSUE TITLE
[Feature request] Make newpipe be recognized by the system as a music player

### ISSUE THREAD

**Issue by Kurolox** [TeamNewPipe/NewPipe#880]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

I've seen that stuff like gadgetbridge doesn't recognize newpipe as a music player. I don't have any knowledge about android development, but I feel like if newpipe was somehow flagged as a music player system-wide, wearables could get metadata from the videos playing, among other stuff.

**Comment by theScrabi** [comment]
Yes that should actually be done.

**Comment by Hyrulian** [comment]
This is a really small great improvement you could make. I'd love to be able to control NewPipe with my smartwatch! Thanks team!

**Comment by theScrabi** [comment]
Yep also I don't think its to hard to do.

**Comment by speednroll** [comment]
when do they work on this? would be good to pause or play automatically from the button of my bluetooth headphones the music of youtube/soundcloud :stuck_out_tongue_closed_eyes:

**Comment by speednroll** [comment]
also, if this is implemented after the playlists. make the option of when you press play on your headphones when there are no videos loaded they automatically load a playlist that you have made on the background player. it's just an idea

**Comment by radiocane** [comment]
This looks related https://stackoverflow.com/questions/15527614/send-track-informations-via-a2dp-avrcp

**Comment by theScrabi** [comment]
@radiocane thx :D 

Our latest version has a working media session. With this you can control NewPipe from external devices like a headset or an external player (so far I only tried it with headset). Could you please test if this working media session may also have fixed these issues here.

**Comment by radiocane** [comment]
@theScrabi I opened a new issue #1507

**Comment by theScrabi** [comment]
@radiocane but you where able to control NewPipe from your car?

**Comment by miztermiyagi** [comment]
I love newpipe, it would be incredible to be able to skip/pause/play songs from my WearOS watch. (Ticwatch E)

**Comment by ildar** [comment]
it does not (correctly) on my KK. Will test more later

**Comment by Kurolox** [comment]
I've been testing with my Gear S3 Frontier, and it seems like it mostly works for me. I can pause, go to the previous and next song, and even select any video in a playlist. The only thing that doesn't seem to work properly is that it doesn't fetch the metadata from the song currently playing (song name, artist, cover image...)

Besides that, it seems to offer better integration on the S3 than the official youtube app. It shows the metadata properly, but unlike newpipe it doesn't let you select any song from a playlist. Will attach screenshots to show the difference.

**Comment by theScrabi** [comment]
Hm :) that sounds good :) Hopefully this is not an exception. Android segmentation you know :/

Well next thing to fix the meta info :)

**Comment by ildar** [comment]
This functionality misbehaves in windowed mode. If I lock the screen it
goes on playing but the media buttons &$_$ job working audio-only player.

> --
Ildar Mulyukov,
(ΙΧΘΥΣ) child of God

email: ildar.mulyukov@gmail.com
matrix: @ildar:matrix.org
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by theScrabi** [comment]
Yes

**Comment by Stypox** [comment]
This was added in #2080
