### ISSUE TITLE
F-Droid Sync/Update?

### ISSUE THREAD

**Issue by js290** [TeamNewPipe/NewPipe#8806]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Thanks for fixing #8760 in 0.23.2.  It looks like the new apk is available for download from github, but F-Droid is still on 0.23.1.  When does F-Droid get updated when a new version is available for download from github?

**Comment by mhmdanas** [comment]
Usually after a couple days, but rarely it can reach up to a week. You can also use our custom F-Droid repo, which receives updates immediately: https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

If you have further questions feel, free to ask.

**Comment by michael9dk** [comment]
Thanks, I had the same question.

Shouldn't this answer be a sticky? I've noticed the same repeated issue, when YT changes things and F-Droid isn't updated with the fix.

**Comment by mhmdanas** [comment]
We can only have a maximum of three pinned issues, so I don't think pinning this issue is a good idea. We can, however, add this question to the NewPipe website FAQ.

**Comment by michael9dk** [comment]
May I suggest a sticky "Commmon issues and solutions"-thread.

**Comment by mhmdanas** [comment]
I think a better idea is to add another item to the issue checklist that states something like this: "I checked the FAQ and made sure that my question is not there"
