### ISSUE TITLE
Earphone button commands

### ISSUE THREAD

**Issue by DeadManIV** [TeamNewPipe/NewPipe#881]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

As a possible enhancement could earphone button support be added?
I assume this is not a bug, but just a possible feature because my buttons work in Rocket Player but not in NewPipe.

**Comment by coffeemakr** [comment]
Duplicate of #781

**Comment by DeadManIV** [comment]
Oh, sorry about that, I searched for earphone, not headset. My bad. Should I close it?

**Comment by coffeemakr** [comment]
Yes please :)

**Comment by DeadManIV** [comment]
Okay, will do.
