### ISSUE TITLE
An invalid bug report email address

### ISSUE THREAD

**Issue by mdimjasevic** [TeamNewPipe/NewPipe#8813]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Attempt to open a YouTube video, but for some reason it fails.
2. The application offers to report the crash to an email address crashreport@newpipe.schabi.org.
3. Attempt to send the report via email, only to get an automatic reply that the email was undelivered.

### Expected behavior

I would expect the email to go through.

### Actual behavior

The email cannot be delivered.

**Comment by mhmdanas** [comment]
That is definitely strange, because we still get crash reports via that e-mail address. Mind if you post the contents of the "automatim reply"?

**Comment by mdimjasevic** [comment]
Sure, I'm attaching it here.

[Exception_in_NewPipe_0.23.1.txt](https://github.com/TeamNewPipe/NewPipe/files/9357218/Exception_in_NewPipe_0.23.1.txt)

**Comment by TheAssassin** [comment]
That's the mail you sent to the address, not the other way round. Also, the mail address is definitely not invalid. This is clearly *not* a bug.

**Comment by mdimjasevic** [comment]
My apologies, the delivery report is [attached](https://github.com/TeamNewPipe/NewPipe/files/9367832/delivery-report.txt).

**Comment by TheAssassin** [comment]
```
530 5.7.0 Must issue a STARTTLS command first
```

Your mail host does not support TLS. Our mail server does not accept unencrypted connections, though. It's 2022 after all... there is no reason to send unencrypted postcards any more across the Internet...

This is clearly _not_ a bug, it's a feature.
