### ISSUE TITLE
Doesn't save landscape rotation in video

### ISSUE THREAD

**Issue by DeadManIV** [TeamNewPipe/NewPipe#882]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I'm not sure if this issue is localised only to me, so I'll give my specs:
Nexus 5
Official Android 6.0.1 (Latest)

When I open a video, I always have to switch it to landscape because it always starts in portrait mode. This might not be a bug, but a potential enhancement. I watch pretty much all videos landscape, so perhaps a default display mode could be added to the settings, so that it always starts in landscape (if selected) with the option to switch to portrait via the button already available.

**Comment by ao2** [comment]
Just curious, do you have the rotation "Locked" in the Android settings?
And if not, do you rotate the tablet **after** opening the video fullscreen or is it already rotated?

Maybe issue #1156 and this one can be merged.

**Comment by Stypox** [comment]
This has been fixed
