### ISSUE TITLE
Can't update from F-Droid

### ISSUE THREAD

**Issue by jrhossain2** [TeamNewPipe/NewPipe#8830]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Install older version of newpipe from f-droid
2. Then try to update the app

### Actual behavior

When I tried to update newpipe, it shows "Failed to install due to an unknown error". Then I downloaded latest version from github. But now it shows "App not installed", though I've already installed 0.23.1.

But when I uninstalled old version manually & reinstalled from f-droid it works. I that any signature error? IDK. Please fixed that

### Affected Android/Custom ROM version

Android 11

**Comment by AudricV** [comment]
> Please fixed that

There is nothing we can do about this, please read what should be read (the README) section `Installation and updates`: https://github.com/TeamNewPipe/NewPipe#installation-and-updates. Thank you.
