### ISSUE TITLE
Allow sorting by latest

### ISSUE THREAD

**Issue by airednot** [TeamNewPipe/NewPipe#884]
Some of us replaced yt with NewPipe entirely. In this case what I'm particularly missing is "sorting feature" that would allow me finding newly published videos. It's pretty handy while looking for latest news about some topic. Normally it shows most viewed or trended.

**Comment by TobiGr** [comment]
> Some of us replaced yt with NewPipe entirely.

That's nice to hear! The filter functionality has already been requested in #110. Please close this ticket, so we can collect all required information there.

**Comment by airednot** [comment]
OK then, I hope it'll be implemented soon. It's sort of a main issue for me to never look back at yt.
