### ISSUE TITLE
How to add crash rep fr:Legacy 20.8 to an already posted crash rep from Latest NewPipe (23.2)

### ISSUE THREAD

**Issue by Grannydontplay** [TeamNewPipe/NewPipe#8844]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

How do I  add a crash rep from NewPipe Legacy 20.8 to an already posted crash rep from Latest NewPipe (23.2) ?

Legacy crash-rep generated when trying  'Steps to reproduce bug' in "Error — io bad, player http status #8843"
—couldn't reproduce in 23.2, so tried my luck in Legacy 20.8 player, which gave me separate crash-rep, but I'm unsure whether it is useful to currently posted crash-rep for "Error — io bad, player http status #8843"

### Additional information

🙏🏼🦾

**Comment by opusforlife2** [comment]
We don't support the Legacy app anymore. Any crash reports from it are useless for investigating the bug.
