### ISSUE TITLE
Slow buffering at 720p

### ISSUE THREAD

**Issue by horvathlaszlogyorgy** [TeamNewPipe/NewPipe#8853]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

- Open a random video, eg https://www.youtube.com/watch?v=HZl7aqkE71A
- It starts very slowly, and when it does start, it stops buffering afterwards.
- If you switch to 1080p instead of 720p the problem goes away.

The issue doesn't occur with all videos. I don't know what it depends on.

### Screenshots/Screen recordings

One of the most beautiful things is when you are looking for a solution to one issue, but you find another one :sweat_smile:

https://user-images.githubusercontent.com/88249170/185813987-ecf7bf5e-484f-4329-b5d2-c7f35b22bdcb.mp4

### Affected Android/Custom ROM version

Android 12 / One UI 4.1

### Affected device model

Samsung S21

### Additional information

- No problem with the network connection.
- Tried to wipe cache.

**Comment by 0Karakurt0** [comment]
had the same issue, can confirm. Before 23.2 it existed too, but was a lot less and pretty much random per video. now it's almost on every second video

**Comment by Eiion** [comment]
Same as #8839
