### ISSUE TITLE
What's new feed doesn't refresh when fast mode enabled

### ISSUE THREAD

**Issue by CrimsonFork** [TeamNewPipe/NewPipe#8855]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

- set feed to fast mode
- update

### Expected behavior

feed should update

### Actual behavior

it doesn't

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/22666602/185845663-1d06de5c-c772-4a7d-af0e-1adc3cb0f909.png)

### Affected Android/Custom ROM version

Android 10 (MIUI)

### Affected device model

Huawei P Smart 2019 (POT-LX1)

### Additional information

"last updated" field remains empty
"slow" feed loading still works just as well (which is to say, not optimally #8005 )

**Comment by opusforlife2** [comment]
No snackbar error, even? Just a silent fail?

**Comment by CrimsonFork** [comment]
Yes. It looks like it's doing the work properly, but when the loading par
finishes it's just the previous videos and what's on the screenshot.

**Comment by CrimsonFork** [comment]
Just found out that this issue is still open even though the problem has been long fixed.
