### ISSUE TITLE
ability add channel groups to the main page

### ISSUE THREAD

**Issue by skrshe** [TeamNewPipe/NewPipe#8857]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

ability to set channel groups as tabs in the main page  so they show up like the `What's New` tab

### Why do you want this feature?

so I can be greeted with a pedigree selection of videos while being subscribed to a lot of creators

also ease of access to channel groups as it is combersome to go to 
subscriptions>channel group 
when a channel group is the main content that I wish to access

**Comment by SameenAhnaf** [comment]
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3319

**Comment by skrshe** [comment]
cool I need to get better at searching such things.
sorry 😹
