### ISSUE TITLE
Maximum watch history size.

### ISSUE THREAD

**Issue by Nizami20052022** [TeamNewPipe/NewPipe#8860]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Apply a limit to watch history size.

### Why do you want this feature?

To set a limit on the watch history size.

**Comment by GameOverFlowChart** [comment]
I want this feature for increased privacy without disabling that feature completely and to limit the size of the storage the app needs over time. Would also make the database thats used to export and import during device migration smaller.
