### ISSUE TITLE
Plz add app filters 

### ISSUE THREAD

**Issue by Gul7333** [TeamNewPipe/NewPipe#8865]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Many apps doesn't work correctly so I have to manually stop AdAway to run those app....after using then I turn on AdAway....like YouTube...also others.....plz add a filter like in vpn to exclude some apps so that these app doesn't use AdAway host...and work correctly...I have rooted phone so make update of AdAway with App filters...I will be very thankful to you

### Why do you want this feature?

It's necessary and will keep us from hardwork turning on and off AdAway 

### Additional information

I used YouTube app and also also allowed many hosts in adway so that my watch and search history is collected by YouTube...but nothing worked ... YouTube is showing me same videos again and again... it thinks that I haven't watched these videos but actually AdAway is stoping them by stoping host....Don't advice me to allow hosts..I have done this...added many host related to YouTube... got advice from developers...read and applied every issue of AdAway.... cleared cache and uninstalled and reinstalled... Nothing working....Also other app which also don't work until ad is shown like ..so plz add app filters especially for rooted phone

**Comment by ouzowtf** [comment]
Maybe others are smarter, but I'm not sure I understood what's the problem or the behavior you want.
But if you have to disable AdAway to use NewPipe, you have to contact the AdAway developers.

**Comment by opusforlife2** [comment]
@Gul7333 Newpipe works fine along with AdAway. Maybe you have a bad filter list that is blocking the Youtube domains needed to fetch videos, such as `googlevideo.com`. In that case, you need to remove that filter list.

**Comment by Gul7333** [comment]
Sorry this issue was meant to be put on AdAway...it was my mistake ...New pipe is Good
