### ISSUE TITLE
[YouTube] Videos and descriptions not loading

### ISSUE THREAD

**Issue by jakem72360** [TeamNewPipe/NewPipe#8876]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

Open NewPipe, and attempt to play any video from your feed.

### Expected behavior

The video loads, and plays

### Actual behavior

Comments and their avatars are loading, however the video preview remains black, and the description is stuck loading with a spinning wheel.

### Affected Android/Custom ROM version

Android 10 / OxygenOS 10.0.1

### Affected device model

OnePlus 5

### Additional information

Videos and their descriptions were loading and playing perfectly yesterday, hence why I'm tempted to think this may be an API/parsing issue. I've cleared NewPipe's cache and restarted the app, but am hesitant to wipe the app's data if I don't need to...

**Comment by atar-axis** [comment]
Same here, Samsung A8, latest newpipe, cleared cache.

**Comment by TheMCNerd2017** [comment]
Having the same thing start happening an hour ago on a Pixel 4 XL. Force-stopped and cleared the cache multiple times but the issue persists. Something to note is that comments would sometimes load properly when this issue started happening, but now they don't.

**Comment by gqqjhffr** [comment]
Had the same thing happen to me on my Google Pixel 4 (5G).

**Comment by Lykantier** [comment]
Same here, Android 10 on a Xiaomi Redmi 9C.

**Comment by mimounelh** [comment]
Same here, on a SM-J710FN
![Screenshot_20220825-023658_NewPipe.jpg](https://user-images.githubusercontent.com/78168500/186548115-4fba9156-d494-442a-b1a8-909ea39f4c02.jpg)
Maybe another google mess up functionality that breaks NewPipe...

**Comment by matthenry2** [comment]
Videos and descriptions are not loading still buffering! Fix issue.

**Comment by crappyrules** [comment]
> Videos and descriptions are not loading still buffering! Fix issue.

REEEEEEEEEEEE FIX THE OPEN SOURCE SOFTWARE YOU TOIL OVER AND I USE FOR FREE NOW!!!

**Comment by Magyman** [comment]
I'm seeing the error 

`java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/lang/model/SourceVersion;
	at org.mozilla.javascript.JavaMembers.<clinit>(JavaMembers.java:37)`

When trying to open a YouTube link from another app.

I can post the whole stack trace if anyone thinks that would be helpful

**Comment by shell-raiser** [comment]
> Same here, Samsung G950f, Android 9, Latest Newpipe 0.23.2, cleared cache.
> 
> Since this is happening more often it would be so nice to have a "open in Webbrowser" button even if the video does not load. :)
> 
> It looks like this:
> 
> <img alt="Screenshot_20220825-022759_NewPipe" height="300" src="https://user-images.githubusercontent.com/11148588/186547297-c5d5da2b-2377-4e93-8c3c-fd2e94268d23.jpg">

"Open in browser" works. Tap and hold the video thumbnail to get the pop-up

**Comment by teambvd** [comment]
> > Videos and descriptions are not loading still buffering! Fix issue.
> 
> REEEEEEEEEEEE FIX THE OPEN SOURCE SOFTWARE YOU TOIL OVER AND I USE FOR FREE NOW!!!

@crappyrules did someone edit their post, or is this a busch league troll attempt?

Anyway, feels like another google API change to me

**Comment by gbatmarx** [comment]
Same here. I hope this issue will be fixed soon. I just discovered newpipe yesterday and now it doesn't work.
Android 12.

**Comment by TAXSET** [comment]
Having same issue, [debug build by @Theta-Dev](https://github.com/TeamNewPipe/NewPipe/files/9387795/app-debug.zip) in #8839 seems to have fixed the issue 3 days ago.

**Comment by atar-axis** [comment]
@taxset right, thanks for mentioning

**Comment by beomusxyz** [comment]
> > > Videos and descriptions are not loading still buffering! Fix issue.
> > 
> > 
> > REEEEEEEEEEEE FIX THE OPEN SOURCE SOFTWARE YOU TOIL OVER AND I USE FOR FREE NOW!!!
> 
> @crappyrules did someone edit their post, or is this a busch league troll attempt?
> 
> Anyway, feels like another google API change to me

they're making fun of the guy demanding the devs fix this immediately even though they all have lives too...

**Comment by ow-ro** [comment]
seems to be related to an issue with the Rhino version being used in the extractor, fixed for us by forcing a downgrade to 1.7.13 for now

```
implementation 'com.github.TeamNewPipe:NewPipeExtractor:25f0ce7305822d37bb6ff21280dff37b2451affd'
implementation 'org.jsoup:jsoup:1.15.3'
implementation ('org.mozilla:rhino') {
        version {
            strictly '1.7.13'
        }
    }
```

possibly related? https://github.com/mozilla/rhino/issues/1149

**Comment by teambvd** [comment]
Which would make sense, if anyone did that - I see no instance of it, at least looking at the edit history of preceding comments. Maybe I missed it?

**Comment by Roruuki** [comment]
Same here, on a Xiaomi Redmi Note 8 Pro
![Screenshot_2022-08-25-10-05-46-511_org schabi newpipe](https://user-images.githubusercontent.com/64415317/186557781-3ce80b38-5cab-4030-8426-21bed89df440.jpg)

**Comment by BlanXyz** [comment]
> Same here, on a Xiaomi Redmi Note 8 Pro
> <img alt="Screenshot_2022-08-25-10-05-46-511_org schabi newpipe" src="https://user-images.githubusercontent.com/64415317/186557781-3ce80b38-5cab-4030-8426-21bed89df440.jpg" height=600 />
> 

I do believe a new Heads up message at the beginning of these  breakage issues which attract attention, is required. This space is constantly being filled with 'Oh Me too! Me too!' Replies which make it hard for actual collaborators to help solve the issue. As bystanders without any new information to add, a thumbs up reaction is enough..

**Comment by teststation5** [comment]
> seems to be related to an issue with the Rhino version being used in the extractor, fixed for us by forcing a downgrade to 1.7.13 for now
> 
> ```
> implementation 'com.github.TeamNewPipe:NewPipeExtractor:25f0ce7305822d37bb6ff21280dff37b2451affd'
> implementation ('org.mozilla:rhino') {
>         version {
>             strictly '1.7.13'
>         }
>     }
> ```
> 
> possibly related? [mozilla/rhino#1149](https://github.com/mozilla/rhino/issues/1149)

This also works to fix the issue in my Simple Song Collector

**Comment by AA-Coder-Beg** [comment]
I thought it was just my internet acting up. Man, what is YouTube doing?! This is like the second time in a row!

**Comment by marek22k** [comment]
Same issue for me

**Comment by mbjorck69** [comment]
Videos with comments disabled seems to be loading OK. If it helps.

**Comment by delvydo** [comment]
Same problem with me, UMIDIGI Bison Pro, Android 11.
NewPipe Legacy and v0.21.16 seems to be loading the videos (the comments don't load there, but hey, at least I can still watch videos).

**Comment by OsiPog** [comment]
> Videos with comments disabled seems to be loading OK. If it helps.

Can't confirm, not with disabling comments in settings nor with videos with disabled comments. Still won't load.

**Comment by leslie-alldridge** [comment]
Not loading for me

**Comment by CyberaxAnnon** [comment]
Can confirm from foco pro x3 end. 
Video not loading

**Comment by Stypox** [comment]
#8880 is on the way, can you confirm that this APK fixes the issue? It is a release APK, and it is signed with my keys.

[app-release.zip](https://github.com/TeamNewPipe/NewPipe/files/9422940/app-release.zip)

**Comment by worldpoop** [comment]
Once a again, Newpipe Legacy (.20.) is working, 23.2 is spinning.

**Comment by Dzordzu** [comment]
Yep. It's working for me

**Comment by leslie-alldridge** [comment]
Works great ty

**Comment by worldpoop** [comment]
Moto Android 11 -- thank you!

**Comment by ColeWunderlich** [comment]
@Stypox Working on Note 9 android 10

**Comment by LunaDragofelis** [comment]
Xiaomi Redmi Note 11 S, Android 11 (MIUI 13): works fine

**Comment by laltroweb** [comment]
0.23.3 work as expected here (OnePlus 6 with A12.1 CR) 🙂

**Comment by Stypox** [comment]
Finally [release v0.23.0](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.23.3) is out! Either download the apk from there or update using our custom repo. The APK on the official F-Droid repo will be available later, as it takes some time for them to build the app and deliver the new version. For more information see https://github.com/TeamNewPipe/NewPipe#installation-and-updates. Thank you to everyone involved in solving this issue!
