### ISSUE TITLE
Every video stuck at buffering after loading comments. 

### ISSUE THREAD

**Issue by zaved707** [TeamNewPipe/NewPipe#8879]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

Go to any video you will see a red circle buffering in below the main video panel after which the comments will load which is normal but after that the buffering continues and the video doesn't starts loading. 
![Uploading Screenshot_2022-08-25-10-29-57-224_org.schabi.newpipe.jpg…]()

### Expected behavior

A few seconds After the loading of the comments i expect a white loading circle in the video panel after which the video starts. 

### Affected Android/Custom ROM version

Miui 13 android 11

### Affected device model

Redmi note 11

**Comment by codetalker101** [comment]
Duplicate #8876

**Comment by Master2050** [comment]
Having same issue, [debug build by @Theta-Dev](https://github.com/TeamNewPipe/NewPipe/files/9387795/app-debug.zip) in https://github.com/TeamNewPipe/NewPipe/issues/8839 seems to have fixed the issue.
