### ISSUE TITLE
What to do with NotificationUtils?

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#8891]
From the OP:

> Maybe we could merge it with NotificationUtil? Tell me what you think

This might have been addressed in the review comments, but just in case it wasn't, I'm leaving this here for future reference.

_Originally posted by @opusforlife2 in https://github.com/TeamNewPipe/NewPipe/issues/8170#issuecomment-1228887994_

**Comment by Stypox** [comment]
I think this does not need its own issue. Just put it into the things-to-be-refactored-of-the-player issue

**Comment by opusforlife2** [comment]
Added.
