### ISSUE TITLE
Videos are not played 

### ISSUE THREAD

**Issue by Suncatcher** [TeamNewPipe/NewPipe#8896]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Open the app
2. Tap any video
3. No playing 

### Expected behavior

Playing the video

### Actual behavior

Black screen

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/6388034/187063589-2c51388c-acbc-4869-856e-0b6986761c95.mp4

### Affected Android/Custom ROM version

Android 12 / OxygenOS, build number IN2015_11_C.33

### Affected device model

OnePlus 8

### Additional information

this happens both on wifi and mobile data

**Comment by MDP43140** [comment]
Are you sure that you use "latest version"? there is a new version of NewPipe (0.23.3) that fixes this bug
https://github.com/TeamNewPipe/NewPipe/releases

**Comment by Suncatcher** [comment]
>> Are you sure that you use "latest version"? there is a new version of NewPipe (0.23.3) that fixes this bug

yep, solved with the last version. BTW the version in the F-Droid is still 0.23.2
