### ISSUE TITLE
I can't import subscriptions .jason from freetube windows.

### ISSUE THREAD

**Issue by flaviofrc** [TeamNewPipe/NewPipe#8900]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1 configurations
2 content
3 import database

### Expected behavior

recognize the subscriptions.jason and import subscritons.

### Actual behavior

cant select subscriptions.jason on file explorer.

### Screenshots/Screen recordings

![freetube export](https://user-images.githubusercontent.com/43420662/187085946-3a578f7c-d3c6-4651-89ec-3cd64edbbdce.png)
<img alt="freetube" src="https://user-images.githubusercontent.com/43420662/187085953-3fe24a2c-8b14-4003-b653-f41b68101d76.png" height=600 />

### Affected Android/Custom ROM version

android 8.1

**Comment by opusforlife2** [comment]
That's because the file extension is "json", not "jason".

**Comment by flaviofrc** [comment]
![image](https://user-images.githubusercontent.com/43420662/187773351-a7909c13-edb4-4e9b-8480-27e7e5641d23.png)
the file extesion is .json

**Comment by opusforlife2** [comment]
Ah, a couple of things:
- You can try Material Files from F-Droid, and see if the JSON file is selectable.
- We don't support importing subscriptions from Freetube as of yet.
