### ISSUE TITLE
Bug info video

### ISSUE THREAD

**Issue by Jeiel17** [TeamNewPipe/NewPipe#8907]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

During the dowload of a video I tried to access more information about. Then there was the error reported by NewPipe.

### Logs

```
{"user_action":"play stream","request":"Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=0UxtgXrAQt0","content_language":"pt-BR","content_country":"BR","app_language":"pt_BR","service":"YouTube","package":"org.schabi.newpipe","version":"0.23.3","os":"Linux motorola/sofiar_retail/sofiar:11/RPE31.Q4U-47-35/0edbf:user/release-keys 11 - 30","time":"2022-08-29 11:44","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(136, null, null, video/avc, avc1.64001F, 1739420, null, [1280, 582, 30.0], [-1, -1]), format_supported=YES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:250)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(136, null, null, video/avc, avc1.64001F, 1739420, null, [1280, 582, 30.0], [-1, -1])\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1017)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437)\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)\n\t... 3 more\nCaused by: android.media.MediaCodec$CodecException: Error 0xffffffed\n\tat android.media.MediaCodec.native_configure(Native Method)\n\tat android.media.MediaCodec.configure(MediaCodec.java:2127)\n\tat android.media.MediaCodec.configure(MediaCodec.java:2043)\n\tat com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)\n\tat com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:130)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1095)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1006)\n\t... 10 more\n"],"user_comment":""}
```

### Affected Android/Custom ROM version

Android 11

### Affected device model

Motorola G8 power

**Comment by opusforlife2** [comment]
> During the dowload of a video I tried to access more information about.

Sorry, this is not clear at all. Please provide more details.

**Comment by Jeiel17** [comment]
> > During the dowload of a video I tried to access more information about.
> 
> Sorry, this is not clear at all. Please provide more details.

Sorry. When downloading a video... When clicking on the notification for more information about the Download, it simply generates a small problem that I am unaware of.

**Comment by opusforlife2** [comment]
I see. Please post a screenrecord.

**Comment by Jeiel17** [comment]
> I see. Please post a screenrecord.

I am no longer able to reproduce the problem. I will close this case. In the next bug reports that I find I will expose more information to facilitate the side of you.
