### ISSUE TITLE
Initial buffer takes ages to complete

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#8911]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3 - 0.24.0

### Steps to reproduce the bug

1. Open "https://www.youtube.com/watch?v=P99qJGrPNLs"
2. Wait for it to load (using WiFi, mobile data gives random results)
3. Wait. Video usually takes 10-15 seconds to even start playing, net traffic never exceeds 500kb/s. Video also buffers a while after just 10-20 seconds playtime (again, never exceeding 100kb/s of traffic)

Note: This does not affect most videos. The early videos on Cyberpunk 2077 channel for example consistently show this behaviour.

### Expected behavior

Video should load within 1s like in previous versions and should not have to stop to buffer in new data.

The app should also use full available bandwidth (20mb/s in my case), and not a measly 100kb/s.

### Actual behavior

Video takes up to 15 seconds for initial buffer to complete.

App is not using full bandwidth (100kb/s out of 20mb/s)

### Affected Android/Custom ROM version

Android 11

### Affected device model

OnePlus Nord 2

**Comment by Eiion** [comment]
I'm having the same issue since yesterday's afternoon. I wanted to wait for at least a day with reporting the issue to avoid it just being temporary server issues. But since the problem still exists...
It appears to be the same issue I had reported for last version at #8839.
