### ISSUE TITLE
Download in more places?

### ISSUE THREAD

**Issue by anoraktrend** [TeamNewPipe/NewPipe#8918]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Allow us to download videos without having to open the video info page, IE in the long press menu or via downloading playlists.

### Why do you want this feature?

Currently, long pressing on a video doesn't allow you to download it in that menu, nor can you download an entire playlist of videos (either would work for the following effect). This would allow me to make better use of the download feature. 

### Additional information

Unless there is a fundamental reason this feature cannot be, I do not understand why it's either not implemented already or that no one has asked for it.

**Comment by SameenAhnaf** [comment]
Already expected to be added in v0.24.0. Try the APK in https://github.com/TeamNewPipe/NewPipe/issues/8890
