### ISSUE TITLE
Using some other player?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#8925]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

* Why don't newpipe use some external player similar to how the the newpipe extractor logic is a separate thing? 
* As the newpipe player seems to be a huge undertaking and requiring lots of maintenance
* separating it as a separate "thing", the player would have more surface of getting improvements 
* and would make newpipe more flexible as in some other player could be easily used if the user so wants, and the newpipe player can also be used in other ways if the user so wants

**Comment by opusforlife2** [comment]
We do use a separate player - Exoplayer. Apart from that, there are in-app toggles to play a video with another app, too.

**Comment by yashpalgoyal1304** [comment]
> there are in-app toggles to play a video with another app, too.

sorry, totally forgot about that

> exoplayer

so, umh, why do the blogs say the player code etc etc ?? and what does the player code in newpipe do then?

**Comment by opusforlife2** [comment]
Exoplayer is a library. If you just import it into your project, that by itself does nothing. It is meant to be used by you, by writing code to access its offered functions. It's a very large project offering several features, which you have to decide on using or avoiding.

As a contrast, Auxio (https://www.f-droid.org/en/packages/org.oxycblt.auxio/) is a music player that is also based on Exoplayer. But its actual player code is bound to be very different from Newpipe's, as you can imagine.
