### ISSUE TITLE
library for subscription pages?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#8928]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

* i have seen the same style of the subscription pages in many unofficial clients of various services 
* like [newpipe] (for youtube and others), [fritter] for twitter, 
* and there probably would be others too like for pixiv, reddit, instagram, and others
* so, i was wondering that is that a library?

[newpipe]: https://f-droid.org/packages/org.schabi.newpipe
[fritter]: https://f-droid.org/packages/com.jonjomckay.fritter

**Comment by opusforlife2** [comment]
Such questions are better asked in the IRC, where devs can see it. It can get lost among GH issues.

**Comment by TobiGr** [comment]
We did not use a library for the subscription pages, neither did fritter. Fritter is programmed using [dart](https://dart.dev) - a different programming language which is not compatible with Java. They say that they tried to replicate NewPipe subscription UI in their readme. In case there are other devs who'd also like to use the design, we could discuss whether it is possible and worth the effort to extract the code into a separate library. But for now, there does not seem to be any reason to do that.

**Comment by yashpalgoyal1304** [comment]
> ... they tried to replicate NewPipe subscription UI ... 
> In case there are other devs ..., we could discuss ... to extract the code into a separate library. But for now, there does not seem to be any reason to do that.

okay, nice to know. thanks for the info. This can be closed from my side for now.
