### ISSUE TITLE
Landscape mode does not work properly

### ISSUE THREAD

**Issue by MD-Box** [TeamNewPipe/NewPipe#8931]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Start Movie
2. Start Landscape mode

Bug = Oneplus User? 

https://user-images.githubusercontent.com/85779968/188317165-6d3ccc8e-88c4-47af-a3c5-237c6078bd71.mp4

### Expected behavior

_Fullscreen Mode_

### Actual behavior

_Smallscreen_

### Affected Android/Custom ROM version

Android 12

### Affected device model

Oneplus 9 pro

**Comment by Nqtural** [comment]
Can confirm this also happens on the Samsung Galaxy S20 FE 5G running Android 12, OneUI 4.0.
