### ISSUE TITLE
Export NewPipe playlist to YouTube

### ISSUE THREAD

**Issue by sobornostea** [TeamNewPipe/NewPipe#8932]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hello !

The app could be able to export NewPipe internal playlist to YouTube (for example a share button in the playlist screen that opens a YT link in the browser/YT app). I've managed to do that manually (without using the YT API of course)

### Why do you want this feature?

It is quite convenient to share playlists with your computer/people that don't use newpipe >:(/people that don't want to go through the hassle of manipulating the databases

### Additional information

I've managed to do that manually from a db export, here's how I did :

* I got all the URLs from the playlist in the db export (simple SQLs manipulation)
* I extracted the ids `?v` in the URL
* I then added them all to this URL as a comma separated list :
`https://www.youtube.com/watch_videos?video_ids=id1,id2,id3,[...],idn`
* Opening this URL leads me to the playlist

I have limited Java proficiency, but I'll be interested in implementing this feature given some help.

**Comment by opusforlife2** [comment]
Have you seen #8542? You can test it using the current RC.

**Comment by NSTAdventure** [comment]
Hi newpipe developer it's could be nice
If you want to import playlist via csv file
(Google takeout file format)
I can provide sample file if needed

**Comment by nlof** [comment]
It would be awesome if someone would implement this feature. 
#8542 is very cumbersome to use for this purpose, it outputs a list of url's that requires additional complex processing to be able to import it as YouTube playlist. It really shouldn't be that complicated...

**Comment by aerickt** [comment]
Seeing that NewPipe still doesn't have a way to export playlists to a YouTube playlist link, I've created a script to help with this.

1. Install termux and termux-api from F-Droid.
2. Run `pkg install termux-api` in F-Droid
3. Create the following script in `~/.shortcuts/` (name it however you want, make sure it is executable):

```
#!/bin/bash
videos=$(termux-clipboard-get)
ids=$(echo "$videos" | grep -o 'v=.*' | cut -f2 -d"="| tr '\n' ',')
playlistLink="http://www.youtube.com/watch_videos?video_ids=$ids"
termux-clipboard-set "$playlistLink"
```

You can pin this script as a Termux widget to your home screen.

To use this, copy the video links NewPipe gives you (when pressing share). Run the scrip above, and you should now have a YouTube playlist link in your clipboard.
