### ISSUE TITLE
Popping noise at start and end of Soundcloud and Bandcamp songs

### ISSUE THREAD

**Issue by pouek** [TeamNewPipe/NewPipe#8938]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Go to any soundcloud or bandcamp link
2. Listen song from start to end
3. There is a popping noise at start and end of stream at each time

### Expected behavior

I expect no noise when I listen a stream 

### Actual behavior

The popping noise occurs just before the file plays and just after it has played

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Galaxy S5

**Comment by opusforlife2** [comment]
Can't reproduce this. Try another device.
