### ISSUE TITLE
Import/Export Bookmarks 

### ISSUE THREAD

**Issue by raavimohindar** [TeamNewPipe/NewPipe#8940]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Export and Import bookmarks. Holding on the bookmark item should give a option to import bookmarks from a file or export to a file.

### Why do you want this feature?

This feature would enable to use my bookmarks if I switch devices. Or backup in case a factory rest is done.

**Comment by opusforlife2** [comment]
Why not use the import/export database feature?

**Comment by raavimohindar** [comment]
Thanks
