### ISSUE TITLE
Data usage incoherence for background player

### ISSUE THREAD

**Issue by AbouRabou** [TeamNewPipe/NewPipe#8943]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

Make sure that those setting in this application are set :
Video and audio : 
-> Default resolution : 144p
-> Default popup resolution : 144p
-> Limit resolution when using mobile data  : 144p

1- On youtube, find a 2hour video.
2- Share it with newpipe(0.23.3), newpipe legacy(0.20.8) or newpipe delivery-methods-v2(0.23.0)
3- Listen to the complete video in backgroud

### Expected behavior

I expect a data usage of about 150MB(with network overhead).

### Actual behavior

Data usage of 810MB.

### Affected Android/Custom ROM version

Android version 10

### Affected device model

Huawei P30 Pro

### Additional information

I compared the same time for data usage to listening a video on Netflix... 2hour video listening on Netflix is 450MB.
I expect audio to be below that the data usage of video for the same time range.

Tried to download the video using newpipe : 
- audio 160kbps = 115MB
- video, 3gpp 140p = 67.29MB
- video, WebM 480p = 561.77MB
- video, mpeg-4 720p = 734.49MB
- video, WebM 1080p = 1.52 GB

It is my comprehension that new pipe take the best audio format available.
But, it either seen like it is deliberately choosing video 720p as audio even though my setting are set to be 140p
Or, that youtube is providing 720p video stream even though the newpipe is asking for 140p like the config was set too.

If there is something akin statistics for nerds that i can provide included in the application, say, and ill redo my test appropriately.

**Comment by opusforlife2** [comment]
Try with 4k/2k/1080p, instead, using 0.24.1.

**Comment by AbouRabou** [comment]
Will do...
Coming back with the result when I have them.
