### ISSUE TITLE
New broken behavior of downloading each mp3 to own subfolder

### ISSUE THREAD

**Issue by degarb** [TeamNewPipe/NewPipe#8947]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

All of the sudden NewPipe is not downloading the mp3s into the NewPipe folder without burying the mp3 I  a sub folder.   I do not see any settings related to this.   The files are not playable in any batch format with being buried,  I can only play one file at a time.   And must spend 20 minutes rooting up the files before taking my lectures to work to listen to.

**Comment by opusforlife2** [comment]
Newpipe doesn't download mp3 files at all. Could you please check if you're using the authentic app? We only release through F-Droid and Github.
