### ISSUE TITLE
No resume power 

### ISSUE THREAD

**Issue by KalpanaChetan** [TeamNewPipe/NewPipe#8954]
### Checklist

- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [ ] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [ ] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [ ] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [ ] This issue contains only one feature request.
- [ ] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

If internet connection is lost all download progress is lost

### Why do you want this feature?

Waste of time 
Waste of data

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/8908#issuecomment-1233362845
