### ISSUE TITLE
113.71 % download 

### ISSUE THREAD

**Issue by KalpanaChetan** [TeamNewPipe/NewPipe#8956]
### Checklist

- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [ ] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [ ] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [ ] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

![IMG_20220825_044446](https://user-images.githubusercontent.com/112402936/189512855-b2d9ce71-825b-4869-9c9b-c8ac3149d1ca.jpg)

113.71 % download why ?

### Additional information

it is bug or other problem
this problem happened once or twice

There may be a problem with my mobile

**Comment by KalpanaChetan** [comment]
![Uploading IMG_20220825_044446.jpg…]()

**Comment by KalpanaChetan** [comment]
![IMG_20220825_044446](https://user-images.githubusercontent.com/112402936/189513070-ed559e25-fd6b-4729-866d-0ec67bd0a802.jpg)

**Comment by opusforlife2** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/8908#issuecomment-1233362845
