### ISSUE TITLE
Fix the player UX

### ISSUE THREAD

**Issue by goyalyashpal** [TeamNewPipe/NewPipe#8958]
### Checklist

<details>

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

</details>

### Problem

* The player UX is very inconsistent 
* accomplishing same task requires completely different actions 
* and same actions does completely different tasks (like: click on an item, or click and hold on an item)

<table>
    <tr>
        <td></td>
        <th>Open Video Details</th>
        <th>Switch playing mode</th>
        <th>Other</th>
    </tr>
        <th>Search results list</th>
        <td>Click an item</td>
        <td>Click & hold on an item</td>
        <td></td>
    <tr>
    <tr>
        <th>Player queue UI</th>
        <td>Click & hold <br/>on an item</td>
        <td>Click on UI's 3 dots</td>
        <td>Click an item: <br/>plays it from start</td>
    </tr>
    <tr>
        <th>Video details <br/>(playing in bg mode)</th>
        <td><i>Not ap-<br/>plicable<i></td>
        <td>Go to play queue UI via <br/>notification, then do as above</td>
        <td>Click play button: <br/>replaces active player queue  <br/>& plays from some random position</td>
    </tr>
</table>

<details>

<summary>
Non-tabular format:
</summary>

<br/>

**Search results list UI:**
* Click the list item to go to video details
* Click and Hold list item for selecting the modes

**Play queue UI:**
* Click on the list item to play it from start
* Click and hold on the list item to go to video details
* Click the UI's 3-dot menu to switch to modes

**Video details and playing in bg mode:**
* Click the player --> will replace the active player queue (ofc when there're multiple queue items) and will start playing from who knows from where
* So, to switch mode, first go to play queue UI via the notification, then click 3-dot menu from there

</details>

### Proposed Solution

pending - ugh, i don't know how to create mockups :(

### Additional information

<details>

* https://github.com/TeamNewPipe/NewPipe/issues/4414
* https://github.com/TeamNewPipe/NewPipe/pull/7194
* https://github.com/TeamNewPipe/NewPipe/issues/3515
* 🔍 : [ux](https://github.com/TeamNewPipe/NewPipe/issues?q=ux)

</details>

~~For now, i am filling this issue only for myself. i will add the details later. please don't do any action (like label, or lock etc) on it yet.~~

**Comment by opusforlife2** [comment]
When I have an incomplete issue that I'm waiting for more info on, I keep it locally in a text file. Every time you make an edit to this, you will send out notifications to everyone who's watching this repo.

**Comment by yashpalgoyal1304** [comment]
i didnt know about that notifs are sent for edits too, i thought they are
sent only on new comments. sorry.

i too generally note the stuff in local file, but this one is related with
some issues already filed... so, thats why i made this mistake of filling
it here.

opusforlife2 wrote:

> Every time you make an edit to this, you will send out notifications to
> everyone who's watching this repo.
>
