### ISSUE TITLE
Notification for playlist update

### ISSUE THREAD

**Issue by xmha97** [TeamNewPipe/NewPipe#8969]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like to receive a notification when a specific playlist is updated.

### Why do you want this feature?

There is a TV program that is published on YouTube and I want to follow this program. But since I am not interested in other programs of this network, I don't want to follow his channel.
I have bookmarked this tv show playlist now but I want to be notification when a new episode is added.
<img alt="Screenshot_2022-09-14-01-57-47-151_org schabi newpipe" src="https://user-images.githubusercontent.com/23485114/190014990-a5e79a8a-ec0e-4b14-acb0-5e8e9e76e308.jpg" height=600 />

**Comment by opusforlife2** [comment]
#3525 could solve your problem, no?

**Comment by xmha97** [comment]
> #3525 could solve your problem, no?

Is this your solution? https://github.com/TeamNewPipe/NewPipe/issues/3525#issuecomment-798451112
I don't want to use another app (feed reader)

**Comment by opusforlife2** [comment]
No, I linked to the entire issue, not that specific comment. Generally, that means a reference to the issue title and description.
