### ISSUE TITLE
Switch YouTube audio track

### ISSUE THREAD

**Issue by ivadham** [TeamNewPipe/NewPipe#8976]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

I have been watching [AC Mirage: Cinematic World Premiere](https://www.youtube.com/watch?v=x55lAlFtXmw) via NewPipe and it plays "English descriptive" as default audio track. It even downloads the video with English descriptive audio track without any question as if there is no other audio track available.

Is there a switch audio track feature in NewPipe that I am unaware of?

**Comment by Aquilux** [comment]
I would argue either against closing this as a bug or for adding the bug tag to the referenced "duplicate" as having videos play in a dubbed language you can not understand without having any control over it is not intended functionality and stopping that from happening is decidedly more significant than just requesting a nice new feature.

**Comment by GameOverFlowChart** [comment]
> > stopping that from happening
> 
> No one's stopping anything. If you have the know-how, you're welcome to open a PR.

Your need to read that sentence again, actually you won't understand after reading it again so I have to tell you that your two sentences contradict each other. By stopping that from happening Aquilux means fixing that problem. So how should Aquilux fix it at the same time if nobody fixes anything (and yes, what you don't understand is that in this context stopping and fixing is interchangeable, you literally said that nobody is fixing anything). Don't get me wrong, I don't expect you to understand it but it won't be fair towards Aquilux if I won't say anything.
