### ISSUE TITLE
Import of subscription JSON from previous version NewPipe

### ISSUE THREAD

**Issue by Gelip** [TeamNewPipe/NewPipe#8977]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

OS Android 6.0.1

When I try to import subscriptions from the JSON file, the system explorer opens but I can't open the JSON file - it's not available:
![android6](https://user-images.githubusercontent.com/16385203/190336346-e2e3485e-58c8-4586-b449-4c188a15e25f.png)

**Comment by Gelip** [comment]
I found a workaround problem by installing the Material Files app:
[https://github.com/TeamNewPipe/NewPipe/issues/7326](url)

P.S. Why does NewPipe use a hidden file manager (com.android.documentsui) instead of the default in the system?

**Comment by Gelip** [comment]
I installed an UnHideDocumentsUI.apk [https://forum.xda-developers.com/t/unhide-documentsui-google-aosp-files-android-6-0-no-root.4482855/](url) and json file is available but when the file manager is launched via NewPipe, the json file is unavailable:
![unhided](https://user-images.githubusercontent.com/16385203/190486090-2d35f740-80be-49e2-976d-3fd56d64fc61.png) ![from_NewPipe](https://user-images.githubusercontent.com/16385203/190486111-f9473f34-9757-4471-9846-8370c3b4f8c8.png)

**Comment by opusforlife2** [comment]
> Why does NewPipe use a hidden file manager (com.android.documentsui) instead of the default in the system?

That _is_ the default file manager that Android wants us to use. Newpipe simply requests file access through SAF, and Android opens this system app in response. Either you or your custom ROM has changed the default OS file manager.

Regarding your comment above, the behavior of that APK is unknown to us. You're better off using Material Files in general as your SAF provider.
