### ISSUE TITLE
Video plays in foreign language not English

### ISSUE THREAD

**Issue by javierxio** [TeamNewPipe/NewPipe#8978]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Go to https://www.youtube.com/watch?v=65fN_OUawjk

### Expected behavior

Video should play in English

### Actual behavior

Video plays in foreign language (dubbed)

**Comment by javierxio** [comment]
@AudricV what's the solution? Where is this duplicated?

**Comment by mhmdanas** [comment]
This is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5854.
