### ISSUE TITLE
Option to pin playlist

### ISSUE THREAD

**Issue by laraib07** [TeamNewPipe/NewPipe#8979]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Option to pin a playlist in bookmarked playlist so that it is visible on the top. This will give users freedom to add some labelled bookmarks like Watch later, favourite, etc 

### Why do you want this feature?

To avoid having to search through countless playlists every time, I want to pin my Watch later playlist.

**Comment by Shadow-302** [comment]
For now, you can just name the playlist 
'1. Watchlater'. That way it will be on top.
