### ISSUE TITLE
How can I change a previous selected external player?

### ISSUE THREAD

**Issue by pietbus** [TeamNewPipe/NewPipe#8989]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

How can I change a previous selected external player?

**Comment by opusforlife2** [comment]
You'll have to clear the 'open by default' setting for that external player. Sadly, Android doesn't let you clear specific defaults. There is only that global button for clearing all defaults.
