### ISSUE TITLE
Disabling button and count

### ISSUE THREAD

**Issue by NSTAdventure** [TeamNewPipe/NewPipe#8990]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I have idea how about add option to disable all counts, like and search button?

### Why do you want this feature?

1. Annoying, causing distraction and addiction to user experience 
2. Useless since you cannot press like without account for example

### Additional information
I just want to watch YouTube free without distraction and such 🥴

**Comment by opusforlife2** [comment]
> without any coercion from any party.

Wot

**Comment by MDP43140** [comment]
> without any coercion from any party
did you mean "without any bias from any party"?

**Comment by opusforlife2** [comment]
We don't even _have_ a dislike button or dislike count. Please clarify what you're asking for.

**Comment by NSTAdventure** [comment]
> We don't even _have_ a dislike button or dislike count. Please clarify what you're asking for.

![Screenshot_2022-09-18-18-07-41-65_1](https://user-images.githubusercontent.com/50813528/190899110-8b3bf98f-47e8-4fe4-8a85-0dc34fb93545.jpg)
![Screenshot_2022-09-18-18-07-50-36_1](https://user-images.githubusercontent.com/50813528/190899113-baae397a-724d-41bf-a5bb-9abaf66dac16.jpg)


71K and 1 like is counter
And respective button is also still there

**Comment by NSTAdventure** [comment]
> > without any coercion from any party
> 
> did you mean `without any bias from any party`?

Yes something like that sir
That's my own idea since i find this distracting and super annoying 🙏🥴🤦

**Comment by opusforlife2** [comment]
It's a strange thing to mention, that's all. We don't have any reason to believe that the creators of any of our current issues were forced to do that by other people.

**Comment by opusforlife2** [comment]
Please modify your description to clearly state that you would like an option for the Like button to be removed. And make sure to remove any unneeded information.

**Comment by NSTAdventure** [comment]
> Please modify your description to clearly state that you would like an option for the Like button to be removed. And make sure to remove any unneeded information.

Yes sir it's done 🙏

**Comment by NSTAdventure** [comment]
> It's a strange thing to mention, that's all. We don't have any reason to believe that the creators of any of our current issues were forced to do that by other people.

I see 
Okay those strange mention that you guys talk about is removed 
Pls consider to delete or hide those strange mention topic reply or msg 
I hide mine 

Thanks 🙏

**Comment by opusforlife2** [comment]
Thanks. Make sure to also change the title of your issue the same way.

**Comment by NSTAdventure** [comment]
> Thanks. Make sure to also change the title of your issue the same way.

Yes and a quick heads up i added new button that should disabled or at least have option to disable
(Search button)

**Comment by opusforlife2** [comment]
> Yes

You didn't, though.

**Comment by NSTAdventure** [comment]
> > Yes
> 
> You didn't, though.

Bruh i confused as hell to choose right title for this issues even i tried my best 🥴
I hope i did right this time 🥴

**Comment by opusforlife2** [comment]
Disabling _which_ button? There are dozens of buttons in Newpipe.

**Comment by NSTAdventure** [comment]
> > We don't even _have_ a dislike button or dislike count. Please clarify what you're asking for.
> 
> <img alt="Screenshot_2022-09-18-18-07-41-65_1" src="https://user-images.githubusercontent.com/50813528/190899110-8b3bf98f-47e8-4fe4-8a85-0dc34fb93545.jpg" height=600 />
> <img alt="Screenshot_2022-09-18-18-07-50-36_1" src="https://user-images.githubusercontent.com/50813528/190899113-baae397a-724d-41bf-a5bb-9abaf66dac16.jpg" height=600 />
> 
> 
> 71K and 1 like is counter
> And only like button is also still there
> (Sorry i forgot if dislike are removed  🙏😅)

This one sir @opusforlife2

**Comment by opusforlife2** [comment]
Sigh.

**Comment by opusforlife2** [comment]
> and search button?

What about this?

You know what, I'm closing this issue. It's clearly not following the "one request per issue" requirement anyway.

You can open separate issues for each thing. Like button and view counts, and whatever it is regarding the search button. They may be fixed separately by different persons.

**Comment by NSTAdventure** [comment]
> > and search button?
> 
> What about this?
> You know what, I'm closing this issue. It's clearly not following the "one request per issue" requirement anyway.

Hello developer my apologies for this inconvenience previously i might misunderstand whole story here but now i understand it
Now i already fix the issues to meet all requirements as possible 

Thanks 🙏
