### ISSUE TITLE
navigation gesture not working after video go landscape

### ISSUE THREAD

**Issue by privacyonly** [TeamNewPipe/NewPipe#8991]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. use gesture mode instead of navigation bar
2. turn off auto rotate
3. play any video, press fullscreen and go landscape mode
4. now try gesture

### Expected behavior

1. the navigation pill should be at the bottom of the screen and we can use it to go to the main screen or multitask.
2. if we swipe the right to left side of the screen or vice versa we should be able to go back

### Actual behavior

1. navigation pill is at the right side of screen and do nothing
2. swiping right to left or vice versa do nothing
3. the only way to go back is to activate auto rotate or press the fullscreen button again.

### Affected Android/Custom ROM version

Android 13 OneUI 5.0 beta

### Affected device model

S21 ultra SM-G998B

**Comment by privacyonly** [comment]
I will add more information now,

1. navigation bar works as expected, only gesture is the problem(I have never tried this with android 12, but I have other samsung phone in my house so I may be able to test this later)
2. multitask screen will only work if oneuihome apk is enabled(may not be related)

**Comment by opusforlife2** [comment]
> so I may be able to test this later

Please do.

**Comment by privacyonly** [comment]
everything is normal with samsung note 10 android 12 oneui 4.1, by normal I mean gesture works.

**Comment by opusforlife2** [comment]
Then let's wait for your beta ROM to become stable.

**Comment by privacyonly** [comment]
problem doesn't exist with one ui 5 beta 2 on s21 ultra and newpipe 0.24.0 rc3
