### ISSUE TITLE
Playlist 100 video limit 🥴

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#8998]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Why add local playlist from online (channel) feature only support 100 videos?
I try to create local playlist from channel that's have more than 100 video on their playlist
But only 100 video are added 

### Additional information

I use latest newpipe version from f droid repository
0.23.3 
And it's official version not fork version 
Another strange thing is i still can add more video in respective playlist so this is are add playlist bug?
Where is playlist from channel?
Now it's lost in the void there is nothing that i can do i also forgot to take screenshot so only local playlist on newpipe existed 
I apologize for this inconvenience 🙏

**Comment by opusforlife2** [comment]
You can follow #875 as it has the same root cause.
