### ISSUE TITLE
[Bug/Feature Request] Changed Home page to something besides Trending keeps a trending icon in Tabs

### ISSUE THREAD

**Issue by SudoLinux** [TeamNewPipe/NewPipe#900]
This one is most likely not a bug, somewhat a feature request, but the icon, that shows in the 2 tabs on NewPipe, the first tab after update was showing Trending on YouTube tab, you can change that but it you look at the tab bar, it still shows a Trending icon. I'm not sure of this is one of those things that was "forgotten" while in implementation... But if you ever need something to fix, here is something, based on choice (say user chooses to show a channel on main page), make a little tab icon that reminds that user of a channel icon. No affect on user whatsoever, but could clean it up a bit if developer runs out of fix ideas...

**Comment by tleydxdy** [comment]
let users choose more than two tab would be nice

**Comment by speednroll** [comment]
@tleydxdy I think I made a similar issue very recently

**Comment by SudoLinux** [comment]
@tleydxdy request it

**Comment by speednroll** [comment]
@SudoLinux What is the point of asking twice for the same thing? before I pass the request that I have made. I do not know if it was taken into account
