### ISSUE TITLE
Open download screen when WiFi and mobile data turned off

### ISSUE THREAD

**Issue by xmha97** [TeamNewPipe/NewPipe#9001]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Open download screen when WiFi and mobile data turned off

### Why do you want this feature?

Faster access to content

**Comment by opusforlife2** [comment]
Are you talking about the Downloads page where past downloads show, or the download dialogue which lets you download new stuff?

**Comment by coding-dynasty** [comment]
he wants to say that if you dont have internet connection the downloded videos page should be displayed automatically not the main page which there is no reason for showing it while offline at all.

**Comment by xmha97** [comment]
> he wants to say that if you dont have internet connection the downloded videos page should be displayed automatically not the main page which there is no reason for showing it while offline at all.

Yes, this is what I want.

**Comment by opusforlife2** [comment]
... okay. How about opening the downloaded folder directly in a media player app, since you already know your internet is off? It's not like Newpipe can play those downloads.
