### ISSUE TITLE
No new videos in feed or channel preview from some channels

### ISSUE THREAD

**Issue by 3dde** [TeamNewPipe/NewPipe#9005]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Visit a channel (e.g. Linus Tech Tips in my case)
2. Scroll all the way up to see the newest videos

OR

1. Subscribe to a new channel
2. Refresh feed

### Expected behavior

The newest videos should appear at the top of the channel page or in the feed

### Actual behavior

On the channel page, the newest video is from 2 days ago, although on YouTube, there are newer videos. In the feed there is the same problem.

### Screenshots/Screen recordings

<img alt="Screenshot" src="https://user-images.githubusercontent.com/73657699/191596448-66883faf-4960-4a96-b1c9-7c4991a7c7ac.png" height=600 />

### Affected Android/Custom ROM version

Android 10

### Affected device model

Motorola Moto G7

### Additional information

This bug seems to affect only some channels. So far, I have identified "Linus Tech Tips" and "JOLLY" as affected channels.

**Comment by 3dde** [comment]
Nvm, seems to be an issue with my dns provider. Switching my dns to my ISP's or Google's fixed the issue.

**Comment by opusforlife2** [comment]
So... close the issue, then?
