### ISSUE TITLE
[Bug] 11.1 Network error channels.

### ISSUE THREAD

**Issue by Duppadaadadii** [TeamNewPipe/NewPipe#901]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

-When i search for channels to subscribe and try to press that channel it says network error and keeps doing that forever until i quit from it.

-Second thing i noticed was that i can't see translations in Weblate for the new threedot submenu for toggle orientation etc.

**Comment by r2308145** [comment]
Same problem here.

**Comment by theScrabi** [comment]
Shame on me, I released this version with a bug. Url and name for a channel where swopped. I fix this asap.

**Comment by theScrabi** [comment]
Fixed. Please redownload v0.11.1 from github
