### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by Chex07** [TeamNewPipe/NewPipe#9017]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

Failed to resolve: com.github.TeamNewPipe:NewPipeExtractor:6a858368c86bc9a55abee586eb6c733e86c26b97
Show in Project Structure dialog
Affected Modules: app
how can i fix ?

### Screenshots/Screen recordings

![Screenshot_3](https://user-images.githubusercontent.com/6298184/192097183-a145e7af-cb7f-4be3-b6d8-b035381e6d33.png)

**Comment by opusforlife2** [comment]
This is not a bug, it's a question about building the app. Please use the correct template and provide proper details.

**Comment by Chex07** [comment]
What should I do ?

**Comment by opusforlife2** [comment]
Use the question template. Provide details about what step of the build process is giving you problems. If possible, provide a screenshot which clearly shows where the problem is happening.
