### ISSUE TITLE
[Bug] 11.1 Popup fullscreen toggle not working.

### ISSUE THREAD

**Issue by Duppadaadadii** [TeamNewPipe/NewPipe#902]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

-Checked the popup window and pressing the upright corner fullscreen button does nothing.

**Comment by analizer2010** [comment]
yes, I found this bug since full screen player has option menu

**Comment by theScrabi** [comment]
confirmed

**Comment by Poilaucul** [comment]
Same.

**Comment by v0idst4r** [comment]
Same problem here. This is quite annoying, hope a fix is coming soon.

**Comment by theScrabi** [comment]
fixed.
Fix will be available with the next version.
