### ISSUE TITLE
No fullscreen possible with AndroidTV

### ISSUE THREAD

**Issue by dolorosus** [TeamNewPipe/NewPipe#9021]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.0

### Steps to reproduce the bug

1) Start any video and try to switch to fullscreen mode results in an error message.
2) No chance to continue the video, 'cause only an remote control is attached, but got no focus to the play button. Only chance is  going back and restart the video which brings us back 1.

Granulations you completely fucked up fullscreen mode on AndroidTV!

### Expected behaviour

Switching to fullscreen (as on 23.xx)

**Comment by AudricV** [comment]
> switch to fullscreen mode results in an error message

Please give us the error report associated with the issue

> Graulations you completly fucked up fullscreen mode!

If you tested the release candidate of this version and you reported it, we may have catched this issue.

**Comment by opusforlife2** [comment]
> Granulations you completely fucked up fullscreen mode on AndroidTV!

Thanks for the love and support. We need more people like you in the world.
