### ISSUE TITLE
Playlist sharing: include video names & playlist name

### ISSUE THREAD

**Issue by thisago** [TeamNewPipe/NewPipe#9025]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

In shared text the video name and playlist name need to be shown.

### Why do you want this feature?

Its very annoying click in all links to find a specific video.

### Additional information

The current feature (that shares just the urls) can be a "Copy to clipboard" button to easy manipulation

But to share to people, just the links is extremely hard to find a video. Like: in 100 videos find a specific video about something.

**Comment by GabbyRichards** [comment]
Hi! I am a first-time contributer to the open source community, and I would love to work on this issue. Can you point me to where the issue is or a place in the source code where I can begin looking?

**Comment by panoreak** [comment]
Hello! I would like to work on this :)

**Comment by Anjali2312-Thombare** [comment]
i am interested in solving this issue

**Comment by Anjali2312-Thombare** [comment]
please assign me this issue

**Comment by snaik20** [comment]
@opusforlife2 Created #10427 because existing PR #9060 appears to have been abandoned for a year. Please review and suggest changes, if needed.
