### ISSUE TITLE
[Bug] 0.11.1 Trending page English

### ISSUE THREAD

**Issue by Duppadaadadii** [TeamNewPipe/NewPipe#903]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

-Trending page shows translation after a while. It first shows Trending in English upleft corner, then changes to user chosen language.

**Comment by r2308145** [comment]
Same problem here.

**Comment by theScrabi** [comment]
Confirmed.

**Comment by theScrabi** [comment]
fixed:
https://github.com/TeamNewPipe/NewPipe/commit/bc7332780de81f720760d8fe5ff5ed2011e0a5a0
