### ISSUE TITLE
Backup subscriptions to google drive

### ISSUE THREAD

**Issue by spectrejs** [TeamNewPipe/NewPipe#9034]
Please add a button to backup my data to google drive, and maybe even automatically sync to it. This will help because I have to subscribe to the same channels on all my devices, its tiresome. Google drive APIs are well documented it can't be that hard, is it? We genuinely need a better backup method.

I tried using LibreTube but NewPipe is just way better, all thats missing is a way to backup my subscriptions. Please help?

**Comment by opusforlife2** [comment]
Hi. We have issue forms that your 3rd party Github app has bypassed. Please use the web interface to fill out a form and create a proper issue.

**Comment by opusforlife2** [comment]
BTW you can export/import your subscriptions through a JSON file from the 3 dot menu on the Subscriptions tab.
