### ISSUE TITLE
Option to reset settings.

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#9036]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Option to reset settings.

### Why do you want this feature?

this is important if someone did something in settings and didn't know how to go back... without the need to clear app data and lose subscription and feed Customizations

### Additional information

this is also especially useful for new users who are trying and learning all the options in the settings

**Comment by opusforlife2** [comment]
Export your database, and then import it. When it asks you if you want to restore settings as well (in the 2nd dialogue), say no.

**Comment by MD77MD** [comment]
that is defiantly not  Intuitive... bro i was not asking for workarounds... i know you are a pro using newpipe... im just making request for essentials that the average user would need in the future... everyday newpipe is growing in functions and features, making it nearly impossible for beginners to experiment without worrying they might not be able to undo them

also it would be appreciated if we could have such discussion befor just closing ... im made the time and effort to creat it so i think I'm the one how should close it if we agreed to do so... 

also closing issues right away denies others the opportunity to give their input ... i think thier should be a fixed period enough to reach fruitful discussion, thus a more complete understanding by incorporating more opinions not just one or two... so yes please reopen this issue so other can discover it and give their feedback 

nevertheless thank you for your efforts maintaining newpipe in github

**Comment by opusforlife2** [comment]
None of that is a problem. Even if I closed this, you were still able to ask me to reopen. Don't consider "closing" of an issue as "final rejection, no changes allowed". These are just maintenance decisions, most of which can be reversed easily.

I marked it as a question after answering because I thought the solution was good enough. Since you want a button anyway, I'll just click on the "reopen" button and go my merry way.

(You're far too emotional about these things :P )

**Comment by plasticanu** [comment]
Hi, we are an assignment group studying computer science at the Australian National University. We would like to work on this issue, and we have 19 days left to write code and open a pull request. Can you assign this issue to us?

**Comment by tsiflimagas** [comment]
Better let team members tell devs they can start working on issues rather than doing it yourself. For example, there hasn't been a verdict whether this feature should make it to the app or not. Perhaps it will, but it could also cost someone wasting his time.

**Comment by cernunnos1710** [comment]
Hello, I am one of the team members with @plasticanu and would like to be assigned to work on it.

**Comment by opusforlife2** [comment]
We can have such a button in the app on an experimental basis, at least. If there is positive feedback for it, it could stay.

Where do you guys intend to put the button? In the top level of Settings or deeper?

**Comment by plasticanu** [comment]
> 

In the top level of settings, at the bottom.

**Comment by opusforlife2** [comment]
Alright. 👍

**Comment by vincetzr** [comment]
Hi there, I am currently working on this issue with @plasticanu and @cern1710. Currently, I have put a reset options within the debug settings fragment and only successfully reset the theme of the app. I realized that the main settings activity calls the settings fragment and I did not want to create a new fragment with it's xml file just to reset settings. Therefore, I put it in the debug settings fragment. My current issue is based on my current understanding is that some of the fragments uses settings file to load the settings but the file is deleted afterwards. I could not find way to load a default when the reset button is clicked every time. I believe if there is a file that saves all the default settings value and a method to initialize those values to each fragment that would solve the issue. Below attached is my current progress on the issue. 
![image](https://user-images.githubusercontent.com/110076924/198281070-00b5d8ee-7048-4744-adf2-fc376f1348b8.png)
![image](https://user-images.githubusercontent.com/110076924/198281165-894dc4ab-c440-41bc-b773-a4fc6467a5d5.png)

**Comment by Stypox** [comment]
@vincetzr adding a button there looks like a good idea for now. What that button should do is to delete the shared preferences XML file and then restart the app. Restarting the app will take care of recreating the shared preferences file with default values, so you don't have to set things manually.

**Comment by vincetzr** [comment]
Hi @Stypox, thank you for your suggestion. I will try and implement that.
