### ISSUE TITLE
v 0.24.0 not importing .csv file of subscriptions

### ISSUE THREAD

**Issue by sanjosanjo** [TeamNewPipe/NewPipe#9043]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

I exported my YouTube subscriptions via Takeout, with only Subscriptions checked.  I extracted the .csv file from the zip file.  
I tried to import the file in the app and it says "Could not import subscriptions".

I verified that the .csv contains only comma delimited text.

### Expected behavior

I was trying to import a .csv file of subscriptions.

### Actual behavior

Error message:
"Could not import subscriptions".

### Affected Android/Custom ROM version

Fire OS 7.2.3.1, which I believe is based on Android 9.0

### Affected device model

Fire HD 10 (9th Generation)

### Additional information

My tablet is updated to allow Google Play store and sideloading.
I can provide the .csv file to anyone interested.

**Comment by sorab2142** [comment]
Can confirm the same issue on Mi Pad 5 - Android 11
