### ISSUE TITLE
Placeholder Variants

### ISSUE THREAD

**Issue by Monstanner** [TeamNewPipe/NewPipe#9044]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

If possible, there should be placeholder variants. For example: If you currently open NewPipe and scroll down, then the thumbnail loads. Instead of the placeholder thumbnail with the play icon, there could be an hourglass to signal that it loads the thumbnail. Or if a video has been deleted, the thumbnail is provided with an X or trash can.

Example thumbnail loads (hourglass):
![Loading Thumbnail](https://user-images.githubusercontent.com/45621250/193050091-cb794fa5-e753-4af2-af1b-508cf1082024.jpg)
Example for deleted video thumbnail (X):
![X Thumbnail](https://user-images.githubusercontent.com/45621250/193049988-78cca143-2877-441d-83d7-6240416b3c76.jpg)
Example for deleted video thumbnail (trash can):
![Trashcan Thumbnail](https://user-images.githubusercontent.com/45621250/193049095-a525bb5c-68a9-4521-83d7-a0d6c60f2b7e.jpg)

### Why do you want this feature?

Currently, there is only one placeholder thumbnail for loading video and when a video has been deleted (play icon). This could lead you to think that the thumbnail is still loading. So you could show that the video has been deleted.

### Additional information

You could also do this for private videos. Also for channel avatars placeholders. But I don't know if the feature request is not already a lot of work and effort. I came up with this idea through the 0.24.0 update. Because at the first start of the version, the thumbnail took a little longer. And so I thought that all videos are deleted or private, because of the placeholder thumbnail.

**Comment by HighGr0und** [comment]
Hi, I would like to solve this issue if possible.

**Comment by opusforlife2** [comment]
@HighGr0und Sure! Could you provide examples of what thumbnails you intend to use?

**Comment by HighGr0und** [comment]
I intend to show the hourglass thumbnails on load and the X thumbnails when there is an error or the URL is empty.

**Comment by opusforlife2** [comment]
@HighGr0und Make sure you post screenshots in your PR.

**Comment by Stypox** [comment]
I am sorry but I think the current way thumbnails are shown is just fine. A thumbnail only really rarely fails to load, and in that case it's clear that the play button means "not found". Showing a contrived placeholder while a thumbnail is loading is also not needed, since thumbnails load really fast. So I am closing this as "won't fix".
