### ISSUE TITLE
audio works, but video does not work in Mediatek Smart TV

### ISSUE THREAD

**Issue by omer-musa-battal** [TeamNewPipe/NewPipe#9048]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Download and install the latest (0.24.0) Newpipe application (I used f-droid).
2. Open any youtube video.

### Expected behavior

Video and audio both play synchronously.

### Actual behavior

only audio plays, video does not show up.
I can see video frame previews when I hover the mouse cursor over the video progress bar, however.

### Affected Android/Custom ROM version

Android 11.0.0, kernel: Linux 4.19.116+ armv7l

### Affected device model

Mediatek Smart TV

**Comment by AudricV** [comment]
This should be a media tunneling issue, could you try a debug build, such as the one from https://github.com/TeamNewPipe/NewPipe/actions/runs/3122058886, enable the `Disable media tunneling` option in debug settings and see if the issue still occurs?

Note that this setting will be made available for release builds in the future.

**Comment by omer-musa-battal** [comment]
Yes @AudricV, the issue is gone after the option you mentioned is enabled in debug settings.
Since you said this setting will be made available in future release builds, I am closing the issue.

Thank you.

**Comment by AudricV** [comment]
Thanks for the feedback! The PR which will allow users to fix this by themselves is #8875.
