### ISSUE TITLE
Channel shows URL as title instead of the name

### ISSUE THREAD

**Issue by coffeemakr** [TeamNewPipe/NewPipe#905]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

In version 0.11.1 the channel shows the URL instead of the name.

[Screenshot](https://user-images.githubusercontent.com/5737978/33705117-59cb0834-db2f-11e7-967b-b13a6574b091.png)

**Comment by r2308145** [comment]
Already reported here https://github.com/TeamNewPipe/NewPipe/issues/901

**Comment by theScrabi** [comment]
fixed by @coffeemakr :)
