### ISSUE TITLE
Media player crash [0.24.0]

### ISSUE THREAD

**Issue by NSTAdventure** [TeamNewPipe/NewPipe#9053]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

This ambiguous because happened unexpectedly
How this happen?
When video end i minimized and  get back to media player it not responding and accident crashed like this

### Expected behavior

No crash

### Actual behavior

Crashed

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ID
* __Content Language:__ id
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux realme/RMX2030/RMX2030:10/QKQ1.200209.002/1605146661:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4d9991a u0 org.schabi.newpipe/org.schabi.newpipe.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7853)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 

### Affected device model

Realme 5i

### Additional information
Happened on both fork and official
And of course unexpectedly so i cannot tell exactly how to reproduce them 
I apologize for this inconvenience 🙏

**Comment by falkpaulfabian2004** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ LU
* __Content Language:__ de-LU
* __App Language:__ de_LU
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```
</details>
<hr>

**Comment by MDP43140** [comment]
Sounds like Android is killing NewPipe foreground process (`android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()`), and when you go back to NewPipe, it crashes. I never had this bug, so this may happen only on some devices (specifically the one that had blocked NewPipe from running in background???).

**Comment by NSTAdventure** [comment]
> so this may happen only on some devices (specifically the one that had blocked NewPipe from running in background??, or ColorOS ROMs?? since #9070 also happened on Realme phones).

I can't comment anything beside those vendor is horsemen of the annoyance 
(Bruh)

**Comment by NSTAdventure** [comment]
> Sounds like Android is killing NewPipe foreground process (`android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()`), and when you go back to NewPipe, it crashes. I never had this bug, so this may happen only on some devices (specifically the one that had blocked NewPipe from running in background??, or ColorOS ROMs?? since #9070 also happened on Realme phones).

I can't comment anything beside those OEM Devices vendor is horsemen of the annoyance
(Bruh)

**Comment by opusforlife2** [comment]
Very likely the same bug as #9070.

**Comment by NSTAdventure** [comment]
> Very likely the same bug as #9070.

Yes that's why i say this:
https://github.com/TeamNewPipe/NewPipe/issues/9053#issuecomment-1276365861
before 
Let's see how this bug will going idk what i can do beside waiting patiently.

**Comment by opusforlife2** [comment]
Try on 0.24.1?

**Comment by NSTAdventure** [comment]
> Try on 0.24.1?

Bug solved thanks developer 🙏😊
