### ISSUE TITLE
HLS video quality.

### ISSUE THREAD

**Issue by Bilingest** [TeamNewPipe/NewPipe#9055]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

HLS video quality.

### Why do you want this feature?

To watch videos comfortably.

**Comment by opusforlife2** [comment]
Not enough info. Please elaborate.

**Comment by Bilingest** [comment]
The best quality is selected by HLS to comfortably watch videos.

**Comment by Bilingest** [comment]
HLS is very fast.

**Comment by opusforlife2** [comment]
That's already the case. What made you think it isn't?

**Comment by Bilingest** [comment]
Opening videos is delayed.

**Comment by Bilingest** [comment]
The feature is very good.

**Comment by opusforlife2** [comment]
That's not due to the lack of HLS support.
