### ISSUE TITLE
Accelerate video loading.

### ISSUE THREAD

**Issue by Bilingest** [TeamNewPipe/NewPipe#9056]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Buffer settings to speed up the loading of videos.
1.Start playback
2.Maximum buffer
3.Purpose of buffering

Change these settings

In that app, the videos were loading late and they added HLS as the default quality. Changing the buffer settings made the longest videos load faster.

### Why do you want this feature?

For fast opening of videos.

**Comment by Bilingest** [comment]
In the LibreTube app, they added that videos open fast.

**Comment by Bilingest** [comment]
Fast opening of videos depends on the default quality.

**Comment by Bilingest** [comment]
Since the default quality is Auto or HLS.

**Comment by opusforlife2** [comment]
> In the LibreTube app, they added that videos open fast.

Explain.

**Comment by Bilingest** [comment]
In that app, the videos were loading late and they added HLS as the default quality. Changing the buffer settings made the longest videos load faster.

**Comment by Bilingest** [comment]
When the main, maximum buffer is reduced, the video loads faster.

**Comment by opusforlife2** [comment]
"HLS" is not a quality. HLS is a protocol for streaming videos. So I'm still not sure what you're talking about.

Also, please edit your comment to add info instead of making a new one each time. It generates a bunch of unnecessary notifications and clutters up the thread.

**Comment by Bilingest** [comment]
Good!
But what will happen now?

**Comment by opusforlife2** [comment]
What will happen is that you will explain in more detail what it is you want. Based on your comments so far it is still not clear. Please write one big paragraph explaining the idea. Use examples, if possible. Right now this issue is not actionable at all.

**Comment by Bilingest** [comment]
Maximum buffer - The player will buffer the maximum amount of media in this period.

**Comment by Bilingest** [comment]
For example: 120000 milliseconds

**Comment by Bilingest** [comment]
I don't know anything else.

**Comment by opusforlife2** [comment]
Sigh.

We're in contact with the Libretube people. The developer of Piped (which Libretube is based on) is part of our team. So you can rest assured that if there are any new ways to increase video loading speed, we will definitely try to use them.

**Comment by opusforlife2** [comment]
@Bilingest Deleting all your comments is not only impolite, it also leaves readers with no context for the conversation. Try to avoid it.
