### ISSUE TITLE
Video is extremely glitchy and can't be watched

### ISSUE THREAD

**Issue by CONIGUERO** [TeamNewPipe/NewPipe#9061]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Play this video: https://www.youtube.com/watch?v=jWc1lAj8O-E
2. Keep watching for approximately 20 seconds.

### Expected behavior

Video plays normally

### Actual behavior

Video playback gets completely corrupted.

### Screenshots/Screen recordings

![Screenshot_20221003-191736_NewPipe](https://user-images.githubusercontent.com/64615687/193696378-e4f507d6-9fc8-4b67-a6af-c0e8c912ba61.jpg)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S21 Ultra 5G

**Comment by opusforlife2** [comment]
Works fine here. Try different resolutions.

**Comment by CONIGUERO** [comment]
> Works fine here. Try different resolutions.

Hmm. You're right It only seems to happen with the 720p60 resolution

**Comment by opusforlife2** [comment]
YT's compression went wrong for that stream. Only solution is to use another resolution for that particular video.
