### ISSUE TITLE
Background play crash bug

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9063]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0 stable

### Steps to reproduce the bug
1. Open the 'Newpipe' app
2. Long press on any video 
3. Select 'start playing in background'
4. App crashes and you are returned to home screen.
Note: it doesn't show any error notification but if you quickly open newpipe again before android kills it you will get the following error report.

### Expected behavior

Video should play in background

### Actual behavior

App crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux OPPO/CPH1861/CPH1861:9/PPR1.180610.011/1587903909:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{446c64b u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1967)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```
</details>
<hr>

### Affected Android/Custom ROM version

ColorOS v6.0

### Affected device model

Oppo Realme 1

### Additional information

Probably works fine in previous version.

A workaround is to click on the video and then select background button and video will play fine in background

To reproduce you must exit the new pipe player notification first and then follow the aforesaid steps.

**Comment by opusforlife2** [comment]
Have you blocked Newpipe notifications?

**Comment by Master2050** [comment]
No I haven't blocked notification from newpipe

**Comment by Master2050** [comment]
I can even provide screen recording if you want.

**Comment by opusforlife2** [comment]
The crash log is what's needed. Edit the description and paste it there.

**Comment by Master2050** [comment]
Updated but not 100% sure check if it helps
