### ISSUE TITLE
Unfinished / Incomplete download disappear from Download list on closing or stopping the app

### ISSUE THREAD

**Issue by t297161** [TeamNewPipe/NewPipe#9066]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

I have noticed that partially/non-completed download items are disappearing from the downloads list if the app is an any way stopped or interrupted - manually closed, times out in the background, etc - before they are done.  It just remove the download listing, The partially downloaded file is still in the folder where it was started to save.

**Comment by t297161** [comment]
The app version is 0.24.0 on Android 6.0.1.

**Comment by frederickjh** [comment]
What is the duplicate iissue number? I am seeing the same issue and would like to follow it. Thanks!
