### ISSUE TITLE
Download error.

### ISSUE THREAD

**Issue by Fertanima** [TeamNewPipe/NewPipe#9068]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1.Go to history or playlists.
2.Click the download button.
3.Tap the Back button on the phone.
4.An error occurred.

### Expected behavior

An Error should not occur when we rollback

### Actual behavior

An error occurs.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/112704336/193872207-777dbbe8-256d-4e37-b0eb-8a85939ded64.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AZ
* __Content Language:__ az-AZ
* __App Language:__ az_AZ_#Latn
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment StatisticsPlaylistFragment{4a733d2} (67ef3676-75e8-4fbd-9195-79757baa6d5c) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.lambda$static$16(StreamDialogDefaultEntry.java:119)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.$r8$lambda$E-BGm7Z2EfgISHn-yX4TCRIhxak(Unknown Source:0)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry$$ExternalSyntheticLambda1.accept(Unknown Source:4)
	at org.schabi.newpipe.util.SparseItemUtil.lambda$fetchStreamInfoAndSaveToDatabase$4(SparseItemUtil.java:121)
	at org.schabi.newpipe.util.SparseItemUtil.$r8$lambda$cfmnXoy0qdCzt8EeO-smvalxWsM(Unknown Source:0)
	at org.schabi.newpipe.util.SparseItemUtil$$ExternalSyntheticLambda2.accept(Unknown Source:6)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 (One UI Core)

### Affected device model

Samsung Galaxy A21s

### Additional information

The error only occurs when I hit the back button.NewPipe has no other errors according to my device, it works great. I tested it.

**Comment by plasticanu** [comment]
Hi, we are an assignment group (6 people) studying computer science at the Australian National University. We would like to work on this issue, and we have 19 days left to write code and open a pull request. Can you assign this issue to us?

**Comment by Nizami20052022** [comment]
What will happen after 19 days?

**Comment by plasticanu** [comment]
> What will happen after 19 days?

It will be the deadline for our assignment :).

**Comment by Nizami20052022** [comment]
Can you no longer contribute to NewPipe?

**Comment by Nizami20052022** [comment]
Solve this issue. I don't think permission is needed.

**Comment by plasticanu** [comment]
> Can you no longer contribute to NewPipe?

There will be a final exam period. I am personally interested in this project, so I'll keep contributing after the exams. Not sure about other people. However, you can assume we'll no longer contribute.

**Comment by plasticanu** [comment]
> Solve this issue. I don't think permission is needed.

So we can work on this? Thanks!

**Comment by Nizami20052022** [comment]
Yes

**Comment by Nizami20052022** [comment]
Start if you want.

**Comment by opusforlife2** [comment]
> Start if you want.

@Nizami20052022 In the future, let a team member handle this. If their work is rejected by any chance, the time they would have wasted would partially become your responsibility as well.

> I don't think permission is needed.

You're right in this case, since it is a bug with a likely straightforward fix. But if it's something that has wiggle room that needs to be worked out, again, the team needs to be aware and in agreement.

**Comment by plasticanu** [comment]
> > Start if you want.
> 
> @Nizami20052022 In the future, let a team member handle this. If their work is rejected by any chance, the time they would have wasted would partially become your responsibility as well.
> 
> > I don't think permission is needed.
> 
> You're right in this case, since it is a bug with a likely straightforward fix. But if it's something that has wiggle room that needs to be worked out, again, the team needs to be aware and in agreement.

I have written some code and the bug is fixed. How can I open a new branch and push my code there?

**Comment by plasticanu** [comment]
> > Start if you want.
> 
> @Nizami20052022 In the future, let a team member handle this. If their work is rejected by any chance, the time they would have wasted would partially become your responsibility as well.
> 
> > I don't think permission is needed.
> 
> You're right in this case, since it is a bug with a likely straightforward fix. But if it's something that has wiggle room that needs to be worked out, again, the team needs to be aware and in agreement.

Hi, how can I open a new branch?

**Comment by AudricV** [comment]
By using a fork of the project on a GitHub account on which you have write access (like your personal fork if you made one).

When you will open a PR with your changes, you would use your fork as the head repository and your branch as the branch used in the PR.

**Comment by plasticanu** [comment]
> 



> By using a fork of the project on a GitHub account on which you have write access (like your personal fork if you made one).
> 
> When you will open a PR with your changes, you would use your fork as the head repository and your branch as the branch used in the PR.

Thanks! Now I have written some code. The issue seems to be related to the fragment. If the user quits the current fragment, the fragment will be destroyed. But the download function was already called, it's still using the previous fragment as the variable.

I think there are two solutions for this bug. One is to display the DownloadDialog anyways no matter if the user quits the history screen or not. But the solution will involve more things because the user can go to settings activity or other screens. The other one is to not display the DownloadDialog if the user quits the history screen. Can you help to decide which one does the team want?

**Comment by opusforlife2** [comment]
> The other one is to not display the DownloadDialog if the user quits the history screen.

I was about to say this one, but it looks like you've chosen this way in the linked PR. 👍

**Comment by plasticanu** [comment]
> 

Yeah. Cuz the deadline is approaching and we are focusing on other issues QAQ
