### ISSUE TITLE
Request to make video and description/comments abe viewed on the same screen (like YouTube) in Landscape mode

### ISSUE THREAD

**Issue by vishalscodes** [TeamNewPipe/NewPipe#9069]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I want the video and the description/comments to be able to align with each other even in landscape mode like it has been done in YouTube. 

![Screenshot_2022-10-04-22-54-37-412_com google android youtube](https://user-images.githubusercontent.com/104351431/193887730-2ef3f582-6fed-442e-9dd6-7c5783168a91.jpg)

### Why do you want this feature?

People who are used to Youtube's behaviour might be confused when they find out that the video and comments/description don't align on the same window in landscape mode.

**Comment by opusforlife2** [comment]
You can long-press on the top right arrow to see the comments, or drag up the full screen button if it is visible to the same effect.
