### ISSUE TITLE
[Feature request] Show comments on YouTube Videos

### ISSUE THREAD

**Issue by SudoLinux** [TeamNewPipe/NewPipe#907]
Not sure if this causes any huge YouTube Privacy Problems, but it would be nice to show comments, maybe by swiping right-to-left or by scrolling down. Thanks!

**Comment by r2308145** [comment]
Yes, that would be nice indeed. I don't think there should be any major privacy concerns as long as the comments would be displayed only for reading without the possibility to write your own comment. Also, I believe this was already suggested by someone some time ago..

**Comment by TobiGr** [comment]
Hey guys, comment support is discussed in #579
