### ISSUE TITLE
How to increase font size and thumbnail size to fit screen? 

### ISSUE THREAD

**Issue by vishalscodes** [TeamNewPipe/NewPipe#9071]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

How to increase font size and thumbnail size to fit screen like in YouTube with Grid mode enabled?

Screenshots:
<img alt="Screenshot_20221005_131020_com google android youtube" src="https://user-images.githubusercontent.com/104351431/194018516-c83b19c6-11db-4b27-becc-f18ef1968c84.jpg" height=600 />

<img alt="Screenshot_20221005_131048_org schabi newpipe" src="https://user-images.githubusercontent.com/104351431/194018557-3ab0f7d6-0b71-49d8-9418-4dfe6f3b7e91.jpg" height=600 />

**Comment by opusforlife2** [comment]
Strange. I get two columns.

**Comment by opusforlife2** [comment]
@vishalscodes What's your screen size? Did you modify display settings?

**Comment by vishalscodes** [comment]
My screen size is 5.93 inches. I didn't modify any display settings but I did change the List view mode to Grid in the Appearance tab.

**Comment by opusforlife2** [comment]
Then it must be a quirk of your particular device's display proportions. Try fiddling with the display size to see what happens.

**Comment by vishalscodes** [comment]
@opusforlife2 How should I do that with a mobile? Besides, I want the video thumbnail and fonts to increase so that it looks more like YouTube, not a double-columned layout.

**Comment by opusforlife2** [comment]
I don't think that's possible currently. You can follow #6087 for that.
