### ISSUE TITLE
Glitchy playback due to excessive cache accumulation

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9077]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0 stable

### Steps to reproduce the bug

1. Have only 100mb of storage left on device
2. Open 'Newpipe' and use until cache fills up all the memory left.

### Expected behavior

Older cache should be cleared to make room for new cache

### Actual behavior

Glitchy interrupted playback like it's buffering in between.

### Affected Android/Custom ROM version

Color OS v6.0

### Affected device model

Oppo Realme 1

### Additional information

Tired of continuously clearing cache every now and then.

**Comment by opusforlife2** [comment]
> Have only 100mb of storage left on device

That's not a Newpipe problem. That's a you problem. Of course the video buffer is going to take up space. That's unavoidable.

How are you even using a device with just 100 MB left? Isn't Android spamming you with "running low on storage" notifications?

The obvious solution is to clear up some space on your device.
