### ISSUE TITLE
Can't see subscribers/videos count (translation related)

### ISSUE THREAD

**Issue by r2308145** [TeamNewPipe/NewPipe#908]
This problem appeared in 0.11.1 after I corrected the czech translation as there was a mistake in inflection in previous version. I'm talking about weblate string [158 ](https://hosted.weblate.org/translate/newpipe/strings/cs/?checksum=4fa95be9b4c014e3) and [162](https://hosted.weblate.org/translate/newpipe/strings/cs/?checksum=3ef2482261f99405). In english there's only 1 subscriber or many subscribers (plural). However in czech there's 1 odběratel, then a few odběratelé (2,3,4) and many (5 and more) odběratelů. The same goes for video/videos with 1 video, then a few (2,3,4) videa and many (5 and more) videí. In version 0.11 the words odběratelé/odběratelů and videa/videí were vice versa, but after correction the numbers count disappeared.. dont know why.

**Comment by TobiGr** [comment]
@r2308145 I already saw it. Please read our [discussion](https://github.com/TeamNewPipe/NewPipe/commit/f9e03c9a40459184c2ad4f53afd5cf663e5f457b#commitcomment-26113369) about this.
@theScrabi Do you want do do another re-release and fix the strings?

**Comment by r2308145** [comment]
Thanks for the link, didnt know this is already being discussed.

**Comment by theScrabi** [comment]
@TobiGr done

**Comment by TobiGr** [comment]
@theScrabi Did you correct the strings?

**Comment by r2308145** [comment]
@TobiGr Probably not, still cant see the counter in latest release

**Comment by theScrabi** [comment]
No, I thought there was a commit fixing that string.

**Comment by Stypox** [comment]
This was recently solved with the introduction of custom plurals
