### ISSUE TITLE
NewPipe Crashed After Clicking Next on Shorts video

### ISSUE THREAD

**Issue by MDP43140** [TeamNewPipe/NewPipe#9086]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open NewPipe
2. Make a video queue consisting of any amount of shorts/normal video (idk if this affects normal > shorts. i tested this with 1 shorts, 1 normal video).
3. Play it
4. Make the player fullscreen
5. Click "next video"
6. The device will rotate, and when it rotates, NewPipe crashed.

### Expected behavior

It should continue to next video even when the screen is rotated

### Actual behavior

Nope, literally crashed...

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/68391650/194713744-8cec37aa-8860-4e1b-b928-f6fb1a887449.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ID
* __Content Language:__ id
* __App Language:__ in
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux samsung/a6ltedx/a6lte:10/QP1A.190711.020/A600GDXU9CUB1:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$handleResult$23(VideoDetailFragment.java:1619)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$kvbSCZYpk1eZXvjw0VQVcbHCIUo(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda23.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 (OneUI 2.0 Custom ROM)

### Affected device model

Samsung Galaxy A6

**Comment by AudricV** [comment]
> org.polymorphicshade.newpipe

This isn't an official NewPipe version. Is it reproducible with the official version? I used your steps to reproduce the bug, but I didn't get a crash.

**Comment by MDP43140** [comment]
i did try it in official version

**Comment by opusforlife2** [comment]
Try with a different OS. This might be OS specific.

**Comment by MDP43140** [comment]
i reported on wrong place sorry

**Comment by MDP43140** [comment]
looks like its fixed in latest version (for both newpipe and now tubular), sorry
