### ISSUE TITLE
[Feature request] Add option to save Favorite videos

### ISSUE THREAD

**Issue by r2308145** [TeamNewPipe/NewPipe#909]
This could be useful when you find a certain video you like (i.e. music) and want to return to it later, but you don't want to download it or subscribe to the channel. Though you can find it in your history or search for it again, but I think something like favorites would be more elegant as in history there's a lot more videos and you don't need to remember the video's name..

**Comment by theScrabi** [comment]
Sounds like this: https://github.com/TeamNewPipe/NewPipe/issues/870

**Comment by r2308145** [comment]
Sorry for duplicate, sounds quite similar.. wonder whats your view on that

**Comment by theScrabi** [comment]
All god :)

I totally lock foreword to it. I like the idea.
