### ISSUE TITLE
NewPipe App. Tracking

### ISSUE THREAD

**Issue by bell-kevin** [TeamNewPipe/NewPipe#9097]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

I thought NewPipe doesn't track.
<img alt="Screenshot_20221010-093202" src="https://user-images.githubusercontent.com/8269880/194903272-c0be200f-4e3e-47e2-9198-b6dedbbffd44.png" height=600 />
<img alt="Screenshot_20221010-093543" src="https://user-images.githubusercontent.com/8269880/194903776-3b086ede-78ca-495b-b842-208b912f1973.png" height=600 />
<img alt="Screenshot_20221010-093957" src="https://user-images.githubusercontent.com/8269880/194904422-84b76eab-dff2-4fe5-9a21-7b88dcb93b95.png" height=600 />
<img alt="Screenshot_20221010-093945" src="https://user-images.githubusercontent.com/8269880/194904428-7c380dcb-c4e9-4a3f-9cfd-4019a1865419.png" height=600 />
<img alt="Screenshot_20221010-094127" src="https://user-images.githubusercontent.com/8269880/194904688-fdfea5e2-e2ad-4b0c-8809-1f75b41f63f6.png" height=600 />

**Comment by bell-kevin** [comment]
![Uploading Screenshot_20221010-093543.png…]()

**Comment by TobiGr** [comment]
NewPipe does not track. Do you have the official app installed? You can find the exodus privacy report for NewPipe [here](https://reports.exodus-privacy.eu.org/de/reports/org.schabi.newpipe/latest/). It clearly says: no trackers
However, when searching for NewPipe on the exodus website you'll notice that there are many illegal NewPipe copies with trackers included.

Stuff that is listed in the second and third screenshot are completely useless to NewPipe (name, gender, advertising id, etc.).

Your first screenshot says "This feature is in beta.". Looks like alpha to me. What kind of app uses generates this report?

**Comment by bell-kevin** [comment]
Thank you for the reply! I use the NewPipe app. via F-Droid, so I'm assuming I have a good copy/version of the NewPipe app. This tracker app is the DuckDuckGo tracker app.

**Comment by TobiGr** [comment]
I suggest you to report these complete false claims to the devs of the DuckDuckGo tracker app. These kinds of false reports can harm the reputation of other devs, too. The report is complete non-sense for various reasons.
We cannot access data like email addresses, first and last name or gender, because we don't even have the permission to access any kind of profiles. I have no idea how they "detected" these kinds of tracking attempts. If we tracked some of these features, we'd be thrown out of F-Droid pretty quickly. They run regular scans and even do manual labor to check if an app is tracking (as e.g. seen in #8705)

I'll close this issue as solved. If you have any further questions, feel free to ask in this thread!

**Comment by bell-kevin** [comment]
@duckDuckGo

**Comment by opusforlife2** [comment]
Did you just ping the entire DDG team on Github!?

It would have been much better to open an issue in their repo and let their regular maintainers deal with it...

**Comment by bell-kevin** [comment]
Could you help me do that, @opusforlife2 ?

**Comment by bell-kevin** [comment]
I got the DuckDuckGo app from the Google Play app. store. I got the NewPipe app. from F-Droid.

**Comment by opusforlife2** [comment]
Do they provide a link to their bug tracker?

**Comment by bell-kevin** [comment]
I can not see a link to the DuckDuckGo bug tracker in the DuckDuckGo app. I don't understand what exactly to report as the bug in the DuckDuckGo app. I think the DuckDuckGo app. is working correctly. If you look at the second screenshot, it says "Google. 4 attempts. Known to collect:" So I understand this to mean DuckDuckGo detected 4 attempts to send data from the NewPipe app on my phone to Google servers. DuckDuckGo is not saying Google actually collected my email address, gender, etc. DuckDuckGo is just saying Google is known to collect those types of data normally on all sorts of apps. I still wonder what data is attempting to flow from my NewPipe app on my phone to Google servers.

**Comment by opusforlife2** [comment]
@bell-kevin Does it specify _which_ domains these are? Could you paste them here?

**Comment by bell-kevin** [comment]
Maybe @Symphonic3648 ? What do you say @TobiGr and @opusforlife2 ?

**Comment by bell-kevin** [comment]
As far as I can tell, NewPipe is still tracking. That's against F-Droid policy, from what I understand.
![Uploading Screenshot_20221024-081351.png…]()

**Comment by bell-kevin** [comment]
![Screenshot_20221024-081351](https://user-images.githubusercontent.com/8269880/197548392-71357411-6252-488a-923c-de58a47705ca.png)

**Comment by bell-kevin** [comment]
@TobiGr , what do you say to my new post?

**Comment by bell-kevin** [comment]
Okay

**Comment by TobiGr** [comment]
@bell-kevin As Symphonic3648 already advised you, please refrain from tagging people repeatedly. GitHub is neither an instance messaging service nor are we maintainers willing to get spammed with notifications in our spare time. And third, you are not the only one who is awaiting a response.

Did you open a ticket in the corresponding duckduckgo repo?
I am not sure, what you want us to do. As I already stated, we do not track. Feel free to go to the source code. I guess that contacting YouTube's services to fetch content is interpreted as tracking. NewPipe does not send any data to external servers - the only exceptions are when the app is requesting content or is checking for a new app version (if enabled and the app was built by us).

**Comment by bell-kevin** [comment]
@TobiGr , I use the NewPipe app. almost everyday if not everyday to watch content. The NewPipe app. tracking event happened has only happened about twice, once about two weeks ago, and then it happened again about 11 hours ago. Is watching content basically the same as fetching content, tracking-wise?

I did open a ticket with DuckDuckGo. DuckDuckGo says they are still looking into the matter, and that it is a complicated issue for them from that end.

**Comment by opusforlife2** [comment]
Okay. Then I advise you to stop using Newpipe until the DuckDuckGo people reply that it doesn't track you. Instead, you can use the Librepipe app, or Invidious/Piped in the browser.

Also you still haven't stopped tagging people despite being warned. If you do it again I'm sorry to say that you might be blocked.

**Comment by opusforlife2** [comment]
You're harassing people the way you keep pinging them. If you want to be treated politely, then you must be polite yourself. If someone mentioned an etiquette guideline for you to follow, which _you yourself acknowledged_, then ignoring it means that you don't care about being rude. Why should we treat you any different than you treat us?

My advice is to stop commenting. Either here or on the DDG repo. Once they find a solution, you will get a notification, and we can proceed from there.

**Comment by opusforlife2** [comment]
Thank you for removing the mentions, bell-kevin. The notifications will have gone out and can't be retracted, but it's the thought that counts. 👍

I can understand why you would want to delete certain comments, but in general, try to avoid it if possible. It leaves future readers confused about what was going on.
