### ISSUE TITLE
Newpipe's Subscription 

### ISSUE THREAD

**Issue by TheGoldenSun** [TeamNewPipe/NewPipe#9105]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hi Newpipe Team,

I wanted to ask you guys a question since it has to do with subscriptions from your platform app newpipe, how come newpipe users are having a hard time importing and exporting their subscriptions from their YouTube app they have been using for years? 

### Additional information

<img alt="Screenshot_20221011_001708" src="https://user-images.githubusercontent.com/104534608/194996388-07ac2c39-aa12-4f52-9393-2cf733fc4d10.png" height=600 />

I have been importing and exporting my subscriptions through my YouTube app that I had installed from Google playstore for years and nothing worked, so allow me to ask you something, should there be any system IU changes for newpipe users to freely notice what they had subscribed through your subscription list?

**Comment by Master2050** [comment]
Not able to comprehend your question could you clarify further?

**Comment by Nqtural** [comment]
In NewPipe, go to the subscriptions tab, tap the 3 dots in the upper right corner, tap `Import from`, tap `YouTube`, then follow the instructions given there.
