### ISSUE TITLE
[with workaround][regression] 0.21.5 -> 0.21.7 (+ all newer versions) - "no application can handle this action" when clicking on import database on Android TV

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#9108]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.21.7 and all newer versions

### Steps to reproduce the bug

<img src="https://user-images.githubusercontent.com/415238/195164077-af60a9c9-ff34-4dca-95f4-08a9576e2c1e.png"/>

<hr/>

I've kept upgrading so I didn't noticed it for a long time,  
but I've needed to do a new installation on Android TV recently  
and came across this.

I went back from v0.24, installing/uninstalling/installing..  
until I've found the version where it broke.

0.21.5 was the last version that the <kbd>Import database</kbd> button worked on Android TV. in version [0.21.7](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.21.7), and all versions ofter that the functionality is broken.

for some reason the <kbd>Export database</kbd> is still working,  
so newer versions can successfully backup, just not import it back.  

<hr/>

the workaround:  
1. make sure you have a recent backup, place it on sdcard (not external storage).  
2. clear data, uninstall whatever version you have.
3. download https://github.com/TeamNewPipe/NewPipe/releases/download/v0.21.5/NewPipe_v0.21.5.apk  
4. install v0.21.5, settings, click <kbd>Import database</kbd>, select the backup file.  
when asked "This will override your current setup" click <kbd>ok</kbd>,  
when asked "Do you want to <strong>also</strong> import settings?"  click <kbd>cancel</kbd> (do not import settings!)  
the app will restart, showing the UI has crashed, that's fine.

<img src="https://user-images.githubusercontent.com/415238/195167996-7ba17ca3-14f8-4422-9d45-babb31415ee1.png"/>

force close the app, clear cache (not data).  

7. download the most recent version from https://github.com/TeamNewPipe/NewPipe/releases/latest - install on top of existing app (upgrade).
8. done. (you still need to manually change all the settings though..).

<hr/>

### Expected behavior

allowing <kbd>Import database</kbd> on Android TV.

### Actual behavior

<kbd>Import database</kbd> on Android TV shows `no application can handle this action`  (in a notification bubble at the bottom of the screen).

### Affected Android/Custom ROM version

Android 9 (SDK 28) (no superuser access)

**Comment by peat80** [comment]
Import and export works fine on shield tv. Has probably to do with SAF enabling by default on newer newpipe versions.
You should try to disable SAF in newpipes settings. (I think its forced for android versions higher than android 9 and can't be disabled there).
SAF seems to be broken on android tv because a lot firmwares out there seems to contain no default filepicker app.
