### ISSUE TITLE
[Bug/Issue] [v0.11.1] Channels cannot be viewed from 'search' function.

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#911]
When searching words on the app, if you select the "channel" filter, all the options are listed as URLs instead of the name of the channel, and when clicking gives the "network error" message. As shown in the following image:-

![exhibit a](https://user-images.githubusercontent.com/34193676/33792081-04de58d4-dcb1-11e7-948c-4785704014c5.png)

However, if you select a video by the same uploader, then click on the channel icon from there, it works normally.
____
Edit 1: P.S. Sorry for the abnormally large image.

**Comment by theScrabi** [comment]
Yes that was a small bug. Please download the apk again and install it. I reuploaded a fixed version
