### ISSUE TITLE
Queue freeze video

### ISSUE THREAD

**Issue by NSTAdventure** [TeamNewPipe/NewPipe#9111]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open newpipe and any video
2. Add the video to any queue by using available button (ex: play in background)
3. Video will freeze but audio will keep playing

### Expected behavior

Video will keep playing along side with audio

### Actual behavior

Video freezed meanwhile audio is still playing

### Screenshots/Screen recordings

N/A

### Affected Android/Custom ROM version

Android 10 Realme UI 1.0

### Affected device model

RMX 2030

**Comment by opusforlife2** [comment]
> Add the video to any queue by using available button (ex: play in background)

If you're adding the same video that is playing to the background audio queue, then that is the same as switching to audio.

**Comment by NSTAdventure** [comment]
> > Add the video to any queue by using available button (ex: play in background)
> 
> If you're adding the same video that is playing to the background audio queue, then that is the same as switching to audio.

Okay maybe my description is not clear 
I gonna add maybe recording soon

**Comment by NSTAdventure** [comment]
> > Add the video to any queue by using available button (ex: play in background)
> 
> If you're adding the same video that is playing to the background audio queue, then that is the same as switching to audio.

Ah i see ok sorry about it 🙏😅
