### ISSUE TITLE
Show more information about the current queue

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9114]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

It will be beneficial to show some further information about the current queue such as:
1. Total duration of the playlist
2. Remaining net duration of the playlist/queue

### Why do you want this feature?

Efficient time management.

**Comment by WorkHard4470** [comment]
Please make a pull request first.

**Comment by opusforlife2** [comment]
> Please make a pull request first.

@WorkHard4470 That's not required, though?
