### ISSUE TITLE
Option to add a playlist to current queue

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9115]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Sometimes people might want a playlist to be played in succession of the currently playing queue. 

### Why do you want this feature?

It would enhance user experience by adding an add to queue button on long press on playlist.

**Comment by opusforlife2** [comment]
Long-press on one of the 3 headers of the playlist.

**Comment by Master2050** [comment]
Clicking any of the three headers namely background, play all and popup will just reset the queue and start playing that playlist instead. Let's consider an example suppose I have a queue of 50 videos to be played and I want all the elements of a playlist to be added to the queue along with the 50 elements which are already in the current unsaved queue

**Comment by Master2050** [comment]
Thereby i request you to reopen this issue again

**Comment by opusforlife2** [comment]
> Clicking 

Read what I wrote again.

**Comment by Master2050** [comment]
Could you please share a screenshot (preferably encircled by virtual marker pen tool) about where these headers are located?. I really never found an option to enqueue an entire playlist to the currently playing queue. Thanks for your time and effort in advance.

**Comment by opusforlife2** [comment]
> Clicking any of the three headers namely background, play all and popup 

These ones that you say you're clicking. You're supposed to long-press them.

**Comment by Master2050** [comment]
Thanks for the help. Don't you think this information should have been mentioned somewhere or this option should be given when long pressing on a playlist. Too hard to figure it out by a NORMAL user easily just by mere looking at it. (Just a suggestion)

**Comment by Master2050** [comment]
A good option will be to display a 'hold to enqueue' toast notification when either one of the option is clicked to make users aware of this feature just as a text is displayed when clicking background play on any video. Or maybe somewhere else.

**Comment by opusforlife2** [comment]
^ This is a good suggestion. You can open a new feature request.
