### ISSUE TITLE
Share to NewPipe Error

### ISSUE THREAD

**Issue by WorkHard4470** [TeamNewPipe/NewPipe#9119]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Go to https://m.youtube.com/channel/UCY6PaxcjGzvxukpzbq66NzA by sharing to debug build of NewPipe. Throws out unsupported URL error.

### Expected behavior

Should be no errors for sharing to NewPipe to view channels.

### Actual behavior

An error occured for sharing issues. This is error.

### Logs

No logs applied.

### Affected Android/Custom ROM version

Android 12 [Global India ROM, realme UI 3.0]

### Affected device model

realme 8 4G

**Comment by chouhanyang** [comment]
I can reproduce this on youtube.com (mobile) and youtube android app.

1. Goto any channel with "Live" stream tab. For example: https://m.youtube.com/@LinusTechTips/streams
2. Click the three-dot button to share a live stream to NewPipe.
3. Error pops up with "Unsupported URL" and "Could not recognize the URL. Open with another app?".

Noticed the URL format for live stream has an extra /live/ path in it.
For example: https://www.youtube.com/live/KkmZGFEpd5c?feature=share

It is different from the original URL. https://www.youtube.com/watch?v=KkmZGFEpd5c&ab_channel=LinusTechTips

If you try the /live/ URL on web browser, it may redirect to original URL on desktop browser. But the same URL will open on mobile browser.

**Comment by chouhanyang** [comment]
This issue is reproducible, but gets auto closed. Should I open another issue?

**Comment by peat-psuwit** [comment]
I also can reproduce the problem, with essentially the same conclusion as @chouhanyang. @SameenAhnaf, is the information given enough or more information from author is still needed?

**Comment by AudricV** [comment]
@chouhanyang The bug you mentioned is different and will be fixed with 0.25.0: see #9546.

@SameenAhnaf Is your issue the same as the one of @chouhanyang? If so, then this issue should be closed due to lack of response of the original author.
