### ISSUE TITLE
Playlist 'Remove Watched' bug

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9122]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0 stable

### Steps to reproduce the bug

1. Start playing any playlist in background
2. Select remove watched from top right 3 dot menu 
3. Select ok

### Expected behavior

Only watched videos should be removed without partially watched ones getting removed

### Actual behavior

The current playing video in background also gets removed and is considered as a watched video.

### Screenshots/Screen recordings

The first one is with currently playing video(Myanmar Aung.....) 

<img alt="Screenshot_2022-10-14-00-55-53-36_ee8807d2de22f1831269d80920e33a3b" src="https://user-images.githubusercontent.com/28833686/195691600-573339d2-c22d-413a-81f4-f1ee077c27ae.png" height=600 />

This is option to remove only watched videos(click OK)

<img alt="Screenshot_2022-10-14-00-56-06-76_ee8807d2de22f1831269d80920e33a3b" src="https://user-images.githubusercontent.com/28833686/195691830-1c8d4f83-a78b-47e9-8fb3-08f44b9360d6.png" height=600 />

The currently playing video also gets removed

<img alt="Screenshot_2022-10-14-00-56-18-15_ee8807d2de22f1831269d80920e33a3b" src="https://user-images.githubusercontent.com/28833686/195691894-cfcadffc-557b-4ccc-8496-71fa70abbc30.png" height=600 />

### Affected Android/Custom ROM version

ColorOS v6.0(android 9.0)

### Affected device model

Oppo realme 1 CPH1861

**Comment by Jared234** [comment]
I would like to work on a fix for this bug. I could create a PR in the upcoming days.
