### ISSUE TITLE
Toast notification to enqueue a playlist 

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9130]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

display a 'hold to enqueue' toast notification when either one of the headers(background, play all, popup) in a playlist is clicked to make users aware of enqueue feature just as a text is displayed when clicking background play on any video.

### Why do you want this feature?

I believe this information should have been mentioned somewhere or this option should be given when long pressing on a playlist. Too hard to figure it out by a NORMAL user easily just by mere looking at it.

**Comment by Jfax510** [comment]
Hi, can I work on this issue?

**Comment by opusforlife2** [comment]
> absolutely open a pull request 

@Master2050 I mentioned this to another user a few days ago. Since you're not a team member, you can't be the one telling people it's okay to open a PR. If their PR is rejected by the team later, the responsibility will partially fall on you for the time they wasted. Let the team handle these things, okay?
