### ISSUE TITLE
Newpipe doesn't work with WiFi connection

### ISSUE THREAD

**Issue by avDuma** [TeamNewPipe/NewPipe#9133]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

With phone connected to the wifi, video doesn't load: not only the stream of youtube videos, also video description and comments: nothing gets loaded.

When I switch off WiFi and use phone data, all works flawlessly.

Important to notice that is not related to my ISP / WiFi connection because the same video reached by the official Youtube application works perfectly.

### Affected Android/Custom ROM version

Android 11 (OxygenOS 11.1.2.2)

### Affected device model

OnePlus 6

**Comment by SC1040-TS2** [comment]
Quick question: Can you check the Play Store to see if the Google Carrier Services app is installed on your device by default?

**Comment by avDuma** [comment]
Hi @SC1040-TS2 ,
Thank you for your reply.

No, I'm not using Wi-Fi calling on my device, neither I have installed Google Carrier Services.

After installing it and reboot the phone, by the way, the problem still occurs.

**Comment by opusforlife2** [comment]
Are you using a particular DNS? Try a different one.

**Comment by avDuma** [comment]
Thank you @opusforlife2 for your reply.
I've switched to OpenDNS, but nothing changes.

Just to notice that using Libretube as Youtube client it works perfectly.

**Comment by opusforlife2** [comment]
Take a backup of your database from Content settings and then uninstall then reinstall Newpipe. Without changing any settings or importing your database, see if it works on Wifi.

**Comment by avDuma** [comment]
Thank you, @opusforlife2 for your reply.

**reinstalling** (and importing my configuration) **solves the problem**.

How to mart as solved?

**Comment by opusforlife2** [comment]
You close the issue as completed.

**Comment by Mech117** [comment]
I'm having the same issue, uninstalling and reinstalling did not fix it. other YouTube apps work fine, internet connection is working like normal. New pipe just refuses to connect on Wi-Fi, connects over cell data just fine.

**Comment by SC1040-TS2** [comment]
> Troubleshooting your connection first would be the way to go. Check your firewall, adblocker, hosts file, DNS server etc. If it fails to fix the problem, open a new issue and we'll help you debug.

I managed to figure out a source of this after personally being frustrated by this problem.

If one enables Respond to Ping on Internet Port in one's router settings—e.g. ignoring the security and DDoS attack risk that introduces in favor of ensuring ICMPv6 is reachable by outside sites and services for IPv6 compliance, as a decent example of that use case—NewPipe will begin to break down. It will suffer from a frequent inability to load and play back videos, load channel pages, render icons, and generally function, suffering frequent over 8000ms timeout error messages, and even exposing a few new error messages involving function execution.

Other Android apps seem to function with the Open ICMP reachability just fine, or to an extent where any latency and timeouts are not noticeable, but NewPipe in particular does not handle this well.

Either listen to NewPipe's network traffic and figure out why it is being hindered by this setting now, or attempt to see if some internal function issues are causing the networking side of NewPipe to act up when it should not.

**Comment by Alokpandey-05** [comment]
@SC1040-TS2 could you please help me with the solution in simple terms not with many jargons... actually I too have been facing similar issue

**Comment by SC1040-TS2** [comment]
What, even with 0.25.2?

**Comment by void-m4110c** [comment]
> This should have been fixed in NewPipe 0.25.2, without needing to do the at the time inconsistent workaround above. Update to it.
> 
> https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.25.2

Nope. I'm on v0.25.2 and the problem persists.
What I find strange is that the wifi connection works fine AFTER the feeds are loaded and I start a video on data connection. Once the video starts, I can switch WiFi back on and it runs till the end.

**Comment by Voix11** [comment]
I have the same problem now. Everything works on mobile data but on wifi nothing :/

**Comment by Alokpandey-05** [comment]
My issue initially which I thought to be from the server end of the software ended up being the issue from the wifi service provider...which was resolved within 1 day after numerous complaints from my area!!

**Comment by arkkito** [comment]
I am using NewPipe 0.27.0, and when I am connected to Wifi that provides IPv6 NewPipe doesn't load anything.
The Youtube APP works fine, and the website works fine too.
Any ideas how I can figure out what is going on?
Any logs I can send to the devs?

**Comment by Alokpandey-05** [comment]
I have no idea bhaii....kindly ask @SC1040-TS2 for help....

**Comment by Kovaelin** [comment]
> My issue initially which I thought to be from the server end of the software ended up being the issue from the wifi service provider...which was resolved within 1 day after numerous complaints from my area!!

What did you tell your provider to get them to fix it?
