### ISSUE TITLE
Words are not available on Weblate.

### ISSUE THREAD

**Issue by Nizami20052022** [TeamNewPipe/NewPipe#9134]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The words that indicate when the video was released are in English

### Why do you want this feature?

<img alt="Screenshot_20221016-013416_NewPipe" src="https://user-images.githubusercontent.com/104249296/196008566-0b9f6e1a-33de-4d89-bdb5-688e38dd5ea3.jpg" height=600 />

### Additional information

Look at the picture, the release date of the video is in English.

**Comment by Master2050** [comment]
Which language do you want release date to be in? Probably not translated maybe you can help. To help translate type www.new pipe.net and click on translate then select language you can either create an account even with github or proceed without any account as well translate the text you can use automatic suggestions as well and suggest the change

**Comment by Master2050** [comment]
Since it is an open source software all contributors are users themselves. It will be nice to have some help in translation if you can

**Comment by Nizami20052022** [comment]
You haven't added them to Weblate, how can I translate them?

**Comment by Nizami20052022** [comment]
I can translate into Azerbaijani and Turkish.

**Comment by Nizami20052022** [comment]
You add them to Weblate first.

**Comment by TobiGr** [comment]
Thank you for translation NewPipe!
The dates and times are generated using prettytime. You can find their translation files [here](https://github.com/ocpsoft/prettytime/tree/master/core/src/main/java/org/ocpsoft/prettytime/i18n). All translation of these components need to be done in their repository. You can find more information on how to add a new language to prettytime [here](https://www.ocpsoft.org/prettytime/#section-13) and [here](https://www.ocpsoft.org/prettytime/#section-14).

**Comment by TobiGr** [comment]
Thank you. It looks like you took the English translation and renamed the file. That means after your changes, there won't be an English localization. You should fix that in your PR :)
(The PR is https://github.com/ocpsoft/prettytime/pull/240)

**Comment by Nizami20052022** [comment]
How?

**Comment by TobiGr** [comment]
Add the English file to your branch: https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_en.java

And make sure to use the correct file path for the Azerbaijan file. It should be `/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_az.java`

**Comment by Nizami20052022** [comment]
I just created a new file. Is the file correct?

**Comment by Nizami20052022** [comment]
Shall I close this issue?

**Comment by TobiGr** [comment]
Yes, thanks.

**Comment by Nizami20052022** [comment]
The translation file has been merged, you need to add it

**Comment by Nizami20052022** [comment]
https://www.ocpsoft.org/prettytime/#section-13

**Comment by TobiGr** [comment]
Big thank you to you to all NewPipe contributors who contributed to the localization update of prettytime!
We'll just need to update prettytime, the rest is done by NewPipe automatically. The update is not available on maven yet. I'll update it once the new version is available.

**Comment by Nizami20052022** [comment]
Will this issue not be resolved?

**Comment by Nizami20052022** [comment]
Why don't you add?

**Comment by Nizami20052022** [comment]
There was no problem anymore.

**Comment by TobiGr** [comment]
PrettyTime has had some problems with the latest replease. It's still not completely published on maven central https://github.com/ocpsoft/prettytime/issues/248

**Comment by Nizami20052022** [comment]
No more problems

**Comment by TobiGr** [comment]
See #9272

**Comment by Nizami20052022** [comment]
Thank you very much!🤗
