### ISSUE TITLE
Action Denied by System when downloading video

### ISSUE THREAD

**Issue by BreadDisease** [TeamNewPipe/NewPipe#9138]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Download video
2. Click ok
3. Pick folder
4. Click checkmark in file explorer to start download

### Expected behavior

I expect the video to download

### Actual behavior

Get error message "action denied by system" when trying to download videos to common folders like Downloads, Movies, etc. The file will be created, but will be 0 bytes in size. If trying to download to Android/data/org.schabi.newpipe/ I get error java.io.FileNotFoundException in MiX file manager. I have tried Material Files and Simple File Manager pro, but they don't support SAF according to NewPipes download feature. I tried reinstalling the app and downloading different videos.The app hasn't asked me for file permissions. By default, Files and Media access is denied in the app info in Android. I allowed it, but it only lets me allow "Allow Access to Media Only"

### Screenshots/Screen recordings

<img alt="Screenshot_20221016-071106_NewPipe" src="https://user-images.githubusercontent.com/54341105/196032085-f6d7fc46-13c2-4b43-a4d1-ca3b5b3e8489.png" height=600 />

<img alt="Screenshot_20221016-071736_Permission_controller" src="https://user-images.githubusercontent.com/54341105/196032289-6b53874a-a438-4cdd-ade4-fc8203c3a94a.png" height=600 />

<img alt="Screenshot_20221016-071743_Permission_controller" src="https://user-images.githubusercontent.com/54341105/196032299-50badc8d-64d7-46ea-acda-40c26fefeec8.png" height=600 />

### Affected Android/Custom ROM version

Android 11 / HavocOS 4.19

### Affected device model

OnePlus 7 Pro

**Comment by opusforlife2** [comment]
> Allow Access to Media Only

Then it should let you download videos to the Movies folder. Did you try that one after enabling this permission?

**Comment by BreadDisease** [comment]
Yes it gives me the same error when I try downloading to the Movies folder

**Comment by opusforlife2** [comment]
Can you check what folders you have set in download settings? Try setting the video and audio download folders again from within Settings.

**Comment by BreadDisease** [comment]
If I turn off Ask where to download then trying to change the video or audio download folder, I get the error 
"No app on your device can open this
No appropriate file manager was found for this action. Please install a storage access framework compatible file manager"

I am currently using MiX file manager. I tried material files and simple file manager pro too.

**Comment by opusforlife2** [comment]
@BreadDisease You or your ROM has disabled the default file manager (DocumentsUI) of the OS. You'll have to enable it to be able to use storage-based features of Newpipe properly.

**Comment by BreadDisease** [comment]
I still have /system/priv-app/DocumentsUI/DocumentsUI.apk. How do I got about enabling it? I checked apps to see if it was disabled and its not. Thanks

**Comment by BreadDisease** [comment]
Ok I figured it out. I used De-Bloater to disable Files thinking I could replace it with my own file manager. I didn't realize that disabling would break app functionality. I used De-Bloater to re-enable it, rebooted, and now it works. Thanks!

**Comment by Phoenix1025** [comment]
> If I turn off Ask where to download then trying to change the video or audio download folder, I get the error 
> "No app on your device can open this
> No appropriate file manager was found for this action. Please install a storage access framework compatible file manager"
> 
> I am currently using MiX file manager. I tried material files and simple file manager pro too.

Same issue here. Though im using material files because my realme c25y is not rooted.

**Comment by Phoenix1025** [comment]
> If I turn off Ask where to download then trying to change the video or audio download folder, I get the error 
> "No app on your device can open this
> No appropriate file manager was found for this action. Please install a storage access framework compatible file manager"
> 
> I am currently using MiX file manager. I tried material files and simple file manager pro too.

Same issue here. Though im using material files because my realme c25y is not rooted.
