### ISSUE TITLE
[Feature Request] Search results lost when I go back from the video I am watching.

### ISSUE THREAD

**Issue by camdadeye291** [TeamNewPipe/NewPipe#914]
I guess this is a feature request. Presently, when I search for something and then watch a video and go back in have to re-enter the search. My request is this, can we make it so that when I press the back button, after watching a video, it goes back to the search list?

**Comment by wb9688** [comment]
It does if you press the back button, but not if you press the up button.

**Comment by camdadeye291** [comment]
Crazy that I didn't try that first... Sorry for wasting time!
