### ISSUE TITLE
Option to sort search by date

### ISSUE THREAD

**Issue by breaking-loss** [TeamNewPipe/NewPipe#9144]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

On searching a thing there  should be option in the hamburger menu or any other to sort the search results by date like today, this week, this month etc.

### Why do you want this feature?

This would make getting updated information very easy . My personal reason is that I want to get a guide on reverse proxy on a jellyfin but I can't get the correct video 

### Additional information

I also request you to make a an option on main settings to set default sort date .

**Comment by skorektoja** [comment]
is this option is available in version 0.24.1?
