### ISSUE TITLE
Crashing frequently 

### ISSUE THREAD

**Issue by PrincessMiki** [TeamNewPipe/NewPipe#9147]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Use app as normal. Since the recent update, it crashes frequently. Crashes more when playing on background since recent update.

### Logs

{"user_action":"play stream","request":"Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=_uwAS7anNwU","content_language":"en-CA","content_country":"CA","app_language":"en_CA","service":"YouTube","package":"org.schabi.newpipe","version":"0.24.0","os":"Linux samsung/a10ecs/a10e:11/RP1A.200720.012/A102WVLU7CUG1:user/release-keys 11 - 30","time":"2022-10-18 03:27","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:246)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: timeout\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.read(YoutubeHttpDataSource.java:502)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:263)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.read(TeeDataSource.java:70)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:622)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)\n\tat com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:291)\n\tat com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:80)\n\tat com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:359)\n\tat com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:333)\n\tat com.google.android.exoplayer2.source.chunk.BundledChunkExtractor.read(BundledChunkExtractor.java:147)\n\tat com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:923)\nCaused by: java.net.SocketTimeoutException: timeout\n\tat com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:225)\n\tat com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)\n\tat com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)\n\tat com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:61)\n\tat com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:602)\n\tat com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:397)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.readInternal(YoutubeHttpDataSource.java:841)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.read(YoutubeHttpDataSource.java:500)\n\t... 14 more\nCaused by: java.net.SocketException: Socket closed\n\tat java.net.SocketInputStream.read(SocketInputStream.java:209)\n\tat java.net.SocketInputStream.read(SocketInputStream.java:144)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)\n\tat com.android.okhttp.okio.Okio$2.read(Okio.java:145)\n\tat com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)\n\t... 19 more\n"],"user_comment":""}

### Affected Android/Custom ROM version

android 11

### Affected device model

Samsung s10e

**Comment by SC1040-TS2** [comment]
Greetings. After encountering a similar degree of instability when I updated ot, it became clear that even when using the NewPipe Upstream Repository, the app was failing to properly migrate to 0.24.0 from 0.23.x.

The following process can be used to mitigate some of it:
1. In the existing 0.24.0 installation, Export a subscription backup. Do not export settings.
2. Once the export is completed, completely purge all data in the NewPipe app and in its App Info>Storage section.
3. Uninstall NewPipe.
4. Go back to F-Droid, and reinstall NewPipe 0.24.0.
5. Once successful there, Import your subscriptions backup, and reconfigure your settings manually.

That should mitigate most of the jank for now. When the app was initially pushed, something about the update process was malformed.

**Comment by PrincessMiki** [comment]
Thanks. Ive settled with basically continually restarting the app and hoping next update comes out soon
