### ISSUE TITLE
New Project management page

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#915]
I'd like to introduce our [Projects management page](https://github.com/orgs/TeamNewPipe/projects) feel free to take a look into, and see whats going on right now :)

**Comment by Cormak** [comment]
I guess only the assignees can see this page? I get a 404.

**Comment by TheAssassin** [comment]
Just checked, you're right, it seems like it is not accessible for anyone who is not a member of the organization. I'll try to publish it.

**Comment by theScrabi** [comment]
Thanks :)

**Comment by r2308145** [comment]
I'm getting 404 too.

**Comment by theScrabi** [comment]
:/ I could not find anything as well. Maybe it's not possible to make this visible to public.

**Comment by TheAssassin** [comment]
I just checked whether https://github.com/orgs/AppImage/projects/1 was publicly accessible, and it is not. That's pretty annoying, actually.

CC @probonopd

**Comment by probonopd** [comment]
Didn't find a way to change that in the settings @TheAssassin

**Comment by TheAssassin** [comment]
Neither did I for Team NewPipe, @probonopd. I think both projects want it to be public. That's a problem, I guess. It's more urgent for Team NewPipe however.

@probonopd the thing is, the repository wide projects are public, but these are not.

**Comment by theScrabi** [comment]
Maybe we should consider to switch to trello until github has enabled this feature.

**Comment by wb9688** [comment]
Why can't we use repository projects?

**Comment by theScrabi** [comment]
Would these be publicly visible?

**Comment by wb9688** [comment]
They are iirc, but then we can only link NewPipe (so no NewPipeExtractor or
PipeCast) issues.

**Comment by theScrabi** [comment]
All right. Well having projects only on NewPipe is better than having no projects :)

**Comment by wb9688** [comment]
Yeah, btw I've now added some stuff to https://github.com/TeamNewPipe/NewPipe/projects.

**Comment by theScrabi** [comment]
I removed multyservice.
I'd like to scedule multi service work after we released 1.0. so its not required for 1.0.
