### ISSUE TITLE
Add 5 band equalizer for native player

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9152]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Here is a visual example

<img alt="Screenshot_2022-10-19-10-45-30-23_deca60f65c681d0bc43599a3c6f91501" src="https://user-images.githubusercontent.com/28833686/196603317-10f2cf3a-fd46-42a4-902f-356cdf5678cb.png" height=600 />

Would be nice if reverb and bass boost is also added.

### Why do you want this feature?

I believe it will be a nice addition and would be useful for many

**Comment by wizdom13** [comment]
For anyone who still wants a built-in equalizer: our independent NewPipe fork, [WizeStream](https://github.com/wizdom13/WizeStream), includes an adaptive 10-band equalizer.

It provides five built-in presets, one persistent custom curve and automatic clipping headroom. The curve adapts to the audio bands supported by the Android device and applies directly to WizeStream playback sessions.

The feature is available in WizeStream Android 1.6.0. WizeStream is independent and is not affiliated with or endorsed by TeamNewPipe.
