### ISSUE TITLE
Storage permission issue and possible fix

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9156]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Recently there have been a lot of issues related to storage permission. Since new pipe doesn't ask for read write permission for files on initial setup it causes issues with downloads and other features. A possible fix would be to prompt the request for storage access permission when the app is initially launched for first time or after clearing data.

### Expected behavior

App should ask for storage access permission on initial start

### Actual behavior

Doesn't ask for anything

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1 CPH1861

### Additional information

A reproducible example is #9154, #9169 and possibly fixes #9138

**Comment by opusforlife2** [comment]
> A possible fix would be to prompt the request for storage access permission when the app is initially launched for first time or after clearing data.

If it's an educated guess, then just mention it in the relevant issues.
