### ISSUE TITLE
Automatically skip over in-video "sponsored" ads and advertisements

### ISSUE THREAD

**Issue by javierxio** [TeamNewPipe/NewPipe#9158]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I came across a feature in piped.kavin.rocks (using garudalinux.org instance) that automatically skips over sponsored ads that play in the video. In the progress bar, you can see it highlighted in green and the player automatically skips over the segment. This seems to be specific to garudalinux.org instance and the official piped.kavin instance does not have this feature enabled.
![image](https://user-images.githubusercontent.com/63758477/196757834-ec1c49ee-bbbf-4d50-a082-716067e96d51.png)
![image](https://user-images.githubusercontent.com/63758477/196758091-df56aa2a-d7e4-42e2-b6e6-514c8b9e1603.png)

### Why do you want this feature?

I don't want to hear about sponsors in the video. If Newpipe could enable this feature, it would be a time saver and a better user experience.

**Comment by javierxio** [comment]
@AudricV can you note the duplicate ticket?

**Comment by tsiflimagas** [comment]
What you're asking for is SponsorBlock and it's been requested a thousand times, but it was rejected in #3205.

**Comment by javierxio** [comment]
thanks @tsiflimagas
