### ISSUE TITLE
Popup dragging

### ISSUE THREAD

**Issue by epistularum** [TeamNewPipe/NewPipe#916]
I am not able to drag the popup, the video stays in place and only the frame moves (the play button,...).

v0.11.0
Android 7.1
Rooted
Lineage OS

**Comment by theScrabi** [comment]
Hm thats odd. Maybe its because of your phone. Maybe the media framework is implemented differently on it.

**Comment by epistularum** [comment]
That's why I pointed out my OS, don't know if you can do anything about it but I wondered it would still be useful to warn you.

**Comment by wb9688** [comment]
What phone do you have? And if it's an unofficial Lineage OS, what one?

**Comment by epistularum** [comment]
https://imgur.com/a/8zXri
Yes it's an unofficial OS.

**Comment by theScrabi** [comment]
@epistularum It might be hard to help you here, due to the huge segmentation of Android some errors might only happen on special devices.
We might have to debug NP on your specific phone.

However did you download an official LineageOS form [here](https://download.lineageos.org/) or did you get it form a forum like xda?

**Comment by epistularum** [comment]
@theScrabi
I completely understand, just wanted to notify the team in case this was an useful information.
I did download an unofficial lineage OS from XDA.

**Comment by theScrabi** [comment]
> I did download an unofficial lineage OS from XDA.

That might it be.

**Comment by theScrabi** [comment]
I know there is a test system out there to check how compatible your system is to the Android Plattform.

**Comment by patrikmusic** [comment]
Hi, I have the same issue. My popup window appears in the middle of the screen and can't be moved. I installed via F-Droid. I am currently using Android 5.1.1. on Xiaomi Redmi 3.

**Comment by HadouKenny** [comment]
Same issue, LG V20, Android 7.0, version V10f-AUS-XX

**Comment by REDGuineaPig** [comment]
Same issue, Wileyfox Swift 2 Plus, LineageOS 14.1 unofficial.

I have noticed however, it only happens to me in landscape mode, if that's of any help here.

**Comment by theScrabi** [comment]
Well since ExoPlayer with which popup player is implemented heavily depends on the underlying hardware, id have to first get a davice where his happens.

**Comment by theScrabi** [comment]
Closing this in favour of https://github.com/TeamNewPipe/NewPipe/issues/1159
