### ISSUE TITLE
Black screen after exitting fullscreen mode when transitions are disabled

### ISSUE THREAD

**Issue by pc165** [TeamNewPipe/NewPipe#9168]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Go to developer settings and disable Transition animation scale.
2. Play any video.
3. Press fullscreen.
4. Press fullscreen again.

### Affected Android/Custom ROM version

Android 13

### Affected device model

Pixel 7

### Additional information

~This patch makes the bug less frequent~
```
Index: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java b/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
--- a/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java	(revision 2a98cca80100d87562f0c9ff1fadeac3838f6ff6)
+++ b/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java	(date 1666382908736)
@@ -1968,7 +1968,7 @@
 
         final int newOrientation = isLandscape
                 ? ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
-                : ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE;
+                : ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
 
         activity.setRequestedOrientation(newOrientation);
     }
```

**Comment by opusforlife2** [comment]
Why would the orientation sensor be dependent on the transition animation?

**Comment by pc165** [comment]
I think it's because the view is being recreated but it still doesn't fix the issue since I got a black screen the first time, locking and unlocking fixes the issue.
Enabling "Show surface updates" fixes this issue.
https://user-images.githubusercontent.com/47307845/197348827-e340afc9-09a7-4d92-a3c2-1d2f4e1d97c1.mp4
