### ISSUE TITLE
[FEATURE REQUEST] Convert sharelinks to hooktube

### ISSUE THREAD

**Issue by marlid91** [TeamNewPipe/NewPipe#917]
I think it's great that NewPipe gets rid of Google's tracking, but it would be nice if I could share privacy respecting links to the videos I watch, instead of linking to youtube.com. Hooktube.com is such a service that strips away Google's tracking and only deliver the video. 

It would be nice if NewPipe could generate a hooktube link instead of a link to youtube.

**Comment by Stypox** [comment]
Added in #1097
