### ISSUE TITLE
Add toggle to control video thumbnail as lock screen wallpaper 

### ISSUE THREAD

**Issue by CerVieel** [TeamNewPipe/NewPipe#9170]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Please, add the option "Use Thumbnail as Lock Screen Wallpaper" to control the behavior of NewPipe in lock screen mode. Right now the lock screen is taken over by the thumbnail of the video active in the background playlist, may it be playing or paused.

There's no option to control this behavior at all, not even the"Show Thumbnail" option affects it, but ideally the new option should be distinct from it.

### Why do you want this feature?

This is a highly invasive cosmetic change.

### Additional information

I'm on Android 9. Unfortunately I'm not sure about which version introduced this change because I skipped a few ones.

**[Edit]** This is the current behavior:

<img alt="NewPipe_Th_LockScreen_Takeover" src="https://user-images.githubusercontent.com/68253601/197291635-4636f68e-1270-493a-9955-1026b19abcb8.jpg" height=600 />

**Comment by opusforlife2** [comment]
The "Show thumbnail" toggle works fine for me. Turning it off does turn off the lock screen background.

Try with a different device.

**Comment by CerVieel** [comment]
Well, this is what happens once the thumbnail is turned off.

![NewPipe_Th_LockScreen_Takeover_Stuck](https://user-images.githubusercontent.com/68253601/197365934-4e553c8d-40e0-4e4a-9bc5-af090baac63d.jpg)

I don't _have_ a different device. In any case I'm asking for an option independent from the show thumbnail toggle. I like the thumbnail, it's small, sweet and useful. But having it taking over the entire lock screen is another thing.

**Comment by tsiflimagas** [comment]
If you're on a custom ROM (which it seems you are), I bet you've made it so in your system settings. Probably the "Media cover art" setting, or something.

**Comment by TGWGitHub** [comment]
+1
