### ISSUE TITLE
Show a toast notification when check for updates is manually clicked

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9175]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

A message like 'you are using the latest version' or 'No updates found as clicking on check for updates make it seem like the button is not working and could make users to panic and check for updates on website or github repository. 

### Why do you want this feature?

It's pretty confusing why it just doesn't show anything at all after manual check for updates.

**Comment by peat80** [comment]
PR #8668 should probably fix this.
