### ISSUE TITLE
Dialog box like prompt to update when a new version is available

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9176]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

As of right now the new pipe only shows a notification. I believe a dialogue box like prompt to update will be more appropriate

### Why do you want this feature?

Notifications can be accidentally cleared when there are a lot of notification stacked up by just one clear notification button offered by most ROMs which could lead to users missing out on an update. Most users are not even bothered to check notifications most of the time.

**Comment by opusforlife2** [comment]
Lol we need an issue to track this. You can open a new issue asking for a toast. 👍
