### ISSUE TITLE
Different Status Bar Icons for PopUp and Background Player

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#918]
I just realized that we use different icons for pop-up and background player in the status bar / for our notifications. We shouldn't do that.
Maybe we even find an icon that makes us stand out among other video players. I think the icon I suggested is not optimal but is a good point to start from.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/17365767/33942640-d3adc2b8-e016-11e7-83f4-4e1f5011bfe6.png" alt="Background Player" /></td>
<td><img src="https://user-images.githubusercontent.com/17365767/33942643-d58d84c4-e016-11e7-9ccd-0b3ca272dddd.png" alt="PopUp" /></td>
<td><img src="https://user-images.githubusercontent.com/17365767/33942648-d7cf3d90-e016-11e7-8f18-15dcd1cde64a.png" alt="new" /></td>
</tr>
<tr>
<td><a href="https://github.com/TeamNewPipe/NewPipe/blob/cd04d869b7ad859878223f893038feb48d8be8e4/app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java#L180"><code>R.drawable.ic_play_circle_filled_white_24dp</code></a></td>
<td><a href="https://github.com/TeamNewPipe/NewPipe/blob/cd04d869b7ad859878223f893038feb48d8be8e4/app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java#L278"><code>R.drawable.ic_play_arrow_white</code></a></td>
<td></td>
</tr>
<tr>
<td>background player</td>
<td>popup player</td>
<td>new icon?</td>
</tr>
</table>

**Comment by theScrabi** [comment]
Yes I think a new Icon was a good idea.
