### ISSUE TITLE
Downloader shows no videos or videos without audio

### ISSUE THREAD

**Issue by Feuerswut** [TeamNewPipe/NewPipe#9185]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0 latest

### Steps to reproduce the bug

1. Go to a recently uploaded, but already fully processed (on youtubes side) video (e.g. 1 hour or older, depends on video length)
2. info: video should currently not be older than approx. 10 hours. Examples: a. https://www.youtube.com/watch?v=lg5wznn3IBE (this does not affect all videos and not in similar ways) 
3. attempt download. some videos will not have audio or not be able to be downloaded at all, most will work.

### Expected behavior

Normal Download with audio

### Actual behavior

Download without audio, or no download

### Screenshots/Screen recordings

![Screenshot_20221024-063826](https://user-images.githubusercontent.com/80217805/197450453-0bb6d891-3f25-4d6d-a27f-996c0733f9aa.png)
(It sais in German: No streams to download found.)

<img alt="Screenshot_20221024-065012" src="https://user-images.githubusercontent.com/80217805/197450586-aa368516-b957-47b1-83b0-65901470aa10.png" height=600 />
(no audio to download with video; note that you still can download the audio seperately, so you could fix the video download by automatically doing that.)

### Logs

no logs currently, sorry

### Affected Android/Custom ROM version

Android 13/Google UI (latest)

### Affected device model

Google Pixel 6

**Comment by Feuerswut** [comment]
Yes, it works now *for this video*, can confirm, BUT the issue persists. It has something to do with YouTubes side of processing video. But the downloader should have an alternative mode where it just simulates streaming the video (which always worked).

**Comment by Feuerswut** [comment]
Again, same problem:
https://www.youtube.com/watch?v=VT5FCz-7DEA

![Screenshot_20221027-183255](https://user-images.githubusercontent.com/80217805/198348024-27eb5c62-d0b5-4fc9-a839-d23ca8a24ced.png)

**Comment by opusforlife2** [comment]
Reproduced.

**Comment by Feuerswut** [comment]
> @Feuerswut ?

Could not reproduce on latest version so closed this.
