### ISSUE TITLE
Add favourites (denoted by ❤ emote) and watch later

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9189]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add a favourites list (I.e. Just an empty playlist which reads favourites) typically denoted by a ❤ heart emote. Can be found in most of the apps.
Same applies for watch later list usually denoted by some sort of clock emote

### Why do you want this feature?

Reduces hassle of creating a new playlist if you need to quickly mark a video for later review. Basically i am asking for two empty playlist one which reads favourites and one which reads watch later. Users are already familiar with these options which make creating these types of empty list useful for a wide user base.

### Additional information

:)

**Comment by opusforlife2** [comment]
The very first checklist item is that you're supposed to check for duplicates.

**Comment by opusforlife2** [comment]
There is a search bar. You use keywords.
