### ISSUE TITLE
[FR] Double Tap on Notification to open current Playlist

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#919]
At the moment it is not possible to open NewPipe notifications from the lockscreen. A double tap on the notification should bring the same result as a single tap on it when the screen is unlocked.

**Comment by theScrabi** [comment]
confirmed

**Comment by TobiGr** [comment]
_Off-topic:_ @theScrabi We should close one of the Bug trackers for 1.0. Otherwise we will mess them up with different issues. You added this ticket only to the team internal project.

**Comment by theScrabi** [comment]
I see. You are right.

**Comment by theScrabi** [comment]
@karyogamy you changed that code.
Could you please take care of this issue.

**Comment by TobiGr** [comment]
The fix works. We get closer to version 1.0 👍

**Comment by theScrabi** [comment]
My fix is not complete. For me it does not work yet.

**Comment by TobiGr** [comment]
I meant @karyogamy's [fix](2837506ca58a2f295f01bd2b30a0815b0cadc6a8).

**Comment by theScrabi** [comment]
I see. What android version are you using, because is still get the issue.

**Comment by karyogamy** [comment]
> final Class clazz

Fixed.

@theScrabi Could you elaborate on the issue? Does nothing happen when you click on the notification on lockscreen? What android version are you using? I've only tested on 8.0 and emulated 7.1.1.

**Comment by theScrabi** [comment]
Yes androi 8 and android 7.11

**Comment by TobiGr** [comment]
Everything works fine with Android 6.0.

**Comment by theScrabi** [comment]
hm maybe I'm doing something wrong.

**Comment by karyogamy** [comment]
Yeah, this shouldn't happen on the emulator. Maybe check if you are running on the branch with the latest commit (updated after the rollback)? I'll create a PR if that makes it easier to switch.

**Comment by karyogamy** [comment]
@theScrabi Are we still fixing this?

**Comment by TobiGr** [comment]
@karyogamy I think so. We just wait for your pull request as you already fixed it :)

**Comment by theScrabi** [comment]
Aaah now i understand. The fix is not yet part of the main repo.

I shouldn't work when I'm at the congress and be heavily on chunk. 🙈

**Comment by theScrabi** [comment]
Sorry, yes @karyogamy you need to send a merge request first.

**Comment by karyogamy** [comment]
Thanks, I've just finished fixing a bunch of other bugs. Will put up a PR shortly after some testing =D

**Comment by theScrabi** [comment]
All right. Now it can be closed :)
