### ISSUE TITLE
Clone > RUN NewPipe in Android Studio 

### ISSUE THREAD

**Issue by abhijit420kb** [TeamNewPipe/NewPipe#9199]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest

### Steps to reproduce the bug

What I try....

- `git clone https://github.com/TeamNewPipe/NewPipe.git`
- Import in my android studio
- Sync gradle
- Try to DEBUG in emulator
- ERROR A LOT
- Then I found this doc `https://teamnewpipe.github.io/documentation/04_Run_changes_in_App/` 
- I got few  error like bellow

![Screenshot_4](https://user-images.githubusercontent.com/62204061/197885286-1e79570b-9fb2-41f5-81ef-885cbb2ae915.png)

**Then what I do**

- I clone NewPipeExtractor as well
- I edit `settings.gradle` uncomment :
```
includeBuild('../NewPipeExtractor') {
    dependencySubstitution {
        substitute module('com.github.TeamNewPipe:NewPipeExtractor') with project(':extractor')
    }
}
```
- Still get the error

![Screenshot_5](https://user-images.githubusercontent.com/62204061/197886419-4d7fe95c-0d3c-4120-a5f1-de7df0096f73.png)

![Screenshot_6](https://user-images.githubusercontent.com/62204061/197888132-81f319a5-3276-4459-bbe3-8b7d688dbf61.png)

**I also get so many error in res xml files**. No xml are not display/preview properly.

I use latest android studio.

Please anyone guide me how to build this repo in android studio. And make an APK from it.
And please don't mind for my noob like question.

**Comment by TobiGr** [comment]
Update your local branch to the latest dev and test if the issue in the original configuration (no changes in settings.gradle) persists. Your problems might be related to #9214.

Please do not post screenshots of errors, but the actual stack trace / error message because those can be copied / pasted.

**Comment by abhijit420kb** [comment]
OMG ... It working now :-) Love you so much
Actually I am finding some better way to display service progress in UI. same like the download progress.
I am using `BroadcastReceiver` but I feel noticeable lag UI update as well notification update.

I am using this app and I try to understand how this app update UI from service. that I try to build.

I found in this repo code "[us.shandian.giga](https://github.com/TeamNewPipe/NewPipe/tree/dev/app/src/main/java/us/shandian/giga)" you use as a download manager util.

and its not using `BroadcastReceiver` to update the UI from service. 

If you have little time can you please provide some reference how this magical things actually happens. I search a lot but I stuck . I need to know what should learn to understand this process.

Anyway thanks a lot again 👍

**Comment by abhijit420kb** [comment]
I think I got it, "[us.shandian.giga](https://github.com/TeamNewPipe/NewPipe/tree/dev/app/src/main/java/us/shandian/giga)" actually use callback interface listener for UI update ... ... 😍😍😍
