### ISSUE TITLE
[Bug/Feature Request] Disable Option for Troublesome Popups

### ISSUE THREAD

**Issue by Grossdm** [TeamNewPipe/NewPipe#920]
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.

I have very little interest in using the Popup feature, but it seems that many tasks in NewPipe cause it to spawn a Popup.
Once there is a Popup, I find it to be nearly impossible to get rid of it.

- Closing the NewPipe app doesn't work
- There is no listing of the Popup in recent apps to kill
- I have resorted to rebooting my device to kill a NewPipe Popup

It seems that an opt-out of Popups would help both users who don't want them, as well as users who would like to wait for the open issues on Popups to be resolved.

Thank you.

**Comment by theScrabi** [comment]
When a pop up shows up there is also a notification as long as the popup persists. You can tab on the X in then notification in order to close the popup.
Also you can sling the popup window to the side fast. That will also close it.

**Comment by Grossdm** [comment]
Thanks for your help on managing popup windows.

Would you consider a setting to disable popups?
I have no idea how difficult it would be to implement, but it sounds like it would be easy. 😆

**Comment by theScrabi** [comment]
We can close the main issue. However i would not want to add settings obtion for hiding ui elements.

**Comment by Grossdm** [comment]
Thank you for considering my request.
👍
