### ISSUE TITLE
Integrate seal as download manager

### ISSUE THREAD

**Issue by laraib07** [TeamNewPipe/NewPipe#9205]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Integrate [Seal](https://github.com/JunkFood02/Seal) as download manager. It can download audio, video and even playlist. It also has a nice UI. I also embed thumbnail and subtitles.

### Why do you want this feature?

Integrating Seal as download manager will give us long awaited option to download whole or partial playlist.

**Comment by laraib07** [comment]
@Master2050 navi can't download whole playlist, can it?

**Comment by opusforlife2** [comment]
Why? What's wrong with using Seal as a separate app?

**Comment by laraib07** [comment]
@opusforlife2 why install separate app when downloading is already a feature in newpipe! But it can be improved by integrating or *copying* seal as it does everything newpipe downloader does plus it also has an option to fully or partially download a playlist.

**Comment by opusforlife2** [comment]
What's the problem with sharing a video from Newpipe to Seal? It works perfectly well. Ignore the Newpipe downloader completely.

**Comment by laraib07** [comment]
@opusforlife2 Not a major problem! it's just one more app doing what newpipe should be doing already.

**Comment by PandoraHayami** [comment]
There's no reason to integrate a third party app because yes
