### ISSUE TITLE
Subtitles out of sync

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9208]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open https://www.youtube.com/watch?v=BISyIBU2gVY
2. Turn on subtitles there are two subtitles with same name (english) chose any one
3. Seek to the middle of video 
4. See 👀 subtitles go out of sync.

### Expected behavior

Subtitles should be in sync with video

### Actual behavior

Subtitles go out of sync

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1 CPH1861

**Comment by opusforlife2** [comment]
Check if they're in sync on Youtube.

**Comment by tsiflimagas** [comment]
Then it's not a problem of Newpipe specifically.
