### ISSUE TITLE
35,40,45,50,55,60 seconds forward and rewind search time

### ISSUE THREAD

**Issue by Nizami20052022** [TeamNewPipe/NewPipe#9212]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

35,40,45,50,55,60 seconds forward and rewind search time

### Why do you want this feature?

It's good to have more options

**Comment by opusforlife2** [comment]
Turn off fast inexact seek.

**Comment by Nizami20052022** [comment]
Fast inexact search is disabled.

**Comment by Nizami20052022** [comment]
![Screenshot_20221027-083823_NewPipe](https://user-images.githubusercontent.com/104249296/198192739-80f602a0-3711-4bab-b723-177f9246a10d.jpg)

**Comment by opusforlife2** [comment]
Yes. You can use one of these.
