### ISSUE TITLE
Why can a user create several playlists with the same name

### ISSUE THREAD

**Issue by sha-e-256** [TeamNewPipe/NewPipe#9216]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

This is something I've encountered a few times but have been unable to understand why it occurs.

Currently, you are able to make more than one playlist with the same name. Sometimes I accidentally create a playlist with the same name as a pre-exisiting playlist because when I add a video to a playlist I cannot view all my playlists before clicking "New Playlist". This can be frustrating because I would prefer if the video was added to the initial playlist instead of being added to a duplicate playlist.

The reason why I don't consider this a bug is because YouTube allows you to do the exact same thing: make several playlists with the exact same name. But I don't understand why you would want to do that; several playlists with the exact same name make navigation through your list of playlists more confusing.

Is there a specific reason as to why you are able to have several playlists with the same name? 

Thanks!

### Additional information

NewPipe version: 0.24.0
Android version: 12

**Comment by opusforlife2** [comment]
Ah, no reason. We could easily have a check for this. Please open a feature request asking for playlist names to be unique.
