### ISSUE TITLE
Shows Black Home Screen

### ISSUE THREAD

**Issue by Nibba2018** [TeamNewPipe/NewPipe#922]
Whenever i open the app it shows a black screen and never fetches videos from youtube even though my internet connection is good and fast enough, please fix this!!

**Comment by TobiGr** [comment]
Can you give us some more details please? What phone do you use,  OS, app version etc.
Did you already try to clean the cache?

**Comment by theScrabi** [comment]
I had similar issues, NewPipe sometimes only shows veery few videos form trending.

@SohamBiswas1 from which country are you using NewPipe from. That might be a hint.

**Comment by SohamBiswas1** [comment]
@TobiGr  @theScrabi 

My Device: Samsung Galaxy A7 (2015)
Model: SM-A700FD
OS: Android 6.0.1, Marshmallow
App Version: 0.11.1
Country: India

Did i Clean my cache before trying? -> Yes
Is my device rooted? -> No

Hope this helps.

**Comment by SohamBiswas1** [comment]
![screenshot_2017-12-16-23-05-06](https://user-images.githubusercontent.com/29832615/34072956-5126c428-e2b6-11e7-881b-5bdd449f7055.png)

This keeps loading forever

**Comment by SohamBiswas1** [comment]
@theScrabi  Nope :(, it just keeps loading forever :(

**Comment by TobiGr** [comment]
> I had similar issues, NewPipe sometimes only shows veery few videos form trending.

@theScrabi That's because of YouTube rewind and changing trending page on YouTube's site. We should improve the extractor to be more flexible.

But that should not cause endless loading. Also the trending page in India looks good atm. So I guess this a different problem.

**Comment by SohamBiswas1** [comment]
so is there any way to fix it?

**Comment by Stypox** [comment]
Is this still an issue? Trending has not given me any problem for a while now

**Comment by Nibba2018** [comment]
It works fine now actually, you may close it.
