### ISSUE TITLE
Videos thumbnail is to small

### ISSUE THREAD

**Issue by c7dl8p** [TeamNewPipe/NewPipe#9238]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Want to see big thumbnails like on yt 

### Why do you want this feature?

Because of small thumbnail i m facing headache 😐
And I m glasses user so facing lot of stress on eyes 
<img alt="Screenshot_20221029-185857" src="https://user-images.githubusercontent.com/112339868/198834309-237fc692-77cc-4cf2-aab5-a2440c9a5b3c.png" height=600 />

### Additional information

Something like this 
<img alt="Screenshot_20221029-185849" src="https://user-images.githubusercontent.com/112339868/198834278-feeb3103-5171-4f52-b65c-3f3fa2f8e768.png" height=600 />

**Comment by CeasarYT** [comment]
Plz sor add an option to change in both types 👌
