### ISSUE TITLE
Newpipe misses subscriptions

### ISSUE THREAD

**Issue by elvenkingfeanor** [TeamNewPipe/NewPipe#9239]
After refreshing All Channel group in Subscriptions, Newpipe skips a few. Clicking on those channels yields blank page.
Opening YT in a browser and copy-pasting links, plays the videos as usual.

**Comment by cernunnos1710** [comment]
Hi! I am unable to reproduce this bug. What do you mean by skipping a few?

**Comment by gsture** [comment]
I have the same problem since today. Some channels are empty after refreshing feed.

![Screenshot_20221029-161642](https://user-images.githubusercontent.com/31156691/198836403-5a02c381-5563-42c4-8cf1-0a265c84e8ff.png)

**Comment by gsture** [comment]
Looks like all channels with new content come up empty. Channels that had content but no new content after refresh keep their previously synced content.

**Comment by gsture** [comment]
Seems like channels with new content are empty after sync. Channels that where previously synced and have no new content keep there already synced content.

**Comment by gsture** [comment]
Fixed already? Nice, that was fast. When is update?

**Comment by m77e4t** [comment]
This is the original report of the bug https://github.com/TeamNewPipe/NewPipe/issues/9223.

Yours is a duplicate. Just do a 'thumbs up' on the original issue.
