### ISSUE TITLE
I cant play videos on 1080p

### ISSUE THREAD

**Issue by psicojazzo** [TeamNewPipe/NewPipe#924]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
Thanks for the app
I have a problem when I try to watch some videos in 1080p, especifically with termination in artitst "topic"
Example
https://www.youtube.com/watch?v=2QT2gefvgls
https://www.youtube.com/watch?v=uqM3AnHaFbw
https://www.youtube.com/watch?v=v4IEdLbC07s
Greetings from México

**Comment by theScrabi** [comment]
I cant even open one of these links.

**Comment by psicojazzo** [comment]
lol, I guess for geolocation, but they are  links that there were no problems formerly

**Comment by theScrabi** [comment]
No i used tor now. I can not open these links.

**Comment by psicojazzo** [comment]
Pretty strange, I changed of country to U.S with TunnelBear vpn and works good, with exception the 1080p, only 720p

**Comment by psicojazzo** [comment]
In Europe does not work this videos

**Comment by FaizKhan5** [comment]
Close this issue.
