### ISSUE TITLE
Change toast text color for dark mode

### ISSUE THREAD

**Issue by cernunnos1710** [TeamNewPipe/NewPipe#9241]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Any toast thrown by the app has text in white background if I run the app in dark mode. 

### Why do you want this feature?

It would vastly improve toast readability. As of now, it is almost a toast without text.

### Additional information

<img alt="Screenshot_20221030-024358" src="https://user-images.githubusercontent.com/57896620/198840802-a60e81cf-dacc-4b26-aec7-982afab22f5d.png" height=600 />

**Comment by cernunnos1710** [comment]
Oops, did not realize this was upstream specific.

**Comment by opusforlife2** [comment]
Sorry, what?

**Comment by AudricV** [comment]
See https://issuetracker.google.com/issues/245108402
