### ISSUE TITLE
Play queue lacks information about video 

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#9242]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Dev branch after #8946 is merged

### Steps to reproduce the bug

1. Watch any video on full screen
2. Close it
3. Start any video on background
4. Go to play queue via mini player before the buffering ends

### Expected behavior

Controls in play queue is shown as expected. 

### Actual behavior

No info is shown on play queue. 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/79245641/198848974-3bbf828c-35be-4bc1-a1ef-18f72cd9abb9.mp4

**Comment by Stypox** [comment]
Fixed by #9109, since the button is not available anymore when the queue is empty. Reopen if the empty queue is still accessible in some way.
