### ISSUE TITLE
[YouTube] Support channel handles

### ISSUE THREAD

**Issue by Symbian9** [TeamNewPipe/NewPipe#9243]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. In a web browser click on link with '**handle URL**' in a form of `youtube.com/@[handle_ID]`

For example, try next handle URL: https://youtube.com/@app4soft

### Expected behavior

*NewPipe* should be associated with such '**handle URL**' links and open it as other YouTube-channels.

### Actual behavior

*NewPipe* does not associated with YouTube's new '**handle URL**' links.

### Affected Android/Custom ROM version

Android 6.0

### Additional information

On October 10, 2022 YouTube introduced '**handle URL**' (`youtube.com/@[handle_ID]`) as a replacement to obsolete '**user URL**' (`youtube.com/user/[user_ID]`) and '**custom channel URL**' (`youtube.com/c/[custom_ID]`):

- https://blog.youtube/news-and-events/introducing-handles-a-new-way-to-identify-your-youtube-channel/

![img](https://storage.googleapis.com/gweb-uniblog-publish-prod/images/1_wDXB35T.max-1000x1000.png)

**Comment by Cryptophunk** [comment]
You can also access YouTube channels with handles without the @ but this bug fix does not include that. For eg https://www.youtube.com/@CharlieSolis works but https://www.youtube.com/CharlieSolis does not open up within Newpipe. But they both load properly on a web browser.

**Comment by Symbian9** [comment]
> Should I open up a new issue? New to using github. Thanks in advance.

Yes, @Cryptophunk, open new bug report.
