### ISSUE TITLE
HTTP 401 with every download (GrapheneOS)

### ISSUE THREAD

**Issue by crankc** [TeamNewPipe/NewPipe#9248]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Begin downloading a video
2. Watch as the download progress halts with HTTP 401

### Affected Android/Custom ROM version

GrapheneOS (Android 13)

### Affected device model

Google Pixel 7 Pro

### Additional information

Every video download begins OK but stops within seconds. The error NewPipe gives is HTTP 401.

This error is **not** present on another device of mine, which has LineageOS (Android 12). The same wifi is used, indicating there is no IP-address related issue. NewPipe is also given appropriate folder permissions to save the download, and it does actually finish but only if i manually resume the halted download dozens of times, indicating this isn't a storage- or permissions related issue either.

Raising the retry count to max (15) helps a little, allowing the download to go on slightly longer before erroring out with 401, but i still need to spank the restart button in order to finish the download.

Is this error NewPipe related, or GrapheneOS related? I will open a ticket over there if there is nothing you guys can do about it.

**Comment by opusforlife2** [comment]
> spank the restart button

Wot

**Comment by SC1040-TS2** [comment]
> > spank the restart button
> 
> Wot

The user appears to be applying Youtuber dialect to describing that action.

In an effort to generate popularity, Youtube influencers will use creative phrasing such as smacking, spanking, or otherwise for the Youtube Like button in the video's opening act, alongside wanting the viewer to hit Subscribe and the Notification Bell icon.

**Comment by crankc** [comment]
Funny.

Nevermind, problem sorted.

**Comment by opusforlife2** [comment]
@crankc It's beneficial for potential future issue-facers to know how you sorted the problem.

**Comment by crankc** [comment]
I'm sure. However, i came here looking for help, not jokes.

**Comment by etruj** [comment]
How was this resolved? I am hitting the same issue

**Comment by Zhafranilhamj** [comment]
have this same issue too so annoying have to constantly spank the restart button
