### ISSUE TITLE
Can't downgrade v0.24.0 to v0.23.x (using F-Droid v1.15.2)

### ISSUE THREAD

**Issue by JVeesha** [TeamNewPipe/NewPipe#9252]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Goto Newpipe App page in latest version of F-Droid (v 1.15.2)
2. Click on the Versions drop down menu at the bottom of the page
3. Click on drop down menu for v0.23.3 or v0.23.2
4. Click on DOWNGRADE button.

### Expected behavior

Expect FDroid to download the correct, older version of a Newpipe and then install it without any errors or lose of data.

### Actual behavior

FDroid seems to download the older app version, pops up a screen asking if you would like to install it, tries to install after you tell it to do so but fails due to an "unknown error".
See picture.
No crash report / log was created afaik.

### Screenshots/Screen recordings

<img alt="Screenshot_2022-10-30-16-16-48" src="https://user-images.githubusercontent.com/117047721/198907873-b9cb965a-71c2-4acd-bff9-9ccc52bec88e.png" height=600 />

<img alt="Screenshot_2022-10-30-16-51-13" src="https://user-images.githubusercontent.com/117047721/198908054-cd5a03c7-040b-4228-9cb4-9fdf3b3f9e35.png" height=600 />

### Affected Android/Custom ROM version

Android 8.0

### Affected device model

LG G6 (H873)

**Comment by tsiflimagas** [comment]
That's not a problem of NewPipe. I don't know why F-Droid provides an option to downgrade (maybe it works in conjunction with some module?) but Android doesn't allow users to downgrade apps. If you have to downgrade, then export your data from Newpipe settings, uninstall it, install the desired version and restore your data.

**Comment by JVeesha** [comment]
Okay good to know, but surprising!  Bad of Android for not allowing downgrades.

Anyway, I had wanted to downgrade so that I could verify if version 0.24.0 of Newpipe is loading thumbnails slower then it did in previous versions, because it feels like it is (everytime I close and then reopen the app).

**Comment by JVeesha** [comment]
Okay thanks everyone for the info on how to downgrade, and this being an Android issue not a Newpipe one.
