### ISSUE TITLE
Video screen always getting cut off/short on all videos; videos doesn't fit on screen 

### ISSUE THREAD

**Issue by dimyself** [TeamNewPipe/NewPipe#9253]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Idk if theres already an issue open with this, i didnt see it...i apologize if theres already one

On some videos i watch, the screen gets cut off in portrait mode...but most videos stream fine in portrait mode

Any video i try to watch in landscape mode, the top and bottom appear to be getting cut off...so effectively not all of the video fits the screen in landscape mode. Its every video i play

I play a video, and rotate screen to landscape... full video stream doesn't fit my phone screen , it gets cut off at the top and I believe also the bottom gets cut off as well

Some videos i play even in portrait mode is getting cut off. This particular video is an example. in youtube, it shows correctly, but in newpipe, in portrait and landscape it gets cut off:  https://youtu.be/2s2SeGzErUw

my phone is a pixel 6 pro running graphene os

installed newpipe from fdroid

Thank you!

### Expected behavior

video should fit screen correctly

### Actual behavior

If i need to provide more info or video or screenshots, i can do so. please let me know

### Affected Android/Custom ROM version

graphene os

### Affected device model

pixel 6 pro

**Comment by opusforlife2** [comment]
Have you tried toggling Fit/Fill/Zoom?

**Comment by dimyself** [comment]
> Have you tried toggling Fit/Fill/Zoom?

omg thank you so much...i didnt even know about this little menu.

changed it to fit fixed it, it was zoomed in! sorry about that!
