### ISSUE TITLE
Having a lot of subscriptions makes NewPipe fails and slows it down

### ISSUE THREAD

**Issue by leoossa** [TeamNewPipe/NewPipe#9259]
Currently having 1,5k+ subscriptions.
After having 700+ NewPipe started becoming slower and slower (especially regarding refreshing).
Now just about over 1,5k (can't say exact number) when refreshing feed it says it's going to refresh just 500+. Nevertheless subscriptions are visible in a proper tab (I think so)

**Comment by ThisIsPaulDaily** [comment]
If you click the (?) Button in the upper right corner, read the description, then enable fast mode, you'll get the result you want.

**Comment by ThisIsPaulDaily** [comment]
![756adb14-f964-40c0-bb7c-34d712a441e3](https://user-images.githubusercontent.com/11018948/199135099-231a7dc3-4eef-49b9-8bd2-3794b6b3ca6b.png)

**Comment by leoossa** [comment]
@SameenAhnaf 

No, I was actually using Android GH client (Fasthub-Libre). I will try to edit and insert template later on today.

Regarding fast-mode - thanks, it actually helped.

**Comment by opusforlife2** [comment]
> No, I was actually using Android GH client (Fasthub-Libre). 

Which is... drumroll...... an app.
