### ISSUE TITLE
Can't exit popup player

### ISSUE THREAD

**Issue by applesandsynths** [TeamNewPipe/NewPipe#926]
In the latest 0.11.1 release, I can't exit the pop up player by pressing the [ ] button. It is unresponsive. I have to restore to opening the appagain and force closing to get rid of it.  On a Note8, Android 7.1.1

**Comment by theScrabi** [comment]
This is a bug. However you can close it by fastly swipe the popup window to the side, or pull down the notification and press the X symbol.
