### ISSUE TITLE
'What's New' and Subscription Channels will not load video

### ISSUE THREAD

**Issue by mcmurphy8097234789** [TeamNewPipe/NewPipe#9264]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1: Swipe Down to update 'What's New'
2: Watch app query each channel that it is subscribed to
3: No new videos are added to feed
Note: When viewing a channel (like Linus Tech Tips) no videos are loaded on the channel page

### Expected behavior

I expect to videos to load on both the "What's New" page and channel pages

### Actual behavior

Videos (as in, thumbnails, links, video) simply do not load at all. In the case of viewing a channel page, the page is blank, save for the Channel banner and logo

### Affected Android/Custom ROM version

Android 13 / GrapheneOS

### Affected device model

Pixel 6a

### Additional information

Stopping app process, deleting cache and storage, and uninstalling, rebooting, and reinstalling did not fix this bug

**Comment by Fincentxyz** [comment]
Same here, refreshing the "What's new" page doesn't fetch new videos anymore.

Android 13, Graphene OS, Pixel 5

**Comment by Para-lyzed** [comment]
Just want to say that I'm experiencing this on LineageOS with Android 11 on a OnePlus 7 Pro, so this is not exclusive to GrapheneOS or Android 13.

**Comment by Emslaender73** [comment]
Same Problem here on Samsung Galaxy Tab S4

**Comment by AadityaJain-Dev** [comment]
I'm also experiencing this on Syberia OS with Android 12L on a Redmi K20 pro

**Comment by Arnesh1411** [comment]
Yes facing the same....also channels are not showing videos under subscription menu

**Comment by Dhangofa** [comment]
Same issue facing

**Comment by BlindSE** [comment]
Experiencing an identical issue on a Nothing phone (1) running android 12 and Nothing OS 1.4.4. Most likely related to #9223

**Comment by HPA4** [comment]
Experiencing same on both phone and tablet.  Went so far as removing subscriptions and re-importing a fresh google export and removing app altogether and reinstalling to no avail.

**Comment by jooker88** [comment]
Experiencing an identical issue on a Oneplus Nord 2 running android 12

**Comment by MeetMaratha** [comment]
Same issue on redmi note 7 pro

**Comment by UcraNerd** [comment]
Guys, for the feed try to use the fast mode (press the "?" on the top right); for the Subscription Channels I dont know.

**Comment by Dhangofa** [comment]
> Guys, for the feed try to use the fast mode (press the "?" on the top right); for the Subscription Channels I dont know.

Tried not working for me

**Comment by hakaci** [comment]
> Guys, for the feed try to use the fast mode (press the "?" on the top right); for the Subscription Channels I dont know.

It works for me

**Comment by AudricV** [comment]
Merging into #9223, as the origin of this issue is the same.

**Comment by HPA4** [comment]
> See: [#9263 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/9263#issuecomment-1298120778) as a temporary workaround.

This workaround does not work for me on either device.
