### ISSUE TITLE
News is no longer read

### ISSUE THREAD

**Issue by Emslaender73** [TeamNewPipe/NewPipe#9266]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

No more news (in German "Neuigkeiten") can be loaded, the list remains empty. I have already deleted the app data and installed it again, but it doesn't help. 

I only have this problem on my tablet (Galaxy S4), not on my mobile phone. So I think it's a local problem. Does anyone have any ideas?

**Comment by Emslaender73** [comment]
Sorry, i have missed https://github.com/TeamNewPipe/NewPipe/issues/9264

**Comment by BlindSE** [comment]
@Emslaender73 If you opened the issue by mistake, you are capable of closing it by yourself instead of waiting for triage/collaborators :)
