### ISSUE TITLE
[Feature Request] Translucent statusbar during video playback on 4.4 and above

### ISSUE THREAD

**Issue by daniellegal** [TeamNewPipe/NewPipe#927]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

It always Bothered me whenever i touch the screen during video playback the statusbar would appear opaque,but when i pull down the statusbar from the top its transparent.

**Comment by theScrabi** [comment]
This is a design issue of android. When there are widgets within the screen the bars turn black.

We can't change this.
