### ISSUE TITLE
Refresh Not Working

### ISSUE THREAD

**Issue by Phantom-Wolf** [TeamNewPipe/NewPipe#9270]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Any refresh to update released content from all subs brings nothing new in since 21hrs ago as of this writing. It is as if YouTube is blocking NewPipe from grabbing new content.

### Expected behavior

Swipe up to refresh content from sub's.

### Actual behavior

Swipe up, refresh runs through list of subs, nothing new aggregates into the list of new content. Last video shows 21hrs ago. However, if I search individually for a sub in the search bar, I can get their content that way. Very odd. Worked perfectly yesterday.

### Affected Android/Custom ROM version

GrapheneOS 13 (TP1A.221005.002)

### Affected device model

Google Pixel 6 Pro

**Comment by Chemus** [comment]
Same issue here. Galaxy A51, Android 12, New Pipe 0.24.0, 19+ hrs since last sub updated.

**Comment by jacekpoz** [comment]
Getting the same thing. Pixel 6, latest alpha GrapheneOS, NewPipe 0.24, last video 22 hours ago

**Comment by ohne-ende** [comment]
I have the same issue on my phone.
**Affected Android**
Android 12 (SP1A.210812.016)
**Affected device**
Samsung Galaxy S22 Ultra

I just checked it on my tablet, it doesn't work on that either.
**Affected Android**
Android 11 (RP1A.200720.012)
**Affected device**
Samsung Galaxy Tab S6lite

**Comment by tomcarlson** [comment]
Same issue here, both on pixel Phone and AndroidTV.

**Comment by Chemus** [comment]
Issue 9223 is what is appears to be a duplicate of. There is a workaround that I found there; switch to 'fast mode' is Settings >Content >Use Dedicated Feed Where Available
