### ISSUE TITLE
What's New Feed Isn't Updating

### ISSUE THREAD

**Issue by breaking-loss** [TeamNewPipe/NewPipe#9273]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Go to what's new
2. Refresh the content

### Expected behavior

The new content needs to be delivered from the sources

### Actual behavior

The what's new feed has stopped updating the videos since 2 days ago . I first thought it was that there was no new videos but calebcity and one village had post videos yesterday and feed isn't updating .

### Screenshots/Screen recordings

<img alt="Screenshot_20221102-070017_NewPipe" src="https://user-images.githubusercontent.com/110153010/199374073-cac14b79-1a03-4da1-9b1e-df20da750926.png" height=600 />
<img alt="Screenshot_20221102-070007_NewPipe" src="https://user-images.githubusercontent.com/110153010/199374082-868115bf-c297-44f9-b6f2-4417405d2524.png" height=600 />

### Affected Android/Custom ROM version

Corvus Os /Android 12

### Affected device model

Redmi 6 pro

**Comment by breaking-loss** [comment]
> Duplicate of #9223 and #9268

Isn't their issue related to channel page . 

> Check if turning on settings> content> fetch from dedicated feed helps or wait for a fix

This helped in fixing this thanks

**Comment by breaking-loss** [comment]
> Duplicate of #9223 and #9268

My bad

**Comment by mirko77** [comment]
Why was this closed? The issue still persists, the solution is a temporary fix.

**Comment by ashoklathwal** [comment]
https://wealthquint.com/fix-newpipe-feed-not-updating-63095/
