### ISSUE TITLE
Does not update 'what's new' section

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [TeamNewPipe/NewPipe#9284]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

What's new - > update list of new entries via icon at the upped righ corner -> update process stared and then finished -> nothing changed on a page (latest entry 2 days old)
Able to play videos, hence internet connection works.

### Expected behavior

Update shoould pull all recent videous in each subscribed channel

### Actual behavior

Update does not work

### Affected Android/Custom ROM version

Lineage 18.1

### Affected device model

Motorola g7

**Comment by TheDeadCell** [comment]
I think this bug may somehow be linked to the bug that fails to display videos while viewing a channel's page.

I have a similar issue, however one or two of my channels do show up in my feed. They are also the only channels that display the channel page properly.

**Comment by dslachut** [comment]
I just came to file the same bug. It's YT specific. I have SoundCloud and PeerTube subscriptions that still work correctly. It's YT channels that will not list videos and YT subscriptions that will not update. The problem with both began sometime late Sunday night (US East Coast time).

There is a similar thing happening with the unrelated Invidious project.
