### ISSUE TITLE
Disable counts

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#9294]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hi fellow dev i have idea to make counts can be disabled

Example:
View count
Like / dislike count etc²

### Why do you want this feature?

Because it's distract me
As  user i want to watching content without such distraction 🙏

### Additional information
Hi dev everything was fixed my apologize for my mistake due to human error 🙏

**Comment by NSTAdventure** [comment]
> Duplicate of #5201

I see sorry about that 🙏🥴
