### ISSUE TITLE
Add support for YouTube Alias Links

### ISSUE THREAD

**Issue by Feuerswut** [TeamNewPipe/NewPipe#9297]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Example Link:
https://www.youtube.com/@scowlowl

This Link will not open in NewPipe, it will open in YouTube or Web-Browser

The YouTube Alias Links .com/@<string>
whereas string is made up of only letters, numbers and _ (no spaces)

### Expected behavior

The app opens a channel tab for the corresponding channel

### Actual behavior

external app opened

Also Important: You cannot just remove the @ and replace it with c/ as you can choose the alias freely.

**Comment by AudricV** [comment]
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #9243. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

Note: this will be supported with the next release (try the release candidate)!

**Comment by Feuerswut** [comment]
@AudricV I did a search but didn't find it, my bad.
