### ISSUE TITLE
0.11.1 ignores rotation lock

### ISSUE THREAD

**Issue by badfish** [TeamNewPipe/NewPipe#930]
Runing on a large phone with 'rotation lock+landscape' installed from f-droid to lock it permanently into landscape mode for use as a tablet.
Playing video in 0.11.1 switches to portrait so the video occupies just 1/3 of the screen, and switches back to landscape when video ends. The 'rotate' button has vanished and turning the tablet has no effect.
Version 0.11.0 did not do this.

**Comment by theScrabi** [comment]
> The 'rotate' button has vanished 

The rotate button has not vanished, its in the three dots menu.
