### ISSUE TITLE
Unable to see videos of a channel when visiting channel info

### ISSUE THREAD

**Issue by Charan-ravi** [TeamNewPipe/NewPipe#9301]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Search keyword 'sam Beckman '
2. Result with videos displayed as usual
3. Click channel 

### Expected behavior

1.display the list of videos from that channel
2. Select one to play

### Actual behavior

Blank page with only channel name and background pic with a subscribe button displayed 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/52713551/200104937-55e80a03-79b7-40b8-a2db-b59877a4e635.mp4

### Affected Android/Custom ROM version

Android 12

### Affected device model

Nothing phone 1

### Additional information

Could someone tell me if this a feature to all or a bug which only I am facing ?

**Comment by mor88888888** [comment]
I'm facing exactly the same problem from 1 week ago aprox.

Newpipe 0.24.0
LineageOS 18.1 (Android 11)

**Comment by JS-dud3** [comment]
I am also facing the same issue on my honor 9s phone Android Version 10. I am also using other youtube client on my phone the same issue is happening over there also. But it gives me some info about the issue which is ChannelTabResponse failed with error code 2 null i think this the same issue causing newpipie to not display channel info hope this help.

**Comment by KiYugadgeter** [comment]
This issue has been fixed in 0.24.1 (Not released yet.)

Can you try using release candidate?
You can download it in below.
https://github.com/TeamNewPipe/NewPipe/issues/9292

**Comment by Ethanol6** [comment]
@KiYugadgeter the channels now display videos in 0.24.1.

**Comment by Ethanol6** [comment]
@Master2050 I used to see shorts and live streams up until this issue started.

**Comment by Ethanol6** [comment]
@Master2050 Ah, I see, this is hinging on the tab view implementation. Sounds good, thanks!
