### ISSUE TITLE
View channel details

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#9302]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

This feature is related to Channel tabs #9182 

When I'm on the tab channel, I can't enter the details (Shorts, Live, Playlists); however, when I'm on the Playlist tab, I can click on the channel name and icon, and I can view the channel details (Shorts, Live, Playlists).

<img alt="Screenshot_20221105-095417_NewPipe channel-tabs" src="https://user-images.githubusercontent.com/11852634/200111895-3db449a7-ed3e-4928-af45-70deb1e88fa2.jpg" height=600 />

<img alt="Screenshot_20221105-091524_NewPipe channel-tabs" src="https://user-images.githubusercontent.com/11852634/200111774-0af70caf-a128-4f2f-851f-eaf81169944e.jpg" height=600 />

<img alt="Screenshot_20221105-091741_NewPipe channel-tabs" src="https://user-images.githubusercontent.com/11852634/200111780-e2d74dbc-5c46-486d-82ec-f06b7828437f.jpg" height=600 />

### Why do you want this feature?

I need to quickly enter to the channel details

**Comment by opusforlife2** [comment]
> This feature is related to Channel tabs

**Comment by opusforlife2** [comment]
> This feature is related to Channel tabs

That's still a PR. Any feedback you want to give should be within the PR, not in a new issue.

**Comment by heberjeur** [comment]
I have the same problem like "Sameen"
https://github.com/TeamNewPipe/NewPipe/pull/9182#issuecomment-1304591106
