### ISSUE TITLE
Channels and Channel groups empty (since November)

### ISSUE THREAD

**Issue by lameventanas** [TeamNewPipe/NewPipe#9307]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Click on a subscribed channel or channel group
2. No videos are visible (these channels do have videos)

### Actual behavior

Since November, the list of videos is empty or isn't updating.
In the channel groups I can see videos that were released until November 1st.

### Affected Android/Custom ROM version

Android 10

### Additional information

Tested using a proxy in the US, just in case it was a region thing of Youtube.

**Comment by lameventanas** [comment]
@opusforlife2 duplicated where? I looked everywhere

**Comment by tsiflimagas** [comment]
Everywhere? It's pinned and there's a dozen of duplicates, you just can't miss it.
