### ISSUE TITLE
Can't play any video

### ISSUE THREAD

**Issue by krablord** [TeamNewPipe/NewPipe#9309]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Play any video from anywhere

### Expected behavior

Video should play or try to buffer

### Actual behavior

Video is stopped right away with error message

## Exception
* User Action: play stream
* Request: Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=nzgzng2hb50
* Content Country: US
* Content Language: en-US
* App Language: en_US
* Service: YouTube
* Version: 0.24.0
* OS: Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

com.google.android.exoplayer2.E
xoPlaybackException: Unexpected runtime error
 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:203)
 at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalArgumentException
 at android.media.MediaCodec.native_setSurface(Native Method)
 at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1914)
 at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.setOutputSurface(SynchronousMediaCodecAdapter.java:189)
 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
 ... 3 more

</details>
<hr>

### Affected Android/Custom ROM version

7.0

### Affected device model

Meizu M5 Note

### Additional information

This started around the same time when Sub list stopped updating, suddenly no video can play and I didn't update new pipe from I believe 0.23.1 it was - as it sometimes required to update for things to start work again, I updated to 0.24.0 and things stood the same. Also I tried 0.24.1 test - and same thing happens.

**Comment by ardumpl** [comment]
Make sure you have been read 2nd point of checklist

Refer to this
https://github.com/TeamNewPipe/NewPipe/issues/9223

Then, close your issue

**Comment by krablord** [comment]
duplicate of 9223 - [https://github.com/TeamNewPipe/NewPipe/issues/9223](url)

**Comment by opusforlife2** [comment]
@krablord It's not. Why do you think so?

**Comment by krablord** [comment]
@opusforlife2 I was lead to believe in private email from I assume moderator(?). I don't want to spam with duplicate issues and make it harder to track issues.

**Comment by opusforlife2** [comment]
Mods don't send private emails. Please report who this person was. And in future make sure you confirm that a person with the "Member" or "Collaborator" tag has provided you the information before assuming that it is from the team.

**Comment by krablord** [comment]
I was sent replies to my thread that I don't see on github, so I assumed it was from the team and those messages are just not visible. Where can I report something like that? I cant find anything about it

**Comment by opusforlife2** [comment]
Sent on email? Yeah, if you're unsure, report these to Github. There's a "Contact Github" link in the footer.

**Comment by krablord** [comment]
Exactly the same way I got notifications (notifications@github.com) about comments right now on specified email, I got same notifications but they are not visible in this topic.
Thank you - will do that.

**Comment by opusforlife2** [comment]
If you're willing to share the username of this person, we could see if anything can be done from our end.

**Comment by krablord** [comment]
I got comment from Deek Pramana about closing issue - hope that helps.

**Comment by opusforlife2** [comment]
No, that doesn't ring any bells. Oh well, Github Support should be much more helpful.

**Comment by krablord** [comment]
can confirm - works in portrait mode with 0.24.1 and errors with fullscreen
