### ISSUE TITLE
Fix Lithuanian anc Czech translation

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#932]
Within [this commit](https://github.com/TeamNewPipe/NewPipe/commit/f58c95840a82f0d6fc232b8e56446a6b73f764fe) we noticed a but in the weblate translation.

Should be fixed.

**Comment by TobiGr** [comment]
The Czech translation needs a fix too.

**Comment by r2308145** [comment]
yes, its not showing subscribers count

**Comment by TobiGr** [comment]
@theScrabi I created a small [Java program](https://gist.github.com/TobiGr/55a05c58d9d09e63cef03eb04f9fe1e0) which removes all wrong plurals. Please run it before every release until the Weblate bug is fixed.

**Comment by theScrabi** [comment]
So I guess I'm supposed to run this programm using the `-r` parameter right?

**Comment by theScrabi** [comment]
pushed your programm together with a little script to main repo:
https://github.com/TeamNewPipe/NewPipe/commit/3a84c47176c1ad196c8352ac918d8899b5f6b92d
