### ISSUE TITLE
NewPipe doesn't load new videos in the "What's New" tab 

### ISSUE THREAD

**Issue by s3rgi0-pr0grAmm3r** [TeamNewPipe/NewPipe#9323]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.0

### Steps to reproduce the bug

1º Open the app
2º Go to the "What's new" tab
3º Scroll down to refresh the "What's New" tab

### Affected Android/Custom ROM version

Android 7

### Affected device model

Xiaomi Redmi Note 5

### Additional information

If I try to manually enter a channel I'm subscribed to, it doesn't load any videos either. Until 5 days ago it worked perfectly. I have also tried it on another device and the same thing happens.

**Comment by M1cR0xf7** [comment]
#9223
