### ISSUE TITLE
"Left arrow" button should go back, not exit search

### ISSUE THREAD

**Issue by probonopd** [TeamNewPipe/NewPipe#933]
"Left arrow" button should go back to the search results, not exit search. Having to re-type the search terms each time is frustrating.

**Comment by theScrabi** [comment]
Use the bottom arrow button, it behaves different.

**Comment by probonopd** [comment]
I found that out, but I am using the top button all the time inadvertently. I doubt I am the only one. Is there any way to make the top button work like the bottom arrow button?

**Comment by theScrabi** [comment]
Yes well, we had this discussion before, but maybe we have to reopen it again.
