### ISSUE TITLE
F-droid update to version 0.24.1

### ISSUE THREAD

**Issue by TriggerDingus** [TeamNewPipe/NewPipe#9338]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

I notice all the Youtube channel issues were resolved last week and I've been waiting for the updated F-Droid package to drop, but so far it hasn't. Could someone nudge the updates to F-droid?

**Comment by opusforlife2** [comment]
Your Fdroid client needs an index update.
