### ISSUE TITLE
App crashing randomly.

### ISSUE THREAD

**Issue by Merijn9** [TeamNewPipe/NewPipe#9339]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

2.4.1

### Steps to reproduce the bug

1. open the app
2. Click on a video
3. Maybe rotate the phone
4. Close the video

I'm not sure how it happens. It happens pretty random but mostly when I open or close video's.

### Expected behavior

Not crashing

### Actual behavior

App crashing

### Affected Android/Custom ROM version

Android 12

### Affected device model

Realme gt neo 2t

**Comment by Girildo** [comment]
I don't know whether it's the same issue I'm facing: I noticed the app crashing after ~10 seconds of playing a video. Upon restart, attempting to play the same video works as expected. 
I observed this behavior to be pretty consistent since 0.24.1

**Comment by opusforlife2** [comment]
We need logs to see if this is the same as 9277 or a different bug.

**Comment by Merijn9** [comment]
Yes this is the same issue, sorry for the confusion.
