### ISSUE TITLE
Videos added to background audio player not showing in history 

### ISSUE THREAD

**Issue by xvg2** [TeamNewPipe/NewPipe#934]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

As per description. Videos which are being added to the background audio player don't show up in watched history.

**Comment by Stypox** [comment]
This does now work
