### ISSUE TITLE
Continue playing during interruptions (phonecalls, notifications,etc)

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9345]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Continue playing video/audio during interruptions like phonecalls 

### Why do you want this feature?

1.  if you don't want to attend a call and also don't want to reject it(may be annoying friend) as the other person will know that you rejected the call or someone calls you multiple times using WhatsApp or other social networks.

2. If the ringer(incoming call ringtone) volume is zero it still keeps the player paused.

*Still conused? Here is a simpler version*

If i reduced the ringtone volume of incoming call to zero that is my phone is on mute or DND is active then I should be able to enjoy the music at full volume regardless of the incoming call the player should not pause just 'cause i don't want to hang up incoming call as it will let the other person know that i am not picking up his/her call which in turn will make to give some annoying friend excuse like oh I was in the bathroom 

### Additional information

Nothing here just crickets

**Comment by tsiflimagas** [comment]
That's already implemented.

**Comment by opusforlife2** [comment]
This isn't a Newpipe problem. It's specific to your OS settings. You can change them. I just tried it. The video continued to play at the same volume despite getting a phone call when I put the device on vibrate. I'm on LOS. Your settings might be different.

**Comment by opusforlife2** [comment]
What have you tried so far? Vibrate? Mute? Tweaking the call notification?

**Comment by opusforlife2** [comment]
Edit your one comment instead of making 3 back to back. 🤦

You don't have a vibrate setting for your ringer?

**Comment by opusforlife2** [comment]
Then this is a bug with your specific OS. Which is...?

**Comment by opusforlife2** [comment]
We've established that it's a problem with your OS. You can only rely on the (slim) possibility of someone with the same OS coming across this and having the know-how to implement a fix.
