### ISSUE TITLE
Change "help" to "Fast mode" in three dot menu on what's new feed kiosk 

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9348]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Help seems deceptive and non self explanatory Fast mode will be a more explanatory and appropriate title for fetching from rss feed. Here is a screenshot for some context.

<img alt="Screenshot_2022-11-09-02-17-55-61_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/28833686/200672739-e95db0ad-727c-4237-8ce2-2841280d76af.png" height=600 />

### Why do you want this feature?

GUI update, more user friendly, easy to use

### Additional information

Nothing special here

**Comment by pratyaksh1610** [comment]
Hi @Master2050 , I would like to contribute to this.

**Comment by pratyaksh1610** [comment]
I am unable to reproduce the issue, I think the three dots menu has been removed. 

![debug](https://user-images.githubusercontent.com/76740999/204796090-075ef55d-3bfb-4c80-8352-dbc49931a30b.png)

**Comment by opusforlife2** [comment]
@pratyaksh1610 You need to try a smaller display, or increase your display size from settings so that the buttons become crowded enough and get pushed into the 3 dot menu.
