### ISSUE TITLE
Shift player notification from appearance to notification in settings 

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9350]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The player notification option should be placed in notifications settings not under appearance settings

See screenshot below
Appearance menu:
<img alt="Screenshot_2022-11-09-09-41-49-47_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/28833686/200736936-0658998e-0d2e-4fe4-8713-a0719ad468b8.png" height=600 />

Notifications menu:
<img alt="Screenshot_2022-11-09-09-45-20-44_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/28833686/200737338-9b44837b-9a52-4f40-9aff-a72ac0b61676.png" height=600 />

### Why do you want this feature?

It feels deceptive and may lead to user not finding the required feature

**Comment by opusforlife2** [comment]
@Master2050 You're opening too many issues that are turning out to be duplicates. Which means you're regularly ignoring the checklist. Please stop opening issues for a week. Instead, whenever you get an idea for a feature or think of a bug, go through the existing issues instead. Don't make extra work for the maintainers. We don't have unlimited time.
