### ISSUE TITLE
Remove unnecessary night theme selection in appearance section of settings 

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9353]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Remove unnecessary night theme selection in appearance section of settings when theme selection menu is already present. See screenshot below 
<img alt="Screenshot_2022-11-09-14-37-30-01_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/28833686/200788350-e734f679-1389-4e43-b5a4-c4ef8783f18d.png" height=600 />
<img alt="Screenshot_2022-11-09-14-37-40-13_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/28833686/200788382-8b53e8f4-84b0-49f9-8f21-6ce92cf8e5bc.png" height=600 />
<img alt="Screenshot_2022-11-09-14-37-35-34_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/28833686/200788392-31566ae7-7b8b-4886-bbb6-94aed7835c0e.png" height=600 />

### Why do you want this feature?

Unnecessary and may cause confusion 

### Additional information

![IMG_20221109_144247](https://user-images.githubusercontent.com/28833686/200789139-8eced9ae-78c2-42fb-8113-a2e854605750.jpg)

**Comment by Jared234** [comment]
I'll work on it and create a PR soon.

**Comment by opusforlife2** [comment]
@Jared234 Please show your changes here before opening a PR.

**Comment by B0pol** [comment]
It's not unecessary, it's useful for users that want black mode instead of dark as automatic night theme. 

On top of that it's not confusing, if you select any other theme than automatic this night theme selection is removed.

It has been made in a separate selector as at some point, there was a terminal dark theme PR (like green / black theme), and in the future we may add other themes.
With what @SameenAhnaf that would make one more option everytime.

**Comment by Jared234** [comment]
I have already worked on the fix that @SameenAhnaf's suggested. 
IMO if there are only two options, this approach is preferable. However, I agree that if multiple auto themes will be introduced in the future that @B0pol's solution should be implemented.

Here is a short preview of what I changed:
https://user-images.githubusercontent.com/26669009/202905800-b497caee-469d-40db-ad6b-5e6ecd0fc125.mp4
After implementing it, I would actually prefer "Auto (Dark for Night)" and "Auto (Black for Night)".

But what do you think about it? Should we go with @SameenAhnaf's solution until more themes are introduced? Or should we leave it as it is right now?

**Comment by Jared234** [comment]
Hmm... I think that just graying it out would be even more confusing. When I see the "Night Theme" option but it is grayed out, I don't immediately know what to do to "activate" it again.
