### ISSUE TITLE
Youtube content restriction toggles should not be independent

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9354]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).-

### What is/are your question(s)?

How can i turn both restricted mode and show adult content side by side? What happens if i turn both on will it show me something interesting 🤔 (you know what i'm talking about) or maybe not see screenshot below.

<img alt="Screenshot_2022-11-09-17-09-14-82_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/28833686/200821735-56f144ea-79de-49ea-a763-36540a462e59.png" height=600 />

### Additional information

Nothing special here

**Comment by Stypox** [comment]
Those two toggles have different meanings and are independent of each other.
- The first toggle is not related to which content appears in search results or trending or channels. It just makes the `VideoDetailFragment` refuse to play and display information about videos for which Youtube/soundcloud/... has an age limit.
- The second toggle instead is YouTube-specific and is passed to YouTube requests to restrict potentially mature content (equivalent of restricted mode in the official Youtube website)
