### ISSUE TITLE
bug report for new pipe 

### ISSUE THREAD

**Issue by manngtm** [TeamNewPipe/NewPipe#9355]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

go to  "subscribe " channels and then you can see 

### Expected behavior

Hi New Pipe Team,

Tks for the updated 0.24.1 version.  Yet, there is still a bug that when we switch to the saved channels,  it can't show the live streaming videos.  So, when we like to watch live broadcasts , we still need to go back to YouTube ！！！

Please advise if this bug can be fixed shortly. 

Tks

**Comment by opusforlife2** [comment]
When you receive an app update, you should read the change log or any new blog posts.
