### ISSUE TITLE
Newpipe Clone filled with ads published on the play store

### ISSUE THREAD

**Issue by Monoxide8969** [TeamNewPipe/NewPipe#9356]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hi, I've recently come to know that there is a newpipe clone published on the play store filled with ads. How could we help? Should we report it to google? I'm pretty sure they've not respected newpipe license, and it 100% violates google TOS. What's the best course of action here?

### Additional information

The link to the clone is https://play.google.com/store/apps/details?id=com.newpipe.protube

**Comment by opusforlife2** [comment]
Thanks, it's known. #539.
