### ISSUE TITLE
Clicking on hyperlink in youtube does not go to newpipe

### ISSUE THREAD

**Issue by AnthonyTheKoala** [TeamNewPipe/NewPipe#9362]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Go to the newpipe app.
2. Get a youtube video example https://youtu.be/w6GJHbxUc6M
3. Paste link in newpipe search.
4. Under the description tab you see hyperlinks
5. When I click on the hyperlinks under the description
https://bit.ly/3jd1W7s
https://www.youtube.com/watch?v=rDQ0zdEx2Ac
https://youtu.be/w6GJHbxUc6M
6. None of the hyperlinks go to a youtube video within newpipe. 
7. Instead clicking on any hyperlink within newpipe goes to the youtube app NOT newpipe.

Note that I cannot find this issue in the newpipe github.

### Expected behavior

I expect that when I click on the hyperlink within newpipe, I expect the video to be displayed in newpipe, not activate the youtube spp.

### Actual behavior

When you click on the hyperlink within the newpipe app, you don't see the hyperlinked video go within newpipe. Rather the hyperlinked video goes to the youtube app.

### Affected Android/Custom ROM version

Android 12

### Affected device model

LM-G900EM

**Comment by AnthonyTheKoala** [comment]
Dear Master2050,
Thank you for the reply.
Good news: when invoking a non-youtube hyperlink, it will direct the default browser. The default browser is set by:
* goto Settings.
* click on apps
* click on default apps
* click on browser app. Select say Kiwi as default browser.

Bad news: cannot invoke youtube video by clicking on youtube video hyperlink within newpipe. This time invoking youtube video invokes default browser rather than newpipe:
* settings for youtube app:
   Settings > Apps > App Info 
    Select youtube.
    Select "open by default" 
    Select "open supported links"
    Select "do not open in this app"
The result is that youtube links within newpipe don't invoke videos with newpipe. Rather these videos are invoked in default browser.

Thank you,
Anthony, Sydney

**Comment by opusforlife2** [comment]
I was quite sure this was a duplicate but even I can't find the mythical original issue for this.

**Comment by opusforlife2** [comment]
The solution is to rewrite links like Piped and Nitter do.

**Comment by AnthonyTheKoala** [comment]
Thank you for that.
A remark about supported links in newpipe's app settings.

For example there are variations in the name of the youtube url. Examples youtube.com, youtu.be, m.youtube.com.

The newpipe app's link settings has the list of recognised variations of the url.

Should there be a url of the form bit.ly, I can see a potential bug where the url of the bit.ly format may resolve to either a non-youtube site OR youtube video. This is because bit.ly is another server.

Thank you,
Anthony, Sydney

**Comment by languagemaniac** [comment]
> @languagemaniac Try this with Firefox.

I get the same result![Screenshot_20230429-212503_Firefox.png](https://user-images.githubusercontent.com/43100450/235320748-55b76646-8a55-45cf-9868-206f39f8c4e4.png)

**Comment by languagemaniac** [comment]
> Did you fiddle with the Open links in apps setting?

Nope, I checked the app's settings to see if I could, but I saw no options to do so

**Comment by languagemaniac** [comment]
> I mean the settings inside the app. There's a menu.

I didn't, but now I have it a look and saw that "open links in apps" was set to "never" although I didn't set that up, I just installed Firefox to try it it would work.

It does work now

Would be nice if I could open links with brave browser which is the browser I use though, but thanks for letting me know it's a browser related issue

**Comment by twiclo** [comment]
If you're using the Kiwi Browser, as I know at least @AnthonyTheKoala is doing, then you need to disable a browser setting that prefers links to be opened with Kiwi rather than other applications.

![image](https://github.com/TeamNewPipe/NewPipe/assets/25187100/fe9a9962-805f-48ea-bb77-e628e9ab84c9)
