### ISSUE TITLE
Option to search on original text, not corrected text

### ISSUE THREAD

**Issue by rogerval** [TeamNewPipe/NewPipe#9364]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Provide an option to search on the user's original spelling of a search term, not the auto corrected version.

### Why do you want this feature?

I can't find certain videos or accounts as they're often misspelt on purpose by the content creator.

**Comment by rogerval** [comment]
Opusforlife I hope my modified request is ok now? 🙏

**Comment by opusforlife2** [comment]
> I'd be happy to know the issue number.

You're supposed to do that work, which is why it is an item in the checklist for you to tick. If you fail to find a relevant duplicate, you can say so in your issue description, and someone can point you in the right direction. 👍
