### ISSUE TITLE
Nothing Shows Up Under Youtube Subscription Channel Video List

### ISSUE THREAD

**Issue by powline99** [TeamNewPipe/NewPipe#9369]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

Goto New Pipe
Open Subscriptions
Opens Up Channel Image and Subscribed area
No Videos Beneath

Tried clearing cache, reinstalling app and importing data in again. No change.

### Expected behavior

Show Channels Videos

### Actual behavior

Nothing In Video Area
Using Dark Theme

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Pixel  4XL

**Comment by opusforlife2** [comment]
?
