### ISSUE TITLE
Can't switch to full player in popup mode

### ISSUE THREAD

**Issue by entriol** [TeamNewPipe/NewPipe#937]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

When I click full screen icon (right-top) on popup mode, it does nothing.

![](https://cdn.pbrd.co/images/GZHtv2g.jpg)

**Comment by theScrabi** [comment]
Fixed.
