### ISSUE TITLE
Swipe down gesture to exit full screen

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9372]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add a swipe down gesture on video to exit full screen like in YouTube 

### Why do you want this feature?

User experience enhancement, GUI update, users are already familiar with this feature as in YouTube, saves time and effort

### Additional information

Opening in favour of closed issue #7660

**Comment by opusforlife2** [comment]
The title area is the trigger. It isn't small at all.
