### ISSUE TITLE
Reminder for videos to watch later 

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9376]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Reminder to watch videos later

### Why do you want this feature?

Seems interesting and useful, user experience enhancement 

### Additional information

May increase battery consumption just guessing

**Comment by opusforlife2** [comment]
Use a reminder app?

**Comment by opusforlife2** [comment]
Try not to open frivolous issues that you don't actually care about.
