### ISSUE TITLE
Changing orientation while viewing metadata of a video takes back to currently playing video 

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9383]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1, channel tabs debugv4, nightly 15

### Steps to reproduce the bug

1. Start playing any video/playlist in background
2. Click on any video not present in playlist/queue
3. Rotate the device by 90 degrees i.e switch between landscape and portrait orientation mode
4. The metadata changes to that of currently playing video

### Expected behavior

The metadata requested should not vanish

### Actual behavior

Metadata changes to that of currently playing video 

### Screenshots/Screen recordings

Reduced bitrate for upload still over 1000 kbps

https://user-images.githubusercontent.com/28833686/201466073-5cbda5f6-5499-4c88-81eb-7bf7456c22c5.mp4

### Logs

Nothing special here 

### Affected Android/Custom ROM version

Color OS v6.0(android 9) Non rooted

### Affected device model

Oppo Realme 1 CPH1861

**Comment by opusforlife2** [comment]
Sigh. @Master2050 This is the second time I'm telling you. Please search harder for duplicates before opening an issue. It's not uncommon for the process to take more than 2 minutes.
