### ISSUE TITLE
thumbnail missing and displayed file length 0 on some downloaded videos

### ISSUE THREAD

**Issue by pabloski80** [TeamNewPipe/NewPipe#9386]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1 choose a folder fir videos or have it set previously
2 download successfully this video: https://www.youtube.com/watch?v=-NK_Ahc8n2E for example in 240p resolution

### Expected behavior

The displayed file length either in Samsung my files or in ghost commander, should be nonzero, thumbnail should be nit a one as displayed on invalid files

### Actual behavior

Fusplayed file length is zero, thumbnail is default for empty file

### Affected Android/Custom ROM version

5.0.1

### Affected device model

Samsung s4

**Comment by opusforlife2** [comment]
Just tried your video and resolution. Works fine. Could be a one-off download error. Try again. Then try with a different video. Then try with a different device.

**Comment by pabloski80** [comment]
It happens on Samsung galaxy S4 android 5.0.1
It doesn't though on Samsung j5 android 6.0

I had it on one more video with flag emoji in name too.

Probably not worth looking further as it must be either old android or specific device.
