### ISSUE TITLE
Sync-Play

### ISSUE THREAD

**Issue by dejalavidavolar** [TeamNewPipe/NewPipe#9389]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hi everyone. 

Is there a way to listen music or watch video with NewPipe? Something like "https://syncplay.pl/" but with this app?

Best Regards

**Comment by opusforlife2** [comment]
Since MPV is already known to work with that service, you could use mpv-android (yt-dlp fork) to do this.
