### ISSUE TITLE
Odia translation completed

### ISSUE THREAD

**Issue by GET100PERCENT** [TeamNewPipe/NewPipe#9393]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I have completed Odia translation using the weblate. Add "Odia" language to Newpipe.

### Why do you want this feature?

Odia is the mother tongue of about 10 crores of people.

**Comment by GET100PERCENT** [comment]
Yes, and it's not supprising, as Odia is the official language of Odisha, a state of India having large population.

**Comment by TobiGr** [comment]
The language still needs to be added to the language chooser in NewPIipe, see #9179
