### ISSUE TITLE
Ability to set audio bitrate for background play

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9397]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Ability to set audio bitrate at which the video is played in background. This can be implemented in the following ways:
- Add a drop-down menu beside background 
 button
- add an option in settings page with options like least possible, max possible, etc.
- add an audio quality selection menu beside video quality in video player screen
- ability to remember the last selected audio quality 
- if possible also implement for livestreams

### Why do you want this feature?

Data saving and efficient use, versatility

### Additional information

Probably a duplicate but I can't find one

**Comment by opusforlife2** [comment]
Ask, then. We have an IRC channel where people frequently ask if their issues are already reported.
