### ISSUE TITLE
Cant delete subscribed channel which has been terminated

### ISSUE THREAD

**Issue by r2308145** [TeamNewPipe/NewPipe#940]
If you subscribe to a certain channel and this channel (account) gets later deleted from youtube, then there's no way how to erase this channel from your subscribed list.. all you get is an error message

**Comment by r2308145** [comment]
So, this will get eventually repaired? Can't see it in the fix bugs Projects page

**Comment by theScrabi** [comment]
What error do you see when this happens?

**Comment by r2308145** [comment]
{
   "user_action": "requested channel",
   "request": "https:\/\/www.youtube.com\/channel\/UCx0Avg-pKltPxU2EibUyqgQ",
   "content_language": "US",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.11.4",
   "os": "Linux Android 7.0 - 24",
   "time": "2018-01-20 22:46",
   "ip_range": "194.108.0.0",
   "exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel name\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeChannelExtractor.getName(YoutubeChannelExtractor.java:102)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:69)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:60)\n\tat org.schabi.newpipe.util.ExtractorHelper$5.call(ExtractorHelper.java:107)\n\tat org.schabi.newpipe.util.ExtractorHelper$5.call(ExtractorHelper.java:104)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:45)\n\tat io.reactivex.Single.subscribe(Single.java:2801)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:2801)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:3749)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:13068)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:3749)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:2801)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)\n\tat java.lang.Thread.run(Thread.java:776)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeChannelExtractor.getName(YoutubeChannelExtractor.java:100)\n\t... 28 more\n"
   ],
   "user_comment": ""
}

**Comment by r2308145** [comment]
Is this enough or do you want to see the screenshot?

**Comment by theScrabi** [comment]
Ah i see, its such an error :) thanks

**Comment by Cormak** [comment]
Just came across this issue with subscriptions to channels that don't exist anymore. Perhaps a long press and delete function will be enough?

**Comment by r2308145** [comment]
and it's quite needed when almost half of your subscribed list are dead channels

**Comment by theScrabi** [comment]
@Somethingweirdhere You already took care about the share menu, could you please take a look at this? :)

**Comment by Somethingweirdhere** [comment]
I was thinking if there is a way to remove the non-existant channels automatically, or at least catching `ParsingException: Could not get channel name` and showing the dialog with an option to remove the channel.

Maybe there are other ocassions when this exception is thrown, but I feel like an error message with possible causes (like channel doesn't exist or youtube currently has issues, do you want to unsubscribe?) would be better than an app crash.

Anyways, think about that. A long-click delete would be nice anyways, I can get working on that. Are there any other options we should have in the long press menu?

**Comment by Cormak** [comment]
@Somethingweirdhere An automatic function seems like more work (and creating more issues) than the simple solution of having a long-press delete function, which should have been included to begin with.

**Comment by theScrabi** [comment]
> Maybe there are other ocassions when this exception is thrown, but I feel like an error message with possible causes (like channel doesn't exist or youtube currently has issues, do you want to unsubscribe?) would be better than an app crash.

If the app crashes we can catch that exception and show a dialog. I think this would be ok.

**Comment by Somethingweirdhere** [comment]
#1516 The menu works, the deleting not though. Calling delete like I did it doesn't do anything, it seems to only work the exact same way that ChannelFragment does it, but this would mean it has to get the channel from youtube first, which it can't when it's deleted.

**Comment by TobiGr** [comment]
@Somethingweirdhere  has this been fixed with #1516? I think so, but had no time to test it.

**Comment by Somethingweirdhere** [comment]
@TobiGr I strongly assume so, as I can delete a channel now without having an internet connection, so it's existance shouldn't matter at all. That said, I wasn't able to add an non-existant channel in any way I tried, so I also couldn't test it.

**Comment by theScrabi** [comment]
This issue will be fixed with the next release

**Comment by github-userx** [comment]
Any update on this?

**Comment by gkeegan** [comment]
Afaik it has been fixed.
