### ISSUE TITLE
NewPipe does not load

### ISSUE THREAD

**Issue by FreddieGamez** [TeamNewPipe/NewPipe#9406]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Open NewPipe
2. Issue can be seen. Feed does not load, and search does not also work.

### Expected behavior

Feed loads and NewPipe can be used as normal.

### Actual behavior

Feed does not load, and search does not also load.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/118343515/202130596-23963200-5f98-4893-baa4-624b9fa305b6.mp4

### Affected Android/Custom ROM version

Android 8.1.0/ColorOS 5.2.1

### Affected device model

Oppo A5s

**Comment by Arcegis** [comment]
Hello, having the same problem.
Android 9.0 on Asus ZenFone Max Pro M1.
Videos will not load if selected from Search, nor from Feeds from channels you follow.

**Comment by FreddieGamez** [comment]
> 

I tried both of those things and I am still experiencing the same issue.

**Comment by Destragon** [comment]
Does it not load at all or does it just take a really long time? For me, Newpipe was really slow the last couple days. Clicking a profile, then waiting 2 minutes for the videos to show up, clicking one of the videos and then waiting 2 minutes for the video to start. But that actually got fixed after clearing cache and restarting the phone for me.

Does it load properly for when you're using mobile data instead of wifi, like https://github.com/TeamNewPipe/NewPipe/issues/9408 ?

**Comment by FreddieGamez** [comment]
> Does it not load at all or does it just take a really long time? For me, Newpipe was really slow the last couple days. Clicking a profile, then waiting 2 minutes for the videos to show up, clicking one of the videos and then waiting 2 minutes for the video to start. But that actually got fixed after clearing cache and restarting the phone for me.
> 
> Does it load properly for you when you're using mobile data instead of wifi, like #9408 ?

Please close this thread - the issue is resolved. My phone just wasn't having it that day

**Comment by AudricV** [comment]
> Please close this thread - the issue is resolved.

You could have done it yourself.
