### ISSUE TITLE
Blank player screen when a private video is clicked 

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9409]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1, nightly 15 

### Steps to reproduce the bug

1. Go to https://www.youtube.com/watch?v=Y6wPoNKdIVc (most likely made private after the video got indexed in feed)
2. See blank screen 

### Expected behavior

The player should show metadata about the requested video or tell me that this video is private or something.

### Actual behavior

Blank screen 

### Screenshots/Screen recordings

The behaviour of YouTube website:
<img alt="Screenshot_2022-11-16-22-22-28-07" src="https://user-images.githubusercontent.com/28833686/202243504-b3653f31-01be-4e84-8509-d2c89505c2da.png" height=600 />

Bug in action:
https://user-images.githubusercontent.com/28833686/202242807-51bfb544-7ede-4842-b07a-1e08a18c07fe.mp4

### Affected Android/Custom ROM version

Color OS v6.0(android 9) Non rooted

### Affected device model

Oppo Realme 1 CPH1861

**Comment by opusforlife2** [comment]
It's showing the correct error page for me. Try after clearing cache.

**Comment by opusforlife2** [comment]
Try pasting the URL in the search bar.

**Comment by opusforlife2** [comment]
👍 Then it's a problem with your network/device. Try switching these.

**Comment by opusforlife2** [comment]
> 0.24.1, nightly 15

You're supposed to test the official release, not nightlies.

**Comment by opusforlife2** [comment]
Ah, got it. To avoid this confusion, you could put multiple versions in a bulleted list, or use 'and' to separate them. I read it like "nightly 15, which is based on 0.24.1".

**Comment by opusforlife2** [comment]
> one other device 

What OS?

**Comment by opusforlife2** [comment]
Welp. I'm out of ideas.
