### ISSUE TITLE
More videos/elements in what's new feed

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9416]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

If i scroll down to the end probably a limited number of videos are shown the list in what's new feed should load further i.e. it should load more items if the user wants to view more videos from subscribed what's new feed.

If possible impliment something like **swipe up to load more** gesture. Also with the text (depicted in bold here) at the end of the list/feed.

### Why do you want this feature?

Why not? The feed should load a few more videos if the user wants to figure out what's he has been missing out from his subscribed channels.

### Additional information

Possible fix for #8629 
The word elements depicts videos, shorts and livestreams.

**Comment by opusforlife2** [comment]
> not sure as i am requesting for a feature rather than reporting a bug.

Bug: there's no milk in the fridge.
Feature: please restock milk in the fridge.
