### ISSUE TITLE
[Meta] Add a bot to compare error logs to detect duplicate issues 

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9418]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

A bot can be used to compare logs in different issues and detect duplicate issues/bug reports more efficiently. 

If possible impliment automatic closing of duplicate issues after leaving a comment informing the author of the new issue about the existence of an open issues and asking them to contribute there. 

### Why do you want this feature?

1. Reduces human labour and effort
2. Increase efficiency of collaborators or maintainers
3. Reduces no of new issues
4. Better identification and categorisation of duplicate issues
I can write another 5 points but i believe it's enough for today 

### Additional information

Nothing special here

**Comment by opusforlife2** [comment]
Which bot are you talking about?
