### ISSUE TITLE
Thumbnail not showing for background play notification

### ISSUE THREAD

**Issue by samjo9** [TeamNewPipe/NewPipe#943]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

The thumbnail appears for a split second and then disappears.

**Comment by theScrabi** [comment]
This is od. Can you tell us which android version, which np version U are using, and the link to the video where it happens.

**Comment by Sam2acc97** [comment]
Had to create another account.

I'm using the latest version 0.11.1

It happens with every video when I use background play. I'm using a Google pixel xl running latest version of android.

**Comment by samucacsm** [comment]
I'm having the same issue, using Android 8 AEX ROM, on a Moto g first generation.
The thumbnail appears for a second and then it turns into a play icon

**Comment by ZJaume** [comment]
Same bug here, it happens with all videos. Thumbnail shows for a split second at the beginning or when the music is paused.

- LineageOS 15.1 (Android 8.1.0)
- NewPipe 0.13.7

I'm trying to get a logcat

**Comment by ZJaume** [comment]
[Here](https://gist.github.com/ZJaume/1d7d40877778e491c17e5f84e7f64afe) is the logcat I've captured greping by "org.schabi.newpipe". I don't know if it has useful information.

**Comment by ZJaume** [comment]
[Here](https://gist.github.com/ZJaume/1d7d40877778e491c17e5f84e7f64afe) is a logcat, I hope that it is useful

**Comment by switchtegrax1** [comment]
Same here Lineage os 15.1 Lg L70

**Comment by theScrabi** [comment]
I could reproduce this on an android 8.1 emulator.

**Comment by ZJaume** [comment]
I think this issue can be closed
