### ISSUE TITLE
Upgrade the network.

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#9432]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

<img alt="Screenshot_20221119-153118_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/118555547/202848759-6e0b4c1b-0aeb-4b8e-a512-0105be1b4d69.jpg" height=600 />

### Why do you want this feature?

Metered network usage.
Required network.
1.Metered

**Comment by tsiflimagas** [comment]
Doesn't "Any network" mean that? I'm not sure I get your request.

**Comment by Binleti** [comment]
In Weblate, replace it with All.I changed the content.

**Comment by jackedwards97** [comment]
> In Weblate, replace it with All.I changed the content.

That doesn't make sense. Please advise why Metered is required as opposed to "Any Network".
