### ISSUE TITLE
The function cannot be closed.

### ISSUE THREAD

**Issue by Binleti** [TeamNewPipe/NewPipe#9433]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The specified function cannot be closed.
![Screenshot_20221119-154131_NewPipe SponsorBlock](https://user-images.githubusercontent.com/118555547/202849002-485028b8-df02-4f6c-b3a1-5ad919bbec3b.jpg)

### Why do you want this feature?

To close this feature.

### Additional information

Android 12

**Comment by opusforlife2** [comment]
Not possible. Android 12 onwards, SAF is compulsory.

**Comment by ozogorc** [comment]
What happened to acces all files perm? He can give this perm to app if he wants to close this feature and i want this feature too.
