### ISSUE TITLE
While seeking, continue playing until you release the seekbar from hold

### ISSUE THREAD

**Issue by jcperil** [TeamNewPipe/NewPipe#9437]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

While moving the seekbar, the video should continue to play what it is playing until you release the seekbar from your finger in which case, it should jump to play from the time stamp you released the seekbar.

Please find attached one exhibit of NewPipe and one exhibit of YouTube (Revanced).

NewPipe behavior:
https://user-images.githubusercontent.com/89805719/202887117-fa5265df-a811-4169-82b7-13ef5a05c7ec.mp4

Expected behavior:
https://user-images.githubusercontent.com/89805719/202887216-312a4ee9-2e4c-4575-a90c-76407e41ff11.mp4

### Why do you want this feature?

It does not break the flow of what you are listening to.

**Comment by Jared234** [comment]
I can work on this and will create a PR soon.

**Comment by Jared234** [comment]
@opusforlife2 Do you think it would be worth adding an option for users to decide whether to pause the player or not? Or do you think this is unnecessary?

**Comment by opusforlife2** [comment]
Good question. Let's discuss.

**Comment by opusforlife2** [comment]
The safest thing would be to add an option for this. Adding the option but also changing the default to this, or merely changing the default behaviour, will impact all Newpipe users.

Whether that is a good thing or not, it is something people will be used to.

Is the functionality important enough/harmless enough to make it the default?

**Comment by Jared234** [comment]
I agree that introducing an option for this would be the safest and most user-friendly option. However, I don't think many people would have a negative experience if we don't introduce this option. Because if you don't want the video to continue while using the seeking feature, you can simply pause the video and then use it. However, this won't be as convenient for people that still prefer the current version.
So, I am still not sure if this feature would be worth adding another option in the settings. What do you think?

**Comment by opusforlife2** [comment]
Personally, I don't care much about this, and in general we shouldn't have too many options. So we need to poll more users, I think.

**Comment by Jared234** [comment]
Yes, I agree. Is there any way to create a poll for questions like that?

**Comment by opusforlife2** [comment]
👍 - add this feature
👎 - don't add this feature
👀 - make it an option

**Comment by Jared234** [comment]
@opusforlife2 I believe the results are clear. If you agree, I'll create a PR for implementing this feature without adding another option.
