### ISSUE TITLE
Display over other apps to jump chapters. Why?

### ISSUE THREAD

**Issue by jcperil** [TeamNewPipe/NewPipe#9439]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Why does clicking on chapter timestamps require "Display over other apps" permission? YouTube (Revanced) does not require this permission and is able to jump chapters by clicking their timestamps. Curious to know.
Also, when I enable the "Display over other apps" permission and then click on the timestamps, it plays in popup mode instead of playing normally.

**Comment by jcperil** [comment]
No, just from the description timestamps.

**Comment by opusforlife2** [comment]
Then that's working as intended. The feature needs to be improved, yes, and an issue is open about it, but the current method isn't a bug.
