### ISSUE TITLE
Popout "fullscreen" key not functioning

### ISSUE THREAD

**Issue by ZaneHannanAU** [TeamNewPipe/NewPipe#944]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Version: 0.11.1 fdroid

Explain: virtual key "fullscreen" on popout window does null, going fullscreen without exiting not possible.

Will upload streamable soon

**Comment by ZaneHannanAU** [comment]
Streamable: https://streamable.com/zkhb6

Uploading currently

**Comment by TobiGr** [comment]
Thank's for your detailed issue report. Videos always help to understand the problem. 
We have already fixed this bug and released version [0.11.2](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.11.2). It should be available on F-Droid soon.

**Comment by ale5000-git** [comment]
Unfortunately 0.11.2 isn't on F-Droid.
