### ISSUE TITLE
HLS or DASH

### ISSUE THREAD

**Issue by Binleti** [TeamNewPipe/NewPipe#9441]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Speeding up initial video loading by using DASH format instead of HLS.

### Why do you want this feature?

LibreTube uses DASH and no longer has problems opening videos.

### Additional information

If NewPipe uses it, close this issue.

**Comment by Binleti** [comment]
#8924

**Comment by Binleti** [comment]
In the same settings, the default quality should be automatic.

**Comment by yashpalgoyal1304** [comment]
hey @opusforlife2 
I think u closed this issue by mistake - the mentioned issue is likely a related issue, not a duplicate

**Comment by opusforlife2** [comment]
I didn't close it because of the issue mentioned.

**Comment by yashpalgoyal1304** [comment]
> I didn't close it because of the issue mentioned.

then u should mention that this is duplicate of what issue :)

**Comment by opusforlife2** [comment]
No thank you. The onus of looking for duplicates is on the issue reporter, not the maintainers. DASH was such a major missing feature that it is unimaginable that the original issue can't be found easily.
