### ISSUE TITLE
Player Screen cuts off in Landscape Mode

### ISSUE THREAD

**Issue by MavisCelus19201** [TeamNewPipe/NewPipe#9447]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Go to a video (tested on multiple videos so specific ones don't seem to matter)
2. Flip the device to change from Portrait mode to Landscape

### Expected behavior

The screen elements are as normal in both sizes.

### Actual behavior

The screen is slightly zoomed in when viewing in Landscape mode, but NOT Portrait mode. 

Sometimes the bottom will also be cut off by a black bar in Landscape mode, though this is more inconsistent when I tried to check this.

### Screenshots/Screen recordings

![Screenshot_20221122-114511_1](https://user-images.githubusercontent.com/73338735/203407917-086dc63b-6032-4c95-9239-69e2b51ff1fd.jpg)
![Screenshot_20221122-114437](https://user-images.githubusercontent.com/73338735/203407919-6fa5858f-9c53-412b-86ca-b9322c7b1af4.jpg)

Image comparison between Portrait (Red bar at the top) and Landscape modes
![Screenshot_20221122-115117](https://user-images.githubusercontent.com/73338735/203408254-2ee70a81-9982-4826-9161-002ab9cf7c63.jpg)

Image comparison between Portrait (Red bar at the top) and Landscape modes, alongside an example with a black bar at the bottom.

### Affected Android/Custom ROM version

Android 10

### Affected device model

OnePlus 8 5G

**Comment by opusforlife2** [comment]
?
