### ISSUE TITLE
Consistent crash if video player closed before the video loads

### ISSUE THREAD

**Issue by Jaydepps** [TeamNewPipe/NewPipe#9448]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Start playing video
2. Before video loads back out and close the small player by either taping the x or swiping down

### Expected behavior

Video playback stops

### Actual behavior

Newpipe crashes

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/61331785/203453472-0d77f799-37f7-46ff-b5ad-ff4cffbbba00.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux HUAWEI/MAR-LX1AEEA/HWMAR:10/HUAWEIMAR-L21A/10.0.0.233C431:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e233f40 u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2540)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 / EMUI 12.0.0

### Affected device model

Huawei P30 Lite

**Comment by opusforlife2** [comment]
What's the value of `Smallest width` in Developer options?

**Comment by Jaydepps** [comment]
423 dp (system default)

**Comment by opusforlife2** [comment]
Your video is blank. Try uploading again?

**Comment by Jaydepps** [comment]
https://user-images.githubusercontent.com/61331785/204088226-97b79eda-0743-4bb7-b67d-d2071cff8098.mp4
Video uploaded again

**Comment by opusforlife2** [comment]
Ah, it's the same problem. You'll have to make a new video. Is this playing for you in the browser?

**Comment by Jaydepps** [comment]
The video is playing fine for me, I checked on multiple devices.

Yes, the crash occurs when you attempt to close the player while its initially loading.

**Comment by Jaydepps** [comment]
https://user-images.githubusercontent.com/61331785/204095825-9b863a10-5a08-40bf-9741-284d7e696773.mp4

New video

**Comment by opusforlife2** [comment]
It's the same issue I reported here: https://github.com/TeamNewPipe/NewPipe/issues/8646#issuecomment-1236162209

But I only get it on Tablet mode (Smallest width >480 dp). You seem to be getting it even on Phone layout.

Just to cover all bases, is `Tablet mode` off in Appearance?

**Comment by Jaydepps** [comment]
Tablet mode is off, yes.

**Comment by Douile** [comment]
Reproducible on android 11 (lineage 18.1), smallest width 587dp (smallest display and font size in android/display settings), for both tablet mode on and off. Although it doesn't just happen when closing video before load for me: same crash log when notification group is closed while loading, or sometimes while refreshing feed with video playing, or closing playing video while feed is refreshing. Not sure if these are more related to other issue posted but its the same crash log so posted here.

**Comment by opusforlife2** [comment]
@Douile Change your smallest width to less than 480 dp and see if it still occurs.

**Comment by Douile** [comment]
Yes
