### ISSUE TITLE
Wrong button after after app reactivation: pause instead of play icon

### ISSUE THREAD

**Issue by ksaerdna** [TeamNewPipe/NewPipe#945]
- Start app and play some video
- Pause video. App shows PLAY icon.
- Switch device on and off. Device shows lock screen.
- Unlock the device. App will show some rotating animation.
- After some time app shows PAUSE icon. But it should be the PLAY icon.

**Comment by maholeycowdevelopment** [comment]
I'm going to jump on this. I will update soon.

**Comment by theScrabi** [comment]
fixed

**Comment by ksaerdna** [comment]
Works "like a charm". Thanks!
