### ISSUE TITLE
Playlist thumbnail doesn't get updated after the "Remove Watched" dialog is used

### ISSUE THREAD

**Issue by Jared234** [TeamNewPipe/NewPipe#9458]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Create a new playlist with two videos
2. Go to playlist overview
3. Go to the newly created playlist
4. Click "Background"
5. Listen for a couple of seconds
6. Click "Removed Watched"
7. Click "Yes, and partially watched videos"
8. Go to Playlist Overview

### Expected behavior

The thumbnail of the playlist should have changed to the only item in the playlist. 

### Actual behavior

The thumbnail doesn't get updated.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/26669009/203877279-809cfc90-4c17-4635-b995-1dde58416bce.mp4

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 5

### Additional information

I am a developer and plan to work on this problem myself.

**Comment by cucumber-sp** [comment]
Hello! I'm gonna try to fix this bug. Leaving comment on this issue due to contribution rules

**Comment by AlertSubject** [comment]
How would you handle this if you manually set a Playlist thumbnail and the video that was used is removed later down the road?

I was searching for a video that fit the watch later Playlist and after I set the thumbnail I removed it again
Otherwise every Playlist would constantly switch to new thumbnails all the time

**Comment by Jared234** [comment]
I can certainly understand your use case. However, if the playlist thumbnail doesn't change when you remove the video, it's considered a "bug" right now because NewPipe tries to update it but fails due to the problem I mentioned in my PR request.
Maybe we should introduce a permanent thumbnail selection feature, or disable updating a playlist thumbnail if you set it directly. Maybe your problem would be worth opening another feature issue?

**Comment by AlertSubject** [comment]
> Maybe we should introduce a permanent thumbnail selection feature, or disable updating a playlist thumbnail if you set it directly. Maybe your problem would be worth opening another feature issue?

I always assumed it was be feature instead of a bug 🤔
Keeping thr thumbnail when it was set manually sounds reasonable to me. At least better than adding another option to the menu. 
The question is how it would be handled if the user wants to "unset" the permanent thumbnail once it has been set

**Comment by Jared234** [comment]
I have just had another look and have found an interesting option. When you press on the three dots in the playlist there could be an option to permanently lock the thumbnail. If it is pressed, the thumbnail of the playlist won't change. If you then press "unlock thumbnail" it can be changed again and if the video is not in the playlist anymore the first video gets selected as the new thumbnail video. How do you like this idea?

**Comment by AlertSubject** [comment]
> How do you like this idea?

Sounds like a good compromise to me 
Up to the devs if they want to add another setting for this edge usecase 

Might be useful for those who want to give their Playlist somewhat of an identity to distinguish between them. 

I'm not gonna shed any tears if the bug is fixed without a replacement for my use case but of course it would be nice to have a was to theme your Playlist page a bit

**Comment by Jared234** [comment]
@AlertSubject I opened a feature request. #9468
If you have anything to add there, feel free to leave a comment.
