### ISSUE TITLE
Can't share a playlist

### ISSUE THREAD

**Issue by licaon-kter** [TeamNewPipe/NewPipe#946]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

0.11.1
Search for something
Choose a playlist
Press share icon -> nothing happens
Press menu -> Open in browser -> nothing happens

**Comment by Munkiiedude** [comment]
Same issue here on 0.11.0

**Comment by theScrabi** [comment]
Aw come on -.-
Confirmed

**Comment by theScrabi** [comment]
[fixed](https://github.com/TeamNewPipe/NewPipe/commit/808ce72078684462980f63b8abf915b9b8939a75)
