### ISSUE TITLE
Targeting S+ (version 31 and above)

### ISSUE THREAD

**Issue by Chex07** [TeamNewPipe/NewPipe#9460]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.1

### Steps to reproduce the bug

If i make targetSdk 31 in buld.gradle then giving this error = 

`11/25 11:04:44: Launching 'app' on Pixel 6 API 31.
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

List of apks:
[0] 'C:\Users\akkay\Downloads\NewPipe-dev (2)\NewPipe-dev\app\build\intermediates\apk\debug\app-debug.apk'
Installation failed due to: 'INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1321914285.tmp/base.apk (at Binary XML file line #553): leakcanary.internal.activity.LeakLauncherActivity: **Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'**
Retry
Failed to launch an application on all devices`

**its working on android studio virtual phone but not working on real mobil phones**

**how can i fix this problem ?**

**Comment by opusforlife2** [comment]
Either wait for the official app to bump up its target SDK version, or fix it yourself?

**Comment by AudricV** [comment]
Also see #9306.
