### ISSUE TITLE
Enable users to permanently lock the thumbnail of a playlist

### ISSUE THREAD

**Issue by Jared234** [TeamNewPipe/NewPipe#9468]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Right now, there is no feature that allows you to permanently set the thumbnail of a playlist.
Such a feature could be introduced by pressing on the three dots in the playlist. There you could have an option to permanently lock the thumbnail. If it is pressed, the thumbnail of the playlist won't change. If you then press "unlock thumbnail" (only visible if thumbnail is currently locked) it can be changed again.
If the thumbnail video is not in the playlist anymore the first video gets selected as the new thumbnail video.

### Why do you want this feature?

I want my thumbnail to stay the same for a particular playlist. The current implementation would lead to the playlist thumbnail constantly changing and thus not always being representative of my chosen playlist topic.

### Additional information

I am a developer and would work on this issue myself.

**Comment by opusforlife2** [comment]
What does YT do?

**Comment by Jared234** [comment]
Youtube doesn't let the user decide which playlist thumbnails they want. The first video of the playlist always provides the thumbnail. So there isn't even an option to choose a playlist thumbnail if it isn't the first video.

**Comment by AlertSubject** [comment]
Thanks for creating this
As a not for future reference:
https://github.com/TeamNewPipe/NewPipe/issues/9458#issuecomment-1328016965 and onwards

**Comment by opusforlife2** [comment]
What about making the first video the playlist thumbnail, instead of the latest one? It would bypass this entire issue.

**Comment by Jared234** [comment]
Hmm... this would be an option, but I don't think that this will satisfy the desired use case completely. This still hinders you from permanently assigning a thumbnail to a playlist. Also, watching the thumbnail video would cause the "Remove Viewed" dialog to become unusable unless you also want to remove the current thumbnail.

**Comment by opusforlife2** [comment]
Ah, I was only thinking of remote playlists. Those could take the 1st index video's thumbnail permanently.

But for a local playlist, yes, no video is guaranteed to be permanent. I suppose we could also just show a placeholder sort of thumbnail there, to indicate that it is a local playlist. Fiddling with custom thumbnails seems too niche.

**Comment by Jared234** [comment]
Yes, for remote playlists this is not necessary. But if you create your own you want to be able to set a certain thumbnail (there already is an option to long press a video and then select its thumbnail as the playlist thumbnail; however it gets changed if the video is no longer in the playlist).
I'm sorry, but I'm not quite sure what you mean by a placeholder thumbnail for local playlists.

**Comment by Jared234** [comment]
Ok, great. Would you agree with the suggestion I made in the issue description? I believe that this option would be the most non-intrusive and user-friendly way to handle this.

**Comment by opusforlife2** [comment]
> There you could have an option to permanently lock the thumbnail

I don't see the need for an option. The default behaviour should be that whatever you set the playlist thumbnail to, it should stay that way forever. If the user wants to change it again, they could select a different thumbnail.

**Comment by Jared234** [comment]
So, right now the default behavior is that the thumbnail of the first video gets used as the playlist thumbnail. If it gets removed, the thumbnail gets updated to the first video in the playlist again. I believe that behavior shouldn't be changed. 
Only if you have manually selected a playlist thumbnail it should be permanent right?
But what happens if you have manually set a thumbnail and then want to go back to the default behavior. This wouldn't be possible anymore... That's why I wanted to introduce a "lock" option, so you are able to "unlock" it again.

**Comment by opusforlife2** [comment]
"Unset" would be clearer, I think. You can set a particular thumbnail for a playlist, and that same dialog option would change to Unset so that it can be reverted.

**Comment by Jared234** [comment]
Thanks for the clarification. I will work on this soon.

**Comment by Jared234** [comment]
Hey. So, I have already started working on this but noticed one flaw in this approach. 
What happens if you set a thumbnail and then remove the thumbnail video again? You are not able to long press the video (because it won't be in the playlist) and use the "unset" option. 
I feel like having an extra option in the playlist to permanently lock/unlock a thumbnail is the only way to solve this issue completely.

**Comment by AlertSubject** [comment]
> I feel like having an extra option in the playlist to permanently lock/unlock a thumbnail is the only way to solve this issue completely.

I would have assumed the option to lock / unlock would only be present in the Playlist menu
As a "global" setting for this Playlist
Otherwise the user might spend quite some time looking through larger playlists just to find the video in question, if it even exists

**Comment by yashpalgoyal1304** [comment]
> Youtube doesn't let the user decide which playlist thumbnails they want. The first video of the playlist always provides the thumbnail. So there isn't even an option to choose a playlist thumbnail if it isn't the first video.

wrong information

**Comment by Jared234** [comment]
@yashpalgoyal1304 Can you please provide a way to change the playlist thumbnail in the official YouTube app. AFAIK this is only possible if you use the web version of YouTube.

**Comment by yashpalgoyal1304** [comment]
> AFAIK this is only possible if you use the web version of YouTube.

the inspiration can be took from web version too - it ain't that specific of a thing which requires stuff to be available in only app form

**Comment by Jared234** [comment]
Yeah, I see what you mean. 👍
Here is the explanation of how it works in Youtube:
- Youtube App: The playlist thumbnail changes automatically if you change the first video in the playlist.  
- Youtube Web version: There are basically two options of changing a thumbnail.
       - As in the Youtube app, if you haven't manully selected a thumbnail the first video of the playlist will be the thumbnail
       - Like in NewPipe there is an option to select the thumbnail manually by clicking on the three dots right next to the video. However, if you remove the video, it is automatically unset as the playlist thumbnail. AFAIK there is no option to unset a thumbnail manually again.  

@SameenAhnaf @opusforlife2 Now that you know what the web version does, should I implement the feature as discussed, or should we do it just like YouTube.

**Comment by Jared234** [comment]
Ok, then I will implement this feature as discussed.

**Comment by opusforlife2** [comment]
> I think, this is a better place to place the option.

Doesn't make sense to put an unrelated checkbox in a Rename dialog.

**Comment by opusforlife2** [comment]
Ah. Then the dialog could be replaced by a proper long-press menu with items: Rename, Delete, Unset thumbnail.

The Rename item would further open the current dialog, just without the Delete button.

**Comment by Jared234** [comment]
Sure, I can implement that. 
But do you prefer an `Unset thumbnail` option, or an `Automatic Thumbnail Selection` checkbox?

**Comment by opusforlife2** [comment]
In a menu with tappable list items, a checkbox wouldn't make sense. Or are you proposing putting it somewhere else?

**Comment by Jared234** [comment]
Do you think it's enough to show the _Unset Thumbnail_ button only if the user has set the playlist thumbnail manually? And otherwise the default dialog options will be only "Rename" and "Delete"?
I agree that allowing the user to set the thumbnail in the playlist tab would not be a good idea.

**Comment by Jared234** [comment]
I actually think that _Automatic Thumbnail Selection_ is the better option, because we don't actually "Always Select First Video for Thumbnail". IMO this would mean that if you move a video to the top spot in your playlist, that the playlist thumbnail should be updated. This is how YouTube does it, but NewPipe won't change the thumbnail if you just change the order of your videos.

Maybe we could have an option "Select Thumbnail Automatically" that is always present in the long press menu of the playlist. It doesn't matter if you have manually selected a thumbnail or the thumbnail already has been automatically chosen. We would just choose the video that is currently at the top of the playlist to be the next thumbnail video.
I also believe that this option would be very clear, so no further explanation would be necessary.

**Comment by opusforlife2** [comment]
> Manage dialogue does not only include tappable options

I was talking about the menu in https://github.com/TeamNewPipe/NewPipe/issues/9468#issuecomment-1335507584

> Do you think it's enough to show the Unset Thumbnail button only if 

A greyed out list item would be better, I think. For users who don't know about this feature (like me a couple days ago!) this would be both a way to discover that the feature exists, and where to go in case they set a thumbnail they want to change later.

**Comment by Jared234** [comment]
That sounds like a good idea. 👍
