### ISSUE TITLE
Videos are not completely fullscreen

### ISSUE THREAD

**Issue by PrinceRaj53** [TeamNewPipe/NewPipe#9472]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1.Play any video
2.Switch to full screen
3.Touch the arrow on top right corner
4.Set the "zoom" option
5.You'll see that the video is still not completely full screen & there is still space left on the left side.

### Expected behavior

The videos should be played full screen.

### Actual behavior

The videos are not in fullscreen.

### Screenshots/Screen recordings

This is how it should've worked :

![Should be like this](https://user-images.githubusercontent.com/96355726/204127980-642880db-17c1-49a3-a885-8faf6623e95a.jpg)

And this ia how it looks as of now :

![Not fullscreen](https://user-images.githubusercontent.com/96355726/204128041-4c8d9c54-427c-435b-b13b-cd417bfd44cc.jpg)

### Logs

None.

### Affected Android/Custom ROM version

Android 12, stock rom

### Affected device model

Realme GT Neo 2(RMX3370)

**Comment by opusforlife2** [comment]
Why open a new issue when one already exists?
