### ISSUE TITLE
Unable to load UI preview. 

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#9486]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hi, 
I want to contribute to this project but cannot load layouts in the UI editor with the default config. 

AD Version: Android Studio Dolphin | 2021.3.1 Patch 1

![image](https://user-images.githubusercontent.com/46952207/204954634-747ee6c2-69c7-48fa-b2b3-c3bd265909bb.png)

### Additional information

Forked the latest version.

**Comment by Stypox** [comment]
This looks like a bug in Android Studio. Maybe try to sync gradle files again, or "invalidate caches and restart"
