### ISSUE TITLE
Android TV "An error occured see notifications"

### ISSUE THREAD

**Issue by disconnect5852** [TeamNewPipe/NewPipe#9487]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

On Xiaomi TV strick android TV
1. start newpipe (all default settings)
2. start playing a video
3. switch it to full screen
4. "an error occured see notifications"
5. restart newpipe
6. try again with different video (the previous will cause instant "an error..."
7. try to switch full screen
8. "an error occurred see notification"
9. quit, try again, no videos will play, always "an error occurred see notification"

Official youtube app works, vanced app works.

### Expected behavior

Play video in fullscreen, play videos at all

### Actual behavior

"an error occured see notifications" notification when i switch to full screen, then after few tries, always the same error with all videos

### Affected Android/Custom ROM version

Android TV 11

### Affected device model

Xiaomi TV stick (MyTV-AYFR0)

**Comment by disconnect5852** [comment]
if i restart the stick, i can restart these things, but always the same is the result

**Comment by JozKov** [comment]
I use NewPipe (v0.24.1) on a new **Xiaomi TV Stick 4K (Android11)**. It plays only one video, the next one won't play because it writes an **error** "an error occured see notifications". Even closing the app doesn't help. The same error if I switch to full screen.

On the **old Xiaomi TV Stick (Android 9)** NewPipe (v0.24.1) app works **without error**.
