### ISSUE TITLE
I had a dream that this app had a better UI

### ISSUE THREAD

**Issue by AlmightyWings232** [TeamNewPipe/NewPipe#9489]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I wanted this app to have a better UI so much it appeared in my dream

### Why do you want this feature?

This shit so ridiculous I had to tell someone, also a better UI in line with YouTube's own app would be good

**Comment by tsiflimagas** [comment]
I had a dream, people would stop writing nonsense in GitHub issues and wasting time of people who actually have important stuff to do. Sadly, we don't always get what we want.
