### ISSUE TITLE
There is 2018nand on fdroid latest version is still 0.11.1

### ISSUE THREAD

**Issue by the4anoni** [TeamNewPipe/NewPipe#949]
Is fdroid abadoned ?

**Comment by rogers1106** [comment]
A lot of apps are outdated at F-Droid at the moment. Something is broken there.

**Comment by TobiGr** [comment]
> A lot of apps are outdated at F-Droid at the moment. Something is broken there.

Yes, there are problems with F-Droid's buildserver atm.

**Comment by theScrabi** [comment]
That happens for quite some time now. That issue existed for the last release as well :(
