### ISSUE TITLE
[bandcamp] load thumbnail error

### ISSUE THREAD

**Issue by shigetsune** [TeamNewPipe/NewPipe#9493]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. open any bandcamp album
2. see thumbnails not loading and newpipe saying that thi shouldn't have happened

### Expected behavior

load thumbnails

### Actual behavior

doesn't load thumbnail and gives a pop-up to report bug

## Exception
* __User Action:__ load image
* __Request:__ https://f4.bcbits.com/img/a1200044877_10.jpg
* __Content Country:__ JP
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ Bandcamp
* __Version:__ 0.24.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504
	at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10/ miui 12

### Affected device model

Redmi 8

**Comment by TobiGr** [comment]
I cannot reproduce this. Does the error still occur for you? HTTP 504 is status code indicating that the server had problems _(504 Gateway Timeout: The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.)_.

**Comment by shigetsune** [comment]
yes, I still do not have thumbnails loading, and when I visit bandcamp.com thumbnails do load, when I use official bandcamp app they don't tho, so that's might be not a newpipe problem.

**Comment by opusforlife2** [comment]
> so that's might be not a newpipe problem

Needs investigation. Maybe your ISP/DNS/adblocker/hosts file is blocking it.

**Comment by shigetsune** [comment]
oh its kinda ok now? idk what was the problem but you can mark this as closed, thanks for your time, and sorry for waiting.
