### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#9494]
{"user_action":"get subscription","request":"Get subscription status","content_language":"en-IN","content_country":"IN","app_language":"en_IN","service":"YouTube","package":"org.schabi.newpipe","version":"0.24.1","os":"Linux Android 13 - 33","time":"2022-12-03 20:55","exceptions":["java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.\n\tat com.google.android.material.snackbar.Snackbar.makeInternal(Snackbar.java:199)\n\tat com.google.android.material.snackbar.Snackbar.make(Snackbar.java:158)\n\tat com.google.android.material.snackbar.Snackbar.make(Snackbar.java:263)\n\tat org.schabi.newpipe.fragments.list.channel.ChannelFragment.showNotifySnackbar(ChannelFragment.java:428)\n\tat org.schabi.newpipe.fragments.list.channel.ChannelFragment.lambda$monitorSubscription$3(ChannelFragment.java:262)\n\tat org.schabi.newpipe.fragments.list.channel.ChannelFragment.$r8$lambda$kKnl6ApHfDm8LSrzW7WrxdfY7uM(Unknown Source:0)\n\tat org.schabi.newpipe.fragments.list.channel.ChannelFragment$$ExternalSyntheticLambda12.accept(Unknown Source:4)\n\tat io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)\n\tat io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)\n\tat io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)\n\tat io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)\n\tat android.os.Handler.handleCallback(Handler.java:942)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.app.ActivityThread.main(ActivityThread.java:7904)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)\n\tat com.android.internal.os.ExecInit.main(ExecInit.java:49)\n\tat com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)\n\tat com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)\n"],"user_comment":""}

**Comment by opusforlife2** [comment]
This isn't helpful by itself. Please fill out the issue template given here: https://github.com/TeamNewPipe/NewPipe/issues/new/choose
