### ISSUE TITLE
bug when resizing popup video

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#950]
Greetings,
I have been following this project for a long time but I have never been encouraged to add any issue because I thought someone else would do it for me. but particularly since I upgraded from my old low-end phone Samsung Young 2 (unnoficial lineageOS 13) to the Motorola G5 Plus (android 7.0) I can not resize the popup videos because it is automatically maximized. after that it is impossible to retract it unless you deactivate the option in the "remember size and position" settings.

PD: I'm sorry if my English sounds weird, is that I'm using the Google translator. I love the work you are doing, please continue like this! ;) I am very anxious to see the options of streaming and subtitles in next versions.

**Comment by theScrabi** [comment]
Maybe you still use the old way of resizing. You may not tab and hold it anymore. It now works with two fingers.

**Comment by speednroll** [comment]
@theScrabi :joy: hahaha, it's true. If you had not told me, I would never have found the trick. regards
