### ISSUE TITLE
Ability to Install Anime Extentions 

### ISSUE THREAD

**Issue by zojfdny7** [TeamNewPipe/NewPipe#9505]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add anime streaming sites into newpipe just by installing anime extentions. This Feature can be found in free and opne source app aniyomi on github link:https://github.com/jmir1/aniyomi

### Why do you want this feature?

I want this feature because I dont want two separate apps to watch anime in Youtube wherein my PC I can switch tabs b/w Youtube and anime sites 

### Additional information

<img alt="159184543-58cbf5aa-cb16-436c-a1f1-1eb194e6947c" src="https://user-images.githubusercontent.com/118600948/205573718-03a84fc3-8455-4cee-97aa-72e00db24781.png" width=270 />

**Comment by opusforlife2** [comment]
That's where my mind went as well, but let's let them clarify.

**Comment by ChiefMikeK** [comment]
https://aniyomi.jmir.xyz/extensions/

UMM ; this is feeds from up to 111 unique websites featuring manga anime etc... as *extention.apk{s} to thier main aniyomi.apk

**Comment by zojfdny7** [comment]
I request the developers to install the app and use it to get a better Idea. Link is in the feature description .Then you can borrow its source code as its free and open source. If you find it difficult to use the app please watch this Youtube video. Its Short less than a minute.
Link:https://youtube.com/shorts/8zqnNyIJcuA?feature=share

Thank You

**Comment by zojfdny7** [comment]
I request the developers to install the app and use it to get a better Idea. Link is in the feature description .Then you can borrow its source code as its free and open source. If you find it difficult to use the app please watch this Youtube video. Its Short less than a minute.
Link:https://youtube.com/shorts/8zqnNyIJcuA?feature=share

Thank You

**Comment by zojfdny7** [comment]
I request the developers to install the app and use it to get a better Idea. Link is in the feature description .Then you can borrow its source code as its free and open source. If you find it difficult to use the app please watch this Youtube video. Its Short less than a minute.
Link:https://youtube.com/shorts/8zqnNyIJcuA?feature=share

Thank You

**Comment by zojfdny7** [comment]
I request the developers to install the app and use it to get a better Idea. Link is in the feature description .Then you can borrow its source code as its free and open source. If you find it difficult to use the app please watch this Youtube video. Its Short less than a minute.
Link:https://youtube.com/shorts/8zqnNyIJcuA?feature=share

Thank You
