### ISSUE TITLE
[Feature Request] Loop 

### ISSUE THREAD

**Issue by usernatilds** [TeamNewPipe/NewPipe#951]
Please, implement a function that enable repeat video infinitily, same feature when play youtube in desktop.

![screenshot_2018-01-03_13-58-36](https://user-images.githubusercontent.com/25496130/34527883-39404524-f08e-11e7-9933-00510c19b95b.png)

**Comment by usernatilds** [comment]
@theScrabi, Thanks for see my topic, please, implement loop in next version, you app allow youtube in background, loop is a feature more demanded. If implement NewPipe is a first app with good features.

**Comment by theScrabi** [comment]
but loop in background is already implemented :P

**Comment by usernatilds** [comment]
@theScrabi, I know, now with the loop is perfect

**Comment by usernatilds** [comment]
@theScrabi, sorry, i not know, thanks for excelent app.
