### ISSUE TITLE
ExoPlayer 2.18.2 is out

### ISSUE THREAD

**Issue by pihug12** [TeamNewPipe/NewPipe#9511]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

ExoPlayer 2.18.2 changelog: https://github.com/google/ExoPlayer/releases/tag/r2.18.2

### Why do you want this feature?

Maybe updating ExoPlayer from 2.18.1 to 2.18.2 can fix some issues.

I read some things about tunneling (talked in the Android TV thread https://github.com/TeamNewPipe/NewPipe/issues/9023) or fix an IllegalStateException in the changelog.

**Comment by opusforlife2** [comment]
There's no need to open such issues. The team has a vested interest in keeping track of Exoplayer releases, so all these things are known and under consideration.
