### ISSUE TITLE
Cannot Turn Off Captions

### ISSUE THREAD

**Issue by puppykickr** [TeamNewPipe/NewPipe#9512]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. make random search
2. video has captions
3. make sure captions are off via app settings, as well as with the device itself
4. captions continue to appear
5. this is only occurring with one of my devices, Moto e running android 10
6. does not seem to happen with my devices running android 9 or 11

### Expected behavior

captions not appearing

### Actual behavior

captions appear even if captions are set to off

### Affected Android/Custom ROM version

Android 10

### Affected device model

Moto e

### Additional information

I am aware that this seems device specific in my case.
Any help as to whatever system app may be responsible would be of great help.

I have restarted the device multiple times, uninstalled then reinstalled the app, cleared cache and data, among other things and have found no remedy.

**Comment by opusforlife2** [comment]
Do the same captions appear when you set captions to on within the app? Or do 2 different ones appear?

**Comment by puppykickr** [comment]
There is no difference, it is the same either way.

It seems the app triggers the caption settings for the device- I am
assuming that they are one and the same.

Grant Ryan Swan
   (puppykicker)

**Comment by opusforlife2** [comment]
To be clear, there is a Captions option inside the app's settings, which takes you to the OS Captions menu.

And then subtitles are also referred to as closed captions. Are you maybe talking about those? The only place to change them is from the top right arrow menu inside the player.

**Comment by cvoges12** [comment]
I have the same issue. I have the OS captions disabled. And yet captions still appear. Also, captions don't respect text size even if os options are enabled.

**Comment by cvoges12** [comment]
@opusforlife2 Can we reopen this? I can continue giving details on the issue.
