### ISSUE TITLE
[enhancement] Add comments section

### ISSUE THREAD

**Issue by Tvax** [TeamNewPipe/NewPipe#952]
A cool feature to add would be the comments section of a video.
It could be displayed by swiping to the right on the "Recommended videos" section beside the video player !

- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.

**Comment by TobiGr** [comment]
Duplicate of #579 
@Tvax I added your idea to the comments ticket.
@theScrabi I don't have permission to close this issue.

**Comment by theScrabi** [comment]
I think you need write permission to the repo if you want to close them.
