### ISSUE TITLE
Long-pressing "background", "popup" buttons stops video

### ISSUE THREAD

**Issue by marcel263** [TeamNewPipe/NewPipe#9524]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1 nightly-20

### Steps to reproduce the bug

1. Load and play Youtube video
2. Long-press popup, background buttons
3. 

### Expected behavior

Any of these:

- A specific and defined secondary action as is common in UI design
- Showing a descriptive label
- Video enqueued as a background play or a popup play

### Actual behavior

Video returns to thumbnail and play button
Video enqueued again

### Affected Android/Custom ROM version

Android 11

### Affected device model

Samsung OneUI 3.1

**Comment by marcel263** [comment]
@opusforlife2 

dear, did you close the bug because it was fixed? or because your template is holy?

**Comment by opusforlife2** [comment]
Those who violate the template shall be burned in binary hell. The fire doesn't burn hotter. It just turns on and off.

**Comment by marcel263** [comment]
OK
