### ISSUE TITLE
A lag during playing

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#953]
After pausing and resuming a video it lags and there is a mismatch between audio and video.

When trying to pause a playing video it takes some time before the pause button is shown

**Comment by theScrabi** [comment]
This is new. Never noticed this. Have you tried using an external player?

**Comment by Jithendra-V-Kumar** [comment]
No I have Never used External Player

When I Seek A Position Of The Video The Audio Later goes First and Video Comes After That For 5-7 Seconds

**Comment by theScrabi** [comment]
Strange. What android version do you use?

**Comment by Jithendra-V-Kumar** [comment]
Jelly Bean 4.2.2

**Comment by wb9688** [comment]
On what device? If not using the default ROM, could you link the custom ROM
you're using?

**Comment by Jithendra-V-Kumar** [comment]
I Am Using Default Rom

**Comment by Stypox** [comment]
Is #3078 related? Also, is this still an issue?

**Comment by opusforlife2** [comment]
@IamJithendra Is this still an issue with 0.20.0?
