### ISSUE TITLE
Why is MrBeast dubbed in arabic?

### ISSUE THREAD

**Issue by Risto-Stevcev** [TeamNewPipe/NewPipe#9534]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.1

### Steps to reproduce the bug

1. Go to latest MrBeast video: https://www.youtube.com/watch?v=h5NvTTOlOtI
2. Observe that it's dubbed in another language. I found out that it's arabic by going to the youtube desktop website and clicking the dubs to find the one it's using.
3. Observe that other MrBeast videos are also dubbed, but no other channels appear to be. It might be that I'm just not subscribed to channels with dubs, not sure.

### Expected behavior

It plays in English by default

### Actual behavior

 It's dubbed in arabic.

Not sure if it's related to this: #5854

### Affected Android/Custom ROM version

Android 13

### Affected device model

Galaxy Z Fold 3 5g

**Comment by AudricV** [comment]
> Not sure if it's related to this: #5854

If you read this issue and its duplicates, you would have noticed that's the case.
