### ISSUE TITLE
Kitkat users delight? Maybe one final release for this classic?

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#9535]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Totally ignore this but I was thinking as we near the end of the year and one of the biggest setbacks the world has ever seen when got hit by pandemic, I think many millions are now struggling more due to the burdening effect of this event.

Yes, this is not about how all devices including Kitkat still support major apps including Youtube and people can use it without issues but the biggest problem is how resource incentive updates make older devices slower and slower pushing them to unreliability quickly than needed.

If we can support even a single user, than fruits of your hard work will be met with delights and wishes from someone we can never know!

### Why do you want this feature?

I don't know but just feels good about it!

**Comment by opusforlife2** [comment]
O_O

Find us someone, or multiple someones, who can hack on NP Legacy. You'll be met with delights and wishes from not just the entire team and the KitKat userbase, but the Jellybean userbase as well. Not even kidding about this. If you have any developer friends, nag them until they get annoyed and agree to have a look, at the very least.

**Comment by ShareASmile** [comment]
I think AnimePipe has kitkat support but not has a interchangeable database backup compatibility,  earlier bravenewpipe used to support KitKat but now it now supports lollipop as minimum.

Another preunified fork i can recommend with security upgrades of dependencies is
https://github.com/spvkgn/NewPipe/releases

**Comment by opusforlife2** [comment]
@spvkgn You should mention in your ReadMe what the fork is doing. And instead of cloning the official ReadMe, link to it instead. Yours is already outdated. See the AnimePipe ReadMe as an example ^.

**Comment by ShareASmile** [comment]
So here i found one,
https://github.com/bravenewpipe/BraveNewPipeLegacy/releases/tag/v0.23.3-2.0.3
a new repo for Kitkat devices embeded with conscrypt to play SoundCloud on kitkat devices thanks to @evermind-zz :

Read Readme first:
https://github.com/bravenewpipe/BraveNewPipeLegacy#about-this-fork
