### ISSUE TITLE
the title of the trends page changes its name by its url until the results are loaded

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#954]
When I have activated the page option of the kiosk the title of "Contents of the Main Page" is changed in the version 0.11.1 (fdroid) when backing out of the results of search / videos by the URL text of  the page of tendencies for a moment until the results are loaded and then disappears for the original title of trends.

I'm still not sure if this is an error or not. if it's something that an average newpipe user should see…

**Comment by theScrabi** [comment]
It's an error, but it got fixed already. Will be fixed with version 0.11.2
