### ISSUE TITLE
[YouTube] Sending livestream link to NewPipe does not work anymore

### ISSUE THREAD

**Issue by LittleVulpix** [TeamNewPipe/NewPipe#9546]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1) Open youtube app and open either active (ongoing) or archived livestream
2) Click "share" and send it to NewPipe
3) You will get a prompt:
"Unsupported URL"
Could not recognize the URL. Open with another app?

This used to work before. I think it's because now the app links have a /live/ in the link. (i.e. youtube.com/live/<video hash> instead of being youtube.com/watch?v=<video hash>

### Expected behavior

NewPipe should be able to play the video. It used to work but I guess with some recent youtube app update this link changed for livestreams/livestream archives.
I use this as a workaround for the recent youtube change that made it so that NewPipe no longer lists any livestreams (be it archives 

### Actual behavior

NewPipe does not accept the incoming link.

### Affected Android/Custom ROM version

Android 10

### Affected device model

Xiaomi Redmi Note 7

### Additional information

It still works fine for non-livestreams / non-livestream-archives i.e. regular video uploads.

**Comment by vlad-mk** [comment]
URLs with query parameters are not getting recoqnized, like
https://www.youtube.com/live/XXXXXXXX?feature=share

**Comment by opusforlife2** [comment]
Could someone post an example link here?

**Comment by vlad-mk** [comment]
here an example
https://www.youtube.com/live/7Ck-BW97K3M?feature=share

**Comment by opusforlife2** [comment]
Hmmm. The full link isn't being accepted, and shows 0 search results.

The link minus the query parameter is also not being accepted, and shows a few search results.

Basically, the URL isn't being recognised as a valid YT URL.

**Comment by nixxo** [comment]
Same issue here.

Here is the url  https://m.youtube.com/live/F906CTfSq3Q?feature=share

If I replace live with v the URL is recognised and processed correctly so, no problem for the extractor, just the URL is not recognised.

**Comment by javierxio** [comment]
> Same issue here.
> 
> Here is the url https://m.youtube.com/live/F906CTfSq3Q?feature=share
> 
> If I replace `live` with `v` the URL is recognised and processed correctly so, no problem for the extractor, just the URL is not recognised.

Verified this works. Thanks. Hopefully the developers can see this.
