### ISSUE TITLE
{Feature Request} MP3 Download Option 

### ISSUE THREAD

**Issue by Rubbix** [TeamNewPipe/NewPipe#955]
Hello !
Would you add an option in the future verions of the app to download the audio file as .mp3 ?
I mean the MP4 option is good but I had some problems with it when I tried to edit it ..
That's all for now , really appreciate your work , keep it up :D 
Oh and Happy New Year !

**Comment by theScrabi** [comment]
This can not work until we would support ffmpeg.

**Comment by theScrabi** [comment]
Thank you a happy new year to you to 😀

**Comment by wb9688** [comment]
>This can not work until we would support ffmpeg.

Yeah, through an optional separate app.

**Comment by theScrabi** [comment]
right
