### ISSUE TITLE
Interrupted download doesn't resume

### ISSUE THREAD

**Issue by maninthemiddle01** [TeamNewPipe/NewPipe#9558]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. download a file from a slow peertube server

### Expected behavior

Download will resume after server-side errors

### Actual behavior

Download pauses and I have to resume it manually for several times. This is especially unpleasant if it stops multiple times.

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Samsung SM-A520F

### Additional information

It would be nice if NewPipe would automatically resume stopped downloads.

Thank you very much for your awesome program, which I use frequently :)

**Comment by agithubber2** [comment]
This very bug DOES STILL EXIST in version 0.25.2!!
