### ISSUE TITLE
Pop up mode stopped working after few seconds or more

### ISSUE THREAD

**Issue by Munkiiedude** [TeamNewPipe/NewPipe#956]
- [☑ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [☑ ] I checked if the issue/feature exists in the latest version.
Version:0.11.0

I was trying out pop up video mode when browsing apps on Play Store to check out the apps functions. The video played about 5-10 seconds and then the pop up video disappeared. On notification bar still there but I can't pause/play and close (X) it, unless "force stop" or try loading the video in pop up video mode then close it on notification bar. Other than this issue, opening the video directly from main app has no issue.

**Comment by wb9688** [comment]
That shouldn't happen, did it show the crash reporter? Can you reproduce it?

**Comment by Munkiiedude** [comment]
OK, sorry about the check box mistake, I'll try another run.

**Comment by Munkiiedude** [comment]
I did a screen video recording and I'm not very sure how to post it here. Suggestions are welcome though.

Anyways, the bug comes on and off, while playing the video demo from Play Store using pop up mode the video disappeared in a while. I tried a few times more it seems okay. When I drag the notification bar the pop up disappeared and can't exit the app from notification bar.

And that been said, nothing like error report pops up.

**Comment by Munkiiedude** [comment]
Currently uploading the video screeny, can check it out later. Give it another 15-30 mins because it's uploading with mobile data.
https://streamable.com/i0eyy

**Comment by karyogamy** [comment]
Try using 0.11.2, this problem should be fixed in #848:

> - Fixes player not running in foreground when launched externally, causing it to get gc'ed when video is still playing.

**Comment by Munkiiedude** [comment]
Okay, I've updated to 0.11.2. Didn't know there was this update until I check on the Newpipe github. Thanks very much and hopefully nothing unusual breaking the great experience using Newpipe!
