### ISSUE TITLE
YT Trending page is sometimes only displaying only a few videos

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#957]
YT Trending page is sometimes only displaying only a few videos instead of all.

**Comment by TobiGr** [comment]
This happens because we have now several `<ytd-item-section-renderer class="style-scope ytd-section-list-renderer">` items instead of one.
![tends](https://user-images.githubusercontent.com/17365767/34539709-eb2f3d6a-f0d1-11e7-82d4-80b60817cb7b.png)

**Comment by theScrabi** [comment]
fixed
