### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by efarcy** [TeamNewPipe/NewPipe#9579]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.21

### Steps to reproduce the bug

Everyday, I receive notifications for the same videos (for my subscriptions).

### Expected behavior

Before, when a new video arrived, I had a notification, but only once.
I shouldn't receive many times notifications for the same video.

**Comment by opusforlife2** [comment]
Try unsubscribing and resubscribing.

**Comment by efarcy** [comment]
It's always strange. I receive sometimes notifications about videos with title not corresponding to content.

**Comment by efarcy** [comment]
Yes I did. It's better (less often). I will say when i'll have a problem
