### ISSUE TITLE
add more trend pages and add them as default at the start

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#958]
Maybe this is already duplicated but the question is would it be possible to add other youtube trending pages as there are on the main page for computers? I mean trends games, music, etc. also have the possibility of having several of these as predetermined in addition to the main page or the list of subscribers.

**Comment by theScrabi** [comment]
All other pages are simply channes which you can subscribe.

**Comment by wb9688** [comment]
And in NewPipe's settings you can set a subscribed channel as main page.

**Comment by speednroll** [comment]
I do not know if they understood me. I am aware of those options, but what I was referring to was adding more icons here:
![](https://framapic.org/fCZIVYKUflix/sctBsLo2gRWR)
With other trendpages. not a single channel instead of the main trend page.

**Comment by theScrabi** [comment]
Ah I see. Yea would be an awsome feature.

**Comment by speednroll** [comment]
hey, this was not labeled as an improvement
