### ISSUE TITLE
MP3 Download Option

### ISSUE THREAD

**Issue by Rubbix** [TeamNewPipe/NewPipe#960]
- [ ✔ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ✔ ] I checked if the issue/feature exists in the latest version.

Pleasea ad an MP3 download option 
I mean MP4 is good but I can't edit the songs that I downloaded for some reasons (didn't happen when I tried to edit an MP3 file) 
That's it for now :)) ;)

**Comment by coffeemakr** [comment]
Hi, you already opened an issue here: #955
