### ISSUE TITLE
create playlist of all videos in youtube channel in one click

### ISSUE THREAD

**Issue by wayto1000** [TeamNewPipe/NewPipe#9606]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

when we click three dots in top right corner of youtube channel page we can have a option to create plalist of all videos in that youtube channel.

### Why do you want this feature?

when i want to binge watch any youtube channel this type of Feature can be helpful

**Comment by IlmariTamminen** [comment]
> Why not use the Play All button given at the top of the Channel page for this?

This kind of a Play All button would be awesome also for the subscribed videos (I think the menu is What's New in English).

**Comment by AudricV** [comment]
You also have a system uploads playlist for YouTube channels: look at the changelog of 0.24.1 to use them.
