### ISSUE TITLE
Phone screen is unresponsive after it times out on a paused full-screen video

### ISSUE THREAD

**Issue by N5-ETSRv** [TeamNewPipe/NewPipe#9610]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Start any video
2. Make it full screen
3. Pause the video at any time before its end
4. Leave the phone alone for the screen timeout to kick in (2 minutes on my device)
5. Press the power button

### Expected behavior

The phone's screen turns on, showing the lock screen.

### Actual behavior

The screen remains off despite pressing the power button. The phone remains responsive, however: I can make calls (e..g, an emergency call by pressing the power button five times rapidly... oops!), and I can resume the audio of the paused video through my bluetooth headset controls. However, the screen is blank and completely unresponsive, and only a hard reset solves the issue.

### Screenshots/Screen recordings

n/a

### Logs

n/a

### Affected Android/Custom ROM version

GrapheneOS Version TQ1A.221205.011.2022122700

### Affected device model

Google Pixel 6a

**Comment by N5-ETSRv** [comment]
I know that bumping my own issue is frowned upon but I wanted to do it because (a) my account was flagged when I submitted the issue and the issue was hidden until recently, and (b) I wanted to add that I am sure that this issue is specific to NewPipe: I have tasted the same steps with other video-playing apps and in-browser videos and the dead screen occurs only with NewPipe.

**Comment by N5-ETSRv** [comment]
Yes, that is Android 13 with the December security update.

Graphene's implemented the January update since I posted the issue but the problem persists.

**Comment by wodend** [comment]
This is probably actually an OS issue. Here's the thread discussing it for CalyxOS: https://gitlab.com/CalyxOS/calyxos/-/issues/1392#note_1239153784

But it looks like it'sa broader scope (possibly all of Android  13) since people with all sorts of devices/OS's have reported it in the Reddit thread.

**Comment by N5-ETSRv** [comment]
This has not been an issue for quite some time for me. I suspect that wodend was correct that this was an OS issue. I think that it was an OS update that eventually resolved this. Thank you.
