### ISSUE TITLE
[Nightly] Unable to open all links (API 30+ restriction)

### ISSUE THREAD

**Issue by Jean-BaptisteC** [TeamNewPipe/NewPipe#9615]
### Checklist

- [ ] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

nightly-24

### Steps to reproduce the bug

1. Open app
2. Select video
3. Use open in browser button

### Expected behavior

Video link is open in browser

### Actual behavior

Android show toast `No app on your device can open this` and browser is not started with url video

### Affected Android/Custom ROM version

Android 13

### Affected device model

Pixel 6

### Additional information

This bug was detected in this [nightly build](https://github.com/TeamNewPipe/NewPipe-nightly/releases/tag/nightly-24) not on latest release.

This bug impact all links in app openable by browser

I confirm this bug is not present on 24.1 release.
I used Google Chrome like browser in my device.

This bug is maybe caused by this PR #9306

**Comment by plasticanu** [comment]
In newer version of Android, the app can't see external packages. Needs to give a permission in top level of the manifest. For example:
    
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
    </queries>

**Comment by Stypox** [comment]
@plasticanu if you want to open a PR feel free to do so, otherwise I'll do it. In case you do, make sure to include "http" and "market", which might be used in the app. Thanks!
