### ISSUE TITLE
Show 'You are all caught up' dialogue in subscription page

### ISSUE THREAD

**Issue by tvnmguy** [TeamNewPipe/NewPipe#9648]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Show 'You are all caught up' dialogue with a tick mark in a circle at the end of new feed items when scrolled through subscription page.

### Why do you want this feature?

Currently new feed items in subscription page are marked with dimmed dashed lines. Seriously which is little difficult to view for aged and sight problems peoples. So implementation of 'You are all caught up' dialogue in subscription feed is easily noticeable and lot of helpful.

 #9310 Additionally unlike other view mode, in card view mode view for total new feed items is not as great as the other view mode and need more scrolling. So implementation of 'You are all caught up' in subscription page really helps to avoid infinite scrolling.

1: List view mode

<img alt="IMG_20230109_161707" src="https://user-images.githubusercontent.com/116799295/211296603-1c6ba5b6-01ed-4dce-98f4-3fa098086344.jpg" width=334 />

2: Grid view mode

a
<img alt="img_2023_01_09_16_20_19" src="https://user-images.githubusercontent.com/116799295/211296732-a4d39a57-2cb7-4e64-8ca2-3f408849c4e4.jpg" width=277 />

b
<img alt="IMG_20230109_162214" src="https://user-images.githubusercontent.com/116799295/211296814-b94466e3-025c-4115-9c79-df6608981022.jpg" width=277 />

3: #9310 

<img alt="img_2023_01_08_14_57_24" src="https://user-images.githubusercontent.com/116799295/211297003-4ce398cc-e396-48c6-9d47-84fd131ff016.jpg" width=277 />

### Additional information

Inspired from Instagram mobile app

https://user-images.githubusercontent.com/116799295/211297110-cdc17294-8067-4741-8401-8127c802bdc5.mp4

**Comment by tvnmguy** [comment]
> It waits for the user to either tap each new feed item, or close the feed and reopen it.


Yah right, that behavior needs to change.

Currently after feed update progress page the feed remains stay same as before instead of directly going to the new videos position.
This doesn't make any sense because people normally refresh the subscription page for find anything new.

**Comment by Stypox** [comment]
This would not make sense in NewPipe. Getting caught up in a video in NewPipe means watching such video, and if you enable the option to hide watched videos, then such videos would hide automatically. So basically you would be all caught up if there are no videos. And right after refreshing you can already see which new videos were fetched thanks to a dashed border around new items.
