### ISSUE TITLE
Kiosk does not know English content language

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#965]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

YouTube/Trending kiosk does not know `English (US)` and `English (UK)` but several other languages like Turkey, Polish etc.

**Comment by speednroll** [comment]
the same happens to me, it would be good to fix this bug

**Comment by theScrabi** [comment]
England is GB
Also I changed content language to content country because that fits better.

**Comment by theScrabi** [comment]
All right, so I replaced the content language to "content country" since it fits better.
This will also fix the difference between GB and US.

Fix: https://github.com/TeamNewPipe/NewPipe/commit/33d75fd2fb4d22d3d1953f2b42ab4b22df7a1aea

**Comment by TobiGr** [comment]
Perfect.
