### ISSUE TITLE
a small error of translation into Spanish in the themes

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#966]
there is a small translation error in settings> Appearance> Theme>

![](https://lut.im/rbrt7Io51p/sIY3Q9Qq3vSf2IbF)

here it is assumed that one of the subjects is darker than the other, however in Spanish both themes are called equal. you just have to correct it to follow something like "Oscuro" and the blackest theme that says "Negro".

PD: in English the white theme is called "Light" but in Spanish it is badly translated and it says "Ligero" which means lightweight. the best translation would be "Blanco" or "Claro".

**Comment by moshpirit** [comment]
I would go for "Claro" instead of "Blanco"

**Comment by coffeemakr** [comment]
Hi thank you for reporting this issue.
Translations are not done via the web service at [weblate](https://hosted.weblate.org/projects/newpipe/strings/).

It would be nice if you could change the translations directly there. Here are the links for the translations to Spanish:

* [Light](https://hosted.weblate.org/translate/newpipe/strings/es/?checksum=78d395f1566910ed)
* [Dark](https://hosted.weblate.org/translate/newpipe/strings/es/?checksum=4ed0672134ff3b22)
* [Black](https://hosted.weblate.org/translate/newpipe/strings/es/?checksum=422db3fb246c1d11)

Also there is a [contribution guideline](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) which contains some more information.

If you need any help feel free to ask! :)

**Comment by moshpirit** [comment]
OK done! Thank you!
