### ISSUE TITLE
Build Failed in Android Studio.

### ISSUE THREAD

**Issue by AnkitBhaiya** [TeamNewPipe/NewPipe#9670]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Andoid Sudio 2021.3.1

### Steps to reproduce the bug

1. Fork the repository.
2. Clone the Project 
3. Open the project in Android Studio
4. Build the Project
![NewPipe – README md  NewPipe  12-01-2023 11_15_22](https://user-images.githubusercontent.com/76736942/211987743-a601b12f-fb62-49a1-8922-7959289688e5.png)

**Comment by Stypox** [comment]
It was likely a temporary host resolution error. https://maven.apache.org/ works for me. Try again and check whether your internet connection works.
