### ISSUE TITLE
Loading second page of channels makes newpip crash

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#968]
NP crashes because it can not get a channel name.

**Comment by theScrabi** [comment]
Just figured out that the architecture of the ListExtractor is broken.
You may never have to call functions of an Extractor directly. You always use an Collector. This might sound stupid on some pleases, however it is important to keep a consistent architecture design.

**Comment by theScrabi** [comment]
hackfixed ... but ListExtractor will require refactor.

**Comment by mauriciocolli** [comment]
Fixed in https://github.com/TeamNewPipe/NewPipeExtractor/commit/a693c0d61dd8ecfb3c3bfabc3e8f61fc16fa033b
