### ISSUE TITLE
menu to order your channel list

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#970]
add an option to sort by time of seniority or by alphabet the list of channels to which you subscribed

**Comment by tetris4** [comment]
Manual ordering would also be useful, so one can group channels by topic (e.g. music, vlogs, comedy, sport highlights etc)

**Comment by theScrabi** [comment]
Yes true.

**Comment by Tajnymag** [comment]
Bump

**Comment by nekobit1** [comment]
theScrabi mentioned before that his focus is bug fixes lately, not feature requests, so your bump isn't much help, but yeah, we should see this again too

**Comment by Tajnymag** [comment]
@nekobit1 I respect that. The only reason for my "bump" was so the issue doesn't get closed by the stale[bot]

**Comment by Stypox** [comment]
This problem will probably be solved by #2309

**Comment by opusforlife2** [comment]
So it is solved now.

**Comment by wb9688** [comment]
@opusforlife2: I don't think it's possible to see channels in a group (well, except when editing it) in a way that you could open the channels (which isn't possible when editing)

**Comment by opusforlife2** [comment]
Then it's a duplicate of other open issues (can't remember the numbers right now, one of them is my own.)
