### ISSUE TITLE
unable to download to SD card

### ISSUE THREAD

**Issue by mammenj** [TeamNewPipe/NewPipe#971]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by mammenj** [comment]
Below is the error on downloading..
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "en",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.11.3",
   "os": "Linux Android 7.0 - 24",
   "time": "2018-01-07 02:31",
   "ip_range": "183.83.0.0",
   "exceptions": [
      "java.lang.RuntimeException: java.io.IOException: Permission denied\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:350)\nCaused by: java.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\njava.io.IOException: Permission denied\n\tat java.io.UnixFileSystem.createFileExclusively0(Native Method)\n\tat java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)\n\tat java.io.File.createNewFile(File.java:948)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\n"
   ],
   "user_comment": ""
}

**Comment by mammenj** [comment]
Storage permission has been given but not specifically to any mount

**Comment by speednroll** [comment]
this issue is duplicated #720

**Comment by mammenj** [comment]
Thanks, closing.
