### ISSUE TITLE
Weblate

### ISSUE THREAD

**Issue by Ilhamiii** [TeamNewPipe/NewPipe#9713]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Clicking the button to translate NewPipe in Weblate does not open the page.Why is that?

### Additional information

However, there is a problem with this project.

**Comment by TobiGr** [comment]
That's inside weblate. We are not responsible for the website. It's not clear what you mean by "does not open the page". What page? works for me.
