### ISSUE TITLE
"open in browser" does not force to choose app

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#972]
I updated from 0.11.1 to 0.11.3, and now if I make in my android NewPipe to always open videos, I can't open videos in a browser from NewPipe, it just openes the video in NewPipe again!

But earlier on 0.11.1 I coud open videos in a browser from NewPipe, even when it was talled to always open videos whith NewPipe.
Now have to disable "defaults" in android settings for NewPipe to have opportunity to open in a browser.

**Comment by theScrabi** [comment]
Yes I removed the explicide launch of the app chooser. So you will only be able to choose an app when there is no default yet.

Should I make it explicit again?

**Comment by teod0r** [comment]
Yes, please.

**Comment by theScrabi** [comment]
fixed.

**Comment by teod0r** [comment]
I think that it happens again.

**Comment by teod0r** [comment]
yes, this happens again
