### ISSUE TITLE
the background player sometimes closes alone and doesn't let any error message

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#973]
so far everything has worked very well in this version of newpipe (0.11.3), except that sometimes when I open the channels I receive an error message that always I sent the logs by mail. but lately when I'm a long time listening to my playlist in the background it just goes away and I do not get any error message.I have to reopen the app and select all my music again and again. 😐

**Comment by theScrabi** [comment]
The problem with the channels is fixed, tho that with the player is new.

**Comment by theScrabi** [comment]
I can not confirm yet :/

**Comment by speednroll** [comment]
It happens to me very often and unexpectedly. this before didn't happen to me (except in much earlier versions)

**Comment by speednroll** [comment]
Good news, it seems that this error did not happen again after updating to 0.11.4. you can close the problem, if I discover any news related to the past problem I report it here anyway.
by the way, I do not know because I have the feeling that this problem was related to the fact that newpipe always crashed when changing pages in the channels

**Comment by speednroll** [comment]
Funny, it just happened again :expressionless: it seems a joke

**Comment by theScrabi** [comment]
This is strange :/

**Comment by speednroll** [comment]
I'm not sure, but I think this problem is related to how many tasks I keep open in my android. for example, sometimes I get to have the exaggeratedly 300 tabs open in my firefox and minimized games :joy: but no music player closes unexpectedly except for newpipe

**Comment by speednroll** [comment]
This has not happened to me again, but because I do not leave so many programs open while I use newpipe. the strange thing is that other music applications work without problems even having a long stack of programs

**Comment by justanidea** [comment]
Couldnt we make the queue save itself in a file? It would have even more good points :
- The user could start again the queue from where he was if he deleted the background notification (or after the crash), or if he wants to come back where he was, some hours after (it would also justify the background player's launching when headphone button is clicked,  bcs for now you only obtain an empty notification and its quite counter intuitive)

**Comment by Stypox** [comment]
@speednroll is this problem still happening lately?

**Comment by gkeegan** [comment]
@stypox I suspect this might be a Huawei issue that requires battery optimizations to be turned off.
