### ISSUE TITLE
Tapping on "Open in Browser" for website in the About page leads to a broken webpage

### ISSUE THREAD

**Issue by slyscorpion** [TeamNewPipe/NewPipe#974]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

If you go to the About page in NewPipe 0.11.3 and tap "Open in Browser" for the website then you are taken to this link https://newpipe.schabi.org which leads to a 502 bad gateway error

**Comment by slyscorpion** [comment]
Screenshot of the bad gateway error:

https://i.imgur.com/U76rffw.jpg

**Comment by TobiGr** [comment]
Thank you vor this report. The link is correct. It looks like we have a problem with the served.
@theAssassin  helps us with hosting the website. Can you please take a look at this?

**Comment by TheAssassin** [comment]
There was an upgrade which killed a few Docker containers, and unfortunately NewPipe was one of them which didn't get restarted automatically. I've changed the container configuration to auto-restart in the future. Thanks for reporting.

**Comment by slyscorpion** [comment]
No problem! Everything works now.

**Comment by TheAssassin** [comment]
I should've been notified by the way, but the upgrade also took the monitoring offline. I was fixing the problems already when @TobiGr pinged me. Fixing stuff at the moment.
