### ISSUE TITLE
Firefox Bookmarks

### ISSUE THREAD

**Issue by Sirove** [TeamNewPipe/NewPipe#975]
Bookmarks which were added via NewPipe to Firefox don't save any information (no bookmark name) about the video expect the plain link (https://www.youtube.com/watch?v=bMQJPsZsL00) without the name of the video (Seth Meyers' Monologue at the 2018 Golden Globes).

**Comment by coffeemakr** [comment]
This could probably be resolved by adding a [`Intent.EXTRA_SUBJECT`](https://developer.android.com/reference/android/content/Intent.html#EXTRA_SUBJECT) to the share intent.
