### ISSUE TITLE
Newpipe time machine for android.

### ISSUE THREAD

**Issue by KaineRecycler** [TeamNewPipe/NewPipe#9759]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hi my name is Kaine Dube and I want to submit a new newpipe app project that allows users to search and watch past deleted unlisted current private content based for the youtube api data application please so i want to ask a few major requirements for this new newpipe app for android so this app will have a date year changer on the top right corner and the rest of the app will have the same  newpipe layout like for the current newpipe app and for the license under between newpipe and newpipe legacy software license for my app project that I want to submit to you guys at newpipe for the help from you guys of how users can easily find and watch lost deleted removed content from within using this app.

### Additional information

So for my examples of my new app for android e,g
Time traveling, 
Youtube, archive, 
Past,deleted, unlisted, private, 
Youtube video and channel archive,

**Comment by test2a** [comment]
Why you release this as a new separate app? People will use it and maybe in time merge that with newpipe itself?

**Comment by KaineRecycler** [comment]
Test2a well for my app that I want to submit to you so i want this separately from the current newpipe app so this will work out for all of the current private past deleted unlisted content that is within the youtube data api for my newpipe time machine app for android so once when you selected the right date year from the date year changer it will focus on the content that you are currently using for your interface and operating layout for between newpipe time machine and newpipe time machine legacy but for right now I have to say that I want my app to be separately from the current newpipe app please.

**Comment by test2a** [comment]
Great. Please do. This sounds like a nice thing

**Comment by KaineRecycler** [comment]
Oh I have one more question to make.
Can you please be able to pass my information to your team at newpipe to see if you could start making it or developing it on this promise so that I can use it for my Samsung galaxy android tablet that I am currently using please.
