### ISSUE TITLE
Layout changed after upgrade to v.0.25.0 from 6 to 4 thumbnails per row !

### ISSUE THREAD

**Issue by intraxit** [TeamNewPipe/NewPipe#9763]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

Upgrade tolatest version

### Expected behavior

Keep layout as in v0.24.1.

### Actual behavior

I cannot go back to v0.24.1
Uninstalling and installing v.0.24..1 is throwing an error !

### Affected Android/Custom ROM version

Andoid v5.1

### Affected device model

Tablet 10.5 inch

**Comment by intraxit** [comment]
Screenshot uploaded to github.

😇❣Bye

**Comment by intraxit** [comment]
Op do 9 feb. 2023 18:02 schreef opusforlife2 ***@***.***>:

**Comment by intraxit** [comment]
![Screenshot_2023-02-09-18-32-03](https://user-images.githubusercontent.com/11077298/217898644-ba0b29b0-cf4a-43c3-85b2-1dd984a66862.png)

**Comment by intraxit** [comment]
Will do so...

😇❣Bye

**Comment by intraxit** [comment]
Shouldn't I be able to go back to v0.24.1 if I did not like the bigger
layout?
Well it doesn't work!

😇❣Bye

**Comment by intraxit** [comment]
Tried yesterday and got an error. Will try again and share it...

😇❣Bye

**Comment by intraxit** [comment]
Exception in Newpipe v0.24.1 after uninstalling v.0.25.0 and reinstalling
v0.24.1

{"user_action":"ui error","request":"ACRA
report","content_language":"nl-NL","content_country":"NL","app_language":"nl_NL","service":"none","package":"org.schabi.newpipe","version":"0.24.1","os":"Linux
Android 5.1 - 22","time":"2023-02-09
20:13","exceptions":["java.lang.IllegalStateException: A migration from 6
to 5 was required but not found. Please provide the necessary Migration
path via RoomDatabase.Builder.addMigration(Migration ...) or allow for
destructive migrations via one of the
RoomDatabase.Builder.fallbackToDestructiveMigration* methods.\n\tat
androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:117)\n\tat
androidx.room.RoomOpenHelper.onDowngrade(RoomOpenHelper.java:129)\n\tat
androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onDowngrade(FrameworkSQLiteOpenHelper.java:194)\n\tat
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)\n\tat
android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)\n\tat
androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)\n\tat
androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)\n\tat
androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:566)\n\tat
androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:555)\n\tat
org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:420)\n\tat
org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:417)\n\tat
io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)\n\tat
io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat
io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:131)\n\tat
io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)\n\tat
io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)\n\tat
io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)\n\tat
io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)\n\tat
io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)\n\tat
androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:47)\n\tat
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)\n\tat
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)\n\tat
java.lang.Thread.run(Thread.java:818)\n"],"user_comment":""}

Bye

Op do 9 feb. 2023 20:08 schreef opusforlife2 ***@***.***>:

**Comment by intraxit** [comment]
Not so nice !

Op do 9 feb. 2023 20:27 schreef opusforlife2 ***@***.***>:

**Comment by intraxit** [comment]
Pls keep old layout (6 thumbnails per row) and small subscription icons for tablets in new version !

**Comment by n-buna404** [comment]
![Screenshot 2023-02-10 181930](https://user-images.githubusercontent.com/68980945/218067573-3216dce8-1c80-4694-b06c-2f1598ccc1d9.png)
Maybe it was related to youtube testing out larger thumbnail.

**Comment by intraxit** [comment]
Nope newpipe changed the grid layout...

😇❣Bye

**Comment by s2r** [comment]
@mahendranv that was a bug and its closed... and this is still a pertinent issue, for a tv user bigger thumbnails is good or at least the option for that, but for a tablet user this is a horrible horrible layout, even basic youtube website has smaller thumbnails and is more compact and if the sidebar is closed i get 5 thumbnails per row, the old layout wasn't perfect but it was way more usable than 4 huge blurry thumbnails with lots of wasted space.

**Comment by mahendranv** [comment]
@s2r I agree. Just pointed out that issue was a duplicate and this one has better description of the issue.

Given that Android's different form factors, a layout might look good in one  while completely unusable in another.

Scalable approach would be leaving the number of columns to the user.

**Comment by realquink** [comment]
Hey everyone, thanks for your hard work. We love newpipe!

I am chiming in to say I have the same issue with 0.25.0. As soon as I upgraded my 1080 TV went from about 6 or so thumbnails per row to now 3. As you can see they are wayy too big now and I have to scroll so much more to view my content vs quick eye scan multiple rows. 

Maybe allow us to choose how many we want per row? Or at least put it back to what was in previous versions. Thanks for reading.

![screenshot](https://user-images.githubusercontent.com/35575102/218341640-1c26dcb3-ac3c-4a79-b3ee-98cd620ee62b.jpeg)

**Comment by Stypox** [comment]
Is https://github.com/TeamNewPipe/NewPipe/pull/9858 a good enough compromise? The thumbnails would still be bigger than in 0.24.1, but no so big as they are now.

**Comment by intraxit** [comment]
Would be much better to be able to set the number of thumbs or tumb
dimensions so screen layout fits any size screen... Just my 2cents!

😇❣Bye

**Comment by Stypox** [comment]
@intraxit please stop suggesting that. There is surely already an open issue proposing the same thing, and apparently nobody has implemented it yet, but we know it would be a good solution. What we are talking about here is just fixing the 0.25.0 regression.

**Comment by s2r** [comment]
@Stypox if its just fixing the 0.25.0 regression, then no... #9858 does not fix it, is it a good compromise? In the sense that it will make me drop the issue? then sorry but also no.

**Comment by Stypox** [comment]
See https://github.com/TeamNewPipe/NewPipe/pull/9858#issuecomment-1445189990. Let's use #3139 to track progress on custom column count.

**Comment by intraxit** [comment]
Not happy either as the original 6 column layout is not restored with this
'fix'!

😇❣Bye
