### ISSUE TITLE
[Android 13+] Missing notification player actions

### ISSUE THREAD

**Issue by benazarenko** [TeamNewPipe/NewPipe#9764]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

Play any song,
Swipe down to see the notification player
Swipe the notification player, or just tap on it

### Expected behavior

Next/previous track buttons, pause/play, repeat, close buttons are visible.

### Actual behavior

Only next/previous track and play/pause buttons are visible. Changing it in preferences does nothing. Not mentioning that I have enough space to have all five of them.

### Screenshots/Screen recordings

<img alt="photo_2023-02-09_15-26-51" src="https://user-images.githubusercontent.com/7333912/217812763-deab4776-c695-4b90-9f66-abf87e144939.jpg" width=270 />

### Affected Android/Custom ROM version

Android 13

### Affected device model

Galaxy M12

**Comment by mendhak** [comment]
Seeing the same on Android 13, Pixel 6. I've got items checked for the player notification under settings, but they don't appear in the notification.

Additionally, maybe it's related, also noticed that the background image of the notification disappears if you switch from normal playing mode to background playing mode. 

![Screenshot_20230212-231721~2](https://user-images.githubusercontent.com/746276/218343292-1a324084-b83e-49b1-878f-3444e4d94b2f.png)

![Screenshot_20230212-231729~2](https://user-images.githubusercontent.com/746276/218343312-b4f82c95-da7d-4ef5-8140-9fd2c7a6d32d.png)

**Comment by gqqjhffr** [comment]
I have this same issue on GrapheneOS on Pixel 4a

**Comment by Graves98** [comment]
Same problem here, on Galaxy S20, Android 13

**Comment by malekairmaroc7** [comment]
I noticed that for example the loop button is missing (Google Pixel 6a; Android 13)

**Comment by dvalter** [comment]
As a temporary workaround, targetSdk can be set back to 32 until transition to PlaybackSession is complete

**Comment by dvalter** [comment]
> This totally depends on the skin (UI). Some skins adapt to the latest Material You guidelines, such as ZenUI, Moto devices, etc which has this issue bydefault. Some UIs like from BBK subsets, completely have their own notification implementation ever since they existed.
> 
> This issue is basically a stall, unless NP decides to comeup with You guidelines.

Now, as mentioned above by @AudricV, it's broken for all UIs that follow Google's A13 reference, so if support something, this is the most reasonable thing to support

**Comment by em-mw** [comment]
> I don't think, this is exclusive to Android 13. My Tecno Spark Go running on Android 12 face the same bug

I am also facing this problem on my pixel 6 with graphene os (custom rom). I remember it worked fine untill I updated newpipe. I think I updated to 0.23 (long time ago) and till this day I still don't have the additional actions in the notification.

**Comment by PaulWoitaschek** [comment]
I can probably help. Can you link in Code, where the custom actions are set up?

**Comment by AudricV** [comment]
Player notifications are created currently in a custom way in the [`NotificationUtil` class](https://github.com/TeamNewPipe/NewPipe/blob/4201723d10a2f5f2add4e893297e8ca8b3ef21d5/app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java).

Also, keep in mind https://github.com/TeamNewPipe/NewPipe/issues/9764#issuecomment-1424263109. This mean the UI of the player notification settings needs to be adapted.

**Comment by maringuk14** [comment]
Please help, I can't use the notification player like the op says.

**Comment by maringuk14** [comment]
Okay, it's been six months since this was reported and nobody has fixed it, I think I'm going to downgrade the firmware on my phone, peace out guys.

**Comment by em-mw** [comment]
> Okay, it's been six months since this was reported and nobody has fixed it, I think I'm going to downgrade the firmware on my phone, peace out guys.

Yeah, I feel like newpipe has also been slacking off recently. Although I used to like newpipe, LibreTube is staring to look like a better option. Not only is the UI better, but it is a lot less buggy than newpipe (seriously, like almost half of the time newpipe crashes when I rotate my device, scroll through, or even when I look at it wrong).

**Comment by DavidTV4** [comment]
> ### Checklist
> 
> - [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
> - [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> - [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
> - [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
> - [X] This issue contains only one bug.
> - [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
> 
> ### Affected version
> 
> 0.25.0
> 
> ### Steps to reproduce the bug
> 
> Play any song,
> Swipe down to see the notification player
> Swipe the notification player, or just tap on it
> 
> ### Expected behavior
> 
> Next/previous track buttons, pause/play, repeat, close buttons are visible.
> 
> ### Actual behavior
> 
> Only next/previous track and play/pause buttons are visible. Changing it in preferences does nothing. Not mentioning that I have enough space to have all five of them.
> 
> ### Screenshots/Screen recordings
> 
> <img alt="photo_2023-02-09_15-26-51" src="https://user-images.githubusercontent.com/7333912/217812763-deab4776-c695-4b90-9f66-abf87e144939.jpg" width=270 />
> 
> 
> ### Logs
> 
> _No response_
> 
> ### Affected Android/Custom ROM version
> 
> Android 13
> 
> ### Affected device model
> 
> Galaxy M12
> 
> ### Additional information
> 
> _No response_

davidkalas732@gmail.com
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.getName()' on a null object reference
	at us.shandian.giga.service.DownloadManagerService.notifyFailedDownload(DownloadManagerService.java:480)
	at us.shandian.giga.service.DownloadManagerService.handleMessage(DownloadManagerService.java:271)
	at us.shandian.giga.service.DownloadManagerService.$r8$lambda$WAroGLCfL9JHoqbHKi33kqWAws0(DownloadManagerService.java:0)
	at us.shandian.giga.service.DownloadManagerService$$ExternalSyntheticLambda2.handleMessage(R8$$SyntheticClass:0)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>

**Comment by aminelazz** [comment]
Any news about this?

**Comment by nico-abram** [comment]
Would the fix here be adding [PlaybackState.CustomAction](https://developer.android.com/reference/android/media/session/PlaybackState.CustomAction)'s to the list returned by [PlaybackState.getCustomActions()](https://developer.android.com/reference/android/media/session/PlaybackState#getCustomActions()) ? Maybe also removing ACTION_SKIP_TO_PREVIOUS and ACTION_SKIP_TO_NEXT from the supported actions list to force it to use the custom actions for actions "2" and "3" too? Sorry, I'm not familiar with these APIs at all.

Alternatively,

> For apps that don't target Android 13 or those that don't include a PlaybackState, the system will display controls based on the Action list added to the MediaStyle notification as described in the previous paragraph. 

Would it be acceptable to not set the PlaybackState at all, in which case (If I'm reading these docs right) it will fall back to the same old behaviour?

I might mess around with this a bit if I can get it to compile and a dev env set up.

**Comment by nico-abram** [comment]
Got it to compile, realized the session playbackState is managed by exoplayer. I think setting custom actions on it then needs to be done on the MediaSession with [MediaSessionConnector.CustomActionProvider](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.html#setCustomActionProviders(com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.CustomActionProvider...)) and implementing [MediaSessionConnector.CustomActionProvider](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.CustomActionProvider.html)

**Comment by nico-abram** [comment]
Just realized exoplayer is apparently deprecated?

> Deprecated.
com.google.android.exoplayer2 is deprecated. Please migrate to androidx.media3 (which contains the same ExoPlayer code).

**Comment by nico-abram** [comment]
I have a patch here https://github.com/nico-abram/NewPipe/commit/7074d8a2b3561b4c4fc42d131754e50689634c45
It's not really clean enough to open a pull request, left a couple comments about the things I thought should be fixed before doing so, but it somewhat works:
![imagen](https://github.com/TeamNewPipe/NewPipe/assets/24706838/736300f3-35a0-45e0-8c18-b7684cf10cde)

If the general approach seems good enough I could clean it up and send a pull request

**Comment by dvalter** [comment]
@nico-abram thank for your attempt, hope it will get merged.

In addition A13 notifications seem to eliminate the whole [at most three controls stuff](https://github.com/TeamNewPipe/NewPipe/blob/6d694518fe1a6747bdb9599394766f996c0ac324/app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java#L154), and the corresponding settings can be removed for A13+ to avoid confusion

**Comment by nico-abram** [comment]
Sent a PR https://github.com/TeamNewPipe/NewPipe/pull/10567

**Comment by Stypox** [comment]
Could you all test whether #10580 works for you? It is based on the work by nico-abram, so many thanks to him!

**Comment by rugk** [comment]
@Stypox Can we get a built APK somehow or so for eas(ier) testing?

**Comment by dvalter** [comment]
@Stypox, works well for me on LineageOS 20 (A13)

**Comment by Stypox** [comment]
#10580 was superseded by #10712, sorry for asking again, but could you test that too? And thanks for testing so far :-)

> @Stypox Can we get a built APK somehow or so for eas(ier) testing?

Yes, the PR description explains how to obtain the APK

**Comment by lawson85** [comment]
The fast forward button, next to the progress bar doesn't function. I'm on a Fairphone 4, Android 13. My NewPipe version is 0.27.2
