### ISSUE TITLE
[Android 11+] Cannot open downloads from the app ("No app installed to play this file" toast)

### ISSUE THREAD

**Issue by GerardEarley** [TeamNewPipe/NewPipe#9771]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.25.0

### Steps to reproduce the bug

1. Download any audio from a youtube video in either .m4a or opus
2. Within the Downloads page tap on the downloaded audio file
3. A notification appears saying 'No app installed to play this file'

### Expected behavior

File should play in assigned player or a notification should appear for a suitable audio player to be chosen

### Actual behavior

A notification appears saying 'No app installed to play this file'

### Screenshots/Screen recordings

![Screenshot_2023-02-09-17-24-01-97_ee8807d2de22f1831269d80920e33a3b](https://user-images.githubusercontent.com/10418107/217899427-48f62a68-5857-48b8-bc68-ecd29cfbb59d.jpg)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Oneplus 10 Plus 5G

### Additional information

In v0.24.1 everything works as expected, it was only when I upgraded to v0.25 that the problem manifests.

I tried installing and uninstalled v0.24.1 and v0.25 a numvber of time to test the issue, and I was able to reproduce it every time.

**Comment by Yowlen** [comment]
I'm running LineageOS 19.1 (Android 12.1) on a OnePlus Nord N200 and since upgrading to v0.25 last night, I get a similar error when trying to play videos using an external player. Mine is a full popup instead of a toast notification and it says there's no streaming apps installed and asks to install VLC.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Got the same error when trying to open a video i downloaded

**Comment by ajay230ps** [comment]
Got the same error for all the downloaded videos. Using Evo X ROM, Android 13. Device Redmi K20 Pro.

**Comment by GerardEarley** [comment]
I don't see any evidence that this bug is device/software specific.

> Got the same error for all the downloaded videos. Using Evo X ROM, Android 13. Device Redmi K20 Pro.

So this bug is not device/software specific then despite that tag being added. I'd be interested to see other peoples device & android versions.

**Comment by GerardEarley** [comment]
As this error has now been reported on multiple devices, by multiple manufacturers running different versions of Android, I think perhaps the "device/software specific" tag should be removed.

**Comment by Yowlen** [comment]
So far, out of all the reports that have specified any details about their hardware and software, the one common factor is that the issue affects Android 12+.

And given it was a known issue for Android 12+ prior to the 0.25 release as per #9758 , it seems to be a safe assumption that the patch(es) generated for the other issue report didn't actually fix the problem, at least not entirely.

So unless someone using an earlier version can specify their Android version and confirm it's also happening to them, the "device/software specific" tag seems accurate enough to me since it only seems to affect specific versions of software, i.e. Android 12+.

**Comment by linucksrox** [comment]
This happens to me on a stock pixel 6a with the latest Android 13 update.

**Comment by darrellenns** [comment]
Same issue here on stock Pixel 5 with up to date stock Android 13. The problem was introduced in newpipe 0.25.0. If I roll back to 0.24.1, it works fine. Upgrading to 0.25.0 breaks it again.

**Comment by Franky1** [comment]
Same behaviour for me, cannot play any audio or video file from the Downloads tab anymore.
Newpipe 0.25.0
Motorola g100
Not rooted
Android 12

**Comment by Stypox** [comment]
Does #9817 fix the issue?

**Comment by czak** [comment]
#9817 fixes the issue for me on Android 11

**Comment by Yowlen** [comment]
It fixes playing via external video player for me, as well.

**Comment by darrellenns** [comment]
#9817 works for me as well.

**Comment by JoshuaKimsey** [comment]
I can confirm this also happens on my Google Pixel 6 Pro running CalyxOS 4.6.0 (Android 13). It worked fine up until the 25.0 update, and now I get the same toast message as the others, saying no app will work with the downloaded videos.

**Comment by AudricV** [comment]
Could you confirm that #9833, which refactor how external intents are made, fixes the issue? Thank you in advance!

**Comment by Yowlen** [comment]
#9833 works for me playing videos using an external player and playing downloaded videos.

**Comment by MarkoIndaco** [comment]
Hallo all, same error for me with videos. Message toast say no player installed and prompt to try vlc. Turning back at version 0.24.1 solve the problem (at least for me).
I'm on Xiaomi Mi 9 Lite - crDroid 8.6 (Android 12 based) - Magisk
Hope can help and keep up the good work 👋

**Comment by GameOverFlowChart** [comment]
I think I have this problem since I updated from Android 12 to Android 13. Or it's a coincidence.

**Comment by brenard** [comment]
This bug is fixed in v0.25.1 for me (Oneplus 7 / Android 12 / OxygenOS). Thanks!

**Comment by MarkoIndaco** [comment]
Is fixed also for me. Anyway I don't understand why my comment was marked as spam?

**Comment by Franky1** [comment]
The new version `0.25.1` fixed this issue for me on Android 12.
Also i don't understand why my previous comment was marked as spam...

**Comment by ashoklathwal** [comment]
https://wealthquint.com/fix-newpipe-no-app-installed-to-play-this-file-63054/
