### ISSUE TITLE
Tablet layout problem

### ISSUE THREAD

**Issue by Angelk90** [TeamNewPipe/NewPipe#9778]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

I simply changed the look of the view mode.

### Expected behavior

The problems are:

Card mode, takes up too much space on the tablet in both modes, works a little better in portrait mode.

Grid mode Vertical, too much space is left both on the sides and in the center.

Another problem is preview image quality too low resolution.

### Screenshots/Screen recordings

Card mode Vertical:
<img alt="Screenshot_20230210-151529_NewPipe.jpg" src="https://user-images.githubusercontent.com/20476002/218115208-22af0ac7-b581-4580-baf0-a21db2a57fb8.jpg" width=381 />

Card mode Horizontal:
![Screenshot_20230210-151655_NewPipe.jpg](https://user-images.githubusercontent.com/20476002/218115239-409013e6-1b31-428d-9f1e-5dd1442817c8.jpg)

Grid mode Vertical:
<img alt="Screenshot_20230210-151726_NewPipe.jpg" src="https://user-images.githubusercontent.com/20476002/218115299-883a9fb7-0c32-4d6d-a4f8-21b7706448f2.jpg" width=381 />

Grid mode Horizontal:
![Screenshot_20230210-151739_NewPipe.jpg](https://user-images.githubusercontent.com/20476002/218115330-2de37ad5-6721-4997-aea1-328f3cb04723.jpg)

### Affected Android/Custom ROM version

Android 10 

### Affected device model

Galaxy Tab A (2016) SM-T585

**Comment by intraxit** [comment]
See my post below. Same story. New bigger layout does not play well on tablets !
Thanks your support...

**Comment by GallusGallu** [comment]
I am experiencing the same issue with the card layout on my Samsung Galaxy Tab A 10.1 (2019), the larger layout serves only to limit the amount of content I can browse through.

New layout:
![Screenshot 25 0 Landscape](https://user-images.githubusercontent.com/125081552/218170346-a17b1f53-389a-4375-92b8-aadaa836d57b.jpg)
![Screenshot 25 0 Portrait](https://user-images.githubusercontent.com/125081552/218170343-bed42a1f-601e-4a52-b4eb-6102ce19fe8c.jpg)

Old layout:
![Screenshot 24 1 Landscape](https://user-images.githubusercontent.com/125081552/218170339-b811d262-f46e-4f86-85bc-065f8be2496a.jpg)

Note that the current portrait card size matches the previous landscape card size - this is consistent behaviour and works exactly as it should. However the current landscape cards are too large, and for consistency should match the size of the portrait cards (subject to aspect ratio).

**Comment by krushia** [comment]
Same problem with subscriptions icons... way too big now.

**Comment by mahendranv** [comment]
> I am experiencing the same issue with the card layout on my Samsung Galaxy Tab A 10.1 (2019), the larger layout serves only to limit the amount of content I can browse through.
> 
> New layout: ![Screenshot 25 0 Landscape](https://user-images.githubusercontent.com/125081552/218170346-a17b1f53-389a-4375-92b8-aadaa836d57b.jpg) <img alt="Screenshot 25 0 Portrait" width="375" src="https://user-images.githubusercontent.com/125081552/218170343-bed42a1f-601e-4a52-b4eb-6102ce19fe8c.jpg">
> 
> Old layout: ![Screenshot 24 1 Landscape](https://user-images.githubusercontent.com/125081552/218170339-b811d262-f46e-4f86-85bc-065f8be2496a.jpg)
> 
> Note that the current portrait card size matches the previous landscape card size - this is consistent behaviour and works exactly as it should. However the current landscape cards are too large, and for consistency should match the size of the portrait cards (subject to aspect ratio).

This is Grid Layout. The item size has been increased for TV experience. Where it was too small to view from distance.

**Comment by mahendranv** [comment]
> Another problem is preview image quality too low resolution.

Should wait for https://github.com/TeamNewPipe/NewPipeExtractor/pull/889#discussion_r1102032293 to get higher resolution icons.
