### ISSUE TITLE
Is anyone else getting extremely slow loading 

### ISSUE THREAD

**Issue by WIMMPYIII** [TeamNewPipe/NewPipe#9779]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Is anyone else getting extremely slow loading?
Menus and videos are taking several minutes to load. Just started yesterday.

### Additional information

Shield TV. Newpipe v24.1 updated to v25 with no change.

**Comment by WIMMPYIII** [comment]
I can't believe no one is reporting on this. Same issue tested and doing the same thing on pixel 2 XL. Menus taking forever to load. Once a video is clicked on it plays fine no buffering or anything. All the lag is in the menu. Video stream is fine.

**Comment by WIMMPYIII** [comment]
I have completely removed and reinstalled on multiple devices.

**Comment by WIMMPYIII** [comment]
Just confirmed it is network related. But I have made no changes to my network. I have fast speeds 1.5gbps. and it is not getting block by my network as it does load, it just takes several minutes. Could my ip be getting throttled or something?

**Comment by feeblor** [comment]
This issue was resolved for me by power cycling my wifi access point.  So it was a local network issue.

**Comment by vehosah** [comment]
I always have this problem no matter what connection I have
