### ISSUE TITLE
Closing popout

### ISSUE THREAD

**Issue by p3lim** [TeamNewPipe/NewPipe#979]
I'm using this mainly to view videos from other apps, and the popout mode is great, but I can't seem to close the video without first going fullscreen, then leaving the full app.
A close button or a swipe action to close would be nice.

**Comment by wb9688** [comment]
There's a close button in it's notification

**Comment by TobiGr** [comment]
You can also swipe the popup to the right side of your screen. This closes it too.

**Comment by p3lim** [comment]
> There's a close button in it's notification

Thanks, although not as convenient as gestures or a dedicated button.
> You can also swipe the popup to the right side of your screen. This closes it too.

First thing I tried, doesn't seem to work for me atleast (EMUI 8, Oreo 8.0).
The only "gestures" that seem to work (basically swiping) is moving the popout up/down on the screen.
