### ISSUE TITLE
Feature request: link sharing on fc, and other messenger, stream on TV screen. playing in background

### ISSUE THREAD

**Issue by landscape69** [TeamNewPipe/NewPipe#98]
at the moment newpipe works fine but missing some features.
its not possible to share the link to other Messenger or media like TV .

in addition to this is not possible to play up a play-list in background so i could listen to music or a film at working on screen with other program.

it would be nice if this will be implement.

thanks

**Comment by medavox** [comment]
Background play has already been requested [here](https://github.com/theScrabi/NewPipe/issues/28) and [here](https://github.com/theScrabi/NewPipe/issues/63). So you're right, we do need this :) All in good time though. I may even try implementing this myself, once I'm done with timestamps.

Also, sharing: https://github.com/theScrabi/NewPipe/issues/84

**Comment by theScrabi** [comment]
In order to play playlists np would need to have playlist support in the first place. This will come, but it will take a while.

**Comment by coffeemakr** [comment]
I think this issue can be closed since both sharing link and playing playlists in the background is implemented.
