### ISSUE TITLE
App/UI crashed

### ISSUE THREAD

**Issue by antuketot76** [TeamNewPipe/NewPipe#982]
Im facing the apps crashing when try to download video as mp3 format.
See attachment for the error report.

<img src="https://user-images.githubusercontent.com/33280865/34812861-26436b48-f6da-11e7-9c26-b0308e8dbfad.jpg" width=350px/>

**Comment by theScrabi** [comment]
The screenshot of an error does not tell us much. Please give us an url to the video.

**Comment by coffeemakr** [comment]
Did you try to save the video to the SD-Card? This would be a known bug.

**Comment by TobiGr** [comment]
Closing due to missing reply of @antuketot76
