### ISSUE TITLE
update automatically notification

### ISSUE THREAD

**Issue by TheGoldmasterCorporation** [TeamNewPipe/NewPipe#983]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

What would be useful is if say the app can let users know if there is a new update and update automatically without having to go though fdroid

**Comment by speednroll** [comment]
it's a pity that F-Droid does not update its repositories more often

**Comment by theScrabi** [comment]
I see. The problem herr would just be that fdroid is signing their apps differently. We could offer auto update only to the download version.

**Comment by speednroll** [comment]
would not be bad. even instead of implementing that option within newpipe it could be more like an extension, like a separate apk that you could also download from the same f-droid :grin:

**Comment by coffeemakr** [comment]
I think this a good idea. It could be done by using two build flavors:
 1. F-Droid flavor without updater
 2. Github flavor with updater

The Github build could be done by Travis using an encrypted keystore file which guarantees the same signature.

**Comment by drfunkencluck** [comment]
i dont think sperate apk would be ok because there would 100 different versions across the web. so if new pipe can check for updates then download and install then ok. proving the signature is ok it would work

**Comment by ale5000-git** [comment]
It could simply detect what signature is used and do the update check only if signed by theScrabi

**Comment by theScrabi** [comment]
That would not work, because android will delete all data created by an app if the app was reinstalled with another signature.

**Comment by speednroll** [comment]
I repeat that it would not be bad to put in f-droid a "downloader/updater" of the latest version of newpipe (with the signatures that the github version has, of course)

**Comment by speednroll** [comment]
something like this:
![](https://framapic.org/ab6Gczc8cg4n/rVvUVp4AddlW)

or this:
![](https://framapic.org/j5LfJBlyYrC3/ElIJUQUId8nG)

**Comment by ale5000-git** [comment]
@speednroll
Do not get me wrong but it is the most stupid thing that can be done.
It can be inside the same apk with a simple option.

**Comment by speednroll** [comment]
As you say, it was just an idea, anyway maybe the best idea is that of @coffeemakr

**Comment by ale5000-git** [comment]
Yes, but the code could be made even more smarter to choose at runtime if execute or not.

**Comment by theScrabi** [comment]
I agree, coffeemakrs idea the best. This could also be combined with an updater.

**Comment by TheGoldmasterCorporation** [comment]
maybe to keep it simple why not say check for a new link from fdroid on load and if there is a new apk then newpipe downloads the apk from fdroid and installs it then removes the downloaded apk file? simple.

**Comment by ale5000-git** [comment]
For me it only look like a complication.
If "Reproducible Builds" are used then the GitHub version and the F-Droid version will have that same signature, and a simple option to toggle on/off the internal update check could be added (that will work also in the F-Droid version that will be the same in this case).

**Comment by theScrabi** [comment]
I see. I think wee need to do this.

**Comment by Stypox** [comment]
This has been added
