### ISSUE TITLE
[FEATURE REQUEST] Share-open with background mode on Youtube app

### ISSUE THREAD

**Issue by oceanwaves90** [TeamNewPipe/NewPipe#984]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When sharing a video in Youtube app, I want it possible to open the video directly with the background mode~!

**Comment by theScrabi** [comment]
Isn't there a switch in the setting that when active the video plays automatically when opened through share.

**Comment by mauriciocolli** [comment]
@theScrabi he means to open in background.

Duplicate of #643
