### ISSUE TITLE
Re-evaluating the use of Kotlin now that minSdk is 21

### ISSUE THREAD

**Issue by csclm** [TeamNewPipe/NewPipe#9846]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hi, I saw in CONTRIBUTING.md that NewPipe is mostly Java for the time being

The [commit](https://github.com/TeamNewPipe/NewPipe/commit/6e576a165c44ac41d769763042acded30bbbc7d4) that originally added this recommendation mentions that once minSdk is 21 or higher it may be reasonable to use Kotlin to leverage Jetpack libraries, particularly Compose and Lifecycle

minSdk was bumped to 21 in [this commit](https://github.com/TeamNewPipe/NewPipe/commit/e55e79bcca44d831dfd951d0c96f222540c00525) a little while back, so I was wondering: have we re-evaluated our stance on Kotlin given this change?

**Comment by Stypox** [comment]
Yes, we are considering switching to Kotlin and in particular to Jetpack Compose. We will open an issue ourselves for tracking progress, when/if it will be the case :-)
