### ISSUE TITLE
[FEATURE REQUEST] Add to a local playlist

### ISSUE THREAD

**Issue by oceanwaves90** [TeamNewPipe/NewPipe#985]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

How about adding videos to a local playlist and opening the playlist just as music player apps do?
And it can be configured shown on the main screen

**Comment by theScrabi** [comment]
@karyugami is currently working on that.

**Comment by oceanwaves90** [comment]
Thanks! I'll try it out!:)
