### ISSUE TITLE
Video and audio playing glitch

### ISSUE THREAD

**Issue by Mortimer-Kerman** [TeamNewPipe/NewPipe#9851]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. Play a video that has this problem (in background or not), I found the problem in two videos:
https://www.youtube.com/watch?v=IGLVMBTIAPE after 8:55

https://www.youtube.com/watch?v=4es-uJRHjGU during the 10-20 first seconds

### Expected behavior

The video/audio should play normally

### Actual behavior

The video/audio have cuts and skips seconds (for example in the first video after 8:58 the video reaches the end in less than 5 seconds instead of 22 seconds and in the second video if you pause at 10 seconds the advancement bar will update at 18 seconds)

### Screenshots/Screen recordings

First video:
https://user-images.githubusercontent.com/50913068/221051102-62c43177-3fd4-4d3f-bbcb-f55bdbb99653.mp4

Second video:
https://user-images.githubusercontent.com/50913068/221051169-924226ec-59d2-4f61-ab7e-ae6c4b39dad6.mp4

### Affected Android/Custom ROM version

Android 10 / EMUI 10.0.0

### Affected device model

Honor 8X / JSN-L21

**Comment by AudricV** [comment]
Please check whether you enabled the skip silence function in the playback speed settings. If that's the case, unchecking the option and pressing OK on the dialog should fix your issue.

**Comment by Mortimer-Kerman** [comment]
> Please check whether you enabled the skip silence function in the playback speed settings. If that's the case, unchecking the option and pressing OK on the dialog should fix your issue.

My bad I'm so stupid it plays normally now

**Comment by marscher** [comment]
I'm pretty sure I did not enable silence detection by myself (I can also be wrong). However I blamed bluetooth audio stack in the first place for like lost frames. Finally I found this very simple solution. Thanks for the "stupid" report :+1:
