### ISSUE TITLE
[Android 11+] Cannot use external player

### ISSUE THREAD

**Issue by Arijeet-17** [TeamNewPipe/NewPipe#9854]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1.Navigated to settings and then video and audio subsection.
2.Scrolled down to use external player option.
3.Upon checking it,it gets enabled.
4.Now upon opening a video in any of the resolution,a dialogue box pops in saying that no stream player has been found and prompts to install vlc.

### Expected behavior

In the earlier versions,it worked well and appropriately opened the media player and streamed the video very well however in the latest version, it's broken.

### Actual behavior

Despite having two different media player,it doesn't work anymore 

### Affected Android/Custom ROM version

Android 11

### Affected device model

Oppo A9 2020

**Comment by Stypox** [comment]
Does #9850 fix the issue?

**Comment by Arijeet-17** [comment]
Ummmm....I don't wanna play it in browser rather I wanna play it in vlc (I have it installed) yet when I click on ok in the choose resolution tab......it prompts to install vlc......earlier it used to detect vlc

![Screenshot_2023-02-24-15-44-20-37_ee8807d2de22f1831269d80920e33a3b](https://user-images.githubusercontent.com/122293067/221153372-5477c5c7-6f1a-4ef0-b9a5-d28baff52280.jpg)
![Screenshot_2023-02-24-15-44-14-17_ee8807d2de22f1831269d80920e33a3b](https://user-images.githubusercontent.com/122293067/221153399-ba419108-d2fb-4021-a212-d2173ad216ff.jpg)

**Comment by Arijeet-17** [comment]
Thank you sir !

It did solve the issue.

**Comment by Stypox** [comment]
This will be closed when a new version is released
