### ISSUE TITLE
[Feature request] Sharing the title of a video

### ISSUE THREAD

**Issue by moshpirit** [TeamNewPipe/NewPipe#986]
Is there any way to select the title of the video? Right now it's just a bar that you can push to open the description box but it would be fine if we can hold press the title in order to select the words and copy it.

Also, what about including the title when sharing the video? Let's say I want to share it with GNU social using Twidere, or Mastodon using Tusky, it would be great if instead of just sharing the link would also appeared the title of the video like it happens with other websites, but maybe that's about the other apps?

**Comment by theScrabi** [comment]
The next version v0.11.4 will also send the title when sharing a video.

**Comment by moshpirit** [comment]
Great!! Should I close the issue then or should I leave it open because of "the ability to copying the title" feature?

**Comment by theScrabi** [comment]
No lets close it.
