### ISSUE TITLE
Newpipe slow downloads (yt-dlp fix needed)

### ISSUE THREAD

**Issue by dewijones92** [TeamNewPipe/NewPipe#9868]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. in newpipe navigate to https://www.youtube.com/watch?v=XWKHA8fAv9k
2. Download the 128kbps m4a audio

### Expected behavior

It should download at multiple MB per second

### Actual behavior

It downloads at around 100kB/s

### Affected Android/Custom ROM version

Android 13

### Affected device model

Pixel 4a

### Additional information

This slowness is caused by a recent update to youtube.
yt-dl has come up with this fix https://github.com/yt-dlp/yt-dlp/commit/5038f6d713303e0967d002216e7a88652401c22a

Is a similar fix being worked on for newpipe? If not then I am willing to do it?

thanks

**Comment by tusch001** [comment]
Also true for video downloads. I can reproduce this with now more than 40 downloads (audio and video),
Android 11 in Waydroid Container on VollaX with Ubuntu Touch
NewPipe version 25.0, older versions were ok,
Network speed is around 300 MBit / s, download starts with 2 - 3 MB / s and within seconds it's down to around 30 kB / s, eventually the download will finish after hour(s).
Don't know if related: the processing after finishing the download (in German: "Nachbearbeitung") also takes a very long time compared to previous versions.

**Comment by Scoojo** [comment]
I also have this issue.. but for video..
Some video downloads slow to a crawl at around 80%.
Takes she's to complete and i have to pause and restart, then wait..

**Comment by lovelilke** [comment]
I have the same problem, download songs with the extractor or even fail

**Comment by AudricV** [comment]
YouTube reverted the `Range` HTTP header throttling, so this issue doesn't need to be fixed. Closing as fixed.

Note: other ways of YouTube throttling downloads are different issues and most of them should be fixed by #9948.
