### ISSUE TITLE
[FEATURE REQUEST] Integrated player for downloaded videos.

### ISSUE THREAD

**Issue by the-mentor** [TeamNewPipe/NewPipe#987]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

1) I would like to be able to play downloaded videos via the NewPipe video player so I can get all the features that it brings like background playback/popup/adjustable play speed etc.
2) I would like a download button on the video list so I can download a videos without going into them individually.

Thanks!!

**Comment by theScrabi** [comment]
Maybe we could make the NewPipe player available though an external app.

**Comment by r2308145** [comment]
All these feature requests are great, dont take me wrong, but first of all, I would like to keep NP simple as possible.

**Comment by ale5000-git** [comment]
There was another request that can be merged.
The one that ask to make NewPipe be seen as player to allow it to be controlled by buttons (in this case it can also function to play downloaded video I think).

**Comment by Stypox** [comment]
Duplicate of #478
