### ISSUE TITLE
loading feed notification never disappears

### ISSUE THREAD

**Issue by louis-vgn** [TeamNewPipe/NewPipe#9879]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. Refresh the feed by swipping down

### Expected behavior

 Reload feed and "loading feed..." notification disappears.

### Actual behavior

"Loading feed..." notification does not disappear

### Screenshots/Screen recordings

`
<img alt="20230302_214339" src="https://user-images.githubusercontent.com/75619262/222641033-ca5b5594-7bdb-4e0e-82c6-169fe9d8986a.jpg" width=292 />
`

### Affected Android/Custom ROM version

Android 9

### Affected device model

Samsung Galaxy S8

**Comment by Inventhrice** [comment]
+1 to this issue, I am also encountering it on a Samsung Galaxy S8. I can't swipe the notification away, but it is also important to note that refreshing feed still works. The notification is just stuck at 20/28 loaded.

**Comment by Inventhrice** [comment]
Update: I just tried uninstalling and reinstalling the app and that fixed it lol. Remember to backup all your settings though because I forgot to 😔.

**Comment by louis-vgn** [comment]
I did that too, but after a while the issue comes back. For now I’ve just been dealing with it.

**Comment by Inventhrice** [comment]
Darn, alright! I'll keep an eye out for it, thank you for letting me know!

**Comment by Inventhrice** [comment]
Not to reopen a dead issue, but for those who are looking for an answer I think I might've found it. For the Samsung Galaxy S8, turn off "Put app to sleep" under Settings > Device Care > Battery > NewPipe
