### ISSUE TITLE
[Issue request] Sort the different new videos in the feed page

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#988]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

Hi, I just wanted to know if it could be possible to add more possibilties on the feed page :
- create your own "playlist feed page"/"whats new", or something like that, to make a feed page for your new music channels for example, or whatever you want (so you have different personnalized pages where you see your videos)

- Please try to do something else with "whats new", make available to sort the new videos of the channels you subscribed,  like in youtube btw, but you can choose to sort it according to the date of upload, or alphabetical order... and not only see the channels in the order where you subscribed 

I hope you understood what i have tried to explain, and i hope this app is going to go higher and higher :)

**Comment by speednroll** [comment]
create a playlist is in process for next versions of newpipe, has already been requested in # 870. and the order of the subscription list has also been requested here #970
