### ISSUE TITLE
[Feature request] More icons/buttons at the top of the main page

### ISSUE THREAD

**Issue by wralach** [TeamNewPipe/NewPipe#989]
Currently, there only two buttons/icons at the top on main page (trends + abos).
It would be great have have further icons for faster access. E.g.: "downloads", "history", "settings"

**Comment by theScrabi** [comment]
Yea it would be great if you could customize that

**Comment by moshpirit** [comment]
I would really like to directly hide the tendencies tab. Every time I open NewPipe it's a reminder of how the music I detest it's the most listened around the world :P

**Comment by speednroll** [comment]
@moshpirit The same thing happened to me. 😑 but fortunately there is already an option so that does not appear in the main tab: you go to settings> content> content of the main page> and you touch on blank page

**Comment by moshpirit** [comment]
Awesome! Thank you!!

**Comment by Stypox** [comment]
This has been added
