### ISSUE TITLE
[Bug] 0.11.4 Video list loop.

### ISSUE THREAD

**Issue by Duppadaadadii** [TeamNewPipe/NewPipe#990]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Channel list keeps looping the same videos.
When i scroll down channel list it loops the same videos over and over again.

**Comment by theScrabi** [comment]
not again :/

**Comment by mauriciocolli** [comment]
See #968
