### ISSUE TITLE
Save audio/video download at subfolder(channel's name)

### ISSUE THREAD

**Issue by Turhvjbufv** [TeamNewPipe/NewPipe#9905]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like an option that if I download videos/audio it would create a new folder for the channel(if there isn't one that already exists) and put all the videos/audio that I download from that channel in the folder

### Why do you want this feature?

Why? For order and for it to feel more clean

**Comment by Turhvjbufv** [comment]
> Then you'd have a bunch of folders, with only one file in each folder. I don't see how that improves usability. You now have `n` audio files, and `n` folders, except you have to go through an additional filesystem layer to get to what you want.
> 
> If you had asked for per-channel folders, that would still make sense, because some automatic file organisation would occur.
> 
> Please clarify your request.


I like to add .lrc file to my songs(audio downloads) but if I add them to an already bloated folder (I download a ton of songs) it just makes it more messy but when every song (or every artist songs) are in one folder it's much cleaner and easier to navigate and add .lrc files

**Comment by Turhvjbufv** [comment]
I only download songs from newpipe so it doesn't really matter, then is doing folders by channels as you suggested above is also out of question?

**Comment by Gravemind2015** [comment]
Hi, I was just about to make this feature request. I agree that this might impact usability for people who only download stuff randomly or from diverse sources.
However, it makes sense for users who download more than they stream. For example I've limited bandwidth & data volume, so everything from my subscription list gets downloaded for later consumption, leading to videos from different creators all dumped into the root of the download directory.
What I'd propose would be (if this ever happens), to maybe keep this toggle/feature optional. People who heavily rely on downloader side of the app could then benefit from the automatic sorting of files.
Thanks :-)

**Comment by Turhvjbufv** [comment]
Currently no new features are accepted am I wrong?

**Comment by Turhvjbufv** [comment]
Nice 👍 thanks

**Comment by oddtoddy** [comment]
I know this is old, but the reason I would absolutely LOVE this option is so I could add each folder as it's own individual virtual feed in my podcast app with proper tagging.
