### ISSUE TITLE
[Feature request] RSS feed option to select as watched and load more videos

### ISSUE THREAD

**Issue by moshpirit** [TeamNewPipe/NewPipe#993]
I'm subscribed  to several channels (locally, I don't have a Google account) and in my feed there's some videos I already saw and there's only 16, so I would like to see more videos and hide those which I already saw.

**Comment by salevdns** [comment]
An overlay over the thumbnail of an already watched video that indicates that it has been watched before would be great too.

**Comment by Stypox** [comment]
I think this pr #2288 suits your needs, since it displays playback positions under videos.
And for the hiding-already-watched-videos-from-feed part, I think #2309 will solve your problem by showing videos in order.

**Comment by Stypox** [comment]
Oh... closing since #2288 has just been merged :-D
