### ISSUE TITLE
Need to add another line in some configuration titles

### ISSUE THREAD

**Issue by moshpirit** [TeamNewPipe/NewPipe#994]
I can't see the entire title of some configurations because there's no enough space in the line and need another.

Of course, when I turn my phone from portrait to landscape mode I can see the rest of the sentence.

I'm using it in Spanish.

**Comment by speednroll** [comment]
here the same thing happens to me

**Comment by Stypox** [comment]
This has been implemented:
In long-press menus and in the main player: the text slides
In the info page: the whole title can bee seen by clicking on the description dropdown icon.
