### ISSUE TITLE
Dar me gusta y comentar

### ISSUE THREAD

**Issue by ElPrincipeGlitchJr** [TeamNewPipe/NewPipe#9944]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Quiero que se pueda dar me gusta y comentar a los vídeos que más me gusta porfavor apruebe para de la nueva actualización que están haciendo

**Comment by av01d1ngx4** [comment]
@ElPrincipeGlitchJr Lo siento, no podemos hacer eso porque requiere una cuenta de Google para comentar y agregar software no libre en la aplicación y esto solo tiene como objetivo ser de código abierto, pero la función de dar like puede ser desconocida en este momento.

**Comment by av01d1ngx4** [comment]
@opusforlife2 
Author Translation: I want you to be able to like and comment on the videos that I like the most, please approve for the new update they are doing

My Translation: I'm sorry we can't do that because it requires a google account to comment and to add non-free software on the app and this is only aimed to be open source but the like feature might be unknown at this time.

**Comment by ElPrincipeGlitchJr** [comment]
Ay entonces solo se puede los comentarios sin escribir y dar me gusta solo
se quedan como si fueran de adorno... Me pone triste

**Comment by AudricV** [comment]
@av01d1ngx4 Please refrain from mentioning specific maintainers, we see what's happening on our repositories. Anyway, thanks for your translations.

@ElPrincipeGlitchJr Please only use English when interacting with our repositories.
