### ISSUE TITLE
the three-point menu does not appear when you watch a video with the light theme on

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#996]
I do not know if this has already been requested, but there is a minor error when you see a video in newpipe with the light theme

![](https://framapic.org/2CUlqaO1rmhH/hQzk0Mrupzqn)

simply the three-point menu that is in a corner is black and can not be seen. you have to change it by white

**Comment by theScrabi** [comment]
Confirmed. The menu icons also don't fit.

**Comment by theScrabi** [comment]
fixed
