### ISSUE TITLE
error in project

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [TeamNewPipe/NewPipe#9966]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Could not resolve all files for configuration ':app:detachedConfiguration3'.
Failed to transform FakeDependency.jar to match attributes {artifactType=_internal-d8-desugar-methods, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
Execution failed for D8BackportedMethodsGenerator: C:\Users\test\.gradle\android\FakeDependency.jar.

**Comment by devkhali** [comment]
same error  what we should do ?
if u have any solution please share with me

**Comment by AudricV** [comment]
What are you trying to achieve? Could you please elaborate and give us more details? Make sure to have a clean development environment set (valid JDK and Android SDK corresponding to the versions used by the app), and also try to clear Gradle caches.
