### ISSUE TITLE
New pipe and telegram

### ISSUE THREAD

**Issue by Xcl4m4t10n** [TeamNewPipe/NewPipe#997]
Hello,

I have a little issue with new pipe. When I enter on a video and I want to share it through Telegram it show me an error that say unsupported content.

I have installed both new pipe and Telegram through FDroid. I am using lineage OS last version with Sony Xperia z5 compact. It is a known issue?

**Comment by theScrabi** [comment]
Free droid is no official distribution service for newpipe. Please download NewPipe from fdroid, or github. For me the latest version also has no such errors.

**Comment by Xcl4m4t10n** [comment]
Sorry, by Free Droid I mean Fdroid.

**Comment by theScrabi** [comment]
Ah I see. Try running the latest version.

**Comment by TobiGr** [comment]
O can't reproduce this with the latest version. Please reopen if this is still an issue for you
