### ISSUE TITLE
Adding lower qaulity than 144p ( 120p and 96p)

### ISSUE THREAD

**Issue by Offgrid2G** [TeamNewPipe/NewPipe#9984]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Standard | Class | Resolution | Pixels | Aspect Ratio
-- | -- | -- | -- | --
MMS‑Small | 96p | 128×96 | 12,288 | 11:9
QQVGA | 120p | 160×120 | 19,200 | 4:3
QCIF Webcam | 144p | 176×144 | 25,344 | 11:9

The reason I ask because a lot of 2G data company's don't let me watch it at 144p this used to be available on youtube Go but it's no longer supported. So if you could add in 120p and 96p that would be great!

### Why do you want this feature?

I want this 120p and 96p lower quality to be able to work on my slow 2G data! Thanks

**Comment by Offgrid2G** [comment]
MMS-Small, 96p, 128×96, 12,288, 4:3, Lowest size recommended for use with 3GPP video transmitted by MMS to/from cellular phones, ...

**Comment by AudricV** [comment]
That's not possible, we can only provide the streams that streaming services return to their clients.

For YouTube, the lowest resolution available is 144p, so there is no 120p or 96p stream.

If you want something with a lower bandwidth than these streams, set 3GP as the default media format in `Video and audio` settings and select it in the quality list where it's available.

We may also provide in the future the MPEG-4 and WEBM streams which have around 15 frames per second, but they are not available on all videos.

Closing as wontfix.
